### ISSUE TITLE
Out of storage redstone signal.

### ISSUE THREAD

**Issue by AlgorithmX2** [AppliedEnergistics/Applied-Energistics-2#100]
I always wanted to have atleast a redstone signal when my drives run out of types or bytes.
So i could send off a redstone signal to a warning lamp or howler.
I guess the simplest way i can think of to implement this would be an upgrade to an level emitter or something you can make by crafting the level emitter with something.

I'm just shooting the idea out there and maby you guys think it sounds interesting.

Originally Posted by TbbW82

This issue was migrated; For original details see http://ae-mod.info/Tracker/1009/

**Comment by Technici4n** [comment]
Sounds like a cool feature, but I don't think we are ever going to implement it due to limited manpower, and having to figure out a way to make it more interesting beyond just that.
