### ISSUE TITLE
redstone card support for inscribers and other machines

### ISSUE THREAD

**Issue by rickschulting** [AppliedEnergistics/Applied-Energistics-2#1001]
why are redstone card upgrades only compatible with IO ports and import/export bus? Would be really neat to support other AE2 machines as well like the Inscriber.

**Comment by yueh** [comment]
Can you suggest anything they could provide for these machines?

Inscribers do not consume energy, if they are inactive.
Making them redstone controlled does not improve them, just more complex to automate.
If you do not want them to craft, do not insert items in the first place.

**Comment by rickschulting** [comment]
i'd like to control my machines directly, not by controlling the export/import busses. It makes it possible for more compact automation, and less resources.

**Comment by thatsIch** [comment]
If you control them manually, then its not automation *snickers*

**Comment by rickschulting** [comment]
yes it does thatslch, just use ME level emitters. if you've got nothing to add or you've got no solution then dont post :)

**Comment by thatsIch** [comment]
*cries*

**Comment by yueh** [comment]
It does not really add anything new.
You can achieve the exact same behaviour already and just as compact as pointing a level emitter at the inscriber. If not even more compact (and less used resources).

The only thing, which comes to my mind would be making the inscribers emit a redstone signal when done. This would introduce quite some interesting new possibilities.
