### ISSUE TITLE
Wireless Crafting Terminal

### ISSUE THREAD

**Issue by dkudriavtsev** [AppliedEnergistics/Applied-Energistics-2#1003]
I know that this has been requested before, but it would be very convenient to have such a device, that could work with NEI's shift click integration. This would save a lot of work managing inventories, crafting tables, and other stuff. The device could use (and store) twice as much power as the Wireless terminal, and use extra power to craft items.

**Comment by thatsIch** [comment]
WCT is a no go,
we want people to fully utilize the crafting system, even though we can see its usefulness.
