### ISSUE TITLE
Potential stackoverflow in EnergyGridCache

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#1004]
This affects a least `EnergyGridCache.extractAEPower()` as well as EnergyGridCache.injectAEPower()`.

It is mostly a theoretical issue and probably will not show up with normal use, but it is not outside of survival. The log itself is truncated and shows about 500 grids, but I would except that it occurs somewhere between 1k and 2k grids.

A 10x10x10 Cube of cables + quartz fiber connections might be enough.
So not to hard to obtain (1k cables + 3k quartz fiber) after a certain point and can be easily build with something like the BC builder.

The actual issue is the used recursion to visit the grids.
Changing it to a proper BFS/DFS approach using an explicit queue or stack (not the normal call stack) should mostly solve it. Changing it to a proper tail recursion might be also an idea, if possible.

It will also make the world impossible to load the world after the first crash.
But there is not log, just a notice that a stackoverflow occurred during the loading of the dimension.
Other methods beside inject/extract in `EnergyGridCache` are following the same pattern, but this could potentially be located somewhere else.

Obligatory log: http://pastebin.com/KChDsBjs

**Comment by thatsIch** [comment]
* DFS (Depth First Search) 
* BFS (Breadth First Search)

**Comment by yueh** [comment]
I am probably also in favor of a BFS. It feels more logical, if the adjacent grids are handled at first.

A PriorityQueue/SortedSet for the adjacent grids might also be an idea to prioritize the larger consumers first. But keeping it sorted might be an issue.
