### ISSUE TITLE
Naming in inscriber entangled pair ruins connectivity

### ISSUE THREAD

**Issue by gixbit** [AppliedEnergistics/Applied-Energistics-2#1006]
With the advent of double posting issues I believe this is not covered. When i named a paired entanglement with an inscriber. It would not work in  a ring. I searched this issue.

**Comment by thatsIch** [comment]
Cannot reproduce

Setup like this works fine even with two different named entangled singularities

![2015-03-11_16 37 49](https://cloud.githubusercontent.com/assets/2210496/6599981/f98b7950-c80c-11e4-9da6-92d821a251a8.png)

**Comment by gixbit** [comment]
Its on the infinity pack recommended version. Will try this and get back To you.

**Comment by gixbit** [comment]
I think the problem was something I was doing. Also cannot reproduce it now.
