### ISSUE TITLE
Different kind of processing pattern

### ISSUE THREAD

**Issue by gixbit** [AppliedEnergistics/Applied-Energistics-2#1007]
Some recipes have a percent chance to return an item desired. Would it be possible to do something with this minus ingame emitters etc.

**Comment by yueh** [comment]
It is certainly interesting, but mostly impracticable. (But if anyone has solution to solve most problems, feel free to suggest them).

The first issue is how to deal with creating the patterns?
One of the straightforward solution would just be use the stacksize.
For example `1 Iron Ore => 100 Iron Dust + 6 Copper Dust` means you have a 100% chance for iron and 6% for copper.
But then these chances could be excluding. So either iron or copper, but not both
Can maybe be solved with `1 Iron Ore => 94 Iron Dust + 6 Copper Dust`, but this does not define that you are guaranteed exactly one output, it might also be 0 or 2. Both possibilites can simultaneously be used in different machines of the same modpack (or even mod).
Or even more probabilities like `1 Iron Ore => 90 Iron Dust + 10 ( 75 Copper Dust or 25 Gold Dust`, which could mean 90% chance for iron dust or if not that the alternative is copper with 75% chance or gold with 25% chance.
You would probably end up with a GUI similar to SFM or the Pneumaticcraft robots just to define a single pattern. Which would be extremely unusable.


Next point would be dynamically changing chances.
For example the EnderIO machines, running out of their resource will change it and can happen out of nowhere. No free crafting cpus for crafting them, the machine for them is blocked or just out of resources. So either the crafting process would completely stall or you have do define everything into the already unusable GUI for patterns. For example conditions like "it also needs flint, which has a 10% chance to break every operation".


And the most important issue is the probability itself.
It is impossible to guarantee the outcome and our crafting is requiring exactly that.
We can only calculate a amount of items needed to guarantee a single item with x%.

Let us assume the secondary output of processing iron ore has a chance of 10% for copper and we want a chance of 99% for it. This also means every 100th crafting request will not be successful, stall or worse. Consider here how many people are playing it and the huge amount of crafting request they are creating.
But back to the math. 99% chance for an item with 10% chance means we need to process at least 43 iron ore. As 1% of failure is still quite high, we could increase it to 99.9% (65 items) or 99.99% (87).
I leave it for you to calculate things like 99.99% chance for a stack of copper from iron ore.

**Comment by thatsIch** [comment]
I just solved it in my world, by using 

> export until I have X of those items

This helps creating a smaller crafting tree too

**Comment by gixbit** [comment]
Yeah. I was thinking about those implications as i was writing it and i know there are mathematical functions to approximate the required amounts but in use it will fail constantly..

I figured this was impossible at least reasonably.

**Comment by yueh** [comment]
It would have worked with the old AE1 crafting, as this could just loop forever until the requirements are satisfied. The actual probabilites would be even irrelevant, just that they are not guaranteed.
But with all the other issues it had and not being able to know, that you are short by one iron ingot.
