### ISSUE TITLE
Display chest name in the interface terminal

### ISSUE THREAD

**Issue by Jofkos** [AppliedEnergistics/Applied-Energistics-2#1008]

**Comment by yueh** [comment]
I do not see any particular reason to add this specific feature as this would be inconsistent with other TileEntities and put chests into a special place.

The current behaviour is either display the name of the TileEntity (renaming will not change it) or if the interface itself is renamed, then this name as preferred one.

**Comment by Jofkos** [comment]
I though of that, because i export the materials for the in-world-crafting to a chest and eject them then. At the moment this in-world-crafting is displayed as "chest". As long it's only only chest, no problem, but if i've other machines needing a chest i've various "chest" in my interface terminal.

**Comment by thatsIch** [comment]
As yueh said, you can rename the interfaces and they will display their names.

**Comment by Jofkos** [comment]
Sorry :see_no_evil: complety missed that. Thank you!

**Comment by yueh** [comment]
Displaying a renamed tileentity is not even feasible.
A block interface can have up to 5 adjacent TEs, but can only display one name.
Should it be the first TE it finds? The last one? Randomly choosen everytime the GUI is opened?
In most cases probably more confusing than an improvement.
