### ISSUE TITLE
ME Network crashes game.

### ISSUE THREAD

**Issue by BoboSims** [AppliedEnergistics/Applied-Energistics-2#1011]
Playing the latest version of DW20 modpack for FTB. Upgraded from rv2-beta-8 to *rv2-beta-10* about an hour ago.
In only 15 minutes time my game crashed twice on the server side while I accessed the ME Network. First time when I switched on the power, second time while I was storing stuff through the Crafting Terminal.

http://pastebin.com/cFQ2upBa
http://pastebin.com/tzZzp8za

**Comment by yueh** [comment]
Why is the oredictionary reporting null as value..

**Comment by BoboSims** [comment]
I hope you're not asking *me*, @yueh. Because I have no idea, either.

**Comment by yueh** [comment]
Just ranting about Forge and their usual lack of documentation. Because who needs it, if you just can crash.

Fix should be in the next build.

**Comment by BoboSims** [comment]
Ok, I understand. Thank you so much for your effort.
