### ISSUE TITLE
available craft recipe ME Cable

### ISSUE THREAD

**Issue by vobis** [AppliedEnergistics/Applied-Energistics-2#1014]
available craft recipe ME Cable. Version appliedenergistics2_rv0_stable_9_1.7.2 
![screenshot_4](https://cloud.githubusercontent.com/assets/11441369/6618715/7674a4fe-c921-11e4-9b5d-e765ff343e77.png)

**Comment by Cisien** [comment]
Use nei to get the recipe. The recipes on the wiki are for rv1+.

Or update ae2 to a supported version (hint, its rv2)
