### ISSUE TITLE
Sky Stone block remains in world after rapid mining

### ISSUE THREAD

**Issue by ShicKla** [AppliedEnergistics/Applied-Energistics-2#1017]
When mining a Sky Stone block with a pick that has fairly high mining speed, such as from Tinker's Construct, the block will remain in the world. About 4 seconds after mining the block, it will then break and provide it's drop.

**Comment by ShicKla** [comment]
No longer able to recreate bug after starting new session. Most likely a one off glitch, and probably doesn't need to be pursued.

**Comment by XFactHD** [comment]
What you explained above looks like a lag. Did you play on a server or on a single player world?
