### ISSUE TITLE
AE2 rv2 beta 10 - Invisible Blocks/Items (Anything multipart capable in AE2)

### ISSUE THREAD

**Issue by BlackHawkDoesGaming** [AppliedEnergistics/Applied-Energistics-2#1018]
I have installed (1.7.10) Applied Energetics rv2-beta 10 with ae2stuff  0.1.6.14 and Extra Cells 2.2.25B45. And when I place any block/item from AE2 that is multipart capable, like any cable, when I place them, they are invisible, including the interfaces. It also makes Buildcraft pipes invisible, too.
I need a fix, please! :)

**Comment by XFactHD** [comment]
Are you using the latest version of Extra Cells? You could also try it without ae2stuff. In my world with rv2 beta 8 it is functioning but I know that ae2stuff is sometimes pretty buggy.

**Comment by thatsIch** [comment]
Have you tried updating EC first?

**Comment by yueh** [comment]
Also try it without optifine.

**Comment by BlackHawkDoesGaming** [comment]
tryed updating EC, no use, also tryed updated aeStuff, going to try without aeStuff

**Comment by BlackHawkDoesGaming** [comment]
Nope, didn't work, I tryed not using EC, still, nope...
Thanks for speedy request, :)
Also, any explanation for invisible BC pipes 
Examples:
![2015-03-13_23 09 40](https://cloud.githubusercontent.com/assets/10902101/6650415/13ed2cce-c9d6-11e4-8ba7-580573a3307d.png)
This is a Inhalation Plane on a ME Dense Cable

**Comment by XFactHD** [comment]
You can't have plug any cable multipart on a dense cable. Have you tried it without Optifine, it sometimes has this bug even with solid blocks, for example tinkers constructs smeltery bricks.

**Comment by XFactHD** [comment]
You can't plug a cable multipart on a dense cable. Your issue can't be a texture file problem, have you tried it without optifine, it is sometimes even causing problems with solid blocks like the smeltery bricks from tinkers construct.

**Comment by BlackHawkDoesGaming** [comment]
It wasn't optifine, immibis microblocks.
Thanks for the help!
