### ISSUE TITLE
Fuzzy detection on crafting patterns?

### ISSUE THREAD

**Issue by 016Nojr** [AppliedEnergistics/Applied-Energistics-2#1019]
I think it would be nice with fuzzy crafting patterns. One of the reasons being the Division sigil, detecting excactly how many uses it got left leaving it to no use. Maybe implement it as an upgrade for the terminal? Or the pattern itself?

**Comment by yueh** [comment]
AE2 can already calculate how often an item can be used and how many are needed to craft the request. This works for example with the quartz cutting knife or IC2 hammers/cutters.

If this does not work with the Division Sigil, then it probably does not tell the correct values (or none at all). Based on the design decision, I am pretty sure it is intended to not really work outside a vanilla crafting table.

If tools have a limited amount of uses, then you should report that to the mod authors and ask them to please fix it. As we cannt really deal with every possible exception.

**Comment by thatsIch** [comment]
Only the creative division signal (advanced setup) lets you do that. The normal division signal is disabled for automation on purpose.
