### ISSUE TITLE
Increased server tick time when last player leaves The End

### ISSUE THREAD

**Issue by InsaneJ** [AppliedEnergistics/Applied-Energistics-2#1023]
Using appliedenergistics2-rv2-beta-10 we have noticed a huge increase in server tick time after all players have left The End. One of our players has a base there with some AE in it. The server tick time for The End dimension increases to several hundred ms per tick.

As soon as someone returns to The End the tick time drops to around 4ms per tick as if nothing ever happened. Until that player leaves and the tick tme increases again. This behavior can reliably be duplicated.

We ran the WarmRoast profiler to try to find out what's causing the increased tick time. During a period of high tick times we noticed that AE is taking up around 61.36% cpu time.

/forge tps screenshot:
![image](https://cloud.githubusercontent.com/assets/1933471/6652430/bef450aa-ca6e-11e4-9d5e-6c3afa1bb083.png)

Opis screenshot:
![image](https://cloud.githubusercontent.com/assets/1933471/6652431/c8b4a0f4-ca6e-11e4-8e59-094c5f46c72a.png)

Server log:http://happydiggers.net/warmroast/2015-03-14/fml-server-latest.log (9.36MB)
WarmRoast HTML page: http://happydiggers.net/warmroast/2015-03-14/WarmRoast_after_leaving_the_end.htm
WarmRoast screenshot: 
![image](https://cloud.githubusercontent.com/assets/1933471/6652419/2c59cf5e-ca6e-11e4-9727-f3a43dc1f06d.png)

**Comment by yueh** [comment]
Opis reports quite a high number of loaded chunks compared to the forced chunks.
For me it looks like chunks are constantly unloaded/loaded, which then forces AE2 to update the grids.

AE2 itself has no chunkloading. So I would recommend finding the culprit causing it and remove it or force the ME network to be chunk loaded and not be constantly updated.

**Comment by FanaticNinja** [comment]
We have the same issue on our server except its inside world, we also have zero chunk loaders in the modpack. Even when no one is on the server, it will eventually come to a crawl and stop.

Unfortunately I have no profiling data (opis crashes on chisel, warmroast refuses to attatch/load). Ill work on getting some tangible data though to help the cause.

**Comment by InsaneJ** [comment]
Thanks for the input. Will try to find out if there's any mod in particular that's causing chunks to load/unload.

**Comment by halvors** [comment]
Can confirm this, but don't think this is related to Applied Energistics, experiencing the same with nether, except that there is no AE2 stuff there. May be related to TeamCofh mods as they ware in use there.

**Comment by ruifung** [comment]
Chunk thrashing, is a really annoying issue. Which is why chunk loaders are pretty much required for heavily modded servers in my opinion.

**Comment by yueh** [comment]
There is an option under the `/ae` (or was it `/ae2`?) to enable logging loaded chunks (as admin/op).
It should log every loaded chunk to either the console or chat, but I have never used it.

Probably a good starting point, if some chunks are constantly loaded. Use it to look at adjacent chunks, one of the most simple setups to load a chunk is using a hopper facing into a chest placed in another chunk. This will load the chunk each time the hopper tries to insert something into the chest. Now chain this and you can pretty much chunkload with vanilla and some issues with randomly unloaded chunks.
So just 1 (force) loaded chunk can potentially cause a huge area to be constantly loaded/unloaded.

(And I am not sure, if the end also has some chunks loaded by default, like the spawn platform to prevent players from falling through it.)

**Comment by FanaticNinja** [comment]
Thx for the info yueh, the /ae2 chunklogger helped show which chunks were unload/loading constantly, which i was also able to get Opis running to help as well.

For my case, anyone with AE in their homes would chunk thrash (for ~10 minutes) the second they would leave their homes. I haven't tested an area with an AE exclusive setup though, so i wouldn't place blame.

At least in my case, i've solved this issue with the Cauldron config load-chunk-on-request: from true to false. (I know its not ideal, but chunks no longer unload/load instantly, thus saving my server).

**Comment by thatsIch** [comment]
Cauldron is dead software and not developed anymore. Its last active administrative task was done early December.  So please, keep that in mind.
