### ISSUE TITLE
Zinc from Steam power mod doesn't work in Grindstone

### ISSUE THREAD

**Issue by Flexico** [AppliedEnergistics/Applied-Energistics-2#1024]
Won't even let me put it in.

**Comment by Cisien** [comment]
You should be able to add this item to the grind atone using the custom recipe file. Search recipe on the wiki for how to do that.

**Comment by Flexico** [comment]
Oh, well that was amazingly simple! Thanks. XD

**Comment by thatsIch** [comment]
If you are so free to share the recipe line, we can integrate it into a future build
