### ISSUE TITLE
Placing items into terminal can cause NPE

### ISSUE THREAD

**Issue by Cobra1117** [AppliedEnergistics/Applied-Energistics-2#1025]
Placing items into a terminal can cause a NullPointerException, although the bug seems to occur at random intervals.

Here's the stacktrace: http://pastebin.com/sXZVE9V1

The exception does not cause the server to crash (hence the lack of a crash report), but the client of the player who tried to add the item is disconnected. The item(s) that were place into the terminal are dropped on the ground when the player rejoins the server.

As I mentioned before, this is somewhat random, but currently the bug happens for me when I try to place Vibrant Quartz Glass into a terminal, but not when I add regular Quartz Glass.

**Comment by Cobra1117** [comment]
The error displayed by the client on disconnect is, "A fatal error has occured, this connection is terminated."

**Comment by yueh** [comment]
#1011

**Comment by Cobra1117** [comment]
Placing an item into the system in a way that does not directly involve a player (placing it in an interface, for example) causes a server-side crash. Here's the full crash report:
http://pastebin.com/uaSsT2SK

**Comment by Cobra1117** [comment]
@yueh Ack. Sorry for the duplicate issue. I _did_ try searching first.
