### ISSUE TITLE
Autocrafting might have problems with metadata.

### ISSUE THREAD

**Issue by EnderrGames** [AppliedEnergistics/Applied-Energistics-2#1026]
Getting problems with the autocrafting using specific items.
I am having the problems now on the only two items that use metadata Pure Certus Quartz and Wool.
Crafting the 1k storage cells I set up the pattern to use pure certus quartz, It first uses charged certus, if i am out of that pure.
If i set up the recipe with regular certus quartz it does the same thing, Charged --> Pure --> Certus Quartz.

Today i got the same problem with wool making covered cables.
I set the pattern to use white wool, it goes through all other colors first, then white.

1k pattern:
https://www.dropbox.com/s/l5mo7ltnw4syish/2015-03-15_01.19.47.png?dl=0

What it does:
https://www.dropbox.com/s/aymdyy1i2vvaw1b/2015-03-15_01.20.39.png?dl=0

Covered Cables:
https://www.dropbox.com/s/mr0tea3oui0svr7/2015-03-15_01.29.31.png?dl=0

Using FTB Infinity + GregTech

**Comment by Mephie** [comment]
Same problem here. Autocrafting prefers stained glass to vanilla glass, and vanilla dyes (bonemeal, lapis, rose red, etc) to my Botania Floral powders which are in my paintball recipes.

Running FTB Direwolf20 1.0.4 (MC1.7.10) which is using ae2-rv2-beta-8
--Meph

**Comment by yueh** [comment]
#784
