### ISSUE TITLE
Crafting Terminal crash with NEI recipe filling

### ISSUE THREAD

**Issue by Eearslya** [AppliedEnergistics/Applied-Energistics-2#1030]
One of the latest commits in b11, f0482dd391efa36268bc0c4f72e7dfee389a469e, introduced a bug where shift-clicking a recipe from NEI into a Crafting Terminal while the AE system does not have the necessary materials will cause an IndexOutOfBoundsException.
I believe the issue lies on line 203 of **appeng.core.sync.packets.PacketNEIRecipe**, where `this.recipe[x][y]` should instead be `this.recipe[x][0]`.

**Comment by abdullamu** [comment]
the game is unplayable because of this bug im encountering this bug too
