### ISSUE TITLE
Crash when shift-clicking items in ME Terminal

### ISSUE THREAD

**Issue by SmokeyTheBandicoot** [AppliedEnergistics/Applied-Energistics-2#1031]
I'm playing with AE2 rv beta 10 and sometimes when I insert items in the Me terminal the game crashes server-side. My ME network has only an Me drive with 4 1k storage cell, a power acceptor a piece of cable and the Me terminal. 

The crash does not happen everytime I insert an item into the terminal

http://pastebin.com/ngNjhuEg

**Comment by yueh** [comment]
#1011
