### ISSUE TITLE
RemoteIO crashes with AE2 channel feature disabled

### ISSUE THREAD

**Issue by SmokeyTheBandicoot** [AppliedEnergistics/Applied-Energistics-2#1032]
If I disable channel feature in AE2 config the mod RemoteIO crashes because it uses the ME controller in a recipe. Since disabling channels means that the Me controller is not registered by AE2, Remote IO cannot register the recipe for the ME transfer upgrade and crashes the game. Changing the recipe with MineTweaker does not change anything

Crash report: http://pastebin.com/J0TE4Lpt

**Comment by RAnders00** [comment]
Is a remote io issue. dmillerw/RemoteIO#73
