### ISSUE TITLE
Wireless Pattern Terminal and Wireless Interface Terminal 

### ISSUE THREAD

**Issue by dkudriavtsev** [AppliedEnergistics/Applied-Energistics-2#1040]
To configure auto crafting and replace Wireless Crafting Terminal.

**Comment by thatsIch** [comment]
Mh, does anybody want to run around with 3 different wireless terminals?

**Comment by yueh** [comment]
Was the previous statement not always "no wireless crafting"?
A pattern terminal would allow it, but a bit clunky.
Also an interface terminal without the pattern one would pretty much useless.

**Comment by gixbit** [comment]
What this is leading to, is basically carrying a gigantic machine around in your inventory. Applied Energistics: Backpack Edition? 

Completely unnecessary. You can literally carry a quantum ring around with you and slap it down, tesserect the power to an energy acceptor and slap the terminals on a wire, looks like a nightmare, works great. Is this feature requeest necessary? I personally don't think so. Would it be cool? Yes, But, You can already mad scientist half the game, All you need is to never see your base ever again to really put that, I feel really lazy, right into the game, when it's already there if you macgyver the quantum ring around with you. The only downside to not having the wireless pattern/crafting is the time it takes to throw close to 11-12 blocks down give or take.
