### ISSUE TITLE
Pattern Encoder doesnt accept stacked items

### ISSUE THREAD

**Issue by Moorleiche2k** [AppliedEnergistics/Applied-Energistics-2#1041]
As title says, the encoder accepts only single items. While this may work with most of the mods, mod recipes of e.g. minechem, which rely on stacked chemicals, cannot be encoded in patterns. Obviously spreading the stack doesnt work as well.

Also, products of a recipe will consume the item within the pattern encoder (the item in the slot to the right of the arrow) and cannot be removed except by a change of the 3x3 grid on the left side. A change makes the product vanish. Overall the item is lost once placed in the product slot of the encoder.

**Comment by XFactHD** [comment]
You have to switch the mode of the pattern terminal. In crafting mode (one output slot, used for MAs) you can't stack items, but in production mode or however it is called you have 3 output slots and you can stack items in the input slots.
