### ISSUE TITLE
Fuzzy metadata card

### ISSUE THREAD

**Issue by krakentoa** [AppliedEnergistics/Applied-Energistics-2#1043]
Feature request. Similar to Random Things filters, or enderio's filter options.

**Comment by yueh** [comment]
The design concept for AE2 is to not expose internal data.
So most likely no.

(And no, mod X doing Y is rarely a good reason)

**Comment by krakentoa** [comment]
aaahhh ok thanks for explaining

**Comment by yueh** [comment]
I have probably explained it somewhere else here already. But let me repeat the basic things about it.
Metadata is in general extremely inconsistent. One mod might just use it for different colors of the same item/block, another one could use them as growth value or similar and the next one will put every item/block into 2 item ids, using the metadata to distinguish them.

For example AE2 is reusing 3 or 4 ids pretty heavily. One for general materials, but that includes the upgrade cards, crystals (but not seeds), dusts or the parts for cells (but not cells). The next one is for all parts like buses, but this also includes every cable, terminals and similar stuff. The other shared ones are paintballs and seeds (and these are very strange).

So something simple like "just ignore metadata" will in most cases either not filter enough items or way to much. So it is mostly useless without an option to specify exact ranges and that does just not work without exposing things a user should not care/know about.

**Comment by krakentoa** [comment]
i'll be careful then with what items i'm actually specifying when using those filters ;)

**Comment by thatsIch** [comment]
I think this was also rejected at some earlier point. It might be useful to export even all older closed issues on the old tracker for these circumstances.
