### ISSUE TITLE
Auto-Crafting stuck not working. All crafts are "scheduled".

### ISSUE THREAD

**Issue by PSR-ReenReen** [AppliedEnergistics/Applied-Energistics-2#1045]
Using the DireWolf20 FTB pack with Ars Magica 2 installed. In my SSP game all auto-crafting recipes get stuck saying "scheduled" and don't continue on from there. In my creative world everything works fine. I've tried turning off my quarry, building a mini AE system with only the molecular assembler, ME interface, and 1k crafting storage attached. Still doesn't work. Any suggestions would be appreciated.

**Comment by OldOpa** [comment]
You are sure that all items can be crafted and that the items don't get stuck in a chest waiting to be extracted?

**Comment by thatsIch** [comment]
Be careful to not enter recursive recipes in like logs + coal = coal

**Comment by PSR-ReenReen** [comment]
I set up a standalone system with 8 planks = a chest. Even just having the
planks in the system still came up as scheduled.

**Comment by thatsIch** [comment]
no free extra storage for the new item?

**Comment by Cisien** [comment]
Show us your setup.

**Comment by PSR-ReenReen** [comment]
Ok, no idea what I did, but it's working now. Launcher had crashed and
wouldn't let me launch FTB so I had to download again. Everything seems to
be working fine now. I'll open up another thread if it fails again.
