### ISSUE TITLE
Powered Grindstone

### ISSUE THREAD

**Issue by jackk225** [AppliedEnergistics/Applied-Energistics-2#1047]
This may already be planned, but it might be useful to add an automatic grindstone that requires power.

**Comment by jackk225** [comment]
It does not seem to be letting me mark this as "type-feature"

**Comment by thatsIch** [comment]
Else people would just mark everything as feature or stuff and that would be chaos
and also https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/23
