### ISSUE TITLE
Wired Issue with 500 Caches

### ISSUE THREAD

**Issue by Noxy4u** [AppliedEnergistics/Applied-Energistics-2#1048]
well im not so much a Technikan so sorry if i do something wrong or wast your Time :D
well i have the strange problem that AE2 brings my cpu usage to 100%, minecraft still works but i cant flip leavers, open doors or annything like that. like serverlag just that it happens in Singleplayer... 
i play AE2 in the Direwolf20 Pack 1.710 (1.1.1 pack version) AE2 is on version rv2-beta-pre9
channels are deaktevatet. the bug (or how ever i shall call it) happens as soon as i connekt my Cappasitor Bank to the AE system (basically as soon as the ae system gets power)
i was able to load a backup so i deaktivated the system. the backup is this file http://workupload.com/file/mXw4dgH8
everything is working perfektly and was before also, i build the system and everything worked very good and suddendly as it was out of power and i reestablished power, boom, wired issue and all 8 cores of my cpu are 100% :/ as soon as i cut the power connektion everything workes fine
i have some mods added and was thinking that this head coused the problem, but everything was fine untill i added 500 resonant caches with storage busses to the AE system maybe that is the problem 
mods i added myself: ex nihilo, extra cells, Draconik evolution, pams harvestcraft
coordinates of my base is x:-1774 y:85 z:869   if someone wants to reproduce the strange failure simply hook ae-system up to the connektor and try to open a door or acces a maschine (it wont work) and wach processor it goes up to 100% 

tank you for reading and i hope i didnt wast your time
Sincerly Noxy :D 

*edit* ok failure is the caches i disconekted all parts of my ae system (autocrafters, factory, cachstorage,...) and as soon as i reconnekt the 500 Caches everything goes nuts ..... maybe i overengineered it a little bit :/

![2015-03-17_23 29 18](https://cloud.githubusercontent.com/assets/7073478/6698922/853e90be-ccfd-11e4-9bce-16ef67f59f7a.png)
this is picture of the caches, im very sorry

**Comment by thatsIch** [comment]
Did we ever distribute a rv2-beta-pre9 version? Can not remember doing so

**Comment by yueh** [comment]
It is an unofficial (unsupported?) testbuild not intended for public use. So...?

**Comment by thatsIch** [comment]
Just wondering, what it is doing in the DW20 pack?

**Comment by TheJulianJES** [comment]
Well, the name of the AE2 versions is: "appliedenergistics2-rv2-beta-pre9.jar" I can't find the download on the offical website.

**Comment by Cisien** [comment]
Yeah, for whatever reason, that test build made it into the official dw20 pack.

Did any of the perf improvements make I into the newer official builds?

As for the issue, are you using subnets, or just one massive network?

**Comment by Cisien** [comment]
You can also try updating ae2 to the latest official build.

**Comment by TheJulianJES** [comment]
@Cisien I don't think there were some changes that maybe fixed this.

**Comment by Noxy4u** [comment]
i made one giant system, and about the version i dont use the recommended version of the direwolf 20 pack (wich is 1.0.4) i hope i didnt couse someone troubble, if so im very sorry, i will try a newer version, very much thank you all for help

**Comment by thatsIch** [comment]
Also you did not post a crashlog

**Comment by Noxy4u** [comment]
the problem is that the game dont crashes it is still open and i can move, its just that i cant flick leavers and cant use maschines. well and the cpu is up to 100%

**Comment by thatsIch** [comment]
In that case, the title sounds a bit missleading

**Comment by Noxy4u** [comment]
im sorry i edited the Title, i updated to the Version rv2-beta-14 wich is the newst i found. i load the Backup with this setup and the result is the same. it dont changes the problem. 
![2015-03-21_11 45 55](https://cloud.githubusercontent.com/assets/7073478/6764729/30e1603a-cfc0-11e4-8234-0a1b7d2455bf.png) this is debug menue

![unbenannt](https://cloud.githubusercontent.com/assets/7073478/6764733/411129d6-cfc0-11e4-8ab6-c56b41858165.PNG) this is recoucenmonitor from task manager while error (normally i use not even half of that recources

**Comment by thatsIch** [comment]
Can you give us profile like in http://ae-mod.info/profiling/

**Comment by thatsIch** [comment]
How can you have 0 fps? :D

**Comment by Noxy4u** [comment]
hahaha i have no idea whats going on, but in fact without the cashes attached i can play totally normal without anny issues. i will try and profiel

**Comment by Noxy4u** [comment]
well im not able to press the cpu button on the net.minecraft.launchwrapper

**Comment by thatsIch** [comment]
Are you on the sampler tab?

**Comment by Noxy4u** [comment]
yes i am, btw i wrote you in the espernet IRC

**Comment by Noxy4u** [comment]
ok so in the process of making a Profile i used several loaders (like MMC etc) while using the Forge Curse loader i upgraded the Version of Applied Energistics to rv2-beta-14 and out of nowhere, the failure is gone, im not able to reproduce it again, so whatever it was its gone, dont know if it is the newest version or the recompiling during the change of the modloader but its away. thanks to everyone too help me you guys Rock :D
