### ISSUE TITLE
Facades and Terminals

### ISSUE THREAD

**Issue by cerbralone** [AppliedEnergistics/Applied-Energistics-2#1050]
I saw in a direwolf video that you can have a facade as a background for your terminals, and I seem to be unable to do just this. I tried putting the facade down then the terminal and vice versa. With putting the facade down first, the screen faces the facade. With putting down the terminal first, the facade will go on any side except the one with a terminal on it.

**Comment by XFactHD** [comment]
You can't use covers from Forge Microblocks as background for terminals, you need to either use cover strips or the ae2 covers.

**Comment by cerbralone** [comment]
I was using the facades from AE2, I expect them to work

**Comment by XFactHD** [comment]
Which ae2 version are you using?

**Comment by thatsIch** [comment]
Works fine for me

![2015-03-19_13 31 25](https://cloud.githubusercontent.com/assets/2210496/6730367/458a7772-ce3c-11e4-856a-b9bcd046a392.png)

**Comment by Cisien** [comment]
The behavior you ate describing is consistent with forge multipart covers, and not the ae2 facades. Double check you are using the ae2 variant. (the one made with 4 cable anchors around a block)

Sent from my Windows Phone
________________________________

**Comment by CrazyPyroEagle** [comment]
I can confirm that this is a bug. A fix was to dismantle the cables and terminal and replace them. I first placed the façade then right clicked the terminal on top.

For some strange reason, this bug occurs on rare occasions.

Version: rv2-stable-10

**Comment by XFactHD** [comment]
Please use the latest version when reporting bugs. For me this works no matter what is placed first when I use AE2 facades (which is intended to be the only way).

**Comment by mindforger** [comment]
maybe he placed __and removed__ a micropart on that part of cable __before__ trying to add the facade ... the cable becomes a micropart but does not change back to be a "normal" cable when the covers are removed! The cable needs to be broken and paced again .... or did this change somewhere down the line ?

**Comment by XFactHD** [comment]
No, it didn't change. I didn't think of that, thanks for reminding me @mindforger.
