### ISSUE TITLE
Update to use only the craftguide API

### ISSUE THREAD

**Issue by thatsIch** [AppliedEnergistics/Applied-Energistics-2#1053]
The current used API is basically the mod itself stripped of its texture files, generating tons of errors in dev environment. Also it increases load time while developing.

**Comment by yueh** [comment]
Is it even still actively maintained? There is no 1.7.10 version or fork for it.

**Comment by thatsIch** [comment]
No, but with 50.000 downloads still used commonly in smaller modded environments
