### ISSUE TITLE
Multiparts disable interfaces

### ISSUE THREAD

**Issue by CandiceJoy** [AppliedEnergistics/Applied-Energistics-2#1059]
When I put a glowstone nook on an Interface, the interface ceases to function.  It happens if I put a multipart anywhere in the block beneath it.  Place a multipart, there's 31 interfaces in the terminal.  Remove the multipart, there's 32 interfaces in the terminal.  Place it again, there's 31.  It's a very obvious correlation.

**Comment by thatsIch** [comment]
Can you post a screen shot to clarify it?

**Comment by CandiceJoy** [comment]
The normal interface: http://puu.sh/gJ9s2/8b7e378987.png
The interface terminal count: http://puu.sh/gJ9sM/64ab4eda25.png
I want to stress that NO OTHER CHANGES were made other than the single change pictured below.
The multipart'd interface: http://puu.sh/gJ9u1/1ac554560d.png
The new interface terminal count: http://puu.sh/gJ9v5/5daa9cc608.png
Again, only THAT SINGLE CHANGE is made.
Back to the normal interface: http://puu.sh/gJ9xX/64b3709599.png
And the new interface terminal count: http://puu.sh/gJ9yn/47acc460b7.png

It may do this with other blocks as well, maybe even cables.  However, I only tested this effect with interfaces.  This is very very very bizarre to me, and it took us quite awhile to figure out why all of our interfaces weren't available.

**Comment by thatsIch** [comment]
Thanks for the pictures, I am trying to reproduce this. A multi-part from FMP should not alter this. Is there by some chance a "new" entry in that list, which replaces the 32th interface?

**Comment by yueh** [comment]
It just changes the name to "tile.multipart". As the interface is using the order of `ForgeDirection`, it means `DOWN > UP > NORTH > SOUTH > WEST > EAST` as order for obtaining the name (if the interface is not renamed itself).

Not sure, if I want to see an exception just to handle FMP differently.

**Comment by thatsIch** [comment]
But why is "tile.multipart" a valid inventory?

**Comment by yueh** [comment]
Maybe FMP defines every TE as inventory to be able to actually handle inventories inside it?
And I am not sure, if the interface really cares about an inventory or just an adjacent TE with some name.

**Comment by CandiceJoy** [comment]
Yeah, it shows up as tile.multipart.

**Comment by CandiceJoy** [comment]
This problem doesn't happen with cables as far as I know, although multiparts DO make cables and things in the same block take a LOT longer to break, but the effect is not limited to just AE2 cables.  Thermal Dynamics cables too, at least, do the same thing.
