### ISSUE TITLE
Fixture Bug

### ISSUE THREAD

**Issue by ken2812221** [AppliedEnergistics/Applied-Energistics-2#1068]
Whenever I use the Charged Quartz Fixture or Light Detecting Fixture on the side (not top) of the grass, it will turn into another grass or ferm. Is that a Bug??

![2015-03-22_00 55 36](https://cloud.githubusercontent.com/assets/11154118/6765955/da84a962-d02e-11e4-9826-5d7ff137ad1c.png)
![2015-03-22_00 55 44](https://cloud.githubusercontent.com/assets/11154118/6765956/dd251a1c-d02e-11e4-9ebf-89049d78c223.png)
![2015-03-22_00 55 51](https://cloud.githubusercontent.com/assets/11154118/6765957/e0e34584-d02e-11e4-9750-855a143203e7.png)

version:rv2-beta-pre9(direwolf20 mod pack 1.1.1)

**Comment by thatsIch** [comment]
Confirmed, a pretty funny one though

**Comment by Cisien** [comment]
I wonder if it changes wool color

**Comment by ken2812221** [comment]
I think it's because grass should be replaced, but wool shouldn't be replaced.

It also happens on Biomes O'Plenty grass
