### ISSUE TITLE
No recipes, No crafting possible and client crash when pressing "U" on item 

### ISSUE THREAD

**Issue by Stette** [AppliedEnergistics/Applied-Energistics-2#1070]
**Started working on AE tonight, but when I was looking up recipes, just a few worked (5-10). I looked up a recipe on the AE website and tried to make it in game, but it couldn't be crafted... I looked up the "Calculation Processor" in NEI and pressed "U" and the game crashed.**

Crash-log:

http://pastebin.com/SRXQ0j1w

**Comment by yueh** [comment]
OpenComputers issue, please report it to them.

**Comment by Stette** [comment]
Wow, that was fast. I'm just curious, how could you see that from the log? Tried to search for it myself.

**Comment by Stette** [comment]
Removed OpenComputers, still same problem.

**Comment by thatsIch** [comment]
maybe some other mod shipping the OC API

**Comment by Stette** [comment]
The crash is one thing, but why can't I craft anything from AE2?

**Comment by thatsIch** [comment]
Sounds like Minetweaker recipe modifications

**Comment by thatsIch** [comment]
Try to remove mods, until you do not get the crash anymore. Somebody is injecting OC code into NEI and crash there. 
And the recipes on the webpage are default. So if you use a modified version of it, it obviously wont work.
