### ISSUE TITLE
Forge Update

### ISSUE THREAD

**Issue by Dudesfield** [AppliedEnergistics/Applied-Energistics-2#1079]
The problem that is happening?
RV2 Beta 14 is not compatible with the new forge build 1291. AE2 blocks become invisible but are accessible, including wires, Terminals and multipart pieces. 

What was expected?
Items to be visible

How to reproduce the problem?
Change to forge build 1291

Server or Single Player?
Single Player

Mod Pack using and version?
No modpacks

Crashlog?
No crashlog. Doesn't Crash.

These are from RV2 Beta 14 on Forge 1230
![2015-03-23_19 32 24](https://cloud.githubusercontent.com/assets/8277434/6792880/892bd1ba-d193-11e4-977a-d3f50ed14b8e.png)
![2015-03-23_19 32 32](https://cloud.githubusercontent.com/assets/8277434/6792881/8aa46d40-d193-11e4-993b-4725fad395c7.png)

These are RV2 B14 on Forge 1291
![2015-03-23_19 30 27](https://cloud.githubusercontent.com/assets/8277434/6792887/9cd7172e-d193-11e4-9d13-b7a7ad8beaf4.png)
![2015-03-23_19 30 40](https://cloud.githubusercontent.com/assets/8277434/6792888/9e49e4ce-d193-11e4-8e22-75058c3dcccb.png)

**Comment by thatsIch** [comment]
We use 1291 and its working fine. Do you use optifine or such, which are not compatible with this version?

**Comment by yueh** [comment]
FastCraft can also cause it.

**Comment by Dudesfield** [comment]
You know, it was optifine. I should have known cause it's happened before and I forgot. Sorry to have bugged you with stupidity. Lol
