### ISSUE TITLE
different fluid supports for crystal growing

### ISSUE THREAD

**Issue by AlgorithmX2** [AppliedEnergistics/Applied-Energistics-2#108]
some stuff like resonant electrum would be maybe faster than water e.g

Originally Posted by thatsIch

This issue was migrated; For original details see http://ae-mod.info/Tracker/1049/

**Comment by Blue64** [comment]
+1 here. Perhaps using the Temperature of the fluids would be a good idea? As long as it isn't destroyed by it of course (lava), there's various fluids that have a wide range of temperatures, so it'd be a nice feature. I enjoy looking at various MineChem & PneumaticCraft temperatures, so adding more thermal based mechanics would be simply lovely.

**Comment by XFactHD** [comment]
@Blue64 Using thermal mechanics is to unrealistic I think. Just look at crystal growing in real life, it takes enormous amounts of time and is not influenced by temperature and in AE2 you already have high-tech crystal growing if you use the crystal growth accelerators.

**Comment by Blue64** [comment]
Unrealistic how? The 2 main components of real crystal growth is Thermal Mass & Pressure, unless of course you're using over saturation method, which takes only a matter of days at room temperature,  but this isn't using the over saturation method, so I believe thermal mechanics mixed with fluid density mechanics would be a wonderful idea and very realistic.

**Comment by Technici4n** [comment]
Probably not gonna happen as we'd like to move away from the current crystal growth mechanic due to how hard it is to correctly automate. See also #5687.

**Comment by shartte** [comment]
@Technici4n This is already implemented 😁

**Comment by shartte** [comment]
Relevant config is:

```
  "inWorldCrystalGrowth": {
    "__comment": "The speed multiplier to use when the crystals are submerged in the improved fluid.",
    "improvedFluidTag": "",
    "improvedFluidMultiplier": 2.0
  }
```

**Comment by Technici4n** [comment]
Oh lol, interesting.
