### ISSUE TITLE
Cannot Craft Most AE2 Items

### ISSUE THREAD

**Issue by Gatzy** [AppliedEnergistics/Applied-Energistics-2#1080]
I can't craft many of the items in this mod, and their recipes aren't showing up in NEI either.

**Comment by mSt3in** [comment]
which pack?

**Comment by halvors** [comment]
I think this is related to  #1061, do you have Mekanism v8 installed?

**Comment by Gatzy** [comment]
Im using FTB infinity with Mekanism 8 installed, I'll go check that other post.

**Comment by Gatzy** [comment]
Yeah disabling the integration fixed it. What else would disabling integration do?

**Comment by Cisien** [comment]
At the least, I don't think the joules form of power from mek will work, mek will convert to RF in that case, I beleive
