### ISSUE TITLE
Invisible blocks in spatial storage

### ISSUE THREAD

**Issue by Desuiseiseki** [AppliedEnergistics/Applied-Energistics-2#1081]
I placed a bunch of Ender chests which cannot be moved in or out on a platform inside a 13x13x13 spatial cell dimension.
I left them there and I then expanded the pylons and made a larger spatial storage cell dimension, storing the original platform.
When I went to place chests in the same place they were in the smaller cell, I was unable to place them and the space was taken up, it could be walked on and acted like there was a block there other than it not being accessible or visible.
Tested with Ender Chests from Ender Storage, might happen with other tile entity blocks not supported for transfer in and out.

**Comment by yueh** [comment]
As far as I know it is a bug with EnderStorage itself. Any mod moving them (except the complete white one) will cause it.

SpatialIO is whitelist based, so it will not move any unsupported TileEntity by default to prevent exactly these issues. (This includes EnderStorage by default.) 
If it moves them around, then someone did whitelist them as working without testing it actually. For example the author of your modpack or the mod author. So I would recommend report it to them.

**Comment by Desuiseiseki** [comment]
They didn't move at all. I got them in by going in myself and manually placing them and I have a chunk loader inside the cell. They are inside the storage dimension unmoved but affect another storage cell as well.

**Comment by thatsIch** [comment]
Can not reproduce, is it persistent after a reconnect/restart?
Maybe some screenshots? I think I am missing something to rebuild it.
