### ISSUE TITLE
Looking at AE2 blocks while moving causes FPS drops

### ISSUE THREAD

**Issue by Chromotron** [AppliedEnergistics/Applied-Energistics-2#1084]
Looking at AE2 (rv2.beta build 14, but also earlier ones)  blocks causes severe FPS drops (from 35 to 10 in my case)  when moving. I tested this with the cables and molecular assemblers on my server's AE2 complex.
I was not fully able to reproduce this, but placing many molecular assemblers that get powered seems to work.

I and others had a very similiar effect when Reika added certain ore blocks to Chromaticraft. He was able to fix this, so maybe asking him about the cause might help.

**Comment by Chromotron** [comment]
I think I found the reason: Thaumic Tinker's armor causes lighting updates wherever I look. And as the abovementioned blocks are partially transparent, this causes tons of clientside lag.

Sorry for this wrong report, please close/delete it.

**Comment by thatsIch** [comment]
You can always close your own issues.
