### ISSUE TITLE
lag when chunk unload

### ISSUE THREAD

**Issue by DrummerMC** [AppliedEnergistics/Applied-Energistics-2#1087]
it takes a long time to unload chunks

![1](https://cloud.githubusercontent.com/assets/7688760/6807405/9785bd96-d24e-11e4-99e5-5b89a150862d.png)
![2](https://cloud.githubusercontent.com/assets/7688760/6807406/97883daa-d24e-11e4-9c7b-36fc336f301f.png)
![3](https://cloud.githubusercontent.com/assets/7688760/6807407/97891a54-d24e-11e4-9ba1-2634c1d2d09a.png)

**Comment by thatsIch** [comment]
Why people only share images and never share the profiles?

**Comment by DrummerMC** [comment]
this is a bug in extra cells not in ae2.
