### ISSUE TITLE
Item Duplication on Server

### ISSUE THREAD

**Issue by Isfirs** [AppliedEnergistics/Applied-Energistics-2#1089]
Hello, my englishskills aren't the best, but I try my best!

On server we made us a ME Drive and 10 4K Storage Cells.
I removed a cell and we still were able to access these items.
Plus, after i removed the ME Drive from the network, we were able to access ALL items.
After someone took out iron blocks, i placed the ME DRive again and filled all 4K Storage Cells in it.

The items removed were still in the ME Drive and and we duplicated the items.

To mention is, we used a Cable Anchor to seperate the Fluix cable from the ME Drive.
After it, the ME Drive was shown offline (no colors lit) but access was possible.

In a second try we weren't able to replicate the scenario, but we agreed to comit a ticket.

I hope for response and sorry for any misspelling or bad english ^^'

--
Isfirs

**Comment by thatsIch** [comment]
Need more background information like version, server type etc
Hope you dont use stff like Cauldron or so
Also duplication are only valid, if the items are persistent after a reconnect.
