### ISSUE TITLE
Allow Inscribers to duplicate crafting/processing patterns

### ISSUE THREAD

**Issue by EnigmaticaGH** [AppliedEnergistics/Applied-Energistics-2#1090]
Put an empty pattern in the middle input slot and a filled processing pattern in the upper/lower slot to receive 2 of the same crafting pattern.

![screenshot_17](https://cloud.githubusercontent.com/assets/11641630/6818286/3cd5de5a-d283-11e4-9dd1-71475d58c271.png)

**Comment by thatsIch** [comment]
You can basically do that already with your termin,
put pattern in, and put out as many "new" patterns you want.

Inscriber Process would be useful, if you want automation of the creation of crafting patterns.

Any particular use-case?

**Comment by EnigmaticaGH** [comment]
I was totally unaware that you could do that. Well I'm sure someone could find a use for automating the crafting, but at the moment, I have no need for it.

**Comment by thatsIch** [comment]
Closing for now, if somebody sees an application for it, it can be re-opened
