### ISSUE TITLE
ME system power dies when adding more blocks.

### ISSUE THREAD

**Issue by Higgins909** [AppliedEnergistics/Applied-Energistics-2#1091]
I'm playing the latest feed the beast direwolf20 and when I add enough items, it just dies... I can't get any decent system going because I cant get enough me cables importer/exporters because it kills the system, when placed a small number.
I tried adding more energy accepters, but that did nothing, and its not my power supply, its nearly full.

**Comment by thatsIch** [comment]
define "dies"

**Comment by yueh** [comment]
I would guess the usual "runs out of channels".

**Comment by Vythrin** [comment]
You're running out of channels. You need to use an ME Controller in order to gain more channels. Each side of a controller is 32 channels, and by default, when not using a controller, you're restricted to 8.
