### ISSUE TITLE
Mekanism is not compatible (recipe bug)

### ISSUE THREAD

**Issue by acgirl1** [AppliedEnergistics/Applied-Energistics-2#1095]
Hey,

if Mekanism is installed, i cant get the recipes for Applied Energistics 2 in NEI.
I think there is an incompatible issue between this mods.

Is there a Fix? or is this a bug by mekanism maybe, that i have to contact the dev of Mekanism ..

**Comment by thatsIch** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1061

**Comment by thatsIch** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/1086

**Comment by acgirl1** [comment]
So ive read this all, and what i have to do this the source? i dont understand Java
