### ISSUE TITLE
Can't place Press inside Inscriber

### ISSUE THREAD

**Issue by giogimic** [AppliedEnergistics/Applied-Energistics-2#1096]
Here's a video one of my admins took of the issue 
https://www.youtube.com/watch?v=Cokgs_EgFiM&feature=youtu.be

Any ideas?

**Comment by Vythrin** [comment]
This is gamebreaking for us, we cannot move forward until this is resolved. We did recently update AOBD and Mekanism, if that matters at all.

**Comment by themechman** [comment]
I am running RV1 and was able to make a copy of 1 press pattern and now I am unable to do any of it again.

**Comment by giogimic** [comment]
Fixed by disabling Mekanism integration

**Comment by themechman** [comment]
How can we perform this and what kind of negative impacts will we face?

**Comment by thatsIch** [comment]
You will only remove Mek Joules Power from AE and some recipes will be missing from processing chain in Mek Machines
