### ISSUE TITLE
Sign

### ISSUE THREAD

**Issue by AlgorithmX2** [AppliedEnergistics/Applied-Energistics-2#110]
Would it be a good idea to give the illuminated panels a sign upgrade?

Name them or give them a sign upgrade to enable them to show text like a sign. Combine this with a level emitter and a redstone card and you have a sign that lights up when a certain amount of items is in the network.

This could possibly be addon-territory though, or through some sort of computer integration.

Originally Posted by ikabodo

This issue was migrated; For original details see http://ae-mod.info/Tracker/1063/

**Comment by thatsIch** [comment]
Closing this in favor of #134
