### ISSUE TITLE
Multiple Server-side crashes

### ISSUE THREAD

**Issue by GreatOrator** [AppliedEnergistics/Applied-Energistics-2#1100]
I apologize in advance if there are bugs reported regarding these crashes already, but as I am getting them collected second hand and I am unsure as to what was being done when the crash occurred.

http://pastebin.com/668Lhzi9

http://pastebin.com/FvRn0FSk

http://pastebin.com/fj79iv8u

Thank you for such a wonderful mod!

**Comment by thatsIch** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1011/
