### ISSUE TITLE
Duplicate crystals

### ISSUE THREAD

**Issue by min4builder** [AppliedEnergistics/Applied-Energistics-2#1104]
when you purify a crystal, you get two purifyed crystals. then you make a block of that crystal using the purified versions. finally, when you turn the block back into crystals, you get double the amount you had in the start! this can be repeated indefinitely!

**Comment by thatsIch** [comment]
Are you telling us, that your modpack introduces an infinite loop? Pretty sure, we have non in our recipes.

**Comment by TheJulianJES** [comment]
@min4builder What's the recipe for YOU (in the pack) to make an block out of purified crystals.
