### ISSUE TITLE
P2P Tunnel Crash

### ISSUE THREAD

**Issue by LordAnimar** [AppliedEnergistics/Applied-Energistics-2#1105]
Hi
Minecraft crash to desktop while trying to set up item peer to peer tunnels. As soon as I place an item pipe for example buildcraft pipes on both ends it crashes. I'm using the appliedenergistics2-rv2-beta-pre9 wich is currently in use of the Direwolf20 Pack.

I Hope i'm doing that right I never realy used pastebin before, but here is the relating crashreport.
http://pastebin.com/99drbWHj

I know rv2 is a beta version and i'm not complaining. I just thought I let you know about it.

PS: Buildcraft pipes are so far the only one that conect to item p2p at all. I tried thermal dynamic ones, the ones from extra utils and Ender IO conduits

**Comment by yueh** [comment]
This is already fixed, tell the dw20 team to update their pack (more frequently).

**Comment by LordAnimar** [comment]
Sorry i guess i will mannually update to beta 18
