### ISSUE TITLE
Export Buses not crafting.

### ISSUE THREAD

**Issue by pterodactal666** [AppliedEnergistics/Applied-Energistics-2#1106]
I have been having trouble on my FTB Infinity 1.3.4 world (AE2-rv2-beta-8) with autocrafting in my quarry processing setup that crafts metals, redstone,etc into blocks for more compact storage. Through some testing in a single player world with only AE2 and NEI, I believe I have narrowed it down to having both crafting and acceleration cards in my export buses.

## Setup
![2015-03-27_20 40 09](https://cloud.githubusercontent.com/assets/7901609/6865817/d8fee5b6-d4c1-11e4-8cd6-9d613328339c.png)
As you can see I have 4 identical networks, going from having 1 crafting and 3 acceleration cards on the left, to only a crafting card on the right.
![2015-03-27_20 24 58](https://cloud.githubusercontent.com/assets/7901609/6865946/26d9d6b4-d4c3-11e4-967b-461ec194f4ea.png)
What is in all of the networks.
![2015-03-27_20 25 09](https://cloud.githubusercontent.com/assets/7901609/6865956/3f73c784-d4c3-11e4-81fd-ac13e5a0741e.png)
The 3 Accelerator card Export bus. The rest are the same except have fewer accelerator cards.
![2015-03-27_20 25 13](https://cloud.githubusercontent.com/assets/7901609/6865975/6c9f6394-d4c3-11e4-8eec-776bfb59a98b.png)
The pattern in the interfaces.

## Result
Only the network with NO acceleration cards would automatically craft the Iron blocks. If I manually trigger the crafting it operates properly, crafting then exported. I have confirmed the lack of acceleration cards fixes this by removing them from the export buses in my game world and they now operate properly.

## Suggested fixes.
1. Fix it. I don't know how hard this would be but it is the obvious answer.
2. Prevent both crafting and acceleration cards in the same export bus. The downside of this is that while crafting does not work, straight exporting from the same bus does, so it will break that.
3. Update the website. Probably best to update all 3 pages to make sure it is seen.

**Comment by yueh** [comment]
It is fairly easy, you want to export 64 iron blocks and do not have enough materials to do so.

**Comment by pterodactal666** [comment]
So I have found out. I misunderstood how acceleration cards work. I thought they made the export bus check for the items more frequently however they increase the size of an individual transfer.

My apologies.

**Comment by yueh** [comment]
No need to apologise.
The ingame descriptions could be clearly better. But that is its own issue.
