### ISSUE TITLE
Updated my pack and most of AE2 recipies missing help plz

### ISSUE THREAD

**Issue by swifty02** [AppliedEnergistics/Applied-Energistics-2#1108]
hi i updated my modpack today with the latest Mekansm 8 in the process of the update i had to remove AOBD (another one bites the dust) mod as it was conflicting and my players have just noticed that alot of the AE2 recipies are now missing i have tried restarting the server and my players would skin me alive if i delete the me systems any suggestions on what may have caused this and a simple fix :)
any help would be greatly appreciated thanks

**Comment by yueh** [comment]
#1061
