### ISSUE TITLE
Item array pattern

### ISSUE THREAD

**Issue by AlgorithmX2** [AppliedEnergistics/Applied-Energistics-2#111]
This in my mind is a rather simple addition. What it would all you to do is add an array of items to a special kind of pattern that can hold a mass amount of items. When you put it into a drive "partion editor" (not sure if that is what the block is still called) You are able to add a selections of items into the pattern. That pattern can than be added to an import / export buss or an interface and things like that.

This would be good for sending a lot of items though the network and not needing 30 import busses all around 1 block :P. 

Not sure but i think it would be cool.

Originally Posted by aokmikey

This issue was migrated; For original details see http://ae-mod.info/Tracker/1065/

**Comment by thatsIch** [comment]
no real benefit
