### ISSUE TITLE
AE network reassigning channels every few seconds.

### ISSUE THREAD

**Issue by pyroicedragon** [AppliedEnergistics/Applied-Energistics-2#1110]
I'm running a custom server that includes Applied Energistics 2 and have set up a large AE network for storage and remote access to the storage. However, I have run into a problem when I add multiple quantum link devices. After adding more than 2 on the same cable or more than 3 on the whole network, the network "refreshes" every couple of seconds and reassigns the channels. This kicks people out of any interfaces etc. and only allows them to access the network in brief intervals. I have made sure that there are plenty of channels to go to every device and confirmed that removing a quantum link will restore the network to full capacity. However, having only 3 quantum links is somewhat limiting.
![2015-03-27_21 32 55](https://cloud.githubusercontent.com/assets/11688663/6879373/a05b2c80-d4c9-11e4-940a-e1483ccd036e.png)
As seen in this screenshot, there are enough channels but the device is missing a channel during reset.
![2015-03-27_21 34 50](https://cloud.githubusercontent.com/assets/11688663/6879378/cad88e58-d4c9-11e4-871d-f9faa89d3c46.png)
This is the core of the network (sorry about the sloppy setup).
![2015-03-27_21 36 32](https://cloud.githubusercontent.com/assets/11688663/6879387/24f15fc8-d4ca-11e4-81d4-3f539b4dc760.png)
This is how I started to set up the quantum links before running into this problem.

If anyone has any ideas on why this is happening or how to fix it, please let me know.

**Comment by thatsIch** [comment]
Sounds like chunk loading issues

**Comment by pyroicedragon** [comment]
I will make sure to have everything chunk loaded and see what happens. Thank you.

**Comment by pyroicedragon** [comment]
That fixed the problem, thank you. I had neglected to chunk load the quantum links that were away from the computer system. This would have taken me forever to figure out. Again thank you.

**Comment by thatsIch** [comment]
urw
