### ISSUE TITLE
Thaumcraft items Glitch

### ISSUE THREAD

**Issue by legendaryA1** [AppliedEnergistics/Applied-Energistics-2#1111]
Whenever i put thaumcraft items into the computer system all the items become unable to take out of the drive and when you access any terminal all you see is nothing.and the only way to remove the item is with a bus. unfortunately if you dont know what the item is in there is becomes a rather hard task. is there anything you can do to fix this?

**Comment by thatsIch** [comment]
Cant reproduce 

![2015-03-28_07 32 49](https://cloud.githubusercontent.com/assets/2210496/6880057/b36735aa-d51c-11e4-8c15-86b4601fa20f.png)

Be sure, you do not have any mods in between which mess them up and use the latest version of everything to be sure, you dont use outdated software.

**Comment by legendaryA1** [comment]
It does it when you put in the essences try putting one of those in. some thaumcraft items do work others dont i am using all the latest mods

**Comment by thatsIch** [comment]
Still, cant reproduce

![2015-03-28_16 58 29](https://cloud.githubusercontent.com/assets/2210496/6881711/b84e7228-d56b-11e4-822d-857b9cbc07a6.png)

**Comment by legendaryA1** [comment]
oh it seemed i had an out of date version of applied energetics sorry to bother you

**Comment by thatsIch** [comment]
Well depends how outdated your version is, because there should be no special handling between ThaumCraft and AE

**Comment by legendaryA1** [comment]
i was using appliedenergistics2-rv0-stable-3

**Comment by thatsIch** [comment]
That is pretty outdated xD Well happens :)
