### ISSUE TITLE
AE2 Cables Break ProjectRed Cables When going Around Corner

### ISSUE THREAD

**Issue by BlackHawkDoesGaming** [AppliedEnergistics/Applied-Energistics-2#1112]
This is what it does...
![2015-03-28_00 55 22](https://cloud.githubusercontent.com/assets/10902101/6880118/23696342-d4e5-11e4-8045-1d5f089b4c24.png)
![2015-03-28_00 55 16](https://cloud.githubusercontent.com/assets/10902101/6880117/23566242-d4e5-11e4-86ec-355a655564fe.png)

Any color cable, or Type, and color of Cables, or Types.

**Comment by yueh** [comment]
For me it looks more like an issue with ProjectRed itself.
They are probably considering the cable as full block and just behave as it is blocking them.

**Comment by yueh** [comment]
Inactive
