### ISSUE TITLE
Start-up Crash with RV2 B19

### ISSUE THREAD

**Issue by Dudesfield** [AppliedEnergistics/Applied-Energistics-2#1113]
The problem that is happening?
B19 is Crashing on start up for Block Charger
What was expected?
Game to Begin
How to reproduce the problem?
As Far as I know, Installing the new beta file, #19
Server or Single Player?
Single
Mod Pack using and version?
None
Crash log
http://pastebin.com/eK6wC5qD
Screen shots or Pictures of the problem
None

**Comment by thatsIch** [comment]
Did you disable anything?

**Comment by Dudesfield** [comment]
No, All I did was add the file and delete the old and it happened. Beta 18 works just fine.

**Comment by thatsIch** [comment]
This is the same as #1115 
only that with b20 it made a better crashlog. Hail the refactoring.

**Comment by thatsIch** [comment]
Thanks for reporting!
