### ISSUE TITLE
Start-up Crash with RV2 B20

### ISSUE THREAD

**Issue by lehjr** [AppliedEnergistics/Applied-Energistics-2#1115]
Crash on startup with Beta 20
Note. Reduced number of mods installed for cleaner crash log. 
http://pastebin.com/EikVeh84

**Comment by CaptainHawaii** [comment]
Another crash log, in case it helps.
http://paste.ee/p/JIUEk

**Comment by thatsIch** [comment]
the second is not even a crashlog
and the first does not make sense.. I gonna test

**Comment by thatsIch** [comment]
Seems the build which is live on the server is corrupted

**Comment by CaptainHawaii** [comment]
Strange. I've re-dowloaded it about three times x.x
I'll try again, though. Is there any possibility that the download from http://ae-mod.info/ is messed up?

**Comment by thatsIch** [comment]
Give this a try http://puu.sh/gTfwW/27d2499d49.jar

**Comment by CaptainHawaii** [comment]
Nope. Same deal: http://pastebin.com/EwjncUUz

**Comment by thatsIch** [comment]
Thanks for reporting!
Sorry for the inconvenience, that was a bug already introduced in b19
