### ISSUE TITLE
Issue with double storage bus

### ISSUE THREAD

**Issue by Aredrih** [AppliedEnergistics/Applied-Energistics-2#1116]
I have a sub network dedicated to handling cobble which have a storage bus filtered for cobble with a high priority. That way I'm sure that every cobble entering the network goes in the sub network.

Now, when I extract cobble, I want that the sub network is checked at the very end. In order to do that, I set the storage bus evoked above in *insert* mod and add a new storage bus in *extract* mod with a low priority. That way, when looking to insert cobble, it should find the storage bus with the high priority and when looking to extract cobble, it should find the storage bus with the low priority.

The idea behind those shenanigan is to make sure that every cobble in the network outside the sub network will be consume first before consuming cobble from the sub network. The issue is that theory goes wrong and the sub network is consume first for both insertion and extraction. I guess having two different priority for a sub network isn't wealthy and as far as I tried. Also, it goes the same for chest so I'll assume it's a issue about ae assigning 1 priority by storage for 2 way interaction.

-----

System tested:
![little storage](https://cloud.githubusercontent.com/assets/10573494/6882114/4ebb7d96-d57b-11e4-9721-e62cf2d7d2f4.png)
The barrel have a storage bus with a 9001 priority on *insert* mod on it side and a storage bus with a -9001 priority on *extract* mod on top of it. The chest have 0 as priority and only the storage bus in *insert* mod on the side of the barrel is filtered.

Result: the chest is ignored as long as the barrel still hold items.

**Comment by thatsIch** [comment]
This is already done natively

High Priority means: 

* Preferred to be selected as valid input if cobble enters the network
* **not**preferred to be selected as valid output if cobble is requested

**Comment by Aredrih** [comment]
Oh, so I guess the double storage was more likely the issue in that case. After testing, the system with only one storage bus work perfectly and exactly as intended at first (also show that priority system perfectly work with 2 storage bus for 1 inventory). I should have test more deeply priority system.

Any ways, thanks for the clarification and sorry for wasting your times.

**Comment by thatsIch** [comment]
If you share that knowledge, I will account it as an investment :P
