### ISSUE TITLE
NPE - Ticking GridNode

### ISSUE THREAD

**Issue by Terpo** [AppliedEnergistics/Applied-Energistics-2#1119]
1st crash: http://pastebin.com/x3f0wh6f
2nd crash: http://pastebin.com/E92Kjsjz

Mods: http://blog.terpo.org/upload/mc/modlist.txt

appliedenergistics2-rv2-beta-10.jar
Forge 1291

----------------------------------------------------
Dimensional Transceiver received items. These were pulled by an import bus into the ME system. After the crash with the import bus we changed the setup to an item conduit + interface. After that change the server crashed again (70min later). It it not really reproducable. If I got more information after some tests I will post them.

**Comment by thatsIch** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1011/
