### ISSUE TITLE
Oredict / variable item support in patterns can hang crafting

### ISSUE THREAD

**Issue by AlgorithmX2** [AppliedEnergistics/Applied-Energistics-2#112]
What is happening?
Crafting a SFM cable camouflage needs red, blue and green wool. I you have exactly 8 of one colour, autocrafting will not work. It uses necessary coloured wool to craft a missing one and hangs. 

What is expected?
Well, not to hang =)

How to reproduce?
See above.

Server or Single Player?: Server.
Screenshot?: http://imgur.com/a/sAKx3

What I'd suggest is being able to lock patterns to use the exact items configured and disable "fuzzy" items support.

Originally Posted by Belgabor

This issue was migrated; For original details see http://ae-mod.info/Tracker/1068/

**Comment by yueh** [comment]
Can you try
