### ISSUE TITLE
P2P are so awesome that they break the stack size limit !

### ISSUE THREAD

**Issue by Aredrih** [AppliedEnergistics/Applied-Energistics-2#1120]
[/sarcasm]

More seriously, you can insert a full stack into a inscriber with a export bus through p2p.

----

Setup used:

![setup](https://cloud.githubusercontent.com/assets/10573494/6882648/11c5da96-d58d-11e4-9d9f-f13085f81f42.png)

Result:

![result](https://cloud.githubusercontent.com/assets/10573494/6882649/1b5d1b00-d58d-11e4-806f-15e44a1d3bd4.png)

Version tested: Current version on the curse page

**Comment by TheJulianJES** [comment]
Whar version did you use (on the curse page they are all versions...) Please try wit the latest rv2 beta build.

**Comment by Aredrih** [comment]
Ok, it was a bug of this version. Also, it seem to be the same that the one use by the infinite mod pack.
