### ISSUE TITLE
Why are my AE2 Recipes Gone?

### ISSUE THREAD

**Issue by JackDaSmack** [AppliedEnergistics/Applied-Energistics-2#1122]
When I try to craft anything in AE2, with a few exceptions, (i.e. wooden crank or grindstone) it will not craft. It doesn't show the recipe in NEI and will not craft in any crafting table

Pls Help!

**Comment by Aevaris** [comment]
You will need to provide more details. What version of AE2 are you using? Screenshots and a modlist would also be helpful.

**Comment by Cisien** [comment]
If you are using Mekanism, you will need to update AE to the latest version

**Comment by thatsIch** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1061/
