### ISSUE TITLE
Crash on world load w/ RV2 B21

### ISSUE THREAD

**Issue by Aevaris** [AppliedEnergistics/Applied-Energistics-2#1123]
Crashed on world load with RV2 Beta 21. Upgraded from RV2 Beta 18. Pastebin here: http://pastebin.com/pj5rw8NN

Snippet:
Time: 3/28/15 9:54 PM
Description: Ticking GridNode

java.lang.RuntimeException: Invalid Itemstack.
	at appeng.util.item.AEItemStack.<init>(AEItemStack.java:81)
	at appeng.util.item.AEItemStack.create(AEItemStack.java:119)

**Comment by lehjr** [comment]
Another beta 21 world crash:
http://pastebin.com/MDmSZ3rs

If I revert back to Beta 18 it loads fine, so it isn't corrupted. I pulled out all other mods to eliminate any conflicts, but it still fails with the same error.

**Comment by thatsIch** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1118
