### ISSUE TITLE
Crash with use "U" of the NEI on any item

### ISSUE THREAD

**Issue by Tsyklop** [AppliedEnergistics/Applied-Energistics-2#1124]
I use "U" on any item and game crash.
Log: http://pastebin.com/0s2eNLrR

AppEng rv2.beta build 21

**Comment by Tsyklop** [comment]
https://github.com/MightyPirates/OpenComputers/issues/978

**Comment by thatsIch** [comment]
Please refrain from using the latest version yet.

**Comment by Tsyklop** [comment]
@thatsIch laset version AppEng or OC?

**Comment by thatsIch** [comment]
of AE, made major mess, 
and I dont have access to take down the downloads :-(

**Comment by Tsyklop** [comment]
@thatsIch OK

**Comment by yueh** [comment]
First of all you are using an outdated OC version. (A build before Jan 24).

But it is actually an issue with OC itself, it is more or less just coincidence that it happend with b21.
OC is using internal classes, which are subject to change and therefore not intended for public use.
So there is a good chance that it will crash with any newer build of AE2.

**Comment by fnuecke** [comment]
I did notice the accidental reference to `core.Api` in another bit of that code, but that's unrelated to this particular crash (and something I'll fix). It's crashing from a call to `AEApi.instance().blocks().blockController.item()`, which I'm aware is now deprecated, but that doesn't mean it should just start crashing right away, does it? ;-)

**Comment by Tsyklop** [comment]
@yueh OC laset version 1.7.10
