### ISSUE TITLE
Spatial Storage: Wither can destroy Matrix Frame

### ISSUE THREAD

**Issue by emperor06** [AppliedEnergistics/Applied-Energistics-2#1125]
If you happen to spawn the Wither boss in a small spatial dimension, the boss may eventually break some matrix frames, enabling the player to wander in an invisible labyrinth.
I know the matrix frame is set to be unbreakable with a resistance of 6 million but well, that boss can't read Java :)

**Comment by thatsIch** [comment]
maybe we should just extend bedrock...

**Comment by emperor06** [comment]
I couldn't get the Wither to destroy Ender IO's Reinforced Obsidian while it has a much lower resistance. Maybe that's due to something else, like opacity.

**Comment by yueh** [comment]
Bedrock is actually not even its own class, just a default block with `.setBlockUnbreakable().setResistance(6000000.0F)`. So more or less identical to our block.

The wither explosion is actually calling `Block.onBlockExploded`, so maybe also override it?
But I did not find any custom handling for bedrock in the default implementation.

**Comment by emperor06** [comment]
The thing is the Wither's explosion seems to be unable to "normally" break a matrix frame. It looks like it only happens when the Wither has not enough space around him. I spawned one in a 3x3x3 spatial dim so he was taking suffocation damage. At some point, after quite a few explosions, he managed to destroy the matrix. So maybe that's another mechanic than onBlockExploded, I don't know.
As I said, I couldn't get a Wither to destroy a 3x3x3 coffin of Ender IO's reinforced obsidian. But that only works if this coffin is surrounded by blocks otherwise the Wither will escape the coffin by going through it.
