### ISSUE TITLE
Crash on opening bus GUI.

### ISSUE THREAD

**Issue by anishin** [AppliedEnergistics/Applied-Energistics-2#1132]
This crash happens with AE2-rv2-beta21.
When I try to open export/import bus GUI (with ANY item or with empty hand), I have a crash. (I don't check another devices and terminals,  maybe some else devices cause this crash).

Crash log: http://pastebin.com/kCizqNaw

With previous version (beta18) I haven't this problem. Please, fix it.

**Comment by yueh** [comment]
#1118
