### ISSUE TITLE
Channels=False java.lang.NullPointerException : null

### ISSUE THREAD

**Issue by Iomega0318** [AppliedEnergistics/Applied-Energistics-2#1136]
Still getting an NPE when setting channels to false which I posted here: #896 

I am current using rv2-beta-21

**Comment by yueh** [comment]
This is actually just a debug output, stating that an item for a recipe could not be found. (caused by disabling channels)

It could actually be a bit more clear about the actual meaning.
But it does not affect the game in a way that it will crash.

But if you want to remove it from the logging, the only option is to create your own ![custom recipes](http://ae2.ae-mod.info/Custom-Recipes/). As the default ones are created with default settings in mind.

**Comment by Iomega0318** [comment]
Well the problem is when disabling the Channels it will prevent my server from starting, it won't crash it just spits out that error repeatedly and wont allow the server to continue..

**Comment by yueh** [comment]
Cannot reproduce it. My testserver does throw some errors around but will start normally.

**Comment by Iomega0318** [comment]
That's why it's weird, I can start the server fine with the error on my desktop but on my actual server itself it will not continue past the error..

**Comment by thatsIch** [comment]
you could set the logger granularity to a finer setting, in hope that something more informative is printed.

**Comment by usafphoenix** [comment]
have you tried it with a NEW world? 
because disabling the channels in my config appears to remove the ME controller completely. but if you do so in a world you already created that has a me controller...well, it may cause it to not start. try-re-enabling channels to see if it starts up fine.... then create a new-world after resetting it to "channels false". if that boots up fine. your world is obviously got ME controllers or other stuff that relies on channel-function and won't function properly without

**Comment by Iomega0318** [comment]
@usafphoenix  I would agree if I didn't know how the server worked lol, it will start with missing items but it will just ask you to delete them and continue to load the world, the same way it works when adding then removing a mod in single player.

@thatsIch how would I do this? Maybe I can get some more information on why it works on one computer and not another, which is till super weird to me..

**Comment by Iomega0318** [comment]
***UPDATE***
Beta 22 seems to fix this issue.
This can be closed for now, thank you.

**Comment by Iomega0318** [comment]
Well that is just so weird.. this error is now back in Beta 23..

**Comment by thatsIch** [comment]
There is no way, that **exactly** the same error is the result

**Comment by thatsIch** [comment]
Cant confirm, works fine for me, no logs

**Comment by Iomega0318** [comment]
I know this is why I am saying it's weird, it will fail on my server but work fine on my desktop. Let me see if I can get the error, it's a pain to try and grab as it literally just spams the consoles..

**Comment by Iomega0318** [comment]
There are no crash logs as it doesn't crash, it just continually spams the console with the following:
http://paste.ubuntu.com/10736702/

**Comment by thatsIch** [comment]
It just states, that you did not modify all the recipes which contain invalid stuff.

**Comment by Iomega0318** [comment]
All I did was set channels to false.

**Comment by thatsIch** [comment]
as I said, you did not change the recipes. Even if you disable channels (which means you dont have ME Controller, Smart Cables, Dense Cables etc), that does not mean, all recipes are magically changing (though it would be convenient)

**Comment by thatsIch** [comment]
also you can disable the displaying of these errors in the recipe files

**Comment by Iomega0318** [comment]
Ahh I did not know that, then I have two questions on that:
1. Do I have to manually alter said recipes? If so where and how as I've never had to do it..
2. Why does it throw this error on my server but not on my desktop? (Exact copy of server folder.)

**Comment by thatsIch** [comment]
http://ae-mod.info/Custom-Recipes/

**Comment by Iomega0318** [comment]
Using custom recipes I removed the only piece I could find mentioning a controller, which was this:
```shaped=
	ae2:BlockSkyStone:1 ae2:ItemMaterial.PurifiedFluixCrystal ae2:BlockSkyStone:1,
	ae2:ItemMaterial.PurifiedFluixCrystal ae2:ItemMaterial.EngProcessor ae2:ItemMaterial.PurifiedFluixCrystal,
	ae2:BlockSkyStone:1 ae2:ItemMaterial.PurifiedFluixCrystal ae2:BlockSkyStone:1
	-> ae2:BlockController
```
Which I found in port.recipe, I still recieved the same error..
So I tried setting erroronmissing to false, which I found in index.recipe and it still didn't work, any other ideas?

**Comment by thatsIch** [comment]
Controller is being removed by default if you disable channels, 
what you want is to remove the parts which are still ingame but not removed like QNB Recipe (which requires dense cables)

**Comment by Iomega0318** [comment]
Alright I will give that a try, thank you lol.. sorry I'm such a noob :)

**Comment by Iomega0318** [comment]
I would just like to state that appliedenergistics2-rv2-stable-1 seems to "hopefully" permanently fix this issue.
