### ISSUE TITLE
[Idea/Feature request] Interfaces recognizing named containers

### ISSUE THREAD

**Issue by Haaki-** [AppliedEnergistics/Applied-Energistics-2#1140]
Thing is, I'm using a lot of chests as the target for a crafting operation. Because i use pipes etc. to transport the items through a complex crafting operation. For example when automating the pure crystals. 
My request is that, when using the interface terminal, if the container is named, the custom names will show up instead of twenty different chests.

**Comment by yueh** [comment]
#1008
