### ISSUE TITLE
[idear] Molecular assembler

### ISSUE THREAD

**Issue by Goten87** [AppliedEnergistics/Applied-Energistics-2#1141]
hello AE team
i'm loving the mod but i think 1 thing is sad and with to see in updates if its somthing that you also like
right now all the Molecular assemblers are the same thing in the interface terminal
will be nice if we can set a name for the Molecular assembler so then we know what assmbler we use

for exemple i love to name 1 of the asseblers Thermal Expention
so that when i make a new pattern i for thermal expention i can include it in that 1 assembler
sins i love to order my stuff by mods
i have right now 4 interfaces on 1 assembler so i want to have 1 for TE and 1 for AE and 1 for vanilla stuff

right now there is no good way to see that but when we can name the Assemblers it will be eazer to see

then in the interface terminal you can look for Minecraft or Thermal Expenion and see the 4 interfaces on there

**Comment by yueh** [comment]
#1008
