### ISSUE TITLE
[idear] Channels

### ISSUE THREAD

**Issue by Goten87** [AppliedEnergistics/Applied-Energistics-2#1142]
i right now have my channels off sins i dont like it at all
i have a downside to it that i think is realy sad
i love the smart cabels and bigger cables
so i think its sad that when i set channels off i cant use the cables anymore
i love to still use them like a main line for the biggest one and then go down to the smaler ones as i make my rooms

so can you make it that we can use the cables without channels

**Comment by yueh** [comment]
Not possible.
