### ISSUE TITLE
Not Enough Items Right click CTD

### ISSUE THREAD

**Issue by arachnidan** [AppliedEnergistics/Applied-Energistics-2#1143]
Minecraft crashes to desktop when right-clicking anything at nei item list. I have a lot of mods  but I narrowed the crash down to 3 mods. This bug only happens with the following mods installed:

Minecraft 1.7.10
forge 10.13.2.1343 (no optifine) and 10.13.2.1291
NEI 1.0.4.94
CodeChickenCore 1.0.4.35
AE 2-rv2-beta-21 (works fine with 18) (couldn't test 20 or 19, no rotarycraft)
OpenComputers 1.5.4.11 and 1.5.4.10

OpenComputers alone works fine, so does together with AE b-18.

Crash with full list of mods:
Raw crash report: http://pastebin.com/raw.php?i=FJ1gZvYU

Crash with OpenComputers 1.5.4.10 + NEI 1.0.4.94 + AE beta 21
Raw crash report http://pastebin.com/raw.php?i=5MEiRnEy

**Comment by thatsIch** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/1134

**Comment by arachnidan** [comment]
Unfortunatelly, minecraft is still crashing with build 22.

**Comment by jznomoney** [comment]
I also am getting this crash http://pastebin.com/pxFmPU0r

**Comment by thatsIch** [comment]
Fixed indev

**Comment by arachnidan** [comment]
I can confirm this is fixed. Good job =)
