### ISSUE TITLE
Molecular assemblers not powered.

### ISSUE THREAD

**Issue by DHeppell** [AppliedEnergistics/Applied-Energistics-2#1147]
Molecular assemblers don't appear to get powered by block interfaces, when the interface is forced to a certain direction. However they do get powered if the interfaces are left omni-directional.

**Comment by yueh** [comment]
This is intentional, every directional interface (includes part interfaces) does not create a connection into the direction they are facing. This allows 2 block/part interfaces to be adjacent and not connect both networks.
