### ISSUE TITLE
Inventory ME Terminal Disconnected  

### ISSUE THREAD

**Issue by MakerTim** [AppliedEnergistics/Applied-Energistics-2#1149]
When i put stuff In or Out of an ME terminal, there is no problem
but when i first put stuff in it, and later on puting stuff in it, i get disconnected.

Doesnt happen the other way around.

forge-1.7.10-10.13.2.1291-universal
appliedenergistics2-rv2-beta-21

**Comment by Aevaris** [comment]
Already documented. see #1118 or #1127. Use beta 18 for now.
