### ISSUE TITLE
ME - Status Terminal

### ISSUE THREAD

**Issue by AlgorithmX2** [AppliedEnergistics/Applied-Energistics-2#115]
Much like the networking tool, it would show you your energy usage, network items, and so on. The status terminal would show you how many channels you are using, how many are free, energy usage, energy storage, items on network, and storage used. May use a channel?

Originally Posted by Hypertacos

This issue was migrated; For original details see http://ae-mod.info/Tracker/1078/

**Comment by Blue64** [comment]
The network tool does help, but something to track the Channel Usage would help (especially with certain Achievements lol), I was also curious what THE maximum possible number of Channels actually is on a network.

**Comment by wlhlm** [comment]
@Blue64 [/u/therealtkh on Reddit got 22,841 channels from a controller](https://www.reddit.com/r/feedthebeast/comments/3qf18u/extreme_me_controller_with_22_841_channels/)

[![22841 Channel ME controller](http://i.imgur.com/HHXmopHh.jpg)](http://imgur.com/a/ceG7ii)

**Comment by thatsIch** [comment]
Where is the controller lol :laughing:

**Comment by Blue64** [comment]
He also made a nice few videos of this build, it's got a LOT of P2P, inside and out both lol I'm not entirely sure how the "Backbone" stuff works, unless this counts as a separate network, which would just make this a Router Hub if I'm not mistaken.
