### ISSUE TITLE
Crash when opening any bus or interface

### ISSUE THREAD

**Issue by mchaggis12** [AppliedEnergistics/Applied-Energistics-2#1150]
http://pastebin.com/MVqQg4YX

When right-clicking on an interface or bus in RV2_21 a crash occurs. Tried a fresh install of forge without optifine and no other mods less NEI. Log attached.

**Comment by mchaggis12** [comment]
Issue does not appear to be present in RV2_15

**Comment by Aevaris** [comment]
Already documented. See #1118 or #1127

**Comment by mchaggis12** [comment]
My bad, thanks.
