### ISSUE TITLE
type numbers in search bar of terminal

### ISSUE THREAD

**Issue by Maelstraz** [AppliedEnergistics/Applied-Energistics-2#1151]
So, problem is simple: i cannot type any numbers in any type of terminal (storage, crafting, pattern etc) until direct click on search bar. Letters working fine.

Found that trying to seek p2p-bus recipe.

**Comment by yueh** [comment]
That is a minecraft feature allowing you to swap items on the hotbar with the number keys.
So it will intercept them until you have focused an input field.

But there should be a terminal mode which automatically focus the input field (but then losing that functionality)

**Comment by 61352151511** [comment]
If you have a numpad those numbers work, if not, not sure of a solution.

**Comment by Xolroc** [comment]
So it's not possible to make the input field automatically focus itself without having to click on it?
