### ISSUE TITLE
Question Quantum Network Bridge

### ISSUE THREAD

**Issue by abdullamu** [AppliedEnergistics/Applied-Energistics-2#1152]
hello
can i link 3rd bridge if i have already have 2 (e.g. one connected to the controller linked to one in botania area and i want to link 3rd one to my blood magic area but to the same bridge )
i tried it and its not working so is it intended or there's special way to do this ?

**Comment by lehjr** [comment]
The Quantum Network Bridge only works in pairs because the Quantum Entangled Singularities only work as a pair. You can have multiple pairs pairs though.

**Comment by abdullamu** [comment]
alright but can i connect all of them together and only one of them connected to the controller ?

**Comment by lehjr** [comment]
Depends on your setup. They only support 32 channels. They more or less act as a virtual cable connection across 2 points in space.

**Comment by abdullamu** [comment]
so across two points only no more ? thats what i want to know

**Comment by lehjr** [comment]
2 points which is why they only work in pairs. You can have multiple QNB's, but they only work in pairs.

**Comment by abdullamu** [comment]
thank you its the answer im looking for , its sad to know that because i'll have to setup lot of them but well its better i just got idea how to do good design :)
