### ISSUE TITLE
Problems with WorldGuard and Factions (Cables, panels)

### ISSUE THREAD

**Issue by NoireMann** [AppliedEnergistics/Applied-Energistics-2#1154]
Hello!

I have a problem on my Bukkit server - I can wrench cables and panels (tile.BlockCableBus) in a claimed chunk.

I've checked the source, and i think fixing of this bug won't be complicated.

I think it just needs to add some "interact" function in CableBus class, cuz other blocks are working right with claimed land: I can`t wrench and break ME Drive for ex, but i can break cables and buses.

Hope you will help me with this ^^
Thanks.

**Comment by yueh** [comment]
We do not support bukkit or cauldron.

**Comment by NoireMann** [comment]
But it is not directly bukkit-related thing, this is just a matter of 2 strings of code :C

**Comment by Cisien** [comment]
You are welcome to submit a pull request if you have a solution, otherwise we don't provide support for cauldron/bukkit. Due to the fact that those systems tend to break forge mods. Additionally, they are no longer being developed due to legal issues.
