### ISSUE TITLE
Network "loses" Channels when using Wireless Terminal at max Range

### ISSUE THREAD

**Issue by Dr-john-Zoidberg** [AppliedEnergistics/Applied-Energistics-2#1157]
Hi there.
i have an odd problem with my me system.
everytime i try to request a craft via my wireless terminal at about 200m out of 214m
every device that is not directly connected to a controller loses its channel for about 10-15 seconds
i play on my local server with the latest Direwolf20 Pack (with a few more mods)
ae2:   appliedenergistics2-rv2-beta-18
yes i have more than enough channels and about a stack of full dense energy cells
yes my controller is a valid structure
i use smart/dense cable on every device to see where it disconnects (directly after 1 block after the controlller)
i connected my access point and my security port to the controller.

maybe its my wall of me drives (4x4 directly sitting on a line of controllers) ?

**Comment by mindforger** [comment]
you forgot to mention one important point: do you even chunkload ? :) 200 Blocks sounds like near the border of chunks being loaded, and due to your complexity of your network, an continous update of the chunks may cause this "lag"

**Comment by Dr-john-Zoidberg** [comment]
oh of ocurse sorry about that :D !
i chunkload the entire network and the spot im standing and the space between. (the whole space is like a player hub)

**Comment by NitroxydeX** [comment]
@Dr-john-Zoidberg We had the same issue since a couple of days. Today we figured out that two terminal weren't loaded with a chunkloader - so the ME System crashed itself, because there was something it could not connect to. Strange thing, that the ME System knows that there is a terminal and it cant load it.

**Comment by Cisien** [comment]
The way it works is that whenever the network changes, ae will reboot. When a chunk loaded or unload the network changes. Chunks on the border will reload often and cause this issue. Some mods, and even vanilla can c cause chunks to load and unload very frequently, which can cause lag and ae2 issues.

**Comment by Dr-john-Zoidberg** [comment]
oh you mean ANY chunky containing any part of the me (even a terminal 3000 block away) has to be loaded?
thanks a lot  for the solution im gonna try it out today :D

**Comment by Dr-john-Zoidberg** [comment]
still crashed the network
its only happening when i stand inside of chunks where subnetworks are in!

**Comment by thatsIch** [comment]
sounds like a network setup issue or so,
try to cut parts of your network until you cant reproduce it anymore.

**Comment by Dr-john-Zoidberg** [comment]
i already took my network apart
its only reproduceable when im near a subnetwork :(

**Comment by thatsIch** [comment]
Then Screenshot of connection between those networks
and maybe SS of the subnetwork itself
