### ISSUE TITLE
[Feature request]Trans-dimensional wireless crafting terminal

### ISSUE THREAD

**Issue by megamanzteam** [AppliedEnergistics/Applied-Energistics-2#1158]
I was thinking of a more complicated recipe for a wireless crafting terminal that can work in any dimension. Also to either upgrade the wireless access point or a new access point that can have unlimited range but have a massive power draw (and be rather expensive). Another item that could be of use (but don't see you easily implementing), will most likely require some UI changes would be a universal trans-dimensional terminal. It would need a button to change modes from access, crafting, patterns, and me interfaces. I know some would consider it lazy, but I would expect it to be insane expensive. Otherwise maybe these ideas could be a creative items only. Thank you for your time and consideration!

**Comment by Cisien** [comment]
Already possible with the qnb. It's bulky, but it's cross dimension. The wireless crafting terminal has been rejected many times already both by algo and the current team.
