### ISSUE TITLE
cpw.mods.fml.common.LoaderException with rv2 build 22

### ISSUE THREAD

**Issue by levicc00123** [AppliedEnergistics/Applied-Energistics-2#1160]
a full crash report can be found at https://gist.github.com/levicc00123/41e01b2886c193b167de.

**Comment by lehjr** [comment]
That's a Thaumic Energistics crash see https://github.com/Nividica/ThaumicEnergistics/issues/155
It's caused from changes in AE2, specifically this commit: https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/1073
