### ISSUE TITLE
Issue with terminal and chest gui

### ISSUE THREAD

**Issue by Aredrih** [AppliedEnergistics/Applied-Energistics-2#1162]
When I click on an empty slot in a terminal or a me chest or when I click on a slot regardless to if it's empty while holding a item stack. Then the bug happen and I'm send back to the multiplayer screen.

* version: ae2 rv2 22
* mod installed: forge, ae2
* log: [here](http://pastebin.com/E6RPJYen), extract from the console from the loading of the world to the unload of it (the crash) it doesn't completely crash and I don't found any mention in the logs.
* fix tried: downgrading the forge version to the last recommended version (10.13.2.1291)
    * effect: none, it keeps crashing.
* other crash encounter: [a random one](http://pastebin.com/nXF77fZZ) which seem completely unlinked and happen in the last forge version (10.13.2.1343)
* loading log: [here](http://pastebin.com/hjGUT7du) (end on the sound engine start)

EDIT: ~~Seem likely to 1143 (more or less (issue with gui interaction))~~ are too different in fact

**Comment by chardo440** [comment]
I believe I'm getting the same issue as you. I crash though any time I take a stack out of the Crafting Terminal

http://pastebin.com/FRpLz1qJ

**Comment by yueh** [comment]
Mostly #1127

Please open another issue for the random one (the p2p + rf one).
There might be an issue with the removing of optional apis through the ASM update.
