### ISSUE TITLE
P2P Terminal

### ISSUE THREAD

**Issue by ztk4** [AppliedEnergistics/Applied-Energistics-2#1163]
So first off, this is a suggestion not a bug, I hope I am putting this in the right place (pretty sure I am otherwise I wouldn't post!).
## The Problem

Before I get into details of the idea, I'll give an example of the problem I'm trying to solve. Imagine wanting to create a massive AE network in a huge base, but you foresee yourself needing 500+ channels, and you want to spread out your machines over the surrounding chunks to avoid lag. Instead of running tons of dense cable adjacent to each other in all directions, it obviously makes sense to run far fewer dense cables outwards as a sub-network, and run several P2P tunnels over that sub-network. 

Given that, a good design would be a sub-network with a network controller or two, allowing sets dense cable transmitting a total of 32+ channels that connects different regions of your base back to a central using P2P tunnels. This central location would have the network controller multi-block for the main network, and the P2P tunnels would come directly out of the faces of the controller and into the sub-network.

The only setback with this design is _book-keeping_. Essentially, after adding more than 32 P2P tunnels sending channels from the main network over the sub-network, it would become increasingly complicated to keep track of which P2P's are connecting to which and how many channels the parent P2P is sending.
## My Proposal

I know this is not exactly _crucial_ to the functioning of your mod, but I think it could add a useful (_and **not** redundant_) feature that is in the style of the rest of the mod.

I am proposing the addition of a single block: the P2P Terminal.
### "Requirements"

Assuming that each P2P tunnel placed in the world has a couple of states that can be distinguished between (or assuming that they could be changed to keep track of these states internally), then I believe the following would at least be feasible. The states that would be required are a boolean representing whether or not the P2P is a parent node (sending channels versus receiving); how many channels any given P2P is transmitting/receiving; and if the P2P is a child node, some unique identifier of the parent node it is receiving channels from. The last bit about child nodes is only needed for a more advanced feature of my idea that is not necessary for the functionality of the proposed block.
##### The Interface and Main Functions

The terminal would be placed on the sub-network that the P2P tunnels communicate over. Its interface would be very similar to that of the Interface Terminal. It would display a line for each parent P2P sending channels over the sub-network (similarly to how the Interface Terminal has a line for each interface), except instead of having 9 inventory slots to place patterns it would have 32 grayed out tick marks (or some other representation of the 32 available channels). For each channel that the given parent node is transmitting, a tick mark would be colored in (maybe purple?).

It is reasonable to note that a P2P connected with a smart or fluix cable to the back would only be able to transmit 8 channels. However this is not a limitation of the P2P tunnel, but of the network design, and so the **best implementation** would probably be to consider all P2P's to have a **maximum of 32 channels** when viewed in the terminal (so the sum of colored in and grayed out tick marks is always 32). 

A P2P Tunnel that has not been bound (not a parent or child) should probably **not** show up in the terminal. If it is connected with a child node, it would then show up in the terminal. If it is loaded with configurations of a parent node, it would become a child and not show up in the terminal. 
##### Paring and Memory Cards

In addition to offering an organized way of viewing the network usage of your P2P tunnels, I thought this block could also organize the pairing of P2P parent and child nodes.  The current system of pairing P2P would not be removed, this would simple be an addition.

This could be done one of two ways. First, the terminal's interface could have a single inventory slot where a memory card would be placed. This slot could be on the right hand side (similar to the upgrade card slots some of your machines have), or in any other convenient location (a corner maybe?). Once a card is in this slot, there would need to be a way of selecting a parent P2P tunnel in the central portion of the interface. This could be done, for example, by allowing the last clicked line in the central portion to be visibly selected (shaded darker or something), and having a "Bind" button near the inventory slot to click. Upon this event, the memory card would be loaded with the configuration information of that parent node. This card can then be used to configure future child nodes.

Another option would be to have no inventory slots or buttons, but to allow the card to be "placed" in a line as if each one were a very long inventory slot. Upon the card being placed in a given line, it would immediately be placed back in the player's inventory (or dropped to the ground if full) configured to that parent P2P.

Another worthy note would be that you could also implement both of the above techniques, but allow a P2P tunnel item to be used instead of a memory card, to bind directly to that tunnel. I doubt this is easily doable though because I suspect the P2P tunnels must be placed and connected to the sub-network their parent is on before being bound to that parent.
##### Bonus Feature (Less Crucial to Functionality, But Cool and Useful)

This is where the bit about a child node have a unique identifier of its parent node comes into play. Instead of coloring each channel tick in the same color, a color could be assigned to each child node associated with that parent, and the ticks being sent to that child are colored in with its color.

This would be simply done given a parent node's load, and it's children's loads. For example, if a parent is sending 15 channels, and it has three children receiving 7, 6, and 2 channels. Then 6 ticks could be colored purple, 6 green, 2 orange, and the rest grayed out.

Additionally, since the maximum number of child nodes is 31 (I'd say 32 [1 channel each], but I don't think you could hook up a parent and 32 children together without having channel issues), the color pallet would only have to support 31 (or 32) different colors (in addition to the grayed out state).
##### The Block Itself

Obviously, the block itself would be a multi-part just like any other terminal, and similarly require a data channel. 

Its crafting recipe would almost definitely contain an illuminated panel. It would probably contain a memory card and/or a P2P tunnel. And it would most likely contain at least some form of processor.
## Final Words

I know this wouldn't be the easiest of features to add, but I was thinking about your mod and some efficient network designs and I though this was at least a worthwhile idea to have you consider!

And honestly, if anyone had read this far, thank you for your interest/dedication and time because I definitely wrote a whole lot here :P

**Comment by 4poc** [comment]
+1 some way of telling how p2p tunnel are wired is really needed. I saw a video[1] where someone proposed renaming the memory card (used to set the tunnel) to the coordinate of the "source" tunnel and placing it in an item frame next to the destination tunnel.

[1] https://youtu.be/j-SQ0AvGA7c?t=1491

**Comment by yueh** [comment]
Thanks for the very detailed suggestion. It does overlap with the other issues about improving P2P, but it adds a new idea to it.

But there are some things to considered.

First of all, brute forced or poorly designed networks should be never rewarded or at least not better than carefully planned ones and also not encourage their use in general.
For example nobody forces you to only use a single underlay network. Instead you could use a smaller network with just a normal cable for each section. So it is suddenly not tracking how do these 192 P2P tunnels on the same network link together, but instead just 16 tunnels on each and then also use a red cable leading to section 1 and a green cable to section 2.
The same is true for P2P tunnels in general. They have their uses, but they are not always the best option and using the best option should be more rewarding/easier to manage.
There are basically already options to make it easier, you just need to use them.
Of course there should be some QoL improvents for tunnels, but they need to take the design goals into account.

Similar about displaying the channel use. The current way is to use a smart or dense cable as they indicate it. So you can just put a dense cable between the controller and P2P tunnel to view it. Of course this is less compact, but we do not really aim at making the most compact version also the best one. Consider it a tradeoff. If you want to have the most compact setup, you have to abandon another feature for it.

A terminal is also pretty stationary. So to be really usefully you need one near most P2P tunnels.
So most people will probably see it as setback, if they would now also need to craft them and waste a channel for them. Or they will be used as mountable tool, but then will cause issue when placed on fully utilized cables.

I am personally doubtful about the actual user experience and if it really improves it.
Scrolling through a list of potentially hundreds of entries does not make it easier to understand how the tunnels are connected. You have to identify the tunnel by the coordinates or name, something you will probably not know, if not next to them. Then try to remember, if the displayed connection is actually the one you considered.
Also coordinates are debug data and not really displayed ingame (outside debug tools), so relying on them is also not a good design. They can be helpful, but should never be the only option.

**Comment by emperor06** [comment]
When I was tracking down potential wiring issues on my network that could explain a bug I have, I made a quick hack so that right-clicking a P2P Tunnel with an empty hand displays some "debugging" information in chat. It looked like this:
[Source] 15 channels, (x=..., y=..., z=...)
[Dest 1] 8 channels, (x=..., y=..., z=...)
[Dest 2] 8 channels, (x=..., y=..., z=...)
[Dest 3] 5 channels, (x=..., y=..., z=...)
I quickly realized that's all I would ever need. Source or destination (in case I misclicked with the memory card), the number of channels, and the coordinate to find them all if I'm lost.
As yueh said, a well planned network makes the use of coordinates useless. Using names, colors, frequencies, or whatever is cool but unnecessary when the network is not a big mess :)
On the other hand, having a display of the number of channels that go through a P2P is, imho, mandatory. On the destination sides you can always put a piece of smart/dense cable on the P2P so you can read the number of channels. But on the source, when it's directly connected to a ME Controller, you have absolutely no option other than browsing all the destinations and count the channels manually.

One can say that colored dense cables can be used to connect P2P to the controller but that's wrong. There are cases where it's impossible. For example, when the controller has a "hole" in it. The 4 inner faces cannot be accessed other than putting P2P tunnels directly on the faces.

So for me, the best improvement we can get is a display of the number of channels on Waila, just like smart and dense cables :)

**Comment by RAnders00** [comment]
@emperor06 This argument was already made, basically it ends in performance issues when using colors. (Insane amount of colors possible; leads to possible performance issues)

**Comment by emperor06** [comment]
Nope, you misunderstood me. I was not talking about colors to differentiate tunnels, I was referring to those strips painted on smart cables that represent the number of channels. That's my bad, I should have say something like "light strips".

**Comment by RAnders00** [comment]
Sorry then. My bad! I guess you want to know the leftover channels on a ME P2P tunnel connection visible via stripes?

**Comment by emperor06** [comment]
Yeah, I think it's a shame the lowest tier pieces of network (smart cables) can tell you the channels used while the top tier (P2P and QnB) can't. Not a request tho, just a suggestion. But that diverges from the OP's proposal, sorry.

**Comment by Gameswithjohn** [comment]
This thread is just about what i was going to ask about/suggest(though i'll admit much more thought out and professionally done than i had planned). It all comes down to the creating of a much larger ME network while somewhat working within confined spaces and limitations. Personally I hit the wall when trying to use the P2P networks to access a great deal of outside storage. Admittedly I could probably import it all into the ME system itself, but that isn't always the easiest/best option for the  situation. Beyond raising the limits of each cable my own thought was to possibly change how the networks handle connections, maybe counting a "channel" as a whole and not each part individually, at the least when concerning connected P2P networks since in essence they are only one channel just with multiple ends. I know this next idea has to have been suggested many times, but a solution to some of this might be to allow the connecting of smaller networks(with the controllers, similar to networking multiple smaller computers into a larger network) or to possibly implement a limited wireless P2P connection bypassing the limitations of planning out and running many cables to each added group to your ME system.

**Comment by thatsIch** [comment]
> connecting of smaller networks(with the controllers, similar to networking multiple smaller computers into a larger network)

Sub-networks are the go to solutions for me, you sacrifice efficiency for simplicity. For example I have one subnetwork to process all ores. For a whole processing network I only use 2 channels on my main network, by offering the ores to the subnetwork through a storage bus and offering the ingots back to the main network through another storage bus

**Comment by DahDude** [comment]
I absolutely think this should be added. My AE System is a complete mess of p2p tunnels and cables that I need to reorganize. This would definitely be something I could see myself using very much. This is a 5 star IDEA
