### ISSUE TITLE
Disconnect from Server

### ISSUE THREAD

**Issue by yepidoodles** [AppliedEnergistics/Applied-Energistics-2#1164]
We updated from
rv0.stable build 10
to
rv2.beta build 22
As half the recipes didn't work since the new Mekanism was added and now when people are using their systems, taking items in and out of their terminals, they get disconnected almost everytime.
This is the error on the console;
https://www.dropbox.com/s/5rzqp2r2j88sgpo/AE%20ERROR.txt?dl=0
I hope this means something to someone, as it means very little to me, and I could really use the help if it's not an issue on your end.

Thanks
- Alice

**Comment by yueh** [comment]
#1127

**Comment by yepidoodles** [comment]
That doesn't tell me much... does that mean you can fix it or ? My server keeps crashing now
