### ISSUE TITLE
Ignore "Generations in Captivity" NBT data on bees in export bus

### ISSUE THREAD

**Issue by rowlock** [AppliedEnergistics/Applied-Energistics-2#1169]
Currently it's not possible to automate Forestry apiaries or alvearies with AE2, as used to be possible with AE1. The export bus considers each generation of bees to be different because of the "generations in captivity" metadata, and using a fuzzy card in the export bus completely disables any selectivity of bee species, creating a random mish-mash of bees and interbreeding.

Can we either ignore the "generations in captivity" tag when using an export bus without the fuzzy card, or have some kind of mechanism that will allow us to export a certain type of bee regardless of generation?

Thank you!

**Comment by Cisien** [comment]
Forestry support was dropped in ae2 because of the complexity of bees, in ae1 out was an intuitive hack anyway.

My suggestion is to prod your nearest ae2/forestry addon devs and ask for an soon mod to support this since we have no plans to support bees
