### ISSUE TITLE
Pattern terminal may cause item lost

### ISSUE THREAD

**Issue by kghost** [AppliedEnergistics/Applied-Energistics-2#1170]
Step to reproduce:

1. Make sure there are machine frames and no piston in the AE system
2. Open the recipe of glacial precipitator in NEI
3. Click the quest mark to complete the crafting grid
4. One of your machine frames in the AE system is lost

Ver:FTB Infinity 1.2.1, AE2 rv2-beta-8

**Comment by yueh** [comment]
Already fixed.
