### ISSUE TITLE
Renaming presses prevents them being usable in the inscriber

### ISSUE THREAD

**Issue by warlordjones** [AppliedEnergistics/Applied-Energistics-2#1173]
...as title. Using rv2.

**Comment by thatsIch** [comment]
That may be actually impossible. The required item for a recipe is as if. If you modify it, e.g. enchant it or rename it. It is technically not the same item anymore. 

If we ignore such information, a recipe with a fully charged item could be replaced by an empty one.

**Comment by XFactHD** [comment]
Also: Why would you name them? Doesn't make any sense to me.

**Comment by warlordjones** [comment]
I named them "Gold Press" "Diamond Press" etc.
