### ISSUE TITLE
BuildCraft Enegry Pipes

### ISSUE THREAD

**Issue by WinSide** [AppliedEnergistics/Applied-Energistics-2#1178]
P2P tunnels do not spend rf energy by using BC energy pipes and stagnant tunnel when clicking any energy pipes from BC

**Comment by thatsIch** [comment]
What do you mean with "spend RF energy"?
also "stagnant tunnel"?

**Comment by WinSide** [comment]
I'm sorry I do not know much English :(
P2P tunnels do not transmit RF energy using BC pipes and P2P tunnel does not change its type with ME on the RF when clicking any BC pipe on it

**Comment by thatsIch** [comment]
Works fine for me

![2015-04-04_12 21 24](https://cloud.githubusercontent.com/assets/2210496/6992281/29aa0c1c-dac5-11e4-980a-b235ec788e25.png)

**Comment by WinSide** [comment]
Hmm, In what assembly it was fixed, my server uses appliedenergistics2-rv2-beta-8 and Buildcraft 6.2.6 
![2015-04-04_18 41 12](https://cloud.githubusercontent.com/assets/7656576/6992322/338209ee-dafa-11e4-8791-83672574ceba.png)

**Comment by Cisien** [comment]
Give beta 18 a try
