### ISSUE TITLE
AE2/MFR Itemstack crash?

### ISSUE THREAD

**Issue by 016Nojr** [AppliedEnergistics/Applied-Energistics-2#1179]
Im not sure if it's caused by either AE2 or MFR, but im using Agrarian Skies 2 which i have not doublechecked yet, but is most likely the latest updates.

http://pastebin.com/FJn1RVA2

**Comment by 016Nojr** [comment]
It serms to be export buses, i am using 3 for my mob farm and i can open the others, i tried replacing the one that was crashing me, and it still crashes? The export bus is on top of an Extra Utilities trash can. I have tried this multiple times

**Comment by yueh** [comment]
#1127

**Comment by 016Nojr** [comment]
Oops
