### ISSUE TITLE
Log to server log when a security terminal is broken.

### ISSUE THREAD

**Issue by AlgorithmX2** [AppliedEnergistics/Applied-Energistics-2#118]
Hello there

As it says in the description, it would be very helpful for server admins if, whenever a security terminal is broken, it logs the player name and security terminal location to the server log.

Regards,
ShamblerDK, owner of Awesomesauce 1.7.10

Originally Posted by ShamblerDK

This issue was migrated; For original details see http://ae-mod.info/Tracker/1099/

**Comment by Technici4n** [comment]
Modern server tools allow monitoring when specific blocks are broken, and by whom. Hence this is unnecessary.
