### ISSUE TITLE
Covers are blocking chests

### ISSUE THREAD

**Issue by agowa338** [AppliedEnergistics/Applied-Energistics-2#1182]
I am playing the latest Direwolf20 pack and I have installed a chest with an import bus at top.
If I place a cover on the side of the import bus, the chest can no longer be opened by hand.

**Comment by thatsIch** [comment]
Works for me

![2015-04-03_15 52 04](https://cloud.githubusercontent.com/assets/2210496/6983027/6e28ff1c-da19-11e4-965d-b5f35f8de8e5.png)

**Comment by agowa338** [comment]
Well, it doesn't for me
![2015-04-03_15 55 25](https://cloud.githubusercontent.com/assets/2544867/6983074/f3cc9ebc-da19-11e4-95d0-488ff0f18dc4.png)

**Comment by XFactHD** [comment]
I have the same problem: If I place a solid block, underneath it a me glass cable and underneath that a chest, I can open the chest, but if I place a cable facade on the cable, I can't open the chest anymore.
