### ISSUE TITLE
Fatal error when dragging items to ME Terminal

### ISSUE THREAD

**Issue by Granik24** [AppliedEnergistics/Applied-Energistics-2#1183]
Depositing any item manually (without shift-click) will cause a server disconnection (Game error) most of the time. This occurs with all ME terminal variants.

Modpack "Tekkit Classic on 1.7.10 v 1.3.3" - http://technicpack.net/modpack/tekitclassis
Forge version: 1291
Crash/Log on server: http://pastebin.com/g9QBdJkJ
AE2 version: rv2 - beta22

Original issue: https://github.com/Granik24/tekkit/issues/1

**Comment by yueh** [comment]
#1127
