### ISSUE TITLE
Ticking GridNode

### ISSUE THREAD

**Issue by accessdenied0** [AppliedEnergistics/Applied-Energistics-2#1184]
Dear Applied-Energistics-2-Team,

Here I'am again... I got this time a weird issue and I'm not sure what is happening this time. I updated AE2, Mekanism, Thaumic Energistics and Extra Cells. But now I'm unable to load the world I recently played with and get every time If I load the world up I got this crash: http://pastebin.com/FjQBKBXw

Has this something to do with https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/1127 ? I'm not sure because the crash seem to be older and slightly different...

Anyway... I hope someone can help,

access_denied

**Comment by yueh** [comment]
Yes.

**Comment by accessdenied0** [comment]
Hi Yueh,

Very short, quick and precise. But what "yes"? "Yes" - You can help? "Yes" - It is the same as #1127?

I guess both... should I use in the mean time r2 beta-18?

Thank you,

access_denied

**Comment by Cisien** [comment]
Stick with 18 for now

**Comment by thatsIch** [comment]
Update
