### ISSUE TITLE
Crafting Job Crash

### ISSUE THREAD

**Issue by gixmy** [AppliedEnergistics/Applied-Energistics-2#1185]
I'm getting a crash when I try to start minecraft - see http://pastebin.com/UBU8VBSM

Last time I was in my world I setup an export bus. This was doing some auto crafting. I guess this is related given the crash report.

This issue has been reported previously by todeus at http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1294449-applied-energistics-2-open-source?comment=1168

**Comment by yueh** [comment]
#276
