### ISSUE TITLE
Terminals stop showing items, or show wrong item counts

### ISSUE THREAD

**Issue by Robzz** [AppliedEnergistics/Applied-Energistics-2#1189]
# The problem
Lately, the terminals in my ME network have started to behave strangely. Sometimes (quite often actually) they will stop showing the contents of the ME network. The fix is to just restart the network.

Also when they work, they're confused about how many items are stored. Say there are 20 diamonds stored in the network. If i pick them up and deposit them again, the terminal will show up 40 diamonds, sometimes just for a second, sometimes for as long as the terminal is open.

Then, there are two cases.
1. The game has been started quite recently, the wrong number of items being displayed is pretty much the only problem, the terminals don't stop working.
2. The game has been running for a little while. The terminal show 40 diamonds for a split second, and then all the diamonds disappear right away. After this, if I leave the terminal and reopen it, no items will show up, on any terminal. Note that this doesn't happen on a fresh game restart, but it happens eventually, and when it does, it keeps happening if i pull a single item out. I can make this happen within the 5 minutes after I load the game.
Note that when I reset the system, the items show and the numbers are right, so nothing is lost, the ME system just gets very confused. Also even if the ME system doesn't show any contents, I can put stuff in it, it will show when i reset the system, and it will show the storage use increase when I look at the cell even without restarting.

These two issues could be related, as the problems appeared at the same time as far as I can tell. I strongly believe they are.

# What I've tried
* The entire network is chunkloaded (it's not that big anyway)
* There are no power issues, the network taps directly in my energy storage, and there is an energy cell to buffer some energy just in case.
* Disconnecting and reconnecting a terminal does nothing.
* Disconnecting and reconnecting the ME Drive shows the items, until the terminals stop working again. I would guess the problem lies in the ME drive.
* This is reproducible. The wrong number of items being displayed happens every time, the terminals refusing to work takes a little while to kick in but then it happens every time i pull items out.

# What the ME network looks like
I have a single ME controller, and 4 dense cables going out of it. Three branches are related to autocrafting (one handles the AE2 inscribers and a charger, another handles the molecular assemblers and AE2 Crystals automation, and the last one has all my processing machines) and the last one goes to the base entrance, the ME drive and all the terminals are on this branch. It's also responsible for pulling energy inside the ME network. And that's about it.

# Information
* Modpack : FTB DW20 1.7.10 v1.2.1
* AE Version : AE2-rv2-beta-pre9 (tried with versions as up as beta16)
* Single player world.

I've tried to be as complete as I can describing the issue (and found no relevant open issues on the bug tracker), but feel free to ask me for any information you think is relevant!

EDIT : okay, I had a look at the closed tickets. There are a few related to terminals going haywire, but I don't think any of them describes the same problem I have.
Also I noticed my AE2-version is a bit old (thought it was more recent since the modpack was updated recently), i'll be trying a more recent one and report my findings.
EDIT² : tried some more recent versions. I can't get minecraft to start with the latest beta 22, but I tried with beta 16 (the only one whose changelog mentions terminals) and the problem is there.
EDIT3 : still present in beta23

**Comment by yueh** [comment]
Sounds really like a power issue. Pulling items out of the ME system will cost power and can cause the network to shut down.

**Comment by Robzz** [comment]
I doubt that, there is plenty of power and the cell powering the network is 99% full pretty much all the time, it's really there "just in case". Also the rest of the network keeps working, the only thing affected really is the terminal display (it sometimes shows the items being pulled in, and only them). I think even crafting continues as normal.

**Comment by XFactHD** [comment]
Is your network completely chunkloaded?

**Comment by yueh** [comment]
What type of energy cell?

**Comment by Robzz** [comment]
@XFactHD it is, but the network is very small, no part of it is far enough from me to not be loaded when I am at the terminal.
@yueh a regular AE energy cell. It permanently shows 399.82/400kAE. Other than that, the energy acceptor is plugged to my power storage, which is never even close to empty.

**Comment by XFactHD** [comment]
That's strange... At this point I am not able to help you anymore because I am just trying to learn coding and when I look at any mod's code I just say to myself: How the heck can that even work?

**Comment by thatsIch** [comment]
If this is reproduceable, just upload the world, try to cut out as much as possible, like other dimensions and chunks if possible. That way we can just load it into a new DW20 client

**Comment by Robzz** [comment]
I will, hopefully tomorrow (it could be later, I have a busy week ahead), after I've done some more testing. Also I noticed a few things I haven't mentioned yet :
* All kinds of terminals are affected regardless of where they are in the network, even wireless (except interface terminals of course)
* Once the bug occurs and the terminal screen is blank, if new items get pulled in the network (manually, crafting...), they sometimes show in the terminal, but they're the only items to show.
* The system sometimes recovers on its own, it can take a couple minutes. I haven't noticed any pattern.
* No need to reboot the network, moving/removing/inserting a storage cell in a connected drive will force the terminals to refresh and display contents again. I could setup a temporary workaround by having a cell constantly pulled out and pushed in a drive... I need to try that.

Do you have any advice on "cutting out as much as possible"? I have never shared my worlds before, Do you mean MCEdit it and remove everything but my base? Or should I just log in and remove stuff that isn't relevant? How do I clean up other dimensions? (I don't think I have any of those except the Nether)

Thank you for your assistance.

**Comment by thatsIch** [comment]
* Dimensions: just delete the folders in the save game
* MCEdit: yes, if you explored a lot, this can make it obviously very huge and hard to load up. 

also dont forget to do it to your real save game, but to a copy of it.

**Comment by Robzz** [comment]
I haven't forgotten about you guys, I just didn't have time and probably won't have time before friday at best. I will upload my world, I promise! :)

**Comment by thatsIch** [comment]
take it easy

**Comment by GetDownOnIt** [comment]
I have the same issue, seems my me interface and storage bus combo is causing the problem. Seems to mostly do it when items are being used in crafting that are normally stored in the interface/bus. I tried it with only 8 different items being stored in the combo so there was one slot available for overcrafted items to be returned to the me system that helped a little bit possibly. I do have a big enough setup to handle all the crafting for both the system and the combo.

The fix...Disconnected the me interface and storage bus combo for now.

I am playing on an infinity server version 1.3.4 with ae2 core rev-2-beta-8. Hopefully we will be updating the server this weekend to 1.4.0. and hope the latest version of ae2 for the pack corrects it.

I may do some more testing before then to make sure its not a texture pack issue or something silly like that. I am using the invictus texture pack just a fyi if needed.

Hope this helps the op until a fix is implemented.

**Comment by Robzz** [comment]
Interesting, I do have an interface storing items used for crafting, I'll see if I can reproduce that when I get some spare time.

**Comment by MC-Soupcup** [comment]
The server I'm on is having this same issue (beta-18 version by the way). However, I'm not sure if it's the same cause? A friend on the server with me noticed that it would happen after he crafted a Mekanism Energy Tablet. I had no luck reproducing it by that method in single player, but on the server he did it again and it started happening (Maybe because I have Mek. integration turned off due to the crash with v8 on older AE2 versions?). I can't guarantee that a Mekanism recipe causes it, but it seems to be what starts making it happen.

Now I looked into the server logs and found [this string of errors](http://pastebin.com/CsCwJpkB) that appeared as we started having the issues. At line 108 one of the errors says there was a critical exception handling an AE2 packet. The errors themselves, while they mention AE2 packet stuff, seem to point to something Resonant Induction is doing (looks like trying to use client-side stuff on the server at one point?) or a combination of the two. After restarting the server, it ended up crashing later on with [this crash report](http://pastebin.com/ycYyyLyg). We don't know what exactly crashed it instead of just spewing the errors into the console like it did before, but then again the error is slightly different in this report.

The modpacks the others who are having the issue use don't have Resonant Induction in it, so I don't imagine it to be the cause for them, but on my server, it appears that the removal of RI (planned to do anyways due to other things) has fixed the issue, we'll just have to wait and see if it happens again. It's been two hours without it happening again, but I'll update if it starts up. Hope this post helps in some way.

**Comment by thatsIch** [comment]
`resonantinduction` requires some class from Forge which is not available on the server side. That seems a new issue to me, which is not related to AE2 in that sense.

**Comment by MC-Soupcup** [comment]
Yeah I figured that would be the case, but I just thought I'd put it here since it mentioned so much AE2 stuff in addition to the other things, and that the removal of the resonant mods stopped the terminals from acting strangely. I wasn't sure if they were related in some way, basically. Still hasn't acted up again though, which is good.

**Comment by XFactHD** [comment]
I am sometimes encountering a similar problem, I have to have 64 of each processor sitting in an interface with a crafting card and a storage bus attached to it. Sometimes, one of the processor types begin to flash and then disappear for a moment from the terminal. I don't really like to have to do the stock keeping with an interface but issuing a crafting request from a level emitter with a crafting card doesn't work.

**Comment by thatsIch** [comment]
Level Emitter are supposed to issue the crafting via the redstone signal (like any machine which stops by receiving a redstone signal, but can produce them basically from void)

**Comment by XFactHD** [comment]
Does that mean that I need another level emitter to provide a redstone signal which then makes the level emitter with the crafting card issue the crafting?

**Comment by yueh** [comment]
No, this means that they will never craft on their own.
Either they emit a redstone signal to indicate something is being craft or something needs to be crafted.

**Comment by XFactHD** [comment]
Which means that I have to use an export bus switched to craft only.
