### ISSUE TITLE
Meteorite compass leads to no meteorites with Realistic World Generation

### ISSUE THREAD

**Issue by SunshineHunter** [AppliedEnergistics/Applied-Energistics-2#1190]
Information:
Forge 1.7.10-10.13.2.1043
AE2 rv2.beta build 18
Realistic World Generation Alpha 1.3.2
(BOP 2.1.0.1067)
Issue:
I started a survival world with RWG, BOP and AE2 in the world type "Realistic Alpha". I made a meteorite compass to find one, but whereever the compass led me to, there was nothing. It starts spinning in a chunk where there's supposed to be skystone, but the meteorite doesn't spawn.

Hope I can help!

**Comment by Techjar** [comment]
You checked underground right?

**Comment by yueh** [comment]
As @Techjar already said, check underground.

A compass will only point to skystone, if there was some actually placed in the same chunk. If there world generation (for whatever reason) later removes/replaces the skystone again without using the normal minecraft function, then we will not notice it and cannot update the compass.
Which then makes it an issue with the world generation itself and not AE2.
