### ISSUE TITLE
Issue with import bus

### ISSUE THREAD

**Issue by tomatflesk** [AppliedEnergistics/Applied-Energistics-2#1193]
So I had this setup to automatically process ores from my ME System using a block smasher, export in on one side, import on the other. It worked fine, but now suddenly two of the import buses changed color (the top two) and they don`t seem to work anymore. As far as I can see it`s not a channel issue. Why have these two changed color and will not work anymore?

![untitled](https://cloud.githubusercontent.com/assets/11791727/6990539/2bbd778e-da6e-11e4-864a-bf298dc4611b.png)

**Comment by yueh** [comment]
The lighter color indicates a missing channel, even Waila tells it.

**Comment by tomatflesk** [comment]
Right. But I can`t figure out what is causing it though. If you look at the Smart cable in front of the lower one, it only uses 1 channel out of 8. Why is it missing a channel? 

![untitled](https://cloud.githubusercontent.com/assets/11791727/6990596/e2455700-da6f-11e4-857a-cd2623486fc8.png)

**Comment by yueh** [comment]
The other end is important. It will starting from the controller with 8 channels and travel to the end of the cable. Each device requiring a channel will then reduce the amount by 1 until no channel is left for devices farther away.

**Comment by tomatflesk** [comment]
I feel kinda stupid now, but hey I`m still learning. I thought I had back-tracked all the way to the Controller already, but I found a small piece of smart cable between dense cables which was bottle-necking my channels.. Anyways, thanks for the help!
