### ISSUE TITLE
Interfaces and Steve's Factory Manager

### ISSUE THREAD

**Issue by vockleya** [AppliedEnergistics/Applied-Energistics-2#1194]
I'm trying to move items from an ME interface to a chest using Steve's Factory Manager.

This is the setup I was using to test this:
![2015-04-03_22 29 16](https://cloud.githubusercontent.com/assets/11792454/6991135/008e9c2c-da51-11e4-8649-0ec852ee014b.png)

The issue I'm having is that the system with the block interface works, and the one with the part interface doesn't. The part interface isn't being refilled when SFM removes items from it. Eventually the interface runs out of items, even though there are plenty in the ME system. 

I'm running the Beyond Reality modpack on the AT Launcher, but with the most recent versions of Forge and AE2.

**Comment by thatsIch** [comment]
Works fine for me

![2015-04-04_14 48 07](https://cloud.githubusercontent.com/assets/2210496/6992638/a2bb08b8-dad9-11e4-99e5-73ee825609f7.png)
![2015-04-04_14 48 14](https://cloud.githubusercontent.com/assets/2210496/6992667/a53b956c-dad9-11e4-8077-edd7272daf12.png)

**Comment by vockleya** [comment]
This is only an issue when using SFM to remove items from an interface. Taking items out by hand (or any other pipe system) works just fine.

Plenty of items in the ME system:
![2015-04-04_12 15 29](https://cloud.githubusercontent.com/assets/11792454/6993505/6d60070a-dac4-11e4-9ea1-32b0d38c850d.png)

After telling SFM to move 1 cobblestone from the interface to a chest:
![2015-04-04_12 17 08](https://cloud.githubusercontent.com/assets/11792454/6993514/88137046-dac4-11e4-992e-2b4c14829b7d.png)

**Comment by thatsIch** [comment]
So what makes you think, that it is an AE2 issue and not a SFM issue (since other piping systems are working)? 
Maybe SFM just forgets to notify the part that an update occured.

The standard test is always use something like a hopper.

**Comment by vockleya** [comment]
I'm not really sure either way. I just started here because I couldn't find an up-to-date SFM forum thread or anything. I'll post there as well when I do. It just seemed like an AE2 problem, since the block interface and part interface were behaving differently in the same setup.

**Comment by thatsIch** [comment]
Just tested this with hoppers and they work fine. 

![2015-04-05_13 04 57](https://cloud.githubusercontent.com/assets/2210496/6996653/63a8fc50-db94-11e4-8222-c2a5315b9b26.png)
