### ISSUE TITLE
ME Terminals Messing Up

### ISSUE THREAD

**Issue by kman469** [AppliedEnergistics/Applied-Energistics-2#1195]
I've had a working me system going on for a few days now, but all of a sudden this started happening. Everything is normal except for the fact I cant see my item pictures. Have no clue what the problem could be, I've tried resetting my server/ client and even replacing my terminals etc. Nothing works, so my final conclusion is it has to be a bug of sorts. Any info would be appreciated, here is a screenshot showing the problem. 
![2015-04-03_22 01 54](https://cloud.githubusercontent.com/assets/11792928/6991241/be61f6e4-da4d-11e4-95cb-dff8793f6cc0.png)

**Comment by XFactHD** [comment]
Do you by chance play on the ftb launcher?
If yes, does your console spit out an error when you open the terminal? If that's the case, please post that piece of the forge_latest.log.

**Comment by TheJulianJES** [comment]
You have OptiFine in your pack.

**Comment by abdullamu** [comment]
it happened to me when i disabled bees in my pack and i had some bees in my system so check if you have some item which is shouldnt suppose to be there or sometime forge micrblocks when it updates it makes changes so if u have some micro blocks in the system try to check on them if its with the name ("unnamed') than remove them should solve the problem hopefully if thats the problem .
