### ISSUE TITLE
Getting Started Video

### ISSUE THREAD

**Issue by Nonsanity** [AppliedEnergistics/Applied-Energistics-2#1196]
It is unclear who might be maintaining the official wiki, but I wanted to offer my own Getting Started video to the list of links the wiki provides—that is, if it is determined to be a worthwhile contribution.

Video Link: https://youtu.be/-sEiNbm1DdU

**Comment by thatsIch** [comment]
Welcome to the video club, nice video.
Liked it very much :)

http://ae-mod.info/Video-Spotlights/
