### ISSUE TITLE
Vibration Chamber showing only produced power in "ae"

### ISSUE THREAD

**Issue by thatsIch** [AppliedEnergistics/Applied-Energistics-2#1197]
* Should be **AE** ?
* Should it be converted depending on the client setting?

**Comment by thatsIch** [comment]
Related class **GuiVibrationChamber:drawFG**

**Comment by yueh** [comment]
Not sure about making it depending on the client setting as the only produce AE.
Letting them show a converted value could cause users to imply they are actually producing RF and also power RF machines.
