### ISSUE TITLE
NEI crash

### ISSUE THREAD

**Issue by linkinkov** [AppliedEnergistics/Applied-Energistics-2#1201]
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 04.04.15 22:45
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at appeng.core.features.DamagedItemDefinition.maybeStack(DamagedItemDefinition.java:51)
	at appeng.integration.modules.NEIHelpers.NEIWorldCraftingHandler.addRecipe(NEIWorldCraftingHandler.java:240)
	at appeng.integration.modules.NEIHelpers.NEIWorldCraftingHandler.addRecipes(NEIWorldCraftingHandler.java:227)
	at appeng.integration.modules.NEIHelpers.NEIWorldCraftingHandler.getRecipeHandler(NEIWorldCraftingHandler.java:178)
	at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:20)
	at codechicken.nei.recipe.RecipeItemInputHandler.lastKeyTyped(RecipeItemInputHandler.java:23)
	at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:307)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73869_a(GuiContainerCreative.java:301)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java)
	at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java)
	at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:474)
	at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:464)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1628)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at appeng.core.features.DamagedItemDefinition.maybeStack(DamagedItemDefinition.java:51)
	at appeng.integration.modules.NEIHelpers.NEIWorldCraftingHandler.addRecipe(NEIWorldCraftingHandler.java:240)
	at appeng.integration.modules.NEIHelpers.NEIWorldCraftingHandler.addRecipes(NEIWorldCraftingHandler.java:227)
	at appeng.integration.modules.NEIHelpers.NEIWorldCraftingHandler.getRecipeHandler(NEIWorldCraftingHandler.java:178)
	at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:20)
	at codechicken.nei.recipe.RecipeItemInputHandler.lastKeyTyped(RecipeItemInputHandler.java:23)
	at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:307)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73869_a(GuiContainerCreative.java:301)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java)
	at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java)
	at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:474)
	at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:464)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['linkinkov'/741, l='MpServer', x=1652,50, y=69,62, z=2346,80]]
	Chunk stats: MultiplayerChunkCache: 121, 121
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,45,0), Chunk: (at 0,2,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 33667986 game time, 34176265 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 57 total; [EntityZombie['Зомби'/768, l='MpServer', x=1700,44, y=25,00, z=2316,00], EntityZombie['Зомби'/769, l='MpServer', x=1699,50, y=25,00, z=2324,50], EntityEnderman['Эндермен'/770, l='MpServer', x=1711,47, y=33,00, z=2331,50], EntitySpider['Паук'/771, l='MpServer', x=1707,41, y=68,00, z=2354,72], EntityCow['Корова'/772, l='MpServer', x=1626,56, y=71,00, z=2394,94], EntityCow['Корова'/773, l='MpServer', x=1626,84, y=71,00, z=2392,19], EntityItem['item.item.arrow'/774, l='MpServer', x=1604,47, y=71,13, z=2369,44], EntityHorse['Лошадь'/775, l='MpServer', x=1616,45, y=72,00, z=2311,42], EntityZombie['Зомби'/776, l='MpServer', x=1629,50, y=54,00, z=2292,50], EntityZombie['Зомби'/777, l='MpServer', x=1624,03, y=54,00, z=2291,56], EntityClientPlayerMP['linkinkov'/741, l='MpServer', x=1652,50, y=69,62, z=2346,80], EntityZombie['Зомби'/778, l='MpServer', x=1629,56, y=54,00, z=2298,09], EntityWitch['Ведьма'/779, l='MpServer', x=1628,56, y=54,00, z=2292,44], EntityCreeper['Крипер'/780, l='MpServer', x=1697,31, y=25,00, z=2319,84], EntityCreeper['Крипер'/781, l='MpServer', x=1697,59, y=25,00, z=2318,97], EntityCreeper['Крипер'/782, l='MpServer', x=1705,78, y=25,00, z=2308,91], EntityCreeper['Крипер'/783, l='MpServer', x=1705,66, y=25,00, z=2315,06], EntityHorse['Лошадь'/784, l='MpServer', x=1687,22, y=71,00, z=2384,44], EntitySpider['Паук'/785, l='MpServer', x=1659,47, y=69,00, z=2285,38], EntityCow['Корова'/786, l='MpServer', x=1652,16, y=72,00, z=2287,22], EntitySkeleton['Скелет'/788, l='MpServer', x=1714,44, y=33,00, z=2339,56], EntityHorse['Лошадь'/790, l='MpServer', x=1660,13, y=70,00, z=2405,34], EntitySkeleton['Скелет'/791, l='MpServer', x=1713,00, y=33,00, z=2332,44], EntityHorse['Лошадь'/792, l='MpServer', x=1602,16, y=70,00, z=2302,66], EntityCreeper['Крипер'/793, l='MpServer', x=1702,50, y=36,00, z=2283,00], EntityHorse['Лошадь'/794, l='MpServer', x=1696,97, y=69,00, z=2298,00], EntityItem['item.item.bone'/795, l='MpServer', x=1596,44, y=71,13, z=2369,47], EntityHorse['Лошадь'/796, l='MpServer', x=1589,13, y=72,00, z=2316,41], EntityHorse['Лошадь'/800, l='MpServer', x=1713,59, y=69,00, z=2305,34], EntityPig['Свинья'/802, l='MpServer', x=1603,47, y=73,00, z=2406,03], EntitySpider['Паук'/742, l='MpServer', x=1656,66, y=24,00, z=2342,84], EntityZombie['Зомби'/743, l='MpServer', x=1655,38, y=24,00, z=2342,09], EntityZombie['Зомби'/744, l='MpServer', x=1653,44, y=24,00, z=2335,28], EntityChicken['Курица'/745, l='MpServer', x=1667,47, y=69,00, z=2351,59], EntityWaypointContainer['неизвестно'/233, l='MpServer', x=0,00, y=0,00, z=0,00], EntityHorse['Лошадь'/746, l='MpServer', x=1652,41, y=68,00, z=2352,75], EntityWitch['Ведьма'/747, l='MpServer', x=1639,09, y=19,00, z=2331,50], EntityZombie['Зомби'/748, l='MpServer', x=1656,16, y=25,00, z=2330,55], EntitySkeleton['Скелет'/749, l='MpServer', x=1614,56, y=23,00, z=2350,94], EntityHorse['Лошадь'/750, l='MpServer', x=1616,28, y=70,00, z=2332,50], EntityHorse['Лошадь'/751, l='MpServer', x=1678,28, y=70,00, z=2319,78], EntitySkeleton['Скелет'/752, l='MpServer', x=1673,78, y=67,49, z=2313,56], EntitySkeleton['Скелет'/753, l='MpServer', x=1675,22, y=67,09, z=2313,22], EntityCreeper['Крипер'/754, l='MpServer', x=1687,50, y=47,00, z=2324,50], EntityZombie['Зомби'/755, l='MpServer', x=1689,50, y=47,00, z=2320,50], EntityCreeper['Крипер'/756, l='MpServer', x=1629,00, y=48,00, z=2314,44], EntityCreeper['Крипер'/757, l='MpServer', x=1694,50, y=25,00, z=2315,50], EntityItem['item.item.rottenFlesh'/758, l='MpServer', x=1685,19, y=69,13, z=2307,31], EntityCreeper['Крипер'/759, l='MpServer', x=1649,50, y=39,00, z=2299,50], EntitySkeleton['Скелет'/760, l='MpServer', x=1658,84, y=45,00, z=2299,31], EntityCreeper['Крипер'/761, l='MpServer', x=1709,50, y=34,00, z=2339,50], EntityHorse['Лошадь'/762, l='MpServer', x=1662,09, y=70,00, z=2399,03], EntityHorse['Осёл'/763, l='MpServer', x=1604,59, y=70,00, z=2325,81], EntityHorse['Лошадь'/764, l='MpServer', x=1607,13, y=69,00, z=2322,50], EntityItem['item.item.rottenFlesh'/765, l='MpServer', x=1670,59, y=69,13, z=2290,34], EntityZombie['Зомби'/766, l='MpServer', x=1698,50, y=25,00, z=2323,50], EntityCreeper['Крипер'/767, l='MpServer', x=1697,50, y=25,00, z=2324,00]]
	Retry entities: 0 total; []
	Server brand: cauldron,craftbukkit,mcpc,fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:909)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_40, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 339612512 bytes (323 MB) / 903348224 bytes (861 MB) up to 932184064 bytes (889 MB)
	JVM Flags: 1 total; -Xmx1000M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 49 mods loaded, 49 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FML{7.10.85.1291} [Forge Mod Loader] (forge.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forge{10.13.2.1291} [Minecraft Forge] (forge.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	appliedenergistics2-core{rv2-beta-24} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Aroma1997Core{1.0.2.13} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NotEnoughItems{1.0.4.90} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.90-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ClientFixer{1.0} [ClientFixer] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ArmorStatusHUD{1.28} [ArmorStatusHUD] ([1.7.10]ArmorStatusHUD-client-1.28.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	StatusEffectHUD{1.27} [StatusEffectHUD] ([1.7.10]StatusEffectHUD-client-1.27.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	IC2BackpackHUD{3.0} [IC2 Backpack HUD] ([9]IC2BackpackHUD.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	appliedenergistics2{rv2-beta-24} [Applied Energistics 2] (appliedenergistics2-rv2-beta-24.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Aroma1997CoreHelper{1.0.2.13} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Core{6.4.5} [BuildCraft] (buildcraft-6.4.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Transport{6.4.5} [BC Transport] (buildcraft-6.4.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Silicon{6.4.5} [BC Silicon] (buildcraft-6.4.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Builders{6.4.5} [BC Builders] (buildcraft-6.4.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Energy{6.4.5} [BC Energy] (buildcraft-6.4.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Factory{6.4.5} [BC Factory] (buildcraft-6.4.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	chisel{1.5.7} [Chisel] (Chisel-1.7.10-1.5.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	IC2{2.2.685-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.685-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forestry{3.4.0.7} [Forestry for Minecraft] (forestry_1.7.10-3.4.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	gregtech{MC1710} [GregTech] (gregtech_1.7.10-5.07.06.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	IC2NuclearControl{2.1.2a} [Nuclear Control 2] (IC2NuclearControl-2.1.2a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (miningworld.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MouseTweaks{2.4.4} [Mouse Tweaks] (MouseTweaks-2.4.4-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons{1.12.4.16} [NEI Addons] (neiaddons-mc1710-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons|Botany{1.12.4.16} [NEI Addons: Botany] (neiaddons-mc1710-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons|Forestry{1.12.4.16} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons|CraftingTables{1.12.4.16} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons|ExNihilo{1.12.4.16} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	neiintegration{1.0.7} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ForgeMultipart{1.1.1.320} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MrTJPCoreMod{1.0.5.11} [MrTJPCore] (MrTJPCore-1.7.10-1.0.5.11-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ProjRed|Core{4.5.15.75} [ProjectRed] (ProjectRed-1.7.10-4.5.15.75-Base.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ProjRed|Transmission{4.5.15.75} [ProjectRed-Transmission] (ProjectRed-1.7.10-4.5.15.75-Integration.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ProjRed|Exploration{4.5.15.75} [ProjectRed-Exploration] (ProjectRed-1.7.10-4.5.15.75-World.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ProjRed|Compatibility{4.5.15.75} [ProjectRed-Compatibility] (ProjectRed-1.7.10-4.5.15.75-Compat.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ProjRed|Integration{4.5.15.75} [ProjectRed-Integration] (ProjectRed-1.7.10-4.5.15.75-Integration.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ProjRed|Illumination{4.5.15.75} [ProjectRed-Illumination] (ProjectRed-1.7.10-4.5.15.75-Lighting.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	voxelmap{1.7.10} [VoxelMap No Radar] (voxelmapNoRadar-1.7.10-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	McMultipart{1.1.1.320} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	zzzzzcustomconfigs{2.2.0} [ZZZZZ Custom Configs] (CustomConfigs-2.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ForgeMicroblock{1.1.1.320} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	AE2 Version: beta rv2-beta-24 for Forge 10.13.2.1291
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:OFF, BC:ON, MJ6:OFF, MJ5:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GT 740M/PCIe/SSE2 GL version 4.5.0 NVIDIA 347.88, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: Русский (Россия)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by thatsIch** [comment]
So... any help, telling us, how you produced this?

**Comment by linkinkov** [comment]
I just trying to see recipe from NEI on server with last beta build Appliend Energestic.
Now i back to 4 build.

**Comment by thatsIch** [comment]
You using special configs? Cause I cant reproduce this by watching the recipe in NEI

**Comment by thatsIch** [comment]
![2015-04-04_23 41 40](https://cloud.githubusercontent.com/assets/2210496/6994721/2ae21f66-db24-11e4-8475-4615677b68f1.png)

**Comment by linkinkov** [comment]
My config:
http://pastebin.com/8zVb4Hem

**Comment by thatsIch** [comment]
I tried it with the configs you provided, and my QES are properly disabled (since you disabled QNBs in the config), not sure how you got to that screen. Can you maybe tell us the steps you did, to exactly create this bug.

**Comment by linkinkov** [comment]
That is mean QES?

**Comment by thatsIch** [comment]
Quantum Entangled Singularities, 2 small balls made from detonating a singularity with ender dust

**Comment by thatsIch** [comment]
Closing due to lack of feedback

**Comment by linkinkov** [comment]
Problem with http://minecraft.curseforge.com/mc-mods/221889-zzzzz-custom-configs . Then i removed or just install this mod.
