### ISSUE TITLE
Exact Item count missing between 999 and 10000

### ISSUE THREAD

**Issue by Staegrin** [AppliedEnergistics/Applied-Energistics-2#1202]
![2015-04-05_00 57 46](https://cloud.githubusercontent.com/assets/8494635/6995045/89ae47da-db2f-11e4-97db-725c7d4872b8.png)
As you can see in the above picture, any amount of items higher than 999 and below 10K do not show the exact item count when you hover the mouse over them. It only shows the number of thousand (1K...2K) rounded down to the nearest thousand. SHIFT also doesn't make it appear. 

Items with an item count above or equal to 10k will show the exact amount when the mouse hovers over the image. 

This has been so in version 23 and 24

**Comment by thatsIch** [comment]
confirmed, its due to the number being converted too early to 1k instead before it was thresholded at 10k

**Comment by TheJulianJES** [comment]
@thatsIch I would like if the numbers are converted at 10k. :)

**Comment by thatsIch** [comment]
yea, that is what it was before.
