### ISSUE TITLE
Can not craft any AE2 items 

### ISSUE THREAD

**Issue by HaloVet99** [AppliedEnergistics/Applied-Energistics-2#1203]
Hello i have my own private modpack on FTB and when i go craft anything in AE2 i can't get any recipes in nei and when i try crafting it from the recipes on the wiki it doesn't work. I have the most up to date mods and have tried deleting the config folder to get it to work. Is there any thing I can do to fix this or will I have to try and roll the mods back until it work?

**Comment by thatsIch** [comment]
If you use Mekanism, either downgrade Mekanism or upgrade AE2

**Comment by HaloVet99** [comment]
Thank you, I will keep that in mind. Dose anyone know what versions of the mods are compatible? I have appliedenergistics2-rv1-stable-1 and Mekanism-1.7.10-8.0.3.207

**Comment by Cisien** [comment]
Rv2 beta 18 and newer work with mek 8

**Comment by XBlackLeopardX** [comment]
18 and newer? I've been trying but they dont work for me i still cant look up or craft any thing in AE2 in my modpack?
