### ISSUE TITLE
Add %s tag for "Channels"

### ISSUE THREAD

**Issue by Adaptivity** [AppliedEnergistics/Applied-Energistics-2#1207]
I need a %s tag for *waila.appliedenergistics2.Channels* string to swap "Channels" word with number of channels. So, it will look like: *Channels: 1 of 8*

**Comment by thatsIch** [comment]
Cant provide you a %s tag, but 

   waila.appliedenergistics2.Channels=%d Of %d Channels

should do it?

**Comment by Adaptivity** [comment]
Yes, it mostly the same thing. Do it  :smile:

**Comment by yueh** [comment]
Maybe we should also add the argument index into the string.
```
waila.appliedenergistics2.Channels=%1$d Of %2$d Channels
```
I remember reading some reports about translating software to russian and they usually encountered some pretty special issues with the grammar.

**Comment by thatsIch** [comment]
done

**Comment by Adaptivity** [comment]
Few more stuff todo:
1. http://i.imgur.com/y9e5sYk.jpg -> this line seems to be hardcoded, aren't it?
2. http://i.imgur.com/cHH9dLS.jpg what about changing this to something like list? So, it will look like *Creates: 1 Piston with: 4 Cobble 3 Wood planks 1 Iron Ingot 1 Redstone. Without "and". And also make ingredients look centered, *one below the other*.

**Comment by yueh** [comment]
"Item stored" in the tooltips > 999/9999 is also hardcoded.

**Comment by thatsIch** [comment]
open new issue for this

**Comment by thatsIch** [comment]
train already departed
