### ISSUE TITLE
AE Dimension + Teleportation

### ISSUE THREAD

**Issue by Blackbird1873** [AppliedEnergistics/Applied-Energistics-2#1208]
So with the new teleportation terminal in development I came up with a great idea involving teleportation. Basically what happens is, pretend you have a mystcraft book in you AE system dimension, then in the over-world you can have some sort if AE teleportation pad linked to that book and it will take you to where the book leads to. Of course it could also be compatible with other mods such as RFTools. Of course the book inside your system may be wired in, but that is up for Algo to decide.

**Comment by 6210classick** [comment]
isn't that an April fool joke ?

**Comment by Blackbird1873** [comment]
I'm pretty sure it wasn't, but even if it was this would still be an awesome feature.

**Comment by Blackbird1873** [comment]
Okay so it was sorry, but it could still be done outside of the dimension. Maybe you could put it into a device and link a teleport pad to it. Sorry about the mistake.

**Comment by kurokuno** [comment]
OK just to clear this up the AE-2 dimension was April fools joke however fireball is making it a split off mod given he enjoyed the idea as for this idea i like it but i find it unlikely to happen given AE2 is more automation mod compatibility and less feature driven compatibility things like an AE2 teleport pad that can use myst books is unlikely i would think

**Comment by thatsIch** [comment]
http://ae-mod.info/ME-Teleport-Terminals/

**Comment by thatsIch** [comment]
This wont be a real part of AE2 but an addon, thus closing. Go nag Fireball on it :P

**Comment by Cisien** [comment]
You can do teleportation today with spatial io
