### ISSUE TITLE
NEI crash

### ISSUE THREAD

**Issue by Leksandrua** [AppliedEnergistics/Applied-Energistics-2#1211]
http://pastebin.com/UepCxAsG

You can reproduce this crash by downloading my FTB modpack (pack code DeltaRising), it's need that you need enter to the world (or create one and it), look for example recipe for Divine Shield (from steave's cart), then exit from world and re-enter to the world and the same recipe again.

While you are enter first time, it works without any NEI crashes, but not second time

Similar problem: http://goo.gl/GrjkRr

P.s. It seems like without any scripts (mine/modtweker's script) that change recipes in incriber it works fine

**Comment by linkinkov** [comment]
Same problem as me

**Comment by thatsIch** [comment]
Can be closed due to https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1229
They can use our public API for that now, no need to hook into internal classes.

**Comment by Yulife** [comment]
@thatsIch is it possible to tweak the Grinding Stone with the seemingly new API as well?

**Comment by thatsIch** [comment]
tweak like what? The grinder has already an API access
