### ISSUE TITLE
Meteorites in generating chunks destroys Moving Structures

### ISSUE THREAD

**Issue by DHerls** [AppliedEnergistics/Applied-Energistics-2#1212]
I created a moving mining platform with a chunk loader in my FTB Infinity World.  Whenever It passes by a meteorite, it gets destroyed as if it were part of the world generation around the meteorite.  This has happened twice so far.  The mining platform is powered by Funky Locomotion.

Info:
Expected: For my mining machine to continue its reign of terror
Problem: Mining machine destroyed by generating meteors
How to reproduce:
   Create moving thing with inchworm drive
   Add Chunk Loader
   Wait for it to pass by a meteor
Mod Pack - FTB Infinity version 1.3.4
Multiplayer Server
Game does not crash

![2015-04-05_11 45 33](https://cloud.githubusercontent.com/assets/5505389/6997538/bb02b99e-db8c-11e4-8fe3-fb8282d4fc9b.png)
![2015-04-05_11 45 41](https://cloud.githubusercontent.com/assets/5505389/6997537/bb0202ec-db8c-11e4-8a7f-cda2f7d48fc8.png)
![2015-04-05_11 45 48](https://cloud.githubusercontent.com/assets/5505389/6997539/bb03f976-db8c-11e4-888c-833de45d83d0.png)

**Comment by yueh** [comment]
#634
