### ISSUE TITLE
Error while rendering - java.lang.NullPointerException

### ISSUE THREAD

**Issue by xWTyrone** [AppliedEnergistics/Applied-Energistics-2#1213]
PasteBin: http://pastebin.com/ZshHRJwR

Crashes when trying to open world.
Happens after updating to rv2 beta24
I'll see about older versions working.

**Comment by draksterau** [comment]
Use B18

**Comment by Aevaris** [comment]
does this happen on new worlds or only your existing world?

**Comment by thatsIch** [comment]
we will look into this.

**Comment by yueh** [comment]
No idea how to reproduce it. The only option which could cause it, if the tile entity for the drive is missing. Also there is no change in the related code between b8 and b24.

Are you using the default config? And as already asked, does it also happen in a new world?
