### ISSUE TITLE
ME Interface not working properly with Inscriber

### ISSUE THREAD

**Issue by tunasushi** [AppliedEnergistics/Applied-Energistics-2#1218]
When connecting an ME interface to an inscriber and using it in a crafting recipe, the materials will be deposited into the inscriber and inscribed, but they are not taken out. This stops the crafting job and it has to be canceled and the items taken out by hand. Is there any way to fix this?

**Comment by Robzz** [comment]
Using an import bus on the right side of the inscriber works for me.

**Comment by tunasushi** [comment]
So I shouldn't use inscribers with auto crafting then because the crafting job will never finish. Thanks for the info!

**Comment by Robzz** [comment]
Sure you can, I do. Just a ME import bus.
