### ISSUE TITLE
Hardcoded localization

### ISSUE THREAD

**Issue by Adaptivity** [AppliedEnergistics/Applied-Energistics-2#1219]
See comments here: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1207

**Comment by thatsIch** [comment]
what a lazy bun

**Comment by thatsIch** [comment]
> Few more stuff todo:
> 1. http://i.imgur.com/y9e5sYk.jpg -> this line seems to be hardcoded, aren't it?
> 2. http://i.imgur.com/cHH9dLS.jpg what about changing this to something like list? So, it will look like Creates: 1 Piston with: 4 Cobble 3 Wood planks 1 Iron Ingot 1 Redstone. Without "and". And also make ingredients look centered, one below the other.
> 3. http://i.imgur.com/M1A2FaM.jpg one more hardcoded string.
> 4. http://i.imgur.com/PpIS91F.jpg another string. It is in .lang file but its seems still to be hardcoded somewhere

> "Item stored" in the tooltips > 999/9999 is also hardcoded.

**Comment by thatsIch** [comment]
1. fixed indev
2. not sure about that
3. fixed indev
4. fixed indev, was a bug
5. fixed indev
