### ISSUE TITLE
Can ME Level Emitters provide a processing pattern?

### ISSUE THREAD

**Issue by XFactHD** [AppliedEnergistics/Applied-Energistics-2#1223]
On ae-mod.info under the category "Crafting CPU" is written that a Level Emitter can provide a Crafting Pattern to a Crafting CPU. Is this right or a mistake, because the only option that would make sense to me is inserting a Crafting Card in the Level Emitter, but this only provides a button to choose between"Always craft" and "Use stored or craft".

**Comment by yueh** [comment]
Yes, they can emit redstone to request items with a crafting card. Just like the wiki says.

**Comment by XFactHD** [comment]
The question was not if they can emit a redstone signal to request items. The question was if they can hold a crafting pattern in the GUI, I was wondering about that because it doesn't really make sense, but it is written on the wiki.

**Comment by Cisien** [comment]
Yes, the level emitter can hold a pattern

**Comment by yueh** [comment]
Maybe you should have mentioned that. Patterns are just telling the autocrafting how to obtain a specific item. Encoded patterns are just one way of doing it, but a machine could also provide them.

Level emitters can hold any item. So if emitting a redstone signal will produce the pattern you placed in there, it will work.
