### ISSUE TITLE
Prtable cell recharging when inside the ME Drive

### ISSUE THREAD

**Issue by Nikkolino99** [AppliedEnergistics/Applied-Energistics-2#1224]
I think it could be a good idea to be able to recharge the portable cell (Only that) whrn it is inside the me drive

**Comment by thatsIch** [comment]
Rather not,
this would mix 2 functionalities of 2 different machines together.

Charger for charging energy items
and ME Drive for containing storage cells

**Comment by Cisien** [comment]
There is probably nothing stopping you from using a storage bus on the charger to achieve this functionality
