### ISSUE TITLE
odd behaviour with channels

### ISSUE THREAD

**Issue by Acidboy92** [AppliedEnergistics/Applied-Energistics-2#1226]
just added mekanismv8 and ae2 beta 18 and having some odd behavior with channels as seen in the images 
![2015-04-05_19 42 35](https://cloud.githubusercontent.com/assets/11821964/7008981/f4a9d454-dc8e-11e4-8a2e-1aeac1c7338a.png)
![2015-04-05_19 42 42](https://cloud.githubusercontent.com/assets/11821964/7008982/f4ae41f6-dc8e-11e4-818e-aa7cae894ede.png)
![2015-04-05_19 42 44](https://cloud.githubusercontent.com/assets/11821964/7008983/f4b02138-dc8e-11e4-9c2e-b475cb177f46.png)
![2015-04-05_20 19 07](https://cloud.githubusercontent.com/assets/11821964/7008980/f4a83cf2-dc8e-11e4-9227-2e1e00886810.png)
![2015-04-05_20 19 12](https://cloud.githubusercontent.com/assets/11821964/7008984/f4b662b4-dc8e-11e4-9802-ad3a3472db2d.png)

**Comment by thatsIch** [comment]
try upgrading

**Comment by Acidboy92** [comment]
I have tired it on the latest ae2 beta with the same results

**Comment by thatsIch** [comment]
Maybe other rendering related software like Optifine or such? Try removing them and see if that fixes it.

**Comment by Acidboy92** [comment]
Don't use them as they cause too much lag 

<div>-------- Original message --------</div><div>From: thatsIch <notifications@github.com> </div><div>Date:07/04/2015  12:15  (GMT+00:00) </div><div>To: AppliedEnergistics/Applied-Energistics-2 <Applied-Energistics-2@noreply.github.com> </div><div>Cc: Acidboy92 <Jeremy@gethyper.co.uk> </div><div>Subject: Re: [Applied-Energistics-2] odd behaviour with channels (#1226) </div><div>
</div>Maybe other rendering related software like Optifine or such? Try removing them and see if that fixes it.

**Comment by thatsIch** [comment]
can you reproduce this in a new world?
