### ISSUE TITLE
Inscriber do not work with Mine/ModTweaker 

### ISSUE THREAD

**Issue by Leksandrua** [AppliedEnergistics/Applied-Energistics-2#1229]
In last version AE (rv2.beta build 26) Mine/ModTweaker scripts do not work with inscriber.
Could it been fix in next version of AE or Mine/ModTweaker's author need to fix this issue?

**Comment by yueh** [comment]
This needs to be fixed on their side.
They are using something never really intended to modify the inscriber recipes and this is now gone as it did cause issues.
