### ISSUE TITLE
Is creative tab's ordering strange?

### ISSUE THREAD

**Issue by karakufire** [AppliedEnergistics/Applied-Energistics-2#1230]
I worry about order of AE2 creative tab.
rv2's order is deffernt  from rv1. the order looks very disorderly.
Is the trouble specification,bug and other problem?
Here's images
rv1 order:http://i.imgur.com/4fCWWA2.png
rv2 order:http://i.imgur.com/wkp87Ci.png

**Comment by TheJulianJES** [comment]
Generate a new world, forge organizes them like so: ID 134, ID 135,..
Since IDs are different in world that can happen.
