### ISSUE TITLE
Crash when trying to autocraft something with the wireless terminal

### ISSUE THREAD

**Issue by Nikkolino99** [AppliedEnergistics/Applied-Energistics-2#1231]
When I try to craft cables, storage cells ecc., the game "close the connection, because of a fatal error
![crash ae2](https://cloud.githubusercontent.com/assets/7397855/7019783/df1e6782-dd13-11e4-9028-be06ca6cd931.png)
"

The error message is this: http://pastebin.com/zCCXYJDp

**Comment by yueh** [comment]
This likes more like a FMP issue or somehow related to it. Maybe even caused by any mod providing FMP parts.

It might be an idea to remove every cover from every cable and try again. If it fixes it, then readd them slowly until you find the one causing it.

**Comment by Nikkolino99** [comment]
OK, i'll try that
Thak you
Il 07/apr/2015 12:17, "yueh" <notifications@github.com> ha scritto:

**Comment by Nikkolino99** [comment]
Nope, still crashing, even without AE2's facades

**Comment by Zaflis** [comment]
1.1.2.331 is latest version for forge multipart, you're on 320. Maybe updating it helps?

**Comment by MassiveNetwork** [comment]
I'm on the latest version of Forge Multipart and still get the disconnects
