### ISSUE TITLE
Add presses as dungeon loot for non-standard world generation.

### ISSUE THREAD

**Issue by bochen415** [AppliedEnergistics/Applied-Energistics-2#1232]
As title.
I have a suggestion to add the 4 basic press types as a rare dungeon loot for modpacks with void generation enabled (when meteor spawning is non-existent).

Both ExNihilo and YUMakeNoGoodMap (and also the vanilla generator) void generation mods are disabling meteor generation and making a modpack with them included forces a workaround with Minetweaker/Modtweaker/CustomLootChest/Lootbags/other to allow the player to obtain those items.

I suggest a config option (disabled by default) to add those items as a rare dungeon loot (or any other means that don't need a dirty and buggy workaround with another mods).

**Comment by yueh** [comment]
Void worlds will also be missing dungeon chest, so it will not change anything. Also skystone is still a crafting ingredient and needs to be obtainable and it does not make sense to put it into dungeon chests. And I think adding them to dungeon loot was already rejected by algo.

But you can always use ![custom recipes](http://ae2.ae-mod.info/Custom-Recipes/) to make presses and/or skystone craftable somehow and do not need another mod for it.

**Comment by bochen415** [comment]
I was thinking about the least intrusive way to add this functionality. My idea was LootBags, a simple mod that adds dungeon loot as a rare mob drop + the mentioned enhancement.
Skystone is obtainable with ExNihilo with skystone dust (from sieves) and some in-world crafting with lava. 
Btw, custom recipes link not working.

**Comment by thatsIch** [comment]
optional disabled by default

**Comment by bochen415** [comment]
Fair enough.

I had a conversation with @MikeLydeamore (current ExNihilo/ExAstris dev) about alternative ways for obtaining AE2 items needed for progression in a skyblock type pack. I presented an idea from reddit:
http://www.reddit.com/r/feedthebeast/comments/300an3/how_are_ae2_presses_obtainable_in_as2/
Presses divided into nuggets/puzzles which need inventing the way for obtaining. He has his own ideas about that.

**Comment by yueh** [comment]
Breaking the presses into parts is probably the worst possible solution. It just throws more RNG at the users in lack of a better idea. Enough users will end up with 2-5 of most nuggets/puzzles, but then missing the usual last one. So it can be pretty frustrating (and some are already complaining that spending maybe half an hour running around to find meteors is too much).

If the pack uses HQM it is easily solvable, just hand them out. Maybe in stages like a silicon one for a charger and the logic one for a inscriber etc.

If not, you could for example add a recipe for the inscriber to craft a press with say 1 block of iron + 1 sky stone dust + the material used with the press later. This will make the initial press more expensive than copying an existing one and also making the copying not obsolete.

Planning with 2-3 parts per press would also add 12-16 mostly useless items after the first one and I would say there are already enough different items with all the ore gravel|sand|dust etc (but still useful compared to additional presses).
