### ISSUE TITLE
Allow for custom number of autocraft items

### ISSUE THREAD

**Issue by Pontiac76** [AppliedEnergistics/Applied-Energistics-2#1234]
Typically in MC, things stack in stacks of multiples of 16.  It seems out of sorts that the prompt asking you on how many items you'd like to autocraft be in multiples of 10.  I understand that some people find this reasonable, but I kind of dislike it, as when I want a stack of torches, I don't want 100, but, 64.

Would it be possible, either via UI configuration, or, flat file configuration, server side or client side, to let the user decide what each of the 4 +/- stacks be made?

IE: Right now, it is +/- 1, 10, 100, 1000.  I'd like to be able to set +/- 1, 16, 64, 128.

Would it also be possible to set this default on a per crafting terminal, or, maybe allow a view cell to handle the custom values?  (Maybe not the view, since, my preference may not be the same as another players preference)

*MY* preference to where the settings should be stored would be first on the client side in a UI options screen, second a configuration file client side, then lastly server side which would then affecting all users.

**Comment by yueh** [comment]
Just change it in the config. These are clientside settings, so the server will not affect them at all.

**Comment by Pontiac76** [comment]
I wasn't aware that it existed.  Thanks.

**Comment by yueh** [comment]
You can also change it through the mod options GUI.

**Comment by Pontiac76** [comment]
WTF... How did I miss this?  You win.  Both my top requests have been met.
