### ISSUE TITLE
Cell not partitioned correctly

### ISSUE THREAD

**Issue by Nikkolino99** [AppliedEnergistics/Applied-Energistics-2#1236]
I was trying to partition a 1k cell for a quarry, but when I put it in the player inventory it cancel the partition

**Comment by Nikkolino99** [comment]
Close this please

**Comment by Nikkolino99** [comment]
I am stupid :)

**Comment by TheJulianJES** [comment]
You can close it yourself :)

**Comment by Nikkolino99** [comment]
I don't know how. I'm new to github


2015-04-07 19:33 GMT+02:00 TheJulianJES <notifications@github.com>:

> You can close it yourself :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1236#issuecomment-90660675>
> .
>



-- 
Nicola Galluccio

**Comment by TheJulianJES** [comment]
Just click the close button next to the comment button @Nikkolino99
