### ISSUE TITLE
Using Network Tool causes sync issues in connection with PlayerInteractEvent

### ISSUE THREAD

**Issue by iTitus** [AppliedEnergistics/Applied-Energistics-2#1237]
Somehow, after using the network tool, the PlayerInteractEvent is not fired on the server side.
This causes some sync issues. I can fix them, but is this intended?

References:
- AlexTheGre4t/MCTNG#39
- BCA-Team/Buildcraft-Additions#369

**Comment by thatsIch** [comment]
http://puu.sh/h552h/0f7b477c73.jar try with that one

**Comment by iTitus** [comment]
Now it crashes every time I shift-right-click on that block.
https://gist.github.com/iTitus/0bfe70b4d03493e61f14

**Comment by thatsIch** [comment]
good that the crashlog tells us a lot

**Comment by iTitus** [comment]
I know :P
But I can say that the code is now executed on the server side.
other wrenches do not crash.

**Comment by iTitus** [comment]
MC tries to send a packet with the id of the currently opened container, which is (obviously) null.

**Comment by thatsIch** [comment]
I concede,
if you know, how to fix this, send us a PR

**Comment by iTitus** [comment]
I don't know a fix, sorry...

**Comment by AEnterprise** [comment]
might it be that on shift clicking it also tries to open the gui even though the clicking was already handled and thus it sends a gui packet with null container?
