### ISSUE TITLE
Crash when accessing buses on ME network

### ISSUE THREAD

**Issue by TheShortBusDerp** [AppliedEnergistics/Applied-Energistics-2#1239]
After last update...  every time I access any bus (import/storage/export), minecraft crashes back to the launcher. Buses still seem to work appropriately, just cannot access to configure in any way as it crashes immediately.

Using a private modpack on a multiplayer server.
Fastcraft is enabled.
Does not crash server.

Link to crash report: http://pastebin.com/ereuEi3X

**Comment by yueh** [comment]
#1127
