### ISSUE TITLE
Using regular expression to search in ME Terminal

### ISSUE THREAD

**Issue by Goten87** [AppliedEnergistics/Applied-Energistics-2#1241]
hello AE2 Dev team
i have a new option for looking stuff up in the terminal
if i want to see all my nether ores, i now need to look for nether and then i get more
is there a possibility to have an option like nether * ore where the * is all that falls in there
like gold - iron - lapiz - diamond
that way we can look up stuff faster and nicer
don't know if you can implement this, but wanted to share it for a better AE2

**Comment by TheJulianJES** [comment]
That would be nice, currently there are View Cells (http://ae-mod.info/View-Cell/).

**Comment by thatsIch** [comment]
@yueh just told me, that this ia already possible. Search does support regex,

so search for `nether.*ore`

**Comment by TheJulianJES** [comment]
O_o
