### ISSUE TITLE
OreDict unifier

### ISSUE THREAD

**Issue by Biofusionz** [AppliedEnergistics/Applied-Energistics-2#1243]
A block a little like the unifier from MFR, which we can hook up to our system and select a preferred ingot/dust which everything in the system would be converted to.

**Comment by wilkemeyer** [comment]
Would be a cool feature maybe this could be releaized with a card for import/export busses, as well as for interface .. 

If the component has the unifier-upgrade-card it should show a button to enable/disable the feature (like the Redstone Card does.)

**Comment by mrgreenacid** [comment]
Please yes, having this integrated into ae2 would be fantastic.

**Comment by misbe** [comment]
+

**Comment by TheJulianJES** [comment]
Me too ;)

**Comment by thatsIch** [comment]
I personally do not like to support OreDictionary more than necessary. People are abusing that for various shit, like giving the possibility to convert one machine into another just for the sake to save a single recipe line. 

I would prefer, if the big mods would deactivate their own ingots if possible, if it is already registered as the same name.

**Comment by misbe** [comment]
I once had the idea to write a core-mod with just one function: providing more ores and as an example if a mod needs silver it'll tell my mod that silver is needed... so you have just one ore and every mod can use it... but the creators of the big mods have to follow this line than it would be awesome...

No more "oh i have 100 different Silver"

**Comment by wilkemeyer** [comment]
@thatsIch basicly i'd agree but i don't know any single mod which's checking if a material has been already registered :( 

@misbe not really neccessary as a mod could check if the material already exists,  yes -> use it, no -> register by mod itself.

**Comment by misbe** [comment]
but then...
ModA: Spawns the ore very often in a big range... 'cause it's needed often and on low tier
ModB: Spawns the Ore very rare... 'cause it's needed on expensive high tier

ModB loads before ModA... ModA is nearly unplayable...

**Comment by wilkemeyer** [comment]
i was not talking about worldgen thats another topic

a solution for this could be a more generic world-gen-api (forge.) which allows customization of registered spawns - so it's possible to re-balance it, depending on what mods are installed / whats the focus of the modpack. 

I'd assume that even if its more generic - enough mods would use their own spawning code / still register duplicates etc etc.
There're modders out there that've always a own way of implementing stuff.
For example - take a look on current oredict naming schemes -> Aluminum :unamused:

**Comment by misbe** [comment]
@wilkemeyer you got the point now ^^
But now BTT

**Comment by thatsIch** [comment]
The problem I have is, that it is not only used for ingots (which you maybe have just 3-4 different kinds of) but some mods which register their whole machines (several dozens or hundreds) under a specific namespace, which makes the name `OreDictionary` totally mismatching

@wilkemeyer AE2 does that

**Comment by yueh** [comment]
`OreDictionary` is really a badly named general item equality system (which it is mostly).

I do not really see it as upgrade as it is way to complex (and the upgrades would really need a more modular system). Especially increasing the complexity for the interfaces is not a good idea. A separate machine is probably the best and could also handle more config slots. Similar to a storage bus with 63 slots compared to interfaces or import/export buses with 9.

Also just because 2 items are equally in a recipe, does not mean it is valid to convert them. For example the harvestcraft seeds all share the same oredict name, maybe even the food.
