### ISSUE TITLE
Flour doesn't exist as an item...

### ISSUE THREAD

**Issue by GamingMortal** [AppliedEnergistics/Applied-Energistics-2#1247]
I don't know if I'm blind or what but I was using mine tweaker to edit a recipe that used flour to accept AE2 flour but when I used /minetweaker names their was no sign of flour from AE2? am I missing something I've searched flour and through all the AE2 items on the dump but their is no sight of flour from the mod.

**Comment by thatsIch** [comment]
maybe disabled?

**Comment by GamingMortal** [comment]
I can create it in survival and it can be used so I don't think it's disabled here is the log file:
http://pastebin.com/3L3MxKQM

**Comment by thatsIch** [comment]
I have never used MineTweaker, nor do we offer special integration for them. 
Maybe better ask them?

The mod author can create an issue here, if something special is missing. Random guessing will get us nowhere.
