### ISSUE TITLE
Facades not placing on multiparts

### ISSUE THREAD

**Issue by Nikkolino99** [AppliedEnergistics/Applied-Energistics-2#1249]
I remember that in beta 1, there was the possibility to place facades on multiparts like the crafting terminal, now, if I try to put the facades on them, they will not place, instead, if i place a facade and then the terminal, the terminal face the facade, with the cable connection in front of me.
Is this a bug or this is intended to be?

**Comment by XFactHD** [comment]
Are you using AE2 cable facades or forge multipart covers? What you are trying to do works only with AE2  cable facades.

**Comment by Nikkolino99** [comment]
I'm doping this with The facades from ae2
Il 10/apr/2015 00:06, "XFactHD" <notifications@github.com> ha scritto:

**Comment by thatsIch** [comment]
works fine for me. 
Maybe you use outdated AE2 and missmatching FMP?

**Comment by Nikkolino99** [comment]
Nope, both at The latest version
Il 10/apr/2015 07:13, "thatsIch" <notifications@github.com> ha scritto:

**Comment by yueh** [comment]
Works also fine for me with AE2 facades.

FMP covers will of course not work and never have. Regardless of the placement order.
FMP will only work with strips (or covers put on the 4 sides adjacent to the one with the terminal)

**Comment by thatsIch** [comment]
Just tried it myself outdev, it even crashes with AE2rv1 if you try to do that, so that functionality was never in there.

**Comment by Nikkolino99** [comment]
http://youtu.be/4yGq1IZE9Zw
This is what I was saying

**Comment by yueh** [comment]
You cannot mix FMP covers and AE2 facades on the same cable (block). It is either one or the other.
Putting a single FMP part on a cable will convert it to a FMP container until the cable/block is fully removed.

**Comment by Nikkolino99** [comment]
There aren't any fmp covers... Only ae2's facades
Il 11/apr/2015 20:45, "yueh" <notifications@github.com> ha scritto:

**Comment by yueh** [comment]
There is clearly one below the terminal. AE2 facades do not render as a hollow cover.

**Comment by thatsIch** [comment]
Waiting for feedback

**Comment by Nikkolino99** [comment]
No, I was using only facades...
Il 13/apr/2015 13:44, "thatsIch" <notifications@github.com> ha scritto:

**Comment by thatsIch** [comment]
Can you replicate that in a new world? Or maybe I still do not understand what really the bug is
