### ISSUE TITLE
Favicon for the website

### ISSUE THREAD

**Issue by VikeStep** [AppliedEnergistics/Applied-Energistics-2#1251]
thatsIch mentioned I should bring this up as an issue so it's not forgotten in an IRC chat. This is just a request for a favicon on the website.

**Comment by TheJulianJES** [comment]
Hahaha, that would be nice :)

**Comment by thatsIch** [comment]
You can use the `@` operator like on Twitter to highlight people.

**Comment by yueh** [comment]
I want something completely meaningless. Like a transparent one with a single fluix colored pixel.

**Comment by TheJulianJES** [comment]
Closing this now?

**Comment by thatsIch** [comment]
Huh? Why?

**Comment by thatsIch** [comment]
Nvm, just saw!

cute favicon

**Comment by TheJulianJES** [comment]
It has a favicon?

**Comment by TheJulianJES** [comment]
:D
