### ISSUE TITLE
Interface Blocking mode not working with Ender IO machines

### ISSUE THREAD

**Issue by momerathe** [AppliedEnergistics/Applied-Energistics-2#1252]
Steps to reproduce:
* Have one ME Interface in block mode, with (for example) one EIO alloy smelter on each free side.
* Alloy smelters are set to push output into the interface
* Interface contains processing pattern for making 1 energetic alloy ingot
* Interface is in blocking mode
* request auto-crafting of a stack of energetic alloy

Expected behaviour
* One set of materials should be pushed to each smelter, distributing the job between them, until job is done. (This is how it works with MFR machines)

Actual behaviour
* Whole stack of each raw material is deposited in a single smelter; the rest go un-used.

For more details, see here: http://www.reddit.com/r/feedthebeast/comments/320dz2/ae_processing_with_multiple_alloy_smelters/
I don't know if this is an AE issue or and EIO issue, but hoping you have insight either way.

**Comment by yueh** [comment]
#681
