### ISSUE TITLE
Large compact machine + AE2 dense cable --> crash

### ISSUE THREAD

**Issue by XFactHD** [AppliedEnergistics/Applied-Energistics-2#1254]
If I place a ME dense cable next to a large compact machine, I get a abstractMethod error:
Crashreport: http://pastebin.com/VhwvD4pV
CM version: 1.7.10-1.2
AE2 version rv2 beta 14

I have also submited an issue on the compact machines issue tracker.
https://github.com/thraaawn/CompactMachines/issues/97

**Comment by yueh** [comment]
How about testing it with the most recent versions and not the oldest one you find before reporting a bug?
