### ISSUE TITLE
Threshold for conversion on storage monitor at 1k, instead of 10k

### ISSUE THREAD

**Issue by Infinitoa** [AppliedEnergistics/Applied-Energistics-2#1256]
Similar issue as described in #1202 
The storage monitor converts the item count to 1k, if more than 999 items are stored. The fix #1238 apparently did not fix it for the storage monitor.
![Screenshot](http://i.imgur.com/Y6ZynGx.png)
Using version rv2-beta-28 on DW20 pack 1.7.10 1.2.1 (manually updated AE2)

**Comment by thatsIch** [comment]
This is actually intended, because the fix was only meant for the Terminals. The storage monitors have a specific size and can only render so much.

**Comment by thatsIch** [comment]
Apparently it was a mixed case with max of 4 chars (thus allowing 9999 items, but not 9999k Items)
