### ISSUE TITLE
Randomly disappearing channels when using P2P Tunnels

### ISSUE THREAD

**Issue by DatJonas01** [AppliedEnergistics/Applied-Energistics-2#1258]
You can see my molecular assembler setup in the next picture. Randomly some crafting recipies disappear because the interfaces just dont get any channels. The red arrow shows where this occurs at the moment. Replacing the P2P tunnels and/or cables doens't help.

![2015-04-11_10 25 44](https://cloud.githubusercontent.com/assets/11249620/7100794/e6cecfc4-e035-11e4-9948-c1d311d46ce2.png)

Another view at the setup:

![2015-04-11_10 34 53](https://cloud.githubusercontent.com/assets/11249620/7100818/857bc64a-e036-11e4-9355-d7e9e492f254.png)

The controller is setup like this:

![2015-04-11_10 37 30](https://cloud.githubusercontent.com/assets/11249620/7100830/99870888-e037-11e4-88c2-e8d6c2818847.png)

Each P2P tunnel at the molecular assembler setup has got an own P2P at the controller, so in fact that's only 16 of the 32 channels used each.

I'm running the Direwol20 1.7.10 Pack v.1.2.1 on a server and haven't modified it in any way.
The version of ae2 in use is: rv2-beta-pre9

**Comment by yueh** [comment]
This is intended behaviour.
For more information about how channels are distributed look [here](http://ae-mod.info/Channels/). (Also keep in mind that everything transmitting channels is behaving like this, regardless of being a cable or machine)
