### ISSUE TITLE
Power output upgrade card (feature request)

### ISSUE THREAD

**Issue by gigaherz** [AppliedEnergistics/Applied-Energistics-2#1261]
While playing in modpacks, many times I have wished I could provide power to an external machine through an ME Interface. Although the full-block ME interface can provide power to other AE machines, it would be interesting to have a "power export" upgrade card for compatibility with other forms of power.

Ideally, this upgrade card would allow the interface to function as the reverse of an Energy Acceptor. Since the mod already accepts RF/t, and hence already makes use of the RF API, I believe it would be an interesting addition to let upgraded interfaces also provide RF power to devices (I suppose others would like their machines to receive EU instead, but I'm not a fan of IC2 mechanics).

**Comment by yueh** [comment]
No. It was always a design decision to never output any other power system.

**Comment by gigaherz** [comment]
Sad choice. Sorry to hear. I'll make do.
