### ISSUE TITLE
Trying to craft something, the gui close

### ISSUE THREAD

**Issue by Nikkolino99** [AppliedEnergistics/Applied-Energistics-2#1262]
I was trying to craft 16k storage component, when I click the item, the gui close, this happens in the ME terminal, on the ME crafting Terminal and the ME pattern terminal, not on the wireless terminal

**Comment by TheJulianJES** [comment]
What version?
Maybe screenshots/video?
Do you have extra addons for AE2?
Logoutput?

**Comment by Villagedeal** [comment]
I am having the same problem
AE2v: rv4-alpha-11
Using modpack: yes
Modpack: FTB Beyond v1.6.1
Using server: yes
