### ISSUE TITLE
Crafting Calculation Time

### ISSUE THREAD

**Issue by sci4me** [AppliedEnergistics/Applied-Energistics-2#1263]
I am trying to craft large numbers of complex recipes. The problem is when I click "next", it takes a LONG time (>10 mins, don't know how long, refuse to wait that long :P) to calculate the required materials and if it has them. I would like a way to close the GUI but keep it calculating the crafting job.

**Comment by yueh** [comment]
This will happen when recipes are using items with a limited amount of uses. In these cases the calculation needs to simulate every single crafting operation to calculate the amount of tools and not just `crafting materials * number of requested items`. This also needs to check of there are oredict tools or oredict materials to craft the tools once a single one is used or other cases of missing items to craft a new tool and adding that to the request.
This can also not really be cached in a useful way, except if the conditions are always identically. So always the same amount of requested items, no prexisting tools, probably the exact same amount of already existing items, etc. For example just one stick more (or less) could be enough to request one less crafting operation for sticks (or 1 more), thus making the whole cached calculation invalid.

You could increase the `craftingCalculationTimePerTick` in the config to allow the calculation to take more time per tick, thus making it perform faster (but potentially trading performance for it)

The best option is really to not use IC2 hammers and cutters to craft a HV solar, but instead the actually machine (or similar recipes)

**Comment by sci4me** [comment]
That's unfortunate... oh well. Time to make those machines :P
