### ISSUE TITLE
Crash when game renders some cables

### ISSUE THREAD

**Issue by OmgitsLuke** [AppliedEnergistics/Applied-Energistics-2#1264]
Windows 8.1
Java 8 update 40 - I have a 64bit and one (same version, update) that doesn't say anything.
Minecraft version: 1.7.10
Forge: Forge10.13.2.1291
Details:
I only installed Applied Energistics 2-rv2-beta-26, the same issue is on 27, 28. When I open my creative inventory and go to the next page, and open the AP2 tab, scroll a bit, and as soon as I reach some of the cables (dense) it crashes (singleplayer world). I do not know if it's really dense or something else but it crashes when I reach that part of the menu. I have not tested earlier versions.

Log: http://pastebin.com/7uQWAs3Q

**Comment by yueh** [comment]
It looks like the ASM part is not stripping the RFApi methods, as well the RF P2P Tunnel is not disabled when the RFApi is missing.
