### ISSUE TITLE
Crafting Calculation Cache

### ISSUE THREAD

**Issue by sci4me** [AppliedEnergistics/Applied-Energistics-2#1265]
My suggestion is a block that could be added to the Crafting CPU multiblock which would act as a size-limited cache for crafting plan calculations. I will try to explain the functionality with this example: user crafts complex recipe for first time and the calculation takes a few minutes. The second time the user crafts the complex recipe (potentially with a different number to craft), it skips the calculation step. Another thing would be that if another complex recipe (complex recipe 2) uses complex recipe as a crafting component in it and complex recipe is in the cache, it can skip calculating that portion of complex recipe 2. Also, I mentioned it would be size limited; if a recipe is crafted that is NOT in the cache and the cache's size is maxed out, the OLDEST entry in the cache will be replaced with the new one.

What do you guys think?

**Comment by yueh** [comment]
See #1263 for the explanation why not possible/feasible.
