### ISSUE TITLE
ME Security Terminal Problem

### ISSUE THREAD

**Issue by Deathwinng** [AppliedEnergistics/Applied-Energistics-2#1266]
Hello, I have problem with the ME Security Station. Every time I load my world and open my ME newtok, I can see all the items in there but I can't take out or put in anything and the crafting terminal appear like normal terminal without crafting grid. The export and import busses work fine. When I break the security station and place it down again, everything is back to normal.

I'm using [The 1.7.10 Pack](http://www.technicpack.net/modpack/the-1710-pack.453902/about) with version rv2-beta-28 in single player.

Thanks in advance.

**Comment by yueh** [comment]
Could you please post the `settings.cfg` located in the `AE2` folder of your save/world? (On pastebin or similar please)

**Comment by Deathwinng** [comment]
Here it is: [settings.cfg](http://pastebin.com/wepfDMmh)

**Comment by yueh** [comment]
Hm. There are way to many player entries for a single player, it seems that you get a new player each time you start. But none of them resolve to an existing minecraft account. (Which is required for a security station).

**Comment by thatsIch** [comment]
What is your minecraft username you are using in your SSP world

**Comment by Cisien** [comment]
Offline mode?

**Comment by thatsIch** [comment]
Offline mode still uses a specific set username, which renders always to the same UUID.
If this is not by chanced using a hacked minecraft account or hacked client, you have at most 2 UUIDs,

1. Mojang UUID
2. Username UUID

If you are constantly changing your username, this obviously is a user error.

**Comment by yueh** [comment]
The username used in his crashlog is `Deathwing` which would map to `89dc5387-0862-4ae7-892d-23223752b41c` (Mojang) but is nowhere found in our mapping.

**Comment by Deathwinng** [comment]
I downloaded the Technik launcher from some web site and it doesn't recuire password to log in so probably it's hacked :D 
I foun another bug with Quantium Network Bridge. It's linket to bridge in Aroma's1997 Mining World and every time I load my world and open the network from the mining world it's appear empty and I have to break and re-place every block to work again. But sometimes the bridge works but look like this:
![2015-04-13_23 19 02](https://cloud.githubusercontent.com/assets/11708611/7124823/b35805ce-e234-11e4-99da-cbc7e6f55463.png)
Sorry for my English.

**Comment by thatsIch** [comment]
ChunkLoader,

also dont use hacked software..

**Comment by Cisien** [comment]
I'm not going to support anyone stealing this game. Try with a real version.
