### ISSUE TITLE
Already Tesselating crash

### ISSUE THREAD

**Issue by lukxx** [AppliedEnergistics/Applied-Energistics-2#1267]
I have a problem, game likes to crash when i have any kind of chunk loader active... can anyone help me with this? Here's a crash report: http://pastebin.com/qukdSrYz

**Comment by yueh** [comment]
Try it without optifine.

**Comment by Cisien** [comment]
Also give an updated AE a try, the rv2 betas have a TON of fixes

**Comment by lukxx** [comment]
When i try to install beta, it crashes at load. I will post crash log when i get home.

**Comment by lukxx** [comment]
Ty yueh! I have removed optifine and ae2 works fine!Yet i dont get as much fps, but thanks, I can play again!
