### ISSUE TITLE
ME Interface with multiple attached machines should parallelize processing

### ISSUE THREAD

**Issue by christate** [AppliedEnergistics/Applied-Energistics-2#1268]
So, an ME Interface with multiple attached Molecular Assemblers will parallelize crafting; that's great.  I was expecting processing recipes on attached machines to behave the same, but apparently it doesn't.

Specifically, I set up an ME Interface block adjacent to two EnderIO SAG Mills, configured the physical inputs/outputs properly, and supplied the ME Interface with various grinding recipes.  The processing recipes *work,* but the Interface only ever dispatches work to one of the mills, leaving the other one idle.  This happens even if I've configured the Interface's blocking mode to not push items if the target inventory contains items.

IMO this should work like crafting via Assembler blocks, and allow multiplexing across identical processing targets, not least because only using a single channel for the extra capacity is a nice prospect.

**Comment by yueh** [comment]
This already happens and with blocking mode the distribution is even better.

The only exception (I currently know) are EnderIO machines. See #681 for more informations.

**Comment by christate** [comment]
Ahhhh, I see.  Thanks for the info!  For the alloy smelter in particular this is rather a show-stopper, but for the sag mill it should be easy to set up an automatic parallel dispatch thing with e.g. Extra Utilities round-robin transfer pipes.

**Comment by Wykks** [comment]
(Just in case someone stumble upon this, here a copy/paste of my answer in the enderio issue)

I found a way to overcome this issue by putting a chest between the interface (set to "Do not push crafting items if inventory contains items") and the ender io machine : 

![Solution](http://i.imgur.com/RkvJusM.jpg)

This way, crafts are evenly distributed across all alloy smelter :)

**Comment by XFactHD** [comment]
This was discussed in another issue already, it works for every machine except EnderIOs.

**Comment by TomyLobo** [comment]
for completeness, this issue is not limited to enderio, but also applies to at least some IC2 and extrautils2 machines. My test cases were the IC2 block cutting machine, IC2 Thermal Centrifuge and the EU2 resonator.
In fact, I have the opposite problem of @yueh, as I am not even aware of _any_ non-vanilla machine where blocking mode works.
