### ISSUE TITLE
More localization options

### ISSUE THREAD

**Issue by Adaptivity** [AppliedEnergistics/Applied-Energistics-2#1270]
*gui.appliedenergistics2.OfSecondOutput* should have %s tag for swapping *any number*% with "Chance for second output.". Is there any other similar strings which may require swapping in other languages?

~~Also, AE2 builds doesn't have pack.mcmeta included. But it is on Github, maybe buildscript doesn't recognize it?~~

€: prioritized the localization problem in this issue -- @thatsIch

**Comment by thatsIch** [comment]
Please, do not use one issue number to notify us about multiple issues, this makes managing them only harder (for referencing them and discussion)

**other strings** probably, just notify us, which require a better localization option

**pack.mcmeta** fixed indev

**Comment by thatsIch** [comment]
for pack.mcmeta https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1271

**Comment by Adaptivity** [comment]
I'm reported about pack.mcmeta here just because it's very(veeery) minor issue so I thought its not worth it to make another issue. But ok...

**Comment by thatsIch** [comment]
no biggie, just for the future
