### ISSUE TITLE
Dropped Items Disappearing

### ISSUE THREAD

**Issue by xypista** [AppliedEnergistics/Applied-Energistics-2#1280]
I had a water block surrounded by 4 Crystal Growth Accelerators. I made 2×64 Pure Certus Quartz in it. Then after a while I went back to create Fluix Crystals, but as soon as I dropped the ingredients out from my inventory they disappeared in the air.
I took the whole setup apart, filled the room with stone blocks, but after clearing the stones, that area still sucking up dropped items. Then, I removed AE2 and loaded up the map, and the problem was gone.

I created a video of the phenomenon: https://www.youtube.com/watch?v=4caVwZyvcgk
Nothing appears in the log files when it's happening. Anyway here is a log file that was created when I made that video: https://gist.github.com/xypista/7a2feefb2193b5ac88d3

Using rv2 beta-28

**Comment by thatsIch** [comment]
Can you try it the other way around?
Remove all mods except AE2 and try it again.

Also maybe some kind of Magnet or Random Things Item Collector around?

**Comment by xypista** [comment]
There is nothing near that sucks up items. (some normal hoppers a few blocks away, but I tried without them).

Removed everything but AE2: The world state is utterly corrupted and this save is NOT loadable
...

**Comment by thatsIch** [comment]
uh, it should still load up, even if you remove mods (after you hit the proceed button)

**Comment by thatsIch** [comment]
maybe remove mods by mods and then try to load up the world.

**Comment by xypista** [comment]
Okay, I found the mod that was missing (DragonAPI replaces vanilla items with its own versions...)
Well, it is not happening this way either. I'm sorry if I made the ticket prematurely, I should investigate further.

**Comment by thatsIch** [comment]
Thus closing
