### ISSUE TITLE
Open Crate doen't accept charges certus quartz from interface

### ISSUE THREAD

**Issue by Tsunayoshi** [AppliedEnergistics/Applied-Energistics-2#1281]
Hey,

I have tried the open crate from botania as dropper (crystal fluix crafting) but it seems the interface won't insert the charged crystal in the open crate (had this problem a with a few gregtech machines on another server to, but eh it's gregtech so I haven't report the issue).

Also the Charger runs out of energy, placed on an interface and with an enderio energy conduit (enhanced/orange) connected on top.
(Energy conduit is connected through a p2p tunnel, maybe this causes the problem, but I wanted to report it.)

keep going :) Can't minecraft (life) without ae2 anymore :p 

Versions:
forge-1.7.10-10.13.3.1370-1.7.10
CoFHCore-[1.7.10]3.0.1-254
appliedenergistics2-rv2-beta-28

**Comment by TheJulianJES** [comment]
#456 maybe?

**Comment by thatsIch** [comment]
Use the part interface for now, I still have no clue where the bug actually resides.

For the charger, please open up a different issue number (for referencing and processing)

Close this issue, if it is really #456

**Comment by Tsunayoshi** [comment]
Yeah looks like #456 :)
I wil test a few things with the charge to exclude a problem from my side and find more details to this problem.

**Comment by thatsIch** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/997

might be related if you mean by accident the energy acceptor and not the charger

**Comment by Tsunayoshi** [comment]
Hm could be related with chunkloading, but charger was right.
![2015-04-15_00 08 49](https://cloud.githubusercontent.com/assets/5128201/7148517/e6d6d3d8-e303-11e4-8be3-298b0d163e54.png)
Was it right that the Interface alone shouldn't load the charger, right?

The latest test worked all fine, maybe it was related to the open crate block. At the moment all works as it should with the openblocks dropper.

**Comment by thatsIch** [comment]
ME Interface can transmit power to network devices, so if you place the interface below or above it should power it. But I have not actually checked it tbh..

**Comment by yueh** [comment]
Only the non directional interfaces (block version without an arrow) will transmit power on every side. Once the are wrenched (or placed as part), they will no longer transmit power into this direction.

**Comment by Tsunayoshi** [comment]
confirmed :) Without the arrow the charger is charged trough the interface. I had no problems since the last report, so I think it was chunkloading related. Thanks for your help.
