### ISSUE TITLE
Problem with channels when controller is at server chunk boundary

### ISSUE THREAD

**Issue by theothersteve7** [AppliedEnergistics/Applied-Energistics-2#1284]
When an AE2 device that uses channels - import/export bus, terminal, etc - is within one or two chunks of the server render distance from the controller, whether by cable or by quantum link chamber, and the player occupies that same chunk, the device will randomly reset itself as though freshly placed once every several seconds. This will also cause any devices on the same length of channel to reset as channels are recalculated. Obviously this only applies if the controller is chunkloaded, otherwise the whole thing will simply cut out once you cross render distance.

This seems like a reasonably common scenario yet I can't find any discussion about it. I've reproduced this problem in about a dozen different ways.  This is likely to be the source of several other bugs on this tracker.

![2015-04-13_22 26 15](https://cloud.githubusercontent.com/assets/982237/7149523/a88ab13e-e2dc-11e4-9d44-28565f16d859.png)
Problem area including quantum ring

![2015-04-13_22 27 01](https://cloud.githubusercontent.com/assets/982237/7149525/a88c32fc-e2dc-11e4-9091-7f9970eb0238.png)
Controller

![2015-04-14_17 59 19](https://cloud.githubusercontent.com/assets/982237/7149524/a88ba90e-e2dc-11e4-92f9-d9ea8fe4fb78.png)
Showing that it's not ring-related

**Comment by theothersteve7** [comment]
I should note that this is in the Infinity 1.2.1 pack, so if you've fixed this problem since then, I apologize for the noise.

**Comment by yueh** [comment]
Yes it is a common user error, thus our first question is usually is the network chunkloaded.
Once a chunk unloads, it will remove these cables/machines from the network including possible connections to other chunks.

**Comment by theothersteve7** [comment]
You have misread.  This is not a question nor user error.

"Obviously this only applies if the controller is chunkloaded, otherwise the whole thing will simply cut out once you cross render distance."

The problem is when the controller is both at the render distance and has a chunk loader keeping it active.

To reproduce, place a controller and wire it to a network bridge.  Then, right around the render limit from the controller, place another bridge and connect to to a device such as a terminal.

You'll see what I'm talking about.  It's painfully obvious that this is a problem with how AE handles chunk loading.  I understand that you get a lot of tickets from people who don't understand the mod properly, but please, give this one proper examination.

**Comment by theothersteve7** [comment]
If I might make a conjecture about how the code behaves based on what I'm seeing:

Devices fitting the above specifications are randomly calling their initialization method for being connected to the network, as though being "unloaded" for "zero ticks."

The best fix I can imagine include increasing the timeout period before devices recalculate channels.  I have a sneaking suspicion that it does that every tick, which would also explain why large controllers are performance intensive.

**Comment by yueh** [comment]
You are mostly guessing that it is neither. Or using assumptions which are pretty much wrong (like how the ME network behaves or chunkloading)

But let me summarize some things you have written yourself (here and on reddit)
* You could not reproduce it in singleplayer
* You are using a hosting service for the server
  * They do not display basic information like vmargs
  * This probably also means they are hiding other things from you

As you confirmed that it works in single player, this means with at least 99% it is a chunkloading issue on your server. Probably 100% as I cannot remember a single case where using proper chunkloading did not solve it.

The ME network is only serverside and does not chunk loading at all.
Meaning your are completely depending on chunkloaders working correctly and not unloading chunks for a short time before notice it.
But as your provider is already hiding some information from you, how can you proof that they do not tinker with the chunkloading and cause exactly this behaviour?

Your best bet to confirm this as bug (which is very unlikely) and not question is to reproduce it in single player with as few mods as possible. Otherwise it just has too many moving parts. Especially if the server is not under your full control.

**Comment by theothersteve7** [comment]
You're looking at old comments from before I determined the source of the problem.  My initial guess of what was wrong was that a large number of quantum rings was causing it, but I determined that wasn't the case with single player.

Your suggestion that my service provider is including a hidden command line argument which causes chunk loaders to unload a chunk briefly before working strikes me as rather unlikely.  Asking me to reproduce outside of a mod pack is quite reasonable.

I will put together an album tonight from single player.  Is there a particular chunk loader you'd prefer me to use?  I had been using Chicken Chunks.

**Comment by yueh** [comment]
The source is chunk unloading and there is nothing we can (or want) to do against it.

I did not imply any commandline arguments. Just that the provider can control the chunkloading behaviour and for example use a quicker unload than usually and the chunkloaders do not cover that case but then force load them with the next tick or similar. Maybe they determined that reloading a chunk is less expensive in terms of CPU/IO than keeping a chunk longer than needed around. Thus saving some performance, better over provisioning of the servers, whatever.

I would highly recommend against using chicken chunks. There have been enough issues with them in the past. Basically what you described. So testing other ones on the server might also be an option.

**Comment by theothersteve7** [comment]
Could be.  I can understand blaming this on the chunk loaders.

What chunk loading mod do you recommend if not chicken chunks?  I need some sort of chunk loader to reproduce the issue.

**Comment by yueh** [comment]
I cannot recall any particular issues with railcraft or dimensional anchors.

It is not really blaming chunkloaders, just the usual issue. As that can be quite finnicky with minecraft and chunkloading.

The ME networks recalculate the channels really in cases of something is added or removed from the network. So either through a player (or anything which can place/break blocks,) power issues or chunkloading.
AE2 is designed to not use chunk loading like other mods or even things like vanilla hoppers, which are loading a full chunk just to store a single piece of cobble in a chest located in a currently unloaded chunk.

**Comment by theothersteve7** [comment]
Alright, I'll try to reproduce with those mods in a single player works tonight and post my results.  Thanks.

I understand the frustration about chunk loading, it's certainly one of the bigger hurdles in Minecraft mod design.

**Comment by theothersteve7** [comment]
I can't reproduce this in single player regardless of the chunkloader being used.  Found another issue in the process, however.
