### ISSUE TITLE
Issue using Forge Multipart on AE2 RV 1

### ISSUE THREAD

**Issue by Aeper** [AppliedEnergistics/Applied-Energistics-2#1285]
Problem: Server Disconnected client from Server due to placing a cover block from Chisel 2 using Forge Multipart on a Fluix Cable.

Currently using the following mods when this issue happened,
AE2 RV 1 Stable
Forge 10.13.2.1352
Forge Multipart 1.1.2.331
Chisel 2 2.3.9.36

PasteBin: http://pastebin.com/iCuScsDy

MC Side:
http://puu.sh/hepP4/23232b55c4.png

**Comment by Cisien** [comment]
Try updating ae2 to rv2, latest beta

**Comment by thatsIch** [comment]
The API changed, was fixed in early alpha
