### ISSUE TITLE
ME Controller side unresponsive after moving with FunkyLocomotion frames

### ISSUE THREAD

**Issue by merach** [AppliedEnergistics/Applied-Energistics-2#1286]
**The problem that is happening?**

Using the same design as direwolf20 in his single player 1.7 world (https://www.youtube.com/watch?v=t7xMm4RZPkA). After adding additional ME interfaces/mining wells and using another side of the ME controller, fluix smart cables connected to the south side of the controller no longer show any connection to the me controller after being moved. I tried the following to get it working again:
south side ME controller -> Dense cable to controller -> smart cable to dense cable
south side ME controller -> dense cable from controller -> ME interface
south side ME controller -> lime smart cable from controller -> ME interface
south side ME controller -> me interface
Adding a terminal to any part of the cable works
There is no message to indicate missing channel

Adding a second controller seems to fix the problem

**What was expected?**
As there are 32 channels per side, if the first 8 ME interfaces are chained through each other, the 2nd set of 8 should be able to chain and connect to the controller on another side

**How to reproduce the problem?**

I have not tested this independently yet, but having a setup similar to the screenshots should allow you to reproduce the issue. 16 ME interfaces attached to a moveable frame platform in a strait line, 8 interfaces per controller, powered by a tesseract on the opposite side of the non-functional side.

**Server or Single Player?**
Single player

**Mod Pack using and version?**
Direwolf20 1.7.10 verison 1.21

**Crash log (Please make sure to use pastebin for the log file)**
N/A

**Screen shots or Pictures of the problem**

http://imgur.com/a/e7UFw

**Comment by yueh** [comment]
Read this [site about channels](http://ae-mod.info/Channels/). Especially the part about design.
The second controller most likely makes it the shortest path.
