### ISSUE TITLE
Quantum bridges maintaining connection after singularity is removed at exactly eight channels

### ISSUE THREAD

**Issue by theothersteve7** [AppliedEnergistics/Applied-Energistics-2#1288]
Steps to reproduce:

Build two quantum bridges, connect to creative energy cells and interfaces.

Connect one to a drive.  Place items in drive.

Connect the other to seven level emitters, to bring the number of channels off that side to eight.

Connect via singularity.  After verifying that they are connected, remove the singularity from the second bridge (the one without the drive).  The items will still be accessible from either side.

Example:

![2015-04-15_18 41 31](https://cloud.githubusercontent.com/assets/982237/7170775/13f867d2-e39f-11e4-86ae-598a0cbfaa73.png)

Problem reproduced with appliedenergistics2-rv1-stable-1.jar and no other mods on minecraft version 1.7.10

Low priority, but I figured I'd report it while I'm here since I can't seem to figure out my other problem.

**Comment by yueh** [comment]
Cannot reproduce the inventory access over a disabled QNB. Also use the most recent version of AE2 to verify bugs.

That an adhoc network can support 8 channels is intended. Regardless of containing a QNB in whatever state. At least as long as it has power (here provided by the creative cell).
Also noticable as the channel indicators on the smart cables show the total network usage and not of the particular cable (as in a controller based network)

**Comment by TheJulianJES** [comment]
@theothersteve7 Yeah, please try with a newer build like @yueh sad, AE2 beta rv28 is currently the latest :)
