### ISSUE TITLE
[Config] Channel = false

### ISSUE THREAD

**Issue by Zoryn4163** [AppliedEnergistics/Applied-Energistics-2#1289]
When setting the config to disable ME channels I noticed that the game doesn't load channel-related blocks (Dense Cables, ME Controllers, and Smart Cables). I can understand why this would occur, but can cause significant issues with mods that are looking for blocks that do not exist. The issue I'm currently facing isn't directly involved with any *problems* with AE2 and I will have to keep channels enabled due to it, but the HQM mod looses it's mind when it can't find a quest item it's looking for. Some such quests involve AE2 items (All 3 of the aforementioned items, to be precise) and every time upon world load it throws a server-side 'java.lang.NullPointerException: Ticking memory connection'. 
I have to reiterate that this is *not* a problem with AE2, it's just an annoyance. I'm certain there's some way to still load the blocks and simply remove their recipes and/or disable their channel functionality.
Just for information I'm using RV2 Beta 28 from the main AE site and HQM 4.2.2. I realize that the system is intended to focus around managing these channels, but I myself am not a fan of the channel system and am simply requesting that something be done at some point in the future such that the blocks aren't outright removed from loading (I assume) and simply exist as useless decorative blocks.

**Comment by Cisien** [comment]
The choice to remove those blocks is functional more than cosmetic. Those blocks still use channels when they are disabled. You have the ability to change recipes.

As for mods breaking... In your case, you need to change the quests to not use these items.

**Comment by yueh** [comment]
If you need more information on why this needs to be done, you can read it up in the other reports about the same issue on this tracker. (Which prevents them being a decorative block)

I am also pretty sure that we are not the only mod disabling, hence HQM should account for that option and not crash.

**Comment by Zoryn4163** [comment]
Yes I got it working finally. I'm slightly surprised that it's apparently not feasible to make them decorative blocks but yes, that is HQM's fault. Thank you for responding.
