### ISSUE TITLE
CraftingCard in Interface cannot see subnet items stored in interface

### ISSUE THREAD

**Issue by gekotrav** [AppliedEnergistics/Applied-Energistics-2#1290]
Version: rv2 beta 14 (Regrowth FTB pack)

Setup: Main network has interface w/ crafting card facing a storage bus and is requesting items to be crafted. Crafting materials are stored on a sub-network through a storage bus facing an interface.

What works: requesting a manual craft of the item in a terminal has it show up in crafting storage with no issues.

Issue: Having an interface w/ crafting card do the crafting request and it is unable to see the items stored on the sub-networks interface.

Proof: Switching the sub-networks interface to an ME chest w/ correct materials allows the system to autocraft.

**Comment by yueh** [comment]
#329

**Comment by gekotrav** [comment]
Sorry didn't see an issue in the recent pages. I know you don't want feedback loops but isn't that what the priority system is for?
