### ISSUE TITLE
Quantum Ring reseting

### ISSUE THREAD

**Issue by nunley21** [AppliedEnergistics/Applied-Energistics-2#1291]
My Quantum Ring keeps resetting in my rf tools world. both are powered with plenty of energy. i have to disconnect all cables and the rebuild the Quantum Ring to fix it. 
Version: rv2-beta-8

**Comment by Cisien** [comment]
Try a newer ae2 build

Also make sure you have both ends chunk loaded.

Also make sure you have some energy cells on the network. AE has a small buffer that can be exhausted quickly regardless of the amount of power you give it from external sources

**Comment by nunley21** [comment]
That worked thanks a ton
