### ISSUE TITLE
Remote Interface Terminal

### ISSUE THREAD

**Issue by power-spike** [AppliedEnergistics/Applied-Energistics-2#1292]
When your working on the automation the amount of running around you do is insane!

Would it be possible, to maybe have a "Me remote interface terminal", This terminal would connect to all the interfaces on the network, just like the Me interface terminal does, however it will allot you to manually put items in. 

An example would be putting a copper ingot into a sag mill remotely to get back the copper dust. (so you could make the pattern)

**Comment by yueh** [comment]
#1040
