### ISSUE TITLE
There's a typo on the description page for ME Dense Cable

### ISSUE THREAD

**Issue by mwoodward** [AppliedEnergistics/Applied-Energistics-2#1293]
On the [ME Dense Cable description page](http://ae-mod.info/ME-Dense-Cable), there is what I beleive to be a typo.

The paragraph reads (typo in **bold**):

>Higher Capacity cable, can carry 32 channels unlike standard cable which can only carry 8, however it doesn't support buses so you must first step down from dense to a smaller cable (such as ME Glass Cable or ME Smart Cable) before using buses or panels. Shows load similarly to **ME Dense Cable**, with each line lit representing four channels in use.

I believe the item in bold *should* be **ME Smart Cable**.

I created an account on the site thinking it was similar to a wiki and that I could edit it myself, but apparently, that's not how it works.

**Comment by thatsIch** [comment]
Thank you!

Fixed
