### ISSUE TITLE
Facades doesn't work on full block interfaces

### ISSUE THREAD

**Issue by Tsunayoshi** [AppliedEnergistics/Applied-Energistics-2#1294]
I have in mind that this worked in rv1?
![2015-04-18_13 22 32](https://cloud.githubusercontent.com/assets/5128201/7215242/da034c0e-e5ce-11e4-80b1-60c4ffe8a1a5.png)

Is it intend that the facades only work on the small form?
![2015-04-18_13 24 27](https://cloud.githubusercontent.com/assets/5128201/7215243/debe7cbe-e5ce-11e4-8ed6-7ec5564d7b90.png)

Because the small form doesn't transmit energy to the charger (top left):
![2015-04-18_13 25 09](https://cloud.githubusercontent.com/assets/5128201/7215244/ec1be04a-e5ce-11e4-9c18-17553561535c.png)

If this is intend, can you allow to connect a energy cable in the back of the charger?

**Comment by TheJulianJES** [comment]
I think they sad that this would require a rewrite.

**Comment by thatsIch** [comment]
This was a feature in AE1, since you have multiparts, this is not really required and wasa never implemented in AE2,

also, if you had put a facade on a ME Interface, it was basically just a basic block, thus not pushing items or anything like that.

**Comment by Tsunayoshi** [comment]
Well then, what about the request to transmit energy trough the interface multipart or the energie line in the back of the charger? :)

**Comment by thatsIch** [comment]
rather not, multi parts are supposed to be limited in functionality in exchange for their space efficiency.

you can charge them through the top too or with a crank :P
