### ISSUE TITLE
[minor minor enchantment] connected textures on facades

### ISSUE THREAD

**Issue by Tsunayoshi** [AppliedEnergistics/Applied-Energistics-2#1295]
I don't know how hard this, but if I don't ask, I will never know ;)

The facades blocks from enderio works fine with connected textures, even with chisel2 blocks (surprised me!).
![2015-04-18_13 30 35](https://cloud.githubusercontent.com/assets/5128201/7215276/f99f22c6-e5cf-11e4-8f7b-6a5e02cd52d6.png)
![2015-04-18_13 30 33](https://cloud.githubusercontent.com/assets/5128201/7215278/175d9c7a-e5d0-11e4-9a1f-6f3443d47a54.png)

Is this possible for facades? I haven't really a problem with this, because on the terminals it looks great but the back side is more a problem :D

![2015-04-18_13 30 44](https://cloud.githubusercontent.com/assets/5128201/7215275/f7ac3684-e5cf-11e4-9e5c-2d34f0a65532.png)
FMP have the same look, so maybe this isn't possible for parts?

**Comment by yueh** [comment]
#740

**Comment by Tsunayoshi** [comment]
Ah I had that feeling. Thanks for the Info.
