### ISSUE TITLE
Channel troubles

### ISSUE THREAD

**Issue by vandenboer** [AppliedEnergistics/Applied-Energistics-2#1296]
![bug ae2 1](https://cloud.githubusercontent.com/assets/12011244/7216942/8d978d5a-e612-11e4-8620-8de54f731816.png)

The blue cable has 22 channels used (from the source at the controller)

**Comment by marduvGitHub** [comment]
@vandenboer Can you also tell me the direction you are facing when you look at the picture? (South, West, North, East)
And which versjon are you runing? (rv2.beta build 28)

Have a issue my self when I set up: interface, molecular assembler, molecular assembler, interface side by side in the south and north direction and stack this 8 times up on each other. (Hight have nothing to say)
If I remove molecular assembler on one of the sides distribution of channels works right.
Creating the same setup in the west and east direction is working properly.

**Comment by thatsIch** [comment]
Maybe provide a better image for starters? I basically see nothing but the smart cables.

**Comment by marduvGitHub** [comment]
@thatsIch Is my description of my issue clear enough so you can replicate it?

**Comment by thatsIch** [comment]
sounds like http://ae-mod.info/Channels/

**Comment by marduvGitHub** [comment]
I have enough channels!
Im am using dens cable before splitting to glass cable in 4 rows with 8 interfaces each. (Did try just with 1 interface also)
@thatsIch Way is the same setup working in the one direction but not the other?
And yes I have try to disconnect the other direction that did not work.
I do mange to establish connection to all interfaces if i do not connect the molecular assembler side by side one the south and north, but in the west and east direction I don't need to do that for it to work :-S

**Comment by Cisien** [comment]
That picture is garbage, basically, all AE machines transmit channels. Are the inscribed creating a short circuit?

**Comment by vandenboer** [comment]
Well i shall explain : my channels for the import busses beneath the inscribers work ,i see that the channels era used , however the upper cable the one with the interface and the level emitter and the export bus only uses 2 channels , but  I want the interfaces and exportbus and level emitter to be connected to my ME system . I don't know why it does this , The blue dense cable only uses 22 channels so it shouldn't be a problem.

**Comment by vandenboer** [comment]
Found the problem : it was a crafter connected with a covered cable

**Comment by thatsIch** [comment]
@marduvGitHub never said anything about not enough channels. I suggest you reading the article and scroll down a bit.

What ever a crafter is, thus closing

**Comment by marduvGitHub** [comment]
@thatsIch Sorry, I did get what you was trying to tell me now...
Thanks for the help! :-)

**Comment by thatsIch** [comment]
You are welcome :)
