### ISSUE TITLE
"A Fatal Error Has Occurred" When putting items into an ME Terminal

### ISSUE THREAD

**Issue by chudders1231** [AppliedEnergistics/Applied-Energistics-2#1297]
Hello, i have recently started playing around with AE2, i had make a 4K Storage Cell into a ME Drive. I then filled it up with plenty of items but i shift clicked them in encountering no problems.
I then started making things in the ME Crafting terminal and i get this error:

<img src="http://i.imgur.com/ED1zvQu.png"/>

When i click "Quit to title screen" it takes me the the multiplayer screen:
<img src="http://i.imgur.com/RI9b9tg.png"/>

This is the ME Network setup just incase you needed it:
<img src="http://i.imgur.com/PFW8uA0.png"/>

If you need any more info i will gladly supply you with it!

thanks in advance!

Chad

**Comment by thatsIch** [comment]
Why not supply them from the start?
Version, logs, server logs, MCPC, Bukkit etc.

**Comment by chudders1231** [comment]
I am using Minecraft 1.7.10 , i am using Applied Energistics 2 rv2 beta-22 . I am not using MCPC / Bukkit as i am playing in single player! Therefore i cannot supply you with server logs. Moreover it isnt crashing, it is disconnecting me and putting me on the multiplayer screen. This is the mod list : 

https://docs.google.com/spreadsheet/ccc?key=0ApSFdDeB_HR7dDRoQkwxd2xsMDF3b0FRRXAtLV94cmc&usp=sharing
<br>
<embed src="https://docs.google.com/spreadsheet/ccc?key=0ApSFdDeB_HR7dDRoQkwxd2xsMDF3b0FRRXAtLV94cmc&usp=sharing" style="width:500px;Height:1000px;/>

**Comment by yueh** [comment]
This is an issue with b22, the modpack needs to update AE2 to a more recent version.
