### ISSUE TITLE
Wireless Access Terminal Crafting Initiation

### ISSUE THREAD

**Issue by MassiveNetwork** [AppliedEnergistics/Applied-Energistics-2#1298]
I play on a server that uses AE2. I use Wireless access terminals to easily use my ME system. When I attempt to intiate a crafting job I get kicked from the server and the job is never initiated due to being kicked instantly after clicking "Craft"

**Comment by TheJulianJES** [comment]
Update AE2 to the latest beta build.

**Comment by Omniwrath** [comment]
Updating did in fact fix the problem. Thank you.
