### ISSUE TITLE
Meteor Destroys Mining machines

### ISSUE THREAD

**Issue by simfrek** [AppliedEnergistics/Applied-Energistics-2#1301]
![image](https://cloud.githubusercontent.com/assets/3540773/7235350/9bc51a22-e785-11e4-89f8-3187fe59a070.png)
this shows what my mining machine now looks like, i am currently running on the Direwolf20 modpack version 1.2.1 it seems as though the ae2 meteors destroy terrain after funky locomotion moves objects into their range, is this intended as its very annoying to have to rebuild my mining machine every time it finds a meteor, is their any other information you would like from me? i am running this on my own private server so can get you any logs you might want?

**Comment by yueh** [comment]
#634
