### ISSUE TITLE
Rotation of blocks in the inventory

### ISSUE THREAD

**Issue by TheJulianJES** [AppliedEnergistics/Applied-Energistics-2#1303]
Screenshot: http://imgur.com/IxQIaGC
I know it's probaly minor issue (or maybe even a feature...).
Expected: The block faces to the right.
Currently every AE2 version has this (minor) issue.

**Comment by yueh** [comment]
This is not even consistent in vanilla or other mods. So I doubt this is an issue.

**Comment by TheJulianJES** [comment]
I think in vanilla they are...

**Comment by Entoarox** [comment]
Stairs face left, all other directional blocks face right.
Mainly this is vanilla though, and personally I dont see why they would bother changing the inventory direction when the block works perfectly fine in-world anyway, and yueh is right that mods usually follow their own choices in this, so a minor thing like this is pretty much unnoticeable.
I'd be somewhat more concerned if stairs got reversed, as that is quite a lot more obvious.

**Comment by TheJulianJES** [comment]
@Entoarox Like I sad, this is a minor bug but stairs are not a full block. :D

**Comment by yueh** [comment]
Stairs, fences, walls in vanilla. Mabye other blocks, but without different sides not noticable.
Factorization for example faces the barrels left and the furnace right or enough other mods behave differently.

I personally would even prefer facing left as we use LTR, thus having the more important piece on the left is actually providing a better usability.

**Comment by TheJulianJES** [comment]
@yueh If want so, sure ;)
