### ISSUE TITLE
NEI does not show recipes ae2

### ISSUE THREAD

**Issue by vobis** [AppliedEnergistics/Applied-Energistics-2#1305]
NEI does not show recipes ae2
minecraft forge 1.7.10
additionally installed 83 mods

**Comment by TheJulianJES** [comment]
What version of AE2 do you have?
Also can you please post the log.

**Comment by nemmises5** [comment]
I have the same issue, using RV1 I posted it in the FTB subreddit, but the fix they suggested didn't work

http://www.reddit.com/r/feedthebeast/comments/33fhvk/applied_energistics_recipes_not_working_nor/

I have no log.

**Comment by yueh** [comment]
#1061
