### ISSUE TITLE
Recpies that include output as an input cannot be crafted

### ISSUE THREAD

**Issue by Nonsanity** [AppliedEnergistics/Applied-Energistics-2#1307]
In attempting to automate a device from the Botania mod that duplicates certain items like Redstone at the cost of mana, I discovered that a Processing Pattern like (1 redstone -> 2 redstone) can be created in a Pattern Terminal, but attempting to use it shows "Redstone, Available:1, To Craft: 2" in simulation mode only with no option to start the craft.

It seems the input and output items are co-mingling, which confuses the craft into acting as if there is no registered output and therefore nothing to actually craft. The crafting cycle then becomes a loop.

(If anyone knows of a workaround to this issue, I'd be happy to hear it, but support for this sort of recipe might best be added to the mod itself.)

**Comment by yueh** [comment]
#439
