### ISSUE TITLE
Wool Lost When NEI Recipe is Shift Clicked Into Crafting Terminal

### ISSUE THREAD

**Issue by Omniwrath** [AppliedEnergistics/Applied-Energistics-2#1310]
There are many potential culprits here, AE2 is my guess as to the most likely culprit. For the record, my server is using Fastcraft. The problem I'm having is that sometimes, as the title says, when a recipe containing wool is shift-clicked into the crafting terminal, items are sometimes lost in the process. This may happen with other items, but so far I only noticed it with wool. This only happens when materials are pulled from the player inventory due to an insufficient supply in the ME system. It also only happens in the ME crafting terminal. The same process at vanilla crafting tables works as intended.

The recipe for a bed will consume up to 16 wool for every one wool required in the recipe. See the pictures below.

![image](https://cloud.githubusercontent.com/assets/2548999/7293646/939599c6-e95b-11e4-856b-9ad6c1d89db5.png)
I have 9 wool in my inventory.

![image](https://cloud.githubusercontent.com/assets/2548999/7293657/aace7176-e95b-11e4-9e72-3fac3ddc22c3.png)
I shift click the question mark to place the recipe into the crafting terminal.

![image](https://cloud.githubusercontent.com/assets/2548999/7293695/f7fb872c-e95b-11e4-9f73-85e70671ff74.png)
The end result is that 8 wool is lost. The wool is not placed in the ME system or otherwise mislocated. Logging out/in does not force the wool to reappear in my inventory.

If I do the same thing with a stack of 64 wool in my inventory the end result is that the recipe is finished for the cost of 48 wool.
![image](https://cloud.githubusercontent.com/assets/2548999/7293745/6a4ef110-e95c-11e4-9bf5-9fcba70ffefd.png)

Let me know if you have any questions or if I can help with further testing.

**Comment by yueh** [comment]
Confirmed. I am really tempted to just pull the whole feature/PR as it is really buggy. (using the player inventory as source)

**Comment by Omniwrath** [comment]
Fantastic turn around on that. I'm happy you were able to salvage the feature (for now at least).
