### ISSUE TITLE
Export/Import bus with level emitter and acceleration cards does not stop at expected level

### ISSUE THREAD

**Issue by Bondza** [AppliedEnergistics/Applied-Energistics-2#1313]
When using import/export buses with one redstone card and one to three acceleration cards it will always export more than one item per tick. Which means that it will not stop at the set level.

For example with a level emitter set to emit above or equal to 101 and three acceleration cards and two stacks of the item to export. I would expect it to export 28 items and leave 100 items in the system, but instead it exports a whole stack of items and then stops. Leaving just one stack of items in the system.

I am guessing that the reason for this is that acceleration cards just increases the number of items exported per tick.

Tested on rv2-beta.-28.

**Comment by yueh** [comment]
As you already guessed, acceleration cards only increase the amount of items exported each tick.
For export/import buses it will be 1 item/tick (0 cards), 8 (1 card), 32 (2), 64 (3), 96 (4).
These might change/behave differently for other machines.

The reason is mostly for performance. There is pratically no difference on the load with extracting 1 or 96 items. But extracting 1 items 96 times, will also be a 96 times higher load on the server.

**Comment by Bondza** [comment]
I can imagine that would have a big impact on performance.

I had a look at the source code last night, and as far as I can see the
import/export bus is not aware that there it is controlled by a level
emitter, at least not which one. So it is not possible to calculate the
difference between the amount to export and level when it should be
disabled.

Would it be possible to make the buses aware of the level emitter settings?
That way it would only need to export once.

**Comment by yueh** [comment]
They only care about a redstone signal and nothing else.

Changing it is acutally not feasible for a couple of reasons. Mostly that it might not be possible to calculate the actual difference without know where the items get exported to, to which network the level emitter belongs or even account for any other mod inventory. Say you export into an enderchest and use a different enderchest with the same colors somewhere else as source for the level emitter.

It might be an idea to scale it with the redstone strength. So if the strength is only 5, it will export `96 * 5/15` per tick. But I would not be suprised, if that is already to complex for some users and backfire as issue.
