### ISSUE TITLE
"Sync" Problem?

### ISSUE THREAD

**Issue by Elvarion** [AppliedEnergistics/Applied-Energistics-2#1314]
appliedenergistics2-rv2-beta-28

Im hosting a server for a small number of people, 4-5 people are online at the same time.
Server is running smooth, Always on 20TPS and MS is around 15-20, peaks sometimes above.

The thing is that my AE System gets broken every now and then. All items just vanish (They are still there, just that I cant see them, nor pick up them.
As can be seen here, my system is Empty
http://gyazo.com/fd1e6527ca74b67a8969a7e43f1f2913
And its not a missing channel issue (The GUI would be dark then)http://gyazo.com/e9801261d29d79f361d193a842f16b58
Just one of few cells ive got (The JABBA is connected with Storage Bus, so the ingots should also be shown in the system)
http://gyazo.com/d294f540b3e197abccdbc672d9b19abd
My Drives
http://gyazo.com/4495c3e8ac79509d3e75493260845524
Placed an EnderPearl into the System
http://gyazo.com/e73fb55968f55c6b58104e7eed78a76d
Added/Removed pearls & Opened/Closed the Terminal, Woila. Everything is back.
http://gyazo.com/5390bb24f71330737e303275dceb23f0

This started happening today/Noticed it today, and we updated to rv2-28 a few days ago.
Does anyone know whats happening?
Cant see anything AE related in any logs
(edit: spelling)

**Comment by Yadokingu** [comment]
Does your whole system lose power for a moment? Because that happens to me, despite the fact that there are two fully charged dense energy cells in the system and the power supply is hooked to a Droconic Energy core that has 15 Billion RF in it at the moment.
Also only started happening today. 
rv2-18 here.

**Comment by Elvarion** [comment]
No, the system never goes dark. The system is connected to Two Big Reactors producing well above 20k RF/t each.

**Comment by mindforger** [comment]
@Elvarion connected in which way? Assuming your connection is via some sort of limited Power Cable it is indeed possible to have power surges higher than thei transport capacity from extensive input/ouput operations, try adding a few energy cells to the system to compensate the surges.
Same goes for Bridges, always buffer the bridge or it will start flickering!

**Comment by Elvarion** [comment]
Big Reactor > Ender IO Capacitor Bank (Can output 600k) > Tesseract > Tesseract > AE Controller.
Before getting my power sufficient I noticed the Bridge flickering. But this was weeks ago.
Ill try and add some cells just for the sake of it might helping, But im pretty sure energy isnt the culprit.

**Comment by Cisien** [comment]
Also, check, then check again, then double check some more that your entire ae2 network is chunkloaded

**Comment by yueh** [comment]
You are outputting 600k RF each tick into something only able to store an equivalent of 10k RF and these 10k RF are not enough to satisfy a demand of 12k RF. (Change the demand to something higher if needed)
You think that is not a power issue?

**Comment by Elvarion** [comment]
This is my system
http://gyazo.com/e7750ccd1b222f7772d3694d26789c71
A system thats draining 12k and can only accept 10k. Yes that would be a power issue.

During the last 30min of gameplay after adding the energy cubes and fiddling around with my system its never gone blank. Perhaps it just wanted some more energy storage. Only thing I find strange is that if it was an energy problem the system should go dark, but it never has.

My capacitor bank is also setup so it CANT run out of RF. It even has an emergency setup should if fall under 25%. 8 Nether Star Generators from Extra Utils kick in and produce around 300k RF/tick for 5min~ This is well above what my ENTIRE base is using even with every machine running.

**Comment by yueh** [comment]
Your capacitor bank or power generation is completely irrelevant, you could even attach an infinite RF source and still have power issues.

The only important thing is your network and how much energy it can store. Because it can never accept more RF per tick than it can actually store. So as already said, if your network can only store 10k RF, it can also only accept 10k RF/t, even when needing more than it. As our energy system will only inject energy once per tick.

Also as @Cisien said, chunkload your network. You did not give any hint about using a QNB in the original post and it is pretty common that people forget to chunkload both sides and causing the network to constantly rebuild itself because of chunk unloads.

**Comment by Elvarion** [comment]
My main AE system is chunk loaded with 1 World anchor, 6 spot loaders thats placed here and there to make sure various vital parts of the system is loaded
The other side of the Bridge has a World anchor right under it and its full of pearls.
My system has gone blank while being at the main part of it, when not using the Bridge.

**Comment by thatsIch** [comment]
This looks more like a Storage Bus set to write only (and probably high priority).

If you can reproduce it, upload a world only with AE2 installed with a minimal setup how to reproduce this.

**Comment by Yadokingu** [comment]
"No, the system never goes dark. The system is connected to Two Big Reactors producing well above 20k RF/t each."

Like I said, my system has more than enough power as well, it still goes dark for 1-2 seconds from time to time, then comes back online with 3 dense energy cells still fully charged. 
Also weirdly enough the wires only go down for a second while the rest stays dark a bit longer.

Here are some screenshots of my problem:
https://i.imgur.com/XQW13bl.png
https://i.imgur.com/F1wb1FA.png

Still think it's not the same issue? If so I guess I'll have to open a new one...

**Comment by Elvarion** [comment]
@thatsIch Ill see what I can do tomorrow
@Yadokingu Dont think we have the same issue. My system is always online, yet it goes blank and I cant see the items

**Comment by thatsIch** [comment]
Maybe related to https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1189

**Comment by Elvarion** [comment]
Read #1189, Sounds very similar to my experience
