### ISSUE TITLE
Shift clicking blank patterns into pattern terminal does not prioritize the pattern slot

### ISSUE THREAD

**Issue by thatsIch** [AppliedEnergistics/Applied-Energistics-2#1315]

**Comment by yueh** [comment]
Encoded patterns should probably also prioritize the bottom slot.

Sadly there is no real filter/priority, just check if every inserted item can be inserted into the pattern slots before inserting it to the network itself.

**Comment by Lodran** [comment]
This begs the question - does the pattern terminal have an inventory, and could an export bus be connected to it somehow, to allow automatic refilling of patterns?

**Comment by thatsIch** [comment]
Probably something like a crafting upgrade might be the " smarter " solution

**Comment by Lodran** [comment]
Another possibility would be to have a "cube" version of the pattern terminal (much like the cube version of an interface) which would provide and obvious way to connect an export bus.
