### ISSUE TITLE
Inscriber/Waila power issue

### ISSUE THREAD

**Issue by floridaman** [AppliedEnergistics/Applied-Energistics-2#1316]
Waila is not correctly rendering the power information for the inscriber when it is powered directly from the AE network. Constantly displays:
0/3000 RF
Contains: 0 AE / 1.5 kAE

The machine is actually receiving power from the ae network and fuctions properly
Also, Waila will show the correct power status when the inscriber is directly powered by another source such as ender io conduits.

I've isolated this issue with just these mods installed:
FML 10.13.2.1291
AE rv2.beta.28
Waila 1.5.10

*photos are from my custom modpack but i verified the issue with only the 3 mods installed.

![2015-04-23_15 54 26](https://cloud.githubusercontent.com/assets/9640443/7308376/23966be8-e9d1-11e4-8919-efad65ae728f.png)

![2015-04-23_15 54 20](https://cloud.githubusercontent.com/assets/9640443/7308368/199cc510-e9d1-11e4-8d5f-a1f78cbd3d34.png)

**Comment by yueh** [comment]
This is actually correct.
AE2 machines will not store energy when powered directly by the network, instead the directly extract it from the network when required.
If powered with an external source, they will act as small energy buffer which then is used to extract energy when needed.

**Comment by socialretard** [comment]
That make sense but how come the charger shows the power levels then?

**Comment by yueh** [comment]
Chargers do not really have a progress like inscribers but instead use their internal buffer as progress and charge a crystal once full as well as being able to prepare for the next operation.
We could potentially hide this somehow and display it as 0, but this is not a good solution.

It might be an idea to hide these, if they are directly powered by the grid. But the RF info is probably not under our control, as these are created for every tile supporting RF. (Except stripping the RF support from everything but the energy acceptor, which is of course also a bad idea)

Both could potentially see some sort of refactoring and simplify the energy consumption and always use the local battery. Probably also for the ME chest. Especially the chest could be quite interesting and give it an actual use by having it basically powered by an UPS for a while in case of a power outage but still some emergency supplies accessible for a while. But that is another feature request.

**Comment by BoboSims** [comment]
I always wondered: the network will not run on any energy other than AE2 energy. If you want to power it from something else, you need to put in an Energy Acceptor as a kind of 'transformer/adapter'. That makes sense. But what did not seem to make sense to me, was that when I powered the system from RF, the AE2 devices powered through this 'adapter' would STILL show RF as their power source. I'd have expected the AE2 side of the network to only show values in AE2-related units, not RF.

But now I think I understand how this works. Thanks for that, @yueh.

**Comment by thatsIch** [comment]
Its just a convenient way to save the user to calculate how much energy something is using 
(remembering the ratios and actually calculating them) though it is not dependent on RF alone, but on which setting you set the energy display on.

**Comment by BoboSims** [comment]
Exactly. I understand that now. In my case it shows RF because it's powered by an RF network, which allows me to keep my RF network up-to-date with the needs of the ME system. Anyone using another type of power would see the numbers fitting their power source.

**Comment by thatsIch** [comment]
Also actually displaying it is less meaningful for AE2, since it has no actual energy production as in terms of exporting it to another system/mod

**Comment by Amindv1** [comment]
This is definitely still an issue. See the screenshots attached. This is the direwolf20 1.7.10 modpack.
![2016-07-09_20 23 44](https://cloud.githubusercontent.com/assets/6717198/16710993/e95ceeac-4613-11e6-9522-c7cf8a6cef6d.png)
![2016-07-09_20 23 50](https://cloud.githubusercontent.com/assets/6717198/16710995/e97e5ab0-4613-11e6-8a53-4676d7fed174.png)
![2016-07-09_20 23 38](https://cloud.githubusercontent.com/assets/6717198/16710994/e976f90a-4613-11e6-8c6e-6f735fce14d0.png)

**Comment by lerby** [comment]
Since this problem wasn't closed - i will ask you about WAILA problem there.

We are still unable to
1) somehow store maximum energy in every block?
2) at least hide this reeeeaaly frustrating 0 AE somehow?
