### ISSUE TITLE
ME chest using internal battery as backup energy source

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#1317]
ME chests could use their internal buffer to stay online for a while after the power is cut. Mabye for a full minecraft day, but extracting items will still consume more power.

This would give them a unique feature compared to the drive and let them for example act as an emergency supply and contain some fuel to get the energy production back online.

**Comment by LastXsile** [comment]
I agree with this, always felt like it was lacking something for what it was. I also thought that if you put portable drives in a chest that it should be powered from the drive if it has no other source of power. I always wanted this map making.

**Comment by BoboSims** [comment]
Having a slot in the ME chest to fit some kind of battery would help. And since the ME Chest already accepts non-AE2 power, I was thinking that allowing this slot to take Thermal Expansion's 'pokeball'-like portable energy-storage cells would work. But maybe an IC2 battery could work too.

**Comment by yueh** [comment]
I am not sure that adding such a functionality makes sense as long as AE2 does provide their own portable battery. (Energy cells are probably be a bit to large in size to count as battery).
But a battery would mostly be useless besides acting as crafting material. If it would also power RF tools, this could open a loophole to transform AE into any other energy type, something we really want to avoid.
So it would just add a useless slot, which only works when another mod is present.

**Regarding the chest itself.**
It currently has a tiny buffer of 40 AE and can consume 1 to 3 AE/t depending on the used cell.
This will last between a bit over 0.5 seconds to at max 2 seconds. Which itself is pretty useless.
So we mostly need to increase that buffer and check if the chest charges itself from the network and not just external sources.

But I am currently uncertain about the amount/length.
Too long makes a setup using an energy cell in many cases obsolete, but this requires a more complex setup. For example quartz fibers are not one way, so they need a reliable way to being cut of in case of a power outage.
Also it would put a large strain on early game when a chest has an internal buffer equivalent to serveral thousands or ten thousands of RF.
Too short and it would pretty much be useless.

A piece of coal for example is equivalent to 8k AE (should that not be 16k as a piece of coal is not usually producing 32k RF?). Which would last a bit over 6 minutes with a 1k cell or 1/3 of it with a 64k. So an equivalent of 1 or 2 coal might be an idea? (Depending on a possible rebalancing of coal)

**Comment by BoboSims** [comment]
@yueh: Indeed, *IF* AE2 were to provide their own batteries, my suggestion of supporting outside power would be totally irrelevant. But so far, it does not.

I *do* however completely support your other concerns: too little would be pointless, but too much would invite abuse of the feature.
