### ISSUE TITLE
nei crash with tank search

### ISSUE THREAD

**Issue by Feinixx** [AppliedEnergistics/Applied-Energistics-2#1318]
not sure if this a bug or conflict in AE2 but i see the word ae2base. any help would be nice

http://pastebin.com/FSirGBwG

**Comment by yueh** [comment]
#1118

**Comment by jogi01** [comment]
same problem here after searching for tank and now crash good work

**Comment by Feinixx** [comment]
You need to make sure all the mods with liquids have compatible versions. That was my issue
