### ISSUE TITLE
Crash when ThermalExpansion is missing

### ISSUE THREAD

**Issue by Bondza** [AppliedEnergistics/Applied-Energistics-2#1320]
If I only have AE2 installed, it crashes when scrolling to the bottom of the first page of AE2 items with a ```ClassNotFoundException``` because ```IEnergyReceiver``` is missing. Stack trace: http://pastebin.com/sHpm3cWb.

After installing ThermalExpansion with it's dependencies it seems to work just fine.

So this is ThermalExpansion actually a hard dependency? Or have I misunderstood something? Tested with rv2-beta28 and built the jar my self from HEAD of rv2.

**Comment by thatsIch** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/1279
