### ISSUE TITLE
Waila NBT error

### ISSUE THREAD

**Issue by Antecer** [AppliedEnergistics/Applied-Energistics-2#1321]
![20150425124305](https://cloud.githubusercontent.com/assets/8684916/7331575/146e1b92-eb49-11e4-8371-5d725e7ef5e5.png)
![20150425124317](https://cloud.githubusercontent.com/assets/8684916/7331577/147015d2-eb49-11e4-8022-b65aff9bce0d.png)
![20150425124333](https://cloud.githubusercontent.com/assets/8684916/7331579/14746150-eb49-11e4-8e62-3a911394bcec.png)
![20150425124343](https://cloud.githubusercontent.com/assets/8684916/7331576/146eec52-eb49-11e4-8158-04d3e067e650.png)
![20150425124611](https://cloud.githubusercontent.com/assets/8684916/7331578/14719c54-eb49-11e4-9000-ee1661afbf60.png)

This all show "tile.appliedenergistics2.BlockCableBus.name=AE2线缆和(或)总线"

**Comment by autopsychorhythmia** [comment]
It has no relation with AE2, perhaps this wailaNBT config file isnot completely corresponding with its localized string.

**Comment by Antecer** [comment]
Why in the "rv2.beta build 28" NBT all right?
This BUG Only in the "rv2.beta build 29"，I don't know how to fixes it

2015-04-25 13:34 GMT+08:00 Erlkönig <notifications@github.com>:

**Comment by thatsIch** [comment]
I dont know what the message is saying, since I never learned Chinese (thats my guess) but it works for me

I assume your ResourcePack is not uptodate to our latest version.

![2015-04-25_10 28 59](https://cloud.githubusercontent.com/assets/2210496/7332229/0fef6548-eb36-11e4-8231-6882d569c5c2.png)

**Comment by Antecer** [comment]
before build29 it show item's name!

**Comment by thatsIch** [comment]
That is cause your ResourcePack is not uptodate, when we change stuff, they need to adept.
They should not override `lang` files in the first place.

**Comment by XFactHD** [comment]
You just have to open the zip file of your resource pack with something like WinRAR and the go to the assets folder and, if there is a folder named lang, you just delete it.

**Comment by Antecer** [comment]
thanks,i know what to do.
