### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by colruytXD** [AppliedEnergistics/Applied-Energistics-2#1322]
Everytime i start up my server with ae2-rv2-beta-29 i get a missingmodsexception :/ hope you can help

**Comment by thatsIch** [comment]
Log please?

**Comment by colruytXD** [comment]
http://pastebin.com/Ax7gBB3m

**Comment by thatsIch** [comment]
Update your Forge
AE2 requires 10.13.2.1291 and you have 10.13.2.1286 installed

Next time, run in your client first and or use a `logging.properties` which is set to a finer level, to actually see the error messages printed by the loggers.
