### ISSUE TITLE
Game crashs when you go into a world

### ISSUE THREAD

**Issue by Felixkruemel** [AppliedEnergistics/Applied-Energistics-2#1324]
My Game crash when I want to join an server or to create a world.
Crash Report
http://openeye.openmods.info/crashes/175c61a7fb8f2c05e8bcd1fef5903d0c

**Comment by copygirl** [comment]
The BetterStorage version you're using is ancient, I suggest to update.

For the devs: The crate API was updated in 0.10 and the version being used here is 0.9.
https://github.com/copygirl/BetterStorage/commit/f1659e1ffe15303bc624dd71ca19b9c05bb2e84d

**Comment by thatsIch** [comment]
Thus closing, thanks for clarification @copygirl
