### ISSUE TITLE
Channels should not be behaving like this

### ISSUE THREAD

**Issue by Stumblebuffin** [AppliedEnergistics/Applied-Energistics-2#1325]
http://imgur.com/zrylyKd,acePOJd,R4QY6m4,txJW9ml,NIG4xwV,vusETNG,KcOzP3Q,zays2HH#0

when i hook up another p2p channels disappear from the first one. 
even on the first one i wanted to run it 8 long with 8 level emitters, 8 import and 8 export. each on their own glass cable line running into dense cable but the channels wouldn't let me

**Comment by thatsIch** [comment]
What is on the other side of the P2P Bus?

**Comment by Stumblebuffin** [comment]
Glass cable with 5 other p2p and 1 p2p directly on the controller

**Comment by thatsIch** [comment]
Have you read the bottom part of this article?
http://ae-mod.info/Channels/

sounds like this will solve your issue.

**Comment by Stumblebuffin** [comment]
hmm but i dont see how that would relate to two separate p2p systems. (although it may solve some problems elsewhere)

**Comment by thatsIch** [comment]
Please upload a world with only AE2 installed with a reproduction of your behaviour

**Comment by Stumblebuffin** [comment]
ok i tried i really did. but after a lot of time trying to figure out ho to launch ae2 by itself etc etc. frustrations... this is the simplest thing i did and ran into a problem 

http://imgur.com/a/ZxaF0

i was not able to fully isolate ae2 i used the ftb launcher and dissabled all other packs but it still left me with "minecraft coder pack" "forge mod loader" "minecraft forge" "bspkrs core"

anyways in the pictures u can see channels on import bus's flickering on the far left first 2, then if i remove the cpu's on the righ just 1. again p2p on controller connected to a few p2p's on glass cable. 
i give up for now. let me know if u have any more questions or solutions. or are just unable to recreate the problem.

**Comment by yueh** [comment]
I am pretty sure that these are working as intended.

You did read the page about P2P tunnels and that they transfer 32 at max and share it them with every output?

**Comment by Stumblebuffin** [comment]
Well for the last image there is less than 32.... but oh... for some reason I thought u could connect 31 p2p terminals to one and have 31p2p × 31channels  (31-1 for the p2p?) going to 1 p2p into the controller.

**Comment by yueh** [comment]
You can link basically infinite P2P tunnels with the same input, you will just share 32 channels with infinite tunnels.

No idea about the last screens, but it is nearly impossible to recognize something (too small/bad image quality). But you loop the cables around, so there might be shorter paths to distribute the channels.
Your best option is to read the channel page and traverse the cables basically with pen and paper.
Removing one device using channels (the crafting cpus), thus gaining a new channel for the bus on the left basically means the channels were fully utilize.

I cannot remember anyone being able to really provide an example with a bug. It was always an issue with the actual network built by the player.
