### ISSUE TITLE
Ability to get Crafting Unit and Storage Component back from Crafting Storage

### ISSUE THREAD

**Issue by Drethic** [AppliedEnergistics/Applied-Energistics-2#1326]
I would like the ability to remove the Storage Component from the Crafting Storage with shift+right-click like you can with the Storage Cells.  It should return the Crafting Unit and the Crafting Component so you can upgrade them.

**Comment by BB20101997** [comment]
if you put the Crafting Storage in a grafting grid you get a 1k Storage component back.Is it a bug that it is always a 1k Storage Component despite the size of the Crafting storage?

**Comment by thatsIch** [comment]
@BB20101997 yes apparently it is a bug. I created this issue regarding that https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1465
