### ISSUE TITLE
Player disconnected with ClassCastException

### ISSUE THREAD

**Issue by ams2990** [AppliedEnergistics/Applied-Energistics-2#1327]
The log [is here](http://pastebin.com/raw.php?i=gyEMWxm0). Unfortunately, I don't know what happened to cause this. I'm on Cauldron build 1343 and AE2 rv2 beta 28.

**Comment by thatsIch** [comment]
This normally does not happen in a Forge Environment, generally Cauldron messes Forge up quite a bit.

**Comment by ams2990** [comment]
Thanks for the quick fix!
