### ISSUE TITLE
crash when looking up the teleport tether from additional pipes after recipe has been removed with Minetweaker Recipemaker

### ISSUE THREAD

**Issue by Sailren** [AppliedEnergistics/Applied-Energistics-2#1329]
a note: fastcraft is installed if this important for you

crash report is here: http://paste.ubuntu.com/10890359/

@thatsIch haste den fehler schon mal gesehen oder ist es was anderes?

used version is rv2-beta-29

used forge version is Forge{10.13.3.1395}

**Comment by thatsIch** [comment]
Something is modifying the recipe list (removing an element) while NEI is iterating over it, which is bad. 
This is probably due to the removal of _some_(?) recipe. I have yet to seen this issue, so I do not really know, how this is happening. 

I am currently rewriting the recipe API, which might resolve this issue, but does not prevent MineTweaker and other hacks from fucking around with mods.

**Comment by Sailren** [comment]
well, i used a minetweaker script from DreammasterXXL, used together with gregtech to modify other mod recipes to match gregs mod

**Comment by yueh** [comment]
I do not see anything in our code which can actually cause a CME.
It is probably randomly triggered in AE2, but it could really affect any other mod.

I personally would see this as minetweaker (recipemaker) issue. Minecraft does not really expect that recipes get removed at runtime. There is not even a method to remove them, only add.
So if they do it, they should also account for the issues they are possible causing.

**Comment by Sailren** [comment]
so you guess it is the script doing it? need to tell dreammaster about this

**Comment by yueh** [comment]
I do not think that the script is actually causing it. These should just be run once during the initialization.

Something is adding or removing recipes after the initalization. This could be for example the recipemaker directly injecting the recipe at runtime, or maybe additional pipes trying to clean up some stuff, or a a completely different mod.
