### ISSUE TITLE
Arcane Stone Block Facade

### ISSUE THREAD

**Issue by MassiveNetwork** [AppliedEnergistics/Applied-Energistics-2#1330]
Adding Regular Arcane stone block (From the mod Thaumcraft) to this list of viable facades.

**Comment by thatsIch** [comment]
If that block is a valid block, it will automatically register. So there must be something about it, which does not match the facade system.

**Comment by XFactHD** [comment]
What could be the problem? The standard arcane block doesn't have any features like warded or whatever.

**Comment by yueh** [comment]
Unknown.

It might still work and you can manually add/enable it in `Facades.cfg`.
Or maybe not, thus we disable it by default instead of causing issues for every user.
But each user has still the option to manually try it, but then do not blame us for ignoring our recommendations.
