### ISSUE TITLE
Crashed game, then disable some features of mod

### ISSUE THREAD

**Issue by linkinkov** [AppliedEnergistics/Applied-Energistics-2#1331]
Then i use that config:
http://paste.ubuntu.com/10892145/

Game crash:
http://paste.ubuntu.com/10892142/

Also using mod to remove some recipes, mod name CustomConfig.

**Comment by linkinkov** [comment]
Its will be soon merged in rv2?

**Comment by thatsIch** [comment]
Depends on the review

**Comment by thatsIch** [comment]
if you cant wait, you can use the file from the build server

**Comment by thatsIch** [comment]
http://goo.gl/VDnu4W

**Comment by linkinkov** [comment]
Thank you!
