### ISSUE TITLE
'sort by priority' in ME Terminal

### ISSUE THREAD

**Issue by kk2020** [AppliedEnergistics/Applied-Energistics-2#1338]
Would it be possible to enable ME Terminal item sorting by drive priority, as in ae1?

**Comment by yueh** [comment]
Is this even possible? The sorting is purely done on the client, which should have no information about the priority.

**Comment by kk2020** [comment]
I haven't got a clue I'm afraid, just noticed I couldn't sort items by drive bay priority in this version so thought I'd mention it. Used that method in previous versions so I could easily see which items in the ME system didn't have their own drives - ie 'loose' stuff at the bottom of the list. I'm sure i can work around it with a separate network for formatted drives tho, if its not possible.

**Comment by Xajar** [comment]
I really miss that feature as well. In AE1 I had all my drive bays priorities set in the order I wanted them viewed in the terminal. View cells just aren't as good as priority sorted inventories in AE1.

**Comment by chorman0773** [comment]
It could be possible to send the client drive priority data, each tick while viewing a AE Terminal. Then the sorting could apply.
