### ISSUE TITLE
Tooltip of the Matter Condenser might be misleading

### ISSUE THREAD

**Issue by thatsIch** [AppliedEnergistics/Applied-Energistics-2#1345]
http://prntscr.com/6yvlbr

the tooltip suggest something about energy, where people might think, that this is related to RF or EU
Renaming to **Matter** might fix this?

**Comment by yueh** [comment]
For AE2 itself, it is actually the correct term as it converts matter into energy and stores it. (until it is enough to create a matter ball/singularity)

Renaming it to **Matter** might make it less confusing for some users.
But could it confuse others about what is matter and does it only accept matter balls and how to obtain matter balls as NEI reports no recipe?

**Comment by Blue64** [comment]
On a related note, mixing Matter Balls with Glowstone Dust supplies a glowing variety not shown in NEI, to compound it worse, I see no recoloration options from NEI once it's become one of the 16 versions of Fluix Matter Balls that glow, though the 16 colors and their glowing variants are displayed in NEI (only recipes are Glowstone Dust + 8 non-glow variants to make the different glowing Fluix, not different colors of Fluix, just the Fluix color, with 16 different stack Meta numbers)

**Comment by XFactHD** [comment]
Those glowing paint balls currently have no use, they might have been intended to make glowing cables.

**Comment by Blue64** [comment]
Ah, thanks for the heads up. I figured it was going to act similar to Quiver Bow's sticky Glowstone myself, but colored. This saves me some redoing of my recipes. I might still add them to the Dye OreDict though.

Has it been posted as a feature request to further that crafting/usage anywhere though?

**Comment by thatsIch** [comment]
You were supposed to shoot them.
