### ISSUE TITLE
Crafting with recipes that use FMP blocks in them doesn't work.

### ISSUE THREAD

**Issue by chrisk123999** [AppliedEnergistics/Applied-Energistics-2#1346]
Attempting to use auto-crafting with recipes that call for FMP blocks doesn't seem to be working.  This is mainly an issue for trying to auto-craft with Project: Red.

https://dl.dropboxusercontent.com/u/1455347/Minecraft/2015-04-28_05.57.00.png
https://dl.dropboxusercontent.com/u/1455347/Minecraft/2015-04-28_05.57.18.png
https://dl.dropboxusercontent.com/u/1455347/Minecraft/2015-04-28_05.57.58.png
https://dl.dropboxusercontent.com/u/1455347/Minecraft/2015-04-28_05.58.31.png

AE2 Version: appliedenergistics2-rv2-beta-30
Forge Version: 10.13.3.1385

**Comment by yueh** [comment]
I have no issues crafting strips from full blocks (including the panels/slabs).

Are you sure that you are using the correct patterns?
The 3rd screenshot basically indicates you are missing the patterns to craft panels.

**Comment by chrisk123999** [comment]
The system is setup to auto-craft the parts, but it won't work for the Draw plate it seems...

https://dl.dropboxusercontent.com/u/1455347/Minecraft/2015-04-28_14.59.17.png
https://dl.dropboxusercontent.com/u/1455347/Minecraft/2015-04-28_14.59.32.png

**Comment by yueh** [comment]
How did you create the pattern for it? Because I cannot even craft the draw plate in a vanilla crafting table.

**Comment by chrisk123999** [comment]
Ah, that would be it then.  I was just mindlessly using the AE2Stuff mod's Pattern encoder to get my encoded patterns.  Seems this is most likely a Project Red issue then.  Most likely the item doesn't have any use.  Sorry for wasting your time.

**Comment by yueh** [comment]
The pattern encoder from AE2Stuff will never give you a valid pattern (or at least a pretty low chance for a valid one)
