### ISSUE TITLE
API for Condenser

### ISSUE THREAD

**Issue by thatsIch** [AppliedEnergistics/Applied-Energistics-2#1351]
There is currently no way for people to add their own results to the matter condenser (especially since addons like ExtraCells add their own storage components, which could lead to a different result?)

Because of that, maybe we need to remove the button and just determine the result through the storage component?

**Comment by yueh** [comment]
An API might be an idea, but it would be fairly limited. Basically just a map int to ItemStack.

The button might be a bit difficult as it would need to display any ItemStack. Probably needing a GUI refactoring.

But making the results depending on the storage size is not really ideal and probably confusing when different cells produce different items without any clear (ingame) documentation. Trying every valid component is not an option.

Players also will no longer be able to store energy before deciding if they want matter balls or singularities. Changing the storage component will even void everything, but necessary to choose the a different product.

**Comment by Technici4n** [comment]
If an addon developer wants to discuss this feature with us, come on Discord! Otherwise, it is not going to happen if nobody needs it.
