### ISSUE TITLE
AE2 rv2 beta 29 refuses Ender IO Conduits / thermal expansion, more?

### ISSUE THREAD

**Issue by JustABunchOfPillows** [AppliedEnergistics/Applied-Energistics-2#1353]
So i tested charger, me controller, power acceptor (not sure if thats the name). and it just directly refuses to accept power from either capacitor bank, ender io conduit, stirling generators, lead energy cell.. Thats what i had by hand when testing and it just directly said nope. can't do.. so i looked around for something config specific and nothing showed up anywhere to "disallow" it. so i assume something changed in the newest version to make this happend.

It may be refusing more than that. but so far thats the only things i've "seen" it refuse.

**Comment by JustABunchOfPillows** [comment]
just to be 100% sure of what i said above. i just started a single player world with forge 1352, doesn't seem to work at all. i have no error logs on this neither. so theres really only my word to go on.

**Comment by thatsIch** [comment]
Works fine for me

![2015-04-29_18 46 07](https://cloud.githubusercontent.com/assets/2210496/7396257/08b889d6-eea0-11e4-944e-95ba17e28691.png)

**Comment by JustABunchOfPillows** [comment]
I will upload a few pictures in a few... (i've checked any possible config and theres nothing there to change for it of what i could see..). out of curiosity what version of forge, what version of enderio, what version of ae2?

I'm currently using forge 1352, enderio 2.2.8.367, ae2-rv2-beta-29

**Comment by JustABunchOfPillows** [comment]
so i did something with ender io / thermal.. (tessaract and transceiver are connected to creative source from both) 
http://puu.sh/hw26l/e51446a870.jpg

**Comment by JustABunchOfPillows** [comment]
just checked extra uitilities generator aswell.  doesn't seem to work on it either.

**Comment by thatsIch** [comment]
Using Forge 10.13.2.1291
EnderIO 2.3.0.375_beta
AE2 rv2 beta31

**Comment by thatsIch** [comment]
You can see the used APIs in here and their version
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv2/gradle.properties

**Comment by JustABunchOfPillows** [comment]
i don't really know what i'm looking at there.. but i could see extra uitilities, enderio and thermal expansion isn't there D: .. not sure if that's good or bad o__o

**Comment by thatsIch** [comment]
That means we dont rely on TET or XU or EnderIO but only on the RF API, so if that updated e.g. then stuff matters, but obviously I run it with the latest version of EnderIO run, so nothing wrong with the RF API. 

So I suggest you to update **all** of your RF Mods, cause when they ship the RF API, they could potentially destroy interactions.

**Comment by JustABunchOfPillows** [comment]
well apparently it was ae2 modintegration area which seemed to cause it.. it was returned to default (and of what i could see. a few modintegration was removed?).

nevertheless that fixed it <.<.... Sorry for any trouble this may have caused and thank you for your assistance on it so far

Keep up the good work
