### ISSUE TITLE
Recipes Disappearing

### ISSUE THREAD

**Issue by gamernick42** [AppliedEnergistics/Applied-Energistics-2#1354]
I loaded up a world after updating many mod. Strangely, all of AE2's recipes became invalid, but other mods were fine. I could not find the recipes in NEI and I could not craft any of them.

**Comment by thatsIch** [comment]
need more information?

**Comment by aurumvorax** [comment]
I've been having this issue as well.  It's not actually ALL AE2 recipes, but most of them.  Charger, inscriber, ME controller, basically any machine, is not working.  NEI shows the item, but does not show the recipe, and the item cannot be crafted.  Other things like fluis blocks, the grindstone, quartz pillars, are unaffected

**Comment by Dream-Master** [comment]
Some machines you can switch off via config i think.

**Comment by aurumvorax** [comment]
I've regenerated all configs, problem persists.

**Comment by thatsIch** [comment]
If you run old AE2 update it, 
especially if you run Mekanism,
there are like 5 issues reported here already regarding that.

Also please always try to use the latest version of AE2,
since we can only fix stuff, which is not already fixed.
