### ISSUE TITLE
Autocrafted items stuck in interfaces

### ISSUE THREAD

**Issue by Armigus** [AppliedEnergistics/Applied-Energistics-2#1355]
My autocrafting system does all but one thing: return the results to the AE system.
![Uploading AE Storage.png…]()
Here is the storage system, a modified SSD.  It's on a bidirectional subnet (two connections, one interface->storage bus and the other reversed).

![Uploading Crafting CPUs.png…]()
Because the product does not get returned to the system, crafting CPU's never get the "finished" notification and clog up.

![Uploading MAC Cells.png…]()
This cube system, with interfaces at the corners and assemblers at the edges, crafts even intricate items like 64K storage cells very well but can't return completed items to storage.

I'm using the version with DW20 1.2.1 for 1.7, rv2-beta-pre9, on a server that is reluctant to update without a full pack update.

Is this a legitimate bug or a design error on my part?

**Comment by thatsIch** [comment]
Images missing? Or is it just me?

**Comment by sci4me** [comment]
They're missing for me too
