### ISSUE TITLE
Stop using System.currentTimeMillis() for time comparisons

### ISSUE THREAD

**Issue by Techjar** [AppliedEnergistics/Applied-Energistics-2#1357]
This is a very bad idea as things can go wonky if the system time changes, which can and does happen (think system clock resync). You should be using System.nanoTime() when you only need to compare a difference in time. It provides nanosecond resolution, but not necessarily nanosecond precision. It does, however, guarantee constant time. It will only ever go forward and "1 second" is always exactly 1 second.

Here is a list of files containing some usage of System.currentTimeMillis(). ~~I haven't checked which ones are using it for absolute time and which are using it for comparisons, I only grep'ed the AE2 files to find these.~~ I have checked them all and reduced the list to only the ones which are actually problematic. Most of them wouldn't cause an issue beyond some funny rendering, but a couple could cause actual issues under certain circumstances.

```appeng/client/render/blocks/RenderBlockInscriber.java:178
appeng/client/render/blocks/RenderBlockSkyChest.java:110
appeng/client/render/blocks/RenderBlockSkyCompass.java:99
appeng/client/render/blocks/RenderBlockSkyCompass.java:188
appeng/client/render/SpatialSkyRender.java:57
appeng/hooks/CompassManager.java:43
appeng/parts/p2p/PartP2PTunnel.java:383
appeng/tile/misc/TileInscriber.java:146
appeng/tile/storage/TileSkyChest.java:60
```

**Comment by thatsIch** [comment]
where is the promised PR!

**Comment by Techjar** [comment]
Soon™

**Comment by TheJulianJES** [comment]
Still not there...
