### ISSUE TITLE
Right-clicking/shift-right-clicking an AEPart

### ISSUE THREAD

**Issue by AfterWind** [AppliedEnergistics/Applied-Energistics-2#1361]
I have a problem with event cancelling, but I only need the answer to this question:
Where is the code executed when placing a new AEPart on an existing one and where is the code executed when wrenching (removing) an AEPart from a block that will still have at least one AEPart in it after wrenching it?

**Comment by thatsIch** [comment]
* ff https://github.com/thatsIch/Applied-Energistics-2/blob/rv2/src/main/java/appeng/parts/PartPlacement.java#L155-155
* https://github.com/thatsIch/Applied-Energistics-2/blob/rv2/src/main/java/appeng/block/AEBaseBlock.java#L470-470
