### ISSUE TITLE
All cables, including buses and facades, are now "AE2 cable and/or Bus"

### ISSUE THREAD

**Issue by Nikkolino99** [AppliedEnergistics/Applied-Energistics-2#1362]
I discovered that with rv2 beta build 30 all my cables are now "AE2 cable and/or bus", so now I can't see how many channels are available on my dense cable that maintain my crafting network.
Some Images
![2015-04-29_22 04 33](https://cloud.githubusercontent.com/assets/7397855/7400555/1736ad58-eebe-11e4-8bd9-38786f7810b6.png)
![2015-04-29_22 04 36](https://cloud.githubusercontent.com/assets/7397855/7400556/173a32d4-eebe-11e4-9387-0f9292743f64.png)
![2015-04-29_22 04 40](https://cloud.githubusercontent.com/assets/7397855/7400557/173df324-eebe-11e4-8d73-fb696914ca25.png)

I don't know if this help, I have installed thaumic energistics

**Comment by yueh** [comment]
This only affects block/part names. Other data like channels/power are still working correctly.

**Comment by yueh** [comment]
This is actually a waila bug as they are using a deprecated method `Block.getPickBlock(MovingObjectPosition target, World world, int x, int y, int z)`, which we no longer support.

**Comment by Nikkolino99** [comment]
OK, thank you, so I should update waila?
Il 30/apr/2015 17:24, "yueh" <notifications@github.com> ha scritto:

**Comment by yueh** [comment]
It seems that Waila is reluctant to update because of an alleged backward compatibility.
Forge does just forward the new method to the old one be default, so this is actually not an issue and would only provide benefits for mods.

**Comment by TheJulianJES** [comment]
Why not call getPickBlock with player null from the old method as a temp fix?

**Comment by TheJulianJES** [comment]
Also, why just not use the old method for the multiparts, since the new one calls the old method until WAILA updates? @yueh
