### ISSUE TITLE
Crash of AE2RV2 build 30 & 31 in combination with Advanced Solar Panels v3.5.1

### ISSUE THREAD

**Issue by walkerjonny** [AppliedEnergistics/Applied-Energistics-2#1364]
Hi, there is an issue with AE2 RV2 builds 30 & 31 in combination with ASP v3.5.1 causing a crash.
Maybe you can fix it.

http://pastebin.com/vhrQuym2

**Comment by yueh** [comment]
Advanced solars is trying to interprete one of our cables as its own machine.
No idea why, but it seems there is a TileEntity lingering in the same location as the ASP machine.

Currently I would assume either a corrupt chunk or some of "performance enhancing" mods are causing issues as usually. So you should try it without Optifine and similar mods. Probably even cut unrelated mods as they could also cause it.

And for the future, please do not spam the tracker with the crashlog. Post it on pastebin or similar.
