### ISSUE TITLE
AutoCraft work only with Wireless Terminal

### ISSUE THREAD

**Issue by linkinkov** [AppliedEnergistics/Applied-Energistics-2#1365]
This problem was started after rv2 alfa 28. Then we click on craft in ME terminal, nothing to do, but from ME Wireless Terminal work propertly.

**Comment by thatsIch** [comment]
Cant reproduce, both work fine for me. Please try to reproduce in a new small new world with a minimal setup.

**Comment by linkinkov** [comment]
Its happens only on server, in single mode work well.

**Comment by thatsIch** [comment]
Try updating your server to the latest version of AE2

**Comment by thatsIch** [comment]
inactive
