### ISSUE TITLE
Channels is still kind of activated when you turn them off in config.

### ISSUE THREAD

**Issue by fresser** [AppliedEnergistics/Applied-Energistics-2#1369]
Hi.

Was playing on my local server with channels deactivated (boring me, haha) So when i went above ~820 devices on the network, it went offline and said "Device Missing Channel". I tried removing one interface, and it worked again, placing anything requiring a channel, turned the whole system offline.

I tried in singleplayer too, same thing happens, but with a different amount of devices. ~800 but with 350 devices that needed a channel.

I am running AE2-Beta30 on ftb infinity.

**Comment by thatsIch** [comment]
Are you actually missing a channel (most devices have an indicator if they are active or not), or just WAILA trolling you?

**Comment by fresser** [comment]
The whole network is offline, and waila says "Device Missing Channel". Is there a way to tell if there is a reason for this, or if it's actually a bug?

No matter what, i don't think i should ever get the message "Missing Channel" when channels is turned off. :)

**Comment by thatsIch** [comment]
Your whole network is offline? Please post a screen of state before and after.

Wrong messages are another issue.

**Comment by fresser** [comment]
Screen of state?
I've uploaded 4 images to imgur
http://imgur.com/YvXws4F,yPfQuB2,jjXSFDG,n5YxuRU
first 2 it works fine, the next 2 i place one more interface and it's offline.

I notice though, the drives are online, but all terminals are offline, even the wireless ones.

**Comment by thatsIch** [comment]
Sounds more like a power issue to me, do you per change have not enough energy buffer (sufficient AE2 energy cells)?

**Comment by thatsIch** [comment]
Also please use the default texture pack next time for screenshots. I basically can not see any difference in off and on behavior with a non-default TP applied.

**Comment by yueh** [comment]
Also keep in mind that it does not actually disable channels, but technically allows infinite channels.
Thus it will still need to initialize the network and recurring power issues or chunk unloading will force the network to rebuild. While it is doing it, there can still be devices without channels.

**Comment by thatsIch** [comment]
Maybe we should call it infinite channels

**Comment by vallard192** [comment]
That might make a lot of sense...  I haven't tested, but (using fancy new
terminology) if you turn on infinite channels, can you set up a equal
length route that ends up with devices offline since there are multiple
paths to it? (As described on http://ae-mod.info/Channels/)

If so infinite channels is probably a much better way to describe it since
there are still channel-like limitations to network design.

**Comment by fresser** [comment]
I have 12 dense energy cells hooked up. I just tried hooking 8 more up, no difference what so ever, they are all fully charged according to wailo (other ways to see if they are charged?)

@vallard192 
Shouldn't make any difference, since there is no controller either. There is no place the cable is going from, so in my head it wouldn't make sense there is such limitations?

you cannot tell any difference if the terminals are online or offline visually. Even with default tp.

**Comment by vallard192** [comment]
Can you try a creative cell? Someone had the issue below a couple weeks
ago...I'm hoping I summarize it well.

On large networks is possible to go from "large and sufficient generator"
-> "power storage" -> AE network

However if your power srorages hold less power than your network pulls each
tick, then your network will still have power issues. Even though your
generator makes more than enough power.

Using made up numbers...

If you generate 200 power a tick, but only have power storage for 50, any
network that needs more than 50 at some point may have issues because the
AE network won't receive more power than your STORAGE can put out...it can
depend on your power design...but a creative cell would be an easy way to
test.

**Comment by fresser** [comment]
Hmn. I tried a creative cell. Same issue.

And yes, i understand, and it took me a while figuring out. (Have been there, when the network was offline for some weird reason xD)

**Comment by fresser** [comment]
Sorry if this stresses you. Just wanted to say, i have not had luck to fix this issue. I've tried with multiple cables attached on the Energy Acceptor, which is the closest we get to a controller on this network.. 

Energy Cells doesn't affect anything, and the network has plenty of charge. (full)

Can i enable some debug thing, that may output why it deactivates the terminals? The drives are still online, although every automatic process in the system is on halt.

**Comment by XFactHD** [comment]
Controller? How can you have a controller with channels turned off?

**Comment by fresser** [comment]
I do not have a controller. I have a Energy Acceptor, which i think is the closest to a controller we'll get. But probably has nothing to do with it though. Worth a shot at least :)

**Comment by ClintonFlowers** [comment]
I'm having the same issue. If I add devices, it shuts off. 
Everything on, working mostly fine: http://i.imgur.com/q2vp0A9.png
+1 assembler, everything turns off: http://i.imgur.com/1nDUdHf.png 
(Energy cells on the right to show that it's full.)

**Comment by Lyokomzm** [comment]
Also having this issue on my server. Channels are disabled, and we have tried everything that was mentioned prior, (creative energy cell, more energy acceptors). If you need any configs, images or logs from us just ask, will gladly provide them.

**Comment by thatsIch** [comment]
We might need to remove/disable the "infinite channels" flag again, if this creates so many untraceable problems..

**Comment by thatsIch** [comment]
Closing this in favor of https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1510
