### ISSUE TITLE
meteorite compass

### ISSUE THREAD

**Issue by wandersonbraz** [AppliedEnergistics/Applied-Energistics-2#1370]
good night

recently installed appliedenergistics2-RV1-stable-1 then started a new world and went to do the Meteorite compass and had a surprise craft works not coming into creative can take the compass usually tried with four irons and 1 certuz quartz charged.

there is some modification in the mod and the compass was changed?

forge 10.13.3.1395
mod appliedenergistics2-RV1-stable-1

**Comment by cleverca22** [comment]
do you also have mekanism?, there is a comparability issue with it on certain versions

**Comment by wandersonbraz** [comment]
Yes on latest version

**Comment by wandersonbraz** [comment]
The recipe does not appear in the NEI and can not crafting putting the materials in crafttable

**Comment by thatsIch** [comment]
Update AE2

**Comment by wandersonbraz** [comment]
Sorry but which version should I use for the ae2 I took that seemed to be the last site

**Comment by thatsIch** [comment]
http://minecraft.curseforge.com/mc-mods/223794-applied-energistics-2/files

this page will show you the latest by date
