### ISSUE TITLE
AE2 rv2.beta build 31 Crashes with noSuchMethod

### ISSUE THREAD

**Issue by PendeBro** [AppliedEnergistics/Applied-Energistics-2#1374]
Applied energistics crashes on launch giving a: java.lang.NoSuchMethodError

ive tried downgrading as far as rv2 build 22 but i get the same crash.

Pastebin error:
http://pastebin.com/fEhfPw81

**Comment by zevipa** [comment]
You may want to try downgrading to Java 7.

**Comment by PendeBro** [comment]
I actually found the error. It was thaumic tinkerer. I'm also using thaumic energistics, and my guess is thaumic tinkerer added an aspect that wasn't working with thaumic energistics, and it was reported as an ae2 crash. Anyway updating thaumic tinkerer fixed it

**Comment by thatsIch** [comment]
Its actually Thaumic Energistics not up to date

**Comment by h404bi** [comment]
Thank you, PendeBro. It works after removing thaumic tinkerer. :thumbsup:
