### ISSUE TITLE
Periodic Import Slowdown from Ender Chest

### ISSUE THREAD

**Issue by Selway00** [AppliedEnergistics/Applied-Energistics-2#1375]
Hey there,

LOVE your mod thank you so friggin much for it!

Ok so I am having periodic importation of items from ender chests slow down or stop.  I am playing a sinlge player Skyfactory 2.3, Applied Energistics: RV2-Beta 6 to RV2-Beta 14.  Tps is usually around 5.  FPS is usually above 100.   

I am using aprox. 400 channels, most of which are routed through P2P Tunnels.  There is a lot of stuff being dumped into ender chests so that they can fill up in a matter of 2-5 seconds with lots of different items.   Most of the time AE imports like a boss.  I can barely see them enter before they are ripped into the ME system.  However, every minute or so, it slows down and even stops sometimes causing the system to back up.  Then AE will slowly start accelerating its importation and catches up again.  

I have tried multiple ender chests of the same color code each with six fully accelerated import buses.  I have tried splitting the intakes among multiple different color coded ender chests but this does not seem to help.  It seems to provides a bigger buffer for import slow downs but the slow downs are still happening.

I have double and tripple checked my system for any channel conflicts and I have not found any.  There is also no loss of power or resetting of the system.  I have plenty of dense energy cells and power.

Is there a limit to how much or how many different items AE2 can import consistently?  Are there slow downs?  Could this be an ender chest API limitation?  If so, why does AE import so well for 45 seconds, or so, then completely stop and have to accelerate all over again?  Will a log help?

My system: 
i7-4790 proc
16gm ram
Nvidia GTX 980 factory overclocked
Dedicated SSHD with 100gigs free 

Thank you!

**Comment by thatsIch** [comment]
This is an intended optimization. All buses regulate their own speed depending on how much work they are doing. If you give them less work over a longer period of time, they will sleep, until somebody wakes them up or they exceed their regular check up.

If you want constant import, use ME Interfaces and Tesseracts. 

Also a TPS of 5 is not really good, it is meant to be 20.

**Comment by Selway00** [comment]
Ok thanks!   I don't understand why the import busses would slow down on my system since its consistently being filled very quickly.  But I'll just switch over to the tesseract/interface method.

**Comment by thatsIch** [comment]
You are welcome!
