### ISSUE TITLE
Update from rv0 1.7.10 to rv2 1.7.10

### ISSUE THREAD

**Issue by DjSapsan** [AppliedEnergistics/Applied-Energistics-2#1377]
Sorry, i'm very bad know english.
I'm played with AE 1.7.10 rv0. Today i open website and saw new version. I was download rv2.beta build 31 and make correct install of mod. When i create the new world, world created, but when i place any block from this mod - crash. How i can update to new version?
Sorry for my english =(

**Comment by thatsIch** [comment]
Post the crash

**Comment by linkinkov** [comment]
Just need remove old config file

**Comment by thatsIch** [comment]
Also a possibility, 

closing due to lack of feedback

**Comment by DjSapsan** [comment]
Олег, не помогает )
08.05.2015 19:39 пользователь "Oleg" <notifications@github.com> написал:

**Comment by thatsIch** [comment]
Try it with english

**Comment by DjSapsan** [comment]
Deleting config don't help

**Comment by thatsIch** [comment]
you still need to post the crashlog

**Comment by DjSapsan** [comment]
http://pastebin.com/GksEr0TA

**Comment by thatsIch** [comment]
You need to update Buildcraft
