### ISSUE TITLE
Slabs 

### ISSUE THREAD

**Issue by Yulife** [AppliedEnergistics/Applied-Energistics-2#1379]
Slab variants for the decorative blocks in AE2 would be brilliant, especially the Sky Stone variant. Right now we've just got stairs so slabs would be very neat ~ :smile: 
Thanks in advance

**Comment by plumpudding** [comment]
You can assign me, I'd try to do that

**Comment by thatsIch** [comment]
You can not assign people outside of the organisation

**Comment by plumpudding** [comment]
:O didn't know that. 
So do we have some kind of ReflectionHelper util?

**Comment by thatsIch** [comment]
like the Forge `ReflectionHelper`?

**Comment by plumpudding** [comment]
Forge has one? I'll try that one

**Comment by plumpudding** [comment]
Very little progress but that's what I've done until now: https://github.com/AppliedEnergistics/Applied-Energistics-2/commit/ac076577668299b65fd6970c203ad3cce14e11e4

**Comment by thatsIch** [comment]
nice, the worst part comes, when you need to handle the merging of the slabs upon double place.

**Comment by yueh** [comment]
The properties of slabs should probably be handle inside the slabs and not set through the `IFeatureHandler`.

**Comment by plumpudding** [comment]
@yueh better? https://github.com/AppliedEnergistics/Applied-Energistics-2/compare/master...plumpudding:rv2?diff=unified&name=rv2

**Comment by plumpudding** [comment]
Houston, we have a problem

getting double slabs up and running is not very difficult either, ***but*** we need an ItemBlock which requires the Block to be constructed before the Items are. How would you do that? I'm not very familiar with the AE Api code..

**Comment by thatsIch** [comment]
There should be an `AEBaseItemBlock` which accepts a `Block`.
You probably should extend that class and use that as a return type of the DoubleBlock

FMP is not AE
