### ISSUE TITLE
[A Bug?]Can place ME * Cable under the player

### ISSUE THREAD

**Issue by Blealtan** [AppliedEnergistics/Applied-Energistics-2#1383]
I found that it's possible to place any kind of ME cable directly below the player, showed in the two pics.
![2015-05-03_11 02 13](https://cloud.githubusercontent.com/assets/6376623/7443522/59e37faa-f184-11e4-8a71-614ba6950889.png)
![2015-05-03_11 05 43](https://cloud.githubusercontent.com/assets/6376623/7443525/800d271c-f184-11e4-873d-1f996c49d17b.png)
Is this a bug?
(In fact it is the same for the pipe in BuildCraft6...But what made me think it is a bug is that in IC2exp, the cable is ok.)

**Comment by Entoarox** [comment]
the multipart placement code is simply not checking for the player hitbox the way blocks do, it is a problem with a lot of mod items it seems.

**Comment by TheJulianJES** [comment]
You can also place it in yourself...

**Comment by thatsIch** [comment]
lets call it a feature *whistles*

**Comment by TheJulianJES** [comment]
Well, I would more consider this as a bug :P

**Comment by yueh** [comment]
Vanilla has the same issue, even with full blocks in some cases.

**Comment by TheJulianJES** [comment]
With what full blocks?

**Comment by Entoarox** [comment]
Well, you are *obviously* mistaken, after all, its the most awesome feature in AE2, such a thing can *never* be a *bug*.... :laughing:

**Comment by TheJulianJES** [comment]
:D
Also @yueh vanilla has it chests/furnaces facing to the right, AE2 to the left :P

**Comment by Blealtan** [comment]
I can accept it as a surprise... But I prefer that we CANNOT live  IN a block..

**Comment by TheJulianJES** [comment]
Yeah, you can not just place it under you. You can also place it in yourself.

**Comment by TheJulianJES** [comment]
This may help: https://github.com/OpenMods/OpenBlocks/commit/100d9d812e74c8c9cbbf93d6075a1567813081ea

**Comment by thatsIch** [comment]
Not really xD

we have a totally different placement logic

**Comment by thatsIch** [comment]
Just asking, but is this just a bother for cables, or all parts?

**Comment by Entoarox** [comment]
@thatsIch Just tested it with a export bus, placement of that also happened even when it should not have, so I'd have to guess it is the same for all parts.

**Comment by thatsIch** [comment]
I did not ask if it is not working for parts, but if parts are also a bother

BC pipes e.g. do not have a hitbox collision on placing too
