### ISSUE TITLE
Import bus not pulling items from inscriber?

### ISSUE THREAD

**Issue by Aevaris** [AppliedEnergistics/Applied-Energistics-2#1385]
Hello,

I tried to google around to see if this was user error or a bug and couldn't find evidence it is user error (although not saying it isn't). This is in rv2b32,

I can't seem to pull items out of my inscriber once they've been crafted.

My setup:
![javaw 2015-05-03 09-35-37-46](https://cloud.githubusercontent.com/assets/9640671/7445422/efd94cd6-f177-11e4-9420-3423bf5a6055.jpg)

You can see channels and power are fine.

But items still in inventory:
![javaw 2015-05-03 09-35-47-06](https://cloud.githubusercontent.com/assets/9640671/7445426/1cc0a41a-f178-11e4-8bab-8c8a2b8c8b08.jpg)

Is there something I am doing wrong or is this a bug?

Edit: I think this is a bug. I rolled back to rv30 and this does not occur.

**Comment by thatsIch** [comment]
mh can you reproduce this in a fresh single player world?

**Comment by Aevaris** [comment]
Disregard. This likely was user error of some variety. Details below:
- Tried fresh world, no problems.
- Tried existing world again, now no problems.

Not sure what the problem was. It may have been storage related (my drives are pretty small currently), but I don't think all of them were full.

*shrug* issue is no longer occurring. Sorry for the trouble. :/

**Comment by TheJulianJES** [comment]
Maybe closing this for now?
