### ISSUE TITLE
Request: Level Card

### ISSUE THREAD

**Issue by RlonRyan** [AppliedEnergistics/Applied-Energistics-2#1387]
Due to space limitations, I should very much enjoy to see the following card added to AE2:

Level Card:
- For the Export Bus
- Integrated level monitor controller for all configured blocks.
- Possibly crafted by combining an advanced card with a level emitter.
- Perhaps requires the export bus to draw an additional channel.
- May require a Redstone Card to be concurrently installed.

The idea is to remove the need for five different export buses to keep dirt, cobblestone, stone, gravel, and sand levels under control.

This card would not allow for the bus to export an items other than the monitored, configured items. It would therefore not be capable of replacing a export bus + level emitter in all aspects, such as maintaining a constant level of glass by exporting sand to a furnace.

I apologize if this may be a duplicate of any other issue, in which case my searching skills have failed me. I thank you for considering this proposal.

**Comment by yueh** [comment]
I currently do not see any particular reason to add it. Especially as it breaks some basic concepts of AE.

* Only one (core) function per part. 
Toggling something on/off is not a core function, but exporting, importing or monitoring items are.

* No duplicate functions
There is already something to monitor items with the level emitter.

Also your use case is already covered by AE2. Just not by export buses.
Based on your description it would actually be a nerfed version of it. Requiring more channels, handling less item types etc.

**Comment by RlonRyan** [comment]
My apologies.

Addendum: How is this use case covered?

**Comment by yueh** [comment]
No need to apologize

Storage buses + their priority settings. Basically have something act as an overflow for the specific items once the primary storage is full.
