### ISSUE TITLE
Wireless Terminal upgrade

### ISSUE THREAD

**Issue by Mecromage** [AppliedEnergistics/Applied-Energistics-2#1392]
Iv always found the Wireless Terminal to be rather irritating with a limited area that's not really that large (unless you wana use a use a crap ton of power) and a battery that only lets you pull so many stacks untell you have to recharge it. i purpose that you can craft a ME terminal with a Quantum Entangled Singularity or QES along with a number of other wireless related materials and use the other on a quantum ring to connect the two. the ME wireless terminal now drains the power from the ME systems power and can access the ME system as long as the ME system is chunkloaded

**Comment by sci4me** [comment]
I haven't had this problem... I mean... use multiple wireless access points with few upgrades to increase power efficiency... as for the battery, I agree it is a bit small but it hasn't been a problem for me.

Interesting to see that it is for others. I would like a way to increase the battery life...

**Comment by minenine** [comment]
I apologize for the miss information. at the time i made this post i was unaware of the changes they made to the wireless access point and boosters. but when i say range i was thinking like across dimensions and when im exploring far away from the base. iv seen others do it with a logistics pipe's remote requester but i like to achieve this within AE2 itself and not use other mods.

**Comment by thatsIch** [comment]
Teleportation is meant to be expensive, 

especially dimensional teleportation.

Its a design decision not to allow dimensional teleportation for free and limit the range on the WAP. If you think its too limited, we offer a config option to increase it by a large amount on default or per upgrade. (e.g set base range to 10000)

**Comment by Mecromage** [comment]
i never thought of this addition to be inexpensive but more of a quantum ring transferred into a spatial storage and the spatial storage inserted into a wireless terminal. the power to use it would be the same if not more then a normal quantum ring connection. though if that's the design then i can live with it. thanks for letting me know about the config.

**Comment by thatsIch** [comment]
Expensive does not need to be in terms of power, but was more meant in game play mechanics. 
The belief of the original author was, that setting up a QNB should be a trivial matter at that point of time.
