### ISSUE TITLE
Repeated Crash related to: Exception in thread "AE2 VersionChecker" AL lib: (EE)

### ISSUE THREAD

**Issue by squirrelkiller** [AppliedEnergistics/Applied-Energistics-2#1397]
Just a quick note, I use players Fastcraft mod, and MultiMC for building and running my custom packs.

I have repeatedly been suffering a crash I am assuming AE2 is the culprit based on the following lines in the minecraft log in each crash:

Exception in thread "AE2 VersionChecker" AL lib: (EE) alc_cleanup: 1 device not closed
Minecraft exited with exitcode -1.

Crash report: http://paste.ee/p/u5aBS

**Comment by thatsIch** [comment]
That is just telling me, that you are using a not recommended forge version, which breaks their API.

In MC 1.8 they switched to using the `minecraftforge` namespace, but in 1.7 it is `cpw`, so apparently in the latest versions, they are using the newer versions of FML. But until it is not marked as recommended, there should be no reason for them to break their API.

Solution: downgrade Forge.
Culprit: User

P.S. If you have crashed based on AE2, report them. We can not fix, what is not being reported.

**Comment by thatsIch** [comment]
I just revisted and its even worse, apparently some mod does not use the recommended forge version, so you might not need to downgrade,

but upgrade all mods or remove them until you find the culprit.

**Comment by thatsIch** [comment]
as you can see, 

https://github.com/MinecraftForge/FML/tree/dda431353953457608c38aacb060ef82ddc88883/src/main/java/cpw/mods/fml/common

there does not exist a `ICraftingHandler`

**Comment by yueh** [comment]
Also to add something about the "error" you have identified. As this will be a common error in case of any crash and is rarely (or never) an issue.

In this case `AL lib: (EE) alc_cleanup: 1 device not closed Minecraft exited with exitcode -1.` is just a notice. It just says that minecraft is not closing the sound engine correctly, which under normal conditions is one of the rare possibilities to actually leak memory with java.
But as something did throw an exception, things are already going down and there is no need to explicitly handle it. Once it is done crashing and exiting the JVM, the OS will take care of it and free any used resource. So a graceful exit is not really needed.
But I have no idea, why this is reported in the context of the AE2 Versioncheck. You should probably ask the lwjgl devs about it. As it runs in its own thread, it will still run while minecraft itself is handling the exception, creating a crashlog and then exiting. Maybe this thread was just one of the last ones being killed.

**Comment by squirrelkiller** [comment]
I am familiar with the AL lib: (EE) alc_cleanup: 1 device not closed
Minecraft exited with exitcode -1. But the main reason I brought it
here is the fact that is specified AE2, which I have never seen this
line come up related to a specific mod before, but I will try
downgrading the version of forge as suggested. I will figure out which
mod is causing the issue and report it to the mod maker.

**Comment by MiningPickaxe** [comment]
So is there a way to disable the Version Checker?

**Comment by Smartydaniel** [comment]
Getting the same error here too.
Anybody got a fix?

**Comment by Tank-Missile** [comment]
Looking into it, VersionChecker.cfg from the AE2 config folder loads completely empty, resulting in the crash. However, the cfg file found in the Feed the Beast Infinity pack has the following text, and allows the mod to load.
```
# Configuration file

cache {
    # Waits as many hours, until it checks again. [range: 0 ~ 168, default: 24]
    I:interval=24
    S:lastCheck=1428430455225
}


channel {
    # Determines the channel level which should be checked for updates. Can be either Release, Beta or Alpha. [default: Beta]
    S:level=Beta
}


client {
    # If true, the player is getting a notification including changelog. Only happens if notification are enabled. [default: true]
    B:changelog=false

    # If true, the player is getting a notification, that a new version is available. [default: true]
    B:notify=false
}


general {
    # If true, the version checker is enabled. Acts as a master switch. [default: true]
    B:enabled=false
}
```

**Comment by MiningPickaxe** [comment]
Thanks

**Comment by wlam02** [comment]
Thanks for the info Tank-Missile. I had the same issue for the same reason. Updated my config file with the text you provided and fixed my issues on my home server.
