### ISSUE TITLE
Charge Quartz Crystal/Fixture lightning effect doesn't render with some resourcepacks

### ISSUE THREAD

**Issue by HanFox** [AppliedEnergistics/Applied-Energistics-2#1398]
I've already stumblingly told thatsIch this on IRC, but as he doesn't have a definitive answer yet I'll post it here so it doesn't get forgotten.

Due to the lightning effect using the first texture on the /assets/minecraft/textures/particle/particles.png spritesheet it doesn't render with some resourcepacks if they haven't centred that texture within the first grid space.

Notable "broken" packs are PureBDcraft in resolutions above 32x and Soartex.

Obviously the easy fix is for those resourcepacks to centre that texture, but Sphax won't retroactively change things nor does he make changes to support mods, sadly.

So, is it possible to add a custom texture for that effect? I understand if it's just not worth the effort, but it'd be nice to get the proper experience when using custom resourcepacks :)

**Comment by thatsIch** [comment]
As I already stated, loading a separate texture would have performance-wise an impact. This should not be the go-to solution. (even though its by far the easiest)

**Comment by HanFox** [comment]
Indeed. After you said that on IRC I should have updated my comment, but I neglected to. Sorry.

Hopefully there's a good fix out there somewhere.
