### ISSUE TITLE
AE2 buses and autocrafting stops then restart

### ISSUE THREAD

**Issue by sourivore** [AppliedEnergistics/Applied-Energistics-2#1399]
Hello,

I have a big system of AE2 (approximatively 700 channels used in total) and I don't know if it is the problem but sometimes the import/export buses stop working (they do nothing). Furthermore, my pending crafting requests stop.
If I wait a short/long time (depending on Saturn phases), the system restart normally. When I restart my game, the system restarts normally but sometimes for a few seconds, just importing a few items and stops again.
I use anchors or colored cables, so no cables are making a loop. All my chunks are loaded and when it begins, my system is not especially overloaded (just an import bus on an ender chest and 0/1/2 crafts)
My system has also enough energy my dense energy cell is already almost full.

I use the Hermitcraft ModSauce ModPack without additionnal mods.

Someone already have this problem and a solution ?

Thanks a lot.

**Comment by TheJulianJES** [comment]
Are you loading all chunks?

**Comment by sourivore** [comment]
As I said, all my chunks are loaded with the Dimensionnal Anchor mod and the problem is still here, even if I am near the import bus.

**Comment by TheJulianJES** [comment]
What AE2 version is in your modpack?

**Comment by sourivore** [comment]
rv2.stable build 1

**Comment by thatsIch** [comment]
If the server thread is having severe difficulties to keep up the TPS, AE2 will decrease its jobs to the minimal required jobs, which will ensure 20 TPS.

It should produce an error log with a big hint.

**Comment by sourivore** [comment]
I will read the logs but I'm not on a server. I play in solo.

**Comment by thatsIch** [comment]
Every SSP has also a server internally.
