### ISSUE TITLE
RF and Liquid P2P Tunnels don't work

### ISSUE THREAD

**Issue by Shockwve** [AppliedEnergistics/Applied-Energistics-2#1401]
For liquids I have tried:
---ExU Transfer nodes directly on the p2p tunnels
---Thermal Expansion and Plastic Tanks placed directly on the p2p tunnels
---Fluiducts from Thermal Dynamics
---Plastic pipes from MFR
---Tesseracts from Thermal Expansion

For RF I have tried:
---Energy cells directly on the p2p tunnels
---All tiers of fluxducts from thermal dynamics
---Energy Transfer Nodes
---Rednet Energy Cable (it can connect but won't work)
---Tesseracts

This problem is on rv2-stable, Agrarian Skies 2 (Pack version 1.0.39, manually updated AE2).
This is on a server and singleplayer.

![2015-05-07_00 33 02](https://cloud.githubusercontent.com/assets/7890240/7508588/b52e8c1e-f450-11e4-870c-c4d7eb0162b8.png)
In this picutres, the leadstone cell should be draining through the p2p into the hardened cell but neither are working.

Item, Redstone, Light, and ME P2P tunnels work fine.

**Comment by yueh** [comment]
#1138
