### ISSUE TITLE
Rotarycraft Automatic Crafting Table crashing

### ISSUE THREAD

**Issue by TomeWyrm** [AppliedEnergistics/Applied-Energistics-2#1402]
This is from another user on the Reika's Mods MCF thread. Just bringing it to your attention. The only mods required to reproduce are apparently AE2 rv2.stable, DragonAPI v6f, and Rotarycraft v6f.

ExDomino:
Server Crash when I tent to use the Automatic Crafting Table from RotaryCraft.
http://pastebin.com/65XcsxRJ

Reika:
Either update or (less likely) downgrade AE.

ExDomino:
Latest version of AE is rv2.stable build 1. And downgrading a mod is never a good idea.
For your mods too there are up to date.
Are automatic crafting table vitals for the rest of the mod?

Reika:
Ask the AE team about this one. The code crashing is ultimately their internal code.

**Comment by yueh** [comment]
RotaryCraft is not supporting rv1, update AE2.

**Comment by TomeWyrm** [comment]
OH. I totally missed that in the log! Thanks
