### ISSUE TITLE
Add logo to mcmod.info

### ISSUE THREAD

**Issue by thatsIch** [AppliedEnergistics/Applied-Energistics-2#1404]
One of the little support you have in `mcmod.info` is providing the logo.
Other nice features in the future would be screenshots and update link. These are current unimplemented though.

**Comment by thatsIch** [comment]
Max size is 200 x 65 px

**Comment by thatsIch** [comment]
apparently `mcmod.info` can not be seen indev

**Comment by thatsIch** [comment]
Would look like this

![ss 2015-05-07 at 05 34 44](https://cloud.githubusercontent.com/assets/2210496/7519100/6c4ce894-f4df-11e4-9457-20f866731d20.png)

**Comment by yueh** [comment]
If you manually copy the `mcmod.info` into the output directory, it will load them also for indev.

**Comment by thatsIch** [comment]
apparently logo for core mods is not a thing
