### ISSUE TITLE
Hide cable facades in NEI

### ISSUE THREAD

**Issue by Elvarion** [AppliedEnergistics/Applied-Energistics-2#1409]
NEI's Subsets makes it possible to hide items from the list to make it a bit easier to browse.
Could we have a subset for the Cable Facades perhaps? I know Extra Utilities have done this for e.x their drums and pipe jackets.

As of now with the mods we currently have ive got 14~ pages of facades / or around 1800 different Facades. This is due to Chisel being installed and other mods that add alot of blocks.

Being able to hide them from NEI would be great

**Comment by XFactHD** [comment]
I think the coremod Inpure core has this functionality.

**Comment by yueh** [comment]
Are these optional and are disabled by default? Otherwise people will start complaining about missing facades.

**Comment by Elvarion** [comment]
You need to manually disable them, so yes. Optional and "disabled" by default. The facades will be shown as default so players can see them in NEI.

This is the default, notice ive got 249 pages of items in NEI
http://gyazo.com/cf18650144eec54f24a0174b9c3b0517

Just hiding "Microblocks" from Forge will drop this to 122
http://gyazo.com/2ac2aae25659c2f828225525ef87ecde

**Comment by thatsIch** [comment]
Mh I was pretty sure I already suggested that..

**Comment by XFactHD** [comment]
I am using Inpure core for whatever mod and the only facade I can see is the glass facade.

**Comment by Elvarion** [comment]
Rather not add another mod to just hide the facades. I can live with them being in NEI, it would just be neat if you can hide them :)

**Comment by Entoarox** [comment]
@Elvarion inPure core is very nice to have for many of these things, since you can customise how it filters the NEI list, and it is also faster then NEI subsets (hiding items via subsets slightly slows down your searching, if you disable to many it becomes noticebly slow)

**Comment by AlphonseSantoro** [comment]
If you look at how GregoriousT does it, you'll see that he have one "universal" recipe for the tools that show up in nei. Thats how most moddders should register their recipes.

**Comment by thatsIch** [comment]
Well, I wonder why not just disable the creative tab?

**Comment by LemADEC** [comment]
Any alternative to InPure core for 1.12.2 or something else to hide all those facades from JEI?

**Comment by Pingger** [comment]
> 
> 
> Any alternative to InPure core for 1.12.2 or something else to hide all those facades from JEI?

Just hide them using JEI?! Enter the settings of JEI and enable element hiding mode, then hide any facade by oredict and all ae2 facades are gone.

**Comment by LemADEC** [comment]
Where do I enable this hiding mode?

**Comment by Pingger** [comment]
> Where do I enable this hiding mode?

> 
> > Any alternative to InPure core for 1.12.2 or something else to hide all those facades from JEI?
> Enter the settings of JEI 

From the JEI page:
With Item List Edit Mode Active:
(These controls are shown in-game on the item tooltip)
Hide Item: Control-Click Item
Hide Items and Sub-Items: Control-Right-Click Item
Hide all Items from a mod: Control-Shift-Click Item

**Comment by LemADEC** [comment]
"Hide ingredients mode" is the name of that JEI option to active "Item List Edit Mode".

**Comment by TheSnowyChickens** [comment]
Hello,

in 1.16.3 JEI there is no feature to hide items anymore.
With "JEI Tweaker" you could hide the facades, but a simple "mods.jei.JEI.hideItem(<item:appliedenergistics2:facade>);"
don't work, the player would have to add a lots of NBT tags to each row of hide code.
(and that is too much effort in large modpacks)

Is it maybe possible to add now a config option, to just show 1 cable facade in JEI ? :)

**Comment by Entoarox** [comment]
@TheSnowyChickens You can still hide items from JEI in 1.16.3, it just takes a bit more knowledge.

You need to assign a hotkey to the "hide item" mode, press it to toggle the mod, then mark any items you want hidden, press it again to untoggle, and use the `/reload` command to have JEI update so it actually hides the items you want hidden.

**Comment by TheSnowyChickens** [comment]
Ohhhhhhhhhhhhhh

Ups, :D

**Comment by yueh** [comment]
The idea here is to condense it into a single entry, which still indicates there are others available.

A config option in some random file is simply not an option for any player as noone wants to dig through hundreds of config files for maybe confusing options. E.g. allow JEI to display a single entry while cycling through a different facade every second or similar. With some additional requirements like being an ingame GUI option specific to JEI like "group similar items into one" and not have it be overwritten with every modpack update.

Just disabling them or only showing the stone facade just leads to confusing and reports about why are there no facades or only a single stone facade.

As there isn't any progress within JEI for probably over 5 years now, I doubt there will be something added. Therefore I close it for now. If it gets ever added to JEI, it would be nice and certainly be used. But until that happens it's mostly something which will never happen.
