### ISSUE TITLE
Inscriber Freezing

### ISSUE THREAD

**Issue by guyzer10** [AppliedEnergistics/Applied-Energistics-2#1412]
Bellow are pictures of the front and back of the inscriber build  did on my FTB Direwolf20 server. IThe build is connected to the controller through a p2p tunnel. I also have a Growth Accelerator build with SFM in the same room using the same p2p tunnel and it's working fine. 

The problem I'm having is the inscribers are freezing up half way through the process or it won't start at all when I request or manually try to make any of the processors, circuits or printed silicone. I've tried to remove and place back the inscribers and also tried reloading the game and server. I've doubled and triple checked to make sure my Import and export buses and interfaces are on the correct side of the inscribers but it still freezes. I've also tried to add accelerator cards in the inscribers to see if it would work, however no luck.

In the picture from the rear of the build, the top inscriber is on its own 8 channel sub system, not connected to the bottom 4 inscribers. It might be hard to tell in the picture. The bottom 4 inscribers are used for the circuits and printed silicone and the top one is for the processors.

Any help would be great. Thanks

Guy A.

UPDATE:
I'm not sure What i did however its working now. I walked away from it and messed around with it and its working. Thanks anyway.

![2015-05-07_23 13 31](https://cloud.githubusercontent.com/assets/10585765/7531099/a7265dec-f511-11e4-807c-2837e5e22d06.png)

![2015-05-07_23 14 34](https://cloud.githubusercontent.com/assets/10585765/7531101/b0b512cc-f511-11e4-9c8c-dadc9b5458e8.png)

**Comment by XFactHD** [comment]
AE2 version?

**Comment by yueh** [comment]
If they just freeze and not reset their progress, this should mean that they do not get enough power.
The same probably then applies to not starting.

**Comment by guyzer10** [comment]
It probobly was a power issue. I did walk away from the build for a few hours and worked on other projects; power being one of them. Then it was working. Thanks and Sorry for the lame question.
