### ISSUE TITLE
Capacity card usage in interfaces

### ISSUE THREAD

**Issue by kinnison** [AppliedEnergistics/Applied-Energistics-2#1418]
Hi,

We just had a thought -- it'd be awesome if we could put capacity cards into interfaces to increase the number of item slots and crafting pattern slots available.  Any chance of that?

Thanks.

D.

**Comment by yueh** [comment]
Like export buses, that you start with 1 slot and can unlock up to 9 slots with 2 capacity cards?

**Comment by XFactHD** [comment]
No, I think it is meant to be like some older request that have been denied, that you get another 9 slots for items and crafting patterns per upgrade card or something like that and I don't think that this is doable because you would need to completely swap the texture and the code for the gui when a card is inserted or removed.

**Comment by Entoarox** [comment]
@XFactHD if such a thing is done, the slots could be added in a permanent fashion as in the export bus, just not usable untill cards are added.

Personally, I can only think of non-AE machines, where you end up needing multiples of each machine just to manage all recipes possible as a good reason to have bigger interfaces, but I think a more expensive "high-capacity" interface would be a better way to do it then having capacity card support in a normal interface. (Although I wouldnt mind the interface limiting how many items you can stock to 3/6/9 based upon capacity cards, as I feel the 1/5/9 of export busses might be a bit steep for interfaces)

**Comment by XFactHD** [comment]
More expensive is not an argument in modded minecraft. I for example had more or less just gone through the basics and pretty early started to build the humongous 7*7*7 multiblock controller.

**Comment by Entoarox** [comment]
Hence why I also added the "crafting only" bit, making using that interface a calculated choice, where you can either have the full interface capabilities, or a high-capacity crafting interface.
