### ISSUE TITLE
Dupe Bug

### ISSUE THREAD

**Issue by Forcedown** [AppliedEnergistics/Applied-Energistics-2#1430]
Whenever a server restarts or a chunk is unloaded and reloaded whatever is autocrafting is dropped on the ground, but is also still autocrafting.

**Comment by Forcedown** [comment]
On direwolf 20 version 1.2.1

**Comment by TheJulianJES** [comment]
Wow... I have to try that.

**Comment by Berzerkerr** [comment]
I just experienced this scenario in the FTB Infinity 1.3.4 pack (We have not upgraded to 1.4.1).  It uses applied energistics 2 v. rv2-beta-8.  I created a large crafting multiblock (7x3x3) that crossed a chunk boundry between a chunk that was covered by a chunk loader and a chunk that was not covered by a chunk loader.  The first time I queued a craft and teleported away (unloading the chunk not covered by the chunk loader) and back the crafting components were dumped into the AE system, but the craft resumed without re-using the components when the chunk loaded effectively duping all the crafting components.  Each subsequent time the crafting multiblock would just drop the items on the ground.  Once I made sure that all chunks covered by the crafting multiblock stayed properly loaded, this issue ceased.

This issue (or at least my issue) seems very similar to #592 as well.

**Comment by thatsIch** [comment]
Related to https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1074?

**Comment by MrHelp** [comment]
+ work on stable 3 RV2

**Comment by MrHelp** [comment]
Video 2 
https://youtu.be/VPaBJPo9JVU
