### ISSUE TITLE
The player inventory in the inscriber is double added

### ISSUE THREAD

**Issue by TheJulianJES** [AppliedEnergistics/Applied-Energistics-2#1442]
Nice screenshot: http://imgur.com/bw8wQGu
Tried with all AE2 version (AE2 rv2 stable 1)
Baiscly the player inventory is double added, this can cause dupes and more.
Can be fixed with #1443

**Comment by Ianaver** [comment]
@TheJulianJES confirmed like you said, luckily I was not able yet to find a way of duping anything n survival (not to say it isn't possible with this bug) which is a good thing :)

**Comment by TheJulianJES** [comment]
@lanaver Good, I think duping with Inventory Tweaks COULD be possible but I'm not sure.

**Comment by Ianaver** [comment]
@TheJulianJES agreed!

**Comment by thatsIch** [comment]
What am I seeing? Whiter inventory highlight thus double player inventory?
