### ISSUE TITLE
Mystery item in drive crashes game

### ISSUE THREAD

**Issue by mrcgamer** [AppliedEnergistics/Applied-Energistics-2#1444]
Hello, I am having a problem with an item stored in one of my drives. I have no idea what the item is because it does not show an icon or a number, but it takes up a space. It is also causing all the items to lose their icons when looking at it in a terminal, but if I take the drive with the item out it stops disappearing. The game crashes when I try mousing over the item. When I take everything else out of the drive it says that it has 1 item type in it and 9 bytes taken up.

I'm not sure how to read the error report exactly, so any help would be greatly appreciated.

Thanks

Log: http://pastebin.com/r9NeEP11.

**Comment by yueh** [comment]
Based on a the crashlog it is a witchery item. But I cannot say which one or if it is actually a issue with witchery. Based on the crashlog, I would consider ttCore, NEI or witchery as actually culprit. Probably in this order.
