### ISSUE TITLE
Large amount of files.

### ISSUE THREAD

**Issue by Shybella** [AppliedEnergistics/Applied-Energistics-2#1445]
I have a folder in my world folder called AE2. Inside that there's a folder called spawndata. This folder is holding .dat files for each chunk. 

I have over 49,000 of these .dat files. I'm copying over my servers to another server, copying these are a pain. What information to they contain and is there a method to just removing them? Or Zipping them up and unzipping on the other side.

Thanks.

**Comment by yueh** [comment]
These store the information for the compass and meteorite generation. So without them, your players will no longer be able to locate meteors through the compass as well as it might mess up further meteor generation.

Also these mirror the normal region files. If just the amount is the issue, this will also apply to transfering the world itself. If you are using linux/bsd, I would recommend using something like rsync over ftp/scp. As it is designed to handle these situations.
With windows you are probably a bit screwed. File operations are not the fastest, especially a large amount of small files.

**Comment by Shybella** [comment]
Yeah, I used rsync didn't have much difference over cp with flags ivpr. Proabably the best bet then is zipping up the folder and moving it that way. 

Besides storing this information via .dat files. Is there negatives of using sql? 

Thank you.

**Comment by yueh** [comment]
In this case the bottleneck is probabyl the mounted NAS and how it handles writing files back to it. rsync over ssh is probably way better.

SQL has multiple downsides. SQL Servers are not an option, so this leaves mostly sqlite.
Which is not provided by forge and the JDBC drivers are distributing some native libraries, so everyone using needs to fiddle with their classpath/launcher and try to convince it to load these libraries.
Also if something corrupts the file, it will break everything, compared to a corrupt .dat only affecting a small part.

**Comment by Shybella** [comment]
Yeah, that makes a lot of sense. Yeah, row goes poop it throws the rest off. I'm sure something could be written to handle this but that's more of a hassle, I'm sure. 

Zipping it up and moving that made the process much faster. Zips up in about 30 seconds. 

Thank you very much!
