### ISSUE TITLE
AE2 pattern conflicts

### ISSUE THREAD

**Issue by Deshiba** [AppliedEnergistics/Applied-Energistics-2#1446]
Setting up a basic auto-crafting network with patterns to convert nuggets to ingots to blocks and back again is something that should be possible. And when I insert the 4 patterns required into the system and add some items it all works as I expected.
![2015-05-11_23 03 11](https://cloud.githubusercontent.com/assets/10565800/7575192/43ae86fc-f833-11e4-8945-0bf76d91409f.png)

But when I actually want to craft ingots, it tells me that there aren't enough materials to create ingots, even though there's a full stack of blocks in the system and there is a pattern for it. 
![2015-05-11_23 03 50](https://cloud.githubusercontent.com/assets/10565800/7575306/13195ae8-f834-11e4-9e08-3c8b95293ba2.png)
 
This seems like an unintended flaw, seeing as what I'm asking the system to do isn't hard at all.

**Comment by yueh** [comment]
#476, #541
