### ISSUE TITLE
Dense Cables show up as "Unnamed"

### ISSUE THREAD

**Issue by Iomega0318** [AppliedEnergistics/Applied-Energistics-2#1450]
In appliedenergistics2-rv2-stable-1 I have Channels set to False and the Dense Cables are showing up as "Unnamed".

Not a big issue but I thought I would report it.

**Comment by XFactHD** [comment]
When channels are disabled, you actually shouldn't be able to get dense cable.

**Comment by Iomega0318** [comment]
Which makes sense of course, but just wanted to let you know lol. I haven't tried to craft them it's just how they show up in game. Also perhaps if channels are disabled the dense cables shouldn't be disabled? Otherwise how would you use the Quantum Network? Just a thought..

**Comment by XFactHD** [comment]
The dense cable has to be disabled because the renderer that renders the lines for the channel usage needs a serious number between 0 and 32 to work, otherwise they misbehave.

**Comment by Iomega0318** [comment]
Ahh that I did not know, well then perhaps a modification that when channels are disabled the crafting recipe for the bridge change from requiring dense cables to something else? Also I just checked and the "Unnamed" dense cables are craftable in game..

**Comment by XFactHD** [comment]
If they are craftable, this is a serious, and when placing the cable, probably also a world corrupting bug.

**Comment by Iomega0318** [comment]
Good thing I didn't place it then LOL but it is indeed craftable.

**Comment by yueh** [comment]
How about adding some more information like screenshots? Because I cannot reproduce it.

**Comment by Iomega0318** [comment]
I will see if I can get you a short video tomorrow, I don't know why it allows me to craft it but it did..

**Comment by Iomega0318** [comment]
I made sure I was using the latest version of AE and I am not op'd on the server or in creative. Here is a video showing me crafting it in AE.

https://vid.me/Yu6p

**Comment by thatsIch** [comment]
Can you post your configs for AE2 please?

**Comment by Iomega0318** [comment]
Client:
http://paste.ubuntu.com/11252579/

Server:
http://paste.ubuntu.com/11252578/

**Comment by border999** [comment]
Hold up, I have encountered something like this in my work on a private modpack, it would appear that certain versions of NEI cause items to appear to be named unnamed. Not saying this is the same as what's happening to you, just though it would be something you should look into.

**Comment by yueh** [comment]
rv3 will fix it. We should try to cherrypick it into rv2, but the changes are pretty large so it might simply be not feasible.
