### ISSUE TITLE
Items Not Showing

### ISSUE THREAD

**Issue by longnecks0** [AppliedEnergistics/Applied-Energistics-2#1451]
So I spent a ton of time getting togethor my stuff on AE 2, only to find that all my items will not show after putting them in e drive. They were there when I exited the terminal, and now they are gone. The Storage Cell shows that it has items, but they will not appear on an ME Terminal or ME Chest. What do I do?
EDIT: This occurs when putting in a Tinker's Construct tool

**Comment by thatsIch** [comment]
how does it exhibit?

**Comment by thatsIch** [comment]
related to this https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1189
