### ISSUE TITLE
Auto-Generate custom recipes

### ISSUE THREAD

**Issue by thatsIch** [AppliedEnergistics/Applied-Energistics-2#1452]
If custom recipes is set to `true` it expects the user to copy the custom recipes into the config folder. This is rarely applicable, because it requires usage-knowledge.

Auto-Exporting will highly improve the QoL for custom recipes user.

The should copy all files named with `*.recipe` in a specific path to the config location. This is extendable for having `*.recipe` files all over the package system if required.

**Comment by TheJulianJES** [comment]
:+1:

**Comment by thatsIch** [comment]
We decided to export the recipes automatically in something like a "backup" folder, which is refreshed on every startup. 

The user gets a new folder, from which the recipes can be loaded, if the user chooses to by copying over the recipes into his "own" folder. This would elevate the need for a config setting.
