### ISSUE TITLE
Wireless terminal "station can not be located"

### ISSUE THREAD

**Issue by DubbaThony** [AppliedEnergistics/Applied-Energistics-2#1456]
happenes on FTB trident server.
if I log in, i cant acces ME network. only solution is to literally stand on wireless point, log out, log in and like in 2-3 seconds open terminal. or I ment to let it hang up for 20 seconds, and then it will open up.
thats only way to be able to use it later, until next log off. using "applied energistics 2 rv2 beta 18".

also, there is graphical bug with controllers. breaking and placing them again will not solve problem though.

any suggestions?

screens

http://www23.zippyshare.com/v/lybymDoG/file.html
http://www23.zippyshare.com/v/QTh9yhMY/file.htm

**Comment by TheJulianJES** [comment]
Relink to your security station, somebody maybe broke and recplaced it or it was moved.

**Comment by DubbaThony** [comment]
Wow, thanx. now I dont even have to wait such a delays if I manage to finally  open it fast enough. idk how that works, but that is now working as fast as it should :+1:
