### ISSUE TITLE
Strange crash on my server, many mods involved

### ISSUE THREAD

**Issue by xanderc2** [AppliedEnergistics/Applied-Energistics-2#1457]
I have a strange error on my server that sometimes occour, it involves sometimes extra utils, somethimes cofh, this time AE2

i have a crash report on server that seems related to cauldron, after this error i've downloaded the map in single player, i realized an error with cauldron cannot occour in single player, and launcher the world again,

that's the error i have in single: http://paste.ee/p/WkRcA

100% latest versions of all mods

sorry for bad grammar, i hope someone can help i'm going crazy
thanks for support

**Comment by Entoarox** [comment]
The issue occurs in cofh's `TileAugmentable` with its array index being out of bounds at 7, the only thing I can think of that might cause crashes there is if you somehow have a machine with more then 6 augments, but I'd ask at the cofh feedback repository to see about getting it fixed.

**Comment by xanderc2** [comment]
Ok, my server is closed until you find the reason of this error, i wont see my server crashing everyday, i'm sure at 70% that the machine that cause this exception is the cyclic assembler, if you know what i am talking about.
thanks for the answer

**Comment by yueh** [comment]
As skyboy already said, this is an issue with cauldron or some other mod changing `ForgeDirection.VALID_DIRECTIONS` and adding `UNKNOWN` to it.

This is neither an issue of AE2 or TE.
