### ISSUE TITLE
Impossible to get fluix without mining?

### ISSUE THREAD

**Issue by Branjoman** [AppliedEnergistics/Applied-Energistics-2#1458]
I'm not sure if this is an oversight or an intended feature, but you are unable to grind up pure crystals into their dust format. This means you can't remake your pure crystals into seeds, which means you need to go through the labor of finding certus to charge and turn into fluix when you run out of fluix or its pure counterpart. Is this intended?

**Comment by TheJulianJES** [comment]
Yea?

**Comment by vallard192** [comment]
So the recipes on the following 2 pages are broken?  What version are you
using?

http://ae-mod.info/Certus-Quartz-Block/

http://ae-mod.info/Certus-Quartz-Crystal/

**Comment by Entoarox** [comment]
Pure certus can be reverted into non-pure certus, but at a 2:1 ratio to prevent duping, so you will still have to mine at some point, this is minecraft after all.
