### ISSUE TITLE
it dose not work

### ISSUE THREAD

**Issue by michalpiwko** [AppliedEnergistics/Applied-Energistics-2#1460]
it dose not work <?xml version="1.0"?>

-<theme>

-<metadata>

<id>theme_base</id>

<name>Base Theme</name>

<description>This theme defines the standard set of images and textures used by CraftGuide </description>

</metadata>

-<image id="base_image">

<source type="file">base.png</source>

<source type="resource">craftguide:textures/gui/CraftGuide.png</source>

<source type="resource">minecraft:textures/gui/CraftGuide.png</source>

</image>

-<image id="recipe_backgrounds">

<source type="resource">craftguide:textures/gui/CraftGuideRecipe.png </source>

<source type="resource">minecraft:textures/gui/CraftGuideRecipe.png </source>

</image>

-<image id="brew_recipe_background">

<source type="resource">craftguide:textures/gui/BrewGuide.png</source>

<source type="resource">minecraft:textures/gui/BrewGuide.png</source>

</image>

-<texture id="stack-any" type="clip">

<source sourceid="base_image"/>

<rect height="18" width="18" y="238" x="238"/>

</texture>

-<texture id="stack-background" type="clip">

<source sourceid="base_image"/>

<rect height="18" width="18" y="219" x="238"/>

</texture>

-<texture id="stack-oredict" type="clip">

<source sourceid="base_image"/>

<rect height="18" width="18" y="181" x="238"/>

</texture>

-<texture id="text-filter" type="clip">

<source sourceid="base_image"/>

<rect height="16" width="16" y="163" x="239"/>

</texture>

-<texture id="window" type="borderedtexture">

-<textures>

-<texture type="clip">

<source sourceid="base_image"/>

<rect height="4" width="4" y="1" x="1"/>

</texture>

-<texture type="subtexture">

<source sourceid="base_image"/>

<rect height="4" width="64" y="1" x="5"/>

</texture>

-<texture type="clip">

<source sourceid="base_image"/>

<rect height="4" width="4" y="1" x="69"/>

</texture>

-<texture type="subtexture">

<source sourceid="base_image"/>

<rect height="64" width="4" y="5" x="1"/>

</texture>

-<texture type="subtexture">

<source sourceid="base_image"/>

<rect height="64" width="64" y="5" x="5"/>

</texture>

-<texture type="subtexture">

<source sourceid="base_image"/>

<rect height="64" width="4" y="5" x="69"/>

</texture>

-<texture type="clip">

<source sourceid="base_image"/>

<rect height="4" width="4" y="69" x="1"/>

</texture>

-<texture type="subtexture">

<source sourceid="base_image"/>

<rect height="4" width="64" y="69" x="5"/>

</texture>

-<texture type="clip">

<source sourceid="base_image"/>

<rect height="4" width="4" y="69" x="69"/>

</texture>

</textures>

<borderwidth>4</borderwidth>

<borderheight>4</borderheight>

</texture>

-<texture id="pane" type="borderedtexture">

-<textures>

-<texture type="clip">

<source sourceid="base_image"/>

<rect height="2" width="2" y="1" x="78"/>

</texture>

-<texture type="subtexture">

<source sourceid="base_image"/>

<rect height="2" width="32" y="1" x="81"/>

</texture>

-<texture type="clip">

<source sourceid="base_image"/>

<rect height="2" width="2" y="1" x="114"/>

</texture>

-<texture type="subtexture">

<source sourceid="base_image"/>

<rect height="32" width="2" y="4" x="78"/>

</texture>

-<texture type="subtexture">

<source sourceid="base_image"/>

<rect height="32" width="32" y="4" x="81"/>

</texture>

-<texture type="subtexture">

<source sourceid="base_image"/>

<rect height="32" width="2" y="4" x="114"/>

</texture>

-<texture type="clip">

<source sourceid="base_image"/>

<rect height="2" width="2" y="37" x="78"/>

</texture>

-<texture type="subtexture">

<source sourceid="base_image"/>

<rect height="2" width="32" y="37" x="81"/>

</texture>

-<texture type="clip">

<source sourceid="base_image"/>

<rect height="2" width="2" y="37" x="114"/>

</texture>

</textures>

<borderwidth>2</borderwidth>

<borderheight>2</borderheight>

</texture>

-<texture id="button_up" type="borderedtexture">

-<textures>

-<texture type="clip">

<source sourceid="base_image"/>

<rect height="2" width="2" y="1" x="156"/>

</texture>

-<texture type="subtexture">

<source sourceid="base_image"/>

<rect height="2" width="32" y="1" x="158"/>

</texture>

-<texture type="clip">

<source sourceid="base_image"/>

<rect height="2" width="2" y="1" x="190"/>

</texture>

-<texture type="subtexture">

<source sourceid="base_image"/>

<rect height="32" width="2" y="3" x="156"/>

</texture>

-<texture type="subtexture">

<source sourceid="base_image"/>

<rect height="32" width="32" y="3" x="158"/>

</texture>

-<texture type="subtexture">

<source sourceid="base_image"/>

<rect height="32" width="2" y="3" x="190"/>

</texture>

-<texture type="clip">

<source sourceid="base_image"/>

<rect height="2" width="2" y="35" x="156"/>

</texture>

-<texture type="subtexture">

<source sourceid="base_image"/>

<rect height="2" width="32" y="35" x="158"/>

</texture>

-<texture type="clip">

<source sourceid="base_image"/>

<rect height="2" width="2" y="35" x="190"/>

</texture>

</textures>

<borderwidth>2</borderwidth>

<borderheight>2</borderheight>

</texture>

-<texture id="button_over" type="borderedtexture">

-<textures>

-<texture type="clip">

<source sourceid="base_image"/>

<rect height="2" width="2" y="1" x="192"/>

</texture>

-<texture type="subtexture">

<source sourceid="base_image"/>

<rect height="2" width="32" y="1" x="194"/>

</texture>

-<texture type="clip">

<source sourceid="base_image"/>

<rect height="2" width="2" y="1" x="226"/>

</texture>

-<texture type="subtexture">

<source sourceid="base_image"/>

<rect height="32" width="2" y="3" x="192"/>

</texture>

-<texture type="subtexture">

<source sourceid="base_image"/>

<rect height="32" width="32" y="3" x="194"/>

</texture>

-<texture type="subtexture">

<source sourceid="base_image"/>

<rect height="32" width="2" y="3" x="226"/>

</texture>

-<texture type="clip">

<source sourceid="base_image"/>

<rect height="2" width="2" y="35" x="192"/>

</texture>

-<texture type="subtexture">

<source sourceid="base_image"/>

<rect height="2" width="32" y="35" x="194"/>

</texture>

-<texture type="clip">

<source sourceid="base_image"/>

<rect height="2" width="2" y="35" x="226"/>

</texture>

</textures>

<borderwidth>2</borderwidth>

<borderheight>2</borderheight>

</texture>

-<texture id="button_down" type="borderedtexture">

-<textures>

-<texture type="clip">

<source sourceid="base_image"/>

<rect height="2" width="2" y="37" x="192"/>

</texture>

-<texture type="subtexture">

<source sourceid="base_image"/>

<rect height="2" width="32" y="37" x="194"/>

</texture>

-<texture type="clip">

<source sourceid="base_image"/>

<rect height="2" width="2" y="37" x="226"/>

</texture>

-<texture type="subtexture">

<source sourceid="base_image"/>

<rect height="32" width="2" y="39" x="192"/>

</texture>

-<texture type="subtexture">

<source sourceid="base_image"/>

<rect height="32" width="32" y="39" x="194"/>

</texture>

-<texture type="subtexture">

<source sourceid="base_image"/>

<rect height="32" width="2" y="39" x="226"/>

</texture>

-<texture type="clip">

<source sourceid="base_image"/>

<rect height="2" width="2" y="71" x="192"/>

</texture>

-<texture type="subtexture">

<source sourceid="base_image"/>

<rect height="2" width="32" y="71" x="194"/>

</texture>

-<texture type="clip">

<source sourceid="base_image"/>

<rect height="2" width="2" y="71" x="226"/>

</texture>

</textures>

<borderwidth>2</borderwidth>

<borderheight>2</borderheight>

</texture>

-<texture id="toggle_off" type="clip">

<source sourceid="base_image"/>

<rect height="13" width="13" y="191" x="48"/>

</texture>

-<texture id="toggle_off_over" type="clip">

<source sourceid="base_image"/>

<rect height="13" width="13" y="191" x="61"/>

</texture>

-<texture id="toggle_on_over" type="clip">

<source sourceid="base_image"/>

<rect height="13" width="13" y="191" x="74"/>

</texture>

-<texture id="toggle_on" type="clip">

<source sourceid="base_image"/>

<rect height="13" width="13" y="191" x="87"/>

</texture>

-<texture id="stack-oredict-single" type="coloredtexture">

<source sourceid="stack-oredict"/>

<color alpha="63" blue="255" green="255" red="255"/>

</texture>

-<texture id="EU-icon" type="clip">

<source sourceid="base_image"/>

<rect height="16" width="16" y="144" x="239"/>

</texture>

-<texture id="liquidFilterContainer" type="clip">

<source sourceid="base_image"/>

<rect height="18" width="18" y="124" x="238"/>

</texture>

-<texture id="recipe-tab_icon" type="clip">

<source sourceid="base_image"/>

<rect height="28" width="28" y="76" x="1"/>

</texture>

-<texture id="type-tab_icon" type="clip">

<source sourceid="base_image"/>

<rect height="28" width="28" y="76" x="29"/>

</texture>

-<texture id="config-tab_icon" type="clip">

<source sourceid="base_image"/>

<rect height="28" width="28" y="76" x="57"/>

</texture>

</theme>

**Comment by TheJulianJES** [comment]
?

**Comment by thatsIch** [comment]
come into IRC to resolve this in a dialog, 
you seem not be capable filing a proper issue.
