### ISSUE TITLE
All crafting jobs stop at "scheduled"

### ISSUE THREAD

**Issue by Drachlox** [AppliedEnergistics/Applied-Energistics-2#1470]
Using: Direwolf20 1.7.10

So i have this annoying problem that makes autocrafting impossible.
I have set up a molecular assembler with ME interfaces on each side, I have added a pattern to one of the interfaces. When I open up my ME crafting terminal and search for the item (in this case it's a basic chest) it appears with the text "craft" under it. So far so good.
I have several empty disks in my ME drive, so there is room for the chest once it is crafted. 
I click craft, select 1 chest, it tells me it has all it needs to craft the item, Crafting CPU is set to automatic, and i press START.

Nothing happens. 

I try again by clicking craft on the chest pattern in the crafting terminal. Again I select 1 chest, but this time the "start"-button is grayed out and it tells me no crafting cpu are available. 

I then check the crafting CPU (a multiblock consisting of 3 4k storage blocks and 1 coprocessor), and in one of the storage blocks i see the crafting recipe i ordered. It lists all the required items, none of them are marked as missing, but the chest says "scheduled: 1"..

I try to cancel the crafting task by clicking the "cancel" button in the crafting processor interface. 
I then go back to the crafting terminal, select the chest recipe again, choose 1 chest.. it no longer says "no crafting processor is available" and instead lets me click "start". When i do, the whole thing repeats itself.

I am playing on a multiplayer server. I have tried setting up a completely separate AE network just to try out autocrafting in addition to my main system, and the same error appears in both networks.

**Comment by jeremiahwinsley** [comment]
Make sure you don't have any other inventories adjacent to the ME interface. I've had this happen when I put things too close together, and the materials for crafting got pushed into a different inventory.

**Comment by mindforger** [comment]
or orientate the ME interfaces towards the assembler, but keep in mind, you will loose the connection between assembler and the interface, you'll have to add a acble to power it then

**Comment by tiennou** [comment]
Also, I had this happen by inadvertently making a *crafting* pattern in a *processing* pattern (like, when you manually set your pattern output to — in your case — Chests). I did that for sticks, and it was a hard time finding what I had done wrong.

**Comment by yueh** [comment]
Inactive.
