### ISSUE TITLE
Cell workbench doesn't work

### ISSUE THREAD

**Issue by Aevaris** [AppliedEnergistics/Applied-Energistics-2#1471]
Using rv2 stable, when I put a memory card into the cell workbench (to partition it to hold on charcoal), it doesn't keep the partition. I reproduced this on a fresh world as well.

To reproduce: take a 16k storage cell and put into workbench
![javaw 2015-05-17 09-11-31-03](https://cloud.githubusercontent.com/assets/9640671/7670724/ba4046fc-fc75-11e4-9f33-a63d315cca1f.jpg)

Put charcoal into workbench:
![javaw 2015-05-17 09-11-41-23](https://cloud.githubusercontent.com/assets/9640671/7670726/cf2d1cfc-fc75-11e4-97fe-4ab1bdc50483.jpg)

Push partition button. Mouse over result, it looks like it worked:
![javaw 2015-05-17 09-11-45-87](https://cloud.githubusercontent.com/assets/9640671/7670729/e34a4e26-fc75-11e4-8adc-55474fb4f0e1.jpg)

Take cell out and put in inventory, and it reverts to pre-partitioned state
![javaw 2015-05-17 09-11-51-87](https://cloud.githubusercontent.com/assets/9640671/7670730/eae4e0ba-fc75-11e4-9a3e-7ba20853b088.jpg)

For giggles, try putting it into your network, but alas it still stores all types of item:
![javaw 2015-05-17 09-12-29-08](https://cloud.githubusercontent.com/assets/9640671/7670731/fd3d0a12-fc75-11e4-9400-2e737ba5960c.jpg)

**Comment by yueh** [comment]
What do you expect should happen when you partion a disc based on the currently stored items and the cell is actually empty? Should it prevent any from being inserted?

**Comment by Aevaris** [comment]
I may be using the wrong tool, but what I thought used to happen was that it created a partitioned disc so that only that item could be stored. This allows me to not have to set up a ME chest so that I can guarantee only charcoal is in my disc to be partitioned.

My use case is that I'm producing a lot of charcoal now (steam power) so I want to partition a disc for only charcoal.

**Comment by Aevaris** [comment]
To add, it does work if I create a ME chest, put my empty disc in there, put 1 charcoal in it, and then take it to the cell workbench and partition it that way.

**Comment by XFactHD** [comment]
If you put the cell into the workbench, put the charcoal in the bench and take the cell out, it works too. The button has the purpose of partitioning the cell with the items that are on the cell at the moment.

**Comment by Aevaris** [comment]
Xfact, how do you put the charcoal into the bench? My screenshots above show that it doesn't work that way.

**Comment by XFactHD** [comment]
You put the cell into the dedicated slot, take the charcoal, click with it into the grid, so that a ghost item shows up and then you put the charcoal back into your inventory and pull the cell out. Then your cell should be partitioned.

**Comment by Aevaris** [comment]
That's my point. Look at my screenshots above. That does not work in RV2 stable and it is the whole point of my bug report here.

**Comment by XFactHD** [comment]
Your mistake is that you press the partitioning button. If you want to partition the cell with the items you put into the grid of the cell workbench, then you don't want to press the partitioning button.

**Comment by Aevaris** [comment]
Oh, so its entirely automatic? That's nice. I'll try that. Did this change recently (recently being a relative term meaning within the last few months)?

**Comment by XFactHD** [comment]
No, as far as I know it didn't change recently.

**Comment by Aevaris** [comment]
Can someone update the website then? The website still shows you pushing the partition button.

http://ae-mod.info/Cell-Workbench/

**Comment by yueh** [comment]
I do not see where the website says you have to click that button.
