### ISSUE TITLE
[request] angled terminals

### ISSUE THREAD

**Issue by power-spike** [AppliedEnergistics/Applied-Energistics-2#1473]
It would be great if you where able to somehow place terminals on an angle. 

a 30 or 45 degree angle, so you could put it horizontal - but slightly raised - like a console of types.
This would allow for some nice aesthetics in the long run, and some better looking base builds.

**Comment by Deshiba** [comment]
Like the Advanced Information Panel from Nuclear Control for IC2?

http://ftb.gamepedia.com/Advanced_Information_Panel

**Comment by thatsIch** [comment]
This is currently not possible. It would require a major rewrite on all the internals to handle such thing.

**Comment by yueh** [comment]
Might be an idea for a separate AE2 addon.
