### ISSUE TITLE
Glitchy Channels?

### ISSUE THREAD

**Issue by TheBossManGamer** [AppliedEnergistics/Applied-Energistics-2#1475]
My Network was getting a bit crowded so I re-did it and now even though the there is channels available it dosent seem to want to connect. Ive tried breaking and replaceing, restating the server, and un-chunk loading the area. Nothing seems to help, not sure what this is but Im also using a quantum bridge if that means anything.(it never did this on a controller.) Version: rv2-beta-30

EDIT: If you use a network tool it shows its on the network, but for autocrafting and showing its connected with the channels it dosent. Its a mechanical and visual glitch? I guess

**Comment by thatsIch** [comment]
You may want to read http://ae-mod.info/Channels/ (bottom section)
else I need more information, since "doesnt seem to want to connect" is a bit generic.

**Comment by TheBossManGamer** [comment]
Im sorry, a more descriptive term for this is that there is only 17 channels in use on the quantum link bridge and it is connected directly into the controller with a single dense cable and it isn't connecting the new interface im trying to connect.

**Comment by thatsIch** [comment]
Maybe provide screenshots or something along

**Comment by popcorn9499** [comment]
im having a similar problem but i found it with p2p connections but nothing went through so i reset the p2p and it worked. not sure if that helps
