### ISSUE TITLE
Reworking storage/conversion monitor interaction

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#1480]
# Current behaviour for storage/conversion monitors

| Shared action | effect |
| --- | --- |
| Left click | Nothing |
| Shift left click | Nothing |
| Right click & unlocked & hold item | Set displayed item |
| Right click & unlocked & hold nothing | Reset monitor |
| Right click & holding wrench | Toggle lock |
| Shift right click & holding wrench | Remove terminal (normal part interaction) |

| Storage monitor specific action | effect |
| --- | --- |
| Shift right click & unlocked & hold nothing | Reset monitor |

| Conversion montor specific action | effect |
| --- | --- |
| Right click & locked | Extract full stack |
| Shift right click & locked & any item | Dump hold stack into the network |
| Shift right click & unlocked & any item | Dump hold stack into the network |
| Shift right click & locked & empty hand | Dump every block into the network |
| Shift right click & unlocked & empty hand | Dump every block into the network |

This is quite inconsistent, ignores all interactions using a left click and needs wrenches as special case which cannot be displayed.
# Proposed behaviour

This is mostly similar to the behaviour of barrels and will no longer have a special behaviour for wrenches. But they prevent shift right click from being used to set/lock the monitor.
This sould also include an indication of the current locked state of a terminal.

| Shared action | effect |
| --- | --- |
| Right click & unlocked | Set displayed item, empty hand results in reset |
| Shift right click & empty hand | Toggle lock |

| Conversion monitor specific action | effect |
| --- | --- |
| Left click | Extract full stack |
| Shift left click | Extract single item |
| Right click & same item | Dump hold stack into the network (optional) |
| Right click & locked & any item | Dump hold stack into the network |
| Right click & locked & empty | Dump all configured stacks into the network (equals a double right click) |

Related issues:
- #12
- #71
- #135

**Comment by Belgabor** [comment]
Excellent suggestion. One small thing I'd like to add, make left-click vs. shift-left-click behavior configurable (aka switchable) so people can change it to their preference or in line with other storage solutions in a pack.

**Comment by yueh** [comment]
That would be for sure useful. But as config option it is only useful for SP as it would most likely be a global setting for everyone.

It actually requires quite some reworking on how the placement/interaction of parts are handled, so maybe there is an option to make it a clientside setting. But I cannot promise anything here.

`Shift right click & empty hand` could maybe also be changed a bit. Instead of only toggling the lock it could switch modes. Like locked/unlocked and normal/inverse interaction.
Of course it would force players to switch through 4 and not just 2 settings, which finally can be a bit tedious. Also it would need some visual indication for 4 states.

**Comment by Fma965** [comment]
This needs the documentation updated, took me ages to figure out that the process has changed
