### ISSUE TITLE
ME Crafting Monitor

### ISSUE THREAD

**Issue by GuestEG** [AppliedEnergistics/Applied-Energistics-2#1484]
A feature request:
A monitor for list of current network's active crafting jobs with ability to cancel any of them. So instead of going to check every single ME Crafting CPU you can have a glance and control of all of them from one central terminal.

UI might be in one of two modes: 
1) "compact" with a grid of just root jobs per crafting assembly, like a crafting monitor of every assembly on one screen  - so you can see overall picture of crafting busyness; click on a job cell can cancel it (like in LogisticsPipes autocraft).
2) "detailed", which is just normal Crafting CPU's UI grids stacked together with divider between them (might be quite slow due to much content refresh at a time).

I have this request after multiple attempts to craft something, getting "no CPU available" and then running around the base trying to figure out what CPU crafting what.

**Comment by XFactHD** [comment]
When you open a ME Terminal or a ME Crafting Terminal, when you click on the hammer symbol in the top right corner, you can see all the crafting jobs and you can click through multiple jobs in the way it was working in AE1.

**Comment by GuestEG** [comment]
Ouch. Always thought it was just a graphic element, not a button. I'm sorry. :( 
Maybe it need some sort of underlay to highlight it from window?
