### ISSUE TITLE
Blocks not rendering

### ISSUE THREAD

**Issue by joespinoza** [AppliedEnergistics/Applied-Energistics-2#1488]
![2015-05-19_16 04 29](https://cloud.githubusercontent.com/assets/12519230/7715835/caa2aed2-fe40-11e4-8569-ec6e13458796.png)

**Comment by thatsIch** [comment]
?

**Comment by Ianaver** [comment]
try the following;

#1 If you have optifine, change chunk rendering to smooth rather than multicore
#2 remove optifine if #1 doesn't work
#3 update forge if you havn't already

Hope that helped! :)

**Comment by TheJulianJES** [comment]
Update Forge and OptiFine @joespinoza

**Comment by joespinoza** [comment]
thanks @TheJulianJES, I just had to update the OptiFine
