### ISSUE TITLE
Limit number of a unique item in storage.

### ISSUE THREAD

**Issue by Lodran** [AppliedEnergistics/Applied-Energistics-2#1489]
I'm looking for a way to place a limit on the number of a particular item which will be allowed into storage.  In particular, I'm trying to come up with a good way to manage GenDustry gene samples.

In theory, I could add an export bus to my network for each sample, but the total number of unique samples I would have to manage is huge, and connecting that many export buses to the network would undoubtedly cause server-wide issues.

It would be nice to be able to simply configure each item using the ME Interface, so that only a set maximum of that particular item will be accepted.  Perhaps center clicking the item could present a configuration interface for it?

Another possibility would be a specialized export card, one that works like the redstone card + level emitter, but in a single card.  When combined with a fuzzy card, it would take the level of each unique variant of the item into account, rather than all items of that type.

The level card would also have the advantage of eliminating redstone lag from the process - I'm forever hitting the wrong level when a complex crafting operation is involved.

**Comment by Entoarox** [comment]
Use a storage bus on a fixed-size inventory to act as actual storage, and a second storage bus with a lower priority to dispose excess samples, a configured ME storage cell could replace the first storage bus if wanted.

**Comment by Lodran** [comment]
@Entoarox - yes, this approach works, but in order to manage GenDustry gene samples with would involve a couple of hundred storage buses.  Having had parts of my AE network go dark on me because of lag issues, I really don't like the idea of attaching that many storage buses.

The other issue with your approach is the difficulty in setting it up - Add a storage device (I'm using droppers so I can limit to 9), configure it to accept only a particular gene sample.  Configure the disposal to accept the same gene sample.  Remove all of that sample from the AE so it will then place them in the dropper rather than memory.  Reinsert all of the samples.  It's painful, it's repetitive, it's tedious, and it's everything I built an AE system to avoid.

That said, your approach is the one I'm currently using, for those gene samples I encounter most often.

**Comment by Entoarox** [comment]
You can add capacity cards to the storage busses to extend how many items a storage bus can filter to somewhere around 64 or so, as to re-inserting the samples, simply use an IO-port to empty your drives one at a time, that automatically does most of the hard work for you.

**Comment by Lodran** [comment]
@Entoarox - Capacity cards only help on the "disposal" side of the gadget - each of the gene sample storage bins has to have its own storage bus.  Right now, I'm up to 40 and haven't run out of common genes.  As to emptying the drives one by one, I have over 100 drives...

**Comment by Entoarox** [comment]
Why would you need separate storage bins for each type of gene sample? a formatted ME drive should be able to handle it if absolutely needed, although I think you might want to look into the 'storage drawers' mod, it adds barrel-like blocks that can be connected to a single controller that you then put the storage bus on, very efficient!

**Comment by Lodran** [comment]
You sample a bee for it's genes - you sample lots and lots of bees for their genes.  You end up with tons of gene samples.  Each one costs you 4 tin and a redstone to make, and you really don't need 5000 "speed: slowest" gene samples kicking around in your system.

The whole point is that the ME drive will happily keep on storing samples that you don't need or want, and would much rather recycle back into a blank sample.

**Comment by yueh** [comment]
This is way too mod specific for AE2 itself. Some other storage mod is probably way better at handling them. Maybe XU filing cabinets?
If nothing really works, maybe raise that issue to gendustry itself and propose some storage, which can only hold 1 of each sample? Might be even a feature request for ExtraCells.

**Comment by Lodran** [comment]
I'm not sure why you say it's "too mod specific" - the need for keeping a limited stock of any particular item comes up over and over, and the current mechanism for managing stock requires a lot of construction, and is prone to causing lag, both because of its use of redstone in level emitters, and because most buses are serviced by a polling service routine which stops servicing busses after 50ms.

**Comment by yueh** [comment]
AE2 can already handle limited stacks and not only limited to level emitters/export buses.
But as you claimed that you probably need hundreds of storage buses, which ultimately means handling several thousands of different items with AE2.
Which is really sound like some special use case for a specific mod.
