### ISSUE TITLE
Items vanishing from inventory

### ISSUE THREAD

**Issue by netzgeist** [AppliedEnergistics/Applied-Energistics-2#1491]
Items vanish from your storage under a certain condition. Tried on a fresh build with default config.

Replication example:
- Have 3 wool in you inventory, 1 in your AE system. 
- Shiftclick a recipe using 6 wool via NEI into your crafting terminal. I tried a dark curtain from ExU.
- Cancel the craft as its not possible (The terminal offers you to craft a carpet because it cant fill up all the slots)
- You now have 2 wool in your AE-System and 0 wool in your inventory.

**Comment by yueh** [comment]
Cannot reproduce it with the current version. Neither with the XU curtains or vanilla recipes like beds.

**Comment by iHeartZigg** [comment]
Having the same thing happen to me and my friends on the server.
Running FTB Infinity 1.5.1.

Seems to delete 2 "Charged Draconium Blocks" almost every time if i try to cancel crafting a "Resurrection Stone".

**Comment by Dongonzales** [comment]
i have had the same problem, with similar conditions.
before crafting i had 7 Alveary block in the inventory.
i wanted to craft the Rain shield by shift clicking the recipe in the grid.
the crafting of rain shield succeeded.
the next recipe with alveary blocks (Frame housing) failed and all 6 alveary blocks disappeared after putting in the recipe from NEI. it looks like this doesnt happen every time you try to craft
