### ISSUE TITLE
Disabled channels and intermittent auto crafting?

### ISSUE THREAD

**Issue by Iomega0318** [AppliedEnergistics/Applied-Energistics-2#1494]
So I set up my system with some auto crafting and of course I have channels disabled, however when actually trying to auto craft 99% of the time it says "simulation" however and seems to be randomly it will actually load the crafting system and allow you to click start. I am pretty sure I set it up correctly considering I have channels disabled and therefor no controller and the fact that it does allow me to auto craft when it can actually detect the crafting system. So bug or intended? Let me know if you need more information as usual, and hopefully you can replicate it lol..

**Comment by thatsIch** [comment]
need config and setup,
also try with channels enabled.

**Comment by Iomega0318** [comment]
Client:
http://paste.ubuntu.com/11252579/

Server:
http://paste.ubuntu.com/11252578/

I will work on testing some more this weekend to get some more information for you.

**Comment by Iomega0318** [comment]
So it looks as if this is just a MP bug, I cannot replicate this in SP using the same setup I have on my server with the exact same configs. I assume it's either a lag related issue or perhaps syncing?

**Comment by thatsIch** [comment]
might be syncing,
can only look out for it

**Comment by Iomega0318** [comment]
I will keep playing around with it then. Thank you.

**Comment by Iomega0318** [comment]
So just curious, does this need to be fixed on my side or is the syncing mod related? I am not entirely sure how to fix it if it's on my side..

**Comment by thatsIch** [comment]
You can not fix this,
only we can do it,
but we have no clue where to start..

**Comment by Iomega0318** [comment]
Ahh okay I thought that may be so, and no worries at least it's not crashing my server :)

**Comment by thatsIch** [comment]
Try it with stable 5 if you can

**Comment by Iomega0318** [comment]
I am actually in the process of doing on update on all the mods on my server, I will load your new version in with the changes later today (it's 5 am my time) and let you know how it's working.

**Comment by Iomega0318** [comment]
This seems to resolve the syncing issues I was experiencing with crafting, but I will keep playing around with it and let you know if I encounter any additional issues.

Thank you!
