### ISSUE TITLE
Non-smart dense cables

### ISSUE THREAD

**Issue by icewindow** [AppliedEnergistics/Applied-Energistics-2#1495]
Similar to normal covered ME cables, which come in the variants non-smart and smart, I think there should be a non-smart version of dense cables. You'd craft them using normal covered cables instead of smart cables.

I hope this isn't considered asking for a cheaper version of dense cables. I just don't want to see the channels used along the entire cable because I don't like the way it looks.

**Comment by yueh** [comment]
Might be an idea. The recipes would also support an easy upgrade and still use the same materials.
But the code/rendering is probably a bit more complex and will potentially break the API.

**Comment by TheJulianJES** [comment]
:P:

**Comment by Entoarox** [comment]
Not a bad idea, but unless the non-smart dense are also FPS/TPS friendlier I personally see little reason to break the API for it, better to hold on adding it until something else more important that is also API breaking gets added. (If it doesnt break the API though, I have no issue with it getting added whenever, but API breaking stuff is usually best reserved to being done in large chunks, that way add-ons dont get broken to often)

**Comment by TheJulianJES** [comment]
I don't see the point of "it could break the api" because it's for rv3 and the api could be completely different.

**Comment by Joe4evr** [comment]
> You'd craft them using normal covered cables instead of smart cables.

But the current recipe for Dense Cable *is* normal covered cables (unless there was an update recently which changed that and I didn't notice). What about making it just 4 covered cables without the Redstone and Glowstone?

**Comment by yueh** [comment]
Even if it is rv3, a API change should still be reasonable and not break everything for a small feature.

I doubt it will have any improvement in terms of FPS/TPS. Cables are actually statically rendered and are basically "cached" until something in the chunk changes like a block placement/update.
If at all it should be a small decrease in the rendering performance as it has to check for another cable type, but very likely not noticable until massive chunk updates occur and then there are enough other things causing performance issues. So a random 0.1 or so FPS loss each time it refreshes the rendering is unimportant.

Most likely it could make some bugs in the rendering code itself visible and could finally be way more work than intended.
