### ISSUE TITLE
suggestion - M.E. Backpack

### ISSUE THREAD

**Issue by shivachirr** [AppliedEnergistics/Applied-Energistics-2#1497]
i know this may be shot down but i thought it would be a good thing to suggest so here we go

so i was thinkking of a M.E system backpack as a super high end highly customizable backpack that will work as a mobile M.E system. i know we have the wireless acess and the mobile sorage unit thing i forget what it called but i was thinking  something of a backpack where you have slots that are empty and you basicly have to configure the setup of the system in the backpack. and i dont mean just add cells. i mean you have to add cables controls drive chest power blocks wireless setups to access it and maybe low end craft but it wont be as strong as a normal M.E system because you cant interact with other mod blocks or furnaces to auto craft but maybe with like a neather star or something like that you can make a m.e system link so when in range your back pack can access the main system. anyway thats what i suggest.

Following is the example of the backpack ui im thinking of

![javaw 2015-05-23 03-35-15-59](https://cloud.githubusercontent.com/assets/9361172/7782936/d86afdbc-00fc-11e5-85e1-3f3dc7cb6a11.jpg)

**Comment by thatsIch** [comment]
So how would you provide the coal to the vibration chambers?

**Comment by shivachirr** [comment]
not sure maybe there would be a slot for it but i was thinking with other mod installed that provoid power like rf should be adaptable like flux capacitors or ender io capacitors

**Comment by thatsIch** [comment]
I guess this is something inbetween the spatialIO and the portable cell. 
Even though I like it, not sure, if this is really required / needed as I do not feel a lot of applications but having a portable QNB.

There is also the question how to interact with such a mini system.

**Comment by yueh** [comment]
The idea itself is interesting, but it does not really fit in terms of a simple backpack. Maybe as portable spatial cell?

Also there are quite a few issues. Like interacting with it or even how to map a 3d space to a 2d one.
Which also does not support rotating the blocks and other functionality.

I feel it would be a huge amount of work for a pretty limited feature (and constant requests to support any other mod). In the end it is probably just an option to obtain a portable QNB, which was always rejected in the past.

It probably also overlaps to some degree with #33 and #870, which is more feasible to actually implement.

**Comment by shivachirr** [comment]
well another way i see of interacting to the devices in the back pack was something smiliar to this that i saw on youtube that AlgorithmX2 talked about -> https://www.youtube.com/watch?v=tuHxhzcm23o&index=3&list=LL3ANJTQSVqe_6Ps67hbF1mA

**Comment by happysmash27** [comment]
Building off of the portable spatial cell idea:
• An ME System could be made inside the spatial cell
• It would contain a quantum link, or something else  that would support the next bullet point
• This quantum link (or other thing) would be accessible by using the storage cell
This could function a little like a wireless receiver, but instead of accessing a remote ME/Automation System, it would access an internal one.
An alternative to the quantum link might be to have some kind of ME cable in the wall, but I don't know how that could be implemented in a spatial IO chamber.
I may think about this some other time, and further develop the idea.

**Comment by Blue64** [comment]
As far as Power goes, Energy Cell Slot, no Vibration Chamber included, could work similar to the ME Drive, and if you put your wireless devices in, it could even recharge them for you (sucking energy from said Energy Cell).

I for one love this concept, but I wouldn't want a portable QNB in there either, and to access the Drives, you could use an Advanced Wireless Access Device [AWAD] (rendering options could resemble WW2 Communication Officer backpacks with the antenna sticking out).

This would really beef up the storage while Mobile, thus allowing for longer trips. Idk how long y'all normally are away from base, but I usually fill up within a few game days, including the Portable Cell. My game has a wide variety of blocks, so this would solve the need for 18 Portable Storage Cells and instead just carry around an ME Drive on my Back (which is the basic idea behind regular backpacks anyway, item storage).

Limiting features could include needing it to be on your HotBar to access it via AWAD, and Adventure Backpacks lets you set backpacks down and interact with them as a Block, which opens up capabilities such as recharging the Cell, perhaps give it an Illuminated Panel to let it generate Light while a block, while on the topic of socketing in stuff, a socket for the Security Cards, that way, if you're charging from a friend's network, he can't steal your loot.

I was about to recommend a Molecular Assembler, but then I thought "nah, too bulky". Still, would be nice to see. If you want an excuse for not being a light source while wearing it, just render the Illuminated Panel in the general area where the Player would be wearing it.

When connected to a network, it can take up the standard amount of Channels and power that all of it's components do (ME Drive, Wireless Connector, Illuminated Panel, etc), and (provided all the security access checks out) allow for items to be pulled out of it, putting items in is standard IO Port use via pulling drives out and running em through the IO Port before putting em back in.

**Comment by shivachirr** [comment]
this is still something i want to see ingame and all the feed back and idea
some looked good some im ify about but all things good
