### ISSUE TITLE
Autocrafting simulation stall

### ISSUE THREAD

**Issue by gozulio** [AppliedEnergistics/Applied-Energistics-2#1502]
This is something i have seen in quite a few different issues, and its something i'm experiencing myself.

the problem is that when i try to  craft an item in my AE network the craft window will simply hang at the simulation page with a grayed out start button.
(like this, trying to craft an ME interface)
![2015-05-23_15 42 42](https://cloud.githubusercontent.com/assets/10771387/7785601/dfdfaf12-0164-11e5-90bc-2573c6c3594c.png)
One strange thing to note here, is the page says it's going to craft fluix powder, annihilation cores, and formation cores. these already exist in the network, i made sure of that.

After digging through a few issue threads to see if anyone solved the problem i found that issue #682 mentioned something about items being stored in more than one place. a bit pointless given that im crafting an me-interface... and all of those items only exist in me drives. i decided to disconnect the outgoing line from my base and try that.

After disconnecting my base from all outside infrastructure (a few MFR farms, projecte RM flowers (all using storage busses) and my frame quarry, i ran the autocraft again. It worked perfectly fine this time.
the autocrafter saw the ingredients in the drive and was able to craft them as well. (and i made sure to check my channels again to make sure i didn't make a mistake)
![2015-05-23_16 12 53](https://cloud.githubusercontent.com/assets/10771387/7785632/916a9cd2-0166-11e5-9f99-7de13c82e443.png)

EDIT: Increasing the priority on my ME drive units eliminates the anomaly...  i went out to my tree farm and lowered the priority the wood storage bus to -10, removed everything from my me drives that could be used to craft sticks. and tried crafting sticks. it worked. i then moved the priority back to 0, and tried again. still worked. i then moved my ME drives from their higher priority back to 0. and the autocrafting kept working.

EDIT... again...: i tried this on a few other crafting recipes. found one that was getting stalled in simulation. this time it was a project red or gate. the results are mixed and changing the me drives priority only fixes some items at a time.

**Comment by shivachirr** [comment]
I get this to and its annyoing i cant make things i need like im trying to make the energygy collector mk3 from project e and i have evything i nee to do it i mean and ive noticed its not reading the diamond blocks i alrdy have in the system its trying to create more so thtere is a another problem to add

**Comment by gozulio** [comment]
its something to do with the import busses or something.

@shivachirr to get around the issue i took all of the things being accessed with storage busses off my main me network. it seems to be working fine now.

**Comment by shivachirr** [comment]
well that could be a issue im using project eat to give my a.e system acess to a infinet but slow generating source of rare materials

**Comment by gozulio** [comment]
projecte isnt really causing an issue... i was just listing things that i had storage busses attached to =P

**Comment by shivachirr** [comment]
ok

**Comment by yueh** [comment]
Duplicate

**Comment by mctom987** [comment]
Missing duplicate ID
