### ISSUE TITLE
Server crash - During game-play 

### ISSUE THREAD

**Issue by EeveeA** [AppliedEnergistics/Applied-Energistics-2#1503]
http://a.pomf.se/xnpkxk.txt

From our observation, server crashes when a player that was not the ME creator right clicks any block with a GUI that is connected to the network. 

No, the security terminal is not in use.

**Comment by yueh** [comment]
We do not really support or even test against Java9 as it not ready for use.

**Comment by EeveeA** [comment]
Is there a java argument to tell a server what java version to use?
