### ISSUE TITLE
ae2 bugs and duplicates redstones for automated insciper setup.(actually it only uses roughly 1/10th of redstone reserved)

### ISSUE THREAD

**Issue by raven0ak** [AppliedEnergistics/Applied-Energistics-2#1504]
I noticed very odd behavior in setup where interface if placing materials to chest and ender IO item conduits taking em to correct inscribers (5 insciper in total: 1 for each press and one to combine the circuit), oddity is that that AE2 places way too much redstone dust into chest and somehow bug occurs and places single redstone into silicon press against whitelist, press rules itself and interfaces placing direction. When I go fix the issue I do note that example order that requested 2k redstone out of 7k stack in system completed eventually after taking redstone out of silicon press, problem is that redstone used was 200 after I returned excess redstones out of chest back to system ... (no, there was nothing at time mining so redstone wasn't resupplied) modpack is ftb infinity 1.7 (ver 1.3.4) (so , order should have eaten 2k redstone from storage...it only used 200)

**Comment by yueh** [comment]
rv2-beta-8 is outdated. Update first before confirming if it happens again.

**Comment by raven0ak** [comment]
![mc inscipers](https://cloud.githubusercontent.com/assets/12258283/7792168/9d2c1a40-02b6-11e5-874c-b5bbcdcdcf4d.png) silicon press is one at right where as circuit press is one at left, under the chest is interface with arrow pointing up and recipes for correct components and actual circuits. and as said above, it should be nightly impossible for redstone to end into silicon press:)

**Comment by thatsIch** [comment]
Are you by chance requesting the crafting via interfaces?

**Comment by raven0ak** [comment]
nope, interface has simple patterns of "these items provide this item" and its ender IO pipes that know what to deliver to where (with white lists). there is no automated  stocking up at least currently

**Comment by yueh** [comment]
No further feedback. (Just in case, I should also point out that this modpack version is horribly outdated)
