### ISSUE TITLE
Items are out of the Grid

### ISSUE THREAD

**Issue by speedcrafter442** [AppliedEnergistics/Applied-Energistics-2#1506]
The Items are sorted in outside of the grid

**Comment by thatsIch** [comment]
more information? what grid are you talking about, crafting grid?

**Comment by speedcrafter442** [comment]
the grid of the me-terminal

**Comment by TheJulianJES** [comment]
Are you using a resurcepack!

**Comment by thatsIch** [comment]
I am closing this, 
feel free to share information about your issue,
when you are ready.

**Comment by speedcrafter442** [comment]
screenshot of the bug https://www.dropbox.com/s/k2jnxd3b6tz1up3/2015-05-26_13.03.21.png?dl=0
https://www.dropbox.com/s/jhifj6z71kgpcec/2015-05-26_13.08.05.png?dl=0

**Comment by TheJulianJES** [comment]
@speedcrafter442 Mod List?
Also try updating AE2 to the latest rv2 stable release :)

**Comment by speedcrafter442** [comment]
it is the latest version with no old config file

**Comment by speedcrafter442** [comment]
https://www.dropbox.com/s/t6yzgzsd6pl4mfi/2015-05-26_13.35.17.png?dl=0
https://www.dropbox.com/s/6nednfbuae6v92g/2015-05-26_13.35.20.png?dl=0 
the bug also exists at the crafting and pattern terminal

**Comment by speedcrafter442** [comment]
i fixed it now by reinstalling the newest librarys of minecraft

**Comment by TheJulianJES** [comment]
@speedcrafter442 Okay...

**Comment by speedcrafter442** [comment]
maybe older minecraft libraries caused this bug

**Comment by thatsIch** [comment]
404, cant view the images

**Comment by thatsIch** [comment]
also that makes no sense xD

**Comment by TheJulianJES** [comment]
What?

**Comment by thatsIch** [comment]
the newest library of minecraft stuff

**Comment by TheJulianJES** [comment]
Why, maybe he had 1.2.5 lib stuff..

**Comment by TheJulianJES** [comment]
I saw the screenshots, they were all going to the right in the terminal.

**Comment by thatsIch** [comment]
This might be actual possible if he updated a vanilla minecraft profile.. but unlikely. Generally it would crash before cause of missing stuff.

**Comment by TheJulianJES** [comment]
Maybe it was just outdated and AE2 needed newer version..
