### ISSUE TITLE
Inscriber issue

### ISSUE THREAD

**Issue by jskorepa** [AppliedEnergistics/Applied-Energistics-2#1507]
Items end up in wrong slot using following setup.

![snimek z 2015-05-24 22 53 49](https://cloud.githubusercontent.com/assets/11293969/7789623/415e645a-0268-11e5-8675-6ef0beb8685f.png)
![snimek z 2015-05-24 22 53 57](https://cloud.githubusercontent.com/assets/11293969/7789625/4187b9b8-0268-11e5-8f78-f15625c54008.png)
![snimek z 2015-05-24 22 54 06](https://cloud.githubusercontent.com/assets/11293969/7789626/4187f09a-0268-11e5-8f37-d15f4b99ee70.png)
![snimek z 2015-05-24 22 54 13](https://cloud.githubusercontent.com/assets/11293969/7789624/41761334-0268-11e5-8ee5-39949cdc4b28.png)
![snimek z 2015-05-24 22 54 19](https://cloud.githubusercontent.com/assets/11293969/7789629/418da83c-0268-11e5-99fa-f6e9fc991cf8.png)
![snimek z 2015-05-24 22 54 36](https://cloud.githubusercontent.com/assets/11293969/7789627/418c27c8-0268-11e5-930c-aba91c6179c0.png)
![snimek z 2015-05-24 22 55 01](https://cloud.githubusercontent.com/assets/11293969/7789628/418dc68c-0268-11e5-8526-d18932607e2f.png)
![snimek z 2015-05-24 22 55 08](https://cloud.githubusercontent.com/assets/11293969/7789630/418ffe02-0268-11e5-9de5-95a08720262c.png)
![snimek z 2015-05-24 22 55 12](https://cloud.githubusercontent.com/assets/11293969/7789631/419f2f80-0268-11e5-8820-54f4f7ff2862.png)
![snimek z 2015-05-24 22 55 23](https://cloud.githubusercontent.com/assets/11293969/7789632/41a3183e-0268-11e5-9c07-d79e83c88d2b.png)
![snimek z 2015-05-24 22 55 30](https://cloud.githubusercontent.com/assets/11293969/7789633/41a6405e-0268-11e5-8549-bc26c296b23a.png)

**Comment by jskorepa** [comment]
When replaced with following (functionally identical) setup using itemducts it does not occur anymore.
![snimek z 2015-05-24 23 07 17](https://cloud.githubusercontent.com/assets/11293969/7789688/c307a2f4-0269-11e5-85cb-b0dd4cb03228.png)

**Comment by thatsIch** [comment]
can you upload this test world please.

**Comment by yueh** [comment]
I cannot really recognise much thanks to the FoV setting. But there is at least a loop through the inscribers and that may end up using the storage buses on the inscribers to store the imported items.

**Comment by raven0ak** [comment]
that seems loosely problem I have with redstone dust ending into silicon press with most like culprit being another AE2 item: interface:) I somehow guess that AE2 inscribers have underlying problem with item acceptance from another AE2 item( other mods whitelists seem work flawless at not allowing wrong items trough)

**Comment by Lodran** [comment]
I've found that if I connect a storage bus to an inscriber, and configure it to bi-directional, the ME system will insert whatever random new items come into the inscriber.  The workaround is to configure the storage bus to be extract only.
