### ISSUE TITLE
multiple meteorites

### ISSUE THREAD

**Issue by french-gamer** [AppliedEnergistics/Applied-Energistics-2#1508]
I have found loads of meteorites in very close proximity. I am not sure if it was just luck or if it is a bug.
It happened on my single player world with 23 mods.

**Comment by thatsIch** [comment]
there is a high chance for meteorites to build clusters, clusters are generally around 3 meteorites.

**Comment by french-gamer** [comment]
Thank you for explaining that to me. I must of just been very lucky to find so many.
