### ISSUE TITLE
AE stops after placing autocrafting setup.

### ISSUE THREAD

**Issue by BladeSlayer1000** [AppliedEnergistics/Applied-Energistics-2#1509]
Dear all,

Currently me and a friend of my experience some issues with the autocrafting. After we changed the setup. The setup is as followed;
![setup1](https://cloud.githubusercontent.com/assets/12450371/7799962/142dc9f2-030e-11e5-8798-f28e4a48c2ae.png)
The black wire shown goes to the autocrafting setup, and straight to the storage drives.
The purple whire goes to the crafting co-processors and then strait to the me drives.

![setup2](https://cloud.githubusercontent.com/assets/12450371/7799963/1505d8f6-030e-11e5-94de-df948a080963.png)
A picture of my me drives setup.

The problem we have is at the moment that we add 6 or more molecular assemblers or interfaces the whole ae system freezes and stops working. With that I mean crafting, importing, and exporting items.

We have channels disabled on the server.

**Comment by BladeSlayer1000** [comment]
Some aditional information. We use the direwolf20 pack from the FTB launcher version 1.3.1 
The server log (latest) shows no errors or something else.

**Comment by thatsIch** [comment]
Closing this in favor of https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1510

**Comment by yueh** [comment]
If it is exactly 6, how many total devices has the network?

**Comment by BladeSlayer1000** [comment]
Currently I have;
![devices](https://cloud.githubusercontent.com/assets/12450371/7801004/66b730d6-031e-11e5-94dd-786e60599a7c.png)
