### ISSUE TITLE
Crafting Monitor shows a list of all Crafting CPUs

### ISSUE THREAD

**Issue by thatsIch** [AppliedEnergistics/Applied-Energistics-2#1511]
currently you have to toggle through all CPUs

extracted from https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1484

**Comment by dominx** [comment]
This is a very good idea. I dreamed about it for months. Please do it.

**Comment by ceasefyre** [comment]
+1
This, and also perhaps prevent the currently viewed Crafting CPU from auto-switching when other (non-viewed) CPUs finish thus altering the CPU list. Makes it hard to cancel that one recipe when it keeps jumping positions so often.

**Comment by Technici4n** [comment]
This was implemented in the 10.0 versions.
