### ISSUE TITLE
Wrenching micro blocks ignores canceled interact events.

### ISSUE THREAD

**Issue by Slind14** [AppliedEnergistics/Applied-Energistics-2#1515]
Hey,

you can wrench micro blocks like cables even when the interact event is being canceled. Previously this only worked with the network tool. Is there a reason that the event is being ignored now?

If not, could be re-implemented?

**Comment by yueh** [comment]
#645

**Comment by Slind14** [comment]
@yueh thanks for linking this, I wasn't able to find. Unfortunately it doesn't answer why this changed as it worked fine in the past. Would you mind to explain what was changed and why, as it worked fine before (with interact)?
