### ISSUE TITLE
Crash report with ThermalExpansion

### ISSUE THREAD

**Issue by linkinkov** [AppliedEnergistics/Applied-Energistics-2#1516]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 5/26/15 3:28 PM
Description: Exception in server tick loop

java.lang.ArrayIndexOutOfBoundsException: 7
	at cofh.thermalexpansion.block.TileAugmentable.func_94128_d(TileAugmentable.java:366)
	at appeng.util.Platform.generateTileHash(Platform.java:1648)
	at appeng.parts.automation.PartSharedItemBus.getHandler(PartSharedItemBus.java:110)
	at appeng.parts.automation.PartExportBus.isSleeping(PartExportBus.java:267)
	at appeng.parts.automation.PartExportBus.getTickingRequest(PartExportBus.java:261)
	at appeng.me.cache.TickManagerCache.addNode(TickManagerCache.java:159)
	at appeng.me.GridCacheWrapper.addNode(GridCacheWrapper.java:55)
	at appeng.me.Grid.add(Grid.java:205)
	at appeng.me.GridNode.setGrid(GridNode.java:255)
	at appeng.me.Grid.<init>(Grid.java:71)
	at appeng.me.GridNode.getInternalGrid(GridNode.java:150)
	at appeng.me.GridNode.updateState(GridNode.java:217)
	at appeng.me.helpers.AENetworkProxy.getNode(AENetworkProxy.java:150)
	at appeng.me.helpers.AENetworkProxy.onReady(AENetworkProxy.java:141)
	at appeng.parts.AEBasePart.addToWorld(AEBasePart.java:309)
	at appeng.parts.CableBusContainer.addToWorld(CableBusContainer.java:605)
	at appeng.tile.networking.TileCableBus.onReady(TileCableBus.java:221)
	at appeng.hooks.TickHandler.onTick(TickHandler.java:231)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_125_TickHandler_onTick_TickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:252)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:851)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 3.2.0-4-amd64
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2684417256 bytes (2560 MB) / 4527226880 bytes (4317 MB) up to 9343336448 bytes (8910 MB)
	JVM Flags: 2 total; -Xms1024M -Xmx10024M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.88.1307 git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218 (MC: 1.7.10) (API v1.7.10-R0.1-SNAPSHOT) Minecraft Forge 10.13.2.1307 50 mods loaded, 50 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.88.1307} [Forge Mod Loader] (industry2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1307} [Minecraft Forge] (industry2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	appliedenergistics2-core{rv2-stable-1} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Aroma1997Core{1.0.2.13} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.4.95} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.95-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IC2{2.2.718-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.718.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] ([15]AdvancedSolarPanel-1.7.10-3.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AdvancedMachines{1.1.3} [IC2 Advanced Machines Addon] (AdvancedMachinesAS-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	appliedenergistics2{rv2-stable-1} [Applied Energistics 2] (appliedenergistics2-rv2-stable-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Aroma1997CoreHelper{1.0.2.13} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHCore{1.7.10R3.0.2} [CoFH Core] (CoFHCore-[1.7.10]3.0.2-262.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0-81.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.1-182.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Core{6.4.13} [BuildCraft] (buildcraft-6.4.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Builders{6.4.13} [BC Builders] (buildcraft-6.4.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Energy{6.4.13} [BC Energy] (buildcraft-6.4.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Factory{6.4.13} [BC Factory] (buildcraft-6.4.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Transport{6.4.13} [BC Transport] (buildcraft-6.4.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Silicon{6.4.13} [BC Silicon] (buildcraft-6.4.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	chisel{1.5.7} [Chisel] (Chisel-1.7.10-1.5.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	EnderIO{1.7.10-2.2.8.0} [Ender IO] (enderio-1.7.10-2.2.8.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forestry{3.5.4.13} [Forestry for Minecraft] (forestry_1.7.10-3.5.4.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite-1.7.10-2.0.3server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IC2NuclearControl{2.2.1a-Yolo} [Nuclear Control 2] (IC2NuclearControl-2.2.1a-Yolo.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (miningworld.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NetherOres{1.7.10R2.3.0} [Nether Ores] (NetherOres-[1.7.10]2.3.0-12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	PowerUtils{1.7.10-1.0.4} [PowerUtils] (PowerUtils-1.7.10-1.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMultipart{1.1.2.334} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.334-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MrTJPCoreMod{1.0.6.13} [MrTJPCore] (MrTJPCore-1.0.6.13-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Core{4.6.0.79} [ProjectRed] (ProjectRed-1.7.10-4.6.0.79-Base.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Transmission{4.6.0.79} [ProjectRed-Transmission] (ProjectRed-1.7.10-4.6.0.79-Integration.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Exploration{4.6.0.79} [ProjectRed-Exploration] (ProjectRed-1.7.10-4.6.0.79-World.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Compatibility{4.6.0.79} [ProjectRed-Compatibility] (ProjectRed-1.7.10-4.6.0.79-Compat.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Integration{4.6.0.79} [ProjectRed-Integration] (ProjectRed-1.7.10-4.6.0.79-Integration.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Illumination{4.6.0.79} [ProjectRed-Illumination] (ProjectRed-1.7.10-4.6.0.79-Lighting.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	rfdrills{1.2.2} [RFDrills] (RFDrills-1.7.10-1.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	simplyjetpacks{1.4.1} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalDynamics{1.7.10R1.0.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.0.0-122.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	wawla{1.2.1} [What Are We Looking At] (Wawla-1.2.1_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	McMultipart{1.1.2.334} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.334-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	zzzzzcustomconfigs{2.2.0} [ZZZZZ Custom Configs] (CustomConfigs-2.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMicroblock{1.1.2.334} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.334-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AE2 Version: stable rv2-stable-1 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.0.2-262
	ThermalFoundation: -[1.7.10]1.0.0-81
	ThermalExpansion: -[1.7.10]4.0.1-182
	NetherOres: -[1.7.10]2.3.0-12
	ThermalDynamics: -[1.7.10]1.0.0-122
	Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Bukkit, Cauldron, or other Bukkit replacement
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
Info: The following plugins have been disabled in the config: mail, extrautilities, equivelent.exchange, harvestcraft, magicalcrops
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:OFF, BC:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 42 / 100; [EntityPlayerMP['valdek'/273, l='world', x=3693.70, y=69.85, z=1764.30](valdek at 3693.699999988079,69.85225396050471,1764.300000011921), EntityPlayerMP['Ex1mik3'/526, l='world', x=-3268.09, y=141.50, z=1360.43](Ex1mik3 at -3268.0939122103177,141.5,1360.4263655530842), EntityPlayerMP['DeadCat'/585, l='world', x=7582.02, y=71.00, z=1941.09](DeadCat at 7582.023952039003,71.0,1941.0916911090076), EntityPlayerMP['Assassinss'/593, l='world', x=690.02, y=69.34, z=-1553.61](Assassinss at 690.0203496795991,69.33971555078223,-1553.6076620989386), EntityPlayerMP['Kirill_Volker'/784, l='world', x=3180.33, y=58.92, z=34.51](Kirill_Volker at 3180.32575067688,58.92159999847412,34.51342592746479), EntityPlayerMP['andryha200'/786, l='world', x=-168.71, y=66.00, z=-158.23](andryha200 at -168.7141781823928,66.0,-158.2345095019459), EntityPlayerMP['ChattyDude'/843, l='world', x=3325.86, y=63.00, z=349.37](ChattyDude at 3325.862284466106,63.0,349.3698842953775), EntityPlayerMP['Fizik13'/842, l='world', x=317.87, y=65.00, z=591.68](Fizik13 at 317.86656890924326,65.0,591.6816518289589), EntityPlayerMP['mozila'/1386, l='world', x=245.16, y=55.00, z=-1885.04](mozila at 245.1560134135182,55.0,-1885.040686949424), EntityPlayerMP['Ubica_iz_ada'/1326, l='world', x=-170.94, y=71.00, z=-160.29](Ubica_iz_ada at -170.9391045556211,71.0,-160.28957264228498), EntityPlayerMP['DEVA'/824, l='world', x=1587.48, y=64.00, z=496.34](DEVA at 1587.4847225222122,64.0,496.34068731981307), EntityPlayerMP['saric'/1633, l='world', x=-119.30, y=69.00, z=-144.47](saric at -119.30000001192093,69.0,-144.4747021054722), EntityPlayerMP['roiur80'/1733, l='world', x=255.01, y=61.00, z=342.27](roiur80 at 255.0141974867867,61.0,342.2681520638063), EntityPlayerMP['ZiNGoR'/1843, l='world', x=5232.01, y=67.00, z=4017.55](ZiNGoR at 5232.013544341496,67.0,4017.55419618182), EntityPlayerMP['Kemuri'/2677, l='world', x=671.75, y=63.00, z=1344.51](Kemuri at 671.7519421660057,63.0,1344.5136099388426), EntityPlayerMP['adrian349'/2718, l='world', x=-7621.30, y=63.00, z=1981.77](adrian349 at -7621.296529361402,63.0,1981.7732664318858), EntityPlayerMP['MarikMarik'/2861, l='DIM6', x=874.98, y=14.00, z=427.32](MarikMarik at 874.9848382139655,14.0,427.32044205754937), EntityPlayerMP['NITRO'/3069, l='world', x=1600.24, y=64.00, z=496.74](NITRO at 1600.244385514592,64.0,496.74448427162815), EntityPlayerMP['BatareuyikA'/3160, l='world', x=886.08, y=6.00, z=408.68](BatareuyikA at 886.082652480867,6.0,408.6802508502928), EntityPlayerMP['MaGaMeD'/3233, l='world', x=2074.34, y=11.00, z=-3376.19](MaGaMeD at 2074.3410829935046,11.0,-3376.191571962314), EntityPlayerMP['Doctor007'/1642, l='world', x=5606.84, y=95.24, z=-5259.58](Doctor007 at 5606.841671974234,95.23981936616575,-5259.5776394379845), EntityPlayerMP['kuner'/3423, l='world', x=388.09, y=58.00, z=-2098.47](kuner at 388.09475735065143,58.0,-2098.4697757295075), EntityPlayerMP['Genius56'/3545, l='world', x=-4900.47, y=78.00, z=622.10](Genius56 at -4900.471307597248,78.0,622.1011021189514), EntityPlayerMP['vlad_shahter'/3680, l='world', x=296.63, y=69.00, z=-660.34](vlad_shahter at 296.6265499286763,69.0,-660.3412343405552), EntityPlayerMP['homeworld'/3893, l='world', x=-4906.14, y=82.43, z=615.75](homeworld at -4906.135840791711,82.43152384527073,615.7494857698165), EntityPlayerMP['WizZRifT'/3955, l='world', x=1491.56, y=54.00, z=441.50](WizZRifT at 1491.558712938129,54.0,441.50174476220275), EntityPlayerMP['Nikita10Polyakov'/3997, l='world', x=453.74, y=70.00, z=-465.07](Nikita10Polyakov at 453.74454560540653,70.0,-465.07397473607006), EntityPlayerMP['Dexter'/4269, l='world', x=2026.54, y=66.00, z=671.96](Dexter at 2026.5417965274798,66.0,671.9633822289036), EntityPlayerMP['ReactorCore'/5129, l='world', x=859.47, y=56.00, z=-1715.04](ReactorCore at 859.4730555523837,56.0,-1715.037973897124), EntityPlayerMP['vitalik932'/5131, l='world', x=-6308.51, y=71.00, z=1959.70](vitalik932 at -6308.512499988079,71.0,1959.699999988079), EntityPlayerMP['mofyer'/5580, l='world', x=6265.00, y=13.00, z=-302.33](mofyer at 6265.000851518051,13.0,-302.32775651307173), EntityPlayerMP['Nasu'/5589, l='world', x=196.30, y=35.00, z=1040.95](Nasu at 196.30000001192093,35.0,1040.949110058774), EntityPlayerMP['Durable'/6234, l='world', x=-149.85, y=11.00, z=978.64](Durable at -149.84631431445874,11.0,978.6365055403327), EntityPlayerMP['DETKA_GAMER'/6821, l='world', x=4301.17, y=70.00, z=-3513.08](DETKA_GAMER at 4301.168134733612,70.0,-3513.077716438699), EntityPlayerMP['lookan'/7541, l='world', x=2172.70, y=7.00, z=517.72](lookan at 2172.699999988079,7.0,517.7224697184446), EntityPlayerMP['betillo456'/7734, l='world', x=491.50, y=156.00, z=500.50](betillo456 at 491.5,156.0,500.5), EntityPlayerMP['Elite'/7737, l='world', x=3678.61, y=65.42, z=1795.49](Elite at 3678.612953318835,65.41999998688698,1795.486592951972), EntityPlayerMP['LoboMalo'/8072, l='world', x=4302.18, y=76.00, z=-3724.17](LoboMalo at 4302.1845797979095,76.0,-3724.1682741087247), EntityPlayerMP['GrandEarl'/8411, l='world', x=-3635.20, y=67.20, z=-6463.93](GrandEarl at -3635.1979119308808,67.20000004768372,-6463.925000011921), EntityPlayerMP['Hardishka'/8632, l='world', x=909.30, y=66.17, z=-2307.04](Hardishka at 909.3028208728065,66.16610926093821,-2307.0358588209465), EntityPlayerMP['DjVladko'/9056, l='world', x=2108.17, y=54.27, z=-1282.70](DjVladko at 2108.173620283317,54.271778952361984,-1282.699999988079), EntityPlayerMP['EfimVlad999'/9271, l='world', x=3195.69, y=59.00, z=-3412.95](EfimVlad999 at 3195.685172644718,59.0,-3412.9475045469007)]
	Is Modded: Definitely; Server brand changed to 'cauldron,craftbukkit,mcpc,fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by yueh** [comment]
Cauldron issue as they break some forge classes..

**Comment by linkinkov** [comment]
Its problem to AE from ThermalExpanson, cauldron dont care

**Comment by yueh** [comment]
Something is modifying `ForgeDirection.VALID_DIRECTIONS` and adding `INVALID` as valid direction, which is completely wrong and will cause issues.

All I know for now is that all reports I am remembering, did contain cauldron. Mabye it is another mod.
But neither AE2 or TE, we are just the ones who suffer from it.
I can only recommend actually debugging it and find which one is the actual culprit.
