### ISSUE TITLE
Crafting Card Slot for Pattern Terminal

### ISSUE THREAD

**Issue by ProRedHD** [AppliedEnergistics/Applied-Energistics-2#1518]
My Idea would be if you put a crafting card into a new Crafting Card slot in the pattern terminal, it will automatically craft blank patterns (if recipe is available) and put them into the correct slot. 

-ProRed

**Comment by FireBall1725** [comment]
I like the idea of coming up with a way to have blank patterns inserted into the terminal automatically

**Comment by yueh** [comment]
#119
