### ISSUE TITLE
AE2 missing Assembler block

### ISSUE THREAD

**Issue by Sasszem** [AppliedEnergistics/Applied-Energistics-2#1523]
I downloaded the AE2 for 1.7.2, but I couldn't find the *molecular assembler* block. I searched on the wiki, but I couldn't find the *history* of this block, like, when was this added... I don't know, it's a bug or there isn't MA in my version? Please add ***history*** to the wiki for all the blocks & items!

**Comment by Melriken** [comment]
Autocrafting was a fairly late ae1 feature to be added to ae2, it is not available in versions that old. 

http://minecraft.curseforge.com/mc-mods/223794-applied-energistics-2/files
There are change logs on curse, they may help you figure out what features are missing for your version

**Comment by TheJulianJES** [comment]
@Sasszem Many things don't work in 1.7.2, consider updating to 1.7.10 and use the latest version (currently rv2 stable 3)

**Comment by Sasszem** [comment]
Thanks!
I can not  update(some of my favourite mods isn't released for 1.7.10, but they'll). Now I has got enderIO installed, I can imagine an Auto-craft system w/ it...
