### ISSUE TITLE
Duplication bug with ae2 if used with Steve’s addones

### ISSUE THREAD

**Issue by zed-hex** [AppliedEnergistics/Applied-Energistics-2#1530]
There is a major duplication bug when ae is used with Steve’s add-ons I don’t know  who’s side the issue is but I thought I better report it here as well.

Here is a copy of the original report:
There is a duplication bug with the energistics connecter when it pulls items from a subnet that has a security terminal. Here is a print screen of how this can be replicated: http://prntscr.com/7alo3n (the manager has just a simple input output code) this bug was found when I was using build: 0.10.9 of Steve’s Addons

Other relevant mods to bug:
Steve’s factory A93
AE2 rv2 stable 3
 
And here is the link to the original report: https://github.com/hilburn/StevesAddons/issues/64#issuecomment-106731869

**Comment by yueh** [comment]
I doubt this is an AE2 bug. If the API is correctly used it will prevent someone from extracting items and not ignoring that it failed.

There is one particularly smelly/buggy looking piece of code. But I will add this the original issue.
