### ISSUE TITLE
Silicon Inscriber Failure

### ISSUE THREAD

**Issue by Scorpinox** [AppliedEnergistics/Applied-Energistics-2#1531]
I am having issues trying to automatic chip production in beta 33 (and all other versions I tried). When I try to setup an automatic production, the first chip or two works fine, then it fails. Checking the system shows that the silicon isn't processing, and is instead bouncing from 1% to 4% indefinitely. Replacing the block does not fix it, but moving the inscriber corrects the issue for a few runs. The inscriber is getting enough power, it never loses for than 10-20 rf during the process (according to WAILA).It also causes major server side lag while it is glitching, healthy inscribers do not cause the issue. Only the silicon inscriber has this issue. I am using the latest COFH core and latest mekanism, along with fastcraft and the big magic mods, blood magic, thaumcraft, ars magica.

**Comment by yueh** [comment]
Inscribers usually reset their progress on inventory changes. Are you sure that your setup not constantly swaps the items around?

No idea about the performance issue on the server side without more information. It would be really helpful, if you can profile it on the server. For further information look [here](http://ae-mod.info/Profiling/).

**Comment by mindforger** [comment]
i can confirm this issue with the rv3 stable3 release, whenever there is an item in the output slot, blocking the current "processing pattern" the process starts and get stuck with a full "power bar" and continously draws power from the system

**Comment by yueh** [comment]
Did you read the issue as you describe something completely different?

But yes, if the output is blocked, the machine will continue to run until it is able to move craft the item.
I do not really see it as necessity to stop it from consuming power. It is fairly reasonable to assume it still needs power to check the output or to keep the pressure as it is already only consuming power to prepare the pressing and not for the actual action itself. (From a "lore" point of view)

**Comment by mindforger** [comment]
i am sorry i did not read close enough, i wanted to post my own issue but this kinda fit best in. 
Every other processing machine i know so far will not start any conversion process when the output slot is blocked and more important, never will consume power then. The way AE2 is working with the inscriber feels odd to the rest of the world imho ;)

**Comment by sensisamurai** [comment]
Sounds like a problem I got in Agrarian Skies 2. If you are running automation with Steve's factory manager, I cannot help you. But if you are running your automatization with Thermal expansion then try to replace itemducts with ?warpitemducts?(don't remember if name is correct, but anyway the ones that transfer items instantly) with servos whitelisting the things you want). Note that you want to import from top, bottom, and back to the one that is combining silicon press with redstone and processor part.

**Comment by Lodran** [comment]
Sounds similar to the problem I encountered:

https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1563
