### ISSUE TITLE
Middle-click crafting not initiating properly

### ISSUE THREAD

**Issue by icewindow** [AppliedEnergistics/Applied-Energistics-2#1533]
**The Problem**
Initiating a crafting job by middle-clicking on an item brings up an empty amount selector (3rd image). Clicking next in that dialog does nothing. It doesn't matter if more of the item to be crafted are already stored in the system or not.

**What was expected?**
The amount selector should show up like when left-clicking (2nd image).

**How to reproduce the problem?**
Middle-click on an item with a crafting recipe stored.

**Server or Single Player?**
Both

**Mod Pack using and version?**
Direwold20 1.7.10 modpack version 1.3.1 with AE2-rv2-stable3. We also have ExtraCells version 2.2.70b119 installed on our server.

**Screen shots or Pictures of the problem**
http://imgur.com/pLyaoNM,JCMF4u9,nCYw2XK

**Comment by XFactHD** [comment]
I am seeing the same thing, but only sometimes and only when computer has been running for so long that the game begins to become laggy.

**Comment by thatsIch** [comment]
wth..

**Comment by thatsIch** [comment]
Can not reproduce
