### ISSUE TITLE
API for meteors

### ISSUE THREAD

**Issue by thatsIch** [AppliedEnergistics/Applied-Energistics-2#1538]
Could publish where there are, or alter them somehow.
Feel free to suggest stuff.

**Comment by Lodran** [comment]
It seems as though the skyblock crowd could use a means to spawn a meteor, perhaps as a step in a quest chain.

**Comment by thatsIch** [comment]
sounds more like a suggestion for map makers?
we do not make the quests.

**Comment by FireBall1725** [comment]
I think being able to add items to them, like how the forge api for the loot chests.
