### ISSUE TITLE
DUPE MAJOR

### ISSUE THREAD

**Issue by MrHelp** [AppliedEnergistics/Applied-Energistics-2#1540]
Look at the video.
http://www.youtube.com/watch?v=zw0_ET6LgZM&feature=youtu.be
Sorry for Russian language and mobile video(it is create people on my server)
So let me translate the video.
He have AE2 and he see chunks.in 1 chunk he add stable ae network and after hee go to the new chunks and add more items(you can see it). After he go in crafttable AE and craft diamonds. He go restart client and see dupe.

Sorry for my English too ;)

**Comment by yueh** [comment]
#1430
