### ISSUE TITLE
AE Multiblock's not working (Bug)

### ISSUE THREAD

**Issue by Sinora1** [AppliedEnergistics/Applied-Energistics-2#1542]
I'm on a LAN Server with my sister (just the 2 of us) and logged on one day and she couldn't put in or take out items from the AE system, She could however see the items inside and I could still use it fine. Also if she took the terminal and tried to place it back it just pings back off again.

So as a test i broke one of the AE autocrafting multi-blocks, and when the block is placed back(to form the multiblock again) it pings the surrounding blocks off into item form.

Sorry if this is already a known issue i couldn't find anything about it anywhere at all.
Any help is appreciated.

**Comment by thatsIch** [comment]
Sounds like a security issue

**Comment by Sinora1** [comment]
Pretty sure i fixed it, My sister(and her laptop) aren't around to test it, but in the world save in AE config, 2 players were listed one equaled 1 the other 0, Swapped them round and then i couldnt access it, so I'm gonna go ahead and say its fixed.

Thanks for the reply, I have no idea how it happened anyway though, i didn't change anything in the config before, it just kind of started acting up.

Once again, Thanks :)
