### ISSUE TITLE
Not able to check items in the inscriber's middle slot using SFM

### ISSUE THREAD

**Issue by AoKMiKeY** [AppliedEnergistics/Applied-Energistics-2#1544]
So i have been trying to do early automation with AE2's inscribers. I got it all working and then found that when i wanted to check if there was a item in the middle slot of the inscriber SFM would always think that there is nothing there. I have had the same system working fine inputting the items but I can not pull the items out or check if they exist in that one inventory slot.

I should be able to pull the item out using SFM and check for its existence. 

Preview of what i am doing to achieve this:
http://gyazo.com/21a2cc880c6bf24592eced6101ecafde
http://gyazo.com/26a0e6545d186573a918e861e9f73ad4
http://gyazo.com/f0fe0120abd785f9868f329a2f11e956

The program does a simple if on the inscriber and checks to see if it contains redstone ( of which it does ) then it will attempt to pull the redstone out. but will not be able to.

**Comment by Entoarox** [comment]
The middle slot is only available for insertion, as the output slot occupies the iSidedness of the inscriber for extraction, it is thus impossible to check the middle slot (And with proper SFM design, is also unneeded)

**Comment by AoKMiKeY** [comment]
Then let me put it this way. I am a programmer and have been for many years. There is no logical reason on why I am unable to check if there is a item in that slot. I do not care for removing it. I simply need to see if it is there. So why am I unable to do something that makes complete sense? 

If this does not get sorted I will fix it myself and just make a pull request but I would rather someone that knows the AE2 source code can do it.

**Comment by yueh** [comment]
@Entoarox is not completely right. The inscriber announces all its inventory including the middle input slot. So the sides are actually announcing the middle input slot and the output slot.

But extraction is restricted to the output slot only. This can be easily checked by attaching a storage bus + terminal to an inscriber and set the "Report Inaccessible items" accordingly. When set to yes it will also show the input slot in the terminal. (No is the default).

So this is most likely a SFM bug (or "feature" depending on the view point).
When I consider the dupe bug with steve addons, it is probably caused be the design flaw finally enabling duping any item reported by the inscriber (or network in regards to steves addons).
As far as I understand the SFM code/concept, it treats every reported item as usable, but it is actually copying/duping the item and afterwards nicely asking the inventory to remove this item, which of course can fail. So limiting it to only extractable items is probably the safe guard to prevent this.

**Comment by AoKMiKeY** [comment]
Okay, thanks for getting back to me although I have already had a big thing with the guy over at steve addons says it was AE2 fault. So looks like this will not be getting solved.

I know i could do it will AE2 but i was looking at early game automaton. I had this perfect program to handle it all but the very important part where if would only remove the press if there was no item in the middle slot did not work. There for on the last item when it saw there was nothing left in the chest it would remove the press before the last item and been pressed. Did a lot of debugging and its either SFM, AE2 or SA.

https://github.com/hilburn/StevesAddons/issues/69

**Comment by yueh** [comment]
I currently cannot think of any mod providing something similar to a terminal + storage bus to easily display other inventories.
Maybe some coding with ComputerCraft or OpenComputers?

But if you look at the source code for `TileInscriber`, you will notice that `getAccessibleSlotsBySide()` returns both slots. `2` is the input and `3`. But `canExtractItem()` is only not allowing anything being extracted from `2`.

**Comment by AoKMiKeY** [comment]
Okay. I am just annoyed that i can not do "IF slot 2 has item"? true | false Very annoying :P Thanks though. I think it is a sfm bug. I am going to look into making a Computercraft program for it :)

**Comment by Entoarox** [comment]
@yueh I meant the extraction part, but perhaps I was unclear as to what I meant with the iSidedness (I meant the ability to attach pipes/conduits/stuff and insert/extract with them)

SFM does not actually HAVE the ability to check if an item exists in a slot, it checks if an item can be extracted from a slot, thus with the middle insert slot not having the ability to be extracted, SFM is unable to see the contents of that slot.

**Comment by AoKMiKeY** [comment]
That makes perfect sense thank you :)
