### ISSUE TITLE
License discrepancy

### ISSUE THREAD

**Issue by joepie91** [AppliedEnergistics/Applied-Energistics-2#1546]
The [license in the repository](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/LICENSE) states that AE2 is distributed under the LGPL, but the text on the site states:

> This mod (plugin, patch to Minecraft source, henceforth "Mod" or "The Mod"), by the terms of http://minecraft.net/terms is the sole property of the Mod author (AlgorithmX2, henceforth "Owner" or "The Owner"). By default it may only be distributed on its own from http://ae-mod.info . It may not be distributed on its own from any other source unless given explicit permission. It may be included in any modpack with other mods, as long as it does not attempt to make money off The Owner's Mods. URL shorteners or other attempts to make money off The Owner's Mods are strictly forbidden without advance written permission. Attempts to modify the Mod, and distribute modified versions are Strictly Prohibited, reguardless of the modifications in question.

... but these two licenses are incompatible. Can you clarify on which license applies, and update the repository/website accordingly?

**Comment by AlgorithmX2** [comment]
The jars we release are licensed using the license on the website, the source based on the licensed included with the file, MIT for appeng.api and for the remainder of the code LGPL, and CC BY-NC-SA for the assets.

I've attempted to clarify this in the license on the website.

**Comment by joepie91** [comment]
Alright, that's clearer. There's a typo though - it says 'complied' on the site, that should probably be 'compiled' :)

**Comment by AlgorithmX2** [comment]
Whoops fixed, Closing.

**Comment by magnusjjj** [comment]
You do realize that having it licensed as lgpl means that people are free to ignore those extra restrictions?

"If the Program as you
received it, or any part of it, contains a notice stating that it is
governed by this License along with a term that is a further
restriction, you may remove that term."

As in, if you remove those permissions on the website, anyone is freely allowed to not give a fuck about it :). You are still allowed to claim that its a fact, but, nobody is required to abide by it.

**Comment by yueh** [comment]
You realise, that you talk about a completely different license, which does not apply at all?

**Comment by magnusjjj** [comment]
Both the creative commons license, the mit license, and the lgpl license allows you to ignore further restrictions placed on the work. If your work only contains work licensed under those licenses people are allowed to ignored restrictions placed on that work :). Or are there other parts in the mod contained only in the released jars? :)

**Comment by magnusjjj** [comment]
Like I said, I just think its pointless and confusing license wise. But if you want to scare people into not being twats by writing that, I guess that's cool :).

**Comment by yueh** [comment]
But they do not allow you to ignore the licenses themselves. So you can still not make money due to the CC NC for assets.

The only exception is being able to distribute it yourself according to the MIT + LGPL + CC NC-BY-SA construct (which is fine).

Nevertheless, the license on the website is still correct, because older versions are still "all rights reserved" (rv0, rv1 and maybe some rv2). The license change only happend at some point during rv2, but I cannot remeber when exactly.

**Comment by magnusjjj** [comment]
Sure!

Thats the only thing I reacted over really :). The non-distribution part. (Writing a compile-open-source-mods util, so going through all of the mods from the major modpacks and peeking at licenses. Every single mod is licensed differently, some with.. really wierd stuff attached to them while still saying that its licensed under CC/gpl :). Going slightly nuts.)

Sorry for wasting your time, only wanted to double check on the non-distribution part.
