### ISSUE TITLE
Issue in Agrarian Skies 2

### ISSUE THREAD

**Issue by ThexXTURBOXx** [AppliedEnergistics/Applied-Energistics-2#1547]
I have set up a server for Agrarian Skies 2 using Applied Energistics 2 rv2-stable-3.
When I restart the server, the world saves and the server starts again.
When the server is preparing the start area, then the server says the following:
http://pastebin.com/QZzikkRi
The crash-report:
http://pastebin.com/gvx59bLM

**Comment by yueh** [comment]
Did you update the pack and also did anyone use P2P tunnels. Not just the ME ones but also RF or fluid?

**Comment by thatsIch** [comment]
#1474
