### ISSUE TITLE
AE2 achievements crash attempting to render disabled item

### ISSUE THREAD

**Issue by wjrogers** [AppliedEnergistics/Applied-Energistics-2#1550]
Viewing the AE2 achievements in the achievement GUI crashed when I panned the achievement window to the right. I'm not sure exactly which item causes this, but I've disabled channels, grinder, and inscriber.

config:
https://dl.dropboxusercontent.com/u/26070/AppliedEnergistics2.cfg

crash log:
https://dl.dropboxusercontent.com/u/26070/ae2_achievement_crash.log

**Comment by thatsIch** [comment]
#1474
