### ISSUE TITLE
"Shaped IC2 Crafting" not pulling items from storage buses when shift clicking recipe from NEI

### ISSUE THREAD

**Issue by 016Nojr** [AppliedEnergistics/Applied-Energistics-2#1552]
When I attempt to shift click a "Shaped IC2 Crafting" recipe from NEI it only places the IndustrialCraft 2 items in the crafting "window", nothing else.

Mod versions:
appliedenergistics2-rv2-stable-4
CodeChickenCore-1.7.10-1.0.6.43-universal
industrialcraft-2-2.2.730-experimental
Jabba-1.2.1a_1.7.10
NotEnoughItems-1.7.10-1.0.4.107-universal

![2015-06-05_19 31 11](https://cloud.githubusercontent.com/assets/8192699/8011552/daf1759e-0bb9-11e5-8098-8e2246e1df9a.png)
![2015-06-05_19 31 07](https://cloud.githubusercontent.com/assets/8192699/8011550/daed75f2-0bb9-11e5-8037-72c6c558b6fd.png)
![2015-06-05_19 31 21](https://cloud.githubusercontent.com/assets/8192699/8011551/daefd1e4-0bb9-11e5-8807-a17d40f51f49.png)

**Comment by TheJulianJES** [comment]
@016Nojr Could you please try this in rv2 stable 5?

**Comment by 016Nojr** [comment]
Repeated same process in rv2 stable 5, not working.

**Comment by oks1998** [comment]
rv2 stable 6 also not working.....and when auto crafting the solar distiller using ae2, it show me in the chat there: crafting tree construction failed

**Comment by 016Nojr** [comment]
That is happening to me with "Transformer Upgrades" aswell @oks1998

**Comment by oks1998** [comment]
but if u create a pattern for the recipe it can craft it...it just cannot shift click the ? in nei and put all the stuff automatic on the crafting table

**Comment by thatsIch** [comment]
probably like #1581

**Comment by yueh** [comment]
It is pretty similar, but this is something we could fix on our side (without breaking stuff).

As everyone knows, using glass or iron ingots to hit zombies will slowly damage these items like any other weapon, thus the IC2 recipes are not asking for the undamaged item, but are using the Oredict wildcard to match any damaged itemstack of these undamagable items.

We could probably change the NEI handler to accept the wildcard on undamageable items.
I could imagine that one mod adds some damagable item with a matching oredict name and we might miss these then. But I currently cannot think of any mod doing it, to actually test it.
