### ISSUE TITLE
Spatial Containment Structure and Big Reactors

### ISSUE THREAD

**Issue by spitfire1081** [AppliedEnergistics/Applied-Energistics-2#1553]
Hi
I am running several tests with this amazing feature, the SCS (Spatial Containment Structure) and Spatial Storage.
O noticed that the Big Reactor structure won't be transported to another dimension.
Is that possible to fix this?

**Comment by yueh** [comment]
BR needs to whitelist their TileEntites to be moveable with SpatialIO. This is done to prevent it from corrupting your world. As some of them will cause this.

There can also still be a couple of bugs. For example the last time I tried moving them they will shut down after being moved. So without some option to remotely reactive them or enter the dimension, they will no longer produce energy. In case of turbines it was not even possible to reactive them without access to the turbine GUI.
