### ISSUE TITLE
Formation Plane doesn't place blocks

### ISSUE THREAD

**Issue by XFactHD** [AppliedEnergistics/Applied-Energistics-2#1554]
I set up a Botania Living Rock and Living Wood farm with annihilation and formation planes and I am shutting either one or the other of with toggle busses. When I configure the formation plane to place wood or stone, it won't place it. As soon as I bring some movement into my system by building a loop with an export bus and an interface, the formation plane places the blocks.
I am currently using rv2 beta 30, but over the weekend I will try if rv2 stable 5 fixed it and then I will come back to you.

**Comment by yueh** [comment]
I recommend reading the wiki page about formation planes.

**Comment by XFactHD** [comment]
I just read it now and I will do some testing this weekend if this works for me.
