### ISSUE TITLE
Can't place cable facade on pattern terminal

### ISSUE THREAD

**Issue by grauerkoala** [AppliedEnergistics/Applied-Energistics-2#1556]
Hello,
while trying to pretty up my setup, I ran into an issue: I can't place cable facades on pattern terminals like I can on other terminals like the crafting terminal. The terminal is active and connected to the network; there are no microblocks anywhere in the space occupied by the cable to which the pattern terminal is attached. Attaching a facade to any other side of the cable in question works just fine.
I noticed this behaviour in rv2.beta build 8 and have since upgraded to rv2.stable build 5.
If requested I will try and provide any kind of information necessary.

-koala

**Comment by thatsIch** [comment]
Works fine for me


just remember, that you have to replace the cable, if it was ever a FMP

---

![2015-06-06_13 59 57](https://cloud.githubusercontent.com/assets/2210496/8019539/67756ee0-0c54-11e5-9c4d-a1a4813cae61.png)

**Comment by grauerkoala** [comment]
Thank you, that did it! I had forgotten to also replace the cable anchor within the same block space.
