### ISSUE TITLE
Molecular Assembler hangs after Power Loss/Surge

### ISSUE THREAD

**Issue by mindforger** [AppliedEnergistics/Applied-Energistics-2#1562]
i chained up 7+4 molecular assemblers to bake me octuple compressed cobblestone
7 for each stage of compressed cobble and 4 additional to initially make the compressed cobble from regular cobble, fed by igneous extruders (resonant, full augmented)

when i restart the server while an assembler is in a crafting process, it seems to freeze and not recover on server startup! Region is chunkloaded with ChickenChunkloader

i could yet not reproduce this on every startup as it is quiet impossible to shutdown the server fast enough to assure the crafting is in progress
ADDITIONALLY: The molecular assembler is not starting a new crafting process and does not consume power while the outputslot is blocked! As i stated in another Issue, the Inscriber is very unconsistent in this behaviour to most of all other mods, vanilla and other components in AE2.

EDIT: sorry i forgot to mention, running on stable r3, r5 not yet tested, will update soon

**Comment by yueh** [comment]
Assemblers do not keep their progress between world unloads, they just reset and start fresh.

Can you try it with another chunkloader? As the Chicken Chunkloader are known to cause different issues.

**Comment by mindforger** [comment]
i would probably blame chicken chunks at this point. it happened again when i changed dimensions this time, while the chicken loader on large size is double loaded by an world anchor the MA outside the world anchor got stuck again ... i'll try to reproduce this with less mods and report it to chickenbones then

**Comment by mindforger** [comment]
okay, i updated and fiddled out, it was an power issue! i was using quiet more power than expected. Especially when then chunk loaded, it seemed to run out of power on a random MA and then the process got stuck! Only way to restart the process was removing the pattern and reinserting it

**Comment by mindforger** [comment]
sorry as i made out not clear enough that i see this behaviour as an error/bug! Why will the MA freeze when it looses its power?
To reproduce, place a line of MAs, each following requireing the input of the MA before (in my case compressed cobble) and fire it with about 50% of the needed power .. at some point one of the MAs will stall but not restart, even if there is enough power to continue!
PS i used a lot of acceleration cards in the first stage of 3 MAs for compressed and a full accelerated MA for double compressed

**Comment by yueh** [comment]
Still cannot reproduce it. I have similar setups with normal autocrafting as well as dumping items into the assemblers directly. Disconnecting the power multiple times during the crafting operation (at different percentages) never got one of them stuck.
They might take 1 or 2 seconds to resume, but that is caused as the network rebuilds itself after reconnecting the power.

**Comment by mindforger** [comment]
"They might take 1 or 2 seconds to resume, but that is caused as the network rebuilds itself after reconnecting the power."
ah okay THIS could be my issue then! surge -> net offline -> accumulate power -> power on -> surge -> net offline -> repeat ... with a little of server lag this is indeed possibly looking like a certain MA is stuck forever ... and the power cells fixed it then
