### ISSUE TITLE
About ME Storage Monitor display

### ISSUE THREAD

**Issue by bakaxyf** [AppliedEnergistics/Applied-Energistics-2#1564]
ME Storage Monitor display
https://cloud.githubusercontent.com/assets/10368307/7987383/b92c2ed6-0b0f-11e5-9f40-ba3878d5cc23.gif

**Comment by TheJulianJES** [comment]
@bakaxyf I would recommend making this two separate issues :)

**Comment by bakaxyf** [comment]
Okey and thank for your recommendation

**Comment by thatsIch** [comment]
Cant reproduce this in the latest version? What is your whole setup?

**Comment by bakaxyf** [comment]
The bug still exist ,but I don't kown how to reproduce.I will upload the save.

**Comment by bakaxyf** [comment]
http://www.mediafire.com/download/g0b7d6ap5wsza52/save.rar

**Comment by bakaxyf** [comment]
And also happen at place which can connect to ME network.[gif](https://drive.google.com/file/d/0B3ftECsjucqQWE1HZXJZN0hvY0E/view)

**Comment by thatsIch** [comment]
Will look into this tomorrow or this weekend
