### ISSUE TITLE
storage bus attached to an interface

### ISSUE THREAD

**Issue by Turmfalke2** [AppliedEnergistics/Applied-Energistics-2#1566]
This works: http://ibin.co/24eiKAL52t4S

This does not: http://ibin.co/24eicaQssTXk

Playing ags2 with ae2 appliedenergistics2-rv2-stable-3.jar

**Comment by yueh** [comment]
Works for me.
![part storagebus/interface](http://i.imgur.com/tilVPQd.png)

**Comment by thatsIch** [comment]
maybe you should tell us, how you define **not working**
