### ISSUE TITLE
pams harvest craft cakes not placeable as blocks with formation planes.

### ISSUE THREAD

**Issue by Zacuis** [AppliedEnergistics/Applied-Energistics-2#1568]
Im not sure that this can be classed as a bug with AE2 as pams cakes appear to be different from vanilla cakes, in NEI they have 2 versions.

none the less it would be very nice to be able to place them as blocks via AE2

**Comment by thatsIch** [comment]
mh, feature request I guess?

**Comment by Blue64** [comment]
I tried to set up an automatic Tree Farm, but couldn't get the Formation Plane to pull out the Saplings from the Network (was using standard Oak). worked on a normal chest connected to the network though. Have you attempted this on a closed network with external storage (such as a vanilla chest)?

**Comment by wlhlm** [comment]
@Blue64 You have to remember that Formation Planes act similar to Storage Buses and drop items when they are _added_ to the network. A good way to set them up is using a sub-network in which you export from another ME Network (or Pipes).

I'm not sure how you built the tree farm, but the following works like a charm:
![METreeFarm](https://cloud.githubusercontent.com/assets/1928113/11250414/bc1ffc44-8e2c-11e5-84fb-99d1527da04e.png)

Export Bus → Interface (in sub-network with Formation Plane)

**Comment by Blue64** [comment]
That looks severely laggy.
