### ISSUE TITLE
AE Stocking system causes network to show completely blank

### ISSUE THREAD

**Issue by theit8514** [AppliedEnergistics/Applied-Energistics-2#1570]
I'm running into an issue where withdrawing an item which is kept stocked using a ME Storage Bus hooked to a ME Interface + Crafting Card causes my entire network to show no items in it. When the issue is replicated, items from storage buses and ME Drives are not showing; I can't even see the craftable items in the Molecular Assemblers.

I have created [this album](http://imgur.com/a/bL6IA) documenting the issue, but I will explain my setup here.

I have a controller set up with 8 dense cables going out to P2P interfaces. 4 of the P2P interfaces are configured, the others are not configured. Off of one of the P2P outputs, I have two Interfaces hooked up to a Storage Bus each configured with a Crafting Card and a configuration or each item I want to keep stocked. For debugging purposes, I have a CC computer hooked to an interface outputting the number of items visible in the system.

To reproduce the issue, I remove one of the 6 Engineering Processors from the system to start a crafting of a Engineering Processor. About 5 to 10 seconds later once the crafting system has crafted the processor, the terminal flashes the Engineering Processors up to 6, then the Engineering Processors disappear entirely.

Once I close the terminal and open it back up, there are zero items showing in the system. The CC computer confirms that no items are visible. I checked that all of the channels are in use and there is enough power, but the system is completely empty. In order to reset, I have to remove a storage cell from the ME Drive and replace it. The Network tool also shows that nothing is different from before the issue.

I am using FTB Infinity 1.6.2 (AE2 is rv2-stable-3) with additional mods: EnderIO updated to 388 beta, Soul Shards:TOW 0.1 RC9-7, Tinker's Steelworks 1.1.0-14, Extra Cells 2 2.2.71b121.

I have tried for about an hour now to replicate the issue in a test world, but I have been unable to do so. I thought it might be an issue with a 1k Storage Cell configured with Engineering Processors, but I am experiencing the issue with other items in the 'keep stocked' system (ie, removing a stack of Fluix dust, which takes items stored in a storage cell and tries to load them into the interface but almost immediately triggers the issue).

**Comment by mindforger** [comment]
just in case, "enough power" includes having installed a few AE Energy Cells? As The System may need more power for a certain action than you are able to put into it!

**Comment by thatsIch** [comment]
Can you manually update to the latest AE2 version and try it again?

**Comment by theit8514** [comment]
TBH, the Energy Cells were from a previous adventure trying to import items into a cell in a ME Chest (about 30 stacks at a time). I just added them to the base for the cool factor. I'm generating 24 kRF/t from a Turbine, so I doubt it is a power issue. I will update to the latest version and test when I get home tonight.

**Comment by theit8514** [comment]
After testing stable-6 for 6-7 iterations, I find that the issue is no longer there. I did find a small issue which I could not replicate but for the first time I attempted the test in which [the interface contents did not match the contents in the system](http://imgur.com/a/e9l08). I believe this issue can be closed.

**Comment by thatsIch** [comment]
You can close it yourself, if you believe so.

**Comment by theit8514** [comment]
Apologies, I had a dev that wanted to keep tickets open so they're easier to find. I'll mark as closed.
