### ISSUE TITLE
Repeated crash related to Exception in thread "AE2 VersionChecker" AL lib: (EE) alc_cleanup: 1 device not closed

### ISSUE THREAD

**Issue by zarkophine** [AppliedEnergistics/Applied-Energistics-2#1572]
We are putting together a pack and having and issue just this crash. We can run it at at times then it will crash in middle of play. It will also just crash Minecraft entirely when trying to load single player world that was working moments before. 

Crash report: http://paste.ee/p/3zx1d

**Comment by yueh** [comment]
See #1397 for an explanation of this message.

Otherwise it looks like a cofh issue.

**Comment by zarkophine** [comment]
It does not show any way how to fix this issue. It might help if you guys posted what version of forge works best with your version of the Mod.

**Comment by thatsIch** [comment]
`10.13.2.1291`
