### ISSUE TITLE
Prevent ME Storage Bus from extracting certain items from its connected inventory block

### ISSUE THREAD

**Issue by Lodran** [AppliedEnergistics/Applied-Energistics-2#1573]
[quote]The UI allows you to control which items are selected as storable items, this selection has no effect on what items can be extracted once they are in the storage.[/quote]

In Agrarian Skies 2, most gears must now be manufactured on a casting table, which is a time consuming process.  As a result, I've been experimenting with a method of maintaining a fixed stock of gears, which will automatically refill itself when the stock is consumed.

The method is as such - feed a source of liquid metal into a casting table that contains a gear template.  Pull the completed gears out of the casting table with a hopper, which has 4 of its slots blocked with cobble.  Connect a storage bus to the hopper, so that it's contents will be shown in ME storage.

The problem is that regardless of whether the storage bus is configured to accept cobble, the ME system will remove the cobble blockers when cobble is requested for any random crafting operation.

My suggestion is that if the storage bus is configured to only accept particular items, then only those items should be visible to the ME system, and only those items should be extractable by the ME system.

**Comment by yueh** [comment]
#330.
But it is really not the job for a storage bus to filter the inventory, just what can enter it.
Else it will also break too many useful builds.

**Comment by vallard192** [comment]
Wouldn't it be possible to work around this by changing the priority of the
storage bus?

**Comment by Lodran** [comment]
Just as a matter of curiosity, I'd like to see an example of the sort of build it would break - I suspect there's a design opportunity there that I'm missing.
