### ISSUE TITLE
Weird generation

### ISSUE THREAD

**Issue by xJon** [AppliedEnergistics/Applied-Energistics-2#1576]
What causes that? Is it the crater, and is there any way to fix this kind of stuff from happening?
![image](https://cloud.githubusercontent.com/assets/8945347/8106659/dbf1d1a0-104b-11e5-97fe-7ac580030073.png)

**Comment by Un-Serious-Gamer** [comment]
It looks like your chunks are a bit messed up. Are you using any other mods? From here it looks like you first loaded the chunks in one direction, then went the long way around without loading the chunk where the village is, and then loaded up to that village chunk from the second direction. As you can see the village looks to be in a snow biome from the farm crops, whereas the landscape around the village chunk is completely snowless.

**Comment by yueh** [comment]
Probably just a race condition between the order of generation for a village and meteor.
There are enough of these cases even with vanilla, like overlapping dungeons/strongholds etc.

The only way to prevent it, is really not use any randomly generated terrain and design everything by hand. Like mcedit, worldedit or similar tools.

**Comment by xJon** [comment]
@Un-Serious-Gamer Yes, a lot, including Fastcraft.
@yueh So you don't think it has anything related to Applied Energistics, or any other mod? Basically Minecraft's way?

**Comment by yueh** [comment]
It just some strange interaction issue. Meteors are generated at least 1 tick after the actual chunk is generated. 
But I have no idea if something like FastCraft (or just forge) could also postpone chunk generation/decoration a bit and then clashing with the meteor generation.

If you just regenerate the world with the same seed, the outcome would most likely be a completely different one. It might not even generate a meteor in this exact location.
So yeah. It is just the way minecraft handles world gen.

**Comment by Un-Serious-Gamer** [comment]
Yes, I believe this is just minecraft's way. However if you are using a modpack, you should check to see if this chunk overlapping is common. It looks like you have Natura or a similar mod installed. Is this working and stable?

**Comment by xJon** [comment]
@Un-Serious-Gamer I'm using my modpack, and I didn't see anything like it, ever
I guess it's indeed Minecraft's way.
It's weird, but I don't think I can get a better answer.

Thanks!
