### ISSUE TITLE
Validate Item Metadata before entering system or notify user of invalid items in the system

### ISSUE THREAD

**Issue by nogamenofun98** [AppliedEnergistics/Applied-Energistics-2#1581]
![2015-06-12_17 34 06](https://cloud.githubusercontent.com/assets/9070825/8128006/c8538f02-112d-11e5-83ca-9b6337a26ee2.png)

can put it into the ae2 system but cannot take it out 
(shift click also cannot, right click also cannot, left click also cannot)
only can taken out by give 1 that item to me and put it into the crafting table in ae2 and take out the rest

**Comment by mindforger** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/951

this one's old, what versions of AE2 and IC2 are you using?

**Comment by oks1998** [comment]
appliedenergistics2-rv2-stable-6
industrialcraft-2-2.2.736-experimental

all is latest version right?

**Comment by yueh** [comment]
To add a bit more insight to it. The old issue basically already states what is the issue but without any real explanation.

Basically what is happening here is that IC2 breaks the metadata, which will only be stored as short, so only `-32,768 to 32,767` are valid values. Even if the code itself works around an int (mostly for convenience)
Now that IC2 is using way higher values, these will actually be truncated and end up being stored with a different metadata, thus making it a different item.

But there is still the original item displayed in the terminal (with the invalid metadata) and when you try to extract these items, it will actually not find them in the storage. Making it impossible to extract the existing ones.

**Comment by thatsIch** [comment]
Just saw, 280k metadata?

Could add this as bug + wontfix as the other IC2 bug

**Comment by oks1998** [comment]
So this is ic2 problem and need to report to ic2?

**Comment by thatsIch** [comment]
At least it seems to break the common usage of Metadata
(assuming 32768 < 274978)

**Comment by joeltine** [comment]
FWIW, I opened an issue with IC: http://bt.industrial-craft.net/view.php?id=1685

**Comment by thatsIch** [comment]
Other workaround is to validate the item before entering the system
