### ISSUE TITLE
Can't Craft AE2 Facades

### ISSUE THREAD

**Issue by gabor6505** [AppliedEnergistics/Applied-Energistics-2#1584]
Hi all, I am playing with Agrarian Skies 2, and I have this issue since I upgraded the pack to 1.1.5.
This occurs in both Singleplayer and on my private Multiplayer server.

So I simply can't "assemble" it, the Facades are shown up in the NEI (because I disabled InPureCore) and it shows recipes too (4 Cable Anchor - and a Block), but I can't Shift+? Click it to place the ingredients in any kind of Crafting Grid (I tried Crafting Tables, Crafting Stations, ME Crafting Terminals and ME Pattern Terminals, and none seems to work) and if I try to put the ingredients manually, it just don't show up the facade, so I can not even see it. I can still get it from the Creative Tab, or from NEI, and I can use them.

I actually only tried with some blocks, but I think none of the blocks will work (for me).

Versions:
Forge 1401,
Applied Energistics RV2 Stable 5
CodeChickenCore (1.0.6.43)
NotEnoughItems (1.0.4.107)

And I have 3 more AE2 related mods installed:
Ender IO (2.2.8.381)
AE2 Stuff (0.3.1.33)
Thaumic Energistics (0.8.10.5)

(Sorry if I was too complicated or if my grammar is not correct)

Screenshots:

Singleplayer:
![2015-06-12_13 39 23](https://cloud.githubusercontent.com/assets/12859334/8129452/9e46e1e2-1109-11e5-87f0-a6bd4b231cc8.png)
![2015-06-12_13 42 19](https://cloud.githubusercontent.com/assets/12859334/8129484/e44ef648-1109-11e5-8aae-1621614a7d8a.png)

![2015-06-12_13 40 08](https://cloud.githubusercontent.com/assets/12859334/8129499/1370552a-110a-11e5-9473-cec4eca7a0c3.png)
![2015-06-12_13 43 02](https://cloud.githubusercontent.com/assets/12859334/8129532/583d6e0e-110a-11e5-93c5-31ba264e704c.png)
![2015-06-12_13 43 06](https://cloud.githubusercontent.com/assets/12859334/8129533/58400826-110a-11e5-8772-f7a1064e5835.png)

Multiplayer (I have some facade left in my AE system because I cheated in with NEI and in the previous versions the crafting worked):
![2015-06-12_14 48 30](https://cloud.githubusercontent.com/assets/12859334/8130415/50334a0a-1112-11e5-94e9-abd35e40bcdb.png)
![2015-06-12_14 58 15](https://cloud.githubusercontent.com/assets/12859334/8130538/7af9161a-1113-11e5-8ae2-d21f139ec910.png)

**Comment by thatsIch** [comment]
Sounds like AS2 is configured that way.
You can only see the facades, cause you disabled another mod.

**Comment by gabor6505** [comment]
I only disabled 1 mod, InPureCore, but as Jadedcat said, it's optional and I don't want it to hide half of the stuff from NEI. I will look into the mods, because I added some to the pack.
What should I do ? Maybe ask in the AS2 forum that it is intented or not ?

**Comment by yueh** [comment]
In general it is a better idea to ask the modpack author, because these should be aware of bugs or changed features. Especially with heavily modded packs like AS2. Even if the config for AE2 looks fine, something like minetweaker can still mess with the recipes.

**Comment by gabor6505** [comment]
Okay, I now tested it with AE2 Stable 1 and Stable 6, and I still cannot craft facades. I also tested it with a fresh AS2 install (1.1.5) and it's still not work, I also tested it with a fresh Forge 1401 setup + AE2 and it worked in that. So there is problem with the default mods in the pack itself. Thanks for the help, I will ask it on the modpack's Bug Tracker.
