### ISSUE TITLE
Add per-terminal Text Memory to Terminals

### ISSUE THREAD

**Issue by WBittner** [AppliedEnergistics/Applied-Energistics-2#1586]
I typically find myself leaving terminals mid-use to go craft something and then coming back and having to re-search is a bit of a hassle. If/when time/effort is available if there could be a config option to have terminals remember their text (one text per terminal remembered), I know a few people that would enjoy that feature a lot. This will also help users who refuse to use the "Sync with NEI" option, as entering a terminal effectively wipes your previous NEI search. 

I understand that there is not a ton of feature development happening with the port to 1.8 and all, but I just wanted to throw this on here for easier tracking.

**Comment by Technici4n** [comment]
Was implemented years ago.

**Comment by Technici4n** [comment]
Not going to be implemented due to technical issues.
