### ISSUE TITLE
Toggle Bus state indication by color

### ISSUE THREAD

**Issue by mjevans** [AppliedEnergistics/Applied-Energistics-2#1587]
After seeing it in your stream just now, I think you might find this feature request useful.

Toggle Bus state indication by color.

Perhaps render an indicator as Red if there is redstone signal (if it should be enabled, but there's no power).

If the toggle is allowing power and has power, a different color, maybe yellow (like glowstone yellow), could indicate that it's active.  This would hopefully be visibly different for most colorblind users, while still making sense to the rest of us.

**Comment by yueh** [comment]
I do not know which stream you have seen, but any toggle bus has an indicator about their state.

It does not have an indicator without the network being powered. But this applies to any other indicator, like cells in drives. So it makes no sense to break the consistency.
