### ISSUE TITLE
Charged Certus Quartz Ore has same name as Certus Quartz Ore

### ISSUE THREAD

**Issue by JentheGeek** [AppliedEnergistics/Applied-Energistics-2#1588]
Minecraft: 1.7.1
JABBA,1.2.1
AppliedEnergetics2 (rv2-beta-18)
Infinity 1.7 Mod Pack

OreDictionary Dump via NEI shows:
oreCertusQuartz,1xtile.appliedenergistics2.OreQuartz@0,appliedenergistics2:tile.OreQuartz,Certus Quartz Ore,false
oreCertusQuartz,1xtile.appliedenergistics2.OreQuartzCharged@0,appliedenergistics2:tile.OreQuartzCharged,Charged Certus Quartz Ore,false

Because of the same item name (oreCertusQuartz), sorting with other mods such as JABBA does not occur correctly.

**Comment by thatsIch** [comment]
Cause both are the same block, just a different metadata/state,

your reasoning would imply, that oak wood and spruce wood is stored the same in Jabba (basically it replaces either of them with the other)
