### ISSUE TITLE
Import Bus on Funky Locomotion Frame Issue

### ISSUE THREAD

**Issue by iovideogiochi** [AppliedEnergistics/Applied-Energistics-2#1589]
The ME Import Bus with a Redstone Card upgrade on "Active with signal", placed on a  frame from "Funky Locomotion" , will import items in the network, even if no redstone signal is given,  every time the frame moves.
BTW Sorry for my English^^

**Comment by thatsIch** [comment]
Not sure if this is our issue, because we have no special interaction for FL,
maybe ask them?

**Comment by iovideogiochi** [comment]
I have contacted them and waiting for the response.i'll let you know when they contact me back.
