### ISSUE TITLE
Card that ignores NBT/Damage

### ISSUE THREAD

**Issue by Keridos** [AppliedEnergistics/Applied-Energistics-2#1594]
The Fuzzy card does not work for items with the same ID; but different meta and NBT data. Please add in a way to filter those per cards aswell.

**Comment by yueh** [comment]
For metadata see: #360, #1043

Otherwise a fuzzy card will ignore NBT data, but it still filters by damage first.
So the [rules](http://ae-mod.info/Fuzzy-Card/) for splitting by damage still apply.
To just ignore NBT data, `match any` is probably the best option.
