### ISSUE TITLE
The ME system deletes all items on display

### ISSUE THREAD

**Issue by Curren95** [AppliedEnergistics/Applied-Energistics-2#1598]
When i put items in the ME system the items disappear from the terminal, stay in my 1k storage. after about 20 items they get deleted. this is on single-player with other mods including tinkers construct, thermal expansion, extra utilities, Waila, etc... this is on the 1.7.10-Forge10.13.2.1347-1.7.10 version of Forge. hope it can be resolved soon. the me system will show the amount of a certain item if you put another one of that specific item in the system(unless it isn't stackable), and then it disappears if i go back into the terminal

**Comment by thatsIch** [comment]
Can you tell us the exact way to reproduce this, 
at best with the least minimal amount of mods in a fresh SSP world.

**Comment by Curren95** [comment]
sure just a sec.

**Comment by Curren95** [comment]
![2015-06-18_15 49 40](https://cloud.githubusercontent.com/assets/12887977/8244064/d4bcbb3a-15d1-11e5-8d71-cbf3a50dc72a.png)
![2015-06-18_15 49 44](https://cloud.githubusercontent.com/assets/12887977/8244065/d5ec874c-15d1-11e5-9f2a-14dfd77fc6d2.png)
![2015-06-18_15 49 51](https://cloud.githubusercontent.com/assets/12887977/8244071/dc106abc-15d1-11e5-94fb-6c3a60fac9d5.png)
![2015-06-18_15 49 56](https://cloud.githubusercontent.com/assets/12887977/8244077/e1eca7e8-15d1-11e5-952d-0c684c1a2c26.png)
![2015-06-18_15 50 14](https://cloud.githubusercontent.com/assets/12887977/8244078/e3017d16-15d1-11e5-89b1-c3ff6783325a.png)
![2015-06-18_15 50 16](https://cloud.githubusercontent.com/assets/12887977/8244080/e3f6ab1a-15d1-11e5-81a4-b5ba6bf9d0cc.png)
make a simple setup like this, put in about 20+ items in the teminal and go back to the terminal and they are gone.(this is in forge 1.7.10-Forge10.13.3.1401-1710ls, with Ap2 version 1.7.10)

**Comment by thatsIch** [comment]
Was it resolved? I did not take a look at this yet (no time)
