### ISSUE TITLE
WorldData fails to construct on creating new worlds

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#1599]
`WorldData` and corresponding classes like `PlayerData` are failing to construct when creating a new world.

This is caused by using `PreConditions` to enforcing the necessary folders and files to exist before these are actually created.

**Comment by thatsIch** [comment]
on rv2 or rv3?

**Comment by yueh** [comment]
rv3 as #1526 is not part of rv2.

`WorldData` already enforce the world folder to exist, so we can already create the necessary folders and files with the constructor. `File.mkdir()` already returns a boolean, which could be used as `PreConditions` or `assert`. The settings file is a bit more complicated as `File.createNewFile()` throws checked exceptions.

Additionally we can then remove the creation and validation from `WorldData.onServerStarting()`

**Comment by thatsIch** [comment]
meh obviously the API does not state that, it is not being created, when accessible

**Comment by thatsIch** [comment]
Also need to pay attention, cause it can also return `null`

**Comment by yueh** [comment]
The API for `File`?

**Comment by thatsIch** [comment]
for `DimensionManager`

**Comment by yueh** [comment]
Ah, ok. But we already ensure that this directoy is not null. 
Not sure when it could return null, except maybe on client only. But then `WorldData` is only constructed on servers.
