### ISSUE TITLE
Redstone Ideas

### ISSUE THREAD

**Issue by AlgorithmX2** [AppliedEnergistics/Applied-Energistics-2#16]
So the best feature I have seen so far from the trailer has been from RedBoss.  Got me thinking.  

What if you could upgrade level emitters?  Or somehow set them to like comparator mode?  Had analog.  :)  Or same for buses for when/when not to operate?  That one might be a lot trickier.

Anyway, thought it was a cool idea and it is like the first time I've ever check IRC and you were not there so passing it on here.  heh

Originally Posted by BevoLJ

This issue was migrated; For original details see http://ae-mod.info/Tracker/0103/

**Comment by yueh** [comment]
There is already a PR open for some more features, but I will most likely split it into two different ones.
The analog one (comparator mode) should be part of rv3.
Not sure about the scaling. This needs some rework.

**Comment by Technici4n** [comment]
Probably not going to happen unless someone comes up with a very detailed explanation of the feature, the GUI, etc.
