### ISSUE TITLE
Crash when shift-clicking covered or dense cable into a crafting table

### ISSUE THREAD

**Issue by xJon** [AppliedEnergistics/Applied-Energistics-2#1601]
Crash report: http://pastebin.com/kqTDsuPS
Very strange, started to happen only with the latest updates of NEI & AE2.
What causes that?

**Comment by thatsIch** [comment]
something is dividing by zero, so maybe downgrade NEI?

**Comment by xJon** [comment]
@thatsIch Yes I saw! I can try, although still it's weird how it happens only with items from AE2

**Comment by thatsIch** [comment]
btw, how can you shift click something into a crafting table?

**Comment by xJon** [comment]
@thatsIch Shift-clicking on the question mark in NEI to put the items in the currect placement into the crafting table.

**Comment by thatsIch** [comment]
that would have been a better problem explanation ;-)

so you basically shift-click a recipe **containing** a dense or covered cable into a crafting table.

**Comment by xJon** [comment]
@thatsIch Shift-click the recipe **of** dense of covered cable :)
Happens on normal crafting tables or special ones

**Comment by thatsIch** [comment]
we are slowly getting there..

testing right now

**Comment by xJon** [comment]
@thatsIch Huh, sorry for that
Thank you for the quick reply :)

**Comment by thatsIch** [comment]
confirmed.. pretty strange though why only on these recipes

**Comment by xJon** [comment]
:)
