### ISSUE TITLE
Removed Inscriber Press Recipie  -> Crash with NullPointerException

### ISSUE THREAD

**Issue by DerOli82** [AppliedEnergistics/Applied-Energistics-2#1602]
Minimal Setup:
- Forge: 10.13.3.1428
- Applied Energistics rv2 stable 5
- CodeChickenCore 1.0.7.46
- MineTweaker 3.0.9c
- ModTweaker 0.8.2
- NotEnoughItems 1.0.5.110

ModTweaker Script: http://pastebin.com/f9XXTgSJ
Crash-Report: http://pastebin.com/Cn4E122r

First i got no problems by looking up the Inscriber Press recipe in NEI. After sending /mt reload command the game crashs if i looking up the Inscriber Press recipe again.

**Comment by yueh** [comment]
The crash basically indicates that something insert null as recipe or a recipe with null as output.
Both should be prevented when using the AE2 Api and not trying to circumvent it and directly modifying internal classes.

Did you report it to ModTweaker? As these are the ones modifying it at runtime.
But then we did not really design it to be changed at runtime, so that might simply not be possible.

**Comment by DerOli82** [comment]
AE2 throws a NullPointerException and in my opinion it's necessary to check a null value or to catch the Exception. No matter who is to blame, it's better than a game crash.

If the game doesn't crash and the custom recipe doesn't work then it's his (ModTweaker) turn.

I've also opened an issue at modtweaker. Cross-Ref: https://github.com/jaredlll08/ModTweaker2/issues/154

**Comment by yueh** [comment]
AE is throwing the NPE on purpose because something is clearly broken and this should not be suppressed.
So it is either throwing a NPE directly or something like an `IIlegalStateException` when null.

**Comment by DerOli82** [comment]
I don't want to suppress it but in case of an broken recipe (only on /mt reload), i think an error log is enough.

**Comment by Zixxl** [comment]
Problem is, that the ```undo()``` operation was not implemented in ModTweaker2 for the Inscriber Press. A null value was inserted in the recipe list which caused the crash. Made a pull request to ModTweaker2 that fixes this problem.
