### ISSUE TITLE
Fuzzy Exporting for ME Interface

### ISSUE THREAD

**Issue by petabyteboy** [AppliedEnergistics/Applied-Energistics-2#1603]
The fuzzy card can't be placed in the interface, but the interface's export function also does not tolerate metadata difference from configured to real item. 
It should be possible to place a fuzzy card in an ME Interface in order to create a fuzzy exporting behaviour.

**Comment by yueh** [comment]
And how should it merge two different items?

**Comment by plumpudding** [comment]
what do you mean by merge? I mean that when there is a broken pickaxe in the config port and you put a brand new pickaxe into the slot below it should not pull that in and replace it.

**Comment by yueh** [comment]
Fuzzy also matches any oredict entry as well as ignoring NBT data.

So for example if you set it to keep a stack of copper A it can also use copper B, but these are still two different items. Should it start converting them into the configured item? Which also mean that anything which can stack when fully repaired can fetch any item from the network and just repair it to stack them.

**Comment by plumpudding** [comment]
for the first example: if the fuzzy comparasion says these are the same oredict: keep the one in there which is in there

**Comment by shartte** [comment]
Implemented by #5863
