### ISSUE TITLE
Meteor generator not work with Multiverse-generated world

### ISSUE THREAD

**Issue by noxowl** [AppliedEnergistics/Applied-Energistics-2#1605]
I'm using Multiverse-2.4 with KCauldron(Forge + Bukkit API). and added AE2 recently.
I didn't want remade my established world. so, make mining-only world with Multiverse.
But only generated AE2's material and Meteor generator doesn't work.

and I tested AE2 and Multiverse only server, It was same.

finally, I tried config's worldgen whitelist. but it was vain.

worldgen {
    D:meteoriteClusterChance=0.1
    I:meteoriteDimensionWhitelist <
        [worldname]
     >

**Comment by yueh** [comment]
You need to add the actual dimension id to the whitelist, not the name.
But there is also the chance that it does not work with this plugin at all.

**Comment by noxowl** [comment]
Thanks! the whitelisted dimension id is working.
