### ISSUE TITLE
Networks which you do not have the right to modify can sometimes be wrenched

### ISSUE THREAD

**Issue by kinnison** [AppliedEnergistics/Applied-Energistics-2#1606]
Hi,

I am running the DW20 1.2.1 pack (AE2 rv2-beta-pre9) so this may already have been fixed, but...

A friend on the server I'm on has a network which I have view-only access to.  E.g. I cannot
place blocks onto the network.  But I did manage to wrench one of his drives by mistake and now
I cannot put it back :-/

This seems sub-optimal.

D.

**Comment by yueh** [comment]
#735
