### ISSUE TITLE
Server crashes while loading or unloading chunks which contain ae.

### ISSUE THREAD

**Issue by Anikilulala** [AppliedEnergistics/Applied-Energistics-2#1608]
It happens while I try to login or logout at a chunk which contains several me-drivers of 1200 kinds of items and 500+ autocrafting patterns.
The server has its option removeErroringTileEntities=true and removeErroringEntities=true.So if fortunately I will find some cables (always cables) droped onto ground and the server does not crash,but most of the time, especially after a long time playing and trying to logout, the server crashes.The log says forge tried to remove an ae TileEntities and then stopped.

Using appliedenergistics2-rv2-stable-5 ,forge 1403.

**Comment by yueh** [comment]
How about posting the crashlog (on pastebin), so we can actually try to resolve it?

**Comment by Anikilulala** [comment]
Yes ,of course. I will tell the server administrator to set removeErroringTileEntities false and get crashlog next time.

**Comment by yueh** [comment]
Inactive, reopen when more information is available.
