### ISSUE TITLE
AE system does not detect storage cells

### ISSUE THREAD

**Issue by SkinHeadBaby** [AppliedEnergistics/Applied-Energistics-2#1611]
hello i updated applied energistics a few minutes ago and now if i use a toggle bus on my network to power it down and after i turn it on it doesnt detect the storage cells in the drive until i take 1 out and put it back in my system is small atm its just an energy acceptor dense energy a drive and a crafting terminal nothing else

**Comment by thatsIch** [comment]
define "doesnt detect" please

**Comment by SkinHeadBaby** [comment]
the storage cells are inside when i give power to the system they light on the interface but the terminal shows no items
when i take end one storage cell out of the drive and then put it inside again all works again util i flip the lever on the toggle bus
i downgraded to the previous version and it works now

**Comment by thatsIch** [comment]
downgraded to which? please help us to reproduce this issue

**Comment by SkinHeadBaby** [comment]
this issue happened with rv2-stable-9
i downgraded to rv2-stable-8 and it works

**Comment by thatsIch** [comment]
Cant reproduce, maybe share you rebuild in a fresh world, so I can rebuild it.

![2015-06-17_20 30 19](https://cloud.githubusercontent.com/assets/2210496/8215522/c01b659c-1530-11e5-844c-d18c38642b5a.png)

**Comment by SkinHeadBaby** [comment]
i guess i didnt explain it well enough
i didnt mean that the drives dont get detected on the rendering they do
they dont show inside the terminal
check these pictures i made and you can see on the background the lights on the drive
http://imgur.com/a/tsNbU
hope the titles of the pictures are clear enough
english isnt my mother language so my grammer is a bit poor

**Comment by phalantas** [comment]
I have a similar bug that showed up when I upgraded to stable-9. It looks like the ME drives thinks they don't have power. this usually happens when I leave the chunk for a bit (even though the site is chunkloaded). Unlike SkinHeadBaby I do not cut the power to the ME system

**Comment by phalantas** [comment]
I figured I should show my own screenshot of the issue, as you can see from the picture there is plenty of power on the energycell, the cables correctly sees the ME drives (and are not overloaded), yet the storage cells appear dark in the drive.
I also noticed that the ME interface that is on the same part of the network (that side of the controller) also becomes unresponsive.


![2015-06-18_16 40 20](https://cloud.githubusercontent.com/assets/12944145/8233944/60c56f3a-15d9-11e5-8d0d-f07ca7f149e2.png)

**Comment by SkinHeadBaby** [comment]
well i have a dense energy cell which is 1.6 mRF but the powers isnt the problem its just storage cells arent detected by the terminal

**Comment by thatsIch** [comment]
I wonder if this has something to do with the network fix of rv2 stable 5

**Comment by yueh** [comment]
I do not think so. The changed methods are only used inside `GridNode` itself and only allow the used channels to exceed 256 ones. The only other change is that these can now overflow and become negative. Which theoretically is possible, but when it happens than it is really a bug somewhere else.
The posted screenshots look like they did not disabled channels, so it can actually not exceed 32 channels.

And I was also not able to reproduce any of these setups.

**Comment by SkinHeadBaby** [comment]
well i didn't use anything else than applied energistics for the screenshots so it cant be something else
something changed from stable 8 to stable 9 version

**Comment by KindarConrath** [comment]
Hm, I just ran into the same issue, the ME drive randomly goes all grey lights as if its out of power or disconnected from the network.  I just have 1 ME Drive, 1 Controller, 1 Energy Acceptor, 1 inscriber and 2 crafting terminals on my network. (Plus a toggle bus that goes to 4 Crystal Growth Accelerators)

I have 
Forge 1472, 
AE2 rv2 stable-9
ExtraCells 2.2.73b129

**Comment by yueh** [comment]
If anyone is actually able to reproduce it in a reliable way, could they please test the build of #1668? (once the CI is done) 
I am still not able to reproduce it in any way.

**Comment by KindarConrath** [comment]
If I figure out a pattern to the bug, i'll do a test, but until then, i'm really not sure what causes it!

**Comment by KennyBurch** [comment]
AE2 rv2 stable9, I have been experiencing the issue. The closest commonality I have been able to determine is what 'phalantas' mentioned. I have my base chunkloaded with a ChickenChunks chunkloader. (1.3.4.19) and upon leaving the area or if I log off for a bit and log back in frequently all storage drives are no longer accessible on on the network.  my system.  For me, they show up as powered...just not there. Simply removing and re-installing a drive corrects that issue. (that or change priority of the drivebay).
![2015-07-01_19 45 30](https://cloud.githubusercontent.com/assets/13078744/8469091/d49b07bc-2029-11e5-95e8-a53236d6d83b.png)
![2015-07-01_19 47 20](https://cloud.githubusercontent.com/assets/13078744/8469102/01ef147e-202a-11e5-9946-37a0a825976b.png)

**Comment by yueh** [comment]
ChickenChunks had quite a few issue in the past as it behaves a bit strange and keeps chunks constantly reloading.

For example when I watch their GUI about the loaded chunks, a chunkloader set to 1 chunk will sometimes try to keep 5 chunks loaded in a plus shaped area. But the 4 additional chunks are unloaded after a couple of seconds and then immediately reloaded. If this happens fast enough and in the right order, then it might not fully unload the AE network, but keep it in some undefined state once they force loading the chunk. But this is something the PR build should handle now.

Not sure about the EnderIO conduits, but their approach to interact with AE is quite hacky. It seems to work in most situations, but I would not rely on it to work perfectly in every situation. So there might be a few issue in some corner cases.

**Comment by SkinHeadBaby** [comment]
I am curious if this happens without any other mods than AE why do you blame other mods i tested this with ae only i didnt even add not enough items

**Comment by yueh** [comment]
Not blaming them. It is most likely an issue related to constant chunk reloading. You can achieve this already with vanilla but it is way harder. ChickenChunks makes it way easier to achieve it, based on the observations. And as said we encountered some other issue with chickenchunks in the past, which changing to a different chunkloaders solved.

EnderIO is most likely not related to this issue, just their integration is a bit tricky and the more potential integration issues we need to consider, the harder it is to actually track these down. So excluding as many mods as possible from testing makes it easier.

**Comment by SkinHeadBaby** [comment]
Its not hard all you need is a toggle bus and a lever you dont have to go anywhere you just flip the lever off and on
 dont know if there are chunk loader issues with the mod i never experienced any with stable 8
and this issue i have is on stable 9
so for me the temporary fix is to use stable 8

**Comment by yueh** [comment]
Except none of us is able to reproduce it with a simple toggle bus.

**Comment by SkinHeadBaby** [comment]
Well  then can it be a problem with forge

**Comment by KennyBurch** [comment]
More testing....
I am able to reliably repeat this issue on my server. I can also repeat it on a copy of my server map played in local single player. I am still having a issues repeating it on a simple test world but I think I have found a way to reproduce the symptoms.(sometimes).
1) Move away from the spawn (since these chunks are always loaded....this delayed me greatly)
2) Set up a little enderchest import system as thus:
![ae2setup](https://cloud.githubusercontent.com/assets/13078744/8508244/c2b296b4-221d-11e5-9a90-d4920915cf7b.jpg)
3)Load up the ender chest with cobble and then teleport away.
4)Monitor the loaded chunks with /chunkloaders while watching the cobble get pulled into the system.  I noted that when the extra chunks near the force loaded chunks are purge, the cobble import stops briefly...then restarts. (Using the same monitoring, this chunk unload is the moment my normal world would stop talking to all storage drives)

I have been able to repeat this with forge  1.7.10-10.13.4.1481 and 1448.
ChickenChunks is currently my thoughts.  I was able to repeat this issue constantly with 1.3.4.19, I have just now rolled back to the recommended version 1.3.4.16 and so far have not had any issues. Will report back if I find out more.

**Comment by brian91292** [comment]
I may have figured out how to reproduce the issue of needed to remove/reinsert a cell from a drive to get the network to update.... without unloading any chunks. It's quite simple really.

Step 1:
Create a simple AE system with the drives p2p'd in.
![image](https://cloud.githubusercontent.com/assets/8050523/8513232/7c51c3ba-2327-11e5-8b3c-a40ed8b7546f.png)

Everything works fine so far...
![image](https://cloud.githubusercontent.com/assets/8050523/8513238/d17cfa1c-2327-11e5-8d00-5a4c0bc73807.png)

Step 2:
Create a second p2p tunnel, in this example I'll connect it to some crafting CPUs, but I don't think the contents of this second network matter. This is where everything goes wrong.... upon linking the second p2p network, the drives stop functioning.

![image](https://cloud.githubusercontent.com/assets/8050523/8513248/36a53b98-2328-11e5-9042-a5a6ce14f2cf.png)
![image](https://cloud.githubusercontent.com/assets/8050523/8513256/547fa95a-2328-11e5-9689-b88df8d695f3.png)

Upon further inspecting the smart cables connecting to the networks... everything appears to be working fine, everything has power, and we aren't using too many channels.

![image](https://cloud.githubusercontent.com/assets/8050523/8513266/94b4c2da-2328-11e5-9a4b-d1bc5fb81bdb.png)

Removing and reinserting one storage cell, appears to return access to all the storage on the network (although only the drive that you removed/reinserted the cell from shows as being visually powered again).

![image](https://cloud.githubusercontent.com/assets/8050523/8513269/cb53b2b0-2328-11e5-98bd-1e9236ec9a6f.png)
![image](https://cloud.githubusercontent.com/assets/8050523/8513272/d6d8387c-2328-11e5-902d-2df1cbee9364.png)

Playing on FTB Infinity 1.7.0, the AE build is rv2-stable-9

I hope this information helps in solving the problem.

**Comment by yueh** [comment]
I am still not able to reproduce it with a similar setup.

**Comment by brian91292** [comment]
That's unfortunate, guess I'll stick with the ghetto computercraft workaround to fix the problem.

It's really quite simple... I just made a program that applies a redstone signal to an item conduit which pulls a storage cell out and back into an ME drive... utilizing the startup computercraft program that is, so that this runs automatically when the server restarts or the chunk reloads. This seems to be a viable workaround for the problem until the issue can be pinpointed and resolved.

**Comment by yueh** [comment]
The workaround would be, if a few, who are able to reproduce it, would finally test the build I linked a couple of days ago. I am pretty convinced it will fix it, but as long as I cannot test it and do not get any feedback, I will not pull it and create a new build.

**Comment by brian91292** [comment]
I'll give it a shot, give me a bit though as I'm a complete noob to this.

**Comment by yueh** [comment]
Also the [direct link to the buid](http://ci.tsr.me/repository/download/AppliedEnergistics_PullRequests/3232:id/appliedenergistics2-rv3-alpha-pr1668.jar), as the CI took a while longer than anticipated and I could not link it, just the PR to then follow it to the CI.

**Comment by brian91292** [comment]
Lol, didn't see your direct link until after I had found it myself. On the new build now, upon linking the p2p tunnel the drives no longer disconnect, so it does seem like you've fixed it ;)

**Comment by KennyBurch** [comment]
I wasn't able to figure out how to pull the build for testing. 

But I can confirm the new v10 (when using the world that I was able to reproduce the issue reliably) the issue seems to be resolved.

Thanks everyone!
