### ISSUE TITLE
Pure Nether Quartz Crystal not growing

### ISSUE THREAD

**Issue by LordMortus** [AppliedEnergistics/Applied-Energistics-2#1613]
Using a modified Curse Forge installation of FTB Infinity and using 2 growth accelerators the nether quartz seeds grow to a max metadata of 4139:11 and the recipe for the calculation press needs 4139:10

I basically removed all IC2 mods, added Smart Moving and manually updated some mods
This issue started in stable-3 and has been recreated in stable9

**Comment by yueh** [comment]
So you are saying that nether quartz seeds are correctly growing to pure nether quartz as well as that calculation circuit require pure certus quartz as it is intented and for example displayed by our website or NEI?

**Comment by LordMortus** [comment]
Ok, I appologize..  I appear to be a complete dufus hehe
Sorry for the wasted post.   I don't know why I didn't notice that.. my mind was stuck on using nether crystals for some reason.
