### ISSUE TITLE
Fuzzy card does not handle IC2's Tiny dust piles

### ISSUE THREAD

**Issue by bence98** [AppliedEnergistics/Applied-Energistics-2#1616]
Basically, the same error occured to me as in [#360](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/360), just with the IC2 Tiny pile dusts.

Quote from yueh:
> If some other mod has damageable items and it seems to not work, please open a new issue regarding the specific issue.

**Comment by yueh** [comment]
These are not damageable.

**Comment by bence98** [comment]
What do you mean? They have subtypes
