### ISSUE TITLE
Opening an ME Terminal or ME Crafting Terminal with NEI installed crashes client

### ISSUE THREAD

**Issue by TechnicallyFatal** [AppliedEnergistics/Applied-Energistics-2#1622]
I wasn't sure if I should post this on the NEI thread or here, so I decided to do both.

The problem that is happening?
    I go to open anything to do with an ME system, and instantly crash
What was expected?
    Uhh... that I'd be able to open it without crashing..? .-.
How to reproduce the problem?
    It happens every time I open an AE2 inventory, Without fail, and occasionally other inventories as well, (ie player inv, and chests, though that's not usually the problem) (It WAS working fine, then I joined my singleplayer / LAN with a different player on the same computer (Not at the same time) and now it crashes for all but the original player.)
Server or Single Player?
    SP / LAN
Mod Pack using and version?
    It's... my own little private pack. It's been working fine until yesterday, though.
Crash log (Please make sure to use pastebin for the log file)
    http://pastebin.com/fu0MmGLz

**Comment by yueh** [comment]
How is it related to AE2, when NEI crashes on multiple different inventories from different mods and in a method which is only using its own data?

**Comment by TechnicallyFatal** [comment]
The crash log mentioned only NEI and AE2, so I posted to both, just incase one or the other knew what was up... So.. Sorry if it doesn't belong here.. :/

**Comment by deadgamer1030** [comment]
I had this happen when i updated botania. try deleting the NEI folder and configs( back them up if this doesn`t help). For me it was a problem with searching certain words in NEI.

**Comment by yueh** [comment]
Inactive
