### ISSUE TITLE
appeng.core.AppEng not found

### ISSUE THREAD

**Issue by Romooska** [AppliedEnergistics/Applied-Energistics-2#1623]
Ive installed the mod and it starts normally untill forge goes to phase 1 then it crashes with this report...    

http://pastebin.com/vy0ns0it

**Comment by yueh** [comment]
And by "normally" you mean you have unzipped it into the mods folder, which is quite the opposite of normally?

**Comment by Romooska** [comment]
...Yes thats how i did it with CodeChickenCore, NEI, and Optifine and those 3 loaded and i was able to play with them.

**Comment by mindforger** [comment]
if you follow the wiki on minecraft forge, it says "Typically you place them in the mods [...] folder" nothing states you should unpack them, as they are mostly already in ".jar", which are indeed a zip archives, but not intended to be unzipped

CCC and optifine are core mods and intentionally designed to even work aside the mod framework so i COULD be loaded while beeing unzipped ... NEI is a suprise to me, but you will have several duplicate files during unzipping other mods and that should have warned you earlier! do not unzip .jar files, just drop them into the mod folder! optifine is (the only) thing on its own!

**Comment by thatsIch** [comment]
Please try to install it described in our readme 

---

https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/README.md
