### ISSUE TITLE
Minecraft don't work

### ISSUE THREAD

**Issue by mattone96** [AppliedEnergistics/Applied-Energistics-2#1626]
Hello, I can't start my modpack. When I press to launch I see this log:
http://paste.ee/p/0K9EK
What can I do?

**Comment by mindforger** [comment]
why do you even post that here ? your texturestitcher exploded because of your textures beeing too big, this has nothing to do wit AE at all

**Comment by mattone96** [comment]
When I see "AE2 VersionChecker", I think that the problem was AE2.. Thanks for te supports, now I'm changing the settings.

**Comment by mindforger** [comment]
@aedevteam sorry for still posting to an closed non related topic again but i think this could prevent at least one guy posting issues without knowing what is going on :P
@mattone96 please be advised, the actual crash report ALWAYS starts after this line
---- Minecraft Crash Report ----
and a few lines later there is the actual source of the error .... 

the line you've seen indicates only a bit of a dirty shutdown in ae2 AFTER the actual crash
