### ISSUE TITLE
Charge Certus via Lightning

### ISSUE THREAD

**Issue by Timeslice42** [AppliedEnergistics/Applied-Energistics-2#1628]
In order to be able to remove charged certus quartz ore from my modpack and gate that behind other progression (in a different mod) I request that certus quartz struck by the lightning entity become charged certus instead of being destroyed. In order for this to work the charged certus would probably also have to be immune to fire.

An easier to code alternative may be certus ore struck by lightning becomes charged certus ore.

Is either of these possible?

**Comment by Timeslice42** [comment]
Actually, unless you really like the idea, go ahead and close this. I figured out how to do it with the other mod as a recipe.

**Comment by yueh** [comment]
#338
