### ISSUE TITLE
Pattern Terminal Terminal Style

### ISSUE THREAD

**Issue by Timeslice42** [AppliedEnergistics/Applied-Energistics-2#1629]
Currently the terminal style button on the pattern terminal does nothing. In the case of the pattern terminal being on it's own single channel ad-hoc network it would make sense if it toggled the GUI between the currently used GUI, and a pattern terminal only GUI, as in AE1.

**Comment by Timeslice42** [comment]
Okay, it turns out the style does nothing on the GUI scale that I'm using... however the feature request still stands.

**Comment by yueh** [comment]
A pattern terminal without access to your normal network is pretty much useless, except for 1 or maybe 2 cases.
You would have to run back to your normal terminal, put the needed items into your inventory, run back, encode the pattern and drop the items back into your normal network. For every single pattern.

The only exception is creative mode, where you can just spawn the required items.
But I doubt this is a large issue in this case.

**Comment by KlutzLament** [comment]
It would be AE1 all over again.

**Comment by Timeslice42** [comment]
It has exactly as many use cases as the pattern terminal in AE1.

**Comment by Timeslice42** [comment]
On a side note, is the pattern terminal meant to work when it has no power? This was pretty much the reason this came up in the first place. I was using a pattern buffer connected to nothing to make patterns, and I wanted to remove the useless terminal section from the GUI.

**Comment by yueh** [comment]
I did not consider that the NEI integration in AE1 was actually another mod. The encoder itself needed the items being placed manually. But the integration is now part of AE2.
It is rare that someone requests to remove a QoL feature :grinning:

**Comment by Timeslice42** [comment]
I'll bet :)
Well, l not so much remove, as toggle.
