### ISSUE TITLE
Recipes export/import buses/P2P

### ISSUE THREAD

**Issue by Carbon-Ghost** [AppliedEnergistics/Applied-Energistics-2#1631]
I have a question / request, is it possible to move around recipes requests ? By that I mean if I have an interface connected to a P2P or an export-import bus, can I have all my recipes going to the same block, like for exemple a bunch of ME interfaces, all pointing in P2P tunnels, which are all connected to a single P2P in the other side, that is connected to a processor block ( electric furnace, pulveriser, electrolyser, assembler.. etc.. ) ?

So far, as I tested, it doesn't seems to be working, have I done something wrong if it already exists ? If not, can we implement this feature ?

**Comment by thatsIch** [comment]
not sure if this works with the item P2P, but ME P2P, ME Interface (with pattern) - pointing to -> ME Interface -> ME P2P Input == ME P2P Output -> Storage Bus should suffice?

**Comment by Carbon-Ghost** [comment]
Erm, so wait, I am kinda confused, image if possible ?

From what I understood, it's ME interface to ( NEW ) ME P2P to another P2P and then processor ?

Sorry it's kinda confusing ^.^''

**Comment by Carbon-Ghost** [comment]
I think I understood, gonna test this once I have time, not sure if it will work though...
