### ISSUE TITLE
[SUGGESTION] cable chance

### ISSUE THREAD

**Issue by Goten87** [AppliedEnergistics/Applied-Energistics-2#1632]
i love to make my base nice looking and cool looking
i can do this with the new smart cabels
the problem is i dont like the channel system but i like the new cabels
can you not make a update that if we set the channels off that we can still make/use the smart cabels
i love to have the dense cable for my main line and stuff
but i dont want to have the channels
hope u will think about this if it even possibel to do
Greets Goten87

**Comment by yueh** [comment]
#1142

**Comment by Goten87** [comment]
so sad thats its not posebol :(
