### ISSUE TITLE
Crafting Interface gets stuck

### ISSUE THREAD

**Issue by Timeslice42** [AppliedEnergistics/Applied-Energistics-2#1636]
If an interface which is set up with a pattern for crafting in a chamber is also configured to autocraft that item the crafting will get stuck after crafting once.

http://imgur.com/np4UVy5
http://imgur.com/XiwoTkn

Pulling the crafted furnace out of the interface will cause that furnace not to be crafted until you clear the (new) crafting job. It will then craft normally once, and then get stuck again.

Note that it gets stuck per batch, so if the interface is configured to hold 3 furnaces it will craft 3 before it gets stuck.

**Comment by XFactHD** [comment]
I don't think this is a bug. That's the way it works, the interface wants to have one furnace, which means it takes the one recently crafted. For this process, the item doesn't need to be imported into the network which means that the crafting operation is not finished.

**Comment by Timeslice42** [comment]
Try it, you'll see what I mean. It's definitely a bug. It can also cause the crafting CPU and terminal to get out of synch when displaying the current crafting recipes, depending on how you cancel the jobs.
 By pull I mean take the furnaces out of the interface and place them into your own inventory.

**Comment by XFactHD** [comment]
1. I don't get why you are not using a second interface for storing the items.
2. I think an interface connected to a molecular assembler uses a special system which means that it is not intended to store items the way you want to.

**Comment by yueh** [comment]
This behaviour is intentional, items exported with interfaces are unknown to the network.
So the network will never be notified that the crafting is finished and will wait forever.

**Comment by Timeslice42** [comment]
Then why does it work every other time?
