### ISSUE TITLE
Porting to 1.8

### ISSUE THREAD

**Issue by thatsIch** [AppliedEnergistics/Applied-Energistics-2#1637]
Work required for full port

- [ ] Use new model and blockstate system for simple blocks
- [ ] Compass Rendering
- [ ] SkyChest Rendering
- [ ] Inhand block rendering
- [x] Stairs
- [x] Slabs
- [ ] Storage Monitor Rendering
- [ ] Rework of the names
- [ ] potential split of different items
- [ ] Rotation
- [ ] Paint not rendering
- [ ] Textures
- [ ] WAP rotated rendering
- [ ] AE2 glas rendering next to cables
- [ ] Crank rendering culling? (crank disappears sometimes depending on viewpoint)
- [ ] Placement based on view
- [ ] ME Interface rotation side rendering (interface displays multiple directions)
- [ ] Molecular Assembler glow rendering
- [ ] parts in inventory rendering (all look the same)
- [ ] GUI button rendering (darkens whole world and all other buttons)
- [ ] Molecular Assembler preview rendering no centered
- [ ] Illuminated panels do not glow
- [ ] Fixture rendering (breaks upon placement on the ground, if another block is placed next to it)
- [ ] ME Chest rendering of the front + z-fighting x
- [ ] Connected Textures for Crafting-CPU

List will be probably expanded upon time

- [ ] Model Tiny TNT
- [ ] Rendering Spatial Pylons
- [ ] Lighting Glitch on mouse over of progress bar of Matter Condensor
- [ ] Crafting CPU Rendering
- [ ] Smart Cable Rendering on long line

Probably also some logic problems?
- [ ] Villager for Trading (possibility is gone to inject into the blacksmith)
- [ ] Integration handling, currently all have to be disabled manually by commenting out the class, not optimal

**Comment by thatsIch** [comment]
Added stair models, for some reason they are still missing the textures though, might be related, that we instantiated them already in construction phase, might require shifting them out again ... sigh

![2015-06-27_10 32 00](https://cloud.githubusercontent.com/assets/2210496/8391159/ccd42394-1cb7-11e5-9cf2-c05b58111d2c.png)

**Comment by yueh** [comment]
You mean the model registration in postInit? If so, maybe instead of shifting everything again add preInit/Init/postInit as phase for the `IFeatureHandler`?

**Comment by thatsIch** [comment]
currently on hold cause RL

**Comment by thatsIch** [comment]
Fixed the stairs but destroyed blocks in the process. Should be nothing major

![2015-09-29_15 47 07](https://cloud.githubusercontent.com/assets/2210496/10165924/db496b06-66c1-11e5-8e3c-637de1323317.png)

The problem was a missing registry call to `CommonHelper.proxy.configureIcon`

**Comment by Gaelan** [comment]
Is there any way I can help out?

**Comment by yueh** [comment]
@thatsIch is there a chance you can hop on IRC today to discuss some stuff related to the port?

**Comment by McBossKiller** [comment]
Will the mod be ported to minecraft 1.8 or minecraft 1.8.9?

**Comment by LordSaad44** [comment]
Just want to put this out: https://github.com/amadornes/MCMultiPart

This might help with porting. :) It's currently the best microblocks api and AE can benefit a lot from it.

**Comment by yueh** [comment]
While it is a nice idea, it is still unfinished and unstable. I already reported a couple of bugs yesterday.

Also we cannot use it as hard dependency, but probably as soft dependency like FMP.
Should it every be merged into forge, maybe we could reconsider it.
But for now it would make porting even worse.

**Comment by DarcClan** [comment]
Also was wondering if this milestone plan was specifically for 1.8 or for 1.8.9. Hoping for 1.8.9 since most major mods seem to be either on, or working toward porting to 1.8.9, at least mods that are still in active development.

**Comment by thatsIch** [comment]
Since no major differences exist between 1.8 and 1.8.+ the list is still valid for any 1.8 version. Since never versions of Forge offer new possibilities its unlikely to aim at earlier versions of 1.8.

**Comment by thatsIch** [comment]
Slabs were removed since it made porting problematic

**Comment by thatsIch** [comment]
using new model is I think half way through, not highest priority though

**Comment by thatsIch** [comment]
It is now on 1.8.9
maybe directly to 1.9.x

**Comment by Ascott29** [comment]
More than willing to beta test if y'all need people to do so for 1.8.9 or higher.

**Comment by NoOneNo** [comment]
are there any 1.8.9 builds ?

**Comment by Alexismachina** [comment]
no. not completed yet.

**Comment by zzApotheosis** [comment]
I vote skip 1.8 and go directly to 1.9. I just have this gut feeling 1.9 will be the new "1.7".

**Comment by SirWindfield** [comment]
Sorry if this sounds really dumb (even if I have a quite decent understanding of Java and programming) but what exactly does make the porting that complicated? 
Sure, rendering has changed (especially the new json format for blocks might create problems). But the core API and logic of AE2 should be quite independent on MC or Forge. 
I have no experience with modding but I would really appreciate if someone could answer my question. 
Btw: I can help out if you want to. Might need some time to get the Modding API going and trying to understand it.

**Comment by gdude2002** [comment]
Yeah, I agree, should just go straight to 1.9 at this point; there isn't really much point in supporting 1.8 now that 1.9 is out and popular.

**Comment by SirWindfield** [comment]
May I ask a question? The pipes are implemented using FMP right? Would it be possible to use different models like rails do and create a Json model for each possible outcome? That would remove the soft dependency on FMP

**Comment by lehjr** [comment]
Regarding multipart: https://github.com/MinecraftForge/MinecraftForge/pull/2891

Doesn't look like it is finalized yet.

**Comment by gdude2002** [comment]
MCMultipart is a real game-changer from what I've seen. There are builds
available on Curse for now, but I assume those will be obsolete once the
merge is done. I ended up building a JAR from source myself.

**Comment by amadornes** [comment]
@gdude2002 You don't need to do that. I have a maven server for that exact reason ;)

**Comment by gdude2002** [comment]
I couldn't find it D:

Maybe I'm blind.

**Comment by lehjr** [comment]
@gdude2002 
https://github.com/amadornes/MCMultiPart#adding-mcmultipart-to-your-workspace

**Comment by gdude2002** [comment]
Yup, totally blind. Thanks!

**Comment by chaos234** [comment]
Seem a that a loot work is to do to port AE2 to 1.8 and later to 1.9.

Which IRC are you to can help if possible and what is to fork/clone/download/etc. to help?

**Comment by lehjr** [comment]
Their IRC info is in the Readme:
IRC #appliedenergistics on esper.net

Also note that 1.8 planning was a year ago. It's likely that if there are enough active team members with enough time they'll target 1.9.4.

**Comment by chaos234** [comment]
> Also note that 1.8 planning was a year ago. It's likely that if there are enough active team members with enough time they'll target 1.9.4.

This sounds nice! We will see/write us this weekend if I have finished my private work :) .

**Comment by HadesDurin** [comment]
well, if the work remaining in 1.7.10 gets done and the mod moves forward, then there will be a competition with "refined storage" in 1.9.4.
i am excited to see how this will be

**Comment by SharkWipf** [comment]
Refined Storage is a nice alternative to AE2, but it is nowhere near as full-featured and worked out, and the balance is completely different. I don't think there'll be much of a competition once AE2 ports over.

**Comment by akarlapudi03** [comment]
I say **MAKE IT ON 1.8**. There's a lot of 1.8 modpacks that really need this mod, and many also don't like the new combat mechanics of 1.9._SO PORT IT TO 1.8_. **PLZ! (since one of those modpacks that need this is MINE)**

**Comment by Gaelan** [comment]
Most 1.8 mods are already on 1.9, and many are now only updating on 1.9. If you don't like the new combat, install Good Ol' PvP.

**Comment by DarcClan** [comment]
Yea I've also tried refined storage, didn't like it as much as I liked AE2, its just not the same... Also seconded for jumping to 1.9.4

**Comment by mgdgfbhevdyeh** [comment]
Will the mod be ported to minecraft 1.8 or minecraft 1.8.9?
(I hope so)

**Comment by chaos234** [comment]
If I am right I think that 1.8.x will be skipped and it will be directly ported to 1.9.x or later.

DeltaNet - Production
Inh. Marcel Petzold
Friedrich-Ebert-Str. 44
04416 Markkleeberg

Mobil: 01728006598
Mail: info@deltanet-production.de

StNr.: 235/256/06058
UStNr.: DE272999582
Am 27.07.2016 06:18:01 schrieb mgdgfbhevdyeh <notifications@github.com>:
Will the mod be ported to minecraft 1.8 or minecraft 1.8.9?
(I hope so)

**Comment by lehjr** [comment]
No need to speculate when the answer is in front of you: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2306
