### ISSUE TITLE
Instant Crash When accessing Cumbustion Engine (right-clicking)

### ISSUE THREAD

**Issue by Twizzlerz** [AppliedEnergistics/Applied-Energistics-2#1639]
This is the crash report, please help i'm new to this and not sure if i'm doing something wrong. It might be something really stupid but I just can't figure it out.

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 23/06/15 2:08 PM
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:36)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:67)
	at buildcraft.energy.TileEngineIron.getGUINetworkData(TileEngineIron.java:275)
	at buildcraft.energy.gui.ContainerEngine.func_75137_b(ContainerEngine.java:57)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147245_a(NetHandlerPlayClient.java:1151)
	at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:26)
	at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:36)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:67)
	at buildcraft.energy.TileEngineIron.getGUINetworkData(TileEngineIron.java:275)
	at buildcraft.energy.gui.ContainerEngine.func_75137_b(ContainerEngine.java:57)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147245_a(NetHandlerPlayClient.java:1151)
	at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:26)
	at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Frank'/3494, l='MpServer', x=-66.76, y=5.62, z=-0.95]]
	Chunk stats: MultiplayerChunkCache: 81, 90
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (117,4,37), Chunk: (at 5,0,5 in 7,2; contains blocks 112,0,32 to 127,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 12380 game time, 12380 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 49 total; [EntityBlock['unknown'/3527, l='MpServer', x=-75.55, y=4.50, z=8.45], EntityBlock['unknown'/3526, l='MpServer', x=-75.50, y=4.45, z=8.45], EntityBlock['unknown'/3535, l='MpServer', x=-65.55, y=4.45, z=8.50], EntityBlock['unknown'/3534, l='MpServer', x=-75.55, y=4.45, z=8.50], EntityBlock['unknown'/3533, l='MpServer', x=-75.50, y=8.45, z=18.45], EntityBlock['unknown'/3532, l='MpServer', x=-65.55, y=4.50, z=18.45], EntityBlock['unknown'/3531, l='MpServer', x=-75.55, y=4.50, z=18.45], EntityBlock['unknown'/3530, l='MpServer', x=-75.50, y=4.45, z=18.45], EntityBlock['unknown'/3529, l='MpServer', x=-65.55, y=4.50, z=8.45], EntityBlock['unknown'/3528, l='MpServer', x=-75.50, y=8.45, z=8.45], EntityBlock['unknown'/3542, l='MpServer', x=-75.50, y=4.45, z=8.45], EntityBlock['unknown'/3543, l='MpServer', x=-75.55, y=4.50, z=8.45], EntityBlock['unknown'/3536, l='MpServer', x=-75.55, y=8.45, z=8.50], EntityBlock['unknown'/3537, l='MpServer', x=-65.55, y=8.45, z=8.50], EntityBlock['unknown'/3550, l='MpServer', x=-75.55, y=4.45, z=8.50], EntityBlock['unknown'/3551, l='MpServer', x=-65.55, y=4.45, z=8.50], EntityBlock['unknown'/3548, l='MpServer', x=-65.55, y=4.50, z=18.45], EntityBlock['unknown'/3549, l='MpServer', x=-75.50, y=8.45, z=18.45], EntityBlock['unknown'/3546, l='MpServer', x=-75.50, y=4.45, z=18.45], EntityBlock['unknown'/3547, l='MpServer', x=-75.55, y=4.50, z=18.45], EntityBlock['unknown'/3544, l='MpServer', x=-75.50, y=8.45, z=8.45], EntityBlock['unknown'/3545, l='MpServer', x=-65.55, y=4.50, z=8.45], EntityItem['item.tile.markerBlock'/3318, l='MpServer', x=-70.19, y=4.13, z=26.56], EnchantedCow['Enchanted Golden Apple Cow'/3314, l='MpServer', x=-52.02, y=4.00, z=11.13], EntityBlock['unknown'/3553, l='MpServer', x=-65.55, y=8.45, z=8.50], EntityBlock['unknown'/3552, l='MpServer', x=-75.55, y=8.45, z=8.50], EntityHorse['Horse'/3326, l='MpServer', x=-37.72, y=4.00, z=24.91], EntitySheep['Sheep'/3324, l='MpServer', x=-49.50, y=4.00, z=27.78], EntityHorse['Horse'/3325, l='MpServer', x=-36.75, y=4.00, z=23.13], EntitySlime['Slime'/5027, l='MpServer', x=-24.47, y=4.00, z=-19.73], EntitySlime['Slime'/5918, l='MpServer', x=-48.01, y=4.00, z=-18.45], EntityHorse['Horse'/3338, l='MpServer', x=-27.50, y=4.00, z=10.22], EntitySheep['Sheep'/3339, l='MpServer', x=-33.91, y=4.00, z=20.84], RedCow['Apple Cow'/3336, l='MpServer', x=-24.78, y=4.00, z=-26.19], EntitySheep['Sheep'/3342, l='MpServer', x=-19.50, y=4.00, z=48.09], EntitySheep['Sheep'/3340, l='MpServer', x=-26.03, y=4.00, z=30.63], EntitySheep['Sheep'/3341, l='MpServer', x=-25.31, y=4.00, z=36.19], EntitySheep['Sheep'/3330, l='MpServer', x=-37.53, y=4.00, z=50.53], EntitySheep['Sheep'/3328, l='MpServer', x=-35.75, y=4.00, z=30.03], RedCow['Apple Cow'/3334, l='MpServer', x=-24.91, y=4.00, z=-52.94], RedCow['Apple Cow'/3335, l='MpServer', x=-24.94, y=4.00, z=-47.94], RedCow['Apple Cow'/3333, l='MpServer', x=-18.56, y=4.00, z=-42.69], EntitySlime['Slime'/5898, l='MpServer', x=-96.56, y=4.95, z=-17.42], EntitySheep['Sheep'/3374, l='MpServer', x=-17.06, y=4.00, z=58.97], EntityHorse['Horse'/3495, l='MpServer', x=-110.78, y=4.00, z=-5.53], EntityItem['item.tile.markerBlock'/3497, l='MpServer', x=-85.81, y=4.13, z=9.13], EntityItem['item.tile.markerBlock'/3498, l='MpServer', x=-86.28, y=4.13, z=27.00], EntityClientPlayerMP['Frank'/3494, l='MpServer', x=-66.76, y=5.62, z=-0.95], EntityTrail['unknown'/3513, l='MpServer', x=-66.76, y=5.62, z=-0.95]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.7.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2876957960 bytes (2743 MB) / 3321798656 bytes (3167 MB) up to 6120341504 bytes (5836 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn3G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 96
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.3.1408 Optifine OptiFine_1.7.10_HD_U_B7 28 mods loaded, 28 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.3.1408-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Forge{10.13.3.1408} [Minecraft Forge] (forge-1.7.10-10.13.3.1408-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	AppliedEnergistics2-Core{rv0-stable-3} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	NotEnoughItems{1.0.5.110} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.110-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	FLabsBF{4.1.2} [Better Furnaces] ([1.7.10]Better_Furnaces_V4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	DamageIndicatorsMod{3.2.0} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	BuildCraft|Core{5.0.7} [BuildCraft] (BuildCraft-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	appliedenergistics2{rv0-stable-3} [Applied Energistics 2] (appliedenergistics2-rv0-stable-3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1019-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	BuildCraft|Builders{5.0.7} [BC Builders] (BuildCraft-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	BuildCraft|Energy{5.0.7} [BC Energy] (BuildCraft-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	BuildCraft|Factory{5.0.7} [BC Factory] (BuildCraft-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	BuildCraft|Transport{5.0.7} [BC Transport] (BuildCraft-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	BuildCraft|Silicon{5.0.7} [BC Silicon] (BuildCraft-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	EnderStorage{1.4.7.36} [EnderStorage] (EnderStorage-1.7.10-1.4.7.36-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	fossil{1.7.10 Build 7.2.1} [Fossils and Archeology Revival] (Fossils_Archeology_Revival-1.7.10_Build-7.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	iChunUtil{4.0.0} [iChunUtil] (iChunUtil-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Morph{0.9.0} [Morph] (Morph-Beta-0.9.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	OreSpawn{1.7.10.20.3} [OreSpawn] (orespawn-1.7.10-20.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Scenter{1.7.10-3.2.0} [Scenter] (scenter-1.7.10-3.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Waila{1.5.3} [Waila] (Waila-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	XaeroMinimap{1.4.5.1} [Xaero's Minimap] (xaeros_minimap_v1.4.5.1_1.7.10_Forge.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	AE2 Version: stable rv0-stable-3 for Forge 10.12.0.1024
	AE2 Integration: RotaryCraft:OFF, IC2:OFF, RC:OFF, BC:ON, MJ5:ON, MJ6:OFF, RF:OFF, MFR:OFF, DSU:OFF, FZ:OFF, Waila:ON, CLApi:OFF, RB:OFF, InvTweaks:ON, NEI:ON, CraftGuide:OFF, FMP:OFF
	Launched Version: 1.7.10-Forge10.13.3.1408-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 765M/PCIe/SSE2 GL version 4.4.0 NVIDIA 344.75, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by FireBall1725** [comment]
This is an error with buildcraft and has nothing to do with AE

**Comment by FireBall1725** [comment]
Also, might want to update your AE, since you are using stable rv0-stable-3 and that is super old.
