### ISSUE TITLE
There is no smooth stone slab cable facade.

### ISSUE THREAD

**Issue by piousminion** [AppliedEnergistics/Applied-Energistics-2#1641]

**Comment by TheJulianJES** [comment]
You can add facades yourself.

**Comment by piousminion** [comment]
Even if I knew how, that doesn't solve the problem of having no facade for a vanilla block by default.

**Comment by yueh** [comment]
Facades for vanilla blocks are enabled by default.
If this is not the case either you disabled them on your own or you should complain about it by whoever creates the modpack you are using and who has most likely disabled them.

**Comment by piousminion** [comment]
Facades for vanilla blocks are present, except for smooth stone (double)slabs id:43. I am the creator of my modpacks and I have made no changes regarding facades. Check for yourself and see that there is no smooth stone slab facade.

**Comment by yueh** [comment]
![smooth stone double slab](http://i.imgur.com/0BEirOK.png)

**Comment by piousminion** [comment]
I now understand that since the block is not obtainable that it can't be crafted. Therefor I request that this be reopened as a feature request. Perhaps crafting the slabs with the anchors to make them.
