### ISSUE TITLE
Terminal displaying twice as many storage components

### ISSUE THREAD

**Issue by phillyfan666** [AppliedEnergistics/Applied-Energistics-2#1642]
Crafting terminal displays 10 64k ME storage components even though system only contains 5.

![2015-06-24_19 50 48](https://cloud.githubusercontent.com/assets/12955457/8344083/74e99448-1aaa-11e5-80f5-53026f655b9d.png)
![2015-06-24_19 50 56](https://cloud.githubusercontent.com/assets/12955457/8344084/76774ac6-1aaa-11e5-858a-108bff9db40f.png)

**Comment by yueh** [comment]
#986
