### ISSUE TITLE
Export Bus with Fuzzy card exporting Paint Balls

### ISSUE THREAD

**Issue by yamees** [AppliedEnergistics/Applied-Energistics-2#1643]
I was testing something on my local server while using a Fuzzy card along with an export bus. I tried to export all the various paint balls using a single paint ball as the whitelist but it would only export the paint ball in the whitelist even though I used the match any comparison and I had no change. I am currently using the latest stable build (9) I tried using different drives and even different network but i had no change. To reproduce the issue, you would put various paint balls in a drive on a network and simply set up and export bus with a fuzzy card with only one of the paint balls white listed. I'm using the DW20 modpack but i did update ae2 to test if it was still an issue. Any ideas on what is happening because to my knowledge the paint balls are only different based on meta data.

**Comment by yueh** [comment]
#360
