### ISSUE TITLE
Quantum Network Bridge Channel Limit?

### ISSUE THREAD

**Issue by TheHell34** [AppliedEnergistics/Applied-Energistics-2#1644]
![screenshot_2](https://cloud.githubusercontent.com/assets/4223026/8356592/8e45be4c-1b56-11e5-8f5e-501a86ed1d59.png)

Is there a channel limit

with the last update most of my Me Interfaces lost connection, when I free some channels some ME interfaces comeback online. Im using a Quantum Network Bridge with 33 channels and cant get more channels

Im using rv2.stable build 9
Im using DW20 1.7.10 v1.5 on my server

**Comment by yueh** [comment]
#1611
