### ISSUE TITLE
EU PTP Tunnel Bug (Bad Solution)

### ISSUE THREAD

**Issue by Speiger** [AppliedEnergistics/Applied-Energistics-2#1645]
Hello.
I Tried to get Fierball to a talk but since he was not acceable i try it here now.

AE PTP Tunnels with EU have 1 Big Problem. They do not use the API Right...
First they do not Support MultiPackets, even that was a thing In IC2 and will be again (classic has it alread).
Second You send only energy if energy was drawen. That causes to a not even energy flow... Tested it...

Solution is easy, instead of using IEnergySink & IEnergySource use IEnergyConductor & IMetadelegate,

IEnergyConductor makes that the PTP Tunnels count as wire (which is the plan), since that is only working for 1 TileEntity there comes the IMetaDelegate into the game, which says i am a MultiStructure,
and that link all conductors together how they should be.
Also Energy can flow in every direction and is not only limited to 1 Direction.

It would be kind of nice if you could solve that problem since it is a potential bug which could cause Problems (including a lag Source!) later down the line which IC2 (Exp/Classic) can nothing do nothing new because there is already a solution for it aviable^^

Anyway thanks for reading. Speiger (IC2 Classic Dev)

**Comment by yueh** [comment]
The one way transfer is by design and any change in the implementation still needs to retain this.
Every other P2P tunnels works with this limitation (except ME ones), so does this change still support it?

**Comment by Speiger** [comment]
Yes because you still have the functions can Accept power and can Send Power (input can recieve but not send and output opposite), but only the "can i do the transfer" request. The power Transfer will be handled by the IC2 E-Net.
Any more questions?

**Comment by Speiger** [comment]
Little note:
The TileEntity that gets provided in the IEnergyAcceptor/IEnergyEmitter is always the TileEntity that try to connect...
So you would need to make a check which PTP tunnel it is now calling that function.
