### ISSUE TITLE
crash on Light Detector

### ISSUE THREAD

**Issue by padgg** [AppliedEnergistics/Applied-Energistics-2#1648]
game version is appliedenergistics2-rv3-latest-110
when set the block Light Detector ,the game had crash.then the save had broken

Crash reports
---- Minecraft Crash Report ----
// Don't do that.

Time: 15-6-26 下午12:40
Description: Unexpected error

java.lang.ClassCastException: appeng.block.misc.BlockLightDetector cannot be cast to appeng.block.misc.BlockQuartzTorch
	at appeng.client.render.blocks.RenderQuartzTorch.renderInWorld(RenderQuartzTorch.java:102)
	at appeng.client.render.WorldRender.renderWorldBlock(WorldRender.java:69)
	at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118)
	at FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:296)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
	at fastcraft.a.o.a(F:86)
	at fastcraft.Hooks.t(F:147)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at appeng.client.render.blocks.RenderQuartzTorch.renderInWorld(RenderQuartzTorch.java:102)
	at appeng.client.render.WorldRender.renderWorldBlock(WorldRender.java:69)
	at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118)
	at FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:296)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
	at fastcraft.a.o.a(F:86)
	at fastcraft.Hooks.t(F:147)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['allens'/16, l='MpServer', x=-203.15, y=58.55, z=380.81]]
	Chunk stats: MultiplayerChunkCache: 370, 370
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-194,4,392), Chunk: (at 14,0,8 in -13,24; contains blocks -208,0,384 to -193,255,399), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 85574 game time, 394804 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 6 total; [EntityClientPlayerMP['allens'/16, l='MpServer', x=-203.15, y=58.55, z=380.81], EntityItemFrame['物品展示框'/11, l='MpServer', x=-195.50, y=57.50, z=378.06], EntityItemFrame['物品展示框'/12, l='MpServer', x=-202.50, y=57.50, z=378.06], EntityItemFrame['物品展示框'/13, l='MpServer', x=-203.50, y=58.50, z=378.06], EntityItemFrame['物品展示框'/14, l='MpServer', x=-201.50, y=58.50, z=378.06], EntityItemFrame['物品展示框'/15, l='MpServer', x=-187.50, y=57.50, z=378.06]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 349675976 bytes (333 MB) / 963117056 bytes (918 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 1 total; -Xmx2048m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 42 mods loaded, 42 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv3-latest-110} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	InputFix{1.7.10-v5} [InputFix] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.4.83} [Not Enough Items] (NotEnoughItems-1.0.4.83-universal[NEI本体].jar) 
	UCHIJAAAA	uniskinmod{1.2-dev4} [Universal Skin Mod] (minecraft.jar) 
	UCHIJAAAA	appliedenergistics2{rv3-latest-110} [Applied Energistics 2] (appliedenergistics2-rv3-latest-110.jar) 
	UCHIJAAAA	BiblioCraft{1.10.4} [BiblioCraft] (BiblioCraft[v1.10.4][MC1.7.10].jar) 
	UCHIJAAAA	BuildCraft|Core{7.0.12} [BuildCraft] (buildcraft-7.0.12.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.0.12} [BC Energy] (buildcraft-7.0.12.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.0.12} [BC Factory] (buildcraft-7.0.12.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.0.12} [BC Transport] (buildcraft-7.0.12.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.0.12} [BC Builders] (buildcraft-7.0.12.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.0.12} [BC Silicon] (buildcraft-7.0.12.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.0.12} [BC Robotics] (buildcraft-7.0.12.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHIJAAAA	Waila{1.5.8} [Waila] (Waila(NEI拓展)-1.5.9_1.7.10.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct] (TConstruct-1.7.10-1.8.5.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJAAAA	thaumicenergistics{0.8.10.5} [Thaumic Energistics] (thaumicenergistics-0.8.10.5.jar) 
	UCHIJAAAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar) 
	UCHIJAAAA	ReiMinimap{1.7.10} [Rei's小地图 堕落汉化] ([1.7.10]Rei小地图.jar) 
	UCHIJAAAA	ArmorStatusHUD{1.28} [ArmorStatusHUD] (ArmorStatusHUD（耐久显示）.jar) 
	UCHIJAAAA	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-156-af3bc68} [Inventory Tweaks] (InventoryTweaks-1.59-dev-156[R键整理].jar) 
	UCHIJAAAA	NBTEdit{1.7.2.2} [In-game NBTEdit] (NBTEdit_1.7.10.jar) 
	UCHIJAAAA	NEIAddons{1.12.9.32} [NEI Addons] (neiaddons-1.12.9.32-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|AppEng{1.12.9.32} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.9.32-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Botany{1.12.9.32} [NEI Addons: Botany] (neiaddons-1.12.9.32-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Forestry{1.12.9.32} [NEI Addons: Forestry] (neiaddons-1.12.9.32-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|CraftingTables{1.12.9.32} [NEI Addons: Crafting Tables] (neiaddons-1.12.9.32-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|ExNihilo{1.12.9.32} [NEI Addons: Ex Nihilo] (neiaddons-1.12.9.32-mc1.7.10.jar) 
	UCHIJAAAA	NEIPlugins{1.1.0.10-unofficial} [NEI Plugins Unofficial] (NEIPlugins-MC1.7.10-1.1.0.10-unofficial.jar) 
	UCHIJAAAA	StatusEffectHUD{1.26} [StatusEffectHUD] (StatusEffectHUD(状态显示)-client-1.26.jar) 
	UCHIJAAAA	thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7a.jar) 
	UCHIJAAAA	wawla{1.2.1} [What Are We Looking At] (Wawla-1.2.1_1.7.10.jar) 
	UCHIJAAAA	worldedit{6.0-beta-01} [WorldEdit] (worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 350.12' Renderer: 'GeForce GTX 860M/PCIe/SSE2'
	AE2 Version: alpha rv3-latest-110 for Forge 10.13.4.1448
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BuildCraftCore:ON, BuildCraftTransport:ON, BuildCraftBuilder:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF
	Launched Version: 1.7.10-Forge10.13.4.1448-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 860M/PCIe/SSE2 GL version 4.5.0 NVIDIA 350.12, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [Faithful for Thaumcraft v2.8 + Addons.zip, Faithful32 pack+sky.zip]
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by TheJulianJES** [comment]
Please use rv2 stable from the website.
