### ISSUE TITLE
Crafting Status Button Crash

### ISSUE THREAD

**Issue by x1xHEADSHOTSx1x** [AppliedEnergistics/Applied-Energistics-2#1649]
I just setup auto-crafting on Sky Factory 2 via the ATLauncher and now when I click on the crafting status icon (Hammer in the Upper Right Corner) in a crafting terminal I crash. Recently I have been trying to craft several tier II solar panels from Solar Flux. I am not sure if the mod is causing the crash or if it is AE2 has a bug. The forum moderator wormmus for Sky Factory 2 suggested I post this issue here. Any help on this issue would be greatly appreciated.

ATLauncher Log Report
http://paste.atlauncher.com/view/a9f1eebe

Crash Report that was produced
https://www.dropbox.com/s/jz1lqks8w12vsyy/crash-2015-06-26_01.24.17-client.txt?dl=0

**Comment by yueh** [comment]
This looks not like an AE2 issue, but more like an issue with infiniteinvo.
Immediately before the actual crashlog that mod is already complaining about not supporting our GUI, but are still trying to inject their own scrollbar but failing at it and probably not providing a fallback to the vanilla scrollbars.

That is probably also something the moderator should have pointed out after looking at the log.
Maybe also mention to them, that without them updating AE2, there is no way we can ensure that the bugs you encounter are fixed for you. As they are still using a pretty old version.

**Comment by x1xHEADSHOTSx1x** [comment]
Thanks. I have disabled the Infiniteinvo mod and it fixed the issue. I let the moderator know and he is thinking of making a suggestion to remove the mod. Thanks again for your timely response.
