### ISSUE TITLE
Crash when Shift Clicking pattern into crafting table for Dense Cable

### ISSUE THREAD

**Issue by Sparky24** [AppliedEnergistics/Applied-Energistics-2#1653]
Hey!

Noticed when Shift+right clicking the question mark from NEI into a crafting table to make Dense Cable, that the game crashes out.

http://pastebin.com/9Fvx8Psu

Thanks!

**Comment by yueh** [comment]
Looks more like a tinker's construct issue.
Reopen, if they can provide feedback that it is ae2 related.
