### ISSUE TITLE
World generation issue (Applied Energistics overwriting vanilla generation.)

### ISSUE THREAD

**Issue by border999** [AppliedEnergistics/Applied-Energistics-2#1654]
Upon generating a random world during a beta test of a custom modpack I'm making. I found that my spawn point was in a taiga biome, the issue came when I  found that instead of mossy cobblestone generating in the ground, it was vibrant glass. If this is a problem on your end I ask that you look into it.
I have already erased and regenerated both the world and the config, same issue occurs.

**Comment by border999** [comment]
It's not really something that completely breaks the game, but I felt I should inform the mod author in case this issue grows bigger over time.

**Comment by yueh** [comment]
We do not have any worldgen besides the meteors and quartz ore.
Are you sure that not any other worldgen related mod did mess something up? As the internal block ids are completely (and randomly) handled by forge and it sounds more some worldgen is still using hardcoded block ids, thus using the wrong block.

**Comment by yueh** [comment]
Inactive
