### ISSUE TITLE
Multi-block ME controllers forcing chunks to stay loaded

### ISSUE THREAD

**Issue by RoyCurtis** [AppliedEnergistics/Applied-Energistics-2#1656]
It appears that ME Controllers are keeping their chunk(s) loaded ("orphaned"?) without using the Forge forced chunk ticket system, when:

* The Controller [is in a multiblock configuration](http://i.imgur.com/SXZZbEV.png)
* It is powered using an Energy Acceptor

This causes surrounding chunks to load by other means such as conduits and machinery from other mods, which then become unloaded during auto-save and immediately loaded again by the ME controller keeping the chunk alive.

# Details

## Discovered on

* Direwolf20 1.7.10 1.4.1 and [1.5.0](https://www.reddit.com/r/feedthebeast/comments/3b2lty/dw20_direwolf20_150_1710_now_in_beta/) live server
* Forge 10.13.4.1448
* Applied Energistics rv2-stable-3 and rv2-stable-9

## Screenshots

* [Recent screenshot of bases being kept loaded by ME controllers](http://i.imgur.com/9x41HSn.png)
* [Video of chunk churn being caused by the loaded chunks](http://gfycat.com/ComfortableGrandioseBedlingtonterrier)
* [2nd June screenshot of chunks being kept alive at bases with ME controllers](http://i.imgur.com/1HMdDY1.png)

# Reproduction

## Testing environment

* Forge 1.7.10 10.13.4.1448
* [Applied Energistics](http://ae-mod.info/Downloads/) rv2-stable-9
* [ChickenChunks](http://chickenbones.net/maven/codechicken/ChickenChunks/1.7.10-1.3.4.19/) 1.3.4.19 & [CodeChickenCore](http://chickenbones.net/maven/codechicken/CodeChickenCore/1.7.10-1.0.7.46/) 1.0.7.46 
* Thermal Suite:
  * [CoFH Core](http://minecraft.curseforge.com/mc-mods/69162-cofhcore/files/2244284) 3.0.2-285
  * [Thermal Foundation](http://minecraft.curseforge.com/mc-mods/222880-thermal-foundation/files/2243148) 1.0.0-88
  * [Thermal Expansion](http://curse.com/mc-mods/minecraft/thermalexpansion/2234200) 4.0.1-182

## Steps

1. Create a flatland creative world with cheats enabled
2. Execute `/tp 0 8 0` and then `/setworldspawn` (keeps spawn chunks away from testing areas)
3. Execute `/tp 1000 8 1000`
4. [Build an ME controller setup with one block, an Energy Acceptor and a Creative Energy Cell](http://vanderprot.gamealition.com/img/2015-06-29_18-33-30.jpg)
5. Execute `/tp 1000 8 -1000`
6. Repeat step 4, but with a [multi-block ME Controller setup](http://vanderprot.gamealition.com/img/2015-06-29_18-36-01.jpg)
7. Execute `/tp -1000 8 1000`
8. Repeat step 4, but with multiple [multi-block ME controller setups](http://vanderprot.gamealition.com/img/2015-06-29_18-38-12.jpg)
9. Repeat steps 7 and 8 at `/tp -1000 8 -1000`
10. Execute `/tp 0 8 0`
11. Press ESC to open the main menu and force a chunk purge
12. Resume game and execute `/chunkloaders`. A new window will open under Minecraft
13. [Observe that chunks with the multi-block ME Controllers are kept loaded, whilst the chunk with only a single ME controller is properly unloaded](http://vanderprot.gamealition.com/img/Chunk_Viewer_2015-06-29_18-42-33.png)

# Notes

I discovered this bug as part of a [long running investigation as to why chunks are mysteriously loading and unloading at random on my server](https://www.reddit.com/r/feedthebeast/comments/3897ky/dw20_130_troubleshooting_mystery_forced_chunks/). It is possible that other mods and factors are contributing to the problem, but I believe this particular bug is a major contributor.

To determine the existance of this bug, I took an offline copy of an affected base and tore it down machine by machine (e.g. reactor, turbine, EnderIO conduits, etc) and teleported in and out, until I was able to unload the chunk.

Because of time constraints and lack of experience with the AE2 codebase, I am unable to offer any advice or pull requests.

**Comment by RoyCurtis** [comment]
Really cool! Looking forward to trying this out. Thank you for the fix, @yueh

**Comment by KennyBurch** [comment]
I'm curious now, I have been fighting with the ME2 controller(just using a single block) losing all contact with ALL storage devices when I use chickenchunks chunkloader on my base.  (Controller stops talking to drives when I move away from my base and the chunks get cleaned up) I wonder if the current 'broken keeping chunks loaded' would keep the system working if I use a multiblock controller.

**Comment by 123Kappa** [comment]
Hello I am having the same issue, It's noted as fixed but I don't see the fix anywhere

**Comment by bigenergy** [comment]
I have the same problem on 1.12.2
