### ISSUE TITLE
Memory-less mode autocrafting

### ISSUE THREAD

**Issue by Carbon-Ghost** [AppliedEnergistics/Applied-Energistics-2#1657]
One thing I think is missing from AE2 is a config for "easy" autocrafting, by that I mean without using memory from the "x"K crafting cpus, similar to channel less mode, this would first allow to have another config for people making casual modpacks having a choice if they want to go the normal route or the easy one ( like channels ) + will bring back a crafting system that while being AE2-ish with the new stuff ( which BTW looks quite gorgeous ), will be a bit similar to the old AE MAC ( by that I mean there was no limit to the number of crafts that could be done ) and will make that we will be able to avoid this kind of stuff : https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/393

Can you please think of this idea please ?

**Comment by Cisien** [comment]
no

**Comment by Carbon-Ghost** [comment]
Why ;(

**Comment by Carbon-Ghost** [comment]
And I am not good enough to try to make an addon out of my idea ;( Please, reconsider this idea :O

**Comment by jHoyne** [comment]
@Carbon-Ghost I'll help make the add-on.

**Comment by Carbon-Ghost** [comment]
Other people also requested something similar on IC2 forums... We can make an addon for this but I'm just too bad for this ;( I barely make mods by my own....

**Comment by jHoyne** [comment]
I am more front-end web programmer then mod or plugin coding but I
understand java and how to code in it and I've seen how the mods are done.

On 30 June 2015 at 04:44, Carbon-Ghost <notifications@github.com> wrote:

> Other people also requested something similar on IC2 forums... We can make
> an addon for this but I'm just too bad for this ;( I barely make mods by my
> own....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1657#issuecomment-117097869>
> .
>



-- 
Joseph Hoyne
Twitter <https://www.twitter.com/JosephHoyne>
Github <http://www.github.com/jHoyne>

**Comment by Carbon-Ghost** [comment]
I made a mod once, it added a block, end :P ( I feel terrible... )

**Comment by jHoyne** [comment]
Experience with code is experience with code take knowledge as you gain it
and use it to your advantage to increase the work of your code


On 30 June 2015 at 04:51, Carbon-Ghost <notifications@github.com> wrote:

> I made a mod once, it added a block, end :P ( I feel terrible... )
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1657#issuecomment-117102060>
> .
>



-- 
Joseph Hoyne
Twitter <https://www.twitter.com/JosephHoyne>
Github <http://www.github.com/jHoyne>

**Comment by Carbon-Ghost** [comment]
Well, we can try to make it... But I won't be much useful except for textures ...

**Comment by jHoyne** [comment]
The bit I am terrible at you are capable of

On 30 June 2015 at 06:24, Carbon-Ghost <notifications@github.com> wrote:

> Well, we can try to make it... But I won't be much useful except for
> textures ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1657#issuecomment-117130676>
> .
>



-- 
Joseph Hoyne
Twitter <https://www.twitter.com/JosephHoyne>
Github <http://www.github.com/jHoyne>

**Comment by Carbon-Ghost** [comment]
Hope I am useful ...

**Comment by jHoyne** [comment]
Yeah pop me an email at JosephHoyne@gmail.com and we can discuss it a bit
further.

On 30 June 2015 at 06:54, Carbon-Ghost <notifications@github.com> wrote:

> Hope I am useful ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1657#issuecomment-117146228>
> .
>



-- 
Joseph Hoyne
Twitter <https://www.twitter.com/JosephHoyne>
Github <http://www.github.com/jHoyne>

**Comment by Carbon-Ghost** [comment]
Kk
