### ISSUE TITLE
When going into your inventory ...

### ISSUE THREAD

**Issue by vvezvi** [AppliedEnergistics/Applied-Energistics-2#1659]
Ok, so today I was playing at home, enjoying the holidays, and I went into the nether to get some manyullyn for tinkers construct. I had set up a piece of sky stone at a nether fortress so that I could easily get to it. I found some cobalt and ardite (materials for manyullyn) on the way and was holding my compass when I went into my inventory, but IT WAS BLANK. I decided that I should try switching the item I was holding and then my inventory had the right items in it. So I just wanted to point out this glitch for your future reference, plz fix.

**Comment by Cisien** [comment]
screenshots?
are you running optifine? if so, turn it off.
post logs otherwise
