### ISSUE TITLE
Sorted mode for Interface Terminal

### ISSUE THREAD

**Issue by Lodran** [AppliedEnergistics/Applied-Energistics-2#1660]
Sort buttons (much like NEI) would re-order the items within the interface categories according to name, plugin or interface, with interface (as-is) being the default.  Perhaps empty slots should be sorted to the top, to make finding them easier.

**Comment by yueh** [comment]
Not feasible, each line is linked to a specific interface and not an arbitrary slot somewhere on the network.
So the only usable is sorting is by the name of the interface/machine. But adding an option to reverse this list is way inferior to the existing filter.

**Comment by Lodran** [comment]
Once you've sorted by the name of the interface, a secondary sorting within the interface grouping absolutely would be useful.  But I can understand that it might be difficult.
