### ISSUE TITLE
Shift-Click to auto-place Crafting patterns in Interface Terminal

### ISSUE THREAD

**Issue by Lodran** [AppliedEnergistics/Applied-Energistics-2#1661]
Shift-clicking a (Crafting only) pattern would automatically place it in the first available interface.

**Comment by yueh** [comment]
This will introduce a bad option as patterns will be randomly placed into the wrong interface.
Like smelting recipes placed in an interface next to an assembler, the pulverizing on in the furnace interace and so on.

**Comment by Lodran** [comment]
That's why I specified that this would only work for crafting (i.e. assembler) patterns - not for processing patterns.

The only time you really care where a pattern goes in a large bank of assemblers is when you're trying to optimize specific patterns (i.e. for compressing cobble quickly, or some such).  Otherwise, scrolling through hundreds of patterns to find an empty slot to put the pattern into is just tedious.
