### ISSUE TITLE
Entire AE storage system is blank, but still there

### ISSUE THREAD

**Issue by NinjaSniperC18** [AppliedEnergistics/Applied-Energistics-2#1662]
I have an system set up with about 12 64k Storage cells in it full of items, plenty of autocraftin and so on. every so often when I attempt to access the storage, there seems to be nothing there for about 10minutes or so, the reason I can confirm the stuff is there is because when I shift-click recipes, the items pop-up into the pattern/crafting terminal and the items will show for about a second or so when my farms update them. otherwise, I can't access items at all\

Using DW20 1.4.1

**Comment by yueh** [comment]
We need more information.
Also check if your network (not your RF energy cell) has enough power, no constant chunk reloading resetting the network etc.

**Comment by XFactHD** [comment]
I had this issue today. I switched all my chunkloaders from chickenchunks to mfr chunkloaders. As soon as they got to work and loaded all the QNB pairs, the storage the storage and crafting (the ThaumicEnergistics crafting recipes remained visible) switched off. As soon as I took one disk per drive out and put it back in, storage came back. Over time, when everything behind the QNBs got initialized, the crafting came back too.

**Comment by KennyBurch** [comment]
I'm having a similar issue here. It's been hard to reliable reproduce..but if I use chickenchunks to load my base it seems to lose access to the storage drives when I leave the area.

**Comment by XFactHD** [comment]
I got the issue again. This time I switched out some cables, recolored them and put down more cables to separate the things a bit better. As soon as I had changed some cables the storage and some random busses shutdown and showed "no channel available" and the crafting cpus showed "offline" even though they were working.

**Comment by yueh** [comment]
Closing in favour of #1611
