### ISSUE TITLE
Cable Facades Turning Brown

### ISSUE THREAD

**Issue by someonefromcanada38** [AppliedEnergistics/Applied-Energistics-2#1663]
This is happening in the most recent Agrarian Skies 2 stable, I had no issues previously to tonight and these facades were all the proper blue color. One turned brown, at which point I broke it to replace it and the adjacent ones also turned brown, eventually they all turned brown.
![image](https://cloud.githubusercontent.com/assets/552641/8451000/afb408da-1fad-11e5-9ebc-2c147011b204.png)

I eventually managed to fix this issue temporarily by removing and replacing all of the affected facades, however it continues to happen periodically

**Comment by XFactHD** [comment]
Are you using ExU bricks for the facades? As far as I know the ExU bricks cause problems because they don't save the colour as metadata but as NBT data.

**Comment by someonefromcanada38** [comment]
Yes I am, I have managed to solve the problem by keeping smooth lighting on minimum the problem disappears after leaving and restarting the map. I believe it has to do with opening the map with smooth lighting off as there is no immediate effect when turning it on or off.

**Comment by yueh** [comment]
Were these blocks not also depending on the chunk they are placed in at one point?

**Comment by TheJulianJES** [comment]
@yueh Yes, they are colored bricks from ExU. You can dye one block (not facade) and all other blocks in the same chunk change.

**Comment by thatsIch** [comment]
Not sure if this is really fixable, since facades are really dumb. They just render the block they were made off. So if the original block changes, it will change with it.
