### ISSUE TITLE
new feature

### ISSUE THREAD

**Issue by killerall5385** [AppliedEnergistics/Applied-Energistics-2#1670]
Algorithm please add that a item transfer pipe like the transfer node and item conduits can insert acceleration card into the molecular assembler. it is annoying to add 5000+ cards to my system and would like to be able to use pipes like i can with drives. please comment weather you agree or disagree.

**Comment by Entoarox** [comment]
What kind of insane build are you making to need a thousand assemblers?!?!?!? that is space for 54 thousand recipes, I dont think ANY modpack in existence even has that many recipes that can viably be auto-crafted! (And where are you even getting the CHANNELS for that stuff!?!?!?!)

**Comment by yueh** [comment]
Assemblers are already inventories, which can be used to craft.
Exposing the upgrades inventory will most likely break them and prevent them from crafting as the pipes insert the items into the wrong inventory. Or you have to open the GUI to somehow define that one side is accepting upgrades, which basically is the same effort as simply place the upgrades cards and also the effort to build the system to insert them finally.

It is really just a poor alternative to #1382.

**Comment by killerall5385** [comment]
Use a item sorting thing so the any card that can go there will. and how is it poor i am in the process of setting up about 10k me drives think i want to put the 64k drives in all those. NO i used a builders wand and transfer pipes. Also Entoarox if you look at the achievement there is one for 2048 devices and the me controllers, yes plural, that i use can support over 4096 channels plus if you look in the config there is a option to turn channels off. if anything i want to see this tried and if algorithm wont i want permission to try myself. if i can get it to work i will probably make a additional mod that does it.
also it is insane speed like craft a octuple compressed cobble in about 30 seconds so that is why. i made my world lag to 5 tps crafting a octuple cobble before but it sucked to build the crafting towers i used to do that and i want to super size that. the memory card would be a start but this would be even better.

**Comment by Blue64** [comment]
@killerall5385 I would love a YouTube tour of your base lol
