### ISSUE TITLE
Massive Chunk Updates

### ISSUE THREAD

**Issue by someonefromcanada38** [AppliedEnergistics/Applied-Energistics-2#1671]
After upgrading to an ME system in agrarian skies 2 I've had severe performance issues, with and without fastcraft. I turned off all of my machines and more than half of my me system and still had 300-400 chunk updates happening every 10-20 seconds, These chunk update numbers are with 40 interfaces on 8 molecular assemblers 128 storage bus connected deep storage units, 7 advanced inscribers 1 crystal growth chamber and 2 64 bit crafting processors with 8 co-processors each. The controller is made up of 72 blocks. I have disconnected all the storage bussed deep storage units and that didn't fix anything. Turning off the Me System removes all excess chunk updates. I have no idea how to fix the lag or why it is happening, I've tried removing components but have been unable to find the source of the problem

![image](https://cloud.githubusercontent.com/assets/552641/8498696/e4411060-2157-11e5-9186-2d4dbb8ec667.png)

![image](https://cloud.githubusercontent.com/assets/552641/8498649/38942a90-2157-11e5-8a28-e680640cb42f.png)

**Comment by yueh** [comment]
The best idea is to remove only parts from the network, not turn it completely off.

I would also recommend starting to remove the ae2stuff blocks first. There where a couple of different issues in the past. Like creating broken patterns, flooding the network with updates etc.

**Comment by yueh** [comment]
No further feedback, reopen once you can add some more details.
