### ISSUE TITLE
AE2 things missing channel

### ISSUE THREAD

**Issue by ZZaphodd** [AppliedEnergistics/Applied-Energistics-2#1672]
![ae2 missing channel](https://cloud.githubusercontent.com/assets/8099421/8498858/112811d6-21c7-11e5-92bd-defa57a3773b.jpg)

version : rv2-stable-9
modpack : direwolf20 1.7 

Are there max channel per a controller?
I have enough power but some random ae elements missing channel.
And when I restarts the game, some random ae elements furthest from ae controller goes down again.

I'm running pretty big network

**Comment by yueh** [comment]
#1611
