### ISSUE TITLE
Draw error on storage monitor after minecraft reload

### ISSUE THREAD

**Issue by datahunter** [AppliedEnergistics/Applied-Energistics-2#1673]
When I put items(from a few other mods) on the storage monitor it works fine until i leave minecraft and reload level then there are a few errors.. I found it is the same on two different systems and when I remove the item from the monitor and replace it it works fine, 

before reload
![ae_forestry](https://cloud.githubusercontent.com/assets/4216742/8502037/be3b1128-21ab-11e5-8d57-00211789bb3a.png)

after reload
![ae_draw error](https://cloud.githubusercontent.com/assets/4216742/8502043/ce2bef80-21ab-11e5-9d6d-6ed2076b464f.png)

draw error items shown i the air and not on terminal and some random molten iron in the air although there isn't any on the map
![ae_draw error2](https://cloud.githubusercontent.com/assets/4216742/8502064/09bf790e-21ac-11e5-9a44-0856bcaaf47f.png)

the ingot in the air is the one in the chest below me 
![ae_draw error3](https://cloud.githubusercontent.com/assets/4216742/8502084/2bc8af52-21ac-11e5-8420-ba50ab7552c2.png)
![ae_draw error4](https://cloud.githubusercontent.com/assets/4216742/8502091/3223939e-21ac-11e5-8211-310a1ebfa1ed.png)

and finally when I look at some monitors my screen goes blank
![ae_draw error5](https://cloud.githubusercontent.com/assets/4216742/8502106/5013ae84-21ac-11e5-84f7-eb82f5d0b8e3.png)

after I remove the item from the monitor everything is then back to normal and I can put the item back on the monitor with no draw error

log file
http://pastebin.com/3hWMxy8Q

**Comment by yueh** [comment]
Looks like a broken itemrenderer, but it seems to not appear with just forestry and AE2 alone.

I would also recommend to try it without any "optimizing" mod like Optifine, FastCraft, etc.
If this not fixes it, start a new instance just with AE2 and add the other mods slowly back until you find the one causing it.

**Comment by datahunter** [comment]
I search further and found the problem with only 2 mods installed first I tested with only forestry and then with bibliocraft, I found when I put the item on the monitor with nothing in the me drive then it works fine even after restart, but when I put the item in ME drive the draw error begin after restart
![2015-07-04_16 45 11](https://cloud.githubusercontent.com/assets/4216742/8508334/4a39a00c-226c-11e5-94d2-1e938ea1f19f.png)
![2015-07-04_16 38 14](https://cloud.githubusercontent.com/assets/4216742/8508335/516888f2-226c-11e5-8942-0ee75a1668e5.png)
![2015-07-04_16 39 05](https://cloud.githubusercontent.com/assets/4216742/8508336/54eafe88-226c-11e5-88a3-b95330303c6d.png)
![2015-07-04_16 37 48](https://cloud.githubusercontent.com/assets/4216742/8508337/615568fc-226c-11e5-8c08-fa5172e40724.png)
![2015-07-04_16 26 17](https://cloud.githubusercontent.com/assets/4216742/8508339/76d065c4-226c-11e5-9c27-db1f38b6ac12.png)
![2015-07-04_16 27 21](https://cloud.githubusercontent.com/assets/4216742/8508341/79a07c9e-226c-11e5-99ba-3fb40dadcb73.png)
if I break the cable so the me system is off then the draw error decrease and after restart the draw error is gone

all my mods are up to date and I tried with older version as well

**Comment by yueh** [comment]
Not sure about rv2, but at least rv3 has an issue with it.
At least AE2 + bibliocraft or forestry works fine for me.

**Comment by datahunter** [comment]
Is there a place where I can get rv3 to test it?
