### ISSUE TITLE
Spatial pylons not deploying

### ISSUE THREAD

**Issue by cardinalsrulejd** [AppliedEnergistics/Applied-Energistics-2#1674]
I have duplicated this twice in Minecraft 1.7.10. SP I can store a building in a spatial storage cell, build pylons exactly the same dimensions somewhere else and it will not deploy. I have configured them exactly the same way. Is this a bug or am I doing something wrong. Seems like I can't find anyone who has an answer. But I can go back to where I got the building and deploy it there but not at the new location

**Comment by mindforger** [comment]
also the same orientation, when not square in x and z dimension

**Comment by cardinalsrulejd** [comment]
Awesome worked perfectly. Thank you! I have my base back lol. Could this please be put on a wiki or something. Thank you.
Sent from Yahoo Mail on Android
