### ISSUE TITLE
Export bus in a subnetwork can't pull from main network

### ISSUE THREAD

**Issue by Baughn** [AppliedEnergistics/Applied-Energistics-2#1676]
![2015-07-03_23 47 11](https://cloud.githubusercontent.com/assets/45811/8505466/f23d2b28-21dd-11e5-8218-e1394b3bdc40.png)

I have an export bus set to export ethanol crystals. This works if it's directly connected to the main AE network, but not for the small subnetwork shown above, consisting of one storage bus, three export buses and an ME terminal for checking. Said export buses do not appear to be working at all, though I haven't checked with local storage.

**Comment by yueh** [comment]
#495
