### ISSUE TITLE
"Connection already exists" when re-placing a P2P

### ISSUE THREAD

**Issue by utoc** [AppliedEnergistics/Applied-Energistics-2#1677]
I'm reporting an error condition in our logs.  There is no crash and as far as I can tell, everything works as it ought to.  This occurs when linking two P2Ps after having broken the farthest end to move/replace cable.  After shift-right-clicking the P2P on the ME Controller with the memory card, this error comes up on the console when right clicking the P2P on the opposite end.

http://pastebin.com/raw.php?i=DeWnAMAQ

The link above is a much cleaner representation of the issue.  Let me know if I can help in any way.

**Comment by yueh** [comment]
This is just a notice, that something tried to create a new connection between something already connected.
