### ISSUE TITLE
[request] gas p2p

### ISSUE THREAD

**Issue by Tsunayoshi** [AppliedEnergistics/Applied-Energistics-2#1680]
Hi,

I have a request for the future. It would be nice if you could support the gas pipes from mekansim for p2p. Enderio has added a gas conduit recently, therefore my idea.

**Comment by yueh** [comment]
#582

**Comment by MyDeloreanWontStart** [comment]
Afaik gas Api is very buggy. Mekanism gas conduits have an annoying habit to delete machines its connected to, and extracells gas integration is going slowly and buggily.  Just make it into liquid and put it through fluid p2p until gas is polished a bit.

**Comment by Tsunayoshi** [comment]
sry for the dupe.
@MyDeloreanWontStart thank you for that! :+1:

**Comment by MyDeloreanWontStart** [comment]
Just my duty to prevent a repeat of the great Gas Tank Disappearances of '15
