### ISSUE TITLE
CPU's offline while connected

### ISSUE THREAD

**Issue by nightstalker6669** [AppliedEnergistics/Applied-Energistics-2#1682]
http://puu.sh/iOghq/5fc8098de1.jpg

using forge 1481 and stable 9 build of AE2 my CPU's will randomly go offline. they are direct connected to the controller and power is always on. the cables still show they are connected (as noted in the picture) but they are registered as offline and will not craft anything.

http://puu.sh/iOgrH/531884ab0b.jpg

now as you can see in the picture if i place a cable anchor next to the CPU then it updates and comes online, and stays online for a random amount of time. if i leave and come back sometimes it will be online, most of the time it will be offline.

**Comment by yueh** [comment]
Duplicate

**Comment by nightstalker6669** [comment]
duplicate of what i may ask? i looked through the open tickets and didn't see anything familiar.
