### ISSUE TITLE
Meteorite glitch

### ISSUE THREAD

**Issue by AgentK9** [AppliedEnergistics/Applied-Energistics-2#1688]
A bajillion meteorites right next to each other...
![2015-07-06_19 02 33](https://cloud.githubusercontent.com/assets/11563088/8535228/e31a5478-2411-11e5-9ed1-c5c8e99a6533.png)

**Comment by AgentK9** [comment]
This is NOT a visual glitch. To top it all off, the seed was RANDOM!!! Mesa and glitch? CRAZY

**Comment by yueh** [comment]
#397

**Comment by MyDeloreanWontStart** [comment]
This has happened to everyone has it n:-P

**Comment by ate0ate** [comment]
Wow, I just encountered this for the very first time in rv2 stable 10. Lets hope it doesn't happen again lol.
