### ISSUE TITLE
NOOO My Items!!!

### ISSUE THREAD

**Issue by DahDude** [AppliedEnergistics/Applied-Energistics-2#1691]
Im completely and utterly unable to access any items in my system. Ive been running Sky Factory 2 for a while and everything was working. Not even touching my AE System, I was actually making a Big Reactor. But then I tried to wirelessly access my AE for some blocks. And my FPS when down from 50 to 1. And stayed there till I managed to lag out of the terminal. I then tried to access it manually and continued to lag. I still cant access my items. I have re installed the pack. Ported it to a server, and done everything I can possible think of to fix it. Still it is not working. It doesnt even error my logs. Just, doesnt work. Please help me. Thx

**Comment by jHoyne** [comment]
Did you try taking the drives out and putting them back in, cutting power
to the network, or putting the drives in an me chest.

Joseph Hoyne

**Comment by Lodran** [comment]
Is your system powered properly?  When this happens to me, I disconnect my ore processor (the biggest power draw) and things usually come right back.

**Comment by DahDude** [comment]
My only ore processing is my one mining laser. And I have diconnected
entire p2p connections from my system. The terminal lags even when I
disconnect it from my system and just try to open it. My fluid storage
works fine. Its really strange on behavior and only lags when its open. My
FPS is always fine when I walk around. I tried locating the culprit by
looking around but it refused to work

**Comment by Zaflis** [comment]
Tried breaking the security station and wireless access point? You didn't say if you had an energycell in the network. Wireless can be using so much power it's repeatedly causing the system to run out of power.

**Comment by DahDude** [comment]
I have a full resonant energy cell attached to my system it is not power issues. I think I have found the issue. AE2 stuff was the  main culprit.

**Comment by Zaflis** [comment]
But no AE2's energycells at all? There is a big difference to internal buffer and external energycells.

**Comment by DahDude** [comment]
No but I don't think u really understood. It's FPS lag not anything else. The server doesn't lag and the power source is just fine.

**Comment by yueh** [comment]
Could this be related to  #1671?

I would recommend removing AE2stuff. It feels really like it is designed to break AE2 on different levels and it already had some known performance issues in the past.
The next possible culprit is probably ExtraCells (see #1621)

**Comment by DahDude** [comment]
Strangely enough, my Fluid Storage system does not lag at all. It works
just fine. I will check my more detailed log however as some things may not
be appearing within my servers console

**Comment by Zaflis** [comment]
@DahDude I don't think you really understood. Here's 1 example http://i.imgur.com/RNmDBlC.png Looking at my small network in creative world, with 100k output Creative energycell attached to 2 ME controllers is seemingly losing power all the time. Observably the network is receiving power from RF source one tick every 2 seconds. See the math of Max power 32k, stored power 21k and energy use 126 RF. You would normally expect the stored power can't get that low. Also the max power is 32k only because 2 ME controllers give 16k each, a network with just energy acceptor has max energy of 0. Check it out with a network tool to see for yourself. We cannot guess what the situation is.

AE2stuff might react in bad way with devices when running out of power. Even the default AE2 with my miniscule 32k power with 100k RF/t incoming had my ME terminal temporarily shutdown because i put inventory full of cobblestone in at once. Depending on your game lag and other things, it might appear differently, maybe even as fps lag.

**Comment by DahDude** [comment]
Actually I added 9 dense energy cells to my system to test. They all filled up in about 10 seconds. Im sure it is NOT power issues

**Comment by Lodran** [comment]
@DahDude,

> I have a full resonant energy cell attached to my system it is not power issues. I think I have found the issue. AE2 stuff was the main culprit.

Which AE2 machine was causing the issue?

> AE2stuff might react in bad way with devices when running out of power.

It has in my system, but by machines locking up, not by causing lag.

**Comment by DahDude** [comment]
None. Just the mod being there in general was bad but by upping my RAM up to 7gigs was also helpful. Still getting around 6-7 frames but now I can actually do some stuff in my system. Still I have no idea why having the little amount of items I have it could be so laggy. It might be the mass inlets and exports going simultaneously. I'll do some tests on that

**Comment by yueh** [comment]
[Profiling](http://ae-mod.info/Profiling/) is really needed here to track it down.

**Comment by DahDude** [comment]
Alright, well AE2 Stuff should NOT be used. I removed it from my client and then everything started to work. Im not sure how it could have caused the problem though as I never placed a single block from that mad and did not even know that it was in the pack until this issue occurred.

**Comment by kimius** [comment]
I had the same problem, the cause was in Bedrock drum full of water with fuidstorage bus/ fluid terminal work fine, but item terminal fps drop
