### ISSUE TITLE
Constantly having to break and re-attach cables to get devices online

### ISSUE THREAD

**Issue by joeltinez** [AppliedEnergistics/Applied-Energistics-2#1692]
It seems like I'm constantly having to break and re-attach cables to get my AE network devices back online after a power loss or adding new devices. 

For example, my base just lost power, and when I got it back up, all devices in AE were still saying "device offline", but after breaking the attaching cable and re-attaching it was fine.

**Comment by mindforger** [comment]
which version of AE2, which device types in particular? did you check your wiring for strange loops (devices itself acting as an 8channel cable you know)? you need to post some more information to give the devs a chance to reproduce the issue and to solve it ... "things not working" is not helping at all

**Comment by joeltinez** [comment]
Using rv2-stable-9. I wasn't aware the system could "loop". Are there examples of what a loop looks like somewhere?

Yes, I use the occasional ender IO ME conduit throughout the system. 

I noticed some similar issues fixed by rv2-stable10, I'll try to upgrade and see what happens.

I was hoping the answer would be "it's a known issue, we're working on it" as this seems like it would affect a larger number of people.

**Comment by yueh** [comment]
#1611
