### ISSUE TITLE
Wireless Terminal Enhancement

### ISSUE THREAD

**Issue by gabor6505** [AppliedEnergistics/Applied-Energistics-2#1693]
I think it would be a good idea if we could colour the ME Wireless Access Terminals. People who have multiple sub-networks, with different colored cables (and terminals of course), like red for Blood Magic, lime for Botania, purple or magenta for Thaumcraft etc. And if I want wireless access to like every network, it would be a much easier way of searching the terminals in my inventory (even if I think I can rename them). The colours will be the same as all the other things: Fluix (the normal one) and than the 16 different coloured Wireless Access Terminals. It's just a minor enhancement.

And another thing I would like (and I think a bunch other people as well) are the Wireless Crafting Terminals. This might be too Overpowered, but it's just a suggestion, maybe that's why you didn't already added this Crafting Terminal in the game. But I think at least a Portable Crafting Cell would be a good idea. (and maybe the Portable Cells in multiple colours)

I hope these are good suggestions.

**Comment by yueh** [comment]
1) Would be a small improvement. Including the cell. Also would be more consistent with other things like chests or crafting monitors which are already colourable.

2) No.

**Comment by gabor6505** [comment]
Thanks for the quick response. I'm glad you like my suggestion. :smile: 

ME Chests and Crafting Monitors are colourable too ?

**Comment by jHoyne** [comment]
​Why not just put an storage bus on the sub networks so you can see what is
on them from the main network w/ the searchbar in the wireless terminal. ​

On 9 July 2015 at 11:42, gabor6505 <notifications@github.com> wrote:

> Thanks for the quick response. I'm glad you like my suggestion. [image:
> :smile:]
>
> ME Chests and Crafting Monitors are colourable too ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1693#issuecomment-120064829>
> .
>



-- 
Joseph Hoyne
Twitter <https://www.twitter.com/JosephHoyne>
Github <http://www.github.com/jHoyne>

**Comment by gabor6505** [comment]
I actually did that in Agrarian Skies 2, so that I can separately see the things on a subnetwork's terminal and i can access it from the main network's terminals and wireless terminals too, but I like to see things much clear, so like only the blood magic stuff, and I can also say that I can specify the things stored in the subnetworks with the storage buses, but Wireless Access Terminals don't have the ability to actually filter out with View Cells.

I think I wrote this very intricately, but I think you get the idea.

**Comment by MyDeloreanWontStart** [comment]
By the way, why no wireless crafting terminal? hard to code?

**Comment by yueh** [comment]
#401

View cells for WATs would also be an idea (but should be another isse)

**Comment by Xemiru** [comment]
@MyDeloreanWontStart Was answered in another issue, though I don't which. It was mainly along the lines of the function of the mod should already provide enough automation where a wireless crafting terminal wouldn't exactly be necessary. In fact, it's deliberate--if you still need something like that then you "haven't utilized the mod to its full potential."

**Comment by Mementh** [comment]
wireless crafting is not imho overpowered.. it would be cluttering up the screen..  but having the option on a sub screen for a big cost would be ok? and a power increase in usage of course!

Also instead of coloring the terminal.. why not have a option to select networks at the top or side? 
The terminal would keep track of networks it knows, and if in range it can open them!

**Comment by thatsIch** [comment]
power is never a good balancing mechanic.

the idea is that you already have the possibility of a wireless crafting terminal by automate every crafting possible in your base and order it.

**Comment by Mementh** [comment]
true.. but what could be in a end game situation or with someone that has alot of time to do things?

we already have rare mats that are a bit hard to get but once you do they are low key

we have hard to get crystals 

.. not sure what could be done

**Comment by Cloudftw** [comment]
[https://minecraft.curseforge.com/projects/wireless-crafting-terminal](url)

**Comment by Technici4n** [comment]
Not going to implement colorable wireless terminals for the foreseeable future. View cells would be nice though.
