### ISSUE TITLE
Feature Request: Add advanced fuzzy card for filtering by item name & ore dictionary

### ISSUE THREAD

**Issue by thedevil259** [AppliedEnergistics/Applied-Energistics-2#1697]
Add a new type of fuzzy card in which you can enter the item name or the ore dictionary name of the type of items you want (basically a text filter). Something like the Logistical Sorter from Mekanism.

With this card it would be possible to set up the ore dictionary filter "ore*" to export all my ores with a export bus out of my system.

Or another example it would be possible to set up a view cell to show all dimlets (an item from RFTools) by setting up a name filter "*dimlet*". By this every item with the word "dimlet" in it's name would be shown on my terminal.

**Comment by yueh** [comment]
No and I recommend reading #1000 and why text based filtering is inherently broken.
