### ISSUE TITLE
Inscriber recipes do not use ore dictionary

### ISSUE THREAD

**Issue by twothe** [AppliedEnergistics/Applied-Energistics-2#1699]
I just noticed that most of the Inscriber recipes do not use the ore dictionary. This makes it a bit difficult to adjust compatibility with other mods. Especially the silicon recipes should be using the ore dictionary, as those are present as well in the often combined Galacticraft and ProjectRed mods.

**Comment by yueh** [comment]
AE2 is by default using the oredict entries, you can view it [here](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/main/resources/assets/appliedenergistics2/recipes/new.recipe).

It is out of your hands, if your modpack is changing them and not using oredict entires or the mentioned mods are not oredict their items.
