### ISSUE TITLE
Z-fighting of facades on terminals

### ISSUE THREAD

**Issue by Kubuxu** [AppliedEnergistics/Applied-Energistics-2#1700]
Placing facade on terminal causes z-fighting. Terminal should be visible in whole.
![2015-07-12_08 44 30](https://cloud.githubusercontent.com/assets/2259282/8636751/49f76fa0-2872-11e5-88ca-4329554539c2.png)

**Comment by yueh** [comment]
Which facades are these? The hitbox seems not to fit the normal AE2, FMP or BC2 ones. All of them would have a hitbox around the terminal and not the full block.

Also any mods like Optifine? (If yes, still appears without them?)

**Comment by Kubuxu** [comment]
No Optifine, just Fastcraft (but it doesn't mess with rendering) and those are Hollow Brick Covers from Immibis Microblocks.

**Comment by yueh** [comment]
Could also be an issue with immibis as it handles the other sides fine and just the top one is affected.
The 2 affected pixels should also match a normal hollow cover (as the hole is smaller than a terminal), maybe just a off-by-one error and the top is not testing for any collisions like the other sides?

**Comment by yueh** [comment]
Maybe @immibis can provide some insight?

**Comment by thatsIch** [comment]
I dont tihnk @immibis is very active on GitHub
