### ISSUE TITLE
Certus Quartz not spawning in any dim

### ISSUE THREAD

**Issue by tethlah** [AppliedEnergistics/Applied-Energistics-2#1701]
I've thoroughly checked Aroma Mining Dim, Overworld, The End, everything.  We don't have a single piece of Certus Quartz anywhere.  Now, MFR Drills are returning regular Certus, but other than that I can't find any.  Certus Quartz world gen is set to true, is there something else that can block Certus ore gen?

**Comment by yueh** [comment]
There is also a whitelist in the config, which by default only allows spawning in the overworld.
You have to either add the dimension id by yourself (not retroactive for existing chunks) or the better alternative is that the used mod does notify AE2, that it is allowed to spawn it in the newly created dimension.

**Comment by tethlah** [comment]
Where is this whitelist?  I'm looking in the AE2 config folder.  Like I said before, AppliedEnergistics2.cfg says world spawn is enabled, but it's not there.
