### ISSUE TITLE
Quantum Bridge sometimes stops working after a server restart (parts not connected)

### ISSUE THREAD

**Issue by kim-yannick** [AppliedEnergistics/Applied-Energistics-2#1702]
On my server, I have a really complex AE system. Sometimes, when the server is restarted, the parts of some of my Quantum Bridges disconnect. Replacing a block works, but is annoying.

![2015-07-13_14 02 55](https://cloud.githubusercontent.com/assets/10467401/8649239/833d90ea-2968-11e5-93d3-ad6c9e140432.png)
![2015-07-13_14 06 43](https://cloud.githubusercontent.com/assets/10467401/8649240/833efafc-2968-11e5-8c4d-38b90de4df9a.png)

I am playing the Infinity modpack version 1.7.0, which contains AE2 RV2 Stable 9.

**Comment by yueh** [comment]
Are you using cauldron or something similar?

**Comment by kim-yannick** [comment]
No, I am using the "vanilla" Infinity server.

**Comment by yueh** [comment]
Can you please post the `settings.cfg` inside your save/world folder on pastebin?

**Comment by kim-yannick** [comment]
The file is really big, Pastebin (also Hastebin) won't accept it. I have uploaded the file on Dropbox.

https://www.dropbox.com/s/na0y1j46xgqb28s/settings.cfg?dl=1

**Comment by yueh** [comment]
This is a huge amount of networks. Is your world really using about 8000 ME networks?

**Comment by kim-yannick** [comment]
I dont have so much Networks.

There should only be three:
- The Main Network
- A Subnetwork with about 5000 64k Cells (but in a single network)
- A not connected ME controller just for the look.
Am 15.07.2015 22:09 schrieb "yueh" <notifications@github.com>:
>
> This is a huge amount of networks. Is your world really using about 8000
ME networks?

**Comment by yueh** [comment]
Most AE2 blocks/parts (anything a cable connects to) form their own network and then join with adjacent blocks to form a single large network. As these still need to persist some data shared by the whole network, this is done inside the settings.cfg as the usually spawn over multiple chunks and saving that as normal NBT would be a nightmare to manage (the `gridstorage` block)

As you said you only have 3 networks, it should also only contain 3 networks (except if you have like 8000 free standing interfaces or so somewhere).
But no idea why there is this ridiculous amount of networks in the case of just 3 networks.
Does the infinity pack contain any other mod with an AE2 integration? A world download might also be an idea.

You could create a backup and delete the `gridstorage { ... }` block to reset it, but this should be really done by AE2 itself...

Also you should monitor the `lastGridStorage` counter, this should not increase without changing anything between saving the world (not deleting the block for this)

**Comment by kim-yannick** [comment]
Sometimes when I connect my 16x16x16 Crafting CPUs, after some time beeing
not on the server (I think that has something to do with the daily restart
of my hoster), my ME controller flashes gray for a tick and then it will
reconnect to the parts. If that happened, it will turn gray again.
Disconnecting and reconnecting the CPU fixes the problem (and the super lag
of about 4 TPS (not FPS))

I have a quantum bridge in another dimension, which is connected to parts
of my autocrafting.

Now the thing could be, that if the quantum bridge lost connection, the
part goes as its own network. If this does happen again and again, maybe
that made the file so large.

The thing with the flashing of the controller could also be a bug, but this
is hard to describe.

I could host a download, but the file is i think 2 GB in size (compressed).
I have 20 MBit/s Upload, but it can a long time though. I also need so much
webspace.

If the download is the only option, i will upload it and say where the
parts of the networks are. Note that i destroyed the Crafting CPU so it
wont connect anymore and i disconnected some parts of the network because
of TPS loss. The problem seems not to happen again if the CPU is
disconnected.
Am 16.07.2015 00:09 schrieb "yueh" <notifications@github.com>:

**Comment by yueh** [comment]
2 GB is way too large.

The controller reset indicates that the network is somehow reset and it needs to rebuild itself. But this should not really affect the TPS that much. This is really something where we need a [profile](http://ae-mod.info/Profiling/), but this might not be possible with the hoster.
There are a few worst case scenarioes, which can affect the TPS in that way. But that only happens with constant chunk reloading. Maybe the hoster is using some more aggressive chunk unloading to save some resources? (If I remember correctly, similar issues were always in combination with some server hoster)

It might be an idea and try to build the larger structures like QNB and crafting cpus inside a single chunk. So unloads will not destroy them.
