### ISSUE TITLE
Security system messing up

### ISSUE THREAD

**Issue by ThereIWas** [AppliedEnergistics/Applied-Energistics-2#1704]
Im playing sky factory 2 and i got a security system for my me system and it wouldnt let me put the card into the security terminal so i got rid of it and it sometimes doesnt let me take stuff out of my system so i have to break the energy accepter to fix it but it keeps on messing up

**Comment by jHoyne** [comment]
Is it on server or local. Sounds like sync.

On 13 July 2015 at 19:41, ThereIWas <notifications@github.com> wrote:

> Im playing sky factory 2 and i got a security system for my me system and
> it wouldnt let me put the card into the security terminal so i got rid of
> it and it sometimes doesnt let me take stuff out of my system so i have to
> break the energy accepter to fix it but it keeps on messing up
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1704>.
>



-- 
Joseph Hoyne
Twitter <https://www.twitter.com/JosephHoyne>
Github <http://www.github.com/jHoyne>

**Comment by yueh** [comment]
Can you post the `settings.cfg` inside your world folder on pastebin?

**Comment by ThereIWas** [comment]
its on a singleplayer world i was getting the security terminal for a wireless accesses point

**Comment by BoWhackem** [comment]
Im having a simular issue with a dedicated server. What should be validated from the settings.cfg?

**Comment by yueh** [comment]
Not validated, we need to look at it.

**Comment by yueh** [comment]
No further feedback, also look at #1266
