### ISSUE TITLE
BetterStorage API incompatibility

### ISSUE THREAD

**Issue by LogicalEnigma** [AppliedEnergistics/Applied-Energistics-2#1706]
I'm a noob when it comes to this, but my best guess is that the meteor generation isn't working well with one of my other mods.

I just downloaded the mod. I can't even start a game without it crashing within seconds of moving around.

The game runs at about 11 frames per second before shutting off completely.

Are there any dependencies that I'm unaware of?

Prerequisites?

Should I change my maximum render distance?

What am I missing here?

http://pastebin.com/mi7fzNWH

**Comment by yueh** [comment]
Looks like BetterStorage did change their API and we missed to validate it.
Your best option is to disable the BetterStorage integration in the AE2 config until it is fixed.

**Comment by yueh** [comment]
Also keep in mind that your version of BetterStorage is horribly outdated and no longer supported.
So the only fix we can provide is to automatically disabled the integration.
