### ISSUE TITLE
Server lag when crafting

### ISSUE THREAD

**Issue by Time6628** [AppliedEnergistics/Applied-Energistics-2#1707]
The problem is that whenever someone shift clicks items from a crafting terminal  the entire server lags until it's done.
I expected the items to come out, not lag the entire server.
Reproduce it by trying to craft quintuple cobble from ExtraUtils. and shift-clicking them out.
Server.
Karma(ATLauncher). rv2-stable-3.
No crash log.
No screenshots.

**Comment by yueh** [comment]
#127, #1448

**Comment by Time6628** [comment]
Yes but what is the fix for it?
