### ISSUE TITLE
Server Crash on Startup

### ISSUE THREAD

**Issue by king05** [AppliedEnergistics/Applied-Energistics-2#1708]
Hi,
after i Updated AE2 to the newest version rv2 stable 10, I got this crash report:
http://pastebin.com/yVYeay0s
http://openeye.openmods.info/crashes/1923f148c318e7594cb3a7daca1a6c1c
The first crash came after 1 day and since this first crash my server is crashing each time i want to start the server.
Hope you can help me.
king05

**Comment by yueh** [comment]
Looks like the TileEntity for the meteor compass is for whatever reason missing. But no idea why currently.

Could you make a backup of the world and try to load it with AE as the only mod?

**Comment by king05** [comment]
Ok, it works with only AE....
Thank you for your fast response...
I'll search for the issue and let you know when i found it.

**Comment by king05** [comment]
Hi,
I just got the crash again... I have started the game everytime with an new mod (started with ae2) and the same world...
After i installed Mystcraft12.0.00 or 12.1.00 i got this crash....

**Comment by yueh** [comment]
Currently no idea which mod interactiong might cause it, please reopen when you can provide something reproducable.

**Comment by king05** [comment]
I don't have an plan what causes it.... after i started a new map it works fine.... but thanks for the help
