### ISSUE TITLE
Crafting Terminal sporadically destroying items

### ISSUE THREAD

**Issue by stephanstross** [AppliedEnergistics/Applied-Energistics-2#1711]
When I attempt to put items into my AE system through the crafting terminal, they usually go in fine. Occasionally, though, when shift-clicking OR dragging and dropping, the system will sometimes consume  the entire stack. They're not being automatically put into a processing machine, and I'm not searching for anything. The drive usage also does not change. When I reload the world, the items stay gone, and nothing has changed. It seems that the system is randomly destroying ItemStacks rather than storing them. As well, no information is printed to the console during these events.

**Comment by yueh** [comment]
How about giving some details about which version you are using?

**Comment by Zaflis** [comment]
Do you have a trashcan connected with storage bus to the system?

**Comment by stephanstross** [comment]
No, I don't have a trashcan connected to the system, but I DO have Condensers from ProjectE. I'm using the latest version of the resonant rise 3 modpack, and I think it might be the storage buses connected to condensers, because those will destroy items. I'll check that out.

**Comment by alexandereliot** [comment]
The condensers are definitely it if you've not looked into it.  I was having the same issue and I disconnected them all.  And the AE network is storing items again like it should.
