### ISSUE TITLE
Spatial Chunk at 0x0

### ISSUE THREAD

**Issue by desagas** [AppliedEnergistics/Applied-Energistics-2#1712]
As a suggestion:

When you import to a Spatial IO drive, the dimension created starts at +1X and +1Y. This means, my 1x1 chunk (16x16 blocks) import will take 4x4 chunks in the drive, as chunks start at 0 and 0. If I am storing machines for use in this dimension, it would be easier on my hardware to load 1x1. This is not major for 16x16 spatial drives or lower, but when you get to 128x128 spatial drives, 1 extra block makes it add 17 extra chunks to account for the 1 block difference on each side, which would be a little easier on my hardware.

To recreate, you need to set up pylons however you want (I have tried many ways) to create a 16x16x16 internal storage space. From there, if you have the ability to check chunk borders, they are one block off the actual space.

I think it would make sense if spatial storage started at 0 and 0 XY instead of at 1x1.

Thank you.
Using AE2 RV2 - Stable 4 build

**Comment by yueh** [comment]
I do not think this is currently possible without breaking every existing dimension. So only an option to implement for a new minecraft release.

Also keep in mind that each chunk maybe about 256-512kb additional memory, even with 17 additional chunks it is like 4-8 MB. As the additinal data just contains some simple blocks, these will not really affect the performance as they do not do anything. What causes issues are the constantly operating machines and for them it is irrelevant, if stacked into a single chunk or spread over multiple ones.
So if a couple of MBs as memory requirement is already an issue, then there should be more serious issues existing as minecraft itself is allocating a multiple of this each second.
