### ISSUE TITLE
Imported Items Count Multiple Times When Multiple Crafting Jobs.

### ISSUE THREAD

**Issue by kurosnow** [AppliedEnergistics/Applied-Energistics-2#1713]
As the title says, if you have two crafting jobs to craft the same item (realized you didn't have enough, or just needed more for another thing you were working on at the same time), when they get imported back to the system, they get counted once for each crafting job.

Steps to recreate: make a set up to craft something outside of the system (e.g. furnace, etc, I did this with Railcraft's rolling machine, but double tested it with redstone furnaces from thermal expansion), then tell the system to craft that multiple times across multiple jobs one after another, then have it import the finished product back into the system.

**Comment by yueh** [comment]
Cannot reproduce it. 

I have setup a network with 4 crafting cpus for "cobble => stone". Interface is dumping the materials into the furnace, import bus to obtain the output and an export bus to keep it stacked with coal.

Requesting 4 jobs of a couple of stacks of stone works without any issue. Each crafting cpu is separate from the other ones and not counting any item multiple times as well as the total amount is as expected .
