### ISSUE TITLE
ME network is read only. Loss of access. 

### ISSUE THREAD

**Issue by BoWhackem** [AppliedEnergistics/Applied-Energistics-2#1714]
Hi, 

Server: Dedicated 1.7.10 FTB infinity 
Issue:  After building the security terminal and adding biometric cards of other players it works great for awhile and then everyone looses write access to the network items. If a player picks up the security terminal and places it down, only that person has access and the terminal will not accept biometric cards. So we have a network with items stored but only one person has access to deposit items and craft items. 
Ive seen this issue posted previously and a settings.cfg was requested. What should i look for in my settings.cfg to resolve the issue? 
Any help or suggestions would be greatly appreciated.

**Comment by yueh** [comment]
Same as #1704
