### ISSUE TITLE
[Feature] Please add a Push/Pull Upgrade Card for interfaces

### ISSUE THREAD

**Issue by twothe** [AppliedEnergistics/Applied-Energistics-2#1715]
To make interaction between mods easier, it would be great if there was an upgrade card for the interface that makes it actively try to push items in adjacent inventories and pull them out again.

I know that a similar behavior can be archived by adding an export and an import bus to the machine, but often you just don't have the room for more than one interface. In these cases having this push/pull behavior on the interface would be much appreciated.

**Comment by yueh** [comment]
No. See the [guidelines](http://ae-mod.info/Suggestion-Guidelines/).
