### ISSUE TITLE
Eye floaties when using storage monitors

### ISSUE THREAD

**Issue by tenten8401** [AppliedEnergistics/Applied-Energistics-2#1717]
On my server with AE2 on it, the shop is powered by me storage monitors. Sometimes it gets really weird and items float around your screen. We removed the shop and no floaties. See https://www.youtube.com/watch?v=VQsbdqkffbo

**Comment by yueh** [comment]
#1673, I will reopen it, when someone can provide some hints on how to reproduce it with rv2.
