### ISSUE TITLE
Allow customization of the p2p tunnel attenuation items

### ISSUE THREAD

**Issue by ruifung** [AppliedEnergistics/Applied-Energistics-2#1719]
For example, I wish to use the RF P2P tunnel, but have neither EnderIO or Extra Utilities installed. It works with Mekanism universal cables - but there is no way to get the RF tunnel without either a conduit or a energy pipe.

Because of that, it would be useful if there was a config option to set what items will attenuate a P2P tunnel to a specific type.

**Comment by yueh** [comment]
The listing on the side is just an example, not every possible option and thus might be incomplete. This is mainly caused as each mod can register attunements via IMC messages.

I personally would prefer to not force a player to deal with item ids/stacks directly in the config as these are nowhere documented ingame. So without digging through some debug data or the actual code and then there are still many pitfalls left (metadata etc).

For RF it should work with most of the large mods (BC, TD, Mek, EIO).
The best option would really be, if mod devs would just send the IMC directly. This is way easier for anyone. The users do not need to deal with it at all, we do not need to monitor every possible mod which might transfer RF (or something else) and what they might change or add, and as it is IMC based there is absolutely no need for the mod devs to depend on the AE2 API, just a single line of code for each attunement.

**Comment by ruifung** [comment]
Right. So in other words its up to the target mod to send a IMC to register?

**Comment by yueh** [comment]
For having the most recent updates, yes.
We simply cannot monitor every mod and make a new build every time they add some new RF block or whatever else P2P type might apply.

There should also be one or two mods which allows you to define IMC messages with some JSON configs, if anyone needs it now and cannot wait some time for the mod devs to handle it.

But we should probably update the P2P page, some entries supported by us are missing. Like BC pipes/engines, TD ducts, TE cells/dynamos for the RF attunement or XU generators.

**Comment by ruifung** [comment]
Btw, where is the documentation for AE's IMC and Java API's located?
