### ISSUE TITLE
Crafting one item at a time for in-world crafting.

### ISSUE THREAD

**Issue by Smtgr14** [AppliedEnergistics/Applied-Energistics-2#1722]
Some mods craft multiple items into one using in world crafting, like botania's terrasteel aglomeration plate. Using AE for mass crafting will cause all items to output at once instead of once recipie set at a time. Can we get an option to configure crafting patterns such that the item being crafted must wait x seconds or for it to enter the network before the next one crafts?

**Comment by yueh** [comment]
The job of the crafting cpus is to manage the overall operation and to ensure materials are available and perform them in the right order. Without any concept of time interfering with it.

Not to micromanage every single crafting operation and ensure that these are perfectly timed or items delivered in the correct order.
This will add a huge complexity to something not needing as well as creating way too many possible issues breaking it as the timing in minecraft is not perfect or the ability to track items.
For example manually putting a terrasteel ingot into the system while it is crafting, can count as the current crafting is done and proceeding with the next ingot, thus breaking it by dropping too many items into the world.

If some crafting operation needs a specific order or timing, then this should be handled locally in a build exactly for these requirements. Both AE2 and Botania provide ways to automate this specific task.
These might be a bit more complex, but we should respect that some mod authors want you to think about the build and it should not be as easy as slap an interface to an open open crate and be done.
