### ISSUE TITLE
AE2 possibly crashing server running Infinity 1.7.0

### ISSUE THREAD

**Issue by p75369** [AppliedEnergistics/Applied-Energistics-2#1724]
http://pastebin.com/SFk9F3ax
http://pastebin.com/U6EB9PsG

I can't read these things, but I can see AE mentioned, so I figured I'd post this here for you folks to have a look.

Basically, a friend has recently started work on her base in an RFTools void world, so far, all she has really done has been her AE system.

Since she started, the server has been crashing once or twice a day, seemingly at random, with or without online players.

**Comment by yueh** [comment]
The crash itself happens while reading corrupt data, nothing we can really recover from.

As you mentioned a RTTools world, maybe they have some issues with it?

**Comment by p75369** [comment]
Any indication of what it's trying to read?

**Comment by ruifung** [comment]
Well, the chunkloader appears to be involved and its a error loading NBT data, I'd say you probably have corrupted world files somewhere. It doesn't say which files are corrupted though.

**Comment by p75369** [comment]
Ok, thank you
