### ISSUE TITLE
Adding PneumaticCraft P2P tunnel part

### ISSUE THREAD

**Issue by MineMaarten** [AppliedEnergistics/Applied-Energistics-2#1726]
I was looking into adding P2P support for PneumaticCraft. After looking into the AE2 source it seemed not doable through the API. As OpenComputers also has PR-ed in their P2P tunnel implementation, I was thinking I could try and do the same :).

Let me know what you think, if you guys still want to support additions like this in the 1.7 branch and such. And if you'd like me to PR it, for which branch (master or rv2)?

**Comment by yueh** [comment]
Yes currently not supported by the API, we would also need to ASM transform them onto our base.
We plan to add a real registry to the API for it, but I slightly fear transforming random stuff can go horribly wrong.

Not sure about integrating it currently, most likely need to discuss it with @thatsIch.
But our current stance is mostly to not include mod specific P2P tunnels. That is for example the reason why do not support something like Mekanism gas as this could in general be done with fluids.

OC is a bit special here as there does not exist something like a common network protocol to communicate in a heterogeneous network. If it would, I am pretty sure we would drop the OC support in favor of it.

If it would be ok, then master as target. rv2 is in feature freeze.

**Comment by Entoarox** [comment]
@yueh You could implement the PneumaticCraft p2p as a generic 'pressure' p2p, even if as far as I know MineMaarten is currently the only one actively using pressure in this fashion.
