### ISSUE TITLE
ME System going blank

### ISSUE THREAD

**Issue by LordAwesomness** [AppliedEnergistics/Applied-Energistics-2#1727]
FTB Infinity 1.7.0 Multiplayer server

Every now and again, every ME Terminal (and Crafting Terminal) in the network will go blank, all the items seemingly disappearing. This issue happens at random intervals, sometimes five minutes in-between, other times several hours. I haven't found anything in common with the times this happens, it can happen whether I'm home or away. The only way I've found to fix the issue is to break the ME Controller and place it back again, and that's only a temporary solution.  

Server restarts don't affect the frequency of the issue, and the person I'm living with has the same issue at the same time. A few other players on the server have mentioned the same problem on their own networks as well. Any ideas for what could be going wrong here? 

Included screenshots show that it isn't an issue with channels, and the actual blank inventory in an ME Terminal.

![2015-07-20_19 02 18](https://cloud.githubusercontent.com/assets/13425916/8790295/e0ba3b2a-2f11-11e5-83a3-56f5f5db8436.png)
![2015-07-20_18 57 11](https://cloud.githubusercontent.com/assets/13425916/8790245/3f3a88b8-2f11-11e5-8a46-dc4e852f387f.png)

**Comment by yueh** [comment]
#1611
