### ISSUE TITLE
Annihilation Plane destroys items, doesn't store them.

### ISSUE THREAD

**Issue by piousminion** [AppliedEnergistics/Applied-Energistics-2#1728]
I'm using rv2-stable-10 with channels disabled in the config.

I have crystal growth accelerators set up with an annihilation plane and a storage bus on a subnetwork at the base. The storage bus is configure to only store pure crystals and fluix crystals.  Placing items in the water via any method causes the annihilation plane to instantly destroy any item and nothing is stored in the network, nor in any interface on the network.  The items are simply deleted.

**Comment by yueh** [comment]
Works for fine for me.

![filtered annihilation plane](http://i.imgur.com/vWUsMLt.png)

**Comment by piousminion** [comment]
I created the same exact setup from above on my server and configured the storage bus for pure crystals and fluix crystals.  Throwing anything in except the configured items causes them to be deleted.  Where do we go from here?

Note: idk if it's important, but as stated, channels have been disabled.

**Comment by yueh** [comment]
Test was done with disabled channels.

**Comment by piousminion** [comment]
Clearly I'm getting different results. What is your recommended course of action?

**Comment by yueh** [comment]
Provide a way to reproduce it on a small scale.

**Comment by piousminion** [comment]
Turns out Lunatrius' "Stackie" mod caused the items to disappear when tossed on the annihilation plane. An updated version causes the items to duplicate.  I'll take it up with him over at https://github.com/Lunatrius/Stackie unless you think there is something that can be done on this end.

**Comment by piousminion** [comment]
https://github.com/Lunatrius/Stackie/issues/5

**Comment by Lunatrius** [comment]
"Fixed" on my end by removing the related code. It caused too many issues (dupes/vanishing items) and the benefits are really not worth it.

**Comment by yueh** [comment]
Just want to make it a bit more sane in case some other mod has the same idea and start trying to stack them on spawning and probably some changes to prevent the last item from not despawning.
