### ISSUE TITLE
Cant Use AE2 In Game At All

### ISSUE THREAD

**Issue by robbooooo1234** [AppliedEnergistics/Applied-Energistics-2#1729]
so i have a custom modpack (Originally CrackPack 2) with multiple mods installed, and it isnt letting my view any crafting recipes with NEI and i cant actually make anything that is from AE2, i havent got any crashes related to AE2 at all and i have no issues with any other mods so I'm not sure why it is doing, this can anyone help? Thank you for your time in advance.
My list of mods is as follows (Not Inluding small/non content mods):

1) Damage Indicators 2) AE2 3) Archimdes Ships 4) Aroma 1997 5) BackPacks Mod 6) Better Chests 7) Biblio craft + Biomes O Plenty/Natura edition 8) Big Reactors 9) Biomes O Plenty 10) Blood Magic 11) Botania 12) Buildcraft 13) Carpenters Blocks 14) Chisel 2 15) Compact Machines 16) Computercraft 17) Crafting Pillars 18) Dense Ores 19) Easy Crafting 20) Enchridion 21) Ender IO, Storage and Tech 22) Extra Cells 23) Extra TiC 24) Extra Utilities 25) Factorization 26) Flans Mod 27) FlaxBeardsSteamPower 28) Flora 29) Forbidden Magic 30) Funky Locomotion 31) FZ Addons 32) Galacticraft 33) Grimoire Of Gaia 34) Growthcraft 35) HardCore Ender Expansion 36) Hats 37) Headcrumbs 38) IC2 Nuclear Control 39) IC2 40) Iron Chest 41) Journey Maps 42) Liquid Dirt 43) Malisis Doors 44) Mantle 45) Mariculture 46) Mekanism + tools and Generators 47) Metallurgy 48) MFFS 49) MineChem 50) Mine Factory Reloaded 51) MystCraft 52) Natura 53) Nether Ores 54) ObsidiPlates 55) Open Blocks, Computers + Peripherals 56) Pams harvestcraft 57) Peripherals ++ 58) Pneumatic Craft 59) Practicalities 60) Pressure 61) Project Red Base, Compat, Integration, Lighting + World 62) RailCraft 63) Random Things 64) Redstone Arsenal 65) Refined Relocation 66) REsonant Engine 67) Rougelike 68) Sanguimancy 69) Simply Jetpacks 70) SolarFlux 71) SpecialMobs 72) Steves Carts, Factory Manager + Workshop 73) SuperCrafting Frame 74) Tails 75) TConstruct 76) ThaumCraft, Exploration, Tinkerer + Infusion 77) Thermal Expansion + Foundation 78) TMechWorks + TSteelWorks 79) Translocator 80) Twilight Forest 81) Universal Electricity 82) WeaponMod 83) Witchery 84) ZTones

**Comment by robbooooo1234** [comment]
Please help, i really want to get an ME system set up and start using AE2 in my world

**Comment by jHoyne** [comment]
It works I bet you. Do you have power going into the system

On 21 July 2015 at 17:11, James <notifications@github.com> wrote:

> Please help, i really want to get an ME system set up and start using AE2
> in my world
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1729#issuecomment-123493975>
> .
>



-- 
Joseph Hoyne
Twitter <https://www.twitter.com/JosephHoyne>
Github <http://www.github.com/jHoyne>

**Comment by robbooooo1234** [comment]
No i cant even make anything that is in AE2 at all, cant even view the crafting recipes in NEI

**Comment by jHoyne** [comment]
Is this on server or single player

**Comment by robbooooo1234** [comment]
Single Player

**Comment by jHoyne** [comment]
Do you have the game logs

**Comment by robbooooo1234** [comment]
just the most recent log? i havent had any crashes or anything

**Comment by jHoyne** [comment]
The log that has the world load info so the most recent yes

**Comment by jHoyne** [comment]
If you take ae out does everything else work

**Comment by robbooooo1234** [comment]
http://pastebin.com/1xZG3Cpb I think this should be the right one

**Comment by robbooooo1234** [comment]
everything works fine even with it installed, it just doesnt work in game. i can play perfectly fine with all other mods, its just AE that isnt working

**Comment by jHoyne** [comment]
Where did you download the mod from.

**Comment by robbooooo1234** [comment]
the official website

**Comment by robbooooo1234** [comment]
it shows everything on NEI just doesnt let me do anything with them

**Comment by jHoyne** [comment]
Can you go into creative and try using them

**Comment by robbooooo1234** [comment]
It lets me use them from the creative menu and NEI but doesnt let me craft anything in a crafting table

**Comment by jHoyne** [comment]
Is it the vanilla crafting table

**Comment by robbooooo1234** [comment]
yes

**Comment by jHoyne** [comment]
What are the "small/Non-content" mods

**Comment by robbooooo1234** [comment]
they are all like Inventory tweaks and things that dont add anything physical to the game

**Comment by jHoyne** [comment]
List?

**Comment by robbooooo1234** [comment]
oh god its gonna take forever, its currently 6:40AM xD

**Comment by jHoyne** [comment]
No rush

**Comment by robbooooo1234** [comment]
they arent anything that would likely cause conflicts

**Comment by robbooooo1234** [comment]
dw i fixed it now, just updated a few things and changed a few things around
