### ISSUE TITLE
Modded Server

### ISSUE THREAD

**Issue by KnottyCord** [AppliedEnergistics/Applied-Energistics-2#1734]
is there a way to find the world id of multiverse so i can add this number in the config. because for now meteor can only spawn in the overworld!

**Comment by yueh** [comment]
I do not know and we do not support bukkit plugins.

**Comment by thejonathanr** [comment]
yourserverfolder/plugins/multiverse
In that folder might possibly be a configure file? If so check it.

**Comment by KnottyCord** [comment]
ok im gonna see

**Comment by KnottyCord** [comment]
But how do i find a "World ID"?
