### ISSUE TITLE
Wireless and Wired Terminals Disconnect frequently, even on small networks

### ISSUE THREAD

**Issue by FalseTetrabyte** [AppliedEnergistics/Applied-Energistics-2#1736]
We didn't have this problem until we added a couple of new modpacks*(hear me out), but where the wireless remote used to work all the time without fail now disconnects at random with the message "Wireless Network out of range".  If I move closer to the AP, then right click again, about half of the time it'll open normally or the other half I'll get a blank terminal window for a bit before it finally loads.  

I thought maybe it was a problem with the wireless signals and my network setup, so I dismissed it as a problem with my wireless setup, however it also happens at the terminal.  I'll be using it, then I'm kicked out.  If I go back into it, the same behavior occurs - it opens, but nothing is in the terminal and it isn't searchable for a few seconds or it will be fine.  Disconnect/reconnect doesn't work, and the issue happens to other players as well.  

I thought maybe it was a power issue, so I set up a terminal next to my controller ring (7x7, but only one block deep) and observed the same issue there.  I investigated my power feed which is a resonant  energy cell, and even set it to the highest power output, no effect.  I also tried to run the system using the power injector from the mod itself - no change in behavior.

Our server is run on Bisect Hosting, has 7 GB of RAM and when this occurs, RAM usage is low and TPS is high (for example, the last time it did this, spurring me to post here, the TPS was saying 19.92 with Free Memory of 5349 MB out of 7084 MB allocated.)
 Even when it happens, the TPS has never dropped below 19. 

Forge tps command shows 20 across the board and the plain tps command shows the 1m, 5m and 15m readings as all 20's as well.  

The mods we added to the pack were 
Bibliocraft 1.10.3
Minechem 5.0.5.398
TravellersGear 1.16.4
MrCrayfishFurnitureMod 3.4.7 ​
Extra Cells 2 2.2.73b129
Thaumic Energistics 0.8.10.5

I inserted PlayerAPI 1.1 to fix an issue with Extra Utilities.  

I tested the server without Extra Cells 2 installed and it does the same thing.  

We are running an AE2 version that is admittedly out of date (rv2-stable-1) but this is where things got interesting - we updated to the latest stable release (I believe rv10?) and it kept occurring.  

Does anyone know of any cross mod problems I could investigate?  We don't see lag spikes on the server, and AE2 seems to be the only thing affected lately.  

The server was also running on the latest version of Forge for a while, but the updates (latest mods for everything I've listed) caused a horrendous memory leak, and we'd have to reboot the server every 2 hours or it was unplayable (Free RAM would drop to under 300 MB, and TPS around 3-5.)  So we rolled back to the earlier setup, which includes rv2-stable-1 for AE2. 

Our pack has approximately 107 loaded mods (72 in the mod jars in the folder).  

Apologies if I am missing any information, I'm still getting used to GitHub - I couldn't find my exact issue after searching for a good while, and am unsure of what is expected in a problem report.  We love AE2, so it's frustrating quite a few users.

**Comment by yueh** [comment]
Most likely a power or chunkloading issue

**Comment by FalseTetrabyte** [comment]
I thought so as well, but the chunkloader in my base is pretty close to where I am, and one of the other users I spoke with has a tiny network, would fit within a single chunk and it has the same problem.  

I'm willing to accept that maybe Chickenchunks is having a bad day, but I'd like feedback from others before I start stripping mods out.  :)

**Comment by FalseTetrabyte** [comment]
I just re-did my power setup to use power from my reactor(s) to the resonant energy cell, which is outputting at 5000 RF/t (I did some calculating to see what I was actually using and it's around 1400 RF/t right now I believe) using the Energy Acceptor between the Energy Cell and the AE2 controller ring, and it still does it.  Unless the Acceptor can't handle that kind of power usage, I don't think power was the issue.

**Comment by yueh** [comment]
AE2 does not care about any external source. It will just use its small internal buffer and if that runs out in a single tick it just shuts down. Add more energy cells as buffers.
Also it has a very dynamic power consumption, any operation will consume additional energy on top of the idle usage. This will show up with the network tool, but only when not idle.

But could also be a chickenchunks issue. We had a couple of issues with them in the past.
As well as with ExtraCells. Like a fluid storage bus will completely reset your network inventory with every block update it recieves (like the attached tank changes, see #1621)

**Comment by FalseTetrabyte** [comment]
Well, the problem is with this latest hiccup, I was standing right next to both the controller and the fabrication (assembly/ME interfaces) were right above me, so unless it's still relying on the chunk loader even when I'm in the immediate vicinity, I think I have to rule that out as well.

**Comment by FalseTetrabyte** [comment]
No change with the energy cells.  I do have quite a few channels in use, would excessive channel use cause the problem with Dense cables?  I recently perfect p2p in a single player world, so I'll migrate eventually, but it's really frustrating to see the entire system lose channel coherency but retain power every so often for no reason.  Even the console doesn't show anything.

**Comment by bramhut** [comment]
I have the same problem too, some times my drives turn dark but they are still using channels and I have a steady power supply. The only way I could fix this (temporary) was by replacing my controller.

**Comment by thatsIch** [comment]
Can somebody of you provide a **minimal** world where this happens?
