### ISSUE TITLE
Devices aren't picking up channels.

### ISSUE THREAD

**Issue by jtgraphic** [AppliedEnergistics/Applied-Energistics-2#1737]
I *think* this might be related to the distance from the controller, which is about 80 blocks.

Here is a video of the behavior: http://screencast.com/t/SOHUceuRd

Basically at one point along the cable they will pick up a channel, but one block farther, they won't. The cable they pick up a channel on is the 77th and the one they don't is the 78th.

There is cable from both Ender IO and AE2 in this chain. It's dense cable until the 68th section and regular cable from there.

This is TPPI2 0.1.5, which has AE2 rv2-beta-28 I think.

I am not providing a crash log because there is no crash.

Here are some images of the same issue if you don't want to download the video:

http://screencast.com/t/Xs1hmwrhrW
http://screencast.com/t/si62eMNvp4YZ

Interestingly, those are from last night and are occurring on the 76th and 77th cable. I'm not sure if this is even a bug, but the people at /r/feedthebeast made comments that made me think it might be.

**Comment by ruifung** [comment]
You probably want to test with rv2 stable 10  instead? Beta 28 is like... over 3 months old now.

**Comment by jtgraphic** [comment]
I just updated to `rv2-stable-10` and the issue persists.

**Comment by jtgraphic** [comment]
I just ran a parallel dense cable along side of the Ender IO cables and it seems to work. This is the discussion on Reddit for it:

https://www.reddit.com/r/feedthebeast/comments/3eei9y/is_there_a_length_limit_on_me_cable/

/u/MrGrey1 gave the suggestion, which in retrospect is obvious. I'll reach out to the folks at EnderIO and see what they have to say.

**Comment by jtgraphic** [comment]
Posted this on EnderIO issue:

>Ok, so I've got it working. I've tried a bunch of stuff, so I can't be sure what changed it. I think what might have done it is that I replaced every single cable in the chain. Update issue somewhere along the way?

**Comment by yueh** [comment]
AE2 has no limited cable length as long as all are loaded.
As replacing the EnderIO conduits with normal cables fixes, I would consider it a bug on their side for now.

**Comment by yueh** [comment]
Reopen once there it is known to be an issue with AE2.
