### ISSUE TITLE
OpenComputers/NEI crash on items usage.

### ISSUE THREAD

**Issue by MrGraphic** [AppliedEnergistics/Applied-Energistics-2#1739]
Simple check on any item usage via NEI crashes client:
[Crash report](http://pastebin.com/932RZGCn)

	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1490 20 mods loaded, 20 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1490-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1490} [Minecraft Forge] (forge-1.7.10-10.13.4.1490-1.7.10.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv3-alpha-1} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.111} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
	UCHIJAAAA	OpenComputers|Core{1.5.14.698-dev} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	appliedenergistics2{rv3-alpha-1} [Applied Energistics 2] (appliedenergistics2-rv3-alpha-1.jar) 
	UCHIJAAAA	NEIAddons{1.12.11.36} [NEI Addons] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Developer{1.12.11.36} [NEI Addons: Developer Tools] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|AppEng{1.12.11.36} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Botany{1.12.11.36} [NEI Addons: Botany] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Forestry{1.12.11.36} [NEI Addons: Forestry] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|CraftingTables{1.12.11.36} [NEI Addons: Crafting Tables] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|ExNihilo{1.12.11.36} [NEI Addons: Ex Nihilo] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJAAAA	neiintegration{1.0.11} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.11.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	OpenComputers{1.5.14.698-dev} [OpenComputers] (OpenComputers-MC1.7.10-1.5.14.698-dev-universal.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar)

**Comment by yueh** [comment]
This is an OpenComputers issue.

**Comment by fnuecke** [comment]
Hrm, OK. I don't really understand the reason for requiring stacks to have a size > 0 (>= 0, sure, but 0 is often used for "ghost stacks"). But allright, I'll request a size one stack to check if it's available.

**Comment by yueh** [comment]
Intended to create actual itemstacks, not some fake ones.

The better approach now (with rv3) is just `maybeBlock().isPresent()` as these will return an `Absent`.
I would call it an oversight with rv2, which always returned an `Present`. Would have been fixed when someone complained about needing to create an itemstack to check if the block exists might be a bad approach.

**Comment by fnuecke** [comment]
Ah, oh well. Nevermind then ;-)
