### ISSUE TITLE
New Ores

### ISSUE THREAD

**Issue by lightning02** [AppliedEnergistics/Applied-Energistics-2#1740]
The new minerals that your mod add, subscribe the existing chunks??
If i put your mod in my server i have to reset the world for the new minerals that add?

**Comment by yueh** [comment]
We do not support any retrogen for the ores or meteors (as they can be pretty destructive).

Either explore new chunks or use something like the CoFH oregen, which supports retrogen of ores and custom spawning.
CoFH is of course limited to certus, it cannot spawn meteors. Here is the only option to explore more chunks.

**Comment by lightning02** [comment]
Thank u!! :)

**Comment by lightning02** [comment]
oh.. another question.. COFH is a dependency of COFHcore o is the original mod?

**Comment by yueh** [comment]
I think it is CoFHCore, which provides the custom ore generation.

**Comment by lightning02** [comment]
yes, i've check it's CoFHCore! Thanks again!
