### ISSUE TITLE
gimme back applied energetics 1 for 1.7.10

### ISSUE THREAD

**Issue by wackoamd1** [AppliedEnergistics/Applied-Energistics-2#1743]
i always loved AE , but this new version sucks balls , no more big multi block computers
have to play wow before i can even craft. ( to find the damn meteor )

and the meteor compas sucks , i was looking at the meteor that happened to be on the top of a mountain , and the compass told me to go right .
it also spins when im in a chunk that doesnt even have the meteor.

overall AE2 sucks imo so please port AE1 to 1.7.10

im sorry but this is a classic case of fixing something that wasnt broke in the first place

**Comment by yueh** [comment]
Use the search for similar posts.
