### ISSUE TITLE
Hidden patterns

### ISSUE THREAD

**Issue by zlotnleo** [AppliedEnergistics/Applied-Energistics-2#1744]
Add the ability to hide encoded patterns from the regular/crafting terminal. This might be useful if an item is only a requirement for another craft. For example, searching for tesseract will show you a tesseract frame. You don't really want a frame, so might as well hide it's recipe.

**Comment by yueh** [comment]
The items displayed in a terminal are really independent from the actual patterns. A pattern is not even required to show an item as craftable.

The some degree you can already achieve this by using view cells, but this will apply to the item itself, so you will no longer be the current amount.

Maybe as an option/upgrade for view cells to distinguish between existing items and crafting items?
(It really needs to work on the level of items and not patterns)

**Comment by zlotnleo** [comment]
I dont really see a problem in adding another if or so. The same way that view cells hide the unnecessery stuff. But this will be encoded by default to check one boolean in the ItemEncodedPattern class.

**Comment by yueh** [comment]
If you have a solution with 1 or 2 additional if, feel free to create a PR.

**Comment by AdmiralEinstein** [comment]
I literally just had this idea and came here to suggest it when I saw this post.

Being able to hide components and things we just make in a chain and never to use on their own would help de-clutter the ME terminal quite a bit.

The idea has my vote and support!

**Comment by thatsIch** [comment]
my general approach would be to hide it in a sub-network.
