### ISSUE TITLE
Random Server Crashes 

### ISSUE THREAD

**Issue by cauliflower69** [AppliedEnergistics/Applied-Energistics-2#1745]
http://pastebin.com/1CmHxBxc

**Comment by yueh** [comment]
Please try to reproduce it without cauldron.

**Comment by cauliflower69** [comment]
Will do

**Comment by cauliflower69** [comment]
Found out what the issue was. It seems that when I was draining my system of power it would cause these crashes. When I broke the power drain it was fine. Just wanted to comment in case someone else has a similar issue
