### ISSUE TITLE
 Applied-Energistics-2 system freezze bug

### ISSUE THREAD

**Issue by zverje** [AppliedEnergistics/Applied-Energistics-2#1748]
After restart my game world my Applied Energistics 2 system freeze.System consumes energy but not working.Verison of Applied-Energistics-2 rv2-stable-10.Video http://youtu.be/t6l5gHXwpmQ

**Comment by Ianaver** [comment]
that's strange, did you ever get it back up? I think maybe replacing one of the wires will send an update and possibly make the system reboot if it happens again

**Comment by yueh** [comment]
Can you post the `settings.cfg` inside your world folder on pastebin?

**Comment by zverje** [comment]
@yueh 
Yes of course. http://pastebin.com/HnRkpKm6

@Ianaver 
Helps only full  dismantling of machines from AP2 , Its happens every time when entering the world.

**Comment by yueh** [comment]
Looks like a duplicate of #1266
