### ISSUE TITLE
Major bug with channels and controllers

### ISSUE THREAD

**Issue by Epicminerzx** [AppliedEnergistics/Applied-Energistics-2#1749]
I get annoyed with channels and I like AE 1 so I turned off channels in the configuration and I reload the game and the ME controller disappeared from the game and so wanting to be able to USE the mod I turned channels back on, they still didn't exist in the game, I am using version rv2-stable-10 can someone please let me know what is going wrong and maybe fix it?

**Comment by yueh** [comment]
#1289
