### ISSUE TITLE
Items is getting stored in subnetworks. is it a bug?

### ISSUE THREAD

**Issue by TheOneDemand** [AppliedEnergistics/Applied-Energistics-2#1750]
i was setting up my network with a subnetwork for thaumcraft items. and my main network was for ore processing and main storage. when i started putting ore into the network i noticed that my drives for that network didnt fill and instead my magic network drives was filled instead.

short vid showing the problem: https://youtu.be/Y-WbSY-gw-w

is this intended?
Thanks

**Comment by ruifung** [comment]
Check your bus configurations?

**Comment by yueh** [comment]
Yes intended. If you do not use the priorities or filters, the network will store it wherever some space is available.
