### ISSUE TITLE
Smarter storage busses

### ISSUE THREAD

**Issue by expl0s1ve** [AppliedEnergistics/Applied-Energistics-2#1752]
Pull items from a storage bus and put them in storage cells if there is more than one or more (or a configurable amount of) stack(s) of that item in the system. That could be a card maybe?

**Comment by ruifung** [comment]
Isn't this already possible with level emitters / export bus & a interface?

**Comment by expl0s1ve** [comment]
How many level emitters would you need for every item/block that you have less than one stack of?

**Comment by ruifung** [comment]
Well... I just said its possible, and you have read the suggestion guidelines right?
http://ae-mod.info/Suggestion-Guidelines/

**Comment by expl0s1ve** [comment]
I did and if you're referring to #3 well, basically, AE is a more compact an efficient version of vanilla storage.  I'm not asking for a more compact or easier version of what's in the mod because you can't possibly know what items you're going to collect or what your quarry is going to pick up so my request is not another implementation of something that's already in the mod. 
It doesn't even have to be a really smart storage bus, I need a system where you can manipulate stored items without specification, like comparing with other items in the storage or checking the number or something.

**Comment by mindforger** [comment]
if you want to have at max 1 stack of something available, you can utilize interfaces!
place an interface, configure it to keep a full stack of something and attach a storagebus to that interface. The interface acts as an 9 Stacks buffer, automatically requesting new items from the net and connected machines to keep the stack up ... and providing a crafting card it will autocraft everything for you

**Comment by expl0s1ve** [comment]
Putting a storage bus on a subnetwork's interface lets you access the subnetwork's all items anyway, without the need to configure the interface. Plus thanks but I know how to use basic ME. :)
Mine is a whole other issue:
I want to keep items such as dungeon loot or damaged bows out of my ME system because I only use 64k+ byte cells and I don't want the items I have very little of clogging up that space.

**Comment by ruifung** [comment]
Uh if thats the case... fuzzy?

**Comment by yueh** [comment]
You might have missed some points, but currently I really do not see that this is impossible to achieve with AE2. I assume that the first post is just a more abstract use case of the last one and if this is true, it is not even that complicated to handle it only with the current storage buses.

**Comment by expl0s1ve** [comment]
I probably have missed some points, I really have no idea how to make that happen. Could you give a brief example?

**Comment by yueh** [comment]
As @ruifung said fuzzy cards and then handle the overflow somehow. Mostly by setting the correct priorities and filters. 
There are many different solutions based on your actual use case, but our IRC channel is really a better place to discuss these and not abusing the bugtracker for it.
