### ISSUE TITLE
Cannot connect more than 4 me drive to the same network

### ISSUE THREAD

**Issue by ExDomino** [AppliedEnergistics/Applied-Energistics-2#1756]
When I try to connect a 5th me drive to the same network, the network is shutted down and refuses to work again until I remove the 5th me drive, even with more Energy Cell next to the Energy Acceptator. The network has enough energy to work, powered by a IC2 Cesu connected to the Power Acceptator and there is an Energy Cell (completely filled according to waila) next to it.

Edit: My network is composed of 2 me terminal, 1 crafting terminal, 4 me drives filled of 1k storage cell and 1 me security terminal. The network doesn't work when I add the 5th me drive, but if I remove the security terminal and replace it with the 5 me drive, it works. How many compounds a me network can handle? It seems to be limited to 8 componds.

**Comment by sanados** [comment]
Normal cable is bound to have only 8 channels.
When you need more channels switch to dense cable.
(But to address more than 8 channels you need a controller)

Anyway, this is no bug but works as intended.
