### ISSUE TITLE
Is it possible to upgrade AE without losing all of my progress?

### ISSUE THREAD

**Issue by lokiwolf** [AppliedEnergistics/Applied-Energistics-2#1758]
I go in and I'm unable to craft half the stuff even though I have the right recipe and all the materials... So I'm wanting to upgrade, but I worry that if I do I will lose everything I've done so far.

**Comment by ruifung** [comment]
I presume from ae1 to ae2?

**Comment by TheJulianJES** [comment]
Maybe https://github.com/AppliedEnergistics/AEUpgrade ?
