### ISSUE TITLE
Can´t build or craft in the crafting Terminal. Only see whats inside.

### ISSUE THREAD

**Issue by Haloleute** [AppliedEnergistics/Applied-Energistics-2#1760]
Hello my problem is:
I can only access the ME system, but can´t take anything out.
It's been around for a few days. 
I play on a server with the Modpack 1.7.10 (0.7.9b) I was there to get something out  from the ME System. then came an error. I don´t have the Error Log but some pictures:

![2015-08-01_17 43 01](https://cloud.githubusercontent.com/assets/13601943/9022424/41688a00-3875-11e5-94d4-9a0a770dee18.png)

![2015-08-01_17 42 35](https://cloud.githubusercontent.com/assets/13601943/9022417/f9c0b5ec-3874-11e5-82cf-b0c567503797.png)

And i can´t access the Fluid.
![2015-08-01_17 47 39](https://cloud.githubusercontent.com/assets/13601943/9022431/6ed6b494-3875-11e5-8c71-350e2e96b205.png)

And placing me pips also not works.

**Comment by yueh** [comment]
Can you post the `settings.cfg` inside the world folder of the server on pastebin?

**Comment by Haloleute** [comment]
Ok here:
http://pastebin.com/sjt9CQ1w

**Comment by yueh** [comment]
Looks ok.

In general it is an issue with the security terminal (but mostly not on the side of AE).
Like someone replaced it.
Also is it a normal server or any cauldron fork?

**Comment by Haloleute** [comment]
Its a normal server. I think its the security terminal because i use the ME Network with a friend.

**Comment by Haloleute** [comment]
It was the security terminal^^.

**Comment by yueh** [comment]
Simply put a [biometric card](http://ae-mod.info/Biometric-Card/) set to your player into the security terminal. (Needs to be done by the owner and the owner does not need any for themself)
