### ISSUE TITLE
Everything in chunk is loaded twice, leading to strange effects

### ISSUE THREAD

**Issue by Chromotron** [AppliedEnergistics/Applied-Energistics-2#1762]
One chunk on my server seems exist twice for AE2: After every server restart the objects in a single chunk are counted twice until removed and replaced. Only removing and replacing some of the parts, e.g. the controller, is not enough. This happens in no other chunk I tested (tried about 10 random ones, plus the ones where there already is something from AE2).
This bug leads to controllers not working (due to there supposedly being a "second" controller, themselves), cables not fully vanishing on removal, busses using up to twice the channels they would normally do, and P2P going haywire.

I can easily recreate this in that one chunk by building any AE2 network. The following pictures where made by placing a single controller, 6 dense cables (normal ones work, too), restarting the server, and then removing a single dense cable at one end:
![2015-08-02_13 48 35](https://cloud.githubusercontent.com/assets/11485938/9026008/a86569cc-391e-11e5-8dd6-a8c6dd34fe3c.png)
![2015-08-02_13 48 45](https://cloud.githubusercontent.com/assets/11485938/9026009/ad99a7e6-391e-11e5-8fde-1ac090e1e0f4.png)
![2015-08-02_13 49 01](https://cloud.githubusercontent.com/assets/11485938/9026010/b1846f30-391e-11e5-9ef0-703bf0763b74.png)

Note the visual glitch where I removed a cable. Also note that it counts 11 cables while there are only 6. It was 12 before I removed one. The controller is red due to it thinking there being a second one (itself) as also visible in the network details.

The only way of fixing this that I found is to completely replace every single part. Only replacing the essential ones gets it to work most of the time, but it still continues showing/using wrong numbers (including channels used by cables).
I tried deleting and recreating the settings.cfg to no avail.

This is with rv2-stable-10.

**Comment by XFactHD** [comment]
Are you using cauldron?

**Comment by Chromotron** [comment]
No

**Comment by Chromotron** [comment]
I was able to "fix" it now by also removing a subnet I overlooked (due to it being much higher up) and replacing everything.

**Comment by yueh** [comment]
I doubt that another network would interfere with it. They are physically located in different places.

It is way more likely that some other mod affects things like chunkloading or the construction of tileentities. The usual things like Optifine, Fastcraft or Chicken Chunks.

The best option is to create a backup and remove all mods except AE2 and then verify, if the problem still exists.
If not, then slowly add the mods back until it reappears. It should basically end up with only AE2 + one or two other mods.
If it still exists with only AE2, then it gets a bit tricker. As you said it only affects a single chunk.
So maybe this one is just corrupted somehow, say something messed up during saving it and caused the tileentities to be saved twice. This could be verified with something to explore the NBT data and just look for duplicates. But finding what actually caused it is most likely impossible as it looks like a very rare/random issue.

**Comment by Chromotron** [comment]
That other network was not separate, but connected to the same one (via P2P by a rather long route through neighbouring chunks). Removing (and rebuilding) it definitely fixed the problem. But as you can see in the pictures, the bug influences unconnected networks, too, as long as they are in that chunk.

It's simply impossible to remove ~200 mods from this a year old world. It causes endless crashes (I tried a couple weeks ago for an unrelated problem). Reproducing is indeed also not possible as I have no idea how it happened.
I don't use Optifine and ChickenChunks, and already tried removing FastCraft (version 21 in this case).

As it seems to stay fixed since the removal of that part you may close this issue if you wish, until I or someone else encounter it again.

**Comment by yueh** [comment]
It should always be possible to remove all mods without crashing (ideal situation).
Just the usual missing blocks and items.

Not being able feels like some mod/mods is/are really messing with minecraft itself and generating some data in such a way, that it can no longer handle it without the mod being present.

It is probably annoying, but to be honest I would be more worried, if it would cover multiple or all chunks. Being limited to only one chunk really feels like something did mess up during saving it, but that is just something rarely happening with this amount of mods. Similar to some random bit flipping.
The best option is probably to hope that it was an one time error and not some slow world corruption. But just in case, making some backups is a good idea.
