### ISSUE TITLE
ME annihilation Plane Storage "Bug"?l

### ISSUE THREAD

**Issue by J0nni** [AppliedEnergistics/Applied-Energistics-2#1763]
Annihilation won't work with a storage Bus and none drive at the Network. if you have one (empty) drive, they'll work and are using the storage bus, without drive they won't do anything.

**Comment by yueh** [comment]
Could you be a bit more precise? For me it sounds like you are not provided any place to actually store the item from the Annihilation plane, thus it simply cannot import anything.

**Comment by J0nni** [comment]
I built A TBM with an ME using a storagebus, bc Miningwells and Funcylocomotion. For storage I use an Storagebu, connected with an Crystalchest from the Ironchest Mod. I am exporting the Items from thr Miningwells with ME interfaces, which use the storage Bus.
On The front is a Head with annihilation Panes, cutting the Blocks. 
The Problem is, when I don*t have an (empty) drive at the ME, the  annihilation Panes won't use the Storage Buus (they doesnt work)
Other Informaltions:
The storage is spended by 100% by the storage Bus and an empty crystalchest, which can be used, but only when I connected an (empty) ME drive to the network. The Network is a sub-ME, including 2 Controllers, som smart- and dense cables, hollow covers, power supply, an storage Bus with crystalchest and an empty ME drive.

**Comment by yueh** [comment]
I built a bore myself with funky locomotion and did not encounter any issue like this. The main different was, that I stored the items directly in the main network via QNB.

But I did not encounter any problems with it.

The only thing I could currently imagine is, that the planes are simply blocking.
In your case the networks need to reboot after every move and this can take a couple of ticks.
If planes cannot store their items somewhere, they will go into a blocking mode to reduce load, by default this takes about 6 seconds until the work again.
But I have no idea why a drive should affect it, it really does not add anything to the network.

Also which AE2 version are you using?

**Comment by J0nni** [comment]
The version is rv 2-stable 10
an important information could be that I trigger the Frames with an empty level emitter, which is emitting an RS-Signal when the complete Network is loaded. then I programmed an Delay of 70 Ticks in an Programmable Rednet Controller.
Another big Problem with FLM I found today is that Inscriber become sometimes Unbuid when they become moved with Framecovers from FLM. The strange Part is, that i have 2 Inscribertowers with frames, but only one unbuilds the Inscribers (the Items become dropped). Every Tower has two sides and one sides become unbuild mor often than the other one.
If you are interested, I can give you the Modpack- and server ip that you can look yourself the problems, becouse I think that these are AEs Bugs. (The 4 Networks with Interfaces, not with annihilation Panes are the same and are wroking only with an storage Bus and without drive)

**Comment by thatsIch** [comment]
Maybe just share a new world/instance with your construction
