### ISSUE TITLE
Memory less auto crafting and question about addon

### ISSUE THREAD

**Issue by Carbon-Ghost** [AppliedEnergistics/Applied-Energistics-2#1764]
Small question, I know it has already been asked, but why can't you make it as a config option like channels ? Disable it by default, but some people might want to play AE2 with a bit of the old AE style in it :/ I mean in the end, people just want to have fun, no one have the final definition of fun as everyone view it differently ( COFH said also something similar ). 

 But how hard would it be to do an addon for that if you guys don't want to do it ? I began with someone else to do one, but he needed to resign due to life getting too busy...

**Comment by yueh** [comment]
#1657

**Comment by Carbon-Ghost** [comment]
But how hard would it be to remove the memory system and optionnally make a config for it ? Do I simply need to change some numbers in the code or is it more complex and I might break the mod ;P ?

**Comment by ruifung** [comment]
You mean the crafting storage ? It probably is more complex then that as unlike AE1 where everything is stored back into the network, materials are stored in the CPU storage instead. I imagine that yanking that bit of code would require rewriting quite a bit of the autocrafting code.

You probably would need to re-implement quite a bit of the autocrafting logic if you choose to do it.

It's just a guess though, if you can't read the code to figure out what you should change, you probably won't be able to change it in the first place.

**Comment by Carbon-Ghost** [comment]
I kinda understood that, although it's not what I wanted to do originally, I think I am going to simply port the old MAC and old ME interface and how they worked in the form of an addon with Speiger, once we finish the Steam reactor & compat update ;) Just to be clear, I prefer using the new AE2 stuff as they look cooler and are better, but the only part I don't like is the limitation of crafting ability due to the cpus :c I would rather had nerfed recipes...

**Comment by ruifung** [comment]
Limitation? How so lol, I don't really feel any limitations? (
