### ISSUE TITLE
ME Terminal ceasse to work when they are far away of more than about 34 blocks

### ISSUE THREAD

**Issue by ExDomino** [AppliedEnergistics/Applied-Energistics-2#1766]
My network is perfectly working, but when I try to connect a ME Terminal far away of more than something of 32 or 34 blocks, it doesn't work. Just one cable closer ant it work, but one cable further and it doesn't work. Is there a distance limit? When I tryed that, my network had a ME Controler and I also checked the amount of energy the Energy Cell (from your mod) had (with Waila) and it was 200 AE. Thanks for you help.

**Comment by yueh** [comment]
Use (working) chunkloaders

**Comment by ExDomino** [comment]
The zone is entierely chunk loaded and I don't even move when I try to put a ME Terminal on a cable, it works, and after I try just the cable next to it, without moving, and it doesn't work. And it doesn't ceasse to work at the limit of a chunk.

**Comment by nigrum-dente** [comment]
So, I'm well aware that I'm answering far too late, but seeing as I had the same problem and found this issue when searching I should probably answer it:

While a ME controller can output 32 channel, only a dense cable can carry 32 channel, any other cable can only carry 8.

What's most likely happening is that you have more than 8 device on the glass cable, after which the network decide to stop activating some other device, most likely those closet to the ME controller take priority.
