### ISSUE TITLE
Meteor Whitelist custom Multiverse names

### ISSUE THREAD

**Issue by djoveryde** [AppliedEnergistics/Applied-Energistics-2#1768]
I am attempting to set the meteorite whitelist into my mining world (multiverse). Issue is when I add it AppEng resets the config each time.
Does anyone know how I can do this? The world name is "mining" but it seems AE only likes numbers?

**Comment by yueh** [comment]
#1605

**Comment by djoveryde** [comment]
Doesn't work... I've created a new world called DIM-14 and -14 still no meteorite rendering??
