### ISSUE TITLE
Suggestion Formation Plane

### ISSUE THREAD

**Issue by Barofioso** [AppliedEnergistics/Applied-Energistics-2#1771]
This Formation Plane was banned from our server, and that because i had placed some blocks which were prevented by a plugin.

It could be a good idea, to create a config to prevent to place these blocks in a specific world.

**Comment by yueh** [comment]
Our general stance is to not support anything related to cauldron. Thus it is unlikely we will add something like this.

AE is using the normal way to place blocks. (What I currently consider as normal.)
Of course I cannot exclude any potential bug, like the Forge documentation being lacking and thus not pointing to the right method. So when someone can point to a better implementation (in the context of forge), we will of course change it.
With some luck it might also affect cauldron, but we will not change anything just to support some dead software.

**Comment by Barofioso** [comment]
is that a big change to create a line that are only block/item IDs which prevent to place some specific blocks?

**Comment by mindforger** [comment]
if you make any exemption, everyone want's one, and look at the issue counter they have enough to do (no insult intended)

**Comment by yueh** [comment]
The part about a config of items per world does not magically appear in the code, also the next person then request an API for it, so the plugin can access it etc. So no it is not a single line of code.

I am mostly leaving it open, in case someone can actually contribute insight about it and if there might be a potential misbehaviour with the code of the formation plane.
