### ISSUE TITLE
ME Interface pattern/autocrafting not pulling finished product out of machine

### ISSUE THREAD

**Issue by dnulho** [AppliedEnergistics/Applied-Energistics-2#1775]
I am using FTB Infinity Modpack (with RV2-Stable 10) and any time i use a processing pattern in a ME Interface, it puts the ingredients into the machine, but after the machine is done, it won't pull the finished material out and import it back into the network. Am I supposed to add import buses to every machine that I am autocrafting with?

**Comment by yueh** [comment]
#703
