### ISSUE TITLE
ME Terminal ceasse to work when they are far away of more than about 34 blocks

### ISSUE THREAD

**Issue by ExDomino** [AppliedEnergistics/Applied-Energistics-2#1777]
Related to: #1766

The zone is entierely chunk loaded and I don't even move when I try to put a ME Terminal on a cable, it works, and after I try just the cable next to it, without moving, and it doesn't work. And it doesn't ceasse to work at the limit of a chunk.

An image to desmonstrate what's the problem:
http://image.noelshack.com/fichiers/2015/32/1438808497-ae.png

At the left of the cable, 5 me drives, 1 energy cell, 1 me controller, 1 me fluid import bus, 1 security terminal, 1 power acceptator, 2 me terminal and 1 crafting terminal are connected. At the right of the cable, only 1 me import bus is connected, but not operationnal for I think the same reason of the second me terminal doesn't work.

**Comment by yueh** [comment]
If I understand your listing correctly, you try to connect 10 devices to a cable which only supports 8? Similar to #1756?

**Comment by ExDomino** [comment]
If it's the cable that cannot handle more channel, why it works when I just move it one block to the left?
It really seems that me cables have a limited lenght.

**Comment by dnulho** [comment]
are both terminals on the line when you are trying to access them? the ME Controller allows intelligent channel utilization. Meaning that the first 8 items on the cable will work, the all other's won't. If there is not a controller on the system then the channel utilization is universal and the network will 'crash' if there is more then 8 items on the network.

**Comment by yueh** [comment]
I also recommend reading [this](http://ae-mod.info/Channels/).

**Comment by TheJulianJES** [comment]
I think this is working as intended.
