### ISSUE TITLE
Clicking on a CPU with a Energy Cell in hand causes internal server error

### ISSUE THREAD

**Issue by dnulho** [AppliedEnergistics/Applied-Energistics-2#1784]
Clicking on a Crafting CPU with an Energy Cell in hand causes an internal server error.
I have had this happen several times and seems to be a repeatable error. Not sure if the "array out of bounds" is the error or not, but I uploaded the client side log for y'all to look at.

I am on a private external server, running FTB Infinity v1.9.

Pastebin of fml-client-latest: http://pastebin.com/yqXSrwcM

**Comment by yueh** [comment]
We need the server log.

**Comment by dnulho** [comment]
Ok, here is the last couple hours of the server log:
http://pastebin.com/YLSYNiyq.

**Comment by yueh** [comment]
Strange as it does not contain anything.

The client log also only states that there was an error while handling the item tooltip and lists all 25 modes which want to handle it. Maybe one of them interferes somehow. But no idea which one.

The best idea would be to download/copy the map and try to find the interfering one by starting to remove mods.

**Comment by dnulho** [comment]
Ok, thank you. Idk if i am actually going to go through the effort of doing
that. I though I would let you know though as both blocks that were
involved in the error were AE2.

**Comment by yueh** [comment]
It is not happening with AE2 as only mod. Also the crash basically says one of these 25 mod handlers crash and not AE2. The question is just which one. To determine if it is an issue with this mod or really AE2 (probably unlikely), the amount simply needs to be reduced.

I have also tested it with a a custom pack and no issue.
The only mods which are missing are EnderIO, Minetweaker, Harvestcraft, NEI Integration, TIC Tooltips, Bdew, Forbidden Magic, and Wawla. Maybe I have overlooked one, but it is probably one of them. If you are not using the recent versions of them, maybe they have already fixed it?

**Comment by dnulho** [comment]
I am using FTB Infinity v1.9, which I believe is the recommended (and
latest) version, although there is the chance with any modpack that some
mods might be slightly out of date for various reasons. Anyway, thank you
for taking the time to look into this (non)issue. :)

**Comment by mindforger** [comment]
"Internal Server Error" is a common error message when a mod does something strange with the packagehandling from the server to the client, can you make a quick reconstruction by loggin in, and asap reproduce and make a paste from the point of login ? I had an compareable issue with EnderIO in the past, and the error happened way befor the disconnect. Sometimes it can be an issue with your internet connection or the server beeing overloaded by worldgen (Infinity 1.9 has performance issues with the new project-red world gen, from what i profiled after people getting contantly timeout while generating world)

**Comment by dnulho** [comment]
ya, I'll try to get it done tonight, when I'm home and have the time to do
so.
