### ISSUE TITLE
Turkish locale convert IMCs

### ISSUE THREAD

**Issue by thatsIch** [AppliedEnergistics/Applied-Energistics-2#1786]
When using `toLowerCase` with Turkish Locale used, it will not convert the Strings as expected from an English Locale perspective, because it respects the `i18n` standard for localization.

[Diskussion Link](https://www.reddit.com/r/feedthebeast/comments/3gdxk1/psa_for_developers_turkish_locale_breaks_stuff/ctxhta2)

A fix would be to use an invariant locale like `new Locale(Empty, Empty, Empty)` or use the English locale as default I guess

**Comment by yueh** [comment]
And that is why only `[a-z0-9]` should be used for anything important like communication or filenames :grinning:.

I am currently not convinced that using a fixed is ideal. It feels just like a workaround. I would even say some of the `toLowerCase` we are using might be even necessary. For example all related to item search on the client side.

Currently it seems that only the P2P IMC messages and `SecurityPermissions` might be affected.
But for example apache commons also provides a case insensitive `contains` or we could use Regex.
Both of these cases are actually static and/or are only called once during the startup, so there are not really any performance impacts.

**Comment by thatsIch** [comment]
Yes, some are required due to being used in GUIs so its intended there. Another way is to enforce a precondition on it where it must be a required case (not so elegant)

I think using `contains` is even semantically incorrect

**Comment by thatsIch** [comment]
btw we reached 1GB on TC, I set up some clean up rules to free us some space, but it will be executed at around 3:00 AM

**Comment by yueh** [comment]
Since Github supports displaying multiple commit statuses per PR, I have added my Jenkins just in case. So ideally we have 2 CI building it, especially as TC also had a couple of issues in the past with cached dependencies when updating them.
