### ISSUE TITLE
processing pattern gets finished too early

### ISSUE THREAD

**Issue by enkido** [AppliedEnergistics/Applied-Energistics-2#1788]
I have a processing pattern which creates one stack of an item. An interface request these items with a crafting card. After the first item gets created and enters the ae2 system, the crafting cpu counts the remaining items fast down and doesn't wait for the others to get crafted, the crafting job is declared done. The interface got only one item and therefore cues another batch.

1.7.10 rv2-stable-10
agrarian skies 2 1.1.8.

**Comment by yueh** [comment]
Cannot reproduce it.

**Comment by enkido** [comment]
i have tried to narrow it down further, i think i found the problem, i had also an export bus (with crafting card) into a barrel with a storage bus, so one item leaves and enters the system and i guess it counts as crafted every time it enters

**Comment by ruifung** [comment]
Just make sure your items never enters the network handling the crafting at any point.
