### ISSUE TITLE
Certus Quartz spawning disabled on default?

### ISSUE THREAD

**Issue by Phantum** [AppliedEnergistics/Applied-Energistics-2#1789]
I just downloaded the latest version ~7 days ago, and was trying to figure out why I couldn't find certus quartz anywhere.   

I looked in the configs and it was disabled.   Not sure if default is set to be disabled or if it was another mod that disabled it.

Didn't see any other posts about this, just thought I'd headsup incase it was an oversight!

appliedenergistics2-rv2-stable-10.jar

http://puu.sh/jwRlZ/cf0f5374cd.png

**Comment by yueh** [comment]
There was no change in this regards since rv0 or so and by default it is enabled.

So either some other mod disables it or maybe there was already a config present?

**Comment by Phantum** [comment]
I think it might have been dense ores, looking through NEI.    if it's enabled by default you can close this. :)  Just wanted to make sure it wasn't something else.
