### ISSUE TITLE
AE2 API Documentation

### ISSUE THREAD

**Issue by ruifung** [AppliedEnergistics/Applied-Energistics-2#1790]
I have a question,

Is there anywhere with a comprehensive guide to the AE2 API, or will I have to go through every file in the API?

Because since the ExtraCells repository is quite inactive recently, I'm trying to fix the many bugs in it.

**Comment by yueh** [comment]
What do you mean with "comprehensive guide"?
Some tutorial styled one? If so no, we simply do not have the time it takes to maintain it and ensure it is up to date.

The best idea is probably to use the provided JavaDocs.

**Comment by ruifung** [comment]
That was poorly phrased of me, what I would like are just some pointers to which parts of the API to start from, I can figure it out from there. And maybe just some idea of how AE's grid system works.

**Comment by yueh** [comment]
Probably start with `appeng.api.networking` and if in doubt, there is always the IRC channel.
