### ISSUE TITLE
Some recipes are not working with rv3

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#1791]
Some recipes are currently not working, for example this applies to the `ME Terminal`, `Network Tool` and nether quartz tools (but not certus ones)

I currently cannot see any pattern or issue causing it, but it seems to be related to oredict or group ingredients. For example the recipes for the quartz tools are identical, just use different oredict entries (for certus/nether quartz)

@thatsIch Could you maybe look into it? You should be a bit more familiar with the recipe handling.

**Comment by yueh** [comment]
Ok it seems to be related to #1635 and that the alias entries are missing. Adding them will fix it for SMP/SSP but not indev.

**Comment by looogin** [comment]
ME Terminal do not crafting in Ap rv3_a4
