### ISSUE TITLE
"Worlddrive"

### ISSUE THREAD

**Issue by minecraft7771** [AppliedEnergistics/Applied-Energistics-2#1793]
I had this crazy idea in my mind that maybe it would be a cool idea to have something like a World-Storagedrive-Computer where you can insert a harddrive that can store a few chunks - not like the spatial storages, more like a whole new world wich can be generated in the Worldcomputer, where you can also make settings for world generation like the biome or maybe some curios stuff like plants grow faster or something like that (Obviously such settings wich make it easier to get something need to be very expensive). And that you can controll the world in the computer like change the weather or time or something and a remote controll to change these things from inside the world. And to enter the world you would need some kind of storage-station for your body (Maybe like in the Clonemod?). And such a machine obviously needs lots of energy and should have a inbuild battery in the computer but if the energy should shut down completly and you are in the world something like screen bugs and maybe that mobs change their models and texture flickering and such should happen and when the power is fullly depleted the whole screen should be "dead" and you would get kicked out back to the real world.
And as a side note for nerfing the selecting a biome to generate their maybe should be slots where you have to for example insert 100 items of 5 different types of this bioms specific items or blocks to chose it for generation.
First of I would like to thank you for reading my suggestion and sorry for gramma mistakes and I really hope that you like the idea of it and can and will bring this idea to life.

Yours minecraft7771

**Comment by ruifung** [comment]
Wut?

**Comment by yueh** [comment]
It might be an idea for an addon. 
But I really do not see any particular reason to integrate something like Mystcraft directly into AE2.
(Also the amount of work for world gen mods. There is a reason why there are not that many configurable ones around)

**Comment by minecraft7771** [comment]
First of all thanks that you took your time to read and reply. I see that it takes a lot of work to realise such a thing and that you are right that this could be better as addon. But is there a place where I can suggest such a thing as addon or do I have to find a modder who can make one?

**Comment by jeremiahwinsley** [comment]
@minecraft7771 Take a look at [RFTools](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2229562-rftools-dimension-builder-teleportation-crafter). It's not an AE addon, but it has most of the features you're looking for.

**Comment by minecraft7771** [comment]
@jeremiahwinsley Ok thanks for the hint im looking into it.

**Comment by yueh** [comment]
Closing it for now.
