### ISSUE TITLE
Meteorite Compass Missing 

### ISSUE THREAD

**Issue by Voidfulqt** [AppliedEnergistics/Applied-Energistics-2#1794]
Hello, I'm playing Crundee Craft Modpack with my friend and yesterday I tried to start the AE2 things rollin'. When I tried to make the compass in a crafting table I've noticed that the recipe isn't right. I've searched the meteorite compass in NEI, same thing the item was missing. The Modpack is running AE2-rv2-stable-9. Is there something I don't know? Any info would be much appreciated.

**Comment by yueh** [comment]
I would say ask the modpack makers about why they disabled it.
