### ISSUE TITLE
Support for EMC as Power Unit

### ISSUE THREAD

**Issue by denzuko** [AppliedEnergistics/Applied-Energistics-2#1796]
Feature: Support for EMC as Power Unit

As a ProjectE/EE3 player I would like to use a PowerFlower to as a source of power so that I do not need to rely on IC2, BuildCraft, or other mods to provide power to my storage network.

Scenario:

Given I have an Energy Collector of any tier
And that I have wired it up to the ME network via a Energy Acceptor, Cable, and ME Interface
Then the Energy Acceptor should convert EMC to AE via a 16:1 ratio

Acceptance Criteria

    * Energy Acceptor converts EMC to AE
    * ME Interface, Storage Bus, or Import Bus accepts emc values from a Anti-Matter Relay (all tiers), or Energy Collectors (all tiers)

**Comment by denzuko** [comment]
I got to review how your intergrating other mods and If you guys are willing to do a pull requeset I can implement this later on in the week based on the Applied-Energistics-2/src/main/java/appeng/integration/modules/IC2.java class for both ProjectE and Thaumcraft.

**Comment by Entoarox** [comment]
The issue with EMC is that a 16:1 scale is far to small, and secondary that it would require that AE2 add a block capable of converting items into their EMC value (Since EE3 currently has no system of 'pure' EMC outside of the transmutation table)

**Comment by yueh** [comment]
I think this is way better suited for one of the AE2 addons like [Equivalent Energistics](https://github.com/Mordenkainen/EquivalentEnergistics/) or [ThaumicEnergistics](https://github.com/Nividica/ThaumicEnergistics).

All of the currently supported power systems are easily interchangeable with a different (official) ratio.
But this does not apply to Thaumcraft or any EE version. Also both provide their own fuel, which can be used in the [vibration chamber](http://ae-mod.info/Vibration-Chamber/), so there is no need to rely on anything besides AE2 + TC/EE.

Also the proposed ratio is way too low. This needs to be at least 250 EMC per 1 AE. Maybe even in the range of 500-1000.

**Comment by denzuko** [comment]
@Entoarox In testing I would agree to the 16:1 scale being rather small especially at late game. yueh's suggestion of 250 EMC maybe right but we can go for a 512 EMC per 1AE given that the first fuel upgrade does generate 512 EMC/tick for 6.4k ticks

As for a block that converts items into EMC values well there's not much need for that, even then if one wants to open up that much scope then maybe an bus attached to the matter condenser would be a good start but that's out of scope in my option and very unneeded by AE2 as that's something ProjectE or EE3 should include.

@yueh Equivalent Energistics only works with EE3 and not with ProjectE from my experience and has crashed the modpack way too manytimes in testing for my continued support.

The mod pack I've been building is centered around DimentionalDoors, AE2, and ProjectE exclusively and I would like to not rely on anything other than AE2 and ProjectE.

As stated the ratio is a little off especially as one builds out thier power flower. So maybe that should be a configurable option later on but lets go with 512EMC per 1AE.

**Comment by thatsIch** [comment]
Also I think EMC is not a really good power source (not energy)

There are some power systems that are intentionally not supported due to their design in the "world"

**Comment by MrPotatoGaming** [comment]
Why not just convert EMC into a usable fuel? Such as coal blocks or something of the sort, then just chuck that in the vibration chamber.  It wouldn't be hard to automate either, once EE3 is finally done. I don't think DynEMC takes fuel burn ticks into the calculation seeing as burn ticks don't tend to follow a pattern, it would be a bit difficult to come up with a value to account for EMC:AE conversion.

**Comment by usafphoenix** [comment]
^that's what i do. I just convert the EMC into a mid-grade tier fuel and pump it into a 64x survivalist generator. SUPER EFFICIENT....and possibly OP....  >__>

**Comment by thatsIch** [comment]
probably just the amounts of vibration chambers required xD

**Comment by denzuko** [comment]
@thatsIch EMC not energy?! uhmm EMC stands for "Energy-Matter Currency" a play on Einstein's E=MC^2. ProjectE/EE's EMC to Klein Star storage is something of which I feel AE2 is in spirit doing exactly the same but only as a large "digital storage" and automated crafting system instead of the more condensed EMC battery/transmutation system.

In either case I'm working out a good value balance in testing before releasing any versions for review that could be used for a pull request.

Currently following up with @yueh suggestion and testing out a 500 EMC to 1 AE based on the fact that a single Mark 1 Energy Condenser only do about 4 EMC per tick alone that equates to 32 ticks (or 1.6 seconds) for a single piece of coal valued at 128 EMC that burns for 16000 ticks. Thus, equating the power generation to the same as by the time one piece of coal burns through there should be only one more to replace it without the "OP" coal generation.

@MrPotatoGaming See my comment above, namely the coal coal generation part. If one was to have that same energy going directly to the ME network instead of a over abundant coal production then the game balance is preserved and one does not have massive backlog over filling their ME Network/Power flowers.

**Comment by Entoarox** [comment]
EE and AE treat matter v/s energy very differently, in very much incompatible ways (AE treats cobblestone and diamond exactly the same, EE does not)

**Comment by thatsIch** [comment]
I consider EE as a magic mod and thus resulting in magic power but not some form of electric energy, and just calling it that way, will not change that fact. 

There is intentionally no support for TC, TT, Bot and many more mods due to their non-technical/magical implementation in-world. 

It is purely a game-play decision and has nothing to do with balance.
