### ISSUE TITLE
Anhilation Plane not able to pickup items horizontaly

### ISSUE THREAD

**Issue by gatekeeper258** [AppliedEnergistics/Applied-Energistics-2#1797]
When the AP(anhilation plane) is facing upwards it can accept the grown seeds but if placed horizontally (to avoid the seeds hopping) it will not pickup any of the seeds. Is this a bug or intended?

**Comment by yueh** [comment]
Is placing them horizontally not the same as facing upwards (or downwards)? Or do you mean placed facing a horizontal axis (north, east, ...)?

Also the plane is only importing items, which are colliding with it.
So if you placed them facing north or so, then it is very likely that the seeds simpy did not touch it.

**Comment by gatekeeper258** [comment]
Ah OK. So if I have a two block tall water drop but the anhil plane on the
first water block (facing east) the seeds aren't picked up because no
collision. So I'd need a flowing water to push them to the plane. Would
that cause the same inefficient hopping as if the plane was under the water
facing up?

**Comment by ruifung** [comment]
What do you mean by hopping? Alternatively if you really want them to collect as fast as possible you could line the entire collection area with planes...

**Comment by gatekeeper258** [comment]
I have a me chest with a partitioned cell only to take pure crystals fully
grown. When the plane attempts to grab a seed and its not ready it 'hops'
up delaying the growth process

**Comment by yueh** [comment]
The hopping itself is fixed with RV3. But I never heard that it somehow affected the growing process and I never noticed an impact on it when testing it.
