### ISSUE TITLE
Feature Request: Save search mode per terminal, like sort by

### ISSUE THREAD

**Issue by Sciencentistguy** [AppliedEnergistics/Applied-Energistics-2#1798]
I would quite like to be able to have auto search + NEI on my main terminal, and Normal seach + NEI on my crafting and pattern terminals. Would this be possible?

**Comment by yueh** [comment]
#1586

**Comment by Sciencentistguy** [comment]
This is not the same as #1586, yueh.

**Comment by yueh** [comment]
Not as clear duplicate, but it touches the same issue.
So if we can add the other one, we can also include this. Github simply has not the option to mark a reference as "subtask" or similar.

Also if the other ones is not possible, this one will also not be possible (or at least it will be limited to a shared one for all terminals like this)

**Comment by thatsIch** [comment]
You can do it actually via checklists. Checking in the maintask the subtask, will close the underlying issue.
