### ISSUE TITLE
Missing Crafting Recipes

### ISSUE THREAD

**Issue by soulknight72** [AppliedEnergistics/Applied-Energistics-2#1799]
Some of the crafting recipes are gone. I put in the correct formation, but nothing comes out. I've seen another complaint like this, but the only recommendation was to remove other mods. I removed all the mods but applied energistics 2 (the rv2 stable 2 i put on after trying to re-install it) and the mod loader, and yet i can't make my cables.

**Comment by mindforger** [comment]
what cables exactly and did you by the way accidentially or intentionally enabled "unlimited channel"? and please provide which version you are running on
