### ISSUE TITLE
Storage bus desyncs with dynamic storage block

### ISSUE THREAD

**Issue by gigaherz** [AppliedEnergistics/Applied-Energistics-2#1800]
I recently released a storage mod, which has a dynamic number of slots (always 1 empty slot at the end, compacts itself as soon as a stack is removed). This works just fine with hoppers, pipes/conduits, and the EnderIO Inventory Panel, but an AE2 setup using a storage bus + interface fails to refresh itself properly when the contents change. I have done my best to improve the situation from my end, including calling markDirty whenever the contents change, but it doesn't seem to help.

At this point, there's nothing else I can do except blame it on AE2 not properly refreshing the contents if the number of slots has changed.

EDIT: My mod is https://github.com/gigaherz/Ender-Rift/

**Comment by yueh** [comment]
If you do not notify anything about the change, we have no chance to invalidate the inventory.
Just because some mods refresh it every tick, does it make a good idea and can also affect the performance badly.

markDirty just tells minecraft to save the TE, nothing else.

**Comment by gigaherz** [comment]
So how would one notify AE2 about the change?

**Comment by yueh** [comment]
Simple block update, as everything else does it.
But this is really better suited for a general forge modding place and not AE2 specific.
