### ISSUE TITLE
Network components can be destroyed even with a Security Terminal (wiki misunderstanding)

### ISSUE THREAD

**Issue by ExDomino** [AppliedEnergistics/Applied-Energistics-2#1801]
Even if I have a Security Terminal on my network, other players can destroy the components, for exemple the ME Drive with all of drives and steal my items. The Security Terminal prevents withdraw and deposit, but the build permission is not blocked.

The wiki is contradictory, it said « The security system does not prevent destructive tampering, removing cables / machines or breaking of drives is not directly provided by the security Terminal. If you need to protect your system from physical vandalism you will need another form of physical security. This block provides Network level security. » but also « G. Build: User can modify the physical structure of the network and make configuration changes. » so if the build permission is not made for preventing physical griefing, what is its purpose?

**Comment by yueh** [comment]
Exactly as it says, build/modify and configuration changes. But not destroying.
