### ISSUE TITLE
AE 2 Not Compatible with Mekanism 

### ISSUE THREAD

**Issue by Mr-Kaboom** [AppliedEnergistics/Applied-Energistics-2#1802]
I currently am running a single player world with Applied Energistics 2 rv1-stable-1, Mekanism (Standard, Generators, and Tools) 8.1.5.246, and other mods that have shown no issues (trial and error, removed and tried small sets of mods to find the ones causing issues). Upon attempting to load a recipe within my not enough items bar, I receive no results, and when I attempt to craft anything from AE2 (wiki for reference) I receive no output. The game does not crash or bug out, it simply does not provide anything. Any thoughts?

**Comment by yueh** [comment]
#1061
