### ISSUE TITLE
Chestname will not show up

### ISSUE THREAD

**Issue by Darklymediaa** [AppliedEnergistics/Applied-Energistics-2#1803]
I namend a Chest in a Anvil like "AE2 Inscriber" and the interface terminal will not show up the name from the chest.

![interface-terminal](https://cloud.githubusercontent.com/assets/13467602/9275929/f08da65c-42a0-11e5-8f41-8693a0351b95.jpg)

**Comment by yueh** [comment]
#1135, #1008, #414
