### ISSUE TITLE
Random weird disconnects from the server....

### ISSUE THREAD

**Issue by evernife** [AppliedEnergistics/Applied-Energistics-2#1804]
I get this errors a lot of times, only when i am near the Applied System...

There is no error by the server side, only this:
15.08 10:32:14 [Disconnect] User EverNife has disconnected, reason: Disconnected

But, in the client console i get this error : http://pastebin.com/EZhtVM0z

Just by walking near the system...

**Comment by yueh** [comment]
XU issue.

**Comment by evernife** [comment]
"XU " wtf?

**Comment by karakufire** [comment]
I guess XU means Extra Utilities.

**Comment by evernife** [comment]
Sorry, i didn't saw that...

The other error didn't metion him...

http://pastebin.com/mm1H8xqt

AnyWay, ty
