### ISSUE TITLE
Wireless Terminal not Connecting

### ISSUE THREAD

**Issue by Dolphinator** [AppliedEnergistics/Applied-Energistics-2#1808]
I have had a wireless terminal for a while and it worked fine. I logged on today and everything was out of power. I fixed my reactor and now my power is restored. When I try to open the terminal is says "Station can not be located."  I tried relinking and it still didnt work.r
![2015-08-15_14 40 52](https://cloud.githubusercontent.com/assets/13812489/9290321/ced85352-435b-11e5-81d0-b0edadb42484.png)

**Comment by yueh** [comment]
#1266, #1754
