### ISSUE TITLE
A couple questions

### ISSUE THREAD

**Issue by Speiger** [AppliedEnergistics/Applied-Energistics-2#1809]
I have at the moment a question about how a couple things work in AE2.. Because i want to try some things...

First: Is it possible to make a block use more then 1 channel (varibablish)?
Second: when does AE ask for gridflags? On load or dynamicly? can i tell that he rechecks it?
i will add some more questions later...
^^"

**Comment by yueh** [comment]
1. No, and it is completely against the balance in AE.
2. When adding/removing something to the network and some during the path finding

**Comment by Speiger** [comment]
1: Well it depends..
2: yeah gridProxy invalidate and validate after the imporantant calculation is done...

New questions... I am trying to make something like a crafting machine... It has its own CPU and does crafting jobs by its own (You put patterns in and it will slowly craft for you).. (very slow) but it is really hard to figure out what i need and what not...
What do i need for that and how do i need to implement it?
(Documentation from github is not really helpfull with it because it only has a licence and function explaining but thats it)

**Comment by yueh** [comment]
1. There is no "depends". It usually indicates a misunderstanding on what channels are, when someone consideres multiple channels per machine.

If you try to reimplement the AE1 MAC, be prepared of being unable to use any crafting related part of AE2. Most of it is actually coded against internal classes and will most likely not work when passing a custom implementation. The API here is mostly for read access. It is simply to complex and easy for an addon to potentially break it.

It is easy to add something providing the crafting operation and integrating it into the current autocrafting system. But replacing it is not really intended. Doing so will most likely involve the following points (if not more)
* Your own Terminal, as the normal ones will not be able to use your crafting system.
* Your own crafting calculation like AE2 (calculate all needed materials before) or similar to AE1 (iterative). 
* Maybe you are able to proxy to the current crafting system somehow to use processsing patterns.
But these are part of the AE2 autocrafting, which is designed around multiple CPUs. So maybe your own patterns, pattern terminal and interfaces.
* Anything requesting crafting like export buses will also need their own implementation to use your crafting system.

All in all it is very likely that you have to reimplement half of AE2 for it.

**Comment by Speiger** [comment]
@yueh you missunderstood me... I do not want to replace the new System... In fact it is better then the old one... (At least calculation wise)...
What i want to add is simply a block where you can put patterns in and it will craft byhimself, it also provides CPU power so you can make a crafting job with it. (It does not mean that the crafting job has to be stored inside of that block) but i want that you can use it for small systems... (combining a CPU with a Me Interface and a Molecular assembler) that is the idea^^"
Also i am not limited to the API... It requires your mod anyway so i can use internal classes.

Like i did with IC2 Classic, it loads optionally a P2P bus which works totally fine but i did not use your API i did use your internal code. But IC2 Classic does not require AE2 at all^^"
Please think of that option too.

**Comment by ruifung** [comment]
Well, the main reason for not using internal classes when possible is to avoid having to update if AE just refactors or moves a few internal stuff around.

**Comment by yueh** [comment]
It is really an advantage for both sides.
We know what we can change without breaking any addon and still be able to improve the code.
Addon devs then know what they can use without breaking every build or we might even change things so it is not longer possible to actually use our classes (like make them final)

@Speiger 
Also to summarize the irc chat. When we transfer these changes to IC2, it basically would require that the IC2 API allows to completely replace the whole energy system with something else like RF without breaking anything else.

**Comment by Speiger** [comment]
@yueh sry i did not nodest that you answered... (Thanks github)
what changes are you talking about?
I have not really a clue what you are talking about...

**Comment by yueh** [comment]
Adding something like this feature to AE2.

As you complained that the API does not allow you to replace a major system of AE2.
To really compare the impact on what it would have, it would require that the IC2 API is able to replace the whole EU powersystem with RF or any other energy system and simultaneously allowing the cables  act as transport medium for anything (items, fluids, whatever you can imagine)

**Comment by Speiger** [comment]
oh you are referencing from minesashas/ghoestcarbones post...
I said to him that the project is canceled/stopped because to implement something like that is distroying the mod and that is not what i want. The Idea of the multiblock structure CPU was that you have to build 1 single thing and you can craft with as much bytes as you want, and they have a storage of multible crafting requests. (it does only 1 crafting job at the time). But since that is not that possible how i wanted it i said nope...
Just to say it again. I do not want to distroy ae2 with that my idea was to extend it/giving more options.

**Comment by Technici4n** [comment]
@Speiger you can maybe create a multiblock and implement the interfaces on different blocks (btw this could probably require multiple channels): a crafting CPU and an ICraftingProvider (something like that)

But i'm not sure you can send a craft to a specified CPU and configure this CPU to only craft specified items
