### ISSUE TITLE
Inscriber printing,crafting cpu threads? and something wierd.. 

### ISSUE THREAD

**Issue by PRavenhold** [AppliedEnergistics/Applied-Energistics-2#1811]
Ok so the back story on this ive been using a 2 chest, 3 inscribers, 1 interface and a import bus for each type of processor to be made.. so obviously interface connected to the chest. item conduits distributing the items and in the last chest the processor gets importet.. to slow for me... 

so i upgraded it.. 
1 interface, 5 inscribers and 5 import buses.. for each type of printing.. 
in the end it seemed like already printed circuits got sucked in again into the inscriber and placed in the "middle" slot where the gold(for logic) was supposed to end up. and ofcourse totally destroying everything.. no idea why but happened "sometimes". 

so new setup.. 
![2015-08-16_04 37 45](https://cloud.githubusercontent.com/assets/9520386/9291755/3f264260-43d2-11e5-9efe-d859fb815133.png)
so these are my inscribers for circuits, a total of 30. an interface to a chest and import buses to get the circuits back into the system. works fine!

next.. 
![2015-08-16_04 38 04](https://cloud.githubusercontent.com/assets/9520386/9291760/8e2f6b70-43d2-11e5-8efb-2871f83e6ca0.png)
(dont mind the crap in on the floor "redecorating")
Here comes the fun part.. 15 inscribers 5 for each processor.. 
attached to 3 export buses and 1 import bus each, (to avoid the jaming from the previous setup)
but the recepie is just in a  kinda loop, and interface connected to a chest (1 printed circuit and 1 printed silicon = 1 processor) and gets imported to the system instantly. I thought it was a good idea since it worked for small batches.. and since everything gets printed and instantly exported to the inscribers that finish the job.. and here it comes.. BUT.. 

i ordered 200 64k crafting storage units.. 
so i think it was 5.4k or 5.6k logic processors that had to be made.. 
now.. first off.. the system did print all circuits at the same time.. worked nicely.. 
but the processors was another deal.. according to the processlist, all processors were being crafted at the same time but no that wasent happening.. only the engineering proc. were. and the calc. proc. the logic processors didnt get their logic circuits until the previous 2 where done crafting and for some strange reason i ended up with 1,4k printed logic circuits extra.. now how that happened i dont know. 
but my question is
Why didnt the inscribers print the processors even tho they all had the materials in storage? 
Could it be some priority/thread thing in the coding? 
i have 48 crafting co-processors for each crafting unit. and 98 64k storage units for it ;)

also shouldn't the system keep count on how much material is sent in to become circuits? since i got 1,4k to many circuits my guess is it somehow calculated wrong..
and for the last, got any idea how to get around this?

and btw yuhe thanks for mentioning chickenchunks as a probable cause for the system to do wierd shit, it solved like 300 problems i had.. so thanks alot..

**Comment by PRavenhold** [comment]
did the test again and it seems like im overloading the system. import buses stops responding, i can't even take items out from a terminal.

**Comment by yueh** [comment]
No idea how this actually works.

But until now, nobody could really provide a reproducable way to fail on the crafting calculation. Usually it was caused by some build issues, say looping items around so it would detect the same items multiple times, finishing the crafting and immediately starting a new one as there are still not enough ones crafted. While the old backlog is still being crafted.

**Comment by PRavenhold** [comment]
you are welcome to my server and test it ;)

**Comment by PRavenhold** [comment]
think i found a way to reproduce it.. not sure yet, going to try a couple of times..

**Comment by PRavenhold** [comment]
ok, so it seems like ive found whats causing my problems. since i'm using alot of RF and when i put in a huge order that requires alot more of RF than i produce, the AE system just cant handle it.. even tho i have a storage of about 50BRF. its like the AE system is about to lose power and turn off but it just glitch or something and continues.. i notice it in the me terminal with all my items disappearing and reappearing for about 10 ticks.. the import/export buses react when they seem to want to.. i look at the me drives and they don't black out or anything.. so when it glitches like this i get wierd results when trying to make processors. either i get a surplus of printed stuff or i'm missing some.. seems random too.. 
so i killed hm a few laser drills. to make sure i was producing alot more RF than needed. And guess how the tests went!! 
flawless :P

**Comment by thatsIch** [comment]
mh I guess the information of how much RF a craft takes would be interesting.
