### ISSUE TITLE
Suggestion - make autocrafting prioritize the smallest crafting CPU

### ISSUE THREAD

**Issue by ariosos** [AppliedEnergistics/Applied-Energistics-2#1814]
Unless I don't understand what I'm doing (highly possible!), I was playing around with autocrafting and noticed that any crafting always used the crafting cpu with 11 64k Crafting Storage rather than the lone 1 64k Crafting Storage. I tested this out with a complex crafting recipe (i.e., a Solar Flux Voltaic Cell III) and a simple one (redstone blocks). Crafting 3,000 of them takes 97,628 bytes in my setup, which I expect to use the large Crafting Storage array. But, when I craft just 100 Blocks of Redstone (1,124 bytes), it's using the large (704K) crafting storage array, rather than the smaller 64K one. That means that any complex crafting recipes have to wait until the redstone one is done.

So, my suggestion would be to make the crafting recipes prioritize the lowest possible crafting storage array that's needed.

![crafting_setup](https://cloud.githubusercontent.com/assets/7917753/9293956/6ab677a4-440b-11e5-95d3-0c01993c4060.jpg)

![crafting_redstone](https://cloud.githubusercontent.com/assets/7917753/9293957/6ab6ceac-440b-11e5-854d-d7458078e627.jpg)

![large_array](https://cloud.githubusercontent.com/assets/7917753/9293955/6ab65e54-440b-11e5-90e5-0660a647acfc.jpg)

**Comment by yueh** [comment]
#1055, #1188
