### ISSUE TITLE
Allow more than one cable going through Quantum Network Bridge

### ISSUE THREAD

**Issue by scotty562** [AppliedEnergistics/Applied-Energistics-2#1816]
Right now It's only possible (AFAIK) to run one cable through the Quantum Network Bridge. This means as far as p2p tunnels go I'm limited to 4 pairs of 32 channels. I would like to be able to run more cables through as well without needing to build a second QNB. Even if the limit was capped at 2 cables going through the QNB that would be fine. Enabling dense cable on both sides of the p2p tunnel would solve the problem as well.

**Comment by XFactHD** [comment]
You can use glass, covered or smart cable to connect the p2p tunnels with the dense cable that leads to the QNB. Or you put 4 rows of each 8 glass, covered or smart cables and put p2p tunnels on those rows.

**Comment by Cisien** [comment]
slap a controller on the cable that your p2p is connected to and you can move something like 1024 channels over the qnb. (32 pairs of p2p tunnels, each tunneling 32 channels) If your network is massive enough to run out of channels, then i think it would be easy to justify another p2p pair.
