### ISSUE TITLE
Terminal with View cell without sorting

### ISSUE THREAD

**Issue by anion155** [AppliedEnergistics/Applied-Energistics-2#1818]
Can you add sorting mode in terminal that places items like they were placed in view cell?
For example, Ex Nihilo add a bunch of metal related stuff for every metal, and the way I'd like to see them is table-like view:

|  | **Iron** | **Gold** | etc |
| --- | --- | --- | --- |
| **Broken** |  |  |  |
| **Crushed** |  |  |  |
| **Powdered** |  |  |  |
| **Dust** |  |  |  |
| **Ingot** |  |  |  |
| **Nugget** |  |  |  |

**Comment by yueh** [comment]
Would be an idea, but I am not sure if it is currently possible.

View cells are just filtering what is send to the client on the server side. The sorting then actually is done by the client and is also shared for any terminal on the same client. This setting simply cannot be moved to the server as some sorting modes are not available for any player (like inventorytweaks is completely optional).

**Comment by anion155** [comment]
Why would it must be done on server?
Client gets filtered information, choose "View exact sorting", then he gets view cell content information, and than puts filtered ItemStacks (or what are you using instead) on their places.
From View Cell can be deleted top and left empty rows and columns, to stay compact.
For multiple View Cells, next VC-design can be put on the next line from previous VC. 

Couple questions:
Is there a way to synchronously get view cell content information?
Is terminal stores ItemStacks linearly or in table? If linearly, it must be possible to add some kind of ghost ItemStack.
Is there a way to show one ItemStack in multiple places?

**Comment by Technici4n** [comment]
I don't think this is going to happen due to the amount of reworking that's needed for this feature.
