### ISSUE TITLE
Random Blocks showing up in spatical storage dimension 

### ISSUE THREAD

**Issue by arkcane** [AppliedEnergistics/Applied-Energistics-2#1820]
![wtf](https://cloud.githubusercontent.com/assets/13604047/9348032/5c654d56-45ff-11e5-983f-e54ad39151ff.png)

So sometimes when I leave and reenter into my spatial storage cell lab diamond and pink slime blocks show up out of no where. I was working on the lab (in the picture) then went to help a friend build something and when I came back those blocks were there. 

its always diamond and pink slime. they dont ever seem to replace blocks or move blocks 

The spatial cell that it is stored on was destroyed (to keep people from tampering with the cell and messing with my lab) and is not in the i/o port. (first thing I checked.)

This does not happen anywhere else but in a spatial storage cell dimension.

I am playing FTB direwolf20 (1.6.1) MC Ver 1.7.1 on the recommended version. which has AE2-rv2-stable-10

**Comment by yueh** [comment]
Are you sure no other mod interferes with it? The spatial dimensions really have no world generation besides the the borders. Especially as these are not completely vanilla or AE2 blocks.

**Comment by arkcane** [comment]
It only happens in storage cells and not in any other dimension that I can tell. the places they tend to pop up is near my well of suffering in blood magic and around the rftools teleporter. but I have a bunch of those set up in other places and those blocks have never spawned there before. as it happens when I teleport in and out (or spawn). going to remove some modded blocks in the area these things are spawning and see if that helps

**Comment by arkcane** [comment]
Ok so after some testing I think it has to do with light nodes from mods like enderio (powered lights) thaumcraft (arcane lamps). I am testing magical lamps and other light node items as we speak

**Comment by thatsIch** [comment]
oh, are these artificial light sources?

**Comment by arkcane** [comment]
Yea, the powered lights (enderio) arcane lamp (thaumcraft) magical lamp (factorization) all spawn invisible non interact able light sources. also since I completely anchored the storage cell its stopped happening as far as I can tell.

**Comment by yueh** [comment]
I still do not think AE2 is involved here. The only time it is modifying the chunks is when using an spatialio port to flip the content. 
Otherwise there is no interaction on loading a chunk on our side, this is just normal vanilla chunkloading. It looks more like some other mod is interacting with chunkloading and maybe is replacing specific blocks with some hardcoded values, as these differ for every map, thus can spawn random blocks.
