### ISSUE TITLE
Crafting will not start

### ISSUE THREAD

**Issue by speedcrafter442** [AppliedEnergistics/Applied-Energistics-2#1821]
some of my crafting recipes won't work. it is a blood magic ritual which will produce 2 gunpowder from 1 gunpowder, 1 sand and 1 coal. The system has a craftingcpu with a 64k crafting storage. 
http://imgur.com/x7QwGek

**Comment by ruifung** [comment]
more pictures of setup?
It's probably just no CPU on the current network as CPU's don't work through subnets

**Comment by yueh** [comment]
Recursive recipes are not supported (1x Item X => Nx Item X)

**Comment by gril002** [comment]
so there is no fix comming?

**Comment by ruifung** [comment]
It's not a bug. AE delibrately does not process recursive recipes.
