### ISSUE TITLE
Crash Rendering item

### ISSUE THREAD

**Issue by MySt1k** [AppliedEnergistics/Applied-Energistics-2#1824]
http://pastebin.com/S2cVTeiH

appliedenergistics2-core{rv2-stable-10}

**Comment by ruifung** [comment]
Lol what?

**Comment by yueh** [comment]
AE2 has no part with a damage/metadata value of 18, thus it simply fails.

For now I assume it is an issue with cauldron (which we do not support).
At least until you can provide a way to reproduce it without cauldron (and a way to obtain invalid items).

**Comment by MySt1k** [comment]
Good. In the near future I will do it
