### ISSUE TITLE
Terminal slots all greyed out and unusable?

### ISSUE THREAD

**Issue by Pocketkid2** [AppliedEnergistics/Applied-Energistics-2#1825]
This terminal was filled with a bunch of stuff. Then I upgraded the server from 1.8.2 to 1.10.1. Now it looks like this:

![2015-08-21_14 16 23](https://cloud.githubusercontent.com/assets/3046638/9419313/792f0082-480f-11e5-9b98-ba764c867590.png)

As you can probably tell it's quite unusable and I cannot figure out why. I tried reinstalling the entire pack as well, with no luck

**Comment by Xanphos** [comment]
Just some basic troubleshooting to get some sort of baseline here:
 * Does your system have enough power?
 * Does your system have a channel available for your terminal to use? Check via Smart ME cables or WALIA if you're unsure.
     * Does disconnecting everything else except for your storage and terminal allow you to see your items again? If this is the case, it's probably an issue with your channel management.
     * Try removing and replacing the ME Controller / a central line to your system -- It'll remake all the connections.

I'm sure this is a user-error issue, as I also have just recently updated my private multiplayer server to 1.10.1 from 1.8.2 without issue.

**Comment by Pocketkid2** [comment]
I will check and see if those are the issues. My friend who is the main maintainer of the ME system has not actually been on since the update and there may need some work done.

**Comment by Pocketkid2** [comment]
My friend got on and fixed the system. It now works. Thanks for the suggestions, I was getting worried that there were client problems!
