### ISSUE TITLE
Quantum ring problems

### ISSUE THREAD

**Issue by PRavenhold** [AppliedEnergistics/Applied-Energistics-2#1826]
so i finally started to expand with both wireless and dimension wide.. 
so my "base" is in a mystcraft dim, 1st outpost in another mystcraft dim and 2nd outpost is in the "OVERWORLD!!!" ;) 
well the whole system starts to glitch.. the whole system reinitializes over and over and over again.. since ALL channels do this.. 
now, is there nobody else who has this problem? 
im not using chickenshit anymore since it fucked up the me system totally but now im using MFR chunkloaders instead and i've removed those and same problem.. read something about giving more power to them so i did that like this (didn't any better)
![2015-08-23_00 54 12](https://cloud.githubusercontent.com/assets/9520386/9426237/689dc06c-4933-11e5-93ed-ed225a70cd13.png)

as soon as i disconnect the quantum rings from the network everything works fine.. 
so any ideas what can be causing this?

**Comment by PRavenhold** [comment]
now i have a friend helping me testing this and as long as im in my base everything works fine..  
so is it MFR chunkloaders that dosent work properly?

**Comment by PRavenhold** [comment]
nm solved it.. chickenchunks are chickenshit.. MFR is way better but when it comes to quantum rings it totally freaks out.. so world anchors solved that problem at least.. i just hope i dont get back some old ones because of this change..

**Comment by Technici4n** [comment]
I dont think you can have more than two QNBs in your network

**Comment by XFactHD** [comment]
You can have more than two, I for example have eight QNBs.

**Comment by Technici4n** [comment]
@XFactHD What do you use to chunkload ?

**Comment by ruifung** [comment]
I have 8 too, I use world anchors and chunk loaders from the tardis mod.

**Comment by thatsIch** [comment]
pay attention that nothing keeps reloading your chunks after you unload them or that something force unloads the chunks which are chunkloaded.

**Comment by XFactHD** [comment]
@Technici4n I am using MFR chunkloaders and for me they are working brilliantly.
Is this a server or singleplayer? If it's a server, are you using cauldron?

**Comment by Technici4n** [comment]
I used two QNBs on a server with ChickenChunks and it worked (they were both in the overworld)

**Comment by TheRobloxBloxa** [comment]
Not to interrupt but what texture pack is that?
