### ISSUE TITLE
Patterns place in ME Interfaces not recognized by AE System (AE System in RF Tools Ages)

### ISSUE THREAD

**Issue by MonkeyMechanic** [AppliedEnergistics/Applied-Energistics-2#1827]
So I play on a server pretty regularly, and the modpack the server uses includes RF Tools and Applied Energetic. After a bit of time playing I moved my AE system to a void dimension using RF Tools. I put the patterns appropriately in ME Terminals properly, however after a while of working properly as normal for auto-crafting these item, the patterns are no longer being recognized by the AE system and I can't auto-craft at all. Breaking and replacing Terminals, Clearing and resetting the patterns, disconnecting and reconnecting the AE system cables, nothing is fixing this.

Example)

Using a an Alloy Smelter from Ender IO to craft Quite Clear Glass, I made a pattern in the ME Pattern Terminal, placed an ME Interface on top, and then placed the pattern in the Interface in order to craft said patterns. Normally in the Crafting Terminal you would be able to see the icon of the item you're wanting to be able to craft with the word Craft in place of the actual number of items. This lets you tell the system to craft said items. The problem is that this icon doesn't show up when there are no stacks (or a partial stack) or said item. It's as if the system is not recognizing that a pattern is in said Interface. The Interface itself is recognized by the system as I also had it set to store a stack of dust to auto-process ore and it did so without a problem.

**Comment by thatsIch** [comment]
Need more information, please read how to post an issue

**Comment by PRavenhold** [comment]
MonkeyMechanic: everything worked fine until you moved to the RFTools void dimension'? 
i myself had problems in RFTools dimension so i moved to a Mystcraft dimension and that solved my problems..

**Comment by MonkeyMechanic** [comment]
Yes, but it wasn't right away. It took a few days until this problem came up for a weird reason. It might be RFTools, or an issue between AE and RFTools, because I know the Security Terminal doesn't play well with RFTools Dimensions (But that is another issue I will post a bug report about separately.) We no longer have Mystcraft mod within the modpack as it was causing problems generating tons of extra dimensions and was being very buggy on the server end.

I also updated the fist comment with an example of what I'm talking about.

**Comment by MonkeyMechanic** [comment]
So I have a bit of an update on this issue... It seemed to resolve itself. I don't think channels were an issues, but after tearing down nearly the entire system and rebuilding it in the dimension it seems that it's working properly. Maybe there was an error with the system the first time but I'm not too sure.

Feel free to close this ticket, as I'm sure I just encountered a fluke of some sort with the patterns.
