### ISSUE TITLE
autocrafting  in the Phytogenic insolator  issue

### ISSUE THREAD

**Issue by gril002** [AppliedEnergistics/Applied-Energistics-2#1828]
in the Phytogenic insolator you can "grow" plants like potatos, carrots, sugar canes etc. , but you need attleast one to make more. The problem is that the ME sistem print's missing items if I have to craft 90 it needs 10 to craft and if you have 5 for instance it will say missing 5 materials, becouxse it does not realize it can craft them too.

**Comment by yueh** [comment]
#1821
