### ISSUE TITLE
Mob storage and teleportation Includes digital Mob farm idea...

### ISSUE THREAD

**Issue by GamingMortal** [AppliedEnergistics/Applied-Energistics-2#1830]
Hi their, I expect that this idea has cropped up before but I think I've tough of a way of implementing it that fits with AE2 progression. I was thinking of a item like a Gashapon or block like a mob annihilation plane that could capture/store Mobs. Now the way I see it the item could be the used item but you would have to insert a storage drive into it. Now Living entities would obviously take up more space depending on their usefulness and/or strength. so chickens would take up the least amount of space but wither knight taking up a lot of space. I know that this may seem useless to be able to transfer/store mobs but I think you could create digital mob farms that are scalable in size inside the AE system were you could control what that farm does either killing, shearing or milking. I like the idea that their would be little pixel mobs running around on an AE2 Monitor. Their is a practical side to this rather than reducing the size of a mob farm. It allows users who run small servers or less powerful PC's to make large, powerful mob farms without the lag that comes from lots of entities and cross mod set ups. I hope you take my idea into consideration and thank you for listening and creating a supper cool mod.

**Comment by XFactHD** [comment]
This doesn't like something for AE2 itself, perhaps an add-on could do this.

**Comment by GamingMortal** [comment]
Just a shame I don't know how to do it then.

**Comment by thatsIch** [comment]
neat idea, but would hardly fit into AE2. Some problems I already see: 

* you have to hard code every entity for its usefulness (even consider zombie villagers which can return to villagers)
* there is currently no way to discern the usefullness of mobs
* how to add support for all the random mobs out there of other mods
* how to raster 3d models of mobs to 2d

neat idea if you like it that much to dig into MC Modding :)
