### ISSUE TITLE
Rendering problem

### ISSUE THREAD

**Issue by MrSapient** [AppliedEnergistics/Applied-Energistics-2#1831]
HexBlocks from Chisel 2 mod don't work well as cable covers... Some reason the color is not rendering when placed on cables.

http://i.imgur.com/WX6T5xL.png

Chisel 2 - 2.5.0
Applied Energistics 2 - rv2-stable-10
Forge - 10.13.4.1492

EDIT: Yes it happens with Texturepack off as well.

**Comment by yueh** [comment]
#285
