### ISSUE TITLE
Storage Monitor & GL Error

### ISSUE THREAD

**Issue by mrgrey1** [AppliedEnergistics/Applied-Energistics-2#1832]
rv2 stable 9&10. Any item (that I have tried,) when placed into a storage monitor causes the below error to spam in the client console.

[09:35:30] [Client thread/ERROR]: @ Post render
[09:35:30] [Client thread/ERROR]: 1286: Invalid framebuffer operation
[09:35:31] [Client thread/ERROR]: ########## GL ERROR ##########

EDIT: This error ~~stopped~~ was greatly reduced after disabling OPIS/Mapwriter on the server.

**Comment by yueh** [comment]
Especially the item rendering is highly defensive as there are enough possible mods around with faulty ones, which will finally break our rendering when not be used carefully.
Combine it with other more defensive ones and it can easily reach some hardware limitations like the opengl stack size.

It is maybe a bit too defensive in rv2 and rv3 does remove some of the overly defensive code, but the changes are simply to large to backport to rv2 without possible issues.
You could use the current alpha to test it, but do not forget to make a backup of the world before.
