### ISSUE TITLE
RF P2P tunnels aren't properly loaded after server restart.

### ISSUE THREAD

**Issue by MaxPower84** [AppliedEnergistics/Applied-Energistics-2#1834]
I have a setup like this:
EnderIO cap bank => P2P tunnel => EIO energy conduit => machines.

This works perfectly when i'm online and also when i log off. (The complete area is covered by chunkloaders) 
But every morning after the daily restart, my machines run out of power. The rest of the ME setup and other machines, that are powered by the same cap bank but through tesseract instead of P2P tunnel, work normally.

As soon as i log in to the area again, the P2P tunnels also work again. So the problem seems to be some interaction with chunkloaders.

Tried both railcraft and chickenchunks chunkloaders. Get the same behavior with both.
I am running FTB Infinity 1.10.1 and AE2 rv2-stable-10.

**Comment by XFactHD** [comment]
Try to put an energy conduit between the capacitor bank and the P2P tunnel and if this doesn't help, try the MFR chunkloader.

**Comment by MaxPower84** [comment]
Will try that and report back after the next restart.

**Comment by yueh** [comment]
Can you try it with another transfer like the fluxducts?

EnderIO conduits behave a bit different, as they basically want full control of the connection handling.
If something does not immediately allow RF connection they will lock this side of the conduit and do not allow further transfer. As AE does not guarantee any specific time on when it put its parts online, it might simply happen that the P2P tunnels are only available after some time and the conduit will just not accept any power. Especially when starting a server this might happen as we do not start the network immediately but it takes a few ticks.

**Comment by MaxPower84** [comment]
I now have a cryostabilzed fluxduct on the input side and will try a few different things on the output side.

**Comment by MaxPower84** [comment]
So i made a little test setup yesterday. 
I set up a few capacitor banks, where the input comes over p2p tunnel with different connectors in between p2p tunnel and cap bank, and the output goes back directly into the draconic energy core.
All inputs on the cap banks are set to a fixed 4k RF/t and all outputs are set to 2k RF/t.
So as long as everything works, the capacitors should stay full, but if something on the input side fails, they will empty.

So this is what i got: http://imgur.com/a/5sqsn
First pic was made after i finished the setup and the caps started filling.
Second pic when they were full.
Third pic i made this morning, a few hours after server restart.
It doesn't seem to matter how the p2p tunnels are connected.

The leftmost setup has the original setup from my initial post with the input p2p tunnel on a cap bank. All other setups have the input p2p tunnel attached to a cryostabilized fluxduct coming directly from the draconic energy core.

I have no idea whats going on with the 2 rightmost setups. In theory they should also fill at a rate of 2k RF/t but instead they are fluctuating around 4k. But this looks like a whole different bug.

**Comment by thatsIch** [comment]
can you reproduce this in a new fresh world, where we can actually look at the issue ourself?

**Comment by mskurnik** [comment]
I can confirm that this bug still exists.  The P2P power ports do not come online until you enter the region in which the AE network is in.  To test this I build a small p2p network with power flowing into a P2P RF via Cryo fluxduct/resonant and out into a tesseract.  Over 1K away I connected that tesseract to a series of TE energy cells that power various machines.  Power flows into them just fine but if I restart the server the power and join the server, the power is draining from the energy cells.  These cells will not recharge until I go over to where the energy generation is.

This bug happens with MFR, ChickenChunks, and railcraft chunk loaders.  What is strange is where the power is being generated I have a quantum ring and one where I am receiving power.  The quantum ring works just fine.  I can see everything on the network (which is powered by another energy source).  That network has 42 P2P ME ports installed and all of those come online just fine.   That means that the network is coming online but the P2P's just are not.

We have been experiencing this for 4-5 months now so it is something that has existing for some time.

**Comment by yueh** [comment]
@mskurnik As small hint, deleting a comment and creating a new issue will not really give it more attention. Once we have some time we will verify it and if necessary reopen the issue.

Otherwise I tried it with sending RF via a P2P tunnel to a chunk about 1k blocks away with a chunkloader (dimensional anchors) + tesseract attached to the output P2P and another tesseract as output to test the transfer and it worked flawlessly after restarting the world.

**Comment by mskurnik** [comment]
My apologies, I thought you might not look at closed reports.  It does with a setup like this:
![Subnetwork P2P](https://cloud.githubusercontent.com/assets/10066235/12509425/304d40c4-c0b7-11e5-954d-eaa7a6ff7219.png)

Here is a full list of mods I use in my pack which I can provide to you if you wish over IRC.

* AdvancedGenerators
* AE2Stuff
* AnotherOneBitestheDust
* AppliedEnergistics2
* ArmorStatusHUD
* Aroma1997Core
* Aroma1997sDimensionalWorld
* ATG
* AutoSapling
* Balkon'sWeaponMod
* BDLib
* BiblioCraft
* BigDoors
* BigReactors
* bspkrsCore
* BuildCraft
* BuildcraftCompat
* Carpenter'sBlocks
* ChickenChunks
* CodeChickenCore
* CoFHCore
* CollectiveFramework
* Compacter
* ComputerCraft
* ControlPack
* Decocraft
* Deconstruction
* Dynmap
* EnderBook
* EnderCore
* EnderStorage
* EnhancedPortals3
* ExtraBiomesXL
* ExtraCells
* Fastcraft
* FloodLights
* ForgeEssentials
* ForgeMultipart
* ForgeTeamspeak3Integration
* FurnitureMod
* Galacticraft
* GalacticraftPlanets
* GardenStuff
* GrimoireOfGaia3
* ImmersiveEngineering
* ImmersiveIntegration
* IronChests
* KingCore
* LiteLoader
* LunatriusCore
* MalisisCore
* MalisisDoors
* Mantle
* MicdoodleCore
* MineFactoryReloaded
* MobiusCore
* ModularPowersuits
* MorePlanets
* Natura
* NEIAddons
* NEIIntegration
* NetherOres
* NotEnoughItems
* Numina
* ObsidianBoat
* OpenBlocks
* OpenCCSensors
* OpenModsLib
* OpenModularTurrets
* Opis
* OptiFine
* OreDictionaryConverter
* Pam'sHarvestCraft
* PeacefulPlus
* Peripherals++
* PlayerAPI
* QuartzPlus
* Railcraft
* RenderPlayerAPI
* Ruins
* Sampler
* Schematica
* SimpleRecipes
* SimplyJetpacks
* SmartMoving
* SmartRender
* SolarFlux
* spatialiocompat
* StatusEffectHUD
* ThermalCasting
* ThermalDynamics
* ThermalExpansion
* ThermalFoundation
* ThermalSmeltery
* TiCTooltips
* TinkersConstruct
* Tinkers'Mechworks
* TorchLevers
* TwilightForest
* VoxelMap
* Waila
* WailaHarvestability
* WAILAPlugins
* WhatAreWeLookingAt
* WorldEdit

**Comment by yueh** [comment]
Way too many mods to reproduce it indev. Especially with mods like Fastcraft changing the behaviour of forge itself.

**Comment by mskurnik** [comment]
When I have time then I will try to shorten the mod list down and find which one is the issue.  This happened before FastCraft was installed.

**Comment by mskurnik** [comment]
I can confirm the issue does not seem to happen in single player but it does happen in multiplayer.  With the mods listed below I was able to reproduce it by doing the following:
# Setup
- Build an ME network like below with power flowing from one end to the other via P2P RF and have it export to a TD duct and then into a tesseract.
- Configure the tesseract to send power to a frequency (123)
- Place down a chunkloader to encompass the area.
- Go a decent distance away (I went about 1K away)
- Place a tesseract down and configure it to use the same frequency but receive power
- Place down a TD resonant flux duct
- Check RF with multimeter as it should say "192000/192000 RF"
- Place down another chunkloader

# Testing
- Reboot the server while staying at the area where you are receiving power
- View the power again with a multimeter a few times.
  - Type test into chat to force it to get another reading.
- Break the resonant fluxduct, place it down, type into chat to make sure you get a fresh reading, and then take a reading with the multi meter again.
 - Do this a few times and it will show "0/192000 RF"
- In order to get the RF back, you must go to where you are creating power and load that area.
- If you go back to the where you are receiving, you will see with the multi meter that you are again receiving power.

# Further steps
I can provide you with a save of my test world with all of the mods if you would like.

# Images
## ME Network
![ME Network](https://cloud.githubusercontent.com/assets/10066235/12535545/b501a050-c23b-11e5-85c5-78f84e913fcb.png)


# List of Mods
- appliedenergistics2-rv3-beta-5.jar
- ChickenChunks-1.7.10-1.3.4.16-universal.jar
- CodeChickenCore-1.7.10-1.0.7.47-universal.jar
- CoFHCore-[1.7.10]3.1.0B1-322.jar
- ThermalDynamics-[1.7.10]1.1.0-161.jar
- ThermalExpansion-[1.7.10]4.1.0B1-235.jar
- ThermalFoundation-[1.7.10]1.2.1-110.jar

**Comment by XFactHD** [comment]
Can you also reproduce this with MFR's chunkloader? The chickenchunks chunkloader is known to cause all sorts of problems.

**Comment by mskurnik** [comment]
Yes I can.  I can reproduce it in MFR, ChickenChunks, and RailCraft.

**Comment by XFactHD** [comment]
I can't reproduce this in SP, I will try it with a forge server environment. I am using MFR's chunkloader and even between dimensions over a quantum bridge everything works fine.

**Comment by mskurnik** [comment]
Correct.  Single player works just fine.  It is a Multiplayer-only bug.

**Comment by XFactHD** [comment]
I can't reproduce this, even with a modpack with over 200 mods. I am joining the server in my rftools dimension and after the main me system comes online and the quantum bridge in the overworld starts up, the rf p2p tunnels provide power properly to the machines. Even in the comact machines dimension everything works fine.

**Comment by mskurnik** [comment]
I can provide you a link to the simplified pack and world save on IRC if you wish.

**Comment by XFactHD** [comment]
Could you try to not use tesseracts and build an me system with a quantum bridge with the energy source p2p on one side and the target p2p on the other side?

**Comment by mskurnik** [comment]
I just tried what you asked and it behaves the same

**Comment by XFactHD** [comment]
This doesn't make any sense...

**Comment by mskurnik** [comment]
The only thing I can think of one of the mods at the start changed something in a dat file somewhere and that change persisted as I whittled down the mods to just the basics.  That means that I should be able to send you my world save and you can track down the error when you attach it to your IDE.

**Comment by XFactHD** [comment]
Can you reproduce this in a new world created with the smaller mod list?

**Comment by mskurnik** [comment]
Yes.  I am able to recreate it with
- appliedenergistics2-rv3-beta-5.jar
- CoFHCore-[1.7.10]3.1.0B1-322.jar
- forgeessentials-1.7.10-1.4.4.1130-server.jar
- MineFactoryReloaded-[1.7.10]2.8.1B1-170.jar
- ThermalDynamics-[1.7.10]1.1.0-161.jar
- ThermalExpansion-[1.7.10]4.1.0B1-235.jar
- ThermalFoundation-[1.7.10]1.2.1-110.jar

**Comment by bookerthegeek** [comment]
@mskurnik You said that you can only reproduce this in a SMP enviroment?
- Is this a server you are connecting to via LAN?
- Is this a forge or non-forge server?
 - What version are you using?
- Is this a fresh server instance you are doing this in?

**Comment by mskurnik** [comment]
I am connecting to a `forge-1.7.10-10.13.4.1558-1.7.10-universal` server with `LiteLoader 1.7.10 with Forge 10.13.4.1558`.  This is a fresh instance of the server.

**Comment by XFactHD** [comment]
Can you reproduce this without LiteLoader and/or ForgeEssentials?

**Comment by mskurnik** [comment]
I was able to reproduce this without both mods.

**Comment by Darkpye** [comment]
Was this issue ever solved? Having the same issue on our server.

**Comment by Darkpye** [comment]
> Was this issue ever solved? Having the same issue on our server.

Why was this marked as spam? This issue has been left completely in the air and unresolved, for anyone experiencing this bug it make the feature unusable. If there is a fix having it documented would be extremely useful. If there is no fix, then knowing that would be useful too, as it stands this current thread needs some kind of resolution.
