### ISSUE TITLE
Multiple patterns for same item, only uses one

### ISSUE THREAD

**Issue by JackTheRedCreeper** [AppliedEnergistics/Applied-Energistics-2#1838]
(I need to do a lil more check on this, but my pc was so slow today that I left)
So, I'm using B0BGary's growores, which is basically reeds that give minerals. In my ME network, I can craft ingots using those reeds.
Now I just added a redstone furnace (yeah, I'm still working on the network, just started with automating stuff :D). I added in the pulverized gold to ingot gold pattern and when I went to the terminal to test it, AE would only use the crafting reeds one.

Maaayyybbbeee if there weren't any reeds it wouldn't use them to craft, but I was using extra excess (it needed 25 more reeds which is 3 gold, and I have the dust) and nothing about the dust appeared.

Prolly it's something I gotta do, so I'm asking here.

**Comment by yueh** [comment]
#541

**Comment by JackTheRedCreeper** [comment]
Hm, thanks. Didn't expect a title so identical O.o

**Comment by JackTheRedCreeper** [comment]
Aaahh, nothing, it's working perfectly. Apparently on the test I asked for way too much gold ( I thought I had more gold dust ;~;)
