### ISSUE TITLE
"Lite" Version of AE2

### ISSUE THREAD

**Issue by silentstormpt** [AppliedEnergistics/Applied-Energistics-2#1840]
This isn't much of a issue but a request. The main problem with AE2 for those who dont want automation are Crafting CPU's and ME Interfaces. However, AE2 is extremely fun to play with specially if its purpose is Storage, would it be possible if you could release a "lite" AE2 version without auto-crafting. Thanks in advance for reading this.

**Comment by yueh** [comment]
Use the configuration to change AE2 for your personal requirements.

Interfaces are an exception and cannot be disabled, as they are a pretty important (and not just autocrafting). But otherwise you can just disable the autocrafting.
