### ISSUE TITLE
Missing channel (when there are enough)

### ISSUE THREAD

**Issue by Xynelio** [AppliedEnergistics/Applied-Energistics-2#1842]
I just setup some storage bus with deep storage unit, but for no reason, i'm missing channel on some of my P2P, when they are exactly the same as the other. i tried different configuration, but nothing change. Here some screenshot :
![image](https://cloud.githubusercontent.com/assets/14028176/9561413/b1ec1406-4e44-11e5-8a7b-2dc9e4531b56.png)
![image](https://cloud.githubusercontent.com/assets/14028176/9561414/c6f63516-4e44-11e5-9420-3cb7664b7ac4.png)
![image](https://cloud.githubusercontent.com/assets/14028176/9561415/cf2f0168-4e44-11e5-990f-f0403800d8c2.png)
Is it a bug ? Or did i miss something maybe ?

**Comment by Acters** [comment]
I would like you to go to the other of that exact P2P and check whether or not the cable leading to the P2P are full.
If you feel as though there are supposed to be enough channels then make the P2P connect directly to the controller and see if this still occurs.
if not then the connection between that ME Storage Bus and the Controller have became full.

**Comment by Xynelio** [comment]
Thanks you for the answer, yes in fact i link my P2P to my ME controller, which took a channel, so i just replace it with a quartz fiber and it worked, that's all rigth :)
