### ISSUE TITLE
MFR Unifier can convert Certus Quartz Ore into Charged Certus Quartz Ore

### ISSUE THREAD

**Issue by Hypocrisy** [AppliedEnergistics/Applied-Energistics-2#1844]
This is a very powerful bug as the Unifier requires no power and can convert whole stacks into the charged counterpart.

**Comment by thatsIch** [comment]
this is due to both ores being in the same oredictionary entry.

It is fixed with https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/1634

I need to re-instantiate my setup to make it match with the current version. Count it as fixed.

**Comment by yueh** [comment]
I would personally consider it an MFR issue as the OreDict is meant for items being used equally in recipes, not to convert between them (this break enough other mods like thaumcraft)

We can just assign a different oredict name for charged certus to fix it and use our own internal "OreDict" of the custom recipes to mimic the old behaviour as some recipe will accept normal as well as charged certus (and some not).
But not all mods have a similar system and where is the point in having an oredict, if you need to handle each and every variation in a seperate recipe?

**Comment by Hypocrisy** [comment]
Sorry, I'm not a developer so I can't offer any input, nor do I represent MFR so perhaps you should address your concerns to them instead. However, I will tell you that in further testing I have found plenty of other mods that will easily convert regular Certus into Charged. This includes:

* JABBA barrels
* Storage Drawers
* Forge Lexicon from Thermal Foundation

So, it would seem there is a system that many mod makers have agreed on, regardless of it being the right one. 

Normally I would alert all mods involved in a bug but seeing as how the common factor in this is AE2 I think it would be best handled on your end. It is your mod, however. You are free to name ores how you wish.

Good luck in your endeavors.

**Comment by thatsIch** [comment]
#1588
