### ISSUE TITLE
Cannot disable SpacialIO and have successful server start

### ISSUE THREAD

**Issue by khionu** [AppliedEnergistics/Applied-Energistics-2#1846]
Whenever I disable SpacialIO in the config, the server fails to start. Complete freeze, the server does not respond. Running KCauldron (1492.155).

**Comment by thatsIch** [comment]
Try running it without cauldron, else I can not help you much without a crashlog.

**Comment by khionu** [comment]
I'll have to do that tomorrow. Currently finalizing the configs for a yet-to-be-published public server. Not too much of a problem to leave SpacialIO on, the only reason I wanted to disable it is for backup sizes.
