### ISSUE TITLE
Autocrafting Won't Start with Wireless Terminal in Inventory

### ISSUE THREAD

**Issue by izzyaxel** [AppliedEnergistics/Applied-Energistics-2#1848]
Encountered in rv2 stable 10, multiplayer, no crash or error message/stacktrace, private modpack: http://www.technicpack.net/modpack/duneyrr

Attempting to autocraft anything from a block terminal's GUI won't proceed to the simulation if I have a wireless terminal in my inventory. (shift left clicking to skip the simulation doesn't work either)  Autocrafting works normally from the Wireless Terminal GUI.  This doesn't happen with a much simpler setup in a test world, so I'm unsure what conditions cause it or how to reproduce it, other than complexity perhaps.  I also tried breaking and replacing all elements of the autocrafting system, and the Security Terminal, but neither helped.

https://www.youtube.com/watch?v=1TpxI9XfyUo

**Comment by yueh** [comment]
Cannot reproduce it.

I would recommend testing for other mods interfering with it, I sadly cannot point to any mod in your pack potentially affecting it. But there are a a couple of mods unknown to me.

**Comment by CodeGrappler** [comment]
I had the same issue just moments ago. Using the Direwolf20 1.7.10 FTB mod pack.

The only thing before it started happening to me was a server restart.

For what it's worth it fixed itself just by dropping the wireless terminal and picking it back up again.
