### ISSUE TITLE
NEI Shift Clicking ? not pulling minecraft items from AE2

### ISSUE THREAD

**Issue by omk5565** [AppliedEnergistics/Applied-Energistics-2#1856]

**Comment by Acters** [comment]
I believe NEI's Shift+Clicking doesn't work for non-stack able items.
What you provided is bare minimum, please provide more info.

**Comment by expl0s1ve** [comment]
Even non stackable items work with NEI shift clicking in ME crafting terminal.

**Comment by Acters** [comment]
ah ok, then thanks for the info. However, we still don't have enough information to declare this an issue.

**Comment by yueh** [comment]
See the our guidelines to contributing

**Comment by nahoul** [comment]
this is a very old post, but the only one i found that matches the issue i am facing. 

only when creating IC2 machines, shift+clicking don't pull Minecraft vanilla items such as iron ingot/cobble store etc. it only pull in IC2 items

**Comment by XFactHD** [comment]
IC2 is using custom recipe handlers, that is most likely the cause.

**Comment by mukunku** [comment]
I have the same issue as @nahoul

**Comment by mindforger** [comment]
@mukunku if you have an issue, please create a new issue with details to your minecraft installation (minecraft/forge version, mods installed and mod versions, you can create a forced bugreport by pressing and holding F3+C until the game  crashes while ingame, not menu) 

don't post in ancient old and already closed issues that have nothing to do with current versions :)
