### ISSUE TITLE
"Explosion" on client when autocrafting yellow wool

### ISSUE THREAD

**Issue by iambob314** [AppliedEnergistics/Applied-Energistics-2#1858]
Update: the solution is to uninstall FlatSigns, or downgrade FlatSigns to version 2.0.0.17. Read on to discover how this could possibly be the issue...

AE version: rv2 stable v10. Forge version: 10.13.4.1448.

When AE is used to autocraft yellow wool, the *client* sees an infinite number of of yellow wool stacks erupting from the molecular assembler used for crafting. This will typically lag the client out _very quickly_  (in a matter of seconds). On reconnecting, the visual glitch will be gone, assuming autocrafting has completed.

It is a client-side-only effect, and has no effect on the server. It appears to only occur when crafting _yellow_ wool; no other color of wool has this issue. I have not observed this issue when autocrafting any other item.

Before autocrafting 1 yellow wool:
![2015-09-05_20 10 12](https://cloud.githubusercontent.com/assets/2476126/9701786/ac7b5b32-540a-11e5-9fbe-3038c74b9050.png)

After autocrafting:
![2015-09-05_20 11 34](https://cloud.githubusercontent.com/assets/2476126/9701787/c7ee4b0e-540a-11e5-84a7-18fef0356473.png)

![2015-09-05_20 11 48](https://cloud.githubusercontent.com/assets/2476126/9701789/d53a60ae-540a-11e5-98f9-3ba2bd900350.png)

![2015-09-05_20 11 55](https://cloud.githubusercontent.com/assets/2476126/9701790/d87c761c-540a-11e5-9bad-05b82d43a9f8.png)

(Note: the setup in these images is complex, but I have reproduced it in single player using a minimal system; I just don't have the screenshots handy)

This was tested in a modpack; I've not had a chance to confirm it in an AE-only environment.

Simple instructions to reproduce:
1. Build an AE system with a controller, drive/chest+storage cell (any size), pattern terminal, interface/molecular assembler pair, and crafting CPU (any size).
2. Put white wool and yellow dye into the system
3. Make a pattern for yellow wool (standard recipe: yellow dye surrounded by white wool)
4. Autocraft any quantity of yellow wool

**Comment by yueh** [comment]
This is the Botania magnet ring not working correctly, you can clearly see the particles of it.

But it does not happen with just Botania and AE2. The particles are still showing up, but it will not pull items from it. If it would just be Botania, it would also affect any item and not only yellow wool.
Maybe something else is interfering with the spawning of entities? Say because it needs yellow wool as in world crafting ingredient?

**Comment by iambob314** [comment]
I am using the magnet ring in this picture, however the issue still occurs without it (I should have removed the ring before this picture for clarity).

In-world crafting of some other mod interfering is an interesting theory. At some point when I have time, I can try a binary search of removing mods and see if I can pinpoint the interfering mod. It's very strange that _only_ yellow wool is affected, as I'm using AE rather extensively for autocrafting (I have about 1000 normal crafting recipes registered), and have had no other similar issue.

Incidentally, I discovered this glitch while trying to automate the Botania Spectrolus flower, which needs to consume all 16 wool colors. It was a test setup in single player, so it was rather minimal (including no magnet ring), and only yellow wool exploded like this.

**Comment by iambob314** [comment]
Possible lead: a quick Google search indicates that FlatSigns has in-world crafting with specifically yellow wool: dropping yellow wool in water produces a sponge. We do have FlatSigns installed.

**Comment by mindforger** [comment]
also check for the Ancient Warfare Mod, it seems to have issues with spawned pseudo Items too
https://github.com/BluSunrize/ImmersiveEngineering/issues/368 also maybe it's an forge issue with the API

**Comment by iambob314** [comment]
Thanks for the tip. We don't have AWM installed, but we do have Immersive Engineering.

**Comment by iambob314** [comment]
In the interest of providing more information for anyone else working on this, here is our full mod list (Forge version 10.13.4.1448 as in original post):

BugfixMod 2.5.0
Zelda Sword Skills 2.2.8
AE2Stuff 0.3.1.33
AOBD 2.6.3
Applied Energistics 2 rv2-stable-10
Baubles 1.0.1.10 (autoinstalled)
BDLlib 1.8.1.87
BiblioCraft v1.10.5
BiblioWoods[BiomesOPlenty] v1.9
BiblioWoods[Forestry] v1.7
BiblioWoods[Natura] v1.5
BigReactors 0.4.3A
Binnie Mods 2.0-pre11
BiomesOPlenty 2.1.0.1067
BloodMagic 1.3.3-11
Botania r208
Buildcraft 7.0.19
Buildcraft-Compat 7.0.10
Carpenter's Blocks v3.3.6
ChickenChunks 1.3.4.19
Chisel2 2.3.10.37
chunkgen 1.2.3
CodeChickenCore 1.0.7.46
CodeChickenLib 1.1.3.138 (autoinstalled)
CoFHCore 3.0.3-303
CoFHLib 1.0.2-160
ComputerCraft 1.74
Computer Landmarks 1.0
Dense Ores 1.6.2
EnderIO 2.2.8.381
EnderStorage 1.4.7.36
EnderTech 0.3.2.388
ExtraCells 2.2.73b129
ExtraUtilities 1.2.9
FastCraft 1.21
FlatSigns 2.1.0.19
Forbidden Magic 0.562
Forestry 3.5.7.16
Forge Multipart 1.2.0.344 (autoinstalled)
GalacticraftCore 3.0.12.341
Galacticraft-Planets 3.0.12.341
Gendustry 1.4.12.92
GravityGun 4.0.0-beta
Guide API 1.0.1-20
iChunUtil 4.2.2
Immersive Engineering 0.5.1
InventoryTweaks 1.58-147
Iron Chests 6.0.60.741
JABBA 1.2.1a
Logistics Pipes 0.9.1.15
Looking Glass 0.2.0.00
Magic Bees 2.3.3
Mantle 0.3.2
MicdoodleCore 3.0.12.341
MineFactory Reloaded 2.8.0-104
MoarPeripherals 1.53
ModularForcefieldSystem 3.0-ALPHA-21
Morph Beta 0.9.1
Morpheus 1.6.4
MrTJPCore 1.0.9.18 (autoinstalled)
MystCraft 0.12.3.00
Natura 2.2.0.1
NEI Addons 1.12.9.32
NEI Integration 1.0.9
NotEnoughItems 1.0.5.111
ObsidiPlates 3.0.0.18
OpenBlocks 1.4.4
OpenCCSensors 1.7.5
OpenModsLib 0.8
OpenPeripheral AIO-5
Origin 5.0.0.288
PlayerAPI 1.2.
PortalGun 4.0.0-beta-4
ProjectRed Base 4.7.0pre1.84
ProjectRed Compat 4.7.0pre1.84
ProjectRed Integration 4.7.0pre1.84
ProjectRed Lighting 4.7.0pre1.84
Railcraft 9.6.1.0
RandomThings 2.2.4
RedstoneArsenal 1.1.1-89
Rouge-like Dungeons 1.3.6.3
sampler 1.44
SimplyJetpacks 1.5.1
SolarFlux 0.8a
StevesAddons 0.10.12
StevesFactoryManager A93
StorageDrawers 1.5.5
TC Node Tracker 1.1.1
Tinker's Construct 1.8.5
Tinker's Mechworks 0.2.14.100
Thaumcraft 4.2.3.5
Thaumcraft Gates 1.4.1
Thaumcraft NEI Plugin 1.7a
Thaumic Expansion 3.0.0-beta.22
Thaumic Exploration 1.1-37
Thaumic Tinkerer 2.5-506
Thermal Dynamics 1.1.0-161
Thermal Expansion 4.0.3B1-218
Thermal Foundation 1.2.0-102
Thermal Smeltery 1.2.1
Translocator 1.1.2.15
Twilight Forest 2.3.7
Waila 1.5.10
Waila Harvestability 1.1.2
WR-CBE 1.4.1.9

**Comment by iambob314** [comment]
Just had a chance to do some testing.

Confirmed: the issue _does_ occur in a minimal creative world with only the following mods installed:
Applied Energistics 2 rv2-stable-10
CodeChickenLib 1.1.3.138 (autoinstalled)
FlatSigns 2.1.0.19
Forge Multipart 1.2.0.344 (autoinstalled)
NotEnoughItems 1.0.5.111

No modification of FlatSigns config fixes the issue. The issue _does not_ occur if FlatSigns is removed from this mod list.

FlatSigns is not open source, and the dev (Myrathi) appears to no longer be active based on some quick searching (though I could be wrong). So, it's unlikely the bug will be fixed from either AE2 (due to closed-source FlatSigns) or FlatSigns itself. Instead, I've determined two options to work around the issue:
* Uninstall FlatSigns completely.
* Downgrade FlatSigns to version 2.0.0.17 (which is before the in-world sponge crafting was added).

Thanks everyone for the help in diagnosing this absurd bug. Special thanks to yueh for the key insight into fixing it, and for going so far as to set up a minimal mod testbed such an obscure bug.

**Comment by yueh** [comment]
Nothing we can really fix (in a sane way) and I would not be surprised, if it can cause other issues by overwriting the normal entity for yellow wool. Like the Spectrolus not detecting yellow wool (maybe not now, but potentially in the future)
