### ISSUE TITLE
Issue with AE Storage Bus and Compact Chest from CompactStorage

### ISSUE THREAD

**Issue by tattyseal** [AppliedEnergistics/Applied-Energistics-2#1860]
Someone has reported an issue where if you use a storage bus with my Chests then it voids items once the chest is full. I have checked the code and this might not be on my end. I just thought I would notify you if this is an AE issue. 

Original Report: https://github.com/tattyseal/IssueTracker/issues/12#issuecomment-138315187

Problem: When you place an Applied Energistics storage bus any sized compact chest, once the chest fills up you can still place items into the AE terminal but it instead voids the item.
Expected: To not use that chest anymore and to move onto another storage place in the network but instead voids items.
Reproduce: Place a storage bus on a compact chest (i would guess)
Server or SinglePlayer: both

TileEntity for Compact Chest that would be source of issue if on my end (i am 50/50 on whether it is on my end or AE's end): https://github.com/tattyseal/CompactStorage/blob/2.1/src/main/java/com/tattyseal/compactstorage/tileentity/TileEntityChest.java

**Comment by yueh** [comment]
Typical off-by-one error on your side. You report an inventory size of 28 for an inventory with 27 slots.
Thus the last slot is always empty and a valid location to store (void) an item, which will happen with every automation like BC pipes, TD ducts and whatever else.

**Comment by tattyseal** [comment]
Ah, thanks.
