### ISSUE TITLE
Filtered Storage bus in extract mode doesn't filter

### ISSUE THREAD

**Issue by tiennou** [AppliedEnergistics/Applied-Energistics-2#1870]
I have a dedicated subnetwork (controller+drive) for my mob farm where I process the generated "junk" into more valuable items that are sent to my main network.

I need level emitters to know how many there are of some items in the main network though (like Ender Pearls, Blaze Rods, etc.), but I want the various terminals in the subnetwork to only report the actual content. So there's 2 Storage bus to the main network, one is Output (Insert Only) filtered on what's worthy of leaving the subnetwork, the other is Input (Extract Only), filtered with the items I need the quantities for.

There are — from what I have tested in a creative test world — 2 bugs here :
- I can grab anything even though the Input storage bus has a filter and Extract Only.
- the Report Inaccessible Items toggle doesn't work.

As such, the terminals in the subnetwork always displays all the contents of *both* networks, so I can't tell where does an item come from.

FTB Infinity 1.10.1

**Comment by yueh** [comment]
This is intentional and described on the wiki page for the [storage bus](http://ae-mod.info/ME-Storage-Bus/).

**Comment by tiennou** [comment]
Oops. Well. Would it be possible to make this a feature request instead ?

Also, can you describe a case where the Report Inaccessible Items will do something, please ? I'm now wondering what it can be used for :smiley: !
