### ISSUE TITLE
Limit the number of concurrent crafts for a recipe

### ISSUE THREAD

**Issue by Rostepher** [AppliedEnergistics/Applied-Energistics-2#1873]
# Problem

It is very difficult to automate crafting for systems that cannot handle concurrent crafting for a recipe. Normally, recipes used in ME Interfaces to produce items like silicon can be stacked, as the machine can accept multiple items without halting the craft. In other instances, such as automating a mod like Botania, it is very difficult to create an automated system that can craft more than one recipes worth of runes, brews or flowers at a time. The crafting mechanics rely on items being dropped on one of the botania specific crafting blocks. If you drop too many of any item in a recipe it will fail to craft the requested item.

# Solution

I propose a change to either the ME Interface or the addition of a new card modifier that can limit the number of concurrent crafts for the recipes in an interface to 1. Then it will only put the items for a single craft into the interface at a time and wait until the current craft is complete before proceeding.

A possible change to the ME Interface could be the addition of a toggleable switch on the side to change between single item crafting and unlimited item crafting modes.

Another possible solution would be add another mode to encoded patterns.

**Comment by yueh** [comment]
Use blocking mode (and see #1722 for a similar post)
