### ISSUE TITLE
Feature Request: Void Card

### ISSUE THREAD

**Issue by eslachance** [AppliedEnergistics/Applied-Energistics-2#1875]
At the moment there is one thing that prevents a 100%, erm, "easy" setup in AE2: Voiding stuff when you have too much of it. Aka, keep only X number of stacks of cobble and delete the rest. While it is possible to send items to a trashcan or other voiding apparatus with an export bus and a level emitter, having one such setup for each item is a little complex.

My suggestion would be a Void Card, which would act similarly to the Void Upgrade from both JABBA and Storage Drawers. When added to an ME Drive or an ME Chest, anything that cannot fit within the storage cells would be voided. A single ME chest with a partitioned cell and this card would then be suitable to replace about a dozen barrels/drawers with void upgrades (with storage buses), for the things you know you'll get a lot of because of automation, farms, and quarries.

**Comment by yueh** [comment]
#465

**Comment by eslachance** [comment]
So the answer is, instead of doing level emitters and export buses to a Trash Can, do it on a matter condenser? I guess I'll keep using barrels then!

**Comment by ruifung** [comment]
Priorities and storage busses!

**Comment by eslachance** [comment]
Right. Unfortunately, both the priority/storage bus concept as well as even my Void Card idea have the same problem, I just realized: the storage cell can fill up, say, with cobble and not accept any more of the other items such as sand or gravel, there's no way to set it to keep a max number of each (like 64 stacks in each barrel). Oh well.

**Comment by ruifung** [comment]
Uh huh. Barrels only store one item type. For similar use case, just use multiple cells.
