### ISSUE TITLE
Feature Request: Storage cell for non-stackable items

### ISSUE THREAD

**Issue by eslachance** [AppliedEnergistics/Applied-Energistics-2#1876]
One "limitation" of having the 63 item type limit in cells, is that you end up with a whole lot of 1k drives filled with non-stackable items such as tools, armor pieces, enchanted books and potions. 

There's a great block from Extra Utilities that helps in this regards: an Advanced Filing Cabinet with a storage bus set to very high priority will store all of these items - I believe 1500+, with no issue whatsoever.

What would be nice to replace it, would be a special cell that can only accept non-stackable items in the same way the AFC does. Perhaps as a mod integration, requiring a filing cabinet in order to craft, if that mod is present?

**Comment by bookerthegeek** [comment]
+1, amazing idea actually.

Much more likely to be added through extra cells.

**Comment by yueh** [comment]
#672
