### ISSUE TITLE
Shift-clicking items in interface GUIs loses items

### ISSUE THREAD

**Issue by p455w0rd** [AppliedEnergistics/Applied-Energistics-2#1882]
If I have a crafting card in an interface and I shift-click any other card, those cards simply disappear. Also if I have a stack of crafting cards and I shift-click the stack, one card is inserted into the card slot, the rest are displayed in the export output slot and when I click those, they disappear. - Running Ae2-RV3-A5 (updating to A6 today, but I didn't see any mention of this in the changelog)

**Comment by ruifung** [comment]
Export output slot. You sure they aren't going into the AE network?

**Comment by yueh** [comment]
1) If you place anything inside an interface it will be imported into the network
2) Cannot reproduce. Also the config uses fake items, we will not change it so it starts duping items.

**Comment by p455w0rd** [comment]
o.0 Didn't even think about that..I'm in the middle of updating my pack/server. I will check as soon as I can, but I'm pretty sure you are probably correct. In fact, since yueh can't reproduce, go ahead an close this. I trust your conclusion to be correct.

**Comment by yueh** [comment]
1) is pretty similar to #779, simply the way minecraft handles inventories and shift clicking..
2) This is something, where I would not ignore any potentially interaction with other mod(s)
