### ISSUE TITLE
Formation Plane spawning items from a disconnected network.

### ISSUE THREAD

**Issue by leolson** [AppliedEnergistics/Applied-Energistics-2#1885]
I am not sure if this is intended, but it seems like a bug to me.
I created a small subnet whose only purpose was to pull items out of a chest with an Import Bus and then drop them with a Formation Plane.  It is only connected to my main network by a single Quarts Fiber for power.  This seemed to work fine until the first time I added a new stack of redstone dust to my main system via my Crafting Terminal and it dropped out of the what I thought was an isolated Formation Plane.  I then tried with other various items and the same thing happened so I could no longer store anything in my system because it would all just drop out right away.  I get that this intended with a fully connected Formation Plane, but it doesn't make any sense to me when it is isolated by a Quartz Fiber which I also verified with my Network Tool that nothing else was showing up when I clicked on the subnet.

I am playing in FTB: Infinity, but I am not exactly sure of the version numbers at the moment and I will have to add them a little later.

**Comment by yueh** [comment]
No idea how to reproduce it. Are you sure the system is not simply storing new items inside the chest, which is then dropped?
