### ISSUE TITLE
[Feature Request] Instant speed card

### ISSUE THREAD

**Issue by Silly511** [AppliedEnergistics/Applied-Energistics-2#1887]
I think you should add a card like the acceleration card but where things you put it in would do their job instantly. For example, if you put it in a export bus, the export bus would fill the inventory it's connected to instantly. Or a Molecular Assembler would craft all the jobs it was given instantly. This is probably to OP but just wanted to put it out there.

**Comment by yueh** [comment]
You answered it yourself, too overpowered.
