### ISSUE TITLE
Unable to remove items from ME System

### ISSUE THREAD

**Issue by Exodus89MTG** [AppliedEnergistics/Applied-Energistics-2#1889]
Hi,

I have been trying to get an ME system setup using mostly DSUs for all of the major items the I stack up on.  It has been working fine and I have also added in some drive storage for crafting purposes.

I connected some extra DSUs so that i could prepare the system for my mob spawner that i had just built and when i returned to the crafting terminal, i was unable to withdraw or deposit items.  in the config on my server and game i have channels disabled so i know that this is not the issue and I have ample power output to be able power the system and all of the auto crafting.

Any advice would be great

Thanks

**Comment by XFactHD** [comment]
Try to put some ae energy cells on your system (the ME system can only accept as much power per tick as it can store).

**Comment by Exodus89MTG** [comment]
Thanks. I will try this when I get home

**Comment by Exodus89MTG** [comment]
This is now sorted thank you
