### ISSUE TITLE
Autocrafting logic bug

### ISSUE THREAD

**Issue by agowa338** [AppliedEnergistics/Applied-Energistics-2#1895]
I've two recipes
1. Craft 1 Soul Vial with: 1 Soularium and 3 Fused Quartz
2. Create 1 Frank'N'Zombie and 1 Soul Vial (Zombie) with: 1 Soul Vial and 1 Z-Logic Controller

the last is sitting inside an interface and has two outputs.

If I try Crafting a Soul Vial, it trays to use the 2nd recipe and tells me, that I've not enough Soul Vials (Zombie)

I'm playing on 1.7.10 (Direwolf20 Modpack) with the Version ae2-rv2-stable-10.

**Comment by yueh** [comment]
#541
