### ISSUE TITLE
Storage Montors are possibly rendering too often

### ISSUE THREAD

**Issue by thatsIch** [AppliedEnergistics/Applied-Energistics-2#1896]
The storage monitors are using the TESR upon list change which makes sense. 
But there is a possibility that the amount is not taken into consideration before marking a storage monitor to update. (Only need to re-render if the amount hits a specific threshold for the amount renderer to render something different? e.g. 10k are still rendered the same even with 10001 items)

Did not investigate this nor did I look into the code. Just had a hunch when hearing somebody saying that too many storage monitors is lagging for him in a large storage solution.

**Comment by yueh** [comment]
Looking at [AbstractPartMonitor.java#L411-L427](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/3fb3f70392cf5f4b3da16e02ce9538938cba6bf2/src/main/java/appeng/parts/reporting/AbstractPartMonitor.java#L411-L427) clearly indicates that an update is triggered each time. So sounds perfectly valid.
