### ISSUE TITLE
RecipeResourceCopier also copies empty folders

### ISSUE THREAD

**Issue by thatsIch** [AppliedEnergistics/Applied-Energistics-2#1898]
Is due to the recursive nature and the pre-mature folder force-making

**Comment by yueh** [comment]
Could also be solved by ignoring empty folders via gradle. So if we ever intent to add an empty folder for the players to put stuff into it, we do not have to use same workarounds like using a `.keep-this-directory-file`.

**Comment by thatsIch** [comment]
It was more an issue with the copier creating the folders while iterating the tree structure for the `HTML` help page
