### ISSUE TITLE
CTRL + C Creates phantom Certus Quartz Pillar

### ISSUE THREAD

**Issue by Milesnocte** [AppliedEnergistics/Applied-Energistics-2#1903]
Presdsing ctrl c creates a pillar client side that I can stand on but no one else can see or touch.

**Comment by yueh** [comment]
Cannot reproduce.

**Comment by Milesnocte** [comment]
this happened in a server fyi

**Comment by thatsIch** [comment]
1. AE has no real key bindings but for `space`, `ctrl` and `shift` for inventory management in GUIs (e.g. terminals)
2. how you know its a certus quartz pillar
