### ISSUE TITLE
[Permission Request]

### ISSUE THREAD

**Issue by Carbon-Ghost** [AppliedEnergistics/Applied-Energistics-2#1909]
We are making a mod that brings back some old stuff to AE. The mod will be compatible with AE2, though will be able to be standalone, my request is, can you allow me to have used 1 texture from AE1 ( crafting terminal ) and 3 colors from AE1 ? And also if possible, though optionnal, the name AE in the modname please.

**Comment by yueh** [comment]
Nobody except Algo can give you the required permissions as AE1 is completely closed source including the textures. So I would recommend contacting him directly.

As advice, I would not count on it. They share similarities with AE2 and his (and our) general style guide is to have distinct texture for everything to clearly distinguish them.

The same applies for anything related to the AE1 code as well as the project name.
And as far is I remember, Algo already declined all previous requests regarding it.

**Comment by Carbon-Ghost** [comment]
For the project name it's ok if it's doesn't contain AE, though I used 3 colors from AE1 and used 1 texture, though the crafting chassis in our mod looks a heck lot like the AE1 pattern holder, so I might need to change it... But basically our mod will keep the concept of the ME stuff, though with a different style of gameplay being closer to AE1 and logistic pipes + code will be 100% custom.. Also where can I contact him ? And I am 100% ok to change the textures, though I quite like them ;-; Gonna use the crafting table one from vanilla if really it's that bad ^^

**Comment by Carbon-Ghost** [comment]
Some blocks are also reminiscent of RP2, and I inspired myself from the ME interface to create our own ( haven't copied it, though 1 of the rings unfortunately matches with the AE2 one.. )

**Comment by thatsIch** [comment]
We just own the private e-mail but obviously can not share it here. Maybe you can find him on Patreon. Pretty sure twitter, github and curse are muted.

**Comment by Carbon-Ghost** [comment]
Can someone then relay the message up to him ;o so he knows I want to speak with him :/

**Comment by Carbon-Ghost** [comment]
ME interface him pretty please :D

**Comment by thatsIch** [comment]
Sorry, I will not mix up private matters with AE. If you can not contact him, he does not want to be contacted.

**Comment by Carbon-Ghost** [comment]
Mmh... Kk, but then lemme reformulate my request, may I use AE2 crafting terminal texture for my mod ? I just need the shape ^^ ( I will redo all textures for that )

**Comment by thatsIch** [comment]
shape?

**Comment by Carbon-Ghost** [comment]
like you know the crafting terminal 9 squares and the line around it ?

**Comment by thatsIch** [comment]
which is just an implication to the minecraft crafting bench

http://ecx.images-amazon.com/images/I/41Xkzz3PsDL._SL500_AA300_.png

I am pretty sure, you do not need to copy it 1 to 1 :laughing:

**Comment by Carbon-Ghost** [comment]
So can I keep the textures then :D ? I will rename the mod due to permissions ^-^

**Comment by thatsIch** [comment]
No, but the shape.

Be inspired :+1:, do not steal :-1:

**Comment by Carbon-Ghost** [comment]
Kk, gonna redo the texture that involved the terminal, and it's what I've done ;)

I also inspired myself from the ME interface, well once texture sheet is finished, I will put it here for your approval if it's respecting everything or if it's too close to the original just to be sure ^-^

**Comment by Carbon-Ghost** [comment]
![assets_blocks_alternate](https://cloud.githubusercontent.com/assets/10200094/10412658/33ce8fd0-6f8d-11e5-87cf-014ca88951c7.png)
Approved ? I inspired myself like you said, everything was made from scratch or used the vanilla crafting table, I did inspired myself from the old AE color, though normally I used similar colors, and not the same ones, blame me if I'm wrong, and if you find that my Auto-crafter interface looks to much like the AE one I can change it, the idea was to make it look like a ME interface - RP2 filter hybrid, in the end looks too much like a ME interface, but if you are ok I may keep it..

**Comment by thatsIch** [comment]
yea looks fine to me :+1: 
you got the theme

Cheers, feel free to report back if you are finished :)

**Comment by Carbon-Ghost** [comment]
New mod name will be Logistic storage, it will be a spiritual successor to AE1, once mod is in stable, I will add a block to have interaction between LS and AE :D ( and LP ^-^ ). 

Gonna maybe change the Autocrafter interface to have the "X" of the RP2 filter, gonna see..

Last thing, thanks for letting me doing this spiritual successor, dramaless talking ftw :D

**Comment by Carbon-Ghost** [comment]
1 IMPORTANT QUESTION : Are we allowed to put the mod on curse ? Technically we are only a spiritual successor of AE1 though a lot of thing will change, and code and textures ( inspired and approved ) are custom, I ask this just to be sure ;)

**Comment by thatsIch** [comment]
Should be technically fine,
if you want to be sure, 
ask a curse moderator

**Comment by Carbon-Ghost** [comment]
I am no expert in curse, Speiger asked this just to be sure we haven't done anything wrong ( and to avoid useless drama ). I will take this as a yes for now as you approved. ^-^

**Comment by yueh** [comment]
It is not really a yes, but also not a no. We simply cannot make any statement about AE1, beside try and hope for the best.
As long as you do not have an ok by Algo, there is always a risk. Probably not likely, but something to remember just in case.

**Comment by Carbon-Ghost** [comment]
Again, the mod is only a spiritual successor of AE1, basically a logistic sorting mod, without the new tweaks of AE2 ( channels, CPUs... ) hence why spiritual as users might have a nostalgic wave, heck it doesn't even have buses, the only thing that is a nod to AE 1 and 2 is the external crafter ( which looks like a bit like an ME interface ;) ). I will make a documentation file on the blocks, I will post it here so you know what I mean, The mod is also inspired by RP2 for some textures and small thingies ( made from scratch, see above ) so lol. Note the mod was first to bring back the old AE1 stuff to AE2 but we changed it once we saw it was too complex.. So we made it standalone from scratch ! It will still be compatible with AE2 though :3
