### ISSUE TITLE
Autocrafting Fluid Support.

### ISSUE THREAD

**Issue by ruifung** [AppliedEnergistics/Applied-Energistics-2#1917]
This is something thats been on my mind for a while now, AE2's autocrafting has no way to deal with fluids as part of its materials calculation. I've been unable to find a way to have a crafting recipe that accepts both fluids and items as materials and outputs items (if its for fluid output then its doable) as the materials calculation for item crafting is pretty much hardcoded to use items in the crafting subsystem.

What I would like is for the crafting subsystem to be able to handle fluids as I see no way to add it short of replacing the entire crafting service, this isn't something thats doable from a addon without resorting to hacks that doesn't work well at best.

(EC2's current fluid crafter actually just strips the fluid items out from the recipe passed to the crafting subsystem)

**Comment by thatsIch** [comment]
AE2 just supports the native crafting recipes since no native fluid crafting system exists. Currently there are so many implicit hacks in there just to support from a normal `IAEStack` to the `IAEItemStack` (just try filling out the generics for `IAEStack`).

If you want a mixture of both this sounds like a new chapter. 

Which explicit changes are required for this?

**Comment by ruifung** [comment]
For starters, based on what I remember from my initial examination of AE's crafting system, for starters it needs to be able to handle IAEFluidStacks as recipe materials or recipe results, 
The actual materials calculation code was well... complex is one way to put it.

I'd say the actual changes would be - solving the IAEStack generics wierdness - It's actually playing hell with my code in scala -([_ <: IAEStack[_ <: IAEStack[_ <: AnyRef]]] is what I actually need to use to get it to compile in some places.

Other then that? I'd guess theres also making the crafting GUI's able to show a... fluid?
I'm available for discussion on this, but I don't understand the crafting system well enough to say, despite my efforts to study it

**Comment by Heliomance** [comment]
The Extra Cells addon mod already does this.

**Comment by ruifung** [comment]
And as the person currently actively working on ExtraCells, I originally put in this in order to improve the functionality of the fluid crafter - however following a discussion on IRC with @yueh and @thatsIch I've settled on a alternative approach that would require less radical changes.

P.S. Feel free to close this.

**Comment by thatsIch** [comment]
You can close it yourself if you think it fits

**Comment by ruifung** [comment]
I'm leaving it open because I think it WOULD be nice to have - if you guys ever decide to make the changes,

**Comment by thatsIch** [comment]
PR *cough* :P

**Comment by ruifung** [comment]
Maybe when I can comprehend the autocrafting code sufficiently to modify it. Heh.

**Comment by Blue64** [comment]
PneumaticCraft seems to have an interesting mechanic for their Plastic Mixer, perhaps reviewing their code could help.

Also Adventure Backpacks has 2 Fluid Tanks and a Storage along with a Crafting Table.

Steve's Carts allows for putting Fluids in buckets in the Liquid Manager, which I think might be auto-extractable as well.

Worst comes to worst, one can always fill buckets via a PneumaticCraft Omni-Directional Fluid Hopper placed next to a Dropper that shoots Empty Buckets, then collect it after it's filled.

There's plenty of workarounds, but I'm guessing PneumaticCraft Plastic Mixer has the closest to what you're getting at from the mods I've used.

**Comment by Aberro** [comment]
Still no changes in fluid support?

**Comment by ShadwDrgn** [comment]
it's worth mentioning, the Sequential Fabricator in TE has this in a way that would likely work great for what AE2 has. Necroing since this is still open, and would be AMAZING in AE2

**Comment by frizzle101101** [comment]
I have begun work on this over on my fork if anyone is interested in helping I could use some help from ppl who know the system https://github.com/frizzle101101/Applied-Energistics-2/commit/4a486b1abe5a5b6e4503dde3fdf7296fadae4cdb

**Comment by EnlitHamster** [comment]
This issue is a zombie rn, but is it implemented?

**Comment by frizzle101101** [comment]
Not that i know of, i wish it was there was no one else ready to help me
dev it so i havnt touched this in a while

**Comment by Technici4n** [comment]
There are some plans for 1.17, details tbd.

**Comment by Technici4n** [comment]
Implemented by #5428.
