### ISSUE TITLE
Ideas for wireless improvements

### ISSUE THREAD

**Issue by Wuestengecko** [AppliedEnergistics/Applied-Energistics-2#192]
The whole wireless system could be largely extended - #47 is just a tiny part of what could be possible.
- First of all, it would be pretty nice if Access Points could be ceiling-mounted :)
- The second is a "repeater mode" for WAPs. In this mode, they act just like real world WLAN repeaters: they connect to a distant network (where both endpoint WAPs need at least enough boosters to 'see' the opposite side).
  In "repeater mode", they do not connect to the network, therefore do not require a channel (neither from the power-source network nor the data-source "wireless" network), however the do require power to operate.
- The third, in addition to "repeater mode", is a "client mode". In this mode, it acts similar to Wireless Terminals, as it connects (possibly via repeaters) to a distant network and provides up to 8 channels to the network it is physically connected to. Just as the Q-Network Bridge, both 'sides' count as the same network, meaning you cannot have controllers on both parts as long as they are connected.

A note about balancing with the Q-Network Bridge:
Since you cannot transfer power wirelessly with repeaters, you need to build a small power setup for each repeater. Also, repeaters have a limited range - in contrary to Q-Networks, which work even across dimensions.

**Comment by Deshiba** [comment]
@yueh "...some mods need to be considered for balancing."
@Cisien "Short range you have cables. long-range you have the QNB."

Balancing with certain mods in mind will also mean that it is going to be expensive to the point of unbalanced if those mods are not present. While editing the amount of items needed in the configuration file might be an option for some, it'll just be a power creep for others.
The mid-range gap that several people have voiced suggestions for don't actually replace QNB's long-range/interdimentional functionality. Most suggestions would only ommit the obstruction that physical cable's cause at the cost of power and channels.

That being said, for most people having a mutually exclusive receiver that can catch the WAP signal without the power transferring functionality would suffice. Whichever constraints are attached wouldn't make a functional difference. Taking up a channel, not transferring power, only working directional/spherical/line-of-sight or anything else would just be there for balance and the unique feeling.

Any mid range solution would be welcome, either unique or a blatent copy... Looking at you "4k" and "16K" storage cells ;)
