### ISSUE TITLE
always use smallest Crafting-CPU available

### ISSUE THREAD

**Issue by Bimmbamm** [AppliedEnergistics/Applied-Energistics-2#1920]
Hello everybody,

first i love your mod. For me it's the best mod of all. But i hate it when i autocraft something small (maybe logic-processors) and it uses the biggest crafting-cpus available. It would be really nice if the ME-Network would always choose the crafting-cpu with the smallest matching memory available for an autocrafting-job ...and yeah i know i can do it manually.

Greeting from Germany
Bimmbamm

PS: sorry for my bad grammar :)

**Comment by yueh** [comment]
#1055, #1188, #1814
