### ISSUE TITLE
Can't figure Out How To Autocraft (request iron ingot)

### ISSUE THREAD

**Issue by Zezarict** [AppliedEnergistics/Applied-Energistics-2#1922]
I have a processing encoded pattern, 1 iron ore to 1 iron ingot. It's in an ME Interface. That ME interface is hooked up to a lot of things including a Mekanism basic smelting factory. The export bus leading to the smelting factory has a crafting card in it.  I click craft on the iron ingot to request some, the ME Crafting CPU has the iron ingots show up on it's interface, but they don't get made? There's plenty of iron ore in the system, in the ME drives. And that is hooked up to everything.

Now whenever I connect it, nothing works. It says there's no power but even a creative energy cube does nothing for the power. Whenever the computer's connected, absolutely nothing works now.

**Comment by Zezarict** [comment]
It also seems possible that it's using too much power? I don't see my energy cube draining but as a test I put 1 16k block down for the computer, and that took 3krf/sec..

**Comment by thatsIch** [comment]
Request crafting and export crafting are 2 different options to craft items.

Export crafting requests a crafting process every time the export bus is activated (redstone controlled e.g. or by default depending on GUI settings). A crafting process will be queued up in your Crafting-CPUs. So these are unrelated to ME Interfaces.

Request crafting via ME Interfaces enables you to interface with a certain machine (rotate to ensure the correct direction). If you put a crafting pattern in there, it will tell the system, that it has a possibility to craft from item X to item Y. **Upon** a manual (crafting terminal) or automatic crafting request (ME Interface, Export Bus) the system will give the ME Interface item X and waits until it gets an item Y. The ME Interface will **push** item X into the adjacent machine.

If something is still unclear about the process feel free to make a screenshot to explain your setup. In response I can show you an explanation or a counter setup to correct your issue.

**Comment by Zezarict** [comment]
I'm goign to bed right after this and don't have time to open up minecraft, so just reply about this for when I get up. Why is it that when the crafting cpu is on, that everything is suddenly unpowered? It says it requires to Krf/t for a crafting CPU made up of just 1 16 k storage drive that I tried as a test. Evne with a creative energy cube to power to Network and all the machines, it doens't work at all with the Crafting CPU plugged in.

**Comment by Zezarict** [comment]
Okay, now my import and export busses aren't even working. Checking with a network tool,e verything's connected!

**Comment by vallard192** [comment]
Do you have a ME controller?

**Comment by Zezarict** [comment]
I have an energy acceptor. Also this problem of busses not even working was fixed by resetting the server. But it just happened again after about 2 hours of play.

**Comment by vallard192** [comment]
If you don't have a ME controller, then you can't have more that 8 devices
hooked up at once.

Have you read http://ae-mod.info/Channels/ ?

Can you upload screenshots of your ME system?

**Comment by Zezarict** [comment]
No, they do work, they just randomly stop. And I have channels off. I have everything working now though, it jsut very randomly stops...

**Comment by thatsIch** [comment]
Try updating your version, it seems you using an outdated version of AE2
