### ISSUE TITLE
Quantum Bridge issue or something

### ISSUE THREAD

**Issue by CitiesXL2815** [AppliedEnergistics/Applied-Energistics-2#1924]
Quantum bridge does not work in single player World, it's so annoying, follow every step, chunk-loader, lots of RF and make sure it's connected, but don't see my inventory in the crafting terminal. imgur link: http://imgur.com/a/PEU4A

**Comment by CitiesXL2815** [comment]
And it's in the overworld in different biomes

**Comment by XFactHD** [comment]
I see that you are in creative mode. Did you create the quantum entangled singularities by hand or did you use NEI to cheat them in?

**Comment by CitiesXL2815** [comment]
yeah cheat them in, i'm still learning about AE2, learning from soaryn's stream and direwolf20's youtube videos.

**Comment by yueh** [comment]
Creative spawned ones do not work (and never will)
