### ISSUE TITLE
Compatibility with MyTown2

### ISSUE THREAD

**Issue by Esctogrillo** [AppliedEnergistics/Applied-Energistics-2#1925]
I'm using your mod in my public server, that have MyTown2 mod to protect the player houses. But, the only mod that don't protect it's the Applied Energistics. Others players can remove my cables and terminals only by shift-right-clicking in it.
I asked to MyTown2 mod developer to fix this issue, and he responded by saying that only you can do this.
http://prntscr.com/8mfz6s

**Comment by yueh** [comment]
See #1396, #645 and to some extend #1244.

In summary we do not deny it in general, just this particularly flawed implementation.
Doing it right will take some time. It simply is not one of the the current top priorities, there still more important things to do.

As AE2 is open source, if anyone wants to contribute a sufficient implementation, we would highly appreciate it. As well as provide as much help as possible regarding the design and to match our requirements.

**Comment by ruifung** [comment]
And after all this time, its pretty safe to conclude that the safest form of area protection - is denying area protection in the first place.

Although... I have to wonder, would having AE post a custom event for wrenching parts with the full detail of what is wrenched work - then leave it up to protection mods to catch it.

**Comment by yueh** [comment]
The PR contains some information about what is required.

But it is completely flawed, when the server is not intended as single player world and players want to actually share some stuff. Allowing access to the ME network would require giving everyone the permissions to break your base as it is not just preventing wrenching stuff but also open any guis like terminals or buses.

**Comment by Esctogrillo** [comment]
Maybe, protect the AE System completly with ME Security Terminal.
Would encourage players to create protection that offers the mod.
It's more easy, right?

**Comment by ruifung** [comment]
The PR in question is working entirely with PlayerInteractEvents. - What about having a custom event... for example AEWrenchEvent or something to that effect?
