### ISSUE TITLE
How do I search by mod?

### ISSUE THREAD

**Issue by Ricket** [AppliedEnergistics/Applied-Energistics-2#1926]
With NEI, I can type the name of a mod and it will filter by that mod automatically. It might also get some results where the item name contains the query, but for the most part, it's a convenient way of viewing just the items from a specific mod.

Is it possible to do the same thing with the search box of an ME Terminal? I haven't found a way to do this.

**Comment by XFactHD** [comment]
Put an "@" and then the modid into the terminal. Example: @thermalexpansion
