### ISSUE TITLE
me light blue dense cable is not dense

### ISSUE THREAD

**Issue by pancho507** [AppliedEnergistics/Applied-Energistics-2#1930]
light blue dense cables in the rv2.stable build 10 version seem to support only 8 channels 
behaviour is on the image:
![2015-10-03_13 50 06](https://cloud.githubusercontent.com/assets/14956584/10264579/c59958ea-69d5-11e5-8e54-46b156140a36.png)

**Comment by yueh** [comment]
Keep in mind that any AE machine will also transfer channels, not just cables and these are also limited to 8 channels.
I would recommend reading [this](http://ae-mod.info/Channels/).

**Comment by siasur** [comment]
I ran in this Problem too. I had a big wall of drives and needed 3 Dense Cables to connect them all...
And to get all drives connected i had to restart my server ('cause then somehow all drives found her connection)

Could it be posibble to preferr calbes over machines in the pathfinding?
Like "Hey, I have a cable attached. Let's find a way through this."

**Comment by yueh** [comment]
It already prefers cables over machines in case of same length. But this will still prefer a shorter route through a machine, if available.

**Comment by wlhlm** [comment]
See the Design section for some tips and explanations: http://ae-mod.info/Channels/
