### ISSUE TITLE
ME Interface won't craft into ME Import Bus

### ISSUE THREAD

**Issue by Ricket** [AppliedEnergistics/Applied-Energistics-2#1931]
![2015-10-04 04_21_26-minecraft 1 7 10](https://cloud.githubusercontent.com/assets/196978/10267045/a1c06d1c-6a4f-11e5-9555-c484bc4352e0.png)

I set up the above: ME interface connected to my main network; then a ME Import Bus on the side of the ME interface connected to a ME Formation Plane, separated from the main network by a quartz fiber. I populated the ME Interface with the pattern for fluix crystal. When I order some fluix crystals, they just sit in my crafting CPU, the interface doesn't send into the ME Import Bus and out the plane. But if I put anything in the top config section of the ME Interface (the box with the down arrow in it), then the formation plane spews that item until I run out.

If I put a chest between the import bus and the interface, it works; the interface puts the crafting materials into the chest, and the import bus takes them out.

I think the issue might be that the subnetwork doesn't have storage. But this should be a bug; the official wiki says about the ME Formation Plane, "**It functions as storage** similar to how a ME Storage Bus, so items that are added to the network are dropped or placed passively."

If it is not a bug, is there any other better way to do this, and why does it act this way?

**Comment by XFactHD** [comment]
A pushing device cannot put items into a pulling device.
To fix it, simply put a part interface in place of the import bus.

**Comment by Ricket** [comment]
Thanks, the interface worked. I wish there were better explanations of these concepts, but I'm slowly getting it...
