### ISSUE TITLE
Ability to add chances to craft in percentages.

### ISSUE THREAD

**Issue by pathurs** [AppliedEnergistics/Applied-Energistics-2#1935]
A lot of mods use percentage chance for additional materials, or for the material to even be crafted, such as scrap, thermal expansion machines and ender IO machines.

This could be used also for Botania Floral Fertilizer, which creates 6-8 flowers of the 16 possible, which is a 37.5% - 50% chance of the wanted flower to be produced.

The system could either wait to see what is produced, such as waiting for slag which is 25% chance to come into the network (Which is what I am assuming how most of the system works), or it could multiply the materials that are sent in by a percent, using my example above, it would double or triple the outputted materials, this however would not work 100%, as of course you cannot guarantee one with chance.

Possible GUI interface, next to the output, an up/down arrow with % chance of material coming out

**Comment by yueh** [comment]
#1007
