### ISSUE TITLE
Items Access seems broken

### ISSUE THREAD

**Issue by mindforger** [AppliedEnergistics/Applied-Energistics-2#1938]
we are running on a small server and using the newest rv3a8 and a lot of other mods as we noticed 2 odd things

first ist the listing of items in the system while taking out an item
best way to reproduce was by dropping different kinds of potions in the system
when you search for potion, you'll see them all, but when you take a potion out, the list halfs or sometimes also gets empty until you search again
(it's probably related to us havin still extracells installed, but i'll test this again without later, as we do not want to fragment or break our world i need to make a new testserver)

the second bug is related to MFR Plasticsheets:
when i have several stacks of plastic sheets in my system and left click and draw them out i get a stack of 128 plastic sheets for some unkown reason (same for rightclick, where i get 64 instead of 32)... i noticed an odd behaviour with tinkerers construct and plastic sheets too, so maybe it's not your fault at all

the funniest is when i drop the stack in my inventory i am forced to split it to regular 64 items-stacks, but when i drop the drawn stack to the ground and then loot it, it becomes overstacked
(same goes for nonstackable but stacked items i get from villagers (bee frames for example), so i believe this also is not your fault, more like forge/minecraft mechanic)

**Comment by yueh** [comment]
We replaced the collection for cells with b8 for a slightly faster implementation (`O(1)` vs `O(log n)`). But seems we still need to respect the self cleaning of the old collection, otherwise it will do strange things in some cases like this one.

Plastic sheets simply stack to 127 by default. Not our issue. Also some inventories are simply build with a max stacksize of 64 in mind, which might cause issues when some items allow larger ones.

**Comment by mindforger** [comment]
there seems to still be an related problem, but probvably it's another issue about bontania flowers, they show very odd numbers of different types of flowers and i can only extract a unspecified number of few flowers at a time. the listing is glitched like in b8 they partially disappear form the list when i try to extract a few flowers and i may have also lost several flowers

set up a ME network with controller, drive, some 1k and 4k cells, connect an acceptor via cable to one side of the controller, the drive on another side and a terminal. now drop in some mystical flowers (different types). try to take em out and see the inventory glitch
