### ISSUE TITLE
What exactly do Co-Processing Units do?

### ISSUE THREAD

**Issue by Jorvalt** [AppliedEnergistics/Applied-Energistics-2#1939]
On the official wiki, it says that they increase the amount of tasks that a crafting CPU can perform at one time, but that's simply not true. If I try and queue one item for crafting and then queue another different item at the same time, it tells me there are no CPUs available. So, what exactly do these blocks actually do?

**Comment by mindforger** [comment]
what official wiki did you read?
http://ae2.ae-mod.info/Crafting-Co-Processing-Unit/
ist very precise i think

**Comment by XFactHD** [comment]
Let's say you want to autocraft an engineering processor from silicon and diamonds and you have one inscriber for diamond circuits and one for silicon. When you don't have co-processors on your system, one item will be crafted after the other. If have co-processors on your system, the system will craft as many items parallel as you have co-processors (as long as you have enough processing machines).

**Comment by Jorvalt** [comment]
So ae-mod.info isn't the official wiki?

And that's pretty lame. It can do multiple parts of a multi-step crafting process at the same time, but it can't do separate single-step crafting processes at the same time?

**Comment by thatsIch** [comment]
it is the official

A process is a set of tasks. While a Crafting-CPU can handle the whole process, it is not specialized into working on crafting tasks. While Co-CPUs can not handle crafting processes, they can virtualize the crafting tasks into sub-tasks and split them among other Co-CPUs.

This restriction does not force you to only use 1 Crafting CPU.
