### ISSUE TITLE
Crafting pylons seems to loose inventory on server reboot. 

### ISSUE THREAD

**Issue by melekaiah** [AppliedEnergistics/Applied-Energistics-2#1944]
Has anyone experienced this. 
I got to autocraft a whole set of disks, with all the parts, having to be made, a task that can take well over 20 minutes depend on power availability etc. 

it gets closed to finsihed and the server reboots for its daily reboot, 
when you log back in, half the items are gone from the pylon, its progress has stopped, and just sits there. 

this has happend twice to me now, loosing tons of stuff in the process, (not a big deal since im admin)
just wanted to know if its something that you guys can reproduce in the build 8 of the latest round of alphas. or if my mod pack is to blame.

**Comment by mindforger** [comment]
which exact version are you using? i noticed this behaviour in rv2_8 or rv2_9 

but the key factor was using chickenbone's chunkloaders! They break something when force loading the chunk, so we kicked chickenchunks from our server as those chunkloaders are way too OP anyways :P

can you can add some more infos on what modpack you are using and in which way you do chunkloading? is the whole energy setup chunkloaded? and what the heck is a crafting-"pylon"?

**Comment by melekaiah** [comment]
rv-3 alpha 8 is what im using at the moment

and yes i am indeed using chickenchunks, we have a chunk area with 10 chunk radius loaded as our city core, in which we have a central ME-system with a crafting setup. 

below is a picture of my crafting core, the craftying "pylon" is my name for the crafting unit, 2 coprocessors, 1 64k storage 2x4k storage, and 1 crafting dispaly, 
![2015-10-12_13 10 11](https://cloud.githubusercontent.com/assets/2993253/10426669/9dbc133a-70e2-11e5-9343-2b558803b94c.png)

The mod Pack is one ive been building for a while, thats still in testing, called abandoned worlds. as soon as i can get all the obvious bugs fixed im gonna start asking for permissions for all the mods in the pack so i can make it semi public at least. 

i prefer not to remove mods since that seems to screw up the id's left right and center, (is that still the case? i know it was a while ago)

**Comment by XFactHD** [comment]
@mindforger I think he means the crafting CPU. The problem here is that at any time the player leaves the chunk without placing a chunkloader or reloads the world, the chunks unload meaning that the multiblock is invalidated and spills the stored items into the world.

**Comment by melekaiah** [comment]
i havent acutally noticed any SPILLING of items, since ive been online within a minute of server reboot, 
although i suppose if it disables the multiblock and spits out items, those items willb e lost on server reboot, 

however, part of the original crafting cue is still in the crafting cpu (not pylon fine i give in) but just frozen and not functioning. Ill need to do some testing of the behaviour if i removed the chunk loader, (which is kinda iffy, since we have a rather large spread out base with lots of wiring, im not sure what will explode without the chunkloader)

**Comment by XFactHD** [comment]
If you have MFR in your pack, use those chunkloaders, they are working brilliantly with the ME system. Are you using plugins on the server or are you using Aroma's Backup mod?

**Comment by mindforger** [comment]
also Railcraft Ones could work for you, just use either sentinels to spread their field to 1x9 in 9 lines or place them in a 3x3 pattern

**Comment by yueh** [comment]
No idea how to reproduce currently. Your best option would be to provide a minimal setup using a minimum amount of mods (if this is some mod interaction issue)

**Comment by thatsIch** [comment]
Sounds similar to https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/58
