### ISSUE TITLE
Suggestion: Advanced card for Import/Export to match on Item ID vs oredict

### ISSUE THREAD

**Issue by lrwerewolf** [AppliedEnergistics/Applied-Energistics-2#1947]
After some comments in #1946, and some experimentation, I had an idea that avoids the pitfalls yueh identified in that issue, while providing some interesting possibilities.

The first experiment was done with an export bus on a chest.  It was given a fuzzy logic card and provided a raw fish (in the test, item ID 349) as its sole configuration.  As soon as I configured the export bus, the chest filled with raw fish and raw salmon (in the test, ID 349:1) as well as raw calamari (from Pam's HarvestCraft, in the test, item ID 5878).  However, pufferfish (in the test, 349:3) and clownfish (in the test, 349:2) did not get exported to that chest.

The result I was hoping for was all items of ID 349 and no items other to be exported to that chest.

Running the experiment again with two types of carved stone from the Chisel mod, where the filter was Stone Bricks (in the text, 667:11), and the network held 32 of that and 32 of another type of Stone Bricks (667:15), the result was a chest with only the 667:11 variant.

The result I was hoping for was that both stacks of 32 of each type would be exported to the chest.

The suggestion then would be an advanced card, useful in ME Import/Export Bus and ME Storage, that causes the bus to match items specifically by item ID and no other feature or data.

Running the same experiment above, using such a card instead of a fuzzy card, would have produced a chest with raw fish, raw salmon, pufferfish, and clownfish, without the raw calamari, as was the desired result, in the first experiment, and both types of blocks exported to the chest in the second experiment.

While item IDs may vary world-to-world and modpack to modpack, the associations will remain valid (ie: if raw fish and raw salmon were in a new modpack to find themselves under item ID 4410 instead, 4410 would still be raw fish and 4410:1 would still be raw salmon).  This could break horribly if someone loads an existing world created with one set of mods with a different set of mods; but this should break horribly anyways, if it even manages to load in the first place.

Other examples of mods that this would play nice with is Botania, for which there are some IDs where there are many different metadata signifying different flowers, or Thaumcraft which lumps many related items under a single ID (such as the treasure bags and the various colors of tallow candles).  On the vanilla front, it would enable the long sought ability to export potions neatly.

**Comment by yueh** [comment]
#360, #1043
