### ISSUE TITLE
question

### ISSUE THREAD

**Issue by rawrfisher** [AppliedEnergistics/Applied-Energistics-2#1948]
I dont know what the cause is but I am unable to craft the basic items from AE with the modpack i have setup.  If I spawn in the items I can use them like normal tho.
Update: I found a way around the issue useing steves carts crafting modual

**Comment by Be-Cool-Man** [comment]
Which modpack? There are tons of Modpacks out there...

**Comment by mindforger** [comment]
also please define "the basic items from AE" and if the modpack is not public the exact version of AE you are using

**Comment by rawrfisher** [comment]
After trying different things I cannot craft any items from the mod that are crafted in the crafting table
version is appliedenergistics2-rv0-stable-10  and the modpack is one i put together myself

**Comment by thatsIch** [comment]
Try starting with only AE2 and re-add mods until it happens again

**Comment by thatsIch** [comment]
also try updating AE2 first

**Comment by rawrfisher** [comment]
appliedenergistics2-rv0-stable-10 is the latest Rv0 version on the AE-mod.info download page right now

**Comment by thatsIch** [comment]
since rv2 stable is already and rv3 in development, this should not be a problem.

**Comment by rawrfisher** [comment]
switching to the RV2 solved an unrelated issue and somehow the issue mentioned here went away with me just reinstalling the mod XD

**Comment by Blue64** [comment]
Custom Recipes Boolean is causing this issue, it never creates the files when initially enabled.
