### ISSUE TITLE
Issue with Storage Bus

### ISSUE THREAD

**Issue by ranger135xp** [AppliedEnergistics/Applied-Energistics-2#1949]
Hello,
I followed this tutorial idea on automated crystal growth using just AE2 and MC, and it worked within the same world in a test scenario exactly how it's built in the tut here: http://imgur.com/a/NhLB9

I made the same device with subtle differences and it's attached to my friend's AE network via a controller network that passes the main network all over with P2P tunnels like a router.

The problem is that the mini-network that the accelerators are attached will not see the large interface as a storage container. I've tried injecting items directly and they go to the main storage area as expected, and that interface can likewise pull items from it as expected. With or without the ME Controller in the image, it still does not see the storage bus on the interface as a valid storage path. Attaching an ME Chest works as expected. I have priorities set correctly within the mini-network and my storage is not full. I'm really stumped as to why this is exerting this strange behavior.

![2015-10-13_18 54 10](https://cloud.githubusercontent.com/assets/15115164/10470720/5044aa26-71dd-11e5-84fc-da6b2e84eb8b.png)

**Comment by ranger135xp** [comment]
I used a chest to act as a surrogate and used an import bus to pull from the chest. I shouldn't have to do that but it works for now. Also, I noticed if you place an item like red alloy wire from Project:Red under and around ME cables, the cable block-space will take the redstone behavior of the wire. The problem is that it won't allow it to change to the "on" state once it's turned off. Breaking all AE items in that particular block-space will allow it to function again.

**Comment by yueh** [comment]
Either add a blank biometric card with deposit rights to the main network or add a security terminal to this network (placed by whoever ones the other network).

**Comment by ranger135xp** [comment]
I think I see what you're saying. So the mini network needs deposit rights to the main (which does have a security terminal). That is to prevent people from secretly attaching storage buses to another person's interface and either extract items or inject them with garbage. Thank you!!
