### ISSUE TITLE
Cutting Knives lose Durability without use

### ISSUE THREAD

**Issue by ranger135xp** [AppliedEnergistics/Applied-Energistics-2#1950]
I just found this and checked with both variants, certus and nether quartz cutting knives. In any crafting grid, simply place one or both of the knives and make any change to the crafting grid. Add an item or two, move the knife, remove items from the grid. Any knife in the crafting grid (checked with them in inventory as well. The bug only works while it's in the crafting grid) will lose durability without crafting anything. The knife can even get into the negatives according to ArmourStatusHUD. The next time you actually use that knife, it instantly breaks after successfully crafting.
![2015-10-13_22 03 20](https://cloud.githubusercontent.com/assets/15115164/10473170/40f9e702-71f6-11e5-8d74-516e6f23aee5.png)

RV2-Stable10

**Comment by yueh** [comment]
Cannot reproduce it with just AE2.

I would assume it is some other mod causing it. I would recommend that you start with a fresh instance only containing AE2 and slowly add the other mods back until you can reproduce it and name the mod (and probably report it to them also)

**Comment by ranger135xp** [comment]
I found that when I removed DragonAPI and associated mods, the problem still occurred. When I put Reika's mods back in and removed Botania and Baubles, the issue was gone. I'll have to let the author know about it. I tested it with other items that are needed in a crafting grid to make things like the IC2 hammer, cutter, and the Forge saws. It only affects the knives from AE2.

**Comment by ranger135xp** [comment]
The friend I play with posted this over at Botania
https://github.com/Vazkii/Botania/issues/1454
