### ISSUE TITLE
Issues adding to large network

### ISSUE THREAD

**Issue by deathglow** [AppliedEnergistics/Applied-Energistics-2#1951]
I love ae.  I put basically everything on the ae network.  It has gotten pretty large and now when I add new devices they do not sync up to the system.  I have found that if i break the main controllers and reattach them the system will re identify everything and that will allow for the new devices but they will not get picked up unless i do this.  Is this just a limitation of the mod or a true bug?  I am running the resonate rise 3 pack, installed through aelauncher.  it is the current version RR 3.2.7.2-RC which has your version 10 stable in it.  Please let me know if you need any additional info.

**Comment by XFactHD** [comment]
Every time you add a device to the network, the network repeats the pathfinding.

**Comment by mindforger** [comment]
how long did you wait for it to update, did you check that really ALL your devices are updating or maybe you just reordering a design flaw in your network and your channels only can find the new device because you have some sort of loop going?

**Comment by deathglow** [comment]
It is hard to say for sure as I usually hook up something and work on something else while i wait for it to connect but I would say at least 30 mins.  It has been a growing issue and originally would eventually connect but it seems I am past the phase.  I cannot say for sure there is a broken loop or not.  I am using ender conduit so that could be some of the issue.

**Comment by mindforger** [comment]
which version of enderIO ? there was an issue with EIO cables and long range connections but i do not remember it had been discussed on the EIO side anyhow

it's nearly impossible to reproduce this i think

**Comment by deathglow** [comment]
looks like 1.7.10-2.2.8.381 as per jar file

**Comment by deathglow** [comment]
yea i can imagine it would be.  here is my current layout from the network tool.  I dont know if there is much more i can give you.
![current network](https://cloud.githubusercontent.com/assets/15041227/10487975/2a25b266-725c-11e5-857e-eb157a721b8c.png)

**Comment by mindforger** [comment]
yeah well this is the latest stable, everything from there on is ... let's say "new!" but gradually getting better, so this issue may still persist ... but why the hell can't i find the issue anymore ?

**Comment by deathglow** [comment]
its all good.  I love your mod so i am pushing it to the limit since it hooked up to everything.  its probably just to much for the server.

**Comment by yueh** [comment]
This is nowhere near the limit of AE2.
More likely just a limitation of EnderIO or maybe some ExtraCells issue.

Best way is to test it would be without any EnderIO conduits.
