### ISSUE TITLE
Quantum Network Bridge

### ISSUE THREAD

**Issue by DeOriginale69** [AppliedEnergistics/Applied-Energistics-2#1952]
When testing a QNB in creative, creatively spawned and renamed (using a vanilla anvil) quantum entangled singularities would not connect the two quantum rings. This isn't a very large issue since they worked after making the quantum entangled singularities using the ender dust and singularity within a blast radius, but it would be nice to be able to creatively spawn them and link them by naming them the same way.

**Comment by XFactHD** [comment]
#1924
