### ISSUE TITLE
sanguimancy crafting server freeze

### ISSUE THREAD

**Issue by Xander112** [AppliedEnergistics/Applied-Energistics-2#1955]
When calculating the materials needed to craft a tier 16 blood tank the minecraft server freezes entirey and needs to be killed over the task manger

**Comment by yueh** [comment]
This is more or less the worst case possible. Exponential growing recipe and using a container item (the orb).

To prevent issues, dupes and what not we need to calculate each step separately, thus preventing us from using any shortcut to reduce the amount of steps.
Resulting in 3^16 steps (~43 million) for this case.

Not sure if we can really fix anything here.

**Comment by Xander112** [comment]
mabye you can make some special case?

**Comment by yueh** [comment]
Workarounds for a specific mod are really a bad idea.

If then a more generic approach should be considered, like simply blacklist certain items known for offending and not treating them as container items. Which in return then requires for this case that you need to have ~15 million orbs.
As well as every other blood magic recipe will need one orb per single task of a job and not simply one for the whole job,

**Comment by thatsIch** [comment]
Best way imo is if you pre-craft the steps below
