### ISSUE TITLE
ME System Flickering

### ISSUE THREAD

**Issue by Robloz360** [AppliedEnergistics/Applied-Energistics-2#1959]
My ME System has been flickering continuously and its kicking me out of my ME and disabling parts of my ME for like 20 seconds which are connected to P2P Tunnels. By the way its on a server for FTB Infinity and the update is 1.10.1

**Comment by XFactHD** [comment]
How big is your network? Did you already try putting AE energy cells on the network?

**Comment by Robloz360** [comment]
here are 2 images which show my ME System Size and power,

![2015-10-18_20 20 29](https://cloud.githubusercontent.com/assets/15184756/10567550/d713ac0e-75d5-11e5-87fc-23c824bd4e66.png)
![2015-10-18_20 20 35](https://cloud.githubusercontent.com/assets/15184756/10567551/d91eda14-75d5-11e5-8aad-f50edd291e6f.png)

￼
￼

**Comment by Robloz360** [comment]
the mod Thaumic Energistics is also in the modpack

**Comment by XFactHD** [comment]
I am using that mod too and I don't have this problem.

**Comment by majic79** [comment]
Would like to add that I'm having a similar problem. I'm using a 7x7 ring Controller, with two Quantum Network Bridges to link extra sections into the network. The main controller is always chunkloaded, with both network bridges starting in the same chunk. The "Farm" QNB end also always chunkloaded, the second QNB doesn't always have it's other end chunk loaded. Dropping the network down to 1 QNB doesn't alleviate the problem. I only see the issue if I'm using a terminal (crafting/pattern/plain/wifi) when I'm at the remote end of the QNB (have a farm setup in a different biome from my AE controller). When I'm in the same area as the main installation, I don't see a problem. I have P2P networks for power (RF) and to expand capacity through one of the QNB's (farm side) with 2 P2P RF output points from 1 input, and I'm using only one P2P ME output on the other side of my QNB. Server is a private one (4GB VPS) which is not running near to the memory limit, nor is it swapping.

**Comment by yueh** [comment]
#293, #380, etc.
