### ISSUE TITLE
Items disappear/blinks when last item is taken/exported..

### ISSUE THREAD

**Issue by Ajes1337** [AppliedEnergistics/Applied-Energistics-2#1964]
https://youtu.be/pdzhAdjRGqc

using beyond reality modpack, with appliedenergistics2-rv3-alpha-9.jar

**Comment by mindforger** [comment]
"should" already been finxed with alpha-10
see https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1938
But still!!! i added something to my old post @yueh

**Comment by Ajes1337** [comment]
@mindforger where do you find rv3 alpha-10 ? it isnt in https://github.com/AppliedEnergistics/Applied-Energistics-2/releases or the AE site..

**Comment by mindforger** [comment]
oh .. yeah you are right .. how was i confusing that XD 

well okay still, same issue :D or maybe related, botania flowers are derping in a similar way since the first attempt in alpha 8 and the revert in alpha 9, but most of the items are now stable except his example and botania

**Comment by yueh** [comment]
Works fine for me.

Without a way to reproduce it, i have no chance to verify and potentially fix it.

**Comment by mindforger** [comment]
this boggles me, i am not able to reproduce it on our server anymore, nor in SSP ... what the heck? (and yes we did "some" updates to seemingly unrelated mods, but yet we lost extra cells, so i am out until it pops up again, sorry)

**Comment by mindforger** [comment]
it happened again, and this time reproducible and only AE2 rv3 a9 + botania 228
creative
http://puu.sh/kYqQl/cd4318b078.jpg
drop all sorts of botania flowers in it, try to pull out full stacks of them, watch the itemlist go nuts
forge 1492
