### ISSUE TITLE
Quantum Link Bride and Chunk Loading

### ISSUE THREAD

**Issue by Laconicus** [AppliedEnergistics/Applied-Energistics-2#1965]
When I log back on to the server, my Quantum Link Chamber in my Spectre Dimension is powered and showing the right color.  Then when I go to my main base (which is chunkloaded with a Dimensional Anchor set to the Server as owner - just like the one in my Spectre Dimension) the Quantum Link Chamber is not lit up or showing that it is being powered, despite a tesseract feeding an energy acceptor in the right spot.  The Wireless Access Point does not light up either.  The only way it works is if I break/wrench the Access Point and re-place it, or if I wrench/break one of the Chamber blocks and re-place it to form the Bridge again.  Do you know why it will not stay powered even though both sides are chunk loaded and have plenty of power?  They work fine once I break one of the parts, and the one connected to the core ME System in the Spectre Dimension is always powered. 

This doesn't happen every time I leave my Spectre Dimension and go back and forth, it just seems to happen after I have been logged out for some time.  Its possible it only occurs on restarts, but it should still work.

**Comment by mindforger** [comment]
Try with another type of Chunkloader,
and also, provide the Quantum Link some Power Cells, having plenty of input does not help when you got a network of a decent size. It can draw more power in a single tick than you can provide over your acceptor easily, the power cells act as buffer for those spikes and are often underestimate or forgotten.

**Comment by Laconicus** [comment]
Buffering it with more power appears to have worked.  Thanks much.

**Comment by mindforger** [comment]
nice, you may close this issue then :)
