### ISSUE TITLE
Some items in hand can not right click a ME Crafting Terminal

### ISSUE THREAD

**Issue by Hypocrisy** [AppliedEnergistics/Applied-Energistics-2#1966]
I haven't gone through extensive testing but certain tools at least will not be able to access a ME Crafting Terminal by right clicking. 

Some Blue Power tools, Extra Utilities builders wand. Nothing happens when right clicking.

**Comment by yueh** [comment]
Not sure about the other tools, but at least the builder's wand overrides the normal right click, even preventing you from opening a vanilla chest.

So not really an AE2 issue, but simply how these tools work.

**Comment by Hypocrisy** [comment]
Hi, you are correct about the Builder's Wand, that was an oversight by me. 

Since then I have done some further testing and found that it is shovels causing the issue. I'm not aware of any right click functionality from shovels nor any mods that give them one. I have tried many various shovels and so far the only one that has worked was the Draconic Shovel from Draconic Evolution which does have a right click function for switching modes.
