### ISSUE TITLE
Fast redstone timer on export bus causes "freeze"

### ISSUE THREAD

**Issue by poiuyqwert** [AppliedEnergistics/Applied-Energistics-2#1967]
Modpack: FTB Obscurity 1.1.16_Beta (Singleplayer)
Forge: 10.13.4.1448
AE: rv2-stable-10

I inadvertently connected a very fast redstone timer (this design: http://minecraft.gamepedia.com/File:Repeater_loop_1-clock.png) to an export bus with a redstone card in it. This caused the world to "freeze". It was kind of as if I was on a multiplayer server and had lagged out. I could visually place blocks and break blocks, but couldn't interact with chests, machines, etc. When i looked at the Used Memory with F3, it was constantly climbing to a high percentage and then dropping back low very quickly.

Since it wasn't just an outright crash there was no crash log, and I couldn't find any info in any logs to indicate what might be happening or causing it. This is obviously problematic for people that run into this issue as there is no way to find any help online, and problematic for you devs because there are no bug reports. It took me a few hours to figure it out why my game was broken, but I have quite a bit of bug reproducing/debugging experience. An average minecraft player would probably have to hope they had a recent backup, and that they didn't run into the issue again.

Anyway, thanks for such an awesome mod! Hope this helps!

**Comment by yueh** [comment]
Works fine for me based on your description.
