### ISSUE TITLE
Some GUI are showing a not working 3x3 upgrade grid

### ISSUE THREAD

**Issue by kim-yannick** [AppliedEnergistics/Applied-Energistics-2#1968]
GUIs like the Inscriber or ME Interfaces are showing a 3x3 upgrade grid for me. If I put acceleration cards in, they can stack in these slots but don't have any effects. My friend can't even see this slots, but the items are not being lost, so the slots seem to exist on the server.

![2015-10-24_11 12 12](https://cloud.githubusercontent.com/assets/10467401/10709924/1e01a15c-7a40-11e5-8c47-d88a3073212b.png)
![2015-10-24_11 14 09](https://cloud.githubusercontent.com/assets/10467401/10709928/62ca99b0-7a40-11e5-97b9-09b15870c4a6.png)

**Comment by yueh** [comment]
[Network Tool](http://ae-mod.info/Network-Tool/)
