### ISSUE TITLE
Crafting terminal bug?

### ISSUE THREAD

**Issue by Zinkeyy** [AppliedEnergistics/Applied-Energistics-2#1969]
Hi, im kinda new to ae2, i just made a crafting terminal with 5 disks, four 4k and one 1k.
Im getting bothered about something that i would like to call a bug...
After each time i exit the Crafting terminal, i can't use it again, i have to take out the disks and then put them in again.

I don't know if this is a part of the mod, but it is really annoying and i wondered if i could fix it somehow?

Im using FTB Infinity.

**Comment by mindforger** [comment]
which version of AE2 ? sounds like the "drive not updating" issue, paired with a "forogt to add an energy cell" while crafting a larger batch of items

**Comment by Zinkeyy** [comment]
Well, i checked out the ftb wiki and it says that the version that im using is "rv2.stable build 1" i dont know if says alot but yeah... i have the newest version feed the beast client.

Maybe i should mention that im using a stirling engine from Ender IO to power the ME controller, maybe that is the issue?

Thanks for answering! :)

**Comment by mindforger** [comment]
yeah, like i said, drop an energy cell on your wire (it does not consume any channel) and your problem will probably vanish in thin air

**Comment by TheJulianJES** [comment]
No, #1611 has been fixed in rv2 stable build 10.
Please try updating: http://ae-mod.info/Downloads/ You should also supply more power to your network.

**Comment by Zinkeyy** [comment]
Thanks guys! i will test both! :)

**Comment by Zinkeyy** [comment]
So i was too stupid to look at the ME controller and see that it was running out of power all the time, thanks guys, it helped a ton! :D
