### ISSUE TITLE
Rendering of a press in inscriber leave the GL engine in an improper state

### ISSUE THREAD

**Issue by leagris** [AppliedEnergistics/Applied-Energistics-2#1970]
When displaying a press, the inscriber leave the GL engine in an improper state causing ambient occlusion to not render at some angles.

Look at toolrack render differences (top-right of pictures)
Without press in inscriber:
![2015-10-25_23 48 58](https://cloud.githubusercontent.com/assets/1111474/10718450/12c0785c-7b73-11e5-92d6-a3e56ce38f30.png)
With press in inscriber:
![2015-10-25_23 49 23](https://cloud.githubusercontent.com/assets/1111474/10718451/12c1a1b4-7b73-11e5-9363-96ce3f85c936.png)

See also: 
https://github.com/ForestryMC/ForestryMC/issues/919

**Comment by yueh** [comment]
Anything printed to the log? For example a GL Stackoverflow?

The rendering is actually stupidly over conservative, especially once it needs to render an item (like the press). Like the renderer tries to protect itself from any buggy item render and simultaneously the item renderer protects itself from any buggy caller (which actually is guaranteed AE2), thus really useless. But this easily can result in some stackoverflows etc. Too conservative/defensive is just as bad as too less... Finding an equilibrium is not that easy.

Out of curiositiy, could you try the PR build based on #1880?
It removes most of the extreme defensive stuff and in general is a bit more selective about what state it protects (which should also result in a better performance in some cases, like ridiculuous amounts of skystone chests.
Build against rv3, but it seems you are already using it. But as usually make backups.
Nevertheless it should be mostly finished, just need to test it a bit more (or get some feedback)

**Comment by thatsIch** [comment]
While working on this I noticed a few other bugs, this is fixed internally

**Comment by yueh** [comment]
Based on my PR or the current master? I had a couple of small rendering issues, mostly lighting based on, which are fixed with the PR. Just to prevent any duplicate work.

**Comment by thatsIch** [comment]
Always on master, also if it is on your PR you would see your commit in it
