### ISSUE TITLE
Terminal Bug

### ISSUE THREAD

**Issue by Wolfseverest93** [AppliedEnergistics/Applied-Energistics-2#1972]
So, this for some reason does not generate anything in the console, but for some reason out of the blue, when i go to open my crafting terminal, the entire screen turns a pale blue, and it doesn't just do this for that set time, it stays until i close minecraft, i even managed to go back to the main menu (i know this because of the song it played) and it was still that creepy bugged out pale blue screen, kind of like the color of average plastic steel plates (a really smokey grey blue). As far as I know, taking a screenshot would be pointless because it's literally just going to be as described. And I unfortunately don't have a laptop capable of recording while in game. If I could guess, I would assume it has to do with the fact that I had another mod installed at first, and some of it's items ended up in the ae2 system, and since i removed that mod, it could be at least partially causing this. Any input is greatly welcome, I felt I should let you know this is all. I hope there's some way it could be fixed without me having to remove the drives... It took me a really long time to craft all of that stuff, I hate creative mode, and I don't want to lose all the stuff that has 3 of my 64k units filled to the brim.

**Comment by XFactHD** [comment]
Do you have Optifine or Fastcraft? Is the driver of your graphics card up-to-date?

**Comment by Wolfseverest93** [comment]
I actually have both and know it's not them because it hasn't replicated in any of my offline test worlds. My graphics card is always up to date being as I attempt to update my drivers once a week, just in case they get another update. Something tells me it really has to do with the whole me removing a mod that some of the items were in that particular console of.

**Comment by XFactHD** [comment]
That's really weird.

**Comment by Wolfseverest93** [comment]
Oh well, no sense crying over spilled milk. I hope they'll fix this issue somehow if they can replicate it. The mod I had before was inventory pets, I removed it after finding out a player on the server received a command block from an Illuminati Pet. Also made sure to check the entire server for any traces of minecarts with command blocks and command blocks, just in case, including inventories and all chests (via plugins thank goodness) and found that 3 others had managed to be spawned in by the pet. Which makes that pet way too op, especially since if they know what they're doing, players can abuse command blocks like never before. I can't have that. I don't know if it's because I at one point had that mod in particular or if this would replicate via removing any mod while having items from it in the ae2 network.

**Comment by mindforger** [comment]
>I actually have both and know it's not them because it hasn't replicated in any of my offline test worlds

you have BOTH installed? Optifine and Fastcraft? How can you know it's not them just because you played an offline world(palying offline and online has nothing to do with rendering)? 

try removing them first (client side) and come back if it still happens!

currently there are 4 mods afaik that have tiny issues in rendering and openGL-state handling that could lead to undefined behaviour, AE does yet not count to them, but as stated in another issue here, the render code is somewhat very defensive and may amplify the bad render code behaviour!

Also you are lacking crucial information: Which Version of AE2 are you using?

**Comment by Wolfseverest93** [comment]
Still happened. I don't just test with or without, I test all possible routes. It's precisely as I assumed, however. It happened because I removed a mod even though some of the items from said mod were still in one of my 64k storage units. It sucked to do but I flushed my ME network and threw out all of the units that had even 1 item in them. That fixed it.

It's not that crucial to be lacking version info when I'm using the latest release available on curse. I don't make bug reports about older ones.

**Comment by mindforger** [comment]
>I don't just test with or without, I test all possible routes

what exactly does this mean again, you threw them out and tested it again, did you? yes or no?
nobody can look inside your brain to understand what you have tested already ... you need to tell it

>It's not that crucial to be lacking version info when I'm using the latest release available on curse. I don't make bug reports about older ones.

and the whole world does like you ... pretty confident opinion ... it is crucial as the "latest" version I f.e. am running is rv3 alpha9 not like the one on curse rv2 stable10 and many other people lack the knowledge to know their modpack isn't up to date, just make an good example for others and file all informations as it helps a lot

**Comment by Wolfseverest93** [comment]
That's what I said, is it not? And in both cases, the only time it replicated was when I put items from a mod into the terminal, closed the game, removed the mod the items were from, reloaded the game, and tried to open that terminal.

Also, my bad, I'll keep in mind to post the revision tag from now on. I can say that I don't much like using alpha or beta versions of mods, especially in mod packs *shiver.gif* they tend to be more buggy than older official releases.

Forgive me if my manner of words are lacking the more common touch, I'm an above average shut in. So communication tends to be subtle.

**Comment by yueh** [comment]
What you describe sounds like a broken item renderer of another mod.

If it is true that you removed some other mod, then these items would also vanish from the cells just like normal chests. Maybe the metadata is still incorrect until some existing items in them are modified (like stored types/bytes).

But as this persists after you removed it (if I understand it correctly), it sounds more like another mod is overtaking these items or the mod itself replaced some other mods items and now leaves them in an invalid state.

I would highly recommend making a backup of the world and slowly remove the other mods until you are either left with AE2 alone (and it still happens) or you find another mod which causes it (and report to them).

**Comment by Wolfseverest93** [comment]
That was the plan. I'll be doing that over the weekend in one of my offline test worlds.

**Comment by Wolfseverest93** [comment]
It reflected all the way down to just having ae2 in the world. For some reason it isn't generating anything in the server, the console, or the log. It's just simply turning the whole screen to that same greyish blue coloration until I closed the client, restarted, and then replaced the storage unit, only then it stopped reflecting.

**Comment by thatsIch** [comment]
Can you post the log please, maybe we will find something

**Comment by Wolfseverest93** [comment]
The log only mentions the general starting up and startup finished agenda, but I'll go at it again and post the log regardless.
