### ISSUE TITLE
ME System looses all Channels for a tick

### ISSUE THREAD

**Issue by fastplayer95** [AppliedEnergistics/Applied-Energistics-2#1976]
Forge: 10.13.4.1448
AE2: rv2-stable-10
(FTB Infinity 1.11.2)

I noticed that my ME-System looses all Channels for a tick and Terminal GUIs close themselves.
I can replicate it nearly every 5 seconds.
Server TPS are fine.
ME System reaches over 5 Chunks in a Plus shape. Terminal as well as Controller are in the same Chunk and the Controller is completely in one chunk.

I have no crashlog since neither client nor server crashes.
I can and will provide more information if needed.

**Comment by wlhlm** [comment]
Make sure you provide the network with enough power. Adding a couple of Energy Cells can help.

**Comment by yueh** [comment]
Check power and/or chunkloading.

Also there are a couple of similar issues, like #1969.

**Comment by fastplayer95** [comment]
I'm sorry but the linked issue is not my problem.

Power is not a problem.
I have 16 Dense Energy Cells and full T7 Draconic Evolution Power Cell.
About chunkloading: all used Chunks are loaded by Chicken Chunks.

I have no problem with reopening the Terminal.
This works just fine.
The ME-System really just losses all Channels and then reconnects everything.
It's still usable and playable just a bit annoying

**Comment by mindforger** [comment]
check again with other chunkloaders, chinkckenchunks are well known to cause random update issues

**Comment by XFactHD** [comment]
@fastplayer95 if you have MineFactory Reloaded in your pack, try using their chunkloader.
