### ISSUE TITLE
Crafting CPU can crash after disabling the result of a recipe

### ISSUE THREAD

**Issue by thatsIch** [AppliedEnergistics/Applied-Energistics-2#1977]
This will likely happen if you are currently crafting something which you are disabling or is being removed from the game. While this is crafting, the result is assumed still being in the game, but could not be loaded up for obvious reasons.

Report: 
http://openeye.openmods.info/crashes/b9fd1cc3d2345d05814bac57e4c75cbb

**Comment by Blue64** [comment]
I also notice a similar issue with 2 Crafting CPUs trying to use the same Molecular Assemblers, if you set up 2 CPUs, 5 assemblers, a Interface Block, and 2 patterns of something (I was compressing cobble), with applicable storage of course, tell CPU#1 to do a large job, then tell CPU#2 to do a small-medium job, #1 will be forced to eventually give up use of the Assemblers to #2 and it SHOULD return to full output once #2 is done, but it doesn't, I had to reset the job (2 Septuple Compressed Cobblestone, from Cobblestone, it was a stress test) to re-enable full use of the assemblers. I suspect the same issue is the cause, likely related to the reason for adding the "Simulation" screen for auto crafting.

**Comment by GuptaChinmay234** [comment]
Will this ever be fixed ?
