### ISSUE TITLE
Crafting kicking players

### ISSUE THREAD

**Issue by chrisbecke** [AppliedEnergistics/Applied-Energistics-2#1980]
So, I'm logged onto a server running direwolf20 1.8 - with Applied Energistics rv2-stable-10 - so not too behind. I have a small ME system, about 4 drives with 4k disks, and some auto-crafting things.

I notice, while I am crafting, that other players are disconnecting and reconnecting constantly. To my consternation, each time I perform a craft.

The craft? I had several stacks of 5k-10k 'tiny dust piles' (IC2 mats) that I am combining 9 at a time, using shift-click, to create stacks of 64 dust. Not using any of the auto crafting facilities - just the crafting terminal.

**Comment by yueh** [comment]
#127
