### ISSUE TITLE
Ability to queue up future crafting requests when resources are not available

### ISSUE THREAD

**Issue by Builderb0y** [AppliedEnergistics/Applied-Energistics-2#1981]
When requesting an item that requires more resources than are currently available, it will not currently allow you to start the request at all. I think this should be changed to the following: If resources are not available, it will still allow you to start the recipe, but will either pause the recipe until all resources ARE available, or craft what it can until it runs out of resources, and then wait for new resources to enter the system.

From the crafting simulation GUI, the "Start" button would simply change to a "Queue" button when resources are missing. When clicked, it would transfer all available resources to the crafting CPU, and then continue transferring them whenever they enter the system.

The main reason this would be useful is if you have semi-automated production of a certain resource, and production stops when you have, say, 10k of it. If you require 20k to craft something specific, queueing up the request would allow it to use the 10k it already has, and then continue crafting as more becomes available.

Having this option would be FAR more convenient than changing the threshold to 20k, waiting for it to finish everything, and then changing it back. It would also be more convenient than making another 10k yourself. But the biggest advantage would be if your system auto-deletes that resource if you have more than 10k of it (take cobblestone for an example here). In that case, it would be impossible to autocraft anything that requires more than 10k cobblestone unless you're willing to craft parts of it manually, which would defeat the purpose of being able to autocraft it to begin with.

**Comment by siasur** [comment]
While this would be a nice feature, what prevents you from autocrafting small parts of you final item(s) and when they are finished and available start the crafting of you final item(s).

**Comment by Builderb0y** [comment]
Again, we can take cobblestone for an example here, and the item we're requesting is, say, an octuple compressed cobblestone. If you're only storing up to 10k normal cobblestone, then you can only craft up to the quadruple compressed version, and it takes 6,561 of those in order to make the octuple. I don't think ANYONE would want to make 6 thousand requests in order to craft something.

Granted, there are plenty of better ways to make octuple compressed cobblestone than using AE's crafting system, but I think this example gets the idea across.

**Comment by yueh** [comment]
I do not see any particular reason to add it. It would basically mean adding the old AE1 behaviour back and this was removed for a couple of reasons, like it could easily stall the whole crafting job.

With AE2 it would be even worse as a single export bus or interface can easily block 9 crafting cpus forever.

Also AE2 can actually do it already, but a very selective manner which operates on a single item.
So especially useful for things like cobblegens or any other "infinite" item generator.
You just need to plan your network accordingly.

**Comment by Builderb0y** [comment]
The difference between this system and the AE1 system is that it wouldn't use storage drives as crafting buffers; items would still be stored in the crafting CPUs. As for the busses, I only intended for this feature to be available to the terminals, as busses will, more often than not, export items constantly. Having them be able to queue up requests would not make them any faster at doing this, so it would be unnecessary there.

Lastly, cobblestone was only one example. In my actual survival world, I wanted it so that I could request around 500ish turbine housing blocks at a time (this was enough to build 4 turbine multiblocks). It needed around 25k steel ingots to do so. Steel production was automated up to 50k ingots, but I had recently used up more than half of it for turbine blades (again, enough for the same 4 turbines), so it was still working on filling my system back up. I simply wanted to request ALL of the turbine-related blocks at the same time, and not have to remember what I have and haven't requested yet.

**Comment by yueh** [comment]
After due consideration I still to not see it adding anything new. It would simply duplicate existing functionality in a more limited way as well as unnecessarily introduce more complexity to an already complex system.

I must admit, that it might not be the best approach to cover every single item. But it is mostly ideal for base materials like cobble, ingots or anything else needed in mass quantities. It does even scale way better/cheaper in terms of throughput compared to normal autocrafting as long as your machines can keep up with it.
