### ISSUE TITLE
Energy Cells lose Power

### ISSUE THREAD

**Issue by bombdetenation** [AppliedEnergistics/Applied-Energistics-2#1982]
I seem to be having a problem with the Energy cells. I put them in the charger, and they hold a charge in inventory, but if i place the energy block while charged, or try to charge directly from the vibration chamber, it won't retain a charge. Any ideas?

**Comment by yueh** [comment]
Works fine for with just a cell and vibration chamber.

Keep in mind that a vibration chamber only produces around 10 AE/t, which can easily be exceeded with just a couple of drives, terminals, used cables etc.
