### ISSUE TITLE
AE2 + Compact machine : Interface pattern list not saved after server reboot

### ISSUE THREAD

**Issue by Greu** [AppliedEnergistics/Applied-Energistics-2#1983]
Hi,

How to reproduce
1) Create a compact machine (CM) A
2) Setup a simple AE Network in CM A (controller + ME Drive + interface terminal)
3) Create a compact machine B and connect it to the network in CM A
4) In CM B setup some ME interfaces + molecular assembler
5) Go back in CM A and check the interface terminal, you'll see your new interfaces
6) Create a new pattern and add it to the molecular assembler's interfaces via the interface terminal
7) Restart the server
8) The item pattern in the molecular assembler's interfaces disappear

**Comment by yueh** [comment]
Not limited to compact machines, but potentially any network spawning multiple dimensions.
