### ISSUE TITLE
Quantum Link Bridge connection and Multiblock structures in spatial storage cells

### ISSUE THREAD

**Issue by Malzi71** [AppliedEnergistics/Applied-Energistics-2#1984]
Hey,
I have two problems
The first one is a Quantum Link Bridge between the normal world and a spatial storage cell.
The 2nd part of the system in the storage cell does work, but the connections between the two bridges stop working if I save and reload the spatial storage cell and I have to link them again. I have 1 chunk loader in my base and 1 in the spatial storage cell and capacitor banks near the 2 bridges to power them.

My second problem is that I can't save multiblock structures like capacitor banks from ender io in the storage cells. They will just stay if I activate the spatial io port and they will also stay if I place them in the cell dimension, leave with a linking book and load the cell again.

Sorry for the bad grammar, it's very late here and English isn't my native language :/

**Comment by mindforger** [comment]
which versionc of AE2 + add an (dense) energy cell ... a capacitor alone is sometimes not enough + don't use chicken chunks chunkloader

**Comment by yueh** [comment]
1)
We do not really guarantee any behaviour regarding chunkloading with the spatial dimension. It might simply be the case that the used chunkloaders do not work after being moved without any player interaction.
The best option is to inform the mod author about it and for example create a feature request to use the AE2 api regarding movable tile entites. This would ensure that the chunk loaders are informed after being moved and can request an new chunkloading ticket as well as release the old one to leave no orphaned chunks around.

2)
This is purely and EnderIO issue as they do not whitelist their tile entites to be movable.
Contrary to other mods which always move tile entities around, we only move whitelisted one. There are way to many ones that do not like being moved and will result in issues ranging from not working to corrupting your whole world.
