### ISSUE TITLE
Storage Buses should passively push items

### ISSUE THREAD

**Issue by SReject** [AppliedEnergistics/Applied-Energistics-2#1988]
I'd like to see storage buses passively push items into an inventory similar to an export bus. To explain further the request:

ME Storage Bus on a chest, partitioned to store cobble, with a higher-than-default priority.
Chest fills up, resulting in cobble being stored on an ME Drive in a bay with default priority.
Space is made available in chest
Cobble stone on ME Drive does not (currently) get pushed into the chest

I'd like to see a change where if there is space available in the inventory the storage bus is attached to, the cobblestone is pulled from the ME drive and placed into said inventory, respecting priorities.

**Comment by mindforger** [comment]
let's call it defrag ;D
but sure this will bring down the system power in no time XD
so it should only be triggerable once in a while

**Comment by SReject** [comment]
Personally, I'd perfer to see it added as a storage-bus specific card that respects priority. That way its up to the user if they desire the behavior or not

**Comment by mindforger** [comment]
item-sink card

**Comment by yueh** [comment]
#460, #598, #1752

**Comment by mindforger** [comment]
that was kind of abrupt ... can you please give some insight @yueh 
if i would add an export bus to the same storage block the storage bus is connected to, would it cycle the items or could this be an possible solution?

**Comment by bookerthegeek** [comment]
I thought there was a block that can move items off of the drives back into the network? Could you not just once in a while move your drives through the I.O. block and that would accomplish the same thing?

**Comment by thatsIch** [comment]
Exactly, defragmentation can be done via some tweaks to your storage drives

**Comment by mindforger** [comment]
imagine a room full of harddrives .. not so uncommon as you would think ... doing this by hand is awefull on an extreme level like the build itself .. again i'd like to have some insight if this litterally "workaround" could possibly work, is the storage bus and the export bus aware of interfering with the same block in any way ?

**Comment by thatsIch** [comment]
It will have no special interactions if placed on the same inventory.

**Comment by wlhlm** [comment]
![2015-11-03_11 40 52](https://cloud.githubusercontent.com/assets/1928113/10953518/c51f8704-8348-11e5-8ca6-e63efa932671.png)

This setup works similar to how @SReject described it, although not as elegant as with using a special card. 

 - Storage Bus partitioned for Cobblestone; set to only extract + Export bus.

**Comment by siasur** [comment]
An idea for the defragmenting any system without the need to move any cell from somewhere (a drive) to somewehere (a I/O port)

You could build a system which is able to remove and add the storage cells from the me network.
It'll move all cells out of the system (if possible take any empty disk an insert it back to the system) and then route every other cell to the I/O port. When the cell is emtpy it'll be moved back into your me system.

All you have to do is:
- beeing creative
- build such a system
- push a button to defrag
