### ISSUE TITLE
Spatial storage proposal

### ISSUE THREAD

**Issue by gixbit** [AppliedEnergistics/Applied-Energistics-2#1989]
So. One of the things i like to do with these mod packs is segregate my gear so my fps is high and my organization is sufficient to my liking. I use teleporters to get into the cell but. How about some enhancements. Maybe instead of making cells void looking, how about making the black walls like a blue grey with purple colors me style circuitry looking design. Maybe also make a storage drive specifically for spatial storage cells where when you put it into the drive, the walls are accessable and if you attach something to the wall it takes a channel from the controller following the same rules only the storage itself uses no channels. 

Maybe some other additions would make it more interesting too.

Reasoning behind this is of course we store storage cells. Why not spatial but in a different way.

 Of course i dont think this should be hard but maybe it is the concept would be interesting. If you can contain an area to contain functions of an me system and literally program the inside itll add an extra level of depth to an me system. So you can move spatial storage cells between systems. So instead of providing tons of gear on each system this might encourage the construction of me systems from the insides of cells and you want to quickly setup a pulverizer line. Instead you can just attach a spatial storage device and it can automatically function the way you programmed it once its connected. And maybe force load chunks in these drives too. Maybe also cost big power. With this you could go over to a friends house and literally bring your pulverizers with you and attach it to their system then take it back similar to how you could do it now only with quantum gates this doesnt provide the modular ability im referring to. Except if you exchange singularities. 

So maybe this is stupid but it might be a good enhancement

**Comment by Blue64** [comment]
This is possible already via cross-mod interactions between AE2 & Compact Machines, which also allows Entangled Machines, and Nesting Machines, also has configurable Chunk Loading (player only, only while it's in a loaded chunk, or always).

The drawback is that the Compact Machines don't require Power to do this, so it's literally possible to nest an entire ME network down to the size of a single block, without repercussions. Perhaps you can track down their GitHub and ask for configurable power consumption, as it already can store/transfer power, this should be almost no problem for them, and they support way more than just AE2.

Alternatively, isn't this idea mostly possible via Spacial Storage? I've yet to test the Spatial features, but it sounds perfect for transporting large groups of blocks.

**Comment by gixbit** [comment]
Well, the idea was to line the walls of the cell with the ability to connect to the controller through the wire. Now, there's a lot of stuff about that that causes problems like needing that chunk to be loaded etc. so it might actually be a horrible idea anyway. But yes, it is possible with spacial storage right now. You can put a system inside of a spatial storage cell, and connect it by quantum gate,  the only issue with some of my systems inside these cells is the fact that I have 3 quantum gates for one of them, so trying to make this modular is hard. It's still great you can put stuff inside the cells. Its thanks to that i was able to find and solve a lag issue that -was not related to ae2, probably-.

**Comment by Blue64** [comment]
Your system sounds like it needs Compact Machines lol the Nether Star room (configurable items By The Way) is 13×13×13, and the current can be transferred from inside to outside. I plan to make one pure Dense Energy Cells xD my generators could get stolen, and I'd still be able to craft an Octuple Compressed Cobblestone from Ex Nihilo Stones (4 makes 1 cobble) without even worrying lol

**Comment by gixbit** [comment]
Well, I've got like 3 or 4 rooms. One of them has controller and gates in it. And the controller is labeled with signs for now which I plan to change for later. And each tunnel is labeled. Then another controller which slides through the middle of the 7x7x3 controller carries the channels through those gates. This way I can just put down stuff and connect it with gates using 8 tunnels per gate.

Thats the first, the second room is just processing Crystals and fluix. But, in the ceiling I put drives up in there that contain the storage. I put it there for convenience.

The third room has 4 massive assembler cubes in it. 5x5 cubes, Which caries something like 29 interfaces and I can't remember how many assemblers, but it's a lot. It's only 1 wire too that goes straight into it. Then above those there's 6 CPUs, but, I don't have the other 6 made yet cause I'm lazy.

The last room has sets of machines. There's I think, maybe 190+ machines connected? Each with their own patterns etc. and there is between 192 and 256 of those. Because there's 1 gate completely used which is 8 * 32 channels and only 80-90% of those entirely configured and theres 1 more gate in there not used yet. Except the room with the crystals, they're all 39x39x39 rooms. 39x39x39 is pretty good for doing symmetrical stuff.

So yeah, I say the spatial stuff is great because it's outside of the main world, it gives you extra security on your stuff, and if theres an issue with something, it's pretty easy to find, minus the power costs. I think my system is up to 24kRF/t? Which is probably not a lot, or maybe it is. Thats what mine uses.

**Comment by gixbit** [comment]
I did find a bug though, When you wrench up assemblers, it changes their metadata, and when you put them back down they're not quite the same. AND apparently the channels travel through those differently, so I had this weird issue where, I had 3 of those 5x5 assembler/interface cubes set up the same way, then, the 4th one was being weird, only 28 of the 29 interfaces would light up. After completely destroying them and replacing everything with non-wrenched interfaces it worked correctly. The other cubes have interface/pattern terminals on the bottom which is directly connected to the assembler underneath the cube and whatever was happening wasn't distributing the channels the same as the others which ran 31 channels properly plus a wire on the bottom of an assembler connecting a pattern and interface terminal.

**Comment by Blue64** [comment]
In my testing world, I have 2 Dense Cables in 1 13×13×13 Compact Machine Cube (no P2P because it's transferring power and items and I wanted it to look nice) maxed out with 4 towers of  Interface Blocks (4 up & 4 down per tower), giving me access to 4 Assemblers per Interface, 5 on the end. I originally planned for 4 maxed Dense Cables, but I realized that the channels are used even if the Assemblers are touching, which is nice, but it forces me to rework my entire layout, and I don't want to chance glitching an Assembler to access the Interface, so I'll stick with Direct connect, and just ponder different layouts … if I move it over I can squeeze a 3rd Dense Cable in … yeah, I'll do that. Should be more than enough juice going through it considering I fit around 1,400 Dense Energy Cells in 1 cube lol the best part is it all fits in my Spectral Dimension (Random Things mod), so even if it was multi player, and someone wanted to destroy it, they'd need to find an Entangled Cube elsewhere to get in,  all very low lag.

**Comment by yueh** [comment]
I currently do not see any reason for this.
As you said yourself, you can already do it by exchanging the entangled singularity.
(Also it really makes no sense based on the "lore" behind spatial dimensions to have the walls act as cables.)

If you want an easy solution for it, there are already a couple of other mods providing something similar.
