### ISSUE TITLE
IMEMonitor causing massive update cascades

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#1990]
The current implementation for `IMEMonitor` is causing way to many updates for a single changed itemstack.

Mostly due to chained networks each calculating their own difference based on the throughput and not the actuall changed itemstack and propagating it to each listeners.

The amout of updates for a single stack are the following, starting with 2 up to 12 chained ones: `2, 3, 4, 6, 9, 13, 18, 24, 31, 39, 48`. I do not really want to consider longer chains...
Each time it invalidates the inventory cache and if anything during the propagation is accessing this inventory, it will be fully rebuild.

This seriously needs to be fixed, but I am currently not certain, if it is possible without an API break.
The best approach would be to change the monitoring from an external one (`IMEMonitor` detecting what is injected/extracted to the network for every section of the chain) to only creating updates on the lowest level.
This means any inventory like cells should be responsible for notifying any listener about the actual change and then only propagated it once up the chain.
Maybe it is possible to keep the current `IMEMonitor` implementation functional by wrapping any new behaviour.

**Comment by yueh** [comment]
The main issue is acutally [NetworkMonitor.java#L116](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/c83946420eec8edc25cf05fce1192442b06a76cf/src/main/java/appeng/me/cache/NetworkMonitor.java#L116), which will rebuild the full inventory with every single change and for every update.

`L132` could actually be changed to `this.findPrecise()`, which will forward that call to the internal handler (which would also populate the cached list), but this does not require a rebuild each time.

The needed change to `IStackWatcherHost#onStackChange()` would potentially break the API, but as far is I can tell, nobody actually uses the changed itemlist. Thus it should be easy to replace it with an empty collection or just an `ItemList` of just the changed items.
For the current use case the passed list would be even the identical one to shared one for the whole network that particular `GridHost` would be a part.

Sampling my test setup changes the used cpu time from about 1/4 to 1/3 of the overall server thread time to just enough to be detected by the sampler.

**Comment by yueh** [comment]
@ruifung, @Nividica as far as I know your mods are most likely the ones being affected by any change for this issue. But depending on the approach maybe not at all or just a minor change.

In case you do not have any idea about the issue, I will summarize it shortly.
Currently every change to the network (like inserting/extracting a single itemstack of 1), will reset the cache for a single network. This would be mostly fine, if not every existing network would also notify their neighbors (via storagebuses/interfaces) about the exact same change again and reset it again.
So the goal is to reduce the amount of updates to exactly one per change, so it will no longer reset the cache as much as now. Further if the updates are actually correct, we could trust them and apply the diff directly to a cache instead of invalidating it completely to further improve the performance.

I am currently not really confident about which approach would be the best as most have some downsides.

The cleanest approach would be to handle modifications as low as possible. In this case this means that cells would send a notification only if they actually change.
Issue with this approach is that they do not to which grid they belong and thus cannot directly the update.

To solve this every tile entity, which is making cells/inventories available to their grid, needs to handle these updates and act as observer for every of its cell and then propagate every update to its grid.
So any mod providing their own tile entity/part like the EC2 drive fixtures needs to handle this now correctly as well as their cell implementations.
Both are something we cannot really enforce as long as we do not provide (and enforce) a default implementation for these cases. It would be purely be based on something fullfilling the contract inside the JavaDocs.
Thus a bit risky as not all addon devs will read read them completely and it would affect a higher number of interfaces in terms of their methods and the contract for existing ones.

A less complicated approach would be to monitor and post updates on the Drive/Chest level. Both are already wrapping the `IMEInventoryHandler` provided by `ICellProvider.getCellArray()`.
It is still reasonable low to be mostly safe to ensure that the difference between the return value and arguments for `IMEInventory#injectItems()` and `IMEInventory#extractItems()` is the actual difference and can thus be posted to the network. The only exception causing this approach to fail would be, if some addon dev has the idea of adding cells with shared contents, similar to enderchests or bspace barrels.
The downside is that it is not longer idiot-proof like the current implementation, if someone adds their own drives and does not post these notifications correctly, it will mess up stuff. It will not start allowing to dupe as actual modifications are handled differently, but monitors or terminals might not report the correct amount of stored items.

**Comment by yueh** [comment]
Also pinging @DrummerMC

**Comment by yueh** [comment]
See #2032 for a potential fix. Currently no API break necessary, but a slight chance that `MEMonitorHandler` provided by the API needs an internal refactoring.

**Comment by thatsIch** [comment]
Resolved?

**Comment by yueh** [comment]
No. 

It is pretty much unfixable without completely breaking the API and changing every inventory method to return a tuple with stored and destroyed items. Because we currently cannot distinguish between "stored" and "destroyed/voided".

Or we have to at least change some thing to behave differently. But without being able to enforce this behaviour through the API. Which means pretty much any addon will fail to do it and break it.

Trying to cleanup actually destroyed items is pretty much not possible in a sane way currently.
