### ISSUE TITLE
Tesselator is broken

### ISSUE THREAD

**Issue by WolfAmaril** [AppliedEnergistics/Applied-Energistics-2#1994]
I've been told that AE2 is the mod that is involved [in this error] (http://pastebin.com/ENsAwhig). I've also been told that is is supposedly fixed in the current alpha releases. My question is: Is there any way to fix it without updating to the alpha and, if now, how unstable is the alpha right now?

**Comment by yueh** [comment]
This is a really generic stacktrace, which could be caused by any mod or even vanilla minecraft itself.

We really need some more information, like the full crashlog.

**Comment by WolfAmaril** [comment]
[Here's the crash log] (http://pastebin.com/StV5UXC6) Which now that I look at it doesn't seem to mention AE2, but I'm completely at my wits end trying to figure out how to fix this and this is the best lead I got.

**Comment by thatsIch** [comment]
So I assume you tried to remove AE2 from your backed-up world and it does not do that? This problem is pretty difficult to track down since the `rawBufferIndex` must be 0.

I assume this happens directly after start-up?

**Comment by WolfAmaril** [comment]
Right after I hop on the server yeah. And I havne't tried pulling AE2 yet, I'll go try that.

**Comment by WolfAmaril** [comment]
Well I tried to remove AE2 but then my server started throwing a fit and refusing to start up because something was requiring AE2 and nothing would tell me what actually wanted it, so I'm right borked with that idea.

**Comment by yueh** [comment]
Something like `MemoryCleaner` is a really really bad idea. All it actually does is adding more freezes and whatever else issues...

The modlist itself is also way too large to identify any issues, the best idea would be really to reduce the amount of them.

**Comment by WolfAmaril** [comment]
While that's a fair point, I'm a sucker for overdoing mods and given that this is a pack I never intend to share, I'll just accept the fact that some stuff is just gonna be borked at times.

At this point I'm just gonna teleport away form where the crash occurs and mark it on a map as "do not get near"
