### ISSUE TITLE
Inscriber renders backside of block

### ISSUE THREAD

**Issue by thatsIch** [AppliedEnergistics/Applied-Energistics-2#1998]
When a block is in the center slot it does not render the front side but the back side.

**Comment by yueh** [comment]
You mean that they are back face culled while needing to be front face or that the rotation seems a bit random and not really matching how the are rotated as itemblock?

**Comment by GinjaNinja32** [comment]
If it's the same problem I'm seeing, it renders items in the inscriber only facing down (i.e. visible from below, invisible from above). Would be nice if it rendered both ways (or didn't back-face-cull).
"Top" of inscribers, from left to right: up, right, down, left; all contain a diamond in the center slot
![](http://nyx.gn32.uk/i/2015-11-12_19:10:42.png)
all inscribers rotated 180 degrees from above:
![](http://nyx.gn32.uk/i/2015-11-12_19:10:57.png)

Also just noticed that if you rotate so the item is the "right way up", the texture is indeed reversed - the front face is being culled, the back is visible.

**Comment by Richley** [comment]
yueh, I may seem like someone who has no idea what I'm doing here, and that's true.

One thing I need from you, however, is to contact Builderb0y and tell him that it's Richley or Pork or whatever. It's been ages since I've last seen him and I want to start up a project with him.

Thank you.

**Comment by XFactHD** [comment]
@Richley Why are you spamming issues with completely unrelated stuff?

**Comment by yueh** [comment]
Will be fixed with #1880.
