### ISSUE TITLE
AE 1.8

### ISSUE THREAD

**Issue by Artemychm** [AppliedEnergistics/Applied-Energistics-2#1999]
Dear Mod author! When AppliedEnergistics2 will at Minecraft 1.8. Thank you!

**Comment by yueh** [comment]
#1637

**Comment by thatsIch** [comment]
Sorry, I have not done much on that regard due to lack of time

**Comment by shobu9** [comment]
@thatsIch do you need help ? i have some people that may want to help :P

**Comment by thatsIch** [comment]
Always :P

**Comment by shobu9** [comment]
@thatsIch can you get on irc ?

**Comment by thatsIch** [comment]
hardly, have not much live time.

**Comment by shobu9** [comment]
Do you have time rigth now ? lol
