### ISSUE TITLE
Please, Builderb0y, Contact me immediately

### ISSUE THREAD

**Issue by Richley** [AppliedEnergistics/Applied-Energistics-2#2001]
Builderb0y it's me Richley from Ako's server. I have a project that I think you'll be interested in and I need your help to make it happen, as you're the only person with the expertise that I know of.

My email is richleyirving@gmail.com. Please send me an email describing whether or not you are interested in my project. Thanks.

Sorry for the abruption. I just recently remembered you still exist.

Did you know we have the same birthday, but you're 3 years older than me? (Not a creep, that's from Ako's server forum that I checked a while ago)

**Comment by Richley** [comment]
Yueh please

**Comment by HyperionNexus** [comment]
What do you want him for? talk to me on enjin or something since this shouldn't be here.

**Comment by Richley** [comment]
I need him for a project. I'm sorry to interrupt you but this project is
one of the only leads I have on what he's been up to.

If you can just tell him that it's an old friend from Ako's server or The
Grid he'll most likely say OK to talking to me for a bit.

On Sat, Nov 14, 2015 at 10:09 PM, HyperionNexus <notifications@github.com>
wrote:

> What do you want him for? talk to me on enjin or something since this
> shouldn't be here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2001#issuecomment-156784878>
> .
>



-- 
Richley Irving, Class of 2019
Laurel Springs Gifted & Talented Academy
richleyirving@gmail.com | +1 818 667-1301
Skype: richley_irving

**Comment by HyperionNexus** [comment]
He was the one who showed me this thread. If it's something to due with command blocks then you are probably out of luck since he left ako's server because of you constantly asking for his help.

**Comment by Richley** [comment]
It's not. I have an idea for a mod. I thought he would be interested.

And Hyperion, it's also been a long time since I've seen you. How have
things been?

On Sun, Nov 15, 2015 at 11:24 AM, HyperionNexus <notifications@github.com>
wrote:

> He was the one who showed me this thread. If it's something to due with
> command blocks then you are probably out of luck since he left ako's server
> because of you constantly asking for his help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2001#issuecomment-156845276>
> .
>



-- 
Richley Irving, Class of 2019
Laurel Springs Gifted & Talented Academy
richleyirving@gmail.com | +1 818 667-1301
Skype: richley_irving
