### ISSUE TITLE
ME Interface doesn't populate from storage bus

### ISSUE THREAD

**Issue by Ricket** [AppliedEnergistics/Applied-Energistics-2#2002]
Version rv2-stable-10.

![2015-11-14 00_52_25-minecraft 1 7 10](https://cloud.githubusercontent.com/assets/196978/11162299/17521622-8a6a-11e5-9d19-cb51a73b0b98.png)

On the left side is the "main network", which contains many diamond axes. On the right side is the sub-network, the storage is empty (it'll hold the collected items). In the center, on the left is an ME Interface and the right is an ME Storage Bus. The ME interface is configured like this:

![2015-11-14 00_55_50-minecraft 1 7 10](https://cloud.githubusercontent.com/assets/196978/11162317/7dcfd9b6-8a6a-11e5-8c83-39aae64a0dc9.png)

The ME Storage Bus is at its default configuration. The full-size ME Interface in the subnetwork is then configured to contain a diamond axe:

![2015-11-14 00_56_39-minecraft 1 7 10](https://cloud.githubusercontent.com/assets/196978/11162319/975556f4-8a6a-11e5-8f48-654b4b9da1ff.png)

But, as you can see, it never receives a diamond axe despite it being available to the network. If I view the right side's crafting terminal I do see the one diamond axe that I expect to see.

What I was aiming to achieve was to have the main network keep the subnetwork stocked with one diamond axe. Then I can have the ME Interface in the middle (not the full size one) with a crafting card, and the result will be that the subnetwork always has access to diamond axes as long as I have diamonds and sticks, but unlike if I set it up with an export bus, it won't eat through my entire supply and fill the right network with hundreds of axes. How do I achieve this, given the above apparently buggy behavior?

**Comment by MrSlayer02** [comment]
I have the same problem since I updated AE2 to rv2-stable-10. Subnetworks seems to be bugged in the last AE2.

**Comment by yueh** [comment]
Please read #708. Notably my first comment, it is mostly identical to this case.

**Comment by Ricket** [comment]
The bit about the potential feedback loops if interfaces tried to interact with each other makes sense, unfortunately. Is the only solution to my problem then to use a level emitter next to an export bus?

**Comment by Blue64** [comment]
Not necessarily, you can stock a small chest with the items (fill it with logs if you must, you've obviously got the Axes for it lol), and just store it between the panels, you get your storage, and can even use the Cable you removed. Alternatively, have you attempted this minus the ME Storage Bus using a ME Interface Block (just don't try to do a 2-way connection, it'll likely cause Lag if you do)? If done either of those ways, it should work, either put something in the middle of em, or use just Interface Block, that's my recommendation.
