### ISSUE TITLE
Molecular Assembler does not output

### ISSUE THREAD

**Issue by Derp3** [AppliedEnergistics/Applied-Energistics-2#2003]
After using my crafting-setup on the overworld (where it all worked properly), I moved into The Last Millenium. My molecular assemblers just won't output these Items that it crafted. Some works, some won't. All my storage cells are empty (enough) and everything is connected properly. I even tried it with import-busses and that didn't work either.

![molecular problem](https://cloud.githubusercontent.com/assets/15850364/11165634/d459706c-8b14-11e5-8280-f3f1ff55d6ee.PNG)

I have read the 'guidelines for contributing', here are some Details:
I am playing FTB Infinity 2.0.2 on a Server with the same version.
(I don't even know if this is the right place for posting this issue... sorry)

AE2 ver.: rv2-stable-10 (including 'AE2Core')
Forge ver.: 7.10.99.99
No crashes
Mods that could have an effect: Extra Utilities 1.2.11

My whole setup:
![2015-11-14_21 34 55](https://cloud.githubusercontent.com/assets/15850364/11165714/9f1abec6-8b17-11e5-8b6e-b0fe43bb994f.png)

I know it might not be optimized, but it works. I mean it should, which it does on the overworld.

Also, I do not really know, how to reproduce it. I am in The Last Millenium from the mod 'Extra Utilities' and have my setup as seen above. They are connected at the back via covered cables directly to the controller. All Interface Busses are online, have some patterns inside it and are ready to go. The assemblers are crafting, and only SOME output. No other devices are connected that could cause a channel-problem. All smart-cables are connected to a dense cable which goes directly to the controller.

It would be awesome if you could help me... as I have not seen this problem anywhere and it is driving me insane.

For this is my first post ever on GitHub, I don't know if I can edit these afterwards, but I will try to update the Server to the newest version, as a new version of Infinity came out as I write this; but this might take some time because my server-provider have to do that...

**Comment by yueh** [comment]
Really strange. Assemblers and interfaces are looking fine, like no missing power or channels.

Also assemblers themself are just pushing the products out (into the requesting interface) and the interfaces are more or less a simple chest.

The only idea, I currently have, is that I have currently no idea, if a security station might affect it in the case that the interfaces and assemblers are on separate networks. But probably not very likely.

Can you reproduce it in a smaller environment? Like a small creative world?

**Comment by Derp3** [comment]
I have a security station set up, but it is in the same network as everything else. It has a card in it, with the permissions for my buddy. But thats it...

The weird thing is, I fiddeled around with the cable setup. It now looks like this...

![2015-11-16_16 32 17](https://cloud.githubusercontent.com/assets/15850364/11185953/a156bd48-8c7f-11e5-93d2-bae5b6820411.png)

...and works totally fine for some reason!

I will try to reproduce it, yes.

I'll update you as soon as I finish it.

**Comment by Derp3** [comment]
Ok, so I was able to recreate the bug in a normal flat world. Infinity is now version 2.1.2.
This is a singleplayer overworld. In this scenario, none of the assemblers did output and the storage-cell I put in was almost empty.

![2015-11-20_20 49 35](https://cloud.githubusercontent.com/assets/15850364/11310192/73148a90-8fc8-11e5-9f31-60591f1ac1b6.png)
![2015-11-20_20 49 48](https://cloud.githubusercontent.com/assets/15850364/11310193/7314f156-8fc8-11e5-8059-2702df444a12.png)
![2015-11-20_20 49 55](https://cloud.githubusercontent.com/assets/15850364/11310194/7318d62c-8fc8-11e5-962c-abc75b3185f8.png)
![2015-11-20_20 50 09](https://cloud.githubusercontent.com/assets/15850364/11310196/731e9b52-8fc8-11e5-8901-1fb9eeb7c81e.png)
![2015-11-20_20 50 13](https://cloud.githubusercontent.com/assets/15850364/11310195/731d2fe2-8fc8-11e5-8bc2-ac1ffd6d7a5e.png)

**Comment by PhoenixVesafary** [comment]
I happen to have the exact same problem. Is there any update on this matter? Any ideas, suggestions, or solutions?

**Comment by yueh** [comment]
Currently not as I am unable to reproduce it.

**Comment by PhoenixVesafary** [comment]
Okay, unfortunate. Thanks anyway. 
If it helps, I play with my buddy on a dedicated Direwolf20 1.9.0 server. We haven't had this problem until yesterday, but came up quite randomly. I had changed a bit of my system, 5 minutes later this happened and I tried everything I could come up with. A couple of hours later it happened at my buddy's base. He hadn't changed anything on his system though. 

We tried if it had to do with coloured cables, facades, cable anchors, crafting storage units, p2p networks, channels, acceleration cards, etc, but nothing had any effect. 
However, since I need autocrafting for my power, I set up a single molecular assembler with a single interface, no cards, only one recipe in it, and it has worked since. 

I've ran out of ideas in the mean time, especially since it worked before and appears to be rather arbitrary. 

Anyway, thanks for your reply. 

Best regards, Phoenixy

**Comment by PhoenixVesafary** [comment]
The problem has been solved by a simple server reboot, at least temporarily.

**Comment by 5cript** [comment]
Interestingly, this issue is very old, but I ran into it as well.
I suspect, that it has something todo with microparts, as the issue started appearing as I used panels in the places where the interfaces were, for looks.
Even though I don't see why there should be any such connection.
