### ISSUE TITLE
A serious bug with Network Tool

### ISSUE THREAD

**Issue by kenvix** [AppliedEnergistics/Applied-Energistics-2#2004]
Network Tool can open chests and other machines even if they have been locked by Woldguard/Lockette/Residence.(Shift+Right click)

For AE2,Network Tool can remove parts from cables although I use ME Security Terminal and they were locked by Woldguard/Lockette/Residence too

**Comment by wlhlm** [comment]
> Network Tool can open chests and other machines even if they have been locked by Woldguard/Lockette/Residence.(Shift+Right click)

#1925

> For AE2,Network Tool can remove parts from cables although I use ME Security Terminal and they were locked by Woldguard/Lockette/Residence too

#735

**Comment by yueh** [comment]
Thanks for linking the related issues @wlhlm.

I also want to mention that we do not support cauldron, probably already mentioned in the linked issues. But just to be safe.
