### ISSUE TITLE
No restrictions for interface's auto outputs into inscribers

### ISSUE THREAD

**Issue by ivanich-fmf** [AppliedEnergistics/Applied-Energistics-2#2008]
I play Minecraft 1.7.10 with Forge 10.13.4.1517 and AE2 rv2-stable10. When I try to place wrong item into inscriber with some press in interface's slot minecraft restrict me. I try to use this for create auto-system for crafting processor units. I can use five interfaces for each inscriber, but I must use one for simplify my network. Auto output from interface put each item into south inscriber without restrictions of installed press when I place four inscribers around interface and place various presses into them.
![2015-11-20_10 08 00](https://cloud.githubusercontent.com/assets/15928505/11293855/23599b2a-8f6f-11e5-9525-929c0b80515e.png)

**Comment by yueh** [comment]
GUI and machine interactions are something completely different.

Checking if a recipe is valid within the GUI is perfectly valid as it has really no scaling issues as it is inherently slow.
Doing the same for machines is a really bad idea. Searching for a valid recipe each time a tileentity tries to insert something can be quite taxing and can easily be scaled up until it will affect the performance. 
Say chain like inscribers together and try to insert an invalid item to them each tick. For each inscriber it needs to search through all valid recipes, if there is a matching one. Probably fine when there are only a few recipes, but nothing prevents you from adding hundreds inscriber recipes.

If we compare it with the vanilla furnace, then the GUI should not even restrict you from placing an invalid item into a slot as the furnace will only prevent shift clicking but not dragging items into the input slot. For example it will neither restrict you from placing furnaces into a furnace via GUI nor via hoppers/pipes/etc.

Are there even any machines which have configurable recipes and filter against a valid recipes?
Most I can currently think of allow inserting any item as long as the slot itself has no restrictions and never take any other slots into account.
