### ISSUE TITLE
Error in log file

### ISSUE THREAD

**Issue by Tsyklop** [AppliedEnergistics/Applied-Energistics-2#2009]
http://pastebin.com/EeCJEUB3

AE2 rv3 alpha10

**Comment by yueh** [comment]
This is intentional, but could probably be a bit more meaningful.

**Comment by Tsyklop** [comment]
fix?

**Comment by thatsIch** [comment]
There is nothing to fix, it is just displayed badly.
We can not fix what is broken in other mods

**Comment by Tsyklop** [comment]
@thatsIch look: https://github.com/bdew/ae2stuff/issues/89
