### ISSUE TITLE
Issue when crafting with Cutting knives AE2 rv2 stable v10

### ISSUE THREAD

**Issue by QuintessenceX** [AppliedEnergistics/Applied-Energistics-2#2013]
When putting a quartz cutting knife in a crafting window eg: players 2x2 crafting window, the knife will take damage without having crafted anything. I this can be repeated and the knife will end up with a negative durability ie -10/50 which will be able to craft one set of cable anchors then break.

Mod List: http://pastebin.com/ea3MNFGL

**Comment by yueh** [comment]
#1950
