### ISSUE TITLE
AE Porting

### ISSUE THREAD

**Issue by InusualZ** [AppliedEnergistics/Applied-Energistics-2#2016]
Hi, I'm a Minecraft PE Modder. I'm trying to contact @AlgorithmX2 because I'm using his code for rendering the Wooden Crank in my [mod](https://github.com/InusualZ/Mechanics). I don't know if this [thread](http://www.minecraftforum.net/forums/minecraft-pocket-edition/mcpe-mods-tools/2437227-sharing-porting-content-to-mcpe) applied on my case but anyway I ask for your permission to use [your code](https://github.com/InusualZ/Mechanics/blob/master/jni/Mechanics/graphics/WoodenCrankRenderer.cpp#L3) in my mod.

Thank You.

PD: Sorry for my "broken" english

**Comment by yueh** [comment]
As long as you respect the licenses as stated in the [README](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/README.md), it should be fine.
