### ISSUE TITLE
Storage bus unable to view items in matter condenser

### ISSUE THREAD

**Issue by Builderb0y** [AppliedEnergistics/Applied-Energistics-2#2017]
If a storage bus is connected to a matter condenser with matter balls or singularities in it, they will not be visible in a terminal. Hoppers/import busses/item conduits/etc… are all capable of extracting items from the condenser, and the storage bus is capable of inserting items, but not extracting them. Changing the input/output mode does not make a difference, nor does enabling "report inaccessible items" (this won't show the storage component in the condenser either, though that's less of a concern). The storage bus DOES seem to work normally on other modded inventories, just not the condenser. Using rv2-stable-10.

Oh, and clicking the partition storage button doesn't do anything either; matter balls/singularities do not get added to the filter.

**Comment by yueh** [comment]
Condensers are handled in a special way with AE2, for example that they are never prioritized over other inventories as long as there is a another prioritized inventory.

But I have currently no idea, why they do not report the stored items inside a condenser. Maybe a design decision?
