### ISSUE TITLE
no load

### ISSUE THREAD

**Issue by EliteTheLegend** [AppliedEnergistics/Applied-Energistics-2#2018]
i have downloaded and deleted meta-inf as should be (right) and it hasnt loaded.
i added a few new mods like 20 or so and some are add-ons to applied energistics and when i opened minecraft with forge it said i have a problem with my instalation although the most recent ae2 is in my mods folder
![screenshot 93](https://cloud.githubusercontent.com/assets/16053258/11449203/351a61d2-9532-11e5-96a2-f708041e7f4e.png)
![screenshot 94](https://cloud.githubusercontent.com/assets/16053258/11449246/ec42139a-9533-11e5-9850-25e0e9995a02.png)

**Comment by bookerthegeek** [comment]
Wait.... what?

Why are you deleting the meta inf when your using forge?

**Comment by EliteTheLegend** [comment]
you sure thats the thing?
cuz..all of the other mods are like that and nothing's wrong with them..i even reinstaled the whole mod to try it but same things happened

**Comment by bookerthegeek** [comment]
1. Clean instance of minecraft.
2. Install forge with the forge installer.
3. Does minecraft start? Go to step 4.
4. Place your mods in the new model folder in your minecraft instance.
5. Enjoy molded minecraft.

**Comment by EliteTheLegend** [comment]
thanks il try that

**Comment by EliteTheLegend** [comment]
there was a messed up mod in the folder..thx
