### ISSUE TITLE
Switch from alpha to stable

### ISSUE THREAD

**Issue by TheRealTurtler** [AppliedEnergistics/Applied-Energistics-2#2019]
Hi everyone,

my friend made a modpack, but he accidently used the version rv3-alpha-9. Is there any way to change it to a stable version without destroying the world?

I would be really happy if anyone can help me :smile:

**Comment by yueh** [comment]
If you just created a world, it should be fine.

rv3 added a few new things, which will be lost.
It probably works, but not really guaranteed. So better make a backup of it.

**Comment by TheRealTurtler** [comment]
Thank you for your answer, but there is a problem now...

I have switched the rv3 with the rv2.stable build 10, but i'm not able to start client/ server. The crash report says missing mods: appliedenergistics2 : [rv3-alpha build-9,] . Am i doing anything wrong or is it not possible to change from alpha to stable?

**Comment by XFactHD** [comment]
Please put the crash report on pastebin.com or gist.github.com and post the link here.

**Comment by TheRealTurtler** [comment]
Here it is:
http://pastebin.com/Ud7TCr4Z

**Comment by yueh** [comment]
Some of of the mods does require this version.

But no idea which one. For whatever reason, forge decides to not add this although they could do it...
