### ISSUE TITLE
OreDict Merge-er(er)

### ISSUE THREAD

**Issue by neogenix** [AppliedEnergistics/Applied-Energistics-2#2020]
A possible idea for an improvement would be a property file to essentially have AE auto-merge all inbound ore/items to the same item on the OreDict. This is the behavior of the Jabba Barrel, and I surmise that this isn't something heavily frowned upon. Perhaps making it variable / optional (property) may make it YMMV. 

Thoughts?

**Comment by yueh** [comment]
#1243

**Comment by Zsashas** [comment]
Suggestion: use this mod: http://minecraft.curseforge.com/projects/oredictionaryconverter

Simple ore dictionary converter, by default only works on ores, ingots, etc. Can be configured for other oreDict entries if you want.
