### ISSUE TITLE
Prefer smallest possible crafting CPU

### ISSUE THREAD

**Issue by neogenix** [AppliedEnergistics/Applied-Energistics-2#2021]
Hi Guys! 

I have a few places right now that single items burn up my huge CPU's, and then I have to either cancel, or wait for those to finish to proceed using my big CPU's, instead of perhaps having the mod prefer the smallest CPU that would fit the requirement. Is this a viable idea?

**Comment by wlhlm** [comment]
#1055, #1188, #1814

**Comment by neogenix** [comment]
Awesome, thanks! I swear I searched before posting, but it is late :(
