### ISSUE TITLE
Cables doesnt show channels!

### ISSUE THREAD

**Issue by rouderx** [AppliedEnergistics/Applied-Energistics-2#2023]
Hi, when i put some blocks from mod "Forge Microblocks" on cables, they doesnt show channels or if i put it ner the interface or similar, it doesnt show "Device is online/ofline" .

**Comment by yueh** [comment]
Works fine for me.

![fmp-cables-channel](http://i.imgur.com/CCRCh5E.png)

**Comment by rouderx** [comment]
I mean here: .. 
![bez nazvu](https://cloud.githubusercontent.com/assets/16058658/11452443/e6530ff2-95e7-11e5-9dc1-1c820cc0ed24.png)

**Comment by TheJulianJES** [comment]
Yeah, I think #621 broke that.

**Comment by shobu9** [comment]
*sigh*, it's just a sync issue , sometimes it doesn't show on waila or show it on the smart cable, but it does work, usually the best way to fix that is to chunk load or break and replace.

**Comment by yueh** [comment]
Not a sync issue, simply an issue with FMP. After adding a FMP cover, they are no longer AE2 tile entities and WAILA will no longer use our integration.

Probably something which never worked from and is probably a good indicator that FMP is nearly never used...
I have no idea, if WAILA provides an FMP specific API. @thatsIch probably knows more.

**Comment by shobu9** [comment]
@yueh , There is no FMP in the pack im in and when the chunk reloaded SAME SAME issue happens.
But it could have an effect with Forge Mutilparts Parts too, i haven't checked it.

**Comment by shobu9** [comment]
I know this main issue here talks about FMP bug but the same thing happens.

**Comment by shobu9** [comment]
Dammit i need to explain this on irc. Be rigth there

**Comment by shobu9** [comment]
Also @rouderx why use FMP instead of the Facades they are especially made for this.

**Comment by TvL2386** [comment]
Because FMP is easy and works with other cables as well (Mekanism for example). Simply cut every block you want and use them as covers. It also allows you to create covers with a hole in it for the cable to go through. It works perfectly, except for the missing channel count which I also observed.

**Comment by thatsIch** [comment]
@yueh not that I am aware of
