### ISSUE TITLE
Error in log (not important)

### ISSUE THREAD

**Issue by Wasabules** [AppliedEnergistics/Applied-Energistics-2#2024]
28.11 15:50:00 [Server] INFO [15:50:00] [AE2 VersionChecker/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Thread.run(Thread.java:745)
28.11 15:50:00 [Server] INFO [15:50:00] [AE2 VersionChecker/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at appeng.services.VersionChecker.run(VersionChecker.java:86)
28.11 15:50:00 [Server] INFO [15:50:00] [AE2 VersionChecker/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at appeng.services.VersionChecker.processInterval(VersionChecker.java:106)
28.11 15:50:00 [Server] INFO [15:50:00] [AE2 VersionChecker/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at appeng.services.version.ModVersionFetcher.get(ModVersionFetcher.java:34)
28.11 15:50:00 [Server] INFO [15:50:00] [AE2 VersionChecker/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at appeng.services.version.VersionParser.parse(VersionParser.java:34)
28.11 15:50:00 [Server] INFO [15:50:00] [AE2 VersionChecker/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at appeng.services.version.VersionParser.parseVersion(VersionParser.java:72)
28.11 15:50:00 [Server] INFO [15:50:00] [AE2 VersionChecker/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at appeng.services.version.VersionParser.parseChannel(VersionParser.java:117)
28.11 15:50:00 [Server] INFO Exception in thread "AE2 VersionChecker" [15:50:00] [AE2 VersionChecker/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.IllegalArgumentException: Raw channel stable did not contain any of the pre-programmed types.

**Comment by yueh** [comment]
#1521
