### ISSUE TITLE
Title of the subject in the Storage monitor

### ISSUE THREAD

**Issue by TarakanE** [AppliedEnergistics/Applied-Energistics-2#2026]
Hi. 
I faced the problem how to make the name of the item (like on the bottom one) appear on the storage monitor (one block up). If there is any chance to deal with this issue? 
![2015-11-28_17 02 06](https://cloud.githubusercontent.com/assets/16063150/11454180/6ca2fee6-963d-11e5-9aad-0008780bbf6b.png)

Texturepack: SoartexFanver

**Comment by yueh** [comment]
Not sure, if this is possible. Item frames are using entities (so similar to zombies or other mobs) and their names for it, which is really a horrible idea in terms of performance.

If I recall correctly, our WAILA integration should display the type.
Not ideal to depend on another mod, but most packs use it.
