### ISSUE TITLE
annihialation plane wont pick up crystals grown from seeds

### ISSUE THREAD

**Issue by convict999** [AppliedEnergistics/Applied-Energistics-2#2029]
basically i had fully automated ae crystal growing and fluix crystals crafting completley on previous infinity modpack using only ae, using formation and anhialation planes succesfully. 

ive rebuilt in the current pack latest version (ftb) crystals passed through system manually from inventry are collected fine, crystals that have grown from seed, i imagine have different metadata (whatever?) so they dont despawn, wont be picked up. tried the fuzzy option but no joy. (was surprised didnt pick up part grown either, even though different items) 

fluix crystals (from certus, redstone and quarts) work fine as they dont have no-despawn.
i notice part grown seeds are not attracted to magnet now, which was always annoying, thanks.
ive had to resort to using a transfer node which works, but dissapointed as wanted to use only ae, was proud that i achieved it before. many thanks.

**Comment by yueh** [comment]
Works fine in my testsetup. 

Keep also in mind that the planes will block for a short time, if they cannot insert the item into the network to reduce the serverload a bit. So as long as there is one item flowing around, which cannot be imported and bad RNG luck, they can block for a long time.

**Comment by convict999** [comment]
interesting, ill have to try again tomorrow.
Just strange as will pick up crystals instantly that are manually placed in the depositing sub net, while grown crystals are still swimming there.
I have interface on main network with seeds to crystal patterns, inserting into another interface on sub network to a formation plane. 
The annhialation plane has to be on another separate whitelisted sub net or the seeds are picked up and placed every tick (infinite loop), which i have to say looks extremely impressive but slightly contradicts the blocking concept again.
Thanks for looking, ill have a try again and report back.

Dire made me happy today because he didnt know how to turn on growth accelerators with ae, i cant be so noob after all.

**Comment by convict999** [comment]
i rebuilt again along side of existing and embarresingly yes it worked fine. 
i notice my original existing build crosses a chunk boundary, water pool in one with sub net exporting into another chunk, if you can think why that would make a difference ill happily tear down and re-test to save you the trouble

**Comment by ranger135xp** [comment]
I've noticed quirky bugs with this myself. I had an issue that I posted about once, but the answer was that the main network had a security terminal. The subnet that hosted the automated crystal growing machine didn't have proper security within AE to allow the subnet to insert items into the main network.

**Comment by XFactHD** [comment]
I have the same problem with a storage bus on an interface. The items are not inserted into the interface by the storage bus although the security terminal on the main network doesn't have a biometric card in it.

**Comment by yueh** [comment]
Performance issues would mostly arise when looping (and failing to insert) through a pretty large network inventory.
Looping inside the small subnetwork is not really an issue.

If I recall correctly, it will be locked for about 5 or 6 secs. So as long as you are not constantly dumping more seeds into it, even with the 5 minutes despawn timer, there is plenty of time to insert everything after all seeds are finished.

**Comment by convict999** [comment]
i think you can mark topic as closed. 
have rebuilt system again, it did have its moment of stubbornness, but break and replace cables fixes issues. 
i think the moral of the story is,  dont sequentally modify active complex networks. 
disable, build/modify then connect.
