### ISSUE TITLE
Crafting patterns get voided on relog

### ISSUE THREAD

**Issue by M0R3design** [AppliedEnergistics/Applied-Energistics-2#2036]
I build a new dimension (with RFtools) and build a new ME system. When i place crafting patterns in Terminals adjacent to Molecular Assemblers and Alloy Smelteries (Ender IO furnaces) they disappear on relog (only these two blocks are affected). This doesn't happen in the Overworld. (I'm Playing Direwolf20 v.1.9.0 for MC 1.7.10 (fastcraft enabled)

**Comment by yueh** [comment]
#1983
