### ISSUE TITLE
Other items disappear for few seconds when pick items in Terminal

### ISSUE THREAD

**Issue by Zaflis** [AppliedEnergistics/Applied-Energistics-2#2038]
Sometimes when i pick specific items, say RFtools dimlets or Botania flowers, N amount of other item types disappear from crafting terminal for few (5+?) seconds. How many other items disappear, completely depend on item type i pick. Sometimes just picking 1 dimlet causes all dimlets to disappear.

Testing this with appliedenergistics2-rv3-alpha-9. Would try with alpha-10 but Chisel2 mod causes a server crash on start, and they are unwilling to patch it against ae2 alpha builds.

**Comment by yueh** [comment]
#1964
