### ISSUE TITLE
Storage Bus & Deep Storage Unit = Weird Dupe Bug

### ISSUE THREAD

**Issue by dogboy21** [AppliedEnergistics/Applied-Energistics-2#2041]
Forge Version: 10.13.4.1492
AE Version: rv2-stable-10
Modpack: Infinity Evolved 2.1.3

When the input slots on a Deep Storage Unit are blocked, a Storage Bus can extract an infinite amount of the stored item.

Steps to reproduce:

![1](http://i.imgur.com/D5EQjMK.png)
(The block above the DSU is needed)

---

![2](http://i.imgur.com/kVwVkjI.png)

---

![3](http://i.imgur.com/ThSSKGj.png)
(Note that the Stone counts as redstone)

---

![4](http://i.imgur.com/H7NLFgN.png)

---

If there is also 1 item at the second input slot, the amount of redstone increases in the terminal when I take out a stack
![5](http://i.imgur.com/a5G0aVp.png)

---

![6](http://i.imgur.com/QeSagfl.png)

---

![7](http://i.imgur.com/szMyINh.png)

**Comment by yueh** [comment]
This is MFR bug as it adds the stacksize of the inputs to the stored amount regardless of being the same item, thus it will report up to 128 more stored items then it actually has stored.

Not fixable on our side, but as far as I know it is fixed in one of the alpha versions of MFR.
