### ISSUE TITLE
Unable to place cables/cable accesories

### ISSUE THREAD

**Issue by amdorj** [AppliedEnergistics/Applied-Energistics-2#2042]
I have a complex ME system set up, and when attempting to add to it, I placed a cable and it *instantly* changed back into an item form. The same thing happened when placing a ME Interface. I am using rv2-stable-10. I also have facades on the cables; I do not if this helps, but the facades, when moused-over with Waila, it says "AE2 Cable and/or Bus". I can provide more information if requested.

**Comment by XFactHD** [comment]
Do you have a security station on the system?
