### ISSUE TITLE
Storage Bus disturbed by ME Level Emitter after restart

### ISSUE THREAD

**Issue by bmario** [AppliedEnergistics/Applied-Energistics-2#2043]
I recently came across a bug in rv2-stable-10 on my server.
However I can reproduce the bug with only AE2 installed in Single Player modus.
The problem only occurs after a reboot or new session in Single Player.

The problem is, that an ME Storage Bus does not seems to be working, when there is an ME Level Emitter with a Fuzzy Card in it installed on the same network.

This is my setup:
The ME network comprises the Storage Bus, an Energy Cell, an Terminal, and the ME Level Emitter.
![2015-12-09_15 12 54](https://cloud.githubusercontent.com/assets/130405/11687628/0c468556-9e88-11e5-8d1f-e4382897dfd1.png)

A Chest with an adjacent ME Storage Bus in default settings.
![2015-12-09_15 27 11](https://cloud.githubusercontent.com/assets/130405/11687865/7446eabe-9e89-11e5-9e6e-dfc34293b347.png)

In the Chest is an diamond pickaxe.
![2015-12-09_15 20 53](https://cloud.githubusercontent.com/assets/130405/11687700/7882180c-9e88-11e5-89a6-0f71e4c48c45.png)

And the ME Level Emitter is configured to emit a signal if there is below 1 diamond pickaxes present, with a Fuzzy Card present.
![2015-12-09_15 22 31](https://cloud.githubusercontent.com/assets/130405/11687738/b28241d0-9e88-11e5-8163-170c2f509f8b.png)

So in theory, the level emitter shouldn't emit a redstone signal and the terminal should show the pickaxe. But after a restart (for single player, go into main menu), the terminal don't show the pickaxe and there is a redstone signal.
However, after a slight change to the Network, e.g., take away the energ cell, it works again like intended.

*edit: I forgot to mention the forge Versions:
Forge Version on my server: 1448
Forge Version on Client: 1291, 1448 and 1403, all three are affected

**Comment by bmario** [comment]
rv3-alpha-10 is also affected.

**Comment by yueh** [comment]
Interesting.

Should be fixed with #2032.

**Comment by bmario** [comment]
Any chance for a fix to rv2?

Or do you have an idea for a workaround?

**Comment by yueh** [comment]
No idea what actually causes this. Just noticed that the pickaxe is not missing from the terminal with the PR, but the level emitter still behaving incorrectly as the cache was updated in the wrong order.

No idea about rv2, need to at how much work backporting would need. And it is more or less the blocking issue for rv3 beta/stable.

**Comment by bmario** [comment]
I found a somewhat usable workaround for rv2 on my server. haven't tested it for other build. Adding an ME Controller has a positive effect. However, it sometimes occur nonetheless. Tho, I felt like sharing, it may help someone else.
