### ISSUE TITLE
Server Side Crash Appeng rv3 alpha 11

### ISSUE THREAD

**Issue by aikpoppel** [AppliedEnergistics/Applied-Energistics-2#2047]
Hey,
im unable to start my server if i using rv3 alpha 11.
http://pastebin.com/EqcLxYeV
LG Aik

**Comment by yueh** [comment]
Cannot reproduce it. Works fine for me on my server running forge 1558 as well as 1448.

Also keep in mind that DragonAPI is replacing our API with rv2, which will also crash.
I would recommend reducing the amount of mods and trying to identify, if any other mod could cause it.
Maybe even grep over all .jars and check, if they contain an `appeng` folder.

**Comment by yueh** [comment]
Ok this is strange. It seems to only affect the build done by your build server for release.

Neither any local build version nor the PR builds did have this issue.
Waiting on some feedback regard the server.

**Comment by yueh** [comment]
Build server did produce a bad build. The newest build (12) should fix it.

(Of course if DragonAPI is still replacing our API, that might cause other issues)
