### ISSUE TITLE
Item storage completly buggered

### ISSUE THREAD

**Issue by PsionicArchon** [AppliedEnergistics/Applied-Energistics-2#2048]
Using version rv3 version 12 completely breaks item storage.

All terminals on my network are reporting incorrect item values, or showing ghost items that are being routed into trash cans.

I'm using emitters to deactivate farms upon storing 32000 of a given item. All of my terminals are reporting as 65000 items. All cells on the given network were white listed. Something is very wrong. Reverting to version 10 in the mean time.

**Comment by yueh** [comment]
This was somewhat expected as we did a major change to improve the performance with b12.

But we really need a detailed description on how to reproduce any issues.
Ideally just with AE2 as the only mod and an easy network setup (maybe even as world download).
"Does not work" is simply not sufficient to fix anything.

I already catched a couple of issues during developing it, but as long as it is not tested by more people, it is simply too hard to find any missed bug.

**Comment by PsionicArchon** [comment]
I'll pull a backup of my server world and load up a test copy for some screenshots as soon as I am able.

Will edit this with the results.

**Comment by yueh** [comment]
Not sure about the JABBA part, this should really not happen. Except if there is a bug with handling DSU (barrels are basically DSUs).

I already reverted the inventory changes from build 12 for now with build 13. I doubt we can really improve the performance without a major design change. So maybe with 1.8. But even that is questionable with the how minecraft handles inventories and how nearly impossible it makes to cache them in a sane way, while still having a reasonable performance and not invalidating the whole cache with every change.
