### ISSUE TITLE
Make compass point to nearest skystone chest rather than just skystone

### ISSUE THREAD

**Issue by isochronous** [AppliedEnergistics/Applied-Energistics-2#2051]
The skystone compass is a really cool idea, but I ran into a major problem using it, which was that it took me ~8 hours of exploration to find all of the press pieces... and not, I think, for the intended reason.

I got pretty lucky and had a meteor generated only a couple dozen chunks from my primary base, and it had 3 of the 4 press plates inside.  I thought to myself, "cool, if the other meteors are similar, I should only need to find one more meteor to get all four!"... and then I realized I had a little problem.

The compass points to the nearest skystone, right?  Well, in the case of above-ground meteors, there are little bits of skystone scattered EVERYWHERE around the meteor itself, and with a mining density similar to obsidian, breaking even one skystone block takes ~10 seconds with a mining speed 12 pickaxe.  I switched to using a TiC hammer on the main body of the meteor because I found it to be a little faster overall, but it still took me probably 25 minutes to completely destroy the meteor.  Then it took me another 30 minutes to hunt down all of the skystone bits scattered around the area.  I'm playing on the 1.7.10 pack, which has the morph mod installed, so I morphed into a bat to visually scan the area from the air while hunting the blocks down.  I was sure I'd gotten all of them, but looked at my compass and it was still just spinning like crazy.  I then went around and basically mined the whole chunk down another 4-5 levels, but the compass just kept spinning despite an apparent absence of any skystone, making me realize I'd just wasted about an hour (and I knew it wasn't because I was too far from another one, because when I moved away from that chunk it would stop spinning and point right back at it), and that going off in another random direction was pretty much my only option... so that's what I did.

Eventually I got far enough from the first meteor for my compass to point to a new one.  I get to it (this one underground), burrow into its center, and find... one press plate that I already had.  So more random wandering it was!

I then repeated that process *five more times*, each time finding just one or two press plates that I already had.  Every time it made me hate the things more and more.  Finally I just said screw it, switched into creative, and stayed in creative until I'd finally located a meteor with the last press piece I needed.

I think this frustration could be alleviated by making the compass point to the skystone chests buried in the middle of the meteors rather than the skystone itself, and making sure the compass recalibrates itself when a skystone chest is harvested.  If that were the case, then we'd only be **required** to mine into the meteor far enough to get the chest, harvest the chest itself, and boom, the compass would indicate the way to the next skystone.  We could still mine out the skystone itself if we wanted, but then the process of finding all of the press plates would consist primarily of following the compass, rather than being half following the compass, half random wandering.

**Comment by yueh** [comment]
#550

**Comment by isochronous** [comment]
Well, crap.
