### ISSUE TITLE
crash during startup and update check

### ISSUE THREAD

**Issue by Sailren** [AppliedEnergistics/Applied-Energistics-2#2052]
well, title says all: http://paste.ubuntu.com/13935114/

well FastCraft{1.22} [FastCraft] (fastcraft-1.22-ctest17.jar)  is installed, but i dont think this is the cause
used Version is rv3_12

**Comment by yueh** [comment]
#1995

**Comment by Sailren** [comment]
can i fake this in creating the Version-cfg manually?

**Comment by yueh** [comment]
Yes, just create an empty text file named `VersionChecker.cfg` for now.
