### ISSUE TITLE
Channels not displaying, storage via P2P not working

### ISSUE THREAD

**Issue by FalseTetrabyte** [AppliedEnergistics/Applied-Energistics-2#2054]
I saw a prior issue thread stating something about WAILA and the channel issue, but I wanted to mention it since we're having that problem as well.  

I cannot get storage to work over P2P.  I've tried both the standard fluix as well as the colored cables - in every case, unless I directly connect the dense / smart cable from a controller to a stack of drive enclosures, the data storage doesn't work.  Coupled with the WAILA issue, makes it hard to isolate the issue.  I've tried flopping the P2P tunnels, clearing the card and re-saving/assigning, nothing seems to work.  Even when directly connecting with dense cable to the storage, it says 0 of 32 channels in use, though I do see one of the lines lit up.

Using rv2-stable-10 with Forge 10.13.4.1448

Can furnish other mods upon request - not sure if this is an issue I can fix by downgrading, but will try it shortly.

**Comment by wlhlm** [comment]
ME P2P tunnels don't provide AE power, so often you have to loop around the tunnel interface with a Quartz Fiber.

**Comment by FalseTetrabyte** [comment]
I'm not a stranger to that, but I appreciate the thought.  I'm using the quartz fiber on each channel.  The end cables are getting power, just no channels, and no access through the P2P tunnel - and the main cable bundle doesn't show any channels in use at all either.
