### ISSUE TITLE
Shift clicking not fully operational With IC2

### ISSUE THREAD

**Issue by bookerthegeek** [AppliedEnergistics/Applied-Energistics-2#2056]
### The following details are required:
Forge Version: 10.13.4.1558
A.E. Mod Version: RV2-STABLE-10
Other Mod: Industrialcraft 2 2.2.804-Experimental
A detailed description of the bug: When shift-clicking the question mark while using the ME Crafting Terminal some recipes do not add the items into the UI. Upon some testing it seems a number of IndustrialCraft 2's refuse to add vanilla items. 
 * Reinforced Glass, refuses to add glass
 * Energium Dust, doesn't add redstone
 * Glass Fibre, doesn't add glass

###  Included as it is applicable
* Expected
  * The recipe would form in the crafting area of the crafting terminal
* How to reproduce the problem?
  * Attempt to shift click the recipe for Reinforced glass while inside a crafting terminal
* Server or Single Player?
  * Both
* Screen shots or Pictures of the problem (Reinforced Glass used as example)
  * [Reinforced Glass Recipe](http://i.imgur.com/NNwDa03.jpg)
  * [After shift clicking](http://i.imgur.com/lsjxpn1.jpg)
* Mod Pack using and version?
  * [FTB Infinity Evolved](http://www.feed-the-beast.com/projects/ftb-infinity-evolved)

[Original Bug report at FTB](http://forum.feed-the-beast.com/threads/2-1-0-me-crafting-terminal-refuses-to-add-items-to-recipe.135080/)

**Comment by yueh** [comment]
#1552
