### ISSUE TITLE
Upon creating pattern GUI suggests specific mode

### ISSUE THREAD

**Issue by thatsIch** [AppliedEnergistics/Applied-Energistics-2#2058]
When a pattern is made and the recipe is not possible to craft in a vanilla crafting bench, the GUI could suggest to switch to external crafting mode

Inspired by https://www.reddit.com/r/feedthebeast/comments/3wqrtp/problem_autocrafting_in_ae2_infinity/

**Comment by yueh** [comment]
Interestingly I considered something similar while reading it. But no idea how to actually improve it.

In my experience any suggestion based system usually works around bugging you when you do not need/want it, thus causing it to be ignored. But never appear when you actually need them, but you can still remember that something did pop up in the past and and have no idea what it suggested or how to bring it back.
Or it is constantly annoying and cannot be turned off...

Automatically switching between the modes once no recipe exists is probably also very confusing.
Not everyone uses NEI to simply shift click them, so it is pretty likely that it will constantly change its mode during the creation. Trying to match the current configuration being a subset of any valid recipe is probably also way to slow and has a good chance of always staying in crafting mode.
Also some processing recipes can easily be identical to a normal crafting recipe, thus it will still need manuall toggling it, yet the player still not knowing how to do it.

It might also be caused be some UI inconsistencies.
This button is really the only one being placed in a similar location and with a similar style.
Nearly all other buttons are located on the left side and clearly distinguishable as buttons.
But then it is a pretty frequently used function, thus placing it in between the other buttons it might even reduce the visibility of it.

A ingame documentation might potentially help a bit, but there will always be some players not reading it.

**Comment by XFactHD** [comment]
Would it be possible to mark processing recipes red when the pattern is placed in an Interface on a Molecular Assembler, similar to the way the Molecular Assembly Chamber did it in AE1?

**Comment by yueh** [comment]
And how does this help to prevent player from not noticing that they can toggle the mode inside a pattern terminal?

**Comment by XFactHD** [comment]
Didn't really think of that, sorry.

**Comment by yueh** [comment]
Also it would not really work. A processing pattern inside an interface + crafting pattern inside the adjacent assembler is a perfectly valid build. Maybe not ideal, but nevertheless an option.
Thus it will be simply wrong in this case to indicate an invalid pattern.

Also more complex situations will cause issues.
Like chunk loading issues and displaying it inside interface terminals could be wrong (assemblers not loaded)
Or what happens, if there is an assembler and something else adjacent. The order on how it tries to dump the input is deterministic, so someone could use this and share the interface. Say if the other machine only accept a limited amount of items, which are never used for the assembler recipes.

**Comment by Technici4n** [comment]
With the `+` button in REI/JEI, this isn't needed anymore I think. REI/JEI will already tell you if you're in the wrong mode, and once you understand that there are two modes this feature isn't necessary anymore.
