### ISSUE TITLE
Bug?: Processing patterns

### ISSUE THREAD

**Issue by Haadoor** [AppliedEnergistics/Applied-Energistics-2#2060]
Hi!

Was trying to use ae2 for autocrafting botania items, and I think i stumbled upon a bug. Are you not allowed to craft 2 (let's say redstone) by sending one redstone? The pattern was crafted successfully, but when trying to craft it through the terminal. It said "simulation" at the bottom and the "craft" button was faded out.

If this is intended, oh well, then i have to figure out a new way :) But it would be really nice to have, especially with botania and the conjuration crystal.

**Comment by yueh** [comment]
#439
