### ISSUE TITLE
ME Terminal issue : Need to break the smart cable for access to storage

### ISSUE THREAD

**Issue by Kikaze** [AppliedEnergistics/Applied-Energistics-2#2061]
I have an issue that's working like this : 

I can right click on terminals of my network but when i want to grab or put something in it, it just do nothing.
I have to break the smart cable wich power/connect them, wait a bit and then replace the cable for grab something in it and after something like 10 seconds i can't anymore.

So i keep break / replace again and again.

I have no error on log.

What i have already tried : stop / restart the server, updated my modpack.

Thanks.

**Comment by thatsIch** [comment]
Sounds like AE1?
