### ISSUE TITLE
Missing Crafting recipe outputs?

### ISSUE THREAD

**Issue by Urahara721** [AppliedEnergistics/Applied-Energistics-2#2062]
Running the latest stable build in a hermitcraft modsauce 2 server and everything worked fine for a while then randomly some crafting recipes no longer output their items. so far dense cables and acceleration cards don't work that i have found, despite having been able to craft them before.

The recipes and items do show up in NEI though, which is whats confusing me.

Update: After a few server restarts and relogs the NEI recipe for dense cable changed (previously it was 4 covered cable, a glowstone dust and a lapis, it then displayed with redstone in place of the lapis) and attempting to shift-right-click the nei '?' to place the items in the crafting grid, the client crashed. Upon rebooting the client, using the newly displayed recipe works fine for dense cable and the acceleration card recipe (same as before) works as well. Still don't understand what was happening, but happy its working again.

**Comment by yueh** [comment]
Could you provide the crashlog?

But it sounds a bit like something is modifying the normal recipes. Maybe also different ones between the server and client.

**Comment by Blue64** [comment]
this sounds similar to the Custom Recipes issue that was experienced in Version 2 Stable 10 where it looks in the ```config``` folder for the Recipes without failsafing to the ```.jar``` if it finds none, but in this case, it sounds to me like the server was having it's recipes tweaked, I would consult the server admin.

the Crash may have potentially been AE2 or NEI from the sounds of it, or whatever you were using to craft on (eg. Gany's Surface's Dual Crafting Table), we would need to see the Crash Log for further debugging. If the error is for example an Invalid Recipe, the Mod Author or Forge would need to know that they need to fix that handling so it doesn't hard crash.
