### ISSUE TITLE
ME storage drives being pulled from ME Drives into ME system inventory

### ISSUE THREAD

**Issue by KrazyChuck95** [AppliedEnergistics/Applied-Energistics-2#2064]
My one ME Drive that is connected right to the controller and everything keeps putting the storage drives that don't have anything stored on them into the ME system inventory. Bug???

**Comment by yueh** [comment]
Where else should they be stored?

**Comment by KrazyChuck95** [comment]
They should be staying in the Me Drive. They're being pulled into the ME
system and being stored on the storage drives so i can't fill them up with
items.

**Comment by ktole1999** [comment]
Do you have something connected to ME drive that imports? Import bus

Sent from Outlook Mobile




On Wed, Dec 23, 2015 at 6:07 AM -0800, "KrazyChuck95" <notifications@github.com> wrote:





They should be staying in the Me Drive. They're being pulled into the ME
system and being stored on the storage drives so i can't fill them up with
items.
On Dec 23, 2015 4:49 AM, "yueh" <notifications@github.com> wrote:

> Where else should they be stored?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2064#issuecomment-166861595>
> .
>


---

**Comment by KrazyChuck95** [comment]
Not to the ME Drive. I have an import bus hooked up to a couple auto sieves
and that's it.

**Comment by yueh** [comment]
AE will not and cannot pull cells from a drive by itself.

You have to actively remove them by some means. But without a good description or maybe a screenshot, we simply cannot help you.

**Comment by KrazyChuck95** [comment]
I'm not sure if I can capture it taking the storage cells out but i can
screenshot that drive. I have another drive hooked on the same ME system
and it has no problems with the storage cells so far and it's hooked
directly to the drive that is having problems.

**Comment by thatsIch** [comment]
video would have been a possibility
