### ISSUE TITLE
Pattern Terminal Division sigil -> Iron infinite duplication

### ISSUE THREAD

**Issue by cjl1750** [AppliedEnergistics/Applied-Energistics-2#2065]
I am playing on the FTB Infinity evolved version 2.1.2 on expert mode. I discovered if you put a division sigil into the pattern terminal you can 'craft' it into iron an infinite number of times, the division sigil is not used up.

I tried to do the same with compressed cobblestone without success. I tried with a crafting terminal with no success. 

Applied energistics mod version: RV2-stable-10
Extra utilities mod version: 1.2.12

**Comment by wlhlm** [comment]
I cannot reproduce this. One Division Sigil yields exactly one Iron Ingot for me. Have you tried to actually pull the iron into your player inventory?

**Comment by cjl1750** [comment]
![1](https://cloud.githubusercontent.com/assets/3987766/11908236/87db388e-a5a8-11e5-92dd-a4111e864c7f.png)
![2](https://cloud.githubusercontent.com/assets/3987766/11908238/87dd9106-a5a8-11e5-9796-1cfeea8d5c8d.png)
![3](https://cloud.githubusercontent.com/assets/3987766/11908235/87dadf2e-a5a8-11e5-9813-51e8cf815cf1.png)
![4](https://cloud.githubusercontent.com/assets/3987766/11908237/87db50f8-a5a8-11e5-80c5-580909156780.png)


I have attached four screenshots of me reproducing this. In between each one I simple shift clicked the iron out of the pattern terminal into my inventory.

I am playing on a server on survival difficulty. I tried to reproduce this in creative in a single player world and could not.

**Comment by yueh** [comment]
#578
