### ISSUE TITLE
Meteors way too common

### ISSUE THREAD

**Issue by tenten8401** [AppliedEnergistics/Applied-Energistics-2#2067]
I'm the owner of IndustrialBox, and if you would hop on the public server you would see that meteors are way too common despite the configuration. I don't think AE2 is using the config for world generation at all.

**Comment by yueh** [comment]
Could you please be a bit more precise and provide some information about how common they are and what you would expect?

**Comment by DraksterAU** [comment]
@yueh Please check out my server, StargateMC.com if you would like an example :)
