### ISSUE TITLE
storage monitor shows incorrect number of coal blocks

### ISSUE THREAD

**Issue by rahangar** [AppliedEnergistics/Applied-Energistics-2#2068]
I noticed an issue today where the storage monitor is showing the same number of coal blocks as coal coke from immersive engineering.  This behavior is intermittent and seems to depend on the item (coal coke or coal block) that was updated last.  See the discrepancy between the storage monitor and the wireless terminal in the screenshot.   The wireless terminal shows the correct amounts.  In the background you can see the incorrect values: 7760 coal blocks and 7760 coal coke.

Version of AE: appliedenergistics2-rv2-stable-10

![2015-12-22_13 59 40](https://cloud.githubusercontent.com/assets/3137077/11964607/841af9be-a8b4-11e5-909f-cc68fe7a6d46.png)

**Comment by yueh** [comment]
Seems to work fine in my testsetup.

Could you please try to reproduce it in a smaller environment? (new map, as few mods as possible)
