### ISSUE TITLE
[Auto crafting] If items are present, ME will not craft.

### ISSUE THREAD

**Issue by xiurobert** [AppliedEnergistics/Applied-Energistics-2#2070]
I setup a small system for the automation of processors. I also setup about 60 molecular assemblers.

One day, I ordered about 40 engineering processors. It showed me that it had 360 diamond essence (Magical Crops) available and wanted to craft 40 diamonds. However, the craft button was grayed out. I checked and I do have enough diamonds as well as enough crafting storage, but it just refuses to craft it. What is going on?

AE2 rv2-beta-28 SkyFactory 2.4

**Comment by wlhlm** [comment]
Does your crafting CPU have enough RAM?

**Comment by yueh** [comment]
#1036
