### ISSUE TITLE
Not able to autocraft

### ISSUE THREAD

**Issue by Mouro001** [AppliedEnergistics/Applied-Energistics-2#2071]
I am on a online server with the SkyFactory 2 modpack and i automated illuminated panel,
but when i try to make one appears this:
![screenshot](http://prntscr.com/9ichdp/direct)

i really dont know what is going on..
this is my setup:
![another screenshot](http://prntscr.com/9icjgf/direct)

i have all items for making the panel:
![another screenshot](http://prntscr.com/9icka9/direct)
![another screenshot](http://prntscr.com/9icki9/direct)
![another screenshot](http://prntscr.com/9ickmv/direct)
![another screenshot](http://prntscr.com/9icks2/direct)

**Comment by Mouro001** [comment]
i removed the auto recipes from glowstone and quartzglass and:
![](http://prntscr.com/9iclme/direct)

**Comment by XFactHD** [comment]
Which version of AE2 are you using?

**Comment by Mouro001** [comment]
SkyFactory 2 (2.4)
appliedenergistics2-rv2-beta-28

**Comment by Mouro001** [comment]
I was looking into closed issues and i tried to disconnect all Storage Bus that i had. I was able to craft but when i put back the craft to glowstone and quartzglass stoped working

**Comment by XFactHD** [comment]
That version is extremely old, update the mod yourself or ask the modpack author to do it.

**Comment by Mouro001** [comment]
https://www.atlauncher.com/pack/SkyFactory

**Comment by XFactHD** [comment]
I know the modpack, but nonetheless you need to reproduce this with the latest version of AE2 (rv2-stable-10/rv3-beta-1).

**Comment by Mouro001** [comment]
i will try ask the server owner to give me download of my island.

**Comment by profrags** [comment]
Have you tried this in single player or with a small ME system using ONLY this auto craft? I had issues with auto crafting before so I redid my wiring and it was much better after, if you would like I can test this myself on the server myself later or tomorrow.

**Comment by Mouro001** [comment]
No, i just checked with the crafting recipes of glowstone and quartzglass, and with storage bus connected and not connected to a DSU with cobble.

**Comment by yueh** [comment]
We cannot provide any solution as long as you do not update to the most recent version of either rv2 (stable-10) or rv3 (beta-2).

**Comment by Mouro001** [comment]
Yeah i know.. im asking one of the servers owner if he can give me my island to download so i can update AE to test that

**Comment by yueh** [comment]
We will reopen it, if this persists after you updated AE2.
