### ISSUE TITLE
Interface issue

### ISSUE THREAD

**Issue by tebruuls** [AppliedEnergistics/Applied-Energistics-2#2076]
I tried to automate inscribers with ae and Steve's factory manager. My setup has 2 chests, the output chest and input chest. There is an interface on the input chest, connected to the main system. There is an item conduit sucking all items out of the output chest into the interface to go into the main system. There are recipies in the interface for silicon press, and 6 other circuits(printed and finished). The sfm system is set to always pull the incoming items out of the input chest into the 5 different inscribers(3 for printed, 1 for finishing, 1 for silicon ). Then it outputs the products into the output chest. In another part of the system, there is an interface with a storage bus attached that keeps 8 of all three finished circuits stocked.

I'm pretty sure that's a complete summary, and I think it should work, but it doesn't always. What happened is when I first turned it on, there were 8 logic, 8 engineering but only 2 calculation. So what happened is it requested 6 calculation. The crafting cpu at first shows it crafting the prints and the finished circuits, but it only actually crafts 1 finished circuit. It crafts all the prints though. I have to click cancel in the crafting cpu, then it requests 5 more, and the same thing happens where it only crafts 1. 

I looked in the input chest, and it is only pushing 1 set of ingredients into the input chest, instead of all sets. All the required components are stored on drives in the main system. It's not a problem with the sfm system because it works fine if I put the items into the input chest myself.

Anyone know what's happening? I can't figure it out. I'm using the newest version of ae2.

**Comment by yueh** [comment]
Sounds like the usual issue of not inserting the products back into the network requesting the autocrafting. The safest option is to insert it back into the interface as the one holding the pattern, but any interface on the same is sufficient

**Comment by tebruuls** [comment]
The products are being inserted into the same interface with the patterns. Another thing that happened is in the stock keeping setup, it was holding 7/8 and requesting 1 more but in a terminal there appeared to be 11. I have a couple subnetworks in the system, but all they have in them is full barrels. I can take the 11 circuits out manually just fine also.

**Comment by thatsIch** [comment]
Maybe showcase in a minimal setup in a picture

**Comment by tebruuls** [comment]
I went into the interface and changed the push items mode, then changed it back and it works. Bug?
