### ISSUE TITLE
Hidden terminals for cosmetic effects

### ISSUE THREAD

**Issue by minenine** [AppliedEnergistics/Applied-Energistics-2#2077]
I had a idea while i was playing on a server. my base is a underground laboratory and i have ME wires and terminals on walls in almost every room. but what if they where in the floor or still in the wall but just not seen tell you walked up to them? My idea is that there are terminals and other misc things that you can put on almost any surface but hidden in the wall or floor or whatever you put it on, even the ceiling. Then when a player gets in say a 3 block radius of this terminal (for players with ME access in the ME security terminal only) it pops out of the floor ready for you to use the ME system.

**Comment by yueh** [comment]
Could be an idea, but it seems to be a bit out of scope for AE2 itself as there are couple of issues with it.

First it would make the rendering even more complex and thus a 1.8 port also more difficult. So something to avoid.
Secondly most parts are render staticly once per chunk refresh, but this would require them to be rendered dynamically and making it a bit slower and affecting every frame. This will slowly add up and decrease the performance overall. Especially with many parts acting like this. Thus it will affect any player in a slightly negative way, even when most are not using it.

Maybe it is better suited for a small AE2 addon mod? Or one of the existing mods which cover a similar usecase could maybe provide one?

**Comment by minenine** [comment]
i agree it's not something that would fit the range of "vanilla" AE2 but a add on would be perfect so people can chose to have it if they want.
