### ISSUE TITLE
many craft disable by Mekanism last version 

### ISSUE THREAD

**Issue by Hunikyel** [AppliedEnergistics/Applied-Energistics-2#2078]

**Comment by TheJulianJES** [comment]
So you mean that many crafting recipes from AE2 are disabled by the latest version of Mekanism or do you mean that many crafting recipes from Mekanism are disabled by AE2?

**Comment by Hunikyel** [comment]
recipes from ae2 are disabled by mekanism, I have the last version of Ae2, I try last and first version of mekanism it s same, i try to remove integration in cfg, same again.

**Comment by TheJulianJES** [comment]
I'm not an AE2 dev but I think that #1061 could be releated to this.

**Comment by Hunikyel** [comment]
install rv3 beta solve it.

**Comment by TheJulianJES** [comment]
So installing the latest version fixed your issue?
