### ISSUE TITLE
Terminal GUI closes when trying to type into search field

### ISSUE THREAD

**Issue by Xolroc** [AppliedEnergistics/Applied-Energistics-2#2081]
When using a standard ME terminal (haven't tried with others) configured for auto-search (*not* NEI-sync), trying to search doesn't work as expected. It's mostly functional, but pressing the T key while typing, if the mouse is over an item in the terminal, either doesn't do anything or simply closes the terminal altogether. I suspect this is related to T being the talk button, and maybe something isn't properly intercepting keystrokes for typing rather than control? It works fine when the mouse is not on an item, though.

This is in FTB Infinity Evolved v2.2.2.

**Comment by yueh** [comment]
#1151
