### ISSUE TITLE
Spatial Pylons glowing read even though I have apple power and set them up in the proper arrangement.

### ISSUE THREAD

**Issue by lokiwolf** [AppliedEnergistics/Applied-Energistics-2#2082]
I don't understand what's going on here, but even though i've set my pylons up in a rectangular arrangement and have more than enough energy thanks to big reactors, the pylons still glow red. It's not even as if the room I've set them up in is that big, so I have no idea what is going on here. All of them are plugged in.

**Comment by yueh** [comment]
#440
