### ISSUE TITLE
Server module crash with rv3-beta-2

### ISSUE THREAD

**Issue by walkerjonny** [AppliedEnergistics/Applied-Energistics-2#2083]
I got this server module crash at loading an existing world:
http://pastebin.com/nPSuPEG5
Maybe you have an idea how to fix it.

**Comment by yueh** [comment]
This makes no sense as something is requesting the server to stop while it is actually starting.

Is this really the complete log? Not that something else did crash earlier and we are just affected by it.

**Comment by walkerjonny** [comment]
I think you're right. 
It happens sometimes on world loading that the server does not start properly, stops then and the main menu comes back again. I have to restart the game in that case.
In this case I tried to load the world again after the server module stopped as described.
I checked the log file but there was no usable info for the former server start/stop.
This error came up at the second server module start/stop.
You're free to close this issue as it is possibly not the real cause in the first place.
