### ISSUE TITLE
an idea: why not add a terminal to put an item stack to an interface remotely? 

### ISSUE THREAD

**Issue by yuyuyzl** [AppliedEnergistics/Applied-Energistics-2#2084]
for example i need to put 32x diamond to the macerator, and i don't want to add a recipe in the ME interface because i only need to do it once. so, instead of get 32 diamonds from the terminal, run to the macerator, put it in, and get 32 dust from the terminal, can we have something like "advanced interface terminal" that allow you to put an item stack to the macerator via an interface remotely? then i can stand in front of  a wall of terminal and have access to all of my machines in the network.
and thank you for reading such a long passage XD

**Comment by yueh** [comment]
#50, #204
