### ISSUE TITLE
Autocrafting industrial steam engine with wireless terminal causes crash

### ISSUE THREAD

**Issue by Pieftw247** [AppliedEnergistics/Applied-Energistics-2#2086]
http://pastebin.com/4657rcLP
Single Player
expected industrial steam engine to be crafting
reproduction rate-10/10
ae2 version-rv2.stable build 10

**Comment by yueh** [comment]
This is a crashlog about NEI while trying to cheat in an item, nothing related to AE2.

**Comment by Pieftw247** [comment]
posted the wrong log whoops
