### ISSUE TITLE
OC P2P odness

### ISSUE THREAD

**Issue by XFactHD** [AppliedEnergistics/Applied-Energistics-2#2087]
If I try to crash my OC computer with a "no such component" error by disconnecting the me cable in the back of the P2P, the P2P goes offline but the OC network is not disconnected and the OC computer still gets updated data. Any ideas @fnuecke?
AE: rv3 beta 2
OC: 1.5.20

**Comment by yueh** [comment]
Looks like the tunnel is never handling being disabled/removed and updating the OC connection accordingly. They simply create a connection and go to sleep forever.

I do not really know the OC API, so @fnuecke should really look into it.

**Comment by fnuecke** [comment]
Yeah, I'll have a look. To clarify, the connection gets established via the tunnel, but when the tunnel goes offline, the OC subnets on either side of the tunnel stay connected?

**Comment by yueh** [comment]
You might also want to look into `PartP2PTunnel#onTunnelConfigChange()` and `PartP2PTunnel#onTunnelNetworkChange()` to establish the connection instead of ticking the tunnel.

**Comment by XFactHD** [comment]
@fnuecke What I did was that I connected 21 OC P2P tunnel to my network, then I saved the settings from one P2P and loaded them into the other 20 P2P tunnels. Then I connected all peripherals and the computer and started my program. As I wanted to change a variable and closing the program over touch doesn't work at the moment, I wanted to crash the OC computer with "no such component" by disconnecting the me cable from the P2P tunnel. The P2P tunnel went offline but the computer did still update the information from the peripherals.

**Comment by XFactHD** [comment]
@yueh onTunnelNetworkChange is overridden in PartP2POpenComputers.java and contains code to wake the P2P up but on onConnect and onDisconnect are overridden and are empty.

**Comment by fnuecke** [comment]
From what I can remember, the `onTunnelNetworkChange` schedules a tick because there were some scenarios where reconnecting didn't work properly when updating connections immediately. I'll have another look though, and also at `onTunnelConfigChange`.

The `onConnect` and `onDisconnect` are from OC nodes and should be irrelevant here.

**Comment by XFactHD** [comment]
Ah, ok, didn't know they were from OC.

**Comment by yueh** [comment]
Neither of these methods are overridden in [PartP2POpenComputers.java](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/main/java/appeng/parts/p2p/PartP2POpenComputers.java)

**Comment by fnuecke** [comment]
[`onTunnelNetworkChange` is](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/main/java/appeng/parts/p2p/PartP2POpenComputers.java#L105)?

**Comment by fnuecke** [comment]
See #2088.
