### ISSUE TITLE
Asscess Fluid Universe Terminal server crash

### ISSUE THREAD

**Issue by TheBlueKingLP** [AppliedEnergistics/Applied-Energistics-2#2089]
error log:http://pastebin.com/raw/d2WCWGZz
I am using Universal Terminal Fluid mode,on the normal fluid terminal no this problem,just the universal terminal crash my server.

Edit:some time not crash,just this error and kick me from the server: http://pastebin.com/raw/mNLEEb25

**Comment by XFactHD** [comment]
Please report this on the ExtraCells 2 issue tracker, the universal terminal is from EC2 and not from AE2.
