### ISSUE TITLE
Crash when pressing 'U' with NEI and AE2-rv3

### ISSUE THREAD

**Issue by GWYOG** [AppliedEnergistics/Applied-Energistics-2#2090]
I just only installed the latest version of NEI and AE2-rv3.beta build 3, and pressed ‘U’ to ask NEI for the usage of an item, then MineCraft crashed.
It seems that the same crash happens since AE2-rv3.alpha build 10, but actually I haven't seen the same issue here till now.....

Crash-report: http://pastebin.com/ZV8KJCX9
Forge client-latest-log: http://pastebin.com/515RuEYy

**Comment by yueh** [comment]
Which language are you using?

It looks like whoever did the translation messed with the string formatting.
But this is really something we cannot verify ourselves and have to trust the translators.

**Comment by Adaptivity** [comment]
from log file "Current Language: 简体中文 (中国)"(Simplified Chinese)

**Comment by 3TUSK** [comment]
Pretty sure @bakaxyf is still busy with school stuff, so I will handle it.

**Comment by GWYOG** [comment]
Yep, using Chinese. I've made a pr to fix the glitch, please merge it.

**Comment by bakaxyf** [comment]
I'm sorry for my mistake. I think it (https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/2092) can be marge now.
