### ISSUE TITLE
AE2 Won't Work!?!?

### ISSUE THREAD

**Issue by bmwools** [AppliedEnergistics/Applied-Energistics-2#2093]
When i try to load minecraft it says AE2 could not load and to check if it was installed correctly All my mods were all installed the same way and all the rest work. I know this because i tried it without AE2. I have the following mods AE2, Better Furnaces, Flans, Lucky Block, Superheroes Unlimited, TooMuchTNT, NEI, Rougelike Dungeons, and Iron chests. If anybody could help that would be great!

**Comment by yueh** [comment]
Post the actual log or error message, without it we cannot really help.

**Comment by bmwools** [comment]
I have fixed the problem and it is working fine, but thanks anyway.
