### ISSUE TITLE
Producing certus quartz crystals

### ISSUE THREAD

**Issue by TarakanE** [AppliedEnergistics/Applied-Energistics-2#2096]
Hi!
In the last time I started to notice that I'm running out of certus quartz crystals. If there is any way to produce/craft it? 
My mods:
minecraft 1.7.10 
ae2 - rv2-stable-10
biomes'o plenty - 2.1.0
buildcraft - 7.0.23
ic2 - 2.2.676 experimental
forestry - 3.6.3.20
projectred - 4.7.0
thermal expansion 4.0.3
thermal dynamics - 1.1.0 

Thanks for reading!

*quantum bees are not available in my version

**Comment by yueh** [comment]
Certus quartz is simply an ore like many other resources. So the only way to produce more, is to mine more.
