### ISSUE TITLE
Rv3-Beta4: CraftingPattern substitution mode

### ISSUE THREAD

**Issue by Namikon** [AppliedEnergistics/Applied-Energistics-2#2098]
We just updated to Beta4 today, and now almost half of all encoded patterns do not recognize the tools to craft with.
It might be related to GregTech, but I don't want to call it a "bug". Once the patterns are re-encoded with the substitution flag set to true, everything is back to normal. So I assume, that the substitution mode was the default behaviour prior to this addition, and therefor should be the default setting for all previous encoded patterns once they get their NBT tag migrated.

I assume most people won't even bother about that, but for some people on our Server, with almost 400 encoded patterns, this caused some trouble today

**Comment by yueh** [comment]
This is already mentioned in the changelogs of the specific build as well as the rv3 release notes.
