### ISSUE TITLE
Crash when placing AE2 Pressure P2P against PneumaticCraft Aerial Interface

### ISSUE THREAD

**Issue by XFactHD** [AppliedEnergistics/Applied-Energistics-2#2099]
See https://github.com/MineMaarten/PneumaticCraft/issues/793.

**Comment by yueh** [comment]
Seems to be a very rare bug when the P2P Tunnel recieves a neighbor update before it was validated.

Currently we have no way to determine, if it is valid. Thus we need to track it our side with all potential issues that might cause, like when changing its internal state without us being able to observe it.
