### ISSUE TITLE
Logistics Pipes Integration

### ISSUE THREAD

**Issue by AlgorithmX2** [AppliedEnergistics/Applied-Energistics-2#21]
Was in AE1.

Originally Posted by AlgorithmX2

This issue was migrated; For original details see http://ae-mod.info/Tracker/0192/

**Comment by Ioandar** [comment]
LP -> AE2 does actualy work fine via ME Interface...

I would very much like to use AE2 again but without LP integration I find it hard to peek/migrate (I am an old LP dog and having some trouble learning all the cool new tricks AE2 has to offer)

If you could find some time to make the request-pipe work again on the ME-Interface it would be great!

cheers and tyvm

**Comment by Drethic** [comment]
Has this integration made it onto the Roadmap and/or had an estimated release date assigned to it?

**Comment by thatsIch** [comment]
All features have no high priority, before not most critical bugs are not fixed. Adding new features, while other bugs are not fixed, will only lead to more inconsistent behavior and harder to track.

If you feel the need, to have this feature earlier, you are free to make a PR and suggest it to us.

**Comment by Drethic** [comment]
Are there any developer docs that would point me in the right direction to start the integration?  I found what looks like the AE 1 integration comment in Applied-Energistics-2/src/main/java/appeng/transformer/asm/ASMIntegration.java on line 60.  However, I don't see where you've integrated with mods like Jabba with the storage bus.

**Comment by thatsIch** [comment]
JABBA is an instance of `IDeepStorageUnit` of MFR

**Comment by NEXUS2345** [comment]
Would really like to see this added sooner or later, at least the ability to request from the ME system

**Comment by SharkWipf** [comment]
Took me a while to figure out it didn't work because of a bug. Guess I'll have to make room for a quantum network bridge after all.
Would love to see this (re)implemented sooner or later though.

**Comment by ruifung** [comment]
Any progress on this?

**Comment by loordgek** [comment]
lp is skipping 1.8
and i need it because ae2 has stuff that lp does not have and the other way around

**Comment by thatsIch** [comment]
API for that

https://github.com/RS485/LogisticsPipes/blob/b616f29b749c2391bca8cf1b4a0be989bd432b18/common/logisticspipes/api/ILPPipeTile.java

since LP pipes are no BC pipes anymore, need to make own new stuff to wrap it up

**Comment by shadoxxhd** [comment]
any time frame for when this will be fixed?

**Comment by thatsIch** [comment]
had a somewhat working branch for that,
I had to do tons of modifications to the ME Interface to accept the LP pipes again and I was waiting for @yueh to finish his networking stuff before rewriting it all over again.

**Comment by thatsIch** [comment]
I require dependency work from @FireBall1725 until then this project is halted

**Comment by dna3e8** [comment]
I am watching for a fix to this.Thanks for the great work you have done to create AE! this is my first time with modded mc.  I have a large LP system - and Leaping to AE is a daunting so i was excited to see tutorials about them connecting.

**Comment by bosto2** [comment]
Any news on this?

**Comment by thatsIch** [comment]
I think the dependency issue was fixed in the meantime, not sure where to allocate my time though. Adding stuff or porting to 1.8.9

**Comment by Manuepolis23** [comment]
so what does it mean?

**Comment by thatsIch** [comment]
any work done in 1.7.10 is potentially unportable to 1.8/1.9 because of lacking integration or other problems like changed design structure.

**Comment by HadesDurin** [comment]
its been a few weeks since the last update and
i am currently still waiting for it and want to know if there is any progress made to this?
Sharing storage is what i used in 1.6.4 ae1-lp and since upgrading to 1.7.10 still waiting for it.

**Comment by xPucTu4** [comment]
If someone is interested:
https://www.bountysource.com/issues/4910249-logistics-pipes-integration

**Comment by secondfry** [comment]
Created a PR with solution.
Experiences same problems as in AE1 – needs inventory refresh in terminal on new items arrival.
Improvement over my old experience (IDK if it was ever fixed in AE1) – doesn't report same items in shared network twice.

**Comment by LukaPix** [comment]
are there old versions for 1.7.10 that can do it ?

**Comment by afloresescarcega** [comment]
@secondfry Would you still be able to publish this patch, unofficially, of course?

**Comment by secondfry** [comment]
`ExternalStorage` registry was removed, should I reimplement it or is it expected from other mods to implement MEInventoryHandler?

**Comment by secondfry** [comment]
Well, nvm, I will just make separate block which will combine ME Interface, LP Request and LP Provider pipe.
