### ISSUE TITLE
Multiple Security Terminals causes Quantum Bridge failure

### ISSUE THREAD

**Issue by Psithief** [AppliedEnergistics/Applied-Energistics-2#2101]
## Versions
- Applied Energistics 2 - RV2 - stable 10
- Forge 1.7.10-10.13.2.1291
## Issue

If a Security Terminal exists on both sides of a Quantum Link Bridge, that bridge connection cannot re-establish itself when the world is reloaded.
### Reproducing (Single-Player)
1. Establish a Quantum Network Bridge.
2. Place a Security Terminal and ME Storage (with some items) on side A.
3. Place a ME Terminal on side B.
4. Quit and re-load to show that the network establishes itself properly by testing the ME Terminal.
5. Attach a Security Terminal to side B.
6. Quit and re-load to show the ME Terminal shows no items (and does not initialise with "Device Missing Channel" if using WAILA).

Please make a note in the [ME Security Terminal](http://ae-mod.info/ME-Security-Terminal/) and [Quantum Network Bridge](http://ae-mod.info/ME-Quantum-Network-Bridge/) pages about this limitation.

**Comment by XFactHD** [comment]
This has nothing to do with the quantum bridge, the same happens if you connect two networks via a piece of cable. What I want to say is that you can't have two security terminals on one network.

**Comment by Psithief** [comment]
Is that so? Fair enough, but this is still not present in the Security Terminal page.

The main problem with this Security Terminal conflict is that it does not fail **immediately**, it appears to work until the ME network reinitialises on server load.

**Comment by XFactHD** [comment]
Why should it be written on the site? I don't see a reason why you would try putting more than one security station on one network.

**Comment by yueh** [comment]
The site also does not state that more than one will actually work. It address them always in singular and states that it is responsible for providing the security/permissions.
Thus adding multiple ones should be expected for them to fight over the network or cause other random things.

**Comment by Psithief** [comment]
We're not psychic. We need to be able to read this limitation in the docs. Relying on grammar on a single documentation page is dubious, considering no one expects to read perfect grammar on the Internet.

* Every other block can be attached to network in multiples except the security terminal, so the fact that two security terminals don't synchronise is completely unexpected.
* Also consider that, after employing a Quantum Bridge, an ME network can span much further than is practical to travel.

**Comment by mindforger** [comment]
let me throw in a thought: (ignore it if you think it does not fit in any way, but this crossed my mind when asking myself "why would you add a security stations on each side of an tunneled network")
-Multiplayer Server
-Multidimensional
-(All-Time-)Chunkloaders are forbidden for reasons
-Security Station is in Dimension X and several QNBs are set up to other Dimensions
-Dimension X gets unloaded
-All Subnetworks are now unprotected

**Comment by XFactHD** [comment]
If dimension X unloads, the network goes down and the sub networks do the same if they are using more than eight channels.

**Comment by mindforger** [comment]
but what if i go by, place a new processor and power and then access the (local) network? it would render the use of the security terminal useless ... only way i can imagine is NEVER storing anything outside the dimension which is probably a bit tricky to accomplish

**Comment by XFactHD** [comment]
Yes, that would be possible but you really can't take everything into account.

**Comment by yueh** [comment]
Frankly good or even perfect grammar is something you should expect when reading a documentation regardless of being on the internet, paper, or whatever else. Of course there can be errors, so it is our job to fix them when we someone reports them.

Up until now I cannot remember a single report about using multiple terminals per network. Thus it seems common sense and/or the existing docs is sufficient without having a line like "Limit 1 per network". I still think we should improve the documentation slightly, but not by adding this explicit statement. A bit reading comprehension should be expected.

Also relying solely on the documentation is a bad design decision, there should be at least some ingame feedback like additional security terminals not switching to active should another already exist.
This would of course necessarily affect chunkloading and the network might be splitted into multipe ones until fully loaded.

Regarding the reasons for multiple ones, you can easily replace "security terminal" with "controller" or any power system. If a controller gets unloaded, the whole network will shut down. Same when using a single power source and it gets unloaded and I doubt you will add a self sustained power source to every small network to achieve redundancy.
