### ISSUE TITLE
Dense Charged Quartz reported twice by /oredistribution

### ISSUE THREAD

**Issue by Guinaro** [AppliedEnergistics/Applied-Energistics-2#2102]
Dense Ores correctly creates a Dense Version of both Normal and Charged AE2 Quartz.
Only during reporting in Oredistribution I get a report 
[CHAT] §c !§r Warning: §cDense CertusQuartz§r has multiple variants generated:
[22:41:33] [Client thread/INFO]: [CHAT] §c - §rdenseores:block2@0
[22:41:33] [Client thread/INFO]: [CHAT] §c - §rdenseores:block2@1

A Nei dump from Ore dictionary shows the following
oreCertusQuartz	1xtile.appliedenergistics2.OreQuartz@0	appliedenergistics2:tile.OreQuartz	Certus Quartz Ore	false
oreCertusQuartz	1xtile.appliedenergistics2.OreQuartzCharged@0	appliedenergistics2:tile.OreQuartzCharged	Charged Certus Quartz Ore	false
oreChargedCertusQuartz	1xtile.appliedenergistics2.OreQuartzCharged@0	appliedenergistics2:tile.OreQuartzCharged	Charged Certus Quartz Ore	false

So oreCertusQuartz refers to both the normal AE2 Quartz as the Charged Version.

My config in dense ores is as follows.
    block_32 {
        S:baseBlock=appliedenergistics2:tile.OreQuartz
        I:baseBlockMeta=0
        S:baseBlockTexture=appliedenergistics2:OreQuartz
        D:denseOreProbability=1
        I:renderType=1
        I:retroGenID=1
        S:underlyingBlock=stone
    }

    block_33 {
        S:baseBlock=appliedenergistics2:tile.OreQuartzCharged
        I:baseBlockMeta=0
        S:baseBlockTexture=appliedenergistics2:OreQuartzCharged
        D:denseOreProbability=1
        I:renderType=1
        I:retroGenID=1
        S:underlyingBlock=stone
    }

Can something be done about this? In Config files?

Guinaro

**Comment by Guinaro** [comment]
Oh yeah forgot this:
appliedenergistics2-rv2-stable-10
denseores-1.6.2
forge 1.7.10-10.13.4.1558-1.7.10

**Comment by yueh** [comment]
We have no special handling for dense ores. (if that is even possible)
Thus if it generates duplicate entries, it is clearly their issue.

**Comment by Guinaro** [comment]
Dense ores is working correctly! I generates the correct ores both for charged and normal AE2.
It is actually the command oredistribution that attended me to the problem.
My game works correct. Also correct display of name on blocks in game.
The only problem is that oredistribution sees the dense ore Certus Quartz and dense ore Charged Certus Quartz as the same ore: Dense ore Certus Quartz. And nowhere mentions the dense version of charged certus quartz.
And I think it is due to the problem that there are 2 ore dictionary entries for oreCertusQuartz namely appliedenergistics2:tile.OreQuartz and appliedenergistics2:tile.OreQuartzCharged.

In all it is a minor issue and doesn't impact the game. I am currently implementing my Custom Ore Generation XML Files. I will report back later if necessary if I run into problems with Jabba as those barrels can merge different kinds of ore registered under the same name in the oredictionary into the same barrel. And I fear that this will be the case for dense charged and normal certus quartz ore.

Guinaro

**Comment by yueh** [comment]
Maybe.
We register it as both, because charged certus ore is still certus ore and if a recipe just wants any certus ore, it should be possible to use both.
But this is sometimes an issue when mods start to abuse the oredictionary to convert between different blocks/items or other things, which was never the intention of it. Just to have an easy way for recipes to use other mods ores/ingots/etc as crafting material.

**Comment by wlhlm** [comment]
To add to what @yueh said, Charged and normal Certus Ore both are registered as `oreCertusQuartz`. This has been changed for rv3, where Charged Certus Ore has its own entry. See #1588.
