### ISSUE TITLE
Icons disappear when scrolling down

### ISSUE THREAD

**Issue by sinterpad** [AppliedEnergistics/Applied-Energistics-2#2103]
Hello,

since our server updated to the new version of the 1.7.10 pack, my ae2 network is acting weird, i cannot use the letter "T" most of the time in none of the terminals, only after 2-3 letters it let's me type a "T", i checked if this could be my keyboard acting up, but outside the terminals my "T" works very good. it is also bound to nothing.

The second problem is that the icons of the items disappear, it is simply the icons, the numbers or the word "craft" is still there, and even the durability if the piece has it, just not the icons.
When i close and reopen my terminals. it keeps doing the same.

Everything is chunck loaded and in the same chunk, it has sufficient power has a capacitor bank with 6.000.000 rf connected to it. 
I tried to reinstall the modpack, relog, reboot, .... disconnected my network and reconnected all my machines, terminals, crafters etc one for one to see if it was a machine bugging, but that doesn't seem to be the case.

I have made a video of the problem, https://www.youtube.com/watch?v=eaY0RnYIK1M
Also don't mind the music xD

Greetings sinterpad

**Comment by mindforger** [comment]
to your letter "T" problem, open your inventory, hit NEI's Options and under Inventory remove the Keybinding for "T" (it's not listed in the default MC keybindings ... very frustrating to find out ...)

for the issue with the icons ... no idea, maybe it's and rendering issue as hitting the "T" key does fancy particles on any nearby inventory

**Comment by sinterpad** [comment]
Ok, thanks alot, the keybind issue is fixed, now i need to get my ae system back up again,
I have tried both with and without texturepacks and still gives the same problem

**Comment by mindforger** [comment]
i just read about your second issue and noticed something (maybe not) missing ... do you have any energy cells in your system?
the fact you have lots of power is irrelevant, if the internal buffer of the AE is too low! it will still fail to operate when there is lots and lots of movement in your system causing it to loose internally power.

can you reproduce the issue with a new world somehow? and if so, try to cut down some mods or post a modlist ... mybe somebody knows the culprit
also include the most exact version of your mods installed including AE2 sometimes it's just and bad render code in an old/broken mod version interfering with AE2

**Comment by sinterpad** [comment]
The issue is solved. The chunks around my base are corrupted. Now when i get to close to my base the client crashes instantly. Same with other people.
I how ever want to thank you for your response.


Verzonden vanaf mijn Samsung Galaxy-smartphone.<div>
</div><div>
</div><div>-------- Oorspronkelijk bericht --------</div><div>Van: mindforger <notifications@github.com> </div><div>Datum: 13/01/2016  09:03  (GMT+01:00) </div><div>Aan: AppliedEnergistics/Applied-Energistics-2 <Applied-Energistics-2@noreply.github.com> </div><div>Cc: sinterpad <jakkemondelaers@hotmail.com> </div><div>Onderwerp: Re: [Applied-Energistics-2] Icons disappear when scrolling down (#2103) </div><div>
</div>
i just read about your second issue and noticed something (maybe not) missing ... do you have any energy cells in your system?
the fact you have lots of power is irrelevant, if the internal buffer of the AE is too low! it will still fail to operate when there is lots and lots of movement in your system causing it to loose internally power.

can you reproduce the issue with a new world somehow? and if so, try to cut down some mods or post a modlist ... mybe somebody knows the culprit
also include the most exact version of your mods installed including AE2 sometimes it's just and bad render code in an old/broken mod version interfering with AE2

---

**Comment by djdarkstorm** [comment]
I have figured out the issue with the items disappearing but I don't know how to fix it

The problem is in your ME system, you have unknown items from forestry. Your inventory shows until you scroll to a point, yes? Mine too. When I get to the line with the forestry item, boom, everything goes clear except numbers and the word "craft." The solution I came up with was to filter the drives and salvage the none forestry items and then put the drives into a trash can, but there must be an easier way. Any server file savvy people here know where the files are stored that keep track of whats in your drives? If we could just delete the lines that have the forestry items in them, it would be fixed.

**Comment by djdarkstorm** [comment]
Ok, so I set up two ME systems, pulled drives from my original system to isolate which ones had the ghost items in them. Put the bad drives into one new system, took all the items I wanted to keep from said drive and ctrl+space+left clicked into my inventory and then dumped them into the clean drives in the second new system. Repeat until only the blank items are left on the bad drives. delete bad drives via trash can, put good drives back into original ME system. Boom, solved. It's tedious but it works.
