### ISSUE TITLE
Invisible Facades

### ISSUE THREAD

**Issue by Direcub10** [AppliedEnergistics/Applied-Energistics-2#2104]
Its awesome if there were facades that unless u had a network tool made cable completely invisible

**Comment by yueh** [comment]
Could you please elaborate why the current functionality to make facades invisible with the network tool is not sufficient?

**Comment by Direcub10** [comment]
No i meant like the entire cable is invisble not just the facades by default so u see nothing at all then when u have the network tool it shows it like it normally does. It would help with things like screenshots and just running cable where facading is not an option like when u run cables across glass windows

**Comment by Direcub10** [comment]
bump

**Comment by yueh** [comment]
I do not think that is currently possible, neither by AE nor Minecraft itself, as we do not use full block facades but one per side. Thus it would require to render the cable based on the angle you are viewing it. Like diagonally looking at a cable with one half using a facade and the other one not, it should still render half of it.

Maybe by abusing some alpha rendering, but that means they have to be renderer dynamically as TESR, resulting in a major performance hit. And probably no longer possible in 1.8 or later.
