### ISSUE TITLE
Energy cell loses charge when unloaded

### ISSUE THREAD

**Issue by jbensonism** [AppliedEnergistics/Applied-Energistics-2#2105]
Forge 1558
AE rv2-stable-10
IC2 2.2.810

This may not be a problem, but I wanted to report it. I discovered this when setting up my first MFE from IC2. I noticed that after connecting my AE2 energy acceptor to the IC2 power grid that my power was dropping when I first signed in after a short break. I did some testing and noticed that my tier 1 energy cells do not maintain their charge after being unloaded and must fully charge again. I wasn't sure if this is correct, but I would point out that the MFE from IC2 maintains its charge level even when unloaded. I feel like if this is correct, that I would not like to use the energy cells, because I will have several players on and off on the server and with a large AE2 network it will drain a lot of power from the other systems without a good reason each time they log in.

Sorry if this has already been reported/resolved, the only other issue I saw was about the acceptor itself losing charge, but in my case it is the energy cells, which hold much more than any of the AE machines on my network. I'm OK if all of the machines don't maintain their internal buffer, that would make sense, but shouldn't the cells be ok for long term energy storage? I don't have access to the tier 2 energy cells yet, so I haven't tested them to see if the same thing happens.

**Comment by yueh** [comment]
#997. But noone of us devs could ever reproduce it or anyone could describe a way to do it.

**Comment by jbensonism** [comment]
Maybe you misread? The energy cells lose charge, not the energy acceptor. To reproduce, just hookup a charged batbox to and energy acceptor to a fully charged energy storage cell. Then logout, wait a few minutes and log in. The batbox will be draining into the (empty) storage cell.

**Comment by yueh** [comment]
It is essentially the same. Reproducing it is not that easy, because what you describe is exactly what we have tried and it does not lose any energy.

**Comment by mindforger** [comment]
@jbensonism do you use any chunkloader? i know this is an old issue i am referring but maybe it's again related to chickenchunks chunkloader
@yueh just a curious question and no offense, did you ensuren in your tests the area is unloaded ? (regarding permanent loading of the spawn area? because i tripped over this when trying to reproduce my cobble compacting issue)

**Comment by yueh** [comment]
I would say leaving a singleplayer world should unload it.

**Comment by mindforger** [comment]
maybe you can test this with a server running in debug, most of such chunkloading issues were not reproducable in single player environments especially using chickenchunks stuff
and fastcraft also seems to do very funny stuff recently in SMP operation (f.E. stripping the worldObj from player when firing network packets)

**Comment by jbensonism** [comment]
Ah, I had fastcraft installed. I deactivated and retested. I think this may
be a problem with fastcraft.

On Mon, Jan 18, 2016 at 6:17 AM, mindforger <notifications@github.com>
wrote:

> maybe you can test this with a server running in debug, most of such
> chunkloading issues were not reproducable in single player environments
> especially using chickenchunks stuff
> and fastcraft also seems to do very funny stuff recently in SMP operation
> (f.E. stripping the worldObj from player when firing network packets)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2105#issuecomment-172512989>
> .
>



-- 
*Jeremy Benson* | Web Development Manager

<http://turnthepage-onlinemarketing.com/>
   206 SE 2nd Street
   Lee's Summit, MO 64063
   P: (816) 527-8371 <8165278371>
   C: (816) 804-1533 <8168041533>
