### ISSUE TITLE
My friend in my server can't take item from item terminal

### ISSUE THREAD

**Issue by TheBlueKingLP** [AppliedEnergistics/Applied-Energistics-2#2106]
just like the title,my friend can't take item from my me network,how can i fix it?

**Comment by wlhlm** [comment]
Your friend most likely has a [Security Terminal](http://ae-mod.info/ME-Security-Terminal/) attached to their network. This by default prevents everyone except the owner from getting items out of the network. Read the above documentation to see how to give access to your friend.
