### ISSUE TITLE
Autocrafting machine balancing

### ISSUE THREAD

**Issue by XFactHD** [AppliedEnergistics/Applied-Energistics-2#2107]
In my base I have 3 inscribers for the last step of every processor. If I request let's say 10 16348k storage cells from ExtraCells, which need about 22k logic processors in total, the complete load gets put on one inscriber instead of being splitted between them. The 3 inscribers are on 3 different interfaces to prevent the last set of ingredients being split between the inscribers, making the system stop. Although I doubt that this is a bug, it is pretty nuicant this way. Just to give some numbers, if nothing else is crafting and only one inscriber per processor is doing all the work, I would need about 5 hours or more to craft 10 16348k storage cells.
AE: rv3 beta 5

**Comment by yueh** [comment]
[Crafting Co-Processing Unit](http://ae-mod.info/Crafting-Co-Processing-Unit/)

**Comment by XFactHD** [comment]
Nope, the crafting CPU has 16 Co-Processors, so that's not the cause.
