### ISSUE TITLE
Custom Cell view

### ISSUE THREAD

**Issue by XenonRaite** [AppliedEnergistics/Applied-Energistics-2#2108]
Hi!
sooo how i do registered my custom item cell?

https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv2/src/main/java/appeng/container/slot/SlotRestrictedInput.java#L191

it is joke? 

case VIEW_CELL:
	return items.viewCell().isSameAs( i );

Why here not checked by some list for custom item view cells?

hmmmm.... HEEELP

**Comment by yueh** [comment]
Based on view cells using mostly internal classes, I would say it was never intended to allow custom ones.

**Comment by XenonRaite** [comment]
If you propose like as extends ItemViewCell
it`s still noty work
My item not have acceess to viewcellslot becose
.isSameAs( i );
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv2/src/main/java/appeng/core/features/ItemDefinition.java#L70
Platform.isSameItemType()
and here i see it 
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv2/src/main/java/appeng/util/Platform.java#L1866
that.getItem() == other.getItem()
it is not instanceof allways

Any idea?

**Comment by yueh** [comment]
As said, it is simply not intended to add custom view cells.

**Comment by XenonRaite** [comment]
mey be it`s fix it:

case VIEW_CELL:
    return iitemStack instanceof ItemViewCell;

I see many issues(from 2012) for ViewCell filtered by modid or any tag.
why it still not work? 
Features of the architecture?
