### ISSUE TITLE
Terminals not displaying item pictures - but displaying items. help!

### ISSUE THREAD

**Issue by djdarkstorm** [AppliedEnergistics/Applied-Energistics-2#2109]
Ok, so I run a server using the modpack "the 1.7.10 pack" on technic launcher and I have done so for about a year, using minecraft 1.7.10 as well. All so very smooth. Recently, the dev of the modpack launched version 0.8.2 of the mod, so I updated my launcher client side and updated the server as well, by copying my world info into the new server directory and the config files and launching. Everything worked perfect. Until I decided to go into my large and pre-existing ME system. Upon clicking on the terminal, everything appears fine for a few seconds. (maybe 3 seconds, tops) Then, all the images (thumbnails) disappear and the item counts and structure of my storage remain. They do not come back, you can only hover over the items to see the name of said items. 

The game has not crashed, so there is no crash report. The game log itself doesn't seem to contain any useful information - though I can upload it if needed.  

This issue is happening for all people on the server, regardless of what system they are trying to access. The issue does not exist if I start a fresh world, but as the world itself is fully intact, I would like to salvage this. Given that fact, I feel like the issue is with how I updated the server as it was my first time doing so - maybe I did something wrong. My friend on the server is convinced that it is being caused by a specific item being in the storage but given the fact that it is happening across any ME system (separate setups) and we all have different things, that seems really unlikely. 

I was hoping someone here would know what mod or what part of the game (or server folders) could interfere with just the thumbnails not displaying. Attached is a picture of the system working until I start to scroll down, and then two of it doing as I describe.
![showing](https://cloud.githubusercontent.com/assets/16702556/12372738/718c3928-bc2f-11e5-921e-3ed8f605d0e6.jpg)
![not1](https://cloud.githubusercontent.com/assets/16702556/12372740/7a2c4f28-bc2f-11e5-84cd-bac4f447334d.jpg)
![not2](https://cloud.githubusercontent.com/assets/16702556/12372742/7cc1a634-bc2f-11e5-8a27-5f0571cda081.jpg)

Thanks for any help possible or ideas or anything.I really want to play in the updated server, rather than reverting, but I am not willing to lose the world.

**Comment by yueh** [comment]
There is a similar issue with the same pack (#2103) and also limited to a existing world.

I would highly recommend talking directly to the modpack maker, as it seems to be something broke with the update.

**Comment by djdarkstorm** [comment]
I found the issue. There are uknown items from forestry mod in my ae system. is there any easy way to delete them from the game files?


________________________________

**Comment by yueh** [comment]
Not really. It is kinda a minecraft "feature" that you cannot remove items with metadata automatically. Just the ID itself.

But this is really something which Forestry should handle on their side. Like displaying a specific icon for outdated/non-existing metadata versions. Probably their whole itemrenderer is actually crashing due to it. But as we expect to deal with broken ones, we try to catch these and at least do not let the client completely crash.
