### ISSUE TITLE
Underground meteorite generation.

### ISSUE THREAD

**Issue by zclimber** [AppliedEnergistics/Applied-Energistics-2#2112]
Somehow a meteorite was generated underground at height about 50, in Thaumcraft magical biome. I think they shouldn't land like this))

**Comment by yueh** [comment]
This is intentional.

**Comment by wlhlm** [comment]
From the [wiki](http://ae-mod.info/Sky-Stone/):

> Meteorites spawn during world generation on the surface __or underground__ and vary in size. They generally contain a Sky Stone Chest which can contain various ingredients required for advanced technology. You can use a Meteorite Compass to locate meteorites near you and as you explore.
