### ISSUE TITLE
P2P RF not working after server reboot

### ISSUE THREAD

**Issue by mskurnik** [AppliedEnergistics/Applied-Energistics-2#2115]
I can confirm that the #1834 bug still exists. The P2P power ports do not come online until you enter the region in which the AE network is in. To test this I build a small p2p network with power flowing into a P2P RF via Cryo fluxduct/resonant and out into a tesseract. Over 1K away I connected that tesseract to a series of TE energy cells that power various machines. Power flows into them just fine but if I restart the server the power and join the server, the power is draining from the energy cells. These cells will not recharge until I go over to where the energy generation is.

This bug happens with MFR, ChickenChunks, and railcraft chunk loaders. What is strange is where the power is being generated I have a quantum ring and one where I am receiving power. The quantum ring works just fine. I can see everything on the network (which is powered by another energy source). That network has 42 P2P ME ports installed and all of those come online just fine. That means that the network is coming online but the P2P RF's just are not.

We have been experiencing this for 4-5 months now so it is something that has existing for some time.

AE2 RV3 Beta 5 with forge-1.7.10-10.13.4.1558

**Comment by yueh** [comment]
Duplicate
