### ISSUE TITLE
(bug) (major) Applied Energistics cant see contents of Logistic pipes storage

### ISSUE THREAD

**Issue by mrgreaper** [AppliedEnergistics/Applied-Energistics-2#2116]
Following guides to get applied energistics to connect to my logistic pipe network i built an interface, added a provider and requestor pipe but while the LP system can see and get the contents of the ae system, the ae system can not see the contents of the LP system
created a test world to make sure its not a quirk of my set up and same thing happened

Video of the issue : https://www.youtube.com/watch?v=qXdndHre1Pg
labled as major as i know the two systems are designed to work together (pretty much every guide i read and watched kept saying that repeatedly lol)

**Comment by yueh** [comment]
#21
