### ISSUE TITLE
F R: Memory cards keep displayName when settings are cleared.

### ISSUE THREAD

**Issue by Psithief** [AppliedEnergistics/Applied-Energistics-2#2117]
Memory cards can be renamed in the anvil, but the displayName is cleared if shift+right-click is ever used on air.

**Comment by thatsIch** [comment]
Imo intended, you generally want a fresh mememory card if you are clearing it.

**Comment by Psithief** [comment]
Mm, but how can one tell one memory card from another?

I have named memory cards simply `Memory card 1`, `Memory card 2`, `Memory card 3`. The names don't matter, it's the fact that one can tell them apart in one's inventory that seems most important.

With careful use, nobody actually needs to use the clear function. However, it is nice to be able to use it so one doesn't overwrite a device's settings by accident. After discovering I could rename memory cards, I essentially lost access to this feature.

**Comment by Psithief** [comment]
> Imo intended, you generally want a fresh mememory card if you are clearing it.

How about giving the user the ability to throw the memory card into any crafting grid by itself to get a stock version of the memory card? Keep the display tag for the normal wipe.

**Comment by XFactHD** [comment]
I would really like this way too. I have the same problem with my memory cards that are named after their source tunnel.

**Comment by thatsIch** [comment]
ok
