### ISSUE TITLE
OC P2P doesn't like being chunkloaded on a dedicated server

### ISSUE THREAD

**Issue by XFactHD** [AppliedEnergistics/Applied-Energistics-2#2118]
A few moments after leaving the rftools dimension (chunkloaded by MFR chunkloader), the game crashed with the following crash report: http://pastebin.com/YFfM2C5y.
AE version: rv3 beta 4

**Comment by yueh** [comment]
@fnuecke any idea?

**Comment by fnuecke** [comment]
Hmm, the only thing that can cause an NPE at that location is [the node's network](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/server/network/Node.scala#L38), and for that to be `null` after [the preceeding joinOrCreateNetwork call](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/main/java/appeng/parts/p2p/PartP2POpenComputers.java#L143) on the part's tile entity, that tile entity [would have to be invalid](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/server/network/Network.scala#L432). Assuming I didn't overlook anything and my logic holds up, that would mean `updateConnections` gets called for an invalid tile entity, which is probably not a good thing in general? The quick fix that's highly unlikely to break anything is to add a `&& this.node.network() != null` to [the preceeding `if`](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/main/java/appeng/parts/p2p/PartP2POpenComputers.java#L145).
