### ISSUE TITLE
[Feature Request] Different colour for P2P inputs compared to outputs.

### ISSUE THREAD

**Issue by Psithief** [AppliedEnergistics/Applied-Energistics-2#2120]
Nobody can tell the difference between a P2P tunnel input and an output because there are no visual cues. Can we have some sort of distinguishing feature when a P2P connector is the input vs. an output? Maybe just a colour or pattern change.

![2016-01-28_16 53 07](https://cloud.githubusercontent.com/assets/1124846/12639497/a841438c-c5df-11e5-8fd1-44c536e694c6.png)

**Comment by wlhlm** [comment]
#43

**Comment by Psithief** [comment]
Not really the same request, I only ask to distinguish the **mode** that the connector is in, not the frequency.

I would say the frequency deserves another solution, like a tool or UI.

**Comment by Psithief** [comment]
I see now that #43 is actually your bucket for all UI issues with P2P.
