### ISSUE TITLE
Missing Channel

### ISSUE THREAD

**Issue by TheBlueKingLP** [AppliedEnergistics/Applied-Energistics-2#2122]
why my all p2p channel say missing channel when i put the 9th p2p tunnel in my me network?it is dense cable

**Comment by mindforger** [comment]
`it is dense cable` ... sure, but is the dense cable connected to an controller? don't forget, ME blocks are acting as 8 channel cables too!

**Comment by TheBlueKingLP** [comment]
ok,that mean if there is no me controller, the dense cable only allow 8 channel?thx

**Comment by XFactHD** [comment]
An ad-hoc network without a me controller can always only handle 8 channels, no matter which cable you use.

**Comment by TheBlueKingLP** [comment]
ok
