### ISSUE TITLE
For 1.8 ?

### ISSUE THREAD

**Issue by qwertyazerty** [AppliedEnergistics/Applied-Energistics-2#2123]
Are you updating this for 1.8 ?

**Comment by wlhlm** [comment]
#1637, [1.8.9 branch](https://github.com/AppliedEnergistics/Applied-Energistics-2/tree/1.8.9-rv3)

**Comment by qwertyazerty** [comment]
It's going o be compatible with forge 1.8 1557 ? I need this on my 1.8 server
