### ISSUE TITLE
Feature Request: Search Bar Terminal Hotkey

### ISSUE THREAD

**Issue by KingMonday** [AppliedEnergistics/Applied-Energistics-2#2124]
Just a simple request for a hotkey to access the search bar in the ME terminals, similar to pressing 'f' in NEI. Basically, it would really be nice to just open the terminal, press f and start typing to search for what I need, instead of having to click the search bar.

**Comment by KingMonday** [comment]
Related:
It would also be extremely nice to be able to access the search bar in NEI while accessing the ME terminal interface as well.

**Comment by yueh** [comment]
You can change the mode to autofocus the search bar every time you open it.

Considering the issue NEI had with intercepting `t` and not forwarding it to the current GUI, it will similarly cause reports about "I need to press f twice to enter a single f".
Thus not really a good idea, also by considering that no additional requests exist for it.
