### ISSUE TITLE
Add way for user to get channel id for p2p tunnels

### ISSUE THREAD

**Issue by omglolbah** [AppliedEnergistics/Applied-Energistics-2#2125]
Currently I am having issues managing my p2p channels properly.
As far as I know there is no way for me to look at a p2p-interface and see what ID it has for comparison with other p2p-interfaces. I have to disconnect the source interface and look at which interface goes dark.

Could a simple mouse-over tooltip be added showing the channel ID? (hex hash-like value is fine!)

Perhaps an added feature to the network tool?

**Comment by XFactHD** [comment]
AE2Stuff adds a special tool that shows which p2ps ore connected to each other.

**Comment by thatsIch** [comment]
I remember my ae-sign branch.. damn

**Comment by yueh** [comment]
Mostly a duplicate of #43
