### ISSUE TITLE
Crash game when we use the trash of NEI from crafting terminal.

### ISSUE THREAD

**Issue by Bressack** [AppliedEnergistics/Applied-Energistics-2#2126]
1 -> Applied Energistics 2 + NEI must be installed.
2 -> In-game : Build : Basic Network AE (Drive with cell (1k, 4k, 16k or 64k), ME Controller, and (for exemple) 1 stack of cobble in the cell)
3 -> enable trash button of NEI and click on the stack of cobble in the cell. When you click, (For me and for a lot of friends) the game crash ...

**Comment by XFactHD** [comment]
What about posting the crash report via pastebin?

**Comment by yueh** [comment]
NEI bug as it tries to purge every slot it can find in the current GUI, even when they are similar to fake item slots (like the network inventory).

Nothing we can really prevent on our side.
