### ISSUE TITLE
Integrating power API into the 1.8 branch

### ISSUE THREAD

**Issue by chorman0773** [AppliedEnergistics/Applied-Energistics-2#2127]
This is not an issue but I would like to see a 1.8 version of ae2!!

**Comment by CitiesXL2815** [comment]
there AE2 for 1.8.9, But hasn't been released yet

**Comment by chorman0773** [comment]
OK Im working on a power system for 1.8 its coversion (for Referance) is 100 Watts - 1 EU. I can provide the basic classes for it, and I would like for it to be useable for AE2 in 1.8. It is soley for 1.8 and later.

**Comment by thatsIch** [comment]
Just provide a proper API for your energy system hosted on a proper maven setup (at best jcenter, mcentral or any other popular hosting)
