### ISSUE TITLE
Pure cereus crystal disappear every time 

### ISSUE THREAD

**Issue by chezpaul** [AppliedEnergistics/Applied-Energistics-2#2128]
I'm trying to grow pure Curtis Quartz with 5 growth chambers or whatever they are called. They are powered and online. I have my water. I can grow fluxes in the water. But I can't grow pure certus Quartz. I'll just watch it disappear after 2 mins. Bam gone. Every single time. I'm running rb2 beta 10 stable. Am I doing something wrong?

**Comment by chezpaul** [comment]
Sorry about the misspellings. I am on my iPhone and didn't read back

**Comment by mindforger** [comment]
please describe your design more clearly or acknowledge my assumptions:

5 growth accelerator surrounding 1 block of water, top face is open
you craft quartz seeds by combining the powder with sand 
and then drop the seed into the water
after 2minutes they disappear without changing their visual appearance(i.E. growing larger in 3 or 4 visual steps)!?#
did you ever took them out of the water inbetween to check their growth?
did you ever leave the area or relog and then return withing two minutes to check their appearance to change in any way?

**Comment by XFactHD** [comment]
The crystal seeds have special code to not despawn. Are you on a server? If you are, is the server using kcauldron or something similar and possibly plugins?

**Comment by chezpaul** [comment]
I do not work with seeds. I'm only trying to grow Pure Certus Quartz. I do have 5 accelerators with one in the bottom, they are all online. I can create a Fluix crystal from a cereus, a redstone and a nether quartz. But pure quartz just won't appear. I am on a KCauldron Server.
Here is my setup from a unrelated crash but it shows my setup.  http://pastebin.com/DQeY1FNs

Thanks for looking into this.

Plugins used are LWC, Worldedit, Worldguard, Prism, Multiverse, Core, Portal, Netherportals, Inventories, Vault, Serversigns, protocol lib JSONAPI, Essentials, Group Manager and  Clearlagg.

**Comment by mindforger** [comment]
that is the problem, you misunderstand how to grow them, you have to grind a normal certus/nether/fluix crystal to dust, craft it together wit sand to get seeds
those seeds are droppen into the watrer and grow over several visual states to pure crystals

**Comment by chezpaul** [comment]
My bad. I've seen two ae2 tutorials where people drop the fully grown certus quartz into the water and they transform into pure certus quartz. No seeds involved. 
Now how are they doing that?
I thought that was how you got a 2 to one ratio between pure and not pure. Hense the reason to get pure quartz.

**Comment by chezpaul** [comment]
Okay so I tried puting in certus seeds and low and behold, they all dissapeared.
Exactly like above!

**Comment by chezpaul** [comment]
Is there a setting I can change to make them never dissapear?

**Comment by mindforger** [comment]
well only choice is to repeat the test without using kcauldron then
can you add a screenshot of the setup?

**Comment by chezpaul** [comment]
Updated to rv3, beta 5 and it now works.
Everyone always dissing on Kcauldron but up to now, all my problems have never been KCauldron related.
Thanks for all the help.

**Comment by mindforger** [comment]
@chezpaul `dissing on Kcauldron` it is the same like fastcraft and optifine, they do "optimizing" stuff that is mostly obscure or even if open source still implemented in other ways or not behaving like "normal" forge ... maintaining compatibility is a major P.I.T.A ... so every guess on what is wrong is as precise as throwing a stone into the ocean to hit a seagull swimming in it without knowing where it is! And saying the seagull is swimming near a coast makes it extremly easier (like saying try without kcauldron/optifine/fastcraft)

by the way you can close the issue yourself :)

**Comment by chezpaul** [comment]
I totally get where you are coming from, only because it seems like all modders think this way.
All I'm saying is that my errors or crashes or game problems have always been recreated in my forge only test world. That's all.  ;-)
Thanks
I'll try to close this.
