### ISSUE TITLE
error in server tick loop

### ISSUE THREAD

**Issue by chanzie** [AppliedEnergistics/Applied-Energistics-2#2129]
this is rv3 beta 5 but the error is happening on all rv3 beta builds

http://pastebin.com/Xfst7Kq8

little more details on it: this is hapenning upon trying to start up a server, 

java is jre 1.8.0_65
forge is .1614

and complete server log is available if ya all want that as well...

**Comment by mindforger** [comment]
you posted to the wrong mod

`   UC**E** extracells{2.3.8} [Extra Cells 2] (ExtraCells-1.7.10-2.3.8b185.jar)

**Comment by chanzie** [comment]
ahhh tytyty
