### ISSUE TITLE
Ae Terminal no longer accepting certain items.

### ISSUE THREAD

**Issue by TubesCraft** [AppliedEnergistics/Applied-Energistics-2#2132]
Not sure when the disconnect happened but It seems almost random the things that will no longer store. Mining drill, The Ender sword, Apiary, Frames, slime sword, lots more all over the mod spectrum.

**Comment by thatsIch** [comment]
Cant help without a way to reproduce, 

IC2 items use metadata off the specified allowed range,
other than that check storage problems and/or energy problems.

Repond with valid hint to re-open issue
