### ISSUE TITLE
Pattern display issue in Interface Terminal

### ISSUE THREAD

**Issue by Keyarose** [AppliedEnergistics/Applied-Energistics-2#2133]
Couldn't find this reported already so here it is.  In rv2 versions the patterns in the Interface Terminal would show as what was encoded on them without having to hold shift.  In the rv3 versions they now display as Encoded Patterns unless you hold shift.  It was a lot easier to find a specific pattern with the old display method.  If this is an intended feature could a config option be added in to use the old way?
Current version: rv beta 5
Forge: 1566

![2016-02-05_09 52 34](https://cloud.githubusercontent.com/assets/1906772/12848241/0ef13618-cbef-11e5-81a8-701b0da2cba7.png)

**Comment by krakel** [comment]
With the last stable version rv2.stable build 10 (appliedenergistics2-rv2-stable-10) I always see the pattern. There is no shift key for encoded pattern. :(

**Comment by Keyarose** [comment]
I'm talking about rv3 beta 5, its not showing the pattern's result as my pic shows.  Unless I hold shift.

**Comment by yueh** [comment]
We did not change anything with the rendering and using shift or not.

I remember that some mods would cause it to break. Was it maybe DragonAPI?
Most likely any mod using a coremod.

**Comment by Keyarose** [comment]
Ah, I did add DragonAPI and related mods around the same time that I updated to rv3 beta 5.  So I guess that's probably it as none of the other mod's I updated around/since then caused the issue previously.

**Comment by krakel** [comment]
I have to apologize. I was testing this behavior with a pattern with the recipe for a pattern. My fault. In this case, both views are equal. Sorry.
