### ISSUE TITLE
Meteorite Whitelist not working for Galacticraft Planets

### ISSUE THREAD

**Issue by LukeSkywaIker** [AppliedEnergistics/Applied-Energistics-2#2135]
I´m not able to let the world generate Meteorites on GC Planets/Dimensions.

Versions:
Applied Energistics 2 RV3 Beta 4
Galacticraft 3.0.12.437

I already posted this on GC Github here: 

https://github.com/micdoodle8/Galacticraft/issues/2068

Result is early Versions of AE2 generated Meteorites on GC Dims.

I tried this with only ae2 and gc installed.

Config:

I:meteoriteDimensionWhitelist <
-28
-29
-30

Quote:
## 

appeng.worldgen.MeteoriteWorldGen.generate(fmlRandom, chunkX, chunkZ, world, chunkGenerator, chunkProvider);
## I have tested it in earlier AE2 versions and it worked fine.

Greets Luke

**Comment by AnrDaemon** [comment]
What "earlier versions" you've tested?
With rv2-stable-10 and GC stable(375) I can't get any meteorites to spawn anywhere.
Tested Asteroids and ExU Deep Dark in particular.

**Comment by LukeSkywaIker** [comment]
i dont know which one that was, my above post is a quote from the mentioned and linked issue (GC) above or here u have the link again:

https://github.com/micdoodle8/Galacticraft/issues/2068

i got some code which might help but i´m not able to compile a source to a jar.. :(

i still have this problem though. used a workaround where i completly turned of meteroid generation. 
then i used cofh to determine where skystone should be generated. (like it is a ore). some crafting recipes for blueprint, done.

greets

**Comment by AnrDaemon** [comment]
Can you please share your skystone def? I'm trying but so far unable to get anything sensible.

**Comment by LukeSkywaIker** [comment]
i use custom ore-generation with cofh core: 

http://teamcofh.com/docs/cofh-core/

in config\cofh\world\
u create a *.json file. 
this is mine:

https://gist.github.com/LukeSkywaIker/f3260bc288f01f86015b82fee3be425b

but u may need to change the dimensions at lines like these:

        "biomeRestriction": "none",
        "biomes": [],
        "dimensionRestriction": "whitelist",
        "dimensions": [
            -30, -2554]

and u may change lines like these, cause they describe which block cofh is allowed to overwrite with an ore. on overworld its minecraft:stone for example. this is for gc asteroid dim:

        "material": [
            {
				"name": "GalacticraftMars:tile.asteroidsBlock",
				"metadata": 0
			}
        ]

**Comment by AnrDaemon** [comment]
Yes, I'm using same one, thanks. It seems that "cluster" template is the most fool-proof one.
Let's not drag it any further into offtopic. Just wanted to thank you for your contribution.

**Comment by Natesky9** [comment]
I can't get meteors to spawn in the asteroids dimension, and I've hunted all over. AE2 in my pack is locked behind Galacticraft asteroids, and they don't seem to generate, even in the pocket garden.

My suspicion is that they stopped being able to spawn in these since it was changed that most, if not all meteors generate on the surface
