### ISSUE TITLE
Please help me create 'sealed ME cable' block in Galacticraft

### ISSUE THREAD

**Issue by radfast** [AppliedEnergistics/Applied-Energistics-2#2136]
Hi, in case you don't know me I'm the Galacticraft developer these days, working alongside micdoodle8 who is semi-retired from modding.

In Galacticraft we offer a few 'sealed' cables and pipes from other mods, so that these can pass in and out of the walls of space bases which need to be sealed to retain a breathable atmosphere.

How these sealed blocks normally work is that the item and block is registered in Galacticraft (the block name is [BlockEnclosed](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/blocks/BlockEnclosed.java)).  When placed in the world it creates a TileEntity from another mod.  For example [TileCableBus](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/main/java/appeng/tile/networking/TileCableBus.java).

We used to have this working with Applied Energistics around 2 years ago, but not recently and I thought it would be good to get it working again.

So currently the steps I am taking are:
* create a new [TileCableBus](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/main/java/appeng/tile/networking/TileCableBus.java)
* create an ItemStack cableGlass from the block with name ```appliedenergistics2:tile.BlockCableBus``` and damage value ```16``` which should be a Fluix-colored ME Glass Cable
* call [addPart(cableGlass, ForgeDirection.UNKNOWN, player)](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/main/java/appeng/tile/networking/TileCableBus.java#L242)

This is not working.  It actually causes the block to break.  :(

So what are the minimum steps I need to take to create a functioning TileEntity here?

**Comment by NoX-programer** [comment]
https://github.com/SleepyTrousers/EnderIO is already done this. Maybe you should learn how them done it? And if you really need that that functionality, try to not duplicate EnderIO's one, because of copy/pasting code is bad :)

**Comment by thatsIch** [comment]
maybe @yueh an idea
