### ISSUE TITLE
ME System and Thermal Expansion

### ISSUE THREAD

**Issue by Scheria** [AppliedEnergistics/Applied-Energistics-2#2137]
I was trying to set up my first ME system today and ran into a problem. As you can see [here](http://prntscr.com/9zzq3t) the interface terminal recognizes that there is a Redstone furnace attached but when I try to make a [recipe](http://prntscr.com/9zzqpe) for Iron ore -> Iron ingot it won't show up. The furnace is configured like [this](http://prntscr.com/9zzr3y) (if that is relevant). There is no visible connection between the pipes and I don't know why it isn't working. I was also hoping to make it Iron ore -> Pulverized iron -> Iron ingot but I wanted to figure this out first

Any help would be greatly appreciated and I can supply more info if needed. Thanks :)

**Comment by siasur** [comment]
In a processing recipe you have to define the result yourself. Just put a iron ingot on the right side in the Pattern Terminal.
