### ISSUE TITLE
Block Dissapearing breaks the ME System

### ISSUE THREAD

**Issue by Sheldor5** [AppliedEnergistics/Applied-Energistics-2#2138]
On our server (FTB Infinity Evolved 2.2.2) it sometimes happens that our ME System just breaks (devices offline). Everytime we fixed the system we encountered that some blocks (mostly the Energy Acceptor) dissapeared completely.

The only hint we have is that the Energy Acceptor is in a chunk while all other parts of the ME System are in another chunk:

http://imgur.com/ASlxJiY

**Comment by XFactHD** [comment]
If you have a security station, can you reproduce it without it?

**Comment by yueh** [comment]
#1074
