### ISSUE TITLE
End of file exception

### ISSUE THREAD

**Issue by white-nrdy** [AppliedEnergistics/Applied-Energistics-2#2139]
This may not be this mod, but I believe that it is. A while ago, I put like 20 storage cells, all with stuff in them into a satchel from Thermal Expansion and I crashed and got an EOF exception, and anyone who was near me couldn't get on because it would crash. We had to rollback. I don't have the log from it, since we wiped the server since.

**Comment by thatsIch** [comment]
Cant do much without the logs, never experienced the exception in AE2
