### ISSUE TITLE
Disabling facades in config file - Glass facade still shows in NEI

### ISSUE THREAD

**Issue by whitephoenix0** [AppliedEnergistics/Applied-Energistics-2#2140]
Image: http://i.imgur.com/ve4ViUq.png
I just disabled facades in the config. I went in-game to test it and a single facade was still showing.

**Comment by bookerthegeek** [comment]
iirc this is intended. It removes all but one facade and that one is randomly choose not every time you open nei.

**Comment by whitephoenix0** [comment]
Just tried it again. It was still glass.

**Comment by XFactHD** [comment]
It will always be glass. Could you give me the exact name of the config option.

**Comment by bookerthegeek** [comment]
Default config, line 185-189
````
    }

    facades {
        B:Facades=true
    }
````
