### ISSUE TITLE
Autocrafting issue/potential solution

### ISSUE THREAD

**Issue by schradieck** [AppliedEnergistics/Applied-Energistics-2#2141]
So i have noticed that i have an issue regarding using the autocrafting system with MACHINES that have a crafting grid, namely the galacticraft ingot compressor. i am using Applied-Energistics-Rv2-Stable-10

If i make a processing pattern that says to use 40 tin beside 40 tin to make 20 compressed tin i instead get 64 tin beside 16 tin in the machine, whereas i end up getting only 8 compressed tin back, with 48 tin being left in the compressor. which is a huge issue as not only do i not get what i needed, but the whole system clogs up due to this.

I'm guessing that this is because the interface bus Shift-Clicks with the items in a processing recipe without actually regarding how they were organised, which works amazing until you try to use it on a machine that either requires you to use the same item in multiple spots, or machines like the galacticraft ingot compressor which have full crafting grids, but use their own recipes separate from a vanilla crafting table.

I believe that a good way to go about this would be to add a third pattern type, alongside of "Crafting" and "processing", something say like a "Machine Crafting". basically a pattern type for when you have to use specific item layouts or the same item in two spots.

**Comment by yueh** [comment]
Way too complicated as we had to support a unique pattern for every single machine with a strange behaviour.

If the machine wants that the same items are placed in many different slots, it either has handle the distribution itself, as this will even be an issue with vanilla hoppers or other pipe mods.
Or it needs a side aware inventory and the player has to ensure that the items are correctly inserted from different sides. Usually done to make automation a bit harder to achieve or completely prevent it.
Something we should respect, if the mod author chooses it (Sometimes AE is even the reason for it)
