### ISSUE TITLE
[Question] Add support for connected textures?

### ISSUE THREAD

**Issue by 016Nojr** [AppliedEnergistics/Applied-Energistics-2#2142]
Would it be possible to add support for connected textures for the cable facades?

**Comment by wlhlm** [comment]
#740

**Comment by XFactHD** [comment]
In the referenced issue is always talked about some kind of API AE2 would need to provide. Why not use the Connected Textures Manager (CTM) that is provided by the chisel devs? Every Modder who wants his connected textures to work with AE2 would need to use that but the compat for AE2 is not the only use of it. Also, with that you would provide compat with Chisel itself as one of the biggest deco blocks mod.

**Comment by bookerthegeek** [comment]
So... 

Connected textures would require chisel to also be installed?

**Comment by XFactHD** [comment]
No, AFAIK, the CTM lib is an independent library that can be shipped like the RF API.

**Comment by mindforger** [comment]
in pointed out how the rendering hack that EIO is using works in https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/740
where they are placing fake blocks and hook the blocks corresponding render code to achive maximum compatibility
but i am not sure how this lib is working, is it a blockrenderer or will it also work when you have only a face of a block available? afaik this would need an TESR and as far as i understand those are baaaad when used pretty often

**Comment by XFactHD** [comment]
A TESR is really bad in performance when used for as many facades as people place.
