### ISSUE TITLE
Processing Pattern material turned negative.

### ISSUE THREAD

**Issue by babyblasphemy** [AppliedEnergistics/Applied-Energistics-2#2143]
Running FTB Infinity Evolved v2.3.5 meaning:
appliedenergistics2-rv2-stable-10
industrialcraft-2-2.2.804-experimental

Long ago, I made a processing pattern for IC2 Compressed Coal Balls
![](http://puu.sh/n39ta/adf810d25b.png)

While requesting an ultimate hybrid solar panel, I noticed that the CPU and Start button were grayed out. Investigating lead me to the Compressed Coal Ball recipe. Somehow it had turned to this:
![](http://puu.sh/n39zr/4b9be35710.jpg)
-1 Coal Ball = 1 Compressed Coal Ball?
Remaking the pattern fixed it, just not sure how the pattern got that way in the first place.

**Comment by XFactHD** [comment]
Can you reproduce this with the latest version?

**Comment by babyblasphemy** [comment]
Unfortunately not, as I have no idea what actually caused it.
None of my other patterns were affected, so I guess it's just a one off. Feel free to close this if there is nothing that can/needs to be done for this issue.

**Comment by yueh** [comment]
Probably once in a blue moon, maybe some bit flipping as it was saved?
