### ISSUE TITLE
null crash on banned p2p plates

### ISSUE THREAD

**Issue by adamsonich** [AppliedEnergistics/Applied-Energistics-2#2144]
if EU p2p plate is banned and I click with IC2 cable on p2p plate (not EU) client gets null-crashed.

**Comment by mindforger** [comment]
`client gets null-crashed` includes a crashreport or at least a log, please drop it on pastebin and hand out the link ;D

**Comment by adamsonich** [comment]
http://pastebin.com/9xaDY4zg

**Comment by mindforger** [comment]
can you recreate the issue with fastcraft not installed? (client only)
`    at fastcraft.a.o.a(F:86)`
`    at fastcraft.Hooks.t(F:147)`

**Comment by adamsonich** [comment]
http://pastebin.com/x59AyNpX
well, it's not fastcraft :(

**Comment by mindforger** [comment]
maybe https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1450 is related, but @yueh should maybe check that, you probably need either enable the bus again or update to rv3 channel

**Comment by thatsIch** [comment]
Can you define **banned**? Do you mean disabled? Can you please try out the latest version.

**Comment by adamsonich** [comment]
Yep, disabled. will try it

**Comment by yueh** [comment]
rv2 (or better minecraft itself) has some issues with disabling features after the world was created as we cannot reliably purge them from the world. Also features are not really intended to be changed after world creation.

rv3 will handle it better.
