### ISSUE TITLE
[Question] AE2 machines accepting power from Ender IO sources.

### ISSUE THREAD

**Issue by CyricV** [AppliedEnergistics/Applied-Energistics-2#2145]
In a custom pack I'm building it seems AE2 machines are able to accept power directly from Ender IO RF sources such as Capacitors and Photovoltaic Cells. This is without the use of a Power Acceptor, simply placing a Capacitor on top of an ME Controller causes the Controller to fill with power and become functional.

Has anyone else encountered an issue like this? I'm unsure if it's caused by AE2 or Ender IO or if there is simple a config value somewhere I simply need to set to false.

AE2 Version: rv2-beta-18

**Comment by mindforger** [comment]
afaik controllers act like acceptors by default, like you can also power a charger and the inscriber without an acceptor connected, except those do not emit AE2 power then ... yet i am unsure how energy cells act, maybe they accept power too?!

**Comment by XFactHD** [comment]
AE Energy Cells do not accept external power but for controllers this is intended.

**Comment by CyricV** [comment]
Hah! This is a fascinating coincidence, those are pretty much all the devices I used to test this. It may be a good idea to update the information on ae-mod.info to reflect this change.

**Comment by thatsIch** [comment]
This is on the "huh, that is odd" list https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/135
