### ISSUE TITLE
Mod Development with BaseActionSource

### ISSUE THREAD

**Issue by SonarSonic** [AppliedEnergistics/Applied-Energistics-2#2147]
Hey,
Wondering if someone might be able to help me out.
My mod 'Practical Logistics' integrates with Applied Energistics to display storage networks on screens.
[Example Video](https://youtu.be/-Ajn4Z7RdYE)

My actual question is what is the best way to use BaseActionSource to interact with Blocks, without having a Tile which implements IActionHost. Mostly because I thought it would be a good idea to utilise the External Storage handlers for my own handling of inventories to allow support for more mods without writing separate handlers. Currently ME Interfaces already work although I might not have implemented them in the best way....[ME Interface Handler Class](https://github.com/SonarSonic/Practical-Logistics/blob/master/src/main/java/sonar/logistics/info/providers/inventory/AE2InventoryProvider.java) using the block itself as the IActionHost

Also this my attempt at [External Storage](https://github.com/SonarSonic/Practical-Logistics/blob/master/src/main/java/sonar/logistics/info/providers/inventory/AE2ExternalItemProvider.java) so far

Thank you!

Forge Version : 1.7.10-10.13.4.1614
AE2 Version: Latest (rv3.beta build 5)

**Comment by SonarSonic** [comment]
Anyone? I still haven't been able to do the External Storage Handlers. Although I have changed the way I connect to networks, allowing for any block not just the ME interface. Just trying to work out how to get all External Handlers

**Comment by thatsIch** [comment]
Could you specify what you mean with `interact` since I do not fully grasp what you really want to achieve and how we can help you

**Comment by SonarSonic** [comment]
Thanks for getting back to me. What I really wanted to know was the most efficient way of reading all the items/fluids stored in an ME system from one block on the network. Here is what I'm using at the moment. https://github.com/SonarSonic/Sonar-Core/blob/master/src/main/java/sonar/core/handlers/inventories/AE2InventoryProvider.java#L66

This is called every tick to update the items. I basically just lifted some of your code.
