### ISSUE TITLE
Smart Cable doesn't show channel visualization

### ISSUE THREAD

**Issue by Nickoladze** [AppliedEnergistics/Applied-Energistics-2#2148]
Version is rv3-beta-5
Extra Cells 2.3.7 and Thaumic Energistics 1.0.0.1 are in the pack, but neither are in use in this network.

Smart cables do not show number of channels in Walia nor do they show lines: http://i.imgur.com/lp7eEoO.png

Dense cables work just fine: http://i.imgur.com/VTGuM2f.png

**Comment by XFactHD** [comment]
Does it work with the standard resource pack?

**Comment by Nickoladze** [comment]
Forgot I was using a resource pack. They do not work default: http://i.imgur.com/4znFvub.png

**Comment by thatsIch** [comment]
WAILA tells me, that you are pointing at a covered cable

**Comment by Nickoladze** [comment]
Oh wow, I got my cables mixed up. That's embarassing.

Please close.

**Comment by mindforger** [comment]
@Nickoladze do not want to embarass you again, but the close button is right beside the "comment" button :)

**Comment by Nickoladze** [comment]
how do i computer
