### ISSUE TITLE
Mod compatible with storage drawers

### ISSUE THREAD

**Issue by Dijkstra1** [AppliedEnergistics/Applied-Energistics-2#2149]
The storage drawers mod has item called compacting drawer witch main use is store item such as ingot but also allows you take items as nuggets and blocks only problem is when you connect it up to your me network and when you try to auto craft something that needs both ingots or nuggets or it knows how turn ingots in to nugget it see nuggets and the ingot and says that ok but when click craft it will not work as see the items need but when it goes to take it then realise it does not have enough of the other, it would be nice if something could be done so the ae networks knows that those are ingot as well so it need to craft more

**Comment by wlhlm** [comment]
This is a known issue and it seems hard to fix. Some information can be found in #1868.

**Comment by thatsIch** [comment]
There is nothing we can do there as long they virtualize all possible outcomes. This is the same as putting 2 storage buses on the same chest. With that you are actively breaking the system. 

Technically this could be fixed on their side by registering the storage drawer as a crafting unit and storage provider. Not sure if this is really realizable and/or feasable to do so.
