### ISSUE TITLE
system gets stuck on scedueled

### ISSUE THREAD

**Issue by mitcharoni12** [AppliedEnergistics/Applied-Energistics-2#2150]
(RESOLVED)
i have a server and i  have been doing ae2 to make things easier. recently i made a mystcraft world with tons of turbines to power my network and other thing. this world has a quantum link chamber in it and is linked with a quantum link chamber at my base. when i kept the mystcraft world chunk loaded that is when the problem emerged. it doesn't matter if i am in the mystcraft world or my world i cant auto craft anything because when i tell it to craft something or if it automatically crafts something it needs it gets stuck on scheduled. The weird thing it, if i tell it to craft something and it is scheduled, when i go to the mystcraft world it crafts it, that is the only way  i can get it to craft something. any help on this issue would be appreciated. i would be willing to let someone on the server to help me with the issue.

**Comment by vallard192** [comment]
You most likely need to change chunk loaders.

What chunk loader are you using?  The recommended chunk loaders are
normally Railcraft and MFR.

**Comment by bookerthegeek** [comment]
RotaryCraft Chunk loaders also do not have this issue.

**Comment by Meller127** [comment]
Also ChickenChunks works, have been using them allot lately. No problems so far. And a big+ is that they dont need any fuel to be running.

**Comment by vallard192** [comment]
Maybe ChickenChunks has been updated, but there are a ton of issues on here
documenting where ChickenChunks specifically were causing problems with
AE.  I would hesitate to say they do not cause issues with AE unless
there's some confirmation somewhere of a code change that fixes the
previous issues.

Just for data, searching the issues for AE, there are 35 issues that have
had ChickenChunks mentioned in them.  This is the first one where someone
said ChickenChunks works.  (Including 6 days ago when @XFactHD confirmed
ChickenChunks causes issues).

**Comment by Meller127** [comment]
Hmm strange, i will do some searching

**Comment by vallard192** [comment]
I'm completely depending on a most likely unreliable memory for this entire
comment.  Has the possibility of being completely wrong.  With that said...

I seem to remember that many of the issues had to do specifically with AE
systems that resided in multiple dimensions from different mods (RFTools,
MystCraft, AE Spatial Storage, etc... not Overworld+Nether) paired with
server reboots.

I don't know that anyone actually has done any specific testing to recreate
the issues because they're normally fairly build specific and difficult to
reproduce in a minimal environment.

**Comment by Meller127** [comment]
I have noticed that in my setup, 2 points in the Overworld 1000 blocks apart and one point in "The last millenium" (this is 3 big ME setups with 100+ channel each) will behave like the issue reported here. If i put an interface on a machine and dont configure a input/output to that side (leave it blank). Then i get "stuck" import busses all over my ME network. Its easy to check from the Interface terminal, it will show up as "Nothing".

**Comment by XFactHD** [comment]
The problem with Chickenchunks chunkloaders is that they do not use the chunkloading system provided by Forge. As soon as a chunk unloads, the chickenchunks chunkloader causes the chunk to reload. This can mean that a tile entity didn't finish writing the NBT data when it needs to load it again.

**Comment by mindforger** [comment]
as @XFactHD stated, the most common issue with chickenchunks is not the "keep something loaded" it's more that they cause reloads sometimes (probably because the server forces them to unload at some point) 
and on loading the dimension or starting the server they cause issues with some mods reengaging their work from the state they were unloaded

**Comment by mitcharoni12** [comment]
im playing ftb infinity, there are no chicken chunck loaders in the pack
On Feb 19, 2016 1:48 AM, "mindforger" <notifications@github.com> wrote:
>
> as @XFactHD stated, the most common issue with chickenchunks is not the
"keep something loaded" it's more that they cause reloads sometimes
(probably because the server forces them to unload at some point)
> and on loading the dimension or starting the server they cause issues
with some mods reengaging their work from the state they were unloaded

**Comment by XFactHD** [comment]
I just looked at the mod list from FTB Infinity, ChickenChunks is in there: https://feedthebeast.atlassian.net/wiki/plugins/servlet/mobile#content/view/22315011.

**Comment by mindforger** [comment]
i was referring to @Meller127 
>>Also ChickenChunks works, have been using them allot lately. No problems so far. And a big+ is that they dont need any fuel to be running.

and what @XFactHD wrote

**Comment by mitcharoni12** [comment]
oh was not aware of that thank you

**Comment by mitcharoni12** [comment]
i haven't been able to play scene i have posted this and will probably be able to play tonight and i will try to trouble shoot the system with this info i have gained here. I will update the page if it worked or not and if it worked what the fix was.

**Comment by mitcharoni12** [comment]
using mfr chunckloaders right now, i was using a world anchor before btw.

**Comment by mitcharoni12** [comment]
Fix: make sure the quantum link chamber is not chunk loaded on both sides of the dimension.
(thanks to all who pointed out there was a problem with the chunk loaders.)

**Comment by XFactHD** [comment]
If the quantum bridges are not chunkloaded, the small network which is connected to the main network by the quantum bridges won't work.

**Comment by mitcharoni12** [comment]
did a little bit of testing, if the server loads and that other side quantum bridge is chunk loaded that is what causes the issue. when the sever is loaded  thats when you can go and load the bridge.
