### ISSUE TITLE
unlimited channels

### ISSUE THREAD

**Issue by TTLPcraft** [AppliedEnergistics/Applied-Energistics-2#2151]
can you please add an option for modpack creator to disable the channels or add a cable with unlimited channels?

**Comment by vallard192** [comment]
Is there are reason the existing config option doesn't work for you?

**Comment by TTLPcraft** [comment]
the existing config works, but i want that it only works with a me controller and the controller i cant find.

**Comment by vallard192** [comment]
Check out the change log here:
http://ae-mod.info/docs/rv2/release-notes/#config-option-for-infinite-channels

Note the following:
The config option will disable any channel related features, including ME
Smart Cable <http://ae-mod.info/ME-Smart-Cable/>, ME Dense Cable
<http://ae-mod.info/ME-Dense-Cable/> and ME Controller
<http://ae-mod.info/ME-Controller/> and any Achievements related to
channels.

There's a note there about using custom recipes.  There's no reason to have
a controller with infinite channels.  If you still want to be able to craft
the controller, then you need to add a custom recipe for it.

**Comment by XFactHD** [comment]
The controller has no use without channels and the smart cable and dense cable rendering won't work without channels.

**Comment by TTLPcraft** [comment]
i want to have it like in ae1

**Comment by TTLPcraft** [comment]
that a me system wont work without a controller

**Comment by vallard192** [comment]
That's not realistically implemented and probably won't be.  Off the top of
my head I would suggest that you use the custom recipes in order to require
controller blocks in order to build any of the storage blocks.

**Comment by TTLPcraft** [comment]
where i can make custom recepies?

**Comment by XFactHD** [comment]
In the config folder is a folder for custom recipes.
Also, the ad-hoc system with maximum eight channels makes complete sense and is awesome when you just start with AE. I have to say that I love the channels because they make you think over your setup but it doesn't stop you from making ginormous AE systems.

**Comment by MineProjectZ** [comment]
when i add the me controller to a recipe i cant craft the item and the controller is still not there
