### ISSUE TITLE
Chromaticraft ore and ME Annihilation Planes

### ISSUE THREAD

**Issue by Keyarose** [AppliedEnergistics/Applied-Energistics-2#2152]
Both the ME Annihilation Plane and the ME Identity Annihilation Plane will pick up Chromaticraft ore blocks(chromaticraft_block_teiredore), but nothing is stored in the system.  While the Planes might not be able to "see" the ore as something other than stone(due to chromaticraft's progression), there should at least be cobblestone or stone added to the system.

AE version: rv3 beta 5
Chromaticraft version: 10d

**Comment by bookerthegeek** [comment]
@Reika

**Comment by yueh** [comment]
Chromaticraft ore reports to not drop anything at all.
We will not start adding custom behaviour for specific blocks just because they might behave a bit differently.

Make a feature request for chromatic craft to report that it would drop something when being broken instead of nothing at all.
