### ISSUE TITLE
[Suggestion] Cables flash when data is accessed

### ISSUE THREAD

**Issue by Quartz101** [AppliedEnergistics/Applied-Energistics-2#2153]
I remember, in AE1 I think, where the cables would flash white inside them when data was sent over them. I miss that! Can you please add it back please, it made wires cooler!

**Comment by Mctitch-CraftSM** [comment]
I Agree this should most defiantly be added back into it, Perhaps make the specific channel flash for that device?

**Comment by mindforger** [comment]
keep it configurable .. i also remember the immense laggs ...

**Comment by XFactHD** [comment]
Making a specific channel flash is not possible because the lines on the cable are not associated to a specific device. I think only glass cable and the corners from covered and smart cable should flash.

**Comment by yueh** [comment]
#20, but most likely no as it is a major performance issue.

**Comment by Quartz101** [comment]
Make it a config option, disabled by default?
