### ISSUE TITLE
Whitelisting a storage cell with a mekanism gas tank does not work correctly

### ISSUE THREAD

**Issue by Silly511** [AppliedEnergistics/Applied-Energistics-2#2154]
Whitelisting a storage cell with a mekanism gas tank that has a specific gas in it cases the cell to accept all gas tanks, no matter what gas is in them. Using AE2 rv3 beta 5 and mekanism 8.1.7.252.

**Comment by XFactHD** [comment]
The gas storage cell is from ExtraCells, please report this to them.

**Comment by Silly511** [comment]
No its from mekanism

**Comment by XFactHD** [comment]
Oh, I thought you wanted to configure a gas storage cell with a gas tank.

**Comment by Silly511** [comment]
Never mind, it was an error in my setup.
