### ISSUE TITLE
applied energistics system randomly gets stuck

### ISSUE THREAD

**Issue by mitcharoni12** [AppliedEnergistics/Applied-Energistics-2#2155]
i have a applied energetic system without channels, recently it just randomly stops in the middle of crafting something and either gets stuck on crafting or scheduled, i dont have it linked to any other dimensions or anything it just randomly does it. and the thing i want to craft is purely made through the molecular assembler. im am getting really really mad because i have probably spent 5-6 hours of trouble shooting on this glitch. if someone knows why it is doing this could you please tell me how to fix it and why it fixes it

**Comment by vallard192** [comment]
What other mods are installed?
What are you trying to craft?

**Comment by mitcharoni12** [comment]
ok well it fixed itself but i know it will happen again if i try to use a quantum link chamber in another dimension that is chunk loaded(was trying to craft a 64k component) , do you know a way you can have a quantum link chamber loaded and not have it stuck on scheduled?

**Comment by Meller127** [comment]
Did you not fixed this problem from your last post? #2150

**Comment by mitcharoni12** [comment]
i would be fine with that, i think i should be able to play today but it wouldn't be till later in the day, if you could give me a Skype or something we could communicate privately with that would be great.
