### ISSUE TITLE
Skystone Chest rendering crash

### ISSUE THREAD

**Issue by BlakeBr0** [AppliedEnergistics/Applied-Energistics-2#2157]
A player of my modpack reported this to me. They were exploring and generating chunks and such and then were caught in a crash loop. I'm assuming this is because of the meteors that AE spawns in the world. 
In the modpack I have AE2 rv3-beta installed.
The crash log can be found here: http://minecraft.curseforge.com/projects/pickle-pack-magical-3/issues/16
If you need any more info let me know.

**Comment by yueh** [comment]
Looks like a corrupted world. Skystone chests can only have 0 or 1 as valid metadata.
But we should probably change the renderer to have a fallback instead of crashing.

**Comment by M1CR0H4CK3R** [comment]
Has this been looked into yet? I'm having the exact same issue, and I don't want to use a Map Editor to fix it manually.
