### ISSUE TITLE
[Feature Request] Spatial Storage Cell labeling

### ISSUE THREAD

**Issue by Leasara** [AppliedEnergistics/Applied-Energistics-2#2158]
I've been using storage cells to collect things from around the world and bring them to my base.  A village, a Jungle Temple, a Desert temple, ect.  As a result I've got some 6 empty Storage Cell dimensions sitting empty.  I'd like to delete those dimensions, but I'm uncertain which are mine and which are other people's.  As an OP on our server it'd simplify things if each drive was labeled with it's DIM number when it creates the dimension, maybe as a Lore tag.  Then users could just hand me the drive when they're done with it and I could delete the folder, saving us a few ticks and some time on backups.

It might also be an idea to allow users to label their own drives through a text box on the Spatial IO Port and maybe add that information to the DIM folder (DIM13 - Jungle Temple) in case that's simpler, it'd also allow users to organize their drives a bit easier. The name would change from [n^3 Spatial Storage Cell] to [User's cool thing]

**Comment by yueh** [comment]
You can name them with an inscriber/name plates or a vanilla anvil.

Displaying the dimension id might be useful.
The AE config keeps track of its used dimension, but I currently cannot remember, if you can use it to map between the cell and dimension in a reliable way (for ops)
