### ISSUE TITLE
Crafting stopped working

### ISSUE THREAD

**Issue by Berserker66** [AppliedEnergistics/Applied-Energistics-2#2159]
I've been playing with rv3.beta build 5 for a while, alongside Thaumic Energistics. All other mods are normal "Infitech 2" modpack.

A while ago, crafting jobs stopped working. When I go to start a crafting job, it gives me the gui for setting the amount of items I want to craft, but once I press next, nothing happens.

I looked into the logs and there's nothing at that timestamp.

The only hint I found, is that when loading the savegame, in the chat it says:
"ERROR: Error executing AE2.zs:
appeng.api.features.IInscriberRegistry.getRecipes()Ljava/util/List;"

It's the infitech 2 modpack, with thaumic energistics and ae2 updated to beta 5, because I needed "Feature #2091: Recipes using Ore Dictionary entry whenever possible. - Adaptivity"

**Comment by XFactHD** [comment]
This error comes from MineTweaker and has nothing to do with your problem.
