### ISSUE TITLE
applied energistics system dosnt work  when server boots up sometimes

### ISSUE THREAD

**Issue by mitcharoni12** [AppliedEnergistics/Applied-Energistics-2#2160]
sometimes when i boot up my server(ftb infinity) it just dosnt work at all except pulling items out manually and putting them back in manually.(i dont have channels btw). and when i mean nothing works i mean nothing with import or export buses work.i would be willing to let someone on and help me trobble shoot

**Comment by yueh** [comment]
Please read our [contribution guidelines](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/CONTRIBUTING.md).
