### ISSUE TITLE
Feature: Ability to show 'recently crafted'

### ISSUE THREAD

**Issue by sherkas** [AppliedEnergistics/Applied-Energistics-2#2163]
Im confused by this site so I hope this is the right place.

I love AE2, and honestly the only thing I would love to see added is after much automation and requesting of items... sometimes I forget what I requested? 

So I would love to see on the terminal a new button (but I would settle for a sorting option) where you can click it and see the last 10 items crafted. Not the components of a recipe (say if you finally had a tesseract auto crafted, maybe only show the 'final' recipe item crafted sorta thing). But a last crafted option would be absolutely sick. Even a start as just the last item crafted would be awesome too. No other suggestions other then much love for the mod.

**Comment by yueh** [comment]
There is not really a difference between the final and intermediate outpots of a job. So it would mostly track all of them as "recently crafted".

Keeping track of it and synchronize it to the client is also not that trivial and has a couple of pitfalls.
Like it would also report any stockkeeping, thus if the network is constantly crafting it will populate it constantly with these items.

For now no, but we should reconsider it should more requests appear for it.
