### ISSUE TITLE
Wireless Terminal power bugged?

### ISSUE THREAD

**Issue by cj89898** [AppliedEnergistics/Applied-Energistics-2#2164]
My Wireless Terminal seems to not be wanting to charge with anything except the Charger from AE2. I am running the modpack Project Ozone v1.5.4S. It will still drain my Flux Capacitor from Draconic Evolution. (Have not tested other capacitors)

**Comment by PiggyWhiskey** [comment]
That is a Project Ozone issue IIRC.

http://minecraft.curseforge.com/projects/project-ozone/issues/1785
http://minecraft.curseforge.com/projects/project-ozone/issues/1778
http://minecraft.curseforge.com/projects/project-ozone/issues/1799

**Comment by PiggyWhiskey** [comment]
Update: After doing some testing in the configs with AE2, the IC2 Power Ratio is set to "0" for that modpack.
Setting to anything other than 0, no matter how small, solves it.

Somehow this is causing the Wireless Terminal to require infinite power.

For the Devs to confirm,
Does AE2 convert other power units to IC2 before converting to AE power?

**Comment by yueh** [comment]
AE2 only uses its own energy (ae) internally.

But most tools/blocks accept different input power types. Therefore whatever powers them can choose which one it uses. Should IC2 power be the first one it tries and you use a multi of 0, it will basically dump infinite power into it without actually charging it.

**Comment by PiggyWhiskey** [comment]
Does AE2 convert between the different power sources? Or just to and from AE power.

I noticed with some config testing that EU = 0.00001 still drains the flux capacitor (and wireless terminal) very quickly. Expensive but maintainable.
Whereas EU = 0.1 is totally manageable with normal RF values being used.

The modpack (Project Ozone) doesn't have IC2 or any EU based mod installed.

**Comment by yueh** [comment]
As said, we only use our own power. But convert others to it.

If you use 0.00001 as multiplicator, it means you need 100,000 EU for 1 ae. And considering that most things in AE2 use at least 1ae/t or so, you should be able to do the math on how quickly it will deplete.

Even if the modpack does not ship IC2, some other mod might ship the IC2 Api (which in general is a very bad idea). But this would force every mod supporting EU to still leave their support enabled.

But this is really a modpack issue and not related to AE itself.

**Comment by cha0s** [comment]
This is still happening in All The Mods 3 on 1.12.2.
