### ISSUE TITLE
Level Emitter with crafting card does not stop emitting signal when crafting cpu is done

### ISSUE THREAD

**Issue by Safh** [AppliedEnergistics/Applied-Energistics-2#2165]
[EmitterTest.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/149925/EmitterTest.zip)

Attached world [using dw20 1.7.10 pack] has demonstration, request any number of green plastic and observe the crafting monitor count them down as they enter the network, then observe that when the monitor is empty and the job is complete, the level emitter is still emitting and the machine is still running.

I tried to add AE2 to a vanilla installation but couldn't figure it out, hope the modpack example is ok otherwise please let me know what mods I need to add to vanilla other than appliedenergistics2-rv2-stable-10.jar (which I copied from the dw20 pack).

**Comment by Silly511** [comment]
Can confirm on rv3 beta build 5.

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.15 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
