### ISSUE TITLE
Can't take/place anything in ME Crafting Terminal

### ISSUE THREAD

**Issue by DemonKitteh** [AppliedEnergistics/Applied-Energistics-2#2166]
I logged on one day and tried taking an arcane stone out of my ME Terminal (From Thaumcraft) Nothing happened, I can't click it, I tried removing and replacing my drive but i can't put the drive down unless i remove the ME Controller first, Same with the ME Glass cable (flux) and the terminal.

**Comment by XFactHD** [comment]
Do you have a security station? Try removing that.

**Comment by DemonKitteh** [comment]
Nope, i don't have a security station

**Comment by siasur** [comment]
could someone else placed a security station on your network?
