### ISSUE TITLE
[Feature] wireless crafting terminal

### ISSUE THREAD

**Issue by TheBlueKingLP** [AppliedEnergistics/Applied-Energistics-2#2167]
i just sugest add a item call wireless crafting terminal,i just like the normal wireless terminal,but it have a crafting grid

**Comment by XFactHD** [comment]
Please look at existing issues before making a new one. This has been requested and denied several times already.

**Comment by wlhlm** [comment]
#401

**Comment by TheBlueKingLP** [comment]
that long time ago

**Comment by SirFlip** [comment]
I think it would be a great thing to have. Of course there should be an option to disable it. So if the modpack editor doesn't want it can be disabled. If you think it would generally break the game mechanic it can be disabled by default so only people who are looking at the configs can use it.

**Comment by XFactHD** [comment]
If you really want this, make an add-on mod.

**Comment by SirFlip** [comment]
Well yes I had this idea but I don't have the skills for programming such a thing yet. But I am working on my Java skills.

**Comment by XFactHD** [comment]
Have fun!
