### ISSUE TITLE
Pattern terminal CTD's upon use

### ISSUE THREAD

**Issue by Trailblazer57** [AppliedEnergistics/Applied-Energistics-2#2168]
recently my pattern terminal ctds me and my crash report states 
"PM Description: Rendering screen java.lang.IllegalStateException: Already tesselating!"

http://pastebin.com/4Cazxp2P

all help would be appreciated.

**Comment by Trailblazer57** [comment]
Note I find this problem to be only on one of my pattern terminals...
the one i use the most... not sure why still.

**Comment by XFactHD** [comment]
Try removing the ExtendedRenderer mod and/or mpm.

**Comment by Trailblazer57** [comment]
to the aabove what is "MPM and i dont beleive i have an extended renderer mod and if i do i not know which mod is doing that.

**Comment by XFactHD** [comment]
MPM is MorePlayerModels. If you take a look at the mod list in the crash report you posted, you will find a mod called ExtendedRenderer and one called mpm. Try removing either one or both of those to see if they are the culprit.

**Comment by Trailblazer57** [comment]
Thank you MPM seemed o be the issue. shame i really liked that mod.

**Comment by XFactHD** [comment]
Report this to the MPM devs, maybe they can fix this.
