### ISSUE TITLE
Nether Quartz & IC2 Scanner+Replicator

### ISSUE THREAD

**Issue by DestroyFX** [AppliedEnergistics/Applied-Energistics-2#2169]
Hi,

I produce my nether quartz using a IC2 Replicator. It was working fine in RV3 Alpha3 but I have updated to the last RV3 Beta and now it take "infinite" UU-matter to produce a crystal. Also I can't put a Nether Quarts in the scanner, it's not accepted anymore.

I did not see anything related in the changelog so I assume it's a bug.

**Comment by XFactHD** [comment]
If this also affects nether quartz, then it is an IC2 bug.
