### ISSUE TITLE
rv3 beta 5 ore dictionary is not working?

### ISSUE THREAD

**Issue by cc2k** [AppliedEnergistics/Applied-Energistics-2#2170]
i have a ae system that works, tested it with sprucewood to spruceplanks crafting. but it does not work when i have checked the "ore-dict substitutions" and use a diffrent wood to get planks.
for ie: i want to crate planks but only have oak wood in the system and a crafting recipe for spruce wood planks.  if i understand correctly this should work in this build? or am i misunderstanding or doing something wrong?

**Comment by XFactHD** [comment]
This won't work because the recipe from wood to planks is no ore dictionary recipe, a specific wood will only give you the respective plank and nothing else.

**Comment by cc2k** [comment]
ah so it was wrong on my side.. ok thx :)
