### ISSUE TITLE
ME Terminal Search Box - DefaultSearch

### ISSUE THREAD

**Issue by FlashTech** [AppliedEnergistics/Applied-Energistics-2#2172]
Feature Request:

The ability to specify the default search text in an ME Terminal.

This feature could be applied to "Auto Search" and "Standard Search". Add another button (or upgrade) when these modes are selected to enable a text field (DefaultSearch). The DefaultSearch would be remembered like other options and every time you leave and access the terminal **instead of clearing the search field it would simply populate with the DefaultSearch**.

This feature would be similar to NEI Synchronized in that it only effects the Terminal Search text.

This moderately straight forward feature would resolve the desire for some custom default filtering that a View Cell can not handle, such as filtering by mod automatically at certain terminals. The abilities would overlap with a View Cell technically except View Cell can have fuzzy and inverted capabilities while DefaultSearch can filter by mod.

Example desires in my world: Terminal showing everything, Terminal showing Ores (do-able with View Cells), Terminal showing Thaumcraft items (do-able with DefaultSearch = @Thaumcraft), Terminal showing Botania items (do-able with DefaultSearch = @Botania), and more.

Edit: DefaultSearch should not be pre-populated and or a drop down with mods, that is way more complicated. This is just another search field that remembers its property like the other terminal options remember their state.

**Comment by XFactHD** [comment]
Remembering the search text has been requested multiple times and has because of the complexity always been rejected.

**Comment by yueh** [comment]
As already said, mostly too complex.

And it would circumvent view cells and that we always reject mod based filtering.
