### ISSUE TITLE
[Idea]: Creative ME controller 

### ISSUE THREAD

**Issue by mariodk** [AppliedEnergistics/Applied-Energistics-2#2173]
my idea for a Creative ME controller is 
with that you Remove the limit of Channels to be able to have infinte channels
i know there is a Config for turn off the channels 
but that config also removes the ME controller / Dense Cables / Smart cables and kinda want them still since they can be nice on some builds & for the looks
kinda want if turned of Channels in Config the ME controller Dense Cables / Smart cables  is still there & can be used but ME controller acts like a reskin of a energy acceptor & Smart/Dense cables acts like the normal cables if channels is turned off

so i was thinking why not a Creative ME controller
so no matter what cable is connected to that
That network will have infinite channels (it will not have infinite power & etc. just Channels)

so you can make a modpack that has Channels on Early game AE2
and a Super expansive repice(via minetweaker or something like that) for End game AE2 for that special ME controller to remove the channel limits
like a upgraded ME controller

**Comment by XFactHD** [comment]
That doesn't work because all the blocks, all the cables and everything else have a channel limit.

**Comment by mariodk** [comment]
i know that
but thats was what my idea was for to remove those limits if having that Creative ME controller in a network
ofc no crafting repice
but if a modpack maker will they can add it via minetweaker

**Comment by XFactHD** [comment]
That's not possible. The channel limits are hardcoded and can't be changed at runtime. This would also create immense lag. An example for that: You place a normal controller, place cables and then switch the controller to the one you are suggesting. The controller would have to run along all off the cables and switch the channel limit off on all of them. Getting a block in MC in the code can be bad on performance. Adding this controller would also remove the need for p2p tunnels and multiblock controllers.

**Comment by mariodk** [comment]
will it atleast be possible to Keep (if channels in configs is turned off):
ME controller multiblock: acts just like a energy acceptor but it looks nicer then a energy acceptor 
& Smart/Dense cables as kind of ReSkins of the normal/Covered cables if channels is turned off

**Comment by XFactHD** [comment]
I have to say that I am not one of the devs if AE2. I doubt that the devs would just add a functionality wise useless clone of an existing block just because of the appearance of those blocks. Just using the normal existing blocks is probably not possible. The smart and dense cables are even in terms of appearance completely useless without channels because nothing would light up on them.

**Comment by vallard192** [comment]
If you're just looking for the ME Controller look, see if you have Chisel 2
on your server.  They have a "Technical Block" that is very similar to the
ME Controller in appearance.

**Comment by progmanpaul** [comment]
There's a Chisel Futura Block that looks and acts and multi-blocks just like an ME Controller - for looks, no RF necessary. Used it on the question mark for an 8-bit Mario coin block, from a distance it looks legit.

https://drive.google.com/file/d/0B7fQZmQpNNqDMG5kUTJ4cEtZZm8/view?usp=sharing
