### ISSUE TITLE
[Feature Request] AE2 rv3 - OreDict Substitution

### ISSUE THREAD

**Issue by JasonMcRay** [AppliedEnergistics/Applied-Energistics-2#2176]
Would it be possible to have substitution for only certain items available in pattern encoding?
Example:
Lets say I have a mod that adds different color doors depending on what wood is used. In that recipe I also have a tool which can be created from diferent materials (the material dictates its durability). The tool is registered under oreTool oreDictionary.

If I will turn on the substitution mode:
It will work fine for my tool. So any tool under oreTool can be used.
But it will break the plank part of the recipe, because all planks have plankWood oredict.

If I will leave the subs mode off:
Crafting will use directly the planks it should
It will only use the exact tool I specify in there; if I will have same tool from different material it will not register it as a encoded item.

Requested feature/solution:
Be able to set only the tool to use Substitution - meaning be able to set specific slots for substitution mode.

**Comment by XFactHD** [comment]
This would probably overcomplicate the substitution feature.

**Comment by yueh** [comment]
Too complex and it would break the current API regarding crafting and item access (thus nearly every AE2 addon).

Also it sounds more like a recipe issue with that specific mod.
If it reports it can uses any oredict plank to craft a oak door, but then fails the input is not oak planks, it should not report that it can in the first place.
