### ISSUE TITLE
The temple plate (Chisel Mod) has the incorrect texture (orientation) for cable facades.

### ISSUE THREAD

**Issue by jtgraphic** [AppliedEnergistics/Applied-Energistics-2#2177]
It looks like the facade is 90 degree offset from what it should be.

These are the facades in place: https://imgur.com/T4RrCAI
This is what is underneath: https://imgur.com/738NiQU

**Comment by yueh** [comment]
We simply use the texture provided by the block without any further rotation.

Should the facade then be rotated differently, chisel itself is actually rotating the texture on their side or using a different texture than reported.
Nothing we can really fix on our side (or at least do not want to start it and suddenly have to deal with hundreds of special cases for some textures)
