### ISSUE TITLE
Pattern Terminal Bug

### ISSUE THREAD

**Issue by TechnologicApe** [AppliedEnergistics/Applied-Energistics-2#2178]
Whenever I try to make a Pattern in the Pattern Terminal, it completely crashes my game.

Here is the log:

http://pastebin.com/fABE0pP0

**Comment by XFactHD** [comment]
Please put your crash report on pastebin and replace the pasted crash report with the URL (you can edit your post BTW).

Can you reproduce this crash without Optifine and/or Minions?

**Comment by TechnologicApe** [comment]
I will try it without Optioned or minions

**Comment by TechnologicApe** [comment]
Still Crashes.

Here's the new Log:

http://pastebin.com/YHNrp0Eq

**Comment by XFactHD** [comment]
That log is incomplete. Most of the stack trace is missing.

**Comment by mindforger** [comment]
do not post the crash log from withing the logfile, thre is a dedicated folder "crash reports" that contains the full crashlog .. you can attach it as file when commenting or use "gist" to paste large logs becasue pastebin has a pretty small limit

**Comment by TechnologicApe** [comment]
I had switched over to the Rv3 Beta, still has the same issue.

[crash-2015-06-02_17.04.41-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/165123/crash-2015-06-02_17.04.41-client.txt)

**Comment by mindforger** [comment]
delete the "1.7.10" folder inside your "mods" folder, you have probably a codechickenlib roaming there .... maybe you are missing it i can not read that from the log itself clearly ... it will download the needed lib-mods by itself again

**Comment by TechnologicApe** [comment]
Seems to be working now. Thank you!
