### ISSUE TITLE
Crash TMechworks Drawbridge With Interface

### ISSUE THREAD

**Issue by Muramasa-** [AppliedEnergistics/Applied-Energistics-2#2180]
If you put an AE Interface in the Extended Drawbridge from TinkersMechworks  and give it a redstone signal to deploy the Interface, it crashes the game and Corrupts your world.

I think it has something to do with not being able to get data from the player that it expects to have place the block, but that's just a guess.

Crash: http://pastebin.com/APN4hqRk

**Comment by XFactHD** [comment]
Why do you need a TMechworks drawbridge to place the interface?

**Comment by Muramasa-** [comment]
My specific use case was to make a 16x16 mining well contraption and the first block I thought of that allows the mining well to dump things into was the interlace.

**Comment by XFactHD** [comment]
You can use white-white-white ender chests with the drawbridge (not white-white-white ender chests will create nasty bugs).

**Comment by Muramasa-** [comment]
Oh of course, this does not stop me accomplishing my build, but I just posted it since it's quite a nasty bug and so it's "out there".

**Comment by mindforger** [comment]
sorry for a little OT here @Muramasa- one hint to the drawbridge ALWAYS test in SP if a certain block in the drawbridge crashes the world or creates bugs, then blacklist it ... the past told me some lessons .. and some lost server worlds ...

**Comment by Muramasa-** [comment]
@mindforger Thanks for pointing out there is a blacklist!
Yeah it wasn't on an important world thankfully!

**Comment by yueh** [comment]
#2134
