### ISSUE TITLE
Issue with Inscriber

### ISSUE THREAD

**Issue by TH3GOD88** [AppliedEnergistics/Applied-Energistics-2#2181]
If you already have a circuit and printed silicon in the Inscriber and place a hopper on the side and place another printed circuit in; it will automatically take it and make a processor.  appliedenergistics2-rv2-stable-10 forge - 10.13.4.1614.

**Comment by yueh** [comment]
Yes, hoppers will automatically insert into an inscriber when attached and should the input match a valid recipe, it will start to craft it.

**Comment by TH3GOD88** [comment]
So it is intended?

**Comment by thatsIch** [comment]
yes
