### ISSUE TITLE
[Feature Idea] Storage Bus Filter

### ISSUE THREAD

**Issue by TechnologicApe** [AppliedEnergistics/Applied-Energistics-2#2182]
I remember in Refined Relocation you can set a filter to only store things under the same creative tab, Like Construction or Redstone. Would something like this be possible for the Storage Bus?

**Comment by XFactHD** [comment]
Features like this were already suggested for the storage cell filter and were denied because of the 63 items limit per storage cell/storage bus.

**Comment by yueh** [comment]
No
