### ISSUE TITLE
[Major][Bug] If AE System becomes to large, cables start glitching/bugging out

### ISSUE THREAD

**Issue by Yanniclord** [AppliedEnergistics/Applied-Energistics-2#2183]
So, this is a thing.

![2016-03-10_00 57 07](https://cloud.githubusercontent.com/assets/5807595/13654855/3381e302-e65b-11e5-8b18-44772ea80fda.png)

![2016-03-10_00 57 14](https://cloud.githubusercontent.com/assets/5807595/13654858/351c6296-e65b-11e5-9661-3d3ab9d39334.png)

My AE system has become so large, that at this point cables seem to randomly bug out and disconnect. They break everything connected to them too (Import/Export Bus and Interface and other such stuff)! This is a big problem, as there are no logs, so no idea what causes it.

**Comment by Yanniclord** [comment]
Its horrible, its even worse downstairs in my Space Station. 
![2016-03-10_01 02 25](https://cloud.githubusercontent.com/assets/5807595/13654913/d00d4b8a-e65b-11e5-93fa-398b0859b4ac.png)

AE2 build rv3 beta 5

**Comment by Yanniclord** [comment]
Question, but could [THIS](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2290415-sci4mes-mods-torcherino) mod have something to do with this problem? I had some Torches placed nearby to speed up some machines, and this is most likely my fault (if it is not an actual AE2 problem).

**Comment by Yanniclord** [comment]
It is NOT Torcherino. I had no Torches nearby, not even in that dimension. And yet, the ME cables just break.

**Comment by Yanniclord** [comment]
Here a new screenshot. After my ENTIRE system became corrupted and broke down, i rebuilt it. And it already starts to happen, the system is slowly breaking apart.
![2016-03-10_18 21 35](https://cloud.githubusercontent.com/assets/5807595/13678054/0d15735e-e6ed-11e5-995f-c52b8868e317.png)

**Comment by XFactHD** [comment]
Can you reproduce this in singleplayer, on a plain forge server or on a cauldron server without plugins?

**Comment by mindforger** [comment]
@Yanniclord can you reproduce this without cauldron ?

**Comment by Yanniclord** [comment]
Well no, but i will see if i still have this problem with KCauldron 1558. If so, i will download the Space Station from my server and try it in Singleplayer.

**Comment by Yanniclord** [comment]
**OK**: So it seems to be something with KCauldron build 1614. I reverted to 1558 (due to several other reasons not related to AE2), and the cables that were corrupt, just directly connected to each other again. What it was i don't know, but if a dev could look into the KCauldron code for build 1614, or better said exactly this build (https://repo.prok.pw/pw/prok/KCauldron/1.7.10-1614.185/KCauldron-1.7.10-1614.185-bundle.zip)

**Comment by Yanniclord** [comment]
Can anyone in this changelog find what exactly would corrupt the AE2 system in build 1614? If i know what version it is, i can just the previous version and everything would be fine.

https://repo.prok.pw/pw/prok/KCauldron/1.7.10-1614.185/KCauldron-1.7.10-1614.185-changelog.txt

**Comment by XFactHD** [comment]
Could be this:
 1.7.10-1614.176: 097252b
Add expermintal feature: tileEnitity list recreation each tick
or this:
# 1.7.10-1492.153: 4a63dca
Transparent unloading {,tile}entities from world

**Comment by Yanniclord** [comment]
Can't be 1492, as this bug does not exist in 1566 (Unofficial KCauldron build).

**Comment by Yanniclord** [comment]
It has to be in 1614. Could it also be this one?


# 1.7.10-1614.185: 7114a28
Implement thread-safe, async-like and not buggy BlockUpdatesTracker

**Comment by XFactHD** [comment]
Possibly.

**Comment by Yanniclord** [comment]
I will try 1614.175, see if it works. I will take a world backup just in case.

**Comment by Yanniclord** [comment]
AE2 does not break in 1614.175, but the server still lags with Galacticraft, where in build 1614.185 the server does not lag with Galacticraft, but the AE2 system breaks.

**Comment by bookerthegeek** [comment]
@Yanniclord, please try with 
http://github.com/TCPR/Thermos

Does the issue still happen?

**Comment by Yanniclord** [comment]
Funny, Thermos does not work at all. Many recommend me Thermos, yet it is even worse than KCauldron at most times (currently, not saying forever). With Thermos, i have to remove several mods to even get it running, which removes the point of even having a modpack server if you ask me :/

**Comment by siasur** [comment]
I think this issue can be closed. It is a bug with relation to an unsuported serversoftware

**Comment by Yanniclord** [comment]
Still gotta love that hate against Cauldron and all its following modifications. Galacticraft wants to support it, while others hate against it for very, ground holding or even meaningful reasons.
