### ISSUE TITLE
Storage size discrepancy between storage cell sizes

### ISSUE THREAD

**Issue by SephirothWS** [AppliedEnergistics/Applied-Energistics-2#2184]
While I understand http://ae-mod.info/ME-Storage-Math/ exists, it does _not_ make sense that a single item uses way more bytes on a larger cell just because its a larger cell. What is the reasoning behind this? If this is something to make people "think" about what cell to use, then why not just cut out the four different tiers of storage cells and have just a singular tier? See the below issue on EC2 for more details.

https://github.com/ExtraCells/ExtraCells2/issues/383

**Comment by vallard192** [comment]
Its based on how computer memory and storage actually works.

Larger storage capacity is made up of a greater number of basic storage
units.  More storage units end up requiring a larger number of addresses to
put stuff in.  It's also compares to how if you make a text file on your
computer and put a single character in it, save it and then right click it
and look at the properties you'll generally see that it takes up 1kb or
more as the "size on disk" even though it only contains a single byte.
