### ISSUE TITLE
All channels going to one interface instead of the rest 

### ISSUE THREAD

**Issue by Frostbitte** [AppliedEnergistics/Applied-Energistics-2#2186]
Ok so im having a problem with the channels and stuff.

so this is it working and how it should look
![github help working](https://cloud.githubusercontent.com/assets/17791514/13720211/e4352b3e-e7d0-11e5-800c-a37c9778b852.png)
![github help front](https://cloud.githubusercontent.com/assets/17791514/13720213/eded9396-e7d0-11e5-8a7d-160e7cf1771e.png)

And then i run off to do thinks like repositioning my quarry and i come back to this.
![github help broken](https://cloud.githubusercontent.com/assets/17791514/13720219/0ff31952-e7d1-11e5-9622-fe875331b8c3.png)

and all my crafting recipes(which are in the ones closest to the mob farm) dont show in the ME system.
It might be just me being stupid but if its not how can i fix it?

**Comment by XFactHD** [comment]
Try separating the blocks a bit, you most likely have the problem that the channels get sent over the molecular assemblers to other interfaces.

**Comment by Frostbitte** [comment]
Is this similar to what you mean? ![githubhelp](https://cloud.githubusercontent.com/assets/17791514/13723900/2ae77490-e841-11e5-86d1-04f07e233702.png)

**Comment by XFactHD** [comment]
Yes, that's what I meant.

**Comment by Frostbitte** [comment]
ok thanks and so far its fixed
