### ISSUE TITLE
Deleted patterns keep reappearing after i replace them with new ones

### ISSUE THREAD

**Issue by Entwo** [AppliedEnergistics/Applied-Energistics-2#2187]
So, I had 64 interfaces, each one wrapped around with 4 molecular assemblers. I wanted to expand that system for more pattern storage. So I hooked up 512 interfaces using p2p tunnels. I moved all my patterns and everything was fine for some time. Anyway, I updated a mod, making all of its patterns invalid. I took them all out one by one and encoded them again. After client restart, all of the old invalid patterns reappered, removing my new ones (not all of them actually but the majority of them). I figured out that removing them manually from the interfaces kinda fixes that issue. But I can't really do that for all of them. I have 512 interfaces as I said before and i don' t really know where's what. It's really tedious to do it manually. I think it's an interface terminal problem. P2p tunnels also have something to do with it. Any thoughts?

**Comment by Entwo** [comment]
I found a kinda meh solution for my issue. So, my main ME network is built in an RFTools dimension. I did the whole re-encoding thing in another RFTools dimension when i had problems (via Quantum bridge). Returning to the main base where the original ME network is located and redoing the whole process seemed to work fine. So it could also be RFTools or Quantum bridges causing that. I really don' t know. I'm just glad i found a way around it.

**Comment by yueh** [comment]
Please read our [contribution guidelines](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/CONTRIBUTING.md).

**Comment by Entwo** [comment]
Forge-1.7.10-10.13.4.1566
appliedenergistics2-rv3-beta-5 (pretty sure I had the same issue with version appliedenergistics2-rv2-stable-10 as well)
[http://imgur.com/kuMBKjq](url) These are the mods I use.It is a custom modpack and all mods are up to date.
I experienced the issue in single player. 
Sorry If I missed anything. If i did please tell me what and I'm gonna add it. I'm kinda lazy to read all of it xD
