### ISSUE TITLE
Crafting with GT powered tools

### ISSUE THREAD

**Issue by JasonMcRay** [AppliedEnergistics/Applied-Energistics-2#2188]
If GT electrical tool you need to use for crafting runs out of power, it will get deleted completely.

Power and durability is stored in NBT tag (not as meta value as in most mods). Using the tool in any good old crafting table (being it modded or vanilla) works perfectly.

Tested in rv3-beta5
GT: 5.09.19

**Comment by wlhlm** [comment]
> Using the tool in any good old crafting table (being it modded or vanilla) works perfectly.

Does that also include other automated crafter's like Molecular Assembler or the crafters from EIO and RFTools?

**Comment by JasonMcRay** [comment]
eIO Crafter seems to not consume the energy at all.
Molecular assembler deletes tool.

By "good old crafting table" i meant crafting table, XACT crafter, TiC crafting station.

**Comment by yueh** [comment]
AE2 will delete container items, once they reach zero durability.

No idea about the actual reason, but I would highly assume it is done to prevent broken ones from underflowing and causing issues or duping them.

I still favour the current approach over changing it. Occasionally destroying an item is still better than starting to dupe items.

**Comment by JasonMcRay** [comment]
Deleting items once they reach zero durability is completely fine. But in GregTech it deletes the item when it reaches 0 EU, and doesn't care about durability at all.

**Comment by thatsIch** [comment]
It has durability and charge?

**Comment by JasonMcRay** [comment]
Yes it has both. Amd both stored as NBT

**Comment by exetico** [comment]
Does anyone prefer another solution than the Molecular Assemblers, for simple taske - like making a Oak wood to  Oak wood planks etc? In the latest version of FTB, the ME-system is simple stops working, then we're using molecular asssembler to simpel tasks like this.
![image](https://cloud.githubusercontent.com/assets/3549445/16171463/b8f501e6-356f-11e6-8639-25c1396a25f7.png)

In our setup, we used 8 molecular assemblers to do different tasks - but after something like 1-2 minutes, every ME-task (AE) is freezing - even ME Import from our Ender-chest and so on..
