### ISSUE TITLE
Pattern terminal fails to start an autocrafting request.

### ISSUE THREAD

**Issue by Entwo** [AppliedEnergistics/Applied-Energistics-2#2189]
That happens in 2 of my pattern terminals. Not all of them. Can' t figure out why or reproduce the bug. I just press middle click to start crafting something and then when i click next or shift-click start, the gui closes and nothing happens. It's not that important i guess. It's really annoying though when you are trying to encode something complex.

**Comment by XFactHD** [comment]
Do you get any stack traces in the log when the gui closes?

**Comment by Entwo** [comment]
I assume you are talking about crash report? The game doesn't crash so how can i check that?

**Comment by XFactHD** [comment]
No, I don't meant the crash report, I meant the normal game log found in the logs folder.

**Comment by Entwo** [comment]
No, not really. The only unusual thing in the log was the "Can't keep up, did the system change...." thing. It only appeared one time, even though I requested 2 crafts. Don't know what's up with that. It might have nothing to do with my problem in the first place.
