### ISSUE TITLE
Starting up the game

### ISSUE THREAD

**Issue by Blazingtactic** [AppliedEnergistics/Applied-Energistics-2#2190]
Hi, I downloaded your game for 1.7.10 (rv2.stable build 10.) and I still seem to think that I need to install some type of core, because I only downloaded that 1 build and it still isn't working. Please help me. I would like a reply soon if possible. Thank you ;)
- David

**Comment by XFactHD** [comment]
What are you trying to do?

**Comment by Blazingtactic** [comment]
Don't worry; I think it's working OK now, but thanks anyway.
