### ISSUE TITLE
Autocrafting requests multiple tools in substitution mode.

### ISSUE THREAD

**Issue by JasonMcRay** [AppliedEnergistics/Applied-Energistics-2#2191]
Its not entirely bad thing, but I thought I will let you know.

When using autocrafting with tools which stores their damage in NBT (for example GT hammer) and you have multiple of them in your AE system, crafting requests them both and both of them are used (it uses first, then second, then first again). So the durability is kinda split between the tools.

Not sure if intended behaviour or not.

**Comment by yueh** [comment]
It will always calculate how many tools it needs in total and due to the way it extract items from the network, it will always use the least used one first.
