### ISSUE TITLE
Annihilation Plane not working with Multiparts as expected

### ISSUE THREAD

**Issue by Almagnus1** [AppliedEnergistics/Applied-Energistics-2#2193]
Relevant JARs:
ForgeMultipart-1.7.10-1.2.0.345-universal.jar
appliedenergistics2-rv3-beta-5.jar

I'm in the process of building out a mining well based frame quarry, and I'm noticing that the Anihilation plane isn't playing nicely with the forge multipart pieces, or the AE2 facades for that matter, as I can't seem to box in the edges.

While I can just leave it open, and ensure that the blocks with the annihilation planes are properly connected, it doesn't really look all that good >.>

**Comment by yueh** [comment]
And what is expected?

**Comment by Almagnus1** [comment]
For example, if I were to make a decorative cube around the conduit, with the top face being the annihilation plane, with the bottom being either a multiblock hollow cover (or facade), then I would expect that the sides should be able to accept a facade or a multiblock cover, so it would look like a block that has the annihilation plane as the top face.

A more practical example would be a highly compact sugar cane or cactus farm, where you would extend the cable down from the ceiling, and you would be unable to cover the bottom of the construct, because it wouldn't accept a facade.

In the case of funky locomotion, this means that an annihilation plane head (or a wall) can't itself be considered interconnected frames, so a workaround must be used, rather than taking advantage of what AE2 already does so well with forge multiblocks.  IIRC, this used to work in the past (and lead to some elegantly compact designs), but was changed along the way for some reason.

**Comment by yueh** [comment]
If something changed, then on FMP side. Our FMP integration is probably untouched since rv1 or so.

FMP probably consideres these sides as already occupied as the plane only leaves a 1 px wide border around it, but FMP covers are 2 px thick and would overlap. I remember that these would cause some massive z-fighting. Maybe that was the reason it was disabled in FMP?

**Comment by Almagnus1** [comment]
True, but it wasn't working with the AE2 facades as well, so unless there's a connection between the facades and FMP under the hood...

**Comment by yueh** [comment]
If you attach a single FMP to a cable, the full block will be converted to a FMP block/tilentity and FMPs collision detection takes over. Facades are probably also affected by it.

Only way to reset them is to completely remove the block with all parts and put it back (without any FMP covers etc)

**Comment by Almagnus1** [comment]
Yeah, that's also what I'm seeing, now that I better understand the issue.

Time to bring it up with FMP....
