### ISSUE TITLE
[Feature idea] Queue block

### ISSUE THREAD

**Issue by TheHell34** [AppliedEnergistics/Applied-Energistics-2#2194]
My idea is to make a queue block, so you can queue crafting jobs.

I think thisblock shouldbe expensive for end game use

**Comment by XFactHD** [comment]
If you connect multiple crafting CPUs to one network, you can make multiple crafting jobs in parallel.

**Comment by TheHell34** [comment]
I know but if you want to do multiple larger crafting jobs and you have only 1 large crafting cpu then a queue is very handy

**Comment by yueh** [comment]
No
