### ISSUE TITLE
Interfaces are "Nothing"?

### ISSUE THREAD

**Issue by jim261** [AppliedEnergistics/Applied-Energistics-2#2199]
Well I was playing Skyfactory 2 and trying to build an autocrafting system with Applied Energistics 2 ^^. So far so good but fast I realized that the Interfaces were shown as "Nothing" It wouldn't craft.... Now I need your help... I took some pictures.^^

 [http://imgur.com/a/nMWAF](url)

Edit: You have to copypaste the link, otherwise it won't find the album.

**Comment by helmutfork** [comment]
Based on your picture, it looks like you only have one interface actually touching the assemblers.  The others are just floating there connected to "nothing."
