### ISSUE TITLE
Items in Terminal get invisible

### ISSUE THREAD

**Issue by Eldiabolo21** [AppliedEnergistics/Applied-Energistics-2#2201]
Items get invisible when scrolling through the (Crafting) Terminal. 
They are initially visible, as soon as scrooling a couple of lines down they become invisible and only the number stored is shown. See attached screenshot. 

MC 1.7.10, Forge 10.13.4.1614, AE2-rv3-beta-5.
It is independt of the installed mods that interact directly with AE2 that I have installed (extra Cells and AE-Stuff), meaning it remains when these two are disabled.

![2016-03-18_12 46 17](https://cloud.githubusercontent.com/assets/5549781/13898436/28fb644e-edd1-11e5-9d6b-0197b4abc4ec.png)

**Comment by XFactHD** [comment]
Are you using Optifine?

**Comment by Eldiabolo21** [comment]
No optifine

**Comment by XFactHD** [comment]
Fastcraft? Also, can you remove all the conduit facades from EIO from the system and see if that fixes it?

**Comment by Eldiabolo21** [comment]
Fastcraft version 1.21. seems to be latest stable. Removing fastcraft didn't help either.

Removing conduit facades did not fix it. Even after restarting client.

**Comment by XFactHD** [comment]
That's odd.

**Comment by yueh** [comment]
Most likely #2109. (Not necessarily Forestry. Might be another broken item renderer)
