### ISSUE TITLE
[Feature Request] ME Interface Terminal add naming per interface

### ISSUE THREAD

**Issue by Gliceas** [AppliedEnergistics/Applied-Energistics-2#2203]
Hi
So today while I was using my new AE setup and adding patterns via ME interface Terminal, I realised when I have say 2 or more alloy smelterys and set to different modes ...

It would be nice to be able to see in the interface terminal which is which i.e. be able to tag/name the interfaces.

e.g. 4 x Alloy Smeltry with interfaces - "AlloysOnly1"  , "AlloysOnly2", "All", "FuranceOnly" etc..

**Comment by Bjonnfesk** [comment]
You can name ME Interfaces in both Inscribers and vanilla Anvils. (Source: http://ae-mod.info/ME-Interface-Terminal/)
