### ISSUE TITLE
[Feature Request] Crafted+Craftable View in various monitors.

### ISSUE THREAD

**Issue by Sorbe** [AppliedEnergistics/Applied-Energistics-2#2204]
Add another object view to monitors that shows only things that are **craftable** and (then as a subset) **crafted**.  This would never show any objects that we cannot currently craft.

This is not the same as the current view which shows **craftable** and **everything**.  I constantly have to switch views/terminals or type in the item name with just the **craftable** view to make stuff.

Further, enable "Shift" to reveal the **craftable** option on anything that is **crafted** so you can force more to be made.

**Comment by XFactHD** [comment]
You can switch a terminal between "Show everything", "Show craftable" and "Show stored". If you want to craft more of an item that is already in the system, use middle mouse click.
