### ISSUE TITLE
[Feature Request] Pattern Terminal and NEI without all items present

### ISSUE THREAD

**Issue by Sorbe** [AppliedEnergistics/Applied-Energistics-2#2205]
Currently, if you are in the Pattern Terminal and search for an object you have not made yet, you must have 1 of everything in the recipe for the object before you can add the pattern.

For example, assume you do not yet have a pattern for "Fluix Pearl" and want to add it.  If you type in the item name in the Pattern Terminal with NEI turned on, you will see the "Fluix Pearl" on the far right in the NEI display, if you now click on it, it will reveal its recipe(4 Fluix Crystals, 1 Ender Pearl) .  If you then Shift-Click on the "?" symbol you will transfer over the recipe to the Pattern Terminal crafting grid.  However, if any of the recipe components are not stored yet, it will leave blank spots!

Please fix this to use the actual recipe you selected if you do not yet have all the components.  This will make creating recipes far less annoying since now, you have to abandon the pattern creation process, switch to another terminal, find the missing items (even if you have patterns for them already), for the system to create at least one of every recipe component and finding and making one of each, even if you already have existing recipes for some of them.

This will dramatically improve the process of creating patterns and thus making AE2 more useful.

**Comment by wlhlm** [comment]
See #355.

**Comment by Sorbe** [comment]
The fact that I found and separately reported this issue proves that it's still a user hassle.  Consider how this works for Crafting Tables, you can get the "pattern" into your crafting table without having any of the items present if you just press "?", but that does nothing in the Pattern Terminal.

**Comment by XFactHD** [comment]
If you have NEI in recipe mode, you can click on an item in NEI and pull it. As soon as you have a stack on your cursor, you can let the mouse go. You can than place this ghost stack in the pattern terminal. The stack will vanish and the item will be in the pattern terminal.
You can also autocraft directly in the pattern terminal.

**Comment by PiggyWhiskey** [comment]
Sorbe, If you're using a Crafting Table and don't have the items present, it won't allow you to craft it. 
Just like the Pattern Encoder.

As wlhlm mentioned, it was always the intention to require one of each item to encode a pattern.

In saying that, if you want to make and expensive item that needs several lower items (Octuple Compressed Cobblestone perhaps) You would only need 1 of the previous item.

**Comment by yueh** [comment]
See the linked issue.
