### ISSUE TITLE
Some terminals (PatternTerminal) start to lose letters ("T" for example)

### ISSUE THREAD

**Issue by Sorbe** [AppliedEnergistics/Applied-Energistics-2#2206]
If you have the Pattern Terminal open and try searching for an item, SOMETIMES **something** is intercepting certain letters, "T" for example, and preventing them from being typed in.

I tried changing "T" to not map to "chat" in the global controls (I reset it to "Tab") but the letter "T" still sometimes doesn't work in Pattern Terminal.  It does work in the crafting terminal.  You can freely type "T" everywhere else within the game and globally in Windows.

This has happened on numerous occasions after I've used AE2 for a while.  Other times, this works properly...

**Comment by wlhlm** [comment]
https://www.reddit.com/r/feedthebeast/comments/40lp3w/ae2_search_issue/cyv5yi6

**Comment by Sorbe** [comment]
Agreed.  Please resolve/close as not an AE2 issue.

**Comment by wlhlm** [comment]
Since you're the issue submitter, you can close it on your own ;)
