### ISSUE TITLE
[Feature Request] Bridging Mode for ME Wireless Access Points

### ISSUE THREAD

**Issue by Sorbe** [AppliedEnergistics/Applied-Energistics-2#2207]
Allow ME WAPs to bind to each other (using memory cards) to establish wireless bridges.  This is similar to the ME Quantum Ring, but is very range limited and does not span dimensions.  The remote side of the bridge will still need initial power to startup, but then it would draw AE power across the link.  This should encourage the use of Energy Cells at remote areas that are served only by the bridged AE network to allow them to re-establish links or run offline for a time.

**Comment by Sorbe** [comment]
Btw: I just reviewed the previous features discussion issue that included WAP Bridging mode.  WAP Bridging is what I originally hoped P2P tunnels would be.  I have created 3+ Quantum tunnels for Inter-building communications, but I still want a way to wirelessly connect two points SHORT range.  This is both for cross-room and cross-floor situations.  Building more Quantum tunnels for this is both expensive and uses too many blocks for this functionality.

Since AE2 is keen to model networking constructs, I will point out all REAL WORLD Wireless Access Points support bridging.  This is commonly used in residences to connect living rooms with offices, wireless closets, etc.

And a WAP in bridging mode, should just need a Memory Card to bind them together in bridging mode.  No singularities, no using them to connect Wireless Controllers, no massive range, just the basic wireless  thing.

**Comment by PiggyWhiskey** [comment]
AE2 Stuff has this already.

http://mods.curse.com/mc-mods/minecraft/225194-ae2-stuff

Power cost for wireless is distance squared.

**Comment by XFactHD** [comment]
1. This was denied multiple times
2. AE2Stuff already has this as said before.

**Comment by yueh** [comment]
No.
