### ISSUE TITLE
[Feature Request] Implement a Network Router

### ISSUE THREAD

**Issue by Sorbe** [AppliedEnergistics/Applied-Energistics-2#2209]
Routers are commonly installed in commercial applications to partition physical nets (1 or 2 per building floor), so that not everything is on one big physical network with all ARP addresses visible.  While I like channel management, I don't really like the P2P tunnel to compress traffic back to the ME Interface.  Why not just create a router block that links disjoint sub networks?

The one router per floor is then linked together with (only) high-speed (dense perhaps?) cables.

**Comment by PiggyWhiskey** [comment]
If you're talking about subnets, 
Storage Bus on an Interface.

Storage Bus network can see all the Interface networks.
The Interface networks can only see their own network.

You seem to be forgetting this is a game. 
It will never match what happens in Real Life.
In this game, there isn't a need to partition nets like you've explained.
And any kind of sub-netting is already available with Cell Partitions, and Storage Bus/Interfaces that I mentioned earlier.

**Comment by yueh** [comment]
No.
