### ISSUE TITLE
[Broad Category] Security Sensors and Weapons

### ISSUE THREAD

**Issue by Sorbe** [AppliedEnergistics/Applied-Energistics-2#2211]
When I look carefully at AE, I see it as an "inventory management" and "auto-crafting" solution.  But it seems to be trying to be a network computing solution.  To go beyond building "sprockets" and "cogs", one path might be to add sensors and weapons.  Think of it as a security system -- vs players and mobs.  I think a good Sci-Fi model for this would be the "Red Queen" from the Resident Evil movie franchise.

Here is a (very short) list of blocks that might enable this...

1) PIR Sensor that detects movement in an area.
2) Laser Beam emitter that zaps unauthorized entities in a restricted area.
3) RFID Security Card that allows access to a restricted area
4) Perimeter Sensors that establish lines of control (think wireless Land Marks)
5) Sirens that can be setup to emit audible alarms
6) Remote alarm keyfobs that can alert online users to intrusion
7) Turrets that can spray an area with projectiles (Matter Balls?)

This is probably a whole new mod, but it could also be a set of features for an big AE2 release.

**Comment by XFactHD** [comment]
1. As you already said, this would fit better for a separate add-on
2. Take a look at OpenSecurity (add-on for OpenComputers), it has almost everything you suggested

**Comment by yueh** [comment]
As you said, it is an "inventory management" + "auto crafting" mod. Nothing less, nothing more.

This is clearly out of scope for AE2. While clearly be possible as AE2 AddOn it might be even better as standalone mod. I would recommend use your idea and make your first mod with it. Maybe you will even find some other devs, which might be interested in supporting it.
