### ISSUE TITLE
[Broad Category] Home Automation

### ISSUE THREAD

**Issue by Sorbe** [AppliedEnergistics/Applied-Energistics-2#2212]
This is another suggestion for a broad category of AE enhancement.  Again, to move AE beyond inventory and crafting into new areas, I would suggest "Home Automation" blocks.   Think about the "Jetsons" and  X10 / zWave type applications.  Here is another (short) list of possible blocks...

1) Automatic Room Lighting Controls -- If you have a Magnum Torch to repel all monsters, you may want actually turn light on/off as needed.
2) Door controls - If you have a RFID tag, you can get your door to open / close as you get near.
3) Curtain Controls for your windows - Do you really want to have your windows wide open always?
4) Food Preparation - Come home to various automatically cooked/baked meals when you arrive
5) Music Players - How about auto-playing some music discs when you're at home
6) Outside Cameras - See what's around your base in a picture frame that can change views
7) Voice Announcement - Play a selection of announcements (or even tones) when stuff happens

Again, this is probably a whole new mod, but it could also be a set of features for an big AE2 release.

**Comment by XFactHD** [comment]
1) Use OC or CC
2) Use OC and OpenSecurity
3) Use OC or CC
4) I think you can fire up some autocrafting via OC
5) OC and CC can play music discs via their drives
6) Use SecurityCraft
7) OC should be able to do this

**Comment by yueh** [comment]
See #2211
