### ISSUE TITLE
AE2 not working properly on FTB Resurrection

### ISSUE THREAD

**Issue by OpusIkahn** [AppliedEnergistics/Applied-Energistics-2#2213]
Not sure if it's all of AE2 but the certus quarts is just showing up as a 4 plane of black and purple squares and I can't craft it into anything. Only thing I've disabled was Gregtech because I didn't want the stupid recipe changes. Everything else is normal.

**Comment by OpusIkahn** [comment]
bump

**Comment by VT-14** [comment]
Issues with modpacks should be reported to the modpack.

A quick look at FTB Resurrection's wiki page helpfully points out that GregTech is the pack's core mod.  You probably want to find a new pack to play on.

Also, Github shows issues in chronological order of creation.  Bump (Bring Up My Post) does nothing but show people your impatience (Seriously, an hour?) and annoy anyone who might have received a notification.

**Comment by OpusIkahn** [comment]
yes, seriously. I'm impatient, oh well.

So how would I go about changing the settings in gregtech to disable all the annoying ''harder'' recipes then?

**Comment by mindforger** [comment]
>Issues with modpacks should be reported to the modpack.

>A quick look at FTB Resurrection's wiki page helpfully points out that GregTech is the pack's core mod. You probably want to find a new pack to play on.

**Comment by VT-14** [comment]
Minetweaker is an option, but I never learned how to use it myself.

**Comment by OpusIkahn** [comment]
That's good for you, I'm asking for assistance here. If you have nothing informative to put forward I suggest you go outside like a good little troglodyte.

**Comment by OpusIkahn** [comment]
> Issues with modpacks should be reported to the modpack.

A quick look at FTB Resurrection's wiki page helpfully points out that GregTech is the pack's core mod. You probably want to find a new pack to play on.

That's good for you, I'm asking for assistance here. If you have nothing informative to put forward I suggest you go outside like a good little troglodyte.

**Comment by mindforger** [comment]
@OpusIkahn you may concider the fact that you are in the completely wrong section for your question! so please keep your insults for yourself or GTFO

and i gave you a hint to check if your texturepack is missing the textures probably!
