### ISSUE TITLE
AE2 loosing imported items

### ISSUE THREAD

**Issue by remyxomatosis** [AppliedEnergistics/Applied-Energistics-2#2214]
I'm playing Infinity Unleashed 2.4.2 on OSX 10.11.3 (AE2 rv3-beta5). 
I have a simple AE system set up with one controller ME drive and a couple of DSUs. Upon server start, everything works fine, however after about 3-4 minutes the AE system starts glitching. Items that are imported into the AE system (either by a chest+import bus) or by shift clicking from the player inventory in the crafting terminal) simply disappear. The are not on any drive in the system, they are erased and cannot be recovered.
Interestingly, breaking the ME controller and replacing it, allows to import items again, however after a couple of minutes the import bug keeps reappearing.  
This is really a game breaking bug, as I effectively cannot use the AE2 system for item storage.

**Comment by mindforger** [comment]
can you reproduce this in a minimal setup or provide pictues of the current setup? are there any trash cans present or maybe a matter condenser somewhere? are all your interfaces defined properly?

**Comment by remyxomatosis** [comment]
The version is AE2 rv3-beta5. My setup is very small, as can be seen here:
![2016-03-23_20 28 58](https://cloud.githubusercontent.com/assets/18032332/14005315/7ed5e3c0-f138-11e5-83c2-e015afe547b1.jpg)
in the back there is a single connection to an enderchest for item import:
![2016-03-23_20 29 03](https://cloud.githubusercontent.com/assets/18032332/14005326/979ba5c0-f138-11e5-9e76-8b0dac2e1b72.png)
The cable towards the basement connects to the DSUs, however, the bug occurs even with the dense cable disconnected. 
Once again, after a couple minutes into playing, imported items and shift clicking into the system leads to the items disappearing.

**Comment by remyxomatosis** [comment]
Forgot to mention: No condensers or trashcans present in the system.

**Comment by VT-14** [comment]
The ME Controller can accept power, so the Energy Acceptor isn't required.

How are the DSUs hooked up to the system?  Storage buses?  Are there any other Storage/Export/Interfaces on the network?

Are there any mods installed that altar things like shift clicking?

**Comment by remyxomatosis** [comment]
The 8 DSUs are connected via storage bus to a single strand of glass cable connecting to the dense cable. However, the bug still occurs if the dense cable is disconnected entirely so it is not part of the problem. 
There are no other storage interfaces on the network, only one ME Drive with 4k disks. 

As far as mods go that modify shift clicking, I don't know. I play the standard infinity unleashed mod list, I hope this helps.

**Comment by sloppythirds** [comment]
if you locked your DSU's unlock them all and see if that works. it worked for me.

**Comment by remyxomatosis** [comment]
Thanks sloppythirds! That fixed it. The really weird part is, that the bug still persists, even if the DSU is NOT connected to to AE network. Simply the existences of a locked DSU in the world seems to get the AE system buggy.  I just confirmed that in my world.
