### ISSUE TITLE
Split small and large quanty items to save storage in big cells

### ISSUE THREAD

**Issue by LonelySouls** [AppliedEnergistics/Applied-Energistics-2#2216]
Hello, i have a suggesting for AE if its possible to make. It would be really cool if cell's or well upgraded version of cells or maybe an upgrade for the AE system where it will move items with smaller quantities to smaller cells. that way junk wont take all the space on the big cells.

**Comment by thatsIch** [comment]
You generally want either to format the big cells to store the large quantities and have them on high priority or format the small cells to store the small quantities and have them on low priority.

**Comment by yueh** [comment]
#460, #598, #1752, #1988
