### ISSUE TITLE
Dupe MC 1.7.10

### ISSUE THREAD

**Issue by Andrey228322** [AppliedEnergistics/Applied-Energistics-2#2217]
Hello. I use MC 1.7.10. - Java8. I have a problem...(DUPE)
https://www.youtube.com/watch?v=a72alZDiQIk
Say pls How to fix on 1.7.10?

**Comment by thatsIch** [comment]
Can you please specificy a point in time? I do not understand Russian.

**Comment by yueh** [comment]
#592, #1430, #2196
