### ISSUE TITLE
Interface not putting items into inscriber from the top/bottom

### ISSUE THREAD

**Issue by Ruhrpottpatriot** [AppliedEnergistics/Applied-Energistics-2#2219]
This is the setup for recreation:
![inscriber-interface_bug](https://cloud.githubusercontent.com/assets/6794359/14061485/5b295614-f381-11e5-8601-7d50e892bcda.png)

The bottom two Inscribers are fed via an interface from the side and produce Printed Silicon and a Printed Logic Circuits. The output is taken back into the ME network via Import Buses.
The upper Inscriber then is fed by two Export Buses, one on the bottom, which feeds the Printed Silicon, and one from the side which feeds Redstone.
On top sits a ME Interface which has a Logic Processor pattern in it and is supposed to feed the Printed Logic Circuit in. The result is then again imported via an Import Bus

Here is the Problem:
1. If the base components for the Processor are available in the System the Export Buses put them into the second inscriber. If the Circuit has to be crafted, it gets not put in.
2. The ME Interface will under no circumstances put the Printed Circuit into the Inscriber from the top. If the interface resides on the side the Printed Circuit gets put into the middle slot.
3. The same as _2_ happens if the interface resides on the bottom.

---

Unrelated Question to this issue:
Is it possible to achieve the above setup in a pure AE way, where the required items for a processors are only added to the inscriber if a processor is requested for crafting, i.e. the Inscriber is empty until the crafting task is recieved?

**Comment by yueh** [comment]
[Inscribers](http://ae-mod.info/Inscriber/) are sided inventories.

**Comment by Ruhrpottpatriot** [comment]
*Sigh* I know that they are sided inventories. The screenshot should show that my setup is indeed respecting the sides as stated in the ae documentation.
Again here is the setup:
* Top is an interface with patterns for processors
* Side is an export bus for redstone
* Bottom is an export bus for Printed Silicon 
* Another side has an import bus to retrieve the crafted item

When I put in the items in the **same** spots **manually** everything works. It's only the interface that will not put items in the inscriber from the top. Export buses work fine in this setup.

**Comment by bookerthegeek** [comment]
So basically;

Automated crafting by an interface placed on top of the inscriber is not placing the requested material in the correct spot inside the inscriber, regardless of the fact that it is on the correct side for the slot to be imputed into?

**Comment by Ruhrpottpatriot** [comment]
@bookerthegeek Yes, that's the issue (bottom doesn't work either). I want to add that if the inscriber has a printing press in it and you input items via interface from the side, the inscriber works and the item is crafted properly.

**Comment by yueh** [comment]
In this case the inscribers rejects them because it will not result in a valid recipe. Thus make sure you are using the correct one should your modpack have modified them.

**Comment by bookerthegeek** [comment]
@Ruhrpottpatriot can I get a screenshot of the inside of the top inscriber in your screenshot and of the recipe your using to attempt the auto crafting?

**Comment by bookerthegeek** [comment]
@yueh you got a TS or discord I can talk to you on ?

**Comment by codewarrior0** [comment]
> Is it possible to achieve the above setup in a pure AE way

Yes. You'll have to use subnetworks to achieve this. Place an ME interface onto an ME interface, and set the first interface to arrow mode pointing at the second. The first interface should have the processing pattern: Printed Logic Circuit, Redstone, Printed Silicon -> Logic Processor. 

The first interface will not join the second interface to its network when placed in arrow mode, so the second interface is on its own subnetwork. On this subnetwork, place your three ME Export Buses on the three sides of the inscriber, and an ME Import Bus on another side. Configure their whitelists accordingly.  Also on this subnetwork, place an ME Export Bus pointing at the first interface, configured to export Logic Processors.

You can use a quartz fiber to supply the subnetwork with power without joining it to the main network. I'm not sure, but you may need some form of ME Storage (either a storage bus or a ME chest) on the subnetwork.

Challenge: Make the first interface instead have the processing pattern: Gold, Redstone, Silicon -> Logic Processor.

**Comment by codewarrior0** [comment]
@Ruhrpottpatriot I found your problem. Your top interface is lying on its side (due to being rotated with a wrench). Thus, what you think is the top of the interface is actually the side.

**Comment by thorsummoner** [comment]
Judging from your screen shoot, the inscriber is on its side; insert an inscribing plate into the top and look inside the jaws to orient yourself <3

**Comment by mindforger** [comment]
this post is 2 years old

**Comment by jason-vivid** [comment]
I had a similar problem.  @thorsummoner thanks.  Your tip made it clear my inscriber was spun.
