### ISSUE TITLE
140 inscriber autocrafting setup, got 42 made and realize it only uses 2 at a time...

### ISSUE THREAD

**Issue by Muntafire** [AppliedEnergistics/Applied-Energistics-2#2220]
I am making a multitude of inscribers, rigged up to autocraft processors. There are 20 banks of 7 inscribers, each of the 7 in each bank creates: 1. engineering circuit 2. logic circuit 3. calculation circuit 4. printed silicon 5. engineering processor 6. logic processor 7. calculation circuit... I have made just over one quarter of the total 140, 42 inscribers, so 6 for each item. I checked the setup while crafting engineering processors and noticed only 2 of the engineering processor inscribers were being used. 

Please tell me there is a fix for this, I already have all 140 inscribers laid out and it is mostly wired up, like 70% complete... All the patterns are in the interfaces etc. It is so close to being complete and I would really like for it to work coz the processor autocrafting is the slowest thing next to crystal autocrafting.

![2016-03-28_12 37 18](https://cloud.githubusercontent.com/assets/18105884/14068526/5021b948-f4e2-11e5-90f8-7f494061b96e.png)
![2016-03-28_12 36 58](https://cloud.githubusercontent.com/assets/18105884/14068534/88074152-f4e2-11e5-83f2-26ec6b721632.png)

This next part is just what I am building at the location of my production facility (for those that are interested) it has little to do with the issue... My production facility is absolutely huge and this is a critical addition to it. The design is around 1/4 built, it has taken around 20 hours so far. I have put down 10 crafting cpus, each 5x5x5 there are going to be 64. I have put down half the molecular assembly units, 64 interfaces with 6 on each interface so 384 and a total of 128 interfaces with 768 molecular assemblers eventually. It is mainly for show, but if I wanna craft any item able to be autocrafted, I bet one day I could using this. 32 dsu laid down and wired, 64 total eventually. A ME controller bank of 20 ME controllers in a cube configuration with 72 p2p tunnels on it, all hooked up to 18 quantum rings to transport the channels wirelessly, I only have 12 of the rings built and there will be 36 eventually. 2 x 24000 rf/t turbines operational, 8 eventually with the majority of the work done on installation. 11x11x11 reactor able to pump 16kmb steam at 60% core insertion. A spawner platform with a witch spawner, a blaze spawner and an enderman spawner.There will be some rooms for the ore processing and fluid production/utilization, a tank room and a misc. room with other mods in it I will use to progress in a number of mods and expand the room. It is built under a red clay volcano in a 3x3 chunk area and it is as tidy as it can be, the wires are compact and symmetrical. The inscriber part was the part that would take up the most channels... There are 512 channels reserved for them and I have over 130 already taken up and so much work has gone into the facility that I don't wanna see this part fail. Even if it can't be fixed, I will still build it for show. lol

**Comment by vallard192** [comment]
That's a lot of inscribers and sounds pretty awesome.

Are you putting speed upgrades in the inscribers?  They are pretty speedy
when full of speed upgrades.  They go in the top right part of the GUI.

**Comment by SephirothWS** [comment]
How many co-processors do you have in your crafting storage multiblock components? Might want to consider increasing the number of co-processors you have, cause if I am correct; a single co-processor adds the ability to use 1 extra machine to craft with.

**Comment by Muntafire** [comment]
Thomas Knight-Wagener has shared OneDrive?files with you. To view them, click the links below.


<https://onedrive.live.com/redir?resid=F1DFC2C469454257!1725&authkey=!AH7PYGUnrty30aA>
[https://r1.res.office365.com/owa/prem/images/dc-png_20.png]<https://onedrive.live.com/redir?resid=F1DFC2C469454257!1725&authkey=!AH7PYGUnrty30aA>

2016-04-03_02.19.45.png<https://onedrive.live.com/redir?resid=F1DFC2C469454257!1725&authkey=!AH7PYGUnrty30aA>

<https://onedrive.live.com/redir?resid=F1DFC2C469454257!1726&authkey=!AN6U9Eg7R8r3zFQ>
[https://r1.res.office365.com/owa/prem/images/dc-png_20.png]<https://onedrive.live.com/redir?resid=F1DFC2C469454257!1726&authkey=!AN6U9Eg7R8r3zFQ>

2016-04-03_02.20.06.png<https://onedrive.live.com/redir?resid=F1DFC2C469454257!1726&authkey=!AN6U9Eg7R8r3zFQ>

<https://onedrive.live.com/redir?resid=F1DFC2C469454257!1727&authkey=!ABMR9tK2pOYIu0M>
[https://r1.res.office365.com/owa/prem/images/dc-png_20.png]<https://onedrive.live.com/redir?resid=F1DFC2C469454257!1727&authkey=!ABMR9tK2pOYIu0M>

2016-04-03_02.20.23.png<https://onedrive.live.com/redir?resid=F1DFC2C469454257!1727&authkey=!ABMR9tK2pOYIu0M>

<https://onedrive.live.com/redir?resid=F1DFC2C469454257!1728&authkey=!AIbdDIBvT0D8n-I>
[https://r1.res.office365.com/owa/prem/images/dc-png_20.png]<https://onedrive.live.com/redir?resid=F1DFC2C469454257!1728&authkey=!AIbdDIBvT0D8n-I>

2016-04-03_02.20.57.png<https://onedrive.live.com/redir?resid=F1DFC2C469454257!1728&authkey=!AIbdDIBvT0D8n-I>

<https://onedrive.live.com/redir?resid=F1DFC2C469454257!1729&authkey=!ADGHE5KxdyNYau4>
[https://r1.res.office365.com/owa/prem/images/dc-png_20.png]<https://onedrive.live.com/redir?resid=F1DFC2C469454257!1729&authkey=!ADGHE5KxdyNYau4>

2016-04-03_02.18.31.png<https://onedrive.live.com/redir?resid=F1DFC2C469454257!1729&authkey=!ADGHE5KxdyNYau4>





I am really not sure what was happening... The crafting multiblock structures are 5x5x5 with 125 blocks, one of which is a crafting storage monitor, two 64k storage and the other 122 are co-processors... There were 10 of those installed so I had 1220 co-processors, but only 122 per crafting cpu. Now I have 31 of those units, and one other 5x5x5 unit with a crafting monitor and 8 x 64k storages. I have since set up level emitters, and that works fine. I have 4000 printed silicon, 5000 logic processors and 2000 of each of the other two types of processors in storage and the import buses on the machines on level emitters to keep them at those levels. I have taken away some, due to space restrictions and now have 128 inscribers. 32 for printed silicon, 16 for each: calculation circuits, logic circuits, engineering circuits, calculation processors, logic processors and engineering processors. All look great and work like a charm, eats my diamonds like cereal for breakfast.

________________________________

**Comment by Muntafire** [comment]
Where ever an accelerator card can fit, there is one there... in every slot available, amongst the crafting cards and redstone cards. Import buses, inscribers and export buses are full of them... there are so many cards in this build it is just a waste, but a very sexy waste.
________________________________

**Comment by limited660** [comment]
I have a similar problem but on a smaller scale.  I have 3 inscribers setup to make Logic Processors and 2 to make the Printed Logic Processor.  If I go request Logic Processors, it only uses 1 of the Printed Logic Processor instead of both which in turn slows everything down.  

The only way I can think to make it work is have the ME dump everything into a chest and then use retrieval nodes with filters to pull from the chest but they have their own set of issues.  They will pull an entire stack into their internal inventory and then drip feed the inscriber which I guess is ok for single item recipes but it becomes a problem when making the processors because each node will pull a different amount of items.
