### ISSUE TITLE
Items get deleted/destroyed

### ISSUE THREAD

**Issue by IVI-e-w** [AppliedEnergistics/Applied-Energistics-2#2222]
Hello there,

Im playing FTB Infinity Evolved on version 2.4.1
AE2 version: RV3-beta-5

Im playing this modpack on a server with some friends, have a AE system for quite a while but starting from yesterday, my friend made some iron ingots and wanted to put these in the system, for some reason the ingots just got deleted or destroyed? 

Today I had the same problem wanting to craft a drum. several items I put in the system got deleted.

Im pretty sure its not a storage issue since I have 40 x 64K storage drives.

Can anyone help me? because this problem makes it quite unplayable

**Comment by VT-14** [comment]
It sounds like you are quite far along in AE2, so it's fairly safe to assume you have a large and complicated system.

The Iron ingots and any other items are probably going somewhere.  Without knowing your entire system, I can only guess that you have something set up someway that is unintended or forgotten about (like autocrafting, or a newly placed security station blocking sub-nets).

I would double check your most recent change to your ME system and work backwards from there, until you find something with a bunch of iron in it, or a trash can.

**Comment by IVI-e-w** [comment]
Hello there,

Ive checked all possible inventories but I couldn't find any thing I missed. I disconnected a auto stone sword disposal export bus wich seemed liked it fixed it. So I disconnected every trash can I could find.

Today im playing again starting to play with Mystcraft. Wanted to craft some Ink Vials so I decided to fill up a lot of Water bottles. Nope All the water bottles I put in the system just vanished, once again I checked every possible inventory, even inventories not connected to the system. It's gone and I have no clue whats the cause of this.

**Comment by sloppythirds** [comment]
I had the same issues. Items dissapeared when put into ME system. After some testing it became clear in my case that when you lock deep storage units this bug will happen. When you unlock them it seems to work perfectly fine.

**Comment by IVI-e-w** [comment]
hmmmmm interesting, I do have deep storage units on locked, Will change that and update here if it fixes it!

Thanks in advance

**Comment by PhoenixSpike** [comment]
ive also had this problem and this is all that i have in my set up. No deep storage no nothing. the only thing that changed after putting my items in was my going downstairs to get more items
![2016-04-17_14 00 01](https://cloud.githubusercontent.com/assets/18517359/14589012/ff2afdfa-04a5-11e6-80ef-f1ca1943017b.png)
##

**Comment by IVI-e-w** [comment]
Well, unlocking the Deep storage units worked for me. I have no clue what would be the solution for your problem, sorry :/

**Comment by mindforger** [comment]
@PhoenixSpike which AE2 version do you have? there were versions that almost unconditionally hides items

**Comment by PhoenixSpike** [comment]
this is the zip file name beyond that im not sure appliedenergistics2-rv0-stable-3

**Comment by PhoenixSpike** [comment]
i updated the mod and it fixed it, thank you!

**Comment by mindforger** [comment]
just to ensure, you are now on rv3 beta5 ? this is the latest and by feel most stable version yet

**Comment by PhoenixSpike** [comment]
yeah thats the one i downloaded
