### ISSUE TITLE
Crafting Status in ME Crafting (and maybe regular) Terminal

### ISSUE THREAD

**Issue by EpiccraftTV** [AppliedEnergistics/Applied-Energistics-2#2224]
Forge Version: 10.13.3.1395-1710ls
Applied Energistics 2 Version: rv3-beta-5
Minecraft Version: 1.7.10
Crash Log: http://pastebin.com/VcnAhVZ9
What was expected: No clue, guessing supposed to be like the crafting monitor.
How to reproduce the problem: Keep clicking the "Crafting Status" button in the terminal.
Server or Single Player: Single Player (survival w/ NEI cheat mode (not a big modded full survival)
Mod Pack using and version: Sky Factory 2, however, I've moved it to curse as a private pack to make it easier to add mods, so basically most of the Sky Factory 2 mods + some mods I added myself.

_**Description;**_
I opened the terminal and clicked the button that says "Crafting Status" and then game froze and crashed.

**Comment by Cisien** [comment]
what were you crafting at the time? Or does this happen on everything?
