### ISSUE TITLE
Small thing

### ISSUE THREAD

**Issue by TH3GOD88** [AppliedEnergistics/Applied-Energistics-2#2225]
I can't seem to shift click redstone, glowstone or glass into a pattern terminal when making patterns. Minecraft 1.7.10 AE2 rv2-stable-10

**Comment by bookerthegeek** [comment]
What patterns?

Do you have ic2 installed?

**Comment by TH3GOD88** [comment]
Yes; it seems to start doing it with more things than just those.

**Comment by thatsIch** [comment]
can you elaborate? not indev to try it out atm.

**Comment by bookerthegeek** [comment]
Simplistic explanation:

IC2 recipies will not shift clicked from the NEI "?" Into the crafting terminal. 

IC2 specifies that you can use damaged items in the recipies and as such they don't match for the pattern matching. You know things like glass, stone and it one bars.

**Comment by thatsIch** [comment]
damaged glass and stone? *confused*

**Comment by bookerthegeek** [comment]
The code for ic2 will accept damaged stone for example. This while technically not breaking anything,  causes shift clicking not to work in the crafting terminal. Surprisingly it does work in a vanilla crafting table.

**Comment by yueh** [comment]
#1552

**Comment by bookerthegeek** [comment]
Lol... thank you @yueh. Could not find that post.
