### ISSUE TITLE
Can't pull full item stacks out of AE system

### ISSUE THREAD

**Issue by emptyknight** [AppliedEnergistics/Applied-Energistics-2#2226]
A weird problem started when I updated my server to rv3 (appliedenergistics2-rv3-beta05.jar). I can only shift click item stacks of 52 in or out of the system. The number changes, and if I add more storage/interfaces/etc I can reach a point where nothing can be added to or removed from the system at all.  Storage is not an issue and neither is power.  This is a very large system - is there a soft limit on how many buses, interfaces, drives, etc can be on a single system?  Channels are turned off as I have a few younger players on the server who find them frustrating.

If I disconnect various parts of the network - tested with the autocrafting setup and a bee area with a subnetwork, the main network resumes full functionality. 

I'm using the Unabridged Modpack on the ATLauncher.  I also have AE2 Stuff, the correct version for rv3, which I tried removing with no difference, and Thaumic Energistics, which I haven't tested removing as that would break a ton of things on the server. I did disconnect all Energistics setups from the main network without any change in the problem.

I'm at a loss as to what to troubleshoot next. This hasn't caused a crash, so I don't have a log.

**Comment by XFactHD** [comment]
Your network seems to not get enough power. Try pumping more power into your system or adding additional storage by adding additional controller blocks or ae energy cells.

**Comment by emptyknight** [comment]
Ok I decentralized my energy cells by spreading them around the network and that seems to have fixed the issue. I had plenty of power but I guess the centralized power storage wasn't fully propagating around the network. Thanks for the suggestion.
