### ISSUE TITLE
Autocrafting simulation not outlining missing items?

### ISSUE THREAD

**Issue by KCar35** [AppliedEnergistics/Applied-Energistics-2#2227]
When i want to autocraft an item, it does not start and I know this is because it's missing certain items in the recipe. But the problem is that it doesn't outline the missing items. If i remember correctly, its suppose to be a red filled box on the item thats missing. This isnt a problem on small crafting recipes but when it comes to a complex crafting recipe, I have to read through every item to see what's missing. AE2-rv2

**Comment by VT-14** [comment]
Random shot in the dark, but are you using Compacting Drawers from the Storage Drawer mod?

**Comment by KCar35** [comment]
no, its The 1.7.10 Pack, and it doesn't have that mod in the pack.

**Comment by thatsIch** [comment]
Well, can only reverse engineer and take AE2 standalone and try it again..
