### ISSUE TITLE
Fluid being voided with P2P Fluid Tunnels and Fluid Pipes

### ISSUE THREAD

**Issue by JasonMcRay** [AppliedEnergistics/Applied-Energistics-2#2228]
#### Issue Description:

Fluid is being voided when inserting it with Fluid Conduits into P2P Fluid tunnels and extracting it on the other side into storage that is using the fluid, regulating the amount or not being able to transfer that much fluid.
#### What happens:

Fluid is being constantly drained from source when inserting into P2P tunnels with Fluid Conduits when the target storage is being constantly drained slower than the fluid is being inserted.
#### What you expected to happen:

Fluid not being voided at all. In the end there should be same amount of fluid as it was on input side
#### Steps to reproduce:
1. Connect tank with Pressurized Fluid Conduits into P2P Fluid tunnel
2. Connect IC2 Fluid Regulator (or anything else which is able to regulate the fluid amount passing though) and set the regulation to 1mB/t (or anything really low)
3. Put tank next to the regulator output
4. Start extracting the fluid
5. Fluid in the final tank will not match the amount of fluid at the start.

Screeshots:
Setup:
![2016-04-03_17 39 23](https://cloud.githubusercontent.com/assets/4236895/14233244/82990b02-f9c3-11e5-97b9-e72bcb212358.png)
![2016-04-03_17 39 39](https://cloud.githubusercontent.com/assets/4236895/14233249/974e2960-f9c3-11e5-8bc5-aed7a96290ee.png)
Begining of process (input tank with 16000mB of water, being extracted by fluid conduit):
![2016-04-03_17 39 31](https://cloud.githubusercontent.com/assets/4236895/14233267/e374df82-f9c3-11e5-93d4-e3111cbb8156.png)
Final (output tank with only 10000mB of water fed through IC2 Fluid Regulator set to 5mb/s, 6000mB is lost)
![2016-04-03_17 41 10](https://cloud.githubusercontent.com/assets/4236895/14233258/c520eb0c-f9c3-11e5-8d2d-d28f50b29b7b.png)

Also a video reproducing the issue (when transfering 256 buckets of liquid):
https://www.youtube.com/watch?v=5sf6j-GUdwA&feature=youtu.be

---
#### Affected Versions
- EnderIO: 2.3.0.424_beta
- EnderCore: 0.2.0.32_beta
- Minecraft: 1.7.10
- Forge: 10.13.4.1566
- AE2: rv3-beta-5

**Comment by JasonMcRay** [comment]
workaround:
use one gt pipe between fluid conduit and p2p

**Comment by JasonMcRay** [comment]
Thanks to @HenryLoenwind I did little bit more testing. P2P tunnels seem to accept anything you put into them, but they void what can't be put anywhere: https://github.com/SleepyTrousers/EnderIO/issues/3255#issuecomment-205461935

And the workaround i posted above does not actually work.

**Comment by nailfor** [comment]
double https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2195

**Comment by skython** [comment]
I'm having the same problem using P2P between RailsCraft Tanks and Binnie's Genetics Machines. The tanks are always empty even though my fluid production is 10 times higher than the fluid usage.

It feels like the whole tank is simply emptied by p2p if some fluid is needed somewhere.

**Comment by paboldin** [comment]
Any updates on this? This is really annoying -- we wanted to build a IC2 fluid reactors with this.

**Comment by fscan** [comment]
Fixed in rv4 dev and rv5 release. rv3 is not supported anymore at this point.
