### ISSUE TITLE
Is there a way to add custom recipes with optional output?

### ISSUE THREAD

**Issue by rehv** [AppliedEnergistics/Applied-Energistics-2#2229]
As title says, is there a way to add a custom recipe with optional output(s)? 

For example, adding a grindstone recipe for Certus Crystals with 10% chance for an additional dust.

If there isn't... would it be easy to add? I'm looking for a solution other than creating an add-on or something.

Thanks in adv!

EDIT: Just to clarify, I'm talking about the text-based .recipe files we can tweak in the config folder.
EDIT2: I'm using rv2-stable10

**Comment by mindforger** [comment]
no there isn't, this has been asked and answered a lot of times, please use the search next time :) ... no rant, even if it sounded like one

**Comment by rehv** [comment]
really? a quick search for "optional" didn't result in any results about this kind of question... maybe I'm searching the wrong way then. Time to code some recipes :+1:

**Comment by mindforger** [comment]
you could always preprocess all recipes with additional outputs automatically to a defined amount or until the source has reached a defined minimum amount using export busses with redstone cards and level emitter

**Comment by rehv** [comment]
Well, I just wanted to change some recipes. Some of the default recipes are a bit too harsh for some extensive networking, and simply increasing the output amount of some of those is a bit overboard, so I wanted to add chance to the formula. Anyway, thanks for the insight, very helpful. :)
