### ISSUE TITLE
Sky chest crash

### ISSUE THREAD

**Issue by PolymerBoy** [AppliedEnergistics/Applied-Energistics-2#2233]
This is a crash that is of the type that you wouldn't think anyone would do.

Basically, I opened a sky stone chest, and during the lag in which it was opening, I broke it. I immediately crashed. 

Like I said, you wouldn't expect anyone to try this.

**Comment by mindforger** [comment]
when you crash, there is a crashlog, please attqach it or paste it on pastebin and post the link, do NOT textwall it directly :)
