### ISSUE TITLE
GUI display problem for interfaces and inscribers

### ISSUE THREAD

**Issue by charlesbevans** [AppliedEnergistics/Applied-Energistics-2#2236]
I'm running an unmodified FTB Infinity expert 2.4.2 SSP, direct load (no separate server), but I've had this issue on other packs.
The interface... interface shows the stocked items row offset from the GUI image (see picture).
The inscriber also shows an offset, in this case the full completion bar is always visible as full and offset from the GUI. There is no completion bar present when processing (see picture).
![screen shot 2016-04-08 at 9 27 17 am](https://cloud.githubusercontent.com/assets/15851438/14390557/8e1bc6b6-fd6c-11e5-9bdd-16ef25bb0499.png)
![screen shot 2016-04-08 at 9 26 57 am](https://cloud.githubusercontent.com/assets/15851438/14390556/8e1b9628-fd6c-11e5-9837-a76045da01aa.png)

**Comment by VT-14** [comment]
AE2 semi-recently changed their interfaces from having 8 slots to having 9.  Either your texture pack hasn't updated yet, or you are on an old version.

**Comment by charlesbevans** [comment]
Thanks. I'll look for an update to the pack.

**Comment by charlesbevans** [comment]
If I could tag on an unrelated graphics question, I've been having an issue with random items having messed up textures. The texture seems improperly loaded (sometimes I recognize part of another item) and flashes the entire square. Every time I load it's a different item and has no game effect. This even happens with no resource packs loaded. Any ideas?
