### ISSUE TITLE
Issuse with thermal expansion

### ISSUE THREAD

**Issue by wurian** [AppliedEnergistics/Applied-Energistics-2#2237]
I was configuring a Phytogenic isolator in my Skyfactory 2 world. Once I configured a side facing into an import bus to a grey input/output the game crashed and i havn't been able to load my world since. 
[crash-2016-04-10_18.20.38-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/214072/crash-2016-04-10_18.20.38-server.txt)

**Comment by wurian** [comment]
If there is any information i could provide that i havent please let me know. I am realticly new to github and such. Please I just want to be able to play on my skyfactory 2 world again.

**Comment by mindforger** [comment]
your mods are waaaay outdated, please update all of them to the latest (some beta)
AE2-rv3-beta
EIO-beta
and all of that COFH stuff

**Comment by wurian** [comment]
I have updated Ae2, Thermal expansion, foundation, and dynamics, CofhCore, TabulaRasa, MinefactoryReloaded, and Waila. I also updated my forge to version 1.7.10-10.13.4.1448. At first it I used the new Ender io Version 1.7.10-2.3.0.424_beta. My forge client told me to use Endercore1.7.10-0.2.0.31_beta. Then I had a conflict with TTcore and Endercore as they can not run together. I then removed TTcore. My client did worse on start and stated it needed TTcore. After that I reverted to the original Ender io, removed EnderCore and added back TTcore. My client will load til the last step I.e. "finishing up" and will immediately crash. 
[crash-2016-04-12_13.52.14-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/215928/crash-2016-04-12_13.52.14-client.txt)

**Comment by wurian** [comment]
I have got my laucher to load completely by keep AE2 version rv2. It seems updating the Cofh and stuff fixed the problem.

**Comment by mindforger** [comment]
that was what i expected from this crashlog, but till AE2 rv2 is a bit outdated, you should at least switch to rv2-stable

**Comment by XFactHD** [comment]
You should look for the mod that needs ttCore and update it, in one of the comments on the curse page of ttCore tterrag1098 said that all the mods depending on ttCore have been updated to EnderCore.
