### ISSUE TITLE
level emitter compare two items

### ISSUE THREAD

**Issue by trad-emark** [AppliedEnergistics/Applied-Energistics-2#2238]
Hi,
I am thinking of a feature to the level emitter to make it able to compare two distinct items.
For example to keep crafting glass as long as you have more sand than glass.
Changeable equation would be also great (e.g. emit signal when you have more sand than 5 times glass + 100).
It may require some upgrade card. Or perhaps placing it in front of storage monitor.
Thanks for considering it.

**Comment by leagris** [comment]
You can already to whatever complex computation rules if you use OpenComputers Mod. You can access ME Inventory, compute and trigger control smelting of glass with redstone. All this in LUA.

**Comment by VT-14** [comment]
It would be convenient for this kind of advanced logistical feature, and a few others, to be available with only AE and Vanilla.  The tools already provided are quite versatile, so there probably is a way to do it already; thought it likely takes a lot of space and is taking sub-netting to the extreme.

It would also be nice for knowing how to program (in LUA) to not be a requirement for such advanced features.  I've only taken an introductory programming class and can read and write (very) basic code, but it still took me several hours to write a simple digital clock with ComputerCraft.

**Comment by thatsIch** [comment]
Level Emitters should output signal strength depending on the inventory amount. Afaik you can compare 2 different signal strenghts in vanilla minecraft.
