### ISSUE TITLE
Duplication Bug with Grindstone and Portal Gun

### ISSUE THREAD

**Issue by Kaupenjoe** [AppliedEnergistics/Applied-Energistics-2#2239]
When you pick up a Grindstone with a portal gun the contents of the grindstone spill onto the ground but also remain inside the Grindstone, doubling whichever ore/dust is inside. 

Happens in the 2.5.0 Version of FTB Infinity with:
Applied Energistics 2 rv3-beta-5
Portal Gun 4.0.0-beta-6

**Comment by mindforger** [comment]
did you report that also to reika? this sounds more like a problem of how it is removed ?!

**Comment by XFactHD** [comment]
PortalGun is not from Reika, it is from iChun. :)

**Comment by mindforger** [comment]
my fault, sorry

**Comment by MinDoth** [comment]
It also works with the ME Drive. If there's storage cells in the drive, and you pick it up with a portal gun, it drops copies of the storage cells, but the original cells are kept too.

**Comment by yueh** [comment]
If a portal gun causes an AE TE to drop their inventory, it has to call `Block.breakBlock()`.
So anything which has a special behaviour for this will cause undefined behaviour when breaking and cloning/duping the block simultaneously.

As long as `breakBlock()` does not state something like "you are not allowed to drop anything when called", I would say it is an issue with portal gun.
