### ISSUE TITLE
feature request: crafting loop

### ISSUE THREAD

**Issue by Marius8** [AppliedEnergistics/Applied-Energistics-2#2241]
Hello,

when producing _Refined Iron_ in IC2 (experimental), you need one _Iron Ingot_/_Iron Dust_ and 6 _Compressed Air Cells_ and get as an output one _Refined Iron_, one _Slag_ and 6 _Empty Cells_.
You produce a _Compressed Air Cell_ in a Compressor, using an _Empty Cell_.

My request is, for the crafting system, to identify that loop, and only uses an as low as possible amount of _Compressed Air Cells_ (eg. 12 for two cyles, or 10% of the needed amount, but not all 600)

![screenshot_3](https://cloud.githubusercontent.com/assets/10903611/14567568/ee10b46e-0334-11e6-857b-d7c2f2b89e6b.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/10903611/14567567/ee0e30cc-0334-11e6-89e9-85c017c88863.png)
![screenshot_5](https://cloud.githubusercontent.com/assets/10903611/14568307/9b4e0200-0338-11e6-9be4-0c1deea8dafa.png)

**Comment by thatsIch** [comment]
At that point of time of the pre-calculation you can not assure that for all possible crafting operations the pre-required matieral is available if we would allow results of prior craftings into the next cycle. 

But you can do this by crafting a single one and in multiple steps until a threshold is reached.
