### ISSUE TITLE
SFM compression with AE bug

### ISSUE THREAD

**Issue by DynoEnviro** [AppliedEnergistics/Applied-Energistics-2#2242]
Playing on FTB Infinity 2.4.2 server. Using SFM to automate compression of items (dirt cobble lapis etc.)  with simple SFM program (Trigger>Input>Crafter>Output) using a SFM inventory variable (Energistics Connector) for the i/o. I've used this setup many times with no problem, but this is the first time on Inf. 2.4.2.

Setup (image) is a simplified recreation in creative mode with 1x 1K ME storage. Placed 64 Dbl Comp cobble and 64 Lapis in the AE system to compress, and then hooked up the trigger in SFM. What happens is the materials are compressed but the resulting products seem to then be duplicated until the available AE storage is full (image).

I've tested the SFM program apart from the AE system (i.e. Chest>SFM program>Chest) and it works fine. Tore down the old system and rebuilt from scratch and the problem persists.

![2016-04-15_13 26 00](https://cloud.githubusercontent.com/assets/18488403/14569775/c26142f0-030e-11e6-9d87-5410d931c695.png)
![2016-04-15_13 26 12](https://cloud.githubusercontent.com/assets/18488403/14569776/c267353e-030e-11e6-9b10-f2aea22b8f4a.png)

**Comment by DynoEnviro** [comment]
So I dumped this to the reddit forum and it got legitimately pulled. This is further analysis info:

It doesn't seem to be a problem with the crafting aspect. I tried dumping ~250 marble from the AE system to a chest, and that worked. However, when I flipped the SFM program around and dumped it back into AE, it duplicated the marble up to 6464 (but did not fill the AE system up like it does with compression, which makes sense if you figure that each time the cobble was compressed and dumped back into the system, it was duplicated, then the compressed cobble was pulled out, crafted to dbl comp cobble, dumped back to AE <duplicated>, dbl comp cobble pulled out ... etc. etc.).

**Comment by DynoEnviro** [comment]
Just some further testing - I created a new world on the server, went into creative, and constructed a minimal system with just an ME controller, energistics connector, factory manager, ME drive with 1K storage, resonant energy cell, ME crafting interface, 1 cable manager, 1 diamond chest. Hooked up similar to above. Tried the basic compression program in Steve's (trigger, input, craft, output) from and back to AE. Tried several different materials (cobble, iron, diamond) and they all duplicate and fill up the ME storage when Steve's puts them back into AE. Tried same Steve's program using a chest as inventory and it worked fine.
 AE. Tried several different materials (cobble, iron, diamond) and they all duplicate and fill up the ME storage when Steve's puts them back into AE. Tried same Steve's program using a chest as inventory and it worked fine.

**Comment by mindforger** [comment]
you could probably add details on which version of AE2 and forge you are using ... i did the work you were supposed to do and downloaded the whole pack 222MB just to get those informations (at most 4kB) you could already have provided :)

FTBServer-1.7.10-1614
AE 2 RV3 B5
StevesFactoryManagerA93.jar

and change the title to "duplication bug" and add a few comprehensive lines in front of your text as it it a bit hard to understand the actual issue with all that "how i built it" around the important info 

i really meant this as positiv criticism as it may sound harsh or sarcastic in some way

**Comment by thatsIch** [comment]
just my assumption but by directly injecting it into the system it gets duplicated. What about if you are using pipes? If pipes works, then it should be on the side of SFM

**Comment by XFactHD** [comment]
The Energistics Connector is from Steve's Addons and was already known in the past to create problems like this.

**Comment by yueh** [comment]
Known for over a year and they refuse to fix it.

Simply consider it a feature, because fixing it would require one of these solutions

1. Rewriting SFM, because it is designed to dupe anything and only tries to cleanup these dupes without verifying its success. As its core inventory handling.
2. Completely remove the AE integration.
3. Turn it into a huge performance issues, because it has to simulate an extract/insert of every item inside the network for every single operation it does. Even when just checking a single item.

**Comment by DynoEnviro** [comment]
No problem; I'll update the post tonight with your input. I thought "FTB
pack 2.5.0" was self-indicating for the mod versions - my bad!
On Apr 27, 2016 1:35 AM, "mindforger" <notifications@github.com> wrote:

you could probably add details on which version of AE2 and forge you are
using ... i did the work you were supposed to do and downloaded the whole
pack 222MB just to get those informations (at most 4kB) you could already
have provided :)

FTBServer-1.7.10-1614
AE 2 RV3 B5
StevesFactoryManagerA93.jar

and change the title to "duplication bug" and add a few comprehensive lines
in front of your text as it it a bit hard to understand the actual issue
with all that "how i built it" around the important info

i really meant this as positiv criticism as it may sound harsh or sarcastic
in some way

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2242#issuecomment-214976230>

**Comment by DynoEnviro** [comment]
That does work,  or simply using a separate chest hooked up to the Steve's
leg, and then moving items back to AE after compression, but this is a real
PITA . Others have said this bug has been around for a long time,  but I've
never experienced it before Infinity 2.4.2 in very similar setups.
On Apr 27, 2016 5:54 AM, "thatsIch" <notifications@github.com> wrote:

just my assumption but by directly injecting it into the system it gets
duplicated. What about if you are using pipes? If pipes works, then it
should be on the side of SFM

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2242#issuecomment-215034746>
