### ISSUE TITLE
Applied Energistic 2 at 1.8.0

### ISSUE THREAD

**Issue by Araton10** [AppliedEnergistics/Applied-Energistics-2#2244]
Hi , sorry to disturb you so much, but how long will it take to get AE2 for the 1.8.9 version

**Comment by MRebhan** [comment]
You can try to compile it yourself, there is already a 1.8.9 branch, no guarantee that it works though.
I want it myself, trying to compile now

**Comment by thatsIch** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1637

still no real work done though..
