### ISSUE TITLE
Me system terminal

### ISSUE THREAD

**Issue by XxFrankiexX** [AppliedEnergistics/Applied-Energistics-2#2245]
I joined a multiplayer server and i made everything needed for the me and the terminal won't open please help me

**Comment by mindforger** [comment]
first of all this is not some sort of forum, so this kind of question does not really belong here until you encounter something really strange along a normal working system :)

maybe you should have a look at youtube and the depending mod spotlights, but be aware to look what version this spotlight is about and if it matches your game version
