### ISSUE TITLE
Using Technicolor Essence in Color Applicatior

### ISSUE THREAD

**Issue by yannick9906** [AppliedEnergistics/Applied-Energistics-2#2246]
It would be very nice if you could use the technicolor essence from Magical Crops in the Color Applicator. With the Technicolor Essence you can create every color there is from 3 Essences. So the Color Applicator could use 3 Technicolor Essence for every color.

**Comment by Cisien** [comment]
I don't think this belongs in AE2. You can easily set up auto crafting to create the dye for the applicator without bypassing at least 1 part of the mod entirely.
