### ISSUE TITLE
Duplication bug with Portal Gun and ME Storage Drives

### ISSUE THREAD

**Issue by robpo4** [AppliedEnergistics/Applied-Energistics-2#2247]
Upon picking up the ME drive block with a portal gun the picked up block goes invisible and supposedly drops the  storage drive, In my case a single 4k drive. But on placing the invisible blocking back down the drive is still in the inventory and I now have an extra drive.

Happens in: FTB Infinity Evolved 2.4.2

**Comment by XFactHD** [comment]
This interaction should probably be blocked anyways because the massive amounts of NBT data a drive can have regularly causes issues when using mods that can transform a block into an entity or item for transport.

**Comment by robpo4** [comment]
I tried it again with the drive inside it in use or containing items and it duplicates everything.

**Comment by yueh** [comment]
#2239
