### ISSUE TITLE
Client crash when rendering crafting monitor

### ISSUE THREAD

**Issue by MilkMC** [AppliedEnergistics/Applied-Energistics-2#2249]
I am playing FTB Infinity 2.4.2. I first noticed this crash after updating my java and it happens whenever I get near crafting monitors. I have since downgraded twice and the crash continued to happen so I determined it wasn't java. I looked in the error log to see if I could find what was causing the crash (see here: [http://pastebin.com/PjTckEUh]) and I found a few lines about rendering the crafting monitors. I canceled all my crafting jobs and then replaced all the crafting monitors with co-crafting processors. It all works fine now that the crafting monitors have been removed. Also I should mention that it only seemed to crash when I was crafting items with a lot of crafting steps (I was crafting ultimate solar panels from solar expansion), I didn't have any trouble with crafting items with only a few crafting steps.

**Comment by thatsIch** [comment]
this looks like a strange bug, even more if you craft "slower"

does this also happen with the latest version? 
It seems to choke on the call list call which is just an integer..

**Comment by yueh** [comment]
Broken intel graphics driver. If possible, update them. Otherwise you are probably out of luck or have to wait for a new version.

Would it be an issue with AE or at least another itemrender, it would already crash during the creation of the displaylist. Not when calling it.

**Comment by bookerthegeek** [comment]
@MilkMC are you on an integrated graphics? If so install a Java version 57 or below.

**Comment by idnthvn** [comment]
i can confirm this with 3 clients on my server
all with update java 8
