### ISSUE TITLE
Me wireless terminal not charging in project ozone

### ISSUE THREAD

**Issue by bojosos** [AppliedEnergistics/Applied-Energistics-2#2250]
It sucked 80 million rf and it didn't charge

**Comment by VT-14** [comment]
This should probably be reported to the modpack author.

At the very least, you need to include a TON of details.  For instance, how are you trying to charging it?, what versions of the mods and Forge do you have installed, etc.

**Comment by thatsIch** [comment]
sounds like modpack issue. please always report to modpack authors first and then the mod as long you are not using standard configs.
