### ISSUE TITLE
Not a issue But a feature request

### ISSUE THREAD

**Issue by drozone69** [AppliedEnergistics/Applied-Energistics-2#2251]
Its about the anniliation planes..would there ba any chance u gguys could add a gui just like the formation plane to be able to pick up certain stuff not just everything like a filter

**Comment by XFactHD** [comment]
This has been requested multiple times already and it has been denied every time.

**Comment by thatsIch** [comment]
the intended way is to filter it through your network

**Comment by drozone69** [comment]
yea but wat if u wanna use for botania to automate the living stone and living wood

**Comment by helmutfork** [comment]
You make a sub-network that contains just the annihilation and formation planes, along with a storage device and ME interface.  Use the ME interface as your input, anything dumped into it (wood or stone) will automatically be shunted to the formation planes.  Make sure to setup the filter on the formation planes to only accept your input (wood and stone), that way they will not try to place the living wood or living stone.  Setup your storage device to only be able to store the living stone and living wood, that way the annihilation planes will only pick up the blocks that can be stored in your storage.  Then you setup an input off your main ME network that connects to that storage.  I've created this setup a few times and it works every time.  Sorry I don't have any screenshots.
