### ISSUE TITLE
Firing Singularities

### ISSUE THREAD

**Issue by Darinth** [AppliedEnergistics/Applied-Energistics-2#2252]
So... I'm not certain why it occurred to me but it's stuck in my head for a few days now... any chance of getting the ability to fire singularities with the matter cannon? I know firing singularities in reality is like a world-ending catastrophe, but since we blow them up with no real ill effect figure that firing them couldn't be to bad. Right? ^_^

**Comment by thatsIch** [comment]
We had that topic few years ago,
I think the matter cannon is just not much of a cannon to fire a singularity. We thought about something like a defense tower. Also the potential of griefing would be too big. It would be probably deactivated per default and needs to be activated by the server admin intentionally.

**Comment by Darinth** [comment]
That's fair enough. I'd contemplating suggesting something more grand then just allowing the matter cannon to fire them (as yeah... it just doesn't feel like the right tool for the job...) but felt like it was the simplest solution to giving my growing stack of singularities a cool use. It seems like perhaps the better choice to disabling it by default would be to disable it's griefing potential by default.

Make it fire a singularity that is slow moving, pulls in non-player entities, and damages anything in it's area. As an alternative, make it spawn the singularity entity at a location, it sticks around there for a bit and pulls in entities and damages them in the same way. Make config modifiable to also pulls in players  and/or damages terrain.

**Comment by thatsIch** [comment]
yea, there is no limit to the imagination what something like that can do. Sadly we are lacking in the rendering and animation department. Somebody like Vazkii could do it probably in 2 days xD

**Comment by Darinth** [comment]
Vazkii & Azanor both do some fantastic work graphically (and technically). I can't make pretty things to save my life, so I'm certainly not going to complain.

**Comment by CraftMinerKyle** [comment]
I have a few comments on how it could be made cool and very dangerous, but no help on textures and code, as I can't even make my own mods work without CraftBukkit. Lel.
1: When fired, a loud electrical zap/explosion occurs from the barrel.
2: A spiraling smoke/lightning trail follows the projectile.
3: Upon projectile impact the projectile entity disappears and a Black Hole block/entity is spawned. The black hole can suck in blocks and entities within a configured radius and do increasing damage as you get sucked closer.
4: The Black Hole should be increasing in size as it wears out, and eventually explode after about 30 seconds. Once the Black Hole wears out, a small explosion should occur.
5: There should be some sort of residual effect/scarring that cannot be cleaned up easily.

**Comment by CraftMinerKyle** [comment]
Something like a Thaumcraft Hungry Node.

**Comment by AzazeII** [comment]
Something like this?
![Screenshot 2019-03-22 at 11 28 26](https://user-images.githubusercontent.com/32298517/54812576-7307a200-4c9c-11e9-8662-43da3d2f825f.png)

And there is base for ME Defence tower:
![Screenshot 2019-03-22 at 09 52 12](https://user-images.githubusercontent.com/32298517/54812593-7f8bfa80-4c9c-11e9-882d-47d33197c5bf.png)

What you think?

**Comment by AzazeII** [comment]
Answer after 2 years, _**nothing new**_

**Comment by RonRicoSuave** [comment]
If it's going to cause world destruction and hence the corresponding tank in frame rates ala the old red matter bombs (but hopefully not anywhere near that messy) or anything else causing a non-small number of block updates I'd suggest tossing in the fragment shader from here (p. 32):

[Visualizing Gravitational Lensing Phenomena in Real-time using GPU shaders in celestia.Sci](http://dwj.freeshell.org/work/file/djung_ipr.pdf)
