### ISSUE TITLE
p2p tunnel me coused laggs

### ISSUE THREAD

**Issue by Dominikzocker141** [AppliedEnergistics/Applied-Energistics-2#2253]
Hi the p2p tunnel me coused lagg spikes 
example here:
![2016-04-26_17 51 05](https://cloud.githubusercontent.com/assets/13309895/14824815/92e52088-0bd7-11e6-8fe0-206615d64c12.png)
the blue and yellow lag spikes are from the ae2/me!

**Comment by mindforger** [comment]
is everythign properly chunkloaded?
reevaluation of such complex structures may cause lag spikes if parts of the network are constantly are loaded and unloaded again

**Comment by thatsIch** [comment]
http://ae-mod.info/profiling/
