### ISSUE TITLE
[Feature Request]: P2P Tunnel indicate available channels (mouseover or visual)

### ISSUE THREAD

**Issue by idgarad** [AppliedEnergistics/Applied-Energistics-2#2255]
After attempting a complex and dense setup seeing what available channels are left on the p2p tunnel was problematic. Normally I would put a P2P-> DENSE CABLE->ME Controller to watch how many channels are left but for compact setups with the p2p source directly on the ME Controller there is no practical way to see how many channels are passing through. Any chance of either a mouseover indicator or visual indicator (the number perhaps on the p2p backside) to make it easier to track channels in use on compact setups? This would be handy at both the source p2p unit and any linked p2p units.

**Comment by VT-14** [comment]
I think that's a little out of scope for the P2P tunnel.

P2P doesn't cover the entire face of a block, so I think it would be cool if the ME Controller could show how many channels each side was using.  It could be more in line with the current way of showing channels by changing the brightness of lines on the controller.


A HUD indicator would be a suggestion better suited for one of Waila's (or the next popular iteration) add-ons.

**Comment by XFactHD** [comment]
You can achieve this with a utility item from the AE2Stuff mod.

**Comment by yueh** [comment]
As already said, out of the scope for a P2P tunnel. Their job is to only tunnel connections. Not visualize them, which is the job of smart/dense cables.
