### ISSUE TITLE
AE2 P2P Crafting isn't working

### ISSUE THREAD

**Issue by ScottyNitro17** [AppliedEnergistics/Applied-Energistics-2#2259]
So ever since AE2 was released I had a setup that I have used on about 7 differant packs over the last year now but lately in the latest RR3 and now in FTB Infinity Skyblock my setup no longer allow's me to get Interfaces to work with the crafters or other machines

My setup:
![javaw 2016-05-01 22-35-57-48](https://cloud.githubusercontent.com/assets/19138854/14944567/ce2c7c48-0fee-11e6-900c-eaa4bec840de.png)

I use this all the time but now it just won't display items that can be crafted at all, They connect and go online but that's all it does, Just sits there looking pretty but not working how it originally did for me, If anyone has some advice for me I'd highly appreciate it, I don't want a few thousand miles of dense cable all over the place :P I like my P2P tunnels xD

Thanks

**Comment by Deathlymad** [comment]
I have a very similar issue, what version are you using?

**Comment by bookerthegeek** [comment]
Please edit your post to follow the guidelines [HERE](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/CONTRIBUTING.md).
