### ISSUE TITLE
Storage Bus facing ME Interface to AE Network

### ISSUE THREAD

**Issue by Sorbe** [AppliedEnergistics/Applied-Energistics-2#2261]
Bug shows up in FTB IE 2.5.0  (this worked earlier in FTB IE 2.2.2)

To get annihilation planes to only grab specific items, you used to be able to connect them in a subnet to a storage bus facing towards an ME interface.  There are youtube videos showing this working and I know it worked in FTB IE 2.2.2 as I was using it for growing pure crystals.

Connect an Annihilation Plane to a Storage Bus facing an ME Interface on a AE2 Network.
Bridge power only from the ME Int to the AP/SB subnet using a quartz fiber to get the subnet up.

```
AP--SB | MEInt === AE Network
     +_ _+
```

Unlike earlier versions of AE2, the SB will not accept items from the AP in this scenario.
The SB apparently does not consider the ME Interface as storage and refuses to accept items.

If you rebuild this using a chest it works - but complicates this whitelist scenario further.

```
AP--SB | Chest | ME Import === AE Network.
     +______________________+
```

Was the SB intentionally modified to block putting items into an ME Interface?

**Comment by Cisien** [comment]
What changed between the versions of FTB IE?

**Comment by XFactHD** [comment]
If you have a security station on your main network, remove the biometric cards in it and the interface should be able to accept stuff.

**Comment by Sorbe** [comment]
Curious.  While I do have Wireless controllers, Access Points and a Security Station, there are no biometric cards in the SS.

**Comment by bookerthegeek** [comment]
Try with a blank general permission card in the ss

**Comment by Sorbe** [comment]
A Biometric Card with all permissions set in the Security Terminal makes this work again.

If this is intended behavior, perhaps it should be described better in the wiki/documentation.

**Comment by bookerthegeek** [comment]
True. I'll see what I can do about that.

**Comment by taesheren** [comment]
I just want to clarify that a blank Biometric Card with permission to deposit items only, will suffice.

I was having this problem with an interface not depositing items into a subnetwork containing a Security Terminal. Interfaces on the same network level as the ST were working as usual. This suggest that the Security Terminal only checks deposit permissions upstream.

If this isn't useful to anyone, I'm sorry for necroing this issue.
