### ISSUE TITLE
ME Network Crashs

### ISSUE THREAD

**Issue by Greg413** [AppliedEnergistics/Applied-Energistics-2#2262]
I have a ME Network on a Server. Sometimes however the complete Network goes offline. No Import or Export busses are working. No Drives. But we can still open every Interface like everything is ok. 

I already Checkt:
-Powersource
-Used Channel
-Additional Mods for AE2 ( Extracells)

Nothing really helps.

Maybe this is a bug or i´m an idiot.

Hope someone can help me.

**Comment by XFactHD** [comment]
Did you already try adding more ae energy cells to the network?

**Comment by mindforger** [comment]
and chunkload the whole area?
