### ISSUE TITLE
Getting project to run in eclipse

### ISSUE THREAD

**Issue by WinterGrave** [AppliedEnergistics/Applied-Energistics-2#2264]
When I try to run the project on eclipse, I get a class not found exception.

Here's the log: http://pastebin.com/ZbXEXkKk

I have already setup the project running 
gradlew setupDecompWorkspace --refresh-dependencies
and
gradlew eclipse

**Comment by mindforger** [comment]
try again and follow the whole setup process like described in the readme and see if that helps, it looks like you are mising files or have a broken download
>    Decompiled source gradlew setupDecompWorkspace
    Obfuscated source gradlew setupDevWorkspace
    CI server gradlew setupCIWorkspace
    Build gradlew build. Jar will be in build/libs

and why the heck do i have the close button O_o

**Comment by XFactHD** [comment]
I have it, too :)

**Comment by WinterGrave** [comment]
Had done that multiple times with the same reuslt. Also forgot to mention I am on 1.8.9-rv3 branch

**Comment by thatsIch** [comment]
@mindforger whitelisted Mod with additional capabilities. I granted active community contributers the privilege to this repository to manage it.
