### ISSUE TITLE
Autocrafting GUI won't show

### ISSUE THREAD

**Issue by SmokeyTheBandicoot** [AppliedEnergistics/Applied-Energistics-2#2270]
Randomly, when I try to autocraft anything in a terminal the guy with +1,+10+100 etc doesn't show up. If I try to see crafting status I got disconnected and redirected back to main menu (playing SSP). No crashes, just this log http://pastebin.com/AepFWtKX of when I get disconnected

**Comment by Ronaldi2001** [comment]
I was just playing and the same thing happened to me, I just don't get disconnected from my world I stay on.

**Comment by Ronaldi2001** [comment]
@SmokeyTheBandicoot After a couple of hours of testing I found out that it is AE2 Stuff's fault for the gui not showing up, and it is not AE2's fault.

**Comment by Ronaldi2001** [comment]
@SmokeyTheBandicoot do you have any AE2 addons in the pack that you are playing??

**Comment by SmokeyTheBandicoot** [comment]
Yes, AE2 stuff, Wireless Crafting Terminal, Thaumic Energistics

**Comment by Ronaldi2001** [comment]
@SmokeyTheBandicoot it is wireless crafting terminal. I deleted it and I haven't had problems.

**Comment by SmokeyTheBandicoot** [comment]
Maybe it has been fixed in the last version of WTC. Unfortunately I didn't and still don't have enough time to test, due to exams.

**Comment by p455w0rd** [comment]
yes these WCT issues have been fixed...also getting ready to upload a new update atm which implements the API and fixes NEI shift-clicking [?] not working when out of range of the WAP..when you experience issues like this and discover that WCT was the cause, I would truly appreciate posting an issue to the WCT repo =D
