### ISSUE TITLE
Suggestion: Removing removed mod items. 

### ISSUE THREAD

**Issue by border999** [AppliedEnergistics/Applied-Energistics-2#2275]
Shouldn't it stand to reason that if a mod is removed from a modpack, that all of its data be removed as well. I believe your ME system doesn't follow this general rule. Mind looking into it?

**Comment by mindforger** [comment]
how in the world should the AE mod know which parts to remove from the world it self has formerly been removed from?

**Comment by ktole1999** [comment]
once a mod is removed any items pertaining to that should also be removed, correct?

**Comment by XFactHD** [comment]
The OP is not talking about items and blocks, he is talking about the special files AE2 puts into a world save folder. While the items are removed by FML/Forge, FML/Forge doesn't have the knowledge that those files are from a mod that got removed, only the mod those files are from also knows about their existence.

**Comment by ktole1999** [comment]
no way for the server to know that unless there is an uninstall process that is performed. thats admin/owner job. sorry for misreading post.

**Comment by yueh** [comment]
That is already done by vanilla minecraft, except for items with changed metadata.
If minecraft cannot detect them as missing, neither can we.

In terms of cells this might not happen instantaneous, but should when the inventory updates or at least once it was emptied by an IO port.
