### ISSUE TITLE
Terminal doesnt show items when entering new dimension? 

### ISSUE THREAD

**Issue by armyxreload** [AppliedEnergistics/Applied-Energistics-2#2277]
My costume modpack runs the latest version of ae2 (1.7.10) but when i go to enter lets say the deep dark and when i return all the items in my terminal vanish, I can only see them with my wireless thing? Only way i can see them is by backing up my world and not entering the deep dark but this kinda gets rid of a lot of the things i want to do. (Does it with mystcraft worlds to)

**Comment by armyxreload** [comment]
Here is my crash report if it helps :/ http://pastebin.com/1QQwN2Ms

**Comment by yueh** [comment]
AE2Stuff issue.

**Comment by armyxreload** [comment]
I thought the same but after removing and backing up i still have the same issue?
