### ISSUE TITLE
Multiple P2P in same block issue

### ISSUE THREAD

**Issue by emperor06** [AppliedEnergistics/Applied-Energistics-2#2279]
It happens with RF P2P (real case) but it probably also affects other types of P2Ps.

If two RF P2P destinations are within the same block and have the same source, one of them will not work. It's like both tunnels are considered the same object because they have the same coordinates and frequency (not sure what actually happens internally).

![p2prf](https://cloud.githubusercontent.com/assets/9116243/15285979/dbca146a-1b5a-11e6-82c8-b161d0683a2a.jpg)

On this screenshot, the source P2P (in the middle) receives power from an energy cube.
It has 2 output destinations (left and right) which are both in the same block. Only DEST 1 (on the left) transmits the power. DEST 1 is the first one I clicked with the memory card.
If I apply getOutputs() to the source tunnel, I get a list of size 1 instead of 2.

AE2 rv3beta5
Forge 10.13.4.1558

**Comment by XFactHD** [comment]
Can you reproduce this with EnderIO conduits or ThermalDynamics ducts?

**Comment by emperor06** [comment]
Yes. I have actually discovered the issue with a tesseract as source and cryo-stab ducts on destinations. Same happens with a bank capacitor and energy conduits.

**Comment by mindforger** [comment]
i know that IC2 Power has no facing direction, so multiple EU P2P in one block is impossible but RF should be IMHO

**Comment by fhntv24** [comment]
> i know that IC2 Power has no facing direction, so multiple EU P2P in one block is impossible but RF should be IMHO
It's wrong ... MFSU has diff. sides to do diff. things. Some output, and other input. You always can do this... Btw, cables do this too. They have two output sides. So you are wrong, or you need to reference IC2 API where it saying this.
Also this is AE core issue ( i think .. ) with P2P, and not actually with RF API.

**Comment by mindforger** [comment]
half wrong, AE implemented only IEnergyAcceptor and IEnergyEmiter and those had no direction component in the past as far as i can remember that discussion ... i am wondering where this issue has gone ...

**Comment by emperor06** [comment]
I don't think it has anything to do with RF. As I said, this probably affects other types of tunnel.
The key here is when I list the outputs of the source tunnel, I get only 1 destination tunnel instead of 2. What I plug on the tunnels don't even matter.

If the 2 destination tunnels are within the same block but have different source, then it works.
When you right-click a tunnel with a memory card, you add it to its source's output list and this doesn't seem to happen when both destinations are in the same block and have the same source.

Here's the same issue with fluids. A bedrockium drum of water plugged to a source Fluid P2P, and 2 Fluid P2P linked to that source. One of them successfully fills the tank (bottom), the other stays empty. No RF API involved here.

![2016-05-17_18 57 07](https://cloud.githubusercontent.com/assets/9116243/15331530/09eb7548-1c62-11e6-9821-04957fbd5256.jpg)

**Comment by emperor06** [comment]
And the same issue with ME P2P. Note that only one Terminal gets powered. The other is offline.

![2016-05-17_19 12 09](https://cloud.githubusercontent.com/assets/9116243/15331772/2a143a8e-1c63-11e6-9656-9b0c6eec270e.jpg)

**Comment by emperor06** [comment]
Arf, sorry guys, that was my bad. I was using the wrong jar. I just tried with rv3-beta6 and it works. It most probably also work in beta5.
