### ISSUE TITLE
AutoCrafting lags

### ISSUE THREAD

**Issue by ArcasCZ** [AppliedEnergistics/Applied-Energistics-2#2280]
When someone try to craft hard recipe, server TPS goes down and tick time goes from 30 ms to 120 ms. What should we do with this?

**Comment by bookerthegeek** [comment]
Please read the guidelines on how to profile and return when completed

**Comment by ArcasCZ** [comment]
We aren't able to use VisualVM. We don't know why, but even with help of my friend, which is really experienced in server hosting, we were not able to profile.

Anyway - Opis wasn't able to show us, which chunk or block does lags, but when our friend started autocrafting, tick time went to horrible numbers.

So, we aren't able to provide more info. But if there is someone who can help us or meet with us at TeamSpeak, we have no problem :-) We wan't to improve this awesome mod and make it better ;)

**Comment by fhntv24** [comment]
@ArcasCZ you could use other tools, there a lot of them. Some dont need to do anything, just run server normally and they will profile it.

Also, you could forget to change default host binding. There is mistace in each guidlines - they arent updated to latest version. Example of server args. so it will work perfectly with VisualVM remote:
-Dcom.sun.management.jmxremote \
-Dcom.sun.management.jmxremote.authenticate=false \
-Dcom.sun.management.jmxremote.ssl=false \
-Dcom.sun.management.jmxremote.port=FREE_PORT -Djava.rmi.server.hostname=SERVER_IP

_WARNING: THIS ISNT SECURE! YOU **MUST** BLOCK THAT PORT WITH IPTABLES OR USE IT ONLY FOR A FEW MINUTES._

Also, you need actually to not profile server, but actually sample it ( there is bug that will crash server with visual vm and remote profiling - it will go into infinite loop for some reason ... )
This is a litle bit off-topic, but this will help ;)

**Comment by ArcasCZ** [comment]
There is problem - we couldn't run VisualVM - we tried to make it working about 3 hours with no reason...

**Comment by XFactHD** [comment]
Which AE2 and Forge version are you using?

**Comment by ArcasCZ** [comment]
AE2 latest, Forge 1614.

**Comment by XFactHD** [comment]
You could look here for some advice: ae-mod.info/profiling.

**Comment by ArcasCZ** [comment]
@XFactHD Jesus Christ, can you read?! We use Ubuntu, so this tutorial is pretty useless. Also, for some reason we can't run remote profiler - we tried to make it working about 3 hours a with no result. We tried lot of tutorials, we invited my friend (which is pretty good, he had lot of MC servers) - without any usefull result. I had an idea about Opis and Event profiling, but first I have to try it.

**Comment by ArcasCZ** [comment]
![image](https://cloud.githubusercontent.com/assets/6602975/15364934/a2469aea-1d1e-11e6-8486-60118fc47b50.png)

Here are images when we run huge autocraft.

![image](https://cloud.githubusercontent.com/assets/6602975/15364989/d44e4f1a-1d1e-11e6-8935-ec4e997ddfd5.png)

You can guess when we turned crafting on...

**Comment by ArcasCZ** [comment]
![image](https://cloud.githubusercontent.com/assets/6602975/15365036/01cf394a-1d1f-11e6-94ce-f7eff3e80318.png)

This img shows when AutoCrafting on (also, Baubles was saving to file, but that's just unfortunate coincidence). 

![image](https://cloud.githubusercontent.com/assets/6602975/15365061/226e5d84-1d1f-11e6-9a23-353b4b8e79b6.png)
And here without AutoCrafting.

**Comment by XFactHD** [comment]
Have you completely read the complete tutorial before yelling at me? Also, you should check your posts before yelling at me because you never mentioned that you are using a Ubuntu server. Back to the tutorial: It mentions another tick profiler mod you could try. I would have put the link to the mod here but the browser on my phone is too dumb to copy something from the URL box to any other text field.

**Comment by yueh** [comment]
We need an actual visualvm snapshot (or comparable). Opis is pretty much useless for these cases.

Once you can provide one, we will reopen the issue.

**Comment by ArcasCZ** [comment]
@yueh Come to our TeamSpeak and through TeamViewer try to run jVisualVM on our server. If you'll do it - you are god. There's no way to do it on our server ;)

**Comment by XFactHD** [comment]
Little hint: Build the server on your local pc and try running jvisualvm.

**Comment by ArcasCZ** [comment]
@XFactHD Problem is I can't run whole server on my PC - map's about 10 GB large!

**Comment by XFactHD** [comment]
How many players have been playing on this map and how long does it exist? Although I do not doubt this being possible, it seems kinda weird.

**Comment by ArcasCZ** [comment]
@XFactHD We pre-render whole map.

**Comment by XFactHD** [comment]
Can you do the map pre-render on your local pc? If you can, please compare how auto crafting performs on the fresh pre-rendered map vs a fresh and not pre-rendered map.

**Comment by ArcasCZ** [comment]
@XFactHD Fact map is pre-rendered is irelevant. It's only about downloading 10 GB from server...

**Comment by XFactHD** [comment]
You can never know...

**Comment by ArcasCZ** [comment]
@XFactHD I really can know - I'm doing MC servers about 3 years.

**Comment by ArcasCZ** [comment]
Here are WarmRoast results.

[Desktop.tar.gz](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/291026/Desktop.tar.gz)

**Comment by XFactHD** [comment]
"I really can know - I'm doing MC servers about 3 years."
And I can safely make assumptions and doubts because I am working with Minecraft's code for over a year and I know that it is sometimes acting really weird.

**Comment by ArcasCZ** [comment]
@XFactHD Yes, I know - but pre-generated world has nothink to do with AE2 auto crafting.

**Comment by ArcasCZ** [comment]
What about that WarmRoast?

**Comment by XFactHD** [comment]
Looks a bit weird because most of the time is spent in java.lang.Thread.sleep() and not in MC itself...
Everything else looks quite normal to me but I could be totally wrong right there. As soon as I have time to do so, I will make a WarmRoast on one of my single player worlds to have a comparison.
