### ISSUE TITLE
I cant pull out anything out of the ME system.

### ISSUE THREAD

**Issue by deadpoint12345** [AppliedEnergistics/Applied-Energistics-2#2282]
I cant really pull out any of my items that are inside the me system although it has enough power and is always powered. I cant also right click on it when its powered please help i have tried using betas and stable versions and it didnt fix anything

**Comment by VT-14** [comment]
Is there a security terminal on the system that was placed by someone else?  If yes, they will need to use Biometric cards to set your access abilities.

Also, a blank biometric card is used to regulate all players and sub-nets.

**Comment by deadpoint12345** [comment]
I do indeed have a security terminal however i placed the terminal my self
so i dont really know

**Comment by VT-14** [comment]
are you trying to pull from/on a sub-net (commonly a storage bus <-> Interface junction)?  The terminal also blocks automatic input/output from the system it is connected to (something vital to sub-nets).  AE on a sub-net can see the items, but doesn't have permission to take them.

a blank biometric card sets the abilities of sub-nets.

**Comment by deadpoint12345** [comment]
i do have an ender chest and attached to import bus but i dont know if thats the problem i got 2 me drives as well but i cant access any of the me including the terminal or the security if it is powered

**Comment by deadpoint12345** [comment]
but it used to work fine i dont know if its a bug maybe

**Comment by VT-14** [comment]
Break the Security Terminal and see if that fixes it.

**Comment by deadpoint12345** [comment]
thanks it worked but is it a bug or if it happens again do i repeat it again

**Comment by mindforger** [comment]
without proper details on how your network is setup nobody can help you but guessing what you may have done wrong, but indeed it sounded like you installed a security terminal without setting up the biometric cards properly

**Comment by deadpoint12345** [comment]
thanks for all ur responses i will try the biometric card now and i will see if the problem reoccurs
