### ISSUE TITLE
ME Export/Import bus Card filtering Items by Name

### ISSUE THREAD

**Issue by LyxTheGamer** [AppliedEnergistics/Applied-Energistics-2#2285]
Hey guys,

My Idea:
Something like a Card Upgrade that allows you to filter Items by name. e.g. I want to export all Dimlets without specifying every single ID

Would be a nice feature :)

**Comment by XFactHD** [comment]
This feature would be dependent on the language settings of each player and those are client-sided. Because an import bus can't just import stuff on your screen but not on the screen of somebody using another language this is not possible.

**Comment by yueh** [comment]
Also #1697.
