### ISSUE TITLE
AE2 Causing duplicate entities bug with Controller Multiblock on rv2-stable-10

### ISSUE THREAD

**Issue by Silver-Wulf** [AppliedEnergistics/Applied-Energistics-2#2286]
I will start off by saying that I did look to see if it was fixed in newer versions but could not find a changelog saying so. I have been running a server for about a year on various versions of AE2 - this one for a few months - and have encountered a strange error involving duplicate entities which run ticks but do not seem to actually exist when a ME Controller multiblock structure unloads along with a dimension (the End in this case). Here is what Opis shows for the tile entity lists (and keep in mind this was also happening for normal living mobs in the effected chunk):
![ex](https://cloud.githubusercontent.com/assets/16447048/15446359/169298ba-1ee4-11e6-8b1b-6ee500244357.png)

I had removed every block one by one in the base causing the issue (which was the only one in the End) and eventually found that the bug ceased when the Controller Multiblock was broken down into a single Controller. Another strange thing I found was that the issue no longer occurred when the Controller Multiblock only consisted of a vertical pole of Controllers while any expansion over the x or z axis broke upon unloading. Opis was not able to show the locations of the copied entities in any dimension so it seemed as if they were just added to the tick list and not ever truly spawned in which suggests that it could be an issue with the ME Controller Multiblock refusing to unload. This multiblock also managed to function as a chunkloader shortly before issues began regardless of all forge chunkloading and chunkloading tickets being set to 0. Hope this information was enough and that I was right about it not being fixed!

**Comment by Silver-Wulf** [comment]
Also, I forgot to mention, the entire dimension had to be unloaded to see any issues and this was most likely normal bukkit chunk-gc. My server's "System Details" are at http://pastebin.com/XeQrp7pD as shown in a recent crash log.

**Comment by XFactHD** [comment]
1. If you report a bug that happened on a server, try to reproduce it on a forge server (no bukkit, cauldron, etc.).
2. This has most likely been fixed, rv2 stable 10 is way out of date. You can find the changelog in the downloads section at ae-mod.info.

**Comment by Silver-Wulf** [comment]
Ok this is tough to reproduce but I will do my best to run some test servers in the future. It was quite handy to have plugins to show loaded chunks and world statuses. I will also try a newer version on the existing server and get back to you in the next couple days.

**Comment by mindforger** [comment]
`handy to have plugins to show loaded chunks` i prefere chickenbones chickenchunks for that, but i personally dislike the chunkloaders that come with this mod, they are pretty buggy, especially with AE and also several other mods

but you can type /chunkloaders and get a seperate window with all tickets and loaded chunks

**Comment by XFactHD** [comment]
The profiling mod Opis includes MapWriter which can show you all loaded chunks, it even differentiates between player loaded and force loaded chunks.

**Comment by Silver-Wulf** [comment]
The picture I provided was from Opis and I am testing the newer version (latest beta) now. Hope it all works!

**Comment by Silver-Wulf** [comment]
The issue seems to be fixed in the newer versions - I misunderstood the beta vs the releases. Thank you for your insight!
