### ISSUE TITLE
Wireless crafting terminal wont work in mystcraft worlds

### ISSUE THREAD

**Issue by tndmadman** [AppliedEnergistics/Applied-Energistics-2#2287]
Hello, thanks for reading. I made my own modpack with a list of mods i will list below
I went into a myscraft world with the infinite wireless crafting terminal and it does not
work in any of the mystcraft worlds. How ever it does seem to work in other worlds like the nether and the end. The error it gives me is network has no power, even though the base witch it connects to is chunk loaded and has power. Even if another player is at the base, same problem. 
I'm assuming its a problem with the mod working with mystcraft hopefully you may fix this or at least look
at it? Thanks.

1.7.10Better_Furnaces_V4.3
appliedenergistics2-rv2-stable-9
BBG-1.0.0
Carpenter's Blocks v3.3.7 - MC 1.7.10
Chisel-2.9.5.11
CoFHLib-[1.7.10]1.1.1-181
ComputerCraft1.75
denseores-1.6.2
EnderIO-1.7.10-2.2.8.381
ExtraCells-1.7.10-2.3.9b188
extrautilities-1.2.12
FastLeafDecay-1.7.10-1.4
forestry_1.7.10-4.2.12.60
IGW-Mod
InventoryTweaks-1.59-dev-152
ironchest-1.7.10-6.0.60.741-universal
Jabba-1.2.1a_1.7.10
liteloader-1.7.10
Mantle-1.7.10-0.3.2b
mcjtylib-1.8.1
Mekanism-1.7.10-8.1.9.265
MekanismTools-1.7.10-8.1.9.265
Minechem-1.7.10-5.0.5.406
MineFactoryReloaded-[1.7.10]2.8.1-174
MobiusCore-1.2.5_1.7.10
ModularPowersuits-0.11.0.300
MoreFurnaces-1.3.9-MC1.7.10
mystcraft-1.7.10-0.11.0.00
NotEnoughResources-1.7.10-0.1.0-121
NuclearCraft-1.6e--1.7.10
Numina-0.4.0.131
OpenComputers-MC1.7.10-1.5.22.46-universal
Opis-1.2.5_1.7.10
practicalities-1.7.10-0.6.2
Practical-Logistics-1.7.10-0.2.1
rftools-4.23
SonarCore-1.7.10-1.1.0
Tails-1.7.10-1.4.1a
TConstruct-1.7.10-1.8.8
ThermalDynamics-[1.7.10]1.1.0-161
ThermalExpansion-[1.7.10]4.1.2-240
ThermalFoundation-[1.7.10]1.2.3-112
VeinMiner-1.7.10_0.31.4.unknown
veinminermodintegration-0.5.0-1.7.10r18+e324d4c
Waila-1.5.10_1.7.10
waila-blacklist-1.7.10-0.1
WailaEvents-1.0.0
WirelessCraftingTerminal-1.7.10-rv2-1.4.b
Ztones-1.7.10-2.2.1
ChickenChunks-1.7.10-1.3.4.16-universal
CodeChickenCore-1.7.10-1.0.4.29-universal
CoFHCore-[1.7.10]3.1.2-325
ForgeMultipart-1.7.10-1.2.0.347-universal
FoxLib-1.7.10-0.7.0
NotEnoughItems-1.7.10-1.0.4.83-universal
WR-CBE-1.7.10-1.4.1.9-universal

Game version 1.7.10 vennial launcher
forge 1.7.10-forge10.13.4.1614-1.7.10

**Comment by tndmadman** [comment]
uhh ignore this i thought this was the post on the wireless crafting plugin

**Comment by XFactHD** [comment]
You can close this yourself if it is invalid.

**Comment by tndmadman** [comment]
how im a idiot lol

On Sun, May 22, 2016 at 4:57 AM, XFactHD <notifications@github.com> wrote:

> You can close this yourself if it is invalid.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2287#issuecomment-220826207>
>



-- 

LOVE YOU!

**Comment by XFactHD** [comment]
Next to the comment button is the close button.
