### ISSUE TITLE
ME interface and Storage Bus bug( I think so)

### ISSUE THREAD

**Issue by noobyaran9** [AppliedEnergistics/Applied-Energistics-2#2288]
I'll explain the problem using the picture below.

As shown in the picture, I'm trying to push an item from the ME interface on the left side in to the ME interface with a storage bus attached to it.
![2016-05-25_19 38 46](https://cloud.githubusercontent.com/assets/13598309/15538744/9b808c60-22b0-11e6-88dd-d6e51283ea3d.png)

This is the item in the ME interface(Input)
![2016-05-25_19 38 49](https://cloud.githubusercontent.com/assets/13598309/15538742/9b7f4b3e-22b0-11e6-99d1-29163fe65efb.png)

The setting on the Storage Bus.
![2016-05-25_19 38 55](https://cloud.githubusercontent.com/assets/13598309/15538745/9b839dc4-22b0-11e6-8217-f330cdf6a775.png)

As we know, the item should land on the ME interface with the storage bus attached to it. But, in this case, no.
![2016-05-25_19 38 52](https://cloud.githubusercontent.com/assets/13598309/15538743/9b7feaf8-22b0-11e6-9bab-8cc8214b7449.png)

When I replace the ME interface with a chest, the items do land on the chest.
![2016-05-25_19 39 04](https://cloud.githubusercontent.com/assets/13598309/15538746/9b88d1a4-22b0-11e6-94c0-4b3dd42ad3d1.png)

It is also bugged when I try using it as a sub-network. Items wont be able to transfer into the sub-network or transfer out of the sub-network when a storage bus is attached onto a ME interface.

**Comment by mindforger** [comment]
the ME interface on the left side makes no sense, or is there another storage bus attached behind we yet do not see on the screenshot!?

**Comment by noobyaran9** [comment]
I've tried to transfer item from a storage bus into a ME interface before and it worked. But for some reason, that method stops working. 

Besides, sub-network seems also is broken.

This is my sub-network feeding into a auto-sieving set-up. It's a replicate of what Soaryn did on his stream on FTB infinity skyblock.
![2016-05-25_21 03 31](https://cloud.githubusercontent.com/assets/13598309/15540877/40b1106e-22bc-11e6-95c2-94b8994527dc.png)
Setting on the ME interface linked to the main network.
![2016-05-25_21 03 39](https://cloud.githubusercontent.com/assets/13598309/15540876/40afd370-22bc-11e6-8703-545226080cb5.png)
Setting on the Storage Bus connected on the ME interface.
![2016-05-25_21 03 41](https://cloud.githubusercontent.com/assets/13598309/15540879/40b30798-22bc-11e6-8e3f-783c0dab2e6c.png)
Setting on the sub-network interface.
![2016-05-25_21 03 49](https://cloud.githubusercontent.com/assets/13598309/15540875/40aba7fa-22bc-11e6-9963-ca6ce929515a.png)

As you could see, items can't be transferred from the main network in to the sub-network. It should be able to as seen on Soaryn's stream.

**Comment by XFactHD** [comment]
1. If you have a security station, remove it or put a blank biometric card with all permissions given into it (This is most likely what makes you think that subnets are broken)
2. Does it work if you filter the storage bus and assign it a higher priority?

**Comment by noobyaran9** [comment]
Ahh thx for the help there. It works.
