### ISSUE TITLE
Level Emitter not working correctly

### ISSUE THREAD

**Issue by FireBall1725** [AppliedEnergistics/Applied-Energistics-2#229]
When 2 level emitters on the same network are configured to use energy mode, and have the same value specified only the first one to register will work, while the other one will do nothing.  If you change the numbers so they are off by 1 then they both will work

**Comment by TheJulianJES** [comment]
@FireBall1725 Is there any progress on this issue?

**Comment by TheJulianJES** [comment]
Is there any progress on this issue? :D

**Comment by thatsIch** [comment]
poke @FireBall1725
