### ISSUE TITLE
Can't access anything.

### ISSUE THREAD

**Issue by 34486** [AppliedEnergistics/Applied-Energistics-2#2290]
Alright, So, I am playing on my Multiplayer Forge Server. I am unable to access my ME Network at all! I have the Controler, Drive with drives in it and a Crafting terminal with a energy accepter from RF to a AE2 Energy cell to the controller and everything. I built the same thing in single player, and it worked. 

I am unable to access the network by clicking on the crafting terminal. Please help!!!

**Comment by 34486** [comment]
Oh, Ok. As I was going to take  picture of th setup, I thought of the coords. (Its like 7 digits), So I tped myself to a smaller one, in this case 821 100 821 just random spawn like area thing yah know. Well, it worked. Looks like I have to move base.


Minecraft has glitches that far anyways. Torches flames are on the side, falling gravel, well, it just brakes.

**Comment by XFactHD** [comment]
If the issue is fixed, please close the ticket.
