### ISSUE TITLE
Interface Terminal Suggestion

### ISSUE THREAD

**Issue by dexter12353** [AppliedEnergistics/Applied-Energistics-2#2291]
My suggestion is, if you are in the interface terminal, you can put an item (not a pattern) in the slot for the machine and it goes into that machine

Example:
Ic2 Energy crystals

Toss 9 energium dust in the slot for the interface on the compressor, and the items then transport to the compressor, the compressor processes them as usual.

This would make it easier to put items into machines that could be a mile across a base, so that way you can access the machines manually from an interface terminal.

**Comment by XFactHD** [comment]
This has already been suggested and denied.
