### ISSUE TITLE
Biometric card model is off center in hand

### ISSUE THREAD

**Issue by Silly511** [AppliedEnergistics/Applied-Energistics-2#2294]
Tested on version rv3 beta build 6.

<img src="http://i.imgur.com/PY5HmOC.png?1">

**Comment by XFactHD** [comment]
This is how item rendering in MC 1.7.10 works and the devs do not really have an influence on that.

**Comment by Silly511** [comment]
Yes they do. The biometric card uses a <a href="https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/main/java/appeng/client/render/items/ToolBiometricCardRender.java">IItemRenderer</a>, All they have to do is use GL11.glTranslatef to move it a bit to the right.

**Comment by yueh** [comment]
No idea why. But the cards change their texture based on the player? Maybe it is done to prevent hiding parts of the unique identifier with a players hand?
