### ISSUE TITLE
ME Pattern encoding special character issue

### ISSUE THREAD

**Issue by EsorX** [AppliedEnergistics/Applied-Energistics-2#2295]
I am unable to insert items with special characters (tested: ü,ö ä and ß properly broken too)
in my target crafting encoding field.
Might be a minor bug because it only affects target crafting block, 
not the crafting recept or target processing fields.
When switching to english encoding works fine and theres no crash when I switch back to german, 
even auto crafting works like a charm.

![me crafting](https://cloud.githubusercontent.com/assets/15246338/15802526/6fb92724-2ab5-11e6-8e62-8c5c293603e1.png) ![me processing](https://cloud.githubusercontent.com/assets/15246338/15802527/71abab38-2ab5-11e6-986c-31ad207eaa89.png)

Used Seeds and Mekanism's Steel Chasing because of ("Körner" and "Stahlhülle") 
Also used a "ME Pattern Terminal", I did not test others so far.

Minecraft:   1.7.10
Forge:        10.13.4.1614
AE2:           rv2-stable-10

(My first issue report, hope everything is fine)

EDIT: I am using **OS X 10.11.5**

**Comment by XFactHD** [comment]
Can you also reproduce this in the latest version (rv3-beta-6)?

**Comment by EsorX** [comment]
RV3's  auto-detecting works fine for me, but it only used affect the target field, which is irrelevant now.
So this remains a RV2 issue.

RV3:
![special character white wool](https://cloud.githubusercontent.com/assets/15246338/15805858/51c5ea28-2b36-11e6-96fe-962f646c8ba2.png)  ![special character white steel chasing](https://cloud.githubusercontent.com/assets/15246338/15805859/556358d2-2b36-11e6-932e-6cf8c29b8622.png)

**Comment by yueh** [comment]
As reported to be fixed with rv3.
