### ISSUE TITLE
Storage Bus Priority Error

### ISSUE THREAD

**Issue by cocotoffee** [AppliedEnergistics/Applied-Energistics-2#2297]
I have an igneous extruder that outputs directly into a barrel so I will always have a backup supply of stone. There is a storage bus on top of the barrel with a priority of -1. My drive bay has a priority of 0 with a few drives that have stone in them as well. As far as I know, when I pull stone out of a terminal, it should take stone out of the drive bay (as it has the higher priority) before resorting to the backup stone. However, the stone is coming from the barrel, but will never go back in even though I have the storage bus set up to be bi-directional and it is not full.

**Comment by HadesDurin** [comment]
if i remeber correctly it takes out from the lowest priority first (to empty it) and when you put stone back inside it choose the highest priority first
so to be sure it always uses the barrel first you need a higher number than your drive

**Comment by cocotoffee** [comment]
Thank you for your reply! That solved my problem! I will be sure to remember that in the future. Thank you for your time, and have a great day!
