### ISSUE TITLE
Export Bus inserting wrong item, triggered by item being put into ME system somewhere else

### ISSUE THREAD

**Issue by seanbrockest** [AppliedEnergistics/Applied-Energistics-2#2299]
EDIT: I've realized that my hypothesis was wrong. it's not the export bus causing the problem. I've got more sluething to do. if someone could close this, i will recreate it when i've figured more out.

forge-1.7.10-10.13.4.1558-1.7.10-universal
appliedenergistics2-rv2-stable-10
I'm using a lot of other mods, this is the regrowth pack (.91), but only AE2 components are related to this bug.

I've seen this in many places with multiple components, but only recently been able to replicate it.  This is only one example, so stay with me.

I've got an Export bus which should be exporting golden chipsets into an inscriber. Currently there are no golden chipset available to export (although this is not a requirement to replicate but bug). I have a piece of Granite in my inventory. When i got to any ME access point (crafting terminal, me terminal) and try to put the granite in the me system, it instead goes straight to the export bus, and lands in the inscriber.

This is doubly weird because Granite should not be capable of going in the inscriber at all. Manually, i cannot even force Granite to go into that slot of the inscriber.

This is my server, and currently I am the only one connected to it. I can now reproduce it pretty well, although it happens whenever it wants to, and really messed up my automated inscribers.

**Comment by bookerthegeek** [comment]
Sever....
 * Forge or bukkit/cauldron based?

**Comment by seanbrockest** [comment]
forge-1.7.10-10.13.4.1558-1.7.10-universal

for both server and client.

**Comment by XFactHD** [comment]
You don't need any special permissions to close your own issue.
Also, beat the modpack creator for using a goddamn old version of AE2.

**Comment by HadesDurin** [comment]
@XFactHD
i think the modpack creator is not to be blamed to be on a stable version of ae2.

or is there a stable version of rv3 aviable somewhere?
havn't not seen any and related to the github code page there is no further development since rv3 beta 6 /build 68.
so waiting for a stable rv3 build is totally legit.

**Comment by XFactHD** [comment]
In most cases, I would agree with you but in the case of AE2 i don't, simply because the beta builds are almost always much more stable than the latest stable version.

**Comment by mindforger** [comment]
@HadesDurin RV2 has been discontinued when RV3 entered beta stage more or less, there where a major code change and cherrypicking the bugfixes is almost impossible and maintaining 2 full versions also :)

**Comment by HadesDurin** [comment]
here is the wrong place and you are the wrong guys to select a discussion with. so all i can say it stops here.

**Comment by mindforger** [comment]
the only one discussing is you, i just told you some facts, generalizing in such way is rude
