### ISSUE TITLE
Terminals won't align correctly.

### ISSUE THREAD

**Issue by Furious1964** [AppliedEnergistics/Applied-Energistics-2#2300]
Use REV 3 BETA Build 6
Forge 10.13.4.1614
FML 7.10.99.99

Crafting Terminal is always facing the facade when placed. Tried it with multiple facade and no go. Can't seem to rotate it with a wrench either.

Problem fixes itself if entire cable is removed.

**Comment by mindforger** [comment]
can you post a screenshot, your explanation lacks a lot of details, like the type of cable used, the surrounding, the order in which it is placed etc.

**Comment by Furious1964** [comment]
Will try to replicate it. I was using AE2 covers and Fluix Glass Cable. I placed the cable first, then the cover and the terminal on top of that. As I stated, the problem solved itself when I removed everything and replaced it.

**Comment by mindforger** [comment]
the order is wrong, you have to place the terminal first and then the facade ... if by chance you meant the hollow cover from FMP, they wont work this way the hole is too small

but you can place hollow and non hollow cover oder stripes to the adjcent sides/edges to close the gaps

**Comment by Furious1964** [comment]
Will try it that way, but the cover never attached the first time I tried it. Always thought you had to place the cover and then the terminal.
