### ISSUE TITLE
applied energistics 2 problem or extracells problem idk which

### ISSUE THREAD

**Issue by bird191** [AppliedEnergistics/Applied-Energistics-2#2301]
The gas storage bus you cant add a capacity card to filter which gas goes in so i dont know wether you have to add gas storage bus to the list of things that use capacity cards or if they have to add capacity card as an upgrade for the storage bus.

**Comment by VT-14** [comment]
Not counting the P2P tunnels, Applied Energetics 2 only deals with items (no fluids, gasses, essentia, etc.).  This is an Extra Cells or another add-on's issue.

**Comment by bird191** [comment]
Ok I did post this on their page as well just to make sure

**Comment by Joshwoo70** [comment]
gas storage bus? Extracells. dont ask here :wink:
