### ISSUE TITLE
Just wondering...

### ISSUE THREAD

**Issue by MakeLord** [AppliedEnergistics/Applied-Energistics-2#2303]
Is this mod dead or are the devs taking a break?
Haven't seen anything for a while.

**Comment by XFactHD** [comment]
The development of AE2 has slowed down because of lack of time.

**Comment by WinterGrave** [comment]
@XFactHD I am new in the team, I want to help but haven ben able to set up the project in eclipse. Anyone who can assit me will just be a one time thing.

**Comment by MakeLord** [comment]
@XFactHD Oh, ok. Thanks for clearing out. I just miss AE2 on my 1.8.9 pack... :/

**Comment by XFactHD** [comment]
@WinterGrave the readme explains everything.

**Comment by WinterGrave** [comment]
@XFactHD well, I did everything on the readme. I know how to set up projects, but it won't run, I seem to be missing a mapping or a reference, I get mising class error. I'll keep trying tho.
