### ISSUE TITLE
Starting Mobspawner with AE2

### ISSUE THREAD

**Issue by Blizzor** [AppliedEnergistics/Applied-Energistics-2#2310]
Hey,

I wish, i could start a Draconic Evolution Mobspawner with Applied Energistics.
But if I try to use 2 Mobsouls as Input and 1 as output, it is always simulating.

As example: [https://dl.dropboxusercontent.com/u/36365753/AE%20Draconic.jpg](url)

Is it possible to do this?

**Comment by XFactHD** [comment]
No, this is not possible because you are effectively using the same item as input and output which means that the recipe is recursive.
