### ISSUE TITLE
Export/Import Changes needed

### ISSUE THREAD

**Issue by RogerRoger101** [AppliedEnergistics/Applied-Energistics-2#2311]
We need a card that if you place multiple items in an export bus (or Import) that it will pick 1 (or more see the end of this post) item from one of the ghost blocks, then rotate to the next ghost block item, etc., in a round robin kinda format.

Example:  
Export bus has 1 capacity card allowing 5 items (5 ghost block images).  Each open slot has a ghost block placed for processing (exporting) this (**sorting card**) will start pulling items from the left ghost block (pull that item), go to the top ghost block (pull that item) to the right ghost block (pull that item), bottom ghost block, then center one.

![2016-06-30 08_08_39-minecraft 1 7 10](https://cloud.githubusercontent.com/assets/7502637/16493571/d895739e-3e9a-11e6-92f0-cd2f65593de5.png)

This will open up the compability with a larger set of mods (like minechem) as the above example shows.   (NOTE: I added in BS blocks just to show the meaning of the selection with one capacity card installed into the device). 

You can add the ability to set 1 or more items to pull in this "round-robin" fashion maybe make it a configuration option when building? 

(just ideas to help this mod - AE and AE2 really has set the standard in quality and flexibility)

Currently I was trying to merge two chemicals into a complex chemical, but the export system just would dump ALL of one chemical first then the next.  The idea of a "sorting" card would help lessen the complexity of adding multiple export or import buses all over the ME system.

**Comment by elix-x** [comment]
@yueh round robin -> 1.

**Comment by mindforger** [comment]
you could achive this using an ME interface and some other mod providing a sorter, sequencer or router

you set the interfac in blocking mode, so every item gets dumped only once in the target storage which is managed through a sequencer or router (Steves Factory Manager for Example)

when the last item is pulled the next process will be initiated

AE was allways designed to provide yet simple and powerfull interfaces but with increasing complexity you need to use your brain and mechanics to solve such complexity issues :)
you could also use 2 export interfaces into one inventory nd monitor an almost equal amount by utilizing level emitter and a storage bus dedicated for ths interface

**Comment by RogerRoger101** [comment]
ME Interface doesn't always cover the job needed.  if you are 'crafting" items, sure it works perfectly but if you just want to sort into a machine into a specific order then it doesn't cover it.  

The idea is brilliant for more than just minechem.  I just used it (minechem) as an example.  I had run into this issue before but never posted the idea.

Believe me I've had some very complex and convoluted setups with AE now learning AE2, the suggestion was more "thinking ahead".  I had this idea back in AE orginal days. If it's not programable then it's not programmable but if it is . . . it would be a great feature.

**Comment by yueh** [comment]
Export buses export items, not control that some random machine is stocked correctly.
They have a round robin mode with rv3, but the state/order is not guaranteed to be stable across chunk reloading or insufficient items (like export 8 total items per tick, but only have 5 A available,  pick 3 from the next one B and export 8 B next tick)

For precise stocking, you have to control the export bus itself. Like export one item per redstone signal or similar.
