### ISSUE TITLE
ME-system stopping

### ISSUE THREAD

**Issue by geozukunft** [AppliedEnergistics/Applied-Energistics-2#2315]
Hello I have a problem I have a ME-system with about 90 channels used and a few days ago the system suddenly disconnected every device. Each device was writing no channel used. Then I disconneted the fluix cable that was beetween the energy acceptor and the energycell after a few seconds the system did something like a reboot and everything worked fine again and I placed the fluix cable again. But a few minutes later there was again the same issue. 

Is this a problem of my client or of the software or a bug of the modß

Hope somebody can help me.

geozukunft

**Comment by bookerthegeek** [comment]
Screenshots, or a video,  would help.

**Comment by VT-14** [comment]
Sounds like insufficient power.  Make sure you are producing enough.

I'll assume you already checked that; so when that is a dead end, try adding a few AE2 Energy Cells around the system.  I've heard that large systems can develop power problems due to not having a large enough AE2 power capacity on hand to deal with any server lag.

**Comment by geozukunft** [comment]
![2016-06-24_20 57 02](https://cloud.githubusercontent.com/assets/20288857/16708464/1e18aa88-45f5-11e6-9002-38e544538a51.png)
![2016-07-06_20 10 37](https://cloud.githubusercontent.com/assets/20288857/16708462/1e14a794-45f5-11e6-89f7-7cbb8fd0fef8.png)
![2016-07-06_20 10 41](https://cloud.githubusercontent.com/assets/20288857/16708465/1e19f9f6-45f5-11e6-9bd4-408b3b98727b.png)
![2016-07-06_20 10 49](https://cloud.githubusercontent.com/assets/20288857/16708463/1e16df5a-45f5-11e6-9ce6-c6365c220a24.png)
![2016-07-06_20 11 02](https://cloud.githubusercontent.com/assets/20288857/16708466/1e1a84f2-45f5-11e6-8f01-0a7fb74f2ba3.png)
![2016-07-08_21 29 34](https://cloud.githubusercontent.com/assets/20288857/16708467/1e1d23b0-45f5-11e6-994a-8ed0ec765ea8.png)
![2016-07-08_21 29 40](https://cloud.githubusercontent.com/assets/20288857/16708468/1e2b675e-45f5-11e6-9fdc-42702c63ebf9.png)
![2016-07-08_21 29 51](https://cloud.githubusercontent.com/assets/20288857/16708469/1e2f58f0-45f5-11e6-8b84-b3d76a69859f.png)
 I also thought it could be a power problem as you can see in the screenshots the tooltip writes 0 EU out of 4K EU. I placed nearly 20 Energy Cells but it was still crashing so I put a creativ Energy Cell but that does not help in any way. Could it be that the things that are far away consume more energy so the cable looses so much energy that it consumes so much energy from the Cell that the fluix cable can't transport so much energy?

**Comment by VT-14** [comment]
Possibly, but I don't think so.  Is your system SO big that parts of it could be in unloaded chunks?

**Comment by geozukunft** [comment]
Yes there are a few ME-consoles and import buses that are nearly everytime unloaded and I have a Quantum Link where the other end is about 1500 blocks away. so there are things that are unloaded yes.

**Comment by geozukunft** [comment]
![network1](https://cloud.githubusercontent.com/assets/20288857/16709012/a30c2486-4604-11e6-9469-b2a4dcc98620.PNG)
![network2](https://cloud.githubusercontent.com/assets/20288857/16709013/a30e7376-4604-11e6-8ffe-763ad6b77f63.PNG)
