### ISSUE TITLE
Interfaces and Busses not Working

### ISSUE THREAD

**Issue by zombiecow7799** [AppliedEnergistics/Applied-Energistics-2#2318]
I was adding interfaces to my ME system in order to auto-craft something when I noticed that all of my interfaces, export, and import buses stopped working. Storage buses still seemed to be working. After some experimentation it seemed to be that once I reached a certain number of interfaces my it all stopped working. I don't have channels enabled so that can't be the issue. I also made sure I had enough power.

**Comment by mindforger** [comment]
`Please review the guidelines for contributing to this repository.`
how should one know what you are doing wrong without ANY details

**Comment by zombiecow7799** [comment]
Sorry, I didn't see the guidelines. The applied energistics version is "appliedenergistics2-rv3-beta-6." How do I tell what forge version I have? I'm having this issue while using the unabridged modpack on the atlauncher.

**Comment by mindforger** [comment]
you can make a forced crash by pressing and holding F3+C for 6 seconds and add the crashlog (attachment or pastebin link please)

**Comment by zombiecow7799** [comment]
I did that, all the happened was that it returned to the homepage of the ATLauncher. No crash log came up.

**Comment by mindforger** [comment]
it is saved as a .log file in your minecraft folder, subfolder crashlogs ... well another reason why i do not like most of tose launchers at all .. they hide the important stuff for optics ...

**Comment by zombiecow7799** [comment]
http://pastebin.com/7LXxKbpQ

**Comment by zombiecow7799** [comment]
Is this right crashlog?

**Comment by mindforger** [comment]
huh ... there was an known issue earlier regarding an overflow in channels with channels off ... can you attach a picture of your setup or can you reproduce it in any way? Check how many items you have installed and try to rebuild it!

Also check if you have enough energy cells installed, it doesn't matter how large your input of power is, it depends on the energy capacity of your network mostly when the network misbehaves!

**Comment by zombiecow7799** [comment]
I didn't realize you had to have energy cells on a network. I thought they were just another form of power storage. I put in six dense energy cells and now everything is working fine.

**Comment by mindforger** [comment]
heh sometimes it the simple things that are missing :D
like i said, you'll always have surges and like in every electronics in the world there are capacitors ... like the energy cells that provide the buffer for such surges
