### ISSUE TITLE
Backfeed of power though quantum gateway causing intense tick lack. 

### ISSUE THREAD

**Issue by themechman** [AppliedEnergistics/Applied-Energistics-2#2319]
Hello, I have several dims where I have bases established. Rather than setting up a whole new manufacturing system, I have the overworld setup to do external fabrication for my AE. My other dims are connected via quantum gateways.

Here is where my problem starts:
When I build the remote gateway and install the item that connects to the other endpoint, the remote gateway does not connect or power up. Once I use an energy acceptor it activates and I am able to use my overworld resources without problem. That is until I leave the dimension or immediate area.

Upon leaving the dim and returning to overworld to check on my system, I am greeted with intense tick and graphic lag as the AE system I built acts like it is starved for power. All of the screens and devices switch online and offline rapidly.

My only options to remedy this is:
* Remove the entangled link item from the gateway
* Break cable to overworld gateway
* Chunk load remote gateway
* Remove energy acceptor

Removing the acceptor does not make things better. Once you do so, leave and then return, the gateway remains offline and is not functional until you supply it with power.

Chunkloading and leaving the acceptor is currently my only option. There are other mods I use that chew up ticks when active and I'd prefer not to keep these area's loaded if nobody is playing there.

Currently running RV2-10 with extracells 2.3.10b190 and ae2stuff-0.5.0.56 on Forge 10.13.4.1558

**Comment by XFactHD** [comment]
While I need to have both gateways chunkloaded for this to work, I could work around the starving bug by placing a tesseract on the energy acceptor, setting it to only be active without redstone signal and place a level emitter next to it that was set to  0 as threshold and no item in it. As soon as the quantum bridge fires up the level emitter switches on and the tesseract gets disabled.

**Comment by themechman** [comment]
> Also, your version of AE2 is extremely old, you should update to rv3 beta 6.

I run stable builds, unless there's a really darn good reason. Two of them being ae2stuff and extracells.

As far as your work around goes, thats not a bad idea. I'll have to try it, but usually the gate does not reactivate once I'm back in the dim.

**Comment by XFactHD** [comment]
In your case there is a darn good reason: rv2 stable 10 is MUUUCH buggier than rv3 beta 6.

**Comment by themechman** [comment]
Gate does not wake upon reentry to dim using XFactHD's work around. I've experienced no other issues with this build and it sounds like its not fixed in rv3b6. That said, it would be logical that the problem is systemic. I didn't have this problem in a prior version of my modpack which ran rv2-8

**Comment by XFactHD** [comment]
Just as a reminder: For my work around, the chunks where the main system is, need to be chunkloaded.

**Comment by yueh** [comment]
AE2 is designed to be either in chunkloaded areas or in unloaded areas. There are already a couple of closed issues about it.

Having something which constantly loads and unloads a chunk, will constantly reset the network and force it to revalidate everything. Which is a bit resource intensive, but fine when not done every single tick. So either keep it loaded, as loaded chunks are way less resource intensive as constant reloads or identify what is constantly reloading them and report it to the specific mod.
