### ISSUE TITLE
Export Buses/Level Emitters not working with Forge Microblocks

### ISSUE THREAD

**Issue by jiseokcube** [AppliedEnergistics/Applied-Energistics-2#2321]
Forge version: 1.7.10-10.13.4.1614
AE2 version: rv3.beta 5
Modpack: FTB Infinity Evolved Expert 2.5.0

Setup to stockpile dark steel balls from main network to chest. Subnet of level emitter and storage bus provides the signal for the export bus.
![2016-07-14_16 58 59](https://cloud.githubusercontent.com/assets/13512335/16832412/285f1c54-49e5-11e6-8314-16f5d0c8aff5.png)

Level emitter settings
![2016-07-14_16 59 05](https://cloud.githubusercontent.com/assets/13512335/16832416/286b407e-49e5-11e6-9112-833d21121fb1.png)

Export bus settings
![2016-07-14_16 59 10](https://cloud.githubusercontent.com/assets/13512335/16832413/285fa80e-49e5-11e6-9926-3b71833fa889.png)

Works as intended; level emitter updates properly and 24 items are left in the chest (due to the slower nature of the level emitter than the export bus).
![2016-07-14_16 59 26](https://cloud.githubusercontent.com/assets/13512335/16832414/2869262c-49e5-11e6-8034-e7e621249d39.png)

Now the addition of microblocks to the level emitter and storage bus.
![2016-07-14_16 59 46](https://cloud.githubusercontent.com/assets/13512335/16832415/2869bf92-49e5-11e6-866e-38866bf31220.png)

Level emitter updates slower (without microblocks was already on at this point)
![2016-07-14_17 00 06](https://cloud.githubusercontent.com/assets/13512335/16832418/2888d4ea-49e5-11e6-87c5-c70baeaf1151.png)

Level emitter remains on even after 24 items in the chest.
![2016-07-14_16 59 54](https://cloud.githubusercontent.com/assets/13512335/16832417/286b51fe-49e5-11e6-8c75-f9271641dd2e.png)

Relogging updates the emitter but now there are 32 items.
![2016-07-14_17 00 35](https://cloud.githubusercontent.com/assets/13512335/16832419/288a96b8-49e5-11e6-94d3-102bac7761a9.png)

Now the addition of a microblock to the export bus.
![2016-07-14_17 01 43](https://cloud.githubusercontent.com/assets/13512335/16832422/289899f2-49e5-11e6-9977-7af256155107.png)

Stops the system completely.
![2016-07-14_17 01 56](https://cloud.githubusercontent.com/assets/13512335/16832420/28962cee-49e5-11e6-9a5e-1cf02cfe5ce3.png)

Relogging updates the level emitter again.
![2016-07-14_17 02 18](https://cloud.githubusercontent.com/assets/13512335/16832423/289c0948-49e5-11e6-8347-c1d6a1846e78.png)

But now it behaves the opposite way.
![2016-07-14_17 02 32](https://cloud.githubusercontent.com/assets/13512335/16832421/28961f06-49e5-11e6-9f87-f7e711ff2e5c.png)
![2016-07-14_17 02 34](https://cloud.githubusercontent.com/assets/13512335/16832424/28b2a298-49e5-11e6-943c-c479e830d05e.png)

I've tried a lot of different things here, from adding energy cells (this one is powered by a creative energy cell and a dense energy cell) to breaking and replacing the components, but nothing seems to work. Replacing both the export bus and level emitter fixes the problem once but it stops once the items are taken out. Perhaps it has something to do with the strange animation when breaking a cable with a microblock?
![2016-07-14_17 02 59](https://cloud.githubusercontent.com/assets/13512335/16832426/28c340e4-49e5-11e6-8791-66249cc19c67.png)

Also, WAILA does not display the channels on smart cable if there are microblocks. I realize this is a different mod, but could it be that AE2 is handling the cable differently with a microblock than without?
![2016-07-14_17 04 50](https://cloud.githubusercontent.com/assets/13512335/16832425/28c1b86e-49e5-11e6-8cc8-f2d19ef8646f.png)
![2016-07-14_17 04 54](https://cloud.githubusercontent.com/assets/13512335/16832427/28d4d70a-49e5-11e6-8a1a-8e021ad22aa1.png)

Please let me know if I can provide any more feedback, and thank you in advance.

**Comment by VT-14** [comment]
Someone might be able to help; but in the mean time, try using AE2 Facades.

**Comment by thatsIch** [comment]
when placing a microblock on it, you convert the whole tile entity to a microblock. This just looks like something from AE2 but is not anymore. Sadly I am no expert on FMP
