### ISSUE TITLE
AE 2 and EnderIO sag mill

### ISSUE THREAD

**Issue by Padnae** [AppliedEnergistics/Applied-Energistics-2#2322]
Hello everyone.

I'm looking since somes days for some tips or knowledge and found nothing relevant.

I'm using Minecraft 1.7.10, Realm of mianite.
Before goes into AE 2 I used Ender IO and Thermal foundation.
I ended with a set up for my quarry:
-Chest (only ore)
-Sag mill (grind just everything it can on the chest)
-chest (powder and extra item)
-Alloy smelter (furnace only)
-chest (final ingot)

The deal it is to mine and automaticaly without big instalation to grind all ore and turn it into ingot.
Very usefull, fast and minimal.

And after I goes to AE 2 for an easyer storage. 

I see how to filter with a ME storage Bus, to put all ore mined in one ME chest.
But I dont see how put all the ME chest content (only) into the sag mill.

So I would just took the ME chest to the old ender io set up and link back the Alloy smelter to AE 2 storage. But I dont see how to extract (not manually) a full storage content (w/o interacting with the main storage system) from a EM chest or whatever AE2.

Maybe I missed something but I dont know what.
If someone can help,
Best regards.

**Comment by VT-14** [comment]
You can pipe/hopper into an ME chest, but not out of it.  There is some ambiguity as to whether you are trying to pull out items or the Storage Cell.  Plus, you are supposed to use all the other components of the mod.

I think the simplest system that you would want would be Me chest - ME Interface - SAG Mill...Alloy Smelter - Pipe back to ME Interface (or chest, but go with interface; the chest is easily replaceable.).

In the ME Interface, you can stock up to 9 stacks of items (and specify the size of the stack).  Do one for each ore.  If you need more than 9, then add another Interface to another side of the SAG Mill (still touching one of the ME devices) and stock the other ores.

ME Chests make pretty good sub-net storage, and for manually filling things (setting partitions, Matter Cannon, Color Applicator, etc).  It's just not the right tool for what you want to do here.

On a sidenote, this is a bug/issue tracker.  For questions like this, you should probably be using a community forum.  Please remember to close your issue when you are done.

**Comment by Padnae** [comment]
I'm gonna just do stuff manually depend on what I need. I guess theyr is no other to do.

Thanks for the answer and I'm gonna close the issue.
Have a good day.
