### ISSUE TITLE
Can't open any AE machines and put in/pull out items from terminal

### ISSUE THREAD

**Issue by BALoney2012** [AppliedEnergistics/Applied-Energistics-2#2324]
I was playing around with thaumcraft and after I did _something_, I started having this issue with AE machines (terminals, interfaces, buses, etc). My **crafting** terminal looked like this https://gyazo.com/599566e77617500c94618582d55ce85a . It looked like a normal access terminal and I couldnt put in any items or pull out items from the terminal. Not only that, when I said that I was having an issue with AE machines, I meant that I couldn't even open the GUI for interfaces, buses, terminals (other than crafting), and even terminals from thaumic energistics. This happened on multiplayer and I asked my partner to see if he had this problem but he said it was fine for him. I've tried /suicide, relogging, restarting the client, breaking and placing it (AKA turning it off and on :P) but the problem never went away.

**Comment by BALoney2012** [comment]
Also, I just tested and saw that ME system works perfectly fine in single player.

**Comment by mindforger** [comment]
do you have a security terminal installed and a biometric card added for yourself?

**Comment by BALoney2012** [comment]
And that was it. someone has slabbed down a security terminal :P

**Comment by mindforger** [comment]
most probably due to it's presence required to attach an wireless access terminal

**Comment by VT-14** [comment]
Biometric Cards set security Terminal permissions.  A blank biometric card sets the default security for people not specified by other cards, and for automation (sub-nets).  Set a blank card to have all permissions, and you should be good to go.

If security is an issue, then have whoever placed the terminal set permissions for your biometric card.  Sub-nets will still need a blank card with item transfer permissions to work still, and that would open your items up to anyone.

**Comment by XFactHD** [comment]
If you are only using the security terminal to be able to use a wireless terminal, you don't even need to put a biometric card into the security terminal.

**Comment by VT-14** [comment]
@XFactHD If you are playing alone on a network that doesn't have any sub-nets, then you are right.  However, you do need to set a blank card for sub-nets to work and set default permissions for players, or specific cards to set specific permissions for individual players.

Unless it was changed since I last used AE2, the Security Terminal defaults to maximum security for all  (including automation, and thus sub-nets) except the player who placed it.  Considering that the creator of this issue is unable to use his ME system because someone else placed down a security terminal, I'm pretty certain it hasn't changed.

**Comment by XFactHD** [comment]
I can't really comment on that as I am playing alone almost every time.

**Comment by VT-14** [comment]
Even when alone, it's still good to know that sub-nets (Storage Bus facing an Interface on different networks) fail with the security terminal unless a blank card has been set to allow input and output.

**Comment by XFactHD** [comment]
I am using sub-nets and for me they work without a blank card.

**Comment by VT-14** [comment]
Direction matters too.  If your security terminal is on your 'main' network and are using a sub-net for storage, then you will be able to use that just fine.  You are pulling in and out of a Storage Bus on the side with the security.  The system treats the storage sub-net as if it's a simple chest with a huge storage capacity.

If the security terminal was on the Storage sub-net, then you have issues.  Pulling an item on the protected storage network by using a terminal on the main network would make the storage network think an outside source was trying to pull the item.  That's a potential security risk.  Maybe someone hooked up a set of Logistics Pipes and is suddenly trying to steal your cobblestone!  Maybe someone slapped down a Storage Bus on one of your interfaces and is trying to steal your dirt!  A security terminal would be pretty useless if it could be bypassed on any open side ME Interface, so these interactions must be blocked!

That sounds pretty simple to avoid, but the security terminal also blocks access attempts through it (if it's between sub-nets).  It's pretty common for people to use something like an SSD and a main network just fine, then add on another sub-net that works off of requesting items through the main network and have that work just fine too.  Then they decide to get a wireless terminal, so they set up a security terminal to bind it... then find that their request based sub-net no longer has access to items.
