### ISSUE TITLE
Inscribers with unlimited buffer

### ISSUE THREAD

**Issue by me2000000** [AppliedEnergistics/Applied-Energistics-2#2326]
attached screenshot of an inscriber with 57k / 3k RF this will continue with seemingly no limit consuming around 800RF/tick earlier I had one up to 226 MRF : 0

this is on The 1.7.10 pack (modpack on Technic Launcher) runner AE 2 rv3-beta6

![no buffer limit](https://cloud.githubusercontent.com/assets/20390939/17010830/3da67016-4ecd-11e6-9bc3-8a562d267428.png)

**Comment by me2000000** [comment]
Update: it seems that this only occurs with Galacticraft's Aluminum Wire

**Comment by yueh** [comment]
If it is just limited to a single cable of another mod, it is most likely an issue on their side.
