### ISSUE TITLE
Idea for Autocrafting

### ISSUE THREAD

**Issue by zombiecow7799** [AppliedEnergistics/Applied-Energistics-2#2327]
I'm not sure that this is the proper place to submit ideas, but I've seen a few other people post ideas they have here. Sometimes when I'm setting up systems to automate certain machines, mainly ones that require inputs from multiple sides, I have to set up semi-complicated systems using item pipes and filters. My idea is that there should be some way to split a recipe into two patterns. So if I'm trying for instance to automate the magma crucible and fluid transposer from thermal expansion I need to put an interface on a chest that has pipes running to the proper machines. With my idea, you would only have to put interfaces on the proper sides of the block(s). This would not only make things like the magma crucible easier to automate but would also vastly simplify auto crafting with mekanism machines,

**Comment by yueh** [comment]
1) That is not a job for an interface. They just provide materials for any machine in the most compatible way. Which is dump it into an inventory.

2) There is also no need for any other mod besides AE2 to do it currently. So no reason to add redundant functionality.
