### ISSUE TITLE
Storage bus on dsu things disappear

### ISSUE THREAD

**Issue by Nordby9** [AppliedEnergistics/Applied-Energistics-2#2328]
Hi, this is my first post/bug report here.

A friend of mine found this bug by accident on a server we play on.

if you import the items from a cell using an io port and you have a full system, but an empty and locked deep storage unit the items will just vanish.

Here's how you can reproduce it.
1. have a small me system (me controller(don't know if you have to have it), terminal, drive, io port and a storage bus)
2. connect a Deep Storage Unit to the storage bus, then go into its gui and lock it before inputting any items in it.
3. put a cell in the drive and throw some items into the drive.
4. take the cell out, making sure there's no other cell in the me system, and put it in the io port.
5. voila, your items will just up and vanish.

the io port will empty the cell and the items will just disappear.

Sry if this has already been reported. i tried looking, but found nothing.

EDIT: Version: appliedenergistics2-rv3-beta-5

**Comment by Nordby9** [comment]
just noticed something else. if you just throw things into the system through the me terminal of me crafting terminal, it will also disappear, if there is no room in the cell's.

i think its due to the storage bus thinking there is space in the inventory of the DSU whenh its locked. and since its locked, the bus can't input any items, therefore they just disappear.

**Comment by mindforger** [comment]
this is a known problem but i can't remember if it was ever fixed on the DSU side ... try updating to rv3 beta6 and also update the other mod

**Comment by Nordby9** [comment]
Ah, well unfortunately i don't think we can update it. as we play with ftb infinity modpack, and the admin might not wanna start changing mods like that, but ill suggest it to him.
we know not to have the dsu's locked, that will prevent this issue, or just have it set to something before locking it.

**Comment by mindforger** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2214
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1010
from Yueh `I also remember NEI interfere did at one point somehow interfere with DSU and by it also breaking AE2 in some way.`
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1036
^^^this one contains several related bugfixes
