### ISSUE TITLE
AE2 Autocrafting - Patterns messing up

### ISSUE THREAD

**Issue by SaberLegend** [AppliedEnergistics/Applied-Energistics-2#2329]
I was setting up my recipes, and when I tried making the cables in the following pictures, the recipes are all messed up. It also does this with IC2,. Any ideas?

http://prntscr.com/bxji9k

http://prntscr.com/bxjiga

http://prntscr.com/bxjjcg

http://prntscr.com/bxjk0b

**Comment by thatsIch** [comment]
Which version do you use? 

I just tried it with rv3 - 6 and it works
