### ISSUE TITLE
inscriber not working...?

### ISSUE THREAD

**Issue by Hcurt** [AppliedEnergistics/Applied-Energistics-2#2336]
http://imgur.com/a/mhu7Y
You say I need a card?
well I need the inscriber to MAKE a card to be ABLE TO USE the inscriber

**Comment by andros705** [comment]
There is actual inscriber crafting pattern: http://ae-mod.info/Inscriber/
As you can see you don't need any cards to craft inscriber or use it, just craft a vibration chamber and connect it to your inscriber then you can make as many cards you want.

**Comment by mindforger** [comment]
he means he needs an card inside the inscriber to produce his items, he missed the info to >>>search for meteorites to find the cards in the chest in the middle<<<

**Comment by thatsIch** [comment]
Well, this sounds like a modpack issue?

**Comment by mindforger** [comment]
to make my statement more clear.
there is no normal crafting recipe for the presses besides the one to duplicate them! You will have to build yourself an meteorite compass, track them down, dig to their core to find the chest with eventually some of the presses inside the chest

**Comment by thatsIch** [comment]
sounds also possible

**Comment by VT-14** [comment]
I see a manual Grindstone on the side of the GUI, no power cables in that area, and nothing that jumps out as using power in the inventory.  I suspect that Hcurt doesn't have any power setup.  

If you don't have any tech mods for alternative generators (RF, EU, etc.), then use the vibration chamber to make AE's power.

Note that ME systems use AE's power, and only certain blocks convert other power systems to AE.  Things like the Inscriber, Charger, and ME Chest only convert power for themselves (won't power the network), while things like the Energy Acceptor and ME Controller will convert power for the entire network.

**Comment by mindforger** [comment]
wasn't the inscriber one of the exceptions that also accept power directly?! (please correct me when i am wrong) well still, it does totally need power :) though

**Comment by thatsIch** [comment]
It does, though only through top and bottom
