### ISSUE TITLE
Wiki page wrong information

### ISSUE THREAD

**Issue by SilenceKiller99** [AppliedEnergistics/Applied-Energistics-2#2339]
On the wiki page (see first link), it says that four glass cables, one redstone dust and one glowstone dust 
make a dense cable.

As you can see on the screenshot I added (see second link), it should be four covered cables instead of four glass cables.

[http://ae-mod.info/ME-Covered-Cable/](url)
[https://gyazo.com/7ff991dbac73e5c08e7bd8774499aae4](url)

**Comment by thatsIch** [comment]
Fixed
