### ISSUE TITLE
ME items disapearing

### ISSUE THREAD

**Issue by Hedkracka** [AppliedEnergistics/Applied-Energistics-2#2340]
Infinity Evolved (easy mode bug)

I have a SSP world,  The problem I have is that items in my ME system are disappearing, 
What I mean is, I put in for example a block of gold, there are none in there before I do, and none in after. I also auto-crafted 100 pistons, and none appeared in the inventory of the ME even though it completed the run.
I have more than enough storage drives, 40x 64k drives, and 10x 16k, with 10 deep storage units on storage buses locked to 1 item for the bulk building stones.
Channels is not an issue as I used dense cable as needed, and i have 44 Controllers and power isn't an issue as i have 8 dense energy cells and a tesseract from a reactor making 44k rf/t (230k Max)

I do have a few export buses but they have been checked for what they export, and even disconnected to no effect.
![2016-08-07_20 02 43](https://cloud.githubusercontent.com/assets/20891568/17464587/22709838-5cda-11e6-9b64-b8a552325cb1.png)
![2016-08-07_20 02 49](https://cloud.githubusercontent.com/assets/20891568/17464586/226c2ece-5cda-11e6-9b0e-36460f0d9e8b.png)
![2016-08-07_20 03 04](https://cloud.githubusercontent.com/assets/20891568/17464585/2266463a-5cda-11e6-8df4-20c1c03a9ae9.png)
![2016-08-07_20 03 12](https://cloud.githubusercontent.com/assets/20891568/17464588/22777a4a-5cda-11e6-914a-11dbc796130c.png)
![2016-08-07_20 03 26](https://cloud.githubusercontent.com/assets/20891568/17464584/22659604-5cda-11e6-8970-113ff0b50de8.png)

**Comment by mindforger** [comment]
is there a Matter Condenser attached somewhere? i can remember this happening in the past.

Are those DSUs on the third picture? make sure none of them is locked, DSUs cause this when they are locked!

**Comment by Hedkracka** [comment]
MC version 1.7.10 on ftb infinity 2.5.0
The dsu are only locked by the storage bus only having 1 item in the filter. I don't have a matter condenser made yet, so it can't be that. 
Version missed in error.

**Comment by mindforger** [comment]
it is not helping to say the mod pack version, please state the version of the actual mod in question!!!

i checked out myself  for you that it is Applied Energistics 2 rv3-beta-5
that is one version behind for now, maybe try updating it


besides this, please remove the locks from the connected DSUs and if that does not help, remove the locks from ALL DSUs in the vincinity of the system ... something strange with the lock mechanism let items disappear in the past for sure, i have yet no idea what happend about this issue, maybe updating MFR also helps

**Comment by Hedkracka** [comment]
Sorry about not having the ae2 version. I am nowhere near my pc atm so couldn't check.

**Comment by Wildie** [comment]
I'm getting the same issue. 

I've done a little bit of testing and i think it might be some sort of ID Conflict. 
It only happens with certain ID's and it stopped happening on some when i deleted all of the Extra Cells blocks from my AE2 system.

Having said that it still happening on loads of other blocks. I can pick up a stack of "Logic Processor" out of my system and then put them back in and they vanish.

It makes it almost unplayable as the autocrafting relies on this too.
Please dont make me use storage drawers. AE2 is the best mod in FTB.

The issue is easily reproducable in the server i'm in so let me know if you'd like to join me server to analyse. I can also let you see all the log files.

Ta
Wild

**Comment by mindforger** [comment]
@Wildie same task to you, tell us the version you are running, it will help to know that
did you also check the existence of any >locked< DSUs ? remove all locks and test again!

**Comment by Wildie** [comment]
ok i've removed 30 DSU locks and the items i was using to test are now going in to the system.
I'll keep testing it on other items and let you know how it goes

MFR eh?

**Comment by mindforger** [comment]
not sure, but i call this ghost effect approved again then, did you try updating both MFR and AE to the very latest ?

**Comment by thatsIch** [comment]
There were some issues with the special inventory handler of DSUs in the past.

**Comment by yueh** [comment]
Iirc it is not the handler, but just the DSU doing bad things.

Locked ones still accept any item as valid item, then suddenly realize it is the wrong item and drop it into the world, if there is air above them or delete it when a block is above them.

**Comment by mindforger** [comment]
missed that comment on the original issue, baaaaad behaviour IMHO :(
