### ISSUE TITLE
spends the tools durability of gregteh 5u ae3

### ISSUE THREAD

**Issue by natzgzul89** [AppliedEnergistics/Applied-Energistics-2#2341]
instead crafting and crafting new
![screenshot_1](https://cloud.githubusercontent.com/assets/20620700/17483826/c7d7c9f4-5db1-11e6-874e-2988983b1a17.png)

**Comment by yueh** [comment]
AE will reuse tools, if these behave like every other tool/container item. If this is not the case with gregtech, there is nothing we can do about it.

**Comment by natzgzul89** [comment]
Bag only rv3. Rv2 all OK
