### ISSUE TITLE
ME Terminal doesn't work but Wireless Terminal does

### ISSUE THREAD

**Issue by Shobu55** [AppliedEnergistics/Applied-Energistics-2#2342]
Hey,
So yea, my ME Terminal suddenly doesn't work anymore. I can't take items out of it, neither can I put them in. If I try to use the NEI to craft it doesnt work either. The Storage Cells are not full.
If I destroy the Terminal and put it back on it works for one move e.g. I can take an item or put an item in but after that it stops working again.
And If I use my Wireless Terminal I can take items out and put items in with no problem. The only thing that doesn't work is the Terminal right above the ME Drive.
I crafted the ME System like 2 Hours ago and it worked perfectly fine until now...

I hope someone can help me.

**Comment by Shobu55** [comment]
It works again.
I dont know what fixed it now. Maybe the Controller had not enough energy.

**Comment by mindforger** [comment]
do you have ANY energy cells in your system? 

you know 10000EU/t is not enough when your operation demands 10001EU at this actual tick when it only requires 100EU/t while idle! Thats what Energy Cells are for, they Buffer your system :)
