### ISSUE TITLE
The Inscriber doesn't works

### ISSUE THREAD

**Issue by TheFlyingPotato** [AppliedEnergistics/Applied-Energistics-2#2343]
I'm using the newest sable version for 1.7.10. I am also using the correct recipe, but the percent doesn't get higher. pls help

**Comment by EvulOne** [comment]
Screen shots, further elaboration, etc...?  More information is needed.

Are you sure it's being powered?

**Comment by mindforger** [comment]
"sable" i presume you mean "rv2 Stable", this one is bugged and out of service, try rv3 beta, its pretty much more stable than rv2
also please add some more details like EvulOne said :)
