### ISSUE TITLE
AE causes(?) corrupt chuncks on server

### ISSUE THREAD

**Issue by Soschian** [AppliedEnergistics/Applied-Energistics-2#2345]
So yesterday i was on my private server, trying to automate some crafting. The first weird sign i saw was that the level emitters were not working correctly (yes i did watch for channels and so), since they were turned off, although the threshold was reached. So i go to close down the server, and join the next but i can't. The server wasn't starting correctly. I contacted the support of my hosting service, which said that it was probably an error with one or some chunks. Luckily they provide a Chunk fixing tool, so i used it, and i was able to join the Server. BUT (and here it gets interesting) A Chunk right in the middel of my base, where all my machienes were was restored so EVERYTHING was gone. Power, Processing and so on. The Day i automated everything i used about 20-40 channels in this chunk for interfaces, im- and export busses and Molecular assemblers. Why i know it was AE2? Well the server did give me one message which i think is pretty obvious saying some Exception with AE2 (sadly i can't provide anything useful here, since the logs are not accesable for some reason)

**Comment by Soschian** [comment]
The AE2 version used is rv2-stable10 with  ae2stuff-0.5.0.56 and ExtraCells-1.7.10-2.3.9b188 as add-ons

**Comment by mindforger** [comment]
rv2-stable10 is outdated and level emitters were generally broken back then, update to latest beta, currently rv3-beta 6 
i do not think it was AE2 that caused the corruption, it highly more likely was an interaction between AE2 and another mod, causing an issue, and while shutting down the server the save went nuts and damaged this chunk

things i can suggest you for the future: 
- you should always do backups of your world from time to time
- never use chickenchunks chunkloader, they are prone to cause load issues, probbaly resulting in another chunk damage
- always provide enough energy cells to your network when increasing it's size significantly, power input does not match the requirements at peak times, well known fact!

**Comment by Soschian** [comment]
Ok thank you for your quick answer, I will try to all that in the future (although i think that 20kRF/t should be enough in combination with 5 dense Power cells)

**Comment by mindforger** [comment]
sounds good to me, as long as you have ANY installed :D
