### ISSUE TITLE
Suggestion: option to ignore NBT and Meta data for patterns (to auto craft)

### ISSUE THREAD

**Issue by FalloutV3** [AppliedEnergistics/Applied-Energistics-2#2346]
**Version: -rv3-beta-6 **

**Suggestion** 
If you could select to ignore meta and NBT data for patterns it would be a lot easier to auto craft items from mods such as magic crops. 
**Issue **
Currently I am attempting to craft particular magical essences from magic crops. These essences use recipes which require different tiers of infusion stone, when you craft using these infusion stones they loose durability. When I attempt to auto craft the magic essences,  instead of using the damaged infusion stone  (durability of the infusion stone does not affect its ability to craft magic essences , until its durability is 0 ) the AE network thinks that a new stone needs to be crafted for each magic essences.

Here are some screen shots to illustrate how the infusion stones work with crafting and how the AE system is behaving with the infusion stones when attempting to auto craft magic essences.

-Hope this suggestion is laid out properly ,this is my first time :)

![2016-08-11_01 29 43](https://cloud.githubusercontent.com/assets/11558013/17575773/2e53ac1c-5f64-11e6-8d5f-b9cbfe25e141.png)  //Undamaged infusion stone 

![2016-08-11_01 29 49](https://cloud.githubusercontent.com/assets/11558013/17575782/4250d7da-5f64-11e6-912e-e6a62c290c14.png)  //Infusion stone losing durability after 1 essences is crafted 

![2016-08-11_01 30 34](https://cloud.githubusercontent.com/assets/11558013/17575796/5c530784-5f64-11e6-80b9-7d5c68fbb942.png)  // Issue with attempting to auto craft the essences  (instead of using damaged infusion stone the AE thinks the infusion stone has to have not lost any durability to craft the  magic essence)

**Comment by yueh** [comment]
Not possible as these are integral parts of the crafting in minecraft. Ignoring them can lead to items being craftable with cheaper materials when mods use NBT or metadata to distinguish different items.
