### ISSUE TITLE
Interface too slow

### ISSUE THREAD

**Issue by Lyror** [AppliedEnergistics/Applied-Energistics-2#2349]
Hello,

I would like to power this maschines with an interface for auto crafting. There is one problem because the interface put too slow the Items into the Enderchest. Can I configure the speed in the config or something else? I use for crafting an 10x10x11 multi block and my system has 6 me controllers
![2016-08-12_19 11 20](https://cloud.githubusercontent.com/assets/10835078/17630718/b5ce860a-60c0-11e6-9303-8be219fdc407.png)
![image](https://cloud.githubusercontent.com/assets/10835078/17630904/e1144808-60c1-11e6-9265-8465b8854faa.png)

**Comment by XFactHD** [comment]
This has nothing to do with the interface, the limit is the pipe you are using.

**Comment by Lyror** [comment]
oh sry. the molecular assembler was too slow. Do you now a pipe that can ulimited transfer items?

**Comment by XFactHD** [comment]
No, sorry
