### ISSUE TITLE
Spawning inside a crater

### ISSUE THREAD

**Issue by znxster** [AppliedEnergistics/Applied-Energistics-2#2350]
I just started up a new world with FTB Infinity (latest pack 2.6.0, AE2 version rv3-beta-6), when it spawn I immediately died from fall damage. I re-spawned, died again, on the third life I spawned and survived.

It turned out that a meteor had landed directly under me on spawn. As such, I wish to suggest that meteors be restricted to not appear within world spawn?

Thanks for a fantastic mod!

**Comment by CraftMinerKyle** [comment]
That is in a config file. If you are running on a server, you will need to find the file, I forgot what it is called. The config is whitelisted chunks from spawn I believe, and it is to prevent such things as this from happening. If you are on a singleplayer world, go to mods>Applied Energistics 2>Config>(I forgot the name)

**Comment by CraftMinerKyle** [comment]
You should find the configuration file easily there.

**Comment by znxster** [comment]
I have since abandoned that particularly world. The information is still useful for sure, so thanks!

It is still reasonable to expect that the default white lists the chunks without need of a configuration change.
