### ISSUE TITLE
ME IO Port, Storage Transfer Discrepancy

### ISSUE THREAD

**Issue by Iomega0318** [AppliedEnergistics/Applied-Energistics-2#2352]
A little hard to give a title to the problem, not sure if it's meant to be this way or if something changed but I don't ever remembering AE working this way.

Version: **rv3.beta build 6**

Here is what I noticed,

I have  12982 of 16384 Bytes on a 16K Storage Cell, when I use the IO Port to transfer to a 64K Cell I end up with 37174 of 65536 Bytes used.

Something about that just seems wrong.. I remember AE using the same amount of bytes when transferred to a larger cell.. so I should have ended up with 12982 of 65536 Bytes being used instead of 37174.

_This is my first time using the new R3 builds I've been on R2 for a while until this modpack so not sure if this was an intentional change or not.._

**Comment by yueh** [comment]
See [storage math](http://ae-mod.info/ME-Storage-Math/).
