### ISSUE TITLE
Issue with paint brushes

### ISSUE THREAD

**Issue by Multiface24111** [AppliedEnergistics/Applied-Energistics-2#2353]
Paintbrush do not paint the cables like they suppose to - both the painter and paint brush from IE2 and OpenBlocks do not work, only the color applicator do, which is the worst possible option

**Comment by yueh** [comment]
As far I as can determine from the openblocks and IC2 API both actually support RGB values and there is simply no mapping between both. Even if we attempt to make one, RGB is not sufficient. For AE we would need an RGBA value.

AE colours are a fixed set of 17 types, not RGB values. Displaying them as numbers with 0-16 would just be as sufficient as colours. But colours are  just better as visualization. 

Thus it is really not possible to provide support for them without having the player to force to use their item and the color applicator itself to be able to fully utilize it.
