### ISSUE TITLE
Crash on rv3-beta6 version

### ISSUE THREAD

**Issue by Stormageddon223** [AppliedEnergistics/Applied-Energistics-2#2354]
When i shift- double left clicked  a piece of coal that i had in the crafting terminal with another item selected my game crashed,it gave me 2 blank crash reports,
here's the game output http://pastebin.com/X9ScCCNf

**Comment by mindforger** [comment]
if i translated it right, enderstorage has a problem with your hard drive beeing toitally full .. nothing related to AE ther ... thats probably also a reason why your crashlogs are empty!
