### ISSUE TITLE
Auto Crafting Locks Network Until Done

### ISSUE THREAD

**Issue by cjburkey01** [AppliedEnergistics/Applied-Energistics-2#2356]
When I try to autocraft anything using the molecular assemblers, specifically a large recipe, my system becomes unusable.  I can open the gui and look at item counts, but I can't take anything out or put anything into it.  I've experienced this issue with the Pattern Terminals and Crafting Terminals.

**Comment by JelmarG** [comment]
It's a bit difficult to say what the problem is without more information about the design of your AE network.

**Comment by cjburkey01** [comment]
One thing that might cause it is my extensive usage of the conduits from EnderIO.  Another issue I was having was something about the max stack size being anywhere between 2 and 58, so when I'd click on an item, at most, it would put 58 below my cursor.  The same goes for shift clicking.  Some items only allowed me to take them out and put them in one at a time.  What I did was completely redesign my network, but I haven't set up autocrafting yet.

**Comment by mindforger** [comment]
sounds like an power issue, try adding more energy cells

NO, having a gazillion RF/tick input is not enough :) you will need a buffer

**Comment by cjburkey01** [comment]
It might have been, I had the AE2 stuff wireless transmitter which takes a good bit of power.  I actually haven't used the power cells before, if I start having these problems again, I'll try adding some.
