### ISSUE TITLE
Can't connect p2p tunnels through p2p connected network

### ISSUE THREAD

**Issue by SinaKamali76** [AppliedEnergistics/Applied-Energistics-2#2357]
Ok this is a bit hard to explain so I'll put a link to a picture of my problem
[link](http://imgur.com/a/4i9kV)
Now the problem is this, so I have something similar to this setup in a much larger scale, and the problem is that when the two p2p tunnels on the blue network are connected, I can't connect the two p2p tunnels on the green(lime) network, even though using the network tool shows they're on the same network, when hovering over either of the p2p tunnels on the green(lime) network, Waila says "Device Missing Channel".
Now idk if this is actually a bug, or more likely because of my lack of information on networks and how p2p tunnels work, but any help would be great.
I also tried putting a controller on the green(lime) network, on one of the sides, doing that made the p2p tunnel on that side go online but the other tunnel still had the same issue

**Comment by SinaKamali76** [comment]
ok so I read on the website that channels aren't transferred through tunnels, so that's my problems, the only question is, how can I make this design work?

**Comment by vallard192** [comment]
http://ae-mod.info/P2P-Tunnel/

ME Tunnels can be used to carry channels from one location to another, and
can carry up to 32 channels <http://ae-mod.info/Channels/>, same as a ME
Dense Cable <http://ae-mod.info/ME-Dense-Cable/>, while only requiring a
single channel per point, making tunnels a very powerful tool to expand me
networks <http://ae-mod.info/ME-Network/>, especially over a distance.
However with the great flex-ability they give you comes a limitation, the
channel of a p2p tunnel cannot be carried by another p2p tunnel, meaning
that you cannot nest them recursively.


You cannot run a p2p tunnel through a p2p tunnel.  In the image you linked
to, you could replace both green cables with dense cable and you would be
able to get a total of 32 channels out of either end of it.  (Dense cable
on the controller, you'd need to step down from dense to normal cable to
connect the ME Chest).

**Comment by mindforger** [comment]
each dense line can transport 16 p2p nets with each 32 channels, meaning each dense line ist capable of 512 channel, this should really be enough for a single line

**Comment by SinaKamali76** [comment]
Ok let me explain exactly what I wanna do:
Basically I'm making this modular network with a lot of room for devices, I have [these](http://imgur.com/a/pepEr) modules as my controllers. now as you can see here, I have the 32 p2p tunnels connected to a controller as using the lime cable I can distribute the tunnels, but the problem is that single controller, see I want to have something like [this](http://imgur.com/a/lxIxR) to see how many free channels I got on each tunnel, building this walls needs 64 p2p tunnels, twice as much p2p tunnels on my controller, now say I upgrade the controller module to have like 72 p2p tunnels, so the wall would need 72x2=144 p2p tunnels, now that's quite a lot of channels, and I haven't even accounted the auto crafting module, the storage module, the display module, the misc module and so on...
now all of those modules use channels available from those 8 controllers, but the wall has to be on the network with the p2p tunnels surrounding the controllers, now if I upgrade the controller module, that single controller block would not be enough to support all those channels for the wall, so I decided to have a multi-block controller module for that as well, like [this](http://imgur.com/a/ES97B), now in this picture, the single controller that I had before is replaced with the module on the right, the storage, auto-crafting and stuff like that would be on the network in the left controller module, and the p2p tunnels, which also make up the wall would be on the right controller module's network, but as I mentioned in the first post, I can't make the system work because I can't connect the left controller module to the controllers on the right module

**Comment by mindforger** [comment]
your first picture link is not working and the second one is an empty 0px sized picture for me, dunno if my browser trolls me or your file is damaged?

**Comment by SinaKamali76** [comment]
just checked, the first link was fixed, but the other look fine to me

**Comment by mindforger** [comment]
i dont get the idea behind all this, it looks overcomplicated

why not making a 8 block long controller with p2ps on each side, this makes 32 p2ps and on the upper and lower face you can install 2 independend dsitribution cable, each connecting half of the p2ps on the controller and their correpsonging end wherever you need it?

**Comment by SinaKamali76** [comment]
I just wanted to use all the channels I can, with my setup I almost always use up the 32 channels provided by the dense cables, with maximum amount of channels in each, 32x32 channels each dense line

**Comment by SinaKamali76** [comment]
I'll close the issue as this isn't actually an issue, more like a design problem on my side, thanks for all the help
