### ISSUE TITLE
[request] pattern storage expansion.

### ISSUE THREAD

**Issue by Tcll** [AppliedEnergistics/Applied-Energistics-2#2358]
Too many times I find myself crafting more interfaces than a single machine supports because there's just too many recipes for 1 interface to handle... (and more machines means more lag)

So here's an idea to fix that:
![img](https://lh3.googleusercontent.com/O5zOlyMBzbU6_IOSHuUQtOYq7bVjHJ5eobFOatHSW5NSceTQRTxPRQnPf6vXzbmNrrpMqfAV9UKlIq7l7n_haFxoE6KLnZvFm0ZzKsIrC4dLpe83l2hEXqEnPhmq8SiD_wtnRYq5lJZEGRj8Mrz8H4KqtmIliEdEBAPkioSB0HuaCP4rvLxaOoOikg4MLv41FAL4kTXXvoXijC4qoVPVeSr7hUhFwcABb3hdK_5ZibocKwYwfqw1ygSoGmngSE9_AwG9lFfbQLZJxwslJ8YewECPjtmQlpAxs_8YFc7We5HS4cVRjLXnjttY8f1xw1IQtMCvFuzBowgY7x3763tEZUcHqWe2MLzdTB6iQwCeesmb3ql_ema9HnB1H1NBBJ3CPGJpDVJpYyeXMHxt96O2hLGl7h9yG_pXrJ4IsiRUhR0DUgrhSLfblw0QQf3XnCTMEgKpuLaYUc8hreXJ4eu7mGqNZpMhRBnjaJyxV1J_UmYRtGFi7HsCCPiWJKDveGazIvSI7a5Slm0L9l1oLNgBc44L7_9CHLPoQ-gxmObU9lABRu9yZCon8WAwYSoYROeY2gkV_K3-A-ed8J7R0ixnhmydIrIVYQw=w1850-no)
(Sorry for the green bg, might update the image with transparency later)
so with this, you can use a max of 3 expansion cards to expand the pattern storage and make things less painful.

Another idea for this is to make either the ME or item p2p link and inventory to an interface.
(This would also aid in less painful autocrafting because it would allow 1 interface to connect to a cloud of Molecular Assemblers)
^ expandable to 6 interfaces for dynamic autocrafting.

**Comment by yueh** [comment]
#393

**Comment by Tcll** [comment]
My focus was not aiming at balancing between ae1 and ae2, it was aimed at improving it's design.
using 6 interfaces per a single MA is VERY  inefficient and only aids in creating issues.

Consider a cloud-farm using 4 planters in the cloud.
at best design, this gives you enough room for 9*4 recipes per planter with a speed increase of 4 pattern dupes (a very poor and painful design)

My aim is to reduce the pain to achieve the same results.
