### ISSUE TITLE
[request] send the crafting request's item count to another mod.

### ISSUE THREAD

**Issue by Tcll** [AppliedEnergistics/Applied-Energistics-2#2359]
To expand on mod support for autocrafting using another mod,
when making a request from a terminal, make it possible to send the request count so the other mod can know exactly how many to craft.

Currently you have to use a Redstone emitter to implement a sort of `while True:` interface, which imo is pretty stupid because it'll cause major over-crafting with a dynamic cloud setup.

So this idea is a safer approach using a `for i in range(count):` interface.

**Comment by yueh** [comment]
That is already possible. The mod in question just has to let their machines join an ME network and then it can use `ICraftingWatcherHost` to watch how many items are still left to craft.

**Comment by Tcll** [comment]
Hmm... looks like I'm at an impass...
The mod in question for my personal use is OpenComputers.
The adapter allows you to issue crafting requests but doesn't accept them when issued through the terminal...

Yeh, I don't think there's much you can do here except possibly modify the Redstone emitter to light up when said amount is requested...

I could configure that into a binary output with multiple emitters, and you get the rest... :P
