### ISSUE TITLE
Import bus/Interface feature to craft “endless” resources

### ISSUE THREAD

**Issue by xZise** [AppliedEnergistics/Applied-Energistics-2#2360]
It seems there is only one way to automate generators (like a snowball generator). And that would be to have a level emitter which at some point emits a signal to stop the generator when you think there is enough of it in the system. But if you set the level to low and have a large crafting task scheduled using more than the amount cached it won't allow you to craft it (even though the generator would refill the resources).

So maybe there could be a part which handles these cases. Now in the case of the snowball generator it would need to output a redstone signal as long as it requires snowballs so that the “machinery” would run and create new snowballs until the CPU actually got enough snowballs. Then the redstone signal would deactivate and the machinery would stop (or the signal is inverted). This would also allow a user to query a given amount of snowballs.

Granted such a setup would probably produce to many snowballs (or items in general), but that might be the case with other setups as well. It would also probably use less compared to the current implementation.

In theory it could also handle other resources which don't actually need a signal. For example if there is a cobble stone generator and that is running all the time anyway, then this part could just signal the CPU that there will be as much cobble stone as it wants. But not sure how sensible this is, especially as it wouldn't really require an actual part placed in the world.

**Comment by yueh** [comment]
Already possible. Just switch the mode of the level emitter.
