### ISSUE TITLE
Quantum Ring only using one channel.

### ISSUE THREAD

**Issue by Furious1964** [AppliedEnergistics/Applied-Energistics-2#2361]
I hooked a bunch if interfaces and assemblers and the ring is only giving one channel.

I'm using R3 Beta6.

[http://imageshack.com/a/img921/6637/6reFlp.png]

Image is without the assemblers.

Tested it by going to the Nether and it's the same thing.

**Comment by JelmarG** [comment]
You're not showing the Quantum Bridge on the other side.

**Comment by Furious1964** [comment]
The other side is buried deep into this thing that I built:

[http://imageshack.com/a/img924/4712/VTOUMr.jpg]

I'll try and make another set today linking the Overworld to the Nether.

**Comment by Furious1964** [comment]
Nevermind, with the help of someone from YouTube I was able to fix it.
