### ISSUE TITLE
AE2 conflicting with Blood Magic

### ISSUE THREAD

**Issue by Diuqil69** [AppliedEnergistics/Applied-Energistics-2#2364]
- 
- 
-     http://puu.sh/qZlZa/0942eb7273.jpg
-     http://puu.sh/qZm0h/d036b9b204.jpg
-     --------------bare minimum setup----------------------------------
-     http://puu.sh/qZm3f/9d84525bf3.png - Me fluid export bus
-     http://puu.sh/qZm9K/f4dc959a5d.png - Me fluid storage bus
-     http://puu.sh/qZmdU/bc7d7b8ea6.png - Blood Altar
-     http://puu.sh/qZmsp/ab3299ec26.png - ME Fluid import bus
-     --------------------------------------------------------------------------
-     Alright so basically all you do is setup a normal ME system to start with. I don't see any reason to post those steps do I?
-     In all actuality you just need power going through the me cables so the fluid import bus/fluid storage bus can start pulling blood out of the blood altar
-     which you can then redirect into me export bus's which are attached to tanks. which nearly filled my resonant ender tank which holds 512000mb of liquid
-     with less than 7500 mb of blood in the blood altar. Not at all sure how that math works out but it did.
-     So easy a 5 year old could do it based on the pictures alone.
-     This is just the easy setup though.
-     There is a bit more complicated setup which wont matter if the above bus's are restricted from attaching to the blood altar which included fluid me drives and
-     storage monitors and just alot of bizarre stuff I barely comprehended. So I believe the above info should be good enough for now.
-     Need any more info and I can possibly make a video tomorrow that may help, but I truly believe the pictures are worth enough words.

**Comment by yueh** [comment]
AE2 does not support fluids, you have to report it to Extra Cells.
