### ISSUE TITLE
crash when attempting to open the crafting terminal

### ISSUE THREAD

**Issue by matrixfury1** [AppliedEnergistics/Applied-Energistics-2#2366]
Hi there!

I am getting a tessellating error when I attempt to open the me crafting terminal. The version is rv2 stable 10, and the forge version is forge-1.7.10-10.13.4.1614-1.7.10-universal

Any help would be welcome

[crash-2016-09-04_14.55.13-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/454132/crash-2016-09-04_14.55.13-client.txt)

**Comment by matrixfury1** [comment]
this is a new crash report I got from trying the same thing with the arcane crafting terminal


[crash-2016-09-04_15.29.02-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/454147/crash-2016-09-04_15.29.02-client.txt)

**Comment by VT-14** [comment]
rv2 is way out of date.  Update to the most recent version of AE2 you can find (rv3).

Arcane Crafting Terminal is from Thaumic Energistics.  As the normal terminal is crashing, it is likely a problem with AE2; and that might be fixed by updating.

**Comment by matrixfury1** [comment]
I updated to rv3 beta 5 and thaumic energistics as well but the issue persists

**Comment by mindforger** [comment]
this sounds most likely an broken item renderer from another mod, but i have no details on the callstack, can you check the other mods for updates?

And from my own experience i would almost call out Powersuits and exspecially Numina Core Mod as possible sources ... but that is only an personal experience, do not count on it :)

**Comment by matrixfury1** [comment]
Well i have in fact narrowed it down to a specific storage cell in the network, but I don't know of a way to pull all the items off of it without using a terminal.

**Comment by mindforger** [comment]
Power Acceptor + IOPort + cable + storage busses into Chests 
throw the drive into the IOPort set to import and the content will be droppend into the storage ports and their chests

**Comment by matrixfury1** [comment]
Well I pulled the 10 items off, but there were not any items in the chest. And when the drive which is now empty is put back in the system it still crashes.

**Comment by matrixfury1** [comment]
never mind that last comment, I got the items into a chest but now when I try to open that it crashes.
[crash-2016-09-05_07.41.36-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/455244/crash-2016-09-05_07.41.36-client.txt)

**Comment by mindforger** [comment]
das sieht jetzt nach einem cover das irgendwas von thermaldynamics als basis hat aus

**Comment by matrixfury1** [comment]
pardon?

**Comment by Pingger** [comment]
Translation: Looks like a cover or something that relies thermaldynamics (including td)

**Comment by mindforger** [comment]
what the ? sorry my internal translator must have failed very very hard O_o

**Comment by matrixfury1** [comment]
it's all good, it turns out there was a conduit cover in the system that it couldn't render for some reason. So I uninstalled the mod and put it back in and everything works fine now

**Comment by matrixfury1** [comment]
Actually a null cover makes sense because I just upgraded from chisel to chisel 2 and the cover was made from a chisel block.
