### ISSUE TITLE
Feature Request - Crafting Jobs take the CPU with the least Memory

### ISSUE THREAD

**Issue by Pingger** [AppliedEnergistics/Applied-Energistics-2#2367]
I noticed some very odd behaviour:
When I create a crafting Job always the CPU with the most Memory is used.
e.g. I have 8 1K CPUs, 4 4K CPUs and 1 64K CPU
All have the same amount of Co-Processors
When I start a Job to craft 1000 Glass (Interface to Furnace) the Job takes 3112 Bytes. It would fit into one of the 4K CPUs but instead it takes the 64K CPU. I tried to craft some 64K Storage units which needed more than 4K but 64K CPU was blocked by the Glass Job.

When building the ME System I tried to build the 1K CPUs then the 4K CPUs then the 64K CPU.
But the ME System automatically sorted them by size which resulted in this odd behaviour.
I guess simply reversing the order would fix the issue

Greetings
Pingger

PS: Issue exists in ALL versions

**Comment by yueh** [comment]
#1055, #1188, #1814, #1920
