### ISSUE TITLE
Autocrafting and Magical crops not working as intended.

### ISSUE THREAD

**Issue by Quazaka** [AppliedEnergistics/Applied-Energistics-2#2369]
When i try to automate crafting an item that require any of the infusion stones from magical crops with durability. The AE auto crafting system will try to craft a new infusion stone instead of using the one in my inventory which still have durability available.

**Comment by XFactHD** [comment]
As far as I know this is caused by the fact that the infusion stones store their durability in the item's NBT data.

**Comment by mindforger** [comment]
that is an issue on magical crops, if they implement the proper damage value, AE can take account for that

**Comment by VT-14** [comment]
I don't think AE completely takes damage values in account; recipes with AE2 cutting knives have the same problem... Unless that was fixed recently. I haven't played a 1.7.10 pack in a few months.

You can make the recipe use substitutions, which will remove the durability requirement, but the recipe assumes the item is used up.  If you have 1 on hand and request 16 crafts, it will think it need 15 more infusion stones.

If I recall correctly, the final infusion stone is never used up and works for all levels, and AE should know how to use that properly.
