### ISSUE TITLE
AE2 RV3 Exceptions?

### ISSUE THREAD

**Issue by neogenix** [AppliedEnergistics/Applied-Energistics-2#2371]
Hi Guys, 

I'm running a FTB Infinity 2.6.0 Server, and a reasonable ME system internally. I've setup auto crafting, and noticed a pretty hairy increase in tick skipping by FastCraft. I pulled up YourKit, and noticed that the AE2 CraftBranchFailure class seems to be generating an inordinate amount of exceptions (as well as the crafting calculators). 

I'm totally not a Java person, so I can't be much help, other than access to the server, mods, etc.... 

The versions: 
AE2 - FTBInfinityServer_2.6.0/mods/appliedenergistics2-rv3-beta-6.jar
Forge - 1.7.10
Java - Oracle Java 1.8.0_101 
Ubuntu - 16.04 64

I've attached some of the oddball things I was seeing: 

![screen shot 2016-09-14 at 1 18 01 pm](https://cloud.githubusercontent.com/assets/141967/18522408/f50c79fe-7a7d-11e6-89f3-3009484769f2.png)
![screen shot 2016-09-14 at 1 12 47 pm](https://cloud.githubusercontent.com/assets/141967/18522407/f506b85c-7a7d-11e6-8976-bc24e06e16a9.png)
![screen shot 2016-09-14 at 1 12 28 pm](https://cloud.githubusercontent.com/assets/141967/18522405/f503c318-7a7d-11e6-845d-8cf8619bf6a8.png)
![screen shot 2016-09-14 at 1 12 20 pm](https://cloud.githubusercontent.com/assets/141967/18522406/f505be98-7a7d-11e6-9d7f-fc54b616c41a.png)

**Comment by yueh** [comment]
This is intentional.
