### ISSUE TITLE
Chunks Generation

### ISSUE THREAD

**Issue by HeberonYT** [AppliedEnergistics/Applied-Energistics-2#2372]
Hi.
I have a server with several mods, but from the beginning I had performance problems due to the load and generation of new chunks.
So I decided to add a plugin to place a global edge, so users do not load new map and do not cause lag.
But after placing the edge, it was still being generated new map beyond the edge, but found that due to its mod AE2, specifically to the generation of meteorites, here is a photo of the chunks generated off the edge, there is a similarity in them, and everyone agrees to have a meteorite in the center of the area generated, you can be on the surface or at depth.
[![Screenshot_3.png](https://s10.postimg.org/e8io32fu1/Screenshot_3.png)](https://postimg.org/image/hs4lsvijp/)

Here the border edge is red, but there are random chunks charged out and all have a meteorite in the middle.
[![Screenshot_4.png](https://s21.postimg.org/kyj7bcebr/Screenshot_4.png)](https://postimg.org/image/5d1vre2df/)

I want to help me solve this problem because the map has become huge because they are still loaded edge areas outside world.
_Regards!_

Mod version used appliedenergistics2-rv2-stable-10.jar

**Comment by mindforger** [comment]
switch to rv3 beta6 because rv2 is out of service

**Comment by yueh** [comment]
AE2 does not feature any chunkloading regarding meteors. They are simply world decorators/generators like trees and are generated once a chunk was loaded the first time. So if they appear, there is something loading the chunks, like players teleporting around or something else.

It is very likely just a coincidence, that they are placed on the randomly loaded chunks. Meteor generation is a NFA and not a DFA like most other world gens. Which means their location is not known until a chunk with a minimum distance to another meteor is loaded the first time. Therefore randomly loading chunks all over the place and with enough distance between them will certainly place a meteor there and most likely at the center as these should be the first chunk to be loaded as they will will very certainly match the conditions to spawn a meteor.
