### ISSUE TITLE
Sky Stone Chest Rendering Issues

### ISSUE THREAD

**Issue by shartte** [AppliedEnergistics/Applied-Energistics-2#2379]
The sky stone chest is using a TESR to render. Investigate how the warning about the missing block model can be avoided.

Orientation of the sky stone chest is also incorrect on the north/south axis.
The chest also doesn't have correct break particles.

**Comment by Eufranio** [comment]
1.10?

**Comment by mightydanp** [comment]
No support for unreleased versions.

**Comment by Pandafuchs** [comment]
1.11?

**Comment by shartte** [comment]
This is just a TODO ticket. See the milestone on the right. The models exist, it's just about warnings in the startup log.
