### ISSUE TITLE
item and block names.

### ISSUE THREAD

**Issue by mightydanp** [AppliedEnergistics/Applied-Energistics-2#2382]
can you add all of the item and block names back to what they should be named instead of itme.appliedenergistics2.basic_storage_cell_64k.name

**Comment by XFactHD** [comment]
Which version are you talking about? The 1.7.10 versions have localized names and the 1.10.2 version is simply not finished yet and localization is usually low priority when the mod is not released yet.

**Comment by yueh** [comment]
We simply cannot support custom builds or unreleased versions.

Secondly as warning. Expect to lose parts or even the complete world at any time, when using these.

**Comment by mightydanp** [comment]
i dont know why your closing my stuff with "We simply cannot support custom builds or unreleased versions." in the read me there is information about doing a build. Everyone else is posting the bugs they are finding in 1.10 as of I so you might as well assume have "We simply cannot support custom builds or unreleased versions." as well. I am just posting the bugs I find to help your mod. Hence why there is a issues section and a CONTRIBUTING.md
