### ISSUE TITLE
Middle Mouse click not Work

### ISSUE THREAD

**Issue by maginator** [AppliedEnergistics/Applied-Energistics-2#2384]
Hi, I have made a Pack and if i Would to Autocraft something that i have in my System normaly i can click with the middle mouse button on it but it dosent work. Please Help

The Mods:
MC 1.7.10
Minecraft Forge 10.13.4.1614
Ae2 Stuff
Agricraft
Anotherbitethedust
applied energistics 2 rv3 beta 6
Aroma1997Core
Aroma1997 Mining World
Bdlib
Biblocraft
Biblowoods Forestry
Biblowoods Natura
Big Reactors
Binnie Patcher
Binnie mods
Botania
Brandons Core
Buildcraft
CarpentersBlocks
Catwalks
Mrcrayfish furniture
Chicken Chunks
Chisel
Code Chicken Core
CofhCore
Cofhlib
Compact Machines
Computercraft
Cookingbook
CraftTweaker
CustomMainMenu
Decocraft
Denseore
Draconic Evolution
EnderCore
Ender IO
Ender Storage
Ender Tech
Enhanced Portals
Extra Cells
Extra TCI
Extra Utillities
Factorization
Fastcraft
FastLeaveDecay
FlatSigns
Forestry
ForgeAnalytics
FTBLib
FTBUtilities
Funy Locomotion
Galacticraft Core
Galacticraft Planets
Guid Api
IC2 Nuclear Controll
iChunUtil
IguanaTinkerTweaks
ImmersiveEngineering
Industrial Craft
INpureCore
IntelligentEnergistics
InventoryTweaks
Ironchest
Jabba
Journeymap
LogisticsPipe
Mantle
MatterOverdrive
mcjtylib
Mekanism v9 (Generators, Tools)
MicdoodleCore
Minefactory Reloaded
Modular Powersuit
Morpheus
Natura
NEI Addons
NEI Integration
Nether Ores
No MoreRecipeConflic
NEI
Numina
OpenBlocks
OpenComputers
OpenModsLib
OpenModularTurrets
OpenPeripheralAddons
OpenPeripheralCore
OpenPeripheral Integration
OpenRadio
OpenSecurity
Pams Harvestcraft
Player API
Pneumaticcraft
Portalgun
Project Red(Base,Compact, Fabrication, Interation, Lighting, Mechanical, World)
Railcraft
RecallStones
RedstoneArsenal
RFTools
Roguelike Dungeons
Realisic Terrain Generation
SimplyJetpacks
SolarFlux
StorageDrawers (Foresty, Misc, Natura)
TinkersConstruct
Thermal Dynamics
Thermal Expansion
Thermal Foundation
TinkersConstruct Tooltips
Tinkers Mechworks
Veinminer
Vending
Waila (Harvestability, Plugins)
Wawla
WirelesCraftingTerminal
Witchery
WR-CBE

I hope you can Help

**Comment by Ravin890** [comment]
*Just randomly browsing issue section, and after reading your thing I have to ask. Did you confirm that you have the recipe as a pattern for it to autocraft and placed it in the correct area?

**Comment by maginator** [comment]
Yes normaly with a simple leftclick i can craft it but i missed that with middle mous click

**Comment by yueh** [comment]
Way too many mods to find the issue. You have to pretty much reduce it to just AE2 and whatever mod might interfere with it, for example by overriding the middle mouse button for whatever else.
