### ISSUE TITLE
Ore Directory in Auotcrafting

### ISSUE THREAD

**Issue by meneken17** [AppliedEnergistics/Applied-Energistics-2#2385]
Hey there
I have an automatic setup to craft Solar Expansion Solar Panels.
It has an recipy which requires Iron nuggets.
I have configure the pattern with Thaumcraft Iron Nuggets and Ore Dict Substitutions enabled.

When Iron nuggets are in the systems it uses them without problems, but it doensn't recognize the crafting pattern and reports "Missing" in the Crafting Plan.

I just updated the Server and updated from rv3-beta-5 to rv3-beta-6. 
Before it worked fine.

**Comment by yueh** [comment]
#1703
