### ISSUE TITLE
Downgrade AE2 from rv3 to rv2??

### ISSUE THREAD

**Issue by vDreezx** [AppliedEnergistics/Applied-Energistics-2#2386]
Hey 
is it possible to downgrade the AE2 version rv3 to rv2 ?
I´m playing FTB Infinty and i want to add AE2 Stuff but it only works with rv2.

pls help me :)

**Comment by Gaberboo** [comment]
You don't need to downgrade, there are specific AE2 stuff versions that support rv3.

**Comment by mindforger** [comment]
"I´m playing FTB Infinty and i want to add AE2 Stuff but it only works with rv2." can you explain that more clearly? maybe there aer other mods heavily outdated?

**Comment by Ommina** [comment]
"AE2 Stuff" is a an AE2 add-on by bdew.  Whether that speaks to the existence of other outdated add-ons I cannot say.

And, yes, there is (very functional) build of AE2 Stuff on bdew's website.  No need to downgrade.

**Comment by mindforger** [comment]
" AE2 Stuff" ... got trolled by too common name XD sorry, i thought he was referring with "stuff" to AE2 in general form haha

**Comment by yueh** [comment]
Usually not possible.
