### ISSUE TITLE
AE2/AE3

### ISSUE THREAD

**Issue by king4q** [AppliedEnergistics/Applied-Energistics-2#2387]
hey ive noticed when im trying to comile it for my own personal use theres alot of issues with the build.gradle because i cant change the value for forge or anything without getting errors and i cant  compile it will you make it more open source for updating for personal use?

P.S: great mod cant wait for 1.10.2 global support

**Comment by shartte** [comment]
We simply cannot support custom builds or unreleased versions.

Secondly as warning. Expect to lose parts or even the complete world at any time, when using these.

**Comment by king4q** [comment]
could i get a build of 1.10.2 if you have the source code for 1.10.2 i wanted to see about support as well but theres no dev build on the downloads page for the official AE2/AE3 page

**Comment by XFactHD** [comment]
@king4q If you just want to play around with AE2 I would suggest how to set up a dev environment and simply launch AE straight from the IDE, that's what I did to just play around a bit (although I already had that knowledge because I am a Modder myself).

**Comment by king4q** [comment]
XFactHD would you post the dev enviroment and ill set it up for eclipse myself and i can even build it if i can get the source files that all i really wanted/needed i was gonna try to make a addon for AE2/AE3 when it comes out and i wanted to get a ahead start and have it ready when AE3 comes out and post it for testing so if you could would you please post it and ill set it up with my IDE (Eclipse) myself please and thank you


-King

**Comment by shartte** [comment]
.... what?

I mean we are regularly updating the forge version in gradle.properties and it's working for me (tm).

**Comment by XFactHD** [comment]
@king4q I am not gonna describe that to you, if you do not know how to set up a dev environment, you most likely also do not know java. If my guess is right, you should first learn java and basic modding before making an addon to a complex mod like AE2.

**Comment by king4q** [comment]
i can setup a dev envoroment also could i get a link to the alpha version i couldnt find it
