### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by dpeter99** [AppliedEnergistics/Applied-Energistics-2#2388]
http://pastebin.com/rC6iC8v8

Forge version: 1.10.2-forge1.10.2-12.18.1.2050
Build from commit :  7139663 , [TC](https://ci.tsr.me/viewLog.html?buildId=4978&buildTypeId=AppliedEnergistics_AutoHeadBuild&tab=artifacts#!) , appliedenergistics2-rv3-latest-70.jar

**Comment by XFactHD** [comment]
You most likely have a 1.7.10 mod in your mods folder, that's were I got this exact crash a couple days ago.
