### ISSUE TITLE
Unoptimized calculation time of crafting ingredients

### ISSUE THREAD

**Issue by MilkMC** [AppliedEnergistics/Applied-Energistics-2#2389]
I have a Sky Factory 2.5.4 server. The crafting recipe for circuits is a bit different due to the lack of meteorites. I have included an example below. As far as I can tell, any crafting recipe that leaves an item in the crafting grid after the craft has completed will take a much longer time to calculate the ingredients needed to craft it. Also, the time to calculate the ingredients seems to increase exponentially as you increase the amount of crafts. For example, 1,000 crafts takes approximately 3ms per craft to calculate(3 seconds total), 10,000 crafts takes approximately 3ms per craft to calculate(30 seconds total), 60,000 crafts takes approximately 3.5ms per craft(210 seconds total), 100,000 crafts takes over 5ms per craft(547 seconds total). Now I know that 3ms may seem like a small amount of time, but when you are crafting large amounts of items such as 20 16384k storage cells from extra cells, it takes 3.5 minutes to calculate it. Other crafting recipes do not have this problem. I can tell my system to craft 100 million glass and it will calculate the ingredients in less than a second.
I'm no coder, but I would think that there would be something that could be done to reduce the amount of time per craft.
![circuitcrafting](https://cloud.githubusercontent.com/assets/18663645/18975656/f54b12c6-8668-11e6-8523-6f2161c5bb00.PNG)
EDIT: The AE2 version in Sky Factory 2.5.4 is rv3 beta 6

**Comment by Ommina** [comment]
You may find yueh's closing comment (Jul 22) on #2323 enlightening.  There is more going on with tools that have durability than is immediately apparent.

**Comment by MilkMC** [comment]
Thank you for alerting me to this. I looked through some of the recent issues before I posted this, but I guess I didn't look back far enough.
