### ISSUE TITLE
[1.10] Crash when searching @applied in JEI

### ISSUE THREAD

**Issue by Xiaminou** [AppliedEnergistics/Applied-Energistics-2#2390]
Crash when searching @applied in JEI.
Works fine with AE on its own, but crashes in my modpack.

Crash Report: http://pastebin.com/7XS3eXUA

**Comment by yueh** [comment]
We do not support unreleased versions.

**Comment by Xiaminou** [comment]
'kay then, so much for helping out...

**Comment by DoktorAerzt** [comment]
The Problem is Optifine. 

When you have Optifine installed and Applied Energistics 2. Then at the moment you get this error
