### ISSUE TITLE
Meteor Bug relating to terrain destruction

### ISSUE THREAD

**Issue by Morat2255** [AppliedEnergistics/Applied-Energistics-2#2393]
A meteor in a world I generated recently in Infinity Evolved crashed into a near-surface monster dungeon. The spawner was transformed into a pig spawner. While both hilarious and useful, I don't think this is intended. Thanks for the endgame storage solutions and the pork.

**Comment by yueh** [comment]
That is a vanilla feature/bug with dungeon generation, nothing we can really do about it.
