### ISSUE TITLE
Cable show channel usage

### ISSUE THREAD

**Issue by Meller127** [AppliedEnergistics/Applied-Energistics-2#2396]
Cable show channel usage when device is unpowered
rv4 - 1.10

![2016-10-01_23 54 38](https://cloud.githubusercontent.com/assets/13392710/19017236/1fbe16f4-8833-11e6-8e26-5f3be3e7509e.png)

**Comment by shartte** [comment]
Issue confirmed in my test world as well.

**Comment by shartte** [comment]
Fixed in 1.10 branch.
