### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by JosephRymer** [AppliedEnergistics/Applied-Energistics-2#2397]
Attention @yueh and the rest of the AE team the other part of the AE team that has been working on the port is in discord which can be accessed here. We ask that you join us that way we can close down IRC and switch are team over to discord chat for various reasons which will be made clear once you join the discord server . 
Link to discord 
https://discord.gg/Mm2vb2m

**Comment by yueh** [comment]
There is no offical AE2 discord server/channel/whatever.

IRC will never be abandoned as this is the place most devs hang around and I personally will never use discord for anything important.

**Comment by JosephRymer** [comment]
Serisouly the reason we setup discord was so we dont have to have a mess of issues tickets her and we can all communicate and discord and its not just you personally that i want to join but everyone else we already have me elix and depter which have joined it and lots of the community have as well and they seem to like it so if you would please make an effort to get the rest of the AE team to join that  would be great

**Comment by shartte** [comment]
@JosephRymer Please feel free to join the AE IRC channel on esper to chat (see main readme for details).
You'll find that esper.net has a large Forge development community and hosts the official Forge IRC channel, as well as the official channels of many other mods.

**Comment by JosephRymer** [comment]
@shartte esper IRC can be accumalted into discord 
and comms can be sent between the 2 i think discord is the better option myself we already have 4+ tema members form the modern port in the discord server 
https://discord.gg/Mm2vb2m
