### ISSUE TITLE
AEModernMCPORT

### ISSUE THREAD

**Issue by JosephRymer** [AppliedEnergistics/Applied-Energistics-2#2399]
So I am apart of the AE team for the port to 1.10 and I saw the branch made in the official ae team for 1.10 and all are work was sent there. I am just curious what going on with that and if the AE modern port team is going to be able to continue to help or if there being screwed over and dumped off

**Comment by JosephRymer** [comment]
@shartte @yueh whats is your response to my question

**Comment by yueh** [comment]
#2306 is still valid source for the reasons behind that repository or the 1.8+ port in general.

**Comment by JosephRymer** [comment]
so you are going to dodge my question with a vague answer ok very well
