### ISSUE TITLE
Inscribers only accept items in the middle slot

### ISSUE THREAD

**Issue by Scoaex** [AppliedEnergistics/Applied-Energistics-2#2410]
Inscribers only accept items in the middle slot (presses/silicon/gold...)
Your unable to put anything in the top/bottom slot. (tested over gui and hoppers/busses)

**Comment by shartte** [comment]
You have not provided any version information...

**Comment by Scoaex** [comment]
Oh sorry, actual 1.10 Branch

**Comment by yueh** [comment]
Duplicate of #2375
