### ISSUE TITLE
Finalize Block and Item IDs To Avoid Breaking World Changes

### ISSUE THREAD

**Issue by shartte** [AppliedEnergistics/Applied-Energistics-2#2415]
This issue is here to collect any outstanding item and block id changes that need to happen before anything can be released.

- [x] ioport -> io_port for consistency.
- [x] mass_cannon -> matter_cannon for consistency with the item name ingame.
- [x] basic_storage_cell_ -> storage_cell_ (basic seems superflous)
- [x] multi_material -> material
- [x] multipart -> part

**Comment by DFliyerz** [comment]
Somewhat related to this, I've finished a version of the recipe config files which fixes all of the recipes. I'll check here to keep the fixes updated.
