### ISSUE TITLE
ME Drive missing break particle

### ISSUE THREAD

**Issue by Meller127** [AppliedEnergistics/Applied-Energistics-2#2416]
ME Drive missing break particle.
Rv4-1.10
9eb093d865704b874a1dabdfa1f841ce2f1519a6
![2016-10-03_17 55 49](https://cloud.githubusercontent.com/assets/13392710/19044046/ebeda086-8992-11e6-81b2-95e06e53301c.png)

**Comment by shartte** [comment]
Fixed
