### ISSUE TITLE
Replace IExternalStorageHandler with IItemHandler

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#2417]
Replace our own `IExternalStorageHandler` to abstract external inventores with the new `IItemHandler` to support any custom inventory as long as they provide their own `IItemHandler` implementation and without having them to explicitly implement and register a custom version just for AE2.

Note this requires a new way to handle internal network inventories exposed to storage buses through interfaces.

This also includes removing any other related class related to the `IExternalStorageHandler` like `IExternalStorageRegistry` and its implementation.

**Comment by shartte** [comment]
Fixed by #2508
