### ISSUE TITLE
Replace LayerBase with a way to have parts expose capabilities

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#2420]
The existing system to transform layers onto the cable bus to add support for new parts like thaumcraft parts or PneumaticCraft P2P tunnels should be replace with an option to have parts simply expose their capabilites and we no longer have to do any asm magic and thus reduce the overall complexity,

The downside is that only capabalities are support as first class citizen, everything not based on them will no longer be supported. So for example no RF P2P tunnels anymore. This case might now be obsolete now, but there can certainly be some mods avoiding capabilities for whatever reason.

**Comment by shartte** [comment]
@yueh Isn't this already implemented? Or maybe I missed a spot, but I think I implemented the capability forwarding from the cable bus tile entity to the respective parts.
See IPart.getCapability and IPart.hasCapability
