### ISSUE TITLE
Can't Launch on Latest Build

### ISSUE THREAD

**Issue by DFliyerz** [AppliedEnergistics/Applied-Energistics-2#2422]
http://pastebin.com/22EwDeJy
Minecraft doesn't get any further than this.

**Comment by yueh** [comment]
This is not related to AE in any way.

**Comment by shartte** [comment]
I believe someone posted before that this means you have a 1.7 mod in your mods directory, @DFliyerz .

**Comment by DFliyerz** [comment]
@shartte However, I can launch fine with all the same mods except a slightly older version of AE2. I tried the two latest commits, and couldn't launch with either.

**Comment by XFactHD** [comment]
That doesn't make sense as the interface IFMLLoadingPlugin was moved (or to be exact the source root "cpw.mods.whatever" was removed) in 1.8 or 1.9.
