### ISSUE TITLE
Me Level Emitter darkscreen cursor shows

### ISSUE THREAD

**Issue by Meller127** [AppliedEnergistics/Applied-Energistics-2#2424]
Me Level Emitter darkscreen and cursor shows when placed on a Cable
Rv4 - 1.10
2e2bb12671d363d0e9f5960693e4905d3eabdd59
![2016-10-04_16 04 01](https://cloud.githubusercontent.com/assets/13392710/19077272/3536c722-8a4c-11e6-93f8-a301dd030294.png)

**Comment by shartte** [comment]
Can you provide a screenshot of how this situation differs from 1.7?

**Comment by shartte** [comment]
Oh I see what the issue here is, nevermind. The UI opened when you placed it, but only the modal background.

**Comment by Meller127** [comment]
Cant reproduce this from commit 070b35f3dbd04df6379f4cabbab5ac30a7c604f4  anymore, so we can Close this now i Think.

**Comment by shartte** [comment]
I've fiddled with click handling quite a bit, this might have fixed it.
