### ISSUE TITLE
Certus ore missing lightmap/glow

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#2428]
Both certus ore blocks are missing their lightmap/glow.

Current
![1.10](http://i.imgur.com/kiEGGno.png)

Expected
![1.7.10](http://i.imgur.com/Vdqww02.png)

**Comment by shartte** [comment]
So this is the only case I know about that has an additive light value for the glow. This makes things more complicated, sadly, as our current UVL only supports a fixed brightness value.

**Comment by Meller127** [comment]
@shartte Hows it going? :D
