### ISSUE TITLE
Inscriber missing item rendering and animated presses

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#2429]
* [ ] Inscriber are neither rendering the presses (items) nor the placed currently processed items.
* [ ] The 2 presses are missing (top/bottom inside the inscriber model)
* [ ] The animation of the presses is missing

Expected
![1.7.10](http://i.imgur.com/d2YZyXM.png)

Current
![1.10](http://i.imgur.com/r9i51Br.png)

**Comment by shartte** [comment]
Rendering is not 100% the same in terms of the item sizes, but it uses the normal item renderer now (using the item frame transform).

![](https://i.imgur.com/AzNGug7.jpg)
