### ISSUE TITLE
QNB not forming multiblock

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#2431]
Quantum network bridges are not forming the finished multiblock structure.

As side note, they seem to be formed internally as well as the collision boxes.
Standing on them while it is formed will mess up the hitboxes and cause the player to constantly jitter slightly up and down when standing on the corner blocks, which will be larger as well as fall slightly down on the edges which have a smaller hitbox when formed.
The jitter might be another bug, or just solves itself once the multiblock is correctly formed.

Expected
![1.7.10](http://i.imgur.com/dsiUEPc.png)

Current
![1.10](http://i.imgur.com/ig6Rpdz.png)

**Comment by shartte** [comment]
The jitter comes from being inside the BB when the multiblock is formed while you stand on it.
Once you are off it, and stand on it again, it'll be fine.
