### ISSUE TITLE
IRC Discord Intergration 

### ISSUE THREAD

**Issue by JosephRymer** [AppliedEnergistics/Applied-Energistics-2#2439]
@yueh myself and other like elix are on discord and we are trying to get others to join as well but i understand that you dont feel the need to switch over to discord even though a good portion of the community has. I am making this issue in the hopes that you will agree to go ahead and allow me or someone else or you to do the integration of discord and irc which will allow communication across both of them and wont cause any security risks or issues in names. I will link the DISCORD IRC integration below for the GitHub document if you want to look over it that way you can make a informed decision 
https://github.com/reactiflux/discord-irc

**Comment by shartte** [comment]
> even though a good portion of the community has
I am sorry, but what are you basing that statement on?

**Comment by JosephRymer** [comment]
current members on discord for TeamAppliedEnergistics

**Comment by shartte** [comment]
> current members on discord for TeamAppliedEnergistics

Which would be how many?
The IRC on Esper has over 150 users.

**Comment by JosephRymer** [comment]
well notsure

**Comment by elix-x** [comment]
@shartte currently over 60 users on discord and counting.

Though, number of users does matter, main reason would be providing choice: don't want to use IRC? You can use discord. Don't like discord? You can use IRC.

**Comment by JelmarG** [comment]
I don't think there is even any collaboration between the official repo team and the AEModernMCPort team, so what is the use? Is the AEModernMCPort even necessary any more, really, seeing this repo now has its own 1.10 branch? Have you guys even talked about that, like, at all? Two teams working on the same thing is a bit of a waste of time.

**Comment by JosephRymer** [comment]
@JelmarG yes we have discussed it and are currently working on resolving other conflicts like the one you described.

**Comment by shartte** [comment]
I really don't think this is an open issue with the AE2 team. We're not the ones who have to enable any form of integration.
