### ISSUE TITLE
Sky Factory 2.5 Crashing when loading a world.

### ISSUE THREAD

**Issue by MullerVGS** [AppliedEnergistics/Applied-Energistics-2#2443]
**ModPack:** Sky Factory 2.5

**Version:** 2.5.4
**AE2 Version:** rv3-beta-6

**Launcher:** Curse

**Crash Log:** http://pastebin.com/D1fGWhda

**Details:** I have 4 Quantum Rings, all of them are chunk loaded(With the ChikenChunks, chunk loader, I could change to the Minefactory one).
2 of the Rings are at my base(Overworld)
1 in the Last Millenium
1 in a RFTools world.
This happens when I travel through dimensions, so Nether-End it will crash, even though I dont have a Ring there.

Another problem that I'm having is that I can't type "t" in any terminal, I need to click on the search bar and then type "t". Edit: Solved the "T" Problem

**Comment by Meller127** [comment]
The problem with "T" is that is often bind to search nearby inventories, change that and it will work again

**Comment by thatsIch** [comment]
The crashlog indicates that the quantum rings are getting unloaded. Maybe check if the footprint (3x1) of quantumrings are totally covered.

**Comment by yueh** [comment]
The modpack contains FTB Utilities, which means it will use multithreaded chunkloading/access in singleplayer. Honestly it just asks for random issues or even world corruption and it will not be fixed by the mod author.

**Comment by MullerVGS** [comment]
Ok, so after some testing, i placed down all 3 of the chunk loaders and for some reason only the spot loader worked.
Thanks for the help!
