### ISSUE TITLE
cables show unorganized lines

### ISSUE THREAD

**Issue by abdullamu** [AppliedEnergistics/Applied-Energistics-2#2447]
i was testing ae 2 1.10.2 and found this 
![2016-10-08_18 36 10](https://cloud.githubusercontent.com/assets/10797410/19219696/0e1786ea-8e1b-11e6-9f96-55eac6322214.png)

**Comment by shartte** [comment]
Confirmed, the actual issue seems to be the "stumps" of channels drawn to connected busses.

**Comment by shartte** [comment]
Actually it was the straight lines, but whatever. Fixed!
