### ISSUE TITLE
Server Crash when placing Crafting Co-Processing Unit

### ISSUE THREAD

**Issue by Patti2507** [AppliedEnergistics/Applied-Energistics-2#2449]
I was building my ME System and i tried placing the Unit and fast placed one more, one block away from it and then suddenly the server crashed and I couldnt start it anymore
[crash-2016-10-09_18.49.12-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/518451/crash-2016-10-09_18.49.12-server.txt)

**Comment by shartte** [comment]
You are using a very dated version of AE2. Please upgrade.

**Comment by Patti2507** [comment]
Thank you!

**Comment by shartte** [comment]
In addition: I think your crash might be related to API incompatibility between ExtraUtils2, Buildcraft and AE2.
