### ISSUE TITLE
WAWLA doesn't correctly show number of channels.

### ISSUE THREAD

**Issue by DFliyerz** [AppliedEnergistics/Applied-Energistics-2#2450]
WAWLA always shows the number of channels for Smart and Dense cables as 0 out of 8/32.

**Comment by yueh** [comment]
Waila itself works just fine. 

I do not know what WAWLA does, but either it does break something in Waila or their own data provider simply does not support it. As their own one does not even provide an API, there is no way we can provide data for it.
