### ISSUE TITLE
ModelFromBaseName get´s called on the Server

### ISSUE THREAD

**Issue by DoktorAerzt** [AppliedEnergistics/Applied-Energistics-2#2451]
appeng.items.parts.PartType.modelFromBaseName get´s called on the Server.

Version: 1.10 from Commit 2588

http://pastebin.com/8hwu8PfR

**Comment by DoktorAerzt** [comment]
I found the problem. The problem is farseek but maybe this is also a bug in AE. 

So when i remove Farseek then the server starts and all is working. 

I don´t know if i should close to issue so maybe one of you can close it so i see that it isn´t a bug in AE too.

**Comment by Ommina** [comment]
This rather looks like a return of delvr/Farseek#10

While it is marked as fixed, and you're using the latest version, the same exception occurring with the same mod installed is mighty suspicious.

**Comment by shartte** [comment]
@DoktorAerzt Please try again with Farseek. The method used ModelResourceLocation, which is client-side only. It doesn't crash since it never really gets used anyway, but I guess that's why Farseek borked.

**Comment by DoktorAerzt** [comment]
@shartte Now it works. At least you can start the Server now and you get no crash.
