### ISSUE TITLE
Comparison Method Bug

### ISSUE THREAD

**Issue by SashaGelert** [AppliedEnergistics/Applied-Energistics-2#2452]
Not sure who to blame for this crash, but it's under very specific circumstances.
Forewarning: MC 1.7.10 Forge 10.13.4.1614.  Bit dated, but i like having lots of nicely working mods.

Single Player Worlds: no issues, everything works fine as expected.

Multiplayer Worlds: When in an ME terminal GUI, whether basic or crafting, if the first letter entered in the search box is 'm' or 'u' then the client crashes, in all four search modes (Auto, Standard, NEI Sync Auto, NEI Sync Standard).

Years of Minecraft, im usually decent at reading crash logs, but between NEI and AE2, I can't seem to find out what is causing this, especially as 'm' isn't bound as a hotkey to anything. 'u' is bound to swapping Tinkers Construct Travelers belt, which i've never had issues with before.

Full crash log, if anyone can help pin down the cause of this bug:
http://pastebin.com/s6ncyQH9

**Comment by yueh** [comment]
Inventory tweaks bug.

**Comment by SashaGelert** [comment]
*shakes head* not sure how I skipped over that, thanks!
