### ISSUE TITLE
Request reopen #2452: Comparison Method Bug

### ISSUE THREAD

**Issue by SashaGelert** [AppliedEnergistics/Applied-Energistics-2#2453]
Thanks to Kobata from inventory Tweaks for pointing out further information related to my crash:

The issue, reposted below, only occurs when the ME Terminal is in InvTweaks sort mode, all other modes work fine, which would suggest this is some issue with AE2's integration of Inventory Tweaks? 

Original Bug Report:

Not sure who to blame for this crash, but it's under very specific circumstances.
Forewarning: MC 1.7.10 Forge 10.13.4.1614. Bit dated, but i like having lots of nicely working mods.

Single Player Worlds: no issues, everything works fine as expected.

Multiplayer Worlds: When in an ME terminal GUI, whether basic or crafting, if the first letter entered in the search box is 'm' or 'u' then the client crashes, in all four search modes (Auto, Standard, NEI Sync Auto, NEI Sync Standard).

I can't seem to find out what is causing this, especially as 'm' isn't bound as a hotkey to anything. 'u' is bound to swapping Tinkers Construct Travelers belt, which I've never had issues with before.

Full crash log, if anyone can help pin down the cause of this bug:
http://pastebin.com/s6ncyQH9

**Comment by KamranMackey** [comment]
@SashaGelert Mods work perfectly with the latest version of Forge for 1.7.10. I don't see why you can't update/

**Comment by SashaGelert** [comment]
I *am* using the latest version of forge available for minecraft 1.7.10, as per the download list through the Forge website.  Version 10.13.4.1614.  there is *nothing* newer unless you guys are compiling against some hidden version I'm unaware of.

**Comment by KamranMackey** [comment]
@SashaGelert That was a mistake. I thought there was a newer version of Forge available for 1.7.10 hahaha. But nope.

**Comment by SashaGelert** [comment]
Does this mean the issue may be looked into, or am I stuck with just not using the InvTweaks sorting mode?
