### ISSUE TITLE
Can't open terminal in spectator

### ISSUE THREAD

**Issue by dpeter99** [AppliedEnergistics/Applied-Energistics-2#2456]
![2016-10-11_15 29 30](https://cloud.githubusercontent.com/assets/7725817/19272184/e213381a-8fc7-11e6-9629-068b3254863b.png)
can't click
![2016-10-11_15 29 32](https://cloud.githubusercontent.com/assets/7725817/19272185/e3814aa2-8fc7-11e6-8fe9-23e89c4b9318.png)

**Comment by KamranMackey** [comment]
Last I checked, you can't interact with any items in spectator mode.

**Comment by KamranMackey** [comment]
Taken from the Minecraft wiki:

> Spectator mode is a game mode which allows you to fly around and observe the world without interacting with it in any way.

**Comment by VT-14** [comment]
@KamranMackey I'm pretty certain that Specator players can 'observe' the contents of vanilla chests (don't actually open it, and can't move things in the chest).  I think they even get an error message in chat if the chest is a loot box and the loot hasn't been set by a normal player opening it the first time.

**Comment by mindforger** [comment]
maybe add an option for paranoid admins who chase people in spectator mode to let them view inside the storage even with an installed security system ... read-only naturally :D
