### ISSUE TITLE
Bug? - SlimLine ME interface Cannot extract complete items from Molecular Assembler

### ISSUE THREAD

**Issue by ozhound** [AppliedEnergistics/Applied-Energistics-2#2458]
I'm unsure if this is intended but the ME interface in its slimline form (Crafted from a full block ME Interface) cannot withdraw created items from the Molecular Assembler. 

In order for it to work correctly, I have slimline ME Interfaces surrounding the Assembler with one full sized ME interface. This way the Full sized Interface will extract the completed items once they are assembled. Otherwise the first scheduled item is made and stays in the output slot of the Assembler.

Forge 2102
1.10 Branch
Commit 55d66be

**Comment by yueh** [comment]
#2417
