### ISSUE TITLE
Network Cannot See Items held in ME Interface from Terminal.

### ISSUE THREAD

**Issue by ozhound** [AppliedEnergistics/Applied-Energistics-2#2459]
Forge 2102
1.10 Branch
Commit 55d66be

Placing a crafting card in an ME Interface and putting an item in the top row successfully queues a crafting request with the items appearing in the second row. However, these items are not available to the network via the terminals.

**Comment by yueh** [comment]
Intentional since rv0 and will not be changed.

**Comment by ozhound** [comment]
then whats the point of having crafting cards?

**Comment by mindforger** [comment]
having export busses crafting exported items on demand ?

**Comment by shartte** [comment]
You can attach a storage bus to the Interface to get what you want

**Comment by mindforger** [comment]
please reread my post i edited some more indepth info, you are half right and half wrong

**Comment by ozhound** [comment]
So if i wanted to keep say, 20 crafting tables in stock at all times, in the past i have just done what i described above. Placing the storage bus on to the interface doesnt expose these items to the network, as mineforger said. How would one achieve a "always keep in stock" scenario i mentioned above.

**Comment by mindforger** [comment]
the only 1-block solution I see is using an item conduit from EIO, redstone controlled to move 1 item provided by the interface back to the interface (or another one if that fails) whenever there is a redstone signal (item conduits can feedback to the source, there is an option in the GUI) and the redstone signal is provided by a  level emitter checking the number of items in the system

**Comment by XFactHD** [comment]
If you place a storage bus on an interface set to hold a certain item, the storage bus will show those items to the system, if not, you did something wrong.

**Comment by ozhound** [comment]
thanks for the tips. It seems silly to me that this feature was removed and
now replicating this requires "hacks" to get the same result. im sure that
there was a good reason though. Again, thanks for the advice.

Oz
