### ISSUE TITLE
With FTB looking to release 1.10 packs, we need to port this mod to 1.10

### ISSUE THREAD

**Issue by SadChimera** [AppliedEnergistics/Applied-Energistics-2#2460]
To my understanding, the creator is no longer here and it is up to the community to update it. Is it currently possible to just plug & play this mod into 1.10? If not, what are some of the hurdles necessary to make this mod support the 1.10 version of minecraft?

**Comment by SadChimera** [comment]
Closed, found the port project.

**Comment by shartte** [comment]
Did you find the right one? :P

**Comment by SadChimera** [comment]
Uh, I guess not.. Is there an actual download link for the WorkInProgress build?

**Comment by shartte** [comment]
No, currently you have to build it yourself from source. It's in the 1.10 branch in this repo.

**Comment by SadChimera** [comment]
Ah, found it. Any timeline on a working download?
