### ISSUE TITLE
Storage Bus on empty locked DSU eats items

### ISSUE THREAD

**Issue by swoolcock** [AppliedEnergistics/Applied-Energistics-2#2461]
If you put a Storage Bus (with no whitelist) on an empty MFR Deep Storage Unit that's locked to "nothing", AE2 will happily send items to it as they enter the network, and they vanish into the aether.  I lost 200 plutonium this way.
If the item is autocrafted in a MAC, it seems to be ok.  It's only if you drop the item in through a terminal, or pipe it into an interface.

Running Infinity Evolved 1.7 (Expert Mode) on multiplayer survival.

Edit: Dropping a storage cell into an I/O Port will cause items to disappear too.  It seems I also lost 1300 iridium ore.

**Comment by yueh** [comment]
#2328, etc

**Comment by mindforger** [comment]
never lock DSUs near any AE2 Stuff :) not solveable
