### ISSUE TITLE
Improve ME Interface flow control

### ISSUE THREAD

**Issue by Sorbe** [AppliedEnergistics/Applied-Energistics-2#2462]
The current _ME Interface_ flow control mechanism of "Do not push crafting items if inventory contains items" does not work well with some devices (as an example, _Runic Altar_).  The problem arises when the AE2 _ME Interface_ outputs to items like a _chest_ / _open crate_ / _item grate_.  The crafting items are then pushed into these "containers" AGAIN before the whatever is doing the actual crafting is ready to accept more items.

What might work better is "Do not push more crafting items until crafted item is returned".  Curiously, this seems to be exactly what AE2 does internally when the crafting job is cleared from the _crafting processor_.  It would seem to be trivial add an option to gate pushing more crafting items on the last item being  complete.  Thus you get a classic SEND <=> ACK type of flow control protocol.

Please consider adding another _ME Interface_ option along these lines.

**Comment by yueh** [comment]
Simply not possible due to how flexible players are with their placement of interfaces. Like not enforcing "you have to return it to the same interface".

If you actually want to compare it with a network protocol, UDP is the right one. Just fire and forget.

**Comment by Sorbe** [comment]
Can't the crafting processor make the call, already?  It's the one that already has to clear out the completed job based on getting back the item, right?
