### ISSUE TITLE
Glass cable connection point

### ISSUE THREAD

**Issue by Meller127** [AppliedEnergistics/Applied-Energistics-2#2467]
Expected behavior: 1.7.10
![2016-10-15_16 58 21](https://cloud.githubusercontent.com/assets/13392710/19410990/eebeb038-92f8-11e6-9fc3-296d7e169231.png)

Rv4 - 1.10 4102f7b8f5b0835b7ff11d9e3db408503a4afc7e
![2016-10-15_16 57 06](https://cloud.githubusercontent.com/assets/13392710/19411000/326b6786-92f9-11e6-887b-59d1ed3a7325.png)

Only happens if you go in a straight line from the block

**Comment by shartte** [comment]
Thanks for the bugreport / screenshots. I will look into it. I've noticed the same with dense cables actually, but wasn't sure whether it was like that in 1.7

**Comment by Meller127** [comment]
Yes dense Cables act weird to.
![Uploading 2016-10-16_18.43.24.png…]()

**Comment by shartte** [comment]
This should now be fixed.
