### ISSUE TITLE
AE2 Facades in latest 1.10 build cause a crash in JEI

### ISSUE THREAD

**Issue by KamranMackey** [AppliedEnergistics/Applied-Energistics-2#2468]
When trying to load a specific page with AE2 facades in JEI (with my setup and everything, its page 6), Minecraft stops responding, and then crashes. It seems as if when AE2 is trying to load the facades in JEI, the facade renderer struggles to load them, which causes the crash. 

A link to the crash report is below.

Crash Report: https://paste.ee/p/oeeEC

**Comment by shartte** [comment]
This bug should be fixed in the latest revision. Please delete your Facades.cfg and try with the latest version.

**Comment by KamranMackey** [comment]
Alright, I'll try that, and then respond back.

**Comment by yueh** [comment]
#2465

**Comment by KamranMackey** [comment]
@yueh I need to learn to search these things. :D Thanks though, and thanks @shartte :)
