### ISSUE TITLE
[1.10]Network tool dont show network details

### ISSUE THREAD

**Issue by Meller127** [AppliedEnergistics/Applied-Energistics-2#2471]
Expected 1.7.10
![2016-10-16_18 28 00](https://cloud.githubusercontent.com/assets/13392710/19418928/4f889458-93ce-11e6-901a-c6a0225f6ca4.png)

Rv 4 - 1.10 build 4102f7b8f5b0835b7ff11d9e3db408503a4afc7e
Nothing happens when right clicking ME controller with the network tool.

**Comment by KamranMackey** [comment]
Probably because it isn't implemented yet I'm afraid.

**Comment by Meller127** [comment]
Aa okay, dident find any report on the issue

**Comment by shartte** [comment]
It's a bug.

**Comment by ozhound** [comment]
This works for me. although it doesn't make the facades transparent like it
did in 1.7.10 (it did this i think right?)

**Comment by GuntherDW** [comment]
It is bugged at the moment @ozhound, but it's only from a fairly recent commit, because my previous build from ~2days ago didn't have this issue.

**Comment by shartte** [comment]
@ozhound It does the transparency for me. Can you elaborate (and maybe make a new issue for it). You still have to activate the mode in the network tool UI (shift+click into the air).
