### ISSUE TITLE
[1.10] 5th channel on smart cables dont render

### ISSUE THREAD

**Issue by Meller127** [AppliedEnergistics/Applied-Energistics-2#2472]
Five terminals only renders 4 channels, terminal 1 to 4 renders correctly
![2016-10-16_18 46 19](https://cloud.githubusercontent.com/assets/13392710/19419134/ea7d7fbc-93d0-11e6-8cb5-6cf5bc66b729.png)

Eight terminals render 7 channels
![2016-10-16_18 47 44](https://cloud.githubusercontent.com/assets/13392710/19419144/15294188-93d1-11e6-9d17-3bf0cda9f417.png)

Rv4 - 1.10 build 4102f7b8f5b0835b7ff11d9e3db408503a4afc7e

**Comment by mixilester** [comment]
Well, all right 5 the terminal interface is 5 channels on cable and shows 5 out of 8.
And with 8 terminal interfaces too, all 8 of them right there on the cable is written, and it is occupied 8 of 8. maybe I could understand what is wrong sorry I am from Russia.

**Comment by bookerthegeek** [comment]
Render. As in it actually visually is not correct on the cable

**Comment by mixilester** [comment]
why not right? if it cost them 5 it says 5 of 5, and if is 8 and says 8 of 8.

**Comment by bookerthegeek** [comment]
Stop looking at waila and look at the cable.

**Comment by mixilester** [comment]
and everyone can see (I apologize just I am from Russia and English is a little crooked translated.

**Comment by yueh** [comment]
These are the cases in which I would actually consider removing WAILA support completely. Once a mod turns minecraft into "Look at a random text panel for everything", it clearly adds nothing worthwhile anymore.

But back to the original bug, seems like there is an off by one error when selecting the texture for > 4 channels.

**Comment by mixilester** [comment]
give a normal response in which file to go, and what is there to change this was not.

**Comment by shartte** [comment]
That is an oddly specific bug hrrr. I'll look at it.

**Comment by shartte** [comment]
Fixed
