### ISSUE TITLE
Still getting Extra Utils 2 Crashes

### ISSUE THREAD

**Issue by DFliyerz** [AppliedEnergistics/Applied-Energistics-2#2473]
https://gist.github.com/DFliyerz/18576ffea319e3b18e92766c1e3e10ba

**Comment by yueh** [comment]
Still an XU2 bug.

**Comment by KamranMackey** [comment]
Delete your Facades.cfg. That fixes the issue.

**Comment by KamranMackey** [comment]
@DFliyerz Delete your Facades.cfg configuration file. That fixed the issue.
