### ISSUE TITLE
Здравствуйте я наверное 1 русский помогите с мэ терминалом интерфейсов

### ISSUE THREAD

**Issue by mixilester** [AppliedEnergistics/Applied-Energistics-2#2474]
Версия appliedenergistics2-rv2
не показывает в мэ терминале интерфейсов, интерфейсы которые подключены к мэ.
показывает только 1 интерфейс и каждый раз разный. если мне нужно писать темы на английском прошу сообщить мне об этом буду использовать гугл переводчик.
![2](https://cloud.githubusercontent.com/assets/22871683/19419184/d033b1a8-93da-11e6-8e56-0dbb0d54d6cd.png)
![3](https://cloud.githubusercontent.com/assets/22871683/19419185/d034554a-93da-11e6-91d4-c587423903d2.png)
![4](https://cloud.githubusercontent.com/assets/22871683/19419186/d036a1e2-93da-11e6-9e99-121bf88711bd.png)

**Comment by yueh** [comment]
Sorry, but we can only provide support in english.

**Comment by mixilester** [comment]
Hello, I really hope that you understand me, we had a bug with the te terminal interfaces, it only sees 1 a certain kind of block in my case it is the molecular assembler, version appliedenergistics2-rv2.
