### ISSUE TITLE
Hello, help me with terminal interfaces does not see the other interfaces but rather only sees 1 of them all.

### ISSUE THREAD

**Issue by mixilester** [AppliedEnergistics/Applied-Energistics-2#2475]
Hello, I really hope that you understand me, we had a bug with the te terminal interfaces, it only sees 1 a certain kind of block in my case it is the molecular assembler, version appliedenergistics2-rv2.
![2](https://cloud.githubusercontent.com/assets/22871683/19419184/d033b1a8-93da-11e6-8e56-0dbb0d54d6cd.png)
![3](https://cloud.githubusercontent.com/assets/22871683/19419185/d034554a-93da-11e6-91d4-c587423903d2.png)
![4](https://cloud.githubusercontent.com/assets/22871683/19419186/d036a1e2-93da-11e6-9e99-121bf88711bd.png)

**Comment by yueh** [comment]
Most likely the interfaces are not on the same network or are missing a channel. The other option would be that some explicitly configured them to not appear on the terminal.

**Comment by mixilester** [comment]
channels enough, you could give the source code and say where to paste it to the terminal I began to see the other interfaces, if not will be told what to do will remove the video. waiting for an answer

**Comment by mixilester** [comment]
channels enough, you could give the source code and say where to paste it to the terminal I began to see the other interfaces, if not will be told what to do will remove the video. waiting for an answer
