### ISSUE TITLE
Recipes of the form (X => 2X) cannot be executed

### ISSUE THREAD

**Issue by Sorbe** [AppliedEnergistics/Applied-Energistics-2#2476]
The crafting processor cannot handle recipes that double or triple items.
While you can create the recipe and request the operation, it won't start.

Example:
Grass => 2x Grass  (Botania)
Lead Nugget => 3x Lead Nugget (Thaumcraft)

**Comment by shartte** [comment]
Please provide version information along with your report.

**Comment by yueh** [comment]
#439
