### ISSUE TITLE
[1.10.2] Immersive Engineering Wirecutters cant be pulled from crafting grid

### ISSUE THREAD

**Issue by Morpheus1101** [AppliedEnergistics/Applied-Energistics-2#2477]
When making the wirecutters form immersive engineering,  the recipe forms an shows the cutters, however when trying to pull them out of the crafting grid it wont allow it.  Using a normal crafting grid or the 2x2 def grid on the char works fine.

**Comment by yueh** [comment]
IE Bug. It even crashes the vanilla crafting table.

AE2 is just a bit more defensive and prevents crashing with it being not craftable.

**Comment by mindforger** [comment]
it is beeing worked on already
