### ISSUE TITLE
[1.10.2] Conversion Monitor not functioning correctly?

### ISSUE THREAD

**Issue by 5stang** [AppliedEnergistics/Applied-Energistics-2#2478]
From the wiki:
> When unlocked, it will display any item it's right-clicked with. Shift-right-clicking attempts to insert the item into the network. Shift-double-right-clicking attempts to insert all items of the type displayed into the network. If the monitor is locked, right-clicking attempts to pull out a stack of the item displayed.

Shift-right-clicking an unlocked monitor (which is already configured to receive the item) with the item selected in the hotbar will deposit the stack **and also clear the monitor setting**.  Doing so without the item selected in the hotbar deposits the item but does not clear the screen.  

Shift-right-clicking on a locked terminal will only deposit items if they are not selected in your hotbar.

I likely haven't explained this correctly, but the gist of it is that there is definitely a discrepancy from the 1.7.10 behaviour.

**Comment by shartte** [comment]
Hi 5stang, can you please provide the exact version of AE2 you tested this with?
If possible, can you also retest this since I've fixed a different issue that also related to right-clicking with items.

**Comment by 5stang** [comment]
The jar file I was using was appliedenergistics2-rv4-nightly-c427fa.jar dated Oct16.

I'll give it a try with the latest build and let you know.

**Comment by 5stang** [comment]
Seems to functioning properly now with appliedenergistics2-rv4-nightly-41b875.jar today's build.

**Comment by shartte** [comment]
Thanks!
