### ISSUE TITLE
[1.10.2] Crash when scrolling AE creative tab.

### ISSUE THREAD

**Issue by mrAppleXZ** [AppliedEnergistics/Applied-Energistics-2#2480]
Forge version: 12.18.2.2107.
AE2 version: rv4-nightly.
Crash-report: http://pastebin.com/7VA9sqsh.
latest.log: http://pastebin.com/H7xhM1E3 
fml-client-latest.log: https://paste.ee/p/8qcSP

**Comment by yueh** [comment]
We currently do not support Optifine.

I cannot even guess, if we ever will be able. It completely changes minecrafts rendering behaviour, but does not document anything. So it really comes down to trial and error to find any issues.

Especially once a mod uses smart models heavily as we have to use for parts, it gets really messy and you have to pretty much disable all of your own performance features or even provide a fallback renderer just for Optifine.

Thus we simply might not have to time currently try to get it to work as there are still more important things. But if someone could provide more insight about how optifine changes the rendering and could also provide help to get it working, we would highly appreciate it.

**Comment by mindforger** [comment]
@yueh if you wish i can search for the issue about this topic 

you can include a deobfuscated version of OF in your dev env to debug such things
but you'll have to deof it via a tool by yourself first, sounded quiet easy but you'll not get into the inner parts of it but you can actually debug with it

**Comment by yueh** [comment]
Which still comes down to reverse engineering optifine and then trial&error to fix it. Which we already have to do with forge to some degree.

So if the author really wants it to be more supported by mods, he should really take the time and write some documentation for it. Like some best practices or which feature he cut for whatever performance reason etc.

**Comment by mindforger** [comment]
yeah I already figured and told him, but i wanted to note and let you know just in case :)

**Comment by mindforger** [comment]
https://github.com/octarine-noise/simpledeobf/blob/master/README.md#have-optifine-will-debug

FYI
