### ISSUE TITLE
Cable anchors are invisible

### ISSUE THREAD

**Issue by GuntherDW** [AppliedEnergistics/Applied-Energistics-2#2481]
Cable anchors have a bit of a rendering issue.

You can place them, it will work as expected, it'll show a bounding box, cables don't connect.
However the anchor itself will not be rendered.
![image](https://i.imgur.com/vBZYtcV.png)

Also, crafting said anchors bugs out the cutting knife and if you try to pull it out after you've crafted some it will delete the cutting knife. It decreases the ItemStack value where it shouldn't.
It does however let you use it up completely if you don't pull it out.
![image](http://i.imgur.com/Vyhq4YH.png)

This is on a ~100 mods kitchen sink however so I'll test if it happens in a pack with just forge/AE/JEI.
EDIT: Tested it out in a pack with just JEI/AE/Forge and the issue occurs here as well.

Version info :

Forge : 1.10.2-12.18.2.2099-universal
AE2 git commit : dacce3e7bdd645a75a2b699125d8ed105f557a5e

**Comment by ozhound** [comment]
im not sure about the cutting knife issue but i can confirm the non-render
issue

**Comment by yueh** [comment]
Missing model probably.

@shartte Just in case anchors also make a cable act as ladder. Currently works, but just in case it appears as weird behaviour.

**Comment by mindforger** [comment]
https://github.com/octarine-noise/simpledeobf/blob/master/README.md#have-optifine-will-debug

FYI :)

**Comment by GuntherDW** [comment]
I don't have OF in my packs @mindforger ?

**Comment by mindforger** [comment]
yeah sorry I removed the comment at the moment I realized i had posted to the wrong issue :P

**Comment by shartte** [comment]
what the hell, i constantly learn about new things :|
like placing cable anchors without a cable, or making cables work like a ladder

**Comment by yueh** [comment]
@shartte Just to clearify it in case. Anchors are just another parts and every part can be placed without a cable being present. Except facades are no parts, so they actually need a cable to be present.

**Comment by shartte** [comment]
Fixed it, just forgot to specify the model for the part.
