### ISSUE TITLE
CRASH WITH OPTIFINE

### ISSUE THREAD

**Issue by SrSlimShady** [AppliedEnergistics/Applied-Energistics-2#2485]
WHEN CLICK ON THE CREATIVE ABA AE, IT CLOSES ALONE.
http://prntscr.com/cvd89z

OptiFine_1.10.2_HD_U_C3
appliedenergistics2-rv4-nightly-41b875

PS. SORRY MY ENGLISH, I am USING GOOGLE TRANSLATOR.

[crash-2016-10-17_10.29.48-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/533434/crash-2016-10-17_10.29.48-client.txt)

**Comment by shartte** [comment]
Optifine is currently not supported.
