### ISSUE TITLE
[1.10.2] AE2 fails to start on SMP with latest Forge

### ISSUE THREAD

**Issue by b0bst3r** [AppliedEnergistics/Applied-Energistics-2#2487]
http://pastebin.ubuntu.com/23341182/

Forge 12.18.2.2106
Applied Energistics 2 rv4-nightly-dacce3

**Comment by yueh** [comment]
#2451

**Comment by shartte** [comment]
@b0bst3r It should be fixed. This issue was due to Farseek removing a method from AE2 via a coremod, which is (in my eyes) a big fat nono.

**Comment by b0bst3r** [comment]
I actually didn't need farseek since I had it in when I put the pack together for streams which I removed because of world gen anomolies I was experiencing at the time.  I will however put it back and test for you.
