### ISSUE TITLE
[1.10.2] Energy Acceptor compatibility

### ISSUE THREAD

**Issue by b0bst3r** [AppliedEnergistics/Applied-Energistics-2#2488]
So far I've tried 

 - EnderIO Energy Conduits
 - Immersive Engineering LV connectors and wire
 - Mekanism Energy cable
 - Flux Ducts
 - RFTools Powercells (adjacent to)
 - EnderIO Capacitor banks (adjacent to)
 - Mekanism Energy Cells  (adjacent to)
 - Actually Additions wireless laser transfer

Sure there was some others too, nothing connects and nothing passes energy to the acceptor or to the controller.

appliedenergistics2-rv4-nightly-41b875
forge 1.10.2-12.18.2.2106

**Comment by yueh** [comment]
#2438
