### ISSUE TITLE
[1.10.2] Optifine almost there

### ISSUE THREAD

**Issue by ozhound** [AppliedEnergistics/Applied-Energistics-2#2489]
I know that you have stated that optifine is not supported but the latest version released on the 17th October (OptiFine_1.10.2_HD_U_D1) works pretty well. Many of our players need to use optifine to run the All the Mods modpack as it has 150+ mods and whilst AE is not included in the pack yet, it will be once we feel that it is ready (and we get your permission of course) then we can remove Refined Storage and Correlated Potentialistics.

Anyway as it stands there are only some rendering issues with certain parts of the textures. Images below, feel free to close this, it was more of a FYI, and a heads up about Optifine if you weren't already aware.

Oz
![image](https://cloud.githubusercontent.com/assets/3649237/19477629/af77a9fe-9571-11e6-895c-e3cc3d98e790.png)
![image](https://cloud.githubusercontent.com/assets/3649237/19477636/b65acb70-9571-11e6-82ae-8fdaff78526f.png)
![image](https://cloud.githubusercontent.com/assets/3649237/19477645/bc74a8be-9571-11e6-8c3a-17dc7746ceb0.png)
![image](https://cloud.githubusercontent.com/assets/3649237/19477649/c1fd455c-9571-11e6-8521-760484079237.png)
![image](https://cloud.githubusercontent.com/assets/3649237/19477662/cfdee720-9571-11e6-8d9c-b2ee708c9b25.png)

Edit: RFtools also has an issue 

![image](https://cloud.githubusercontent.com/assets/3649237/19479095/ca1c05ec-9577-11e6-9e42-c7ff9629752a.png)

**Comment by mindforger** [comment]
did you report this also to optifine in any way ?

**Comment by yueh** [comment]
We usually do not support Optifine.

But just looking at the missing parts, it is clearly missing our custom uv lightmap rendering, because that is not supported by vanilla itself. Not sure, if we can really fix it. At least not without some insight about what optifine changes within the vanilla rendering.

Also regarding the permission. There is non for AE. If in doubt, just look at our [FAQ](http://ae-mod.info/Frequently-Asked-Questions/). To be honest I personally would never ever consider adding any mod to modpack, if requires some permission. Because essentially the author states that they do not wish anyone to play with there mod. So why even bother making it.

**Comment by ozhound** [comment]
Thanks yueh,

ill submit this to optifine and see what they say. Interestingly, the RFTools teleporters also do not render the blue and yellow circles with optifine either.

![image](https://cloud.githubusercontent.com/assets/3649237/19478873/c290e4e2-9576-11e6-81f1-50f58e410057.png)

**Comment by yueh** [comment]
Not sure if that is related. But with the animation it looks like RFTools uses a similar system like we. Just that theirs merges a normal texture and a animated one, while we merge a normal texture with a custom lightmap one. So only the panels glow and not the full block including the border.

**Comment by shartte** [comment]
So I changed the way we create the fullbright quads, and made the switch to one of the default vertex formats. But I'd be somewhat careful with the effect. I tested it quickly with Optifine, and at the very least the faces now show up, although the fullbright effect at night is gone.
This change needs some testing, but at a quick glance still seemed to work for me without Optifine.

**Comment by ozhound** [comment]
@shartte I have just got around to testing this with 5b4c3c and the terminals and me controller are working now (albeit the controller is static and doesn't cycle through the colours anymore) but there are still weird issues. I havent heard at all from the Optifine Dev so either he is ignoring it or just hasnt looked into it yet.
![image](https://cloud.githubusercontent.com/assets/3649237/19591318/fdfd64ea-97a8-11e6-8fb5-6cdfe5734677.png)
![image](https://cloud.githubusercontent.com/assets/3649237/19591321/036e5024-97a9-11e6-9c16-4500eb3de1b6.png)
![image](https://cloud.githubusercontent.com/assets/3649237/19591325/089ac5d2-97a9-11e6-9b3c-bbea0f8e30d2.png)
![image](https://cloud.githubusercontent.com/assets/3649237/19591331/1528c5ec-97a9-11e6-948e-42b69a8e97da.png)
![image](https://cloud.githubusercontent.com/assets/3649237/19591339/1b044d10-97a9-11e6-8084-46bdac800277.png)

**Comment by shartte** [comment]
@ozhound Hm, it didn't quite look that irritating when I tested it, actually. so I wonder what settings are different for you. The controller did animate for me as well, it just didnt glow at night.

**Comment by mindforger** [comment]
those screens are definately 1 preview version of optifine behind
the custom uv maps have been fixed but what is this thing with the warped textures that look like cables?!

**Comment by shartte** [comment]
I forgot a second spot where we do the UV Maps using a custom vertex format... testing a fix right now

**Comment by shartte** [comment]
@ozhound Can you try the latest nightly (4b607d8f) and see if it fixes the corrupted vertices for you? I tried it locally and it looks better. Still, no "glow at night" for Optifine users, but at least the rest should look functional.

**Comment by shartte** [comment]
And just a bit of ranting: It's *very* annoying that Optifine doesn't work in my dev environment, and that Optifine doesn't provide Dev builds. Actually testing this shit is horrible without having the ability to debg into it :(

**Comment by mindforger** [comment]
you can deobfuscate it to get it running in dev env
https://github.com/octarine-noise/simpledeobf

**Comment by yueh** [comment]
Still having to build that stuff by yourself is annoying. Also Optifines disables a good portion of the Forge rendering pipeline, especially the part we depend on.

**Comment by shartte** [comment]
Ah, Github ate my reply heh. 
Yeah, consider that Optifine is one of the mods most prone to Mod incompatibilities. So providing an easy way for devs to actually test against it would be beneficial to Optifine the most.
And regarding that "tutorial": I still have to include a custom ASM Tweaker in my code to make it work, and the command-line it presents doesn't work with the latest release of that deobf tool. So... no dice.

**Comment by mindforger** [comment]
oh how unfortunate, this project was linked by the @sp614x to include his code into dev env

maybe @sp614x can shade a bit more light on this :)

**Comment by sp614x** [comment]
OptiFine is not built on the Forge platform, it is only compatible with the obfuscated Forge classes.
It uses MCP class mappings which are most probably not identical to the Forge's mappings, so a DEV OptiFine build is not going to work in a DEV Forge environment.
The only solution so far is to deobfuscated the OptiFine classes with the Forge mappings which should produce a Forge compatible version (as shown above).

**Comment by shartte** [comment]
@sp614x Thanks for the clarification. Minecraft modding is still a mess :|

It's unfortunate that Optifine is closed source and Forge hasn't adopted a more active approach to improving the broken mess that is Minecraft rendering. I personally have played a lot with Optifine in the past, and greatly enjoyed it, but the mod incompatibilities often stand in the way.
I tried the solution mentioned above for generating the mappings, but the latest release on that repo doesnt support the command line options in the example.

**Comment by ozhound** [comment]
Gentlemen, it all looks really good now.

![image](https://cloud.githubusercontent.com/assets/3649237/19619525/3160ff60-989c-11e6-9442-69c546005464.png)
![image](https://cloud.githubusercontent.com/assets/3649237/19619527/372ab77e-989c-11e6-9ed2-3e62af6a4b9a.png)
![image](https://cloud.githubusercontent.com/assets/3649237/19619529/3c3665ce-989c-11e6-91bd-b61c7b8c6561.png)
![image](https://cloud.githubusercontent.com/assets/3649237/19619532/42b1f22e-989c-11e6-9e1f-78bd7f8d6fd0.png)

I think we can close this off.

Thanks for your persistence.

Oz

**Comment by shartte** [comment]
@sp614x Is there a way to set the lightmap coordinates in a quad in such a way that Optifine would respect it during building a rendering-chunk? To fix the obvious corruptions I've removed those hacks, but having that functionality restored for Optifine users would be great.

**Comment by joshricker** [comment]
This isn't related to this issue as it seems to be fixed now, but that black outline of carts in all your screen shots @ozhound what is that? I have it in a 1.10 pack I'm making and don't know what causing it.

**Comment by sp614x** [comment]
The lightmap coordinates are calculated based on the current lighting model (flat, smooth, ao level, etc) and the light levels of the surrounding blocks. The block model can not force the lightmap coordinates.
The classic way for "fullbright" models is to make the block emit light. Then it will have the correct lightmap coordinates AND the blocks around it will also be lit, which looks natural. Otherwise having one bright model in a pitch-black room can look very strange.

**Comment by sp614x** [comment]
Is there a download link for AE2 1.10.2?

**Comment by mindforger** [comment]
>can look very strange

that is the desired effect, having only parts of the pixels glow not the whole texture
like having only those 2 pixels of the diskdrives glowing that indicate the status of the drives

**Comment by sp614x** [comment]
The lightmap coordinates in the vertex data are 0,0 by default. 
The BlockModelRenderer can be extended to check if the lightmap coords in the vertex data are non-zero and use them instead of the calculated ones.
This may or may not conflict with some other mods.

**Comment by shartte** [comment]
Download for nightlies (1.10) can be found here: https://github.com/AppliedEnergistics/Applied-Energistics-2#nightly-builds

Yeah, I am unsure about a good way to proceed for this. It's almost a miracle that our intial approach worked at all in Forge. I might go ahead and see if they are receptive to a patch that provides an actual extension point for this. 

Do you think making that check conditional on VertexFormat=BLOCK would make sense? If I am not mistaken, MC bakes all models for VertexFormat=ITEM, then copies their vertexData, which happens to be the same size, and overwrites the space that was previously used by the 3 byte vertex normal with the lightmap coordinates. We are already "faking" it by baking our fullbright quads with vertex format BLOCK, which for some unknown reason, at least causes it to partially work in Forge.

**Comment by sp614x** [comment]
The "fullbright" effect looks strange to me: http://i.imgur.com/fIo1acE.png
I would expect the block to illuminate at least 2-3 blocks around it. About half of the side pixels are lit, so it should emit light at about 50%.

**Comment by shartte** [comment]
I agree this could be true for the controller.
But in case of the disk drives and terminals, I think the desired effect is more like this: https://blogdotinsanegenius.files.wordpress.com/2014/10/night.jpg

**Comment by mindforger** [comment]
^^^^
exactly what i meant :)

**Comment by sp614x** [comment]
Created a test version which checks if the lightmap coordinates are set in the vertex data. Seems to work in vanilla, but not with Forge. Most probably Forge is using non-zero lightmap coordinates as default.

**Comment by RainWarrior** [comment]
Forge explicitly [supports](https://github.com/MinecraftForge/MinecraftForge/commit/f0ae51bb346c8c8dacac6d9e48f97f68708798cb) passing lightmap data as a part of the model, it's not a miracle, it's the intended way. 
With vanilla, all models are baked into the same format - BLOCK, which isn't good enough if you want to have correct lighting for things that are not axis-aligned; with forge, the format is abitrary, and stored in the BakedQuad, with ITEM being the default one used - since it has the normal data, and there's no need for the lightmap data until the actual lighting is applied. If mods need to pass that data, they can use a format with both a normal and a lightmap spot - which is what you did initially.
I suspect that Optifine relies on quads always being either in BLOCK or ITEM formats, or at least on having them the length 24, which is not true in forge anymore. Though it's easily checkable.

**Comment by sp614x** [comment]
OptiFine currently disables the Forge lighting pipeline as it breaks way too many OptiFine features. 
I tried to work around the lighting pipeline, but there are many problems. Some Forge changes are needed to make this possible: https://github.com/MinecraftForge/MinecraftForge/issues/3091. 

A fixed vertex format is only required when shaders are enabled. The shaders use extended vertex formats derived from the default ITEM and BLOCK formats. The default formats are updated and BakedQuad automatically translates the vertex data so that it matches the extended formats. This only works for ITEM and BLOCK formats. Any custom formats will not work with shaders.

**Comment by shartte** [comment]
Yeah I will take another look at this. For Forge without Optifine, I will go back to our initial way of doing things (having normal + lightmap data). 
@sp614x Does Optifine have any form of API where we could expose custom vertex formats and/or tell it to reuse the lightmap data for just those formats? I'll also try the previous approach with custom vertex formats with Optifine without shaders, but in that case the quads were just invisible previously.

**Comment by ItzKdoge20YT** [comment]
i'm having issue with energy acceptor
can't connect IC2 Cable or directly to acceptor or controller it won't power the controller
i'm on 1.10.2 rv4 alpha 1 AE2 and latest version of forge and JEI also optifine HD D1
my issue :
#2539

**Comment by mindforger** [comment]
@ItzKdoge20YT I am quiet sure your post went into the wrong topic did it ?

**Comment by ItzKdoge20YT** [comment]
i fixed it but ran to another problems but it already closed by AE2 member it say "duplicate"
this time alpha2 rv4 only RF issue it can't power this
#2541

**Comment by mindforger** [comment]
this topic is about optifine behaviour nothing to do wwith power, when you acknowledge to this i will remove this misleading posts asap

**Comment by ItzKdoge20YT** [comment]
who deleted my comment?
