### ISSUE TITLE
Quantum Rings are limited to 32 channels

### ISSUE THREAD

**Issue by Sorbe** [AppliedEnergistics/Applied-Energistics-2#2491]
Despite having 12 connection points on each end, _Quantum Rings_ cannot transmit more than 1 _dense cable_ (32) worth of channels.

Specific scenario -- connect multiple _dense cables_ on each end of the _Quantum Ring_ ... total channels is still limited to just 32.

**Comment by mindforger** [comment]
aren't 512 Channels total enough for an "remote location" ?
And how will you distinguish which of the cables on both ends are paired?

**Comment by Sorbe** [comment]
You don't understand... it's apparently 32 _total_ channels through a Quantum Ring.

**Comment by DoktorAerzt** [comment]
Or 992 Channels when you use P2P. So you have 32 * 32 - 32 Channels

**Comment by shartte** [comment]
I believe this is by design. The "virtual" network node that actually bridges the two networks can carry 32 channels. There's just one per QNB, not one per connection point.

**Comment by Sorbe** [comment]
Or... there is Refined Storage... in most of the 1.10.2 based modpacks.    It doesn't even have channels. :)

**Comment by mindforger** [comment]
>Or 992 Channels when you use P2P. So you have 32 * 32 - 32 Channels

it is 32x16 as each pair of p2p needs 2 channels and i don't know why you substract 32 from it.

@Sorbe 32 channel means you can tunnel 16 pairs of P2P ME which seems enough for me for a remote location!

**Comment by yueh** [comment]
It is still up to 1024 channels per QNB. But depending on the choosen balance between less or more effort the actual amount max might vary between values like 32, 128, 512 or 1024. So putting some thoughts into it will certainly reward more compared to a quick solution.

@Sorbe currently yes. But for whatever reasons some are already thinking/planning to removing it after AE2 is released as stable version. So you might be surprised by it. And we really have no influence over it.

**Comment by VT-14** [comment]
@mindforger Dense cable with 32 in P2P channels -> ME Controller (for P2P sub-net) -> QNB -> 32 out P2P channels.  32x32 = 1024

I've personally haven't used more than about 5 channels through QNBs.  I don't use them that often, assumed P2P wouldn't pass through them, and haven't really had a need for very many channels far away from my base.

@Sorbe in 1.7.10, you could set a config to disable channels.  I assume that will remain/return in 1.10+.

**Comment by mindforger** [comment]
@VT-14 disabling channels makes crafting of QNB impossible witthout modifying recipes

each attached P2P requires a chjannel and you require 1 tunnel end on one side and one tunnelk end on the other side, this results in 16 connected p2p tunnel not 32

**Comment by Meller127** [comment]
Tunnels are 1 input to N outputs. This means you can output to as many points as you want, but only input at a single point per tunnel.
