### ISSUE TITLE
Terminals face the opposite direction when placed on a Dense Cable

### ISSUE THREAD

**Issue by Scoaex** [AppliedEnergistics/Applied-Energistics-2#2492]
When placing a ME Terminal on a Dense Cable it faces the opposite Direction.
(Happening with all Terminals + formation/annihilation plane)
Working fine on normal smart cables

version ec4bc8626668bd65f5f4a1b8b69d2ce53edd388e

![2016-10-20_10 58 10](https://cloud.githubusercontent.com/assets/22586741/19553489/c028e6e8-96b4-11e6-8a12-cc8944e4158c.png)

**Comment by yueh** [comment]
That was always the case.
