### ISSUE TITLE
Minecraft crashing

### ISSUE THREAD

**Issue by mc-gamer-16** [AppliedEnergistics/Applied-Energistics-2#2493]
When I try to start my minecraft it crashes when it gets to postInitilization and it says something in the console about ae2. Is it ae2 causing the crashing?

**Comment by mindforger** [comment]
you can go to pastebin.com and upload the crashlog there, it would help to understand your problem much much better, also state which AE2 Version you are using and which Forge Version, a list of additional mods would be appriciated, but it is mostly isnide the crashlog (which you find in your gamefolde under the crash-logs folder)

**Comment by shartte** [comment]
Yes, please provide a crash-log

**Comment by mc-gamer-16** [comment]
this is a multimc crash report but here:
http://paste.ee/p/IeqFF

**Comment by shartte** [comment]
Your issue seems to be unrelated to AE2. 

> java.lang.IllegalArgumentException: Duplicate id: archiHelm

You may have two versions of Archimedes Ships installed at the same time.
