### ISSUE TITLE
1.10 Energy Acceptor not accepting energy

### ISSUE THREAD

**Issue by KingZero** [AppliedEnergistics/Applied-Energistics-2#2494]
I ahve tried with Multiple mods and the last one i tried was Mekanism. Nothing seems to be giving power to the block at all for any usage

![2016-10-21_14 20 23](https://cloud.githubusercontent.com/assets/13442728/19612099/a7aeebae-9799-11e6-8c9c-d293f84f4bcb.png)
![2016-10-21_14 20 29](https://cloud.githubusercontent.com/assets/13442728/19612098/a7ae0f22-9799-11e6-81b6-faf04ea514ad.png)

**Comment by shartte** [comment]
Hello, please provide the exact version of AE2 you are using.

**Comment by KingZero** [comment]
Rv4 Nightly Build 87cebc

**Comment by shartte** [comment]
@KingZero Do you have the Tesla API in your mods folder? If it isn't present, this mod interaction might not work. (I think that Mekanism supports Tesla, but I might be wrong about that). Other than Tesla, we support Forge energy, which is supported by the latest version of EnderIO.

Can you verify and comment on this again?

**Comment by KingZero** [comment]
I do not have Tesla I will try adding that and if not i will see if enderIO works

**Comment by p455w0rd** [comment]
EnderIO also supports Tesla :)

**Comment by shartte** [comment]
Yes, but the latest EnderIO also supports Forge Energy, which we also support. So it should work even without Tesla (at least the latest version of EnderIO should).

**Comment by p455w0rd** [comment]
oh i see what you were saying, sry bout that

**Comment by KingZero** [comment]
So the block now connects but still does not recieve power I am relaunching right now to test with EnderIO

![2016-10-21_14 58 02](https://cloud.githubusercontent.com/assets/13442728/19613037/f0c4b5e4-979e-11e6-886a-1574e57e4a69.png)
![2016-10-21_14 58 25](https://cloud.githubusercontent.com/assets/13442728/19613036/f0c453ba-979e-11e6-8600-473002714ea4.png)

**Comment by p455w0rd** [comment]
afiak Mek is still quite buggy and last commit on the repo was Sept 7th, so bugfixes in the near future son't seem likely

**Comment by KingZero** [comment]
EnderIO does work and use the Mekanism creative block and it seems that it maybe the pipes are not giving power to the energy acceptor so i think it is most likely a bug on Mekanism's part

**Comment by p455w0rd** [comment]
yeh Meka pipes have been borked for a while now with other mods..good to see it's working for you :)

**Comment by shartte** [comment]
Allrighty, Closing this issue then. Keep an eye on #2438 too.
