### ISSUE TITLE
[1.10]Biometric card, color and scale

### ISSUE THREAD

**Issue by Meller127** [AppliedEnergistics/Applied-Energistics-2#2498]
Build: rv4-nightly-30a978

The center color is Brown, expected is black and the dropped item scale is to large.

Expected 1.7.10
![2016-10-23_11 45 19](https://cloud.githubusercontent.com/assets/13392710/19625349/5cf9e338-9916-11e6-9cc9-9cfeb1248286.png)

rv4-nightly-30a978
![2016-10-23_11 44 52](https://cloud.githubusercontent.com/assets/13392710/19625354/8fe2e376-9916-11e6-91e9-622e69ac7d0e.png)

**Comment by shartte** [comment]
Thanks for the report. Should both be fixed now.
