### ISSUE TITLE
Tiny TNT floating in air when activated

### ISSUE THREAD

**Issue by Meller127** [AppliedEnergistics/Applied-Energistics-2#2499]
Build: rv4-nightly-30a978

Expected 1.7.10
![2016-10-23_12 05 55](https://cloud.githubusercontent.com/assets/13392710/19625450/1335746c-9919-11e6-86a4-390e395faef2.png)

Build: rv4-nightly-30a978
![2016-10-23_12 04 40](https://cloud.githubusercontent.com/assets/13392710/19625443/ecccbd58-9918-11e6-9e61-5a7d60a19b5c.png)

**Comment by shartte** [comment]
huh... odd
Will take a look at it

**Comment by shartte** [comment]
And thanks for your reports!

**Comment by yueh** [comment]
Maybe the hitbox of the entity is too large?
