### ISSUE TITLE
Rate of Change Based Monitor / Emitter

### ISSUE THREAD

**Issue by AlgorithmX2** [AppliedEnergistics/Applied-Energistics-2#25]
Configure a emitter, or monitor to show the changes in storage or items production / consumption.

Originally Posted by AlgorithmX2

This issue was migrated; For original details see http://ae-mod.info/Tracker/0271/

**Comment by yueh** [comment]
The PR to for the rate based level emitter needs still some rework.

**Comment by Technici4n** [comment]
Unlikely to ever happen in AE2 itself, but addon developers are welcome to use our API to implement this feature!
