### ISSUE TITLE
Controller Darkness-Lightning issue? 

### ISSUE THREAD

**Issue by DeadSix27** [AppliedEnergistics/Applied-Energistics-2#2502]
Forge Version: forge-1.10.2-12.18.2.2110
AE Version: https://github.com/AppliedEnergistics/Applied-Energistics-2/commit/30a978b614075b77c98bc632b16b86e184fcf170

I did not use/try OptiFine.

So on the ME Controller when turned on half of it get "somewhat dark" not sure if this is a graphic setting or a known issue or even a feature, just seemed odd:

See the red outlined areas on the NOT powered controller being evenly "lit" up
and on the POWERED controller being somewhat darkened out to the left 2/3 of it:

![lightning_bug](https://cloud.githubusercontent.com/assets/1492505/19630888/7d495542-9993-11e6-8456-33e3248f76fe.png)

EDIT: This is not due to the Animation, the animation goes on and the darkness stays.

**Comment by shartte** [comment]
Yeah, this is probably due to my attempted fix for optifine. I'll have to look into it. We may have to revert to our old (even hackier) approach for Forge, while we use this one to at least get it to render somewhat acceptably for Optifine.

**Comment by DeadSix27** [comment]
Ah, alright, kind of thought it would be about that since I've seen that optifine work around in the commits as well.
Considering I'll probably have to use optifine later on too, I guess its fine  :P

**Comment by shartte** [comment]
This should be fixed by 5954499. Can you validate that on your end?

**Comment by DeadSix27** [comment]
@shartte Yep fixed in https://github.com/AppliedEnergistics/Applied-Energistics-2/commit/59544993bd54839d40b4d771d787c55398d0f1de
with AND without Optifine :)

See screenshots:

Without Optifine:

![2016-10-27_21 35 06](https://cloud.githubusercontent.com/assets/1492505/19782366/e169107e-9c8d-11e6-9247-57a23bcc155c.png)

With Optifine:
![2016-10-27_21 39 05](https://cloud.githubusercontent.com/assets/1492505/19782368/e55f6282-9c8d-11e6-8cac-1657cbf4a1e3.png)
