### ISSUE TITLE
Quartz ores could not be smelted to quartz crystals

### ISSUE THREAD

**Issue by CatMe0w** [AppliedEnergistics/Applied-Energistics-2#2506]
#### Description

The certus quartz ores only can mine to drop the crystal items, and it is could not to get crystal by smelting. In the recipes of certus quartz in NEI, there is no way to turn quartz ores to crystals without break them by players. 
A picture of it: http://imgur.com/a/HeKs5

Can you make a recipe that let the furnaces can smelt certus quartz ores to crystals? Thanks.

#### Environment

- Minecraft Version: 1.7.10
- AE2 Version: rv2.stable build 10 and rv3.beta build 6
- Forge Version: 10.13.4.1158

**Comment by yueh** [comment]
Feel free to add your own recipes with our [custom recipes](http://ae-mod.info/Custom-Recipes/).

**Comment by CatMe0w** [comment]
@yueh Uh, though there is a way to solve this problem manually, why not add this recipe to mod by default?

**Comment by shartte** [comment]
Would be in line with vanilla to have such a recipe: 
http://minecraft.gamepedia.com/Diamond_Ore

It would be a bad ratio though, getting only 1 crystal from the ore block being smelted.
