### ISSUE TITLE
SpongeForge API Crash 

### ISSUE THREAD

**Issue by YOYOK9** [AppliedEnergistics/Applied-Energistics-2#2509]
#### Description
So not sure whether to report this to you or sponge powered (Forge) but it seems that there is an incompatibility with the 2 mods. 
From what it looks like when I add AE2 something loads prematurely and the server false to start. (Takes about 10 seconds to crash)

#### Environment
multiplayer server. 
Using spongepowered API for plugins. 
Running latests of SpongeForge, Forge, and AE2 nightly build
http://pastebin.com/eNiLEPit

- Sponge Forge: spongeforge-1.10.2-2107-6.0.0-BETA-1842
- Minecraft Version: 1.10.2
- AE2 Version: -rv4-nightly-923517
- Forge Version: 12.18.2.2114

Please let me know.

**Comment by yueh** [comment]
Known, but will not be fixed before reaching a more stable state.
