### ISSUE TITLE
I have found a bug in AE2 for 1.10.2

### ISSUE THREAD

**Issue by ItzGenetix** [AppliedEnergistics/Applied-Energistics-2#2512]
#### Environment

 SP
![2016-10-26_22 03 22]

- Minecraft Version: 
- AE2 Version: appliedenergistics2-rv4-nightly-41b875
- Forge Version: forge-1.10.2-12.18.2.2114

Here the photo: (https://cloud.githubusercontent.com/assets/20307984/19743248/dbc4f4f0-9bc8-11e6-9dc8-d1c13122b1f1.png)

**Comment by shartte** [comment]
You are using an outdated version.
