### ISSUE TITLE
Crash in JEI, possible interaction with ExtraUtils2

### ISSUE THREAD

**Issue by drowfx** [AppliedEnergistics/Applied-Energistics-2#2518]
#### Description

I am using AllTheMods 1.10.2 v1.39, with RefinedStorage disabled and appliedenergistics2-rv4-alpha-1 added. Otherwise the pack is unchanged. Sometimes when browsing JEI the client crashes.

Crash log: http://paste.ee/p/ki7Bw

Looks like some kind of item rendering interaction with ExtraUtils when rendering JEI results?

#### Environment

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-1
- Forge Version: Forge 12.18.2.2112

**Comment by shartte** [comment]
Hum i think we fixed this stuff a while ago.

Could you please delete the Facades.cfg in your config folder and see if the problem persists?

**Comment by drowfx** [comment]
That fixed it, thank you.

The problem seems to be that the AllTheMods pack includes (old) AppEng configs, even though the mod itself is not in the pack at the moment. Removing those fixes the issue.
