### ISSUE TITLE
[1.10.2] Sponge server crash

### ISSUE THREAD

**Issue by WhiteWidow** [AppliedEnergistics/Applied-Energistics-2#2519]
[http://pastebin.com/jPFYrE05](url)

- Minecraft Version:  1.10.2
- AE2 Version:  R4A0
- Forge Version: 1.10.2-12.18.2.2107

**Comment by shartte** [comment]
Sponge is currently not supported.

Also: Please do not tag your issues with 1.10.2

**Comment by shartte** [comment]
See #2482
