### ISSUE TITLE
Implement the RF P2P-Tunnel

### ISSUE THREAD

**Issue by shartte** [AppliedEnergistics/Applied-Energistics-2#2522]
Implement the RF P2P Tunnel with support for Forge Energy and Tesla. 

Decide upon which items can be used to actually mark a tunnel as such, since we only rely on APIs and not actual mods implementing the APIs, we don't really have access to any applicable items.

**Comment by yueh** [comment]
I am still not sure about the naming. Calling it RF tunnel but not support RF is really confusing for the players. Especially when we also have an IC2 tunnel (and not a generic Energy tunnel, but no idea, if I want to go there).

A Tesla tunnel would probably be ok, as most other mods are already communicating openly as some power system and not just an API, which should be hidden from the player.
But the FU tunnel would certainly be troublesome. Calling it just Energy tunnel would be as confusing as all other options and calling it Forge Energy/Units tunnel is certainly bad in terms of "omg. Every mod has to support it" and thus make most alternatives obsolete.

**Comment by shartte** [comment]
Yup, I share your concerns, but it's a real shitshow right now in terms of clarity for the player.

Should we check with the other mod authors implementing Tesla/RF and see what their take on it is?

**Comment by yueh** [comment]
We can start with the obvious ones and add IC2 + Tesla first and wait until the forge one settles a bit more. And not even adding a RF tunnel.

**Comment by shartte** [comment]
Well, for the player it *is* RF though.
If you look at EnderIO for example, it exposes it's internal power as the Unit of "RF". Tesla is never exposed anywhere. Can you refer me to the actual "gameplay" mod that Tesla comes from? 
Because on the API project page it states "Tesla is a power API designed for cross mod communication.".
This is not a concept I would expose a player to in the game.

**Comment by yueh** [comment]
There was this google doc about which mod supports what. I want to remember some mod where listed as Tesla only. If i recall correctly forestry wanted to drop RF support and just use forge/tesla.

The part about cross mod stuff is certainly listed by every API. But as real world example, you can say electricity is a cross device power transfer, while you certainly do not want to stick your 110V machine into a 240V power grid. Or even some HV stuff running at 380kV or more.

**Comment by VT-14** [comment]
I think Mekanism lets you choose which system to display in, and it uses "T" for Tesla (But RF it one click away with the same numbers).  I can't think of any other mods that actually display as Tesla in the game; only shown as RF on the surface.

I would personally look for RF P2P Tunnels first, even though they won't work with the actual RF API.  From a player perspective, most mods are using Tesla or Forge and displaying RF, and I would expect that power to be called RF everywhere regardless of what the API is named.

**Comment by Skaronator** [comment]
Any update on RF Tunnels?

**Comment by HIghCommander540** [comment]
Any movement on this? Its really annoying to not be able to attune a P2P tunnel to transmit RF. I need this feature. I don't want to setup generators everywhere.

**Comment by kkinateder** [comment]
I would like to have RF Tunnels in 1.10.2 too.

**Comment by mindforger** [comment]
most certainly not happening ... power systems are still a mess in 1.10 and there are way more important things to work on ... MC1.12 is knocking on the door
