### ISSUE TITLE
Put RV4 on the maven please

### ISSUE THREAD

**Issue by p455w0rd** [AppliedEnergistics/Applied-Energistics-2#2524]
Could you guys please get a build on the maven
- Minecraft Version:  1.10.2
- AE2 Version:  rv4-alpha-1
- Forge Version: 12.18.2.2114

**Comment by yueh** [comment]
The API is currently not finished. Once we have ironed out most of the bugs, we will potentially break it in major ways and thus wasting most of the time everyone would have spent on making addons. Thus deploying it to maven would be not a good idea now.

**Comment by p455w0rd** [comment]
I feel that "since the API may change/break" (generalised) is in no way a valid excuse to not push builds to the maven. At the very least we could get a start on what is there. It would be your job to push to the maven and our (addon devs) job to update our code as necessary. You're simply delaying the time it would take addon devs to begin active (meaning staying up-to-date) development as including the project in the workspace just isn't ideal/efficient. Having alpha versions of the actual mod (now 4 builds in) with no maven access is just silly. @bdew @DrummerMC Please weigh in if you would.

**Comment by bdew** [comment]
I'm just grabbing the JAR from curse and already have a public alpha out for AE2Stuff :P

I'm a stout follower of "release early, release often", so i don't like that reasoning too much, but meh.
