### ISSUE TITLE
Quartz Fiber break particles missing

### ISSUE THREAD

**Issue by Meller127** [AppliedEnergistics/Applied-Energistics-2#2525]
Quartz Fiber break particles missing

- Minecraft Version:  1.10.2
- AE2 Version:  rv4-nightly-ee0bfb
- Forge Version: Build 2114

**Comment by shartte** [comment]
I think this applies to all parts on a cable bus.

Did you just place the quartz fiber on its own?

**Comment by Meller127** [comment]
It was placed on its own, you have right it effects all parts, terminals, fiber etc.

**Comment by shartte** [comment]
Should be fixed for all parts now.
