### ISSUE TITLE
Light without lighttunnel.

### ISSUE THREAD

**Issue by Swabek** [AppliedEnergistics/Applied-Energistics-2#2528]
You are able to make a P2P light tunnel to a P2P redstone tunnel without loosing the light.

### Steps To Reproduce:
1. Setting up a network with 2 P2P light tunnels. One in a bright place (P1) and the other one in a dark place (P2).
2. Save the settings of P1 with an memory card and load it on P2.
3. Make P2 to an redstone tunnel (rightclick with a redstone)

### Actual Results:
The light of P2 **don't** extinguish.
Now you can also destroy the tunnel and you have still light.

### Expected Results:
The light of P2 extinguish.

Also if P1 was built (and the settings was saved) on the surface while it was day P2 is also bright if it is night. 

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-1
- Forge Version: 1.10.2-12.18.2.2114

**Comment by Meller127** [comment]
I get light even from regular ME Tunnel that stays even after breaking the tunnel.

**Comment by shartte** [comment]
Confirmed.

Easier way to reproduce: make a dark room. place a cable, place an illuminated panel
-> Room gets lit
Remove the illuminated cable
-> Room stays lit
Break the cable bus
-> Room still stays lit!
