### ISSUE TITLE
Tiny tnt results in endless explosion

### ISSUE THREAD

**Issue by Swabek** [AppliedEnergistics/Applied-Energistics-2#2529]
If you are able to ignite multiple tnts at the same time (with mods or with a redstone construction) you will end up in an endless explosion. Also I think the tnts reproduce them self and it starts lagging like hell.

### Steps To Reproduce:
1. Place 5 tiny tnts on top of each other
2. Bring them all to explosion in the same time (I used the explosive mod of the mining laser by Industrial Craft)

### Actual Results:
[Picture](https://swabek.de/uploads/bugs/tinytnt_ae_1.10.2.png)
and after a few seconds the hole game freezes.

### Expected Results:
Just a normal explosion.

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-1
- Forge Version: 1.10.2-12.18.2.2114
- Minecraft Version: 
- AE2 Version: 
- Forge Version:

**Comment by shartte** [comment]
Was able to confirm this.

**Comment by shartte** [comment]
Fixed. Tiny TNT Block wasn't destroyed when affected by an explosion, resulting in an endless loop of TNT spawning.

**Comment by yueh** [comment]
This might need further testing, due to the option to not have tiny tnt destroy blocks and calling `super` will also call `Block#onBlockDestroyedByExplosion` and not just set it to air.

**Comment by shartte** [comment]
Okay? But this is not for the case where TinyTNT explodes another block. The bug report is incorrect in that respect.
This is about a Tiny TNT block being affected by another "normal" explosion (i.e. normal TNT). In that case, the Tiny TNT should explode and be removed.
