### ISSUE TITLE
[1.10.2] Facades of Chisel blocks not rendering

### ISSUE THREAD

**Issue by Susjin** [AppliedEnergistics/Applied-Energistics-2#2531]
I think this is happening to every mod that render chisel blocks in other blocks (eg. EnderIO painting machine), looks like HenryLoenwind found a solution on build 121 of EnderIO.

Screenshot(that is a factory block facade):
https://imgur.com/a/4XNPg

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-2
- Forge Version: 12.18.2.2107

**Comment by shartte** [comment]
Fixed. Chisel was aware of the layer we were currently rendering. I introduced code to query the texture for all render layers and just use the first one we can get.
