### ISSUE TITLE
Lighting issues on ME Drive (and possibly other blocks?)

### ISSUE THREAD

**Issue by GuntherDW** [AppliedEnergistics/Applied-Energistics-2#2532]
There is an odd issue with lighting on blocks, but it only seems like the north face is affected by this calculation.

It is like the amount of blocks you have right behind the block makes it more and more buggy. It is like it's calculating the lighting for the face on the wrong face.

I have made an album to show it occuring, which might help explain the issue.
https://imgur.com/a/MW6wF

The strange part is that only the north face seems to be affected by this.

- Minecraft Version: 1.10.2
- AE2 Version: 53c32cc296481a92d792d906d4aabf68d5f66862 (manual gradle build)
- Forge Version: 12.18.2.2114

**Comment by shartte** [comment]
Reproduced

**Comment by shartte** [comment]
I tried every AE2 block. Also affected:

- Inscriber

**Comment by shartte** [comment]
Seems to be related to the auto-rotator, because disabling that fixes the problem.
