### ISSUE TITLE
Crash with Facade and Chicken Lib

### ISSUE THREAD

**Issue by HoussenMoshine** [AppliedEnergistics/Applied-Energistics-2#2533]
#### Description

Crash happening when i try to use Facade. Facade are transparent. Crash is systematic on loading the world.

For now, i have returned to appliedenergistics2-rv4-alpha-1.

Crash Log : **http://pastebin.com/NzvtyWbF**

- Minecraft Version:  1.10.2
- AE2 Version: appliedenergistics2-rv4-alpha-1
- Forge Version: Forge 12.18.2.2104

**Comment by shartte** [comment]
A facade made of what exactly?

**Comment by shartte** [comment]
p.s.: I don't think this is related to code chicken lib.

**Comment by yueh** [comment]
`Block#getBlockFromItem()` can potentially return null. But that should be fine here. A non `ItemBlock` should never reach this point.

**Comment by shartte** [comment]
We have some issues with facades still, but this looks like a removed item or block maybe?

**Comment by yueh** [comment]
A removed block would have triggered the NPE earlier. In terms of removed blocks, it would have to be a block now being an item, which would be very strange.

`PartPlacement.isFacade()` might be a option to filter them a bit more strictly.
