### ISSUE TITLE
Lighting Problem with Slabs

### ISSUE THREAD

**Issue by shartte** [AppliedEnergistics/Applied-Energistics-2#2534]
Supposed to look like this:

![](https://i.imgur.com/7Ly995I.jpg)

![](https://i.imgur.com/EG0biML.jpg)

**Comment by ItzKdoge20YT** [comment]
try rv4 alpha 2

**Comment by ken-noland** [comment]
nope, the light shouldn't pass through slabs, just like vanilla slabs

**Comment by VT-14** [comment]
The top picture is of Vanilla's Purpur slabs.  The bottom picture should look similar.

**Comment by fscan** [comment]
I cannot reproduce this with the current version. Probably fixed with the registration rework.
