### ISSUE TITLE
a bug Energy Acceptor or Controller Can't Power directly EU/RF or Tesla

### ISSUE THREAD

**Issue by ItzKdoge20YT** [AppliedEnergistics/Applied-Energistics-2#2539]
#### Description
i have Rv4 Alpha 1 latest version forge when i connect IC2 cables it won't connect? try putting MFE directly still not get power? i tried other power like RF and Tesla still doesn't work i have newest version of JEI and AE2
#### Environment
no crash report
just bugs
SinglePlayer Mode

- Minecraft Version: 1.10.2
- AE2 Version: Rv4 Alpha1
- Forge Version: 1.10.2-12.18.2.2114

**Comment by ItzKdoge20YT** [comment]
pls fix this

**Comment by MauveCloud** [comment]
> newest version of JEI and AE2
really?
> AE2 Version: Rv4 Alpha1
Rv4 Alpha2 has been out for about a day or so now.

**Comment by ItzKdoge20YT** [comment]
ill post my screenshots later, working on creative testing
oh it fixed? thx 
problem solved

**Comment by ItzKdoge20YT** [comment]
here screenshots
before alpha2
![2016-10-31_17 40 09](https://cloud.githubusercontent.com/assets/13083280/19851618/642949a6-9f91-11e6-9618-2b70af761f7f.png)

**Comment by ItzKdoge20YT** [comment]
#### Description
alright another issue
RF still not connect but not EU also P2P EU and RF Disappeared
EU just fine
#### Environment
SinglePlayer Mode

- Minecraft Version: 1.10.2
- AE2 Version: Rv4 Alpha2
- Forge Version: 1.10.2-12.18.2.2114

it won't connect RF Cables example : SolarFlux cable
oh well... RF won't work :( previous Version which is rv3 1.7.10 connect just fine
oh wait didn't work on p2p rf? nope p2p RF Disappeared for some reason

![2016-10-31_18 13 58](https://cloud.githubusercontent.com/assets/13083280/19852765/c28fdb4e-9f97-11e6-8e1e-6a2c09005a5a.png)
also RF and Eu P2P tunnel disappeared?
![2016-10-31_18 30 30](https://cloud.githubusercontent.com/assets/13083280/19852827/25910cae-9f98-11e6-91b7-2129c239a5d4.png)
