### ISSUE TITLE
RF Still not powering Controller or Energy Acceptor, also P2P EU and RF disappeared?

### ISSUE THREAD

**Issue by ItzKdoge20YT** [AppliedEnergistics/Applied-Energistics-2#2541]
#### Description
alright another issue
RF still not connect but not EU also P2P EU and RF Disappeared
EU just fine
#### Environment
SinglePlayer Mode

- Minecraft Version: 1.10.2
- AE2 Version: Rv4 Alpha2
- Forge Version: 1.10.2-12.18.2.2114
Optifine HD U D1
it won't connect RF Cables example : SolarFlux cable
oh well... RF won't work :( previous Version
oh wait didn't work on p2p rf? nope p2p RF Disappeared for some reason
using RFtools powercell connecting SolarFluxReborn Cables to ME Controller or Energy Acceptor
![2016-10-31_18 13 58](https://cloud.githubusercontent.com/assets/13083280/19852765/c28fdb4e-9f97-11e6-8e1e-6a2c09005a5a.png)
also RF and Eu P2P tunnel disappeared?
![2016-10-31_18 30 30](https://cloud.githubusercontent.com/assets/13083280/19852827/25910cae-9f98-11e6-91b7-2129c239a5d4.png)

**Comment by yueh** [comment]
Duplicate

**Comment by ItzKdoge20YT** [comment]
closed again....
what duplicate? it means i duplicate rv2 again?!
come on....
oh well i use EU then

**Comment by ItzKdoge20YT** [comment]
*Closed*

**Comment by mindforger** [comment]
dud duplicate by the meaning of "use the search" to look for issues like yours, this has been discussed already, to make it short for you, energy systems are clusterfucked a bit in the newer versions, drop the tesla API into your mod folder to get soem additional support,  but please use the search first befor reopening and crossposting

**Comment by ItzKdoge20YT** [comment]
i forgot to put tesla API damn...

**Comment by ItzKdoge20YT** [comment]
still didn't work
i was late due to internet down for 3 days

**Comment by ItzKdoge20YT** [comment]
rv4 alpha3 should fix...

**Comment by ItzKdoge20YT** [comment]
where that issue number that duplicated...

**Comment by mindforger** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/search?q=energy+acceptor+not+accept+power&type=Issues&utf8=%E2%9C%93
