### ISSUE TITLE
Annihilation Plane not annihilating anything when at least one item can't be transmitted or when water is pushing items to it

### ISSUE THREAD

**Issue by flonou** [AppliedEnergistics/Applied-Energistics-2#2546]
The annihilation plane has some weird behaviors : 
When an annihilation plane is placed vertically, with water pushing items towards it, the items won't be annihilated
Also, when placed horizontally, again with water pushing the items above it, if at least one item can't be annihilated (i.e. not stored or imported by anything in the network), none of the items (even the valid ones) will be annihilated

- Minecraft Version: 1.10.2
- AE2 Version: rv4 nighlty 30a978
- Forge Version: 12.18.2.2107

**Comment by shartte** [comment]
Hi, I can't actually find the nightly version you are referencing. Where did you get that from?

I don't think it really affects the behavior you describe here, but I'd like to know.

**Comment by flonou** [comment]
I got it from the link in the readme file. Its date is 22/10/2016 it seems

**Comment by shartte** [comment]
Ah I see. It was so far down in the list that I didn't see it.
You can see the changes since then here: https://ci.appveyor.com/project/shartte/applied-energistics-2/history

But as I said, I don't think there were any changes to how Annihilation Planes work since then, so I'll look into it.

**Comment by flonou** [comment]
I just tried latest nightly build (9bf296) and can confirm the behavior has not changed :)

**Comment by flonou** [comment]
Hi ! I think the second part of the bug is still present (when items can't be sucked by the annihilation plane, it prevents valid items to be annihilated too) :)

**Comment by yueh** [comment]
This is intentional to prevent performance problems by failing when trying insert hundreds of floating items.
