### ISSUE TITLE
Fluix Crystal won't form above annihilation plane

### ISSUE THREAD

**Issue by flonou** [AppliedEnergistics/Applied-Energistics-2#2547]
I tried to get automated crafting of fluix crystal using formation and annihilation plane. I turns out that fluix crystal won't form when above an annihilation plane (with water flowing on it, of course)

- Minecraft Version: 1.10.2
- AE2 Version: rv4 nighlty 30a978
- Forge Version: 12.18.2.2107

**Comment by shartte** [comment]
So I looked into the code. The crystal is 0.001 units below the water if it's bouncing on an annihilation plane and doesn't register itself as being inside the water at that point. 
I'll have to look into how the behavior was in 1.7 to compare if this is even related to the 1.10 port.

**Comment by shartte** [comment]
Tested it in 1.7. The issue doesn't exist there. Might be a change in how entities collide with our stuff.
