### ISSUE TITLE
NoSuchMethodError: net.minecraft.item.Item.func_77640_w()Lnet/minecraft/creativetab/CreativeTabs

### ISSUE THREAD

**Issue by C0rn3j** [AppliedEnergistics/Applied-Energistics-2#2548]
Relevant bit of the log: http://pastebin.com/6F7xyMTC

Modlist: http://pastebin.com/KQYzk5xn

Forge 2116.

**Comment by shartte** [comment]
The message itself is harmless btw., so stating what the actual effect of the bug you are reporting is, would have been nice.

Fixed the log message by disabling the item.csv export on the server side. Creative Tab information is not accessible on the server.

**Comment by C0rn3j** [comment]
>stating what the actual effect of the bug you are reporting is, would have been nice.

No effect besides console throwing a bunch of errors.
