### ISSUE TITLE
Assembler is being rendered insideout in your hand

### ISSUE THREAD

**Issue by GuntherDW** [AppliedEnergistics/Applied-Energistics-2#2549]
The Molecular Assembler seems to have an issue being rendered in the players' hands. This is without mods like OptiFine installed.

http://i.imgur.com/yheqYvY.png

In-world assemblers are being rendered fine, but when holding it inside your hands it kind of looks like the quads are being drawn in the reverse order, or some other OpenGL screw-up.

- Minecraft Version: 1.10.2
- AE2 Version: c7eb696d60e37acd0b39f1e0d418625a216f9d36
- Forge Version: 12.18.2.2117

**Comment by yueh** [comment]
The assembler uses a normal json model. No idea how there could screw up on our side.

@shartte The fix to lighting does not seem to affect it.

**Comment by shartte** [comment]
The problematic part is this in code snippet in ItemRenderer (vanilla):

  boolean flag = this.itemRenderer.shouldRenderItemIn3D(heldStack) && this.isBlockTranslucent(block);

            if (flag)
            {
                GlStateManager.depthMask(false);
            }

            this.itemRenderer.renderItem(heldStack, entitylivingbaseIn, transform, leftHanded);

            if (flag)
            {
                GlStateManager.depthMask(true);
            }
