### ISSUE TITLE
ME drive and storage bus strange interaction

### ISSUE THREAD

**Issue by Frosky01** [AppliedEnergistics/Applied-Energistics-2#2554]
#### Description
When a storage bus is connected to a ME drive it can copy the information form one cell into the other when you extract cells form a terminal.

#### Environment
I made a imgur album showing the steps to reproduce the bug: http://imgur.com/a/mFSq9, the bug only happens if the cell you are interacting isn't in the first slot. 
Only tested in single player.
I've also seen this bug happening when you have the same conditions but with an array of ME drives connected via a storage bus -> interface. But in that case the copying of data happens in others ME drives, not in the same one.

- Minecraft Version: 1.10.2
- AE2 Version: appliedenergistics2-rv4-alpha-3
- Forge Version: 12.18.2.2116

**Comment by yueh** [comment]
Not related to cells in general. Just any item with specific nbt data.
