### ISSUE TITLE
Pattern terminal discrepancy from 1.7.10

### ISSUE THREAD

**Issue by GuntherDW** [AppliedEnergistics/Applied-Energistics-2#2556]
#### Description
The pattern terminal behavior when you're making processing patterns is a bit different than it was in 1.7.10 in terms of clicking with the mouse. It's quite a bit different if you're used to the details of 1.7.10 but nothing gamebreaking.
This probably is more of a suggestion than a bug, as it's just behavior that's a bit different.

**1.7.10:**
You can take a full stack of an item, and left click it in to specify that item, and that stacksize.
A right click with the item will tell it to take the item, but only specify 1.

You can increase or decrease the amount afterwards by right or left clicking on that item.
Left clicking with an empty hand clears it, right clicking decreases the amount by 1.
If you're holding the exact item and left click it'll increase the amount.

**1.10.2:**
In this version if you either right or left click with any item it will take the item, AND the stacksize. Whether or not you left or right clicked. The amount will be the amount you had in your hand, no exceptions.
You are also not able to increase or decrease the stacksize afterwards.

Right or left clicking with an empty hand on the item will clear the spot in the recipe.

- Minecraft Version: 1.10.2
- AE2 Version: https://github.com/AppliedEnergistics/Applied-Energistics-2/commit/c7eb696d60e37acd0b39f1e0d418625a216f9d36
- Forge Version: 12.18.2.2117

**Comment by DerMax93** [comment]
I don't know whether I should open a new bug-report or continue ins this one, but I found this report via google and it seems to coincide with my experience.

When creating patterns (especially processing-pattern) i am used to just right-clicking the itemstack into the desired slot in the grid to place a single item there. While this does work normally on a crafting-terminal it doesn't on a pattern-terminal. The initial right-click does not place anything in the slot and if you then continue to drag the mouse across to other slots both the initial and the subsequent slot do receive the correct amount (1 piece each) of the item in hand.


PS: I initially suspected inventory tweaks of messing with the way the items are handled, but even after disabling it the problem does persist.

MC-Version: 1.10.2
AE2 Version: rv4-stable-1
Forge Version: 12.18.3.2511

**Comment by fscan** [comment]
FYI, disabling MouseTweak's right mouse button tweak fixed all the issues for me (also lots of non AE2 related issues).

**Comment by DerMax93** [comment]
Thank you :)
Disabling Mousetweaks did the trick for me as well :+1:
