### ISSUE TITLE
AE meteor crashes when being exploded with ic2 nuke

### ISSUE THREAD

**Issue by Crazy-KSK** [AppliedEnergistics/Applied-Energistics-2#2558]
https://gist.github.com/7c550186e036507b6a8b1aae936b6ea8
https://gist.github.com/6dc5111dfcad33150d973a094396ff54

the first time the meteor just go caught in the blast, to replicate it I had to place the nuke a bit inside the meteor 

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-3
- Forge Version: 12.18.2.2117

**Comment by thatsIch** [comment]
mh why is our TESR called for an air block?

**Comment by shartte** [comment]
Well, theoretically some desync issue maybe? I suppose this could only happen on a server/client environment. In my initial attempts I can't reproduce this locally. 
We can be more defensive in the sky chest TESR however.

**Comment by shartte** [comment]
I made it more robust, can you check again with the next release or the current nightly build, @Crazy-KSK ?

**Comment by Crazy-KSK** [comment]
Sorry for the late reply.
I went and blew up two dozen meteors with zero crashes, so this has fix worked!
