### ISSUE TITLE
Inventory Tweaks sorting

### ISSUE THREAD

**Issue by b0bst3r** [AppliedEnergistics/Applied-Energistics-2#2559]
Can we have inventory tweaks sorting back please in the terminals, it was one of the best custom ways of sorting items that we had.  

- Minecraft Version:  1.10.2
- AE2 Version: appliedenergistics2-rv4-alpha-3
- Forge Version: forge 1.10.2-12.18.2.2116

**Comment by yueh** [comment]
Is there any maven repo for it?

**Comment by b0bst3r** [comment]
https://github.com/Inventory-Tweaks/inventory-tweaks

**Comment by yueh** [comment]
We also cannot ignore that the sorting is still bugged as it is not transitive. So it will introduce guaranteed crash currently.

**Comment by thezak48** [comment]
Is this possible now in its current state?

**Comment by GuntherDW** [comment]
The same question has to be asked again. "Is there any maven repo for it".
That is pretty much a requirement before we can actually support it properly.

The old way of having API's in "thirdparty/" was messy and requires us to manually keep it up to date.
Hence why it was removed in favour of just using maven repo's.

**Comment by MrMetric** [comment]
According to Google, it is at http://mvn.rx14.co.uk/simple/local/inventorytweaks/InventoryTweaks/. According to [BetterStorage's build.gradle](https://github.com/copygirl/BetterStorage/blob/master/build.gradle), it is http://mvn.rx14.co.uk/repo/. But, when I go to either in a browser, I get 'No such site at :80'.

**Comment by cooliojazz** [comment]
Is using CurseForge's maven looked down upon for any reason? It's what I used when I added InventoryTweaks sorting to RefinedStorage  (see https://github.com/raoulvdberge/refinedstorage/commit/90a137ea100e630e00f4bcbcbda9d1064acd7531 ), and if you really just need it in a maven repo of any sort so it can work with the build proccess, that might work?

**Comment by fscan** [comment]
Hmm .. didn't know about the curse maven repository.
