### ISSUE TITLE
Dye applicator does not dye ME FMP Parts

### ISSUE THREAD

**Issue by Cisien** [AppliedEnergistics/Applied-Energistics-2#256]
http://paste.cisien.com/f/5630356b.png

**Comment by TheJulianJES** [comment]
In the ColorApplicator there should be something like this:
````
if(cable.fmp.getBlock instance of IColorThing)
````

**Comment by thatsIch** [comment]
its more of a problem to me, the lack of FMP knowledge

**Comment by TheJulianJES** [comment]
I agree, I will try to learn a bit of FMP, since there are also many others bugs in AE2 with FMP. If I learned a bit I will try to create a PR :D
