### ISSUE TITLE
Add check for real player in crafting listeners

### ISSUE THREAD

**Issue by RealGrep** [AppliedEnergistics/Applied-Energistics-2#2561]
#### Description
The new version of reliquary is causing all patterns created to be invalid. I filed a PR there, and he said it's because AE2 needs to add a check for a player here, since it's assuming all crafting listeners are players:

https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/main/java/appeng/container/implementations/ContainerPatternTerm.java#L498

The PR in question: https://github.com/P3pp3rF1y/Reliquary/issues/186

#### Environment
- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-3
- Forge Version: 2116
- Reliquary Version: 1.10.2-1.3.3.585
- SMP

**Comment by ozhound** [comment]
I am seeing the same problem. I can not confirm that it is Reliquary though.

**Comment by ozhound** [comment]
Also Chisel and Bits is having an issue with the same Tear error bug
https://paste.ubuntu.com/23419764/

**Comment by predakanga** [comment]
Can confirm that guarding the referenced line with an `IContainerListener instanceof EntityPlayerMP` check enables patterns to work with the latest versions of Reliquary.

I'm not certain of any further ramifications though, so I won't provide a PR.
