### ISSUE TITLE
Item render crash(Facades)

### ISSUE THREAD

**Issue by S-Fort** [AppliedEnergistics/Applied-Energistics-2#2564]
Crash when with JEI:
Trying to type: "lo"
       Vazkii/Botania#2010
Trying to type: "ca"
       [Railcraft](http://pastebin.com/Y7gLb5Um)
       [Unknown mod](http://pastebin.com/Pn9R66c9)
- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-3
- Forge Version: 12.18.2.2107

**Comment by yueh** [comment]
Duplicate
