### ISSUE TITLE
Cable Anchors Do not update properly when placed on a cable

### ISSUE THREAD

**Issue by Joshwoo70** [AppliedEnergistics/Applied-Energistics-2#2566]
#### Description
When a cable anchor is placed it does not render but the hitbox is there.
![2016-11-04_18 41 12](https://cloud.githubusercontent.com/assets/7894419/20003116/90cd5962-a2bf-11e6-8f19-bdc63aaa677c.png)
#### Environment
(Not Really related to texture issues)

- Minecraft Version: 1.10.2
- AE2 Version: rv4.alpha build 4
- Forge Version: 12.18.2.2118

**Comment by GuntherDW** [comment]
It happens for me as well, but I have noticed that if you update the neighbouring blocks that the anchor does in fact get rendered.
