### ISSUE TITLE
Crash related to Applied Energistics facades, Extra Utilities block models, and JEI

### ISSUE THREAD

**Issue by kaitoyuuki** [AppliedEnergistics/Applied-Energistics-2#2568]
#### Description

When searching JEI for applied energistics by mod (@appliedenergistics), the game will crash to desktop as soon as some of the facades try to load on the screen. It appears to be a rendering bug, most likely related to something from Extra Utilities judging by the stack trace.

#### Environment

Issue occurs on a client connected to a sever; Have not tested if the issue persists in single player, but given the nature of the issue I imagine it will persist.

Crash report: https://gist.github.com/kaitoyuuki/ae16833e790bab47a6cd8e050048a2b0
FML log: https://gist.github.com/kaitoyuuki/4dd2a1b4a75b779a28c475269a9b2e79

- Minecraft Version: 1.10.2
- AE2 Version: rv4 alpha 3 for 1.10.2
- Forge Version: 1.10.2-12.18.2.2117

**Comment by yueh** [comment]
#2557

**Comment by shartte** [comment]
@kaitoyuuki Please try latest alpha. In your case, also delete Facades.cfg.
