### ISSUE TITLE
Server won't start without IC2

### ISSUE THREAD

**Issue by RealGrep** [AppliedEnergistics/Applied-Energistics-2#2569]
#### Description
Unable to start the server with the latest update (rv4-alpha-4). I get a ticking block entity caused by:
java.lang.NoClassDefFoundError: ic2/api/recipe/IRecipeInput

#### Environment
- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-4
- Forge Version: 2116
- SMP

The crash log: https://gist.github.com/RealGrep/f675c1e47d2c0f741b94d7a79feef31d

**Comment by shartte** [comment]
Working on it. For some reason, I only get this sporadically, even without IC2 being present. I am in the process of debugging it.

**Comment by shartte** [comment]
PR #2581 fixes this, but needs review first since it's ab it more involved.

**Comment by shartte** [comment]
This should now be fixed with alpha 5

**Comment by RealGrep** [comment]
Yep, looks good. Server starts ok now, plus I zapped my AE2 configs, and I can scroll through the entire JEI list and nothing crashes. Good stuff.
