### ISSUE TITLE
NPE Breaking 16K Crafting Storage

### ISSUE THREAD

**Issue by Ommina** [AppliedEnergistics/Applied-Energistics-2#2570]
http://pastebin.com/PdyDUdqF

OK, repeating this second person.

Setup was a Controller, 4K crafting storage, crafting co-processor, 16k crafting storage, horizontal.  Red glass cable was placed on the co-processor (did not connect to a controller, or the 4k), then extended onto the 16k crafting storage.  16k crafting storage was then harvested.  Server exploded in a fit of fire and tears.  Restarted with no problems, but 16k had vanished from the world.

SMP
Forge 2116
AE2 rv4 alpha4 for 1.10.2

**Comment by shartte** [comment]
Like this?
![](https://i.imgur.com/pYany65.jpg)

**Comment by Ommina** [comment]
Pretty much, yes.  The red glass cable may have extended off a pair of blocks further over empty space, as I believe intention was to have the 16k as a distinct crafting CPU, joined to the main network via the glass cable.

I appreciate this isn't much to go on, and I regret not taking a backup of the world as soon as it happened.

**Comment by Crazy-KSK** [comment]
I noticed something possibly related: the arrangement above has a hard time forming a multiblock if the controller is on the south side and a chunk boundary goes through the middle
http://i.imgur.com/6M2StKp.jpg

Singleplayer
Forge 2122
AE2 rv4 alpha-4 for 1.10.2

**Comment by Ommina** [comment]
Goodness, I didn't even think of checking the orientation of the blocks.

It looks like they were running east-west, with the controller on the west end.  Doesn't appear that they crossed a chunk boundary.  (I fear I'm not helping much here.)

**Comment by yueh** [comment]
Can you provide the full log additionally to the crashlog?

**Comment by Ommina** [comment]
If by full log, you mean the fml-server-n.log, then yes, that I still have.  Do you need the whole thing (3283 KB, presumably I can attach it here), or is the tragic ending sufficient?

I note there are 771 lines worth of

`[18:37:53] [Server thread/ERROR] [AE2:S/]: [AppEng] Network Event caused exception:
[18:37:53] [Server thread/ERROR] [AE2:S/]: Offending Class: appeng.tile.networking.TileController
[18:37:53] [Server thread/ERROR] [AE2:S/]: Offending Object: appeng.tile.networking.TileController@1b60a15f
`

before the actual crash.

**Comment by yueh** [comment]
Full one please, github should also allow you to zip it.

I have an idea where the problem is and the log might provide some info about it.

**Comment by Breadabix** [comment]
I am having the same issue with 64k and co processing units. The blocks are in a cube, connected by magenta covered cable with channels disabled. It is happening with multiblocks in a singe chunk and across chucks. Just fixed it, so will post screenshot when it next happens if needed.

**Comment by Ommina** [comment]
And here's the full log file.

[fml-ae2-exception.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/579554/fml-ae2-exception.zip)

**Comment by yueh** [comment]
Thanks for it. It sadly does not contain the actual exception, as these will only be logged when the debug logging is enabled in the config.

Can you reproduce it easily or was this just a one-off crash?

**Comment by Ommina** [comment]
Strictly a one-off, I'm afraid.  I've since turned on the debug logging, "just in case", but so far we've seen no other untoward behaviour.
