### ISSUE TITLE
Server crashes when chunk containing a player's AE2 system is loaded

### ISSUE THREAD

**Issue by corvak** [AppliedEnergistics/Applied-Energistics-2#2571]
#### Description
Server crashes as soon as the chunk containing the AE2 system is loaded. Player had just placed Red Matter from Project E into the system.

#### Environment

- Minecraft Version: 1.10.2
- AE2 Version: rv4 alpha 4
- Project E version: PE1.0.6B
- Forge Version: 1.10.2-12.18.2.2118

Server Crash log: http://pastebin.com/CpZKRP5V

**Comment by shartte** [comment]
First Glance: A Project E item lost it's NBT tag, which crashes inside of Project E.

It'll be hard to figure out how the item lost the NBT, but it would also be nice if Project E didn't crash in that case.

**Comment by shartte** [comment]
PR #2573 will also allow to remove such offending items in the future without having to throw the world away.

**Comment by shartte** [comment]
@corvak If you want to fix this in the meantime, you can use one of the nightly builds and see if it fixes it for you (it should).

**Comment by corvak** [comment]
Thanks. Already fixed by deleting the player's ME Drive with MCEdit. 

Such is life with new mods :)
