### ISSUE TITLE
Inscriber freezes by autocrafting and don´t get materials.

### ISSUE THREAD

**Issue by Stiefel94** [AppliedEnergistics/Applied-Energistics-2#2572]
#### Environment

- Minecraft Version: 1.7.10 (FTB Infinity)
- AE2 Version: appliedenergistics2-rv3-beta-6
- Forge Version: 7.10.99.99

Hello community,

i have a major problem with my autocrafting. Because if i start the crafting of 20 Calculating Processors at some point the inscribers just stop working. They freeze sometimes by 20 % or the silicon don´t gets injected in the inscriber with the export bus.
Here are pictures of the full setup. In picture 2 you can see the inscriber in freezed status. Energy is enough, as you can see in picture 3.
In picture 5 you see that i have silicon in my system but the export bus pic 6 doesn´t export the silicon in the inscriber in picture 7.
And every material is having this problem not only the silicon.

Maybe its a bug, but i´m not sure because this is my first setup with autocrafting.

![me_bug_10](https://cloud.githubusercontent.com/assets/23276042/20029361/2acd8f84-a34a-11e6-8755-1059790c79a9.PNG)
![me_bug_11](https://cloud.githubusercontent.com/assets/23276042/20029359/2acab246-a34a-11e6-9e75-bda902a66cf0.PNG)
![me_bug_12](https://cloud.githubusercontent.com/assets/23276042/20029360/2acc6faa-a34a-11e6-84d9-e3648ee42727.PNG)
![me_bug_13](https://cloud.githubusercontent.com/assets/23276042/20029358/2acadbfe-a34a-11e6-875d-2d14da805e2c.PNG)
![me_bug_14](https://cloud.githubusercontent.com/assets/23276042/20029362/2ad1dbfc-a34a-11e6-9d23-117c6217cfec.PNG)
![me_bug_15](https://cloud.githubusercontent.com/assets/23276042/20029364/2b0619bc-a34a-11e6-87b1-0e0318b6047a.PNG)
![me_bug_16](https://cloud.githubusercontent.com/assets/23276042/20029363/2ae03918-a34a-11e6-90fc-72ff39e3c0b0.PNG)

Have a nice day.

Steve

**Comment by Meller127** [comment]
Look at this http://ae-mod.info/Inscriber/ and you will get the order the inscriber accept items in its diffrents slots

**Comment by Stiefel94** [comment]
I don´t know if this solves my problem because it is working fine. then at some point the complete system stops working. even my import busses won´t work anymore. The complete system stops working. And i have enough diskspace.

**Comment by Meller127** [comment]
Do you have any chunk loaders?

**Comment by Stiefel94** [comment]
Only 2 querrys. But im directly next to the inscribers. So they are only 5 blocks away from me.

**Comment by Meller127** [comment]
Do you have enough cpus to handle to hole chain, if there is auto crafting requests?

**Comment by Stiefel94** [comment]
Yeah there are enough. And inscribers won´t stop by 21 % and don´t finish the printed silicon if there are to less cpus, or?. Even if i put it inside from hand it won´t work. and all my import and export bus don´t work anymore. channels are also enough in the system

**Comment by Meller127** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2500

If you break the export bus for Silicon and Place it manualy will it finish?

**Comment by Stiefel94** [comment]
Sorry waiting for the bug to happen again :D

**Comment by Stiefel94** [comment]
So i rewired the complete network and now it seems to be working. But now i have another problem.
After 10 or more minutes the ME-System starts dropping all new importet items. I have enough space in the me but if i put an item in the me it just disappears.

**Comment by Stiefel94** [comment]
Even if i have 200 cobble in the system and i take 64 of them and then put them in again. They disappear. This is realy a big problem because we loose to much items.

**Comment by mindforger** [comment]
if you have any Deep Storage Units in your system, make sure they are all unlocked, this sounds familiar

also double and tripple check you have no trash cans or matter condenser in your system that may be trashing items

**Comment by Stiefel94** [comment]
3 Deep Storage Units. All 3 were locked. What happens if they are locked?

**Comment by mindforger** [comment]
ther is something derpy about ME interfacing locked DSUs ... yet still unknown why exactly, but is really sounds like that issue

**Comment by swoolcock** [comment]
Having a storage bus on a locked DSU can cause items to be incorrectly sent to it unless you put the DSU's contents in the storage bus whitelist.  Otherwise, the system will see it as a valid target for any item, but the DSU will just eat it.  I put a storage cell in an IO port and it sent the entire contents to the void.  I lost 1300 iridium ore.  :(

**Comment by mindforger** [comment]
@swoolcock thank you for this explanation, it makes totally sense, i'll note that down, have my gratitude

**Comment by Stiefel94** [comment]
Thank you very much.
