### ISSUE TITLE
RV4 API Suggestions

### ISSUE THREAD

**Issue by p455w0rd** [AppliedEnergistics/Applied-Energistics-2#2578]
I figure this can serve as the base issue for all suggestions to the RV4 API. Paging @bdew @DrummerMC

**Comment by shartte** [comment]
Heh, I'd more like one issue per suggestion so we can actually close them at some point ;-)

Otherwise this will probably degenerate into a gigantic mess.

**Comment by p455w0rd** [comment]
I give up..you guys are seriously impossible

**Comment by shartte** [comment]
You realize that with closing them I mean after we have implemented them, right?
