### ISSUE TITLE
missing ores support for grindstone

### ISSUE THREAD

**Issue by Hypsellis** [AppliedEnergistics/Applied-Energistics-2#2584]
I just wanted to suggest to add a support for all the Substratum and TechReborn ores in the default config for the grindstone. ;)

**Comment by VT-14** [comment]
What would you want added from Ender IO?  It doesn't add any ores.  The one recipe that uses Copper will use an Iron Ingot if you don't have another mod that adds copper.

**Comment by Hypsellis** [comment]
It doesn't add any ores to the generation, but it has his own ores. ;)

**Comment by VT-14** [comment]
Really? Which ones and how do you get them?

**Comment by Hypsellis** [comment]
http://wiki.enderio.com/Alloy_Smelter

**Comment by VT-14** [comment]
Those are alloys, and none of them have crushed versions.  I'm really confused here. Can you take away any ambiguity and list the recipe you want?  Input -> Grindstone -> Output.

**Comment by Hypsellis** [comment]
Yeah my bad it was an error from me. It was for the pulsating crystal, vibrant crystal and ender crystal. But they seem to have a special process, so do what you want.

**Comment by Hypsellis** [comment]
If you want a list of the potential ores which miss in the default config, it misses the Steel, Cupronickel/Constantan, Chrome, Titanium, Tungsten, Tungstensteel, Uranium. I surely forget somes, but it's the ones that come in my head now.

**Comment by VT-14** [comment]
Just to let you know, I'm just a random person who isn't associated with AE2.  I just happen to be fairly familiar with Ender IO and was confused about what you were asking for.

**Comment by Hypsellis** [comment]
Yeah I guess, it's fine that you notice me about it. I do sometimes errors. ^^'

**Comment by yueh** [comment]
As you said, it is the default config. Which should work with the common ones, but not everything out there. Because these might have special handling to turn ore/ingots into dust, which usually not the case for the common ones.

That is why it is a config option. Missing something for your modpack? Simply add it. Or trust the modpack author to maintain it correctly.
