### ISSUE TITLE
Cross-world QNB issues

### ISSUE THREAD

**Issue by GuntherDW** [AppliedEnergistics/Applied-Energistics-2#2594]
#### Description
I have a fullsized controller in the overworld, connected via a P2P network over a QNB to another world. In this case it's the mining world from Aroma1997.
https://minecraft.curseforge.com/projects/aroma1997s-dimensional-world

In short, the storage is in the overworld, while 90% of the processing, like the processor banks and interface/assemblers are in the other world.
Both spots are fully chunkloaded. Either Extra Utils 2 chunkloaders, or FTBUtilities' chunkloaders.
Both networks also have a bunch of dense power cells, around 25 each.

However, when I'm in the overworld, only briefly but on a bunch of occasions the network will "reset" itself, like it lost power, or the chunks not being loaded.
Sometimes when the system is in the middle of crafting something it can lead to loss of items while the processor banks throw out their items into the world.
This made the map have an almost unplayable TPS once when I decided to request a ~200K dust -> ingot process and it decided to throw it all out in the process. This made me have to MCEdit out all the dropped entities.

I have a Mekanism fusion reactor generating 2M RF/t, feeding into an Ender IO capacitor bank that can deliver up to 6M RF/t, power is not the issue I think.

I remember a couple tweets from Dinnerbone back in the day how he was experimenting with threads for different worlds, could this be an issue?
I'm about to try and see if ChickenChunks or other chunkloaders also cause these issues, but because of the randomness of the issue it's kind of hard to narrow down on what's causing it.

EDIT: I have noticed that when I stay in the mining world's chunks, that the issue comes up less regularly. Then again I don't know if it's the storage now that gets reloaded, but I don't see any resets on this end.

#### Environment
This is in a singleplayer environment. I can try to put the world on a server and see if it still happens there.
I can try to provide screenshots of the setup, but I don't think anything would provide anything valueable, unless I make a creative testworld replica of the setup.

So the setup that I have right now is controller > P2P into a P2P subnet in order to have more than 32 channels available on the other end of the QNB and back to P2P and into processing in the other world.

- Minecraft Version: 1.10.2
- AE2 Version: 77bb28ded62bc157bf18ca5e50f653152cb90d8f
- Forge Version: 12.18.2.2122

**Comment by yueh** [comment]
The usual not enough power issue. Add energy cells.

**Comment by mindforger** [comment]
>Both networks also have a bunch of dense power cells, around 25 each.

I doubt that this is an actual power issue @yueh, crafting CPUs dont't spill Items when powerless don't they?

I would see the Chunkloading as an Issue here. Since when does EXUtils provide Chunkloader?
Avoid ChickenChunks Chunkloaders for starters, I would recommend to retest this behaviour with Railcraft World Anchors (you can disable Fuel requirement in the Config)

Also try to Chunkload everything with FTBUtils and test if it persists.

**Comment by GuntherDW** [comment]
I kind of doubt it's a power issue as well.

I tried chunkloading with FTBUtils, but changed to the Extra Utils one to try to "fix" this.

I just saw it happen even when every dense cell is fully charged.

http://i.imgur.com/y5YpAdW.png on the P2P subnet and
http://i.imgur.com/jTpKOJh.png is the "main" network.

I guess I'll have to add more then?

**Comment by yueh** [comment]
CPUs spill their items, if they are changed somehow and have not other options to dump it back into the network. So usually P2P tunnels failing through missing power, chunkloading etc. (Not sure currently what happens, if they "join" a new network when the QNB or P2P stop working. They might just stall, but could also break internally).

To throw some numbers in. Each time an item enters or leaves the network it costs 1 AE. (stacksize = 1, full stack of cobble = 64 items)
So in terms of 200k dust it requires at least 400k AE, 200k to extract the dust, 200k to insert the ingots back into it.

**Comment by mindforger** [comment]
okay but he has at least 40mio reserve, but is this reserve through the whole network present? maybe the p2p connection is not buffered properly ?!

**Comment by GuntherDW** [comment]
It even happens when I'm not crafting anything. When I want to request something it'll just tell me that no crafting CPU's are available. Which leads me to believe it's either chunkloading or threading issues?
Either both FTBU and ExU chunkloading don't do a good enough job or my wiring is bad. I triplechecked that everything is within the chunk boundaries and loaded though (as well as enough GP to handle the chunkloaders, I have over 400 GP in reserve for them, use 600, have 1008).

**Comment by yueh** [comment]
I have no idea how any chunk loaders in 1.10 behaves. But personally I think linking them to some power system usually causes more issues than it solves. Like is grid power perfectly deterministic? So does it always operate in the same order respective to insert/extract? Or be non deterministic, so one tick it will extract the 600 as last operation and the next tick as first, having not enough stored and stop to work.

@mindforger sounds like an idea. Feel free to make a feature request for it. Might be also an idea for modpack makers as quest reward.

**Comment by GuntherDW** [comment]
Are there any chunkloaders that you want me to try out then @yueh? So far I've tried FTBUtils' chunkloaders and Extra Utilities 2's chunk loaders.
I'm going to try the railcraft world anchors when I can get them working, there seems to be some issue with my configs according to the logs.

**Comment by mindforger** [comment]
hm yeah i figured that as well, the release was only for halloween and not even feature complete before january, i was just looking for a 1.10 tag on the build :P

i'll open an issue for that request :)

**Comment by GuntherDW** [comment]
It seems the issue was with forge.
I upped the limits in forgeChunkLoading.cfg after noticing that a single mod can only "claim" up to 25 chunks in a dimension before it starts unloading random other chunks.

For testing sake I upped the limits tenfold for the default config, reapplied the chunkloaders and everything seems to be running fine so far.

**Comment by mindforger** [comment]
nice to know, I heared that some mods adapted the forge chunk loading but i did not know there is such a limit
