### ISSUE TITLE
Autocrafting Multiblock structures keep breaking

### ISSUE THREAD

**Issue by Breadabix** [AppliedEnergistics/Applied-Energistics-2#2597]
When the auto-crafting multiblocks are being used they are fine, but when they are not being used some of the blocks in them, sometimes more than half, will break, like old IC2 machines with too much power. I assume this isn't meant to happen, and it gets quite annoying. 

The structures are chunk-loaded and the majority of them are in a single chunk. I have channels disabled in the config and as far as I know nothing else is different from standard config. I am playing on a server of a custom modpack, and the server doesn't crash when this happens. Neither does client (as far as I know). 

- Minecraft Version: 1.7.10
- AE2 Version: rv3-beta-6
- Forge Version: 10.13.4.1614

Link to mods= https://www.dropbox.com/sh/6heaokbmjn3pk18/AACNpwR1rJpeJcqhj4d8bAPka?dl=0

Edit- If I rebuild the multiblock when an ME cable can connect, it pops and the blocks break. I have to rebuild the multiblock and only then can I connect it to my ME network

**Comment by mindforger** [comment]
do you have channels disabled by chance ?

**Comment by Breadabix** [comment]
I have channels disables on the server and on my client.

**Comment by mindforger** [comment]
i can remember having several issues when i tried with disabled channels ... that was the point where i adapted to the use of channels
as this feature was never really intended, more like a gap closer for 1.6 version
@yueh in my opinion this feature should be discussed again if it not already happened to be removed or be tested more firmly before porting it over to rv4 silently

**Comment by Breadabix** [comment]
Thanks for the help, will probably just adapt the system to enable channels again.

**Comment by tlf30** [comment]
Hello,
We are having the same problem, or at least I think it is the same problem, on one of my servers. Dense energy cells and crafting multi structures are randomly breaking some blocks when new blocks are being added. We have all default settings in the config.

The version I am using is rv2-stable-10. 

Thank you,
Trevor

**Comment by mindforger** [comment]
rv2 is WAY outdated, switch to rv3 beta ... it is way more coplete and debugged than rv2

**Comment by yueh** [comment]
Closing due to rv3 being no longer supported.
