### ISSUE TITLE
Crash the server when clicked on "order by" button

### ISSUE THREAD

**Issue by Susjin** [AppliedEnergistics/Applied-Energistics-2#2599]
I was playing with AE2 in my server, and i made an drive and an interface, but i didn't put any storage drives in it, then i openned the interface and clicked on that button to change the order that items apears (even if i didn't had any items in the system), and them i crashed

For some reason the log says that is something with Reliquary

Log:
http://pastebin.com/EBs8wfiR

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-5
- Forge Version: 12.18.2.2122

**Comment by yueh** [comment]
Hm, how could I miss it when fixing #2561?
