### ISSUE TITLE
Crafting Will Not Start

### ISSUE THREAD

**Issue by Ommina** [AppliedEnergistics/Applied-Energistics-2#2600]
I do not know if this is a duplicate of #2595 or not.  The symptoms are somewhat different, but they both do touch on storage drawers.

Summary: We are repeatedly unable to craft even a smallish number of items (I just had it occur with a request for 128 items -- 16 sets of 8).  The simulation _does_ complete.  The START button _does_ enable.  There is ample power available, and suitable crafting storage (without which the START button would not light anyway).

But pressing START does... nothing.  One can cycle through CPUs or cancel, but the start button is just ignored.  No messages, no return to the terminal, just nothing at all.

I am using storage drawers almost exclusively (there is a single overflow chest).  Another user on the server has a mixture of storage drawers and frequently suffers from the same "no start" problem.  But maybe it's just coincidence.

No crash or logging that I can see. 

Minecraft 1.10.2
AE rv4 alpha5
Forge 2122

**Comment by yueh** [comment]
Yes, it is a duplicate. In short every crafting request which requests more than 1 full stack from a storage drawer will fail thanks to `IItemHandler` being pretty much useless for anything but chests.
