### ISSUE TITLE
ME Terminal Crashes when the ME Network has a Storage Bus Attached to a Storage Drawer Network

### ISSUE THREAD

**Issue by Wealthyturtle** [AppliedEnergistics/Applied-Energistics-2#2601]
#### Description

ME Terminal Causes the Game to Crash. 
(When the ME Network has a Storage Bus is Attached to a Storage Drawer Network to Automate the Restocking of Materials via ProjectE Condensers.)
The Storage Bus is Sometimes Attached to an Updating Inventory (That May have been the Cause of the Crash)
Expected Behavior is for the ME Terminal to Not Crash.

#### Environment

Crashlog: [http://pastebin.com/m09gYDRt](http://pastebin.com/m09gYDRt)
Entire Modlist of the Modpack: [https://wealthyturtle.github.io/Universal-Interdimensional-Escape/modlist.html](https://wealthyturtle.github.io/Universal-Interdimensional-Escape/modlist.html)

- Minecraft Version: 1.7.10
- AE2 Version: rv2-stable-10
- Forge Version: 10.13.4.1614

**Comment by HenryFBP** [comment]
Link to world.

https://drive.google.com/file/d/0B2NiQ-5oF-x3OEE4ZHBuWDRMUHM/view?usp=sharing

**Comment by yueh** [comment]
#2452
