### ISSUE TITLE
Items cannot be extracted from Matter Condenser

### ISSUE THREAD

**Issue by Susjin** [AppliedEnergistics/Applied-Energistics-2#2602]
Exactly as the title said, i tried lots of diferent ways of extraction from this block, but nothing works

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-5
- Forge Version: 12.18.2.2122

**Comment by kingcraftingnl** [comment]
Same problem

**Comment by Susjin** [comment]
I found out that the problem is that the matter condenser does not use the new capability system for inventory, because i used the Machine Inventory Manager from Steve's Factory Manager and it worked

**Comment by allorente** [comment]
Same issue with alpha 11

**Comment by SanAndreasP** [comment]
I have to chime in and say I have the same problem. Not even vanilla hoppers work :(
