### ISSUE TITLE
Feature Request: Please allow renamed connected chest or block in ME Interface Terminal

### ISSUE THREAD

**Issue by jambaugh** [AppliedEnergistics/Applied-Energistics-2#2603]
I've tried this in older versions and it didn't work then either but would be nice.
In setting up crafting systems I would like to distinguish various devices or chest fed mechanisms so I tried to rename the relevant block (in an anvil) connected to the ME interface.  The interface as shown in the ME Interface terminal still shows the blocks default name.  It would be extremely useful it it could read the actual modified name.

Alternative to that would be to allow a new field "MEInterfaceName" be applied to blocks in the meta-data or whatever and allow that to be edited from the ME Interface Terminal. 

I apologize if this has been suggested before.  A cursory review didn't turn up any prior similar requests that I recognized.

I'm currently using versions:
- Minecraft Version:  1.10.2
- AE2 Version: rv4 alpha-5
- Forge Version: 12.18.2.2114

**Comment by XFactHD** [comment]
You can rename an interface in an anvil or with that naming thingy (forgot how it was actually called) together in the inscriber. The advantage is that you don't need xp to rename stuff.

**Comment by mindforger** [comment]
naming press, rightcklick with a quartz knife in the air, insert an iron bar, set a name, drop press in inscriber with block and then finish

**Comment by XFactHD** [comment]
Naming Press, that's what I was thinking of :)

**Comment by yueh** [comment]
#1008

**Comment by jambaugh** [comment]
Well, I feel like an idiot for not doing more research before cluttering up the hub with this non-issue.  My apologies.

**Comment by mindforger** [comment]
well the naming press is not well described ion the website so no biggie
