### ISSUE TITLE
Formation plane dropping downwards problems

### ISSUE THREAD

**Issue by Lukas45** [AppliedEnergistics/Applied-Energistics-2#2605]
#### Description
The Formation Plane sometimes have issues dropping items downwards, and most will end up on top of the plane, instead of falling down. Some do fall down as they should, but most doesn't.
With 4 Acceleration Cards on the Importer, where it should drop 3 stacks of items, only 2 stacks will fall down correctly, and the 3rd getting stuck above. With no Acceleration Cards, far most will land on top

#### Environment
Formation Plane in the ceiling, dropping stuff down into a tube of Clear Glass, down to a Annihilation Plane (no issues there)
![7e49b3d92a58f2d718c1fb67b8692e25 1](https://cloud.githubusercontent.com/assets/4707702/20239763/90962bd2-a908-11e6-8a03-c31da876d18b.png)

Above the Formation Plane. there's a few cables, with an import bus linked to a chest (which is linked to an Interface block). This is where the issue is, where it likes to drop the items on top of the Formation Plane, instead of the way it's facing.
![72d1c79148a03e999234edeb07f24a56 1](https://cloud.githubusercontent.com/assets/4707702/20239773/fdb530aa-a908-11e6-8a5d-b49478e3e4b8.png)

- Minecraft Version: 1.10.2
- AE2 Version: rv4 alpha 4
- Forge Version: 12.18.2.2122

I know it's not the latest AE2 version, but I did not see this issue mentioned either in the changelog, or on the bug tracker.

**Comment by shartte** [comment]
There has been a fix in terms of collision detection with annihilation planes, so you might want to try the latest one.
But you're right, the spawn behavior was unchanged. I might take a peek at Botania's dropper behavior, since there seems to be some funky changes to hitboxes in 1.10.

**Comment by Lukas45** [comment]
I'll try and get our server to update AE, might take a few days though (to make a bigger patch)

**Comment by shartte** [comment]
Yeah don't sweat it, i think this issue might not be fixed in the latest version yet. As I said, I'll look into it.

**Comment by Lukas45** [comment]
Aight, cool.
Cheers man

**Comment by yueh** [comment]
Looks like the y offset is too high, when spawning the items

**Comment by shartte** [comment]
@yueh You were faster than me ;-)
Would it make sense to use the entity bounding box and spawn it such that the top of the bounding box is exactly below the formation plane?

**Comment by yueh** [comment]
Would make sense, if we would not spawn an entity with a fixed size of .25. But it is only spawning them on a parallel plane offset by .5 from the formation plane. So it cannot even touch them. Maybe it would be an idea to spawn them a bit nearer to the plane. It should also not spawn them in a way, that they could clip into a wall. Spawn plane is a .7x.7 centered inside the block. So even if minecraft does not spawn them centered, it should never exceed 0.05 or .095 as min/max value for a position

**Comment by shartte** [comment]
Okay, I see that the default entity has size 0.25, 0.25
I wasn't aware of that.
I guess the chances of an Item setting a custom entity with a different bounding box are slime, but would you expect them to handle the shift in position due to a bigger bounding box themselves?

**Comment by yueh** [comment]
It is still hardcoded to `EntityItem`, so to change it, someone has to patch vanilla minecraft. Which probably causes more issue than just formation planes behaving strangely. I guess spawning an `EntityItem` will actually be the more serious issue. But as long as nothing shows up, there is no need to change it for now.
