### ISSUE TITLE
Cross-compatibility bug with TAIGA ores generation

### ISSUE THREAD

**Issue by Hypsellis** [AppliedEnergistics/Applied-Energistics-2#2606]
I link this issue here since AppliedEnergetics is involved to this issue https://github.com/Zkaface/TAIGA/issues/56. I curruntly still researsh all the other mods involved in this issue.

**Comment by shartte** [comment]
Please open an issue here when you are at least *somewhat* certain that this is an issue with Applied Energistics. Just because AE happens to be in your modlist doesn't mean it has anything to do with the actual issue. 

As I stated, feel free to reopen an issue once you have more information.

**Comment by Hypsellis** [comment]
yeah sorry for the bothering.
