### ISSUE TITLE
[1.10.2] Meteorite compass incorrectly displaying when holding it in your hand

### ISSUE THREAD

**Issue by mariot7** [AppliedEnergistics/Applied-Energistics-2#2607]
Hello,

I noticed that meteorize compass is not displaying properly as in the 1.7.10 version of the mod:

<a href="http://www.igreklik.com/slike/"><img src="http://www.igreklik.com/slike/images/45899723611977202126.png" border="0" alt="IgreKlik - Igrice online" /></a>

- Minecraft Version: 1.10.2
- AE2 Version: rv 4 alpha build 6
- Forge Version: 12.18.2.2125

**Comment by shartte** [comment]
Please define "properly" in this case. Is the pointer not pointing correctly?

**Comment by mariot7** [comment]
In the rv 3 the compass is on the right side of the screen but in rv 4 it's a bit to the left...
