### ISSUE TITLE
Terminal scroll bar registers click through JEI Recipes "+"

### ISSUE THREAD

**Issue by Lukas45** [AppliedEnergistics/Applied-Energistics-2#2608]
#### Description
When looking through recipes in JEI, and adding one to the crafting grid, clicking the "+", will also click on the scroll bar in the terminal, if the mouse is in position of the scroll bar.

#### Environment
Example:
![e2e9db108496e81197e61753cad001d9 1](https://cloud.githubusercontent.com/assets/4707702/20242599/66495ae4-a934-11e6-9984-87fe37e22fc7.gif)

- Minecraft Version: 1.10.2
- AE2 Version: rv4 alpha 4 (again, haven't seen this specific issue mentioned in changelogs)
- Forge Version: 12.18.2.2122

**Comment by Shindur** [comment]
Can confirm, this happens on the latest (rv4 alpha 5) as well
