### ISSUE TITLE
[1.10.2] ME Storage Bus not reading modded inventories

### ISSUE THREAD

**Issue by Rumpelstiltskinny** [AppliedEnergistics/Applied-Energistics-2#2610]
The ME Storage Bus is not reading inventories from [Quantum Storage Unit](https://minecraft.curseforge.com/projects/quantumstorage/files/2332869) and [Compact Chests](https://minecraft.curseforge.com/projects/compactstorage/files/2302965)

- Minecraft Version: 1.10.2
- AE2 Version: appliedenergistics2-rv4-alpha-4.jar
- Forge Version: 2107

**Comment by Meller127** [comment]
Quantum Storage is working, compact chest dont work yet. I wonder if this really is on the AE side for the compact chest.
![2016-11-13_10 51 15](https://cloud.githubusercontent.com/assets/13392710/20244797/2b9a8480-a98f-11e6-9bf5-fb5895074ab8.png)

![2016-11-13_10 48 01](https://cloud.githubusercontent.com/assets/13392710/20244789/edd32332-a98e-11e6-960b-8e7ee6ea2307.png)


Minecraft Version: 1.10.2
AE2 Version: appliedenergistics2-rv4-alpha-5.jar
Forge Version: 2121

**Comment by yueh** [comment]
#2550

**Comment by Rumpelstiltskinny** [comment]
Considering that [Refined Storage](https://minecraft.curseforge.com/projects/refined-storage/files/2332840) is able to read Quantum Storage Units (entire contents, not just the output slot) and Compact Chests properly I'd venture to guess it's an AE2 issue.
