### ISSUE TITLE
Shift-clicking in the crafting terminal can put items in off-hand slot

### ISSUE THREAD

**Issue by GuntherDW** [AppliedEnergistics/Applied-Energistics-2#2611]
#### Description
When you shift-click a crafting recipe when your inventory is full it will put the resulting item in your offhand slot (if that slot is empty).
The Crafting or terminal interface doesn't give you access to that slot which makes it so you have to exit out and remove it manually if you want to do something with it.

I don't know whether or not this is an intended change but it's kind of something that can take you by surprise if you didn't know about it, and can be irritating because the UI doesn't have a slot for that particular inventory slot.

- Minecraft Version: 1.10.2
- AE2 Version: fc834036a0a76daec3cf7d39bad383d97a11ac0d
- Forge Version: 12.18.2.2122

**Comment by yueh** [comment]
This stupid inventory handling of minecraft (read there is none)...

**Comment by fscan** [comment]
It would be easy to fix this, but i think the proper way to solve this would be to show the armore/offhand slots in the GUI.
