### ISSUE TITLE
channels not working on dense cable

### ISSUE THREAD

**Issue by glmdev** [AppliedEnergistics/Applied-Energistics-2#2615]
#### Description
My network is rather large, and I am using p2p tunnels to carry dense cable signals from my controller throughout my base. Most of the time, this works as expected. After connecting the 2 p2p tunnels, the dense cable on the remote one uses the full 32 channels (one per side of an me controller). Recently, however, I have run into an issue a couple of times where a dense cable will not accept all 32 devices. In this instance, I am trying to connect 8 more devices on a dense cable with only 8 in use, however they will not connect. 

#### Environment
I am using a custom modpack, but most notable mods are AE2, EnderIO, Thermal Expansion & friends, IC2, and Mekanism.

As far as troubleshooting goes, I have confirmed that the p2p tunnels are linked properly and no other tunnel is using the same side of the controller. I have also put a creative power cell on my me network, and have determined that this is not the cause of the issue either. I have also confirmed that the entire network is chunkloaded using ChickenChunks.

 - AE2: rv2-stable-10
 - MC: 1.7.10
 - Forge: 10.13.4.1614

Attached are screenshots. I have attached 8 other devices the exact same way, and they work fine. 

###### Non-functional devices
![2016-11-13_13 11 03](https://cloud.githubusercontent.com/assets/18516622/20248198/4b6266b0-a9a4-11e6-9317-2ba9330218c8.png)

###### Functional Devices
![2016-11-13_13 10 59](https://cloud.githubusercontent.com/assets/18516622/20248197/4b613e7a-a9a4-11e6-9f8c-dfd3b508c361.png)

###### Remote Dense Cable coming out of p2p
![2016-11-13_13 10 51](https://cloud.githubusercontent.com/assets/18516622/20248199/4b670dbe-a9a4-11e6-81ff-31850d9d3b41.png)

###### P2P on the controller side (the orange dense cable under the crosshair)
![2016-11-13_13 10 30](https://cloud.githubusercontent.com/assets/18516622/20248200/4b66fc48-a9a4-11e6-948c-f055fd166f43.png)

**Comment by shartte** [comment]
rv2 is no longer supported. You might try rv3 and see if the problem persists.
