### ISSUE TITLE
Needs another mod but doesnt show what it needs

### ISSUE THREAD

**Issue by hpiracing46** [AppliedEnergistics/Applied-Energistics-2#2618]
#### Description

Ok i didnt know how to add this before now i do. so every time i have the mod in my minecraft folder and start up the game, it says that "AE2 doesnt have the mods it depends on to work download the mods or remove it" something like that and doesnt show the mod it depends on and i dont know if this is a bug or not.
#### Environment

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-6 
- Forge Version: 12.18.2.2099

**Comment by shartte** [comment]
Neither your Forge nor your AE2 version are the *actual* versions. You just specified the Minecraft version.

**Comment by hpiracing46** [comment]
oh. im dumb...

**Comment by hpiracing46** [comment]
@shartte ok i have fixed that little issue by specifying the mc version

**Comment by shartte** [comment]
Please update your Forge version, we require 12.18.2.2104
