### ISSUE TITLE
AE2 Lagging server

### ISSUE THREAD

**Issue by Eufranio** [AppliedEnergistics/Applied-Energistics-2#2619]
Using AE2 rv3-beta-6 on my server, in about 30mins the server starts lagging. WarmRoast report:
https://github.com/AppliedEnergistics/Applied-Energistics-2/files/577074/WarmRoastReport.zip

- Minecraft Version: 1.7.10
- AE2 Version: rv3-beta-6
- Forge Version: 1614

**Comment by yueh** [comment]
#2495
