### ISSUE TITLE
Installing Applied Energistics while running SpongeForge prevents startup

### ISSUE THREAD

**Issue by Orcinuss** [AppliedEnergistics/Applied-Energistics-2#2620]
I wasn't sure where to post an issue so ill make one in both.

#### Description

Install Applied Energistics on a server with SpongeForge prevents startup. The server stops loading and crashes with the message:
An essential class was loaded before Sponge could patch it, this usually means that another coremod has caused the class to load prematurely.

#### Environment

Running Direwolf20 1.10.2 Pack v1.0.0
Applied Energistics rv4-alpha-5
Forge v12.18.2.2124
SpongeForge v1.10.2-2123-6.0.0-BETA-1878
Multiplayer Server MC 1.10.2

Crash log: http://pastebin.com/HayMrXN7

**Comment by shartte** [comment]
Duplicate of #2482
