### ISSUE TITLE
Make craft processor work with IAEStack

### ISSUE THREAD

**Issue by Dimach** [AppliedEnergistics/Applied-Energistics-2#2622]
Now craft processor work only with IAEItemStack, but there a possibility to make it work with any type of stack (fluids for example). This will require not a lot of changes and I can help with writing most part of code (via pull request).
Major update is best time to do this.
I can write more detailed description if you interested.

**Comment by yueh** [comment]
#1917

**Comment by Dimach** [comment]
Okay. A year has passed... So can i help with this part??
