### ISSUE TITLE
Facades brighter than normal blocks

### ISSUE THREAD

**Issue by Susjin** [AppliedEnergistics/Applied-Energistics-2#2625]
Screenshots:
http://imgur.com/a/KivwJ

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-6
- Forge Version: 12.18.2.2122

**Comment by yueh** [comment]
Probably related to the cables themself being not a full block/not blocking light. Not sure if we can trick the rendering into it, but @shartte should be the one being able to answer it.

**Comment by shartte** [comment]
Yeah, this will be tricky to do with model based rendering. I'll see what we can do.
