### ISSUE TITLE
Issues with ME Terminals' UIs

### ISSUE THREAD

**Issue by Xiaminou** [AppliedEnergistics/Applied-Energistics-2#2627]
#### Description
1. Mouse scroll does not scroll down the list of items when.
2. Shift + Right-click does not give a single item like it used to in 1.7.10.
3. JEI Integration: JEI doesn't tell you if you're missing the items or not. Althought I don't know if it can even do that. with AE.

#### Environment
[list.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/614353/list.txt)

- Minecraft Version: 1.10.2
- AE2 Version: alpha 6
- Forge Version: 2125

**Comment by yueh** [comment]
Cannot reproduce anything. (Or it never existed like 3)

**Comment by Xiaminou** [comment]
So are you saying it's mod interaction bugs?

**Comment by snacdaws** [comment]
may i add that u can no longer shift+scroll to pull items out of the me system (it worked on older 1.10.2 alpha's 1,2,3)

**Comment by avix133** [comment]
In version 1.12.1 there are still both 2 and 3 issues.

**Comment by mindforger** [comment]
This issue is closed and 1 year old, make a new issue and reference this one but don't skip the versions used and the modlist
