### ISSUE TITLE
certus seeds not growing correctly

### ISSUE THREAD

**Issue by nightstalker91** [AppliedEnergistics/Applied-Energistics-2#2628]
I tend to throw alot of seeds in a puddle and have a hopper with sorting circuit pull the finished ones out but I threw a stack and a half in and 3 grew 2 don't stack but show no change and the rest don't do anything. I can get them to grow by continuously picking up the ones that don't grow and throwing them again repeatedly with varying amounts growing each time. I have tried with and without accelerators ,i use just 4 accelerators, and it is the same either way.
I am using: 
Minecraft 1.10.2
appliedenergistics2-rv4-alpha-6
forge-1.10.2-12.18.2.2122
jei_1.10.2-3.13.0.332
mcmultipart-1.2.1-universal
inventorytweaks-1.61-58
improving minecraft-1.12.1
biomesofplenty-1.10.2-5.0.0.2068
and a bunch of other mods total mod count is 67 i think.
it is a single player world.

**Comment by yueh** [comment]
Works fine for me. Can you eliminate any mod interaction causing it?

**Comment by nightstalker91** [comment]
I will take all other non mods out and try as soon as my girlfriend let's me on the computer and get back to u

**Comment by yueh** [comment]
It might be already enough to remove the hopper. Not sure how it operates, but it is certainly possible that the pick up the item, compare it and spit it back out should it not match and so prevent the seeds from being able to actually grow.

**Comment by nightstalker91** [comment]
Looks like it was the hopper which is weird because it's vanilla hopper and I was able to use a omnidirectional hopper when I was playing on 1.7.10 guess there must be something different about how it checks for matches. Thanks for all the help and the speed of the responses I'm going to see if I can come up with a different way to automate it or maybe find the mod with the omnidirectional hoppers if it has a 1.10.2 version

**Comment by shartte** [comment]
Stupid check: Can you stand on the hopper and see what F3 says regarding your Y position in relation to the block?

**Comment by yueh** [comment]
I tested it earlier and it did not work one time. So maybe a rounding issue with their location. Maybe not only related to y but also x/z as they were in one corner.

**Comment by nightstalker91** [comment]
It's like when u make a chicken farm u have have to put carpet over hoppers or chicken might glitch into hopper space I think as for my y if in center of hopper it is 64.625 on edge it is 65

**Comment by GuntherDW** [comment]
Yeah, hoppers, kinda like botania mana pools have an inner circle that has a small indent that makes you drop a little bit below the block. Thus breaking the "sight" for the accelerators.

**Comment by shartte** [comment]
I recently changed our check for "is this in water" regarding seeds.
It's now checking in the middle of the item hitbox, which if i remember correctly is 0,25 units high. 
So in this case, if your water block is at y=65, the seed being at y < 64.875 means it wont grow.

**Comment by yueh** [comment]
I do not see any real solution for it, except starting to let the seeds float. Which breaks other solutions (like the AE2 based ones). 

So we will probably lose the pure vanilla one compared to 1.7.10. But I doubt many will actually pick this one.
