### ISSUE TITLE
Some cable parts not rendering on client.  Sometimes.

### ISSUE THREAD

**Issue by Ommina** [AppliedEnergistics/Applied-Energistics-2#2630]
OK, I don't know how to best describe this other than by offering a picture:

http://imgur.com/a/ctuyd

The 90 degree cable on the left, and the horizontal cable on the right, are simply not interested in rendering on the client.  It is not limited to a single client, but affects three different players equally (and I'm going to check with a fourth when I'm able).  If I try to interact with the missing cable, I get the block behind it.

The cable _does_ exist on the server.  If I attempt to place a block in either location, it is not placed, and the block is returned to inventory.  Additionally, the export bus to the left is online, functions, and the "i have a channel!" line on the cable is lit.

Optifine is not installed, but certainly have other mods installed that fondle rendering.

And here is a list of installed mods and the "prompt for computer specs to be printed" that is created at startup: http://pastebin.com/HShDkdY4

SMP.  I do have a backup of the world.
MC 1.10.2
jre1.8.0_101
Forge 12.18.2.2122
rv4 alpha6

Edit:

Copied the world to single player.  The cable bits do not render in single player either, but!, if I try to place a block in one of the affected locations, I get the following crash: http://pastebin.com/fGqtL8Pk

The crash features Mekanism at the top of the stack trace, followed by AE.  I broke the Mekanism TE (cables did not appear), quit to title, restarted, and cables DID return.

I feel I should close this as Mekanism issue, but I'll leave that to more knowledgeable minds than mine.

**Comment by yueh** [comment]
Are there any stacktraces in the server log? It might be a bit more fault tolerant there and just break the synchronisation instead of crashing.

**Comment by shartte** [comment]
Hm... It looks like the cable is rendering as if it was connected to an adjacent tile. Will have to investigate in more depth.

**Comment by Ommina** [comment]
Nothing in either the server logs, nor the client console.  I even checked to ensure DebugLogging was set to true, just in case.

@shartte The cables _are_ connected to other cables in the (what seems to be) empty blocks.  The cables are there, but the client seems to know nothing about them.

**Comment by Ommina** [comment]
Followup.

I've had this recur twice tonight.  In both cases, it was with tiles on the diagonal of a Mekanism machine.  However, in neither case was it AE affected: they were Ender-IO conduits instead.

With that in mind, I'm going to close this as "not AE2".
