### ISSUE TITLE
Disable channels in settings will delete controllers and not allow to craft one

### ISSUE THREAD

**Issue by SubsterNL** [AppliedEnergistics/Applied-Energistics-2#2631]
Switching AE2 to no channel (in config) will on world load delete your controllers and not allow you to craft them.

1.10.2 Alpha 6 (same as what happened in alpha 5, do not know if this was an issue before).

**Comment by mindforger** [comment]
that is well known (use the search, it is known since it was implemented in 1.7.10 due to people having a hard time to adapt), you don't need controllers without channels at all and to craft the QNB you need to modify he recipe on your own, the channel disable feature was never fully developed. @yueh this is what i meant in the other topic :) this feature has either to be developed to a point where it is "switch on and go" or ahs to be removed completely

**Comment by yueh** [comment]
It is fully developed, just some approaches we take for a better performance or network use do not work well without channels due to exceeding the used datatypes.

But otherwise it is correct.

**Comment by mindforger** [comment]
>It is fully developed

this includes alternate recipe set for the QNB in my opinion, or did i miss the recipe?

**Comment by yueh** [comment]
This includes it working. Nothing else. If someone wants to change the default config, they have to take care of the rest themselves. That is why you can modify all AE2 recipes. We simply cannot provide a recipe set for every permutation of 70 or more config options.

**Comment by mindforger** [comment]
are there more options alternating the recipes???

**Comment by yueh** [comment]
You can disable dense cables, or the inscriber or whatever else. I would even go as far and say if you cannot disable a block/item currently, then it is a bug. And to some degree also features like the crystal purification (which is optional). Ideally you should be able to strip down AE2 and just use it for the grindstone, if you want.

**Comment by mindforger** [comment]
wow O_o i have never dug so deep in the config, funny but understandable now.

**Comment by SubsterNL** [comment]
Thanks for clearing this up. And thanks for making the most incredible Minecraft mod ever available in 1.10.2. 

For me, channels is a god send, I was just trying to disable it until I got relocated to a void dimension.

But I love the channel mechanics. Shame algoX got so much grief over it and glad you guys are sticking with it. :)
