### ISSUE TITLE
Typing in terminal and then moving the mouse (deliberate or not) over the contents part will invoke the special hotkeys 'U , 'R'etc

### ISSUE THREAD

**Issue by SubsterNL** [AppliedEnergistics/Applied-Energistics-2#2634]
Typing in terminal and then moving the mouse (deliberate or not) over the contents part will invoke the special hotkeys 'U , 'R', etc...

So trying to search an item it will sometimes shift focus to the JEI special windows (crafting recipes etc).

Hope I described it clear enough. 

Would be helpful that once you are in the search box the focus on it will remain, even though the mouse moved (without any clicks)

1.10.2  R3-Alpha 6 of AE2
Latest forge and FTB unstable like modpack through MultiMC but all mods updated

**Comment by yueh** [comment]
Nothing we can do, JEI intercepts the keypresses before we can even handle them.
