### ISSUE TITLE
Placing a charger crashes the server.

### ISSUE THREAD

**Issue by sharkck** [AppliedEnergistics/Applied-Energistics-2#2635]
#### Description
I placed a charger and the server crashed upon placement.  I have the complete logfile, the except from that log file, and the crash report.

#### Environment
See log files below
[crash-2016-11-18_03.39.28-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/599415/crash-2016-11-18_03.39.28-server.txt)
[fml-server-3.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/599420/fml-server-3.txt)
[Logfile.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/599416/Logfile.txt)

- Minecraft Version: 1.10.2
- AE2 Version: rv4 alpha-6
- Forge Version: 12.18.2.2125

**Comment by sharkck** [comment]
And the same thing just happened when placing the inscriber.  (note, everything loads back up fine when the server starts back up.  Thankfully!)
Here are the logfiles from placing an inscriber:
[crash-2016-11-18_03.55.02-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/599436/crash-2016-11-18_03.55.02-server.txt)
[fml-server-latest.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/599435/fml-server-latest.txt)

**Comment by yueh** [comment]
Can you please reproduce it without any other mod? The code path is actually not possible with only AE2.

**Comment by mindforger** [comment]
@yueh if you `LinkedList.add(null)` this could possibly be a thing or am i wrong? But i was not able to trace all possible sources now where a null could possibly ne added

**Comment by yueh** [comment]
There are only 2 calls to it and both are guarded against null.

**Comment by mindforger** [comment]
yeah i see it now, this one is very very odd :)

**Comment by sharkck** [comment]
Updated the server to Forge 2147, plus updated 
`Forge 12.18.2.2125 --> 12.18.2.2147
Actually Additions r71 --> r74
Baubles 1.3.3 --> 1.3.5
BetterThanBunnies 1.0.3 --> 1.1.0
Biomes O Plenty 5.0.0.2094 --> 5.0.0.2096
Botania r1.9-337 --> 338
Cavern v1.5.1 --> 1.5.2
Chameleon 2.1.7 --> 2.1.8
CyclopsCore 0.8.0 --> 0.8.1
Endertanks 1.4.4 --> 1.4.5
EvilCraft 0.10.14 --> 0.10.15
Forestry 5.2.16.326 --> 5.2.16.327
HardcoreWither 2.1.3v9fa0986 --> 2.2.1va5c7aff
JEI 3.13.3.372 --> 3.13.3.377
JER 0.5.4.68 --> 0.5.7.87
Morpheus 3.1.9 --> 3.1.12
Platforms 1.2.3 --> 1.2.4
QuantumStorage 3.2.10 --> 3.2.11
RandomThings 3.7.6 --> 3.7.7
RFTools 5.60 --> 5.61
ShadowMC 3.5.0 --> 3.6.0
Steves Factory Manager Reborn 1.0.7 --> 1.0.8
Storage Drawers 3.4.4 --> 3.4.6
Thuttech 4.0.9 --> 4.0.10
Thutcore 3.7.2 --> 3.8.0
Vampirism 1.0.2 --> 1.0.3`
and the problem seems to have gone away.  I spawned in a few other AE2 items and placed them and there weren't any issues that I could see.
