### ISSUE TITLE
Me Terminal derpy

### ISSUE THREAD

**Issue by 016Nojr** [AppliedEnergistics/Applied-Energistics-2#2637]
When I try to extract or change any settings in a ME Terminal nothing happens. The buttons update but the "storage interface" doesnt update.

#### Environment
Playing on a multiplayer server with the Direwolf 1.10.2 pack version 1.0.0 (Modlist: https://www.feed-the-beast.com/projects/ftb-presents-direwolf20-1-10/relations/dependencies)

- Minecraft Version: 
- AE2 Version: rv4-alpha-5
- Forge Version: 12.18.2.2124

**Comment by leelawd** [comment]
We are experiencing this same issue, Unable to retrieve items from the interface and the buttons act in the same way as stated above.

The configuration is similar. We are also running  Direwolf20 1.10.2 - 1.0.0
