### ISSUE TITLE
ME System Duplicates all Items

### ISSUE THREAD

**Issue by Hellhound732** [AppliedEnergistics/Applied-Energistics-2#2640]
#### Description 

My current setup for an ME system involves a storage bus leading into an Ender-Rift (from the Ender-Rift mod), and every time I attempt to take something out of my system, even with the wireless terminal, it takes the item out in a stack of however many of that item there is. I get stacks of 200k cobblestone, and it doesn't let me place it back into the system because it is too large of a stack, so I have to manually place it back in the system 20 stacks at a time. Also, when I place items back into the system, they are duplicated. Not just the items themselves, but the stack. So when I place a 1000 stack, it turns into 2k of that item. Ender-rift version is 2.0.0, and I don't have optifine installed, if either of those help.
#### Environment

- Minecraft Version: 1.10.2
- AE2 Version: appliedenergistics2-rv4-alpha-6
- Forge Version: 12.18.2.2151

**Comment by yueh** [comment]
#2626
