### ISSUE TITLE
Using JEI "+" in pattern terminal destroys items

### ISSUE THREAD

**Issue by Xiaminou** [AppliedEnergistics/Applied-Energistics-2#2645]
#### Description
https://youtu.be/eo7PmLtobuY

#### Environment
[list.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/614353/list.txt)

- Minecraft Version: 1.10.2
- AE2 Version: alpha 6
- Forge Version:

**Comment by yueh** [comment]
Cannot reproduce.

**Comment by Tsukiumy** [comment]
just to add, it seem only some itens are destroyed, in this case the covered cable, gets destroyed, and in this recipe in specific

**Comment by yueh** [comment]
Most likely duplicate of #2626.
