### ISSUE TITLE
ME auto crafting system gets stuck at scheduled after 100 channels on system

### ISSUE THREAD

**Issue by mitcharoni12** [AppliedEnergistics/Applied-Energistics-2#2646]
I have channels turned off so everything is running on 1 wire and after 100 channels on the system all crafting gets stuck at scheduled

#### Description
AE version 0.5.0.56
I have an auto crafting system and whenever I exceed 100 channels on the system everything except the drives shut down, all the crafting, import and export buses, it's like the entire system is frozen or the tick rate doesn't work or something. playing on crack pack 1.7.10 on my server. don't know why it's doing this. I also have channels disabled in the config.

- Minecraft Version: 1.7.10
- AE2 Version: 0.5.0.56
- Forge Version: 7.10.99.99

**Comment by bookerthegeek** [comment]
Turning channels off was a stopgap for 1.6.X to 1.7.X 

Not really supported.  Can you reproduce with casuals turned on?

**Comment by mitcharoni12** [comment]
what are casuals?

**Comment by bookerthegeek** [comment]
Channels

Stupid phone autocorrect

**Comment by mitcharoni12** [comment]
well, I can't because if I do turn channels the system will not work because of all the channels on 1 wire. if I do turn it on I need to redo my me system

**Comment by bookerthegeek** [comment]
That was sorta the point.

**Comment by yueh** [comment]
That is not a valid AE2 version.

**Comment by mitcharoni12** [comment]
I'll probably just switch my system to channels, didn't know about tunneling with p2p channels and everything, won't be that bad. thanks for the help.
