### ISSUE TITLE
Wired interface to autocrafting broken, wireless terminal works fine (in dimension)

### ISSUE THREAD

**Issue by tekacs** [AppliedEnergistics/Applied-Energistics-2#2647]
In an RFTools dimension, interacting with the AE system in the overworld works fine, crafting works fine from a wireless terminal - but trying to craft from any wired, static terminal causes problems.

#### Description
Setup:
* Quantum Network Rings in the overworld and in the dimension.
* Wireless Access Point, pattern terminal, crafting terminal, interface terminal [connected like this](https://cloud.githubusercontent.com/assets/63247/20500828/ffaa25be-b02e-11e6-97ce-6a66648f935d.png) in the dimension.
* The overworld is chunkloaded to cover the entire AE system and its subsidiaries.

Working cases:
* Using a wireless terminal in the dimension, I can access items, initiate autocrafting and see crafting status fine.
* Using the interface terminal in the dimension, I can see and manipulate recipes in everything, including all of the molecular assemblers.
* Using any wired or wireless terminals for any purpose in the overworld works fine.

Broken cases:
* If I attempt to *initiate* any kind of autocraft only from the wired pattern or crafting terminals, the interface GUI closes itself - no error appears in the server console or in the client interface.
* If I attempt to *see crafting status* in the wired pattern or crafting terminals, the server crashes (but the client does not) with this crash log: https://gist.github.com/tekacs/c97c33a91a1f1ef51e9305db540f656a - seemingly crashing on [this line](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/6554e295d592d795fa7a0b7c8320bb4245237f2c/src/main/java/appeng/container/implementations/ContainerCraftingStatus.java#L55)
* This also applies if I extend any of the cabling and put down a new terminal, or replace the existing ones. This persists across crashes/restarts.

#### Environment
All The Mods pack, version 1.46 (https://mods.curse.com/modpacks/minecraft/242462-all-the-mods)
Running in multiplayer with a server.

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-6
- Forge Version: 12.18.2.2125

**Comment by yueh** [comment]
It does call `detectAndSendChanges()` on an invalid container. Should clearly not happen and I cannot remember it ever happen with 1.7.10. Maybe mojang changed the order of updating a container and checking it for a valid one with 1.10?

**Comment by JelmarG** [comment]
Related to [2347](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2347) perhaps?

**Comment by wiviw5** [comment]
I have also had this same problem in 1.7.10 with ae2 rv3 beta 6 Kicks me out of the game when I click on the crafting status and cannot autocraft as it kicks me out of the terminal but works fine in a wireless terminal no useful logs.
