### ISSUE TITLE
JEI crash when moving onto AE page

### ISSUE THREAD

**Issue by TheDarkFlame** [AppliedEnergistics/Applied-Energistics-2#2648]
When scrolling through JEI, pages containing some AE2 items (not sure which ones) causes a crash.

#### Description
When entering JEI  and browsing through the JEI item pages, page 4 caused system to hang then crash. This was found by browsing both ways through the JEI item pages.
Upon removing AE2, normal JEI behavior returns, with no hanging and then a crash.
Submitted this here because mod is in alpha, and the bug existed for this mod only, leading me to think AE2 might be causing the issue instead of JEI. 
If this bug is in the wrong place, say so and I'll post it over at JEI

#### Environment
Bug exists in both SP and MP.
A large number of other mods are installed, with JEI{3.13.3.382} being the most relevant, see linked pastebin crashlog (from SP) for list of all mods.
http://pastebin.com/B6SirVcT

- Minecraft Version: 1.10.2
- AE2 Version: alpha rv4-alpha-6 for Forge 12.18.2.2104
- Forge Version: forge1.10.2-12.18.2.2151

Edit: just found the port to 1.10 project, and this bug might have something to do with
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2375

**Comment by yueh** [comment]
The usual "Do not use optifine".

**Comment by TheDarkFlame** [comment]
Apologies for wasting your time. Yes, optifine is the issue.
