### ISSUE TITLE
Press Conversion

### ISSUE THREAD

**Issue by eLION119** [AppliedEnergistics/Applied-Energistics-2#2649]
#### Description
I currently on a single player world have yet to find any Silicon presses in all of about 7 meteors, but i have found multiple engineering, calculation, and logic presses.

My suggestion is that there be a way to convert presses at the very least.
For recipes, as far as i'm concerned my best crafting solution is to have shapeless recipes of all 3 presses that you have make the 1 you don't have, or with a little bit of work possibly some way of using the inscriber to make a blank press or to change the press and if going the blank press route some other item to create the press.

**Comment by mindforger** [comment]
this was rejected countless times, you can add your own recipes if you mind, using crafttweaker for example

**Comment by yueh** [comment]
Even possible with AE2 [custom recipes](http://ae-mod.info/Custom-Recipes/), no need for anything else.

But otherwise that is the downside of playing a game based on RNG. Sometimes you might get all presses in one. The other time it takes more than 2 or 3. To which we even point directly.
