### ISSUE TITLE
AE2 Channels on The One Probe 

### ISSUE THREAD

**Issue by LewisHolt** [AppliedEnergistics/Applied-Energistics-2#2650]
WALIA/WAWLA etc has the ability to show current channels in use when looking at a cable but I've noticed that the one probe doesn't. With the one probe gaining popularity this would be an awesome feature. I asked the creator of TOP (McJty) but he said to contact you guys. :)

Hopefully you consider this request. 

Thank you. :)

**Comment by McJty** [comment]
Interfacing with TOP is not hard. There is a tutorial here: http://modwiki.temporal-reality.com/mw/index.php?title=API_TOP-1.9

Many big mods (Tinkers Construct, Immersive Engineering, ...) already implemented TOP support

Thanks

**Comment by yueh** [comment]
At some point certainly (should it not introduce a hard dependency).

If you want it now, feel free to take the WAILA integration as example and create a PR.
