### ISSUE TITLE
Fluix Crystal Crash

### ISSUE THREAD

**Issue by Sletoon** [AppliedEnergistics/Applied-Energistics-2#2652]
#### Description
Minecraft keeps chrashing when I'm interacting with a crafting table, chest, furnance, etc. by having an fluix crystal in my inventory and by typing "fluix" in the NEI searchlist

PS: Sorry for my bad english, it's WIP... ;)

#### Environment

- Minecraft Version: 
- AE2 Version: 
- Forge Version:

**Comment by VT-14** [comment]
Please post your crashlog (in a GitHub Gist [top of this page] or another text dump site, like Pastebin). Also fill out the rest of the form and specify Minecraft, AE2, and Forge versions.

**Comment by Sletoon** [comment]
The MC Version is 1.7.10, the AE2 Version is [rv2-stable10 ](http://www.mediafire.com/file/t5eeb0n03jzwku7/appliedenergistics2-rv2-stable-10.jar)and the Forge Version is [Forge 1.7.10-10.13.4.1158](http://www.mediafire.com/file/mjdn9zqqpwcin30/forge-1.7.10-10.13.4.1558-1.7.10-universal.jar)

You can get the Latest log [here](http://www.mediafire.com/file/4uiznj6va9pnrgd/latest.log)

**Comment by mindforger** [comment]
rv3-beta is much more stable than rv2 and forge is also VERY outdated, 1614 is the current best working build
