### ISSUE TITLE
Item P2P Tunnels not transferring

### ISSUE THREAD

**Issue by Grygon** [AppliedEnergistics/Applied-Energistics-2#2653]
#### Description

I have [this setup](http://imgur.com/a/wq7xc) for p2p tunnels which should, in theory, be working fine to transfer the items from the hopper to the chest through the two connected item P2P tunnels.

#### Environment

Using:
appliedenergistics2-rv4-alpha-5
ae2stuff-0.6.0.5
All other mods should be irrelevant, but can be found on the [dw20 modpack site](https://www.feed-the-beast.com/projects/ftb-presents-direwolf20-1-10/relations/dependencies).

Tested in SP in both an existing setup an a new, creative setup.

- Minecraft Version: 1.10.2
- AE2 Version: appliedenergistics2-rv4-alpha-5
- Forge Version: forge-12.18.2.2124

**Comment by shartte** [comment]
Will try this out as soon as I can to confirm.

**Comment by yueh** [comment]
I am not sure, if hoppers even work as the tunnels are still using the old inventory system and hoppers might be patched to only use an item cap.

Regardless they should be changed to an `IItemHandler` to make it easier. Maybe also some QoL improvments.

**Comment by Xiaminou** [comment]
so I take it fluid P2P are not working right now?

**Comment by ken-noland** [comment]
yeah, fluid p2p not working in my build either

**Comment by ken-noland** [comment]
I'm using appliedenergistics2-rv4-alpha-11.jar

**Comment by yueh** [comment]
Should be fixed it 1.12.
