### ISSUE TITLE
Entities become invisible after been transported with spatial IO

### ISSUE THREAD

**Issue by Frosky01** [AppliedEnergistics/Applied-Energistics-2#2654]
#### Description
After transporting entities back form a spatial storage cell all entities become invisible (mobs and items entities), you can still pickup items but can't interact with mobs

#### Environment
Only tested in SP

- Minecraft Version: 1.10.2
- AE2 Version: appliedenergistics2-rv4-alpha-6
- Forge Version: forge-2.18.2.2125

**Comment by yueh** [comment]
No idea why, maybe they are not correctly registered to the renderer after being moved?

**Comment by mindforger** [comment]
**optifine** and **betterPVP** installed possibly ? they had an issue with chunk updates and entities and players disappearing

**Comment by Frosky01** [comment]
Probably, because if you reload the world they reappear. And also if you go with the entities to the pocket dimension they render correctly.
I'm using the Direwolf20 1.10 pack with no optifine or betterPVP. I'll try to test in a clean install of just AE2

**Comment by ZombieWeeD** [comment]
Im having this same ishue now in direwolf20 1.10 pack (hevily modified) as well.

i also tested to see if it was a conflict by running a test pack with only ae-2 installed as a mod.  i tested it in multiple 1.10.2 forge versions. they are ending in 2185, 2202, and 2221. 2185 is the recomended version 2221 is the lattest version.

what setup do you use when you build the mod (what version of forge for example) to get this feature working if i can figure out what setup works for you when your building it maybe i can get it to work right.

**Comment by fscan** [comment]
I cannot reproduce this in the current version. If it's not fixed for you please reopen.
