### ISSUE TITLE
Ore Dictionary button missing in Pattern Terminal

### ISSUE THREAD

**Issue by JTLWebDesign** [AppliedEnergistics/Applied-Energistics-2#2656]
We recently updated our Technic Modpack to latest versions of most of our mods and now that we are in our new pack, one of our players has noticed the Button for the Ore Dictionary in the Patter Terminal is missing. I built a setup myself and confirmed it is not there for me as well. 

Our server is running MC 1.7.10, Thermos 1.7.10-1614.58, Forge 1.7.10-10.13.4.1614-1.7.10-universal, and we are running AE2 RV2-stable-10. 

After looking at our old server, I saw it was running AE2-RV3-beta-6. Is this the reason for the issue with the button being there? If so, I can update our server but we were trying to stick with only Stable releases of mods on this pack to reduce various issues on our old pack.

**Comment by mindforger** [comment]
rv2 is WAY less stable that rv3

**Comment by JTLWebDesign** [comment]
Ok, thank you for the fast reply!!! I didn't realize rv3 was more stable. I was just looking at the Stable vs Beta tags when building our new pack (this was the first time I assembled a pack so I was trying to be cautious but now that I know, I will be updating to RV3 tonight. Thanks again!!!
