### ISSUE TITLE
Licence Agreement for Item Textures

### ISSUE THREAD

**Issue by StanleyMines** [AppliedEnergistics/Applied-Energistics-2#2658]
In the licence, I see no mention of "texture", "art", "images", or "artwork". (Could someone point me to where the licence for the textures is?)

I am making (a) mod(s), and I would like to use and/or modify some textures for the mod(s).

@Cisien @FireBall1725 @thatsIch @yueh May I use the textures?

(The FAQ page has:
"Can I use this in my private/public mod pack?
Yes, don't ask for permission. For proof send people to this FAQ."
But I assumed that was talking about the mod in a mod pack, I am asking about using this mod's assets/textures in my own mod.)

Thanks, StanleyMines.

**Comment by VT-14** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2#license

**Comment by thatsIch** [comment]
Also keep in mind, that you do not want to confuse the user and use the same texture in wrong context. Like using the texture of the terminal for something which is not terminal related.

**Comment by StanleyMines** [comment]
Thanks VT. I see now that textures are under a CC licence.

(I am aware of that, thatsIch. Thanks.)
