### ISSUE TITLE
Network Tool does not remove facades when shift+right-click

### ISSUE THREAD

**Issue by Xiaminou** [AppliedEnergistics/Applied-Energistics-2#2659]
#### Description
https://youtu.be/UgAUamrDoig

#### Environment
[list.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/614353/list.txt)

- Minecraft Version: 1.10.2
- AE2 Version: alpha 6
- Forge Version: 2125

**Comment by yueh** [comment]
#2623
