### ISSUE TITLE
[Feature Request] Underground Biomes Constructs compatibility

### ISSUE THREAD

**Issue by mankra** [AppliedEnergistics/Applied-Energistics-2#2663]
Minecraft version: 1.10.2

The mod Underground Biomes Constructs replaces the vanilla stone with different stone types like rhyolite, soapstone, marble etc. As these different stone types contain the ores, the textures of the ores have to be changed when UBC is installed. UBC provides an API for this task.

Short: Please make certus quartz ore fit the UBC stone textures.

**Comment by yueh** [comment]
They do not seem to provide a maven repo with an api artificat, which is a prerequisite. Also it looks like the plan to merge the old compat plugin from 1.7.10 into the 1.10 version in some way.
