### ISSUE TITLE
Please Fix: system lockup when power is lost and restored

### ISSUE THREAD

**Issue by Tcll** [AppliedEnergistics/Applied-Energistics-2#2665]
I'm using the latest 1.7.10 version on Xubuntu 14.04, no channels or inscriber.

There's no doubt this is a power loss issue, but I'm reporting this because I have to use a Redstone clock to unlock the network after it locks until I can build more solar-expansion panels for it.

The network should automatically resume when it receives power.

Please do not tell me to add dense energy cells, this is a bug that should be fixed, not ignored.

**Comment by XFactHD** [comment]
Does your network already have energy cells to be able to store at least as much energy as the network consumes? How much does your network need? How much energy are the solar panels supplying to the network? How big is the network?

**Comment by Meller127** [comment]
I have the same issue on 1.10.2 when Power is lost i have to break the disk drives and insert all the disk again to acces all the items.

**Comment by XFactHD** [comment]
@Meller127 the exact AE2 version, Forge version and screenshots would be nice.

**Comment by Meller127** [comment]
Forge: 2151
AE2: Alpha 7

This is my complete ME setup, Energy Acceptor -> Disk Drive -> Crafting Terminal. Every time Power is lost i have to break the disk drive and re insert the disks.
![2016-11-30_15 45 51](https://cloud.githubusercontent.com/assets/13392710/20756765/3a2ab924-b714-11e6-9f5b-a6a959586212.png)

You can se in the bottom that the disks is used and powered and no items.
![2016-11-30_15 48 32](https://cloud.githubusercontent.com/assets/13392710/20756827/79d8a2b6-b714-11e6-891d-b4e79201a6fe.png)

**Comment by Meller127** [comment]
No crazy chunkloading going on, dont have any ;)

**Comment by XFactHD** [comment]
@Meller127 You may want to open a new issue for that as it is another MC version and seems to be a completely different issue.

**Comment by yueh** [comment]
We do not support the 1.7.10 any longer, due to missing time.

**Comment by Tcll** [comment]
F-ing dangit!
I'm working on a modpack limited to this version due to mod support specifics.
(One of my major mods in the pack is magical crops beta 13a for the charms and armor design)

Well...
I understand, if you ever get enough complaints, will you consider fixing it then? :)

**Comment by XFactHD** [comment]
@Tcll would have been awesome if you answered my questions, then there would at least be a chance to tell you if this is really a bug or just a limitation that causes the system to take really long to boot.

**Comment by Tcll** [comment]
Sorry, lol, it's using about 512rf/t and currently I only have 2 (making more) resonant panels connected to it.

I have an inverted toggle bus connected to the cable coming from the energy acceptor with a clock and a lever connected to it...

The clock unlocks it for crafting ticks, the lever turns it off to recharge.

**Comment by XFactHD** [comment]
How much do resonant solar panels produce?

**Comment by Tcll** [comment]
512rf

I'm sorry, my system uses many times more than that, it locks when running out of power while still being supplied power, and yes, it does resume when enough power is supplied.

Why doesn't it just go black when running out, instead of staying on??

**Comment by Tcll** [comment]
To give you a good estimate on the size of my network (besides saying it uses a good amount of power), I have Compact Machines with 5 nether-star rooms filled with specific layouts:

- auto-farm
- smelting factory
- interfacing
- super-crafter
- nether farm 

The auto-farm and smelting factory rooms are linked to the interfacing room (it's how I get 1 planter to plant all my magical crops seeds when requested via autocrafting).
Same goes for my smelting factory.

The super-crafter is just a bunch of rftools crafters, with a few mekanizm assemblicators for processor crafting  (stupid quartz cutter).

And i intend to have even more rooms, such as for crafting storage cells and co-processors...
So yea, it's pretty massive.

**Comment by XFactHD** [comment]
I think the problem is that the time needed to boot a network rises with its size and because power runs out very often, AE might be turning down the tick rate of the network to save server resources. Be aware that this is just a guess as I am not familiar with AE's source code. You could try adding some dense energy cells to work around this.

**Comment by Tcll** [comment]
This was really just a bug report since the network is misinforming me...
Initially I thought it was receiving enough power just to find out it wasn't shutting off...

I already know I have to add more panels and have been working on it since the initial post.
I've added 5 electrum panels which seems to be stabilizing it, but that doesn't fix the bug which led me to assume my network was fine. ;)
(It's a lack of needed information that's the problem)

**Comment by mindforger** [comment]
you should still add some energy cells, they act as buffer to comensate power surges

**Comment by Tcll** [comment]
As I add solar panels, the buffer gets larger ;)

To add, the buffers provided with the panels are more informative I do believe...

The last time I used cells, I couldn't get an amount of rf stored and had to rely strictly on their color...
I'm never doing that again.

**Comment by mindforger** [comment]
external buffer != internal buffer 

just a simple demo, you deliver 1000RF/t , your baseline is 100RF/t but a large crafting recipe requires **for one single tick**  1200RF ... your buffer runs dry and the system shuts down ... **on the next tick** it boots again, your recipe is aborted and your system stalls until rebooted

additional internal buffers are **ALWAYS** required!

**Comment by Tcll** [comment]
I don't have the loss of recipe problem...

I can completely disconnect my panels and not have to worry about losing my recipe...

Btw, I'm keeping track of rf/t
Nothing outputs more than solar expansion ultimate solar panels grouped with universal cable to a p2p bus, unless you get into those stupid reactors :P

You can Google how much rf/t each panel generates and even how much their buffers store.

When you group them, it really makes dense energy cells a bit pointless, unless you like battery backup...

**Comment by mindforger** [comment]
please read again my comment, because if you did, you would probably get the point of your bottleneck beeing the maximum RF you can **INSERT** to the system in **ONE TICK** vs the power demands of an ME system in **ONE TICK** beeing very high sometimes, especially when doing big crafting jobs!
