### ISSUE TITLE
Issues with EU and RF p2p tunnels in 1.10.2

### ISSUE THREAD

**Issue by Valkyrinn** [AppliedEnergistics/Applied-Energistics-2#2667]
#### Description

After placing an ME P2P Tunnel, I can set the mode the fluid, items, light, or redstone, but right-clicking with an IndustrialCraft cable does not set it to EU mode. If I cheat in the EU mode P2P Tunnel, it connects and works fine. There is no RF version in my game, so I can't connect my Ender IO conduits to it.

#### Environment

I'm playing the Direwolf20 1.10 pack on single player. I tried making a pack with just the latest versions of AE2, IC2, Ender IO, and forge, but that didn't fix the issue.

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-5
- Forge Version: 12.18.2.214

**Comment by yueh** [comment]
Looks like IC2 changed the item names, so the attunements are wrong. Will be fixed.

But there is simply no RF tunnel.

**Comment by Valkyrinn** [comment]
If you don't mind me asking, why was the RF tunnel feature removed?

**Comment by Ommina** [comment]
@Valkyrinn See #2522

**Comment by HIghCommander540** [comment]
This is still an issue! I am unable to attune to RF using EnderIO conduits.
