### ISSUE TITLE
Putting Storage Cells in the I/O Port disconnects from server

### ISSUE THREAD

**Issue by Xiaminou** [AppliedEnergistics/Applied-Energistics-2#2668]
#### Description
Shift-clicking storage cells in the I/O Port causes a fatal error from time to time.
23:58:28: [fml-server-latest.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/623235/fml-server-latest.txt)

#### Environment

- Mods: [list.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/623239/list.txt)
- Minecraft Version: 1.10.2
- AE2 Version: alpha 7
- Forge Version: 2135

**Comment by yueh** [comment]
There is nothing related to AE2 in the log.

**Comment by Xiaminou** [comment]
Any idea what might be the problem then?

**Comment by mindforger** [comment]
net.dries007.**holoInventory**.network.response.PlainInventory.toBytes(PlainInventory.java:87) ~[PlainInventory.class:?]
