### ISSUE TITLE
[Sponge] Applied Energistics 2 MixinErrorHandler

### ISSUE THREAD

**Issue by micheldewit** [AppliedEnergistics/Applied-Energistics-2#2677]
As title suggest: 
We are using Sponge for our plugins (protection etc). However, we have concluded (After 3 hours of testing with other mods) that for some reason Applied energistics isnt playing nice with Sponge. We concluded the following: 
Applied Energistics loads before Core Mods can do their Mix ins. 

As Sponge has to patch blockloading properties, this is causing the server NOT to start. 

Errorlog is attached in zipfile. 

Is there a quickpatch to make AE2 work with Sponge? We love AE2, but we dont want to lose our plugins. 
[fml-server-latest.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/626551/fml-server-latest.zip)

**Comment by bookerthegeek** [comment]
@micheldewit Please use the search function next time.

**Comment by chazwarp923** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2482

**Comment by bookerthegeek** [comment]
Yes their is, you need to compile the denied PR into a custom source. NO SUPPORT Given if you use this.
