### ISSUE TITLE
Facades facing East and North are rendering the wrong block face

### ISSUE THREAD

**Issue by Xiaminou** [AppliedEnergistics/Applied-Energistics-2#2679]
#### Description
![2016-12-04_16 02 12](https://cloud.githubusercontent.com/assets/8670392/20867052/ec9cd0ae-ba3b-11e6-9cce-d3878e5ac167.png)
![2016-12-04_16 06 16](https://cloud.githubusercontent.com/assets/8670392/20867053/ec9e5672-ba3b-11e6-8c20-38618684f601.png)
![2016-12-04_16 12 21](https://cloud.githubusercontent.com/assets/8670392/20867077/745729a4-ba3c-11e6-8cd6-b5bb79932b5f.png)
![2016-12-04_16 13 15](https://cloud.githubusercontent.com/assets/8670392/20867083/93363284-ba3c-11e6-882c-cff32421bc89.png)

#### Environment
- Mods: [list.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/629596/list.txt)
- Minecraft Version: 1.10.2
- AE2 Version: alpha 8
- Forge Version: 2135

**Comment by yueh** [comment]
Also bottom

**Comment by Jarpiino** [comment]
5 months later still having the same problem with Basalt Brick facade, only in the bottom side. Annoying to see them vice versa on the roof.

FTB Beyond 1.5.3
Applied Energistics 2 rv4-alpha-11

![screenshot_2](https://cloud.githubusercontent.com/assets/28261664/25581446/90d76350-2e90-11e7-873a-23c8ec0fcbc5.png)
Facades in middle

**Comment by Xiaminou** [comment]
Yup, it never got fixed, for some reason...
