### ISSUE TITLE
Cable Anchor visible throught facades

### ISSUE THREAD

**Issue by Xiaminou** [AppliedEnergistics/Applied-Energistics-2#2680]
#### Description
When moving around you can see cable anchors flickering through facades
![2016-12-04_16 08 28](https://cloud.githubusercontent.com/assets/8670392/20867068/46db126a-ba3c-11e6-97e5-f8afbdb51461.png)

#### Environment
- Mods: [list.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/629596/list.txt)
- Minecraft Version: 1.10.2
- AE2 Version: alpha 9
- Forge Version: 2135

**Comment by yueh** [comment]
And the usual "without Optifine?".

**Comment by Xiaminou** [comment]
Yes, happens without Optifine too.

**Comment by yueh** [comment]
Cannot really reproduce it, the anchors are by default 1 pixel shorter than the actual block, so there should be no way to have them z-fight with the texture.

**Comment by Xiaminou** [comment]
Reproduced easily enough with only AE2 (on a server): https://youtu.be/6C4dqEqM-I8

**Comment by yueh** [comment]
Ah you mean actual cable anchors and not the cable anchor part of facades.

They can start to z-fight, but using a anchor and facade on the same side is not really providing anything useful. Thus instead of modifying the renderer, it might be a better option to let anchors block facades on that side.

**Comment by Xiaminou** [comment]
Well, without getting into the debate of what's useful and what's not I can tell you that in my years of playing with AE2 I have come up with dozens of situations where I wanted both facade and anchor on the same side. Like the one on my screenshot, where I want to hide some cables and leave some other visible in front of those first cables, but they should not connect hence the cable anchor.

**Comment by VT-14** [comment]
Other ways to not connect those cables:
A) Cable Anchors attached on the cable outside of the facade
B) Paint the cables different colors.

**Comment by Xiaminou** [comment]
I'm afraid your assumption that I wouldn't know about these 2 methods is wrong. And the point of this thread is not to find a work-around but to report an issue and potentially find a fix for said issue.

**Comment by VT-14** [comment]
Well, pardon me for trying to help.  In spite of your somewhat rude reaction, I'm going to keep trying to help.  Ha!

While I agree with yueh that it doesn't really add anything useful (as there are other ways to keep those separate), I do have to admit that keeping facades + cable anchors a thing makes more sense than removing them (and by extension, fixing the z-fighting would probably be a good idea).  Facades can be applied concurrently with any other cable part.  Making anchors the only exception would be somewhat weird.

Consistency would also suggest fixing the z-fighting so the end of anchor is visible on the facade, but the only use for anchors in this context would be cosmetic separation of cables, so I would say not showing them on the facade does make more sense.

**Comment by mindforger** [comment]
i just want to calm you down and tell you that this most likely beeing an issue of mod interaction ... in early 1.7.10 it was jabba, creating rendering issues and z-fighting over very much mods ... in the mid time of 1.7.10 there was an update to carpenters doing the same

what you have to do now is **reproduce this in a new world**, reduce the mods until it vanishes

**Comment by yueh** [comment]
It is an issue of the normal vanilla renderer as there are 2 parts overlapping. The facade and anchor.

Anchors are already a special case, as there are pretty much the only part not changing the facade into a hollow one as well as the only part fitting on a dense cable. Thus to be consistent, they should really be visible. Especially as it is needed to remove them again.

**Comment by Xiaminou** [comment]
@mindforger please read the older posts before replying, I posted a video of me reproducing it with pretty much only AE2.

@VT-14 I don't see how I was any rude, merely pointing out facts.

**Comment by leagris** [comment]
Z-Fighting is ugly. There is no reason to keep this as-is but solutions like: rendering a 1/8 shorter anchor when a facade is attached to it. Another option is offsetting the tip end face of the anchor 1 px inward or removing that face altogether.
