### ISSUE TITLE
Facades let light through

### ISSUE THREAD

**Issue by Xiaminou** [AppliedEnergistics/Applied-Energistics-2#2683]
#### Description
![2016-12-05_17 37 18](https://cloud.githubusercontent.com/assets/8670392/20893379/d9a73c7e-bb11-11e6-8c46-e9dfb495adbf.png)
![2016-12-05_17 37 47](https://cloud.githubusercontent.com/assets/8670392/20893380/d9a7ae0c-bb11-11e6-8b4c-7eab144d7c76.png)
![2016-12-05_17 37 49](https://cloud.githubusercontent.com/assets/8670392/20893378/d9a71bd6-bb11-11e6-972b-8f3a0281c26a.png)

#### Environment
- Mods: [list.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/629596/list.txt)
- Minecraft Version: 1.10.2
- AE2 Version: alpha 8
- Forge Version: 2135

**Comment by yueh** [comment]
This might be a limitation by minecraft itself. As a single block cannot be the same in regards to opaque and transparent.

**Comment by Xiaminou** [comment]
I can't recall if they blocked light in 1.7.10.

**Comment by leagris** [comment]
They did like partial blocks do (slab, stairs).

**Comment by yueh** [comment]
Yes, they were always transparent as it is a limit with minecraft itself. 1.10 seems to have some new things which may make it possible to tie it to the blockstate. But I would not count on it, maybe we revisit it again. But for now we keep the 1.7.10 behaviours.
