### ISSUE TITLE
Mass Crafting Fluix Crystals does not consume correct amount of Charged Certus

### ISSUE THREAD

**Issue by Savallator** [AppliedEnergistics/Applied-Energistics-2#2684]
Hi,
when crafting huge amounts (like 8+ stacks) of fluix crystals at the same time (by Shift-Dragging them out of the Inventory), there are charged certus left over. 
Lets say I am crafting 16 stacks, using 8 stacks of each charged certus, nether quartz and redstone, then most of the time it crafts the expected amount, but leaves like 2 charged Certus in the puddle of water.
I am playing on a Server, so it might be a latency problem. It happens consistently every time i craft these amounts.
- Minecraft Version: 1.7.10
- AE2 Version: rv2-stable-10
- Forge Version: 1.7.10-10.13.4.1614
Big modpack of other mods, but i suppose they have nothing to do with that. I can test it in pure AE if needed, but i suppose there is someone who already has a testing environment set for this.

**Comment by mindforger** [comment]
can you pick them up?

are you using sponge or thermos/cauldron?
there are plugins, especially the spigot code to merge items dropped on the ground into combined stacks that may interact.

**Comment by Savallator** [comment]
I can pick them up, they are not Phantom items.
I have no such plugins.
Here is a list of my mods as extracted from the filenames:
`1.7.10_AM2-1.4.0.009.jar
AgriCraft-1.7.10-1.5.0.jar
AnimationAPI-1.7.10-1.2.4.jar
AOBD-2.9.2.jar
appliedenergistics2-rv2-stable-10.jar
Aroma1997Core-1.7.10-1.0.2.16.jar
Aroma1997s-Dimensional-World-1.7.10-1.1.0.1.jar
AromaBackup-1.7.10-0.1.0.0.jar
Automagy-1.7.10-0.28.2.jar
Avaritia-1.11.jar
bdlib-1.9.4.109-mc1.7.10.jar
BiomesOPlenty-1.7.10-2.1.0.1889-universal.jar
BloodMagic-1.7.10-1.3.3-17.jar
Botania r1.8-249.jar
BrandonsCore-1.0.0.11.jar
buildcraft-7.1.14.jar
buildcraft-compat-7.1.3.jar
Carpenter's Blocks v3.3.7 - MC 1.7.10.jar
carpentersblocks
ChickenChunks-1.7.10-1.3.4.19-universal.jar
Chisel-2.9.4.10.jar
ChromatiCraft 1.7.10 V16d.jar
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
CoFHCore-[1.7.10]3.1.3-327.jar
CoFHLib-[1.7.10]1.1.1-181.jar
ComputerCraft1.75.jar
Decocraft-2.2.1_1.7.10.jar
Draconic-Evolution-1.7.10-1.0.2-Snapshot_9.jar
DragonAPI 1.7.10 V16d.jar
ElectriCraft 1.7.10 V16d.jar
EnderCore-1.7.10-0.2.0.31_beta.jar
EnderIO-1.7.10-2.3.0.t3_beta.jar
EnderStorage-1.7.10-1.4.7.37-universal.jar
EnderTech-1.7.10-0.3.2.405.jar
EnderZoo-1.7.10-1.0.15.32.jar
ExtraCells-1.7.10-2.3.9b188.jar
ExtraTiC-1.7.10-1.4.5.jar
extrautilities-1.2.12.jar
Factorization-1.7.10-0.8.107.jar
FastLeafDecay-1.7.10-1.4.jar
Forbidden Magic-1.7.10-0.575.jar
generators-0.9.20.123-mc1.7.10.jar
gregtech-5.09.25.jar
Guide-API-1.7.10-1.0.1-20.jar
Hats-4.0.1.jar
HatStand-4.0.0.jar
Headcrumbs-1.7.4.jar
iChunUtil-4.2.2.jar
IguanaTinkerTweaks-1.7.10-2.1.6.jar
ImmersiveEngineering-0.7.3.jar
immersiveintegration-0.6.7.jar
industrialcraft-2-2.2.826-experimental.jar
INpureCore-[1.7.10]1.0.0B9-62.jar
InventoryTweaks-1.59-dev-152.jar
ironchest-1.7.10-6.0.62.742-universal.jar
Jabba-1.2.1a_1.7.10.jar
journeymap-1.7.10-5.1.4-unlimited.jar
logisticspipes-0.9.3.95.jar
Mantle-1.7.10-0.3.2b.jar
mcjtylib-1.8.1.jar
MineFactoryReloaded-[1.7.10]2.8.1-174.jar
MineTweaker3-1.7.10-3.0.10B.jar
MobiusCore-1.2.5_1.7.10.jar
ModTweaker2-0.9.5.jar
Morpheus-1.7.10-1.6.21.jar
mystcraft-1.7.10-0.12.3.01.jar
natura-1.7.10-2.2.0.1.jar
neiaddons-1.12.14.40-mc1.7.10.jar.disabled
NEIIntegration-MC1.7.10-1.1.2.jar.disabled
NotEnoughItems-1.7.10-1.0.5.118-universal.jar
OpenBlocks-1.7.10-1.5.1.jar
OpenModsLib-1.7.10-0.9.1.jar
OpenPeripheralAddons-1.7.10-0.5.1.jar
OpenPeripheralCore-1.7.10-1.3.jar
OpenPeripheralIntegration-1.7.10-0.5.jar
Opis-1.2.5_1.7.10.jar.disabled
Pam's HarvestCraft 1.7.10Lb.jar
PlanetguyLib-1.9.1.jar
PortalGun-4.0.0-beta-6.jar
PortalGunSounds.pak
ProjectRed-1.7.10-4.7.0pre12.95-Base.jar
ProjectRed-1.7.10-4.7.0pre12.95-Compat.jar
ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar
ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar
ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar
ProjectRed-1.7.10-4.7.0pre12.95-World.jar
Railcraft_1.7.10-9.12.2.0.jar
ReactorCraft 1.7.10 V16d.jar
RedstoneArsenal-[1.7.10]1.1.2-92.jar
RemainInMotion-2.8.9.jar
rftools-4.22.jar
RotaryCraft 1.7.10 V16d.jar
runicdungeons-1.1.6a.jar
SimplyJetpacks-MC1.7.10-1.5.3.jar
SolarExpansion-Basic-1.6a.jar
Springboards-1.7.10-0.1.jar
StevesAddons-1.7.10-0.10.16.jar
StevesCarts2.0.0.b18.jar
StevesFactoryManagerA93.jar
StevesWorkshop-0.5.1.jar
TConstruct-1.7.10-1.8.8.jar
Thaumcraft-1.7.10-4.2.3.5.jar
thaumcraftneiplugin-1.7.10-1.7a.jar
thaumicenergistics-1.0.0.5-RV2.jar
ThaumicExploration-1.7.10-1.1-53.jar
ThaumicTinkerer-2.5-1.7.10-512.jar
ThermalDynamics-[1.7.10]1.2.0-171.jar
ThermalExpansion-[1.7.10]4.1.4-247.jar
ThermalFoundation-[1.7.10]1.2.5-115.jar
TiCTooltips-mc1.7.10-1.2.5.jar
TMechworks-1.7.10-0.2.15.106.jar
Translocator-1.7.10-1.1.2.15-universal.jar
TravellersGear-1.7.10-1.16.6.jar
twilightforest-1.7.10-2.3.7.jar
Waila-1.5.10_1.7.10.jar
WailaHarvestability-mc1.7.10-1.1.6.jar
Wawla-1.3.3-1.7.10.jar
witchery-1.7.10-0.24.1.jar
WitchingGadgets-1.7.10-1.1.10.jar
WR-CBE-1.7.10-1.4.1.9-universal.jar
`
