### ISSUE TITLE
Have to remove and replace drive after power loss

### ISSUE THREAD

**Issue by dshadowwolf** [AppliedEnergistics/Applied-Energistics-2#2685]
Losing power to the network can cause ME Terminals and ME Crafting Terminals to not find any items stored in connected drives.

#### Description

A creeper explosion damaged the power line feeding from some solar cells (Solar Flux Reborn) to the Energy Acceptor. This break was not noticed (it was the only line actually broken)  and the energy cell maintaining the start of my ME Network went dry.

After I noticed and fixed it, the Crafting Terminal I had claimed there was nothing in the network, but the drive (sitting on top the controller) and storage elements said otherwise. Finally removed the drive, put it back in place and put the cells back in and the system worked again.

This was repeatable, though I have not yet attempted to replicate with Build 8, as I've only just learned that was released. 

#### Environment

This was not a hard crash, so a crashlog is not available - although I did have a client crash soon after this event, the issue with the terminal not showing items and the client crash are likely not connected.

- Minecraft Version: 
- AE2 Version: rv4-alpha-7
- Forge Version: 12.18.8.2151 (client), 12.18.8.2166 (server)
(version difference was because of a touch of laziness on my part - I hadn't bothered to update the client side code I was using)

**Comment by yueh** [comment]
#2666
