### ISSUE TITLE
Coremods pre-loading with AE2

### ISSUE THREAD

**Issue by kulflame** [AppliedEnergistics/Applied-Energistics-2#2686]
First off I want to give a sincere apology if this "issue" shouldn't be posted here.  

AE2 provides conflicts when trying to load SpongeForge and is a known issue on the SpongeForge forums.  I do not know of the relationship between mod devs and plugin devs but sometimes we like to add plugins to servers.  

I just want to make the issue known.  Not sure if anything could even be done about it.

http://pastebin.com/GekkAN0P

**Comment by bookerthegeek** [comment]
Duplicate of https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2482
