### ISSUE TITLE
duplicate items

### ISSUE THREAD

**Issue by azbh111** [AppliedEnergistics/Applied-Energistics-2#2688]
I make a video when the player duplicate items.    
https://youtu.be/tmsDiSbH6ys
but sorry,I don't know the detailed steps.
the left mc is his ME system
the right mc is his inventory
the ME system:
![image](https://cloud.githubusercontent.com/assets/18545310/20969517/3d7b1906-bcc4-11e6-8974-bc2d4c27385a.png)
the item
![image](https://cloud.githubusercontent.com/assets/18545310/20970104/e7e62384-bcc6-11e6-8f21-79945ee43c49.png)
mods and plugins are the same with  #2655 
two bugs in #2655 are fiexd

**Comment by azbh111** [comment]
Who can reproduce it.  :)
@mindforger

**Comment by yueh** [comment]
As already stated, we no longer support 1.7.10. Especially without any way to reproduce something.

**Comment by azbh111** [comment]
take 32 Singularity as an example:
steps:
1.make sure the ME system can only hold up to 32 Singularity .
2.put 64 Singularity into a ME system with ME Pattern Terminal.  ( Shift+LeftClick)
result:
There are 64 Singularity  in the ME system,but the Singularity in the your inventory did not decrease

the video
https://youtu.be/_I-zs2bXADk

**Comment by azbh111** [comment]
i have found out the steps.
take 32 diamonds as an example.
1.make sure the ME system can only hold 32 items  (full)
2.open ME Pattern Terminal
3. shfit left click 33 diamonds (more than 32)  in your inventory
result:
there are 32 diamonds in ME system,but diamonds in inventory are not decreased

it works in 1.7.10,but not work in 1.10.2
are you going to fix it?

**Comment by mindforger** [comment]
so shift clicking items will insert as much as possible but fail to insert due to full inventory 

resulting in the inventory to not beeing taken **anything** while the system updates as if it had recevied the items

**Comment by azbh111** [comment]
it was fiex in #2312

**Comment by mindforger** [comment]
nice to know ... i rally need to write down those fixes to get myself a safe 1.7.10 version XD if the final release will not happen
