### ISSUE TITLE
I can't click on the Me Export/Import/Storage bus

### ISSUE THREAD

**Issue by quinten501** [AppliedEnergistics/Applied-Energistics-2#2691]
# I can't click on the Me Export/Import/Storage bus

I clickt meny times end i can't chance it

- Minecraft Version: 1.7.10
- AE2 Version: appliedenergistics2-rv2-stable-10
- Forge Version: 10.13.4.1614

**Comment by VT-14** [comment]
Taking a shot in the dark, you need to smack your friend for placing a security terminal down for wireless  access and didn't think to set your permissions (at least not the physical changes to the system permission) using a biometric card.
