### ISSUE TITLE
Energy Acceptor not accepting energy when using a specific setup

### ISSUE THREAD

**Issue by Rewyn** [AppliedEnergistics/Applied-Energistics-2#2694]
See referenced issue regarding what's the problem, as well as under which circumstances it's tested.
Edit; apparently I'm too stupid to reference the actual issue, so here's a link.
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1248

- Minecraft Version: 1.7.10
- AE2 Version: rv3.beta build 6
- Forge Version: 1614

This is using the Revolution 3 Modpack, in both SSP and SMP.
Problem also persists, if only using ae2, DragonAPI, RoC and NEI. Only tested for SSP in the minimalist environment.

**Comment by yueh** [comment]
Sorry, but we will no longer update the 1.7.10 version.

**Comment by Rewyn** [comment]
Alright, fair enough. Guess it's not exactly an issue you'll regulary run into.
