### ISSUE TITLE
Storage Bus not detecting inventory of Mekanism Bin

### ISSUE THREAD

**Issue by whitenite72** [AppliedEnergistics/Applied-Energistics-2#2697]
#### Description

Placed a storage bus on a mekanism bin. Expected to see its inventory. Did not see its inventory.

#### Environment

Mekanism 9.2.1.295

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-8
- Forge Version: 12.18.3.2185

**Comment by yueh** [comment]
Since forge added `IItemHandler` as common way to interact with any inventory, we no longer support custom or the old options. This will should true for many other mods as most are moving to only support them in the future or have already dropped support for old inventories.
