### ISSUE TITLE
Pause Terminal Updates, or passive sort

### ISSUE THREAD

**Issue by AlgorithmX2** [AppliedEnergistics/Applied-Energistics-2#27]
In extremely active systems items can change position and move around constantly, some sort of way to prevent this would be nice.

Originally Posted by AlgorithmX2

This issue was migrated; For original details see http://ae-mod.info/Tracker/0299/

**Comment by Jack-McKalling** [comment]
(copied suggestion from duplicate issue)

A new button could be added to the terminals, named "Sort frequency". It would have two modes: "Always sort items" or "Sort items once". This setting would be saved per player. The button would be complementary to the sorting mode and sorting direction buttons.

Sorting items once would allow the player to freeze the positions of items in the terminal. This way even when the network runs out of an item, it doesn't cause the entire grid of items to shift but simply keeps its cell empty. Any item types that become newly available to the network, do appear in their appropriate sorting position while the GUI is opened, but will maintain their new positions during this mode. Item stacksizes are never affected, and will keep being updated each unit of time regardless of the setting.

If set to "once", the gui will sort item positions once only when the grid of items is initially presented or when the sorting settings change. If set to "always", the gui will always update item positions as the network contents change on each unit of time (the current behaviour).

**Comment by l-ricardo** [comment]
(Extracted from #5987)
When HOLDING SHIFT prevents terminals from updating the positions of items. Useful when we are using SHIFT+CLICK to pick up some item but the terminal is configured to sorted by amount and items that I'm trying to get keep changing position, solves what was asked in #27.

**Comment by Hazmatik** [comment]
Not sure if this is the exact issue here but it would be solved by this suggestion.

I have noticed that in 1.18.2 when I search in the terminal for an item then go to shift+click an item out when pressing shift with Advanced Tooltips enabled all of a sudden more items are displayed moving the item you were trying to click and causing you to click the wrong item.
