### ISSUE TITLE
Illuminated Panels forget to emit light? after server restart

### ISSUE THREAD

**Issue by sharkck** [AppliedEnergistics/Applied-Energistics-2#2700]
Basically, when I restart my server, half, some or most of the illuminated panels I'm using for lighting forget to emit light until I destroy one (or all) of them in the affected areas.

Currently running rv4 Alpha 7 on Forge 2166.

There isn't a crash log or anything else that I can provide other than screenshots showing the issue.

![2016-12-12_00 57 30](https://cloud.githubusercontent.com/assets/960552/21089489/71f8a4e2-c006-11e6-92b6-10ff7e4b30b1.png)
![2016-12-12_01 01 08](https://cloud.githubusercontent.com/assets/960552/21089493/7af7ed96-c006-11e6-84f5-d2ea0fdfed99.png)
![2016-12-12_01 01 29](https://cloud.githubusercontent.com/assets/960552/21089501/8777c3a2-c006-11e6-9391-144cce0cb4db.png)

**Comment by yueh** [comment]
Is this a single chunk?

**Comment by sharkck** [comment]
No.  It's across multiple chunks.  Pictures 1 and two are on two opposite sides of the room.  Certain spots between were out (like just 1 or 2 lights vs a whole area as represented above.  I can show you more specifically with more screenshots... just would need to restart the server again.

**Comment by yueh** [comment]
Each one. With the angle it is hard to tell, but it really looks about 16 block long and the square shape really makes no sense with normal lighting behaviour. Like it actually looks like a single chunk did get reset somehow.

If it is reproducible, please provide a full server log. It might contain some error entries,

**Comment by sharkck** [comment]
Recorded two videos with the chunk map up showing a minor case and after restarting the server, it was a major case.

Video 1: https://www.youtube.com/watch?v=vDXb6umYM4Y
Video 2: https://www.youtube.com/watch?v=w6_5u_5DycY
[first vid logfile.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/656115/first.vid.logfile.txt)
[second vid logfile.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/656114/second.vid.logfile.txt)

I'm also attaching the client logfile (did not restart client b/t server restarts).  Also, this only shows up after a server restart.
[fml-client-latest.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/656117/fml-client-latest.txt)

**Comment by sharkck** [comment]
Would like to add that YES the server really thinks there's no light in those areas.  Just had two creepers spawn and blow up on me while I was working on patterns.

**Comment by sharkck** [comment]
Would like to give another update.  Just updated to the latest version of AE2 (Alpha 9) on forge 2185 and the same thing happens.

**Comment by CraftMinerKyle** [comment]
Did you know that there is a Vanilla lighting glitch that occasionally chunks will NOT light up properly, and to fix this error you can simply place a block that emits light and the glitch is fixed? This is likely NOT your issue, but I am just throwing that out there.

**Comment by CraftMinerKyle** [comment]
Yeah, after watching those videos, I kinda think that the error is actually not AE2, but actually Minecraft itself. I can replicate this error myself without ANY mods, but I mostly see this around lava pools in unloaded chunks. It is a chunk loading error, and there isn't anything AE2 DEV's can do about it.

**Comment by CraftMinerKyle** [comment]
Hey! You know how I said that I could replicate this glitch in vanilla? Well, I just did. I was mining along in survival and came to an unloaded lava pool. Here are the pictures.
![2017-04-20_12 25 34](https://cloud.githubusercontent.com/assets/22898072/25244250/8c4d4db4-25c5-11e7-8fa1-f5e9b012e4a8.png)
![2017-04-20_12 25 37](https://cloud.githubusercontent.com/assets/22898072/25244258/937d5f70-25c5-11e7-9f20-b6e2b0dfa50a.png)
![2017-04-20_12 25 52](https://cloud.githubusercontent.com/assets/22898072/25244265/96fdc4f0-25c5-11e7-9f19-166646858014.png)
![2017-04-20_12 26 07](https://cloud.githubusercontent.com/assets/22898072/25244268/99623726-25c5-11e7-9b5c-bf513befbeae.png)
The 4th image is after I updated the chunk.

**Comment by sharkck** [comment]
Ok, that's all fine... but this doesn't change the fact that regular torch lighting NEVER does this.  Whatever type of light AE2 provides seems to be the type that bugs out on server reboots.  Why cant it be changed to match the way a torch works so that this does not happen?  Also, if that's not an option, cant the AE2 controller send out a chunk 'ping' or something that forces the entire AE2 network to respond thus making sure this doesn't happen?

**Comment by CraftMinerKyle** [comment]
To be honest, I was thinking that if AE2 is causing this problem in it's own unique way, that it is missing a function that, like you said, checks all lighting objects connected to AE2 Systems. I doubt that is the issue, but If it is, the solution should just be as simple as adding a few lines of code for checking light sources. The fact that it is repeating is curious, but is not unheard of to me.
