### ISSUE TITLE
Some items cannot be taken out of storage by players

### ISSUE THREAD

**Issue by dshadowwolf** [AppliedEnergistics/Applied-Energistics-2#2702]
I have not tested further than the mod combination found to trigger this, but with TCon 2.6.1, "Tinkers Tool Leveling" 1.0.1 and AE2 rv4-alpha-8 on Forge 12.18.3.2185 any TCon tool that has been leveled cannot be removed from the storage system manually. 

Setting up an export bus with a "fuzzy" card can export them from the system.

#### Description

Put a TCon tool with a level greater than 1 in an ME storage system. You can not take it back out via a terminal. Using an Export bus with the "fuzzy" card you can export it to a chest or other non-AE2 storage for retrieval.

#### Environment
Mods Involved:
Tinkers' Construct:  2.6.1
Tinker Tool Leveling: 1.0.1
AE2: rv4-alpha-8
Forge: 12.18.3.2185
SMP and SSP both
Minecraft: 1.10.2

No crash, just an interfacing issue

**Comment by yueh** [comment]
Cannot reproduce.

**Comment by dshadowwolf** [comment]
Will try to simplify and find exact conditions. Was able to reproduce locally in both Single and Multiplayer, but might have been more than just tool level - I had only looked at tool level at the time.

**Comment by jarquafelmu** [comment]
I don't know the exact cause but I also have experienced this issue on my server. I am unable to remove a Tinker's Pickaxe at the comfortable tool level.

**Comment by RareBeast** [comment]
Had this happen to me today in Forever Stranded.   Couldn't remove my TiCon Shovel from the system.  Mod pack does not have tool leveling in it.

Worked around problem by removing all the storage cells from the drive and then putting them back in (not sure if same order).  After that I was able to take the shovel out again.

**Comment by elijahlorden** [comment]
Had the same issue, RareBeast's solution fixed it.

**Comment by operinko** [comment]
RareBeasts workaround helped, had the same issue on version 1.29 of Enigmatica 2 modpack, couldn't take out an autocrafted 64k storage cell from the system before taking out and replacing each and every one of the 50 storage cells in my drives.
I suppose I could've just taken out and put the cell containing the item, but having no clue which one contains it... :D

**Comment by thorsummoner** [comment]
Ugh, So RareBeast's motion of re-plugging all the hard drives does work for me too. can whatever code this triggers be added to the computer poweroff/poweron cycle? It would be far easier to unplug and replug the whole storage array networks, or reboot the entire computer than to manually yank/stuff every drive on a growing network. Please <3

**Comment by SomewhatDamaged** [comment]
Keep having this happen on FTB Revelations with the AE2 storage cells. The above kludge works.

**Comment by fscan** [comment]
Please not that that issue is for an old version. I don't know hat version Revelations has, but this should not happen with recent versions.

**Comment by taveric** [comment]
I can confirm I have experienced this same issue with appliedenergistics2-rv5-stable-11. I couldn't pull out 64k storage cell from the system. I pulled out each individual storage cell and place in a me chest to remove. Also noticed issue when multiple 64k storage cells are in the system such as showing the wrong amount. Also not being able to craft 64k cells until removing the recipe from the interface and replacing.

**Comment by fscan** [comment]
this is a special issue with storage cells and is fixed in dev

**Comment by douglasg14b** [comment]
Seeing this with some 16k and 64k storage cells, and an Extra Cells 1024k cell. They are just stuck in the ME system and players can't take them out.

Applied Energistics 2 rv5-stable-11

**Comment by raymondbh** [comment]
Can confirm this with FTB Revelation 3.2.0
