### ISSUE TITLE
AE2 and sponge dislike each other

### ISSUE THREAD

**Issue by hugeblank** [AppliedEnergistics/Applied-Energistics-2#2710]
#### Description
I was looking through 1.10.2 mods, and found AE2 had been updated. In a rush of excitment, I went to go install it on my sponge server. It crashed...
#### Environment
-RAM:
Mem:         32066      
Swap:         1021
-CPU
       description: CPU
       product: Intel(R) Xeon(R) CPU E3-1245 V2 @ 3.40GHz
       vendor: Intel Corp.

As implied above, I was attempting to load a multiplayer server.
[Here](http://pastebin.com/yHzr5Hv6) is the crash log with -DfmldebugExit set to true

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-9
- Forge Version: 12.18.3.2185
- Spongeforge Version: 2171-5.1.0-BETA-2000

**Comment by bookerthegeek** [comment]
Duplicate 
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2482
