### ISSUE TITLE
Fluix Crystal Creation + Annihilation Plane Interaction

### ISSUE THREAD

**Issue by EternalDeiwos** [AppliedEnergistics/Applied-Energistics-2#2711]
# Description
I have two separate networks which I use to automate the production of pure crystals and theoretically it should also work to create Fluix crystal. The first network provides the necessary items to the formation plane and the second network is configured to only accept fluix crystals or any of the complete pure crystals. The annihilation plane is situated below the block of water (if that is relevant).

The system works for the creation of pure crystals, and unlike #2547, the fluix crystals do form over the annihilation plane; however they are not collected and put into storage; you have to manually pick them up first.

I tried putting fluix crystals through the formation plane that I had on me (not newly created) and the annihilation plane handled that fine. This only seems to be happening directly after the combination of the ingredients to create fluix crystal.

# Environment
First noticed on MP, problem persists in SP. This was using Direwolf20's 1.10.2 Pack (1.1.4). There are no other mods involved in the build so I figured I didn't need a new instance with just AE2 installed.

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-8
- Forge Version: 12.18.2.2171

**Comment by yueh** [comment]
Annihilation planes will lock themselves for up to 6 secs once they are not able to store any item into the network. (Technically even longer, but that is not the default)
Mostly for a performance reason to not have them try to insert hundreds of items every tick and failing each time.

**Comment by EternalDeiwos** [comment]
I was about to comment that I tried it again and it worked and that the issue seemed intermittent but this:
> Annihilation planes will lock themselves for up to 6 secs once they are not able to store any item into the network. 

sounds like good explanation of the behaviour I was seeing. I *might* have been a bit impatient in my prior testing :sweat_smile:.

Thanks for the response. Closing the issue.
