### ISSUE TITLE
Server deadlock - stall - 1.7.10

### ISSUE THREAD

**Issue by Rubbertjuh** [AppliedEnergistics/Applied-Energistics-2#2712]
Minecraft Version: 1.7.10 - Thermos (https://github.com/CyberdyneCC/Thermos/releases)
AE2 Version: appliedenergistics2-rv3-beta-6
Forge Version:  1.7.10-1614
Modpack: FTB Infinity Evolved 
Modlist: (https://www.feed-the-beast.com/projects/ftb-infinity-evolved/files/2320896)

Issue at hand:
Server deadlocks completely after unknown event. I'm not sure how this is caused but I'm pretty sure that AE2 is the cause. In the past 24 hours it has deadlocked over 60 times..     
The server has some decent sized ME systems on it, a lot of small systems as well so it's very difficult to pinpoint the precise location of the issue and reproduce it.   
I would love to get some feedback on these stall reports on what particular item or item combinations I should be looking out for.     
  
I will provide 4 stall reports in a pastebin, if you want more, just ask. I can provide up to 60 if needed.
  
Stall reports:  
http://pastebin.com/mYMT2Bjz  
http://pastebin.com/LFZrV68Q  
http://pastebin.com/B74su8S7  
http://pastebin.com/E9euUfCT  
  
I hope to get some kind of support in here. A possibly fix for this would be amazing of course. 
If I left out any important information that you think is relevant, please don't hesitate to ask.  
I'm aware that you might have moved on from 1.7.10, we're moving torwards 1.10 in 2017 as well, we can't just leave our 1.7.10 servers to rot though! Hope you understand this.   
Thank you in advance, looking forward hearing from you.

**Comment by yueh** [comment]
We no longer support 1.7.10 and especially never support Thermos or anything similar.

**Comment by Rubbertjuh** [comment]
@yueh can I maybe hire you to look into it in that case? You, out of all people, should be the best to possibly fix this or give us more information.

**Comment by mindforger** [comment]
@Rubbertjuh a lot of info is missing to do so (except that i can yet not view the pastes as pastebin is blocked where i am currently :P)

but to give you my standard list: has every network ...

been properly chunkloaded
been properly powered
enough energy cells in the system (yes that matters, please don't argue about that :) )
any deep storage units attached that are locked (they cause items to disappear when locked, which itself can cause a bizarre chain of interactions)

also think of any plugin used that may interact with chunkloading as any big enough ME network can grind a server to a halt if parts of it are unloaded and reloaded infinitely

also don't use chickenchunks chunkloaders, they are known to cause chunkreloads

**Comment by Rubbertjuh** [comment]
@mindforger thank you for taking the time to reply to this issue.

I don't think I would be able to go through every Network on the server, our server tops off at 80 concurrent players =/ So you can imagine that I can't go through all the places to check for these things. 

Would you be able to give some examples of Deep storage units? This will help me identify them and look for them to see if I notice anything strange.
We're not using Chickenchunks chunkloaders, we are currently using a plugin called "BetterChunkLoader" which allows us to control the amounts people can chunkload to a precise number. You can find the plugin here: https://github.com/KaiKikuchi/BetterChunkLoader

Would there be a way for me to check if a chunk has been properly reloaded?

**Comment by mindforger** [comment]
items moved via storage bus to deep storage units not accepting the item can lead to it's destruction
so using properly configured storage busses on them shouldn't be a problem

you could possibly use >opis< to find if there are any item spills on any of those ME systems as crafting cpus cutting chunkborders may spill ALL items when partially unloaded


there is hardly anything i could help you besides the checklist without visiting the server and doing manual time consuming research

**Comment by Rubbertjuh** [comment]
Thank you for your feedback. I will try to keep an eye out for ME systems on chunk borders. 
I already appreciate all help that I get @mindforger , no need to come on my server and waste your time! 
I'm sure we will fix it one day. 
Thanks again, more feedback is always welcome!
