### ISSUE TITLE
Can't Dismantle Molecular Assembler

### ISSUE THREAD

**Issue by thiakil** [AppliedEnergistics/Applied-Energistics-2#2713]
#### Description
Sneak right clicking the Molecular Assembler does not dismantle it. 
Expected: drops itself as an item like other AE2 blocks.
Tested with the quartz wrench.

I would suspect because you're not passing to super @ https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/main/java/appeng/block/crafting/BlockMolecularAssembler.java#L102

#### Environment

- Minecraft Version: 1.10.2
- AE2 Version: appliedenergistics2-rv4-alpha-8
- Forge Version: 1.10.2-12.18.2.2171 (DW20 pack)

**Comment by yueh** [comment]
Also applies to crafting unit and wireless ap.
