### ISSUE TITLE
Crash server when AE is out of energy 

### ISSUE THREAD

**Issue by MaxGaming63** [AppliedEnergistics/Applied-Energistics-2#2714]
When my AE is out of energy, my server has a crash.

http://pastebin.com/xDdB0x2e

- Minecraft Version: 1.10.2
- AE2 Version:  rv4 alpha 8
- Forge Version: forge-12.18.2.2151

**Comment by yueh** [comment]
This is probably the confirmation, that we actually have to create a copy and cannot use the approach of #2496.

If you can reproduce it easily, can you please try the build from #2715? Once jenkins is done.

**Comment by Xiaminou** [comment]
I'd like to try that but where is the jenkins?

**Comment by Xiaminou** [comment]
This worked... (maybe)

**Comment by yueh** [comment]
Not maybe, we did intentionally change to test, if the old implementation was necessary or not. Now we know it, but at least it should be faster using an `CopyOnWriteArrayList` compared to the old implementation, which was backed by a copying a `LinkedList`.

**Comment by melekaiah** [comment]
any chance of a release with this fix? i cant really remove the mod and friends just keep forgetting. i keep having to call home to restart our private server.

**Comment by Xiaminou** [comment]
Like Yueh said, you can download it from the Jenkins.
