### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by Xiaminou** [AppliedEnergistics/Applied-Energistics-2#2717]
#### Description
Server crash shortly after loading the world, I don't know if it's really applied energistics but it shows up in the crash report so...
It was working fine yesterday, nothing changed between when I close the server and when I started it again. But today it's crashing no matter how far I rollback.
Removing Applied Energistics seems to fix it.

Crash Report: [crash-2016-12-22_15.47.03-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/669556/crash-2016-12-22_15.47.03-server.txt)
Log: [fml-server-latest.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/669557/fml-server-latest.txt)

If it's not applied energistics I'd like it if you could point me in the right direction because I have no idea what's happening and I've already wasted hours trying to find what's wrong.

- Minecraft Version: 1.10.2
- AE2 Version: alpha 9
- Forge Version: 2185

**Comment by yueh** [comment]
Duplicate

**Comment by Xiaminou** [comment]
of?

**Comment by Scoaex** [comment]
#2714 i guess
