### ISSUE TITLE
Massive duplication bug

### ISSUE THREAD

**Issue by identity001** [AppliedEnergistics/Applied-Energistics-2#2718]
Applied Energistics 2-rv4-alpha-9
Currently my ME is experiencing a glitch that happens under circumstances I am unable to yet identify.  Effectively, all of the items in my ME inventory just randomly double over.  It will double over all items that are attached to my player data unless there is not at least one copy of the item in my ME.  If I have 20 diamonds in the ME and 20 diamonds in a chest, I suddenly have 80 diamonds in the ME.  Deloading the chunk or restarting the server seems to reset the data and restores the items to their original number, however, if while the bug is active, I take the duped items out of my ME and put them in inventory, the items will remain even after the items in the ME have restored to their original numbers.  Deloading the chunk after the numbers are returned will in turn trigger the glitch again like on an off switch.  The main thing being that anything I take out while the bug is active, remains.  

#### Environment
I have a base built on water and my ME set up is small.  I literally just got it running the other day with only 4 controllers, one CPU unit, I have 7 64k drives because the server I am allows for purchasing of items and just got inscribers set up for on command automation. 
It is a direwolf 20 server MP

- Minecraft Version: 1.10.2
- AE2 Version: Applied Energistics 2-rv4-alpha-9
- Forge Version: Don't know, I am using the FTB launcher and playing on an online server with the latest Direwolf20 pack which is the only pack I am aware of that has the latest AE2.

**Comment by yueh** [comment]
What does this `allows for purchasing of items` means? Is that a sponge server?

**Comment by Ommina** [comment]
I'm guessing by "in a chest", you mean "in a chest, which is attached to the ME network via a storage bus", yes?

**Comment by identity001** [comment]
No, any chest at all.  The one in particular was not connected to the ME.  It was just a standard chest.  

And Yueh, the server owners have a system that allow you to actually purchase points to buy kits that will basically just creative in items for you.  That is how I got my ME drives.  

I did some further testing and just can't figure out what is causing it.  I have the exact same set up on an SP world and have not seen such an issue.  Got another guy on the server that has an ME set up, no issues.  I have used AE since Unleashed and never seen anything like this before.  

Restarting the server is like an on off switch for it.  After the items dupe, they remain duped until the server restarts, at that point when it comes back online the items literally undupe unless I have pulled them from the ME and placed them in my inventory.  I am at a loss.

**Comment by identity001** [comment]
The more and more I test with it the more random behavior I see in regards to items that it dupes.  Server restarts automatically every 3 hours so I have to wait for restarts to do anything in regards to further testing.

**Comment by GuntherDW** [comment]
Purchase points to buy kits. If that's real world money backed that means it's horribly out of line with the minecraft EULA.

**Comment by identity001** [comment]
Since no one seems to want to take me seriously on this, I made a video.  In the video I show my ME system inventory, then I wander around showing my small ME setup and then wander aimlessly while I wait for server restart.  After server restart, I go to my ME inventory and show it again.  The items in it are all doubled.

https://www.youtube.com/watch?v=w0DEuMy2av8

**Comment by GuntherDW** [comment]
We're "not taking you seriously" because you haven't answered the question to whether or not the server is running on sponge, or "vanilla" forge.

**Comment by identity001** [comment]
It was to my understanding that the issues AE2 had with spong were rectified.  Furthermore, idk if it was being run with sponge.  This server previously had AE2 disabled due to sponge issues but eventually enabled AE2 due to compatibility corrections.  

I have left a message on the servers discord channel but everyone is away due to the holidays.  

AE2 has been running perfectly for everyone including myself minus this random glitch that seems to exist only for me.  Even my SP world runs perfectly with AE2.  The video shows it all though but you know what, at this point, if no one cares, maybe i'll just figure out how the dupes work and make a full blown public video on how to make it happen.

**Comment by identity001** [comment]
That way people on any modpack that currently or may go public with AE2 can just duplicate whatever the hell they feel like duplicating.  Sounds great!

**Comment by identity001** [comment]
I pull about 8k views a month on my channel, i'm sure a portion of those folks are Minecraft players.  I bet they'll love it.

**Comment by identity001** [comment]
Doesn't matter if sponge is the issue.  There are public servers out there that are promoted by major launchers.  You should feel a sense of responsibility in regards to correcting this issue.  In the end though, it only benefits me so I mean whatever.

**Comment by identity001** [comment]
Yes, I have just been told it is run with sponge.

**Comment by yueh** [comment]
We simply do not support sponge. Of course server admins can choose to use sponge, but at their own risk.

**Comment by identity001** [comment]
The thing is many people are using AE2 on this server without this issue.  I have AE2 set up on an SP copied nearly block for blcok without this issue.

**Comment by bookerthegeek** [comment]
@identity001 I'm pretty good at fixing these issues on servers, if your server has a teamspeak, or a discord I would be more then willing to walk them through some ways to fix most issues.

A server address helps also so I can come on and assist with troubleshooting.
