### ISSUE TITLE
rv4-alpha-9 wireless remote bug

### ISSUE THREAD

**Issue by BushTrocity** [AppliedEnergistics/Applied-Energistics-2#2719]
rv4-alpha-8 the wireless access tool was working fine but from when the 1.10.2 direworlf pack was updated it broke it.

It will only display the crafting patterns and not any items. I have tried to re link it to my security terminal and to re craft it still only give me my auto crafting stuff.

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-9
- Forge Version: 2185

**Comment by yueh** [comment]
How about clicking the button to toggle between showing items, craftables or both?

**Comment by BushTrocity** [comment]
Nope that doesnt work either.

**Comment by BushTrocity** [comment]
Restarting the server a few times seemed to fix it.
