### ISSUE TITLE
Issue with spatial pylons in ae2 rv3 Beta6

### ISSUE THREAD

**Issue by enginekid92** [AppliedEnergistics/Applied-Energistics-2#2720]
#### Environment

- Minecraft Version: 1.7.10
- AE2 Version: rv3 beta 6
- Forge Version:  1614

When placing pylons there is an issue with larger setups (Not sure what exact size it starts at but I know it is an issue at 32x32x32).  The pylons will not always connect to cable and will only partway turn blue.  Underground, I get a different issue.  The pylons seem to form properly, but the SCS will not capture anything.  The image below it 32 width and depth, but not height.  Please let me know if more info is needed or maybe I am just doing something wrong.  Mod pack is technological illusions 2.  This is a multiplayer server (only a few friends on it).

![image](https://cloud.githubusercontent.com/assets/1272916/21478403/1e59163c-cb19-11e6-8201-aa0262b29f95.png)

**Comment by yueh** [comment]
Under some conditions, it seems minecraft/forge does not correctly instantiate the corresponding tile entities. But without any way to reproduce it, to actually fix it.

Nevertheless, we no longer support 1.7.10.
