### ISSUE TITLE
Config option to blacklist dimension ids for meteorite spawns

### ISSUE THREAD

**Issue by codetaylor** [AppliedEnergistics/Applied-Energistics-2#2721]
I would like to be able to prevent meteorite spawns in specific dimensions.

#### Description
I'm using this mod in conjunction with Advanced Rocketry (AR). AR creates new planets, or dimensions, using a pool of ids, or rather any id after a specified number. I want to prevent meteorites from spawning in dimensions -1, 0 and 1, essentially requiring the player to travel "off-world" to find a meteorite spawn and progress into Applied Energistics.

#### Environment
- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-9
- Forge Version: forge-12.18.3.2185

**Comment by yueh** [comment]
There is already a whitelist for the dimensions with meteors.

**Comment by Ommina** [comment]
Nonetheless, whitelist != blacklist.  When there can be any number of possible dimensions for a thing to spawn, attempting to list all of them (particularly when you don't know what, and how many, there are) ahead of time can be problematic.

**Comment by codetaylor** [comment]
I'm very well aware of the whitelist. That wasn't what I was talking about. Please ready my previous post more carefully.
