### ISSUE TITLE
Interface Name New Feature request

### ISSUE THREAD

**Issue by maginator** [AppliedEnergistics/Applied-Energistics-2#2723]
Hi. I have some ideas for a feature.  The idear is  that I can name some groups of interfaces  in the interface  terminal  some eg if I have a big me system and I have some molecular  assembler that are for normal crafting and some interfaces with more molecular  assembler for speed crafting.  And the idear is to tag the interface and in the terminal I can see the difference.

**Comment by yueh** [comment]
Already possible.

**Comment by maginator** [comment]
How? And allready in 1.7

**Comment by VT-14** [comment]
1.7.10 is no longer supported.

I think the mechanic is that you name the interface in an anvil or in an inscriber with a name plate (right click a quart cutting knife while having an iron ingot in your inventory, I think).

**Comment by maginator** [comment]
Nice that work. and with 1.7 i mean that work in 1.7 or is a feature of the new verion but its work in 1.7. Thx
