### ISSUE TITLE
Color Applicator does not accept dye items.

### ISSUE THREAD

**Issue by zlainsama** [AppliedEnergistics/Applied-Energistics-2#2724]
#### Description
As title says.
It is supposed to be able to accept dye items as documented in [wiki](http://ae-mod.info/Color-Applicator/).

#### Environment
- Minecraft Version: 1.10.2
- AE2 Version: appliedenergistics2-rv4-alpha-9
- Forge Version: forge-1.10.2-12.18.3.2185

I have tested in a clean install. [Picture](http://imgur.com/a/mAN1s)

**Comment by yueh** [comment]
Looks like there were some changes to the color names, which caused some problems with the case sensitivity.
