### ISSUE TITLE
Add Just Enough Resources compat

### ISSUE THREAD

**Issue by The-Fireplace** [AppliedEnergistics/Applied-Energistics-2#2725]
#### Description
I think support should be added for Just Enough Resources (JER), an addon for Just Enough Items (JEI). I believe it would be useful to be able to see what layers Certus Quartz Ore and Charged Certus Quartz Ore generate at, and the odds of finding them. Here is what JER's "recipes" look like:
![image](https://cloud.githubusercontent.com/assets/5914284/21557830/6c27a212-cdf7-11e6-95b9-f8a5bc5427f3.png)

#### Environment
This would need Just Enough Resources and Just Enough Items to be available libraries in the dev environment. If you would like code examples of how this can be done and the integration added, take a look at the repositories of [Fire's Clay Spawn](https://github.com/The-Fireplace/Fires-Clay-Spawn) and [Brain Stone Mod](https://github.com/BrainStone/brainstone).

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-9
- Forge Version: 12.18.3.2185

**Comment by yueh** [comment]
JER is probably the one mod causing most issues with JEI. Not sure if I really want to deal with that on top. And there is no maven repo for it.

Also the current API is extremely limited to actually provide a useful distribution chart for certus ore in particular.
It scales for every single world, pptentially for every single chunk under some conditions. Either it is not possible (chunk based) or we have to register every single world explicitly with its own potentially wrong distribution. Which can be as bad as having nearly none at the reported best layers.

So either it would be extremely tedious or pretty useless.

We even have/had ideas to to make more use of the x/z coordinates, which would also screw with it.

**Comment by SnowShock35** [comment]
You can technically already do this; use `/profile <No. Of Chunks> <Dimension No.|all>`

**Comment by yueh** [comment]
Yes, but only technically. It has to scan a very high number of chunks (like a couple of thousands) to give a reasonable result.
While doing so it needs an absurd amount of memory like I ran into memory issues even with dedicating 8 GB heap to it, no other mods an just scanning a single world/dimension. 

Thus I would not be surprised, if any larger server will run into issues with it and being unable to use it at all. Especially as you have to rerun it for every newly added dimension and it pretty much screws up the whole server/client while doing it.

**Comment by SnowShock35** [comment]
Oh yeah it's awful!!! Darn memory hog alright. mezz managed to make it a little better but it's still pretty bad. :/
