### ISSUE TITLE
ME Controller Disappeared after disabling channels

### ISSUE THREAD

**Issue by checkium** [AppliedEnergistics/Applied-Energistics-2#2726]
#### Description

So, I had a basic AE2 system with one drive, a terminal and a controller. Today, before starting the server I got into AE2 config and disabled channels. FML even warned me about missing block and I tougth it was just some ID change, but right now ME Controller doesn't even appear in NEI.
#### Environment

- Minecraft Version: 1.7.10
- AE2 Version:  0.5.1.61
- Forge Version: 7.99.4.1614
- [Mod list](http://www.technicpack.net/modpack/the-unleashed-survival.928280/mods)

**Comment by yueh** [comment]
#714
