### ISSUE TITLE
Crash at forge load, says it's caused by appeng/items/tools/powered/ToolEntropyManipulator throwing a NoClassDefFoundError exception

### ISSUE THREAD

**Issue by zackeezy** [AppliedEnergistics/Applied-Energistics-2#2729]
#### Description

I was building the game and got an error.  When I checked the crash log, it said that Applied Energistics 2 was the problem, and it said that the cause of the issue was the Tool Entropy Manipulator.  Or that's the object it said wasn't defined.  The expected behavior was for the game to build, and the actual behavior was a crash.  I'm going to deprecate to alpha-9 and try again. 

#### Environment

Singleplayer using the curse launcher with a custom modpack. 
http://pastebin.com/p8xVETRE

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-10
- Forge Version: Forge 12.18.3.2185

**Comment by yueh** [comment]
Meh, and that is why I hate any VCS IDE integration, because they usually pull some crap when not paying 120% attention. Especially when the whole forge build system is down at the same time and cannot be used to verify stuff.

**Comment by zackeezy** [comment]
I ran again with alpha-9 and it loaded fine, so something went wrong from 9 to 10.

**Comment by yueh** [comment]
Yes, my IDE slip in a regression during the time ForgeGradle/mcpbot was down, thus every CI did fail during that time, thus I did not caught it earlier. And the forge server(s) seem to still be a bit unreliable currently, with like every other CI/build failing...
