### ISSUE TITLE
ConcurrentModificationException w/ Controllers & Quantum Bridges

### ISSUE THREAD

**Issue by SnowShock35** [AppliedEnergistics/Applied-Energistics-2#2731]
#### Description
I'm not 100% sure of what the issue is, but when playing around with quantum bridges and me controllers I had instantaneous crashes to desktop which then corrupted the world save. (Same w/ dedicated server as well)  I have a feeling it's something to do with  the bridges connecting and disconnecting then something happening while they're trying to process information. From what the stack trace says it seems the issue is in the TickHandler, which is what leads me to think this is the case. 

#### Environment
The issue occurred when playing a FTB mod pack (Unreleased). Issue occurred in both SP and MP.

Here is the crash report. (Contains mod list & their versions): http://pastebin.com/yAuALK3C

#### Information
- Minecraft 1.10.2
- Minecraft Forge 12.18.3.2185
- Applied Enerigistics 2 rv4-alpha-9

**Comment by yueh** [comment]
Also with rv4-alpha-11?

**Comment by SnowShock35** [comment]
Didn't realise that build existed. Was using what was the latest on CurseForge. Want me to try it?

**Comment by yueh** [comment]
11 is pretty fresh, but curse seems to be pretty slow today for approving builds, while not even testing them at all.

**Comment by SnowShock35** [comment]
Yeah, Probs because of NYE 🙂

**Comment by SnowShock35** [comment]
Well, I'll make sure it's in the next update of the pack and if I come across it again I'll let you know :)

**Comment by SnowShock35** [comment]
And of any other bugs that occur 😄

**Comment by yueh** [comment]
Did it fix it?

**Comment by SnowShock35** [comment]
Well I can't get a copy of that version till it becomes available on Curse. Couldn't see any other download anywhere else

**Comment by yueh** [comment]
http://ae-mod.info/

**Comment by SnowShock35** [comment]
rv4.alpha build 11 download link takes me straight to curseforge :/

**Comment by yueh** [comment]
Oh. looks like Algo removed our own mirror link. Then you have to wait for curse.
Should it not fix it, no idea. But I will not work on the system reported by the stacktrace currently. It is a bit too messy, but there is no straightforward alternative for it.

And certainly not touch anything with FTBLib/FTBUtilities

**Comment by SnowShock35** [comment]
Okay not to worry. Thanks yueh :)
