### ISSUE TITLE
Spatial Storage Cells seem not to empty

### ISSUE THREAD

**Issue by zebMcCorkle** [AppliedEnergistics/Applied-Energistics-2#2732]
#### Description
Spatial Storage Cells, after "emptying" them, don't become empty cells in the output of the IO port.

#### Environment
Windows 10 64-bit
Java 8u111

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-11
- Forge Version: 2185

**Comment by mindforger** [comment]
as far as i can remember, a Spatial Storage Cells can not be emtied out at all, it is more like a link to a custom generated dimension where the content of the space between the pylons is switched in and out

**Comment by yueh** [comment]
Exactly.
