### ISSUE TITLE
Optifine Animated textures and ME Controllers

### ISSUE THREAD

**Issue by DeadSix27** [AppliedEnergistics/Applied-Energistics-2#2733]
So, since without OptiFine 1.10 and and a Pack with lots of mods the game is pretty much unplayable (i get insane stuttering on a very good system)

I have to turn off `Terrain Animated` in OptiFine (suddendly 120fps stable).

Anyway my point here is, the ME Controller does not animate due to that, but many other mods apparently still have animated textures working.
Is there anyway you can make this work while clients have `Terrain Animated` off?

**This is purely cosmetic and does not break game play, its just a little thing I noticed.**

And **I know this is not AE's problem...** but you have to agree that without OptiFine its almost unplayable on very big modpacks.

**Comment by yueh** [comment]
No, we do not have to agree that OptiFine is a solution for anything.

If you want to do something responsible, help identify the mods actually causing problems and provide good scenarios for their devs to reproduce them. Or even better provide some basic profiling results as starting point. (That might even apply to forge itself, not a specific mod)

It would improve it for everyone not just OptiFine users and make OptiFine a solution for low end pcs with a potential cost of graphics qualitity for a bit more performance.
