### ISSUE TITLE
issue with energy and growth chamber

### ISSUE THREAD

**Issue by Nekothika** [AppliedEnergistics/Applied-Energistics-2#2734]
Hi all, there is my issue http://i.imgur.com/JqIKYx9.png or http://i.imgur.com/y5af02c.png no results, crystal growth chamber stay Offline and no power inside. On the second screen, the energy cell is charged but ... no energy sent on growth. Did a made a mistake ? plz help me ^^ (sry bad english)

**Comment by mindforger** [comment]
is crystal growth chamber now a part of AE2 ? 

i think you posted to the wrong mod here! 

try https://github.com/bdew/ae2stuff
