### ISSUE TITLE
AE2 Return on Main Menu (Crash) when hit the Craft Status inn ME Craft Terminal

### ISSUE THREAD

**Issue by Bruno3434** [AppliedEnergistics/Applied-Energistics-2#2738]
#### Description
AE2 Return on Main Menu (Crash) when hit the Craft Status inn ME Craft Terminal in Survival Mode

It look to be "intermittent" because one time i got it work for about 10 min, and another time worked on a new world Creative mode.

I m playing with the [Universale Interdimentional Escape mod](url=https://minecraft.curseforge.com/projects/universal-interdimensional-escape) Pack from Curse. 

i already got this bug one time, (one or 2 years ago), with another modpack (don't remerber which one)

#### Environment
http://pastebin.com/GPsrA0ye

- Minecraft Version: 1.7.10
- AE2 Version: appliedenergistics2-rv2-stable-10.jar
- Forge Version: forge-10.13.4.1614 1.7.10 (modded)

**Comment by yueh** [comment]
Sorry, but we no longer support 1.7.10.
