### ISSUE TITLE
[1.10.2] Storage Bus + Interface isn't creating a subnetwork to store items on one channel.

### ISSUE THREAD

**Issue by Swat6** [AppliedEnergistics/Applied-Energistics-2#2739]
When trying to create a subnet with a storage bus and interface combo(like a super soaryn drive) the main system does not see the subnetted drive and its contents. Not like how it worked in 1.7.10. I read through all the changelogs on curse and it didn't mention it so I thought I would report it here. 

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-11
- Forge Version: 12.18.3.2185

**Comment by FiveEYZ** [comment]
i have done exactly what u described and it works 100%, are sure u are giving the subnet power?

**Comment by yueh** [comment]
Works fine for me.

**Comment by SwatKid** [comment]
It was getting power, but maybe it was because it was on a already established network and it was messing with something. I will try it by it self when I get home.

**Comment by SwatKid** [comment]
Got it to work, sorry.

**Comment by SwatKid** [comment]
Looks like when I created the subnet I would have to relog to get it to show the items and for the network to register the subnet.
