### ISSUE TITLE
Won't render correct item count in Quantum Storage Units

### ISSUE THREAD

**Issue by sublimn** [AppliedEnergistics/Applied-Energistics-2#2740]
#### Description
When connecting quantum storage units to the network via external storage buses, it displays _only_ the stack in the "out box" in the storage unit, while looking at the item count. (I.E. I have 1.6 mil cobble in the storage unit, the item count reads 64 cobble. I remove the cobble, and the count remains at 64.)

contents of the QSU
![2017-01-03_23 28 04](https://cloud.githubusercontent.com/assets/24909526/21633474/c796c31c-d20c-11e6-976a-22bebba60eee.png)

display in AE
![2017-01-03_23 28 21](https://cloud.githubusercontent.com/assets/24909526/21633488/de5a49fc-d20c-11e6-878b-68966998b64a.png)

Removing stacks, number stays the same
![2017-01-03_23 28 35](https://cloud.githubusercontent.com/assets/24909526/21633494/efc862c8-d20c-11e6-9a3d-c9788b2abb27.png)

- Minecraft Version: 1.10.2
- AE2 Version:  rv4.alpha build 11
- Forge Version: 12.18.3.2185

**Comment by mindforger** [comment]
just to prevent future issues with loosing items using DSUs take this hint: 
configure your storage bus to ONLY move items matching the content or the DSU ... if the storeage bus attempts to move items into them while they are locked, the items might get destroyed! 

sorry for your atual issue i have unfortunately no idea

**Comment by sublimn** [comment]
I mean, it seems the issue stems from how AE2 is checking the QSU's inventory. It's only looking for blocks in the UI, not wherever QSU's store it...? That'd be my best guess

**Comment by sublimn** [comment]
After perusing through more forums, I found this is an old issue. Is there another mod that uses Itemhandler and provides large storage?

**Comment by mindforger** [comment]
naah .. sorry i misread it like you were using deep storage units, sorry :P

**Comment by yueh** [comment]
#2550
