### ISSUE TITLE
After disconnecting the ME-Drive from the network, there are still items in terminal.

### ISSUE THREAD

**Issue by AgKey47** [AppliedEnergistics/Applied-Energistics-2#2741]
Connect a ME-Storage-Monitor to the network and right-click with a item to monitor the network. Then quickly disconnect, connect, and then disconnect the ME-Drive from the network. You will see the item are still displayed in the terminal and can be taken out.

My English isn't good, if you can't understand what I mean, please reply to me.

- Minecraft Version: 1.7.10
- AE2 Version: rv2.stable build 10 and rv3.beta build 6
- Forge Version: 1.7.10 - 10.13.4.1614

**Comment by mindforger** [comment]
this is a knownj issue and may be fixed in a final release but don't quote me on that it may never happen as 1.7.10 is not supported anymore
