### ISSUE TITLE
[1.10.2] WAILA support for channels used in cables (may got broken)

### ISSUE THREAD

**Issue by 016Nojr** [AppliedEnergistics/Applied-Energistics-2#2743]
Basically as title says

**Comment by yueh** [comment]
Already exists.

**Comment by 016Nojr** [comment]
If that is so, how do I enable it @yueh?

**Comment by GuntherDW** [comment]
While this isn't the greatest Issue report, something indeed has broken it in the rv11 snapshot.

The one probe integration works, but WAILA (or rather, HWYLA in my case) support seems broken : http://i.imgur.com/LY8WAFM.png

**Comment by 016Nojr** [comment]
It wasnt the greatest issue report because it was never the intention, I sent it in because I thought it wasnt implemented back in. However, I can inform that I am using the 1.2.2 version of the DW20 1.10.2 pack.

AE2: rv4 - alpha - 9
Waila: 1.7.0-B3_1.9.4.jar
Forge: 12.18.3.2185

@ProfMobius

**Comment by mindforger** [comment]
I am reopening this issue to not loose it, as is seems confirmed there is an issue

**Comment by yueh** [comment]
Works fine for me:

![waila integration](http://i.imgur.com/zz5Ionl.png)

**Comment by 016Nojr** [comment]
Could it be something wrong with servers? Im not home so I can test singleplayer and see if it actually works for me in singleplayer

**Comment by GuntherDW** [comment]
My screenshot is indeed when connected to a server.
In a single player world WAILA does indeed show how many channels are on a cable.

So it seems that it's a SMP only issue.

**Comment by GuntherDW** [comment]
Hmm, after I updated HWYLA (basically a WAILA fork, but updated) it seems to have broken it in SSP as well.

HWYLA Curseforge link : https://minecraft.curseforge.com/projects/hwyla
The newest version changed a bunch of internals. I guess it has broken some things.

https://github.com/TehNut/HWYLA/issues/38
I'll add an issues on their end as well.

**Comment by Zormuche** [comment]
Hi
I used to have the same problem
just put Hwyla also on your server and it's all fixed
