### ISSUE TITLE
(suggestion) Add compatibility with chisel and bits mod to make custom facades

### ISSUE THREAD

**Issue by ICantThinkOfAG00dName** [AppliedEnergistics/Applied-Energistics-2#2744]
i think there shoud be possibility to use chisel and bits to make custom facades in ae2

**Comment by yueh** [comment]
Not possible.

**Comment by ICantThinkOfAG00dName** [comment]
why is it not possible refined storage mod works with c&b well

**Comment by XFactHD** [comment]
Because AE2 currently does not support MCMP which C&B uses for its multiparts.

**Comment by ICantThinkOfAG00dName** [comment]
well is it maybe possible later or at least please fix the facades being weird 
![2017-01-07_17 11 28](https://cloud.githubusercontent.com/assets/24963816/21861237/acf39770-d83c-11e6-9569-e886cb4746ee.png)
