### ISSUE TITLE
Dark Roleplay Will cause crash

### ISSUE THREAD

**Issue by bruce8866** [AppliedEnergistics/Applied-Energistics-2#2745]
#### Description
When I install Dark Roleplay Medieval-0.1.6 and Dark Roleplay Core, placing ME-Controller in the world or loading have the ME-Controller world will cause crash

#### Environment
Dark Roleplay Core 0.1.7
Dark Roleplay Medieval-0.1.6
crash log : http://pastebin.com/1fTJHgHR

- Minecraft Version: 1.10.2
- AE2 Version: appliedenergistics2-rv4-alpha-11
- Forge Version: forge-12.18.3.2185

**Comment by yueh** [comment]
While not a clear duplicate, the concept is the same as #2598.
