### ISSUE TITLE
ME Drive + ME Storage Bus

### ISSUE THREAD

**Issue by BurovB** [AppliedEnergistics/Applied-Energistics-2#2746]
Can I connect ME Storage Bus from first ME-Network to ME Drive from second ME-Network and extract items by it?

**Comment by VT-14** [comment]
No.

You can place a Storage Bus on an Interface to access the items on the second network (a sub-net), or you can use a ME I/O Port to transfer items between drives.

**Comment by BurovB** [comment]
Thanks.
