### ISSUE TITLE
Crafting CPU Dropping items

### ISSUE THREAD

**Issue by TheWildBananas** [AppliedEnergistics/Applied-Energistics-2#2747]
When crafting 64k ME Storage Components, it crafts for a while, and when it gets to the end, all of the materials drop(on the ground, it just explodes everywhere), without crafting the item. 

#### Environment
I am using the latest rv2.stable build 10.
http://prntscr.com/dsmgrl This is my Crafting setup. With a Crafting Monitor on the front. 
Running on a server. Haven't tested in singleplayer.

- Minecraft Version: 1.7.10
- AE2 Version: rv2.stable.10
- Forge Version: forge-1.7.10-10.13.4.1614-1.7.10-universal

**Comment by mindforger** [comment]
MC 1.7.10 is not supported anymore, but you are using an extremly outdated version!

use rv3 beta 6 instead it is WAY more stable that the actual rv2 stable
