### ISSUE TITLE
[1.10.2] Yeta Wrench support

### ISSUE THREAD

**Issue by 016Nojr** [AppliedEnergistics/Applied-Energistics-2#2749]
Add back support for the Yeta Wrench from EnderIO

**Comment by gerd2002** [comment]
What do you mean precisely by that?

~Gerd

**Comment by 016Nojr** [comment]
Being able to pick up cables and blocks with the Yeta Wrench like you can with the Certus/Nether Quartz Wrench

**Comment by yueh** [comment]
There was never support for the yeta wrench by us. 

Either this was just working sd we did support the BC wrench. Basically it was the default wrench in 1.7.10 support by most mods. But there is no BC in 1.10 (yet) or another widely accepted wrench;

Or EnderIO added their own support for our wrench, but did forget to readd this support in 1.10.
