### ISSUE TITLE
MIssing Channel Device

### ISSUE THREAD

**Issue by Nekothika** [AppliedEnergistics/Applied-Energistics-2#2751]
Hi all, I have some issue about channels, first, here a screen : (sorry bad english i'm french)

http://i.imgur.com/1C4PtZ6.png

The enabling/disabling channel is completely random, i can be inside my ME, search some some items and "clic" no more answer, all gray, i check and : "missing channel device" however, and as you can see, only 6/8 channel, and anchor cable used for avoid any routing mistake. Here the full setup : 

http://i.imgur.com/ZVkGSpT.png
http://i.imgur.com/wMvMMD8.png
http://i.imgur.com/N6fZ6jK.png
http://i.imgur.com/A7PpVHE.png
http://i.imgur.com/kW48DvT.png

As you can see, on the very last section of the cable linking terminal to ME Controller, only 23/32 channel, and .... random deactivation still here, please help me, I just want my system being stable, without turning off randomly without any reason.

Thanks for help

**Comment by mindforger** [comment]
do you have sufficient power and energycells? is any part of your ME system chunkloaded?

**Comment by Nekothika** [comment]
BigReactor delivering 1 000 000 000 RF/t with 4 tesseract directly link to ME controller, personnal anchor on terminal and on the ME controllers chunk

**Comment by vallard192** [comment]
Double check that the entire cable is chunkloaded too.

**Comment by Nekothika** [comment]
he is

**Comment by mindforger** [comment]
install dense energy cells, at least 4 .. i am not going into why this is important just try it out please 

having the controller loaded means nothing, you need to load the full network .. each change results in an update of the net possibly causing this behaviour

**Comment by XFactHD** [comment]
Also the one billion RF input won't get you anywhere, you need to make sure that the energy storage of your network is higher than the consumption. You can see network status info when you click on a controller block with the network probe.
