### ISSUE TITLE
Formation plane can't drop Actually Additions canola seeds?

### ISSUE THREAD

**Issue by cha0s** [AppliedEnergistics/Applied-Energistics-2#2755]
#### Description

I set up a simple network, energy acceptor -> interface -> cable -> formation plane. Attempted to load a canola seed into the interface. It just sits in there. Pretty much anything else I manually insert into the interface is immediately ejected from the formation plane.

#### Environment

Survival multiplayer

- Minecraft Version: 1.10.2
- AE2 Version: appliedenergistics2-rv4-alpha-11
- Forge Version: FTBserver-1.10.2-12.18.3.2185-universal

**Comment by yueh** [comment]
If these seeds are actually plantable, the formation plane will try to plant them in block mode (default mode). Depending on the requirements for the seeds (farmland whatver) this can of course fail.

**Comment by cha0s** [comment]
This was not in block mode.
