### ISSUE TITLE
Hang/crash when any block using connected texture method=ctm is next to any ME Drive

### ISSUE THREAD

**Issue by h8ball** [AppliedEnergistics/Applied-Energistics-2#2756]
Minecraft v1.10.2 with Forge (any version), Optifine HD Ultra (any version) and Applied Energistics 2 rv4-alpha-(any version) either hangs or crashes instantly if any block using connected texture method=ctm is next to an ME Drive.

This always occurs whenever a method=ctm block is placed next to an ME Drive, or any resource pack is enabled which enables method=ctm for any block having an ME Drive as a neighbour.

That world subsequently hangs or crashes instantly on load and the only way to reload it successfully again is to disable the resource pack involved (so connected textures are no longer in-use). The offending block next to the ME Drive must then be removed before that resource pack can be re-enabled. But this means that ANY resource pack that employs method=ctm will cause a hang/crash if any such block is next to any ME Drive. Only method=ctm causes the problem. Other connected texture methods work fine.

I've disabled ALL other mods leaving ONLY Forge, Optifine and AE2 enabled, and the crash problem still persists. I've tried many version combinations of Forge, Optifine HD Ultra (C3 and D1 through to the latest D6), and AE2 rv4-alpha versions 1 through 11, and the instant hang/crash still occurs whenever AE2 attempts to render an ME Drive next to any method=ctm block.

My ME System is far too useful to give up and took a LOT of resources and time to build. As such, the only thing I can do for now is to ensure that any resource pack I use has NO occurrences of method=ctm. If it does, I have to remove them from assets/mcpatcher/ctm so that Optifine reverts to the standard single-tile versions in assets/minecraft/textures/blocks.

Crash log attached (only Forge, Optifine and AE2 mods were enabled, and the only resource pack in-use was MojoKraft which employs method=ctm for Cobblestone).

[crash-2017-01-14_20.19.22-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/706271/crash-2017-01-14_20.19.22-client.txt)

Best regards,

H8Ball

**Comment by yueh** [comment]
Based on the crashlog, optifine tries to render the drive in an invalid state by not passing the actual state of it to it.

Sure we could protect against it, but this cause should never happen normally as well as it is completely useless to pass an invalid/incomplete state to a block because it will never be able to return the correct texture. Thus mostly an optifine issue.

**Comment by h8ball** [comment]
Many thanks for the quick reply.

Yeah, I thought so, but as I can find no way to report a bug on the Optifine site, I posted here in the hope you might be in contact the author (since ALL resource packs using method=ctm are "broken" with AE2 under ANY version of Optifine for Minecraft v1.10.2).

Until the Optifine author issues a fixed version, I'm working around the ME Drive crash problem by editing any resource pack I use to ensure ALL method=ctm connected textures are removed.

Thanks again.

**Comment by leagris** [comment]
Or you could disable connected textures in Optifine settings.

**Comment by Silly511** [comment]
I think [this](https://github.com/sp614x/optifine/issues) is the optifine bug tracker.

**Comment by CraftMinerKyle** [comment]
There is an option in Menu>Video Settings>Quality>Connected Textures>Off or Fast. Try that. Also, OptiFine has a LOT of problem with textures in mods like Chisel, so try removing OptiFine in general. If you are using OptiFine for a Preformance boost, try using FastCraft instead.
