### ISSUE TITLE
Client Crashing in Multiplayer when mining Ores from Immersive Engineering

### ISSUE THREAD

**Issue by clifftrials** [AppliedEnergistics/Applied-Energistics-2#2758]
#### Description
When mining Ores from Immersive Engineering on my server, the client crashes with an error referencing AE2. The server does not crash. The crash occurs only to the individual who mined the block, regardless if others are nearby. The mining method was tested both with a pickaxe and with creative mode breaking--both resulted in a Client crash. We also tried performing the same tests 1000s of blocks away to see if location might be an issue. 

#### Environment
Crash Log: http://pastebin.com/zcfSPsWT

- SMP. Did not occur in Single player.
- Minecraft Version: 1.10.2
- AE2 Version: appliedenergistics2-rv4-alpha-11.jar
- Forge Version: 1.10.2 - 12.18.3.2185

**Comment by yueh** [comment]
Based on the crashlog it looks like it is trying to render the ore as quartz pillar.

Either the server itself is corrupted somehow, like the id mappings for blocks is different between the server and client. Or something other like optfine interferes with it.

But neither AE2 or IE is the actual cause.
