### ISSUE TITLE
When you turn off "channel =" false "" game crash (when you take the subject in hand)

### ISSUE THREAD

**Issue by BioTech21** [AppliedEnergistics/Applied-Energistics-2#2759]
Minecraftsion: 1.7.10
AE2 Version: rv3.beta build 6
Forge Version: forge-1.7.10-10.13.4.1614-1.7.10-universal

**Comment by mindforger** [comment]
can you attach a crashlog please (use pastebin or attach it as file, do not copy & paste it) also what do you mean by "take the subject in hand"
