### ISSUE TITLE
Random CME on TreeMap backed Iterator

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#276]
Currently known stacktraces:
https://gist.github.com/anonymous/e195310b3e10f0b4c91c
http://pastebin.com/RpamKi4T

TreeMap iterators are fast failing and not threadsafe, so any modification of the underlying map will cause them to throw a ConcurrentModificationException.

**Comment by Cronosus** [comment]
i try latest (rv2-b7) build a i have this spammed in console
[15:15:10] [Server thread/WARN] [IC2/]: EnergyNet.removeTileEntity: appeng.tile.misc.TileInscriber@3ebe9fb (appeng.tile.misc.TileInscriber@3ebe9fb) doesn't match the registered te appeng.tile.misc.TileInscriber@6702536, skipping

and tps going everytime down under 1TPS.. :(

without AE are TPS still 20 and not going down... problem must be in AE.. :(

**Comment by gixmy** [comment]
Thanks for pointing me here. FYI using the latest build (appliedenergistics2-rv2-beta-23.jar), AE2 no longer crashes my server. The point above about ic2 being involved wasn't the case for me.
