### ISSUE TITLE
When you turn off "channels =" false "" game crash (when you take the subject in hand)

### ISSUE THREAD

**Issue by BioTech21** [AppliedEnergistics/Applied-Energistics-2#2760]
Minecraftsion: 1.7.10
AE2 Version: rv3.beta build 6
Forge Version: forge-1.7.10-10.13.4.1614-1.7.10-universal

**Comment by mindforger** [comment]
one report is enough :) 
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2759
