### ISSUE TITLE
world can't  generate oreOsmium when used with Mekanism

### ISSUE THREAD

**Issue by joutenchi** [AppliedEnergistics/Applied-Energistics-2#2761]
when i use rv3-b6 version,oreOsmium is not generate in world ,and this will not happen when i use rv2-10.

Minecraftsion: 1.7.10
AE2 Version: rv3.beta build 6
Forge Version: forge-1.7.10-10.13.4.1614-1.7.10-universal

**Comment by Tyrant0x1** [comment]
Not an AE dev, but I've personally used rv3 beta 6 and mekanism together in 1.7.10, and I've never had issues with Osmium generating in the world. Try double checking your other config files.
