### ISSUE TITLE
Bring back sparks in cables from AE1

### ISSUE THREAD

**Issue by tyra314** [AppliedEnergistics/Applied-Energistics-2#2762]
Add the sparks in cables, which were there in AE1. This is clearly a wish.

#### Description
I always loved the sparks in an AE1 ME System, which are triggered, whenever an item is transferred through the network. It actually gave me the feeling, that items are not ported from one place to another, but instead are transferred via the network as energy. I think it is a small addition, but adds SO much in a bigger network. I recently loaded up my old 1.6.4 world and it just feels way more alive and active.

For anyone having forgotten about it, take a look:
![sparks](https://cloud.githubusercontent.com/assets/16997177/22127246/75f40556-de9b-11e6-814f-16560f6e95c0.gif)

This is probably only feasible for the glass cables.

#### Environment
If you insist, but as it ain't in any AE2 version and it is a wish...

- Minecraft Version: 1.7.10
- AE2 Version: rv3-beta-5
- Forge Version: 10.13.4.1614

**Comment by yueh** [comment]
#20, but unlikely as this can be a massive performance issue.
