### ISSUE TITLE
Items bypassing priorities

### ISSUE THREAD

**Issue by Littlenemo** [AppliedEnergistics/Applied-Energistics-2#2763]
using rv3-beta-6 

Current network hierarchy:
Ender chest from various production farms ->ME Import bus -> Storage bus (priority 1) ->Interface -> connected to subnet with 3x Drive Bays (priority 0) and Storage bus (priority 1) with filters for high production items ->Inteface -> connected to subnet with 5x Drive bays(priority 0) with formatted cells for single items (priority 10) -> Storage bus (priority -1) -> Trash can

My expectation is that items being filtered will be limited at 8128 (127*64).
What's happening is that items are bypassing that limit, and being stored on the lower priority general storage drive bays. 
I can cycle any of the filtered items, and it will lock their inventory back to 8128, but if I sit with the ME inventory screen up, I can watch them exceed the formatted drive's capacity.

Maybe I don't have a clear understanding of the how priorities interact with subnets. Maybe I'm just doing this wrong in general.

**Comment by yueh** [comment]
Priorities are only relevant for the local network.

If you have Network A with

* Storage Bus -> Network B @ 10
* Drive A @ 5

and Network B with

* Storage Bus -> Trashcan @ -1
* Drive B @ 0

When inserting something into Network A, it will always try to store it into Network B until that is full.
Due the trashcan, this will never be true, Thus regardless of Drive A having a higher priority than Drive B and t he Trashcan, it will never be used

**Comment by Littlenemo** [comment]
Alright, so after taking that info, I'll try to reconstruct the problem I'm seeing.

![ae2wtf](https://cloud.githubusercontent.com/assets/5568077/22395179/cee6a178-e4ea-11e6-9202-4111df8b9bfb.png)

Main ME network connects to Network A with a storage bus priority 0
Main ME network connects to Network B with a storage bus priority 1 with filters for high production items

Network A has general storage of unformatted cells
Network B has formatted cells and a priority -1 storage bus pointed at a trashcan.

After any given item filtered into network B has filled up the storage cell, that item then begins to be stored on network A. Why?

I can use a chest with import/export buses on it to cycle out that same item which forces them into the trashcan like I assume it should always work, setting the maximum stored amount to the appropriate formatted cell size.

**Comment by GhostShot3** [comment]
Too much drives
