### ISSUE TITLE
Redstone Duping

### ISSUE THREAD

**Issue by Renari** [AppliedEnergistics/Applied-Energistics-2#2764]
#### Description
I was trying to automate crafting fluix crystals, however it seems the formation plane is dumping items into the world that do not exist.
[Here](https://my.mixtape.moe/xjsjqv.mp4) is a video of the setup causing this issue.

**Expected:**
To receive two fluix crystals and not obtain surplus redstone.

**What happens:**
Two fluix crystals are created however redstone continuously gets shot out of the formation plane while not being removed fromt he network.

#### Environment

- Minecraft Version: 1.10.2
- AE2 Version: rv4.alpha build 11
- Forge Version: 12.18.3.2202

**Comment by GuntherDW** [comment]
Can confirm, even asked about it in IRC a while ago but didn't got any real attention.
Next time I might want to check if any of the devs are awake...

**Comment by yueh** [comment]
Cannot reproduce.
