### ISSUE TITLE
Inscriber stucks?

### ISSUE THREAD

**Issue by Nomflow** [AppliedEnergistics/Applied-Energistics-2#2765]
hello,

my english isn't as good as it could be but i'll try to explain my problem as good as i can:

-set up 5 advanced inscribers - each attached with one me controller and one me import bus
-4 advanced inscribers contain the relevant inscriber press plates (eg. calculation, engineering, silicon, logic)
-4 me controller contain the pattern for the 4 existing circuits
-1 me controller contains the pattern for the 3 existing processors
-when i order let me say 15 logic processors using the me system, the inscriber stucks after printing 2,3 or 4 printed logic circuit with 76%, 94% or something like that

i already tried different setups but i can't find any way to solve this problem.

is this intendend or a bug which wasn't fixed yet? as it seems to be just impossible to automate processor production.

![inscriber](https://cloud.githubusercontent.com/assets/25311007/22227599/659cb05c-e1cc-11e6-9502-f0e412c1a1f9.png)

any help would be great... thanks in advance.

regards

ae2-rv3-beta5
mc 1.7.10

**Comment by mindforger** [comment]
unfortunately 1.7.10 is not supported anymore, but

can you post a more complete image of your setup? it kind of looks like an setup error

PS beta6 is the most up to date version, or is there a particular reason?
