### ISSUE TITLE
ME Controller not recieving power when replacing it (Same issue with power acceptor)

### ISSUE THREAD

**Issue by Darnellis** [AppliedEnergistics/Applied-Energistics-2#2766]
#### Description
(I'm using FTB HermitPack and the power cables I'm using are ultimate universal cables)
Forgive my poor description of the problem. Whenever I place down an ME Controller or power acceptor it works perfectly fine until I replace the block. Power isn't transferred to either of these blocks and when I replace the block with an ME Smart cable the Universal cables connect to the smart cable (even though they shouldn't). I tested to see what the issue was and it seems to be an issue with the position of the controller. I can replace the controller anywhere I want and power goes to it just fine but when I try to replace the controller in the exact same position it doesn't work (power doesn't go to it). 

http://imgur.com/a/uoxjt

Hopefully, this explains it well enough. If not you can contact me via email so we can discuss this to further lengths. > Captain0dan@gmail.com

I'm playing on a singleplayer world

>Followup, It seems to be an issue with the Mekanism cables. I replaced one with an EnderIO energy conduit and it works perfectly fine,

- Minecraft Version: 1.10.2
- AE2 Version: Alpha 11 RV4
- Forge Version: 12.18.3.2185  
- Modpack: HermitPack Version 1.6.1
- Mekanism Version: 9.2.1.295

**Comment by yueh** [comment]
Probably #2750
