### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by magnusjjj** [AppliedEnergistics/Applied-Energistics-2#2767]
#### Description

The license file in this repo, and the license on the forge website says that the mod is licensed under lgplv3. BUT, the website says this:

"This mod (compiled plugin, compiled patch to Minecraft source, henceforth "Mod" or "The Mod"), by the terms of http://minecraft.net/terms is the sole property of the Mod author (AlgorithmX2, henceforth "Owner" or "The Owner"). By default it may only be distributed on its own from http://ae-mod.info . It may not be distributed on its own from any other source unless given explicit permission. It may be included in any modpack with other mods, as long as it does not attempt to make money off The Owner's Mods. URL shorteners or other attempts to make money off The Owner's Mods are strictly forbidden without advance written permission. Attempts to modify the Mod, and distribute modified versions are Strictly Prohibited, reguardless of the modifications in question." 

Last modified on 01/09/2016 03:29 PM CST
By yueh

#### Environment

- Minecraft Version: n/a
- AE2 Version: n/a
- Forge Version: n/a

**Comment by yueh** [comment]
#1546
