### ISSUE TITLE
Wireless terminal drains RF at a ridiculous rate

### ISSUE THREAD

**Issue by xenoflot** [AppliedEnergistics/Applied-Energistics-2#2768]
This may be related to the post-1.7.10 RF power changes that McJty mentioned in #2750.

I have an ActuallyAdditions battery in my inventory that holds 8 million RF. It's set to recharge any RF-powered items also in the inventory. If I have an AE2 wireless terminal in my inventory, that 8 million RF is drained in less than 10 seconds.

- Minecraft Version: 1.10.2
- AE2 Version: 
- Forge Version: 2185

actuallyadditions-1.10.2-r98
appliedenergistics2-rv4-alpha-11

Cheers!

**Comment by GuntherDW** [comment]
Other mods like Flux Networks have the same issue.
https://github.com/SonarSonic/Flux-Networks/issues/39

In 1.7.10 some ExtraCells wireless terminals also had this issue.
