### ISSUE TITLE
3D Model for the ME Drive

### ISSUE THREAD

**Issue by TheVanoq** [AppliedEnergistics/Applied-Energistics-2#2772]
This is a feature request.

I would love to have a config option to enable "3D models", atleast for the ME Drive. I'm thinking of having the drives pop out the front just a little bit and not have a flat surface in front. A little bit like Refined Storage does it. I believe that it would give AE2 a more futuristic look and fit well, especially with tech themed builds.

**Comment by yueh** [comment]
No.
