### ISSUE TITLE
[Question] Add-ons for rv4 

### ISSUE THREAD

**Issue by viper2g1** [AppliedEnergistics/Applied-Energistics-2#2773]
I'm curious about the state of the mod. It's been used on 1.10.2 for a while now and I've seen it remarked online that most people consider it, in its current state, stable.. Myself included.

Based on that comment what is the timeline to enable add-ons?  

Mods like OpenComputers, for example, cannot interface with AE2.

And for clarification, I'm referring to this statement from the download page: "Alpha builds are not compatible with any AE2 addons"

Issue from OpenComputers:

https://github.com/MightyPirates/OpenComputers/issues/2206

**Comment by viper2g1** [comment]
#https://github.com/MightyPirates/OpenComputers/issues/2206

**Comment by viper2g1** [comment]
MightyPirates/OpenComputers#2206

**Comment by yueh** [comment]
It is up to the addon devs to decide when they want to support a specific version.

Alpha has no guarantee regarding the API stability, thus it might change at any point and make supporting them not as easy as stable or beta.

**Comment by viper2g1** [comment]
Thank you for the reply and the fantastic mod!
