### ISSUE TITLE
Report bug 

### ISSUE THREAD

**Issue by N3rdG4mer** [AppliedEnergistics/Applied-Energistics-2#2774]
Hi, I have a bug that is happening with the Applied mod, I put it in my modpack 1.10.2, the world tps goes down to the point of not being able to play

- Minecraft Version: 1.10.2
- AE2 Version: rv4.alpha build 11
- Forge Version: 12.18.3.2221

**Comment by mindforger** [comment]
is the ME system chunkloaded? does it have enough power, does it have energy cells installed (reuired to buffer high power spikes)
maybe provide screenshots and overall more details please
