### ISSUE TITLE
ME Storage Bus showing only one stack of an item but I have millions.

### ISSUE THREAD

**Issue by jk1895** [AppliedEnergistics/Applied-Energistics-2#2776]
I hooked up a storage bus to a quantum storage (DSU thing for 1.10.2)
https://mods.curse.com/mc-mods/minecraft/235121-quantumstorage
In the ME system it shows only 64 items but I have much more.
When I take one stack out it shows all the time 64 BUT! when I put it back very fast (yes, priority is higher than the drives) then it goes to the disks. When I put it slowly in by clicking one stack after stack it goes to the quantum storage.
Storage Drawers don't have this issue, it seems. Refined Storage is working with quantum storage flawlessly.

Another bug:
Ender IO Ender Energy Conduits don't work properly with the energy acceptor. Tier 2 and 1 conduits do (but they are to weak).
Also Flux Networks plugs don't work with the acceptor.

Last bug:
I have problems with JEI. When I search something in the JEI bar, and the ME storage is opened, then AE is delets my entry.
Another scenario, when I search something in the ME console bar and the result has more than 1 page, I scroll to page 2 for example, then it jumps back to page 1.

#### Environment
Windows 10 64 bit, 16 GB ram, Intel i5-4670K, 1080 GTX
Only SP. I Play FTB Sky Factory 3 version 3.0.6
I installed Optifine (deactivated Surge) and ArchitectureCraft-1.7.1. 
QuantumStorage version 1.10.2-3.2.19
JEI version 1.10.2-3.14.3.403

- Minecraft Version: 1.10.2
- AE2 Version: appliedenergistics2-rv4-alpha-11
- Forge Version: 12.18.3.2215
- MCP 9.32

**Comment by yueh** [comment]
#2550
