### ISSUE TITLE
Discord and Official AE Team

### ISSUE THREAD

**Issue by JosephRymer** [AppliedEnergistics/Applied-Energistics-2#2777]
Hello @yueh I'm a bit concerned. I work with the Discord team for AE and own the server that we set up for the AE mod and was wondering if you could clarify if any of our team on Discord would be allowed to join you or if that team has been pushed away so to speak and your just going to develop only with the current team you have. So essentially I'm trying to find out if are discord team can merge with yours and we can all work together on one team. or if we are not going to do that and are team needs to go away.

**Comment by yueh** [comment]
Having more developers is usually good.

But we simply cannot invite anyone, who wants to join just by claiming some intention to help.
If they actually need to help already, like having successfully contributed (but not trivial things like fixing some typos).

Currently there is not enough demand to have someone just managing tickets or other support systems.
Thus having clicked on "create new discord channel" is not really sufficient as contribution. Still any team member could decide to provide support on new platforms, but that should emerge from the team itself.

**Comment by JosephRymer** [comment]
ok thanks for the info
