### ISSUE TITLE
Export bus ignores redstone signal.

### ISSUE THREAD

**Issue by Asphodan** [AppliedEnergistics/Applied-Energistics-2#2782]
#### Description

[Emitter is set to put out redstone signal when Quartz is >100.  We can see that it is not.](https://cloud.githubusercontent.com/assets/1139830/22576865/dd3ae098-e983-11e6-9845-94894f03a05a.png)  

[The export bus *does* have a redstone card. And if I hadn't removed Quartz from its config window, it would still be pumping out items.](https://cloud.githubusercontent.com/assets/1139830/22576887/10dd627c-e984-11e6-814c-5e609aef9a0b.png)

What is strange to me is that this very same configuration works for other items just a few floors below. I can not determine why the emitters / export busses here are not working.
#### Environment
Direwolf 1.17 - 1.10.0
- Minecraft Version: 1.17
- AE2 Version:  RV2-stable-10
- Forge Version:  7.10.99.99

**Comment by drunkripper** [comment]
From the screenshot, the export his has nothing to export. Export buses will only export what they are told too.
