### ISSUE TITLE
There have a big BUG

### ISSUE THREAD

**Issue by Juese** [AppliedEnergistics/Applied-Energistics-2#2783]
I am  Chinese .My English is poor .If you can konw Chinese and QQ .My QQ is 762551738.
http://www.tudou.com/programs/view/ZGlNUc0Gj1U/?resourceId=0_06_02_99 
appliedenergistics2-rv3-beta-6   MC1.7.10

**Comment by xsun2001** [comment]
我建议你发到youtube上，要不然美国地区可能会看不见的。

**Comment by Juese** [comment]
然而.....怎么发Q.Q




------------------ 原始邮件 ------------------
发件人: "徐晨曦";<notifications@github.com>;
发送时间: 2017年2月3日(星期五) 下午3:42
收件人: "AppliedEnergistics/Applied-Energistics-2"<Applied-Energistics-2@noreply.github.com>; 
抄送: "偏挚、"<762551738@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [AppliedEnergistics/Applied-Energistics-2] There have a big BUG(#2783)




我建议你发到youtube上，要不然美国地区可能会看不见的。

**Comment by Juese** [comment]
...如果你可以看到这个BUG视频并帮我反馈一下我会特别感谢你...而且这个BUG非常严重、如果你也看不到视频我可以告诉你怎么进行这个BUG




------------------ 原始邮件 ------------------
发件人: "徐晨曦";<notifications@github.com>;
发送时间: 2017年2月3日(星期五) 下午3:42
收件人: "AppliedEnergistics/Applied-Energistics-2"<Applied-Energistics-2@noreply.github.com>; 
抄送: "偏挚、"<762551738@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [AppliedEnergistics/Applied-Energistics-2] There have a big BUG(#2783)




我建议你发到youtube上，要不然美国地区可能会看不见的。

**Comment by xsun2001** [comment]
It is a bug that allows us to get unlimited items.
If I connect a ME diver and a ME Terminal by ME Smart Cables, and quickly damage the cable,the items in the diver will stay at the Terminal and you can get them.But the items still at the diver.So you can get unlimited items.
AE version:appliedenergistics2-rv3-beta-6
MC version:1.7.10

**Comment by xsun2001** [comment]
@Juese 你把视频发到1563770452@qq.com中，我来上传

**Comment by xsun2001** [comment]
see this demo https://youtu.be/plIHKY9V6OM

**Comment by mindforger** [comment]
the issue is known, but 1.7.10 is not supported anymore

there MAY BE and final release update soon

https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2276

you MAY compile a version for yourself with that fix

**Comment by xsun2001** [comment]
Well, thank you very much!
