### ISSUE TITLE
Error found - ME Controller instantly breaks in certain spots

### ISSUE THREAD

**Issue by Lukas45** [AppliedEnergistics/Applied-Energistics-2#2785]
**_EDIT:_** Error found while making bug report, still posting though.
#### Description
https://i.gyazo.com/01037652b0b6515a91299faf905e9eaf.mp4
When I place an ME Controller in a specific spot (or rather 3 specific spots), the block instantly breaks and drops (in this case dragged by my magnet). I can place any other block there just fine (for the moment it's filled by Cobblestone), it's only the ME Controller.
It only started happening yesterday, I believe around the time where I set up my Wireless system (placing the Security Terminal). I came back a bit later and found 3 ME Controllers had randomly broken off, and I could not replace them in those certain spots where they had broken off. I could place cables and other ME parts in the spots just fine. I could place the ME Controllers at any other spot just fine, both to break the ME System, and be part of it.

**_EDIT:_** Since I'm sharing my ME System with another player, I made him a Wireless Terminal and a Biometric Card (Deposit, Search, Autocraft, Build). Since he hadn't been online for a few days, I placed the 2 items on the wall (with Draconic Evolution's Place Item feature) for when he would be back.
**Breaking and replacing the Security Terminal fixed my issue, and the 3 spots has been filled with the ME Controllers again.**
I had fine access to the Security Terminal before, even made an additional Biometric Card (Deposit/Withdraw) without issues.

#### Environment
ME System contains: 4x4 border cube of ME Controllers, 4 Crafting Units, 4 1k Crafting Storage, 8 ME Drives (with 10 1k Drives in total), 5 Importers (linked to an MultiStorage Ender Chest), 1 Storage Port (linked to a Drawer Controller and a lot of drawers), 4 Interface Blocks, 2 Molecular Assemblers, 1 pair of Quantum Rings, 1 Crafting/Pattern/Interface Terminals, 2 Wireless Access Points - 20 upgrades in each (1 in the 4x4 Cube, 1 at the other end of the Quantum Link (~3000 blocks away)) and a Security Terminal. And ~100 cables.
Gains power from Immersive Engineering HV Connectors'
I am the owner of the ME System (placed every piece of the system)

This is on a small dedicated MP server.

- Minecraft Version: 1.10.2
- AE2 Version: rv4 alpha 11
- Forge Version: 12.18.3.2221

**Comment by yueh** [comment]
This is exactly the intended and documented behaviour.

**Comment by Lukas45** [comment]
Is it though, despite me being the original owner of the system? 
I should have full access to it, including placing the controllers, which I still could at any other spot, except those 3.

**Comment by Lukas45** [comment]
After doing some more reading up on it, I guess the overall bug is that the permissions blocked me (as the owner) partially out, which shouldn't be possible.
The no placing block works as it should, except:
Only happened in 3 specific spots, and only(!) with ME Controllers.
Do note that there was no Biometric Card in the Security Terminal itself (if that has got something to do with it, then my bad I guess?).

Or should I open a new report on it?
