### ISSUE TITLE
Redstone Card not working, 1.10.2

### ISSUE THREAD

**Issue by NillerUdenDild** [AppliedEnergistics/Applied-Energistics-2#2788]
I'm using an Export Bus to export items from my system to a machine. I've put a Redstone Card in it, to control when it exports. The thing is, no matter which of the 4 redstone modes I pick, the behaviour is exactly the same - Redstone signal on = Export stops, redstone signal off = Export runs. The Export Bus also had a Capacity Card, Fuzzy Card & Acceleration Card. Feel free to ask for additional details :)

The bug occured on a server, running the "Dongland" modpack, version 2.3.

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-9
- Forge Version: 12.18.3.2221

**Comment by yueh** [comment]
All 4 modes work fine for me.

Maybe another mods interferes with it? Did you also report it to the modpack author?

**Comment by NillerUdenDild** [comment]
I am the modpack author :)

Alright, I'll do some digging into which mods could be interfering, thanks for the fast response.
