### ISSUE TITLE
Add an option for meteors to not make craters (i.e. spawn underground only in a single ball of skystone)

### ISSUE THREAD

**Issue by Barhandar** [AppliedEnergistics/Applied-Energistics-2#2789]
It would accomplish several things at once: allow still having meteors without landscape destruction that gets boring quickly, raise the need for meteor compass, and help compass work by not having any loose skystone blocks around after the main meteorite is mined.

**Comment by yueh** [comment]
Already an option.

**Comment by belathus** [comment]
I'm glad that this is already an option. I have one question: how would I allow meteors to only spawn underground?
