### ISSUE TITLE
Bug with crafting after disabling channels

### ISSUE THREAD

**Issue by deeredman1991** [AppliedEnergistics/Applied-Energistics-2#2790]
While playing Sky Factory 2.5.1 when I disable channels I am unable to craft certain objects...So far I have found that Transfer Pipes (from extra utilities) and 64k Fluid Storage Cells (from extra cells) are not craftable.

When shift+click the "?" in NEI it takes me out of the crafting preview screen but it does not put the items in the crafting table. When I manually put the items in; I can see it in the crafting G.U.I but when I try to pull it out nothing happens. Shift+Clicking doesn't work either, and I cannot create a pattern for either item as well. The pattern simply will not encode when I click the button to encode.

**Comment by mindforger** [comment]
are the recipes (with enabled channels) working the exact same way ? or were they altered in some way?

**Comment by deeredman1991** [comment]
I believe they may have been altered by the creators of Sky Factory. That being said, I was running on a server, I just loaded it up in singleplayer for 1.5.6 and the issue seems to have been fixed, however the recipes are different now (I assume their original recipes)

**Comment by mindforger** [comment]
disable channels on both client and server, see if that solves your problem, as the client uses items that may not be present on the server for displaying the recipes
