### ISSUE TITLE
FakePlayerName for annihilation planes

### ISSUE THREAD

**Issue by Hallowhead1** [AppliedEnergistics/Applied-Energistics-2#2793]
I am trying to figure out the name to trust inside my region and can't for the life of me find it!

Please someone let me know of what it is

**Comment by VT-14** [comment]
If you are using FTB Utilities, then the command you want is:
/ftb team config ftbu.fake_players true

If you are using something else, then I don't know.

**Comment by Hazmatik** [comment]
If you are using GriefPreventionPlus there is a command /autotrust that will trust any player real or fake that tries to place blocks within a certain time after the command is entered (i think 30 seconds, but not sure)

**Comment by yueh** [comment]
Annihilation planes do not use a fake (or real) player at all for block breaking. It only uses the default one for a simple check, if a block is breakable, but this covers mainly the (optional) vanilla spawn protection.
