### ISSUE TITLE
Unable to remove water

### ISSUE THREAD

**Issue by woodzykiler** [AppliedEnergistics/Applied-Energistics-2#2794]
Useing the fluid wireless terminal im unable to remove water from the ME system with buckets, or fluid busses. but i can put water in just fine
#### Description

Read above.
the water to be extracted with a bucket from the terminal, and fluid buses when told to export water
#### Environment

Multi player, no crash log is not crashing game
- Minecraft Version: 
1.7.10
- AE2 Version:
2 rv3 beta 6 
- Forge Version:
 ForgeMultipart-1.7.10-1.2.0.345-universal
ForgeRelocation-1.7.10-0.0.1.4-universal
ForgeRelocationFMP-1.7.10-0.0.1.2-universal
I guess?

**Comment by mindforger** [comment]
" fluid wireless terminal " ? since when is ExtraCells part of Applied Energistics? did i miss the fusion of those mods?
