### ISSUE TITLE
Slow crafting and interrupting if spam shift-clicking for many stacks.

### ISSUE THREAD

**Issue by jk1895** [AppliedEnergistics/Applied-Energistics-2#2795]
Hello,
when I spam shift click an item to craft lots of it, for example iron blocks than it interrupts after a couple of clicks because it takes the items out of the crafting grid although there are enough in the system.
Also the crafting is a bit "slow" I can watch the stack growing and sometimes it stops in the middel for a moment. Back then in 1.7.10 that was instant if I remember correctly. Maybe the interrupting is caused by this "slowness"

- Minecraft Version: 1.10.2
- AE2 Version: rv4-apha11
- Forge Version: 12.18.3.2219
- All the mods pack

Thank you very much.

PS. Are you still working on this awesome mod? It's so silent around it...

**Comment by mindforger** [comment]
sounds like an power issue, this behaviour is known also in 1.7.10

make sure you have enough energy cells installed

to give you an image: 
if your system has an internal buffer of 1k RF, it can only consume 1k in 1 tick and refill it from your source, even if your source provides millions of RF/tick ou will not exceed 1k RF/tick ... energy cells increase your system buffer

**Comment by jk1895** [comment]
Thank you very much for the fast response.
Yes, you have right. I cheated a creative energy cell for testing and the interruption is gone. The "slow" crafting (seeing stack growing) still persists but this no real problem.
I'm sorry for steeling your time.
Thanks again.

**Comment by mindforger** [comment]
you can close this issue with the close button right beside the comment button, i'll close it for you :)

**Comment by jk1895** [comment]
Thank you for closing the issue. I didn't know that.

Sorry for my bad English. It's hard to describe this all.

The "slow" ("" because it's not really slow but compared to 1.7.10 or Refinded Storage it is) crafting is normal crafting trough the 9x9 grid without assemblers.
But like I said it's not a big thing. Maybe it was the same in 1.7 but I forgot.

**Comment by mindforger** [comment]
your english is fine enough to understand everything :)

like youeh already hinted in the other report, there are issues with the way Refined Storage presents items to the me system that may cause a slowdown
