### ISSUE TITLE
Spatial I/O doesn't work in MP

### ISSUE THREAD

**Issue by wtywtykk** [AppliedEnergistics/Applied-Energistics-2#2796]
#### Description

Spatial Pylons at the end of each pylon don't connect to the pylon and cables sometimes don't attach to them. 
If I managed to build a valid structure and activate the spatial i/o block, the server produces an error message and nothing happens on client side.

Here's the server side log:
http://pastebin.com/Aua7cw30
and client side log:
http://pastebin.com/KdUDnjSg

![ss3](https://cloud.githubusercontent.com/assets/13284789/22857335/4f077ad6-f0de-11e6-8034-6dd568f0e665.jpg)
![ss1](https://cloud.githubusercontent.com/assets/13284789/22856873/8f67abc2-f0d5-11e6-9160-21f2c7fc5b47.jpg)
![ss2](https://cloud.githubusercontent.com/assets/13284789/22856874/8f68e0b4-f0d5-11e6-9234-9d52819ce50d.jpg)
#### Environment

This problem is only found in MP
- Minecraft Version: 1.7.10
- Server: KCauldron-1.7.10-1614.201
- AE2 Version: appliedenergistics2-rv2-stable-10
- Forge Version: 1.7.10-Forge10.13.4.1614-1.7.10

**Comment by wtywtykk** [comment]
I think it's related to some kind of block update problem. It seems that AE doesn't update the network after the spatial pylon is placed. The network tool shows that the new blocks didn't join the network.

**Comment by GuntherDW** [comment]
Two things:

1) 1.7.10 is no longer supported
2) This is caused by a third party server software, kcauldron, which is also not supported.
Only "vanilla" forge is supported

**Comment by mindforger** [comment]
Also rv2 ist like ages old, update to rv3 beta6

**Comment by wtywtykk** [comment]
I think I have found out what caused this problem. KCauldron changed the return value of getWorld().getPendingBlockUpdates from a list of net.minecraft.world.NextTickListEntry to a list of kcauldron.BlockUpdateEntry, so it's a problem caused by KCauldron. PS: I'm not familiar with java, so there maybe mistakes.

**Comment by wtywtykk** [comment]
rv3 beta6 doesn't work.

**Comment by yueh** [comment]
KCauldron issue and unsupported.
