### ISSUE TITLE
Both ThaumicTinkerer and AE2 can't work together

### ISSUE THREAD

**Issue by SnoIcarus** [AppliedEnergistics/Applied-Energistics-2#2798]
Both ThaumicTinkerer and AE2 can't work together

#### Description
AE version : rv3-beta-6 (The lastest version with 1.7.10)
ThaumicTinkerer version : 164(The lastest version with 1.7.10)

The ThaumicTinkerer website : https://minecraft.curseforge.com/projects/thaumic-tinkerer

**The crash report：**
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 17-2-15 下午5:36
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: appeng.api.util.IConfigManager.registerSetting(Lappeng/api/config/Settings;Ljava/lang/Enum;)V
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: appeng.api.util.IConfigManager.registerSetting(Lappeng/api/config/Settings;Ljava/lang/Enum;)V
	at appeng.core.AEConfig.<init>(AEConfig.java:137)
	at appeng.core.AppEng.preInit(AppEng.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 889932344 bytes (848 MB) / 2249719808 bytes (2145 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 1 total; -Xmx6144M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D6 154 mods loaded, 154 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	BetterFonts{1.1.3} [BetterFonts] (minecraft.jar) 
	UCH	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UCH	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UCH	Aroma1997Core{1.0.2.16} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UCH	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCH	InputFix{1.7.10-v5} [InputFix] (minecraft.jar) 
	UCH	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCH	PaneInTheGlass{1.2.0} [Pane In The Glass CoreMod] (minecraft.jar) 
	UCH	ChocoPatcher{1.1} [Choco Patcher] (minecraft.jar) 
	UCH	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCH	FastCraft{1.23} [FastCraft] (fastcraft-1.23.jar) 
	UCH	FamiliarsAPI{1.7.10} [Familiars API] (FamiliarsAPI-1.7.10.jar) 
	UCH	non_update{1.0} [NonUpdate] (NonUpdate-1.7.10-1.0build7.jar) 
	UCH	DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar) 
	UCH	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCH	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCH	dungeonpack{1.7.10-1.0} [Dungeon Pack] ([1.7.10]更多地牢——DungeonPack[心殇搬运]-V1.0.jar) 
	UCH	grim3212core{V0.2 - 1.7.10} [Grim3212 Core] ([1.7.10]精灵球前置Grim3212-Core-1.7.10.jar) 
	UCH	pokeball{V0.1 - 1.7.10} [Pokeball] ([1.7.10]精灵球——Pokeball-V0.1.jar) 
	UCH	AutoSapling{1.0} [AutoSapling] ([1.7.10]自动树苗种植——Auto Sapling-V1.1.jar) 
	UCH	craftSaddle{1.72.0.3} [Craft Saddle] ([1.7]合成鞍和命名牌、腐肉烧炼皮革craftSaddle.jar) 
	UCH	deconstruction{2.2.6} [The Deconstruction Mod] ([MC1.7.10]deconstruction[v2.2.6].jar) 
	UCH	TravelDokodemoDoor{3.0.0-MC1.7.2} [锟斤拷锟斤拷锟角傦拷锟脚傦拷锟絟锟紸 (Anywhere Travel Door)] ([任意门]TravelDokodemoDoor-3.0.0-MC1.7.2.jar) 
	UCH	Torcherino{2.2s} [Torcherino] ([加速火把]Torcherino-1.7.10-2.2s.jar) 
	UCH	animalsPlus{1.2} [Animals+] ([动物附加]1.7animalsPlus-1.2cn.jar) 
	UCH	MoreHome_MCBBS{0.7.0} [MoreHome_MCBBS] ([单机指令]morehome-0.7.0_1710.jar) 
	UCH	MoreHome{0.7.0} [MoreHome] ([单机指令]morehome-0.7.0_1710.jar) 
	UCH	craftnstar{0.2.1} [Craftable Nether Star +] ([地狱物品合成]craftnstar-1.7.10-0.2.1.jar) 
	UCH	buffedtools{1.1.1710.1} [Buffed Tools] ([属性工具]BuffedTools-1.1.1710.7[L_RweI汉化].jar) 
	UCH	TwilightForest{2.3.7} [The Twilight Forest] ([暮色森林]Twilightforest-1.7.10-2.3.7.jar) 
	UCH	bookshelf{1.0.4.187} [Bookshelf] ([更好的附魔前置]Bookshelf-1.7.10-1.0.4.187.jar) 
	UCH	eplus{4.0.0..73} [Enchanting Plus] ([更好的附魔]EnchantingPlus-1.7.10-4.0.0.74.jar) 
	UCH	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCH	Thaumcraft{4.2.3.5} [Thaumcraft] ([神秘]Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCH	harvestcraft{1.7.10j} [Pam's HarvestCraft] ([潘马斯丰收工艺][汉化]Pam's HarvestCraft 1.7.10Lb.jar) 
	UCH	thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin] ([神秘NEI查询]Thaumcraftneiplugin-1.7.10-1.7a.jar) 
	UCH	IC2{2.2.827-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.827-experimental.jar) 
	UCH	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCH	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCE	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (Appliedenergistics2-rv3-beta-6.jar) 
	UCH	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] ([神秘工匠]ThaumicTinkerer-2.5-1.7.10-164.jar) 
	UCH	tcinventoryscan{1.0.11} [TC Inventory Scanning] ([神秘时代库存扫描]tcinventoryscan-mc1.7.10-1.0.11[寒冰之刃汉化].jar) 
	UCH	bt{1.0.2} [NotEnoughThaumcraftTabs] ([神秘标签]NotEnoughThaumcraftTabs-1.0.2.jar) 
	UCH	ThaumicHorizons{1.1.9} [Thaumic Horizons] ([神秘视界]thaumichorizons-1.7.10-1.1.9.jar) 
	UCH	NodalMechanics{1.7.10R1.0} [NodalMechanics] ([神秘附属节点学]NodalMechanics-1.7-1.0-7.jar) 
	UCH	mdeco{0.3.5} [Magical Decorations] ([神秘附属魔法装饰品]MagicalDecorations-0.3.5.jar) 
	UCH	InfernalMobs{1.6.6} [Infernal Mobs] ([精英怪物]InfernalMobs-1.7.10.jar) 
	UCH	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel-1.7.10-3.5.1[TFCN].jar) 
	UCH	Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UCH	Backpack{2.0.0} [Backpack] (Backpacks-Mod.jar) 
	UCH	BambooMod{Minecraft@MC_VERSION@ var@VERSION@} [BambooMod] (Bamboo-2.6.8.5.jar) 
	UCH	BetterTitleScreen{1.7.10-1.1} [Better Title Screen] (BetterTitleScreen-1.7.10-1.1.jar) 
	UCH	bigtrees{1.6.4} [BigTrees] (BigTrees-Mod-1.7.10.jar) 
	UCH	CoFHCore{1.7.10R3.1.3} [CoFH Core] (CoFHCore-[1.7.10]3.1.3-327.jar) 
	UCH	BuildCraft|Core{7.1.20} [BuildCraft] (buildcraft-7.1.20.jar) 
	UCH	BuildCraft|Robotics{7.1.20} [BC Robotics] (buildcraft-7.1.20.jar) 
	UCH	BuildCraft|Factory{7.1.20} [BC Factory] (buildcraft-7.1.20.jar) 
	UCH	BuildCraft|Transport{7.1.20} [BC Transport] (buildcraft-7.1.20.jar) 
	UCH	BuildCraft|Energy{7.1.20} [BC Energy] (buildcraft-7.1.20.jar) 
	UCH	BuildCraft|Silicon{7.1.20} [BC Silicon] (buildcraft-7.1.20.jar) 
	UCH	BuildCraft|Builders{7.1.20} [BC Builders] (buildcraft-7.1.20.jar) 
	UCH	Forestry{4.2.16.64} [Forestry for Minecraft] (forestry_1.7.10-4.2.16.64.jar) 
	UCH	BuildCraft|Compat{7.1.5} [BuildCraft Compat] (buildcraft-compat-7.1.5.jar) 
	UCH	cfm{3.4.8} [?9MrCrayfish's Furniture Mod] (cfm-3.4.8-mc1.7.10.jar) 
	UCH	ChunkAnimator{@VERSION@} [Chunk Animator] (ChunkAnimator-MC1.7.10-1.0.1.jar) 
	UCH	BuildMod{v1.0} [Build Mod] (coroutil-1.7.10-1.1.5.jar) 
	UCH	CoroPets{v1.0} [CoroPets] (coroutil-1.7.10-1.1.5.jar) 
	UCH	CoroAI{v1.0} [CoroAI] (coroutil-1.7.10-1.1.5.jar) 
	UCH	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.7.10-1.1.5.jar) 
	UCH	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.7.10-1.1.5.jar) 
	UCH	DragonMounts{r41-1.7.10} [Dragon Mounts] (DragonMounts-r41-1.7.10.jar) 
	UCH	DummyCore{1.13} [DummyCore] (DummyCore1.13.jar) 
	UCH	DynamicLights{1.3.9} [Dynamic Lights] (DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_onFire{1.0.5} [Dynamic Lights Burning Entity Module] (DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] (DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] (DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_otherPlayers{1.0.8} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_thePlayer{1.1.4} [Dynamic Lights Player Light Module] (DynamicLights-1.7.10.jar) 
	UCH	DefaultMobPack{1.7.10} [DefaultMobPack] (FamiliarsDefaultMobPack-1.7.10.jar) 
	UCH	ExtendedFamPack{1.7.10} [ExtendedFamPack] (FamiliarsExtendedFamPack-1.7.10.jar) 
	UCH	GrimoireOfGaia{1.0.0} [Grimoire of Gaia 3] (GrimoireOfGaia3-1.7.10-1.2.7.jar) 
	UCH	heartdrop{1.3.2} [Heart Drop] (HeartDrop-1.7.10-1.3.2.jar) 
	UCH	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCH	IronChest{6.0.60.741} [Iron Chest] (ironchest-1.7.10-6.0.60.741-universal.jar) 
	UCH	je_calculation{0.3.4} [Just Enough Calculation] (JustEnoughCalculation-1.7.10-0.3.4.jar) 
	UCH	Mekanism{9.1.0} [Mekanism] (Mekanism-1.7.10-9.1.0.281.jar) 
	UCH	MekanismGenerators{9.1.0} [MekanismGenerators] (MekanismGenerators-1.7.10-9.1.0.281.jar) 
	UCH	MekanismTools{9.1.0} [MekanismTools] (MekanismTools-1.7.10-9.1.0.281.jar) 
	UCH	MineFactoryReloaded{1.7.10R2.8.1B1} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.1B1-113.jar) 
	UCH	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.1B1} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.1B1-113.jar) 
	UCH	MineFactoryReloaded|CompatAtum{1.7.10R2.8.1B1} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.1B1-113.jar) 
	UCH	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.1B1} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.1B1-113.jar) 
	UCH	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.1B1} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.1B1-113.jar) 
	UCH	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.1B1} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.1B1-113.jar) 
	UCH	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.1B1} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.1B1-113.jar) 
	UCH	MineFactoryReloaded|CompatForestry{1.7.10R2.8.1B1} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.1B1-113.jar) 
	UCH	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.1B1} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.1B1-113.jar) 
	UCH	MineFactoryReloaded|CompatIC2{1.7.10R2.8.1B1} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.1B1-113.jar) 
	UCH	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.1B1} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.1B1-113.jar) 
	UCH	MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.1.0.33-universal.jar) 
	UCH	ProjRed|Core{4.7.0pre12.95} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre12.95-Base.jar) 
	UCH	ProjRed|Exploration{4.7.0pre12.95} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre12.95-World.jar) 
	UCH	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.1B1} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.1B1-113.jar) 
	UCH	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.1B1} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.1B1-113.jar) 
	UCH	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.1B1} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.1B1-113.jar) 
	UCH	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.1B1} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.1B1-113.jar) 
	UCH	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.1B1} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.1B1-113.jar) 
	UCH	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.1B1} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.1B1-113.jar) 
	UCH	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.1B1} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.1B1-113.jar) 
	UCH	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.1B1} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.1B1-113.jar) 
	UCH	mobends{0.20.1} [Mo' Bends] (MoBends-0.20.1 for MC 1.7.10.jar) 
	UCH	modchulib{17a} [modchulib; for mc162_179] (ModchuLib_mc1_5_2-1_11_2-v17a.zip) 
	UCH	MouseTweaks{2.4.4} [Mouse Tweaks] (MouseTweaks-2.4.4-mc1.7.10.jar) 
	UCH	multimine{1.5.4port1710} [Multi Mine] (MultiMine-1.7.10.jar) 
	UCH	recipehandler{1.7.10} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.3(1.7.10).jar) 
	UCH	pcb{1.3} [Portable Craft Bench] (portablecraftbench-1.7.10-1.3.jar) 
	UCH	packchevsky{b5} [Potion Packs] (PotionPacks_1.7.10_b5.zip) 
	UCH	ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCH	ProjRed|Transportation{4.7.0pre12.95} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
	UCH	ProjRed|Compatibility{4.7.0pre12.95} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre12.95-Compat.jar) 
	UCH	ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCH	ProjRed|Fabrication{4.7.0pre12.95} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre12.95-Fabrication.jar) 
	UCH	ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar) 
	UCH	ProjRed|Expansion{4.7.0pre12.95} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
	UCH	mod_RadarBro{v1.9.9.9.9.9} [RadarBro] (RadarBro-Mod-1.7.10.zip) 
	UCH	woodenshears{0.0.1.4} [Wooden Shears] (SBM-WoodenShears-1.7.10-0.0.1b4-universal.jar) 
	UCH	shinyfood{1.5} [ShinyFood] (shinyfood-1.7.10-v1.5.jar) 
	UCH	redgear_core{2.1.3} [Red Gear Core] (RedGearCore-1.7.10-2.1.3.jar) 
	UCH	redgear_snowfall{2.2.2} [Snowfall] (Snowfall-Mod-1.7.10.jar) 
	UCH	soundfilters{0.8_for_1.7.X} [Sound Filters] (SoundFilters-0.8_for_1.7.X.jar) 
	UCH	stepup{4.0-mc1.7} [StepUp] (stepup-4.0-mc1.7.jar) 
	UCH	erebus{0.4.7} [Erebus] (TheErebus-0.4.7[汉化].jar) 
	UCH	thirstmod{1.8.14} [Thirst Mod] (thirstmod-1.8.14.jar) 
	UCH	tropicraft{v6.0.5} [Tropicraft] (tropicraft-6.0.5.jar) 
	UCH	Uncomplication{0.1.2.1.b77} [Uncomplication] (Uncomplication-1.7.10-0.1.2.1.b77.jar) 
	UCH	UnicodeFontFixer{1.1.9-mc1.7.10} [UnicodeFontFixer] (UnicodeFontFixer-1.1.9-mc1.7.10.jar) 
	UCH	AS_UpdateCheck{1.1.7} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.7.10.jar) 
	UCH	wawla{1.3.1} [What Are We Looking At] (Wawla-1.0.5.120.jar) 
	UCH	weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar) 
	UCH	werkbench{1.2.56} [Werkbench] (Werkbench-1.7.10-1.2.56.jar) 
	UCH	yarr_cutemobmodels{1.0.9} [Cute Mob Models] (yarrcutemobmodels-1.0.9-1.7.10.jar) 
	UCH	ZAMod{v1.10} [Zombie Awareness] (zombieawareness-1.7.10-1.10.jar) 
	UCH	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCH	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCH	MCFrames{1.0} [MCFrames] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCH	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-0.0.1.2-universal.jar) 
	UCH	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	CoFHCore: -[1.7.10]3.1.3-327
	MineFactoryReloaded: -[1.7.10]2.8.1B1-113
	OptiFine Version: OptiFine_1.7.10_HD_U_D6
	Render Distance Chunks: 32
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 4.5.0 NVIDIA 378.57
	OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
#### Environment
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 889932344 bytes (848 MB) / 2249719808 bytes (2145 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 1 total; -Xmx6144M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 
	Minecraft Forge 10.13.4.1614 
	Optifine OptiFine_1.7.10_HD_U_D6 
	154 mods loaded, 154 mods active

**Comment by Zsashas** [comment]
Did this get resolved? Why did it get closed? Having this same issue...
