### ISSUE TITLE
AE2 network tool bypasses chunk protection from ftbutilities

### ISSUE THREAD

**Issue by wormzjl** [AppliedEnergistics/Applied-Energistics-2#2801]
It can be used to open chest and other protected inventories in claimed chunks

**Comment by drunkripper** [comment]
This would be a bug for ftbutils I do so believe

**Comment by mindforger** [comment]
not if the tool bypasses to fire an event, i can remember this has been an issue in the past for cauldron and other spigot-forge mashups, i can not remember if this has been dealt with and how

**Comment by wormzjl** [comment]
nope, this is on vanilla forge server

**Comment by XFactHD** [comment]
The problem is that the network tool uses onItemUseFirst to interact with blocks and that method does not fire the PlayerInteractEvent which means not even a Forge mod can block the interaction.

**Comment by mindforger** [comment]
>nope, this is on vanilla forge server

when the right click with network tool not comply with vanilla right click behaviour, it wont trigger hooks from other mods/cauldron, thus undermining the function of them
