### ISSUE TITLE
ME cables "segmenting" on game load

### ISSUE THREAD

**Issue by metnavman** [AppliedEnergistics/Applied-Energistics-2#2802]
This is SSP, on 1.7.10, using AE version rv3-beta-6 and forge 10.13.4.1614

This is happening every so often upon loading into my game. It happens on only one line of cabling that branches off a direct line to a Quantum Bridge. The cable in question is located in an RFTools dimension. It is connected to 2 Export Buses and 1 Import Bus, which are rendered completely inactive and unable to be interacted with. None of the cabling or buses work until I break and replace them, at which point they all go back to normal. There are 4 channels total on the line, of which 3 are on the line having this problem. The 4th channel is connected directly to the line going into the P2P network connection to the Quantum bridge and does not suffer this problem. The issue replicates across all cable types. Normal glass, Smart, and Dense in any combination down this one section are affected.

No other cables in my entire network (150+) channels have this issue, or any other issue when I change dimensions or log in/log out. Just wondering if anyone has seen anything like this before. Thanks!

http://imgur.com/a/5q7oD

**Comment by yueh** [comment]
This is usually caused by a corrupt chunk, which losses its tile entities. But for now there is no way to reproduce it even as well as 1.7.10 being no longer supported.
