### ISSUE TITLE
Server - Crystals Despawning

### ISSUE THREAD

**Issue by yepidoodles** [AppliedEnergistics/Applied-Energistics-2#2806]
#### Description
All Crystals despawn after they are fully grown for default despawning time.

#### Environment
- Minecraft Version: 1.10.2
- AE2 Version: rv4.alpha build 11
- Forge Version: 2221
- SpongeForge: 2221-5.1.0-BETA-2147
- Modpack: http://www.technicpack.net/modpack/172-dragontech-testserver.408937

**Comment by yueh** [comment]
We do not support sponge.

**Comment by yepidoodles** [comment]
Are you planning on supporting Sponge in the future? Because if not, I may as well stop using AE2.

**Comment by mindforger** [comment]
DISCLAIMER: I am not speaking as Contributor of AE2 now, this is only for your benefit.

this issue has almost nothing to do with Sponge and AE2, it is almost certain a plugin that optimizes server performance by constantly removing floating entities. Most common used plugins have a blacklist for the crystals.

Check your plugins for such an feature and setup the config to ignore the crystals.

This is not an AE2 to Sponge Compat Issue this is an Plugin to AE2 Compat Issue

**Comment by vallard192** [comment]
I think this is by design.  I'm not an AE2 Dev and could be reading the
code wrong, but only seeds say they won't despawn in the tooltip.  And only
seeds have this line of code:
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/1760113cd46e08178d0eda3a8233f4205a5f7973/src/main/java/appeng/items/misc/ItemCrystalSeed.java#L173

Once the seed is fully grown it loses it's "Despawn immunity."

There are a lot of ways to automatically pick up full grown crystals and
ignore the seeds... I'd suggest setting them up.

**Comment by mindforger** [comment]
@vallard192 don't quote me on that but i think this is only half right, as far as i can remember, the final crystals are spawned with a preset lifetime, resulting in some pluigins thinking the item is dropped accidentially and wiping them (to prevent item spam on the ground producing lag)

this could well be a function of sponge itself, cauldron had such an feature but blacklisted the crystals for the wipe, nolagg and other plugins did the same.

**Comment by vallard192** [comment]
Yeah.  I know almost every server I've seen try to do any kind of
optimization has some kind of "entity cleanup" and they almost always have
to configure it to ignore AE2 seeds + crystals and other in-world crafting
type mechanics.

My point was more you're not even promised that a pure crystal will not
despawn (unlike the seeds).  Its not an answer I really like giving... but
just don't leave them on the ground.  There are many many ways to
automatically pick up the pure crystals once the seeds finish growing.
