### ISSUE TITLE
Network restarting randomly after adding chargers

### ISSUE THREAD

**Issue by CidsADev** [AppliedEnergistics/Applied-Energistics-2#2808]
- Minecraft Version: 1.10 (Singleplayer)
- AE2 Version: rv4 alpha 11
- Forge Version: 12.18.3.2202

What happened:
After I added 3 chargers to my ME-network and automated them with EnderIO-cables, my network seems to be restarting in intervals of ~1 second. (only when they are running)
I have connected a creative EnderIO capacitor bank to an Energy Acceptor to make sure it is not because of a lack of power.

I also disabled Channels in the config.
The addon AE2 Stuff (0.6.0.7) is also installed.

I first isolated the part with the chargers and the bug continued. After breaking and rebuilding all AE blocks that were part of that build, the bug disappeared.

Example build where I was able to reproduce the bug:
![screenshot](https://cloud.githubusercontent.com/assets/25868587/23106674/33a62f6c-f6f1-11e6-98c1-b377c10563c2.JPG)
Note: It also happens with the creative energy cube from mechanism (although universal cable do not seem to transport power into the acceptor, enderIO conduits do), however does **not** appear with the creative energy cell (from AE2). I sadly do not have other means of transporting power into the acceptor as Flux Plugs/Points from Flux Networks do not connect either.

Honestly I am rather confused as to what the exact conditions for the bug to appear are. First I wasn't able to reproduce it with only charges (like in the screenshot above), so I continued to test. Then it appeared after adding advanced inscribers (from AE2 Stuff) to the build. Later I was able to reproduce the bug again without them after reopening the world and (in another test) in a new world (where the screenshot above is from).

**Comment by XFactHD** [comment]
The reason for this is a lack of power. That's also the reason why you couldn't reproduce this with AE's Creative Energy Cell. To fix this this you need to add Energy Cells or Dense Energy Cells Ro your system because the maximum amount of energy that can be consumed per tick is capped by the internal storage of your system.

**Comment by CidsADev** [comment]
Oh I wasn't aware of that cap. I never used storage cells in 1.7.10 and therefore assumed they wouldn't be needed.
In that case I'm sorry for the false bug-ticket.
