### ISSUE TITLE
Switch to MCMP rendering

### ISSUE THREAD

**Issue by Dhvagra** [AppliedEnergistics/Applied-Energistics-2#2809]
#### Description

The last couple of weeks I noticed that there are some silly rendering bugs (like the lighting error with the facades). Currently AE2 uses it's own rendering system for non-full blocks. 

This week, MCMP2 has had a public build, and devs (for example Charset by asie, or Refined Storage by raoulvdberge) are updating to that from MCMP1. My suggestion is that you implement the MCMP2 multipart rendering system in AE2. This way you don't _need_ to provide covers per se, because people can use 'third party' covers like SimpleCovers by bdew, or Chisels & Bits.

There's this very intelligent bloke, I believe he is called @amadornes, and he might want to help you with the case.

I think the implementation of MCMP can find a good spot in the hearts of the AE2 fans.

#### Environment

- Minecraft Version:  1.10.2+
- AE2 Version: rv3+
- Forge Version: 1.10.2+

**Comment by yueh** [comment]
Not possible until it is part of forge.
