### ISSUE TITLE
Wireless terminal interaction with Quintuple battery from Actually Additions.

### ISSUE THREAD

**Issue by demethan** [AppliedEnergistics/Applied-Energistics-2#2810]
https://github.com/Ellpeck/ActuallyAdditions/issues/652 for reference. 

I'm playing ATM-Expert mode recently and crafted a Wireless Interface from AE2. Once in my inventory it drained my Quintuple battery from AA in seconds. I recharged the battery twice before I could figure out it was the AE2 terminal.

Just posting it here as I am not sure what mode is the culprit.

I didn't try to reproduce in single player.

Actually Additions 1.10.2-r98
AE2 RV4-alpha-11

**Comment by VT-14** [comment]
#2768.  A newer version with that fix hasn't been released yet.

**Comment by demethan** [comment]
Thx much
