### ISSUE TITLE
Inscribers stored power does not show properly on Waila(Hwyla)

### ISSUE THREAD

**Issue by DeadSix27** [AppliedEnergistics/Applied-Energistics-2#2811]
Found no related issue (other than https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2743 , but that is about channels, which work just fine for me)

![image](https://cloud.githubusercontent.com/assets/1492505/23211841/3aeb7bdc-f904-11e6-8b98-83249702eb54.png)

Power is always 0 AE/ 1,5 kAE (on all 3 inscribers, it doesn't matter where I connect the cable to)

- AE2 Version: https://github.com/AppliedEnergistics/Applied-Energistics-2/commit/1760113cd46e08178d0eda3a8233f4205a5f7973
- Forge Version: `1.10.2-forge1.10.2-12.18.3.2234`

**Comment by mindforger** [comment]
try it out while directly powering it, if i remember right it was either only working while beeing directly powered or while powered by network, just to confirm the issue :)

**Comment by DeadSix27** [comment]
By directly, I assume you mean with a non AE power cable, e.g EnderIO conduits and yes, I can confirm it shows up then.

**Comment by mindforger** [comment]
well then yes, this was by design then :) ... i thought i mixed that up

they only use the buffer when powered directly ... does the controller have such an indicator, as this one is having an buffer that contributes to the network total capacity where the inscribers don't (more or less like the acceptor if i remember correct)

**Comment by DeadSix27** [comment]
Ah, okay, interesting. Well in that case, time to close this issue.

**Comment by mindforger** [comment]
if you think so? i would leave it as an improvement, as indicating AE could probably be suppressed when having no power stored in my opinion at least, as this seem to confuse at least **some** people
