### ISSUE TITLE
Issue with auto-crafting items which require printed Silicon.

### ISSUE THREAD

**Issue by akatosh100** [AppliedEnergistics/Applied-Energistics-2#2812]
Hello, my issue is with a inscriber on my ME system. 

I'm using what seems to be the traditional 5 inscriber setup to automate the creation of processors. 
It looks like this: https://puu.sh/ueJBn/8621a56223.png  https://puu.sh/ueJAx/7a9a877bf8.png  

The orange channel are my 4 press inscribers and the yellow channel is my processor inscriber. I have the 4 press ones with interfaces on the back with their corresponding recipes for the printed circuit, and ME import buses on the front for extraction.  

The processor inscriber has 2 export buses, one on the bottom for silicon and one on the side for redstone. I use an interface on the top with the corresponding recipes for the 3 processor types. 

My issue occurs when I request an item to be made that requires a processor, when the system doesn't have printed silicon in storage. The Inscriber meant for making printed silicon will stop making silicon and the whole process will jam. Note; when I request just printed silicon from the ME terminal it makes it just fine, it only freezes up when I request something in which it needs to make printed silicon.   

I saw some other issues opened with similar issues as mine but none of their problems seemed to be the same cause as mine.

- Minecraft Version:  1.7.10
- AE2 Version: rv3-beta-6
- Forge Version:  7.10.99.99

**Comment by mindforger** [comment]
i can not see ANY energy cell in your system, add at least one to prevent power surges :) 

(no, your input is irrelevant to this)

**Comment by akatosh100** [comment]
I put one on the system but I'm still having the same problem. Again; the system makes everything else fine its just printed silicon.

**Comment by CraftMinerKyle** [comment]
Do you have any other mods in this pack? Try using other mods to help your automation process. Also, isn't the output slot in Inscribers underneath them, like furnaces? I that is so, that could be your setup problem, not a coding problem.

**Comment by mindforger** [comment]
No, output is the middle slot you wont be able to press processors if it were the Button ... Most likely a power issue, will close it because has not been answered in ages
