### ISSUE TITLE
AE2 + RS replicatable dupe bug.

### ISSUE THREAD

**Issue by Duncyn** [AppliedEnergistics/Applied-Energistics-2#2813]
I found a dupe bug with the ae2 interface and refind storadge interfaces. It dupes when they try to keep the same items in them and are conected with storage busses. They dupe items when ae2 tries to extract the items to the refind storage interface.

#### Description
On the latest ae2 version: 12/31/2016
Refind Storage version: 1.2.14
If you try to keep 1 stone in 2 seperate slots in the rs interface and 1 stone in one of the slots in the ae2 interface and export stone from the tiny ae system to the tiny rs system there will be a stone increase in the rs interface. (Can work with larger numbers. And is single player and multi player.)

#### Environment
1.Set up an ae2 controller and an rs controller with power.
2.Hook up an interface to the two systems. With on the ae2 interface an external storage and on the rs interface a storage bus.
3.Let the rs interface try to keep one stone in two of its slots and the ae2 interface keep one stone.
4.Use an export bus with at least 2 acceleration cards to export stone to the rs interface.
5.Put three stone in the rs interface and see the number increase.
(6.)Can do with entire stacks and if you use a second external storage with a higher priority on a craft it will fill up the crate.
![ae_export](https://cloud.githubusercontent.com/assets/25965012/23231310/a35eb7fe-f947-11e6-9acb-ed44cf1684e3.png)
![ae_interface](https://cloud.githubusercontent.com/assets/25965012/23231311/a360b324-f947-11e6-905e-0e522c6c7d06.png)
![ref_interface](https://cloud.githubusercontent.com/assets/25965012/23231312/a3619eec-f947-11e6-9478-71cb54302669.png)
![total_setup](https://cloud.githubusercontent.com/assets/25965012/23231313/a362d55a-f947-11e6-8dfb-2e90a341974f.png)
- Minecraft Version: 
- AE2 Version: 12/31/2016 appliedenergistics2-rv4-alpha-11.jar
- Forge Version: 12.18.3.2185

**Comment by CraftMinerKyle** [comment]
Also, if you use something that picks a block with a Storage Cell in it (ME Chest, ME Drive, etc) and also keeps that data that it still has the Storage Cell in it, the object will drop the cell as if it had been broken.
