### ISSUE TITLE
Additional interface window and upgraded search option

### ISSUE THREAD

**Issue by chah85** [AppliedEnergistics/Applied-Energistics-2#2816]
I have an idea to improve the interface and search options. 

When I'm crafting several things, I might not need all the items at once, but don't want to search for the items every time. If you add another interface window next to it, where you can place and  store 5-10 items, while keeping the work area clear for crafting.

Second, I would like to be able to search for items form a specific mod. Example:
I wish to craft a few items from Ender IO, and I search for "ender IO" in the search box. Then all the items I have from that mod appears. At present, I have to click on "sort by mod" and scroll through, hoping I recognize the items from that specific mod.

Hope you can use my feedback. Thank you for a great mod!
- Minecraft Version:  1.7.10
- AE2 Version: 0.5.0.56
- Forge Version: 1.2.0.345

**Comment by XFactHD** [comment]
Searching for items from a specific mod is possible with @modid if recall correctly. For EnderIO you would write @enderio.
