### ISSUE TITLE
Strange mod interaction or something 

### ISSUE THREAD

**Issue by 31trainman** [AppliedEnergistics/Applied-Energistics-2#2817]
Description
Im seeing a strange bit of red text printed out in my multimc console playing on the rail Chronicles modpack in mp

Environment
MP, Multimc
Here's the first section of the error http://pastebin.com/Q28m6F4C and heres the second http://pastebin.com/qJFP1Xsj

Mods:
  AdvancedSolarPanel-1.7.10-3.5.1
  ae2stuff-0.5.0.56-mc1.7.10
  AgriCraft-1.7.10-1.5.0
  AOBD-2.9.2
  AOBDBB-1.0.6
  AppleCore-mc1.7.10-1.3.8
  appliedenergistics2-rv2-stable-10
  Aroma1997Core-1.7.10-1.0.2.16
  AromaBackup-1.7.10-0.1.0.0
  AsieLib-1.7.10-0.4.6
  bdlib-1.9.4.109-mc1.7.10
  BiblioCraft[v1.11.5][MC1.7.10]
  BiblioWoods[BiomesOPlenty][v1.9]
  BiblioWoods[Forestry][v1.7]
  BigReactors-0.4.3A
  Binnie Patcher 1.8
  binnie-mods-2.0-pre14
  BiomesOPlenty-1.7.10-2.1.0.1889-universal
  BRCore-1.7.10-1.0
  buildcraft-7.1.18
  buildcraft-compat-7.1.5
  Carpenter's Blocks v3.3.8.1 - MC 1.7.10
  catwalks-2.0.4
  Chisel-2.9.5.11
  ChiselTones-1.7.10-1.0-3
  CodeChickenCore-1.7.10-1.0.7.47-universal
  CoFHCore-[1.7.10]3.1.3-327
  Computronics-1.7.10-1.6.1
  CraftTweaker-1.7.10-3.0.13
  Decocraft-2.3.6.1_1.7.10
  deepresonance-1.1.4
  denseores-1.6.2
  DynamicSurroundings-1.7.10-1.0.5.9
  eiorteis-1.3
  ElecCore-1.7.10-1.4.294
  EnderCore-1.7.10-0.2.0.39_beta
  EnderIO-1.7.10-2.3.0.429_beta
  EnderIOAddons-1.7.10-2.3.0.427_beta-0.10.11.54_beta
  EnderStorage-1.7.10-1.4.7.37-universal
  ExtraCells-1.7.10-2.3.14b197
  ExtraTiC-1.7.10-1.4.6
  extrautilities-1.2.12
  Farseek-1.0.11
  FastAsyncWorldEdit-forge1710-17.02.20-b16276e-530-10.8.30
  fastcraft-1.23
  FastLeafDecay-1.7.10-1.4
  forestry_1.7.10-4.2.16.64
  FSP-1.7.10-0.29.3
  FTBLib-1.7.10-1.0.18.3
  FTBUtilities-1.7.10-1.0.18.3
  gearswap-1.2.3
  gendustry-1.6.3.132-mc1.7.10
  generators-0.9.20.123-mc1.7.10
  grapplemod-1.7.10-v9
  HPTanks-1.7.10-1.1.4
  HungerOverhaul-1.7.10-1.0.0
  IC2 Wrench Plugin Version 1.0.3
  IC2NuclearControl-2.4.2a
  IguanaTinkerTweaks-1.7.10-2.1.6
  ImmersiveEngineering-0.7.7
  immersiveintegration-0.6.8
  industrialcraft-2-2.2.827-experimental
  IndustrialExpansion-BETA-v1.1.2-var1
  InGameAccountSwitcher-Forge-1.7.10-7.0.1
  INpureCore-[1.7.10]1.0.0B9-62
  InventoryTweaks-1.59-dev-152
  ironchest-1.7.10-6.0.60.741-universal
  IronChestMinecarts-1.0.4
  JAFFA-1.72.13
  liteloader-1.7.10
  logisticspipes-0.9.3.128
  LootBags-1.7.10-2.0.17
  magneticraft-0.6.1-final
  Mantle-1.7.10-0.3.2b
  mcjtylib-1.8.1
  Mekanism-1.7.10-9.1.0.281
  MekanismGenerators-1.7.10-9.1.0.281
  MekanismTools-1.7.10-9.1.0.281
  MineFactoryReloaded-[1.7.10]2.8.1-174
  MineTweakerRecipeMaker-1.7.10-1.1.0.11
  mod_voxelMap_1.6.21_for_1.7.10
  MoreChisels-1.7.10-1.0-28
  MouseTweaks-2.4.4-mc1.7.10
  mp3spi-1.9.5-1
  neiaddons-1.12.14.40-mc1.7.10
  NEIIntegration-MC1.7.10-1.1.2
  NEIlootbags-1.7.10-1.1.3
  NetherOres-[1.7.10]2.3.1-22
  netherportalfix-mc1.7.10-1.1.0
  Networks Manager-10.4R
  nhdshaders-1.7.10-1.0.4
  nhintegration-1.7.10-1.0.12
  nhlib-1.7.10-2.0.11
  nhowshaders-1.7.10-1.0.0
  nhwrench-1.7.10-3.1.6
  NotEnoughCodecs-1.7.10-0.4
  NotEnoughIDs-1.4.3.4
  NotEnoughItems-1.7.10-1.0.5.120-universal
  NotEnoughKeys-1.7.10-3.0.0b45-dev-universal
  NotEnoughResources-1.7.10-0.1.0-122
  NVLIC2Machines-1.7.10.1558.1.3
  OpenBlocks-1.7.10-1.5.1
  OpenComputers-MC1.7.10-1.6.1.11-universal
  OpenFM-1.7.10-0.1.0-44
  OpenModsLib-1.7.10-0.9.1
  OpenModularTurrets-1.7.10-2.2.10-233
  OpenPeripheral-1.7.10-AIO-7
  OpenPrinter-MC1.7.10-0.1.0.132
  OpenSecurity-1.7.10-1.0-97
  Pam's HarvestCraft 1.7.10Lb
  PlanetguyLib-1.9.2
  platforms-1.7.10-0.1.2
  pressure-1.3.0.130-mc1.7.10
  ProjectRed-1.7.10-4.7.0pre12.95-Base
  ProjectRed-1.7.10-4.7.0pre12.95-Compat
  ProjectRed-1.7.10-4.7.0pre12.95-Fabrication
  ProjectRed-1.7.10-4.7.0pre12.95-Integration
  ProjectRed-1.7.10-4.7.0pre12.95-Lighting
  Railcraft_1.7.10-9.12.2.0
  RebornCore-1.1.0.15-universal
  RedstoneArsenal-[1.7.10]1.1.2-92
  RemainInMotion-2.8.9
  ResourceLoader-MC1.7.10-1.3
  ResourcePackOrganizer  MC-1.7.10  v1.0.1
  RFDrills-1.7.10-1.7.3
  rftools-4.23
  roguelike-1.7.10-1.5.0b
  RouterReborn-1.7.10-1.2.0.43-universal
  RTG-1.7.10-1.1.1.3
  secretroomsmod-1.7.10-4.7.1.406
  ShetiPhianCore-1.7.10-3.0.0
  SimpleLabels-1.7.10-1.0-9
  SimplyJetpacks-MC1.7.10-1.5.3
  SolarExpansion-Basic-1.6a
  StevesAddons-1.7.10-0.10.16
  StevesCarts2.0.0.b18
  StevesFactoryManagerA93
  Streams-0.2
  TConstruct-1.7.10-1.8.8
  TechReborn-1.7.10-0.7.19.1115-universal
  ThermalDynamics-[1.7.10]1.2.0-171
  ThermalExpansion-[1.7.10]4.1.4-247
  ThermalFoundation-[1.7.10]1.2.5-115
  ThermalSmeltery-Redux-v1.1
  TiCTooltips-mc1.7.10-1.2.5
  TMechworks-1.7.10-0.2.15.106
  Traincraft-4.3.1_007
  trashslot-mc1.7.10-1.0.31
  vorbisspi-1.0.3-1
  Waila-1.5.10_1.7.10
  WailaHarvestability-mc1.7.10-1.1.6
  WAILAPlugins-MC1.7.10-0.2.0-25
  Wawla-1.0.5.120
  worldedit-forge-mc1.7.10-6.1.1-dist
  WR-CBE-1.7.10-1.4.1.9-universal
  zettaindustries-1.1-106
  Ztones-1.7.10-2.2.1

- Minecraft Version: 1.7.10
- AE2 Version: appliedenergistics2-rv2-stable-10
- Forge Version: 10.13.4.1614
- Java 8 update 121
-Mac Os X version 10.12.3

**Comment by mindforger** [comment]
1.7.10 is not supported anymore, also rv2 is extremely outdated, try at least rv3 for 1.7.10 if it does not break with another mod

**Comment by 31trainman** [comment]
ok il try that
