### ISSUE TITLE
QuantumStorage only shows 64 items behind a Storage Bus.

### ISSUE THREAD

**Issue by DeadSix27** [AppliedEnergistics/Applied-Energistics-2#2818]
AE Version: https://github.com/AppliedEnergistics/Applied-Energistics-2/commit/1760113cd46e08178d0eda3a8233f4205a5f7973
Forge Version: `1.10.2-forge1.10.2-12.18.3.2234`

![image](https://cloud.githubusercontent.com/assets/1492505/23370121/f55e880c-fd13-11e6-9224-5479c273eda2.png)
![image](https://cloud.githubusercontent.com/assets/1492505/23370131/ff2b4e60-fd13-11e6-9b99-cd3600acb622.png)

If nessesary I can report this on QS's issue tracker too.

**Comment by yueh** [comment]
#2550

**Comment by DeadSix27** [comment]
@yueh thx for pointing, looking at the referenced issue a lot of people asked this already, I myself searched via github search beforehand... for "stack quantum" and it did not come up.. well well
