### ISSUE TITLE
Incompatibility between AE2 & IC2 Experimental in 1.7.10 [CRASH]

### ISSUE THREAD

**Issue by FenFawnix** [AppliedEnergistics/Applied-Energistics-2#2819]
#### Summary
Game crashes when AE2 machines are placed down while is IC2 installed. Bricks/corrupts world.

#### Description
I've bricked my world twice now simply by placing AE2 "machines." First with the inscriber, and second with the ME chest. In both instances the game froze for a second before crashing. Upon reopening the world, the game intermediately crashes. I've read the crash log (attached at end) and it appears to have something to do with IC2 power. (IC2 version: 2.2485 experimental.) It's probably IC2's problem, but I'm posting here since the crash was triggered by an AE2 block. 

#### Environment
I'm running a modified version of the Cobalt Legends pack in minecraft 1.7.10. There's also 9 extra mods installed on top the ~40 from Cobalt Legends. Extras including;; AE2, IC2, Thermal Foundation/Expansion/Dynamics, Twilight Forest, Dragon's Radio Mod, Wolf Armour & Storage, and finally World Edit.

#### Fix*
Uninstall IC2. This is no longer an issue for me, but if anyone else has bricked their world, just remove the problem block in MC Edit. *Results may vary

- Minecraft Version: 1.7.10
- AE2 Version: rv0-stable-3
- Forge Version: 10.13.4.1481

[crash-2017-02-28_19.56.16-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/811919/crash-2017-02-28_19.56.16-server.txt)

**Comment by mindforger** [comment]
First 1.7.10 is not supported, second rv0 is somewhere close to the ice age ... rv3 beta 6 is the latest and most stable version, third Version 1618 was the latest stable forge version for 1.7.10

**Comment by Ommina** [comment]
As an aside -- some of those filenames look really... odd.  "minecraft.jar", "modpack.jar"?  You may also want to ensure you are using official releases.

**Comment by mindforger** [comment]
*shiver* it looks like he dropped all files into his jar file like it was done pre forge

**Comment by FenFawnix** [comment]
I figured it'd be a waste to throw a report for an out dated version (of everything.) But I was instructed to I say!

@mindforger 
I'll consider updating and choosing mods (and versions of said mods) more carefully—not just downloading the first version I see.

@Ommina 
Official releases of what? Minecraft, Technic Launcher or the mods themselves?
