### ISSUE TITLE
can't establish QNB connection

### ISSUE THREAD

**Issue by jonilala796** [AppliedEnergistics/Applied-Energistics-2#2820]
In SP I wanted to set up an Quantum Network Bridge but it didn't work. I wanted to do this between Overworld and a RFTools dimension. After it didn't worked I set both up in my RFTools dimension. I already tried different cables and directions of the QNB. As you can see in the picture attached I wanted to do this between the one in the upper left corner and the bottom right.  The one at the bottom right is connected to a controller and the other one has only some energy and a terminal. And i also have the same singularity in both. When you need some more information please contact me.

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-11
- Forge Version: 12.18.3.2239

![2017-03-04_14 03 22](https://cloud.githubusercontent.com/assets/17726681/23579035/97c9b49e-00e4-11e7-95d8-c907324ded0d.png)

**Comment by jonilala796** [comment]
I have an update on this: the quantum entangled singularity when you give it to you with  jei is not working

**Comment by mindforger** [comment]
that is totally intended! you need to entangle a pair by exploding one
