### ISSUE TITLE
Suggestion Auto Crafting Function with Conversion Monitors

### ISSUE THREAD

**Issue by Hazmatik** [AppliedEnergistics/Applied-Energistics-2#2821]
It would be nice to be able to trigger a crafting operation using a Conversion Monitor. On a locked conversion monitor if you have none of the item in your storage but you have a crafting recipe for it instead of displaying "0" it would instead display "Craft", then when you left click, like you would to withdraw items, instead it would open up the crafting GUI.

**Comment by yueh** [comment]
Might be an idea. But it might defy the idea of automation/stockkeeping for an item being important enough to justify a monitor, but then not handled automatically once it is below a limit. (They are similar to barrels in their function)
