### ISSUE TITLE
Cannot entangle singularities

### ISSUE THREAD

**Issue by ScorcherOfAwesomeness** [AppliedEnergistics/Applied-Energistics-2#2822]
#### Description
Cannot entangle singularites

#### Environment
That info I cannot find
- Minecraft Version: 1.7.10
- AE2 Version: RV2-stable-10
- Forge Version: Cannot find

**Comment by VT-14** [comment]
Try updating to RV3 (Beta build 6).  That was the last 1.7.10 version.  1.7.10 is no longer being developed.

Make sure you have a Singularity, some Ender Dust (not all are in the ore dictionary), and an explosion.
