### ISSUE TITLE
Ignore keybinds in terminal search bar

### ISSUE THREAD

**Issue by XFactHD** [AppliedEnergistics/Applied-Energistics-2#2823]
#### Description
When the search bar in a terminal is selected and JEI is installed, certain keybinds like "Show Recipe", "Show Uses" and "Hide JEI" should be blocked as it is really annoying when JEI hides everytime I type something with an "o" (My hotkey for hiding JEI) in it.

#### Environment
- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-11
- JEI Version: 1.10.2-3.14.7.415
- Forge Version: 12.18.3.2239

**Comment by yueh** [comment]
1.10 is a bit of a mess here. It basically provides 2 different ways to handle inputs and of course both are incompatible. And of course neither is considered deprecated.

As long as you do not support both simultaneously it will always break somehow. Fixing it will pretty much require a complete rewrite off all GUI handling probably including any client/server synchronisation and maybe even the basic packet sending. But there is simply no time currently for it.
