### ISSUE TITLE
Server Crash with "java.lang.ClassCastException: appeng.block.networking.BlockCreativeEnergyCell cannot be cast to appeng.block.crafting.BlockCraftingUnit"

### ISSUE THREAD

**Issue by john01dav** [AppliedEnergistics/Applied-Energistics-2#2825]
Hello,

I run a Minecraft server with the Direwolf20 1.10 pack. Recently, my server has been crashing when specific players join. When it does so, I get [this](https://www.moddedminecraft.club/crash-reports-dw20/crash-2017-03-08_02.03.03-server.txt) crash log.

I should note that since I am using a pre-made modpack I _can't_ switch my server to the latest AE version because that will prevent any players from joining unless they do the same, and a server that has extra steps to join is an empty server.

#### Environment

- Ubuntu 16.04 LTS x64
- Java 1.8.0_121
- 14GBs of ram allocated to the server
- Minecraft version: 1.10.2
- Modpack (mods list available on FTB's website): [Direwolf20 1.10](https://www.feed-the-beast.com/projects/ftb-presents-direwolf20-1-10) version 1.6.2
- Multiplayer server
- I am also running SpongeForge version 1.10.2-2221-5.1.0-BETA-2168
- Forge version (different from modpack default): 1.10.2-12.18.3.2221
- Applied Energistics version rv4-alpha-11

NOTE: If there are any fixes, I would like to ask for a backport to a version that will work correctly with this modpack so I can continue running my server crash-free.

**Comment by Ommina** [comment]
Unless things have changed and I didn't notice, official AE2 does not work with SpongeForge.

I _believe_ (I've not looked, but I presume it is still there), that there is a build provided by Sponge that you can place on the server.  That said, I was under the impression the incompatibility prevented the server from starting at all, so the SpongeForge build may or may not solve your problem.

**Comment by mindforger** [comment]
this looks like a corrupted chunk, it tries to acces sa block as something that it not is 

namely he tries to interact with an creative energy cell like an crafting cpu .. if there is no creative energy cell anywhere, you should look for the chunks with the crafting CPUs inside

**Comment by john01dav** [comment]
@Ommina By default AE won't work with Sponge. As such, I am using [SpongeBootstrap](https://forums.spongepowered.org/t/spongebootstrap-fixes-ordering-issue-with-other-coremods/12275) to make it work correctly. Is this a bug I should report to the SpongeBootstrap developers instead

@mindforger I'm not sure if you think this occurs when a player, for example, interacts with a block. If so, that is incorrect. This error occurs when any player who last logged off in the same area tries to log back in. As such, I agree it is probably world corruption, but, I have no idea _where_ this world corruption is so I can't fix it. (Other crashes have given me coordinates) Perhaps I can get a patched AE that will print coordinates when this happens so I can mcedit the broken block out?

**Comment by mindforger** [comment]
you can examine the server log, player logging in always presents their coordinates, so you know where it happened

also like i said, the game tries to interact with an creative energy cell like it would normally with an crafting CPU, bets are high, that you have only very few or none creative enrgycells, so it is most possibly a corrupted chunk with an crafting CPU in it or right next to it on the border somewhere around that player logging in

on other hand, i know from Immersive Engineering that some sort of deco mod is currently using tile entity blocks as camouflage and breaking mod interaction with this, i just can't remember the actual issue and mod

**Comment by yueh** [comment]
As usually, we do cannot support servers using sponge as it can break too many things.

It might be a corrupted world or just sponge or a plugin returning the wrong block for a location.

If it is actually corrupted, the damage is already done. So probably no way to even validate it without sponge. Protecting against a `ClassCastException` is also pretty much impossible as it can happen everywhere and therefore require an absurd amount of defensive programming.
