### ISSUE TITLE
Modpack loading crash

### ISSUE THREAD

**Issue by the-creamster** [AppliedEnergistics/Applied-Energistics-2#2826]
I'm getting the following crash upon modpack load

https://gist.github.com/the-creamster/a9e77e9853efa311a3d0b0141b2b2b1f (line 355+)
had another one that looks identical but triggered on a different mod. same issue type??

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha11
- Forge Version: build 2254

**Comment by yueh** [comment]
This could be any mod.

We will reopen the issue, once you can provide an instance with a minimum amout of mods to trigger it and it still contains AE2.
