### ISSUE TITLE
Game crashes when trying to pick up robit with network tool

### ISSUE THREAD

**Issue by jonilala796** [AppliedEnergistics/Applied-Energistics-2#2827]
when I shift + right click the robit from mekanis with the network tool from then my client is crashing
crash report: http://pastebin.com/SShKUjLm

Minecraft Version: 1.10.2
Mekanism Version: 9.2.1.298
Forge Version:12.18.3.2239
AE2 Version: rv4-alpha-11

This is the link to the issue at Mekanism: https://github.com/aidancbrady/Mekanism/issues/4256

**Comment by CraftMinerKyle** [comment]
I'm not seeing your issue, but I am seeing a problem with the loading of the Creative Energy Cells. EnderIO Takes over with RF Power Conversion, so that may be what I am seeing. Maybe it could be something to do with block info?
