### ISSUE TITLE
[1.10.2] [SpongeVersion] Error unloading server

### ISSUE THREAD

**Issue by KappaKiddie** [AppliedEnergistics/Applied-Energistics-2#2828]
- Minecraft Version: 1.10.2
- AE2 Version: appliedenergistics2-rv4-alpha-11
- Forge Version: 1.10.2 - 12.18.3.2254
- Sponge Version: 1.10.2-2221-5.2.0-BETA-2223

Log: https://gist.github.com/KappaKiddie/3b9e577a57cf9fe6bc39c8e35011e1fc

**Comment by yueh** [comment]
Sorry, but we cannot support sponge.
