### ISSUE TITLE
Terminal GUI close when trying to auto-craft

### ISSUE THREAD

**Issue by MarcNemesis** [AppliedEnergistics/Applied-Energistics-2#2830]
**Problem:**
- When i try to select a item to auto-craft from my terminals, the GUI simply close. It worked fine less than 24h ago (last time i was logged in.)

**What should happen:**
- I should be redirected to the GUI where i can choose the ammount of items to craft.

**Additional details:**
- Modpack Infitech 2 V3.2.20
- MC 1.7.10
- Forge 1614 (I think? not 100% sure where to find that info)
- AE2 version: rv3-beta-6
- SMP
- Other player interference is not an option considering we are only 2 players on the server and know each other quite well IRL.
- No change were made to the ME Network.
- Power is not an issue.
- Storage is not an issue.
- As stated above, was working fine before last login.

I've tryed looking arround the Github for similar issue. Only found this thatw as very similar: #2444 but did not provide an answer and it dating from a few months ago,

Edit:
- Dunno how..it fixed itself on it's own. I went back to the main menu and was cursing silently while watching Netflix and when i went back to try something else, it was working.

Edit 2 (Re-opened):
- I seem to have found the culprit. I used an IC2 Teleporter and when i came back to my base. My network was buging again as described above.

**Comment by mindforger** [comment]
1.7.10 is no longer supported

do you installed enough energy cells into your system?

>Power is not an issue.

input power means nothing when your internal buffer runs dry in one gametick, your system can only accept as much power per tick as it can store internally ...
