### ISSUE TITLE
Server crashed when AE ran out of power while I was starting a craft

### ISSUE THREAD

**Issue by Xiaminou** [AppliedEnergistics/Applied-Energistics-2#2832]
Crash Report: [crash-2017-03-10_16.06.46-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/834769/crash-2017-03-10_16.06.46-server.txt)

- Minecraft Version: 1.10.2
- AE2 Version: alpha-11
- Forge Version: 2258

**Comment by CraftMinerKyle** [comment]
OK. I'm sort of expecting the DEV's to yell at this comment saying "You idiot! That's wrong!", but from my (limited) knowledge, EnderIO RF power conversion is causing the issue. Don't quote me on that. Also, if you are crafting while your ME System runs out, that shouldn't cause a crash. the items just disappear back into the system.

**Comment by mindforger** [comment]
@CraftMinerKyle if you guess so, you should advise him to see if the offending mods listed way down the crash report may have been updated? EnderIO complains about an invalid RF API
>	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * An unsupportted RF API is installed (1.7.10R1.3.1 from (guessing) jar:file:/C:/Users/Administrator/Minecraft%20Servers/2017/FTB%20Beyond%201.0.1%202/mods/BrandonsCore-1.10.2-2.1.4.92-universal.jar!/cofh/api/CoFHAPIProps.class).
                    Ender IO needs at least 1.8.9R1.2.0B1 and will NOT work with older versions.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

but as i said and as the log says, it does not have to be an actual issue, but you can check by removing those mods or trying to update them

**Comment by CraftMinerKyle** [comment]
You know, I have had a similar problem before with EnderIO and AE2 Power Conversion conflictions before, but I restarted after the crash and EnderIO took over on the RF Power Conversion and everything was fine. I did't even touch any code, any mods, or any error logs. IDK what fixed it, but EnderIO took over a lot of things. All Silicon recipes were changed to EnderIO only recipes, and all Power Conversion amounts were also taken over by EnderIO. Can you continue to play your game after this incident or not?
