### ISSUE TITLE
Storage bus + quantum storage unit = ignored settings

### ISSUE THREAD

**Issue by Cobra1117** [AppliedEnergistics/Applied-Energistics-2#2833]
#### Description
When attaching a storage bus to the Quantum Storage Unit (from the QuantumStorage mod here: https://minecraft.curseforge.com/projects/quantumstorage?gameCategorySlug=mc-mods&projectID=235121), the storage bus completely ignores its settings. For example, if you set the settings to "insert only" and "iron ingot", you can insert and extract rotten flesh. Removing the Quantum Storage Unit and replacing it with a chest caused the storage bus to act as expected.

#### Environment
Tested on a dedicated server.

- Minecraft Version: 1.10.2
- AE2 Version: rv4-aplha-11
- Forge Version: 12.18.3.2239
- QuantumStorage: 1.10.2-3.2.19

**Comment by ThomasAunvik** [comment]
> We decided to drop any support for special inventories in 1.10 because forge provides a common interface now for anyone to use (at least up to 2^31 per slot, like a dsu).
> 
> This results in longer having to add support for every storage mod out there to every mod interacting with storages. Now each storage mod can implement their own solution and everyone can use it. And it just works. For example storage drawers, there is no special support for it on our side.
> 
> Should a mod still insists on doing it as in 1.7.10 instead of adapting to 1.10, they certainly can expect other mods not supporting it when there is another solution which requires less work and provides more benefits.
-Yueh https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2550#issuecomment-257512457
