### ISSUE TITLE
Server Crashes as Soon as it Finishes Starting

### ISSUE THREAD

**Issue by BaconatorNoVeg** [AppliedEnergistics/Applied-Energistics-2#2834]
I am running a Direwolf20 1.10.2 server. I restarted the server this morning, but now it keeps crashing. Looking closer at the console, it gets as far as finishing loading the server, then it immediately crashes.

Here is my log: [https://drive.google.com/open?id=0B2HSJ-t_17MYT3lKd0p4eFhSejA](https://drive.google.com/open?id=0B2HSJ-t_17MYT3lKd0p4eFhSejA) (It was too big to paste into PasteBin)
And my crash report: [http://pastebin.com/Sxjeyyy8](http://pastebin.com/Sxjeyyy8)

I already tried reinstalling the latest version of AE2, but it still keeps crashing. The only reason why I am posting this issue here is because the crash report mentions AE2.

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha11
- Forge Version: build 2185

**Comment by jambonmcyeah** [comment]
There seems to be a broken AE creative energycell in your world. Try MCediting it out

**Comment by jambonmcyeah** [comment]
Or create a new world

**Comment by mindforger** [comment]
this is the second bug of this type but i can not find the other one ... looks like a broken chunk but there may be more behiind it ?!

**Comment by BaconatorNoVeg** [comment]
There shouldn't be any type of creative block on the world. It's an SMP world. We already tried MCediting the AE energy cells in our houses out of the world, but the server still crashes.

**Comment by BaconatorNoVeg** [comment]
I'd like to avoid creating a new world if at all possible. My friends and I put several months of work into the current world.

**Comment by Zedrimar** [comment]
well if you have backups, you could try loading one of those.... may or may not fix the issue

**Comment by CraftMinerKyle** [comment]
Try removing ALL the energy cells from the world, and then see if that works.

**Comment by Ommina** [comment]
@mindforger Were you thinking of #2825 ?

Different crash reports, but both seem to believe there is a creative energy cell somewhere when there isn't.

**Comment by mindforger** [comment]
@Ommina nailed it :)
