### ISSUE TITLE
Runic altar autocrafting

### ISSUE THREAD

**Issue by SoniEx2** [AppliedEnergistics/Applied-Energistics-2#2835]
#### Description

Hello! I'd like to be able to split autocrafting recipes across interfaces. So that e.g. I can have 2 droppers facing an open crate, and one of them set to livingrock and the other one set to the rune ingredients. However, when I tried it, only one of the recipes seemed to have an effect.

#### Environment

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-11
- Forge Version: 12.18.3.2185

**Comment by XFactHD** [comment]
If you want to split the ingredients for a recipe why not use a chest as a buffer? I also don't get how being able to send crafting ingredients of a recipe to different interfaces would fix your problem as the ME system doesn't know anything about the crafting process of the altar an therefore doesn't know when to drop the living rock onto the altar.

**Comment by SoniEx2** [comment]
The idea is that blocking mode would work across recipes.

So the ME system would put items in a dropper, and 1 livingrock in another dropper, I'd drop the items onto the runic altar, and using a comparator I'd trigger the other dropper. Then put the runes into the ME system.

Using a chest as a buffer leads to issues since we haven't had sorters since 1.4.7 and every damn item transfer mod is too incapable of being reasonable about item transfer and I'm not in the mood to make an overcomplicated redstone mess.

**Comment by XFactHD** [comment]
If you want to just get the ingredients into the correct dropper you could use EnderIO item conduits with filters. I also think that you can pipe directly into Botania's Open Crate. That combined with blocking mode would most likely solve your problem.

**Comment by SoniEx2** [comment]
The livingrock still needs to be separate and I would like it to block until the recipe is completed, not until the inventory is empty.

**Comment by SoniEx2** [comment]
Also:

- Automated Fluid Transposer Crafting
    - Put [base item]->[target item] in fluid transposer interface.
    - Put [the exact amount of redstone/glowstone/enderpearls/etc]->[target item] in magma crucible interface.
    - Configure sides so magma crucible autoejects into fluid transposer.

No mess of cables, no having to worry about conflicting items (you need to use redstone in the fluid transposer for this one recipe, but the magma crucible also needs to use redstone for different recipes?), etc.

**Comment by XFactHD** [comment]
In case of the Fluid Transposer your setup would be 2 by 2 blocks big, my setup with a chest and EnderIO conduits would be 3 by 2 blocks big, where would be the massive difference in complexity?

**Comment by SoniEx2** [comment]
What if you need to use redstone in the fluid transposer for one recipe, but the magma crucible also needs to use redstone for different recipes?

**Comment by XFactHD** [comment]
It makes no difference if the items are directly put into the machines by the interface or indirectly by a pipe?

**Comment by SoniEx2** [comment]
As I said, pipes are incapable of routing the redstone correctly for that one recipe.

**Comment by XFactHD** [comment]
EnderIO conduits have filters.

**Comment by SoniEx2** [comment]
If both machines are allowed to accept redstone, how would they know where to put the redstone?

**Comment by XFactHD** [comment]
Then you just make a setup for each fluid, that's what I normally do.

**Comment by yueh** [comment]
Essentially no.

On one hand it will make autocrafting way more complex for users as well as code OR it has to break the current functionality of using multiple interfaces at all.

On the other hand it is already possible to handle it in various ways with AE2 itself. And that is before using any additional mod, which will add even more ways to solve it,

**Comment by SoniEx2** [comment]
But I'm pretty sure I remember this being a thing in AE1?

Also, we already have blocking modes, I'd just like a "multipart" blocking mode.

**Comment by mindforger** [comment]
go ahead, fork the code, make a proposal :)
there are way more other things to fix and implement yet

**Comment by SoniEx2** [comment]
Can this be reopened for the sake of automating inscribers with pure AE2 without wasting resources by keeping them stocked in the inscribers?

**Comment by mindforger** [comment]
SoniEx2 you have a very very demanding personality (looking at your previous postings on other mods) to make other do things for you, fork the code and propose your changes (you seem to be able from your profile and requests), they got more important bugs to do than your change request just because for comfort without actual thinking of how to build it

by the way you can easily achieve your requested system with AE2  only

have a few pictures
https://puu.sh/uV0X5/b13041264b.jpg
https://puu.sh/uV0Xx/d65d52a0b9.jpg

all solved with only using 2 interfaces, 4 storage busses and 1 output bus and one capacity card and maybe a fluix to bridge the power instead of using 2 power sources

**Comment by SoniEx2** [comment]
Filters? Meh...

I'll have a go at it, see if it's trivial. It should be.

**Comment by SoniEx2** [comment]
Can this be reopened?

https://www.youtube.com/watch?v=Bu2ITOOU_wk
