### ISSUE TITLE
HWYLA Mod Compatibility for ME Smart/Dense Cables

### ISSUE THREAD

**Issue by Xiaminou** [AppliedEnergistics/Applied-Energistics-2#2836]
Add compatibility for HWYLA, apparently it works differently than WAILA.

https://github.com/TehNut/HWYLA/issues/57#issuecomment-286424866

**Comment by XFactHD** [comment]
WAILA did also not add AE comp at by itself, it was also added by AE. WAILA for 1.10.2 is supported as far as I know.

**Comment by Xiaminou** [comment]
I know but what I meant is, HWYLA is not showing channels when WAILA does.

**Comment by yueh** [comment]
Last time I tested HWYLA it worked perfectly fine. Thus should it be broken now, it means HWYLA most likely has broken the compatibility with WAILA. But as there is no way to target HWYLA directly and as long as there is still a working WAILA for 1.10, it will take precedence over HWYLA in terms of compatibility,

See also #2811

**Comment by totyaxy** [comment]
Recent version of HWYLA doesn't show channels information.

Hwyla-1.8.26-B41_1.12.2.jar

**Comment by mindforger** [comment]
The issue got closed one year ago, make a new one please and include more Information
