### ISSUE TITLE
Applied Energistics 2 missing texture fore Inscriber Silicon Press.

### ISSUE THREAD

**Issue by thecrazycimfam** [AppliedEnergistics/Applied-Energistics-2#2837]
In my mod pack, i was trying to make something  i believe it was the inscriber silicon pres for ae2 . to make that theirs a missing texture.  [ Inscriber Silicon Press  4132:19 ]<- to actually may that the middle piece is missing a texture as i said please fix that asap because i just requested my pack that has your mod to wait to be accepted and as i said i need it to be fixed withing couple of my  updates. 
Applied Energistics 2 for 1.7.10 , version of mod: appliedenergistics2-rv3-beta-6.jar

**Comment by mindforger** [comment]
1.7.10 is not maintained anymore, there MAY be an final release version someday but don't count on that

will not close this immediately but soon somebody will do .. maybe community can help

**Comment by thecrazycimfam** [comment]
but is it fixed in 1.8?

**Comment by thecrazycimfam** [comment]
is it fixed in 1.8

**Comment by mindforger** [comment]
why do you give me a thumbs down .. i could have closed it right away without giving you a chance to get help dude ... you are rude

**Comment by thecrazycimfam** [comment]
sorry. i dont know why i am just alittle confused ... i removed it. all i am gonna say is why is 1.7.10 not "maintained anymore?" its a mod that would need to be worked on or  its gonna be removed some how if i contact FTB  if they could pull it from all funds. but im not gonna be that person. i just need it to be fixed for 1.7.10

**Comment by thecrazycimfam** [comment]
sorry..... its late at night when i typed this <3

**Comment by yueh** [comment]
As said, we no longer support the 1.7.10 version.

@mindforger A final rv3 stable will simply be a relabeled beta-6 without any changes. It is just to prevent lossing a rv3 completely when releasing a higher rv beta.

**Comment by mindforger** [comment]
@yueh nice, thank you for the info, was not aware that the core functions are THAT independend to the MC version to be backported as a whole :D
