### ISSUE TITLE
Add a config option to disable channels and/or crystal growth

### ISSUE THREAD

**Issue by jambonmcyeah** [AppliedEnergistics/Applied-Energistics-2#2838]
#### Description
Everyone knows that a lot of people has switched from AE2 to Refined Storage, if a option is added in the config or there is a version of the mod where crystal growth and/or channels can be disabled, that will be great. I think if that happened, a lot of people are going to go back to using AE2. Honestly, refined storage sucks but me and many other players just don't want to worry about channel managment and growing crystals.

**Comment by yueh** [comment]
No.

**Comment by Ommina** [comment]
Besides, existing config options already cover both requests.  You're requesting something already available.

**Comment by jambonmcyeah** [comment]
I didn't know that
