### ISSUE TITLE
AutoCrafting Crash / Java Crash

### ISSUE THREAD

**Issue by MiamiCenterPL** [AppliedEnergistics/Applied-Energistics-2#2839]
When trying to autocraft a single chest <I have 7 planks and some oak logs, and configured autocraft that system can craft also planks for this> game just crashed.
Screenshoot: https://scr.hu/pL1wm8
On click "Start" game will crash...

Log: http://pastebin.com/uAR2NecX
hs_err_pid7844.log file: http://pastebin.com/RYNmBgd8
No Crash Report in crash reports folder!

Mod List:
Core:

BdLib
bspkrsCore
CodeChickenCore
CoFHCore
CoFHLib
EnderCore
INpureCore
Player API
WanionLib
Mods:

AE2 Stuff
Applied Energistics 2
AppleCore
AutoPackager
Avaritia
Avaritiaddons
Better Furnaces
Biblio Craft
Big Reactors
Build Craft
Buildcraft Compat
Chisel 2
Custom Main Menu
EnderIO
Ender IO Addons
Ex Astris
Ex Nihilo
Extra Utilities
Fastcraft
FastLeafDecay
Iguanas Tinker Tweaks
Immersive Engineering
Immersive Integration
Iron Chest
Journey Map
Mantle
Mekanism
Mekanism Generators
Mekanism Tools
MineFactory Reloaded
MineTweaker3
ModTweaker
MrCrayfish Furniture
NotEnoughItems
NEI Integration
OptiFine
Pam’s HarvestCraft
PneumaticCraft
ProjectRed
Redstonic
Resource Loader
Storage Drawers
TConstruct
TiC Tooltips
Tree Growing Simulator 2014
Thermal Dynamics
Thermal Expansion
Thermal Foundation
Universal Coins
Waila
WAILA Plugins
Wawla

- Minecraft Version: 1.7.10
- AE2 Version:  rv2-stable-10 / rv3-beta-6 <I was using rv3 beta, when crashed I changed it to rv2, and It's crashing again>
- Forge Version: 7.99.40.1614

**Comment by yueh** [comment]
That is a know bug with the intel gpu driver (happens even with vanilla itself)

Try updating them. But otherwise way out of our reach for any fix on our side.
