### ISSUE TITLE
Dense Cable - Unable to use all 32 channels Version: Rv4-alpha-11 | Minecraft: 1.10.2

### ISSUE THREAD

**Issue by LightSyaoran** [AppliedEnergistics/Applied-Energistics-2#2841]
Description:
I'm currently using the FTB Beyond pack for 1.10.2 and the version i'm on rv4-alpha-11 seems to get a problem with the channels on dense cables not registering, on most of the cables i can only see up to about 14 channels at most and once i go over that they will not show at all in the console or in the cable info.

To sum it up i can connect to say 18 blocks with a dense cable and instead of it showing 18 channels being used it will show about 14 channels being used and the others will not show unless i use another cable.

Environment:
Pack: FTB Beyond
- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-11
- Forge Version: 12.18.3.2254

--
Light
--

**Comment by mindforger** [comment]
pictures of the setup eventually ?

**Comment by LightSyaoran** [comment]
the pictures are from after i had to find a workaround.

number 1,2,3 were originally all 1 colour but sadly 1 of the 7 inscibers i had wouldnt get seen.
3,4,5 were also originally all 1 wire but got stopped at only seeing 14 channels so had to split them in to 2 wires.

![1](https://cloud.githubusercontent.com/assets/4660911/24118367/6b61b6a4-0da5-11e7-9a18-fb5d973f3073.png)
![2](https://cloud.githubusercontent.com/assets/4660911/24118364/6b5d65f4-0da5-11e7-841c-b9ce59a1d909.png)
![3](https://cloud.githubusercontent.com/assets/4660911/24118366/6b60def0-0da5-11e7-91b6-f075c3c25925.png)
![4](https://cloud.githubusercontent.com/assets/4660911/24118368/6b662202-0da5-11e7-8e79-daf06c5a4f34.png)
![5](https://cloud.githubusercontent.com/assets/4660911/24118365/6b5eb29c-0da5-11e7-8e5e-77e16877d150.png)
![6](https://cloud.githubusercontent.com/assets/4660911/24118363/6b5d3aac-0da5-11e7-9a0a-b12882acddf0.png)

**Comment by mindforger** [comment]
i hope you are aware that EVERY block from AE except for the controller behaves like a standard ME cable and reroutes up to 8 channel to devices facing each other

you may have channel loops present through this fact that prevents from detecting all objects! 

please try to reproduce this issue with a more simplicated setup, because from your pictures it is not possible to say what is connected where ... simply too much machinery in this case

**Comment by CraftMinerKyle** [comment]
Here is a suggestion that could possible help you with your potential channel sharing issue: Try using machines from other mods to do your autocrafting. They can't share the channels, and they also make you look cool because you have the know how to integrate machines from other mods.
