### ISSUE TITLE
[Suggestion] Reimplement OC P2P

### ISSUE THREAD

**Issue by XFactHD** [AppliedEnergistics/Applied-Energistics-2#2842]
It would be great if someone who has the time and the knowledge to do it could reimplement the OC P2P Tunnel for 1.10.2. I would do it myself but I currently have very little free time because of school.

**Comment by CraftMinerKyle** [comment]
Can't you just copy and edit the original code, or is it really that much work to re-implement the P2P Tunnels?

**Comment by Notawallplan** [comment]
In the meantime, work around it using OC's wireless networking. You can actually do a lot with it if you understand it.

**Comment by TheMuso** [comment]
It is for 1.12.2, but I've worked on this. #3720 is the pull request. If you know how to build mods, feel free to test.
