### ISSUE TITLE
Pure Fluix Seeds are not detected in Processing Patterns

### ISSUE THREAD

**Issue by Castone22** [AppliedEnergistics/Applied-Energistics-2#2844]
#### Description
I defined a processing pattern that takes an input of 1 fluix seed to output a fluix crystal, placed it in an interface hooked to an IE conveyer belt.  Pure Nether Quartz and Pure Certus Quartz behave as expected.

When I attempt to craft the Pure Fluix, I get a window returning to craft: <number of fluix crystals requested> with no ingredients despite the only pure fluix recipe in the system being set to take an input of fluix seeds equal to the number requested.  Certus and Nether will show the required inputs.

[Imgur Album](http://imgur.com/a/DlSSv)

#### Environment
SMP
Skyfactory 3 + AE2, Ding, Class Cache Tweaker, Foamfix, Thump, Schematica, Optifine and Deep Resonance

- Minecraft Version: 1.10.2
- AE2 Version: appliedenergistics2-rv4-alpha-11
- Forge Version: 12.18.3.2239

**Comment by yueh** [comment]
Cannot reproduce
