### ISSUE TITLE
ME Drives are not detected when placed after a P2P tunnel.

### ISSUE THREAD

**Issue by Castone22** [AppliedEnergistics/Applied-Energistics-2#2845]
#### Description
Attempting to place an ME drive after a P2P tunnel in a network will consume channels but the ME network will not display the contents of that ME drive.

On the bright side, slave networks still work properly and make a great workaround.

#### Environment

SMP
Skyfactory 3 + AE2, Ding, Class Cache Tweaker, Foamfix, Thump, Schematica, Optifine and Deep Resonance

-Minecraft Version: 1.10.2
-AE2 Version: appliedenergistics2-rv4-alpha-11
-Forge Version: 12.18.3.2239

**Comment by NosajDraw** [comment]
Can confirm this.  Additional information the far end of the P2P lights up as if connected to the main network, but instead forms it own separate ME system, you can verify this by connecting a terminal to the far end, and it will show you only what is at the far end.

-Minecraft Version: 1.10.2
-AE2 Version: appliedenergistics2-rv4-alpha-11
-Forge version 12.18.3.2254

**Comment by yueh** [comment]
Cannot reproduce.
