### ISSUE TITLE
Dense cable not detecting/using all channels

### ISSUE THREAD

**Issue by BSRVandal** [AppliedEnergistics/Applied-Energistics-2#2847]
#### Description
I have a dense cable being used to connect CPU groups daisy chained together but after 9 CPU groups the cable does not detect the remaining.

![2017-03-24_13 55 33](https://cloud.githubusercontent.com/assets/26659262/24309975/0650e772-109c-11e7-9fd8-0142515046cc.png)
![2017-03-24_13 55 56](https://cloud.githubusercontent.com/assets/26659262/24309976/0651fc70-109c-11e7-97c3-467306f7be5d.png)
![2017-03-24_13 58 06](https://cloud.githubusercontent.com/assets/26659262/24309973/0647f3b0-109c-11e7-8181-657416c8fec5.png)
![2017-03-24_13 58 01](https://cloud.githubusercontent.com/assets/26659262/24309974/0649d658-109c-11e7-8bf8-64970a904075.png)

The images show the issue pretty definitively. This is not an issue of running out of channels. I only have 9 total channels being passed to a p2p tunnel. I have the remaining channels not being used. 

#### Environment
Using Hermitpack with (as far as I can recall) forge, eleccore, and deep resonance all updated to the latest versions. 

- Minecraft Version: 1.10.2
- AE2 Version: rv4.alpha build 11
- Forge Version: 1.10.2-12.18.3.2254

**Comment by mindforger** [comment]
i am not 100% sure on this, but afaik the multiblock builds have size restraints

can you try a more compact design where the blocks have only 2 neighbour blocks with the same amount of blocks?

**Comment by BSRVandal** [comment]
Oh, ok, I had typed out a long response before this but now I understand. So a solution I guess would be to run a cable over the top or bottom of all the CPU groups in order to get around the 8 channel limit for blocks. It makes total sense now I just never gave a thought to a channel cap on blocks.
