### ISSUE TITLE
Storage bus doesn't work on IC2 reactor

### ISSUE THREAD

**Issue by zxvnm4** [AppliedEnergistics/Applied-Energistics-2#2850]
#### Environment

- Minecraft Version: 1.10.2
- AE2 Version: rv4 alpha build 11
- Forge Version: 12.18.3.2254
       Latest version of AE2 on 1.7.10 allowed the use of a storage bus on an IC2 reactor, for what ever reason, that no longer works. 
![2017-03-28_17 30 44](https://cloud.githubusercontent.com/assets/3515761/24431989/700d0ef0-13dc-11e7-9508-78bb107ee8c0.png)
![2017-03-28_17 30 47](https://cloud.githubusercontent.com/assets/3515761/24431996/795d6126-13dc-11e7-8078-466545e42f0c.png)

**Comment by ThomasAunvik** [comment]
> We decided to drop any support for special inventories in 1.10 because forge provides a common interface now for anyone to use (at least up to 2^31 per slot, like a dsu).
> 
> This results in longer having to add support for every storage mod out there to every mod interacting with storages. Now each storage mod can implement their own solution and everyone can use it. And it just works. For example storage drawers, there is no special support for it on our side.
> 
> Should a mod still insists on doing it as in 1.7.10 instead of adapting to 1.10, they certainly can expect other mods not supporting it when there is another solution which requires less work and provides more benefits.
-Yueh https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2550#issuecomment-257512457

**Comment by zxvnm4** [comment]
Well that is quite informative, thanks!
