### ISSUE TITLE
Cannot use an export bus on a multipart interface

### ISSUE THREAD

**Issue by zxvnm4** [AppliedEnergistics/Applied-Energistics-2#2851]
#### Environment

- Minecraft Version: 1.10.2
- AE2 Version: rv4 alpha build 11
- Forge Version: 12.18.3.2254
The export bus is not exporting to the inventory of the interface. Who knows why.
![2017-03-28_17 37 57](https://cloud.githubusercontent.com/assets/3515761/24432170/8e645c18-13dd-11e7-8491-eddcf0acc90c.png)
![2017-03-28_17 37 56](https://cloud.githubusercontent.com/assets/3515761/24432172/92575230-13dd-11e7-9dfc-f9b4b561f3a5.png)
![2017-03-28_17 37 52](https://cloud.githubusercontent.com/assets/3515761/24432178/9b0a0986-13dd-11e7-9cb9-07a7ae25980c.png)
![2017-03-28_17 37 54](https://cloud.githubusercontent.com/assets/3515761/24432185/a5a4587e-13dd-11e7-964a-de254787de1e.png)
![2017-03-28_17 37 49](https://cloud.githubusercontent.com/assets/3515761/24432194/b4fb5fca-13dd-11e7-9bc1-58c2bf1a1775.png)

**Comment by Tahakk** [comment]
I'm not sure what are you trying to accomplish here. If you want some items to be provided for another storage put it to 1st column of interface connected to the network without any other piece between and interface on it's own will work as as export bus. I don't think that those slots act like that - sure I can be wrong too.

**Comment by mindforger** [comment]
again you are misunderstanding the interface, it has no "storage" like a chest, it CAN act like that when configured to stockpile things, but the interface also needs power and somewhere to route the items as it will only accept items to move them into storages behind it, then stockpiling it into it's configured slots!

**Comment by zxvnm4** [comment]
Well, that isn't exactly how it works. Well if it is why would it be different with a multipart block vs a full block? This issue also exists with the multipart block and IC2's export upgrades, which is the real reason I made this post.
![2017-03-29_13 09 08](https://cloud.githubusercontent.com/assets/3515761/24472073/9c8c620a-1481-11e7-8072-a3c8e192fb37.png)
![2017-03-29_13 09 11](https://cloud.githubusercontent.com/assets/3515761/24472091/b28ccc5c-1481-11e7-812e-e19d58f43365.png)
![2017-03-29_13 09 14](https://cloud.githubusercontent.com/assets/3515761/24472098/b5ac61cc-1481-11e7-8efc-87c51c319259.png)
![2017-03-29_13 09 15](https://cloud.githubusercontent.com/assets/3515761/24472106/b81ca4d0-1481-11e7-8268-1cc42bed511b.png)
![2017-03-29_13 12 00](https://cloud.githubusercontent.com/assets/3515761/24472108/ba3e3346-1481-11e7-833b-59c8374af6ae.png)
![2017-03-29_13 12 04](https://cloud.githubusercontent.com/assets/3515761/24472110/bc4ba7b8-1481-11e7-9582-734181772f0c.png)
![2017-03-29_13 12 05](https://cloud.githubusercontent.com/assets/3515761/24472113/bf05e5ea-1481-11e7-98ae-cb9b94b18448.png)
![2017-03-29_13 12 13](https://cloud.githubusercontent.com/assets/3515761/24472122/c42276a6-1481-11e7-800b-e99846bca57c.png)
![2017-03-29_13 12 16](https://cloud.githubusercontent.com/assets/3515761/24472123/c684fc52-1481-11e7-829d-95e66ced6f1b.png)
![2017-03-29_13 16 11](https://cloud.githubusercontent.com/assets/3515761/24472157/e270f3c6-1481-11e7-9cae-0b9caaff2c3e.png)
![2017-03-29_13 16 14](https://cloud.githubusercontent.com/assets/3515761/24472160/e50c3a32-1481-11e7-94d5-20ff065bef3f.png)
![2017-03-29_13 16 15](https://cloud.githubusercontent.com/assets/3515761/24472163/e6fa3b5a-1481-11e7-8f24-62698d0de684.png)

**Comment by mindforger** [comment]
yeah i see that is a valid one there is an inconsistency between the multipart version of the interface and the block version @yueh 

@zxvnm4 you could have stated that difference between block version and multipart version a bit more clearly :)
