### ISSUE TITLE
Cannot use a filtered storage bus, connected to a filtered interface, to output items to the other network.

### ISSUE THREAD

**Issue by zxvnm4** [AppliedEnergistics/Applied-Energistics-2#2852]
#### Environment

- Minecraft Version: 1.10.2
- AE2 Version: rv4 alpha build 11
- Forge Version: 12.18.3.2254
I expect a filtered storage bus to be able to export items, through a filtered interface, to the larger network. This does not appear to be the case.
Overall View
![2017-03-28_17 46 54](https://cloud.githubusercontent.com/assets/3515761/24432315/91beb114-13de-11e7-9c1c-08a49b5d4db7.png)
Input Interface
![2017-03-28_17 46 56](https://cloud.githubusercontent.com/assets/3515761/24432317/93b4730a-13de-11e7-97ae-0c873e849d49.png)
Storage bus connected to filtered interface(Connects to the storage bus+chest)
![2017-03-28_17 46 59](https://cloud.githubusercontent.com/assets/3515761/24432319/980140b4-13de-11e7-9ab9-efbff0609215.png)
Filtered interface(Connects to the storage bus+chest)
![2017-03-28_17 47 01](https://cloud.githubusercontent.com/assets/3515761/24432322/9b5b0e52-13de-11e7-8cee-fe1f461d2f01.png)
Storage bus that connects to output chest
![2017-03-28_17 47 03](https://cloud.githubusercontent.com/assets/3515761/24432324/9d7710f0-13de-11e7-80d8-614a95df99e1.png)
The output chest
![2017-03-28_17 47 04](https://cloud.githubusercontent.com/assets/3515761/24432326/9f3aa2f8-13de-11e7-8856-99be2113c4d7.png)

**Comment by mindforger** [comment]
you are misunderstanding the "filter" for interfaces, if you set an item in an interface, it will stockpile the item to the defined number and act as a chest to the storage bus, but the interface will then not work like a subnetwork anymore. 

if you only configure the storage bus, the system should behave like you expect.

**Comment by zxvnm4** [comment]
Well, this setup does not work in 1.7.10 either. So my main conjecture is, quite wrong indeed. There isn't a bug here, more so a suggestion(Or a bug, I mean who knows?) I setup a similar system but instead of using an interface to force items into the system, I used an import bus, which then allowed the transfer of items from the chest it is attached to, to the interface then the chest.

I must say, this isn't a misunderstanding that an interface will stock pile the resources in itself first then the chest. I just failed to setup the images in a way to tell you what I was looking at. What was happening here is that I was using an interface to push those 64 wooden planks into the filtered storage bus/filtered interface(The storage bus connected to the filtered interface which is connected with a storage bus to the chest). The issue I am describing is that the 64 wooden planks didn't enter the interface connected directly to the chest, or the chest itself. I expected that the items from the interface would of been at least put into the filtered interface or the chest connected to it. As I said before, when using an import bus to push items to the filtered storage bus/filtered interface, it acted as one would expect.

I have reason to believe the reason, in the newer version, this was a bug was because I had a similar system setup that used this method, I must of been mistaken and used an import bus to push the items, or a separate non filtered interface to put it into the rest of the system.

**Comment by mindforger** [comment]
okay your text is extremly confusing, please review it and try to figure what you mean and use the proper term

interface: 
-does acept items like any inventory as long as it can stuff them somewhere
-provides the content of the whole network as a virtual chest when connected to an storage bus
-provides 9 slots to stockpile defined number of items (acts as an real chest then as it holds the actual items)

import bus:
-obviously pulls items from attached inventorys (honestly i have no idea what this one does when attached to an non programmed interface)

storage bus:
-presents the attached inventory to the network as if it would be part of the network, only pulling and inserting items as priority criteria are met and storage accepting or providing the item beein moved by another part of the network (import/export/crafting)

what i see from your image is an chest with an storagebus, connected to an inteface, connected via storagebus to an terminal


unfilitered this would mean the terminal shows all items in the chest an every item inserted goes into the chest ...
the moment you filter the storagebus that access the interface, you can only access (import/export) the filtered item from that chest

by setting the interface up to stockpile certain item, any item inserted into the interface will be rerouted to said interface and be stockpiled until the preprogrammed number of items are stockpiled

every ecess item should flow into the chest but the terminal should only show the stockpiled number of items as far as i can remember

**Comment by zxvnm4** [comment]
I don't quite see why you find it so confusing, maybe you could be a bit more direct with the reason why(It might help me)? None the less I prepared a video that should be able to explain the situation. There is just for clarity sake and this "issue" has lost it's objective anyway.
https://youtu.be/thAPIAffnH0

**Comment by mindforger** [comment]
> I was using an interface to push those 64 wooden planks into the filtered storage bus/filtered interface

that does not make ANY sense ... an interface can only push when used with a pattern and a crafting request!
