### ISSUE TITLE
Suggestion: Give the export bus the ability to export all available items from an AE2 system.

### ISSUE THREAD

**Issue by zxvnm4** [AppliedEnergistics/Applied-Energistics-2#2853]
#### Environment

- Minecraft Version: 1.10.2
- AE2 Version: rv4 alpha build 11
- Forge Version: 12.18.3.2254

This could be used to export all the stored items in many different inventories via storage buses. With a network full of storage buses full of random items, one could use an export bus to act as a bunch of single import buses(Not like it is cheaper or anything but... Meh, it allows single sided stuff.)

This would be SUPER useful for buffer systems. Lets say you want to have a separate system that will store all of the ores and other blocks that are to be processed, and that said system is using a ME drive. It is easy to get the system to process said ores in such, but when it comes to all of the other blocks that come from a quarry you can't sort them without having a filtered export bus for each and every single one of the other materials, There is a way around this by storing all of the input items before hand, then sending them to their separate systems...

The other handy part about having an export bus that could export everything is that you can setup 2 systems. One system being an input system, and another being an output system. This system could be circular in some right, with the output system taking items from inventories and putting them in the ME drive, while the input system is taking all the items from the ME drive and putting them into what ever inventory is able to take said items. I implemented this system in a mod-pack that had Open Peripherals, which allowed me to use the AE2 API w/ Computer-Craft to take all the items from a network and try to cram them into an interface,

Oh and you cannot input into an IO Port so, trying to use that to do a similar thing doesn't work.

![2017-03-28_18 15 34](https://cloud.githubusercontent.com/assets/3515761/24432919/8d250172-13e2-11e7-84b0-89ba6706be23.png)
![2017-03-28_18 15 35](https://cloud.githubusercontent.com/assets/3515761/24432920/8f952a0e-13e2-11e7-8e4c-394f098bda48.png)
![2017-03-28_18 15 41](https://cloud.githubusercontent.com/assets/3515761/24432921/91b38d44-13e2-11e7-94e3-77bcbf26b8cf.png)

If you got this far, AE2's search algorithms seem a bit non-logarithmic (a non-balanced tree?), When I craft a stack of something, it takes less time to craft iron blocks(close to the start of the storage listings), to crafting tin blocks(far from the start of the storage listings). This could be completely false but *shrugs*.

**Comment by yueh** [comment]
No.

**Comment by douglasg14b** [comment]
Well, that's kinda toxic @yueh

**Comment by zxvnm4** [comment]
As much as his response was just rude and didn't give me any information as to why he disagreed. IO Ports now are not bugged as they were when I made this and can be used to produce the same effect as above in, of course, a less compact format.(Or in fact I wasn't able to pull out of the IO Port because a few of it's sides cannot be used to input or output the cell inside).
