### ISSUE TITLE
Memory card removes the previous connections

### ISSUE THREAD

**Issue by zxvnm4** [AppliedEnergistics/Applied-Energistics-2#2854]
#### Environment

- Minecraft Version: 1.10.2
- AE2 Version: rv4 alpha build 11
- Forge Version: 12.18.3.2254

When you use your memory card on a P2P tunnel you get copied and then loaded msg's. This erases the current connections the P2P tunnel has (It loads the empty memory card data onto the tunnel) and then loads it into the card.
![2017-03-28_18 24 44](https://cloud.githubusercontent.com/assets/3515761/24433141/ef6c9a4c-13e3-11e7-8c01-c72c548746a7.png)
![2017-03-28_18 32 48](https://cloud.githubusercontent.com/assets/3515761/24433348/2156a0f6-13e5-11e7-9e5e-1a900195dcd7.png)
![2017-03-28_18 33 13](https://cloud.githubusercontent.com/assets/3515761/24433350/23845508-13e5-11e7-819d-81efcb4cd39c.png)

**Comment by yueh** [comment]
This is a feature, because otherwise it would be impossible to create new tunnels at all.
