### ISSUE TITLE
Interface/bus issue

### ISSUE THREAD

**Issue by dan-at-the-van** [AppliedEnergistics/Applied-Energistics-2#2855]
Hi there. I seem to be having an issue involving interfaces and buses when too many of them are placed in a single network. I am using Minecraft 1.7.10 on a custom modpack but i have encountered this issue before on other packs so am confident it is not due to other mods. The issue arrises when a large number of buses or interfaces are placed in a single network. This causes buses to stop importing or exporting and prevents molecular assemblers receiving power from my network even when directly connected through other cables. This is not an issue with channels as i have intentionally disabled them and is not a power issue either. Upon removing buses or even sometimes encoded patterns from interfaces i have found that the buses start functioning again and the assemblers receive their power as they should. However upon the addition of a single extra encoded crafting pattern, a large number of buses stop working and all molecular assemblers can no longer receive power. I have encountered a few other issues that claim to be similar on forums but none of the fixes on these pages seem to have any effect. I can provide a full list of my running mods if you still believe this is the cause but as i said, this is a persistant issue i seem to come across occasionally in various modpacks.

**Comment by Zedrimar** [comment]
Ok, great! what version of the mod are you running?

**Comment by dan-at-the-van** [comment]
1.7.10 rv2-stable-10. the latest in the stable versions.

**Comment by Zedrimar** [comment]
go to 1.7.10 rv3 beta 6. it is the last build for 1.7 and probably as stable as it gets. Things have changed between rv2 and rv3 so I suggest you read up on that.

**Comment by Zedrimar** [comment]
rv2 is no longer supported

**Comment by mindforger** [comment]
>rv2 is no longer supported

as is every other 1.7.10 version ... 

rv3 is WAY more stable than rv2 ... as far as i understood, an version enters stable as the new version hits beta and gets a full backport .. still waiting for a stable rv3 to be honest :P 

still closing this for reasons :)

**Comment by dan-at-the-van** [comment]
rv3 crashes my client upon launching, it must have a mod confliction or something that doesn't exist with rv2.

**Comment by mindforger** [comment]
you can still post the crashlog, even if it is an unsupported version and the issue beeing closed ... someone may can help you :)
