### ISSUE TITLE
Pattern Terminal - Auto add existing items into crafting grid for easier use of NEI

### ISSUE THREAD

**Issue by tiggerbiggo** [AppliedEnergistics/Applied-Energistics-2#2856]
Firstly, I'd like to link to #355 and #2205 

The reasons given in these issues as to why this can't happen are frankly wrong and it really annoys me. Let's consider Logistics pipes as an example of how this should work.

Logistics pipes gives you the option of which oredict item to add BEFORE adding it to the grid. Why can this not happen? I agree, if it just added a random oredict item or left it up to the crafting to work it out, it would be buggy and slow, but why not just let the user decide which **specific** item? Even more annoying is the fact that there is no easy way to add the items I already have to the crafting grid once the "ghost" items have been placed, I have to search for each one and add it individually, so the problem is 2-fold. I can't even use NEI to easily add recipes for items already in my ME. 

I want to respond here to the comment @yueh made on #355:

**"The problem with this addon or even a config option is, that it will break the current autocrafting."**

No, it wouldn't if you let the user choose which specific oredict items to add

**"Just using the NEI recipe will cause it to specify randomly choosen oredict items"**

Not unless you program in a simple menu like the one Logistics pipes uses: [LINK](http://imgur.com/a/ub1t8)

**"AE2 is basically moving some calculation which would needed for every crafting request to require a bit more time during the pattern crafting once."**

Again, all these problems would be solved by just letting the user choose which item to use, it's not hard.

**" if the items are available inside the network you can just craft the pattern and then craft some of the items and put it back into the system for the following pattern."**

Ok then, but why do I have to go searching for them? In this instance: [LINK ](http://imgur.com/a/bTTT9)I have all the items right there available, why do I have to add them all in? It makes no sense, the system should just auto fill them with solid ghosts and let me craft it. Even when the items aren't faded ghosts, they're still technically ghost items, so what's the problem?

Look, I know it's your project, and at the end of the day you guys can do what you want with it, but your reasoning just makes no sense to me. If you have other deep seated technical reasons why this can't happen, **please** explain them, because again, none of this makes sense. At the very least, it would be great to automatically add items we already own into the grid once I have the recipe in NEI. None of this is the end of the world, it's a game after all, but Quality of Life improvements are always a good thing for everyone, and this one seems like it's been a long time coming.

Thanks for your time.

**Comment by yueh** [comment]
Yes, there are other reassons. Which are mainly based on the datastructures AE2 uses to allow for fast access of items, calculating the materials and similar.

I cannot go into many details here. But feel free to study the code.
