### ISSUE TITLE
ME Crash.

### ISSUE THREAD

**Issue by jibanyan626** [AppliedEnergistics/Applied-Energistics-2#2857]
When I try to place the ME Controller, It Crashes the game. 

- Minecraft Version: 1.10.2
- AE2 Version: Newest 1.10.2 - Can't find version, but do know that.
- Forge Version: 1.10.2 - 12.18.3.2254

**Comment by jibanyan626** [comment]
Sorry, Pastebin link: https://pastebin.com/raw/v20i7xXF

Crash log is there.

**Comment by Cobbs3** [comment]
Looks like the issue is do with the IC2 compatibility, you should try updating your version of AE2 because you are using Alpha-4 rather than the latest version which is Alpha-11

[http://ae-mod.info/Downloads/](url)

**Comment by jibanyan626** [comment]
Where would I find a Download link fo 1.10.2? They all say 1.7

**Comment by jibanyan626** [comment]
Thanks! I didnt realize that that was an old version.
