### ISSUE TITLE
"Select Amount" dialog malfunction - appears coordinate based?

### ISSUE THREAD

**Issue by andreboogaards** [AppliedEnergistics/Applied-Energistics-2#2858]
I moved my working AE2 setup to a new location. "Select Amount" UI stopped working. Attempted some troubleshooting (most likely not relevant anymore, but see https://forum.feed-the-beast.com/threads/ftb-beyond-release.220305/page-23#post-1853789). Ultimately seemed to be able to boil it down to coordinates of a terminal.

Tested setup:
http://image.prntscr.com/image/e4deb45b6593476c9bb5fafd119f2a5e.png
http://image.prntscr.com/image/b6448d4448a74f0f96430d12571095d5.png

The terminal on the left (x=35,z=102) functions as expected: I click a pattern, a window pops up that allows me to select the amount.
The terminal on the right (x=34, z=102) doesn't function as expected: I click a pattern, the entire UI closes itself.

No log messages are generated at all, not on the server, not on the client.

- Modpack: FTB Beyond 1.3.0 (only change to this modset is adding FullscreenWindowed-1.10.2-1.5.0, removing it made no difference to the problem)
- Multiplayer, self-hosted server on linux
- Minecraft Version:  1.10.2
- AE2 Version: appliedenergistics2-rv4-alpha-11
- Forge Version: ForgeMultipart-1.10.2-2.0.0.29-universal, Forgelin-1.4.1 (not sure which one actually is Forge)

Savegame available on request

**Comment by CraftMinerKyle** [comment]
Ok. #1: ForgeMultipart is a ChickenBones and Forge only mod, not a mod loader. #2: Forge version is displayed when you launch the game. Go to "Profiles", 'Edit Profile", and then click "Minecraft Version". The selected version should look like "Forge1.7.10r28.938.9283" Or something along those lines.

**Comment by yueh** [comment]
Remove wireless crafting terminal. It is know to break autocrafting in many ways.

Should it still appear after that, please give an update about it, so we can reopen the issue.
