### ISSUE TITLE
The sky stone chest can be opened when a block is on top of it

### ISSUE THREAD

**Issue by PapiDimmi** [AppliedEnergistics/Applied-Energistics-2#2859]
Version: rv4-alpha-11

**Comment by TheSirati97** [comment]
I through that was a feature :O

**Comment by PapiDimmi** [comment]
“It’s not a bug; it’s a feature!”

**Comment by mindforger** [comment]
please leave this feature, also @PapiDimmi have you ever wrenced a skystone chest? you can rotate it to let it open in any direction, sideways and even downwards i think this is intended

**Comment by PapiDimmi** [comment]
It might be intended; I don’t know. I’ll wait for a developer to respond.

**Comment by yueh** [comment]
See it as feature. But I think the vanilla chest itself is kinda broken with allowed to opened through a stair...

**Comment by PapiDimmi** [comment]
I know that vanilla chests can be opened under chests; this is a known bug and might as well be intended, since it’s never been fixed after all these years.

That said, the sky stone chest can be opened under regular blocks, which is out of the ordinary. I don’t get why this would be intended; it doesn’t really make any sense.

**Comment by TheSirati97** [comment]
it's alien technology. far outside of the reach of a minecrafters understanding! :D
