### ISSUE TITLE
AE2 is not compatibile with SpongeForge

### ISSUE THREAD

**Issue by kamanabc123** [AppliedEnergistics/Applied-Energistics-2#2860]
If you attempt to load AE2 and spongeforge at the same time it will give you an error saying that ae2 didnt allow it to patch something. Obviously this is not good and I don't know if this is a spongeforge or an ae2 issue but I hope it gets fixed none the less.
- Minecraft Version: 1.10.2
- AE2 Version: rv4 alpha 11
- Forge Version:  2554

**Comment by mindforger** [comment]
known issue, not easy to solve, there are workarounds
