### ISSUE TITLE
Lag spike upon chunk loading / unloading - 1.10.2

### ISSUE THREAD

**Issue by Rubbertjuh** [AppliedEnergistics/Applied-Energistics-2#2862]
#### Description
There seem to be some serious lag spikes coming from Applied Energistics when certain chunks are loaded and/or unloaded. I've attached the download link for the VisualVM profiles (.nps file format) 

#### Environment
Running on a multiplayer environment running SpongeForge. Player count, 20 players online at all times atleast, peaks at 50.
Happens with 15 players online and above. 
Version appliedenergistics2-rv4-alpha-11
Modpack: FTB Beyond 1.3.0
    Minecraft: 1.10.2
    SpongeAPI: 5.2.0-SNAPSHOT-a3257a01
    SpongeForge: 1.10.2-2254-5.2.0-BETA-2264
    Minecraft Forge: 12.18.3.2254

Profiles:
https://toastynetworks.net/rsampler.php?id=17d4318abf3a4af599e40fa9c8313dc7
https://toastynetworks.net/rsampler.php?id=234733c9753e47158e8f3e77976345a3

**Comment by mindforger** [comment]
depending on the size of ME systems i would recommend always to chunkload them, calculating an entire network can take quiet a bit time if complicated enough

**Comment by Rubbertjuh** [comment]
We're trying to chunk load as much as possible, however on a server of this size we can't chunk load everything. 
Is there something you could possibly do to optimize the unloading/loading of chunks/setups?

**Comment by CraftMinerKyle** [comment]
Hey Rubbertjuh! Can I make a simple suggestion that may/may not work? Try compressing you systems vertically into one or two chunks, so that machines can be always loaded at the same time, as well as reducing the amount of chunks required to load.

**Comment by mindforger** [comment]
Yeah sorry for the lack of answer i was hoping for a dev comment as i have no better solution yet

**Comment by CraftMinerKyle** [comment]
Also, I noticed something else about your problematic server: You are running Sponge. A lot of error reports claim they are using Sponge, and the problem/glitch is unique to running Sponge servers. Could your unusual spikes be from running sponge? I often use CraftBukkit or CanaryMod, as they work great with a lot of things. Modded servers with plugins, probobly CanaryMod is a good alternative.

**Comment by CraftMinerKyle** [comment]
Also, for more info, do you know the allocated RAM to the server? Most mods and modpacks suggest at least 1.5, and very graphical mods suggest at least 2 Gigabytes.
