### ISSUE TITLE
Quantum network bridge is not connecting despite being lit up.

### ISSUE THREAD

**Issue by TheDisturbedDragon** [AppliedEnergistics/Applied-Energistics-2#2863]
#### Description
When I attempt to establish a quantum network bridge it fails to connect.  Despite this, the sides of the bridge DO light up on the sides while the corners don't.  I have tried renaming the singularities, using individual power sources for each side piece of both bridges, and a lot of other things.  Nothing has succeeded.
What's confusing is that they are lit - which according to the AE wiki tells me that they should be connected - but only on the sides.  I don't know what this means, and my searches have found nothing.
I'm not sure whether this is a bug, glitch, or just me being a moron, but I'd appreciate any help I can get.

#### Environment
Mods that I'm using:
Advent of Ascension 2.3
Decocraft 2.3.6.1
Draconic Evolution 1.7.10_1.0.2h
Tinkers Construct + Tinkers Tweaks 1.8.8 and 2.1.6 respectively
Thermal Expansion 4.1.2
Enderio 2.3.0.424beta
Magical Crops (w/ integration addon) 4.0.0 PUBLIC BETA
Botania 1.8-249
MineFactory reloaded 2.8.1
ChickenChunks/core 1.3.4.19
Ender Storage 1.4.7.37
Et Futurum 1.5.5
Extra Cells 2 2.3.9
Extra Utilities 1.2.12
ExtraTiC 1.4.5
Microblocks 1.2.0.345
ImmersiveEngineering 0.7.5
InvTweaks 1.59-dev-152-cf6e263
Lycanites (all) 1.13.0.5
Matter Overdrive 0.4.1
Mekanism + tools/generators 9.1.0
NEI 1.0.5.118
OpenBlocks 1.5.1
Pam's Harvestcraft  1.7.10i
ProjectE 1.7.10-PE1.10.1
Thaumcraft 4.2.3.5
Twilight Forest 2/3/7
Thermal Dynamics + Expansion +Foundation 1.1.0, 4.1.2, 1.2.3 respectively
Veinminer 0.31.4
Witchery 1.7.10-0.24.1

There's no crashlog since this doesn't actually crash anything, it just refuses to bridge.  The console doesn't spew out any message when I put in both singularities or anything like that.  I've got a four block wide controller with two levels - the one in the very front was a mistake that I never got around to removing and creative power cells (both AE and RF) connected to the network.  The singularities are named the same.  I've got MineFactory chunk loaders keeping both areas loaded, and both are powered by a creative cell.  I've also tried with ChickenChunks loader but the outcome is the same.

- Minecraft Version:  1.7.10
- AE2 Version: RV3-beta-5
- Forge Version: 10.13.4.1614

My setups and the bridges themselves:
![2017-04-09_16 08 03](https://cloud.githubusercontent.com/assets/25781898/24841725/51539f6c-1d3f-11e7-953d-e3418c8576da.png)
![2017-04-09_16 08 52](https://cloud.githubusercontent.com/assets/25781898/24841726/515404d4-1d3f-11e7-9075-12ebb9fb71ec.png)
![2017-04-09_16 09 13](https://cloud.githubusercontent.com/assets/25781898/24841727/51557670-1d3f-11e7-9174-55b56cedcfc7.png)
![2017-04-09_16 09 35](https://cloud.githubusercontent.com/assets/25781898/24841728/5155c7ec-1d3f-11e7-8b68-dbf3ed94d5ec.png)

**Comment by mindforger** [comment]
just to be sure because i see a creative energy cell there, you did NOT spawn the entangled singularitys, you actually entangled them by exploding the singularity ?

creatively spawned entangled singularitys acn not work because they are spawned and not entangled through the designed mechanics

**Comment by CraftMinerKyle** [comment]
Hey! Your pack looks alot like one of my packs I made! The problem you are having is the same problem that I had when I first tried to set up link chambers. Just like you, I pulled 2 singularities out of creative. First I was dumb enough to try and craft them, only to find that you have to use a matter condenser. So I tried to automate cobble generators to put into the matter condenser, but I realized I could just pull them out of creative. I didn't realize that you need to explode it with ender dust until I looked it up. Then, I had problems with having the controllers go red (You can't have multiple controllers in 2 different places on one network.) I finally got smart and got it right after destroying the controllers on one side of the chambers. If any of this explains any problems you may have had, or simply amuses you with my sheer stupidity at the time, please tell me. Thank you and God bless.

**Comment by TheDisturbedDragon** [comment]
Strangely enough no, I didn't end up spawning them in creative.  I didn't see them in NEI (probably just missed them) so instead I set up a condenser with projectE red matter blocks.  So unfortunately that's not it...

**Comment by CraftMinerKyle** [comment]
Try making a setup in creative in another world. Make an ME System the bridges(Within a vicinity of each other, so you can see if it works on both ends), blow up the singularity and ender dust to get the 2 Entangled ones, place them on each of them and place an item into the system and check the terminal and the other bridge. If that item appears, then Hooray! It worked. If it says "Missing Channel", then there is a problem. Oh yeah, almost forgot: Machines need power.
