### ISSUE TITLE
import/export buses and molecular assemblers dont work even if lighten up and on a free channel

### ISSUE THREAD

**Issue by crystal211** [AppliedEnergistics/Applied-Energistics-2#2864]
#### Description
i have a pretty large but organised 7x7x7 controller with cables going into my areas of crafting/processing and at some point of my map the import/export buses as well as my molecular assemblers just forget how to work. they dont import or export items in/out of the system [i made sure they are active and taking a free channel. the molecular assemblers simply have all of the items they need already in the system but just dont use them up for the crafting process as if they forgot how to craft

#### Environment
i am using the infinity version 2.6.0 modpack through the curse launcher [this also happend through the ftb launcher] 

- Minecraft Version: 1.7.10
- AE2 Version: rv3-beta-6.jar
- Forge Version: 10.13.4.1614

**Comment by mindforger** [comment]
1.7.10 is not supported anymore, sorry

can you still post a few pictures please?
also have you ensured you have enough (dense) energy cells installed? input mean nothing when your internal buffer is too small! Also are all parts of the network within viewing distance (meaning them all beeing loaded or supplied with chunkloaders)

i am closing this  for out of support reasons, we can reopen if you can reproduce this in higher versions
but please also send the requested infos, it most likely is an setup issue
