### ISSUE TITLE
Problem with autocrafting (witchery related) 1.7.10

### ISSUE THREAD

**Issue by LordViperagyil** [AppliedEnergistics/Applied-Energistics-2#2865]
Trying to autocraft witchery poppets it only allows the base one, not the actual useable ones.

#### Description
 When I try to autocraft death protection poppets it allows me to craft the base one, but if I try to request the death protection ones (or any other useable), after chosing the amount (even if it 1) clicking on the next button just makes the sound and didn't advance to the required items screen. ( I have everything it needs in excess)  

#### Environment
 flat land testing world, a village in the distance, a medium otherwere circle next to the machine with grasspers.
 The mods are: ae2 rv2-stable10 1.7.10 , both sp and mp, witchery 0.24.1, blood magic 1.3.3-17, codechicken core 1.0.7.47, nei 1.0.5.120,openmods core 0.10, baubles 1.0.1.10,thaumcraft 4.2.3.5, forge multipart 1.2.0.345. chisel 2.9.5.11,extra utilities 1.2.12. journey map 1.7.10-5.1.4p2 , magical crops 1.7.10-0.1, 
mekanism/gen/tools 8.1.9, openmods 0.10,openblock 1.6 project-e 1.7.10-PE1,10.1 , waila 1.5.10, wawla 1.3.1, another one bites the dust 2.9.2.

- Minecraft Version: 1.7.10
- AE2 Version: rv2-stable-10
- Forge Version: 10.13.4.1614

**Comment by LordViperagyil** [comment]
Update: I tried it with only witchery ae2 and nei. now it allows me to craft the, and the bounded one is working, but the unbounded poppet is not. the system scheludes it and craft every prior thing but does not craft the actual death protection poppet itself. the crafting cpu just has it booked and never craft it.

**Comment by mindforger** [comment]
1.7.10 is not supported anymore, if you can repüroduce this in higher versions please make a new issue

PS update to rv3, rv2-stable ist hell a alot more bugged than rv3-beta

**Comment by LordViperagyil** [comment]
Witchery doesn't exist in higher versions.
