### ISSUE TITLE
Creative Tabs Crash in beta 6...

### ISSUE THREAD

**Issue by Axelandre42** [AppliedEnergistics/Applied-Energistics-2#2868]
When i go to the page containing the AppliedEnergistics Creative Tab, it crashes

#### Description
I created a small mod to display a list of CreativeTabs and their Item icons. In the list, the Item icon for Applied's CreativeTab was "null" so I removed Applied and its dependencies from the client and the server : No crash, all tabs accessible.

So, you have got everything.

```java
if (e.gui instanceof GuiContainerCreative)
for (CreativeTabs tab : CreativeTabs.creativeTabArray) {
	mod.logger.info("This is a creative tab : " + tab.getTranslatedTabLabel() + " - And its icon is : " + tab.getTabIconItem());
}
```
It's a sample code of my small tab lister mod.

#### Environment
Side: Multiplayer
Crashlog: https://paste.ee/p/HYiTX

- Minecraft Version: 1.7.10
- AE2 Version: rv3-beta-6
- Forge Version: 10.13.4.1614

**Comment by mindforger** [comment]
Can you confirm this issue in any version beyond 1.7.10? If yes please Open a new issue and link to this, 1.7.10 is Not supported anymore but it will eventually get a backport
