### ISSUE TITLE
Overall Problems with Storage buses, just plain broken.

### ISSUE THREAD

**Issue by TheUnderTaker11** [AppliedEnergistics/Applied-Energistics-2#2869]
#### Description
Expected behavior: Put a storage bus on a chest, it uses the chest to store items instead of the disk drive. Same concept with the Quantum storage, it should just basically use whatever it is attached to as storage for the system.

Actual behavior: It is already well know the quantum storage is super buggy, but even putting the storage bus on something as simple as an alchemical chest from ProjectE is causing item's to get duped and over stacked in the chest, [Link to screenshot](https://imgur.com/a/F4XM3).
It should be noted I started with less than a stack of item conduits, and noticed a ton in my system, which was what first hinted to me that stuff was getting duped. On that same note, many other things such as the wooly, conduit binder, and items in a different chest outside the screenshot got duped as well.

#### Environment
Single player, lots of other mods. Specific mods interacting are ProjectE, and Quantum Storage.

- Minecraft Version: 1.10.2
- AE2 Version: appliedenergistics2-rv4-alpha-11
- Forge Version: 12.18.3.2281

**Comment by TheUnderTaker11** [comment]
Update, after restarting the game the chest now looks [like this](https://imgur.com/a/GCSIj).   
Still wayyyy more conduit binder than I put in though.

**Comment by ThomasAunvik** [comment]
> We decided to drop any support for special inventories in 1.10 because forge provides a common interface now for anyone to use (at least up to 2^31 per slot, like a dsu).
> 
> This results in longer having to add support for every storage mod out there to every mod interacting with storages. Now each storage mod can implement their own solution and everyone can use it. And it just works. For example storage drawers, there is no special support for it on our side.
> 
> Should a mod still insists on doing it as in 1.7.10 instead of adapting to 1.10, they certainly can expect other mods not supporting it when there is another solution which requires less work and provides more benefits.
-Yueh https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2550#issuecomment-257512457

**Comment by TheUnderTaker11** [comment]
Alright thank you, now I can inform the mod authors to switch to the new system if things are wonky
