### ISSUE TITLE
Interface - Round Robin to replace Blocking Mode

### ISSUE THREAD

**Issue by PhiPhiper** [AppliedEnergistics/Applied-Energistics-2#2870]
#### Feature Suggestion:
Apparently there a some issues with the interface's blocking mode and other mods (eg. ae2 stuff, ender io,...). For the ignorant (wrt development) players it is of little importance who makes it work to fit the intent of distributing to adjacent machines. Therefore I'd suggest a feature eliminating the need for other authors to adapt specifically to the ae2 interface by replacing the blocking mode with a round robin mode (maybe an extra upgrade card for balance?).

#### Environment
- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-11
- Forge Version: 12.18.3.2254

**Comment by yueh** [comment]
The idea was always to have stateless interfaces, to avoid as many issues as possible with them. Like maintain them between chunk reloads and similar.

Yes, blocking mode might not the ideal solution for every mod. But it is designed with vanilla as "gold standard" in mind. Like normal furnaces. The only real alternative which will not force every mod to explicitly support AE2 (or us to support every mod out there), is if forge itself would add something to detect a working or idle machine.
