### ISSUE TITLE
Channels not being recognized or used when connected to things

### ISSUE THREAD

**Issue by SuperUnitato** [AppliedEnergistics/Applied-Energistics-2#2871]
#### Description
My cables aren't picking up any channels and nothing is being recognized as a channel. My interface for looking at all of my items for example isn't recognized, which uses just a regular covered cable. Interfaces for crafting and such aren't recognized either and those are hooked up with dense cable. Ive tried using both cables and nothing works. The controllers have full power. It is hooked up the same way as the one in my other base and that one works? The controllers form a square around the room, could that affect something?

#### Environment
This is in SP, and I'm using the mod pack All the Mods 1.10.2.
![2017-04-13_19 49 56](https://cloud.githubusercontent.com/assets/27461836/25029517/ca5c2edc-2083-11e7-9356-68a7669588b1.png)
![2017-04-13_19 50 04](https://cloud.githubusercontent.com/assets/27461836/25029519/cfb72ec2-2083-11e7-9590-580d18ef7259.png)
![2017-04-13_19 50 16](https://cloud.githubusercontent.com/assets/27461836/25029522/d7b5db6e-2083-11e7-8a26-6fdd98813291.png)
![2017-04-13_19 50 21](https://cloud.githubusercontent.com/assets/27461836/25029525/dae497bc-2083-11e7-92c2-f1d9791dfa93.png)

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-11
- Forge Version: 12.18.3.2254

**Comment by Ommina** [comment]
[The maximum number of CPU blocks in a row is seven.](http://ae-mod.info/ME-Controller/)

**Comment by CraftMinerKyle** [comment]
See how the CPU wires are red? That means that there is a problem with the CPU setup and the system cannot work. Remove the CPU blocks one at a time until they start changing colors. Ommina claims the new limit is 7, and know that you said you used Dense cables to machines. Dense cables are only good for channels, and cannot DIRECTLY be connected to machines or interfaces.

**Comment by mindforger** [comment]
Going to close this, issue is clearly too long controller chain
