### ISSUE TITLE
Import useful features done in Logistics pipe

### ISSUE THREAD

**Issue by Telokis** [AppliedEnergistics/Applied-Energistics-2#2873]
Since there is no **full** integration available between LP and AE2 in 1.7.10, I'd like to suggest some features I find really interesting to have.

**A way to require autocrafting for a recipe.** Based on the _Logistics request table_, a way to ask my AE2 system to autocraft a bunch of items so that I can directly get what I want to craft my recipe. (It is really annoying to craft everything "manually" item by item.)

**A more compact way to keep a certain amount of items in an inventory.** Based on the _active supplier module_ from LP, this would allow me to always have, say, 100 crafting tables available in the system. They would autocraft to fill the need. This can be done with level emitters but use a lot of channels for just one item to keep.

**A way to craft items by sending inputs to different places.** Much like the _satellite pipe_, a way to, for example, send item **A** to machine **mA** and item **B** to machine **mB** in order to get object **C** as a result.

**Finally, I'd really like to see a _full_ integration between AE2 and other inventory-managing mods.** What I mean by _full_ is:
* Two way items input and output. (Being able to take items from AE2 to put them in system B using a storage bus **AND** vice versa)
* Two way crafting discoveries. A craft _simply_ is a given amount of inputs that returns a given amount of outputs. In much the same way we would be able to see items thanks to the point above, we would also be able to request crafts.

NB: This whole feature request is made with LP in mind but that could be replaced with any inventory manager I guess.

**Comment by yueh** [comment]
> A way to require autocrafting for a recipe.

Not sure what you want, but either already possible or already rejected.

> A more compact way to keep a certain amount of items in an inventory.

More compact/smaller/efficent is already the keyword to reject a suggestion

> A way to craft items by sending inputs to different places

Already possible, otherwise as the previous.

> Finally, I'd really like to see a full integration between AE2 and other inventory-managing mods

While it sounds nice, it can be a major performance issue. Not even speaking about the amount of effort to maybe get it to work. In some cases it might not be even possible as these mods might be also locked down for similar reasons.
