### ISSUE TITLE
Internal Server Error upon attempting to link wireless terminal

### ISSUE THREAD

**Issue by smithb99** [AppliedEnergistics/Applied-Energistics-2#2875]
#### Description

When I try to link a wireless terminal in the security station, I lose connection to the server with an internal server error message. The server doesn't crash, and I can rejoin like nothing happened, but it does not link. The same thing happens when I try to open the terminal by right-clicking.

#### Environment

The server is locally hosted, and we use a custom modpack of my own design. This issue doesn't deal with other mods, though, only AE.

- Minecraft Version: 1.7.10
- AE2 Version:  rv3 beta 5
- Forge Version: 10.13.4.1614

**Comment by mindforger** [comment]
Clear your client and server logs, launch server and client, connect, try to produce the bug without doing too much other stuff, close server and client und upload the logs of both
