### ISSUE TITLE
Inscribers Dont work

### ISSUE THREAD

**Issue by sebat2** [AppliedEnergistics/Applied-Energistics-2#2877]
My Inscribers just don't work. It just don't take energy from network. It was working last time.
I don't know what's going on, help me ;(
- Minecraft Version: 
FTB Infinity Evolved 2.6.0

![obraz](https://cloud.githubusercontent.com/assets/27779710/25193186/801c1d66-2536-11e7-8b8e-013513a02c71.png)

**Comment by CraftMinerKyle** [comment]
Try manually printing stuff with the Inscriber. If that doesn't work, than it is a mod issue. If it does work, than it is your setup issue.
