### ISSUE TITLE
Compass

### ISSUE THREAD

**Issue by Mroczus** [AppliedEnergistics/Applied-Energistics-2#2879]
- Minecraft Version: 1.10.2
- AE2 Version:  1.10.2 rv4 alpha 11
- Forge Version: ForgeMultipart-1.10.2-2.0.0.31-universal

My meteor compass doesn't work. It just keeps spinning again and again. I've looked into options and there is only "no tooltip defined, restart the game" Any suggestions?

**Comment by CraftMinerKyle** [comment]
Ok, This is not a bug. This means that there are no meteors detected in the chunks you have loaded. The best way to get the compass working again is to go FAAAaarrrr out and load as many chunks as you can. Eventually, you will encounter a chunk that has a meteor. If you have NEI installed, F9 brings up chunk borders so you can see what 2x2 chunk area has the meteor once the compass locates a meteor. Also, the compass will spin wildly once it has encountered a 2x2 chunk area that has a meteor. So if you have not ventured out with your compass, you may just be standing on top of a meteor. One last note: Meteor Compasses only work properly if placed on the ground or held in your inventory. If you have it in a chest or in any non-player inventory, it will not work.

**Comment by CraftMinerKyle** [comment]
Here is a key for help:
Blue Pointer is spinning slowly around: No meteor chunks detected
Blue pointer is spazzing out and spinning like mad: Player is inside of a meteor chunk
Blue pointer is constantly pointing one direction: Follow it!

**Comment by mindforger** [comment]
if you got a mod that can visualize chunk borders, you can pin down the location of the meteor without blindly digging holes

if there are two chunks, the meteor has to be at the border of the two, just dig 2 holes 4 blocks off the center along the edge between the chunks

if there are 4 chunks it is even easier, you just have to dig down the corner and will have a 100% hit ... except there may be multiple smaller ones close to each other sometimes

**Comment by CraftMinerKyle** [comment]
Every meteor I have ever seen or found has been a 2x2 Chunk one that I just dig a stairway down in the corners of each of the chunks. There are smaller ones that can take only 1 chunk?

**Comment by mindforger** [comment]
i had everything in my MC life already, small one in a single chunk, big one in 4 chunks and 3 medium sized in 6 chunks, thrust me, everything is possible :)

@Mroczus to repeat the initial question of kyle, does it sping fast like crazy or really slow?

**Comment by CraftMinerKyle** [comment]
"Thrust you"? Am I some sort of rapist? :<) I know, it's a typo, but PLEASE check your spelling. lel

**Comment by mindforger** [comment]
yeah thank you smartphone ... i can't even edit on mobile XD

**Comment by CraftMinerKyle** [comment]
#AutoSpell=Creepers
