### ISSUE TITLE
Crafting butter via fresh milk gets the fresh milk stuck as "Scheduled"

### ISSUE THREAD

**Issue by TomyLobo** [AppliedEnergistics/Applied-Energistics-2#2880]
#### Description

1. Make sure the following recipes are available:
     - Crafting Patterns (with ore dictionary disabled) in non-blocking-mode interfaces attached to (powered) molecular assemblers:
         - saucepan+heavy cream+salt -> butter
         - mixing bowl+fresh milk -> heavy cream
         - milk bucket -> 4 fresh milk
2. Make sure there are no conflicting recipes
3. Make sure _none_ of the following items are present:
     - fresh milk
     - heavy cream
4. Make sure there the following items _are_ present:
     - 1 milk bucket
     - 1 salt
     - cutlery
         - 1 saucepan
         - 1 mixing bowl
5. Craft butter
     - Expected: butter is crafted, crafting CPU is freed
     - Actual: butter is still crafted, but 4 fresh milk get stuck as "scheduled"

Crafting fresh milk from these preconditions works and so does crafting heavy cream.
If I pre-craft fresh milk (or heavy cream), crafting butter works, too.

#### Workaround
If I change the heavy cream recipe to use a milk bucket instead of fresh milk, the issue disappears.
I'm reporting it anyway, since it might affect other recipes.

#### Environment

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-11 with [unrelated modifications](https://github.com/AppliedEnergistics/Applied-Energistics-2/compare/master...TomyLobo:fix-blocking-mode)
- Forge Version: 12.18.3.2254
- Pam's Harvestcraft Version: 1.9.4-1.10.2g

**Comment by yueh** [comment]
Cannot reproduce.

Also we cannot support custom builds. Please ensure that any bug can be reproduced with an official release.
