### ISSUE TITLE
Applied Energistics 2 does not work with forge mircroblocks.

### ISSUE THREAD

**Issue by novakedward** [AppliedEnergistics/Applied-Energistics-2#2882]
#### Description
The mod doesnt let me place blocks around the cables to make the cables hidden and look nice.

#### Environment

- Minecraft Version: 1.10.1
- AE2 Version:  RV4-alpha-11
- Forge Version: 12.18.2.2254

**Comment by VT-14** [comment]
See #2809 

AE2 provides its own facades to cover cables and busses.  4 cable anchors in a + shape around practically any block.

**Comment by novakedward** [comment]
Thanks for quick response. although I much prefer micro blocks.
