### ISSUE TITLE
Applied Energetics prevents Sponge from patching Forgemodloader class

### ISSUE THREAD

**Issue by Trickster29** [AppliedEnergistics/Applied-Energistics-2#2883]
As you may know, sponge is a replacement for bukkit made by the forgemodloader team themselves. 

You can see more about it on :
www.Spongepowered.org

I ran what I believed to be the latest version of your mod (1.10.2 rv4 alpha) and it prevents the Sponge enabled server from patching a class. Because it loads it before sponge patches it.

It would be appreciated if you could make your mod work with sponge. As many servers appreciate the extra functionality that sponge offers. As-well as I love your mod. And would love to re-include it on our server. 

Environment:
While your mod is installed along side sponge, near immediately (within the first 30 seconds) after starting the server, it will crash saying sponge failed to patch a class. Claiming to check core mods to see if any of them loaded it prematurely. i removed every mod one by one that was considered a core mod. Upon removing Applied Energistics the problem ceased. None of the other core mods i had caused the issue.

Minecraft Version: 1.10.2
Forge Version:  forge-1.10.2-12.18.3.2281-universal
Ae2 version: appliedenergistics2-rv4-alpha-11
SpongeVersion: spongeforge-1.10.2-2123-6.0.0-BETA-1902

**Comment by Trickster29** [comment]
Latest Forge and latest experimental sponge for 1.10.2 were used.

**Comment by mindforger** [comment]
not want to sound to agressive, but you'd only have to use the search to find the solution prior making a new issue :)

Duplicate
#2482

Solution at the bottom of the topic is using SpongeBootstrap: https://forums.spongepowered.org/t/spongebootstrap-fixes-ordering-issue-with-other-coremods/12275

**Comment by Trickster29** [comment]
im terrible sorry. im new to github, thank you for the information. :)
