### ISSUE TITLE
Only two of my ME drives are powered

### ISSUE THREAD

**Issue by donoheath** [AppliedEnergistics/Applied-Energistics-2#2884]
Hello. I have installed AE on my survival world and I was trying to add more ME drives to my system but it seems that the last one will not get power. This is strange because when drives are placed adjacent to each other, they are supposed to share power. That is not the case with this however. I have provided a screenshot of my drives:

(https://cloud.githubusercontent.com/assets/24435718/25414901/61e149ea-2a02-11e7-831e-9e0a0da8a8d4.png)

If anyone possibly knows the solution to this problem, I will be very grateful.

**Comment by mindforger** [comment]
Any reason why you closed the issue?

**Comment by donoheath** [comment]
I figured out the problem. Didn't want anybody answering if I already figured it out within 5 minutes.

**Comment by mindforger** [comment]
kay :D still care to share the issue? it was not obvious in the picture, must have been something hidden ?

**Comment by donoheath** [comment]
Nah it's all good. There was a dense cable behind the top ME drive and for some reason that was cutting the power. I removed it and the problem was solved.
