### ISSUE TITLE
Not a bug——about Certus quartz

### ISSUE THREAD

**Issue by forestbat** [AppliedEnergistics/Applied-Energistics-2#2886]
I‘m a translator of China and I want to ask，why quatz and that purple crystal were named Certus and Fluix？What memes they are instead of？

**Comment by CraftMinerKyle** [comment]
Do you mean "Why were the crystals named Certus and the purple being Fluix? What do they mean?"

**Comment by mindforger** [comment]
he want's to have a non-(semi-)fantasy name that he can use for translation as those names translate not well

the only alternate meanings i could find for "certus" is "reliable" and "fluix" meaning of things beeing in a "flow", maybe because the items flow as energy stream through the cables?

**Comment by CraftMinerKyle** [comment]
That i good! Can you also try "Synthetic" for fluix?

**Comment by forestbat** [comment]
@mindforger “Reliable crystal” is not very suitable，I think……Do I tell other people the certus is “可信水晶” in Chinese？

**Comment by forestbat** [comment]
@CraftMinerKyle Synthetic or Flow are both good。

**Comment by mindforger** [comment]
trusted and reliable have the same basic meaning, so your's is fitting

**Comment by CraftMinerKyle** [comment]
I actually don't know Cantonese or Mandarin, but I got "Synthetic" from the fact that you have to unnaturally make the crystals by combining Charged Certus (Try using "Broad" for certus) and redstone to make Fluix.

**Comment by yueh** [comment]
These are pretty a real name. So there is no real translation for it.

It predates vanilla quartz and was just called quartz. Certus was pretty much added to not have 2 different items with the same name.
Certus is actually based on the latin word "certus". Maybe that helps.

No idea curently about fluix. But also pretty much a name thus lacking a translation.
