### ISSUE TITLE
Duplication with annihilation plane

### ISSUE THREAD

**Issue by Gohu29** [AppliedEnergistics/Applied-Energistics-2#2887]
The annihilation plane does not break the block but it recovers them

https://www.dropbox.com/s/jyvms6ugprdezog/Dupe%20Bug.gif

List of mod: https://pastebin.com/9b56HxAd

last version Alpha 11
SpongeAPI: 5.2.0-SNAPSHOT-a3257a0\n   
SpongeForge: 1.10.2-2254-5.2.0-BETA-2236\n    
Minecraft Forge: 12.18.3.2254

**Comment by yueh** [comment]
We do not support Sponge officially.

Should you be able to reproduce it without it, please update the issue accordingly and we will reopen it.
