### ISSUE TITLE
A New bug with latest SpongeForge and AE2

### ISSUE THREAD

**Issue by NocturnalSergal** [AppliedEnergistics/Applied-Energistics-2#2889]
#### Description

While using the latest version of spongeforge and AE2 (im going to open a issue in SpongeForge github aswell) there is a world interaction that is seemingly unbeknownst to sponge. I had a import bus and a storage bus on the same me network while this was happening. cant really describe why, i could read enough of the error to tell it was AE2 and Spongeforge yet again squaring off <3

https://pastebin.com/Vrt7YM3b

#### Environment
CentOS 7
Oracle Java 8u121 64-bit

- Minecraft Version: 1.10.2
- AE2 Version: RV4-Alpha11 with the sponge patch
- Forge Version: 2254

**Comment by Idesmi** [comment]
It affects me too.

**Comment by NocturnalSergal** [comment]
@Idesmi this was fixed (assuming it hasnt poped its head back up) by a more recent spongeforge update
try updating your Sponge and see if that fixes it

**Comment by yueh** [comment]
We do not support Sponge officially.

Should you be able to reproduce it without it, please update the issue accordingly and we will reopen it.
