### ISSUE TITLE
Redstone Arsenal - Omniwrench - Not compatible with AE2 in 1.10.2

### ISSUE THREAD

**Issue by Hodel1** [AppliedEnergistics/Applied-Energistics-2#2890]
#### Description
i wish a support of Wrenches to dig up anything.
For example: The Omni-Wrench can't break any AE2 Blocks in 1.10.2.
In 1.7.10 were not a problem.

At first I thought it was the Wrench so i posted it at CoFH Teams Issuetracker.
https://github.com/CoFH/Feedback/issues/178

#### Environment
Multiplayer, Debian Server, with SpongeForge

- Tested in FTB Beyond 1.5.3
- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-11 (With Spongefix)
- Forge Version: 12.18.3.2254

**Comment by thiakil** [comment]
To be honest, it's equal parts COFH and AE - AE only ever had the buildcraft wrench interface support (which in 1.7 COFH had on their wrench), and COFH doesn't have AE's wrench class either.

**Comment by mindforger** [comment]
Wrench unification is gone since past 1.7.10 unfortunately, maybe there will be common sense about this in 1.11 or 1.12 but everything is moving too fast at the moment

**Comment by thiakil** [comment]
Yeah it's sad that KL seems to have no desire to add outside integration.

I've added BC and COFH wrench support to my 1.11 fork though

**Comment by mindforger** [comment]
AFAIK BC wrench was base for all in 1.7.10, but BC skipped 1.10 for 1.11 because of reasons (no blame on them, fair descision)
let's see how fast BC goes online and how fast AE2 will adapt, i am tempted to change the titel and leave it open, but i would rather see a new issue for asking for BC wrench support for 1.11 when BC hits release, how do you think?

**Comment by thiakil** [comment]
Indeed it was the standard, now COFH is it seems. 

It is unlikely that this repo will see much (if any) updates based on discussions in other issues. I'm making great progress on 1.11 in my fork though

**Comment by mindforger** [comment]
yueh just picked up again answering, dunno what was going on in the meantime(peronal reasons most likely)! i will make a new issue then and close this one.
