### ISSUE TITLE
Inventoryhandling with Right-Click

### ISSUE THREAD

**Issue by Hodel1** [AppliedEnergistics/Applied-Energistics-2#2891]
I miss the feature to store one of a item from a stack with a right click to store back to the Me, when i got a stack.

In 1.7.10 were not a problem.

### Environment
Multiplayer, Debian Server, with SpongeForge

- Tested in FTB Beyond 1.5.3
- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-11 (With Spongefix)
- Forge Version: 12.18.3.2254

**Comment by yueh** [comment]
We do not support Sponge officially.

Should you be able to reproduce it without it, please update the issue accordingly and we will reopen it.

**Comment by Bircko** [comment]
Yeah i got same issue in forever stranded.
