### ISSUE TITLE
Open any GUI by search anything when cursor is over a item

### ISSUE THREAD

**Issue by Hodel1** [AppliedEnergistics/Applied-Energistics-2#2892]
When i search anything, i type for example "R" or "U", where i get the helpgui, when my cursor is over a item.

Crafting Terminal is in "Auto-Search" mode.

This was in 1.7.10 not a problem.

### Environment
Multiplayer, Debian Server, with SpongeForge

- Tested in FTB Beyond 1.5.3
- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-11 (With Spongefix)
- Forge Version: 12.18.3.2254

**Comment by CraftMinerKyle** [comment]
Wasn't this similar to an issue that was closed a while ago?

**Comment by mindforger** [comment]
that is total normal r and u are short cuts for NEI mod, the helper gui you see

**Comment by Hodel1** [comment]
i'm really sure, that was no problem on 1.7.10 (FTB Infinity Evolved)

**Comment by yueh** [comment]
Duplicate
