### ISSUE TITLE
Modded MC crashes while in inventory, AE2 seems to be the problem.

### ISSUE THREAD

**Issue by drPimpa** [AppliedEnergistics/Applied-Energistics-2#2893]
#### Description
Currently playing Craft of the Titans (by Boolyman) and it didn't have AE2 which I manually installed and there seems to be an incompatibility issue with one or several other mods. Periodically (doesn't seem to be a specific pattern to it), when either bringing up inventory or while crafting, the game crashes. I find having AE2 extremely essential to gameplay, so if there's a fix to this, I'd be quite grateful. :)

#### Environment
Craft of the Titans modpack v.1.04 by Boolyman. List of mods (incomplete - it has around 150 - but the only list I could find) can be found here:
https://media-elerium.cursecdn.com/attachments/201/998/mod-list.png.
Same problem persists in the newest version of the modpack (1.14).

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-11
- Forge Version: 12.18.3.2281

Crash report: 
https://pastebin.com/PSwaBbH5

**Comment by drPimpa** [comment]
Okay, so I did quite a bit of digging, and found out that deleting the facades.cfg from the AE2 folder solves the problem.

**Comment by mindforger** [comment]
send this hint to the modpack maker, the config files are often distributed with the pack, maybe his one is corrupted! PS you can close the issue yourself, right next to the comment button :D

**Comment by drPimpa** [comment]
AE2 was not part of the modpack, that's why I was sure about that clashing with the pack. When I removed it, everything was fine. Anyway, nice to play without hiccups. Will close the thread soon.

**Comment by CraftMinerKyle** [comment]
Sometimes there are reasons that really cool mods are not added to modpacks...

**Comment by mindforger** [comment]
That is not really a helpful comment Kyle, @drpimpa did you change anything else in the pack after adding AE2 ? sometimes removing mods or inserting new ones can mess up the recipes and comfigs

**Comment by drPimpa** [comment]
I only added AE2, ProjectE and OptiFine. When solving, I tried taking out one by one while putting back the previously removed one, that's how I knew where the problem was. Then I found a thread somewhere deep in the FTB forum that advised to delete said .cfg.

**Comment by mindforger** [comment]
funny, well it helped, you can close this for now :)
