### ISSUE TITLE
ME Interface will not insert materials into the inscriber

### ISSUE THREAD

**Issue by vakkq** [AppliedEnergistics/Applied-Energistics-2#2894]
#### Description

This setup (http://i.imgur.com/ZxJMcan.png) is supposed to produce a processor. The Interface on the right has appropriate patterns in it. The interface on the left is simply a reciever. The Item Conduit on the top has a whitelist wich will only allow printed logic, engineering, and calculation circuits in. The Item Conduit on the right has a whitelist wich will only allow Redstone, meanwhile the Item Conduit on the bottom only allows Printed Silicon. 

I have tested this design in singleplayer and it worked, but now it won't work. I can't load the singleplayer world and compare the differences, because since i have installed the Compact Machines mod i can no longer load or create new singleplayer worlds.

#### Environment

This setup is located inside a "Compact Machines" environment. It is used in a multiplayer world, on a FTB Inventions server, and a modpack of the same name. The server is hosted locally on a Windows Server 2016 machine, and there are two players on the server. CPU is i64.

The same setup (at least as far as i remember) was confirmed working on a singleplayer test world, on the same modpack, without Compact Machines mod.

- Minecraft Version: 1.7.10
- AE2 Version: AE2-RV2-STABLE-10
- Forge Version: 7.99.40.1614 for Minecraft 1.7.10

**Comment by mindforger** [comment]
rv2 is stoneage, try rv3, it's way more stable also 1.7.10 is not supported, hence why i close this

but keep posting if you still have issues

**Comment by vakkq** [comment]
I like the modpack and i want to keep playing it. I cannot update the mod.

**Comment by vakkq** [comment]
It did work before, on singleplayer, on the same modpack, the same version. read my post please.

**Comment by mindforger** [comment]
your issue is, that the interface does not export it's pattern contents to the ender io conduit  ?
