### ISSUE TITLE
not sure if this has been adressed or not ive trying searching for this issue, but when i create a any of the processors for AE2, it doesnt allow me to use restone, just pulseating chipsets. any help plox

### ISSUE THREAD

**Issue by cabellism** [AppliedEnergistics/Applied-Energistics-2#2896]
#### Environment

- Minecraft Version: 1.7.10
- AE2 Version: 0.5.1.9
- Forge Version:  10.13.4.1448

**Comment by mindforger** [comment]
- the AE2 Version you are giving makes no sense, is it rv2 or rv3?
- the headline is not the right place for the error description!
- 1.7.10 is not supported anymore, thus this issue will be closed

but if you give me the right informations and probably 1 or two screenshots of your issue i may can help you
