### ISSUE TITLE
Molecular Assembler annihilates shears when crafting IE copper wires

### ISSUE THREAD

**Issue by TomyLobo** [AppliedEnergistics/Applied-Energistics-2#2897]
When crafting Immersive Engineering's Copper Wires from Copper Plates and Shears in a Molecular Assembler, the (now slightly damaged) Shears are not returned to the system as expected, but disappear altogether.
Interestingly, the alternative recipe using IE wire cutters instead of shears does not suffer the same issue.

#### Description

Test matrix:
- Copper Plate + Shears crafted in a Molecular Assembler, initiated via a Wireless Terminal
    - Expected result: Copper Wire, slightly damaged Shears
    - Actual result: Copper Wire, Shears are annihilated
- Copper Plate + Shears crafted in a Crafting Table
    - Correct result: Copper Wire, slightly damaged Shears
- Copper Plate + Engineer's Wire Cutters crafted in a Molecular Assembler, initiated via a Wireless Terminal
    - Correct result: Copper Wire, slightly damaged Engineer's Wire Cutters
- Copper Plate + Engineer's Wire Cutters crafted in a Crafting Table
    - Correct result: Copper Wire, slightly damaged Engineer's Wire Cutters

#### Environment

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-11 with [unrelated modifications](https://github.com/AppliedEnergistics/Applied-Energistics-2/compare/master...TomyLobo:fix-blocking-mode)
- Forge Version: 12.18.3.2254
- Immersive Engineering Version: 0.10-58-78 from http://ci.blamejared.com/job/ImmersiveEngineering-1.10.2/

**Comment by jarquafelmu** [comment]
This seems to be true for any recipe that returns some of the ingredients as byproducts. I actually just now wondering if there was a proper way to handle this.

**Comment by TomyLobo** [comment]
As stated in my original post, the alternative recipe (copper plate + engineer's wire cutters) works.
And so do all of the pots&pans recipes from pam's harvestcraft that i tried

**Comment by jarquafelmu** [comment]
Oh, I wasn't aware that some recipes do work correctly. That is good to know. I know for a fact that it seems to eat the Yah Hammer or the dies from the Woot mod and I had thought that it ate buckets or pots and pans from pam's harvest craft because it's constantly recrafting those and I can't find them in the network after a crafting job.

**Comment by yueh** [comment]
If tools are destroyed during crafting, that usually means they are not tools at all.

In these cases the mod usually uses their own system to somehow return these items to a player's inventory. But as AE2 pretty much avoids the normal crafting handlers for performance reasons, there is no way for us to catch these cases outside of container items (tools) and iirc 1 or 2 standard forge events.
