### ISSUE TITLE
TPS spike, skipping ticks, freezing 1.10.2 rv4 a 11

### ISSUE THREAD

**Issue by djcprone** [AppliedEnergistics/Applied-Energistics-2#2898]
I saw a post about this from 2014 that was for and discussed numerous older (much older) versions of the mods on older versions of Minecraft so I am opening this in hopes to get info relevant to current versions of both the mod and the game so others having this issue can find the fix as well. 

When you craft something, any type of shaped craftable in a crafting terminal, and you shift click to craft stacks at a time, the more you make the more you break, so to speak. One stack might lag you by a few seconds, but shift click 4 times and the server freezes completely for about 30 seconds, and command window shows 300-800+ ticks skipped. Can recreate always. Never had this issue in my 1.7.10 server and I used to go nuts crafting stacks from resource crops essence ^^

I'm using most recent version, rv4alpha11 on minecraft 1.10.2 in modpack ATM1 via curse.

No crashlog, it just locks up and goes normal after it catches up.

I noticed in my year of playing in my last server on 1.7.10, when you shift clicked to craft a stack, you could see it throw a stack of 64 into your inventory instantly. Now, you can sometimes see it actually put 1 in your inventory and watch the number count the whole way up to 64, just really quickly. Did you change the way that this operation is handled - or does 1.10.2 require something to be done differently? Because that change in behavior could be the source of the lag that never used to exist. (Just a thought, I'm not a developer lol)

- Minecraft Version: 1.10.2
- AE2 Version: rv4 alpha 11
- Forge Version: 12.18.3.2254

**Comment by mindforger** [comment]
do you use any quantom storage or compacting drawers? there are some issues with the forge capability system and these storage are very hard to handle code wise.

is ist really a freeze or does the ME system just not keeping up and serving you with items? that could easily be a power issue, make sure to have enough energy cells present to buffer the power peaks by those requests. input mean NOTHING if oyur buffer is too small :)
