### ISSUE TITLE
Redstone dupe bug w/ Me Interface & Formation plane

### ISSUE THREAD

**Issue by TestamentDoom** [AppliedEnergistics/Applied-Energistics-2#2900]
#### Description

Redstone does not get removed from the ME Interface inventory when outputted into the world through an ME formation plane. I tried other items like diamond or emerald, but they work as normal. Was only able to get this to work with just redstone.

This means infinite redstone for daaayyysss, at an extremely fast rate.

You just need an ME network consisting of 1 Interface and 1 Formation plane. Of course you need to power the network as well.

Once that's set up, just insert your redstone into the Interface and the dupe is complete. Infinite shower of redstone.

Again, with other items like diamond or emerald, it behaves normally, removing the item from the Interface when it gets put out into the world through the formation plane. Just seems to work with redstone from what I've found, where the count never decreases from the ME Interface as it gets outputted into the world through the formation plane.

#### Environment
I was able to reproduce this bug in any local SP world, but I'm sure this will work anywhere.
I found this on FTB Beyond. This pack also includes AE2 Stuff, but I never used any of their blocks
to cause this bug.

- Pack used: FTB Beyond 1.5.3
- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-11
- Forge Version: 12.18.3.2254

**Comment by CraftMinerKyle** [comment]
AE2 Stuff is very glitchy, even if you haven't placed anything down in the world. Placing the Wireless Receiver block crashes the game, and opening some interfaces causes extreme lag spikes, even with non-AE2 interfaces. IDK why, but try reproducing this issue without AE2 Stuff, and see what the difference is. It seems that the interface is not removing the items from the system correctly. Ask the DEV's what might be causing that, as I just know that AE2 Stuff is a garbage 3rd party addon.

**Comment by mindforger** [comment]
That is a known AE2 bug indeed

**Comment by mindforger** [comment]
ARt Stuff i mean sorry

**Comment by CraftMinerKyle** [comment]
Yeah, whenever I used AE2 Stuff, my average FPS was 10, and looking at modded ores caused FPS to be like 1/2. Linked it to AE2 Stuff, and everything that was made of copper was also the same effect. AE2 Stuff is trash. Sorry to the DEV's of AE2 Stuff!

**Comment by francisgendreau** [comment]
This also happen using any inventory and import bus as long there are no storage attached to the network. The import bus will remove from the inventory any item until it reaches redstone dust. Once it touches redstone, a single dust get placed into the first slot of the inventory and the glitch occurs. 

Last tested in appliedenergistics-rv4-alpha-11

**Comment by mindforger** [comment]
@francisgendreau please check if you have ae2stuff installed, if you do, remove it and try to reproduce or else report it to ae2stuff.

this is as far as i know NOt an ae2 issue, but ae2 stuff addon mod

**Comment by UncleOwen** [comment]
Hi,

I also ran into this issue, and decided to play around without a bit. It is not related to ae2stuff. Instead, I managed to reproduce it with just

- Minecraft 1.10.2
- Forge 1.10.2-12.18.3.2422
- Applied Energistics 2 rv4-stable-1
- Flux Networks 1.10.2-1.2.5
- SonarCore 1.10.2-3.2.8 (dependency of Flux Networks)

Guess I'll file a bug with Flux Networks.

**Comment by mindforger** [comment]
thank you for further investigation in this case

**Comment by TFenby** [comment]
This bug still exists in FTB Revelations 2.0.0, which does not include AE2 Stuff. Can this be re-opened?

**Comment by mindforger** [comment]
@TFenby this issue is 1year old and about 1.10, if it happens in a recent version make a new issue please and include the details requested. Naming only the modpack is not enough.

**Comment by GuntherDW** [comment]
@mindforger The Flux networks dev has reintroduced the bug in a semi-recent commit sadly.
https://github.com/SonarSonic/Flux-Networks/commit/3b914a6ae9055be04ee83e455366dc0ab7e608cb

But yeah, It might be better to open a new bug report?

**Comment by TFenby** [comment]
Already opened a ticket over at flux net.
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3563
https://github.com/SonarSonic/Flux-Networks/issues/239
