### ISSUE TITLE
AE2 processor recipes.

### ISSUE THREAD

**Issue by cabellism** [AppliedEnergistics/Applied-Energistics-2#2901]
ok here is my issue, im currently playing on project ozone 2 reloaded, not 100% sure if it is normal, titan, or kappa. when i try to make the logic processors, calculation processors, and engineering processors the recipe all requires a pulsating chip-set from EnderIO in stead of red stone, every video i've seen uses red stone, ever recipe i have seen uses red stone, etc. i have no idea what is going on to be honest. any help would be grateful on this issue, not sure if i need to enable something/disable something, update or downgrade. just any help at all would be great, and im hoping  this time it doesnt get closed out before i get any help. 
im currently playing on a SMP server from scalacube, i believe everything is up to date. 

Here is two screen shots. 

![2017-05-04_23 29 05](https://cloud.githubusercontent.com/assets/28294258/25732874/10562c40-3122-11e7-8577-18e7af0677d8.png)
![2017-05-04_23 29 12](https://cloud.githubusercontent.com/assets/28294258/25732873/105587cc-3122-11e7-8beb-e9264a0abf22.png)

#### Environment

- Minecraft Version:  1.70.10
- AE2 Version: rv3-beta-6 --- the one that came with the modpack, unsure if i should be using this one or not and how to change it i have no idea
- Forge Version: 10.13.4.1614

**Comment by mindforger** [comment]
well the modpack maker decided to make recipes harder and modified the recipes of AE2, but i honestly have no idea how to do that, maybe @yueh can give you a hint

one thing upfront, don't be sad, the issue will then most likely be closed because of 1.7.10 beeing unsupported

**Comment by cabellism** [comment]
just really confused and alittle frustrated to be honest, i like project ozone 2, first real modpack ive tried, made it pretty far in the game. just trying to figure out what the heck is going on compared to every other recipe and video i have found out on this... it makes no since really. unless im using a older/ newer version of everything ive seen on AE2. i love the mod, and want to support it cause it is pretty neat and really great.

**Comment by mindforger** [comment]
as i said it is the modpack maker who decided to fuck with the recipes to make you progress across all mods in this packt to finish your buildings. there is sense behind his edits with no doubt but i personally also do not like to be forced to progress across different mods just to accomplish siple products. 
you should concider to either not play this particular modpack or contact the pack-creator to ask him for help and making you an easier version ... which i thing pretty sure will be denied
look at it as a challenge: download and install curseclient and build your own modpack, it is very easy and you can share your "profile" easily with friends without uploading hundreds of megabytes and asking mod devs for permission all day long

PS closed for 1.7.10 reason

**Comment by cabellism** [comment]
No need to be a douche, what did I do to piss you off. I hope you close each and every 1.7.10 version thread on here. All I was doing is asking for small amount of help from people that know more about this game and how the inner workings work. Ok the first issue I posted yeah, it needed to come down yes, wrong format, wrong info, etc. I thought with this one it appease you o great and mighty mindforger. I guess I'll follow your advice and suck it up

**Comment by mindforger** [comment]
> No need to be a douche, what did I do to piss you off. I hope you close each and every 1.7.10 version thread on here

indeed i do, i told you earlier that 1.7.10 is not supported anymore hence the close ... i also told you not to worry about that fact, you will still get helped as long as someone can

also i gave you an answer and what you have to do ... i assume you just rageresponded a bit ... no hard feelings from here and i hope neither from you anymore

**Comment by cabellism** [comment]
Yes I'll admit I rage responded, it did come across a bit crass but after given it some thought, after the fact on how I responded, being a admin/dev? For a popular mod for a very popular game, with a metric sh&+ ton of players I can understand pressure and the type of attitude you need for this gig. Similar to a project manager to a international company.... <--- 
For my ragery I am sorry, no hard feelings. For my current predicament I can say fuck it give, wish, roll a d20, etc me the pulsating chip sets, or learn how to edit a recipe to correct it the way the wiki and videos show the recipe as.

**Comment by vallard192** [comment]
@cabellism it looks like you're probably playing PO2 in Titan mode.  Almost all the recipes are going to be different/tweaked in some way.  The best thing to do is probably to search "AE2 Project Ozone 2 Titan" on youtube and find peoples let's play series on how they do it.  I found this video which shows him using a pulsating chipset to make a processor:
https://www.youtube.com/watch?v=joh0FWEba6Y

**Comment by cabellism** [comment]
That's the thing, the first thing I done was type in the command for normal mode,/ftb_mode set normal, I'm new to any of these mod packs, and modded MC in general. Hell no I'm not going to start it off on kappa or Titan mode, I am not a masochist.
