### ISSUE TITLE
Server Crash on startup

### ISSUE THREAD

**Issue by Whazaaaaa** [AppliedEnergistics/Applied-Energistics-2#2903]
#### Description
My server crashes on startup with very little crash-logs. I'm hoping someone can help me solve the issue.
Ae2 has been great so far but I didnt expect this random crash.
This crash happens right after the server is fully started.

I cant really reproduce the issue this just happend out of nowhere and im hoping for a quick edit in a file or whatever that can fix this.

#### Environment

CRASHLOG: https://pastebin.com/LDjwu292
most system info can also be found in here.

- Minecraft Version: 1.10.2
- AE2 Version: appliedenergistics2-rv4-alpha-11
- Forge Version: FTBserver-1.10.2-12.18.3.2254-universal (2254)
- Sponge Version: spongeforge-1.10.2-2281-5.2.0-BETA-2303
- Modpack: AllTheMods 2.54b
- Multiplayer (players go from 5 to 20 at a time) so its quite populated

**Comment by mindforger** [comment]
hm ... this corrupted block thing is becoming viral somewhow, this is at least the third issue with a case of an wrong blockaccess @yueh 
funny difference this time it is not an access to a non-existent creative energy cell this time it's a slab

**Comment by Whazaaaaa** [comment]
Is there a way to find out in what chunk or whatever it was? So I can remove it and fix the problem?

**Comment by mindforger** [comment]
from the crash i suppose either somewhere around the controller or any point where ME parts meet with slabs, no coordinates, maybe  AE2 can hook into that particular exception and create a bit debug output as the 4th one is almost predefined to happen

**Comment by Ommina** [comment]
I see no logging of the position.

I presume you have multiple crash reports by now.  Do they all (around or at line 71) read the same "BlockStateContainer{block=tconstruct:seared_slab, properties=[half, type]}"?

It's a bit perplexing, as immediately before the error, it checks to ensure the tile is, in fact a Controller.

**Comment by Whazaaaaa** [comment]
All crash report are identical

**Comment by mindforger** [comment]
well it COULD be that sponge is interfering here, all checks may fail if sponge does some sort of recycling at the very wrong moment (talking about concurrent modifications of some sort)

check your logfile if somebody joined the game **all the time right before the crash**, you could possibly reduce the terrain by 9 chunks around his login coordinates then
also make a flyover around all known ME structures and try to pin it down this way (you may need to modify you coordinates in the savegame if you are unable to join)

if it is utterly random happening you can try to run a copy of the server without sponge

**Comment by Whazaaaaa** [comment]
Thing is the server crashes without any player being online.

**Comment by mindforger** [comment]
that supports my theorey of sponge interference ... as so called ghost loading can cause such issues ... it can also be foamfix ... very hard to say

**Comment by Whazaaaaa** [comment]
The server sorta timed out and I did see some foamfix log before I restarted the server. but that log is probably long gone since it only saves the last 4. Now trying without sponge tho

**Comment by Whazaaaaa** [comment]
Seems that removing sponge has 'solved' the problem. What can I do now? Find the place and remove it?

**Comment by Whazaaaaa** [comment]
So I can join the game properly without spongeforge. But I need to find the spot that is causing this. Would I be correct to think that I would need to find a seared stone slab?

**Comment by mindforger** [comment]
try to disable "optimizations" in the sponge config, but thanks for clearing this up, sponge seems to recycle chunkdata and causing such a mess probably ... but i am only guessing!

**Comment by Whazaaaaa** [comment]
Turned off optimizations without any luck :(
Here is the crash from the log itself
https://pastebin.com/b0Gu0ht0
Its probably the same but who knows

**Comment by Whazaaaaa** [comment]
Would it be an idea to either remove ae2 of tinkers construct from the world?

**Comment by mindforger** [comment]
would be interesting to know if that solves it permanently
i would guess it will crash again but with another block ... maybe not instantly

**Comment by Ommina** [comment]
That said, if it is some weirdness through Sponge, there may not be anything actually corrupt in the world.

Are you able & willing to make a world download available (the 'will crash' version).  I wouldn't mind spending a bit of time tracking down the actual position of the (allegedly) broken block.

**Comment by Whazaaaaa** [comment]
@Ommina https://whazaaaaa.stackstorage.com/s/DiySJUcrcc1XqWL
This is the worldfolder from before I went into the world without sponge. Perhaps you can still find issues ^^

**Comment by HadenOverlord** [comment]
I was having the same issue but for me, the issue occurred when I reset my world I got it to work again by downgrading my Ae2 version to alpha-9.

**Comment by HadenOverlord** [comment]
nv it still doesn't work it is definitely a sponge issue because the server works fine without sponge

**Comment by Idesmi** [comment]
I am having the same issue on the same version.

[fml-junk-earlystartup.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1050270/fml-junk-earlystartup.txt)
[fml-server-latest.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1050271/fml-server-latest.txt)

**Comment by mindforger** [comment]
@Idesmi well it is not good to hear you have the same problem, but the more important, did you try the same steps? or did you just skip the issue and post to it ? :)

**Comment by yueh** [comment]
We do not support Sponge officially.

Should you be able to reproduce it without it, please update the issue accordingly and we will reopen it.
