### ISSUE TITLE
Server crash on join

### ISSUE THREAD

**Issue by TomyLobo** [AppliedEnergistics/Applied-Energistics-2#2906]
Our server now crashes every time I join.
As long as I don't join, the server stays up, as soon as i do, the following crash happens:
https://pastebin.com/XesnQUtT

~What can I do (including hotfixes - I can build the source) in order to get the map working again?~
The map is working again, but I think the issue is worth looking into.
I do not possess the background knowledge to do so, as this is deep within the belly of AE.

What we changed since it last worked:
* We now use a lot of AE's own dense cables, as opposed to enderio dense ME conduits
* We moved most of our ME network into an rftools dimension, attached via tunnels through a quantum ring

#### Environment

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-11 with [unrelated modifications](https://github.com/AppliedEnergistics/Applied-Energistics-2/compare/master...TomyLobo:fix-blocking-mode)
- Forge Version: 12.18.3.2254
- EnderIO Version: 1.10.2-3.1.180

**Comment by mindforger** [comment]
can you reproduce this with the original mod? also try to remove foamfix for testing, concurrent modification exceptions are hard to deal with and as you are already using a modified version you are the only one who can reproduce it

**Comment by TomyLobo** [comment]
like i said, the modifications are unrelated. click the link to see for yourself.
That said, I'm currently taking the easy (but potentially laggy) way out:

````
List<IGridNode> nodeList = new ArrayList<IGridNode>();
for( final IGridNode obj : g.getMachines( subscriber.getKey() ) )
{
	nodeList.add(obj);
}
for( final IGridNode obj : nodeList )
{
	x++;
	target.invoke( obj.getMachine(), e );
}
````

I don't yet know if it works, wish me luck.

**Comment by CraftMinerKyle** [comment]
Could there be a corrupt player file somewhere? Lemmie check your attached files and double check your errors.

**Comment by CraftMinerKyle** [comment]
Do you have something AE2 Related in your inventory? Try making a backup of your player files and delete the server's copy. Then rejoin. Sometimes that is all it takes.

**Comment by TomyLobo** [comment]
I applied my fix and now it works again, no player file shenanigans needed.
I did make a backup of the broken world though, in case someone wants to debug through it.

**Comment by CraftMinerKyle** [comment]
If you are finished, please close the thread. Thank you and have fun!

**Comment by TomyLobo** [comment]
Yeah if all I cared about was my server, that would make sense.

**Comment by CraftMinerKyle** [comment]
It's a thread on an issue, right? Well anyway, no matter. What is done is done.

**Comment by yueh** [comment]
There is no crash log. But based on the code snippet: If there is a crash around that point, it pretty much means something does something very stupid like multithreaded chunkloading or similar. Nothing we can actually fix. Sure you can choose to ignore it. But it is up to you, if you want to risk of a corrupted world.

**Comment by TomyLobo** [comment]
On May 9th there was a crash log there. not my fault you take 2 months to actually look at this.
I probably can't even repaste it, since that server is currently being taken down.
I'll see what I can do.
