### ISSUE TITLE
Autocrafting using ore dict supports even when disabled

### ISSUE THREAD

**Issue by dieselfuelonly** [AppliedEnergistics/Applied-Energistics-2#2907]
#### Description

https://www.reddit.com/r/feedthebeast/comments/6a28nb/ae2_autocrafting_issue_bug_or_am_i_doing/

From the video linked in the Reddit post I made asking for help, it looks like cables being crafted are using regular Fluix Crystals instead of Pure Fluix Crystals as it should.  Substitutions are disabled in the pattern settings.  

#### Environment

*AE2 rv3 beta 6
*Revolution|3 1.7.10 pack - SMP
*Known AE2 addons - ae2stuff-rv3-0.5.1.9-mc1.7.10, ExtraCells-1.7.10-2.3.14b197, thaumicenergistics-1.0.0.5, immersiveintegration-0.6.8

- Minecraft Version:  1.7.10
- AE2 Version:  appliedenergistics2-rv3-beta-6
- Forge Version:  forge-1.7.10-10.13.4.1614-1.7.10-universal

**Comment by yueh** [comment]
We no longer support 1.7.10 at this point.

Should you be able to confirm that this issue still apply to the most recent version, please update the issue and we will reopen it.
