### ISSUE TITLE
Strange Channel Behavior (Bug?)

### ISSUE THREAD

**Issue by congochicken** [AppliedEnergistics/Applied-Energistics-2#2908]
This is either a bug, or I'm making a mistake somewhere. Either way, I'd love some support on this, because it's driving me crazy. 

My channels aren't distributing correctly across cables, causing a limit of 8 channels even when I use dense cable. 

<img width="1440" alt="screen shot 2017-05-11 at 2 44 36 pm" src="https://cloud.githubusercontent.com/assets/20884252/25973531/579f4122-3659-11e7-9ed6-5674f69ac5c0.png">

<img width="1440" alt="screen shot 2017-05-11 at 2 44 55 pm" src="https://cloud.githubusercontent.com/assets/20884252/25973672/edf2888c-3659-11e7-8feb-8c6c91f6997a.png">

<img width="1440" alt="screen shot 2017-05-11 at 2 45 01 pm" src="https://cloud.githubusercontent.com/assets/20884252/25973673/ee306f6c-3659-11e7-91e2-dde85e235431.png">

Below that central dense cable is a p2p bus, which is linked directly to a blank controller face (image 1). Both sides of the dense cable are showing 8 channels, despite the fact that there are only 4 interfaces attached to each side (images 2 & 3).

My initial thought was that I had made an inefficient path for the channels to flow through, so I attached the exact same setup directly to a controller as a test. As you can see below, this (strangely) fixed the issue, meaning (I think) that it isn't an issue with routing. 

<img width="1440" alt="screen shot 2017-05-11 at 2 45 38 pm" src="https://cloud.githubusercontent.com/assets/20884252/25973783/6bea4040-365a-11e7-83e9-fc84fca6ee95.png">

Next, I thought the issue might be related to the complexity of my network as a whole, so I created a separate network JUST for these eight channels, using a p2p tunnel. The problem persisted, as is visible in the screenshots below.

<img width="1440" alt="screen shot 2017-05-11 at 2 47 24 pm" src="https://cloud.githubusercontent.com/assets/20884252/25973819/a62c9b18-365a-11e7-80b0-f80df78ec386.png">

<img width="1440" alt="screen shot 2017-05-11 at 2 47 31 pm" src="https://cloud.githubusercontent.com/assets/20884252/25973824/a9ada944-365a-11e7-815e-7f66c07267ba.png">

Anyone have a clue what's going wrong? At this point, I think there's either a bug, or I'm making an error that I don't understand. 

Thanks for the help,
Congochicken

- Minecraft Version: 1.7.10
- AE2 Version: (rv2-stable-10)
- Forge Version: 7.10.99.99

**Comment by mindforger** [comment]
you say the main cable is routed through a p2p, this looks like the p2p is not connected! having 8 channels lit up mneans no controller present ... and placin a controller directly on the cable fixing your issue just proevs the p2p not to be working

how did you connect the p2p (crouch + right a memory card click on the first p2p and then right click on the second)  ?

**Comment by CraftMinerKyle** [comment]
Can I just state that I see an orange Smart Cable limiting the usage of the Dense Cables?

**Comment by VT-14** [comment]
@CraftMinerKyle that Orange cable is connected to an Energy acceptor by what I think it a Quartz Fiber cable (visible in the picture 4), so no channels pass through it.  It is only lit up because that entire network is an ad-hock system (no controller found) and is using 8 channels (clearly visible by every single smart cable being completely lit up rather than having channels trace back to the controller).

I think mindforger hit the nail on the head; something is probably wrong with the P2P setup here.

**Comment by CraftMinerKyle** [comment]
I couldn't see it. Sorry for the false information.

**Comment by congochicken** [comment]
Thanks for the responses @mindforger @CraftMinerKyle @VT-14 
@mindforger the p2p is definitely corrected to a controller directly, yes, that's how I did it. I'm fairly sure that this is actually a bug, I can't find any good reason that this should be happening.

**Comment by congochicken** [comment]
Turns out this is entirely my fault and not a bug - I'll just delete my account now. Thanks for helping everyone!

**Comment by CraftMinerKyle** [comment]
Can you please tell me what you found out was the REAL issue? I just want to know because I'm curious.
