### ISSUE TITLE
Some bugs of condenser

### ISSUE THREAD

**Issue by xsun2001** [AppliedEnergistics/Applied-Energistics-2#2910]
There are some bugs of the condensers. One of them were reported to my 1.7.10 version. But in my test, those bugs still exist in the newest 1.10.2 version. I will give you the demo video later.
https://github.com/xsun2001/Applied-Energistics-2-Unofficial/issues/7

#### Description

1. The number of item that condenser crafts required can be changed in sever config file, but it cannot display in client.
2. The crafted item cannot display in the slot until a mouse click.

#### Environment

- Minecraft Version: 1.10.2 MP
- AE2 Version: rv4-alpha-11
- Forge Version: 1.10.2-12.18.3.2185

**Comment by xsun2001** [comment]
https://giphy.com/gifs/3o7buhRwKlCc0cpFi8

https://giphy.com/gifs/l4FGAyyFDeanRRdHq

**Comment by CraftMinerKyle** [comment]
I unfortunately cannot view your GIF's on my school network, but are you saying that the Matter Condenser is not showing the Singularity, when it should have been made, until after you roll your mouse over them, or that only the mouse shows the text that says "Singularity".

**Comment by mindforger** [comment]
>The number of item that condenser crafts required can be changed in sever config file, but it cannot display in client.

so you are telling that the client behaves different when server and client config are not the same? well you should hand out your friends a copy of the server config then, as far as i know configs do not get synced in any way

**Comment by xsun2001** [comment]
> I hate my poor English. I hate the GFW.

I changed the number of items it requires in server to 1,and client exactly craft one singularity use one items,but it still displays 256000 in its tips. I am sorry to explain it unclearly,but I hope you can try to understand me. You can try it yourself.

**Comment by CraftMinerKyle** [comment]
I'm pretty sure that you don't need to sync client and server configs for that, as the server gives the client the information on that. But syncing to prevent errors is always a good practice. What server build/type are you running? I know that the configs are in different locations on each server. Are you running SpongeForge?

**Comment by xsun2001** [comment]
@CraftMinerKyle No, there is only an original Forge server with only AE2.
The client is supposed to sync its number in the craft instruction, which will display when you mouse on the mode-changing button. Or it will make players confused. The client can craft the singularity currently but it is wrong that only in its display.

**Comment by yueh** [comment]
If you want that the client syncs the config with the server, than this is a feature request for forge. Not something every mod has to reinvent themselves.
