### ISSUE TITLE
[1.10.2] Airblock crash every 30min

### ISSUE THREAD

**Issue by YOYOK9** [AppliedEnergistics/Applied-Energistics-2#2911]
After updating forge and sponge my server was fine for a few days now all of a sudden it crashes every 30min or so. The report is talking about crafting with an air block which doesn't make much sense but it refers to appeng... Apologize that there isn't much details since I'm not fully sure what is happening. 

This is on a 1.10.2 multiplayer server. We are using sponge but with the sponge bootstrap and have had no issues till now. 
https://pastebin.com/teSDk22v

- Minecraft Version: 1.10.2 
- AE2 Version: appliedenergistics2-rv4-alpha-11
- Forge Version: forge-1.10.2-12.18.3.2281-universal
- Sponge: 1.10.2-2281-5.2.0-BETA-2330

**Comment by Ommina** [comment]
Try it without Sponge.

Yes, I know that isn't the response that you wanted to hear.  Yes, I know it's been running just great until now.  Just the same, we've seen a number of reports of weird crashing behaviour (see #2903, for example), and they go away with the removal of Sponge.  Even though all appearances are that they have been working just great together, possibly for weeks.

**Comment by YOYOK9** [comment]
So I removed sponge and it looks like it may have stopped crashing. However I have noticed when I am around any ae2 blocks my fps drops like crazy. Any thing I can do for this? it is really breaking my server. If I remove sponge I loose all the perms and protections my players have. but if i remove ae2 some players lose all their stuff

**Comment by yueh** [comment]
We do not support Sponge officially.

Should you be able to reproduce it without it, please update the issue accordingly and we will reopen it.
