### ISSUE TITLE
Logic processors won't autocraft

### ISSUE THREAD

**Issue by fireworrks** [AppliedEnergistics/Applied-Energistics-2#2913]
#### Description
Using AE2 in the FTB beyond pack I am in an RFTOOLS dimension. I have a properly setup auto processor inscriber but it will not make logic processors. It can make both calculation and engineering but refuses to place an logic circuit into the top of the press. 

- Minecraft Version: 1.10.2
- AE2 Version: 1.10.2
- Forge Version: 12.18.3.2254

**Comment by Monerfone** [comment]
There's a simple & cheap method in a  [tutorial on youtube](https://www.youtube.com/watch?v=e_isR_UfnDE&index=9&list=PLOWJFCNCQEFiagrr4xj_4S8tNEyPzA2Wk)

**Comment by mindforger** [comment]
@fireworrks can you include a picture of your setup and the GUI while trying to craft? your descrioption is not enough, also make a forced crashlog by pressing ansd holding f3 + c until you crash and post it via pastebin or as attachement, but please do not "wall of text" it :D
with that crashlog we can see what other mods you have installed

**Comment by fireworrks** [comment]
Hi @mindforger It's exactly as you would expect, and it works in the overworld but once i'm inside an rftool dimension it doesn't work

**Comment by fireworrks** [comment]
I fixed the issue. Turns out I'm DUMB there was a duplicate logic processor pattern stored in a regular interface next to a molecular assembler. It was trying to craft it manually without using a press.

Sorry for your time.

Thanks
