### ISSUE TITLE
AE2 and InventoryTweaks 1.10.2 crash issue?

### ISSUE THREAD

**Issue by cyris69** [AppliedEnergistics/Applied-Energistics-2#2914]
#### Description

NEI/JEI Show issues: https://imgur.com/a/Ef1F4
When crafting any AE2 item game crashes with InventoryTweaks error so trying to contact both parties of issue.
#### Environment

Used in MP, no errors in console, logs, or FML just crashlog
Crash Log: https://gist.github.com/cyris69/658618935e65e581af0c125cf91d5158
Other Mods: https://gist.github.com/cyris69/484944c6ff24bd02855a6b6476b284be
Libs/APIs: https://gist.github.com/cyris69/f31375966c9a310095477c9c1d954e5b

- Minecraft Version:  1.10.2
- AE2 Version:  appliedenergistics2-rv4-alpha-11
- Forge Version:  2281
- SpongeForge Version: spongeforge-1.10.2-2281-5.2.0-BETA-2322

**Comment by mgdgfbhevdyeh** [comment]
try delete SpongeForge.
now I think AE isn't support it.

**Comment by mindforger** [comment]
like said, can you reproduce this without spongeforge? this is a strange one tbh

what were you crafting or does it not depend?
