### ISSUE TITLE
add a way to automate the dire crafting table from avataria

### ISSUE THREAD

**Issue by coehlrich** [AppliedEnergistics/Applied-Energistics-2#2915]
#### Description
since avataria has a 9x9 crafting table and a neutronium compressor that can have recipes like 43884 emerald blocks (although the only thing left in the 1.10 port is the 9x9 crafting table it would still be helpful) it can require a lot of crafting and the pattern encoder can only do up to 3x3

#### Environment
i have mainly noticed that this isnt there is the project ozone 2 pack

- Minecraft Version: 1.7.10 
- AE2 Version: rv3-beta-6
- Forge Version: 10.13.4.1614
(although i am using a outdated version i had a look at the source code and only found a max of 9 slots for the pattern encoder)

**Comment by chorman0773** [comment]
This could be done using a custom mod, If you have programming skills.

**Comment by yueh** [comment]
No. Grids larger than 3x3 are usually used to prevent autocrafting. This would just cause them to get larger and larger.

**Comment by coehlrich** [comment]
the qed from extra utilities doesn't allow autocrafting just fine and avaritia addons actually has a autocrafting table just for the dire crafting table.

**Comment by ThatCynicalX** [comment]
@chorman0773, how can one accomplish this?

**Comment by chorman0773** [comment]
@ThatCynicalX depends on exactly what kind of thing you want to accomplish. If you want a work around, you could probably create a custom ae2 peripheral, that can do autocrafting with >9 items and a special type of pattern for that terminal, then get ae2 to recognize it as an autocrafting target. If you want more integration, say using the basic interface, rather then coding your own autocrafting target peripheral, I could not say exactly how to do it. Though I saw etho do a really fantastic "No Coding Required" Work arround, but it needs Tinkers Construct as well. Though you could probably figure a way to implement it without it.
