### ISSUE TITLE
MC Crash

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [AppliedEnergistics/Applied-Energistics-2#2916]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TatwCore (TATW-1.10.2-1.0.0.0.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  IC2core (industrialcraft-2-2.6.210-ex110.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.2-anarchy.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  AppEngCore (appliedenergistics2-rv4-alpha-11.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.8.255-universal.jar)
  CorePlugin (MrTJPCore-1.10.2-2.0.0.17-universal.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 17-5-20 下午7:57
Description: Unexpected error

java.lang.IllegalStateException: Already building!
	at net.minecraft.client.renderer.VertexBuffer.func_181668_a(VertexBuffer.java:291)
	at net.minecraft.client.shader.Framebuffer.func_178038_a(Framebuffer.java:264)
	at net.minecraft.client.shader.Framebuffer.func_147615_c(Framebuffer.java:229)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1103)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.VertexBuffer.func_181668_a(VertexBuffer.java:291)
	at net.minecraft.client.shader.Framebuffer.func_178038_a(Framebuffer.java:264)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Hawaii'/93, l='MpServer', x=1297.89, y=4.00, z=1914.89]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (1294,4,1927), Chunk: (at 14,0,7 in 80,120; contains blocks 1280,0,1920 to 1295,255,1935), Region: (2,3; contains chunks 64,96 to 95,127, blocks 1024,0,1536 to 1535,255,2047)
	Level time: 1247 game time, 6000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 21 total; [EntitySlime['史莱姆'/69, l='MpServer', x=1340.13, y=4.67, z=1918.58], EntitySheep['羊'/70, l='MpServer', x=1339.22, y=4.00, z=1983.68], EntityHorse['马'/75, l='MpServer', x=1375.50, y=4.00, z=1876.50], EntitySlime['史莱姆'/76, l='MpServer', x=1369.18, y=5.08, z=1947.35], EntitySlime['史莱姆'/77, l='MpServer', x=1368.41, y=5.08, z=1952.51], EntityPig['猪'/78, l='MpServer', x=1374.50, y=4.00, z=1957.50], EntitySlime['史莱姆'/47, l='MpServer', x=1284.39, y=4.33, z=1847.97], EntityPig['猪'/79, l='MpServer', x=1373.50, y=4.00, z=1956.50], EntityPlayerSP['Hawaii'/93, l='MpServer', x=1297.89, y=4.00, z=1914.89], EntityPig['猪'/80, l='MpServer', x=1370.50, y=4.00, z=1952.50], EntitySlime['史莱姆'/49, l='MpServer', x=1287.33, y=4.00, z=1860.68], EntityPig['猪'/81, l='MpServer', x=1373.50, y=4.00, z=1952.50], EntityHorse['马'/50, l='MpServer', x=1285.57, y=4.00, z=1894.92], EntitySlime['史莱姆'/58, l='MpServer', x=1324.39, y=4.33, z=1850.85], EntitySlime['史莱姆'/59, l='MpServer', x=1334.72, y=4.33, z=1879.90], EntitySheep['羊'/28, l='MpServer', x=1223.50, y=4.00, z=1951.50], EntityPig['猪'/60, l='MpServer', x=1326.50, y=4.00, z=1982.50], EntityPig['猪'/61, l='MpServer', x=1323.50, y=4.00, z=1986.50], EntitySheep['羊'/30, l='MpServer', x=1232.26, y=4.00, z=1955.47], EntityPig['猪'/62, l='MpServer', x=1324.50, y=4.00, z=1985.50], EntitySheep['羊'/31, l='MpServer', x=1221.50, y=4.00, z=1952.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:498)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 552454296 bytes (526 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2281 Optifine OptiFine_1.10.2_HD_U_C3 35 mods loaded, 35 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2281.jar) 
	UCHIJAAAA	Forge{12.18.3.2281} [Minecraft Forge] (forge-1.10.2-12.18.3.2281.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv4-alpha-11} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.1.2.jar) 
	UCHIJAAAA	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.8.255-universal.jar) 
	UCHIJAAAA	appliedenergistics2{rv4-alpha-11} [Applied Energistics 2] (appliedenergistics2-rv4-alpha-11.jar) 
	UCHIJAAAA	Aroma1997CoreHelper{1.1.1.2} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.1.2.jar) 
	UCHIJAAAA	CodeChickenLib{2.5.8.255} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.8.255-universal.jar) 
	UCHIJAAAA	CodeChickenCore{2.4.1.103} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.1.103-universal.jar) 
	UCHIJAAAA	eleccore{1.7.420} [ElecCore] (ElecCore-1.10.2-1.7.420.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.66-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.66-beta.jar) 
	UCHIJAAAA	EnderIO{1.10.2-3.1.190} [Ender IO] (EnderIO-1.10.2-3.1.190.jar) 
	UCHIJAAAA	EnderStorage{2.2.1.106} [EnderStorage] (EnderStorage-1.10.2-2.2.1.106-universal.jar) 
	UCHIJAAAA	foamfix{@VERSION@} [FoamFix] (foamfix-0.6.2-anarchy.jar) 
	UCHIJAAAA	forgemultipartcbe{2.0.0.31} [Forge Multipart CBE] (ForgeMultipart-1.10.2-2.0.0.31-universal.jar) 
	UCHIJAAAA	microblockcbe{2.0.0.31} [Forge Microblocks] (ForgeMultipart-1.10.2-2.0.0.31-universal.jar) 
	UCHIJAAAA	minecraftmultipartcbe{2.0.0.31} [Minecraft Multipart Plugin] (ForgeMultipart-1.10.2-2.0.0.31-universal.jar) 
	UCHIJAAAA	immersiveengineering{0.10-58} [Immersive Engineering] (ImmersiveEngineering-0.10-58.jar) 
	UCHIJAAAA	IC2{2.6.210-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.210-ex110.jar) 
	UCHIJAAAA	MrTJPCoreMod{2.0.0.17} [MrTJPCore] (MrTJPCore-1.10.2-2.0.0.17-universal.jar) 
	UCHIJAAAA	projectred-core{4.8.2.41} [ProjectRed Core] (ProjectRed-1.10.2-4.8.2.41-Base.jar) 
	UCHIJAAAA	projectred-integration{4.8.2.41} [ProjectRed integration] (ProjectRed-1.10.2-4.8.2.41-integration.jar) 
	UCHIJAAAA	projectred-transmission{4.8.2.41} [ProjectRed Transmission] (ProjectRed-1.10.2-4.8.2.41-integration.jar) 
	UCHIJAAAA	projectred-fabrication{4.8.2.41} [ProjectRed Fabrication] (ProjectRed-1.10.2-4.8.2.41-fabrication.jar) 
	UCHIJAAAA	projectred-illumination{4.8.2.41} [ProjectRed Illumination] (ProjectRed-1.10.2-4.8.2.41-lighting.jar) 
	UCHIJAAAA	projectred-expansion{4.8.2.41} [ProjectRed Expansion] (ProjectRed-1.10.2-4.8.2.41-mechanical.jar) 
	UCHIJAAAA	projectred-transportation{4.8.2.41} [ProjectRed Transportation] (ProjectRed-1.10.2-4.8.2.41-mechanical.jar) 
	UCHIJAAAA	projectred-exploration{4.8.2.41} [ProjectRed Exploration] (ProjectRed-1.10.2-4.8.2.41-world.jar) 
	UCHIJAAAA	rftools{6.01} [RFTools] (rftools-1.1x-6.01.jar) 
	UCHIJAAAA	rftoolscontrol{1.6.8} [RFTools Control] (rftoolsctrl-1.1x-1.6.8.jar) 
	UCHIJAAAA	rftoolsdim{4.55} [RFTools Dimensions] (rftoolsdim-1.1x-4.55.jar) 
	UCHIJAAAA	tatw{1.0} [TATW] (TATW-1.10.2-1.0.0.0.jar) 
	UCHIJAAAA	Translocator{2.1.4.55} [Translocator] (Translocators-1.10.2-2.1.4.55-universal.jar) 
	Loaded coremods (and transformers): 
TatwCore (TATW-1.10.2-1.0.0.0.jar)
  
CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  
IC2core (industrialcraft-2-2.6.210-ex110.jar)
  
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.2-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
AppEngCore (appliedenergistics2-rv4-alpha-11.jar)
  appeng.coremod.transformer.ASMIntegration
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.8.255-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
CorePlugin (MrTJPCore-1.10.2-2.0.0.17-universal.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.4.0' Renderer: 'GeForce GT 610/PCIe/SSE2'
	AE2 Version: alpha rv4-alpha-11 for Forge 12.18.3.2185
	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/F:/Minecraft我的世界/.minecraft/versions/1.10.2-forge1.10.2-12.18.3.2281/mods/TATW-1.10.2-1.0.0.0.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/F:/Minecraft我的世界/.minecraft/versions/1.10.2-forge1.10.2-12.18.3.2281/mods/TATW-1.10.2-1.0.0.0.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/F:/Minecraft我的世界/.minecraft/versions/1.10.2-forge1.10.2-12.18.3.2281/mods/TATW-1.10.2-1.0.0.0.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/F:/Minecraft我的世界/.minecraft/versions/1.10.2-forge1.10.2-12.18.3.2281/mods/TATW-1.10.2-1.0.0.0.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/F:/Minecraft我的世界/.minecraft/versions/1.10.2-forge1.10.2-12.18.3.2281/mods/TATW-1.10.2-1.0.0.0.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/F:/Minecraft我的世界/.minecraft/versions/1.10.2-forge1.10.2-12.18.3.2281/mods/TATW-1.10.2-1.0.0.0.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/F:/Minecraft我的世界/.minecraft/versions/1.10.2-forge1.10.2-12.18.3.2281/mods/TATW-1.10.2-1.0.0.0.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/F:/Minecraft我的世界/.minecraft/versions/1.10.2-forge1.10.2-12.18.3.2281/mods/TATW-1.10.2-1.0.0.0.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/F:/Minecraft我的世界/.minecraft/versions/1.10.2-forge1.10.2-12.18.3.2281/mods/TATW-1.10.2-1.0.0.0.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash. Scroll up!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	EnderStorage Invalid Fingerprint Reports: 
	Translocator Invalid Fingerprint Reports: 
	AE2 Integration: IC2:ON, RC:OFF, RF:OFF, RFItem:OFF, MFR:OFF, Waila:OFF, InvTweaks:OFF, JEI:OFF, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF
	Launched Version: HMCL 2.7.6.25
	LWJGL: 2.9.4
	OpenGL: GeForce GT 610/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Pentium(R) CPU G3250 @ 3.20GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_C3
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0
	OpenGlRenderer: GeForce GT 610/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 2

**Comment by mgdgfbhevdyeh** [comment]
I click on the AE create the label to crash

**Comment by mindforger** [comment]
you have a rendering issue, not sure what it sources from
first, please use pastebin to post the crashlog or attach the crashlog as file for better readability of your issue
second, please try the following things:
increase your memory settings (-Xmx1024m using only 1GB RAM seems a very few memory, maybe causing this)
remove optifine, sometimes rendering issues are cause by optimizations from optifine
same for foamfix, try reproduce the issue without

**Comment by mgdgfbhevdyeh** [comment]
arrive i come back
this problem is form foamfix
@asiekierka

**Comment by asiekierka** [comment]
https://github.com/asiekierka/FoamFix/issues/54

**Comment by mgdgfbhevdyeh** [comment]
arrive of my use new Optifine or use Foamfix lanful,it should work
