### ISSUE TITLE
Autocraft bug with certain items

### ISSUE THREAD

**Issue by MPeti1** [AppliedEnergistics/Applied-Energistics-2#2918]
#### Description
It is happening with the the most recent version. (rv2-stable-10)
I placed crafting patterns with the needed recipes to an interface at a molecular assembler to craft the circuits of railcraft (controller, receiver and signal circuit). If i start crafting 10 about any of the mentioned, the system only crafts some of it (for example only 6, but it can be just 4 or 9). If this happens, if i open the crafting processor which ran the crafting process, i see the crafting queue stopped. (so nothing is changing, even the number of the remaining items of the last item in the queue (the circuits), and if i look in the molecular assembler which are needed to craft it, it has no item in it, even the progress bar is on 0. If i cancel the crafting queue in the processor and start it again, i can craft again A FEW of the items, then it will stop again.

#### Environment

Relevant details:
- The items needed for any of the circuits are not removed from the storage system when they are needed for crafting
- The system is not being disassembled even for a tick while the crafting is running
- The system can craft other items as expected, the bug only happens with the circuits mentioned (as i emember)
- version: rv2-stable-10
- Single player
- other mods and their version: [asd.pdf](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1033684/asd.pdf)
- crashlogs: no crash happened, and the mod doesn't write any information to console when this bug happens

Minecraft Version: 1.7.10
AE2 Version: rv2-stable-10
Forge Version: 10.13.4.1614

**Comment by mindforger** [comment]
rv2 is heravily outdated, please switch to rv3 and try to reproduce
also check if you have enough space left for the results
and check if you have enough energy buffer (aka energy cells) in your system

**Comment by MPeti1** [comment]
ok, thanks.
i have enough space for results, and also my power generation is stable.

**Comment by MPeti1** [comment]
Now i needed to revert back to rv2 because AE2 Stuff mod by BDew has some compatibility issues with the beta release, so now i cant say if the rv3 release is working fine. When AE2 Stuff gets updated, i will be back :D

**Comment by Ommina** [comment]
An update to ae2stuff seems unlikely to happen, although it is certainly not my place to speak for bdew.

That said, there are builds of AE2Stuff for rv3 of 1.7.10 -- try the newest of them.

**Comment by mindforger** [comment]
There is a compatibility mod for that bdew issue. Power Generation means nothing without buffer throw in a few energy cells.

**Comment by MPeti1** [comment]
yesterday i've seen in the mod's description on mods.cusre.com there is a version for rv3, but i've not found it in the downloads list.

**Comment by MPeti1** [comment]
the bug is still existing in rv3-beta-6. Railcraft circuit crafting still stops at a random* point for some reason

*the crafting stops always at the same item, but for some time it can craft it, as in the latest rv2 version.

**Comment by mindforger** [comment]
you did not answer my question about the energy cells, power can possibly spike out the internal buffer and the network resets

**Comment by MPeti1** [comment]
I will try it, but this bug only occurs when it comes to railcraft circuit crafting, which not requires any other machines than the molecular assembler chamber, an interface on it, and the crafting cpu. by the way i have an energy cell (by enderio) on my power grid, but i think you meant to place some energy cell from ae2

**Comment by mindforger** [comment]
Yeah i mean exactly those and the molecular assembler only powers from the internal buffer of the me network, any other external machine will use external power... So logical i guess, when using the molecular assembler, it could possibly suffer from a too small buffer in your me network

**Comment by yueh** [comment]
We no longer support 1.7.10 at this point.

Should you be able to confirm that this issue still apply to the most recent version, please update the issue and we will reopen it.
