### ISSUE TITLE
[1.7.10] Startup Crash

### ISSUE THREAD

**Issue by Zsashas** [AppliedEnergistics/Applied-Energistics-2#2919]
#### Description

Crashes on startup with the linked crash report. This did not happen until I updated DragonAPI, Chromaticraft, and Geostrata, and disabled Sky Stone chiselling in the Chisel config (got a different crash from that).

I know 1.7.10 is outdated, I don't expect a fix, just would like to know how I can fix this on my end, or what I have to disable, etc. Disabling Tiny TNT in the config does nothing.

Crash Report: https://hastebin.com/ilifosolax.sql

#### Environment

- Minecraft Version: 1.7.10 
- AE2 Version: RV2 Stable 10
- Thaumic Energistics Version: 1.0.0.5 RV2
- Forge Version: 1614

**Comment by Zsashas** [comment]
Before disabling chiselling for Sky Stone in the chisel config, this was the crash I got: https://hastebin.com/abulelexik.swift

Again, only happened after updating those three of Reika's mods.

**Comment by mindforger** [comment]
Try out rv3 it is far more stable. Also try to reset the config for facades.. Can not remember if it were already present in 1.7

**Comment by Zsashas** [comment]
Well, I was using RV2 because I also have Thaumic Energistics and RV3 was crashing with that.

Is it facades that's causing the issue? I never use those anyway...

**Comment by xsun2001** [comment]
By the way, rv3 and thaumic energistics will not crash with my fix https://github.com/xsun2001/Applied-Energistics-2-Unofficial. TE used rv2 api and caused the crash. And the dragon Api..... It changed to many things in original Minecraft and caused a lot of mistakes and crashes. Such as a display error #2902 .  And I cannot get a version that can be used in the develop environmen. I am trying to fix those issues. But it is really difficult as Reika do those thing so unusual......

**Comment by yueh** [comment]
We no longer support 1.7.10 at this point.

Should you be able to confirm that this issue still apply to the most recent version, please update the issue and we will reopen it.

**Comment by Zsashas** [comment]
I know 1.7.10 is unsupported, I just wanted to know if there was anything on my end to fix the issue, or at least know what was causing it.

**Comment by yueh** [comment]
Do not use DragonAPI or Thaumic Tinkerer or request them to stop shipping our API.

**Comment by Zsashas** [comment]
Is it possible to manually remove it? Dragonapi updates rarely, and TT isnt updating at all anymore, so shouldn't have to be done too often.
