### ISSUE TITLE
Light Rendering BUG

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [AppliedEnergistics/Applied-Energistics-2#2920]
Rendering Bug:
Note the direction(Facing)
![2017-05-28_12 20 50](https://cloud.githubusercontent.com/assets/20567492/26526259/7a439a10-43a7-11e7-88dc-b215f71fd897.png)
![2017-05-28_12 27 50](https://cloud.githubusercontent.com/assets/20567492/26526258/7a3e1496-43a7-11e7-8dd8-eec552e18efa.png)
![2017-05-28_12 28 03](https://cloud.githubusercontent.com/assets/20567492/26526263/7a75b310-43a7-11e7-98b8-ebdcf706bd0c.png)
![2017-05-28_12 28 22](https://cloud.githubusercontent.com/assets/20567492/26526261/7a52a578-43a7-11e7-903d-fc65ae89a253.png)
![2017-05-28_12 28 41](https://cloud.githubusercontent.com/assets/20567492/26526260/7a518e4a-43a7-11e7-8034-b7e5e95d0fb0.png)

**BuG**

Minecraft Version: 1.10.2
AE2 Version: rv4-alpha-11
Forge Version: 12.18.3.2281

Edit: sorry for my English

**Comment by GuntherDW** [comment]
Can you try it out without optifine and check to see if the issue still occurs?

I have the feeling that Optifine causes this issue.

The other "request" (you had 1 "bug" and 2 requests) where you can't just JEI the items for a pattern is a deliberate gameplay element. Not an oversight.

**Comment by mgdgfbhevdyeh** [comment]
looks it isn't optifine BUG

**Comment by mindforger** [comment]
>looks it isn't optifine BUG

those look familiar, also removed foamfix and other "optimizing" mods?

**Comment by mgdgfbhevdyeh** [comment]
@mindforger that's isn't foamfix BUG.I tried to remove it but the BUG still exists
And i try 1.7.10,NEI support ghost items,but I try 1.10.2,JEI isn't support ghost items

(Sorry for my English)

**Comment by mindforger** [comment]
i am not sure on this, but i can remember the request to allow virtual or ghost items for pattern got already rejected 
for the lighting issue, i am out of ideas

can you go into your game, press and hold F3 + C to force a crash and attach the resulting crashlog as file or via pastebin please? i think this issue needs more details!

**Comment by mgdgfbhevdyeh** [comment]
@mindforger You do not encounter this problem?

**Comment by mindforger** [comment]
Press and hold, at least 6 seconds while ingame, not titlescreen, sorry i was not clear enough on that

**Comment by mgdgfbhevdyeh** [comment]
[crash-2017-06-02_20.55.39-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1047702/crash-2017-06-02_20.55.39-client.txt)

**Comment by mgdgfbhevdyeh** [comment]
![2017-07-03_20 36 16](https://user-images.githubusercontent.com/20567492/27812834-6428530a-60a4-11e7-85ce-5ff2a7c9c864.png)

**Comment by mindforger** [comment]
sorry, that one slipped my mind

can you reproduce this without optifine and withoput foamfix? both do changes to rendering and maybe are causing this

**Comment by mgdgfbhevdyeh** [comment]
ok i I try again,sorry,yes,it's optifine things

**Comment by mgdgfbhevdyeh** [comment]
i will try foamfix

**Comment by mgdgfbhevdyeh** [comment]
ok it's just optifine things

**Comment by mindforger** [comment]
you can hit the close button if this issue shifts over to optifine or continue here if there is assitance required from optifine :)

**Comment by mgdgfbhevdyeh** [comment]
why closed?

**Comment by mindforger** [comment]
Because it is not AE fault, but i tend to leave them open for feedback unlike yueh :)
