### ISSUE TITLE
[1.7.10] 

### ISSUE THREAD

**Issue by Felixfex** [AppliedEnergistics/Applied-Energistics-2#2921]
It's a Simple Problem!
If you have Autocrafting System build and your Terminal is in the Chunk 0/0 (Coordinates 0 0 to 15 15)
You can't tell the System to craft the automated items because the Window which should pop up throws you out of the terminal.

In both MP and SP, this problem occurs.
Does not happen to wireless crafting terminal even if the Acces point and Security Terminal is in the chunk.

To Replicate:
- Build a system in Chunk 0/0
- Build Autocrafting
- Make a Pattern
- Let the System craft it

Stats of The Game:
- Modpack Project Ozone 2 Reloaded - Kappa Mode
- Minecraft Version: 1.7.10
- AE2 Version: rv3 -beta6
- Forge Version: 10.13.4.1614

I hope i could Help you to fix the problem :D

**Comment by mindforger** [comment]
press and hold f3 + c to force a crash and attach the resulting crashlog as file or upload it to pastebin and post the link

AE2 Version 1.7.10 is not maintained anymore, but with the required informations we could make out something

i am sure AE2Stuff is present, can you reproduce this without ae2stuff installed?

**Comment by Felixfex** [comment]
Sooo I had time to test which mods have influenced this Bug. I came to the following mods:
- Botania Garden od Glass
- Wireless Crafting Terminal (mod)
- AE2

The problem only happens in the garden of glass Dimension
With the other given factors in the Main post

For Extra info here is the crash log like you ordered :D

https://pastebin.com/Z6BDRTz8

**Comment by mindforger** [comment]
GoG having influence on AE2 is a new one, but if removing the wireless crafting terminal mod helps, i would suggest to report it over there linking to this issue, maybe a reason can be found that way

also did you make sure to isntall at least 1 single energy cell jsut in case (to counter an very common answer, NO it is not enough to have infinite power input, the system can only handle as much buffer it actually has per tick, except using a creative energy cell :P )

**Comment by Ommina** [comment]
Given that it is only happening in chunk 0,0 -- perhaps some sort of spawn protection?

I admit I'm grasping.

**Comment by mindforger** [comment]
so do i, but spawn protection only should work when "someone" is "op" and the default spawn afaik is not chunk 0
it would be interesting to test if this is present in 1.9+

**Comment by Felixfex** [comment]
Nah Spawn Protection is not enabled (and it even happens in Singleplayer)
and it happen ONLY in the garden of glass dim

**Comment by Felixfex** [comment]
And i did use a complete system with energy cell

**Comment by yueh** [comment]
We no longer support 1.7.10 at this point.

Should you be able to confirm that this issue still apply to the most recent version, please update the issue and we will reopen it.
