### ISSUE TITLE
Hopper extracts items from crafting cpu

### ISSUE THREAD

**Issue by bothie** [AppliedEnergistics/Applied-Energistics-2#2922]
Setup: Full ME system with exactly one crafting cpu composed of exactly one 64k crafting storage and nothing else, placed somewhere with a hopper beneath (didn't plan on that but didn't expect a problem either).

What happened: The Hopper actually extracted items from the crafting cpu rendering the crafting impossible. I can't really believe this to be intended behavior, so reporting it here.

- FTB Infinity Evolved Skyblock v 1.2.0
- Minecraft Version: 1.7.10
- AE2 Version: appliedenergistics2-rv3-beta-6.jar
- Forge Version: 7.99.40.1614

**Comment by yueh** [comment]
We no longer support 1.7.10 at this point.

Should you be able to confirm that this issue still apply to the most recent version, please update the issue and we will reopen it.
