### ISSUE TITLE
[Request]Some useful features

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [AppliedEnergistics/Applied-Energistics-2#2923]
![2017-06-03_10 20 01](https://cloud.githubusercontent.com/assets/20567492/26749945/d1950d3e-4849-11e7-8687-1bb7663219f7.png)
![2017-06-03_10 20 08](https://cloud.githubusercontent.com/assets/20567492/26749946/d197d3d4-4849-11e7-8137-7208836b86f9.png)
no need Fuzzy Card,can be set directly
I think this is more convenient
and more useful
![2017-06-03_10 14 51](https://cloud.githubusercontent.com/assets/20567492/26749978/608f3ab4-484a-11e7-9f62-1c982ccd19c8.png)
Destructor Fortune(or Silk Touch) update
Some magic Mod's automation needs it!

![2017-06-03_10 21 59](https://cloud.githubusercontent.com/assets/20567492/26749994/b954e0fe-484a-11e7-8421-9312db0bb669.png)
![2017-06-03_10 22 15](https://cloud.githubusercontent.com/assets/20567492/26749993/b921c5c0-484a-11e7-98eb-1c1edacb6340.png)
![2017-06-03_10 22 24](https://cloud.githubusercontent.com/assets/20567492/26749995/b956a556-484a-11e7-93cb-cfd39e1e4785.png)
inv/network no item but can make Pattern with JEI
and can use JEI fast make Processing Pattern
I think this is very useful when doing large automation projects
![2017-06-03_10 20 40](https://cloud.githubusercontent.com/assets/20567492/26750086/a0363a6c-484c-11e7-9aec-df1128145b8a.png)
stack update

**Comment by MPeti1** [comment]
this is AE2's github page, not Refined Storage ;)
