### ISSUE TITLE
rv4.alpha build 11 no recipe for Quartz Glass, bug

### ISSUE THREAD

**Issue by Cbert** [AppliedEnergistics/Applied-Energistics-2#2924]
No recipe for Quartz Glass, and no recipe for Quartz Grindstone. SP and MP
#### Description
![2017-06-09 01 27 03](https://user-images.githubusercontent.com/9320867/26953527-8aaeb960-4cb3-11e7-820c-89f1287c3905.png)
![2017-06-09 01 26 24](https://user-images.githubusercontent.com/9320867/26953528-8ab0348e-4cb3-11e7-9205-af29e3d797e2.png)

#### Environment
<details>
  <summary>Mods - Click to expand</summary>

> ActuallyAdditions-1.10.2-r105
> AdvancedInventoryManagement-1.10.2-1.2.0
> ae2stuff-0.6.0.9-mc1.10.2
> analyzeio-1.10.2-0.3.3.22
> Kl_AppleSkin-mc1.10.2-1.0.5
> appliedenergistics2-rv4-alpha-11
> bib_Aroma1997Core-1.9.4-1.1.1.2
> bib_AutoRegLib-1.0-2
> bib_base-1.10.2-1.4.0
> Baubles-1.10.2-1.3.11
> BaublesHud-1.10.2-3.2.0
> bib_bdlib-1.12.4.24-mc1.10.2
> BetterBuildersWands-1.10.2-0.11.1.220+f8232fe
> bib_Forgelin-1.4.2
> bib_MCMultiPart-1.4.0-universal
> bib_Bookshelf-1.10.2-1.4.4.347
> bib_BrandonsCore-1.10.2-2.1.7.102-universal
> Chameleon-1.10.2-2.3.0
> ChestTransporter-1.10.2-2.5.17
> ChickenChunks-1.10.2-2.2.0.52-universal
> Kl_1.10-chunkedgeindicator-1.3
> Kl-clarity-1.0
> ClockHUD-1.10.2-1.3.2
> Clumps-1.0.5
> bib_CodeChickenCore-1.10.2-2.4.1.102-universal
> bib_CodeChickenLib-1.10.2-2.5.8.255-universal
> bib_CoFHCore-1.10.2-4.1.1.156-universal
> bib_compatlayer-1.10-0.2.9
> CookingForBlockheads_1.10.2-4.2.43
> corail_pillar-2.0.0-1.10.2
> creeperconfetti-1.2.1
> DarkUtilities-1.1.8.finalrc1
> deepresonance-1.1x-1.4.8
> Draconic-Evolution-1.10.2-2.0.12.222-universal
> bib_ElecCore-1.10.2-1.7.421
> ElevatorMod[V.1.3.0][MC.1.10.2]
> EnchantingPlus-1.10.2-4.1.0.115
> EnderIO-1.10.2-3.1.183
> bib_EnderCore-1.10.2-0.4.1.66-beta
> EnderStorage-1.10.2-2.2.1.106-universal
> etpmod-1.10.2
> Unified Stone-1.0A mc 1.10.2
> expandedbonemeal-1.11-1.0.1
> extrautils2-1.10.2-1.4.1
> FastLeafDecay-v11
> foamfix-0.6.2-anarchy
> bib_ForgeMultipart-1.10.2-2.0.0.31-universal
> GraveStone Mod 1.5.12
> Improving Minecraft-1.12.1
> Kl_InventoryTweaks-1.61-58
> ironchest-1.10.2-7.0.15.804
> kl_journeymap-1.10.2-5.4.6
> Kl_jei_1.10.2-3.14.7.419
> Kl_JustEnoughResources-1.10.2-0.5.8.98
> Kl_BetterFps-1.4.4-1.10
> Kl_jehc-1.2.1
> KleeSlabs_1.10.2-3.3.5
> LunatriusCore-1.10.2-1.1.2.38-universal
> kl_MacroKey-1.10.2-1.1.6.1
> bib_Mantle-1.10.2-1.1.5
> bib_mcjtylib-1.1x-2.3.11
> Mekanism-1.10.2-9.2.2.301
> MekanismGenerators-1.10.2-9.2.2.301
> MekanismTools-1.10.2-9.2.2.301
> CraftTweaker-1.10.2-3.0.24
> MmmMmmMmmMmm-1.10.2-1.13
> moartinkers-0.4.1
> ModLister-1.10.2-2.1.8
> Morpheus-1.10.2-3.1.13
> Kl_MouseTweaks-2.8-mc1.10.2
> MyCommands-1.9.4-1.10.2-02
> natura-1.10.2-4.1.0.65
> NaturesCompass-1.10.2-1.3.0
> netherportalfix-mc1.9.4-4.0.1
> notenoughwands-1.1x-1.5.5
> OfflineSkins-1.10.2-v2a
> bib_omlib-1.10.2-3.0.0-101
> openmodularturrets-1.10.2-3.0.0-158
> OreExcavation-1.2.93
> Pam's HarvestCraft 1.9.4-1.10.2h
> PrimordialCrops-v1.7g_mc1.9.4
> Quark-r1.1-70
> rangedpumps-0.3
> rftools-1.1x-6.01
> Schematica-1.10.2-1.7.8.153-universal
> SimpleTcon-2.0
> bib_simplecore-1.10.2-1.4.5.1
> SleepTron-1.10.2-0.1.0
> SpartanShields-1.10.2-1.3
> spikemod-1.10.2-1.2.1
> StorageDrawers-1.10.2-3.7.8
> SuperCircuitMaker-1.0.4
> ThermalExpansion-1.10.2-5.0.4.90-universal
> ThermalFoundation-1.10.2-2.0.5.81-universal
> Tinkers' Addons-1.10.x-1.0.5
> TConstruct-1.10.2-2.6.5
> TinkerToolLeveling-1.10.2-1.0.1
> Uncrafted 1.10.2 (v.2.2.0a)
> Kl_Hwyla-1.8.13-B27_1.10.2
> Kl_WailaHarvestability-mc1.10.2-1.1.9
> Kl_WAILAPlugins-MC1.10.2-0.3.0-26
> WaterStrainer-1.9.4-1.3.2
> WR-CBE-1.10.2-2.0.0.18-universal

</details>
<details>
  <summary>latest.log - Click to expand</summary>

> [01:02:13] [Client thread/INFO]: Starting AE2 CSV Export
> [01:02:13] [AE2 CSV Export/INFO]: Cache is enabled. Checking for new mod configurations.
> [01:02:13] [AE2 CSV Export/INFO]: Same mod configuration was found. Not updating CSV content.
> [01:02:13] [Client thread/WARN]: Recipe Error 'Invalid crafting type: grindfz' near line:1 in processing/factorization.recipe with: [ae2:material.FluixCrystal, ->, ae2:material.FluixDust]
> [01:02:13] [Client thread/WARN]: Recipe Error 'Invalid crafting type: grindfz' near line:2 in processing/factorization.recipe with: [ae2:sky_stone_block:0, ->, ae2:material.SkyDust]
> [01:02:13] [Client thread/WARN]: Recipe Error 'Invalid crafting type: grindfz' near line:4 in processing/factorization.recipe with: [mc:ender_pearl, ->, ae2:material.EnderDust]
> [01:02:13] [Client thread/WARN]: Recipe Error 'Invalid crafting type: grindfz' near line:5 in processing/factorization.recipe with: [ae2:material.CertusQuartzCrystalCharged, ->, ae2:material.CertusQuartzDust]
> [01:02:13] [Client thread/WARN]: Recipe Error 'Invalid crafting type: grindfz' near line:7 in processing/factorization.recipe with: [ae2:material.CertusQuartzCrystal, ->, ae2:material.CertusQuartzDust]
> [01:02:13] [Client thread/WARN]: Recipe Error 'Invalid crafting type: grindfz' near line:8 in processing/factorization.recipe with: [ae2:quartz_ore, ->, 2, ae2:material.CertusQuartzDust]
> [01:02:13] [Client thread/WARN]: Recipe Error 'Invalid crafting type: grindfz' near line:9 in processing/factorization.recipe with: [ae2:charged_quartz_ore, ->, 2, ae2:material.CertusQuartzDust]
> [01:02:14] [Client thread/WARN]: Unable to register a recipe:Unable to find item: appliedenergistics2:material.Flour:0
> [01:02:14] [Client thread/WARN]: Unable to register a recipe:Unable to find item: appliedenergistics2:material.Flour:0
> [01:02:14] [Client thread/WARN]: Unable to register a recipe:Unable to find item: appliedenergistics2:material.Flour:0
> [01:02:14] [Client thread/WARN]: Unable to register a recipe:Unable to find item: appliedenergistics2:material.GoldDust:0
> [01:02:14] [Client thread/WARN]: Unable to register a recipe:Unable to find item: appliedenergistics2:material.IronDust:0
> [01:02:14] [Client thread/WARN]: Unable to register a recipe:Unable to find item: appliedenergistics2:material.Flour:0
> [01:02:14] [Client thread/WARN]: Unable to register a recipe:Unable to find item: appliedenergistics2:material.Silicon:0
> [01:02:14] [Client thread/WARN]: Unable to register a recipe:Unable to find item: appliedenergistics2:material.Silicon:0

</details>

- Minecraft Version: 1.10.2
- AE2 Version: rv4.alpha build 11
- Forge Version: 12.18.3.2281

**Comment by mindforger** [comment]
is this the only mod installed? if not provide a FULL  or make a forced crashlog by pressing and holding F3 + C for at least 6 seconds while ingame

**Comment by Ommina** [comment]
Given the tooltip for the Quartz Grindstone features the word "Disabled", I can't help but be suspicious that a CraftTweaker script has made some changes as part of whatever pack you're using.

**Comment by mindforger** [comment]
wow okay call me blind i did not notice that, maybe it has been disabled in the AE2 config for good ... i suspect the OP is using a modpack ...

**Comment by Cbert** [comment]
**Ommina**, correct advice, this was CraftTweaker-1.10.2-3.0.24. Thank you.
Didn't think to check scripts folder, sorry.

**Comment by Cbert** [comment]
Please delete this issue.

**Comment by TheJulianJES** [comment]
You can close it yourself.
