### ISSUE TITLE
Wireless Crafting Terminal dosn't function

### ISSUE THREAD

**Issue by Stigma67** [AppliedEnergistics/Applied-Energistics-2#2926]
I have installed Applied Energistics wit the Crafting Terminal addon.
While starting Minecraft it occurs an Error ( shown in the Picture), where the log says
that the AE2 Wireless Crafting Terminal requires another mod to be available.

latest.log: https://pastebin.com/PZfH2PTE

![fehlermeldung](https://user-images.githubusercontent.com/29356566/27012597-03a35aa8-4ed3-11e7-9ae7-a0eb618c12e6.png)

- Minecraft Version: 1.7.10
- AE2 Version: rv3 - beta6
- Forge Version: 10.13.4.1614

**Comment by mindforger** [comment]
that is the ae2wct Addon asking for other mods, not ae2
