### ISSUE TITLE
Wireless Terminal emptying DE Flux Capacitors

### ISSUE THREAD

**Issue by Lukas45** [AppliedEnergistics/Applied-Energistics-2#2928]
#### Description
The Wireless Termincal accepts infinte energy from the Wyvern/Draconic Flux Capacitors, and can empty a 640mil RF Flux Capacitor in about a second.
brandon3055/Draconic-Evolution#781

#### Environment

Seen in Enigmatica 3.07a modpack (MP) and others.
Tested and reproducible in a SP instance with only Applied Energistics 2, Brandon's Core, CodeChickenLib,  Draconic Evolution and JEI.

Reproduction steps:
- Get a Wireless Terminal (Empty or Full, doesn't matter)
- Get a full Flux Capacitor (either Wyvern or Draconic, upgrades doesn't matter)
- Set Flux Capacitor to Charge Held Items / Charge Held Items and Armor
- Have Wireless Terminal as held item
- Watch the Flux Capacitor empty in about a second

Mod versions:
- Minecraft Version: 1.10.2
- AE2 Version: rv4.alpha11
- Forge Version: 12.18.3.2221
- Brandon's Core: 2.18.104 / 2.1.8.107 (tested in both)
- Draconic Evolution 2.1.0.232
- Code Chicken Lib: 2.5.9.267
- JEI: 3.14.7.420

**Comment by mindforger** [comment]
Duplicate https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2768
has been fixed but not released yet, but you can try the fix and compile it yourself for the time beeing

**Comment by Lukas45** [comment]
Hmm, 5 months ago though.
Would there be an ETA on an update, or is that out of sights? Seeing how the fix would have to be applied to a public modpack, and I'm not sure how that works and so on :]

**Comment by mindforger** [comment]
there is another question already going on the update status, i have no insight on this but i think they are just working hard on some major internal refactoring as there have been quiet some issues that called for rework

**Comment by cha0s** [comment]
This is still happening in All The Mods 3 on 1.12.2.

**Comment by fscan** [comment]
Cannot reproduce .. i just tested it with the newest All The Mods 3. This specific issue has been fixed for about 9 months on our end.
