### ISSUE TITLE
crash on startup 1.11.2

### ISSUE THREAD

**Issue by frookey** [AppliedEnergistics/Applied-Energistics-2#2932]
Crash on startup 1.11.2

Game crashes with Applied Energistics in the mod folder

minecraft crashes on startup

- Minecraft Version: 1.11.2
- AE2 Version: 2
- Forge Version: newest

**Comment by mgdgfbhevdyeh** [comment]
hello
now AE isn't update to 1.11.2
AE Team is so busy now.
