### ISSUE TITLE
user custom recipes do not overwrite generated in 1.10

### ISSUE THREAD

**Issue by falizure** [AppliedEnergistics/Applied-Energistics-2#2936]
Basically i am trying to disable the recipe that inscribers have for copying presses, however in the 1.10 theirs no options to do this directly so working backwards threw the mod i determined the best course of action would be to make the recipe prohibitably expensive, reading the readme inside the configs and following that what i did is i copied the presses.recipe from generation and moved it into user and then modified it from 
inscribe=
    oredictionary:blockIron ae2:material.LogicProcessorPress
    -> ae2:material.LogicProcessorPress
to
inscribe=
    draconicevolution:draconic_block ae2:material.LogicProcessorPress
    -> ae2:material.LogicProcessorPress

from my understanding how it works that should make it take a awakened draconium block from draconic evolution instead of a iron block to copy.

when loading up the game it completely ignores the presses.recipe in the user folder and goes straight to the generation which is the opposite of how it describes its functionality to work.

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-11
- Forge Version: 1.10.2-12.18.3.2281-universal

i have a extensive list of other mods installed but none that "should" interfere with recipes except, craftteaker, modtweaker and lootteaker (which i might add no longer has ae2 support in 1.10 in the first place) i can provide the full list if necissary.

**Comment by bookerthegeek** [comment]
IIRC their is a config option also you need to change to use the custom recipies.

**Comment by falizure** [comment]
right from the readme from within the configs "you can modify the recipes by copying over the recipes from generated-recipes into user-recipes you do not need to copy over all the files but the ones you will be changing. AE2 will prefer loading a user recipe if one would replace a generated recipe. That way changed recipes by us are not overwriting your modified files" this is exactly what i have done i took the generated file presses.recipe from materials and generated and copied it into user folder instead of generated folder and made my changes there as shown above.

**Comment by Ommina** [comment]
I expect the setting to which @bookerthegeek  is referring is _B:CustomRecipes=false_ in AppliedEnergistics2.cfg.  While I can't claim to have tried it, did you set this to true?

**Comment by falizure** [comment]
i just found the config you are talking about and it is true, it is true by default.

**Comment by falizure** [comment]
anyone else got any ideas? a dev preferably.

**Comment by flyingmoose** [comment]
I can confirm the same issue at least

**Comment by yueh** [comment]
Cannot reproduce it.

There is also the option that the other recipe mods simply purge all of our ones and replace them with their own recipes.

Otherwise we need more details. Like the full server/client logs. It might also be important, if you use a non english OS and if the path to your minecraft instances contains anything other than alphanumeric chars.
