### ISSUE TITLE
not sure if bug or config setting

### ISSUE THREAD

**Issue by Mikecolle** [AppliedEnergistics/Applied-Energistics-2#2937]
Spatial IO only works with vanilla blocks? is there a way to use it with modded blocks?

**Comment by mindforger** [comment]
in the past there were contributors adapting those blocks

**Comment by Mikecolle** [comment]
is there anyone working on this yet? or is it practically abandonware? wanted to set up spatial io rooms for all the different mods

**Comment by mindforger** [comment]
That would not work in 1.7.10 even, too much individual Block mechanics to make all mods compatible, but you could create the rooms empty and use some other teleporting mod to enter them and build stuff inside

**Comment by mindforger** [comment]
Take an Rftools teleport plus some Energy equipment Stand inside the pylons and set it up when in the spatial dim

**Comment by Mikecolle** [comment]
mainly looking for vector plates and cursed earth
i want to do a 1.11 mod map like the material energy ^4 map and pack

**Comment by yueh** [comment]
#1455
