### ISSUE TITLE
new version is bad (i am talkin about AE2)

### ISSUE THREAD

**Issue by Ld01337** [AppliedEnergistics/Applied-Energistics-2#2938]
the new version of applied energistics is not so far as good as the AE1

#### Description
AE1 was so much better simpler and easier to understand
automatization was also much simpler like ore processing(enrich-smelt),all farms-just hooked precision import busses set to stack mode and connected to the network with one cable and now are needed dense cables and bullshit like colored cables etc.
and controller was simply just one block and i didnt need to build a multiblock structure

And one simple question why the awesome super duper ultimate storage system was completely ruined
and was created AE2 it is basically the same thing that happened to old equivalent exchange 2 but problem of that mod was clear(because creating diamonds from nothing and tools were really OP). and i dont know whats OP on storage :( . even my classmates and people i asked think the same thing - 
AE2 is BAD
but the idea about storing items on hard drive and basically building a server is briliiant and original
![the good old system](https://user-images.githubusercontent.com/29714555/27555980-10416722-5ab4-11e7-8e2f-3bf90b1d7559.png)
#### Environment
AE2 controller sometimes sets on fire itself (tekkit legends) XD

- Minecraft Version: would use newer but there is no AE1
- AE2 Version: AE1
- Forge Version: IDK

**Comment by Ld01337** [comment]
why was AE 1 recreated and this bullshit was born ?

**Comment by Ld01337** [comment]
<!-- the new version of applied energistics is not so far as good as the AE1

#### Description
AE1 was so much better simpler and easier to understand
automatization was also much simpler like ore processing(enrich-smelt),all farms-just hooked precision import busses set to stack mode and connected to the network with one cable and now are needed dense cables and bullshit like colored cables etc.
and controller was simply just one block and i didnt need to build a multiblock structure

And one simple question why the awesome super duper ultimate storage system was completely ruined
and was created AE2 it is basically the same thing that happened to old equivalent exchange 2 but problem of that mod was clear(because creating diamonds from nothing and tools were really OP). and i dont know whats OP on storage :( . even my classmates and people i asked think the same thing - 
AE2 is BAD
but the idea about storing items on hard drive and basically building a server is briliiant and original
![the good old system](https://user-images.githubusercontent.com/29714555/27555980-10416722-5ab4-11e7-8e2f-3bf90b1d7559.png)
#### Environment
AE2 controller sometimes sets on fire itself (tekkit legends) XD

- Minecraft Version: would use newer but there is no AE1
- AE2 Version: AE1
- Forge Version: IDK

**Comment by Ld01337** [comment]
ps all drives on screenshot up there are 64k :D and it is really power hungry somethig around 900-800 kj per tick (powered with BigReactor)

**Comment by Ld01337** [comment]
the only good thing about AE is the spatial storage otherwise nothing

**Comment by vallard192** [comment]
AE1 and AE2 have in common the original author and the idea of storing
items digitally.  I think the biggest mistake made in AE2 is that it was
named AE2 instead of something different.  It is a different mod with a
couple of similar themes but a completely different design.

Your ticket can be summarized as "This mod is not the same as a different
mod with a similar name."

It's probably best if you try other storage mods because you've already
determined that you don't like this one.  Refined Storage and EZStorage
might be more to your liking.

**Comment by mindforger** [comment]
Well, the way you are talking is the best way to burry it forever... How about constructive criticism, all you do is complain and dishonor the work invested .... Shame on you, use another mod and leave the devs alone

**Comment by mgdgfbhevdyeh** [comment]
AE2, TE and Mekanism, the more is the pursuit of balance
If the survival of the MC is too OP, I think it is better to play the creative mode
Limitations of channels, more wisdom is to allow players to play
I think RS is useless, is entirely plagiarism
Why AE is Bad ???
AE pioneered the era of storage, which do not always point to the RS RS is always plagiarism

PS:My english is no good
