### ISSUE TITLE
Unable to extract from the matter condenser

### ISSUE THREAD

**Issue by DaemosDaen** [AppliedEnergistics/Applied-Energistics-2#2939]
#### Description
This is pretty much a case of "what is says on the tin". I am unable to extract matter balls from a matter condenser using ME Import Bus, EnderIO conduits, Minecraft hopper, TD item ducts, ExtraUtils Item node
I can put items into the Matter Condenser via Hopper, ME Export Bus, and a filtered ME Storage Bus
#### Environment
Default client/server setup of the DW20 pack v 1.12.1 for MC 1.10.2

- Minecraft Version:  1.10.2
- AE2 Version:  rv4a11
- Forge Version: 2316
- DW20 Pack version: Release; 1.12.1

**Comment by mindforger** [comment]
as far as i remember it is not implementing the new inventory system, AE2 is under heavy construction, please have patience

**Comment by DaemosDaen** [comment]
Just dropping off a notice as it does not work with AE2 either.

**Comment by yueh** [comment]
Duplicate
