### ISSUE TITLE
(1.10.2) Advanced Inscriber Requires Multiple Presses (Not Sure What Mod)

### ISSUE THREAD

**Issue by StevieBranscum** [AppliedEnergistics/Applied-Energistics-2#2942]
#### Description
 RV4-Alpha-11
 I have auto-crafting recipes for the AE2 Stuff Advanced Inscriber, and I have up to 64K storage drives. When I make a 64k drive, it requires about 40 Silicon Presses, and it only pulls out 1 press, ruining automation.

#### Environment

 Playing FTB Beyond, with Mystical Agriculture installed

- Minecraft Version: 1.10.2
- AE2 Version: RV4-Alpha-11
- Forge Version: Don't Know as of Right Now.

**Comment by Ommina** [comment]
I'm not 100% certain of the issue you're trying to describe here, but you seem to be discussing the AE2Stuff Inscriber.  If so, you should be reporting it on AE2Stuff issue page ( https://github.com/bdew/ae2stuff/issues ), not here.

**Comment by StevieBranscum** [comment]
Well I don't know. It was with an autocrafting recipe and I assumed it was with AE2. Sorry.

**Comment by mgdgfbhevdyeh** [comment]
I think it's AE2 Stuff BUG

**Comment by TheUnderTaker11** [comment]
Close this issue. It isn't anything but a human problem. You put the silicon press as part of the recipe and got surprised when it asked for a bunch of them. The point is to leave those presses in the machines.

**Comment by StevieBranscum** [comment]
It's not just that. It ruins automation for my presses. I guess it's just that, as players and humans, we strive for efficiency, and we find it annoying and inefficient running back and forth. Sorry for the hassle, as I said, I wasn't sure of what mod it was caused by.

**Comment by TheUnderTaker11** [comment]
My point is you need at least 1 inscriber for each press, then make the recipe be whatever material is used by that press.

**Comment by Quest79** [comment]
If youre not sure what mod it is, take the time to google it before taking time to do a bug report with bad information.
