### ISSUE TITLE
Subnet storage system not working.

### ISSUE THREAD

**Issue by thecheff** [AppliedEnergistics/Applied-Energistics-2#2943]
Using Applied Energistics 2, rv3-beta-6.
Extra Cells 2 2.3.14.

Im trying to create a storage system using subnets.

https://gyazo.com/8000b3a9ee8a2317132173361a8e8af2

Items in 16k, regular AE2 cells appear to be working. It doesn't seem to read anything from extra cells 2, i.e. fluids. Why is this?

**Comment by mindforger** [comment]
why do you ask AE2 about that? ask in the Extra Cells repo!
