### ISSUE TITLE
[Code question] Where are the static items declared in code?

### ISSUE THREAD

**Issue by TheUnderTaker11** [AppliedEnergistics/Applied-Energistics-2#2944]
Sorry to make a Github issue about this, but I'm unable to find where the items are declared in your code. I'm making a recipe for your mod and I'm unable to find where the items are I need.

**Comment by thatsIch** [comment]
they are mostly declared via reflection and its Item Class Names. You can dump them using mods like NEI or similar helper mods

**Comment by TheUnderTaker11** [comment]
I was stupid and didn't realize I could get the items from their registry names, was going to close this but forgot.
