### ISSUE TITLE
not a bug a question

### ISSUE THREAD

**Issue by omagarwal25** [AppliedEnergistics/Applied-Energistics-2#2947]
Is AE2 stable enough to play 1.10.2 if so what is not working yet

**Comment by DaemosDaen** [comment]
I've had no issues except shift click crafting, but that issue happens with all kinds of mods, it's only more noticeable because ME inventories can get very large.

**Comment by mindforger** [comment]
what kind of issue do you have? It is as stable as it could

**Comment by omagarwal25** [comment]
@mindforger no issue but wanted to know if it was close to fully work FYI I'm making a private mod pack and I wanna have a chose btw Refined Storge and me.

**Comment by mindforger** [comment]
question was at Daemos sorry

**Comment by DaemosDaen** [comment]
When using a crafting Terminal and shift clicking several stacks of items there may be a bit of server lag. This is in a MP setup on a server with 4 cores running at 2.4ghz, and the MC server running with 6 GB ram. Running the DW20 pack.

**Comment by mindforger** [comment]
i noticed the stack forming slowly for some reason... Or do you mean real lag.... Then your system lacks a few energy cells

**Comment by DaemosDaen** [comment]
No, the stack forming slowly. The system has plenty of power.

**Comment by mindforger** [comment]
i also noticed that, can not explain ... what i meant ith lag is when you system is big enough and has no energyx  cell, the request can empty your system in one tick ... resulting in a power loss, recovery and resulting reevaluation of the net ... this can indeed cause a severe lag on the server :) so always install one or two energy cells ;)

**Comment by DaemosDaen** [comment]
I knew about the energy issue, I made a dense one early on. Right after I started the quartzite vein's excavator (Immersive Engineering.)
