### ISSUE TITLE
Kicked out of terminal when clicking autocrafting recipe

### ISSUE THREAD

**Issue by TheDutchMC04** [AppliedEnergistics/Applied-Energistics-2#2950]
#### Description
Everytime I try to click an autocrafting recipe in a terminal, I get kicked out of the terminal. I have 3 1k crafting storages and 1 co-processing units. No recipes work, not in a molecular assembler neither a interface on machine. I don't know what the problem is. Channels or power are not the problem.

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-11
- Forge Version: forge-12.18.3.2316

**Comment by mindforger** [comment]
remove wireless crafting terminal mod (this is a known issue caused by them)
if not present, go ingame, press and hold F3 + C to get forced crashlog and post it via pastebin or compareable site :)

no wall of text please
