### ISSUE TITLE
How to enable meteorites?

### ISSUE THREAD

**Issue by Conzile** [AppliedEnergistics/Applied-Energistics-2#2951]
Hi!

I started playing FTB Beyond some time ago and now wanted to start using applied Energistics 2. But there is a problem! there is no meteorites enabled. so my question is how do i do that?

**Comment by piedpipr314** [comment]
it's in /config/AppliedEnergistics2/AppliedEnergistics2.cfg  Simply edit it with a text editor of your choice.  If you scroll down to features, world, there is a "B:MeteoriteWorldGen=(true/false)", and yours is probably set to false.  Just set it to true and you should be good.  Oh, and unless you have some type of retrogen, they'll only be in new chunks.

**Comment by piedpipr314** [comment]
Yes, I can confirm that the FTB team disabled those.  The presses are craftable via minetweaker, or should be.  (I'm checking their scripts)
