### ISSUE TITLE
Singleplayer low tps

### ISSUE THREAD

**Issue by N3rdG4mer** [AppliedEnergistics/Applied-Energistics-2#2955]
#### Description
Every time I create a map with the applied installed, it causes the tps of the world to be very low, and when it manages to be stable, I walk 3 blocks and the tps fall a lot

#### Environment
Low tps: http://prntscr.com/fvjwh3

- Minecraft Version: 1.10.2
- AE2 Version: rv4.alpha build 11
- Forge Version: 12.18.3.2316

**Comment by yueh** [comment]
#2774
