### ISSUE TITLE
Invalid crafting type: grindfz

### ISSUE THREAD

**Issue by kkinateder** [AppliedEnergistics/Applied-Energistics-2#2959]
Hello,

I know that error appears, cause there is no Grind Factorization mod in my environment. Would be nice to suppress that warning, or give an option to not try to include, when Factorization isnt present.
Or should I just delete the cfg?

Regards,
Karsten

**Comment by mindforger** [comment]
can you give some informations like minecraft version, AE2 version, a log file showing your issue eventually ? sorry to ask all that things but it is hard to tell what you are referring to :)

**Comment by kkinateder** [comment]
Forge Mod Loader version 12.18.3.2316 for Minecraft 1.10.2 loading
[main/INFO] [FML/]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_131, running on Linux:amd64:3.16.0-4-amd64, installed at /usr/lib/jvm/java-8-oracle/jre

List of loaded APIs: 		* actuallyadditionsapi (29) from ActuallyAdditions-1.10.2-r105.jar
		* AppleCoreAPI (2.2.0) from AppleCore-mc1.10.2-2.1.2.jar
		* appliedenergistics2|API (rv4) from appliedenergistics2-rv4-alpha-11.jar
		* AromaBackupAPI (1.0) from AromaBackup-1.9.4-2.0.0.0.b62.jar
		* Base|API (1.0.0) from base-1.10.2-1.4.0.jar
		* Baubles|API (1.3.1.3) from WirelessCraftingTerminal-1.10.2-0.1.31.jar
		* BetterQuesting|API (2.6) from BetterQuesting-2.3.231.jar
		* BetterWithModsAPI (Beta 0.6) from Better With Mods-0.14.24-1.10.2.jar
		* bigreactors|API (4.0.1) from ExtremeReactors-1.10.2-0.4.5.29.jar
		* ChiselAPI (0.0.1) from Chisel-MC1.10.2-0.0.10.22.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.10.2-0.0.10.22.jar
		* ChiselsAndBitsAPI (12.10.0) from chiselsandbits-12.12.jar
		* CoFHAPI (1.8.9R1.2.0B1) from Railcraft_1.10.2-10.1.2.jar
		* cofhapi (1.5.0) from SimplyJetpacks2-1.10.2-2.1.1.47.jar
		* cofhapi|block (1.6.0) from zerocore-1.10.2-0.1.0.6.jar
		* CoFHAPI|core (1.8.9R1.2.0B1) from valkyrielib-1.10.2-0.10.6.jar
		* cofhapi|core (1.6.0) from zerocore-1.10.2-0.1.0.6.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from WirelessCraftingTerminal-1.10.2-0.1.31.jar
		* cofhapi|energy (1.5.0) from ActuallyAdditions-1.10.2-r105.jar
		* CoFHAPI|inventory (1.8.9R1.2.0B1) from valkyrielib-1.10.2-0.10.6.jar
		* CoFHAPI|item (1.8.9R1.2.0B1) from valkyrielib-1.10.2-0.10.6.jar
		* cofhapi|item (1.6.0) from CoFHCore-1.10.2-4.1.1.156-universal.jar
		* CoFHAPI|tileentity (1.8.9R1.2.0B1) from ProgressiveAutomation-1.10.2-1.7.4.jar
		* cofhapi|tileentity (1.6.0) from zerocore-1.10.2-0.1.0.6.jar
		* cofhapi|util (1.6.0) from CoFHCore-1.10.2-4.1.1.156-universal.jar
		* cofhlib (1.6.0) from CoFHCore-1.10.2-4.1.1.156-universal.jar
		* cofhlib|audio (1.6.0) from CoFHCore-1.10.2-4.1.1.156-universal.jar
		* cofhlib|gui (1.6.0) from CoFHCore-1.10.2-4.1.1.156-universal.jar
		* cofhlib|gui|container (1.6.0) from CoFHCore-1.10.2-4.1.1.156-universal.jar
		* cofhlib|gui|element (1.6.0) from CoFHCore-1.10.2-4.1.1.156-universal.jar
		* cofhlib|gui|element|listbox (1.6.0) from CoFHCore-1.10.2-4.1.1.156-universal.jar
		* cofhlib|gui|slot (1.6.0) from CoFHCore-1.10.2-4.1.1.156-universal.jar
		* cofhlib|inventory (1.6.0) from CoFHCore-1.10.2-4.1.1.156-universal.jar
		* cofhlib|util (1.6.0) from CoFHCore-1.10.2-4.1.1.156-universal.jar
		* cofhlib|util|helpers (1.6.0) from CoFHCore-1.10.2-4.1.1.156-universal.jar
		* cofhlib|world (1.6.0) from CoFHCore-1.10.2-4.1.1.156-universal.jar
		* cofhlib|world|feature (1.6.0) from CoFHCore-1.10.2-4.1.1.156-universal.jar
		* ComputerCraft|API (1.80pr0) from zerocore-1.10.2-0.1.0.6.jar
		* ComputerCraft|API|FileSystem (1.80pr0) from zerocore-1.10.2-0.1.0.6.jar
		* ComputerCraft|API|Lua (1.80pr0) from zerocore-1.10.2-0.1.0.6.jar
		* ComputerCraft|API|Media (1.80pr0) from zerocore-1.10.2-0.1.0.6.jar
		* ComputerCraft|API|Peripheral (1.80pr0) from zerocore-1.10.2-0.1.0.6.jar
		* ComputerCraft|API|Permissions (1.80pr0) from zerocore-1.10.2-0.1.0.6.jar
		* ComputerCraft|API|Redstone (1.80pr0) from zerocore-1.10.2-0.1.0.6.jar
		* ComputerCraft|API|Turtle (1.80pr0) from zerocore-1.10.2-0.1.0.6.jar
		* CoroAI|dynamicdifficulty (1.0) from coroutil-1.10.2-1.1.16.jar
		* CSLib|API (0.3.0) from Decocraft-2.4.2_1.10.2.jar
		* DLDungeonsAPI (1.1) from DoomlikeDungeonsJBG-1.9.2-MC1.10.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.10.2-3.1.192.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.10.2-3.1.192.jar
		* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.10.2-3.1.192.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.10.2-3.1.192.jar
		* environmentaltech-api (1.10.2-0.10.6b) from environmentaltech-1.10.2-0.10.6b.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.10.2-5.2.17.376.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.10.2-5.2.17.376.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.10.2-5.2.17.376.jar
		* ForestryAPI|climate (2.1.0) from forestry_1.10.2-5.2.17.376.jar
		* ForestryAPI|core (5.1.0) from forestry_1.10.2-5.2.17.376.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.10.2-5.2.17.376.jar
		* ForestryAPI|food (1.1.0) from forestry_1.10.2-5.2.17.376.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.10.2-5.2.17.376.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.10.2-5.2.17.376.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.10.2-5.2.17.376.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.10.2-5.2.17.376.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.10.2-5.2.17.376.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.10.2-5.2.17.376.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.10.2-5.2.17.376.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.10.2-5.2.17.376.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.10.2-5.2.17.376.jar
		* ForestryAPI|world (2.1.0) from forestry_1.10.2-5.2.17.376.jar
		* IC2API (1.0) from Slugs Converters.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.10-58.jar
		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.10-58.jar
		* IronBackpacks|API (0.5) from IronBackpacks-1.10.2-2.2.27.jar
		* journeymap|client-api (1.3) from journeymap-1.10.2-5.4.6.jar
		* journeymap|client-api-display (1.3) from journeymap-1.10.2-5.4.6.jar
		* journeymap|client-api-event (1.3) from journeymap-1.10.2-5.4.6.jar
		* journeymap|client-api-model (1.3) from journeymap-1.10.2-5.4.6.jar
		* journeymap|client-api-util (1.3) from journeymap-1.10.2-5.4.6.jar
		* JustEnoughItemsAPI (4.10.1) from jei_1.10.2-3.14.7.420.jar
		* Open Glider|API (0.1) from OpenGlider-1.10.2-0.2.3.jar
		* pressureAPI (1.3.1.25) from pressure-1.3.1.25-mc1.10.2.jar
		* ProjectEAPI (1.9.4-1.0.0) from p455w0rdslib-1.10.2-1.0.13.jar
		* railcraft:API|core (3.1.0) from Railcraft_1.10.2-10.1.2.jar
		* RailcraftAPI|bore (2.0.0) from Railcraft_1.10.2-10.1.2.jar
		* RailcraftAPI|carts (2.1.0) from Railcraft_1.10.2-10.1.2.jar
		* RailcraftAPI|charge (3.0.0) from Railcraft_1.10.2-10.1.2.jar
		* RailcraftAPI|crafting (2.0.0) from Railcraft_1.10.2-10.1.2.jar
		* RailcraftAPI|events (2.0.0) from Railcraft_1.10.2-10.1.2.jar
		* RailcraftAPI|fuel (2.0.0) from Railcraft_1.10.2-10.1.2.jar
		* RailcraftAPI|helpers (2.0.0) from Railcraft_1.10.2-10.1.2.jar
		* RailcraftAPI|items (2.1.0) from Railcraft_1.10.2-10.1.2.jar
		* RailcraftAPI|locomotive (2.0.0) from Railcraft_1.10.2-10.1.2.jar
		* RailcraftAPI|signals (4.0.0) from Railcraft_1.10.2-10.1.2.jar
		* RailcraftAPI|tracks (4.0.0) from Railcraft_1.10.2-10.1.2.jar
		* reborncoreAPI (2.13.6.142) from RebornCore-1.10.2-2.13.6.142-universal.jar
		* reborncoreAPI|Fuel (2.13.6.142) from RebornCore-1.10.2-2.13.6.142-universal.jar
		* reborncoreAPI|Power (2.13.6.142) from RebornCore-1.10.2-2.13.6.142-universal.jar
		* reborncoreAPI|Recipe (2.13.6.142) from RebornCore-1.10.2-2.13.6.142-universal.jar
		* reborncoreAPI|Tile (2.13.6.142) from RebornCore-1.10.2-2.13.6.142-universal.jar
		* SoulShardsTOW|API (0.1.5) from SoulShards-TOW-1.10.2-2.6.7-48.jar
		* StorageDrawersAPI (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.7.8.jar
		* StorageDrawersAPI|config (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.7.8.jar
		* StorageDrawersAPI|event (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.7.8.jar
		* StorageDrawersAPI|inventory (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.7.8.jar
		* StorageDrawersAPI|pack (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.7.8.jar
		* StorageDrawersAPI|registry (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.7.8.jar
		* StorageDrawersAPI|render (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.7.8.jar
		* StorageDrawersAPI|storage (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.7.8.jar
		* StorageDrawersAPI|storage-attribute (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.7.8.jar
		* valkyrielib.api (1.10.2-0.10.6) from valkyrielib-1.10.2-0.10.6.jar
		* VeinMinerApi (0.3) from VeinMiner-1.9-0.36.0.609+0056a96.jar
		* WailaAPI (1.3) from Waila-1.7.0-B3_1.9.4.jar
		* wct|API (1.10.2-rv4-1.0.0b) from WirelessCraftingTerminal-1.10.2-0.1.31.jar
		* zerocore|API|multiblock (1.10.2-0.0.2) from zerocore-1.10.2-0.1.0.6.jar
		* zerocore|API|multiblock|rectangular (1.10.2-0.0.2) from zerocore-1.10.2-0.1.0.6.jar
		* zerocore|API|multiblock|tier (1.10.2-0.0.2) from zerocore-1.10.2-0.1.0.6.jar
		* zerocore|API|multiblock|validation (1.10.2-0.0.2) from zerocore-1.10.2-0.1.0.6.jar

**Comment by kkinateder** [comment]
its a custom Forever Stranded Modpack.

**Comment by mindforger** [comment]
this still does not show your issue
>Would be nice to suppress that warning

what warning do you mean? Can you make a screenshot of what you mean

it is impossible to reproduce this issue and see what exactly you mean, especially because you are using a custom modpack, nobody can tell what is all that custom ... deleting the AE2 configs and especially the recipe files could probably help but it would rip apart alle the recipes the original modpack maker has included ... you have to edit the configs and fix the recipes using items from mods you have not installed anymore or you will break your modpack

and i suppose you did not read my edit when answering :) so please avoid those wall of text postings and use pastebin or similar instead or attach the logfiles to the post ... increases readability of an issue alot :)

**Comment by yueh** [comment]
The easist option is to ignore it. Or simply edit the recipes, that is why they exist.

Logs are not there to preventively search for meaningless stuff, but to actually help solving issues once they arise. Should we have to refrain from logging everything, it the log itself would become pretty useless as it no longer gives any hint. But that comes at the cost of maybe being a bit inconvenient in some cases.

**Comment by chezpaul** [comment]
These are the warnings he's talking about:
[09:15:54] [Server thread/INFO] [AE2:S]: Disabling item.csv export for custom recipes, since creative tab information is only available on the client.
[09:15:54] [Server thread/WARN] [AE2:S]: Recipe Error 'Invalid crafting type: grindfz' near line:1 in processing/factorization.recipe with: [ae2:material.FluixCrystal, ->, ae2:material.FluixDust]
[09:15:54] [Server thread/WARN] [AE2:S]: Recipe Error 'Invalid crafting type: grindfz' near line:2 in processing/factorization.recipe with: [ae2:sky_stone_block:0, ->, ae2:material.SkyDust]
[09:15:54] [Server thread/WARN] [AE2:S]: Recipe Error 'Invalid crafting type: grindfz' near line:4 in processing/factorization.recipe with: [mc:ender_pearl, ->, ae2:material.EnderDust]
[09:15:54] [Server thread/WARN] [AE2:S]: Recipe Error 'Invalid crafting type: grindfz' near line:5 in processing/factorization.recipe with: [ae2:material.CertusQuartzCrystalCharged, ->, ae2:material.CertusQuartzDust]
[09:15:54] [Server thread/WARN] [AE2:S]: Recipe Error 'Invalid crafting type: grindfz' near line:7 in processing/factorization.recipe with: [ae2:material.CertusQuartzCrystal, ->, ae2:material.CertusQuartzDust]
[09:15:54] [Server thread/WARN] [AE2:S]: Recipe Error 'Invalid crafting type: grindfz' near line:8 in processing/factorization.recipe with: [ae2:quartz_ore, ->, 2, ae2:material.CertusQuartzDust]
[09:15:54] [Server thread/WARN] [AE2:S]: Recipe Error 'Invalid crafting type: grindfz' near line:9 in processing/factorization.recipe with: [ae2:charged_quartz_ore, ->, 2, ae2:material.CertusQuartzDust]

**Comment by mindforger** [comment]
@chezpaul the issue is months old and closed 

try to regenerate your configs and see if the issue vanishes, if this is a modpack, seek for help from the pack author

**Comment by fscan** [comment]
There is no need to seek help as there is **no problem**. Like yueh said, this is not a error, just a warning that 'grindfz' (which is the factorization grinder) is not available. **This is expected behaviour at the moment**.

**Comment by chezpaul** [comment]
He never answered your question. I was just trying to help. Sorry guys.
