### ISSUE TITLE
Not able to extract from Matter Condenser

### ISSUE THREAD

**Issue by whatthedrunk** [AppliedEnergistics/Applied-Energistics-2#2960]
Just putting this her for the reminder. 
"Not being able to extract from the condenser is because they don't expose Item capabilities yet"

- Minecraft Version:  1.12
- AE2 Version: Custom version on ATC
- Forge Version: 2415

**Comment by GuntherDW** [comment]
Hmm, I might've been wrong in my early assumptions. We'll need to look at this a bit better.

**Comment by yueh** [comment]
Also note that condenser never exposed their inventory. I asked Algo about it, but he could not remember, if there was a balancing decision for it.

But it is pretty much 1 of 2 missing things to allow self replicating storage systems.
