### ISSUE TITLE
[1.12] Localisation names all broken

### ISSUE THREAD

**Issue by Morpheus1101** [AppliedEnergistics/Applied-Energistics-2#2965]
MC Version: 1.12
AE version: rv5-alpha-0
Forge version: 14.21.1.2420

Localisation names for all things are no longer working using the latest code from the rv5-alpha 1.12 branch as of 12hrs ago

**Comment by Morpheus1101** [comment]
Closing as i resolved after cleaning the workspace and re-building

**Comment by GuntherDW** [comment]
This might be one of those occasions where a "gradlew clean" could have saved you a headache.
That task cleans (well, deletes) the build/ directory, making the next build not use cached resources.
