### ISSUE TITLE
AE2 Storage system erases Botania stuff's inventory

### ISSUE THREAD

**Issue by Chocorean** [AppliedEnergistics/Applied-Energistics-2#2970]
#### Description

How to do it : fill a Bauble Case or a Flower Pouch (from Botania mod) with something and put them in a storage cell. Just take it back and they become empty instead of containing deposed items. I don't know how storage has been coded in Botania but there is something wrong between AE2 and Botania.

#### Environment
Bug occurs while playing both MP and SP serveur
- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-11
- Forge Version:  12.18.3.2316

#### Comments
Your mod is just wonderful, but not hard enough I think. Storage is so broken, I think it should be more expensive to make one. (especially quantum this is sooooooo cheap :o)

**Comment by yueh** [comment]
#2624
