### ISSUE TITLE
Inscriber name pressed items revert to original name when placed in world

### ISSUE THREAD

**Issue by BattleNachos** [AppliedEnergistics/Applied-Energistics-2#2973]
Modpack Age of Engineering 1.0.3
AE2 1.10.2 rv4 alpha 11

Anything (including named ME interfaces) immediately loses its custom name when placed in world.  Same behavior with anvil named items.  If connected to a network they appear as their original name.

Just me?  Any thoughts?

**Comment by GuntherDW** [comment]
I know this was a bug in my 1.11.2 version (and in extension the 1.12 one), but in 1.10.2 that feature should still work as intended.

What are you checking the names with, WAILA/TOP or the interface terminal/the terminal itself?

**Comment by BattleNachos** [comment]
As soon as an item is placed in the world TOP (i believe it's TOP in this modpack) tooltip shows original name, connecting the item to a AE2 network and then looking for the item in interface terminal displays original name as well.

**Comment by GuntherDW** [comment]
That TOP/WAILA doesn't show the custom name is a known issue, but the interface terminal (I had someone test just recently) does show the name in an interface terminal in 1.10.

It was tested with "Forever Stranded".
http://i.imgur.com/K1Zl6Ad.png (The empowerer is pointing to a chest).

It is a bit buggy in a development environment because it clashes with a name in an interface in vanilla minecraft depending on which mappings they used back then.
Could you try rv4-stable-1 and check if still happens in there?
https://github.com/AppliedEnergistics/Applied-Energistics-2/releases/tag/rv4.stable.1

Also, which AE2 addons are installed in the modpack?

**Comment by BattleNachos** [comment]
Tested in rv4 stable 1.  Same issue.  As far as AE2 addons I'm uncertain what I'm looking for.  Going through the list of installed addons for the modpack all I see is AE2 so if they're named "Applied somethin or other" then there aren't any AE2 addons.

**Comment by BattleNachos** [comment]
I just created a fresh profile to test with only a few mods installed.  Same issue.  My setup: http://imgur.com/a/rPZVD

1.10.2
Addons:
AE2
CompatLayer
JEI
The One Probe
TOP Addons

**Comment by GuntherDW** [comment]
Fresh world with latest Forge ( 12.18.3.2185 ) and latest 1.10.2 build from the CI server.
Still can't get the bug to occur.

http://i.imgur.com/UONCody.png

The only mod installed in that profile is AE2. Where did you get that 1.10.2 AE2 build?

**Comment by BattleNachos** [comment]
I created a new 1.10.2 profile in the curse/twitch loader and downloaded the mod from there.  I tested with just AE2 and JEI only.

**Comment by BattleNachos** [comment]
Update: semi resolved, odd behavior.  Maybe it's just me?

In Curse launcher click profile picture to View Profile, then in top right corner click "..." for dropdown, then "Repair Minecraft."

I "Repaired Minecraft" for my Age of Engineering modpack profile.  I can name ME Interfaces and the name will stay.  It won't show in TOP tooltip but opening the Interface config shows the new name, and the new name displays in a ME Interface Terminal.

However, I can rename chests, and when I place it in the world I can open it and the new name shows up in the chest, but when I connect to an interface and look for it in ME Interface Terminal it just shows up as "Chest".

"Repair Minecraft" option in curse launcher did partially fix my issue, but I have no idea how the repair function works so couldn't say how it worked.
