### ISSUE TITLE
[1.12] Controller not sharing energy

### ISSUE THREAD

**Issue by 016Nojr** [AppliedEnergistics/Applied-Energistics-2#2980]
When a controller is placed like this: https://gyazo.com/d344f3986fcc0c1336894365069b42ba

The controller in the middle is "split" off from the other controllers, when one of the 4 blocks next to the controller is removed, the controller lights up along with the 3 that is left. https://gyazo.com/7185635acb3d29ad4887ff52df0a7dcb

Not sure if this is intended or not, but I figured I would report it.

I compiled the mod myself after 4ad31f506621eea2656f3b313a5b44b7b7974cce was pushed to the 1.12 branch on GitHub.

Forge: 14.21.1.2423
Modlist can be provided if wanted

**Comment by 016Nojr** [comment]
Any comments on why it was closed? @yueh

**Comment by Dhvagra** [comment]
That's intended gameplay behavior.

**Comment by Ommina** [comment]
"3. A ME Controller can have 2 adjacent blocks in at most 1 axis; if a block violates this rule, it will disable and turn white." (in case you're curious).

**Comment by 016Nojr** [comment]
ah, didnt know about that
