### ISSUE TITLE
New tool to move Drives and Interfaces without losing contents

### ISSUE THREAD

**Issue by lpenap** [AppliedEnergistics/Applied-Energistics-2#2981]
#### Description
This tool is the equivalent of a chest mover.
The tool will be able to pickup ME Drives and Interfaces (or any machine in general) without losing contents (right click to pickup, right click to place it).
The tool will remain loaded with just one machine and will lose energy overtime.
The tool could be charged again in the charger.
The tool will drop the machine and therefore the machine contents if its internal energy is depleted.
Having a loaded tool could produce effects on the player like "slow".
Maybe it could be restricted to move the loaded tool to other inventories and it must remain in player inventory until the machine is placed again or is droped due to lack of energy.

#### Environment

- Minecraft Version: 
- AE2 Version: 
- Forge Version:

**Comment by GuntherDW** [comment]
While not being able to store contents, most machines can be wrenched instead of mined with a pickaxe to store settings,names and/or power.

**Comment by lpenap** [comment]
Indeed. The main purpose of the tool is to relocate ME Drives and Interfaces.

**Comment by mindforger** [comment]
and then you stuff the drive with the disks in it back into another ME system ... i can hear the minecraft world storage system grinding to a halt with a terrible sound :P

**Comment by lpenap** [comment]
Hence I suggested that the loaded tool could not be placed in other inventories.

**Comment by mindforger** [comment]
yeah the last line must have slipped my mind, but how can one prevent that from happening? there is no way that springs to my mind yet .. and to be honest ... having the item with that much data in it already in the player inventory can cause havoc already ... BluSunrize from IE had an fantastic crash with a bunch of "golden bag of holding" stuffed into an crate which was then crashing everybody trying to pickup that crate

**Comment by GuntherDW** [comment]
That is already a feature mindforger. You cannot in the current version store filled cells into other cells.
Nevertheless I don't know if this is a viable tool or option just yet.

**Comment by mindforger** [comment]
have you tried to stuff a cell in a bag and stuff the bag into the system ... this is one of those creepy things that destroy worlds 

i just afraid of the consequences of giving people things into their hand that can lead to catastrophic failure

and i actually have remembered that it were ME disks, stored in a crate, stored in a bag of holding and then beeing dropped into an ME system causing a server to crash

**Comment by yueh** [comment]
This is a pretty easy no for the following reasons

1. It is an absolute nightmare in terms of player and/or world corruption. Putting the amount of data stored inside a drive into an item can easily corrupt your player.dat. Which is already the case with using any bag mod to store cells and there is no way to prevent it.

2. It is one source for dupes. It literally works by duping the block including any content and then breaking the block itself, hoping that it does not dump their inventory. Which of course then happens.

**Comment by lpenap** [comment]
Thanks for you reply @yueh ! makes sense.

**Comment by leagris** [comment]
It could work better if disk content was stored on a file/directory handled by AE. This is how OpenComputers handle disk content. So when player transports a disk, that disk content is not stored inside player.dat and when disk is inside a drive or computer, its content is not part of the tile's NBT data. The only NBT of a disk is an identifier used to reference the actual file assigned to this disk.
