### ISSUE TITLE
AE network import & export buses stoped working

### ISSUE THREAD

**Issue by exxis** [AppliedEnergistics/Applied-Energistics-2#2983]
Version of the Mod/Modpack 

Hello,

i´ve encountered an issue with the import and export buses in connection with machines (right now only tested with Thermal Expansion machines)

If an import a export bus is connected to a machine and the machine is upgradeable like augmentations speed upgrade, stuff like that. All import and export buses connected to that ME system stop working. All Devices are online and functional only no import nor export is happening. The same Problem was explained here #838
I´ve tested it right now only with Thermal Expansion but i assume there might be some other machines where this will happen. (I will update if i find more)

- Modpack: Project Ozone 2: Reloaded
- Minecraft Version:  1.7.10
- AE2 Version: appliedenergistics2-rv3-beta-6
- Forge Version: 10.13.4.1614

**Comment by yueh** [comment]
We no longer support 1.7.10 at this point.

Should you be able to confirm that this issue still apply to the most recent version, please update the issue and we will reopen it.
