### ISSUE TITLE
[1.12] SMP Wireless Terminal Stops Working//Connection is broken after a server restart

### ISSUE THREAD

**Issue by Morpheus1101** [AppliedEnergistics/Applied-Energistics-2#2984]
#### Description
Playing on the ATC Server and i've noticed a few times that the Wireless terminal when i come back has stopped functioning.  This time it was working before the server restart and after it has restarted whewn trying to use the Wireless terminal you get the error "Station can not be located".  The only Solution to fix this is to goto the Security Terminal, break it, grab the biometric card/s, break the machine and place it back down and re-insert biometric cards, re-link device(although this last step is probably not needed) and everything works fine again.

#### Environment

Used in SMP with the ATC Pack .. pic below is a brief look at what the setup of the various AE network etc thats running.

https://puu.sh/wW4Je/8384c9f109.png

- Minecraft Version: 1.12
- AE2 Version: appliedenergistics2-rv5-alpha-0-wtd2
- Forge Version:  *.2426

**Comment by fscan** [comment]
I can't reproduce with rv5-alpha-2, can you confirm this is still an issue?

**Comment by Morpheus1101** [comment]
Its still an issue, however its intermittent and not always guaranteed to happen

**Comment by fscan** [comment]
Does replacing the security station fix the problem or do you need to re-link the device? 
Also, can you fix it by relogging/restarting the server or does it stop working forever?

**Comment by Morpheus1101** [comment]
Replacing the Security station yes, no need to re-link wireless terminal though. Restarting the server or relogging has no affect and remains broken untill such time as you replace the Security Terminal

**Comment by Morpheus1101** [comment]
Is this now fixed or ?

**Comment by yueh** [comment]
Data loss is currently a forge "feature" and it might not see a working fix before 1.13 (if at all). So nothing we can do about it and you simply have to deal with it.
