### ISSUE TITLE
Did 1.11.2 get skipped?

### ISSUE THREAD

**Issue by Go-Wish** [AppliedEnergistics/Applied-Energistics-2#2989]
Is 1.11 getting skipped?

**Comment by Ommina** [comment]
While I've not seen an official announcement, all indications are 'yes'.

**Comment by GuntherDW** [comment]
I at first was going to attempt supporting both 1.11.2 and 1.12 at first, and might just maybe give that a go in the future.
But right now, with how the codebase is shifting around, and how most of the actual 1.12 code isn't really ready yet a 1.11.2 backport would mean a lot of potentially wasted efforts.

In short, "not now, maybe in the future".

**Comment by yueh** [comment]
As @GuntherDW said maybe not. But very unlikely as minecraft is going forward and not backwards. 1.11 was not that widely supported support and most of them already moved on to 1.12. The more time passes, less incentives exist for backporting a mod. Same reason why there is no AE2 for 1.6.4 or 1.2.5

**Comment by FireController1847** [comment]
@GuntherDW Would love to see this for 1.11.2, as I don't like updating my modpack to the latest version because then another 1.12.x comes out, and I have to update AGAIN. It'd be great to see this for 1.11.2, of course when you have time <3
