### ISSUE TITLE
Question about texture. 

### ISSUE THREAD

**Issue by CrossVas** [AppliedEnergistics/Applied-Energistics-2#2993]
Hey!

Is there a way to change DEFAULT color (purple) of ME Terminals, ME Monitors, Illuminated Panels?
Ex. I want to replace purple color by blue (like in old version).

I know that i can do with colored cable, but i want it to be by default.

Thanks!

**Comment by xenxero1** [comment]
I dont believe so, since the colors are actually important to the channel system.

**Comment by VT-14** [comment]
Might be able to do it with a run of the mill texture pack.  Looks like the cables and such might be the 'transparent' textures.

I'm not sure how the terminals are colored.

**Comment by CrossVas** [comment]
After several hours of torment i found out a few things:

- You cant change default (purple) color of Terminals;
- You also can't make white color by default. If you set white texture, it use transparency system (White color is applied over the base colors). Except white color.
- To get old view of terminals, monitors i should use white cable white cable. 

Result:
Applied Energistics 1
![image](https://user-images.githubusercontent.com/25727222/28876488-0b932958-77a2-11e7-9978-9aae37451502.png)

Applied Energistics 2
![image](https://user-images.githubusercontent.com/25727222/28876518-237be294-77a2-11e7-942d-58f31924c117.png)
