### ISSUE TITLE
Terminal closes because of autocrafting

### ISSUE THREAD

**Issue by MelanX** [AppliedEnergistics/Applied-Energistics-2#2997]
- Minecraft Version: 1.10.2
- AE2 Version: rv4-stable-1 (latest :D)
- Forge Version: 12.18.3.2422

At first: I'm using my own modpack with many mods but I hope you can help me. 
My problem:
I open the Crafting Terminal and wanna autocraft something. I click on it and instantly the terminal closes. Yesterday I destroyed every AE2 blocks and rebuilded it, then it was working again. 
Now I tried again and it works! After that I left the world and rejoined and now the same problem. I have enough energy, but I don't know, what's the reason. I use a ME-Controller and a Capaciter Bank from EnderIO for energy.

**Comment by mindforger** [comment]
try without wireless crafting mod
but still install an energy cell or two, the ME system can only accept as much RF per tick as it can contain in this one tick

**Comment by MelanX** [comment]
Yes, it worked. Thank you very much! 
But is oh a problem by Applied Energistics or by Wireless Crafting Terminal? Is this issue important for you or for they?

**Comment by mindforger** [comment]
*points on Wireless Crafting Terminal* ... they need to deal with that or contact AE2 devs for help if they can't solve it ... probably nobody has ever reported it to them despite us hinting to do so numerous times
