### ISSUE TITLE
[1.12] Inscriber Issue

### ISSUE THREAD

**Issue by ridvanonal** [AppliedEnergistics/Applied-Energistics-2#2998]
Inscriber give random processor, especially I inscribe logic press, it give me engineer processor

**Comment by trilexcom** [comment]
hi We are having the same issue on our modpack

**Comment by Boqzo1** [comment]
Same problem, same AE version, Forge 2426

**Comment by jbhitman** [comment]
Same issue here.  
Forge 2415, 
AE: rv5-alpha-1

**Comment by xMrWolfx** [comment]
Same problem here
Forge Version : 2443
AE version : rv5-alpha-1

**Comment by mindforger** [comment]
Please refrfain from posting useless "same here" comments over and over ... it is enough that 3 people reported it, but can please at least two of the 5 reporting people do us a favor, go into the game, press and hold F3 + C until the client forcibly crashes and post their crash report to have a bit insight and crosschecking about the mods used? 
none of you yet has posted if this happens with AE2 alone or with any other mods present 

also please try to reproduce with AE2 alone ... but i believe i have already seen a PR beeing worked on mentioning the inscriber and some odds in the slots

**Comment by xMrWolfx** [comment]
@mindforger I am sorry about that I am new to GitHub and I was trying out features but here is my crash report **https://pastebin.com/17dJd5B8**

**Comment by mindforger** [comment]
okay that is number one .. and as far as i can see nothing present that deals with AE2 in any way yet (like addons) .. now a second report please (with hopefully  lesser mods XD) or can you reproduce this issue with AE2 only (or way less other mods) but keep the configs first to test and then delete configs to see if issue persists ... could be a broken config that all of you are sharing through a modpack eventually

**Comment by yueh** [comment]
Already fixed with #2995

**Comment by mindforger** [comment]
i knew i had seen it somewhere :P

**Comment by xMrWolfx** [comment]
Just a question is there a update that is going to fix it?

**Comment by GuntherDW** [comment]
There should be a build either somewhere today or tomorrow. I'm waiting on a response from someone, but if that takes too long a build will probably come out sometime today?
