### ISSUE TITLE
Certus Quartz Knifes With Autocrafting

### ISSUE THREAD

**Issue by Tigercraft01** [AppliedEnergistics/Applied-Energistics-2#2999]
I have set up autocrafting in my world and it all works but every time I craft a processor it is making a new cutting knife rather than just using one that is already made. I am sure this is an easy fix but I cannot see what it is.

Modpack:
SkyFactory 2.5
Minecraft version:
1.7.10

**Comment by CrossVas** [comment]
Hey!!

When you encode your craft, try to allow OreDict substitution of input components.
So, if you request an item which use Cutting Knife in his craft, AE system will not craft a new Knife, but will use the previous one.

Ex:
![image](https://user-images.githubusercontent.com/25727222/28869592-e7fab5b8-7785-11e7-8a6c-79e64782a158.png)

**Comment by Tigercraft01** [comment]
Hey,

It works now thank you very much. I wasn't sure what that button did so I haven't clicked it for anything.

Thanks again. :+1:
