### ISSUE TITLE
After clicking to autocraft, Client crashes.

### ISSUE THREAD

**Issue by Nobelz** [AppliedEnergistics/Applied-Energistics-2#3001]
#### Description

So I was testing out my new auto-craft system by crafting a chest. I selected the number I wanted to craft (1) and when I got to the CPU screen, when I clicked "Start," the client crashes. This has happened 2 out of 2 times. When I log in again, the item is crafted, but the energy acceptor (converts RF from Enderio 3 vibrant capacitor banks to AE) is broken or missing. This has happened in the past (The energy acceptor disappearing, that is) so I do not think it is related to the crash. 

Transporting RF using resonant fluxduct (Thermal Dynamics)
Transporting AE using ME Glass Cable at first, then ME Dense Cable
Have Controller, ME Crafting Terminal, Me Security Terminal, Wireless Access Point, 2 ME Drives, 2 ME Chests
Have 64k Crafting Storage, Crafting Monitor, and Crafting Co-Processing Unit

#### Environment

- Minecraft Version: 1.7.10
- AE2 Version: v2 stable build 10
- Forge Version: 10.13.4.1614
- Ender IO Version: 2.2.8.381

List of Mods (Using Custom Modpack) Here:
https://pastebin.com/ze8icxeb

No Client Crash Reports.

Although there is an error popping up server side, it does not close.
Server Error Information (Error highlighted):
https://pastebin.com/c3zKPMki

**Comment by Nobelz** [comment]
I have noticed that this is very close to #2997, but my client crashes instead of just closing.

**Comment by mindforger** [comment]
>client crashes
>No Client Crash Reports

this is some inconsistency in your report that i do not understand :)

you either have client crashing and a resulting crash report or your JVM is crashing hence you won't get a crash report ... can you check your client logfile and paste the last 200lines (or less, depends if there are traces of crashing in it that are huge or tiny) to pastebin or similar?

**Comment by yueh** [comment]
We no longer support 1.7.10 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
