### ISSUE TITLE
Inscriber Recipe Issue

### ISSUE THREAD

**Issue by bluev1121** [AppliedEnergistics/Applied-Energistics-2#3004]
Inscriber returns Logic Circuits when Engineering Circuit recipe is provided
#### Description

Inserted  engineering Circuit recipe into an Inscriber both Manually, and with automation, and received Logic Circuits as a crafting result.

#### Environment
 
Updated the mod from RV5 Llamagistics to RV5-Alpha1 of Applied Energistics

Will provide a modlist if asked.

No relevant crashlogs

- Minecraft Version: 
- AE2 Version:  RV5-Alpha-1
- Forge Version: 14.21.1.2424

**Comment by GuntherDW** [comment]
Duplicate of #2998
