### ISSUE TITLE
Inscriber not working right

### ISSUE THREAD

**Issue by thebongolest1206** [AppliedEnergistics/Applied-Energistics-2#3005]
When putting just the item that is needed to craft a printed press it crafts it. The actual press its self is not needed. And when putting a piece of redstone and a printed silicon it crafts a logic processor with nothing else in the inscriber. 

#### Description
When you put in, lets say, a gold ingot into a powered inscriber, it crafts a printed logic circuit without needing the right kind of press. And when putting in a piece of redstone and a printed silicon into an inscriber it makes a logic processor without even putting in anything else. 

#### Environment
Single player
No crashes
All The Mods 3 with added mods - Will elaborate if needed
Minecraft version - 1.12
Ae2 version - Rv5 Alpha 1
Forge version - 12.21.1.2428

**Comment by GuntherDW** [comment]
Duplicate of #2998
