### ISSUE TITLE
Last one got closed, tried it in a different instance with no other mods

### ISSUE THREAD

**Issue by thebongolest1206** [AppliedEnergistics/Applied-Energistics-2#3006]
When putting just the item that is needed to craft a printed press it crafts it. The actual press its self is not needed. And when putting a piece of redstone and a printed silicon it crafts a logic processor with nothing else in the inscriber.

Description

When you put in, lets say, a gold ingot into a powered inscriber, it crafts a printed logic circuit without needing the right kind of press. And when putting in a piece of redstone and a printed silicon into an inscriber it makes a logic processor without even putting in anything else.

Environment

Single player
No crashes
No other mods other than JEI
Minecraft version - 1.12
Ae2 version - Rv5 Alpha 1
Forge version - 14.21.1.2443

**Comment by GuntherDW** [comment]
Duplicate of #2998
