### ISSUE TITLE
Crank not lined up with Quartz Crusher in 1.12

### ISSUE THREAD

**Issue by RepoDraghon** [AppliedEnergistics/Applied-Energistics-2#3008]
[YouTube vid of issue](https://youtu.be/ZiaNxgWeFaY)

- Minecraft Version: 1.12
- AE2 Version: rv5-alpha-2
- Forge Version: 14.21.1.2443

**Comment by tyra314** [comment]
I've done a bisect on this issue, and this seems to be a regression of the commit 5e001d86cbebe7aaef04c4782f63017b2c3598d1 or #2994  

Also, a picture of the issue: 
![2017-08-06_11 51 43](https://user-images.githubusercontent.com/16997177/29002300-83dfe842-7a9f-11e7-8efd-dd7c9f25a419.png)
