### ISSUE TITLE
Crash with gravity gun/ portal gun

### ISSUE THREAD

**Issue by Trinsdar** [AppliedEnergistics/Applied-Energistics-2#3010]
#### Description
Crashes whenever trying to pickup a me drive.
#### Environment
crash log: https://pastebin.com/2YCSUZnP

- Minecraft Version: 1.10.2
- AE2 Version: rv4-stable-1
- Forge Version: 1.10.2-12.18.3.2316
- GravityGun-1.10.2-6.0.1
- PortalGun-1.10.2-6.0.1
- iChunUtil-1.10.2-6.3.2

What was expected:
Expected to pick up the me drive with the portal gun or gravity gun, but instead it crashed.

How to reproduce:
Use a portal gun or gravity gun to pickup a me drive.

**Comment by mgdgfbhevdyeh** [comment]
> -- Block model being tesselated --
Details:
    Block: appliedenergistics2:drive
    Block location: World: (-240,70,248), Chunk: (at 0,4,8 in -15,15; contains blocks -240,0,240 to -225,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Using AO: false
Stacktrace:
    at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:46)
    at me.ichun.mods.ichunutil.client.render.entity.RenderBlock.doRender(RenderBlock.java:103)
    at me.ichun.mods.ichunutil.client.render.entity.RenderBlock.func_76986_a(RenderBlock.java:28)
> 
I think this is the gravity gun / portal gun rendering problem.
Try the Github report on the gravity gun / portal gun.
and try referenced both sides Isseus.

**Comment by yueh** [comment]
Yes, it looks like the gravity/portal gun does not pass the whole blockstate to the render.

Safe guarding would certainly be an option, but in general it should reported to this mod as we are probably not the only one being affected.

**Comment by Trinsdar** [comment]
Already reported it to the Ichun github
