### ISSUE TITLE
Placing last ME Cable offhand clears main hand also

### ISSUE THREAD

**Issue by Vovan-VE** [AppliedEnergistics/Applied-Energistics-2#3011]
#### Description
Take any ME Cable offhand and anything in mainhand (pickaxe or torches in my case). When so you placing a block and main hand item cannot be placed (either only currently here nor anywhere at all), the offhand cable will be placed. So, when placing the last cable from offhand stack, main hand slot bacame completely empty too.

#### Environment
FTB Beyond 1.10.0. Single player survival.

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-11
- Forge Version: 12.18.3.2316

**Comment by GuntherDW** [comment]
Confirmed bug, looking at this for the 1.12 version.
