### ISSUE TITLE
Crafting recipe gone from system, while still in interface

### ISSUE THREAD

**Issue by Lilylicious** [AppliedEnergistics/Applied-Energistics-2#3015]
I have a moderately extensive network, with four molecular assemblers with four interfaces each. The entire network is chunkloaded, has no power issues, and there are no channel issues. Each of the two 8 channel cables go into a dense cable, which goes straight into a controller. The dense cable has 28/32 used channels.

I have a large crafting request, which is included in the screenshots. This request includes furnaces. According to the main system, furnaces are not autocraftable. They do not show up when searching the system, unless there's one already in.

Searching the interface terminal, I can see the furnace recipe. Still doesn't show in the main system. If I go to the interface itself, I can see the recipe. If I remove the recipe and add it back into the interface, it reappears in the system and can be used in autocrafting.

This is the second time this has happened, with two different recipes. Can't remember what item the first one was.

Summary: Crafting recipe in an interface on a molecular assembler does not appear in the main system, unless the recipe is removed and put back in. 

This happened in a singleplayer world, in a mining dimension, using the pack Age of Engineering.

I have no idea how to make it happen, nor what the possible cause could be. I think I've eliminated any error on my part (cabling issues etc), though.

Screenshots:
[Crafting Request](http://i.imgur.com/4DXpLe4.png)
[Empty search for furnace](http://i.imgur.com/IdR98LH.png)
[Presence of the furnace pattern](http://i.imgur.com/MF0MXii.png)

In the second screenshot I was using the wireless crafting terminal 2 mod, but the same issue happens even in the terminal block from vanilla AE2.

- Minecraft Version: 1.10.2
- AE2 Version: RV4-Stable-1
- Forge Version: 12.18.3.2316

**Comment by Lilylicious** [comment]
Since it isn't hard to fix in the game, I'm going to keep everything as it is and see if I can make it happen again. Hopefully I'll figure out how to reproduce it, so I can give you something solid to go on. If I can reproduce it, I'd also be able to eliminate or confirm the WCT as the culprit.

**Comment by Delegold** [comment]
was this ever resolved? having the exact same issue on 1.7.10 with Project Ozone 2. :( 
i would greatly appreciate a helping hand here
