### ISSUE TITLE
game crash if QuartzKnife is disabled

### ISSUE THREAD

**Issue by DerBaM** [AppliedEnergistics/Applied-Energistics-2#3024]
If you disable the QuartzKnife in the configuration _B:QuartzKnife=false_ the game crashes on load.

- Minecraft Version: 1.12
- AE2 Version: rv5-alpha-2
- Forge Version: 14.21.1.2426

[crash-2017-08-11_12.16.50-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1217583/crash-2017-08-11_12.16.50-client.txt)

**Comment by GuntherDW** [comment]
This is due to the recipes again.
They currently only take into account "Material" or "Part" like the Ender Pearl dust not existing.
Not configs (at least right now). That is something that I still need to implement indeed.

**Comment by GuntherDW** [comment]
Why did you close the issue already? It's a legit bug that I have to take a look at.

**Comment by 3TUSK** [comment]
Not sure what's wrong exactly but [my crash-report](https://paste.ubuntu.com/25662836/) implies that this issue still somehow persists. [The config used that produces this crash](https://paste.ubuntu.com/25662845/) has `B:CertusQuartzTools=false` but left `B:QuartzWrench=true`.  

AE2 with version `rv5.alpha build 6` is used. MinecraftForge 14.23.0.2493 is used. Other mods used can be found at the end of crash-report.
