### ISSUE TITLE
dupe any item

### ISSUE THREAD

**Issue by ArtBorax** [AppliedEnergistics/Applied-Energistics-2#3031]
Dupe through the terminal templates.
It is necessary to build a minimal system as in the screenshot.
http://clip2net.com/s/3MWJhrp
http://clip2net.com/s/3MWJjfl
Then put the object in the craft and hold the space key, click on the encoding button and the result of crafting, the space does not need to be released, and so do one by one.
Working MP/SP, only forge server or sponge server.

Minecraft Version: 1.10.2
AE2 Version: appliedenergistics2-rv4-stable-1.jar (last)
Forge Version: forge-1.10.2-12.18.3.2422

**Comment by yueh** [comment]
Cannot reproduce.

**Comment by mindforger** [comment]
while ingame, press and **hold** f3+c to force a crash and attach crashlog posted via pastebin or attached as file to get insight on other installed mods

**Comment by ArtBorax** [comment]
http://mcborax.ru/CrashAndVideo.zip
only video https://youtu.be/P38Bfw8C4t0

**Comment by mindforger** [comment]
wow .. okay i was honestly expecting any of the mousetweaks, inventorytweaks and other mods installed that maybe causing this
