### ISSUE TITLE
SpatialIO doesnt respond, crashes game on save.

### ISSUE THREAD

**Issue by Zendrex** [AppliedEnergistics/Applied-Energistics-2#3036]
It seems that SpatialIO doesnt work in r5 (which i expected). I have learned that when trying to use the system and interact with a ready-made SpatialIO system, its non-responsive. It doesnt crash the game when you trigger redstone on the io port or anything. It just does nothing. However, when you try to save and exit to main menu, you crash and below is the error log.

- Error: https://pastebin.com/VJtFmkDZ
- Minecraft Version: 1.12
- AE2 Version: rv5 alpha 2
- Forge Version: 14.21.1.2443

**Comment by GuntherDW** [comment]
As discussed this is not fixed in that pull. We have to make a change or 2 in the code before it is fixed.
