### ISSUE TITLE
Wooden Crank

### ISSUE THREAD

**Issue by TheSnowyChickens** [AppliedEnergistics/Applied-Energistics-2#3037]
Hello
The wooden crank is missplaced , the pictures say all I think . :)
(The grinder still work)

![2017-08-17_04 34 04](https://user-images.githubusercontent.com/29357962/29393658-5c7f77cc-8305-11e7-9649-1019e571765e.png)

![2017-08-17_04 34 06](https://user-images.githubusercontent.com/29357962/29393661-5f739206-8305-11e7-91be-bcfab1973e6f.png)

![2017-08-17_04 34 08](https://user-images.githubusercontent.com/29357962/29393664-61e6f14a-8305-11e7-8d53-fe2eb49fe117.png)

MC : 1.12
Forge : 2443
AE2 : rv5 - alpha-2

**Comment by yueh** [comment]
#3008
