### ISSUE TITLE
AE2 channel usage and WAILA tooltip

### ISSUE THREAD

**Issue by daantimmer** [AppliedEnergistics/Applied-Energistics-2#304]
Hello there,

For some reason, WAILA is displaying channel usage while in a singleplayer test world, but when I am on my private server it somehow doesn't display channel usage.

(Goes for Smart cables and Dense cables). Other information like is a device connected or not is shown in the WAILA tooltip.

This has been happening with RV1 stable 1 as well as with RV2 alpha 7.

Is this a bug? A feature? Or am I missing some configuration settings on client/server side?

**Comment by TheJulianJES** [comment]
Finally!
