### ISSUE TITLE
Can't open Minecraft

### ISSUE THREAD

**Issue by Dragon-Magician** [AppliedEnergistics/Applied-Energistics-2#3052]
I can't open Minecraft modded when I have applied energistics 2 in my mods folder. I am on 1.7.10 and I am using the file appliedenergistics2-rv3-beta-6.jar which is the latest for 1.7.10. Any Help?

**Comment by Elvarion** [comment]
Pretty hard to help you when you ain't very helpful to begin with :(
Id suggest you take a look at the information that is written when you make an Issue.
