### ISSUE TITLE
|1.12| problem when disabling chans system.

### ISSUE THREAD

**Issue by Bass2style** [AppliedEnergistics/Applied-Energistics-2#3057]
#### Description
Hi, when disabling the Chanels system in the config, the controller and the covered cables dissapears from the game, that whas intended, but now, it's impossible to craft the glass cables, they are present in JEI, but, the craft is disabled.

#### Environment
no specific environment, crafting issue.

- Minecraft Version: 
- AE2 Version: appliedenergistics2-rv5-alpha-3
- Forge Version: 14.21.1.2443

**Comment by yueh** [comment]
This is essentially a "feature" of the new recipe system in minecraft forge. Once a single recipe of a mod is invalid due to a missing item, it will all recipes for this mod.

For now the only option would be providing your own resource pack for it.
