### ISSUE TITLE
Patterns disappearing in RV4-Stable 1 in Interfaces.

### ISSUE THREAD

**Issue by Furious1964** [AppliedEnergistics/Applied-Energistics-2#3059]
Losing my patterns and Interfaces seem to only want to hold 3 patterns.

Just updated to RV4-Stable 1 from Alpha11 because of this and it's still happening.

- Minecraft Version: 1.10.2
- AE2 Version: RV4 -Stable 1
- Forge Version: 12.18.3.2422
- FTB Version: 3.0.13

I might have stumbled onto something: I have 16 Interfaces with 5 Molecular Assemblers attached. When I put patterns in the first 4 Interfaces, my patterns disappear. But when I skip those and put patterns in just the other 12 Interfaces...I don't lose any patterns.

**Comment by Furious1964** [comment]
So I've found where the problem originates: the dense cable can't handle more than 12 Interface Channels on it. Any more Interfaces added to it with start deleting the patterns in them.

Doing more testing.

**Comment by Furious1964** [comment]
It seems that AE2 can't handle 12 Interfaces on the same dense cable and 18 Interfaces total on the entire system.

**Comment by fscan** [comment]
Can you please send a screenshot of the setup?

**Comment by Furious1964** [comment]
![2017-08-27_14 06 51](https://user-images.githubusercontent.com/2803725/29752773-26079de8-8b32-11e7-9aa1-19806f0c9062.png)

This is with just Forge and AE2.

![2017-08-27_11 49 53](https://user-images.githubusercontent.com/2803725/29752782-493ee988-8b32-11e7-9095-c968b1021e2c.png)
![2017-08-27_11 50 14](https://user-images.githubusercontent.com/2803725/29752784-49426892-8b32-11e7-8a91-b2db8af2c2e2.png)
![2017-08-27_11 57 54](https://user-images.githubusercontent.com/2803725/29752783-494092a6-8b32-11e7-838b-dd8b0f96bc34.png)
![2017-08-27_11 58 20](https://user-images.githubusercontent.com/2803725/29752785-4942f898-8b32-11e7-8459-02ad6622c8ce.png)

The next 4 are with the mods I have. All the newer testing was done with mods on. Testing with mods off seems to reveal strange results...

**Comment by Furious1964** [comment]
Still doing more testing to narrow the problem down and I found that it might also involve the AE2 ME system loading and registering all of its components. If I wait long enough to access the system, patterns remain the same...but the more patterns/interfaces you have, the more time you have to wait.

**Comment by Furious1964** [comment]
Does this mean you found the problem and there will be a fixed version soon?

**Comment by fscan** [comment]
Let's say it does fix the problems i could reproduce. There's still some weird interaction with InvTweaks/MouseTweaks but no patterns should be lost.

**Comment by Furious1964** [comment]
I've never noticed that. Maybe it's because those two mods think that the inventory of AE2 can be manipulated by it.
