### ISSUE TITLE
Smart Cables not connecting to Dense Cables

### ISSUE THREAD

**Issue by rolltide0** [AppliedEnergistics/Applied-Energistics-2#3060]
#### Description

Watching several how to videos I see people connecting smart cables to dense cables, however when i try it they won't connect. I can connect glass cables but not smart cables. 

I checked the documentation on this site and it also states this should be possible. Also checked the current issues with dense cable and I did not find this issue, so I apologize if this is a dupe submission.

#### Environment

- Minecraft Version:  FTB Beyond 1.10
- AE2 Version:  rv4-alpha-11
- Forge Version: 12.18.3.2316

**Comment by GuntherDW** [comment]
Are the cables the same color? Fluix cables are a wildcard but other than that the color should be the same.
Colored cables are used to segregate a network, hence they won't just connect to each other.

Could you post a screenshot of said cables otherwise?

**Comment by rolltide0** [comment]
My bad. I didn't realize that the color of the cables meant something. I tried it using like colors and it worked without any issue. Thanks for the help!!
