### ISSUE TITLE
Planning for rv5/rv6 API 

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#3066]
We are currently starting to wrap up the rv5 API to move it to a beta state.

Currently there are still a few larger things to do like #1480. Most of them should not affect addons in a large way. Most should require a minor or moderate amount of work. But it would certainly make the next rv incompatible with existing addons once the start moving to 1.12.

The option now would be to move quickly to a beta stage and postpone  the larger changes to rv6. Maybe even move to a beta within the next 2 or 3 weeks.

Or take some more time for larger changes and push back a beta release for a longer time. Which is probably not the best idea, even if it would make porting easier for addons as it would be only one step.

This also gives the opportunity to request changes/features for rv5 or rv6 for addon devs.
So if you have some ideas, open a new issue for it. Please do not use this one for it to avoid having to deal with 10 different discussion. This is just about a wrapping up rv5 faster or slower.

Changes like the part interactions can certainly make it into rv5, if requested and we maybe have some more people testing it quickly.

Some ideas are propably off the table like adding fluids (or even other things) to the autocrafting, as this is already extremely complex and can easily break down. At least for rv5 and probably rv6. Maybe after these, but there are more important changes to do before touching it.

Pinging some devs, who were at least somewhat active in the past weeks. Sorry, in case you do not plan to move to 1.12 or cannot due to some other mod missing. But just in case. Should I have forgotten anyone, feel free to ping them.
@Nedelosk @p455w0rd @Mordenkainen

**Comment by Ommina** [comment]
@bdew presumably, whose Jul26 post says "currently undecided".  If nothing else, this may help him decide on way or another.

**Comment by Mordenkainen** [comment]
I will take a look if I can, but at the moment I'm still stuck at 1.7.10 and haven't had time to wrap my head around the stuff needed to update like block rendering and capabilities. That said, I will try to find the time to at least browse through the API to see if I think it covers what I need!

**Comment by yueh** [comment]
That will be quite a jump from 1.7.10 to 1.12, should there be EE3 or ProjectE for it. But maybe easier, as the transition between 1.8, 1.9, and 1.10 did cleanup a bit of the rendering and should make it easier (but not really the multipart stuff for parts...). 

Parts already support caps, it is pretty much identical minus the side parameter as parts itself are inherently sided. The older `LayerBase` still exists, but maybe we scrap it at some point. Caps certainly have issues, but it is for sure way more sane than transforming classes at runtime.

The API is still pretty similar to rv3. If you miss a feature there, it probably is still missing.

**Comment by bdew** [comment]
Honestly i haven't looked at 1.12 (for AE2Stuff) much yet, so i don't have any useful input at the moment... hopefully i'll get to it soon (tm).
