### ISSUE TITLE
Missing Block Model/state/texture for Charged Quartz Ore

### ISSUE THREAD

**Issue by kenijey** [AppliedEnergistics/Applied-Energistics-2#3068]
![2017-09-02_15 17 12](https://user-images.githubusercontent.com/24831406/29995433-ea8b06dc-8ff1-11e7-9cf9-8252d7c15eca.png)
mc 1.12 forge 2443 AE2 rv5 a4

**Comment by fscan** [comment]
I'm not in the mood of guessing games right now. Can you please at least provide a log file? Also, this looks like a custom resource pack .. try without it.

**Comment by kenijey** [comment]
oh i'm so sorry about it, yes it's all about the resource pack. sorry :(

**Comment by kenijey** [comment]
oh no it's not about the resourcepack, it happens in my modpack. dunno what causes..
if u want to take a look, it's [here.](https://github.com/kenijey/Ezteria)

**Comment by leagris** [comment]
@kenijey 
1. Try without Optifine
2. Stop breaching mod distribution licenses https://github.com/kenijey/Ezteria/tree/master/mods

**Comment by kenijey** [comment]
which licence? i'm just using github to upload my modpack faster instead of uploading hole the pack to dropbox with my slow internet. i'm not gaining money or something else, and i linked it to you to get help
...

**Comment by leagris** [comment]
> which licence? i'm just using github to upload my modpack

Uploading mods on Github is public redistribution and on a publicly accessible website here:
https://github.com/kenijey/Ezteria/blob/master/mods/OptiFine_1.12_HD_U_C5.jar

I mention issue with Optifine because it is one of the mods with the strictest redistribution restrictions.

[Optifine Copyright](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1272953-optifine-hd-c2-fps-boost-dynamic-lights-shaders)
> The mod OptiFine is Copyright © 2013 by sp614x and the intellectual property of the author. It may be not be reproduced under any circumstances except for personal, private use as long as it remains in its unaltered, unedited form. **It may not be placed on any web site or otherwise distributed publicly without advance written permission**. Use of this mod on any other website or as a part of any public display is strictly prohibited and a violation of copyright.
