### ISSUE TITLE
Grid Crashing when using AE2, Quark and colossal chests

### ISSUE THREAD

**Issue by Akitori** [AppliedEnergistics/Applied-Energistics-2#3070]
[crash-2017-09-02_15.51.43-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1272525/crash-2017-09-02_15.51.43-server.txt)

So the bug i have is after pulling out a few items using Ae2, I usually like to sort things using Quark's sort function. So, my expected behavior is this:

Click sort. Get more space in chests and organize it neatly.  Dats it.

What i got however, on more than one occasion.

Use ae system (basic setup of storage bus, energy displacer and a terminal) and shove some items in/out.
Go to colossal chest and click quark's sort button.

Crash. Usually happens only on server. 

This is using forge version 14.21.1.2420 on servers and clients. This is for minecraft 1.12 (not 1.12.1) and its using rv5 alpha 4 of AE 2

**Comment by ouroborus** [comment]
@Akitori Quark's sorting doesn't properly handle exceptionally large slot counts (though, usually, it just kills the connection rather than crashing anything). AE2 doesn't have any control over that. Colossal Chests just makes Quark's issue apparent.
