### ISSUE TITLE
Items default to "Pure Certus Quartz" when crafting from NEI

### ISSUE THREAD

**Issue by i00** [AppliedEnergistics/Applied-Energistics-2#3073]
#### Description
When crafting some things, such as the 1K storage, when bringing the items across from the NEI recipe they default to use "Pure Certus Quartz"...

My suggestion would be to remove this completely from crafting recipes that require only normal quartz; this would prevent people wasting this valuable resource on things that don't require it.

#### Environment
- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha11
- Forge Version: 8.0.99.99

**Comment by Ommina** [comment]
Er, opposed.  Maybe it's because I build the growth accelerators before anything else, but I would find the loss of the doubling mechanism of the Pure lineup quite distressing.  (And would custom recipe it right back in regardless.)

**Comment by yueh** [comment]
No, as @Ommina said you request it should prefer the more valuable one.

**Comment by i00** [comment]
Sorry @yueh ... but why "should *it* prefer the more valuable one."?

Kris

**Comment by fscan** [comment]
He said "**you** request it should prefer the more valuable one"
As in normal quartz is more valuable .. because you know 1 quartz = 2 pure quartz .. math.
