### ISSUE TITLE
Cables/bus's(and occasionally drives) can be deleted randomly from chunks

### ISSUE THREAD

**Issue by Makeshift** [AppliedEnergistics/Applied-Energistics-2#3074]
#### Description
We have a RFtools void world containing pretty much only a (reasonably mid-game, so fairly large) AE system plus assorted other machines that it interacts with. Every 6 or so hours when everybody exits the world, the world is unloaded. When the world is loaded again, between 2 and 6 chunks will be missing ALL their cables/buses and occasionally their drives. These can be traced to certain chunk boundaries, but it doesn't seem to matter if the chunk is particularly busy. We've had a chunk which simply had 4 import bus's in it plus their cables be removed.

Leaving this chunks loaded by use of tools does not seem to help. When a player enters, occasionally all cables/drives/buses are destroyed. (Note by destroyed I mean removed, but the items do not drop) All actual 1x1x1 "blocks" stay, such as the ME controller and drive bays, but items that do not use a full block such as cables and buses are removed. Is this perhaps related to their NBT tags?

There are no server errors, and occasionally if players move fast enough from our teleport area they can see all the cables explode (with the glass shattering noise).

#### Environment

- Minecraft Version: 1.12.1
- AE2 Version: rv5-alpha-3 (Am aware alpha-4 has been released but can't see a possibly related change in the log for this bug)
- Forge Version: 14.22.0.2456
- Modpack: [FTB Unstable 2.0.1](https://www.feed-the-beast.com/projects/ftb-unstable-1-12/relations/dependencies) (Yes, I know it's the unstable version, but as this is only affecting AE I thought it was relevant)
- Multiplayer server running on an Ubuntu server with Java 8, 4 cores, 12GB ram and about 10 regular players.

**Comment by fscan** [comment]
>... as this is only affecting AE ...  

Are you 100% sure that when this happens no other machine in the chunk has it's NBT data reset? Things like machine side configurations, stored power, etc?
Can you reproduce this in a chunk **only** containing AE2 parts/blocks?

> chunks loaded by use of tools 

What mod are you using for chunk loading?

**Comment by Makeshift** [comment]
It does seem to only be AE that's affected. It just happened again and no RFTools, YABBA barrels, Multi-Storage items were affected. Unfortunately we didn't have any Thermal Dynamics systems in those chunks but since those chunks seem to be the most affected I'm going to move a couple into there just to see if the machines are affected next time.

We tried using FTBU's team based chunk loading to try and keep it loaded, but it didn't help.

**Comment by Makeshift** [comment]
Apologies, it does seem to be deleting all NBT data for other items as well, such as thermal expansion machines etc. It doesn't look like this is an AE specific issue. Closing.
