### ISSUE TITLE
Some Bugs

### ISSUE THREAD

**Issue by Bircko** [AppliedEnergistics/Applied-Energistics-2#3076]
I can't right click with item in crafting terminal to lay only one item inside the crafting terminal.
Shift-left click to produce a stack of a item cause server lags even in a lan server.

- Minecraft Version: 1.10.2
- AE2 Version: appliedenergistics2-rv4-alpha-11.jar
- Forge Version: forge-12.18.3.2316

**Comment by Bircko** [comment]
Okay Updatet to rv4-stable-1 but both issue still exist only the half of the first issue fixed with the update, cause i still can't lay single items in pattern terminal

**Comment by fscan** [comment]
Can you try without MouseTweaks?

Regarding the crafting lag, this is a known issue with newer Minecraft versions (for me even the Tinkers crafting table lags). It's a lot better in the 1.12 build.

**Comment by GuntherDW** [comment]
If you have mousetweaks installed you should disabled the "RMBTweak" in the Mod Options page indeed. There is an interaction bug between the 2 mods.

**Comment by fscan** [comment]
And it seems to me it's not only with AE2. Right clicking into the world when in the inventory to drop 1 item from a stack also doesn't work when RMBTweak is enabled.
