### ISSUE TITLE
ME Annihilation Plane Upgrades

### ISSUE THREAD

**Issue by m3awardr** [AppliedEnergistics/Applied-Energistics-2#3079]
#### Description
I had an idea when I was playing Minecraft and farmed some new ore in my world (Draconium Ore) with my Ender Quarry, which supports SilkTouch mining.

The problem with this ore (and others like e.g. Redstone) is that it needs to be broken. And let's face it, we want the result to be most efficient, which simply isn't with SAG Mills or Pulverizers. So I thought: 

Why not share the idea of Upgrade-Chips for the ME Annihilation Plane to make it more attractive?

It could support:
   - Silk Touch
   - Luck 1-3
   - Range Upgrades 

#### Environment

Console.println("NO CRASHLOG FOUND");

- Minecraft Version: 1.7.10
- AE2 Version: rv3-beta6
- Forge Version: Forge10.13.4.1614

**Comment by yueh** [comment]
Silk touch is already possible. Range, too. At least in 2 axis. The third is pretty useless without moving them and it will not work with all features. And when moving them, range it this direction is also getting unimportant.

This leave the luck option and that is simply not a goal for AE2. This should be left to other mods with various mechanics.
