### ISSUE TITLE
[Suggestion] Single colour crafting

### ISSUE THREAD

**Issue by TheSnowyChickens** [AppliedEnergistics/Applied-Energistics-2#3080]
Hello
Since the 1.7.10 Version I miss a single crafting recipe for all kinds of the cable colours.
I dont like it to craft 8 new one , if I need just 1 .

I hope you can do there something , I would rly appreciate it. :)
Thx.

- Minecraft Version: 1.12.1
- AE2 Version: rv5.alpha build 4
- Forge Version: 1.12.1-forge1.12.1-14.22.0.2475

**Comment by Ommina** [comment]
Since I had a 1.7.10 world open, I took a peek there, and there were no single-cable recipes, which leaves me believing that they are not available by default.

That said, if the developers do not wish to add them into the vanilla install, you can certainly add them yourself as a custom recipe.

**Comment by yueh** [comment]
Use a Color Applicator.
