### ISSUE TITLE
What type of entity is charged quartz item?

### ISSUE THREAD

**Issue by donqixot** [AppliedEnergistics/Applied-Energistics-2#3083]
#### Description
I can't seem to identify what type of entity is charged quartz item when dropped on the ground. Most (if not all) items when dropped on the ground are @e[type=item], but not charged quartz. For instance, following command has no effect on charged quartz item:
/tp @e[type=Item,r=10] @p

If I use entitydata command, I can see following tag: Item:{id:"appliedenergistics2:material",Count:1b}, so I tried [type=material] or [type=appliedenergistics2:material], still no effect.

I realized this is probably to prevent this item from despawning, but very curious what qualifier inside @e[type=???] can I use?

#### Environment
- Minecraft Version: 1.12.1
- AE2 Version: rv5-alpha-4
- Forge Version: 1.12.1-14.22.0.2475

**Comment by leagris** [comment]
Did you try:
```command
/tp @e[id="appliedenergistics2:material",r=10] @p
```
?

**Comment by donqixot** [comment]
Yes, I did, I am getting
Invalid selector argument: 'id="appliedenergistics2:material"'

**Comment by yueh** [comment]
Charged certus has its own entity. The same applies to seeds. I have absolutely no idea how the selector for the vanilla commands works. But the entities are simply registered under their name `EntityChargedQuartz` plus probably the mod id appened/prepended by forge. But the forge docs are as usually outdated and might be completely wrong, So it might no longer used the explicitly assigned name by us...

IIRC there was a command to display all data of an entity. So maybe just droping one and limit the selector to a specific range might print the data including their name/id to the chat.

**Comment by donqixot** [comment]
Thank you very much. So it is custom entity, I should've realized, summon command would tell me possible type. So this worked:
/tp @e[type=appliedenergistics2:appeng.entity.entitychargedquartz,r=10] @p,

for seeds, I would use
/tp @e[type=appliedenergistics2:appeng.entity.entitygrowingcrystal,r=10] @p

There is third entity - singularity, it will need this command:
/tp @e[type=appliedenergistics2:appeng.entity.entitysingularity,r=10] @p
