### ISSUE TITLE
Interface pattern dupe

### ISSUE THREAD

**Issue by TheSnowyChickens** [AppliedEnergistics/Applied-Energistics-2#3093]
Hello
first off all , I only can discribe this bug , because I dont have some logs or other.

So , in the Picture you can see 2x the same line with the same pattern . Myself create only once of this and the other one was stocked with repices from thermal dynamics. (like super-Laminar Fluiducts or hardened fluiducts)

![grafik](https://user-images.githubusercontent.com/29357962/30511614-4a0e0f1e-9add-11e7-9d94-04e3ee618687.png)

In the second picture you can see how I build the autocrafting modules (installed with black Dense cables).

![interfaces](https://user-images.githubusercontent.com/29357962/30511912-36cac4d2-9ae3-11e7-9fcb-7939f0cff8a6.png)

So , now something that I do in the time .
-I restarted the game often
-I put the pattern in the interfaces by the interface Terminal
-I sortet the patterns with the terminal
-I updated some other mods (Reborn Core , Chisel)
-reconnect the connection often (from the cable)
-design my base

I hope you can do something with this informations . Ask me if you need more , then I try to find more :D

- Minecraft Version: 1.12.1
- AE2 Version: appliedenergistics2-rv5-alpha-4
- Forge Version: 1.12.1-forge1.12.1-14.22.1.2478

**Comment by yueh** [comment]
With forge being unable to guarantee stable and uncorrupted data, there is no option for us to prevent and/or fix it in any case.
