### ISSUE TITLE
Console Spam and Server crash after replaceing controller

### ISSUE THREAD

**Issue by DeKai91** [AppliedEnergistics/Applied-Energistics-2#3094]
Description:
i have made a Selfmade modpack with MMC.
If i place a controler, brake it an Place it at the same position i get an error message in the Console.
> [15:21:37] [ic2-poolthread-48/WARN] [IC2.EnergyNet]: Tile appeng.integration.modules.ic2.IC2PowerSinkAdapter@731b53e0 (dim 0: -147/53/273), sub tile -147/53/273 (appeng.integration.modules.ic2.IC2PowerSinkAdapter@731b53e0) addition is conflicting with a previous registration at the same location (appeng.integration.modules.ic2.IC2PowerSinkAdapter@7964b29d).
this happens every time a controller block is replaced.

then if i loggout ~every minute i get this message with differend coordinates (dim 0: -147/53/273) for every contolerblock i placed no matter if i replaced it or not .
for example i build an controller, brake one block an place it again, this message appears for every controler block.

the server load increasede till the server stops automaticly. 

if i brake the whole controler the message didn't show up again, but if i build the controler again the message starts to show again. 

Environment: 
Nitrado Game server

> Other Mods
> + Actually Additions,
> + AppleSkin
> + Applied Energistics 2
> + Better Builders Wands
> + Bookshelf
> + Brandons Core
> + Ceramics
> + Chickens
> + Chisel
> + CodeChickenCore
> + CodeChickenLib
> + CoFHCore
> + ComputerCraft
> + ConnectedTexturesMod
> + CustomMainMenu
> + DarkUtilities
> + Draconic Evolution
> + Elevator Mod
> + EnderCore
> + EnderIO
> + EnderStorage
> + ExCompressum
> + ExNihiloAdscensio
> + ExtraUtilities 2
> + ExtremeReactors
> + FlucNetworks
> + GooglyEyes
> + GraveStone Mod
> + Hatchery
> + Immersive Engineering
> + IndustrialCraft 2
> + Inventory Tweaks
> + Ironchest
> + JEI
> + Journey Map
> + LLOverlayReloaded
> + Mantle
> + MineFactoryReloaded
> + Minicoal
> + MoarSigns
> + ModularPowersuits
> + MoreShears
> + MoreChickens
> + Morpheus
> + Mystical Agriculture
> + Natura
> + Neat
> + OptiFine
> + OreExcavation
> + Pam's Harvestcraft
> + Resource Loader
> + SimpleGenerators
> + Snad
> + SonaCore
> + Tinkers Construct
> + Thermal Dynamics
> + Thermal Expansion
> + Thermal Foundation
> + Tiny Progression
> + Twerk-Sim 2k16
> + ValkyrieLib
> + Hwyla
> + Wawla
> + YUNoMakeGoodMaps
> + ZeroCore

- Minecraft Version: 1.10.2
- AE2 Version: rv4 stable -1
- Forge Version:

**Comment by yueh** [comment]
Forge Bug/Feature. Nothing we can fix.

**Comment by fscan** [comment]
FYI, forge has a fix for this in the 1.12.1 version. In the meantime, chunkloading the area should help.

**Comment by DeKai91** [comment]
> FYI, forge has a fix for this in the 1.12.1 version. In the meantime, chunkloading the area should help.

i chunkloaded the whole area
thank you verry much that realy helped!!!

**Comment by macks2008** [comment]
could someone please link the forge issue tracker entry corresponding to this bug? I want to see if I can bug them for a 1.10 fix, as it (or a similar bug with the same error message) is making my server slow down and eventually completely freeze when no players are online. This bug seems to affect ANY and ALL industrialcraft generators (regardless of the energy recipient), of which we have a lot. 
I'd also like to see if industrialcraft can fix this in 1.10, in case it's on their side of the fence or forge devs simply don't want to bother with 1.10. I understand if no one wants to bother with 1.10, but I still feel compelled to try anyway
Known offenders on our current map: solar arrays and a furnace generator
