### ISSUE TITLE
ME network connections not reconnected at SCS edge

### ISSUE THREAD

**Issue by rayxDE** [AppliedEnergistics/Applied-Energistics-2#3095]
#### Description

Tinkering around with a Spatial Containment Structure I encountered an issue with ME cables.
I connected ME-devices inside the SCS to the outside ME-network using several methods (smart cable to smart cable, dense cable to dense cable, P2P tunnel to dense and smart cable).

Expected behaviour:
When restoring the described setup the ME connections are reconnected.

Actual behaviour:
The cable adjacent to the outside ME network cable/P2P tunnel drops into the world.

Workaround:
Connections to a quartz fibre seem to be restored correctly. The ME network connection can be achieved using ME Interface and ME Storage Bus.

#### Environment

- Minecraft Version: 1.7.10
- AE2 Version: rv3 beta 6
- Forge Version: 10.13.4.1614
- Technic-Modpack: After Humans 1.2
- Mode: singleplayer creative
- Log: https://pastebin.com/zCV9pNC0

**Comment by yueh** [comment]
We no longer support 1.7.10 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
