### ISSUE TITLE
Pattern Terminal causing crashes

### ISSUE THREAD

**Issue by jefferyrlc** [AppliedEnergistics/Applied-Energistics-2#3098]
#### Environment

- Minecraft Version: 1.12.1
- AE2 Version: Rv5 Alpha 4
- Forge Version: 1.12.1 - 14.22.1.2478

Upon trying to use the pattern terminal to create patterns the game will crash. Especially if you are attempting to create a Processing Pattern.

Below is attached crash report

[crash-2017-09-17_11.33.21-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1309179/crash-2017-09-17_11.33.21-client.txt)

**Comment by fscan** [comment]
This is already fixed in git and will be in the next release.

**Comment by TheSnowyChickens** [comment]
Is it possible to download the git version anywhere?
I rly need the processing pattern. :)
