### ISSUE TITLE
Interface and me interfaces not working very well

### ISSUE THREAD

**Issue by HairyDragonBeck** [AppliedEnergistics/Applied-Energistics-2#3099]
#### Description

So basically, whenever I try to autocraft, the CPU's go offline. Then when I break a interface, one of my CPU's come back online. It is weird and I can't seem to fix it. Because I know that I should be able to have a lot of interfaces without having any errors. Also, everything else is working fine
#### Environment

I am playing [All The Mods: Expert Mode](https://docs.google.com/spreadsheets/d/1n5XguE0yknSIqdcsMZQEsU3ybmAWeR9gXiR03wiQGBI/edit#gid=0), and I don't think that any of the mods _other then possibly AE2 Stuff_ will interfere at all
- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-11
- Forge Version: 12.18.3.2254

**Comment by Quest79** [comment]
You should really ask the forums before creating a half-ass issue report. You likely have a channel/power distribution issue or something else you're not seeing.
