### ISSUE TITLE
Lost permission to own ME network??

### ISSUE THREAD

**Issue by i00** [AppliedEnergistics/Applied-Energistics-2#3100]
#### Description
I have a security terminal as I wanted to access my ME remotely... and everything worked fine.
I logged on today and couldn't take or put items into it, like I didn't have permission.

I can still access it however through the Wireless Terminal
Also I know that no one has interfered with it as this is a single player game.

- Minecraft Version: 1.10.2
- AE2 Version: rv4-stable-1
- Forge Version: 12.18.3.2422

**Comment by yueh** [comment]
Most likely a duplicate of #3013. In short it is a forge feature since (probably) 1.9.4 to lose the tile entity data of chunks in some rare occasions. (to my knowledge, could be even earlier). Nothing we can fix.

**Comment by i00** [comment]
This is not the same ... all blocks in the chunk contain the same stuff etc (no inventory lost)... just the system became non-accessible.

**Comment by fscan** [comment]
Then send some logs please, this is the best guess with the information you give.
