### ISSUE TITLE
hi AE2 team this is not a issue but its a question regarding custom recipes

### ISSUE THREAD

**Issue by trilexcom** [AppliedEnergistics/Applied-Energistics-2#3109]
hi AE2 team thanks for updating AE2 to 1.12.1 i really appericate everyone of you!

i am trying to add a custom recipe to AE2 Grindstone 
i add this script grind= minecraft:clay -> 1 ic2:dust:1

i made a folder called user-recipes under the folder below!

in config AppliedEnergistics2 > aerecipes > user-recipes

when i go in game i try to put a clay block in AE Grindstone it won't accept it

here is what is my grind.recipe file looks like 
grind= ae2:material.fluix_crystal -> ae2:material.fluix_dust
grind= ae2:sky_stone_block:0 -> ae2:material.sky_dust
grind= mc:gravel -> mc:flint
grind= mc:bone -> 4 mc:dye:15
grind= minecraft:clay -> 1 ic2:dust:1

in the config file customrecipes.cfg file i have custom recipes enabled

general {
    # Will output more detailed information into the CSV like corresponding items [default: false]
    B:enableAdditionalInfo=false

    # If true, the CSV exporting will always happen. This will not use the cache to reduce the computation. [default: false]
    B:enableForceRefresh=false

    # If true, the custom recipes are enabled. Acts as a master switch. [default: true]
    B:enabled=true

    # If true, all registered items will be exported containing the internal minecraft name and the localized name to actually find the item you are using. This also contains the item representation of the blocks, but are missing items, which are too much to display e.g. FMP. [default: true]
    B:exportItemNames=true
}

but for some reason AE2 won't pull up the clay to grind down to ic2 claydust

Forge : 2485
MC : 1.12.1
AE Version : appliedenergistics2-rv5-alpha-4

can you please tell me what i am doing wrong so i can add this to my pack

Thanks 

Mat (TrilexCom)

**Comment by leagris** [comment]
<ol>
<li>Follow all instructions here: <a href="http://ae-mod.info/Custom-Recipes/">AE2 Custom Recipes</a>. (Especially ensure, you extracted and copied, <em>whole recipes definitions files and directories</em> into <code>config/AppliedEnergistics2/recipes/user/</code> and then made your changes there.)</li>
<li>Minecraft™ items are referred as <code title="Aliased Minecraft™ abbreviation">mc</code>, using <code title="Aliases definitions file">aliases.recipe</code>; so your <code>grind.recipe</code> should read:

```cfg
grind= ae2:material.fluix_crystal -> ae2:material.fluix_dust
grind= ae2:sky_stone_block:0 -> ae2:material.sky_dust
grind= mc:gravel -> mc:flint
grind= mc:bone -> 4 mc:dye:15
grind= mc:clay -> 2 IC2:itemDust:1
```   
<li>Now, considering your initial submission has its output to just one <code>dust</code>, but designated <cpde title="Minecraft™ Clay Block">mc:clay</code> witch refers to the Clay Block; I upped it to two instead, witch matches an <code title="ModID for Industrialcraft2">IC2</code> Macerator output doubling.</li>

**Comment by trilexcom** [comment]
thanks Lea

**Comment by trilexcom** [comment]
hi Lea sorry to bother you again here is what i have done let me know if i have done it right please

so when i launch mc ae2 on her own make a folder called aerecipes below is the link to the screen of the folder
https://imgur.com/a/7pn63

if i open ae2 jar file in my winrar i see this https://imgur.com/a/3c45y

when i extract the whole folder called recipe as per in the jar file in to ae2 config file and i create a user folder in their and i add grind.recipe file to that folder

AE2 still not picking up that recipe , 

i copy everything from aerecipes folder in to user folder and made my changes to grind.recipe file ae still not picking up that, 

so i delete the whole aerecipes folder and just leave and create a recipe folder and than i create a user folder i add the same stuff with my changes still not picking up (even though i have deleted the aerecipes when ae launched it created that folder again)

can you please confirm me if this is correct way of doing this below is a screenshot

https://imgur.com/a/jlgZq

just a fyi again when i create that folder and with user folder ae2 still creates another folder called aerecipes

one thing though when i look at index.recipes look like ae is using json recipes ? am i right ? or i dont have to worry about that ?

### REPLACED IN 1.12 BY JSON RECIPES
# All actual recipes
#import=decorative/index.recipe
#import=materials/index.recipe
#import=misc/index.recipe
#import=network/index.recipe
#import=tools/index.recipe

can you please tell me if i am being dumb about this or their something wrong with AE2? not picking up recipes even though i understand AE2 in 1.12.1 is still alpha just wanna make sure lol

Thanks again 

Mat (TrilexCom)

**Comment by leagris** [comment]
@trilexcom ah yes AE2 1.11.2 changed recipes syntax to JSON probably you have to:
- Check your grind.recipe is indexed in some import or add your change to existing already indexed file
- Adapt syntax to that of the Json.

And probably check with Team here, that custom recipes still works.
I think someone needs to update the custom recipes documentation to match late changes.

**Comment by trilexcom** [comment]
i tried to tell import file to grab the grind.recipe file everything i change that once i restart MC, AE2 rewrite it back to default,  what do you know adapt syntax to that of the json ? any doc? please

Thanks 

Mat

**Comment by Ommina** [comment]
You should have your modified _grind.recipe_ in .\config\AppliedEnergistics2\aerecipes\user\processing

No mucking about with json for the custom recipes, no dragging any files out of the jar, no importing.

**Comment by trilexcom** [comment]
I did that but it wont accept the clay as a recipe inside the grindstone
when i try to put it in it wont even go in  for ic2 clay dust or even when
i check for recipe in jei i dont see it except ic2 maceser recipe

Mat

**Comment by Ommina** [comment]
Then I'm going to suggest that there is something else (unrelated to the placement of the files) that is causing the trouble.

I successfully tested with **grind= mc:clay -> 8 mc:flint** as I did not have IC2 installed. I'll add in IC2 and edit this post.

**Comment by yueh** [comment]
Custom recipes are no longer supported as vanilla now supports something similar natively.

Forge is somewhat lacking in regards to supporting machine recipes, thus we are are still depending on the old system for some machines. But these will finally phase out once forge decides upon supporting machine recipes themselves or not and we can design our own extension for the vanilla recipes.

**Comment by twoworlds** [comment]
So is there a possibility to change or disable specific recipes at the moment?`
I am trying to change the recipe for the wooden gear used in the grinder, because it blocks the basic recipe from another mod (Blockcraftery: https://minecraft.curseforge.com/projects/blockcraftery?gameCategorySlug=mc-mods&projectID=278882)
