### ISSUE TITLE
Shooting paint ball on clay causes weird rendering

### ISSUE THREAD

**Issue by pot-code** [AppliedEnergistics/Applied-Energistics-2#3112]
#### Description

![2017-09-25_11 47 34](https://user-images.githubusercontent.com/17687881/30791916-da096700-a1e8-11e7-8633-fe3900004394.png)

[Item]: Matter Cannon 
[Ammo]: paint ball - Lumen Red
[Target block]: White hardened clay

Update: Aiming at a specific angle should trigger the same issue from any block (adjust the aiming line to be more paralleled to the surface of the block).
![2017-09-25_12 15 13](https://user-images.githubusercontent.com/17687881/30792334-01d30d42-a1ec-11e7-844b-bc78f5c143f1.png)

#### Environment

- Minecraft Version: 1.10.2
- AE2 Version: appliedenergistics2-rv4-stable-1
- Forge Version: 12.18.3.2422
- Operating System: Windows 10 (amd64) version 10.0
- Java Version: 1.8.0_112, Oracle Corporation
- Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
- Memory: 420595984 bytes (401 MB) / 1004466176 bytes (957 MB) up to 4225236992 bytes (4029 MB)
- JVM Flags: 2 total; -Xincgc -Xmx4096M

#### Loaded mods

- appliedenergistics2-rv4-stable-1
- Calculator-1.10.2-3.2.3
- Chameleon-1.10.2-2.3.0
- ChestTransporter-1.10.2-2.5.18
- Chisel-MC1.10.2-0.0.13.30
- chiselsandbits-12.12
- ChiselsBytes-1.9.4-0.4
- compatlayer-1.10-0.2.9
- CraftTweaker-1.10.2-3.0.26
- CTM-MC1.10.2-0.2.2.24
- cyberware-1.9.4-1.10.2-beta-0.2.10
- EnderCore-1.10.2-0.4.1.66-beta
- EnderIO-1.10.2-3.1.193
- extrautils2-1.10.2-1.6.3
- Flesh2Leather [1.10.2]
- FluxNetworks-1.10.2-1.2.6
- ImmersiveEngineering-0.10-61
- immersivepetroleum-1.10.2-1.1.3
- industrialcraft-2-2.6.252-ex110
- IndustrialWires-1.4-18
- intwheel-1.1x-1.2.6
- InventoryTweaks-1.61-58
- jei_1.10.2-3.14.7.420
- journeymap-1.10.2-5.4.7
- JustEnoughCalculation-1.10.2-2.6.4
- malisiscore-1.10.2-4.4.0
- malisisdoors-1.10.2-5.2.0
- MCMultiPart-1.4.0-universal
- Mekanism-1.10.2-9.2.3.97
- MekanismGenerators-1.10.2-9.2.3.97
- ModTweaker2-2.0.13
- MTLib-1.0.3
- OpenComputers-MC1.10.2-1.6.2.7
- OptiFine_1.10.2_HD_U_E3
- PracticalLogistics2-1.10.2-2.0.2
- SonarCore-1.10.2-3.2.9
- StorageDrawers-1.10.2-3.7.10
- supercraftingframe-1.10.2-1.2.1.88
- theoneprobe-1.1x-1.4.18
- TreeChopper-1.10.2-1.1.2
- UniDict-1.10.2-2.9b
- WanionLib-1.10.2-1.3
- WaterStrainer-1.9.4-1.4.2

**Comment by Tahakk** [comment]
Can you try to replicate this without Optifine/TexturePack or if you want to really help with minimum mods that are required to replicate this.
