### ISSUE TITLE
were has the build for 1.11.2 gone

### ISSUE THREAD

**Issue by Anora** [AppliedEnergistics/Applied-Energistics-2#3115]
hey guys I have a build of AE for 1.11.2 using forge 13.20.1.2476 and I came here to see if there was a problem then i see the builds for 1.11.2 are gone and I would of loved to have fixed the problem I am having whit the grind stone eating resources

**Comment by yueh** [comment]
There were never 1.11 builds.

**Comment by Anora** [comment]
I did find one but it was super glitchy
