### ISSUE TITLE
Going to Nether breaking network

### ISSUE THREAD

**Issue by nlogozzo** [AppliedEnergistics/Applied-Energistics-2#3116]
Anytime that anyone in the world going into the nether and comes back a part of the network disappears. Whether it is cable, drives, terminals, they randomly disappear when coming back from the nether

- Minecraft Version: 1.12.1
- AE2 Version: 1.12.X Alpha 3
- Forge Version: 1.12.1

**Comment by yueh** [comment]
Data loss is currently a forge feature/bug. Nothing we can do.

**Comment by mindforger** [comment]
try persistent chunkloading for the area meanwhile

**Comment by nlogozzo** [comment]
Do you know how i can do that?
________________________________

**Comment by mindforger** [comment]
depends on what mods you have ... look for chunkloaders(common name) and world anchors(railcraft version ... if available)
i believe FTBUtils chunkloading (by claiming chunks) don't work as FTBU is suffering from a similar issue stemming from the root cause of this issue
