### ISSUE TITLE
No types have been added to Biome

### ISSUE THREAD

**Issue by UnPure** [AppliedEnergistics/Applied-Energistics-2#3118]
#### Description
It seems like the storage_biome has no types that could be loaded.
I know this is nothing that is realy needed, but maybe it should still be added.

    [10:43:16] [Server thread/WARN] [FML]: No types have been added to Biome appliedenergistics2:storage_biome, types have been assigned on a best-effort guess: [COLD, PLAINS]

#### Environment
- Minecraft Version: 1.12.1
- AE2 Version: rv5-alpha-4
- Forge Version: 14.22.0.2475

**Comment by mindforger** [comment]
cold sounds good, but plains ... meh ... is there a type "void" ?

**Comment by yueh** [comment]
While there is a `VOID`, it is not really fitting as it is pretty much the exact opposite as a nearly solid biome. Even `COLD` does not fit really. Think more about absolute zero.

**Comment by mindforger** [comment]
i agree on the absolut zero ... but there is not such a type i guess? VOID as in there is nothing by definition that gets filled with overworld content in the act of creation but the dimension/biome itself is nothing but space

**Comment by josephcsible** [comment]
This is still happening for me as of AE2 rv6-stable-4 and Forge 2794.

**Comment by katubug** [comment]
I am also still having this issue.

`[14:04:43] [Server thread/WARN] [FML]: No types have been added to Biome appliedenergistics2:storage_biome, types have been assigned on a best-effort guess: [COLD, PLAINS]`

* **Minecraft version:** 1.12.2
* **Forge version:** forge-1.12.2-14.23.5.2838-universal
* **Modpack version** (links to current modlist): [1.7.2](http://enthusiasticraft.cf/modpack-update-1-7-2/#modlist)
* **Mod versions:** appliedenergistics2-rv6-stable-7
