### ISSUE TITLE
My Applied Energistics 2 System isn't showing my items!!

### ISSUE THREAD

**Issue by HuskyPlays** [AppliedEnergistics/Applied-Energistics-2#3119]
I started a new World (Public server) ive got the basic ME System going but once i put a lot of items in the system it stoped showing me all my items but still lets me put mine in.

Video showing you: https://youtu.be/WMjQJRpbzM8

- Minecraft Version: 1.7.10
- AE2 Version: (All it says is rv0-stable-3)
- Forge Version: 17.10    10.13.4.1614

http://prntscr.com/gqptd6

I've tried reinstalling my pack stoped and started the server but nothing is working can someone please help me.

**Comment by mindforger** [comment]
1.7.10 is out of support, and why do you even use rv0? this one is old as heck .... try rv3 beta 6 instead!
