### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by GhostShot3** [AppliedEnergistics/Applied-Energistics-2#3120]
How to leave crawling all the time without stopping ?
How do I for example for some item from another place to enter or exit on my ME Chest for example using buidcraft tubes,enderio conduits ?

- Minecraft Version: 1.7.10
- AE2 Version: last update
- Forge Version: 10.13.4.1614

**Comment by mindforger** [comment]
>How to leave crawling all the time without stopping

what now?

>How do I for example for some item from another place to enter or exit on my ME Chest for example using buidcraft tubes,enderio conduits ?

trying to understand ... you want to move an item out of the me chest?

well you have two options
1. an interface configured to present an specified ammount of a certain item that you can pull out with any system you like
2. and export bus that exports an defined item into any object that accepts items input

1.7.10 is not supported anymore, i will close this issue now

but i will still monitor it if you have any further questions

**Comment by GhostShot3** [comment]
I nerd to craft item without requesting in terminal

I managed to get items out of ME chest thanks

I'm using a translator, sorry for the mistakes.

**Comment by mindforger** [comment]
crafting without terminal is possible when you insert a **crafting card** into the interface or export bus

as long as your system has all required machines for autorcrafting (crafting CPU, interfaces with recipes and molecular assembler) and your export bus has an crafting card, it will request the item to craft before exporting it

**Comment by GhostShot3** [comment]
Thanks i got it

**Comment by GhostShot3** [comment]
Okay, I managed to do as the machines to craft items but I put the exportbus on my system with crafting upgrade but it's still not automatically crafting I need to request itens with terminal, what could have gone wrong on my system?

**Comment by GhostShot3** [comment]
In exportbus I put the item to and activated "craft the items when exported" something to yes still is not working.
