### ISSUE TITLE
Crash on startup 1.12.1 rv5-a5

### ISSUE THREAD

**Issue by XxZajoZzO** [AppliedEnergistics/Applied-Energistics-2#3121]
#### Description
Custom modpack crashes on startup after updating appeng to rv5-a5 version
Crash report: https://pastebin.com/bJUJmSJw

#### Environment
- Java: 1.8.0_25
- OS: Windows 10 64-bit
- Minecraft Version: 1.12.1, 6GB allocated RAM
- AE2 Version: 1.12.1-rv5-alpha5
- Forge Version: 14.22.1.2485

**Comment by TheSnowyChickens** [comment]
Jep , I have the same bug. ^^

**Comment by Uuo-Ununoctium** [comment]
Also having the same issue, I tried the build with and without other mods.

With: https://pastebin.com/iAzcbw1n

Without: https://pastebin.com/dcej1SaR

Java 1.8.0_121
Forge 2484
AE 1.12.x-rv5-a5
OS Win 10 Pro x64

Perhaps need the latest forge?

**Comment by fscan** [comment]
There seems to be something wrong with the build server. We are working on it.

**Comment by Uuo-Ununoctium** [comment]
Thanks. You guys rock!

**Comment by JasonKillsUs** [comment]
thanks for the quick response...

**Comment by TheSnowyChickens** [comment]
Thanks AE2 Team!

**Comment by yueh** [comment]
As far as I can tell for now, it seems like Forge/ForgeGradle is producing broken builds in some cases. 

Allegedly this should be fixed, but I am currently not trusting it without some verification and end up with a couple of broken builds floating around. But the buildserver was never designed around being able to verify a build before releasing it as we trusted Forge to not create broken builds without failing. Therefore it might take some time, before we have a manual way to try a build before releasing it.

**Comment by leagris** [comment]
Could it be unit tests of some kind, running last build in a fully featured server and client environments?

**Comment by yueh** [comment]
This would be more like integration testing (or maybe even system tests depending on how you interprete it) and not unit testing.

But probably no feasible. Running the client headless is probably impossible. So catching stuff like `@SideOnly` not applying to inheritance in some cases will still miss broken builds. As far as I remember, there is also no "run the server once and stop immediately" option for the server. So it would be more like start it, hope it does not crash and kill it after N secs. While hoping nothing does influence the startup time in a way to exceed the defined limit and thus marks a valid build as broken.

All in all, Minecraft and Forge is not really be made to be used in automatic tests. In some cases Forge even actively prevents unit testing by explicitly checking for a full FML/Forge environment for meaningless things like parsing a simple textfile.

**Comment by yueh** [comment]
Just pushed a fixed build. No idea how long curse will need to "review" it. But once they have accepted it, you will be able to download a fixed build.
