### ISSUE TITLE
Not able to insert into Matter Condenser

### ISSUE THREAD

**Issue by ouroborus** [AppliedEnergistics/Applied-Energistics-2#3122]
Other then being able to place the Storage Component in the slot meant for it, I'm unable to place anything into the trash slot. (It doesn't get eaten, it just doesn't go in.)

Possibly related to: [Not able to extract from Matter Condenser](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2960)

- Minecraft Version: 1.12.1
- AE2 Version: rv5-alpha-4
- Forge Version: 14.22.0.2467

**Comment by Meller127** [comment]
A new release is just out that fixes this, but wait ti update they have problems with the build server atm.
-Fix matter condenser input slot - fscan

**Comment by ouroborus** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/commit/216e2cb1e3e8a9ccb67fc75edb388b558bd6c498
