### ISSUE TITLE
Possible dupe bug with ME pattern Terminls.

### ISSUE THREAD

**Issue by Xvalencia** [AppliedEnergistics/Applied-Energistics-2#3123]
While setting up auto crafting, I was in the ME Pattern Terminal UI and I right clicked and item by mistake and it gave me half a stack of the item (didn't matter what the item was, I tried it on a a couple item)

- Minecraft Version: 1.12.2
- AE2 Version: rev5-alpha-4
- Forge Version: 14.22.1.2485
(I'm playing on the ATM3 pack on a server)

**Comment by yueh** [comment]
The pattern terminal is just like any other terminal. Rightclick a stored item will always extract half a stack from the network.
