### ISSUE TITLE
1.12.1 crash (sonar core and applied energistics)

### ISSUE THREAD

**Issue by erwin1234777** [AppliedEnergistics/Applied-Energistics-2#3127]
Crash report link: https://pastebin.com/3W3dNEDZ

- Minecraft Version: 1.12.1
- AE2 Version: rv5-alpha-6
- Forge Version: 14.22.1.2485

**Comment by fscan** [comment]
AE2 is an alpha, there where API changes. There is nothing we can do on our side.
