### ISSUE TITLE
rv5-alpha-6 crash during forge loading.

### ISSUE THREAD

**Issue by danikk14g** [AppliedEnergistics/Applied-Energistics-2#3130]
#### Description
alpha-4 works fine, when i update to alpha-6 it doesn't.

#### Environment
FluxNetworks has the 'E' of errored in the state column, maybe there is an issue with that, i don't like to bother you but the crash only happens when i update to rv5-alpha-6 only.

- Minecraft Version: 1.12.2
- AE2 Version: rv5-alpha-6
- Forge Version: 1.12.2 - 14.23.0.2493 and also 1.12.2 - 14.23.0.2495

**Comment by yueh** [comment]
Then report it to the crashing mod.

**Comment by danikk14g** [comment]
sorry i forgot to leave the link of the crash report
java.lang.NoClassDefFoundError: appeng/api/networking/security/BaseActionSource
