### ISSUE TITLE
ME Pattern Encoder missing

### ISSUE THREAD

**Issue by CombatPower** [AppliedEnergistics/Applied-Energistics-2#3133]
Hello,
I'm using Forge v12.18.3.2488 with minecraft 1.10.2 and ae2-rv4-stable-1. I wanted to automate my ME-System with patterns but I can't find the pattern encoder. This issue exists as well in SP as in MP.

Do you have some ideas?

LOG of AE2:
[B#353] 2017/10/04 22:29:41 [INFORMATION]  [22:29:41] [Client thread/INFO] [AE2-CORE]: Removing Interface cofh.api.energy.IEnergyReceiver from appeng/tile/powersink/RedstoneFlux because RF integration is disabled.
[B#353] 2017/10/04 22:29:41 [INFORMATION]  [22:29:41] [Client thread/INFO] [AE2-CORE]: Updated appeng/tile/powersink/RedstoneFlux
[B#353] 2017/10/04 22:29:41 [INFORMATION]  [22:29:41] [Client thread/INFO] [AE2-CORE]: Removing Interface ic2.api.item.ISpecialElectricItem from appeng/items/tools/powered/powersink/IC2 because IC2 integration is disabled.
[B#353] 2017/10/04 22:29:41 [INFORMATION]  [22:29:41] [Client thread/INFO] [AE2-CORE]: Removing Interface ic2.api.item.IElectricItemManager from appeng/items/tools/powered/powersink/IC2 because IC2 integration is disabled.
[B#353] 2017/10/04 22:29:41 [INFORMATION]  [22:29:41] [Client thread/INFO] [AE2-CORE]: Removing Method getManager from appeng/items/tools/powered/powersink/IC2 because IC2 integration is disabled.
[B#353] 2017/10/04 22:29:41 [INFORMATION]  [22:29:41] [Client thread/INFO] [AE2-CORE]: Updated appeng/items/tools/powered/powersink/IC2
[B#353] 2017/10/04 22:29:41 [INFORMATION]  [22:29:41] [Client thread/INFO] [AE2-CORE]: Removing Interface cofh.api.energy.IEnergyContainerItem from appeng/items/tools/powered/powersink/RedstoneFlux because RFItem integration is disabled.
[B#353] 2017/10/04 22:29:41 [INFORMATION]  [22:29:41] [Client thread/INFO] [AE2-CORE]: Updated appeng/items/tools/powered/powersink/RedstoneFlux
[B#353] 2017/10/04 22:29:41 [INFORMATION]  [22:29:41] [Thread-6/INFO] [FML]: Using sync timing. 200 frames of Display.update took 44885528 nanos
[B#353] 2017/10/04 22:29:41 [INFORMATION]  [22:29:41] [Client thread/INFO] [AE2-CORE]: Removing Interface ic2.api.energy.tile.IEnergySink from appeng/parts/p2p/PartP2PIC2Power because IC2 integration is disabled.
[B#353] 2017/10/04 22:29:41 [INFORMATION]  [22:29:41] [Client thread/INFO] [AE2-CORE]: Removing Interface ic2.api.energy.tile.IEnergySource from appeng/parts/p2p/PartP2PIC2Power because IC2 integration is disabled.
[B#353] 2017/10/04 22:29:41 [INFORMATION]  [22:29:41] [Client thread/INFO] [AE2-CORE]: Updated appeng/parts/p2p/PartP2PIC2Power
[B#353] 2017/10/04 22:29:42 [INFORMATION]  [22:29:42] [Client thread/INFO] [AE2:C]: Starting AE2 VersionChecker
[B#353] 2017/10/04 22:29:42 [INFORMATION]  [22:29:42] [Client thread/INFO] [AE2:C]: Pre Initialization ( ended after 1111ms )
[B#353] 2017/10/04 22:29:42 [INFORMATION]  [22:29:42] [AE2 VersionChecker/INFO] [AE2:C]: Last check was just recently.
[B#353] 2017/10/04 22:29:42 [INFORMATION]  [22:29:42] [AE2 VersionChecker/INFO] [AE2:C]: Stopping AE2 VersionChecker
[B#353] 2017/10/04 22:29:42 [INFORMATION]  [22:29:42] [Client thread/INFO] [FML]: Applying holder lookups
[B#353] 2017/10/04 22:29:42 [INFORMATION]  [22:29:42] [Client thread/INFO] [FML]: Holder lookups applied
[B#353] 2017/10/04 22:29:42 [INFORMATION]  [22:29:42] [Client thread/INFO] [FML]: Injecting itemstacks
[B#353] 2017/10/04 22:29:42 [INFORMATION]  [22:29:42] [Client thread/INFO] [FML]: Itemstack injection complete
[B#353] 2017/10/04 22:29:42 [INFORMATION]  [22:29:42] [Sound Library Loader/INFO]: Starting up SoundSystem...
[B#353] 2017/10/04 22:29:42 [INFORMATION]  [22:29:42] [Thread-9/INFO]: Initializing LWJGL OpenAL
[B#353] 2017/10/04 22:29:42 [INFORMATION]  [22:29:42] [Thread-9/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[B#353] 2017/10/04 22:29:42 [INFORMATION]  [22:29:42] [Thread-9/INFO]: OpenAL initialized.
[B#353] 2017/10/04 22:29:42 [INFORMATION]  [22:29:42] [Sound Library Loader/INFO]: Sound engine started
[B#353] 2017/10/04 22:29:43 [INFORMATION]  [22:29:43] [Client thread/INFO] [FML]: Max texture size: 16384
[B#353] 2017/10/04 22:29:43 [INFORMATION]  [22:29:43] [Client thread/INFO]: Created: 16x16 textures-atlas
[B#353] 2017/10/04 22:29:43 [INFORMATION]  [22:29:43] [Client thread/INFO] [AE2:C]: Initialization ( started )
[B#353] 2017/10/04 22:29:43 [INFORMATION]  [22:29:43] [Client thread/INFO] [AE2:C]: Starting AE2 CSV Export
[B#353] 2017/10/04 22:29:43 [INFORMATION]  [22:29:43] [AE2 CSV Export/INFO] [AE2:C]: Cache is enabled. Checking for new mod configurations.
[B#353] 2017/10/04 22:29:43 [INFORMATION]  [22:29:43] [AE2 CSV Export/INFO] [AE2:C]: New mod configuration was found. Commencing exporting.
[B#353] 2017/10/04 22:29:43 [INFORMATION]  [22:29:43] [AE2 CSV Export/INFO] [AE2:C]: Item Exporting ( started )
[B#353] 2017/10/04 22:29:43 [INFORMATION]  [22:29:43] [AE2 CSV Export/INFO] [AE2:C]: Exported successfully 477 items into items.csv
[B#353] 2017/10/04 22:29:43 [INFORMATION]  [22:29:43] [AE2 CSV Export/INFO] [AE2:C]: Item Exporting ( ended after 21 ms)
[B#353] 2017/10/04 22:29:44 [INFORMATION]  [22:29:44] [Client thread/WARN] [AE2:C]: Recipe Error 'Invalid crafting type: grindfz' near line:1 in processing/factorization.recipe with: [ae2:material.FluixCrystal, ->, ae2:material.FluixDust]
[B#353] 2017/10/04 22:29:44 [INFORMATION]  [22:29:44] [Client thread/WARN] [AE2:C]: Recipe Error 'Invalid crafting type: grindfz' near line:2 in processing/factorization.recipe with: [ae2:sky_stone_block:0, ->, ae2:material.SkyDust]
[B#353] 2017/10/04 22:29:44 [INFORMATION]  [22:29:44] [Client thread/WARN] [AE2:C]: Recipe Error 'Invalid crafting type: grindfz' near line:4 in processing/factorization.recipe with: [mc:ender_pearl, ->, ae2:material.EnderDust]
[B#353] 2017/10/04 22:29:44 [INFORMATION]  [22:29:44] [Client thread/WARN] [AE2:C]: Recipe Error 'Invalid crafting type: grindfz' near line:5 in processing/factorization.recipe with: [ae2:material.CertusQuartzCrystalCharged, ->, ae2:material.CertusQuartzDust]
[B#353] 2017/10/04 22:29:44 [INFORMATION]  [22:29:44] [Client thread/WARN] [AE2:C]: Recipe Error 'Invalid crafting type: grindfz' near line:7 in processing/factorization.recipe with: [ae2:material.CertusQuartzCrystal, ->, ae2:material.CertusQuartzDust]
[B#353] 2017/10/04 22:29:44 [INFORMATION]  [22:29:44] [Client thread/WARN] [AE2:C]: Recipe Error 'Invalid crafting type: grindfz' near line:8 in processing/factorization.recipe with: [ae2:quartz_ore, ->, 2, ae2:material.CertusQuartzDust]
[B#353] 2017/10/04 22:29:44 [INFORMATION]  [22:29:44] [Client thread/WARN] [AE2:C]: Recipe Error 'Invalid crafting type: grindfz' near line:9 in processing/factorization.recipe with: [ae2:charged_quartz_ore, ->, 2, ae2:material.CertusQuartzDust]
[B#353] 2017/10/04 22:29:44 [INFORMATION]  [22:29:44] [Client thread/INFO] [AE2:C]: Recipes Loading: Shaped: 211 loaded.
[B#353] 2017/10/04 22:29:44 [INFORMATION]  [22:29:44] [Client thread/INFO] [AE2:C]: Recipes Loading: Smelt: 6 loaded.
[B#353] 2017/10/04 22:29:44 [INFORMATION]  [22:29:44] [Client thread/INFO] [AE2:C]: Recipes Loading: Macerator: 8 loaded.
[B#353] 2017/10/04 22:29:44 [INFORMATION]  [22:29:44] [Client thread/INFO] [AE2:C]: Recipes Loading: Press: 3 loaded.
[B#353] 2017/10/04 22:29:44 [INFORMATION]  [22:29:44] [Client thread/INFO] [AE2:C]: Recipes Loading: OreRegistration: 16 loaded.
[B#353] 2017/10/04 22:29:44 [INFORMATION]  [22:29:44] [Client thread/INFO] [AE2:C]: Recipes Loading: MekCrusher: 3 loaded.
[B#353] 2017/10/04 22:29:44 [INFORMATION]  [22:29:44] [Client thread/INFO] [AE2:C]: Recipes Loading: HCCrusher: 9 loaded.
[B#353] 2017/10/04 22:29:44 [INFORMATION]  [22:29:44] [Client thread/INFO] [AE2:C]: Recipes Loading: Inscribe: 8 loaded.
[B#353] 2017/10/04 22:29:44 [INFORMATION]  [22:29:44] [Client thread/INFO] [AE2:C]: Recipes Loading: Shapeless: 57 loaded.
[B#353] 2017/10/04 22:29:44 [INFORMATION]  [22:29:44] [Client thread/INFO] [AE2:C]: Recipes Loading: Pulverizer: 9 loaded.
[B#353] 2017/10/04 22:29:44 [INFORMATION]  [22:29:44] [Client thread/INFO] [AE2:C]: Recipes Loading: Crusher: 9 loaded.
[B#353] 2017/10/04 22:29:44 [INFORMATION]  [22:29:44] [Client thread/INFO] [AE2:C]: Recipes Loading: Grind: 4 loaded.
[B#353] 2017/10/04 22:29:44 [INFORMATION]  [22:29:44] [Client thread/INFO] [AE2:C]: Recipes Loading: MekEnrichment: 2 loaded.
[B#353] 2017/10/04 22:29:44 [INFORMATION]  [22:29:44] [Client thread/INFO] [AE2:C]: Initialization ( ended after 335ms )
[B#353] 2017/10/04 22:29:44 [INFORMATION]  [22:29:44] [Client thread/INFO] [FML]: Injecting itemstacks
[B#353] 2017/10/04 22:29:44 [INFORMATION]  [22:29:44] [Client thread/INFO] [FML]: Itemstack injection complete
[B#353] 2017/10/04 22:29:44 [INFORMATION]  [22:29:44] [Client thread/INFO] [AE2:C]: Post Initialization ( started )
[B#353] 2017/10/04 22:29:44 [INFORMATION]  [22:29:44] [Client thread/INFO] [AE2:C]: Industrial Craft 2 - Integration Disabled
[B#353] 2017/10/04 22:29:44 [INFORMATION]  [22:29:44] [Client thread/INFO] [AE2:C]: RedstoneFlux Power - Tiles - Integration Disabled
[B#353] 2017/10/04 22:29:44 [INFORMATION]  [22:29:44] [Client thread/INFO] [AE2:C]: RedstoneFlux Power - Items - Integration Disabled
[B#353] 2017/10/04 22:29:44 [INFORMATION]  [22:29:44] [Client thread/INFO] [AE2:C]: Waila - Integration Disabled
[B#353] 2017/10/04 22:29:44 [INFORMATION]  [22:29:44] [Client thread/INFO] [AE2:C]: Just Enough Items - Integration Disabled
[B#353] 2017/10/04 22:29:44 [INFORMATION]  [22:29:44] [Client thread/INFO] [AE2:C]: TheOneProbe - Integration Disabled
[B#353] 2017/10/04 22:29:44 [INFORMATION]  [22:29:44] [Client thread/INFO] [AE2:C]: Post Initialization ( ended after 98ms )
[B#353] 2017/10/04 22:29:44 [INFORMATION]  [22:29:44] [Client thread/INFO] [FML]: Forge Mod Loader has successfully loaded 5 mods

**Comment by GuntherDW** [comment]
It's not called the "Pattern encoder", it hasn't been since the AE1 days. It's called the "Pattern terminal" nowadays.
