### ISSUE TITLE
Power outage in drives

### ISSUE THREAD

**Issue by nlogozzo** [AppliedEnergistics/Applied-Energistics-2#3134]
Minecraft Version: 1.12.1
AE2 Version: 1.12.1 RV5 Alpha 6
Forge Version: 1.12.1

Once and a while, when the energy cells are fully charged, my ME Drive looses power for a couple of minutes and everything says Device Missing Channel, but then eventually power is restored. It isn't a huge problem but it is an annoyance.

**Comment by mindforger** [comment]
you may experience an issue with your cable layout, double check you don't have overseen loops and keep in mind, a device also can carry 8 channels that may throw off your cable routing!
rerouting always happens when the network gets updated (chunk unloading while far away)

**Comment by fscan** [comment]
As always, if you want this fixed and not just complain to us we need something to work with. Screenshots, log files, description of exactly when it happens and how it fixes itself.

**Comment by nlogozzo** [comment]
Later today I will send a screenshot of my cable layout for you to exam to see if I have anything wrong

On Oct 5, 2017, at 6:51 AM, fscan <notifications@github.com<mailto:notifications@github.com>> wrote:


As always, if you want this fixed and not just complain to us we need something to work with. Screenshots, log files, description of exactly when it happens and how it fixes itself.

**Comment by nlogozzo** [comment]
Here is a copy of my setup
![image](https://user-images.githubusercontent.com/17648453/31297685-0764551e-aab5-11e7-9ac2-cca4c6f11192.png)

**Comment by mindforger** [comment]
That is quiet a good knot of cables :) 

Now the question is, does it happens when you are close nearby or far enough for it to unload partially

And where does the cable on the right go?

**Comment by nlogozzo** [comment]
It usually happens when I start to move far away. Also the cable to the right leads out of my house and goes throughout the world so I can access storage and power throughout

**Comment by nlogozzo** [comment]
![image](https://user-images.githubusercontent.com/17648453/31298384-eb61da5a-aab7-11e7-9dfd-706f227318fb.png)
That is where the cable distributes to.

**Comment by mindforger** [comment]
Yeah that is what i meant with chunk unloading, you leave a part of the network so far away, the server unloads it and your new and smaller network is rebuilding... 

Just chunkload all parts of the network

**Comment by nlogozzo** [comment]
I did install chunk loaders throughout the world and I still have this probably once and a while

**Comment by mindforger** [comment]
try other chunkloades, some do
 not work well ... In 1.7.10 chickenchunks did not work well, but it's spotloads worked well

**Comment by mindforger** [comment]
Also, there was a limit for loaded chunks in the forge config file, you may passed the limit

**Comment by nlogozzo** [comment]
Is there a way to increase the limit?

**Comment by nlogozzo** [comment]
I just went back to my house and saw that it lost power seeing that the button drive went out
![image](https://user-images.githubusercontent.com/17648453/31298957-5db727d4-aaba-11e7-8aca-af98ecd83f76.png)

**Comment by nlogozzo** [comment]
I was inside the house when this happened so this isn't something with chunks

**Comment by mindforger** [comment]
sure it is, if only one part of the network getting unloaded it is rebuilt internally and the result is this effect ... There is a forge config file, just change it

**Comment by nlogozzo** [comment]
That problem was fixed. But now, of course, a new problem arose revolving around the same issue. When traveling back from other dimensions, not just the drive, but the whole network looses power and I need to restart the whole server to get power back.

**Comment by fscan** [comment]
This other dimension also has an me network connected to this one? Also, can you use the network tool to inspect power usage?

**Comment by nlogozzo** [comment]
The other dimension does not have an ME network. And I never saw a network tool before, I will try using that later when i'm home

On Oct 7, 2017, at 1:16 PM, fscan <notifications@github.com<mailto:notifications@github.com>> wrote:


This other dimension also has an me network connected to this one? Also, can you use the network tool to inspect power usage?

**Comment by nlogozzo** [comment]
![image](https://user-images.githubusercontent.com/17648453/31311775-3cc1d430-ab81-11e7-8c94-5b011a2cbf82.png)
This is what I am reading when the network is fully up and running

**Comment by nlogozzo** [comment]
I will try to repeat the process and see if it goes out

**Comment by fscan** [comment]
You can also try to replace the cables with smart ones to visualize channel usage.

**Comment by nlogozzo** [comment]
I added some more smart cables. There seems to be no channel overflow, with the max I am using is 10 out of 32 channels. I also added in some more vibration chambers which generate more AE power instead of using generators (EU power from ic2) and having the power units being converted, which may have been a problem. As of now going back and forth between dimensions isn't causing a problem. Therefore, you can close this issue and if it does happen I will create a new ticket if needed. Thank you for all the quick answers and support. Have a great day

**Comment by nlogozzo** [comment]
Close #3134

**Comment by nlogozzo** [comment]
Fixes #3134

**Comment by mindforger** [comment]
>Therefore, you can close this issue

You created the issue, you can close it yourself, right beside the comment button :)

**Comment by nlogozzo** [comment]
Oh okay thank you didn't see that lol

**Comment by fscan** [comment]
Can you post a screenshot with the smart cables? Also, can you try using a different color cable for the one going outside so it doesn't connect to the other cables?.

**Comment by nlogozzo** [comment]
I didn't know I could use different color cables. I will try that

**Comment by nlogozzo** [comment]
![image](https://user-images.githubusercontent.com/17648453/31316742-5c72f568-ac01-11e7-8a09-a15187ab8a96.png)
My server was offline so I went into single player to recreate the issue. My dense cables can carry the 32 channels, but the regular cable can only carry 8. Terminals and import and export buses can only go regular cables. Therefore I am only allowed to have a max of 8 terminals and import and export busses combined. So anything more than 8 of those items breaks the network. But then I able to connect dense ables to other machines. I require a lot of terminals and import and export busses, so is there a way to connect terminals to dense cables?

**Comment by fscan** [comment]
Without a Controller you can have a max of 8 channels.

Please read http://ae-mod.info/Channels/

I'm closing this now, as it seems this seems to be a misconception of how channels work. A small tip: you should separate the networks connecting to different controller sides, the grid sometimes behaves weird otherwise.
