### ISSUE TITLE
[rv5.alpha 7]Game crash when Sticky Piston pull Quartz Vibrant Glass

### ISSUE THREAD

**Issue by Flithor** [AppliedEnergistics/Applied-Energistics-2#3146]
Push with no problem.
~Speculation may be caused by the OptiFine material connection.~(Exclude the reason for OptiFine)
Crash log:
[crash-2017-10-09_21.22.26-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1368588/crash-2017-10-09_21.22.26-client.txt)

**Comment by fscan** [comment]
Please try without OptiFine.

**Comment by Flithor** [comment]
Remove OptiFine will not crashed immediately, but still after a few push or pull will crash.
[crash-2017-10-10_18.02.18-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1371467/crash-2017-10-10_18.02.18-client.txt)
