### ISSUE TITLE
client is fine, server crashes though 

### ISSUE THREAD

**Issue by BA3WOLF** [AppliedEnergistics/Applied-Energistics-2#3147]
#### Environment

- Minecraft Version: 
- AE2 Version: 
- Forge Version: 
[crash-2017-10-09_10.02.50-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1369024/crash-2017-10-09_10.02.50-server.txt)

**Comment by Ommina** [comment]
IronMan-Beta appears to be calling a client-only function on the server.  You'll have to report it to them; there is no mention of AE2 here.

**Comment by BA3WOLF** [comment]
Truthfully, I knew ae2 wasn’t the problem. But I didn’t  know how to read a crash report tbh lol I just sent the. Rash crash report to the first modder I saw :D
