### ISSUE TITLE
[Question/Suggestion]How can I use ME network to assign the specified number of specified items to the specified external container?

### ISSUE THREAD

**Issue by Flithor** [AppliedEnergistics/Applied-Energistics-2#3148]
This is not machine processing, just allocation.
If it can not be achieved, then this is a suggestion.

**Comment by mindforger** [comment]
external container is a nogo, you would have to measure the item number and return a redstone signal to an export bus!

but you can configure an interface to provide items with a certain number, just pull an item into the lower slotbar into the upper slots there and adjust the number ... in the slot below the items will be presentend and can be pulled out by any means

**Comment by fscan** [comment]
This may be something for additional upgrade cards in the future.

**Comment by Flithor** [comment]
Thx!

**Comment by yueh** [comment]
This was actually already rejected. IO Buses are for bulk transfer, their job is not to control themselves or the attached inventory.
If stockkeeping with an interface is not sufficient, you have to use an IO bus controlled by some external signal.

There might be some changes to acceleration cards and how the increased amount is handled. E.g. let the user define the actual size within an allowed range. But even this is already possible in some ways, therefore it is not guaranteed.
