### ISSUE TITLE
Crash soon after loading, after MC/AE2 update

### ISSUE THREAD

**Issue by unikmhz** [AppliedEnergistics/Applied-Energistics-2#3150]
#### Description
After updating MC and mods to current versions, old world crashes about 5 seconds after loading.

#### Environment
- Minecraft Version: 1.12.2 (updated from 1.12.1).
- AE2 Version: rv5-alpha-8 (updated from rv5-alpha-7).
- Forge Version: 2512 (updated from 2478).
- Linux 64-bit.
- Oracle Java, 1.8.0_144.
- Single-player.
- Tried with/without foamfix.
- Tried with/without LiteLoader.
- Tried using removeCrashingItemsOnLoad=true.
- Crashlog attached: [crash-2017-10-11_02.36.59-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1373772/crash-2017-10-11_02.36.59-server.txt)
- Can provide world/save if needed (save is about 800MB though).

**Comment by unikmhz** [comment]
If I manage to open a crafting terminal before NPE, the grid is empty.

**Comment by yueh** [comment]
And without sponge?

**Comment by Ommina** [comment]
I don't see sponge in the mod list -- would it even be used in a single-player context?  I was under the impression it was used exclusively on dedicated servers.  Perhaps I'm simply confused.

**Comment by unikmhz** [comment]
No sponge. At least I didn't install it - don't even know how to ;)
Used MultiMC to recreate "FTB Unstable" modpack. Installed forge using MultiMC.

**Comment by unikmhz** [comment]
Now, I discovered "Transformer: org.spongepowered.asm.mixin.transformer.Proxy" string in crash report. Does it mean that sponge somehow sneaked in?

**Comment by yueh** [comment]
Except liteloaded bundles some sponge parts (for example see the transformers).

But the `NullPointerException` really makes no sense here, without some external interaction.
E.g. some other mod having some sort of AE integration, but they no longer work with the refactoring done in the latest build.

**Comment by unikmhz** [comment]
Some additional info:
1. Disabling LiteLoader does indeed make all mentions of "org.spongepowered" namespace disappear from crash report. Still outcome stays the same.
2. Captured full log of a crash without LiteLoader: https://paste.ee/p/aow6m (warning, 15k lines).

**Comment by yueh** [comment]
Are you using using a storage bus attached to a ME chest anywhere?

**Comment by unikmhz** [comment]
There is 1 ME chest in the network. It is attached directly to dense smart cable going all the way back to 2x1x1 controller. Additionally this chest has no storage cell installed in it.

Also, interestingly, I can create new world and build a functional simple ME network (controller, creative cell, drive with couple storage cells, crafting terminal) without any crashes. Only loading old world produces crashes.

**Comment by lugiaf** [comment]
I also have the same issue
I was using "rv5.alpha build 7", no problem ==> Update "...build 8", crash and world can't be loading 
*Crash log :https://pastebin.com/vpzpu0av ( 30KB over )
so, create New world, without any crashes too. (build 8)
*i am not good at English. Sorry X(

**Comment by unikmhz** [comment]
Managed to narrow the crash down.
> Also, interestingly, I can create new world and build a functional simple ME network (controller, creative cell, drive with couple storage cells, crafting terminal) without any crashes. Only loading old world produces crashes.

When I load this new world and place a ME chest near this small network, the game crashes.
