### ISSUE TITLE
Cant use items in ME whilst Autocrafting is processing

### ISSUE THREAD

**Issue by 0Chameleon0** [AppliedEnergistics/Applied-Energistics-2#3151]
#### Description
I am on Foolcraft 2 - Server (multiplayer online)

I am finding when I am autocrafting, whilst a job is running, although I can search the ME Termil, I cannot input or extract items. AE2 is in Easy mode on the server. Once the job is complete, the ME is fine again. I would assume technically, when autocrafting, the items needed are extracted from storage and stored in the processor storage.

I would think that as theoretically the items are transferred to the processor storage for processing in the autocrafting, there should be no strain on the ME. I do separate the connection to the storage on on cable run, and connect the processors to the crafting module by another cable connected to a separate point on the processor (like a subnet). I assume this is correct.

#### Environment

FoolCraft 2 Server

- Minecraft Version: 
- AE2 Version: rv4-stable-1
- Forge Version: 12.18.3.2422

**Comment by brobotato** [comment]
How much power are you feeding into your ME system? I have had this issue before and it turns out that the controller was running out of power. Try feeding more into it.

**Comment by 0Chameleon0** [comment]
I will put a capacitor between my Power Source (Dimensional Transceiver) and my Power Acceptor and see what it is doing, I will do the same at the Auto-crafting Processors. I will let you know.

 

Thanks for the advice.

 

Regards,

 

Darren

**Comment by mindforger** [comment]
>I will put a capacitor between my Power Source (Dimensional Transceiver) and my Power Acceptor

that won't help, place an ME energy cell on your network instead
reason explained with following example:

ME System with an energy capacity of let's say 2k ... energy is filled in every single tick and drain is calculated also per tick ... so when your craftin request and passive energy drain uses more than 2k energy in one single tick (yes that is possible) you will run out of energy for one tick until it is refilled and the system is unusable in this tick! 

calculate your max power input by: Max ME System Energy Capacity / Tick

**Comment by 0Chameleon0** [comment]
Thanks mindforger, Ill try that

**Comment by 0Chameleon0** [comment]
Thanks mindforger, this appears to have resolved my problems.

 

This is greatly appreciated, I have been trying to work on this for weeks 😊
