### ISSUE TITLE
Energy acceptator doesn't work anymore

### ISSUE THREAD

**Issue by Hifros** [AppliedEnergistics/Applied-Energistics-2#3156]
Connection between AE2 flux and RF flux from other mods such as Immersive Engineering and Thermal Dynamics by using a Energy Acceptator has no energy flowing. I think a fix is needed.

Minecraft Version : 1.12.1
AE2 Version : appliedenergistics2-rv5-alpha-7
Forge Version : 14.22.1.2478

#### Environment

- AE2 Version: 
- Forge Version:

**Comment by fscan** [comment]
As always, please provide logs and screenshot to help us identify the issue.

**Comment by Ommina** [comment]
Not to take away the importance of providing logs and anything else that might provide some detail toward solving a particular problem -- in this case,  #3046 is pretty much the summary.

**Comment by fscan** [comment]
Immersive Engineering and Thermal Dynamics work perfectly fine with FE Caps. I'm using them myself together with AE2, So no,  #3046 should have nothing to do with it.
