### ISSUE TITLE
[Question] Charged Certus Quartz Ore

### ISSUE THREAD

**Issue by TheSnowyChickens** [AppliedEnergistics/Applied-Energistics-2#3158]
Charged Certus Quartz Ore question.

You can see in the picture, that Charged Certus Quartz Ore are not like the other Ores. (all the little black boxes)
Now my question, is this only because the particles?

![2017-10-14_16 58 45](https://user-images.githubusercontent.com/29357962/31576751-9e140fc0-b101-11e7-8275-41f88ea02788.png)

Im fly in the Spectator mode simply in the underground.

- Minecraft Version: 1.12.2
- AE2 Version: Beta1
- Forge Version: 2512

**Comment by Flithor** [comment]
I also found this problem, it does not stop rendering the invisible sides, which obviously affects rendering performance

**Comment by fscan** [comment]
I honestly don't have an idea what i am looking at in the screenshot. 
I recently worked around a vanilla/forge bug regarding creative picking, maybe this helps.
Regarding backside rendering: There's some special stuff going on while baking to make it glow but the rest is a standard json model with multiple texture layers. I have no influence over the culling (afaik).

**Comment by mindforger** [comment]
the backface culling is a feature that improved rendering performance significantly and made classic texture approach for x-ray impossible, so this is more like a quality of life thing imho ... i would suggest to invest a bit amount of time into fixing this when there is nothing to do on other parts .... yeah i know this was kind of sarcastic :P ... but maybe it can be put on the todo at the very end?

**Comment by fscan** [comment]
I'm closing this for now. If there is an actual issue other then "they look different when messing with the rendering engine" please open a new issue. I'm also skeptic about any measurable performance impacts, it's not like the GPU is fill limited with minecraft.

**Comment by TheSnowyChickens** [comment]
Good job, you fixed the missing texture from "The One Probe" :D
(left corner from the screenshot)

**Comment by fscan** [comment]
Yeah, that's related to the creative picking "fix"
