### ISSUE TITLE
Cell Workbench card slots crash on mouse click

### ISSUE THREAD

**Issue by PieExplosion** [AppliedEnergistics/Applied-Energistics-2#3159]
#### Description
In Cell Workbench with any ME Storage Cell inserted in cell slot, left or right clicking either card slot with or without an item or card on cursor or in the slot crashes the client.  Shift-clicking a card into the slots does not cause the crash.

#### Environment
Issue discovered in a custom 1.12.2 modpack using rv5-alpha-8.  Issue replicated in MultiMC instance containing only Forge and AE2 rv5-beta-1 in Single Player.  Crash log: https://pastebin.com/fuSALdqV

- Minecraft Version: 1.12.2
- AE2 Version: rv5-beta-1
- Forge Version: 14.23.0.2512

**Comment by b0bst3r** [comment]
Beat me to it, getting same crash trying to insert inverse card in the slot on a view card contents.
