### ISSUE TITLE
Visual glitch with encoded patterns

### ISSUE THREAD

**Issue by bbgott** [AppliedEnergistics/Applied-Energistics-2#3161]
#### Description

When holding shift to preview what an encoded pattern contains, rather than seeing the preview the pattern just disappears.  Letting go of shift makes the pattern reappear
#### Environment

Tested with multiple mods and with AE2 alone.  The behavior is the same
- Minecraft Version: 1.12.2
- AE2 Version: rv5-beta-1
- Forge Version: 1.12.2-14.23.0.2500

**Comment by fscan** [comment]
Can you be a bit more specific? What item/recipe is it happening on? Do you have logs, screenshot?

**Comment by bbgott** [comment]
In this first screenshot I have created an encoded pattern for a chest as an example.  You can see the encoded pattern in my inventory.
![2017-10-15_10 48 31](https://user-images.githubusercontent.com/314107/31586429-85a3389a-b196-11e7-9eed-0dec5de1f644.png)
When I hold down shift, the encoded pattern is supposed to show me that it is a pattern for a chest by changing to an icon of a chest.  Instead, it just disappears.
![2017-10-15_10 48 42](https://user-images.githubusercontent.com/314107/31586431-88949026-b196-11e7-9343-17971b9fe659.png)

I do not see any lines added to the log when it happens.

**Comment by fscan** [comment]
Can you reproduce this with any other item then a chest? 
I don't know much about the rendering process, but it looks to me the chest item model is rendered with a TESR, so the baked model we get is empty. I don't really know how to fix this, maybe move to a TESR for the encoded pattern? Maybe someone with a bit more insight into this can help.

**Comment by bbgott** [comment]
Ok, It looks like it may just be models that have a TESR maybe.  I tried the same process for making sticks or a furnace and they showed up just fine.  
![2017-10-15_13 46 59](https://user-images.githubusercontent.com/314107/31587897-63e322d8-b1af-11e7-8bd4-ca8461e7e34b.png)

**Comment by Yoosk** [comment]
Pretty sure its related to oredictionary enabled in pattern, if it is, they tend to disappear.

**Comment by fscan** [comment]
OreDict shouln't affect the output (rendered item).
 I'm sure its because the chest item has a custom renderer (eg not a BakedModel). The good news is that there are not a lot items that fall under that category.
