### ISSUE TITLE
Inscriber Ticking GridNode server crash

### ISSUE THREAD

**Issue by valeriantech** [AppliedEnergistics/Applied-Energistics-2#3164]
#### Description

Server crashes when inscribing an item without a name press in the bottom slot. This happens both in SP and MP. Crash log is from SP instance with only ae2 and ae2stuff for testing.

[crash-2017-10-17_18.01.00-server.txt](https://pastebin.com/b1heP5j8)

#### Steps to reproduce

1. Make a name press (I named mine "Return Only")
2. Insert name press in top slot of inscriber.
3. Insert item to name (I used an ME Interface)
4. Server crashes.

#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: rv5-beta-1
- Forge Version: 14.23.0.2512

**Comment by fscan** [comment]
This is fixed in git.
