### ISSUE TITLE
Max number of quantum network bridges?

### ISSUE THREAD

**Issue by rahangar** [AppliedEnergistics/Applied-Energistics-2#3165]
I'm using appliedenergistics2-rv4-stable-1 in 1.10.2.

I don't have an issue - just a question.   I'm working on a giant build.   What is the max number of quantum network bridge pairs ?

thanks!

**Comment by Flithor** [comment]
The role of the quantum network bridge is just link each other between two separate physical locations network.
A physical network can set up multiple quantum network bridge.
Although there have a real upper limit, but is very large you do not have to worry about.

**Comment by mindforger** [comment]
always chunkload the bridges and attached networks or your server will die from recalculations :D when the chunks get unloaded .... also check the max chunks loaded config in your forge.cfg ... or was it an ini?

**Comment by rahangar** [comment]
Yay!.  Thanks much.   I'll be going for 400 pairs :-)
