### ISSUE TITLE
ME Drive client crash

### ISSUE THREAD

**Issue by Diam0ndWarri0r** [AppliedEnergistics/Applied-Energistics-2#3170]
So i was making my network and when i placed ME Drive my screen froze and turned blue(mix of white and blue)and crashed. I tried re logging in but i woud just crahs when loading my chunk. I had to go to mcedit to delete block so i can re log on with no problems. I also placed other blocks from the mod:ME chest,ME controller,terminal... No crash. Other mods seem to be workin fine but this issue is delayng release of my modpack but i dont think other mods are and issue. On crash it gives me: 
"The game crashed whilst tesselating block model"
And this:   "The game crashed whilst tesselating block model
            Error: java.lang.NullPointerException: Tesselating block model"

It is curently too late to make video about it right now. Instead i can only provide log files and crash reports.

Logs:
[latest.log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1403410/latest.log)

[2017-10-20-7.log.gz](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1403411/2017-10-20-7.log.gz)

This is log for first crash.
[2017-10-20-2.log.gz](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1403413/2017-10-20-2.log.gz)

Video:
all help apriciated

- Minecraft Version: 1.10.2
- AE2 Version: rv4 stable 1.10.2
- Forge Version: 1.10.2-18.3.2511(recomended in curse/twitch launcher)

**Comment by fscan** [comment]
Please try to remove OptiFine and post a log without it if it still happens.

**Comment by Diam0ndWarri0r** [comment]
Alright I'll test it now.

**Comment by Diam0ndWarri0r** [comment]
Finished testing and it loads world with drive just fine, I am able to place ME drive normally but optifine was there to stabilize my framerate so I don't know what to do now.

**Comment by fscan** [comment]
OptiFine is closed source and messes with the rendering system. We are simply not able to debug/fix any problems caused by it. Maybe they have a newer version. Or try to move the drive to a different location, the log said something about connected textures (also something we are not even using).

**Comment by mindforger** [comment]
Optifine has a github report it over there

**Comment by Diam0ndWarri0r** [comment]
Quick update: I created new world for testing with optifine and i didnt crash so i loaded my original world and also placed it outside and i didnt crash. It was potifines lightning error.
