### ISSUE TITLE
cable facades dont show in jei

### ISSUE THREAD

**Issue by joshuasuperboy** [AppliedEnergistics/Applied-Energistics-2#3172]
I want to ask how to get cable facades to show up in jei. I tryed to search how to do that but no results were found. I dont know why they are not showing up in jei like seen is this photo
![2017-10-22_14 57 09](https://user-images.githubusercontent.com/32559193/31865775-fd7d3c16-b728-11e7-8ad5-2669b6b536f5.png)
This is the only way to know how to craft them like below.
![2017-10-22_14 57 46](https://user-images.githubusercontent.com/32559193/31865780-23b68f36-b729-11e7-93e3-ec88914e9e66.png)
I been having to guess what blocks can be made in to cable facades. Its really hard to know the different types of facades. If you know whats wrong let me know and thanks. I tryed to give as much detail as i could.

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv5-alpha-8
- Forge Version: 14.23.0.2515

**Comment by nigrum-dente** [comment]
A comment by the creator of JEI, Mezz:

> Mods that generate items dynamically, like covers, multiparts, etc, can really clog up JEI and even slow it down. There's also not a lot of benefit to displaying them all, so I added a config to stop showing them once they're above a certain number. Thousands of buildcraft covers had broken, crashing models and made JEI startup much slower, so I added this config.

https://github.com/mezz/JustEnoughItems/issues/923#issuecomment-313833270

**Comment by fscan** [comment]
Like @nigrum-dente  wrote, all the recipes would clog up jei. You should be able to craft the facades with almost any block.
