### ISSUE TITLE
ME Chest Crash when right click

### ISSUE THREAD

**Issue by Enderlook** [AppliedEnergistics/Applied-Energistics-2#3173]
**Version:** appliedenergistics2-rv5-alpha-8 | Minecraft 1.12.2 | Forge Release 1.12.2-forge1.12.2-14.23.0.2512

I've just make an ME Chest in my survival world and connect it to the network (ME Controller + 6 Vibration Chamber + arround 15 ME Storage + 1 ME Terminal) and I after click the block the game crashed.

I make a creative world to test it and happened again, then I removed from the config the ME Chest (to dissintegrate it) and in the creative world it worked, the block dissapear, but in my survival world it didn't, the game crash before delete the block (also Minecraft stop working). Now I can't open my survival world.

I've two crash reports:

- https://pastebin.com/i7rM0V7L
- https://pastebin.com/QewF5Vzy (In THIS crash, it's seem (I don't know how to read the crash very well) that the problem was Steves Cars... but I didn't do anything with that mod)

**PD:** I've unistalled Steves Cars and I can open the survival world, but... cables became Quantum Rings, Vibrations Chambers becomes Certus Quarz Ores, ME Controlles became a block of static water and other blocks become block of another mods... please... help me :(.

**Comment by fscan** [comment]
For the first crash: Please use the latest version. This bug is fixed in newer versions.
The rest looks like world corruption. Sadly i can not help you there.

**Comment by Enderlook** [comment]
Ok, thanks you, I didn't know that there was a new version of Applied Eenrgitics, thanks!
