### ISSUE TITLE
[Suggestion] Add Applied energistics for 1.11.2 

### ISSUE THREAD

**Issue by Seba10** [AppliedEnergistics/Applied-Energistics-2#3180]
AE2 Needs to have version 1.11.2 because Refined Storage is destroying popularity of this mod

**Comment by fscan** [comment]
Not happening, we do not have the time to maintain yet another version. Especially with 1.13 on the horizon.

**Comment by Seba10** [comment]
Ok i can wait like 4 and 5 months

2017-10-26 22:05 GMT+03:00 fscan <notifications@github.com>:
