### ISSUE TITLE
BuildCraft 6.1 preparation

### ISSUE THREAD

**Issue by asiekierka** [AppliedEnergistics/Applied-Energistics-2#319]
Hello,

Since BuildCraft 6.1 is slowly becoming a more and more stable release, I just wanted to open up an issue stating what has to be changed:

- BuildCraft 6's power API is only available in BuildCraft 6.0. The BuildCraft 5 API should be off by default with BC 6.1+, as while BuildCraft 6.1 supports it, it prefers Redstone Flux greatly. (Note: BuildCraft 6.0 also supports the BC 5 API, meaning the BC 6 API can just be removed at any moment.)
- BuildCraft 6.1.2 or 6.1.3 should bring the IFacadeItem API AlgorithmX2 requested, meaning it will not have to hook inside BC code any longer.

**Comment by thatsIch** [comment]
Well I guess, we can remove BC facade integration in AE2
else we will never get rid of MJ5 and MJ6
