### ISSUE TITLE
Network shuts off randomly with plenty of power!

### ISSUE THREAD

**Issue by 34486** [AppliedEnergistics/Applied-Energistics-2#3197]
#### Description
Latest Version of AE2 (Stated below) I am on my pack and I NEVER have had this issue before! 

#### Environment
Alright, Everything was working just fine, I was working on another storage room and autocrafting room. Everything was working, when I come back from watching a video it was off, it turned on. I go back to the main base and it was flickering on and off. I gave my draconic core as many creative cells as possible and then later added creative energy cells to the controller itsself, (16 of them) and it STILL goes on and off no matter how much power it seems to get!!! Here is a video: (Link Below) 

https://youtu.be/ieZO3iSUXGc

- Minecraft Version: 
- AE2 Version:  RV4-Stable-1 (Latest) thats the only version that is a full release for 1.10.2
- Forge Version: Forge1.10.2-12.18.3.2511 Java 1.8.0_144 64 bit. 5120 Gb dedicated to pack, 8 to server.

I supplied the information that SHOULD be neded, if not let me know, I hope I can respond in time before this gets closed somehow. Thanks!

**Comment by fscan** [comment]
Your problem is not the amount of power you input, but the total capacity the AE2 network can handle (eg the network uses more power at a time that it can store). Add a dense energy cells (the one from AE2) to your system. The top 2 number you see in the network tool should go up, they are quite low for that big a system.

**Comment by 34486** [comment]
Alrighty, thanks! Was just wondering about that but never have seen it done from numerous videos, possibly my network is much larger. Took a while to autocraft somewhat around 6 stacks of dense cells lol! 1.32 GRF sounds good and is stable now! Many many thanks!
