### ISSUE TITLE
Network Tool Inventory Deletes Items When Drag-and-Dropping

### ISSUE THREAD

**Issue by leasoncre** [AppliedEnergistics/Applied-Energistics-2#3199]
Any drag-and-drop action into or out of the network tool seems to be deleting items.
+You Can Shift-Click stacks into and out of the tool, as well as drag-drop items into EMPTY slots in the tool
-You Can't Drag-drop items into the tool to an existing stack (whole stack gets deleted)
-You Can't Drag-drop items/stacks OUT of the tool (deletes the item/stack from your inventory when you interact with another AE2 block, items stay in inventory until then)

#### Description

Steps to reproduce:
1. Open network tool inventory
2. Put a bunch of cards in it (have been using JEI to spawn them into my inventory)
3. Shift-Left-Click them -OR- Drag-Drop them into empty slots
[[opening AE2 inventories and shift-left-clicking stacks into block-inventory works]]
4. Open any AE2 block inventory screen
5. Drag card/cards from either Block inventory or Player inventory >and Drop into> the Tool's inventory
6. -> Slot is now empty (All items in that slot were deleted)
7. Right-click (part of a stack) a stack from the Tool's inventory and place in player inventory (you don't have to be in a block-inventory for this part)
8. Exit block inventory
9. Open player inventory (Take note that the item is still there)
10. Open an AE2 block inventory
11. -> Card(s) are no-longer in player inventory (deleted)

#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-1
- Forge Version: 14.23.0.2517
- PACK: ATM3, SINGLE PLAYER, manually updated AE2 to latest version and issue persists

**Comment by fscan** [comment]
Thanks for the report, this should be fixed in the next release.
