### ISSUE TITLE
Certain recipes no longer working as of Forge 1.12.2-14.23.0.2532

### ISSUE THREAD

**Issue by ruifung** [AppliedEnergistics/Applied-Energistics-2#3200]
As of Forge 14.23.0.2532, probably due to the changes in how ShapelessRecipes are handled,
certain crafting recipes in AE2 are broken, such as the ones for fluix glass cables.

By broken, I mean that the result doesn't even show up in the inventory's 2x2 crafting grid, despite the recipe being correct.

I have tested in forge 14.23.0.2531, and it does not have the issue.

As I am unfamiliar with how recipes are handled, it could also be an issue with the Forge changes.
Therefore, I'm leaving this issue just to notify about the potential breakage.

- Minecraft Version: 
- AE2 Version: rv5-stable-1
- Forge Version: 1.12.2-14.23.0.2532

**Comment by ruifung** [comment]
Also on another offtopic note, what a nice issue number.

**Comment by fscan** [comment]
I am unable to reproduce. Can you test with just AE2?

**Comment by ruifung** [comment]
Tested with only AE2 and NEI. (Multiplayer Server), Doesn't seem to work.

Interesting to note that it only happens on a multiplayer server though. So it's most likely a forge issue?

![image](https://user-images.githubusercontent.com/1073945/32579435-d53a5fb2-c51b-11e7-85f9-8190ac588b58.png)

**Comment by fscan** [comment]
Hmm ...ok, i tested only locally. The server is running the same forge version?
I'll have to test, this is strange.

**Comment by ruifung** [comment]
Yes, the server is running the same forge version. This is a fresh world, fresh install with only AE2, CoreChickenLib, NEI, JEI... and that's just about it.

**Comment by p455w0rd** [comment]
Related to https://github.com/MinecraftForge/MinecraftForge/pull/4472 ? This is very odd as even @grum approved the changes made in the Forge PR that supposedly fixed this? Specifically here: https://github.com/MinecraftForge/MinecraftForge/pull/4472/files#r146108157 they talk about sidedness..this is supposed to be fixed lol

**Comment by SnowShock35** [comment]
@p455w0rd I see you also stumbled on this. Currently having the same issue with dw20 pack too.

**Comment by SnowShock35** [comment]
E.g. this recipe should be grout. Nope! it's flint. https://ss.blamesnow.co.uk/2017/11/1510256741-28caf578.png (╯°□°）╯︵ ┻━┻

**Comment by fscan** [comment]
I haven't had the time to look at it yet, but i think we do override the recipe factory for parts.  Maybe there is some sidedness issue we introduce with this.

**Comment by yueh** [comment]
Cannot reproduce it with neither 2532 nor 2537.

And with NEI being one of the worst offenders in relation to JEI and probably recipes in general, I would not be surprised should it be an issue. Also it fails the "can you reproduce it with just AE2?"

**Comment by LC14199** [comment]
Confirmed that this is also occurring in the ATM3 modpack, after upgrading to version 4.5. 

I'll attempt to reproduce this with AE2 and Forge in a standard installation.

**Comment by cjburkey01** [comment]
Occurs on a custom pack I play with my friend. Using AE2 rv5-beta-3 and Forge 14.23.0.2537 with a Multiplayer server. Sometimes it looks like the recipe is craftable, but upon crafting the item is not received and a ghost recipe remains in the crafting table.

**Comment by ruifung** [comment]
@yueh In this case, reproduced using only AE2, no other mod, no JEI, NEI, etc. On a multiplayer server instance with, as stated, only AE2.
Works fine when testing in a single player world.

![image](https://user-images.githubusercontent.com/1073945/32687221-f1a03f0e-c6f2-11e7-8eab-134fdb10ba6f.png)

**Comment by phit** [comment]
thanks @fscan 😃

**Comment by AgentA1cr** [comment]
I'm currently using rv5-stable-2, and cable anchors still appear to be uncraftable unless using a full durability quartz cutting knife.

**Comment by cjburkey01** [comment]
Fixed in Forge [14.23.0.2539](
http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.0.2539/forge-1.12.2-14.23.0.2539-changelog.txt).

**Comment by fscan** [comment]
i'm reopening this until this is fixed in forge

**Comment by fscan** [comment]
fixed with https://github.com/MinecraftForge/MinecraftForge/commit/836be2e3a0d83d3ae54fec37c1da9332acc4d2b3

**Comment by ThatGrzegorzB** [comment]
seems to happen again, using forge 1.12.2-14.23.1.2601
