### ISSUE TITLE
Me Network Not Working

### ISSUE THREAD

**Issue by Colton-Slayden** [AppliedEnergistics/Applied-Energistics-2#3203]
#### Environment

I am building an AE unit in Foolcraft 2 which has the channels turned off. I 2 41x3 walls of drives and when connected to a crafting terminal i can see the items going in but cant manully put items in and cant take them out.

- Minecraft Version: 1.10.2
- AE2 Version: 
- Forge Version: 2511

**Comment by Colton-Slayden** [comment]
Power issues the power accept-er limited the power being pulled in.

**Comment by mindforger** [comment]
also install an energycell or a dense ... the equation for power input is input = "ME capacity" / tick and your Me system has only a few blocks with AE power capacity except for the energy cells
