### ISSUE TITLE
ME Terminal Show exact amount of items.

### ISSUE THREAD

**Issue by Colton-Slayden** [AppliedEnergistics/Applied-Energistics-2#3204]
I was wondering if there was a way to set the terminal to show the exact amount of items in a me unit instead of just 20k. I believe that it used to tell you when you hover over the item the exact quantity and would like that back or if it is somehow turned off.

#### Environment

- Minecraft Version: 1.10.2
- AE2 Version: rv4-stable-1
- Forge Version: 2511

**Comment by mindforger** [comment]
can not imagine how bad this could possibly collide with other mods, but having an exact number beeing readable in the lore of the item would really be nice

but i am unsure if there is anything beeing backported to 1.10

**Comment by yueh** [comment]
It's already displayed as part of the tooltip.
