### ISSUE TITLE
Wrench bug

### ISSUE THREAD

**Issue by felipeleite5w** [AppliedEnergistics/Applied-Energistics-2#3208]
#### Environment

- Minecraft Version: 
- AE2 Version: rv3-beta-6
- Forge Version:10.13.4.16.4

If I someone use these wrenchs(Flux-Infused, Nether quartz wrench, and Buildcraft wrench ) in someone claim (protected from grieffing) it removes ME Terminal and some Thermal Dynamic items too! What shoud I do ?

**Comment by fscan** [comment]
Sorry, rv3 is no longer supported. Also as this not only applies to AE2, report to the mod doing the "claiming".
