### ISSUE TITLE
Requestable items are not considered for autocrafting

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#3212]
Requestable items are not considered as source for autocrafting requests, if not also marked as emitable items.

This results in everything having to announce an infinite amount as emitable items, thus the calculation cannot fail due to missing items. Further emitable items will also prevent autocrafting from being used at all for missing items.

The main issue here should be that [MECraftingInventory.java#L141](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/6e81f698c0025a3df2fb1b78c280fe8708fa2318/src/main/java/appeng/crafting/MECraftingInventory.java#L141) creates the initial inventory by simulating an extraction, which will cause it to lose the data about requestable amounts as these are not available for instantaneous access. Yet it is necessary to avoid the crafting to operate on non extractable items and fail later on starting the job.

**Comment by repairmant** [comment]
I'm now getting this too after updating to rv6 stable 6.

Example: request 1 charger it says im missing 2 Fluix Seed (another ME Interface has a custom pattern for seeds to pure with it going to water/growth machines) when I have that pattern in an ME Interface next to 4 Molecular Assemblers

**Comment by PixelmonPRO** [comment]
Any news?

**Comment by Technici4n** [comment]
No clue what should be done about this, if anything. I can't find where we handle requestable items,

**Comment by Technici4n** [comment]
Requestable item support has been removed for now.
