### ISSUE TITLE
Colored names aren't colored in AE2 Terminals

### ISSUE THREAD

**Issue by Xiaminou** [AppliedEnergistics/Applied-Energistics-2#3216]
I don't know this is intended but I think it should show colored names in the terminals.
![2017-11-11_21 16 30](https://user-images.githubusercontent.com/8670392/32693139-bedd4566-c725-11e7-9135-9f8a779bd7e9.png)
![2017-11-11_21 16 32](https://user-images.githubusercontent.com/8670392/32693140-bef5aec6-c725-11e7-9507-3e5c7003ca08.png)

#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-1 
- Forge Version: 2537
- Mods: [list.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1464047/list.txt)

**Comment by fscan** [comment]
theres already a fix (#3205) for this

**Comment by Xiaminou** [comment]
Woops, I didn't look at pull requests for this one, sorry.
