### ISSUE TITLE
Shift Double-clicking items in the ME Crafting Terminal also inserts items in the crafting area

### ISSUE THREAD

**Issue by Xiaminou** [AppliedEnergistics/Applied-Energistics-2#3220]
#### Description
Shift Double-clicking items in the ME Crafting Terminal also inserts items in the crafting area.
I don't think it should.

#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-1 
- Forge Version: 2537
- Mods: [list.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1464047/list.txt)

**Comment by fscan** [comment]
AFAIK, double-click is not a vanilla behavior. What should it do? I'm guessing something like shift-click?
Please report to the mod adding it.

**Comment by Xiaminou** [comment]
Are you sure it's not? Because I don't know what other mod could be adding that since it's applied energistics only.

**Comment by Xiaminou** [comment]
It's actually Shift Double-Clicking, I made a mistake in the description.

**Comment by Xiaminou** [comment]
Here: <insert video that's not uploading to youtube for some reason>
Applied Energistics only in this instance, same behavior.
To be clear the expected behavior is for it to put the similar items from your inventory only in the ME Network

**Comment by Xiaminou** [comment]
@fscan Can we re-open this please?

**Comment by fscan** [comment]
Ok, I'll have a closer look at it when i find the time.

**Comment by fscan** [comment]
After looking having a better look at the double click behavior, i fixed some issues related to your other issue. The behavior described in this issue should only happen if either your storage is full or you don't have enough power to transfer all the stacks. Either way this is not worth it complicating the GUI code further (generally blacklisting fake slots is not an option, as we allow shift clicking into eg. filter slot)
