### ISSUE TITLE
Encoded Pattern Colored Items

### ISSUE THREAD

**Issue by Xiaminou** [AppliedEnergistics/Applied-Energistics-2#3224]
#### Description
Some items do not display colors when holding shift with encoded patterns in your inventory.
![2017-11-12_22 47 03](https://user-images.githubusercontent.com/8670392/32744481-e2a97dbc-c8af-11e7-9175-9ad0c262b5d0.png)
![2017-11-12_22 47 04](https://user-images.githubusercontent.com/8670392/32744482-e2be65a6-c8af-11e7-9de5-8abebeedf8f4.png)
![2017-11-12_22 47 06](https://user-images.githubusercontent.com/8670392/32744483-e2d6fe0e-c8af-11e7-8f27-3837677d0c3d.png)

#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-2
- Forge Version: 2540
- Mods: [list.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1467155/list.txt)

**Comment by Xiaminou** [comment]
Is this a duplicate? I couldn't find any similar issues in my search.

**Comment by fscan** [comment]
probably in the same boat as #3161

**Comment by Xiaminou** [comment]
Oh okay, I thought it was a different one because my patterns do show up.
