### ISSUE TITLE
On Fast Graphics settings bad rendering item in machine 

### ISSUE THREAD

**Issue by friksasha** [AppliedEnergistics/Applied-Energistics-2#3225]
#### Description
On Fast Graphics settings bad rendering item in machine. Item is rendered from the back side of the machine. On front side not rendering.
On appliedenergistics2-rv2-stable-10 all normal rendering. But ExtraCells-1.7.10-2.3.14b requires a version rv3.
On Fancy i not want played.

I also assemble versions 
8b4a39085e53e6974c3ae0f04f60dae0a8791aaa
12cf76a62f51a7b66d3623c468704deada090bc1
824ec1eccbf0e1976e703b90a86a940ab774a6ea

#### Environment

- Minecraft Version: 1.7.10
- AE2 Version: rv3-beta-1 - rv3-beta-6
- Forge Version: 10.13.4.1614
- Extracells: ExtraCells-1.7.10-2.3.14b
- IndustrialCraft: Industrialcraft-2-2.2.827-experimental.jar
- Win7
- GTX 750
- lwjgl 2.9.1
![2017-11-14_06 44 07](https://user-images.githubusercontent.com/25547088/32762165-cdf5a3ec-c908-11e7-9e4f-7f1d15df540f.png)
![2017-11-14_06 44 13](https://user-images.githubusercontent.com/25547088/32762167-cfaee18a-c908-11e7-9669-9e3b461ccef9.png)

**Comment by GuntherDW** [comment]
1.7.10 is no longer supported.
Check if the same issue still happens in the newer 1.12 version and re-open if it still happens.
