### ISSUE TITLE
Formation Plane Duping Bug

### ISSUE THREAD

**Issue by Shoxxo** [AppliedEnergistics/Applied-Energistics-2#3227]
Check that Video below!

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/NPk2jGCN5dw/0.jpg)](https://www.youtube.com/watch?v=NPk2jGCN5dw)

- Minecraft Version: 1.7.10
- AE2 Version: appliedenergistics2-rv3-beta-6
- Forge Version: 7.99.4.1614

**Comment by yueh** [comment]
We no longer support 1.7.10 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.

**Comment by Shoxxo** [comment]
Why someone rederict support for the best game version that is not fair. Please send me a fix and ill do that by ma hands.

**Comment by mindforger** [comment]
the issue was not only on AE but also on the mod site that has this strange item spawner ... extra utilities is it? and it was known issue on both sides 

as far as my memory goes the issue was partiall resolved but never fully backported and both mods continued to 1.12 at that stage

**Comment by Shoxxo** [comment]
can you tell me the commit where it was fixxed on here? Please?

**Comment by mindforger** [comment]
thats way to long ago i am very sorry

**Comment by Shoxxo** [comment]
Is it possible to tell me what year it was fixxed?!
