### ISSUE TITLE
Autocraft 'Start' button not working

### ISSUE THREAD

**Issue by noxiaz** [AppliedEnergistics/Applied-Energistics-2#3234]
I have been playing for some months with the mod pack "Age of Engineering", i have billion of items in my ME storage.
I have created recipe for autocrafting "Dimensional Transceiver", which use a lot of items for crafting it.

When i select 1 "Dimensional Transceiver" to be build, it give me this screen: 
![image](https://user-images.githubusercontent.com/3165178/32990340-3570f3c8-cd28-11e7-8dbc-48737b8e9c08.png)

When i press the "Start" button nothing happens, i tried spam it, tried selecting a CPU, but nothing helps. - Sometimes i can wait 5 minutes and then try craft again, and then it will work. It doesnt only happen for "Dimensional Transceiver".

I have no idea how to fix this.

**Comment by mindforger** [comment]
>i have billion of items in my ME storage

this is telling me your system has a large size, do you have enough enrgy cells installed?
it's not about power input beeing available, but input beeing limited to ME_Capacity/t, so when oyu increase the buffer it can accpet more power

**Comment by noxiaz** [comment]
I have now added 6 "Dense Energy Cell", and i have as well transfered all "Ores" out of the system, to make the amount of storage smaller, this made the crafting window faster, but still the "Start" button have no effect at all.

**Comment by fscan** [comment]
You are sure your crafting cpu's are big enough? Can you post log files please?

**Comment by noxiaz** [comment]
I'm sure they are big enough.

Here is my log file: 
[latest.log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1485672/latest.log)

If anything else is needed, or access to the server im playing on so you are able to see the problem, just let me know.

**Comment by yueh** [comment]
This happens with inventory like storage drawers reporting incorrect amounts being stored or in some other cases sharing them across multiple tile entities like ender chests and thus reporting the inventory multiple times. (the mod not vanilla ones).

There is pretty much nothing we can do about it, except recommending to not use them for this cases.
Which exact mod/tileentity it causes is hard to tell, but it is one (or more) attached with a storage bus.
