### ISSUE TITLE
[Question] Inventory Custom name shown in Interface Terminal

### ISSUE THREAD

**Issue by TheSnowyChickens** [AppliedEnergistics/Applied-Energistics-2#3236]
Hello,

its maybe only a question or suggestion, but is it possible to rename a chest for example into "CPU Pattern Crafting" and this chest is connected with an Interface and then, the custom name is shown in the Interface Terminal instead of the block name.

Chest renamed with an Anvil.

![suggestion](https://user-images.githubusercontent.com/29357962/32992762-e5eec4b6-cd4e-11e7-86b5-6f7b0747184f.png)

- Minecraft Version: 1.12.2
- AE2 Version: Stable 2
- Forge Version: 2546

**Comment by yueh** [comment]
#1008
