### ISSUE TITLE
Wrench bug

### ISSUE THREAD

**Issue by felipeleite5w** [AppliedEnergistics/Applied-Energistics-2#3237]
#### Environment

- Minecraft Version: 1.7.10
- AE2 Version: rv3-beta-6
- Forge Version: 10.3.4.1614

All wrenchs (including ae2 wrench) removes a lot of items like All Me Terminals and ME Cables in protected areas ( plugin used is GrieffPrevention)

**Comment by yueh** [comment]
We no longer support 1.7.10 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
