### ISSUE TITLE
Cables disconnecting from ME Capability Adapter on server restart

### ISSUE THREAD

**Issue by jp-bennett** [AppliedEnergistics/Applied-Energistics-2#3244]
#### Description
Playing through the Modern Skyblock 2 pack, and using the ME Capability adapter block to place AE2 machines in a compact machine.  Playing Single player, and when loading the world up, all the AE2 cables are disconnected from the capability adapter, requiring breaking and replacing the cable.

#### Environment
Single Player, on a Linux desktop.  No crash is associated with this bug.

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-2
- Forge Version: 14.23.0.2549

**Comment by yueh** [comment]
That is not an AE block, report it to whichever mod adds it.

**Comment by jp-bennett** [comment]
Yeah, I was afraid of that.  Thanks for the info.
