### ISSUE TITLE
Cutting knife do not work anymore when loosing durability

### ISSUE THREAD

**Issue by zISKo666** [AppliedEnergistics/Applied-Energistics-2#3245]
Hello found this recipe issue.
When using a cutting knife to create some cable anchors it looses durability and is unusable then.
Tested it in single and multi player.
Also tested it with just Minecraft, Forge and AE2 installed.

![2017-11-22_20 12 11](https://user-images.githubusercontent.com/6992216/33145823-269d24ba-cfc2-11e7-91a9-01b87ab6c5ef.png)
![2017-11-22_20 12 17](https://user-images.githubusercontent.com/6992216/33145826-2a970234-cfc2-11e7-870a-4caa2c355ab3.png)

- Minecraft Version: 1.12.2
- AE2 Version: rv5.stable build 2
- Forge Version: 2550

**Comment by fscan** [comment]
This is "fixed" in dev. Either wait for the next release or downgrade forge to before 2532.
