### ISSUE TITLE
ProjectE Compatibility

### ISSUE THREAD

**Issue by Colton-Slayden** [AppliedEnergistics/Applied-Energistics-2#3253]
Lots of people are wanting projecte to be able to map AE2 but because it uses custom crafting it has not been down.
#### Environment

- Minecraft Version: 1.10.2, 1.*
- AE2 Version: 
- Forge Version:

**Comment by fscan** [comment]
I'm sure there is some kind of API or config for ProjectE to add emc values. There is nothing special about AE2 items that prevent that.

**Comment by Colton-Slayden** [comment]
That is incorrect ProjectE cannot map items to AE2 because of how it crafting API is set up if there was i wouldnt be here

**Comment by mindforger** [comment]
main issue is, projectE is generating stuff from nothing or duplicating items simply, which the crafting system can not understand, this has been discussed and declined multiple times in the past, projectE would have to find a way to add some item-like ingredients to fit normal crafting recipes, becuase the recipe:

1 Stone -> n Stones is impossible

**Comment by Colton-Slayden** [comment]
I dont think you are understanding what i am asking, and there is not an api because the projecte api can only map default minecraft crafting while AE2 uses a custom crafting api, i do not want to add it to the ME network because there is a mod that bridges that i am asking to allow access to the crafting api so projecte when mapping items will auto add emc to items instead of having to do it by hand each time after each update.

**Comment by Colton-Slayden** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/367

**Comment by fscan** [comment]
Then state what you want do. The phrase "custom crafting api" makes no sense to me.
My GUESS: 
1) You want to assign emc values to AE2 items? I dont see an issue with this, or why it wouln't work.
2) You want AE2 to auto-assign emc values? Not happening. Just do 1)  .. it's not like we change our items/recipes at a regular basis.

And pleeeeeaaaase use punctuations, i have a very hard time parsing your sentences.

**Comment by Colton-Slayden** [comment]
Okay AE2 uses a custom crafting wrapper, non-vanilla crafting.
ProjectE cannot auto map the items because of this.
Need to integrate the custom crafting wrapper into the api to allow ProjectE to access it and auto map items. 
Not AE2

**Comment by fscan** [comment]
No. 
90% of AE2's items come from vanilla (or forge to be precise) crafting recipes. Assign the rest manually.

**Comment by Colton-Slayden** [comment]
If you actually looked at it it doesn't happen that way and many issues are open about it so obviously its a problem.

Very Rude supposed to be help
