### ISSUE TITLE
Invalid Patterns cause FPS to drop

### ISSUE THREAD

**Issue by Xiaminou** [AppliedEnergistics/Applied-Energistics-2#3255]
#### Description
Invalid Patterns cause FPS to drop when pressing shift.
https://youtu.be/Q7r_1cTtbdY

#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-3
- Forge Version: 2556
- Mods: [list.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1518165/list.txt)

**Comment by yueh** [comment]
Cannot really reproduce it indev. There might be a small FPS drop, but that can also be something random as it also fluctuates in the same area witout invalid patterns.

But there is one code path, which might be a bit problematic in combination with some mods and how badly recipes are handled in 1.12 by forge and some mods make it even worse.

I'm just testing a slightly optimized build, but there is no guarantee that it really helps. Outside this particular path, it is just vanilla/forge item rendering. Thus outside of our control.
