### ISSUE TITLE
Port request

### ISSUE THREAD

**Issue by Tyfyter** [AppliedEnergistics/Applied-Energistics-2#3258]
#### Environment

- Minecraft Version: 1.11
- AE2 Version: N/A
- Forge Version: 13.20.0.2223

Please port either the 1.12 version, or the 1.10 version to 1.11.

**Comment by yueh** [comment]
No, just use 1.12.

**Comment by Tyfyter** [comment]
so you're saying I should switch to an inferior minecraft version with less mod compatibility because you don't want to port something to 1.11 even though you most likely could do so without programming more than a few changes?

**Comment by mindforger** [comment]
>without programming more than a few changes?

this argument looks like you are qualified enough to send in an pull request with those few littkle changes :)

we are happy to have a look at it then ... but keep in mind, you would have to maintain any issues arising from this version then
