### ISSUE TITLE
Scrolling mouse wheel on items to roll them out of AE2 updating issue

### ISSUE THREAD

**Issue by SorryLorry** [AppliedEnergistics/Applied-Energistics-2#3264]
**Scrolling items out of chests provides a smooth update in the player's inventory whereas when I scroll items out of habit from AE2, it does not update smoothly.**

Example : Scrolling out iron one by one from a chest 
Each time i scroll, 
Chest :  - 1 iron
Inventory : + 1 iron
From here on it goes as logical -1 , +1 .

But when I do it with AE2...

Example : Scrolling iron from AE2 crafting terminal 
It would be logical to assume the same,
AE2 Storage : -1 iron
Inventory : + 1 iron.

**_However this happens instead_**
1st scroll
AE2 storage: -1 iron (Total: 1)
Inventory:+0 iron (Total: 0)
2nd scroll
AE2 storage: -1 iron (Total:2)
inventory: +2 iron (Total:2)
3rd scroll
AE2 storage:-1 iron (Total:3)
Inventory: -1 iron (Total:1)
4th scroll
AE2 storage:-1 iron (Total:4)
Inventory:+3 iron (Total:4)

It has a trend where every odd scroll the inventory decides to half the amount. And that half can be briefly seen on the cursor tip as well. Then every even scroll, it fixes itself.

And if i accidentally do it too quickly, it freezes up my game (though i think that's my hardware)
- Modpack : Stranded Alone modpack version : 1.9.8.1
- Minecraft Version: 1.10.2
- AE2 Version: appliedenergistics2-rv4-stable-1.jar
- Forge Version: forge-12.18.3.2511

**Comment by fscan** [comment]
That functionality is implemented by MouseTweaks (or InventoryTweaks, not sure). It should really not do that for the terminals (1.12 versions seem to disable this).
You can "shift-scroll" items from the terminal to the mouse pointer and back.
