### ISSUE TITLE
Unable to ask system to request very very large recipe programs

### ISSUE THREAD

**Issue by SplitInfinitive** [AppliedEnergistics/Applied-Energistics-2#3267]
Asked my system to make a 16meg storage component from Extra cells.  System forgets how to make pure fluix crystals even though the recipe works for smaller requests and DOES have the relevant required materials/recipes installed in the appropriate machines.

Not really game breaking, just kind of annoying.

**Comment by mindforger** [comment]
no versions, no pictures, no service ....

no seriously .. you lack ANY information to reproduce or debug your issue!

**Comment by SplitInfinitive** [comment]
https://imgur.com/a/jUMgb  please let me know what other information you need

**Comment by bookerthegeek** [comment]
@SplitInfinitive we need you to go and follow the instruction in the template that is given when you click on new issue.

**Comment by yueh** [comment]
As @mindforger already said, nearly no information given.

Even the screenshots are pretty useless as they only show that you can craft seeds as well as the storage components. But no proof about the system being able to craft pure certus from seeds. This step is completely ignored, but most likely the cause why it does not work. E.g. producing different seeds with the recipe compared to the ones needed for pure certus.
