### ISSUE TITLE
Mekanism crusher recipes not working

### ISSUE THREAD

**Issue by XxZajoZzO** [AppliedEnergistics/Applied-Energistics-2#3271]
#### Description
You can't use mekanism crusher to crush certus quartz into dust

#### Environment
Win10 64-bit
Java 1.8.0_25
Log: https://paste.ubuntu.com/26147490/

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv5-stable-3
- Forge Version: 14.23.1.2562

I tried deleting generated recipes in the config folder but that didn't help.

Not sure if this problem is because of AE2 or Mekanism.

**Comment by yueh** [comment]
Mekanism removed the recipes the added themselves for whatever reason.
