### ISSUE TITLE
Network Reset Involving ME P2P Tunnels

### ISSUE THREAD

**Issue by Draxhax** [AppliedEnergistics/Applied-Energistics-2#3277]
- Minecraft Version: 1.12.2
- AE2 Version: rv5 stable 2
- Forge Version: 14.23.0.2531
- Modpack: All The Mods 3 v5.1 - Multiplayer

Issue:

Disconnecting a cable from behind a P2P tunnel (breaking it's link to the ME controller) and replacing it causes the network to flicker / reset constantly until cable connected to the front end of the input side is disconnected and reconnected. I discovered this when I went to swap out a piece of smart cable with dense smart cable and the network started flickering constantly instead of just a brief moment to reconnect the channels.

This is what my controller shows connected currently. Note that the first two items are actually wrong to begin with. I have 7 1k crafting storage and 7 crafting units.
[Network Details 1](http://puu.sh/yE7wn/49e134dedf.png)

This is the output side of the P2P tunnel. Note that none of the other P2P tunnles are currently being used.
[Output ME P2P Tunnel 1](http://puu.sh/yE7Cd/9f24a143c5.png)

This is the input side of the P2P tunnel. This is only a few blocks away and located in the same chunk as the ME controller.
[Input ME P2P Tunnel 1](http://puu.sh/yE7EB/b63cfcdf2a.png)

I am currently using 27 channels on the input side of the P2P tunnel. 7 Crafting Units/1K Crafting Storage Units, 7 Interfaces, 7 Import Buses, and 6 Export Buses. All wired up using dense smart cable in the front to handle the channels and ME Glass Cables. Cable Anchors are utilized to control where each device hooks up to the dense cable.
[Input Dense Cable - Channel Usage 1](http://puu.sh/yE7Gh/c9cd9918a9.png)

I remove this cable, located behind the Input ME P2P Tunnel.  Not the smart cable directly connected to the P2P tunnel, but the cable after that. Please note that I could remove it from behind the Output ME P2P Tunnel as well or anywhere between the P2P tunnels and the controller and achieve the same results.
[Removed Dense Cable Behind Input ME P2P Tunnel](http://puu.sh/yE7SK/a18081880c.png)

The network updates as expected, no longer showing the 12th P2P Tunnel or the devices on the other side. Everything seems normal.
[Input ME P2P Tunnel - Online and Unlinked](http://puu.sh/yE7VV/163a7da975.png)
[Output ME P2P Tunnel - Offline and Unlinked](http://puu.sh/yE7XH/53ba281ea1.png)
[Network Details Confirming Changes](http://puu.sh/yE7YO/162ce228dd.png)

At this point, I reconnect the Input ME P2P Tunnel back to the system.
[Replaced Dense Cable](http://puu.sh/yE81J/91a039e185.png)

This is where the network begins freaking out instead of simply bringing the items back online.
[Network Flickering](http://puu.sh/yE8k7/d17ebc1d70.gif)
[0 Channels on Input P2P ME Tunnel](http://puu.sh/yE8nB/2d7075278c.png)
[Device Missing Channel on Input P2P ME Tunnel](http://puu.sh/yE8oM/f3f67652c3.png)
[Device Missing Channel on Output P2P ME Tunnel](http://puu.sh/yE8qF/aacaf6bd24.png)

The network will continue to do this until I break and replace the cable on the other side of the Input ME P2P Tunnel.
[Input P2P ME Tunnel Online After Breaking Cable](http://puu.sh/yE8t7/813750b3f3.png)

At this point, I can place the cable back and everything will go online again.
[Dense ME Cable - 27 Channels](http://puu.sh/yE8vm/f05e0b15c7.png)

I hope this was enough information to diagnose the issue. I attempted to replicate the issue in my singleplayer 'test bed' world in that modpack using the exact same design (minus the blocks used for aesthetics), but was unable to replicate the problem in SSP. I am not the owner of that server, so unfortunately I cannot pull any logs or restart it to see if the issue can be replicated after that.

**Comment by yueh** [comment]
Most likely a power issue.

**Comment by mindforger** [comment]
make sure yoiu have enough system power capacity using energy cells, input is limited to basically "system capacity" / tick

**Comment by Draxhax** [comment]
The behavior certainly looks to be power with the flickering, but the amount of power I'm supplying is excessive compared to what is being used. As a test, while the network was fully functioning, I removed my power source, leaving only the power in the controllers and the dense energy cell. Energy usage in the controller showed 184.9 RF/t with no energy generation and the stored power slowly draining. The difference in RF being caused by a pattern, interface, crafting, and security terminal along with an extra import bus I have attached since I reported this issue. More has been added to the network since then, but I disconnected those cables so as to not interfere with the test. The controllers finally lost power after 15 minutes, but it took me a moment to start the timer, so it probably lasted a couple seconds longer than that.

At the time I had 48 MRF in reserve that it could pull from, but now I have 24 BRF (and going up). There's no additional draw going on, the controllers and the dense cells do not show them as going empty when I look at them directly (via WAILA or whatever is giving me the tooltips in the corner). As long as I don't break the connection to the P2P tunnels, everything works fine. As soon as I break the connection and try to bring it back online, it freaks out until I disconnect it from the other side of the P2P tunnel and reconnect it.

**Comment by Draxhax** [comment]
And seriously, look at the frickin' screenshots. I didn't spend all the time and effort to show you there's nothing wrong with my power to have you suggest power.

**Comment by Draxhax** [comment]
I created my own server to replicate this issue and will attempt again in SSP soon.

I recreated this using a creative energy cell, 1 controller, 2 PTP tunnels, some dense cable, a glass cable, and a couple crafting units with 1K storages.

[Example](http://puu.sh/yI6aj/130968186f.png)

**Comment by yueh** [comment]
Just managed to reproduce it and it is a basic power issue.

What happens is that both sides boot on their own and run on their small internal buffer of 200 AE. To give the network some time to settle in, fill energy buffers, and so on, it will need to be powered for 30 ticks before turning active.

With 4 (actually just 3) crafting cpus, 2 tunnels and the controller it is just enough passive consumption, to last slightly less than 30 ticks with the internal buffer. This powers the network down, gives the other side time to settle down and just power the controller/P2P. Which it can. Then reconnect both sides and repeat it again.

When rewriting the energygrid for 1.12, I choose it to buffer 200 instead of 1000 previously to better fit the other values for energy cells/controllers. Thus it can now start to noticed a bit earlier. Increasing it would just result in pushing it back to slightly larger networks.

Having a large enough buffer on both sides to survive the first few ticks is sufficient to prevent it. Or even just backfeed it with a quartz fiber will prevent it, as it does have a physical energy connection and not rely on an inactive P2P connection.

**Comment by Draxhax** [comment]
Thanks for tracking down the root of the problem, the information you've provided is quite interesting and I'll keep it in mind in case I run into this again. So far, just me swapping which tunnel was the input and output has taken care of it for now. I just wish I had noticed that I reversed the order to begin with.

Thanks again for looking into this!
