### ISSUE TITLE
Interface not being able to insert item into another interface for subnetwork processing

### ISSUE THREAD

**Issue by Neoxon4865** [AppliedEnergistics/Applied-Energistics-2#3278]
Image for reference :https://imgur.com/gallery/cNhVC

Hi, I am trying to replicate this video https://www.youtube.com/watch?v=xatLaJDWxyk and https://imgur.com/a/ZvCAi to craft simple recipes like clay>hardened clay. In the picture, I have the pattern inserted into the flat interface and it is connect to the block interface. I have attached a storage bus into the redstone furnace with clay as the config. Any time I want to craft 10 hardened clay, nothing happens until I cancel the request and the items actually craft. 

I was able to replicate this in 1.10 in project ozone lite and it is working properly.

- Minecraft Version: 1.7.10 (project ozone 2)
- AE2 Version: rv3 beta 6
- Forge Version: 10.13.4.1614

**Comment by mindforger** [comment]
for subnetworking you connect an interface to a storage bus, the interface acts as a slave, presenting every content to the connected storage bus

i can't remember last time i tried to access and interface with an interface, i am not sure if this is working like you'd expect but i am not sure how it should work then either :) interfaces are a bit special

**Comment by leagris** [comment]
It is and was a valid setup with 2 interfaces: (it also worked in 1.7.10)
- Place machine pattern in nterface A
- Have Interface A connect Interface B from sub-network.
- Upon crating request of item in pattern, Interface A passes ingredients to interface B's own inventory space.

@Neoxon4865 Be sure to employ a machine pattern and not a workbench pattern, as the destination Interface B inventory has no workbench layout.

**Comment by Neoxon4865** [comment]
@leagris I got it to work by placing a cable anchor on top of the block interface. It seem like the problem was my 2 interface was still connected to the main network when one should be connected to the sub. The weird part is that the system i nthe image is working fine however in 1.10 without a cable anchor
