### ISSUE TITLE
P2P Tunnels Resetting

### ISSUE THREAD

**Issue by jiak1** [AppliedEnergistics/Applied-Energistics-2#3279]
When I assign an EU P2P tunnel about 30 seconds later it stops working and I have to reassign it with a memory card.

This was in FTB Beyond.

- Minecraft Version: 
- AE2 Version: rv4-stable-1
- Forge Version: 12.18.3.2422

**Comment by jiak1** [comment]
It seems to happen around about 15 seconds after setting it.

**Comment by mindforger** [comment]
not sure if this is an EU thing there, do other p2p work normal if you set em up in the same location and binding?

did you double check there is enough power **capacity** in your system? (input is limited to capacity/tick having unlimited input means nothign then, or try with a creative energy cell for testing)

please provide a few screenshots including the p2p endpoints and the connection in between (if possible)

**Comment by jiak1** [comment]
I posted a video of it here: https://youtu.be/efs4Fe2mX_g

**Comment by mindforger** [comment]
Hmmm. that does look fine setup wise indeed.

**Comment by jiak1** [comment]
The World Can Be Found Here: https://www.dropbox.com/s/bfaokk3wlslj9z9/world.zip?dl=1
It Is Using FTB Beyond

**Comment by yueh** [comment]
1.10 Forge is somewhat unstable and can led to dataloss. Probably not in this case, but it's hard to ignore it.

Could also be a bug with the EU P2P in particular. I rewrote a good amount of them and the power system for 1.12, which fixed some edge cases. But this is simply too large to backport (as well as a breaking change). So it will most likely stay that way.

Some sort of periodic block update might also cause it to reset. No guarantees, but certainly worth trying.

**Comment by Vexs** [comment]
I can confirm this issue is happening in the age of engineering modpack.

Forge 12.18.3.2511
