### ISSUE TITLE
P2P Desync?

### ISSUE THREAD

**Issue by Xiaminou** [AppliedEnergistics/Applied-Energistics-2#3280]
#### Description
When using a Memory Card on a P2P Tunnel to copy its setting to the Memory Card it will show that P2P as if it had been tuned to what the Memory Card contained previously.
Video for clarification: https://youtu.be/4ONuysSnej8

I haven't tested it yet but my guess is this is a desync between client and server and therefore it only happens on dedicated servers.

#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-3
- Forge Version: 2562

**Comment by yueh** [comment]
Cannot reproduce.
