### ISSUE TITLE
only getting 20 items when taking item from terminal

### ISSUE THREAD

**Issue by moopig** [AppliedEnergistics/Applied-Energistics-2#3283]
#### Description

Using any of the terminals i'm only picking up 20 items at a time, after crafting a few more recipes with JEI the number seems to be decreasing by 4.

#### Environment
Modern Skyblock 2 Normal mode, Version: 2.7.3.2 on a locally hosted dedicated multiplayer server

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-3
- Forge Version: 14.23.1.2566

**Comment by mindforger** [comment]
sounds like a power issue, add some energycells, input is limited when system capacity is low

Please try with a creative cell to verify the issue
