### ISSUE TITLE
Network disables when chunk unloads/server resets

### ISSUE THREAD

**Issue by gahertrj** [AppliedEnergistics/Applied-Energistics-2#3285]
We are running the direwolf 20 pack for 1.12.2. Essentially any time a chunk unloads or a server restart happens the AE2 network will cease to get power through the energy acceptor and you have to pick up every block and place it again to get it to work. 

- Minecraft Version: 1.12.2
- AE2 Version: rv5
- Forge Version: 14.23.1.2566

**Comment by mindforger** [comment]
do you have energy cells in the system? sounds like it is unabbbbble to scan the network bec ause it is loosing power again and again?

input power is limited by the capacity of the system, available power means nothing if the capacity is limited

also, do you use something like spongeserver or any other "performance enhancing" mods?

**Comment by gahertrj** [comment]
I haven't used and AE2 energy cells. It's basically a top tier thermal expansion cell attached to the energy acceptor which is then wired to everything with the fluix cables. The power never goes out unless there is a server reset or the chunk gets unloaded. Once that happens all the machines need to be picked up and replaced in order to accept power again.


We are using pretty much the basic direwolf pack which I don't think has any performance mods. The system would stay fully powered for days as long as the server doesn't reset.

**Comment by gahertrj** [comment]
I haven't used and AE2 energy cells. It's basically a top tier thermal
expansion cell attached to the energy acceptor which is then wired to
everything with the fluix cables. The power never goes out unless there is
a server reset or the chunk gets unloaded. Once that happens all the
machines need to be picked up and replaced in order to accept power again.

We are using pretty much the basic direwolf pack which I don't think has
any performance mods. The system would stay fully powered for days as long
as the server doesn't reset.

On Dec 20, 2017 03:57, "mindforger" <notifications@github.com> wrote:

do you have energy cells in the system? sounds like it is unabbbbble to
scan the network bec ause it is loosing power again and again?

input power is limited by the capacity of the system, available power means
nothing if the capacity is limited

also, do you use something like spongeserver or any other "performance
enhancing" mods?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3285#issuecomment-353003867>,
or mute the thread

**Comment by mindforger** [comment]
then install some ... i clearly said available power means NOTHING when there is not enought capacity to keep the system up for a single server tick

**Comment by gahertrj** [comment]
I clearly said that the power never fluctuates on and off. It runs for days
on end with zero issues through thousands of server ticks. It's only a
server restart that disables all the machines and they will not restart
without being picked up and placed again. After that point they will run
again for days without issue until a server reset. The only thing clear
from your replies is a bit of a dickish attitude.

**Comment by fscan** [comment]
I love people who come here for help, get a valid helpful response and somehow feel the need to insult.
If you tried the suggested solution and it didn't work, please say so. No need to insult a someone who sacrifices their free time to help some random person.

**Comment by gahertrj** [comment]
I simply haven't had the chance to try it yet as I am at work. You asked
questions and i answered them. Then you attacked me in a rude manner. I
don't know why you expected a praising thank you response for a rude
comment. I fully intend to try your solution, what I'm trying to understand
is why you think it would help. Because the input power obviously enough to
run the tiny system I'm using, this is shown by the fact that it works
flawlessly 99% of the time. Only failing when a server restart happens. The
assertion that there isn't enough power to run it seems flawed to me since
the power is sufficient to run it for days before a reset. Nothing else in
the system changes.

**Comment by fscan** [comment]
Nobody attacked you. He tried to explain to you twice that it doesn't matter how much energy you can theoretically pump in, if your network doesn't have the maximum capacity to do all the operations at once (which may happen on startup). The best way to extend that capacity is to install AE2 energy cells. Not saying that this is definitely the problem, but its a very common issue.

**Comment by gahertrj** [comment]
That explanation is a lot clearer than the original poster explanation. I
took his comment as an attack because of the all caps nonsense. He implied
that the power was fluctuating due to lack of energy flow into the system.
If that was the case it wouldn't be able to run flawlessly between resets.
But from what you're describing it sounds like the startup requires all the
power at once which could be higher than the cable can process since it's
the 4k rf cable. That doesn't explain why items don't kick on once I start
removing parts from the network. But if it just flat out stalls completely
then either a higher capacity cable or a storage unit on the ae side would
fix it.

**Comment by ktole1999** [comment]
if the system is stable and sustaining as long as the chunk is loaded then there is enough power being applied. if the issue happens when chunk unloads then what else could cause it other than something is not  acknowledging the presence of power? would that be the controller? I am just trying to understand.

**Comment by fscan** [comment]
No, again .. its not about cables or how much you pump into the AE2 network. Its about how much the network itself can store internally. Its like RAM vs HDD space. The AE2 network is one big energy storage from which all the devices draw from (and contribute to in case of a cell). If its empty it stops working, doesn't matter if it gets refilled the next tick.

**Comment by ktole1999** [comment]
if it gets refilled on next tick it should work? why the need to break and replace? i know nothing about code so smite me if needed. lol

**Comment by mindforger** [comment]
simple example ... constructing network costs X amount where normal operation only consumes Y where Y < X .. if X > System Capacity the system starts building, aborts due to power loss and tries again the next tick when it got refilled .... while it CAN run with input and capacity > Y, it can not run when capacity < X the power needed to initialize the system .... energy cells are simply a buffer to compensate power surges

i sometimes write things in CAPITAL letters where i could make it bold text instead but on mobile it is quite difficult to use markdown due to limited keyboard

sorry if it felt rude to you

**Comment by gahertrj** [comment]
No worries, text has that impact sometimes. I understand the probable issue
and will run some tests this evening when I get the chance. I do appreciate
the insights, truly.

**Comment by ktole1999** [comment]
thanks for clarification.
