### ISSUE TITLE
[1.12. 2] Wooden Gear

### ISSUE THREAD

**Issue by JonasCiss** [AppliedEnergistics/Applied-Energistics-2#3289]
If binnies Mods are present in my mod pack the normal wooden gear of Applied Energistics is deactivated. I try now to figure out which mod that does.
Does Applied Energistics have a function that replaces wooden gears if another wooden gear is present?

**Comment by fscan** [comment]
AE does  not replace anything. It just does not register some things if other oredict alternatives are present (like silicon, or the wooden gear). You can disable this in the config file.

**Comment by JonasCiss** [comment]
It was a bug with Binnie's Mods. It was closed.
