### ISSUE TITLE
Disabling AE2 security also disables wireless capability

### ISSUE THREAD

**Issue by ouroborus** [AppliedEnergistics/Applied-Energistics-2#3292]
#### Description
Disabling security in the config removes the ME Security Terminal making wireless access unavailable.

I'd like to see a security mode where ops have full rights to any ME system regardless of how the players have chosen to configure their security.

#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-3
- Forge Version: 14.23.1.2570

**Comment by yueh** [comment]
Yes, the security system is an essential requirement for the wireless functionality to link them against a specific network. There is simply no way around it.
