### ISSUE TITLE
image of Certus Quartz is not showing properly

### ISSUE THREAD

**Issue by masterterp** [AppliedEnergistics/Applied-Energistics-2#3295]
The ore of certus quartz is working its just that after i mine the material the image shows up as to black blocks and two pink blocks. 
looks like it is broken.
thought i should let you know.

Im usiing the most recent version of ae2 rv5 stable 3 12.2
Im on minecraft 12.2 
Forge version
- Forge Version: 1.12.2-14.23.1.2555

**Comment by fscan** [comment]
Can you please post a screenshot and a recent log file?

**Comment by masterterp** [comment]
![2017-12-31_19 58 10 - copy](https://user-images.githubusercontent.com/34935607/34465337-0e79423a-ee65-11e7-9390-9483ce24a1cc.png)
[2017-12-31-1.log - Copy.gz](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1595587/2017-12-31-1.log.-.Copy.gz)

**Comment by masterterp** [comment]
sorry for the post its a different mod that i am using that is causing problems.
Just uses the same name.

**Comment by masterterp** [comment]
i was mining one of your ores and it turned into a croparia item that looks broken
