### ISSUE TITLE
Spacial Storage crashes game

### ISSUE THREAD

**Issue by Zacxen** [AppliedEnergistics/Applied-Energistics-2#3296]
When I attempt to use any large Spacial Storage system or a small one with an ae2 multi-block crafting unit, everything gets moved into the Storage cell then Minecraft crashes.

I am running Maverick's Tech Overload Modpack. I tried installing the newest version of AE2: rv5-stable-3 and it still crashes. It happens only when transferring the crafting multi-block structure and with 70x70x70+ storage areas. If you reload after the crash everything is then in the storage cell and can be brought back into the overworld just fine.

https://pastebin.com/ruw12uNq

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-3
- Forge Version: 14.23.0.2549

**Comment by yueh** [comment]
Please remove the SpatialCompat mod as it will whitelist incompatible TEs and cause crashes/world corruption/etc due to it. But worst case it might already be corrupted in some sort.

**Comment by Zacxen** [comment]
I removed all mods except ae2, created a new world and attempted to put the multi-block crafting CPU into a storage cell. Minecraft still crashed. Also, this issue was happening before SpacialCompat was installed. Here is the latest crash log.

https://pastebin.com/ZAFCD5VM

**Comment by yueh** [comment]
Yeah, I found a issue with crafting cpus and how forge handles restoring tile entities in some cases causing it to duplicate them. (Which seems to be a bit related to the order the cpu is transfered)

But just in case, the approach that mod uses is extremely dangerous and will result in dataloss at some point.
