### ISSUE TITLE
Upgrades for Portable Cell.

### ISSUE THREAD

**Issue by AlgorithmX2** [AppliedEnergistics/Applied-Energistics-2#33]
Add two upgrades for the Portable cell.

-Annihilation Pane Upgrade : Allows the the Cell to absorb a Items from your inventory from its built in Whitelist, that you set with a Shift click on the upgrade itself.

Example : It can pick up Cobblestone as your mining and it will automaticly go into the cell.
Example 2 : It can Pick up all the Ore as your Mining, 

-Formation Pane Upgrade : Allows the cell to Drop things into your Inventroy from its Inventory from its built in Whitelist, that you access with a Shift click on the upgrade. Keeps up to a Stack in your Inventory of Whitelisted items.

Example : It fills adds a stack of Cobble to your inventory and fills it as you use it.

Example 2 : Your out Mining and your pick Breaks, it automaticly Adds another to your inventory when it sees it broke.

Originally Posted by ExodusDeath

This issue was migrated; For original details see http://ae-mod.info/Tracker/0322/

**Comment by Technici4n** [comment]
Sounds like a cool feature, but I don't think we are ever going to implement it due to limited manpower, having to figure out a nice config GUI, etc. Can happen in an addon or a PR though.
