### ISSUE TITLE
Add dimension to chunklogger reporting

### ISSUE THREAD

**Issue by ouroborus** [AppliedEnergistics/Applied-Energistics-2#3306]
#### Description
Currently `/ae2 Chunklogger` only logs the coordinates but not the dimension.

#### Environment
- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-3
- Forge Version: 14.23.1.2570

**Comment by yueh** [comment]
It is mostly a debug tool for our own use (indev).

If you want something reliable and feature rich, you should request it as forge feature or maybe some dedicated server tool. Not rely on some random mod providing it.
