### ISSUE TITLE
Cell Workbench Configuration is not saved

### ISSUE THREAD

**Issue by max-kamps** [AppliedEnergistics/Applied-Energistics-2#3307]
When trying to configure a storage cell in the Cell Workbench, the configuration is either not saved in the first place or lost after a short while.

#### Description
Let's say I fill the cell workbench with some items
![image](https://user-images.githubusercontent.com/11182284/34473311-7f3a7f5e-ef71-11e7-85ee-2398f510ae26.png)

after saving the configuration the item seems to have stored the information (`Partitioned - Included Precise`)
![image](https://user-images.githubusercontent.com/11182284/34473316-875f5dd0-ef71-11e7-8b0e-4e465844a0f6.png)

After taking the cell out of the workbench the lore of the item no longer contains the partitioned text, but it still has one NBT tag
![image](https://user-images.githubusercontent.com/11182284/34473318-8b8aa5b8-ef71-11e7-9f40-17897fa75471.png)

The NBT data appears to contain no items
![image](https://user-images.githubusercontent.com/11182284/34473320-8eefc076-ef71-11e7-924b-8c2617b1c897.png)

#### Environment
- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-4
- Forge Version: 14.23.1.2562

**Comment by yueh** [comment]
Could there be any mod conflict as I cannot reproduce it SP or MP?

**Comment by max-kamps** [comment]
Sorry, looks like this was problem was PEBKAC. I was pressing the wrong button.
Thanks for your help though. 😅
