### ISSUE TITLE
unable to craft quantum ring

### ISSUE THREAD

**Issue by mindforger** [AppliedEnergistics/Applied-Energistics-2#331]
as the title states i am not able to craft it in SMP, i can not pull it from the crafting window and when using a regular crafting table i can pull it but it vanishes the moemnt i drop it and the items spew out

maybe it's related to that we just disabled channels as we were out of possible solutions for doing the great centralized PC system at the moment :P did not test it yet with enabled channels

**Comment by Zaflis** [comment]
Reason we can't craft quantum ring without channels, is because there is a dense cable in recipe. But there are no dense cables even in NEI.

**Comment by mindforger** [comment]
@Zaflis this issue is way past decomposition and well known, no need to dig up the topic ... and by the way @yueh i support removing the "diable channel option" verybody should have acclimated to the channels at some point
