### ISSUE TITLE
[1.12.2] Metallurgic Infuser form Mekanism shows as "Nothing" in interface terminal

### ISSUE THREAD

**Issue by Morpheus1101** [AppliedEnergistics/Applied-Energistics-2#3310]
Forge v *.2583
AE2 v stable-4

When the mettalurgic Infuser is connected to the AE2 autocrafting network, it displays as "Nothing"
![javaw_2018-01-04_18-52-34](https://user-images.githubusercontent.com/10524952/34556020-797f303a-f180-11e7-9453-e47201953921.png)

**Comment by yueh** [comment]
That is because they are unusable from certain sides, which causes the fallback to be used for these. Other rotations are fine.
