### ISSUE TITLE
Molecular assembler wont accept pattern

### ISSUE THREAD

**Issue by abbyyssimal** [AppliedEnergistics/Applied-Energistics-2#3311]
Hey all im using minecraft 1.12.2, appliedenergistics2-rv5-stable-4, and forge -14.23.2558. the molecular assembler will take a crafting pattern but will take a processing pattern. I can not also put any items in the assemblers inventory manually. is this a known bug??

- Minecraft Version: 
- AE2 Version: 
- Forge Version:

**Comment by fscan** [comment]
http://ae-mod.info/Molecular-Assembler/

Note, the assembler still needs power!

**Comment by abbyyssimal** [comment]
I have an interface on one side and smart cable connected to another for power still cannot craft. Also cannot put crafting pattern directly into the assembler.

**Comment by fscan** [comment]
Please provide more information. What do you want to achieve? Attach some screenshots of the setup and the pattern you want to put into the assembler. Also, read the documentation i linked again .. if you want to manually craft with the assembler you don't need the interface.

**Comment by abbyyssimal** [comment]
I have followed the instructions and videos. I have never had this issue before. still cant craft manually either.
[screenshots.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1607193/screenshots.zip)

**Comment by abbyyssimal** [comment]
tried in new world with only ae2 mod installed same results

**Comment by fscan** [comment]
And you are sure this is a crafting pattern and not a processing pattern? I haven't noticed any issues with autocraftig, and i tried manual crafting just the day before (dont have access to mc right now).

**Comment by abbyyssimal** [comment]
yup definitely a crafting pattern

**Comment by yueh** [comment]
That's a crafting pattern. So everything is fine, except you mixed crafting and processing up.

**Comment by abbyyssimal** [comment]
no  when i use the crafting pattern the assembler will not work. but it does work with a processing pattern. i was using 1 charged 1 nether 1 redstone for 2 fluix. and will not craft
