### ISSUE TITLE
Molecular assemblrr problem

### ISSUE THREAD

**Issue by abbyyssimal** [AppliedEnergistics/Applied-Energistics-2#3312]
I had to open this again. the problem is not resolved yet
when i use the crafting pattern the assembler will not work. but it does work with a processing pattern. heres a link to a video i made of the issue.
https://youtu.be/RaRrcGCoK20

**Comment by yueh** [comment]
As already said, you mix up crafting patterns with processing patterns (and the other way round).

**Comment by abbyyssimal** [comment]
but when i try  making  a crafting pattern it does not work

**Comment by abbyyssimal** [comment]
ive been a fan of applied energistics for a long time and have never had this issue. i know the difference between a crafting pattern and a processing pattern. the crafting pattern will not work just stays schedualed

**Comment by fscan** [comment]
Look, in the video when you're saying you are making a crafting pattern, you are actually making a processing pattern. It even says so when you hover over the toggle button on the right. Another clue is that you have multiple output slots, which makes no sense for a crafting recipe.
