### ISSUE TITLE
ME Cables appears to be buggy.

### ISSUE THREAD

**Issue by WaterXCubic** [AppliedEnergistics/Applied-Energistics-2#3313]
ME Cables in Applied Energistics appears to be behaving weird as seen in the picture
here : https://imgur.com/a/SCEDD

#### Description
As seen in the picture, the AE cable is "broken" from the other cables for no reason. Normally it should be able to connect to the other cables.

#### Environment
- Minecraft Version: 1.10.2
- AE2 Version: appliedenergistics2-rv4-stable-1
- Forge Version: SpongeForge 1.10.2-2477-5.2.0-BETA-2731

**Comment by yueh** [comment]
We do not support Sponge officially.

Should you be able to reproduce it without it, please update the issue accordingly and we will reopen it.
