### ISSUE TITLE
Storage cell DIM - Question

### ISSUE THREAD

**Issue by Keaton1188** [AppliedEnergistics/Applied-Energistics-2#3314]
Hey, just wondering if its possible to disable the Storage Cell DIM's (perm) ?

**Comment by fscan** [comment]
I guess your are talking about the spatial storage dimension? You can disable the SpatialIO feature in the config. Then just delete the dimension if it already exits.

**Comment by Keaton1188** [comment]
@fscan What config is this in.. I'm not seeing it.

**Comment by fscan** [comment]
"SpatialIO" under network features.

**Comment by Keaton1188** [comment]
Got it, thanks
