### ISSUE TITLE
Will the owner of the mod, upload my 1.8.9 port, if I do port it and release it?

### ISSUE THREAD

**Issue by ChaosChorus** [AppliedEnergistics/Applied-Energistics-2#3317]
I would like to upload my 1.8.9 port when im done porting it.

Is it OK,
Does the owner, agree I can? 

Im using eclipse, to port the mod! May be changing it.
I loved the 1.7.10 version ,ad the new 1.12.2 version, but i rarely play those versions, I mostly play 1.8.9!

- Minecraft Version: 1.8.9
- AE2 Version: rv5-stable-4
- Forge Version: IDK

**Comment by yueh** [comment]
Sorry, but we won't support any obsolete minecraft version in any regards.

**Comment by ChaosChorus** [comment]
Wow, so u hate 1.8. Bad enough people have bad computers and the best version for them is 1.8 shame

**Comment by mindforger** [comment]
shame for what?  Do you have the slightest idea of how much trouble it is to maintain only one version of that mod? And more important ... For free?
