### ISSUE TITLE
[1.12.2] Support for No More Recipe Conflict or something similar with ME Crafting 

### ISSUE THREAD

**Issue by Morpheus1101** [AppliedEnergistics/Applied-Energistics-2#3324]
I was wondering if its possible, to have some sort of system that takes into account recipes with the same crafting outlay to be used with the ME Crafting grid or is it more of a case that the recipe system for the ME Crafting cant have that functionality?

**Comment by yueh** [comment]
That is a vanilla feature and it would be up to forge to solve it. Which they do not really want.
Alternatively a modpack author should provide customised recipes.

Mods trying to resolve it retroactively just cause more issues than it is actually worth.
