### ISSUE TITLE
[Feature] "Creative" (non functional) smart/dense smart cables that can simulate various channel capacities

### ISSUE THREAD

**Issue by astrutzenberg** [AppliedEnergistics/Applied-Energistics-2#3325]
There is no (easy) way to make smart/smart dense cables display as if there were multiple channels in use for creative type builds. 

What I was thinking:  

Introduce:
A new controller type (a "display controller"), Visually this would behave exactly like the existing controllers in terms of multiblock rendering, and will connnect to any cables.  
The difference however is that any cables that attach to it would be rendered inoperable/disabled, and would display as if they were at full capacity.  

These cables would also be allowed to attach to a functioning AE2 network, however since they path back to the display controller, they would be in some sort of inert state (exactly as if you exceeded the capacity of the cable) 

Future idea:  the controller would expose a UI that lets you control the simulated capacity of the cables vs just showing full capacity)

#### Description
Creative build idea 1:  
Different colors of smart cable that are exposed along a wall, with the channel bands lit up as if they were at full capacity, and sink into the ground.....e.g. something like a an organized Data Center wiring---(example image: http://torontowiring.com/wp-content/uploads/2014/09/data-cabling-toronto.jpg )

Creative build idea 2:
Player (in SMP) has a functioning multiblock setup (Molecular Assemblers + ME Interfaces for instance), which are hooked up via a functional (and full capacity) Dense Smart Cable.  

The player would like to be able to attach further dense cables onto this for creative purposes, and have them light up as if they to were at full capacity

 #### Environment
- Minecraft Version:  1.12.2
- AE2 Version: 
- Forge Version:

**Comment by yueh** [comment]
Sorry, but the design goal was/is to always have things visually distinctive. If it looks like a cable, it is a cable or if it looks like channels are used, channels are used. 

Otherwise it will just confuse players unnecessarily. Which is also the reason why there is no decorative controller block.
