### ISSUE TITLE
[Sugestion] less frequent meteorites  

### ISSUE THREAD

**Issue by SimulatorSia** [AppliedEnergistics/Applied-Energistics-2#3326]
It seems like there's an impact in every other biome now adays, true minecraft feel has generated structures few and far between making people work for what they need. I propose making meteorite impacts much rarer, thus making sky stone a rare substance as it truly should. People will have to actually do work to find one.

**Comment by Ommina** [comment]
Isn't this already achieved with the config file?

> D:meteoriteClusterChance=0.1
> I:meteoriteMaximumSpawnHeight=180
> I:minMeteoriteDistance=707

Increasing the minimum distance and lowering the height should both serve to achieve your stated goal.

**Comment by SimulatorSia** [comment]
Oh, I'm sorry, I'll do that, I hope I didn't waste your time, thank you for responding though
