### ISSUE TITLE
Suggestion «Crafting option»

### ISSUE THREAD

**Issue by marciox25** [AppliedEnergistics/Applied-Energistics-2#3327]
I would like to make a suggestion

#### Description

As everyone knows, there are multiple ways of getting a certain ore, eg: Iron Ore, you can make them by smelting the ore directly, or first pulverizing, then smelting the pulverized ore, or even with the Iron crops.

I would like to suggest, if possible, to add a methode, that if you have both patterns of the recipe to get that specific ore, tha you can chose which one to use. Or that ir takes both,
#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv5-stable-4
- Forge Version: 14.23.1.2585

**Comment by yueh** [comment]
Not worth the hassle it would place onto every player.
