### ISSUE TITLE
Massive lag - 1.12.2

### ISSUE THREAD

**Issue by Keaton1188** [AppliedEnergistics/Applied-Energistics-2#3328]
#### Description
Hey, we are getting some massive lag on our Dw20 1.12.2 server linked with Applied Energistics 2, I have checked users bases but we still seem to have the issues.

#### Environment
![untitled](https://user-images.githubusercontent.com/24898745/34902400-a0b42cbc-f812-11e7-9d7c-ef826fd84f2b.png)

- Minecraft Version:  1.12.2
- AE2 Version: appliedenergistics2-rv5-stable-4.jar
- Forge Version: 14.23.1.2585

**Comment by yueh** [comment]
Please provide actual profiling or sampling results. Otherwise there is no way for us to help identifying the issue.
