### ISSUE TITLE
I want to fix the auto crafting BUG

### ISSUE THREAD

**Issue by Ayenlighter** [AppliedEnergistics/Applied-Energistics-2#3329]
#### Description
Hello,I am a AE2 mod little lover.
I use your version "appliedenergistics2-rv4-stable-1",encountered some problems
Please look this picture
![2018-01-13_14 47 54](https://user-images.githubusercontent.com/35393632/34904306-4b6188e2-f87e-11e7-927f-82313272802b.png)

Here you can see the auto crafting of jetpack for each level I set.

Then,the point is here,please look the following two pictures.
![2018-01-13_14 48 00](https://user-images.githubusercontent.com/35393632/34904309-568ae736-f87e-11e7-80d7-b912dec32963.png)

The Tier1 jetpack,I can craft it,it's no problem!
but....
![2018-01-13_14 48 11](https://user-images.githubusercontent.com/35393632/34904312-5d6ae06a-f87e-11e7-9e01-8d76c65f400c.png)

No matter Tier2,3,4 jetpack auto crafting,the above situation occurs.
"The Tier1 jetpack is missing."
I don't know what's wrong with it.
(I used to have this problem in the AAmod battery crafting.)
Is there a solution?
Please give me an answer.
THANKYOU VERYMUCH!!!!!
(I am from Taiwan,and I don't know how to program.
So...Can I fix this bug without writing any program?
If you can ... Can you please release a fix for the wrong version?)
#### Environment

- Minecraft Version: 1.10.2
- AE2 Version: appliedenergistics2-rv4-stable-1
- Forge Version: 12.18.3.2511

**Comment by yueh** [comment]
This is caused by simply jetpacks and their crafting handling. It makes it impossible to consider consider any jetpack as equal to the one required by the pattern. Therefore nothing we can solve on our side without introducing more bugs than it might solve.

**Comment by Ayenlighter** [comment]
So,It is the bug that we can't fix it?
