### ISSUE TITLE
[1.12.2] FEATURE Request: OreDict Support for Processing Patterns

### ISSUE THREAD

**Issue by Morpheus1101** [AppliedEnergistics/Applied-Energistics-2#3331]
Currently in the pack im playing i have a massive amount of Red Sand as apposed to normal sand currently, but that changes back and forth, so when crafting, when i run out of 1 or the other of the sand types, id like it to be able to use the other sand in order to continue to make glass, the issue lies in that this functionality as far as i can tell is not available.

**Comment by yueh** [comment]
#2501
