### ISSUE TITLE
Smart cables ignoring adjacent cable type and upgrade them incorrectly

### ISSUE THREAD

**Issue by ouroborus** [AppliedEnergistics/Applied-Energistics-2#3333]
#### Description

In the screenshot, all connections to the crafting array have eight incoming channels each. However, the middle dense cable is indicating no channels on its attachment to the Molecular Assembler. It seems like dense cables connected to Molecular Assemblers don't indicate channels while regular cables do.

![2018-01-15_03 20 44](https://user-images.githubusercontent.com/392047/34940188-7a530182-f9a3-11e7-98eb-add93e361eda.png)

![2018-01-15_03 27 09](https://user-images.githubusercontent.com/392047/34940321-f32a2220-f9a3-11e7-9a9b-bc4028e5eb19.png)

#### Environment
- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-3
- Forge Version: 14.23.1.2570

**Comment by yueh** [comment]
Actually the smart cable on the bottom is bugged and should render as covered cable.

**Comment by yueh** [comment]
Fixed in rv6
