### ISSUE TITLE
The Quantum Link does not work after being transported to/from a Spatial Cell

### ISSUE THREAD

**Issue by JacobTDC** [AppliedEnergistics/Applied-Energistics-2#3335]
#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: rv5.stable build 4

In order to make it work, you have to break and replace the Quantum Chamber and Singularity.
I don't know why this happens, but my best guess is that it is because you can only have two quantum links using the same singularity pair, and the mod fails to register that the previous Chamber has been destroyed when it is moved to the Spatial Storage.

**Comment by yueh** [comment]
Cannot reproduce it. They work just fine when being transported around for me.
