### ISSUE TITLE
Dupe Acceleration Cards

### ISSUE THREAD

**Issue by mouro001** [AppliedEnergistics/Applied-Energistics-2#3338]
#### Description
Place a Molecular Assembler in the world, put 64 (or any amount) acceleration cards on your offhand, with a empty hand go close to the molecular assembler and shift right click. It will put 5 acceleration cards in the Molecular Assembler and it will give you the rest (59) and you will still keep the ones on your offhand.
Here is a gif:
![Gif](https://i.imgur.com/lCISJQS.gif)

#### Environment
Both Multiplayer and Singleplayer.
- Modpack: Project Ozone Lite v1.3.5
- Minecraft Version: 1.10.2
- AE2 Version: rv4-stable-1
- Forge Version: 12.18.3.2511

**Comment by e30Birdy** [comment]
Confirmed in 1.12 Revelation
