### ISSUE TITLE
Storage bus not storing in separate ME interface

### ISSUE THREAD

**Issue by ManIkWeet** [AppliedEnergistics/Applied-Energistics-2#3343]
It used to be possible to use a Storage Bus to store items into an ME Interface on a separate network. This no longer seems to be the case.

Reproduce: Chest<-import bus-->storage bus|ME Interface

Image for more clarification:
![2018-01-19_23 22 59](https://user-images.githubusercontent.com/4006814/35174492-e92ff6a8-fd6f-11e7-809e-f21d4dfa73ba.png)

Items inside the chest are not imported into the ME Interface. If the ME Interface is replaced with anything else (like a chest), items are imported as expected.

Expected: Items appear in top row of ME Interface.
Actual: Items don't get transferred.

#### Environment

- Single player
- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-5
- Forge Version: 14.23.1.2599
- Log found here: [https://pastebin.com/AZCuDS8g](url)

**Comment by yueh** [comment]
Storage buses never stored anything inside an unconfigured interface.

**Comment by ManIkWeet** [comment]
I guess I have oversimplified my issue...

In a modpack that I'm playing (Modern Skyblock 2) it won't store the items in my network through the Storage bus Interface combo.

Can't reproduce it though...
