### ISSUE TITLE
Controllers keep breaking off of structure.

### ISSUE THREAD

**Issue by Furious1964** [AppliedEnergistics/Applied-Energistics-2#3346]
Building  this (https://imgur.com/a/M8JCZ) and every time a place a new controller, it breaks off.

I was just finishing up making this and it won't complete as the controllers keep breaking off. When I try putting down the controllers first, the assembly processors become individual blocks and don't link

Playing FTB Sky Factory 3 and have no crash report.

- Minecraft Version: 1.10.2
- AE2 Version: Rev 4 Stable 1
- Forge Version: 12.18.3.5211

I think I was able to fix it as I had to attack the problem from a different perspective and build the controllers first, then everything else from outside inwards. Will do some testing.

No, logging in breaks it again. Can you please port the newest version to 1.10.2!

Just tested and found out that it happened every time the structure is powered. There's definitely a problem with this version of your mod. Hopefully, you can port the latest version to 1.10.2.

Found the problem, it's the ME Security Terminal. As soon as it's put onto the network, my controllers break. Can you please look into it?

**Comment by yueh** [comment]
1.10 Forge still has a couple of data corrupting bugs, which can easily cause these bugs in various cases. Even if we could reproduce it, it is very likely to never see a fix for it. At least not without updating to 1.12 or later.
