### ISSUE TITLE
AE2/EnderIO/Calculator Item duplication via Conductor/Interface/Item Conduit.

### ISSUE THREAD

**Issue by reifnotreef** [AppliedEnergistics/Applied-Energistics-2#3347]
Playing up to date version of Age Of Engineering
* Forge Version: forge:1.10.2-12.18.3.2422
 * Calculator Version: Calculator-1.10.2-3.2.5
 * SonarCore Version: SonarCore-1.10.2-3.2.9
 * EnderIO Version: EnderIO-1.10.2-3.1.193
 * AE2 Version: appliedenergistics2-rv4-stable-1
 * Multiplayer or Singleplayer: Single player survival, hosted via Open to Lan option.
 * Crash Report Link: N/A, No Crash
 * Affected Features: 
 * Description: 
I am trying to automate creating electric diamonds in a conduster mast. I have item conduits putting in fire diamonds and pulling out the electric diamonds.

I am using an AE2 interface with a chest on top of it, with conduits from the chest to the condutor. And another conduit from the conductor to the AE2 interface.

When I call to create an electric diamond it gets made, and then sits in the conductor mast.
W/e I thought, let me check my conduit settings... they're all good. I check in my AE2 storage, and my electric diamond count is skyrocketing.

It seems like the item conduit is telling the interface it is pulling the electric diamond out, but it really isn't. So AE2 is getting more electric diamonds, when I'm not actually making any. I now have about 2000 electric diamonds, and I've only requested to make 1.

Not sure if this is an EnderIO, Calculator or AE2 bug. Will try to report to all 3.

**Comment by yueh** [comment]
At this point 1.10 can be considered EOL, so there won't be any further fixes.
