### ISSUE TITLE
ME system getting stuck crafting fresh milk

### ISSUE THREAD

**Issue by e30Birdy** [AppliedEnergistics/Applied-Energistics-2#3349]
#### Description
I made a ME Fluid Assembler and put in a recipe that one bucket of milk makes 4 fresh milk and upon crafting the recipe gets stuck trying to craft the fresh milk

- Minecraft Version: 1.12
- AE2 Version: RV5 stable 5
- Forge Version: 2604

**Comment by yueh** [comment]
Wrong mod.

**Comment by e30Birdy** [comment]
My bad didnt see it was extra cells 2, thought the fluid assembler was AE2, any way to do this with AE2?
