### ISSUE TITLE
Subnet doesnt see crafting recipes and liquid storages in main network...

### ISSUE THREAD

**Issue by excelcrafter** [AppliedEnergistics/Applied-Energistics-2#335]
Yo, I dont know if it is feature if bug, if its feature dont slap me for this message :-D

using:

cauldron-1.7.10-1.1207.01.198
forge-1.7.10-10.13.0.1207
appliedenergistics2-rv1-stable-1
- another mods

I like AE 2 so much, great improvement, I was pulling my hair when I tryed it first time...

I made 2 subnets, one on magenta one on white color, every subnet is in another direction. Got it powered and working. If I access the subnet via ME terminal, I can see materials in the network, but cant see liquids via liquid terminal on subnet and cant see crafting recipes, I done have option to "craft" stuff if I access the network. I can craft only via main network.

My idea was to make huge hangar like building with many floors, every floor will got different production, so basicall every floor will have own subnet.

It seems it will not work like that...

**Comment by dcbartlett** [comment]
If the pattern is in an interface on the subnetwork, but the CPU and terminal are on the main network, the crafting recipe doesn't show up in the terminal.

Should this be configured differently?

FTB: Direwolf20 1.7.10

**Comment by excelcrafter** [comment]
cpu + interface needs to be in same network, I think

**Comment by dcbartlett** [comment]
yeah, but cpu + interface on sub-net means the main network still can't craft the item, and i'm in a device # lock on the sub network, so can't include it in the main network.

I'm trying to find a way to do this without upgrading to a controller

**Comment by excelcrafter** [comment]
recipes in subnetwork dont work in main network
