### ISSUE TITLE
Crafting card not working

### ISSUE THREAD

**Issue by murdurer** [AppliedEnergistics/Applied-Energistics-2#3355]
#### Description

Hope I'm geting the version right:
rv3-beta-6

So what i wanted to do is to use crafting card to autocraft items as soon as they reach the system.
I pluged in interface to assembler and put in crafting card.
![2018-01-27_19h47_45](https://user-images.githubusercontent.com/5287353/35475243-3e0bfa2e-039b-11e8-8e7b-8b8c0997e50b.png)

That does not work for some reason.
I'm definetly not runing low on channels and this is the only network that I have.
![2018-01-27_19h51_53](https://user-images.githubusercontent.com/5287353/35475261-8977bd68-039b-11e8-81a5-fa7e8c9d1a5f.png)

funny hing is...it did work for a short time. Idk why it stoped.
Eithery way. Can I ask for help with this?

edit: oh forgot to mention. when  requst crafting for the item the interface does craft it.

**Comment by yueh** [comment]
That is not how crafting cards in interfaces work. For more information read [this](http://ae-mod.info/ME-Interface/).
