### ISSUE TITLE
Security Terminal/WAP

### ISSUE THREAD

**Issue by jmac460** [AppliedEnergistics/Applied-Energistics-2#3365]
Every so often when I start my singleplayer world, the Security Terminal denies access to my storage system with the wireless crafting terminal. Also, this somehow bugs out my hardlined AE2 ME terminal, which is directly connected to my system. If i restart the world a few times, or break and replace the security terminal, they are accessible again. I have power so that is not an issue. Also, when I try to access the security terminal to try and link the devices again, it does not open the GUI and instead says "Error Communicating with the Network" even though I am directly trying to access the security terminal.

#### Environment

- Minecraft Version: 1.10.2
- AE2 Version: Most recent POLite version
- Forge Version: ditto

**Comment by yueh** [comment]
1.10 Forge will occasionally leak invalid or corrupt chunkdata/TEs. Some cases seem to be fixed for 1.12, but no all are backported to 1.10 and there seem to be no plans for it. So nothing we can reailly do about it.

**Comment by Coding-Kiwi** [comment]
If anyone has this problem using Wireless Crafting Terminal: I put the Wireless Terminal in the Security Terminal again and it worked.
