### ISSUE TITLE
Quantum link chamber is turning off by itself.

### ISSUE THREAD

**Issue by Qarryy** [AppliedEnergistics/Applied-Energistics-2#3368]
Hello. I have a problem with quantum link chambers. They are just suddenly disconnecting from the ME network by itself when reloading the world or going back to that location even though the area is chunk loaded, but it does not happen allways. I had this problem in previous version as well so I thought I will wait for another version which came out, but it did not fix the problem. I tried disconecting the ME crafting terminal, no luck with that. Just breaking the quantum link chamber and putting it back fixes it. I recorded a video so you can see. That is from I logged in today and It didn't work so I hope it will help you. https://youtu.be/4SeqwnV2hWo
There is some little information for you that I can provide now. If you need something more just tell me.
I'm using AE2 rv5-stable7 (1.12.2) (Single player)
Forge: 14.23.1.2594

Thanks.

**Comment by yueh** [comment]
It's called "running out of power" before the network can fully boot, therefore getting stuck in a bootloop.
