### ISSUE TITLE
Crafting certain items using Interfaces/Molecular Assemblers crashes game

### ISSUE THREAD

**Issue by StoicBeliever** [AppliedEnergistics/Applied-Energistics-2#3369]
Playing Infinity Evolved 1.7

When asking the ME system to auto-craft certain items it causes the client (though not the server) to crash. 

#### Description

Crafting the following items has caused my client to crash:
(Wooden) Chests
Certus Quartz Tanks
(Solar Expansion) Solar Panels

#### Environment

- Minecraft Version: 1.7
- AE2 Version: appliedenergistics2-rv3-beta-6
- Forge Version: Don't know how to tell this. Just using the default Infinity Evolved version available via the legacy FTB launcher, at the recommended update level.

I don't know why but it doesn't seem to be generating crash reports for me, either that or I am not looking in the right place. I see crash reports from several weeks ago in C:\Users\*******\Desktop\Minecraft\FTB\FTBInfinity\minecraft\crash-reports but nothing from the most recent crashes.

I will go hunting for more information if you ask, I just am not sure what to look for.

Thank you!

**Comment by mindforger** [comment]
make a forced crash by pressing and holding F3+C while ingame, not in menu so we can have a look in your setup and you can check if you are looking in the right directory :)

**Comment by StoicBeliever** [comment]
Alright, here is what it produced

https://pastebin.com/0Pk0CUnw

**Comment by mindforger** [comment]
i see:
-thaumicenergistics
-extracells
-immersive integration

those are interefering with AE2 and **may or may not** be the cause of this issue

is this issue somewhat reproducible, that you can test it without those mods? (don't forget a copy of the world including configs and stuff)

**Comment by yueh** [comment]
We no longer support 1.7.10 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
