### ISSUE TITLE
Cannot remove grinder recipes

### ISSUE THREAD

**Issue by justinrusso** [AppliedEnergistics/Applied-Energistics-2#3372]
#### Description
Attempting to remove an item from the grinder using crafttweaker does not remove the item.

#### Environment
Singleplayer. Small new instance just to test this issue.
[crafttweaker.log & test.zs](https://gist.github.com/justinrusso/d88c4efaab88966d55631e34eba13a49)

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-7
- Forge Version: 14.23.2.2611

Others:
- Crafttweaker Version: 4.1.2
- JEI Version: 4.8.5.147

**Comment by yueh** [comment]
Does it really not work, or is CT just unable to detect it being removed as it is not a normal crafting recipe?

**Comment by justinrusso** [comment]
The recipes still show in JEI as well. I suppose I havent actually tested one, just going off what JEI shows

**Comment by yueh** [comment]
Oh, I missed the metadata value. Which explains a lot, as there is no recipe registered by default for certus dust, thus nothing to be removed.

**Comment by fscan** [comment]
You probably want to remove the things that grind **into** certus dust.

**Comment by mindforger** [comment]
>remove

recipes.remove(output, NBTMatch);

This will crafting table recipes for the given output.
If NBTMatch is true, it will only remove recipes that result in items with the same NTB-Data as provided

Output is an IIngredient.
NBTMatch is a boolan and optional (Will be the same as false if not specified).

taken from https://crafttweaker.readthedocs.io/en/latest/#Vanilla/Recipes/Crafting/Recipes_Crafting_Table/

you always have to specify the **output** item of the recipe you want to remove (this normally also applies to any mod related scripts), but this requires you to rescript all the recipes you want to keep (just copy them from your CT logfile using /mt recipes before you remove it)

**Comment by justinrusso** [comment]
Not sure what you mean by there is nothing to be removed. Looking in JEI with just Crafttweaker, JEI, and AE2, there are 3 grindstone recipes that result in certus dust. None are removed with the script.

**Comment by justinrusso** [comment]
Ok, I see my mistake, you are doing it by input, not output.

**Comment by fscan** [comment]
Removing by output makes no sense as the grinder may have multiple outputs with varying chances which is pretty much opposite to a crafting recipe. You cannot apply terms like "usually" when comparing apples and oranges. Also, looking at the TE support (iirc done by the MT author himself), the pulverizer works the same way.

**Comment by mindforger** [comment]
>Removing by output makes no sense as the grinder may have multiple outputs with varying chances which is pretty much opposite to a crafting recipe

sure thing, did not think about that .... but still confusing AF

**Comment by justinrusso** [comment]
As long as its documented (which it is, I just read it wrong) its fine. My goal was to be able to remove an item from the game completely (to the best of my ability). Meaning remove it from all machines possible, etc..There's no way to really do that for the grinder if removed by input. Will just have to drop support for clearing it, as there's no way to obtain the grinder recipes an output exists in then.

On 2/5/2018 8:58:28 AM, mindforger <notifications@github.com> wrote:

Removing by output makes no sense as the grinder may have multiple outputs with varying chances which is pretty much opposite to a crafting recipe

sure thing, did not think about that .... but still confusing AF

**Comment by mindforger** [comment]
>as there's no way to obtain the grinder recipes an output exists in then

i slightly doubt that! have a look at the CT API reference i posted.

I have glanced about something that was labeled "conditionals" ... you maybe able to accomplish it with a little bit effort but have not yet read into that stuff yet, i maybe totally off with my assumption there

**Comment by justinrusso** [comment]
@mindforger not sure what you're speaking of. If you're talking about the crafting table recipe link you posted earlier, this does nothing for me as all of that information is unrelated to AE2 integration

**Comment by mindforger** [comment]
https://crafttweaker.readthedocs.io/en/latest/#AdvancedFunctions/Conditional_Statements/

this looks promising (keep an eye on the lower part of the article and the menu to the left to look for other possibilitys)

**Comment by justinrusso** [comment]
... Right, but what would I be comparing to? I cannot find recipes that output a given item in the grinder.

**Comment by fscan** [comment]
There's currently not functionality to expose all recipes to CT. For the intended use case this is simply not needed. For more complicated modifications you would have to use our API directly. I'm pretty sure this is true for most (if not all) CT mod integrations.
I'm don't want to expand on the CT API at this time because depending on how the 1.13 stuff turns out it may not be needed anymore.
