### ISSUE TITLE
crafting terminal statistics

### ISSUE THREAD

**Issue by otsns** [AppliedEnergistics/Applied-Energistics-2#3375]
crafting terminal doesnt update statistics (times crafted)

i tried to craft some items using crafting teminal but my stats hasnt changed
crafting table stats working fine

no other mods installed

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-7
- Forge Version: 14.23.1.2606

**Comment by joshuasuperboy** [comment]
just update to this version its works fine for me on this version https://minecraft.curseforge.com/projects/applied-energistics-2/files/2543840
