### ISSUE TITLE
Server crash on Startup

### ISSUE THREAD

**Issue by MrDj200** [AppliedEnergistics/Applied-Energistics-2#3377]
#### Description

Expected: Normal Server Start
Actual: Crash on Server Start

#### Environment

Crashlog: https://pastebin.com/4byqArg7

Note: I do believe it has something to do with the Spatial Storage part of the mod, as when I remove my [SpatialCompat ](https://github.com/MrDj200/SpatialComapt)mod, the Server no longer crashes.
I'm pretty new to modding, and I'm not sure if it's on my part, or if the registration has changed(?).
If it's on my part I'd really appreciate a tip on how to fix it!
The part in the code where I register the TE's can be found [HERE](https://github.com/MrDj200/SpatialComapt/blob/master/src/main/java/me/dj/spatialserver/SpatialServer.java#L61)

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-8
- Forge Version: 14.23.1.2604

**Comment by yueh** [comment]
And that is why it is whitelisted based and not adding just any TE out there.

I will look into safeguarding it better. E.g. only allowing mods to register their own TEs and/or keeping a blacklist of faulty mods, so it will only crash once. As well as give modpack authors a way to blacklist a whole mod from being transfered around.

**Comment by MrDj200** [comment]
So, should I just give up on finding the error, as you will disable the functionality of the somewhere in the future anyway, or did I get that wrong?^^
