### ISSUE TITLE
AE2 with WorldEdit

### ISSUE THREAD

**Issue by jmac460** [AppliedEnergistics/Applied-Energistics-2#3378]
Using any Ae2 material, I cannot place ANY blocks with the mod after using world edit. I can see the blocks, but they do not get copied correctly, and once broken cannot be replaced. The blocks instantly break once placed. (they drop to the ground and i have to pick them up again) If possible, could this get reworked for a WorldEdit compatibility?

#### Description
1.10.2 Version (not sure exact version but its for 1.10.2)

#### Environment
- Minecraft Version: 1.10.2
- AE2 Version: whatever version is in 1.10.2
- Forge Version: same as above

**Comment by yueh** [comment]
Copying AE blocks is certainly possible as we use it frequently with for development with a pretty trivial debug tool.

Should this not work with WorldEdit, it is most likely something on their side. E.g. not copying invalid data around.
