### ISSUE TITLE
P2P Tunnels have missing recipes - 1.12.2[MC] rv6-stable-7[AE2] 14.23.1.2590[FML]

### ISSUE THREAD

**Issue by Synergyst** [AppliedEnergistics/Applied-Energistics-2#3379]
- I am having the issue inside of singleplayer and multiplayer.
- There is only a recipe for the ME P2P tunnel.

Placing a glass fibre cable in front of the spawned in P2P EU tunnel will result in a cable connecting.
However when trying to link them to each other the P2P tunnel will turn into an ME tunnel.

If I need to add any more details please let me know.

**Comment by yueh** [comment]
Please consider the issue template when creating a new issue as well as any additional resource like the [contributing guidelines](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv5-1.12/.github/CONTRIBUTING.md) or the documentation available on [ae-mod.info](http://ae-mod.info/).
