### ISSUE TITLE
New ways to charge Certus

### ISSUE THREAD

**Issue by zlyfire** [AppliedEnergistics/Applied-Energistics-2#338]
Would it be possible to charge certus quartz outside of a charger? Like in any other (supported) energy provider, such as mekanism charge pad or ic2 generator?
I know it's a little useless since one should be able to find the initial charged easily enough, but sometimes the ring isn't in one's favor.

**Comment by XFactHD** [comment]
I think that the charger we have now is sufficient. If you put it in between of two hoppers or in the later between an import bus or interface and an export bus, the charging goes well. It's sufficient to keep up with the other crafting operations where the charged certus is needed. A cool idea in my opinion would be certus and charged certus spawning in the nether with a higher output in the grindstone or similar. This feature could perhaps be also implemented by Nether Ores.
