### ISSUE TITLE
1.7.10 Endgame autocrafting is a bear

### ISSUE THREAD

**Issue by Anyone700** [AppliedEnergistics/Applied-Energistics-2#3381]
Scenario: Interface with crafting card installed has a pattern pushed into it by an enderio conduit

Expected behavior: Interface stores the pattern in it's inventory since it has a crafting card

Behavior: Interface inputs it into data storage.

To set up the equivalent amount of storage as a single 5x5x5 crafting multiblock with 9 pattern providers. I would need to set up 9 complicated towers, that cannot be made automatically with buildcraft, with the storage split up between 63 different blocks. That is a pain in the ass, especially compared to an elegant crafting cube. 

However after making them, I found out that I would have to go to each one of the sixty three different interfaces individually and add the patterns in to each of the 63 interface blocks. I would even have to mark the ones that are full because there is no outside way to tell. Even though I specifically told the interface that it was a crafter, with a crafting card.

That being said, conceptually, I love the way that interfaces/molecular assemblers work. The only problem is that there is no good endgame. You have P2P tunnels capable of storing over 500 channels in a single cable. You have a terminal that can store a practically infinite amount of stuff accessible from one place, but with no elegant endgame solution for autocrafting.

Though I do understand why you transitioned to this setup. You wanted to make people think before they just made a pattern for everything they wanted to craft. I want to though, and I have the resources to make a network that can max out 512 channels provided by 4 smart cables using P2P running into a single dense cable that goes wherever I need it to. If I did this using the current config, I would need to manually go to each of the 448 interfaces in my stacks and add the patterns.

SP
- Minecraft Version: 1.7.10
- AE2 Version: rv2-stable-10
- Forge Version: 10.13.4.1614

**Comment by yueh** [comment]
We no longer support 1.7.10 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.

**Comment by fscan** [comment]
Also, i'm not sure what you want to achieve? You know you don't need to fit the interfaces with a crafting card for normal autocraftig? And whats wrong with the interface terminal? If you want to group the interfaces in there, rename them (anvil, inscriber).

http://ae-mod.info/

**Comment by Anyone700** [comment]
I want to be able to add patterns to interfaces without having to manually going to them. From what I read the crafting card is what allows them to craft

**Comment by fscan** [comment]
Ok, I'll repeat myself one more time: No crafting card needed. Use a interface terminal. Read the documentation (also there are some good videos out there).
