### ISSUE TITLE
Server Crashing on loadup

### ISSUE THREAD

**Issue by RoboJackPlays** [AppliedEnergistics/Applied-Energistics-2#3385]
Server is crashing the moment it loads up

https://pastebin.com/GRgzUkN1

- Minecraft Version:  1.12.2
- AE2 Version:  Latest
- Forge Version:  Latest

**Comment by fscan** [comment]
First off, Latest is not a version, specially for forge which releases almost daily. FYI your version is about a month old.
You've seem to have hit a chunk corruption issue. Sadly there's nothing we can do about it.

**Comment by yueh** [comment]
Also it is using sponge, which we do not support and could potentially be a cause for it.
However as this looks like some sort of corruption, it might already be too late to test it without.
