### ISSUE TITLE
[1.12.2] Disable passing of AE power via Quantum Gateway [Suggestion]

### ISSUE THREAD

**Issue by themechman** [AppliedEnergistics/Applied-Energistics-2#3386]
Due to the fact that AE supplies power to the quantum gateway from one side to the other, I am having problems with unique situations.

In the past I have run into world killing problems with chunk loading two sides of a quantum gateway and then the restart of the server. This would cause power from the wrong dimension to "back feed" to the overworld.

I was able to reduce this problem by placing a 4x4x4 pile of dense energy cells on each side of the quantum gateway but this does not always work.

Since I have applied a bug report on this situation before and it went unfixed, I am simply requesting a configurable option to turn off the flow power packets between quantum gateways. This way I must power feed BOTH sides from localized power supplies.

But you're thinking, dude... thats cray-cray... why would you do that?
- Autocrafting across different dimensions (This one really breaks things!)
- 400+ channels in use (Yes... I've done this in survival and crashed a server)

**Comment by yueh** [comment]
That is simply not possible due to how grids work. At least not without also preventing anything else from working across a QNB. Further changing it is simply not worth it and would make an already complex system even more prone to errors.
