### ISSUE TITLE
Security Terminal Breaking Blocks

### ISSUE THREAD

**Issue by MindGamesMcClane** [AppliedEnergistics/Applied-Energistics-2#3387]
#### Description

I'm playing on FTB Revelation Singleplayer and I've been having the problem of whenever I teleport away from my base then come back some of my advanced inscribers/ crystal growth chamber are broken. If there's a way to just not use the security terminal but still wireless I can't find it. Not sure if this is a known bug, my incorrect setup, or a AE2 Stuff problem. Either way if someone could help me with a solution that would be very much appreciated.
#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv5-stable-5
- Forge Version: forge-14.23.1.2601

**Comment by yueh** [comment]
That is an AE2stuff issue as it only affects their blocks and they already have at least one open issue about it.
