### ISSUE TITLE
JEI feature for auto-completing crafting recipes with craftable items

### ISSUE THREAD

**Issue by SHIuSH** [AppliedEnergistics/Applied-Energistics-2#3388]
I'd like to request a feature(Which I couldn't find being requested elsewhere, sorry if dupe) that makes makes an auto-craft order for items that are missing in a shift-clicked recipes from JEI. 
Example: 
   I want to make a diamond pickaxe and in my AE system I have: planks, diamonds, recipe to make sticks out of planks. I shift-click the [+] on pickaxe recipe and the sticks get requested(and even put in a crafting grid)

**Comment by yueh** [comment]
It would pretty much defeat the purpose of autocrafting. The goal is to avoid/prevent using anything like JEI outside the creation of new patterns. So if you want a diamond pick, there should be a pattern to request the finished item or even keep some stocked.
