### ISSUE TITLE
P2P inception problem

### ISSUE THREAD

**Issue by KalaMiDeviL** [AppliedEnergistics/Applied-Energistics-2#3396]
#### Description

Okay, so these 7x7x7 controllers made me rethink my channel hatred. It's a lot more challenging and less OP and EZ, but you can still go mental - it's actually perfect for long term fun.

I was trying to squeeze as many channels as I could out of a maxed controller in my testing world, when I came up with the idea of tunneling tunnels to gobble up some extra controller sides inside the thing. After a bunch of testing I ended up with this little setup:
![2018-02-20_00 47 21](https://user-images.githubusercontent.com/23558065/36401505-16162536-15d8-11e8-903b-aa16ac986ba2.png)
Now, in my head this system should 100% work. I powered literally everything separately, don't even have more than just 2 channels used anywhere and the controller is visibly happy.
What happens? Well the inner tunnel works as intended, the left end of the outer tunnel says "device offline" and "unlinked", the right one says "device missing channel" and "linked (output side)".

When I provide channels to the left end,
![2018-02-20_00 52 18](https://user-images.githubusercontent.com/23558065/36401779-0eaad984-15da-11e8-8105-95db1f1e948d.png)
it changes to "device misssing channel" (?) but insists on being "unlinked", even though the right one always says "linked (output side)" (??).

When I provide channels to the right end,
![2018-02-20_00 52 40](https://user-images.githubusercontent.com/23558065/36401875-c57a200c-15da-11e8-86b4-169632a5b7db.png)
it changes to "device online" and "linked (output side)", while the left one remains at "device offline" (or "device missing channel" if it had had a controller before) and "unlinked" (???).

Thinking it might be something weird, I also tried this,
![2018-02-20_00 52 50](https://user-images.githubusercontent.com/23558065/36402237-49604796-15dd-11e8-9467-afe09ff8a420.png)
but no cigar

The chest is registered in the right-most cable and the working tunnel ends on the inner-most. The buggy ends are not registered. They do show up where they should with the network tool, but you don't see any lines on the smart cables and WAILA disagrees with the network tool.

Switching input and output did nothing either, I also built the following and alternated the roles of the tunnel ends to verify that the ME tunnels are duplex (even though the tunnel ends tell you whether they are the input side or output side):
![2018-02-20_00 58 47](https://user-images.githubusercontent.com/23558065/36402009-b5bee624-15db-11e8-808c-b977fcde5de6.png)

What on earth is going on?

I did build ME chest structures in all the scenarios and it always allows 8 and dies with 9 (and no there were no adjacent chests, everything was purely cable-connected).

#### Environment

1. run:

Singleplayer (Creative) with a lot of mods (special thanks to WAILA)

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable 8
- Forge Version: 14.23.2.2612

2. run:

Singleplayer (Creative) - clean install -

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable 8
- Forge Version: 14.23.2.2618

apologies for my non-native English

**Comment by mindforger** [comment]
>tunneling tunnels 

this is just not possible ME p2p can not carry other ME p2p
to make it sound logically, the bandwidth of a p2p does not allow another p2p to be fed through it 

>it always allows 8 and dies with 9

all blocks are treated like fluix cable not dense, they can only carry 8 channels

**Comment by Tahakk** [comment]
If you want to know how to max you channels I reckon you watch [this](https://www.youtube.com/watch?v=bMU1scXth6M) video. After watching this it still gave me few hours of tweaking my existing chaos net of my AE2 cabling, but at the end it worked out awesome :)

**Comment by KalaMiDeviL** [comment]
Wow, a community that actually tries to help you, how about that?

But I actually set it up correctly during testing. I did use dense cable and as I said there were no adjacent chests (well, not more than 8 any way). The screenshots were just to show where I hooked up the additional controllers. The testing setup looked something like this:
![2018-02-20_10 16 02](https://user-images.githubusercontent.com/23558065/36415697-16e65a7c-1627-11e8-8157-13ba0971cf2e.png)
My idea with the chests was to check if it was just a UI bug and the 32 channels actually did carry all the way through, because one of the outer tunnel ends always said "linked".

I also know how to get 22985 channels off a 7x7x7, which should be the maximum or close to it, it was just the P2P2P2P idea that gave me a headache.

I guess it's good that you take bandwidth into account, I was imagining horribly multiplexed systems already. It would save major cable budget - and just get OP again.

**Comment by mindforger** [comment]
like already said, for this particular screenshot, the main issue is that the p2p stacking is not possible
thus building an independend network which only carrys 8 channels total

you can check if any connection is fed from a controller by using a smart or dense cable branching from the main cable, if the branched cable shows 8 channels in use, the network is just a "adhoc" network with 8 channels, if the branched cable stays dark the channels are linked to an controller

but 1 out of 9 me chests showing "connected" sounds odd can you replicate that mith an minimal setup or upload the world somewhere ?

**Comment by KalaMiDeviL** [comment]
Yes, I know, I'm just trying to prove that I wasn't stupid when I tested it, back before you told me there's no bug and that the tunnels have a bandwidth. Whatever, just ignore it xD
No, it's not the chest that says linked it's one of the two outer, intentionally non-working tunnel ends. Gotta read it properly ;) Or whatever, just ignore it too, it doesn't matter any way.

By the way, watching the linked video, I realised a miscalculation on my part. My maximum is 22854. Do you know the actual limit?

**Comment by mindforger** [comment]
i would have to throw some math at it to be sure, so "no" for now

but if you have a dedicated network for hosting all the p2p connections you can expand the system, you could also try some simple management tricks, like making your production a subnet
