### ISSUE TITLE
Inverted View Cell blocks autocrafting?

### ISSUE THREAD

**Issue by BrisingrAerowing** [AppliedEnergistics/Applied-Energistics-2#3397]
#### Description
From [this thread on /r/feedthebeast](https://www.reddit.com/r/feedthebeast/comments/7yo8qi/1122_ae2_view_cell_problems/), it appears that an inverted view cell preventing nuggets from showing also prevents nuggets from being used in autocrafting. Is this behavior intended? I haven't personally tested this (I don't use the view cells), and I don't know what version the Reddit poster is using (I'm going to ask).

#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: RV5-Stable-8
- Forge Version: 2616

**Comment by mcdodge34** [comment]
I'M the one having the issue, I wasn't sure if it was intended or not. Details about version are accurate


    Minecraft Version: 1.12.2
    AE2 Version: RV5-Stable-8
    Forge Version: 2616

**Comment by mindforger** [comment]
please don't forget the important things!

> I also have ae2stuff-0.7.0.4-mc1.12.2.jar in there I didn't think it was an issue, but it make sense that a view cell shouldn't affect available crafting materials for the crafting grid or later on autocrafting system. Can you link me to your github issue once its done, I love to subscribe to the issues I've got so I can track when they are taken care off.

does this still happen without any addon mods like ae2stuff, extracells etc. ?

**Comment by yueh** [comment]
This is about the user not being able to use the recipe transfer in JEI and not about autocrafting or even the normal crafting grid.

Which is completely intentional as view cells are a filter to restrict the terminal to a subset of items for all network related tasks. E.g. to protect certain items from being accidentally being consumed by JEI or refilling an oredict item.

**Comment by mcdodge34** [comment]
Ok then, any chance for a proper system that would just block items from view and not from crafting ???
