### ISSUE TITLE
Adding AE support to my own mod

### ISSUE THREAD

**Issue by ServantGirl** [AppliedEnergistics/Applied-Energistics-2#3398]
- Minecraft Version: 1.12.2
- AE2 Version:  rv5-stable-5
- Forge Version: 14.23.1.2555

Hello. I was doing some compatibility testing for an item processing block in my own mod. More specifically I was testing to make sure the various forms of automation worked properly.

I've assigned each slot to a face of the block. It pretty much uses the same slot/face mappings as a furnace, and while vanilla hoppers and other mod's pipes connect correctly, it doesn't seem to respond to the ME import and export bus's.

So I was wondering is there something I need to do on my end? Like do I need to actively put in ME support or is there some simple silly thing I'm missing, or is it on AE's end? Thanks~

**Comment by fscan** [comment]
AE2 dropped support for IInventory, you need to support IItemHandler. Forge adds those to all the vanilla blocks.

**Comment by ServantGirl** [comment]
I'll look into this. Is it like hugely complicated or no? Any blocks you can suggest I look at to work out how its done?

**Comment by yueh** [comment]
This is probably more suited for the forge forum/irc or similar places as it is basic minecraft modding and nothing AE2 specific.

**Comment by ServantGirl** [comment]
Thanks! I got the compatibility working now~ I would have never found it if not for you guys help.
