### ISSUE TITLE
Unable to Smelt Nether Quartz Dust

### ISSUE THREAD

**Issue by mgwerner** [AppliedEnergistics/Applied-Energistics-2#3400]
#### Description
appliedenergistics2-rv5-stable-8
No option in JEI to smelt dust, furnaces will not accept dust

#### Environment
SP, 111 mods installed, all updated to latest 1.12.2

- Minecraft Version: 
- AE2 Version: appliedenergistics2-rv5-stable-8
- Forge Version: 14.23.2.2611

**Comment by mindforger** [comment]
quartz dust was never intended to be smelted, what do you expect?

an have a look at the website on how to use the dust properly :)

**Comment by mgwerner** [comment]
Thanks for the response.  I understand the uses, and had been able to use nether Quartz to Silicon before:
https://ftb.gamepedia.com/Nether_Quartz_Dust_(Applied_Energistics_2)

Nether Quartz Dust (Applied Energistics 2)
This page is about the Nether Quartz Dust from Applied Energistics 2. For other uses, see Nether Quartz Dust.
Nether Quartz Dust is an item that is added by Applied Energistics 2. Nether Quartz Dust is created by grinding Nether Quartz in either a Quartz Grindstone or a Macerator. The most significant use for Nether Quartz Dust is Silicon, which is used in the majority of AE2's crafting recipes.

**Comment by yueh** [comment]
Actually it is. But if it is missing, it is either explicitly deactived by the user or some other mod did disable it for various reason.

**Comment by mgwerner** [comment]
Also, in the Vanilia recipe section of the config:

# Silicon
smelt= ae2:material.nether_quartz_dust -> ae2:material.silicon
smelt= ae2:material.certus_quartz_dust -> ae2:material.silicon

**Comment by mindforger** [comment]
quartz to silicone? since when was this a thing? i am completely oblivious to that fact!

big sorry @mgwerner 

i'll reopen this until you found out where it has gone (which mod deactivated it)

**Comment by yueh** [comment]
Closing it is actually ok. As it is a modpack specific issue. As already said due to a mod adding their own silicon, removing the recipe, or disabling the item completely.
