### ISSUE TITLE
Configs to lower meteorite spawn chance and set meteorite dim whitelist don't work

### ISSUE THREAD

**Issue by TomTheHero** [AppliedEnergistics/Applied-Energistics-2#3407]
The title explains itself, i have removed the whitelist and set the chance to 0.0 and the spawnrate of the meteorites hasen't changed at all.

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv5-stable-8.jar
- Forge Version: 1.12.2 - 14.23.2.2611

**Comment by yueh** [comment]
There is no option to reduce the spawn chance at all and removing the whitelist will cause it to be initialised with the default values.

**Comment by TomTheHero** [comment]
Then what is this line about : worldgen {
    D:meteoriteClusterChance=

**Comment by Ommina** [comment]
What is your actual goal here?

If you're setting the (what you believe to be) meteor spawn chance to 0.0 and/or setting an empty whitelist, presumably you don't want meteors at all.  In that case, set MeteoriteWorldGen=false and be done with it.

**Comment by TomTheHero** [comment]
Derp, i never noticed that xD
