### ISSUE TITLE
Quantum Links seem to break and all become unpowered after some time.

### ISSUE THREAD

**Issue by GoOhm** [AppliedEnergistics/Applied-Energistics-2#3408]
I have a small ME network set up which is being powered by Environmental Tech solar arrays. I currently have 5 tier 1 solar arrays providing power to 4 quantum link chambers and the ME system (Plenty since each array produces 549RF/t). One pair of chambers are meant to move power from the end to the overworld and the other set are to allow access to the ME system at my friends base. I did use Thermal expansion fluxducts in the end to move power from the array to the quantom link but changed it to an energy acceptor per solar and then ME cable to transfer the power. Every now and then it just seems to lose power in the end even though its chunk loaded and this causes the entire system to lose power. This is a MP server and I am using the latest r5 release 8 version of AE2. It works temporarily if I break the P2P tunnel - FE in the end and a couple other cables then replace and relink them and power the output side temporarily with a TE energy cell. Then I can remove the cell and it will work until I log off and on again, Im using a FTB mod to load the chunks.
- Minecraft Version: 1.12.2
- AE2 Version: R5Release8
- Forge Version: 14.23.2.2623

**Comment by mindforger** [comment]
> (Plenty since each array produces 549RF/t)

providing infinite power is much irrelevant
you have to have enough internal capacity to not run out of power EACH server tick
plug in some energy cells to increase the internmal storage

try your setup with creative cells for testing and see if the issue persists


also don't forget you neec to chunkload the QLC and all parts of the network to prevent reloading your network over and over when far away or other dimension

**Comment by GoOhm** [comment]
OK that makes sense. I guess then having a powercell for each chamber at least with the capacity to power them for at least one tick would be sufficient. I can use TE cells which I can upgrade to reinforced just to be safe and put one at least in every part of the system. Thanks for the quick response I'll try this out and let you know how it goes.

**Comment by mindforger** [comment]
>I can use TE cells

no you cant! the issue resided with the capacity INSIDE of the AE system (and subsystems) and you can increase this capacity only by adding a energycell from AE2 to the network anywhere you want

**Comment by GoOhm** [comment]
Well it seems that when I use TE cells I havent had the problem happen as of yet and the AE2 system seems to be using 0 power? I was trying to use P2P tunnels to transfer the power from the end to the overworld. I added the cell from TE in series to the output of the solar array and connected it via an energy acceptor and a dense ME cable. This seemed to power the QLC so I went back to the overworld and powered my base side of the QLC and it turned on but wasnt draining anything from the cell. I thought this was weird but I didnt have to hook up the other end of the P2P tunnel to power the ME and theres no external power source connected at all. Not sure but that may be a different bug.

**Comment by mindforger** [comment]
The TE Cell is providong much more output than the solars, and i guess the solars have VERY limited internal capacity

so you have two issues, a "kind of" limited supply which was actually causing the issue and low internal AE power storage that then triggered the power outage

trust me, you might have solved one issue, but the other will bite you at some point, throw at least one normal energy cell in EVERY network and if you encounter issues, first try increasing the storage capacity or a creative energycell and see if the problem gets solved ... else report back :D

**Comment by GoOhm** [comment]
Ok man no worries. Just seemed a bit funny that I didnt need to use the P2P tunnel to move the power to the overworld lol thanks though XD
