### ISSUE TITLE
Auto crafting wont craft pure seeds as a component.

### ISSUE THREAD

**Issue by Crowley723** [AppliedEnergistics/Applied-Energistics-2#3414]
I am trying to craft processors en masse, anything that requires the system to craft a pure certus seed says the seed is missing even though I have made sure the system can craft them. I can craft as many as I want but it says they are missing even if I have them already crafted in the system. Is this something simple I am missing? I want to be able to request more than one calculation processor at a time. I am, however able to craft them separately from anything else, ie requesting just the seeds.

FTB Revelation V1.6.0
I am running my world on a dedicated server machine,
Server Java Version: "1.8.0_161" JRE: "build 1.8.0_161-b12"
Client Java Version: "1.8.0_151" JRE: "build 1.8.0_151-b12"

- AE2 Version: appliedenergistics2-rv5-stable-8
- Forge Version: 1.12.2 forge-14.23.2.2618
![2018-03-05_17 26 11](https://user-images.githubusercontent.com/26265198/37009341-5d603d96-209b-11e8-9c63-d7998cbaa73a.png)
![2018-03-05_17 26 11](https://user-images.githubusercontent.com/26265198/37009350-6aaaf568-209b-11e8-818d-a23a4319b9e5.png)
![2018-03-05_17 26 38](https://user-images.githubusercontent.com/26265198/37009357-73c4e71c-209b-11e8-806e-e12747de74ae.png)

**Comment by Tahakk** [comment]
I cannot say what's wrong although it's working for me in DW20 pack, as I can see that you have right _Pattern_ encoded, but afterwards there is no sand in _Crafting Plan_. Are you able to craft it in hand/on table?

**Comment by mindforger** [comment]
double check the pattern to be a crafting pattern
double check you can craft the seed as a request and the pattern is actually working
and finally, do a check if the recipe for the pure crystal is working with hand crafted seeds

**Comment by Crowley723** [comment]
Hmmm. Thanks for the double checks, while rewriting the pure crystal recipe it started working. I don't know exactly what changed but its working now. Thanks, everyone!
