### ISSUE TITLE
CraftTweaker Issues (Recipe) with AE2

### ISSUE THREAD

**Issue by fmohican** [AppliedEnergistics/Applied-Energistics-2#3416]
#### Description

The reciped added with crafttweaker isn't showed on AE2 and also the Patter says "Invalid" but when hover they display craft recipes, check the below video (it's a video, download archive)

[the_bug_video.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1788708/the_bug_video.zip)

#### Environment
Dedicate MP Server 
- yes i have full root access if it's need
- yes forge and plugins are same version as server
- yes server have ct scripts installed

The script files with recipe are there : https://gist.github.com/fmohican/4382d7e835a4b3e149185f13523c5a42

There isn't a crashlog

- Mod Tweaker Version: 4.0.7
- CraftTweaker Version: 1.12-4.1.5
- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-9
- Forge Version: 14.23.2.2624

### Mirror to CT Issues
https://github.com/CraftTweaker/CraftTweaker/issues/485

**Comment by mindforger** [comment]
do you have the same CT scripts on the client?!
i believe there are some recipes that need to be loaded on gamestart and can not be synced properly to the client, so this may be a recipe desync!?

**Comment by fmohican** [comment]
ofc the script are installed both on client and server also before open
issue I check the script for errors (via in game command) to ensure isn't
my fault

**Comment by jaredlll08** [comment]
we've already fixed this on our side, just not released.

**Comment by mindforger** [comment]
Thx for info, will close then, can be reopened anytime if the issue occurs again or similar

**Comment by fmohican** [comment]
Thanks.
