### ISSUE TITLE
Suggestion for an alternative to the crafting of Fluix Crystals

### ISSUE THREAD

**Issue by MikkelRH** [AppliedEnergistics/Applied-Energistics-2#3419]
**Summary**
I hope this is the right place to put it but whatever. I've been playing on a FTB Revelation server and i have been experiencing the issue og fluix crystals dissapearing after dropping.

**Description**
I play on a FTB Revelation server where there a moderate amount of players, a lot of the times where i try to make fluix crystals, the items thrown dissapear and nothing comes out of it (And no its not clear lag). Im not sure why, but im guessing it could be the fact that its a server with pretty heavy modpack, and with other players also doing some demanding stuff, things like dropping items can bug out.
A fix could be an additional way to make the crystals, im suggesting a machine or another crafting method to make the fluix crystals, i think it would help a lot of people out who also experiences this. Im not saying that the dissapearing of the crystals is something you should fix, since its probably just the server having a hard time, im just saying that you could add something to work around this.

**Environment**
Im dropping them in a normal water pool, with some chisel factory blocks under and around the pool. The server is also made as a Skyblock server to reduce lag.

Im using FTB revelation 1.5.0 and have added optifine to it.

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-8
- Forge Version: Forge- 14.23.2.2613

I hope you will consider my idea :)

**Comment by yueh** [comment]
Simply no. If the server decides to purge item entities for whatever reason, it's their job to provide an alternative way.

**Comment by MikkelRH** [comment]
I found out that the mod AE2 Stuff has a thing called the crystal growth
chamber that i can just put the items into.
But thanks :)


2018-03-08 3:45 GMT+01:00 BookerTheGeek <notifications@github.com>:
