### ISSUE TITLE
No working wooden gear recipe

### ISSUE THREAD

**Issue by jarnalyrkar** [AppliedEnergistics/Applied-Energistics-2#3422]
#### Description

![image](https://user-images.githubusercontent.com/20617365/37174014-9678bdde-2315-11e8-8ec1-286d02354cad.png)

#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv5-stable-8
- Forge Version: 14.23.2.2611

Multiplayer, dedicated server, an extensive list of mods:
![image](https://user-images.githubusercontent.com/20617365/37174122-ef6c5f9a-2315-11e8-9d4b-75502236cbaa.png)

**Comment by jarnalyrkar** [comment]
My bad, i forgot to remove "is open" when searching through old issues, I found my solution. :)

**Comment by jarnalyrkar** [comment]
Unfortunately the suggestion did not work, I've edit the config file on the server, but I still get the "this item is disabled" item

**Comment by Ommina** [comment]
Ensure the config file is changed on both the server AND the client.

**Comment by jarnalyrkar** [comment]
Ah, I thought the server config had precedence. It works now, thank you very much! :)

**Comment by Codingale** [comment]
can you link the config for future use? this shows up first.

**Comment by jarnalyrkar** [comment]
Just go to your config-folder (on both your server and the clients), find the config for ae2, and then find the line that disables that wooden gear recipe, and enable it. I can't remember the exact filename right now.
