### ISSUE TITLE
AE2 - Project E Ph.Stone

### ISSUE THREAD

**Issue by fmohican** [AppliedEnergistics/Applied-Energistics-2#3423]
#### Description

AE2 "store" item that doesn't use.
I made an pattern for diamond with 1 emerald can craft 2 diamond (using Ph.Stone from ProjectE). So as example via one recipe (i mean only one patter) to make 50000 diamond from 25000 emerald, ME store ALL Ph.Stone and use only 4 (cuz 1 interface have 4 molecular assembler), and shorty when i want to make other craft recipe i have to wait till 1st craft end, due no Ph.Stone

![2018-03-09_14 07 16](https://user-images.githubusercontent.com/8583317/37210486-90160ba8-23b1-11e8-9efd-2929835b0b73.png)

#### Environment

- its Dedicate Server, yes i have full root access
- its same version on both, client

 and server
- yes it's happens with other recipe that use Ph.Stone

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-9
- Forge Version: 14.23.2.2624

**Comment by yueh** [comment]
Depending on how they did implement it, we might simply not be able to correctly detect any loop. 

Storing all required items for a job in a cpu is simply by design.

**Comment by fmohican** [comment]
yeah, but basically the system just uselessly store items and as in this case with PH Stone, the system keeps busy 11 PH Stone that could be used for another crafts

**Comment by fmohican** [comment]
@yueh ... isnt anything to fix?

**Comment by mindforger** [comment]
there is nothing to fix, the design descision was, store all items used for crafting in a crafting CPU to make it impossible to get stuck during crafting due to loops in the recipes

**Comment by fmohican** [comment]
That it's the problem the CPU store item uselessly, as you can see from screen capture I gave, the system store all ph. stone and use only 4.
OK. I will make a video about it, to see exactly what i'm talking about.

**Comment by mindforger** [comment]
i just tested this with pams harvestcraft and know what you mean .... @yueh can you explain in short why the crafting CPU pulls more than one of the reusable items?

i tested it with a kitchen knive, it does not get damaged during crafting and acts like a catalysator and does not get consumed, is there a particular reason why the crafting pulls ALL available kitchen knives from the storage where it only requires one? i mean it's not a real bug imho but kindof annoying when you can only craft one thing using this catalysator even when you have 10 in your system

**Comment by fmohican** [comment]
[TheBug_VIDEO_MP4.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1799647/TheBug_VIDEO_MP4.zip)
