### ISSUE TITLE
Abillity to change content of sky stone chest in generated Meteorits

### ISSUE THREAD

**Issue by Krosta8** [AppliedEnergistics/Applied-Energistics-2#3424]
#### Description

Hello,
I just wanted to ask, if there is a way, to set, what should be generated in sky stone chest in generated Meteorits.
I would like to add some new presses, which I made like add-on.
Is there this option or is it possible to add this option?
#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable 10
- Forge Version: 14.23.2.2611

**Comment by yueh** [comment]
Currently no and I would not say it is planned at all.

If i ever get around to rewrite the generation to use normal loot tables, it should not be that hard to append them with another mod. But that is under the assumption, that we can keep the current generation with non random presses (as long as the player knows what they are doing).

Or even better, if someone would contribute the changes for them.

**Comment by Krosta8** [comment]
Okay, I understand it.

Thank you :)
