### ISSUE TITLE
Custom Recipe not outputting correct amount of dust

### ISSUE THREAD

**Issue by GoDzViper** [AppliedEnergistics/Applied-Energistics-2#3425]
#### Description
I want to create a custom recipe so I can grind up Redstone ore into 6 Redstone dust, however, the grindstone will only output 1 Redstone dust. I have copied the 'grind.recipe' to the ae2 config folder as that is the only place the custom recipes seem to even work and added, "grind= mc:redstone_ore -> 6 mc:redstone" but as already stated only outputs 1 Redstone dust.

#### Environment
I'm using the project ozone lite modpack in a single player world

- Minecraft Version: 1.10.2
- AE2 Version: rv4-stable-1
- Forge Version: 12.18.3.2511

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.12 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
