### ISSUE TITLE
[1.12.2] Server Crash: Ticking Grid Node

### ISSUE THREAD

**Issue by Morpheus1101** [AppliedEnergistics/Applied-Energistics-2#3426]
At the time of this crash i was afk, so unsure of anything occurring prior to the crash.
Crash log @ https://gist.github.com/Morpheus1101/3c7168c977b9b228d8a7c682a854c1b5

Forge v*.2.2625
AE rv5-stable-10

**Comment by yueh** [comment]
In this case, it appears to be a Storage Drawer issue. (based on the provided world/pack)

What happens is that the interface tries to store 1x nether star into the network, which end up hitting a storage drawer and then being returned 130k nether stars as left over. At which point everything breaks down.

So nothing we can really fix, but I will look into crashing way earlier. Essentially crashing immediately when hitting a broken `IItemHandler` (more remaining than ever inserted or more extracted than requested etc). At least to avoid bubbling up and obscuring it. Reporting the actual tile entity is probably impossible, but at least mentioning the FQDN for the class should help.
