### ISSUE TITLE
The problem with the spatial I / O port

### ISSUE THREAD

**Issue by demycat** [AppliedEnergistics/Applied-Energistics-2#3427]
- Minecraft Version: 1,7,10
- AE2 Version: rv3-beta-6
- Forge Version: 1.2.0.347

My construction took on a spatial map 27 * 12 * 21(length * height * width), but I can not withdraw it (I built the pylons indentically)
I do not observe this problem with small buildings (for example, 5 * 4 * 5)
All in screenshots:
![2018-03-13_23 20 526](https://user-images.githubusercontent.com/34833284/37371619-a54f89ee-2718-11e8-93d5-4e5e23441ba8.png)
![2018-03-13_23 21 07](https://user-images.githubusercontent.com/34833284/37371620-a57f6696-2718-11e8-9755-8bfb859f1f7f.png)

**Comment by mindforger** [comment]
Did you check the orientation? With non-symmetrical chamber you have to have the same orientation in world when the cell was defined the first time

**Comment by demycat** [comment]
@mindforger What do you have in mind?

**Comment by mindforger** [comment]
from what i understand, you made a 27 * 12 * 21 cell and you are not able to spawn it anywhere else?

i was guessing, you did not check the orientation (rotation in regards to facing direction, like north, east, south and west) 
the target pylons have to have the exact same size in all 3 dimension X Y Z and when i say X Y Z i mean X Y Z and not width, height and length

hope i could make clear what i mean :)

**Comment by demycat** [comment]
@mindforger pylons are constructed exactly as when saving to the map (I took screenshots before moving pylons)

**Comment by demycat** [comment]
@mindforger I've built pylons (I even did screenshots), but they do not work
The first and second screenshot is this before saving the build on the map
![2018-03-13_19 53 42](https://user-images.githubusercontent.com/34833284/37450023-1ac7d470-2835-11e8-8d8f-41758836a54e.png)
![2018-03-13_19 53 51](https://user-images.githubusercontent.com/34833284/37450024-1af40f72-2835-11e8-8861-221b0ea0d647.png)
![2018-03-13_19 54 35](https://user-images.githubusercontent.com/34833284/37450027-1ddbb26c-2835-11e8-8790-806a5d2e74be.png)

**Comment by mindforger** [comment]
okay from the coordinates of your minimap is looks like X,Y and Z are correctly oriented, but i don't see any channels lit on your dense cable, do you even have a valid working network?

**Comment by demycat** [comment]
@mindforger I understood the essence of the problems, thanks for the help!
