### ISSUE TITLE
Thermal Foundation satchel crashes the game when in storage

### ISSUE THREAD

**Issue by violetoctagon** [AppliedEnergistics/Applied-Energistics-2#3429]
#### Description

i accidentally put my resonant satchel from the thermal foundation mod into the ME system via a crafting terminal, and the game (and server) crash when i try to take it out.

#### Environment

FTB Revelation 1.6.0

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-8
- Forge Version: 8.0.99.99

**Comment by yueh** [comment]
Please consider the issue template when creating a new issue as well as any additional resource like the [contributing guidelines](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv5-1.12/.github/CONTRIBUTING.md) or the documentation available on [ae-mod.info](http://ae-mod.info/).
