### ISSUE TITLE
Vibration Chamb er - Energy use

### ISSUE THREAD

**Issue by Peroaner** [AppliedEnergistics/Applied-Energistics-2#3431]
The Problem is, that between 2 connects to my Server all Coal and Energy is lost. 

So my question is, if there is a kind of a Chunkloader in the AE2-Mod, because my system burns all my coal during two connects in my World. 
I use 24 vibration chambers, my system uses 187 AE/t and can safe 6,43 MAE in dence energy cells. 
I have 10k charcoal in my system, if i disconnect now and rejoin in 24 hours the server, all coal and energy is away. 

My hoster told me, that the world wounld not be loaded by the hoster, only if there is a chunk loader in the mod.

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-10
- Forge Version: 14.23.0.2517

Further i use the following Mods (in these mods are no chunk loader): 
ComputerCraft 1.80 
Tinkers' Construct 1.12.-2.7.3.30

**Comment by yueh** [comment]
No, AE2 does not provide any chunk loading feature.
