### ISSUE TITLE
ME P2P Tunnels Not Providing Channels Upon Server Restart

### ISSUE THREAD

**Issue by khift363** [AppliedEnergistics/Applied-Energistics-2#3432]
I have recently gotten into using AE2 and have discovered a very unfortunate side effect to playing on a server that shuts down for 8 hours every night to save on server costs, and that side effect is that every time the server comes back up my storage solution breaks and I have to manually refix it.

#### Description
Before server restart, I have two arrays of Storage Controllers feeding into item barrels with channels provided by a pair of ME P2P tunnels. These two arrays use 27 and 29 channels individually.

After server restart, the P2P tunnels only deliver 8 channels each to the arrays. 8 storage buses on each side will be online, and the rest will be offline. To fix the problem, I have to remove and reinsert cables until the system suddenly works again. I have not been able to predict which cable will cause that, so I've taken to just removing all of the cables and reapplying them all.

I have not used any other P2P tunnels yet, so I don't know how extensive this bug is at the moment. I have, however, given this situation half an hour's wait time to see if it would 'fix itself', but it never did.

#### Environment
The server is running FTB Revelations v1.5. According to the in-game "Mod Options" menu, my version numbers are as follows:

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-8
- Forge Version: 14.23.2.2613

**Comment by yueh** [comment]
This is most likely the server not reloading chunks on restart. E.g. only load chunks, if a player is online to further save costs.

**Comment by khift363** [comment]
Reloading chunks does not solve the problem, whether done manually or as part of the automatic server update. We actually already had server reloading chunks on restart already enabled.

However, after testing today it's not a problem with P2P terminals, it's a problem with storage buses, and it's createable even without a restart involved. Something about storage buses makes the system never reallocate channels to fit buses onto them. If I don't recreate this storage bus array in a very specific manner, certain cables will fill with channels before they should, and once that happens the system never reallocates channels away from those cables to fit new storage buses discovered on the network, even if there's a valid way to do so. Restarting will trigger the problem as well, since the whole chunk is now created from thin air effectively, and it fills the cables up immediately and there's no memory of how I assembled the array in the first place.

I can recreate the report with some video of this happening, if you'd like. At least personally the workaround is to use dense cable on all of the storage bus arrays, because then no matter how retarded it draws the lines there'll be enough channels, but it's absolutely an AE2 bug that it won't reallocate channels to these devices.
