### ISSUE TITLE
1.7.10 ae2 rv3 when setting up 2 fully powered, fully chunk loaded quantum network bridges with disabled channels on the server, establishing a connection between the bridges prevents the input and extraction of items from the network or crafting interfaces at any terminal except the wireless ones. This is not a power or channel issue as channels aren’t enabled and power is no issue due to the use of creative energy cells. 

### ISSUE THREAD

**Issue by dan-at-the-van** [AppliedEnergistics/Applied-Energistics-2#3436]
#### Environment

- Minecraft Version: 
- AE2 Version: 
- Forge Version:

**Comment by dan-at-the-van** [comment]
Apologies for the bad formatting in the title, never posted on here before.

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.12 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
