### ISSUE TITLE
Weird crash

### ISSUE THREAD

**Issue by Sacrificialgaming** [AppliedEnergistics/Applied-Energistics-2#3438]
[Crash Log](https://gist.github.com/Sacrificialgaming/4b23e7d0d619bd921dcab037ea8816e8)

#### Description
Crashes on startup

#### Environment
Multiplayer

- Minecraft Version: 1.12.2
- AppliedEnergistics 2 stable 10
- Forge: 2631

**Comment by Meller127** [comment]
SpongeCoremod

**Comment by yueh** [comment]
We do not support Sponge officially.

Should you be able to reproduce it without it, please update the issue accordingly and we will reopen it.
