### ISSUE TITLE
Client Config Option to Disable Smart Cable Corners

### ISSUE THREAD

**Issue by XerShade** [AppliedEnergistics/Applied-Energistics-2#3441]
#### Description
So a few friends and I love this mod but there is one issue that we can't just get over and it's the little boxes that appear on smart cables every time something connects to it. A client config option would be a great idea for people that have a similar issue, plus it could possible use less resources not having to detect/render the boxes every other block on complex setups. I personally like using smart cables pretty much everywhere so I don't need to keep track of channels on large networks but end up using glass cables or hiding dense ones because of the boxes every time the cable turns. I suggest three options:
- On: Default behaviour that is currently in the mod.
- Connections: Only render them when connected to a bus/device.
- Off: No boxes at all.

**Comment by yueh** [comment]
They are simply necessary to avoid transition issues.
