### ISSUE TITLE
Storage buses stop working

### ISSUE THREAD

**Issue by soncemvo** [AppliedEnergistics/Applied-Energistics-2#3446]
On server i playing we have multidimension world. If you warp frim your "home" dimension to another and warp back storage buses stop working. It have channels, it have lights, buts it cant see invenory in chests and interfaces. 

Only way to fix it is to remove cable from bus and place it again, or remove bus and place it again.

**Comment by yueh** [comment]
Please consider the issue template when creating a new issue as well as any additional resource like the [contributing guidelines](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv5-1.12/.github/CONTRIBUTING.md) or the documentation available on [ae-mod.info](http://ae-mod.info/).
