### ISSUE TITLE
Storage buses stops working

### ISSUE THREAD

**Issue by soncemvo** [AppliedEnergistics/Applied-Energistics-2#3448]
On server i playing we have multidimension world. If you warp from your "home" dimension to another and warp back, storage buses stop working. It have channels, it have lights, buts it cant see invenory in chests and interfaces.

Only way to fix it is to remove cable from bus and place it again, or remove bus and place it again.

Forge version: 1.7.10-Forge10.13.4.1614-1.7.10
AE2 version: appliedenergistics2-rv3-beta-6-client
Mod Pack: 
https://github.com/Blood-Asp/GT5-Unofficial
https://bitbucket.org/IgorsBarkovskis/iis/src/84184f48e2fcc081569760a6742801d8dd8f693a/mods/?at=master

Video of reproducing bug:
https://www.youtube.com/watch?v=ueAnPnG9s7k

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.12 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
