### ISSUE TITLE
Storage Cells in network do not display/display and can't get them out of network.

### ISSUE THREAD

**Issue by 34486** [AppliedEnergistics/Applied-Energistics-2#3449]
#### Description
Expected: I expect AE2 to display in the terminal "craft" for the storage cell, and then the storage cell its self without deleting ones I craft  after that.. 
Ok the issue is that I have the system to autocraft 1k me storage cells, so it has that display to "craft" the cell, and then it crafts it, and replaces the option to craft it with the cell, which is an issue, and I am in the correct mode, to view both craftable and stored items... and when I manually craft one and put it in the system, it is just deleted... 

**EDIT**
If I restart the server, it displays correctly and I now have my drives, so they do NOT get deleted, they just are not displayed in the network!

#### Environment
Basic network I got going, has sufficient power. it has ONLY 1 1k autocrafting block. Basic setup really. I do NOT have any storage busses on the drive, so its not that. 

- Minecraft Version: 
- AE2 Version: RV5 - STABLE 11 - Latest version from the time of this post. 
- Forge Version:  1.12.2-14.23.2.**2632**

**Comment by 34486** [comment]
Anybody have a fix for this so the cells appear in the network after being crafted?

**Comment by GuntherDW** [comment]
I can't reproduce this is in either my dev enviro or in an obf'ed environment.
What other mods (especially AE2 addons) do you have installed?

Before: 
![before](https://i.imgur.com/wECjNqy.png)

After :
![after](https://i.imgur.com/034uAKj.png)

**Comment by 34486** [comment]
Huh. I do have the latest version of Extracells... I should have noted that in the first place, whoopz. I'll have to try without extracells somehow hopefully in the next 24 hours if I find time. 

Thanks!

**Comment by Zang518** [comment]
All I can attest to this. Currently running appliedenergistics2-rv5-stable-11 and experiencing the exact same problem described as the OP except I am using 64k storage cells with the extra cells 2 mod. See pics below. Also this is the Enigmatica 2 non-expert pack.

The sim for the pattern
![sim](https://user-images.githubusercontent.com/6557762/40278714-42e403fe-5c04-11e8-8325-73078f4b7b7f.PNG)

After auto crafting is complete. it displays two patterns in the system to craft the cell
![now 2 patterns but not](https://user-images.githubusercontent.com/6557762/40278717-5624f7e8-5c04-11e8-9959-2e80173038ee.PNG)

Trying to craft the cell again, sim displays that the cell is available, cannot start craft
![sim after crafting](https://user-images.githubusercontent.com/6557762/40278721-68d1f09e-5c04-11e8-9a08-3ed04d81408a.PNG)

I can export the cell out of the system via bus but when crafting again, says cell is missing, cannot start craft
![sim after export bus to chest](https://user-images.githubusercontent.com/6557762/40278725-7c1cd45c-5c04-11e8-8013-6617f42a7fcb.PNG)

A way around this for now is to remove the pattern from the interface via the interface terminal or the interface itself. Once I do that, it displays the crafted cell in place of the pattern and I can remove the cell and craft another cell like normal but only to repeat the process as described above.

i streamed a quick vid showcasing the wierdness
https://www.youtube.com/watch?v=KjoRdY5qO1k

**Comment by 34486** [comment]
Sorry for late reply! Works, and thanks! 👍

**Comment by bruzenak** [comment]
Adding a +1 to this. I get this in the latest All the Mods 3 pack running on a server. A few details:

* Seems to apply to any storage cell but not any component. It's just storage cell so far.
* When this happens, clicking on the cell doesn't remove it. 
* Using a fuzzy export bus will actually export the cell, but you still can't craft.
* If you break the ME Network, then put it back online, you can get the cell out. Breaks again on the next craft.
* Applies to 1k, 4k, 16k drives (haven't tested with 64 but I'm betting it does there too).
* Taking out the drive that the cell would have gone on allows you to craft again.

I hope this is helpful, I know finding bugs like this can be a needle in a haystack.

**Comment by 34486** [comment]
Yep. :D

**Comment by 34486** [comment]
Also, If you put a cell into a network, it only shows 1 and ya can't take it out! (I am sure somebody already said this but I forget and am too lazy to look up)
