### ISSUE TITLE
Unable to insert into conversion monitor if item not present in network

### ISSUE THREAD

**Issue by Meryl** [AppliedEnergistics/Applied-Energistics-2#3450]
A conversion monitor will not accept items that I try to insert into the network through them, if the item count is currently zero. 

#### Description
Expected behavior: Insert items into the network.
Actual behavior: Items remained in player inventory.

#### Environment
I'm playing on (a somewhat customized version of) FTB Revelation.

- Minecraft Version:  1.12.2
- AE2 Version: rv5-stable-8
- Forge Version: forge-14.23.2.2618

**Comment by yueh** [comment]
Could you please provide some more informations? Modpack, etc?

I cannot really reproduce it. It works just fine for me. BUT there is some really weird interactions when storing something as it places the blocks clientside before inserting them into the network. Yet I cannot find the issue as we cancel the block placement. So maybe something forge related, but if it actually issues a block placement before handing it off to us to handle the shift clicking, some protection mod might completely prevent it from ever reaching us.

**Comment by Meryl** [comment]
The modpack is FTB Revelation, originally I experienced the problem on 1.6.0. In the mean time I've updated to 1.8.0, which includes rv5-stable-11. I'm still having the problem, although it's *weirder* than I originally thought. I also experience the behavior you mentioned, although I'm unsure if this is relevant to the issues with inserting items I'm having.

I just tested this on FTB Revelation 1.8.0, AE2 rv5-stable-11 and Forge 14.23.2.2627. I've also added [these](https://i.imgur.com/eErDxs6.png) mods.

There seems to be a difference between items that can be placed as a block (e.g. stone) and items that can't be placed as a block (e.g. nether stars). There is, weirdly, also a difference between a conversion monitor that has been set to zero and (non-shift) right clicked afterwards, and one that has not been right clicked afterwards (not kidding). I feel like these may be two separate issues, as the first one (the difference between block items and non-block items) also exists when the monitor *isn't* locked.

When the monitor isn't locked, the behavior of shift + right clicking a non-block item into the conversion monitor doesn't have the effect (inserting the stack in hand into the network) it is supposed to have according to [this wiki page](http://ae-mod.info/ME-Conversion-Monitor/). Instead, it resets the monitor. Block items work as expected, but they do display the behavior you mentioned earlier (of having it look like the block is placed in front of the monitor for a fraction of a second) **unless** there is some reason the block can't be placed in front of the monitor, like the player standing too close to the monitor or something like a torch already occupying the space in front of the monitor.

The second problem occurs when a monitor is locked and is just incredibly *weird*. This problem exists for both block items and non-block items, and the only way I can explain it and stay sane is through [a video, so here's one on Gfycat](https://gfycat.com/gifs/detail/HalfBrilliantGallinule). When the count hits zero, inserting with shift+right click and an empty hand does not work, until you non-shift right click the monitor (once is enough, more doesn't matter).

I hope this is enough information for now, if you need more, do ask.

**Comment by frankGarlitos** [comment]
i just move in to 1.12.2 tthe very first mod ever that i search instantly is AE 2, but when i started to use it in creative mode flat world for testing ME terminals or any terminals I cant insert everything, and when i change the drive bcoz i use extra cell first, when i tried to use the default drive i can now put items but it will disappear i mean shift+right clickingin my inventory will make items disappear. instead of transfering it inside me network.

**Comment by fscan** [comment]
@frankGarlitos, this has absolutely nothing to do with this issue. If you can reproduce, please open a new issue with a detailed description, version information and preferably some screenshots.

@Meryl, can you test with rv6? i recommend with a new testworld, as there may be incompatibilities. Note that the interactions have changed, see #1480
