### ISSUE TITLE
Terminal sitting incorrect on Smart Cable

### ISSUE THREAD

**Issue by SquidNeko** [AppliedEnergistics/Applied-Energistics-2#3453]
- Description:

Im not fully sure if its the most resent version. But Twitch App says its appliedenergistics2-rv5-stable-11.jar
Whats happening is that when i place an ME Dense Smart Cable - Fluix ontop of an ME Drive and then after try to place an ME Crafting Terminal onto that cable to access the drives. The terminal always want to attach with its screen towards the cable and wont activate cause of the missing connection.
I attached an screenshot showing the problem i have.
![applied energistics 2 fail](https://user-images.githubusercontent.com/37712045/38334351-5fdef60c-385b-11e8-8081-6166b76af3d4.PNG)

I did try to extend the cable out longer to see if that fixed it. But same result no matter where i place an terminal.

- Environment

Its on an multiplayer server i have.
The mod is part of the modpack called FTB Revelation. Im on version 1.8.0 of FTB Revelation.

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv5-stable-11.jar
- Forge Version: forge 14.23.2.2627

**Comment by GuntherDW** [comment]
Parts, IE ex/import buses or P2P bus'es or terminals don't connect to dense cables.

Those only connect to smart cables.
