### ISSUE TITLE
Craftable items aren't showing in ME terminal

### ISSUE THREAD

**Issue by kekosminek** [AppliedEnergistics/Applied-Energistics-2#3454]
I can't craft things because the option to craft isn't there. Patterns are in a Me interface that is connected to a moleculal assembler but i can't craft

- Minecraft Version: 1.7.10
- AE2 Version: rv2.stable build 10
- Forge Version: 10.13.4.1614

Note: The glass in the picture bellow is there by a different ME interface attached to a furnace

**Comment by kekosminek** [comment]
@ktole1999 yes

**Comment by ktole1999** [comment]
if you craft an ME terminal can you see it in the list?

**Comment by ktole1999** [comment]
but an ME terminal will show all ME interfaces on the network. i havent used ME interfaces in a while. if it doesnt show up in the me terminal maybe something wrong with the block? idk.

**Comment by kekosminek** [comment]
i fixed it

**Comment by kekosminek** [comment]
thx
