### ISSUE TITLE
Issue with JEI crafting table auto fill

### ISSUE THREAD

**Issue by Dalethium** [AppliedEnergistics/Applied-Energistics-2#3455]
(Since this issue involves multiple mods, I am not 100% sure which repo to post this on, so I'll start here) 
#### Description
I use the universal wireless terminal from extra cells 2, and in the crafting menu when using jei to auto fill recipes with the plus button, it only auto fills when in the same dimension as the actual ae system.

To rephrase, using jeis build in feature to click the plus button and have items moved from the inventory to the crafting grid does not work outside the dimension that the ME Controller/Drives are in. 

#### Environment
[Full mod and env list with versions](https://pastebin.com/iB5mzR6k)
- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: 14.23.2.2611
- Extra Utilities 2 Version:  1.0 (According to mod meta, it is the latest release as of 2018/04/07)
- AE2 Stuff Version: 0.7.0.4
- JEI Version: 4.8.5.159

**Comment by yueh** [comment]
That is up to the mod adding the terminal.
