### ISSUE TITLE
Request: CraftTweaker support for crystal growing

### ISSUE THREAD

**Issue by TheDeviantCrafter** [AppliedEnergistics/Applied-Energistics-2#3457]
Crystal growing in AE2 is an interesting mechanic that I'd like to expand upon in my modpack. To do this, I'd like to be able to add new recipes.

`mods.appliedenergistics2.CrystalGrowth.addRecipe(IItemStack output, IIngredient input, int time);`

The items listed in the input array would be placed in the machine by the ME network, and convert to the output stack once the time defined in `int time` has passed.

**Comment by mindforger** [comment]
>The items listed in the input array would be placed **in the machine** by the ME network, and convert to the output stack once the time defined in int time has passed.

which machine? there is no machine for growing crystals ... do you maybe picked the wrong mod?

**Comment by TheDeviantCrafter** [comment]
For some reason  I'm thinking of the old crystal crystal growing mechanic. To fit it with modern AE2 you'd have to add new pure crystal types. At that point it should probably be an addon.

**Comment by mindforger** [comment]
there is an addon, i believe ae2stuff it is called, that adds a chamber for that purpose, but be warned those addon mods create strange behaviour sometimes, make sure to test without addons mods before reporting thign in this tracker :)
