### ISSUE TITLE
Crash with animania and morph-o-tool

### ISSUE THREAD

**Issue by Dalethium** [AppliedEnergistics/Applied-Energistics-2#3459]
[Crash log](https://pastebin.com/JnRfAiDY)

Minecraft Version: 1.12.2
Forge Version: 14.23.3.2666
AE Version: rv5-stable-11
Morph-o-tool Version: 1.2-16
Animania: 1.4.7

I check for updates multiple times a day with this pack so everything should be up to date. 

Alright so, I was in a spatial storage cell dimension, I was using my morph-o-tool with the ae networking tool installed, I switched hands (thereby making the morph-o-tool stay in the ae item mode) and I right clicked my hamster from animania with a empty hand, it removed the hamster ball (not sure if that's important but I know I like details for bug fixes) -- then I switched back to my morph-o-tool (still in a.e. networking tool mode) and accidentally right clicked the same hamster, my game crashed instantly. 

If you need any more information let me know, I keep all logs so if there's anything I missed let me know!

Good luck!

**Comment by GuntherDW** [comment]
This is happening because the BlockPos object it got back from the RayTraceResult is null.
We'll have to find out why exactly this is happening.
