### ISSUE TITLE
Game crashing while installing Flan's Mod causing AE2 to error during loading

### ISSUE THREAD

**Issue by EmeraldTiger64** [AppliedEnergistics/Applied-Energistics-2#3460]
Hello, sorry to bother anyone. I recently got an idea to use flans in a custom modpack of mine, and whenever I try to launch the game with flans, it causes AE2 to crash in the loading phase. It is discoverable while looking through the crash log that 

#### Description
 It is discoverable while looking through the crash log that AE2 is erroring on the game loading up. When I take flans mod away though, it works fine and without a hitch. The game loads about as far as post-initialization, and then crashes.

#### Environment
I am using a 1.12.2 game instance with the MultiMC launcher. Here is the link for the crash-log, https://pastebin.com/5KyC0J3b.

- Minecraft Version: 
- AE2 Version: rv5-stable-11
- Forge Version: 14.23.3.2655

**Comment by mindforger** [comment]
that crash log is cut up at the most vital point, the stack trace is missing 

also only 1 gig of RAM is a bit optimistic imho! 

>-Xmx10240m

make that more like -Xmx2G

**Comment by Pingger** [comment]
Why is a 10GB RAM limit a problem? I mean Java doesn't allocate more than it needs (usually)

**Comment by mindforger** [comment]
oh well ... i missed that additional zero at the end ... it was such an unusual writing XD

**Comment by EmeraldTiger64** [comment]
I still have no clue though as to why the game is crashing.

**Comment by bookerthegeek** [comment]
You have duplicate dimension id's you meed to fix via condigss.

The mod you added should have a config option to change the dimension id.

**Comment by Pingger** [comment]
In your AppliedEnergistics2.cfg (<minecraft>\config\AppliedEnergistcs2\)
change the setting under
```
spatialio {
  [...]
  I:storageDimensionID=<other ID>
}
```
Where <other ID> is an ID, for which you don't find a folder in your savegames folder (<minecraft>\saves\<yoursavename>\DIM<usedID>)
If unsure try 5678

**Comment by mindforger** [comment]
>NOTE to myself: before replying to an E-Mail on github, see if there are newer mail regarding the same issue 

yeah i kinda don't like github for that ... only sending a mail for a enwly created comment and then no additional note if i add something to it ...

**Comment by EmeraldTiger64** [comment]
Massive thanks to everyone who helped me solve this issue. I was able to get the game to load just fine.

**Comment by Zipper213** [comment]
After i read this, i changed the DimensionID to 5678. It now works with flans, i have been trying to get it to work for like an hour.  Thanks :)
