### ISSUE TITLE
Custom Recipes Problem

### ISSUE THREAD

**Issue by yepidoodles** [AppliedEnergistics/Applied-Energistics-2#3461]
#### Description
I'm having an issue with the shaped recipes via the custom recipes. I started out changing some of the Processor recipes (changed `dustRedstone` to `dustEnderPearl`) and had no issues, worked straight away. So I continued then to replacing `ingotIron` to `ingotSteel` in the rest of the recipes (no other changes made) however they did not load once I restarted my modpack (custom processor/ inscriber recipes mentioned above still work).

#### Environment
- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: 14.23.2.2654

I'm sorry if this isn't a good report, I'm just out of ideas of things to try. The fact that the inscriber recipes work and the normal shaped ones don't have totally baffled me.

~ Alice

**Comment by yueh** [comment]
Because shaped/shapeless are now using the normal minecraft recipes. To some degree they might only be really usable once 1.13 is released.
