### ISSUE TITLE
Cannot find config.

### ISSUE THREAD

**Issue by shnopy** [AppliedEnergistics/Applied-Energistics-2#3463]
#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: latest 1.12.2
- Forge Version: recommended 1.12.2

I cannot find the config file.

I

**Comment by ktole1999** [comment]
keep looking

**Comment by shnopy** [comment]
so helpful... Well i found it with no help from you.

**Comment by ktole1999** [comment]
95% of mod configs are in config folder



Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by mindforger** [comment]
also
>
    Minecraft Version: 1.12.2
    AE2 Version: latest 1.12.2
    Forge Version: recommended 1.12.2


this is nowhere near any proper issue report!
