### ISSUE TITLE
[Enh] Remove sparkles from Certus Quartz crystal texture.

### ISSUE THREAD

**Issue by AnrDaemon** [AppliedEnergistics/Applied-Energistics-2#3464]
As it stands, the textures for regular (non-charged) Certus Quartz and charged version are only differ in slight tint. You have no way to tell them apart, unless you either have both in the inventory or hover over it with mouse.

I suggest removing the sparkles from `textures/items/material_certus_quartz_crystal.png` texture to make crystals more distinctive.
Something along the lines of this: ![CertusQuartzCrystal](http://project.rootdir.org/gallery/minecraft-1.7.10/?view=ItemMaterial.CertusQuartzCrystal.png)

**Comment by yueh** [comment]
The sparks are part of the normal texture, simply as they are crystals.

While they are certainly not using complementary colors, they are usually not that hard to distinguish.
Certain color blindnesses could be an issue e.g. achromatopsia, but I do not know of a single report in this regard.

So for now, we stick to the current textures as there are still texture packs for persons, who really dislike them for various reasons.

**Comment by AnrDaemon** [comment]
Regarding "crystals", I have another complaint. But first, what are the Forge policy on oredict usage currently? I've heard there were changes.

**Comment by AnrDaemon** [comment]
P.S.
"Not that hard to distinguish" is not the same as "easily distinguishable".
