### ISSUE TITLE
Grindstone suggested Ore names update.

### ISSUE THREAD

**Issue by sinistar26** [AppliedEnergistics/Applied-Energistics-2#3467]
#### Description
appliedenergistics2-rv5-stable-11.jar
Not seeing Aluminum due to inconsistent spelling between two spelling methods ( Aluminium )

S:grinderOres <
        Obsidian
        Ender
        EnderPearl
        Coal
        Iron
        Gold
        Charcoal
        NetherQuartz
        CertusQuartz
        Wheat
        Fluix
        Copper
        Tin
        Silver
        Lead
        Bronze
        Brass
        Platinum
        Nickel
        Invar
        Aluminium
        Aluminum
        Electrum
        Osmium
        Zinc
        Yellorium
        Uranium

#### Environment

 Will make Grindstone compliant with other mods that a typically used with your mod.

<!-- The following ones are required, Aluminum, Yellorium, Uranium
- Minecraft Version: 1.12.2 (modded)
- AE2 Version: appliedenergistics2-rv5-stable-11
- Forge Version: 14.23.3.2669

**Comment by yueh** [comment]
I would not consider Yellorium or Uranium as early game ores by default and none of them are really applicable for manual processing. With the grindstone being mostly designed as early game alternative to other grinders/pulverizers/etc or as fallback solution should there literally be no other machine providing the same mechanic, there is little reason to unrealistic options. Yet modpack authors can still change the whitelist to fit their particular needs.
