### ISSUE TITLE
Cable visual glitch

### ISSUE THREAD

**Issue by Tzorion** [AppliedEnergistics/Applied-Energistics-2#3468]
- Minecraft Version: 1.10.2
- AE2 Version: RV4-stable-1
- Forge Version: 12.18.3.2511

When placing cables, they will only connect after I tp out and back in, sometimes they randomly disconnect from eachother, but they keep function, so purely visual, but a pain since I cannot click on interfaces etc.

**Comment by mindforger** [comment]
Do you have an security station? If yes, do you have everything chunkloaded? Unloading chunks tear the network and the security station prevents  reconnection

**Comment by Tzorion** [comment]
I dont have a security station, I have the chunk loaded (even ehile offline)

I tried to remove the loaders, but it came back with same result
They do not disconnect on chunkborder either, its pure random.

**Comment by Tzorion** [comment]
![2018-04-22_21 45 54](https://user-images.githubusercontent.com/3669114/39099192-97c829ca-4676-11e8-9d15-a54d56889b5e.png)

**Comment by Tzorion** [comment]
this is after I tp'ed 4 chunks away and back
![2018-04-22_21 48 05](https://user-images.githubusercontent.com/3669114/39099208-e8448c36-4676-11e8-8b83-34c9e73114a9.png)

**Comment by Tzorion** [comment]
as stated in the first post, this is client side only.
I have reinstalled without any optional mods (its a Beyond server)

**Comment by bookerthegeek** [comment]
This looks like ping lag. What is your ping to the server?

**Comment by Tzorion** [comment]
111ms

**Comment by bookerthegeek** [comment]
If you wait a while do the cables fix themself?

**Comment by Tzorion** [comment]
Sometimes, when placing a long cable, some of the previous will connect, but not all of them.

**Comment by bookerthegeek** [comment]
Honestly it looks like a mix of ping and tps issues.

**Comment by Tzorion** [comment]
tps is steady at 20, everyone switched to Revelation.. 

Tried joining the rev. server, had no issues at all with cables.

Also tried curse launcher, reinstall, inc. Ram and permgen, without result.

**Comment by Tzorion** [comment]
Just noticed, my storage monitors does not update when items is imported to the system, have to tp out/in to get them updated, so no realtime updates at all.

Could this be Java? other players are having the same problem on the server, but not everyone..

**Comment by mindforger** [comment]
sounds like a server that is acting up, do you have insight if there is sponge/bukkit/bungee involved with this server?

**Comment by mindforger** [comment]
>there is a server hub

do you mean a world where you can choose which other world you want to join (normally organized in dimensions) or like a real serverhub like bungee that acts like a proxy to other physical or logical server instances? 

AE only supports normal forge minecraft because it is hard enough to maintain stable code for one type of server, bungee may drop packats or other funky stuff we don't know

**Comment by Tzorion** [comment]
like a bungee, where you can select various servers from 1 place.

**Comment by bookerthegeek** [comment]
@Tzorion Two things;

1. What is the name of the server you are playing on?
2. If you could have one of the staff with access to the back end (Console and the file system, usually only Admins and Owners have that access) I would be willing to assist them. This is not a Mod issue, but a server issue.

**Comment by yueh** [comment]
Both, and always just the latest release. So even rv5-stable-10 is unsupported, because there is no way to fix anything, when people refuse to update.

**Comment by mindforger** [comment]
thx, i just wanted to update myself to support you better

**Comment by yueh** [comment]
rv5-stable-10 is certainly a bit artifical, usually it's just the current stable + potentially an upcoming release.
But I certainly do not remember every single bugfix in every release, so it's easier to request that only the latest release is used for bug reports.

**Comment by Tzorion** [comment]
Hey guys, sorry for the late response, been at work.

So the only option is to update the server atm?
doubt I can convince them to do that if its only some players who got the issue :(

**Comment by mindforger** [comment]
@bookerthegeek and i were assuming the issue is from the server itself because it may not use regular forge causing this

the best bet would be to try to replicate this issue with as few as other players present and closely observe the log for any network traffic issues ... second bet would be the server itself derps up the data sent to the client, this is why the devs can not support it, it would be to big of a hassle to maintain code for different platforms

**Comment by Tzorion** [comment]
Hoped this was an client side glitch, but it seems there is nothing I can do about from my side?

**Comment by mindforger** [comment]
help @bookerthegeek and show him how to join the server and how to contact stuff he want's to test and help :)

**Comment by Tzorion** [comment]
server site https://toastynetworks.net/
server ip (hub) play.toastynetworks.net

The discord is very active and it should be possible to reach the right person there.

**Comment by bookerthegeek** [comment]
@Tzorion I need your discord name please.

**Comment by Tzorion** [comment]
Neryn

**Comment by Tzorion** [comment]
They gave me this info:

For further debugging, we use the following versions:
[08:24:56] [Server thread/INFO]: SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 5.2.0-SNAPSHOT-c675e80
    SpongeForge: 1.10.2-2477-5.2.0-BETA-2731
    Minecraft Forge: 12.18.3.2477
