### ISSUE TITLE
AE@ Autocrafting not working

### ISSUE THREAD

**Issue by Ribbons0121R121** [AppliedEnergistics/Applied-Energistics-2#3469]
minecraft version:1.7.10

i try autocrafting as usual and i try testing crafting for a wooden pickaxe.
nothing happens after i tell it to craft.
it says its schedueled and it says i can craft more, but nothing is working for autocrafting.
what is wrong with this!?!?

**Comment by bookerthegeek** [comment]
With your ability to provide such degailed information, I will assume it is a [PEBCAK](https://en.m.wiktionary.org/wiki/PEBCAK) error.

**Comment by Ribbons0121R121** [comment]
well ive debugged it and my setup is 1 fully upgraded auto crafting cube. it says its scheduled and nothing happens. ive tried everything but the only thing that doesnt work is auto crafting.

**Comment by Pingger** [comment]
We need:
AppliedEnergistics Version
Forge Version
Your exact Setup (better yet the savegame)

Also: What do you mean with 'debugged', what exactly did you test, because I don't think, that you tested P2P tunnels, spatial storage, ... (which _probably_ isn't related to your problem, but still is included in 'tested _everything_')

**Comment by mindforger** [comment]
i will close this for an unsupported 1.7.10 minecraft version

if you hit this issue in the latest version then open a new issue, and this time, read before you remove the template text .... 

you are lacking a ton of information to help ... 
also for this kind of error always make screenshots of your setup and the templpates and the machines or components invloved in that crafting process (hover templates with mouse when taking the screenshot, to assure they are configured right)
