### ISSUE TITLE
FTB revelations - Unable to access/use all of the blocks

### ISSUE THREAD

**Issue by tommynov1000** [AppliedEnergistics/Applied-Energistics-2#3470]
- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: 14.23.2.2627

I host a FTB revelations 1.8.0 server through creeper host, and I was redirected here to solve an issue:

Before restarting the server, there were no issues. After the restart, however, I was unable to access the ME drives, crafting monitor, ME interface, ME interface terminal, ME wireless access point, etc ONLY when powered. I was able to access all, except for the crafting monitor, when unpowered. Further, I tried to replace everything, but ran into this issue upon doing so: 

https://imgur.com/a/BQl2eUJ

In this gif, I'm trying to replace a wireless access point, only to have it break immediately and drop on the ground for me to pick up. This only happens when the system is unpowered. When I try to place things down when the system is unpowered and access immediately after, the same issue arises: I'm unable to access the GUI. This happens for all the aforementioned machines/blocks.

Lastly, my current system has an ME terminal, ME crafting terminal and a ME pattern terminal. For all of these blocks, I'm able to access the GUI, but unable to craft/interact with the GUI (I cannot remove items or put items into the system).

The pack has not been altered, except for a config file dealing with FTButils, which was changed to increase the number of claimable/loadable chunks we could take advantage of.

**Comment by mindforger** [comment]
sounds like an either improperly chunkloaded network that did not boot up complete so the security station keeps blocking the parts in chunks loading after the security station or the server messing up the boot of the network somehow
