### ISSUE TITLE
All crafting items drop on the floor?

### ISSUE THREAD

**Issue by Echoeggs** [AppliedEnergistics/Applied-Energistics-2#3471]
So I have a pretty large computer in the Infinity Evolved Modpack and I created a massive crafting CPU to make Solar panels with. I can start the crafting, and log off the server with a chunk loader running, but when I get on, the several hundreds of thousands of items that were being used to craft the solar panels were spilled out on the floor around the crafting CPU. It's not like they don't fit in the computer, as one of the items is cobblestone for which I have a deep storage unit. The items cause massive lag, and my only option to make the game playable again is to wait until all the items have despawned, which takes forever since time is moving so slow.

- Minecraft Version: 1.7.10
- AE2 Version: rv3 beta 6
- Forge Version: 10.13.4.1614

**Comment by mindforger** [comment]
closing this due to 1.7.10 not being supported, but i know your issue :)

>with a chunk loader running

which exact type? the chicken chunks don't keep stuff loaded properly! us the smaller spot loaders, they work perfectly well, also the extra utils one and the worldanchor from railcraft

**Comment by Echoeggs** [comment]
I Used the chunk loader from MineFactory Reloaded

**Comment by mindforger** [comment]
that is strange, are they powered properly? is the power source also safely chunkloaded?

still try with alternate chunkloaders please, i am a little stunned here

**Comment by GuntherDW** [comment]
Are you certain that it's chunkloaded correctly? The MFR chunkloaders chunkload in a circular patter, not a square/rectangle one.
That got me off guard when I used them years ago because that wasn't documented. at all. anywhere.
