### ISSUE TITLE
Applied Energistics does not remember channel pathing after a server restart.

### ISSUE THREAD

**Issue by Xiaminou** [AppliedEnergistics/Applied-Energistics-2#3473]
#### Description
I have a group of 32 interface into molecular assemblers, the way I cabled it they all have channels. However I have found that after I restart my server I must break and replace two of the Dense Cables providing the channels so that the path the channels take works again.
Applied Energistics should remember what path the channels took before the server restart, otherwise you end up with this kind of problem.

Before I replaced the cables (after a server restart):
![2018-04-29_14 08 34](https://user-images.githubusercontent.com/8670392/39406581-9916e630-4bb8-11e8-8054-94dc18f0f54f.png)

After I replaced the cables (before a server restart):
![2018-04-29_14 20 30](https://user-images.githubusercontent.com/8670392/39406570-7fe7887c-4bb8-11e8-964d-f70b71383b98.png)

#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: stable 11
- Forge Version: 2673
- Mods: [list.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1958694/list.txt)

**Comment by yueh** [comment]
This is intentional.

**Comment by Xiaminou** [comment]
Why?
