### ISSUE TITLE
AE equivalent of Bulk50 mode?

### ISSUE THREAD

**Issue by cinnamennen** [AppliedEnergistics/Applied-Energistics-2#3475]
In logistics pipes, there was a supplier mode `Bulk50` that would supply an inventory with a requested amount of items, but would only request/craft more of an item once the supply dropped below 50%. This was useful as it batched together crafting requests. Is there an equivalent way to get this behavior in AE2?

**Comment by mindforger** [comment]
I don't think you can have this treshold behaviour but you can configure an interface to provide a defined number of items and add a crafting card

**Comment by yueh** [comment]
As @mindforger said, there is no threshold/stockkeeping behaviour for any external inventory at all. Interfaces might fit to some degree, but it is only a batch of the missing items, so it might be just 1.
A more fine grained solution is basically up to the user to build by combining various parts like level emitters together.
