### ISSUE TITLE
Crash with Name Inscriber Press and Inscriber

### ISSUE THREAD

**Issue by sajhino** [AppliedEnergistics/Applied-Energistics-2#3476]
[Crashlog](https://pastebin.com/A7QZ3aAy)

Modpack: FTB Revelations 1.8.0
Minecraft Version: 1.12.2
Forge Version: 14.23.2.2627
AE Version: rv5-stable-11

Steps to replicate crash:
1. Make 2 Name Inscriber Press.
2. Place them into an Inscriber, one on the top slot and one on the bottom slot.
3. Place an ME Interface into the middle slot.
4. Remove the top Name Inscriber Press as the ME Interface is being renamed.
5. Game crashes.

Can't even load the world anymore after the crash, have to use an older backup.

**Comment by mindforger** [comment]
hope you don't mind me slapping the label on it @yueh, this one seems confirmed, a more clean report is over in the linked issue i just closed because of duplication

https://pastebin.com/PnQrSya4

from @bkbarbee for reference
