### ISSUE TITLE
[1.12.2]Crashed each time on Spongeforge server starting up

### ISSUE THREAD

**Issue by Tollainmear** [AppliedEnergistics/Applied-Energistics-2#3477]
#### Description
This crash occured after a server crash [(Crash-Report)](https://gist.github.com/Tollainmear/0402629e7e1604fc58b0af2fd52c04d7)，then the server goes crash (with the same [crash-report](https://gist.github.com/Tollainmear/fbbe182aa56bcdd65d10e43b70b0274c) which different with further crash-report) every time and could not start/run, whether set `B:removeCrashingItemsOnLoad` to true or false.

An'the [info](https://gist.github.com/Tollainmear/fef6a3471880f19415f81a71682c1a3c) might different with crash-report in log file.

#### Environment
happened on Spongeforge server 1.12.2

- SpongeForge: API-7.1.0-Beta-3064
- Minecraft Version: 1.12.2
- AE2 Version: rv5-s11
- Forge Version: 2655

If any information else needed, I'll provided soon 😅 
@yueh

**Comment by JackMeds** [comment]
I met the same problem too

**Comment by mindforger** [comment]
first crash has nothing to do with ae, second indicates an broken chunk or a forge bug or maybe sponge, also sponge is not supported and third „me too“ without any additional logs or data is pointless and the opposite of helping

Will close for unsupported environment, if you can reproduce with regular sponge, call back with another crash report please

**Comment by Tollainmear** [comment]
@mindforger However, could your please help me to analysis this [exception](https://gist.github.com/Tollainmear/fef6a3471880f19415f81a71682c1a3c)?

A lots of exceptions mention the appeng.me package, so I'm curious about how's that happened and how can I solve that :flushed:
