### ISSUE TITLE
Items Wont leave Me Interface Inventory

### ISSUE THREAD

**Issue by Genetichunter** [AppliedEnergistics/Applied-Energistics-2#3487]
Im using AE2 from 1.7.10. I have a Me network set up and it has a Molecular Assembler with a me interface hooked up to it. The problem I am running into is the items I request for crafting are being crafted then left in the me interface storage area. It wasn't doing this before then I added more patterns to the interface and all of a sudden it started leaving the items in the interface instead of pulling them out and putting them into my hard drives. Is this how its supposed to work or is there some way I can push them out of the interface and back into my computer system.

**Comment by Genetichunter** [comment]
Lol psych just kidding I am an idiot. I just realized my me system was full and wasn't accepting anything else.

**Comment by mindforger** [comment]
be aware if you use ender io ME conduits

i noticed that wrenching (or disabling via GUI) an conduit does introduce VERY strange channel behaviour ... always use cable anchors to seperate ME cables from ME conduits (except one enderio conduit from another, that works fine as it looks like)
