### ISSUE TITLE
Can't take Ender IO Soul binder out of ME system 

### ISSUE THREAD

**Issue by vinyl90** [AppliedEnergistics/Applied-Energistics-2#3488]
#### Description
Ok so I put a bunch of stuff in my me system from my chest one was the soul binder from EnderIO but when i went to take it out it will not come out with click drag or click or shift click its just stuck in there.
#### Environment
well Applied Energistics 2, EnderIO-5.0.381 and more if you want to see the full list go here https://server.enderio.com/
- Minecraft Version: 1.12.2
- AE2 Version: RV5-stable-10
- Forge Version: 14.23.2.2654

**Comment by GordoOscuro** [comment]
I have the same problem, cant take Soul Binder out of my ME system.

**Comment by HadesDurin** [comment]
have you checked if the client has same settings in config as the server has?
mostly the client uses a diffrent recipe setting than the server..

**Comment by matix931** [comment]
Problem still exists on:
AE2 Version: RV5-stable-11
EnderIO-1.12.2-5.0.25

Soul binder stuck in ME cell, can't take it out in any way :/

**Comment by fscan** [comment]
Can't reproduce, can you try without ae2stuff?

**Comment by GuntherDW** [comment]
There might be another mod interfering with the items,
I can't reproduce it either on our server, and we have AE2Stuff and WCT installed alongside AE2.

**Comment by Ommina** [comment]
Does https://github.com/SleepyTrousers/EnderIO/issues/4628 offer any insights?

It is in the context of RS, but does provide some (potential, at least) reproduction steps.

**Comment by fscan** [comment]
Yes, that would explain it. I don't think there is anything we can do about it. We have to check the NBT equality. If there is a NaN in there it will never be equal (NaN == NaN is always false)
