### ISSUE TITLE
While searching in the terminal and hovering over an item, pressing R will trigger JEI

### ISSUE THREAD

**Issue by kosakriszi** [AppliedEnergistics/Applied-Energistics-2#3489]
#### Description
I fully understand that this is a duplicate of https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2634, however it has been almost 2 years since that issue, and technology has evolved. I struggle to believe that nothing can be done to remedy this, seeing as Refined Storage has somehow worked around this issue. This is a huge usability problem, and having to move my mouse every time I'd like to search for something with an R or U in its name is both exhausting to remember, and frustrating when you forget to do it.

#### Environment
- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: 14.23.3.2679

**Comment by mindforger** [comment]
i wonder why nobody in all this time did not bug the JEI devs about it ....

**Comment by GuntherDW** [comment]
We might be able to work around it the same way other mods (like RS) do it. At least when auto search is enabled.

https://github.com/mezz/JustEnoughItems/blob/1.12/src/api/java/mezz/jei/api/gui/IAdvancedGuiHandler.java#L33

**Comment by kosakriszi** [comment]
That method looks like the exact way that RS deals with this problem, they return null when the search bar is focused:
https://github.com/raoulvdberge/refinedstorage/blob/mc1.12/src/main/java/com/raoulvdberge/refinedstorage/integration/jei/GuiHandlerGrid.java

@mindforger No one bugs the JEI devs about it because they provided a way to control this behavior :)

**Comment by GuntherDW** [comment]
The thing about that class is that it only gets fired when it can't find the item under your cursor.
So we'll have to make some other changes to our UI classes as well.

I haven't put *too* much time into it yet though.

**Comment by yueh** [comment]
As you noticed it is still not working, technology has not evolved since then. The underlying cause is that forge still offers two completely incompatible ways to handle inputs.

If you want a fix, either convince forge to only provide a single system or make both comaptible with eachother. Also we cannot add a special case for every mod out there adding their own hotkyes.
