### ISSUE TITLE
Massive Lag in Pattern Terminal

### ISSUE THREAD

**Issue by scotty9090** [AppliedEnergistics/Applied-Energistics-2#3490]
#### Description
When opening the pattern terminal, I get a massive amount of lag, mouse becomes unresponsive, etc.  This seems to be somewhat inconsistent and will often start out fine (although a little bit sluggish) and will either remain stable, but often gets worse and worse.  At times, it suddenly seems to recover and performance goes back to acceptable levels.

This is the first time in many playthroughs with both AE2 and this pack that I've run into this problem.  I've tried breaking replacing the terminal, moving it to different locations on the network - not really sure what else to try so any advice or things I can do to further diagnose the issue would be welcome.

EDIT: All other terminal types are fine - Crafting Terminal, Interface Terminal, etc.  I've systematically disconnected every segment of my network with the terminal directly connected to the controller (no P2P) and the problem persists.

EDIT2:  Okay it seems to be tied to putting anything in the crafting grid.  So if I have a blank workspace performance is fine.  As soon as I shift click in, or manually drag items into the pattern terminal grid (to try to encode a pattern) performance starts to suffer.  The more items I put in, the worse it gets.  I think this likely explains the perceived "inconsistency" that I sighted in my original post.

#### Environment
I have a fairly average AE2 network setup - nothing extreme and this problem has happened from very early game when my network was really basic.

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: 14.23.3.2674
- Pack: ATM 3 v5.9.5

**Comment by yueh** [comment]
Nothing we can do without any actual sampling/profiling results.

**Comment by mindforger** [comment]
Try a creative energy cell as power source, you may suffer power outages due to small capacity in your system, always make sure to have enogh powercells installed

**Comment by scotty9090** [comment]
Can you point me to something that explains how to enable sampling / profiling?  I've never done this before and not sure what to do.  Is this the vanilla profiler (/debug start)?  Or something with Forge?

**Comment by Pingger** [comment]
Opis would be good for thos. Unfortunately it is out of date. Last working version is for 1.7.10

**Comment by Buuz135** [comment]
It seems to be instense checking inm the recipe tree, it happens with both modes (Processing and Crafting)

![ae2](https://user-images.githubusercontent.com/3874674/40349146-f539981e-5da5-11e8-87a7-bcab0e8a7cc5.png)
[ae2_snapshot.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/2025512/ae2_snapshot.zip)

**Comment by yueh** [comment]
The cache probably will not be that impressive, as it it will not prevent that many duplicate calls as most ones can still be considered as unique call (or have to). Not comparable to say the changes we could make to a crafting terminal.

The underlying cause is that recipes in minecraft are slow as hell and it seems that forge is fine with it.
