### ISSUE TITLE
Null Pointer Block Cable Bus

### ISSUE THREAD

**Issue by artdude543** [AppliedEnergistics/Applied-Energistics-2#3491]
#### Description
Debugging a server world from a SevTech's user; and on their world they are getting a crash from a setup which I can't get to due to crash.

I guess maybe throwing a null check could be a fix here; but I feel like BWA would need to do something also about this.

#### Environment
This was on a server world.
Report: https://gist.github.com/artdude543/6a4894759581b105b7ef777f0d8b922b

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: 14.23.1.2554

**Comment by kylev** [comment]
This appears to be a bug in BetterWithMods: they were calling pick() with a null target sometimes.

BetterWithMods/BetterWithMod#0720f24b8dbdf505a54da017e3dbb9f843783a48
