### ISSUE TITLE
Unable to properly autocraft storage cells

### ISSUE THREAD

**Issue by Sovereignty89** [AppliedEnergistics/Applied-Energistics-2#3498]
#### Description

When trying to autocraft 1k, 4k, 16k and 64k storage cells I am getting some unexpected behaviour. It is best shown in [this](https://www.youtube.com/watch?v=qCCGlGNetEY) video. 

The pattern is correct and there is also no other pattern for the same cell. When crafting any cell, the result either disappears or when the result is pulled out of the ME system, the ability to craft it disappears with it. When replacing the pattern in the interface (taking it out and putting it back in), the ability to craft appears but the item that it crafted doesn't stack on top of it. 
Sometimes it creates it but then shows up as [this](https://i.imgur.com/VJMzdZt.png), when replacing the pattern again, the second 'craft' will change in to 1 but again, not stack with the actual crafting recipe. The video shows everything in greater detail.

I have tried the patterns in another interface. I have broken the interface and replaced it. Other recipes in the same interface work fine as well as other crafting recipes. I have not tried crafting any higher cells from (Extra Cells2).

#### Environment

We are on version rv5-stable-11, on a MP server using modpack ATM3

- Minecraft Version: 1.12
- AE2 Version: rv5-stable-11
- Forge Version: 14.23.3.2678

**Comment by mindforger** [comment]
can you reproduce this without any AE2 addon mods? because i saw very strange cell recipes there, something like extracells or such things?

**Comment by Sovereignty89** [comment]
Yes, ATM3 does have Extra Cells 2, should've mentioned that more clearly, sorry. I will try and test this without Extra Cells 2. I must add that this only happens on the server I play on and not on SP with the same controller/p2p design. 

I'll update with more info as soon as I know more.

**Comment by mindforger** [comment]
GunterDW already has taken that issue :)

should be just a matter of time for fixing hopefully :)

**Comment by Sovereignty89** [comment]
Thank you very much :)
