### ISSUE TITLE
Minecraft crashed while rendering the crank of a grindstone

### ISSUE THREAD

**Issue by NYorck** [AppliedEnergistics/Applied-Energistics-2#3499]
When I try to join the Minecraft server that I used to play on my game crashed with the following crash report: https://pastebin.com/bc8hhkjn
If I am right in reading the crash log it is cause by the crank of a grindstone that my friend build in our base.
I am playing the modpack All of the mods 3 v.5.9.4b

- Minecraft Version: 1.12.2
- AE2 Version: rv5 stable 11
- Forge Version: 14.23.3.2678

**Comment by yueh** [comment]
I do not see anything obvious causing it. Currently I would guess it is either just some random crash due to data corruption or some othere mod interfering with the rendering. Best idea would to reduce the mods when trying to reproduce it.

**Comment by NYorck** [comment]
It was already fixed by removing the crank but I hoped that sharing this would help finding the cause for it. If you say that it might just be some data corruption then it is probably not reproduceable.
