### ISSUE TITLE
Substitutions seem not to be working

### ISSUE THREAD

**Issue by mmalfatti** [AppliedEnergistics/Applied-Energistics-2#3500]
Bowl, stick, piston, wood planks recipes won't accept substitutions when trying to craft.

#### Description

Getting these messages in the server window:

"[21:00:42] [AE Crafting Calculator/WARN] [AE2:S]: Using CraftingManager fallback: Recipe <minecraft:stick> for output <4xitem.stick@0> rejected inputs [351xtile.stonebrick@0, 1xtile.wood@0]. NOT FOUND, please report."

"[21:02:37] [AE Crafting Calculator/WARN] [AE2:S]: Using CraftingManager fallback: Recipe <minecraft:piston> for output <1xtile.pistonBase@0> rejected inputs [1xtile.wood@0, 1xtile.wood@0, 1xtile.wood@0, 10xtile.stone@5, 1xitem.ingotIron@0, 1xtile.stonebrick@0, 1xtile.stonebrick@0, 1xitem.redstone@0, 1xtile.stonebrick@0]. NOT FOUND, please report."

### Environment
Mac 10.13.4, Java minecraft, jdk1.8.0_152 minecraft v1.12.2, AE2 v rv5-stable-11, forge 2655, MP,
136 mods on client side

- Minecraft Version: 
- AE2 Version: 
- Forge Version:

**Comment by yueh** [comment]
This just indicates there is something wrong with the recipes of your modpack, which are rejecting the alternative items.
