### ISSUE TITLE
Pulling all of an item out of the system causes a crash and world corruption

### ISSUE THREAD

**Issue by PanzarTank** [AppliedEnergistics/Applied-Energistics-2#3501]
Basically whenever I pull all of an item that the system knows how to make out of my ME system the world crashes and corrupts. The error is: java.lang.IllegalArgumentException: Stack can not be invalid!

#### Description
Steps taken to reproduce the bug:
1) Set up basic ME system storage.
2) Put some glass into the system.
2) Connect system through an interface to a Thermal Foundation Redstone Furnace.
3) Use a Pattern Terminal to make a pattern for glass. Sand -> Glass Processing Pattern and put the pattern in the interface connected to the Redstone Furnace.
4) Go to the ME crafting grid and pull out all of the glass you had in there originally.

#### Environment
- Multiplayer Server
- Crash Log: https://pastebin.com/ysYZPrfx
- The modpack is FTB: Revelation with 4 or 5 custom mods.

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: 14.23.2.26.27

**Comment by yueh** [comment]
`at extracells.part.PartOreDictExporter`
