### ISSUE TITLE
Heavy delay when interacting with item in shown by AE2

### ISSUE THREAD

**Issue by andr9528** [AppliedEnergistics/Applied-Energistics-2#3502]
#### Description
I'm not sure how best to describe this, so on top my attempted description will also pack up my Modpack, and add a link to it. This might not be an AE2 bug, but AE2 is the only mod where i fell the issue.

I expect to be able to take out items and order new crafts, with very little to no delay from clicking on it to actually opening/taking out the items.

In reality tho, i can take anywhere from immediately to infinite time for an action to actually happen. When it is infinite time, it will simple not do anything or so it seems, until you do some other action which end up being successful, in which case you would see the prior action for a split second.
 - Example: you go and try to open the window where you set how many you want to craft of an item, but the window never opens, so instead you begin to pull out an other item from the system, and in the moment you do that, the crafting window pops up for a split second.

this Also means that will you are pulling out items, you might not see them actually being pulled out being held your cursor, but they are actually in your cursor, clicking them into ones inventory, exiting the terminal and opening ones own inventory will reveal that the items are there. in some cases the items do seem to drop to the ground, but theses are often phantom items, that disappears ones picked up.

This is not a TPS issue as the TPS have never while the problem was present dropped below 20 TPS. While the AE2 system becomes inoperable, i'm free to break and interact with any another non-AE2 blocks.

Sometimes when order the system for some big crafting recipes or sometimes just at random, the player will disconnect from the (single player) server with an Internal Exception error (java.nio.channels.ClosedChannelException), therefor a crash report is not available, but i will include a link to a part of my latest log, where the disconnect happened.

![image](https://user-images.githubusercontent.com/21788044/40267413-3072805e-5b5c-11e8-842e-134b42c5589e.png)

#### Environment
Latest Log, from me logging in to the world, to me disconnecting.
 - https://pastebin.com/QZu7atRh

Export of my modpack, including my world, where you should stand right in front of the AE2 system. From this you should also be able to see any other mod, with versions, that i use, that you might think could be a culprit for the issue.
- https://drive.google.com/file/d/1Htzq1zA7OTD1Emyt2ch9nA_7Xe7BZ_Kf/view?usp=sharing

Versions:
- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv5-stable-11
- Forge Version: forge-14.23.3.2676

**Comment by mindforger** [comment]
check your me is not running out of power, input is limited to capacity per tick. Use the network tool to check capacity and install some ae energy cells

**Comment by andr9528** [comment]
it is being powered through a dimensional transceiver, which has a 2800 million vibrant capacitor as a battery. On top of this the system has 1 Dense energy cell. The system is using around 6.5k rf/t, and my generation is 15k+

**Comment by andr9528** [comment]
I will add some more energy cells. I have rather many Quantum Bridges (ca 9), one for each Compact Machine, that has some form of ME operation, could that be of any effect?

**Comment by mindforger** [comment]
an improper chunkloading of said QNBs can lead to an constant reevaluation of your network making it inresponsive

@yueh i have an idea, could you check how often a network is reevaluating over a given periode and raise an warning symbol in any UI as an easy to access indication for this repeating kind of issue?

**Comment by andr9528** [comment]
I had forgot to chunkload the chunks wherein the QNB's were, so the hole reevaluating of the network was proably the reason. The thing is, the issue was present while i were at the terminals, and from there the QNB's are only 5-6 chunks away, with my render distance being 10, they should still be loaded. I understand i would be very unhappy when i enter a Compact machine, but should it really mean that entering and then leaving the Compact machine would make the ME system so unstable?

**Comment by andr9528** [comment]
Still unsure of whether or not the disconnect issue has been fixed, but my guess would be yes. my guess of what caused it, would be that it happened when the QNB's unload in the overworld, while the receiving end is still loaded, trying to pull stuff out.

**Comment by andr9528** [comment]
So i can now for sure tell whether or not the disconnected error is gone, which it is not. The delay is almost completely gone, each energy cell i added, seemed to lower the delay.

Changes that have been made since i started the issue:
 - Gone from 1 to 5 Dense Energy Cells on the system
 - Chunk loaded the QNBs

Issues that are still present:
 - Delay when interacting with ME system, tho very little and primary when attempts are made to auto craft something.
 - Disconnects, with the same error as mentioned before, still exist. This has been drastically lowered too tho, going from ca 8 on a day of playing down to 1 or 2.

**Comment by andr9528** [comment]
Could the delay be from Autocrafting orders? At the moment i have my system autocrafting Wood Piles from forestry to turn in to charcoal and creosote, and slimeballs from slimepearls to power Slime generators. On top of this, the things that seems to be delayed the most, is attempt to order a autocraft. My system also passes through a P2P network could this have any effect?

**Comment by mindforger** [comment]
on p2p i don't know, but in your orders, yes! Ae always chooses to use the largest crafting cpu so having all similar sized cpu may help to prevent large requests to wait on silly small automated one. Also use co-processors to enable large recipes to split different tasks that can be done simultan. And finally make sure to distribut heavy used recipes over available machines to not lockup single processing machines

**Comment by andr9528** [comment]
So after some more time playing i think i found the culprit. Excessive amount of items with NBT data, like enchanted weapons, armors, ability totems from everlasting ability. It seems having 1000+ of items with this specification, lag the ME system. if i'm not mistaken AE2 for 1.10.2 didn't have this issue, at least not last time i played that version, so what changed?

**Comment by Pingger** [comment]
My guess would be, that the amount of NBT-Tag content is larger (as in more KiloBytes that need to be transfered over the internet)

**Comment by mindforger** [comment]
totally explains lag and disconnect

**Comment by andr9528** [comment]
I have been noticing my TPS going down slowly recently, not sure if this is still to blame, but my ME system, is the part of my world that is most visibly effected. but the weird part is it is different how low the TPS is depending on what command i use / where i see it.

F3 debug information:
![image](https://user-images.githubusercontent.com/21788044/40854750-ae63e612-65d2-11e8-9106-c4c9a2841401.png)

Command /tps: 
![image](https://user-images.githubusercontent.com/21788044/40854797-d1238aea-65d2-11e8-9444-86ed6f724e5a.png)

Command /forge tps:
![image](https://user-images.githubusercontent.com/21788044/40854835-f4d304d4-65d2-11e8-89d4-7e04d9f63db0.png)

Which one should i trust? the game doesn't fell as bad/laggy as the second one suggests, but it is clearly not at 20 TPS.
Is there any data, like sampler or something else, that i can supply that might indicate where the issue is from / how to minimize its effect.

The biggest amount of NBT items my system can see is my enchanted books which are stored in a large storage drawer bank, connected with a storage bus. Disconnectiong them, has no impact on the delay i fell in the Me system, so i don't think NBT is to blame this time.

Could really use some way to see the rate of input / output of items, redraw of system and other statistical information regarding the ME system, this would help the player to locate any issues, and improve upon their build, as to lower the toll on the world. Could maybe be done with at Statistical Terminal, which could be a terminal, that could shows the data from the network tool and maybe calculate different things, like income/outcome of specific items.

**Comment by andr9528** [comment]
i think i located my TPS problem, i'm using Impulse items duct to route items in my loot bag opener, which seems to be eating around 10 of my TPS.
