### ISSUE TITLE
Java EOFException while joining

### ISSUE THREAD

**Issue by supi1290** [AppliedEnergistics/Applied-Energistics-2#3505]
#### Description
During Inventory Loading when you connect to a Server it can come to an Java EOFException. This can occur if you have too many me storage discs with too many items in your inventory and minecraft cannot load your inventory anymore.

Problem: 
- too much information in an inventory, that the server cannot send to the client

Result:
- player is not able to join the server anymore and if he tries to join the server,
all players who load the joining avatar get the Java EOFException and get kicked from the server

Possible Solutions at the moment:
- clearing the inventory of the affected player which results in losing all items in me storage disks as well as the inventory

**Comment by yueh** [comment]
This is more or less a vanilla feature/bug. There are simply not protections in place to protect a player inventory from overflowing with data. The only option is basically clear the affected player's inventory or maybe try and split it somehow with nbt tools and restore it iteratively.
