### ISSUE TITLE
ME System not using multiple inscribers

### ISSUE THREAD

**Issue by TLangendam** [AppliedEnergistics/Applied-Energistics-2#3506]
#### Description

I currently have a system setup that has multiple inscriber clusters for the 3 different processors, however even though all of them have the same priority, and all of them have max speed upgrades, it still only uses 1 cluster if i request it to craft a multitude of processors. The issue is that it's ineffective if the other clusters that can create the same item are idling.

#### Environment

MP, Modpack called Gigabyte 2. Others on the server have no issues with this problem.
Screenshot: [Link](https://i.imgur.com/Q2sdBBk.jpg), as i said it works, but slow because it's not using multiple clusters. As you can see in the bottom left i have enough co-processors.
I actually have 8 CPU's with 64k storage and 20 Co-Processors each.

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: 14.23.2.2611 (Modloader 8.0.99.99)

**Comment by JelmarG** [comment]
From the screenshot it looks like you're not actually using AE to distribute the materials to the inscribers, but EnderIO conduits. Did you set those conduits to round robin mode?

**Comment by mindforger** [comment]
co-processors only allow for simultaneous production of parallel sub-processes, not splitting processes over multiple interfaces evenly

your best way would be to insert the materials into some sort of buffer, from which you distribute the items over the interfaces, and don't forget to activate round robin like @JelmarG said or item conduits will always choose the closest target with same priority

also i don't see actual AE2 inscribers in your picture, are you using the ones from AE2Stuff Addon? Please be aware those addon mods are not directly supported (means you won'tget help with issues interacting with their stuff) here, so always check if you are in the right tracker :)

**Comment by TLangendam** [comment]
@JelmarG The ender io conduits are just to push the items from the chest into the inscribers, i do use AE to distribute the materials over the different interfaces.

**Comment by TLangendam** [comment]
@JelmarG Yes, exactly the same recipe in each of the interfaces with standard settings. All of the interfaces are connected with the same AE2 pipe/cable.

**Comment by JelmarG** [comment]
That can work, but probably not if your order isn't large enough. If it fits in one of the chests, it probably just dumps everything in that one and leaves it at that. If you want to have more inscribers doing work, you'll probably have to make a subnet that distributes items to all of them or something like that.

**Comment by TLangendam** [comment]
@JelmarG So what you're suggesting is 1 interface per item, then through that chest, connect multiple inscriber clusters? But how would i make sure that the chest will distribute evenly over the inscribers? Because i feel like this will just move the problem i'm having to a later stage in the process.

**Comment by JelmarG** [comment]
@TLangendam EnderIO conduits can do 'round robin' mode, which will distribute everything relatively evenly over all connected inventories.

**Comment by TLangendam** [comment]
@JelmarG Could you enlighten me on where i can find how this 'round robin' mode works? And how to set it up?

**Comment by JelmarG** [comment]
@TLangendam not really something for this message board, but okay, it's fairly simple, you just enable round robin mode on the extract side of the conduit, the conduits will do the rest (i.e. distribute items somewhat evenly over all attached inventories).
