### ISSUE TITLE
EnderIO combined with AE2 and ThermalExpansion

### ISSUE THREAD

**Issue by 5pHiNxX** [AppliedEnergistics/Applied-Energistics-2#3507]
#### Description
EnderIO does not replace all Flour-Items from AppliedEnergistics2. The Pulverizer from ThermalExpansion normally produces AppliedEnergistics2 Flour, but in combination with EnderIO it just produces AppliedEnergistics2 Disabled Item. All other grinders (like SAG-Mill, Grindstone, etc.) produce the EnderIO dustWheat.

#### Environment
Steps to reproduce:
-    Install AppliedEnergistics2, ThermalExpansion and EnderIO
-    Place a Pulverizer, power it and put Wheat in it.
-    AppliedEnergistics2 Disabled Item is produced

Versions
-  EnderIO: 1.12.2-5.0.21
-  EnderCore: 1.12.2-0.5.18
-  Minecraft: 1.12.2
-  Forge: 14.23.3.2655
-   AppliedenErgistics2: rv5-stable-11
-  ThermalExpansion: 1.12.2-5.4.2.25-universal

**Comment by 5pHiNxX** [comment]
Oh never mind... Going to replace AE2 with Refined Storage and ask everyone with similar problems to do so as well... They at least respond to issue posts... And they don't have this and similar problems... Bye bye AE2

**Comment by mindforger** [comment]
No need to become rude just because you are impatient. The devs are doing it for free and don't owe you shit so you are free to not use ae2
