### ISSUE TITLE
Pulling from Inteface using OC Transposer doesn't update item

### ISSUE THREAD

**Issue by mrmakeit** [AppliedEnergistics/Applied-Energistics-2#3508]
#### Description
Attempting to transfer an item present in an ME Interface using the OpenComputers Transposer causes the item to not be restocked inside the interface until the interface's UI is clicked on by a player.

Steps to reproduce:
 - Setup AE2 with interface containing 1 item in the top slot. Ensure there are sufficiant items inside the network
 - Place a OC Transposer next to the interface
 - Place an inventory block next to the Transposer
 - Call `.transferItem()` with appropriate side parameters
 - Check AE interface

Clicking inside the UI of the interface causes the item stack to properly update.

Tested in Single Player including only AE2 and OpenComputers version 1.7.2.67

Log Paste: https://paste.ee/p/yn77J
Last line regarding possible item duplication was created when running the transfer.

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: 14.23.3.2702

Related issue MightyPirates/OpenComputers#2845

**Comment by yueh** [comment]
Can you also forward this issue to OC? We mostly just reuse the helpers provided by forge and I am not aware of any similar isue with something else. Like some pipes extracting from interfaces.

**Comment by mrmakeit** [comment]
Sure thing.

**Comment by fscan** [comment]
I'm closing this, as this seems to be an OC issue.
