### ISSUE TITLE
Inscriber wont accept any press

### ISSUE THREAD

**Issue by Cruorzy** [AppliedEnergistics/Applied-Energistics-2#3512]
Currently playing on the latest direwolf20 pack

When I try to put any press into the inscriber it throw it out in my inventory or on the floor, when I shift click it it puts it in the middle slot.

This is on a multiplayer server, everyone has the problem making a new inscriber or moving it doesn't help

**Comment by mindforger** [comment]
screenshots, modlist, versions of MC, Forge and AE2 ... you are missing a LOT of helpfull informations
