### ISSUE TITLE
Ae2 addon (sorry for that spam issue)

### ISSUE THREAD

**Issue by AAzazell** [AppliedEnergistics/Applied-Energistics-2#3515]
hello, i want to create addon for ae2 that adds energy storage elements like energy import,export,storage buses e.t.c. and i realized that ME drive not support energy storage channel. Could you add storage channel for energy in API class:StorageChannel and Me drive class, for support this mod working? sorry for that spam issue and pull request, i didn't know how to contact you. 

version of ae2 - 1.7.10. i also want to port this addon later to other versions

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.12 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
