### ISSUE TITLE
Game start crash

### ISSUE THREAD

**Issue by shadowslayer111** [AppliedEnergistics/Applied-Energistics-2#3516]
#### Description
When I try and load the game when it gets to the finishig up step than crashes

#### Environment

Other modes used: Advanced capes V 9.0
Advanced solar panels V 4.2
Aroma1997Core V 1.12.2-2.0.0.0.b150
Aroma1997s Dimensional World V 1.12.2-2.0.0.2.b69
BrandonsCore V 1.12-2.4.2.157
Build craft V 7.99.14
Code Chicken Lib V 3.1.8.341
CoHF Core V 4.4.1.12
CoHF World V 1.1.1.12
Cucumber V 1.0.4
Draconic Evolution V 1.12-2.3.11.290
Ender IO V 5.0.20
EnderCore V 1.12.2-0.5.20
Extra Utilities 2 V 1.12-1.7.6
Extreme Reactors V 1.12.2-0.4.5.46
Flans V 5.5.2
Flans apocalypse V 1.0
Hammer core V 1.9..7.0
Industrial Forgoing V 1.12.2-1.5.5-92
Industrial craft 2 V 2.8.80-ex112
Iron Chest V 7.0.40 build 824
Just Enough Items V 4.9.1.168
Mantle V 1.3.1.21
Mystical Agriculture V 1.6.7
Not Enough Items V 2.4.1.233
Redstone Flux V 2.0.1.2
Shadowfact's Forgelin V 1.5.1
Simply Jet Packs 2 V 2.2.5.39
Solar Flux Reborn V 3.50r
Tesla V 1.0.63
Tesla Core Lib V 1.12-1.0.10
Tesla Core Lib Registries V 1.12-1.0.10
Thermal Expansion V 5.4.2.27
Thermal Foundation V 2.4.1.15
Tinkers Construct V 1.12.2-2.9.0.55
Vein miner V 0.38.1
Version Checker 1.3.0
Waila V 1.8.20
Waila Harvestability V 1.1.11
Xaero's Minimap V 1.15.1.2
Zero Core V 1.12-0.1.1.0
Crash report: https://pastebin.com/Nyg47byV

- Minecraft Version: 1.12.2
- AE2 Version: R5 11
- Forge Version: 14.23.3.2664

**Comment by mindforger** [comment]
check your log and configs, you have another mod, using the same dimension 2 like ae2.

**Comment by shadowslayer111** [comment]
Ok thanks for the help
