### ISSUE TITLE
Game crashes at launch: Unknown item 'appliedenergistics2:certus_quartz_cutting_knife'

### ISSUE THREAD

**Issue by Isaac-SOL** [AppliedEnergistics/Applied-Energistics-2#3518]
#### Description

When launching the game, at forge loading step 4, the game crashes. My issue seems identical to [this one](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2990). However, the game launched fine at first, until yesterday, when it started crashing at launch for seemingly no reason.
I haven't changed anything in the minecraft folder besides some lines in a crafttweaker script, unrelated to AE2 (reverting these changes didn't help). I have no idea which json file this is referring to.

#### Environment

Mods installed:
forge-1.12.2-14.23.3.2655
AkashicTome-1.2-10
appliedenergistics2-rv5-stable-11
Baubles-1.12-1.5.2
CraftTweaker2-1.12-4.1.8
astralsorcery-1.12.2-1.8.9
MTLib-3.0.4
modtweaker-4.0.12
jei_1.12.2-4.9.1.168
RedstoneFlux-1.12-2.0.1.2-universal
CoFHCore-1.12.2-4.4.1.12-universal
ThermalFoundation-1.12.2-2.4.1.15-universal
ImmersiveEngineering-0.12-81
CodeChickenLib-1.12.2-3.1.7.340-universa
ThermalExpansion-1.12.2-5.4.2.27-universal
BetterWithMods-1.12-2.1.12
Quark-r1.4-123
AutoRegLib-1.3-17
BetterTitleScreen-1.12.2-1.4b
Thaumcraft-1.12.2-6.1.BETA14
Botania+r1.10-354
Chameleon-1.12-4.1.3
ChickenChunks-1.12.2-2.4.1.71-universal
CoFHWorld-1.12.2-1.1.1.12-universal
CraftTweaker2-1.12-4.1.8
embers-0.230.jar
EnderCore-1.12.2-0.5.20
EnderIO-1.12.2-5.0.22
Hwyla-1.8.24-B39_1.12
iChunUtil-1.12.2-7.1.4
InventoryTweaks-1.63
ironchest-1.12.2-7.0.40.824
OpenModsLib-1.12.2-0.11.5
OpenBlocks-1.12.2-1.7.6
OpenComputers-MC1.12.2-1.7.2.67
OpenGlasses-MC1.12.2-1.5.5
PortalGun-1.12.2-7.0.2
ReAuth-3.5.2
secretroomsmod-1.12.2-5.6.3
ThermalDynamics-1.12.2-2.4.1.10-universal
ThermalInnovation-1.12.2-0.2.1.6-universa

Crashlog: https://pastebin.com/VdXa7e0Q

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: 2655

**Comment by mindforger** [comment]
What the heck is craftinghelper.jar?

**Comment by Isaac-SOL** [comment]
Ok, I have found the source of the issue: I forgot I had disabled the certus quartz tools, which also disabled the certus quartz cutting knife. Setting it back to "true" solved the issue.
However that means disabling the certus quartz tools is currently not possible.

**Comment by mightydanp** [comment]
is there a possibility to make an if statement if certes quirts tools are enabled then you can make it false or true if certus quartz tools is false then they are all false
