### ISSUE TITLE
Server Tick Loop Crash

### ISSUE THREAD

**Issue by Jo-Mamma75** [AppliedEnergistics/Applied-Energistics-2#3522]
#### Description
FoolCraft 3 Server crashing randomly with the following crash log [https://pastebin.com/YBDRVnZW](url)
Seems to be similar to Issues #3150 & #3157 but we are using the latest stable version of the mod.

Initially it seemed to be caused by one particular person's AE2 system but we made adjustments to it by loading the world in SP and changing some items around.  Uploaded the region file back to the server and all seemed fine.  However, the server continues to crash at random intervals even while the player who's system caused the initial problem is logged on for a while.

Can't really determine where the offending block(s) is/are located in order to troubleshoot based upon the information in the crash log.  Any suggestions other than manually inspecting each AE2 system on the server that may be chunkloaded?

#### Environment
FoolCraft 3 v1.0.0 (was planning on updating server to v1.1.1 this evening but AE2 is not changed in this version of the pack)

#### Version Info
- Minecraft Version:  1.12.2
- AE2 Version:  rv5-stable-11
- Forge Version:  2673

**Comment by leagris** [comment]
:-1: `ae2stuff-0.7.0.4-mc1.12.2.jar`

**Comment by Jo-Mamma75** [comment]
You think that's the cause of the problem @leagris or you just don't like the mod?

**Comment by Jo-Mamma75** [comment]
Update:
Still getting the crash on our server.  I've downloaded that region file again and packed up all AE2 related items as well as AE2 Stuff related items into a chest.  Uploaded the region file back to the server and still get the crash when I log on at that location.
Thoughts?

**Comment by leagris** [comment]
Try without it and without any AE2 add-ons.
