### ISSUE TITLE
[Request] Auto-Hide Facades

### ISSUE THREAD

**Issue by Sanofus** [AppliedEnergistics/Applied-Energistics-2#3523]
I'm not sure if this is a bug or not but it might be very important because AE2 facades have a much amount and fill JEI. That is very annyoing if you look up a thing and three pages are just facades. Maybe this could be changed like Thermal Dynamics does to avoid flooding screen with facades.

**Comment by yueh** [comment]
Which would lead to this #3172

**Comment by Sanofus** [comment]
There is no option to turn facades off anymore. JEI displays them and I don't want them to displayed. And they already hit the 300 hundred limit. My idea was to add a config to turn them off if they are not wished.

**Comment by Ommina** [comment]
While I do have a vague memory of JEI removing the auto-hide feature (that confused many), I'm quite certain that the per-user Item Hiding Mode still exists.  Can this not be used to achieve the same effect you are seeking here?

**Comment by Sanofus** [comment]
Well, I'm working on a modpack and I do not want to select every single block. I think it is only necessary to have on example recipe. JEI should allow that. It is not necessary to view every facade recipe. 

EnderIO do not show all facades. Thermal Dynamics do not show all facades. I requested the same to Buildcraft and they added this to the compat list. 

The only thing that spams JEI are the AE2 facades and I need a sulotion for that.

**Comment by A-T-L-A-S** [comment]
There is a blacklist for items. I just don't understand how it works.
