### ISSUE TITLE
 unload and load chunks causing bad performance 

### ISSUE THREAD

**Issue by JoeSGT** [AppliedEnergistics/Applied-Energistics-2#3524]
#### Environment

So my server chunks are unload and load simultaneously and it's degrading performance 
https://pastebin.com/raw/JFjHinLg i am unsure how to fix this please help greatly appreciate it and your time thanks you.
EDIT: i do not have any chunk loaders on the server they are banned from use so i know it's not a chunk loader.
- Minecraft Version:  1.12.2
- AE2 Version: appliedenergistics2-rv5-stable-11
- Forge Version: 1.12.2-14.23.3.2690

**Comment by yueh** [comment]
This is expected behaviour when banning chunk loaders. 

Also in this context TE access their associated block when ticking, thus if this causes a chunk load there is something seriously broken in sponge when they tick unloaded chunks.

**Comment by Dockter** [comment]
You can't tick an unloaded chunk....

**Comment by Ommina** [comment]
While I totally agree the chunk-loader ban is silly (didn't we just have this very issue a couple days ago?) this doesn't appear to be a case of a TE accessing its own block, but accessing an adjacent TE (via pos.offset) and subsequently loading _that_ chunk; presumably the molecular assembler is sitting on a chunk boundary.

I'll remain quiet on whether this is an actual issue or not.

**Comment by Pingger** [comment]
Maybe adding a warning, that ME Systems, spread over several chunks, can run into issues, when not properly chunkloaded, could be useful?

**Comment by mindforger** [comment]
@yueh you did not answer to my proposed idea with the indication of unusual high network reloads in the GUIs on the other issue
