### ISSUE TITLE
Inscriber issue

### ISSUE THREAD

**Issue by mukzon** [AppliedEnergistics/Applied-Energistics-2#3526]
Modpack: Sevtech Ages Server 3.07

Inscriber slot didn't work as expected.
for example.
- Inscriber Logic Press won't go to the top slot. If you force it by dragging the logic and put on the top slot it just drops the logic press on the ground. And if you tried shift clicking, it goes to the middle slot.

- Printed Engineering Circuit won't go to the top slot. and goes to middle slot only (same problem like inscriber logic press)

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: 14.23.3.2679

**Comment by yueh** [comment]
Please report it to your modpack author. Especially these heavily modded packs can change recipes in unexpected ways up to simply broken configs for them.
