### ISSUE TITLE
Cannot have two patterns to make ingots

### ISSUE THREAD

**Issue by TH3GOD88** [AppliedEnergistics/Applied-Energistics-2#3527]
If I have two or more furnaces with interfaces with the same recipe, it will not split the quantity of the material, it just tries to use one or the other.  This is with using the flat interfaces or having one interface between two furnaces. If you need more info, I will be glad to respond with more.

It's my own server running on another computer. Everything is the same on both as in Java and Windows versions.

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: Any/At the moment I went from 14.23.3.2697 to 14.23.4.2705

**Comment by yueh** [comment]
#3402
