### ISSUE TITLE
Crafting recipe with Priority

### ISSUE THREAD

**Issue by 4Source** [AppliedEnergistics/Applied-Energistics-2#3528]
Why is there not a way to prioritize a crafting recipe while creating? It would be quite useful if there are different crafting recipes for an item. So can a recipe be considered as a prioritized solution if this recipe is not possible because non-craftable / missing items are used then the recipe with the next higher priority will be used and so on.

**Comment by yueh** [comment]
Because complexity and there are other issues, you could search for more detailed information about it.
