### ISSUE TITLE
Crafting Lag/Console Spam when Crafting Mekanism Items (Cables / Induction Cells / Induction Providers)

### ISSUE THREAD

**Issue by Vyraal1** [AppliedEnergistics/Applied-Energistics-2#3531]
#### Description
Mekanism features a lot of nested crafting recipes (eg. to craft next tier of cables from Advanced Tier to Ultimate Tier, you need to craft 8 of Advanced Tier Cables with some alloys into 8 Ultimate Tier Cables).
![image](https://user-images.githubusercontent.com/26587049/41043435-ef1e3ebc-6971-11e8-9410-b8f1b4833146.png)
These items have the same resource ID and and metadata, and only really differentiated by NBT.

Whenever I order a stack or so of any of these nested crafting recipes (only happens with Mekanism, though I don't know of any other mod that heavily uses NBT to differentiate all of its blocks instead of metadata), I get the following console spam https://hastebin.com/mewecusexi.pl as well as a slowndown in my ME system's autocrafting. It seems as if it's trying to use other inputs and getting rejections? Not sure really.

A sample pattern looks like this:
![image](https://user-images.githubusercontent.com/26587049/41043369-cbd3cb3e-6971-11e8-9699-ad79db181981.png)

Another pattern for the ultimate cables, hard to see the color but those are elite cables in the left crafting grid - 
![image](https://user-images.githubusercontent.com/26587049/41043595-45872890-6972-11e8-851d-3843cbf7a8ce.png)

#### Environment
**AE2 Version:** rv5-stable-11
**Server Play:** hosted by SYS (OVH Canada), I'm the only person on the server
**Minecraft Version**: 1.12.2
**Modpack:** Enigmatica 2 Expert, v1.26c
**Forge Version:** 2705

**Comment by Pingger** [comment]
my guess would be, that the 'ore substitutions' are causing this issue. Try to disable it on these patterns

**Comment by yueh** [comment]
Yes, due mekanism's approach to stick everything into a few ids even without metadata and just use NBT, it makes it virtually impossible to do select the actually matching item for a recipe without trying every other item first and then failing it. So nothing we can actually do, except logging these cumbersome recipes for visibility.

The only solution would be for mekanism to change how they identify items and assign every item a unique it. Which is probably impossible for them currently and has to wait to for a 1.13 release, which will also be the suggested approach by minecraft itself. If they even consider it.

**Comment by Vyraal1** [comment]
All right thanks, I can assume this is also the default result for other recipes that rely heavily on NBT (eg. generators from Extra Utilities 2, cables from IC2)?

I guess best practice policy would be to tell players to turn off substitutions for any recipes that rely on ingredients differentiated by NBT data.
