### ISSUE TITLE
Annihilation plane not able to store items to main network with a security terminal

### ISSUE THREAD

**Issue by bramhut** [AppliedEnergistics/Applied-Energistics-2#3532]
**Description**

When there is a security terminal connected to the main network, an annihilation plane, connected to a sub system, can no longer store its items via a storage bus + interface in the main network.
I have tested it in SP & MP, in both cases the problem occurs.

I am also using the Wireless Crafting Terminal mod (3.9.64).

Am I overlooking something or is it a bug?

_**EDIT:**_
Placing a blank biometric card with full access solved the issue. Is this intended behaviour?

**Version info**
- Minecraft: 1.12.2
- Forge: 14.23.4.2705
- AE: rv5-stable-11

**Comment by yueh** [comment]
> Placing a blank biometric card with full access solved the issue. Is this intended behaviour?

Yes, this is also commonly suggested in other tickets here.
