### ISSUE TITLE
Can't take off and put in items in ME

### ISSUE THREAD

**Issue by kave777** [AppliedEnergistics/Applied-Energistics-2#3533]
#### Description

I changed the option "B:Channels=true" to "B:Channels=false" . After launching my world ME Controller disappeared and dense cables too ( it is normal , I think ) . I connected all the stuff and now I can't   take off and put in items in ME . 
#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: 14.23.4.2703

**Comment by kave777** [comment]
I have connected this through the energy accepter to my generator , it produces enough power , I am absolutely shure

**Comment by kave777** [comment]
I will try to add an energy cell

**Comment by mindforger** [comment]
also, as we don't know the size of the system, make sure it is chunkloaded (but this shouldn't be an issue since it worked before)

**Comment by kave777** [comment]
it works , thank you
