### ISSUE TITLE
Performance issue from appeng.hooks.TickHandler.onTick()

### ISSUE THREAD

**Issue by JoeSGT** [AppliedEnergistics/Applied-Energistics-2#3536]
#### Description

I am unsure about this issue because it is happening to random i would love to know what are your thought on this. 

EDIT: i know part of the lag is happening on ExtraU. mod i had also made a github issue on their as well
[WarmRoastReport.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/2103566/WarmRoastReport.zip)
![8b38961b7077ad905cf80dceecf1026a](https://user-images.githubusercontent.com/30296350/41430867-34ead766-6fdf-11e8-8c97-6a2384007046.png)

#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: 1.12.2-14.23.4.2705

**Comment by yueh** [comment]
This is a chunk loading issue and in general we don't support sponge.
