### ISSUE TITLE
Item Exporting methods are unknown (taking items out of system into chests automatically)

### ISSUE THREAD

**Issue by AwesomeDragon10** [AppliedEnergistics/Applied-Energistics-2#3537]
#### Description
1.12.2
After a while of having the applied energetics mod ways of moving items right out of the system, into chests dose not seem possible. There really should be a way for a player to export items into temporary storage so they can clean out the memory cells to upgrade the storage to the next level easier

#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv5-stable-11
- Forge Version: 1.12.2-14.23.4.2705

**Comment by yueh** [comment]
[IO Port](http://ae-mod.info/ME-IO-Port/)
