### ISSUE TITLE
Repost request

### ISSUE THREAD

**Issue by Mycrafte** [AppliedEnergistics/Applied-Energistics-2#3538]
I am a player who came from china,and i love ur mod very much!
Its easy for me to download ur lovely mod cuz i have VPN,but because of the GFW,most of us cannot download ur mod or visit curseforge.
So i find a new way to "rescue" them!
This is a website [www.mcmod.cn] created by chinese Minecrafter, its a chinese ModWiki,I want to repost ur mod to this website.
Of course,i will mention ur name and url,we wont use this mod to earn any money,wo will keep ur mod original.
Hope you can agree!

**Comment by yueh** [comment]
Please refer to the license for the requests.

**Comment by Mycrafte** [comment]
Im so sorry about that but i cannot open the license .I can only start an issue ....sorry abou that.But..Is AE2 using LGPL?

**Comment by mindforger** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv5-1.12/LICENSE

Why can't you open it?

**Comment by Mycrafte** [comment]
I dont know,but i think it was GFT to blame.

**Comment by yueh** [comment]
The website hosts different versions of AE2 and some are still covered by the old license and noone here can give you a permission for these versions. Otherwise MIT/LGPL/CC BY-SA-NC applies to the source/textures/etc.

**Comment by fscan** [comment]
To sum it up, for older versions (up to rv2 i think) you will need permission from AlgorithmX2. Newer versions fall under LGPL and you are basically free to redistribute.
