### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by meitangdehulu** [AppliedEnergistics/Applied-Energistics-2#3541]
First of all, I'm very sorry, because I didn't know how to get in touch with you, I got this Issue.
I hope I can repost it in a Chinese BBS which is called MCBBS,to promote it to more Chinese players.
I will conduct localization and promotion of module introduction within the license of LGPLv3.
I will not use this as a profit, I will keep everything you ask, such as the author's name or other.
Can I reprint your mod to another Chinese forum?
Due to network problems,can I create a Download link of China?
Looking forward to hearing from you.

**Comment by yueh** [comment]
#3538

**Comment by Mycrafte** [comment]
老哥咱俩好像来错地方了

**Comment by meitangdehulu** [comment]
@yueh 
This does not solve my problem, mcmod is similar to the existence of a wiki, mcbbs is a player forum, the forum has curse-like sections.
What I need is the permission of the agree or disagree.
I want to know if the current author can give me the current partial authorization of his development part.

**Comment by Pingger** [comment]
This source code is licensed under the LGPLv3, which allows you to even commercially redistribute it, as long as you provide the LICENSE and copyright notice.

Here is a link for GPLv3: https://choosealicense.com/licenses/gpl-3.0/
the LGPLv3 has some minor changes: https://stackoverflow.com/questions/1114045/gpl-and-lgpl-open-source-licensing-restrictions

Please note, that the compiled versions under ae-mod.info may not be used to redistribute this project. (Which BTW violates the LGPL ...)

**Comment by meitangdehulu** [comment]
@Pingger 
Thank you for your reply.
If I need authorization for content on ae-mod.info, who do I need to contact and get authorization?

**Comment by Pingger** [comment]
According to the copyright notice that would be AlgorithmX2
