### ISSUE TITLE
Security terminal lockout

### ISSUE THREAD

**Issue by x1R1SHN1NJAx** [AppliedEnergistics/Applied-Energistics-2#3547]
im using all the mods 3 on a server, current version of ae2 Rv5-stable-11. i have channels turned off
 
for some reason it locks me out of my ae system, i am the one who placed the entire system and the security terminal. only fix i can find is breaking it powering down the ae system then restarting it an making a new security terminal. 

as soon as i log off of the server it just repeats itself.

**Comment by mindforger** [comment]
make sure of the following:

1. everything is chunkloaded
2. enough power input
3. enough ae energycells installed (input is limited to system capacity)

you are probably suffering from 1. when you have parts of the ME unloading they may not reconnect, throwing off your whole Me system (this may also cause a lot of lag)

your informations are lacking any informations to recreate this issue, please add minecraft version used, forge version used and a modlist next time
