### ISSUE TITLE
ME Export/Import Bus dont work

### ISSUE THREAD

**Issue by Down16IQ** [AppliedEnergistics/Applied-Energistics-2#3551]
I tried to automate ore processing, but when I put export and import bus, they did nothing. They are online (Device online), items I filtered out were not supplied, but they are in the system. What I have to do? Maybe this is an error in my minecraft?

**Comment by mindforger** [comment]
You provided absolutely no info to support your case, Mc Version, forge, ae2, modlist, etc.

Will reopen when you provide enough data to reproduce your issue
