### ISSUE TITLE
Optimize storage cells

### ISSUE THREAD

**Issue by fscan** [AppliedEnergistics/Applied-Energistics-2#3553]
Currently, storage cells serialise to NBT on every inventory operation. Change the system to make serialisation the responsibility of the TE containing the cell so it can be better optimised.

Needs API changes.

**Comment by yueh** [comment]
Most certainly will also require addons to potentially change any custom drive to behave differently and not fix some compile errors. E.g. They now need to take care of explicitly saving to disk on the cell being removed, the block destroyed etc. (Also applies to our own drives)

**Comment by fscan** [comment]
Sure .. i think for most TE's it makes sense to emulate the current behavior, eg: call saveChanges after every inject or extract.
The only real performance bottleneck are drives and maybe chests.
