### ISSUE TITLE
AE2 in 1.13?

### ISSUE THREAD

**Issue by awurster1** [AppliedEnergistics/Applied-Energistics-2#3557]
#### Description
Considering the most recent version of AE2 is rv5.stable build 11

#### Environment
The environment being used is a single player, creative environment.
When will AE2 be built for Minecraft version 1.13?

- Minecraft Version: 1.13
- AE2 Version: rv5.stable build 11
- Forge Version: 14.23.4.2709

**Comment by fscan** [comment]
Considering that there isn't even a confirmed release date for 1.13 this seems like an odd question.
All i can say is that we definitely plan to do a 1.13 release at some point.
