### ISSUE TITLE
can't create quantum entangled singularity 

### ISSUE THREAD

**Issue by xXDarkNovaXx** [AppliedEnergistics/Applied-Energistics-2#3559]
#### Environment

- Minecraft Version: 1.7.0.10
- AE2 Version: rv3 Beta 6
- Forge Version: 10.13.4.1614
- Thermal Foundation: 1.2.6-118

I tried to create a quantum entangled singularity and somehow it does not seem to work properly
I threw a singularity and Enderium dust into a hole and then added a TNT block and then detonated the TNT, but when it explodes, the Enderium disappears, but the singularity is still there

What we noticed is that in the Ore Dictionary entry in the Applied Energistics Mod still dustEnder stands but in Thermal Foundation its now dustEnderium.

But we also changed the entry in Applied Energistics from dustEnder to dustEnderium but it did not work because then all things disappear.

**Comment by fscan** [comment]
The singularity requires ENDER dust not ENDERIUM dust.

**Comment by xXDarkNovaXx** [comment]
there is no ender dust in thermal fundation anymore
Ender dust was renamed to Enderium Dust

**Comment by Pingger** [comment]
no
There is ender dust! put an ender pearl into the APPLIED ENERGISTICS Grinder and Grind it! Don't forget the hand crank to grind!

**Comment by Pingger** [comment]
Enderium is something entirely different from ender!

**Comment by xXDarkNovaXx** [comment]
I have the Ender Pear in the Grinder and become from the Grinder a Dust from Ender IO
But I will try it
Applied Energistics does not have its own ender dust

**Comment by fscan** [comment]
https://ae-mod.info/Ender-Dust/

**Comment by xXDarkNovaXx** [comment]
The Dust is not in the NEI or Creative Menu
The Dust say he is from Ender IO but Ender IO have not Ender Dust
Screenshot: http://prntscr.com/jy7lzz
sry the Text on the Screenshot is German

**Comment by fscan** [comment]
To avoid recipe conflicts the old AE2 removed it's own recipes if it detected another mod is providing it. EnderIO's ender pearl powder should work too.

**Comment by Pingger** [comment]
You might want to take a look at this:
https://github.com/SleepyTrousers/EnderIO/blob/master/enderio-base/src/main/java/crazypants/enderio/base/material/material/Material.java
Line 53 states the following
`POWDER_ENDER("powder_ender", "nuggetEnderpearl"), // "nugget" because it is 1/9th pearl`

which is the Ender Dust that EnderIO "doesn't have" 

But the EnderIO Ender Dust (or Powder) should work. 


PS: And the image of the _not_ added item https://github.com/SleepyTrousers/EnderIO/blob/master/enderio-base/src/main/resources/assets/enderio/textures/items/item_material_powder_ender.png

**Comment by xXDarkNovaXx** [comment]
So you can say Applied Energistics then uses the Ender dust that there is not even more gives I understand that correctly?
Because the Ender dust from Ender IO you only get through the quartz mill and nowhere else

**Comment by Pingger** [comment]
> So you can say Applied Energistics then uses the Ender dust that there is not even more gives I understand that correctly?
What?! This sentence makes no sense at all ...
