### ISSUE TITLE
Energy Cells charge to 99.98%

### ISSUE THREAD

**Issue by ShadwDrgn** [AppliedEnergistics/Applied-Energistics-2#3565]
#### Description
When placing an Energy cell against a smart cable or other device on the ME network it charges to 99.98%. In order to get it to change to 100% you have to pick it up with a wrench then place it back down again. It will then charge to 100%.

Expected behaviour:
Place energy cell down. It charges to 100%.

#### Environment
Network is being charged by RFTools powercell going into ME Controller.

- Minecraft Version: 1.12.2
- AE2 Version: rv5 stable 11
- Forge Version: 2705

**Comment by yueh** [comment]
Cannot reproduce. Also keep in mind that cells are accessed randomly and this cell might simply be the one powering the whole network after it was fully filled, so it will always be missing some charge until it is no longer the first one (e.g. picking it up and placing it down again.)

**Comment by ShadwDrgn** [comment]
A network with nothing but 4 accelerators an energy acceptor and a creative power cell.

There are no energy cells on the network. I place one down next to an existing smart cable. There's now one on the network. It powers to 99.98%. I pick it back up.  Back to zero on the network. I place it back down. It's now the only one on the network again. It charges to 100%. This is a network with nothing but accelerators on it. If it's using the power from the cell sometimes but not others, that's fine. It just seems odd that it's so inconsistent. It only sometimes uses the cell and therefore can't power it. It's not really a big deal to me, but this is definitely inconsistent behavior. If you don't consider it a bug, that's fine.

**Comment by fscan** [comment]
Maybe it would help if you post a screenshot. The problem is that we cannot reproduce it on our side.
