### ISSUE TITLE
Connect ME Cables to Compact Machine

### ISSUE THREAD

**Issue by lyzio** [AppliedEnergistics/Applied-Energistics-2#3566]
As people seems to been able to use Compact Machines for AE i would guess there is a compatibility between the mods. Though i am not able to connect the cables to the machines on either side so that I can use the ME network within a machine. 

#### Description

- Minecraft Version:  1.12
- AE2 Version:  Rv5-Stable-11
- Forge Version: 14.23.4.2709

**Comment by mindforger** [comment]
as an expensive workaround, you could use a quantum link chamber to access the inside, but the size of the QNB would defeat the use of the compact macine in the first place :P 

if you have an issue on thei git, please link it here that helps a lot

**Comment by yueh** [comment]
Compact Machines dropped AE2 support after 1.10 or so.

**Comment by ruifung** [comment]
I made a small minimod that proxies the AE2 connections through a capability. See ME Capability Adapter on curse.

Also, will AE2 adopt capabilities for it's connections? Or will interfaces still be the main way?
Because compact machines basically proxies any kind of capabilities based connections.
