### ISSUE TITLE
Took out Security Card from active Terminal, kicked me from server, can no longer join 

### ISSUE THREAD

**Issue by Pasmans23** [AppliedEnergistics/Applied-Energistics-2#3574]
Hey,

So me and my friends have been playing on a server I set up (and run) using Forge (10.13.4.1614), with a modpack I made. Because of the mods I wanted, I decided to use the Minecraft 1.7.10 version, and the latest compatible AE2 version, rv3-Beta-6 (released on curseforge.com on April 27, 2016). After many hours of fun, in which AE2 has been indispensable, while I was playing alone, I accidentally opened the Security Terminal one of my friends had put down (he knows what he's doing so he's in charge of the ME network), I stupidly took out my security card, on which he had given me all privileges so if we got stuck, we didn't need him to come online and fix it. Because I no longer had access to the Terminal, I of course got kicked out of the UI, however, somehow it also kicked me from the server, with the message "Internal server error". Trying to reconnect works, but as soon as I join the server I'm kicked out again, now with the message "Internal Exception: Java.io.IOException: An existing connection was forcibly closed by the remote host."

There has not been any problems before (not game breaking ones at least), and my brother (who usually doesn't play on our server) is still able to join, so I'm guessing the other mods, Java, firewalls, etc are all fine. Could it be that removing that security card somewhere changed something in my personal client, automatically logging me out, and if so, what can be done?

Thanks in advance

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.12 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
