### ISSUE TITLE
Can't auto-craft Crafting Tables

### ISSUE THREAD

**Issue by Nico8400** [AppliedEnergistics/Applied-Energistics-2#3575]
- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: ModId 'forge' Version 14.23.4.2705

Applied just won't craft things that have a crafting table somewhere in the craft. When clicking "next" nothing happen and the screen stay the same without crashing. Tested on Crafting table and Molecular Assembler.
I can autocraft ME interfaces that are in the same interface than the Molecular assembler/crafting table pattern.
edit: Having crafting tables in stock won't solve the problem.
![2018-06-29_16 38 48](https://user-images.githubusercontent.com/17343779/42098503-64b01e24-7bbb-11e8-9ca6-96c4d069854a.png)
![2018-06-29_16 39 36](https://user-images.githubusercontent.com/17343779/42098504-64da9f64-7bbb-11e8-8ada-d53f6a39f2c9.png)

**Comment by yueh** [comment]
Cannot reproduce. Crafting them works fine in a test environment.

**Comment by Nico8400** [comment]
Original environment
![2018-06-30_11 45 55](https://user-images.githubusercontent.com/17343779/42124019-1da5561a-7c5c-11e8-9f5b-6a8f0f517308.png)
![2018-06-30_11 46 10](https://user-images.githubusercontent.com/17343779/42124020-1dc41352-7c5c-11e8-97da-afc600e034a1.png)
![2018-06-30_11 46 16](https://user-images.githubusercontent.com/17343779/42124021-1de24c14-7c5c-11e8-8a19-a326449f2f6f.png)
Test environment in the same world
![2018-06-30_11 50 44](https://user-images.githubusercontent.com/17343779/42124022-1dff3662-7c5c-11e8-9290-c47d42a715eb.png)
![2018-06-30_11 50 48](https://user-images.githubusercontent.com/17343779/42124023-1e1c437e-7c5c-11e8-8677-3efdfd7bcb34.png)
I was able to autocraft crafting table in another save.
Here is a link to the save since it's too big for Github.
https://drive.google.com/open?id=1zTuBOED0X2YBReWxMmUqEx-f0iWgCMzq
Modpack is FTB Continuum.
Config file
[AppliedEnergistics2.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/2151602/AppliedEnergistics2.zip)

**Comment by GuntherDW** [comment]
I haven't checked out the save, but does something show up in the log when you click "start"?

The modpack has quite extensive changes towards recipes. Do you have them set to "allow substitutions"?
If you do, try turning  that off for this recipe. Some recipes are bugged and can cause issues like this.

**Comment by Nico8400** [comment]
Ok so I'm back, I re-opened my world and I was able to request crafting tables, so I "Saved and quit to title" and re-opened my wolrd but wasn't able to request crafting tables again and this appeared in the log.

> 

15:34:42 | FML | Server thread | error | Exception caught during firing event net.minecraftforge.fml.common.gameevent.PlayerEvent$ItemCraftedEvent@1672d4d: java.lang.ArrayIndexOutOfBoundsException: 0 	at net.minecraft.server.MinecraftServer.func_191949_aK(MinecraftServer.java:1415) 	at slimeknights.tconstruct.shared.AchievementEvents.grantAdvancement(AchievementEvents.java:57) 	at slimeknights.tconstruct.shared.AchievementEvents.onCraft(AchievementEvents.java:33) 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1380_AchievementEvents_onCraft_ItemCraftedEvent.invoke(.dynamic) 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) 	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerCraftingEvent(FMLCommonHandler.java:594) 	at appeng.crafting.CraftingTreeProcess.<init>(CraftingTreeProcess.java:80) 	at appeng.crafting.CraftingTreeNode.<init>(CraftingTreeNode.java:86) 	at appeng.crafting.CraftingJob.getCraftingTree(CraftingJob.java:98) 	at appeng.crafting.CraftingJob.<init>(CraftingJob.java:92) 	at appeng.me.cache.CraftingGridCache.beginCraftingJob(CraftingGridCache.java:515) 	at appeng.core.sync.packets.PacketCraftRequest.serverPacketData(PacketCraftRequest.java:100) 	at appeng.core.sync.network.AppEngServerPacketHandler$1.call(AppEngServerPacketHandler.java:57) 	at appeng.core.sync.AppEngPacket.func_148833_a(AppEngPacket.java:128) 	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at net.minecraft.util.Util.func_181617_a(SourceFile:46) 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) 	at java.lang.Thread.run(Thread.java:745)
-- | -- | -- | -- | --
15:34:42 | FML | Server thread | error | Index: 7 Listeners:
15:34:42 | FML | Server thread | error | 0: NORMAL
15:34:42 | FML | Server thread | error | 1: ASM: crafttweaker.mc1120.events.CommonEventHandler@7162c3fe onPlayerItemCrafted(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
15:34:42 | FML | Server thread | error | 2: ASM: com.rwtema.extrautils2.crafting.PlayerSpecificCrafting$EventHandler@543d9c61 onCraft(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
15:34:42 | FML | Server thread | error | 3: ASM: com.rwtema.extrautils2.crafting.PlayerSpecificCrafting$EventHandler@47b51c81 onCraft(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
15:34:42 | FML | Server thread | error | 4: ASM: bq_standard.handlers.EventHandler@375d06ac onItemCrafted(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
15:34:42 | FML | Server thread | error | 5: ASM: de.ellpeck.actuallyadditions.mod.event.CommonEvents@345a5733 onCraftedEvent(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
15:34:42 | FML | Server thread | error | 6: ASM: reborncore.shields.RebornCoreShields@755f41ce craft(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
15:34:42 | FML | Server thread | error | 7: ASM: slimeknights.tconstruct.shared.AchievementEvents@619f4929 onCraft(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
15:34:42 | FML | Server thread | error | 8: ASM: tonius.simplyjetpacks.crafting.PlatingReturnHandler@5990d8c5 onItemCrafted(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
15:34:42 | FML | Server thread | error | 9: ASM: vswe.stevescarts.handlers.EventHandler@63d84e86 onCrafting(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
15:34:42 | FML | Server thread | error | 10: ASM: zmaster587.advancedRocketry.event.PlanetEventHandler@1d59eb05 onCrafting(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
15:34:42 | FML | Server thread | error | 11: ASM: com.rwtema.extrautils2.items.ItemUnstableIngots@409911ee onPlayerEvent(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent;)V

**Comment by Pingger** [comment]
@Nico8400 please! Pastebin or something similar!

**Comment by yueh** [comment]
This is tinkers construct crashing, because there is something seriously wrong with your modpack. The only option we can recommend is to start removing mods until you find the one causing the crash and then report it to this particular mod.

**Comment by Pingger** [comment]
My guess: You autocrafted a TC item with AppliedEnergistcs, and TC tried to give an achievment for this, but couldn't handle, that the item wasn't crafted by player

**Comment by Bizuex** [comment]
I have the same issue. Can't autocraft craft tables. Molecular assembles didn't work at first (craft table in recipe), but started working afterwards. Have no clue what it is.

**Comment by forkinme** [comment]
Same crash here, using Enigmatica 2 Expert modpack (other reporters are in other modpacks). The crash shows up after a long time playing, saving/restarting the world fixes it for a while again. That makes it a bear to recreate.

The crash makes it seem that it's an interaction between AE2 (the initiator) and TC (the crasher).
But AE2 dev says it's not AE2 https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3575#issuecomment-401609772
And TC dev says it's not TC https://github.com/DarkPacks/SevTech-Ages/issues/3161#issuecomment-410805743

So...not sure where to go looking :)

**Comment by jk1895** [comment]
I had the same bug suddenly and I had to remove Tinkers Construct from the modpack (Stoneblock) to fix this.

It's a shame that developers on both sides won't fix this nasty bug.

**Comment by KnightMiner** [comment]
Hello, Tinkers Construct dev here from SlimeKnights/TinkersConstruct#3546, can an AE2 dev shed more light on this issue? We already have a null check in place for the player, is there something else from [this line](https://github.com/SlimeKnights/TinkersConstruct/blob/1.12/src/main/java/slimeknights/tconstruct/shared/AchievementEvents.java#L57) that AE does not include in their FakePlayer implementation?

**Comment by temp1029** [comment]
FYI, for anyone experiencing this issue, if you do a processing pattering into something like an RFTools crafter the issue does not occur. Maybe that's common sense, but I had to test it and it worked.
