### ISSUE TITLE
crash report 

### ISSUE THREAD

**Issue by JoeSGT** [AppliedEnergistics/Applied-Energistics-2#3577]
#### Description

Hello i am having an crash ill post the crash report here i am unable to figure what is the cause of the crash
https://pastebin.com/raw/U54s9gxi

#### Environment

- Minecraft Version:  1.12.2
- AE2 Version:  rv5-stable-11    
- Forge Version: 14.23.4.2705

**Comment by yueh** [comment]
We do not support Sponge officially.

Should you be able to reproduce it without it, please update the issue accordingly and we will reopen it.

**Comment by JoeSGT** [comment]
https://pastebin.com/072bMhFj
took out Sponge and still crash @yueh

**Comment by JoeSGT** [comment]
any updates about this situation ?

**Comment by JoeSGT** [comment]
https://pastebin.com/ejcL00YW
posting on here so if others has the same issue they can take a look, i had found a backup of my worlds and use it to restore whatever hat happen i also provided a pastebin with more detail about the crash

**Comment by yueh** [comment]
Closing for now as it's most likely data corrupted by sponge as discussed on discord. Our only option is to make the similar crashes a bit less vague in the future.
