### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by PhanaticD** [AppliedEnergistics/Applied-Energistics-2#3578]
#### Description

I got this crash report: https://pastebin.com/raw/vK6UvbEx should have all the information there

this is what it looked like in the log: https://pastebin.com/raw/NtTb8Dgq

I am using the "All the Mods 3" modpack if that is relevant
#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: rv6-alpha-1
- Forge Version: 1.12.2-14.23.4.2725

**Comment by yueh** [comment]
rv6 is still alpha and not considered usable for production. If "All the Mods 3" decides to test it, it is recommended to remove all AE2 addons until AE2 reaches stable or at least some time into the beta phase.
