### ISSUE TITLE
Many missing texutres, how to fix?

### ISSUE THREAD

**Issue by YumaYamamoto** [AppliedEnergistics/Applied-Energistics-2#3585]
I have many missing textures errors how to fix it? Screenshot of it: http://i.prntscr.com/ZJ6klzbjSeeZuUzDtLoL0A.jpeg
http://i.prntscr.com/puvmT5TmR52qgL97222iCg.jpeg

- Minecraft Version: Newest
- AE2 Version: Newest
- Forge Version: Newest

**Comment by mindforger** [comment]
"Newest" is not only lazy but unhelpfull as there is a "latest stable" of forge, a "latest built", a "latest beta" ... please do NEVER use "latest/newest" in an report

will reopen when you fix your issue

**Comment by YumaYamamoto** [comment]
Obviously I mean latest stable, Im not dumb. So how to fix? You didnt answer my question.

**Comment by mindforger** [comment]
and you did not provide any data to reproduce your issue, i gave you examples why "latest" or "newest" is not enough

fix your report and i will reopen

**Comment by YumaYamamoto** [comment]
I have no clue about minecraft mods I just started to use it since 2 days so obviously I cant provide more informations than that I use latest stable.

**Comment by mindforger** [comment]
You know where your mods are? Just look at the filenames. 95% of them got the version in name
