### ISSUE TITLE
Mekanism Cardboard Box spams crafting terminal

### ISSUE THREAD

**Issue by thundR** [AppliedEnergistics/Applied-Energistics-2#3589]
#### Description
Mekanism cardboard box with a vanilla blaze spawner spams the crafting terminal inventory, like so:
https://gyazo.com/d9498aca513db11ec8ce947efc531be8

Expected: One box in the terminal. 

#### Environment
Mekanism 9.4.11.349
Dedicated server
No ME drives, only storage buses on EnderIO warehouses and Actually Additions wooden crates. I suspect that this may be an interaction with the warehouse. 

- Minecraft Version: 1.12.2
- AE2 Version: rv6-alpha-1
- Forge Version: 14.23.4.2705

**Comment by fscan** [comment]
Can you inspect the NBT data of the cardboard boxes? This should only happen if the items have different NBT or caps attached to it.

**Comment by thundR** [comment]
I'm not sure I was clear. There is only one actual cardboard box in the system. As soon as it displays on the screen, the icons begin to increase as seen in the gif I linked. Closing the terminal and opening it again restarts the effect. 

As for the single box: this is the NBT
`NBT: {mekData:{blockData:{meta:0,id:52,tileTag:{MaxNearbyEntities:6s,RequiredPlayerRange:16s,SpawnCount:4s,SpawnData:{id:"minecraft:blaze"},MaxSpawnDelay:800s,Delay:369s,x:-116,y:56,z:-161,id:"minecraft:mob_spawner",SpawnRange:4s,MinSpawnDelay:200s,SpawnPotentials:[{Entity:{id:"minecraft:blaze"},Weight:1}]}}}}`

**Comment by thundR** [comment]
When trying to reproduce this, I set up a minimal AE system with a single drive and single storage cell, placed a cardboard box with a spawner in, and was unable to get it out at all, although the visual effect didn't happen.

**Comment by fscan** [comment]
After some debugging, this seems to be an issue with Astral Sorcery attaching caps to random stuff. I don't know why it only affect a filled cardboard box. Removing Astral Sorcery fixes the issue for me.
Can you confirm?

**Comment by fscan** [comment]
Maybe this is the same issue? https://github.com/HellFirePvP/AstralSorcery/issues/780

**Comment by fscan** [comment]
Ok, after having a short look i think i know what is going on.
Astral Sorcery attaches caps based on getMaxStacksize, which changes for the cardboard box after ItemStack creation (setBlocklData). So the droppe cardboar entity item has a cap, but the serialized/deserialized ItemStack in the storage cell does not (because the correct block data is present at ItemStack creation).
Please open an issue with these mods.
