### ISSUE TITLE
ME Interface duplicated redstone using formation plane

### ISSUE THREAD

**Issue by jv1057** [AppliedEnergistics/Applied-Energistics-2#3590]
#### Description

I have an ME Interface, flat form, that is attached to another ME Interface, block form, that  is connected to a formation plane, this drops items in water in order to automate Fluix Crystals. Other items pass through it just fine and get put into the world but redstone falls and but it still stays in the slot so it ends up duplicating the redstone. This occurs for all the slots, I now have a lot of redstone.

![ae2bug](https://user-images.githubusercontent.com/20132551/42352685-04f1dc74-808a-11e8-9b8f-001fe7b551b8.png)
![ae2bug2](https://user-images.githubusercontent.com/20132551/42352714-3bd62bfa-808a-11e8-9fb1-f9ab39743832.png)

#### Environment

Running FTB Revelation v2.1.0 

- Minecraft Version: 
- AE2 Version:  rv5-stable-11
- Forge Version: 8.0.99.99

**Comment by fscan** [comment]
https://github.com/SonarSonic/Flux-Networks/issues/239

**Comment by ZechCal** [comment]
still not fixed... I'm facing with same issue at 1.12 ae2-rv6, newest edition.(⊙o⊙)
And it seems only redstone can not processed rightly.
