### ISSUE TITLE
Memory card tooltip to show display name

### ISSUE THREAD

**Issue by exube** [AppliedEnergistics/Applied-Energistics-2#3593]
#### Description

When building large networks, I often find that I use too many p2p tunnels to keep track of.  One solution I've come across is renaming my tunnels on an anvil, as output tunnels inherit the display name of the input tunnel.  This is especially useful with WAILA or an equivalent mod installed, as this gives players an easy way to keep track of their tunnels.

My suggestion is that memory cards show the display name of the source device as part of the tooltip.  This will also make memory cards easier to organize, without renaming the card itself.

I cobbled together a demo [here](https://imgur.com/a/NX0jmh6)
#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: rv6-1.12 (3ba04b3)
- Forge Version: 14.23.3.2655

**Comment by fscan** [comment]
We are planning to do an QoL overhaul of the P2P system. Please provide any input there.
I'm linking #2978 and #2674 here to keep a reference to this.
