### ISSUE TITLE
Terminal GUI closing when trying to autocraft

### ISSUE THREAD

**Issue by Hamsterotron9000** [AppliedEnergistics/Applied-Energistics-2#3594]
If I have portable storage cell in inventory (not on hotbar) any terminal instantly closing after I clicking on item what I want to autocraft. May be it will conflict with other items with gui, like a wireless terminal or something.

Minecraft   1.12.2
AE2 rv5-stable-11
Forge 14.23.4.2711
singleplayer

**Comment by fscan** [comment]
I cannot reproduce this. Please post more information, like details (eg screenshots) about your setup and log files.

**Comment by Hamsterotron9000** [comment]
well it is strange but it fixed itself and dont appeared anymore.
I'll try to record this on video if it will appear again

**Comment by fscan** [comment]
Well, i'll close this for now. If it happens again, reopen.
