### ISSUE TITLE
Dupe Bug involving ME Fluid Terminal

### ISSUE THREAD

**Issue by Birgliss** [AppliedEnergistics/Applied-Energistics-2#3595]
#### Description

When extracting and inserting fluids from an ME Fluid Terminal, it is expected to give and take 1000mb. 
Currently, it gives and takes 169mb.
In conjunction with tanks from other mods, this results in a dupe bug, as they insert the proper value.
#### Environment

- Minecraft Version: 1.12 (multiplayer server)
- AE2 Version: rv6 alpha 1
- Forge Version: 14.23.4.2705

Modlist: 
![image](https://user-images.githubusercontent.com/20749209/42415022-c9c95f68-8210-11e8-95b7-d39940b7772a.png)

this was tested with:
EnderIO's iron tank
Mekanism's basic tank

**Comment by fscan** [comment]
It should insert/extract as much as it can (eg tank size), limited by the available power. It is possible that the power scaling is currently not correct and the "not enough power" case is not handle correctly.
Can you attach some energy cells (AE2) to the network and try again?

**Comment by Birgliss** [comment]
will do. launching the game now

**Comment by Birgliss** [comment]
oh, some added clarification:
buckets insert 169mb
for some fluids (it's inconsistent) you can fill a bucket with 169mb as well
