### ISSUE TITLE
Quantum link chambers

### ISSUE THREAD

**Issue by MrBeegamer** [AppliedEnergistics/Applied-Energistics-2#3596]
Hey everyone, im trying to set up a quantum link chamber for my second base and when ever i start it up either my second base or my main base's ME termnial says device missing channel. Im using 1.7.10 and heres a screen shot. 
![image](https://user-images.githubusercontent.com/40927526/42416284-dfb78258-82ad-11e8-89c2-fdfa0e09efd1.png)

That is my second base that is saying device missing channel.

**Comment by mindforger** [comment]
1.7.10 is not supported anymore, therefore i will close. But if you tell usb a bit more on how you set it up, we may figure it out, but chances are high for it being a user-error.

Please tell me how you created the singularitys and if both of your systems are chunkloaded. Make sure all systems have enough power and some energy cells installed, those are very important
