### ISSUE TITLE
Fuzzy Export Bus not correctly Exporting

### ISSUE THREAD

**Issue by PiggyWhiskey** [AppliedEnergistics/Applied-Energistics-2#360]
I'm attempting to set up an Export Bus into a Mekanism Factory (Results repeatable with Vanilla Chests)

The Export Bus has:
2x Capacity Cards
1x Fuzzy Card
1x Acceleration Card

The Export Bus is configured to Iron Shard (BTP Item ID: 6568:0, Item Name: Mekanism:Shard)
The Export Bus refuses to send Gold Shard (BTP Item ID: 6568:1, Item Name: Mekanism:Shard)

The Fuzzy Export Bus isn't filtering by true Meta Data fuzzy-ness and will only export the precise item (Iron Shard)

Is it likely to be an option to Fuzzy on Name or Meta Data?
Or is it set to Fuzzy only on matching Item Name?

**Comment by krakentoa** [comment]
enderio is a decent mod and their fuzzy behavior does work with these other weird "damage values". most use cases I have for "match a range of items" do not work with ae fuzzy card.
 maybe extending this functionality to metadata would be a good improvement?
