### ISSUE TITLE
Minecraft crashing when searching specific things in a terminal

### ISSUE THREAD

**Issue by jannik2103** [AppliedEnergistics/Applied-Energistics-2#3600]
#### Description
Everytime when entering some combination of letters into the "searchfield" from a crafting-terminal or normal terminal like something with a vocal: "redXXX" "resXXX" "solXXX" minecraft crashed without a server-error or an client error. It closes without any notification.

#### Environment
normal minecraft ae2-network
Multiplayer

- Minecraft Version: 1.12.2
- AE2 Version: v6 alpha
- Forge Version: Forge Vanilla 14.23.4.2705

**Comment by fscan** [comment]
Does the same thing happen if you just type it in JEI? And what crashes, server or client? Look in the logs folder of you client for recent log files.

**Comment by jannik2103** [comment]
....found out that its because of JEI. I'm sorry fscan.
