### ISSUE TITLE
Busses stopped working? (One part of the base...)

### ISSUE THREAD

**Issue by 34486** [AppliedEnergistics/Applied-Energistics-2#3607]
#### Description
I expected import and export busses to continue to work. 

#### Environment
No crashes or errors in console of multiplayer.
I am on multiplayer on my own server and I made a processing area for my fusion plant from Tech Reborn. I had it all setup and turned it on to run, it was all working, every part of it, exporting endstone dust for deuterium and electrolyzing ect all that and I come back about 3 hours later and find it stopped working, EVEN exporting the empty cells to the fluid transposer had stopped working, now, this large subnet is p2p to the fusion area from the main network and then the subnets on that fat cable to run my processing plant, all the busses had a channel, said they was on, and I even placed a terminal right on the subnets with the busses and it could access everything. I have NOT changed any part of that network in the 3 hours I was gone from it since I was in the twilight forest. I didn't run out of drive space or anything. Items just stopped being imported and exported. I am the only one at that base, I hope I proved the point that NOTHING was changed (accept for it stopped working) in the 3 hrs when it was working to death.

I don't understand why the items stopped working with the fluid transposer, autocrafting works on the rest of my network, (so the busses work) and thats set up the same exact way, p2p then subnet! I don't understand, its all chunk loaded too!! No quantum link chambers involved I have no idea what to do here! Help please!

- Minecraft Version: 1.12.2
- AE2 Version:  RV5 Stable 11
- Forge Version: 2705 for 1.12.2

**Comment by 34486** [comment]
By the way it has plenty of power, everything. Even hooked up dense energy cells to the very end of the subnet, charged right away. No clue what is going on.

**Comment by 34486** [comment]
the chickenchunks loader one and its maxed out, I can double check sometime if the chunks are loaded, and ill try the network tool to see if it says an error

**Comment by fscan** [comment]
It won't tell show you an error, but it will tell you what devices are connected to the network you clicked on.   Also, have a look into forgeChunkLoading.cfg, maybe your chunkloader is not allowed to keep that may chunks loaded at once.

**Comment by mindforger** [comment]
I can tell that the resizeable chicken chunkloader did not work well in the past versions

**Comment by 34486** [comment]
Ok I checked nt and it said all they was all connected, like, a all of them since there are a lot, but thye stil dont work every part is chunkoaded, even myself as a plyer the view distance for chunks is still loading the entire base accept my future storge unit, and there is an import bus for tree farm there n its suckin in the iitems... I got NO idea since terminal on the subnet with the busses can access everything (accept autocraft ofc thats normal) idek. btw i made chunkloader a max of 800 chunsk it only cranked to 441 (11 dist) so yea idek

**Comment by fscan** [comment]
Can you post a full server log (pastebin or something)?
Some screenshots of your setup would be helpful. Have you tried breaking and replacing a bus? Also, just to be sure the issue is on AE2 side, have you tried extracting/inserting with another pipe/duct/hopper?

**Comment by 34486** [comment]
I have not tried ducts hoppers ect, I can get a pic of setup and logs
twomarrow, yes i broke and replace bus and shut down network and started
again and all that still no fix. But yea I will get the log and try
extracting with a hopper/ducts and send sceenshots

**Comment by fscan** [comment]
Ok, your (blue cable) subnet seems to be working, but the storage bus connecting to it is offline. Check if this part of the grid is powered and has enough free channels.
BTW, now that i see that you use storagebus<->interface subnets: do you have a security terminal installed? if yes you will need to give anonymous subnets the rights to insert and extract stuff (or install a security terminal on the subnet too) .. see https://ae-mod.info/ME-Security-Terminal/

**Comment by 34486** [comment]
Oh.............................................. Yea.. I added a security term, and thats when the issue started happening.... Will check it out to confirm and fix the storage bus issue, thanks for findin that!

**Comment by 34486** [comment]
Ok it just started working now, took a while to register it was gone. Thanks guys! You might reconize this build style from Thorinair. (I am making a near replica)
