### ISSUE TITLE
Processing Pattern & Ore-Dict Substitutions

### ISSUE THREAD

**Issue by GitHubUser88E10000** [AppliedEnergistics/Applied-Energistics-2#3608]
For a simple crafting template a ore dictionary is available, but for processing template this feature is not available, although it would be very useful. Is there there a way to turn it on a chance to ask you to add this feature?

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: 14.23.4.2711

**Comment by yueh** [comment]
#2501
