### ISSUE TITLE
Can interfaces "show" the ME inventory to conduits and itemducts? 

### ISSUE THREAD

**Issue by GameSlayar** [AppliedEnergistics/Applied-Energistics-2#3612]
#### Description
I think that in the same way that the ME interface "shows" the inventory of the system to an ME Storage bus, it should show this same inventory to something like an item conduit from Thermal Expansion. There are a couple of filters that I cannot achieve with standard export buses (like "Extract only from this mod) that TE itemducts support.
I set up the itemduct to extract from the Interface, expecting it to show the items in the system to said itemduct, but it extracted nothing unfortunately. I heard RS has this feature _([Link](https://www.reddit.com/r/feedthebeast/comments/81jugx/how_do_i_export_items_from_a_single_mod_from_my/dv3m3qu/))_, but I like AE2 much more, so I was hoping for either a solution or maybe an explanation why this doesn't work.

![2018-07-13_15 50 45](https://user-images.githubusercontent.com/10010491/42698082-c6caeed2-86b4-11e8-8ce6-072c656fdbde.png)
![2018-07-13_15 50 51](https://user-images.githubusercontent.com/10010491/42698120-dfb2b826-86b4-11e8-9066-d4c73ed98d97.png)

#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: forge-14.23.4.2709

**Comment by yueh** [comment]
Performance, same reason RS is removing it again.

**Comment by GameSlayar** [comment]
Would there be any intelligent way that you could recommend for me to pull out items from a certain mod? i.e. Thaumcraft?

**Comment by fscan** [comment]
There is currently no way except manually specifying the items (either with export buses or with a storage bus if you want to store specific stuff separately). I'm curious what do you want to achieve with this, as i can't think of any use for this off the top of my head. You can sort and filter by mod in the terminal.

**Comment by GameSlayar** [comment]
You can sort by mod with the terminal?

The whole purpose of this was for me to make a slave network that only had Thaumcraft items in it. Mainly for ease of access. But if I can just sort the terminal by mod, that totally solves my problem.

**Comment by fscan** [comment]
Filtering works like in JEI, just type eg: "@thaum" for thaumcraft. For sorting just cycle through the sorting modes.

**Comment by GameSlayar** [comment]
Oh, I thought you meant I could filter via View Cell. I thought I could set up a view cell for a terminal just for Thaumcraft stuff for example.

**Comment by fscan** [comment]
Something like this may be an idea for a future version, but currently not possible (afaik) without specifying every single item.
