### ISSUE TITLE
Applied Energistics Crashes during Post Initialization!

### ISSUE THREAD

**Issue by Devilswarchild** [AppliedEnergistics/Applied-Energistics-2#3614]
Not Sure Whats Going on with Applied Energistics 2 Ive tried both appliedenergistics2-rv6-alpha-2.jar and appliedenergistics2-rv5-stable-11.jar and both crash minecraft during the post initialization process. Im not sure if its the mod itself or another mod is interfering with it. So Ill post the entire latest log file for ya'll to read through and see if you can help me get it working. 

Minecraft: 1.12.2
Forge: 1.12.2 - 14.23.4.2732
[latest.log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/2194206/latest.log)

**Comment by fscan** [comment]
Someone is using the dimension AE2 uses for the spatial dimension (in your case 3). If you just installed AE2 the configure another id. If not, some other mod grabbed our dimension without checking if it exists first .. configure that mod to use another or you will loose your stuff in spatial io.
