### ISSUE TITLE
Custom recipes folder missing + some normal recipes missing

### ISSUE THREAD

**Issue by UnPure** [AppliedEnergistics/Applied-Energistics-2#3616]
#### Description
For some reason i dont have the aerecipes folder inside of the ae2 config folder.
I also noticed that some of the recipes are missing. For example, all storage cells have only the recipe for cell + housing but no direct recipe. The housing itself has no recipe at all so its basically impossible to craft a working storage cell.

#### Environment
Modlist: https://pastebin.com/dcpx7SCB
latest.log: https://gist.github.com/UnPure/5699ba42ec5d6954d18d736555cefe4a
AppliedEnergistics2.cfg: https://pastebin.com/WfEkDzHF
CustomRecipes.cfg: https://pastebin.com/1cLWtTN7

- Minecraft Version: 1.12.2
- AE2 Version: rv6-alpha-2
- Forge Version: 14.23.4.2732

**Comment by yueh** [comment]
There is a reason we publish changelogs on github and [ae-mod.info](https://ae-mod.info/).

**Comment by fscan** [comment]
You disabled decorative quartz blocks, which for some reason quartz glass counts for. I will open a new issue for this, as quartz glass is needed in a lot of recipes.
