### ISSUE TITLE
Clean up configuration

### ISSUE THREAD

**Issue by fscan** [AppliedEnergistics/Applied-Energistics-2#3617]
For example quartz glass is behind the decorative blocks feature. This may be technically true, but the consequence of this is that you cannot disable decorative blocks as a lot of core recipes need it. The same is true for  fluix blocks and sky stone.
As there will be a lot of changes in item and block definitions for 1.13, this would be a good place to start cleaning up and restructuring the config file a bit.

**Comment by Ommina** [comment]
I don't know if this is a step too far removed for this discussion, but I'd like to mention it here anyway.  It surely falls under the "unintended consequences" umbrella, at any rate.

Disabling channels effectively disables the QNB, as the recipe for the latter uses a dense smart cable, which are removed when disabling the former.

When this has been mentioned in the past, the reply has been "use a custom recipe", which is certainly only a few minutes' work, but nonetheless feels a bit unsatisfying.

**Comment by fscan** [comment]
Config will change a lot in new forge. New format (toml) and probably multiple configs (global, player, server).
Completely disabling item/block registration based on config is discouraged because of config reloads/sync. An easy way to hide registered items will probably be provided.
