### ISSUE TITLE
AE2-RV6 Alpha 3 Crash

### ISSUE THREAD

**Issue by Furious1964** [AppliedEnergistics/Applied-Energistics-2#3621]
Crash on start-up with new build.

Installed latest build and game crashed on start-up.

Playing FTB Revelation Pack and going back to Alpha 2 doesn't produce a crash.
Crash Report: https://pastebin.com/2MTL2b1F

- Minecraft Version: 1.12.2
- AE2 Version: RV6 Alpha 3
- Forge Version: 14.23.4.2736

**Comment by Pingger** [comment]
extraCells went incompatible with the new build

**Comment by Furious1964** [comment]
Thank you.

**Comment by fscan** [comment]
please don't, this is an expected API break and we are already working with the extra cells devs to resolve it.

**Comment by Furious1964** [comment]
I've already checked the Extra Cells 2 site before you posted and they are currently working on the problem, so there was no need to post anything.
