### ISSUE TITLE
Split ItemStack and AE specific data from the AEStack definition

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#3623]
Currently AE specific data/values are stored together with the serialised ItemStack. To avoid conflicts, both should be splittet into their own separate datastructure. E.g. preventing data fixers from affecting the AE2 data.

**Comment by StarboundModderRWC** [comment]
is there a way to split one item going into multi machines by setting a value for the item in the import, export bus ?
