### ISSUE TITLE
opaque texture of facades with OptiFine

### ISSUE THREAD

**Issue by KiraLinux** [AppliedEnergistics/Applied-Energistics-2#3629]
with OptiFine glass texture of the glass facades do not look transparent
Textures with zero transparency are displayed normally
OptiFine_1.12.2_HD_U_E1

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-alpha-3
- Forge Version: 1.12.2-forge1.12.2-14.23.4.2705

![2018-07-19_100602](https://user-images.githubusercontent.com/20641834/42926889-6b387842-8b3b-11e8-969c-e56c8b90e43c.png)
![2018-07-19_100624](https://user-images.githubusercontent.com/20641834/42926890-6b5e400e-8b3b-11e8-92f8-336ff751d82e.png)

**Comment by yueh** [comment]
Please report Optifine bugs to Optifine itself as it is closed source and we do not know it it changes/breaks the default vanilla/forge rendering.
