### ISSUE TITLE
Dupe bug with security terminal and cables

### ISSUE THREAD

**Issue by maximcs1** [AppliedEnergistics/Applied-Energistics-2#3634]
There is no protection of the region.
The First step: Create a simple ME network with security terminal, ME Dense covered cable and ME Covered cable.
https://image.ibb.co/dSpPzJ/2018_07_22_14_33_56.png
The Second step: Another player becomes like in the screenshot and right click with ME toggle bus
https://image.ibb.co/fVSV6y/2018_07_22_14_35_20.png

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv5-stable-11
- Forge Version: 14.23.4.2739

**Comment by yueh** [comment]
We do not support P2W servers running all sorts of unkown/broken plugins.

**Comment by maximcs1** [comment]
I tested on the original forge server.
This video showed for an example dupe

**Comment by fscan** [comment]
Please explain how to reproduce this in english.  Attach server logs if possible.

**Comment by Pingger** [comment]
Is this made in a server protected Area? There might be a duplicate item return event from another mod involved (e.g. the Protection mod)
The area shown in the video looks like a protected HUB Area, where only a subset of players is allowed to build.

**Comment by maximcs1** [comment]
There is no protection of the region.
The First step: Create a simple ME network with security terminal, ME Dense covered cable and ME Covered cable.
 https://preview.ibb.co/dSpPzJ/2018_07_22_14_33_56.png
The Second step: Another player becomes like in the screenshot and right click with ME toggle bus
https://image.ibb.co/fVSV6y/2018_07_22_14_35_20.png
