### ISSUE TITLE
Implement a batch pattern system

### ISSUE THREAD

**Issue by Jizanthapus** [AppliedEnergistics/Applied-Energistics-2#3642]
**Suggestion**
To further advance the autocrafting mechanic, a batch crafting system could be utilized to call multiple crafting patterns through one interaction. 

**Use Case**
I want to add a new crafting computer to my AE network. I want all my computers to be the same (e.g. 1 Crafting Unit, 3 Crafting Co-Processing Units, 4 4k Crafting Storage). A Batch Pattern that contains this request could be created and placed into a special Interface or other network device. I could then call this recipe from an ME terminal and specify the number of new computers I would like to craft.

**Comment by fscan** [comment]
@Pingger  Have you actually tried this? This does not work. You cannot have recursive crafting patterns where the output is part of the input. Please confirm before suggesting "solutions".

**Comment by yueh** [comment]
This can already be achieved by using some creativity.

**Comment by Pingger** [comment]
@fscan I HAVE not obly tried this, but am actually using this in my wirld. Once home I can make a videi to deminstrate this.
