### ISSUE TITLE
Crash involving AE2 rv5-stable-11 and PeripheralsPlusOne 1.1-T58

### ISSUE THREAD

**Issue by craft-lover** [AppliedEnergistics/Applied-Energistics-2#3643]
#### Description
So, recently I tried adding PeripheralsPlusOne (ver' 1.1-T58) to the latest version of SevTech Ages (3.0.8) which resulted in a crash. Using the deinstall-rerun method I verified that it was indeed PPO causing the crash, however the report which Minecraft generated cited Applied Energistics 2 (rv5-stable-11) as being the errored party and further cited a code path referencing Botania which is not installed.

I have already posted on the PeripheralsPlusOne Curse page and have reached out to the #help section on the Bontania Discord channel.

[Link](https://pastebin.com/42KpuFyL) to paste.

#### Environment
pack: SevTech Ages 3.0.8
    running: AE2 r5v-stable-11
added: PeripheralsPlusOne 1.1-T58
    (core/dependency) The Framework 1.0.1-T23

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version:

**Comment by fscan** [comment]
PeripheralsPlusOne  passes us an invalid IMC messge. We guard against missing classes (ClassNotFoundException), but for some reason it throws an NoClassDefFoundError. Not sure what that is about.

**Comment by fscan** [comment]
The main issue is probably that PeripheralsPlusOne ships botania api. Leaving this open because imho we shouldn't really crash in the MCI handler ever.

**Comment by craft-lover** [comment]
On 2018.07.24 rolandoislas stated that this issue should be fixed on PPO's end in the T65 beta release. I just checked and the new version does indeed run with out crashing.
