### ISSUE TITLE
Disable meteorites with chests and turn on without chests.

### ISSUE THREAD

**Issue by MrLador** [AppliedEnergistics/Applied-Energistics-2#3649]
Description
I'd like to have a way to disable the generation of meteorites with chests inside and replace them with spavn empty meteorites without a chest. This is useful for the development of various assemblies where crafting presses are added.
- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: 14.23.4.2705

**Comment by yueh** [comment]
Just disable the spawning of presses themself.
