### ISSUE TITLE
Spatial IO Spongepowered

### ISSUE THREAD

**Issue by beareogaming** [AppliedEnergistics/Applied-Energistics-2#3651]
When using spatial IO on a spongepowered server i cannot get it to function regardless of size/power supply

#### Description
When creating a spatial io system, the system would not function at all, originally it would load the dimension then unload shortly after, so i forced the dimension to stay loaded and now i get no messages in console & the spatial IO draws no power nor moves the cell to the output slot.

I am fairly certain it is spongepowered but cannot track down what exactly is causing it

#### Environment
recommended build of FTB Revelations (v2.2.0)
AE2 = rv5-stable-11
spongepowered = 7.12.2-2705-7.1.0-beta-3323
forge 14.23.4.2729
minecraft 1.12.2

**Comment by fscan** [comment]
We do not support sponge, i will reopen if you can reproduce without.
