### ISSUE TITLE
Cable Facades

### ISSUE THREAD

**Issue by SaxonHW** [AppliedEnergistics/Applied-Energistics-2#3655]
Cable Facades arn't cappable of being rotated.

Cable Facades neewd to be able to be rotated like wood logs are. As they stand out like dogs balls when they arn't rotated. And by rotated i don't just mean clockwise but to all directions. as to show the ends as well.

- Minecraft Version: All
- AE2 Version: All
- Forge Version: All

**Comment by Dimentive** [comment]
How are you using all versions of Minecraft, AE2, and Forge at the same time? That’s pretty damn impressive, if I do say so myself.

**Comment by Dimentive** [comment]
How are you using all versions of Minecraft, AE2, and Forge at the same time? That’s pretty damn impressive if I do say so myself.

**Comment by deregtd** [comment]
Just +1'ing this.  Just spent several hours building a giant tree and started running AE2 cables and then found that they don't work at all with wood logs, so back to the drawing board from scratch for a new design, unfortunately. :(
