### ISSUE TITLE
Game crashes when i try to get items from AE2

### ISSUE THREAD

**Issue by xp0colipse** [AppliedEnergistics/Applied-Energistics-2#3656]
mod version - appliedenergistics2-rv5-stable-11
Minecraft version 1.12.2
forge and liteloader version - 1.12.2-LiteLoader1.12.2-1.12.2-forge1.12.2-14.23.4.2711

I can load my game fine, but when I tab over or search for ae2 items in nei, the game crashes instantly.

https://pastebin.com/r9Y5y13R

**Comment by fscan** [comment]
Please try without optifine

**Comment by xp0colipse** [comment]
okay loading it up again

**Comment by fscan** [comment]
after a short google:
see https://github.com/micdoodle8/Galacticraft/issues/3393 or https://github.com/BuildCraft/BuildCraft/issues/4175

**Comment by xp0colipse** [comment]
solved, thank you very much
