### ISSUE TITLE
Stored items not recognized when upgrading world from 1.10.2

### ISSUE THREAD

**Issue by tupperkion** [AppliedEnergistics/Applied-Energistics-2#3657]
#### Description

I just upgraded my private modpack from 1.10.2 to 1.12.2. While doing this upgrade, I have noticed that every time a storage cell that already had items is inserted into a drive, a message like below is logged for every item type in the cell (modded and vanilla items):
```
[16:07:09] [Server thread/WARN] [AE2:S]: Removing item {Craft:0b,Cnt:1L,id:"minecraft:iron_shovel",Count:0b,Damage:193s,Req:0L} from storage cell because the associated item type couldn't be found.
```
As well, nothing shows up in the terminal. The tooltip of the storage cell doesn't change. If the storage cell has available types, I can put additional items in, and they will show up; however, I can't if the cell is full (w/ orange indicator). AE system does have more than enough power, connections are good, channels are not an issue.

#### Environment

- Minecraft Version: 1.12.2 (upgraded from 1.10.2)
- AE2 Version: rv6 alpha 3 (upgraded from rv4 alpha 9)
- Forge Version: 1.12.2-14.23.4.2745 (upgraded from 1.10.2-12.18.3.2511-installer)

#### [`Full log report`](https://gist.github.com/tupperkion/dd9ef03c1cf02ee8d39713d14c65d4a1)

All mods have latest versions as of within 24 hours of this post.

<details><summary>Full mod list</summary>

```
flyringbaublemod
appliedenergistics2
attachablegrinder
autoreglib
base
baubles
betterbuilderswands
bloodmagic
bookshelf
botania
brandonscore
chesttransporter
chickenchunks
chickens
chisel
chiselsandbits
clienttweaks
clumps
codechickenlib
cofhcore
cofhworld
controlling
ctgui
crafttweaker
crafttweakerjei
ctm
cucumber
cyclopscore
darkutils
deepresonance
dimensionalcake
draconicevolution
eleccore
elevatorid
endercore
enderio
enderstorage
exnihilocreatio
extrautils2
bigreactors
fastleafdecay
flatcoloredblocks
microblockcbe
forgemultipartcbe
minecraftmultipartcbe
funkylocomotion
generallaymansaestheticspyingscreen
globe
gravestone
gravitygun
guideapi
waila
ichunutil
inventorysorter
ironbackpacks
ironchest
jei
journeymap
jeresources
mantle
mcjtylib_ng
mcmultipart
minemenu
mob_grinding_utils
modtweaker
morphtool
morpheus
mrtjpcore
mtlib
mysticalagriculture
neat
nei
opencomputers
packingtape
platforms
portalgun
projectred-core
projectred-compat
projectred-fabrication
projectred-integration
projectred-transmission
projectred-illumination
projectred-expansion
projectred-relocation
projectred-transportation
psi
quark
rangedpumps
reborncore
redstonearsenal
redstoneflux
rftools
rftoolscontrol
rftoolsdim
stevescarts
sync
tcdrill
tconstruct
tesla
beneath
thermaldynamics
thermalexpansion
thermalfoundation
thermalinnovation
tp
torchmaster
translocators
treegrowingsimulator
wrcbe
yunomakegoodmap
zerocore
shetiphiancore
```
</details>

**Comment by yueh** [comment]
Upgrading between minecraft versions is not supported and will result in dataloss.
