### ISSUE TITLE
Error when loading Debug World

### ISSUE THREAD

**Issue by thakyZ** [AppliedEnergistics/Applied-Energistics-2#3663]
#### Description
Loaded a new Debug World save and crashed instantly when loading chunks due to the quantum_rign block state error.

#### Environment

Modded enviorment and used many times before. This was testing in Single Player and other mods are listed here: https://git.io/fNKTm
The complete crashlog: https://git.io/fNKTs

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: 14.23.4.2745

**Comment by fscan** [comment]
This should only happen when the TileEntity is missing, which either points to a corrupted save or something trying to render the chunk before its loaded.
Have you tried without optifine? Also, betterfoliage shows up in the trace, try without it.

**Comment by thakyZ** [comment]
Does it detect if the tile entity is there, by checking the block next to it? Because if so, then that is the exact reason why I was crashing because every block in the debugging world is spaced one block apart.
