### ISSUE TITLE
Crash when using non-AE drives from any AE-addon mods

### ISSUE THREAD

**Issue by andyad8865** [AppliedEnergistics/Applied-Energistics-2#3666]
#### Description

From what i have found this happens when using storage drives from any addon mod for AE2, this results in the mod ether deleting the item when placed in a "ME Drive" OR "ME Chest" or crashing the Client/Server, this is repeatable as i have had this happen multiple times with different addon mods, this happens to all mods that add storage drives to the game to be used in a AE network.

#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: AE2-RV2-Alpha-3
- Forge Version: 14.23.4.2739
- World: Single Player
- Crash-log: Via LAN Server
- Link: https://pastebin.com/xUQ16z2f

Can someone help with a fix for this as it is causing the mod to be unusable with addon mods, if needed I have more crash-logs.

Thanks
Andy

**Comment by yueh** [comment]
Alpha explicitly states that it is for testing only and not compatible with any addon.
