### ISSUE TITLE
AE2 crashes the game when autocrafting

### ISSUE THREAD

**Issue by niedem** [AppliedEnergistics/Applied-Energistics-2#3670]
Okay so I'm playing the A bit of Everything pack, version 2.0.2. It contains AE2 rv3 beta 6, alongside with some other ae2 related mods. No problems whatshowever. However, i just came to the point in the game where autocrafting kicks in. I made myself a processor, but when I tried to craft up some stuff nothing happened. When I opened the active processes interface, my world (so not the game) crashed. I tried troubleshooting in a different creative world, but nothing seemed to change anything, same behaviour. I tried downgrading to rv2 as well as different beta releases but nothing seemed to fix the issue. Autocrafting seems to be enabled in the config, and my ae2 setup is also fine. 
Im on minecraft 1.7.10 with forge version 10.13.4.1614

Crashlog:
https://pastebin.com/eiHG8KvU

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.12 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.

**Comment by mindforger** [comment]
try removing fastcraft, es it is part of the Grad in an very low level and may cause this

**Comment by niedem** [comment]
Thanks mindforger, sadly no luck
