### ISSUE TITLE
Bad channel distribution after unloading/reloading area

### ISSUE THREAD

**Issue by CheapySheep** [AppliedEnergistics/Applied-Energistics-2#3671]
Hi everyone, I'm playing on a MC server with a friend on a 180 mods-modpack. We recently build our big auto-crafting setup: 1024 interfaces+molecular assemblers. They are divided in 8 tower of 128 interaces. Every tower is made of 4 parts of 32 interfaces and molecular assemblers linked to a P2P tunnel. The P2P tunnels are linked to a sub-network which is linked to others P2P to the real network.

We think that because the interfaces are attached together maybe they make a bad distribution of the 32 channels between theim. After every reboot (not after every area realoading beacause we're using chunk loader form Chicken Chunk) we need to take off every cable of each part then replace them to actualize the channels and to make theim working again.

We hope that you'll considere our request and maybe fix it if it's not intended.

PS: Sorry for my bad english ;)

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: 1.12.2-forge1.12.2-14.23.4.2744

**Comment by yueh** [comment]
[Channels](https://ae-mod.info/Channels/).

**Comment by mindforger** [comment]
i know i should encourage OP to read the channels FAQ but to make it short, block-devices may share channels, but they can only carry 8, so make sure you don't have block-devices touching each other where they shouldn't or you may run out of paths to reach the far most blocks

always plan to have a dense line going near each block and don't rely too much on the channel propagation

also if you improve your layout to not have too many alternative routes to link up blocks
(i.E. 8 presses in line connected additionally from the back via cable, where channels can be transfered in strange ways between blockss and cable)
you can improve performance and reduce lag on the server in case of low power situations

recalculation of channels takes a lot of time and the more paths the more time it may take
