### ISSUE TITLE
Problem with AE network (and IndustrialCraft 2 item)

### ISSUE THREAD

**Issue by LordWiseRus** [AppliedEnergistics/Applied-Energistics-2#3672]
The iron turning form (any) from mod IndustrialCraft2 doesn't take away from AE network.

![default](https://user-images.githubusercontent.com/41589224/43838537-569d3a14-9b24-11e8-9528-5dfa2afece5e.png)

- Minecraft Version: 1.7.10
- AE2 Version: appliedenergistics2-rv2-stable-10
- Forge Version: 1.7.10-Forge10.13.4.1614-1.7.10
- Industrial Craft 2 Version: industrialcraft-2-2.2.825-experimental

**Comment by mindforger** [comment]
update AE2 rv2 is broken, use the latest beta for 1.7.10 this is fixed as IC2 introduced special meta values that can't be handled by AE2 in this particular version 

@yueh wasn't there a final stable rv3 somewhere for 1.7.10 ?!

**Comment by LordWiseRus** [comment]
rv2-stable-10 is the latest version 1.7.10. I don't see other versions on https://ae-mod.info/Downloads/

**Comment by Tahakk** [comment]
[Here](https://minecraft.curseforge.com/projects/applied-energistics-2/files?filter-game-version=2020709689%3A4449) you can get more recent version

**Comment by LordWiseRus** [comment]
Thank you.

**Comment by mindforger** [comment]
Lol, why is rv3 missing on the homepage?

**Comment by LordWiseRus** [comment]
???

**Comment by yueh** [comment]
1.7.10 isn't supported anymore.

**Comment by mindforger** [comment]
oh shoot i read that rv6 and thought this is now 1.12 sorry
