### ISSUE TITLE
Molecular Assemblers Prioritization

### ISSUE THREAD

**Issue by temp1029** [AppliedEnergistics/Applied-Energistics-2#3677]
Allow priority to be set on Molecular Assemblers for use by an interface.

#### Description
Basically, I want to be able to prioritize Assemblers which are exclusively attached to one interface over those which are attached to multiple interfaces. The idea is to use a dedicated resource before using a shared resource.

This could be either an automated calculation or a manual setting for those of us OCD enough to care.

Sorry if this has been asked and answered before, I looked for previous issues with some of the keywords, but could've missed it.

**Comment by yueh** [comment]
That's why interface have priorities.

**Comment by BlueAgent** [comment]
I think they're asking for, given a configuration like this:

`MIMIM
M - Molecular Assembler
I - Interface`

A way to have the interfaces use the assemblers on the left or right be used before the shared middle one.

Interfaces already properly share the common assembler though.

**Comment by temp1029** [comment]
That’s correct @BlueAgent. Are you saying that’s the way it works now?
