### ISSUE TITLE
i just have a question

### ISSUE THREAD

**Issue by joshuasuperboy** [AppliedEnergistics/Applied-Energistics-2#3679]
how do i click processing recipes into the pattern grid when i do not really have the items for me to put in there

**Comment by mindforger** [comment]
you don't, that is how it is designed. But i think you could pull ghost items from the right, but afaik they always come with a full stack, so you need to adjust the stack size every time, so it is a tedious Workaround. Please close the issue if your question is answered :)

**Comment by joshuasuperboy** [comment]
so i basicly change the code so it will not require the items

**Comment by mindforger** [comment]
Technically yes. Keep the license in mind

**Comment by joshuasuperboy** [comment]
k will do
