### ISSUE TITLE
Lighting issues for all items

### ISSUE THREAD

**Issue by morgan2233** [AppliedEnergistics/Applied-Energistics-2#3680]
#### Description
All panels and blocks for example peaces of the auto-crafting CPU's do not illuminate when power is provided; they stay dim as if unpowered, inside NEI or creative inventory the panels look darkened.

#### Environment
Other Mods: NEI, JEI, Aroma1997, Optifine, Xaeros Minimap

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv5-stable-11
- Forge Version: 1.12.2-forge1.12.2-14.23.4.2705

**Comment by mindforger** [comment]
Sounds like an graphical issue on your side can you post a list of all mods and their versions? Don't forget optimizing mods like fastcraft, foamfix or optifine...also try it without those mods first please

**Comment by FlandreCirno** [comment]
I had similar problems and it seems that it depends on the facing of the blocks. Like ME chest, the panel side of it is dim sometimes but illuminate when rotates to some direction. I didn't test which mod caused that since it is not critical.
