### ISSUE TITLE
Spatial IO problems with SpongeForge

### ISSUE THREAD

**Issue by FlandreCirno** [AppliedEnergistics/Applied-Energistics-2#3681]
#### Description

I'm currently running a test server to figure things out. Applied Energistics 2 spatial IO doesn't work with Sponge and forge server, but works with only forge server. It throws an Exception as posted below(only switch debug logging on in AE2 configs) after activating spatial IO.

Exception:
https://gist.github.com/FlandreCirno/fc57dc27bbeb9df56feae9e14905b791
Full log:
https://gist.github.com/FlandreCirno/73732703f643910c3a82735e91cc69ab
#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11/rv6-alpha-3
- Forge Version: forge-1.12.2-14.23.4.2705-universal

**Comment by FlandreCirno** [comment]
https://github.com/SpongePowered/SpongeForge/issues/2384

**Comment by yueh** [comment]
We do not support Sponge officially.

Should you be able to reproduce it without it, please update the issue accordingly and we will reopen it.

**Comment by FlandreCirno** [comment]
I understand the decision you made not to support Sponge. I know I have no right to question your decisions. I also understand that fixing this issue could mean a shift on the whole frame. But these is really no way to choose from between AE2 and Sponge, as Sponge is almost the only way to get server necessities in a moded server with 1.12.2. I appreciate that if you could take consideration of fixing this issue.
