### ISSUE TITLE
JEI Synchronization QoL Improvements (not hotkey suppression)

### ISSUE THREAD

**Issue by temp1029** [AppliedEnergistics/Applied-Energistics-2#3686]
I’d like to see better text handling in the terminals when JEI sync options are selected. I saw previous issues here asking for suppression of hotkeys when typing and understand why that’s not possible, but I’m looking for things like the home and end keys to work, shift + arrow keys to highlight, etc.

Also, when using things like ‘@‘ to search for items from a given mod, I noticed putting any terms after the mod name causes nothing to be displayed. For example, if I type ‘@actually’ I get all Actually Additons items, but if I type ‘@actually restonia’ I get nothing in the terminal window (although it does work in JEI. If this isn’t intended behavior I can provide more details of my setup if desired.

Thanks for your hard work and a great mod!

**Comment by yueh** [comment]
We just reuse the textfield provided by forge/minecraft. Thus better direct this feature request to them. Especially as it would benefit every mod out there.

Filter in AE2 is simply not as advanced as with JEI. So it will search for the full string (e.g. `@actually additions` would only search for actually additions and not any other mod with actually as part of the mod name and additions as item name).
On the plus side we don't need 2-3GB additional memory like JEI does in common packs to achieve its search functionality.

**Comment by temp1029** [comment]
Just as a point of clarification, the special keys (home, end, etc) work when not in JEI sync mode, so I think it’s an issue with the way AE does the JEI sync, not a problem with the forge text field.

Makes sense on the JEI-like filters, no need for all that overhead really!
