### ISSUE TITLE
CCL has caught an exception whilst rendering a block

### ISSUE THREAD

**Issue by CraXyOW3** [AppliedEnergistics/Applied-Energistics-2#3689]
All so often i get a CCL caught an exception rendering block, message and after a random set of times getting it, game crashes.
Tbh i am not 100% sure it is an AE2 issue, so often MC crashlogs can for me atleast, be cryptic.

> [Chunk Batcher 1/ERROR]: 
>  CCL has caught an exception whilst rendering a block
>   BlockPos:      x:2542, y:92, z:-1061
>   Block Class:   class appeng.block.networking.BlockCableBus
>   Registry Name: appliedenergistics2:cable_bus
>   Metadata:      0
>   State:         appliedenergistics2:cable_bus
>  Tile at position
>   Tile Class:    class appeng.tile.networking.TileCableBus
>   Tile Id:       appliedenergistics2:blockcablebus

[https://pastebin.com/SLW6JYxQ](https://pastebin.com/SLW6JYxQ)

Post edited as requested.

**Comment by mindforger** [comment]
Please for the sake of readability, Never post such a wall of text and split it into two pastesbins, also the link seems broken. 

Please edit your post :)

**Comment by yueh** [comment]
ExtraCells issue.
