### ISSUE TITLE
Cert error for ae2.ae-mod.info

### ISSUE THREAD

**Issue by Gaelan** [AppliedEnergistics/Applied-Energistics-2#3692]
#### Description
ae2.ae-mod.info has a cert error (giving a cert for ae-mod.info with no subdomain). Looks like the subdomain isn't required anymore, but it's probably good to have it working for old links/bookmarks (I personally typed the URL in from memory). I think Let's Encrypt might issue wildcards now, but it shouldn't be too hard to get a second cert for the subdomain either. Obviously not a hugely higher-priority thing, but it would be nice to not have the confusion there.

**Comment by mindforger** [comment]
i am wondering why there even is this subdomain?! it seems to reflect the exact same content as the address without any subdomain!?
