### ISSUE TITLE
NPE with Wireless Crafting Terminal

### ISSUE THREAD

**Issue by Shybella** [AppliedEnergistics/Applied-Energistics-2#3693]
#### Description

Server crash with Wireless Crafting Terminal steps to reproduce below.

1. Obtain a Wireless Crafting Terminal
2. Open the Wireless Crafting Terminal (Make sure it's linked)
3. Type 64 quickly with auto-search enabled

#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv5-stable-11
- Forge Version: 2739

Crash Report: https://pastebin.com/raw/jn9WtSMt

If you need any additonal information, let me know.

Thank you.

**Comment by yueh** [comment]
We do not support Sponge officially.

Should you be able to reproduce it without it, please update the issue accordingly and we will reopen it.

**Comment by Shybella** [comment]
I can confirm this does still happen with Spongeforge uninstalled.

The stack trace also has nothing to do with Spongeforge.

If you need anymore information, please let me know.

**Comment by fscan** [comment]
Does this happen in the wireless terminal or the normal terminal? If it's only the wireless *crafting* terminal, please report to https://github.com/p455w0rd/WirelessCraftingTerminal as this is not our mod.

**Comment by Shybella** [comment]
Oh, yes. You are correct, this is the wrong place to report.

Thank you.

**Comment by p455w0rd** [comment]
this would be so much easier if you guys got RV6 out...no one ever reports which RV version they're using...i'm going to ignore this on my end since I cannot reproduce and this whole RV6 being on CF has been nothing but headache after headache for me
