### ISSUE TITLE
[Question before complete Report]might encounter an performance issue with large storage crates from actually additions

### ISSUE THREAD

**Issue by mindforger** [AppliedEnergistics/Applied-Energistics-2#3696]
i am playing Sevtech Ages with some friends and noted some performance issues while one player was dumping his mining loot into the ME system

and going by my experience and the setup containing several storage busses with oversized large storage crates from actually additions, I seemingly solved it with an energy cell, but sevtech is hiding it in late game and revoked an investigation about my issue, so i want to make a waterproof test and report for them to make em move it to prior ages

edit: the ME system runs obviouslly out of power when doing so much importing of items and then creates lag by reevaluating the storage busses i guess

can you tell me a good tool to inject into the server to make a performance analysis? its running on linux and i have not so much experience in how to sample performance stuff with linux based OS

PS: i am still strongly voting for an indicator in any GUI that the ME system it was attached to had power issues in the last 5 seconds or so, to indicate people power issues more clearly

**Comment by mindforger** [comment]
i resorted to run visualvm directly on my machine, this should make the TPS drop more obvious

**Comment by Pingger** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2363
https://github.com/Buuz135/Industrial-Foregoing/issues/266

It seems to be an issue with AE2 adding each item individually causing the storage block to send an update for every item added/removed which then causes the lag

**Comment by mindforger** [comment]
i am pretty sure it is an power issue this time, that is why i want to profile it, adding the power cell reduced that problem always completely and repeadately push pulling large number of items made it worse, you could see the sky lagging whenever the push or pull did not succeed 100%

but i need reliable data
