### ISSUE TITLE
ME Conduits do not join with EnderIO ME Conduits on server start

### ISSUE THREAD

**Issue by Merung-Kelsith** [AppliedEnergistics/Applied-Energistics-2#3697]
#### Description
I use EnderIO conduits for most of my cabling, but since the  EnderIO cables cannot connect to AE2 Import/Export busses I use the AE2 version of the conduits at the termination of each line.  I have found that when I initially start my server, a few of the connections between my EnderIO ME Conduits and AE2 ME Conduits  at termination are not connecting.  I can easily fix this by either removing/replacing the AE2 conduit OR right clicking the EnderIO conduit connector and toggling it off and back on.  This only happens in a few places, and it is usually the same place at each server boot.  What this means is each time I start the server I have to go through my entire network, looking to see which conduits need to be reset.

#### Environment
FTB Revelations mod pack

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: 14.23.4.2738

**Comment by yueh** [comment]
EnderIO conduits were always a bit tricky, e.g. blocking any future connection in case a neighboring block only allows delayed connections. A chunk with an conduit being loaded before the normal cable might cause it, but there is nothing on our side to change it.
