### ISSUE TITLE
Crash with AE2 and Spatial Compat

### ISSUE THREAD

**Issue by lays24mc** [AppliedEnergistics/Applied-Energistics-2#3705]
Hi,

my game crasehd when I used AE2 and Spatial Compat, but i don't know it is a problem with AE2 or Spatial Compat. (sry for my bad english)

Crashlog: https://pastebin.com/r6EjkUnL

- Minecraft Version: 1.12.2 
- AE2 Version: appliedenergistics2-rev5-stable-11
- Forge Version:  14.23.4.2751
- Spatial Compat 1.12.2-1.3

**Comment by mindforger** [comment]
somebody (i doubt it's AE2 itself) tries to use the industrial craft api, but there is no industrial craft present, maybe there is a config for the spatial compat
