### ISSUE TITLE
Autocrafting support for complex crafting

### ISSUE THREAD

**Issue by golyalpha** [AppliedEnergistics/Applied-Energistics-2#3707]
#### Description
Some mods have multiblock structures for crafting, and these multiblock structures sometimes have separate input points for different ingredients of the crafting recipe. A great example is the Rolling Machine in Advanced Rocketry, which creates plates from various materials.  

To create a plate, you need to provide it with 100 mB of Water + one Ingot of the material per plate.  
The issue comes when you try to integrate this into the AE2 autocrafting system, because you actually need to interact with two different places on the multiblock in order to start making it.  
You need to fill up the fluid hatch with water, and one of the two input hatches with the desired source material. Then you have separate output hatches which you take the finished product out of. That is not a job for a single interface, at least not as I know it.

If there actually is a way, that doesn't involve throwing more mods at the issue, and I am oblivious to it, then I'd love to know.

**Comment by 5t0rmr1d3r** [comment]
Did you tried it with:
 interface(recipe)->interface->cable->exporter(restricted)->machine input?

**Comment by mindforger** [comment]
if i do not have additional mods like EIO providing item cables with filters, i make ad-hoc networks instead, they have no controller, only an input interface (like @5t0rmr1d3r described) which accept items from the Me network interface, an configured storage buses attached to the ports of the machine (i don't know if export busses can work that way i always believed they can't act as an storage target and i never tried)

**Comment by golyalpha** [comment]
@5t0rmr1d3r And then machine output importers connect to which network, the one before the interfaces (The one where my storage and terminals are), or the one after the interfaces (the one where the machine is)?

**Comment by 5t0rmr1d3r** [comment]
@golyalpha to the one with the recipe, this one has to count the produced items...
