### ISSUE TITLE
[1.12.2] Crash with C. Q. cutting knife

### ISSUE THREAD

**Issue by TheSnowyChickens** [AppliedEnergistics/Applied-Energistics-2#3708]
I screwed in the config.
![grafik](https://user-images.githubusercontent.com/29357962/44966464-9c005980-af3b-11e8-8ba3-bf6de225ea3c.png)

#### Description
This crash is, I think, already a long time in your mod.

#### Environment
Modpack, 150 Mods
Singleplayer, game start
crash log -> https://paste.dimdev.org/cemafexulo.mccrash

- Minecraft Version: 1.12.2
- AE2 Version: RV6 Alpha 4
- Forge Version: 2759

**Comment by Pingger** [comment]
This looks like you are using an outdated config, where the Q Cuttingknife is named deifferently. 

Have you tried deleting the config and let forge create a new one?

**Comment by TheSnowyChickens** [comment]
@Pingger I installed AE2 RV6 Alpha 4 new in my Modpack.
So this is the first config. (the new facade config is the right one)

**Comment by TheSnowyChickens** [comment]
And a new discovery, if I disable the silicon -> crash on start up

https://paste.dimdev.org/isosuyatug.mccrash

**Comment by TheSnowyChickens** [comment]
Rly different? Its under the category "config -> crash" ( :D ) , and the first and second crash is in this category.

**Comment by TheSnowyChickens** [comment]
@yueh Hi again,
recently I disabled the tools again and got, again, I think the same crash. :/

MC: 1.12.2
Forge: 2815
AE2: Rv6 - stable 6

![grafik](https://user-images.githubusercontent.com/29357962/53688283-2cc8be00-3d42-11e9-924f-c7a983e6d86a.png)

[crash-2019-03-02_23.18.45-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/2922552/crash-2019-03-02_23.18.45-client.txt)
