### ISSUE TITLE
[1.12.2] Facade hiding in JEI

### ISSUE THREAD

**Issue by TheSnowyChickens** [AppliedEnergistics/Applied-Energistics-2#3709]
Can you add back the config option, to Hide the Facades in JEI ? (but pls with the version, that 1 facade is still visible, for crafting. :) )

If this is still implemented and I just don't see it, pls tell me. (JEI Item hiding mode hide sadly ALL)

- Minecraft Version: 1.12.2
- AE2 Version: RV6 Alpha 4
- Forge Version: 2759

**Comment by Tahakk** [comment]
You can hide them yourself (just learned few days ago) -> https://gfycat.com/WatchfulSmallGrayreefshark
works like a charm

> also, disable those colored cabels, much more clean after that ;)

**Comment by TheSnowyChickens** [comment]
@Tahakk Yes, I used the JEI feature, but ALL Facades are now hidden. 
I asked the Refined Storage dude for creating a config for the facades in RS and he added it, but so that 99,9% of all facades are hidden, only 1 type (stone) is visible, so that we can see the crafting recipe. :)

**Comment by Tahakk** [comment]
It would be great to get one facade Item as cycling with all possible block, but hard to say if it is possible even

**Comment by yueh** [comment]
#899

**Comment by TheSnowyChickens** [comment]
Come on xD #899 is 3 years old.

**Comment by bookerthegeek** [comment]
#Heyo
@yueh That other issue is not only 3 years old but also for a different outdated version of minecraft that is EOL for modder support. And the mod mentioned in it (InPure Core) is not for 1.12.2

So... I was wondering if it would be possible to add a config option to hide every facade except one from JEI/NEI?

Yes I saw the video but that is an all or nothing option. I'd still like one facade to show up hopefully with a description about how most blocks will work for facades they just are not in JEI/NEI

**Comment by Dimentive** [comment]
Hold Ctrl and left-click one of the facades in JEI with “hide ingredients mode” enabled. Then, left-clicking (while _not_ holding Ctrl) one of the facades, and only that one will show up in JEI once you disable hide ingredients mode.

**Comment by Dimentive** [comment]
I know I’m late, but in case anyone needs help with this, here’s how to hide all Applied Energistics 2 facades except one in JEI: Hold Ctrl and left-click one of the facades in JEI with “hide ingredients mode” enabled. Then, left-clicking (while _not_ holding Ctrl) one of the facades, and only that one will show up in JEI once you disable hide ingredients mode.

**Comment by TheSnowyChickens** [comment]
Ahh good to know, this tutorial worked. :)

Thx
