### ISSUE TITLE
Visual glitch with new alpha facades

### ISSUE THREAD

**Issue by PanSzelescik** [AppliedEnergistics/Applied-Energistics-2#3711]
#### Description
I have visual glitch with facades using CTM (tested with: chisel:lavastone:7 and chisel:lavastone:11 and chisel:cobblestone2:7)
![image](https://user-images.githubusercontent.com/26679785/44990197-98e38880-af90-11e8-9793-fc98629c5b0f.png)
![image](https://user-images.githubusercontent.com/26679785/44990529-93d30900-af91-11e8-9b6c-db7a72a9629c.png)

#### Environment
- Minecraft Version: 1.12.2
- AE2 Version: rv6-alpha-4
- Forge Version: 14.23.4.2758
- CTM: MC1.12.2-0.3.2.18
- Chisel: MC1.12.2-0.2.0.31

**Comment by PanSzelescik** [comment]
Optifine bug :/

**Comment by TheSnowyChickens** [comment]
@PanSzelescik 
1. Nice profil picture xDD - I like it^^
2. Can you open a issue at Optifines Github for this bug?

**Comment by PanSzelescik** [comment]
1. Thanks xD
2. Yes ;-)
