### ISSUE TITLE
[1.12.2] Inscriber don't accept oreDic for silicon

### ISSUE THREAD

**Issue by TheSnowyChickens** [AppliedEnergistics/Applied-Energistics-2#3712]
Your default inscriber recipe don't has a oreDic entry for (in my case) RefinedStorage Silicon, I tried to create a recipe with CraftTweaker / ModTweaker : ...

![grafik](https://user-images.githubusercontent.com/29357962/44996577-e9ff7680-afa8-11e8-8a2a-e34ad0b0422c.png)

But this also don't work.

#### Environment
Modpack, 150 Mods
Singleplayer

- Minecraft Version: 1.12.2
- AE2 Version: RV6 Alpha 4
- Forge Version: 2759

**Comment by yueh** [comment]
The [default recipe](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv6-1.12/src/main/resources/assets/appliedenergistics2/aerecipes/inscriber/silicon_print.json) accepts any oredict `itemSilicon`.

They might simply not register theirs under this name or something else removes these recipes afterwards.

**Comment by Tahakk** [comment]
This is duplicate that was already posted but both mods said it is fault of the other.
https://github.com/raoulvdberge/refinedstorage/issues/1814
#3534

Cost continue to ignore it on both sides, never get's resolved prolly. Personally never had any issues with silicon so...

**Comment by fscan** [comment]
Like in normal json recipes, oredict entries for inscriber recipes are resolved at recipe registration time. If you register oredict in the item registration event (as [suggested by lex](http://www.minecraftforge.net/forum/topic/60426-112-what-event-should-ore-dictionary-registrations-happen/?tab=comments#comment-281737)  ), everything should be fine.
In 1.13 the tag system will probably fix this whole mess..

**Comment by raoulvdberge** [comment]
Fixed in https://github.com/raoulvdberge/refinedstorage/commit/78703611bb9a64f817fb39dfbc2d3f18989c36ac.

**Comment by TheSnowyChickens** [comment]
Ahh okay. Ty
