### ISSUE TITLE
Missing textures 

### ISSUE THREAD

**Issue by Wreav66** [AppliedEnergistics/Applied-Energistics-2#3715]
To be quick and honest im attempting to put a small mod pack together and during experimenting and playing around i noticed a few textures were missing i tried to search for fixes myself but i either didnt get it due to technical chatter or couldnt find something helpful
http://prntscr.com/kqfh42
http://prntscr.com/kqfhci
Pages 10-30 close to none are textured

If additional info is needed or other means to fix this is needed please let me know 
Thanks !

- Minecraft Version: 1.12.2
- AE2 Version: Rv6 Alpha 4 and several previous versions
- Forge Version: 14.23.4.2739

**Comment by Aquahatsche** [comment]
You said you are using the alpha builds. Alpha means, they are unstable and for testing only. Did you try any version of the stable-branch?

**Comment by covers1624** [comment]
This is due to the model for what ever block those facades are made out of, is either invalid or wasn't loaded properly. There's probably not much that can be done about this, what blocks are those facades made from?

**Comment by PanSzelescik** [comment]
Propably this is from Chisel

**Comment by Wreav66** [comment]
yes i used the top 3 stable builds for 1.12.2 and as for the facades i believe they are all from Applied energistics but i am unsure how to properly check that if i did not when i showed the screen shots

**Comment by Aquahatsche** [comment]
Press F3 + H to show the advanced tooltips. Then hover over the items. Maybe that shows more about the items

**Comment by Wreav66** [comment]
this is what i got after trying F3 + H http://prntscr.com/kqtps8 
i dont really understand all that though

**Comment by Wreav66** [comment]
i removed the chisel mod and everything ended up being fine what i dont get is why ? any ideas how to keep it and the other mods or best left out ?

**Comment by covers1624** [comment]
The issue here is that the Chisel block the facade is made from doesn't have a model, so the standard Missing model gets assigned, hence the 'missing' texture, the facades are fine, they are just working with the data they are provided. Perhaps @mezz can shed some light or give some pointers on how users can edit the JEI panel and hide items. (if they cant, feature suggestion!)

**Comment by Aquahatsche** [comment]
For me the chiseled facades work. Sometimes there is something missing on the texture (e.g. moss on mossy stone). There is a config file in the ae-subfolder where you can disable facades.

**Comment by Wreav66** [comment]
what would be the best course of action ? disable it see if anyone else or that mods creator has an idea or see about finding those models ? which i dont know where to look for them

**Comment by yueh** [comment]
Cannot reproduce, no missing textures with AE2 and Chisel alone.

**Comment by Wreav66** [comment]
how do i go about it then ?
