### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by GizliKodcu** [AppliedEnergistics/Applied-Energistics-2#3719]
#### Description
https://paste.dimdev.org/exudanepus.mccrash
#### Environment
Latest version of FoolCraft3 modpack, added latest version of Flans alongside with Simple Part(Version: 5.5.2) and Modern Warfare(5.5.2) content pack. Crash occured after i first open the game with these Flans stuff.
Single player world

- Minecraft Version: 1.12.2
- AE2 Version: rv6 Alpha 3
- Forge Version: 14.23.4.2758

**Comment by fscan** [comment]
A mod has claimed our spatial dimension (2 in your case, we autodetect a free dimension at first start). Find out which mod and change their id's or ask them to fix this behaviour.
