### ISSUE TITLE
Crafting bug with storage cell

### ISSUE THREAD

**Issue by Mugiwaxar** [AppliedEnergistics/Applied-Energistics-2#3721]
#### Description
When I try to auto-craft storage cell (1k, 4k, 16k,...), the process stop on the last cell and freeze,
then, I can't craft any other cell. What I get:
![scrs2](https://user-images.githubusercontent.com/4124999/45236593-8d6bc680-b2dc-11e8-8364-ea3521aaadd8.png)

This is the craft pattern:
![scrs1](https://user-images.githubusercontent.com/4124999/45236601-965c9800-b2dc-11e8-9acd-4027d532e9a1.png)

#### Environment
Server-Multiplayer
Ftb Revelation Modpack

- Minecraft Version:  1.12.2
- AE2 Version:  rv5-11
- Forge Version:  14.23.4.2759

**Comment by fscan** [comment]
This is a known bug and fixed in git.
