### ISSUE TITLE
Crash on Serverstart

### ISSUE THREAD

**Issue by efinder2** [AppliedEnergistics/Applied-Energistics-2#3723]
#### Description
We've update our Server from rv5-alpha-8 to Crash on rv5-stable-11. (in Modpack Modern Sykblock 3). If I start the Server with a new world everything is Ok. Only if I start the existing world the server will crash.

#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: 14.23.4.2749 
- Pack: Modern Skyblock 3
- Location: Server
- Crashlog: https://pastebin.com/gt9HPSjM

We've just started wit AE2. We have a little bit Autocrafting, Advanced Inscriber (automated), Wireless Crafting Teminals. Wired Crafting terminals on the whole Island.

**Comment by yueh** [comment]
This is actually a crash caused by yabba (more likely) or Astral Sorcery while attaching their itemstack caps.
