### ISSUE TITLE
Exception from AE launching

### ISSUE THREAD

**Issue by Niilyx** [AppliedEnergistics/Applied-Energistics-2#3726]
#### Environment

- Minecraft Version: 
- AE2 Version: latest
- Forge Version: latest

Here's the crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.37.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-85.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 9/20/18 10:29 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Energistics 2 (appliedenergistics2)
Caused by: java.lang.IllegalArgumentException: Failed to register dimension for id 2, One is already registered
	at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:134)
	at appeng.core.Registration.registerSpatialDimension(Registration.java:222)
	at appeng.core.Registration.postInit(Registration.java:397)
	at appeng.core.AppEng.postInit(AppEng.java:252)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 676550848 bytes (645 MB) / 2818572288 bytes (2688 MB) up to 2919235584 bytes (2784 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2780M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2759 64 mods loaded, 64 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                | Version           | Source                                             | Signature                                |
	|:------ |:--------------------------------- |:----------------- |:-------------------------------------------------- |:---------------------------------------- |
	| UCHIJ  | minecraft                         | 1.12.2            | minecraft.jar                                      | None                                     |
	| UCHIJ  | mcp                               | 9.42              | minecraft.jar                                      | None                                     |
	| UCHIJ  | FML                               | 8.0.99.99         | forge-1.12.2-14.23.4.2759.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ  | forge                             | 14.23.4.2759      | forge-1.12.2-14.23.4.2759.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ  | micdoodlecore                     |                   | minecraft.jar                                      | None                                     |
	| UCHIEE | appliedenergistics2               | rv5-stable-11     | appliedenergistics2-rv5-stable-11.jar              | None                                     |
	| UCHI   | codechickenlib                    | 3.2.1.351         | CodeChickenLib-1.12.2-3.2.1.351-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHI   | redstoneflux                      | 2.0.2             | RedstoneFlux-1.12-2.0.2.3-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHI   | brandonscore                      | 2.4.4             | BrandonsCore-1.12.2-2.4.4.173-universal.jar        | None                                     |
	| UCHI   | buildcraftlib                     | 7.99.18           | buildcraft-7.99.18.jar                             | None                                     |
	| UCHI   | buildcraftcore                    | 7.99.18           | buildcraft-7.99.18.jar                             | None                                     |
	| UCHI   | buildcraftbuilders                | 7.99.18           | buildcraft-7.99.18.jar                             | None                                     |
	| UCHI   | buildcraftenergy                  | 7.99.18           | buildcraft-7.99.18.jar                             | None                                     |
	| UCHI   | buildcraftfactory                 | 7.99.18           | buildcraft-7.99.18.jar                             | None                                     |
	| UCHI   | buildcraftrobotics                | 7.99.18           | buildcraft-7.99.18.jar                             | None                                     |
	| UCHI   | buildcrafttransport               | 7.99.18           | buildcraft-7.99.18.jar                             | None                                     |
	| UCHI   | buildcraftsilicon                 | 7.99.18           | buildcraft-7.99.18.jar                             | None                                     |
	| UCHI   | chameleon                         | 1.12-4.1.3        | Chameleon-1.12-4.1.3.jar                           | None                                     |
	| UCHI   | ctm                               | MC1.12.2-0.3.2.18 | CTM-MC1.12.2-0.3.2.18.jar                          | None                                     |
	| UCHI   | chisel                            | MC1.12.2-0.2.1.34 | Chisel-MC1.12.2-0.2.1.34.jar                       | None                                     |
	| UCHI   | cofhcore                          | 4.5.3             | CoFHCore-1.12.2-4.5.3.20-universal.jar             | None                                     |
	| UCHI   | cofhworld                         | 1.2.0             | CoFHWorld-1.12.2-1.2.0.5-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHI   | thermalfoundation                 | 2.5.0             | ThermalFoundation-1.12.2-2.5.0.19-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHI   | draconicevolution                 | 2.3.13            | Draconic-Evolution-1.12.2-2.3.13.306-universal.jar | None                                     |
	| UCHI   | elevatorid                        | 1.3.6             | ElevatorMod-1.12.2-1.3.6.jar                       | None                                     |
	| UCHI   | endercore                         | 1.12.2-0.5.37     | EnderCore-1.12.2-0.5.37.jar                        | None                                     |
	| UCHI   | jei                               | 4.11.0.212        | jei_1.12.2-4.11.0.212.jar                          | None                                     |
	| UCHI   | thermalexpansion                  | 5.5.0             | ThermalExpansion-1.12.2-5.5.0.29-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHI   | enderio                           | 5.0.31            | EnderIO-1.12.2-5.0.31.jar                          | None                                     |
	| UCHI   | enderiointegrationtic             | 5.0.31            | EnderIO-1.12.2-5.0.31.jar                          | None                                     |
	| UCHI   | enderiobase                       | 5.0.31            | EnderIO-1.12.2-5.0.31.jar                          | None                                     |
	| UCHI   | enderioconduits                   | 5.0.31            | EnderIO-1.12.2-5.0.31.jar                          | None                                     |
	| UCHI   | enderioconduitsappliedenergistics | 5.0.31            | EnderIO-1.12.2-5.0.31.jar                          | None                                     |
	| UCHI   | enderioconduitsopencomputers      | 5.0.31            | EnderIO-1.12.2-5.0.31.jar                          | None                                     |
	| UCHI   | enderioconduitsrefinedstorage     | 5.0.31            | EnderIO-1.12.2-5.0.31.jar                          | None                                     |
	| UCHI   | enderiointegrationforestry        | 5.0.31            | EnderIO-1.12.2-5.0.31.jar                          | None                                     |
	| UCHI   | enderiointegrationticlate         | 5.0.31            | EnderIO-1.12.2-5.0.31.jar                          | None                                     |
	| UCHI   | enderiomachines                   | 5.0.31            | EnderIO-1.12.2-5.0.31.jar                          | None                                     |
	| UCHI   | enderiopowertools                 | 5.0.31            | EnderIO-1.12.2-5.0.31.jar                          | None                                     |
	| UCHI   | extrautils2                       | 1.0               | extrautils2-1.12-1.9.3.jar                         | None                                     |
	| UCHI   | flansmod                          | 5.5.2             | Flan's Mod-1.12.2-5.5.2.jar                        | None                                     |
	| UCHI   | flansmodapocalypse                | 1.0               | Flan's Mod-1.12.2-5.5.2.jar                        | None                                     |
	| UCHI   | forgemultipartcbe                 | 2.5.0.71          | ForgeMultipart-1.12.2-2.5.0.71-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHI   | microblockcbe                     | 2.5.0.71          | ForgeMultipart-1.12.2-2.5.0.71-universal.jar       | None                                     |
	| UCHI   | minecraftmultipartcbe             | 2.5.0.71          | ForgeMultipart-1.12.2-2.5.0.71-universal.jar       | None                                     |
	| UCHI   | galacticraftcore                  | 4.0.1.181         | GalacticraftCore-1.12.2-4.0.1.181.jar              | None                                     |
	| UCHI   | galacticraftplanets               | 4.0.1.181         | Galacticraft-Planets-1.12.2-4.0.1.181.jar          | None                                     |
	| UCHI   | ichunutil                         | 7.1.4             | iChunUtil-1.12.2-7.1.4.jar                         | None                                     |
	| UCHI   | mcjtylib_ng                       | 3.0.4             | mcjtylib-1.12-3.0.4.jar                            | None                                     |
	| UCHI   | mekanism                          | 1.12.2-9.4.13.349 | Mekanism-1.12.2-9.4.13.349.jar                     | None                                     |
	| UCHI   | mekanismgenerators                | 9.4.11            | MekanismGenerators-1.12.2-9.4.13.349.jar           | None                                     |
	| UCHI   | mekanismtools                     | 9.4.11            | MekanismTools-1.12.2-9.4.13.349.jar                | None                                     |
	| UCHI   | morph                             | 7.1.2             | Morphing-Mod-1.12.2.jar                            | None                                     |
	| UCHI   | nei                               | 2.4.1             | NotEnoughItems-1.12.2-2.4.1.238-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHI   | portalgun                         | 7.0.2             | PortalGun-1.12.2-7.0.2.jar                         | None                                     |
	| UCHI   | rafradek_tf2_weapons              | 1.3.8.2           | rafradek_tf2_weapons-1.12.2-1.3.8.2.jar            | None                                     |
	| UCHI   | rftools                           | 7.55              | rftools-1.12-7.55.jar                              | None                                     |
	| UCHI   | rftoolscontrol                    | 1.9.1             | rftoolsctrl-1.12-1.9.1.jar                         | None                                     |
	| UCHI   | simplefluidtanks                  | 1.12.2-1.7.1.1    | simplefluidtanks-1.12.2-1.7.1.1.jar                | None                                     |
	| UCHI   | thermaldynamics                   | 2.5.1             | ThermalDynamics-1.12.2-2.5.1.14-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHI   | simplyjetpacks                    | 2.2.7.45          | SimplyJetpacks2-1.12.2-2.2.7.45.jar                | None                                     |
	| UCHI   | storagedrawers                    | 1.12-5.3.5        | StorageDrawers-1.12.2-5.3.7.jar                    | None                                     |
	| UCHI   | thermalinnovation                 | 0.3.0             | ThermalInnovation-1.12.2-0.3.0.7-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHI   | immersiveengineering              | 0.12-85           | ImmersiveEngineering-0.12-85.jar                   | 4cb49fcde3b43048c9889e0a3d083225da926334 |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.37.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  team.chisel.ctm.client.asm.CTMTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-85.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 22.20.16.4708' Renderer: 'Intel(R) HD Graphics 620'
	AE2 Version: stable rv5-stable-11 for Forge 14.23.1.2554
	Ender IO: No known problems detected.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by mindforger** [comment]
Check your configs, you have another mod already using dimension 2, also for the next report please use pastebin to post the Log, this wall of text is quite painfull to read :) 

At least, if you find the other mod, please tell which mod it was, we never got back what the other mod is

**Comment by Uweb95** [comment]
The cause seems to be the Flansmod, I just got the same error after I installed it.
