### ISSUE TITLE
Memory Cards not working

### ISSUE THREAD

**Issue by X-Rader** [AppliedEnergistics/Applied-Energistics-2#3727]
#### Description

The Memory card only clears when right-clicking on a p2p tunnel instead of storing its configuration to 
the memory card or when you left-click to load the configuration from the memory card to a p2p tunnel.

In Singleplayer the memory card have suddenly stopped working. I Loaded an old world where I do some testing with AE2, and I noticed that the memory card was not working. I then loaded my survival world where It were working yesterday and when I tried it there, is also stopped working.  This happened last time when I upgraded to rv6-alpha-4 from rv-alpha-3. I just created a new world and everything worked fine.
I just wonder what is causing it to stop working, because I have not changed anything in the last week I was playing.
 
#### Environment

- Other mods use: 
  [1.12]UncraftingTable-1.8-beta6
  Advanced+Solar+Panels-4.2.0
  BBOutlineReloaded-1.0.3-mc1.12.2.forge
  BetterBuildersWands-1.12-0.11.1.245+69d0d70
  buildcraft-7.99.18
  ChickenASM-1.12-1.0.2.7
  ChickenChunks-1.12.2-2.4.1.71-universal
  CodeChickenLib-1.12.2-3.2.0.345-universal
  CoFHCore-1.12.2-4.5.3.20-universal
  CoFHWorld-1.12.2-1.2.0.5-universal
  CompactSolars-1.12.2-5.0.17.340-universal
  EnderStorage-1.12.2-2.4.2.126-universal
  FasterLadderClimbing-1.12-0.1-127
  ForgeMultipart-1.12.2-2.4.2.60-universal  
  ForgivingVoid_1.12.2-1.0.12
  industrialcraft-2-2.8.97-ex112
  jei_1.12.2-4.11.0.204
  journeymap-1.12.2-5.5.2
  LEDM+V.2.3.0
  MalisisCore-1.12.2
  MalisisSwitches-Mod-1.12.2
  MoreCommands-1.12.2-6.0
  mystcraft-1.12.2-0.13.6.00
  OptiFine_1.12.2_HD_U_E2
  RedstoneFlux-1.12-2.0.2.3-universal
  rsgauges-mc1.12.2-1.0.0-rc1
  ShulkerBoxViewer
  subcommonlib-sublib-1.12.2-1.2.0.4
  tekdrone-1.0
  Telepads-Mod-1.12.2
  Translocators-1.12.2-2.5.0.73-universal
  Treecapitator-1.12
  WorldEdit_CUI_Edition
  worldedit-forge-mc1.12-6.1.8-dist
  Xaeros_Minimap_1.15.6_Forge_1.12
  XRay-58-vDLB

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-alpha-4
- Forge Version: 1.12.2-forge1.12.2-14.23.4.2745

**Comment by yueh** [comment]
[Memory Card](https://ae-mod.info/Memory-Card/)

**Comment by Panzer1119** [comment]
This link is not helping. I have the same problem. Just updated from rv5-stable-11 to rv6-stable-1 and the old and linked p2p tunnels are working fine.
But when i right click on a (new crafted) p2p - ME tunnel with a (new crafted) memory card it says "Invalid Machine" and when i shift + right click somewhere it says "Memory card cleared."

**Comment by Codingale** [comment]
I also get this issue (no sponge) on 1.12.2 using the following mods
[ServerMods.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/3966014/server.1.txt)
and I'll post a debug.log if needed.

**Comment by Panzer1119** [comment]
Do you had any items in your off hand (the left hand in Minecraft)? Because i think this causes the bug, just remove any items from the off hand and try it again.

**Comment by Codingale** [comment]
Nope, I tried putting one in, then it only said it cleared it, with nothing it said it saved it then cleared it.

**Comment by shadowpanther** [comment]
With nothing in off-hand, it says:
```
Copied current device configuration to memory card.
Memory card cleared.
```
With something in off-hand, it says:
```
Memory card cleared.
```
Can anyone help? I'm on Tekxit 3 modpack multiplayer. I tried reconnecting and restarting the client, this didn't help.

**Comment by Accir** [comment]
Experiencing the same issue as @shadowpanther said.

The 1.12.2 pack, version 1.1.2
Multiplayer

**Comment by Codingale** [comment]
I still have the issue server mods are the same except updates

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Codingale** [comment]
I still have this issue, same server mods minus updates

**Comment by Ommina** [comment]
For giggles, I tried it out in a test world.

Yes, there is some weirdness surrounding having something in the offhand.  With offhand empty, however, it worked fine, as described in the link above.

My pack is certainly different than others'.  But if the behaviour is different in different packs, it does suggest a mod interaction, or, perhaps, a mod somewhere just not handling right-clicking as they should be.

**Comment by Codingale** [comment]
A suggested solution I've heard is to add a GUI slot for the card to be programmed and a button to save or load it. I'd be down for that over the right click issues we have now.

**Comment by Accir** [comment]
@Ommina i think it only happens on multiplayer servers

**Comment by Codingale** [comment]
I'm pretty sure every world is ran in a MP server now. (SinglePlayer too) 

And I also had this happen on SP I'm pretty sure.
