### ISSUE TITLE
Feature Request: Search History list

### ISSUE THREAD

**Issue by delta2k** [AppliedEnergistics/Applied-Energistics-2#3728]
please could you add search history with the ability to flick between the search history with programmable hotkeys to select up and down the list. just a quality of life feature

**Comment by delta2k** [comment]
well it could be done in the same way as refined storage does it and also remember for people with disabilities (including my self) who find it hard to keep typing or remembering this a huge QoL feature.

**Comment by yueh** [comment]
Accessibility would actually be something I'd really like to support. But it's simply not possible currently without some major flaws like not being persisted between world loads and similar limitations.

The GUIs really need some major rework to enable us to do these things more easily. Which sadly is a bit time constrained currently. But I'll certainly consider these things once we are able to rewrite it.

**Comment by delta2k** [comment]
thank you for at least considering it.
