### ISSUE TITLE
Cross server interaction

### ISSUE THREAD

**Issue by SinTh0r4s** [AppliedEnergistics/Applied-Energistics-2#3731]
Hi,

I am running a GregTech server (GT New Horizons) on a rather low end server with quite a lot of cores and RAM. Since minecraft requires single core performance my server has not exactly the best specs.
But if i could run a second server, connect them over bungeecord and offload quarries and other tick heavy automatation i could basically multiprocess my server to get overall better performance. It would be quite the overhead to releave the main server, but since my CPUs idle anyway i thought i should be worth it.

For machienery to interact over two servers all that would be required is an ME system with autocrafting. No P2P or similar, just ME.
I have some experience in java but mostly in small applications. So i tried to look into the AE2 code and found an EventBus.

I have the question if it would be sufficient to "simply" relay events over tcp to the second servers to get those ME systems to act as one.
Or how much more would be necessary to somewhat get that functionality. Even if it would introduce lag of a second or two it should not really matter for automated factories.

Sincerely,
SinTh0r4s

**Comment by yueh** [comment]
In general we won't support anything other than forge. But the short (or rather long) answer would be to completely reimplement AE2 yourself.
