### ISSUE TITLE
Flour with AE2, Ender IO, and Thermal Expansion: I searched the issue but the last one was ended prematurely

### ISSUE THREAD

**Issue by MtnDrew** [AppliedEnergistics/Applied-Energistics-2#3735]
When the trifecta of Applied Energistics 2, Ender IO, and Thermal Expansion are installed, the pulverizer from TE will try to produce AE2 flour from wheat, but AE2 flour is disabled because of Ender IO.

I am using the most recent release verion of AE2, not the beta. Also using the most recent versions of TE and IO.

Pretty simple to reproduce, just install all 3 mods and try to pulverize wheat.

Is there a way to stop AE2 from disabling flour? I'm fine with having both versions since i usually cook it immediately anyway. It's a better option then getting a weird invisible disabled item that doesn't do anything.

Cheers, mates, I've been using your mod forever and consider it a staple of any personal modpack I build.

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: 2759 (latest as far as I know)

**Comment by yueh** [comment]
Forge requires that we register recipes before we can even detect if they are needed. If you're lucky, 1.13 will make it impossible and disabling items/blocks will no longer be possible, for now just use the config for it.
