### ISSUE TITLE
Fluix Seeds Won't be "Requested" Nor "Viewed as There" but They are Craft Able if Manually Requested

### ISSUE THREAD

**Issue by FriendlySurvival** [AppliedEnergistics/Applied-Energistics-2#3736]
Basically when a recipe calls for Fluix seeds like to process them in a machine they won't be requested and thinks they are missing. I MADE sure that they do craft automatically and even then the AE2 network WILL not pull even if there are seeds ALREADY in the network!

It's exactly like trying to tell it to make a chest and it saying it's out of planks when there logs. And if there were to be planks it's not "seeing" them. But instead of that it's these seeds...

- Minecraft Version:1.12.2 
- AE2 Version:v5 Stable 11
- Forge Version: Ending in 2759  
Another major mod I have is Mekanism v9 ending in 349 as well. But I had and still can make this mod things just fine...
![2018-09-26_00 49 06](https://user-images.githubusercontent.com/38051855/46059949-521c2500-c12f-11e8-910c-d1253a80ca52.png)
![2018-09-26_00 49 18](https://user-images.githubusercontent.com/38051855/46059950-521c2500-c12f-11e8-93e3-8863669e9013.png)
![2018-09-26_00 49 28](https://user-images.githubusercontent.com/38051855/46059951-521c2500-c12f-11e8-877e-de4c7865fbe5.png)

**Comment by yueh** [comment]
The items required by the pattern do not match with the ones produced. This is mostly caused by patterns encoded by addons, spawned items, or similar.

**Comment by FriendlySurvival** [comment]
I did that multiple times though. I re coded the pattern using the un separated stack and it still will shows that on the network.  

So if I used a "clean" stack from the one that was autocrafted then why it still doing this?

**Comment by yueh** [comment]
Hard to tell, we had a few mods in the past, which would add random data to itemstack. Say in case a player picked them up or similar, which forces us to no longer consider them being the same item as some mods use the same approach to distinguish between most/all of their items. Thus we would start using their low tier items as replacement for high tier ones or similar.

1.13 could make it technically way easier, yet I sadly expect some mods will still try and work around it, thus making it much harder for everyone else.

In your case I also cannot simply recommend to start removing mods until it no longer happens, as this data will be persistent even after removing a potentially offending mod. The only way is pretty much to start from scratch with an instance only containing AE2, setting up the crafting process and then slowly adding different mods each start until it reappears. Be sure to make a initial copy of a working world, so you can restore it for every try. Hopefully it should make it possible to identify any mod interfering with it.
As tip, starting with the lesser known mods is probably a good idea as they usually are a bit less tested.

**Comment by FriendlySurvival** [comment]
I see and once I DO find that mod, would a server reset be required because of the persistence data? Or will it "go away" for any new crafted seeds as long as I reset both patterns?

**Comment by yueh** [comment]
It would only affect old stacks. But another mod interfering is just a guess, nonetheless that or an incorrect pattern is pretty much the only cause.
