### ISSUE TITLE
In "Easy Mode", devices added to the network affects removal of items from terminal

### ISSUE THREAD

**Issue by Orichlol** [AppliedEnergistics/Applied-Energistics-2#3738]
#### Description
Expected Behavior:   In "easy mode" (no channels), I can add as many devices via Glass Cables to the network as I want without repercussion or "channel oversubscription"

Actual Behavior:  If I go over some threshold of channels (very low, I think 16 or 32), every additional device I add to the network actually lowers the amount I can "shift click" or "left click" remove out of the AE terminal in terms of the size of the stack.

(ie.  With limited devices, I can remove a stack of cobblestone as qty:64.   After some threshold (8/16/32, i didnt count specifically, but its not large) devices on the glass cable, each additional device I add lowers the amount I can remove a stack by 1.  After 64 additional devices, you can't remove any items from the ME terminal)

#### Environment

ATM3 Remix is the modpack (v. 0.0.3, latest)

- Minecraft Version: 
- AE2 Version: rv5-stable-11  (ATM3 Remix)
- Forge Version:  2760

**Comment by yueh** [comment]
This is the expected behaviour for running out of power.

**Comment by mindforger** [comment]
>Nevermind, it looks to be a bug with the interaction between Quantum Entangloporter and the Energy Acceptor. 


Nope, power input simply is limited by System energy capacity

**Comment by Orichlol** [comment]
> 
> 
> > Nevermind, it looks to be a bug with the interaction between Quantum Entangloporter and the Energy Acceptor.
> 
> Nope, power input simply is limited by System energy capacity

Hmm?  What determines the system energy capacity?

**Comment by mindforger** [comment]
Correct, you need to provide a buffer of some size and as AE is scalable, so is the buffer.
