### ISSUE TITLE
Crash to Launcher (AE Wireless Terminal)

### ISSUE THREAD

**Issue by PiggyWhiskey** [AppliedEnergistics/Applied-Energistics-2#374]
I've experienced a repeatable crash when accessing AE2 Wireless Terminal.

Steps:
1. Open Wireless Terminal within range.
2. Quickly switch to another inventory (I used Golden Bag of Holding)
3. Open other Inventory.

Game will freeze, then crash to Launcher.

http://pastebin.com/NYMzGiy2
http://pastebin.com/tpbj3jPe

**Comment by PiggyWhiskey** [comment]
Playing Dark Trilogy with AE RV2-Beta-1

Issue still exists
http://paste.ee/p/i9Spo

**Comment by thatsIch** [comment]
new one is open here https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/574
