### ISSUE TITLE
rv6-alpha-4 breaks OpenComputers integration in export bus

### ISSUE THREAD

**Issue by arketec** [AppliedEnergistics/Applied-Energistics-2#3741]
#### Description

I'm playing on a Foolcraft 3 server that was just updated and AE was updated to rv6-alpha-4. 

Now, when trying to use the OC integration:
`component.me_exportbus.exportIntoSlot(side,slot)`

it fails to export and I get this message:

`appeng.api.storage.channels.IItemStorageChannel.poweredExtraction(Lappeng/api/networking/energy/IEnergySource;Lappeng/api/storage/IMEInventory;Lappeng/api/storage/data/IAEStack;Lappeng/api/networking/security/IActionSource;)Lappeng/api/storage/data/IAEStack;`

#### Environment

Modpack: Foolcraft 3 v1.5.4
SMP server

- Minecraft Version: 1.12.2
- AE2 Version: rv6-alpha-4
- Forge Version: 14.23.4.2760

**Comment by yueh** [comment]
There isn't any OC integration on your side. As far as I remember it is/was added by OC itself.

**Comment by arketec** [comment]
ok thanks, I'll let them know
