### ISSUE TITLE
[Feature Suggestion] Remote Crafting Monitor for crafting CPU multi-block structures

### ISSUE THREAD

**Issue by Sol-on-github** [AppliedEnergistics/Applied-Energistics-2#3745]
Should add a monitor to remotely display what a crafting CPU multi-block is working on. Could be linked to a crafting CPU with a memory card.

**Comment by yueh** [comment]
This is already part of the ME Terminal, ME Crafting Terminal and Wireless Terminal.

**Comment by mindforger** [comment]
@yueh I think what he meant was more like a Version of the crafting CPU Monitor that can be placed somwhere else, like the storage monitors

**Comment by Pingger** [comment]
This is probably not the type of monitor, he imagined. I think he wants something, like that block for the CPUs, that displays the item without having to 'open' it

**Comment by Sol-on-github** [comment]
@yueh you have misunderstood what I meant or maybe I did a poor job of explaining it.
@mindforger & @Pingger are correct.
[Here are some pictures to help explain.](https://imgur.com/a/N606v7e)

**Comment by Pingger** [comment]
@yueh can we reopen this?
