### ISSUE TITLE
Cutting knives with damage do not function

### ISSUE THREAD

**Issue by incomingnerd** [AppliedEnergistics/Applied-Energistics-2#3746]
#### Description

A cutting knife with less than full durability will not craft cable anchors.

To reproduce:
1. Craft a cutting knife (certus or nether quartz).
2. Craft cutting knife with an iron ingot - cable anchor will be created.
3. Attempt to craft cutting knife with another ingot - observe no output/recipe match.

#### Environment

Tested with a fresh MC+Forge installation from Twitch launcher.

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-1
- Forge Version: forge-14.23.4.2765

**Comment by Skaronator** [comment]
Can confirm that.

**Comment by yueh** [comment]
This is basically a forge bug. Nothing we can really do besides choosing between not working or have the alternative crash during load.

**Comment by blockbreaker1361** [comment]
Can confirm this.
https://imgur.com/AoHtTz9
https://imgur.com/7maAO9O
