### ISSUE TITLE
Crash on launch - New modpack

### ISSUE THREAD

**Issue by Halkhan** [AppliedEnergistics/Applied-Energistics-2#3749]
rv6-stable-1 causes crash during load.
rv5-stable-11 works without incident

#### Description
During load of game I crash and get the error below. I have used rv5-stable-11 without this crash. I can't be 100% certain the source of the crash. It looks like a AE2 issue since I can use an older version

Put this modpack together yesterday and in the process of working out the kinks. This crash happened after updating mods. I updated AE2 and tried before updating other mods after initial crash.

Uninstalled rv6 and installed rv5 and it works fine.

#### Environment
Single player - i7 8th gen, 16gb ram. 
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  FarseekCoreMod (Farseek-1.12-2.3.1.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  HCASM (HammerCore-1.12.2-2.0.2.3.jar)
  BCModPlugin (backpacks 1.12.2 - 3.5.4.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.39.jar)
  EECore (Expanded-Equivalence-Mod-1.12.2.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 9/30/18 12:19 PM
Description: Initializing game

java.lang.NoSuchMethodError: appeng.api.storage.ICellRegistry.getCellInventory(Lnet/minecraft/item/ItemStack;Lappeng/api/storage/ISaveProvider;Lappeng/api/storage/IStorageChannel;)Lappeng/api/storage/IMEInventoryHandler;
	at extracells.item.storage.ItemStorageCell.func_77624_a(ItemStorageCell.java:48)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:575)
	at net.minecraft.client.Minecraft$$Lambda$1037/377710309.apply(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at net.minecraft.client.Minecraft$$Lambda$1054/444460695.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:589)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:528)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at extracells.item.storage.ItemStorageCell.func_77624_a(ItemStorageCell.java:48)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:575)
	at net.minecraft.client.Minecraft$$Lambda$1037/377710309.apply(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at net.minecraft.client.Minecraft$$Lambda$1054/444460695.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:589)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:528)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1874240888 bytes (1787 MB) / 4091543552 bytes (3902 MB) up to 8351383552 bytes (7964 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8960m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2765 Optifine OptiFine_1.12.2_HD_U_E2 76 mods loaded, 76 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version                  | Source                                             | Signature                                |
	|:----- |:--------------------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft                         | 1.12.2                   | minecraft.jar                                      | None                                     |
	| UCH   | mcp                               | 9.42                     | minecraft.jar                                      | None                                     |
	| UCH   | FML                               | 8.0.99.99                | forge-1.12.2-14.23.4.2765.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                             | 14.23.4.2765             | forge-1.12.2-14.23.4.2765.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | micdoodlecore                     |                          | minecraft.jar                                      | None                                     |
	| UCH   | openmodscore                      | 0.12                     | minecraft.jar                                      | None                                     |
	| UCH   | appliedenergistics2               | rv6-stable-1             | appliedenergistics2-rv6-stable-1.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| UCH   | backpacks16840                    | 3.5.4                    | backpacks 1.12.2 - 3.5.4.jar                       | None                                     |
	| UCH   | biomesoplenty                     | 7.0.1.2399               | BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar      | None                                     |
	| UCH   | codechickenlib                    | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | redstoneflux                      | 2.0.2                    | RedstoneFlux-1.12-2.0.2.3-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | brandonscore                      | 2.4.5                    | BrandonsCore-1.12.2-2.4.5.176-universal.jar        | None                                     |
	| UCH   | ctm                               | MC1.12.2-0.3.2.18        | CTM-MC1.12.2-0.3.2.18.jar                          | None                                     |
	| UCH   | chisel                            | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                       | None                                     |
	| UCH   | cyclopscore                       | 0.11.10                  | CyclopsCore-1.12.2-0.11.10.jar                     | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCH   | draconicevolution                 | 2.3.15                   | Draconic-Evolution-1.12.2-2.3.15.312-universal.jar | None                                     |
	| UCH   | endercore                         | 1.12.2-0.5.39            | EnderCore-1.12.2-0.5.39.jar                        | None                                     |
	| UCH   | jei                               | 4.13.0.218               | jei_1.12.2-4.13.0.218.jar                          | None                                     |
	| UCH   | enderio                           | 5.0.33                   | EnderIO-1.12.2-5.0.33.jar                          | None                                     |
	| UCH   | enderiointegrationtic             | 5.0.33                   | EnderIO-1.12.2-5.0.33.jar                          | None                                     |
	| UCH   | enderiobase                       | 5.0.33                   | EnderIO-1.12.2-5.0.33.jar                          | None                                     |
	| UCH   | enderioconduits                   | 5.0.33                   | EnderIO-1.12.2-5.0.33.jar                          | None                                     |
	| UCH   | enderioconduitsappliedenergistics | 5.0.33                   | EnderIO-1.12.2-5.0.33.jar                          | None                                     |
	| UCH   | enderioconduitsopencomputers      | 5.0.33                   | EnderIO-1.12.2-5.0.33.jar                          | None                                     |
	| UCH   | enderioconduitsrefinedstorage     | 5.0.33                   | EnderIO-1.12.2-5.0.33.jar                          | None                                     |
	| UCH   | enderiointegrationforestry        | 5.0.33                   | EnderIO-1.12.2-5.0.33.jar                          | None                                     |
	| UCH   | mantle                            | 1.12-1.3.2.24            | Mantle-Mod-1.12.2.jar                              | None                                     |
	| UCH   | tconstruct                        | 1.12.2-2.10.1.87         | TConstruct-1.12.2-2.10.1.87.jar                    | None                                     |
	| UCH   | enderiointegrationticlate         | 5.0.33                   | EnderIO-1.12.2-5.0.33.jar                          | None                                     |
	| UCH   | enderiomachines                   | 5.0.33                   | EnderIO-1.12.2-5.0.33.jar                          | None                                     |
	| UCH   | enderiopowertools                 | 5.0.33                   | EnderIO-1.12.2-5.0.33.jar                          | None                                     |
	| UCH   | projecte                          | 1.12-PE1.3.0             | ProjectE-1.12-PE1.3.0.jar                          | None                                     |
	| UCH   | equivalentenergistics             | 0.8.2                    | Equivalent-Energistics-Mod-1.12.2.jar              | None                                     |
	| UCH   | everlastingabilities              | 1.3.18                   | EverlastingAbilities-1.12.2-1.3.18.jar             | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCH   | hammercore                        | 2.0.2.3                  | HammerCore-1.12.2-2.0.2.3.jar                      | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCH   | expequiv                          | 11b                      | Expanded-Equivalence-Mod-1.12.2.jar                | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCH   | waila                             | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
	| UCH   | extracells                        | 2.5.13                   | ExtraCells-1.12.2-2.5.13a60.jar                    | None                                     |
	| UCH   | extrautils2                       | 1.0                      | extrautils2-1.12-1.9.4.jar                         | None                                     |
	| UCH   | zerocore                          | 1.12-0.1.2.2             | zerocore-1.12-0.1.2.2.jar                          | None                                     |
	| UCH   | bigreactors                       | 1.12.2-0.4.5.49          | ExtremeReactors-1.12.2-0.4.5.49.jar                | None                                     |
	| UCH   | farseek                           | 2.3.1                    | Farseek-1.12-2.3.1.jar                             | None                                     |
	| UCH   | quickleafdecay                    | 1.2.4                    | Fast-Leave-Decay-Mod-1.12.1.jar                    | None                                     |
	| UCH   | galacticraftcore                  | 4.0.1.181                | GalacticraftCore-1.12.2-4.0.1.181.jar              | None                                     |
	| UCH   | galacticraftplanets               | 4.0.1.181                | Galacticraft-Planets-1.12.2-4.0.1.181.jar          | None                                     |
	| UCH   | gokistats                         | @version@                | gokiStats-1.2.5.1.jar                              | None                                     |
	| UCH   | inventorytweaks                   | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCH   | ironchest                         | 1.12.2-7.0.46.831        | Iron-Chests-Mod-1.12.2.jar                         | None                                     |
	| UCH   | journeymap                        | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                        | None                                     |
	| UCH   | longerdays                        | 1.0.4                    | Longer-Days-Mod-1.12.2.jar                         | None                                     |
	| UCH   | lostcities                        | 2.0.11                   | lostcities-1.12-2.0.11.jar                         | None                                     |
	| UCH   | malisiscore                       | 1.12.2-6.4.0             | malisiscore-1.12.2-6.4.0.jar                       | None                                     |
	| UCH   | malisisdoors                      | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                      | None                                     |
	| UCH   | moartinkers                       | 0.6.0                    | moartinkers-0.6.0.jar                              | None                                     |
	| UCH   | moreplanets                       | 2.0.17                   | More-Planets-1.12.2-2.0.17-GC181.jar               | b3468b224a74e296555ad7efeb35f482e6f445de |
	| UCH   | natura                            | 1.12.2-4.3.2.62          | Natura-Mod-1.12.2.jar                              | None                                     |
	| UCH   | openmods                          | 0.12                     | OpenModsLib-1.12.2-0.12.jar                        | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCH   | openblocks                        | 1.8                      | OpenBlocks-1.12.2-1.8.jar                          | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCH   | oreexcavation                     | 1.4.129                  | OreExcavation-1.4.129.jar                          | None                                     |
	| UCH   | plustic                           | 6.5.2.0                  | plustic-6.5.2.0.jar                                | None                                     |
	| UCH   | portality                         | 1.0-SNAPSHOT             | Portality-Mod-1.12.2.jar                           | None                                     |
	| UCH   | randomloot                        | 1.3                      | RandomLoot-1.3.1.jar                               | None                                     |
	| UCH   | roguelike                         | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar                 | None                                     |
	| UCH   | spatialservermod                  | 1.3                      | SpatialCompat-Mod-1.12.2.jar                       | None                                     |
	| UCH   | stellarapi                        | 1.12.2-0.4.2.9           | Stellar+API-1.12.2-0.4.2.9.jar                     | None                                     |
	| UCH   | stellarsky                        | 1.12.2-0.5.2.8           | Stellar+Sky-1.12.2-0.5.2.8.jar                     | None                                     |
	| UCH   | streams                           | 0.4.4                    | Streams-1.12-0.4.4.jar                             | None                                     |
	| UCH   | tinker_io                         | release 2.6.1            | tinker_io-1.12.2-release+2.6.1.jar                 | None                                     |
	| UCH   | tinkersaddons                     | 1.0.7                    | Tinkers'+Addons-1.12.1-1.0.7.jar                   | None                                     |
	| UCH   | tcomplement                       | ${version}               | Tinkers-Complement-Mod-1.12.2.jar                  | None                                     |
	| UCH   | tinkersjei                        | 1.0                      | tinkersjei-1.0.jar                                 | None                                     |
	| UCH   | tinkertoolleveling                | 1.12.2-1.0.5.DEV.30c7957 | TinkerToolLeveling-1.12.2-1.0.5.jar                | None                                     |
	| UCH   | wanionlib                         | 1.12.2-1.5               | WanionLib-1.12.2.jar                               | None                                     |
	| UCH   | simpleundergroundbiomes           | 1.0.0                    | Simple-Underground-Biomes-Mod-1.12.2.jar           | None                                     |
	| UCH   | pvj                               | 1.3.2                    | Project-Vibrant-Journeys-Mod-1.12.2.jar            | None                                     |
	| UCH   | unidict                           | 1.12.2-2.7b              | UniDict-Mod-1.12.2.jar                             | None                                     |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
FarseekCoreMod (Farseek-1.12-2.3.1.jar)
  farseek.core.FarseekClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  team.chisel.ctm.client.asm.CTMTransformer
HCASM (HammerCore-1.12.2-2.0.2.3.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
BCModPlugin (backpacks 1.12.2 - 3.5.4.jar)
  brad16840.core.ClassTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.39.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
EECore (Expanded-Equivalence-Mod-1.12.2.jar)
  com.zeitheron.expequiv.core.EETransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.jar)
  openmods.core.OpenModsClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.82' Renderer: 'GeForce GTX 1070/PCIe/SSE2'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	AE2 Version: stable rv6-stable-1 for Forge 14.23.3.2655
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 671 names; 3800 stacks.
Configuration Info: IyBDb25maWd1cmF0aW9uIGZpbGUNCg0KY2xpZW50IHsNCiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSByZXBsYWNlIGVuY2hhbnRtZW50IGdsaW50IGNvbG9yIHdpdGggbW9yZSBtYXRjaGluZyBjb2xvcnMgZm9yIHNvbWUgdmFuaWxsYSBpdGVtcz8gW2RlZmF1bHQ6IHRydWVdDQogICAgQjoiQ3VzdG9tIEVuY2hhbnRtZW50IENvbG9ycyBmb3IgVmFuaWxsYSBJdGVtcyI9dHJ1ZQ0KDQogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgcG9ydGZvcndhcmQgeW91ciBsb2NhbCB3b3JsZCB3aGVuIHlvdSBzaGFyZSB3aXRoIGl0IHRvIExBTj8NCiAgICAjIFRoaXMgZmVhdHVyZSBkb2Vzbid0IHdvcmsgb24gYWxsIGNsaWVudHMsIHlvdSBhcmUgZ29pbmcgdG8gZ2V0IGEgbWVzc2FnZSBpbiBjaGF0IGlmIGl0IHdhcyBzdWNjZXNzZnVsL3Vuc3VjY2Vzc2Z1bCBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJMQU4gVVBuUCI9dHJ1ZQ0KDQogICAgIyBSZXBsYWNlIHZhbmlsbGEgZnVybmFjZSBhbmQgYnJld2luZyBzdGFuZCBwcm9ncmVzcyBiYXJzIHRvIHVzZSBzbW9vdGggcmVuZGVyaW5nPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJTbW9vdGggVmFuaWxsYSBHdWlzIj10cnVlDQp9DQoNCg0KaXdyZW5jaCB7DQogICAgIyBXaGF0IGlzIHRoZSBjb2xvciB3aGVuIHRoZSBob3ZlcmVkIGJsb2NrIGlzIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6R3JlZW49MjJGRjIyDQoNCiAgICAjIFdoYXQgaXMgdGhlIGNvbG9yIHdoZW4gdGhlIGhvdmVyZWQgYmxvY2sgaXMgTk9UIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6UmVkPUZGMjIyMg0KfQ0KDQoNCiJ2YW5pbGxhIGltcHJvdmVtZW50cyIgew0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIGZvcmNlLXNwYXduIEVuZGVyIERyYWdvbiBFZ2cgb24gRW5kZXIgRHJhZ29uIGRlYXRoPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJBbHdheXMgU3Bhd24gRHJhZ29uIEVnZyI9dHJ1ZQ0KfQ0KDQoNCg==
Pastebin Connection: Okay.
Dependent Mods:
    -Expanded Equivalence (expequiv) @11b

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Pulsar/tcomplement loaded Pulses: 
		- ModuleCommons (Enabled/Forced)
		- ModuleFeature (Enabled/Not Forced)
		- ChiselPlugin (Enabled/Not Forced)

	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Launched Version: forge-14.23.4.2765
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 398.82, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Conquest_1.12.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E2
	OptiFine Build: 20180728-185429
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 398.82
	OpenGlRenderer: GeForce GTX 1070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

- Minecraft Version: 
- AE2 Version: rv6-stable-11
- Forge Version: 14.23.4.2765

**Comment by Pingger** [comment]
you need to update extra cells!
rv5 to rv6 changed the api, so you need to update extra cells as well

**Comment by Pingger** [comment]
The following simple search term would have pointed you in the right direction: "crash after update"
