### ISSUE TITLE
Fuzzy Card (?) Crash

### ISSUE THREAD

**Issue by TimeConqueror** [AppliedEnergistics/Applied-Energistics-2#3753]
**Describe the bug**
I think, Minecraft crashed, when I edited the settings of Storage Bus, that had been connected to Storage Crate from with a couple of armor pieces. I insert there the Fuzzy Card and few second ago, when I tried to sort the content of Storage Cells through the IO Port. Doing this, I wanted to extract armor from cells to Crate, but Minecraft crashed.

**Additional context**
Crash-report: [gist](https://gist.githubusercontent.com/TimeConqueror/86fcce5f2e53d594ad6a421752351b66/raw/85ec9f60303da957b29f66b056d2269b2bbd863c/Minecraft%2520Crash%2520Report)

**Environment**
- Modpack: StoneBlock.
- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: 14.23.4.2760

**Comment by yueh** [comment]
That is a really odd crash.

Any additional info? Like which mod does provide the inventory? Can you reproduce it in a new instance with just AE2 and that particular mod? Items stored, one time crash, etc.

**Comment by TimeConqueror** [comment]
I just tried with new verison, all is fine.

**Comment by yueh** [comment]
I kinda doubt that a version update would actually resolve it, but it was most likely just a one time crash as it is a pretty obscure one.
