### ISSUE TITLE
Texture bug

### ISSUE THREAD

**Issue by StarboundModderRWC** [AppliedEnergistics/Applied-Energistics-2#3754]
Hello, 
Thank you so much for all the years on this mod. Thank you.

Here is the issue I am experiancing.

So my system and minecraft has the infamous sound bug, when switching to headphones, minecraft does not adjust. I have to restart until I found a workaround. That is clicking on video settings, then quality, then clicking once anywhere on the mipmap type button slider (not changing the setting, but for the sound bug fix), after a 1 minutes pause it fixes the sound issue but causes ae2 textures to become distorted. See attached photos, i ordered them 1,2,3 in order

![1](https://user-images.githubusercontent.com/43756186/46301287-e80ee000-c573-11e8-8a4d-f7f61afb1eb5.png)
![2](https://user-images.githubusercontent.com/43756186/46301288-e80ee000-c573-11e8-85ab-0a28f3abe2f0.png)
![3](https://user-images.githubusercontent.com/43756186/46301289-e80ee000-c573-11e8-8510-d9802f7d593f.png)
![4](https://user-images.githubusercontent.com/43756186/46301290-e80ee000-c573-11e8-8e76-bc88f8f87503.png)
![5](https://user-images.githubusercontent.com/43756186/46301291-e80ee000-c573-11e8-947b-4fdf05033ad6.png)
![6](https://user-images.githubusercontent.com/43756186/46301285-e80ee000-c573-11e8-89d7-430bb6a2da6e.png)
![7](https://user-images.githubusercontent.com/43756186/46301286-e80ee000-c573-11e8-9a4b-763e5e9ca177.png)

. I was deleting the entire ae2 config folder which was working, until I found out a simple restart fixes the textures. I also noticed that any shader or resource pack loaded from scratch will recreate this issues as well, and simply removing them and restarting will not fix the issues, deleting the minecraft options.txt config file works. Thank you for your time and patience, you have a great mod. From one modder to another.  I would be happy to zip a video if the photos don't work for you

- Minecraft Version: 1.12.2
- AE2 Version:  RV 6 beta 1
- Forge Version: 2759

**Comment by yueh** [comment]
Don't use Optifine.

**Comment by StarboundModderRWC** [comment]
what are the drawbacks of not useing opt fine ? 

    On Monday, October 1, 2018 2:29 PM, yueh <notifications@github.com> wrote:
 

 Don't use Optifine.—

**Comment by StarboundModderRWC** [comment]
what are the drawbacks of not useing opt fine ?

**Comment by StarboundModderRWC** [comment]
so my game really is choppy, now that i took opti away.....dont know why im running i5 @ 4.6 Ghz and my ram is ddr3 2400 and I have a gtx 770

**Comment by HaphLife** [comment]
> so my game really is choppy, now that i took opti away.....dont know why im running i5 @ 4.6 Ghz and my ram is ddr3 2400 and I have a gtx 770

If it isn't your toaster, try changing the configs.
