### ISSUE TITLE
Where is multipart support?

### ISSUE THREAD

**Issue by alpharou** [AppliedEnergistics/Applied-Energistics-2#3755]
As the title says. I cannot integrate AE2 cabling with ProjectRed's one, and it used to be possible (and really cool in that aspect)

#### Description
It's not entirely a compatibilty issue, but AE2 does not interact as it always did with multipart blocks. I've put ProjectRed's example because it's one of the cleanest ways of using multipart that I know. You could run redstone buses underneath an ME cable and then put a cover. I just want to know if there's another version of multipart, or that AE2 doesn't support it anymore.

#### Environment
- ProjectRed 1.12.2-4.9.1.92-Base
- ForgeMultipartCBE 1.12.2-2.5.0.71-universal
- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-1
- Forge Version: 14.23.4.2765

**Comment by yueh** [comment]
There is none.
