### ISSUE TITLE
Issue with Mekanism Cardboard Box in System

### ISSUE THREAD

**Issue by JathTyki** [AppliedEnergistics/Applied-Energistics-2#3756]
**Describe the bug**
Upon accidentally putting a Mekanism Cardboard Box inside of the AE system, you are unable to remove it via a regular terminal, and attempting to use the Cell Workstation actually doesn't show any items so I am unable to actually remove it through normal means.

**To Reproduce**
Take a Mekanism Cardboard Box (mine had an Iron Chest's Diamond Chest that had items in it) and place it into the system. At that point you are unable to remove it.

**Expected behavior**
To be able to remove it through the regular terminal.

**Additional context*
https://i.imgur.com/VgreGiD.png
https://i.imgur.com/ra2WoE6.png
The only way I was able to remove the cardboard box from the system was using an export bus with a similar cardboard box as the item to export, and a fuzzy card to export it into a chest. This allowed it to come out of the system

**Environment**
Using a modified version of ATM3 from the Curse Client, removing about 20 or so mods that I didn't want (like Pam's HarvestCraft, and some more)
SP

- Minecraft Version: 1.12.2
- AE2 Version: rv6 stables 1
- Forge Version: 14.23.4.2760

**Comment by yueh** [comment]
Cannot reproduce.

**Comment by ikyonawooka** [comment]
Playing Enigmatica 2: Expert i have the same issue.
Cardboard Box with a Vanilla Minecraft chest (with items in it) inside of said box, accidentally placed it into the AE system.

As with the OP's suggest way of getting it out of them system it works (export buss, fuzzy card with same item boxed upped)

- Minecraft Version: 1.12.2
- Enigmatica Version: 1.50a
- AE2 Version: rv6 stables 6
- Forge Version: 14.23.5.2781

**Comment by Elvarion** [comment]
Can also confirm, just had this happen in Enigmatica 2 - Expert

* Minecraft 1.12.2
* appliedenergistics2-rv6-stable-6
* Forge 14.23.5.2781

**Comment by HugoZink** [comment]
Same issue **still** happens in All The Mods 3 Remix. I put 4096 basic plates from Nuclearcraft in an Actually Additions storage crate, put it in a box, and now the box can't be taken out by the terminal at all anymore.

**Comment by TheInfamousAlk** [comment]
Same issue still happens in all the mods 3 remix as well. I have a cardboard box with a blaze spawner in it, and cannot remove it. Also tried export bus and storage bus. It seems it's not limited to storage blocks in boxes.

**Comment by Elvarion** [comment]
> ~Also tried export bus and storage bus.~

> ~An export bus with a fuzzy card doesn't work either. This is a very serious issue.~

When this happened for me on Enigmatica 2 - Expert I was able to export my box from my system via an Export bus, Not sure if I used a Fuzzy card or not, But I did get it out somehow (Was quite the time since I played Enig~ now, so thats all I can say

**Comment by TheInfamousAlk** [comment]
I figured out a workaround. While a cardboard box in the export bus filter doesn't work, a cardboard box _with the exact same item in it_ in the export bus will work. I had a stabilized spawner in a box, I had to make another stabilized spawner and put it in a cardboard box, then use that cardboard box as the filter for the export bus, then it exported the stuck box into a chest.

**Comment by connorch** [comment]
I am also having this issue - going to try and build my first export bus just to get the cardboard boxes out.

**Comment by desagas** [comment]
It must contain an item, a normal box will not work.

**Comment by DDriggs00** [comment]
I can confirm that the issue still exists in e2e v1.72

**Comment by HugoZink** [comment]
Still happens. The idea of "cannot reproduce" is laughable as it happens 100% of the time when you put a full Mek cardboard box in the terminal.

**Comment by wesleytech** [comment]
Hi, i know this is conversation is closed. but if you accidently put cardboard boxes in your ME, you can pull them out with an export bus+fuzzy card (might need to have something in the cardboard box for this to work!).

hope it helps.

**Comment by desagas** [comment]
Yes, that is correct.  It that is not a fix, that is an intended method of extracting items.

Denver Leman

On Jan 21, 2020, at 10:52 AM, wesleytech <notifications@github.com> wrote:

﻿

Hi, i know this is conversation is closed. but if you accidently put cardboard boxes in your ME, you can pull them out with an export bus+fuzzy card (might need to have something in the cardboard box for this to work!).

hope it helps.

**Comment by StripedMonkey** [comment]
Just ran into this very same issue, can't remove the box after putting in one that has a spawner inside. Putting a fuzzy card in only worked if the box had something else inside (In my case I just grabbed an XP drain because it was the closest thing on hand, using a box without anything inside didn't export the item. Enigmatica 2 Expert mode, 1.75 (1.12.2 IIRC)

@yueh I get that you might not have been able to replicate the issue but it seems like it's affecting quite a few people.

**Comment by sbenedict** [comment]
Hit this one too. Used the fuzzy export bus to get it out of the storage cell. However want to add you can work around this issue by setting up a chest with a fuzzy storage bus set to a filled cardboard box and you'll be able to pull it out of the terminal.
Using this method there is also a UI bug that still shows the item in storage after you retrieve it, but it goes away when you close and open the terminal again.
