### ISSUE TITLE
Air in Recipes

### ISSUE THREAD

**Issue by FriendlySurvival** [AppliedEnergistics/Applied-Energistics-2#3759]
Air in recipes detected by Caliper 

This boot up mod that detect various errors on boot reported the following... 
"# Recipes with Air

If a recipe has air in it as an ingredient or output it can cause many issues
such as crashes and uncraftable recipes.

Recipe: appliedenergistics2:disassemble Class: public final class appeng.recipes.game.DisassembleRecipe
Recipe: appliedenergistics2:facade Class: public final class appeng.recipes.game.FacadeRecipe"

Non Applicable just a reporting. But to bring this up load Caliper for the AE2 version in question.  
Non Applicable 
Non Applicable
Non Applicable since it was a boot run only. 

- Minecraft Version: 1.12.2
- AE2 Version: v6 Stable
- Forge Version: ending in 2759

**Comment by yueh** [comment]
Forge does not state anything about this in their documentation, if these things really causes issues for that particular mod, they should work with forge on improving their docs instead of confussing players and providing us with a clear guideline about best practises.

**Comment by FriendlySurvival** [comment]
This is not a mod capability issue it's more like "hey I am reporting this to you so you may become aware of such possible issues and ensure a cleaner mod".  

So your saying even IF it possible that these may cause issues you have no regards to clean up the coding anyways just to follow best practices in general?
