### ISSUE TITLE
Can’t put in quartz in macerator 

### ISSUE THREAD

**Issue by Akilele** [AppliedEnergistics/Applied-Energistics-2#3762]
Hello, the following problem appeared: I can not put quartz in the macerator from ic2 mod. I tried different versions of both mods. Please tell me how to fix it, can it be possible to prescribe a recipe in some kind of config file?

- Minecraft Version: 1.12.2
- IC2 Version: industrialcraft-2-2.8.100-ex112
- AE2 Version: appliedenergistics2-rv6-stable-1
- Forge Version: 1.12.2 - 14.23.5.2768

**Comment by yueh** [comment]
We dropped our own custom recipes during 1.12 in preparation of 1.13, thus we no longer register recipes to other mods. Usually this isn't a problem as most mods already have their own support for it built in.

If not, the best options are probably something like CraftTweaker or asking the other mod for native support. Keep in mind, that your modpack could simply have disabled them for whatever reason.
With 1.13 it should be much easier for us to register custom recipes for other mods.
