### ISSUE TITLE
Memory Cards not working in a big Modpack

### ISSUE THREAD

**Issue by Panzer1119** [AppliedEnergistics/Applied-Energistics-2#3763]
The Memory Card no longer works how it is described [here](https://ae-mod.info/Memory-Card/) in a big Modpack.

**Describe the bug**
I just updated from rv5-stable-11 to rv6-stable-1 and the old and linked p2p tunnels are working fine.
But when i Right Click on a (new crafted) P2P ME Tunnel with a (new crafted) Memory Card it says "Invalid Machine" and when i Shift + Right Click on a block it says "Memory card cleared."

**To Reproduce**
I could not reproduce it, i created a small pack with only 5 mods or so (AE2, AE2Stuff, ExtraCells2 and WirelessCraftingTerminal, JEI) then updated all the mods from AE2 rv5 to AE2 rv6 and it worked just fine.
But on my big Modpack it does not work...

**Expected behavior**
Shift + Right Click with Memory Card on P2P Tunnel should copy the device configuration to the card.
Right Click another P2P Tunnel should load the device configuration from the card.

**Environment**
ATM3 Modpack v5.9.8.d but with various changes (over 300 Mods)
AE2 Stuff v0.7.0.4
ExtraCells2 v2.6.1a
Wireless Crafting Terminal v3.10.81

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-1
- Forge Version: 14.23.4.2749

**Comment by yueh** [comment]
As you confirmed it's working in a basic setup, it is up to the modpack author to identify the offending mod.

**Comment by Panzer1119** [comment]
I created a new world with the modpack and it worked, but in my old world not, so i think its not the fault of another mod?

**Comment by yueh** [comment]
No idea, I did test some upgrade paths for rv5 -> rv6 as the cards now have some additional data, but that is purely visual. Nothing in terms of functionality. The only thing happening is that existing ones will use the same model as newly crafted once until they read something again.

**Comment by Panzer1119** [comment]
It seems that the PartP2PTunnel.java "throws" the INVALID_MACHINE part, which is totally acceptable, because the memory card is empty, but in the ToolMemoryCard.java the Shift (Sneak) + Right Click clears the card, so how can it copy the settings from a P2P Tunnel?
