### ISSUE TITLE
Compatibility with GregTech: Community Edition (1.12.2) EU

### ISSUE THREAD

**Issue by Vyraal1** [AppliedEnergistics/Applied-Energistics-2#3770]
**Describe the feature**
Would it be possible to have compatibility with GregTech: Community Editions energy system? It is now standalone from IC2 and has its own energy. 
https://minecraft.curseforge.com/projects/gregtechce

**Reasons why it should be considered**
This is the only port of GregTech playable on CurseForge post 1.12.2, and there was always compatibility between the two in the past, although that was probably a result of using IC2's ENet. 

**Additional Context**
Can keep the old ratio of 1 EU to 2 AE still. If it isn't too complicated, could make it so that the energy  acceptor can only accept 1 amp per side, and controllers can do up to 4 amps per side. If this is not feasible, than unlimited amperage would also be great.

**Comment by yueh** [comment]
Currently there are no plans to support it. Especially as it is currently a single mod and at least API wise very similar to RF, but only a different API for the goal of implementing their own API (at least on a first look).

Yet this should change once it is adopted a bit more commonly.

**Comment by Vyraal1** [comment]
Hey just to clarify the main reason why they have their own API versus RF's is because the energy net system operates differently than RF in that it has amperage/energy packets, so functionally and from a gameplay perspective it's more akin to IC2's EU. For example GTCE machines, a machine cannot accept unlimited packets, and if it receives more than its intended energy, the machine will explode.

As for community acceptance, that's a fair point - this is an alpha port of Gregtech, which doesn't have as large fanbase (but a pretty dedicated fanbase regardless).
