### ISSUE TITLE
Crash Upon Logging In

### ISSUE THREAD

**Issue by Vyraal1** [AppliedEnergistics/Applied-Energistics-2#3771]
**Describe the bug**
Had a crash trying to log into a world, it can sometimes be reproduced, and other times I can just log in fine.

**To Reproduce**
Can provide world download on request, this is a modified Gregblock pack version 1.1.3 (modified by adding OpenBlocks Elevators). I just try to login and the client crashes.

**Expected behavior**
Not to crash.

**Additional context**
https://gist.github.com/Vyraal1/795dbba68707153a39d30d1e4c19cdfe

**Environment**
SMP, AE2-rv6-Stable 1, GregBlock Ver 1.1.3

- Minecraft Version: 1.12.2
- Forge Version: 2768

**Comment by yueh** [comment]
I do not see any obvious reason for it. It is also crashing inside actual minecraft code, which we do not touch at all. Therefore could you try and reproduce it with less mods? Especially "performance" optimizing ones, as they might alter the particle system of minecraft.

**Comment by Vyraal1** [comment]
So the current performance enhancing mods I could identify were BetterFPS and FoamFix, although I'm not sure of the latter's involvement in anything graphic related. I actually can't seem to reproduce the crash anymore, as it does seem to be random, sorry if this isn't helpful. I'll try to keep an eye out, it's just that I had this crash happen multiple times after assembling a somewhat large base with multiple facades.
