### ISSUE TITLE
HWYLA Mod Compatibility for ME Smart/Dense Cables (I'd like to reopen this issue)

### ISSUE THREAD

**Issue by totyaxy** [AppliedEnergistics/Applied-Energistics-2#3773]
With 1.12 MC, is not possible to see the channel informations. This is missing feature.

Because WAILA unsupported on 1.12 MC. HWYLA supported on 1.12 MC, but  I don't see the channel informations on the cable. The author of HWYLA doesn't support for other mod as I read the posts.

Thank you.

**Comment by yueh** [comment]
Works for me.

![hwyla-1.12](https://i.imgur.com/6Q8Gw1N.png)

**Comment by totyaxy** [comment]
Hi!

Thank you for your answer!

Okay, In the picture I see the "Smart cable", well I tried this, and the result, with this cable type HWYLA  show the channels, indeed. Before I posted this issue, I tried the "covered cable". Covered cable support up to eight cahnnels too. The question is, "covered cable" doesn't show channel informations, this is normal?

Thanks again.

**Comment by mindforger** [comment]
>On my server isn't "the one probe" installed, so there is the communication error on the MP, but I don't think this will influence the given problem.

sure it does, the system is not present on you PC ist is simulated on the server so the server has to tell your client the data to display

**Comment by Horf** [comment]
So you mean, Hwyla is only showing the channels in SP, because there is "the one probe" active?
