### ISSUE TITLE
Memory Card does not function properly with an offhand item equipped

### ISSUE THREAD

**Issue by sharkck** [AppliedEnergistics/Applied-Energistics-2#3775]
**Describe the bug**
When you have an item in your offhand and go to use the memory card normally, it does not work.

While having anything in your off-hand, when you shift-right-click on a p2p tunnel, it clears the memory card instead of setting it.  When you right click after on a p2p tunnel, it just says invalid machine.

**To Reproduce**
Equip something in your offhand and try to use the memory card on a p2p tunnel.

**Expected behavior**
When you shift-right-click, it is supposed to copy the p2p tunnel's information so that you can configure the tunnel.

**Additional context**

No logs or crash reports.

**Environment**

If need-be, I could provide an export of my mods I'm using for Twitch to retrieve them.

- Minecraft Version: 
Using version AE2's rv6-stable-2 on Minecraft version 1.12.2 Forge version 14.23.5.2770

**Comment by yueh** [comment]
This is a forge bug and/or limitation.

We need to bypass the usual sneak clicking to use the memory card with the targeted block/part. Which needs a special flag usually not set by items, yet Forge wants both items to have it set, which is only true in some rare cases.
