### ISSUE TITLE
Cell workbench dupes upgrade cards and gives very glitchy behaviour

### ISSUE THREAD

**Issue by incomingnerd** [AppliedEnergistics/Applied-Energistics-2#3776]
**Describe the bug**
The Cell Workbench can duplicate and destroy upgrade cards such as the Inverter Card and Fuzzy Card. It also leaves manipulated cells in an inconsistent state, filtering as if they had upgrades when they don't and vice versa.

This might be an issue with how and when the workbench writes back upgrade card information to the cells, as different results can be had by opening and closing the workbench UI at various points while manipulating the cards.

**To Reproduce**
*For a visual guide, see here: [https://imgur.com/a/6eKRuo1](https://imgur.com/a/6eKRuo1)*

Note: *Don't close the Cell Workbench UI unless stated - this alters the results*

1. Create a Cell Workbench, two Cells and a single Inverter Card
2. Insert the first Cell into the Cell Workbench
3. Insert the Inverter Card into an upgrade slot
4. Remove the first Cell
5. Insert the second Cell
6. Remove the errant Inverter Card from the upgrade slot
7. Close the Cell Workbench UI and re-open it
8. Remove the second Cell
9. Insert the first Cell
10. Close the Cell Workbench UI and re-open it
11. Remove your free gift from the upgrade slot!

**Environment**
- Single player
- Fresh installation from Twitch launcher
- Only AE2 installed

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-2
- Forge Version: forge-14.23.5.2770

I discovered the bug in the FTB Direwolf20 1.12 modpack (appliedenergistics2-rv5-stable-11) when using View Cells to filter my storage system. I've verified it is still present using the latest version of AE2 and Forge at the time of writing.

**Comment by mixilester009** [comment]
Provide screenshots to better understand the situation.

**Comment by incomingnerd** [comment]
See the album here: [https://imgur.com/a/6eKRuo1](https://imgur.com/a/6eKRuo1)

**Comment by incomingnerd** [comment]
Note: I've only illustrated the dupe bug, but the buggy behaviour also leaves the two cards in a weird state - they may or may not have inverted filtering, depending on the order of operations.
