### ISSUE TITLE
Ae2 does not properly register cables/blocks to the Minecraft Schematic System

### ISSUE THREAD

**Issue by sharkck** [AppliedEnergistics/Applied-Energistics-2#3778]
Items from AE2 register as 'AE2 Cable and/or Bus' to the Minecraft Schematic System instead of identifying/relaying what they actually are

**Describe the bug**

In Minecolonies, there is a scan tool that will save a schematic in .nbt format that uses the Minecraft Schematic System.  When I scan an area that has AE2 items in it, it assumes all of the items are 'AE2 Cable and/or Bus' even though there are a variety of different items.  In my example here: 
https://github.com/ldtteam/minecolonies/issues/2970
I have a mixture of AE2 Dense Cable (Fluix), AE2 Covered Cable (Fluix), AE2 Covered Cable (Lime), AE2 Illuminated Panel and AE2 Quartz Fiber and it all registers as the same thing instead of what each individual item is.

**To Reproduce**

Make a scan tool in Minecolonies, make an area using AE2 items and have your builder try to build the schematic and see that it's all put under the same block type.

**Expected behavior**

AE2 to properly identify the blocks so that they could be saved to a schematic so that I can create workshop templates using a schematic.

**Additional context**

![image](https://user-images.githubusercontent.com/960552/46920461-95461700-cfbc-11e8-97db-22e793f25c28.png)

**Environment**

Multiplayer using Minecolonies and other various mods.  Modpack export from Twitch can be made available if needbe

Minecraft Version:
Using version AE2's rv6-stable-2 
Minecraft version 1.12.2
Forge version 14.23.5.2770

**Comment by yueh** [comment]
Based on the minimal information being available, it looks to be mostly aimed at vanilla. Thus there is no support for multipart blocks as well absolutely no information on something like an API.

So simply not possible (currently).
