### ISSUE TITLE
[Question] New Facade Config

### ISSUE THREAD

**Issue by NickelHub** [AppliedEnergistics/Applied-Energistics-2#3779]
> Feature #3706: Added a new facade config. Will delete old config file. Refer to config documentation for > more details. - yue

I try to enabled glass as facades, but I cannot find these documentation and there is no readme, how to set it up. Could you tell me, where it is?

**Comment by yueh** [comment]
It is part of the config file itself...

**Comment by NickelHub** [comment]
There is no ifromation how to format the settings or how to add a block, that is a tile like furnace.

**Comment by NickelHub** [comment]
This would be similiar to the old settings. https://pastebin.com/Vt1B1wBE 
Is this the wa it should be done?

**Comment by covers1624** [comment]
The new facade config is a blacklist, glass facades should already be a thing.

**Comment by NickelHub** [comment]
Now I am consufsed. I enabled the tile entity crafting, but that did not change anything. I am still not able to craft facades from tiles.

![2018-10-15_22 59 28](https://user-images.githubusercontent.com/26455012/46978223-ad0dc000-d0ce-11e8-9983-835b5d8f8201.png)
![2018-10-15_23 02 16](https://user-images.githubusercontent.com/26455012/46978224-ad0dc000-d0ce-11e8-8958-4c17c30384e6.png)
![2018-10-15_22 59 24](https://user-images.githubusercontent.com/26455012/46978235-b7c85500-d0ce-11e8-85b7-0c6e97156243.png)
