### ISSUE TITLE
RFE: go directly to colored covered cable via dyed wool

### ISSUE THREAD

**Issue by WebDragon** [AppliedEnergistics/Applied-Energistics-2#3780]
**Describe the feature**

It would be really nifty if one could take advantage of one's wool farming to use dyed wool to sidestep the need to produce large quantities of dye, by allowing one to use a colored wool to go directly from fluix cable to colored covered cable. 

**Reasons why it should be considered**

This allows one to make better use of resources by not always having to craft 8 of any cable before you can color it, and prevents winding up with unused leftovers that occupy space in the ME system.

**Comment by yueh** [comment]
Not possible as we need 17 colours and there are only 16 coloured wools available.

I might look into an alternative with 1.13. The 1.12 recipes involving oredict and custom parts are buggy as hell. Hopefully the metadata flattening will make it less buggy.

**Comment by WebDragon** [comment]
just have it work on every color except white -- if someone really wants white covered cable as opposed to fluix covered cable, do you suppose they will have even the remotest chance of a dearth of bonemeal? :)

**Comment by mindforger** [comment]
@yueh as 1.13 arises this may not be important anymore, but how about using 4 string instead of wool for the fluix cables, would be an fine subsitute imho :D maybe for 1.13
