### ISSUE TITLE
API w/spatial pylons dont update neighbours on restart

### ISSUE THREAD

**Issue by CGDoctor8** [AppliedEnergistics/Applied-Energistics-2#3786]
**Disclaimer**
I Was Requested by HenryLoenwind to make an issue if this makes no sense or is completely inaccurate it because i have no idea what I'm talking about

**Whats going on?**
On server reload Ender IO Conduits disconnect from spatial pylons due to "AE2 blocks change what they can provide to connect to and don't notify their neighbours about it"

**To Reproduce**

1. Install AE2, Ender IO and [Ender IO AE2 Conduits](https://minecraft.curseforge.com/projects/ender-io-ae2-conduits)
2. Make a basic pylon setup
3. Disconnect and rejoin world

**Expected behaviour**
For the API to notify neighbours on restart / For Ender IO Conduits to reconnect to spatial storage on restart like smart cables

**Environment**
- Single player
- Minecraft Version: 
- AE2 Version: rv6-stable-2
- Forge Version: 14.23
- EnderCore 0.5.41
- Ender IO 5.0.36

**Additional context**
Request from HenryLoenwind
![vln6xfe](https://user-images.githubusercontent.com/39572468/47173069-4bb24080-d2ca-11e8-8e38-faa1d2e193cf.png)
Before Restart
![dxgg5hl](https://user-images.githubusercontent.com/39572468/47173080-5371e500-d2ca-11e8-98dc-52d1126132ef.png)
After Restart
![1xyjcxw](https://user-images.githubusercontent.com/39572468/47173083-553ba880-d2ca-11e8-8a8a-ff951ead24f5.png)

**Comment by HenryLoenwind** [comment]
@EpicSquid linking you in here

**Comment by yueh** [comment]
Ender IO assumes that every single conduit has full control over exposing connections depending on various conditions like how it's configured, available neighbours and so on, thus requiring that everything else has to notify them about changes.
AE2 on the other hand assumes full control about how a network is constructed and each part/block just announces the connectable sides in a static way, regardless of any neighbours and instead the block itself notifies the network once it wants to change. E.g. to avoid having thousands of cables constantly sending neighbour updates for mundane stuff.

As long as these opposed design approaches exist, it's pretty much impossible to have it work perfectly in every case.
