### ISSUE TITLE
Autocrafting Pure Crystals with ME interfaces and it creating uncraftable patterns 

### ISSUE THREAD

**Issue by ToxicSnow** [AppliedEnergistics/Applied-Energistics-2#3788]
So In a modded SMP server I play on, I'm getting ready to massively overhaul my AE system, add more storage and more slots for machines, part of that was automating processers and crystals so I set up sub networks to do those two things
I used this set up for the processers: https://www.youtube.com/watch?v=e_isR_UfnDE&t

And this set up for the crystals: 
https://www.youtube.com/watch?v=yArP-IGr_sQ&t

My main system is two drives with 15 64k drives, a controller with the three interfaces for crafting making patterns and putting the patterns in the system. I have a  single CPU still, was making more when this happened, I looked around and saw that Redstone being duped was a problem with the formation plate, took that out replaced it with a storage bus and a precision dropper in the hopes that that would fix it but it didn't, When I go to craft the pure crystals it doesn't show what is needed for the crafting just the finished product, with no way to get to it. I tried to make the 33 controllers I needed in order to make my new system and this happened so If anyone can shine a light on what I can do 

**Additional context**
https://imgur.com/a/bnd4uyE
This is the Pictures of how after I take out the patterns and completely destroy the interface that holds them in the system before putting a brand new interface in the same spot and getting those two patterns in my system that do nothing. 

I am playing FTB revelations version 2.5.0

everything is set up correct, there's nothing missing and yet the crystals aren't crafting, I can craft the fluix crystals, but not the pure variants

**Environment**
This has happened in both the overworld and the storage cell I'm going to be storing my AE system in. 

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv5-stable-11
- Forge Version: Forge-14.23.4.2759

**Comment by ToxicSnow** [comment]
Its part of a mod pack so I cant try out the latest stable build. the full mod list is in the 200's so I didn't want to waste my time and yours listing them all out

/dank/null | TheRealp455w0rd
Actually Additions | Ellpeck
Actually Baubles | Jacky1356400
Akashic Tome | Vazkii
AppleSkin | squeek502
Applied Energistics 2 | AlgorithmX2
ArchitectureCraft | darkevilmac
Aroma1997Core | Aroma1997
Aroma1997's Dimensional World | Aroma1997
Astral Sorcery | HellFirePvP
AutoRegLib | Vazkii
B.A.S.E | lanse505
Bad Wither No Cookie - Reloaded | kreezxil
Baubles | azanor
BdLib | bdew
Bed Patch | Mordenkainen3141
Better Advancements | Way2muchnoise
Better Builder's Wands | Portablejim
BiblioCraft | JDSinclair
Binnie's Mods | Binnie567
Blockcraftery | elucent
Blood Magic | WayOfTime
Bookshelf | darkh4x
Botania | Vazkii
Brandon's Core | brandon3055
Career Bees | RWTema
Chameleon | jaquadro
Chest Transporter | CubeX2
Chisel | tterrag1098
Chisels & Bits | AlgorithmX2
Clumps | jaredlll08
CoFH Core | TeamCoFH
CoFH World | TeamCoFH
CodeChickenLib | covers1624
Compact Machines | Davenonymous
Compact Solars | progwml6
Compacter | bdew
ConnectedTexturesMod | tterrag1098
Construct's Armory | TheIllusiveC4
Controlling | jaredlll08
Cooking for Blockheads | BlayTheNinth
CraftTweaker | jaredlll08
Custom Main Menu | lumien231
Dark Utilities | darkh4x
Deep Resonance | McJty
Default Options | BlayTheNinth
Diet Hoppers | RWTema
Dirt2Path | marwat208
Draconic Evolution | brandon3055
ET Lunar | ValkyrieofNight
ElecCore | Elec332
EluLib | elucent
Embers | elucent
EnderCore | tterrag1098
EnderIO | CrazyPants
Ender Storage | covers1624
Engineer's Doors | Nihiltres
Engineers Workshop Reborn | modmuss50
Environmental Tech | ValkyrieofNight
Exchangers | Jacky1356400
Extra Rails | shadowfactsmc
Extra Utilities 2 | RWTema
ExtraCells2 | Destroyer7128
Extreme Reactors | ZeroNoRyouki
FTB Utilities | FTB
FTBLib | FTB
FastWorkbench | Shadows_Of_Fire
Fence Jumper | TheRealp455w0rd
Flat Colored Blocks | AlgorithmX2
Flux Networks | Ollie_Lansdell
Forestry | SirSengir
Gadgetry: Core | elucent
Gadgetry: Machines | elucent
Gendustry | bdew
Guide-API | TehNut
Immersive Engineering | BluSunrize
Immersive Petroleum | Flaxbeard
IndustrialCraft 2 | Player
Industrial Foregoing | Buuz135
Industrial Wires | malte0811
Initial Inventory | jaredlll08
Inventory Tweaks | Kobata
Iron Backpacks | gr8pefish
Iron Chests | progwml6
JEI Bees | bdew
JEI Integration | SnowShock35
JourneyMap | techbrew
Just Enough HarvestCraft | mrAppleXZ
Just Enough Items | mezz
Just Enough Resources | Way2muchnoise
KleeSlabs | BlayTheNinth
Long Fall Boots | NanoHeart
MCMultiPart | amadornes
MTLib | jaredlll08
Magic Bees | MysteriousAges
Mantle | mDiyo
McJtyLib | McJty
MineTogether | Creeperhost
Mod Name Tooltip | mezz
ModTweaker | jaredlll08
More Overlays | feldim2425
Morph-o-Tool | Vazkii
Morpheus | Quetzi
Mouse Tweaks | YaLTeR97
Natura | mDiyo
Nature's Compass | ChaosTheDude
NetherPortalFix | BlayTheNinth
Not Enough Wands | romelo333
NotEnoughIDs | fewizz
OpenBlocks | OpenMods Team
OpenModsLib | OpenMods Team
OpenComputers | SangarWasTaken
p455w0rd's Library | TheRealp455w0rd
Pam's HarvestCraft | MatrexsVigil
Placebo | Shadows_of_Fire
Platforms | ShetiPhian
Project Red | Mr_TJP
Quark | Vazkii
Quick Leaf Decay | lumien231
RFTools | McJty
RFTools Control | McJty
RFTools Power | McJty
Ranged Pumps | raoulvdberge
ReAuth | TechnicianLP
Reborn Core | modmuss50
Reborn Storage | modmuss50
Redstone Arsenal | TeamCoFH
Redstone Flux | TeamCoFH
Refined Storage | raoulvdberge
Refined Storage Addons | raoulvdberge
Reliquary | P3pp3rF1y
Resource Loader | lumien231
Roots | elucent
Rustic | mangoose3039
SecretRoomsMod | AbrarSyed
Shadowfacts' Forgelin | shadowfactsmc
ShetiPhianCore | ShetiPhian
Signals | MineMaarten
Simple Void World | modmuss50
Simply Jetpacks | Tomson124
Snad | TheRoBrit
Sonar Core | Ollie_Lansdell
Soot | BordListian
Soul Shards: The Old Ways | SgtPunishment
SplashAnimation | asiekierka
Steve's Carts Reborn | modmuss50
Storage Drawers | jaquadro
Storage Drawers Extras | jaquadro
TOP Addons | DrManganese
Tesla Core Lib | Face_of_Cat
Thaumcraft 6 | Azanor
Thaumic Inventory Scanning | BlayTheNinth
Thaumic JEI | Buuz135
The Lost Cities | McJty
The One Probe | McJty
The Twilight Forest | Benimatic
Thermal Cultivation | TeamCoFH
Thermal Dynamics | TeamCoFH
Thermal Expansion 5 | TeamCoFH
Thermal Foundation | TeamCoFH
Thermal Innovation | TeamCOFH
Thut's Elevators | patnevis
ThutCore | patnevis
Tinkers Construct | mDiyo
Tinkers' Tool Leveling | bonusboni
TipTheScales | jaredlll08
TorchMaster | xalcon
Translocators | covers1624
Traverse | ProfessorProspector
UniDict | WanionCane
ValkyrieLib | ValkyrieofNight
WanionLib | WanionCane
Waystones | BlayTheNinth
Wireless Crafting Terminal | TheRealp455w0rd
Woot | Ipsis
XNet | McJty
xNICEx | McJty
Xtones | TehNut
YABBA | LatvianModder
ZeroCore
==============================================
I Cant do anything I reported the issue here because I thought that maybe someone would have an answer for what was going wrong, I would still like an answer bc I will continue to use the same version of the mod until the modpack that I am using updates to rv6. and updates all related mods as well. I have energy cells hooked up to it if you took a look at the images you would have seen that. I apologize for sounding hostile I was just expecting more than 4 lines of text that don't help at all. I would really love to see what the mod developers make of this problem. if they would download the mod to see the bug themselves I can get them whitelisted on the server that I'm playing on. Or if you want me two I will run through the whole process of making my set up in creative and record the process and when the bug happens.

**Comment by yueh** [comment]
This is pretty much a user error like using the wrong pattern type, not returning the result or similar.

**Comment by Andrey1661** [comment]
@ToxicSnow, do you use level emitter within your configuration for controlling growth accelerators? It seems, when level emitter with inserted crafting upgrade and mode set to "Emit redstone to craft item" lead to the problem you described. Switching mode to "Emit redstone while item is crafting" solved the problem in my case.
