### ISSUE TITLE
P2P over Quantum Bridge doesn't work

### ISSUE THREAD

**Issue by Mr3DAlien** [AppliedEnergistics/Applied-Energistics-2#3796]
Hello There, so The Title basically says everything, I try to create a p2p tunnel over a quantum bridge, but the system just starts and stops again. Here is a Picture
![2018-10-22_18 26 01](https://user-images.githubusercontent.com/28678215/47304890-302b9a80-d628-11e8-8122-1df1f9a79b27.png)
![2018-10-22_18 28 32](https://user-images.githubusercontent.com/28678215/47304937-50f3f000-d628-11e8-90f4-549ec3870281.png)
![2018-10-22_18 28 36](https://user-images.githubusercontent.com/28678215/47304943-53564a00-d628-11e8-92c3-05d1d40dab40.png)

**Comment by yueh** [comment]
The left one isn't powered or doesn't receive enough power to stay active.

**Comment by Mr3DAlien** [comment]
How do i get enough power ?

**Comment by ZaxLofful** [comment]
Put generators on the left side, the tunnel requires power on both sides; you cannot use the first side of a tunnel to power the second side of a tunnel....You can however embed networks in each other.

Lava generators are good or coal generators. You just need something on the other side making power and then you can transfer items through the tunnel and into the generator. Just takes a bit more thinking and steps.

**Comment by Mr3DAlien** [comment]
I found the Problem, the Problem was the Quartz Cable on the Me Controller, because the Quantum Bridge also needs a Channel the work, and because of that it didn't work

**Comment by mindforger** [comment]
Also please concider using me energy cells to increase the internal system storage to compensate surges
