### ISSUE TITLE
Blocking mode doesn't work with Thermal Expansion machines

### ISSUE THREAD

**Issue by ThatOneCheetah** [AppliedEnergistics/Applied-Energistics-2#3798]
**Describe the bug**
As the title says, when queuing a crafting job for a stack of glass, only one of the furnaces is used, instead of all furnaces concurrently. Each furnace is set to have input/output face the interface. The crafting CPU is 3x2x1 ( W x H x D ), consisting of 1x crafting unit, 2x co-processors and 3x 4k crafting storage units.

**To Reproduce**
Create the setup mentioned above, insert a processing pattern for sand->glass into the interface, queue a large crafting job for glass. All AE2 devices are connected to the same Glass Fluix Cable; which is connected to one side of the ME Controller.

**Expected behavior**
Sand is inserted into each furnace one-at-a-time to allow parallel processing for maximum speed. This is however not the case. Instead, all sand (up to 64) for one job is shoved into one furnace.

**Additional context**
![image](https://user-images.githubusercontent.com/9394711/47315101-dd5fdc00-d643-11e8-8bd3-487071e2e2ee.png)

**Environment**
This bug occurs in SP and MP.

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-3
- CoFH Core Version: 4.6.1.22
- Thermal Foundation Version: 2.6.1.22
- Thermal Expansion Version: 5.5.2.39
- Forge Version: 14.23.5.2772

**EDIT:** The processing pattern was created with one sand in the centre of the 3x3 crafting grid, outputting 1 glass to the centre of the 1x3 output grid. Not sure if this is relevant.

**Comment by yueh** [comment]
This is pretty much a limitation on how we are able to detect a busy machine and many mods lately make it pretty much impossible to use.

The only reliable option would be that Forge adds something to signal that a tileentity/machine is working. Which most likely won't happen, because it would make it too easy and reliable for modders to improve the QoL for players.

**Comment by ThatOneCheetah** [comment]
The only current fix (though probably too dirty) I can currently see is using [this](https://github.com/CoFH/ThermalExpansion/blob/24de8fafb7690ae826c801c52ccb234442d92235/src/main/java/cofh/thermalexpansion/block/machine/TileMachineBase.java#L471) function.

As in:
`if getScaledProgress( 1 ) > 0 then machine is busy`

**Comment by yueh** [comment]
If you can convince every mod out there to use this class as base tile entity, we can use it. Otherwise no.

**Comment by ThatOneCheetah** [comment]
Hence I said why it's probably still too dirty of a "fix". What I don't understand is that I remember this bug not existing a while back in a modpack running 1.7.10; though whatever has changed in the major versions of any of the related mods probably "broke" it.

Secondly, as a fellow programmer I understand the frustration, but giving off these vibes to users who are simply reporting a bug and attempting to help, is not a desirable trait. Just a word of advice, no offense intended.
