### ISSUE TITLE
Some of cables and terminals will be hidden.

### ISSUE THREAD

**Issue by dnplayer** [AppliedEnergistics/Applied-Energistics-2#3799]
When updating to the latest version, the cable and terminal became invisible.
Especially when you move the dimension the symptoms worsen.

![2018-10-22_17 06 20](https://user-images.githubusercontent.com/44361369/47334208-11c5ad80-d6c1-11e8-9e9d-f1cc56f0c238.png)
![2018-10-22_17 09 30](https://user-images.githubusercontent.com/44361369/47334217-1ab67f00-d6c1-11e8-9bbc-422f9254a942.png)

Mod list
[modlist.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/2504394/modlist.txt)

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-3
- Forge Version:14.23.5.2772
- Optifine Version:1.12.2_HD_U_E2

I am Japanese. And I use translation.

**Comment by yueh** [comment]
Please do not use optifine, it causes all sorts of rendering bugs. Due to being closed source, we do not know what it does and therefore it is impossible for us to try avoiding them.

**Comment by Pingger** [comment]
CTM (ConnectedTexturesMod) might also be an issue, also optifine includes CTM, so this mod is a duplicate
