### ISSUE TITLE
P2P Tunnel Glasses' or link viewing

### ISSUE THREAD

**Issue by AlgorithmX2** [AppliedEnergistics/Applied-Energistics-2#38]
some form of tracking or "seeing" P2P links or a tool that gives an id in chat

Originally Posted by mstaaf

This issue was migrated; For original details see http://ae-mod.info/Tracker/0369/

**Comment by Pyeroh** [comment]
Well, it's almost been a year since the first post, any news about it ? :/

**Comment by thatsIch** [comment]
working on different approach

**Comment by leagris** [comment]
The network tool sound like the appropriate tool to probe P2P source and destination.
Without adding yet another GUI, it could at least display locations of related parts into chat.

**Comment by fchtngr** [comment]
Did anything ever happen with this?
