### ISSUE TITLE
Infinite Liquid

### ISSUE THREAD

**Issue by Grobes** [AppliedEnergistics/Applied-Energistics-2#3804]
**Describe the bug**
A tank connected to a Fluid Storage Bus is filled infinitely.

**To Reproduce**
This seems to occur when a specific fluid is being pumped into a Fluid Interface and on another section of the AE network the fluid is stored via a Fluid Storage on a tank. 

If the tank becomes full the interface will fill with backlogged fluid as expected. However if fluid is then slowly pumped out of the tank using a pipe, at some point the fluid in the Fluid Interface is no longer consumed to fill the tank and the tank is kept topped up without consuming any more fluid from the interface.

I was making soul sand using witch-water pumped into a drum and despite switching off the output of my generation and disconnecting the Fluidduct from the Fluid Interface, it kept going, using 1000ml of witch-water every second or so without any consumption of fluid from the Fluid Interface.  I removed the Fluid Interface after 600 buckets of fluid had been generated and then the Drum connected to the Fluid Storage began draining.

**Expected behavior**
I would expect the fluid to be consumed from the interface.

**Additional context**

**Environment**
Gregblock modpack 1.12
Using Gregtech Drums as the storage container. Pumping fluid into the Fluid Interface with Hardened Fluiducts from Thermal Expansion.

**Comment by yueh** [comment]
Already fixed
