### ISSUE TITLE
Naming P2P buses

### ISSUE THREAD

**Issue by 016Nojr** [AppliedEnergistics/Applied-Energistics-2#3805]
**Describe the feature**
Right clicking on a linked P2P bus to access some kind of "frequency settings gui", in that gui you could set a name for the frequency that could show up in WAILA/TOP when looking at it or a name hovering over the bus when looking at it, specify what kind of p2p bus (Yes, I know you can right click with stuff too to set the type) and other things that might be useful.

Maybe even add a "P2P Terminal" that will group buses in a list after each frequency, were each p2p bus would appear and you could hover over to see the coordinates to that specific bus.

**Reasons why it should be considered**
It's a feature that I and I think many others would agree should be implemented, it would almost be a final touch to the new frequency colouring on the p2p buses. It will help organize the buses even more.

**Comment by yueh** [comment]
That is already supported by vanilla itself.

**Comment by 016Nojr** [comment]
What about the p2p terminal @yueh?
