### ISSUE TITLE
See Through blocks

### ISSUE THREAD

**Issue by zezreli** [AppliedEnergistics/Applied-Energistics-2#3806]
I have not check all the blocks but most of them are see Through and makes other blocks see through like, if you place a me- controller and have a tunnel under you will see the tunnel from up above through all blocks in between.

**Describe the bug**

blocks create x-ray vision
**To Reproduce**

I have no clue how to reproduce it, if I knew I probably knew how to fix it
**Expected behavior**

no see through them, they should shine in different colours if I remember exactly
**Additional context**

![2018-11-02_19 40 59](https://user-images.githubusercontent.com/27296782/47934575-e8cec500-ded7-11e8-8f29-c3a450076c5b.png)
![2018-11-02_19 41 04](https://user-images.githubusercontent.com/27296782/47934576-e9675b80-ded7-11e8-9281-519505a04411.png)

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-3
- Forge Version:  14.23.5.2772

**Comment by mindforger** [comment]
I highly suspect the presence of optifine, please try again without

**Comment by zezreli** [comment]
>           I highly suspect the presence of optifine, please try again without

I have removed optifine, well I have disabled it in the twitch launcher, do you think that could be the problem that the config files and the actual file is still there but not used?

**Comment by zezreli** [comment]
it didn't help

**Comment by 016Nojr** [comment]
Try with just AE2, if it's fixed disable one mod at a time in your pack until it's fixed. I doubt it's an issue caused by AE2 only

**Comment by mindforger** [comment]
@zezreli see if you can narrow down your modpack to a minimum to reproduce this bug and then create a forced crash by pressing and holding F3 + C until ist crashes (while in game not in menu)

then post the crashlog to pastebin and link it here, so we can see a bit more details on your launcher, modpack and system, do not attach the file directly or post the content unspoilered into a giant wall of text please :)

**Comment by zezreli** [comment]
@mindforger, okey I will do that, mostly because I want to help improve the mods I use, it will take a few days to go through the modpack because if I include ae2 there are roughly 300 mods in the mod pack, I'll send an update asap.

**Comment by mindforger** [comment]
@zezreli thank you for your continuing help to find the root of this problem :)

**Comment by zezreli** [comment]
Yup that is the problem, if you have ever installed optifine together with AE2 you need to reinstall the AE2 if you remove optifine, because optifine changes something in the files, corrupt them in a way.

**Comment by zezreli** [comment]
interesting

**Comment by zezreli** [comment]
its like without power the blocks looks fine, but as soon as you give it powers they bugs

**Comment by zezreli** [comment]
but why only in the old version where optifine once existed and not in the version I created today.

**Comment by zezreli** [comment]
the F3 + C doesn't work, do not crash the game
