### ISSUE TITLE
Start up crash

### ISSUE THREAD

**Issue by TheSnowyChickens** [AppliedEnergistics/Applied-Energistics-2#3808]
**Describe the bug**
Crash on start up. (step 2? from Forge (pre inizialation))

**To Reproduce**
Start MC with the mods in the crash report list.

**Expected behavior**
It should start.

**Additional context**
Log: 
[2018-11-05-1.log.gz](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/2546637/2018-11-05-1.log.gz)

Crash report: https://paste.dimdev.org/qiwufenoya.mccrash

**Environment**
![grafik](https://user-images.githubusercontent.com/29357962/47973593-97743080-e0a5-11e8-932c-259ac9bb885c.png)

I use this custom java arguments:
-Xmx9G -XX:+UseG1GC  -Dsun.rmi.dgc.server.gcInterval=2147483646  -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20  -XX:G1ReservePercent=20  -XX:MaxGCPauseMillis=50  -XX:G1HeapRegionSize=32M -XX:ParallelGCThreads=4  -XX:+UseStringDeduplication  -XX:+UseCompressedOops  -XX:+UseCodeCacheFlushing  -XX:+AggressiveOpts  -XX:+AlwaysPreTouch -XX:+UseLargePagesInMetaspace  -Dfml.ignoreInvalidMinecraftCertificates=true  -Dfml.ignorePatchDiscrepancies=true  -Dfml.debugExit=true

I use: Java 8, Update 192

I have updated these mods:
- Animania -> v1.6.0.2 
- AE2 -> Stable 3, but with Stable 1 this crash also appear
- Better Questing -> v3.5.274
- Botania -> v1.10-357
- C&B -> v14.27
- Comforts -> v1.3.1
- Forgelin -> v1.8.0
- FTBLib -> v5.3.1.58
- FTBUtilities -> v5.3.0.53
- JEI -> v4.13.1.222
- Mantle -> v1.3.3.39
- MetalChests -> v3.8.1.gfd0d85a
- Placebo -> v1.5.0
- PlusTIC -> v6.5.3.0
- ProportionalDestructionParticles -> v1.2.4
- RebornCore -> v3.10.4.348
- RefinedStorage -> v1.6.9
- TConstruct -> v2.11.0.106
- TechReborn -> v2.17.7.840
- Tinkers Tool Leveling -> v1.1.0
- Woot -> v1.4.7

and added:
- Better Foliage
- Dynamic Surroundings
- 3D Particles

**MC**
- Minecraft Version: 1.12.2
- AE2 Version: Stable 3 Rv6
- Forge Version: 2772

**Comment by covers1624** [comment]
I believe you need to update CTM, ae just happens to be the one loading that class.

**Comment by TheSnowyChickens** [comment]
Ahh okay, this fixed it, thx. :)

But now, I crash with an Immersive Engineering error. xD
Here is the error: https://paste.dimdev.org/ixifokolul.mccrash

I close this issue now^^
