### ISSUE TITLE
Add support to the In Game Wiki mod (IGW)

### ISSUE THREAD

**Issue by FireBall1725** [AppliedEnergistics/Applied-Energistics-2#381]
It would be nice to add AE2 support to the IGW mod by MineMaarten 

https://github.com/MineMaarten/IGW-mod/

This way people could see the Wiki about AE2 machines in game, instead of having to refer back to the website.

**Comment by Blue64** [comment]
Snapshot of current wiki is bad idea, as it would cause problems with older versions, you'll instead desire to include an IGW page for each item in the .jar file of AE2, it's lots of work, but allows for updated content without breaking the feature for those whom haven't yet updated or play offline, which most players tend to do for various reasons.

Solid idea though as the IGW is very useful (I use it with PneumaticCraft, lots of info, pictures, and links both internal & external), big +1 from me minus the snapshot idea, it's an in game wiki page minus the need for internet is the basic idea behind IGW Mod.

**Comment by thatsIch** [comment]
This makes sense
