### ISSUE TITLE
Client crash searching ores in JEI serch with AE mod?

### ISSUE THREAD

**Issue by chunkedelement** [AppliedEnergistics/Applied-Energistics-2#3810]
**Description:**
When searching for tin, copper, bronze, or other metals in JEI the client will crash to desktop. Also, crashes when running a server. Client crashes but server does not. I tried disabling the metals/ores in the mystical world config but still get the same result. The crash log states its a facade but unsure why.
If you remove/disable the Mystical World mod and do the search again the game is fine. Not sure what is causing this is it a metals conflict possibly or a AE2 conflict? Thanks for your help.
**Basically this:**
Ingredient Mod: Applied Energistics 2
Ingredient Info: 1xitem.appliedenergistics2.facade@0 appliedenergistics2:facade nbt:{damage:0,item:"mysticalworld:copper_block"}
**Environment:**
AE2 version: RV6-Stable-3
Mystical World Version: 1.12.2-1.0.1
Forge Version: 1.12.2-14.23.5.2772
**Logs:**
[crash-2018-11-05_23.09.13-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/2558727/crash-2018-11-05_23.09.13-client.txt)
[crash-2018-11-06_21.58.48-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/2558728/crash-2018-11-06_21.58.48-client.txt)

**Comment by Daenyth** [comment]
I'm getting this too: paste.ee/p/MXvQY

**Comment by krisjenner** [comment]
same crash only with Forge Multipart stone cover

[crash report](https://gist.github.com/krisjenner/deb3f1de3f77edd5fa518516fc7eb13a)
