### ISSUE TITLE
JEI/AE2 bug FPS drop 

### ISSUE THREAD

**Issue by ospis12** [AppliedEnergistics/Applied-Energistics-2#3813]
When JEI is opened and AE2 facades are shown (take majority of JEI screen) FPS drops from 90+ to low 10s. When JEI shows other blocks/items FPS is around mid 20s.

**Expected behavior**
Fps shouldn't drop so drastically 

**Additional context**
https://imgur.com/a/QzLYovb

**Environment**
StoneBlock 1.27r1
Lenovo y700-15
i5-6300HQ

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-3
- Forge Version: 14.23.5.2768
- JEI Version: 4.13.1.222

*Edit:
It looks like it has more to do with JEI or JEI integrations. 
To be Closed

**Comment by chunkedelement** [comment]
is this related in any way to #3810?

**Comment by covers1624** [comment]
No, that is a crash.
