### ISSUE TITLE
CraftingManager fallback log spam

### ISSUE THREAD

**Issue by Orygeunik** [AppliedEnergistics/Applied-Energistics-2#3822]
**Description the bug**
With automatic crafting, when the electric circuit begins to craft (from the modification of industrial craft 2 experimental), the following warning pours in the server logs with a huge frequency:

> [00:09:53] [Server thread/WARN] [AE2:S]: Using CraftingManager fallback: Recipe <ic2:194> for output <1xic2.crafting@1> rejected inputs [1xic2.cable@0, 1xic2.cable@0, 1xic2.cable@0, 1xitem.redstone@0, 1xic2.plate@3, 1xitem.redstone@0, 1xic2.cable@0, 1xic2.cable@0, 1xic2.cable@0]. NOT FOUND, please report.

However, the fact that many recipes are from industrial craft...
[Issues in IC tracker](https://bt.industrial-craft.net/view.php?id=2425)

**To Reproduce**

1. Make the template wiring
2. To start production
3. Logs are clogged

**Environment**
MP
jre1.8.0_181 (Upgrade to 191 in queue)
Mods (excluding dependencies):

- buildcraft-7.99.19
- buildcraft-compat-7.99.15
- forestry_1.12.2-5.8.2.372
- industrialcraft-2-2.8.102-ex112
- jei_1.12.2-4.13.1.220
- ProjectRed-1.12.2-4.9.1.92
- UniDict-1.12.2-2.9.1
- TConstruct-1.12.2-2.11.0.106
- Thaumcraft-1.12.2-6.1.BETA26
- practicallogistics2-1.12.2-3.0.4
- ironchest-1.12.2-7.0.52.837

---

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-4
- Forge Version: 1.12.2 - 14.23.5.2772

Full log:
[Debug.log](https://gist.github.com/Orygeunik/4d3618516a65255a478dc3851278c57d)

**Additional context**

In JEI:

![1](https://user-images.githubusercontent.com/6960655/48513546-208d2380-e86d-11e8-81ae-f311e970c8ca.png)

In game craft-book:

![2](https://user-images.githubusercontent.com/6960655/48513549-208d2380-e86d-11e8-8f0a-9c64416b4d00.png)

Template:

![3](https://user-images.githubusercontent.com/6960655/48513547-208d2380-e86d-11e8-8797-9e6350e22de7.png)

**Comment by yueh** [comment]
This basically indicates a broken recipe and we have to fall back to a very performance heavy method to find a matching one. With the ingame crafting book not being able to display vanilla redstone, some other mod could replace it somehow and thus causing it.

It's really nothing we can avoid. It has to be reported to whoever manages the modpack and hope they can forward it to the mod adding this particular recipe to hopefully fix it.

**Comment by NillerMedDild** [comment]
I'm guessing the recipe is broken in the in-game crafting book, because it uses `ore:dustRedstone`.
