### ISSUE TITLE
FoolCraft : Forge 12.23.4.2760 : Pack Version Release 1.5.2 : Loading into a multiplayer server errors

### ISSUE THREAD

**Issue by EmeraldKnight79** [AppliedEnergistics/Applied-Energistics-2#3823]
FoolCraft : Forge 12.23.4.2760 : Pack Version Release 1.5.2 : Loading into a multiplayer server errors

I click on the server in my list then on "Join server". The world loads then within 5 to 15 seconds (98/100 times) I get kicked and Minecraft gives the added crash reports.

As I am not the server owner nor its admin there is not much I can do on the server side and I have been told that we are waiting for the new FoolCraft server pack to become available.

crash-2018-11-16_20.30.21-client
https://pastebin.com/5uZYFQuk
crash-2018-11-16_20.17.59-client
https://pastebin.com/tcvuQzVi
and there is another 150 of them from today only :(

Acer Predator G9-593
Intel Core i&-6700HQ
16GB RAM with 8GB allocated to MC
2GB NVidia GeForce GTX 1060
MP version of Minecraft

Minecraft 1.12.2
AE2 rv6-alpha-4
Forge 12.23.4.2760

Any hints on 
1. What I am doing wrong? 
2. What can I do to solve this issue?
3. Am I just trying to rush things and need to wait for a pack upgrade?

Not very technical since I had my mini stroke so sorry if I waste anyone's time. I play Minecraft to take my mind of my other physical issues as it requires very little hand to eye co-ordination and I can get hints and tips from youtube to help me out.
Thank you.
EK

**Comment by yueh** [comment]
It is a pretty outdated version, but the stacktrace isn't really indicating  that an update should fix it.
At first glance it looks like some rendering/"performance" mod could incorrectly change the normal rendering behaviour.

The best approach would be to wait for the modpack to be updated with all mods. If AE2 is horribly outdated, it is pretty likely that this also applies to other mods and might already be fixed upstream.
