### ISSUE TITLE
Browser Tabs

### ISSUE THREAD

**Issue by MegaBleeder** [AppliedEnergistics/Applied-Energistics-2#3824]
Being able to open "tabs" like in a web browser for multiple searches 

Basically just have it work like opening additional tabs like in Google Chrome for productivity

In large modpacks keeping track of rabbithole recipes it can get very confusing but with multiple tabs you could easily track a recipe through multiple mods and steps to keep a project on track

**Comment by yueh** [comment]
Manual crafting is not the ultimate goal of AE, therefore we should not encourage it further.
