### ISSUE TITLE
Items deleted from Colossal Chest when AE2 System if attached to it.

### ISSUE THREAD

**Issue by Furious1964** [AppliedEnergistics/Applied-Energistics-2#3825]
Bug Report

I put items into the chest via an Ender pouch/chest and the items show up but when I finished adding more, I lost 70% of everything I had.
Steps to Reproduce (for bugs)

Added items.
Added more items and look into the AE2 System.
Logged of and then on again and I lost stuff again.
Replaced AE2 System with RFTools Storage Scanned and same thing.

Logs

Client/Server Log:
Crash Log:

Client Information

Minecraft Version: 1.12.2
Forge Version: 14.23.5.2775
Modpack Version: Stoneblock Mod Pack 1.0.28
Server/LAN/Single Player: Single Player
Optifine Installed: Yes, HD U E2
Shaders Enabled: No

Added an RFTools Storage Scanner to the chest in place of the AE2 System and it does the same thing. When I place items into the chest via those systems, when I log off and on again the items are deleted.

I made both a 9x9 and a 20x20 wooden chest and in both instances, items are deleted upon logging into the game.
[latest(1).log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/2591901/latest.1.log)

**Comment by yueh** [comment]
There is nothing we can do when an external inventory decides to not save its contents correctly.

**Comment by Furious1964** [comment]
The Mod maker is saying it's not their fault, but AE2 and I feel like I'm in a Tennis Match right now as you serve the ball back.

**Comment by yueh** [comment]
Also as recommendation these massive inventories hooked to a storage bus can be a major performance issue and there is nothing we can do about it as Forge does not care to improve it anyhow.

**Comment by Furious1964** [comment]
Never had a problem with that when I was playing Revelation. I installed a mod called Ender Rift that basically allows for infinite storgage...at a power cost. Never had any performance issues with that.
