### ISSUE TITLE
Fluid Formation plane does not place over flowing liquid

### ISSUE THREAD

**Issue by GeekBeam** [AppliedEnergistics/Applied-Energistics-2#3839]
**Describe the bug**
ME Fluid formation plane refuses to place liquid source block over a flowing liquid

**To Reproduce**
place water source block in a block space so that it will form a flowing liquid block where the formation plane operates, attempt to store any liquid in the network that the formation plane exists.
**Expected behavior**
I would expect the fluid formation plane to place a source block into the expected space
**Additional context**
pic of formation plane, with water flowing into it's block space, fluid interface is being filled with water
https://puu.sh/C7Rl8/e8949d020d.png
**Environment**
currently in the Enigmatica 2 modpack, testing in an isolated environment (forge, JEI, Rftools for power, Mekanism for creative tank) yields the same results.

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable4
- Forge Version: 14.23.5.2768

**Comment by GeekBeam** [comment]
upon testing other mods to see if THEY could do this, it seems that integrated dynamics, and Actually Additions have this exact same issue. Immersive Engineering does seem to be able to place within flowing blocks with the fluid outlet though.

**Comment by yueh** [comment]
Not sure, if this is even possible currently. As far as I have seen, pretty much any water block is reported as still water. Flowing water does not be used at all. Which would also explain why other mods have issues with it.

We could probably handle water in a special way. But that would mean only water will work. Any other fluid probably won't. Or sometimes it works, sometimes not. Simply to inconsistent to justify it. Also with 1.13 on the horizon (hopefully) and its changes to the fluid in vanilla, it's most likely wasted time now.
