### ISSUE TITLE
[BUG]Problem with Advanced Inscriber , AE2 Rev6 Stable 4 and CustomNPC

### ISSUE THREAD

**Issue by lays24mc** [AppliedEnergistics/Applied-Energistics-2#3840]
The Advanced Inscriber (AE2Stuff) will no longer accept needed materials as soon as CustomNpc is used. See screenshot:

**(Advanced Inscriber not work)**
![notwork](https://user-images.githubusercontent.com/38819519/49103233-14489380-f27b-11e8-93f4-53c41cd32129.png)

**(Inscriber works)**
![work](https://user-images.githubusercontent.com/38819519/49103268-262a3680-f27b-11e8-8c3b-cf06b245ab62.png)

Noppes say it isn't his problem. Custom NPC check NBT Data and not Recipes since 1.12.2. So I don't now which of this two Mods (AE2Stuff or AE2) have a problem :/

- Minecraft Version: 1.12.2
- AE2 Version: 1.12.2-rev6-stable-4
- Forge Version: 2784

**Comment by yueh** [comment]
Wrong mod, this is just AE2.

**Comment by lays24mc** [comment]
> Wrong mod, this is just AE2.


I am a bit confused. I am reporting a problem with AE2 Rev6, AE2Stuff and CustomNPC and closed due to wrong mod?

The problem exists only from AE2 Rev6. Everything works wonderfully with AE2 Rev5.

**Comment by mindforger** [comment]
You have a problem with an ae2stuff machine, report it to ae2stuff. That is what yueh said

**Comment by lays24mc** [comment]
Ah okay. Than i understand it wrong :). Sorry
