### ISSUE TITLE
Subnetwork level emitters - viable vs extractable items

### ISSUE THREAD

**Issue by myrddraall** [AppliedEnergistics/Applied-Energistics-2#3841]
**Describe the feature**

I have a sub network with the storage bus configured to `insert only` and report inaccessible items set to `Yes`

I would have expected that level emitters on the sub network would "see" the items in the main network
they do if the storage bus is set to `extract` or `bi-directional`.

it would be nice if they followed the visibility setting or if storage buses could be configured with view cells and only be able to read/extract items allowed by the view cell

**Reasons why it should be considered**

i have a system that autocrafts  rich slag which is being consumed constantly.  It uses cobble stone and i want it to only craft with the cobble overflow that exists in the subnetwork. however if the storage bus is `insert only` the level emitters always think there is no rich slag and craft all the overflow cobble even when there is enough rich slag. if the interface is set to extract then the level emitters work, but the crafting pulls from my main networks supply of cobble

**Additional Context**

**Comment by Technici4n** [comment]
Closed by #5614.
