### ISSUE TITLE
A crash report

### ISSUE THREAD

**Issue by JackMeds** [AppliedEnergistics/Applied-Energistics-2#3843]
A crash report（My client cannot start, but the server can start）
[crash-2018-11-28_10.19.21-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/2622846/crash-2018-11-28_10.19.21-client.txt)

Use java 191
- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-4
- Forge Version: Forge 14.23.5.2784

**Comment by yueh** [comment]
Some mod is changing core minecraft code in an inconsistent way. Which one I cannot say sadly.

The best idea is to start removing mods until it stops, starting with everything listed under coremods.

**Comment by JackMeds** [comment]
thank you

**Comment by covers1624** [comment]
I believe you need to update CTM.

**Comment by JackMeds** [comment]
> 我相信你需要更新CTM。

thanks for your help，my game can start again

**Comment by yueh** [comment]
@covers1624 Was there a way to define a min version for an optional dependency? Cannot remember currently.

**Comment by covers1624** [comment]
`[min')` iirc.
