### ISSUE TITLE
Applied energistics 2 compatibility with rs?

### ISSUE THREAD

**Issue by salvo18** [AppliedEnergistics/Applied-Energistics-2#3848]
Yeah so, i have a custom modpack with ae and rs and i wanted to make them view each other disks (maybe with some cables?) to use addons from both parts. Is that possible?

**Comment by TheSnowyChickens** [comment]
RS 1.6 removed that ability, to connect both systems. :/

**Comment by salvo18** [comment]
@thesnowychickens aw, so if i download the 1.5 version what i'm losing in added things?
