### ISSUE TITLE
I created a modpack on version 1.12.2 and everything

### ISSUE THREAD

**Issue by brachy84** [AppliedEnergistics/Applied-Energistics-2#3851]
Crash startup post initalisation
I created a modpack (200 mods)
crash says something about forestry but i dont have forestry
https://pastebin.com/tRy0Z1B5
Mods: too many
- Minecraft Version: 1.12.2
- AE2 Version: all
- Forge Version:14.23.5.2770

**Comment by yueh** [comment]
Some mod registers invalid tile entities for spatial io. Nothing we can really avoid. Your only option is to find out which mod causes it.
