### ISSUE TITLE
Color applicator offhand cable placement

### ISSUE THREAD

**Issue by ilightwas** [AppliedEnergistics/Applied-Energistics-2#3854]
**Describe the feature**

The ideia is to select a color in the color applicator, put it in the offhand and when a cable is placed it will place a cable with the selected color in the applicator.

**Reasons why it should be considered**

When playing I saw a lot of situations that this would help. Not having to craft a specific colored cable every time or having to place all the cables and go back coloring them. Also I see an improvement when placing cables next to each other when you don't want them to connect since placing a standard one would cause the network to connect and refresh the connections until you go and color it.  This would go nice with #88  but I suggest getting the color with only holding shift and scrolling while aiming at the colored cable.

**Comment by yueh** [comment]
Sounds pretty interesting and is certainly a nice QoL feature.

Just no idea about any timeframe for it. PRs would be really nice for these smaller features.
Could be a bit difficult to handle the colour selection. E.g. if both active items support shift + scrollwheel.
Also it would need a better indicator about running out of dyes.

**Comment by TherminatorX** [comment]
Just popped in to suggest this very thing, though the pull request for this is over a year old now.
