### ISSUE TITLE
Interface Connectors

### ISSUE THREAD

**Issue by Vonr** [AppliedEnergistics/Applied-Energistics-2#3855]
**Describe the feature**
New cable called Interface Connector. The Interface Connector will let you connect multiple inventories to one interface, this allows for a more effective blocking mode when needed. It connects to all inventories, including machines so that the interface can recognise them.

**Reasons why it should be considered**
Some operations (cough cough, auto fusion crafting) requires a more advanced setup to properly function. The Interface Connector will allow for such tasks to be simplified or made possible.

**Additional Context**
Interface Connector can be made quite expensive as nobody will be doing complicated projects early game. There should also be a way to disconnect them from each other (or different colors) in the case where you want to build in a small area.

**Comment by yueh** [comment]
This would be way to narrow in terms of uses as well as the blocking mode being already nearly impossible to achieve for a single machine. (As long as forge does not provide a generic way to have a machine signal it is working).

Also most/all of it is already possible with just AE and some creativity. Therefore it would only make it easier, which is usually enough reason to reject it.
