### ISSUE TITLE
Crashes when trying to install

### ISSUE THREAD

**Issue by joshuaxlino** [AppliedEnergistics/Applied-Energistics-2#3856]
game crashes whenever it tries to load this mod
![screenshot 36](https://user-images.githubusercontent.com/25727040/49974321-9933de00-ff06-11e8-9b7f-e5c053b7c19e.png)

- Minecraft Version: 1.12
- AE2 Version: appliedenergistics2-rv6-stable-4.jar
- Forge Version: forge-14.23.5.2796

**Comment by Ommina** [comment]
Post (a link to) the full crash report.  Sadly, a screenshot tells us nothing.

**Comment by joshuaxlino** [comment]
Ommina i have fixed it, after updating the core mods it stopped crashing
