### ISSUE TITLE
minMeteoriteDistance Does not seem to have an effect.

### ISSUE THREAD

**Issue by KaneHart** [AppliedEnergistics/Applied-Energistics-2#3857]
Overall it seems that changing the Meteorite Minimal Distance has no effect.

**Describe the bug**
Changed the config example
I:minMeteoriteDistance=4000
I found Meteorite about 100 blocks away from spawn  lol. (near 0,0).

- Minecraft Version:  1.12.2
- AE2 Version: v6-stable-4
- Forge Version: 14.23.5.2768

**Comment by Ommina** [comment]
minMeteoriteDistance is the minimum distance between individual meteorite (clusters), not the minimum distance from spawn to the closest meteor.

**Comment by KaneHart** [comment]
Ohhh, Thanks. I guess there is no option for this?
