### ISSUE TITLE
[Question] Spatial Storage Dimensions

### ISSUE THREAD

**Issue by MonfGeiger** [AppliedEnergistics/Applied-Energistics-2#3860]
This is more of a question than a feature request or bug report, so I would like input on it if possible, as researching the ftb wiki or the ftb gamepedia wiki shows nothing relevant to what im looking for. I am planning on making a max size Spatial Storage setup (128 * 128 * 128) so I can store more "volatile" creations into it so they don't erase my base and other setups

Now im trying to get it exact on the money, but when I check the spatial IO port block, it says my setup is 128 * 126 * 128. Now I forget if the dimensions are measured by x,y,z or x,z,y, but I would like to know if I need to move my setup down a bit more, widen it, make it taller, etc..., just what the missing 2 digits associate to

respond when able, thank you for doing so

**Comment by yueh** [comment]
They should use the normal minecraft coordinates, but not 100% sure currently.
Best idea is to simply make a small 2x3x4 one or so and measure it.
