### ISSUE TITLE
Preinitilization crash

### ISSUE THREAD

**Issue by BetzerLIVE** [AppliedEnergistics/Applied-Energistics-2#3862]
hi! I just downloaded, direwolf20' 1.12.2 mod pack and there's a problem with applied energistic.

**Describe the bug**

it happens that when the minecraft forge launcher is at preinitialization step applied energistic makes it crash
telling me this : net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Energistics 2 (appliedenergistics2)

**To Reproduce**

download lastest forge release
download lastest direwolf 1.12.2 release
throw all the .jar files in the mods folder in .minecraft.
try launching forge with at least 4gb ram allowed to minecraft

**Expected behavior**

at pre initialization phase, minecrraft should crash and give you this error message :
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Energistics 2 (appliedenergistics2)

**Additional context**

pastebin of the crash report

https://pastebin.com/PEeVjgWG

**Environment**

here's all the mods in the pack
https://www.feed-the-beast.com/projects/ftb-presents-direwolf20-1-12/files/2615409

- Minecraft Version: 1.12.2
- AE2 Version: tried all release in 2018
- Forge Version: 14.23.5.2795 for minecraft 1.12.2

Thank you!

**Comment by mindforger** [comment]
Try using a newer Java version, also rv 5 is pretty outdated for 1.12 try one of the later rv 6 

If you feel uncomfortable with changing the modpack ask the author please

**Comment by yueh** [comment]
Should be reported to the modpack. There is nothing we can do as long as they refuse to keep all mods updated.

**Comment by Tahakk** [comment]
@BetzerLIVE problem appears to be on your side, I have no problem starting pack on versions 2.3.0 or 2.4.0 via Twitch Launcher
