### ISSUE TITLE
"Caught exception from Applied Energistics 2" on loading

### ISSUE THREAD

**Issue by Taggerung559** [AppliedEnergistics/Applied-Energistics-2#3864]
I was playing the FTB presents Direwolf20 1.12 modpack, version 2.3.0 with the personal addition of projecte, expanded equivalence, and hammercore, went and restarted my computer and increased the RAM allowance of the pack, and all of a sudden the pack crashes while loading, giving the message:

"The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Energistics 2 (appliedenergistics2)"

This has happened each time consistently with multiple load attempts.

pastebin of the crash report: https://pastebin.com/qw04EBh0

- Minecraft Version:  1.12.2
- AE2 Version: appliedenergistics2-rv5-stable-11.jar
- Forge Version: forge-14.23.5.2796

**Comment by BetzerLIVE** [comment]
i had the same problem just posted about it earlier today

[https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3862](url)

**Comment by Taggerung559** [comment]
My mistake for not looking thoroughly before posting the issue.  The crash logs, etc are pretty much identical, so it's probably safe to close mine then.
