### ISSUE TITLE
Game Crashes when using pattern terminal

### ISSUE THREAD

**Issue by aheroindisguise** [AppliedEnergistics/Applied-Energistics-2#3865]
I took a look at previous errors that were similar but the version is different and other circumstances may also be different.

When inserting a third HSLA Steel ingot from Rotarycraft into a pattern terminal recipe grid (pattern terminal set to Processing Recipe), the game crashes. Upon restarting the same world, the stack of HSLA steel ingots used is gone from existence, and right-clicking the pattern terminal at all causes a crash. 
"The game crashed whilst rendering screen
Error: java.lang.StackOverflowError: Rendering screen"
I am able to break and replace the pattern terminal, but upon attempting to replace the ingots, the same crash happens.

I am able to create other processing patterns without issues, such as the processing pattern for Bedrock Shaft Units.

I am not even sure if the recipe I am attempting to make will work, but this is a hurdle I did not anticipate.

MC version 1.7.10
AE2 version rv3-beta-6  and  rv2-stable-10
Forge version 10.13.4.1614
Windows 10
32 GB Ram
Intel i7 Core 4710HQ @ 2.5GHz

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.12 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
