### ISSUE TITLE
Crash with newer version of AE2

### ISSUE THREAD

**Issue by mxnmnm** [AppliedEnergistics/Applied-Energistics-2#3876]
I crashed with a new version of applied energistics 2 on curse forge but no crash report was made
**Describe the bug**

Crash without a crash report (The reason I think it's ae2 is because of this line that I found in the log "[15:17:37] [pool-8-thread-4/ERROR]: Applied Energistics 2 Integration: java.lang.IllegalArgumentException: argument type mismatch" and the game launched when I went back to an older version so yea)
**To Reproduce**

Have AE2 Version: rv6.stable build 5 and launch it with my modpack.

**Expected behavior**

Expectations-no crash
Reality-crash 

**Additional context**

Not a crash report as one wasn't created but my logs.
https://gist.github.com/mxnmnm/d1689d434c2096894968a60173a51f74

**Environment**
I'm working on my modpack Crystal Progressions but it's using newer versions of mods than the one currently on twitch so if you really need that I can export my current client for you to test with but it's too much of a hassle to do that now when you might be able to fix it just by looking at the log.  

- Minecraft Version: 1.12.2
- AE2 Version: rv6.stable build 5
- Forge Version: 14.23.5.2768

**Comment by Pingger** [comment]
excuse me, but do you even know how to properly create/update mod packs? the log is full of exceptions telling me, that you are using conflicting core mods, and mismatching versions of other mods. you should start looking at cofh mods, ctm, core mods.

and not posting the modlist with the versions isn't helping. try to reproduce this issue with as few mods as possible and then start looking at the conflicting mods.

**Comment by Pingger** [comment]
just one line from your log should make you eonder:
[15:17:40] [main/ERROR]: The item cofh.thermaldynamics.item.ItemCover@4e8c4e2d (item.thermaldynamics.cover) produces empty itemstacks in getSubItems(). This is a major bug in the mod 'Thermal Dynamics'.

**Comment by yueh** [comment]
If minecraft crashes, there will be a crashlog. Plain and simple. (Or at a jvm log in the worst case).
Also we do not even use that particular string anywhere.

This is simply not the place to debug basic modpack problems. Will be reopened in case you can actually provide concrete details about how AE2 might be involved.
