### ISSUE TITLE
Crash white Mod Ancient Warfare 2

### ISSUE THREAD

**Issue by Mantafisch** [AppliedEnergistics/Applied-Energistics-2#3877]
when I insert the mod Ancient Warfare 2 I get the following crash. If I take Applied Energistics 2 out it works fine. what can be done so that the two mods get along?

**Describe the bug**

unfortunately does not fix the poroblem

**To Reproduce**

as soon as I insert the mod Ancient Warfare 2 crashes the server, I take it out he runs properly

**Expected behavior**

I expect AE2 to run with the Ancient Warfare 2 mod

**Additional context**

https://pastebin.com/DJtesYrs

https://pastebin.com/DJtesYrs

https://pastebin.com/DJtesYrs

**Environment**

MP and Mod Pack Time

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-4.jar
- Forge Version: forge-1.12.2-14.23.5.2784-universal.jar

**Comment by Pingger** [comment]
wouldn't that make ancient warfare 2 the co conflicting mod?
and how did you manage to make a class from core minecraft disappear while still sending references around during the runtime?

**Comment by Mantafisch** [comment]
I do not quite understand? :/

**Comment by yueh** [comment]
Not our problem when something registers incompatible tile entities.
