### ISSUE TITLE
Charger does not accept oredict certus quartz

### ISSUE THREAD

**Issue by roboderpy** [AppliedEnergistics/Applied-Energistics-2#3878]
**Describe the bug**

Title

**To Reproduce**

* Install gregtech-ce, ae2 and crafttweaker
* Put a crafttweaker script in scripts/ directory with following contents
```
#modloaded gregtech appliedenergistics2

<ore:crystalCertusQuartz>.addAll(<ore:gemCertusQuartz>);
<ore:crystalNetherQuartz>.addAll(<ore:gemNetherQuartz>);
```
* Create a creative world
* Place the charger and try to put certus quartz from gregtechce into charger
* You can not do so.

*Also, you guys really need to make another way of making charged certus quartz without charger, like 8 redstone + certus quartz to get first charged certus quartz since gregtech-ce adds all known ores (and doesn't contain charged certus quartz ore in worldgen), and every other mod needs to have it's worldgen disabled to prevent ore overlap*

**Expected behavior**

You can put certus quartz into charger

**Additional context**

![screnshot](https://i.dbotthepony.ru/2018/12/javaw_2018-12-25_08-07-29.png)

**Environment**

- Server?: yes
- Minecraft Version: 1.12.2
- AE2 Version: Revision 6 Stable 4
- Forge Version: Build 2796

**Comment by yueh** [comment]
It is nowhere stated, that adding random oredict entries make it work magically. There is an API endpoint available in case mods want to register new items for it.

**Comment by roboderpy** [comment]
But isn't charging quartz is supposed to be oredicted?

**Comment by roboderpy** [comment]
Nope, it is hardcoded :clap: https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv6-1.12/src/main/java/appeng/tile/misc/TileCharger.java#L301

**Comment by leagris** [comment]
@roboderpy  make a clean [contribution guidelines conformant](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv6-1.12/.github/CONTRIBUTING.md) PR to add OreDictionary support to the Charger.
See: https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv6-1.12/.github/CONTRIBUTING.md

**Comment by roboderpy** [comment]
I can't, http://www.isitblockedinrussia.com/?host=mobiusstrip.eu

**Comment by roboderpy** [comment]
I can't resolve dependencies, so i can't setupDecompWorkspace/compile the mod - http://www.isitblockedinrussia.com/?host=mobiusstrip.eu

**Comment by yueh** [comment]
If you'd followed the code a bit further, you'd encountered `IAEItemPowerStorage`. That as well as the charger registry should be enough for mods to implement their own chargable items. Might not be as straightforward as it could be, but it is there.

Charging certus is more or less just an edge case for the charger and there wasn't a single request in the last 4 years or so to allow it to convert basic itemstacks. Doing it now is simply a waste of time and effort. It will need an API break as well as having to throw it away when porting to 1.13/1.14.

Also as fyi, the whole CT is pretty much temporary as vanilla/forge itself is not sufficient for our needs.
Once vanilla/forge is enough, it will be removed (so pretty much guaranteed in 1.13)
