### ISSUE TITLE
Dimensional ID Conflict when Lord Craft Mod is Installed

### ISSUE THREAD

**Issue by iKhatEX** [AppliedEnergistics/Applied-Energistics-2#3884]
**Describe the bug**
There is a dimensional conflict with ID 8, whenever I have the mod Lord Craft installed in my modpack.
I'm not sure what other mod that comes with a dimension could be conflicting with Lord Craft's dimension ID. AE2 is what I assume is the culprit with its spatial dimension since theoretically can be any viable ID. It could be another mod but I'm not for certain. In the crash log it says that AE2 caught a conflict on this ID stated at the start, when launching the pack. 
------------------------------------------------
[Note]: I hope this can be resolved because both of these mods are crucial towards progression in my pack.

**To Reproduce**
Have both Applied Energistics 2 and Lord Craft both installed together in a pack together.

**Expected behavior**
When I have Lord Craft there shouldn't be a dimension ID conflicts to in order for the pack to launch correctly.

**Additional context**
https://pastebin.com/MS3PxjMz

**Environment**
- Minecraft Version: 1.12.2
- AE2 Version: Current (Rv6-Stable 5)
- Forge Version: forge-14.23.5.2786

**Comment by yueh** [comment]
And thats why there is an option in the config file.
