### ISSUE TITLE
Amount of continous power drain

### ISSUE THREAD

**Issue by TheBlackLuigi** [AppliedEnergistics/Applied-Energistics-2#3888]
It seems that there is no config option to change the amount of energy drained passively by several blocks and items. I wanted to adjust the amout used by the 64k storage to be 64 times the amout of the 1k and so on.
- Minecraft Version: 1.12.2
- AE2 Version: rv-6-stable-6
- Forge Version: 1.12.2-14.23.5.2768

**Comment by yueh** [comment]
Your observation appears to be correct. And no it will not change as it is already somewhat hidden and most likely not obvious to most players.
