### ISSUE TITLE
Client crashes with "ItemStack#isEmpty() has to be false" exception

### ISSUE THREAD

**Issue by newsec** [AppliedEnergistics/Applied-Energistics-2#3889]
If I order the item craft without ME drive installed (used storage bus with chest) then client crashes with an exception.
Tested with only AE2 mod installed in a new world in Single Player mode.

MC: 1.12.2
AE2: appliedenergistics2-rv6-stable-5
Forge: 14.23.5.2780

https://pastebin.com/YNwRh8vp

**Comment by newsec** [comment]
@yueh Could you give some comments? Why did you close the issue?

**Comment by Mordenkainen** [comment]
Perhaps because it was a dup issue and already fixed? See #3880

**Comment by newsec** [comment]
@Mordenkainen got it, thank you so much.

**Comment by Mordenkainen** [comment]
@newsec and please try not to take offense. When dealing with a really large project like this it is sometimes difficult to put a comment on every dup you close out.

**Comment by newsec** [comment]
@Mordenkainen I'm not taking offense. I just tried to understand why the issue was closed. Because I searched same issues with no luck (used wrong words like "ItemStack" etc). Thanks again.
