### ISSUE TITLE
Hotkey for showing craftable items

### ISSUE THREAD

**Issue by p455w0rd** [AppliedEnergistics/Applied-Energistics-2#3890]
**Describe the feature**
So you can middle-click a stack to bring up the craft amount GUI. This only works if you know that the stack is craftable. I propose to add the option hold `Alt` to change the stack size rendering to show the 'Craft' render so we know what items are craftable.

**Reasons why it should be considered**
Just a feature I have always thought should be implemented

**Additional Context**
Essentialy this would be the default:
![](https://puu.sh/CoBK9/152d571636.png)

While holding `Alt` this would display:
![](https://puu.sh/CoBLO/64bfe5cd8a.png)

**Also**
When clicking while holding `Alt`, this would do the same as middle-clicking (bring up the craft amount GUI)

**Comment by yueh** [comment]
Might be an idea. just more abstract. As in toggle between the primary and secondary option. In case of only displaying craftable items, it could switch to displaying the stored amount.

But it has similar issues to middle clicking itself. If you don't know it exists, nobody will use it.
There might be better options like indicating them better. Different background, add some icon in another corner or simply something like appending a `+` to the count when craftable.

The last option is probably the easiest one, put could result in the count being too long.
Everything else won't be done until we could finally rework the whole GUI/container part to make these things easier.
