### ISSUE TITLE
Autocrafting with non-stacking items for mekanism not craftable with autocrafting

### ISSUE THREAD

**Issue by ApostolosRisen** [AppliedEnergistics/Applied-Energistics-2#3897]
Autocrafting solar panels, and advanced solar panels fails to finish construction

**issue**
When setting up autocrafting for mekanism solar panels, and subsequent types of solar equipment, advanced solar panels for reference, or an altered recipe for the solar neutron activator, altered to require a solar generator, The autocrafting reaches the final assembly stage and then stops without completing the crafting job, or ending the crafting process. All required recipes are in an interface connected to an assembler, Solar panel(crafts with no problem)< Solar Generator (fails to craft despite all resources needed being also included in the autocrafting recipes)< Advanced Solar Generator(fails to craft do to crafting failure of Solar Generators). this could possibly affect the production of induction matrix parts as well, I haven't progressed far enough to run into this problem

**To Reproduce**
place crafting recipes for all needed resources and components into autocrafting system, start a call order for either the Advanced Solar Generator, or the Solar Generator, ensuring that all the needed supplies to craft them from nothing are in the system.

**Expected behavior**
the system should produce either, 1 A Solar Generator/s, or 2 several Solar Generators then an Advanced Solar Generator and place it in the ME System.

**Environment**
both Single player world, and public server produced the same results for me, info and modpack are both available through technic launcher, and at this address https://www.technicpack.net/modpack/nw-the-end-of-days.1321792/about

large list of mods added in png format for viewing 
![modlist pt 1](https://user-images.githubusercontent.com/26664327/50719317-6e056000-1068-11e9-8c41-d84f3ba15705.PNG)
![modlist pt 2](https://user-images.githubusercontent.com/26664327/50719320-6fcf2380-1068-11e9-8bc4-00b843b44a23.PNG)
![modlist pt 3](https://user-images.githubusercontent.com/26664327/50719321-7362aa80-1068-11e9-8b51-29444bffedc0.PNG)
![modlist pt 4](https://user-images.githubusercontent.com/26664327/50719324-79588b80-1068-11e9-96a6-4b95a6718033.PNG)
![modlist pt 5](https://user-images.githubusercontent.com/26664327/50719335-93926980-1068-11e9-885d-16c2d92136c8.PNG)

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-3
- Forge Version:14.23.5.2768

**Comment by ApostolosRisen** [comment]
you can trust me when I say its not an incorrect pattern, but if you want I can try to upload a video of them, and I know the the other mod refined storage had the same problem, and was fixed by removing mekData from all of the machines, and that could be the case here as well, I will load up the pack and add pictures of the recipes shortly, here is the link to the fix and issue from refined storage https://github.com/raoulvdberge/refinedstorage/issues/834 its exactly the same problem as I have occurring with applied energistics

**Comment by yueh** [comment]
Sorry, but we won't start adding custom solutions for broken mods. E.g. one day they might suddenly use the same tag to actually be important and store the tier. Leading to all sorts of issues showing up.

The best options is to either suggest mekanism starts cleanup up their items (unlikely) or convince forge for a generic solution to allow mods to register custom comparators for itemstacks and everyone could benefit from it.
