### ISSUE TITLE
Weird behaviour from fluid annihilation planes

### ISSUE THREAD

**Issue by FelixLouis** [AppliedEnergistics/Applied-Energistics-2#3899]
Case of an annihilation plane not working when supposed to store in a fluid interface

**Describe the bug**

A subnetwork containing only a fluid annihilation plane (facing an infinite water source) and a fluid storage bus (facing a tank or a fluid interface) won't consider the tank/interface as valid to recieve water from the annihilation plane (and thus the plane won't work)

**To Reproduce**

Copy the setup in the screenshot. 

**Expected behavior**

**Additional context**

screenshot of the setup: https://imgur.com/a/U8evouG
a reddit post where I describe it: https://www.reddit.com/r/feedthebeast/comments/adjyxm/applied_energistics_how_do_annihilation_planes/

**Environment**

Gregblock Modpack
- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-4
- Forge Version: 14-23-5-2768

**Comment by Ommina** [comment]
#3767 -- I think?

If so, this is fixed in stable-5.  If possible, try upgrading your version of AE2 and see if the issue persists.

**Comment by yueh** [comment]
@Ommina Nope, unrelated. Or at least a follow up bug.

Basically the flag for a configured fluid interface is not set, thus it will expose the whole network inventory and thus allow it to be completely filled.
So it just needs to behave like the item interface, once a slot/tank is set to keep a certain item/fluid, it will expose the the local inventory and no longer the network one.
