### ISSUE TITLE
Consider the inventory exposed by interfaces to be a toggle option

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#3900]
It might be an idea to have an explicit button to toggle between exposing the network inventory or local inventory of a an interface to any attached storage bus instead of automatically setting it based on having configured slots or not.

It should still automatically toggle once it is configured to hold an itemstack/fluid to maintain the current behaviour.

One reason to avoid it would be that it can confuse players on how it interacts with something else than storage buses. E.g. they could expect it to expose the network inventory to an attached pipe.

Or maybe just expose the setting as a non interactable button with a tooltip explaining the current mode. But that might have to wait for a UI refactoring.

**Comment by mindforger** [comment]
does AE provide an API to access the network storage?
this would open an oppertunity to allow other storage mods to use the interface properly as both either supply/chest mode or interface mode, so mods do not need to add a custom "interface" block

**Comment by bookerthegeek** [comment]
A button would be nice. So if I am reading this right....

- Local Mode would only let a Hopper pull what is inside the interface
- Network Mode would have a hopper slowly pull the entire AE network out.

(I realize not a Hopper but you get the point) Sound about right?

**Comment by yueh** [comment]
That should be enough proof to consider it bad idea as it will confuse most players.

**Comment by bookerthegeek** [comment]
Lol. I actually would like this option as a card for when logistic pipes comes out for 1.12 as it will make a lot of things easier.

**Comment by Mordenkainen** [comment]
Logistics pipes already had this functionality in the past on the quicksort (and other) modules. It would just require them to reimplement that.

**Comment by bookerthegeek** [comment]
Correct. But this functionality was dependant upon AE exposing the entire inventory in the first place. Which would need to still happen for this feature to remain usable.

**Comment by Mordenkainen** [comment]
Any block that joins the grid has access to the full inventory. It would just require making the "pipe" grid aware, this would entirely be within LPs code.

**Comment by bookerthegeek** [comment]
Gotcha. I sit corrected.
