### ISSUE TITLE
AE2 + CTM + Better With Mods = Charged certus quartz glitch

### ISSUE THREAD

**Issue by Snownee** [AppliedEnergistics/Applied-Energistics-2#3905]
![image](https://user-images.githubusercontent.com/16059084/51100532-823c2080-1811-11e9-82cc-3e4af645576e.png)

Normal certus quartz as a contrast on the left

**Environment**

Forge: 2796
CTM: 0.3.3.22
BWM: 2.3.20.1027
AE2: rv6-stable-6

https://github.com/Chisel-Team/ConnectedTexturesMod/issues/92

**Comment by seancrain** [comment]
I commented on the issue on the other, but I'll add it here as well.

I'm having a similar problem within my modpack Telkit. However, my issue is with active terminals, and I do not have Better with Mods installed.

![Strange rendering](https://i.imgur.com/xhIYul4.png)

I think that Chisel, not just CTM, has something to do with it.

**Comment by SnorrLaxZ** [comment]
Looked into this aswell:

Went through some configs
COFH Client = B:DisableParticles=false
FoamFix = Turned off the Textures Category

Didn't do anything to it... I also have CTM + BetterWithMods

**Comment by mindforger** [comment]
tried to remove chisel to see if it helps? it's mentioned in the linked issue

**Comment by SnorrLaxZ** [comment]
> tried to remove chisel to see if it helps? it's mentioned in the linked issue

Ill try that really soon, I'll update

**Comment by SnorrLaxZ** [comment]
Sorry for extremely late reply, but I removed Chisel and can confirm that it's not related to chisel

**Comment by seancrain** [comment]
The thing I find odd is that when you introduce OptiFine into the environment, the problem disappears.

**Comment by SnorrLaxZ** [comment]
> The thing I find odd is that when you introduce OptiFine into the environment, the problem disappears.

So, if I add Optifine to my list of FPS Mods (BetterFPS & FoamFix) it should get fixed? Would be awesome tbh

**Comment by Carnaxus** [comment]
I seem to remember having the opposite happen, honestly.  I *removed* OptiFine and *replaced* it with BetterFPS and this problem went away.  Weird.

**Comment by Snownee** [comment]
@yueh Any reason for closing this issue? Cannot see a related commit

**Comment by yueh** [comment]
Inactivity, related ticket closed, the usual Optifine or other break rendering mods are not supported and so on.
