### ISSUE TITLE
Suggestion: Advanced Export/Import Bus

### ISSUE THREAD

**Issue by Explosivee** [AppliedEnergistics/Applied-Energistics-2#3906]
We all know AE2 cables can be really annoying sometimes especially when we need to connect our machines with IN/OUT and Energy so what i was thinking at least to get rid of from Energy issue is that you guys might add "Advanced Export/Import Bus" and their only extra feature might be transfer items + energy in same time. I'm sure everyone would love this kind of feature and make our job a lot easier.

**Comment by yueh** [comment]
No, and the reason is already covered by our [suggestion guidelines](https://ae-mod.info/Suggestion-Guidelines/).
