### ISSUE TITLE
Pattern Terminal Freeze

### ISSUE THREAD

**Issue by Yamza** [AppliedEnergistics/Applied-Energistics-2#3907]
**Describe the bug**
When attempting to craft a pattern in the pattern terminal, incomplete patterns that do not produce a valid recipe seem to cause the client to freeze. This effect is exacerbated by attempting to create patterns that require more items. It seems as if AE2 is endlessly searching for a correct recipe but instead just causes the client to freeze indefinitely. 

Eventually after spamming Esc for several minutes i can get out of the terminal, or spamming the Clear button on the terminal it will clear.

**To Reproduce**
Input items into the terminal in such a way that a valid recipe is not found.

**Expected behavior**
Not freezing.

**Additional context**
https://i.imgur.com/5C4nSZs.png
For refrence, there should be a blue crystal in the center of this, but since it was not available in the system it did not fill and thus froze.

**Environment**
Heavily modded pack. This is client side while playing on a server.
https://minecraft.curseforge.com/projects/all-the-mods-3-remix (Version 1.0.2)

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-6
- Forge Version: 14.23.5.2796

**Comment by jtgraphic** [comment]
I'm also experiencing this. I was trying to make quartz glass as a pattern and experienced the freeze. I had suspected it has something to do with the ore dictionary on quartz dust. I was playing on Enigmatica 2 (Normal). https://minecraft.curseforge.com/projects/enigmatica2

**Comment by ThePixelbrain** [comment]
I'm experiencing the same issue, so I did some testing. I created a small ae system with only the required items for the recipe in it. I created a new singeplayer world and I had no performance issues, however as I build the same system in my main world (which was created in rv6-stable-3), I had these extreme lag issues.

**Comment by yueh** [comment]
Please report these issues to the modpack directly. A couple ones decides to break the normal behaviour causing such issues and there is simply no way to track which ones decided to break it.
