### ISSUE TITLE
Large amount of lag when calculating autocrafting requirements

### ISSUE THREAD

**Issue by JathTyki** [AppliedEnergistics/Applied-Energistics-2#3908]
#### Description
Currently using stable v6, so latest mod.
At this current time, I am experiencing an issue with the calculation part of the autocrafting. As far as I can tell, all other functions of the autocrafting seem to work fine E.G. exporting the items, importing them back in and storing them, etc. But the calculation part is rough.

Even if the autocraft is for one crafting table, the moment you click on "next" it will hang for about 15 seconds, and I noticed on the server the CPU utilization is through the roof. If the crafting job is big it'll obviously hang for longer, but not by much.

I don't remember having this issue on a lower version of the mod but I am unable to revert back without some hard work with it. If there's an easy way to tell what exactly is causing so much lag, I can figure it out.

[09:54:21] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 11026ms behind, skipping 220 tick(s)
[09:54:41] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 5469ms behind, skipping 109 tick(s)
[09:59:38] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 11047ms behind, skipping 220 tick(s)

#### Environment
This is a MP server where I'm really the only one playing. It's a server in case friends want to play, but they don't really. Also a server to have processes left run when my computer is asleep.

Mod List: https://pastebin.com/tkrJZz8n
Picture of network base: https://i.imgur.com/VsAsDZo.png

- Minecraft Version: 1.12.2
- AE2 Version: v6 stable 6
- Forge Version: 2796

**Comment by yueh** [comment]
We actually need a sampling/profiling report. E.g. a .nps dump. Otherwise there is nothing we can do about it

**Comment by JathTyki** [comment]
How can I do the profiling/sampling? It is still happening so I can get that for you.

**Comment by yueh** [comment]
E.g. https://ae-mod.info/profiling/ or there is also the mod [sampler](https://minecraft.curseforge.com/projects/sampler)

**Comment by JathTyki** [comment]
I apologize for being a noob on this side of things. I installed the JDK and was able to get the server launched via the JDK java instead of the JRE. Unfortunately even after having the server launched with VisualVM open, it won't actually see the instance of the server. Any ideas on how to get it to show in VisualVM?

https://i.imgur.com/a0vb6Ve.png

Aside from that, I attempted the sampler mod and it crashed the server upon startup. I had to remove the sampler mod from the server and the server launched fine. Not sure what's up with that.

**Comment by Mordenkainen** [comment]
You need the profiler on the same machine the server is running on. If you can't do that there are ways to profile remotely but they are a bit more complicated.

**Comment by JathTyki** [comment]
Yup, I do understand that. I installed JDK onto the server and ran the minecraft server with Jdk, which is linux mint and ran VisualVM, but it wasnt showing the server as a running task. I am going to try running visualvm as sudo similar to the server, but otherwise I'm missing something.

**Comment by JathTyki** [comment]
Okay, I figured it out and was able to capture three different types of situations.

1) Attempting to request autocrafting of 64 chests. Video here: https://vimeo.com/user93230105/review/312425721/17cdb0d1ed

2) Attempting to request autocrafting of 64 4k drives. Video here: https://vimeo.com/user93230105/review/312425760/e0fc58e053

3) Putting a crafting card in an export bus to autocraft fertilizer. Video here: https://vimeo.com/user93230105/review/312425689/ac7c833e36

I have attached the JVisualVM captures for all 3 scenarios also. If you need any more data, please let me know. I'd be able to collect anything you may need.

[JVisualVM.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/2777139/JVisualVM.zip)

**Comment by mindforger** [comment]
either something is broken with my internet again and making funny things with my requests or the videos are not available to view

**Comment by Mordenkainen** [comment]
I cant get to them either.

**Comment by yueh** [comment]
Ok, that is basically a Forge Bug/Feature, depending on how you want to see it.

There is nothing we can do about the immense performance problems itemstack capabilities create. At least not until Forge decides to fix it.

**Comment by JathTyki** [comment]
Okay, understood. I just don't know why it decided to start happening very recently. I didn't have this issue a while back, and then it just started happening. Really odd, but understood if you can't do anything.

Thanks for taking a look.
