### ISSUE TITLE
Pattern Terminal causing disconnect due to Payload when trying to set Quartz Glass. 

### ISSUE THREAD

**Issue by Gunner76th** [AppliedEnergistics/Applied-Energistics-2#3909]
**Describe the bug**

When using the Move Items button to set a pattern on the Pattern Terminal to quartz glass, I get a DC with the message " Payload may not be larger than 32767 bytes." Using the Crafting Terminal to execute the same task does not result in this error. As I have just gotten to the point in the game of setting up automatic crafting I cannot say if other recipes can/do cause this issue as of yet. 

While I do not see mention of AE specifically in the console log at the time of the DC, this is being reported here first since the DC has been confirmed to only happen when the Pattern Terminal is used. When repeating the steps on a crafting table, crafting station from Tinker's, and even the Craft Terminal from AE this DC event does not happen. 

**To Reproduce**

Look up the recipe for Quartz Glass
Use the "Move Items" button that is added by JEI to move the items in the recipe to the Pattern Terminal crafting area. 

**Expected behavior**

Recipe to be set in the crafting area of the Pattern Terminal without a DC or error message. 

**Additional context**

![image](https://user-images.githubusercontent.com/5566872/51433078-e3e4fc00-1c10-11e9-901d-1c574ee1431c.png)

Gist Link: https://gist.github.com/Gunner76th/a18de7d0f1a476404d1840238f17ed14

Direct File Upload: [latest.log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/2776056/latest.log)

![image](https://user-images.githubusercontent.com/5566872/51433076-d760a380-1c10-11e9-9274-60ffe5457f5e.png)

For the console log, the time index of the last DC that I was able to induce while testing to confirm was at 17:28:46
**Environment**

The environment being used is a Server Multiplayer Survival setup. The modpack in use is FTB Presents StoneBlock 2, version 1.2.0 Beta. 

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-6
- Forge Version: 14.23.5.2796

**Comment by yueh** [comment]
Sorry, but SB2 uses an unsupported version of AE2. Thus you habe to report all issues to them.

**Comment by Gunner76th** [comment]
If this is an unsupported version can you please advise as to what is a supported version? The version in use is the current version that is posted on Curse Forge as owned by AlgorithX. Is he not the official and authorized owner and authorized of Applied Energistics?

**Comment by Gunner76th** [comment]
Also be advised that the curse Forge page for Applied Energistics links back to this GitHub for issue reporting. Based on that information, how can the version in use not be a supported version when it is also the most recent Release version that is posted?

**Comment by Gunner76th** [comment]
@yueh ?

**Comment by mindforger** [comment]
don't quote me on that, but i think what he means is somebody used the code with all the links in it, modified it and compiled it themself and dropped it in that particular modpack, thus you got mislead to believe it is an original AE2 VVersion ... that is what i understand of what yueh wrote and what is the most probable situation that i can think of

**Comment by Gunner76th** [comment]
Does the license for Applied Energistics allow for individuals to do this? If not then wouldn't the individuals who working on Stone Block be in violation of the license and thus be subject to a cease and desist order?

**Comment by Gunner76th** [comment]
After thinking about your reply @mindforger I looked at the pack as hosted on Twitch launcher/CurseForge page, and no it is not a custom compiled version. 

![image](https://user-images.githubusercontent.com/5566872/51445183-4b15b580-1cd0-11e9-8c94-eb35c52b9c0e.png)


If you notice it is listed as the official release version, pulling directly from AlgorithX's official page on CurseForge. So no, this isnt some custom compiled version of the mod that is being used. This is the official release version, and most up to date version of the mod in use as released by AlgorithX through both Twitch/CurseForge and the official Applied Energistics website. 

So once again I ask you @yueh directly, you claim that the version of Applied Energistics that is in use is not a supported version, yet it is the most up to date version that is publicly released, it is from the stable channel, and it is a release build, How is it that that version is not a supported version even though it is not modified, is the official release version, and there are no other more recent versions released?

**Comment by codewarrior0** [comment]
I set a breakpoint on the large packet and it seems to be sent on the channel named "jee", which I'm certain is from JustEnoughEnergistics. @Gunner76th Can you confirm that JEE is in the modpack where you encountered this issue?

**Comment by codewarrior0** [comment]
JEE is at fault here. https://github.com/p455w0rd/JustEnoughEnergistics/issues/4
