### ISSUE TITLE
Persistent types (storage)

### ISSUE THREAD

**Issue by KirillBorunov** [AppliedEnergistics/Applied-Energistics-2#3916]
**Describe the feature**

Should be a way to enable "persistent types".
If an item type was existed ever on the storage it gets persisted until the player "removes" it manually.
It means that if the count for that item downs to zero it not disappears but shows "you have 0 of that item".

**Reasons why it should be considered**

There are 2 reasons:
1) you can see what are you out of.
2) it will prevent this on complex extraction-process-insert systems: https://youtu.be/MWRR_2VLJaE

**Additional Context**

**Comment by yueh** [comment]
That is simply not possible for various reasons like needing a major rewrite to how items are handled internally, it would be a potentially performance issues as itemstacks are no longer removed and start to accumulate into the range of many thousand or even million ones, etc.
