### ISSUE TITLE
Identity Annihilation Plane not silk-touching

### ISSUE THREAD

**Issue by RGBoorman** [AppliedEnergistics/Applied-Energistics-2#3919]
### Description
Simple enough, I've found that the identity annihilation plane is acting as a normal annihilation plane  - whenever a coal ore block is placed in front of it, the system receives one coal. This also applies to all other ores, one ore always producing one 'ingot' rather than the block itself.
https://ibb.co/VBLTWLr for a setup screenshot. This has been moved and rebuilt a couple times.

#### Environment
Running on a standalone Windows server. Low user count.
Complete mod list https://pastebin.com/hrNRt1Vq

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-6
- Forge Version: 1.12.2-14.23.5.2796-universal

**Comment by Dastari** [comment]
I can confirm this. Having the same issue on a Multiplayer Server.

**Minecraft:** 1.12.2
**Forge:** 1.12.2-14.23.5.2811
**AE2:** rv6-stable-6

**Comment by zISKo666** [comment]
Hello,

is there any update to this issue?

Kind regards
zISKo666

**Comment by MirrgieRiana** [comment]
Hello,

I found the problem here.
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv6-1.12/src/main/java/appeng/parts/automation/PartAnnihilationPlane.java#L419

`obtainBlockDrops` successfully returns the result of applying silk touch.
However, `breakBlockAndStoreItems`, which actually breaks blocks, performs normal block break process.

**Comment by Dimentive** [comment]
I’m having the same issue. I hope this gets fixed soon, as currently, the ME identity annihilation plane behaves identically to the regular ME annihilation plane, which is, of course, not how the block is supposed to behave.

#### Versions

* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2781
* **Modpack:** [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2) (version [1.63a](https://minecraft.curseforge.com/projects/enigmatica2/files/2691579), latest)
* **Applied Energistics 2:** [rv6-stable-6](https://minecraft.curseforge.com/projects/applied-energistics-2/files/2652453) (latest)

**Comment by yueh** [comment]
I currently do not see a way to fix it. Reintroducing it will also enable vanilla dupe bugs again.

**Comment by Dimentive** [comment]
It works for [Refined Storage](https://minecraft.curseforge.com/projects/refined-storage) ([destructor](https://refinedstorage.raoulvdberge.com/wiki/destructor) with Silk Touch upgrade), but there might be a dupe bug associated with that; I’m not sure. I’ve not used RS in a while, so I can’t say.

If you’re not going to fix this, though, I’d suggest removing the identity annihilation plane from the mod—or at least remove its recipe or add a tooltip stating that it doesn’t work.

**Comment by Dimentive** [comment]
It works for [Refined Storage](https://minecraft.curseforge.com/projects/refined-storage) ([destructor](https://refinedstorage.raoulvdberge.com/wiki/destructor) with Silk Touch upgrade), but there might be a dupe bug associated with that; I’m not sure. I’ve not used RS in a while, so I can’t say.

If you’re not going to fix this, though, I’d suggest removing the identity annihilation plane from the mod—or at least remove its recipe or add a tooltip stating that it doesn’t work, but that’s up to you.

**Comment by zISKo666** [comment]
Suggestion!

Reintroduce it (with vanilla dupe bugs expected) and make the config option like:

```
    networkbuses {
        ...
        # default for IdentityAnnihilationPlane=false, if set to true then you might expect some vanilla dupe bugs #
        B:IdentityAnnihilationPlane=false
        ...
    }
```

**Comment by Dimentive** [comment]
@zISKo666 That would be great!
