### ISSUE TITLE
Annihilation Plane Refuses to Break Blocks

### ISSUE THREAD

**Issue by z64555** [AppliedEnergistics/Applied-Energistics-2#3920]
#### Description
The annihilation plane won't break blocks in various setups to try to automate Botania's pure daisy.  A recent attempt had the plane able to digitize items toss at it, but any block (including cobble) placed in front of it would not break.

 This setup was on a subnet powered by the main network via a quartz fibre, and the only two devices on the subnet was the plane and a storage bus (placed on an empty chest), both were connected and powered correctly.

I've had success with the plane before placing a security terminal, and I suspect that something with the permissions is interfering with the plane from functioning correctly.  A default biometrics card with all permissions enabled doesn't resolve the issue.

Whats wierd is that the behavior is inconsistant if the plane is placed on the main network, sometimes it *does* work, but then immediately stops.

#### Environment
- Pack: Enigmatica 2
- Minecraft Version: 1.12.2
- AE2 Version: 
- Forge Version:

#### Other Comments
I'm posting this from mobile on behalf of a friend.  I've had the exact same issue before in a test pack with just AE2/in it.  I dont have an active PC right now to help with the debugging issue, but should be getting it fixed soon.

**Comment by yueh** [comment]
Please report this directly to the modpack as it is using addons which can cause unpredicatable behaviour in AE2.

**Comment by z64555** [comment]
Do i need to add that the same exact behavior works in an AE2 test instance by itself?

**Comment by z64555** [comment]
My machine is back up and running.  I'll remake the test pack with *only* AE2 and its dependencies to double-check my claim.

My earlier test instance added mods and I don't remember if I did the annihilation plane tests before after the mods were added, so we'll see if that is the case soon enough.

**Comment by z64555** [comment]
Ok, latest run with just AE2, nothing else, was unable to repro the issue as described.

I apologize for the inconvenience and thank you for your time.

**Comment by Darkosto** [comment]
This has been confirmed on a server, with only JEI and AE2 installed. The formation and Annihilation planes are not working. They work fine in single player but not a server.

Forge: 2824
MC: 1.12.2
AE2: RV6-Stable-6
