### ISSUE TITLE
[Request] Tell JEI about the extra areas AE GUIs draw

### ISSUE THREAD

**Issue by mezz** [AppliedEnergistics/Applied-Energistics-2#3922]
**Describe the feature**

Currently, some AE guis overlap a bit with JEI because of the extras they have on the left and right sides.
There is no way to detect these automatically in JEI, but AE can use its JEI Plugin to do it.
In `appeng.integration.modules.jei.JEIPlugin#register`
call
`mezz.jei.api.IModRegistry#addAdvancedGuiHandlers`
and implement a `IAdvancedGuiHandler` for  your gui.

`mezz.jei.api.gui.IAdvancedGuiHandler#getGuiExtraAreas` is the method that will tell JEI about extra slots on the sides of your gui so that JEI can move out of the way.

To test fully, use the latest version of JEI and add some bookmarks to the left panel by hovering over items and pressing 'a'.

**Reasons why it should be considered**

It creates a more pleasing experience for players.

**Additional Context**

Here is the original issue reported to JEI: https://github.com/mezz/JustEnoughItems/issues/1484
![51965932-de14c500-241f-11e9-9cd6-d085d3ef7ef2](https://user-images.githubusercontent.com/916092/52161536-1e23b400-267b-11e9-80fe-c011de1502a6.png)

**Comment by yueh** [comment]
Will be considered once there is time to refactor the whole GUI part to make these things easier.

**Comment by mezz** [comment]
Sounds good. I was going to PR it myself but things got complicated, so I understand why you’d want to refactor first.

**Comment by shartte** [comment]
@mezz Is this still relevant in 1.15? I think JEI now automatically inspects the current screen's size if I am not mistaken, or at least I don't see any obvious overlaps in 1.15 anymore.

**Comment by mezz** [comment]
JEI works the same way, maybe AE is supplying different values in 1.15?
If there are no overlaps then this is solved.

**Comment by shartte** [comment]
I'll double check it again.

**Comment by BrettMoan** [comment]
FYI, Still seeing this in minecraft versions of 1.16.

**Comment by shartte** [comment]
@mezz We're in the process of implementing this, but on tall terminals, we see the following effect:

![image](https://user-images.githubusercontent.com/1261399/115292181-f171ef00-a155-11eb-8220-50217ce1483c.png)

Is the only way to fix this to move our toolbars down?

This is with JEI 7.6.1.71

**Comment by mezz** [comment]
You're doing the right thing here, I think JEI is just acting poorly in this case. Once this is in, please open an issue with JEI and we can work out the rest of this on my side :)

**Comment by shartte** [comment]
This is now implemented in the 8.4 alpha
