### ISSUE TITLE
Fluid Level Emitter not Emitting when it should

### ISSUE THREAD

**Issue by W0lfgangster** [AppliedEnergistics/Applied-Energistics-2#3923]
The fluid level emitter is set to "Emit when levels are below limit" but is not emitting when the level is zero, which is far below the limit of 300,000.

**Describe the bug**

I have a TC smeltery set up with a fluid storage bus set with tin plugged in to it. The level emitter is hooked up to a redstone clock so when the tin reserve is above the set level the emitter will let the clock go and activate the drains and when it's below the level the emitter will emit a signal and stop the clock so it won't drain anymore. The issue comes when I leave he area and something (presumably the storage bus) unload so the molten tin won't show up in the ME system anymore, and the emitter stops emitting a signal and the clock starts draining the smeltery.

**To Reproduce**
Hook up a fluid storage bus to a smeltery, set a fluid level emitter to 'emit when levels are below the limit,' hook it up to a clock hooked up to the smeltery drains, then leave the area and come back to find an empty smeltery.

**Expected behavior**
The level emitter should still emit a signal when the molten tin is not loaded by the ME system because the level is zero.

**Environment**
Multiplayer Server with a AE2 stuff and Extra Cells, and to be clear it is the AE2 storage bus not the Extra Cells one.

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-6
- Forge Version: 14.23.5.2796

**Comment by yueh** [comment]
Is the area fully chunk loaded? For performance reasons they rely on being notified about changes, which can be missed in case the level emitter or cable to them is unloaded.

**Comment by W0lfgangster** [comment]
Well now none of the chunks are loaded due to the whole area being corrupted and crashes the server whenever anyone gets near them.

**Comment by yueh** [comment]
Sorry, but if the area itself cannot be loaded, there is no way it can work correctly.
