### ISSUE TITLE
Autocrafting Interface not responding

### ISSUE THREAD

**Issue by kugamer** [AppliedEnergistics/Applied-Energistics-2#3924]
**Describe the bug**
When trying to autocraft anything with multiple steps the system does not respond. I can select the craft, select how many of something I want to craft and when I select start nothing happens. I have tried breaking a line in the system, I have 6 of 8 channels, I have plenty of crafting cpu capability. I am playing the most recent version of Enigmatica 2 with the most recent version of Java. 

**To Reproduce**

**Expected behavior**

**Additional context**
![2019-02-04_11 13 16](https://user-images.githubusercontent.com/37590553/52225343-c5693c80-286f-11e9-8519-e8e3ba180f19.png)

![2019-02-04_11 30 31](https://user-images.githubusercontent.com/37590553/52225567-4aecec80-2870-11e9-8bea-afc491bf4168.png)

![2019-02-04_11 31 32](https://user-images.githubusercontent.com/37590553/52225626-7243b980-2870-11e9-8fac-6a6b250b1f70.png)

![2019-02-04_11 32 30](https://user-images.githubusercontent.com/37590553/52225681-9901f000-2870-11e9-8828-00918b28ee3e.png)

![2019-02-04_11 32 35](https://user-images.githubusercontent.com/37590553/52225685-9dc6a400-2870-11e9-82a7-c0f848f9b3b0.png)

**Environment**
Using Enigmatica 2. Hooked up to the system is -Storage drawers, ender chest, AE2 Stuff (inscribers x5)

- Minecraft Version: 1.12

- AE2 Version: appliedenergistics2-rv6-stable-6
- Forge Version:

**Comment by yueh** [comment]
Please report it to the modpack as they decided to break autocrafting.

**Comment by kugamer** [comment]
well, cool. They say to talk to you guys, you say to talk to them. Fun times.

**Comment by Tahakk** [comment]
If 'they' told you to come here, you can link the issues together so it get's resolved.
