### ISSUE TITLE
Items only Appear when input

### ISSUE THREAD

**Issue by DevynMaaske** [AppliedEnergistics/Applied-Energistics-2#3926]
**Summary**
When I open any of my terminals my items are not  visible to extract until at least one is input. Say I have 5 million cobble then my storage bus automatically inputs 1, then I can view it on the system.

**To Reproduce**
I have many items auto-inputing into my system with storage buses and such and whenever I open them they aren't there until input

**Expected behavior**
When I open my terminal my items will all be availible to take out.

**Additional context**
https://youtu.be/TvkIve1R7UY - a video i took as proof of the ME not showing items until they were input. Then it shows again everytime I close and reopen the ME. At the end I show the main input system to my ME through an interface.

**Environment**
I am on the latest version of "Project Ozone: 3" version 3.0.37
I am not having power issues or channel issues, I have mined my controllers and replaced as well as the drives. I have changes priorities to see if that was the issue, no change.

- Minecraft Version: 1.12.2
- AE2 Version:  rv6.stable build 6
- Forge Version: 14.23.5.2808

**Comment by mindforger** [comment]
i can't see a single energy cell in your relatively large setup, maybe you are experiencing a bootloop due to running out of power 
(especially since in the video it looks like the rate of error is linked to your flower harvester)

power input to the system is limited by "system capacity" / tick

**Comment by DevynMaaske** [comment]
i don’t have energy cells i have a teir 5 quiber cell that has 65 million rf stored and a reactor with 18k rf/t. if you any ideas that would be great. thanks anyway

**Comment by mindforger** [comment]
>power input to the system is limited by "system capacity" / tick


Would you mind to test it with a few dense energy cells first? You can supply a gazzillion rf / tick but your INPUT is limited

**Comment by Pingger** [comment]
As someone who also didn't think this would be the issue: Missing Energy Cells in your ME System are the root of pretty much all evil! 
If something does not behave as you would expect it put some energy cells down and check if it still behaves weird.

**Comment by mindforger** [comment]
;)

**Comment by DevynMaaske** [comment]
I just tested putting dense energy cells o. my controllers and on the energy accepter leading to my system. i’ll do a bit more testing later but no luck

**Comment by mindforger** [comment]
whoops sorry, i did mistake Pingger for you as OP :(

**Comment by pizza963** [comment]
Has any solution been found to thi?

**Comment by mindforger** [comment]
@pizza963 did you test to add some energy cells (the one from AE2 itself) to the system already? @DevynMaaske did not respond yet if it helped, but it looks just like it's bound to an power issue.

**Comment by DevynMaaske** [comment]
i have tested with energy cells and different inputs and i’m not seeing any change

**Comment by DevynMaaske** [comment]
i am using a few p2p tunnels with some different energy inputs throughout my system. the problem is that i don’t know how to recreate the bug.

**Comment by pizza963** [comment]
@mindforger I have messed around with basically any energy configuration and any channel mess and none of it has worked, I’ve restarted server numerous times

**Comment by bookerthegeek** [comment]
@DevynMaaske could upload the save? I'd like to take a look. Would Also need your base cords.

**Comment by mindforger** [comment]
@pizza963 i have heared so many people say "i got infinte power blah" that recovered from their issue by just adding some energy cells in the past, it's just that many people don't understand that the input has a limit, thats why i was asking explicitely about the nergy cells

do you have a dedicated test setup that @bookerthegeek can have to try and replicated the issue?

**Comment by pizza963** [comment]
@bookerthegeek if I send you the save file would you mess test it out a little

**Comment by DevynMaaske** [comment]
i’ll upload the save file this afternoon

**Comment by pizza963** [comment]
I’ve been messing around with my ME system and now it’s back up and running when I took out one of my drives, it seems that something on the drive was breaking the system, I tried to see what was on the drive in an ME chest but I still couldn’t view the items, but it’s a lead

**Comment by DevynMaaske** [comment]
i have broken and replaced/ taken out and put back all my drives, controllers, terminals, and energy acceptors as well as tested around with some energy cells. like i said idk how to recreate so i’ll upload the save file this afternoon.

**Comment by bookerthegeek** [comment]
If you havve a save that is still broken that would be best otherwise do not worry as without an ability to replicate the issue I will not be able to fix it.

**Comment by yueh** [comment]
Please report this directly to the modpack as it is using addons which can cause unpredicatable behaviour in AE2.

**Comment by PizzaAddict** [comment]
I Have similar issues. for me, invisible items are 'encoded patterns' 'mekanism fluid tanks' 'cobblestones named with inscriber name press'. their visibility fluctuates.

and my modpack is enigmatica2 1.66c
also tried attaching 20+ dense energy cell, reconstructing MC controller, replacing ME cells with vanila ones, not extra cells, re-chunkloading, etc..etc...


I can share the save file if you want.(10gb when compressed)

devs, you should consider this bug seriously. If the bug happens for just one modpack, you can blame the modpack author. but when two different modpacks have similar problem, well. you know which one has the problem.

**Comment by PizzaAddict** [comment]
And I know Noone is gonna respond this. cause you are not paid, so have no responsibility, no duty to fix this. you can just ignore, or blame every modpack author and close the issue. what a handy.

**Comment by Pingger** [comment]
**You might want to give us a few minutes to actually get a notification**

To your issue:
Do you have the terminal set to **Show stored only**? (A small button in the top left corner, I think it is 3 layers of brown)
If so, click it until you have to show **Stored and Craftable**

**Comment by PizzaAddict** [comment]
Jesus. I didn't think you could see my post. I just spat some complaint and no one gonna see this cause this post is super old.... I'm very sorry if I disturbed you...

**Comment by PizzaAddict** [comment]
https://github.com/NillerMedDild/Enigmatica2Expert/issues/1333

This is my post about the bug.
