### ISSUE TITLE
Server crash Loading data after part of a grid

### ISSUE THREAD

**Issue by bigenergy** [AppliedEnergistics/Applied-Energistics-2#3929]
**To Reproduce**
...
**Expected behavior**
Server will crash.

**Additional context**
https://pastebin.com/e0CrN7qq
**Environment**

* Minecraft Version: 1.12.2
* AE2 Version: appliedenergistics2-rv6-stable-6
* Forge Version: 14.23.5.2796

**Comment by bigenergy** [comment]
pls help

**Comment by Ommina** [comment]
This has all the appearance, to me, of a corrupted world / chunk, though I'm happy to be corrected if that's not the case.

From a vanilla sapling to a Bukkit server function into AE2 grid code.  Quite a journey, but I do not believe represents a AE issue.

**Comment by bigenergy** [comment]
@Ommina How can I determine the location of crash? 
I think that this is a mistake applied energistics, or mantle lib mod.

**Comment by yueh** [comment]
We do not support anything like Sponge or Bukkit officially. Only a standard forge environment.

Should you be able to reproduce it without it, please update the issue accordingly and we will reopen it.
