### ISSUE TITLE
Make dense smart cables also from normal smart cables

### ISSUE THREAD

**Issue by Domkeykong** [AppliedEnergistics/Applied-Energistics-2#3930]
Make dense smart cables also from normal smart cables!
Currently there is no way to convert normal smart cables to dense smart cables.
Much like you make them now have 4 smart cables become 1 dense smart cables so you can basically upgrade them.

**Comment by yueh** [comment]
Already considered it, but was somewhat reluctant about it as this upgrade path would increase the redstone and glowstone costs by 4 times as much.

This would probably be fine when rarely used, but in case it is used with autocrafting it can easily lead the system to pick `covered cable -> smart cable -> dense smart` as path instead of `coverered -> dense -> smart dense` and put a hefty cost into it.

Might be an idea to streamline it at some point, but for 1.12 it is simply to late.

**Comment by Carnaxus** [comment]
Most autocrafting systems (including AE2's, unless I'm mistaken) either allow or require you, the player, to specify the recipe for each stage of the crafting process.  Buildcraft's Automated Workbench, ProjectRed's Project Bench, Immersive Engineering's multiblock Assembler, RFTools' three tiers of Crafter, Thermal Expansion's Sequential Fabricator (CoFH and their complex names...), and EnderIO's Crafter all require manual recipe setup.  There may be other mods with other autocrafting functionality, but I'd be surprised if any of them just randomly selected a recipe path to get to a final product.

**Comment by Pingger** [comment]
My opinion:
The player has to create a pattern for Cables to Dense Cables. If the players chooses to create the pattern with smart cables instead, that's on them.
For that to work, the dense cable recipies need to be separated and not combined into a single one with oredict.

**Comment by Hevlikn** [comment]
> My opinion:
> The player has to create a pattern for Cables to Dense Cables. If the players chooses to create the pattern with smart cables instead, that's on them.

Agreed here, plus redstone and glowstone are often in abundance. This seems like a method you'd use manually when you need just one or two more pieces of dense, and don't want to trek back to your terminal. I think it's one of those QOL things; similarly you could consider why you can't craft 4 of a coloured cable into the coloured dense version, or even reverse craft a dense into 4.

> For that to work, the dense cable recipies need to be separated and not combined into a single one with oredict.

I don't think this applies, as smart dense can only be created through washing smart dense coloured (which is ore-dict) or applying glow+red to a fluix dense. I'm not sure ore-dict allows replacing completely different shaped recipes!
