### ISSUE TITLE
Expand the ME Controller range by 1.

### ISSUE THREAD

**Issue by TheSnowyChickens** [AppliedEnergistics/Applied-Energistics-2#3933]
Hi,
for me as a symmetry - fan, the 7x7x7 ME controller range hurts me.
In a chunk based design, it's not possible to place the controller in the middle of the room. (16x16 area)

**Describe the feature:**
+1 range from the controller.

**Reasons why it should be considered**
Symmetry - fans would be happy. :D 

**Additional Context**
![grafik](https://user-images.githubusercontent.com/29357962/52901637-62c85700-3206-11e9-8e60-da34841fe702.png)

Used versions:
Forge: 2810
AE2: stable 6, Rv6
MC: 1.12.2

**Comment by Pingger** [comment]
Hi,

AFAIK this is a config setting you can change yourself

**Comment by TheSnowyChickens** [comment]
This is new for me.

**Comment by TheSnowyChickens** [comment]
I'm must be blind but where is the option ?
@Pingger

**Comment by Pingger** [comment]
OK, 
I just double checked and can't find the setting anymore... 
But I remember, that I changed that value before! I am certain I did, because I wanted a full chunk core (as in 16x16x16 cube). 

Sorry ...
+1 for config setting to change maximum controller dimension.

**Comment by yueh** [comment]
Not going to happen.

**Comment by TheSnowyChickens** [comment]
:(
