### ISSUE TITLE
Memory leak rv6-stable-6

### ISSUE THREAD

**Issue by Mr-Krab** [AppliedEnergistics/Applied-Energistics-2#3935]
**Describe the bug**
https://pastebin.com/85i9anEe

**To Reproduce**
I can not say what caused it. I saw in the console. There were 2 players on the server.

**Expected behavior**
Net console.

**Additional context**
Crash no. The necessary piece of the log provided above.

**Environment**
 - Minecraft: 1.12.2
    SpongeAPI: 7.1.0-366290f8
    Sponge: 1.12.2-7.1.5
    SpongeForge: 1.12.2-2768-7.1.5
    Minecraft Forge: 14.23.5.2796

-  Mods (53): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Applied Energistics 2, Better Questing, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, CoFH Core, CoFH World, CodeChicken Lib, Console Filter, Construct's Armory, CraftTweaker JEI Support, CraftTweaker2, CreativeCore, CreativeCoreDummy, CustomNPCs, Ex Nihilo Creatio, Fishing Net Mod, Forestry, HoloInventory, Iron Chest, ItemPhysic, Just Enough Items, LagGoggles, MTLib, Mantle, McJtyLib, Mekanism, Mod Tweaker, Quick Leaf Decay, Redstone Arsenal, Redstone Flux, Shadowfacts' Forgelin, SpongeForge, Standard Expansion, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinkers' Construct, Tiquality, Tree Chopper, UniDict, WanionLib

- Plugins (25): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge,  FastAsyncWorldEdit, BeanCore, CatClearLag, CommandSync, EconomyLite, GriefPrevention, GuiShopManager, Holograms, HuskyCrates, HuskyUI, LuckPerms, Nucleus, ProjectCore, SkyClaims, StackBan, UltimateChat, UniversalMarket, VirtualTool, Wasted, WorldEdit, spark

**Comment by yueh** [comment]
We do not support anything like Sponge or Bukkit officially. Only a standard forge environment.

Should you be able to reproduce it without it, please update the issue accordingly and we will reopen it.

**Comment by MaxNeedsSnacks** [comment]
I can confirm this issue also occurs when Sponge or Bukkit are not present.

Context: I was playing on Enigmatica2Expert v1.56 (Forge 2781, ae rv6-stable-6) and crafting something manually through the crafting table.

Here's a paste that shows what has been logged in console (As far as I could tell, the details of the memory leak weren't actually saved in any sort of persistent log file, at least neither latest nor debug.log):

https://pastebin.com/izYZCAje
