### ISSUE TITLE
Facades are invisible

### ISSUE THREAD

**Issue by BentoGambin** [AppliedEnergistics/Applied-Energistics-2#3937]
Cable facades are invisible, only the cable anchors are rendered. The facade hitbox is still present just like it should be. The block from which the facade is made does not seem to matter, since I used the minecraft:stone in the screenshots bellow.

**To Reproduce**
Just craft the facade normally and place on any ae2 cable.

**Expected behavior**
Normal Facades that should cover my direwiring.

**Additional context**
![2019-02-18_15 08 14](https://user-images.githubusercontent.com/41645690/52970953-65f14d80-3394-11e9-9b11-4fbd6c2d5b4a.png)
(Disabling shaders does nothing, also resetting all mods cfg files does nothing)

**Environment**
<details>
  <summary>Full mod list (click to show)</summary>
  
- preview_OptiFine_1.12.2_HD_U_E4_pre1
- ProjectE-1.12.2-PE1.4.0
- ProjectIntelligence-1.12.2-1.0.2.16-universal
- Quark-r1.5-145
- RedstoneFlux-1.12-2.1.0.6-universal
- Rex's-Additional-Structures-1.12.x+-(v.2.2.0)
- rftools-1.12-7.61
- SmoothBedrock-1.12.2-3.0.0.102
- SmoothFont-mc1.12.2-1.16.1
- StorageDrawers-1.12.2-5.3.8
- supersoundmuffler-1.12.1-1.0.2.9
- TConstruct-1.12.2-2.12.0.115
- theoneprobe-1.12-1.4.27
- tinkersjei-1.0
- TinkerToolLeveling-1.12.2-1.1.0
- Toast+Control-1.12.2-1.7.1
- topaddons-1.12.2-1.10.1
- torcherino-7.5
- twilightforest-1.12.2-3.8.689-universal
- UniDict-1.12.2-2.9.2
- VanillaFix-1.0.10-99
- WanionLib-1.12.2-2.2
- WirelessCraftingTerminal-1.12.2-3.11.86
- WrapUp-1.12-1.1.3
- Xaeros_Minimap_1.15.8_Forge_1.12
- [1.12.2]+VersionChecker-1.4.0
- ActuallyAdditions-1.12.2-r145
- AdvancedSharing-1.12.2-1.1
- AE2WTLib-1.12.2-1.0.5
- appliedenergistics2-rv6-stable-6
- AttributeFix-1.12.2-1.0.4
- AutoRegLib-1.3-24
- Avaritia-1.12.2-3.3.0.28-universal
- Backups-1.12.2-1.4.4
- Baubles-1.12-1.5.2
- bdlib-1.14.3.12-mc1.12.2
- BetterFps-1.4.8
- blockcraftery-1.12.2-1.1.0
- Blur-1.0.4-14
- Bookshelf-1.12.2-2.3.570
- BrandonsCore-1.12.2-2.4.9.195-universal
- Chameleon-1.12-4.1.3
- ChickenChunks-1.12.2-2.4.1.73-universal
- Chisel-MC1.12.2-0.2.1.35
- chiselsandbits-14.30
- Chunk+Pregenerator+V1.12-2.0
- Clumps-3.1.1
- CodeChickenLib-1.12.2-3.2.2.353-universal
- compactmachines3-1.12.2-3.0.13-b236
- Controlling-3.0.6
- CraftTweaker2-1.12-4.1.14
- CreativeCore_v1.9.39_mc1.12.2
- CTM-MC1.12.2-0.3.3.22
- CyclopsCore-1.12.2-1.0.2
- DankNull-1.12-1.4.43
- DarkUtils-1.12.2-1.8.219
- diethopper-1.1
- Draconic-Evolution-1.12.2-2.3.20.333-universal
- DynamicSurroundings-1.12.2-3.5.4.3
- DynamicTrees-1.12.2-0.9.4
- EnchantingPlus-1.12.2-5.0.176
- EnderCompass-1.12-1.2.6.2
- EnderCore-1.12.2-0.5.45
- EnderIO-1.12.2-5.0.40
- EnderIO-endergy-1.12.2-5.0.39
- EnderStorage-1.12.2-2.4.5.136-universal
- ExpandedEquivalence-1.12.2-11b
- extrautils2-1.12-1.9.8
- foamfix-0.10.3-1.12.2
- Forgelin-1.8.2
- GasConduits-1.12.2-1.0.0
- HammerCore-1.12.2-2.0.4.1
- iChunUtil-1.12.2-7.1.4
- IGCM_v1.2.7_mc1.12.2
- industrialcraft-2-2.8.109-ex112
- instantunify-1.12.2-1.1.2
- intwheel-1.12-1.2.7
- InventoryTweaks-1.64+dev.144
- ironchest-1.12.2-7.0.54.838
- ItemPhysic_Full_1.4.17_mc1.12.2
- JAOPCA-1.12.2-2.2.8.100
- jei_1.12.2-4.14.3.245
- JustEnoughResources-1.12.2-0.8.10.50
- KleeSlabs_1.12.2-5.4.11
- LootBags-1.12.2-2.5.7
- malisiscore-1.12.2-6.4.0
- malisisdoors-1.12.2-7.3.0
- Mantle-1.12-1.3.3.42
- mcjtylib-1.12-3.1.1
- MCMultiPart-2.5.3
- Mekanism-1.12.2-9.4.13.349
- MekanismGenerators-1.12.2-9.4.13.349
- MekanismTools-1.12.2-9.4.13.349
- MobDismemberment-1.12.2-7.0.0
- moreoverlays-1.14-mc1.12.2
- MouseTweaks-2.9-mc1.12.2
- mysticallib-1.12.2-1.0.0
- NoMoreRecipeConflict-0.12(1.12.2)
- notenoughwands-1.12-1.7.1
- OreExcavation-1.4.133
- OreLib-1.12.2-3.5.2.2
- p455w0rdslib-1.12.2-2.0.36
- Placebo-1.12.2-1.5.0
- plustic-6.5.4.2
- pressure-1.3.1.9-mc1.12.2

</details>

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-6
- Forge Version: 14.23.5.2795
*Optifine version: Preview_OptiFine_1.12.2_HD_U_E4_pre1

**EDIT: I i'm pretty sure it's a mod incompatibility, but I really would appreciate some help on finding which one. Also I'm sorry for any mispellings, as english is not my main language.

**Comment by covers1624** [comment]
Remove optifine.

**Comment by BentoGambin** [comment]
Well... Then refined storage it is
