### ISSUE TITLE
Forge Microblocks issues

### ISSUE THREAD

**Issue by Shephaard** [AppliedEnergistics/Applied-Energistics-2#3938]
Basically, I wanted to set up a quarry using annihilation planes and frames from Funky Locomotions. Just like in Direwolf's series (here is the specific timecode https://youtu.be/H-WULPYg8Bs?t=215), but it seems to be non-compatible anymore....

**Expected behavior**

Do you have in plans to fix it?

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-6
- Forge Version:14.23.5.2810

**Comment by XFactHD** [comment]
If I recall correctly, they removed this interaction for performance reasons, so it will most likely not come back.
