### ISSUE TITLE
ME Fluid Terminal GUI flawed

### ISSUE THREAD

**Issue by PiDabbelju** [AppliedEnergistics/Applied-Energistics-2#3939]
**Describe the bug**

The ME Fluid Terminal GUI is missing any possibility to insert fluid containers. Fluids stored in the ME system can also not be selected. My Minecraft installation is as "clean" as it can be when starting Stone Block 2 via Twitch Launcher. Faithful Ressource Pack is installed (also via Twitch Launcher), but disabling it does not fix the issue.
Either fixing the bug or telling me, why the GUI looks other than in any YT video or screen shot will be very much appreciated. :)

**To Reproduce**

Issue can be reproduced on any newly installed ME Fluid Terminal (in the same world) and persists even after restarting Minecraft & rebooting the PC

**Expected behavior**

I would expect the ME Fluid Terminal GUI as visible in many tutorials & screenshots.

**Additional context**

This is how the GUI looks like:
![image](https://user-images.githubusercontent.com/47504963/53261800-395f6d80-36d5-11e9-96a0-d7f57752ec31.png)

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-6
- Forge Version: 14.23.5.2808
as part of the FTB Stoneblock 2 Modpack, version 1.7.0 (bug also existed in 1.6.0 & 1.5.0)

**Comment by Ommina** [comment]
Several months ago, fluid support was ported from the Extra Cells addon to be built into AE2 directly.  The fluid terminal was tweaked at the time.

As such, any tutorials or videos more than a handful of months old will feature the previous ExtraCells GUI.

**Comment by PiDabbelju** [comment]
Oh, how embarrassing. I was so confused by the interface that I never tried to just click on the (in this case) lava with an empty bucket... 

Thanks for the hint Ommina and /closed
