### ISSUE TITLE
ME system jumping off and on again.

### ISSUE THREAD

**Issue by Huugboy** [AppliedEnergistics/Applied-Energistics-2#3940]
My ME system randomly jumps off and on again?

I use a pretty big me system, But i manage the channels well, Always making sure they don't overflow.
I've got a friend who lives about 20 chunks away (Or less, I don't really know) So we decided to set up a Quantum network bridge. But When the bridge is connected it just jumps on and off at random intervals. It only lasts a second, but it is enough to sometimes sever the link with the other QNB. And my ME drives stay off for about 30 or more seconds.

Any insight into this is helpfull. Im at a loss, I've checked everything there is.

If needed here are the Screenshots:

Main network:
![qnb1](https://user-images.githubusercontent.com/47916457/53285394-28a80980-3760-11e9-9bd9-b32ae1c2332d.png)

Friends side:
![qnb2](https://user-images.githubusercontent.com/47916457/53285398-31004480-3760-11e9-81e3-0127f7d0630b.png)

**Comment by yueh** [comment]
Please make sure everything is chunkloaded.
