### ISSUE TITLE
Deceleration Card.

### ISSUE THREAD

**Issue by Yusunoha** [AppliedEnergistics/Applied-Energistics-2#3941]
**Describe the feature**

Currently AE2 has the acceleration card, which speeds up the processing speed of certain blocks and items. I'd like to suggest a deceleration card which does the exact opposite, it slows down the speed of blocks and items. 

For machines this upgrade wouldn't really make much sense, because you want those to process items fast. For items such as import and export busses there could be some cases where this might be handy, but it's not something that's really needed. No, for this deceleration card there's one specific use I'm thinking of, the item interface.

Now you might think "You want to slow down the import and export speed of item interfaces?". No, this card is mostly meant for autocrafting with the item interface. Currently if you try to autocraft with the item interface, and you request a couple of the same item, the item interface dumps all the items into the machine and waits for the machine to process, but you don't always want that to happen.

Some machines and processes can only process 1 item at a time, and if everything gets dumped right away, the machine or process could get stuck on the crafting. Or if you've an item interface with several recipes, connected to a machine with several slots, and the recipes are chained, but don't take up all the slots, all the items get dumped aswell and the machine gets stuck.

With the deceleration card the item interface will only craft 1 recipe at a time, and will wait for the network to receive that crafting item before it sends the next batch of items for the other requested items.

**Reasons why it should be considered**

An example is rune-crafting with Botania. When crafting runes you can only craft them 1 at a time, and if you put more items in the altar than what's needed for a rune, the alter will refuse to work.

Or for example the Alchemy Table from Blood Magic. The alchemy table has several slots available, and some items require items that are also crafted in the table. If you try to request an item with chained recipes that require the Alchemy Table aswell, the table gets filled with all the items and it won't be able to process the items.

**Additional Context**

**Comment by yueh** [comment]
Use blocking mode.
