### ISSUE TITLE
Bidirectional partitioning for Storage Bus

### ISSUE THREAD

**Issue by Ar4093** [AppliedEnergistics/Applied-Energistics-2#3942]
**Describe the feature**

Right now, the partioning of a storage bus only affects which items can be inserted into the attached inventory.

It would be nice to have either an upgrade card or a toggle option for the Storage Bus so the partition works both ways (or maybe even both or either one direction).

**Reasons why it should be considered**

It would be useful if you want to expose only part of an inventory's items to AE.
For example, if you have some kind of inventory with a very large amount of different items in it, it can take a while for AE terminals to load. A specific example would be Equivalent Integration's Transmutation Chamber, which exposes all of a player's EMC transmutation knowledge to e.g. storage buses. This can easily be thousands of different items in larger modpacks.

**Additional Context**

**Comment by yueh** [comment]
Duplicate of #1573
