### ISSUE TITLE
Not compatible with Nomadic Tents.

### ISSUE THREAD

**Issue by masternetra** [AppliedEnergistics/Applied-Energistics-2#3944]
Minecraft fails to start with both this mod and Nomadic Tents, Minecraft faults Applied Energistics 2.

**Describe the bug**
Incompatibility with Nomadic tents when trying to load both Minecraft fails to start with both of them with Applied Energistics 2 faulted by MC.

**To Reproduce**
Just launch with Nomadic Tents and Applied Energistics 2.

**Expected behavior**
To launch to main screen.

**Additional context**
Log: https://paste.dimdev.org/igeturilef.mccrash
(Mentioned incompatibility at Nomadic tents too)

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-6
- Forge Version:14.23.5.2768

**Comment by Ommina** [comment]
> Failed to register dimension for id 2, One is already registered

Use the config to change the dimension ID for either AE2 or Nomadic.  They both want to use ID 2.  One of them will have to... not use 2.

**Comment by masternetra** [comment]
Forge's doing with the tent mod. The tent mod's config is set to allow forge to find a Dimension ID for it.
