### ISSUE TITLE
Patterns in the ME network not being considered

### ISSUE THREAD

**Issue by repairmant** [AppliedEnergistics/Applied-Energistics-2#3946]
Patterns in the ME network not being considered for autocrafting

Example: request 1 charger it says im missing 2 Fluix Seed (another ME Interface has a custom pattern for seeds to pure with it going to water/growth machines) when I have that pattern in an ME Interface next to 4 Molecular Assemblers

**Expected behavior**
I would expect when requesting 1 charger with the autocraft system that it would goto see if there is the needed Pure Fluix Crystal then when there is to use the patten for that which it seems to do but then when it also see that the needed Fluix Seeds needed for making the Pure Pluix Crystal aren't in the system it Should look for the pattern for Fluix Seeds that is also in the system.

**Environment**
It's a 24/7 Multiplayer Server
Server Mod List: http://prntscr.com/msebcr

- Minecraft Version: 
- AE2 Version: rv6-stable-6
- Forge Version: 2768

**Comment by Mordenkainen** [comment]
The seeds behave oddly. If you hand craft a seed and then build a pattern with it, you will get the behaviour you describe. But the following works for me:

1. Create a pattern for the seed and install it in an interface.
2. Use AE to craft a seed.
3. Use the seed AE crafted to create the pattern for the crystal.
4. Install that pattern in your seed growing machine.

For some reason AE sees the hand crafted seed and the AE crafted seed as different items.

**Comment by repairmant** [comment]
Also noticed other stuff having this behavior like Capacitor Bank used in Vibrant Capacitor Bank

**Comment by repairmant** [comment]
Also had to do it with all the different tiers of Capacitors like Flux Capacitors from Simply Jetpacks. And now its trying to craft a Flux Capacitor (Signalum) and it shows it has all the materials it needs but not its just stuck with an ETA of zero time.

**Comment by fluid-uu-matter** [comment]
AE2 should add option to ignore NBT in patterns for automation. also option to ignore meta for ingredients.

**Comment by Pingger** [comment]
Already discussed OFTEN, NBT ignoring will not happen for autocrafting:
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3897
