### ISSUE TITLE
Entering atmosphere is galacticraft causing crash

### ISSUE THREAD

**Issue by japsiken** [AppliedEnergistics/Applied-Energistics-2#3947]
Im running lapitos galacticraft version 2.0.8 off the twitch cruse launcher. I recently finished building a tier 1 rocket and launched with only the components to build a teleporter and to power it. After launching into the atmosphere the game crash stating "shutting down internal server". And has done that ever since when trying to load the world, even stating the above message while still displaying the "loading world" message. Afterwards it states that applied energistics was the issue and gives me the following report, this is on a standalone machine in solo play. any help with this would be greatly appreciated.

https://paste.dimdev.org/omaretalel.mccrash

**Comment by yueh** [comment]
Looks like a corrupted world, I'd recommend restoring a backup and try if it still occurs.
