### ISSUE TITLE
Lag when autocrafting simple recipes

### ISSUE THREAD

**Issue by MiningPickaxe** [AppliedEnergistics/Applied-Energistics-2#3948]
**Describe the bug**

The server is running really slow with laggoggles reporting insane amounts of ticktime used for the AE2 Event Subscriber (in the 100000s of µs) and the TPS drop down to about 9 tps every now and then. "stable" is 15tps. We havent had this issue before and cant trace it back to something we changed in our AE systems. This even lead to multiple crashes this evening because the ticktime exceeded the allowed limit (which is 2 mins)

**To Reproduce**

Cannot reproduce this in a fresh world, but the issues persist on the current one. If nessecary I can provide a download link to the 2.7gb world folder.
**Expected behavior**

I don't expect the lag when nothing is autocrafting and even crashing of the server.
**Additional context**

Crashlog: https://gist.github.com/MiningPickaxe/5edaf63f9c7de1e8dbe804541a1cdb49
**Environment**

Forge Server running on a E3-1270v6, 7gb of memory allocated to java with 12gb in total. 
Java 1.8.0_191
Ubuntu with Kernel 4.15.0-42-generic

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-6
- Forge Version: 14.23.5.2781
- Modpack: Enigmatica 2

**Comment by yueh** [comment]
That is simply what Forge considers acceptable performance for recipe lookups. Nothing we can really do about it. 

At least not until 1.13 or maybe even 1.14. And then only when whatever Mod API exists at point decides to not break recipes again to allow the old behaviour with all of its downsides.
