### ISSUE TITLE
Interface performance issues

### ISSUE THREAD

**Issue by Sir-Will** [AppliedEnergistics/Applied-Energistics-2#3949]
Is there anything which can be done by AE2 to improve the performance of the interface's?

![](https://i.imgur.com/spoypgD.jpg)

**Environment**
Multiplayer

- Minecraft Version: 1.12
- AE2 Version: appliedenergistics2-rv6-stable-6
- Forge Version: forge-1.12.2-14.23.5.2796-universal

**Comment by yueh** [comment]
Duplicate of #3948
