### ISSUE TITLE
Recipe for Crafting Storage to storage component not able to be removed

### ISSUE THREAD

**Issue by Thedrummonger** [AppliedEnergistics/Applied-Energistics-2#3951]
Attempting to remove the recipe that turns a crafting storage block into a storage component with crafttweaker does not work.

**Describe the bug**
I have added a line in my crafttweaker script to remove the recipes for all storage components. I have verified the script works since it removes the base crafting recipe for the components. It does not however remove the recipe that allows you to turn a crafting storage back into a component. Since I have a completely separate and cheaper recipe for crafting components in my pack this causes issue.

**To Reproduce**
Add the crafttweaker file below to an instance with Crafttweaker and Applied Energistics 2.

**Expected behavior**
All recipes for the storage components, including the one that converts a crafting storage back into a component, should be removed.

**Additional context**
Crafttweaker Script:
https://pastebin.com/HycWbbEa

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-6
- Crafttweaker Version: 1.12-4.1.15
- Forge Version: 14.23.5.2815

**Comment by fluid-uu-matter** [comment]
Maybe you can remove this recipe using AE2 built-in recipe customizer

**Comment by yueh** [comment]
That is a standard CT recipes as far as I can tell. Nothing related to our custom handlers.

Probably better to ask CT directly for help as I actually don't have the slightest clue about it.
