### ISSUE TITLE
Reseting spatial storage cells

### ISSUE THREAD

**Issue by fluid-uu-matter** [AppliedEnergistics/Applied-Energistics-2#3952]
**Describe the feature**
When a storage cell is completely filled with air, you will be able to reset the cell(May need a machine like spatial dis-linker), dis-linking it from the current area in the storage dimension, and reusable as a new spatial cell. The dis-linked space will also be reusable for new spatial storage.

**Reasons why it should be considered**
Enlarging spatial pylon makes old cells unusable

**Additional Context**

**Comment by mindforger** [comment]
Did you try to dismantle the disk? (I did not try, just an idea). Just crouch + right click with the disk in your Hand. This dismantled normal disks but i have no idea if it works with spatial cells

**Comment by yueh** [comment]
Not worth the effort with tracking the freed ids, add ways to revert an accident, etc.
