### ISSUE TITLE
ATM3 remix - Crashed when putting wireless terminal into bauble slot

### ISSUE THREAD

**Issue by V0odoofyxen** [AppliedEnergistics/Applied-Energistics-2#3953]
(cross posted to ATM3R) Playing All the mods 3 remix v 1.1.0 . Crashed upon putting wireless crafting terminal which had been combined with the fluid terminal and crafting terminal into bauble slot. reloaded/reentered the world, seemed to load fine but am unable to open my inventory at all, crashes as soon as I try to open it or use the key I assigned to open the terminal with.

any help would be appreciated

first crash report - https://pastebin.com/R9fP1nij
second crash report- https://pastebin.com/4YWFxNNm
third crash report - https://pastebin.com/PwRjbrae
last crash report - https://pastebin.com/Sp5pXWri

- Minecraft Version: 1.12.2
- AE2 Version:  appliedenergistics2 rv6 stable 6 jar is what it says in the mod list for ATM3r
- Forge Version: -14.23.5.2811

**Comment by BrockWS** [comment]
This is a ExtraCell2 issue, which has been reported at ExtraCells/ExtraCells2#619
