### ISSUE TITLE
Sap from Thermal Foundation lost on storing it

### ISSUE THREAD

**Issue by Sephiroth018** [AppliedEnergistics/Applied-Energistics-2#3955]
#### Description
When producing sap from Thermal Foundation and then importing it into the network with a fluid import bus, the sap is completely lost. The same happens when I try to store a bucket of sap via the fluid terminal. When I have some external storage with sap and an external storage bus on it, I can see and take out sap in the fluid terminal, but still not store it again. Also, when using the "partition storage" button on the storage bus, nothing happens. Transfering it via liquid P2P tunnels works.

#### Environment
- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-3
- Forge Version: 14.23.4.2772
- Multiplayer
- Modpack [FTB Presents Direwolf20 1.12](https://www.feed-the-beast.com/projects/ftb-presents-direwolf20-1-12)

**Comment by yueh** [comment]
Cannot reproduce it with the current version.

Could the tank simply disallow inserting fluids? Or at least limit it to a certain side, the storage bus is not attached to?

**Comment by Sephiroth018** [comment]
I'm using fluid storage cells to (try to) store it, the external storage was just to test if I had an error in my setup.
To sum it up:
- Taking it out of the network when it is stored somewhere (eg some tank hooked up with an external storage) via fluid terminal works
- Putting it into the network via fluid import bus or fluid terminal does not work, sap is accepted but lost.
- P2P fluid transfer via pipes works.

**Comment by yueh** [comment]
Hm. The pack is also not using the latest release and I did fix some fluid related bugs with inserting/extracting them. Could be already fix in a newer one.

**Comment by Sephiroth018** [comment]
Tried it with the latest version (rv6-stable-6), it works correctly. Thanks for investigating this.
