### ISSUE TITLE
performance with crafting cards server skipping ticks

### ISSUE THREAD

**Issue by blinkinglight** [AppliedEnergistics/Applied-Energistics-2#3956]
in enigmatica 2 expert i have big system: 300x64k drives, 50M+ items, 1000 crafting recipes, and several hundreds of different item types.

**Describe the bug**
base "crafting task" time is "big" ( for example 300ms ) 

**To Reproduce**
if you add to system 10 export busses without acceleration cards but with crafting card, you get base crafting task time * 10 crafting cards, that causes server to skip ticks. 

**Expected behavior**

**Additional context**
nps for visualvm https://we.tl/t-CHflkI4iK6
tickprofiler - https://pastebin.com/PfbPZMJk

**Environment**

on personal server - 1 player

enigmatica 2 expert 1.57

- Minecraft Version:  1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-6.jar
- Forge Version: forge-14.23.5.2781

**Comment by yueh** [comment]
There is not much we can do about it in these extreme cases. 1.14 might improve it a bit, but not possible with 1.12 sadly.

The best solution would be to move continuous crafting requests to a subnetwork and only provide the necessary materials for it. E.g. via interfaces or dedicated storage.
