### ISSUE TITLE
Disks Disappeared from ME Drive after wrenching it

### ISSUE THREAD

**Issue by Cri16228** [AppliedEnergistics/Applied-Energistics-2#3958]
Today I was playing Project Ozone Lite on a public server and I wanted to move my applied network, I did it and I placed 5 ME Drive (2 full of disks) and I wanted to rotate them but for how I placed them 2 were upside down so I took my certus quartz wrench and I shift-clicked it to remove it, the problem is that I lost my drives, so I was thinking "A mod like this doesn't implement a drop of content when the block is wrenched?" So I took another ME Drive, put a empty disk, wrenched it and It dropped the disk and the ME.
My question is: Is this even possible? Is there any remove chance where the ME Drive removed with a wrench (with disks inside) can drop only itself? I can't have my stuffs back but I want to know if it is a known bug, a solved big in newer versions or a new bug (if is a bug)

- Minecraft Version: 1.10.2
- AE2 Version: appliedenergistics2-rv4-stable-1 (https://minecraft.curseforge.com/projects/applied-energistics-2/files/2454983)
- Forge Version: 12.18.3.2511

**Comment by AzazeII** [comment]
>My question is: Is this even possible? Is there any remove chance where the ME Drive removed with a wrench (with disks inside) can drop only itself?
There is no chance to drop only me drive, when you wrenching ME Drive full of items. So it's definitely bug

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.12 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
