### ISSUE TITLE
ME Fluid Interface exports the same fluid to all faces

### ISSUE THREAD

**Issue by RobertBouillon** [AppliedEnergistics/Applied-Energistics-2#3959]
EC2 Fluid Interface has 6 slots in the UI: one corresponding to each side. This allows you to pipe out up to 6 different fluids: one to each side. The AE2 fluid interface has 6 slots in the UI, but exports the fluid in the first slot to every side. The other 5 slots don't change the behavior of the interface.

**Describe the bug**
EC2 Fluid interface only exports the first fluid to all faces

**To Reproduce**
Import 6 different fluids into a new ME system.
Attach a Fluid Interface
Configure the Fluid Interface to export a different fluid to each face
Attach fluid pipes (Such as a TE fluiduct) to each face.
Only one fluid fills each fluiduct

**Expected behavior**
Import 6 different fluids into a new ME system.
Attache a Fluid Interface
Configure the Fluid Interface to export a different fluid to each face
Attach fluid pipes (Such as a TE fluiduct) to each face.
**A different fluid will fill each fluiduct**

**Additional context**
https://imgur.com/a/GZLCTox
Expected Behavior
![image](https://user-images.githubusercontent.com/612152/54708725-63f8e680-4b1a-11e9-8ae5-b16655e350a2.png)
Actual Behavior
![image](https://user-images.githubusercontent.com/612152/54708737-69563100-4b1a-11e9-8ca8-a57149112154.png)

**Environment**
FTB Revelations 2: 2.7.0
MC: 1.12.2
AE2: Rv6-6

**Comment by yueh** [comment]
This is intentional.

**Comment by RobertBouillon** [comment]
How do you get the other fluids out?

**Comment by RobertBouillon** [comment]
Also, is there a reason this behavior is different then EC2? I was optimistic that this would deprecate EC2's fluid functionality, but now it seems like I'll need to keep it around.

**Comment by Aranak** [comment]
i have the same issue have 2 fluid and i try to export both on 2 different fluid conduit with both who have a filter each white listed. And only the first fluid can be exported and not the other one.

**Comment by AzazeII** [comment]
>How do you get the other fluids out?

Maybe filter will help?

**Comment by Aranak** [comment]
i did not filter dosent work

**Comment by AzazeII** [comment]
Also you can attach 6 interface buses, instead of one block, and give each different fluid filter. Put it all into subnetwork and provide it's inventory trough storage bus to main network, to avoid 6 channel lose(1 < 6)

**Comment by yueh** [comment]
I'd recommend asking the mod directly. They should know why they don't work with machines providing more than 1 tank.

**Comment by Aranak** [comment]
yueh its the reverse

**Comment by RobertBouillon** [comment]
> I'd recommend asking the mod directly. They should know why they don't work with machines providing more than 1 tank.

Can you expose more than one tank per face? Isn't it one fluid per face? Wouldn't the way to expose multiple tanks be to provide a different one to each face? That's how EC2 does it.

XNET won't extract more than one fluid, either.

**Comment by AzazeII** [comment]
>Edit: im trying Azazell trick

So you should build something like this
![Screenshot 2019-03-23 at 01 00 25](https://user-images.githubusercontent.com/32298517/54855438-5a80a180-4d07-11e9-9617-fc01ef27c9d4.png)

**Comment by Aranak** [comment]
thank you azazell for the plan B :)

**Comment by yueh** [comment]
Yes, it's built into the normal fluid handlers. Should support up to `2^31-1` tanks per side.

Afaik it just not something many mods do and I recall at least one TE machine being very picky about it and basically only checking the first tank for the filtered fluid and no other. Would not be surprised when it also applies to ducts, etc.

**Comment by Aranak** [comment]
Yueh iw as trying with ender io
