### ISSUE TITLE
Already Building! crash

### ISSUE THREAD

**Issue by Dayyer1** [AppliedEnergistics/Applied-Energistics-2#3961]
**Describe the bug**

When scrolling through an ME Crafting Terminal, I get a crash. I also included a log. This also sometimes happens when searching for items.
**To Reproduce**

I think that the crash is related to rendering an item, and I'm not sure what mod the item is from. I'm hoping you could help.
**Expected behavior**

I was scrolling and the game froze and crashed. I was expecting to go further down the terminal.
**Additional context**

[crash-2019-03-21_19.52.11-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/2994645/crash-2019-03-21_19.52.11-client.txt)

[latest - copy 2.log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/2994647/latest.-.copy.2.log)

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-6
- Forge Version: 2822

**Comment by yueh** [comment]
Yes, looks like some broken/corrupt items. The log also contains some entries about rendering some items did fail. Sadly it does not report which ones failed. Would probably be an idea to extend the log entry about it.

So for now it's not really possible to determine which item/items could cause it.

**Comment by Dayyer1** [comment]
How can I get an extended log? Or was the log cut short already somehow?

**Comment by yueh** [comment]
Does not exist at all and needs to be added in a future release. But that is currently just a guess, so no guarantee that it even provides any useful information.

For now probably the best option is probably to identify the broken item by either sorting by name/mod and start guessing which one it could be by searching for a specific one until it crashes. Maybe even identify the cell first by checking every via a ME chest until it crashes and then try to export the broken one via an export bus or IO Port into a chest or similar.
