### ISSUE TITLE
Toggle bus screws up large network

### ISSUE THREAD

**Issue by SimonFriedberg** [AppliedEnergistics/Applied-Energistics-2#3962]
I have a somewhat large network and I have recently tried to attach a toggle bus. I am still trying to figure out the details but it seems the issue is caused by the toggle bus.

Here is the detailed setup:.
1. Largish network (nowhere close to the 2048 for the achievement)
2. Cobblestone flows ins from a miner
3. Cobble gets compressed in an external machine
4. A toggle bus disconnects the interface where that external machine pulls when the cobble supply is low

Now, I am experiencing some strange behavior on my network and I think what is happening is the following:
1. Cobble supply is somewhere around the limit which triggers the level emitter
2. The level emitter toggles the bus and adds/removes the interface every few seconds or even more often
3. The network takes a long time to figure out what is connect (in general)
4. These two interact and keep the network from reaching a stable state

I am using AE2 from the Divine Journey modpack for 1.7.10.

**Comment by SimonFriedberg** [comment]
If you have any suspicions what this might be or suggestions for debugging please do let me know!

**Comment by yueh** [comment]
Using a toggle bus can cause the network the repath, which will take a moment by design and scales depending on the network size. Usually it shouldn't be an issue, but needing to switch within a couple seconds probably won't be stable.
