### ISSUE TITLE
Crash with ae2 and flux networks

### ISSUE THREAD

**Issue by 123Kappa** [AppliedEnergistics/Applied-Energistics-2#3965]
**Describe the bug**
Crash, judging for the crash report it happens when a flux point connects with a me system. It's a common crash, server crashed 10 times in 3 days.

Crash report: https://paste.feed-the-beast.com/view/6726bb55

**Environment**

Minecraft Version: 1.12.2
AE2 Version: rv6-stable-6
Forge Version: forge-1.12.2-14.23.5.2808

**Comment by yueh** [comment]
We do not support anything like Sponge or Bukkit officially. Only a standard forge environment.

Should you be able to reproduce it without it, please update the issue accordingly and we will reopen it.

**Comment by 123Kappa** [comment]
https://github.com/SonarSonic/Flux-Networks/issues/105

Seems similar to this.
