### ISSUE TITLE
(enhancement) The possibility to name interfaces with custom names

### ISSUE THREAD

**Issue by NarigudoBR** [AppliedEnergistics/Applied-Energistics-2#3966]
**Describe the feature**

you should be able to configure the name of exhibition of the interface in the interface terminal
, configured in the interior of the interface itself;
**Reasons why it should be considered**

 I have multiple interfaces in chests or any inventory block,feeding different machines(like IE presses or mekanism machines) how can I differentiate them without looking at the patterns inside of the interfaces?

**Additional Context**

**Comment by yueh** [comment]
Just rename them.
