### ISSUE TITLE
add range support to level emitters and crafting cards

### ISSUE THREAD

**Issue by blinkinglight** [AppliedEnergistics/Applied-Energistics-2#3968]
**Describe the feature**

level emitter - start emitting signal if items count less 10  and emit till it reaches X ( X = 1000 )
crafting card - if less 10 items  craft until reaches X ( X = 100 )

**Reasons why it should be considered**
less crafting requests.

**Additional Context**

**Comment by yueh** [comment]
Already possible with vanilla.
