### ISSUE TITLE
Seed "Errors" (Too many meteors)

### ISSUE THREAD

**Issue by theriftwalker** [AppliedEnergistics/Applied-Energistics-2#397]
Apparently I'm being suggested to start AE. http://puu.sh/cFfQL/d26046eccd.jpg  http://puu.sh/cFfWf/7cca9d1d8c.jpg  http://puu.sh/cFg1B/755d4707d8.jpg (I'd hate to be that guys barber)  Seed is : 113963865144355269 with BoP installed, but not enabled.

**Comment by thatsIch** [comment]
Somebody per chance still encountering this?

**Comment by moto1239** [comment]
2016 and I'm experiencing it with a new world.
Running Feed The Beast Infinity Evolved v2.3.5

![2016-01-21_14 07 09](https://cloud.githubusercontent.com/assets/16826578/12496098/78c4538e-c048-11e5-9c0f-5b4ed677a4f2.png)
![2016-01-21_13 59 06](https://cloud.githubusercontent.com/assets/16826578/12496111/81166ad6-c048-11e5-9bf1-7eb92d903036.png)
First time using GitHub \o/
Let me know if more info/pics/world file is needed

**Comment by wlhlm** [comment]
What are the coordinates and what is the seed? Are you running modpack unmodified?

**Comment by moto1239** [comment]
Seed is -3468532045546355263 coordinates are around x: -550, z:800
iirc I haven't modified the pack, just updated it as a matter of fact.

**Comment by thatsIch** [comment]
this is bullshit

**Comment by thatsIch** [comment]
Is this on a server  @moto1239

**Comment by moto1239** [comment]
No

**Comment by Digitalsabre** [comment]
So, apparently I'm not the only one getting what's ostensibly entirely meteorite-based biomes...

**Comment by gamecompiler** [comment]
Could it be that Biomes o plenty has a problem with mod rv2 ? Appearantly that "Bug" do not appear when using the default WorldGen.

I try to figure out why BOP-1.7.10-2.1.0.1394 and AE2-rv3-beta-1 work perfectly, but BOP... with AE2-rv2 not. 

So the "resolution" for this problem is to update to rv3-beta-1.

**Comment by Sxw1212** [comment]
I experienced this bug without BOP. I had rv2, but I don't know if rv3 fixes everything or not.

**Comment by mindforger** [comment]
why would you not update to the latest rv3.beta build 6 instead on rv3.beta build 1 ?!

**Comment by thatsIch** [comment]
I assume rv3 fixed that. We rewrote some parts of the chunk management system of the metereorites and fixing this is a nice side-effect
