### ISSUE TITLE
Dungeons Tactics with AE2?

### ISSUE THREAD

**Issue by SipaiL** [AppliedEnergistics/Applied-Energistics-2#3970]
When I try to shove the iron cluster from the dungeons tactics mod into a quartz crusher, I can’t do anything, and mine the quartz from minecraft cracks into dust. The option to transfer the cluster through the funnel to the quartz crusher also failed. What can you do about it? thanks for the answer.
Minecraft Version: 1.12.2
AE2 Version: rv6-stable-6
MOD PACK : Life in the village(1.10a)

**Comment by yueh** [comment]
Honestly I do not see how this relates to AE2 at all as nothing is mentions it directly. 
I'd really recommend contacting the modpack directly as it sounds either like an issue with it or at least a question for them.

**Comment by SipaiL** [comment]
I want to say that I myself added this mod to this modpack.
