### ISSUE TITLE
Please make the crafting terminal compatible with Futurepack.

### ISSUE THREAD

**Issue by ProsperCraft** [AppliedEnergistics/Applied-Energistics-2#3971]
Futurepack tests if the player crafting has done the research to craft something, currently this will not work in the AE Crafting Terminal.

**Additional Context**
https://github.com/mcenderdragon/Futurepack-API/issues/560#issuecomment-475987856

**Comment by yueh** [comment]
Such a functionality is pretty much limited by minecraft/forge itself as they do not provide anything to have player specific recipes for normal crafting. So it's simply nothing we can support, especially if the particular mod is closed source and it relies on reflecting into other mods to even work.

The best approach for these things would be something similar to Thaumcraft or other mods and add their own crafting table as well as a custom crafting terminal for AE2. Either directly or via some companion mod similar to the Thaumcraft/EE+AE2 integration ones.

**Comment by mcenderdragon** [comment]
I did add a custom crafting table (the Techtable) and people complained why their recipes did not work (because they used the vanilla table), so I added support for that one. Then they complained why table XY from mod Z did not work, so I ended up to just check the class if there was anything that could be a player... If my opinopn would matter, only our table would work, but I am tired of the drama...

**Comment by mcenderdragon** [comment]
if I saw it correctly if ContainerNull would have a player (used here https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv6-1.12/src/main/java/appeng/container/implementations/ContainerCraftingTerm.java#L82) then it should work. So basicaly, the normal ContainerCrafting

**Comment by yueh** [comment]
We also use the same approach for autocrafting and in this case there is simply no player availalble. So in these cases it's virtually impossible.

It's really limited to what normal crafting provides and locking recipes for players is simply nothing we'd anticipate as long as it's not part of minecraft/forge itself.
