### ISSUE TITLE
Crash with Electroblobs Wizardry

### ISSUE THREAD

**Issue by krisjenner** [AppliedEnergistics/Applied-Energistics-2#3973]
Client crashes when hovering over EB Wizardry item in AE terminal AND Wireless Crafting Terminal (addon)

**Describe the bug**

Hovering over an EB Wizardry item in AE system causes client crash.
**To Reproduce**

EBWizardry 4.1.4
**Expected behavior**

Able to hover over EB Wizardry item without crash

**Additional context**

[LOG1](https://gist.github.com/krisjenner/5bd85c0aad882fba019fe06eb97322eb)
[LOG2 WirelessTerm](https://gist.github.com/krisjenner/86c31a49522388959b9da957fbabe6f2)
**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-4
- Forge Version: 2815

**Comment by yueh** [comment]
Looks like this item expects at least a damage value of 1, otherwise it will crash. Something they have to fix as it's way to easy to create a default stack with a value of 0. E.g. some rewardbag didn't take the requirement into account.
