### ISSUE TITLE
Mekanism Cardboard Box causes problems in ME storage system

### ISSUE THREAD

**Issue by marred01** [AppliedEnergistics/Applied-Energistics-2#3976]
Same issue as described in #3756, Cardboard Box in AE storage system cannot be pulled out.  But will come out with an export bus with a fuzzy card.

**Describe the bug**
I'm on Enigmatica 2: Expert v.158.    3 cardboard boxes containing monster spawners were stuck in the AE system, was able to pull them out with an export bus with fuzzy card. 

More info:  I narrowed down the storage cells they were located on and using an ME Chest, I was able to remove everything else on the cells but the cardboard boxes, until I put an export bus on the ME Chest, with a fuzzy card.

The problem was first noticed because the terminal display would auto fill with cardboard box icons and keep filling, making it look like the cardboard boxes were reproducing like tribbles.

**To Reproduce**
Wrap a monster spawner in a cardboard box.  Put that box inside an AE system.  Had boxes stuck in both a 1k and a 4k storage cell.

**Expected behavior**

Cardboard boxes containing something, should go into and come out of the system through a terminal, and should not reproduce on the display of a terminal.

**Additional context**

**Environment**
Mod pack:  Enigmatica 2: Expert, non skyblock, installed and run through twitch client.

- Minecraft Version: 
- AE2 Version: 
- Forge Version:

**Comment by yueh** [comment]
#3756, #3589

It's basically a forge feature, which makes the clientside stack incomparable with the serverside one. Thus it cannot request the requested one.
