### ISSUE TITLE
[1.7.10]crash when loading a world

### ISSUE THREAD

**Issue by tonimark** [AppliedEnergistics/Applied-Energistics-2#3977]
the minecraft crashes upon loading a world

**Describe the bug**
the Minecraft crashes

**To Reproduce**
just load the world

**Expected behavior**
the world would load normally but instead, it crashed Minecraft (as open-eye report it )

**Additional context**
crashlog:https://pastebin.com/hRHrL9K0
YES
YES

**Environment**
eventually I removed a bugged mod but my Minecraft still crashes I haven't built anything about applied energistics 2
the list is long sorry, but i can tell you that enderIO also mess with this, I also got installed the latest versions of  extra cells addon with mekanism (it activates gases on extra cells mod)
messed mods:
applied energistics versions:rv3-beta-6
extra cells mod versions:1.7.10-2.3.14b200
mekanism versions:9.1.1.1031 (both machines tools and generators installed)
enderIO versions:1.7.10-2.3.0.429_beta
enderCore versions:1.7.10-0.2.0.39_beta
- Minecraft Version:1.7.10
- AE2 Version: rv3-beta-6
- Forge Version:1.7.10-10.13.4.1614-1.7.10-universal

**Comment by yueh** [comment]
Looks like a corrupted chunk.

But we do not really support 1.7.10 anymore.

**Comment by tonimark** [comment]
what ?!

**Comment by tonimark** [comment]
i only wanted a world that is good but instead it crashes all the time

**Comment by tonimark** [comment]
nah i have the must corrupted world in minecraft mods history
