### ISSUE TITLE
Rendering of drive fixtures is buggy

### ISSUE THREAD

**Issue by NyxCode** [AppliedEnergistics/Applied-Energistics-2#3978]
Rendering of drive fixtures is buggy

**Describe the bug**
When filling drive fixtures with storage cells, they are rendered incurrectly. Sometimes, filled fixtures appear empty, but most of the time their texture is just broken  

Here, you can just see through the LEDs on some of the drives:  
http://prntscr.com/n48eaw  
http://prntscr.com/n48ex1  
http://prntscr.com/n48f5j  

This fixture is actually filled with cells, but appears empty:  
http://prntscr.com/n48fka

Adding/Removing drives to/from one fixture often affects the rendering of others on the same network.

**To Reproduce**
Add drive fixtures to a network and place drives in them.

**Environment**
FTB Revelation 2.7.0

- Minecraft Version: 
- AE2 Version: rv6-stable-6
- Forge Version: 14.23.6.2796

**Comment by yueh** [comment]
Drive fixtures are provided by extracells, not AE2 itself.

**Comment by NyxCode** [comment]
oh, sorry - i have opened an issue there
