### ISSUE TITLE
Crash on start up appliedenergistics2-rv6-stable-6.jar

### ISSUE THREAD

**Issue by themoleman1000** [AppliedEnergistics/Applied-Energistics-2#3979]
So every time i start my game up it ends up crashing and not sure why #crash 
Description
i'm using appliedenergistics2-rv6-stable-6.jar and it keep crashing 
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-1.7.9-1.12.2.jar)
  wings (wings-1.1.0-1.12.2.jar)
  ObfuscatePlugin (Obfuscate-Mod-1.12.2.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 3/28/19 4:50 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Energistics 2 (appliedenergistics2)
Caused by: java.lang.IllegalArgumentException: Failed to register dimension for id 2, One is already registered
	at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:134)
	at appeng.core.Registration.registerSpatialDimension(Registration.java:201)
	at appeng.core.Registration.postInit(Registration.java:352)
	at appeng.core.AppEng.postInit(AppEng.java:233)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 561968008 bytes (535 MB) / 2617245696 bytes (2496 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2772 Optifine OptiFine_1.12.2_HD_U_E2 60 mods loaded, 59 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version           | Source                                          | Signature                                |
	|:------ |:--------------------- |:----------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJ  | minecraft             | 1.12.2            | minecraft.jar                                   | None                                     |
	| UCHIJ  | mcp                   | 9.42              | minecraft.jar                                   | None                                     |
	| UCHIJ  | FML                   | 8.0.99.99         | forge-1.12.2-14.23.5.2772.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ  | forge                 | 14.23.5.2772      | forge-1.12.2-14.23.5.2772.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ  | openmodscore          | 0.12.1            | minecraft.jar                                   | None                                     |
	| UCHIJ  | obfuscate             | 0.2.6             | minecraft.jar                                   | None                                     |
	| UCHIEE | appliedenergistics2   | rv6-stable-5      | appliedenergistics2-rv6-stable-5.jar            | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| UCHI   | baubles               | 1.5.2             | Baubles-1.12-1.5.2.jar                          | None                                     |
	| UCHI   | bibliocraft           | 2.4.5             | BiblioCraft[v2.4.5][MC1.12.2].jar               | None                                     |
	| UCHI   | cdm                   | 0.4.1             | cdm-0.4.1-mc1.12.2.jar                          | None                                     |
	| UCHI   | cfm                   | 6.2.0             | cfm-6.2.0-mc1.12.2.jar                          | None                                     |
	| UCHI   | codechickenlib        | 3.2.2.353         | CodeChickenLib-1.12.2.jar                       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHI   | chickenchunks         | 2.4.1.73          | ChickenChunks-1.12.2-2.4.1.73-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHI   | redstoneflux          | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHI   | cofhcore              | 4.6.1             | CoFHCore-1.12.2-4.6.1.22-universal.jar          | None                                     |
	| UCHI   | cofhworld             | 1.3.0             | CoFHWorld-1.12.2-1.3.0.6-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHI   | computercraft         | 1.80pr1           | ComputerCraft1.80pr1.jar                        | None                                     |
	| UCHI   | customspawner         | 3.11.4            | CustomMobSpawner-3.11.4.jar                     | None                                     |
	| UCHI   | mocreatures           | 12.0.5            | DrZharks MoCreatures Mod-12.0.5.jar             | None                                     |
	| UCHI   | ebwizardry            | 4.1.1             | Electroblob's+Wizardry+-+4.1.1+-+MC+1.12.2.jar  | None                                     |
	| UCHI   | enderstorage          | 2.4.5.135         | Ender-Storage-Mod-1.12.2.jar                    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHI   | jei                   | 4.12.0.216        | jei_1.12.2-4.12.0.216.jar                       | None                                     |
	| UCHI   | forestry              | 5.8.2.374         | forestry_1.12.2-5.8.2.374.jar                   | None                                     |
	| UCHI   | forgelin              | 1.8.2             | Forgelin-1.8.2.jar                              | None                                     |
	| UCHI   | mantle                | 1.12-1.3.3.39     | Mantle-1.12-1.3.3.39.jar                        | None                                     |
	| UCHI   | tconstruct            | 1.12.2-2.11.0.106 | TConstruct-1.12.2-2.11.0.106.jar                | None                                     |
	| UCHI   | exnihilocreatio       | 1.12.2-0.3.9      | exnihilocreatio-1.12.2-0.3.9.jar                | None                                     |
	| UCHI   | excompressum          | 3.0.26            | ExCompressum_1.12.2-3.0.26.jar                  | None                                     |
	| UCHI   | extrautils2           | 1.0               | extrautils2-1.12-1.9.9.jar                      | None                                     |
	| UCHI   | zerocore              | 1.12.2-0.1.2.8    | zerocore-1.12.2-0.1.2.8.jar                     | None                                     |
	| UCHI   | bigreactors           | 1.12.2-0.4.5.65   | ExtremeReactors-1.12.2-0.4.5.65.jar             | None                                     |
	| UCHI   | flansmod              | 5.5.1             | Flan's Mod-1.12.2-5.5.1.jar                     | None                                     |
	| UCHI   | flansmodapocalypse    | 1.0               | Flan's Mod-1.12.2-5.5.1.jar                     | None                                     |
	| UCHI   | forgemultipartcbe     | 2.6.1.81          | ForgeMultipart-1.12.2-2.6.1.81-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHI   | microblockcbe         | 2.6.1.81          | ForgeMultipart-1.12.2-2.6.1.81-universal.jar    | None                                     |
	| UCHI   | minecraftmultipartcbe | 2.6.1.81          | ForgeMultipart-1.12.2-2.6.1.81-universal.jar    | None                                     |
	| UCHI   | guideapi              | 1.12-2.1.8-63     | Guide-API-1.12-2.1.8-63.jar                     | None                                     |
	| UCHI   | harvestcraft          | 1.12.2w           | HarvestCraft-Mod-1.12.2.jar                     | None                                     |
	| UCHI   | ichunutil             | 7.0.2             | iChunUtil-1.12.2-7.0.2.jar                      | None                                     |
	| UCHI   | hats                  | 7.0.0             | Hats-1.12.2-7.0.2.jar                           | None                                     |
	| UCHI   | howlingmoon           | 0.9               | Howling-Moon-Mod-1.12.2.jar                     | None                                     |
	| UCHI   | waila                 | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                     | None                                     |
	| UCHI   | journeymap            | 1.12.2-5.5.2      | journeymap-1.12.2-5.5.2.jar                     | None                                     |
	| UCHI   | llibrary              | 1.7.9             | llibrary-1.7.9-1.12.2.jar                       | None                                     |
	| UCHI   | numina                | 1.10.0            | ModularPowersuits-1.12.2-0.7.0.035.jar          | None                                     |
	| UCHI   | powersuits            | 1.12.2-0.7.0.035  | ModularPowersuits-1.12.2-0.7.0.035.jar          | None                                     |
	| UCHI   | mrtjpcore             | 2.1.3.35          | MrTJPCore-1.12.2-2.1.3.35-universal.jar         | None                                     |
	| UCHI   | nei                   | 2.4.2             | NotEnoughItems-1.12.2-2.4.2.244-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHI   | openmods              | 0.12.1            | OpenModsLib-1.12.2-0.12.1.jar                   | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCHI   | openblocks            | 1.8               | OpenBlocks-1.12.2-1.8.jar                       | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCHI   | projecte              | 1.12.2-PE1.4.0    | ProjectE-1.12.2-PE1.4.0.jar                     | None                                     |
	| UCHI   | projectred-core       | 4.9.1.92          | ProjectRed-1.12.2-4.9.1.92-Base.jar             | None                                     |
	| UCHI   | thermalfoundation     | 2.6.2             | ThermalFoundation-1.12.2-2.6.2.26-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHI   | thermalexpansion      | 5.5.3             | ThermalExpansion-1.12.2-5.5.3.41-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHI   | thermaldynamics       | 2.5.4             | ThermalDynamics-1.12.2-2.5.4.18-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHI   | vehicle               | 0.37.0            | vehicle-0.37.0-mc1.12.2.jar                     | None                                     |
	| UCHI   | waystones             | 4.0.67            | Waystones_1.12.2-4.0.67.jar                     | None                                     |
	| UCHI   | wings                 | 1.1.0             | wings-1.1.0-1.12.2.jar                          | None                                     |
	| UCHI   | bauble_wings          | 1.0.0             | wings-1.1.0-1.12.2.jar                          | None                                     |
	| UD     | mobends_wings         | 1.0.0             | wings-1.1.0-1.12.2.jar                          | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-1.7.9-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
wings (wings-1.1.0-1.12.2.jar)
  me.paulf.wings.server.asm.WingsRuntimePatcher
  me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher
ObfuscatePlugin (Obfuscate-Mod-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
ForgelinPlugin (Forgelin-1.8.2.jar)
  
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
  openmods.core.OpenModsClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13476 Compatibility Profile Context 22.19.128.0' Renderer: 'AMD Radeon(TM) R5 Graphics'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	AE2 Version: stable rv6-stable-5 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_E2
	OptiFine Build: 20180728-185429
	Render Distance Chunks: 22
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13476 Compatibility Profile Context 22.19.128.0
	OpenGlRenderer: AMD Radeon(TM) R5 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4
- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-6.jar
- Forge Version: forge-1.12.2-14.23.5.2814-universal

**Comment by themoleman1000** [comment]
o yes for got to menchen as it was crashing with the latest version i tryed with one below it and got the same result

**Comment by yueh** [comment]
`Failed to register dimension for id 2, One is already registered`, some mod overtook the dimension for the spatial dimension after it was added to the pack.
