### ISSUE TITLE
Improved worldgen customization

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#398]
The worldgen options should be improved with the following options.
- Meteors
  - (existing) meteoriteDimension should just be a list, neither blacklist or whitelist
  - (new) option if the list is used as whitelist or blacklist. Users might only want to disable it for a single world and not have to add every future world to the whitelist.
  - (new) option to specify the ratio of overworld vs. underground meteors
- Certus
  - (new) like meteors dimension list as whitelist or blacklist

Also provide an IMC handler with messages to dimensions to the specific list.
There should be no need to use the whole API just to do this.

**Comment by AnrDaemon** [comment]
Do want x.x

**Comment by fscan** [comment]
Dont know if we need an API (or even just IMC). Deciding what generates where is probably mostly interesting for modpack authors, which can just change the config.

**Comment by mindforger** [comment]
some mods may specifically use this feature, like an special traait for RF tools dimensions ... an AE meteor shard for example ... or galacticraft ... meteors on moon should be almost exclusively surface while on "earth" maybe exclusively underground
