### ISSUE TITLE
Craft Tweaker problem

### ISSUE THREAD

**Issue by SacrificialFlame** [AppliedEnergistics/Applied-Energistics-2#3980]
**Describe the bug**

It would seem any time I add a Variable for Storage Component using Crafttweaker that it does not work and gives an error of Error: [crafttweaker | SIDE_Client]; Error Parsing when it is setup to like all the other Variables in the script and those work but none of the Storage Component or Storage cells can use a custom Variable to make a custom script
**To Reproduce**

**Expected behavior**

**Additional context**

**Environment**

SP/MP

- Minecraft Version:  1.12.2
- AE2 Version: Appliedenergistics2-rv6-stable06
- Forge Version: 14.23.5.2808

**Comment by bookerthegeek** [comment]
A copy of your script might help.

**Comment by SacrificialFlame** [comment]
You will see in this link the ones that don't have Variables are the ones that refuse to work, this has been an on going issues for months now, https://gist.github.com/SacrificialFlame/d5d45daf8ab2284c9bfa4d02d2114c75

**Comment by yueh** [comment]
Probably better to ask crafttweaker directly for help. I simply have not the slightest clue about it and in the end it's just normal crafting recipes with normal itemstacks.
