### ISSUE TITLE
Crash on server startup

### ISSUE THREAD

**Issue by andyad8865** [AppliedEnergistics/Applied-Energistics-2#3983]
when the server starts the it begins to construct AE2 and fails.
**Describe the bug**
fml catches a exception from AE2 that prevents the server from loading, no crashlog is generated as the server does not get a chance to before FML stops the server.

**To Reproduce**

currently it is just using enigmatica 2 expert skyblock and and every boot causes it to fail

**Expected behavior**
stops and outputs the error below.

**Additional context**
https://pastebin.com/wdQhVRj6 (error)
https://pastebin.com/UebPU3rk (full log)

**Environment**
Server enviroment: Linux - Ubuntu using java 5 SE JDK

- Minecraft Version: 1.12.2 
- AE2 Version: Latest stable branch
- Forge Version: 14.23.5.2781

**Comment by mindforger** [comment]
I am pretty sure using java 5 is heavily outdated, try using at least Java 7

**Comment by andyad8865** [comment]
we've changed pack as where where limited on time and now it is working, sorry for using your time
