### ISSUE TITLE
Quantum Network Bridge Disconnects / Level Emitter Problems

### ISSUE THREAD

**Issue by scriptomania** [AppliedEnergistics/Applied-Energistics-2#3986]
UPDATE: Added 4 AE Energy Cells, 2 on each end. Got Connection 2 online, just cuts out every so often.
![Applied Energistics 2 Power usage](https://user-images.githubusercontent.com/7844674/55447349-038d8e80-5589-11e9-8052-5a88460071b9.PNG)

Just to clarify I have 1 ChickenChunks Chunk loader, in both dimensions. Also have that chunk loading option set for both dimensions in JEI. In addition to chunkloading, I have 1 resonant energy cell full on each Quatum Network Bridge. 

Problem 1: After every refresh the network does, when a new cable is attached; It will disconnect the Quantum Network Bridge. I have connection 1 in the overworld and connection 2 in the void dimension. It fixes when I break and re attach the cable to connection 2.

Problem 2: On the connection 2 side, in the void. I have Mystical Essence farms, and essence being put into quantum storage units. From there, an Import bus with a level emitter underneath, making sure the storage of essence in the system is at 100,000. Just for safety measures. Lastly, All connections going into a P2P and into the Quantum Bridge. When the Quantum Network Bridge disconnects, and I reattach the cable, I have to re set every level emitter redstone mode, to emit when levels are below limit. Before I go to reset each level emitter, I check the storage unit, and it's importing the items into the system. (All though it's already at that setting, I just gotta flip it off and back on again..) 

Any solution to this? 
![2019-04-02_19 59 27](https://user-images.githubusercontent.com/7844674/55445853-e1910d80-5582-11e9-9d3f-fbc41cdef896.png)
![2019-04-02_20 01 02](https://user-images.githubusercontent.com/7844674/55445861-ea81df00-5582-11e9-9393-ad802a08dc49.png)

Project Ozone 3 - Twitch Launcher
Minecraft Version: 1.12.2
Forge Version: 14.23.5.2808
Applied Energistics 2 Version: RV6-Stable-6

**Comment by mindforger** [comment]
Try a spotloader which keeps the chunkloader loaded(or many spotloader as replacement), may sound stupid but the chunkloader acted funky some times for me but the spotloader never failed for me

**Comment by scriptomania** [comment]
> 
> 
> Try a spotloader which keeps the chunkloader loaded(or many spotloader as replacement), may sound stupid but the chunkloader acted funky some times for me but the spotloader never failed for me

Well, It's managing to stay on with the addition to spot loaders. I think AE Should look into there own chunkloading feature. 

Thanks for the tip!

**Comment by mindforger** [comment]
i did report this to chicken chunks a long time ago and i think it never got resolved ... somethign with loading the dimension does trouble the chunkloader somehow but spotloaders work jsut fine and are kind of a jumpstarter
