### ISSUE TITLE
fluix crystal can't be made in sever

### ISSUE THREAD

**Issue by dablackM** [AppliedEnergistics/Applied-Energistics-2#3989]
fluix crystal can't be made in sever
**Describe the bug**

when I make the fluix crystal in single game, it works. But, when I made it in onlion game , it fails.I use the sponge to hold a sever, is that relevant?
**To Reproduce**

**Expected behavior**

**Additional context**

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-6
- Forge Version:1.12.2-forge1.12.2-14.23.5.2810

**Comment by yueh** [comment]
We do not support anything like Sponge or Bukkit officially. Only a standard forge environment.

Should you be able to reproduce it without it, please update the issue accordingly and we will reopen it.

**Comment by dablackM** [comment]
But,it just happen in the server,the forge version is 1.12.2-forge1.12.2-14.23.5.2810 .

**Comment by Pingger** [comment]
Correct if I'm wrong, but Sponge is just a serverside modification is it?
So you are just proving the point, that the issue is caused by sponge, since Singleplayer does not use Sponge and everything is working fine there

**Comment by mindforger** [comment]
Not 100% correct. Sponge does a lot of Things differently than a normal server, this is why it is not supported. If the issue can be replicated without, there still would be more informations required to help this case. 

For now just a random guess, some plugin or config is messing with floating items on the ground.
