### ISSUE TITLE
AEApi question: How to get outer grid from main grid

### ISSUE THREAD

**Issue by AzazeII** [AppliedEnergistics/Applied-Energistics-2#3991]
#### API
Version: RV6

#### Description
I'm trying to create visualisation tool in my mod. Currently i need to get relatively outer grid from main grid, to get all info about subnetwork. I figured out, that EnergyGridCache::providers can give me info about all nodes which carrying only energy, but not channels. But even with these nodes, if node is connected at side of cable from main network(red) calling it's function GridNode::getGrid() will only give me inner(main) network, but not subnetwork. Here is screen shot of network setup
![Screenshot 2019-04-07 at 22 33 07](https://user-images.githubusercontent.com/32298517/55688763-2d79f300-5985-11e9-9b16-ad723fc3b8ad.png)

My question is: How i can get list of grids of all subnetworks connected to main network?

**Comment by yueh** [comment]
There is none.

**Comment by AzazeII** [comment]
(Just for case if someone will need this later)
I'll leave this here:
[SubnetHelper.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/3053372/SubnetHelper.txt)

And here is usage:
[TopologyUtils.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/3053376/TopologyUtils.txt)
