### ISSUE TITLE
ME formation planes (normal and fluid) not working

### ISSUE THREAD

**Issue by Dimentive** [AppliedEnergistics/Applied-Energistics-2#3993]
#### Description of bug
The ME formation plane and ME fluid formation plane are not working.

I have supplied them with channels, I have blocks and fluid in my network, I have blocks and fluids entering my network, I have configured them so that they place certain blocks and fluids, I have power, they have higher priority than everything else, and everything is on the same network, but they’re not working.

I tried using formation planes in both my survival world and a creative test world, and they didn’t work in my first ME system setup in the creative world, nor did they work in my survival world, but when I created a _second_, separate, ME system setup, it worked, but going back to my first setup, it doesn’t work. In my creative test world—the same world, mind you—I have one setup where the block and fluid formation planes aren’t working whatsoever and another identical setup where they _are_ working.

I then tried making a _third_ ME network, replacing the first network I made in my test world, and _this_ time, the _block_ formation plane works just fine but _not_ the fluid formation plane. I am really confused. This is one of the strangest bugs I’ve encountered in any mod.

And yes, I do have blocks and fluids entering the network rather than simply sitting in the network.

I’ve asked others to try it out, and they can’t get the formation planes to work either.

#### To reproduce
* Create an ME network.
* Put a block and fluid into the system.
* Put an ME formation plane and an ME fluid formation plane somewhere in the network.
* Configure the formation planes to place the block and fluid in the system.

#### Expected behaviour
The expected behaviour is for the ME formation plane to place the block it’s configured to place and for the ME fluid formation plane to place the fluid it’s configured to place.

#### Additional context

**Environment**
![Formation plane](https://user-images.githubusercontent.com/34230933/55859844-2fa1a480-5b73-11e9-900c-6ae67f8a37ff.png)
![wot](https://user-images.githubusercontent.com/34230933/55860001-89a26a00-5b73-11e9-8370-1e742195f789.png)
![And NOW it works, apparently… but only here](https://user-images.githubusercontent.com/34230933/55860032-9c1ca380-5b73-11e9-8575-cfa0c1bebc01.png)

#### Versions

* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2781
* **Modpack:** [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2) (version [1.63a](https://minecraft.curseforge.com/projects/enigmatica2/files/2691579), latest)
* **Applied Energistics 2:** [rv6-stable-6](https://minecraft.curseforge.com/projects/applied-energistics-2/files/2652453) (latest)

**Comment by AzazeII** [comment]
In my modpack it is working, maybe there is issue with one of AE2 addons in your modpack, or maybe you have incorrect setup. Try to set up maximum priority in formation plane and add some fluid(or items) into the network. Or you can just try to reproduce this in subnetwork. If planes still not working, then problem is caused by one of addons in your modpack. My setup:
Fluid Formation Plane:
![Screenshot 2019-04-10 at 18 32 16](https://user-images.githubusercontent.com/32298517/55892425-fd1d9900-5bbe-11e9-8fe8-de5ff1d49c6c.png)

Item formation plane:
![Screenshot 2019-04-10 at 18 33 39](https://user-images.githubusercontent.com/32298517/55892553-2c340a80-5bbf-11e9-99a8-3483f15cb909.png)

**Comment by yueh** [comment]
Also cannot reproduce. I would recommend reporting it to the modpack itself, they might use some protection mods to prevent spawning items/fluids or similar.

**Comment by Dimentive** [comment]
>In my modpack it is working, maybe there is issue with one of AE2 addons in your modpack, or maybe you have incorrect setup. Try to set up maximum priority in formation plane and add some fluid(or items) into the network.

I didn’t have an incorrect setup, I did set maximum priority in the formation planes, and I did add fluids and blocks into my network.

Because you two cannot reproduce, and because the people I got to test this out also played the same modpack as I do, it’s probably a problem with the modpack. I have no idea what could possibly be causing this, though.

**Comment by SPWC** [comment]
I have the same problem, only tried with Fluid Formation and Annihilation Planes, both didn't work. Playing on Project Ozone 3 Version: 3.0.38

Minecraft Version: 1.12.2

(modded) forge-14.23.5.2808

**Comment by Dimentive** [comment]
Just like [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2) (the pack I’m playing), [Project Ozone 3](https://minecraft.curseforge.com/projects/project-ozone-3-a-new-way-forward), too, has the Applied Energistics 2 add-ons [AE2 Stuff](https://minecraft.curseforge.com/projects/ae2-stuff) and [ExtraCells2](https://minecraft.curseforge.com/projects/extracells2), so it _could_ be one of those mods causing this.

**Comment by tylerwiegand** [comment]
Not sure if this is important info, but I thought mine wasn't working, when in reality it was only functioning when new items entered the system -- not from the items just being available in the ME system.

**Comment by Kinomora** [comment]
Not working currently on Glacial Awakening for 1.12.2

**Comment by HarshNormal** [comment]
Playing Departed3, which does have AE2 Stuff and ExtraCells2. I've tried to create several different valid systems that would import fluids into an ME chest, ME drives, and just as @tylerwiegand said, it will not place fluids into the world from those storage locations, only when a new bucket has entered the system and moves directly to the fluid formation plane.
Again, nothing in the storage drives is being placed by the fluid formation plane.

**Comment by Guigui220D** [comment]
happens to me in 1.16.5

**Comment by mindforger** [comment]
> happens to me in 1.16.5

not really helpfull, make a new issue please and follow the template to provide required info.

**Comment by Guigui220D** [comment]
> > happens to me in 1.16.5
> 
> not really helpfull, make a new issue please and follow the template to provide required info.

Sorry, I meant that I have the exact same problem as the last message. I'm on a custom modpack with only a dozen mods and the formation plane only forms the fluidbwhen I insert  bucket.

**Comment by mindforger** [comment]
>with only a dozen mods 
 in 1.16.5

is still more than just AE2 and tell nothing ybout the mod or forge version used, this is why i asked you to make a new fresh issue according ti the template :) 

PS: debug crash report can be done by holding do2n F3 + C while ingame until it crashes forcibly

**Comment by shartte** [comment]
This also sounds like misunderstood behavior. At least if the last few comments are to be believed.

Formation planes act like "storage". Items are not automatically moved from storage to other storage in AE2, so they will only "place" a block if something enters the network.

**Comment by mindforger** [comment]
i think what @Cerebricide wanted to say is, with an system composed of fluid storage and formation plane alone it will not place any fluid at all but when you add some sort of fluid input into the system it will be moved to the formation plane and successfully deploy
