### ISSUE TITLE
Mod interraction crash (Project EX)

### ISSUE THREAD

**Issue by demethan** [AppliedEnergistics/Applied-Energistics-2#3994]
https://github.com/LatvianModder/Project-EX/issues/32

Server freeze with autocrafting. 

**Describe the bug**
I am playing FTB Sky Odyssey 1.0.0 , I put some storage bus in extract only mode on the Project EX - Refined EMC Link.  this block provides items based on available EMC. It works great with the crafting terminal. With autocrafting, the server freezes as you click request on the autocrafting menu. 

**To Reproduce**
**edit** I choose the amount of items I want to craft and click next. game (server) freezes.
If I remove the EMC blocks from the storage bus. doing the same request and clicking next give me the start crafting page. One more thing I notice before it crash, there is a slider pop up in the top right corner that says (finished calculations)

**Expected behavior**
it should autocraft without crashing. 

**Additional context**
-I am unable to product a useful crashlog.  Watchdog just kills the server.
-here is the crashlog anyways.
[crash-2019-04-10_18.45.46-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/3066197/crash-2019-04-10_18.45.46-server.txt)

**Environment**
Windows 10
Java 8 U 201
I tried SP and MP
- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-6
- Forge Version: 14.23.5.2815

**Comment by yueh** [comment]
Looks like the usual issue of some EE variant exposing every known item, which results in a huge inventory. Combine that with how poorly Forge handles inventories and itemstacks and performance issues are guaranteed. Especially once we extract many itemstacks for crafting something.

This can most likely be solved once the mod uses a more sophisticated inventory. E.g. similar to StorageDrawers, which also offers a large inventory without much performance issues. If any.

**Comment by demethan** [comment]
You only expose certain items with that block.  about the same as a chest.

**Comment by jarquafelmu** [comment]
I have this problem as well. Where attaching storage interfaces to Compressed Refined Personal EMC Link causes AE2 to crash the server when a crafting operation is initiated. The only things that the user can see from the AE2 network is the items which are defined like demethan shows. 

Is the issue that AE2 still "sees" the entire EMC network regardless of what the player can see exposed? It would really be nice to have the ability to link a crafting AE2 network to the EMC system but right now that cannot be the case.

If it helps, I am providing additional data below.

### Logs:
https://drive.google.com/drive/folders/1d9ZfUnn427XJi6Q3tpGXFm_1pnjmjkNm?usp=sharing

### Save:
https://drive.google.com/open?id=1OTk-dHXTrurOgF2_N1ntOtyz75Xx7L6d

### Versions
**Minecraft:** 1.12.2
**Forge:** 14.23.5.2815
**FTB Sky Odyssey:** 1.0.0
**Applied Energistics 2:** rv6-stable-6
**ProjectE:** 1.12.2-PE1.4.0
**Project EX:** 1.1.0.14

**Comment by LatvianModder** [comment]
It's not the amount of item types, it's the item stack count. Like @demethan said, you can only have certain types exported, but each slot is as many items as you can take out in theory (maxes out at 2 billion). So it can be 10 cobblestone, or it could be 2000000000 cobblestone in one slot. If there is a better / AE specific way to implement custom external storage handler, let me know. Currently I just basically return an ItemStack with setCount(2143398493) or whatever
