### ISSUE TITLE
Autocrafting recipies not showing up in terminal, but they are in the interface terminal

### ISSUE THREAD

**Issue by loganipad** [AppliedEnergistics/Applied-Energistics-2#3995]
This happened to me randomly on my single player world. I have a normal me system, that is not very large, only has one me controller. I have been doing fine autocrafting stuff. I have been able to craft anything, and been able to use machines in it as well. The issue is just before I am posting this thread, I realized that I could not request anything in the terminal to be crafted. For example, I have a sticks auto craft recipe for my molecular assembler. But when I type in sticks into my crafting terminal, nothing shows up with the little white craft under the sticks logo, and yes, i know you have to have none of the item for that option to be available. I have an interface terminal and all of the encoded patterns are in there.

I do not know how to reproduce

I do not know the expected behavior

https://gyazo.com/f0505c4b123868272e997b782c5c7a88
https://gyazo.com/ee4aff174bc3ea6999b1d6d0b86ef8f7
https://gyazo.com/400c3dec68732f2abe6349cb6e72b046

I am playing on a direwolf20 modpack
- Minecraft Version: 1.7.10
- AE2 Version: rv2-stable-10
- Forge Version: 1.7.10

**Comment by mindforger** [comment]
but you do have attached that interface to an molecular assembler and a crafting cpu attached to your system?! 

and as a side note, drop at least one AE energy cell into your system alsways to make sure your buffer is big enough to not run out of power eventually (input is limited to buffer/tick)

make a few snapshots of the system itself to show how you configured it please

**Comment by Pingger** [comment]
Not a bug:
You changed your Crafting Terminal to "Show Stored only", which hides patterns. This is second from the Top Button on the left side of the Terminal. (The possible modes are "show everything", "show stored", "show craftable")

**Comment by mindforger** [comment]
... well yeah it was too obvious :P

**Comment by loganipad** [comment]
well...... thanks?? but thanks hahahha
