### ISSUE TITLE
Crashing when pick-blocking me cable facade

### ISSUE THREAD

**Issue by Testo0987** [AppliedEnergistics/Applied-Energistics-2#3996]
**Describe the bug**
My game crashes when middle clicking a certus quartz cable facade with an ME Pattern Interface

**To Reproduce**
Open world, create ME system with cable facade and pattern, and possibly see game crash.

**Expected behavior**
I expected it to give me a copy of the block.

**Additional context**
Pastebin: https://pastebin.com/kJe4mXGh

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-6
- Forge Version: Forge 1.12.2 2808

**Comment by yueh** [comment]
Cannot reproduce it with just AE. Neither by picking the facade, terminal, or cable will crash.

Maybe some other mod overrides the default pick block behaviour?

**Comment by Testo0987** [comment]
Most likely. I think it's mouse tweaks/inventory tweaks, but i will check today. Thanks for the info.

**Comment by KRYKOT** [comment]
Try to remove the one probe or hwyla

**Comment by ScorcherOfAwesomeness** [comment]
I replicated it without HWYLA or TOP. I have Better Hud

**Comment by mindforger** [comment]
aaaand how is it without BetterHUD ?

**Comment by ScorcherOfAwesomeness** [comment]
Have not checked yet. I'm currently away from home.

**Comment by ScorcherOfAwesomeness** [comment]
Wait, #4003 said removing TOP worked. I have its WAILA like functionality on. I think it tries to grab its item ID and fails.

**Comment by ScorcherOfAwesomeness** [comment]
Something is up with its ItemID. This is like the olden day IC "pickblocking cable gives broken cable" fiasco.
