### ISSUE TITLE
Spatial IO Missing vignette texture in 1.12.2?

### ISSUE THREAD

**Issue by Sora-Canstavia** [AppliedEnergistics/Applied-Energistics-2#3997]
#### Description
When going into a spatial IO Cell there is a missing texture (pink and black squares) that fills up the entire screen, goes transparent when I Disable HUD

#### Environment
Created spatial IO system, went inside the cell, unable to see anything inside of it.

- Minecraft Version: 
- AE2 Version: Appledenergistics2-rv6-stable-6
- Forge Version: Forge 14.23.5.2772 

I Apologize in advance if I Messed anything up or missed something on the form!

I Also have these two screenshots showing the issue:
![Screenshot_2](https://user-images.githubusercontent.com/28876886/56063647-c931a780-5d67-11e9-8f73-ce24c72ce117.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/28876886/56063648-c931a780-5d67-11e9-9b26-6c84ce66d3ec.jpg)

**Comment by yueh** [comment]
And with the default texture pack?

**Comment by Sora-Canstavia** [comment]
I Tested the default resource pack, and I Realised what exactly is happening. If I Make the spatial pylons to the same height as what my viewpoint is, my head gets stuck in the storage cells wall which is where the missing texture comes from, since the game is trying to overlay the blocks texture on my view.
