### ISSUE TITLE
Game crash with JEI and Facades

### ISSUE THREAD

**Issue by Mugiwaxar** [AppliedEnergistics/Applied-Energistics-2#3998]
**Describe the bug**
The game crash when I looking for facades on JEI

**To Reproduce**
Open inventory and JEI, tip facade

**Expected behavior**
Don't Crash

**Additional context**
It's appening since I added the galacticraft Addon: More-Planets

**Environment**
Multiplayer Server
ModPack: FTB Revelation + Galacticraft
Overworld

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-6
- Forge Version: forge-1.12.2-14.23.5.2823-universal

**Comment by mindforger** [comment]
please make a pastebin of the crashlog, without it is almost impossible to help you
