### ISSUE TITLE
Game breaking Crash

### ISSUE THREAD

**Issue by Roper6896Cz** [AppliedEnergistics/Applied-Energistics-2#3999]
I just put wireless Item tablet from ME to my boubles and it crashed
[crash-2019-04-14_16.13.39-client.txt]

 https://paste.dimdev.org/monamiguvu.mccrash
[crash-2019-04-14_16.13.39-client.txt]
(https://github.com/AppliedEnergistics/Applied-Energistics-2/files/3077474/crash-2019-04-14_16.13.39-client.txt)

**Environment**

 https://www.technicpack.net/modpack/lapitos-galacticraft.4030/updates

- Minecraft Version: 1.12.2

- AE2 Version: 1.0.6
- Forge Version: 14.23.5.2824

**Comment by Roper6896Cz** [comment]
And Btw Game breaking because i cant turn on the world rn

**Comment by mindforger** [comment]
please don't upload files (also the links are broken) use pastebin instead please next time :)
