### ISSUE TITLE
Mount cell

### ISSUE THREAD

**Issue by AlgorithmX2** [AppliedEnergistics/Applied-Energistics-2#40]
Mount cells are cells which you can attach on donkeys and mules to carry items, you would be able to store more items, but looking at the items and taking items out would require energy, just like the portable cell, To charge it, shift click on the donkey/mule to get the mount cell back and put it in the charger. You would only be able to see the items inside the cell when the cell is attached to a donkey or a mule. The mount cell would have 2048 bytes and would be able to store 4 times more than a portable cell, you would get the mounted cell by shapelessly combining 4 portable cells and an ME chest.

Originally Posted by Jappards

This issue was migrated; For original details see http://ae-mod.info/Tracker/0379/

**Comment by Deshiba** [comment]
A mule with a chest has 15 inventory slots and can hold as many portable cells, 7680 bytes worth of it. Creating and coding an item that decreases storage space over 3 times and has less utility for the sake of convenience in very specific situations seems undesireable.

It is a neat concept.
