### ISSUE TITLE
Separate settings and searches for different ME terminals and wireless terminals

### ISSUE THREAD

**Issue by Dimentive** [AppliedEnergistics/Applied-Energistics-2#4000]
I would like to have my main ME terminal in my home be set to “standard search,” my terminal in my garden be set to “standard search keep,” and my wireless terminal be set to “auto search keep.” However, whatever search mode you set any of your terminals to, whether it’s a wireless terminal or a stationary terminal, they are shared between terminals. It’s not possible to have one terminal with standard search and another terminal with auto search, for instance. I’m not sure whether this is a bug or intended.

Additionally, if you search for something in one terminal and go to a different terminal, it’ll appear in the search bar of that terminal as well (if it’s set to keep text in the search bar).

When it comes to wireless terminals, the search setting (such as “standard search” or “JEI synchronized auto keep”) **is** shared between other, stationary terminals, but what you searched for _isn’t_. So, for example, if you set your wireless terminal to “standard search keep” and search for “obsidian,” and then, you go to one of your stationary ME terminals, “obsidian” _won’t_ appear in that terminal, but it _will_ be set to standard search keep, regardless of its previous search setting.

I would like for terminals _not_ to share searches or search settings. I want my wireless terminal to be set to “auto search keep” for convenience, as that’s the most beneficial to me when I’m out building something, but, as previously mentioned, I want my main, stationary ME terminal in my house to be set to “standard search.” I also want the terminal in my Botania garden to be set to “standard search keep,” where I want to always have “@botania” in the search bar so that I only see items from Botania in this particular terminal (which you can’t do with a view cell). However, none of this works when all my terminals share searches and search settings.

If this could be changed so that terminals _don’t_ share searches and search settings—or a config option that changes it could beadded—it would be greatly appreciated and would make AE2 so much more convenient for me and probably many others as well.

**Comment by mindforger** [comment]
And then in multiplayer people start complaining the others

**Comment by Dimentive** [comment]
@mindforger I don’t understand what you mean. Currently, settings and searches are synchronized between terminals. That’s what I’m suggesting to be changed—or at least have a config option that can change it. I don’t see how others would be able to change the settings if this change were made. If anything, others can change the settings _now_, as it applies to all terminals (although I’m not sure if it works the same way in multiplayer as it does in singleplayer). Either way, I don’t see what your point is.

Besides, it would be a config option anyway, and it could be disabled by default. If you don’t want it on your server, just don’t enable it. For some people, like me, it would be incredibly useful, as it’s frustrating to have the searches and settings synchronize between terminals when I don’t want them to.

**Comment by yueh** [comment]
As @mindforger already said having settings for each terminal would require them to be stored serverside and shared between all players. So in case someone decides to use your botina terminal for something else, it will be gone. Same for other settings. E.g. using a terminal in parallel means both players will share the same search filter and constantly change it for the other one. Or sorting, etc.

Storing it clientside is afaik currently not possible. Or if every modpack update will overwrite you custom settings. As well as requiring you to configure every single terminal on your own. Did not realise you can synchronize it with JEI? Have fun going through 20 terminals and updating each one, and hope that you did not forget one. Probably the more annoying case.

Also for your botania case, there are view cells.

In case we have the time for a complete UI refactoring, it might be an idea to allow to be saved globally or per terminal type. But only if we can guarantee that some modpack author won't force you into either mode.

**Comment by Dimentive** [comment]
@yueh I understand. That’s all right. Thanks for explaining.

>Also for your botania case, there are view cells.

I mentioned the view cell, but unless I’m missing a certain option, it’s not possible to have a view cell filter by mod like you can by searching “@botania.”

**Comment by Dimentive** [comment]
@yueh I understand. That’s all right. Thanks for explaining. I didn’t quite understand what mindforger meant, as they didn’t explain it very well.

>Also for your botania case, there are view cells.

I mentioned the view cell, but unless I’m missing a certain option, it’s not possible to have a view cell filter by mod like you can by searching “@botania.”

**Comment by Dimentive** [comment]
@yueh I understand. That’s all right. Thanks for explaining. I didn’t quite understand what mindforger meant, as they didn’t explain it very well.

>Also for your botania case, there are view cells.

I mentioned the view cell, but unless I’m missing a certain option, it’s not possible to have a view cell filter by mod like you can by searching `@botania`.

**Comment by Pingger** [comment]
Afaik a fuzzy filter can do 'by mod' but I'm unsure about that. May have been an extraxells feature.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Dimentive** [comment]
It does? That’s nice. Thanks for letting me know!

I do have ExtraCells2 in the modpack I’m playing, if that is the mod that does it (but if I were to guess, I’d say it’s Applied Energistics 2).
