### ISSUE TITLE
Can’t check recipes and uses with JEI while auto-search is enabled

### ISSUE THREAD

**Issue by Dimentive** [AppliedEnergistics/Applied-Energistics-2#4001]
When any form of auto-search is enabled in a terminal, I can’t press `R` to check the recipe of an item or `U` to check the uses of an item in the terminal with [JEI](https://minecraft.curseforge.com/projects/jei), as it puts “r” or “u” in the search bar instead. I can with items in the JEI overlay but not items in my ME system.

Personally, this makes the auto-search feature unusuable for me. Could this be something that could be changed? That would be very helpful.

#### Versions

* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2781
* **Modpack:** [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2) (version [1.64](https://minecraft.curseforge.com/projects/enigmatica2/files/2697889), latest)
* **Applied Energistics 2:** [rv6-stable-6](https://minecraft.curseforge.com/projects/applied-energistics-2/files/2652453) (latest)

**Comment by yueh** [comment]
That is the basic idea behind auto(focus). To focus the search bar and a player does not have to keep moving their mouse away before they can search for something instead of accidentally open JEI or other mods.

**Comment by Dimentive** [comment]
To me, auto-search is useful because it lets me instantly search for something in a terminal without having to select the search bar every time, but not being able to use JEI to look up recipes or uses while auto-search is enabled prevents me from using it, as I do want to use those features in terminals.

An idea I have is to make it possible to press `R` and `U` (or whatever keys the recipe and usage buttons are bound to) even with auto-search enabled but only when you’re hovering over an item (that can be crafted or used in recipes, respectively). This way, you could still make use of auto-search when searching for something that begins with “r” or “u” as long as your cursor isn’t over an item. Or perhaps there could be a config option that would enable this behaviour? It would be very useful.

**Comment by mindforger** [comment]
It was annoying in the past when you could not search for something starting with letter r because some mod hijacked the key when hovering an item to let chests sparkle which contain the item under the cursor. Best bet would be to remap the key to ctrl+r and ctrl+u for your convenience. That is what i did with this search feature

**Comment by Dimentive** [comment]
That’s an [Extra Utilities 2](https://minecraft.curseforge.com/projects/extra-utilities) feature. I don’t want to remap the keys, but maybe there could be a config option to enable this behaviour for people who want it. Or maybe the keys could work with auto-search enabled as long as you’re holding Ctrl, without having to rebind the keys? That’s an idea.
