### ISSUE TITLE
energy usage on ranged wireless is inaccurate when not on default power configs

### ISSUE THREAD

**Issue by Saereth** [AppliedEnergistics/Applied-Energistics-2#4002]
**Describe the bug**

Our pack runs 10x power cost for AE (FTB Interactions) When checking the wireless transmitter it shows it uses 1k rf/t. The network tool properly shows it consumes 10k/tick.

**To Reproduce**

set ae power values to non standard values and check the wireless transmitter usage. 

**Expected behavior**

transmitter should show 10k usage as well

**Additional context**

no crash

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-6
- Forge Version: 2795

**Comment by Saereth** [comment]
originally reported here:
https://github.com/FTBTeam/FTB-Interactions/issues/327

**Comment by yueh** [comment]
Changing the costs will updating the wireless access point accordingly.

For example with 10x and 1x. With the usual rounding errors.
![10x](https://i.imgur.com/RjwzuHD.png)
![1x](https://i.imgur.com/cobt59O.png)

**Comment by Saereth** [comment]
@yueh 
Did you test this locally or on a server? any chance of desync invovled here?
I cant reproduce this in singleplayer either but I have verified it on our server. (FTB Interactions modpack). the only mod that does anything with AE in that pack is password's wireless terminal.

**Comment by Saereth** [comment]
![image](https://user-images.githubusercontent.com/9200909/56151481-500c9d00-5f7f-11e9-85d8-c02de619e4d5.png)
