### ISSUE TITLE
Crash with looking at cabel

### ISSUE THREAD

**Issue by KRYKOT** [AppliedEnergistics/Applied-Energistics-2#4003]
When I look at cabel, world crashes

![2019-04-16_21 37 58](https://user-images.githubusercontent.com/44555023/56239519-ab877980-60aa-11e9-8c63-aa4307b1dc12.png)
![2019-04-16_21 38 21](https://user-images.githubusercontent.com/44555023/56239525-ade9d380-60aa-11e9-8475-36d795bda5e7.png)
![2019-04-16_22-39-00](https://user-images.githubusercontent.com/44555023/56239550-bfcb7680-60aa-11e9-89cb-eeee303ab54b.png)
[latest.log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/3086639/latest.log)

- Minecraft Version: 1.12.2
- AE2 Version: rv6 stable build 6
- Forge Version: 14.23.5.2823

**Comment by yueh** [comment]
Duplicate of #3996

**Comment by KRYKOT** [comment]
I solved the problem. When Hwyla or The One Probe tries to get information of cabel - it's crashes. I just removed The One Probe and it's worked.
