### ISSUE TITLE
Pattern Encoder does not want to accept the output product

### ISSUE THREAD

**Issue by Zoulee** [AppliedEnergistics/Applied-Energistics-2#4006]
I have a problem with Pattern Encoder. I wanted to set a crafting logic processor, to automatic crafting. And i can't set output item (Logic Processor). Pattern Encoder accepts only 
usually craftings like Stone Furnace.

Sorry for my bad English ;)

i have Applied Energistics 2 Stuff

**Comment by yueh** [comment]
This block is provided by AE2stuff not AE2.
