### ISSUE TITLE
Full-block ME interfaces don’t show their status in Hwyla

### ISSUE THREAD

**Issue by Dimentive** [AppliedEnergistics/Applied-Energistics-2#4010]
#### Description of bug
The full-block ME interface doesn’t say whether it’s online or offline in [Hwyla’s](https://minecraft.curseforge.com/projects/hwyla) information box, but the slim ME interface block _does_. This may be an oversight rather than a bug since, I assume, the slim ME interface is a more recent addition compared to the original full-block ME interface, but I’m unsure. I haven’t tested if this also occurs with [The One Probe](https://minecraft.curseforge.com/projects/the-one-probe), a similar mod to Hwyla.

I assume that this a problem on AE2’s end since I think other mods usually have to incorporate their blocks into Hwyla and other mods like it rather than the other way around, but I could be wrong.

#### To reproduce
1. Create an ME interface with Applied Energistics 2 and Hwyla installed.
2. Place it down.
3. Witness that it doesn’t say “Device online” or “Device offline” in the Hwyla box.
4. Break it, convert it to a slim ME interface in a crafting grid.
5. Place it down.
6. Witness that it _does_ say “Device online” or “Device offline” in the Hwyla box.

#### Expected behaviour
The full-block ME interface should say whether it’s online or offline in Hwyla’s information box.

#### Additional context

**Environment**
![ME interface Hwyla](https://user-images.githubusercontent.com/34230933/56458548-8d5e9980-6388-11e9-8adf-4dcc64232167.png)

#### Versions

* **Modpack:** [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2) (version [1.65a](https://minecraft.curseforge.com/projects/enigmatica2/files/2700051), latest)
* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2781
* **Applied Energistics 2:** [rv6-stable-6](https://minecraft.curseforge.com/projects/applied-energistics-2/files/2652453) (latest)
* **[Hwyla](https://minecraft.curseforge.com/projects/hwyla):** [1.8.26-B41](https://minecraft.curseforge.com/projects/hwyla/files/2568751) (latest)

**Comment by yueh** [comment]
This is by design.

**Comment by Dimentive** [comment]
Ah, okay. Could you explain why? I’m just curious. It’s very useful to know when they’re online, so I don’t see why you can only see the status of the slim block.

**Comment by yueh** [comment]
Every part has an ingame status indicator, but this is missing for the block interface. For Hwyla/TOP and probably other similar stuff, the basic rule is that they cannot be mandatory. So they will never expose any information besides what is already visible with the block/part itself.
