### ISSUE TITLE
Server crash while placing 2nd Dense Energy Cell, forcing world to be restored from a backup.

### ISSUE THREAD

**Issue by JackRuby1** [AppliedEnergistics/Applied-Energistics-2#4012]
**Describe the bug**
Inside of a max sized compact machine setting up a quantum ring with an energy acceptor with a flux point on it, placed down 1 dense energy cell and when I went to place a second on top of the other, the server crashed and forced the world to be restored from a back up as forge entity fixer didn't help from config.

**To Reproduce**
Set it up like I have shown in the picture and try placing down 2 dense energy cells.

**Expected behavior**
Placing down the dense energy cells on top of each other to act as power storage and for me not to crash the server into a crash loop.

**Additional context**
https://pste.me/#/5JbL9
https://imgur.com/a/I0fBHhv my set up minus the dense energy cells, the go on the exposed side facing the player.

**Environment**
Inside of a max sized compact machine setting up a quantum ring with an energy acceptor with a flux point on it, placed down 1 dense energy cell and when I went to place a second on top of the other, the server crashed.
This is on the modpack SkyFactory 4

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-6.jar
- Forge Version: forge-14.23.5.2831

**Comment by yueh** [comment]
The usual sonarcore/flux network bugs.

**Comment by Gunner76th** [comment]
To prevent this crash, you need to blacklist AE energy cells as well as the energy acceptor in the Flux Network config. The config change is supplied below, copy it and replace what is in your current config in the blacklist section.

```
blacklists {
    # a blacklist for blocks which flux connections shouldn't connect to, use format 'modid:name'
    S:"Block Connection Blacklist" <
        actuallyadditions:block_phantom_energyface
	appliedenergistics2:energy_acceptor
	appliedenergistics2:dense_energy_cell
	appliedenergistics2:energy_cell 
     >

    # a blacklist for items which the Flux Controller shouldn't transfer to, use format 'modid:name'
    S:"Item Transfer Blacklist" <
	appliedenergistics2:energy_acceptor
	appliedenergistics2:dense_energy_cell
	appliedenergistics2:energy_cell 
     >
}
```

**Comment by Favo47** [comment]
how do you open the code in order to change it

**Comment by Gunner76th** [comment]
> how do you open the code in order to change it

You go to the configs folder, find the Applied Energistics config file and edit it there
