### ISSUE TITLE
P2P cabling issues

### ISSUE THREAD

**Issue by MilestoneMan52** [AppliedEnergistics/Applied-Energistics-2#4014]
Hello Everyone,

Im current learning to do the P2P networking within my AE network. However, ive ran into issues when setting up my P2P network, as it will not work.

https://gyazo.com/3144974f72c8129f017d8f15d14e659c

This first image shows the quantum link, which is connected to the rest of the machinery.
Ive used a P2P me interface on the controller, and used quartz cable to power it.

https://gyazo.com/a6153cb4f2ae67dc4fd046f7b8541695

This quantum link is then connected here, which is used to connect my P2P interfaces attached to the me interfaces.

When I connect both ends using the memory card, it will sometimes allow me to access the auto crafting recipe I want, but if I connect more than 3 at a time, it will stop working and will not show any crafting recipes. 

https://gyazo.com/0f972076f4f4a5d6cac36563e5d57421

As you can see on this screenshot, the link is created between the upper connection and this auto crafting area:

https://gyazo.com/ed7dc3cfce95db6a000d456314874844

This auto crafting area has the recipe of an anvil, but it does not show up in the system.

https://gyazo.com/1d05bbe0d6b3e75393ac33544c060fd2

Ive look all over to see if anyone else had the issue, but havent found anything.

Thankyou for reading!

**Comment by mindforger** [comment]
2 questions

What do you mean with
>but if I connect more than 3 at a time

P2P only connects 2 panel and require 1 channel per panel, there is no 1:n mode only 1:1 

Secondly i see more than 8 interfaces chained in the second picture but blocks can not link more than 8 channels and running blocks side by side with a dense cable can cause routing issues, either make groups of 8 and isolate 7 of of each group from the cable using anchors or redesign them to not touch each other

**Comment by Ommina** [comment]
I'm confused.  The documentation explicitly stated that tunnels are 1:n -- but that was also four years ago.  Have tunnels changed since then?

**Comment by mindforger** [comment]
nope, P2P were 1:1 Tunnels always and i am sure the description of the P2P states that since then

fel free to close the issue if you don't have any other questions

**Comment by MilestoneMan52** [comment]
> 2 questions
> 
> What do you mean with
> 
> > but if I connect more than 3 at a time
> 
> P2P only connects 2 panel and require 1 channel per panel, there is no 1:n mode only 1:1
> Completely wrong/yueh
> 
> Secondly i see more than 8 interfaces chained in the second picture but blocks can not link more than 8 channels and running blocks side by side with a dense cable can cause routing issues, either make groups of 8 and isolate 7 of of each group from the cable using anchors or redesign them to not touch each other

Thankyou for the reply.

Ill try to answer this:

>but if I connect more than 3 at a time

as best as I can as its hard to explain.

So, when im connecting my P2P ME interfaces, I can link a maximum of 3 to the main P2P (the one connected to the controller) before they stop working.

Here's what I did to get this issue:
1. Link the P2P interface on the controller to the interface that is circled in red in this screenshot.
https://gyazo.com/ed7dc3cfce95db6a000d456314874844
2. I then link the P2P interface on the controller to the interface that is now circled in this screenshot in blue.
https://gyazo.com/b8fd9c6b8afde784db8e32ced69fc87c

At this point, I can now see the crafting recipes from 1 and 2 on the network, as well as seeing that the connection to the network from the controllers is successful (right clicking the controller to check for the ME interfaces and the molecular assemblers).

3. Finally, I link the P2P interface on the controller to the third P2P interface circled in green.
https://gyazo.com/b61616ea43948d76766efc96e22fc737

However, when I link the third one, none of my crafting receipts show up in the terminal (including the ones from steps 1 and 2).
Whats even stranger is that when I check to see what things are connected to my controller, it shows that both 1, 2 and 3 are connected to the network, but are not displaying crafting recipes.

Ive also tried extending the dense cables so that each interface has its own dense cable in the row, like this:
https://gyazo.com/b3ec75bfbbc5d6f3bab0f7aefe28a4d0
Which shows that I have a full connection of 16 channels.
https://gyazo.com/fc65ce7ab6443bd4890395e7f2666f65

I hope this tries to explain my issue.

**Comment by mindforger** [comment]
>1, 2 and 3 are connected to the network

well the cables create a standalone network so showing them oonline is nothing strange, as there is "some" power present that has to deplete bfore they offline (or P2P busses still trasnfer power despite being illegally 1:n connected, i would have to try it out)

>Ive also tried extending the dense cables so that each interface has its own dense cable in the row, like this:

this is where i wanted to throw a basic warning (just as a measure of avoiding strange issues) as your machines behave like small cables, so you are basically running dense and normal cables parallel like a grid which may result in path finding issues or irregular behaviour when booting the system, you may avoid that but only chaining 8 interfaces in total and connect them via an cable on only one single machine of that cluster or avoid the blocks touching each other :)

this by far does not mean you will encounter issues, just a design advise

**Comment by yueh** [comment]
Every P2P tunnel is 1:n. IC2 are only special as they cannot support multiple tunnels in a single block.

Otherwise closing this now as this tracker is for bugs/features and not general build help.
Just keep in mind that everything in AE2 transfers 8 channels, exepct dense cables/P2P/QNB with 32 in total.

**Comment by mindforger** [comment]
>Every P2P tunnel is 1:n
are you sure about that?! 
i can remember even back to 1.7.x that you could not split up p2p me busses to allow for multiple outputs
