### ISSUE TITLE
Recipe errors in log for disabled items

### ISSUE THREAD

**Issue by MarkKoz** [AppliedEnergistics/Applied-Energistics-2#4015]
**Describe the bug**
Upon disabling items in the config, recipe errors appear in the logs such as 

```
Parsing error loading recipe appliedenergistics2:decorative/light_detector
com.google.gson.JsonSyntaxException: Unknown item 'appliedenergistics2:light_detector'
```

```
item was null for paint_ball ( paint_ball.brown )!
Parsing error loading recipe appliedenergistics2:tools/paintballs_brown
com.google.gson.JsonSyntaxException: Got a null item for paint_ball ( paint_ball.brown ). This should never happen!
```

However, this does not cause the game to crash or prevent it from completely loading; there are no apparent issues in-game. That being said, I am not sure what consequences such errors could have.

**To Reproduce**
Use [this](https://hastebin.com/aboliqediw.cfg) config.

**Expected behavior**
There shouldn't be any errors.

**Additional context**
The errors can be seen in the [full log](https://hastebin.com/ehayexovoq.txt).

**Environment**
Happens on both MP and SP. I have tested with AE2 being the only mod installed on a fresh instance. 

Here is some info I took from a recent, unrelated crash log:

```
-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 8.1 (amd64) version 6.3
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Launched Version: MultiMC5
  LWJGL: 2.9.4
  OpenGL: GeForce GTX 980 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 417.35, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Current Language: English (United Kingdom)
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
```

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-6
- Forge Version: 14.23.5.2836

**Comment by yueh** [comment]
Basically we cannot provide a recipe for every single config permutation. If you choose to change the defaults, you pretty much have to provide your own recipe alternatives without the disabled items.

**Comment by MarkKoz** [comment]
> Basically we cannot provide a recipe for every single config permutation. 

Why would a recipe need to be provided if it is disabled? Any recipes which depend on a disabled items should also get disabled.
