### ISSUE TITLE
Firewalls for item, pattern and CPU network connections

### ISSUE THREAD

**Issue by Peilonrayz** [AppliedEnergistics/Applied-Energistics-2#4016]
I'm new to AE2, so maybe this is possible but I've not found much about this. And given #802 I think this currently isn't possible.

Currently it looks like there are only two ways to make a connection between two networks:

 - Import bus, Export bus and a chest.
 - Storage bus/Interface connection.

These only pass items.

---

I want to make a 'CPU network', 'crafting network', 'host network', etc. These networks are designed to work at max capacity over one cable (512/1024 channels) and perform one task.

The 512 controller is simple. Create a 1x1x4 controller. Have 16 P2P ME multiblocks on all the 1x4 faces, all connected to one of the two 1x1 faces. This cable can then take the P2Ps to their destination using up all 32 channels (16 source, 16 destination). The other 1x1 face can have the connection to another network(s).

This is currently possible to implement in AE2 and works with continuous crafting, but doesn't allow JIT crafting. Ultimately nerfing JIT crafting. To show this you setup a two-way Storage Bus/Interface connection and use Export Buses to continuously move the items from the external network into the internal one to craft the resource. The interface on the output of the crafting block allows items to go into the internal network and get sucked up into the storage on the external network.

---

This would have a couple of in-game benefits:

 - Reduce complexity of the central ME controller - as it would literally be split up.
 - Allows modular expansions to the network.

Some ways these connection could be implemented in Minecraft:

 - Allow a P2P ME on two controllers to connect them. (allows all both ways)
 - Add more cards that could be added to Storage Bus/Interface connection to allow Patterns and CPUs to pass-through.
    This would allow one-way and two-way configurations. However items will always be accessible.
 - Add a Firewall multi-block that works the same way as Storage Bus/Interface does. But allows the user to chose what is passed through, like the above solution using Storage Bus/Interface and cards. But would allow the user to disable items from passing into or out of the network.
    To allow one-way transfer you could use a Firewall/Interface, where Firewall/Firewall could allow two-way transfer.
    Alternately you could do the same as Storage Bus/Interface and require two of these connections for two-way connections.

**Comment by yueh** [comment]
Thanks for the suggestion, but the current behaviour is simply our intentional game design.
