### ISSUE TITLE
AE2 Autocrafting and Industrialcraft2

### ISSUE THREAD

**Issue by Joly0** [AppliedEnergistics/Applied-Energistics-2#4020]
**Describe the bug**
Well, i cant Autocraft many things in Industrialcraft 2, because things like Re-Batteries, Energy Crystals and others, arent used correctly by the following Crafting recipes.

**To Reproduce**
Place Energy Crystal in Pattern Terminal, surround it with Lapis and 2 Advanced Circuits and make a Pattern, then try to Craft the Lapotron Crystal, this Recipe should make, gets stuck, cause cant take Energy Crystal. 
Works same for Generator/Re-Battery etc.
Enabling Oredict doesnt work or help, checked multiple times.
Also using Empty, stacked, Full and other variations of the Items in the Patterns doesnt work.

**Expected behavior**
Autocraft a Lapotron Crystal should result in a crafted Lapotron Crystal.

**Additional context**

**Environment**
Using FTB Ultimate Reloaded as Modpack, Latest Version of both Mods, as far as i can see.

- Minecraft Version: 1.12.2
- AE2 Version: 
- Forge Version:

**Comment by bookerthegeek** [comment]
This is a known issue with IC2 and there damage values. It also needs to be reported to the mod pack or to ic2 and not here.

**Comment by Joly0** [comment]
It is not a Issue with Ic2. The same Problem appears for the Magical Crops Infusion Stone and the EE2/EE3 Philosophers Stone and many other Items, with a Durability or a kind of Energy.

Thermal Expansion found the solution to that Problem for their pipe System: Add a Button to Ignore NBT and Metadata, and that works, with every Mod i tested. So its still an AE2 Issue, nothing else
