### ISSUE TITLE
Cables change texture when changing mipmap levels

### ISSUE THREAD

**Issue by CvoidWyvern** [AppliedEnergistics/Applied-Energistics-2#4021]
When loading a world with cables they're initially the correct texture/color, but when changing mipmap levels they use the wrong texture. This stays the same when reloading textures and even when quitting out of a world and entering again. With a higher mipmap than 1 this can start using non cable textures. Only the specific types of cables placed will be retextured, colors and types that haven't been used yet when changing mipmap levels will not be changed.

Appears to be the same error as #3754, but without Optifine.

https://imgur.com/a/aBGcnLk

Tested on SP
Modlist: https://paste.dimdev.org/gitacuyici.css

- Minecraft Version: 1.12.2
- AE2 Version: rv6 6
- Forge Version: tested on 14.23.5.2811 and 14.23.5.2836

**Comment by mindforger** [comment]
I currently suspect an issue with foamfix but wont yet call it out bugged yet, can you test again without it please?

**Comment by CvoidWyvern** [comment]
Just tested and nope, still happens without Foamfix.

**Comment by mindforger** [comment]
thank you

**Comment by MonoToast** [comment]
it, not just ae2 cables I have the same issue with mipmap on with other cables from other mods so it's not just an ae2 thing

**Comment by Carnaxus** [comment]
Remove NotEnoughIDs, start a new flat world, place some cables, change mipmaps.  No risk to the world you've been busting your ass on, and allows testing without NEIDs

**Comment by CvoidWyvern** [comment]
Well I've found this also happens for me with JustEnoughIDs, although that doesn't say much. Can't really test this pack without either of those because yeah, well above the itemid limit already kinda need those.
