### ISSUE TITLE
I need help with crafttweaker

### ISSUE THREAD

**Issue by TAmeET** [AppliedEnergistics/Applied-Energistics-2#4022]
I create the modpack for minecraft version 1.7.10. Using crafttweaker i write the following script:
**import mods.appliedenergistics2.Grinder;**
But in the game it tell me the following message:
**No such member: appliedenergistics2 .**
What's wrong? I want to create the grinder recipe, but nothing works, because this error disables the script.

- Minecraft Version: 1.7.10
- AE2 Version: rv2-stable-10
- Forge Version: 10.13.4.1614

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.12 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.

**Comment by mindforger** [comment]
you may require the addon modtweaker to do this
