### ISSUE TITLE
Restored Quantum Bridge from Spatial IO doesn't work properly

### ISSUE THREAD

**Issue by lanterrt** [AppliedEnergistics/Applied-Energistics-2#4023]
After recovering the area including Quantum Bridge, it doesn't work properly.

**Describe the bug**

Restored Quantum Bridge from the spatial cell doesn't connect to any others

**To Reproduce**

Make a Quantum Bridge, and make it work with the other. Store the space, and recover
it from the cell, then it doesn't work. I have checked it through the attached terminal.

Of course, removing the singularity doesn't help.

**Expected behavior**

It should work with the other.

**Additional context**

**Environment**

I have installed the server including the same versions.

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-6.jar
- Forge Version: forge-1.12.2-14.23.5.2768-universal.jar

**Comment by yueh** [comment]
Cannot reproduce. Please take into account that after moving they still might need to be powered sufficiently before reconnecting themselves.
