### ISSUE TITLE
[Question] How do i autocraft with fluids with the new integrated fluid storage?

### ISSUE THREAD

**Issue by ReiDaTecnologia** [AppliedEnergistics/Applied-Energistics-2#4024]
Idk if it's possible to autocraft without using the ExtraCells method (ME Fluid Assembler) but i googled about it and i didn't found nothing so i came here to ask.

Sorry if it's not allowed to do "Small" question or questions at all :/

**Comment by yueh** [comment]
There is no autocrafting support for fluids (currently)
