### ISSUE TITLE
ME Interfaces does not connect to a channel at specific locations.

### ISSUE THREAD

**Issue by shitstainlord** [AppliedEnergistics/Applied-Energistics-2#4025]
**Describe the bug**
ME Interfaces does not connect to a channel at specific locations. I have tried pulling the channels from different connections and later on tore down the entire network and rebuilt it, the issue stays the same. It refuses to connect to interfaces at certain locations. I managed to pinpoint at what location it stops connecting. You can see it in the screenshots. Also, all the me system is chunkloaded and everything else is working as it should

**To Reproduce**
Was not able to reproduce it on a test server.

**Expected behavior**
It should connect to a channel like any other interfaces should

**Additional context**
![2019-05-03_15 34 27](https://user-images.githubusercontent.com/50236595/57137858-bbe16900-6db9-11e9-8eaa-9d754d5b5280.png)
![2019-05-03_15 35 26](https://user-images.githubusercontent.com/50236595/57137861-c00d8680-6db9-11e9-966b-efecffa18c57.png)
![2019-05-03_15 35 40](https://user-images.githubusercontent.com/50236595/57137866-c1d74a00-6db9-11e9-9597-67e162a4e58d.png)
![2019-05-03_15 35 52](https://user-images.githubusercontent.com/50236595/57137868-c3a10d80-6db9-11e9-95f8-be88befd323e.png)

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: rv6 stable-6
- Forge Version: 14.23.5.2781

**Comment by yueh** [comment]
[Channels](https://ae-mod.info/Channels/)
