### ISSUE TITLE
Storage bus "report inaccessible items" bug

### ISSUE THREAD

**Issue by orblazer** [AppliedEnergistics/Applied-Energistics-2#4026]
**Describe the bug**

When configure `report inaccessible items` to `Yes` that have no effect, the item is hide when this is remove from ME.

**To Reproduce**

1. place `storage bus` on the chest
2. configure `report inaccessible items` to `Yes`
3. (optional) configure the `partition storage`

**Expected behavior**

The items is always visible in ME even if the item is no longer present.
This need look like barrel/drawer locked, show item with 0 amount.

**Additional context**

The storage bus :
![Storage bus](https://user-images.githubusercontent.com/1344792/57142122-154a9780-6dbc-11e9-9bad-0f13d5a66a07.png)

The me with item :
![me with item](https://user-images.githubusercontent.com/1344792/57142144-1ed3ff80-6dbc-11e9-9d82-1e77722bbd21.png)

The me without item :
![me without item](https://user-images.githubusercontent.com/1344792/57142198-41feaf00-6dbc-11e9-91c1-2b20033b6cbd.png)

**Environment**

- Mod pack : Sky Factory 4 - 4.0.3
- Play on Multiplayer

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-6
- Forge Version: 14.23.5.2831

**Comment by yueh** [comment]
It states pretty clearly that it shows not extractable items and not non-existing ones.
