### ISSUE TITLE
Spatial IO Query

### ISSUE THREAD

**Issue by MilestoneMan52** [AppliedEnergistics/Applied-Energistics-2#4027]
Hello, 

So ive been trying to set up a 128 cubed spatial io multiblock. I built the multiblock and connected it using channels and quantum bridges, but cannot get it to work. I press the button, and the machine does not do anything when I press it.

Heres some screenshots to show what ive done:

https://gyazo.com/a9e804238d9077dd82eb8f099190e143
This is my 128x129x131 spatial io multiblock,

https://gyazo.com/4311bb70fe94a7931387ae65c6da4efa
I connected the first side using p2p interfaces and channeling the cables to each spatial pylon rows. I connected these to quantum bridges, which connect to my network.

https://gyazo.com/7b1ce117ffa4affeb7f5a758b86704f3
I did the same on the opposite side, to power and give each one channels.

https://gyazo.com/4d82b4a15947dd479d14015b47ac64e1
Bottom row connections.

https://gyazo.com/af93cd56067d24bcae7f6419ecbc08d5
The controller is also color coded, which each color corresponds to each color on the cables connected to the pylons.
The tall 4 quantum bridges at the top are connected to the bottom pylons for reference.

https://gyazo.com/6235ae3eaa609d2c86b3bd2ee1b5e6ca
Then I have energy cells connected to the spatial pylon, providing the power needed. Also, the front quantum bridge on the network is connected to the spatial io port shown in the picture.

https://gyazo.com/d9b20dbde2f24aaecc24f9f22be3fc37
Shows that im getting power and that the system is also detecting all my pylons (from the power needed)

https://gyazo.com/1c2e41059313a68f397edc28a2dc3ddb
Shows all of my pylons being on the network.

Also, this is not a power issue. Ive read up on some posts on the internet with people saying it could be power issues, but I do have enough power to run it. Also, I made sure that the config was sorted, so that it is white listed.

Thankyou for reading :)

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.12 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
