### ISSUE TITLE
Me system go offline when i pull anything

### ISSUE THREAD

**Issue by Salah2Eddin** [AppliedEnergistics/Applied-Energistics-2#4028]
So , Simply i was using my Me System normally , all of sudden it started going offline whenever i try to pull or put anything with left click ( 1 stack ) , i assumed that there is a power problem so i just tried right clicking (half a stack) and it worked normally , after few mins it now dont make me pull any thing , if i try to do so it goes offline , and iam sure its not a power problem, because i tried using creative power cell and still the same  ,no security terminals since its SP , and the really weird thing is that there is a chain of interfaces for autocrafting , whenever i remove them the system work pretty normally, but as i mentioned there is no power problems .

**Expected behavior**
The Normal Thing

**Environment**
Channels turned off from config
SP

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-6
- Forge Version: 14.23.5.2781

**Comment by Salah2Eddin** [comment]
Nvm , figured it out .
Sorry for bothering you.

**Comment by mindforger** [comment]
Care to share your solution?

**Comment by Salah2Eddin** [comment]
Just add a Power Cell ( AppliedEnergistics one)  , for some sort of causes
, the problem might be that i was using more power than i was supplying ,
so the power cell will just charge while idle , and if u do something , it
will just use its power , thats how i fixed it .

‫في الاثنين، 6 مايو 2019 في 5:25 ص تمت كتابة ما يلي بواسطة ‪mindforger‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by mindforger** [comment]
Kind of what i guessed ;D

Your issue is NOT supply, but capacity

I5 can only accept as much RF/tick as it has capacity
