### ISSUE TITLE
Applied Energistics 2

### ISSUE THREAD

**Issue by Rainbowstar93** [AppliedEnergistics/Applied-Energistics-2#4029]
I am not sure where to ask this question, so i thought i would try here. Does anyone know if there is going to be a Wireless Crafting Terminal for Sky Factory 4?

**Comment by yueh** [comment]
No idea, ask them?

**Comment by Tahakk** [comment]
And ask on [Discord](https://discordapp.com/invite/darkosto), not on Git

**Comment by Rainbowstar93** [comment]
Sorry. Wasnt sure where to ask. Thank you.
