### ISSUE TITLE
[bug?] Constant energy draw

### ISSUE THREAD

**Issue by Felthry** [AppliedEnergistics/Applied-Energistics-2#403]
I've a very simple ME network set up, just one drive and an access terminal, with an energy acceptor connected to a leadstone energy cell (from Thermal Expansion). This network draws as much power as I allow it to, even the maximum of 80 RF/t (which would be 40 AE/t, far more than required).  Additionally, this power is drawn regardless of whether the energy cell is receiving the redstone signal it's set to output on or not; this is probably a bug with TE, not AE2, but it may be relevant.

The network does not have any AE energy cells connected, though it seems to act as if it does; after removing power, the devices continue to function for a short time.  The website suggests that the energy acceptor functions also as a storage device, but is not very clear on this, and doesn't list a capacity either. If this is the case, I would suggest adding information on it to the website, as it's currently just confusing.

**Comment by Pimhazeveld** [comment]
I got the same bug in direwolf 20 1.7.2 i had a bigreactor with 4 power taps to eachother with leadstone energy cell and a energy acceptor and then a battery i tried breaking all the blocks to maybe reload them but nothing worked. after placing an enderio storage it wont fill from the reactor nor from the lead cell but i tried with a SAG mill and that thing will fill from it help?

**Comment by Cisien** [comment]
I don't understand what you are trying to describe, and how it relates to ae2. Can you clarify the ae2 piece of the issue?

**Comment by Pimhazeveld** [comment]
the point is that an energy acceptor does not work when only attached to a thermal cell and that a enderio battery wont charge from thermal cells while the sag mill Does

**Comment by yueh** [comment]
Then report it to EnderIO, ThermalExpansion or whatever else mod? Why to us?
