### ISSUE TITLE
Can't break all of the crafting block in our world

### ISSUE THREAD

**Issue by chouuul** [AppliedEnergistics/Applied-Energistics-2#4030]
Hello, i'm new on gitHub because i need your help ! When i place a crafting block
crafting co processing unit
crafting storage 1k
crafting storage 4k
crafting storage 16k
crafting storage 64k

i can't break them. disapear and replace... i didn't know what mod do this bug :(

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-6.jar
- Forge Version: 1.12.2 - 14.23.5.2768

**Comment by chouuul** [comment]
EDIT : it's normal in all others dimensions...

**Comment by mindforger** [comment]
mh ... just for record, you can place new blocks but not remove them?
or is it that you can just not replace any blocks in a specific area? 

(it kind of doubt it will help, but please edit the server.config in your server folder and set spawn protection to 0 for testing :) )

**Comment by chouuul** [comment]
My problem is only in the overworld. i can place new blocks but not remove them and only this list of block :
crafting co processing unit
crafting storage 1k
crafting storage 4k
crafting storage 16k
crafting storage 64k

Do you have an idea ? Do you need something ?

**Comment by yueh** [comment]
As this is limited to a single dimension, it's most likely some protection mod interfering with it. But AE2 itself does not care about this at all.
