### ISSUE TITLE
Dimensions error?

### ISSUE THREAD

**Issue by JimekitoYT** [AppliedEnergistics/Applied-Energistics-2#4032]
As I saw that there were complaints to other users for copying the crash report directly here, I uploaded it to pastebin: https://pastebin.com/eSNPJLed

**Comment by JimekitoYT** [comment]
PD: If someone tells me to modify something, tell me how it is done, I do not have much idea of the subject

**Comment by Ommina** [comment]
The dimension dimension requested by AE2 (for spatial IO) is already in use by another mod.  Go into the config and change the dimension ID from 2 to... something else.

At least this particular issue will go away with newer Minecraft versions.
