### ISSUE TITLE
Final Inscriber in my autocrafting system refuses to make Engineering Processors

### ISSUE THREAD

**Issue by TheWallsPlayer** [AppliedEnergistics/Applied-Energistics-2#4033]
#### Description
Version: "appliedenergistics2-rv6-stable-6.jar". There isn't a command in game for me to check. :/

Bug: My AutoInscriber setup works perfectly for creating Logic and Calculation Processors, but will not make Engineering Processors. It should make them the same way the others do.

#### Environment
Overworld. Power is coming directly from ME Controllers in the same room, which have an ME Interface, ME Security Terminal, ME Drive, ME Crafting Terminal, and a crafting CPU made of two 64k Crafting Storage blocks, Monitor, and Co-Processing Unit. Also attached to these ME Controllers is an autocrafting machine.

This is on my Sevtech Ages modpack server, pack version 3.1.1.

Here's a video showing the issue. I've since removed the two ME Interfaces you see in this video as they are not necessary in the setup. https://youtu.be/lOPHnBWsleo

Here's also a video from which this setup is based. His setup is nearly identical to mine and works just fine: https://www.youtube.com/watch?v=yke-rFCOUyo&feature=youtu.be

I've tried powering different ME cables in the setup, but it didn't fix the problem. Swapping the Calculation and Engineering Inscribers and their respective busses didn't fix it. Making new Encoded Patterns didn't work, either. Another person on the Sevtech Ages Discord tried the exact same setup and his didn't work either. Honestly dumbfounded at this point.

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-6
- Forge Version: 14.23.5.2815

**Comment by TheWallsPlayer** [comment]
Okay, sorry for wasting your time. I just fixed the problem by making a new Engineering Processor Encoded Pattern and replaced the old one with it. Keep in mind that the two patterns are _identical in everyway_ and were both crafted the exact same way. I also did this exact same thing earlier today in an attempt to fix the problem and it DID NOT work, however, now it DOES.

I think something should be done about Encoded Patterns being bugged like this, because there isn't a way to tell when it happens besides the fact that you can no longer craft the item. In more complicated autocrafting/inscribing setups, it might be even harder to pinpoint the source of the issue. I spent all day trying to fix this because I was under the assumption that what I did to fix the problem wouldn't work because it _didn't work_ the first time.

**Comment by TheWallsPlayer** [comment]
Can anyone explain how this happens before closing?

**Comment by yueh** [comment]
Basically a couple of modpacks decide it is nice to add some mods to randomly break patterns. No idea about Sevtech, but currently I simply assume they do.

Otherwise it's usually some mod attaching caps or data to random items, which for our purpose means these are totally different items. As some mods decide to use the exact same approach to actually implement different items we have to handle it this way.
