### ISSUE TITLE
Missing ME Controller (Question)

### ISSUE THREAD

**Issue by zandercodes** [AppliedEnergistics/Applied-Energistics-2#4035]
- Minecraft Version: 1.12.2
- AE2 Version: rv6.stable build 6
- Forge Version: 14.23.5.2837

I have a question:
Has the ME controller been removed?
Or has it been reduced to the Dense Cable?

Best regards
ZanderCodes

**Comment by Ommina** [comment]
If you have channels disabled, the controller will not appear.  Otherwise, no.

**Comment by zandercodes** [comment]
Thank you I had missed in the Config
