### ISSUE TITLE
Crash wireless terminal

### ISSUE THREAD

**Issue by bigenergy** [AppliedEnergistics/Applied-Energistics-2#4036]
- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-6
- Forge Version: 2836

https://hastebin.com/ezibalefic.rb

**Comment by yueh** [comment]
We cannot support custom builds of AE2.

**Comment by bigenergy** [comment]
Lol, this is not custom build.

**Comment by bigenergy** [comment]
@yueh

**Comment by yueh** [comment]
AE2 releases are signed, missing it indicates a custom build or at least modified jar contents. What I cannot say, but I simply cannot rule out that it behaves differently and thus not reproduce it. On top of not supporting bukkit or similar things either.

And just in case, no renaming the jar will not break it.

**Comment by bigenergy** [comment]
I can repeat the same crash in your original version.
In my version the classes mentioned in the report were not affected.
Bukkit is not suitable here.

**Comment by mindforger** [comment]
Then please provide a crash report with the unmodified version
