### ISSUE TITLE
NullPointerException in TileEnergyCell.injectAEPower causing server crash

### ISSUE THREAD

**Issue by mcsoapthgr8** [AppliedEnergistics/Applied-Energistics-2#4037]
NullPointerException in TileEnergyCell.injectAEPower is crashing server

Gist with stacktrace: https://gist.github.com/mcsoapthgr8/052e0c800b9561cd4b8ffd2ee4f2cebe

SkyFactory4 (v4.0.5) modpack

- Minecraft Version: 1.12.2
- AE2 Version: stable rv6-stable-6
- Forge Version: 14.23.5.2768

**Comment by yueh** [comment]
Flux networks bug.
