### ISSUE TITLE
Crash wireless terminal

### ISSUE THREAD

**Issue by bigenergy** [AppliedEnergistics/Applied-Energistics-2#4040]
- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-6
- Forge Version: 2836

https://hastebin.com/ezibalefic.rb

**WARNING! This is not custom build AE2!**

**Comment by bigenergy** [comment]
@yueh Cool feedback. Close the issue without comment, are you normal?

**Comment by Tahakk** [comment]
Cool story, use template next time. +they don't have to give you explanation.

**Comment by mindforger** [comment]
to be more precise, he spammed 3 issues for similar crash reports, which is also not nice
