### ISSUE TITLE
Storage Bus connected to "Real Filing Cabinet" causes crippling server lag, but TPS is fine.

### ISSUE THREAD

**Issue by Goof245** [AppliedEnergistics/Applied-Energistics-2#4042]
**Describe the bug**

When storing items in a filing cabinet, attaching a storage bus to the cabinet results in unplayable hitching / lag. This is avoided by moving the exact same items into another deep storage block like a crate or shipping container.
Crates and shipping containers from the "Barrels, Drums, Storage & More" mod do not have this issue, despite exposing many more items to the storage bus than the filing cabinets.

**To Reproduce**

* Create an ME network
* Create a filing cabinet
* Fill the filing cabinet with several thousand items, in at least 2-3 different folders
* Attach a storage bus to expose the items to the ME network
* Observe server TPS is still >20
* "Enjoy" getting constant "Moved too fast" errors in the server console, missed attacks, slow machine guis, most everything that's normally expected when TPS is chugging

**Expected behavior**

To be able to play the game normally

**Additional context**

Issue on the Real Filing Cabinet github:
https://github.com/bafomdad/realfilingcabinet/issues/79

I apologise for posting screenshots instead of actual text, but I'm not sure where, if anywhere these are available to copy from...
Most intensive calls when the problem is happening:
![Screenshot (270)](https://user-images.githubusercontent.com/3851003/57828982-d15e8600-77f0-11e9-9ac8-eea9b7750e53.png)

Laggoggles info when the problem is happening:
![2019-05-16_14 51 54](https://user-images.githubusercontent.com/3851003/57829002-e63b1980-77f0-11e9-9426-4578d71d4a02.png)

Laggoggles info from a healthy server, all items moved out of filing cabinet into a shipping container:
![2019-05-16_15 05 49](https://user-images.githubusercontent.com/3851003/57829042-04087e80-77f1-11e9-9207-6681ac2b13f4.png)

**Environment**

Modpack is Skyfactory 4, v 4.0.5
Real Filing Cabinet v 0.1.84
Barrels, Drums, Storage & More v 0.0.22
- Minecraft Version: 1.12.2
- AE2 Version: rv6 stable 6
- Forge Version: 14.23.5.2831

**Comment by yueh** [comment]
They might be able to improve it on their side to some degree, but there isn't much left for us to improve.
It is basically what forge considers acceptable performance when handling items. Fine when just using Vanilla and Forge, but a massive issue once it hits the extreme ranges of modded.
