### ISSUE TITLE
I have a question I am trying to make an addon mod for AE2 channels and storage that would increase the channel size to 256 and the storage size to 32768, 65536, 131072, and 262144

### ISSUE THREAD

**Issue by xxxjahlilallenxxx** [AppliedEnergistics/Applied-Energistics-2#4043]
**Describe the feature**

**Reasons why it should be considered**

**Additional Context**

**Comment by xxxjahlilallenxxx** [comment]
more expansion for the base mod itself so that its less ingenuity on the players roll when it comes to storage in minecraft

**Comment by Tahakk** [comment]
it is nice that you have a question, but I cannot see it anywhere

**Comment by xxxjahlilallenxxx** [comment]
Im sorry which file is the one that manipulates the channels for the cables and which file is the file that manipulates the number of bytes for the storage cells?

**Comment by yueh** [comment]
The assumption are used all over the code. Pretty much an integral part of it.
It might sound harsh, but finding them yourself should be the least difficult part.
