### ISSUE TITLE
AE2 Cache Performance issue

### ISSUE THREAD

**Issue by Shybella** [AppliedEnergistics/Applied-Energistics-2#4044]
**Describe the bug**

Version: appliedenergistics2-rv6-stable-6
Modpack: FTBUltimate Reloaded 1.6.0

I have a visualvm nps report for my issue. I have disabled things such as cache from config without a change in performance for debugging purposes. I have not been able to retrieve more info on what's causing this and need assistant in debugging further. 

**To Reproduce**

I do not have steps for reproduction, but, I am spending time trying to find the cause of the performance hit in-game. 
**Expected behavior**

**Additional context**

NPS Report
https://drive.google.com/open?id=1CmahQ2GQjSS_3zB8ET2IZZsj4ZKK9w2o
**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-6
- Forge Version: 2815

Thank you all for the hard work.

**Comment by yueh** [comment]
We do not support anything like Sponge or Bukkit officially. Only a standard forge environment.

Should you be able to reproduce it without it, please update the issue accordingly and we will reopen it.
