### ISSUE TITLE
Channel is not making up it mind...

### ISSUE THREAD

**Issue by PlayOnly** [AppliedEnergistics/Applied-Energistics-2#4050]
**1st**
<a href="https://ibb.co/RHRjhsR"><img src="https://i.ibb.co/Th9WK79/2019-05-25-15-54-05.png" alt="2019-05-25-15-54-05" border="0" /></a>

8 furnace, each one of them only need 1 charcoal.
So 8 Bus Storage, 8 lvl emitter (emit redstone when below 1), 8 toggle bus (cut off line)
1 import bus will pull item from bag (charcoal)
So, 8 Str bus + 8 lvl emitter + 1 import bus = 17 items in one channel
**But it works!**

**2nd**
<a href="https://ibb.co/NZV5rfp"><img src="https://i.ibb.co/SRsbcH0/2019-05-25-15-54-14.png" alt="2019-05-25-15-54-14" border="0" /></a>

4 Furnace, each one of them can only cook 8 items at a time.
So 4 Storage bus, 4 lvl emitter, 4 toggle bus
1 Import bus to pull item from chest
So, 4 Str bus + 4 lvl emitter + 1 import bus = 9 items in one channel
**Doesn't work**
if normal toggle = storage bus offline
if inverted = storage bus missing channel
Ay so now it following the channel rule ei...

I can solve the problem just by having each furnace (channel) have their own import bus or 2 furnace 1 import bus... But I have OCD to minimise resource use as possible... Sorry..

Its not a game bug... but its really bugs me... why the **1st** one work but not the **2nd**?

Tag#BurningQuestion

- Minecraft Version:  1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-6
- Forge Version: 23.5.28.15

**Comment by yueh** [comment]
No idea, but I also cannot actually make out the build from this particular angles.

Further this is not really the best place for build help. Please limit it to actual bug reports or similar.
