### ISSUE TITLE
Thaumcraft aspects not visible in AE2 computers

### ISSUE THREAD

**Issue by TearsOfLA** [AppliedEnergistics/Applied-Energistics-2#4051]
Thaumcraft aspects are not visible when items are stored within the computer system. they are visible everywhere else.

#### Description
ModPack: FTB Revalation
Thaumcraft 6.1Beta
AE2: rv6-stable-6

#### Environment
This post on the thuamcraft github shows the issue very well
#https://github.com/Azanor/thaumcraft-beta/issues/1244

- Minecraft Version: 1.12.2

**Comment by Dr-Turtle** [comment]
The [Arcane Crafting Terminal](https://ftbwiki.org/Arcane_Crafting_Terminal) from Thaumic Energistics shows the aspects. Another workaround is simply to press the recipe keybind from JEI and hover over the item there.

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.15 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
