### ISSUE TITLE
Crash - ME Glass Cable

### ISSUE THREAD

**Issue by rehv** [AppliedEnergistics/Applied-Energistics-2#4054]
**Describe the bug**

_I initially thought this was an issue with the facade, but have since discovered the problem was the cable_
I used a ME Glass Cable - White, and the client crashed while hovering the cable.

I removed one of the affected mods and changed my pointer OUT of the cable, put the mod again and crashed **only** when hovering the pointer over the cable.

I've tested the following:
-ONLY hwyla = no crash
-ONLY hwyla + wawla = no crash
-ONLY betterhud = no crash
-ONLY betterhud + hwyla = **crash**
-betterhud + hwyla + wawla = **crash**

Tested with quite a number of ME Glass Cables (White, Gray, Red), so far they all bugged on me.

**To Reproduce**

Place a ME Glass Cable anywhere in the world
Hover the mouse over it

**Expected behavior**

Block info about the ME Glass Cable ?

**Additional context**

[Crash Log - betterhud + hwyla](https://pastebin.com/XDBsssUM)
[Crash Log - betterhud + hwyla + wawla](https://pastebin.com/YHFttN55)
Other crash logs with the same mods and error if it helps:
[Crash 1](https://pastebin.com/GPVGSLfb)
[Crash 2](https://pastebin.com/P6RhCUk5)
[Crash 3](https://pastebin.com/6Bdyg6ki)

**Environment**

_removed info about server since I've narrowed it down - testing done in SP_

Betterhud had the block viewer disabled.

Mods version:
![image](https://user-images.githubusercontent.com/1697639/58629152-00293180-82b2-11e9-96b5-7afaa10729fb.png)

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-6.jar
- Forge Version: forge-1.12.2-14.23.5.2768-universal.jar

**Comment by rehv** [comment]
Update comment: betterhud author suggestion worked for another mod: Slayer5934/ChocoCraft3SLY#32

**Comment by yueh** [comment]
With betterhud present, they will inject some NBT when hywla tries to render it's overlay. Normally this is not present and from a quick look, this particular tag appears to break vanilla code. Why? No idea, but we cannot fix things other mods break.
