### ISSUE TITLE
Feature Request cell workbench that would allow for name /mod filter 

### ISSUE THREAD

**Issue by MonoToast** [AppliedEnergistics/Applied-Energistics-2#4055]
now I have read other feature request ask about this and everyone says that this can't be done because of a language barrier here is a solution to this 

1. ask for a string for the search if it does not contain a @ then refer to 2a. if it does contain @ ask if a mod search can be done, not sure which mod adds this ability if it is built into ae2 or jei, if a mod search cant be done, refer to 2a if it can be done refer to 2b

2a. this would search for the string client side in the system as if you where in a terminal, this would only find current items in the system for performance reasons, but don't show the result ,sound like that be hard to do since you would have to rework the interface on the cell workbench to get to work but that would be cool if it could be done, saving all the item it found that are in the system as there item ids' to array.

2b. not 100% sure how this is handled so first if it possible to add just the mod id tag in full to the view cell then do that if not possible then saving all the item it found that are in the system and apart of the mod that is specified as there item ids' to array.

3. now 1 of 3 things would happen after hitting done

A. if less then or equal to 63 add all item ids' in the array to the cell

B. if greater then or equal to 64 then ask to refine search or to click the overflow button the button if pushed would copy 63 item ids' to the cell then remove the copied ids' from the array. inserting another cell and click the button again or adding it automatically depending on what the mod dev wants would add the next set of 63 remove the 63 from the array rinse and repeat till there less the 63 adding the remaining amount of items to cell optionally if they are view cells you could limit the number of items to 252  because that is how much can be held in the 4 view cells the amount that could be held in a terminal now, of course, you could warn them instead of outright banning it, so if there is a mod extension that adds more than 4 view cell slots or something else I missed it would not be an issue

C. if there is less then or equal to x amount of letters then request that there be more the x amount of letter once again for performance reasons. x = to amount of letter would be minimum 

now of coures, this would be a little tricky to implement but if you don't want people to get different thing when they open the terminal this is a solution to the issues being it could be the solution to make a better way to specify what you want to see in a terminal. simply instead of handling server-side handle it client side till ids' are established then transfer over to server side making it so language at that point would not differ the search result for different people.

sorry for the long-winded explanation thanks for the consideration for this feature and I hope to see this in the game at some point

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-6
- Forge Version: 14.23.5.2825

**Comment by yueh** [comment]
This does not solve the actual issues at all. And filter by mod missing from buses&co is still intentional.

**Comment by MonoToast** [comment]
Ok then what is the issue
