### ISSUE TITLE
Fluid Annihilation Plane Not working

### ISSUE THREAD

**Issue by AwesomeSyd239** [AppliedEnergistics/Applied-Energistics-2#4056]
**Describe the bug**
I set up a very simple network trying to automatically put water from the world into an ME system. I am attempting to use a Fluid Annihilation Plane for this. Screenshot of system: https://i.imgur.com/krE0QAj.png (the export bus is configured to water, the storage cell has space, the system has energy)
The system was fine to import/export fluids in the tank, but the annihilation plane refuses to work.

**To Reproduce**
Connect ME Drive to Fluid Interface and a power source.
Stick a Fluid Storage Cell into the ME Drive.
Connect Fluid Interface and ME Drive to Fluid Annihilation Plane.
Connect ME Drive to a fluid tank with a Fluid Export/Storage bus.
Place Water in front of Fluid Annihilation Plane.

**Expected behavior**
I expect the plane to take the water source, and stick it somewhere into the network. This is how regular Annihilation plane works with blocks.

**Attempted workaround**
 I gave it a lot of options for where to put the fluid, but it apparently doesn't like any of them.

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-6
- Forge Version:14.23.5.2831
Tank used is from Mekanism. This tank works with import/export buses while talking to the drive/cells, so is probably not the issue. Everything else is from applied energistics.
Modpack is SkyFactory 4, but that should hopefully not affect the behavior of this small isolated system.

**Comment by yueh** [comment]
You cannot grab water from a flowing water block. That is basic vanilla behaviour similar to buckets.

**Comment by AwesomeSyd239** [comment]
That is a source block. A vanilla bucket picks it up just fine.

**Comment by kiljacken** [comment]
I'm having this same problem.
