### ISSUE TITLE
About Custom Recipes

### ISSUE THREAD

**Issue by rehv** [AppliedEnergistics/Applied-Energistics-2#4057]
Hi, how exactly do Custom Recipes work now? It isn't the same as described in https://ae-mod.info/Custom-Recipes/ (due to #3232), and there's no new tutorial (I've checked every changelog on curseforge since RV2 and tried some google results). I'm trying to redo some custom recipes I had in 1.7.10 (~AE2 RV2).

I've checked the AE2 jar and one grinder recipe is:

```
{
	"type": "appliedenergistics2:grinder",
	"input": {
		"type": "forge:ore_dict",
		"ore": "crystalFluix"
	},
	"result": {
		"primary": {
			"part": "material.fluix_dust"
		}
	},
	"turns": 8
}
```

so if I wanna add it to my dedicated server, do I edit CustomRecipes.cfg and put it there, or is there anything else? Thanks in adv.

#### Environment

This is intended for MP/dedicated server use.

- Minecraft Version: 1.12.2
- AE2 Version:  rv6
- Forge Version: 1.12.2 2768

**Comment by yueh** [comment]
Basically we moved to the recipe system provided by forge since 1.12 or so. Forge just didn't bother to add a way to allow players/modpack authors to actually change them. Hopefully 1.14 will change it.
