### ISSUE TITLE
Freeze a minute and don't craft when auto crafting

### ISSUE THREAD

**Issue by bunchamino** [AppliedEnergistics/Applied-Energistics-2#4059]
**Describe the bug**

I set a simple auto-craft dense energy > energy accepter > ME drive > cable > 1k craft > Co-crafting>Assemble > ME interface in a line
I click crafting after I add a number on GUI auto-craft then click "next" button my client freeze 1-2 minute. It not show next step to select CPU. I can't right click on another GUI
**To Reproduce**

**Expected behavior**

**Additional context**

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-6.jar
- Forge Version:1.12.2-forge1.12.2-14.23.5.2831

**Comment by mindforger** [comment]
A picture tells more than a thousand explanations. But seriously, if the order of blocks is correct, the design sounds broken

Also what are you trying to craft and a modlist or forced crashlog

**Comment by bunchamino** [comment]
I know a problem. I think because I connect ME export bus to over item storage. this case I connect with filing cabinet (real filing cabinet mod) it can store more than 2.4 brillion item when I break cable or remove ME export bus from system I can auto craft normally.

thank for respond.

**Comment by mindforger** [comment]
you can hit the "close" button beside the comment button yourself as author of an issue when the issue is done

just as a hint :)
