### ISSUE TITLE
Crashing Client

### ISSUE THREAD

**Issue by WujcioKarol** [AppliedEnergistics/Applied-Energistics-2#4061]
**Describe the bug**
Crashing client after trying to destroy disappired cables
**To Reproduce**
just go to me system and try to break disappired cables
**Expected behavior**
idk

**Additional context**
https://pastebin.com/eXReKeNc
**Environment**

- Minecraft Version: 1.12
- AE2 Version: appliedenergistics2-rv6-stable-6
- Forge Version: 1.12.2-forge1.12.2-14.23.5.2838

**Comment by yueh** [comment]
This is a matter overdrive crash.
