### ISSUE TITLE
Storage fill stand

### ISSUE THREAD

**Issue by angelusnoctis** [AppliedEnergistics/Applied-Energistics-2#4063]
A way to see how much storage is currently free/occupied would be useful

Some sort of terminal telling you "You are currently using X out of Y Bytes and X out of Y Types" instead of having to manually go to each ME drive, and hover over every single storage disc to get an idea if i am running out of space or if i have enough space left.

Sorry if it had been suggested before but after an hour of googling i´m fairly certain it hasnt

**Comment by yueh** [comment]
This is not really possible due to how cells work internally.

Also the value of it would be pretty much useless for any indication about free space.
Even the still somewhat imprecise cell leds are many times better for a quick information about the global state.
