### ISSUE TITLE
FTB Ultimate reloaded: No quartz seeds recipe?!

### ISSUE THREAD

**Issue by VasalisErretti** [AppliedEnergistics/Applied-Energistics-2#4065]
#### Description
So I've been playing this mod pack for a while and finally got some progress in AE2, the problem as stated above, when I checked the wiki for AE2 you are apparently supposed to be able to craft quartz seeds using quartz dust and sand to help automate your progress. Problem being when I search for it in the item list neither seeds exist. This makes it have the same problem as AE1 which is that to make any kind of progress is a grind fest for the quartz. I really hope this is a bug/something they forgot to do, and that it gets fixed right away, cause I already spend too much time grinding for quartz and it is a massive time sink to just look for them manually. Everything else works fine (I assume). Most amount of progress I have in the mod currently is an ME drive with a 64k storage disk. I then had checked the wiki to try to remember what else I needed to make for a working ME system then realized that I should have been doing the seeds thing the whole time, but when I checked they weren't in the search bar even after searching with an at. For now will work without it but since I know it's a thing that I don't have now I really want it to save time.

Edit: I checked creative mode, and while the seeds do show up there, they do not seem to be craftable for some reason. I tried every type of orientation for the quartz dust and sand and nothing worked, tried in different benches (inventory, crafting bench, project table, workbench) none worked
#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-6
- Forge Version: 14.23.5.2836

**Comment by Ommina** [comment]
This is not really an AE2 issue, as it does not represent a bug in the AE2 code.  Instead, this is something you would need to take up with the pack designers, as it would be they that are disabling the seeds.

That said, it seems to me that the goal of the "Ultimate Reloaded" pack is to recreate, as closely as possible, the original FTB Ultimate.  So if, as claimed, it becomes a lot like AE1, then the change is almost certainly intentional.  That's the whole point of the pack.

**Comment by VasalisErretti** [comment]
ok, I was going to put it on the FTB reddit but saw there was a rule to inform the mod creators first if it is a bug, so my bad. Kind of sucks that it's this way though, will either have to figure out how to enable it to craft or might just creative them in potentially. Cause while I do enjoy ME system, my biggest gripe back in the day (played old FTB 4 years ago before this) was the fact you couldn't farm or create certus quarts. I was glad when I saw the growable option and a bit mad that it's disabled.
