### ISSUE TITLE
A method to move items based on modid

### ISSUE THREAD

**Issue by Grimlock257** [AppliedEnergistics/Applied-Energistics-2#4066]
**Describe the feature**
A method to move items from a ME Drive / Individual storage cells to another based on modid. I guess this could be an extension of the ME IO Port via a new upgrade card or a fancy export bus,

**Reasons why it should be considered**
The mod already allows configurable cells views, extraction of items and upgrades of various items such as export buses or interface by upgrade cards. Since extracting/moving by modid essentially is an export bus with all mod items configured in it, the upgrade card or new block/part would be somewhat expensive to produce and probably power hungry to balance the upgrade out.

***Balancing Suggestions***
Perhaps in order to perform the operation, it could be implemented in such a way in which some resource is consumed in the process, or maybe the resource to be consumed will only handle so many bytes of the transfer before being fully consumed.

**Comment by mindforger** [comment]
hmmm ... i would have to test it myself, which i can not do until weekend, but isn't there a mode in the cell workbench for this?!

**Comment by yueh** [comment]
This was already rejected.
