### ISSUE TITLE
XNet will not connect to the ME Controller or Energy Acceptor.

### ISSUE THREAD

**Issue by VT-14** [AppliedEnergistics/Applied-Energistics-2#4074]
**Describe the bug**
#3483 was closed due to not following the template.  This was also previously reported to XNet here: McJtyMods/XNet#311, so I'll add more to that issue as well.

The XNet Connectors do not connect to the ME Controller or Energy Acceptor.  They should connect in order to transfer Forge Energy and power the ME Network.

XNet will connect and power the ME Chest, Inscriber, and Charger directly, but those will not share power with the rest of the network.

**To Reproduce**
Place an XNet Connector next to an ME Controller or Energy Acceptor.

**Expected behavior**
To be able to power AE2 using XNet cabling (without resorting to some kind of intermediary power cable).

**Additional context**
![2019-06-24_13 32 04](https://user-images.githubusercontent.com/12564251/60039552-fc0bec00-9684-11e9-87fd-fa6d0f38c97e.png)

Manual Debug Crashlog: https://gist.github.com/VT-14/cbc54a085459dfbc76dd1291fa326f2f
Forge Log: https://gist.github.com/VT-14/f132b49600f2fb6f4b18b1f8730ae7b3

**Environment**
Single Player, in a minimal test modpack (only AE2, XNet, RFTools, JEI, and McJtyLib).

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-6
- Forge Version: 14.23.5.2838
- XNet: 1.8.1

**Comment by yueh** [comment]
All energy accepting tiles use the exact same code, if XNet can connect to some, it should be able to connect to all. The only difference is that inscribers and chargers have a limited set of exposed sides. Yet chest, acceptor and controller are the same and it can connect to a chest.

**Comment by VT-14** [comment]
On XNet's issue McJty responded with "Not much I can do on my side. The AE2 controller has to properly support the energy capability for side null (on the client and server)"

I suspect that XNet is connecting to those 3 specific blocks because they have inventories.

**Comment by yueh** [comment]
No idea, but not supporting `null` as valid side is intentional.
