### ISSUE TITLE
Getting Server crash...

### ISSUE THREAD

**Issue by crashies1** [AppliedEnergistics/Applied-Energistics-2#4075]
https://gyazo.com/0391fb459a6f980ccc9085d479f3eb07
#### Description
After running my server for 30second I get this error and they right after it crashes.
I have newest version and everything but doesnt work rip.

- Minecraft Version: 
- AE2 Version: appliedenergistics2-rv6-stable-6
- Forge Version:  forge-1.12.2-14.23.5.2768

**Comment by Ommina** [comment]
And is a server already running on that port?

I feel that the actual log would be significantly more useful than a screenshot of a stack trace, as I'm quite suspicious that your problem relates to AE2 not at all.
