### ISSUE TITLE
AE2/The Betweenlands/JEI - client crashes when placing "Life Crystal" recipe from JEI into Crafting Terminal

### ISSUE THREAD

**Issue by katubug** [AppliedEnergistics/Applied-Energistics-2#4076]
**Describe the bug**
A player reported that she was being disconnected from the server when attempting to auto-fill a recipe from JEI into the crafting terminal. The recipe in question involves a drained Life Crystal and a number of Wight Hearts from The Betweenlands. I can replicate this crash reliably.

**To Reproduce**
- Used _/give Katubug thebetweenlands:life_crystal 1 99_ to give myself a drained Life Crystal. Also obtained a stack of Wight Hearts from creative tab.
- Opened AE2 Crafting Terminal.
- Searched "Life Crystal" in JEI and clicked on the filled Life Crystal Item.
- Pressed the [+] on the second recipe to input the items automatically into the crafting grid.

**Expected behavior**
I expected the crafting grid to fill with the Life Crystal and a number of Wight Hearts. This is the behavior that happens when using a vanilla or Tinker's crafting grid. The crash seems to occur only with the AE2 Crafting Grid or with the Wireless Crafting Terminal crafting grid.

**Additional context**
Here is my crashlog: https://paste.dimdev.org/ecixiyoduh.mccrash

**Environment**
This is on a multiplayer server and has happened in multiple ME systems. It does not seem to matter whether the items are in the player's inventory or in the ME system itself.

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-6
- Forge Version: forge-1.12.2-14.23.5.2838-universal

Let me know if you need any more information!

**Comment by katubug** [comment]
Just wanted to add that this also occurs with Note Blocks, as reported by two of my players. I will attempt to get a crash report for that.

**Comment by yueh** [comment]
This is due to some recipe using null as valid ingredient. Technically JEI does allow it, but vanilla itself is no longer using it itself, so I would consider it a design flaw either with this particular mod or JEI overlooked this part.

Basically it is not worth to safeguard against something vanilla does not even allow for recipes anymore.
