### ISSUE TITLE
Level emitter with crafting card not emitting redstone signal to craft item 

### ISSUE THREAD

**Issue by Hexakosioihexekontahexa** [AppliedEnergistics/Applied-Energistics-2#4078]
#### Trivia
While playing Divine Journey modpack tried to automate alchemy mechanic from Blood Magic via combination of level emitters, where one was triggered by the quantity of items, activating the second one (with crafting card installed), which should control the autocrafting process.

#### Description
So, the problem is that level emitter with crafting card installed does not work in "Emit redstone signal to craft item" mode.
We have a simple system, with storage, autocrafting part (interface, assemblers and CPUs) and emitters:
![2019-06-30_13 33 23](https://user-images.githubusercontent.com/48926983/60395463-87312a00-9b3c-11e9-86a9-10eea156422d.png)
I am using a combination of level emitters
![2019-06-30_13 33 35_2](https://user-images.githubusercontent.com/48926983/60395750-e7c26600-9b40-11e9-9d0b-28b50db857b7.png)
where:
1. The first one works as quantity controller:
![2019-06-30_13 34 07](https://user-images.githubusercontent.com/48926983/60395509-4c7bc180-9b3d-11e9-92c1-813b35e9b946.png)
It also controls ME Toggle Bus, which activates...
2. The second level emitter:
![2019-06-30_13 34 15](https://user-images.githubusercontent.com/48926983/60395526-85b43180-9b3d-11e9-9c23-acc0c5489518.png)
This one is supposed to be an autocrafting controller. It has a crafting card installed and should control autocrafting process. Also, searching here (on github) for possible solution found that in case a crafting card is installed into level emitter, [the emitter should be configured with the pattern, and not the output item](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/816#issuecomment-72324611), so I did so:
![2019-06-30_13 34 26](https://user-images.githubusercontent.com/48926983/60395600-987b3600-9b3e-11e9-9b5c-14f938822fef.png)

Despite the system has all necessary recipes and resources (see images below), the second level emitter does not seem to work, as it does not emit a redstone signal. Moreover, it does not emit when attached directly (without toggle bus).
![2019-06-30_13 33 44](https://user-images.githubusercontent.com/48926983/60395640-2ce59880-9b3f-11e9-9341-1ed55429a791.png)
![2019-06-30_13 33 56](https://user-images.githubusercontent.com/48926983/60395641-2ce59880-9b3f-11e9-954b-71c9f0af4890.png)

Also noticed that it's possible to "turn it on" by selecting emitting mode to "Emit when levels are above..." and install crafting card after that. It will emit redstone signal, but autocrafting won't start.

#### Environment
Playing on Windows 10, Java 8 update 181 (build 1.8.0_181-b13)
Reproduces both in SP/MP.
ExtraCells, AE2 Wireless Crafting Terminal, Thaumic Energistics are installed in the modpack, but aren't used in setup, only vanilla AE2

- Minecraft Version: 1.7.10
- AE2 Version: rv3-beta-6
- Forge Version: 10.13.4.1614

**Comment by yueh** [comment]
The emitter will emit a redstone signal to craft an item using something responding to the signal.

**Comment by Hexakosioihexekontahexa** [comment]
@yueh, what do you mean under "something responding"? I've placed a vanilla redstone lamp next to the 2nd emitter and it is still not working:
![2019-06-30_15 21 33](https://user-images.githubusercontent.com/48926983/60396490-eac25400-9b4a-11e9-846d-e2e24ffcb4ff.png)
