### ISSUE TITLE
Frequency

### ISSUE THREAD

**Issue by SmileaffO** [AppliedEnergistics/Applied-Energistics-2#4079]
Frequency is not given to p2p tunnels in my world. In others that work,
![2019-06-30_16 15 12](https://user-images.githubusercontent.com/52374053/60395806-6542a200-9b52-11e9-9480-6f7ab871ee30.png)

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-6
- Forge Version:14.23.5.2836

**Comment by yueh** [comment]
Holding something in the offhand can interfere with the memory card.
