### ISSUE TITLE
Mod Filter

### ISSUE THREAD

**Issue by shadowfacts** [AppliedEnergistics/Applied-Energistics-2#408]
Add a way for view cells to be configured to display (or not display) all blocks and items from a certain. Possible an option could be added to the cell workbench for when a view cell is in the propper slot to switch between manual mode and mod filter. If the workbench is in mod filter mode display a text field for the player to enter the Mod ID instead of having slots for items/blocks.

This would be great for people who have different areas of their bases devoted to different mods. They could have an ME Terminal in each section configured to only show items from the mod they're working on.

**Comment by Silwing** [comment]
Looking very much forward to this being added :) and I could use mod filter for storage busses in my build.
