### ISSUE TITLE
Unknown Incompatibility with other mod

### ISSUE THREAD

**Issue by Hailfire32211** [AppliedEnergistics/Applied-Energistics-2#4080]
Game starts to load and... then it crashes with the error "net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Energistics 2"

Have no idea. The only way to stop the bug is to remove AE2 and so I have no idea how to reproduce it.

Well, I expected the game to actually load and to play.

Crash report: https://pastebin.com/YZh4VkGc

Decently big modpack, designed to be a mix between Tech and Military, designed for Multiplayer but the crash occurs before the game even loads.

- Minecraft Version: 1.12.2
- AE2 Version: r6-stable-6
- Forge Version: 14.23.5.2838

**Comment by Ommina** [comment]
Caused by: java.lang.IllegalArgumentException: Failed to register dimension for id 2, One is already registered

Choose a different dimension ID in your config.

**Comment by Hailfire32211** [comment]
where would I do that? Not very specific, have to remember not everybody on the internet will know exactly what you are talking about.

**Comment by Pingger** [comment]
In the mod config of ae2. And to be honest, if you don't know what that is and you can't read it, then you should no be composing modpacks...
And AE2 is following the Forge Standard! This makes it very easy.

.minecraft/config/AppliedEnergistics2/AppliedEnergistics2.cfg
Search for `I:storageDimensionID=` and change the value to something different (e.g. `4711`)

**Comment by Hailfire32211** [comment]
when you say "config" I think of the Config menu in the game, not editing some files in the game that Ive only really messed with to make sure my friends had the same exact settings. But hey, I guess there is Elitism in modpack making as well.
