### ISSUE TITLE
Redstone Blocking for Interface Crafting

### ISSUE THREAD

**Issue by Famous5000** [AppliedEnergistics/Applied-Energistics-2#4081]
**Describe the feature**
The feature would do exactly as it says on the tin: Either block the interface while it's receiving a redstone signal, or block it until it receives a pulse.

**Reasons why it should be considered**
It would help auto-crafters determine when the sequence is complete rather than adding an additional "stopper" item for the system. It could also be tracked a bit better in the crafting monitor of the crafting CPU.

**Additional Context**
Take a look at how "Refined Storage" does the redstone blocking for the crafter block; that should put it in a more simple way as to how it should be implemented.

**Comment by yueh** [comment]
Might be an idea, but it would be a binary option. So it would not possible to block each side differently to still be able to split multiple task across all attached machines and in case of part interfaces, it will block every one.

Ideally Forge would provide a common way to detect a busy machine, which many mods could use to improve their behaviour, but being able to provide a better user experience is pretty much the reason to not be added to Forge.

Probably also needs some balancing considerations. E.g. an interface only has a single upgrade slot and redstone behaviour would require a redstone card. Thus users had to decide between a redstone or crafting card, which would actually be better in terms of other parts or blocks and needing to compromise on their upgrades. Adding more slots would also require more card options. E.g. unlock the config slot in a similar way to buses (each capacity cards would unlock 4 slots) and then limit it to 3 upgrades overall.

**Comment by Famous5000** [comment]
Formatting alert: I'm on mobile. 

Yeah, that's basically what I was hoping for. The Redstone behavior could be used with the Redstone card on the interface, could be used on the 5-sided blocks or the 1-sided interface modules that are attachable to the cables. I appreciate that you're considering this feature already, so I'll let you do what you want to with this feature; the only ones that I really want for the Redstone blocking is just using Redstone to control activity, or using the Redstone pulse mode.

**Comment by yueh** [comment]
I already thought about it as the normal blocking mode gets more and more broken without any sane alternative available.

But it's really the edge cases which might be interesting. Like how it deals during loading chunks, chunks behind unloaded and the redstone signal temporarily is flipped around and so on.
Also there is really no way currently to indicate that it is blocking (regardless of the normal one or some other approach). That's one reason there isn't something like a AE2 specific cap, as every other mod would have to support it and no player would know, if it is supported or not.

Following the normal buses with on on low or high signal would probably work and should both be supported. Not sure if pulse mode is an option. I currently cannot remember how interfaces deal with being unable to push the full pattern ingredients into an adjacent machine. At some point it will happen, I just cannot remember, if the interfaces are buffering it (would allow pulse) or the crafting cpu (pulse pretty much impossibe)

So probably the following settings:
* Ignore/Always unblocked
* Blocking on low
* Blocking on high
* Block until next pulse

**Comment by Famous5000** [comment]
That works quite well actually (the settings), that would be so much better than nothing at this point.

**Comment by Technici4n** [comment]
With the changes to blocking mode in 1.18 to make it work with modern tech mods, this is not needed anymore.
