### ISSUE TITLE
More then three outputs in the processing patterns

### ISSUE THREAD

**Issue by crashniels** [AppliedEnergistics/Applied-Energistics-2#4082]
Hello. I noticed that there are "only" three outputs in the processing patterns. Some mods like GregTech require more then the 3 in the processing patterns. Would it be possible to change it from three outputs to maybe six or more? Thank you. 
![gregtecg](https://user-images.githubusercontent.com/39709384/60607139-fddc5a80-9dbc-11e9-99ba-1c9b29fb70ea.png)

**Comment by yueh** [comment]
3 is a pretty sensible amount. More are usually chance based, which won't work at all. And if in doubt, the outputs could always be split across multiple patterns.
