### ISSUE TITLE
minMeteoriteDistance has no effect, meteorites cluster up/spawn together.

### ISSUE THREAD

**Issue by sustained** [AppliedEnergistics/Applied-Energistics-2#4083]
# Description

Meteorites are spawning in clusters, despite `I:minMeteoriteDistance=707`.

This seems to only be happening in Biomes O'Plenty biomes but I can't be sure without more testing.

# Reproduction

Well this is a custom/in-development modpack based fairly heavily on FTB Ultimate Reloaded. If you really need I can supply configs and such... I am messing around with CoFH custom World generation a lot so perhaps that is interfering and as mentioned BOP is included and it mostly happens in BOP biomes (needs more testing to verify).

# Expected

That `minMeteoriteDistance` is respected.

# Additional context

## Screenshots

![2019-07-03_17 51 01](https://user-images.githubusercontent.com/5995080/60610212-3b3fe880-9dbb-11e9-898b-047aca71859b.png)

![2019-07-03_17 50 13](https://user-images.githubusercontent.com/5995080/60610219-3da24280-9dbb-11e9-9ecd-92be5e57f37f.png)

![2019-07-03_17 47 41](https://user-images.githubusercontent.com/5995080/60610222-3f6c0600-9dbb-11e9-9751-dac26a81531f.png)

## Other

- No Crashes.
- Nothing relevant in logs as far as I can tell.

# Environment

- Minecraft Version: 1.12.2
- AE2 Version: rv6.stable build 6
- Forge Version: 14.23.5.2838

**Comment by Pingger** [comment]
This looks somewhat like parallel generated chunks. Does BoP generate multiple chunks in parallel?
Normal minecraft does not generate multiple chunks in parallel, only one at a time.

**Comment by sustained** [comment]
I haven't a clue and I can't find any information about it online.

Could this also be the case/be relevant:

```
[18:08:53] [Server thread/WARN] [FML]: Astral Sorcery loaded a new chunk [-2, -2] in dimension 0 (overworld) while populating chunk [-3, -2], causing cascading worldgen lag.
[18:08:53] [Server thread/WARN] [FML]: CoFH World loaded a new chunk [-2, 14] in dimension 0 (overworld) while populating chunk [-2, 13], causing cascading worldgen lag.
```

**Comment by Pingger** [comment]
This might be the cause. But usually cascading world generation still handles one chunk after the other, so the locations of the meteorite drops should be remembered and respected ... 

But guess we need to wait for a maintainer to be sure.

I also didn't find anything related to parallel chunk generation for BoP ...

**Comment by yueh** [comment]
Clusters are a feature.

**Comment by sustained** [comment]
I see. Can we disable or configure said feature?

Also, in that case your minimum meteorite distance configuration variable is useless/irrelevant and should be removed.

**Comment by Ommina** [comment]
meteoriteClusterChance=0.0

Five lines above _minMeteoriteDistance_

**Comment by sustained** [comment]
Ha, my bad... thank you. Sorry, it's been a long day/it's late. Time for bed, probably.
