### ISSUE TITLE
extract priority fluid storage

### ISSUE THREAD

**Issue by Gammelkebab** [AppliedEnergistics/Applied-Energistics-2#4085]
So far as i understand it priorities are used for two things: 
Deciding where to store something and
 deciding, which recipe to use. 

What i want is to have the contents of one Storage bus to be used up completely before ones with lower priority are even scratched.

For example i have two sources A and B for water and one consumer. both storage buses are set to extract only. Currently setting A to 1 prio and B to 0 seems to be doing nothing at all, while it should lead to B being unused as long as A is not empty.

**Comment by yueh** [comment]
Extract is reversed to automatically cleanup an actively used system over time.
