### ISSUE TITLE
game crash with applied energistics 2 and mekanism

### ISSUE THREAD

**Issue by BoganC** [AppliedEnergistics/Applied-Energistics-2#4086]
When trying to enter the world you are sent to a error page stating that the game crashed and it may be because of Applied Energistics 2 or Mekanism

**Describe the bug**

something happened in the game and I got a error screen that said the game crashed and Applied Energistics 2 or Mekanism caused an error i tried to reboot the game and make a copied file to see if it was transferred, it seems when the game is loading and enters the world it immediately says the is shutting down then it goes to the error screen this might be because it enters the world then realizes there is something wrong with it and then it stops the game

**To Reproduce**

I don't really know how I did this glitch/bug but what I do know is what I did before the game crashed, i had placed down a inscriber down beside a power cable and then went to go and get the materials needed to make a circuit board of some kind which i looked up how to make in the JEI menu, i then went up and grabbed the materials form a vanilla chest and went to the inscriber where my game crashed.

**Expected behavior**

I expected it not to crash my game and just let me use minecraft like normal and not block me out of the world

**Additional context**

![image](https://user-images.githubusercontent.com/52521013/60682494-bf907b00-9e50-11e9-8681-37fe1a9227e0.png)

The following link is the crash report form the button that says "Get Link"
https://paste.dimdev.org/ipawaforot.mccrash

![image](https://user-images.githubusercontent.com/52521013/60682512-c8814c80-9e50-11e9-95b1-a4f09719d8a9.png)

the top world is the original world and the bottom one is a file copy of it

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-6
- Forge Version: 14.23.5.2838

**Comment by yueh** [comment]
Not AE2 related.

**Comment by BoganC** [comment]
any idea what it might be about?

**Comment by Ommina** [comment]
See https://github.com/mekanism/Mekanism/issues/5509

I'm not sure why VanillaFix (I guess?) claims AE2 is at all involved, as AE2 is mentioned nowhere in the stack trace of the crash report you posted.

At any rate, it seems the pack developer needs to update Mekanism.

**Comment by BoganC** [comment]
ok thank you

**Comment by BoganC** [comment]
yes i just updated it and that fixed it
