### ISSUE TITLE
Can't take Item out of terminal

### ISSUE THREAD

**Issue by Dilitritho** [AppliedEnergistics/Applied-Energistics-2#4091]
I can't take out a soul shard (soul shards respawn) from my crafting terminal. 

I created a soul shard for wither skeleton farming and decided to use it later. When I went to grab the soul shard, it just stays put.

I did some testing with it, if I place a newly made soul shard in the terminal, I can take it out. Only when the soul shard is bound to an entity does it become manually unmovable.

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-6
- Forge Version: 1.12.2-forge1.12.2-14.23.5.2838
SoulShardsRespawn -1.12.2-1.1.0-12.jar

**Comment by yueh** [comment]
Astral Sorcery bug.

**Comment by alileino** [comment]
Here is a workaround to get your expensive should shard(s) out:
1. Add a chest and a storage bus to it which accepts **unbound** soul shard
2. Add fuzzy card to the bus
3. Add a large priority
4. Empty your disks using IO port

You also get bound soul shards out this way. Export bus probably also works.

**Comment by syntaxaire** [comment]
As referenced in Doomgull's issue, this happens to /dank/null without Astral Sorcery installed.
