### ISSUE TITLE
question

### ISSUE THREAD

**Issue by zacharyhenry** [AppliedEnergistics/Applied-Energistics-2#4095]
how do u connect buildcraft quarry to me interface(ae2)
- Minecraft Version: 1.12.2
- AE2 Version: ae2-rv6-stable6
- Forge Version:14.23.5.2838

picture is what i have so far
![Minecraft 1 12 2 7_16_2019 4_21_54 AM](https://user-images.githubusercontent.com/49297302/61282643-562e3780-a781-11e9-99d2-781bb5ed9388.png)

**Comment by mindforger** [comment]
you placed an interface on an storage bus, that is your issue

you simply place the block version of the interface and connect it with a cable

but the quarry may not accept the me interface as inventroy, so you might have to use a chest as buffer ind import via import bus (+ upgrades to be fast enough)
