### ISSUE TITLE
Covered and dense cables broken

### ISSUE THREAD

**Issue by PreaFire** [AppliedEnergistics/Applied-Energistics-2#4096]
my dense and smart cables just try to use the shortest way run out of space and leave the empty spaces out 

i have 40 black hole units stacked in a 8x5 wall i connected all the storage busses with covered smart cables and connected those to 2 lines of dense smart cables

it happens when i try to get a lot of cables into fewer dense cables it just doesnt use the free spaces even when the other spaces are full

when the fastest rout is full and unusable it should use the second fastest

Mp: Stoneblock 2 1.15.0
the 2 dense lines are going to 2 different sides of my me controller

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-6
- Forge Version: 14.23.5.2838 (stoneblock 2 1.15.0)
![Runtime Screenshot 2019 07 17 - 21 45 23 33](https://user-images.githubusercontent.com/47985803/61407556-4d9f4380-a8de-11e9-9edf-3e801e0a8651.png)

**Comment by mindforger** [comment]
Use cable anchors to cut connections and let it snake around in One line or do it row wise or by column

**Comment by PreaFire** [comment]
ok thx for the help i didnt even know these existed fml x)
