### ISSUE TITLE
Crashing due to a clash between two mods. AE2 and Extra Cells 2

### ISSUE THREAD

**Issue by AwesomeBroDude** [AppliedEnergistics/Applied-Energistics-2#4097]
**Describe the bug**
When I placed down a charger from AE2 for a wireless terminal, and placed my Wireless terminal into the charger, I instantly crashed. This also answers the question below.

**Expected behavior**
I expected the WT to start charging like it normally should.

**Additional context**
https://pastebin.com/eJiT2ykg - Crashlog for the very first time it happened. Havent been able to log into the world since.

**Environment**
https://pastebin.com/9rc1zLww - This is the listed mods in the pack.

The modpack I am using is StoneBlock 2(v1.15.0) Minecraft Version 1.12.2 - run through the FTB Launcher, not the Twitch launcher.

- Minecraft Version: 
- AE2 Version: AE2WT - 1.0.30
AE2stuff - 0.7.0.4
- Forge Version: N/A - Forge Multipart by Chickenbones

**Comment by mindforger** [comment]
This is an bug in extracells, not ae2, just look at the stacktrace
