### ISSUE TITLE
Nested crafting assembler

### ISSUE THREAD

**Issue by vrnvorona** [AppliedEnergistics/Applied-Energistics-2#4098]
Advanced tool to create complicated crafts with only need to have raw materials, not the components, if possible.
**Describe the feature**

Instead of building a lot of patters and crafting all from terminal, allow components that are in need of craft to be crafted automatically if pattern is present. For example with having Wood->Stripped Wood-> Planks you need to call each craft one by one. I suggest instead, that with patterns present that just asking Planks it will use other patterns and create all steps itself from raw wood.
**Reasons why it should be considered**

Makes crafting complicated multi-step crafts even easier with just need of creating patters, not making a lot of crafts.
**Additional Context**

**Comment by yueh** [comment]
That's already how it works.
