### ISSUE TITLE
Plans on 1.14

### ISSUE THREAD

**Issue by mydexterid** [AppliedEnergistics/Applied-Energistics-2#4099]
Apologies for creating an issue for a question, I just don't know where this would be appropriate.
Feel free to close this immediately but pointing me to the right direction where it is appropriate to ask.

So as I see the the rv6.stable - 1.12 milestone is almost ready (only 1 issue left open).
The rv?.alpha - 1.13 milestone not even started, and the backlog milestone is... something.

Are there any plans on making this mod for 1.14, while skipping 1.13 completely, or rv?.alpha - 1.13 milestone comes first and sometime later there will be a 1.14 milestone too?

Thanks.

**Comment by yueh** [comment]
That is something you have to ask forge. Neither is there a stable 1.13 nor 1.14 release. It is still missing important features from 1.12 or earlier like fluids and so on. And then let's hope that mojang won't release 1.15 before and forge skips 1.14...

**Comment by electrofloat** [comment]
Fluids have been merged:
https://github.com/MinecraftForge/MinecraftForge/commit/b7e1cc5f6bc4338fc2e1b36faaa5184cabd198f9
https://github.com/MinecraftForge/MinecraftForge/pull/5983#issuecomment-525982480

**Comment by TheBigerGamer** [comment]
An update: Forge for 1.14.4 is stable.
