### ISSUE TITLE
Processing pattern output can't handle items more than one stack

### ISSUE THREAD

**Issue by Cyl18** [AppliedEnergistics/Applied-Energistics-2#4100]
**Describe the bug**
![image](https://user-images.githubusercontent.com/14993992/61657702-27bada00-acf6-11e9-8586-09235a2a8b41.png)
![image](https://user-images.githubusercontent.com/14993992/61657714-330e0580-acf6-11e9-8125-ff9e53eb659a.png)

**To Reproduce**

**Expected behavior**

**Additional context**

**Environment**

- Minecraft Version: 
- AE2 Version: appliedenergistics2-rv6-stable-6.jar
- Forge Version: latest

**Comment by yueh** [comment]
Each output will basically be added as a possible recipe, in this case it just happens that identical ones will overwrite each other.

With the actual recipe being 1 Sand -> 1 Glass, I do not seen any reason to support this. Especially as it could run into issues with minecraft not really supporting stacksizes larger than 64.
