### ISSUE TITLE
Changing The Dimension ID In 1.12.2

### ISSUE THREAD

**Issue by portalman22** [AppliedEnergistics/Applied-Energistics-2#4101]
I need to change the dimension id for Applied Energistics 2, as im getting this crash report

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Energistics 2 (appliedenergistics2)
Caused by: java.lang.IllegalArgumentException: Failed to register dimension for id 2, One is already registered

I am aware that this issue has been brought up on here before, but the solutions may be a little dated and some of the files i cant seem to find. (I am using winrar to open the .jar file)

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-6
- Forge Version: 14.23.5.2838 (1.12.2)

**Comment by Pingger** [comment]
Don't open the jar!
See #4080 
@yueh duplicate of dimension id already taken
