### ISSUE TITLE
Applied Energistics 2 exception

### ISSUE THREAD

**Issue by CaptainVSGames** [AppliedEnergistics/Applied-Energistics-2#4102]
Whenever I try to start my modpack server, AE2 runs into an exception. I do not know what is causing it, and I have tried reading the log myself.

#### Description
Using Latest Version already.
 I don't know how to recreate it except using the mods I currently have installed. Here is the mod list. https://pastebin.com/eGNbmw6t

#### Environment
Mod LIst: https://pastebin.com/eGNbmw6t
 Crash Report: https://pastebin.com/ftRXPTqQ

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-6.jar
- Forge Version: forge-1.12.2-14.23.5.2838-universal.jar

**Comment by mindforger** [comment]
this does not look like it has anything to do with AE2

this looks way more relevant 
https://github.com/Vazkii/Quark/issues/857

and it hints to decocraft having issues because it is not properly declaring a depending lib-mod PTRLib
