### ISSUE TITLE
Interface naming using ghost items

### ISSUE THREAD

**Issue by hubertnnn** [AppliedEnergistics/Applied-Energistics-2#4104]
Add an extra slot for overwriting name o interface.

**Describe the feature**
Would be nice to add an extra ghost item slot used to "name" an interface.

This item would define naming and grouping in interface terminal overwriting current behavior (aka checking what block the interface touches).

Eg. If you put a vanilla furnance there, then it would be shown together with other interfaces placed on vanilla furnaces, even if the interface is placed on IC2 electric furnace, a chest or any other machine.

**Reasons why it should be considered**
Interfaces have issues when working with multiblocks, they show the name of the block, and not the machine, eg. in gregtech interfaces placed on electric blast furnace and pyrolyse oven will both be shown as "Input bus (MV)" and grouped together. 

On top of that if you use an intermediate storage (eg. a chest) before your machine, you will see it as chest and not eg. "fluid transposer"

By making it possible to manually define the interface name using an item it would be easier to setup your machines using the terminal.

**Comment by Pingger** [comment]
Already a feature. See [Inscriber Name Press](https://ae-mod.info/Inscriber-Name-Press/)
1. Use the quartz cutter
2. rightclick into the air
3. place iron
4. name it. 
5. put it into the Inscriber (like the other presses)
6. put item to name into the middle slot
7. Profit

Alternatively: Use the enchanting table to rename either the interface or object attached to the interface.
