### ISSUE TITLE
How to remove error message from log after disabling channels

### ISSUE THREAD

**Issue by HaddockA** [AppliedEnergistics/Applied-Energistics-2#4105]
The mod is working fine for me, but after I disabled channels I get the following error message in my log:

**Parsing error loading recipe appliedenergistics2:network/blocks/controller**

Channels is the most common feature turned off, so especially in this case it would be nice to know how to hide that message and keep our logs clean, many people would appreciate your help on this one.

Thank you.

**Comment by HaddockA** [comment]
Ignore, I fixed it myself.

**Comment by Pingger** [comment]
@HaddockA 
Maybe you'd like to share, what fixed the issue? So others who run into the same issue can look here and see if your fix also applies to their issue.

**Comment by mindforger** [comment]
disabling channels was never fully supported by AE2 to my knowledge and diabling channels leads to certain items that are linked to channel (like smart cables) are diabled as block/item

this results in a few recepies breaking, for which you need to adjust. you can do it useing AEe2s recipe config or other mods/tools like crafttweaker

if i guess right the reported errors here are simply the recipes you did not adjust ... by guess i mean there is no logfile so nothing can be said specifically
