### ISSUE TITLE
Crafting operations use far more bytes than needed

### ISSUE THREAD

**Issue by Dr-Turtle** [AppliedEnergistics/Applied-Energistics-2#4107]
**Describe the bug**

When attempting to autocraft various recipes, the "bytes used" is far more than it should be, this can occur with both crafting and processing patterns, but there seems to be no correlation to which patterns this affects, all of the broken patterns stopped working properly at the same time, I am not sure if there was a specific action that caused this. The recipes are still craftable but require much larger CPUs than should be necessary

**Troubleshooting steps taken**

- Replaced pattern with a new identical pattern
- Moved pattern to various different interfaces capable of doing the same crafting job
- Removed interfaces and replaced with newly crafted ones
- Restarted server
- Rebooted ME system
- Removed all recently added patterns

None of the above had any effect on the issue

**To Reproduce**

I was unable to find a way to reproduce it outside of the pre-existing ME system with this bug

**Expected behavior**

Crafting request uses a number of bytes correctly based off of the items needed to be stored

**Additional context**

![image](https://user-images.githubusercontent.com/34402990/61997589-a787d200-b071-11e9-87ca-8830c4cb4520.png)
![image](https://user-images.githubusercontent.com/34402990/61997601-ce460880-b071-11e9-93b3-5d9e4227ee80.png)

I have previously been able to perform these crafts with many more steps required within my 14 1x 64k storage 16x co-processor CPUs, the same applies for numerous other crafts that are not shown in the screenshots above. I can provide the save if someone would like to inspect the ME system with this issue as I was unable to reproduce.

**Environment**

Modpack is Omnifactory 1.2.1
Channels are disabled (has 100+ interfaces, level emitters, etc.)
MP server (locally hosted)

- Minecraft Version: 1.12.2
- AE2 Version: rv6.stable.6 (rv6.stable.7 has fixes that appear to be unrelated)
- Forge Version: 14.23.5.2838

**Comment by yueh** [comment]
Please report all autocrafting related bugs directly to the modpack itself.
There are a couple mods, which break it intentionally and we cannot keep track, which modpack decides to use them.

**Comment by Dr-Turtle** [comment]
I have found that this is an issue with packagedauto and not AE2, I am sorry for posting here
