### ISSUE TITLE
Molecular Assembler not working with Sky Orchards patterns

### ISSUE THREAD

**Issue by HeyWhatsHisFace** [AppliedEnergistics/Applied-Energistics-2#4110]
Molecular Assembler works fine with other mods like Mystical Agriculture but not Sky Orchards. When I go to craft a pattern that has acorns or resin from the pack, it will go to the processors but the Molecular Assembler will not create any items that are made with items from the Sky Orchards pack.

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-6

![2019-08-04_04 23 29](https://user-images.githubusercontent.com/53689986/62421967-4e6efe00-b670-11e9-9489-d1bc0fc0a9d8.png)
![2019-08-04_04 23 37](https://user-images.githubusercontent.com/53689986/62421968-4f079480-b670-11e9-9ae4-43f1f1befab8.png)
![2019-08-04_04 23 02](https://user-images.githubusercontent.com/53689986/62421969-4f079480-b670-11e9-8234-85a7067f1b87.png)

**Comment by yueh** [comment]
Please report crafting directly to the modpack as they will use addons, which will intentionally break it and we cannot keep track of which modpack uses which.
