### ISSUE TITLE
Issue with Auto Crafting : Craft staying on scheduled

### ISSUE THREAD

**Issue by Cikei** [AppliedEnergistics/Applied-Energistics-2#4112]
Hi, I'm playing on a mod pack: Ragnamod V. I'm trying to auto-craft items with AE2. I can auto craft simple items like piston or others. I want to craft solar panel IV to VIII from the mod Solar Flux Reborn but it stays on scheduled.

I'm playing on Minecraft 1.12.2. AE2 : appliedenergistics2-rv6-stable-6.jar and forge: forge-14.23.5.2838

**Comment by yueh** [comment]
Please report all autocrafting related bugs directly to your modpack as most are using addons which intentionally break it.
