### ISSUE TITLE
Creative Mode middle click on dense smart cable crashes game

### ISSUE THREAD

**Issue by lclcpg2018** [AppliedEnergistics/Applied-Energistics-2#4113]
#### Description

Minecraft always crashes when I try to middle-click (getting the block/whatever thing) on a dense smart cable in creative (any colour), and the stacktrace appears to be an overload, with:

at net.minecraft.nbt.NBTTagCompound.func_74737_b(NBTTagCompound.java:452)
at net.minecraft.nbt.NBTTagCompound.func_74737_b(NBTTagCompound.java:24)

repeating literally infinite times...

Help! This is really quite annoying, especially cuz AE2 is such a critical mod!

#### Environment

LOG: https://paste.ee/p/DsAPV

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: 14.23.5.2838

**Comment by lclcpg2018** [comment]
Played in MultiMC, and no other mods had the E (errored) tag in the crash report.

**Comment by yueh** [comment]
BetterHUD bug.

**Comment by lclcpg2018** [comment]
Thanks so much!
