### ISSUE TITLE
Server crashing when auto crafting Master Infusion Stone / Insanium Essence

### ISSUE THREAD

**Issue by bestmine12345** [AppliedEnergistics/Applied-Energistics-2#4115]
I'm playing on my server, we are 2. When I try to craft the Master Infusion Stone from Mystical Agriculture with autocrafting, the server crashes. Also I can't autocraft Insanium or Supremium, when I click to autocraft them it does nothing and the server's lag for a bit of time. I can craft superium and lower tier essence/craft.

**Additional context**
Crash report : https://pastebin.com/BATRXziP

**Environment**
- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-6
- Mystical Agriculture Version : MysticalAgriculture-1.12.2-1.7.5
- Forge Version: forge-1.12.2-14.23.5.2838
- Modpack : Ragnamod V (version : 5.2.1)

**Comment by yueh** [comment]
Please report all autocrafting related bugs directly to your modpack as most are using addons which intentionally break it.
