### ISSUE TITLE
All Crafting table repices gone

### ISSUE THREAD

**Issue by big-lip-bob** [AppliedEnergistics/Applied-Energistics-2#4117]
**Describe the bug**
No repices or craft for items in the crafting table are availaible

**To Reproduce**
Unknown, May be due to having some other mod included that can conflict wiht AE2 and remove repices : mod list https://paste.dimdev.org/raw/epomecikuy

**Expected behavior**
Recipes and crafts need to be avaible

**Environment**
Singleplayer, no spongeforge, with optifine
1.12.2 Forge 2838, AE2 RV6-s7

**Comment by yueh** [comment]
Cannot reproduce. Also you should report recipe issue directly to your modpack, they usually know what they have changed and should be able to identify the actual issue for it.
