### ISSUE TITLE
Autocrafting simulation taking too long to compute and requiring too much memory

### ISSUE THREAD

**Issue by danielaschipper** [AppliedEnergistics/Applied-Energistics-2#4118]
**Describe the bug**

Upon making an autocrafting request to the AE system a there is a significant delay before moving to the crafting screen, most likely due to crafting computational time. This computational time is very out of step with the complexity of the craft, in addition the memory requirement of the craft is far larger than expected. However if the recipe of one of the ingredients is removed these problems go away.  This ingredient has significant complexity to craft, however a copy of it is already in the system and does not need to be crafted. The system seems to be doing computations as if the expensive ingredient is not there. In addition removing sub ingredients from the complex provided ingredient does lessen the effect.

This problem has been replicated in my system for multiple items, as one particular example in the omnifactory pack crafting dragon hears requites the draconium microminer, which is a complex craft. However when the system has one in stock it still takes the time to compute as if it did not. 
![AEwithCraft](https://user-images.githubusercontent.com/23439648/62690641-25a88900-ba21-11e9-8b31-6d7f3105ae24.PNG)
When removing the recipe for the microminer the memory requirements and time to compute dropped to normal
![AEwithoutCraft](https://user-images.githubusercontent.com/23439648/62690750-60aabc80-ba21-11e9-98ba-d2aab609fae5.PNG)
Assuming that it might be the packagedauto mod doing something weird I removed all packagedauto components for my network.  This did not resolve the issue.
![AEwithoutPackaedAuto](https://user-images.githubusercontent.com/23439648/62690840-95b70f00-ba21-11e9-9f38-742dd9677a08.PNG)
However because several components for the microminer were removed the time taken and memory cost dropped. 

**To Reproduce**

I have not tried to reproduce in a clean world, however in the attached world file just try and craft a dragon heart.

**Expected behavior**

AE does not try to compute crafting for components it does not have to. 

**Additional context**

**Environment**

- Minecraft Version: 
Minecraft Version: 1.12.2
- AE2 Version: 
appliedenergistics2-rv6-stable-7 (latest and specifically updated) 
- Forge Version:
forge-14.23.5.2838
Everything else if the omnifactory pack with AE2 related mods updated, list  
actuallyadditionsapi (34) from ActuallyAdditions-1.12.2-r148.jar
		* ae2wtlib|API (1.0.30) from AE2WTLib-1.12.2-1.0.30.jar
		* appliedenergistics2|API (rv6) from appliedenergistics2-rv6-stable-7.jar
		* ArmorPlusApi (2.1) from armorplus-1.12.2-11.24.0.60.jar
		* Base|API (1.0.0) from base-1.12.2-3.13.0.jar
		* Baubles|API (1.4.0.2) from Baubles-1.12-1.5.2.jar
		* betteradvancements|API (0.1.0.77) from BetterAdvancements-1.12.2-0.1.0.77.jar
		* BetterQuesting|API (3.2) from BetterQuesting-3.5.300.jar
		* BetterQuesting|API2 (3.1) from BetterQuesting-3.5.300.jar
		* BetterWithModsAPI (Beta 0.6) from AppleSkin-mc1.12-1.0.9.jar
		* chesttransporter|api (2) from ChestTransporter-1.12.2-2.8.8.jar
		* Chisel-API (0.0.1) from Chisel-MC1.12.2-0.2.1.35.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.12.2-0.2.1.35.jar
		* cofhapi (2.5.0) from CoFHCore-1.12.2-4.6.3.27-universal.jar
		* CraftingTweaks|API (4.1) from CraftingTweaks_1.12.2-8.1.9.jar
		* ctm-api (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
		* ctm-api-events (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
		* ctm-api-models (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
		* ctm-api-textures (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
		* ctm-api-utils (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
		* DraconicEvolution|API (1.3) from Draconic-Evolution-1.12.2-2.3.22.343-universal.jar
		* enderioapi (4.0.0) from EnderIO-1.12.2-5.0.46.jar
		* enderioapi|addon (4.0.0) from EnderIO-1.12.2-5.0.46.jar
		* enderioapi|capacitor (4.0.0) from EnderIO-1.12.2-5.0.46.jar
		* enderioapi|conduits (4.0.0) from EnderIO-1.12.2-5.0.46.jar
		* enderioapi|farm (4.0.0) from EnderIO-1.12.2-5.0.46.jar
		* enderioapi|redstone (4.0.0) from EnderIO-1.12.2-5.0.46.jar
		* enderioapi|teleport (4.0.0) from EnderIO-1.12.2-5.0.46.jar
		* enderioapi|tools (4.0.0) from EnderIO-1.12.2-5.0.46.jar
		* enderioapi|upgrades (4.0.0) from EnderIO-1.12.2-5.0.46.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|arboriculture (4.3.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|book (5.8.1) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|climate (5.0.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|core (5.7.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|farming (5.8.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|food (1.1.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|genetics (5.7.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|gui (5.8.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|lepidopterology (1.4.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|modules (5.7.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|world (2.1.0) from forestry_1.12.2-5.8.2.387.jar
		* ForgeEndertechAPI (1.0) from ForgeEndertech-1.12.2-4.4.21.1-build.0377.jar
		* Guide-API|API (2.0.0) from Guide-API-1.12-2.1.8-63.jar
		* journeymap|client-api (1.4) from journeymap-1.12.2-5.5.5b7.jar
		* journeymap|client-api-display (1.4) from journeymap-1.12.2-5.5.5b7.jar
		* journeymap|client-api-event (1.4) from journeymap-1.12.2-5.5.5b7.jar
		* journeymap|client-api-model (1.4) from journeymap-1.12.2-5.5.5b7.jar
		* journeymap|client-api-util (1.4) from journeymap-1.12.2-5.5.5b7.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.15.0.283.jar
		* MouseTweaks|API (1.0) from MouseTweaks-2.10-mc1.12.2.jar
		* Open Glider|API (0.1) from OpenGlider-1.12.1-1.1.0.jar
		* PatchouliAPI (6) from Patchouli-1.0-20.jar
		* reborncoreAPI (3.13.12.447) from RebornCore-1.12.2-3.13.12.447-universal.jar
		* reborncoreAPI|Power (3.13.12.447) from RebornCore-1.12.2-3.13.12.447-universal.jar
		* reborncoreAPI|Recipe (3.13.12.447) from RebornCore-1.12.2-3.13.12.447-universal.jar
		* reborncoreAPI|Tile (3.13.12.447) from RebornCore-1.12.2-3.13.12.447-universal.jar
		* redstonefluxapi (2.1.0) from RedstoneFlux-1.12-2.1.0.6-universal.jar
		* StorageDrawersAPI (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
		* StorageDrawersAPI|event (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
		* StorageDrawersAPI|registry (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
		* StorageDrawersAPI|render (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
		* StorageDrawersAPI|storage (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
		* StorageDrawersAPI|storage-attribute (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
		* theoneprobe_api (1.4.4) from theoneprobe-1.12-1.4.28.jar
		* wct|api (1.1) from WirelessCraftingTerminal-1.12.2-3.12.93.jar

World copy, Note a large portion of the world, including other dimensions has been deleted, however these parts do not  have anything in them. 
[New World - Copy.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/3481011/New.World.-.Copy.zip)

**Comment by yueh** [comment]
Please report all autocrafting related bugs directly to your modpack as most are using addons which intentionally break it.
