### ISSUE TITLE
Sort crafting plan with unavailable items first

### ISSUE THREAD

**Issue by codeka** [AppliedEnergistics/Applied-Energistics-2#4119]
**Describe the feature**
Sort the items in the "Crafting plan" window so that missing items are displayed before everything else.

**Reasons why it should be considered**
The crafting plan can get pretty big for complex builds. Missing items appear randomly scattered throughout the list in red, and it means you've got to slowly scroll down the screen to see what you don't have available.

**Additional Context**
Here's an example from Enigmatica 2: Expert: I'm building a bunch of infinity catalysts, but the flux singularities are the only thing I don't have enough of. But because it appears about half-way down the list, it's really hard to know (it also means I'm never 100% sure that this is the *only* thing I'm missing...) If missing items were sorted at the top, it would be so much easier to use.

<img width="515" alt="Screen Shot 2019-08-10 at 6 24 58 PM" src="https://user-images.githubusercontent.com/1569910/62828491-c8d1dd80-bb9c-11e9-844e-9462cbe8f3ec.png">

**Comment by yueh** [comment]
Please report all autocrafting related bugs directly to your modpack as most are using addons which intentionally break it.

**Comment by mindforger** [comment]
@yueh i think this was an suggestion :)

**Comment by codeka** [comment]
Yeah, the screenshot from E2:E was just an example, this is a suggestion to sort the crafting plan window.

**Comment by mindforger** [comment]
Sorry if i may overextended my permissions in reopening it

**Comment by yueh** [comment]
This is a bug. Missing ingredients are at the end of the list.

**Comment by mindforger** [comment]
Ah okay, wasnt clear, sorry

**Comment by codeka** [comment]
OK, so to show that this isn't an issue related to Enigmatica 2, I've installed AE2 rv6-stable-7 on it's own in a new instance:

![2019-08-11_13 25 08](https://user-images.githubusercontent.com/1569910/62839200-9d520000-bc3b-11e9-9c81-c9afeadbcd24.png)

It's a little harder to get really complicated recipes with only vanilla stuff available, but here's a daylight sensor recipe.

![2019-08-11_13 24 49](https://user-images.githubusercontent.com/1569910/62839221-f883f280-bc3b-11e9-9ddc-5cc66ac434f9.png)

I have no nether quartz and no glass in my system so they are indeed sorted at the bottom (I would argue sorting them at the top is better than the bottom, because then you don't have to scroll at all to see them, but no matter). However, notice that I have *some* wood but not enough: that's not sorted at the bottom with the rest of the missing items, it's in the middle.

![2019-08-11_13 28 29](https://user-images.githubusercontent.com/1569910/62839224-00dc2d80-bc3c-11e9-9e9a-874598be2c22.png)

Now I've added some glass, but not enough. Notice how the glass has moved from the bottom of the list to the middle as well.

The suggestion here is to sort *all* missing items at the top (or I could live with them all at the bottom as well).

**Comment by Ommina** [comment]
So "some missing" are still sorted within "available".

For my part, I agree.  As 'missing anything at all' is enough to block the craft, it makes sense to have all the "Missing" as a group (yes, ideally at the top), then available / to craft.  If the Start button isn't enabled, the first thing a user is going to want to know is 'why'.  Making the 'why' easy to find seems like a better UX.

**Comment by codeka** [comment]
FWIW, here's the result of my PR above:

![2019-08-11_23 38 53](https://user-images.githubusercontent.com/1569910/62848732-b1285100-bc91-11e9-8606-d8448ceea78d.png)
