### ISSUE TITLE
Cable facade is glitched in one corner

### ISSUE THREAD

**Issue by someone0010** [AppliedEnergistics/Applied-Energistics-2#4120]
**Describe the bug**
The graphics turn weird in one corner on the facades. Screenshot below.

**To Reproduce**
I tried it with Optifine HD E3 Ultra (on my other saves the glitch doesn't seem to pop out, even with OptiFine). Place a smart cable and a facade on it, and it should glitch like that.

**Expected behavior**
I expected the facade to blend into the marble/glowstone (using the CTM mod). It only blends 3/4 the way and the last quarter just keeps glitching out.

**Additional context**
![WeirdGPUGlitch](https://user-images.githubusercontent.com/44930310/62837935-c7281880-bc75-11e9-8fee-c4ed57a35940.PNG)

GPU: AMD Radeon R9 270X Series (not overclocked)
CPU: Intel i5-4400 3.10GHz

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-6
- Forge Version: 14.23.5.2837

**Comment by Battlecrown** [comment]
Have the same problem
![2020-01-01_17 16 48](https://user-images.githubusercontent.com/59414246/71642313-91cea680-2cba-11ea-8aa6-1e4d2cb45b0b.png)
CPU: FX-4350(4.5 Ghz/Overclocked)
GPU: RX 460(Overclocked)
RAM: 16 Gb 1720(1600) Mhz.

**Comment by Pultex** [comment]
Are facade parft of AE2 thought it was an add-on

**Comment by yueh** [comment]
Probably some optifine issue. They constantly come up in various combination. 

Looksl like a chisel block texture due to the 2x2 texture grid. So could be something like CTM + Optifine not working in some cases or for some blocks.
