### ISSUE TITLE
Cannot autocraft EnderIO soul vial

### ISSUE THREAD

**Issue by Cyl18** [AppliedEnergistics/Applied-Energistics-2#4122]
**Describe the bug**

Cannot autocraft EnderIO soul vial

**To Reproduce**

insert two encoded pattern into a ME interfact
![image](https://user-images.githubusercontent.com/14993992/62855910-09a92e00-bd26-11e9-93fd-5406f7c76b19.png)
![image](https://user-images.githubusercontent.com/14993992/62855921-0f9f0f00-bd26-11e9-9122-5cd32b85963f.png)

**Expected behavior**

it shows "crafting tree construction failed"

**Additional context**
https://youtu.be/h6W9PcxJcek

**Environment**

Omnifactory v1.2.1

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-6
- Forge Version: 1.12.2-14.23.5.2838

**Comment by mindforger** [comment]
is that a modpack or just the two mods? can you post the version of all mods included? this can not be reproduced with this few data

**Comment by Cyl18** [comment]
> is that a modpack or just the two mods? can you post the version of all mods included? this can not be reproduced with this few data

Omnifactory v1.2.1

**Comment by mindforger** [comment]
then report this to the modpack authors first please as they might have changed the recipes

**Comment by yueh** [comment]
Please report all autocrafting related bugs directly to your modpack as most are using addons which intentionally break it.
