### ISSUE TITLE
Cannot craft items from Thermal Solars with Molecular Assembler

### ISSUE THREAD

**Issue by Adrriii** [AppliedEnergistics/Applied-Energistics-2#4126]
Here is one of the crafts : 
https://puu.sh/E6I0O/5b02c5c853.png

Here is what it shows in the molecular assembler :
https://puu.sh/E6HZN/47e806353f.png

The pattern was made correctly : 
https://puu.sh/E6I23/ef7b4f89ad.png

**Comment by yueh** [comment]
Please report all autocrafting related bugs directly to your modpack as most are using addons which intentionally break it.

**Comment by Adrriii** [comment]
This is a custom modpack I made, nothing was meant to break it

**Comment by Pingger** [comment]
Then the infortmation requested in the template might be useful ...
AE2 version
Forge version
Minecraft version

Additionally a list of the other mods and their version would be very helpful.

**Comment by Adrriii** [comment]
Minecraft: 1.12.2
Forge: 14.23.5.2838
AE2 : rv6-stable-7

Other mods : 
CodeChickenLib-1.12.2-3.2.3.357
CoFHCore-1.12.2-4.6.3.27
CoFHWorld-1.12.2-1.3.1.7
MRCrayFish's Furniture-6.3.0-1.12.2
Just Enough Items 1.12.2-4.15.0.287
MovingQuickly-1.12.2_1.0.0
RedstoneFlux-1.12-2.1.0.6
ThermalDynamics-1.12.2-2.5.5.21
ThermalExpansion-1.12.2-5.5.4.43
ThermalFoundation-1.12.2-2.6.3.27
Thermal-Solars-Mod-1.12.2
Voice Chat Reloaded-1.2.0
WorldEdit Forge-mc1.12.2-6.1.10

**Comment by Adrriii** [comment]
Here is another craft that doesn't work in Thermal Foundation

https://puu.sh/E6LfS/434a18a9f2.png

**Comment by mindforger** [comment]
I spot plugin related mods, is this an single player issue? Can you confirm this happens in single player?

**Comment by Adrriii** [comment]
Hey, so in fact i'm a total noob and i used 6 interfaces on the molecular assembler. Output wasn't connected to the network. Everything is working ...

And this was on a forge server, but it's not relevant anymore then

**Comment by Pingger** [comment]
So the issue was, that the m. assembler wasn't powered. You can only attach 5 interfaces on to 1 ma., because at least one side needs to be connected to power (usually a normal me cable without interface)
