### ISSUE TITLE
ME Formation Plane Infinite redstone

### ISSUE THREAD

**Issue by Mirror-XD** [AppliedEnergistics/Applied-Energistics-2#4128]
#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: rv6.stable build 7
- Forge Version: 2838

If constructed in this way, the ME Formation Plane will be indefinitely brushed with Double redstone.
![image](https://user-images.githubusercontent.com/54396722/63502977-32d57580-c501-11e9-801c-be712f6ec1a6.png)

**Comment by mindforger** [comment]
no modlist included, this is most probably another mod causing the issue, there are several other reports over this directing at flux network as culprit
