### ISSUE TITLE
Way to obtain Wireless without Security Terminal

### ISSUE THREAD

**Issue by tyler489** [AppliedEnergistics/Applied-Energistics-2#4129]
**Describe the feature**
When Security terminals are disabled there is no way to link your wireless terminal to your network. Prehaps u could shift click the terminal on your controller 

**Reasons why it should be considered**
We have a custom "faction/raiding" plugin where blocks are protected unless they are blown up via explosion. when a security terminal is on the network blocks are unable to be blown up. After we disabled the security terminal people were complaining that they were unable to use Wireless networking 
**Additional Context**
none

**Comment by yueh** [comment]
Wireless terminals a tightly coupled with the security features provided by a security station. Separating them would be a really high effort task, which is simply not worth it. Also in terms of potential bugs, required effort to support multiple (incompatible) systems in the long run, etc.
