### ISSUE TITLE
ME Fluid interface input from single side fills all buffers with same fluid

### ISSUE THREAD

**Issue by Eds1989** [AppliedEnergistics/Applied-Energistics-2#4135]
#### Description
When I have several fluid inputs to an ME fluid interface, if only one of the inputs is currently inputting a fluid, all the internal buffers will fill with that fluid.
I was expecting one buffer to correlate to one side of the block, so once the buffer for that side was full, it would stop.
This would then allow inputs of different fluids on different faces to fill the other buffers.

In a situation where I have no room on my ME network for that particular fluid, if all buffers fill, I cannot import any other fluid as they have no buffer to transfer to.

#### Environment
- Minecraft Version: 1.12 
- AE2 Version:  rv6-stable- (ATM3R 1.4.9)
- Forge Version: 14.23.5.2838 (FML 8.0.99.99)

**Comment by yueh** [comment]
Fluid interfaces behave just like their item counterpart and expose everything on every side the interface handles.

**Comment by Eds1989** [comment]
Ok. Can I raise this as a feature request instead of a question/bug?
