### ISSUE TITLE
Fluix Pearl Recipe Not Available

### ISSUE THREAD

**Issue by Trudster1988** [AppliedEnergistics/Applied-Energistics-2#4137]
**Describe the bug**
When trying to craft a Fluix Pearl, the recipe seems to not exist. I have tried manually making it and it doesn't work.

**Expected behavior**
Recipe should allow player to craft a fluix pearl.

- Minecraft Version: 1.10.2
- AE2 Version: appliedenergistics2-rv4-stable-1.jar
- Forge Version: forge-12.18.3.2511

**Comment by yueh** [comment]
In general we do not support old versions of AE2, but I'd recommend raising this to your modpack. Most likely they disabled or changed the recipe for whatever reason.
