### ISSUE TITLE
Autocrafting Serverside Lag (With Samples)

### ISSUE THREAD

**Issue by TheFlash787** [AppliedEnergistics/Applied-Energistics-2#4140]
**Describe the bug**
Hey! So we started to notice lag spikes on the server ranging from 7 seconds up to 20 seconds very frequently. I first ran a LagGoggles profile to see if it was a silly block that might've caused it, but as we know from #4131, all I saw was it using 200% or so as an event subscriber. So then I ran an ongoing Sampler profile to grab some NPS samples, which of course show AE2 using up all of the ticktime in those spikes. The issue basically being that there are lots of crafting recipes which AE2 can't handle easily.

With the issue I referenced, I was also looking for a response to their actual suggestion (that being an AE2 setup profiler), where perhaps when you run a scan it will gather (or it could on an config-based interval, print out) which AE2 systems (by it's controller position) are using the most ticktime. It could even provide other information such as recipes detected, running/pending crafting tasks, etc. I feel that this will really help out all server owners who are required to use AE2 on the servers.
![image](https://user-images.githubusercontent.com/25883284/63963945-f1f3d880-ca8d-11e9-9651-7baab163323a.png)
![image](https://user-images.githubusercontent.com/25883284/63963962-f9b37d00-ca8d-11e9-89d8-40b016c5e733.png)

**To Reproduce**
1) Having a server with a technology based modpack (such as Omnifactory) will help since it's entirely based around AE2 autocrafting early-to-mid-game. 
2) Setup average autocrafting for most components needed for progression in the modpack.
3) Sit back and watch the spikes happen

**Expected behavior**
I would expect that AE2 would at least try to streamline a large amount of AE2 crafting recipes much easier, without using up too much of the ticktime

**Additional context**
![image](https://user-images.githubusercontent.com/25883284/63964162-7181a780-ca8e-11e9-9fc7-5801a4602ab3.png)
**Channels are enabled, which helped the performance initially**

**Environment**
- Minecraft Version: 1.12.2
- AE2 Version: `appliedenergistics2-rv6-stable-6.jar `
- Forge Version: `forge-1.12.2-14.23.5.2838`
- Mod List: https://pastebin.com/jFJDabAs

**Comment by yueh** [comment]
1. We do not support sponge as this can/will cause these issues.
2. We cannot support modpacks which intentionally break autocrafting and can cause these issues. Please report it to the modpack authors.
