### ISSUE TITLE
Some Items Are Not visible in ME network

### ISSUE THREAD

**Issue by PizzaAddict** [AppliedEnergistics/Applied-Energistics-2#4142]
**Describe the bug**
https://github.com/NillerMedDild/Enigmatica2Expert/issues/1333

**To Reproduce**
Sorry. I cannot reproduce. but I can share the save file. give me an email address. then I'll send you Onedrive folder share link

**Environment**
modpack:enigmatica2 1.66c 
AE2 version:rv6-stable-6
forge version: 14.23.5.2836

**Comment by yueh** [comment]
Please report all autocrafting related bugs directly to your modpack as most are using addons which intentionally break it.

**Comment by Pingger** [comment]
@yueh not autocrafting related. Handcrafted items put into the me network are bo kobger displayed after closing and opening the terminal. Can't see the link to autocrafting.
