### ISSUE TITLE
ME system randomly stops doing anything related to inputting/outputting

### ISSUE THREAD

**Issue by botboy0** [AppliedEnergistics/Applied-Energistics-2#4143]
Hello people :)

I am dealing with a major issue since a few days . 

my problem is that My ME system stops doing anything related to inputting and outputting items , that includes:

Import bus , export bus and occasionally the  Me Interface

when does it happen? : it appears to be almost random but get worse over the span of a couple of minutes

how does it happen? : whenever I have an ME system setup that has anything to do with inputting / outputting items

Happens in : Omnifactory Modpack

Have you checked X/Y ? :
 
I checked and made sure my problem is not related to:

Power consumption ( i tested it in creative with a creative energy cell)
Storage capacity ( tested with big amounts of empty cells and creative cells) 
Server issues ( tested on a singleplayer world and it is indeed a problem of the world and not the server)
Chunkloading ( everything is chunkloaded)

I also tried rebuilding and resetting my ME system partially and entirely but It only makes it work for a few more minutes before breaking down once again

Here is the world download:

https://we.tl/t-VRKH3uFbL7

**Comment by yueh** [comment]
Please report it to the modpack. They are using a couple mods, which break AE2 intentionally.
