### ISSUE TITLE
Droppers not working with seeds/fluix

### ISSUE THREAD

**Issue by dovaezburn** [AppliedEnergistics/Applied-Energistics-2#4144]
#### Description
Having a problem with AE2 seeds not being an entity when dropped by a non player (open crates and item droppers in general) same thing with fluix crystal. The seeds do not grow unless a player drops it, I have no plugins or mods that   I can think of that's blocking non players from creating entities like that, has anyone have this problem before or know a way of fixing it?

#### Environment

- Minecraft Version: 
- AE2 Version: rv6-stable-7
- Forge Version: 1.12.2

**Comment by yueh** [comment]
We do not support anything like Sponge or Bukkit officially. Only a standard forge environment.

Should you be able to reproduce it without it and in a new environment and save, please update the issue accordingly and we will reopen it.
