### ISSUE TITLE
Crystal seeds of all type despawn.

### ISSUE THREAD

**Issue by jgilmore** [AppliedEnergistics/Applied-Energistics-2#4146]
Drop them in, wait, disconnect, reconnect, and they vanish without a trace. Fluix seeds, nether quartz seeds, and the mod-special quartz seeds all do this.

I'm not using (and *probably* cannot use) the most recent version, as I have to use an older version of forge due to some mods not supporting more recent versions.

This is my most recent attempt to use this mod, but I recall encountering the same showstopper last time. Perhaps it's time to admit that dropped items aren't supposed to persist?

Seriously, this is a weird mechanic, and encounters clashes with all sorts of mods. JEI, NEI, and all other recipe mods won't show recipes for this stuff, meaning that it ALWAYS has to be looked up online to get started. Which is stupid.

All mods that deal with picking up items (enderIO's electromagnet comes to mind)
All mods that auto-despawn or shorten the despawn time of items. (which is just about every mod that tries to optimize things)

Better idea: Play it like twlight forests portal, and take an action when the seeds or charged crystals are thrown in. What action? Change the water block to a chest-like block that looks just like water, and displays the contained seeds floating inside. That way you won't have to worry about all that stuff, because it's not an item sitting in the world, it's a custom crafting block like the press, and will be easier for other mods to interact with by default. You could even add the fluix crystal creation method as a recipe for completeness sake, just so people can look it up using standard recipe mods. And et viola! Looks the same, but never have to worry about despawning, or interface with electromagnets, or any of that other stuff.

Another alternate: Just make another crop. Lots of mods do it. And if you're going to call something a "seed" then that's what people are expecting anyway. It doesn't have to plant on farmland, even. Plant it on a quartz block, for instance, that would make sense enough that you could expect people to guess it.

I'm using the technic launcher, and forge-1.12.2-14.23.4.2705-universal.jar
it's a multi-player server, running on linux.

I don't really expect you to change this, and given it's non-standardness it's probably been fixed dozens of times already.I'm just frustrated that, after taking a second look at this, it still doesn't work for me. Growing crystals seems to be core to making this mod work, and without that it's pretty useless. Combine that with a counter-intuitive mechanic that is (again) bugged, and it's a recipe for frustration.

complete mods list:
ae2stuff-0.7.0.4-mc1.12.2.jar
AkashicTome-1.2-10.jar
angelRingToBauble-1.12-0.3.1.50+d4e654e.jar
appliedenergistics2-rv5-stable-11.jar
astralsorcery-1.12.2-1.9.4.jar
AutoRegLib-1.3-20.jar
badwithernocookiereloaded-1.12.2-3.1.14.jar
Baubles-1.12-1.5.2.jar
bdlib-1.14.3.12-mc1.12.2.jar
BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar
BloodMagic-1.12.2-2.3.3-101.jar
CodeChickenLib-1.12.2-3.2.0.345-universal.jar
CoFHCore-1.12.2-4.5.2.19-universal.jar
CoFHWorld-1.12.2-1.3.0.6-universal.jar
CookingForBlockheads_1.12.2-6.4.65.jar
CustomOreGen-1.12-1.8.1.jar
DummyCoreUnofficial-2.4.112.5.jar
EnderCore-1.12.2-0.5.41.jar
EnderIO-1.12.2-5.0.35.jar
extrautils2-1.12-1.9.4.jar
ExtremeReactors-1.12.2-0.4.5.49.jar
forestry_1.12.2-5.8.1.322.jar
furniture-5.13.0-1.12.2.jar
gravestone-1.10.1.jar
Guide-API-1.12-2.1.6-61.jar
InventoryTweaks-1.63.jar
jei_1.12.2-4.12.1.217.jar
LibEx-1.12.2-1.0.8.jar
MagicBees-1.12.2-3.1.10.jar
Mantle-1.12-1.3.2.24.jar
mcjtylib-1.12-3.0.5.jar
mystcraft-1.12.2-0.13.6.00.jar
NetherEx-1.12.2-2.0.8.jar
OptiFine_1.12.2_HD_U_E2.jar
ProjectE-1.12-PE1.3.1B.jar
RedstoneFlux-1.12-2.0.2.3-universal.jar
Ruins-1.12.2.jar
Tainted-Magic-r7.82.jar
Thaumcraft-1.12.2-6.1.BETA25.jar
thaumicbases-3.2.265.4r-BBF.jar
ThaumicEquivalence-1.12.2-1.0.5.jar
ThaumicJEI-1.12.2-1.5.3-20.jar
ThermalDynamics-1.12.2-2.5.1.14-universal.jar
ThermalExpansion-1.12.2-5.5.0.29-universal.jar
ThermalFoundation-1.12.2-2.5.0.19-universal.jar
Treecapitator-1.12-at_0.9a.jar
twilightforest-1.12.2-3.8.689-universal.jar
WIT-1.12-1.0.24-43.jar
Xaeros_Minimap_1.15.8_Forge_1.12.jar
zerocore-1.12-0.1.2.2.jar

**Comment by mindforger** [comment]
seeds should not despawn, do you use a server only mod that you might have not include into the list (because it looks like a client side mod list) or some sort of script that cleans dropped entitys on a regular shedule?

>it's a multi-player server, running on linux.

plain forge or some sort of spigot/sponge ... maybe there is an option that interferes with the anti-despawn or a plugin

**Comment by yueh** [comment]
JEI has info pages about crystals/seeds explaining them. This might be a rv6, I simply cannot remember currently. These things just happen when someone refuses to update, so no new features, bugfixes and so on.

If your server forcefully deletes items before the normal despawn time, it's their fault. Nothing we can do about it.

**Comment by Pingger** [comment]
As you are using AE2 stuff I propose the use of the **Crystal Growth Chamber**. It grows Crystals inside a chest like block. (Taken from here: https://www.curseforge.com/minecraft/mc-mods/ae2-stuff)

**Comment by mindforger** [comment]
i just crossread a code comment on "setnodespawn()" on immersive engineering's build 91 that this does only increase despawn time to 10 minutes, is this true?

**Comment by Ommina** [comment]
It increases the despawn time by ten minutes.

But AE is setting the maximum age somewhat higher: https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/df2a7c18588aa5d322910dc1a93ca1be3fea372a/src/main/java/appeng/items/misc/ItemCrystalSeed.java#L172-L176

**Comment by mindforger** [comment]
oh okay, i was looking at 
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/c2d18ce0133a27d54a16d95a4f89f38dbc1a1bb1/src/main/java/appeng/entity/EntityGrowingCrystal.java
that confused me a bit
