### ISSUE TITLE
Suggestion: More info on invalid patterns

### ISSUE THREAD

**Issue by seebs** [AppliedEnergistics/Applied-Energistics-2#415]
Sometimes if mods have been updated, encoded patterns become invalid. It would be neat to have some way to examine an encoded pattern to see what it might have been, such as listing its inputs or outputs if any of them are still recognizable. Even something arcane like "Crafts One INVALID:4872 from 3 INVALID:2817" would be helpful, but if a couple of the parts are recognizable, you can probably figure it out.

**Comment by leagris** [comment]
Some mod updates can have changed recipes, rendering existing patterns invalid.
It would be just fine it the pattern editor allowed placing the pattern back into the editor and even highlight wrong ingredients with some overlay texture.
