### ISSUE TITLE
Missing recipes

### ISSUE THREAD

**Issue by Rhah-** [AppliedEnergistics/Applied-Energistics-2#4150]
I'm having an issue with no AE2 recipes, other than dusts and facades, being recognized by JEI. I've gone through and looked at some of the older issues here to see if any are similar, but I haven't found anything that stands out particularly. Any help would be appreciated.

Here is the [latest.log](https://pastebin.com/4fU761Yw)

**Environment**
- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-7
- Forge Version: 14.23.5.2846

**Comment by Rhah-** [comment]
I'm working through adding in all mods one by one and I think I may be narrowing it down.

**Comment by mindforger** [comment]
did you use always the same config folder? sounds like it has been configured out then

**Comment by Rhah-** [comment]
> 
> 
> did you use always the same config folder? sounds like it has been configured out then

I did not. Once I managed to get all the mods loaded and still maintain working order, configs was my next guess. I feel more confident this is where the issue lies if you're also suggesting it. I'm going through the old configs now to see if there was something that was changed that should not have been.

**Comment by mindforger** [comment]
if there is crafttweaker present, there will also be a "scripts" folder

**Comment by Rhah-** [comment]
> 
> 
> if there is craft/modtweaker present, there will also be a "scripts" folder

They were there at one point but then removed when I noticed the problem. I haven't created any scripts to use with them yet, but axed them just in case something wonky was going on in the background.

I think I might have found the issue: Would disabling the tools in AE2 be a cause for my issues? The comparison tool for N++ shows that line as being the only one different between to the 2 configs.

**Comment by Rhah-** [comment]
That may have been it. I disabled the tools with the umbrella option thinking it was going to the pick/shovel/sword/etc. Apparently, it disables something that breaks the recipes for everything. After re-enabling the umbrella option and disabling the individual tools themselves seems to have resolved the current issue, but does little to explain why it happened in the first place. Do you have any insight on that?

**Comment by mindforger** [comment]
>I disabled the tools with the umbrella option

the what now?

is that something inside the AE2 config?

**Comment by Rhah-** [comment]
Those.
https://i.imgur.com/A8Gapaw.png

You know, like an umbrella group. A group that contains other smaller groups. Except in this case its options and not groups. Either way, disabling either certusquartztools or netherquartztools breaks recipes, whereas only disabling the quartzaxe/hoe/etc is the right way to do it. Lesson learned: Don't disable those two options.

**Comment by mindforger** [comment]
@yueh seems like something is actually broken there, i can't find it but i remember (not quite sure) this was reported already but dropped because of no response from the author

**Comment by yueh** [comment]
That's a Forge bug/feature once you dare to use their provided recipe system in full and not just half of it.

There are basically two options.

1. Have recipes break in certain configurations and force a small number ofmodpack to provide their own. That's simply because once Forge has a single invalid recipe, it will throw away any from this mod instead of just ignoring it.

2. Have recipes be broken for everyone. E.g. no longer being able to use damageable tools and instead you have to craft a new one for every single crafting and a couple of other issues.

**Comment by mindforger** [comment]
oh, that was the conclusion :D well he found an workaround
