### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by drago87** [AppliedEnergistics/Applied-Energistics-2#4152]
Getting a crash on startup

**Additional context**
OpenEye crashlog rv6 stable 7 https://openeye.openmods.info/crashes/3c7838391b228655609d79f2334c804a

OpenEye crashlog rv6 stable 6
https://openeye.openmods.info/crashes/2630154948c4df97deb75afc55f99666

Minecraft Crashlog rv6 stable 7
[crash-2019-09-10 rv6 stable 7.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/3596507/crash-2019-09-10.rv6.stable.7.txt)

Minecraft crashlog rv6 Stable 6
[crash-2019-09-10 rv6 stable 6.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/3596517/crash-2019-09-10.rv6.stable.6.txt)

**Environment**

Minecraft 1.12.2

All mods and versions on the OpenEye crashlog link

- Minecraft Version: 
- AE2 Version: rv6 stable 6 and 7
- Forge Version: 14.23.5.2847

**Comment by yueh** [comment]
I would recommend identifying the mod shipping our API as it will cause it and then inform them, so they can stop it.

Sadly there is no way to tell which one it might by based on the crashlog.
