### ISSUE TITLE
IC2's eject upgrade is not compatible to the panel-me interface

### ISSUE THREAD

**Issue by cuifuyani** [AppliedEnergistics/Applied-Energistics-2#4153]
Applied Energistics version : appliedenergistics2-rv6-stable-7
IC2 version: industrialcraft-2-2.8.170-ex112

When i put the eject upgrade in the machine like compressor or extractor, and at the top of the machine, I place a panel-Me inteface and connect it to my MEnet, also i set the direction of the upgrade to the top, but the output did not go to the net. 

However, when i replace the panel interface by block interface, it worked. 

I thought it is a bug and i dont know whether it is the bug for ae or ic.
so .. 
If it can be fixed, do it!
Thanks!!

**Comment by mindforger** [comment]
>If it can be fixed, do it!

Very respectless

**Comment by cuifuyani** [comment]
I'm sorry if I made some mistakes..
I just start leaning English so there are some expressions that I do not really clear..

Thanks for correcting me！

**Comment by mindforger** [comment]
There was this issue https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2851

but is has never been resolved just closed at soe point unfortunately
