### ISSUE TITLE
Meteorites dont spawn in Nether

### ISSUE THREAD

**Issue by thetakodev** [AppliedEnergistics/Applied-Energistics-2#4154]
**Describe the bug**
Meteorites dont spawn in Nether when using Biome Bundle (OTG) for world generation

**To Reproduce**
Install OTG, Biome Bundle and AE2, configure AE2's meteorite whitelist to `-1` and generate a world using OTG and notice the lack of meteorites.

**Expected behavior**
Meteorites spawning in nether

**Environment**
- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-7
- Forge Version: 1.12.2 - 14.23.5.2847

**Comment by nictrace** [comment]
This is non a bug but feature! Nether has no sky, so meteorites can not falls
For worlds from another mods (like Galacticraft) I working hard for fix it)

**Comment by thetakodev** [comment]
But could underground meteorites spawn in nether? This would be a good option, as many people think of nether as a space under the overworld? Also maybe an option to disable falling meteorites, so they only spawn underground?

**Comment by nictrace** [comment]
No, it's totally banned in code (but I've forgot when)
