### ISSUE TITLE
Community Enhancements appreciated? (NBT Ignore and Interface Sorting changes)

### ISSUE THREAD

**Issue by tursi960** [AppliedEnergistics/Applied-Energistics-2#4156]
Hey, I am interested in contributing and while I'm proficient in coding, I haven't exactly worked much with GitHub.

If I add features like a new button that (like OreDictionary) ignores NBT data, will it get added? What if there's a toggle in the settings for it? Or similarly the ability to set a type of machine as the *upper* interface in the interface terminal and to shift click it in?

**Comment by yueh** [comment]
In general yes, any help would be gladly appreciated. But I would recommend contacting us before with a general idea. In case we have to reject them, it won't waste your time trying to implement it first.

In the specific case of ignoring NBT, most likely not. It was already rejected multiple times and would cause too many issues for us.

Not sure if I understand the second one correctly. But it sounds like an extreme niche case, which won't benefit many users while most likely affecting many normal players in a negative way.
