### ISSUE TITLE
[AE Crafting Calculator/WARN] [AE2:S]: Using CraftingManager fallback

### ISSUE THREAD

**Issue by daniil8803** [AppliedEnergistics/Applied-Energistics-2#4159]
- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv5-stable-11
- Forge Version: forge-1.12.2-14.23.5.2838-universal

[AE Crafting Calculator/WARN] [AE2:S]: Using CraftingManager fallback: Recipe <ic2:7> for output <1xic2.te@72> rejected inputs [1xtile.wood@0, 10xic2.cable@4, 1xtile.wood@0, 1xic2.re_battery@0, 1xic2.re_battery@0, 1xic2.re_battery@0, 1xtile.wood@0, 1xtile.wood@0, 1xtile.wood@0]. NOT FOUND, please report.

Do not create objects in which there is a battery from the IC2
And on the latest version of AE2 the same thing

**Comment by yueh** [comment]
This is more or less a warning for the modpack maker or maybe the mod developer. It just indicates that the crafting recipe encoded with the pattern is not accepting the requested inputs. Usually this happens in case some mods make their items indistinguishable for us.
