### ISSUE TITLE
JEI Search vs AE2 Search

### ISSUE THREAD

**Issue by JKIceman** [AppliedEnergistics/Applied-Energistics-2#4160]
Hi, 

i don't know if this is a bug or not, but when i search in JEI for example for the Ender IO Generators, i can put in the search box "@ende gen" and it shows me every item with "gen" in the name from any mod with "ende" in the name. When i try the same search in AE2 it shows shows me nothing after i put in space after "ende". Then sometimes it does not show the mod stuff, for example there is a mod "Mystical Agriculture Tiered Crystals". If i put in JEI "@tier" it only shows me the items of this mod, if i put the same thing in AE2 it shows me nothing even though items of that mod are in my system.

Modpack i tested this with: All the mods 3 Remix
Applied energistics: rv6-stable-6

**Comment by yueh** [comment]
Our search is way less sophisticated than the JEI one. E.g. it should threat the whole string after @ as the mod name and not split it at the space or similar features.

It's simply just a small part of AE compared to the major feature of JEI. And we have to deal with dynamic data. So the additional cpu utilization and memory JEI uses can be done once for a static approach, while we would have to do these things each time the network inventory changes and rebuild it. Which could easily take a couple seconds or even minutes on very large modpacks.
