### ISSUE TITLE
Issue with disabled channels - certain parts of network disappear

### ISSUE THREAD

**Issue by katubug** [AppliedEnergistics/Applied-Energistics-2#4161]
**Describe the bug**
My modpack has channels disabled. One of my players was reporting an issue where some of his items on certain storage cells were not properly appearing in the ME terminal. After he did some testing, we concluded that the issue was that channels were technically disabled (the Controller block was removed, etc), but that the network was still trying to operate as if they were enabled.

As far as I know, he is the only person on the server with a network large enough to encounter this issue.

As a temporary workaround, we have re-enabled channels on the server, and everything seems to be accessible now.

**To Reproduce**
My player did some fairly rigorous testing, and here were his findings:

> AE2 Channel Bug Testing
> 
> Channels config set to false
> Tested with 6 drives (full) and ME Terminal, no issues
> Tested with 7 drives (full) and ME Crafting terminal, intermittent issues
> Tested with 8 drives (full) and ME Crafting terminal, one of the drives, mostly at random between interacting with the ME crafting terminal would not show contents
> Tested between last 2 around 9 times but couldn't get a consistent result with getting it to occur on a single drive and was random, ME Crafting terminal never became inaccessible
> 
> Channels config set to true
> Utilising channels as intended had no issues (tested up to 16 ME Drives) and crafting terminal, drives showing offline when incorrectly using channels (as expected)

**Expected behavior**
We expected a larger amount of drives to be able to connect to the network with channels disabled.

**Additional context**
None to provide.

**Environment**

* **Minecraft version:** 1.12.2
* **Forge version:** forge-1.12.2-14.23.5.2838-universal
* **Modpack version** (links to current modlist): [1.7.1](http://enthusiasticraft.cf/modpack-update-1-7-1/#modlist)
* **Mod versions:** appliedenergistics2-rv6-stable-7

Please let me know if there is any other information I can provide! Thanks for your time. :)

**Comment by yueh** [comment]
Basically it is caused by the system running out of power.

**Comment by katubug** [comment]
Then why does it stop occurring when channels are re-enabled? Sorry to bother, just curious.

**Comment by yueh** [comment]
Less power needed.

**Comment by katubug** [comment]
According to my player, they are generating about 12k rf/t, and their system only uses about 380rf/t. Is it possible the issue was due to something other than power fluctuation?

**Comment by mindforger** [comment]
Disabling channels means you loose controllers and as far as I remember there are only few other blocks that maintain the power capacity. Are there any power cells in that system? Because power input of an me system is limited by capacity/tick

**Comment by katubug** [comment]
He reports there are two dense power cells in the system.
