### ISSUE TITLE
Constant server crashing every 5 mins

### ISSUE THREAD

**Issue by kamrantekkit** [AppliedEnergistics/Applied-Energistics-2#4164]
Server is constantly crashing every 5 mins. I checked the crash logs. And it seems something in my AE system is ticking longer then expected causing the server to crash. I do have a large AE system but i can not pinpoint what is causing the crash.

**Additional context**'
https://pastebin.com/HWLQb1uw

**Environment**
Multiplayer 

- Minecraft Version: 1.12.1
- AE2 Version: rv6-stable-6
- Forge Version: 14.23.5.2838

**Comment by yueh** [comment]
Please report all autocrafting related bugs directly to your modpack as most are using addons which intentionally break it.
