### ISSUE TITLE
AE2 terminals fail to show autocrafting tree

### ISSUE THREAD

**Issue by Anthios314** [AppliedEnergistics/Applied-Energistics-2#4165]
**Describe the bug**
for the past day, I have been crafting a lot of things in my Omnifactory world. Suddenly, the AE2 terminals have stopped allowing me to autocraft stuff from them. Luckily, I still have the ability to autocraft via a wireless terminal (Wireless crafting terminal from the mod with the same name). When I go to craft something on a terminal, at the point where the "crafting tree" is supposed to pop up, I get kicked out of the terminal. 

**To Reproduce**
I have NO IDEA why this wont work. All I remember is loading the world and this not working. 

**Expected behavior**
As with AE2 autocrafting, I click on an item i have none of and want to craft, and then the box for how many I want to make appears. I input the value (say, I want 2 illuminated panels), and then click the next. Then, it SHOULD show the crafting tree. "in order to make this in omnifactory, you need 3 quartz glass and 3 fluix plates. those can be made..." Then I should either get a notification that Im missing something, or that there isnt a CPU powerful enough to do it, or I click start, and it starts. 

**Additional context**
this is the Omnifactory modpack. Notable mods included are gregtech: community edition, enderIO, extra utils 2, Avaritia, extended crafting, storage drawers, and an incredibly hefty dose of contenttweaker. 

The config disables channels, the ME controller, and dense ME cables. 

95% of my AE2 system is wired using EnderIO Me conduits. 

Things I have tried to use to correct it:

1. breaking and replacing the terminal. 
2. restarting the game
3. using cheats via LAN mode
4. completely disconnecting my network and then reconnecting it.

a number of mods have been added, but I fail to see how any may affect AE2:

1. Laggoggles
2. Spark (lag finder mod)
3. "Exa's fixes", a bugfix addon to Omnifactory that fixes several bugs with the modpack. For more information, ping Exa in the omnifactory discord (https://discord.gg/7nEP9Zy). 

I should probably also note that this bug started occuring yesterday, and I installed Exa's bugfix pack about 2 weeks ago, so I doubt that it's the cause.

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-6
- Forge Version: forge-1.12.2-14.23.5.2838

- omnifactory version: 1.2.1 (+ Exa's fixes)

**Comment by yueh** [comment]
Please report all autocrafting related bugs directly to your modpack as most are using addons which intentionally break it.

**Comment by Anthios314** [comment]
addons that INTENTIONALLY break it? can I have an example?
