### ISSUE TITLE
ME glass cable material changes , tearing with light and shadow blocks

### ISSUE THREAD

**Issue by im3098** [AppliedEnergistics/Applied-Energistics-2#4166]
**Describe the bug**

Switching material packs causes 'ME glass cable' color changes
Use of light and shadow to cause block tearing directly
Test with MOD:'appliedenergistics2-rv6-stable-7.jar'
'OptiFine_1.12.2_HD_U_E3.jar'
Test pictures stored in China's BOS
Test preparation：(https://lkcj.cdn.bcebos.com/1%2F1.png)

Using R3D CRAFT 64X:(https://lkcj.cdn.bcebos.com/1%2F2.png)

Use Faithful 1.12.2-rv4:(https://lkcj.cdn.bcebos.com/1%2F3.png)

Remove material packs:(https://lkcj.cdn.bcebos.com/1%2F4.png)

Using light and shadow:(https://lkcj.cdn.bcebos.com/1%2F5.png)

Light and Shadows and Faithful 1.12.2-rv4：(https://lkcj.cdn.bcebos.com/1%2F6.png)

Turn off light and shadow：(https://lkcj.cdn.bcebos.com/1%2F7.png)

Turn off the Light and Shadows and Material Packs:(https://lkcj.cdn.bcebos.com/1%2F8.png)
**To Reproduce**

**Expected behavior**

**Additional context**

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-7.jar
- Forge Version:1.12.2-forge1.12.2-14.23.5.2768

**Comment by yueh** [comment]
We cannot really support optifine. It's closed source so we do not know how it changes the normal vanilla or forge rendering.
