### ISSUE TITLE
ae-mod.info wiki incredibly slow loading

### ISSUE THREAD

**Issue by Sinxar** [AppliedEnergistics/Applied-Energistics-2#4167]
#### Description
I'm sorry I don't know where else to report it.

Getting 30 second - 2 minute loading times per page with frequent failure to connect errors. Trying to get up to date mod information but the wiki is unusably slow.

I've tried it on Chrome, and Edge. I've had 2 others confirm it but I can only speak for my experience with it.

Is there anything I can do on my end to speed it up?

**Comment by gamewin1** [comment]
it's not just you, i've got fiber internet and it too is the only site that loads so freakishly slow.

**Comment by gamewin1** [comment]
https://web.archive.org/web/20190225010530/https://ae-mod.info/Text-List/

Found this workaround. It may not be the most up to date information, and not all of it may be archived, but it's better than nothing, and it certainly loads a lot quicker.

**Comment by yueh** [comment]
Not really under my control. Hopefully it resolves itself, otherwise it's probably so.
