### ISSUE TITLE
Cannot Retrieve the /dank/null/MK VI from the ME System (any storage cell)

### ISSUE THREAD

**Issue by Tukop** [AppliedEnergistics/Applied-Energistics-2#4168]
#### Description
I put my /Dank/null from the mod /dank/null into the ME system by accident as it is something that can help me carry me more items.
When i tried to retrieve the /dank/null/MK VI from the storage cells it was stored in, it wouldn't let me. 
#### Environment
So i tried to export it using a filter with the /dank//null in it, but it didn't work.
Using any type of exporter to retrieve the item from the system didnt work.
I identified the cell in which it was stored in and put it in a seperate ME network.
I tried again the Storage bus, export bus and the IO port to move the item, but it just doesnt.
Im not the only one that had this problem, my friend who plays on the same server ( Project ozone 3 version 3.1.44) also had the issue. 
We now have 2 /dank/null/MK VI stuck inside 2 different storage cells...

- Minecraft Version: 1.12.2
- AE2 Version:  appliedenergistics2-rv6-stable-7
- Forge Version: 14.23.5.2838

**Comment by yueh** [comment]
Astral sorcery bug/feature.
