### ISSUE TITLE
Shaders don't seem to work with cable facades

### ISSUE THREAD

**Issue by LegitLunatic** [AppliedEnergistics/Applied-Energistics-2#4170]
Whenever I load up any shaders, it completely bugs out the cable facades I have placed...
![2019-10-07_16 35 00](https://user-images.githubusercontent.com/54214356/66357004-05fae780-e922-11e9-9bb8-8487305584a4.png)

**Comment by yueh** [comment]
Shaders/Optifine are closed source, so we don't know what they might break.
