### ISSUE TITLE
[1.12.2] Some error is spam in my server

### ISSUE THREAD

**Issue by SamLam140330** [AppliedEnergistics/Applied-Energistics-2#4171]
**Describe the bug**
When no player is in the specific world (In this time is DIM-6), some error will generate and spam in the server console every second.

**Additional context**
https://pastebin.com/e0Ct5m6B

**Environment**
- Minecraft Version: 1.12.2
- AE2 Version: 1.12.2-rv6-stable-7
- Forge Version: 1.12.2-14.23.5.2847
- Sponge: 1.12.2-2838-7.1.7-RC3927

**Comment by yueh** [comment]
We do not support anything like Sponge or Bukkit officially. Only a standard forge environment.

Should you be able to reproduce it without it and in a new environment and save, please update the issue accordingly and we will reopen it.

**Comment by mindforger** [comment]
Also, this warning is generated by ic2
