### ISSUE TITLE
wrench doesn't work on crafting monitor

### ISSUE THREAD

**Issue by DoomSquirter** [AppliedEnergistics/Applied-Energistics-2#4174]
**Describe the bug**
used the certus wrench, eio, thermal wrenches.  rclick does nothing.  shift-rclick picks block.

**To Reproduce**
placed a couple crafting monitors inline with floor facing up and I can't rotate the text display

**Expected behavior**
Expected rotation

**Additional context**

**Environment**
appliedenergistics2-rv6-stable-7
ExtraCells-1.12.2-2.6.3aNIGHTLY
ae2stuff-0.7.0.4-mc1.12.2
pack: stoneblock 2
ssp
forge: 14.23.5.2846
mc : 1.12.2

**Comment by yueh** [comment]
They need to be locked to be rotated. Otherwise rightclick will configure the displayed item. That's simply the issue with having to support more actions than there are interaction options like right click with or without shift.
