### ISSUE TITLE
crashed while loading minecraft 

### ISSUE THREAD

**Issue by christianPRO2007** [AppliedEnergistics/Applied-Energistics-2#4176]
i was loading minecraft forge and i got a error while loading

- Minecraft Version:  1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-7
- Forge Version: 1.12.2-forge1.12.2-14.23.5.2847

[crash-2019-10-12_17.16.31-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/3720837/crash-2019-10-12_17.16.31-client.txt)

**Comment by mindforger** [comment]
Change the dimension id in the config, you have another mod using the same like ae2, also for future reports, use pastebin or gist gisthub to post the report and so not upload files
