### ISSUE TITLE
IGridBlock.getMachineRepresentation is not @Nullable

### ISSUE THREAD

**Issue by ruifung** [AppliedEnergistics/Applied-Energistics-2#4178]
Despite the interface itself claiming that the method *can* return null, returning null for this method will crash the game due to ContainerNetworkStatus.java:122 trying to call .isEmpty() on a null item stack.

**Comment by yueh** [comment]
Duplicate of #3925

**Comment by ruifung** [comment]
Well, yeah, probably should remove that @Nullable annotation on that interface and update its javadoc to say that it shouldn't be null (the javadocs say that null is an acceptable value.)
