### ISSUE TITLE
ME Interfaces not working properly

### ISSUE THREAD

**Issue by sagesse-cn** [AppliedEnergistics/Applied-Energistics-2#4179]
**Describe the bug**

The ME Interfaces Panel in the IC2 EXP can't use ejector upgrade and pulling upgrade input and output item, but ME Interface block is worked. 
I am not sure whether this is a issue of IC2 EXP or AE2.

**To Reproduce**

1: Build an AE2 network
2: Put an electric furnace and ME Interfaces Panel
3: Set the output items in the ME Interfaces Panel (such as iron ore)
4:  Put ejector upgrade and pulling upgrade in electric furnace

**Expected behavior**

Can't input and output items.
This worked fine if it is the ME Interfaces block.

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-7
- Forge Version: 14.23.5.2838

**Comment by Ommina** [comment]
#4153 

Short version as I understand it: IC2 sees the panel not as an inventory, but as a multipart (which it is).

**Comment by ruifung** [comment]
And also probably IC2 not utilizing the ItemHandler capability I guess,.?
