### ISSUE TITLE
Autocrafted parts in energy condensers are not extractable

### ISSUE THREAD

**Issue by Skavies** [AppliedEnergistics/Applied-Energistics-2#4182]
**Describe the bug**

version rv6-stable-7 from project ozone 3, kappa 3.1.44

If you have energy condensers from ProjectE with inventory/storage buses, it will sometimes try to place crafted items in the energy condensers.  This leaves you with items appearing in your me system as crafted, but not accessible.  You can see them, but you must take them out of the chest, not out of a terminal.

**To Reproduce**

attach a mk 1 energy condencer to your AE system with a storage/inventory bus (whatever it's called now, I hate it when items get renamed) and leave it with the same 0 priority as your me drives.  (setting priority to 1 or higher than your me drives most likely will force this).   Do not have your condenser set to make any objects, leave it like a chest.   Items that get stored in it will appear in your terminals but you can not take them out of the system from any terminal.

**Expected behavior**

I expect it to act like a normal chest where if you were to put an inventory/storage bus on it, the me system would use it like a storage drive.

**Additional context**

**Environment**

- Minecraft Version: 
- AE2 Version: 
- Forge Version:

**Comment by Skavies** [comment]
make that any item stored in an energy condenser that is not set to generate something will be visible, but not retrievable.    I was using them to make base materials for the autocrafting, and had a bank of them ready for new resources, when I found this.   THe ones producing resources from emc are outputting those resources correctly.   Like the iron ingot one is accessible from the me system, and I can pull iron out of it with any terminal, but if I were to put iron ingots in a condenser which is not set to make iron ingots, I will see them from a terminal, but not be able to extract or use them in auto crafting.

**Comment by mindforger** [comment]
i am a bit confused why they expose the item when they only accept items? Do barrels and similar storages with input filter work the same when empty?

**Comment by ruifung** [comment]
You could. IIRC storage busses have an option to not show non extractable items, and I'm pretty sure storage busses can be set to extract only mode, so they can only take items out but not put item in.

Also, I'm pretty sure nothing got renamed for years now, as I recall, AE1 had storage busses and interfaces too.

That being said, if the intention is to use it for autocrafting tasks, you use an interface + some method of getting items out of it and into AE (import bus, pipe into interface, etc.), I personally have *no* idea if depositing the results in a  storage bus inventory counts as I've never used it in that configuration.

**Comment by Skavies** [comment]
I didn't mean to use it as a storage.  I was using them to provide base resources for crafting projects.   Ingots, logs, redstone/glowstone/etc...    I was expanding it to provide other things when something I auto crafted was showing up in my me system, but I couldn't get it out.   Took me almost an hour to figure out where it ended up.
