### ISSUE TITLE
p2p tunnel memory card not linking tunnels. (and how to fix it)

### ISSUE THREAD

**Issue by Emsaic** [AppliedEnergistics/Applied-Energistics-2#4187]
Hey, I was having a problem with p2p tunnels, whenever I tried to shift right click a p2p tunnel with the memory card it would say "memory card cleared" instead of working.

I don't know if it has been fixed but I had a tinker's construct shovel in my offhand, once I removed it it worked as intended.

**Comment by mindforger** [comment]
you are missing all required informations on versions used, SP or MP and so on ... to properly help you, but i guess you just didn't know that you can also search already closed issues

https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4123

might be your answer, but that is just a guess
