### ISSUE TITLE
Just put a glass cable.

### ISSUE THREAD

**Issue by krestelll76** [AppliedEnergistics/Applied-Energistics-2#4188]
#### Environment

[crash-2019-11-02_11.00.35-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/3800152/crash-2019-11-02_11.00.35-client.txt)

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-7
- Forge Version: 14.23.5.2836

**Comment by yueh** [comment]
BetterHUD bug iirc.
