### ISSUE TITLE
AE2 won't let the game to launch

### ISSUE THREAD

**Issue by berkkrkc09** [AppliedEnergistics/Applied-Energistics-2#4189]
I am the owner of the "Quick Quack" pack on twitch desktop client. I was trying to relase a new version for my modpack. Just after i launch minecraft, game crashes and it says AE2 is the potential cause of the problem.

**Describe the bug**
AE2 mod crashes the game after the launch. 

**To Reproduce**
You need "Quick Quack" pack from [CurseForge](https://www.curseforge.com/minecraft/modpacks/quick-quack) and these mods: AbyssalCraft, Advanced Inventory, Advanced Mortars, Advanced World Selection, AnimalNet, Apocalypse Dimension, Armor Toughness Bar, Chainmail Armor Crafting Recipe Mod, ChickenShed 1.1x, Chisel, ConnectedTexturesMod, Duck Craft, Controllable, DeathQuotes / Death Quotes, Draw Bridge, Ducky Mod, Environmental Tech, EverlastingAbilities, EverlastingAbilities-PotionCore, Potion Core, Giselbaer's Durability Viewer, Grid, Hunting Dimension, Item Got, Item Scroller, Just Enough Buttons, JustTheTips, Lightning Rods, Loot Slash Conquer, Modular Powersuits, MystAgrad Cloche Compat, Numina, Overloaded Armor Bar, Real Time Clock, RFTools, RFTools Dimensions, RFTools Power, Storage Tech, The Twilight Forest, Wesley's Roguelike Dungeons, YUNG's Better Caves, **and all of the dependencies of the mods listed** (The latest versions of the listed mods including beta versions relevant to this date: 3.November.2019) +OptiFine_1.12.2_HD_U_F4

**Expected behavior**
I expected the game to launch into the title screen.

**Additional context**
Crash Log:  https://pastebin.com/pxXW2eQK
![javaw_Y1bBQEK63g](https://user-images.githubusercontent.com/57318309/68085427-0c617e00-fe52-11e9-8999-baa3b320843b.png)

**Environment**
Java x64 Build 1.8.0_231-b11  ----  Windows 10
The latest versions of the above listed mods including beta versions relevant to this date: 3.November.2019

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-7
- Forge Version: forge-14.23.5.2847

**Comment by berkkrkc09** [comment]
P.S. I was trying to relase a new version to my modpack

**Comment by mindforger** [comment]
>Failed to register dimension for id 2, One is already registered

Your pack config seems broken some other mod is using the same dimension id as ae2

**Comment by berkkrkc09** [comment]
can you find which mod does it ? Because these logs are a bit too technical for me. Thanks.

**Comment by Tahakk** [comment]
If you want to know start deleting mods or (if it is still a thing) just edit AE's dimension ID in config

**Comment by mindforger** [comment]
@yueh i can yet not remember which mod (but i think it was one of the COFH mods) which could spit out all registered blockIDs, DimensionIDs and such info associated with the specific mod! Could the Exception, thrown here, be made more specific to tell which other mod is using the ID for easier config?
