### ISSUE TITLE
Fluid formation plane not placing fluids into world

### ISSUE THREAD

**Issue by Darkmift** [AppliedEnergistics/Applied-Energistics-2#4190]
**Describe the bug**
tested with a minecraft world with only AE2 mod installed

https://media.discordapp.net/attachments/219142420112211981/640672012188254218/unknown.png?width=1202&height=677

- Minecraft Version: 
- AE2 Version: 1.12.2
- Forge Version:14.23.5.2847

**Comment by yueh** [comment]
Planes are similar to storage buses. If there are other places in the network with a higher priority to store the fluid (or item) available, it will prefer these until they are full.
