### ISSUE TITLE
Terminal textures broken

### ISSUE THREAD

**Issue by jusjudge** [AppliedEnergistics/Applied-Energistics-2#4191]
**Describe the bug**
I removed the channels in my private pack for the purpose of not having limitations. I finally am able to setup an AE2 system but the 2 types of cables I can use (when channels are removed) show the terminals with an almost rainbow effect.

**To Reproduce**
1. Remove channels
2. Use the two available types of cables to connect terminals to
3. Connect the terminals

It only happens when the terminals are powered or online.

**Expected behavior**
For it to show the white color or at least the color of the cable I am using on the terminal.
Even if it didn't show the color, for it to be the stock fluix purple color.

**Additional context**
I am using two resources packs but I am 99% sure that by now, they are compatible with AE2. I am using Faithful Vanilla and Faithful Modded.

This is a [screenshot](https://imgur.com/a/3tovOLC) of the broken texture.

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-7
- Forge Version: 14.3.5.2847

**Comment by yueh** [comment]
Most likely the usual optifine issues.
