### ISSUE TITLE
Energy Acceptor Limited to IC2C MV input

### ISSUE THREAD

**Issue by MachiavelliSeraphim** [AppliedEnergistics/Applied-Energistics-2#4193]
It appears that the Energy Acceptor can only handle Medium Voltage without exploding when using Industrialcraft 2 Classic.  

Forge 14.24.5.2587
AE2 rv6-Stable-7
IC2C 2.2.999

Not sure if this is by design or not.

Please let me know.
Thanks.

**Comment by sagesse-cn** [comment]
In Industrialcraft 2, the explosion is related to the tier level.
the tier level of the energy acceptor is indeed 1. 
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/c2d18ce0133a27d54a16d95a4f89f38dbc1a1bb1/src/main/java/appeng/integration/modules/ic2/energy/PoweredItemManager.java#L112
But I don't know is a "as designed"

**Comment by sagesse-cn** [comment]
Tier 0 is 32eu/t
Tier 1 is 128eu/t
Tier 2 is 512eu/t
Tier 3 is 2048eu/t
...

**Comment by MachiavelliSeraphim** [comment]
Thats what I was wondering.
Years ago, AE1 could handle high voltage (512 eu/t).  Since then Ive always used RF.

**Comment by MachiavelliSeraphim** [comment]
Tier 4 is 8192
Tier 5 is 32768

**Comment by yueh** [comment]
IC2 classic is simply breaking the normal IC2 api, while still claiming to be the same.

There is simply no way to distinguish between the IC2 and IC2 classic API and behave differently as long as IC2C does not introduce their own API.

**Comment by MachiavelliSeraphim** [comment]
Thats fine.  I just wanted to know if it was a MV only block when the old one was HV capable.  Thank you for the time.

**Comment by yueh** [comment]
It should accept pretty much any tier with IC2. We simply make use that the API has something like an autoranging, which will automatically scale it to the highest tier availabe. As far as I remember, IC2 classic simply does not like this and automatically sets it to some tier they consider "right" in their opinion.

**Comment by MachiavelliSeraphim** [comment]
Now the problem makes sense.
Thank you for the time.
Keep up tge good work :)
