### ISSUE TITLE
Annihilation plane deletes fire, even without storage

### ISSUE THREAD

**Issue by syntaxaire** [AppliedEnergistics/Applied-Energistics-2#4195]
Steps to reproduce:
1. Start a Creative Superflat world.
2. Place a Creative Energy Cell, ME Glass Cable, Quartz Fiber, ME Glass Cable, and Annihilation Plane, all in a straight row.
3. Light the space in front of the Annihilation Plane on fire with a Flint and Steel as many times as you want.

Expected behavior: Annihilation Plane only annihilates things it can buffer or store.
Actual behavior: Annihilation Plane always annihilates the fire.

- Minecraft Version: 1.12.2
- AE2 Version: rv6.stable build 7
- Forge Version: 14.23.5.2847

**Comment by Pingger** [comment]
Hi,

afaik not a bug. When "breaking" a fire it just doesn't yield any drops and thus can be "annihilated" even if no space is available. This also applies to other entities like tall grass

Greetings

**Comment by yueh** [comment]
Fire is basically a block which won't drop anything. So there is nothing to be stored, which technically can be stored. No idea if that should be considered a bug or feature...

**Comment by syntaxaire** [comment]
The use case for this is the new EnderIO Grains of Infinity crafting mechanic, which needs you to light some bedrock on fire, then spawns the Grains into the world. An Annihilation Plane would then bring them into the network.

Since the fire is deleted instead, a different mod is required to suck up the items.

**Comment by mindforger** [comment]
Or you use the vaccuum chest/hopper from EIO

**Comment by leagris** [comment]
Or maybe implement check in AE2, so that the annihilation plane calls getDrops and only harvests the block if getDrops returns actual items.

**Comment by Pingger** [comment]
> 
> 
> Or maybe implement check in AE2, so that the annihilation plane calls getDrops and only harvests the block if getDrops returns actual items.

No, as this could easily lead to item duplication, for stuff, that drops only sometimes actual items

**Comment by syntaxaire** [comment]
> 
> 
> Or you use the vaccuum chest/hopper from EIO

That's... exactly what I said in my post. Use another mod to suck up the items.

**Comment by mindforger** [comment]
> > Or you use the vaccuum chest/hopper from EIO
> 
> That's... exactly what I said in my post. Use another mod to suck up the items.

Sounded more like you meant a third mod.

**Comment by yueh** [comment]
I do not think it is worth to have a special case for fire. 

Also preventing blocks without any drops from being destroyed is most likely also an issue. E.g. in case some mod drops it as part of the block break event and not the actual block. Which would make it pretty much impossible to automate these.

In the case of EIO (that was what I had in mind initially), it is also worthless. I cannot remember how exactly it worked, but iirc they did drop on random ticks or the fire burning out by itself or something like this. In these cases the plane wouldn't even work. As it only breaks blocks or whatever item directly touches it. Thus it would only work, if the plane faces up and is lit itself, which in return wouldn't cause any EIO drops at all as it has to be bedrock. Or some extremely low chance, that it drops directly at the edge of the block and touches the plane. Which is pretty unlikely already and then pretty much falls apart in case the dropped item don't have a movement when being spawned.

Further there are so many other mods, which provide some magnet/vacuum blocks. I do not think we have to copy every single functionality out there. Simply allow it that these things can somehow work with AE2. And in case the mod itself does not provide a way to automate their own recipes, I would simply argue they want it to be done manually and not being automated.
