### ISSUE TITLE
A development questions

### ISSUE THREAD

**Issue by sagesse-cn** [AppliedEnergistics/Applied-Energistics-2#4196]
I use Intellij IDE development, exec the `gradlew genIntellijRuns` after, using `Applied-Energistics-2.main` configure run client. run is success, but it doesn't load any textures.
How fix its?

**Comment by ichbineinNerd** [comment]
if this is what I think it is: it's a common problem with newer versions of intellij, basically it just puts the resources in the wrong location. (You can verify that this is your problem by googling for "Forge intellij problems", you'll find something on the forge forums)

The fix seems to be to NOT delegate the build to gradle, by following [these instructions](https://www.jetbrains.com/help/idea/work-with-gradle-projects.html#delegate_build_actions)
