### ISSUE TITLE
Travis CI fails to execute SonarQube

### ISSUE THREAD

**Issue by Pingger** [AppliedEnergistics/Applied-Energistics-2#4198]
**Describe the bug**

CI is currently broken. Example: https://travis-ci.org/AppliedEnergistics/Applied-Energistics-2/jobs/610517076#L709
**To Reproduce**

https://travis-ci.org/AppliedEnergistics/Applied-Energistics-2/jobs/610517076#L709

**Expected behavior**

Properly running CI, that properly runs SonarQube?

**Additional context**

**Environment**

- Minecraft Version: N/A
- AE2 Version: rv6-1.12 (or whatever Travis uses ...)
- Forge Version: N/A

**Comment by yueh** [comment]
That is simply a Travis CI or SonarQube feature. Whatever you consider the one being broken.

There is simply no way to fix it except running your own CI and SonarQube instance. Which requires our own buildserver including maintenance und so on. And in my expierence every SonarQube update would completely break the current installation and require a reinstall and trying to restore the original database state somehow.
