### ISSUE TITLE
Matter Cannon Range 

### ISSUE THREAD

**Issue by bloche1871** [AppliedEnergistics/Applied-Energistics-2#4199]
The matter cannon acts as a melee weapon and has no effect beyond a short range (energy and ammunition are used but nothing happens beyond melee range, whether aiming at a block or mob). I assume it's supposed to be a ranged weapon instead.

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-7
- Forge Version: 1.4.23.5.2847

**Comment by yueh** [comment]
No idea actually. But in case it's actually caused by the linked forge bug, probably nothing we could really fix. And to be honest, I probably haven't ever tested the matter cannon since 1.7...

**Comment by yueh** [comment]
Should be fixed for 1.15+
