### ISSUE TITLE
TE Signalum & enderium equipment stuck in autocrafting

### ISSUE THREAD

**Issue by minenine** [AppliedEnergistics/Applied-Energistics-2#4203]
I have been having this problem in modpacks recently where the Signalum & enderium tier equipment specifically, from the TE mod will get stuck in autocrafting and the system will just refuse to craft the item
![image](https://user-images.githubusercontent.com/1365542/68979941-ad422880-07c4-11ea-8a42-054024d798ed.png)

two modpacks this has happened to me on is the Sky factory 4 and ATM3 but I think there are other that I don't remember off the top of my head. to reproduce just put the recipe for the signalum equipment of choice into an MA and deposit the necessary items and try to craft it to which it should just get stuck at the last step (if you have more then one step in the crafting).

- Minecraft Version:  1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-6.jar
- Forge Version:14.23.5.2838

**Comment by sagesse-cn** [comment]
Try to this version.
[appliedenergistics2-rv6-alpha-0.jar.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/3854004/appliedenergistics2-rv6-alpha-0.jar.zip)

**Comment by yueh** [comment]
Please report all autocrafting related bugs directly to your modpack as most are using addons which intentionally break it.
