### ISSUE TITLE
yo. My game started crashing today

### ISSUE THREAD

**Issue by BlackestChaos96** [AppliedEnergistics/Applied-Energistics-2#4204]
Every time I've tried to create a new world today, ae2 keeps causing the game to crash and it is the latest build. and I have the latest build of Minecraft forge

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CorePlugin (ForgeEndertech-1.12.2-4.4.22.2-build.0405.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.0.29.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.0.381.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 11/15/19 4:34 PM
Description: Exception in server tick loop

java.lang.IllegalArgumentException
	at net.minecraft.util.WeightedRandom.func_76273_a(SourceFile:18)
	at net.minecraft.util.WeightedRandom.func_76271_a(SourceFile:37)
	at net.minecraft.world.WorldEntitySpawner.func_77191_a(WorldEntitySpawner.java:266)
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185931_b(ChunkGeneratorOverworld.java:466)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:142)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 961116464 bytes (916 MB) / 2013265920 bytes (1920 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 50 mods loaded, 50 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version               | Source                                          | Signature                                |
	|:------ |:-------------------- |:--------------------- |:----------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2                | minecraft.jar                                   | None                                     |
	| LCHIJA | mcp                  | 9.42                  | minecraft.jar                                   | None                                     |
	| LCHIJA | FML                  | 8.0.99.99             | forge-1.12.2-14.23.5.2847.jar                   | None                                     |
	| LCHIJA | forge                | 14.23.5.2847          | forge-1.12.2-14.23.5.2847.jar                   | None                                     |
	| LCHIJA | forgeendertech       | 1.12.2-4.4.22.2       | ForgeEndertech-1.12.2-4.4.22.2-build.0405.jar   | None                                     |
	| LCHIJA | adlods               | 1.12.2-1.0.6.2        | AdLods-1.12.2-1.0.6.2-build.0408.jar            | None                                     |
	| LCHIJA | ctm                  | MC1.12.2-1.0.0.29     | CTM-MC1.12.2-1.0.0.29.jar                       | None                                     |
	| LCHIJA | appliedenergistics2  | rv6-stable-7          | appliedenergistics2-rv6-stable-7.jar            | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | aroma1997core        | 2.0.0.2               | Aroma1997Core-1.12.2-2.0.0.2.jar                | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHIJA | aroma1997sdimension  | 2.0.0.2               | Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.jar | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHIJA | cfm                  | 6.3.0                 | cfm-6.3.0-mc1.12.2.jar                          | None                                     |
	| LCHIJA | chesttransporter     | 2.8.7                 | ChestTransporter-1.12-2.8.7.jar                 | None                                     |
	| LCHIJA | codechickenlib       | 3.2.3.357             | CodeChickenLib-1.12.2-3.2.3.357-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | chickenchunks        | 2.4.2.74              | ChickenChunks-1.12.2-2.4.2.74-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | chisel               | MC1.12.2-0.2.1.35     | Chisel-MC1.12.2-0.2.1.35.jar                    | None                                     |
	| LCHIJA | redstoneflux         | 2.1.0                 | RedstoneFlux-1.12-2.1.0.6-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | cofhcore             | 4.6.3                 | CoFHCore-1.12.2-4.6.3.27-universal.jar          | None                                     |
	| LCHIJA | cofhworld            | 1.3.1                 | CoFHWorld-1.12.2-1.3.1.7-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | ctdcore              | 1.4.0                 | CTD-Core-1.12.2-1.4.0.jar                       | b50fe22651b9d97d9d6631514a6a57cd6174b0dc |
	| LCHIJA | cxlibrary            | 1.6.1                 | cxlibrary-1.12.1-1.6.1.jar                      | None                                     |
	| LCHIJA | elevatorid           | 1.3.6                 | ElevatorMod-1.12.2-1.3.6.jar                    | None                                     |
	| LCHIJA | extracells           | 2.6.3                 | ExtraCells-1.12.2-2.6.4.jar                     | None                                     |
	| LCHIJA | fairylights          | 2.1.9                 | fairylights-2.1.9-1.12.2.jar                    | None                                     |
	| LCHIJA | silentlib            | 3.0.12                | SilentLib-1.12.2-3.0.12+165.jar                 | None                                     |
	| LCHIJA | funores              | 1.6.3                 | FunOres-1.12.2-1.6.3-124.jar                    | None                                     |
	| LCHIJA | hopperducts          | 1.5                   | hopperducts-mc1.12-1.5.jar                      | None                                     |
	| LCHIJA | jei                  | 4.15.0.268            | jei_1.12.2-4.15.0.268.jar                       | None                                     |
	| LCHIJA | malisiscore          | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                    | None                                     |
	| LCHIJA | malisisdoors         | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                   | None                                     |
	| LCHIJA | mekanism             | 1.12.2-9.8.0.381      | Mekanism-1.12.2-9.8.0.381.jar                   | None                                     |
	| LCHIJA | mekanismgenerators   | 1.12.2-9.8.0.381      | MekanismGenerators-1.12.2-9.8.0.381.jar         | None                                     |
	| LCHIJA | mekanismtools        | 1.12.2-9.8.0.381      | MekanismTools-1.12.2-9.8.0.381.jar              | None                                     |
	| LCHIJA | moglowstone          | 1.5.6                 | Mo-Glowstone-1.12.2-1.5.6.jar                   | b50fe22651b9d97d9d6631514a6a57cd6174b0dc |
	| LCHIJA | moreexplosives       | 1.0.2                 | More+Explosives+V1.0.2.jar                      | None                                     |
	| LCHIJA | multipagechest       | 1.9.1                 | MultiPageChest-1.12-1.9.1.jar                   | None                                     |
	| LCHIJA | nei                  | 2.4.3                 | NotEnoughItems-1.12.2-2.4.3.245-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | oreexcavation        | 1.4.140               | OreExcavation-1.4.140.jar                       | None                                     |
	| LCHIJA | placebo              | 1.4.1                 | Placebo-1.12.2-1.4.1.jar                        | None                                     |
	| LCHIJA | plants2              | 2.10.3                | Plants-1.12.2-2.10.3.jar                        | None                                     |
	| LCHIJA | shearmadness         | 1.12.2                | shearmadness-1.12.2-1.7.2.4.jar                 | None                                     |
	| LCHIJA | speedyhoppers        | 1.1.19                | speedyhoppers-1.1.19.jar                        | None                                     |
	| LCHIJA | thermalfoundation    | 2.6.3                 | ThermalFoundation-1.12.2-2.6.3.27-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermalexpansion     | 5.5.4                 | ThermalExpansion-1.12.2-5.5.4.43-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermaldynamics      | 2.5.5                 | ThermalDynamics-1.12.2-2.5.5.21-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | bspkrscore           | at_0.9                | Treecapitator-1.12-at_0.9a.jar                  | None                                     |
	| LCHIJA | treecapitator        | at_0.9                | Treecapitator-1.12-at_0.9a.jar                  | None                                     |
	| LCHIJA | unlimitedchiselworks | 0.2.4                 | UnlimitedChiselWorks-0.2.4.jar                  | None                                     |
	| LCHIJA | usefulcows           | 1.0.4                 | usefullcows-1.0.4.jar                           | None                                     |
	| LCHIJA | worldedit            | 6.1.8                 | worldedit-forge-mc1.12-6.1.8-dist.jar           | None                                     |
	| LCHIJA | zerocore             | 1.12.2-0.1.2.8        | zerocore-1.12.2-0.1.2.8.jar                     | None                                     |

	Loaded coremods (and transformers): 
CorePlugin (ForgeEndertech-1.12.2-4.4.22.2-build.0405.jar)
  
CTMCorePlugin (CTM-MC1.12.2-1.0.0.29.jar)
  team.chisel.ctm.client.asm.CTMTransformer
MekanismCoremod (Mekanism-1.12.2-9.8.0.381.jar)
  mekanism.coremod.KeybindingMigrationHelper
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  cubex2.cxlibrary.CoreModTransformer
CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:OFF, JEI:ON, Mekanism:ON, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Pingger** [comment]
Hi,
sorry, but this doesn't look like it has to do with AppliedEnergistics. In fact, it looks like it isn't connected to any mod at all. 
It seems, for some reason OpenGL (that thing, that sends instructions to your GPU, to make images appear on your screen) can't find its "context" for sending its instructions. Maybe your GraphicsDriver went haywire?

Or maybe one of the CoreMods might be at fault. Coremods can alter the vanilla Minecraft behaviour and sometime causes weird bugs, that don't seem to be related to any mod.

As we had another user having issues (not GPU related) with MalisisCore yesterday, which isn't resolved yet, it might be, that a recent update broke something.

Maybe you can backup your world and try opening it with only forge and ae2 enabled?

Greetings

**Comment by BlackestChaos96** [comment]
OK so I went into the customization menu when creating a new world and turned off the dungeons, temples, and mineshafts and it seems to be working so far
