### ISSUE TITLE
ME Fluid Level Emitter is not working

### ISSUE THREAD

**Issue by Ioandar** [AppliedEnergistics/Applied-Energistics-2#4207]
The ME Fluid level Emitter is not changing state depending amount stored in ME system

**Describe the bug**
The ME Fluid level Emitter is not changing state depending amount stored in ME system

There is no Entry for the ME Fluid Level Emitter in the linked Wiki of AE2
I assume it works like the Level Emitter for Items (which works fine)

**To Reproduce**
Fill Fluid Storage with certain amount
Place ME Fluid Emitter
Set the threshold in GUI
Set the Liquid in GUI

Change the amount of fluid or the threshold 
Nothing changes, the Fluid Level Emitter always stays on (emit redstone signal)

**Expected behavior**
ME Fluid Emitter is changing state (like the ME Level Emitter does) when passing threshold

**Additional context** 
Fill in Fluids
<a href="https://ibb.co/1rnY3t3"><img src="https://i.ibb.co/gS7bGLG/2019-11-19-08-26-02.png" alt="2019-11-19-08-26-02" border="0"></a>

Place Fluid Level Emitter
<a href="https://ibb.co/TbRZ8Cv"><img src="https://i.ibb.co/Jy2N7hB/2019-11-19-08-25-30.png" alt="2019-11-19-08-25-30" border="0"></a>

Set GUI (Threshold/Liquid
<a href="https://ibb.co/HFXYq7j"><img src="https://i.ibb.co/gj6wJyx/2019-11-19-08-27-45.png" alt="2019-11-19-08-27-45" border="0"></a>

State never changes. Stays Redstone active
Same behavior in SP World with only mods are AE2 and JEI
<a href="https://ibb.co/4Zb56By"><img src="https://i.ibb.co/WWrYbS9/2019-11-19-20-48-21.png" alt="2019-11-19-20-48-21" border="0"></a>

no crash

**Environment**

Single Player World

- Minecraft Version: 1.12
- AE2 Version: rv6.stable build 7
- Forge Version: 14.23.5.2847

**Comment by Ommina** [comment]
I'm am NOT 100% confident on this, but please check if the Fluid Level Emitter units are in mb, while the terminal is is buckets.

**Comment by Ioandar** [comment]
Oh, I will check on that right meow!

**Comment by Ioandar** [comment]
> 
> 
> I'm am NOT 100% confident on this, but please check if the Fluid Level Emitter units are in mb, while the terminal is is buckets.

This is it! 
* Level Emitter works in/with buckets
* Fluid Level Emitter works in millibuckets

Fluid Level Emitter GUI should reflect that by adding "mb" or using a decimal maker or both

puzzled me way longer that I am willing to admit . Thank you for your quick answer!
I close this now but I think a little reminder in the GUI would be great!

**Comment by omblivion** [comment]
I really suggest adding some way to communicate this to the player, me and friends encountered the same issue and we struggled to understand why it wasn't working
