### ISSUE TITLE
Support for 1.14?

### ISSUE THREAD

**Issue by TheBigerGamer** [AppliedEnergistics/Applied-Energistics-2#4208]
I've opened this because I just **love** this mod. This is the mod I always include it on my modpacks. And I love 1.14.4 version. And I want to know if you're already developing it for 1.14.4.

And before you ask, yes. I've saw the closed issues about 1.14, and they still don't answer my question.

In this: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4099 you said forge 1.14 don't have a stable version. Well, now it has! So, can you please update it to 1.14.4?

**Comment by 34486** [comment]
I agree, but they will choose to update or not. They simply can not do it faster than they would anyways, ane its not just 'update' they gotta do a lot of crap to get a build working on 1.14.4

**Comment by bookerthegeek** [comment]
It will update when it updates.
