### ISSUE TITLE
[BUG] Already building!?

### ISSUE THREAD

**Issue by ExitCore** [AppliedEnergistics/Applied-Energistics-2#4209]
**Describe the bug**
 Not known.

**To Reproduce**
Not known.

**Expected behavior**
Every time I click on any terminal it take a few seconds then crashes for some reason.

**Additional context**
[Crash Report](https://paste.dimdev.org/amosayesop.mccrash)

- Minecraft Version:  Minecraft 1.12.2
- AE2 Version:  Applied Energistics 2 RV6 Stable 7
- Forge Version: 14.23.5.2847 and Lower

**Comment by Ommina** [comment]
1.12.2 is starting to age now, but try without Optifine.

**Comment by ExitCore** [comment]
> 1.12.2 is starting to age now, but try without Optifine.

Im not to sure but I got it working just by a restart minecraft. lol
Plus optifine is still installed and thank you anyway.

**Comment by Ommina** [comment]
Fair enough.  Probably best to just close up this issue then.
