### ISSUE TITLE
Memory Card not working

### ISSUE THREAD

**Issue by Bronze5yasuomain** [AppliedEnergistics/Applied-Energistics-2#4211]
Memory card cannot detect p2ps or even any ae2 item as a valid machine when right clicked on a p2p it says invalid machine. It is able to clear memory on shift + right click.

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-7
- Forge Version: forge-14.23.5.2847

**Comment by Tahakk** [comment]
You have to SHIFT + RIght click the tunnel first, than by right clicking on the other tunnels you are connecting them together

**Comment by BerdinskiyBear** [comment]
Sometimes memory card will not work if you have any items in your off-hand

**Comment by Bronze5yasuomain** [comment]
yea tried it with no items in off-hand while shift-right clicking it. It worked thank you.

**Comment by yueh** [comment]
Forge/Vanilla bug. Nothing we can really do about it.
