### ISSUE TITLE
nuggets don't work if its a complex patern

### ISSUE THREAD

**Issue by Anora** [AppliedEnergistics/Applied-Energistics-2#4214]
nuggets don't work if its used in a complex pastern dose not affect all nuggets
so when i qu up something  whit specifically copper or lead nuggets it will say cant complete even dough the pattern exist for those
**Describe the bug**

build a system that uses lead and copper(nugget) in a pattern
**To Reproduce**

**Expected behavior**

expected it to craft the item's in question, no error in error log

**Additional context**

**Environment**

mineos 24GB of ram 6core cpu
all mods in paste bin
https://pastebin.com/j4C054J5

server

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-7 
- Forge Version:14.23.5.2847

**Comment by Pultex** [comment]
just asking is this a modpack or something you made?
