### ISSUE TITLE
Ticking world?

### ISSUE THREAD

**Issue by Pultex** [AppliedEnergistics/Applied-Energistics-2#4216]
**Describe the bug**
crash on AE chunck unload not sure 

**To Reproduce**
enter chunk with AE system
leave chunk AE system

**Expected behavior**
move from chunk to chunck without server freeze

**Additional context**
crash log
https://paste.dimdev.org/hepakijijo.rb

**Environment**
SP world
Enigmatica 2 Expert mod pack

- Minecraft Version: 
- AE2 Version: appliedenergistics2-rv6-stable-7
- Forge Version: 1.12.2-forge1.12.2-14.23.5.2847

Question:
Maybe I am over loading the chunk
Should the AE system be all by itself
In one chunk
I have 64 Me Interfaces
6 p2p connected to several different chunks
do chunk loaders cause issues with AE as one is on it

**Comment by yueh** [comment]
This basically indicates that some addon is incorrectly accessing the network storage. But sadly there is no way to identify which one it actually causes.

The best idea would be to remove AE2 related addons in case you can reliably reproduce it and until it stops crashing. If then adding the removed addon again and it starts to crash again, it's most likely the culprit.
