### ISSUE TITLE
Server crash "Exception ticking world entities"

### ISSUE THREAD

**Issue by 04Slash** [AppliedEnergistics/Applied-Energistics-2#4217]
**Describe the bug**
There is a small chance that when leaving my base the SP server will crash. This happens right around when the "main area" of my AE system gets de-rendered.

**To Reproduce**
Unsure exactly how to reproduce as it doesn't happen every time, but it only happens when I reach a certain distance from my base/ where the AE system is set up.

**Expected behavior**
To leave the base without the game/server crashing.

**Additional context**
[A screenshot](https://imgur.com/a/9Uw6aHp) of the "main area" of my AE system, the part I presume causes the crashing when de-rendered, as well as the network tools summary of the entire AE system. All non-AE blocks have been stripped to get a clear view of the system (Excluding conduits because they're mentioned in the crash report). 
[Crash log](https://paste.dimdev.org/pazesuyamu.sql)
Same issue as #4216 ?

**Environment**
SP world
Omnifactory with [these mod changes](https://paste.dimdev.org/inekegagih.css)

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-7
- Forge Version: Forge-14.23.5.2847 (Release)

**Comment by Pultex** [comment]
Yes it is odd seems random too, or maybe seasonal not sure, for me at least
It seems to be on unload of the AE system render for me
same error as above

**Comment by 04Slash** [comment]
> Also just thought of it, have you tried TP away from the location and back
> 
> For me if you use an item that moves you clear way from the position you are at
> where your avatar/character does not actually move from direction controls
> The error happens less [though might just be a perceptional illusion]

Yea, it happens when both leaving the area by flying away, and using the Dislocator from Draconic evolution. I don't leave the area enough by flying away to notice if there is a difference, but the issue doesn't happen all that often for me to really test it.

**Comment by yueh** [comment]
Not the exact same, but pretty likely to be caused by the same addon. Maybe comparing the modlist might help to identify it?
