### ISSUE TITLE
Unknown Crash Reason

### ISSUE THREAD

**Issue by LonelySauce** [AppliedEnergistics/Applied-Energistics-2#4219]
[crash-2019-12-09_00.15.52-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/3937999/crash-2019-12-09_00.15.52-client.txt)

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergestics2-rv6-stable-7
- Forge Version: 1.12.2-forge1.12.2-14.23.5.2847

I'm not sure as to what caused the crash, I'm not very good at debugging this kind of stuff so here's the crash string I got in the launcher:

appeng.api.storage.ICellRegistry.getCellInventory(Lnet/minecraft/item/ItemStack;Lappeng/api/storage/ISaveProvider;Lappeng/api/storage/IStorageChannel;)Lappeng/api/storage/IMEInventoryHandler;

It mentioned something about an "MEInventoryHandler" at the end so I thought it had something to do with AE2. Something to note is that I am running AE2 in a modpack with 200+ active mods though I hope you guys can help me out with this so I know how to fix it.

**Comment by Ommina** [comment]
`at com.thiakil.appliedfluidics.item.ItemFluidicStorageCell.func_77624_a(ItemFluidicStorageCell.java:150)`

This is an add-on to an earlier version of AE2 to include fluid support.  As AE2 now supports fluids natively, I would suggest Fluidics is no longer necessary.

Indeed, you'll note the CurseForge page for Applied Fluidics explicitly states "**Not compatible with AE2 RV6!**"

**Comment by LonelySauce** [comment]
Well that's a facepalm moment for me.
I really need to read up on mods before I install them even on impulse, thanks for your help and I'll be closing this issue to further replies.

-Lonely

"Well, that was idiotic..."
