### ISSUE TITLE
Issue of the ME import / export bus with fuzzy card

### ISSUE THREAD

**Issue by snow6326** [AppliedEnergistics/Applied-Energistics-2#4224]
#### Description
I was testing in the creative mode to try to implement a automatic cooling system for the Nuclear Reactor from Industiralcraft. However, some issue was encountered when configuring the ME export and import bus. 
The mode of import bus was configured to 50% damage detection, but the LZH-Condensator with full durability still pulling out from the Nuclear Reactor and keep looping from export bus.
![擷取333](https://user-images.githubusercontent.com/57866808/70993300-afbad980-2106-11ea-8e52-a0c1c33535cf.PNG)

Sorry for my bad English :)

#### Environment
Forge Mod Loader version 14.23.5.2847 for Minecraft 1.12.2 loading
- AE2 Version: appliedenergistics2-rv6-stable-7
- Industiralcraft Version: Industrialcraft-2-2.8.170-ex112

**Comment by sagesse-cn** [comment]
try this pr #4194

**Comment by yueh** [comment]
The damage split only defines at which point it splits. But the item will actually decide which half it will operate on.

E.g. with setting it to 50% and having an item with >50% dmg, it will act on every item, which has 50-100% damage value. An item with less damage will then select items in the range of 0-50%.

[See this for more information](https://ae-mod.info/Fuzzy-Card/)
