### ISSUE TITLE
Polygon on termanals

### ISSUE THREAD

**Issue by madpanda334** [AppliedEnergistics/Applied-Energistics-2#4226]
So i am plating a twich mod pack called Automaton and all my ME stuff looks off like polygons for terminals and my ME drives lights arnt working along with the ME controller and I have no idea on how to fix it ive tryed restarting my game but no luck and messed with my settings to see if that fix it but it still broken

![15767048967244280492307281785950](https://user-images.githubusercontent.com/59033010/71125133-446f1700-219b-11ea-9e55-f992aa759468.jpg)

![15767049655441962556621585809476](https://user-images.githubusercontent.com/59033010/71125184-5fda2200-219b-11ea-8467-4027c1ad7a8b.jpg)
 
 It says all my stuff is set up right i can still use them but it just keeps bugging me.

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-3
- Forge Version:8.0.99.99

**Comment by mindforger** [comment]
I have seen something similar happening with enderio, do you have any issues with EIO blocks?

**Comment by yueh** [comment]
Most likely some Optifine or other FPS "enchanting" mod related issue.

**Comment by madpanda334** [comment]
> I have seen something similar happening with enderio, do you have any issues with EIO blocks?
> 
> Edit: whoops finger was too fat, did not want to close there
