### ISSUE TITLE
Wrenches Not Breaking Cables When Using Shift-Right Click

### ISSUE THREAD

**Issue by dscyrux** [AppliedEnergistics/Applied-Energistics-2#4229]
**Describe the bug**
I was doing some work on my ME system. I was removing some cables with the shift-right click function with my Crescent Hammer from Thermal Expansion, then one of the cables I was removing just disconnected from one of the other cables it was connected to. I think it had a cable anchor next to it. After this occurred, I could not pick up any cables the same way. I could still interact with other AE2 machines, like the drives and controllers, but I could no longer do it to the cables. I tried other wrenches, including the Certus Quartz Wrench, but it still would not work.

https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3710
It looks like this person had a similar issue, though I was still able to shift-right click other machines. His solution of unchunkloading, leaving the area, then relogging did not work for me. A full server restart was required to remedy this.

**To Reproduce**
I have absolutely no clue how to reproduce this error. 

**Expected behavior**
The expected behavior was for the wrench to pick up the cables as it had been previously doing.

**Environment**
FTB Revelation v3.2.1
SMP

- Minecraft Version: 1.12.2
- AE2 Version: rv6_stable_7
- Forge Version: 14.23.5.2846

**Comment by yueh** [comment]
Works fine for me with the normal certus wrench as well as the crescent hammer.

Maybe your modpack contains some protection mod, which prevents you from interacting with blocks under some conditions?

**Comment by dscyrux** [comment]
The modpack does have FTB Utilities. However, there had been a chunkloaded protection over the area since I had set up base there (a few days). No change occurred with the protection to my knowledge.

Something more specific about what occurred at the moment of the issue: It happened in the middle of removing some wires, and when it happened, the wire I was trying to break disappeared for a split second, then popped back, unconnected to the wires around it. From that point on I was unable to shift-right click AE2 wires to remove them until a full server restart.

It seems to me something went wrong server-side, but I couldn't tell you what would make it so that I would be unable to remove any further wires.

**Comment by yueh** [comment]
Sounds like something is reacting to it. E.g. something failed when trying to remove it and it tried to restore the original state and block any further interaction of the same type. With some luck, there might be a log entry the moment it happens, which could help to narrow it down,
