### ISSUE TITLE
Colourable Machines.

### ISSUE THREAD

**Issue by APasz** [AppliedEnergistics/Applied-Energistics-2#423]
Could be used to say divide up a double side bank of drives so one side is say green and the other is say red so channels are able to get to all drives, It would fix issue #308, http://tinypic.com/view.php?pic=29xhnd4&s=8#.VGP6rvmUfwo, http://tinypic.com/view.php?pic=15f23i0&s=8#.VGP6r_mUfwo

**Comment by Technici4n** [comment]
Not going to be implemented.
