### ISSUE TITLE
Questions about plotworld

### ISSUE THREAD

**Issue by qyanlongfeng** [AppliedEnergistics/Applied-Energistics-2#4230]
Hello, I have a question for you. My English is not good, so I use a translator. Sorry. Is such that. The name of my plot world in the server is plotworld. But after installing AE2, the sky of the earth's world has become black, and the sky of other dimensions is no problem. Later I discovered that it was a problem with AE2. I would like to ask if I can close the closed space or not load it by modifying the configuration file from the beginning. Otherwise the sky of my land is always black.

**Comment by yueh** [comment]
No idea really. I would recommend asking the modpack itself. Most likely their dimension system does not work correctly when a now mod with a new dimension is added and will then pick a random skybox.
