### ISSUE TITLE
Modpack doesnt load.

### ISSUE THREAD

**Issue by runerterra1** [AppliedEnergistics/Applied-Energistics-2#4231]
So, i made a modpack, game didnt load, and it crashed, when i looked into the file (im really new to this) AE2 was in the crash txt file so im posting it here, i honestly dont know what the text means though
**To Reproduce**
Honestly, Dont know

**Expected behavior**
The modpack to open

**Additional context**
heres the txt file https://pastebin.com/buTq4ye5
**Environment**
Basically, mods are Thaumcraft, Thermal Foundation, Tinkers, Blockcraftery Ender IO Mekanism Railcraft Translocators Dinamic Trees + Biomes o Plenty Ender Storage Mowzies mobs Decocraft, Chisel Industrial Craft 2 Botania and RFTools, 

- Minecraft Version: 1.12.2
- AE2 Version: R511
- Forge Version: Newest 1.12.2 version

**Comment by Ommina** [comment]
The version of AE2 that you have installed is really quite old indeed.  Given that the exception is being thrown inside the API, I expect one of the other mods is expecting a newer version than you are giving it.

Switch to rv6 build 7 and see how it goes.

**Comment by runerterra1** [comment]
K, crashed again, this is the log https://pastebin.com/3yswx9C8

**Comment by mindforger** [comment]
To me it kinda looks like a broken translation, in what language do you play? Does it work when you launch in english? What is you language setting of your system?

**Comment by runerterra1** [comment]
the language of my pc is in spanish, but I usually play minecraft in enlgish

**Comment by runerterra1** [comment]
however the launcher i use for modded is in spanish

**Comment by mindforger** [comment]
Can you try with the original?

**Comment by runerterra1** [comment]
ok, tried with original, this was the crash log https://pastebin.com/Zgtv88hx

**Comment by mindforger** [comment]
> OutOfMemoryError

You need to assign more ram, check the settings of the launcher

**Comment by runerterra1** [comment]
k, putting 6gb im going to see how it goes

**Comment by runerterra1** [comment]
crashed again, this is the log https://pastebin.com/v4tGAvMs

**Comment by Ommina** [comment]
You've reverted back to rv511, why?  ThaumicTerminal explicitly states it doesn't work with that version.

But that's not the weird bit -- the error message is stating the function `net.minecraft.util.text.translation.I18n.translateToLocal` doesn't exist.  That's vanilla code, being called from the AE2 API code.  And it bloody well does exist, I just checked.

At any rate, this isn't an AE2 issue.

**Comment by runerterra1** [comment]
sorry, friend told me to do that, i dont know why the vanilla code doesnt exist though, i play vanilla ll the time so thats wierd

**Comment by runerterra1** [comment]
redownloaded rv6 build seven in another site, it worked! thank you for helping!
