### ISSUE TITLE
Annihilation plane does not destroy blocks on the spongeforge

### ISSUE THREAD

**Issue by bigenergy** [AppliedEnergistics/Applied-Energistics-2#4232]
**Describe the bug**
Annihilation plane does not destroy blocks on the SpongeForge server

**To Reproduce**
To build Annihilation plane in GriefPrevention/GriefDefender claim

**Expected behavior**
Annihilation plane must destroy blocks inside user claim

**Additional context**
I contacted the developer GriefPrevention/GriefDefender plugin. 
Here is what he said:
![image](https://user-images.githubusercontent.com/17977139/71416466-99b29900-2671-11ea-9991-8e6b41117199.png)
https://gist.githubusercontent.com/bloodmc/8957056fccc4416a014de39b2ced14e3/raw/1b9ab882771c912d3df8835515da4ce10d068860/AE2_issue.txt

**Environment**
- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-7
- Forge Version: forge-1.12.2-14.23.5.2847
- spongeforge-1.12.2-2838-7.1.8-RC3965

**Comment by mindforger** [comment]
Why did you close it? Though SEi
