### ISSUE TITLE
Storage Location

### ISSUE THREAD

**Issue by DJKenzoDE** [AppliedEnergistics/Applied-Energistics-2#4235]
Good Day everyone,

i must switch the miencraft server to a other dedicated system with a new world,
i will copy player inventories (no problems) but where is the file that storage the items in i.e. a 64k me storage cell?

Nice Greetz from Germany for your hard work.

**Comment by yueh** [comment]
These are simply part of the world itself. And there is pretty much no guarantee that they might survive a transfer to a new one.
