### ISSUE TITLE
Gamecrash while searching in Terminal 

### ISSUE THREAD

**Issue by Nedogin** [AppliedEnergistics/Applied-Energistics-2#4237]
If I search for "tan" (tank) in the terminal or scroll down my game crashes.

[crash-2020-01-02_17.16.35-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/4016527/crash-2020-01-02_17.16.35-client.txt)

List of Mods: https://docs.google.com/spreadsheets/d/1gvz2XUaJwBr_TvasPZ7vOXZutBv2noSaUIrzgj80auQ/edit?usp=sharing

**Comment by mindforger** [comment]
Can you try without optifine?

**Comment by Nedogin** [comment]
great! it's working again. Thanks for the really quick answer.  So it seems to be related to the current version of Optifine (OptiFine 1.13.2 HD U F5)
