### ISSUE TITLE
Craft hotkey from JEI

### ISSUE THREAD

**Issue by dav9670** [AppliedEnergistics/Applied-Energistics-2#4238]
**Describe the feature**

Use the hotkey to craft items inside the ME Terminal to open the crafting dialog from inside JEI, if the item is craftable. 

For example, inside JEI, I want to craft a dispenser, which takes a bow, and the bow itself takes sticks. Both are currently auto-craftable in my system, but I have none in stock. What I would like to be able to do is use the auto-craft hotkey inside JEI to be able to summon the auto-crafting dialog for the bow, and after confirming the number to craft, to be returned to the JEI page I was at.

**Reasons why it should be considered**

The goal would be the reduce the back and forth needed to craft items which already have their components auto-craftable in the system. Instead of having to quit JEI to search for the component, craft it, and then come back to the actual recipe, all the steps could be done without quitting JEI.

**Additional Context**

I want to craft a dispenser. I do not have a bow in my ME system, but it is auto-craftable
![edit](https://user-images.githubusercontent.com/8339708/71702666-cd42a100-2d9e-11ea-9be4-1e352fe9b7a2.PNG)

After pressing the craft hotkey, the following dialog would open :
![image](https://user-images.githubusercontent.com/8339708/71702690-e8adac00-2d9e-11ea-876a-bf85ca64241a.png)

Once "Next" is clicked, we would be taken back to the first image.

**Comment by yueh** [comment]
This would somewhat clash with the design goal of autocrafting. Basically the idea is to create patterns for autocrafting and not having the player craft everything by hand. Even if it might be a quality of life features. Think of making manual crafting a bit more tedious to encourage using patterns.

Also in many cases it will not work. Items displayed in JEI are often actually invalid, missing data real items don't have. Or having extra data, which real ones won't have and similar. These things cannot be ignored as the same feature is used by many mods to distinguish between the real items. So on some cases it might work for some mods, while it then would craft something completely different when requesting an item from another mod. E.g. wanting to craft a metal ingot would suddenly craft some random machine.

And further, I am not even aware that we could hook into JEI in this way. It is a completely different system, which we cannot influence at all. Except JEI allows us to explicitly do it. For example the recipe transfer button. Which in my memory is not an option to hook into random JEI slots.
