### ISSUE TITLE
recipes broken - server crashes and uses obsidian essence in each recipe ...

### ISSUE THREAD

**Issue by jannik2103** [AppliedEnergistics/Applied-Energistics-2#4239]
Hello there,

we've automated a ressource farm with ae2 recipes and Mystical Agriculture.
In the end of the automation the essences are crafted automatically into items.

Since some days our server crashes with some of the following server warns:
"[39;0m> 
[K[33;1m[01:11:18] [Server thread/WARN] [AE2:S]: Using CraftingManager fallback: Recipe <mysticalagriculture:diamond> for output <1xitem.diamond@0> rejected inputs [1xitem.ma.diamond_essence@0, 1xitem.ma.diamond_essence@0, 1xitem.ma.diamond_essence@0, 1xitem.ma.diamond_essence@0, 1xitem.ma.diamond_essence@0, 1xitem.ma.diamond_essence@0, 1xitem.ma.obsidian_essence@0, 1xitem.ma.diamond_essence@0, 1xitem.ma.diamond_essence@0]. NOT FOUND, please report."

...here the recipe seems to use one time obsidian essence, even if it is not included in the recipe. The recipe shows ingame the correct formation of items.

The recipe is in a molecular assember and is feeded via routed logistic pipes.
Some days before, the recipe was processed correctly. All mods are updated to the latest version.

Environment:
Multiplayer - Server
List of mods: https://docs.google.com/spreadsheets/d/1gvz2XUaJwBr_TvasPZ7vOXZutBv2noSaUIrzgj80auQ/edit#gid=0

[copied log.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/4021339/copied.log.txt)

- Minecraft Version: 
- AE2 Version: appliedenergistics2-rv6-stable-7
- Forge Version: forge-1.12.2-14.23.5.2847-universal

Thank you so much for your help!
Jannik

**Comment by yueh** [comment]
This is not a crash but a simple indication that we have to validate the inputs against the recipe in a very inefficient way. Which can result in a pretty severe performance issue.

This is nothing we can fix, but has to be reported to the modpack itself. They can then decide to fix it, forward it to the actual mod, or just ignore it in case the performance hit is not that severe in their context.
