### ISSUE TITLE
AE2 Preventing Server Launchl.  Caught Exception

### ISSUE THREAD

**Issue by jpoblocki77** [AppliedEnergistics/Applied-Energistics-2#4240]
appliedenergistics2-rv6-stable-6
forge-1.12.2-14.23.5.2847-universal

How to reproduce: just install direwolf20 1.12.2 with froge 2847 and launch

[java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Energistics 2 (appliedenergistics2)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: Caused by: java.lang.NullPointerException
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at appeng.core.AppEng.serverStopped(AppEng.java:271)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at java.lang.reflect.Method.invoke(Unknown Source)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at java.lang.reflect.Method.invoke(Unknown Source)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at java.lang.reflect.Method.invoke(Unknown Source)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at net.minecraftforge.fml.common.Loader.serverStopped(Loader.java:852)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStopped(FMLCommonHandler.java:508)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:587)
[net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: at java.lang.Thread.run(Unknown Source)

**Comment by Yamza** [comment]
What was/is the solution to this issue?

**Comment by jpoblocki77** [comment]
never got an answer

**Comment by mindforger** [comment]
you may have missed the hints in the prepared text to properly report


 A complete crashlog is required when reporting a crash. No excerpts. 
 **Please use pastebin or gist for posting the complete crashlog.**
