### ISSUE TITLE
Memory card in ME p2p tunnel not working

### ISSUE THREAD

**Issue by andre200177** [AppliedEnergistics/Applied-Energistics-2#4242]
Using a memory card to configure my me p2p tunnel the chat displays "Invalid Machine".
I'm playing in a singleplayer world.
I've tried to clear it, restart the game and stuff like this but it continues doing like this.

- Minecraft Version: 1.12.2
- AE2 Version:  rv6-stable-7
- Forge Version: 14.23.5.2847

**Comment by yueh** [comment]
I would guess your are holding something in your offhand. If so, that is simply a forge we cannot fix on our side.

**Comment by andre200177** [comment]
Maybe it did like so because I had baubles on or stuff like that.
I've tried without any of that stuff on and it worked!
