### ISSUE TITLE
Terminal suddently stopped displaying any contentsd(items,fluids)

### ISSUE THREAD

**Issue by JoeJoeTV** [AppliedEnergistics/Applied-Energistics-2#4245]
**Describe the bug**

We have a big ME System and suddently all the terminals (even wireless) stopped displaying any contents, except the interface terminal. Also moving items into crafting using jei, importing/exporting items using a import/export bus and putting items into the terminal still worked. Sometimes the System comes back when taking out a storage cell and putting it back in, but only until you open and close any terminal. When it is working for a short time, behaviour is still buggy and when you take any amount of any item out of the system, the entry disappears. This should also not be caused by not enough energy, because the network can store 16 MRF and uses 10 kRF and is powered by a large capacitor bank connected through a flux plug with surge mode enabled and energy limit disabled. I have tried to only connect the drives, which also didn't work. I am also only using storage cells from ae2.

**The last thing I've tried was building a completely new network(just a core, drive, terminal and two 1k disks) and the problem still persisted.**

**To Reproduce**

I don't really know, it just sort of started happening randomly after working fine for a long time.

**Expected behavior**

The Terminal to behave normally and to be able to acces the items from the terminal.

**Additional context**

-I could provide a Video of it happening

**Environment**

-Minecraft Version: 1.12.2
-AE2 Version: rv6-stable-7
-Forge Version: 14.23.5.2874
-Dedicated Server running on Ubuntu Server
-Modpack Mod List(I am the Modpack Author): https://pastebin.com/vtSTTtSj

**Comment by Pultex** [comment]
maybe world corruption did you try breaking the controllers and placing them back I  have to do that for mine when it stops seeing parts of the system.

Are you saying that the contents of the cells are disappearing from the system or just not showing up in the terminal when you look them up?

**Comment by yueh** [comment]
Usually this is simply not enough power available.

Otherwise I would recommend looking into AE2 addons. There are a bunch in your modpack, which can break AE2.

**Comment by mindforger** [comment]
> Usually this is simply not enough power available.

in addition to that: try throwing in a bunch more ae2 energy cells , 16MRF internal storage seems okayish, but the system size is pretty big

**Comment by JoeJoeTV** [comment]
Yeah but it still didn't work, with an entirely different me system with the same 19MRF energy storage and only a drive and one terminal. After loading a backup and restarting the server a few times I got it to work again, but I had this issue twice before, but before, a simple server restart was all it needed.

**Comment by mindforger** [comment]
Can you repeat the test without ae2 Addons like yueh requested? (Make a Backup of the world and renove one mod at a time)

**Comment by JoeJoeTV** [comment]
The Problem is that it's working now and I don't know what caused it. As I said I had this problem twice before, but this time it wasn't fixed by just restarting.

**Comment by attichicco** [comment]
Do you use ME Toggle bus? if so then that is very likely the cause, every time a toggle bus is triggered the entire system has to be recalculated like when you place a cable and on big system it might take a few seconds, if that toggle bus is piloted by a level emitter it's possible that it gets triggered on and off many times causing your me to basically freeze up, it happened to me on Enigmatica 2 Expert modpack, and to give you an Idea of the size of the ME System... I could autocraft Creative Fluid Tanks from nothing but base resources
