### ISSUE TITLE
ME Crafting Terminal will not craft. Works otherwise.

### ISSUE THREAD

**Issue by KMFrench1** [AppliedEnergistics/Applied-Energistics-2#4247]
When I go to craft in one of my ME crafting terminals it just closes and does not display the GUI. Also it does not seem to have access to the ME drive. I ran a new Cable so that the ME terminal would be on its own channel so I know it is not a channel issue. The distance is over 200 blocks but all the blocks are chunk loaded. A terminal about 40 blocks away from the non working one is working and crafting fine.
Is there a limit to how far you can run cable?

I am playing stoneblock2 on a private server.

appliedenergistics2-rv6-stable-7.jar
Forge-14.23.5.2846

**Comment by Pultex** [comment]
Did you get to the Quantum Network yet maybe that could fix the distance error so it does not need to look at all the connections of cables.
They even work between dimensions so a few chunks should not effect them.
