### ISSUE TITLE
reCAPTCHA blocked in website

### ISSUE THREAD

**Issue by ckykenken** [AppliedEnergistics/Applied-Energistics-2#4248]
**Describe the bug**

"It looks like the you entered an incorrect answer to the reCAPTCHA", but the reCAPTCHA box does not show up.

**To Reproduce**

Create a new account in the website

**Expected behavior**

A reCAPTCHA is shown just above the 'Register' button

**Additional context**

Excerpt of F12 console:
Mixed Content: The page at 'https://ae-mod.info/Register/' was loaded over HTTPS, but requested an insecure script 'http://www.google.com/recaptcha/api/challenge?k=6Lca488SAAAAAPbMjffcbYKHM-X2V8SLREqEL8QQ'. This request has been blocked; the content must be served over HTTPS.

**Environment**

Google Chrome 79, Windows 10 Pro 64-Bit

**Comment by yueh** [comment]
I would have to reach out to Algo to fix it, which probably will take quite a while to potentiall fix it.

But there is really no benefit for creating an account there. So closing for now.
