### ISSUE TITLE
Every single import bus and interface stops/breaks when there is autocrafting scheduled

### ISSUE THREAD

**Issue by tankirules** [AppliedEnergistics/Applied-Energistics-2#4249]
I play with channels disabled, this is on 1.7.10, and the import buses that break include the ones that import the items neccessary to finish the crafting, so everything just hangs - items in chests aren't imported, the cpu crafting hangs, but if i disconnect the cpu crafting cable connectors, everything works again. I have tons of free storage so it's not a cell problem.
Minecraft 1.7.10
AE2 version: appliedenergistics2-rv3-beta-6
This is FTB infinity evolved btw

**Comment by tankirules** [comment]
Ok NVM, turns out the real bug was my molecular assembler setup deciding to just not be turned on and all i had to do was  break and replace the connecting cable - weird bug nevertheless because wh y the hell would it randomly disconnect with full power supply

**Comment by tankirules** [comment]
Ok NVM, turns out the real bug was my molecular assembler setup deciding to just not be turned on and all i had to do was  break and replace the connecting cable - weird bug nevertheless because wh y the hell would it randomly disconnect with full power supply
EDIT: NVM THIS comment, everything is still broken

**Comment by tankirules** [comment]
What? did some further testing, right now i can manually extract and insert items into the me system, but i had a singular, empty 64k cell with a drive in a differerent location, and when i disconnected the main bank of me drives(which i could manually take and give itemsf from still) all the import busses started working. I am SO confused right now.

**Comment by tankirules** [comment]
For some reason if i remove some storage cells(all 64k or less) from my drives(of which there are 4) it works, but
![image](https://user-images.githubusercontent.com/35437320/72217658-27a0e600-3585-11ea-8308-88cb61f66548.png)
if i add any more storage cells than these then the import busses and interfaces break. This really is a strange bug

**Comment by tankirules** [comment]
![image](https://user-images.githubusercontent.com/35437320/72217757-c9750280-3586-11ea-8f77-a7461df7b7b1.png)
So i broke a cable to the molecular assembler bunch of blocks and my system also started working................. Despite turning off channels, is there like a limit to the load that can be put on an me fluix cable? Have I reached it?
![image](https://user-images.githubusercontent.com/35437320/72217776-ea3d5800-3586-11ea-8fed-a70ccbea1b4d.png)

**Comment by mindforger** [comment]
Sidenote first: You can edit older posts to update them, adding comment after comment makes it harder to read, just for future reports

To the report: do you have enough (dense) energy cells, they seem to be missing in your pictures

Power input is limited to network capacity/tick, regardless of input

Please do not misunderstand me closing this issue, but 1.7.10 is not supported anymore but we can still try to figure this out!

**Comment by tankirules** [comment]
> Sidenote first: You can edit older posts to update them, adding comment after comment makes it harder to read, just for future reports
> 
> To the report: do you have enough (dense) energy cells, they seem to be missing in your pictures
> 
> Power input is limited to network capacity/tick, regardless of input
> 
> Please do not misunderstand me closing this issue, but 1.7.10 is not supported anymore but we can still try to figure this out!

What do you mean? I have a tesseract with power acceptor that is linked to a 29 billion RF core, I should have enough power to power the network?
![image](https://user-images.githubusercontent.com/35437320/72218784-fcbd8e80-3592-11ea-87bd-0db77026531c.png)

**Comment by mindforger** [comment]
i just explained it to you 

>Power input is **limited** to network **capacity/tick**, **regardless of input**

**Comment by tankirules** [comment]
> i just explained it to you
> 
> > Power input is **limited** to network **capacity/tick**, **regardless of input**

So you're saying i need more energy acceptors?

**Comment by mindforger** [comment]
no, more capacity
add energy cells

**Comment by tankirules** [comment]
> no, more capacity
> add energy cells (those from AE2)

this worked thank you very much

**Comment by mindforger** [comment]
Glad i could help
