### ISSUE TITLE
System shuts off

### ISSUE THREAD

**Issue by Reun85** [AppliedEnergistics/Applied-Energistics-2#4251]
I'm hosting a server on my computer and playing on it as well, just so that my friend can play with me. 

**Describe the bug**
Recently we have been experiencing a bug, which caused our complete ae2 system to keep switching on/off. After messing around I found out it doesn't shut off, the holy ae2 falls apart, and forgets its there. Nothing is available through ae2 at that point. Picture of before:

(https://user-images.githubusercontent.com/59803338/72224867-4d2af100-357f-11ea-8db1-09cd3c3a4b6a.png)

Picture after:

(https://user-images.githubusercontent.com/59803338/72224869-52883b80-357f-11ea-92cb-4ec41f15ac45.png)

Energy is definitely not a problem.
)

**To Reproduce**
I have no idea how to, I would blame the p2p tunnels for this instability but these shutoffs started happening way after I placed those tunnels down and started using them.

**Expected behaviour**

**Environment**
Our system has 11 controllers and most of the sides are covered with p2p me tunnels to ensure easy wire connection. These p2p tunnels run into 2 controllers and are distributed nicely through the base.
Picture of the controller setup:

(https://user-images.githubusercontent.com/59803338/72224841-0b01af80-357f-11ea-93dd-9b9a50935ea6.png)

I do think though this is pretty basic nowadays.

Distributor system data:
(https://user-images.githubusercontent.com/59803338/72224875-65027500-357f-11ea-9e83-b91d17b7f0dc.png)

- Minecraft Version: 1.7.10(FTB infinity evolved 3.10)
- AE2 Version: rv3-beta-6
- Forge Version: 10.13.4.1614

**Comment by mindforger** [comment]
3MRF power capacity sounds okay, but can you try with the creative energy cell from ae2 just for testing? Next up would be to make sure if everything connected being chunkloaded

**Comment by Pultex** [comment]
If you are using channels how do you have that many P2P connected to each other?
the blue cable is connected to the Fluix cable.
