### ISSUE TITLE
Fluid Terminal autofocus or focus key

### ISSUE THREAD

**Issue by schliip** [AppliedEnergistics/Applied-Energistics-2#4252]
**Describe the feature**
Unlike the other Terminals, the Fluid Terminal does not focus the search bar when it is opened. Also, the "Toggle search box focus" hotkey has no effect.

**Reasons why it should be considered**
Focusing the search bar automatically would make the Fluid Terminal easier to use with many fluid types or similar looking fluids, and would be consistent with the other Terminals.

**Comment by Technici4n** [comment]
Fluid terminal was merged with the regular item terminal.
