### ISSUE TITLE
Cache AESharedItemStack#hashCode() for performance improvements

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#4256]
`AESharedItemStack#hashCode()` can easily be cached due to being an immutable class.

For simple itemstacks it most likely won't be a noticable improvement, but computing the hashcode for nbt tags can be quite taxing and the hashcode is pretty much used anywhere in AEs internal data structures.

**Comment by LemADEC** [comment]
Can we get a new publish version with that fix?
