### ISSUE TITLE
IO Port can not extract items to a physical storage (chest) without Controller

### ISSUE THREAD

**Issue by Amegatron** [AppliedEnergistics/Applied-Energistics-2#4259]
Imagine I have:
1) IO Port
2) Storage cell with some items written onto it (inserted into IO port)
3) A simple chest connected to IO port through Storage Bus (bi-directional or in specific direction according to operations I perform) and smart cable.
4) All these is properly powered.

**Describe the bug**
With such setup I can easily "dump" the contents of a chest to the storage cell (IO Port mode: From Network TO Storage cell). But, I can't do vise versa: IO port does not dump contents of the storage cell back to the chest when switching to opposite mode: From Storage Cell TO the Network. In this case smart cable becomes black and says "0 of 8 channels". But if Controller is present in this small setup - IO port successfully "exports" data from the Storage cell to a chest.

**Expected behavior**
Though I don't see any reason why Controller should be presesnt here (there are only 2 channels involved), and also taking into account that reading from chest also works fine without Controller, dumping the contents to the chest should also happen without a Controller.

**Additional context**
I've also found this posst on Reddit: https://www.reddit.com/r/feedthebeast/comments/5n4hkv/remove_items_in_storage_cells_ae2_in_to_a_chest/ which suggest the same schematics, and seems it worked then, but that was 3 years ago.

**Environment**
- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-7
- Stoneblock 2 pack (1.16.0)
- Forge: 14.23.5.2846

**Comment by yueh** [comment]
Not enough power available.

**Comment by mindforger** [comment]
to add a bit insight, your system has no >internal< storage, so it can not work properly, try adding an ae2 energy cell to verify

**Comment by Amegatron** [comment]
Ok, thanks for the replies. But I still don't understand it and I find it strange. I attached an energy cell to this setup (without controller) and it started to work. But ok, if some energy "buffer" is needed, why can I still freely dump the contents of a chest to a memory cell? This small setup is powered from my main network through a fiber to make things clear. Also, another thing: if I experiment with just a stack of items, I can still read and write to the chest without an energy cell. But if I increase amount of items (I made it 12 stacks) - then I can no longer read a single item from the chest. Why so? Why not read at least one stack (while energy is "enough") and then stop? Could you please explain the mechanics?

**Comment by mindforger** [comment]
Each transfered item requires a bit of energy + the power requirement of the active component. If power runs out in a single tick, it reboots. It also can only recharge its internal buffer once, so the input is limited by its own capacity/tick. I can not explain exactly why it is working one way but not the other but i guess converting item to data cost way less energy than the other way. Reboot itself also cost energy, with big systems this could cause a bootloop, and impact server performance, at least in the past

**Comment by Amegatron** [comment]
@mindforger Ok, thanks for the reply again. But I still don't fully understand it and moreover, still consider it an issue. Ok, it is logical that operations through network should require additional power ... But, why not take this power from the main power supply of the network, let it be Energy Acceptor or connection to another network through fiber? I still don't get it. So, I don't actually get why this issue was closed :)

**Comment by Ommina** [comment]
I see two possible reasons:

First -- it's a design choice.  As networks grow in ability, they have greater demands, and will require resources from the player.  (I think, as a design, it fails.  There are countless issues on these pages from those who just don't see the difference between internal and external power, coupled with no real indication that energy is the reason the network is failing.)

Second -- it's a performance choice.  Calling into the energy supplier once and filling local storage is cheaper than calling across mods repeatedly, especially when AE doesn't know how performant the other mod is.  That is, move 50,000 once instead of 1,000 fifty times.

Or maybe both.  Or none of the above.  I don't claim to know Algo's original reasoning, but those are my suspicions.

**Comment by Amegatron** [comment]
Thanks for your ideas. It makes some sense now to me. I was also among those who didn't even know about "internal" energy storage of the network, and only now, after reading your answer and ME Controller description on AE's site I'm aware of it. Bad thing is it seems to be a complete mystery how much additional energy storage one should have for his networks, seems only trial and error.

**Comment by mindforger** [comment]
>seems only trial and error.

the me network tool tells you all about capacity and consumption + components in the network (though the value is averaged, so spikes should be taken into account when adding energy cells)
