### ISSUE TITLE
Re-battery IndustrialCraft2 and AE2 autocraft

### ISSUE THREAD

**Issue by Orygeunik** [AppliedEnergistics/Applied-Energistics-2#4261]
**Describe the bug**
Problem like as in issues:
#4020; #4184; #3974
When try to build some object used Re-Batteries crafting pending

**To Reproduce**
1. Install IC2 Exp (2-2.8.188-ex112)
1. Make 2 templates;
1. Encode templates as generator and re-battery (allow replace material);
1. Insert templates into interface;
1. Add base resources;
1. Order a generator;
1. Pending...

**Expected behavior**
Generator built by order

**Additional context**
Template of Re-Battery
![TemplateReBattery](https://user-images.githubusercontent.com/6960655/72767430-d936bb80-3c04-11ea-9495-5f40dd10e266.png)
Template of Generator
![TemplateGenerator](https://user-images.githubusercontent.com/6960655/72767429-d89e2500-3c04-11ea-8ee9-3a75f191be0e.png)
Interface Config
![InterfaceConfig](https://user-images.githubusercontent.com/6960655/72767419-d76cf800-3c04-11ea-96a7-140f5cfc4862.png)
Plan of Craft
![PlanOfCraft](https://user-images.githubusercontent.com/6960655/72767428-d89e2500-3c04-11ea-96fb-c836e2589d0f.png)
Craft Processor Struct
![CraftProcessorStruct](https://user-images.githubusercontent.com/6960655/72767418-d76cf800-3c04-11ea-8b95-fa8fcc588895.png)
Pending Craft 1
![PendingCraft](https://user-images.githubusercontent.com/6960655/72767426-d89e2500-3c04-11ea-8519-46fc05cae705.png)

---
Maked 2 Re-Battery by Template
![Maked2ReBatteryByTemplate](https://user-images.githubusercontent.com/6960655/72767424-d8058e80-3c04-11ea-9d40-44f46ced02b7.png)
Try again and ...
Pending Craft 2
![PendingCraft2](https://user-images.githubusercontent.com/6960655/72767427-d89e2500-3c04-11ea-95c1-a773aa917945.png)

---
All Items Page 1
![AllItemsPage1](https://user-images.githubusercontent.com/6960655/72767414-d20fad80-3c04-11ea-9b6c-d9ef76a1bcc9.png)
AllItems Page 2
![AllItemsPage2](https://user-images.githubusercontent.com/6960655/72767415-d2a84400-3c04-11ea-86e2-98aefd9f2416.png)
Loaded Mods
![LoadedMods](https://user-images.githubusercontent.com/6960655/72767420-d76cf800-3c04-11ea-8197-a82230edbafc.png)
Loaded Mods List Page 1
![LoadedModsListPage1](https://user-images.githubusercontent.com/6960655/72767421-d8058e80-3c04-11ea-8a1c-129edb826ec8.png)
Loaded Mods List Page 2
![LoadedModsListPage2](https://user-images.githubusercontent.com/6960655/72767422-d8058e80-3c04-11ea-9c56-ce4b180af1cf.png)
Mods In Mods Folder
![ModsInModsFolder](https://user-images.githubusercontent.com/6960655/72767425-d8058e80-3c04-11ea-953c-30e73f689816.png)

**Environment**
SMP (Too on server)
Mods:
* IC2 exp (2-2.8.188-ex112);
* AE2 (rv6-stable-7);

[Saved map](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/4088744/-.zip)

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-7
- Forge Version: 14.23.5.2847

**Comment by Orygeunik** [comment]
Note. In other issues you said that problem in mod-packs or in other place. In current example no any other mods, only IC2 and AE2. Map with this example and from which screenshots were taken in attachment of main message.

[Duplicated link to map (Новый мир-.zip)](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/4088744/-.zip)

**Comment by Orygeunik** [comment]
@yueh 
What is a reason to close this issue?

**Comment by Ommina** [comment]
@Orygeunik 

https://github.com/AppliedEnergistics/Applied-Energistics-2/commit/aa6e1e30331ae011907943001a557062111553bc

**Comment by Orygeunik** [comment]
@yueh
Because that PR #3974 not solved the problem. Reopen issue, please
