### ISSUE TITLE
Export bus functions request

### ISSUE THREAD

**Issue by HonzaVinCZ** [AppliedEnergistics/Applied-Energistics-2#4263]
I'd like to ask for enhancing export bus for functions: Set certain items to route at once and set amount of items to be stored in connected storage. Just like in Logistics Pipes. 
It is quite important function for any tech mod as GTCE to fill machines with just certain amount of material to process and not block machine input by one item of four requested for example. 
Thank you.

**Comment by yueh** [comment]
Stock-keeping of external inventories is outside the scope for an export bus.

**Comment by Tahakk** [comment]
you can use interface that will keep certain items in stock or u can use the EnderIO counter filter

**Comment by HonzaVinCZ** [comment]
Tahakk you're right, thanks.
