### ISSUE TITLE
Partial storage access between networks

### ISSUE THREAD

**Issue by supercat765** [AppliedEnergistics/Applied-Energistics-2#4266]
**Describe the feature**
A white list storage access between networks to compartmentalize between networks and subnetworks.
potentially via connecting the 2 networks with face to face storage busses

**Reasons why it should be considered**
it allows a new form of subdividing systems
allowing a subsystem to provide to several specialized systems only what is needed
makes said subdivide more user navigatable

**Additional Context**
So here is the setup I have
ME network 1: My ME crafting system to auto craft the parts for more ME systems
ME network 2: A future Ore Processing plant/metal storage using tinkers construct

so ME1 needs gold and iron to craft with and I want it to be stored on ME2
But if I grant full access of ME2 to ME1 then ALL the other stuff shows up as well clogging up the viewscreen
And I want to be able to store misc AE2/other processing items without having to add each and every one of them to a view cell

**Comment by mindforger** [comment]
Not sure if you did not try yet or what feature is missing there, but you can attach a storage bus to an interface and access the whole subnet connected to that interface through the storage bus. I use this to minimize channel usage by connecting z barrels with storage busses and an interface and access it through a single storage bus. You can not use pattern from the subnet if i remember right, but i am very unsure actualy

**Comment by supercat765** [comment]
I did try it. it is what I have because I can't do what I want
as ven diagrams to represent
![ven](https://user-images.githubusercontent.com/13575378/73239246-6c657900-4150-11ea-8b3f-e9850bd0c1ef.png)
I don't want it to have full access to the subnet
![2020-01-27_22 04 20](https://user-images.githubusercontent.com/13575378/73239551-4a202b00-4151-11ea-9b8f-b5a6b0e2dae5.png)
This here is my terminal for creating ME components...
You see the Platinum, the nickel, the copper, the cobalt, etc.
it does need gold and iron to craft its things
and I want this subnet to store/manage all the metal
So I want This network to only access the gold and iron from the subnet

**Comment by mindforger** [comment]
you can filter the storage bus but i have never tested if this applys to the interface mechanic, as storagebus + interface is special case code

**Comment by supercat765** [comment]
I can say that it doesn't as I tried that.
If it did that would solve this

**Comment by mindforger** [comment]
@yueh that would be a very helpfull feature indeed :D

**Comment by yueh** [comment]
While it certainly might be helpful, the current inventory system does not really support it easily. It would have to be completely rewritten or at least see a major refactoring. Otherwise it would be a constant source of bugs. There should already be an issue about it, probably with a bit more information, but I have not found it yet.

Otherwise the basic idea of sharing specific items between two networks is not totally impossible. There are even a couple different approaches depending on the exact needs.

**Comment by mindforger** [comment]
>It would have to be completely rewritten or at least see a major refactoring

that is what i feared and asked you for detail :(
