### ISSUE TITLE
When autocrafting certains items the process request "Encoded pattern"

### ISSUE THREAD

**Issue by Furuchiru** [AppliedEnergistics/Applied-Energistics-2#4267]
**Describe the bug**

Asking the system to craft for some items will not work as it request for "Encoded pattern".
I tried re-making all patterns and it didn't work. I've never seen this bug and couldn't find something similar.

**Expected behavior**
The requested items should be crafted as all materials and patterns are present in the system

**Additional context**
https://imgur.com/a/ADFPzUx

- Minecraft Version: 1.7.10 Project Ozone 2
- AE2 Version: rv3-beta-6
- Forge Version: 7.99.40.1614

**Comment by yueh** [comment]
In general 1.7.10 is no longer supported.

But just in case, to me it looks like some pattern uses the pattern to craft an ingredient as ingredient and not the ingredient itself.
