### ISSUE TITLE
AE network suddenly power loss.

### ISSUE THREAD

**Issue by EreticKB** [AppliedEnergistics/Applied-Energistics-2#4271]
Hi, i understand that this must be fixed in newest version, but they not compatible with minecraft 1.7.10. My AE network suddenly loss all of it's power even if power generation is about 20-30 times more then possible consumption. There is a screenshot with network layout and inadequate power consumption.
![2020-01-31_17 37 15](https://user-images.githubusercontent.com/59476878/73548274-886b6200-4451-11ea-9eb8-af88fd726cc8.png)

- Minecraft Version: 1.7.10
- AE2 Version: RV3-Beta6
- Forge Version: 10.13.4.1614

P.s. i will glad if you waste some of your time for fix with trouble in a such old version.

**Comment by Pingger** [comment]
Have you found a solution?
