### ISSUE TITLE
Am I missing something? Crafting Capacity

### ISSUE THREAD

**Issue by Rithenar** [AppliedEnergistics/Applied-Energistics-2#4272]
When requesting a crafting job I get an error saying "No crafting CPU's available", even though I am already running a similar job in a different crafter with same setup.

**Describe the bug**

As you can see in the picture below I have my crafters set-up properly and a couple of them are running the same process: 2 Draconic Solar Panel.  The problem is that despite having 2 more crafters with the same setup, 2X64K crafting storage and 1 co-processor, I cannot run the same job on them.

The second snapshot shows the job request which is also for 2X Draconic solar panels and is showing that there are "No Crafting CPU's Available"

**To Reproduce**

Request the same job from AE with all materials available in storage
**Expected behavior**

The job is requested and processed as with the other crafters

**Additional context**

![Crafters](https://user-images.githubusercontent.com/9939332/73693067-29009280-469b-11ea-9cbf-a3aaf0b686d4.png)
![Solar Panel Crafting Screen](https://user-images.githubusercontent.com/9939332/73693077-2c941980-469b-11ea-82ea-7581b2c8cd6b.png)

**Environment**

Project Ozone 3 Titan Mode SP with ComputerCraft and PackagedAuto added  https://www.curseforge.com/minecraft/modpacks/project-ozone-3-a-new-way-forward/relations/dependencies
MC 1.12
AE2 rc6-stable-7
Forge 14.23.5.2847
AE2 Wireless Terminal Library 1.0.30
AE2 STuff 0.7.0.4

**Comment by Meller127** [comment]
I Think when you started the first crafting job you hade some materials already in the system. So when starting the next job of the same recipe it needs more bytes 141k and you need to add more crafting storage. You have 128k and need 141k

**Comment by Rithenar** [comment]
I am not sure that is the case. I have Two 2X64 + 1 co-processor, 1 2X16 +1 co-processor, 2 2X4K +1 co-p, and 2 1X1K crafters sitting there doing nothing. Wouldn't the additional jobs get directed to one of those? Maybe the 1K and the 4K can't handle it but the 2X64 and the 16 can sure handle making some of the additional stuff...?

**Comment by Rithenar** [comment]
Welp...you may be right. I just made 4 4X64 with 2 co-processors each ans was able to add the job.

**Comment by mindforger** [comment]
I asume the issue can be closed then? :)

**Comment by Rithenar** [comment]
Yup! :)  Thank you!
