### ISSUE TITLE
Bigger/ Customizeable Interface terminal GUI

### ISSUE THREAD

**Issue by attichicco** [AppliedEnergistics/Applied-Energistics-2#4273]
#### Description
Quality of life Improvement, allow the player to select tall centered terminal option on ME Interface terminal, 6 rows are not many, especially when you have more than 200 Interfaces to search into for an empty space.
I find the small GUI extremely annoying while playing Enigmatica 2 Expert, and down here you'll find some screenshot that will show you, side by side, the size of the crafting terminal compared to the terminal and the Interface terminal

#### Screenshots
![The 3 terminals near eachother](https://user-images.githubusercontent.com/21057954/73752064-8b6f9680-4760-11ea-92f8-722ed02c8123.png)
![Interface Terminal alone on my big screen](https://user-images.githubusercontent.com/21057954/73752081-932f3b00-4760-11ea-8c5c-d487f8767c8d.png)

**Comment by GuptaChinmay234** [comment]
I recommend marking this as an enhancement

**Comment by mkaito** [comment]
I'm playing Project Ozone 3 Kappa mode, which is often described as a recursive rabbit hole of madness when it comes to crafting anything. The amount of crafting and processing patterns I have to juggle is quite high.

Seeing only 6 rows at a time in the interface terminal is just not enough when you're juggling dozens upon dozens of patterns.

Seeing as a tall vertical mode is already present for other terminal types, I'd love to see it applied to the interface terminal as well. It would be a big improvement to UX.
