### ISSUE TITLE
AE 2: ME TERMINAL help pls

### ISSUE THREAD

**Issue by iScarr** [AppliedEnergistics/Applied-Energistics-2#4274]
I made an ME Terminal and it works very well, but I would like to access this terminal on my second base which is very far from this system

**Comment by Meller127** [comment]
Here you go, and remember to chunkload both ends. 
https://ae-mod.info/ME-Quantum-Network-Bridge/

Tip: This is not an Help forum

**Comment by iScarr** [comment]
> Aqui está, e lembre-se de carregar as duas extremidades.
> https://ae-mod.info/ME-Quantum-Network-Bridge/
> 
> Dica: este não é um fórum de Ajuda


thanks for the help, and sorry i didn't know it was an S2 help forum
