### ISSUE TITLE
(Help with game balance) I want to nerf the mod as much as possible without removing any game mechanic or component

### ISSUE THREAD

**Issue by NestorZuZu** [AppliedEnergistics/Applied-Energistics-2#4275]
Can someone please tell me how to nerf this mod? I am making a modpack (only for 4 friends and me) but this is quite an OP mod and I would like to make it more difficult to obtain certain ores or materials without changing the recipes or disabling things. Any help is welcome (Example: in config line 128 change the value of ore spawn ratio for something lower)

(Also sry I don't know where to ask this I think this is a thread for issues not just bagging for help)

**Comment by attichicco** [comment]
You can change the ore spawn rate on the configs, even limiting the dimensions on which they can spawn, you can also use https://www.curseforge.com/minecraft/mc-mods/crafttweaker (CraftTweaker Mod) to change the recipes of every crafting you think is too easy. Anyway as you already know this is a Thread for Issues, and you'll get answers much sooner if you got on any forum that is made for helping people out :)

**Comment by yueh** [comment]
I would recommend looking for a community around building modpacks. They are probably better suited to give you advice about balancing a modpack itself. Especially as not everyone considers only reducing drop rates as nerfing or more difficult when every other balance option is already excluded.
