### ISSUE TITLE
Not sure wether this belongs here, but i couldnt find a better place

### ISSUE THREAD

**Issue by Ubus99** [AppliedEnergistics/Applied-Energistics-2#4278]
#### Description

how do I remove items from the inscriber using the build in recipe template?

#### Environment

- Minecraft Version: 1.7.10
- AE2 Version: rv3 latest
- Forge Version: 10.13.4.1614

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.12 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.

**Comment by mindforger** [comment]
besides the version based closure, if i am remembering right, you can only disable ALL built in recipes and rebuild the recipes all together (never did it so no idea where to start exactly or if there is a template of the recipes generated)

but you can use modtweaker for your purpose 
http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Applied_Energistics_2_Support

not sure if the wiki is up to date tbh. i am playing on 1.12

**Comment by Ubus99** [comment]
> 
> 
> besides the version based closure, if i am remembering right, you can only disable ALL built in recipes and rebuild the recipes all together (never did it so no idea where to start exactly or if there is a template of the recipes generated)
> 
> but you can use modtweaker for your purpose
> http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Applied_Energistics_2_Support
> 
> not sure if the wiki is up to date tbh. i am playing on 1.12

MT is broken for rv3, but so be it...

**Comment by repo-alt** [comment]
You may ask at https://github.com/GTNewHorizons, there is a forked version of AE2 for 1.7.10 and I'm pretty sure it supports MineTweaker

**Comment by leagris** [comment]
@repo-alt AE2 for 1.7.10 supports custom recipes within its config

**Comment by mindforger** [comment]
@leagris you missed OPs post
