### ISSUE TITLE
The console keeps reporting errors about [AE2: S]: using craftingmanager fallback

### ISSUE THREAD

**Issue by DJmanito** [AppliedEnergistics/Applied-Energistics-2#4281]
**Describe the bug**
I found that mekanism's "basicblock: 6" and AE automatic synthesis may brush items, so I ban the item, but this error has been in the background. After restarting the server, it still exists. When there are fewer players in the night, I checked each AE system, and there are no related synthesis tasks or stored items.
This should also have nothing to do with the ban item plug-in. After I unban this item, restarting the server still has this problem.

**To Reproduce**
Mekanism's "basicblock: 6" can take out the items in the box through composition, store for example 64 items, and then generate AE synthesis template, then take some items out of the box, and then put the box into automatic synthesis, and 64 items can still be synthesized.
The same method can also be used for Botania's "blackholetalisman" and other items that can be taken out and stored through synthesis

**Additional context**
[Server thread/WARN] [AE2:S]: Using CraftingManager fallback: Recipe <mekanism:bin> for output <1xtile.air@0> rejected inputs [1xtile.BasicBlock@6]. NOT FOUND, please report.

**Environment**
    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-ea50f0c2
    Sponge: 1.12.2-7.1.8
    SpongeForge: 1.12.2-2838-7.1.8
    Minecraft Forge: 14.23.5.2847
    JVM: 1.8.0_242/64-bit (Private Build)
    OS: Linux (5.3.0-28-generic/amd64)

**Possible mod information**
   appliedenergistics2-rv6-stable-7
   Mekanism-1.12.2-9.8.3.390

**Server Plugins**
Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge,  FastAsyncWorldEdit, AmberShop, ClearMob, DailyRewards, DupeFixer, EconomyLite, FlexibleLogin, GiftCode, Inspector, JoinTitle, KaroglanSignEditor, LuckPerms, MMCLogger, MMCReboot, MMCRestrict, MMCRules, MultiCurrencies, New Honor, Nucleus, NucleusHover, PixelAutoMessages, PixelVip, PlaceholderAPI, RedProtect, ServerListPlus, ShabbyHolograms, Sledgehammer, SoulLaggRemover, SpongeLoginFix, Title Broadcaster, UltimateChat, UniversalMarket, VirtualChest, VirtualChestEnchantments, WorldEdit, YYS ScoreBoard, latch, wolrdpc

**Server Mods**
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Applied Energistics 2, Aroma1997Core, AromaBackup, AromaBackuprecovery, Astral Sorcery, Baubles, Biomes O' Plenty, Botania, Chisel, Clumps, CoFH Core, CoFH World, CodeChicken Lib, ContainerFix, CraftTweaker JEI Support, CraftTweaker2, CustomNPCs, Cyclops Core, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, Ender Zoo, EnderCore, EnderStorage, EverlastingAbilities, Extra Utilities 2, ExtraBotany, FoamFix, FoamFixCore, Forestry, Hatchery, Immersive Engineering, Iron Chest, Just Enough Items, MCMultiPart, Mantle, Mekanism, Mekanism: Generators, MineTweakerRecipeMaker, NoMoreRecipeConflict, OpenBlocks, OpenModsLib, OpenModsLib Core, Patchouli, Phosphor Lighting Engine, RandomPatches, Reborn Core, Redstone Arsenal, Redstone Flux, Rustic, SpongeForge, TOP Addons, TeaStory, Tech Reborn, Tech Reborn Mod Compatibility, The One Probe, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tinker I/O, Tinkers Tool Leveling, Tinkers' Construct, Tiquality, Touhou Little Maid, VanillaFix, Varied Commodities

**Comment by DJmanito** [comment]
Oh, I'm wrong. Instead of automatic AE terminal composition, it is directly synthesized in the molecular assembler. The composition in the terminal will detect that the item is wrong

**Comment by yueh** [comment]
This basically just indicates a potential performance issue, which cannot be resolved on our side.
Only the modpack or mod adding the particular recipe would be able to solve it.

In terms of mekanism it is pretty much unsolvable without them breaking every existing save. We cannot determine the actual item any recipe would accept and have to basically shove half of the blocks/items from mekanism into each recipe until we found some, which would work.
Combined with forge recipe handling being extremely poorly designed, this can be a pretty costly operation.

**Comment by DJmanito** [comment]
After I changed the B: craftingmanagerfallback in the configuration file to false, the problem was solved.

```
craftingfeatures {
        B:CraftingCPU=true

        # Use CraftingManager to find an alternative recipe, after a pattern rejected an ingredient. Should be enabled to avoid issues, but can have a minor performance impact.
        B:CraftingManagerFallback=false
        B:MolecularAssembler=true
        B:Patterns=true
    }
```

**Comment by yueh** [comment]
This won't solve it, just stop crafting anything which need it.
