### ISSUE TITLE
Modded 1.12.2 Minecraft Game Crash/Freeze

### ISSUE THREAD

**Issue by JasonBourne007** [AppliedEnergistics/Applied-Energistics-2#4283]
I have been pouring over google for the past 5 days and from what I can tell, this SEEMS to be an AE2 issue. 

I am trying to create a new mod pack for myself for Minecraft 1.12.2.

After lots of tinkering, I got all of the mods matched with their proper versions, and the game launched to the menu without any issues.

Now I can get the game to launch with any NEW world but I am trying to resume playing on my existing world that has an AE storage system set up as well as a quarry. So my goal is to not lose my progress haha. 

THESE ARE THE MODS I HAVE INSTALLED SO FAR:

Actually Additions
Actually Baubles
Applied Energistics 2
Architecturecraft
Baubles
BetterBuildersWands
Bibliocraft
Biomes O' Plenty
Block Craftery
Blood Magic
Bookshelf
Botania R1
BuildCraft
Chest Transporter
ChickenChuncks
Chisel-MC1
Chisels and Bits
Clumps
CodeChickenLib
CoFHCore
CoFHWorld
Craft Tweaker 2
CTM-MC1
EnderCore
EnderIO
EnderStorage
Extra Utilities
Extreme Reactors
Finder Compass
Forgelin
GalacticraftCore
Galacticraft-Planets
Guide-API
Hwyla
iChunUtil
Industrial Craft
Industrial Foregoing
Integration Foregoing
Iron Backpacks
Iron Chest
Just Enough Items
Mantle
MCMultiPart
Meta-Morph
MicdoodleCore
More Overlays
Mysticallib
Not Enough Items
OpenBlocks
OpenModsLib
Portal Gun
Railcraft
Redstone Arsenal
Redstone Flux
Replay Mod
SubCommonLib
Tinker's Construct
Telepads
Tesla-Core-lib
Thermal Cultivation
Thermal Dynamics
Thermal Expansion
Thermal Foundation
Thermal Innovation
Tree-Capitator
Twilight Forest
Waila Harvestability
WorldEdit-CUI-Forge-Edition
Worldedit-Forge-MC
Xaero's Minimap
Zerocore

On my current world, once I clicked on "play world", it loaded for a few seconds, said "creating terrain", and then froze, and stayed that way until I had to close down the whole program.

But again, creating a new world works fine.
So it’s something within that save that I can’t figure out what the problem is.

I checked the crash logs, and this is the most recent one. I can't figure out what it is saying the actual issue is. CRASH LOG INCLUDED BELOW.

Any help with this issue would be greatly appreciated.

Thank you.

[crash-2020-02-12_18.47.13-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/4208585/crash-2020-02-12_18.47.13-server.txt)

**Comment by yueh** [comment]
This pretty much indicates a corrupted world (or some other mod doing something really broken).
E.g. it is most likely, that loading an old world with a completely new mod pack might simply not survive due to too many changes like missing/new blocks now interfering with each other.
