### ISSUE TITLE
Config to blacklist meteors by biome

### ISSUE THREAD

**Issue by TheDeviantCrafter** [AppliedEnergistics/Applied-Energistics-2#4285]
**Describe the feature**

A blacklist that prevents meteors from spawning in specific biomes. This would work just like the dimension blacklist, but use biome names in `modid:biomename` format.

It should also support biome dictionary tags such as `WET` or `PLAINS`. Supporting these would make it easy to add, for example, all mountainous biomes fairly easily.

**Reasons why it should be considered**
When a meteor spawns, it digs a large hole in the terrain. This hole removes all blocks in a massive vaguely oval shaped region. This is usually fairly minor, but if it spawns on the side of a mountain or the bottom of a forest, it can carve an *enormous* gash in the terrain.

This is can bring my PC to a crawl for a few seconds in extreme cases, and it's kind of ugly. I would like to blacklist particularly tall biomes like BoP's alps and redwood forest biomes.

**Additional Context**
Here's an example I found where it spawned on a mountainside. I've personally witnessed some craters that were much larger.
https://imgur.com/gallery/BwMSN/comment/479983741

**Comment by yueh** [comment]
Might be an idea in case the meteor generation is completely rewritten. But currently not worth it.

It will also have to deal with edge cases like spawning at the border while still extending into a different biomes. Or some of the very small biomes, which can be smaller than the crater itself.
