### ISSUE TITLE
Can't Crafting Fluix Crystal

### ISSUE THREAD

**Issue by ShVAKcannon** [AppliedEnergistics/Applied-Energistics-2#4286]
Hi everyone! I have  a some trouble: on my own server I use spongeforge-1.12.2-2825-7.1.6, so while this mod is installed, crafting Fluix Crystal is not possible (no reaction in world between Charged Certus Quartz Crystal, Nether Quartz and Redstone)
Can you help me with it?

- Minecraft Version:  1.12.2
- AE2 Version: rv6 stable 7
- Forge Version: 14.23.5.2847

**Comment by yueh** [comment]
We do not support anything like Sponge or Bukkit officially. Only a standard forge environment.

Should you be able to reproduce it without it and in a new environment and save, please update the issue accordingly and we will reopen it.

**Comment by mindforger** [comment]
You could add a normal crafting recipe as an idea
