### ISSUE TITLE
Spatial IO port not moving cell on activation, not storing player either.

### ISSUE THREAD

**Issue by mgla** [AppliedEnergistics/Applied-Energistics-2#4288]
After activating a spatial IO port in the overworld from within a spatial storage cell (using cross dimension redstone), it shows odd behavior.

* On redstone signal, all blocks are correctly swapped. Players however (that is, me) are not.
* The spatial IO cell does is not moved to the second slot of the spatial IO port on activation anymore.

**To Reproduce**
The behavior only changed when I used cross-dimension redstone signal for activation. I placed the transmitter (RFTools Redstone transmitter) while being stored in the dimension.

**Expected behavior**
* On activation, the player should be moved into the spatial storage cell, not just the blocked.
* The spatial storage cell should move to the second slot of the spatial IO port as usual.

**Additional context**
I tried replacing the Spatial IO port, but the behavior is consistent. Seems to be related to the storage cell.

**Environment**
Multiplayer, modpack is Dungeons and Dragons & Space Shuttles 7.1a

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-7
- Forge Version: 8.0.99.99

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.15 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
