### ISSUE TITLE
i had a crash while trying to open a crafting terminal 

### ISSUE THREAD

**Issue by lucifervii** [AppliedEnergistics/Applied-Energistics-2#4289]
cant open a crafting terminal on my world just started today i can open other blocks in AE2 liek the ME drive
**Describe the bug**

**To Reproduce**

open a crafting terminal
**Expected behavior**

**Additional context**

https://paste.dimdev.org/kuvisexuja.mccrash
**Environment**

the 1.12.2 pack with some added mods

- Minecraft Version:  1.12.2
- AE2 Version: ae2stuff-0.7.0.4-mc1.12.2
- Forge Version: 1122

**Comment by TheJulianJES** [comment]
Try removing XCPatch. https://github.com/ExtraCells/ExtraCells2/issues/673
