### ISSUE TITLE
Game crashes before reaching the main menu 

### ISSUE THREAD

**Issue by devontheyoutuber** [AppliedEnergistics/Applied-Energistics-2#4291]
**Describe the bug**
Game is crashing before reaching the main menu

**Expected behavior**

[crash-2020-02-21_10.32.09-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/4237089/crash-2020-02-21_10.32.09-client.txt) 

**Environment**

- AE2 Version: rv6-stable-7
- Forge Version: 1.12.2
Other mods: https://www.dropbox.com/s/7ie6o4d7hom0ubp/Dragons%20Lair%20Mod%20Archive%201.0.1.zip?dl=0

**Comment by mindforger** [comment]
Failed to register dimension for id 7, One is already registered

configure another dimension ID in the coinfigs

**Comment by devontheyoutuber** [comment]
thanks that fixed the problem
