### ISSUE TITLE
System slowly leaking fluids

### ISSUE THREAD

**Issue by Rithenar** [AppliedEnergistics/Applied-Energistics-2#4294]
I have 4 distinct Mekanism basic fluid tanks connected to Thermal Expansion's Magma Crucibles producing Liquids on demand. The tanks have a Fluid Storage Bus attached and formatted so it recognizes the fluid that is stored there. I have removed all Fluid export buses from my base and I still have these tanks slowly "leaking" fluids somewhere. See pictures and quick video of problem

This is the base setup to produce liquids. The liquid is produced in the Magma Crucible and auto extracted to the tank above
![fluid setup](https://user-images.githubusercontent.com/9939332/75118701-f74b6d80-5641-11ea-9cf3-588e73738b53.png)

The tanks have a bus connected and formated to the contents
![Formated storage bus](https://user-images.githubusercontent.com/9939332/75118725-2cf05680-5642-11ea-8fc5-2b4087384a8e.png)

The fluid slowly "leaks" even though there are no fluid export buses connected to the system

https://youtu.be/PSUXvNjSzbo

**Describe the bug**

Fluids leaking from connected fluid storage tank even though there are no fluid export channels in system
**To Reproduce**

**Expected behavior**

**Additional context**

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-7
- AE2 Stuff: 0.7.0.4
- Forge Version: 14.23.5.2847

**Comment by yueh** [comment]
Storage buses are entirely passive. If the tank content changes, it is either the tank itself or something else is still extracting with it somehow. Like a constant loop between the tank and crucibles.

If you can provide a reliable way to reproduce it with a minimal set of mods, I will reopen it.
