### ISSUE TITLE
Make the unit clear in the ME Fluid Emitter Interface

### ISSUE THREAD

**Issue by MrZoraman** [AppliedEnergistics/Applied-Energistics-2#4297]
I fumbled around with the ME Fluid Emitter thinking it was broken for a long time because I thought that the unit was in buckets, not millibuckets. There is no indication of the unit anywhere in the GUI, and I was unable to find the ME Fluid Emitter documentation on ae-mod.info.

**Comment by attichicco** [comment]
As far as I know everything is based on mB, tanks of every sort, pipettes, fluid emitters, every weapon that contains fluid, and most recipes that require liquids often consume half or a quarter bucket, unless they're done in a crafting table.
The only thing that is measured in buckets that I remember in minecraft is the bucket itself.
Anyway I think a little text next to it that says mB shouldn't be a problem, we'll see what the creator thinks about this

**Comment by yueh** [comment]
Could certainly be better. But there isn't really space to add a `mB` in a sensible way without changing the GUI and also affecting the item based one.

**Comment by mindforger** [comment]
How about putting it into the hover text? Wouldn't need any large changes afais

**Comment by shartte** [comment]
Changes in #4486 will make it look like this:
![grafik](https://user-images.githubusercontent.com/1261399/87886991-73938280-ca21-11ea-8723-4f2b53de5a3e.png)

Is that what was asked for here?

**Comment by shartte** [comment]
Has been merged, unit is shown now.
