### ISSUE TITLE
Crash if Meteorite Compass rendered in a GUI

### ISSUE THREAD

**Issue by Evolution0** [AppliedEnergistics/Applied-Energistics-2#4298]
**Describe the bug**
If you attempt to view the Meteorite Compass item in any way (JEI, Creative inventory) the game will crash immediately if running alongside Real Train Mod (v2.4.5 for reference)

**To Reproduce**
Load AE2 and RTM and any required dependencies together, then attempt to view the aforementioned item 

**Additional context**
RTM seems to do some of its own unique model loading and Meteorite Compass has its own unique model. May be related.

Crashlog: 
https://pastebin.com/m0nFfvde

**Environment**
Windows 10 Pro x64 Build 18362
OpenJ9 (1.8.0_222)

- Minecraft Version: 1.12.2
- AE2 Version: Revision 6 Stable 7
- Forge Version: 14.23.5.2847

**Comment by yueh** [comment]
This is a crash inside the JRE itself, so must likely a bug with OpenJ9 itself. 
Or potentially some "performance enhancing" mod did successfully patch it into a broken state (but I do not think that is actually possible)
