### ISSUE TITLE
P2P Not Working With Spongeforge 1.12.2-2838-7.1.9, instead of formatting memory card item, it wipes it

### ISSUE THREAD

**Issue by tjdokas** [AppliedEnergistics/Applied-Energistics-2#4299]
Title. P2P bus and memory card work as intended in singleplayer, but with spongeforge 1.12.2-2838-7.1.9 this issue easily reproduced, whereby you attempt to use them through the same means, only in this environment it wipes the card.

I had the same issue with forge 2768 last year. Some versions of spongeforge don't produce this issue, but after attempting ten different versions this issue persists. I suspect the issue here lies with spongeforge but am filing the issue here as this mod is the only one causing problems.

Server output returns nothing when replicating the issue.

**Environment**
spongeforge 1.12.2-2838-7.1.9
openjdk1.8

- Minecraft Version: 1.12.2
- AE2 Version: 2rv6stable7
- Forge Version:2838

**Comment by yueh** [comment]
We do not support anything like Sponge or Bukkit officially. Only a standard forge environment.

Should you be able to reproduce it without it and in a new environment and save, please update the issue accordingly and we will reopen it.
