### ISSUE TITLE
Add support for stack crafting

### ISSUE THREAD

**Issue by dwentz89** [AppliedEnergistics/Applied-Energistics-2#4300]
I don't know if any other mods do this, but [IC2C](https://github.com/TinyModularThings/IC2Classic) uses something they call "stack crafting", where some crafting recipes require a stack of multiple items in a single slot. For example, the Industrial Worktable is crafted with
Hopper, 4x Electronic Circuit, Hopper
Nano Tool Box, 28x Crafting Table, Nano Tool Box
Hopper, Machine Block, Hopper

Currently in AE2 (rv6-stable-7), I cannot create a crafting pattern with multiple items per slot using the pattern terminal. I tried hacking one in anyway and placing it in an interface with an assembler, but I got an error in the chat when I tried to autocraft with it. I also tried placing the hacked pattern in the assembler directly and inserting the items into it, and it only allowed 1 item in each stack, but it crafted the item anyway once each slot had an item, so it used up fewer items than the recipe called for.

**Describe the feature**
The Pattern Terminal will allow multiple items per slot in crafting mode, not just processing mode. Molecular Assemblers will allow and require multiple items per slot if the recipe calls for them. Autocrafting will be able to process these patterns and craft them just like any other crafting pattern.

**Reasons why it should be considered**
This works in the vanilla crafting table, as well as some modded equivalents. It is not a feature IC2C added, merely a very rarely used one. AE2 should be able to craft anything the vanilla crafting table can, so it should be able to do this.

**Comment by yueh** [comment]
Vanilla shaped/shapeless recipes have no way of specifying any sort of amount for inputs.

If some mod changes this, they most likely patch the vanilla crafting table directly or use the assumption that they have an inventory and delete the items after crafting it. Which would also explain why it does not work in all cases.

As long as vanilla recipes do not support specifying an amount, there simply will not be any support for it. We can only take recipes into account and not some arbitrary assumptions about every crafting table being able to store a full stack of ingredients or similar.
