### ISSUE TITLE
Is AE2 going to get anymore updates?

### ISSUE THREAD

**Issue by Zorro8183** [AppliedEnergistics/Applied-Energistics-2#4305]
**Describe the feature**

**Reasons why it should be considered**

**Additional Context**

**Comment by 34486** [comment]
What do you think? Are they fixing issues? Is there activity on their GIT? Are they still responding and helping? If these are yes, they PROBABLY will update. Now if its to 1.15.2 or something, who knows, only they do! I can't speak for them, but they can get done as much as they can get done.

**Comment by yueh** [comment]
Maybe?
