### ISSUE TITLE
Cannot create Quantum Entangled Singularities

### ISSUE THREAD

**Issue by devapple** [AppliedEnergistics/Applied-Energistics-2#4306]
Description:

I haven't been able to create the Singularities, I'm using the Ender Dust (From AE2) and I made the singularity in a Matter Condenser (if that even matters) and normal TNT.

**To Reproduce**
Just going about making Quantum Singularities.

**Expected behavior**
To drop a Singularity and Ender Dust and explode it.

**Additional context**
none to give.

**Environment**
SMP Server. Is all i can really give.

- Minecraft Version: 1.12.2
- AE2 Version: RV6 Stable 7
- Forge Version: Unsure most likely the newest version. (just updated it)

**Comment by yueh** [comment]
I would recommend asking your server admin or maybe modpack author about it.

At first glance it looks like they disabled the recipe or explosions. Using Tiny TNT might also be an idea as it is somewhat designed to work around some cases, which can be disabled on a server. If that item is not disabled, too.
