### ISSUE TITLE
ME Formation Plane Placing Order?

### ISSUE THREAD

**Issue by b3ntastic** [AppliedEnergistics/Applied-Energistics-2#4308]
Description:

So I am playing Direwolf20 with a few friends and am working on a Wither-Farm and I am using the ME Formation Planes to place the Soulsand and the Skull, everything works fine but one thing. The lower piece of the Soulsand is being placed last, means that the 3 Skulls are being placed before the body is complete and thus the Wither will not spawn. I tried changing priority in the interface and also in the Formation Planes, but nothing changes.

So I am asking if anyone could tell me a way to delay the one skull being placed, so it is placed last or how to fix my problem / speed up the Soulsand being placed.

Thank you in advance :)

Minecraft Version: 1.12.2
AE2 Version: 1.7.2
Forge Version: 14.23.5

**Comment by yueh** [comment]
Formation planes are passive components. They do not actively do anything. Therefore the placement order simply depends on the insertion order for the items entering the ME network.

The priority would only be useful when multiple formation planes handle the same items. Say to ensure the bottom soulsand is placed first or the skulls are placed left to right or similar.

So the only option would be to insert every soulsand into the network before the skulls are added.
