### ISSUE TITLE
Cable Facade as separate sum mod

### ISSUE THREAD

**Issue by warderbrad** [AppliedEnergistics/Applied-Energistics-2#4310]
I am suggesting that the cable facades are moved to their own sub-mod (probably AE2 Cable Facades)

With NEI there is some way to hide them but for users of JEI, we don't have any such things.

The reason for this is a user interface part with JEI. As it is now the AE2 mod has 14 pages of JEI entries. of those nearly (if not) 13 pages of those are just cable facades. When a user is trying to find a device to build and uses @Applied then they have to scroll through many pages (unless they remember to just go back on the first page). If the facades were in a separate mod then the user could use @Applied (as long as the new mod does not start with that) and only get the items that are needed. Also, users looking for a facade and wanting to browse can open just them as well.

**Comment by yueh** [comment]
This is not possible at this point. Moving them to a separate mod would destroy every existing facade and force players to craft and place them again. Or alternatively offer both facades and double the amount of JEI entries.

**Comment by Ommina** [comment]
I share your annoyance with scrolling through pages of facades.  However, JEI _DOES_ have a way to hide the facades, at least up through 1.12.2.  This can be done either by the player, or distributed as part of the JEI configs by the pack developer.
