### ISSUE TITLE
Mystical Mechanics API Support for Quartz Grindstone

### ISSUE THREAD

**Issue by drhaber** [AppliedEnergistics/Applied-Energistics-2#4312]
What I hope is a simple™ idea. The Quartz Grindstone which currently has a crank for usage, would benefit tremendously if it had support for the [Mystical Mechanics API](https://www.curseforge.com/minecraft/mc-mods/mysticalmechanics).

**Comment by yueh** [comment]
The grindstone is by design for manual use.
