### ISSUE TITLE
AE2 blocks (e.g. ME Drive) don't connect to the right channel provider

### ISSUE THREAD

**Issue by Vintschente** [AppliedEnergistics/Applied-Energistics-2#4313]
**Describe the bug**
Multiple blocks like ME Drives next to each other like a wall are additionally connected with dyed cables on the back but instead of connecting to the cable that provides the channels they connect to each other.

**Expected behavior**
All blocks search for a valid connection channel and work.

- Minecraft Version: 
- AE2 Version: 1.12.2 rv6-stable-7
- Forge Version: 14.23.5.2847

**Comment by mindforger** [comment]
pathing (to my understanding) is done in the most cost efficient way to not have servers grind to a halt when large networks are onlined, resulting in "compromises" with pathfinding for channels
