### ISSUE TITLE
Will AE be updated to 1.15?

### ISSUE THREAD

**Issue by ClaudiusMinimus** [AppliedEnergistics/Applied-Energistics-2#4319]
I was wondering if AE will be updated to 1.15. I'm developing a pack and would love to add your mod, even if it is in alpha. Several major mods are included in the pack that have not yet been made public and will not publish with those mods included until they are public on curseforge. Please let me know if you are interested.
Thank you,
CM

**Comment by yueh** [comment]
Maybe if there is enough time.
