### ISSUE TITLE
Competition between AE2 and Flan's MOD

### ISSUE THREAD

**Issue by sirohigan** [AppliedEnergistics/Applied-Energistics-2#4320]
**Describe the bug**

If you try to install AppliedEnergistics2 and Flan'sMod at the same time, a crash will occur in InitializingModsPhase3, the fifth stage of the startup phase.
If only one of them, it was able to start normally.
What causes this phenomenon?
Sorry to trouble you, but could you do the investigation?

**To Reproduce**

Start minecraft after putting AE2 and Flan'sMOD in the mods folder.

**Expected behavior**

At the same time you can use the AE2 and Flan's MOD.

**Additional context**

<script src="https://gist.github.com/sirohigan/0edfc3504d25671009ef65079aaf0ca9.js"></script>
https://gist.github.com/sirohigan/0edfc3504d25671009ef65079aaf0ca9

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-7
- Forge Version:14.23.5.2768
- Flan's MOD Version: 5.5.2 (for 1.12.2)

**Comment by mindforger** [comment]
> java.lang.IllegalArgumentException: Failed to register dimension for id 2, One is already registered

the crash report is pretty clear on your issue

change your config :)
