### ISSUE TITLE
Incapable of using ME storage.

### ISSUE THREAD

**Issue by The-Math-Maniac1** [AppliedEnergistics/Applied-Energistics-2#4321]
I have set up an ME storage system, with all the necessary parts of it, (ME controller, drive, power, terminal, etc...) and when I open it, it shows all the storage in it but does not allow me to put any items in. I did NOT use the security terminal and I used the creative storage cell. I replicated a storage system I have used on a server exactly the same in my own world. The one on the server I was able to access. The one in the world I was not.

To recreate, place an ME controller, place a creative energy cell underneath, an ME drive to the right, and put a creative storage cell into the drive, then put a fluix glass cable on the top of the controller, and a regular terminal on the side of the fluix glass cable. I have also tried putting the cable and terminal on the drive and nothing changed.

What I expected was to be able to access the storage and put items inside, just like one would normally do with an ME storage system.

For the modpack I am using, go here: https://drive.google.com/drive/folders/1hLqpFKR-_-aqToxS5bhCRukHrAvH9sFf?usp=sharing 
Minecraft version 1.12.2
AE2 Version Latest 
Forge Version 14.23.5.2846 for Minecraft 1.12.2 on Windows

**Comment by yueh** [comment]
Creative cells are readonly.
