### ISSUE TITLE
Lag issues when loading items in AE

### ISSUE THREAD

**Issue by Guniek** [AppliedEnergistics/Applied-Energistics-2#4325]
**Describe the bug**
AE seems to sending a lot of packets when loading many items with NBT Tags.

**To Reproduce**
Add AE2 mod to server with ~50 players and 120 mods. Then throw many items with NBT Tags to AE network. Then when you try to open AE, a lot of packets are sent.

**Additional context**
![image](https://user-images.githubusercontent.com/52070471/78451076-8d33d880-7683-11ea-8135-2f9fa1d9c7fb.png)

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-7
- Forge Version: 14.23.5.2847

**Comment by mindforger** [comment]
isn't that the purpose of AE2 to show your items? implying it has to transfer the data to your client then?

**Comment by yueh** [comment]
Sending the data to a client is a simple necessity to display it. ME networks just store more compared to vanilla chests, therefore it will also send more data. NBT data on top requires even more data, but that is just how minecraft works.

**Comment by DEv0on** [comment]
AE2 is sending a lot of data, so why you cant do simple event what is called by any AE2 item change, then send new item list to player

**Comment by mindforger** [comment]
Feel invited to implement that feature and file a pull request if it is that easy. AE2 Team sure could need some helping hands with their hard work.
