### ISSUE TITLE
crashes in modpack

### ISSUE THREAD

**Issue by devomaa** [AppliedEnergistics/Applied-Energistics-2#4326]
#### Description

it crashed?
#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-7
- Forge Version: 14.23.5.2847
Log: https://pastebin.com/4pfvTUUM

 Mods:
  [📁] 1.12 (folder)
  [✔️] ae2stuff-0.5.0.56-mc1.7.10
  [✔️] AE2WTLib-1.12.2-1.0.34
  [✔️] appliedenergistics2-rv6-stable-7(1)
  [✔️] AppliedFluidics-1.12.2-2.0.3
  [✔️] AutoRegLib-1.3-32
  [✔️] Backups-1.12.2-1.5.4
  [✔️] Baubles-1.12-1.5.2
  [✔️] betterhud-1.12.2-1.4.1
  [✔️] cc-tweaked-1.12.2-1.86.0
  [✔️] CD4017BE_lib-1.12.2-6.4.17.1
  [✔️] Chisel-MC1.12.2-1.0.1.44
  [✔️] CodeChickenLib-1.12.2-3.2.3.358-universal
  [✔️] Commons0815-1.12.2-1.3.7
  [✔️] Computronics-1.12.2-1.6.6-squid-02
  [✔️] CTM-MC1.12.2-1.0.1.30
  [✔️] EnderCore-1.12.2-0.5.73
  [✔️] EnderIO-1.12.2-5.1.55
  [✔️] EnderIO-endergy-1.12.2-5.1.55
  [✔️] EnderIO-zoo-1.12.2-5.1.55
  [✔️] EnderStorage-1.12.2-2.4.6.137-universal
  [✔️] ExtraCells-1.7.10-2.3.14b200
  [✔️] extrautils2-1.12-1.9.9
  [✔️] FacadePainter-1.12.2-1.0.0-RC3
  [✔️] felling-1.4.1-1.12.x
  [✔️] firstaid-1.6.7
  [✔️] foamfix-0.10.10-1.12.2
  [✔️] Forgelin-1.8.4(3)
  [✔️] funky-locomotion-1.12.2-1.1.2
  [✔️] GasConduits-1.12.2-1.2.2
  [✔️] Hwyla-1.8.26-B41_1.12.2
  [✔️] iChunUtil-1.12.2-7.2.2(1)
  [✔️] industrialcraft-2-2.8.194-ex112
  [✔️] InventoryTweaks-1.64+dev.146
  [✔️] ironchest-1.12.2-7.0.72.847
  [✔️] jei_1.12.2-4.15.0.293
  [✔️] JustEnoughEnergistics-1.12.2-1.0.8
  [✔️] LogisticsBridge-1.3.1
  [✔️] logisticspipes-0.9.3.132
  [✔️] LunatriusCore-1.12.2-1.2.0.42-universal(2)
  [✔️] mahoutsukai-1.12.2-v1.15.3(1)
  [✔️] Mantle-1.12-1.3.3.55
  [✔️] Mekanism-1.12.2-9.8.3.390(1)
  [📁] memory_repo (folder)
  [✔️] MrTJPCore-1.12.2-2.1.4.43-universal
  [✔️] OpenComputers-MC1.12.2-1.7.5.192
  [✔️] OpenGlasses-MC1.12.2-2.2-50
  [✔️] OpenPrinter-1.12.2-0.1.0.9
  [✔️] p455w0rdslib-1.12.2-2.3.161
  [✔️] Pam's+HarvestCraft+1.12.2zf
  [✔️] plethora-1.12.2-1.2.3
  [✔️] ProjectRed-1.12.2-4.9.4.120-Base
  [✔️] ProjectRed-1.12.2-4.9.4.120-compat
  [✔️] ProjectRed-1.12.2-4.9.4.120-fabrication
  [✔️] ProjectRed-1.12.2-4.9.4.120-integration
  [✔️] ProjectRed-1.12.2-4.9.4.120-lighting
  [✔️] ProjectRed-1.12.2-4.9.4.120-mechanical
  [✔️] ProjectRed-1.12.2-4.9.4.120-world
  [✔️] PTRLib-1.0.4
  [✔️] Quark-r1.6-177
  [✔️] reauth-3.6.0
  [✔️] Redstone+++ver1.3d
  [✔️] refinedstorage-1.6.15
  [✔️] ResourceLoader-MC1.12.1-1.5.3
  [✔️] Schematica-1.12.2-1.8.0.169-universal(1)
  [✔️] stellarfluidconduit-1.12.2-1.0.2a
  [✔️] stg-1.12.2-1.2.3
  [✔️] TConstruct-1.12.2-2.13.0.179
  [✔️] Tesla-1.12.2-1.0.63
  [✔️] TIS-3D-MC1.12.2-1.5.1.37
  [✔️] UniDict-1.12.2-2.9.6
  [✔️] veining-1.3.2-1.12.x
  [✔️] WanionLib-1.12.2-2.4
  [✔️] weirdinggadget-1.12.2-2.1.16-universal
  [✔️] WirelessFluidTerminal-1.12.2-1.0.4
  [✔️] WirelessInterfaceTerminal-1.12.2-1.0.2
  [✔️] WirelessPatternTerminal-1.12.2-1.0.3
  [✔️] worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist(3)
  [✔️] Xaeros_Minimap_1.19.5_Forge_1.12
  [✔️] zerocore-1.12.2-0.1.2.8

**Comment by yueh** [comment]
`Failed to register dimension for id 2, One is already registered`

**Comment by devomaa** [comment]
after checking every file, i don't see anything using the dimension 2

**Comment by mindforger** [comment]
>you guys should add a way to change the dimension IDs for it in the config

and you should read the config and find the actual existing option there

**Comment by Ommina** [comment]
ae2stuff-0.5.0.56-mc1.7.10 ?
AppliedFluidics-1.12.2-2.0.3 ?
ExtraCells-1.7.10-2.3.14b200 ?
