### ISSUE TITLE
AE2 Auto-Crafting Problem

### ISSUE THREAD

**Issue by Khaldonis** [AppliedEnergistics/Applied-Energistics-2#4328]
Minecraft Version - 1.7.10
AE2 Version - rv3-beta-6
Forge Version - 10.13.4.1614
Modpack - Voltz Community Modpack

I've created an AE2 storage system that I'm trying to add auto-crafting so I can automate the crafting of compressed cobblestone.  I've looked at multiple tutorials and I appear to have everything set up correctly.  However, when I create an order for compressed cobblestone, it sits in the crafting monitor and is never actually crafted.  

I have the system hooked up to plenty of power, I've double-checked to make sure the recipe encoded correctly, and I've swapped out the ME glass cables for smart and dense cables with no effect.  The ME controller has 4 channels going into the storage system on the right, and two channels going into the crafting system on the left.  Each device is powered and shows as "Device Online".  

I've attached some screenshots that will help, hopefully.

![screenshot 1](https://user-images.githubusercontent.com/63174267/78464180-fe8b7f80-76b3-11ea-9447-3ac3c2a6f3ac.jpg)
![screenshot 6](https://user-images.githubusercontent.com/63174267/78464201-30044b00-76b4-11ea-8186-27a418be91ad.jpg)
![screenshot 3](https://user-images.githubusercontent.com/63174267/78464183-00554300-76b4-11ea-8c71-320a2b0fdc8a.jpg)
![screenshot 4](https://user-images.githubusercontent.com/63174267/78464184-00edd980-76b4-11ea-8c5e-1590edbb6536.jpg)
![screenshot 5](https://user-images.githubusercontent.com/63174267/78464185-01867000-76b4-11ea-87eb-a8a2f29ec000.jpg)

**Comment by mindforger** [comment]
1.7.10 is not supported anymore, also the way your setup is unclear about your pattern setup, check if the are actually crafting pattern and no processing pattern
