### ISSUE TITLE
Can generate infinite of any molten fluid with the fluid formation plane/fluid interface

### ISSUE THREAD

**Issue by AlphaWarrior987** [AppliedEnergistics/Applied-Energistics-2#4330]
When using the fluid formation plane (FFP), fluid annihilation plane (FAP) and a fluid interface (FI)
You can generate infinite, molten liquids.  

Starting with the M.E network, create/supply any molten fluid into a F.I making sure that you have at least 2000mb. (Image A) further testing showed will work with 2000mb
![ImageA](https://user-images.githubusercontent.com/38117939/78532153-b86a1500-77b4-11ea-9b9f-6b76a773e692.jpg)
Connect a FFP up to network, with an FAP. (Image B),
![ImageB](https://user-images.githubusercontent.com/38117939/78532159-ba33d880-77b4-11ea-82d1-9c81ed0aa16b.jpg)
Do note that this Network does **NOT** have any Fluid storage connected. This should mean the fluid should stay in the F.I
**SIDE**
The Duplication process occurs with only the F.I and the FFP
the FAP is just the easiest way to "harvest."

 If any fluid storage tank or drive is introduced to the main network the interface will send its fluid to the tank/drive thus removing the liquid from the interface which results in the dupe not working.
With these steps you have the FFP placing the fluid down and the FAP should try to pick up but no storage to go to. However if you now remove the FAP from the main network and create a sub net for the FAP, and provide a storage tank on the sub net, the FAP will pick it up and store.
![ImageC](https://user-images.githubusercontent.com/38117939/78532164-bbfd9c00-77b4-11ea-8d50-1bdce38b82fc.jpg)

This should in turn make the Main network's F.I lose its stored fluid, however it does not.
**Note I tested with only single bucket worth and it does consume the Fluid
This infinite fluid state occurs when there is at least 2000mb**

**Expected behavior**
The fluid should be moved from the main network into the sub net however, while consuming the "buffer" of the F.I
Also Tested this on a single player world with **ONLY** AE2 install 
same version of MC/AE2/Forge

Same results happen with good old lava buckets
![Vanilla Bug1](https://user-images.githubusercontent.com/38117939/78537079-e6535780-77bc-11ea-90dc-55b1fd040472.jpg)
Provided World save to see the process in action

[New World.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/4437004/New.World.zip)
-250 X / 66 Y / 212 Z Cords where the device is in the vanilla world just in case

I discovered this while playing on a multiplayer world, locally hosted server with a custom Mod list (all stock)
Mod list
![Mod List](https://user-images.githubusercontent.com/38117939/78532731-c10f1b00-77b5-11ea-8b92-614aa5f27148.jpg)

- Minecraft Version:  1.12.2
- AE2 Version: rv6-stable-7
- Forge Version: 14.23.5.2847

**Comment by Ommina** [comment]
Since I had a pack open, I tried this out.  That means this is _not_ with AE2 only.

- Placed Fluid Interface in world.
- Piped exactly two buckets of water into the Fluid Interface.
- Connected a Fluid Formation Plane.
- Plane placed a water block into the world; fluid stored in Interface remained at 2000mb.

If this has been reported before, I sure don't remember it.

**Comment by yueh** [comment]
Appears to be a problem with how fluid interfaces handle leftover amounts with some central method.

Changing it does not seem to be particular difficult, but it will break a commonly used function. So there is a good chance of it breaking something major. Like replacing one dupe bug with another one.

It would really need a larger API change to handle it in a more sane way. But that is in my opinion no longer an option for 1.12.

**Comment by shartte** [comment]
Fixed in next 1.15 alpha
