### ISSUE TITLE
Not an issue: question about server client relationship

### ISSUE THREAD

**Issue by frizzle101101** [AppliedEnergistics/Applied-Energistics-2#4335]
Im kinda new to minecraft moding and am trying to figure out how the client interacts with the server. If someone could explaain calls such as 
NetworkHandler.instance().sendToServer(	new PacketValueConfig( "PatternTerminal.CraftMode", CRAFTMODE_PROCESSING ) );

I get that this sets the bool variable on the server but what im wondering is how does the gui switch as a result of this line, does the server then respond to the client and calls the gui? where are these variables and actions defined? just wondering how this communication pipeline works.

**Comment by yueh** [comment]
These packets are mostly used to synchronize the client state to the server, but there is no way back or confirmation. 

As nearly all settings are clientside, waiting for the server to response would be very irritating on connections with a high latency. E.g. clicking a button and it will not update for half a second. Or change for half a second and then immediately switch back to the old state.

The issue tracker is probably also not the best place for these kinds of discussions.

**Comment by frizzle101101** [comment]
Where can i ask you questions about these things
