### ISSUE TITLE
Cannot process my auto craft for mekanism mod (using elite energy cube)

### ISSUE THREAD

**Issue by htachoires** [AppliedEnergistics/Applied-Energistics-2#4337]
**Describe the bug**
Auto crafting using elite energy cube of mekanism can't process. I have the following message

**To Reproduce**
create elite energy cube of mekanism to be in autocraft and create an auto craft using the elite energy cube. for example ultimate energy cube, and when you ask to craft the ultimate in the applied system the fallback message appear 

**Expected behavior**
Like normal behavior of applied make my craft available using auto crafting system

**Additional context**
`[03:11:29] [Server thread/WARN] [AE2:S]: Using CraftingManager fallback: Recipe <mekanism:basicblock2_3_alt_alt> for output <1xtile.BasicBlock2@3> rejected inputs [1xitem.EnergyTablet@0, 1xtile.BasicBlock2@3, 1xitem.EnergyTablet@0, 1xtile.BasicBlock2@3, 1xtile.EnergyCube@0, 1xtile.BasicBlock2@3, 1xitem.EnergyTablet@0, 1xtile.BasicBlock2@3, 1xitem.EnergyTablet@0]. NOT FOUND, please report.
`
[Image Craft](https://cdn.discordapp.com/attachments/683001967215509546/699065877428961330/unknown.png)
[Image Console](https://cdn.discordapp.com/attachments/683001967215509546/699066189766459432/Capture_decran_de_2020-04-13_03-19-01.png)

**Environment**
I am using mekanism mod

- Minecraft Version:  1.12.2
- AE2 Version: rv6-stable7
- Forge Version: 14.23.5.2847

**Comment by yueh** [comment]
The warning just indicates we have to use a fallback option, which can introduce a serious performance issue. But that can only be fixed by the mod or modpack adding this particular recipe.

Otherwise I would recommend forwarding it to your modpack. Many are using AE2 addons which will cause autocrafting to break.

**Comment by htachoires** [comment]
Thanks for your reply, I'm searching ae2 addons to add this craft but i'm not finding it, can you leave a clue ?

**Comment by htachoires** [comment]
Alright, I find the solution. **Mekanism using tags** for owner and config sides. When you create your auto craft for energy cubes, tags are _'not set'_. Later when you'll create auto craft using energy cubes or other stuff with tags, you **MUST** use the **direct output of ae2 gave you**. if you use energy cube already placed or configured and use it for autocrafting settings, it won't work !

**Comment by htachoires** [comment]
> The warning just indicates we have to use a fallback option, which can introduce a serious performance issue. But that can only be fixed by the mod or modpack adding this particular recipe.
> 
> Otherwise I would recommend forwarding it to your modpack. Many are using AE2 addons which will cause autocrafting to break.

Alright, I find the solution. Mekanism using tags for owner and config sides. When you create your auto craft for energy cubes, tags are 'not set'. Later when you'll create auto craft using energy cubes or other stuff with tags, you MUST use the direct output of ae2 gave you. if you use energy cube already placed or configured and use it for autocrafting settings, it won't work !

**Comment by yueh** [comment]
Yes, mekanism here is a particular bad example here. On one hand they use nbt data for config, charge level, or similar, which we would have to ignore. On the other one, they use nbt for the actual item like every energy cube is the same item with a different type tag, which of course cannot be ignored for crafting or actually anything. And there is no way to know, which one is important and which ones are not.

There are (or at least were) other mods, which add random nbt tags to items. Pretty much causing the same issue. Or AE2 addons introducing invalid itemstacks into patterns.
