### ISSUE TITLE
Game crashed

### ISSUE THREAD

**Issue by Warrendi** [AppliedEnergistics/Applied-Energistics-2#4338]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  HCASM (HammerLib-1.12.2-2.0.6.14.jar)
  MovingWorldCore (movingworld-1.12-6.342-full.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 4/13/20 4:12 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Energistics 2 (appliedenergistics2)
Caused by: java.lang.IllegalArgumentException: Failed to register dimension for id 2, One is already registered
	at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:134)
	at appeng.core.Registration.registerSpatialDimension(Registration.java:201)
	at appeng.core.Registration.postInit(Registration.java:352)
	at appeng.core.AppEng.postInit(AppEng.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 112735632 bytes (107 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 56 mods loaded, 56 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                           | Version           | Source                                        | Signature                                |
	|:----- |:-------------------------------------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJ | minecraft                                    | 1.12.2            | minecraft.jar                                 | None                                     |
	| LCHIJ | mcp                                          | 9.42              | minecraft.jar                                 | None                                     |
	| LCHIJ | FML                                          | 8.0.99.99         | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCHIJ | forge                                        | 14.23.5.2847      | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCHIJ | com.elytradev.movingworld.common.asm.coremod |                   | minecraft.jar                                 | None                                     |
	| LCHIJ | openmodscore                                 | 0.12.1            | minecraft.jar                                 | None                                     |
	| LCHIJ | securitycraft                                | v1.8.17           | [1.12.2]+SecurityCraft+v1.8.17.jar            | None                                     |
	| LCHIE | appliedenergistics2                          | rv6-stable-7      | appliedenergistics2-rv6-stable-7 (5).jar      | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHI  | bdlib                                        | 1.14.3.12         | bdlib-1.14.3.12-mc1.12.2.jar                  | None                                     |
	| LCHI  | ae2stuff                                     | 0.7.0.4           | ae2stuff-0.7.0.4-mc1.12.2 (1).jar             | None                                     |
	| LCHI  | baubles                                      | 1.5.2             | Baubles-1.12-1.5.2 (1).jar                    | None                                     |
	| LCHI  | jei                                          | 4.15.0.269        | jei_1.12.2-4.15.0.269.jar                     | None                                     |
	| LCHI  | projecte                                     | 1.12.2-PE1.4.1    | ProjectE-1.12.2-PE1.4.1.jar                   | None                                     |
	| LCHI  | redstoneflux                                 | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar       | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHI  | thaumcraft                                   | 6.1.BETA26        | Thaumcraft-1.12.2-6.1.BETA26 (1).jar          | None                                     |
	| LCHI  | p455w0rdslib                                 | 2.3.161           | p455w0rdslib-1.12.2-2.3.161.jar               | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCHI  | ae2wtlib                                     | 1.0.34            | AE2WTLib-1.12.2-1.0.34 (1).jar                | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCHI  | biomesoplenty                                | 7.0.1.2427        | BiomesOPlenty-1.12.2-7.0.1.2427-universal.jar | None                                     |
	| LCHI  | blockarmor                                   | 2.4.11            | BlockArmor-1.12.2-2.4.11.jar                  | None                                     |
	| LCHI  | chameleon                                    | 1.12-4.1.3        | Chameleon-1.12-4.1.3.jar                      | None                                     |
	| LCHI  | clienttweaks                                 | 3.1.11            | ClientTweaks_1.12.2-3.1.11.jar                | None                                     |
	| LCHI  | movingworld                                  | 1.12-6.342        | movingworld-1.12-6.342-full.jar               | None                                     |
	| LCHI  | davincisvessels                              | @DVESSELSVER@     | davincisvessels-1.12-6.340-full.jar           | None                                     |
	| LCHI  | ptrmodellib                                  | 1.0.4             | PTRLib-1.0.4 (1).jar                          | None                                     |
	| LCHI  | props                                        | 2.6.3             | Decocraft-2.6.3_1.12.2 (1).jar                | None                                     |
	| LCHI  | hammercore                                   | 2.0.6.14          | HammerLib-1.12.2-2.0.6.14.jar                 | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCHI  | expequiv                                     | 13r               | ExpandedEquivalence-1.12.2-13r.jar            | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHI  | extracells                                   | 2.6.5             | ExtraCells-1.12.2-2.6.5.jar                   | None                                     |
	| LCHI  | extrautils2                                  | 1.0               | extrautils2-1.12-1.9.9.jar                    | None                                     |
	| LCHI  | fpsreducer                                   | mc1.12.2-1.12.4   | FpsReducer-mc1.12.2-1.12.4.jar                | None                                     |
	| LCHI  | cfm                                          | 6.3.1             | furniture-6.3.1-1.12.2 (1).jar                | None                                     |
	| LCHI  | immersiveengineering                         | 0.12-92           | ImmersiveEngineering-0.12-92.jar              | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCHI  | immersivecables                              | 1.3.2             | ImmersiveCables-1.12.2-1.3.2.jar              | None                                     |
	| LCHI  | ironchest                                    | 1.12.2-7.0.59.842 | ironchest-1.12.2-7.0.59.842.jar               | None                                     |
	| LCHI  | journeymap                                   | 1.12.2-5.5.4      | journeymap-1.12.2-5.5.4.jar                   | None                                     |
	| LCHI  | jee                                          | 1.0.8             | JustEnoughEnergistics-1.12.2-1.0.8.jar        | None                                     |
	| LCHI  | mcmultipart                                  | 2.5.3             | MCMultiPart-2.5.3.jar                         | None                                     |
	| LCHI  | mo_swords                                    | v5                | moSwords-1.12.2v5.jar                         | None                                     |
	| LCHI  | openmods                                     | 0.12.1            | OpenModsLib-1.12.2-0.12.1.jar                 | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHI  | openblocks                                   | 1.8               | OpenBlocks-1.12.2-1.8.jar                     | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHI  | oretweaker                                   | 1.0.2-1.12.0      | Ore Tweaker-1.0.2-1.12.0.jar                  | None                                     |
	| LCHI  | oreexcavation                                | 1.4.137           | OreExcavation-1.4.137.jar                     | None                                     |
	| LCHI  | orespawn                                     | 3.3.1             | OreSpawn-1.12-3.3.1.167.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHI  | sonarcore                                    | 5.0.19            | sonarcore-1.12.2-5.0.19-20.jar                | None                                     |
	| LCHI  | practicallogistics2                          | 3.0.8             | practicallogistics2-1.12.2-3.0.8-11.jar       | None                                     |
	| LCHI  | storagedrawers                               | 1.12-5.3.5        | StorageDrawers-1.12.2-5.3.8.jar               | None                                     |
	| LCHI  | storagedrawersextra                          | @VERSION@         | StorageDrawersExtras-1.12-3.1.0.jar           | None                                     |
	| LCHI  | switchbow                                    | 1.5.7             | switchbow-1.5.7.jar                           | None                                     |
	| LCHI  | tardis                                       | 0.1.3A            | tardis-0.1.3A.jar                             | None                                     |
	| LCHI  | thaumicenergistics                           | 2.2.3             | thaumicenergistics-2.2.4.jar                  | None                                     |
	| LCHI  | wanionlib                                    | 1.12.2-2.4        | WanionLib-1.12.2-2.4.jar                      | None                                     |
	| LCHI  | wct                                          | 3.12.97           | WirelessCraftingTerminal-1.12.2-3.12.97.jar   | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCHI  | wit                                          | 1.0.2             | WirelessInterfaceTerminal-1.12.2-1.0.2.jar    | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCHI  | wpt                                          | 1.0.3             | WirelessPatternTerminal-1.12.2-1.0.3.jar      | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCHI  | orelib                                       | 3.5.2.2           | OreLib-1.12.2-3.5.2.2.jar                     | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHI  | unidict                                      | 1.12.2-2.9.6      | UniDict-1.12.2-2.9.6.jar                      | None                                     |

	Loaded coremods (and transformers): 
HCASM (HammerLib-1.12.2-2.0.6.14.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
MovingWorldCore (movingworld-1.12-6.342-full.jar)
  
IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
  openmods.core.OpenModsClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4358' Renderer: 'Intel(R) HD Graphics 4000'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	HammerCore Debug Information: 
Dependent Mods:
    -Expanded Equivalence (expequiv) @13r

	List of loaded APIs: 
		* ae2wtlib|API (1.0.34) from AE2WTLib-1.12.2-1.0.34 (1).jar
		* appliedenergistics2|API (rv6) from appliedenergistics2-rv6-stable-7 (5).jar
		* Baubles|API (1.4.0.2) from Baubles-1.12-1.5.2 (1).jar
		* CSLib|API (1.0.1) from PTRLib-1.0.4 (1).jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.12-92.jar
		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.12-92.jar
		* journeymap|client-api (1.4) from journeymap-1.12.2-5.5.4.jar
		* journeymap|client-api-display (1.4) from journeymap-1.12.2-5.5.4.jar
		* journeymap|client-api-event (1.4) from journeymap-1.12.2-5.5.4.jar
		* journeymap|client-api-model (1.4) from journeymap-1.12.2-5.5.4.jar
		* journeymap|client-api-util (1.4) from journeymap-1.12.2-5.5.4.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.15.0.269.jar
		* openblocks|api (1.2) from OpenBlocks-1.12.2-1.8.jar
		* practicallogistics2-api (3.1) from practicallogistics2-1.12.2-3.0.8-11.jar
		* projecteapi (1.12.2-1.2.0) from ProjectE-1.12.2-PE1.4.1.jar
		* redstonefluxapi (2.1.0) from RedstoneFlux-1.12-2.1.0.6-universal.jar
		* SecurityCraftAPI (1.2.3) from [1.12.2]+SecurityCraft+v1.8.17.jar
		* sonarapi (1.0.1) from sonarcore-1.12.2-5.0.19-20.jar
		* StorageDrawersAPI (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
		* StorageDrawersAPI|event (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
		* StorageDrawersAPI|registry (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
		* StorageDrawersAPI|render (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
		* StorageDrawersAPI|storage (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
		* StorageDrawersAPI|storage-attribute (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
		* Thaumcraft|API (6.0.2) from Thaumcraft-1.12.2-6.1.BETA26 (1).jar
		* wct|api (1.1) from WirelessCraftingTerminal-1.12.2-3.12.97.jar
		* wit|api (1.0.2) from WirelessInterfaceTerminal-1.12.2-1.0.2.jar
		* wpt|api (1.0.3) from WirelessPatternTerminal-1.12.2-1.0.3.jar

**Comment by yueh** [comment]
`Failed to register dimension for id 2, One is already registered`

**Comment by Warrendi** [comment]
But I only have one I put one and removed the other one

**Comment by yueh** [comment]
Just removing it will not work, the old one is still registered by forge. Just change the id.

**Comment by Shadowninja397** [comment]
how do we change the id?
