### ISSUE TITLE
Infinite Stashing Using Shulker Box

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [AppliedEnergistics/Applied-Energistics-2#4339]
**Describe the bug**
Portable Cells Can Store Shulker boxes That contain Portable Cell.

**To Reproduce**
1. Insert Portable Cells Into Shulker Box.
2. Insert Shulker boxes That contain Portable Cell Into Portable Cell.

**Expected behavior**
Portable Cells Don't Store Shulker boxes That contain Portable Cell.

**Environment**
- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable7
- Forge Version: 14.23.5.2847

**Comment by yueh** [comment]
There is no way to reliably detect any sort of bag item. While it would be somewhat possible to forbid shulker boxes in cells, someone could just use the next backpack mod to circumvent it.

This is really something Forge or even Minecraft has to resolve by introducing a common way to determine if an item can store other items or not.
