### ISSUE TITLE
Interface and cable visual glitch

### ISSUE THREAD

**Issue by Beidub** [AppliedEnergistics/Applied-Energistics-2#4342]
I'm playing in a modpack and just got to AE2 and trying it for the first time. I install my interface and my cables, and they all have the same visual glitch, as seen in the provided screenshot. 

I am playing on the TCR Classic Refined 1.12+ Version 2.5.1, which uses Applied Energistics 2, AE2 Stuff, Extra Cells and Wireless Crafting Terminal

I've seen people mentionning Optifine might be the problem, but it's not installed in this modpack. The only things around my structure are a cactus farm and a chunk loader. I cannot install Optifine to possibly solve this problem, as the modpack doesn't even want to start when I try to include it in.

I can still access the terminals, the glitch is just very obnoxious to work with.
Thank you for a possible solution

![2020-04-13_20 26 18](https://user-images.githubusercontent.com/63621707/79173473-9fb9ba80-7dc5-11ea-82cb-22714a417be1.png)

**Comment by Beidub** [comment]
Nothing?

**Comment by mindforger** [comment]
You provided not nearly enough information to properly help you, but since i have seen this kind of glitch on ender io tracker and it was some other mod, i would say it is not an AE2 issue

**Comment by Beidub** [comment]
Thank you, I didn't know the lack of information was actually the issue here ^^"
Crashlog is here, I honestly hope this will be enough

[crash-2020-04-19_13.51.11-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/4499856/crash-2020-04-19_13.51.11-client.txt)

**Comment by mindforger** [comment]
Next time please use pastebin for the report, please try in a copy world without malisis doors (dont forget the core mods) as far as i remember it was one of the reasons, also i am gonna close this es it is another mod causing this effect

**Comment by Beidub** [comment]
Thank you, I am new to the website and I shall take notes of what you said to me.
