### ISSUE TITLE
AE2 issues on Catserver jar including Storage Cell entry and (rarely) server crashing

### ISSUE THREAD

**Issue by Th4nat0s1s** [AppliedEnergistics/Applied-Energistics-2#4344]
#### Description
We apparently had a server crash with the log provided, also we have noticed an inability to warp players into their own Storage Cells, though this is a secondary issue. I am just wanting to report that this did hapen but we have since restarted our server and everything seems to be running ok (minus the storage cell warping). Hope this helps further developemnt, and if this doesnt seem to be an issue with AE2 please let me know as I will also be bringing it to the attention of the Catserver devs in the off chance that its something to do with the server jar. That being said, this currently seems to be the only mod having any issues.

#### Environment
Catserver 1.12.2-81903c3
Multiplayer hosted on ServerMiner with approx 280 mods total
https://gist.github.com/Th4nat0s1s/baf697aa9b31d782c550e6db5d76e851

- Minecraft Version:  1.12.2
- AE2 Version:  AE2 - rv6 stable 7
- Forge Version:  1.12.2 - 14.23.5.2847

**Comment by yueh** [comment]
We do not support anything like Sponge or Bukkit officially. Only a standard forge environment.

Should you be able to reproduce it without it and in a new environment and save, please update the issue accordingly and we will reopen it.
