### ISSUE TITLE
Multiple Wireless Terminals, can't use because of Security Terminal.

### ISSUE THREAD

**Issue by GladBody22** [AppliedEnergistics/Applied-Energistics-2#4345]
Me and my friends opened up a SkyFactory 4 server a few days ago and have our ME system up and operating. However when using multiple wireless terminals(1 for each of us, 3 total) Only one of us can access it at a time. We have a security terminal and have biometric cards. We can't link the biometric cards to ourselves(i've looked on guides for about 2 hours now) and only the person who places the security terminal can access it, and the ME System. I'm completely confused how to set this up and have looked at guides for a few hours now. As I couldn't find any discord link for the official SkyFactory 4 modpack, I've resulted in explaining the issue here.

**Comment by yueh** [comment]
[Biometric Card](https://ae-mod.info/Biometric-Card/)/[ME Security Terminal](https://ae-mod.info/ME-Security-Terminal/)
