### ISSUE TITLE
Drives don't connect how they sould

### ISSUE THREAD

**Issue by XilefTech** [AppliedEnergistics/Applied-Energistics-2#4346]
**Describe the bug**
I just recently wanted to buld a server room with a lot of drives. I layed out smart and dense smart cables to connect them all but after I placed a few of the drives, I noticed that some were not connected, even tho a cable with enough free channels was attached to the back. 
I also noticed that the channels went out from only one drive. So it seems like, the lastdrives are not connected because AE wants to conecct them only via the inter-drive-connection and not through the cables in the back.
![front](https://user-images.githubusercontent.com/52332196/79549329-21943700-8097-11ea-8d81-cf3dbce29ced.png)

**To Reproduce**
Just place drives in a 3x3 grid, attach smart cables in the back like shown in the picture
![buggy system back](https://user-images.githubusercontent.com/52332196/79504348-11e30700-8033-11ea-8ac8-e612b6107792.png)

**Expected behavior**
all drives sould be connected through the cable in the back of the drive

**Environment**
Playing Project Ozone 3 Kappa Mode

- Minecraft Version: 1.12.2 
- AE2 Version: rv6-stable-7
- Forge Version: 14.23.5.2847

**Comment by Tahakk** [comment]
This is just how it works, searching for the shortest (optimal) path.

**Comment by XilefTech** [comment]
but it's not optimal when there are no free channels left in the path

**Comment by Tahakk** [comment]
I would say try to reconnect your connections. I tried it and it works with many possibilities (yours included), and they work just fine.

Few images for you:
![2020-04-17_11 15 04](https://user-images.githubusercontent.com/25863620/79553519-e6950200-809c-11ea-938d-d2297590493f.png)
![2020-04-17_11 15 12](https://user-images.githubusercontent.com/25863620/79553522-e7c62f00-809c-11ea-978f-d7a68c50026a.png)
![2020-04-17_11 15 22](https://user-images.githubusercontent.com/25863620/79553526-ea288900-809c-11ea-91e8-5dfa754a067a.png)
![2020-04-17_11 15 20](https://user-images.githubusercontent.com/25863620/79553535-ebf24c80-809c-11ea-8af3-2e2c125efa0c.png)

At the end the connections sometimes work little wonky and they do not prefer cables over machine-to-machine connection

**Comment by XilefTech** [comment]
okay, thanks!
I'll try that out as soon as I fixed my world from crashing
