### ISSUE TITLE
Freezing with Iron Backpacks

### ISSUE THREAD

**Issue by LemonJamTart** [AppliedEnergistics/Applied-Energistics-2#4347]
**Describe the bug**
When attempting to retrieve an Iron Backpacks backpack from the ME system, the game will freeze and require a force-shutdown via task manager. Essentially, I can't retrieve my backpack- and for some reason, when trying to get it out using an export bus and _another_ backpack, it will not get pulled out of the system- so my backpack full of _really important stuff_ is now lost forever. It wouldn't be an issue if there were a way to extract every item, without a filter, but to the best of my knowledge there is not.

**To Reproduce**
I accidentally shift-clicked my (regrettably loot-filled) diamond backpack while putting away resources.

**Expected behavior**
I would get my backpack back.

**Additional context**
Unfortunately, as the game necessitates being force quit, it doesn't generate a proper crashlog, and my latest.txt has only this: https://pastebin.com/vAcvZ935

**Environment**
- Minecraft Version: 1.12.2
- AE2 Version: rv6.stable build 7
- Forge Version: 14.23.5.2847

**Comment by yueh** [comment]
That is the usual issue with items with extremely large nbt sizes. Technically there are solutions for the mod itself to handle it and reduce the amount of data needed to send to the client. But that is up to the mod itself to implement. And probably has other downsides.

One thing you could try is to use an export bus and export any backpack into a normal chest. Maybe using a fuzzy card. Might work, but I cannot really guarantee it.
