### ISSUE TITLE
ME Level Emitter + Crafting Card -> accept multiple items

### ISSUE THREAD

**Issue by Melfick** [AppliedEnergistics/Applied-Energistics-2#4349]
I would like to be able to set-up multiple items in the level editor when it is in crafting mode. 

**Describe the feature**
Expands the UI to a multiple-items grid when the crafting card is placed in the level emitter.

**Reasons why it should be considered**
Same machines to be triggered for multiple recipes.

**Additional Context**
Example: opening the Crystal Growth Accelerator for different crystals

**Comment by yueh** [comment]
Level emitters are only binary. While this might work for watching for crafting, it cannot handle emitting redstone to craft more than one item. As well as the basic functionality also not support more than one.

Further redstone itself already behaves as a simple or gate, so it would not offer anything new besides smaller builds.
