### ISSUE TITLE
Autocrafting Growth Crystals Tier 3 stuck at Simulation (1.12.2)

### ISSUE THREAD

**Issue by Sventecc** [AppliedEnergistics/Applied-Energistics-2#4350]
Hello, I am currently playing Skyfactory 4 and wanted to auto-craft the growth crystals from Tiny Progressions. The first two tiers work like a charm but every time I try to auto-craft the tier 3 crystals the GUI shows up with the "Start" button greyed out. I also tried with ore-dic activated. In a test world I created a much smaller AE system with a big energy buffer and still couldn´d get it to work.

Steps to reproduce:
- Build a simple AE system with enough energy, crafting storage, CPU´s, molucular assembler and 
  interface
- Create a pattern for the growth crystal tier 3
- Provide your system with the necessary materials
- Try to start the crafting job

As a little workaround for now, I made two patterns for the growth crystal tier 3, one crafting and one processing. Then I put the crafting pattern in the molecular assembler and the processing pattern in the interface next to the assembler. It works but it´s still weired that it doesn´t work the normal way. First I thought the potions are the problem but the other two tiers work too so thanks in advance for your help.

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-7
- Tiny Progressions Version: 3.3.34
- Forge Version: 14.23.5.28.38

**Comment by yueh** [comment]
Please report crafting bugs to your modpack first. It is simply way too much effort to track every pack out there as many use addons breaking autocrafting in some way.
