### ISSUE TITLE
AE2 Quantum Ring issue

### ISSUE THREAD

**Issue by danielpmc** [AppliedEnergistics/Applied-Energistics-2#4354]
AE2 quantum ring going offline although area is chunk loaded and main system is also chunk loaded.

**Describe the bug**
AE2 quantum ring going offline although area is chunk loaded

**To Reproduce**
Not sure if it would work but. Install StoneBlock from twitch/curseforge and spin up a server. Chunk load your base then set a Quantum ring going to the mining world. (Make sure to chunk load them both)

Oh while iv been typing this it has also happened to a quantum ring i have in my base. (was only about 90blocks away from me (is also chunk loaded)

**Expected behavior**
Quantum rings to work like normal.

**Additional context**
Video: https://youtu.be/wt2v_sm1OWk

**Environment**
SP/MP : Multiplayer server (Only for 2 people to play) running on hardware: 
2x Intel Xeon E5645 @ 2.4GHz
64GB RAM

Mods:
ActuallyAdditions-1.12.2-r146.jar
ActuallyBaubles-1.12-1.1.jar
ae2stuff-0.7.0.4-mc1.12.2.jar
AE2WTLib-1.12.2-1.0.6.jar
angelRingToBauble-1.12-0.3.1.50+d4e654e.jar
AppleSkin-mc1.12-1.0.9.jar
appliedenergistics2-rv6-stable-6.jar
Aroma1997Core-1.12.2-2.0.0.2.b165.jar
Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.b89.jar
AttributeFix-1.12.2-1.0.4.jar
AutoRegLib-1.3-26.jar
Avaritia-1.12.2-3.2.0.25-universal.jar
badwithernocookiereloaded-1.12.2-3.3.16.jar
base-1.12.2-3.12.0.jar
Baubles-1.12-1.5.2.jar
bdlib-1.14.3.12-mc1.12.2.jar
BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar
BetterFps-1.4.8.jar
BetterQuesting-3.5.296.jar
BetterQuestingTriggerer-1.0.jar
BetterThanBunnies-1.12.1-1.1.0.jar
BetterThanLlamas-1.12.1-1.0.0.jar
bonsaitrees-1.1.2-b144.jar
Bookshelf-1.12.2-2.3.577.jar
Botania r1.10-361.jar
BrandonsCore-1.12.2-2.4.10.198-universal.jar
buildcraft-all-7.99.23.jar
BuildingGadgets-2.6.8.jar
Ceramics-1.12-1.3.7.jar
Chameleon-1.12-4.1.3.jar
ChanceCubes-1.12.2-4.0.0.270.jar
ChestTransporter-1.12.2-2.8.8.jar
chickens-6.1.0.jar
Chisel-MC1.12.2-0.2.1.35.jar
chiselsandbits-14.31.jar
ClientTweaks_1.12.2-3.1.11.jar
Clumps-3.1.2.jar
CodeChickenLib-1.12.2-3.2.2.353-universal.jar
CoFHCore-1.12.2-4.6.2.25-universal.jar
CoFHWorld-1.12.2-1.3.0.6-universal.jar
ColossalChests-1.12.2-1.7.1.jar
comforts-1.12.2-1.4.1.1.jar
CommonCapabilities-1.12.2-2.2.0.jar
compacter-1.3.0.3-mc1.12.2.jar
compactmachines3-1.12.2-3.0.16-b263.jar
CompactSolars-1.12.2-5.0.18.341-universal.jar
ComputerCraft1.80pr1.jar
Controlling-3.0.6.jar
CookingForBlockheads_1.12.2-6.4.70.jar
CraftingTweaks_1.12.2-8.1.9.jar
CraftPresence-1.12.2-1.5.3.1.jar
CraftTweaker2-1.12-4.1.17.jar
CTM-MC1.12.2-0.3.3.22.jar
Cucumber-1.12.2-1.1.3.jar
CustomMainMenu-MC1.12.2-2.0.9.jar
cxlibrary-1.12.1-1.6.1.jar
Cyclic-1.12.2-1.19.2.jar
CyclopsCore-1.12.2-1.1.1.jar
DankNull-1.12-1.4.46.jar
DarkUtils-1.12.2-1.8.223.jar
DefaultOptions_1.12.2-9.2.8.jar
Draconic-Evolution-1.12.2-2.3.21.342-universal.jar
ducky-mod-1.12.2-0.1.1.jar
EnderCore-1.12.2-0.5.57.jar
EnderIO-1.12.2-5.0.43.jar
EndermanEvolution-1.12.2-1.0.19.jar
EnderStorage-1.12.2-2.4.5.135-universal.jar
EnergeticSheep-1.12.2-1.1.4.jar
environmentaltech-1.12.2-2.0.20.1.jar
etlunar-1.12.2-2.0.20.1.jar
EvilCraft-1.12.2-0.10.72.jar
Exchangers-1.12.2-2.8.jar
ExCompressum_1.12.2-3.0.27.jar
exnihilocreatio-1.12.2-0.4.1.2.jar
ExtraCells-1.12.2-2.6.2a.jar
extrautils2-1.12-1.9.9.jar
ExtremeReactors-1.12.2-0.4.5.50.jar
FarmingForBlockheads_1.12.2-3.1.26.jar
FastLeafDecay-v14.jar
FeaturedServers-1.12-1.0.6.jar
flatcoloredblocks-mc1.12-6.7.jar
fluxnetworks-1.12.2-3.0.19-21.jar
foamfix-0.10.5-1.12.2.jar
forestry_1.12.2-5.8.2.387.jar
Forgelin-1.8.2.jar
ForgeMultipart-1.12.2-2.6.1.81-universal.jar
FTBLib-5.4.1.95.jar
FTBUtilities-5.4.0.92.jar
FTBUtilitiesBackups-1.0.0.3.jar
FullscreenWindowed-1.12-1.6.0.jar
GooglyEyes-1.12.2-7.1.0.jar
Guide-API-1.12-2.1.8-63.jar
Harvest-1.12-1.2.7-20.jar
hatchery-1.12.2-2.2.1.jar
Hats-1.12.2-7.0.2.jar
Hwyla-1.8.26-B41_1.12.2.jar
iChunUtil-1.12.2-7.2.1.jar
ImmersiveEngineering-0.12-89.jar
industrialcraft-2-2.8.120-ex112.jar
industrialforegoing-1.12.2-1.12.11-235.jar
industrialmeat-1.12-1.0.2.jar
InGameInfoXML-1.12.2-2.8.2.94-universal.jar
IntegratedDynamics-1.12.2-1.0.11.jar
IntegratedTunnels-1.12.2-1.6.8.jar
IntegrationForegoing-1.12.2-1.9.jar
inventorysorter-1.12.2-1.13.3+57.jar
IronBackpacks-1.12.2-3.0.8-12.jar
ironchest-1.12.2-7.0.59.842.jar
jehc-1.12.2-1.6.3.jar
jeibees-0.9.0.5-mc1.12.2.jar
jei_1.12.2-4.15.0.277.jar
journeymap-1.12.2-5.5.4.jar
JustEnoughIDs-1.0.2-26.jar
KleeSlabs_1.12.2-5.4.11.jar
llibrary-1.7.18-1.12.2.jar
longfallboots-1.2.1b.jar
LootBags-1.12.2-2.5.8.5.jar
LunatriusCore-1.12.2-1.2.0.42-universal.jar
Mantle-1.12-1.3.3.49.jar
mcjtylib-1.12-3.1.1.jar
MCMultiPart-2.5.3.jar
Mekanism-1.12.2-9.7.0.369.jar
MekanismGenerators-1.12.2-9.7.0.369.jar
MekanismTools-1.12.2-9.7.0.369.jar
Mercurius-1.12.2.jar
missing_pieces-1.12.2-4.3.0.jar
MobGrindingUtils-0.3.13.jar
modnametooltip_1.12.2-1.10.0.jar
Modpack Configuration Checker-1.12.2-v1.7.jar
modtweaker-4.0.17.jar
morechickens-1.12.2-3.1.0.jar
MoreFurnaces-1.12.2-1.10.6.jar
moreoverlays-1.14-mc1.12.2.jar
MoreShearables1.3.1-1.12.2.jar
Morph-o-Tool-1.2-21.jar
Morpheus-1.12.2-3.5.106.jar
MouseTweaks-2.10-mc1.12.2.jar
MTLib-3.0.6.jar
MysticalAgradditions-1.12.2-1.3.1.jar
MysticalAgriculture-1.12.2-1.7.3.jar
natura-1.12.2-4.3.2.66.jar
Neat 1.4-17.jar
NetherPortalFix_1.12.1-5.3.17.jar
nice-1.12-0.3.2.jar
noRecipeBook_v1.2.2formc1.12.2.jar
notenoughwands-1.12-1.7.3.jar
OldJavaWarning-1.12.2-1.0.8.jar
OpenBlocks-1.12.2-1.8.1.jar
OpenModsLib-1.12.2-0.12.2.jar
oreberries-1.12.x-0.5.0.jar
OreExcavation-1.4.137.jar
OreSpawn-1.12-3.2.2.113.jar
p455w0rdslib-1.12.2-2.1.44.jar
Pam's HarvestCraft 1.12.2zb.jar
Pam's Simple Recipes 1.12.2c.jar
Placebo-1.12.2-1.6.0.jar
plustic-7.0.5.1.jar
ProjectE-1.12-PE1.3.2h.jar
Psi-r1.1-73.jar
QuantumStorage-1.12-4.6.8.jar
RandomThings-MC1.12.2-4.2.7.1.jar
randomtweaks-1.12.2-2.5.0.3.jar
RealisticItemDrops-1.2.14.jar
reauth-3.6.0.jar
RebornCore-1.12.2-3.13.12.447-universal.jar
RebornStorage-1.12.2-3.3.2.79.jar
RedstoneArsenal-1.12.2-2.6.2.17-universal.jar
RedstoneFlux-1.12-2.1.0.6-universal.jar
refinedstorage-1.6.14.jar
refinedstorageaddons-0.4.4.jar
ResourceLoader-MC1.12.1-1.5.3.jar
rflux-1.12-0.3.2.jar
rftools-1.12-7.61.jar
rftoolsctrl-1.12-1.9.3.jar
rftoolsdim-1.12-5.64.jar
roost-1.12-1.3.0.jar
shearmadness-1.12.2-1.7.2.4.jar
Signals-1.12.2-1.4.1-30-universal.jar
SimpleCorn1.12-1.12-2.4.1.jar
SimplyJetpacks2-1.12.2-2.2.11.64.jar
SlimyBoyos-1.0.0.jar
Snad-1.12.1-1.7.09.16a.jar
SolarFluxReborn_1.12.2-4.14r.jar
sonarcore-1.12.2-5.0.19-20.jar
StandardExpansion-3.4.154.jar
StevesCarts-1.12.2-2.4.30.134.jar
StoneBlockUtilities-2.1.1.jar
StorageDrawers-1.12.2-5.3.8.jar
TConstruct-1.12.2-2.12.0.135.jar
Tesla-1.12.2-1.0.63.jar
tesla-core-lib-1.12.2-1.0.15.jar
ThermalCultivation-1.12.2-0.3.2.11-universal.jar
ThermalDynamics-1.12.2-2.5.4.18-universal.jar
ThermalExpansion-1.12.2-5.5.3.41-universal.jar
ThermalFoundation-1.12.2-2.6.2.26-universal.jar
ThermalInnovation-1.12.2-0.3.2.11-universal.jar
TinkerToolLeveling-1.12.2-1.1.0.jar
tinyprogressions-1.12.2-3.3.32-Release.jar
Toast Control-1.12.2-1.8.0.jar
torchmaster_1.12.2-1.7.1.74.jar
Translocators-1.12.2-2.5.1.77-universal.jar
TS2K16-1.2.10.jar
UniDict-1.12.2-2.9.2.jar
valkyrielib-1.12.2-2.0.20.1.jar
voidislandcontrol-1.5.3.jar
WanionLib-1.12.2-2.2.jar
Wawla-1.12.2-2.5.269.jar
Whoosh-1.12.2-0.1.12.1-universal.jar
WirelessCraftingTerminal-1.12.2-3.11.88.jar
WitherSkeletonTweaks-1.12.2-2.6.3.jar
woot-1.12.2-1.4.10.jar
worldprimer-1.12.2-0.5.0.jar
xnet-1.12-1.7.6.jar
Xtones-1.12-1.0.8-11.jar
zerocore-1.12-0.1.2.3.jar

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-6.jar
- Forge Version: forge-14.23.5.2836

**Comment by mindforger** [comment]
Did you attach a few ae2 energy cells? (To increase internal buffer) Maybe your system is running out of power.

**Comment by danielpmc** [comment]
> Did you attach a few ae2 energy cells? (To increase internal buffer) Maybe your system is running out of power.

I'll try that now. I will reply later if it happens again (takes a little bit of time to happen). That shouldn't be a problem for all of them but 1 is running on my main power source (always online with loads of backup power) the one in the video is running from solar in a always day world. but i will try you'r idea and see how it goes.

**Comment by mindforger** [comment]
just for explanation, me systems have internal capacity and if (in a single tick) you consume all that stored energy, it will offline the network.

Having an infinte power input does not mean you can not run out of power internally, the only way you can never run out of power is using an creative energy cell because it makes the capacity infinite

**Comment by danielpmc** [comment]
I was just playing and randomly the quantum ring went off again.

Heres a video: https://youtu.be/eXBEpWIsC4M

**Comment by repo-alt** [comment]
Perhaps it would make sense for the quantum ring to have an internal energy buffer of sufficient capacity (scaled along with config consumption multiplier)?

**Comment by mindforger** [comment]
@repo-alt what purpose do the energy cells have then?

**Comment by repo-alt** [comment]
Energy cells have a bit different role, e.g. if energy supply is varying. The problem with quantum ring is that the logic that you explained above is not obvious/transparent to the user.

**Comment by mindforger** [comment]
I am with you on that there could be a tiny bit more indication in case of low capacity in some way

**Comment by xanderc2** [comment]
Same issue here, i am experienced mod/ae2 player since 1.4.7, actually playing on OMNIFACTORY i completely removed quantum rings (totally bugged) and i am using tons of cables D:

**Comment by danielpmc** [comment]
Ok its worse with energy cells. now all of them are going off every few mins. before it was hours but now i cant even use them for more than 30mins before they go off

**Comment by yueh** [comment]
There is nothing we can do without any way to reliably reproduce it.
With the amount of similar reports lately, I would even guess some updated mod interacting with AE2 could cause it.

**Comment by Korvynus** [comment]
Sorry for necro this issue, but I have the same issue as OP. But I noticed the 1.12.2 branch of the mod was abandoned. I guess there will be never a fix for this then?

**Comment by shartte** [comment]
This has been worked on for 1.15/1.16, but it wont be backported due to time constraints.

**Comment by Korvynus** [comment]
Ok nvm I'll work without it then. Thanks for your answer.
