### ISSUE TITLE
Game crashes when disabling pure crystals

### ISSUE THREAD

**Issue by Tepiltzin** [AppliedEnergistics/Applied-Energistics-2#4356]
**Describe the bug**
Setting 'B:PureCrystals' to 'false' in the config file causes the game to crash during loading.

**To Reproduce**
Change 'B:PureCrystals=true' to 'B:PureCrystals=false'

**Expected behavior**
Pure Certus, Fluix and Quartz crystals and all recipes which use them should not be registered.

**Additional context**
Crashlog: https://pastebin.com/ydXbvfrJ

**Environment**
- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-7
- Forge Version: 14.23.5.2854
- Tested on a fresh install of Minecraft. Just AE2 and JEI installed.

**Comment by yueh** [comment]
The recipe system in 1.12 is still fairly lackluster. So this is not really fixable in a sane way for now.
