### ISSUE TITLE
Applied-Energistics-2 Crash

### ISSUE THREAD

**Issue by KiaraMinecraft** [AppliedEnergistics/Applied-Energistics-2#4358]
When I was loading the modpack, It was at Initializing mods phase 2 before it crashed.

https://pastebin.com/QRX2WrTP

**Comment by yueh** [comment]
`Caused by: java.lang.IllegalArgumentException: Failed to register dimension for id 7, One is already registered`

**Comment by KiaraMinecraft** [comment]
> 
> 
> `Caused by: java.lang.IllegalArgumentException: Failed to register dimension for id 7, One is already registered`

What does that mean?

**Comment by Hinara** [comment]
It means what it is written. There is already a dimension with this id.
Try to reach who make your modpack or if it is a custom one, in `config/AppliedEnergistics2/AppliedEnergistics2.cfg` you should have something like that
`I:storageDimensionID=7` replace the 7 by another value that doesn't collide with other mods

**Comment by KiaraMinecraft** [comment]
Okay, I found it, but it won't let me change it. All I can do is highlight it.

**Comment by KiaraMinecraft** [comment]
It's under spatialio.

**Comment by Hinara** [comment]
It's strange that you cannot change the value
Which editor do you use ?

**Comment by KiaraMinecraft** [comment]
The top of the screen says cool file viewer.

**Comment by Hinara** [comment]
If you cannot modify with this one try to open it with notepad

**Comment by KiaraMinecraft** [comment]
Okay, I opened it in notepad. What do I do now?

**Comment by Hinara** [comment]
Same as before replace the 7 `I:storageDimensionID=7` by another value that doesn't collide
