### ISSUE TITLE
Items not showing up on Terminals

### ISSUE THREAD

**Issue by XilefTech** [AppliedEnergistics/Applied-Energistics-2#4361]
**Describe the bug**
After I fixed once again a ticking Gridnode Problem on my map and re-joined the server I couldn't see any items in any of my terminals.

**To Reproduce**
I don't know how I can reprouduce it yet.

**Expected behavior**
All my Items sould show up as normal in the terminals

**Additional context**
I haven't added anything to the cables for my drives so there is no channel problem. Especially because it worked before. My complete system is chunkloaded and I got plenty of power to run the system. 

**Environment**
Project ozone 3 (Kappa mode)

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-7
- Forge Version: 14.23.5.2847

**Comment by mindforger** [comment]
Screenshots would help, also the mandatory question if you have enough ae2 energy cells installed, because input is limited by internal capacity

**Comment by XilefTech** [comment]
So I got more than enough energy storage on both my p2p carrier and my main system. More than 15 dense energy cells per system.

But the Problem is getting more strange, since once I re-joined the server today to make the requested screenshots, everything was fine again. I could see all my Items again. 

A friend of mine that is also playing on the server noticed, that while we couldn't see the Items in the terminals, things like importing cobblestone to a Storage bus attached quantum storage unit worked perfectly fine. So there must have been some sort of bug in the terminals.

And for if it happens again, what kind of screenshots would you like to have? My drives? the empty terminal?

**Comment by mindforger** [comment]
the "physical" setup to see how your system is built (sometimes pictures say more than a thousand words)

where do you store items, only in drives?, only in storage busses and so on

**Comment by XilefTech** [comment]
Since this issue didn't happen again and thus I cannot collect much more debug information, I'd consider this Issue closed for now. If this would happen again, we could revisit the topic, but since this is ATM not reproducable at all and for me just a very big mysterious, we cannot do anything here.

Thanks for trying to help tho

**Comment by Ricket** [comment]
@mindforger I've been hitting this quite frequently in my server - items missing, crafts missing, see the item but unable to extract it. Various buggy behavior like that.

I don't know of any pattern to why the items are disappearing and it's not really reproducible. Often just retrying, or randomly breaking and replacing things, can fix it. Or at the extreme end, a server restart usually makes it go away and idk what triggers it. Network has plenty of power, etc. Do you have any tips on how I could "catch it in the act"? e.g. would a heap dump be at all helpful? Or is there any way to increase the logging verbosity?
