### ISSUE TITLE
AE2 corruption in World - Voids Fluids put into the system

### ISSUE THREAD

**Issue by PiggyWhiskey** [AppliedEnergistics/Applied-Energistics-2#4363]
AE2 corruption with Fluid management

Versions:
Minecraft 1.12.2
AE2 rv6 stable 7
Forge: 14.23.5.2847

Modpack: Enigmatica 2 Expert v 1.80
Single Player

---
Current situation:
Fluids put into ME Fluid Interface's or ME Fluid Terminal is voided.
Tested with ME Drive + Fluid Disk and ME Storage Bus on TE Tank.

Fluids Pumped into Fluid Interface remain in there until connected to the network.
Buckets pushed in Fluid Terminal, Fluids in connected Fluid Interface, and Fluids from Fluid Import Bus all get voided.

Fluids can be extracted via Fluid Export Bus and Fluid Interface without issues.

Tested in same world with a new Test network (1x Controller, 1x Drive, 1x Cell, 1x Terminal) which works fine.

---
I have a very extensive AE2 network with dozens of P2P connections spanning many chunks.
I have taken down the controller and rebuilt with no success.

World Link: https://www.dropbox.com/s/cpu6rds6ejjlxhh/World%2001%20-%20Copy.7z?dl=0

How can I 'rebuild' my AE2 network without actually tearing everything down?

**Comment by mindforger** [comment]
did you attach any fluid storage busses to voiding blocks without configuring them by chance?

**Comment by PiggyWhiskey** [comment]
Damn, you nailed it.
I didn't have any Fluid Trash Cans set up, but I had a Sink and a Creative Fluid Tank.
Having either without Filters will void anything new to the system.
Adding a filter to both stopped the issue.

I had set those 2 priorities very high to make sure I didn't get extra water clogging up my other fluid storage options.

Sorry for the derp report.
