### ISSUE TITLE
Tight cable do not count channels on server.

### ISSUE THREAD

**Issue by sunddc** [AppliedEnergistics/Applied-Energistics-2#4364]
Screenshot is attached.

Get issue on server:
Minecraft 1.7.10
AE2 version  appliedenergistics2-rv2-stable-10
Forge 1.2.0.345

Tested is SP it`s count wrong, on server its always 0.

Screenshot (tight cable with 2 connected import tire)
https://i.imgur.com/GlT6dBn.png

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.12 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.

**Comment by mindforger** [comment]
also don't use stable its way more bugged than the latest beta :)
