### ISSUE TITLE
Crafting computers randomly stop working

### ISSUE THREAD

**Issue by blindmoomoo** [AppliedEnergistics/Applied-Energistics-2#4367]
My crafting computer system randomly stops working, as if there wasnt enough power provided but i have a 185m AE power battery buffer. I tried breaking and replacing cables, me controllers, the computers themselves, the machines, the molecular assemblers and even the me interfaces. It seems to happen when all the hard drives get full or near full?(i really am not sure)...I do empty hard drives before crafting anything though otherwise i know it wouldnt work. The crafting system seem to start working again after some time on its own...

I did look if i had enough channels too.

**Comment by yueh** [comment]
Please report all autocrafting related bugs directly to your modpack.

Many are intentionally using AE2 addons, which will break autocrafting by design and tracking which modpack does or does not use them is simply not possible.
