### ISSUE TITLE
Why my channels not working

### ISSUE THREAD

**Issue by MagicFreeMaster** [AppliedEnergistics/Applied-Energistics-2#4368]
Hi guys, currently  I am playing mc eternal latest version and trying to automatize things with AE but as you can see in picture somehow my channels are not working 

**Additional context**
![image](https://user-images.githubusercontent.com/64662023/80836868-f14fab00-8bf5-11ea-95b4-85f19b840a60.png)

**Environment**
playing SP

- Minecraft Version: 1.12
- AE2 Version: 
- Forge Version:

**Comment by mindforger** [comment]
I can at least see two channels working there. Anyways you need to show way more details and a more clear issue description. You say your car isnt working by showing a picture of your blinker

**Comment by MagicFreeMaster** [comment]
same issue here, channels bellow are connedted but wont connect to crafting table. I tried to reroute cabels but terminal still not connecting
![image](https://user-images.githubusercontent.com/64662023/80838519-7f796080-8bf9-11ea-9e44-43739433f652.png)

**Comment by Hinara** [comment]
If you want to get help, you need to provide something visible or a minimal reproduction of this that we can reproduce. More ever your channel is currently supporting 1 channel and not 0.
Also, Did you provide enough power to your network ? 
With the current information provided it is impossible to debug your case.
