### ISSUE TITLE
There's a problem with AE system handling items with a huge NBT strings!

### ISSUE THREAD

**Issue by Dm5354** [AppliedEnergistics/Applied-Energistics-2#4369]
If you put items that have a really long NBT string than your doomed, You simply can't pull out the item from the me system. I experienced that problem with a 30k character long item NBT string, and that was accidently a half filled cardboard boxed me drive, which was put into the system by accident!

If you want to reproduce it and you have a half decent me system with mekanism in the modpack than do what I did, but first, do a Backup!

If you succed your item can't be pulled out of the me system!

The modpack I used was the latest Po3 (Kappa)

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-7
- Mekanism Version: 1.12.2-9.8.3.390
- Forge Version: 1.12.2 - 2.6.2.84

**Comment by yueh** [comment]
This is a limitation in minecraft/forge.

**Comment by Hinara** [comment]
@yueh is there any issue in minecraft/forge for this particular case ?

**Comment by yueh** [comment]
Packets limited to 32k bytes.
