### ISSUE TITLE
umm i hav a problem whit my mod applid energestics 2 

### ISSUE THREAD

**Issue by oskarmikey** [AppliedEnergistics/Applied-Energistics-2#4371]
- AE2 Version:  appliedenergistics2-rv6-stable-7.jar

- Forge Version:  1.12.2 (moddad) forge-14.23.5.2847

my problem 
java.lang.IllegalArgumentException: Failed to register dimension for id 2 

[crash-2020-01-29_20.28.54-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/4570307/crash-2020-01-29_20.28.54-client.txt)

**Comment by Hinara** [comment]
Hi,

So this is not a Applied Energistics 2 issue but more a configuration issue. See https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4358.
If you are playing on on modpack, you need to reach who made it, in other cases look at the give issue to see how to fix that.
