### ISSUE TITLE
Allow for searching ingredients within recipe patterns in interface terminal

### ISSUE THREAD

**Issue by BenLarge1** [AppliedEnergistics/Applied-Energistics-2#4376]
Currently, searching for crafting patterns within the interface terminal only returns the pattern itself.

**Describe the feature**
Ideally, searching for "widget X" would not only return the recipe for widget X, but also any recipes that require widget X within them. i.e: widget Y requires 2 widget X and a widget Z, so it would show up as well when searching widget X

**Reasons why it should be considered**
This is mostly a response to my need to replace circuits within recipes in my Omnifactory playthrough so there isn't a massive need for it given the niche nature of the issue, but it would be nice nonetheless

**Additional Context**
Link to reddit thread mentioned: https://www.reddit.com/r/feedthebeast/comments/gdhrtx/anyway_to_search_ae2_patterns_for_ingredients/

**Comment by yueh** [comment]
Might be an idea in case there is time to refactor the whole terminal GUIs. But not now.

Currently the interface terminal is extremely simple.
E.g. it is lacking a way to add buttons so a player could toggle the search mode as I doubt most players want to have it show every recipe using iron ingots when they are just searching for the iron ingot recipe.
Also the search itself is pretty naive. Having to search through 10 item names (9 ingredients and 1 output) is an order of magnitude worse than just the output. Without a more sophisticated approach this can be really obvious on how long it might lock up until it displays the filtered result.
