### ISSUE TITLE
Tinkers construct mod docent appear when i do the @  

### ISSUE THREAD

**Issue by AliesterYT** [AppliedEnergistics/Applied-Energistics-2#4378]
**Describe the bug**
When i do _@tinkers_ the mod's items and blocks don't appear 

**To Reproduce**
do @tinkers in an ae system with tinkers in a game and in the system

**Expected behaviour**
all the items and blocks should appear 

**Additional context**

**Environment**
appeared in modpacks enigmatica 2 expert and stoneblock 2

- Minecraft Version: 1.12.2 
- AE2 Version:  rv6-stable7
- Forge Version: 14.23.5.2847
-Tinkers's Construct Version: 1.12.2-2.12.0.183

**Comment by yueh** [comment]
The mod id for tinker's construct is actually `tconstruct`.
