### ISSUE TITLE
appeng.core.AppEng.serverStopped

### ISSUE THREAD

**Issue by JumboTSB** [AppliedEnergistics/Applied-Energistics-2#4381]
AE2 Prevents the latest forge from launching. For some reason, this worked fine for a few days.

**Describe the bug**
AE2 Preventing the server from launching due to a null pointer exception.

**To Reproduce**
Unknown.  Although this seems similar to issue: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4240
And: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4106
The issue 4106 shows a nullable instance that seems to be the cause.

**Additional context**
Pastebin: https://pastebin.com/Bk0hvxTS

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-7.jar
- Forge Version: Forge Mod Loader version 14.23.5.2854

**Comment by Hinara** [comment]
`**** FAILED TO BIND TO PORT!`
I agree that AE2 however should not throw after that

**Comment by JumboTSB** [comment]
That's... Quite odd. I may have skipped over this, apologies.
