### ISSUE TITLE
Suggestion for "Gird update()", and potential bug report

### ISSUE THREAD

**Issue by i493052739** [AppliedEnergistics/Applied-Energistics-2#4383]
**A Suggestion for Performance Improvement and potential bug report (on Gird)**

**Describe the feature**
update the Gird asynchronously at onTick() method;
and unload Grid when the corresponding Chunk unloaded.

**Reasons why it should be considered**
When loaded more chunks, it seems like the Gird will not unload when chunks unloaded.
So the onTick() method will take more and more memory to update Girds, even no player is playing, no chunk is loaded...? (Am I right?...)
![PLWAJ$0MKJLIW8N}O5UP7M8](https://user-images.githubusercontent.com/36336351/82121495-1d575880-97c0-11ea-98d6-398a062a79bc.png)
So, could you make the Grid update method asynchronously in another thread, 
this may enhance the overall performance enormously I think

**Additional Context: BUG report about the Grid**
Like I said above, the Gird may not unload with the chunk, so there has another potential issue when Grid keeps updating at an unloaded Chunk. 
![20200516200713](https://user-images.githubusercontent.com/36336351/82121498-221c0c80-97c0-11ea-85b0-ff6306bfc278.png)
when you link the Grid to an OpenCreate(BotaniaMod) or BuildCraftTube or something like Dispensers which can pop items out from the Gird, then put a hopper to retrieve items and put it to the chest, or another Grid. 
When that chunk unloaded from the server, **the issue begins** ---- More and more dropped item popping out from the Gird, but there is no any hoppers work to receive items. 
Next, after 5 minutes, or 10. Your server will get maybe 10,000 dropped items, or even more...

**Comment by yueh** [comment]
Once minecraft and everything else is threadsafe, it might be an idea.
