### ISSUE TITLE
CraftingManager fallback "High Voltage Solar Array" from Compact Solar

### ISSUE THREAD

**Issue by hduelme** [AppliedEnergistics/Applied-Energistics-2#4385]
When autocrafting an "High Voltage Solar Array" from Compact Solar Array the Server Crashes after showing many times a CraftingManager fallback.

**To Reproduce**
Try remake the pattern without Ore-Dict. This fixed the problem for me.

**Additional context**
![Bildschirmfoto vom 2020-05-17 21-48-21](https://user-images.githubusercontent.com/46139144/82158478-7094de00-9888-11ea-9bf3-8ea1fe83aedc.png)
CraftingManager fallback Screenshot

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-7
- Forge Version: 1.12.2-14.23.5.2847
- Modpack; FTB Presents Direwolf 20 1.12 - 2.6.0

**Comment by yueh** [comment]
This indicates a potential performance problem, but nothing we can fix on our side. That would be up to the modpack or potentially the mod providing the reported recipes.
