### ISSUE TITLE
This crash happened after stage 4 in the loading process

### ISSUE THREAD

**Issue by babymanperson** [AppliedEnergistics/Applied-Energistics-2#4386]
https://pastebin.com/4JMUBRFb

- Minecraft Version: Minecraft Version 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-7.jar
- Forge Version: forge-14.23.5.2847

**Comment by Hinara** [comment]
Read the log
Change your configuration file
Dimensions ID should be unique, but it's your/modpack creator job to allocate a unique ID for dimensions.
If it is in a modpack please report it to the modpack author

**Comment by babymanperson** [comment]
Alrighty. Thank you.
