### ISSUE TITLE
ME sleep while crafting 

### ISSUE THREAD

**Issue by K1ZO** [AppliedEnergistics/Applied-Energistics-2#4388]
**Describe the bug**
ME stops working with such a crafting scheme. All ME bus and mechanisms was sleeping.
https://youtu.be/-KZEYG4EcH8

**To Reproduce**
Video: https://youtu.be/-KZEYG4EcH8
Map: https://drive.google.com/open?id=1fYS1IMsTeeGQJF6cK_W1RdcRDCMXqk7J

**Expected behavior**
Stable work

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-7
- Forge Version: 14.23.5.2847

P.S. Sorry for my English. This is not my main language.

**Comment by Pingger** [comment]
Please add a list of all mods installed

**Comment by XerShade** [comment]
I'm just asking a stupid question here but do those assemblers have a power cable on the back, busses do not transfer power, nor do pointed interfaces. We had to work around work around this when my team was designing our crafting bank arrays on Enigmatica 2 expert.

**Comment by yueh** [comment]
There appears to be an issue how the dynamic ticking behaves in this particular case.

In general using import buses on assemblers is not ideal as assemblers try to push out their result to an adjacent inventory. If they are not able, they won't go to sleep and try to constantly eject it every tick. So in this case they have to wait for the import bus to empty them before they also will be able to accept new ingredients. So it certainly won't be ideal in terms of throughput. Also as the export bus potentially has to wait on the import bus it might decide to slow down itself, which in return slows down the assembler and potentially the import bus. So it can easily oscillate within a speed range.

At some point the network simply decides the assemblers are more important than the buses as assemblers can tick every tick while buses tick only every 5 ticks (by default). Once that happens it somehow messes up the priority for the ticking order and stops after processing the assemblers.

**Comment by Pingger** [comment]
> 
> 
> I'm just asking a stupid question here but do those assemblers have a power cable on the back, busses do not transfer power, nor do pointed interfaces. We had to work around work around this when my team was designing our crafting bank arrays on Enigmatica 2 expert.

The Energy comes from the cable directly on top of the top most molecular assembler. The power is then transfered directly through the assemblers.
