### ISSUE TITLE
Crafting Unit in Crafting Multiblock Prevents Autocraft From Actually Starting.

### ISSUE THREAD

**Issue by z64555** [AppliedEnergistics/Applied-Energistics-2#4390]
Minecraft ver: 1.12.2
AE2 ver: rv6-stable-7

This is something of a second-hand report.  Somebody was trying out AE2 for the first time and was having trouble getting his autocrafter to work on anything.  After moving the multiblock to a cable feeding directly into the controller and verifying it had an available channel, we finally figured out that it was the Crafting Unit (filler) block that was causing the issue.

Essentially, the multiblock would form, cables would connect to the Crafting Unit, a channel was consumed, the Crafting GUI was active, but pressing Start didn't actually craft anything and in many cases the items were consumed.

By moving the cable over to a Crafting Co-Processor unit or a Crafting Storage unit, the autocrafting feature worked as intended.  the Crafting Monitor was not tested to see if it had an issue with connecting to cables.

If this is intended behavior please document it.  If its not, then please fix, thanks!

**Comment by Tahakk** [comment]
That sounds very strange, do you have any screenshots of a not-working setup? Was it with other mods or is it reproducible with AE only?

**Comment by z64555** [comment]
Ok, this is frustrating.  I've tried both a vanilla test instance with just AE2 and an instance with the full modpack, and was not able to repro the issue personally, but the guy clearly did have the problem of it not connecting and was only able to fix it once another crafting multiblock part had the cable in it.

Modpack in question is Enigmatica 2, version 1.77; Forge 14.23.5.2847.

I had another, different issue in the past that was a heisenbug just like this one (#3920 ), and it was pretty much decided that one or a combination of addons in the pack had caused unpredictable instability.  Much to the point where trying to add in each of the addons one-by-one would be futile and fruitless. :(
