### ISSUE TITLE
ME Crafting terminals and Wireless Crafting terminal not working in skyfactory 4

### ISSUE THREAD

**Issue by CARA560** [AppliedEnergistics/Applied-Energistics-2#4391]
I was playing skyfactory 4 on a apex server and just getting started with new inventory system with AE2 components. Then I notice that the mod pack didn't have a wireless crafting terminal so I installed the mod in both server and client.  The mod is WirelessCraftingTerminal-1.12.2-3.12.97 and as prerequisites I also installed the AE2WTLib-1.12.2-1.0.34 & p455w0rdslib-1.12.2-2.3.161.

After this my client kept crashing, I asked my server host and they recommended me to update the Extracells 2 mod to the newest version (1.12.2-2.6.5). So I updated in both client and server and the game stopped crashing, it runs well. 

The issue now is that none of the ME crafting terminals neither the Wireless Crafting terminals or the Universal wireless terminal won't work. They just now respond.

Can this be fixed or just because is skyfactory 4 modpack i have to get it all back as it was before I added the mods for it to work? or maybe i need to updated something else?

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-7
- SkyFactory 4 from twitch app

**Comment by Ommina** [comment]
Sadly, this is wholly a modpack issue, and not a bug with AE2.  I'd suggest taking it up with the Skyfactory4 designers, but as you elected to add it on your own, I'd expect them to suggest it isn't their problem either.

**Comment by Pingger** [comment]
when opneing the crafting terminal, do you get any exception in the server or client log? If yes, send the log.
Have you actually linked the terminals using the Security Controller?
