### ISSUE TITLE
Limitation of overall Crafting Units?

### ISSUE THREAD

**Issue by Nexo02** [AppliedEnergistics/Applied-Energistics-2#4394]
So, my problem or rather question is, if there is a maximum amount of Crafting/ Co-Processing Units you can have in the world at a time?
The reason i asked is because I can't pull any Items related to Crafting Units out of my ME System anymore. I already placed down a lot, so I figured that there need to be any kind of limitation. When I put some back in my System I can take them out normaly, but never aboth the amount I had before.

Is there any way to bypass or solve this? 
Many thanks in advance! =)

- Minecraft Version: 1.12.2
- AE2 Version: 23.7.19
- Forge Version: 14.23.5.2854

**Comment by Alex-hawks** [comment]
do you have a Storage Bus attached to anything like Extra Utilities' Player Chest?

**Comment by Nexo02** [comment]
I actually have some Massive Storage Bundles from Ender Utilities connected with storage busses. But only got ingots and some essence in it.

**Comment by Nexo02** [comment]
Nvm lol... I found the problem. Because I build my base new I had some storage busses connected with autocrafters but did not configured them yet. So they just got filled with random Stuff ^^ Well thanks a lot Alex =D
