### ISSUE TITLE
IOPS Item monitor

### ISSUE THREAD

**Issue by AlgorithmX2** [AppliedEnergistics/Applied-Energistics-2#44]
A monitor that has two numbers on it, the first one is how much of that item is outputted in some reaction per hour based on averages. The second number is how much of that one item is inputted in some reaction per hour based on averages. This would be a recipe that upgrades the Item monitor. It might still have the option to tell you how many of that item is there. Either way, I would find this feature very interesting.

Also, Great job on this mod. 11/10. My favorite mod hands down.

Originally Posted by Gixbit

This issue was migrated; For original details see http://ae-mod.info/Tracker/0398/

**Comment by Technici4n** [comment]
Unlikely to ever happen in AE2 itself, but addon developers are welcome to use our API to implement this feature!
