### ISSUE TITLE
Main thread hang in TickHandler

### ISSUE THREAD

**Issue by clienthax** [AppliedEnergistics/Applied-Energistics-2#4401]
**Describe the bug**
Main thread hangs occasionally for long peroids

**To Reproduce**
Unknown

**Expected behavior**
For the main thread to not hang

**Additional context**
Thread info https://gist.github.com/clienthax/5f871002b1ad4b41dadc876903c66ff8

**Environment**
- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-7.jar
- Forge Version: forge-1.12.2-14.23.5.2847-universal.jar
- Modpack: The 1.12.2 pack

**Comment by yueh** [comment]
We do not support anything like Sponge or Bukkit officially. Only a standard forge environment.

Should you be able to reproduce it without it and in a new environment and save, please update the issue accordingly and we will reopen it.
