### ISSUE TITLE
"IllegalStateException ItemStack#getCount() has to be 1" caused by "PartStorageBus being ticked"

### ISSUE THREAD

**Issue by NopeDK** [AppliedEnergistics/Applied-Energistics-2#4402]
**Describe the bug**

Server crash as per title.

**To Reproduce**

Unknown but the setup is a Storage Bus on a Storage Drawer Slave with an assortment of Mystical Agriculture essences stored.

![2020-06-05_00 42 31](https://user-images.githubusercontent.com/808397/83817666-a4179b00-a6c5-11ea-8ef4-d3006e24d3a7.png)

**Expected behavior**

No crash.

**Additional context**

Crashlog: https://pastebin.com/SexCsrEU

**Environment**

SMP, server crashed. DD&SS modpack v. 7.4a.

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-7
- Forge Version: forge-1.12.2-14.23.5.2847-universal.jar + spongeforge-1.12.2-2838-7.1.8.jar

**Comment by yueh** [comment]
We do not support anything like Sponge or Bukkit officially. Only a standard forge environment.

Should you be able to reproduce it without it and in a new environment and save, please update the issue accordingly and we will reopen it.
