### ISSUE TITLE
ME controller multiblock force loading chunks

### ISSUE THREAD

**Issue by frostie22** [AppliedEnergistics/Applied-Energistics-2#4411]
**Describe the bug**

Multiblock structures of me controller are force loading any chunks that contain the controller / network they control
**To Reproduce**

Build a multiblock Me Controller structure, have something you can test to see if a chunk is still active
Personally I tested importing 1000 items on lowest speeds while the chunk is unloaded and also smelting items within the chunk while its unloaded

**Expected behavior**

I was far away from spawn already, which is always loaded

I expected maybe 10 items to go into the system, with the time taken for me to activate the test and leave the area (I teleported 200 thousand blocks away)
I expected little smelting from objects smelted before I managed to tp away and unload the area

**Additional context**

All 1000 items went into the system and 4 stacks of ore smelted whilst unloaded

A test was conducted solely with ae2 items and thermal expansion¬dynamics / enderio power supply
then thermal expansion smelting devices were added on a second test

I found this bug on a server where I woke up in the morning to  many million items I started draining the night before I logged off, to be completely finished when I woke up, my base was private and nobody has reasonable access to stay in it long enough to transfer 14mill items. the me system was more or less 1 chunk in size

I tested it in singleplayer, building a semi-replica of the system, AE2/Thermal dynamics/Enderio/enderchests were  the mods, the 4 chunks I split it into all chunk loaded in tests I did

I found an old bug report (5 years ago) about me multiblocks chunk loading, so I isolated the controllers.
The test now included a controller, import bus, a storage block (I tested a few, same results, one being modded, the black hole unit from IF), cryotheum flux ducts and capacitor banks. I had the exact same chunk loading results.

**Environment**

Tested in MP and SP, 
Mods included in the test:
EnderIO: 1.12.2-5.1.55
(base enderio) EnderCore - 1.12.2-0.5.73
EnderStorage- 1.12.2-2.4.6.137-universal
(Modded storage example) industrialforegoing-1.12.2-1.12.13-237
ThermalDynamics-1.12.2-2.5.5.21-universal
ThermalExpanison-1.12.2-5.5.4.43

- Minecraft Version: 1.12.2 Tekxit 3 modpack by Slayer5934
- AE2 Version: appliedenergistics2-rv6-stable-7
- Forge Version: 14.23.5.2847

**Comment by mindforger** [comment]
ME systems should be loaded at any time, or you will encounter issues later on, especially in larger systems including security controller
Since you did not provide a crashlog i just want to know if there are ANY ae2 addons installed that MAY cause the behaviour. 

Please keep in mind my advice to keep the whole me chunkloaded or expect it to be funky at times you are leaving the area.

**Comment by frostie22** [comment]
There is no AE2 addons.

Whilst its beneficial to keep it loaded, it permaloads chunks itself anyway, this is especially bad on servers because these chunks never unload which can be problematic.

**Comment by mindforger** [comment]
I see what you mean, i was just making sure your modlist is complete, since the named modpack is larger

**Comment by frostie22** [comment]
yea apologises, it is concerning if it is permanently chunk loading. At least the place i manage its not a known thing but it can be very bad if it begins to be used to force perm loaded chunks

**Comment by yueh** [comment]
Controllers are pretty much dumb blocks. The old issue was because validating the multiblock didn't take unloaded chunks into account. Which was fixed long ago.

In this case let's make the assumption that the capacitor banks keep it loaded because the constantly push energy into adjacent blocks, even if these are unloaded.
