### ISSUE TITLE
Placing interface terminal on a facaded interface terminal => crash

### ISSUE THREAD

**Issue by PoolloverNathan** [AppliedEnergistics/Applied-Energistics-2#4414]
**Describe the bug**

See title

**To Reproduce**

1. Do your standard spatial setup (optional)
2. Place a ME Drive, ME Cable, ME Interface Terminal, and ME Facade in that order.
3. Place another interface terminal on the *edge* of the facade and try to figure out what got concurrently modified.

**Expected behavior**

The placement should fail or attempt to place a terminal in front of the existing one.

**Additional context**

https://pastebin.com/AgyZ975A
**Environment**

See crash log

**Comment by shartte** [comment]
If you can reproduce this issue with only AE2 installed, please open a new issue with the relevant crashlog, otherwise please report this to the makers of your modpack.

**Comment by PoolloverNathan** [comment]
Why would I report an error to myself...
