### ISSUE TITLE
Matrix Frame

### ISSUE THREAD

**Issue by DoremySwee** [AppliedEnergistics/Applied-Energistics-2#4416]
I found that I can place this block by right-clicking with the item appliedenergistics2:matrix_frame, while others can't. We all used rv6-stable7. So I'm simply wondering what caused this difference.

(Perhaps I shouldn't consider this as a bug.)
(I'm sorry that my poor English may cause some inconvenience. I hope it doesn't matter.)

**Comment by mindforger** [comment]
sounds like 1.12 which is cirrently not supported anymore

but i assume you have a security controller installed and you are placing the frame against a structure that is connected with said security controller?!

you need to give a bit more detailed information to reproduce or analyze the effect

versions, screenshots or a forced crashlog (press and hold f3 + c while ingame, not title, singleplayer would be enough) to get a grip of all mods used in that case

**Comment by DoremySwee** [comment]
> sounds like 1.12 which is cirrently not supported anymore
> 
> but i assume you have a security controller installed and you are placing the frame against a structure that is connected with said security controller?!
> 
> did you make sure other people are allowed on that security controller?
> 
> you need to give a bit more detailed information to reproduce or analyze the effect
> 
> versions, screenshots or a forced crashlog (press and hold f3 + c while ingame, not title, singleplayer would be enough) to get a grip of all mods used in that case

I'm afraid you misunderstood me.
I meant the block appliedenergistics2:matrix_frame which isn't available in survival and creative tabs.
I can place it. While others can't place it by right-clicking.
No crash. Only difference between my client and my friends'. I'm simply wondering what caused the difference.
We all only used AE2-rv6-stable7.

**Comment by yueh** [comment]
As you already noticed, you cannot aquire it with normal means. So do not be surprised when cheating in some of them will not work as expected or even start corrupting your world.
