### ISSUE TITLE
Quantum Ring turning off when leaving the chunk, tho it is loaded.

### ISSUE THREAD

**Issue by HeyIJoNNy** [AppliedEnergistics/Applied-Energistics-2#4417]
**Describe the bug**

I have a QNB Setup with one network, with one ME Controller multiblock.
One end is directly connected to the controller with ME Dense Cables. The other has an energy acceptor with Dense Cells and a flux point connected. The "Controller End" works fine, but when i leave the "Second End" Chunk then the QR on this side is turning off. To check it i'm using a wireless Terminal outside. Even when i get back in the chunk, the QR remains off. To fix this i have to break one block of the QR an place it again.

**To Reproduce**

Setup as described above.

**Expected behavior**

I can access all interfaces on both sides. With my Wireless Terminal or a normal one.

**Environment**

Minecraft Eternal Modpack on a dedicated Server.
Version: 1.3.5.3
forge-14.23.5.2847

**Comment by Exordio** [comment]
hello, do u use chiken chunks - to load chunks? try it if no

**Comment by HeyIJoNNy** [comment]
What i already tried is:
Flux Points with the chunkloading option.
Chicken Chunks
World Anchor from Railcraft.
All of this ends up the same.

**Comment by aducheylard** [comment]
I have a QR within 300 blocks from my main base and it only has one storage and an import bus, and everytime I start the server I have to break one cable or a QR block to 'refresh' the network. Also tried using the chunkloading option and Chicken Chunks and the problem is still there

**Comment by Exordio** [comment]
If your quantum bridge does not work, be sure to check the following

1) Are both sides of the quantum bridge powered by electricity? If yes, then they glow
2) A matching pair of Quantum Entangled Singularities inside?
3) Are the chunks of both places loaded?
4) It is possible in the ME network to have only 1 controller multiblock. The fact that they are separated by a quantum bridge does not change this. However, for the Sub network, you can have a separate controller multiblock
5) Electricity and cables should connect to the midpoints of the sides of the quantum bridge, and not to the corners.

**Comment by HeyIJoNNy** [comment]
All conditions are met.
I could provide some Screenshots, if this would help?
