### ISSUE TITLE
Meteorite Surface Detection Issues w/ YUNG's Better Caves

### ISSUE THREAD

**Issue by Brittank88** [AppliedEnergistics/Applied-Energistics-2#4424]
Posting a bug report as recommended by YUNG himself in [the bug report I posted to his GitHub page](https://github.com/yungnickyoung/YUNGs-Better-Caves/issues/58).

**Describe the bug**

Meteorites spawn underground within YUNG's Better Caves systems.

**To Reproduce**

1. Install AE2 and YUNG's Better Caves
2. Generate a new world
3. Go find a meteorite with a compass
4. Sometimes they'll be deep underground in caves

**Expected behavior**

Meteorites generate on the surface like they were designed to.

**Additional context**

![image](https://user-images.githubusercontent.com/24266948/85128442-a0167c00-b274-11ea-92ab-28bec63dba20.png)
![image](https://user-images.githubusercontent.com/24266948/85128617-ff748c00-b274-11ea-95e6-5b0dbbd2a45f.png)

**Environment**
I'm playing on `1.12.2`, using `bettercaves-1.12.2-2.0.3`, AE2 version `rv6-stable-7` and forge version `14.23.5.2854`. Let me know if you need any more information.

Modlist: https://hatebin.com/bothdgufny

[Forced crash report](https://hatebin.com/kndrvluqqz).

**Comment by mindforger** [comment]
They spawn over AND underground, that IS by design.

**Comment by Brittank88** [comment]
Huh, my apologies then!

**Comment by mindforger** [comment]
that is what the meteorite compass is for, so you don't have to wander around to find a surface one

sidenote: they will most probably reach over chunkborders, so identifying the 2 or 4 chunks there in and a little logic thinking will make it possible to almost always pinpoint them with the first hole ... unless it is a cluster, thats just mean then :P

**Comment by Brittank88** [comment]
Thanks for the tips!

Also gonna share this with you, this "intended behaviour" my friend screenshotted might make you laugh :P 

![image](https://user-images.githubusercontent.com/24266948/85394177-84bbb180-b591-11ea-971f-80e9bba1d1cc.png)

**Comment by mindforger** [comment]
Yeah, had those monster crater before, quite a nice place for a base
