### ISSUE TITLE
Not able to build from source with gradle

### ISSUE THREAD

**Issue by lev4ukpavel2** [AppliedEnergistics/Applied-Energistics-2#4425]
**Describe the bug**
Using instructions on building the mod using Gradle, the build fails on resolving dependencies from curseforge.

**To Reproduce**
Follow the instructions on how to build the mod from source using Gradle

**Expected behavior**
The build is expected to complete successfully

**Additional context**
https://hastebin.com/otamowefah.http

**Environment**
Tried building on Windows 10 with Java 1.8.0_251 and on Kali Linux with OpenJDK-8 using WSL.

**Comment by yueh** [comment]
1.15 is in no way usable for anyone but developers, which would be able to understand the error easily.
