### ISSUE TITLE
ME Interface Table should display the DisplayName of the block

### ISSUE THREAD

**Issue by Tanju42** [AppliedEnergistics/Applied-Energistics-2#4426]
When a Interface is connected to a Oak Chest it shows in the terminal so:
![image](https://user-images.githubusercontent.com/16364184/85212263-68c9cd00-b351-11ea-98a7-933b081ca7b1.png)

BUT I want a feature that displays the name of the renamed item eg. when I name the chest "TEST" in the Anvil and place it on the interface then it should display the DisplayName:
![image](https://user-images.githubusercontent.com/16364184/85212305-c9f1a080-b351-11ea-835b-a332e5554ad7.png)

**Comment by yueh** [comment]
[ME Interface Terminal](https://ae-mod.info/ME-Interface-Terminal/)
