### ISSUE TITLE
Few bugs in v7.0.0-alpha.3 

### ISSUE THREAD

**Issue by Tahakk** [AppliedEnergistics/Applied-Energistics-2#4436]
**Describe the bug**
1. Channels acting weird
   a. they don't respect channel limits
   b. they 'overflow' to the other cables
2. energy  in Controllers shows 0/8k in TOP
3. Disk Drives
   a. always shows disks as online - even if not connected to the network
   b. weird shadowing with block above/aside
   c. disk drives appear to be empty (new texture or bug?)

**To Reproduce**

33/8???
![2020-06-28_19 33 46](https://user-images.githubusercontent.com/25863620/85954488-279c7300-b978-11ea-9c88-5120f73647bb.png)

33/8 when nothing connected?
![2020-06-28_19 33 54](https://user-images.githubusercontent.com/25863620/85954489-28350980-b978-11ea-982f-3fc0b14a7daf.png)

Drives online without being connected
![2020-06-28_19 34 24](https://user-images.githubusercontent.com/25863620/85954491-28cda000-b978-11ea-85dc-6b35c2563e27.png)

Bottom drive shadows?
![2020-06-28_19 34 30](https://user-images.githubusercontent.com/25863620/85954492-29663680-b978-11ea-810c-8c0b5523e58f.png)

On the left Drive you can see shadow in the middle that is created there. If intention l it's not happening for the other side
![2020-06-28_19 34 42](https://user-images.githubusercontent.com/25863620/85954484-2703dc80-b978-11ea-9d5a-2cab90a031f0.png)
![2020-06-28_19 34 40](https://user-images.githubusercontent.com/25863620/85954494-29663680-b978-11ea-9bda-aee1960edf19.png)

0/8k with creative source
![2020-06-28_19 51 50](https://user-images.githubusercontent.com/25863620/85954594-d2ad2c80-b978-11ea-907c-a07270fde9a6.png)

**Environment**
[crash-2020-06-28_19.41.49-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/4842741/crash-2020-06-28_19.41.49-client.txt) - forced crash

**Comment by yueh** [comment]
1. Already fixed
2. That happens as long as controllers don't get any external energy
3. a. Fixed
   b. Might be fixed, but overall a bug/missing feature in forge.
   c. A new model
