### ISSUE TITLE
Placing Down Energy Dev Tool Causes Game to stop responding and crashes game when loading the world

### ISSUE THREAD

**Issue by ImVaskel** [AppliedEnergistics/Applied-Energistics-2#4437]
**Describe the bug**

When placing down the Dev Tool "Energy" in v7.0.0 Alpha 3 causes the game to instantly stop responding. After my game finally crashed I reloaded it and then loaded my world, causing my game to instantly crash.
**To Reproduce**

Place the Dev Tool "energy"
**Expected behavior**

To not crash my game
**Additional context**
https://pastebin.com/J03p9s6t (Initial crash) https://pastebin.com/UkzEKbEu (World Loading Crash)

**Environment**

- Environment:

**Comment by yueh** [comment]
Dev/Debug tools are in general unsupported and can easily corrupt your world. With 1.15 we can no longer disable blocks based on a config value and there is no real reliable way to prevent players from aquiring them. That is simply how forge now wants to handle things and through it expose players to potentially dangerous items without an easy way to deal with them in case they start acting up.
