### ISSUE TITLE
Fluid terminal doesn't detect fluid storage on subnetworks

### ISSUE THREAD

**Issue by Bricklou** [AppliedEnergistics/Applied-Energistics-2#4440]
**Describe the bug**
I have my ME drive on a subnetwork with fluid disk inside, I can't access of the disk from the main network while I can access normally with normal disks.

**To Reproduce**

- Place a ME controller with a terminal and a fluid terminal
- Create a subnetwork with ME interface and ME storage bus
- Place a ME drive on the subnetwork
- Add a normal disk and a fluid disk in the ME drive
- Add some items in the terminal
- Try to add fluid in the fluid terminal

**Expected behavior**
It should add fluid in the fluid disk even if this disk is on a subnetwork

**Additional context**
![image](https://user-images.githubusercontent.com/15181236/86135213-cba62b80-baea-11ea-944a-d8fac882b14e.png)
![image](https://user-images.githubusercontent.com/15181236/86135230-d2cd3980-baea-11ea-96ee-26d5b78d68e8.png)

**Environment**

- Crashlogs: https://hastebin.com/oxejufeyoz.log

**Comment by shartte** [comment]
Isn't this expected? You didn't use a fluid storage bus / fluid interface to connect the subnetwork if I get your picture right...

**Comment by Bricklou** [comment]
Really this is just a fluid storage problem ? 😅
I will try it right now to see if this is that.

**Comment by Bricklou** [comment]
I tried and this is all my fault. With fluid storage bus and fluid interface it work well.
But that's too bad there is no way to to normal interface/storage bus and fluid ones at same time. 😢
