### ISSUE TITLE
Game crashing after Me controllers were placed

### ISSUE THREAD

**Issue by Gigglingg** [AppliedEnergistics/Applied-Energistics-2#4450]
I deleted all Ae2 addons, optifine, also removed me controllers somehow but game is still crashing after few seconds or immediately

Latest crash report
[crash-2020-07-04_12.00.05-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/4872504/crash-2020-07-04_12.00.05-server.txt)

**Comment by Pingger** [comment]
For some reason the "tesseract" (com.supermartijn642.**tesseract**.capabilities.CombinedItemHandler)  tries to get the Slot with id 10 ... which does not exist ... and then is not properly catching the resulting exception ...

**Comment by Ommina** [comment]
Not AE2 -- and [may already be fixed on Tesseract's side](https://github.com/SuperMartijn642/Tesseract/commit/6257bcd98ba38a0fffe88ff616f3ec0be50ca0f5#diff-3f4c9cf3c79ba7cd8428409eb4561861L100).  Try (their) version 1.0.6.

**Comment by Gigglingg** [comment]
Thank you so much, I was scared of idea repeating (somehow) my world. It seems tesseract was causing these problems. I put a chest between tesseract and interface for a while and it works. Thx again
