### ISSUE TITLE
Crash between AE2, ThermalExpansion and Placebo (FastFurnace?) clientside.

### ISSUE THREAD

**Issue by strivenous** [AppliedEnergistics/Applied-Energistics-2#4460]
**Describe the bug**
Apparently there's a clientside crash between Placebo, AE2 and Thermal, it's trying to output something from AE2 via Thermal and then it screws up. Believe it's the certus quartz crystal.

**To Reproduce**
Can provide the server and client pack.

**Expected behavior**
Normal behavior.

**Additional context**
 
 

**Environment**
 https://gist.github.com/strivenous/7f28299d7490b27eaf9473c5e1663ec3
 can't join 

- Environment: 
https://gist.github.com/strivenous/7f28299d7490b27eaf9473c5e1663ec3 
can't join any server or world with AE2, so I can't force crash.

**Comment by strivenous** [comment]
forgot to link the crash: https://gist.github.com/strivenous/4ca50ee2817b46a854f7df12bc0130a8

**Comment by strivenous** [comment]
tried to disable fast shapeless, no success

**Comment by strivenous** [comment]
no success with both client and server side fastshapeless disabled

**Comment by Ommina** [comment]
I don't see AE2 in the stack trace anywhere.  If the same crash continues without Placebo removed, post the new crash report.

**Comment by Meller127** [comment]
> I don't see AE2 in the stack trace anywhere. If the same crash continues without Placebo removed, post the new crash report.

java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Recipe thermalfoundation:material_97 (shadows.placebo.util.FastShapelessRecipe@63be3a69) **produces unregistered item appliedenergistics2:material (ItemMaterial[material])**

Dont know if its AE2 fault or Placebo doing something

**Comment by Ommina** [comment]
Heh.  I was quite careful to say "in the stack trace", not 'the exception message', just to ward off that very objection. 

The only (non-MC) _code_ that is mentioned is Placebo.  As such, my suggestion remains to remove Placebo.  If it still crashes, post a new crash report.

**Comment by yueh** [comment]
Based on the crashlog placebo seems to register an invalid recipe with at least one missing item. Most likely something they have to fix.
