### ISSUE TITLE
Crash on 1.15.2 server-side. 

### ISSUE THREAD

**Issue by MaximoTG98** [AppliedEnergistics/Applied-Energistics-2#4461]
I made a server modpack that includes AppliedEnergistics 2 and when it tries to load the whole server crashes.

**Issue**
Mentioned before, crash when AE2 loads, in my client works perfectly but when the server tries to run the mod I get a crash.

**Environment**
I attached the log and debug of the crash on the description.
[latest.log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/4906870/latest.log)
[debug.log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/4906869/debug.log)

The server is running in 1.15.2 with AE2 last version ,the modlist in the server is:
[modlist.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/4906879/modlist.txt) (Change the extension from .txt to .html) The server has the same mods except from:

- It's the little things
- Optifine
- RandomPatches
- SoundFilters
(there are client-side mods that are also on the server but not running, didn't have time to remove those, but I'm sure they don't mess up with AE2)

I'm able to test the server as many times as needed to fix the crash.

**Comment by mindforger** [comment]
"This crash report has been saved to: /home/minecraft/servers/mine277224/./crash-reports/crash-2020-07-11_15.56.53-server.txt" 

the actual crashlog would be a bit shorter and more usefull, also please use pastebin instead of uploading files

**Comment by shartte** [comment]
@MaximoTG98 Should already be fixed in newer version.
