### ISSUE TITLE
Encountered an error during the common_setup event phase in v7.0.0-alpha.7

### ISSUE THREAD

**Issue by TheBigerGamer** [AppliedEnergistics/Applied-Energistics-2#4465]
**Describe the bug**

I loaded minecraft with only the latest version of applied energistics, but it will not load and always throw this error:
![image](https://user-images.githubusercontent.com/39341546/87558222-c59a7800-c6b0-11ea-83a0-b38fe6be4629.png)

Also, for what I saw in the other issues, it seems like other people could start the game with the alpha.3 version, but it thrown the same error with me.

**To Reproduce**

Just start minecraft forge with only appliedenergistics2-7.0.0-alpha.7.

**Expected behavior**

Minecraft to lauch normally.

**Additional context**

There isn't any crash report, but only latest.log: https://pastebin.com/KSpr4VCv

**Environment**

- Environment: https://pastebin.com/kqYiBFu6

**Comment by Ommina** [comment]
#4456 

Update Forge.  At least 31.2.5.

**Comment by shartte** [comment]
Also, we upped the Forge requirement to minimum version 31.2.31 now.
