### ISSUE TITLE
AE2 + ForgeSponge, first server start error

### ISSUE THREAD

**Issue by sidboy55555** [AppliedEnergistics/Applied-Energistics-2#4470]
Hi!
I have made my own modpack recently, and I've been updating my server side without reinstalling the modpack but instead changing the changes manually. Somewhere in the versions I've added spongeforge, which worked fine.
but now I wanted to make a creative server (and so installing the modpack from the serverpack.zip). and get this crash report.
https://pastebin.com/5vGuF6p1 , and of course the server won't start. Now I've deleted the spongeforge jar, started the server, and it booted up fine. now close it down again, reinstalled spongeforge, and now the server boots fine again. I though the incompatibility with spongeforge was fixed. or is this a new bug?
Regards, Sidney - sidboy55555

**Comment by yueh** [comment]
We do not support anything like Sponge or Bukkit officially. Only a standard forge environment.

Should you be able to reproduce it without it and in a new environment and save, please update the issue accordingly and we will reopen it.
