### ISSUE TITLE
Start up crash rv6-stable-7 for 1.12.2

### ISSUE THREAD

**Issue by LabsZero** [AppliedEnergistics/Applied-Energistics-2#4476]
[crash-2020-07-18_11.13.57-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/4941454/crash-2020-07-18_11.13.57-client.txt)

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.15 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.

**Comment by LabsZero** [comment]
ok thank you i shell try
