### ISSUE TITLE
Bag with use safety terminal

### ISSUE THREAD

**Issue by IMozgg** [AppliedEnergistics/Applied-Energistics-2#4482]
**Describe the bug**

Hello, a have a problem with use security terminal and destruction plane and bus of storage together.
When I use security terminal destruction plane doesn’t receive any items through storage bus filter
**To Reproduce**

If remove security terminal, the destruction plane work now.
**Expected behavior**

**Additional context**

**Environment**

Minecraft 12.2 , ae2 last

- Environment:

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.15 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
