### ISSUE TITLE
Crash when Switching Sort By in Crafting Terminal

### ISSUE THREAD

**Issue by Dyonovan** [AppliedEnergistics/Applied-Energistics-2#4488]
When switching the sort by in the crafting terminal, causes server to crash.

Version: 7.0.0-alpha.8

[crash-2020-07-20_20.21.00-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/4950573/crash-2020-07-20_20.21.00-server.txt)

**Comment by shartte** [comment]
Confirmed. PacketBuffer#readString seems to be client-only.
