### ISSUE TITLE
Right Clicking on Search Bar in Crafting Terminal does not Clear writing.

### ISSUE THREAD

**Issue by Dyonovan** [AppliedEnergistics/Applied-Energistics-2#4492]
If I recall, shouldn't right clicking on the search bar clear any text that is currently inside?

Version: 7.0.0-alpha.8

**Comment by yueh** [comment]
Please do not report missing features in this stage. Usually we are aware of them and simply have not gotten to them or these are no longer possible due to changes in forge or rarely other mods.
