### ISSUE TITLE
Got a server crash saying something about ae2 argument

### ISSUE THREAD

**Issue by dbaum42** [AppliedEnergistics/Applied-Energistics-2#4512]
https://pastebin.com/eWUjLBwd

not sure what else to say tried adding mods to my server I have 100 total so far and also trying to add plugins

**Comment by yueh** [comment]
We do not support anything like Sponge or Bukkit officially. Only a standard forge environment.

Should you be able to reproduce it without it and in a new environment and save, please update the issue accordingly and we will reopen it.
