### ISSUE TITLE
Calculation of crafting jobs which include "reusable items" takes extremely long

### ISSUE THREAD

**Issue by d-avery** [AppliedEnergistics/Applied-Energistics-2#4515]
**Describe the bug**

Calculation of crafting jobs which include "reusable items" (Philosopher's Stone, Infusion Crystal..) takes extremely long.

**To Reproduce**

Start crafting job which involves usage of reusable items. Slowness isn't that noticeable when requesting single items, but once you request multiple, calculating the craft takes excruciatingly long.

**Expected behavior**
Crafting job including reusable item takes as long to calculate as other crafting jobs of similar size.

**Additional context**

![image](https://user-images.githubusercontent.com/29543330/88740693-8b1beb00-d146-11ea-8446-2ccb0eb1b741.png)

**Environment**

- Environment: 
Windows 10 Pro
Stoneblock 2 Modpack Version 1.19.0, Forge Version 14.23.5.2847
Java 8 261 64-bit
MultiMC 0.6.11
AE2 rv6 stable 7

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.15 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.

**Comment by d-avery** [comment]
Tested in 7.0.3 for 1.15.2. Issue is resolved, calculating crafting jobs with reusable items (in this case, Philosopher's Stone from ProjectE) now takes just as long as calculating other jobs.
