### ISSUE TITLE
Error with applied

### ISSUE THREAD

**Issue by P4um** [AppliedEnergistics/Applied-Energistics-2#4516]
https://pastebin.com/rDc1twBa

please, I have this error on my console and my server turns off and on every time

**Comment by mindforger** [comment]
There is a template on how to properly file a report which tells you to check for a crash report, which your log tells is stored in „This crash report has been saved to: /home/container/./crash-reports/crash-2020-07-28_22.01.18-server.txt“ .. Also from the log, it seems like a broken config

Please follow the template when reporting in future

**Comment by P4um** [comment]
[crash-2020-07-28_22.01.18-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/4994593/crash-2020-07-28_22.01.18-server.txt)
here crash report

**Comment by mindforger** [comment]
As i said, corrupted config or from the stacktrace a corrupted Player list file, but no idea which. Supposedly not an AE fault

**Comment by P4um** [comment]
do you know how I can at least try to reset this error? do I have to reset the list of players?

**Comment by Ommina** [comment]
I can't tell which file is affected; I note you are using a "Mohist" server (which I'd never heard of before), and that may be messing with the line numbers.

I would suggest checking the various lists (player ban list, ip ban list, op list, white list) looking for an EMPTY file.  Check them all in case multiple files are empty.
