### ISSUE TITLE
ME always craft swiftness potion speed II even when in stock

### ISSUE THREAD

**Issue by hacker104** [AppliedEnergistics/Applied-Energistics-2#4519]
**Describe the bug**
ME always craft swiftness potion speed II even when in stock

**To Reproduce**
carft some thing with swiftness potion speed II

**Expected behavior**
use the stock items

**Additional context**

**Environment**

- Environment: 
os: debian linux buster 10 
modpack:skyfactory4 4.1.0
version:1.12.2
mod version: rv6 stable 7

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.15 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
