### ISSUE TITLE
[1.16/1.15] Add away to hide facades all at once in JEI

### ISSUE THREAD

**Issue by BedrockLegends** [AppliedEnergistics/Applied-Energistics-2#4520]
**Describe the feature**

I would like to see away for all the Facades added by Ae2 to be hidden by a config option for JEI, as going and click every single facade you guys have one by one takes forever to hide

**Reasons why it should be considered**

This can help a ton of Modpack creators out that like to Hide things from JEI for a much cleaner look.

**Additional Context**

**Comment by yueh** [comment]
As far as I am aware, JEI still has no way to group items together in a way that players can easily understand that there are actually multiple different ones.

The current options are as far as I am aware either to hide all facades or to combine all into one and only show a stone facade.
The first option will lead to reports about "why are there no facades" and the second to "why are there only stone facades".
Neither are really acceptable options in terms of UX. Also with the new forge config system, I am not even sure, if that is available at the time we would have to register the items to JEI.

The minimum functionality JEI would have to provide is a way to group different itemstacks together in an easily recognizable way. E.g. cycle through a different one every second in the overview and also make it apparent for the recipe itself. E.g. similar to item tags by cycling through each ingredient option, but still be synchronized correctly. So nothing like displaying that a dirt block would craft a diamond facade.

**Comment by Tahakk** [comment]
You can use Hide function in JEI. For 1.15.2 it's not fully implemented yet it seems but you turn on Edit/Hide mode in the JEI options (or hotkey) and just Control + Right Click any facade and that will select and hide all of them. That easy
