### ISSUE TITLE
[1.15.2] No meteorite generation with Biomes O Plenty

### ISSUE THREAD

**Issue by TheUntamed** [AppliedEnergistics/Applied-Energistics-2#4524]
**Describe the bug**

If I create a world with Biomes O Plenty (BOP) installed (even if I use default generation) the compass is rotating all the time and after flying around a bit I could not find any meteorites.

**To Reproduce**

Install ae2 and BOP and create a world. It doesn't matter if it's a world with BOP world gen or default world gen. The compass should rotate all the time. This only happens if BOP are installed.

**Expected behavior**

**Additional context**

No crash.

**Environment**

- Environment: 
forge-31.2.33
appliedenergistics2-7.0.0-beta.1
BiomesOPlenty-1.15.2-10.0.0.366

**Comment by yueh** [comment]
Cannot reproduce it, meteors are spawning fine for me in BiomesOPlenty biomes.

Keep in mind, we now make use of minecrafts structure spawning for meteors and it might takes a few minutes until they are succesfully detected. Just creating a new world and flying around for 30secs will most likely not trigger any. But this is certainly fine for normal games, as it would be highly unlikely to have all necessary tools and materials to use AE2 within 1 or 2 minutes.
