### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by newresource-dev** [AppliedEnergistics/Applied-Energistics-2#4530]
**Describe the bug**

*server crash on startup*

**Additional context**

[crash-2020-08-01_17.54.38-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5010788/crash-2020-08-01_17.54.38-server.txt)
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.b166.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  SpongeCoremod (spongeforge-1.12.2-2838-7.2.3.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 8/1/20 5:54 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Energistics 2 (appliedenergistics2)
Caused by: java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
	at appeng.core.worlddata.WorldData.<init>(WorldData.java:79)
	at appeng.core.worlddata.WorldData.onServerAboutToStart(WorldData.java:132)
	at appeng.core.AppEng.serverAboutToStart(AppEng.java:259)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.redirect$zza000$forgeImpl$PostEvent(LoadController.java:568)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.serverAboutToStart(Loader.java:859)
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:292)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:268)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$zjf000$onCrashReport(MinecraftServer.java:4687)

-- Sponge PhaseTracker --
Details:
	Phase Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$zjf000$onCrashReport(MinecraftServer.java:4687)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:889)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:371)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:558)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_261, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 15158269440 bytes (14456 MB) / 17179869184 bytes (16384 MB) up to 17179869184 bytes (16384 MB)
	JVM Flags: 20 total; -Xms16G -Xmx16G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=40 -XX:G1MaxNewSizePercent=50 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=15 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=20 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 58 mods loaded, 58 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	Mods:

	| State   | ID                                | Version                  | Source                                               | Signature                                |
	|:------- |:--------------------------------- |:------------------------ |:---------------------------------------------------- |:---------------------------------------- |
	| LCHIJA  | minecraft                         | 1.12.2                   | minecraft.jar                                        | None                                     |
	| LCHIJA  | mcp                               | 9.42                     | minecraft.jar                                        | None                                     |
	| LCHIJA  | FML                               | 8.0.99.99                | forge.jar                                            | None                                     |
	| LCHIJA  | forge                             | 14.23.5.2847             | forge.jar                                            | None                                     |
	| LCHIJA  | spongeapi                         | 7.2.0-e4abe364d          | spongeforge-1.12.2-2838-7.2.3.jar                    | None                                     |
	| LCHIJA  | sponge                            | 1.12.2-7.2.3             | spongeforge-1.12.2-2838-7.2.3.jar                    | None                                     |
	| LCHIJA  | spongeforge                       | 1.12.2-2838-7.2.3        | spongeforge-1.12.2-2838-7.2.3.jar                    | None                                     |
	| LCHIJA  | quarryplus                        | 12.4.1                   | AdditionalEnchantedMiner-1.12.2-12.4.1-universal.jar | 617a4e95f0af9de5402bb9883abe0f53a6bfa230 |
	| LCHIJA  | quarryplus_ct                     | 12.4.1                   | AdditionalEnchantedMiner-1.12.2-12.4.1-universal.jar | 617a4e95f0af9de5402bb9883abe0f53a6bfa230 |
	| LCHIJA  | ic2                               | 2.8.188-ex112            | industrialcraft-2-2.8.188-ex112.jar                  | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA  | advanced_machines                 | 61.0.1                   | Advanced+Machines-61.0.1.jar                         | None                                     |
	| LCHIJA  | advanced_solar_panels             | 4.3.0                    | Advanced+Solar+Panels-4.3.0.jar                      | None                                     |
	| LCHIJAE | appliedenergistics2               | rv6-stable-7             | appliedenergistics2-rv6-stable-7.jar                 | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA  | aroma1997core                     | 2.0.0.2.b166             | Aroma1997Core-1.12.2-2.0.0.2.b166.jar                | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHIJA  | attributefix                      | 1.0.4                    | AttributeFix-1.12.2-1.0.4.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA  | morphtool                         | 1.2-21                   | Morph-o-Tool-1.2-21.jar                              | None                                     |
	| LCHIJA  | autoreglib                        | 1.3-32                   | AutoRegLib-1.3-32.jar                                | None                                     |
	| LCHIJA  | betterbuilderswands               | 0.13.2                   | BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar    | None                                     |
	| LCHIJA  | biomesoplenty                     | 7.0.1.2441               | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar        | None                                     |
	| LCHIJA  | bopadditions                      | 1.1.2                    | BoPAdditions-1.1.2.jar                               | None                                     |
	| LCHIJA  | codechickenlib                    | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA  | chickenchunks                     | 2.4.2.74                 | ChickenChunks-1.12.2-2.4.2.74-universal.jar          | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA  | clumps                            | 3.1.2                    | Clumps-3.1.2.jar                                     | None                                     |
	| LCHIJA  | dynamictrees                      | 1.12.2-0.9.8             | DynamicTrees-1.12.2-0.9.8.jar                        | None                                     |
	| LCHIJA  | dynamictreesbop                   | 1.12.2-1.4.1e            | DynamicTreesBOP-1.12.2-1.4.1e.jar                    | None                                     |
	| LCHIJA  | endercore                         | 1.12.2-0.5.76            | EnderCore-1.12.2-0.5.76.jar                          | None                                     |
	| LCHIJA  | jei                               | 4.15.0.296               | jei_1.12.2-4.15.0.296.jar                            | None                                     |
	| LCHIJA  | enderio                           | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                            | None                                     |
	| LCHIJA  | enderiointegrationtic             | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                            | None                                     |
	| LCHIJA  | enderiobase                       | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                            | None                                     |
	| LCHIJA  | enderioconduits                   | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                            | None                                     |
	| LCHIJA  | enderioconduitsappliedenergistics | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                            | None                                     |
	| LCHIJA  | enderioconduitsopencomputers      | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                            | None                                     |
	| LCHIJA  | enderioconduitsrefinedstorage     | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                            | None                                     |
	| LCHIJA  | forestry                          | 5.8.2.409                | forestry_1.12.2-5.8.2.409.jar                        | None                                     |
	| LCHIJA  | enderiointegrationforestry        | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                            | None                                     |
	| LCHIJA  | enderiointegrationticlate         | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                            | None                                     |
	| LCHIJA  | enderiomachines                   | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                            | None                                     |
	| LCHIJA  | enderiopowertools                 | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                            | None                                     |
	| LCHIJA  | endportrec                        | 1.0                      | endportrec_1.12-1.0.jar                              | None                                     |
	| LCHIJA  | extracells                        | 2.6.2                    | ExtraCells-1.12.2-2.6.2a.jar                         | None                                     |
	| LCHIJA  | gravisuite                        | 3.1.1                    | Gravitation+Suite-3.1.1.jar                          | None                                     |
	| LCHIJA  | inventorytweaks                   | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                             | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA  | iridiumsource                     | 2.0.1 - MC 1.12.2        | iridiumsource-2.0.1.jar                              | None                                     |
	| LCHIJA  | journeymap                        | 1.12.2-5.5.6             | journeymap-1.12.2-5.5.6.jar                          | None                                     |
	| LCHIJA  | jee                               | 1.0.8                    | JustEnoughEnergistics-1.12.2-1.0.8.jar               | None                                     |
	| LCHIJA  | redstonepaste                     | 1.7.5                    | redstonepaste-mc1.12-1.7.5.jar                       | None                                     |
	| LCHIJA  | surge                             | 2.0.77                   | Surge-1.12.2-2.0.77.jar                              | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA  | tatw                              | 1.0.1.2.b27              | Tatw-1.12.2-1.0.1.2.b27.jar                          | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHIJA  | wanionlib                         | 1.12.2-2.4               | WanionLib-1.12.2-2.4.jar                             | None                                     |
	| LCHIJA  | phosphor-lighting                 | 1.12.2-0.2.6             | phosphor-1.12.2-0.2.6+build50-universal.jar          | f0387d288626cc2d937daa504e74af570c52a2f1 |
	| LCHIJA  | unidict                           | 1.12.2-2.9.3             | UniDict-1.12.2-2.9.3.jar                             | None                                     |

	Plugins:

	| State  | ID            | Version         | Source                                             | Signature |
	|:------ |:------------- |:--------------- |:-------------------------------------------------- |:--------- |
	| LCHIJA | luckperms     | 5.1.17          | LuckPerms-Sponge-5.1.17.jar                        | None      |
	| LCHIJA | nucleus       | 1.14.6-S7.1     | Nucleus-1.14.6-S7.1-MC1.12.2-plugin.jar            | None      |
	| LCHIJA | magibridge    | 2.10.0          | MagiBridge-API7-2.10.0.jar                         | None      |
	| LCHIJA | totaleconomy  | 1.8.1           | TotalEconomy-1.8.1.jar                             | None      |
	| LCHIJA | universeguard | 2.24            | UniverseGuard-2.24.jar                             | None      |
	| LCHIJA | worldedit     | 6.1.10-SNAPSHOT | worldedit-sponge-api7.1.0-6.1.10-SNAPSHOT-dist.jar | None      |

	Loaded coremods (and transformers): 
CoreMod (Aroma1997Core-1.12.2-2.0.0.2.b166.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
SpongeCoremod (spongeforge-1.12.2-2838-7.2.3.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  
SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
  
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                 An unsupported base software is installed: 'sponge'. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Authlib is : /C:/Users/Mihail/Desktop/server/minecraft_server.1.12.2.jar

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:OFF, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)`

**Please write how to solve this problem**

**Comment by yueh** [comment]
We do not support anything like Sponge or Bukkit officially. Only a standard forge environment.

Should you be able to reproduce it without it and in a new environment and save, please update the issue accordingly and we will reopen it.

**Comment by newresource-dev** [comment]
**Thanks for saying about sponge. I was able to fix the problem by installing a different version of sponge.**
