### ISSUE TITLE
Crash using AE2 in SMP 1.16.1 forge 32.0.77

### ISSUE THREAD

**Issue by archonsd** [AppliedEnergistics/Applied-Energistics-2#4531]
**Describe the bug**
Server crashes on startup with specific AE crash.

**To Reproduce**
Install forge .77, install mod, start server.

**Expected behavior**
Server to be able to start without crashing.

**Additional context**
https://pastebin.com/UFsJtZ4d -- Console Crash output

**Environment**
SMP

- Environment:

**Comment by zmg2008** [comment]
This is listed as closed (mine was closed as a duplicate of this one) - does that mean it has been fixed in a version that will be released shortly? Thanks for everything you do, this mod is the best!

**Comment by Ommina** [comment]
@zmg2008 -- I will not promise 'shortly', as I don't know how shartte and yueh are deciding when to release a new version.  But yes, it is marked as fixed for a future release.

**Comment by yueh** [comment]
Once there are enough fixes, yes. But we won't push one for every small fix. Also this is still an alpha, so there is a good chance for a breaking change, which could break your world. So it is something you should be ready to deal with when using an alpha.

**Comment by zmg2008** [comment]
No worries at all @yueh @Ommina! Thank you for all you do, really underappreciated work but I definitely appreciate all you do.
