### ISSUE TITLE
Crash happens after I put a ME Controller connected to a configured P2P Tunnel - AE (Input Side) with a quantum ring connected too.

### ISSUE THREAD

**Issue by Micrafast** [AppliedEnergistics/Applied-Energistics-2#4535]
**Describe the bug**

Server first crashed after I put a ME Controller connected to a configured P2P Tunnel - AE (Input Side) with a quantum ring connected too.
After restarting the server, it had run normally for about 6 hours until it suddenly crashed again with no players in the server.
The server restarted again, and the server had run normally for another 6 hours approximately.
Then the server crashed, and it crashes after starting for some minutes now.
It seemed to be caused by the energy grid of the ME Network.

**To Reproduce**

As the description said, it's too confusing that I have no idea about how to reproduce this crash.

**Expected behavior**

The server should run normally without these crashes.

**Additional context**

The first crash: https://pastebin.com/6GQuMenb
The second crash: https://pastebin.com/N4jb3egq

**Environment**

- Environment:

**Comment by shartte** [comment]
This issue should be fixed in 1.15 (see #4484). It'll probably not be fixed in 1.12. Sorry!
