### ISSUE TITLE
Mekanism mechanical pipe and Fluid P2P tunnel crashing the game

### ISSUE THREAD

**Issue by NiamiTV** [AppliedEnergistics/Applied-Energistics-2#4537]
**Describe the bug**

Mekanism mechanical pipes have unexpected behaviour with Fluid P2P tunnels. The tunnels work but then the tunnel is broken it crashes the game, but allows me to load back in. I can transport liquids through P2P tunnels most of the time without issues but interacting with the tunnel (breaking the tunnel or the pipe connected to it) after connecting it causes crashes for me

**To Reproduce**

I can't actually provide proper steps to reproduce the issue as my server unexpectedly crashed while I wasn't on it and now it wont load up. I have a related issue though where breaking the P2P tunnel connected to a mechanical pipe crashes the server but doesnt lock up the world.

The best I can do:
1. Connect a Fluid P2P tunnel to a mechanical pipe that has a resource in it
2. Break the P2P tunnel, this results in a crash without locking the world

**Expected behavior**

There should be no issues with Fluid P2P tunnnels interacting.

**Additional context**

https://pastebin.com/Q9wDubYz
This a similiar issue to #4529 where any kind fluid interface has unexpected results with mekanism's mechanical pipes

**Environment**

- Environment:  https://pastebin.com/Yah7ZMZK

**Comment by yueh** [comment]
Fluid P2P is still subject for a rewrite, so this particular one will not be fixed. (directly)
