### ISSUE TITLE
[1.16.1] Crash when opening a terminal/portable cell

### ISSUE THREAD

**Issue by TBiscuit1** [AppliedEnergistics/Applied-Energistics-2#4547]
**Describe the bug**

When you open a terminal or a portable cell, the game crash

**To Reproduce**

Open a terminal or use a portable cell, (is probably caused by an other mod, so, test will be needed)

**Expected behavior**

Not to crash, quite obvious

**Additional context**

Crash Report VVV
[crash-2020-08-03_15.13.13-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5018002/crash-2020-08-03_15.13.13-client.txt)

Logs VVV
[latest.log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5018004/latest.log)

**Environment**

- Environment: 
Minecraft Version : 1.16.1
Forge Version : 32.0.98
Applied Version : 8.0.0-alpha.1
Modpack Mod List : 
[modpack mod list.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5018066/modpack.mod.list.txt)

**Comment by yueh** [comment]
This does not make much sense at all. Can you please test it with just AE2?

**Comment by hickorysb** [comment]
I was able to replicate this bug with the same error using just AE2 in under these circumstances.

**Environment**
Minecraft Version : 1.16.1
Forge Version : 32.0.98
Applied Version : 8.0.0-alpha.1

**Crash Log**
[crash-2020-08-03_23.34.28-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5020792/crash-2020-08-03_23.34.28-client.txt)

It appears `SettingsToggleButton.getWidth()` is showing up as abstract when it's getting called while the tooltip is being drawn even though it is defined in `IconButton.java`. The error occurs when `SettingsToggleButton.getWidth()` is called on line 181 of `AEBaseScreen.java`. I made multiple attempts to replicate this behavior in a Java test project of my own but failed.

**Comment by shartte** [comment]
I'll check the actual class-file in that release.... It should re-map the name of getWidth to the SRG-name of the baseclass, but if it's complaining about getWidth (verbatim, not the SRG name) it looks like ForgeGradle fucked up the remapping....

**Comment by shartte** [comment]
🤦 Ofcourse this can't work correctly.

We have an interface `ITooltip` with a `getWidth` method, and when we implement this interface in a class that _also_ overrides a base class method called `getWidth`, that method will be remapped by ForgeGradle (correctly) to the SRG name, which means it now implements the interface without actually providing a method with a matching name.
