### ISSUE TITLE
[1.15.2] Items going through formation/annihilation plane

### ISSUE THREAD

**Issue by celestialy** [AppliedEnergistics/Applied-Energistics-2#4551]
Hello,

I'm trying to automate crafting fluix crystals but I've encountered a bug where items go through the formation/annihilation plane.

**Describe the bug**
I've made a setup where redstone, nether quartz and charged certus crystal go through the formation plane in a block of water which then craft them into a fluix crystal and the annihilation plane below the water collects them.
The problem is that either some of the three ingredients go through the annihilation plane (I mean under it, they just fell) or the fluix crystal pops and go through the formation plane (above it).

It's a setup I already made on 1.7.10 which had no issues.

**To Reproduce**
Surround one block of water by dirt or glass on it's 4 side, a formation plane above and an annihilation plane below. Annihilation plane is configured to filter only fluix crystals.

**Expected behavior**
Items should not go through the planes. They should stop on the annihilation plane and be fetch by it when the craft is done.

**Additional context**
Video example showing item going through the annihilation plane: https://pinkylily.fr/s/0GiAG9O20B.mp4
Screenshot of the setup: https://pinkylily.fr/s/vHQG56aeTo.png

**Environment**
Running Forge 1.15.2-31.2.31
appliedenergistics2-7.0.0-beta.1

Other mods:
cc-tweaked-1.15.2-1.90.2
CraftTweaker-1.15.2-6.0.0
gravestone-1.17.5
jei-1.15.2-6.0.2.12
journeymap-1.15.2-5.7.0b3
Mekanism-1.15.2-9.10.9.422
MekanismGenerators-1.15.2-9.10.9.422
MekanismTools-1.15.2-9.10.9.422
preview_OptiFine_1.15.2_HD_U_G1_pre30

Thanks for your help!

**Comment by shartte** [comment]
Couldn't you have made that screenshot at daytime, I can barely see anything :-P

**Comment by celestialy** [comment]
@shartte Haha I'm sorry, there you go 😄 https://pinkylily.fr/s/vD0abB7oCl.png

**Comment by shartte** [comment]
You do realize that there's a gap around the plane when you don't put a facade on it? :-P

**Comment by celestialy** [comment]
I didn't know you could put a facade under the annihilation plane to prevent this! Thank you 😄

**Comment by shartte** [comment]
@celestialy You'll not need to put the facade on anymore after the updates we released yesterday.
