### ISSUE TITLE
Quartz dust as forge quartz dust

### ISSUE THREAD

**Issue by chidori** [AppliedEnergistics/Applied-Energistics-2#4560]
Looks like nether quartz dust is not considered as forge:dusts. It's little bit frustrating when you can not use quartz dust from other mods (eg Mekanism) trying to smelt it into silicon.

**Reasons why it should be considered**
Since AE2 can obtain quartz dust only in grinder - it's a pain.

Issued in appliedenergistics2-7.0.0-beta.1.jar

**Comment by chidori** [comment]
Accidentally closed the issue :(
As temp fix this for this, have added **forge:dusts/quartz** as ingredient in data/appliedenergistics2/recipes/smelting/silicon.json.
Waiting for the official update.
Thank you.

**Comment by shartte** [comment]
We'll leave this to modpack authors. I have no idea how common or uncommon Mekanism quartz is and if its a good fit or not.

**Comment by chidori** [comment]
@shartte 
> We'll leave this to modpack authors. I have no idea how common or uncommon Mekanism quartz is and if its a good fit or not.

It's not about Mekanism.
You have added nether quartz dust - an item which obtained through grinder from the minecraft's nether quartz.
Another mod authors can do the same thing - add processing of the original resources to dusts, so it is only about forge recommendations - to make such things in tag domain of forge (in our case **forge:dusts**).
https://mcforge.readthedocs.io/en/latest/utilities/tags/#conventions

My point is that Grinder - just make dust (eg iron dust from iron), do not add some magic, to make quartz dust special - to not become common quartz dust, to make silicon from.

I just suggest to add into silicon recipe a forge common domain tag **forge:dusts/quartz** to make silicon recipe universal for all authors who somehow make nether quartz dust.

All is need - to update recipe to accept forge:dusts/quartz, so the other mod authors if the implement obtaining of quartz dust - it will be OK to make the silicon from them.
```
{
  "type": "minecraft:smelting",
  "result": {
    "item": "appliedenergistics2:silicon"
  },
  "ingredient": [
    {
      "tag": "appliedenergistics2:dusts/nether_quartz"
    },
    {
      "tag": "forge:dusts/quartz"
    },
    {
      "tag": "appliedenergistics2:dusts/certus_quartz"
    }
  ],
  "experience": 0.0
}
```

If I still don't convinced you, can I manually update a mod to play in my single worlds?

**Comment by yueh** [comment]
There is simply no `forge:dusts/quartz` tag we could use. And if you would have read the conventions you linked, than you would know that mods should not pollute the forge domain on their own but make a PR for it to add a new one instead.

So if you consider it is a worthwile contribution to forge to add a tag for quartz dust, feel free to submit a PR and once that is actually available, we can consider using it. Which might depend on various conditions like in case some mod adds a recipe for `1 quartz -> 2 dusts` it might break our own doubling and create an infinite loop for quartz or quartz dust.

For now we provide our own tags within our domain for anyone to use as additional option.

**Comment by chidori** [comment]
@yueh Ok, reasonable.
Then I dive deeper in that topic.

**Comment by XFactHD** [comment]
@yueh You should not pollute the Forge domain with new groups but if there is a group for this already (forge:dusts), then you should add to it. This is supported by the examples of brass ingots and cobalt nuggets in the migration section.

**Comment by shartte** [comment]
Ooooooooh I thought this was about certus quartz. Yeah we can do that.

**Comment by yueh** [comment]
They call tags groups and state that you shouldn't add groups below `forge`. Either they need to fix their useless docs and state what they want exactly or just remove them and let anyone do what they want and then try and cleanup it later somehow between mods.

**Comment by chidori** [comment]
@shartte also, shaped recipes such as quartz glass
