### ISSUE TITLE
Me Network shutting down when controller multiblock in 2 ore more chunks

### ISSUE THREAD

**Issue by Dr-Zoidberg-de** [AppliedEnergistics/Applied-Energistics-2#4566]
ME Networks shuts off for a second whenever someone enters the Chunk/s with the ME Controller, IF the COntroller multiblock stretches over several Chunks

**To Reproduce:**
Place a ME Multiblock Controller (7*7**7 in my case) in Multiple Chunks (mine is cut in the exact Center by 4 chunks)
connect a Crafting cpu into an adjacent chunk to the controller and connect them
leave and/or enter the controler and crafting cpu chunk
observer the controller turning off the exact moment a player crosses chunkborders
edit: only occurs when in addition to the above mentioned, several p2p connectors are connected to the controller (input side to another net)

**Expected behavior**
no shutdown

**Enviroment:**
Minecraft 1.12.2
Project Ozone 3 -3.3.59
appliedenergistics2-rv6-stable-7.jar
ae2stuff-0.7.0.4-mc1.12.2.jar 
WirelessInterfaceTerminal-1.12.2-1.0.2.jar 
AE2WTLib-1.12.2-1.0.34.jar

forge-14.23.5.2847

**Comment by shartte** [comment]
Hi there. Sorry, but we're not supporting any version older than 1.15 at the moment.
