### ISSUE TITLE
Molecular Assembler Texture error - MC 1.16.1

### ISSUE THREAD

**Issue by sagesse-cn** [AppliedEnergistics/Applied-Energistics-2#4575]
The Molecular Assembler Texture show error and flashing.
<img width="854" alt="image" src="https://user-images.githubusercontent.com/6903353/89715315-64c43e00-d9d7-11ea-9bff-419eb998aeb4.png">

**To Reproduce**

In the new world places a Molecular Assembler.

**Environment**

1.16.1-forge-32.0.105
appliedenergistics2-8.0.0-alpha.2

<img width="854" alt="image" src="https://user-images.githubusercontent.com/6903353/89715450-31ce7a00-d9d8-11ea-8c28-c0ea49e9d4f8.png">

**Comment by Pingger** [comment]
In the first screenshot I can see a minimap. 
What other mods do you have installed? 
By any chance the current beta release of Optifine (OptiFine_1.16.1_HD_U_G2)?
If you do have it installed, do you mind trying again without OptiFine please?

**Comment by shartte** [comment]
If he had optifine, you'd see it in the upper left corner of the debug screen.

I think this is a texture loading issue in the MAC TESR. Easy enough to fix.

**Comment by sagesse-cn** [comment]
> In the first screenshot I can see a minimap.
> What other mods do you have installed?
> By any chance the current beta release of Optifine (OptiFine_1.16.1_HD_U_G2)?
> If you do have it installed, do you mind trying again without OptiFine please?

I've tried to leave only AE2 and JEI, and the problem is the same.

**Comment by shartte** [comment]
Turns out this was a semi-forge bug. They had fixed it a few days ago, and we just applied the fix and moved some code around 👍
