### ISSUE TITLE
Interaction problem with EnderIO : ItemConduits vs ME Interface

### ISSUE THREAD

**Issue by thatsIch** [AppliedEnergistics/Applied-Energistics-2#458]
if an ItemConduit pushes an item into the ME Interface, it could be drawn technically at the same time. Generally it should be their bug, but we can handle it better, since this would happen with any item transport system which pulls and pushes from the same side.

**Comment by agowa338** [comment]
I'm not sure, if this is the same issue, but if I attach EnderIO ItemConduits to my ME Interface, it sometimes happens, that a Item lands in the wrong slot and doesn't get pulled out of it.
In this example the empty syringes.
![image](https://cloud.githubusercontent.com/assets/2544867/7047241/a0a3d4d0-de0b-11e4-8340-a5f5251a0e5a.png)
(Playing on latest 1.2.1 Direwolf20 mod pack)
