### ISSUE TITLE
Autocraft ME Quantum Ring not working. Add Energy Cell distinguish in CPU

### ISSUE THREAD

**Issue by Trackhe** [AppliedEnergistics/Applied-Energistics-2#4581]
I cant autocraft ME Quantum Ring because the ME System don`t use the Energy Cell with 0% AE only the Energy Cell with 100% AE should work with the Molekular Assembler. but the ME CPU cant distinguish.

**Describe the feature**
distinguish the Cells of AE2

**Reasons why it should be considered**
because to make it possible to autocraft ME Quantum Ring

**Additional Context**
On version. 
AE2: rv6-stable-7
MC: 1.12.2

**Comment by shartte** [comment]
Sorry, we are no longer supporting versions of AE2 prior to 1.15.
