### ISSUE TITLE
applied energistics 2 (appliedendergistics2) encountered an error during the sided_setup event phase

### ISSUE THREAD

**Issue by clericcraft** [AppliedEnergistics/Applied-Energistics-2#4582]
**Describe the issue**
Hello! I am attempting to create a custom mod pack in 1.16.1. When adding AE2 to the pack on a server level it pauses the startup without a solution. When starting in MultiMC it launches Minecraft with the above error listed.
The log of this startup can be found here [https://paste.ee/p/ePfEf](url)
Nothing actually Crashes, but the game is not playable, and the server does not start.

**Comment by kellixon** [comment]
The same error, we will wait for new versions.

**Comment by yueh** [comment]
Forge did a breaking change and as usual not with a way for us to prepare for it and mark AE2 as incompatible with it to give better feedback to players. Something which should be possible for a professional project.

So either downgrade Forge. I think .106 should work, but the save option is to choose .93, which we currently compile against.
Or alternatively wait for us to update, probably with the next build. But no ETA.

**Comment by shartte** [comment]
Yes, the change in 107 exposes an actual issue, but does so by breaking a bunch of stuff.
https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.1-32.0.108/forge-1.16.1-32.0.108-changelog.txt
