### ISSUE TITLE
The generated fluix crystals will be ejected out of other region - MC 1.16.1

### ISSUE THREAD

**Issue by sagesse-cn** [AppliedEnergistics/Applied-Energistics-2#4583]
**Describe the bug**

I have a device to automatically generate `Fluix Crystals`. 
up side place `ME Formation Plane`, down side place `ME Annihilation Plane`,  other sides place `Crystal Growth Accelerator`.
In the old version everything is normal, but in the new version of the generated fluix crystals will be ejected out of the region.
I tried to put some `Cable Facade` place in the up and down side to block it from eject, but not working.
![image](https://user-images.githubusercontent.com/6903353/89755082-c89e5200-db10-11ea-993e-edce73112a8e.png)

**To Reproduce**

In the new world up side place `ME Formation Plane`, down side place `ME Annihilation Plane`,  other sides place `Crystal Growth Accelerator`.
Then create the processing repice and use it

**Environment**

1.16.1-forge-32.0.105
appliedenergistics2-8.0.0-alpha.2
<img width="854" alt="image" src="https://user-images.githubusercontent.com/6903353/89755247-524e1f80-db11-11ea-8450-dc1306e86f92.png">

**Comment by yueh** [comment]
Keep in mind the water physics in minecraft did change. Thus it might need new approaches.

**Comment by sagesse-cn** [comment]
> Keep in mind the water physics in minecraft did change. Thus it might need new approaches.

This commit does not have much effect, I using the buoyancy of the water to solved the problem, by place the `ME Annihilation Plane` on the up side, place the `ME Formation Plane` on the down side.

**Comment by have-a-boy** [comment]
I'm currently trying to find a working setup for 1.16 that doesn't eject half of the crystals in a way that leaves them undetectable by the annihilation plane. An extra gap above the water will stop them from landing atop the formation plane, but unfortunately they can still float on top of the water surface with the new item water physics. Somehow this causes the annihilation plane to be unable to detect them. Maybe the items are actually in the block above the water line? Crystal setups are like 50% lossy as is though lol.

**Comment by shartte** [comment]
Make sure you are on the latest version, there were some fixes to annihilation plane bounding boxes and fluid crystal reactions.

**Comment by sagesse-cn** [comment]
> I'm currently trying to find a working setup for 1.16 that doesn't eject half of the crystals in a way that leaves them undetectable by the annihilation plane. An extra gap above the water will stop them from landing atop the formation plane, but unfortunately they can still float on top of the water surface with the new item water physics. Somehow this causes the annihilation plane to be unable to detect them. Maybe the items are actually in the block above the water line? Crystal setups are like 50% lossy as is though lol.

Although the swapn area is reduced, it still floats on the surface,a new solution is to Annihilation Plane place in top side.

**Comment by have-a-boy** [comment]
@sagesse-cn Thank you for the advice. I will try that with the newest release.
