### ISSUE TITLE
Many block can't using Wrench to the drop - MC 1.16.1

### ISSUE THREAD

**Issue by sagesse-cn** [AppliedEnergistics/Applied-Energistics-2#4584]
**Describe the bug**

Many block (example: ME interface, ME Drive, Charger ...) can't using `Wrench` + `Shift` + `Mouse right click` to the drop.
<img width="854" alt="image" src="https://user-images.githubusercontent.com/6903353/89756897-4f096280-db16-11ea-9244-0b5d30d9bda3.png">

**To Reproduce**

In the new world place a ME Interface, using wrench to operate.

**Environment**

1.16.1-forge-32.0.105
appliedenergistics2-8.0.0-alpha.2
<img width="854" alt="image" src="https://user-images.githubusercontent.com/6903353/89757159-0c945580-db17-11ea-9517-ba0f2b4ec4e5.png">

**Comment by sagesse-cn** [comment]
This a feature or bug or can’t reproduce?

@yueh

**Comment by shartte** [comment]
This is still under investigation, it was just low priority so far.
