### ISSUE TITLE
Cable Facade Issue - MC 1.16.1

### ISSUE THREAD

**Issue by SAGESSE-CN** [AppliedEnergistics/Applied-Energistics-2#4585]
**Describe the bug**

1. The GUI for 'ME Formation Plane' could not be opened from back side when `ME Formation Plane` decorated by `Cable Facade`
2. If some plane decorated by `Cable Facade`(with all sides masking), using `Wrench` + `Mouse right click` will drop the plane.

**To Reproduce**

1. In the new world place a 'ME Formation Plane' then decorated by `Cable Facade`, Open the GUI for `ME Formation Plane ` in the back side.
2. In the new world place a 'ME Formation Plane' then decorated by `Cable Facade`, using `Wrench` to operat.

**Environment**

<img width="854" alt="image" src="https://user-images.githubusercontent.com/6903353/89758012-5f6f0c80-db19-11ea-8b5b-a18ecb153292.png">
<img width="854" alt="image" src="https://user-images.githubusercontent.com/6903353/89758743-15872600-db1b-11ea-941c-44d76c333dc4.png">

**Comment by shartte** [comment]
Thanks for reporting. I noticed something similar but couldn't reproduce it.

We did change the collision box for facades to be larger than the visual box to improve item entities clipping through facades. Will investigate further...

**Comment by sagesse-cn** [comment]
> Thanks for reporting. I noticed something similar but couldn't reproduce it.
> 
> We did change the collision box for facades to be larger than the visual box to improve item entities clipping through facades. Will investigate further...

I wanted to see if the master code had this problem, but there was an error:
> Invalid patcher dependency: net.minecraftforge:forge:1.16.1-32.0.108:userdev

**Comment by sagesse-cn** [comment]
> Thanks for reporting. I noticed something similar but couldn't reproduce it.
> 
> We did change the collision box for facades to be larger than the visual box to improve item entities clipping through facades. Will investigate further...

In master code, problems remain.
