### ISSUE TITLE
Server Crazy Spam

### ISSUE THREAD

**Issue by SamLam140330** [AppliedEnergistics/Applied-Energistics-2#4593]
**Describe the bug**
When player use auto craft, the server console will crazy spam warning!

**To Reproduce**
When player use auto craft

**Expected behavior**
No any warn spam in my console

**Additional context**
Part of server log: https://pastebin.com/bSenAcAv

**Environment**
Forge - 14.23.5.2854
Applied Energistics2 - appliedenergistics2-rv6-stable-7.jar
AE2 Stuff - ae2stuff-0.7.0.4-mc1.12.2.jar
AE2 WIreless Terminal Library - AE2WTLib-1.12.2-1.0.34.jar
Wireless Crafting Terminal - WirelessCraftingTerminal-1.12.2-3.12.97.jar

**Comment by Ommina** [comment]
#3822 and lots others.

**Comment by Pingger** [comment]
Basically caused by Mods, that implement their own Crafting Handler, that does not work like the Forge one. AE2 is programmed with the Forge one in mind. 
In your case Mekanism is the Mod causing the issues with the Crafting.

**Comment by shartte** [comment]
We also don't (sadly) support any version prior to 1.15 anymore due to time constraints. Sorry!
