### ISSUE TITLE
Import Export Buses Limited or Stop Working

### ISSUE THREAD

**Issue by kevupton** [AppliedEnergistics/Applied-Energistics-2#4594]
Not sure how i can easily reproduce, but to me it seems like the behaviour on a large network with lots of import and export buses.
However, basically it seems that they suddenly stop working and in random order. I have a bunch of autocrafting export buses, and one main import bus on a chest. And the import bus randomly stops working. It seems to lag and slow down as if it can only import so many or export so many at a time. 
I have checked the network, and it has plenty of power, with a dense battery cell, and hooked up to a draconic energy storage. SO input energy is no problem. The main import bus has at least 20 free connections available on the dense cable, and 6 free on the normal cable. 
So it is not a connection problem either.
The only way to get it working again is to re-attach the import bus. or disconnect the cable and attach it again. However it seems some import bus somewhere else stops working. It seems to be consistent behaviour. no matter what. Just give it enough time and it will stop working. It is chunk loaded with standard world spike and all the setup is inside just one chunk.
So it is not power, it is not connections, it is not chunk loading. It legitimately looks as if the network has a maximum amount of input and export buses that can be running at any point in time. And while one is running or trying to run another cannot run, which seems to just halt everything.

Environment: https://www.curseforge.com/minecraft/modpacks/infinityevolved-reloaded

AE2 version: 
appliedenergistics2-rv6-stable-7.jar

Other tickets similar:
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2983
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1010

Upper core area. (has some dense energy cells above).
![image](https://user-images.githubusercontent.com/2093615/90208762-e7f8f000-de2c-11ea-8e00-eb123ab30cc4.png)

This is the main one that stops working and clogs up the whole system...
![image](https://user-images.githubusercontent.com/2093615/90208810-0fe85380-de2d-11ea-9461-fdf2a1fbee93.png)

Power to main network:
![image](https://user-images.githubusercontent.com/2093615/90208903-5342c200-de2d-11ea-9608-8ecc9a62d635.png)

**Comment by shartte** [comment]
Sorry, we don't (sadly) support any version prior to 1.15 anymore due to time constraints. Sorry!

**Comment by mindforger** [comment]
busses have tick limiter functions but total stopping sounds unrelated to this function
do you have 39 storage busses in your system? to what are they attached?

**Comment by kevupton** [comment]
So this should be fixed if I update to the latest version?

**Comment by kevupton** [comment]
@mindforger those are 39 interfaces :D

**Comment by mindforger** [comment]
I always mix them up

I just wanted to know how you are storing items, as your storage busses can be an issue.

**Comment by kevupton** [comment]
@mindforger i did think maybe it was storage buses. Because I had a cache system, however trying to fix this I completely detached the cache, and was just having me drives with a bunch of cards. I had about 8 drives with 6 filled with storage cards.

**Comment by mindforger** [comment]
okay that rules out the storage busses, i tried to recreate this with no luck, only thing i had as a known issue were storage busses on otehr storage mods, causing a cascade of checks when trying to insert stuff into the network

**Comment by kevupton** [comment]
one other thing maybe is im using a bunch of ender chests, which is my main method if importing items into the system. and so i have about 48 export busess pointing into the same ender chest for auto crafting? then on the same ender chest i have an import bus? could this be anything? The same ender chest also receives ores and drops from monsters, so fills up really quite fast.

**Comment by mindforger** [comment]
sounds possible at least, but how does one attach 48 import busses to the same 1x1x1 block with only 6 sides ? sounds like there is something in between that also may cause this!? can you try to rule it out temporary by adding a buffer chest between the export bus and the ender chest?
