### ISSUE TITLE
After crafting items disappear

### ISSUE THREAD

**Issue by Raam337** [AppliedEnergistics/Applied-Energistics-2#4596]
**Describe the bug**

After ordering a recipe items start to disappear.

Playing Omnifactory modpack. AE2 version rv6 stable 7, https://www.curseforge.com/minecraft/modpacks/omnifactory

Also, I am sure that nothing is being exported out of the system.

**Additional context**

[mc_bug (1).zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5074083/mc_bug.1.zip) video describing the problem

**Environment**

[crash-2020-08-14_13.39.13-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5074130/crash-2020-08-14_13.39.13-client.txt)

**Comment by mindforger** [comment]
please use pastebin(for logs), youtube or any other platform to share videos and logfiles

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.15 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
