### ISSUE TITLE
import/export buses not doing their job

### ISSUE THREAD

**Issue by katanush** [AppliedEnergistics/Applied-Energistics-2#4597]
**Describe the bug**
so after i placed an import bus it imported few items and than stopped. to make it work again i have to break it and place it again but the thing is i do have a lot of them not only 1. so i cant use any kind of auto crafting as it is not importing anything unless i break and place them back 
i do have a big system but that should not be the issue ? is there a limit of how many channels i can have  like max 100 ? if it is than why we can make a big controller for more channels if we cant even use them ?

there is enough power provided . is nothing about chunk loading as i am right there.

version used : 
rv6.stable 7

**To Reproduce**
u do not have to reproduce as i can provide the map if i am allowed to and coords as i am playing on a server . 

http://modscraft.eu/ozone_world.zip

coords for my overworld base: x:-11480 z:66968 y:85 
under the me terminal there is the teleporter for rf dimension where the main me system is and all the import/export buses are not working. 

**Expected behavior**
i do expect for the import bus to import all the items into me system and for the export bus to export the items ?

There been similar issues  : 
#4311 
#4594 
#4249 
 
- Environment:  Project ozone 3 , 3.3.59v , rf dimensions , appliedenergistics2-rv6-stable-7

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.15 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.

**Comment by mindforger** [comment]
since you noted those other issues, could YOU give me an answer please? how do you store things? maybe the way you store things in your system is causing the delay?

**Comment by katanush** [comment]
storage is with yabba barrels and drives. everything that i import into the system goes into drives . in yabba barrels i have only mystical agriculture essence which is going in with itemducts .

**Comment by mindforger** [comment]
ah okay, make sure you set a filter for each bus attached to a barrel, that should help with performance

**Comment by katanush** [comment]
no no , for the barrels i have a connector and i have a storage buss on the barrel connector . but as i said the barrels are only for essence . so what ever i m trying to import into the system is going into me drives . still the imports are not working . if i m using less imports than it will start working but seems liked dev dont even care about that problem as i m not the only one reporting it  :))

**Comment by mindforger** [comment]
Having an unconfigured storage bus on a limited storage is not good because the system tries to store items there and the code path for checking of the attached storage may cause high load (even item loss with DSUs), you can relieve it by configuring the storage busses

**Comment by Tahakk** [comment]
In later stages I would recommend making big amount of ME Storage Cells and dump all the barrel items into them. I went from like 10 seconds waiting queue to instant. 

Also using exporters with Crafting Cards when you have your barrels connected to the system will most likely kill the whole server, use those ONLY when you have your items on the Disks.

As far as number of channels goes, you have unlimited, it just depends on your controller setup and channel structure.
