### ISSUE TITLE
Villager

### ISSUE THREAD

**Issue by AlgorithmX2** [AppliedEnergistics/Applied-Energistics-2#46]
Maybe we could add an option to allow players to switch Meteorite/Sky Stone Chest to Villagers.
OR
Introduce a Villager to trade with to get rid of excess plates or acquire missing plates.  At a cost of course

Originally Posted by BJR1984

This issue was migrated; For original details see http://ae-mod.info/Tracker/0407/

**Comment by Technici4n** [comment]
Closing in favor of #5302.
