### ISSUE TITLE
Storage bus won't move already stored items

### ISSUE THREAD

**Issue by tiennou** [AppliedEnergistics/Applied-Energistics-2#460]
I'm trying to setup one of those Deep Storage Unit Rooms so that my network doesn't get filled with 2M+ cobblestone/dirt/whatever. It seems that the storage bus doesn't try to get items that are already stored — items that are _new_ to the network get correctly routed, but items already in a drive somewhere won't move. Right now, even though the cobblestone Storage Monitors displays 3M, there's only 1,7M items in its DSU. Maybe I'm doing something wrong, but I seem to remember AE1 was correctly detecting the preferred storage on the Network and move the items there by itself. A "workaround" I've found is if I remove a stack of items and put them back in, they get stored in the corresponding DSU (but 3M cobblestone is 50K mouse clicks so, no :laughing:).

My actual setup is 1) my main AE network (where items enter the Network) 2) a bi-directional Interface-Storage Bus subnetwork where the DSUs are located. The main → storage Storage Bus has been set to priority +1000 because I want it to be considered first. I've also tried with the same +1000 Storage Bus/DSU on the main Network, to no avail.

DNS Techpack 7.5.2 / ae2-rv1-stable-1.

**Comment by Blue64** [comment]
Or hook it up to a Hopper and let it do your heavy lifting as you sift through the 50k stacks into a new chest. The export bus sounds by far faster though, just remember to add somewhere for the OTHER stuff to go (like dyes) first, otherwise you'll be pulling those out of your DSU's xD

**Comment by thatsIch** [comment]
Stop necroing please, this issue is over 1 year old.
