### ISSUE TITLE
Fabric 1.16.2 GenerationSettingsAccessor mixin & mod compatibility

### ISSUE THREAD

**Issue by Katorone** [AppliedEnergistics/Applied-Energistics-2#4600]
Overwriting a method can be bad for mod compatibility.  There might be another way to get the same result while remaining compatible.

**Describe the bug**

`Method overwrite conflict for setFeatures in appliedenergistics2.mixins.json:structure.GenerationSettingsAccessor, previously written by slexom.earthtojava.mobs.mixins.MixinGenerationSettings. Skipping method.`

Two mods are trying to overwrite the same method, causing incompatibility.  I'm reporting this to the earth2java git as well.

**To Reproduce**
Install AE2 and earth2java
https://www.curseforge.com/minecraft/mc-mods/earth2java-fabric/files/3031517

**Expected behavior**

Mod compatibility.

**Environment**

- Environment: 
Debian, minecraft 1.16.2, fabric@0.18.0+build.397-1.16, earthtojavamobs@1.2.0+1.16.2, appliedenergistics2@8.1.0-alpha.1

**Comment by shartte** [comment]
I think this is on their end. They add methods to the class without making the method names unique.
We're using an accessor mixin of which one can have multiple copies using the same name usually.

**Comment by Katorone** [comment]
Thank you for your reply and for weighing in on the bug report at earth2java's repo.
