### ISSUE TITLE
Invalid pattern? causes crash to desktop

### ISSUE THREAD

**Issue by Krutontar** [AppliedEnergistics/Applied-Energistics-2#4602]
1.16.1
8.0.0alpha3  beta 1 also, but maybe the item in my inventory is corrupt.
Forge 32.0.108

java.lang.IllegalStateException: No pattern here!

**To Reproduce**
I created a pattern for quartz glass(certus dust version).  The pattern terminal was left in machine mode and the second my mouse touches the pattern in my inventory, I crash to desktop.  I have re-created the pattern in regular crafting mode and it works.  I don't really want to try it again because I can't seem to remove it from my inventory no matter what I try.
Tested with and without extended tooltips.

Update:  Now it crashes just by opening my inventory.  I was able to finally get it out by swapping with another item and tossing it into the world.  I tested the original cause again in beta1 and it still happens.

Crashlog:  https://pastebin.com/kTXjUan1

**Comment by Tatters1526** [comment]
im having the same issues

**Comment by shartte** [comment]
I finallly managed to reproduce this. For me this only occurs when clearing the output of the processing pattern and there's an otherwise encoded pattern in the slot. I'll check this.
