### ISSUE TITLE
Server Boot Crash 1.12.2 

### ISSUE THREAD

**Issue by YOYOK9** [AppliedEnergistics/Applied-Energistics-2#4604]
Originally thought this to be a Spongeforge issue (talked with yueh & Gimpansor on discord) BUT it seems to be an issue with AE2 itself or at least that's where it errors at. I have Removed spongeforge and all its little plugins and still receiving the same style of crash on boot. 

**Describe the issue**
Crash on server boot, 

However client side works perfectly fine with no issues, which is what the server has been copied from (mods,configs and scripts)

'Caught exception from Applied Energistics 2 (appliedenergistics2)
Caused by: java.lang.NoSuchFieldError: TEX'

AE2: appliedenergistics2-rv6-stable-7
Forge both client & server: forge-14.23.5.2854
MC: 1.12.2

**Environment**
Server reports:
Crash report: https://pastebin.com/v3Ds5mVZ

Other logs if useful:
Latest Log: https://gist.github.com/YOYOK9/a3d1e4613abbe4b69f28f00cddb86a1b
Debug log: https://gist.github.com/YOYOK9/8d1bccae00d5cc46056183b662d9608a

Extra stuff: 
Client and server are basically the same aside from some client side only mods removed from the server. Can provide mod lists if required.

**Comment by YOYOK9** [comment]
Update: I removed  Restonecontrol and its core CD4017BE_lib and it seemed to fix the boot issue. However I tried the 2 mods alone with ae2 and it booted no problems.

**Comment by Ommina** [comment]
It is happening inside a private static method of cd4017be.lib -- AE2 is not the cause, only, in this case, the trigger.

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.15 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
