### ISSUE TITLE
Add 8.0.0 Maven support

### ISSUE THREAD

**Issue by sagesse-cn** [AppliedEnergistics/Applied-Energistics-2#4605]
**Describe the feature**
Some mod authors require Integration 8.0.0 Maven support.
https://github.com/mekanism/Mekanism/issues/6479#issuecomment-674617149

**Comment by yueh** [comment]
For now, we provide a maven repo through github packages, which is sufficiently documented by github on how to use and works fine as basic maven. Maybe a bit inconvenient currently, but github is also looking for feedback and suggestions on how to improve it further. In case they are missing something.

**Comment by sagesse-cn** [comment]
> Maven
> 
> We use Github Packages as maven repository now. You can use the following snippet as example on how to add a repository to your gradle build file.
> 
> repositories {
>     maven {
>         name "AE2"
>         url "https://maven.pkg.github.com/AppliedEnergistics/Applied-Energistics-2"
>     }
> }
> When compiling against the AE2 API you can use gradle dependencies, just add
> 
> dependencies {
>     compileOnly "appeng:appliedenergistics2:VERSION:api"
> }
> or add the compileOnly line to your existing dependencies task to your build.gradle.
>
I tried using AE2 API maven config by the README, but it didn't build.

**Comment by sagesse-cn** [comment]
> For now, we provide a maven repo through github packages, which is sufficiently documented by github on how to use and works fine as basic maven. Maybe a bit inconvenient currently, but github is also looking for feedback and suggestions on how to improve it further. In case they are missing something.

Can provide a working example? THX

**Comment by yueh** [comment]
Please refer to https://docs.github.com/en/packages, there a multiple use cases and we cannot provide an example for every one. 

Our docs assume you are familiar with github packages and just adds the details explicitly needed for AE2. Omitting the common github packages details found in their docs. As these are a way more comprehensive.

**Comment by sagesse-cn** [comment]
@yueh The AE2 has any mirrored to another without token then maven plans？

**Comment by shartte** [comment]
@sagesse-cn Yes, we're also going to upload to Modmaven and will update the README accordingly.

**Comment by sagesse-cn** [comment]
> @sagesse-cn Yes, we're also going to upload to Modmaven and will update the README accordingly.

That's great. When do your usually upload?

**Comment by shartte** [comment]
When there's a release? :-P
