### ISSUE TITLE
missing textures

### ISSUE THREAD

**Issue by wanderingmage** [AppliedEnergistics/Applied-Energistics-2#4606]
Minecraft 1.16.1
Forge 32.0.108

Applied Energistics 2 8.0.0 Beta 1
![2020-08-17_11 46 21](https://user-images.githubusercontent.com/26194881/90421665-63ea7680-e07f-11ea-90ce-c8a59a76850d.png)
![2020-08-17_11 46 24](https://user-images.githubusercontent.com/26194881/90421682-68af2a80-e07f-11ea-9189-89a6d5f8d70e.png)

**Comment by yueh** [comment]
Please refer to the issues template displayed to you while opening this issues and add the missing information.

**Comment by DeadlyLazy** [comment]
I've seen similar issues with Mekanism when Optifine is installed, can you remove it for me and reply whether it the issue remains? ty

**Comment by wanderingmage** [comment]
OK. looks like it is something to do with the fact that it isn't jiving with the current optifine.

**Comment by shartte** [comment]
Oh yeah, you're going to see some hard crashes too with Optifine :-P

**Comment by sagesse-cn** [comment]
> I've seen similar issues with Mekanism when Optifine is installed, can you remove it for me and reply whether it the issue remains? ty
> 
> EDIT: If it fixes it, the issue is caused by OF being incompatible with the latest versions of forge.

If use OptiFine mod, plase install additional for OptiForge
