### ISSUE TITLE
Fabric 1.16.2 TinyTNT related server-crash

### ISSUE THREAD

**Issue by Katorone** [AppliedEnergistics/Applied-Energistics-2#4611]
Setting off a tinyTNT crashes the server

**Describe the bug**
Setting off a tinyTNT crashes the server

**To Reproduce**
Set off a tinyTNT.

**Expected behavior**
:-)

**Additional context**
Crash log: https://pastebin.com/vaVbjUaG
I'm not sure how useful this is, since it's the resolution of a hang.
The snippet of the actual crash:
https://pastebin.com/uVgm9qnd

**Environment**

- Environment:  Debian, minecraft 1.16.2, fabric@0.18.0+build.397-1.16, appliedenergistics2@8.1.0-alpha.1

**Comment by shartte** [comment]
This problem affects forge too. Client-side only Explosion constructor is being used here.

**Comment by shartte** [comment]
Yes, this method became client-side only in 1.16.1, so 7.0.x is not affected by it.
