### ISSUE TITLE
Optifine Rendering issue

### ISSUE THREAD

**Issue by HiddenGhost121** [AppliedEnergistics/Applied-Energistics-2#4613]
when optifine is install the facades textures turn black and purple using the twitch launcher
**Describe the bug**

Version - appliedenergistics2-8.0.0-beta.1
Optifine - OptiFine_1.16.1_HD_U_G2
**To Reproduce**

install AE2
install optifine
make world
exit world
**Expected behavior**

**Additional context**
https://imgur.com/b7gYK6e

**Environment**

- Environment:

**Comment by yueh** [comment]
Optifine is closed source, so there is no way for us to identify what they might break. You have to report it directly to them.

**Comment by sagesse-cn** [comment]
> when optifine is install the facades textures turn black and purple using the twitch launcher
> **Describe the bug**
> 
> Version - appliedenergistics2-8.0.0-beta.1
> Optifine - OptiFine_1.16.1_HD_U_G2
> **To Reproduce**
> 
> install AE2
> install optifine
> make world
> exit world
> **Expected behavior**
> 
> **Additional context**
> 
> https://imgur.com/b7gYK6e
> **Environment**
> 
> * Environment:

If use OptiFine mod, plase install additional for OptiForge
