### ISSUE TITLE
Select Amount Text Input Enhance

### ISSUE THREAD

**Issue by sagesse-cn** [AppliedEnergistics/Applied-Energistics-2#4614]
**Describe the feature**

Can input number in `Select Amount` is a great design.
But if it only have one digit, can't delete it.
I hope can delete last number and the `next button` set to disable state.
At this time, the value should be regarded as 0, and the number can be increased through the `plus button`.

**Reasons why it should be considered**

Better interaction experience.

**Comment by shartte** [comment]
Fixed now
