### ISSUE TITLE
Remove Tab Keybind

### ISSUE THREAD

**Issue by shartte** [AppliedEnergistics/Applied-Energistics-2#4615]
The Tab keybind should no longer be needed. Minecraft itself hardcodes the use of TAB for iterating through the focus order now.
It also has the side-effect of conflicting on Fabric in such a way that it hides the scoreboard.

**Comment by yueh** [comment]
While minecraft now allows us to cycle between buttons using tab, it does not support using tab to unfocus the search field.

At least there is no obvious way to handle it. Except using something like a fake button, which can act as tab target, but forwards every keypress without handling it. Or a similar approach.

**Comment by shartte** [comment]
Oh this does not necessarily mean we can completely remove any handling code for tab, it is just pointless to keep the keybind since Vanilla **hardcodes** the keycode for tab in all of its handlers.

**Comment by Technici4n** [comment]
Fixed by  #5753.
