### ISSUE TITLE
Storage bus and YABBA barrels autocraft freezes

### ISSUE THREAD

**Issue by ReturnX2** [AppliedEnergistics/Applied-Energistics-2#4620]
**Describe the bug**
Playing modpack Project Ozone 3. I have a ME and it is connected to several storage buses that are connected to barrels from the YABBA mod. After clicking the "next" button when autocrafting any item, the server is freezes for a few seconds.

**To Reproduce**
1. Connect the storage bus to the item barrel connector (Barrels must contain millions of items.)
2. Start autocrafting any item and click on the "next" button
3. The server freezes for a few seconds.

**Expected behavior**
I thought everything would be okay.

**Additional context**
https://gist.github.com/ReturnX2/e3e1cc502d211295d3fae0005a256853

**Environment**

- Minecraft 1.12.2 forge-14.23.5.2847
- appliedenergistics2-rv6-stable-7.jar

_Full list: https://gist.github.com/ReturnX2/b2fe7e7ea9a5d863cba6f8029433b7bf_

**Comment by shartte** [comment]
Sorry, we currently do not support any version older than Minecraft 1.15 anymore.
