### ISSUE TITLE
How do I remove channels? 1.15.2-7.7.0

### ISSUE THREAD

**Issue by FariZTheKiller** [AppliedEnergistics/Applied-Energistics-2#4621]
**Describe the bug**
I looked in the applied energistics configs and couldn't find the disable channels config

**To Reproduce**
check configs and you won't find the disable channel config

**Expected behavior**
Disable Channels

**Additional context**

**Environment**

- Environment:

**Comment by yueh** [comment]
Due to changes in Forge, this is no longer feasible to support.
