### ISSUE TITLE
Many Bugs at Input and Output of Inscriber (Fabric Version)

### ISSUE THREAD

**Issue by yuuuanquuu90** [AppliedEnergistics/Applied-Energistics-2#4632]
**Describe the bug**
1. The input items, in addition to Center Input (B), will be also filled to the Output (D).
2. If for exsample there is a hopper at the bottom, the items in the center input (B) will be exported directly.

**Additional context**
appliedenergistics2-fabric-8.1.0-alpha.3.jar
fabric-loader-1.16.2
fabric-loader-0.9.2-build.206

**Comment by shartte** [comment]
This should be fixed in the next version (alpha.5).
