### ISSUE TITLE
No texture once channel given - MC 1.15.2

### ISSUE THREAD

**Issue by Flexz9** [AppliedEnergistics/Applied-Energistics-2#4634]
**Describe the bug/To Reproduce**
Placing ME controller, ME security terminal, ME wireless access point on an active cable it will turn into no texture after a few seconds.

If placed somewhere not connected it will remain with the correct textures.

After the forced crash (F3+C) it seemed to work, not able to let it break again, however I had this issue over multiple days.

**Expected behavior**
Have an actual texture.

**Additional context**
[https://flexz.stackstorage.com/s/GUrHqR3OBGQZqhFa](https://flexz.stackstorage.com/s/GUrHqR3OBGQZqhFa)

**Comment by shartte** [comment]
BTW: I think this is related to something that Forge changed in 1.16.1
Potentially I can derive a fix from that for this problem.

**Comment by shartte** [comment]
@Flexz9 Can you please report back if 7.0.2 changes the situation for you?

**Comment by Flexz9** [comment]
7.0.3 seems to be fixing it, both single and multiplayer are showing all textures.
