### ISSUE TITLE
Public Crafting Cube renderer

### ISSUE THREAD

**Issue by DAmNRelentless** [AppliedEnergistics/Applied-Energistics-2#4638]
**Describe the feature**
I am currently working on an addon mod for Applied Energistics which adds Crafting Storages with more capacity for v1.12.2 and above.

I got everything working and you can already use the new blocks for the crafting cpus. The only thing that does not work are the textures. The item texture is no problem but since you guys use a custom renderer for the multiblock structure, I have no way to implement that.

The textures are applied here: https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv6-1.12/src/main/java/appeng/client/render/crafting/CraftingCubeModel.java

However I can't override anything because the class is not public. I also tried making an own version of the `CraftingCubeModel.java` but the only use of it is in the `CraftingCubeRendering.java` and that's only used by your API when you register the blocks. Either the `CraftingCubeModel.java` needs to be public or you tell me a different way how to implement the blocks properly without breaking the functionality.

**Reasons why it should be considered**
I don't really understand the point of not making the class public. You can't add new stuff to multiblocks because it uses this custom renderer.
It would make it a lot easier to make this addon and maybe also helps other people in the future.

**Additional Context**
Minecraft 1.12.2
Forge 14.23.5.2847
AE2 rv6-stable-7
![](https://i.imgur.com/Ih20N1w.png)

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.15 at this point.

**Comment by DAmNRelentless** [comment]
It's the same thing for every version, even the newer ones.

**Comment by DAmNRelentless** [comment]
That's the 1.15 branch and it has the same structure. You can't extend that class since it's not public.
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/7.x-1.15/src/main/java/appeng/client/render/crafting/CraftingCubeModel.java

**Comment by yueh** [comment]
Is it part of the `appeng.api` package? If not it's not intended to be used by other mods.
