### ISSUE TITLE
Maven POM-File contains incorrect dependencies

### ISSUE THREAD

**Issue by shartte** [AppliedEnergistics/Applied-Energistics-2#4641]
We need to investigate why the maven pom file for  8.0.0-beta.2 contains references to the remapped forge:
https://modmaven.k-4u.nl/appeng/appliedenergistics2/8.0.0-beta.2/appliedenergistics2-8.0.0-beta.2.pom

**Comment by yueh** [comment]
That is a FG3 feature. I wouldn't consider it a bug as they have not bothered fixing it in over a year.

**Comment by shartte** [comment]
We need to fix it somehow though since it seemingly makes it impossible to use our library.

**Comment by yueh** [comment]
The easiest and probably most reliable would be to recommend using

```gradle
dependencies {
    compileOnly ("appeng:appliedenergistics2:VERSION:api") {
       transitive = false
    }
}
```

This will force gradle to ignore the mapped debs. We could try and strip the debs from the xml. But that is some random string matching and can break down every other FG or Forge release. And I certainly do not want to implement integration tests to ensure some xml file is not broken again.

**Comment by shartte** [comment]
I'll look into it later. I tried using our API on Mekanism to get recipes into their datagen, but they use HWYLA's Maven which breaks things. Alot.
Sadly they're on Gradle 4.10 and cannot filter repositories by group id.
Does the transitive dependency disabling actually work for fg.deobf / in Gradle 4.10?

**Comment by yueh** [comment]
Technically it should. But assuming it is ForgeGradle it will probably only work when `--max-workers` is set to > 1 and it hits the right thread.

**Comment by shartte** [comment]
Solved
