### ISSUE TITLE
Improved portable cells

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#4643]
### More cell types

Analog to 1k, 4k, 16k, and 64k cells add the corresponding portable cell variant.

The capacity should still be half of a normal cell. Therefore more like a 512, 2k, 8k, and 32k portable cell.
Types is something to be considered increasing. E.g. add 9 more types per tier up to 54 max, but must be less than a normal cell.

Large ones could also offer a larger energy storage by using dense energy cells instead of normal ones.

### More utility functions

Mostly what is already mentioned in #33

In summary upgrades to allow

* Restocking the player inventory to always have X stacks/items of something on hand
* Removing excess items, so the 100 stacks of cobble will not clutter the normal inventory

Could use upgrade cards for further use. E.g. capacity cards to allow more items to be stocked or acceleration cards to speed up how fast something is restocked or stored away.

### ~~ME Docking Station~~

Similar to how drives or chests already work with portable cells, but allowing the network to restock/empty the portable cell according to some configuration.

This would be highly tentative as it covers similar functionality like drives/chests, io ports, and interfaces. Which would need further balancing. E.g. not making the content available to the network or similar.

Also potentially a large internal API break as formatting currently works around a simple blacklist or whitelist. For a useful way to store bulk items and then only export these later, it would need something like a prefered/unwanted list, which still allows these items to be inserted, but handled differently in other cases.

**Edit**: Probably better handled with allow cell workbenches to set an amount and use IO Ports to fill it

### Portable fluid cell (?)

Would only be of limited use and also somewhat tedious to use as interacting with fluids would still require some fluid container like a bucket.

The only useful function I could currently see is some sort of bucket with a higher capacity and a way to select which fluid should be placed. Assumimg it is actually a placable fluid.

### Progress

- [X] More types
- [x] More utility functions
- [ ] ~~ME Docking Station~~
- [x] Portable fluid cell

**Comment by shartte** [comment]
:-O

**Comment by shartte** [comment]
Ooops misclick.

**Comment by sagesse-cn** [comment]
I should really needed this enhanced🤩

**Comment by Tomodachi94** [comment]
Yes, this is a great idea! +1

**Comment by mindforger** [comment]
add filterable auto pickup feature like mining backpacks, additionally to the „Dev/cell“ function

**Comment by andrewsf** [comment]
Is this complete as of 3f726d1a? You can [reference the issue in the PR or the commit msg](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) to link it up and even auto-close the issue.

**Comment by Tomodachi94** [comment]
Looks like it, @andrewsf

**Comment by yueh** [comment]
Utility functions will be postponed without any ETA for now, except someone wants to take it on with a PR.

Portable fluids cells will hopefully be added with 8.4.x

**Comment by shartte** [comment]
Done
