### ISSUE TITLE
Problem with Fluid input-bus

### ISSUE THREAD

**Issue by DoremySwee** [AppliedEnergistics/Applied-Energistics-2#4645]
I don't know weather I should call it a bug or a feature request......
And the problem is found in 1.12.2, I suppose it may also occurs in the higher edition. So I reported this.
It's related with AE2, ExU2 and CrT. 

What happened?
![image](https://user-images.githubusercontent.com/66953201/91272055-b9283580-e7ad-11ea-84b9-1d3bc24c70cf.png)
   I used fluid storage bus at a custom machine(made by ExU2 and CrT), and I used fluid input-bus to input water into the machine, but it doesn't work.
   When I used other equipment such as ME-IO Port, ME Fluid Interface, or ME Fluid Terminal, I successfully input water.
   It doesn't occur when I'm dealing with items.
![image](https://user-images.githubusercontent.com/66953201/91272205-f7255980-e7ad-11ea-9326-90618b116a0b.png)
   On the other hand, everything is right when I'm dealing with other machines or tanks. But I don't think that's the only sample.

Why I'm reporting this to AE2?
   I guess there must be something wrong with fluid input-bus because it didn't behave as other equipment.

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.15 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
