### ISSUE TITLE
Incorrect config file on server start - Forge 1.15.2 v 31.2.33 - AE2 v 2-7.0.1

### ISSUE THREAD

**Issue by Shtreudel** [AppliedEnergistics/Applied-Energistics-2#4646]
I looked through the issues page and did several google searches but couldn't really find an answer on this.

I have been trying to change the default meteor and quartz generation to use an alternate dimension. After a lot of testing I started to notice that regardless of what I changed in the config file I was always met with 

"[Server thread/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Configuration file (path_to_server_directory...)/test_modpack_with_custom_gen/config/appliedenergistics2-common.toml is not correct. Correcting"

I assumed it was just changing the config back to default values and continuing - which seemed right since my overworld would always spawn meteors even though I specifically tried to configure the whitelist to only spawn in a modded dimension. Even when I disabled meteor spawning in the config I was still seeing meteors in my overworld.

I thought maybe I accidentally messed up the config file with a fat fingered deletion of a letter or line somewhere... so I removed the config file and let it re-create the file in whatever default state. I was still met with the above error in my logs at startup. I made no change to the file. It's literally the config file the mod generates. So this led me to believe that no matter what change I made to the file, I would never be able to alter the meteor or quartz generation because it will continue to find fault with the config file and setup default values at startup. Is the above warning an unrelated message or am I missing something?

If there is any additional information I need to provide, please let me know. I appreciate whatever input you can provide =)

**Comment by shartte** [comment]
The configuration log-message is actually irrelevant and is only about config-file comments.

Your actual problem comes from the configuration option sadly no longer being possible to implement, and us just forgetting to remove it.

**Comment by Shtreudel** [comment]
Ouch. So there is no ability to alter meteor generation? Not even to disable it so I can just add recipes for presses?

**Comment by shartte** [comment]
Nope, sadly not. Going forward, it is likely going to be based around biomes, and not dimensions.

**Comment by shartte** [comment]
If you do not want _ANY_ meteorites, you can disable the feature in the config, it should not add it to biomes anymore.

**Comment by Shtreudel** [comment]
Awesome. I guess I'll go the route of custom press recipes then. Thanks for taking the time to help!
