### ISSUE TITLE
Void disk feature request

### ISSUE THREAD

**Issue by EanLombardo** [AppliedEnergistics/Applied-Energistics-2#465]
So when using an me system with automation there are often byproducts that you get that you don't want, like cobble from quarries. A void disk would be a special storage disk. You have to configure it's type in a cell bench, but when  you do any of the types on the disk are just destroyed when they are put in the me system.

This would allow people to automate whatever they like and not have to set up more and more exporters depending on the speed of the automation to export into voiding blocks. And it's simple enough that no new mechanics really have to be added.

**Comment by shartte** [comment]
I'd like to have this. It's more efficient **and** convenient to use a stupid drawer bank with void upgrades than it is to use ME disks.
Using one ME disk per item type + condensers is wasteful.

**Comment by yueh** [comment]
Closing in favour of a more flexible solution, which does not require micromanaging each cell with an upgrade card.
See #5240 and #5242

**Comment by Technici4n** [comment]
Will be nice combined with #5240.
