### ISSUE TITLE
Make textures (mostly GUI/container sprites) more friendly for artists to work with

### ISSUE THREAD

**Issue by ConstaChugga** [AppliedEnergistics/Applied-Energistics-2#4650]
Currently the container sprites in AE2 are a bit of a nightmare to work with. All the little tricks done work great for the default Minecraft UI style however they are incredibly frustrating to work with, such as some elements being reused from vanilla textures and not included in AE2's, unchangeable flat-coloured primitives being drawn over cells or areas, some parts of textures being repeated in a way that's hard to work with, and it not being entirely clear where some textures are used, come from, or if they're used at all.

Fixing this up would not only make the lives of texture artists (like me) easier, it would make your lives easier later down the road if you want to fix or change some parts to be more stylistic or informative (such as adding level marks to the fluid interface's tank).

For context, I am working on a GUI texture pack called Breui, which makes all container sprites I can change a nice, mellow brown, as MC's default grey is too harsh for me.
I got to AE2's GUIs and just dropped it, there's too many hard-coded elements making it basically impossible to give interfaces any kind of look besides default. Which sucks, because I love AE2.

It's difficult to get across all of the things that need to be tweaked at once though. I could probably write up something describing what needs to be made a sprite (such as greyed out inv. cells) and how some things should be handled (like adjusting the terminal height) when I have more time.
![image](https://user-images.githubusercontent.com/22027276/91359295-22f21080-e7a9-11ea-8ecb-3295c3a3d897.png)
![image](https://user-images.githubusercontent.com/22027276/91359321-30a79600-e7a9-11ea-8172-4e76887a02f4.png)
![image](https://user-images.githubusercontent.com/22027276/91359371-4b7a0a80-e7a9-11ea-9cfd-95b947904a4d.png)

**Comment by shartte** [comment]
While I understand your frustration, we're probably only going to _really_ fix this once we rewrite the entire UI (which is needed anyway).

**Comment by ConstaChugga** [comment]
Oh cool. When is that meant to happen?

**Comment by shartte** [comment]
Not before 1.16.2 is stabilized and we don't maintain 4 versions concurrently anymore.
So probably not soon enough for your texture pack, sadly.

**Comment by ConstaChugga** [comment]
Damn. What are the 4 different versions anyway?
I'm guessing 1.12.2, most recent MC version, and something Forge related?

**Comment by shartte** [comment]
1.12 isn't supported anymore. It's 1.15 Forge, 1.16.1 Forge, 1.16.2 Forge and 1.16.2 Fabric

**Comment by ConstaChugga** [comment]
I see. I was unaware that mods had moved on from 1.12 being the defacto standart. Neat.
Also, is there anywhere better to discuss AE2 or modded MC, such as a discord server?

**Comment by shartte** [comment]
There is a Discord linked in the Github Readme or on CurseForge I believe.

**Comment by ConstaChugga** [comment]
It is. Thanks.

**Comment by yueh** [comment]
Hopefully within the next 5 years or so. I certainly would not expect it before 1.17 and also depends on how difficult forge will continue to make it for us to support two modloaders.

Also once we are at a point to even consider it, we will start opening tickets to summarize needed features and keep track of them. Which would be the ideal point to add feedback.
