### ISSUE TITLE
Non-API Renderer Usage Incompatible with Canvas

### ISSUE THREAD

**Issue by grondag** [AppliedEnergistics/Applied-Energistics-2#4657]
I've fixed some problems in Canvas and JMX that were going to prevent AE2 from being compatible with Canvas when [the PR to fix Fabric #987](https://github.com/FabricMC/fabric/pull/1046) is merged. 

However, AE2 is still depending on an implementation class [here](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/b1a55f3a79fe6c4fdd673325df4c37a2bd7f632f/src/main/java/appeng/thirdparty/codechicken/lib/model/pipeline/transformers/QuadReInterpolator.java#L42) and I can't do anything about that.

If there's a need for a mutable buffer quad,  it's possible to create a `QuadEmitter` instance but given the apparent usage hee it seems possible to simply stash the transformed values in an array, but I could be wrong.

As always, feel welcome to tag/ping me with questions/feedback.

**Comment by shartte** [comment]
Yes, I have this on my radar I am just waiting for the upstream PR to be merged.

**Comment by shartte** [comment]
Removed the dependency on implementation class.
