### ISSUE TITLE
Silicon recipe not working w. 8.1.0-alpha.5 [FABRIC].

### ISSUE THREAD

**Issue by vini2003** [AppliedEnergistics/Applied-Energistics-2#4659]
In the [silicon recipe](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/fabric/master/src/main/resources/data/appliedenergistics2/recipes/smelting/silicon.json), an array of tags is being used; which is invalid. A tag extending (`#`) both tags should instead be used, or an array of items themselves.

**Comment by shartte** [comment]
Can you point me to some reference as to why that would be invalid?

**Comment by vini2003** [comment]
My bad; it's KubeJS.
