### ISSUE TITLE
Add a generic capability based P2P tunnel

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#4666]
The current P2P tunnels for fluids, forge energy and some degree items are very similar and could be combined into a single class with configurable suppliers for the input and output capabilites.

This should allow for other mods to add custom tunnels, but that will require some careful planning for the requirements,

- [ ] Extract a generic P2P tunnels for capabilities
- [ ] Change `TunnelType` into an interface make extending easier
- [ ] Add a registry for tunneltypes and input/output capabilities (tentative)

**Comment by wisemars** [comment]
Why not remove the energy / liquid separation at all and make an imitation of the direct connection of pipes, wires and other things.

**Comment by Technici4n** [comment]
Addons can now add p2p tunnels, provided they depend on implementation details. I would say that is fine for now.
