### ISSUE TITLE
Items of the same type but with different enchantments combine in me system

### ISSUE THREAD

**Issue by Cielis1** [AppliedEnergistics/Applied-Energistics-2#4669]
**Describe the bug**
When adding two or more of the same item with different enchantments (e.g. a diamond pickaxe with fortune I and another with unbreaking III) into an ME system, the second item stacks into the first, causing loss of the second item.

**To Reproduce**
1. Create any ME system
2. Get two of the same enchantable item
3. Ensure that at least one of the items is enchanted and that both have identical durability
4. Put both items into the me system via any method
5. Both items will occupy one slot and have the same enchantments

**Expected behavior**
Items with differing enchantments should not stack in an ME system

**Additional context**
Recording of bug: https://youtu.be/NP7CJjZ30lg
Screenshots of bug: https://imgur.com/a/0xC1utN
Issue also occurs on latest 1.16.1 build

**Environment**

Minecraft Versions: 1.16.1 and 1.16.2
Applied Energistics 2 versions: appliedenergistics2-8.0.0-beta.2 and appliedenergistics2-8.1.0-alpha.1
Forge versions: 32.0.108 and 33.0.23

Tested with only AE2 + forge on 1.16.2 and many mods + AE2 on 1.16.1 (mods list: https://imgur.com/a/yUdkoZn)

**Comment by shartte** [comment]
Confirmed. Found the reason, working on fix.
This affects damageable items only. (Which would still be a _lot_ of stuff with enchants).
