### ISSUE TITLE
shift click name plates into inscriber bug

### ISSUE THREAD

**Issue by Monster-Zer0** [AppliedEnergistics/Applied-Energistics-2#4671]
Fabric API 0.19.0+build.398-1.16
applied energistics2 fabric 8.1.0-alpha 5
mc 1.16.2

**To Reproduce**

take name plates.. at least 2 shift click into inscriber. get crash.

**Expected behavior**

no crash when adding to inscriber

**Environment**
[Crash Log](https://hastebin.com/amoqedafuz.sql)

**Comment by MrWinABagel** [comment]
It seems to be an issue only on dedicated servers
What happens on servers: https://youtu.be/nZSgkWYEahg
Vs what happens in singleplayer: https://youtu.be/VzW2q1KF6_g

**Comment by shartte** [comment]
NoSuchMethodErrors are often us using client-side only methods on servers. Sounds like that is the case here. Investigating...
