### ISSUE TITLE
Custom mod pack

### ISSUE THREAD

**Issue by Tyrantin** [AppliedEnergistics/Applied-Energistics-2#4672]
I would like to add this to a custom mod pack!

**Describe the feature**
I would like to be able to remove the Channels from the Dense Cable.
The only thing that would be able to connect to it from that point would be the rest of the cables.

**Reasons why it should be considered**
Reduce the amount of Tic and cable overload that tends to happen in bases resulting in lag!

**Additional Context**
If someone could instruct me in how to "Fix" this for my mod pack I would greatly appreciate it!

**Comment by shartte** [comment]
Not "fix"-able

**Comment by Tyrantin** [comment]
I didn't mean it as it was broke...

**Comment by mindforger** [comment]
and he said as it was meant, the way blocks IDs and rendering now works, this is not feasible to make it optional anymore, though the lack of the feature is not "fix"-able unfortunatly

by the way this has been asked a few times yet, please consider searching closed issues too next time :)
