### ISSUE TITLE
No REI when bringing up crafting terminal

### ISSUE THREAD

**Issue by Monster-Zer0** [AppliedEnergistics/Applied-Energistics-2#4673]
**Describe the bug**
when bringing up the crafting terminal, rei is blank (could be rei bug)

however fluid terminal shows a few lines of rei.

**To Reproduce**
bring up crafting terminal with rei installed

**Expected behavior**
open crafting terminal, rei shows.

**Additional context**
https://i.imgur.com/FVXwy4t.png

**Environment**
1.16.2 
Fabric API 0.19.0+build.398-1.16
applied energistics2 fabric 8.1.0-alpha 5

**Comment by MrWinABagel** [comment]
![image](https://user-images.githubusercontent.com/17460735/91790268-f3426e80-ebd5-11ea-847f-25608d308efb.png)
Image of what it looks like, happens with all ae2 blocks with a gui

**Comment by shartte** [comment]
@Monster-Zer0 Please specify your REI version too. This looks newer than mine.

**Comment by Monster-Zer0** [comment]
5.2.9

**Comment by shartte** [comment]
Should be fixed in next version.
Exclusion zones are not perfect yet, but should at least be usable now.

![image](https://user-images.githubusercontent.com/1261399/91919233-85757000-ecc5-11ea-8a12-4f20635ea315.png)
