### ISSUE TITLE
Invisible facade when placing non-opaque block next to facade in any direction

### ISSUE THREAD

**Issue by Monster-Zer0** [AppliedEnergistics/Applied-Energistics-2#4674]
Fabric API 0.19.0+build.398-1.16
applied energistics2 fabric 8.1.0-alpha 5
mc 1.16.2

**Describe the bug**
when placing a non-opaque block next to a facade, the facade will go invisible.

**To Reproduce**
place a non-opaque block next to a facade, it will go invisible.

**Expected behavior**
no invisible

**Additional context**
https://i.imgur.com/NtjVmHI.jpg

**Comment by shartte** [comment]
Should be fixed in next version.
