### ISSUE TITLE
Missing textures on 1.16.1-forge-32.0.108

### ISSUE THREAD

**Issue by meza** [AppliedEnergistics/Applied-Energistics-2#4679]
Hey, I'm trying to play with 8.0.0-beta.2 but have come across some missing textures.
Some items work but the most don't.
Can I do something to fix it locally or should I just wait for a proper release?

![image](https://user-images.githubusercontent.com/211977/91919982-a6d35d80-ecbf-11ea-89e8-d38fa905d505.png)

**Comment by sagesse-cn** [comment]
If use OptiFine mod, plase install additional for OptiForge.

**Comment by Manan2004** [comment]
where can i download it??

**Comment by yueh** [comment]
Please follow the issue template when reporting bugs as well as do a quick search for duplicates.

**Comment by meza** [comment]
> Please follow the issue template when reporting bugs as well as do a quick search for duplicates.

I swear I did search! 😅 Not hard enough then
