### ISSUE TITLE
Server freezes when using an export bus with a fuzzy card

### ISSUE THREAD

**Issue by Ricket** [AppliedEnergistics/Applied-Energistics-2#4681]
**Describe the bug**
1.12.2, `appliedenergistics2-rv6-stable-7.jar` in pack `Enigmatica 2 Expert 1.81a`

I set up an export bus, and the moment I drop a fuzzy card into it, the server freezes. ~I am not sure if it will ever unfreeze.~ After about 10 minutes, the server OOMed. I am running with Xmx 8gb...

**To Reproduce**
1. set up export bus with some item to export
2. add a fuzzy card

**Expected behavior**
Not freeze the server

**Additional context**
![image](https://user-images.githubusercontent.com/196978/91958699-4ea35800-eccd-11ea-8e05-0d3986e0ef58.png)

**Environment**

- Environment: 
See above screenshot for the stack trace.

My AE2 network is pretty expansive, with about 150 molecular assemblers and dozens of machines. A few storage buses attached to storage drawer controllers, mostly small, largest one has about 80 items in it. Couple of storage buses attached to crates. Around a dozen P2P connections. Only a few recipes (definitely less than 10) are oredict enabled; I have heard that the oredict option is much slower. Plenty of RF being fed into the system, verified by the network tool.

**Comment by shartte** [comment]
Sorry, we currently do not support any version older than Minecraft 1.15 anymore.

This specific part has actually been changed in 1.15. If you can reproduce this on 1.15++, please let us know.
