### ISSUE TITLE
Missing items and blocks from creative inventory and JEI

### ISSUE THREAD

**Issue by emanuele246gi** [AppliedEnergistics/Applied-Energistics-2#4685]
**Describe the issue**
I have installed the latest version of AE2 for Minecraft 1.15.2: 7.0.3, with Forge 31.2.36
![2020-09-03_13 22 43](https://user-images.githubusercontent.com/61762317/92109463-5c4e0000-ede9-11ea-8952-5cfe53157a26.png)

As you can see, I can't find anything about the mod, except the facades and those tools that you can see on the right side of the JEI tab
Should I post the log?

**Comment by shartte** [comment]
Yes, we broke this by moving the model registration ealier to avoid models from going missing.

A fix is already in the pipeline: #4682

**Comment by emanuele246gi** [comment]
Oh thanks!

**Comment by shartte** [comment]
Should be fixed in next version.
