### ISSUE TITLE
[Fabric 1.16.2] InvocationTargetException + IllegalArgumentException at startup

### ISSUE THREAD

**Issue by Fogrits** [AppliedEnergistics/Applied-Energistics-2#4686]
![image](https://user-images.githubusercontent.com/14002834/92186055-ed45cb00-ee2b-11ea-8269-f036721b21ff.png)

Running Fabric 0.9.2-206
              Fabric API 0.20.1-401
              Applied Energistics 8.1.0-a6

**Comment by shartte** [comment]
Unable to reproduce this with the stated versions.

**Comment by shartte** [comment]
p.s.: we are also incompatible with fabric-api 0.20 for other reasons. please downgrade. fabric-api to the previous version.
