### ISSUE TITLE
Server crash on 7.0.3

### ISSUE THREAD

**Issue by Jergeric** [AppliedEnergistics/Applied-Energistics-2#4691]
Aloha,
directly after the start the server crashes directly.

[crash-2020-09-04_19.51.13-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5176298/crash-2020-09-04_19.51.13-server.txt)

**Comment by shartte** [comment]
The stack trace in the log does not look suspicious.
Please provide a full server log.
