### ISSUE TITLE
Annihilation Plane voids Concrete Blocks

### ISSUE THREAD

**Issue by NillerMedDild** [AppliedEnergistics/Applied-Energistics-2#4692]
**Describe the bug**
The Annihilation Plane completely destroys Concrete Blocks, the blocks are not picked up or dropped. Concrete Blocks are the only blocks I have found with this behaviour.

**To Reproduce**
1. Place and power Annihilation Plane, attach AE block storage of some kind
2. Place any Concrete (from vanilla Minecraft) on the Annihilation Plane
3. Observe that the block has not gone into the AE block storage

**Expected behavior**
For the Concrete to be broken, and picked up.

**Additional context**

**Environment**
Forced crash: https://gist.github.com/NillerMedDild/f431a6c16dda4092c6b229a3653f4301

- Environment: 
Singleplayer, in the modpack Enigmatica 6 version 0.2.15 in-dev

**Comment by shartte** [comment]
We believe this to be related to this: https://github.com/MinecraftForge/MinecraftForge/issues/7258

This broke for us after fixing a bug that actually inverted the harvestable check... :-|

**Comment by yueh** [comment]
We use forge to obtain the correct tool for a block, which in many cases is not maintained at all by them.

Hopefully they fix it or provide a working alternative, but for now there is not really something we can do about it.

**Comment by ManIkWeet** [comment]
3 months later, this appears to still be an issue.
Is there really nothing that can be done about it on the AE2 side?
(appliedenergistics2-8.2.0-alpha.2)
