### ISSUE TITLE
[Forge, 1.16.1] Color Applicator behavior

### ISSUE THREAD

**Issue by TheSnowyChickens** [AppliedEnergistics/Applied-Energistics-2#4693]
Hello,
the problem is simple: the Color Applicator doesn't work. :( 

**Describe the bug**
I click with my Color Applicator with blue dye (and yellow dye) selected on a Fluix ME Dense Smart Cable and nothing changed on the cable.
The Applicator take his 100 RF/FE (but anyhow this is also a visual bug, it reset himself to 100% RF/FE after some time) and thats it.

**To Reproduce**
1. Place a Cable
2. Fill your Color Applicator with RF/FE and some Dye.
3. Click on the Cable (with selected Dye)

**Expected behavior**
A colored cable should appear.

**Additional context**
![grafik](https://user-images.githubusercontent.com/29357962/92293383-71c74500-ef23-11ea-8397-6e0781ab1971.png)

**Environment**
+ I play on a server
+ Enigmatica 6 modpack
+ Java 8 64 bit Update 261
+ 12GB RAM allocated

- Environment: 
Forge: 1.16.1 - 32.0.108
AE: appliedenergistics2-8.0.0-beta.2

**Comment by shartte** [comment]
Fixed in next version.
