### ISSUE TITLE
Feature: Not a JSON object

### ISSUE THREAD

**Issue by ianmeinert** [AppliedEnergistics/Applied-Energistics-2#4694]
**Describe the bug**

JSON objects are failing to load on world start up.

**To Reproduce**

1.     install TechReborn
2.     generate world
3.     watch the logs.

1.     Rejoin the same world
2.     watch the logs

**Expected behavior**

JSON objects should load without error

**Additional context**

**Environment**

[17:40:32] [Netty Client IO #8/ERROR]: Feature: Not a JSON object: "appliedenergistics2:quartz_ore"

- Environment: 

-     Minecraft: 1.16.2
-     Mod Loader: fabric 0.9.3+build.207
-     appliedenergistics2-8.0.0-beta.2

**Comment by shartte** [comment]
This is not caused by us.
