### ISSUE TITLE
1.12.2 AppliedEnergistics crashes dedicated Server for unknown reason

### ISSUE THREAD

**Issue by Silverrain2004** [AppliedEnergistics/Applied-Energistics-2#4698]
Hello Guys, i have a Big Problem... i dont know why my Server is crashing... 
i see that AE2 is the Problem... so i thought maybe problems with the 
Dimension ID becouse i have Twiglight too... but seems not... i would be 
very happy for every help Guys... 

Version: appliedenergistics2-rv6-stable-6 (I used the latest for 1.12.2 but still the same Problem)

**https://hastebin.com/zegehejato.rb (Crashreport)**

**https://hastebin.com/bujacivoqo.md (Latest.log)**

Thats my Config:

```
spatialio {
    D:spatialPowerExponent=1.35
    D:spatialPowerMultiplier=1250.0
    I:storageDimensionID=-12
    I:storageProviderID=-11
}
```

If you Guys need additional Information, i am willing to collaborate, so let me know.

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.15 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.

**Comment by shartte** [comment]
I looked at your crashlog anyway @Silverrain2004, the actual error is:

```
[21:57:27] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: org/lwjgl/LWJGLException
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_261]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_261]
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539) ~[forge-1.12.2-14.23.5.2854-universal.jar:?]
```

That is not related to AE2. The error further down happens because AE2 is not handling this particular error very well when shutting down, but the error mentioned above is what is actually crashing your server. (And that is not us I think)

**Comment by Ommina** [comment]
It's constructing Cursor Icon Changer.  Which really sounds like something that is client only.

Wholly unrelated to AE2.

**Comment by Silverrain2004** [comment]
Thank you very much Guys :) that solved my whole Problem... becouse i was unable to resolve
