### ISSUE TITLE
why won`t it go ito the system?

### ISSUE THREAD

**Issue by Chaos-Gang-OFC** [AppliedEnergistics/Applied-Energistics-2#4700]
Hey my crafting cpu is 7 by 7 by 21
why won´t it go into the system. it has enought power and the it´s attached to the system with several cables.
my modpack is SkyFactory 4 btw. channles are disabled.
![crafting cpu 1](https://user-images.githubusercontent.com/52545942/92329684-5a926f80-f069-11ea-945e-8e1ae6790905.png)
![crafting cpu 2](https://user-images.githubusercontent.com/52545942/92329686-5b2b0600-f069-11ea-90eb-4f40fd5af7fd.png)
![crafting cpu 3](https://user-images.githubusercontent.com/52545942/92329687-5c5c3300-f069-11ea-9612-8912217c7b99.png)
![crafting cpu 4](https://user-images.githubusercontent.com/52545942/92329689-5cf4c980-f069-11ea-8eae-8120ea1b1a6e.png)
![crafting cpu 5](https://user-images.githubusercontent.com/52545942/92329690-5e25f680-f069-11ea-9a55-cc48e1bcb59e.png)

**Comment by yueh** [comment]
Because 21 > 17

**Comment by Chaos-Gang-OFC** [comment]
bruh so its not possibla to build the full 4913 bloks in another quadrangular structure except of a square... well then...
