### ISSUE TITLE
[1.16.2 Forge] Crashes on new version of Forge released on 09/06/20

### ISSUE THREAD

**Issue by BedrockLegends** [AppliedEnergistics/Applied-Energistics-2#4703]
As soon as you go to launch a said modpack, this mod crashes before loading
**Describe the bug**

**To Reproduce**

Update to new forge release today
and Boom Crash goes the Dynamite 
**Expected behavior**

**Additional context**

https://gist.github.com/BedrockLegends/b48ec9559cf3cb62b51a7ba0a3d21a83

**Environment**

- Environment:

**Comment by shartte** [comment]
I cannot reproduce this. Please try this again when the next alpha of AE2 for 1.16.2 releases (soon)

![grafik](https://user-images.githubusercontent.com/1261399/92417460-98bf8a00-f162-11ea-9625-f6e314397d32.png)
