### ISSUE TITLE
Crafting Terminal keeping amadron tablet

### ISSUE THREAD

**Issue by Throwtex** [AppliedEnergistics/Applied-Energistics-2#4707]
Build a ME-system and put all our stuff in it. And now we can't get the Amadron Tablet from PneumaticCraft :Repressurized out of the system. Tried left clicking, right clicking, shift etc. Nothing seems to get the tablet out of the system.

**Comment by shartte** [comment]
Please provide more information as described in the issue template (the initial value of the text box when you create an issue).
