### ISSUE TITLE
Can't Connect Wires to ME System or Interact Correctly (Only for me?)

### ISSUE THREAD

**Issue by Taxibutle** [AppliedEnergistics/Applied-Energistics-2#4711]
**Describe the bug**

Basically, every time I place down a wire that is connected to my ME system, it immediately breaks itself and I cannot interact with multiple different machines related to AE2. Example: the crafting interface doesn't have the crafting part, just the terminal, and it cannot scroll down (might not be enough items for the scrolling); the spatial IO port doesn't allow me to click it; wires can be placed anywhere not connecting to my ME system. (Memory card would also get info then clear itself, nothing in off-hand)

**To Reproduce**

Placing down wires next to ME system or interacting with AE2 machines.

**Expected behavior**

I expected the wires to be placed down and connected to my ME system, and to be able to access the spatial IO port.

**Additional context**

![2020-09-08_18 22 34](https://user-images.githubusercontent.com/25257631/92537254-4b462a00-f201-11ea-9901-28940fe6d31f.png)
![2020-09-08_18 22 39](https://user-images.githubusercontent.com/25257631/92537257-4ed9b100-f201-11ea-9741-bde66c9e9ee3.png)
![2020-09-08_18 24 20](https://user-images.githubusercontent.com/25257631/92537259-50a37480-f201-11ea-9dde-a8486243e6c4.png)
![2020-09-08_18 24 22](https://user-images.githubusercontent.com/25257631/92537267-526d3800-f201-11ea-9151-0e67b51e65c4.png)
![2020-09-08_18 24 31](https://user-images.githubusercontent.com/25257631/92537269-5436fb80-f201-11ea-9177-bbba2e383853.png)

**Environment**

Lots of mods, the ME system was located next to some chunkloaders. It was also inside the spatial IO port's pylons, but NOT inside a drive. There were two quantum rings connected, one ME drive, one ME controller, a Charger, a Security Terminal (placed by me), energy accepters, dense cables (smart and not), energy condenser, two P2P systems (one was working, other was not). 

The server was restarted a few different times, my player data was wiped, replaced the ME controller, there are no plugins on the server, I have used the shader in the photos with the mod before this occured, and the build of the mod is the latest 1.12.2 version

Other players other than me can still use the system correctly and place wires/etc, but I specifically can not. I have no client-side mods other than optifine and inventorytweaks installed.

- Environment: https://pastebin.com/xc7xMZcB  <-- Forced Crash Report

**Comment by Taxibutle** [comment]
It also seems that when I remove the ME controller I can then place and access stuff, but not while it is placed down, so it seems to be something related to that.

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.15 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
