### ISSUE TITLE
Cannot Take some items out of the terminal

### ISSUE THREAD

**Issue by GustavGregorovich** [AppliedEnergistics/Applied-Energistics-2#4715]
Version 1.15.2 (most recent update of the mod)

Made an ME system. 3 controllers, a drive with 4 x 64k storage inside. I use the terminal but am unable to pull out the 2 enchanted bows from it. Cannot shift click them into inventory or drag click them into it. As if they arent there

**Comment by shartte** [comment]
Can you please fill out the information that is requested in the issue template (most importantly the F3+C forced crash)

**Comment by GustavGregorovich** [comment]
Steps to reproduce:
 forge-1.15.2-31.2.37 server
both bows are enchanted (vanilla enchants even tho server has non vanilla enchants)
ME system has 3 controllers, 1 drive case, and 4 x 64k drives inside. 3 have 63/63 types. 


Crash report:
https://pastebin.com/YEeiYE1s



Video of it:
[2020-09-09 20-27-29.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5198473/2020-09-09.20-27-29.zip)

**Comment by yueh** [comment]
Cannot reproduce this with the current release for 1.15 with AE2 alone.

We had issues in the past with other mods attaching random data to stacks only on clientside, which technically makes them completely different items, so the server will not know about them when trying to retrieve these again.

It would be certainly helpful, if you could try and reproduce this in a test world and try to remove/readd mods until it happens.

Also when holding a bow in your inventory, dumping the player data with `/data get entity @p` might be an idea. But I am currently not sure, if this dumps the client or server data. And probably not with an inventory full with other items.

**Comment by GustavGregorovich** [comment]
I transferred over the world file to single player so I could easily test it. With the same mods, it still occured. 

Next, I removed every single mod from the game except for AE2 and Mekanism (to power the controllers) and I still could not take the bows out. I could use the middle mouse button to make a copy of it to take out, but that was all. 

Here is the requested `/data get entity @p `

On the single player world, if I make copies of the bows that will not get out of the ME system, then I Shift them back into the system, I can take those bows out, then after a timer, can take the offending bow out as well. That might be a property of the ME system stacking it though? Give me 20 min to re add the mods to the profile, and i will try to replicate on the server world

**Comment by GustavGregorovich** [comment]
Like you mentioned, I believe the ME system did not recognize that there was an actual item where the bows were shown. Because I redid the stop I took in the single player world. I copied the bow three times, and then shift clicked them back into the system. But where the system should have shows 4 bows, it only showed 3

**Comment by corhean** [comment]
I noticed a similar problem with revolvers and revolver speedloaders from Industrial Engineering while playing Enigmatica 6. 
https://github.com/NillerMedDild/Enigmatica6/issues/297 

I was able to reproduce on a brand new single player test world by creating a simple AE system and loading random items in - other items from IE can be removed, just not revolvers or revolver speedloaders.

**Comment by yueh** [comment]
I still cannot reproduce this within the dev environment or a basic server/client setting.

For now I would assume some other mod is change the nbt data of each item just on one side, which already happened in other versions and caused these sorts of problems. However as long as there is no indication about which mod it could cause, there is nothing we can really do currently. (or even a combination of some mods)
