### ISSUE TITLE
Pattern creation with JEI only shows stored items

### ISSUE THREAD

**Issue by Minspace32** [AppliedEnergistics/Applied-Energistics-2#4717]
**Describe the issue**
I have a issue  creating patterns when using the ? from JEI it only put the items in the patten window that are currently stored in AE.

Expected 
Patten can be created without having the items stored in AE

**Environment**

Direwolf 20 1.12 pack with AE2 version appliedenergistics2-rv6-stable-6.jar also tried on 
[crash-2020-09-10_19.07.53-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5200484/crash-2020-09-10_19.07.53-client.txt)

- Environment:

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.15 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.

**Comment by mindforger** [comment]
@Minspace32 this is by design, don't know if that will be in later versions, pattenr crafting requires the items to be present

**Comment by shartte** [comment]
There's been a large change regarding this feature in 1.16.2
