### ISSUE TITLE
Forge Tag Support for 1.15.2

### ISSUE THREAD

**Issue by ClaudiusMinimus** [AppliedEnergistics/Applied-Energistics-2#4725]
Add support to AE2 items include forge tags when possible

**Describe the feature**
For example the AE2 Nether Quartz Dust to have the forge tag: <tag:forge:dusts/quartz> 

**Reasons why it should be considered**
In the above example Mekanism Nether Quartz Dust would be compatible with AE2 and making crafting easier. As it is, I have to add recipes conversions to my mod pack. This should just work out of the box by using forge tags.

**Additional Context**
![2020-09-11_13 13 00](https://user-images.githubusercontent.com/17887664/92964717-cee65d80-f431-11ea-8154-5a2a185974e6.png)

**Comment by ClaudiusMinimus** [comment]
I'm going to use kubejs to fix this and other ae2 recipes

**Comment by shartte** [comment]
I believe this should be the case in newer versions of AE2 anyway. We just didn't backport it to 1.15

**Comment by shartte** [comment]
@ClaudiusMinimus If you want this for your pack, you can probably just copy paste the recipes/tag files from a newer AE2 jar into a datapack and include that in your modpack.
