### ISSUE TITLE
[1.16.2] Double Grindstone Crank visual glitch

### ISSUE THREAD

**Issue by Fogrits** [AppliedEnergistics/Applied-Energistics-2#4726]
![2020-09-12_00 53 49](https://user-images.githubusercontent.com/14002834/92986619-ab073400-f492-11ea-969f-5dc61cd1fb5a.png)

**Comment by shartte** [comment]
Uuuuuuuuuuuuuuh how?

**Comment by Fogrits** [comment]
I don't have any idea.

**Comment by shartte** [comment]
Please provide more information as described in the issue template (the initial value of the text box when you create an issue).

**Comment by Fogrits** [comment]
This is my modlist. I had simply crafted a grindstone and put the crank on it, no additional steps were required. as soon as I started turning the crank lever, its original texture state remained and the model started to turn (as it should)
![image](https://user-images.githubusercontent.com/14002834/92996623-5a6bf700-f4e3-11ea-8377-7c94a1745338.png)

**Comment by shartte** [comment]
I cannot reproduce this on AE alpha.9
