### ISSUE TITLE
Allow Storage Bus configurations to be copied into a Cell Workbench

### ISSUE THREAD

**Issue by nBeebz** [AppliedEnergistics/Applied-Energistics-2#4727]
**Describe the feature**
It should be possible to load a Storage Bus's partition config into a Cell Workbench using a Memory Card, and vice versa.

**Reasons why it should be considered**
A Storage Bus and a Cell Workbench have functionally identical configurations of 63 items, theoretically they should be compatible. Some interesting possibilities this would allow:
- Creating a partition for ME Drives and View Cells using any arbitrary container.
- Easily transferring the contents of a partitioned ME Drive via a Storage Bus using an I/O Port.
- Sets of items can be "abstracted away" to some external system by copying the Storage Bus's configuration into an inverted View Cell. 

I think this would give View Cells and partitions a lot more utility.

**Comment by nBeebz** [comment]
Thinking about writing a PR for this @shartte, y/n?

**Comment by Technici4n** [comment]
Implemented in #6638.
