### ISSUE TITLE
AE Compass Service prevents VM termination

### ISSUE THREAD

**Issue by sfPlayer1** [AppliedEnergistics/Applied-Energistics-2#4728]
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/5225ea426beb873ab4d1906da352b5dde4b45067/src/main/java/appeng/services/compass/CompassThreadFactory.java#L37 doesn't use Thread.setDaemon(true), leading to a non-daemon thread that will prevent MC from shutting down from an exception. As there is no way to orderly terminate the thread within a crash, making all auxiliary threads daemon threads is the only adequate solution.

**Comment by yueh** [comment]
Thanks, I would assume this would also apply here
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/b8e53adf40fc363fff341ea1b04614c5a97b564b/src/main/java/appeng/me/cache/CraftingGridCache.java#L99-L101

**Comment by sfPlayer1** [comment]
Yes, same easy fix

**Comment by sfPlayer1** [comment]
While you are at it, setUncaughtExceptionHandler is always a good idea, just in case an exception slips through and otherwise ruins your day by becoming invisible.
