### ISSUE TITLE
ME Fluid Interface Crash - MC 1.16.1

### ISSUE THREAD

**Issue by sagesse-cn** [AppliedEnergistics/Applied-Energistics-2#4733]
**Describe the bug**

Crash when pull the fluid from the `ME Fluid Interface` by `Mekanism 10.0.9` the `Ultimate Mechanical Pipe`

**To Reproduce**

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/6903353/93106932-85bd3480-f6e3-11ea-9d8d-d047da6ac0f1.png">

**Expected behavior**

Crash

**Additional context**

https://pastebin.com/nr3797GP

**Environment**

Mekanism-1.16.1-10.0.9
appliedenergistics2-8.0.x(compile from latest source code at branch 8.0.x-1.16.1)

**Comment by shartte** [comment]
This should now be fixed on 1.15/1.16.1 and soon 1.16.2
