### ISSUE TITLE
ME Network - Autocrafting Stuck on Crafting Stage, ME Interface Won't Push to Subnetwork

### ISSUE THREAD

**Issue by FluxEntity** [AppliedEnergistics/Applied-Energistics-2#4734]
**Describe the issue**

I've had an ME Network work perfectly for several days now, autocrafting and all with over 100 recipes, placing orders on hundreds and thousands of items in single requests without issue. Without warning, the ME network was having recipes get stuck in Interfaces on the way back after going through a series of processing machines. That is to say, this problem occurs with autocrafting using ANY processing recipes in my current setup.

Here are images of my setup and the problem at hand using 4 Iron Ingots -> 1 Iron Gear as an example.

Searching the system, it's clear that the recipe is initially available for request, and the network holds the materials to make it.

![javaw_CRFtX2uPUW](https://user-images.githubusercontent.com/8834111/93159656-4e935700-f6d4-11ea-9a42-3fb9954e6938.png)
![javaw_ZmreyLoEIM](https://user-images.githubusercontent.com/8834111/93160113-4982d780-f6d5-11ea-8a2d-e8f3bb079133.png)

However, after placing the order in queue, the order manages to initially send the materials, but they get stuck in an Interface/Import Bus on on the way back, where Interfaces are used for processing machines that push into the network, and Import Buses are used to instead pull items from those machines that don't have the ability to push.
Here's the CPU getting stuck in the "Crafting" Stage of the request:

![javaw_W5jVR4vVJd](https://user-images.githubusercontent.com/8834111/93160165-65867900-f6d5-11ea-9b90-1343e9847d69.png)

Here is where the materials for the request are pushed, and the Ingots successfully are processed into a Gear, but the resulting item gets stuck in the Interface on the way out.

![javaw_xpStBgqq2Z](https://user-images.githubusercontent.com/8834111/93160413-e2b1ee00-f6d5-11ea-8f6e-dd06c1099fd7.png)
![javaw_e6s0sNkG4I](https://user-images.githubusercontent.com/8834111/93160396-d62d9580-f6d5-11ea-8ccf-efb4be367aa9.png)

Here's an image below of the storage bus to the interface connecting to the main network, where orders would reach completion after routing to this point.

![javaw_haPWZCBNfR](https://user-images.githubusercontent.com/8834111/93160606-4a683900-f6d6-11ea-8388-991ad8df85ec.png)

Autocrafting via standard recipes (ME Interfaces + Molecular Assemblers) seems to work fine as long as the immediate materials are already on hand, but anything with intermediate crafting steps will simply report an item as missing rather than attempt to craft the ingredient, despite having the recipe and base materials available. My ME Network is fairly modular and contains all processing within subnetworks, so having the entire system collapse on itself has been a head-scratcher.
Sorry in advance if you suspect that this issue is attributed to mod conflicts.

**Environment**

- Environment: rv6-stable-7, Modpack: E2:E

**Comment by mindforger** [comment]
the slot you set up the item in is working like a chest slot, the machine can pull from it but it will not be pushed, you should either make your machine pull the item or use an export bus instead!

**Comment by FluxEntity** [comment]
Issue resolved - the presence of an ME Security Terminal with no biometric cards installed would allow the owner of the network to place orders and items to be initially exported, but importing the product back into the network requires elevated permissions. Adding a blank biometric card with Deposit/Withdraw permissions allowed the ME Interfaces to push the products to the entry Interface/Storage combo, and injected the items back to the network. Thanks for the help!
