### ISSUE TITLE
Name and ID list? (for custom cr scripst)

### ISSUE THREAD

**Issue by Chaos-Gang-OFC** [AppliedEnergistics/Applied-Energistics-2#4739]
Hey. Is there a list of the names and id`s of all items (I mean these wich are used in custom crafting recipe scripts (as an example _**appliedenergistics2:material:42**_ or _**appliedenergistics2:material:8**_) ). I especially want to make custom crafting recipes for the creatiev items (Creative Energy Cell and Creative ME Storage Cell) and need the ids or names for these items which are used in such scripts.

THX.

**Comment by shartte** [comment]
Sorry, we currently do not support any version older than Minecraft 1.15 anymore.
