### ISSUE TITLE
1.12.2 version. Crash with kemonocraft on any multipart block placement.

### ISSUE THREAD

**Issue by sallyshift** [AppliedEnergistics/Applied-Energistics-2#4740]
Hello from russia, sorry for my poor english or bad discribing, ill try my best. So, if i have only installed ae2 last version and kemonocraft, then trying to place cable or p2p tunnel or other multipart blocks like terminals, game freezes and crashes fast, i talked to kemonocraft developer, he said to report this here. Crashlog attached.
[crash-2020-09-17_04.52.28-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5236740/crash-2020-09-17_04.52.28-client.txt)

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.15 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
