### ISSUE TITLE
Accidential enchantment unification

### ISSUE THREAD

**Issue by 2xMJet** [AppliedEnergistics/Applied-Energistics-2#4743]
Played on server
When i put 2 of my Netherite pickaxes with different enchant into ME system(from ME Crafting terminal), Enchants and name of one pickaxe copied from 1 to another replacing data of second pick.

**Reproducing**:
Put both items in crafting grid and put them from grid to ME system first item will copy its data to second.
Works even when put from inventory.
Works same with names and not only with gear even with blocks with not matching NBT-data

Expected differentiation between 2 items with not matching NBT.

**Additional context**
2 boots with Soul Speed II and Soul Speed III
![image](https://user-images.githubusercontent.com/26283528/93473701-87277080-f920-11ea-87fd-79c760168541.png)
![image](https://user-images.githubusercontent.com/26283528/93473734-90184200-f920-11ea-97d1-a6c507a86229.png)
Putting them into system
![image](https://user-images.githubusercontent.com/26283528/93473802-a920f300-f920-11ea-9318-77776125047a.png)
Getting both Soul Speed II when put Soul Speed II boots first.
![image](https://user-images.githubusercontent.com/26283528/93473865-bdfd8680-f920-11ea-8f77-508cfd8134c5.png)
![image](https://user-images.githubusercontent.com/26283528/93473878-c2c23a80-f920-11ea-8cee-76b91f8dd3dc.png)

**Environment**
Modpack: All The mods 6 0.29 
Forge 1.16.1-32.0.108
AE version 8.0.0-beta.2
Java 8 Update 261 (build 1.8.0_261-b12)
Forced crash:
[crash-2020-09-17_13.13.09-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5239305/crash-2020-09-17_13.13.09-client.txt)

**Comment by yueh** [comment]
Please report this to your modpack. There is nothing we can do about them not updating mods to fix bugs.

**Comment by 2xMJet** [comment]
Is it fixed already?

**Comment by shartte** [comment]
This should be fixed in 8.0.0-beta.3
