### ISSUE TITLE
texture not loading

### ISSUE THREAD

**Issue by FlibbleTiggon** [AppliedEnergistics/Applied-Energistics-2#4751]
textures for select blocks not loading properly. 1.16.1 beta 3
![2020-09-19_16 12 25](https://user-images.githubusercontent.com/71600200/93714971-cf66ae80-fb2b-11ea-9453-ec4d56381ef6.png)

**Comment by shartte** [comment]
Please provide more information as described in the issue template (the initial value of the text box when you create an issue).

Additionally for debugging issues like this, please check for the debug.log in your Minecraft instance's `logs` folder.
