### ISSUE TITLE
Backport Fabric version (1.16.2) to (1.16.1)

### ISSUE THREAD

**Issue by InsaanNotFound** [AppliedEnergistics/Applied-Energistics-2#4752]
I have single request, can we posibbly get a backport of the mod on Fabric for 1.16.1? Yes, i know, i know that i should already advance in game version, but i made modpack specifically for 1.16.1, and i am stuck with it. Looking at Curseforge, people also still use Fabric for 1.16.1. I would be thankful for at least response.
Sincerely
Insaan

**Comment by yueh** [comment]
No.

**Comment by InsaanNotFound** [comment]
That was rough response.
