### ISSUE TITLE
Terminals (and other parts) cannot be rotated around their front axis

### ISSUE THREAD

**Issue by shartte** [AppliedEnergistics/Applied-Energistics-2#4754]
In 1.7 it was possible to rotate terminals and similar parts around their forward axis using a wrench,
which is especially useful when they're embedded in the floor or ceiling, given that there's no inherent "UP" axis in those circumstances.

This is currently not possible anymore.

**Comment by dandin87** [comment]
This may be related to this issue as well. https://github.com/Ladysnake/BLAST/issues/8#issuecomment-735216242 
Also, in the AoF3 Modpack, I noticed with the mod Block Shifter that I was not able to rotate around the same axis as above. I think these may be all related to access .FACING
