### ISSUE TITLE
Dense Smart Cable only giving 8/32 channels

### ISSUE THREAD

**Issue by Raywilleatchu** [AppliedEnergistics/Applied-Energistics-2#4756]
Hi guys, I am a bit new to bigger ae2 systems but I don't want this play through to be another play through without channels and I just need to sit and learn the mod. All I need to know is why is my Dense Smart Cable only offering 8/32 channels. How do I use all of my channels? Every chest except the far right chest in the middle row is unable to connect their storage buses and I don't know why
![image](https://user-images.githubusercontent.com/58750225/93808426-f26f8c00-fc19-11ea-9b97-ebf618a929ad.png)

**Comment by shartte** [comment]
You are using non-dense cable to connect the chests though?

**Comment by mindforger** [comment]
to be more precise, dense cable offer 32 and normal 8. If you attach a normal on a dense, you still only have 8 channels. You need to path the dense close to your target and then branch off a normal cable. You can attach 4 normal in a dense which means 4x8=32 channels
