### ISSUE TITLE
java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by SirOMGitsYOU** [AppliedEnergistics/Applied-Energistics-2#4757]
[crash-2020-09-22_13.37.16-server (1).txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5261448/crash-2020-09-22_13.37.16-server.1.txt)

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.15 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
