### ISSUE TITLE
I am unable to connect BuildCraft kinesis pipes with a energy acceptor

### ISSUE THREAD

**Issue by windetrsfugwq** [AppliedEnergistics/Applied-Energistics-2#4758]
I am unable to connect BuildCraft kinesis pipes with a energy acceptor I am on a server as well
![Minecraft 1 12 2 9_23_2020 1_56_38 AM](https://user-images.githubusercontent.com/66659349/93955799-6aff4700-fd05-11ea-861b-c4e3fe92b40a.png)

**Comment by mindforger** [comment]
did you notice the template text when you opened the issue? it tells you what info is needed for us to help you

there are many versions of minecraft and AE2 around that are being used :)

feel free to add them and the issue can be reopened (consider that versions older than MC 1.15 are not supported anymore)
