### ISSUE TITLE
Missing Textures with Fluix ME Glass Cables, ME Toggle Bus

### ISSUE THREAD

**Issue by CygnusiaX1** [AppliedEnergistics/Applied-Energistics-2#4760]
**Describe the bug**
When placing the blocks such as the ME Fluid Glass Cable, or the ME Toggle Buss, instead of proper cabling, the default purple/black missing block appears. This is happening in the modpack 'All of Fabric v2.1.1', but I manually the mods in the pack. This happens in both Alpha 9 and 10.

**To Reproduce**
Placing the above blocks creates a missing texture block instead.

**Expected behavior**
Placing cabling should produce proper cables and toggles.

**Additional context**
![AE2 Bug](https://user-images.githubusercontent.com/50664192/94346645-b0689080-fff3-11ea-8306-ba4c562a8076.jpg)

**Environment**
Startup Log:
[https://pastebin.com/ed4F31Gx](url)

Forced Crash Report:
[https://pastebin.com/h7F7Twn4](url)

**Comment by shartte** [comment]
> sodium: Sodium 0.1.0-SNAPSHOT

Sodium is not supported, sorry. It does not support the Fabric Rendering API.

**Comment by Technici4n** [comment]
For anyone trying to run AE2 fabric with sodium, you need to install indium as well. Go ask on the All Of Fabric 3 discord server. Find the link yourself, and don't expect any support from us.
