### ISSUE TITLE
Cable hitboxes are not connected but visually they are connected. It doesn't transfer chanels

### ISSUE THREAD

**Issue by FariZTheKiller** [AppliedEnergistics/Applied-Energistics-2#4761]
**Describe the bug**
Cables hitboxes doesn't connect but visually they are connected

**To Reproduce**
Connect some cables to an existing cable

**Expected behavior**
Connect and transfer chanels

**Additional context**
 
![2020-09-28_17 57 00](https://user-images.githubusercontent.com/53105954/94465334-6b498780-01c8-11eb-8ba0-f3d786e928a0.png)

**Environment**

- Environment:

**Comment by shartte** [comment]
Please provide more information as described in the issue template (the initial value of the text box when you create an issue).

**Comment by FariZTheKiller** [comment]
> Please provide more information as described in the issue template (the initial value of the text box when you create an issue).
![image](https://user-images.githubusercontent.com/53105954/94478135-896cb300-01db-11eb-8b11-29ddfdce15f1.png)

It's connected to the system and has enough chanels but it wont work. I also checked the p2p tunnel and it's the same code.
