### ISSUE TITLE
AE2 fabric datapack error

### ISSUE THREAD

**Issue by milkev** [AppliedEnergistics/Applied-Energistics-2#4762]
**Describe the bug**
when attempting to load into a world, it tells me there is an error with the datapack. im not experienced with modding, but it seems like tags that dont exist are required.

**To Reproduce**
build the latest fabric release (8.1 alpha 10), load game with latest fabric api & loader, attempt to join or create a world.

**Expected behavior**
load into the world without errors

**Additional context**
copy & paste from relevant logs:
https://pastebin.com/JB5bhd55>
i can copy a full log if needed

**Environment**
1.16.3 fabric, 
fabric loader v 0.10.0+build.208-1.16.3
fabric api v 0.22.0+build.408-1.16
appliedenergistics2-fabric-0.0.0-SNAPSHOT
I used the command 'gradlew build' and found the mod in /build/libs, as this was the only way i found to compile the mod. if this way is incorrect sorry, and could you let me know how to build it properly if so.

**Comment by shartte** [comment]
Yeah its a bit obtuse. you need to run "gradlew runData" once to generate the data-generated tags. I should probably put checks in that you cant compile otherwise.

BTW: if you just want to play, its on curseforge.

**Comment by milkev** [comment]
i managed to find it on curseforge, thank you though!
it wasnt listed in the main files list so i thought it wasnt on curseforge, turns out its on the sidebar, goodjob curseforge

**Comment by shartte** [comment]
Yeah, we need to really release a beta-version, CF doesnt show alpha versions on the main file list. It's not actually any less stable than the Forge betas.
