### ISSUE TITLE
Add AE2 blocks / items to more appropriate Forge tags

### ISSUE THREAD

**Issue by shartte** [AppliedEnergistics/Applied-Energistics-2#4763]
quartz and charged quartz ore: `forge:ores` (both items and blocks)
quartz and charged quartz ore: `forge:ores/certus_quartz` (blocks)

**Comment by Warbringer12** [comment]
add silicon to forge:silicon (item)
also fluix crystal to forge:gems/fluix
add fluix and certus dust to forge:dust/fluix and forge:dust/certus
add sky stone dust to forge:dust/sky to the tag system please too

**Comment by shartte** [comment]
I don't see a use for forge:dust/sky. There's a slight cost to tags, so unless there's at least _some_ tangible benefit.... Do you have a use for that?

**Comment by Warbringer12** [comment]
nah im good with not having the forge:dust/sky one not become one as long as the rest become tagged im all good

**Comment by phit** [comment]
this would be really nice to have, for cross mod compat, multiple mining tools are having issues with certus ores due to the lack of ore tag on the block

**Comment by Alpvax** [comment]
Additionally, certus quartz blocks should be in the forge:storage_blocks/quartz tag
