### ISSUE TITLE
Selecting an item with a pattern in the crafting terminal hangs the game, which then crashes. (Fabric) 

### ISSUE THREAD

**Issue by Radagast** [AppliedEnergistics/Applied-Energistics-2#4765]
**Describe the bug**
Playing on MC 1.16.2, with appliedenergistics2-fabric-8.1.0-alpha.10. Yesterday, when using the crafting terminal the game hung then crashed. I reverted to a backup and all was well until just now, when the same thing happened again.

**To Reproduce**
Select the crafting terminal and select an item for which a crafting recipe exists. The game crashes.

**Expected behavior**
I expect to craft the item.

**Additional context**
https://pastebin.com/KQwMAtUg

**Comment by joester12321** [comment]
I also am having this issue playing in 1.12.2. Everytime I input a crafting request, game freezes and crashes. Simple recipe, sufficient computer set up, sufficient power.

**Comment by Silsec** [comment]
Same issue as Radagast. MC 1.16.2 with appliedenergistics2-fabric-8.1.0-alpha.10. With a ME Interface to the Inscriber, selecting the item with a pattern in the crafting terminal would crash the game.

**Comment by BeaconStudio4** [comment]
Same issue on AOF3 NA server.  Confirmed it only happen when population the recipe from REI, and only for machine patterns.

Workaround is to manually create machine pattern recipes.

**Comment by GuichardVictor** [comment]
Hello, found the issue, it is only happening when the mod `InventorySorter-1.7.4-1.16.jar` is also installed. (please check if removing it works)

**Comment by justastranger** [comment]
This bug still occurs.

**Comment by GuichardVictor** [comment]
Have you tried without any other mod except the Applied Energistics one?

**Comment by justastranger** [comment]
No, but it only occurs in combination with inventory sorter 1.7.4

**Comment by Technici4n** [comment]
This was fixed on Inventory Sorter's end.

https://github.com/kyrptonaught/Inventory-Sorter/issues/35
