### ISSUE TITLE
Is there an upgrade alternative to the grindstone? 1.16.1

### ISSUE THREAD

**Issue by pokemongen4champ** [AppliedEnergistics/Applied-Energistics-2#4766]
Sorry if this is the wrong format, I didnt know where else to ask for help. Im at a point where im grinding stacks for dusts and the grindstone is just not cutting it, is there a compatible mod to get an upgrade in 1.16.1?

**Comment by shartte** [comment]
No there is currently no upgraded alternative by us. 
Mekanism added recipes back in 1.16.3.
Until then, you'll need a datapack to add appropriate recipes.

**Comment by shartte** [comment]
Here's the datapack that I used on 1.16.1:

[extrarecipes.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5360997/extrarecipes.zip)

**Comment by pokemongen4champ** [comment]
> Here's the datapack that I used on 1.16.1:
> 
> [extrarecipes.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5360997/extrarecipes.zip)

holy cow that worked! thank you so much
