### ISSUE TITLE
Custom Building broken due to Bad Gateway 502 error on modmaven.k-4v.nl

### ISSUE THREAD

**Issue by Moonded** [AppliedEnergistics/Applied-Energistics-2#4767]
Costum building stops due to 502 Server Error from modmaven.k-4u.nl.
Used was the latest build, downloaded via git.

Following packages are not accessible:

https://modmaven.k-4u.nl/net/minecraftforge/forgespi/3.1.1/forgespi-3.1.1.pom'
https://modmaven.k-4u.nl/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.pom
https://modmaven.k-4u.nl/net/jodah/typetools/0.8.1/typetools-0.8.1.pom
https://modmaven.k-4u.nl/org/spongepowered/mixin/0.8.1/mixin-0.8.1.pom
https://modmaven.k-4u.nl/net/minecraftforge/forge/1.16.3-34.0.8/forge-1.16.3-34.0.8.pom
https://modmaven.k-4u.nl/net/jodah/typetools/0.8.1/typetools-0.8.1.pom
https://modmaven.k-4u.nl/net/minecraftforge/forgespi/3.1.1/forgespi-3.1.1.pom

**Comment by shartte** [comment]
Does this still persist? I think this has fixed itself.
