### ISSUE TITLE
Crafting Subnetwork

### ISSUE THREAD

**Issue by mike-link** [AppliedEnergistics/Applied-Energistics-2#4769]
Using a network that contains crafting recipes and share its crafting cpu's and recipes with another ME network

**Describe the feature**
I would like to propose a new feature that is enabled when connected two ME Interfaces from different networks. Similar to how when a ME Interface is connected to a Storage Bus additional things occurs. In this instance, when two small form factor ME Interfaces from different networks as facing each other (with no other configuration), then this new feature is added. 

Once connected All crafting CPUs and crafting recipes and now available to be used by the other network. When a user requests a crafting task, the now shared crafting CPU would use items from the requesting network instead of its own. After the job is complete, it would then send the items back to the requesting network. If storage is not available it would store it in the ME Interface on the requesting network just like it would have normally. 

When the a network contains a ME Security Chest the user must have access to the crafting permission otherwise the crafting recipes do not show up. 

**Reasons why it should be considered**
This enables the ability to create crafting subnetworks. This would be beneficial on servers where people want to share machines they have created but not allow others to access their own storage networks.

**Comment by Moonded** [comment]
Wrong tab, this should be under "**Pull Request**" , as not being a issue.


I would move it if i would be able to.

**Comment by mike-link** [comment]
@Moonded really? Pull requests require code to be pushed in. When I looked at the docs it said to create a new issue and select 'feature request' Which is what I did.

**Comment by Moonded** [comment]
Well, could be wrong too. I only have pull reqeusts as "add this and that" in my mind. Welp. i can be wrong too :D

**Comment by mike-link** [comment]
If this is the wrong place @yueh would close it :D. Thanks for the info though.

**Comment by yueh** [comment]
The current behaviour of limiting crafting to a single network is intentional and won't be changed at all.
