### ISSUE TITLE
Dank Dock + storage bus not filling properly

### ISSUE THREAD

**Issue by Yoosk** [AppliedEnergistics/Applied-Energistics-2#4770]
**Describe the bug**
Dank storage allows for more than 64 items in their slots, while ae2 fills them with only 64 items instead of example 4096 ones per slot.

**To Reproduce**
Play AOF3 modpack on curseforge, try to fill any dank with ae2 storage bus.

**Expected behavior**
Ae2 should fill slots with more than 64 items per slot

**Additional context**
https://github.com/Tfarcenim/DankStorageFabric/issues/7
https://github.com/cakewhip/ezpas/issues/22
https://yoosk.ovh/lYL3uPnG.mp4

**Environment**
https://yoosk.ovh/SeBPjQ8M.txt

**Comment by yueh** [comment]
As described in the linked issues, it also applies to other transport systems. Even vanilla hoppers. So this is most likely a bug with the dank dock itself or even a limitation by how fabric handles inventory interactions currently. So most likely nothing on your side currently.
