### ISSUE TITLE
IE2 submod Applied Aerodynamics armor not accepting a charge. 

### ISSUE THREAD

**Issue by rusty0t** [AppliedEnergistics/Applied-Energistics-2#4772]
i place armor in the charger for a while and no charge is going to the pieces of kit. ample power provided.

**Describe the bug**
chargeable armor not accepting charge 

**To Reproduce**
place appliedaerodynamics armor (chestnut, horeshoes, etc) in charger.

**Expected behavior**

I expected armor to charge in standard AE2 charger

**Environment**
https://pastebin.com/LCF2NLwn

**Comment by shartte** [comment]
You'll need to direct that at Applied Aerodynamics. We don't support that mod, nor do we still support 1.7.
