### ISSUE TITLE
Fluid Dupe with Fluid Terminal and Fluid Tanks

### ISSUE THREAD

**Issue by NillerMedDild** [AppliedEnergistics/Applied-Energistics-2#4774]
Relayed from https://github.com/NillerMedDild/Enigmatica2Expert/issues/1832

**Describe the bug**
When extracting fluids from an Applied Energistics Fluid Terminal using a Thermal Expansion Resonant Tank, fluids stored in a 64k fluid storage cell duplicate themselves. I used a Portable Tank (Resonant) to remove 208 buckets of Thermal Foundation Sap from my system. I then hovered over the tank and the tooltip said the tank contained 376 buckets. I repeated the experiment with Lava, going from 13 buckets to 109.8 buckets and (off camera) Liquefacted Coal, going from 34.6 buckets to 202.6 buckets.

This bug also effects fluids stored in external containers with storage buckets such as Mekanism Tanks and Extra Utilities Drums, turning 56 buckets of milk into 232 buckets

**To Reproduce**
This video sums it up well: https://youtu.be/mTuJw8wV0cU

**Expected behavior**
Tanks to either be filled or extract the amount the AE system contains

**Additional context**
Same video as in "To Reproduce" section https://youtu.be/mTuJw8wV0cU

**Environment**

- Environment: 
Singleplayer
Forced crash: https://pastebin.com/V2DKLuBt

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.15 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.

**Comment by shartte** [comment]
I thought we fixed something very similar to this in 1.15
