### ISSUE TITLE
Chisel Mod Compatibility for Sky Stone Bricks

### ISSUE THREAD

**Issue by Tomodachi94** [AppliedEnergistics/Applied-Energistics-2#4775]
**How it should work:**
Allows you to use the Chisel mod's Chisel item to change the form of the Sky Stone blocks (bricks, etc).

**Additional Context**
[Chisel](https://github.com/Chisel-Team/Chisel)

**Comment by yueh** [comment]
There isn't even a release for 1.16 yet and I do not have any details about that happening. Once that is the case, we can revisit it potentially.
