### ISSUE TITLE
8.1.0 alpha 3 + Optifine 1.16.3 HD U G4 Pre 2 = No vanilla ore / block generation nor AE2 gens

### ISSUE THREAD

**Issue by KinamKrindar** [AppliedEnergistics/Applied-Energistics-2#4777]
**Summary**
Building a _toss together_ pack including a lot of different mods, started up world, and there were absolutely no generation of vanilla ores, nor blocks (IE: Granite, andesite, diorite, etc), as well as none of the AE2 blocks (no meteors, no quartz)

**The Issue**
After spending some time in a world, thinking everything was fine with the "pack" I'd tossed together, I realized I'd not run into any Iron. Got down to my normal mining level of 11, and realized I'd not run into any other ores except some random small patches of ores from some of the mods I'd added (including "ice and fire" and "Immersive Engineering" ores). I then realized after some time, that there was also no Diorite, Andesite, or Granite generating either. When at level 11, I'd hit a ravine, and saw no redstone, lapis, or any diamonds either. 

**Diagnosis / Troubleshooting**
My troubleshooting methods included turning off ALL other mods, leaving only AE2 on, and everything would work as expected (Vanilla generation correct, meteors generated instantly detected by meteor compass). Slowly added each of my desired mods back in, starting with Optifine because I enjoy shaders lately with my new rig... and immediately boom, no resources. Yes I was using OptiForge as well to load Optifine jar file, and the proper version of it. 
-OptiForge-MC1.16.3-0.3.4.jar
-OptiFine_1.16.3_HD_U_G4_pre2_MOD.jar

Disabling those two mods and loading the rest of my library of mods I wanted to have, and the world will load and generate the ores and everything properly. So, I'm not exactly sure WHAT Optifine is doing to cause the issue, but it's certainly farking with something.

I did attempt to load the game without OptiForge installed, and it did install and run Optifine, but again, had the same issue as before, of not having vanilla blocks generate, as well as not having any AE2 block structures (meteors) generate.  So, it really does seem like it's something going on specifically between that OptiFine version and AE2.

**Comment by shartte** [comment]
Optifine is not supported
