### ISSUE TITLE
Revert Liquid Requirement Changes for Crystal Growth

### ISSUE THREAD

**Issue by phit** [AppliedEnergistics/Applied-Energistics-2#4780]
**Describe the feature**

This https://github.com/AppliedEnergistics/Applied-Energistics-2/commit/88c9370e4f195b9fcf6e7b95b615dacb1e970c02 changed the liquid check for crystal growth to use the Minecraft tags for water (lava in the nether) instead of the prior isLiquid check. 

Having only the water tag as an option in the overworld is not a big deal, however in the Nether this makes growing Crystals impossible as Lava destroys any seeds.

Either this should be rolled back so you can use any liquid like it is still the case with crafting Charged Fluix [reference](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/main/java/appeng/entity/ChargedQuartzEntity.java#L84), or maybe make it so that lava doesn't destroy the seeds and the resulting item.

Thank you.

**Comment by yueh** [comment]
It also introduced a tag for allowing different fluids to be used and each modpack can design their own balance around it.
In case it is not enough control for various modpacks, we can still evalute more options. But for now it will stay this way.

**Comment by phit** [comment]
that tag doesn't seem to exist, at least searching for crystal_purification_medium in the repo finds nothing besides the commit message, am I missing something or was it missed in the commit?
