### ISSUE TITLE
Crafting isn't substituting other materials, even after checking subs = yes

### ISSUE THREAD

**Issue by poboy975** [AppliedEnergistics/Applied-Energistics-2#4781]
**Describe the bug**
Like the title, when I'm autocrafting a pattern, it's not using other substitutal materials, eg. oak or dark oak for making chests.

Using ae2-8.1.0-alpha.3
Forge version 34.1.23
Minecraft Java 1.16.3

**To Reproduce**
Seems to be consistant in 1.16.3 for me so far. I've had same issue in several worlds.

**Expected behavior**

I expect materials to be automatically substituted when available.
![Screenshot from 2020-10-17 11-49-40](https://user-images.githubusercontent.com/249487/96351244-0a96c780-106f-11eb-9236-0de824e4dc55.png)
![Screenshot from 2020-10-17 11-50-06](https://user-images.githubusercontent.com/249487/96351250-14202f80-106f-11eb-97be-1d74635df56b.png)
![Screenshot from 2020-10-17 11-50-21](https://user-images.githubusercontent.com/249487/96351259-1bdfd400-106f-11eb-95bf-5f82b26ff297.png)

**Additional context**

**Environment**

- Environment: 
https://pastebin.com/ZqTPJH3D

**Comment by yueh** [comment]
Currently this is not well supported since the switch from forge oredictionary to the new native tags system. This is now way more ambiguous and we can no longer look up alternative items in an easy way without an API change. So this needs to be at least postponed to 8.2.x or even 9.x depending on requiring an API break or can support it in a backwards comaptible approach.

**Comment by poboy975** [comment]
Gotcha, thanks. I can understand that. Would it be possible to add a popup text over the button, to indicate that it's not working well currently? So others can understand without having to add more bug reports?

**Comment by andrewsf** [comment]
I realize this is a much larger scope, but has anyone considered the concept of a "substitution pattern", allowing a specific set of substitutes? After crafting and configuring a pattern (somewhere), this pattern would substitute into 1+ slots of the recipe in the Pattern Terminal.

This is particularly helpful for cases wherein a recipe does not directly use a tag, but rather there are multiple recipes. Or if that is not possible, it is still useful to be able to whitelist certain items. For example, maybe I want to craft _Resourceful Bees_ bee hives using Water Honeycomb and Lava Honeycomb, but never craft them using Netherite Honeycomb.
