### ISSUE TITLE
Crash with optifine (fabric)

### ISSUE THREAD

**Issue by LordLettuce113** [AppliedEnergistics/Applied-Energistics-2#4783]
**Describe the bug**

Using AE2 Alpha 8.1.0 alpha.10 and the mods optifabric and optifine (latest version) the game crash when try to break AE2 cable on survival mode

**To Reproduce**

on survival mode, when optifabric and optifine installed breake AE2 cable with only hands

**Expected behavior**

Dont crash and breake the cable

**Additional context**

https://pastebin.com/8WNRywyu
**Environment**

- Environment: 
https://pastebin.com/8WNRywyu

**Comment by yueh** [comment]
Optifine is not supported.
