### ISSUE TITLE
Applied Energistics Receipe for Stages (fakenameplayer)

### ISSUE THREAD

**Issue by Nexow91** [AppliedEnergistics/Applied-Energistics-2#4786]
Hello Community, 

i have a problem. I have a receipe on stages mod i cant crafting in AE2 Grid. I think im need the Fakeplayers names in the stages cfg but i dont know the fakenameplayer. According to the stages mod developers, every mod author has his own fake name player how about ae2? [AE2]? somehow doesn't work, I really ask for help

**Comment by yueh** [comment]
We use the default one provided by forge/minecraft. But honestly I don't have an idea what name they use. Maybe the forge docs could mention it.
