### ISSUE TITLE
openGl error 1281 when i place any kind of cable in the world 

### ISSUE THREAD

**Issue by Dalltop** [AppliedEnergistics/Applied-Energistics-2#4787]
Using appliedenergistics2 8.1.0 alpha 3 with 1.16.3 forge 34.1.7, optifine 1.16.3 HD_U_G4 Pre2, optiforge 1.16.3 0.3.4, Chokapic 13v9 shaders, mekanism 10 and various mods. Anytime i put a cable in the world the openGL 1281 error begins to spam the screen,

**Comment by Ommina** [comment]
And..... without Optifine and shaders?  Does it persist?

**Comment by yueh** [comment]
Optifine is not supported.

**Comment by Dalltop** [comment]
Reset video settings and reloaded shaders and it was fine. Thanks!
