### ISSUE TITLE
Server Crash from Looping Power

### ISSUE THREAD

**Issue by Hexonoid** [AppliedEnergistics/Applied-Energistics-2#4788]
**Describe the issue**

Server crashes from power placing power acceptor and energy cell side by side, and then linking them with cable.

**Environment**

https://pastebin.com/e0SL53fZ
- Environment:

**Comment by mindforger** [comment]
Versions older than 1.15 are not supported anymore
Please open a new Issue when you can create the issue with a more recent version

but please also provide a screenshot of the setup to reproduce in future

(despite me closing the issue, please provide a screenshot for this version too)
