### ISSUE TITLE
Issue with external inventories when crafting manually

### ISSUE THREAD

**Issue by 016Nojr** [AppliedEnergistics/Applied-Energistics-2#4789]
**Describe the bug**
When crafting in the crafting terminal, if you shift click a crafting recipe, it only has a stack "available" from the external inventory when doing the crafting. 

**To Reproduce**
1. Connect to a large external storage, this case I am using Quantum Storage.
2. It's filled with Diamond Essence that is used to craft Diamonds, 9 Essence to 1 Diamond
3. Fill the crafting terminal, and shift click the recipe.
4. When crafting you will get 8 diamonds, 64+9( The 9 is already in the crafting grid)
5. After crafting there is one leftover essence from the single stack provided, even though there is more essence located in the system

**Expected behavior**
Craft a stack of the item, or use up the item that is stored in the external storage.

**Environment**
MC: 1.16.3
AE2: 3.1.0.alpha.3
Forge: 34.1.25

**Comment by yueh** [comment]
Can you try it with a different storage solution? The quantum storage ones are still a but clunky on how they operate.
The still have an output and input slot like the original DSU, which only accept 64 of a stack and it's constantly ticking to either move them to the internal storage or refill the output slot. So we could easily run into a case with only being able to extract 64 items at a time and then have to wait for it to tick again. Which is not something we account for at all (and probably will never).

But it can easily lead to something like having the 9 items stored inside the crafting terminal and then refill it with a full stack, which is not dividable by 9 and result in this behaviour.

**Comment by 016Nojr** [comment]
Will test more

**Comment by 016Nojr** [comment]
@yueh Just spoke with Gigabit (Author of Quantum Storage) and he said: 

> I will take a look at fixing that up, I have been wanting to change how the inventory works anyways and if it’s causing issue then more reason to get it done

I tested with normal chests and it works fine.

**Comment by yueh** [comment]
Ok, let's hope they can fix it in the future. Could even be caused by Forge as Quantum Storage reuses the simple implementation provided by them and I am not sure how how well it handles storing more than the max stacksize by default without potentially reimplementing most of it.

If that happens with another mod (with a more simple implementation) in the future, I can look into it again. But I really want to avoid handling some mods in a custom way. Just makes it more complicated and can introduce bugs later on.
