### ISSUE TITLE
ME Terminal and Fluix pipes have no block texture

### ISSUE THREAD

**Issue by ElliottF5522** [AppliedEnergistics/Applied-Energistics-2#4792]
Summary:
I started building my first basic ME storage system yesterday when I noticed that the Fluix pipes and any ME terminal had no block texture when placed. Other items such as the ME controller are fine when in hand or placed.

Issue Description:
I'm currently running on 1.16.3 (fabric) using the appliedenergistics2-fabric-8.1.0-alpha.10.jar file.
Expected behaviour is that these item should have block texture compatible with 1.16.3. Instead I can see the Purple and Black block texture whenever the item is placed.

**Environment**
Environment is a standard Minecraft world running 1.16.3 (not amplified or anything). This is being run with Fabric however, rather than Forge.
Forced Crash Report can be found below.
[crash-2020-10-25_01.00.42-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5433952/crash-2020-10-25_01.00.42-client.txt)

Thanks for any help with this guys!

**Comment by Mari023** [comment]
I also had this issue, removing sodium did fix it

**Comment by ElliottF5522** [comment]
> I also had this issue, removing sodium did fix it

Can confirm, yes removing Sodium does fix this. Thanks for your help!
