### ISSUE TITLE
[1.16.3] Automatic crafting does not work

### ISSUE THREAD

**Issue by ScottCTD** [AppliedEnergistics/Applied-Energistics-2#4793]
I did not get any reaction after click next or start button
![image](https://user-images.githubusercontent.com/35100768/97103503-dc0c9280-16e7-11eb-9be4-10635b57906d.png)

**Describe the bug**

appliedenergistics2-8.1.0-alpha.3.jar which is the latest one for 1.16.3
or if this version currently does not support auto crafting?
Sorry for troubling, but thanks!

**To Reproduce**

Just normally follow the step to do auto crafting

**Expected behavior**

Nothing happen

**Additional context**

none

**Environment**

Windows10 2004
Java 8u261

- Environment:

**Comment by ElliottF5522** [comment]
I've got a similar issue to this. I set up an auto-crafting system, when testing, I deposited 64 Oak planks and put in an encoded pattern with instruction on how to make sticks (2 oak planks). However when clicking on the sticks in the terminal, my game crashes with a java.lang.NullPointerException: rendering screen error.

I'm currently running appliedenergistics2-fabric-8.1.0-alpha.9 on Minecraft 1.16.3. I've attached the crash report below. Additionally the error also states "Exit Code: -1".

[crash-2020-10-25_17.59.31-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5435640/crash-2020-10-25_17.59.31-client.txt)

Thanks for any assistance guys!

**Comment by wirilome** [comment]
It doesn't work for me either. It's my first time with technological systems but I installed All of Fabric 3 which includes a bunch of them and I'm having fun. As some stuff are not really easy when you never used mods like that before, I'm using the videos from rbPlays All of Fabric to learn how to place some stuff.

I could automate the inscriber process, but I can't get any form of auto-crafting with the molecular assembler. Every single time, the process holds, saying that the craft is "scheduled".

As I'm not a pro at all, I made a copy of my world, destroyed the floor and took screenshots. 

![old-system](https://user-images.githubusercontent.com/73445985/97119747-7e417000-1712-11eb-89e5-4a71a1dedaf5.png)

I then tried to add a bunch of CPU and storage and all in creative mode to make sure I wasn't missing something, no change.

![creative-system](https://user-images.githubusercontent.com/73445985/97119742-7aade900-1712-11eb-86c9-516f06718807.png)

Here are the various interface screenshots
![molecular interface](https://user-images.githubusercontent.com/73445985/97119744-7d104300-1712-11eb-9fea-c3cb74c22fa2.png)

![crafting panel](https://user-images.githubusercontent.com/73445985/97119738-7386db00-1712-11eb-8cf5-e7a5f1b42721.png)

And here is the crafting state getting hug on scheduled. I can't launch anything else as it says that I don't have a crafting CPU available (hence the bunch I added in creative mode)

![crafting state](https://user-images.githubusercontent.com/73445985/97119741-77b2f880-1712-11eb-8b95-f27114d564bc.png)

My game doesn't crash but I can't use patterns at all except in the inscribers.

**Comment by mindforger** [comment]
in the pattern terminal, give the button in the middle right side with the furnace a click, it should change to a crafting terminal. You can encode crafting and processing pattern. The processing are made with the furnace symbol and only work as input/output list, the other type is an actual crafting pattern which works in combination with the assembler

**Comment by ScottCTD** [comment]
> in the pattern terminal, give the button in the middle right side with the furnace a click, it should change to a crafting table. You can encode crafting and processing pattern. The processing are made with the furnace symbol and only work as input/output list, the other type is an actual crafting pattern which works in combination with the assembler

Yeah sure, but actually in the 1.16.3 forge version, I cannot even get to the CPU GUI for auto-crafting...You could check my screenshot in the fist comment. Maybe my encounter was a special case?

**Comment by mindforger** [comment]
i am not sure if i am misunderstanding, but i was referring to your pattern used on the interfaces attached to the assemlber being possibly wrong coded to be processing instead of crafting pattern

**Comment by wirilome** [comment]
I think he was answering to me (as I did post screenshots of the patterns) and that did the trick. I saw in some messages people saying to make sure to encode the right way and I thought I had the wrong one but I had no clue how to switch between both. This mod isn't easy for newbies for sure and that part could use a tooltip.
Maybe you made the same thing as I did and encoded the pattern with the furnace icon showing and not the crafting station.

**Comment by mindforger** [comment]
oh sorry, when i opened the issue, i only saw your screenshots, since it was updated and did not scroll up :P
and i did not notice the OP was answering XD

**Comment by ScottCTD** [comment]
@mindforger 
Okay, sorry for my carelessness.
![image](https://user-images.githubusercontent.com/35100768/97181296-12c0d680-17d6-11eb-8872-71ecfcfff958.png)
![image](https://user-images.githubusercontent.com/35100768/97181384-2e2be180-17d6-11eb-888a-46c9b4b45822.png)
![image](https://user-images.githubusercontent.com/35100768/97181398-3421c280-17d6-11eb-922c-4a72beefba21.png)
![image](https://user-images.githubusercontent.com/35100768/97181442-400d8480-17d6-11eb-9f79-7f50389a53ec.png)



# Step by step
## Step1 click the "Craft ME Interface"
![image](https://user-images.githubusercontent.com/35100768/97181576-66cbbb00-17d6-11eb-84b5-dcef312c8f85.png)

## Step 2 this gui popped up
![image](https://user-images.githubusercontent.com/35100768/97181780-a2668500-17d6-11eb-89d4-d6f766b2403a.png)

## Step 3 nothing happen (No gui popped and no game crashing and no any reaction) after clicking the next ("start" when shift pressed because my screenshot hotkey) in the step 2 gui

**Comment by mindforger** [comment]
hmm strange enough, it looks right 
you also checked your pattern to be a crafting and not a processing pattern i would guess?

just in case, try to reprogram the pattern (and make sure the craftbench icon is showing), i will try to summon @yueh to confirm that version "appliedenergistics2-8.1.0-alpha.3.jar which is the latest one for 1.16.3" should be capable of autocrafting since the setup looks fine

**Comment by ScottCTD** [comment]
Okay, I will try later, my forge version is 34.1.25

**Comment by ProsperCraft** [comment]
Do you have FTB Quests installed? - https://github.com/FTBTeam/FTB-Quests/issues/469

**Comment by ScottCTD** [comment]
> Do you have FTB Quests installed? - [FTBTeam/FTB-Quests#469](https://github.com/FTBTeam/FTB-Quests/issues/469)

Yeah! After I removed FTB Quests, the auto-crafting works! Thanks!

And I should inform the developers @mindforger
