### ISSUE TITLE
Crafting status screen should show what interface is active

### ISSUE THREAD

**Issue by zigdon** [AppliedEnergistics/Applied-Energistics-2#4794]
**Describe the feature**

When looking at an ongoing crafting request, the status page shows what steps are currently active (in green). It would be nice if as a tooltip, it would give the name associated with the interface hosting the pattern for that step, so for instance it would be easy to tell when crafting dust if it is using a pulverizer, a grinder, or a crusher.

**Reasons why it should be considered**

The current way to figure out why a step is taking too long is to search for the pattern in the interface terminal and hope there is only one.

**Comment by yueh** [comment]
We currently don't track which tasks goes to which interface/machine to handle it and it is also virtually impossible to do it without enforcing major limitations on how you can setup autocrafting.

For example there is no requirement to which interface you have to return the items to. So there is no way to tell, if it was produced by the pulverizer or grinder by default. To do so, we'd have to change it so crafting results must be returned to the exact same interface the task was issued from.

And then you can still have cases like hooking a pulverizer and crusher to the same interface and splitting it between both. In this case we won't even know which one did just ffinish except it's returned to the exact same side of the interface it originally send the ingredients. Which means autocrafting will now only work with machines which can only input and output from the same side. Everthing else no longer works.

Or something silly like blocking all other crafting tasks for the same itemstack until a single one is finished and we can map to a single task. Which can easily lead to something like crafting one iron ingot every minute as the furnace needs some time, then the pipes delivering the item to the furnace and back to the interface also might not be instantaneous.

**Comment by zigdon** [comment]
I just meant there is already a name associated with each interface, since that's used in the interface panel. So if we know we have the pattern, I thought we could find the name of the interface holding it, and attach that to the crafting step. So it doesn't matter where the item is returned from, or even where it is being handled, just knowing what interface holds the pattern would be useful.

Totally get if that would be incompatible with the current design, so not going to reopen, but was wondering if my understanding was off.

**Comment by Ommina** [comment]
@zigdon

I get what you are saying, but I do worry about things getting wobbly if there are multiple interfaces with the same recipe (because the player wanted to take advantage of installed co-processors, for example.)  In such a case, we no longer have a 1:1 correspondence between 'interface' and 'now crafting'.  

In the past, there was some brief discussion surrounding improving the functionality of the interface terminal -- a 'show all' button or something to that effect.  That would at least let you search for all interfaces with the recipe in question.  I wonder if that might be a better solution to your problem.

**Comment by yueh** [comment]
The patterns aren't available client side and the crafting status is just a simple list of items without any other information. So we'd have to calculate that serverside, modify the itemstacks and have a custom tooltip. Which will result in various other issues once other mods also have their own extensions for item tooltips and so on.
As well as there can be multiple interfaces like omnina already mentioned. So we cannot design it around a single one but for a more or less infinite amount of interfaces. Or at least some reasonable amount like a dozen or two, which will then again lead to being completely ambiguous about which one might be broken.

All in all it would just be a very small QoL improvement to not have to open an interface terminal and  type in the item name. Which is in my opinion still not big enough to justify the amount of effort it would  take.
