### ISSUE TITLE
Can not register to a locked registry. Modder should use Forge Register methods.

### ISSUE THREAD

**Issue by poboy975** [AppliedEnergistics/Applied-Energistics-2#4796]
Just updated Forge today to latest update 34.1.32 After updating I tried to launch minecraft and this error occured. I've included a crash report below. Latest version of AE2 that is available to GDLauncher.

Game crashes on launch.

I do expect the game to load. It worked just fine before I updated Forge today.

Forge version 34.1.24 works as intended, but none of the updates since up to 34.1.32 work.

Here is a pastebin of my crash report. Which includes my environment and mods list.
https://pastebin.com/Yp8Ez9Rf

- Environment:

**Comment by Entoarox** [comment]
Can confirm, ran into the same issue myself.

**Comment by Swoaxx** [comment]
you managed to solve the problem ?

**Comment by Entoarox** [comment]
@Swoaxx I reverted back to 34.1.25, which still works while waiting for AE to provide a fix from their end.

**Comment by shartte** [comment]
Forge added more validation which breaks any mod who did structures similar to our approach.
