### ISSUE TITLE
Forge 34.1.24 Minecraft 16.3 no ores and no meteor are generated, the same for vanilla ores

### ISSUE THREAD

**Issue by Silbersurfer01** [AppliedEnergistics/Applied-Energistics-2#4798]
no ores and no meteor are generated, the same for vanilla ores. Minecraft 16.3 and Forge 34.1.24

**Comment by Spoke666** [comment]
and also, no villagers in minecraft 1.16.3 Forge 34.1.33

**Comment by Ommina** [comment]
That's lovely and all, but how are we concluding that any of this is an issue with AE2?

**Comment by yueh** [comment]
Duplicate of #4777
