### ISSUE TITLE
Crash when clicking on a craft on all terminals

### ISSUE THREAD

**Issue by GuichardVictor** [AppliedEnergistics/Applied-Energistics-2#4799]
**Describe the bug**
Crash when clicking on craftable items on the terminals.

**To Reproduce**
Click on any craftable items.
![image](https://user-images.githubusercontent.com/25057256/97496479-4849f900-1969-11eb-95af-f6ff0c93973d.png)

**Expected behavior**
Open the "CraftAmountScreen" GUI.

**Additional context**
The ME network is composed of: one me drive, one energy acceptor, me terminal (pattern), 4k crafting store, crafting co processing unit, charger, 5 inscriber (one has: one me interface, and 3 import buses on), one molecular assembler with one me interface.

Seems related to [issues/4765](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4765). However crashes happen on all type of crafts.

**Environment**

- Environment: 
Crash Report: https://pastebin.com/kGUVYPYR

**Comment by GuichardVictor** [comment]
Hello, found the issue, it is only happening when the mod `InventorySorter-1.7.4-1.16.jar` is also installed.

**Comment by shartte** [comment]
> 	mousewheelie: Mouse Wheelie 1.5.7+mc1.16.2-pre1

Mousewheelie is incompatible to my knowledge.

**Comment by GuichardVictor** [comment]
Mousewheelie works.
