### ISSUE TITLE
the book guides in the game

### ISSUE THREAD

**Issue by AlgorithmX2** [AppliedEnergistics/Applied-Energistics-2#48]
my friend suggested this idea (some fashion so Dalet), is convenient when there is no possibility to view the information about fashion on the Internet (guide).

Originally Posted by MrJek

This issue was migrated; For original details see http://ae-mod.info/Tracker/0494/

**Comment by Blue64** [comment]
That last idea could be possible I think by mixing Eureka API with InGameWiki API, the IGW idea was mentioned here:

https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/381

**Comment by thatsIch** [comment]
yes, but there will be always a request for having it only in AE2. Most of the problem rise from maintaining such content if new features are added.

**Comment by Blue64** [comment]
Could have a page for each recipe (sure would make meteors more useful, and assist in maintaining the recipes. Worst comes to worst, someone else could always make it an Add-on Mod using the Eurika API, IGW API & AE2 API as dependencies (or some other In-Game Book mods' API's, they're getting quite varied these days), then they could throw in a recipe to create their own blocks/panels to store all this data in (could even require a few ME Drives [slot it into the Block like an ME Chest] to store it all in). It's a very solid and fitting idea… I might even want to make this Mod myself xD it'd be a great mod to learn MineCraft Mod Creation with now that I think about it.

Would I have your permission y'all to create this Add-on Mod? I'll probably need to use your API obviously to figure out various compatibility issues and interaction functions (such as the ME Drive Slots)

**Comment by thatsIch** [comment]
@FireBall1725 wanted to do that part. He is currently moving and thus not available for such task. 

Feel free to do that, maybe ask him first, but I would doubt he would deny your request.

**Comment by Blue64** [comment]
I didn't see that posted anywhere, I'd need to learn Java first (nothing a few hundred hours of YouTube can't solve), but it's more than likely @FireBall1725 would be able to do it before me. I wouldn't mind collaborating with him, as I do have some ideas for this line of thinking. Good thing I asked first lol some people don't even ask, they just release it and y'all hear about it later when issues start showing up lol
