### ISSUE TITLE
Client Crash: Rendering overlay error with appliedenergistics2-8.1.0-beta.2

### ISSUE THREAD

**Issue by Impshial** [AppliedEnergistics/Applied-Energistics-2#4800]
1.16.3 Client crashes before main screen with error: java.lang.IllegalStateException: Failed to load description for particle appliedenergistics2:charged_ore_fx

Seems to be an issue running with Better Caves and Better Mineshafts mods. Removing them fixes the problem.

Crashlog: 
https://pastebin.com/zKMeEfrB

**Environment**
https://pastebin.com/zKMeEfrB

**Comment by OldManCraft** [comment]
I'm having the same issue. I do not have the better caves and mindshafts mods installed.

**Comment by shartte** [comment]
I just tested this with latest Forge and 1.16.3 and don't get this problem.
Was this sporadic? Did it happen everytime or just _sometimes_?

**Comment by Ommina** [comment]
I believe this is some other mod that has the error, and AE2 is getting blamed for it in the crash report.  I would be interested in seeing a debug.log.

**Comment by 04Slash** [comment]
This appears to be an issue with Yung's better caves and is probably the crash on startup fix that is in the Oct 27 v1.0.1 changelogs.
https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge/files/3094940
Changelog:
- Fix crash on startup with newer Forge versions (34.1.27 - 33)

You can figure out which mod is at fault by looking at the state of each mod. All but Yung's Better Caves is listed at 'COMMON_SET' where YBC is 'VALIDATE'. I don't know the reliability of this but out of the 4-5 times I have seen this issue it's always been the 'VALIDATE' mod's fault.

**Comment by shartte** [comment]
Alright, I'll close this for now. Please let me know if this persists.
