### ISSUE TITLE
AE2 Security Terminal - No Access after Reconnect

### ISSUE THREAD

**Issue by DerEnderman** [AppliedEnergistics/Applied-Energistics-2#4801]
**Describe the bug**
AE2 Security Terminal - No Access after Reconnect

**To Reproduce**
AE2 Security Termina Bug : https://streamable.com/sv4kt1 Fix income when?

**Expected behavior**
Let the Owner / User with access use the terminal!

**Additional context**
https://streamable.com/sv4kt1

**Environment**
Mniecraft 1.12.2 Modpack Revelation
Windows 10 Pro
Java 1.8.x

- Environment:

**Comment by shartte** [comment]
Sorry, we currently do not support any version older than Minecraft 1.15 anymore.

**Comment by DerEnderman** [comment]
Sad to hear can you then tell me where in the code i have to look to be able to fix it? can you show me that please to find a solution i am not alone with this bug.
