### ISSUE TITLE
my game AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768 but for my game has 14.23.5.2854 

### ISSUE THREAD

**Issue by halk6000** [AppliedEnergistics/Applied-Energistics-2#4802]
wo can send me link for old versions ap2 usage this forge. because i have old server dont have latest forge in serwer use hybrid

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.15 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.

**Comment by halk6000** [comment]
yueh ok but  hybrid servers have version 4 or more latency, so it's not my fault I want to have plugins on the server itself forge doesn't support it
