### ISSUE TITLE
Huge bandwith usage on terminal opening

### ISSUE THREAD

**Issue by clavierp** [AppliedEnergistics/Applied-Energistics-2#4805]
**Describe the bug**:
When I open my AE2 network trough a terminal or wireless terminal (WCT), my bandwith usage goes to max after few seconds and stay at max until I close the term (with ~10s delay).
Using Sampler, https://www.curseforge.com/minecraft/mc-mods/sampler, I narrowed it down to either AE2 or WCT CustomPayload. 2 runs gave me ~40Mb DL for approx 8s of term usage.
I have quite a huge AE2 network (4 drive bays with 40 max drives and a lot of external storage).
I disabled the AE2 channels.

No messages on the server's console.

**To Reproduce**
Open a crafting terminal on my server, i may provide a backup but it's 5 Gb

**Expected behavior**
Be able to play (not maxing my DL bandwith)

**Additional context**
[https://i.imgur.com/Q3Taiii.png](https://i.imgur.com/Q3Taiii.png)

**Environment**
- Environment: https://paste.ee/p/9vuij

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.16 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
