### ISSUE TITLE
No compass needle when in hand/inventory

### ISSUE THREAD

**Issue by L0rdLogan** [AppliedEnergistics/Applied-Energistics-2#4806]
**Describe the bug**
8.1.0 alpha 11 Fabric - no compass needle on the meteorite compass when in your inventory/in-hand. Placed on the ground the compass needle shows and gives a direction

**To Reproduce**
Get compass in your hand/inventory

**Expected behavior**
Compass needle to guide the way

**Additional context**
https://i.imgur.com/TsFrVBs.png - in inventory
https://i.imgur.com/XFtzCDs.png - in hand
https://i.imgur.com/E2h5GDb.png - on ground

**Environment**
Forced crash-report: https://paste.ee/p/Rr0XD

**Comment by spyway1** [comment]
I have a similar problem.
Only my compass is not displayed at all, or it is erroneously in the shape of a square.
![2020-11-10_22 03 31](https://user-images.githubusercontent.com/74270301/98733440-cd3d0580-23a0-11eb-97f1-96012380a191.png)

**Comment by insertt** [comment]
From what I've tested, compass needle is missing because of Sodium, so try to reproduce it without it being loaded into the game.

**Comment by L0rdLogan** [comment]
> From what I've tested, compass needle is missing because of Sodium, so try to reproduce it without it being loaded into the game.

Without sodium, it's showing fine 👍 
![2020-11-15_10 45 31](https://user-images.githubusercontent.com/5092548/99182894-dc6cdc00-272f-11eb-95e9-f83037fe3710.png)

My FPS is, a lot worse with Sodium, looks like I have a choice to make (find the things I need without sodium, once I have them, put sodium back in)

**Comment by L0rdLogan** [comment]
Also, It kind of works in 1.16.4 - hope there's an update soon

Without sodium: 
![2020-11-15_11 09 25](https://user-images.githubusercontent.com/5092548/99183400-581c5800-2733-11eb-9a17-797bc5c0d9d9.png)

With Sodium: 
![2020-11-15_10 42 07](https://user-images.githubusercontent.com/5092548/99183409-67030a80-2733-11eb-8f34-c5a82585b882.png)
