### ISSUE TITLE
1.12.2 forge client crash: NoClassDefFoundError

### ISSUE THREAD

**Issue by Pookaamon** [AppliedEnergistics/Applied-Energistics-2#4807]
1.12.2-forge-14.23.5.2854 client crashes with the error: "The game crashed whilst there was a severe problem during mod loading that has caused the game to fail, Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Energistics 2 (appliedenergistics2)"

Here is the crash report: [https://pastebin.com/4JvX4zSC](url)

Thanks in advance

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.16 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
