### ISSUE TITLE
ME Interface should support the "Only craft, do not use stored items" button from the Crafting Card, like the Export Bus does

### ISSUE THREAD

**Issue by Jack-McKalling** [AppliedEnergistics/Applied-Energistics-2#4808]
**Describe the feature**

If you insert a Crafting Card into an ME Interface, a new button should show up with which you can toggle between "use stored and crafted items" and "only craft items" modes. Exactly like the Export Bus already does (although can't remember the exact tooltip)

If you would choose to toggle that button, it would alter the crafting behaviour of the ME Interface from its current behaviour, and have it only craft items and never use already stored items, when you specify that it should always keep a stack of a certain item.

**Reasons why it should be considered**

The reason why this should be considered is because it would make the function of the Crafting Card consistent between Export Buses and ME Interfaces. This crafting mode button already exists on the Export Bus, but is missing on the ME Interface.

**Additional Context**

![interface with crafting card](https://user-images.githubusercontent.com/14236702/97857462-14225f80-1cfe-11eb-9ee4-92aaa91a4161.png)

**Comment by yueh** [comment]
While it might be useful in some very rare cases, it is simply not worth the performance issue.

Interfaces cannot scale dynamically like export buses on failed jobs as they have various other tasks to do. So while an export bus can scale between ticking every 5 to 60 minecraft ticks (by default), interfaces need to tick every tick. Which means a single interface which cannot craft the required items, will put about the same load as 60 failing export buses on a server.

If it can satisfy the request from the network itself, it can at least mostly idle as it will not deal with an infinite amount by default but just up to the storable amount compared to the export bus.

**Comment by Jack-McKalling** [comment]
Thanks for your reply. I understand the problem.

What made me look for this solution, is that the interface doesn't need capacity cards to get to the full 9 slots, and when compared to if you do use capacity cards with the export bus, the interface would not have the max speed penalty that the export bus would have. I guess both should have their own pros and cons. I'll use the export bus to do this task instead then and leave the interface for the other tasks that it has.
