### ISSUE TITLE
Charged Certus ore renders wrong when both Better with Mods + CTM are installed

### ISSUE THREAD

**Issue by KotetsuRedwood** [AppliedEnergistics/Applied-Energistics-2#4812]
Charged Certus ore renders wrong in-world when Better with Mods and ConnectedTexturesMod are installed at the same time. Removing either mod fixes the problem - might actually be related to one of them.

**Describe the bug**
With both of the other mods installed, Charged Certus Quartz ore's texture is replaced by diagonal lines. From personal testing, the bands change based on other mods installed.

**To Reproduce**
A modded instance with only the specified mods installed causes the rendering bug.

**Additional context**
![image](https://user-images.githubusercontent.com/10330701/98298033-41486980-1fad-11eb-8805-ac04893a684c.png)

**Environment**
Forced Crashlog:
https://pastebin.com/XpLq8iJn

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.16 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
