### ISSUE TITLE
ME Cable Crash - Tesselating block model

### ISSUE THREAD

**Issue by Kuhnmann** [AppliedEnergistics/Applied-Energistics-2#4813]
Hi there 

as soon i will click on a ME Cable the Game Crash.
I  am not to good in codeing and don't understand the Crash log..

Can anyone help me?

[crash-2020-11-06_14.55.05-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5501688/crash-2020-11-06_14.55.05-client.txt)

Thank you!

**Comment by yueh** [comment]
Please try without optifine.

**Comment by Kuhnmann** [comment]
Hi yueh - thank you for your respons. it works, but now it just looks boring ;) 
Is there a way to have a Optifine work with my config? i love to use a shader...

Thank you!

**Comment by yorii** [comment]
This is fixed in latest version of Optifabric. Any similar crashes in the future are best reported to the Optifabric github: https://github.com/Chocohead/OptiFabric

**Comment by Kuhnmann** [comment]
Thank you very much! All is working fine - glad that you helped me!

**Comment by yorii** [comment]
> Thank you very much! All is working fine - glad that you helped me!

Do note that ME Chests still produce a crash with optifine, but hopefully that will be solved soon too.

**Comment by Chocohead** [comment]
Whilst I've fixed this in OptiFabric, for reference the `null` which is passed in here:
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/52f3bf8c1b221381dc5d4518dbd3d0cc17d28f78/src/main/java/appeng/client/render/tesr/ChestTileEntityRenderer.java#L147-L148
should be the sprite from `quad`. There's already a pair of accessor mixins which exist in AE2 which would work to allow it to be accessed (as it is protected field on `BakedQuad`):
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/52f3bf8c1b221381dc5d4518dbd3d0cc17d28f78/src/main/java/appeng/mixins/BakedQuadAccessor.java#L9-L15
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/52f3bf8c1b221381dc5d4518dbd3d0cc17d28f78/src/main/java/appeng/mixins/unlitquad/BakedQuadAccessor.java#L9-L15

**Comment by VieLassiel** [comment]
I'm playing 1.16.3 and using v1.7.0 and I'm having the same issue.

**Comment by Chocohead** [comment]
It was fixed in OptiFabric v1.8.8 so that or any later version should have you going fine. All the v1.8.x versions work from 1.16.1 to 1.16.4 in case that wasn't clear.

**Comment by shartte** [comment]
Yeah we should copy over that sprite nevertheless. I even left a FIXME FABRIC heh.

**Comment by VieLassiel** [comment]
> OptiFabric v1.8.8

I updated to the latest version 1.8.10 and it still has the same issue.

**Comment by Chocohead** [comment]
> 
> 
> Yeah we should copy over that sprite nevertheless. I even left a FIXME FABRIC heh.

That would be the best solution

> 
> 
> > It was fixed in OptiFabric v1.8.8 so that or any later version should have you going fine. All the v1.8.x versions work from 1.16.1 to 1.16.4 in case that wasn't clear.
> 
> I updated to the latest version 1.8.10 and it still has the same issue.

If you're still getting crashes even with the newest version I'll need the crash report to see what else can be done
