### ISSUE TITLE
Cannot withdraw PSI CAD from ME storage. 

### ISSUE THREAD

**Issue by alphaNumeric01** [AppliedEnergistics/Applied-Energistics-2#4816]
**Describe the bug**
When you insert an CAD from the PSI mod in 1.15.2 it cannot be withdrawn through crafting terminal or me chest. 

**To Reproduce**
Create a CAD through the PSI mod, (it must be assembled from parts to create a Casting Assistant Device). Insert it into the ME network and attempt to withdraw it.

**Expected behavior**
The item is retrieved without problem. 

- Environment: 
https://pastebin.com/sDd4qG3x

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.16 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.

**Comment by Rerumu** [comment]
I can confirm this issue still happens in 1.16.4 with mod version 8.1.0.

**Comment by NeoInversion** [comment]
A friend told me they just had this problem happen to them, playing on 1.16.4.

**Comment by have-a-boy** [comment]
I can also confirm that this is still happening in Minecraft 1.16.4.
