### ISSUE TITLE
mirror shulker boxes placed by the formation plane

### ISSUE THREAD

**Issue by Quezler** [AppliedEnergistics/Applied-Energistics-2#4817]
**Describe the feature**

the top of the shulker box should face away from where the formation plane is.

**Reasons why it should be considered**

currently the top of the shulker box faces the formation plane, preventing it being opened.

**Additional Context**

![2020-11-08_13 29 55](https://user-images.githubusercontent.com/3179271/98464964-84c9f000-21c6-11eb-99a8-20b57acfdd80.png)

(and yes, i am aware that as with a lot in ae2 it "can" be done with the existing tech like a dispenser, but this seems QOL)

**Comment by Technici4n** [comment]
Same as #5655: the formation plane logic is very general (it just tries to use the item), and we don't want to support dozens of special cases.
