### ISSUE TITLE
Wrench Support

### ISSUE THREAD

**Issue by 016Nojr** [AppliedEnergistics/Applied-Energistics-2#4818]
I did look at #4763 but I think this deserves a request of its own because I guess it may require some more background work. 

It would be nice if all the wrenches added in the game could work cross-mod avoiding having to deal with multiple wrenches. CoFH  tags their wrench with `forge:tools/wrench`, in my opinion all mods should be using the same tag.

This is an oppurtunity for mods to fix a long-lasting "issue" that we "shouldnt" need to worry about.

**Comment by yueh** [comment]
This is pretty much pointless besides allowing any wrench to be used for crafting recipes.

Even CoFH still requires that their own interfaces [IDismantleable](https://github.com/KingLemming/1.16/blob/895cb1dface763e8f50044151532fe5cfbfaa32b/CoFHCore/src/main/java/cofh/core/block/IDismantleable.java) or [IWrenchable](https://github.com/KingLemming/1.16/blob/895cb1dface763e8f50044151532fe5cfbfaa32b/CoFHCore/src/main/java/cofh/core/block/IWrenchable.java) have to be implemented on 3rd party blocks to be wrenchable. A tag won't have it magically work.

The same is true for own [IAEWrench](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/1dc9bc27c736d221b63c3ec621676f72bad125ad/src/api/java/appeng/api/implementations/items/IAEWrench.java). If the item itself does not implement it, it will not work. Say in case CoFH would want to add support for our wrench

In both cases the wrench is the active part acting on a block and not the block reacting to an item being interacted with them.
It is probably possible, but that will eliminate many more advanced uses cases. E.g. if you have a wrench which could toggle between multiple modes like dismantling, rotating, or changing the I/O if a specific side, this will no longer be possible.

Our goal is still to depend on only forge (and of course minecraft). With `@Optional` now no longer being a thing, We would have to introduce a hard dependency on cofh core. And probably any other mod adding their own wrench. Same for CoFH or any other mod now needing AE2 as hard dep.

If you want actual cross mod wrenches, you have to convince forge to provide a common interface for it to at least provide the most basic features like can a block be wrenched by a specific player and to actually wrench it. E.g. there might still be the need to limit interactions with a wrench to the player having placed a block and so on.
