### ISSUE TITLE
[1.16.3] Dedicated server crash on changing settings on a fuzzy card on an export bus. java.lang.IllegalArgumentException: fromKey > toKey

### ISSUE THREAD

**Issue by ProsperCraft** [AppliedEnergistics/Applied-Energistics-2#4821]
**Describe the bug**
When changing the settings on a fuzzy card a player caused the dedicated server to crash.
The server crashes now when the player logs back in without any interactions.

**To Reproduce**
Set up a dedicated server and connect and change the export bus with a fuzzy card in it
Change the settings on that card.

I have uploaded the entire server zip- 
https://www.dropbox.com/s/999mjc6bi4htgz4/ae2crashmodpackworld.tar.gz?dl=1

**Expected behavior**

**Additional context**
Crashlog-
https://gist.github.com/ProsperCraft/29f457e1e6d33e42122482e76d214a15
Server log-
https://gist.github.com/ProsperCraft/7242da265769f53f9f6c3818d42295e3

Second crash on player logging in -
https://gist.github.com/ProsperCraft/4b33d9db2f4f41485947825d7f24b45c

A third crash from a different player going to the area-
https://gist.github.com/ProsperCraft/bda5d8a95943a1edec09c38376bf1ca1

**Environment**

- Environment: 
Centos 7
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (build 1.8.0_262-b10)
fabric-1.16.1-geckolib-2.0.0
Modpack - [The Adventures of Halk for 1.16](https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk) Version 0.11
appliedenergistics2-fabric-8.1.0-alpha.12

**Comment by Badtz13** [comment]
Can confirm this issue also occurs on forge builds.

**Comment by JonathanCSmith** [comment]
Experienced this myself. I loaded a backup that was post fuzzy filter installation but pre hard crash and now I cannot access any export & import busses...

**Comment by Cerbrus** [comment]
I've had this same issue.

[crash-2021-01-16_23.22.52-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5825220/crash-2021-01-16_23.22.52-server.txt)

The setup:
A 10 priority storage bus with a fuzzy card, on an Iron Chest.  
The storage bus is configured to store stone swords with 1 durability missing (130/131).
Then I open up my wireless AE system and start searching for stone sword. Before I get to type "Sto", the game crashes.

**Comment by liamchaps** [comment]
https://paste.shockbyte.com/xapogukovojebobocula.rb
Same problem here, had an export bus going into a trash can with a fuzzy card with armor

**Comment by tyler489** [comment]
Can confirm also occurs  forge issue https://termbin.com/j21f

Specifically i had some hammers from excompressium in my AE that i was exporting because they were stuck in the terminal unable to be removed. so i set a fuzzy card to match any and it crashed.

**Comment by ConanODoyle** [comment]
Can this be resolved by implementing `Comparable<T>` in the `ItemDamageBound` static class, overriding `compareTo(ItemDamageBound b)` to return `Integer.compareTo(b.itemDamage, this.itemDamage)`? https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/c04e7c363e69775dcab912e5e3d825105de96b0d/src/main/java/appeng/util/item/FuzzyItemVariantList.java#L65-L71

**Comment by Technici4n** [comment]
It might be fixed with the new **VERY EXPERIMENTAL PLEASE MAKE A BACKUP** 8.3.0-alpha.1 build given that it merges many forge branch commits, but that probably has other bugs as well... That will probably have to wait until we manage to get more stable 8.3.0 builds... If you want to help by testing them out, please go ahead :)

**Comment by irunatbullets** [comment]
A player reported this crash on a single player world with AOF3 2.7.4.

This setup:
![unknown](https://user-images.githubusercontent.com/344908/119985533-0d717780-bfc3-11eb-99ed-30009a189dc9.png)

https://hastebin.com/bosehogika.yaml

I'll check if they want to try the experimental build.

**Comment by Technici4n** [comment]
Fixed indeed in the experimental builds.
