### ISSUE TITLE
Automating Inscribers

### ISSUE THREAD

**Issue by McCalihan** [AppliedEnergistics/Applied-Energistics-2#4823]
I tried to set up a automated inscriber build for applied energistics 2. It refuses to work. Any help? 

**Describe the feature**
Won't craft anything I request it. I tried everything when it came to cables and placing the crafting storage. It still won't work. 
I looked up videos on to automate inscribers but it wouldn't work on my end. I need help please.

**Comment by mindforger** [comment]
please use that template when you create an issue, it tells you what infos we need to help you, other than that your help request is like asking a car workshop via mail "my car is beeping for 5 times every minute how to fix"

nobody can tell unless you tell brand, type, build year and what you have done to make it beep

to be precise minecraft version, forge version, version of AE2, other mods involved and a picture of your setup would be nice
(you can create a debug crashlog by pressing and holding F3 + C, this log tells all details of your setup but please paste ist via pastebin or similar)

**Comment by yueh** [comment]
The issue tracker is for reporting bugs or feature requests, but not the right place for build guides.
