### ISSUE TITLE
Device missing channels, when it's definitely not

### ISSUE THREAD

**Issue by Oreo456** [AppliedEnergistics/Applied-Energistics-2#4826]
**Describe the bug**
I had a whole section of my network up and running, there were plenty of channels and I had chunk loading and everything. At some point a bunch of the devices just decided to stop working. I tried to cut down on the number of devices, I checked my routing and everything and nothing fixes it. It's random what works and what doesn't too. For example on the same cable branch I can have an import bus that connects fine, but a fluid export bus in a different spot that acts like it doesn't have an available channel, even if I get rid of the import bus so it is the only device on that branch.

**To Reproduce**
I have not been able to reproduce it myself in different worlds. All the help I can really give on that part is the subnetwork that it's on is coming out of a p2p bus.

**Expected behavior**
I just expected the devices to be working fine

**Additional context**
![2020-11-15_20 56 20](https://user-images.githubusercontent.com/56943177/99205061-7317b800-2785-11eb-8712-4c83cbebb412.png)
![2020-11-15_20 56 30](https://user-images.githubusercontent.com/56943177/99205067-74e17b80-2785-11eb-9ba0-7e5e573c7b92.png)
![2020-11-15_20 56 41](https://user-images.githubusercontent.com/56943177/99205070-76ab3f00-2785-11eb-825f-3d0d75143458.png)
![2020-11-15_20 56 50](https://user-images.githubusercontent.com/56943177/99205074-790d9900-2785-11eb-9b65-7b4da825fd05.png)
![2020-11-15_20 57 01](https://user-images.githubusercontent.com/56943177/99205077-7a3ec600-2785-11eb-9f5b-628cc94161ed.png)
![2020-11-15_20 57 40](https://user-images.githubusercontent.com/56943177/99205082-7b6ff300-2785-11eb-9019-2879a96cb698.png)

The device that is working and the device that isn't are on the same branch of cable

If there are any more screenshots or anything you need let me know

**Environment**
I'm using the most recent stable 1.12.2 release

- Environment: 
https://gist.github.com/Oreo456/44f599dee711d5f77f238c49c1405618.js

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.16 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
