### ISSUE TITLE
Can't craft some blocks

### ISSUE THREAD

**Issue by WittgensteinS** [AppliedEnergistics/Applied-Energistics-2#4828]
I have a problem regarding some recipes of the mod such as the vibration chamber, the necessary recipe appears in the jei but when I move it to the crafting table the desired item does not appear, there are some that also cannot be but I could not identify.

Version MC: 1.16.3
Version mod: 8.1.0 beta 2
Version forge: 34.1.35

The item i want to make
![image](https://user-images.githubusercontent.com/74155498/99327752-619fe000-2859-11eb-957c-14c22e3fb748.png)
The result
![image](https://user-images.githubusercontent.com/74155498/99327771-6a90b180-2859-11eb-90d9-1439ec5bdaac.png)

Now with the crystal growth Accelerator
![image](https://user-images.githubusercontent.com/74155498/99327840-96139c00-2859-11eb-92fb-2957c23af160.png)
![image](https://user-images.githubusercontent.com/74155498/99327852-9ad85000-2859-11eb-81aa-4d03d7a9d877.png)

**Comment by yueh** [comment]
Could you please forward this to your server or modpack?

This looks more like your server has disabled or changed these recipes while still sending the incorrect recipes to the client.
I am currently not aware of any mod doing it, but I would not be surprised when there is one doing it. Would certainly be helpful to know it.

**Comment by WittgensteinS** [comment]
Yeah, i solve the problem, it was the pmmo mod (https://www.curseforge.com/minecraft/mc-mods/project-mmo).

I restart the pmmo-common.toml (config) and works properly both mods.

The mod has a restriction on what is crafting and smithing, so inside the config making the recipe not work.
