### ISSUE TITLE
Sub-Crafting Monitor

### ISSUE THREAD

**Issue by EpicPuppy613** [AppliedEnergistics/Applied-Energistics-2#4834]
**Describe the feature**
The crafting monitor shows the current task assigned to the crafting cpu, and the items it needs to craft. A cool idea would be being able to see the subcrafts needed for a crafting task. For example, for a crafting table, the normal crafting monitor would show the crafting table, but the sub crafting monitor would show the crafts needed to make it, in this case, planks. A wrench on a crafting monitor could convert it to a subcrafting monitor or adding another recipe for a separate block.

**Reasons why it should be considered**
The subcrafting monitor would be a cool addon for bases where the crafting cpus are in plain sight, and crafting monitors are used to keep track of crafting tasks rather than the crafting task gui.

**Comment by Ommina** [comment]
Crafting co-processors allow for multiple combines to be happening at the same time -- how would the sub-crafting monitor select which, of a possible many, current craft to display?

**Comment by yueh** [comment]
A crafting job is not really linear (in various ways). It can easily craft multiple different items in parallel and these are not really sorted in a useful way. So they actually displayed item can change easily change many times per tick. Which also means we have to constantly synchronize the whole state to every client multiple times per tick, basically each time a single task is completed.

So in many cases it will not even display anything useful as anything besides bulk items will not be visible at all or just for a fraction of a second as well as introduce a major bandwidth increase for servers, which is certainly something to be avoided.
