### ISSUE TITLE
1.16.4 [CRASH ON LAOD UP] 

### ISSUE THREAD

**Issue by SDUBZ** [AppliedEnergistics/Applied-Energistics-2#4835]
appliedenergistics2) encountered an error during the common_setup event phase
ยง7java.lang.ExceptionInInitializerError: null , makes it crash on laod up
**Describe the bug**

appliedenergistics2-8.2.0-alpha.1
**To Reproduce**

load up with forge 35.1.0 this also happens on earlier versions of forge 1.16.4
**Expected behavior**

Thought it would load up no problems

**Additional context**
[crash-2020-11-21_17.48.02-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5577149/crash-2020-11-21_17.48.02-client.txt)

[latest.log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5577150/latest.log)

**Environment**

- Environment: 
singplayer
appliedenergistics2-8.1.0 loads up no problems

if you need any more info let me know :)

**Comment by shartte** [comment]
Can you please try 8.2.0-alpha.2?

**Comment by SDUBZ** [comment]
yes it worked
