### ISSUE TITLE
HWYLA Integration

### ISSUE THREAD

**Issue by UnhappyCodings** [AppliedEnergistics/Applied-Energistics-2#4838]
Add an Integration to let HWYLA display data from Blocks of AE2

**Describe the feature**
Display for example the number of channels used/free so for example: "Channels: 5/32"
Power Integration for all Blocks and more...
Like in the older versions

**Reasons why it should be considered**
Because it was in earlier versions and very very helpful

**Additional Context**
https://www.curseforge.com/minecraft/mc-mods/hwyla
https://github.com/TehNut/HWYLA

![grafik](https://user-images.githubusercontent.com/49205934/100076737-d36fbf00-2e41-11eb-8a7d-349f94df36f7.png)
![grafik](https://user-images.githubusercontent.com/49205934/100077107-3d886400-2e42-11eb-97e2-0f57734c322a.png)
![grafik](https://user-images.githubusercontent.com/49205934/100077314-80e2d280-2e42-11eb-8e8a-ab686937aaa2.png)

**Comment by shartte** [comment]
This integration was removed because HWYLA's Maven is garbage and regularly causes our builds to fail.
