### ISSUE TITLE
Crash when MI pipe enters inscriber 

### ISSUE THREAD

**Issue by TheFluffyDisneyGeek** [AppliedEnergistics/Applied-Energistics-2#4840]
**Describe the bug**
Rendering crash when a Modern Industrialization pipe enters an inscriber.

**To Reproduce**
Place inscriber on the ground, put hoppers inputting into it, then put an MI pipe in, it will crash if it can enter.

**Additional context**
Crash report:
https://pastebin.com/d303p1eP

**Environment**
Fabric version, Specifics in the crash log.

**Comment by ImJustMatt** [comment]
Want to add, playing the same pack (AOF3) and have a similar crash when a modded fluid is in storage and I try to partition in a Cell Workbench. I can replicate and post logs if that helps.

**Comment by Technici4n** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/b81b383ef26a5a41f98250e41e705129acf3742b/src/main/java/appeng/client/render/tesr/InscriberTESR.java#L206

I think that you should make sure that `model.getQuads(null, null, new Random())` is not `null`. MI (and probably other mods) assume that the method will never called, and prefer returning `null` over returning an empty list.

**Comment by Technici4n** [comment]
Should be fixed in 0.8.2-alpha.3.
