### ISSUE TITLE
Spatial Storage issue

### ISSUE THREAD

**Issue by slink7** [AppliedEnergistics/Applied-Energistics-2#4842]
**Describe the bug**

Powering a Spatial IO Port with redstone won't do anything, there's enough energy and Spatial pylons are toggled.
Using an 'Unformatted' 16^3 Spatial Storage Cell.

**To Reproduce**

Use the Spatial IO Port casualy

**Expected behavior**

I was expecting the structure in the SCS to get stocked in the Cell

**Environment**

- Environment: 
 Using Forge 35.0.18 and AE2 8.1.0 on minecraft 1.16.4

**Comment by bls220** [comment]
I also had this issue. I was using ATM6 (1.3.1)

I did some testing and it seems to be related to an integration with biomes of plenty; as the issue only occurred when using the biomes of plenty level generator.

**Comment by slink7** [comment]
Thank you !
I uninstalled biome o' plenty and it worked in solo however on my
server the problem is still there even though i deleted biome o'plenty and
restarted it with no problems.
I wasn't even using biomes o plenty's generation on the server so it's weird

**Comment by yueh** [comment]
Does it produce an error logged in the server log once applying the redstone signal? That might help to identify the issue.

**Comment by rwdj** [comment]
@yueh I have the exact same problem with the exact same symptoms mentioned.

The log shows nothing when applying the redstone signal. Debug.log and latest.log included. 

Minecraft: 1.16.4
Forge: 35.1.29
Biomes O' Plenty: 1.16.4-13.0.0.426
Applied Energistics 2: 8.2.0-beta.2

Procedure:
* Use biomes o plenty
* Create a single player world
* Setup the Spatial Containment Structure
* Observe it fail to store a block.
* Remove biomes o plenty.
* Relaunch minecraft
* Load the same world
* Observe it succeed to store the block.

**Comment by rwdj** [comment]
https://github.com/Glitchfiend/BiomesOPlenty/issues/1750

**Comment by yueh** [comment]
As far as I can tell this is purely an BOP problem. With their custom worldtype they only add their custom overworld + nether + end, but no other world ([BOPDimensionType.java#L59-L65](https://github.com/Glitchfiend/BiomesOPlenty/blob/f59bc74869710050955b27fd89feb0fe36c91e05/src/main/java/biomesoplenty/common/world/BOPDimensionType.java#L59-L65)).

So any mod adding new worlds can probably fail.

**Comment by rwdj** [comment]
If I'm understanding you correctly, AE2 isn't able to create/use extra dimensions because BoP doesn't allow the creation of extra dimensions.
So BoP is incompatible with mods like Twilight Forest (when/if updated), AE2 and more. Sad. 
At the very least, I can get around this by temporarily turning on BoP world gen, pregenerating the world and turning it off. Alternate dimensions (multithreading) is too important to me to not go through this work. Thank you very much!

**Comment by shartte** [comment]
We could potentially change our approach to always just add the spatial world, but currently it is rather that we don't support any but the normal world type for spatial, since we add our dimension to the default world type, rather than globally. In essence we do this to avoid the annoying "experimental features used" warning screen when loading into the world. If we were to use a JSON file for the dimension_type, that's what you'd get.

**Comment by yueh** [comment]
I do not think that would actually help. When looking at the BOP tracker there are a bunch of reports with other mods not being able to add dimensions, biomes, etc.

As far as I can tell, BOP replaces the whole `SimpleRegistry` used to populate every dimension but the overworld without taking other mods into account. I would even guess that registering new dimension with a datapack has a good chance of not working at all.

Further while forge seems to add an event to replace the world type completely (which provides the simple registry), there seems to be no event to register custom dimensions at all. Only the dimension type usable as template. Or something which would indicate that Forge merges the vanilla one with whatever is provide by any mod replacing the world type. 

So for now I assume it either forge needs to provide a way to register dimensions to any `DimensionGeneratorSettings` globally or BOP needs some sort of API to register them, but that would be a mess for any other mod as it needs explicit BOP support and support for every similar mod. Or each BOP like mod has to add support for every other mod adding dimensions to itself.

**Comment by shartte** [comment]
I think the datapack dimensions are added later, the method they override is the "default dimension registry" as far as I know.

**Comment by plebania** [comment]
Mabe I'm just stupid and I'm using it wrong, but i have same problem. I'm using forge 35.1.29 and ae2 8.2.0
