### ISSUE TITLE
AE2 Crashing my minecraft whenever I load it up.

### ISSUE THREAD

**Issue by Kooseh** [AppliedEnergistics/Applied-Energistics-2#4843]
I am trying to make my own modpack and whenever I load up minecraft it crashes ([crash log](https://pastebin.com/LFnNtUCm)). would appreciate the help. Thanks.

**Comment by mindforger** [comment]
it would be beneficial for you to learn how to read crashlogs

>Caused by: java.lang.IllegalArgumentException: Failed to register dimension for id 2, One is already registered

Check your cobfigs

**Comment by mindforger** [comment]
Also 1.12 is not supported anymore
