### ISSUE TITLE
Can't take diamond pickaxe out of ae system

### ISSUE THREAD

**Issue by reeev** [AppliedEnergistics/Applied-Energistics-2#4844]
**Describe the bug**

I have put 2 diamond picks in my me system. Everything works fine, until I've used the grindstone to remove enchantments twice. The pickaxes have 2 nbt tags on them but I don't know what they are.
**To Reproduce**

I think the only way to reproduce is enchant a diamond pick and remove the enchantments twice, then put it in an me system.
**Expected behavior**

From what I can tell, once you put the pickaxe in the me system, you won't be able to take it back out.
**Additional context**

**Environment**

- Environment:

**Comment by mindforger** [comment]
what color is your PC case? *sarkasm*

You should add more infos so one can help out better, versions, mods used, maybe some screenshots of your me system?

A forced crashlog (f3 + c for a couple seconds) tells most of the complicated data but just telling to disenchant twice wont help.

**Comment by levmeister** [comment]
I have had this happen before, I removed the offending item by hooking an export bus up to a chest and exporting all similar items. I think it needed a fuzzy card to work, it was a while ago though.
