### ISSUE TITLE
Crash in applied energistics 2 1.16.4

### ISSUE THREAD

**Issue by omeranha** [AppliedEnergistics/Applied-Energistics-2#4846]
1.16.4 appliedenergistics2-8.0.2-alpha.2
forge 35.1.6 

I don't know how to reproduce, its a crash and i can't enter the world, it crashes my entire minecraft.

Crash Report: https://pastebin.com/q2h7hzW0
Latest.log: https://pastebin.com/KjvxvFaX

Once I was just playing and the map crashed and I couldn't get into it again, at first, I thought it was a bug in a dispenser, but after sending the crash to friends, I was recommended to make an issue here

**Comment by mindforger** [comment]
Looks like  broken crafting pattern, did you change or update any mods or your savegame?

**Comment by omeranha** [comment]
> Looks like broken crafting pattern, did you change or update any mods or your savegame?

No.

**Comment by yueh** [comment]
This indicates a broken pattern. The only reasons I could currently imagine is that some mod would actually remove an item, but that would require a mod being updated or removed. Or that the save itself got corrupted and might require to be restored from a backup.
