### ISSUE TITLE
Shift clicking items into inscriber will make it restart the process again

### ISSUE THREAD

**Issue by flleeppyy** [AppliedEnergistics/Applied-Energistics-2#4847]
**Describe the bug**

**To Reproduce**

in my case, I put in a silicon press, and shift clicked silicon in there. If you keep shift-clicking the silicon into the inscriber, it will stop the inscriber from continuing and restart the inscribing process all over again. (See video)
**Expected behavior**

**Additional context**

Modpack FTB Revelation 3.2.0
[Video](https://cdn.discordapp.com/attachments/780630126474821634/782538439341113344/5Qx0yJ6vpO.mp4)

**Environment**
OS: Windows 10 Pro
CPU: AMD Ryzen 7 2700
16GB DDR4
GPU: GeForce GTX 1080

Forced Crash Log https://pastebin.com/bvvQQGLZ

**Comment by shartte** [comment]
Sorry, we currently do not support any version older than Minecraft 1.16 anymore.

**Comment by flleeppyy** [comment]
But why? There's many popular packs that can't happen if they were at the latest version of Minecraft that mod developers support. It doesn't make sense to me. Modpack creators can't just update to the latest version of Minecraft and expect all the mods to work, just for one specific mod, to fix a bug. Some mods they use aren't being worked on any more but still work perfectly in the Minecraft version it was originally/last made for, but not in the latest version.
