### ISSUE TITLE
Crafting Terminal blacks out on first interaction after login

### ISSUE THREAD

**Issue by Jack-McKalling** [AppliedEnergistics/Applied-Energistics-2#4848]
**Describe the bug**

(consistent in 1.12.2 modpack, will test in newest version too but I need to submit this after 2days of work, will get back to it ASAP)

After you log into your world, the first time you try to click a stack of items from a crafting terminal, it blacks out the terminal. No items are pulled out and you have to try again when the terminal comes back up a second later. Then it succeeds then onwards normally until you login again.

It seems to happen when the network consumes between 270 - 280rf/t when idle. I can change the amount of storage buses and cables, and as long as the network consumes within that power range it will still happen. I did not finetune the exact numbers.

**To Reproduce**

1. Build the setup in below screenshots
a. An energy acceptor on the floor with 2 dense energy cells on both sides
b. A glass cable on top of all 5 blocks
c. A tower of 5 cables on top of the left, middle and right cable
d. Attach Crafting terminal to one of the cables, and a storage bus onto every other available face of the remaining cables (for a total of 76 buses)
e. The one cable in front of the energy acceptor in the screenshots is not necessary (but can be used to be removed from the network so you can see that modifying the network has no influence)
f. Place a compatible energy producer at the back of the energy acceptor (I tried Flux Networks as well as an Integrated Dynamics creative battery)
g. Place a chest next to one of the storage buses (I placed mine behind the terminal for symmetry), and insert a stack of dirt (any item)
2. When everything is setup and working, logout and back in.
3. Open the terminal, and click the stack of items
  ❌ the terminal blacks out as if it hasn't got enough power
4. Wait until power is back, and click the stack again
  ✅ now it works

**Expected behavior**

When you pull a stack of items, it should not de-power the terminal/network when it clearly has so many full dense energy cells connected. NB you can even see in the screenshot that they are in fact _full_ when the bug occurs.

**Additional context**

No crash relevant. This is the simplest setup I was able to reproduce this with:
![ae2 terminal blackout - setup](https://user-images.githubusercontent.com/14236702/100540232-532fcc00-323c-11eb-8803-b61103e47858.png)

This is what the network tool reports on the network:
![ae2 terminal blackout - network](https://user-images.githubusercontent.com/14236702/100540230-51fe9f00-323c-11eb-84a5-dcc44034a9e1.png)

This is the terminal before any interaction with the contents:
![ae2 terminal blackout - items](https://user-images.githubusercontent.com/14236702/100540229-51fe9f00-323c-11eb-8b78-761f4dc1a5b0.png)

And when the stack of dirt is clicked, this happens:
![ae2 terminal blackout - bug](https://user-images.githubusercontent.com/14236702/100540227-50cd7200-323c-11eb-9e5b-8c04a3ea0690.png)

**Environment**

Launcher log: https://gist.github.com/Jack-McKalling/86da8a4d7f810ec471bd66c4a4d2128c
Forced crashlog before terminal blackout: https://gist.github.com/Jack-McKalling/a215e1b3668c79da251a44ebf94f522f
Forced crashlog after terminal blackout: https://gist.github.com/Jack-McKalling/814eda74d2c8c6d44382ab5fb9a5dd4d

- Environment: 
Minecraft: 1.12.2
Forge: 14.23.5.2854 (I think)
Modpack: Sky Factory4; 4.2.2
AE2 version: rv6-stable-7

**Comment by mindforger** [comment]
I did notice that in 1.12 but could never reproduce it with sei alone, i hiess it is some mod interaction. Unfortunately 1.12 is not supported here anymore, you should try it with something around 1.16 and make a new issue if it persists

**Comment by shartte** [comment]
Energy network behavior was changed in 1.16. The "brownout" occurs when the network's internal buffer is depleted and it was as far as I know not guaranteed that the internal buffer was actually placed last in the list of energy sources.

This was changed in 1.16. The network's internal buffer will now always be last in the list of energy sources.

**Comment by Jack-McKalling** [comment]
I cannot even try this in 1.16 it turns out, because I have no way to disable channels, which is vital for this to occur. The enery consumption is also different, the numbers are different from 1.12 with this setup. But the terminal has no power because I'm obviously way above 8 channels here.
