### ISSUE TITLE
[1.16.4] The Me Security Terminal will not recognize it's owner after server restarted.

### ISSUE THREAD

**Issue by ScottCTD** [AppliedEnergistics/Applied-Energistics-2#4849]
I am the owner who placed the security terminal.
However, after the server restarted, I clicked my ME Security Terminal and this just popped up:
![image](https://user-images.githubusercontent.com/35100768/100704842-27018000-33e1-11eb-9531-60d203d17a23.png)

**Describe the bug**

Minecraft Version: 1.16.4
Forge Version: 35.1.6
AE2 Version: 8.1.0

Just like the summary above.

**To Reproduce**

1. Have a 1.16.4 server with AE2
2. Have a security terminal
3. Restart the server
4. The ME network shouldn't know you now

**Expected behavior**

The ME network **shouldn't** know you after the server restarted

**Additional context**

No crash and no log

**Environment**

- Environment: 
    - Windows10 with Java 8u271

**Comment by mindforger** [comment]
i will quote from the issue template




**Environment**




you are lacking way too many details

**Comment by ScottCTD** [comment]
I'm sorry that I initially thought this question does not need that information.
https://paste.ubuntu.com/p/9t5HyjJPyk/

**Comment by mindforger** [comment]
that is a tad more work to reproduce than just 

>Have a 1.16.4 server with AE2

To reproduce

**Comment by ScottCTD** [comment]
Umm.. I need to firstly apologize for that.
Yesterday, I got that issue and test 1 time to confirm it. 
But now I just tested that, everything is good.

I will try to do a further test today, so if everything goes alright I think I will get the result in the afternoon.
And, again, sorry for my irresponsible action yesterday because I was too busy at that time to think about that problem calmly.

**Comment by ScottCTD** [comment]
This is not a AE2 issue, I just messed up everything...
**Using My Mod Pack** -> Caused Problem Step
1. Start server at onlineMode=true
2. A online player join in and place ME security terminal
3. Restarted the server with onlineMode=false
4. A online player join in and the previously placed ME security terminal definitely prevent the player now
5. The online player replaced the ME security terminal and then the server restarted
6. Started server, still with onlineMode=false
7. That online player will not able to open up the ME security terminal.

**Pure forge and AE2** will **not cause this problem** with the same step.

**Comment by luchokoldo** [comment]
Im having this issue with DW20 1.16 modpack in my server
