### ISSUE TITLE
ability to keep a number of different items in an inventory

### ISSUE THREAD

**Issue by ArthurGamerHD** [AppliedEnergistics/Applied-Energistics-2#4850]
it is not possible to export a specific quantity of items to a chest using only applied and vanila, be it vanila chest, or other mods, and sometimes it is necessary to keep a chest, with multiple items with a minimum quantity, without fill it with item X, leaving no space for item Y

i suggest creating an upgrade card, which can be used in the exporter, importer and storage bus, which can read the inventory in which it is directed, to maintain a specific quantity of different items, defined as minimum / maximum

other mods, such as thermal dynamics, Logistic Pipes, Ender IO, and even, refined storage have this function, but none of them (except refined storage) are available for version 1.16+

in my case, I need to keep construction items, being sent automatically to the MineColonies deposit, so that the mod's npcs can build, but it was not possible to send multiple items, because when the npc removed an item, the system quickly filled with another any item, and it got to the point that the deposit only had 1 item type, I had to use refined storage, to read the ME Interface items, and send the correct amount to the deposit.
In another example, I did a metallurgy, using the mekanism factories, but the applied one always filled them with a single item per slot (with the roundabout mode active), which caused the machine to become clogged, and only processed the first slot, or, it provided only one type of item, which meant that my quantity of ores of one type, filling the system, and the other types, were not processed

**Comment by mindforger** [comment]
Could be an interface upgrade, keep faced inventory stocked with numbered item

**Comment by ArthurGamerHD** [comment]
exactly, in some situations, as it appears in the interface inventory with exactly the amount that the player defined, I need the number of items to be in the external inventory

**Comment by ArthurGamerHD** [comment]
(ops, miss click)

**Comment by yueh** [comment]
This is already possible with the tools provided by AE2.

**Comment by mindforger** [comment]
I do honestly not see how one could stuff a single storage block with more than one type of item and specify or limit the number or the slots used @yueh

**Comment by Technici4n** [comment]
Hint: subnetwork, storage bus, level emitter

**Comment by ArthurGamerHD** [comment]
> Hint: subnetwork, storage bus, level emitter

for 72 different stacks????????

**Comment by ArthurGamerHD** [comment]
for 2 - 4 items, it's ok, but when a huge amount of items needs to be separated into different stacks, using a single exporter for each item, it becomes totally unviable
