### ISSUE TITLE
Easier custom processing recipes

### ISSUE THREAD

**Issue by sgtkwol** [AppliedEnergistics/Applied-Energistics-2#4851]
**Describe the feature**
Allow items to be dragged from JEI to the pattern terminal to create recipes and allow numbers to be set. Could work similar to Just Enough Calculations mod.

**Reasons why it should be considered**
Some recipes work better when used in multiples, like 1 bucket might make 4 of something. This would prevent having to run through the whole craft step by step to get a final pattern.

**Additional Context**

**Comment by yueh** [comment]
The items shown in JEI quite often have additional or missing data compared to the crafted ones. Due to the way minecraft/forge handles items, for us these are completely different items and you could compare it to define a pattern to craft a furnace while it's actually a chest.
