### ISSUE TITLE
Switchs or Routers

### ISSUE THREAD

**Issue by RogerFerraro256** [AppliedEnergistics/Applied-Energistics-2#4853]
**Describe the feature**
it would be an block or interface that add channels to a point in your cable, so you have a smart cable running through somewhere, and you just run out of channels, so you put an router or a switch and it add some channels, not that many, so it wouldn't work with something like a 32 channel cable, but a 8 channel would be fine

**Reasons why it should be considered**
many times when i was building some long network or something what requires a lot of channels, i had to get back to the controller and pass another cable, and i think most people have suffered from this on larger networks, so i think it might be usefull and quite interesting to see the new possibilities

**Comment by Technici4n** [comment]
Do you know what P2P tunnels are? I think they are exactly what you are looking for...
