### ISSUE TITLE
Cant craft the Inscriber

### ISSUE THREAD

**Issue by Kalezra** [AppliedEnergistics/Applied-Energistics-2#4855]
I cant seem to be able to craft the Inscriber at all in my friends 1.12.2 server.

We have been playing this modpack for a couple weeks now and i just go into building my ME system after farming alot of materials. and now i cant seem to actually be able to craft the Inscriber at all. Ive tried reinstalling the mod, the modpack, my minecraft and nothing has worked.. im using curse forge currently, the mod is up to date and is the recommended "working version". Please this is really frustrating. thank you!

- Environment: 
ae2 v7 for minecraft 1.12.2 (curseforge launcher) (forge).

**Comment by Tahakk** [comment]
1.12.2 is not supported anymore. Anyways didn't have any problems with rafting inscriber in many modpacks that I tried it with so it muset by some kind of mod incompatibility.

**Comment by mindforger** [comment]
>playing this modpack

ask the modpack author, maybe he disaled it on purpose or in a wrong way?
