### ISSUE TITLE
Request all missing items button in crafting terminal

### ISSUE THREAD

**Issue by ProfessorBiddle** [AppliedEnergistics/Applied-Energistics-2#4856]
**Describe the feature**

Like the '~' button in Logistics Pipes, a button to request the autocrafting of all missing components in a recipe would be really cool.

Edit: Refined storage added a similar button with a ctrl click to request missing items in JEI, that might be a better way to do it as well

**Reasons why it should be considered**

It would be very useful and a huge optimization to terminal workflow.
**Additional Context**

Thanks for all you guys do, absolutely love the mod, have a great day.

**Comment by yueh** [comment]
Not going to happen. The goal of AE is still autocrafting with patterns and not replace it with manual crafting/requests of random JEI entries.
