### ISSUE TITLE
1.12.2 version of AE2 draining all of my power on a server when no players online

### ISSUE THREAD

**Issue by oddbookworm** [AppliedEnergistics/Applied-Energistics-2#4857]
Exactly as the title says. I am running AE2 on a modpack (ATM3 specifically) on a server, and when nobody is online, the ME system completely drains any power that I had stored in energy cells and capacitor banks and whatnot. I'm using the most recent version of the 1.12.2 files. I know that version might not be supported, but I was hoping that there is a solution to this issue. I have verified through disconnecting/reconnecting various things that it is indeed the ME system that is draining the power. I am aware that I can use a chunkloader from ic2, but in this modpack, those are prohibitively expensive.

**Comment by Tahakk** [comment]
You have it chunkloaded? Also how much does your AE system drains, it seems not that likely that AE would be the biggest power hungry mod.

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.16 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
