### ISSUE TITLE
Meteorites Causing WorldGen Crash

### ISSUE THREAD

**Issue by Rover656** [AppliedEnergistics/Applied-Energistics-2#4858]
The meteorite world generation feature causes a server crash every few minutes.

**Describe the bug**

The meteorite world generation feature causes a world generation crash related to SectionLightStorage.getLight. I'm unsure how this happens, however I am referring to this forum post detailing somebodys research into the bug: https://forums.minecraftforge.net/topic/94072-1163-custom-modpack-crash-while-chunk-loading/.

**To Reproduce**

Create a new server with applied energistics installed, explore for a while, the server tends to crash after a few minutes.

**Expected behavior**

The server should not crash.

**Additional context**

The aforementioned forum post: https://forums.minecraftforge.net/topic/94072-1163-custom-modpack-crash-while-chunk-loading/
My own crash log: https://gist.githubusercontent.com/Rover656/cc2a6ea6f5bf5ca8474209c7e359aeb0/raw/cb30bc9db58032f12fad97d9e4afa771ec70b730/gistfile1.txt

**Environment**

- Environment:  Minecraft 1.16.4, Forge 35.1.10. Custom mod pack (however it has been proven to be ae2 by running packs without, again see forum post).

**Comment by shartte** [comment]
> however it has been proven to be ae2 by running packs without

This does not prove that it is AE. Rather, it is most likely one of your other mods or a cross-mod interaction, since AE2 on it's own seems to work fine.
