### ISSUE TITLE
Change inscriber inventory position or at least document which side does what

### ISSUE THREAD

**Issue by Trevinlc1997** [AppliedEnergistics/Applied-Energistics-2#4859]
**Describe the feature**

You are using the inscriber for only a set of materials, one pipe should be able to handle everything
Is it a press or any type of printed circuit? Insert at the top slot
Is it redstone, raw silicon, diamond, gold? Insert in the middle
Is it printed silicon? Insert in the bottom

Another thing at least you could document somewhere that specifies which each side is suppose to be used as input/output so if you kept the current design people could easily automate the processors better. 

**Reasons why it should be considered**

This whole mod seems to be based around automation and solve the chest issue. Automation works amazingly with every other mod but when you try to automate anything in the mod pack it becomes a nightmare. 

**Additional Context**

Why should I have to do this (Example of it in picture) when one should be good enough. 
![2020-12-07_19 59 58](https://user-images.githubusercontent.com/24485362/101428747-f335c700-38c6-11eb-8664-ab9e0c4fa59c.png)

**Comment by Trevinlc1997** [comment]
Top is top, right is right, down is down.

**Comment by mindforger** [comment]
and you can rotate em for optimal connection layout
