### ISSUE TITLE
ae2 spatial storage cell 

### ISSUE THREAD

**Issue by D3s0l4ti0n** [AppliedEnergistics/Applied-Energistics-2#4861]
im trying to use a spatial system to store a base in, it functions when i flick the switch pulls items into the cell and stores them and brings them back when i flip the switch again taking things out of spatial storage but if i send myself in there nothing there and its just void and i take bleeding damage and cant do anything but /home to get out

**Comment by mindforger** [comment]
yeah sure you can be helped, but can you provide at least 1% of the required informations that are requested from you via the template you deleted?

**Comment by D3s0l4ti0n** [comment]
im not really looking for help i assumed its because applied energetics is still in alpha for 1.16.4 and was just asking if anyone else had the issue

**Comment by mindforger** [comment]
this is an issue tracker, no forum

When given the right information you will get help ... PS: my 1% were kindof sarcastic, still not enough
