### ISSUE TITLE
Automatic block compression and conversion

### ISSUE THREAD

**Issue by Trevinlc1997** [AppliedEnergistics/Applied-Energistics-2#4862]
Compacts blocks to save space

**Describe the feature**

It should act like compacting storage, if you insert 90 iron ingots in your ME system it should show 810 iron nuggets, 90 iron ingots and 9 iron blocks.  (However it stores everything as blocks and converts depending on the item you pull out) 

Obviously this sounds OP so my suggestion to counter the effectiveness is you add a new type of block called "ME Compression" or something that needs to be placed in your ME system before any compression tasks can be done. 

You could either put a inventory system in the compression block that acts as a filter so you can either choose to compress all blocks or only a few. Lastly, to prevent it being OP even more, I like how the type system is setup so perhaps add compression cards that upgrade the compression blocks capabilities (able to compress multiple types, concurrent compression jobs, etc)

**Reasons why it should be considered**

It gives AE2 more features to mess around with, more depth.  I personally would love having a "Compression terminal" that shows all the ore/ingots/blocks that the system is working on. 

**Additional Context**

**Comment by yueh** [comment]
This can already be achieved with AE2 currently. Maybe with the exception of displaying it as broken down values, but that is not really important with the game design in mind as players should not be bothered to deal with it manually at all.
