### ISSUE TITLE
Client got kicked from Server

### ISSUE THREAD

**Issue by Vaex** [AppliedEnergistics/Applied-Energistics-2#4863]
**Describe the bug**

AE Version: rv6 build 7

**To Reproduce**

I'm using the mod Better Crates and i accidentally put a diamond crate into my AE Stytem but the crate was not empty and had a few Items filled. When i try to remove my diamond crate (which stores items inside) i get the following error: Internal Exception: java.lang.IllegalArgumentException:Payload may not be larger than 32767 bytes

Which kicks me out from the Server
**Expected behavior**

Dunno if AE2 Team is able to fix this Problem. It should be possible to remove a full Diamond Crate from AE System
**Additional context**

**Environment**

- Environment: Actually there is no Crashreport produced, it just kicks me out from the Server with the message above.

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.16 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
