### ISSUE TITLE
Server crashes with spatialcompat

### ISSUE THREAD

**Issue by Crimson7806** [AppliedEnergistics/Applied-Energistics-2#4864]
Server crashes when I try starting it with Spatialcompat, was told to report the crash here

[crash-2020-12-09_21.33.44-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5676280/crash-2020-12-09_21.33.44-server.txt)

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.16 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
