### ISSUE TITLE
The latest build is messing up the default ore gen

### ISSUE THREAD

**Issue by ShardUsers** [AppliedEnergistics/Applied-Energistics-2#4865]
**Describe the bug**

When I started a new world the normal ores don't get generated 
**To Reproduce**

I just started a new world and started trying to get coal iron ect cant find any started another world with creative mode and same thing none was generating at all. I had other mods installed at the time however i removed all those and it is AE2 causing it
**Expected behavior**

**Additional context**

**Environment**

- Environment:

**Comment by shartte** [comment]
Please provide more information as described in the issue template (the initial value of the text box when you create an issue).

**Comment by ShardUsers** [comment]
![Without AE2](https://user-images.githubusercontent.com/75883344/101990201-6be7ab00-3c5a-11eb-8ec7-9d7718feab00.png)
![With AE2](https://user-images.githubusercontent.com/75883344/101990203-6f7b3200-3c5a-11eb-87f8-92b9d3aab752.png)
[crash-2020-12-12_09.11.34-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5683473/crash-2020-12-12_09.11.34-client.txt)


I created a new world with and without ae2 installed using the same seed left all other mods i have installed   Notice that in the first screenshot there is iron coal  and such and the second there is not. Same with all the rest of the default ore.   I also spawned a meteorite compass all it will do is spin around wont point to anything

**Comment by shartte** [comment]
I tried this with only the latest Forge, 1.16.4 and AE2 8.1.0, and could not reproduce this problem.

**Comment by yueh** [comment]
Also most likely a duplicate of #4777

**Comment by ShardUsers** [comment]
Yah that seems to be it I updated to the alpha and its working fine now. And when I did a clean install it worked fine. Thank you guys for the help

**Comment by ShardUsers** [comment]
If someone is able to change the download page to state its not compatible with Opti fine in its stable version would probably head off anymore of these posts
