### ISSUE TITLE
Change Annihilation Plane range

### ISSUE THREAD

**Issue by Starjumper2821** [AppliedEnergistics/Applied-Energistics-2#4869]
**Describe the feature**
Annihilation planes should also pick up items slightly above the targeted block, at least when in front of water.

**Reasons why it should be considered**
Due to changes to item behaviour in water, specifically floating on top, Annihilation Planes pointing into a water block that does not have a solid block above it do not reliably pick up items. This specifically made the crystal purificaiton design I was using highly impractical. Even if no change will be made, I'm hoping this issue will at least help people understand why their system might be no longer working as intended when moving to versions after 18w07a.

**Additional Context**
![2020-12-16_13 02 03](https://user-images.githubusercontent.com/20238370/102346334-f738a780-3f9e-11eb-9fff-2c37b390f4fa.png)
![2020-12-16_13 04 44](https://user-images.githubusercontent.com/20238370/102346534-4aaaf580-3f9f-11eb-951e-73c579a85f52.png)

Here the mentioned design where a Formation plane drops seeds or fluix resources and an Annihilation plane is supposed to pick them up, but unable as the items float and glitch into the Formation plane.

**Comment by yueh** [comment]
Planes work when something touches them and are not some vacuum devices. Thus if nothing hits them, they cannot react to it at all.

**Comment by mindforger** [comment]
well, then ae2 can not automate crystal growth anymore by itself when the crystals are floating

I think this needs to be addressed .. Like make the crystals not float

@yueh

**Comment by Starjumper2821** [comment]
You still can, put the annihilation plane on top and it will pick the crystals up at some point. Might not even need a filter anymore. However, if it isn't a water source that's not the case. I'd really wish for them to just make a multiblock structure with a controller that takes the seeds and after a period has finished crystals in the inventory. Something a bit like the multiblocks in tech reborn.

**Comment by mindforger** [comment]
>You still can, put the annihilation plane on top

not really viable, since you have to drop the items in first and that is most often done from the top ... but with an formation plane it would be possible from every otehr side i just found out :P
