### ISSUE TITLE
Minecraft 1.12.2 Server Crash

### ISSUE THREAD

**Issue by Worldconsumer10** [AppliedEnergistics/Applied-Energistics-2#4871]
Im pretty sure its related to the installation of AE2.. not sure what to say

**Describe the issue**
java.lang.NullReferenceException happens when the server starts loading AE2

**Environment**
https://pastebin.com/R69jhaTT

- Environment: 
[latest.log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5709142/latest.log)

Server Log ^

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.16 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.

**Comment by mindforger** [comment]
>[20:38:39] [Server thread/WARN] [net.minecraft.server.dedicated.DedicatedServer]: **** FAILED TO BIND TO PORT!
[20:38:39] [Server thread/WARN] [net.minecraft.server.dedicated.DedicatedServer]: The exception was: java.net.BindException: Cannot assign requested address: bind
[20:38:39] [Server thread/WARN] [net.minecraft.server.dedicated.DedicatedServer]: Perhaps a server is already running on that port?
