### ISSUE TITLE
Cable facade rotation

### ISSUE THREAD

**Issue by Flexo013** [AppliedEnergistics/Applied-Energistics-2#4872]
Reopening #3655

I suggest using something similar to the Yeta Wrench by Ender IO, which has a rotation mode. The Network tool could have this.

**Comment by shartte** [comment]
This is not a matter of not having a tool. It's a rendering issue.

**Comment by CC007** [comment]
Couldn't you have it swap between the other versions of the facade item then? Like have it a whole different item as a facade?
