### ISSUE TITLE
Spatial Storage Entity/Block Issue

### ISSUE THREAD

**Issue by ERRORCODE509** [AppliedEnergistics/Applied-Energistics-2#4873]
**Describe the bug**
The spatial storage dimension is full of non-existent blocks that suffocate entities and players, entities cannot be retrieved from spatial storage after entering, and blocks sent to the spatial dimension cannot be seen while in it. (Note that blocks can be retrieved from the spatial dimension without issue, but cannot be seen while in it.)

**To Reproduce**
1. Assemble an appropriately-sized SCS
2. Load yourself, some blocks, and a few entities into the SCS
3. Activate the spatial I/O port
4. Notice that the blocks you sent in are nowhere to be seen
4. Watch as you, and the entities with you, cannot move and slowly suffocate

**Expected behavior**
Blocks sent in to be visible, to be able to move around (within the dimensions of the formatted spatial storage drive), for entities to be able to be retrieved from spatial storage, for you and entities to not suffocate in the spatial dimension.

**Environment**
- Forge 35.1.13 for MC 1.16.4
- Tested with both AE2 versions 8.1.0 and 8.2.0-alpha
- Other loaded mods: 
    - VoxelMap 1.10.14
    - Optifine 1.16.4_HD_U_G5_MOD

**Comment by shartte** [comment]
OptiFine is unsupported. Can you reproduce this with **only** AE2 loaded?

**Comment by ERRORCODE509** [comment]
Sorry for the slow response, I tested it earlier but forgot to reply. I can confirm that AE2 is the only source of the issue, as removing other mods changed nothing. Still couldn't move, entities still suffocated and couldn't be retrieved, and blocks still didn't appear.

**Comment by mindforger** [comment]
Please make a forced crashlog by holding F3+C while ingame and upload it to pastebin for more insight to your last setup

**Comment by shartte** [comment]
I just reproduced this locally. No crashlog needed anymore.

Forge reactivated their teleport code at some point, which broke our vanilla-oriented teleport-workaround from the very early 1.16.x days.
