### ISSUE TITLE
Sodium causes some blocks to have a missing texture (Fabric 1.16.4)

### ISSUE THREAD

**Issue by charles-mccall** [AppliedEnergistics/Applied-Energistics-2#4880]
When Sodium is installed on Fabric 1.16.4, cable, glass and terminal blocks get a black and purple texture. (possibly more, not tested them all)
Essentially, most glass-like blocks get a missing texture, but are still usable and funcitonally normally.
Screenshot 1 shows a few blocks both placed and on the ground. My hotbar order is the same order in which the blocks have been placed.

To reproduce, install Fabric 1.16.4, Fabric API, appliedenergistics2-fabric-8.1.0-alpha.13, and Sodium See screenshot 2 for installed mod list

![installed-mods](https://user-images.githubusercontent.com/53658598/102720117-aacccf00-42f2-11eb-965e-128446eb173e.PNG)
![missing-textures](https://user-images.githubusercontent.com/53658598/102720118-ab656580-42f2-11eb-885e-551b15822fd7.png)

**Comment by shartte** [comment]
Sodium is still incompatible with the Fabric Rendering API, which AE2 uses.
