### ISSUE TITLE
ME Storage bus connected to anything doesnt show up on terminal MC Eternal 1.3.7.1

### ISSUE THREAD

**Issue by Jarpiino** [AppliedEnergistics/Applied-Energistics-2#4881]
ME Storage bus connected to anything doesnt show up on terminal. MC Eternal 1.3.7.1
 
**Describe the bug**
 When connecting something to ME System via Storage Bus, nothing shows up on terminal.

**To Reproduce**
 Play MC Eternal 1.3.7.1 modpack with "StorageDrawers-1.12.2-5.4.1" and "appliedenergistics2-rv6-stable-7" mods.

**Expected behavior**
 I expect to see my items on ME Terminal.

**Additional context**
 ![1](https://user-images.githubusercontent.com/28261664/102721089-36e5f300-4301-11eb-8e90-a3d7013c8a0c.png)
![2](https://user-images.githubusercontent.com/28261664/102721091-377e8980-4301-11eb-8b23-6a2b2d8cdab3.png)
![3](https://user-images.githubusercontent.com/28261664/102721092-39484d00-4301-11eb-8d17-2797544cbb3d.png)
![only thing that works](https://user-images.githubusercontent.com/28261664/102721093-39e0e380-4301-11eb-8203-4b55e9853890.png)

**Environment**
 Maybe FTBUtilities-5.4.1.129 is interfering with it's claiming and chunkloading?

- Environment: overworld, base

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.16 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
