### ISSUE TITLE
Psi CAD's get stuck in storage

### ISSUE THREAD

**Issue by MilkyRu** [AppliedEnergistics/Applied-Energistics-2#4882]
I have been playing on DW20's Mod pack and accidentally put my CAD in my AE2 storage system and they can not be removed.

**Comment by mindforger** [comment]
Quoting from the template you deleted to create this issue

>**Environment**
Include as many relevant details about the environment
A forced crash report by pressing F3+c for 10 seconds. Use pastebin, gist, etc.
Without it, we will automatically close the issue.

**Comment by NeoInversion** [comment]
Older issue at #4816 with proper info. Hoping to get that one reopened as I and some others have confirmed the issue still happens in 1.16 and above.

**Comment by mindforger** [comment]
please open  new one with proper explanation and Link the other issues there, this is better to handle
