### ISSUE TITLE
Botania Mana Tablet fuzzy card logic not working

### ISSUE THREAD

**Issue by olee** [AppliedEnergistics/Applied-Energistics-2#4885]
Somehow the Fuzzy Card cannot compare Botania's Mana Tablet damage values.
![image](https://user-images.githubusercontent.com/6547794/103026371-0b0e7b80-4554-11eb-84e0-34be68758e5d.png)

This is how I configured it - so it should only put Mana Tablets with less than 50% durability into the Dropper, however it always puts **ANY** Mana Tabet into the Dropper.
When I tested it with Minecraft bows instead, it worked properly.

![image](https://user-images.githubusercontent.com/6547794/103026455-45781880-4554-11eb-9c22-45136b1ec80a.png)

**Expected behavior**
Fuzzy Card should work on Mana Tablets as well

**Environment**
- Forge 25.1.13
- AE2 8.1.0
- Botania-1.16.4-410

**Comment by yueh** [comment]
Nothing we can fix. Tablets are not really damageable at all and therefore we cannot handle them like these. It just appears to a user that they are due to reusing the durability graph, but that is purely a visual thing.

**Comment by olee** [comment]
😢 


Would it be possible to add this as some custom integration / extension to AE2 / botania / a compatibility mod?
And would you be willing to help a bit with code if I could take care of the rest (setup, deployment, etc.)?
