### ISSUE TITLE
Terminal, Fluix ME Glass Cable, and ME Drive appear as missing models

### ISSUE THREAD

**Issue by ThatBenderGuy** [AppliedEnergistics/Applied-Energistics-2#4889]
**Describe the bug**
The Fluix ME glass cable, Terminals, and ME Drive appear as purple/black checkered blocks (Correct hitboxes though). They still function but they do not render properly.

**To Reproduce**
Place down the respective blocks.

**Expected behavior**
The blocks to render properly.

**Additional context**
![2020-12-26_20 24 30](https://user-images.githubusercontent.com/3581398/103163213-722c6a00-47b8-11eb-9d32-ef253cebdb74.png)

**Environment**
Crashlog - https://pastebin.com/2aCTSdYw

- Environment: 
MC Ver: 1.16.4
Modloader: Fabric
AE2 Ver: 8.1.0-alpha.13 (Fabric)

**Comment by mindforger** [comment]
Duplicate i guess
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4792

Please check closed issues too
