### ISSUE TITLE
Server crash when trying to autocraft pattern with substitutions

### ISSUE THREAD

**Issue by mkaito** [AppliedEnergistics/Applied-Energistics-2#4893]
**Describe the bug**

I'm helping to test the next release of the ATM6 pack. We've updated AE2.

While trying to craft some Quartz Glass via pattern with substitutions enabled, the server crashed as soon as I submitted the crafting job. The world would not come back up and I had to restore a backup. See crash log below.

Could of course be a bad mod interaction, but I wanted to bounce the stack trace off you before I start removing 200+ mods one by one.

Just to be clear, this was an AE2 crafting recipe that was to be carried out in a molecular assembler. No actual cross-mod interaction via processing pattern or similar. The stack trace seems to point at an explosion when trying to resolve ingredients via tags.

**To Reproduce**

- Create pattern with substitutions
- Put pattern in terminal
- Submit a crafting job with said pattern

**Expected behavior**

- For the job to either submit or fail to submit

**Additional context**

Crashlog: https://hastebin.com/urezegefaj

**Environment**

- Mod pack: ATM6 1.3.8 (unreleased)

**Comment by mkaito** [comment]
Here's another crash log from a test world I made in single player: https://hastebin.com/qerumedabu.rb

**Comment by mvb0005** [comment]
I was able to recreate this on an AE2 only instance. Seems to be related to [this change](https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/4877/files#).

**Comment by Meowing-Cat** [comment]
Anyone got a quick fix for this. kinda tired of doing rollbacks :D

**Comment by mkaito** [comment]
Yes. Downgrade to Alpha 2.
-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by 8qBITs** [comment]
Direwolf 1.16 same issue here is crash log https://hastebin.com/ejucijites.rb

**Comment by shartte** [comment]
This is sadly non-trivial to fix properly, but we're working on it. (The crash is easy to fix. Correctly auto-crafting with substitutions is not)
