### ISSUE TITLE
Rendering overlay null pointer exception during startup

### ISSUE THREAD

**Issue by CvoidWyvern** [AppliedEnergistics/Applied-Energistics-2#4894]
1.16.4 game constantly crashes while starting,
AE2 8.2.0 beta 1, also tested on 8.1.0 release
Forge 35.1.28, also tested on 35.1.22 with same results

Crashlog 8.2.0 beta https://hastebin.com/zumuzurene.rb
Crashlog 8.1.0 https://hastebin.com/eguviweqav.rb

**Comment by yueh** [comment]
If the stacktrace is correct about the lines, this looks like some other mod is registering their models without a valid identifier.
No idea which one, but I would guess the debug.log should contain some warning about it, which should then be reported to the mod causing it.

But we should probably look into safeguarding it against other broken mods.

**Comment by CvoidWyvern** [comment]
Not sure if there's one mod causing other mods to fail or if I'm just not reading it right, here's the debug.log
https://cdn.discordapp.com/attachments/359814544090071040/793635445874884619/message.txt

**Comment by CvoidWyvern** [comment]
Whatever mod it was, an update fixed this. But definitely would be good to safeguard against that.
