### ISSUE TITLE
AE2 rv6-7 autocraft malfunction w/ Storage Drawers upgrade template

### ISSUE THREAD

**Issue by KThompson77** [AppliedEnergistics/Applied-Energistics-2#4895]
when attempting to autocraft a storage template with regular oak components, all tier 1 required pieces available, system registers all pieces 'stored' and final component 'scheduled', never completes. Happens on specific recipes only so far, regular drawer and other items craft with no issue.
**Describe the bug**

created isolated network containing only what was required for single crafting job:
crafting processor
storage bus connected to chest with requisite items inside
a terminal attached on smart cable
and an interface connected to assembler with recipe inside
**To Reproduce**

should use 1 basic drawer [oak] and 8 sticks to create 2 upgrade templates
**Expected behavior**

**Additional context**

**Environment**

- Environment: 
using storage drawer 1.12.2 - 5.4.2
ae2 rv6 stable build 7

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.16 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.

**Comment by mindforger** [comment]
that is an issue with another mod adding several wood types, you can try disabling substitution on wood recipes to fix it or fix the recepies itself ...or remove the mod adding additional wood (i guess this would ruin your world :P )
