### ISSUE TITLE
Cannot pulverize fluix crystal in Thermal Series Pulverizor

### ISSUE THREAD

**Issue by Pants44** [AppliedEnergistics/Applied-Energistics-2#4897]
**Describe the bug**
In Version 8.2.0-beta1, cannot pulverize fluix crystal in the Thermal Series pulverizor

**To Reproduce**
Try to put crystal in the pulverizor

**Expected behavior**
The crystal to be turned into dust

**Additional context**
![image](https://user-images.githubusercontent.com/33103193/103302870-a3808200-49d2-11eb-9701-47ec9abf504e.png)

**Environment**
No crash, just doesn't allow the item to be put into the machine. Looks like only mods that are supported to crush are AE2 and Mekanism

- Environment:

**Comment by yueh** [comment]
The way recipes (and technically tags) now work, will not make it easy for mods to add generic recipe for pulverizers and similar machines. In other ways every mod would have to explicitly support every mod out there adding these mechanics with the additional requirement of maintaining these recipes in case some mod decides to change their structure at some point without a good way to be aware of changes.

So for now this is pretty much up to each modpack to support their custom mod selection and provide fitting recipes as well as keep track of changes.
