### ISSUE TITLE
ArrayIndexOutOfBoundsException when autocrafting a recipe with Item Substitutions enabled

### ISSUE THREAD

**Issue by sedlak477** [AppliedEnergistics/Applied-Energistics-2#4898]
**Describe the issue**
When trying to auto craft any pattern that has "Item Substitutions" enabled, after selecting the amount and pressing the "Next" button, the GUI closes and the following message is displayed in chat:
```
Error: java.util.concurrent.ExecutionException:
 java.lang.IllegalStateException:
 java.lang.ArrayIndexOutOfBoundsException: 3
```

No crash or any other noticeable side effects.

**To Reproduce**
Create an AE network without a controller with the following components:
 * ME Drive
   * 1k ME Storage Cell
   * 4k ME Storage Cell
  * Energy Acceptor
  * 1k Crafting Storage
  * Molecular Assembler
  * ME Interface (non-block version, facing the molecular assembler)
  * ME Crafting Terminal
  * ME Pattern Terminal

Create any pattern, enabling Item Substitution and try crafting it.

**Expected behavior**
Craft the item or show a useful error.

**Workaround**
Don't use Item Substitution.

**Environment**
Java 1.8.0_51 64bit
Minecraft 1.16.4 (1.16.4-forge-35.1.15/forge)
Forced crash report: https://pastebin.com/FmEzur7r

Modpack: Direwolf20 1.16 - 1.2.0
I'm playing on a self-hosted server over the internet.

**Comment by shartte** [comment]
Duplicate of #4893
