### ISSUE TITLE
Adding mod to existing server changes Biomes O' Plenty biomes

### ISSUE THREAD

**Issue by TristanKing0** [AppliedEnergistics/Applied-Energistics-2#4901]
On my 1.16.3 server if I add version 8.1.0 then all of my biomes are swapped around. They're still in the same place, they just change to the wrong biome. Taking out this mod then reverts them back to normal.

**Comment by shartte** [comment]
Please provide more information as described in the issue template (the initial value of the text box when you create an issue).

**Comment by rwdj** [comment]
Maybe related to #4842?

**Comment by rwdj** [comment]
AE2 dev provided feedback.

**Comment by shartte** [comment]
A user reported back that it will be fixed by the linked update. This will be in beta3
