### ISSUE TITLE
[Question] API Question

### ISSUE THREAD

**Issue by Seniorendi** [AppliedEnergistics/Applied-Energistics-2#4908]
I don't know whether the problem comes from me or from AE2, I apologize in advance if I just forgot something.

**Describe the bug**
I added AE2 to my build.gradle
```
compileOnly fg.deobf("appeng:appliedenergistics2:${appliedenergistics_version}:api");
runtimeOnly fg.deobf("appeng:appliedenergistics2:${appliedenergistics_version}");
```
I can't run runClient, AE2 throws a mixin error when starting.

**To Reproduce**
Insert
```
compileOnly fg.deobf("appeng:appliedenergistics2:${appliedenergistics_version}:api");
runtimeOnly fg.deobf("appeng:appliedenergistics2:${appliedenergistics_version}");
```
to the build.gradle
add "appliedenergistics_version=8.2.0-beta.2" to the gradle.properties
run runClient

**Expected behavior**
MC should start correctly.

**Additional context**
The exception: https://gist.github.com/Seniorendi/c77eabf3327e212da0c870473fd6c882
Full log: https://gist.github.com/Seniorendi/07b950c9427b8458c2cfc6204ebc3bb0

**Environment**
Forge version: 35.1.28
MC Version: 1.16.4
AE2 version: 8.2.0-beta.2

**Comment by shartte** [comment]
Sadly, ForgeGradle does not handle SRG names in mixin files correctly.

Please see https://github.com/Vazkii/Patchouli#mixin-troubleshooting for help

**Comment by Seniorendi** [comment]
Thank you!
