### ISSUE TITLE
ME Import Bus and ME Export Bus

### ISSUE THREAD

**Issue by WunKiz** [AppliedEnergistics/Applied-Energistics-2#4909]
Me import Bus and Me Export Bus dont working.

Me import Bus and Me Export Bus dont working after put acceleration card. i am playing on 1.12.2 with (appliedenergistics2-rv6-stable-7) and all times when put acceleration card on export/import bus his stop to work, i dont know make stop this.
(i have energy [21.000 RF Generating] i have 40 Me controllers and channel for this.)
![image](https://user-images.githubusercontent.com/77036825/103725674-e4b9f880-4fb5-11eb-93eb-e21193d5951b.png)

![image](https://user-images.githubusercontent.com/77036825/103725694-edaaca00-4fb5-11eb-928e-9e4e3cdb4e43.png)

![image](https://user-images.githubusercontent.com/77036825/103725738-f6030500-4fb5-11eb-9b53-1f86dc9662bc.png)

![image](https://user-images.githubusercontent.com/77036825/103725748-00bd9a00-4fb6-11eb-8164-3a626f6b007d.png)

Sorry for my ingles. i am a brazilian

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.16 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
