### ISSUE TITLE
Spacial storage dimension not working

### ISSUE THREAD

**Issue by DraTrav** [AppliedEnergistics/Applied-Energistics-2#4911]
The spacial io dimension wasnt being created on my server, was working before but then suddenly stopped and now when i send a redstone signal into the spacial io port i get the error

[Server thread/WARN] [AE2:S/]: Failed to retrieve spatial storage dimension: java.lang.IllegalStateException: The storage cell world is missing.

I can guarantee the dimension files are still there 

its only on the server in single player it works just fine

**Comment by DraTrav** [comment]
it oddly seems to be some sort of incompatibility with the biomesoplenty world type using default world type ae2 spacial storage dimension worked again

**Comment by Tahakk** [comment]
look at #4906

**Comment by mindforger** [comment]
that issue is a corrodinates problem for teleporting blocks and entities into different locations, not related

**Comment by rwdj** [comment]
As Dratrav mentioned, it's #4842 which needs to be reopened.
