### ISSUE TITLE
curseforge page is annoying

### ISSUE THREAD

**Issue by nikishev1** [AppliedEnergistics/Applied-Energistics-2#4914]
it says nothing and it is tagged as FABRIC so i thought I have this mod but ive just noticed it says in log this mod is stupid FORGE. Fix your description to add that it is forge and remove fabric curseforge tag.
 idiot ae-mod.info has last update in 2019

**To Reproduce**
open curseforge, choose game version "fabric", AE2 will appear, instead of description it has link to idiot ae-mod.info that is outadet, so you dowload thinking it is fabric when the mod is stupid forge.

**Expected behavior**
remove fabric tage, so that when you choose "fabric" on curseforge, it doesn't list AE2, and add proper description, is it that hard.

**Additional context**
[13:57:05] [ForkJoinPool-1-worker-5/WARN]: Non-Fabric mod JAR at "D:\Games\Minecraft\versions\1.16.4-fabric\mods\appliedenergistics2-8.1.0.jar", ignoring

**Environment**
MINECRAFT

- Environment: FABRIC LATEST VERSION FOR 1.16.4 https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2

**Comment by yueh** [comment]
Please submit your feedback to curseforge. We can't do anything about their inability to handle different modloaders in a userfriendly way.

**Comment by nikishev1** [comment]
you can add "This mod is for forge" in the description and it will take 10 seconds to do that

**Comment by Mari023** [comment]
there is a version for fabric
https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2/files/3117933
