### ISSUE TITLE
OpenGL Error: 1281 (Invalid value)

### ISSUE THREAD

**Issue by yonnie** [AppliedEnergistics/Applied-Energistics-2#4920]
When connecting anything via ME cable and providing power spams my chat box with OpenGL Error: 1281 (Invalid value)

Forced Crash Report - https://pastebin.com/NGD0QV8c

<a href="https://ibb.co/QCMjBQz"><img src="https://i.ibb.co/mX4FsT1/2021-01-09-11-18-55.png" alt="2021-01-09-11-18-55" border="0"></a>

**Comment by Seniorendi** [comment]
You forget to provide versions.
Try to turn off Video Settings -> Other Settings -> Show GL Errors if you have optifine installed.

**Comment by yonnie** [comment]
whoops. everything is on 1.16.4 and compatible. ok great il try that. i do have it installed. thanks

**Comment by yonnie** [comment]
> You forget to provide versions.
> Try to turn off Video Settings -> Other Settings -> Show GL Errors if you have optifine installed.

that worked. thanks again.

**Comment by shartte** [comment]
OptiFine is generally unsupported by AE2

**Comment by yonnie** [comment]
> OptiFine is generally unsupported by AE2

had no clue. everything is good now and working together. :)
