### ISSUE TITLE
ArrayOutOfBoundsException: 4 error with autocrafting

### ISSUE THREAD

**Issue by Yanis42** [AppliedEnergistics/Applied-Energistics-2#4921]
First of all, I searched on this repo and I haven't seen any fix or opened issue, I apologize if there's already one opened, also I haven't tried this yet with the 8.2.0 beta 2 version (I'm using ver. 8.2.0 beta1 currently).

**Describe the bug**

When I try to start a craft on a terminal the windows closes itself with the error message: "Error: java.util.conccurent.ExecutionException: java.lang.IllegalStateException: java.lang.ArrayOutOfBoundsException: 4
**To Reproduce**

- Version 8.2.0 beta 1, and start a craft as long as the 1k storage component one
**Expected behavior**

The pre-start crafting windows closes and an error message is shown in the chat
**Additional context**
I made a little video: https://youtu.be/U2HTGIJ44mo

**Environment**

- Environment: https://pastebin.com/6JZh5hHC

**Comment by Seniorendi** [comment]
Can you send a full log?

**Comment by Yanis42** [comment]
I used the F3+C thing to generate a crash report, it's the pastebin link: https://pastebin.com/6JZh5hHC

And you have the youtube video so you can see exactly what I'm doing to make the error happen

**Comment by Yanis42** [comment]
Oh sorry I'm stupid, wait a minute lol

**Comment by Yanis42** [comment]
This is longer than Pastebin's char limit so here's the log file: https://www.dropbox.com/s/xr3fl7qk92aqbfz/2021-01-09-1.log?dl=0

**Comment by Yanis42** [comment]
I made it work with substitutions disabled in the encoded pattern

**Comment by Seniorendi** [comment]
Oh, yeah #4893

**Comment by Yanis42** [comment]
Ok I'm gonna close this issue then, I didn't know it was specifically related to substitutes

Thanks for your time!
