### ISSUE TITLE
AutoCrafting doesn't work

### ISSUE THREAD

**Issue by pd200** [AppliedEnergistics/Applied-Energistics-2#4926]
**Describe the bug**
When i start the autoCrafting if is a simple crafting for example redstone block, the autoCrafting working, but when the crafting it's complex for example 64k crafting storage, the autocrafting doesn't starting

**To Reproduce**
Start a autoCrafting of redstone blocks, of any quantity, and start autoCrafting of 64k autocrafting storage, of any quantity.

**Expected behavior**
AutoCrafting of redstone blocks  completed.
AutoCrafting of 64K autocrafting storage remains to autocrafting plan.

**Additional context**
This is autoCrafting of 64k crafting storage
![Immagine](https://user-images.githubusercontent.com/47245832/104129618-f06a3e00-536c-11eb-97b5-5ab73a513ec4.png)

This is autoCrafting of redstone blocks
![Immagine](https://user-images.githubusercontent.com/47245832/104129870-6e7b1480-536e-11eb-9cef-169a1822d3f9.png)

**Environment**
Ae2 8.2.0 beta 2 
Forge 35.1.12
Minecraft 1.16.4

**Comment by shartte** [comment]
Please provide the information requested in the issue template, and additionally in such a case, your debug.log

**Comment by pd200** [comment]
Ok, sorry for this,  I delet this issues and make a new one

**Comment by pd200** [comment]
I edited following the guidelines

**Comment by pd200** [comment]
> Please provide the information requested in the issue template, and additionally in such a case, your debug.log

I edited following the guidelines

**Comment by Seniorendi** [comment]
I had this issue with an older version of FTB Quests. But everything works fine with the newest FTB Quest version.
Can you provide a mod list?

**Comment by pd200** [comment]
> I had this issue with an older version of FTB Quests. But everything works fine with the newest FTB Quest version.
> Can you provide a mod list?

I made the pack.
The mod list is:
Cucumber-1.16.4-4.1.5.jar
woot-1.16.4-1.0.2.1.jar
craftingstation-4.1.1.jar
jei-1.16.4-7.6.0.58.jar
JAVD-2.5.42+mc-1.16.4.jar
Mekanism-1.16.4-10.0.18.445.jar
autooredictconv-1.16.4-16.1.0.jar
ae2extras-1.1-1.16.4.jar
reap-1.16.4-1.0.2.jar
invtweaks-1.16.4-1.0.1.jar
IronJetpacks-1.16.4-4.1.3.jar
ForgeEndertech-1.16.4-7.0.8.0-build.0028.jar
CTM-MC1.16.1-1.1.2.6.jar
Controlling-7.0.0.11.jar
appliedenergistics2-8.2.0-beta.2.jar
ftb-gui-library-1603.1.1.25.jar
mdecore-1.16.4-16.1.0.jar
branders-spawnermod-1.16.4-1.7.9.jar
Bookshelf-1.16.4-9.3.18.jar
BotanyPots-1.16.4-6.0.7.jar
buildinggadgets-1.16.4-3.7.3.jar
mcjtylib-1.16-5.0.15.jar
rftoolsbase-1.16-2.0.9.jar
DarkUtilities-1.16.4-7.0.3.jar
LightingWand-1.16.4-1.7.2.jar
MekanismGenerators-1.16.4-10.0.18.445.jar
Hwyla-forge-1.10.11-B78_1.16.2.jar
WAWLA-1.16.4-7.0.1.jar
carryon-1.16.3-1.15.1.7.jar
JustEnoughResources-1.16.3-0.12.0.100.jar
CraftTweaker-1.16.4-7.0.0.63.jar
forge-1.16.4-35.1.12-universal.jar
shetiphiancore-1.16-3.8.4.jarMysticalAgriculture-1.16.4-4.1.4.jar
MysticalAgradditions-1.16.4-4.1.3.jar
ironchest-1.16.4-11.2.10.jar
ZeroCore2-1.16.4-2.0.18.jar
forge-1.16.4-35.1.12-client.jar
cofh_core-1.16.3-1.0.4.jar
thermal-1.16.3-1.0.5.jar
industrial-foregoing-1.16.4-3.2.7-7d95990.jar
rftoolsutility-1.16-3.0.20.jar
torchmaster-2.3.5-alpha.jar
MouseTweaks-2.13-mc1.16.2.jar
titanium-1.16.4-3.2.4.jar
ImmersiveEngineering-1.16.4-4.1.2-129.jar
MekanismAdditions-1.16.4-10.0.18.445.jar
valkyrielib-1.16.4-3.0.6.1.jar
envirocore-1.16.4-3.0.6.0.jar
envirotech-1.16.4-3.0.6.1.jar
simplechunkloaders-1.16.4-1.0.6.0.jar
AdLods-1.16.4-4.1.2.0-build.0027.jar
simplylight-1.16.4-1.1.1.jar
ChickenChunks-1.16.4-2.7.0.85-universal.jar
rftoolsbuilder-1.16-3.0.13.jar
SolarFluxReborn-1.16.3-16.2.3.jar
curios-forge-1.16.4-4.0.3.0.jar
Patchouli-1.16.4-48.jar
Xaeros_Minimap_20.30.1_Forge_1.16.4.jar
JAOPCA-1.16.4-3.4.0.1.jar
gravestone-1.16.4-1.0.8.jar
torcherino-13.0.2+1.16.3.jar
StorageDrawers-1.16.3-8.2.1.jar
FluxNetworks-1.16.4-6.1.5.10.jar
angelring-1.16.3-1.3.3.jar
thermal_expansion-1.16.3-1.0.5.jar
elevatorid-1.16.4-1.7.9.jar
MekanismTools-1.16.4-10.0.18.445.jar
constructionwand-1.16.2-1.7.jar
connectedglass-1.0.6-mc1.16.4.jar
ExtremeReactors2-1.16.4-2.0.20.jar
trashcans-1.0.6-mc1.16.4.jar
betterbedrockgenerator-1.16.4-0.1.0.jar
extremeSoundMuffler-3.0_Forge-1.16.4.jar
SolarGeneration-1.16.4-2.3.0.jar
FastLeafDecay-v25.jar
CodeChickenLib-1.16.4-3.5.0.401-universal.jar
EnderStorage-1.16.4-2.7.0.161-universal.jar
QuantumStorage-1.16.4-5.3.0.jar
Cyclic-1.16.4-1.1.0.jar

**Comment by shartte** [comment]
Do you have a debug log?

**Comment by pd200** [comment]
> Do you have a debug log?

This is the latest

[debug.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5798549/debug.zip)

**Comment by pd200** [comment]
I think I understand what the problem is.
I the photo of autocrafting of redstoneBlock, some of this redstone are stored in storage cell and the rest in the quantum storage unit of quantumStorage mod, the quantum storage unit in linked with the quantum controll. While the photo of autocrafting of 64k crafting storage the component of crafting are all in the quantum storage unit.

Now i tryed to craft a large quantity of redstoneblock  and the don't start the craftin.
