### ISSUE TITLE
Mod incompatibility: Facades invisible when immersive portal is installed (and active?); Machines turn

### ISSUE THREAD

**Issue by 7eggert** [AppliedEnergistics/Applied-Energistics-2#4932]
If in MC 1.16.4 / Forge 35.1.4
the mod Immersive-Portals-1.16.4.jar
is installed (and a lot more) in addition to AE2,
Cables below facades will become invisible and machines will appear turned in their default direction.

By setting in config/immersive_portals-client.toml
"model_data_fix = true"
, the issue is EDIT: NOT fixed.

**Comment by shartte** [comment]
Please report this to them. I don't see how this is caused by us.
