### ISSUE TITLE
Memory card support for configured fluids and level emitters reportingValue

### ISSUE THREAD

**Issue by PrototypeTrousers** [AppliedEnergistics/Applied-Energistics-2#4936]
Memory cards completely ignore fluids configured and do not save the configured level on emitters (item and fluids)

**Describe the feature**
Copying settings with the memory card saying its configuration has been copied, should actually be copied.

**Reasons why it should be considered**
This should make even easier to configure AE networks, and manage your setups

**Comment by yueh** [comment]
Introduced by the merged PR.
