### ISSUE TITLE
I think there is some compatibility problem with quantumStorage, maybe it's a quantumStorage problem (AutoCrafting)

### ISSUE THREAD

**Issue by pd200** [AppliedEnergistics/Applied-Energistics-2#4941]
**Describe the bug**

I have a problem with autocrafting, everything is described here in my previous issue at the following link
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4926

Now I left a comment in the previous Issue, but I think I need to create a new one so that everything is clearer.
I apologize if this was not to be done.

I believe that the system doesn't take into account the items stored in the quantum unit of quantumStorage mod, quantum unit is linked to the quantum controll.

**To Reproduce**
In my system I have a part of redstone stored with the applied, while another part is stored in a quantum unit.
When i starting the autocrafting of the redstoneblocks, for example, if the amount of redstone required is less than what I have stored in the Applied the autocrafting starts, while if it exceeds the quantity that I have stored in the applied and therefore must take the remainder from the quantum unit, the crafting does not start.

**Expected behavior**
Autocrafting starts in any case

**Environment**
Ae2 8.2.0 beta 2
Forge 35.1.12
Minecraft 1.16.4
QuantumStorage 5.3.0

**Additionl Context**
I am placing this issue of the quantumStorage there
https://github.com/gigabit101/QuantumStorage/issues/233

**Comment by mindforger** [comment]
there is an older issue that describes the problem very well, dunno if it has been fixed since

https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4789
