### ISSUE TITLE
Possible Bug - ME Storage Bus in latest version in Project Ozone 3

### ISSUE THREAD

**Issue by ziron999** [AppliedEnergistics/Applied-Energistics-2#4943]
**Describe the issue**
For some reason when you queue/craft (for example) 4 ME storage bus's in a Molecular Assembler. It crafts all of them except 1 every single time. It hangs on the last craft and never finishes. When I cancel I see all of the available materials needed to craft it so it should of crafted without issue. Every other pattern works without issues. Only the ME Storage Bus will not craft the last one. It is a very strange bug that doesn't really make sense. I've tried replacing everything, remaking the pattern. It doesn't seem to matter.

**Environment**
Just Project Ozone 3 modpack on todays date.

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.16 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
