### ISSUE TITLE
Security terminals not working after restart

### ISSUE THREAD

**Issue by josh-65** [AppliedEnergistics/Applied-Energistics-2#4944]
When I place security terminal it works fine until a server or world restart and then it say I lack permissions and all he biometric cards users cant access it either.

**To Reproduce**
1) place security terminal
2) restart world or server
3) Try access network

**Expected behaviour**
I expect to still be able to access the network and use the wireless terminal.

**Environment**
Versions:
Minecraft: 1.16.4
Mod: 8.2.0 beta 2
Forge: 35.1.36

**Comment by DesolateElf-dev** [comment]
I'm having this issue too, after restart a multiplayer server in 1.16.4

**Comment by shartte** [comment]
This is potentially correlated with #4940 (low chance, however).

**Comment by shartte** [comment]
@DesolateElf-dev Are you running your server in offline mode? AE2 uses Profile GUIDs to identify players.

**Comment by josh-65** [comment]
I have my server in online mode

**Comment by shartte** [comment]
8.2.0-beta.3 has been released. Can you please re-check if the problem still occurs?

**Comment by josh-65** [comment]
still an issue

**Comment by shartte** [comment]
Alright. Thanks for checking. We'll have to investigate this further.

**Comment by DesolateElf-dev** [comment]
My server is running in offline mode, because some players don't have an account, is there any way to solve the problem in offline mode?

**Comment by Paddyboy1991** [comment]
the problem is still there

**Comment by OHutchyHutch** [comment]
Using all the mods 6 1.5.0, this happens 100% of the time.

**Comment by josh-65** [comment]
Any updates on this?

**Comment by Kandoral** [comment]
Same happening on applied energistics 2 8.3.0 alpha 1 with inscriber. After restart they stop working just like the terminal
