### ISSUE TITLE
Spatial Dimension is not Localized

### ISSUE THREAD

**Issue by Flytre** [AppliedEnergistics/Applied-Energistics-2#4946]
**Describe the bug**
The Spatial Dimension Biome has no localizationL
![Screen Shot 2021-01-14 at 6 21 58 PM](https://user-images.githubusercontent.com/40476907/104660877-646e5400-5695-11eb-93bf-674ea7bdc29c.png)

**To Reproduce**

**Expected behavior**

**Additional context**

**Environment**

- Environment:

**Comment by shartte** [comment]
How do you actually get to that?

I don't remember Vanilla accessing this localization key at any point.

**Comment by Flytre** [comment]
This was accessed using my biome locator mod, I know it technically doesn't need to be localized because its a dev biome but every other modded / vanilla biome is localized so just good for compat (It makes no sense for my mod to add a localization for another mod's biome).

**Comment by shartte** [comment]
Well, the thing is, we can add a localization string, but we couldn't even test if it works unless I am missing some way to see a biome name in Vanilla

**Comment by saltyseadoggo** [comment]
As I mentioned in my duplicate issue, biome names can be seen in vanilla by going to the Customize menu for Single Biome, Caves and Floating Islands type worlds when creating a new world.

**Comment by Technici4n** [comment]
Thanks @saltyseadoggo for the tip!
