### ISSUE TITLE
Massive lag when a player leaves the chunks of their AE2 setup

### ISSUE THREAD

**Issue by Walkintall** [AppliedEnergistics/Applied-Energistics-2#4948]
**Describe the bug**

On a multiplayer server, I am on and help manage we have been diagnosing lag issues. I have come across a big upswing in the microseconds per tick using a mod called LagGoggles. This up-swing comes from the Event Subscribers and is called: 
"Applied Energistics 2 (appliedenergistics2-rv6-stable-7.jar) (Server Thread)
net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent

This Event Subscriber is giving off 149769 μS/t 299.53%. This is causing the server Mean Tick Time to increase within the dimension and subsequently the cause of lag.

I would expect all this to happen when the ME system is being used but the jump in Lag only happens when the player is not in the immediate chunks of the ME system. As soon as the player goes to another dimension, logs off, or leaves the immediate vicinity the server experiences quite a bit of lag, in some instances unplayable.

I have tried cutting power to the ME Controler in order to fix the problem but it continues to happen powered or not.

**To Reproduce**
I am unsure if this can be reproduced as I am unaware of the cause of the lag and can only find the statistics that the lag is happening. If the Event Subscriber is happening because of the specific set-up of the ME system it would be extremely hard to replicate.
Currently, the steps that I am aware of to reproduce this would be to create a ME system with controls, p2p tunnels, various machines and liquids, storage buses attached to multiple different mods.

**Expected behavior**
I expect that when a player leaves the area and the chunks are not being loaded that the lag would subside and the Mean Tick Time would decrease in the dimension/area.

**Additional context**
MC Version - 1.12.2
Modpack - The 1.12.2 Pack Version 1.3.2
AE2 Version - rv6-stable-7
Mod for diagnosing Lag - LagGoggles Version 1.12.2-5.8-132

Away from chuncks:
![Capture 1](https://user-images.githubusercontent.com/10326101/104674208-3eef4380-56b1-11eb-8ac8-996664ee8d61.PNG)

In the chunks close to the ME System:
![Capture 2](https://user-images.githubusercontent.com/10326101/104674592-e9676680-56b1-11eb-8b95-0476bf5207d2.PNG)
You can see by the above photo that the stress on the server has changed drastically, AE2 is no longer at the top of the list, and the overall lag of the server as reduced significantly.

Let me know if you need more info.
Thanks for your help and time. I do really like AE2 for my storage needs! Cheers

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.16 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.

**Comment by Walkintall** [comment]
Perfect thanks for the reply!
