### ISSUE TITLE
Annihilation Plane and water don't work well together anymore - No more pure automation possible

### ISSUE THREAD

**Issue by hanni79** [AppliedEnergistics/Applied-Energistics-2#4949]
I tried to automate the autocrafting of pure crystals like I did in a lot of MC versions ( AE2 Tutorial #20 - Updated Auto-Crafting Fluix and Pure Crystals (MC 1.7.10) ) https://www.youtube.com/watch?v=yArP-IGr_sQ. This worked well for many years, but it seems since items swim up in water now, the **Annihilation Plane is not able to "catch" them anymore.** 

**To Reproduce**
( I built it like in the video linked above lots of times, summary below and picture 1)

- Export Seeds to a subnetwork via Interface-Interface connnection through a Formation Panel into water surrounded by crystal growth chambers from top
- Suck up grown pure crystals from bottom through a second subnetwork containing the annihilation plane and a ME chest with partitioned storage cell to only contain pure crystals ( this is the "filter" ) and re-insert them to the main network. -> _This is the part which doesn't work anymore - the crystals are shown flowing towards the Annihilation Plane in an endless stream, but never actually are sucked in_
- Switching formation plane bottom/top does not change the outcome, neither does a second waterblock.
- Even sideways, the Pure Crystals are not sucked in, they just "flow" towards the Annihilation Plane, get set back a bit and flow towards it again but are never sucked in ( see picture 2 ).
- I also tried a single Annihilation Plane (in the sideways version) and a double version, as I presumed that the pure crystals counted as being in the block above the water and therefore might get sucked in when there was a second plane above waterlevel ( also can be seen in picture 2 )

**Expected behavior**
The Pure Crystals are expected to be sucked up by the annihilation plane and then re-inserted into the network.

**Additional context**
Picture 1
![Pure Autocraft 1](https://user-images.githubusercontent.com/67236843/104815973-4ed56780-5818-11eb-855a-1715ebec82bc.png)

Picture 2
![2021-01-16_16 33 07](https://user-images.githubusercontent.com/67236843/104816013-a07df200-5818-11eb-9092-88eb4ef17993.png)

**Environment**
Environment is Forge 35.1.4. Minecraft 1.16.4, appliedenergistics2-8.1.0

(Sorry, I'm no english native, Environemnt means the version numbers ?)

**Comment by yueh** [comment]
Minecraft changed the physics for items in water, which needs different solutions now. In general this is a bug tracker, so we will not provide any build tips here.

**Comment by hanni79** [comment]
Yes, I know that. But shouldn't the Annihilation Plane not consistently absorb any item present in the block in front of it regardless of water ? 

I just tested it without water, see below : 
![2021-01-16_17 38 56](https://user-images.githubusercontent.com/67236843/104817468-bcd25c80-5821-11eb-8643-f207753ac61f.png)

When throwing the pure crystals directly in front of the plane, they get absorbed, when thrown a bit to the right, they are not.

**Comment by Tahakk** [comment]
Ye, but since they float up they are not technically in front of it, they are one block higher.

**Comment by shartte** [comment]
No, the mechanic is:

- For blocks, it will try to collect the **block** in front of it
- For dropped items, it will only try to collect items that **collide with it** (i.e. items that float up into the block occupied by the plane will be picked up)
