### ISSUE TITLE
Certus quartz ore is not using forge:ores tag

### ISSUE THREAD

**Issue by XxZajoZzO** [AppliedEnergistics/Applied-Energistics-2#4952]
**Describe the bug**
Certus quartz ore is not using forge:ores tag, only forge:ores/certus_quartz. I created my own modpack and every ore is using both  forge:ores and forge:ores/orename

**Expected behavior**
Certus quartz ore should use both tags

**Additional context**
https://i.imgur.com/gn8wZPM.png <- Quartz ore
https://i.imgur.com/srBCJNC.png <- Copepr from thermal

**Environment**
MC 1.16.4
Forge 35.31.36
appliedenergistics2-8.2.0-beta.2

**Comment by shartte** [comment]
Please search for issues before opening new ones.

**Comment by XxZajoZzO** [comment]
Sorry was searching for 10 minutes didn't find anything

**Comment by shartte** [comment]
Searching for `forge:ores`, it was the first result :-|

https://github.com/AppliedEnergistics/Applied-Energistics-2/issues?q=forge%3Aores
