### ISSUE TITLE
Adding a bit of sound scenery

### ISSUE THREAD

**Issue by NXTler** [AppliedEnergistics/Applied-Energistics-2#4953]
Hi, I walked around my house while auto crafting and notice that AE2 mod is really quiet in comparison to other mods.
I got some ideas for adding sounds to some parts like adding hard drive sounds to the ME drives or a deep ambient to the core.
I would really like to see this because it would make the system more alive and not just some flashing blocks.

**Comment by mindforger** [comment]
imagine "coil whining" sound in the CPU room XD

**Comment by Keinzell** [comment]
Or oldschool modem sounds from ME interfaces

**Comment by yueh** [comment]
Honestly sound effects, especially machine ones, can get annoying pretty fast. The sound engine is not really great in terms of positional audio, so the coil whine won't be just limited to a server room but be hearable in the whole base at nearly full blast and then cut off sharply once the player moves just a block further away.

So I would not plan on sounds being added to AE2 directly, it's really some one the few cases needing a real professional sound designer/engineer to do.

I have not really looked how minecraft/forge handles sounds, I would hope it's by triggering events. If so, I could certainly see us adding the necessary ones to allow anyone to design their own custom datapack for it, in case they really wanted to have some sounds.

**Comment by mindforger** [comment]
sounds do have a falloff range (at least Entity based), just take a look at the music block or a minecart ... it is some more complex stuff based on mono sounds that can have a location but one would have to define a falloff based on same type blocks being in a close proximity and adjust its range and position to a intermediate position or (if you do it per block) you would have an screaming stacked sounds (imagine/remember standing near a mob trap)

**Comment by yueh** [comment]
Yes, there is some falloff, but in my opinion it's not really well designed. It basically sounds like having the volume at 150% right next to the block (as in way too loud overall) and then scaled to like 75% at the cutoff range. iirc 16 blocks for entities/mobs. (And still way too loud in comparision to the distance). And with 17 block distance it's completely gone without any real transition.
There is simply nothing like a faint sound you can hear when actually paying attention to the background, it goes immediately from silent to pretty much foreground sound.

Using a redstone clock and hook it up to something like a piston is probably another example.

Further something like the IE crushers/generators are probably another example of bad sound design. No idea about the ranges, but it feels like they are unbearable loud up to 32 blocks away, then have a sharp cut after that to "that should probably the sound right next to them", which then reaches to like 64 blocks. All without much variation in the volume. And then gone.
Plus the various bugs at least in 1.12 with having stuck sound constantly looping and needing a restart to fix it.

**Comment by mindforger** [comment]
well he faced the same question and called out for somebody to make a PR :D
