### ISSUE TITLE
Applied Energistics Crashing Server Horribly for an Unknown Reason - 1.12.2 - possible bug or conflict?

### ISSUE THREAD

**Issue by Aubarino** [AppliedEnergistics/Applied-Energistics-2#4954]
**Describe the issue**
I'm using the most recent version of ae2 for 1.12.2 forge,
As i'm putting together a 1.12.2 Modpack with a friend.
All the mods I have are Updated decently - should work,
But no matter what I try, even Downgrading or Upgrading the server jar libraries themselves,
This error occurs.
I have configured dimension id's of other mods and etc,
So that shouldn't be an issue.
But I keep getting This crash, And have been busting my a## off trying to figure it out. 
Something about "Caused by: java.lang.ClassNotFoundException: net.minecraft.client.audio.ISound"
Also came up, but I cannot trace what's causing it or what it's relation is to the issue.

- Environment: 
A minecraft server running a 1.12.2 Forge Jar of the Latest version of 1.12.2 Forge,
8 gigs of ram, and about 90 player slots.
about 220 Mods, that work Perfectly Fine on a Single Player client - Decently updated and functional,
But when transitioned over onto a Server, Even after Hours apon Hours of reconfiguring and debugging,
ae2 Won't even let it Start.

Pastebin of latest crash report log - https://pastebin.com/0v62ECXv

**Comment by Aubarino** [comment]
I think it's an issue with Client v Server class comparison or etc,
But yet again, i cannot easily trace what's going on.

**Comment by shartte** [comment]
Sorry, we currently do not support any version older than Minecraft 1.16 anymore.

**Comment by Aubarino** [comment]
well that's not very helpful Is It,
People still mod 1.12.2 don't they?
You could atleast Help :/ or tell me to downgrade some stuff that could be causing it :/

**Comment by mindforger** [comment]
For your next report, you could post ONLY the crash report from the crashlog folder, because the normal log is hard to read ... 

Your log even tells you where you can find it

>[22:08:39] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: /home/mch/multicraft/servers/server100723/./crash-reports/crash-2021-01-20_22.08.39-server.txt

Secondly you should include the mod versions wird in future, especially when you do not provide a proper crashlog, you are making it hard to help when you ignore the template
