### ISSUE TITLE
Improve inscribers

### ISSUE THREAD

**Issue by pd200** [AppliedEnergistics/Applied-Energistics-2#4955]
**Describe the feature**
Inscribers are very slow, so it is boring to wait a long time for crafting that requires a high number of processors, so I ask you to add, or simply speed up the current inscribers, an advanced tier of inscriber, which will perform better than the inscriber current.
Th

**Reasons why it should be considered**
To speed up the game, and not have to wait hours for crafting

**Comment by shartte** [comment]
Put acceleration cards in it

**Comment by shartte** [comment]
You can put acceleration cards in an inscriber.
