### ISSUE TITLE
Openblocks Sky Block (Facades)

### ISSUE THREAD

**Issue by Keinzell** [AppliedEnergistics/Applied-Energistics-2#4956]
I am trying to get a Cable Facade for the OpenBlocks Sky Block (inverted, Metadata 1) , but no matter whether I use Wildcard mode or the specififc Metadata it does not create the Facade, only the one with Metadata 0.

In my Facade.cfg I changed the following things:

 B:allowTileEntityFacades=true 
# Set to true

        openblocks {
        I:sky=16
        }
# This is supposed to add all openblocks:sky as a Facade, also tried 1 before, still cant get one with Metadata 1.

![2021-01-21_14 56 48](https://user-images.githubusercontent.com/77789832/105361683-3b504500-5bfa-11eb-8c09-5b5a70f73ea9.png)
![2021-01-21_14 56 59](https://user-images.githubusercontent.com/77789832/105361718-42775300-5bfa-11eb-9b92-9a2c6c056a40.png)

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.16 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.

Also note that config option explicitly mentions it is unsupported and may simply not work (in the best case).
