### ISSUE TITLE
Placing Import Bus on Vibration Chamber crashes server (Fabric)

### ISSUE THREAD

**Issue by pkim168** [AppliedEnergistics/Applied-Energistics-2#4958]
**Describe the bug**
I placed a import bus on a vibration chamber and the server immediately crashed. Server now crashes when attempting to connect.

**To Reproduce**
Had vibration chamber connected to me drive. Once i placed the import bus, it crashed

**Expected behavior**
Server doesn't crash

**Additional context**
Crash when placing import bus
[crash-2021-01-24_23.10.43-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5864146/crash-2021-01-24_23.10.43-server.txt)
Crash when restarting server and attempting to connect
[crash-2021-01-24_23.11.48-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5864149/crash-2021-01-24_23.11.48-server.txt)

**Environment**

Minecraft Fabric Server. List of mods below:
[mods-list.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5864151/mods-list.txt)

- Environment:

**Comment by shartte** [comment]
Fixed by #5033

**Comment by shartte** [comment]
And props to @Technici4n
