### ISSUE TITLE
Crystals Seeds not growing in water/growth accelerators not working

### ISSUE THREAD

**Issue by LightningBlu** [AppliedEnergistics/Applied-Energistics-2#4959]
**Describe the bug**

When I put the seeds in the water they do not gain any percentage. I have added 4 growth accelerators and they do not help the process. I have tried it with 1 accelerator and it still doesn't work. I have used up almost a stack of coal in each of my vibration chambers and the accelerators are online but the seed wont grow.
**To Reproduce**

**Expected behavior**

The seeds should be gaining percentage when put in the water surrounded by the accelerators.
**Additional context**

**Environment**

- Environment: 
I am playing this in Sky Factory 4 and I am very new to Applied Energistics 2 and I have no idea what to do.

**Comment by shartte** [comment]
Please provide more information as described in the issue template (the initial value of the text box when you create an issue).
