### ISSUE TITLE
Modifier for autocrafting stocked items (AE2 8.2.0-beta3)

### ISSUE THREAD

**Issue by mthnry** [AppliedEnergistics/Applied-Energistics-2#4960]
**Describe the feature**
In the version for Minecraft 1.12 a modifier could be held to craft items even when there were some in stock.

**Reasons why it should be considered**
When a certain amount of an item is needed and you have  only say half the amount, and want to start an autocrafting job, you have to take out the stocked items to start the job, which is somewhat tedious.

**Comment by yueh** [comment]
It still uses a middle mouse click for it. If this does not work, some other mod will override that behaviour. E.g. mousetweaks is a common cause for it.

**Comment by XFactHD** [comment]
InventorySorter can cause this aswell because it uses middle mouse click for sorting by default.

**Comment by mthnry** [comment]
Can you change the key for AE2 as inventory sorter did use middle click in 1.12 as well. Why not have it set to ctrl as modifier again?

**Comment by XFactHD** [comment]
You can also change the key for inventory sorter. AE2 used the middle click in 1.12 as well for this functionality

**Comment by mthnry** [comment]
So there is no option for changing the key then? I got quite used to middle click to sort my inventory.

**Comment by XFactHD** [comment]
There is functionality for blacklisting a GUI in InventorySorter but I have not yet gotten that to work with AE2. This is the best solution in my opinion
