### ISSUE TITLE
Skipping onReady for Tile-Entity Log Spam

### ISSUE THREAD

**Issue by phit** [AppliedEnergistics/Applied-Energistics-2#4961]
**Describe the bug**
Just updated our Direwolf20 server to the latest AE2 version and I'm sIeeing the same log spam 8 times in a second from AE2 making the server console unusable.

**To Reproduce**
update to appliedenergistics2-8.2.0-beta.3 watch your console being flooded due to https://github.com/AppliedEnergistics/Applied-Energistics-2/commit/ce2f804fd6e93caa64a969906e2fbf79d2dfd542

**Expected behavior**
no log spam

**Additional context**
https://gist.github.com/phit/f5ddf9b676ff24c059212cbad79a54db

**Environment**

- Environment: Modpack Direwolf20 1.16 version 1.5.1
- appliedenergistics2-8.2.0-beta.3.jar

**Comment by shartte** [comment]
Do you have something that is loading and unloading a chunk each tick?

**Comment by yueh** [comment]
This really looks like something constantly reloading this specific chunk. Could also be caused by some adjacent chunk and we are just the messenger here notifying you about it.

As you mentioned it happens when trying to sleep and there is a bed in the screenshot, maybe some "ingenious" sleeping mod checks the spawn of every single player and if they are sleeping in their bed even when not logged in?

**Comment by shartte** [comment]
@phit Just as an explanation of what is happening here: You see that warning when an AE2 tile entity is loaded, but before the end of the server-tick, the chunk it's in is already unloaded again. (AE2 then skips the delayed initialization of the tile entity).

If this happens "normally", I can see us reducing this to debug loglevel, but it stil indicates that something is spam-loading this or an adjacent chunk.

**Comment by phit** [comment]
Yeah I looked around, I can't really see anything that should load the chunk. Do you happen to know any mod that can log load reasons, in the past I used sampler for that but I don't know of any 1.12 alternative.

**Comment by mindforger** [comment]
try disconnecting the mekanism universal cables that cross the chunk borders and temporary contain energy production inside each individual chunk (or cheat in infinite power sources to keep everything running), these are the only ones i know (from what i can see in your picture) that may cause this 
a good rule of thumb in the past was to keep the ae2 system and it's power source chunkloaded all time

**Comment by phit** [comment]
That's not really a solution for a somewhat public server, if I let everyone chunkload their base  24/7 I get sub 5 TPS after a day. I'd much rather figure out which mod is responsible for this, so I can get this patched.
For the same reason I can't really fix the cabling for every player, but I'll try it temporarily in a couple hours.

**Comment by mindforger** [comment]
please also add a few more screens of the chunk so one could see what's more there, maybe causing the update if the cables don't prove guilty

**Comment by phit** [comment]
Ok, I tried basically to remove any form of tile crossing chunk boundaries and it is still happening.. without some mod that logs stacktrace for loading this is gonna be impossible

I also checked `/forceload query` for anything nearby that could possibly lazy load the chunk but nothing. `/mek chunk clear` also made no difference and reported 0 chunks as being "watched".

Here's some more pictures, basically I had removed everything going across chunks, including the drawer controller https://imgur.com/a/TaT42ws
