### ISSUE TITLE
Unable to load model

### ISSUE THREAD

**Issue by Vulcanoz** [AppliedEnergistics/Applied-Energistics-2#4964]
In the console:
Unable to load model: 'appliedenergistics2:dummy_fluid_item#inventory' referenced from: appliedenergistics2:dummy_fluid_item#inventory: java.io.FileNotFoundException: appliedenergistics2:models/item/dummy_fluid_item.json

Fabric Loader: 0.11.1
Fabric API: 0.30.0
Applied Energistics: 8.1.0 Alpha 13

**Comment by L0rdLogan** [comment]
Fluix ME Smart cable does also not have a texture

![image](https://user-images.githubusercontent.com/5092548/106668258-f5a05e80-65a1-11eb-995a-a1e2a2230bdc.png)

**Comment by Mari023** [comment]
@L0rdLogan are you using sodium?
It messes with rendering

**Comment by L0rdLogan** [comment]
I am indeed using sodium
