### ISSUE TITLE
game crashes when i try to start it

### ISSUE THREAD

**Issue by WHYUMAD** [AppliedEnergistics/Applied-Energistics-2#4967]
so when i start minecraft it loads everything fine except when it gets to applied energistics it crashes

here's the crash log: https://pastebin.com/DtyiEqCM

- Environment: 
im playing on a private moded smp i own here are every mods i have (refer imgur link attached below)
https://imgur.com/gOmNcRD

**Comment by Tahakk** [comment]
`Failed to register dimension for id 2`

some other dimension is already occupying ID 2, reassign it in config and try again

**Comment by WHYUMAD** [comment]
@Tahakk is there any way to dirrectly find which dimension id is occupying it or do i have to manually search for it?

**Comment by WHYUMAD** [comment]
nvm found the mod which was causing the problem thx for the help!
