### ISSUE TITLE
Add keybind to open Wireless Terminal from anywhere in your inventory much easier.

### ISSUE THREAD

**Issue by TheUnderTaker11** [AppliedEnergistics/Applied-Energistics-2#4968]
**Describe the issue**

Simply add a keybind to open to Wireless terminal. I'm suggesting this due to the fact that right now I'm playing a modpack, and the only thing swaying me to Refined Storage, even though I love AE much more, is the fact I know I will never be able to keybind it without the "Wireless Crafting Terminal" mod being updated. I'm amazed it's not be added to the base mod by now.

**Environment**

- Environment: N/A, this is a suggestion

**Comment by yueh** [comment]
When used correctly the wireless terminal is a pretty powerful tool. For now I simply consider that sacrificing a single hotbar slot is an acceptable compromise. Minecraft itself also does not allow you to bind your pickaxe to a hotkey and then stuff it into the player inventory, instead it needs to be on the hotbar to be used.

Additionally AE2 already removes a large part of the inventory management of minecraft, so keeping a bit around as gameplay decision is not that bad.

**Comment by shartte** [comment]
I actually like this one :-P

**Comment by yueh** [comment]
Certainly not for the case of just stuffing it somewhere in your inventory, ideally even inside a random bag.

I'd guess a hotkey when it's on the hotbar is fine, but mostly useless. There are also other problems like we currently lock the terminal (and other stuff like portable cells) when being used, so a player cannot accidentally throw them into the network. Or even the portable cell into itself. How we do this is pretty hacky and I am not even sure, if this works for anything but the hotbar.
So it would also be placed on the "can be done once we refactor the GUI stuff" list.

Another option would be to make it a bauble, if that is still a thing. So players would still have to compromise about their ideal setup. So basically anything which falls under "have your cake and eat it" is out.
