### ISSUE TITLE
No more than 8 P2P input tunnels on a network

### ISSUE THREAD

**Issue by theLadyStardust** [AppliedEnergistics/Applied-Energistics-2#4969]
**Describe the bug**

By placing more than 8 P2P ME tunnels on a singular network (either input or output), the network goes down. 

**To Reproduce**

Place more than 8 p2p tunnels in the same network.

**Expected behavior**
In earlier versions, you could have up to 16 p2p tunnel pairs along the same dense cable (32 total channels). However, now the network goes down. 

**Additional context**

With 8 P2P tunnels:
![image](https://user-images.githubusercontent.com/63514508/107087476-1c88ab80-67c1-11eb-99a3-7af77f230e42.png)

Network diagnostic: 
![image](https://user-images.githubusercontent.com/63514508/107085992-ed713a80-67be-11eb-9747-0d00d05ca4af.png)

With more than 8: 
![image](https://user-images.githubusercontent.com/63514508/107086103-214c6000-67bf-11eb-9df3-e6bdde1ceccd.png)
Network diagnostic:
![image](https://user-images.githubusercontent.com/63514508/107086014-f8c46600-67be-11eb-8641-dba340ff2e9d.png)

It's not a power issue, I tested with a creative energy cell.

I'm not overloading channels, each 4 p2p tunnel leads into a smart cable, then into a singular smart dense cable. Having more than 8 tunnels on a network worked before 1.16.4, so I'm unsure if it's a bug or feature. 

**Environment**

- Environment: Latest release, 8.2.0, on forge 35.1.36.

**Comment by shartte** [comment]
Hm, I am unaware of anything specific that'd limit P2P tunnels to 8 per network. There were no changes I am aware of either for 1.16.x.

**Comment by yueh** [comment]
Adhoc networks were always limited to 8 devices since 1.7.2

**Comment by shartte** [comment]
Oh, I missed that there wasn't a controller. Oops.

**Comment by theLadyStardust** [comment]
Oh, huh. Alright, ty! And yea, I added controllers and now its working fine
