### ISSUE TITLE
Tag 1.16.5 on CurseForge to enable custom profiles to add the mod

### ISSUE THREAD

**Issue by paulhlschr** [AppliedEnergistics/Applied-Energistics-2#4971]
**Question/Request**
Is it possible to tag AE2 on CurseForge with 1.16.5, as custom profiles and modpacks are not able to include the mod using the CurseForge client, if the profile runs on Forge 1.16.5?

**Comment by yueh** [comment]
Forge for 1.16.5 is marked as potentially breaking compatibility with 1.16.4. While we should be compatible with both vanilla versions, we had Forge introduce a couple breaking changes in other 1.16.x version. Therefore for now we will not mark a stable release as compatible with 1.16.5 as this could change tomorrow. 

However the next release of 8.3 will support 1.16.5, potentially also as minimum requirement in case we can not support other 1.16.x versions simultaneously.
