### ISSUE TITLE
Can't craft powah's items.

### ISSUE THREAD

**Issue by DiogoPortela** [AppliedEnergistics/Applied-Energistics-2#4976]
**Describe the bug**
If you try to craft powah's Ender Gate (Hardened) on a ME Crafting Terminal it won't do it.

**To Reproduce**
Try to craft the item from powah.

**Expected behavior**
Item should be crafted.

**Environment**
Minecraft 1.16.5
FTB Presets Direwolf20  1.6.1
Client: Ubuntu 18.04
Server: Windows 10

**Comment by yueh** [comment]
This is a bug with powah. They marked these items as unstackable, but the recipe will craft 4 at once. Therefore we could only attach 1 of it to the player hand or inventory and would potentially lose the other 3 crafted ones. To prevent this we simply err on the side of caution and do not try to craft it at all.

Either they need to change their recipe to only produce 1 item or allow them to stack to at least 4 items.
