### ISSUE TITLE
Server Side error on cable bus

### ISSUE THREAD

**Issue by Xabi08YT** [AppliedEnergistics/Applied-Energistics-2#4979]
Hello, when i want to start my server with the last version of this mod, i got 3 big errors about cable bus:

https://pastebin.com/aD2jFfxV

Get a server on aternos and add many mods in Magma Software with some plugin

For the envirronement, i can't, the server won't start!

**Comment by mindforger** [comment]
you are not even providing ANY version info or what your mod setup looks like ... how do you think one is supposed to help then?

please read the tempplate carefully and provide the required informations when creating an issue
