### ISSUE TITLE
Channels

### ISSUE THREAD

**Issue by Biria90** [AppliedEnergistics/Applied-Energistics-2#4982]
I apparently have not enough channels for any of my busses anymore since i moved my controller. I feel like im being an idiot but many thanks for the help.
![2021-02-13_19 15 00](https://user-images.githubusercontent.com/79021849/107859238-f2be2d00-6e2f-11eb-902e-2f11ed2d1e1b.png)
![2021-02-13_19 15 05](https://user-images.githubusercontent.com/79021849/107859239-f356c380-6e2f-11eb-9627-d578921cebb0.png)

![2021-02-13_19 15 11](https://user-images.githubusercontent.com/79021849/107859229-edf97900-6e2f-11eb-95ba-6e96363f62b1.png)
![2021-02-13_19 15 15](https://user-images.githubusercontent.com/79021849/107859230-ee920f80-6e2f-11eb-8b08-91ed094fc01f.png)
![2021-02-13_19 14 44](https://user-images.githubusercontent.com/79021849/107859231-ef2aa600-6e2f-11eb-98db-5dd1274bbd66.png)
![2021-02-13_19 14 46](https://user-images.githubusercontent.com/79021849/107859232-f05bd300-6e2f-11eb-9396-13c6aada0ad8.png)
![2021-02-13_19 14 50](https://user-images.githubusercontent.com/79021849/107859234-f18d0000-6e2f-11eb-8b8e-c3316c445447.png)

**Comment by mindforger** [comment]
well ... a fluix cable only handles 8 channels even if connected to a controller

and a single cable attached only provides 32 channels in total ... so if you need something like 128 channels, you have to attach 4 dense cables and branch out from your controller, you seem to have misunderstood the function of the controller ... it only provides 32 channels per side and acts as a relay between cable segments than can handly only so much channels themself

also be aware, blocks can only handle 8 channels, so any interconnected blocks can only share 8 channel to its neighbours
