### ISSUE TITLE
 me interface extender with 3x3 different outputs

### ISSUE THREAD

**Issue by lublak** [AppliedEnergistics/Applied-Energistics-2#4984]
**Describe the feature**
Currently the me interface with a crafting pattern outputs the items sequential.
I have some multiblock machines that needs an item in different imports.
So my idea is a me interface which is 3x3 blocks big.
Or more like an extendable me interface with me interface extender.
Each me interface extender block represents a crafting table slot of the pattern. Only one me interface and 8 me interface extender are allowed to be connected.
If you now craft an item based on the pattern in the me interface it just puts each item into the right me interface extender and me interface.

**Reasons why it should be considered**
It can be help to provide a autocrafting for multiblockmachines and also can help for the "more than 3x3 pattern" problem.
For the "more than 3x3 pattern" you can use two extended me interfaces with 2 different patterns.
First pattern creates a placeholder item with 9 items and second pattern use the placeholder item and 8 items (so 17 items) to create a new item. With the extended me interface you can simple filter you placeholders.

It allows you to route your items more more precise.

**Additional context**
basic Implementation idea:

```
Me interface on Export ->
    if me interface conntected to me interface extender ->
        export to the me interface extender
    else
        default behaviour
```

I don't know if im right, but the lines should be here:

https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/main/java/appeng/tile/misc/InterfaceTileEntity.java#L249
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/main/java/appeng/helpers/DualityInterface.java#L788
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/main/java/appeng/helpers/DualityInterface.java#L495

**Comment by yueh** [comment]
This is already solvable with AE2 alone in most cases.

Just a few edge cases might not work perfectly, like needing the same item to be delivered to multiple inputs in precise amounts and the machine not taking care when overfilling it. But that is something most other pipe mods will also not be able to handle reliably, so these are in my opinion up to the mod itself to provide their own solution for it. Assuming it was not introduce to actually enforce manual operation.

**Comment by lublak** [comment]
@yueh i was talking about the create mod.
I try to use create with a 3x3 crafter, because i wan't to reduce the modpack only use the create mechnical crafter.
So i try to match the pattern of 3x3 from ae to the 3x3 mechnical crafter. But currently in my brain it needs a hell of engineering.
Also with "empty" slots of the pattern i think it is nearly impossbile currently. Only with placeholder items, which is a ugly solution.
You said it is possible. Could you please give me a hint? I'm not using any other technic mods.
If you say you don't want to have this feature in this mod, i can understand it. But i was thinking that it would be usefull and not to complex to implemented.
I could also try to implement it myself with a pull request.

**Comment by yueh** [comment]
No idea about the create mod besides having seen some screenshots. So I can only guess what it does.
If it is a machine for crafting normal shaped or shapeless recipes, that might be a bit more tricky to use. But that is why we have the molecular assembler. If it's some sort of processing machine, then it's really up to how it works. Could be easy, could be hard.

However based on the screenshots I did see, it really looks more like factorio or similar with a setup to continuously craft a single or couple of items. Like a machine producing torches from a tree farm and turning it into charcoal, planks, sticks and so on forever. Not really for on demand crafting of any item.

Nevertheless this is an issue tracker and not really a place for build help. There are better places for it. So I will not really provide it here to avoid spoiling it for someone else in case they want to come up with their own solution.

**Comment by lublak** [comment]
@yueh you can demand craft any item. It takes a redstone imput to start the crafting process.
So you can craft with a 3x3 grid any item you wan't. just trigger with a redstone.
yes for building tips there is a better place.

Nevertheless, I am trying to develop an addon for AE2 that has this functionality.
But that will be a lot of work as most of the functions of ae2 are private.
Like pushItemsOut, hasItemsToSend, isBusy. But thanks for your time :)

**Comment by yueh** [comment]
That was more with the overall build in mind. 

Say you build some contraption with a chest as input and by placing 6 oak planks into it, it would know that it should craft a set of doors. And not trapdoors, which also need 6 planks. Or anything else you could craft from 6 planks like 3 sets of sticks, 6 buttons, 2 sets of bowls, a boat, etc. As well as also know that you just didn't forget to bring some sticks with you to craft signs and it should wait until you got around adding them on the next day.

I would assume create is more designed towards the player building some machine, which can only craft doors, probably from every log type. But that's it. And maybe even designed to it a sapling as input and not just the final planks.

A generic interface which just replaces a molecular assembler with a crafter from create doesn't really offer much in terms of difficulty. Just needs more space. As well as most likely bypasses half or more of the gameplay mechanics added by create.
