### ISSUE TITLE
Crashes while loading together with AVP

### ISSUE THREAD

**Issue by Bastelking** [AppliedEnergistics/Applied-Energistics-2#4989]
AVP and applieenergistigs are not compatible at same time, because if i have both installed the game crashes due to an Server error, it sais Dimensin 3 could not be loadet, because it already exists. 

Download AVP (Alien vs Predator) and Applied-Energistics-2 at the same time on forge 1.12.2 and it will crash while loading.

Minecraft crashes in loading state, due to an server error

**Additional context**
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Energistics 2 (appliedenergistics2)
Exit Code: -1
https://pastebin.com/gAJSJCTd

Exit Code: -1
- Environment: Minecraft Java 1.12.2 forge,

**Comment by mindforger** [comment]
Just go ahead and use the configs and change the dimension id of either mod .. PS 1.12 is not supported anymore
