### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by thekiller9583** [AppliedEnergistics/Applied-Energistics-2#5001]
when I load up i cant get past the loading screen. i don't know what is causing this. it is the only mod i have installed.

https://pastebin.com/WDGL3PRQ

**Comment by ModernGamingWorld** [comment]
@thekiller9583 It related to this forge commit? Looks like this is what's writing the log entries anyway MinecraftForge/MinecraftForge@d2cfda3 but I made an issue about this and it got closed cause they felt like it was a forge issue when its not

**Comment by yueh** [comment]
When searching for the error, there are multiple reports for Forge going back to at least 1.14. Maybe also 1.13 if it uses the same config system.

The recommended solution was always to delete the affected config file and have it regenerate during the next start as the old file did get corrupted for some reason.
