### ISSUE TITLE
Game Crashes when pressing enter in the ME crafting terminal

### ISSUE THREAD

**Issue by Nathan-Matharu** [AppliedEnergistics/Applied-Energistics-2#5002]
When using the crafting terminal to search up items, pressing the enter key crashes the game because of "keyPressed event handler"

**Describe the bug**

When enter is pressed while in the ME crafting terminal, the game crashes

**To Reproduce**

Open a ME crafting terminal
Start searching for any item
Press Enter
Crash

**Expected behavior**

Accidental keystrokes do not crash the game

**Additional context**

https://pastebin.com/H08j55JY

**Environment**

- Environment: 
Minecraft version: 1.16.4
Forge Version: 35.1.4
AE2 Version: 8.2.0

**Comment by RoDaBaFilms** [comment]
Most likely an issue with Inventory Tweaks or some form of incompatibility with invtweaks
`at invtweaks.util.Sorting$$Lambda$15217/690358676.test(Unknown Source) ~[?:?] {}`
