### ISSUE TITLE
Crash on Teleport

### ISSUE THREAD

**Issue by CrossVas** [AppliedEnergistics/Applied-Energistics-2#5004]
**Describe the bug**

The world is crashing when teleporting to my base. 

**To Reproduce**

1. Make a teleport at your base (I use mekanism teleport);
2. forceload the chunk where you have a mid-game base and ae system (interfaces, buses, controllers, cables);
3. Go far away from your base and set another teleporter to your base; 
4. Teleport to your base using teleports.

**Expected behavior**

Load my base and not crashing. 

**Additional context**

[crash-2021-02-24_14.15.25-server](https://paste.ubuntu.com/p/vTz5gDJ88y/) - pastebin link

**Environment**

- Environment: 
Minecraft: 1.16.5
AE: 8.3.0-alpha.1

!!! Also tried with 8.2.0 release build: works fine. 
Maybe I should reorganize my cables. I feel like I'm missing something, but the fact that previous version worked fine makes me think that this is not related to my way of cable management. 

F3+C crashlog: [pastebin](https://paste.ubuntu.com/p/BCDJRZTVT9/);

Spoilers:
<details>
  <summary>First picture: my base from top. I have a multiblock controller, another controller which take channels from the multiblock and spread it around the base. </summary>
  
![2021-02-24_15 16 14](https://user-images.githubusercontent.com/25727222/109012382-a0480080-76ba-11eb-85bd-0db96faa4c62.png)
</details>
<details>
  <summary>Second picture: the chunk where I'm teleporting - floor 1</summary>
  
![2021-02-24_15 21 16](https://user-images.githubusercontent.com/25727222/109012836-206e6600-76bb-11eb-8ba4-10af3d101367.png)

</details>

<details>
  <summary>Third picture: same chunk - floor -1. Also the way I use p2p to get channels</summary>
  
![2021-02-24_15 16 30](https://user-images.githubusercontent.com/25727222/109012874-2b28fb00-76bb-11eb-8c61-c446035f0c54.png)

</details>

<details>
  <summary>4th picture: same chunk - some cable-management (2 p2p tunnels, 2 dense smart cables going to my storage room).</summary>
  
![2021-02-24_15 21 55](https://user-images.githubusercontent.com/25727222/109012956-4431ac00-76bb-11eb-9b6f-3ca8ccac17ff.png)

</details>

**Comment by yueh** [comment]
There is a bug which causes clientside tile entities to be exposed to the serverside when playing in single player.
