### ISSUE TITLE
Turning channels off puts server in boot loop ( 1.7.10 )

### ISSUE THREAD

**Issue by dudeman1k** [AppliedEnergistics/Applied-Energistics-2#5005]
**Describe the bug**
Simply turning channels off in the server config puts the server in a boot loop. Turning channels back on resolves the issue but I want to run with channels off. 

**Expected behavior**
The server should boot normally

**Additional context**
I cant currently provide the server logs but I am hoping that this is a known isssue with an easy fix.

**Environment**
Omega adventure pack v3.37 for minecraft 1.7.10. Shockbyte 16GB offsite server.

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.16 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
