### ISSUE TITLE
Avoid putting the server thread into wait during a craftingjob

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#5007]
Currently the crafting thread can put the server thread into wait for a short time per tick. Which should be avoided and instead simply allow the `CraftingJob` a bit more time to run each tick.

**Comment by yueh** [comment]
This might be impossible without refactoring everything into an iterative process instead of the current recursive one.

But it should certainly be possible to improve the code quality and precision in regards to the configured time per tick.
Also it should be a global time limit and not per world, so it is fixed to 5ms by default per tick and not scale with the number of worlds/dimensions to potentially over a value of 50ms.

**Comment by Technici4n** [comment]
> This might be impossible without refactoring everything into an iterative process instead of the current recursive one.

Indeed, as accessing any block in the world from the crafting thread will deadlock the chunk manager.

> so it is fixed to 5ms by default per tick and not scale with the number of worlds/dimensions to potentially over a value of 50ms.

We'll see when/if that is ever reported, it seems quite niche.
