### ISSUE TITLE
Missing textures on cables and terminals when placed.

### ISSUE THREAD

**Issue by jothethe** [AppliedEnergistics/Applied-Energistics-2#5009]
**Describe the bug**
The textures for the cable and terminal blocks are missing, and are instead black and magenta checkerboard. 

**To Reproduce**
Unsure? It's simply there.

**Expected behavior**
Expected the texture to not be a checkerboard.

**Additional context**
![Screenshot](https://user-images.githubusercontent.com/79672569/109234503-71e92480-7791-11eb-8094-7e6ce062a837.png)

**Environment** 
I'm using Fabric.

log from the forced crash: https://pastebin.com/mWeTqmGV

**Comment by mindforger** [comment]
Caused by sodium, you may report it to them eventually

When looking for existing issues, please include closed issues in your search
