### ISSUE TITLE
channel disable config

### ISSUE THREAD

**Issue by A009i8** [AppliedEnergistics/Applied-Energistics-2#5010]
hi

i think every one of us want a config Feature that we can disable channel in the the 1.16.4.

**Comment by mindforger** [comment]
duplicate https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4621

**Comment by A009i8** [comment]
I want a answer from the dev not from you no one have a answer so why you clone a Feature quation ?????

**Comment by mindforger** [comment]
yueh IS a dev form AE2 and he answered already to this question, so i called it duplicate, gave you a link to the dev response to save them time when wokring on actual issues ... cool down

**Comment by A009i8** [comment]
Bro I Tag this for a Feature not a issue.

**Comment by mindforger** [comment]
irrelevant in what color you paint it or what paper you wrap it, just read the answer in the linked issue

also don't "Bro" me thats rude

**Comment by A009i8** [comment]
Okey sis
