### ISSUE TITLE
All cables drop in Creative mode

### ISSUE THREAD

**Issue by saltyseadoggo** [AppliedEnergistics/Applied-Energistics-2#5016]
**Describe the bug**
Cables drop their respective items when broken by a player in Creative mode, which is inconsistent with vanilla behaviour, in which things broken by Creative mode players do not drop their items. This effectively makes testing designs using cables in Creative mode to be a bit annoying due to the item drops that can pile up in the player's inventory or around them.

**To Reproduce**
- Start Minecraft with the Fabric loader and AE2 in the mods folder.
- Create a new world in creative mode.
- Place down any cable, then break it. It drops itself.

**Expected behavior**
Cables would not drop their items when broken in Creative mode.

**Environment**
Minecraft version: 1.16.5
Fabric Loader version: 0.11.1
AE2 version: 8.2.0 alpha 1

**Comment by shartte** [comment]
Fixed by #5032

**Comment by shartte** [comment]
And thanks to @Technici4n
