### ISSUE TITLE
Please separate Forge/Fabric as 2 seperate curse projects.

### ISSUE THREAD

**Issue by schradieck** [AppliedEnergistics/Applied-Energistics-2#5022]
probably too late now, but will request anyways.

PLEASE separate the curse projects for Forge/Fabric. as a pack builder a mod with both versions in the same project is a nightmare, as curse is not smart enough to know the difference between a forge/fabric mod, and will ALWAYS grab the newest version when either adding or updating a mod regardless if said version will cause the pack to no longer work.

while manually specifying which version to download is an option, it becomes a major hassle when you have a pack with 200+ mods and you need a list of which ones you can click "update" and which mods will kill the pack if you do that.

**Comment by shartte** [comment]
Curse promised to fix this ages ago, especially with the Overwolf stuff.

We're not going to split the project on CF.
