### ISSUE TITLE
Crash on Fabric server restart when crafting

### ISSUE THREAD

**Issue by Blardow** [AppliedEnergistics/Applied-Energistics-2#5023]
**Describe the bug**

Playing on All of Fabric 3 (8.2.0 alpha-1, I didn't seem to find this bug in alpha-2's changelog), the server will hang after a restart while crafting. The only fix was to manually disable the crafts through NBT editing, and reboot.

**To Reproduce**

I'm not 100% positive these are the exact steps to reproduce, as I'm just hosting the server and haven't been on myself, but I can say (by looking at the NBT), it is crashing after the server restarts, while the autocrafter is crafting something that it's said to do by an export bus with a crafting card, no player crafting seems to be the cause (though that doesn't necessarily mean it wouldn't cause it). If it helps, the exact recipe that seems to be there during most of the crashes is the 3 sawdust + 1 water bucket = 3 paper recipe from Tech Reborn (being done as a crafting pattern in a molecular assembler), though that recipe works perfectly time when not during a restart. This may just be a coincidence as that just happens to be one of my only autonomously activated crafting recipes. This has happened to me twice, and I've had to go in and clear out the crafting units with NBTExplorer both times to fix it.

**Expected behavior**

When crafting as the server restarts, the craft should resume just as normal when it turns back up.

**Additional context**

Here is the crashlog:
https://pastebin.com/pegDKpCD
Here is an NBT snippet that shows the crafting unit in question that I have to clear out in order to make the server no longer be in a crash loop:
https://i.imgur.com/kck7pdL.png
There are more than one of these that I need to clear out, but they all have very similar data.

**Environment**

- Environment: Environment details are in crash log, but to re-iterate, it's on a server on a Linux environment, running All of Fabric 3 but with three additional mods (being, BetterNether, Astromine, and Origins), plus an extension to Origins (Origins extra), and KubeJS scripts that do things entirely unrelated to AE2, and unrelated to the crafting recipes being executed (alter Origins things, and change some endgame recipes for Astromine compatibility, entirely unrelated to any of the crafting currently being done).

**Comment by Technici4n** [comment]
Should be fixed in 0.8.2-alpha.3.
