### ISSUE TITLE
Blocks not rendering while using Chocapic13_V9 shader

### ISSUE THREAD

**Issue by KompetenzAirbag** [AppliedEnergistics/Applied-Energistics-2#5028]
Blocks are just invisible (X-ray like, I can see caves through the block) while using Chocapic13_V9_high shader (if I disable the shader, the blocks render).
I am using the lastest version of fabric and the lastest shader version (aswell as lastest Optifine and Optifabric version).

**Comment by yueh** [comment]
Duplicate of #5027
