### ISSUE TITLE
Make crafting CPU selection a scrollable list instead of an iterating button

### ISSUE THREAD

**Issue by Jack-McKalling** [AppliedEnergistics/Applied-Energistics-2#5044]
**Describe the feature**

On the left of the Crafting Jobs GUI, there would be a list of CPUs and named CPUs that the user can select from. They could scroll through the list if it gets too tall to display, similar to the job itself. When they would click any of them, that CPU would be selected for the job. An "Automatic" option would still be available, at the top of the list.

**Reasons why it should be considered**

This way it would cost the user to only click _once_, for the CPU selection. Regardless of where in the list the desired CPU is sorted. Consequently, it will also be possible in one glance, for the user to see which CPUs can be chosen from (and thusly are recognised by the network). Clicking the same button repeatedly to try and find this out, is tedious and non-informative.

**Additional Context**

I made a simple mockup of the would-be screen that gets shown when you're about to start a job, but the same could apply to the screen with existing/running jobs.
![crafting job gui](https://user-images.githubusercontent.com/14236702/110224202-dca90700-7ed9-11eb-9b21-d95346b39dd5.png)

**Comment by yueh** [comment]
Would be nice (with a slightly more fitting UI). But most likely never happen until we have a dedicated UI dev.
And needs a couple other changes like iirc cpus do not have static names.

**Comment by Jack-McKalling** [comment]
Yes, you can rename a CPU. if any block contained within the multiblock has been renamed on an anvil, its name will show up here instead of the automatic incremented name.

What do you mean slightly more fitting? I drew this in paint, from elements that were already there and are an example.

**Comment by Technici4n** [comment]
Implemented in #6005.
