### ISSUE TITLE
Security Terminal Bug

### ISSUE THREAD

**Issue by xWaller0119** [AppliedEnergistics/Applied-Energistics-2#5045]
**Describe the bug**
When using a Security Terminal, it randomly breaks anything over time. Cables, Molecular Assemblers, Interfaces, Etc. You name it. Been a thing for atleast a year+ now. Idk how it hasnt been noticed...

**To Reproduce**
Use a Security terminal and wait..?

**Expected behavior**
To not break any of the networks pieces... Duh.

**Additional context**
https://i.imgur.com/LOfWyyi.png
https://i.imgur.com/J3DWAm3.png

**Environment**
Not sure what this means but, im just doing a playthrough on a modpack, trying to do stuff, and I go to craft something, its missing a pattern, go to my assemblers and interfaces and a few are gone..? No crashes.

- Environment:

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.16 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
