### ISSUE TITLE
Crash on beta version when placing spatial anchor

### ISSUE THREAD

**Issue by Dragonlord1005** [AppliedEnergistics/Applied-Energistics-2#5046]
**Describe the bug**

I was in a creative testing world and I placed the spatial anchor and the game crashed, and then it corrupted the world file
**To Reproduce**

Place the spatial anchor, pylon, and the other spatial thing (there was three, I forgot the other one's name)
**Expected behavior**

It should just be placed, but it instead crashes
**Additional context**

https://pastebin.com/3gerny2e
**Environment**

- Environment: 
https://pastebin.com/3gerny2e

**Comment by yueh** [comment]
This is a crash in forge itself. Or maybe the usual suspects like optifine causing it. Try it without optifine and probably different forge releases.
