### ISSUE TITLE
Loading a world with a Tech Reborn thermal generator powering an ME terminal and drive causes subsequent worlds to load incorrectly

### ISSUE THREAD

**Issue by saltyseadoggo** [AppliedEnergistics/Applied-Energistics-2#5047]
Copied from [an identical report on Tech Reborn's repository.](https://github.com/TechReborn/TechReborn/issues/2364)

**Describe the bug**
My partner, in her modded survival world, constructed the machine shown in the image below, using a Tech Reborn thermal generator to power an adjacent Applied Energistics 2 energy acceptor, which in turn powers a ME terminal and an ME drive through one block of fluix glass cable. She later found that, upon exiting her survival world and entering any other world, the world would behave unexpectedly after a few seconds of joining. In the subsequent world,
- All entities stopped moving: a minecart on a rail or in flowing water and an iron golem in flowing water, for example.
- The F3 menu began showing both Server Light values as ??
- She could no longer flick levers, but could still open and close a fence gate
- Bumping into entities did not cause them to move, but would cause her character to move.
- She could no longer pick up items.
- And, most frustratingly, upon exiting the world, the game would stop responding, and the java process would need to be ended through Ubuntu's system monitor.

**Steps to Reproduce**
- Place the two worlds within this archives into the saves folder.
[bug reproducing worlds.zip](https://github.com/TechReborn/TechReborn/files/6097850/bug.reproducing.worlds.zip)
- Start Minecraft with the following mods in the mods folder:
Tech Reborn 3.8.1 build 221
Reborn Core 4.7.2 build 132
Fabric API 0.31.0
Applied Energistics 2 8.2.0 alpha 1
- Play the world named "machine world [load first]." This is a superflat void world containing only the bugged machine.
- Simply let your character exist in this world for a moment, then save and quit to title.
- Play the world named "subsequent world [load second]." This is another superflat void world containing a minecart in flowing water, two villagers and a minecart on powered rails to showcase the issue.
- Simply exist in this world until all of the entities stop moving.
- Check the F3 menu; the Server Light values both show as ??
- Place down a lever, and attempt to flick it. The player's hand moves, but the lever does not flick.
- Bump into any of the entities. They will not move.
- Save and quit to title. Minecraft will stop responding.

**Screenshots**
The machine described above. The thermal generator was given ten buckets of lava, and the ME drive contains three empty 4K storage cells and one empty 64K storage cell.
![2021-03-07_12 14 29](https://user-images.githubusercontent.com/69029346/110253369-c8e3bc00-7f3e-11eb-83a9-c56ce06f5842.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: Fabric

**Logs**
A fresh log generated by following the above steps exactly.
https://hatebin.com/gjmzmveits

**Additional context**
The bug was originally observed in a modded survival world with many other mods active, and a version of one of gnembon's iron farm world downloads with mods loaded, but both of the worlds above were generated and loaded with only Tech Reborn, AE2 and their dependencies.

**Comment by Technici4n** [comment]
Hello, many thanks for this detailed issue report! I can reproduce this with the versions you linked but not in dev with the more up-to-date builds.
I am pretty sure this was fixed when #4983 was fixed. Can you try again using 0.8.2-alpha.3?

**Comment by saltyseadoggo** [comment]
Yes, the issue appears to be resolved if I follow the steps above. Thank you!
I didn't notice the update because I check Curseforge's Fabric tag for updates daily, but AE2 lacks the Fabric tag. If I may make a request, and assuming that you don't have a reason for not using that tag, could you add the Fabric tag to this mod on Curseforge so that it can be found by those searching by the tag?

**Comment by Technici4n** [comment]
I am pretty sure AE2 would then be seen as fabric-only by a lot of people, and there would probably be other problems as well.

**Comment by saltyseadoggo** [comment]
I've seen mods available on both loaders use the Fabric tag, but I can understand that. Another thing to note is that I've seen a lot of people on the Fabric subreddit, for example, who didn't even know that AE2 was available on Fabric, because, unless you hear about it or go digging through its files tab on Curseforge, there's no real way to know, y'know?

**Comment by saltyseadoggo** [comment]
Just something to consider. Anyways, I will close this since it's fixed.~
