### ISSUE TITLE
ME interfaces transmit power to attached molecular assemblers when in block form but not part form

### ISSUE THREAD

**Issue by Hawk777** [AppliedEnergistics/Applied-Energistics-2#5054]
**Describe the bug**
If I attach an ME interface block to an ME network and place a molecular assembler adjacent to the ME interface block, everything works fine. If I place an ME interface *part* on the side of a network cable and place the molecular assembler adjacent to it, the molecular assembler doesn’t work (device offline and does not perform crafting) unless I also bring wire directly to the assembler (it doesn’t need any channels—it still works with quartz fibre—but it does require its own wire connection).

**To Reproduce**
Build a working ME network. Attach an ME interface in either block form or part form. Place a molecular assembler beside the interface such that the assembler is not touching any other part of the network.

**Expected behavior**
I expected the two forms of ME interface to work the same way—either I would have to explicitly power the assembler in both cases, or the interface would power the assembler in both cases.

**Environment**
- Minecraft 1.12.2
- Applied Energistics 2 rv6-stable-7

**Comment by Mari023** [comment]
I am pretty sure this is intentional, as far as I know it works like this since 1.7.10

**Comment by yueh** [comment]
Intentional in two ways. 
First all parts do not transfer power except it is their job like a quartz fiber.
Second a part interface is a directional interface like a block interface pointing in a certain direction, which will also not transfer power in the direction it is facing.

**Comment by Hawk777** [comment]
OK, if that’s what you want it’s fine, but could it at least be documented on the ME Interface page? I didn’t see such a rule (“parts never transmit power”) anywhere in the documentation.

**Comment by yueh** [comment]
Actually the case with parts is probably just a more specific variant of "if a cable doesn't connect, it does nothing". Which should be pretty self explanatory.

**Comment by Hawk777** [comment]
I don’t think it’s that simple. The ME interface in block form acts as an implicit cable, and since it takes up a full block of space visually, you can’t see whether it connects to the assembler or not cable-wise. The ME interface in part form does have a piece of cable running into it visually (as all parts do), and is also in direct physical contact with the molecular assembler, but doesn’t act as a cable connection.
