### ISSUE TITLE
Storing a quantum bridge + spatial anchor inside a spatial storage does not work as expected

### ISSUE THREAD

**Issue by LuckyTeran** [AppliedEnergistics/Applied-Energistics-2#5055]
**Describe the bug**
Storing a quantum bridge + spatial anchor inside a spatial storage cell does not keep the bridge, network and anchor active and the connection to the bridge gets lost.

**To Reproduce**
Build a minimal network in the overworld consisting of:
- Controller
- Creative Energy Cell
- Spatial Anchor
- Quantum Bridge + entangled singularity
- Spatial IO Port + Spatial Cell + Button
- Spatial Pylons
- ME Crafting Terminal

Inside the SCS area build:
- Controller
- Creative Energy Cell
- Spatial Anchor
- Quantum Bridge + the other entangled singularity
- ME drive + storage cell

Go to the Terminal and put items into the Network. Check the Spatial Anchor, it should show something along the lines of "Loading/Spanning x chunks in 1 worlds". Trigger the Spatial IO Port to store the drive, bridge and anchor inside the spatial storage. Check the Terminal again, no Items are visible. Check the Spatial Anchor, it should show something along the lines of "Loading/Spanning x chunks in 1 worlds", so no change. Bring back the SCS Area from storage. The Items should show up again in inside the Terminal. Store the SCS Area again inside the storage. Use "/ae2 spatial tp 1" to teleport inside the spatial cell. Check the anchor inside the cell it now shows something like "Loading/Spanning x chunks in 2 worlds". Teleport back to the overworld with "/ae2 spatial tpback". Check the overworld anchor it now shows something like "Loading/Spanning x chunks in 2 worlds"

**Expected behavior**
When i send a anchor and a quantum bridge into spatial storage i expect the anchor to keep the chunks inside the spatial dimension loaded without the need to teleport inside the cell. The anchor in the overworld should show/update to "Loading/Spanning x chunks in 2 worlds" to signal that the bridged part inside the spatial cell is still loaded and active and it should be possible to access the items inside the drive.

**Environment**
Singleplayer/Multiplayer
F3+C crashlog: [https://pastebin.com/LYcuA0vU](https://pastebin.com/LYcuA0vU)

**Comment by buttpooper23** [comment]
![butt pooper 89](https://user-images.githubusercontent.com/80023047/110737353-d3c67700-81f2-11eb-8f08-c7f9d72cb23c.jpg)

**Comment by buttpooper23** [comment]
![REDEYES](https://user-images.githubusercontent.com/80023047/110737363-dcb74880-81f2-11eb-8b46-db2cc857b648.png)

**Comment by buttpooper23** [comment]
who wore it better ( you have to guesss which is a better one )

**Comment by yueh** [comment]
This is not that easy to to how forge loads chunks and immediately unloads them after a transfer as well as there is no way currently to determine the affected chunks.

We basically would have to chunkload a large enough area to cover a 128^3 cell regardless of where the anchor is placed. Which probably means forcing a 17x17 chunk area to be temporary force loaded and then reduce to the actual network size later. However this could lead to some other inconsistencies.

Ideally a player would teleport into the cell initially and then then setup an anchor. But that is a bit difficult to get then back out of it.
