### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Sunekaer** [AppliedEnergistics/Applied-Energistics-2#5058]
**Describe the bug**
Server crash on load of chunks

**To Reproduce**
Server crash on load of chunks

**Expected behavior**
To not crash

**Additional context**
https://paste.feed-the-beast.com/view/raw/d6f063f8
Modpack: FTB Presents Direwolf20 1.16
forge: 36.0.45
appliedenergistics2-8.3.0-alpha.1.jar

**Comment by yueh** [comment]
Duplicate of #5004
