### ISSUE TITLE
I can't open the Cell Workbench inventory 

### ISSUE THREAD

**Issue by pavuk300** [AppliedEnergistics/Applied-Energistics-2#5066]
When I try to open the inventory, nothing happens. Writes these lines in the log:
https://gist.github.com/pavuk300/ad133f9d7119faca1bbb1281394eaf8b
Video: https://youtu.be/mtVtll6w7bg

Force crash: https://gist.github.com/pavuk300/cdf5b04e3fb09898193d4635bde2b3c8
ver: 8.2.0-alpha.1
minecraft: 1.16.5
fabric-api: 0.30.3
forge:36.0.13

**Comment by Ommina** [comment]
If I'm understanding correctly -- you're using a specialized mod loader to load Fabric mods into a Forge environment.  (Or perhaps the other way around, the forced crash report lists 'Fabric', and libBlockAttributes is in the stack trace.)

I certainly am not speaking for yeuh or shartte, but I'm honestly amazed that the only issue you're running into is with the Cell Workbench.

**Comment by Technici4n** [comment]
AE2 exists for fabric, it's not a hack...

**Comment by Technici4n** [comment]
Jump loader however might be the hack causing forge to be displayed.

**Comment by pavuk300** [comment]
I run Minecraft through curse forge. Modpack: all of fabrics 3.

**Comment by Technici4n** [comment]
Hello, could you try again with the latest AE2? This should be fixed in 8.2.0-alpha.3.

**Comment by pavuk300** [comment]
I can’t, because other versions don’t work on my modpack.

**Comment by Technici4n** [comment]
Why not? Does it crash? If so please post the crash log.

**Comment by pavuk300** [comment]
If I set another version, it just doesn't load into the game. In latest.log nothing about ae2.

**Comment by pavuk300** [comment]
it’s kinda black magic.

**Comment by mandrin92** [comment]
I too was using AOF 3 on Curse (v 2.6.10) and replacing appliedenergistics2-fabric-8.2.0-alpha.1 with appliedenergistics2-fabric-8.2.0-alpha.3 did the job, interface of cell workbench opens now.
