### ISSUE TITLE
Alpha.2 Version causing Chunks to not be saved and strange issues on server. 

### ISSUE THREAD

**Issue by itsTort** [AppliedEnergistics/Applied-Energistics-2#5069]
**Describe the bug**
After upgrading to the Alpha 2 version of AE2 for 1.16.5, I noticed our chunks weren't being saved which was causing a slew of weird problems on the server. Mekanism pipes were disconnecting, Flux Plugs & Points were disconnecting / turning white, but retaining their network. Block states were being extremely weird. I.E, I added 64 blocks of coal to a coal generator, left the room, came back, removed the blocks of coal, added 1 piece of coal, left the room, and the blocks of coal were still in there. Similarly, with the ResourcefulBees Centrifuge, I deconstructed the device in Creative, reconstructed it; but it retained it's past block state with full fuel, and partially processed honeycombs. 

**To Reproduce**

For me, perhaps it was a mod conflict, but just simply installing AE2 Alpha 2 broke our game. 

**Expected behavior**
N/A, things should just work. 

**Additional context**
Forge Version: forge-1.16.5-36.0.42.jar

Log is too large for pastebin. https://www.dropbox.com/s/gmsstcl0m8rwjd4/latest.log?dl=0 here is a copy of our log from last night.  The Dev of Mahou Tsukai had pointed out the (appeng) line next to where the errors start.  

Here is a copy of our server/client mods, as well as all of the configurations we use.
https://www.dropbox.com/s/wivz24cggepa0op/server%20files.zip?dl=0
https://www.dropbox.com/s/w2lnx9z1u2lf6b2/client%20files.zip?dl=0

I reverted our version from Alpha 2 to Alpha 1, and everything appears to be working as normal again. 

**Environment**

- Environment:

**Comment by shortybsd** [comment]
same here! constantly spamming

**Comment by lukeski14** [comment]
same issue here on FTB Endeavour 1.1

**Comment by greystarMC** [comment]
I'm seeing this in 8.3.0-alpha.2. If I'm looking at this right this fix was done on March 16 and 8.3.0-alpha.2 was released on March 13. If this is pending a new release, do you know when one will be made? Thanks.
