### ISSUE TITLE
MC crash upon using RFtools Transmitter and receiver with radiation possible AE2 conflict with rf tools

### ISSUE THREAD

**Issue by mcintosh109** [AppliedEnergistics/Applied-Energistics-2#5071]
Issue description: game crash upon arriving on a Rftools receiver while having mek radiation possable AE2 confilct

Steps to reproduce:
1.get radiation on plyer
2. use the rf tools transmitter and recever
3.game crash

Versions:
Pack: DW1.16.5 Pack Ver1.7.0
Forge: forge-1.16.5-36.0.45
Mekanism-1.16.5-10.0.21.448
Rftoolsutility-1.16-3.0.23
appliedenergistics2-8.3.0-alpha.1

crashlog online ----> https://paste.ee/p/BRrpp
[Crashreport 3.15.21.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/6145139/Crashreport.3.15.21.txt)

will upload to mekanism RFtools crash report as well

**Comment by mcintosh109** [comment]
conflict was determined to not involve Mekanism by their dev team

**Comment by yueh** [comment]
Duplicate

**Comment by shartte** [comment]
See #5004
