### ISSUE TITLE
interface terminal blank

### ISSUE THREAD

**Issue by TheMrCaveman** [AppliedEnergistics/Applied-Energistics-2#5082]
**Describe the bug**

Is the latest version of direwolf20 1.16

**To Reproduce**

put over 100 patterns in the interface terminal and it goes blank
**Expected behavior**

Able to put more patterns in since there is more space for it
**Additional context**

**Environment**

- Environment:

**Comment by mindforger** [comment]
could you please use the issue template to complete your issue report? "latest" is not a valid version information and a modpack this big is not feasible to debug at all ... please try if you can reproduce the issue with just AE2 and note down the version of mods you used to test it
