### ISSUE TITLE
Unable to withdraw Psi CAD from ME storage

### ISSUE THREAD

**Issue by have-a-boy** [AppliedEnergistics/Applied-Energistics-2#5083]
**Describe the bug**

After inserting an assembled CAD of any kind from the mod Psi into an ME storage cell, it becomes impossible to get it back out, or even interact with it in any way. I've reproduced this in a newly created world, with a minimal setup.
<details>
<summary>Screenshots</summary>

Minimal setup
![2021-03-21_13 01 10](https://user-images.githubusercontent.com/33687037/111904927-77145900-8a49-11eb-93a7-a67d219a56e7.png)

Psi CAD in ME terminal after insertion. No amount of clicking will get it back out again.
![2021-03-21_13 02 58](https://user-images.githubusercontent.com/33687037/111904955-9ad79f00-8a49-11eb-9323-208cd2991134.png)
</details>

**To Reproduce**

1. Assemble any kind of CAD from Psi by putting a CAD assembly in the CAD assembler machine.
2. Put the finished CAD into an ME storage cell through a terminal, interface, ME chest or any other kind of IO.
3. Try extracting the CAD from said storage.

**Expected behavior**

Being able to extract the CAD from ME storage or interact with it in any way after inserting it.

**Additional context**

This isn't the first time this happened to me in practice. I have 2 Iron CADs stuck in my system, my friend recently added a Psimetal one to the growing collection. I have tried every workaround and IO interface I could think of, but I cannot get them out again. Please help.

**Environment**

I've encountered this issue in at least two different modpacks that I can recall the version of:

- **All the Mods 6 v1.5.5**
  - Minecraft 1.16.5
  - Forge 36.1.0
  - appliedenergistics2-8.3.0-alpha.2
  - Psi 1.16-91
- All the Mods 6 v1.5.1
  - Minecraft 1.16.5
  - Forge 36.0.13
  - appliedenergistics2-8.2.0-beta.2
  - Psi 1.16-91
- Limitless 3 v1.9.2
  - Minecraft 1.16.5
  - Forge 36.0.1
  - appliedenergistics2-8.2.0-beta.2
  - Psi 1.16-91

Both were started in MultiMC, using the newest Java 8 runtime, with a memory limit of 8 GiB and no additional command line arguments.

Let me know if you need any other details.

Related issues describing the same problem: #4882, #4816

**Comment by mindforger** [comment]
try an export bus with a fuzzy card to get it out of the system i think  this has to do with how Psi is using nbt data

**Comment by have-a-boy** [comment]
> 
> 
> try an export bus with a fuzzy card to get it out of the system i think this has to do with how Psi is using nbt data

Good call, I don't know why I didn't think to try this at the time, but it does work. Thanks for the workaround.
