### ISSUE TITLE
Idle power draw of most devices undocumented

### ISSUE THREAD

**Issue by Hawk777** [AppliedEnergistics/Applied-Energistics-2#5086]
From looking in the source code, I see that most things consume 1 AE/t of power (this is the default in `AENetworkProxy` unless overridden by the individual device, which a handful do but many do not, AFAICT). I had no idea this was the case until looking in the source code! The documentation, as far as I can find, says that it costs 1/128 AE/t for a channel to travel through one node of distance, and it mentions specifically a number of machines that require power (crystal growth accelerator, controller, wireless stuff, quantum bridge, spatial pylon, chest, and drive), but it doesn’t say anywhere that I can see that most of the other devices (such as interfaces and buses) also consume 1 AE/t each, which is quite a lot.

**Environment**
AE2 rv6-stable-7 for Minecraft 1.12, but this is really a documentation issue.

**Comment by mindforger** [comment]
1.12 is not supported anymore and documentaition in this periode was a bit chaotic due to ownership changes, is this still valid for current 1.16?

**Comment by mindforger** [comment]
Sorry for misclick on assignemt, browser acted up a bit

**Comment by shartte** [comment]
Yeah it's still as bad 😁 
I'll leave this open until we do have a guidebook that includes this information (at some point)

**Comment by yueh** [comment]
Guidebook migh not really help here. Many consumers are also somewhat or totally dynamic, so just guessing will not really give a good result. The network tool is still the best option for it.

**Comment by Hawk777** [comment]
> Guidebook migh not really help here. Many consumers are also somewhat or totally dynamic, so just guessing will not really give a good result. The network tool is still the best option for it.

I agree, I did eventually make a network tool and discover this, it’s just that I had no clue that machines other than those explicitly called out even *had* an idle draw, so why would I build a network tool to discover something that I didn’t know existed? So I think it may not be necessary to call out the exact numbers in documentation, but it would be good to point out that the number exists and is nonzero, and if you care what the number is, use the network tool.

**Comment by Technici4n** [comment]
Honestly this can be figured out by just adding the device to a network and using a network tool, so closing.
