### ISSUE TITLE
Dupe with chunks

### ISSUE THREAD

**Issue by STILLCR4CK** [AppliedEnergistics/Applied-Energistics-2#5087]
Hi i find video where ppl show dupe with chunks https://www.youtube.com/watch?v=ZnuplQ5p2BQ&t=1s

How fix it ??

**Comment by shartte** [comment]
1.7.10-1.12.2 -> unsupported

**Comment by shartte** [comment]
p.s.: If you can demonstrate this still works in 1.16.5, I'll take another look.

**Comment by STILLCR4CK** [comment]
> p.s.: If you can demonstrate this still works in 1.16.5, I'll take another look.

Say me just when i can find this block and how i can fix. Im download code, find this item and how fix?
Need decline all enchanted items from pattern!
