### ISSUE TITLE
[Forge 1.16x] Spam of NPE at appeng.hooks.TickHandler.onUnloadChunk(TickHandler.java:180)

### ISSUE THREAD

**Issue by Morpheus1101** [AppliedEnergistics/Applied-Energistics-2#5092]
**Describe the bug**
Major Console spam of https://pastebin.com/P77iWbgE when leaving a loaded area

**To Reproduce**
Load up with only AE2 SMP tp to anywhere away to any location, let it briefly load up, then tp away and watch the console get spammed with above mentioned message

**Environment**
Ae2 Forge 8.3.0-Alpha
Forge 36.1.0
Java 1.8.0_51
Win 10

**Comment by yueh** [comment]
Please use the search next time.

**Comment by Morpheus1101** [comment]
ok after some more deep searching, found its fixed and mentioned in #5069
