### ISSUE TITLE
The panel is turned upside down

### ISSUE THREAD

**Issue by queenjp** [AppliedEnergistics/Applied-Energistics-2#5093]
i use appliedenergistics2-8.3.0-alpha.2.jar and Other things mod

However, when I made a panel and used it, the front and back were reversed, which is a problem.
Is this my problem? Or is it a bug?

I'm playing in Japan and I'm sorry if there's something wrong with English
![2021-03-25_17 41 07](https://user-images.githubusercontent.com/81353934/112444759-bd432280-8d91-11eb-9172-9c93e9028566.png)

**Comment by Mari023** [comment]
you need to place it on a cable, and it won't be upside down
