### ISSUE TITLE
ME Shop Terminal

### ISSUE THREAD

**Issue by AlgorithmX2** [AppliedEnergistics/Applied-Energistics-2#51]
First of all im not speaking English so if this post is not good fix me.

The idea of the terminal is like the ExtraCells Terminal, that you choose fluid and puting a bucket and then its giving you the fluid in a bucket.
so... you choose what you want to buy, its telling you what is the cost, and you put it in special slot.
im not talking about a money system, im talking about paying with items.

Thanks for your attention.

Originally Posted by Avivcool1

This issue was migrated; For original details see http://ae-mod.info/Tracker/0506/

**Comment by MaverickMartyn** [comment]
I hope this doesn't count as necroing.
I just wanted to voice my support for this idea.
