### ISSUE TITLE
Failed to save chunk

### ISSUE THREAD

**Issue by GusNa** [AppliedEnergistics/Applied-Energistics-2#5100]
I'm hosting an Enigmatica 6 server with a couple friends and also added in AE2. I've been encountering a bug where chunks don't save when they are unloaded. If I'm far from spawn doing something, chunks don't save my work unless I do /save-all before I leave.

**Describe the bug**

My latest.log says:
`[Server thread/ERROR] [net.minecraft.world.ChunkManager/]: Failed to save chunk [x, y]
java.util.concurrent.CompletionException: java.lang.NullPointerException ...`
`... caused by: java.lang.NullpointerException
at appeng.hooks.TickHandler.onUnloadChunk(TickHandler.java:180) ~[appliedenergistics2:8.3.0-alpha.2] ...`

**To Reproduce**

All I did was make an Enigmatica 6 server, install AE2 and Simple Voice Chat in both client and server, and play.

To reproduce the bug:
1. Fly far away from spawn or go to another dimension.
2. Make some noticeable changes to the world.
3. Leave the area so that the chunks unload.
4. Verify that the server console is being spammed on unloading chunks that need to be saved.
5. Go back to the changed chunks, all of your changes will be gone.

**Expected behavior**

I would expect chunks to save properly.

**Additional context**

latest.log: https://gist.github.com/GusNa/ab37b80f579d6f05adb5468e34fc3bd7
The issue seems to start on line 3002

**Environment**

forced crash report: https://gist.github.com/GusNa/8732bccb63f458d23361965756696b1e

**Comment by yueh** [comment]
Please use the search before reporting issues.

**Comment by ChallengerPoro** [comment]
hey, do u found a solution for this error?

**Comment by 4rz0** [comment]
> 
> 
> hey, do u found a solution for this error?

See #5069.
