### ISSUE TITLE
Mutliblock Molecular Assembler

### ISSUE THREAD

**Issue by 4Source** [AppliedEnergistics/Applied-Energistics-2#5106]
**Describe the feature**
Molecular assembler as a multibock structure that can be built in different sizes (for example 3x3x3 to 7x7x7).  Consists of housing blocks and core blocks.  The number of core blocks would determine the number of crafting fields that a multiblock assembler would have available.  The housing blocks would only be responsible for the outer shape and of course became the contact area for interface functions.  Now to the actual feature.  If an interface orders to craft a item with the same recipe several times, this order is divided between the several crafting fields and thus built in parallel.  If several crafting orders come from different interfaces at the same time, they are also divided between the crafting fields.

**Reasons why it should be considered**
It would make the whole ME system smarter.  Larger orders would be processed faster without the existence of several assemblers with the same recipe without slowing down the crafting of several smaller orders.

**Comment by mindforger** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3380 for your reference ... but i will not close the issue again, as people tend to only want to talk to dev-level support about features and flame against contributors when they do it :(

**Comment by yueh** [comment]
This is not a request for the linked issue.

It's just requesting something already possible in AE2, just in a dumbed down version so they no longer have to design their networks around their particular needs and just have a magic block. Which usually gets rejected.
