### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by Retrieveryt** [AppliedEnergistics/Applied-Energistics-2#5114]
basically i see most of the AE2 blocks as missing textures (black and purple)

i downloaded the appliedenergistics2-fabric-8.2.0-alpha.3.jar file.

![2021-04-04_23 51 31](https://user-images.githubusercontent.com/80072116/113522432-b215a100-95a0-11eb-9963-bb391224d691.png)
![2021-04-04_23 50 59](https://user-images.githubusercontent.com/80072116/113522433-b3df6480-95a0-11eb-9b7b-1fd095aeeaea.png)
![2021-04-04_23 51 03](https://user-images.githubusercontent.com/80072116/113522434-b477fb00-95a0-11eb-993d-985215705d27.png)

**Comment by Retrieveryt** [comment]
nvm i installed an alpha build

**Comment by Technici4n** [comment]
Duplicate of #4760
