### ISSUE TITLE
Alternate access to ME Chest Inventory

### ISSUE THREAD

**Issue by RobertBouillon** [AppliedEnergistics/Applied-Energistics-2#5116]
**Describe the feature**
I would like to use the ME chest to replace a traditional chest. ME Chest inventory is currently only available if you access the chest from the TOP. This limits its usefulness in various layouts as many of my complex machines are built into walls. When built into a wall, the only access I have is to the storage cell, which is the least-frequent use-case.

Possible alternatives:
1. Shift-Right-Click to access the inventory of an ME chest from the side
2. Allow one side to of the chest to access the inventory, accessible via rotating the block.
3. Allow a terminal to be placed on the chest, which provides direct access to only the contents of the chest.
4. Change right-click to always open inventory. Shift+right-click to access the storage cell.

**Reasons why it should be considered**
ME chests should be superior alternatives to vanilla chests. Given the current access pattern, I almost never use them.

**Additional Context**
![image](https://user-images.githubusercontent.com/612152/113607111-d744f680-9616-11eb-9b55-9b8041612196.png)
A common pattern I use for my lab. ME interface allows me to pipe items directly into / out of ME system. Sometimes I want to limit what I craft - for example, I may not want to grind ALL of my ores, only 10 or so stacks. In that case, I'll drop the stacks into a chest and pull from the chest instead of the ME interface. I can't really use a ME chest to replace a crate (IE or EU2) because I can't access it from the side.

**Comment by yueh** [comment]
Chests can already be rotated like many other AE2 blocks and have their terminal facing whatever direction is more useful.

Using shift + right click might be an idea. But we need a better way to document it first. I am also not really aware of anything using a similar approach, which could make it not really intuitive with the normal minecraft behaviour.
Also this would be highly random as shift + right click is also used by many items (tools) to bypass the block behaviour. Depending on what the player might hold, they cannot even access the cell at all. E.g. while holding a patchouli book, it would instead open the related entry. 
I guess something to consider for later like 1.17 as well as potentially some real unique feature for the chests to make it more useful overall.

There might also be other ideas like splitting the chest at some point, e.g. opening the terminal when clicking on the light gray faces on each side. However with the experience from cables and parts, relying on anything more than having the player pay attention to what side they are clicking, could easily run into dealing with additional reports about why chest behave randomly.

So for now, I hope being able to rotate the terminal face to a side will be sufficient.

**Comment by shartte** [comment]
@RobertBouillon Yes, in short: You should be able to rotate the side that allows you to open the chest to the front.
An alternative that I also like is putting terminals and ME chests into the floor.
