### ISSUE TITLE
Opening ongoing crafting screen causes CTD

### ISSUE THREAD

**Issue by CloWnicide** [AppliedEnergistics/Applied-Energistics-2#5132]
**Describe the bug**
Opening crafting screen causes CTD

**To Reproduce**
Begin auto-crafting of item, open crafting screen, CTD

**Expected behavior**
No CTD when looking at ongoing auto-crafting

**Additional context**
https://gist.github.com/CloWnicide/d6b2256fe305cc531775d3c3adfffe64

**Environment**
Java: 11.0.1.0.0, Forge: 36.1.2, AE2 Version: 8.3.0-alpha.2
Force Crash Log: https://gist.github.com/CloWnicide/c2e8ba13a522e8b62feaba3c509aaec1

**Comment by Technici4n** [comment]
We don't support optifine, please try again without it.

**Comment by sagesse-cn** [comment]
i had the same issue not long ago, but it not a ae issue, you can't any support in here. 

optfine and forge has some compatibility problems, someone use optfore mod to fix it.

good lucky.

**Comment by shartte** [comment]
I can in theory see how this happens. Do you by chance have a slow network connection?

**Comment by shartte** [comment]
Reproduced by forcefully slowing down GUI syncs between server->client.

This is a race-condition and should happen rarely. Will look into fixing this.
