### ISSUE TITLE
(Charged) Certus quartz ore has no tool requirement

### ISSUE THREAD

**Issue by ChloeDawn** [AppliedEnergistics/Applied-Energistics-2#5137]
**Describe the bug**

Certus quartz ore blocks can be mined without a pickaxe, contrary to vanilla ores

**To Reproduce**

Mine a certus quartz ore block with an open hand, experience and certus quartz crystals are dropped

**Expected behavior**

Certus quartz ore to only drop experience and an item when mined with an appropriate tool

**Additional context**

**Environment**

- Environment: https://gist.github.com/ChloeDawn/fa1068c2ed3e37e3493a96db85cb70cc

**Comment by Technici4n** [comment]
Is this really a bad thing? It already takes multiple seconds to mine them without a pickaxe.

**Comment by ChloeDawn** [comment]
It conflicts with the behaviour of vanilla blocks. Even stone requires a pickaxe to be mined.

**Comment by shartte** [comment]
It's not terribly high priority, to be honest. Why does this specific thing bother you?

**Comment by ChloeDawn** [comment]
I never indicated a priority. It is just a bug, and therefore I reported it. I'm unsure why a fuss is being made.

**Comment by shartte** [comment]
No fuss. Just managing expectations, and trying to figure out if there's good reason to make it higher priority.
