### ISSUE TITLE
8.3.0-alpha.3 not able to run

### ISSUE THREAD

**Issue by fattredd** [AppliedEnergistics/Applied-Energistics-2#5139]
**Describe the bug**

8.3.0-alpha.3 isn't able to start on server or client

**To Reproduce**

Build the v8.3.0-alpha.3 and copy build/libs/appliedenergistics2-0.0.0.jar it into a new server.

**Expected behavior**

Server starts an runs.

**Additional context**

https://gist.github.com/fattredd/6cd1c72beddd501457c7e87eb6f0dcba

**Environment**

https://gist.github.com/fattredd/84b6201d1d6e06ce3173cdce6ee6ddce

- Environment: 

Server is Linux 4.15.0-140-generic #144-Ubuntu SMP Fri Mar 19 14:12:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Also windows 10 client

**Comment by Technici4n** [comment]
You should run `gradlew runData` before building or you won't get the tag, drops, etc... files. Please lmk if that doesn't solve this.

**Comment by fattredd** [comment]
This does indeed fix the issue. Could we add this step to the README? Running the suggested ```gradlew runData build``` alone doesn't seem do everything needed.

**Comment by Technici4n** [comment]
`gradlew runData build` already does it...
