### ISSUE TITLE
Network repeatedly restart when game restart in MC 1.16.5

### ISSUE THREAD

**Issue by sagesse-cn** [AppliedEnergistics/Applied-Energistics-2#5140]
**Describe the bug**

I have such a network, when I restart minecraft it will cause the whole network to down
<img width="843" alt="image" src="https://user-images.githubusercontent.com/6903353/114292625-57a9a280-9ac2-11eb-8477-abf4c397049b.png">
it will restarts the network repeatedly.
<img width="683" alt="image" src="https://user-images.githubusercontent.com/6903353/114292636-6ee89000-9ac2-11eb-9f32-a005f3741109.png">
<img width="666" alt="image" src="https://user-images.githubusercontent.com/6903353/114292640-760f9e00-9ac2-11eb-90b9-0cc199e7e572.png">
until I take it drop and reconnect.

**To Reproduce**

construct an identical structure as shown in the image above.

**Expected behavior**

the network will not restart and all components will work.

**Environment**

1.16.5-forge-36.1.4
appliedenergistics2-8.3.0-alpha.3

**Comment by Technici4n** [comment]
Can't reproduce in 1.17, I assume this was probably fixed at some point.
