### ISSUE TITLE
(QUESTION) Does the 8.3.0-alpha.3 fix the chunk errors of 8.3.0-alpha.2?

### ISSUE THREAD

**Issue by Darrk101** [AppliedEnergistics/Applied-Energistics-2#5146]
In issue [#5069](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/5069) there was an issue with chunk saving. **I was wondering if this issue [#5069](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/5069) got fixed in alpha.3?** I noticed a few commits, but I was wondering if they made it into alpha.3.

**Comment by yueh** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/releases/tag/v8.3.0-alpha.3
