### ISSUE TITLE
[1.16.5] Crash on existing world

### ISSUE THREAD

**Issue by Alkasym** [AppliedEnergistics/Applied-Energistics-2#5147]
Hi, 

With the lastest version of AE2, the server crash with an NullPointerException on an existing world. 
No problem on new world.

Edit : Same issue on solo with the same world.

Pastbin : https://pastebin.com/wA5K0h4d

------------------------------------------------------------------------------------------------------------------------------------

Forge : 36.1.4
AE2 : 8.3.0-alpha.3

**Comment by shartte** [comment]
>  sonar.fluxnetworks.common.storage.FluxChunkManager

this looks like some performance mod...
can you please try without that?

**Comment by Mari023** [comment]
> > sonar.fluxnetworks.common.storage.FluxChunkManager
> 
> this looks like some performance mod...

I have no clue how it works internally, but flux networks is a wireless energy distribution mod
It's a bit like the old tesseracts from TE but only for Energy

**Comment by shartte** [comment]
AE2 expects to be notified of world-loads before any chunks are being loaded. It looks like FluxChunkManager loading chunks _during_ the world load event, leading to this problem.

Can you try (make a backup of your world please) without that mod to see if my hypothesis is correct?

**Comment by Alkasym** [comment]
Without flux networks we have no crash problem.
The issue is on flux networks?

**Comment by shartte** [comment]
We can potentially fix this on our end.

**Comment by Alkasym** [comment]
So I don't need to open a ticket on flux netwoks git?

**Comment by shartte** [comment]
Nah, we'll discuss this internally first.

**Comment by Alkasym** [comment]
Ok thanks you :)

**Comment by yueh** [comment]
Yes, this is up to flux networks to fix. They start loading chunks before even minecraft does it. Leading to who know what issues.
We might just be the first one crashing on it and not cause some hidden data corruption. (Just guessing here)

We could technically shuffle our event handling around a bit with a higher priority, but that only works until flux networks decides to do that it as well to counter another issue. Which at some point makes it impossible to fix on our side.

**Comment by shartte** [comment]
Sorry, but no. I don't know of any restriction w.r.t. to chunk-loading in response to world load event, or can you point me to any?

**Comment by yueh** [comment]
Feel free to follow the code, but in short minecraft does a bunch of other things like setting the spawn point, handling entity spawns for structures, setting allow mob spawns and what not. No idea what would happen, if it loads a chunk without any allowed spawns and it suddenly starts deleting entites.

This is also where forge hooks their own chunk loader into. So I guess it's not without some reason for them to load chunks. And Forge certainly won't document that you cannot load chunks during the world load event. Or anything else.

**Comment by shartte** [comment]
Additionally reported to https://github.com/SonarSonic/Flux-Networks/issues/436
