### ISSUE TITLE
ME Auto crafting bug?

### ISSUE THREAD

**Issue by LordBene** [AppliedEnergistics/Applied-Energistics-2#5154]
I'm playing on Direwolf20 1.12.2 on a server. I wanted to set up an ME autocrafting with Inscriber. The auto recipe is displayed in the terminal and every other player except me can auto craft it. But when I click on the item (Craft), the window (Terminal) closes immediately. I regretted reinstalling the client and am not using a security terminal. It's not the server either. Could you please give me additional help?

**Comment by shartte** [comment]
Sorry, we currently do not support any version older than Minecraft 1.15 anymore.

**Comment by LordBene** [comment]
but the bug could also exist in 1.16 if you are not yet aware of it
