### ISSUE TITLE
P2P ports disappearing when clicked on with Mekanism cables and pipes

### ISSUE THREAD

**Issue by CloWnicide** [AppliedEnergistics/Applied-Energistics-2#5155]
**Describe the bug**
When trying to setup FE, fluid, or other p2p channels and using Mekanism pipes and cables, the p2p will completely disappear. Item does not drop on the ground, the cables do not replace the p2p, they just straight up disappear

**To Reproduce**
Set p2p, try to change type with Mekanism cable/pipe, p2p disappears

**Expected behavior**
P2p does not disappear

**Additional context**
![Screenshot (31)](https://user-images.githubusercontent.com/27911500/114829382-dbdc7e00-9d7f-11eb-80ea-e426c084a430.png)
![Screenshot (32)](https://user-images.githubusercontent.com/27911500/114829387-dda64180-9d7f-11eb-8628-87e804d79897.png)

- Environment: Java: 11.0.10.0, Forge: 36.1.2 AE2: 8.3.0-alpha.3

**Comment by yueh** [comment]
Cannot reproduce, works fine for me with mekanism cables and energy cubes.

**Comment by CloWnicide** [comment]
Restarted the game, and tried it again and it did it a few times then allowed me to change it to a FE channel. Mechanical fluid pipes change it to FE channels too, is that normal?

**Comment by shartte** [comment]
@CloWnicide It's a bit wonky. I think any item that implements forge energy transfer will make it do that.

**Comment by CloWnicide** [comment]
Interesting, on the topic of p2p channels, how do you get gases to transfer through the fluid channels? I cannot get fluid p2p or fluid storage panels to work with gases.

**Comment by shartte** [comment]
You cannot, because Mekanism gases do not use Forge's fluid system.

**Comment by Technici4n** [comment]
You can use Rotary Condensentrators on both ends to convert back and forth.

**Comment by CloWnicide** [comment]
> You can use Rotary Condensentrators on both ends to convert back and forth.

Oh god, thank you. For fixing the issue and causing another one XD
