### ISSUE TITLE
Are molecular assemblers broken, or did their usage change/are they disabled in alpha?

### ISSUE THREAD

**Issue by Kinsypoo** [AppliedEnergistics/Applied-Energistics-2#5164]
**Describe the bug**
i am using appliedenergistics2-8.3.0-alpha.3 and the molecular assemblers simply dont accept items at all. Interfaces dont interact with them, and i cant put a pattern inside manually either. Are they disabled because it is an alpha build, or do they not work the same way as they used to and im just doing it wrong?

**To Reproduce**

use appliedenergistics2-8.3.0-alpha.3 and try to use them.

**Expected behavior**

for them to work normally

**Additional context**

**Environment**

Mod list:

- Environment:

**Comment by Kinsypoo** [comment]
Waddles (by Girafi)
    The Farlanders (by ModdingLegacy)
    Just Enough Resources (JER) (by way2muchnoise)
    Serene Seasons (by TheAdubbz)
    Simple Voice Chat (by henkelmax)
    Create (by simibubi)
    Hwyla (by TehNut)
    Macaw's Roofs (by sketch_macaw)
    WorldEdit (by sk89q)
    Cosmetic Armor Reworked (by LainMI)
    Collective (by Serilum)
    MCDoom Mod (by AzureDoomC)
    Structure Gel API (by ModdingLegacy)
    Better Diving (by meldexun)
    ZeroCore 2 (by ZeroNoRyouki)
    Botania (by Vazkii)
    JEI Enchantment Info (by Phylogeny)
    Pam's HarvestCraft 2 - Trees (by pamharvestcraft)
    Stoneholm, Underground Villages (Forge) (by TheGrimsey)
    Tetra (by mickelus)
    Theurgy (by kli_kli)
    FTB GUI Library (by FTB)
    Snow! Real Magic! ⛄ (by Snownee_)
    Mekanism Additions (by bradyaidanc)
    Mekanism (by bradyaidanc)
    Occultism (by kli_kli)
    Mekanism Generators (by bradyaidanc)
    Outvoted (by HowBoutNo)
    Kiwi 🥝 (by Snownee_)
    CoFH Core (by TeamCoFH)
    Ender Storage 1.8.+ (by covers1624)
    TerraForged (by won_ton_)
    Arcane Fundamentals (by Ac310102)
    Druidcraft (by VulpTheHorseDog)
    Abnormals Core (by TeamAbnormals)
    Waystones (by BlayTheNinth)
    Realistic Torches (by Chaosyr)
    Tetra Pak (by noobulus__)
    Placebo (by Shadows_of_Fire)
    MythicBotany (by noeppinoeppi)
    Armor Underwear Mod [FORGE] (by The_Wabbit0101)
    Better Advancements (by way2muchnoise)
    Flux Networks (by sonar_sonic)
    Bookshelf (by DarkhaxDev)
    CC: Tweaked (by SquidDev)
    AIOT Botania (by MelanX)
    Infernal Expansion (by InfernalStudios)
    Curios Quark Oddities Backpack (by 6LeoMC)
    Eidolon (by elucent_)
    Extreme Reactors (by ZeroNoRyouki)
    UnionLib (by Stereowalker)
    Travel Bag (by Corail_31)
    Savage & Ravage (by TeamAbnormals)
    Waila Harvestability (by squeek502)
    AI Improvements (by QueenOfMissiles)
    Spartan Weaponry (by ObliviousSpartan)
    Client Tweaks (by BlayTheNinth)
    YUNG's API (Forge) (by YUNGNICKYOUNG)
    Ensorcellation (by TeamCoFH)
    Autumnity (by TeamAbnormals)
    Curious Elytra (Forge) (by TheIllusiveC4)
    JEI Integration (by SnowShock35)
    Spice of Life: Carrot Edition (by lordcazsius)
    Better Weather - Seasons, Blizzards, and more! (by Corgi_Taco)
    Relics (by SSKirillSS)
    Curios API (Forge) (by TheIllusiveC4)
    Wither Skeleton Tweaks (by Shadows_of_Fire)
    Immersive Engineering (by BluSunrize)
    Wawla - What Are We Looking At (by DarkhaxDev)
    Dungeon Crawl (by XIROC1337)
    Crafting Tweaks (by BlayTheNinth)
    Snow Under Trees (by bl4ckscor3)
    Pandoras Creatures (by andrew0030)
    YUNG's Better Caves (Forge) (by YUNGNICKYOUNG)
    Chat Embeds (by Yunus1903)
    Farmer's Delight (by vectorwing)
    Quark (by Vazkii)
    AutoRegLib (by Vazkii)
    Quark Oddities (by Vazkii)
    Survive (by Stereowalker)
    Macaw's Furniture (by sketch_macaw)
    Engineer's Decor (by wilechaote)
    Nature's Aura (by Ellpeck)
    Architectury API (Forge) (by shedaniel)
    Undergarden/Tetra Patch (by syrikalis)
    Ore Grow EX (by mrflamerax)
    Extended Lights (by Polyvalord)
    Corail Tombstone (by Corail_31)
    Controlling (by Jaredlll08)
    Mana and Artifice (by AWildCanadianEh)
    Advanced Chimneys (by EnderLanky)
    Blood Magic (by WayofTime)
    ForgeEndertech (by EnderLanky)
    YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)
    Desolation (Forge) (by y4z0n)
    Immersive Petroleum (by Flaxbeard)
    SwingThroughGrass (by exidex)
    Lootr (by Noobanidus)
    Tetranomicon (by syrikalis)
    LibX (by noeppinoeppi)
    FerriteCore (Forge) (by malte0811)
    Whisperwoods (by itsmeowdev)
    FastWorkbench (by Shadows_of_Fire)
    NoDamI (No Damage Immunity) (by ProfHug0)
    AppleSkin (by squeek502)
    Flat Bedrock (by Sunekaer)
    Fast Leaf Decay (by olafskiii)
    Just Enough Items (JEI) (by mezz)
    Pollution of the Realms (by EnderLanky)
    Iron Chests (by ProgWML6)
    Numina (by machinemuse)
    Modular Powersuits (by machinemuse)
    Cloth Config API (Forge) (by shedaniel)
    Mutant Beasts (by Chumbanotz)
    Macaw's Windows (by sketch_macaw)
    Caelus API (Forge) (by TheIllusiveC4)
    Naturally Charged Creepers (by Serilum)
    Towers Of The Wild (by idrae_)
    ReAuth (by TechnicianLP)
    Patchouli (by Vazkii)
    Iron Jetpacks (by BlakeBr0)
    RandomPatches (Forge) (by TheRandomLabs)
    Aquaculture 2 (by Shadowclaimer)
    FastFurnace (by Shadows_of_Fire)
    Neon Craft Mod (by Polyvalord)
    Artifacts (by ochotonida)
    Applied Energistics 2 (by AlgorithmX2)
    Save My Stronghold! (Forge) (by YUNGNICKYOUNG)
    Macaw's Doors (by sketch_macaw)
    mGui (by mickelus)
    Pam's HarvestCraft 2 - Crops (by pamharvestcraft)
    Macaw's Trapdoors (by sketch_macaw)
    Guns, Rockets and Atomic Explosions (by songxia23)
    Dark Utilities (by DarkhaxDev)
    ObserverLib (by HellFirePvP)
    Pam's HarvestCraft 2 - Food Core (by pamharvestcraft)
    Abnormals Delight (by TeamAbnormals)
    Runelic (by DarkhaxDev)
    Spartan Shields (by ObliviousSpartan)
    Decorative Blocks (by stohun)
    Consecration (by TheIllusiveC4)
    Clumps (by Jaredlll08)
    Curio of Undying (Forge) (by TheIllusiveC4)
    GeckoLib (by ThanosGecko)
    Magma Monsters (by Kashdeya)
    Curious Shulker Boxes (Forge) (by TheIllusiveC4)
    Storage for ComputerCraft (by uecasm)
    Cucumber Library (by BlakeBr0)
    Bed Benefits (by DarkhaxDev)
    Carrots Library [FORGE] (by The_Wabbit0101)
    CodeChicken Lib 1.8.+ (by covers1624)
    JourneyMap (by techbrew)
    Macaw's Fences and Walls (by sketch_macaw)
    The Undergarden (by Quek04)
    Neat (by Vazkii)
    Astral Sorcery (by HellFirePvP)
    Mystical World (by EpicSquid315)
    BetterEnd (Forge) (by Beethoven92)
    Spiders 2.0 (by TheCyberBrick)
    Better Animals Plus (by cybercat5555)
    Friendly Fire (by DarkhaxDev)

It doesnt allow me to put the html mod list in there apparently so here is plain text

**Comment by mindforger** [comment]
>It doesnt allow me to put the html mod list in there apparently so here is plain text

For future reports, you can create a forced crashlog while ingame and pressing and holding F3+C until it crashes, put the craslog on pastebin or similar and link it here, too long blocks of text are hard to read in the issue box

**Comment by Kinsypoo** [comment]
Ok do you want one of this?

**Comment by mindforger** [comment]
sure, gives more info about your specific setup :) 

also is this singleplayer or dedicated multiplayer?
i did not test it yet myself but maybe it is disabled by the pack author ?! (implying you did not create the pack yourself)

**Comment by shartte** [comment]
Do you even have the "highlight" when hovering over the slots of the molecular assembler?
There's no known issue with them that I am aware of.

**Comment by Kinsypoo** [comment]
I made the pack myself so it isnt disabled, and its on a server me and my friends are playing on which i setup. I didnt change any of the AE2 configs. 
[crash-2021-04-19_03.12.45-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/6333973/crash-2021-04-19_03.12.45-client.txt)
https://pastebin.com/tfRhFxex <- paste of crash report.

I have the highlight when i hover over the slots i just dont seem able to place anything inside the assembler and neither can the interface. The interface acts as if it is not next to a valid inventory, and then dumps the items into a chest or other inventory once it is provided. It isn't an issue with the interface, or the patterns as they work in other respects as normal just the assemblers dont seem to want to do anything. The assemblers also light up and are powered by the network properly so its not an issue with that.

I also tried other methods of getting an item into the assembler like putting an encoded pattern into a hopper pointing at it just to see, and that didnt do anything either altho im not sure if it even would normally.

If you'd like to test it in the exact pack i can upload a curseforge profile of it for you.

**Comment by yueh** [comment]
Also the obvious are you using crafting patterns and not processing ones? As the assemblers only support the first option.

**Comment by mindforger** [comment]
>dont seem able to place anything inside the assembler and neither can the interface. The interface acts as if it is not next to a valid inventory, and then dumps the items into a chest or other inventory once it is provided

yeah that strongly encourages @yueh 's guess :D

**Comment by Kinsypoo** [comment]
omg yes the one ive been using to test it is a processing pattern im so stupid lmao sorry for wasting your time
