### ISSUE TITLE
Crafting plan blank

### ISSUE THREAD

**Issue by Jaders2** [AppliedEnergistics/Applied-Energistics-2#5168]
helo I'm playing atm6 with the latest update of ae2, however when using autocraft the crafting plank is appearing in white, even with everything working (creative cell), and if I click start the recipe will be made but it doesn't show what it is being done or the missing items

![image](https://user-images.githubusercontent.com/67982891/115447761-401f9780-a1ef-11eb-8f69-f65051ca776c.png)

**Comment by shartte** [comment]
Please provide more information as described in the issue template (the initial value of the text box when you create an issue).

Can you please also enable AE2 debug logging in your config and provide a debug log-file?

**Comment by Jaders2** [comment]
**Describe the bug**
so I'm playing modpack all the mods 6, and recently it had an update where the new version of ae2 (8.3.0-beta1) was added, and when asking to make an autocraft it appears empty, but make the recipe if you have the items in the system, but I can't see the process, nor do I have the items or if something is missing

**To Reproduce**

just ask the system to crafting something automatically

**Expected behavior**

at least I expected to see the items requested in the craft, whether I have it or not, and the process being done or if there was any impediment

**Additional context**



and where i can find the log from debug????

ps: sorry for the english, but it is not my mother language

**Comment by Jaders2** [comment]
sorry i read some logs that i find and remove a mod better weather and the problem was fixed

**Comment by mindforger** [comment]
@Jaders2 FYI the crashlog is unsually stored inside the minecraft folder and you can create a forced crash and log by holding F3 + C while ingame ... this log contains all the vital informations on mods, minecraft and forge versions and couple details on your system

i will close this issue for you, but you could do it on your own when you think it is resolved :)
