### ISSUE TITLE
Have `IPart#getDrops()` handle dropping the part itself

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#5169]
Currently the cable bus is responsible for creating the itemstack to drop the part itself. This should be completely moved to the `IPart` and not just have it handle dropping upgrades or similar. E.g. if a addon desires to drop unstackable items by keeping the config stored within the itemstack, it should be possible.

Also evaluate how `Block#getDrops(LootContext.Builder)` might be useful. E.g. roll using a wrench into it. Which would allow us to make further changes down the road without needing a potential API. Like adding a secondary wrench mode to keep the config in case some players would prefer it. As far as this is possible as some combinations can then easily cause issues later like suddenly having a P2P tunnel with multiple outputs.

**Comment by shartte** [comment]
Will not implement this for now.
