### ISSUE TITLE
Drop `appeng.api.parts.PartItemStack`

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#5171]
This is currently overlapping with a couple other methods or will be with other planned changes

* [ ]  `BREAK` and `WRENCH` should be rolled into `IPart#getDrops()`. See #5169 for further details
* [ ] `PICK` should be provided by something like `IPart#getPickBlock` similar to `Block#getPickBlock()`
* [ ] `WORLD` and `NETWORK` are more of an internal case and are probably obsolete with the changes in #5170.

**Comment by shartte** [comment]
What return type would you consider for getPickBlock? Parts usually don't have blocks.

**Comment by mindforger** [comment]
by vanilla behaviour i would say return the itemstack of the part that is under the cursor (at least this is what i see ender io doing)

**Comment by yueh** [comment]
Just like currently the item. I guess we can argue about the the name and potentially call it `IPart#getPickPart()` or something. Vanilla also returns an itemstack and calls it `pickBlock` (or at least mcp. no idea how the official mapping is)
