### ISSUE TITLE
Can't see any stored items in craftin Terminal

### ISSUE THREAD

**Issue by Mars1984Upilami** [AppliedEnergistics/Applied-Energistics-2#5173]
AE2 Fabric Alpha 3 (had same issue with Alpha 2)
MC 1.16.5
Fabric 0.11.3

I have a simple setup. 3 Energy Cells, 1 ME Drive with a single 16K Storage Cell, 1 Crafting Terminal (see provided Screenshots)

Power is not an issue since my energy cells are full or after restart getting there.

![2021-04-23_20 27 57](https://user-images.githubusercontent.com/83086601/115914614-76207e00-a472-11eb-802e-bb1740d4a963.png)
![2021-04-23_20 30 47](https://user-images.githubusercontent.com/83086601/115914888-d1527080-a472-11eb-93c4-91e3735d52a1.png)

**Comment by shartte** [comment]
Please provide the crashlog as requested in the issue template (using the F3+C shortcut if i remember correctly)

**Comment by Mars1984Upilami** [comment]
Its not crashing. 

When I hit F3+C and paste it:  /execute in minecraft:overworld run tp @s -22.97 61.00 85.60 -326.06 17.25

**Comment by Mari023** [comment]
you have to hold F3 + C for like 10 seconds

**Comment by Mars1984Upilami** [comment]
This crashed my MC.

[latest.log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/6367598/latest.log)

**Comment by Mars1984Upilami** [comment]
Do u need further info?

**Comment by shartte** [comment]
Hm, I didn't even know Optifine would work on Fabric.
Either way, we can't really support Optifine, sorry.
But even besides Optifine, you have so many errors in your logfile that I couldn't really help without Optifine either.

**Comment by Mars1984Upilami** [comment]
Optifine workes with Optifabric. Could u point me in the direction of some errors because im to blind to see them in the log.
