### ISSUE TITLE
Certus Quartz Crystals not keeping charge

### ISSUE THREAD

**Issue by Songar87** [AppliedEnergistics/Applied-Energistics-2#5175]
**Describe the bug**
In all current versions of AE2 (Alpha, Beta and Release) charged certus quartz crystals immediately lose their charge when removed from a charger by hand or when dropped from an inventory onto the floor

**To Reproduce**
Remove charged certus quartz crystals from charger by hand or drop charged crystals from an inventory ( dispenser, player inventory, etc.) on the ground

**Expected behavior**
The charged certus quartz crystals should keep their charge when removed from the charger by hand or when thrown in water for crafting fluix crystals

**Environment**

- Environment: 
- Windows 10 64-bit
- Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
-  NVIDIA GeForce RTX 2060

**Comment by shartte** [comment]
Please provide more information as described in the issue template (the initial value of the text box when you create an issue).

**Comment by Songar87** [comment]
What other info do you need? (I've never made a github post before)
