### ISSUE TITLE
Decouple API from registration

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#5178]
Decouple the API from the registration to allow an easier bootstrapping.

Internally it could be using `RegistryObject` or `@ObjectHolder` with a collection of `ResourceLocation` as constants. Or something similar like a custom lazy getter and tie to with a safeguard to the registration lifecycle

**Comment by yueh** [comment]
Should be done

**Comment by Technici4n** [comment]
Yeah, @shartte please reopen if you don't agree. :smile:
