### ISSUE TITLE
Head unremovable from Terminal

### ISSUE THREAD

**Issue by kiozix** [AppliedEnergistics/Applied-Energistics-2#5180]
**Describe the bug**
Version 8.3.0-alpha.3

hello I noticed that once the entity head is put in the terminal can no longer remove them

**To Reproduce**
put an entity head in the terminal me and remove it

**Expected behavior**
entity head remove from terminal

**Additional context**
https://www.youtube.com/watch?v=9iafV0wX5dM

**Environment**
windows 10 pro N
i7 10700k
64Gb ram
nvme 1to 
rtx 2060 super

C:\Users\PC01>java -version
java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)

https://ptero.co/osegaxisin.rb

**Comment by yueh** [comment]
This is somewhat of an ongoing problem with Forge making it impossible to correctly identify an item between server and client.
There might be some changes in 8.4 (or later), which might be another attempt at solving it. But that is certainly not guaranteed.
So I would consider that as something which will never be fixed until Forge provides a reliable way for it, at least without turning it into a massive performance or bandwidth problem.
