### ISSUE TITLE
Block Entity Spatial storage rendering issues (fabric)

### ISSUE THREAD

**Issue by profjb58** [AppliedEnergistics/Applied-Energistics-2#5181]
**Describe the bug**
When cloaking a region using spatial storage and then uncloaking it on a dedicated server rendered features visible to the player from a block entity disappear. Maybe this is a client sync issue?

**To Reproduce**
Place a tile entity that dynamically renders something within the game, for e.g. in this case we use the Eternal Pedestal from Better End then cloak and uncloak it within spatial storage (video of this below) It also happens with other mods though including Through The Looking Glass with there own similar version of this pedestal

**Expected behavior**
In the case of the Eternal pedestal the item displayed should not dissapear

**Additional context**
Video showcasing how to reproduce using a betterend pedestal
https://user-images.githubusercontent.com/46009144/116002688-cfafb680-a5f2-11eb-8e10-b60ef752ec4b.mp4

**Environment**
On a dedicated server running this pack: https://github.com/The-Tiny-Taters/TTTM-AOF which is basically AOF3 2.7.1 running the latest version of AE2 but with some additional mods ontop

**Comment by Technici4n** [comment]
Spatial IO is a low priority. As such, non-critical issues related to it are unlikely to be fixed until we are done with the rest of the backlog.
