### ISSUE TITLE
Spatial cell "No server is currently running" logspam

### ISSUE THREAD

**Issue by profjb58** [AppliedEnergistics/Applied-Energistics-2#5182]
**Describe the bug**
holding your mouse over an AE spatial cell spams the log with 
```
[20:02:25] [main/WARN]: Failed to retrieve spatial storage dimension: java.lang.IllegalStateException: No server is currently running.
```

**Expected behavior**
Shouldn't spam the console since it is running on a dedicated server and it works

**Environment**
On a dedicated server running this pack: https://github.com/The-Tiny-Taters/TTTM-AOF which is basically AOF3 2.7.1 running the latest version of AE2 but with some additional mods on-top

**Comment by Technici4n** [comment]
I suspect without having tested this that it also happens on Forge - removing the `fabric` tag.

**Comment by Technici4n** [comment]
It's the classic vanilla bug where dimensions get deleted.
