### ISSUE TITLE
Auto crafting issue with both "crafting" and "uncrafting" patterns.

### ISSUE THREAD

**Issue by Shroototem** [AppliedEnergistics/Applied-Energistics-2#5186]
When you put patterns in to "craft" and "uncraft" iron nuggets all the way up to iron blocks, the auto crafting gets confused. 
![image](https://user-images.githubusercontent.com/47718633/116604790-9467fd00-a8fc-11eb-9764-c6c73c2a6f47.png)
![image](https://user-images.githubusercontent.com/47718633/116604841-a8abfa00-a8fc-11eb-815f-902a98b31acf.png)

With this I would expect it to automatically craft ingots, than ingots into blocks.

Enigmatica 2: Expet Skyblock
Java 1.8.0_281 64bit

**Comment by mindforger** [comment]
you should complete your bug report according to the template

to make a comparision, you just said something like "there is a broken handle on my blue car, pleace fix it"

**Comment by Tahakk** [comment]
at the same time you have same recipe for one block, meaning it chose the latest recipe it seems, use compacting drawers for these and you'll be fine

**Comment by yueh** [comment]
If you give AE2 multiple paths to craft something, at some point it will pick a random one. There is simply no best way as this differs for every player. Plus it will not use recursive tasks like crafting an iron block with iron ingots made from another iron block. So in this case it might simply stop at requesting iron ingots as it picked the pattern to produce them from an iron block and stop there.

On the other hand, your modpack decided to pick mods which change AE2 internally and will produce broken patterns, which might never work. So I guess asking them is the best option here.

And further, 1.12 is no longer supported.

**Comment by Shroototem** [comment]
So basically I'm not getting any help.
That's ok I guess, I'll figure something out.
