### ISSUE TITLE
Evaluate replacing some iron with copper in recipes

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#5187]
Iron ingots are overall in very high demand across many mods, which is usually not resolved by a corresponding increase of spawn rates or other mechanics to reduce it.

With 1.17 introducing copper as new metal, we should consider using it for some recipes when fitting thematically.

## Potential candidates for changes

* [ ] Cells use `Iron - Copper - Iron` instead of `Iron - Iron - Iron` for the lower row
* [ ] Blank patterns use `Iron - Copper - Iron` instead of `Iron - Iron - Iron` for the lower row
* [ ] Advanced /Basic Card replace 1 or 2 iron ingots with copper

**Comment by Technici4n** [comment]
Done in the 1.17 early game rework.
