### ISSUE TITLE
ME System Automation

### ISSUE THREAD

**Issue by Logics2996** [AppliedEnergistics/Applied-Energistics-2#5188]
![1](https://user-images.githubusercontent.com/83439271/116752387-67e7da00-a9fd-11eb-9d7b-59bd5121bf91.png)
![2](https://user-images.githubusercontent.com/83439271/116752388-69190700-a9fd-11eb-8051-c62416af92b2.png)
![3](https://user-images.githubusercontent.com/83439271/116752391-69b19d80-a9fd-11eb-9b44-78c740429979.png)

**Describe the bug**

so i am trying to import smelted items from my smelting factory (mod=Mekanism) to my Me System, have it configured to output items on the side i need it to and i have an export bus going from the smelting factory to my ME system i have also tried the Me interface but thats not working either, i dont know if its me or if the mods are being weird with each other

**Comment by Mari023** [comment]
uhm...
the export bus is to export things out of the me system.
what you are looking for is an import bus.
