### ISSUE TITLE
Me System, Cant Access

### ISSUE THREAD

**Issue by Logics2996** [AppliedEnergistics/Applied-Energistics-2#5191]
i am trying to do a wireless me system, i have the security terminal set up and the wireless is working for me. i have put in the biometric card to give everyone else access but it is not working
![2](https://user-images.githubusercontent.com/83439271/116793320-0b98bf00-aabe-11eb-9ca7-c2ea359d11c6.png)
![1](https://user-images.githubusercontent.com/83439271/116793321-0c315580-aabe-11eb-9f6a-c9f56e8a22d3.png)

**Comment by PoolloverNathan** [comment]
AFAIK cards are only effective when placed in the actual storage part of the GUI, they don't work when still in the editor. Also, are you sure the biometric card isn't bound to anyone?
