### ISSUE TITLE
Suggested : Dimension ID in Config as option 

### ISSUE THREAD

**Issue by McKitten** [AppliedEnergistics/Applied-Energistics-2#5192]
I tend to be of the belief that stuff in the overworld is to easy to access and that there should be an option to change where the items spawn. Personally I believe nether seems appropriate for these items but other places like a mining dimension that would take someone else's fancy. They may even want to split the meteors & certus quartz locations up.

I am just going off the info in this https://ae1.ae-mod.info/Config-Options/ so you may have already added it but if so, please update.

**Comment by mindforger** [comment]
do you suggest a dimension ID for the spatial dimensio or a config on ore spawn?
the referenced site is not AE2 but the predecessor ... that one is SERIOUSLY outdated

**Comment by shartte** [comment]
World generation cannot be constrained using dimension IDs anymore. It's all based on biomes now.
