### ISSUE TITLE
Ae2 stuff getting added to Ae2

### ISSUE THREAD

**Issue by Sleeclow** [AppliedEnergistics/Applied-Energistics-2#5193]
Ae2 stuff added many items, that mod pack authors felt were needed in the base game but Ae2 stuff isn't being updated 

**Describe the feature**
 Will Ae2 ever see things like the wireless crafting terminal, the network tool and the growth chamber?

**Reasons why it should be considered**
 these things are huge QOL of additions to the mod and seem like an obvious progression, and the fact that they are STILL not in Ae2 has lead to it being dropped from some mod packs, like Enigmatica. Ae2 is easily my favorite mod and so seeing it getting dropped really sucks.

**Additional Context**

**Comment by yueh** [comment]
No, there are currently no plans to integrate inferior solutions or ones that are opposed to the general game design.

**Comment by Sleeclow** [comment]
> No, there are currently no plans to integrate inferior solutions or ones that are opposed to the general game design.

Well damn clearly yall feel some kinda way about new things in AE2. Sucks to hear that I'll have to learn RS over AE2 to do some mod packs now, AE2 was my favorite mod but oh well, wish it got those improvements.

**Comment by Technici4n** [comment]
> I'd hardly call an item that lets you see your network in world and identify issues inferior

The network visualization tool is a cool concept, but certainly not what comes to my mind with AE2 stuff, so it might be cool to have. Advanced inscriber and crystal growth chamber come to mind, and those are certainly a no-go because they only exist to bypass regular AE2 gameplay (which is fine if you like it, but shouldn't be in the base mod).

> wireless crafting terminal that always seemed like a natural progression
It _seems_ like a natural progression, but the progression is actually to setup autocrafting for everything. There is a reason it's not in base RS either. See #401.

**Comment by Sleeclow** [comment]
> It _seems_ like a natural progression, but the progression is actually to setup autocrafting for everything.

Expect AE2 to me is a mod meant for mod packs, its entirely unreasonable to assume that people will setup to auto craft the thousands of different recipes that can be made in the 3x3 grid.

**Comment by Mari023** [comment]
> > It _seems_ like a natural progression, but the progression is actually to setup autocrafting for everything.
> 
> Expect AE2 to me is a mod meant for mod packs, its entirely unreasonable to assume that people will setup to auto craft the thousands of different recipes that can be made in the 3x3 grid. especially considering you may only never need something once.

You can always just carry a crafting table with you... or store one in the me...

**Comment by Sleeclow** [comment]
> You can always just carry a crafting table with you... or store one in the me...
If its that easy then why do the devs have such a strong, almost fuck off stance, about adding a wireless crafting table?
