### ISSUE TITLE
Update certus worldgen to match 1.18 concepts

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#5197]
With 1.17 moving to spawn rates for ores to depend on the y level, we should follow this approach for certus quartz.

## Pick a y level for maximum spawn rates

Currently minecraft sets this to `y48` for copper and `y16` for iron. Usually these maximums are moved in 16 block increments.
With #5187 in mind, it would make sense to pick something like `y32`.
However this might depend on how much iron vs copper we will overall use. So moving it a bit towards the iron level might be reasonable, or making the spawn wider.

## Negative y levels

Completely new, minecraft itself now places redstone, gold and diamonds here. As well as a couple other like iron again below `y-32`.
We could also add certus here, maybe with an increasing chance to obtain charged certus.

**Also needs a new deepslate texture**

**Comment by shartte** [comment]
Changed to 30 clusters per chunk, cluster size increased to 7.
Range set to triangle -34 to 36
