### ISSUE TITLE
Sky Stone Brick Stairs

### ISSUE THREAD

**Issue by AlgorithmX2** [AppliedEnergistics/Applied-Energistics-2#52]
I really like the Skystone blocks (Normal, Brick, Small Brick).
I think it would be nice to have them as stairs, especially the Sky Stone Brick.

Originally Posted by Alex

This issue was migrated; For original details see http://ae-mod.info/Tracker/0508/

**Comment by Yulife** [comment]
Maybe a bit of an necropost but slabs would be brilliant as well. I am quite in need for them in a current map that I am making and FMP and Carpenter's blocks wouldn't be a good solution :)
Thanks in advance

**Comment by thatsIch** [comment]
Feel free to open up a new issue for that.

**Comment by Yulife** [comment]
Thank you :wink:
