### ISSUE TITLE
Potential for Infinite Items from ME Pattern Terminal

### ISSUE THREAD

**Issue by OrionCummings** [AppliedEnergistics/Applied-Energistics-2#5201]
**Describe the issue**
I'll preface this by saying that I have been seeing 'Gray Dye' in the output of every crafting interface, regardless of the source mod. When I place an invalid crafting recipe in any crafting interface, I see the vanilla gray dye. Usually, I cannot actually craft the given item into Gray Dye. It is only a visual bug. Whatever I don't really mind. But I started to use the ME Pattern Terminal today and while configuring a recipe, I could actually craft ANY invalid crafting recipe into one gray dye. This one was not a visual bug. I relogged and it was still in my inventory. I could craft with it as well. This prevents me from creating recipes that do not actually have traditional recipes, like a printed logic circuit in this example.

While duplicating infinite gray dye isn't really a huge issue, I'm concerned with the capability for the ME Pattern Terminal to create items from effectively nothing.

**Environment**
I am playing on All Of Fabric 2.7.2 multiplayer.
I tested this in a creative singleplayer and I could not reproduce the error. I explained the issue to the moderators of the server (the developers of AOF), and they had heard of the visual aspect but not the ability to craft gray dye.

- Environment: 
https://pastebin.com/8GZSbggQ

**Comment by Technici4n** [comment]
This is a BYG recipe bug, nothing directly related to AE2. The AOF team will work with the authors of BYG to get it resolved.
