### ISSUE TITLE
Opening REI settings in Crafting Terminal crashes the game

### ISSUE THREAD

**Issue by Silky777** [AppliedEnergistics/Applied-Energistics-2#5202]
Exactly as above. Trying to open REI settings while in an ME Crafting Terminal (haven't tested with other terminals) crashes the game.

**Describe the bug**
See above

**To Reproduce**
See above

**Expected behavior**
I expected to be able to open the REI settings to enable cheat mode in order to test out the ME system.

**Additional context**
Crashlog: https://pastebin.com/TFua43XC

**Environment**
Debug crashlog: https://pastebin.com/Vyx0S2F4

- Environment: 
_OS:_ Windows 10 Home
_CPU:_ Ryzen 7 3800X
_GPU:_ Geforce RTX 2070 Super
_Java:_ Java 1.8.0
_Memory dedicated to Minecraft:_ 8192MB (8GB)

**Comment by Silky777** [comment]
I'm using the fabric version, specifically this file. 

`appliedenergistics2-fabric-8.2.0-alpha.3.jar`

**Comment by Mari023** [comment]
I cannot reproduce with just ae2 and REI and a few other mods I thought might be involved ([debug log](https://gist.github.com/Mari023/403ec9b6b167b77a88011c87b72a6e05))
can you maybe break down which specific mods are involved?

**Comment by Technici4n** [comment]
This looks like a Not Enough Crashes crash, not an AE2 crash. Please reopen if you manage to reproduce without Not Enough Crashes installed.
