### ISSUE TITLE
Smart cables take a while to update channel lines

### ISSUE THREAD

**Issue by Wlnfr** [AppliedEnergistics/Applied-Energistics-2#5211]
**Describe the bug**
Smart cables' lines that update more slowly the more cables are connected. ME Chest connected to controller/energy source with 4 smart cables updates the lines immediately upon connection. ME Chest connected to the end of a cable line of around 504(shown in a screenshot) takes around 45 seconds for smart cables to get the line on them. I imagine it would take even longer to update the lines on smart cables for even larger AE networks.

**To Reproduce**
1. Create a world.
2. Place a controller/energy source.
3. Make a long cable line(I tested with around a 100 cables).
4. Connect any block that uses a channel to the last cable.
5. Wait X seconds for the line to appear.
Note: Everything that uses a channel will work as intended if there are enough channels in the network, only the visual representation of used channels on smart cables gets updated with a delay.

**Expected behavior**
For smart cable lines to appear within a few seconds after connecting them.

**Additional context**
![2021-05-11_16 18 25](https://user-images.githubusercontent.com/8050905/117832956-9b88f680-b27e-11eb-9191-26bcbaae5b8b.png)
![2021-05-11_16 18 32](https://user-images.githubusercontent.com/8050905/117832966-9d52ba00-b27e-11eb-888b-c88c18d7f49d.png)
![2021-05-11_16 18 38](https://user-images.githubusercontent.com/8050905/117834052-86609780-b27f-11eb-9d47-ff60c973317b.png)
![2021-05-11_16 50 01](https://user-images.githubusercontent.com/8050905/117832973-9fb51400-b27e-11eb-90c0-c00ec27f2570.png)

**Environment**

- Environment: 
Minecraft 1.16.5
Forge: 36.1.6
AE2: 8.3.1
The One Probe: 3.0.7 (used for convenience, not necessary to reproduce the bug)
Forced crashlog: https://pastebin.com/mVUyQpLT

**Comment by mindforger** [comment]
Just to be sure, you are powering it with an creative energy cell? If not, do you have enough energycells attached? Booting and detecting the grid can take quite a peak of power and input is limited by capacity

**Comment by Wlnfr** [comment]
Yes, I am powering it with creative energy cell, you can see it on second screenshot in the middle of bottom layer of controllers.

**Comment by Wlnfr** [comment]
I have done some more testing, the problem seems to be with the controller. since smart cables update their channel information almost immediately after connecting ME chest to an energy cell with a ~500 long cable, while controller blacks out right after connecting the same cable to it and starts up after a few seconds. The energy levels don't drop drastically after connection, the controller just blacks out fully, like, the energy consumption drops to 0. Hope this helps.

**Comment by yueh** [comment]
This is by design, repathing the network takes some time and the algorithm is optimized to explore multiple parallel paths. Which usually is the most common configuration. This allows us to implement it in an easy way and spread it across multiple tocks without potentially risking an exponential cost in a single tick or otherwise strange bugs when assigning channels due to race conditions.

On the opposite this means a single long cable is the worst case in terms of how long it takes to fully repath the network.
However I don't see any change happen in the short term. As to some degree it is also a design decision to have larger networks boot slower overall.
