### ISSUE TITLE
1.16.5 fabric version not working

### ISSUE THREAD

**Issue by bigchungus54** [AppliedEnergistics/Applied-Energistics-2#5213]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional context**

**Environment**

- Environment:

**Comment by bigchungus54** [comment]
wouldn't let me edit preview so yeah it's blank

**Comment by Technici4n** [comment]
Please fill the template next time, this doesn't help.

**Comment by mindforger** [comment]
just by chance, everything that starts with "<!--" is just readable in the editor and will be hidden, your text should go below those lines not inside :)
