### ISSUE TITLE
Spatial ancor crashes on place 

### ISSUE THREAD

**Issue by Mari023** [AppliedEnergistics/Applied-Energistics-2#5215]
**Describe the bug**
When placing a spatial anchor crashes the latest fabric Version
after reloading the world it still crashes.

**To Reproduce**
place a spatial anchor. it doesn't matter whether it is placed on a network or not

**Expected behavior**
The spatial anchor either not to crash or not to be present if it isn't finished yet

**Additional context**
The spatial anchor is also missing a texture
judging from the missing recipe it is probably not intended to be used anyways

**Environment**
[crashlog](https://gist.github.com/Mari023/afbab2507ad9cc91984bef9256cc68a9)

**Comment by shartte** [comment]
It's not intended to be used. Fabric does not have the chunkloading infrastructure that Forge has.

**Comment by Mari023** [comment]
It would be great to make that block unobtainable tho.
so that unknowing users don't corrupt their world and then cry about it

**Comment by Technici4n** [comment]
Fixed by registering the `StatisticsCache`. Will release another alpha when Github Actions comes back online.
