### ISSUE TITLE
Item Sort Order Resets After MC Restart

### ISSUE THREAD

**Issue by Peca21** [AppliedEnergistics/Applied-Energistics-2#5218]
Item Sort Order Resets After MC Restart

**Describe the bug**

Every time I enter MC today after restarting it my sort order on my wireless terminal and on my pattern terminal was set to ascending but I always set it to Descending. Also Crafting terminal doesn't seem to be affected by this (Maybe because I change it in the wireless terminal)

**To Reproduce**
1. Set sort order to descending
2. Exit MC
3. Launch MC
4. Sort order will be ascending

**Expected behavior**
Sort order should stay on descending

**Additional context**
![Wireless Terminal Screenshot](https://user-images.githubusercontent.com/13818400/118409789-759f8f80-b68c-11eb-9968-0dde33493c13.png)

**Environment**

- Environment: 
Jre 1.8.0_291 x64
Forge 1.16.5-36.1.18
appliedenergistics2-8.4.0-alpha.1
Forced Crash: https://pastebin.com/2ndzri0x

**Comment by shartte** [comment]
Cannot reproduce this in the latest version (Fabric). If Forge resets our config on load, I don't think we can do much about it.

**Comment by Peca21** [comment]
IDK it works now in a new modpack
