### ISSUE TITLE
OpenComputers more crafting information

### ISSUE THREAD

**Issue by milkev** [AppliedEnergistics/Applied-Energistics-2#5220]
**Describe the feature**

report more information to opencomputers getCpus()
things such as craftingStack or craftingStackSize would be helpful.
Edit:  variables i think would be useful
craftingStack - the item being crafted
craftingStackSize - the amount of items to be crafted
craftingIngredients - matrix of ingredients being used, in addition to the same information as above, for each of them.
craftingETA - estimated time for autocraft to finish

**Reasons why it should be considered**

for use in opencomputers, the current functionality only allows for 'on/off' signals that tell if the cpu is in use or not. it would be far better if we had more context available such as the item being crafted. then instead of just displaying if a cpu is in use, we could display the item and amount as well. As is, theres not much reason to really use opencomputers for this, as opening a wireless terminal gives so much more information, that simply knowing if a cpu is in use or not, is not useful. if one could use opencomputers to display more crafting information on an in world screen (no need to go through terminal menus, which can be laggy, especially on servers or low end devices) that can be viewed at a glance. it would also mean you could see all recipes being processed at the same time, rather than viewing them one at a time in the terminal.

**Additional Context**

seeing as opencomputers hasnt updated since 1.12.2, this would only effect the 1.12.2 version, however...
i dont know the capabilities of cc:tweaked in 1.16.5, but it would be a useful feature there as well.

**Comment by shartte** [comment]
We do not have any specific opencomputers or cctweaked interfaces in 1.16, and will not add improvements to 1.12 anymore. Sorry.

**Comment by milkev** [comment]
understandable. perhaps in the future if an interface is created with cctweaked (or similar mod) these ideas could be implemented!
