### ISSUE TITLE
The `nether_quartz_wrench` cannot be removed with Shift + Right click `dense_energy_cell`

### ISSUE THREAD

**Issue by ChihoiTse** [AppliedEnergistics/Applied-Energistics-2#5221]
**Describe the feature**

- `nether_quartz_wrench` or `certus_quartz_wrench` should be right-click used to rotate the direction, then using 'Shift + right-click' can be used to dismantle most AE2 items.
- The nether_quartz_wrench cannot be disassembled with Shift + Right click dense_energy_cell
- Other things like `fluix_glass_cable` can be removed, but the various components and the vibration_chamber can't

**Reasons why it should be considered**

- I think this feature has been removed in the latest version, probably due to a different version

**Additional Context**

Fig. 1, cannot be disassembled
![image](https://user-images.githubusercontent.com/49972747/118439046-d7590b80-b717-11eb-9881-e9d60b6406a5.png)
Fig. 2, successful disassembly
![image](https://user-images.githubusercontent.com/49972747/118439073-e17b0a00-b717-11eb-9d8a-fab1966e420a.png)

**Comment by ChihoiTse** [comment]
Can someone help me？

**Comment by mindforger** [comment]
did you consider reading the template before deleting it?
i can not reproduce ... (though i am currently using 1.12 minecraft which had a couple different AE2 versions over the time)

**Comment by ChihoiTse** [comment]
> did you consider reading the template before deleting it?
> i can not reproduce ... (though i am currently using 1.12 minecraft which had a couple different AE2 versions over the time)

Do you mean that in 1.16, `wrench` will not be able to remove `dense_energy_cell`?

**Comment by mindforger** [comment]
not really but please read the template again and edit your first post to fill out the required informations to get you some help ... I always compare such reports with calling an car mechanic "Hello, my car makes noises, can you fix? .. What car do you have? .. A blue one!" ... not really helpful towards the mechanic ain't it?

**Comment by ChihoiTse** [comment]
> not really but please read the template again and edit your first post to fill out the required informations to get you some help ... I always compare such reports with calling an car mechanic "Hello, my car makes noises, can you fix? .. What car do you have? .. A blue one!" ... not really helpful towards the mechanic ain't it?

I'm so sorry, I don't know the rules.I have already corrected.

**Comment by Technici4n** [comment]
I noticed this bug myself a few days ago on Forge 1.16: I think the correct behavior can be ported from Fabric, I will likely have a look soon.

**Comment by ChihoiTse** [comment]
> I think the correct behavior can be ported from Fabric, I will likely have a look soon.

I am so excited to hear that and hope to fix this BUG as soon as possible.Incidentally, it's not just 'dense_energy_cell' that can't be disassembled, but many other blocks as well, such as' vibration_chamber 'and' quartz_growth_accelerator '

**Comment by masakitenchi** [comment]
Since those blocks can still be removed properly by network tools, I consider them as a "feature" rather than a bug. But I will leave this problem to devs to discuss

**Comment by ChihoiTse** [comment]
OK. Please let me know if anything comes out of the discussion.I will tell Minecrafters in China to solve their confusion.

**Comment by ChihoiTse** [comment]
There is a newly discovered problem in 1.16 that if an energized 'dense_energy_cell' is placed into a working 'vibration_chamber', there is a chance that the energy of 'dense_energy_cell' will be lost.This probability becomes very high when 'dense_energy_cell' is not 100% energetic.

**Comment by ChihoiTse** [comment]
There is a newly discovered issue, in 1.16, if you put a charged but not 100% 'dense_energy_cell' on any block, there is a hight chance that the energy of 'dense_energy_cell' will be lost.
I have submitted a new `ISSUES` to illustrate this issue.#5226
