### ISSUE TITLE
Decouple `IExternalPowerSink` from `IAEPowerStorage`

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#5231]
`IExternalPowerSink` is mostly used as wrapper to ensure the power units are converted correctly, but there is no need to have it extend `IAEPowerStorage` as it will only allow inputting.

The internal implementation can then still wrap an `IAEPowerStorage`. E.g. to charge inscribers or chargers directly with FE.

Also it should be considered to move it into the internal package as this does really offer anything to an API consumer.

**Comment by Technici4n** [comment]
Not something very important for us at the moment.
