### ISSUE TITLE
After server restart, I lose access to my network and need to break/replace the security terminal to fix. 

### ISSUE THREAD

**Issue by TheInfamousAlk** [AppliedEnergistics/Applied-Energistics-2#5234]
--Info--
I'm using the modpack "all the mods 6" 1.6.3c, with ae2 version 8.3.1. This is on a dedicated server that I host with default config from the modpack. My network consists of 1 crafting terminal, a wireless access point with 64 range boosters, an ME storage bus connected to a storage drawers controller, 6 energy acceptors, one energy cell, 2 empty ME drives, a charger, an ME controller, and a security terminal.

--Description--
When the server does its nightly restart, when logging back in, I no longer have access to my own ME network. I can see the items inside and my wireless terminal is still linked so I can use that to see items, but I cannot take items out and can't access the security terminal GUI with the message "you do not have access". I can break and replace the security terminal and re-link the wireless pad and it all works fine until next restart. There are no crash logs. If a specific log file would be useful, I can upload it. 

- Environment: 
I host on akliz.net. I use 8000mb of RAM. I do not know the backend environment they host this server on.

**Comment by CommYutzy** [comment]
I had the same issue after updating to ATM6 1.6.4 from 1.6.3, my server has not restarted since the update so I cannot confirm if it happens every restart. Self hosted on an Ubuntu VM with 4 cores and 8GB RAM (6GB set to the ATM launcher)

**Comment by mindforger** [comment]
please use the issue template to learn how to provide the required informations to give you help
you might not know but only telling the modpack name and version is as precise as telling a mechanic "i got a blue light car"

**Comment by CommYutzy** [comment]
Scrolled through the entire 2k+ line `latest.log` and Ctrl-F'd `debug.log`, I cannot find any such simulated crash. This was on a clean start and I cleared out the logs directory prior to starting. Added AE2 version to my original comment though

**Comment by mindforger** [comment]
search the debug log for "Mod signature data" there shall be an indented list of mods with and without signatures and their versions

i am stumped as it seems they removed that crash report, it was quite usefull since you can not forcibly crash the server like you do when crashing the client with F3 + C

but the main issue here is the size of your modpack, it is nearly impossible to debug such a pack even with all the mod versions and the system specs, if you have the time and would try t reproduce the issue with a minimal setup this would be great ... or do a so called binary search:

make a fresh world
reproduce the issue with minimal setup
then begin removing half the mods (keep em somewhere stored, each removed part in a different folder)
-> if the issue persists, remove another half and so on
-> if the issue goes away, take away all other mods beside AE2 and maybe some other required ones and put back the "bad" half you just dropped before and continue the search until you have the smallest possible setup to reproduce

**Comment by LucyValeheart** [comment]
Still having this issue on 8.4.4. 

Writing in with a workaround I found, though- On multiplayer, at least, if I have someone else who has security access put a biometric card in for myself, it will continue to allow me access through restarts. I'm unable to put it in myself, though, so this method does require a second person.

**Comment by TheInfamousAlk** [comment]
Yeah same I also found this out today. I'm curious, what is your minecraft username? Maybe there's something in common that we can pin this on. Mine is The_Infamous_Alk. I had a theory that the underscores might have been causing problems for some reason. Because if it works for someone else and breaks for me, even in different worlds, the only common variable is "my account/username". It never happens to anyone else on my server.

**Comment by LucyValeheart** [comment]
Unfortunately it's LucyValeheart, no underscores. But I do think there are others having this issue in the server I play - I'll ask around and see. I'm on the kinetic network modpack mythic satus,their official server.

**Comment by shartte** [comment]
If you are not playing offline, the owner information is stored using your game profile ID, which is independent of your username.

**Comment by TheInfamousAlk** [comment]
Any ideas why it has happened to me in 2 different modpacks, several different worlds and servers in those 2 modpacks, and nobody else? It has to be something related to my ID or account or something. This world I didn't even make the whole network or any pieces, it was mostly made by another user, then at some point I broke and replaced the security terminal and that made the issue start happening again. It has to be something tied to my ID/character. I have even tried completely emptying my inventory between reboots and it still happens. 

If you do ask around, ask what people are doing, what mods they are really progressing in, what they carry on their person/bauble slots, stuff like that. Maybe it's an item/status/data tied to my character from another mod causing it.

**Comment by CommYutzy** [comment]
FWIW the issue plagued every single person on my server back when I commented. Nothing weird about my username, all letters within A-Za-z. I haven't played in several months though and ultimately determined it not worth my time to track down.

**Comment by Krutontar** [comment]
It won't be a name thing.  It's something global that doesn't even trigger at world start.

**Comment by shartte** [comment]
It would be great to have a reproducible test case for this, but since it "just happens" and is then broken afterwards, this is actually quite hard :-|

**Comment by TheInfamousAlk** [comment]
If it makes a difference, it is reproduceable on my server. Every single reboot it does the same thing. I could give logs if that helps. I own it, I could reboot any number of times to test if someone has any idea what to test.

**Comment by shartte** [comment]
Hm, can you go into your AE2 config file and set:
`securityAuditLog` to `true`
`debugLog` to `true`
?

Reboot once, try to access your network to log the reason, and then attach your server log here?

**Comment by TheInfamousAlk** [comment]
Yes. I will report back later, I'm out for the next couple days.

**Comment by TheInfamousAlk** [comment]
I will record one instance of accessing the network where my friend placed the security terminal, then I will break and replace it, reboot, and record me attempting and failing to access the network before breaking and replacing the security terminal and successfully accessing it. I'll do that on the 26th.

**Comment by TheInfamousAlk** [comment]
So I ended up breaking and replacing the terminal before the testing, so I don't have data from when someone else owned the network and it was "working fine". In this test I logged in, attempted to access my crafting terminal, attempted to access the security terminal, both unsuccessful. Then I broke and replaced the security terminal, put all the bio cards back in, and successfully accessed the security terminal, then successfully accessed the crafting terminal. Then shut down the server. Please let me know if there is any more specific testing I can do to help.

Things to note: my controller and about half of my network is in the blood magic demon realm dimension, but this happens regardless of dimension. I believe my network is the only AE2 network on the server, most other people use refined storage.

https://gist.github.com/TheInfamousAlk/5f2919f0157930d4474713f07b718bb0#file-latest-log


I noticed after I logged in, there were no AE2 log entries, but several before. I do not know if this is supposed to happen or not, since it didn't log any of my actions, but here it is anyway.

**Comment by shartte** [comment]
Thanks for grabbing this log, it has at least given me an idea where I might look...

Also, 

```
:26:17] [Server thread/INFO]: Security audit 1 failed at [dimension=net.minecraft.world.DimensionType@1c1db0a6, x=-999, y=139, z=-1] belonging to player [id=0]
[17:26:17] [Server thread/INFO]: Security audit 2 failed at [dimension=net.minecraft.world.DimensionType@1c1db0a6, x=-939, y=150, z=8] belonging to player [id=1]
[17:26:17] [Server thread/WARN]: Failed to establish a ME P2P Tunnel between the tunnels at [x=-999, y=139, z=-1] and [x=-939, y=150, z=8]
```

The locations it mentions, are those actually placed by different players?

**Comment by TheInfamousAlk** [comment]
No, those are part of a p2p cable with 3 sources and 3 destinations that I built just today so I could bring a bunch of channels to another part of the base without tons of cables. I've never actually touched anything p2p until today. No idea why those have different player ids.

**Comment by TheInfamousAlk** [comment]
Also if you need more specific information on the setup of my network I can show you pictures/video, or you could even join the server, it's up 24/7. Though not sure if that is super relevant since it's happened over a few different unrelated network setups

**Comment by TheInfamousAlk** [comment]
By the way, the "failed p2p tunnel" in the log is still linked and working just fine.

**Comment by mzuletal** [comment]
Given the unknown cause of this could there be a way to disable the permissions from the security terminal, cause in my case i only use it to have the wireless terminals linked

**Comment by TheInfamousAlk** [comment]
If this is possible I would also like to do this. I don't actually need the security terminal for anything other than wireless. Or maybe if there is a way to use wireless without having to have a security terminal set up?

**Comment by Technici4n** [comment]
#6356
