### ISSUE TITLE
Aggregate blacklists/whitelists from storage buses or cells at the network level

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#5242]
This would aggregate all black and white lists at the network level as well as provide them for every upstream networks.

For one would provide a small performance improvement, as we can now potentially reject insertions/extractions at a network level and not have to potentially iterate through 10 chained subnets to find nothing. This might however not apply to most setups, which will not have a default route allowing everything.

A prerequisite for it would be to have all storage locations inside a single network use a whitelist or blacklist. If there is a single unconfigured storage bus, it would act as default route and accept everything. This could make use of the particilar state of this storage bus or cell and apply the network wide partition once these storages are full. However this is probably outside this scope. If even possible to determine for external storage.

Further this would allow a couple more useful features in combination with other ideas like #5240.

In combination with a `Distribution Card` inserted into a storage bus, it could disable announcing its partition list and also be ignored as default route. This would allow a storage bus attached to a condenser and a low priority to inherit all partition lists from any other cell or storage bus and act as a network wide trashcan without running into a problem that it is full of cobble and everything else is suddenly voided. Further it would avoid micromanaging each and every cell with a void upgrade, just to run into incorrect priorities, as well as not add redundant functionalities in terms of condenser and void cells.

**Comment by Technici4n** [comment]
Unfortunately this would require quite an infrastructure to dynamically update the white/blacklists as items are inserted in and extracted from storage cells. I don't see us ever implementing this.
