### ISSUE TITLE
How to Retrogen Chunks?

### ISSUE THREAD

**Issue by HappyCuppy** [AppliedEnergistics/Applied-Energistics-2#5245]
I have an existing world on v.1.16 and most of the area that I do my playing with has already been generated. I'm also using Oh The Biomes You'll Go and Quark, if that matters for generation.
How can I retrogen blocks? I'd like to still be able to play in the areas of my world that I explored.

_Note: I'm using the latest version of the mod_

**Environment**
Environment: Forge 1.16-forge-36.0.46 on Windows 64-bit

**Comment by Technici4n** [comment]
You need to generate new chunks, maybe there exists a "retrogen" mod for forge (that will regenerate old chunks and add missing ores), but I doubt meteors will generate if that happens. Your best option is to generate new chunks (the nether can help get there fast).

**Comment by HappyCuppy** [comment]
> You need to generate new chunks. Maybe there exists a "retrogen" mod for forge (that will regenerate old chunks and add missing ores), but I doubt meteors will generate if that happens. Your best option is to generate new chunks (the nether can help get there fast).

Thanks for the useful information :)

How would the Nether help, exactly? I'd go there, and then what?

**Comment by Technici4n** [comment]
Well, moving 100 blocks in the nether is equivalent to moving 800 blocks in the overworld... it's only necessary if you have explored A LOT. :P

**Comment by HappyCuppy** [comment]
> Well, moving 100 blocks in the nether is equivalent to moving 800 blocks in the overworld... it's only necessary if you have explored A LOT. :P

Oh, so you mean to use it just as a shortcut to get access to newer chunks in the Overworld.
Yeah, I want to retrogen my base - I have a whole village and surrounded area that I explored around that has already been generated and I don't want to move away from it.

Thanks for the suggestion, though :)

**Comment by Technici4n** [comment]
Closing this as I think it's resolved, otherwise please let me know! :)

**Comment by HappyCuppy** [comment]
> Closing this as I think it's resolved, otherwise please let me know! :)

...well, it does answer my question, but it doesn't give me a solution. I'll edit this one to describe that I'm looking for a solution to this (which is why I asked to begin with).

**Comment by Technici4n** [comment]
Well that's not really something that has to do with AE2 itself then... The best solution is probably going far away for mining and coming back with your stuff when you're done. Or if you have a portal mod installed you can use that...

**Comment by HappyCuppy** [comment]
> Well that's not really something that has to do with AE2 itself then... The best solution is probably going far away for mining and coming back with your stuff when you're done. Or if you have a portal mod installed you can use that...

Yeah, it is a possible solution, but it's not optimal. Especially considered just how much I've explored around already (went on a few treasure seeking expeditions). :\

And about the portal - I'm trying to play a more evolutionary way - starting from low tech and going into high tech so that'd technically be "cheating" and would just not be consistent with the gameplay style I want.

**Comment by HappyCuppy** [comment]
> Well that's not really something that has to do with AE2 itself then... The best solution is probably going far away for mining and coming back with your stuff when you're done. Or if you have a portal mod installed you can use that...

Yeah, it is a possible solution, but it's not optimal. Especially considered just how much I've explored around already (went on a few treasure seeking expeditions). :\

And about the portal - I'm trying to play a more evolutionary way - starting from low tech and going into high tech so that'd technically be "cheating" and would just not be consistent with the gameplay style I want.

Could you please open the issue again?

**Comment by Technici4n** [comment]
I don't think it's in scope for AE2, but sure.

**Comment by yueh** [comment]
Not really in the scope of AE2. It always has the risk of being a destructive action. Not as severe with certus quartz compared to meteors, however both a necessary for the normal progression and we certainly will never retrogren meteors at the chance of destroying a player's base.

So exploring for new chunks will always be required to some degree, makeing retrogen not that useful overall.
