### ISSUE TITLE
P2P (items) eats up bulks

### ISSUE THREAD

**Issue by Tsukero** [AppliedEnergistics/Applied-Energistics-2#5249]
Item P2P eats up items, when having items go through Mekanism logistical transporters into item P2P it eats up almost everything, having 64 items go though i will end up with only 4 items going through and the rest no where to be found. But if i put manually items in Molecular assembler the items go through another P2P (item) without any issues 

(Having 16 items go through P2P only to and up crafting only 4 planks from 1 wood, rest of the 15 wood has vanished) 

![image](https://user-images.githubusercontent.com/84744976/119408479-11ad4480-bce6-11eb-8ede-47d4907c93be.png)
![image](https://user-images.githubusercontent.com/84744976/119408551-34d7f400-bce6-11eb-95bf-2429e44318fd.png)

**Comment by Technici4n** [comment]
Mind sending a full picture of the minimal setup to reproduce this?

**Comment by Tsukero** [comment]
![image](https://user-images.githubusercontent.com/84744976/119417815-f991f100-bcf6-11eb-8681-7b86126d8643.png)
i put 64 logs in the chest so i should get 64 * 4 but instead the P2P kinda "eats" the 60 wood and i end up with 4 spruce logs crafted into 16 planks... but if i put 64 logs directly into molecular assembler it goes through P2P to storage with correct numbers

**Comment by Tsukero** [comment]
oh and behind the mekanism bin is a storage bus if that is important but even after doing without storage buss the same issue occures

**Comment by Tsukero** [comment]
Theres few more issues on P2P and molecular assemblers (not sure if i should issue another bug or not), i havent seen anyone post these in the "issues". 

In picture above P2P that imports outside items to the system doesn't care if it can or cannot intake items, leading to items that shouldn't be able to be accepted in P2P (literally anyhting besides the wood because only wood can go to molecular assembler for crafting planks) it ends up accepting items anyway. Items are no where to be found (only storage thats connected to ME system is the bin). 

Second is if assign second output from same P2P input to molecular assembler and then molecular assembler doesn't have a pattern in it, it will end up eating any of the items for example my wood that should be crafted in the planks would go to second molecular assembler which has no pattern (for me I do this so i can assign patterns later on and already have everything set up) and the wood would not be crafted but instead get just lost in  ME cables somewhere or mollecular assembler without pattern would eat it (not sure whats causing this problem actually) 


Third issue is assigning normal P2P to for example redstone, energy, item, or others before i connect P2P to cable, P2P just suddnely vanishes. If i connect cable to it before i try to assign it to different type it works fine.  

In picture assigning P2P on the side with any of the items it vanishes, assigning top P2P works alright.
![image](https://user-images.githubusercontent.com/84744976/119530180-11af5200-bd83-11eb-94dc-03b0449a5eb6.png)

**Comment by Technici4n** [comment]
The first two issues are I think the same thing that is fixed by #5251. (Thanks for the detailed report tbw, really help me find the bug quickly!)

The third one is different. Mind explaining (in a new issue) the exact steps to reproduce? (What to click exactly, in which order)

**Comment by Tsukero** [comment]
First i put P2P where i need it (on lamp for redstone or on the chest to export items or on different pipe doesn't matter) But since the main P2P tunnel is assigned for channels only you need to press it with an item (right click) , redstone for redstone, cable for FE, hopper for item and so on. But since i don't want to put cables first because its easier to move in a larger setups I've done, I first assign P2P to Item with a hopper aaaaand its gone.  but if i put ME cable behind it then it can be assigned to item P2P. 


Same picture of above ive just put both of the P2P's on item P2P and one is gone (i promise i didnt break it with left click) 
![image](https://user-images.githubusercontent.com/84744976/119532868-90a58a00-bd85-11eb-81cc-4e1ee7b89243.png)

**Comment by Technici4n** [comment]
Many thanks for this information, I have updated #5251 to fix this as well! :)

**Comment by Tsukero** [comment]
I found one more issue (not sure if its disgussed already or not). I have 2 outputs so i will refer to OUTPUT1 (first link assigned) and OUTPUT2 (second link assigned) and this issue happens when theres 1 input and multiple outputs like above too hoverever this issue is a little bit different from what I mentioned, and I just realized it thinking i can work around the issues above but apparently not.  Aslo in screenshot the only thing that matters are from molecular assembler and all to the left everything on the right is irrelavent P2P and bins), also you might have already figured it out.

Okay so, I want multiple outputs and only 1 input so that items get sorted themselves. By putting polished diorite pattern and spruce wood pattern in both molecular assemblers I want to fill the hopper with a stack of diorite and a stack of spruce logs. 

Expectation: By linking input to Output1 and Output2 the log will go in molecular assembler crafting and craft planks, diorite will go to MA and craft polished diorite. 

Issue: Assinging input to Output1 (bottom logs) and Output2 (top diorite) and then by putting a stack of logs into hopper, the P2P will accept the logs and they will be crafted, however putting diorite into hopper the P2P will also accept it but it will not end up in the top MA to craft, P2P just items accepts and items are gone. 

Conclusion: Only first P2P output will accept items from P2P input, wheter you have 50 Outputs from same input or 2 is irrelavent. 

Sidenote having 1 input and 1 output going to MA and when ME cant accept items P2P will still eat items even tho theres no where to put them 

![image](https://user-images.githubusercontent.com/84744976/119656116-9b662a80-be2a-11eb-996e-b1f01bcdad30.png)

**Comment by Technici4n** [comment]
Yes it's all the same problem 😆, we are working on a fix but it takes a little bit of time to make sure we don't miss other issues!

**Comment by Tsukero** [comment]
Ah I'm sorry It's new to me and thought maybe it can help, guess only thing is to wait for it's fix good luck. :D

**Comment by Technici4n** [comment]
Closed by #5251.
