### ISSUE TITLE
The storage cell world is missing

### ISSUE THREAD

**Issue by thetriangl** [AppliedEnergistics/Applied-Energistics-2#5250]
When I send a Redstone input to a spatial storage bus it gives the error that The storage cell world is missing

**Comment by yueh** [comment]
Duplicate of #5136

**Comment by thetriangl** [comment]
This happens on my fabric server not on a singleplayer world

**Comment by Technici4n** [comment]
This is the same issue, please read #5136. We can't do more than what is written there.
