### ISSUE TITLE
Crash with the latest Fabric version

### ISSUE THREAD

**Issue by heyjudek** [AppliedEnergistics/Applied-Energistics-2#5254]
**Describe the bug**
The game keeps loading in an infinite loop
Up until now, I was using the appliedenergistics2-8.2.0-beta.3.jar and it worked fine

Here is the latest log + the crash report
[latest.log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/6549004/latest.log)
[crash-2021-05-26_20.42.05-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/6549007/crash-2021-05-26_20.42.05-server.txt)

**Comment by Technici4n** [comment]
We don't support ae2ao. And please never report issues when you have that mod installed to us as they access unsupported internals.

**Comment by heyjudek** [comment]
Thank you for letting me know. I assume you wouldn't recommend to even install that mod then?

**Comment by Technici4n** [comment]
Up to you, depends if you want support or not. For now I guess you don't have the choice anyway... :-p

**Comment by heyjudek** [comment]
Yeah, I got rid of it, I didn't know it was developed independently, I just assumed it was an addon or something :)
