### ISSUE TITLE
non-ME P2P disappear when cable placed on back 

### ISSUE THREAD

**Issue by SavageCabbage64** [AppliedEnergistics/Applied-Energistics-2#5255]
**Describe the bug**
non-ME P2P disappear when cable placed on back 

**To Reproduce**
Place down any p2p tunnel besides the ME one on the ground with no cable connected. Then click on the back with a glass cable. The p2p tunnel will vanish and there will be no way to get it back.

**Expected behavior**
I expected either the cable to place down on the back of the p2p, or for the p2p to turn into a ME p2p

![image](https://user-images.githubusercontent.com/59934842/119757716-f91a6700-be6a-11eb-831c-ef500a64a1b6.png)
![image](https://user-images.githubusercontent.com/59934842/119757740-08011980-be6b-11eb-8475-addf3d64a034.png)

https://pastebin.com/X3HDhLvu

- Environment: 
Windows 10, 
Intel core i7-8700,
Nvidia 1080 ti,
16 gb RAM

**Comment by Technici4n** [comment]
Will be fixed by #5251, but thanks for reporting anyway!

**Comment by Technici4n** [comment]
Closed by #5251.
