### ISSUE TITLE
Replace `IGridHost` with a capability or provide it as alternative

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#5257]
This will be blocked by #5256.

If there is no option for us to reduce it to the states provided by `Direction`, it will not be possible to really move to a capability based approach. Except for some hacks like only exposing the cap on `null` and then move the actual location into the interface.

Also a prerequisite to implement #4666.

**Comment by shartte** [comment]
Made obsolete by grid refactor
