### ISSUE TITLE
Nothing works. read description.

### ISSUE THREAD

**Issue by Bloxish** [AppliedEnergistics/Applied-Energistics-2#5268]
None of the storage setups work.

Im playing a modded smp with my friends and we finally got around to crafting a basic ME system, which includes a dense energy cell, energy acceptor, ME controller, a disk drive, and a crafting terminal. When we put items into the cell (4k storage cell) we can put items in but we cannot take them out as they are not displayed in the terminal. They are still displayed as being stored in the cell, though.
I downloaded this from curseforge, not another site that could potentially carry malware.
I'm not sure how to reproduce this issue, but I have tried it with version 8.3.1 and 8.3.0 and neither of the versions work. I have a feeling this is a config problem, but im not experienced enough to dive into that.
I've played with AE2 many times in modded servers and worlds and know how most of the machines work.
I've also tried this in a creative singleplayer and the same issue arises when using any other cell type. The server did not crash. 
screenshots:
![Capture](https://user-images.githubusercontent.com/85134738/120241731-05b30c80-c229-11eb-8901-5b505ad3efe0.PNG)
with that same disk (520 vanilla stone btw so it can't be a cancelled item)
![Capture](https://user-images.githubusercontent.com/85134738/120241844-3b57f580-c229-11eb-959d-48245f03cc49.PNG)

**Comment by Technici4n** [comment]
Can you try an alpha 8.4.0 build? (Backup first, of course)

**Comment by Bloxish** [comment]
ok i can try that
i will get back if it works or not

**Comment by Bloxish** [comment]
ok so i tried lauching the modd but it requires forge 36.1.10 but the server and everyone elses client is run on 36.1.0. I know i could update it and its not that I am lazy but i am the most experience modder in our group and trying to reinstall a later version of forge would confuse everyone else to the point of not wanting to play anymore.

**Comment by shartte** [comment]
That means we can't really help you at this point, sorry.
