### ISSUE TITLE
add old cable config

### ISSUE THREAD

**Issue by Goten87** [AppliedEnergistics/Applied-Energistics-2#527]
i hate the new channel system (sorry cant get use to it)
is there a way to have it as a config to return it to the old cable system
so no channels anymore just 1 cable to use all my EA with

hope this is somthing that can come into EA2 sins i realy cant get use to the new system :(

**Comment by asgdfagdsfg** [comment]
This feature is just idiotic and renders the mod completely useless.
Every other mod with pipes and sorting systems is now way cheaper / faster / more compact then this garbage.
Whoever came up with the idiotic idea of limiting the cables should be forbidden from working on any game ever again.
Talking about the "point" of the mod... WHAT is it now?
It's clearly not "user friendly production and crafting".
The mod adds absoloutely NOTHING to the game anymore, and i can't understand why people don't put AE1 on their servers. AE2 ONLY ruined the things, that were awesome (and kind of the WHOLE purpose) in AE1...
Please name a SINGLE thing that you developers have improved?
Yea, nothing. Everything has become stupid and annoying. Really wish you people would just disappear and server owners would go back to the finished AE1.
