### ISSUE TITLE
Server crash caused by patterns from removed items

### ISSUE THREAD

**Issue by jpwanabe** [AppliedEnergistics/Applied-Energistics-2#5270]
After updating the server with some removed mods, the server now crashes

**Describe the bug**
Server crashes due to removed recipe from mod that is no longer in server.

**To Reproduce**
Create patterns from a mod, remove mod from server, start server, crash.

**Expected behavior**
server should not crash and make patterns empty or just delete them

**Additional context**
crashlog 
https://pastebin.com/g50FMQ7S

Believed to be one of these items causing it. Not sure yet and is still being tested.
https://i.imgur.com/ZgE7IU9.png
https://i.imgur.com/FIisIRX.png

**Environment**
Server is running All of Fabric 3
updating from version 2.7.4 to 2.8.1

**Comment by jpwanabe** [comment]
To add more info, I found the culprit mod that caused it, not the item though.
The change from one version to the next is what is causing it.
Modern Industrialization (Modern-Industrialization-0.3.17.jar -> Modern-Industrialization-0.4.0-alpha.06.jar)

**Comment by Technici4n** [comment]
Fixed in 1.17 by #5625.
