### ISSUE TITLE
Network lags when i search someting.

### ISSUE THREAD

**Issue by KodYazanDruid** [AppliedEnergistics/Applied-Energistics-2#5271]
**Describe the bug**
The more item types i have the more lag i suffer.

**To Reproduce**
Create normal network. Dump different items.

**Expected behavior**
To not lag :(.

**Additional context**
There is no crash but i forcecrashed for more info.
https://paste.dimdev.org/esucehofek.mccrash

I tried using only ME Drives still lags.
I tried using large storage crates via storage busses still lags.

**Environment**
- Environment: 
Multiblock Madness Modpack v1.1.1
Applied Energistics 2 :  appliedenergistics2-rv6-stable-7.jar

**Comment by Technici4n** [comment]
Sorry, we don't support MC 1.12 anymore.
