### ISSUE TITLE
Security Terminal

### ISSUE THREAD

**Issue by Snoe0** [AppliedEnergistics/Applied-Energistics-2#5272]
**Describe the feature**
Make it so that if a user doesn't have full permission for a security terminal, they can't mine it.

**Reasons why it should be considered**
The security terminal is supposed to protect your ME system from other players, but players can mine the security terminal and place it back and then they own your entire ME system.

**Additional Context**
I had a setup where if users tried to use my farms and machines, it would take their materials into my ME system, since they didn't have permission to use them, and one person broke the security terminal, took their stuff back, and I got locked out of my ME system.

**Comment by yueh** [comment]
This is simply outside the scope of AE2 and better be handled by a real protection mod. Which can simply spend way more time on better features like admin tools, visualisation, and other features. Most of them would actually be needed to keep server admins happy and eat up our available time for other things.

The security we provide is simply on top of that as protection mods usually will not be able to tell between someone opening a terminal and dismantling all cables. For them both are pretty much the same interaction, yet the first one might be intented for helping other players, while stripping your whole ME network is probably not, and all they could offer is either none of these permissions or everything.
