### ISSUE TITLE
Remove internal Annihilation Plane Block-Blacklist

### ISSUE THREAD

**Issue by shartte** [AppliedEnergistics/Applied-Energistics-2#5279]
All blocks on the internal blacklist already have hardness -1, which is already checked for the annihilation plane anyway.
We'll also still have the tag-based blacklist for modpack authors to blacklist whatever they want.

**Comment by Technici4n** [comment]
Closed by #5276.

**Comment by shartte** [comment]
Also, I was being stupid, the list is actually already in the tag. Just unnecessarily.
