### ISSUE TITLE
Improve memory card interactions

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#5284]
Extracted from #2978, behaviour not set in stone.
The main requirement is to allow players to pick up an existing tunnel without assigning a new frequency. Ideally also from an output side.

## Improve the interaction parts by using the proposal in #1480 (prerequisite)

Currently we are limited to 2 actions per part. Right click and shift + right click. This limits us to each a single read and write action for the card. In terms of the p2p tunnels this includes also reseting the frequency and changing it to an input, when reading the settings. Without it, there would be no way to ever create a new input or even a new tunnel.

With the proposed changes in #1480 we would have at least 4 different actions available. Which could translate something like

| action | effect |
| --- | --- |
| Left Click | Read settings, no change (analog to extract item) |
| Shift + Left Click | Reset and read (new frequency/input/etc) |
| Right Click | Write settings (analog to insert item) |
| Shift + Right Click | Could also insert cards like proposed in #1382 (Or should we ever allow N:N tunnels to set input) |

**Comment by Technici4n** [comment]
We've already reworked memory cards since (with different semantics).
