### ISSUE TITLE
Crash when trying to partition fluid cell in workbench

### ISSUE THREAD

**Issue by matt31084** [AppliedEnergistics/Applied-Energistics-2#5285]
**Describe the bug**
When placing a partially filled fluid cell into the workbench and clicking the Partition icon, the game crashes.  

**To Reproduce**
In AoF 3 new creative world I used the following setup:
1) Blocks from left to right, Workbench, Creative Energy Cell, ME Controller, ME Drive
2) Add a cable on top of ME Controller and attached a Fluid Terminal
3) Add 16K fluid cell to ME Drive
4) Use fluid terminal to insert bucket of lava
5) Take fluid cell from ME drive and insert it into Workbench
6) Click Partition, game crashes
7) Restart game, attempt to open Workbench and game crashes again

**Expected behavior**
I expect to view the fluids stored and to be able to partition the drive

**Additional context**
Crash Log:
https://pastebin.com/RvkVVyKm
It seems this issue has been around for a while as issue #4841 was closed "assumed it was fixed in latest release".  However this doesn't seem to be the case.

**Environment**
Using AoF 3 modpack 2.8.4 but also happens in 2.8.2.  Both versions use the latest fabric release, 8.3.0-alpha.3
Fresh install of AoF 3 modpack from CurseForge (they just released the new version a few hours ago)
- Environment:

**Comment by mindforger** [comment]
based on your crash report you are using non-native fabric but a fork that is used for sodium
and as far as i know sodium is not supported
https://github.com/comp500/Indium
as a reference

**Comment by matt31084** [comment]
Sorry, my modpack folders got mixed up and I was using the sodium/indium version.  However I downloaded the modpack into a fresh folder and verified it was using indigo renderer.  The issue still happens, here is the crash report:

https://pastebin.com/D9psuHua

**Comment by Technici4n** [comment]
Fabric 1.16 is not supported anymore, this is probably fixed in 1.17.
