### ISSUE TITLE
Charged Certus quartz not keeping charge.

### ISSUE THREAD

**Issue by Electro9899** [AppliedEnergistics/Applied-Energistics-2#5286]
<Charged Certus quartz crystals are not remaining Charged when picked up by an inventory>

**Describe the bug**
<When an inventory such as a hopper or player picks up a Charged Certus crystal it will un charge and become regular Certus quartz, this is a problem because you need charged Certus to progress. >

**To Reproduce**
<Obtain charged Certus quartz, and drop it on the ground when the crystal, then pick up the crystal with an inventory.>

**Expected behavior**
A Charged Certus quartz will remain Charged Certus quartz when picked up.

**Environment**
< A forced crash report>https://pastebin.com/MDgV7L7B

A video of the bug in action-https://youtu.be/8NE7t61Msdw

**Comment by shartte** [comment]
Please provide more information as described in the issue template (the initial value of the text box when you create an issue).

**Comment by Electro9899** [comment]
I've updated the issue to provide a short video of the bug in action

**Comment by mindforger** [comment]
This „lazierAE2“ seems to be an very beta mod, can you recreate the issue without it?

**Comment by yueh** [comment]
Unified Resources will merge them into a single type.
