### ISSUE TITLE
ME Identity Anihilation Plane problems

### ISSUE THREAD

**Issue by abel1502** [AppliedEnergistics/Applied-Energistics-2#5287]
**Describe the issue**
In #3919, the discussion ended with a solution being proposed, yet in the latest stable release, the Identity Anihilation plate is still enabled by default and still functions exactly like its regular couterpart. Due to this, currently it is just a more expensive variant of the regular Anihilation Plane. I expect this to be fixed either by disabling the plane not to confuse players, or by reverting it to the duping variant, but disabling in the config by default with a warning, as suggested in the original issue.

**Environment**
- Minecraft 1.12.2
- Forge 14.23.5.2855
- AE2 rv6-stable-7

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.16 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
