### ISSUE TITLE
Pattern not loading when opening world

### ISSUE THREAD

**Issue by shylux** [AppliedEnergistics/Applied-Energistics-2#5288]
I am using the 1.7.10 Version of this mod (in the Divine Journey Modpack). When i load the world then sometimes only a few of my pattern on the assembler load (only on assemblers). The missing pattern are together with correctly loaded patterns in the same interface.
It is not consistent. Sometimes all pattern are loaded sometimes none, sometimes a few. It looks like some kind of race condition.

I have a save file from 2, 3 years ago when i finished the same pack and the bug does not happen there. And this save file has hundreds of pattern. So its probably something with my save

I tried rebuilding the network and also tried redoing the pattern, but nothing helps.

I also have the strange bug that my iron gear pattern will sometimes turn into a shuriken pattern (the same pattern but the iron ingot in the middle is missing). This might be related.

Picking up a pattern and placing it down will fix all the pattern in the same interface.

**To Reproduce**
Not sure if possible, since it only happened in one world.

**Expected behavior**
All pattern should be loaded and display produce the correct item.

**Additional context**
This is my minimal setup. It also happens when i remove the controller.
![2021-06-13_09 45 44](https://user-images.githubusercontent.com/1375745/121799754-1f435380-cc2e-11eb-9c5c-302c45605358.png)

**Environment**
Using Divine Journey (1.7.10) Modpack.  
AE2 Version rv3-beta-6 (out and used since 2015).

**Comment by Technici4n** [comment]
Sorry, we only support 1.16 at the moment.
