### ISSUE TITLE
Encoded Patterns not rendering recipe preview (1.12)

### ISSUE THREAD

**Issue by DoomSquirter** [AppliedEnergistics/Applied-Energistics-2#5295]
**Describe the bug**

patterns in interfaces show the pattern item itself, not the item it crafts.
it's identical to #5258 but this is for 1.12 version is is much older than the one talked about in that issue.

**To Reproduce**

make a pattern and put it into any interface

**Expected behavior**

I expected it to show the item it crafts
I have played other 1.12 packs with identical version of ae and not had this issue.  In addition, I don't see a config option for this, so I am at a loss as to why this specific pack is doing this.

I am creating this issue because I commented on #5258 but then someone's response was to hide my comment with no explanation.  I am assuming it was to mean to go and create a new issue, so here I am.

**Additional context**

there is no crash report

**Environment**

- Environment: 

here is the F3+C crashlog:
https://pastebin.com/XKKLjZvu

forge: 14.23.5.2854
appliedenergistics2-rv6-stable-7
ExtraCells-1.12.2-2.6.5

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.16 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.

**Comment by DoomSquirter** [comment]
so I can't even ask a question?  I don't expect code changes or anything, but wouldn't you say this is really really strange behavior?  

All I'm asking for is some clue or hint on where to look to try to get a remedy on this.  that's all.

**Comment by Tahakk** [comment]
well there is something wrong wit the combination of your mods, since normally it works just fine. It's up to you to find which one

**Comment by krakel** [comment]
For your information:
I was doing some test with modpack Stacia and found the mods findme and kubejs prevent the correct rendering of encoded patterns (also with the version 8.4.0). :(

**Comment by shartte** [comment]
Hmmm. KubeJS in theory should just be a framework for other modifications of recipes and such.
I saw the same weird issue with encoded patterns (in inventory) in a modpack that also had KubeJS installed, but it rendered the preview 90% of the time, for the remaining 10% it showed the item from an incorrect perspective for some reason.

**Comment by TheSnowyChickens** [comment]
mini question: do you have rendering problems like that ?

![grafik](https://user-images.githubusercontent.com/29357962/124532108-26661780-de10-11eb-91c5-dde5f10cbee2.png)

:D
