### ISSUE TITLE
AE2 import/export massive amount of items

### ISSUE THREAD

**Issue by Miaawing** [AppliedEnergistics/Applied-Energistics-2#5296]
**Describe the feature**
At the current moment. with mods like Environmental tech and other ''get items fast'' mods. were processing 100-1000 items a second is not uncommon AE2 seems to fall behind in the performance section. AE2 gets the job done faster and effective than other pipe or storage mods. but at the cost of MASSIVE TPS lag. i always had the vision of AE" being the more server friendly autocrafting storage mod. but with these types of mods coming out. and being more commonly requested in modpacks. something needs to change related to how the code handles items in and out of the system every tick. 

This also is seen when shift clicking crafting items from a terminal. it will dead lock a server for a few seconds.

**Reasons why it should be considered**
Generally i see modded being a more community type gameplay thing. so server performance is a must. which AE2 have done well so far. i just saddens me that i have to choose something like refined storage over my favorite mod AE2 and have ''crappy looking systems'' just to have a better running server. i hope this is something that you guys already is working on since it seems to be a growing problem.

**Comment by Technici4n** [comment]
Hope you're on 1.16, we can't support 1.12.

If you are on 1.16, consider hopping on our Discord server with a [spark](https://spark.lucko.me/) profile and we'll have a look at your performance issue!

**Comment by Miaawing** [comment]
> Hope you're on 1.16, we dont't support older versions such as 1.12.
> 
> If you are on 1.16, consider hopping on our Discord server with a [spark](https://spark.lucko.me/) profile and we'll have a look at your performance issue!

i am on 1.16 even our own pack to keep things uptodate. ill see if i can find the spark profile i did. and give you guys those i got in my browser history :)

**Comment by Technici4n** [comment]
Requires something like MinecraftForge/MinecraftForge#7830 for further optimization.

**Comment by Miaawing** [comment]
> Requires something like [MinecraftForge/MinecraftForge#7830](https://github.com/MinecraftForge/MinecraftForge/pull/7830) for further optimization.

Guess the forge team aint much for fixing it

**Comment by Technici4n** [comment]
They are certainly interested in getting it fixed, but they're busy with the 1.17 update right now, this will have to wait a bit.

**Comment by Miaawing** [comment]
> They are certainly interested in getting it fixed, but they're busy with the 1.17 update right now, this will have to wait a bit.

Arh okey :D well hopfully they get some to pass it on both 1.17 and some past version
