### ISSUE TITLE
Add a command to summon a meteorite and more ideas...

### ISSUE THREAD

**Issue by AlgorithmX2** [AppliedEnergistics/Applied-Energistics-2#53]
Pls i think that it would a great idea to add a commando to generate a meteorite,

Other thing is to give user a initial book, like thinker construc, open blocks... where saids how to get the chargue crystals, how to use the seeds, etc... WITH PICTURES PLS

Originally Posted by yorch044

This issue was migrated; For original details see http://ae-mod.info/Tracker/0520/

**Comment by Blue64** [comment]
+1 on the Summon idea, Blood Magic Mod can summon various Meteors, and they even include an option for the meteors destroying blocks or not, but the documentation idea is also being discussed here:

https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/381

I'm totally new here so idk how to do any of the reference or labeling or anything.

**Comment by thatsIch** [comment]
Currently there is a Meteorite Placer as an unsupported developer tool. 

Only owner of this repository are allowed to place labels.
