### ISSUE TITLE
java.lang.ClassNotFoundException: net.fabricmc.fabric.mixin.structure.BiomeAccessor

### ISSUE THREAD

**Issue by William5553** [AppliedEnergistics/Applied-Energistics-2#5301]
**Describe the bug**

Game crashes on launch on [v8.2.0-alpha.1](https://github.com/AppliedEnergistics/Applied-Energistics-2/releases/tag/fabric%2Fv8.2.0-alpha.1) and up, doesn't crash on [v8.1.0-alpha.13](https://github.com/AppliedEnergistics/Applied-Energistics-2/releases/tag/fabric%2Fv8.1.0-alpha.13)

**To Reproduce**

Launch the game

**Expected behavior**

The game doesn't crash

**Additional context**

The game doesn't produce a crash report and exits with exit code 0. latest.log: https://pastebin.com/RZerZbgx

**Environment**

Curseforge Profile: [ae2 crash test.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/6659415/ae2.crash.test.zip)
Java 1.8.0.291 (64 bit)
Fabric 0.11.3

**Comment by Technici4n** [comment]
Latest is 8.3.0-alpha.3, can you try that one?
https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2/files/all

**Comment by Technici4n** [comment]
Please reopen if it still happens on the latest alpha.

**Comment by William5553** [comment]
Can confirm [v8.2.0-alpha.1](https://github.com/AppliedEnergistics/Applied-Energistics-2/releases/tag/fabric%2Fv8.2.0-alpha.1) to [v8.3.0-alpha.3](https://github.com/AppliedEnergistics/Applied-Energistics-2/releases/tag/fabric%2Fv8.3.0-alpha.3)

**Comment by Technici4n** [comment]
What if you download from curseforge? Mind sending the new crash if it happens?

**Comment by William5553** [comment]
Same crash
[latest.log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/6663157/latest.log)

**Comment by Technici4n** [comment]
This is a bug in AE2, we are incorrectly referencing a Fabric API mixin that was removed by FabricMC/Fabric#1495. Thanks for reporting, I'll fix this soon.

**Comment by Technici4n** [comment]
Fixed in 8.4.0-alpha.1.
