### ISSUE TITLE
AE2 Villager

### ISSUE THREAD

**Issue by Technici4n** [AppliedEnergistics/Applied-Energistics-2#5302]
We could possibly have our own villager profession, to make acquiring sky stone, presses, and possibly other resources easier on servers. That would require our own workstation as well.

**Comment by Technici4n** [comment]
@jlundberg-edgio your comment motivated me to implement that feature tonight. It will be in the next 1.19 release. ;)

**Comment by johalun** [comment]
@Technici4n Awesome!! Looking forward to it!

**Comment by johalun** [comment]
Deleted my original comment due to posting with wrong account but it was
> Yes! I would love to see this. Tech Reborn have their own villager professions and it's super helpful to help bootstrap your production. For example they could sell processors, smart cables and other components.
