### ISSUE TITLE
Started Minecraft after update and all text squares!

### ISSUE THREAD

**Issue by mcbigboy** [AppliedEnergistics/Applied-Energistics-2#5304]
I'm using CurseForge App to make a modpack. I saw that AE2 could be updated to 2.8.4.0, so I did. After, stated up the game and I get squares for text. I then closed it out. Replaced with version 2.8.3.1 and no more squares. 

Thanks

**Comment by shartte** [comment]
We need more info about your install to assess this issue. Please follow the instructions in the issue template to provide us with some standardized info.
