### ISSUE TITLE
Applied Energistics 2 and Flux Networks crash

### ISSUE THREAD

**Issue by WywySenariosa** [AppliedEnergistics/Applied-Energistics-2#5305]
Basically I do something and sometimes I crash. Vanilla fix always says its Applied Energistics 2 and Flux Networks crashing. I cannot remember the last time something has crashed and it wasn't Applied Energistics 2 and Flux networks. Vanilla fix also includes Laggoggles as the cause when installed. 

**I struggle with clarity, so please ask me to clarify if needed**

**Describe the issue**
I have appliedenergistics2-rv6-stable-7 version of AE2 and yesterday I updated flux networks to the most recent version.
Expected: No crash. Actual: Crashes randomly. Usually I interact with something, and then the server lags, (I'm playing singleplayer) and I crash. 

**Environment**
Force crash:
https://paste.dimdev.org/cufuyanuba.mccrash

On request I can force crash again.

Unforced crash:
https://paste.dimdev.org/getososelo.mccrash

- Environment: 
- Singleplayer
- appliedenergistics2-rv6-stable-7
- FluxNetworks-1.12.2-4.1.1.34
- According to manifest it is SkyFactory 4 version 4.2.2 before I started adding more mods
- Extra mods include (but not limited to) techguns, fossils and archelogy and advanced rocketry.
- End game island, meaning lots of machines but I can change any machine to your liking to fix the problem.
- A lot of quantum rings. Might be causing issues because here is where the majority of flux points are.
- AE2 addons have been installed, which might change interaction? I dunno
- ExtraCells-1.12.2-2.6.5
- ae2stuff-0.7.0.4-mc1.12.2
- AE2WTLib-1.12.2-1.0.34
- WirelessCraftingTerminal-1.12.2-3.12.97
- Several crash reports can be presented if needed
- Logs may be presented if needed
- full mod list may be presented if needed
- Screenshots/descriptions of my machines may be presented if needed
- No FPS issues (expect when my drawbridges are activated)
- Slight server lag, sometimes crafting in wireless terminals becomes really weird. Severe server lag happens before crashes.
- Coming back from AFK the past few days always results in crashes, meaning interaction does not cause crashes. Its completely random.
- Client restarts help? Sort of.

**Comment by shartte** [comment]
Sorry, we currently do not support any version older than Minecraft 1.15 anymore.

(p.s.: this was fixed in 1.16)

**Comment by WywySenariosa** [comment]
is there an in game workaround? like RTGs (Does putting flux points on energy accepotrs cause the crashes)? Or configs?
