### ISSUE TITLE
Can´t Autocraft with the Advanced Inscriber

### ISSUE THREAD

**Issue by DerKudu** [AppliedEnergistics/Applied-Energistics-2#5306]
Hello, i have the problem that i can´t autocraft the Printed Silicon . I have enough silicon in my system and i have the right recipe.
 For the 10 printed silicon he will 10 silicon presses. 
What can i do?

![Unbenannt](https://user-images.githubusercontent.com/86157072/122644327-ef57ec80-d114-11eb-98d9-986b6c98d369.jpg)

**Comment by Mari023** [comment]
while it is possible to automate it in a similar way you did, I would advise you to have the press constantly stay in the inscriber, and don't put it in the recipe.

The way you did it, the me "thinks" it will use up the press

**Comment by DerKudu** [comment]
Hey, that's right. I follow your instruction and it's done. Big thanks to you. Have a nice day =)
