### ISSUE TITLE
The interface terminal can see the template, but the synthesis terminal cannot synthesize

### ISSUE THREAD

**Issue by kongbai-s** [AppliedEnergistics/Applied-Energistics-2#5307]
![image](https://user-images.githubusercontent.com/65010311/122715730-e9404800-d29b-11eb-8367-e6a77b044288.png)
The interface terminal can see the composite template
![image](https://user-images.githubusercontent.com/65010311/122715756-f3624680-d29b-11eb-87b0-4af5dd622766.png)
However, the template can not be synthesized at the synthetic terminal, and Applied Energistics 2 item synthesis is not possible

**Comment by Technici4n** [comment]
I don't understand what synthetic and synthesize mean here? Could you use the correct English worlds? (as defined by the English translation keys)

**Comment by kongbai-s** [comment]
Sorry,I made a mistake.
I'm having problems with Modpacks。

**Comment by Serenazhou0629** [comment]
use crafting
