### ISSUE TITLE
1.17 release

### ISSUE THREAD

**Issue by SinLessGaming** [AppliedEnergistics/Applied-Energistics-2#5308]
**Describe the feature**
I was hoping to get a release for fabric on 1.17 for your mod AE2

**Reasons why it should be considered**
There is more than a few of us who chase the latest releases on minecraft nowadays.

**Comment by Technici4n** [comment]
No, we are waiting for Forge to port and then we will port to Fabric later. This is also the chance for us to rework a few things, so don't expect a release for a few weeks.

**Comment by SinLessGaming** [comment]
ok thank you guys for all the hard work you do
