### ISSUE TITLE
Help For 1.12.2 crash with java.lang.NoClassDefFoundError: ic2/api/energy/tile/IEnergyTile

### ISSUE THREAD

**Issue by SiewPao123** [AppliedEnergistics/Applied-Energistics-2#5318]
Crash Report:
https://pastebin.pl/view/fc197da9
Log:
https://pastebin.pl/view/e59fb3cd

This only happened after I installed applied energistics 2 to my modpack, I did change the dimensions I from 2 to -2 to -22 to 70 but it still crashed. I put it on a new folder without any mods and it loaded perfectly, can you guys tell me what I should do? My friends are looking forward for my modpack on thursday ;-; help pls

**Comment by mindforger** [comment]
not sure why, but pastebin.pl does not load, can you try pastebin.com instead?

also closure of the issue, since 1.12 isn't supported anymore, but with a loading crashlog one might give you help :)

**Comment by mindforger** [comment]
the link took a while to load, your IC2 is incompatible with this AE2 version!

**Comment by SiewPao123** [comment]
> the link took a while to load, your IC2 is incompatible with this AE2 version!

I dont have IC2 ;-;

**Comment by mindforger** [comment]
okay i may have phrased it wrong, besides AE2 there is "some other" mod that seems to include a broken API of IC2, which means the AE2 Version is incompatible to this other mod, which i can not tell

**Comment by SiewPao123** [comment]
Crash Report:
https://pastebin.com/VBWNYkvQ
Log:
https://pastebin.com/t1TuX4UX

**Comment by SiewPao123** [comment]
> Crash Report:
> https://pastebin.com/VBWNYkvQ
> Log:
> https://pastebin.com/t1TuX4UX

**Comment by mindforger** [comment]
try removing the wireless terminal addon and check if you can load a new world without it

maybe the addon needs an update or maybe you need a patch mod, which i know exists but no idea whree to find since 1.12 is way too old

**Comment by SiewPao123** [comment]
It still crashed. I searched online but still no luck ;-;
Newer Log:
https://pastebin.com/L0tCAsnM

**Comment by mindforger** [comment]
mh then i am sorry, i can not help you there, but the issue lies somewhere in the API used inside the mods, AE2 is expecting a class that is not present

**Comment by Ommina** [comment]
Try removing **spatialservermod-1.3.1.jar**

**Comment by SiewPao123** [comment]
> Try removing **spatialservermod-1.3.1.jar**

YES THANK YOU SO MUCH IT FIXED ITSELF. THANKS ! oops caps
