### ISSUE TITLE
Level Emitter stays active after crafting has finished

### ISSUE THREAD

**Issue by therealtkh** [AppliedEnergistics/Applied-Energistics-2#5319]
**Describe the bug**
This is hard to describe in few words so I recorded a video as well. It's unlisted and will probably be deleted in some time, but here it is:
https://www.youtube.com/watch?v=CY2xJ_6iey0
Using a Level Emitter with Crafting Card upgrade, in certain situations the Emitter stays on even though crafting job has finished. Breaking an re-placing ME cable (to disable Emitter) solves the problem - it will not turn back on.

**To Reproduce**
From what I have seen, it only happens when I order one product but recipe will give two, using Processing Pattern. Ingots or Dust from Ore will give two from one. If I order two products, Emitter will turn off as expected, but if I order one (the recipe is still for two), Emitter will stay on but only if they are inserted to the network one by one... This is shown in detail in the video.

**Expected behavior**
I would expect the Emitter to turn off after crafting has finished, just like it does when I order even number of products.

**Additional context**
This build/method worked fine in 1.12.2 (using rv6-stable7), but in the pack I tested in now (All The Mods 6 1.6.14 for Minecraft 1.16.5) the problem occurs. I don't have a functional 1.16.5 miniature pack with AE2 so at this time I have only tested in ATM6. 

**Environment**
Not sure how much more info you would need, I did a crashdump just in case:
https://pastebin.com/xPSqZ5YZ 
Windows 10
CurseForge app
Unmodified ATM6 pack - latest as of today

**Comment by Technici4n** [comment]
I am 99% sure this was fixed with the autocrafting rework in 1.17. Please reopen if the issue persists in 1.18+.
