### ISSUE TITLE
Security Terminal doesn't allow authorised users to access terminal

### ISSUE THREAD

**Issue by BlamedDoor** [AppliedEnergistics/Applied-Energistics-2#5320]
**To Reproduce**
1. Run server 
2. Create ME system
3. Add security terminal
4. Give another player a biometric card with Deposit, Withdraw, Craft, Build and Security permissions

**Expected behavior**
Other player is able to access the items in the ME system and is able to access security terminal.

**Additional context**
Imgur album with screenshots
[https://imgur.com/a/NL5boWS](url)

**Environment**
Link to list of mods
[https://pastebin.com/uTWUa2Ag](url)
Link to forced crash report
[https://pastebin.com/b6hRPiAR](url)

**Comment by mindforger** [comment]
your links are broken, but can be copied

**Comment by BlamedDoor** [comment]
No texture problems as far as I’m aware

**Comment by mindforger** [comment]
do you have the card inserted into the security terminal? the picture gives the impression you are only holding it in your hand?!

the idea behind a biometric card is it contains all data to authenticate the actual user that is imprinted with this card when he access the system from any point but the data have to be stored on the card, inside the security terminal

**Comment by BlamedDoor** [comment]
It would seem that was the issue

**Comment by mindforger** [comment]
to put it simple, the card could be stolen from the player which would make it useless and the therminal is locked to authenticated users and the owner only, so it is the best place to store the data
