### ISSUE TITLE
Cannot pull lexica Botania out of ME System

### ISSUE THREAD

**Issue by Estaria07** [AppliedEnergistics/Applied-Energistics-2#5322]
I am having trouble with pulling out the Lexica Botania book from Botania out of my Me system. I cannot pick up the book from a terminal nor shift click to get it out I currently have 10 stored in there but cant remove any.

Minecraft ver: 1.12.2
Applied energistics 2 ver: rv6-stable-7
Botania ver: r1.10-364.4

steps to reproduce:
Place a Lewxica Botania book into a ME system.

Edit: After taking out the drives and putting them back in I can take it out again however putting them back in they are stacked separately and the new stack can no longer be taken out again.

**Comment by mindforger** [comment]
Try an export bus with fuzzy card. Unfortunately 1.12 is not getting any service anymore
