### ISSUE TITLE
Some text is unreadable with Unity: Dark installed

### ISSUE THREAD

**Issue by CodeGordon** [AppliedEnergistics/Applied-Energistics-2#5328]
**Describe the bug**
Text for things such as energy totals when using the Network Tool or auto-crafting amounts when using various terminals matches the window color when using the Unity: Dark resource pack.

**To Reproduce**
Install AE2, Unity, and Unity: Dark. Open the Network Tool or terminal dialogue as described above.

**Expected behavior**
Text to be displayed in a color that does not match the background.

**Additional context**
This issue is new to version 8.4.0, as version 8.3.1 displayed such text in a color that was readable.

**Environment**
Windows 10, Forge v36.1.32

**Comment by Technici4n** [comment]
Have you tried tweaking AE2's style files to change the text color?

**Comment by CodeGordon** [comment]
> Have you tried tweaking AE2's style files to change the text color?

I tried the mod menu's config button, but that isn't set up for AE2. Having to manually tweak the configs for something that worked in the previous version isn't a good solution, especially if that includes having to unpack the mod's JAR file.

**Comment by Technici4n** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/main/resources/assets/appliedenergistics2/screens/common/palette.json

You can override this file with a resource pack to change the text color I believe. That should probably be done by Unity directly if it works.

**Comment by yueh** [comment]
As said, that is up to the texture pack to solve.

**Comment by CodeGordon** [comment]
> As said, that is up to the texture pack to solve.

Be that as it may, there was clearly a change in this version, and it would be helpful to know which settings should be reported to the Unity project as having changed.

**Comment by omeranha** [comment]
@Technici4n I tried setup this palette.json to #ffffff (white), but the color not changes, tried with resource pack and even inside mod (just for testing), any ideas?

**Comment by shartte** [comment]
I can't actually tell what they did to change the font color before, because it wasn't really supported.

The new approach is to override the palette via the resource pack, this _should_ work (I did test it).

It has to be in assets/appliedenergistics2/screens/common/palette.json in the resource pack.
Let me know if this does NOT work.

**Comment by omeranha** [comment]
i copied the entire screens folder, changed the color and not worked :( @shartte

**Comment by Technici4n** [comment]
Did you put it in the correct location in the resource pack? Changing the palette alone is enough btw.

**Comment by omeranha** [comment]
![image](https://user-images.githubusercontent.com/53233626/125112685-e1670d00-e0bd-11eb-8cea-745e76ca2bb1.png)
