### ISSUE TITLE
(Fabric) Techreborn machines can't auto-output or auto-input items into any AE2 blocks

### ISSUE THREAD

**Issue by brenodantas10** [AppliedEnergistics/Applied-Energistics-2#5330]
**Describe the bug**

Techreborn machines cannot output or input to ME interfaces or even the skyblock chest while it can auto-output or auto-input to any vanilla storage block. (although AE2 blocks can do both actions with Techreborn blocks)

**To Reproduce**

 - Setup energy for a ME system and the Techreborn machine with a ME Interface (or Skyblock Chest) attached to it
 - Configure an item into ME interface to pull from the ME network (if skyblock chest can jump this)
 - Set the Techreborn machine to auto-input and auto-output from the attached side
 - Watch it doing nothing.

**Expected behavior**

The machines should push and pull items into the AE2 block without any trouble

**Additional context**

Yes, I can use import/export bus and ask an auto craft normally with a ME Interface attached to any Techreborn machines, it's just the other way around that doesn't work.
Also, [Techreborn Issue#2221](https://github.com/TechReborn/TechReborn/issues/2221)

**Environment**

- Game Setup:
  * MultiMC
  * Fabric Loader 0.11.6
  * Fabric API 0.34.7+1.16
  * AE2 8.3.0-alpha.3
  * Tech Reborn 3.8.4+build.236
  * Performance mods (Sodium, indium, lithium, starlight)

- Environment: 
  * Ubuntu 20.04.2 LTS
  * Intel® Core™ i7-6500U CPU @ 2.50GHz × 4
  * Mesa Intel® HD Graphics 520 (SKL GT2)

**Comment by Ommina** [comment]
While I can't speak to the chest, you are using the full block (not part) Interfaces for these tests, yes?

**Comment by brenodantas10** [comment]
yes, I'm speaking for the ME Interface as a block. but even using the ME Interface as a bus this occurs

**Comment by CygnusiaX1** [comment]
I have had the same problem with the ME Interface (block only, not bus) to export into. I ended up using a hopper as a go-between for the two. I had read somewhere else that apparently, AE2 doesn't register the interfaces as a proper inventory, and TechReborn won't output to it due to that. I have no issues with the bus version, as I wrap them around my TechReborn machines for inserting items.

**Comment by Technici4n** [comment]
You need buffer chests at the moment, a solution should be found during the 1.17 release cycle (no, AE2 isn't ported yet, and won't be before forge is released).
