### ISSUE TITLE
issue on storeing stuff via sptial storage

### ISSUE THREAD

**Issue by TheNimbleNinja** [AppliedEnergistics/Applied-Energistics-2#5333]
**Describe the bug**
okay i have a major issue
when i tried to store my custom build in a spatial io cell some things were not included in the storege blocks from ore regen mod were not included and little tiles blocks were not included so this is breaking my custom map very badly can you fix this
**To Reproduce**
try storeing little tiles blocks/ ore regen blocks and it wont store
**Expected behavior**
the stuff to get stored in the cells so i can make my custom map!
**Additional context**

**Environment**

- Environment: 
this is happening on version rv6-stable-7

**Comment by Technici4n** [comment]
Mods must opt into spatial IO support themselves. Also, note that we don't support 1.12 anymore.
