### ISSUE TITLE
Shift clicking items into terminal moves all of that item

### ISSUE THREAD

**Issue by HueboWasTaken** [AppliedEnergistics/Applied-Energistics-2#5337]
I'm not sure if this is a bug or if it's intended but it's incredibly frustrating (it's also possible it isn't even AE2 doing this). 

**Describe the bug**

I have 5 stacks of iron ingots in my inventory, I want to keep one stack so I start shift clicking the others into the terminal, after shift clicking the second stack, all stacks of that item (iron ingot) are automatically moved, leaving me no iron ingots in my inventory. If there are any iron ingots in the crafting grid at the time, they will also be dumped back into the system.

**To Reproduce**

Have multiple stacks of an item in your inventory
Start shift clicking them into the terminal 
all existing stacks of that item will be automatically moved into the terminal 

**Expected behaviour**
only the stacks that I shift click myself should go into the terminal

if this is intended, is there a way to turn it off? it's driving me insane

playing All of Fabric 3 modpack
AE2 version: 8.3.0-alpha.3

**Comment by yueh** [comment]
Doubleclicking the same item quickly will move all other stacks of the same type to the ME network, that's a QoL feature for quickly emptying someone's inventory.

**Comment by HueboWasTaken** [comment]
> Doubleclicking the same item quickly will move all other stacks of the same type to the ME network, that's a QoL feature for quickly emptying someone's inventory.

I'm not double clicking, I do love that feature though. I've discovered it's the Mouse Wheelie mod causing it, I shift click one stack then I click another stack while still holding shift which activates their shift click and drag feature, this for some reason causes all the stacks of one item to be put into the terminal, even the ones I didn't drag my mouse over. 

Since it doesn't happen in other inventories I'm assuming this is a compatibility issue, I'll report it on the mouse wheelie issue tracker too.
