### ISSUE TITLE
(Fabric 1.16.5) The server crashes.

### ISSUE THREAD

**Issue by PTOM76** [AppliedEnergistics/Applied-Energistics-2#5351]
**Describe the bug**
Excuse me.
Single play works fine, but AE2 crashes server. It works with AE2 alone, but if you add other mods, an error will occur.

**To Reproduce**
Start with AE2 and other mods on the Fabric 1.16.5 server.

**Expected behavior**
As you can see from the explanation, it's probably causing conflict.

**Additional context**
- latest.log: https://pastebin.com/5WKN0xgj
- crash-2021-08-01_22.10.35-server: https://pastebin.com/bwASjmpV

**Environment**
- Environment: Server
- MOD Loader: FabricMC
- Game Version: 1.16.5
- Java: 16
- OS: Windows 10
- MOD:
  - gravestones-v1.9.jar
  - Hwyla-fabric-1.16.2-1.9.23-79.jar
  - improved-stations-2.0.3.jar
  - libblockattributes-all-0.8.8.jar
  - libcd-3.0.3+1.16.3.jar
  - RebornCore-1.16-4.7.3+build.136.jar
  - RoughlyEnoughItems-5.12.248.jar
  - simplepipes-all-0.5.0.jar
  - simpleteleporters-2.2.1.jar
  - SimpleVoidWorld-5.0.0.jar
  - TechReborn-1.16-3.8.4+build.236.jar
  - torcherino-14.0.1+1.16.4.jar
  - vanilla-hammers-3.0.3-1.16.5.jar
  - appleskin-forge-mc1.16.x-2.1.0.jar
  - appliedenergistics2-fabric-8.4.0-alpha.1.jar
  - CardboardMod-1.16.4.jar
  - cc-tweaked-1.16.5-1.97.0.jar
  - cloth-api-1.5.50.jar
  - cloth-config-4.11.26-fabric.jar
  - diggusmaximus-1.4.2-1.16.3.jar
  - expandedstorage-5.6.33+1.16.5.jar
  - fabric-api-0.37.1+1.16.jar
  - fabric-furnaces-1.3.3-1.16.4.jar
  - fabric-language-kotlin-1.6.2+kotlin.1.5.20.jar
  - fabric-language-scala-1.1.0+scala.2.13.6-fat.jar"

**Comment by mindforger** [comment]
>D:\minecraft\fabric\1.16.5\server\.\crash-reports\crash-2021-08-01_22.10.35-server.txt

That report would be better to have

**Comment by PTOM76** [comment]
I got it. Added Crash Report.

**Comment by mindforger** [comment]
does that happen without spigot? Because the crash looks very strange and does not seem to be realted to AE at all

**Comment by PTOM76** [comment]
That was the case. excuse me. thank you
