### ISSUE TITLE
(1.16.5) Fabric Game Crashes on Start

### ISSUE THREAD

**Issue by Pikman1210** [AppliedEnergistics/Applied-Energistics-2#5352]
**Describe the bug**

Game fails to launch and crashes

**To Reproduce**

Start the game with version "1.16.5 8.3 alpha.3"

**Expected behavior**

The game should start and not crash.

**Additional context**

https://gist.github.com/Pikman1210/8733912b786517f9b3056e8043b2df27
Game crashes with and without other mods present

**Environment**

Environment: Java
MOD Loader: FabricMC
Game Version: 1.16.5
Java: Unknown
OS: Windows 10
(this is on a friend's pc, he wanted me to make the report instead of him, my version is the same yet starts fine)

**Comment by mindforger** [comment]
you have a broken config, backup your config and generate a new, then check if it still fails

**Comment by Pikman1210** [comment]
How can I do that?

**Comment by mindforger** [comment]
>[20:53:30] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: Failed to load AE2 config: C:\Users\eczaj\AppData\Roaming\.minecraft\config\appliedenergistics2\client.json

just move that file somewhere else and restart the server as far as i am aware it should regenerate itself .... also post a copy of that file or compare it yourself with the generated one, to see if you can spot the difference

**Comment by Pikman1210** [comment]
Thank you for the help, I’m close this issue tomorrow if it works!

**Comment by Pikman1210** [comment]
It worked! Thank you!
