### ISSUE TITLE
Combine the behaviour of Item P2P tunnel in rv6 and rv8 and apply on all similar P2P

### ISSUE THREAD

**Issue by DoremySwee** [AppliedEnergistics/Applied-Energistics-2#5353]
**Describe the feature**
It seems that in rv8 Storage Bus or other blocks monitoring the storage of blocks cannot do that through P2P.  (In addition, getting items out of the output side of the tunnel)
However, it works in rv6. For instance, Storage Bus can monitor the exact content of the ME Interface.
Is it possible to combine the behaviour of item P2P tunnel in rv6 and rv8? (And also apply that on the fluid (and energy? ) tunnels)
To be a little bit more specific:
      When recieving items:
           Detect the number of items, "equally" divide them to the output sides of the tunnel.
      When being monitored (not that special capability from storage bus, but normal item monitoring):
           Return the sum of available items.
      When getting items out of the tunnel:
           Get "equal" amount of items out of the output sides of the tunnel.

**Reasons why it should be considered**
Both features are extremely useful. Without the equal division it would be hard for AE2 divide items equally, while there are lots of brilliant automation design based on P2P in rv6.

**Comment by yueh** [comment]
This will not be added back. With the changes in Forge it is not as trivial to track all attached inventories with a chained wrapper anymore. (and probably not ideal for performance)

Further P2P is a transport/pipe system system to complement some features not really possible with the normal ME storage. Which also means that I will not provide functionality, which is already possible normally.

**Comment by DoremySwee** [comment]
> This will not be added back. With the changes in Forge it is not as trivial to track all attached inventories with a chained wrapper anymore. (and probably not ideal for performance)
> 
> Further P2P is a transport/pipe system system to complement some features not really possible with the normal ME storage. Which also means that I will not provide functionality, which is already possible normally.

Then what about another option changing the "blocking" of interface? (then three options in all, two current blocking options and a new option using AE2's special capability of monitoring?)
Or should I open a new issue?
![image](https://user-images.githubusercontent.com/66953201/129012742-cd001e4c-2ef1-4890-90be-a3728d922c2d.png)
