### ISSUE TITLE
Clientside crash with rendering AE2 skycompass

### ISSUE THREAD

**Issue by Nyinxie** [AppliedEnergistics/Applied-Energistics-2#5354]
**Describe the bug**
same as subject. 

**To Reproduce**
install AE2 and use JEI/inventory

**Expected behavior**
no crashes :>

**Additional context**
[Gist](https://gist.github.com/Nyinxie/e0f254456202ede9af99aa0ab064b87d)

**Environment**
Forge 1.16.5 - 36.2.2

- Environment: 
[Forced crash log F3+c](https://gist.github.com/Nyinxie/2d4067c143d2aa65bf53cead5fde31bc)

**Comment by Nyinxie** [comment]
from messing around with versions, I do believe it's to do with anything added after appliedenergistics2-8.3.1.jar

**Comment by yueh** [comment]
We do not support Optifine or other "performance" mods. Please remove them and try to reproduce it again.
