### ISSUE TITLE
java.lang.IllegalArgumentException: invalid itemStack in slot [1] after updating create on server

### ISSUE THREAD

**Issue by LordNoisy** [AppliedEnergistics/Applied-Energistics-2#5359]
**Describe the bug**
After updating from create 0.3.1c to the most recent version of create I get this issue and the server (Forge 36.2.0) will not start.

**To Reproduce**
Update from create 0.3.1c to the most recent version of create I get this issue and the server will not start, although I'm not sure if this is specific to my world

**Expected behavior**
The server should start

**Additional context**
Crashlog:
https://pastebin.com/pG684X4G

**Environment**
Crashlog above
Forge Server (1.16.5 - 36.2.0)
AE2 8.4.0

**Comment by embeddedt** [comment]
Create removed some items in 0.3.2, so I suspect this is caused by the removed items still being referenced in an AE2 pattern.

**Comment by TheRealWormbo** [comment]
It's apparently not just server start, but also any way of loading an area. I recently "soft banned" myself from a server this way (i.e. the server kept crashing whenever I logged in) after going to an abandoned base until the admin edited my coordinates to be nowhere near that base.
IMHO an invalid entry in a crafting pattern (at least that's what I read from this crash log) should not crash a server.
