### ISSUE TITLE
Autocrafting not working when Pattern Terminal attached to network (No CPU's available)

### ISSUE THREAD

**Issue by Kulturnilpferd** [AppliedEnergistics/Applied-Energistics-2#5367]
Hey there,
do I something wrong? 
Maybe build a separate AE2 network just for pattern crafting as a workaround?
I'm on 1.16.5 (AOF3 Modpack)

**Comment by Tahakk** [comment]
1. use the predetermined Issue template next time
2. you need to have Patter wit recipe, Mollecular Assemblers solo ir with Interface combination (to put the pattern into) and Crafting CPU's (so 3 parts total)

**Comment by Kulturnilpferd** [comment]
Have used an totally packed up flux cable, changed to the 32-Channel one, now it works :)
