### ISSUE TITLE
Seemingly random crashes on dedicated 1.16.5 forge server.

### ISSUE THREAD

**Issue by LordNoisy** [AppliedEnergistics/Applied-Energistics-2#5374]
**Describe the issue**
At random intervals the mod crashes the server, sadly I cannot give much more information than this. A user has been playing with quantum bridges a lot recently, and some users noticed a slowdown/latency when plugging a new crafting terminal into an AE2 system prior to when the frequent crashes started happening.

**Environment**
Forge 36.2.0
Java 8
1.16.5
https://pastebin.com/bX13MczB

**Comment by Technici4n** [comment]
Seems part of the log is missing. Can you provide the full log, please?
