### ISSUE TITLE
Suggestion for a more accurate time calculation

### ISSUE THREAD

**Issue by leonbeer** [AppliedEnergistics/Applied-Energistics-2#5388]
I noticed that the autocrafting doesn't seem to be very accurate with the time calculation, because of various machines needing more time than the Molecular assembler, which i think the time is for.

**Describe the feature**
I would be a nice feature for the ME to "Remember" The last time that it took to craft, to make a more accurate estimate on the time it will take.

**Reasons why it should be considered**
It is just a little thing some players would probably appreciate.

**Comment by yueh** [comment]
The ETA is just a very basic guess based on how many tasks a job has and how long it did run. There is simply no way to guess or even maintain a value of how long each item would take.

For example when crafting something which needs 2 ingots in parallel, it could easily lead to one type being stuck somewhere for minutes until all other ingots are smelted. While a job with the ingot now marked as 5 minutes per item and something not needing the same furnace is reporting a couple hours and then done in less than a minute.
