### ISSUE TITLE
The game always crashes.

### ISSUE THREAD

**Issue by orrinpants** [AppliedEnergistics/Applied-Energistics-2#5400]
**Describe the bug**
With the mod, the game crashes.

**To Reproduce**

Just play the game with the mod.
**Expected behavior**

The game running with the mod.
**Additional context**

The first time I did it it worked until I created a world.
**Environment**

There was no environment as I didn't get to play a world.

**Comment by orrinpants** [comment]
Nevermind, I think I just had too many tabs open.

**Comment by orrinpants** [comment]
Nope, it just made it get farther before crashing.

**Comment by ramidzkh** [comment]
If browser tabs is influencing how far it goes, you're definitely running out of memory

**Comment by shartte** [comment]
Please provide more information as described in the issue template (the initial value of the text box when you create an issue).

**Comment by orrinpants** [comment]
Nevermind, it's an issue with MultiMC apparently.

**Comment by orrinpants** [comment]
Actually, I had to restart my computer.
