### ISSUE TITLE
Charged Certus duplication glitch

### ISSUE THREAD

**Issue by CrystalDiamondia** [AppliedEnergistics/Applied-Energistics-2#5402]
It's possible to duplicate Charged Certus Quartz, and only Charged Certus Quartz, by using Mekanism's cardboard boxes.

**Describe the bug**
Placing a cardboard box on top of any chest-like storage container (I discovered it trying to move a chest from the Iron Chests mod, but it works with vanilla chests) with Charged Certus Quartz inside will cause the quartz to drop as an item outside the box, but the exact same amount of quartz will still be inside of the container once the box is removed. This glitch, as far as I can tell, cannot be replicated with any other item.
This could potentially be an issue with Mekanism, or maybe the modpack, but since it only works on this specific item from AE2, I decided to put the issue here.

**To Reproduce**
1. Place down storage container.
2. Put any amount of Charged Certus Quartz inside.
3. Put a cardboard box on it by right clicking.
4. Remove cardboard box from container by shift and right clicking.

**Expected behavior**
I expected the box to simply encase the chest along with its contents, not duping anything.

**Additional context**
![2021-08-25_11 08 34](https://user-images.githubusercontent.com/54674248/130764059-40e5cc5f-f7b6-455b-b2d6-018d8cb3f938.png)
![2021-08-25_11 08 31](https://user-images.githubusercontent.com/54674248/130764044-04059e92-0791-4734-8823-2d37a6369b1f.png)
![2021-08-25_11 08 42](https://user-images.githubusercontent.com/54674248/130764073-b780dafa-8db1-45d1-adea-42e169562782.png)
![2021-08-25_11 08 46](https://user-images.githubusercontent.com/54674248/130764032-a4c0ad37-c72e-426a-8e9c-33f9b9600dec.png)

**Environment**

- Environment: I am playing on version 1.7.11 of All the Mods 6, with no additional mods installed.

**Comment by shartte** [comment]
Sorry, we currently do not support any version older than Minecraft 1.16 anymore.

**Comment by shartte** [comment]
Oooooooops. I read "1.7" and turned off my brain ;-)

**Comment by Technici4n** [comment]
This is likely still an issue, the root cause of which is:
- Mekanism uses `EntityJoinWorldEvent` to cancel any item drop that happens when it is removing the tile entity. Pseudo code:
```
startCancelingItemDrops();
setBlockState(world, pos, air);
stopCancelingItemDrops();
```
- Forge uses `EntityJoinWorldEvent` to cancel item drops for stacks that have a custom item entity, and then schedules the spawn of the custom entity **the next tick**, which Mekanism doesn't detect.

**Comment by Technici4n** [comment]
Reported to Mekanism as it is not an AE2 issue, thanks!
