### ISSUE TITLE
ME Interface on subnet is unable to retrieve/send items from/to main network

### ISSUE THREAD

**Issue by teammate165** [AppliedEnergistics/Applied-Energistics-2#5407]
**Describe the issue**
I'm currently making a subnet to handle a Mystical Agriculture farm. It will pull items from the main network and craft up the fertilizers as well as send the farm products back to main network. I'm using an ME Interface + Storage bus combo to link storage between the networks.

Initially after setting it up the system seems to be functional, Interfaces pulling items in, crafting them if need and other interface sending the farm output back. After a while I went to check on the farm and everything just freezes up. The crafting CPUs on the subnet is frozen, ME Interfaces no longer pulling/pushing items from/into the main network. I tried re-doing the setup as well as simplifying it down to a single ME Interface on the subnet but to no avail. That ME Interface will refuse to pull items in the config slot as well as refuses to push the items back. I tried breaking/replacing all the possible parts but the behavior still persists

So I went to a creative world to replicate the [setup](https://imgur.com/a/eGeMa43) (ignore the Compact Machine stuff). The network with an ME drive is the main network as it has the storage. To my surprise, the ME Interface is working correctly, sending/pulling items without problems. I went back to my survival world and replicated the setup in a different spot, everything is working normally. Now I'm really confused as to why it would refuse to work in my base. Asking around in the modpack's discord didn't help much

**Environment**
- Forced crash report: https://pastebin.com/d9Ah2aSw
- Modpack Engimatica 2 Expert (E2E) version 1.83
- AE2 version stable rv6-stable-7
- Forge version 14.23.5.2855

**Comment by Mari023** [comment]
do you have a security terminal on your main network?

**Comment by teammate165** [comment]
I do yes

**Comment by Mari023** [comment]
that is why it is not working
I think it is possible to put a blank card in the terminal (with some permission, but no player) and then it should work
otherwise you would have to use a security terminal on the subnet

**Comment by teammate165** [comment]
Now that you've mentioned it I remember putting a security terminal and a wireless access point on my subnet in the Compact machine to use my wireless terminal. Removing the security terminal probably broke it
