### ISSUE TITLE
Crash minecraft when launching 

### ISSUE THREAD

**Issue by Pana321** [AppliedEnergistics/Applied-Energistics-2#5409]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional context**

**Environment**

- Environment:

**Comment by Pana321** [comment]
I have a bug that when i launch my minecraft later it crashes i have a crash log but idk why it is
[crash-2021-08-29_19.25.49-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/7072956/crash-2021-08-29_19.25.49-client.txt)

**Comment by shartte** [comment]
Sorry, we currently do not support any version older than Minecraft 1.16 anymore.

However, you have to configure unique dimension ids in the version of MC you are using. Check the mod config files.

**Comment by Pana321** [comment]
let me try

**Comment by Pana321** [comment]
what do i do

![AppliedEnergistics2 30_08_2021 19_23_09](https://user-images.githubusercontent.com/89701800/131379338-874164bb-1182-439f-9da8-054dd5bc3bf4.png)
](url)

**Comment by Tahakk** [comment]
open it wit text editor and edit ID of the dimension
