### ISSUE TITLE
Toggling the ability to hold shift to see patterns

### ISSUE THREAD

**Issue by jasonjlam** [AppliedEnergistics/Applied-Energistics-2#5410]
Not sure if it is a version change or a bug, but as of the latest 1.12 version (This problem occurs on AE2 rv6-stable 7 for 1.12) patterns in the interface terminal are not shown by default; you have to hold shift, which interferes with dragging the patterns in. 

**There should be a config for whether or not patterns are shown by default, or if they should only be shown when shift is held.**

**Comment by shartte** [comment]
Please define "latest version".

**Comment by jasonjlam** [comment]
This problem occurs on AE2 rv6-stable 7 for 1.12. Updated original post.

**Comment by Technici4n** [comment]
We no longer support any minecraft version older than 1.16 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
