### ISSUE TITLE
Не закидываются золото, алмазы, редстоун AE2 STAFF

### ISSUE THREAD

**Issue by W1ndit** [AppliedEnergistics/Applied-Energistics-2#5411]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional context**

mod AE2 Staff, не закидываются конкретные предметы из ванили(золото, алмазы, редстоун) в продвинутный высекатель, я пробовал и через шину экспорта и сам по 1 штуке или стаку, пробовал переустановить с другого сайта, не помогло, версия AE2 rv6 stable7, версия AE2 Staff 0.7.0.4
**Environment**

- Environment:###

**Comment by Mari023** [comment]
after google translating this, it looks like an ae2 stuff problem and not an Applied Energistics 2 problem
also, if I remember correctly, the latest ae2 stuff version is for 1.12.2 which is not supported anymore

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.16 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
