### ISSUE TITLE
Search in terminal does't work correctly for Russian 

### ISSUE THREAD

**Issue by imcasper** [AppliedEnergistics/Applied-Energistics-2#5416]
**Describe the bug**

Search in terminal not work correct.

**To Reproduce**

I use simple ME network (power from adapter, one simple terminal, one controller with for memory cells)
I open terminal GUI.
My language -- russian (it is improtant)
Start search (by name) something "Кварц" / "Кальцитовая пыль" for example -- result is empty...
If i enter "варц" /  "альцитовая пыль" (without first big char) -- result showed (correctly for any word part)
Search on english in equal case is good (item with name "Quartzite Sand" for example)
Other languages im not tested.

**Expected behavior**
Search work with for any part of word (from start too)

**Additional context**
[fabirc] 8.4.0.alpha.2

**Environment**
many other mods.
if bug not reproduced, i can make mod list and send it.

PS I have custom fonts, and used options "unicode off" by default.... 
But i try switch options (unicone on) -- behaviour not changed.

Maybe the word gets distorted in translation. An invisible space is added, special formatting characters, or some other nasty thing going on. For me, as a user, the search does not work as it should.

**Comment by Jly4** [comment]
Im too have this...(
Release 8.4.1 Forge

**Comment by yueh** [comment]
We use a basic case insensitive matcher for it. However I am not familar how this does work with the russian alphabet. So I guess someone with more insight would need to provide a PR or otherwise useful details about it.

**Comment by imcasper** [comment]
I suppose that it is enough to run the game in Russian (maybe in anything other than English). And see the search under the debugger.
Telepathically, I can assume that the beginning of the name is distorted, or the beginning of the line is incorrectly determined. If the whole line broke, the search would not work at all.

**Comment by Romz24** [comment]
@yueh 
I confirm, I have the same problem with search. How can I start debugging to help with this problem?

**Comment by shartte** [comment]
Corresponding code is at appeng/client/gui/me/common/Repo.java:142

**Comment by shartte** [comment]
Thanks to @vsergeenko777 for fixing this!
