### ISSUE TITLE
Terminal with no items even though i have cells with items in drives

### ISSUE THREAD

**Issue by Gavin123-code** [AppliedEnergistics/Applied-Energistics-2#5419]
So basically what happened was I set up a really overpowered mob farm to kill Androids from matter overdrive so I can get legendary parts and when I activate it one time all of the items in my me system GONE I am playing FTB revelations with a PVP client mod mods that I like and a few other stuff and everything recess whenever I open the terminal I have the channels disabled in the configuration everything was going great until this started happening. How do I re-create this: I don’t know make the same exact mob farm and disable channels in the configurations. And Me system is basically brokenI think I have too many items in there because it is a little too over powered

**Comment by mindforger** [comment]
Guessing from the ONLY HINT you gave, that you disabled channels, you are using a MC version below 1.16, which is not supported anymore. And if you did not get my hint, next time add more details please

**Comment by Gavin123-code** [comment]
Everytime i open the terminal the items reset

**Comment by mindforger** [comment]
Again, please provide a proper report, following the template

**Comment by Technici4n** [comment]
Note that we don't support versions older than 1.16.
