### ISSUE TITLE
Duplication bug with AE2 in Minecraft forge 1.16.5

### ISSUE THREAD

**Issue by xTewph** [AppliedEnergistics/Applied-Energistics-2#5422]
**Describe the bug**
Item duplication with AE2 autocrafting, item p2p tunnels and interface

**To Reproduce**
I made a video where I show how to reproduce it
Here is the link: https://youtu.be/Ya5Ibfk_f1w

**Environment**
[crash-2021-09-09_20.52.20-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/7140305/crash-2021-09-09_20.52.20-client.txt)

- Environment: Minecraft 1.16.5, forge 36.2.0, handcrafted modpack, Linux Ubuntu. USING AE2 VERSION 8.4.0.

**Comment by Technici4n** [comment]
Duplicate of #5334

**Comment by Technici4n** [comment]
We'll get the fix out soon!
