### ISSUE TITLE
Crash during startup

### ISSUE THREAD

**Issue by lolgod123534** [AppliedEnergistics/Applied-Energistics-2#5431]
I was making a modpack for my friends to play on but when trying it, it would crash while loading. (I'm using curseforge)
Crash report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  RandomPatches (randompatches-1.12.2-1.22.1.10.jar)
  CorePlugin (SmoothFont-mc1.12.2-2.1.2.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  PerformantLoadingPlugin (performant-1.12.2-1.10.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  Born in a Barn (Born In A Barn V1.8-1.12-1.1.jar)
  Plugin (NotEnoughIDs-1.5.4.4.jar)
  McLib core mod (mclib-2.3.5-1.12.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.7.3-SNAPSHOT-20210323.072210-core.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.16.jar)
  SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 9/15/21 10:36 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Energistics 2 (appliedenergistics2)
Caused by: java.lang.IllegalArgumentException: Failed to register dimension for id 2, One is already registered
	at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:134)
	at appeng.core.Registration.registerSpatialDimension(Registration.java:201)
	at appeng.core.Registration.postInit(Registration.java:352)
	at appeng.core.AppEng.postInit(AppEng.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 945061328 bytes (901 MB) / 3106930688 bytes (2963 MB) up to 4682940416 bytes (4466 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5024m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 123 mods loaded, 122 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                      | Version                  | Source                                         | Signature                                |
	|:----- |:----------------------- |:------------------------ |:---------------------------------------------- |:---------------------------------------- |
	| LCHIJ | minecraft               | 1.12.2                   | minecraft.jar                                  | None                                     |
	| LCHIJ | mcp                     | 9.42                     | minecraft.jar                                  | None                                     |
	| LCHIJ | FML                     | 8.0.99.99                | forge-1.12.2-14.23.5.2855.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | forge                   | 14.23.5.2855             | forge-1.12.2-14.23.5.2855.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | ivtoolkit               | 1.3.3-1.12               | minecraft.jar                                  | None                                     |
	| LCHIJ | smoothfontcore          | mc1.12.2-2.1.2           | minecraft.jar                                  | None                                     |
	| LCHIJ | foamfixcore             | 7.7.4                    | minecraft.jar                                  | None                                     |
	| LCHIJ | srm-hooks               | 1.12.2-1.0.0             | minecraft.jar                                  | None                                     |
	| LCHIJ | randompatches           | 1.12.2-1.22.1.10         | randompatches-1.12.2-1.22.1.10.jar             | None                                     |
	| LCHIJ | smoothfont              | mc1.12.2-2.1.2           | SmoothFont-mc1.12.2-2.1.2.jar                  | None                                     |
	| LCHIJ | jei                     | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                      | None                                     |
	| LCHIJ | abyssalcraft            | 1.10.4                   | AbyssalCraft-1.12.2-1.10.4.jar                 | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJ | ctm                     | MC1.12.2-1.0.2.31        | CTM-MC1.12.2-1.0.2.31.jar                      | None                                     |
	| LCHIJ | chisel                  | MC1.12.2-1.0.2.45        | Chisel-MC1.12.2-1.0.2.45.jar                   | None                                     |
	| LCHIJ | mantle                  | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                       | None                                     |
	| LCHIJ | quark                   | r1.6-179                 | Quark-r1.6-179.jar                             | None                                     |
	| LCHIJ | twilightforest          | 3.11.1021                | twilightforest-1.12.2-3.11.1021-universal.jar  | None                                     |
	| LCHIJ | tconstruct              | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar               | None                                     |
	| LCHIJ | acintegration           | 1.11.3                   | AbyssalCraft Integration-1.12.2-1.11.3.jar     | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJ | aether_legacy           | 1.5.3.2                  | aether-1.12.2-v1.5.3.2.jar                     | None                                     |
	| LCHIJ | aether_legacy_addon     | 1.12.2-v1.3.0            | Aether Continuation v1.3.0.jar                 | None                                     |
	| LCHIJ | aoa3                    | 3.3.6                    | AoA3-3.3.6.jar                                 | 8bddeac148843f40e0b9f69201be2f4b3071700d |
	| LCHIJ | appleskin               | 1.0.14                   | AppleSkin-mc1.12-1.0.14.jar                    | None                                     |
	| LCHIE | appliedenergistics2     | rv6-stable-7             | appliedenergistics2-rv6-stable-7.jar           | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHI  | attributefix            | 1.0.4                    | AttributeFix-1.12.2-1.0.4.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHI  | atum                    | 2.0.20                   | Atum-1.12.2-2.0.20.jar                         | None                                     |
	| LCHI  | autoreglib              | 1.3-32                   | AutoRegLib-1.3-32.jar                          | None                                     |
	| LCHI  | codechickenlib          | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHI  | avaritia                | 3.3.0                    | Avaritia-1.12.2-3.3.0.37-universal.jar         | None                                     |
	| LCHI  | battletowers            | 1.6.5                    | BattleTowers-1.12.2.jar                        | None                                     |
	| LCHI  | betteradvancements      | 0.1.0.77                 | BetterAdvancements-1.12.2-0.1.0.77.jar         | None                                     |
	| LCHI  | bibliocraft             | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar              | None                                     |
	| LCHI  | biomesoplenty           | 7.0.1.2441               | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar  | None                                     |
	| LCHI  | bookshelf               | 2.3.590                  | Bookshelf-1.12.2-2.3.590.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHI  | brokenwings             | 2.0.0                    | brokenwings-3.0.0.jar                          | None                                     |
	| LCHI  | chameleon               | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                       | None                                     |
	| LCHI  | chickenchunks           | 2.4.2.74                 | ChickenChunks-1.12.2-2.4.2.74-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHI  | chickens                | 6.0.4                    | chickens-6.0.4.jar                             | None                                     |
	| LCHI  | chiselsandbits          | 14.33                    | chiselsandbits-14.33.jar                       | None                                     |
	| LCHI  | chococraft              | 0.9.9.0                  | chococraft_1.12.2-0.9.9.0.jar                  | None                                     |
	| LCHI  | geckolib3               | 3.0.0                    | geckolib-forge-1.12.2-3.0.0-beta.8.jar         | None                                     |
	| LCHI  | neid                    | 1.5.4.4                  | NotEnoughIDs-1.5.4.4.jar                       | None                                     |
	| LCHI  | phosphor-lighting       | 1.12.2-0.2.6             | phosphor-1.12.2-0.2.6+build50-universal.jar    | f0387d288626cc2d937daa504e74af570c52a2f1 |
	| LCHI  | cqrepoured              | 2.5.3B                   | Chocolate_Quest_Repoured-1.12.2-2.5.3B.jar     | None                                     |
	| LCHI  | conarm                  | 1.2.5.10                 | conarm-1.12.2-1.2.5.10.jar                     | b33d2c8df492beff56d1bbbc92da49b8ab7345a1 |
	| LCHI  | fastbench               | 1.7.3                    | FastWorkbench-1.12.2-1.7.3.jar                 | None                                     |
	| LCHI  | cyclicmagic             | 1.20.11                  | Cyclic-1.12.2-1.20.11.jar                      | 0e5cb559be7d03f3fc18b8cba547d663e25f28af |
	| LCHI  | dimdoors                | 1.12.2-3.1.2+UNOFFICIAL  | DimensionalDoors-1.12.2-3.1.2-UNOFFICIAL.jar   | None                                     |
	| LCHI  | dldungeonsjbg           | 1.14.8                   | DoomlikeDungeons-1.14.8-MC1.12.2.jar           | None                                     |
	| LCHI  | dungeonsmod             | @VERSION@                | DungeonsMod-1.12.2-1.0.8.jar                   | None                                     |
	| LCHI  | dungeontactics          | DT-0.16.9                | DungeonTactics-1.12.2-0.16.9.jar               | None                                     |
	| LCHI  | ebwizardry              | 4.3.4                    | ElectroblobsWizardry-4.3.4-MC1.12.2.jar        | None                                     |
	| LCHI  | eplus                   | 5.0.176                  | EnchantingPlus-1.12.2-5.0.176.jar              | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHI  | erebus                  | 1.0.32                   | Erebus-1.0.32.jar                              | None                                     |
	| LCHI  | fastfurnace             | 1.3.1                    | FastFurnace-1.12.2-1.3.1.jar                   | None                                     |
	| LCHI  | featuredservers         | 1.12-1.0.6               | FeaturedServers-1.12-1.0.6.jar                 | None                                     |
	| LCHI  | foamfix                 | 0.10.14-1.12.2           | foamfix-0.10.14-1.12.2.jar                     | None                                     |
	| LCHI  | forgelin                | 1.8.4                    | Forgelin-1.8.4.jar                             | None                                     |
	| LCHI  | futureminecraf          | 1.3.1                    | FutureVersions v1.3.1.jar                      | None                                     |
	| LCHI  | gottschcore             | 1.14.0                   | GottschCore-mc1.12.2-f14.23.5.2854-v1.14.0.jar | None                                     |
	| LCHI  | lucraftcore             | 1.12.2-2.4.16            | LucraftCore-1.12.2-2.4.16.jar                  | None                                     |
	| LCHI  | heroesexpansion         | 1.12.2-1.3.5             | HeroesExpansion-1.12.2-1.3.5.jar               | None                                     |
	| LCHI  | placebo                 | 1.6.0                    | Placebo-1.12.2-1.6.0.jar                       | None                                     |
	| LCHI  | hexxitgear              | 2.8.0                    | Hexxit Gear-1.12.2-2.8.0.jar                   | None                                     |
	| LCHI  | icbmclassic             | 1.12.2-4.0.1.75          | ICBM-classic-1.12.2-4.0.1b75.jar               | None                                     |
	| LCHI  | teslacorelib            | 1.0.18                   | tesla-core-lib-1.12.2-1.0.18.jar               | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHI  | industrialforegoing     | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.12.13-237.jar     | None                                     |
	| LCHI  | infernalmobs            | 1.7.6                    | InfernalMobs-1.12.2.jar                        | None                                     |
	| LCHI  | inventorypets           | 2.0.15                   | inventorypets-1.12-2.0.15.jar                  | None                                     |
	| LCHI  | inventorytweaks         | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                       | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHI  | ironchest               | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                | None                                     |
	| LCHI  | journeymap              | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                    | None                                     |
	| LCHI  | jrftl                   | 1.1                      | JRFTL[1.12.2]-1.1.jar                          | None                                     |
	| LCHI  | jeresources             | 0.9.2.60                 | JustEnoughResources-1.12.2-0.9.2.60.jar        | None                                     |
	| LCHI  | login_shield            | 1.12.2-6-g5654706        | Login_Shield-1.12.2-6-g5654706.jar             | None                                     |
	| LCHI  | lootbags                | 2.5.8.7                  | lootbags-2.5.8.7.jar                           | None                                     |
	| LCHI  | lost_aether             | 1.0.2                    | lost-aether-content-1.12.2-1.0.2.jar           | None                                     |
	| LCHI  | malisiscore             | 1.12.2-6.5.1-SNAPSHOT    | malisiscore-1.12.2-6.5.1.jar                   | None                                     |
	| LCHI  | malisisdoors            | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                  | None                                     |
	| LCHI  | malisisswitches         | 1.12.2-5.1.0             | malisisswitches-1.12.2-5.1.0.jar               | None                                     |
	| LCHI  | mclib                   | 2.3.5                    | mclib-2.3.5-1.12.2.jar                         | None                                     |
	| LCHI  | morebeautifulplates     | 1.12.2-1.1.4             | morebeautifulplates-1.12.2-1.1.4.jar           | None                                     |
	| LCHI  | morechickens            | 3.1.0                    | morechickens-1.12.2-3.1.0.jar                  | None                                     |
	| LCHI  | natura                  | 1.12.2-4.3.2.69          | natura-1.12.2-4.3.2.69.jar                     | None                                     |
	| LCHI  | netherportalfix         | 5.3.17                   | NetherPortalFix_1.12.1-5.3.17.jar              | None                                     |
	| LCHI  | recipehandler           | 0.13                     | NoMoreRecipeConflict-0.13(1.12.2).jar          | None                                     |
	| LCHI  | oretweaker              | 1.0.2-1.12.0             | Ore Tweaker-1.0.2-1.12.0.jar                   | None                                     |
	| LCHI  | patchouli               | 1.0-23.6                 | Patchouli-1.0-23.6.jar                         | None                                     |
	| LCHI  | performant              | 1.12.2-1.4               | performant-1.12.2-1.10.jar                     | None                                     |
	| LCHI  | reccomplex              | 1.4.8.2                  | RecurrentComplex-1.4.8.2.jar                   | None                                     |
	| LCHI  | xreliquary              | 1.12.2-1.3.4.796         | Reliquary-1.12.2-1.3.4.796.jar                 | None                                     |
	| LCHI  | roguelike               | 2.4.0                    | RoguelikeDungeonsFnarEdition-1.12.2-2.4.0.jar  | None                                     |
	| LCHI  | roost                   | 2.0.10                   | roost-1.12.2-2.0.10.jar                        | None                                     |
	| LCHI  | roughmobs               | 2.0.0                    | roughmobs2-1.12.2_2.0.15.jar                   | None                                     |
	| LCHI  | roughmobsrevamped       | 2.3.21                   | roughmobsrevamped-1.12.2-2.3.21.jar            | None                                     |
	| LCHI  | secretroomsmod          | 5.6.4                    | secretroomsmod-1.12.2-5.6.4.jar                | None                                     |
	| LCHI  | valkyrielib             | 1.12.2-2.0.20.1          | valkyrielib-1.12.2-2.0.20.1.jar                | None                                     |
	| LCHI  | simplegenerators        | 1.12.2-2.0.20.2          | simplegenerators-1.12.2-2.0.20.2.jar           | None                                     |
	| LCHI  | somanyenchantments      | 0.5.2                    | SoManyEnchantments-0.5.2.jar                   | None                                     |
	| LCHI  | soulshardsrespawn       | 1.12.2-1.1.1-13          | SoulShardsRespawn-1.12.2-1.1.1-13.jar          | None                                     |
	| LCHI  | spartanshields          | 1.5.4                    | SpartanShields-1.12.2-1.5.4.jar                | None                                     |
	| LCHI  | spartanweaponry         | beta 1.3.8               | SpartanWeaponry-1.12.2-beta-1.3.8.jar          | None                                     |
	| LCHI  | storagedrawers          | 5.2.2                    | StorageDrawers-1.12.2-5.4.2.jar                | None                                     |
	| LCHI  | surge                   | 2.0.77                   | Surge-1.12.2-2.0.77.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHI  | the-fifth-world         | 0.5                      | the-fifth-world-0.5.1.jar                      | None                                     |
	| LCHI  | theoneprobe             | 1.4.28                   | theoneprobe-1.12-1.4.28.jar                    | None                                     |
	| LCHI  | tcomplement             | 1.12.2-0.4.3             | TinkersComplement-1.12.2-0.4.3.jar             | None                                     |
	| LCHI  | toastcontrol            | 1.8.1                    | Toast Control-1.12.2-1.8.1.jar                 | None                                     |
	| LCHI  | tombmanygraves          | 1.12-4.2.0               | TombManyGraves-1.12-4.2.0.jar                  | None                                     |
	| LCHI  | tm                      | 1.0                      | Transformers+Unlimited+1.1.2.jar               | None                                     |
	| LCHI  | treechopper             | 1.2.4                    | TreeChopper-1.12.2-1.2.4.jar                   | None                                     |
	| LCHI  | uniquebase              | 1.0.0                    | Unique Enchantments Base-1.12.2-1.0.0.jar      | None                                     |
	| LCHI  | uniquee                 | 2.0.0                    | Unique Enchantments-1.12.2-2.1.0.jar           | None                                     |
	| LCHI  | unloader                | 1.2.0                    | unloader-1.2.0.jar                             | None                                     |
	| LCHI  | universalmodifiers      | 1.12.2-1.0.16.1          | valkyrielib-1.12.2-2.0.20.1.jar                | None                                     |
	| LCHI  | waddles                 | 0.6.0                    | Waddles-1.12.2-0.6.0.jar                       | None                                     |
	| LCHI  | wearablebackpacks       | 3.1.4                    | WearableBackpacks-1.12.2-3.1.4.jar             | None                                     |
	| LCHI  | worleycaves             | 1.5.2                    | worleycaves-1.12.2-1.5.2.jar                   | None                                     |
	| LCHI  | betteranimalsplus       | 9.0.1                    | betteranimalsplus-1.12.2-9.0.1.jar             | None                                     |
	| LCHI  | orelib                  | 3.6.0.1                  | OreLib-1.12.2-3.6.0.1.jar                      | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHI  | thebetweenlands         | 3.7.3                    | TheBetweenlands-3.7.3-universal.jar            | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| LCHI  | teslacorelib_registries | 1.0.18                   | tesla-core-lib-1.12.2-1.0.18.jar               | None                                     |
	| UD    | mclib_core              | 2.3.5                    | minecraft.jar                                  | None                                     |

	Loaded coremods (and transformers): 
MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  
RandomPatches (randompatches-1.12.2-1.22.1.10.jar)
  com.therandomlabs.randompatches.core.RPTransformer
CorePlugin (SmoothFont-mc1.12.2-2.1.2.jar)
  bre.smoothfont.asm.Transformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
PerformantLoadingPlugin (performant-1.12.2-1.10.jar)
  
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
Born in a Barn (Born In A Barn V1.8-1.12-1.1.jar)
  com.chocohead.biab.BornInABarn
Plugin (NotEnoughIDs-1.5.4.4.jar)
  ru.fewizz.neid.asm.Transformer
McLib core mod (mclib-2.3.5-1.12.2.jar)
  mchorse.mclib.core.McLibCMClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.7.3-SNAPSHOT-20210323.072210-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  
LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.16.jar)
  lucraft.mods.lucraftcore.core.LCTransformer
SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  com.wynprice.secretroomsmod.core.SecretRoomsTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
  
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 27.20.100.8681' Renderer: 'Intel(R) Iris(R) Plus Graphics'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)
		- quarkIntegration (Enabled/Not Forced)

	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Pulsar/tcomplement loaded Pulses: 
		- ModuleCommons (Enabled/Forced)
		- ModuleMelter (Enabled/Not Forced)
		- ModuleArmor (Enabled/Not Forced)
		- ModuleSteelworks (Enabled/Not Forced)
		- ChiselPlugin (Enabled/Not Forced)
		- Oredict (Enabled/Forced)

	Patchouli open book context: n/a

**Comment by mindforger** [comment]
Take a look at the following line, the issue is in your configs :)

> Caused by: java.lang.IllegalArgumentException: Failed to register dimension for id 2, One is already registered
