### ISSUE TITLE
Improve portable cells on 1.7.10

### ISSUE THREAD

**Issue by Oxas95** [AppliedEnergistics/Applied-Energistics-2#5433]
As for this problem (https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4643) that was solved on a more recent version of minecraft, would it be possible to add larger portable cells to version 1.7.10 of minecraft?

I tried to do it myself, but I couldn't do a rebuild of the mod, there would be a problem with dependencies. I tried to solve it but I couldn't. So I ask you to do it.

Can you add these elements? Or at least publish a version of sources that fixes the dependency problem (maven)?

Thanking you in advance

**Comment by shartte** [comment]
Sorry, we currently do not support any version older than Minecraft 1.16 anymore.

**Comment by Myridium** [comment]
Hi, can you please clarify what is the latest version available for 1.7.10? The changelogs are not explicit about when the target version changes. The changelog does not mention updating the forge version beyond 1.7.10 until after rv4.alpha.8. But the forge website shows rv3.alpha.6 as the latest version. The FAQ on the AE2 website says only 1.7.10 is required for AE2, and the website is generally out of date. There is conflicting information and it's hard to tell what the actual version requirements are for this mod's various releases.
