### ISSUE TITLE
Duplicated craft request [1.16.5]

### ISSUE THREAD

**Issue by Raft08** [AppliedEnergistics/Applied-Energistics-2#5435]
Hello
I play with my friend on a server

The bug

When i do a craft request it duplicated the rquest

How to reproduce

I play with a modpack and teh applied add-ons are :

LazierAE2
AE2 Extras
Advanced Peripherals

On a server (I don't have test that on single player)
And just make a craft request

What was expected

That it craft redstone

Screens :
![bugAE](https://user-images.githubusercontent.com/72615320/134030867-abf7c82a-0c65-4c73-a056-34067e294798.gif)
**Environment**

- Environment: 
Minecraft Server 1.16.5 Mohist
The modpack: (CurseForge app)
[Tech_of_Craft-Do_not_update_MODS.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/7196873/Tech_of_Craft-Do_not_update_MODS.zip)t

**Comment by Technici4n** [comment]
> LazierAE2

We don't support this mod, report to them.
