### ISSUE TITLE
Wireless booster extension / modification

### ISSUE THREAD

**Issue by Remo41997** [AppliedEnergistics/Applied-Energistics-2#5438]
Adds an infinite wireless booster, which is very expensive to manufacture, or adds more range to the current wireless booster e.g. 1000 blocks

- from Remo41997

**Comment by yueh** [comment]
QNB already has an infinite range.

**Comment by ruifung** [comment]
But isn't the QNB for site-to-site vs the wireless AP which is for the wireless terminals?
