### ISSUE TITLE
Input recipe from JEI IllegalArgumentException: null

### ISSUE THREAD

**Issue by Diversion98** [AppliedEnergistics/Applied-Energistics-2#5445]
**Describe the bug**
When looking at a recipe in JEI and try to input it in the crafting terminal with the plus button, the crafting terminal stays empty.

**To Reproduce**
1. Put 9 or more gold ingots into the ME system.
2. Look up Gold Block in JEI
3. Click the plus button
4. Error

**Expected behavior**
Crafting recipe should be inputted when u click the plus button when looking at a recipe in JEI

**Environment**
The error when u try to input the recipe: https://pastebin.com/VtCRAbu3
Forced Crash: https://pastebin.com/mxwFKgPk

Modpack + version: The MHG Modpack 0.1.3-Hotfix (I will try to minimize the mods, dont have the time right now, sorry!)
AE2 version 8.4.1
Crafttweaker, itemstages, recipestages are involved in the pack

CPU: Ryzen 5600x
RAM: 16GB Ram
GPU: GTX 1070
Storage: Samsung 980 Pro NVMe
OS: Windows 10, 64 Bit

https://github.com/Diversion98/The-MHG-Modpack/issues/3

More details coming soon.

**Comment by yueh** [comment]
If the stacktrace is correct, it indicates that we could not look up the recipe itself in the context of the current player.

As you mention there are stages involved, the most likely case is that they introduce a discrepancy between the actual recipes and what is shown to the player. Best course of action would probably be to stop showing unknown recipes to players.
We really need to be able to access the recipe as otherwise the data provided by JEI can be too much and crash the server with it.

**Comment by Diversion98** [comment]
Its allready coded in that if a player doesn't have the stage, the items are hidden in JEI.

Also for testing purposes, i gave all stages in the pack to myself and still had this issue.

I think it was working before, I'll test tomorow with a previous version of the pack and I'll give u feedback

**Comment by yueh** [comment]
No idea really. All I can say is that we don't get a valid recipes for some reason. The most obvious problem is that some stage mod will break it. Another one could be a invalid recipe id (or custom recipe). While a valid one is a requirement on our side is a requirement to prevent other crashes.

**Comment by Diversion98** [comment]
Okay this just got weirder now :/

So I minimized the modlist to test with only stages and ae2.
And suddenly it works :/
The stages are the same and I put in the script to hide things in JEI and make them unusable when the stage is not met.
I gave myself all the stages and it was working :/
Need to look into it more because this wont help u I think xd

by the way, forge: 36.2.2

modlist:

- Applied Energistics 2 8.4.1
- AppliedEnergisticsTweaker 1.0.0.15
- Bookshelf 10.2.27
- CraftTweaker 7.1.2.435
- Game Stages 7.3.10
- Item Stages 3.0.6
- JEITweaker 1.0.1.35
- JEI 7.7.1.121
- Recipe Stages 2.0.0.20

**Comment by Diversion98** [comment]
Found the issue.

Because im using item stages now instead of recipe stages, my unstage method from recipe stages was conflicting (weird but ok)
Thanks for your replies and sorry for bothering u guys :)

cheers
