### ISSUE TITLE
Quick drag from inventory

### ISSUE THREAD

**Issue by imcasper** [AppliedEnergistics/Applied-Energistics-2#5446]
### Describe the feature

Using [shift+LMB] will help you quickly pick up items and stacks of items from the network into your inventory. 

### Reasons why it should be considered

I have a mod that does this. Manual dragging is now very tedious. 

### Additional details

It's all about the convenience of the interface. In the vast majority of cases, the action is obvious, but the default game forces us to specify the goal (although there is only one possible goal!)

**Comment by yueh** [comment]
Shift + left click will already move a the whole itemstack into the network or player inventory directly.
If this does not work, then most likely your mod adding it again is breaking it in our UI and should be reported to them.
