### ISSUE TITLE
Add setting for the pattern provider to push out a single task across all sides

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#5451]
Most notably for machines which cannot accept items and fluids from the same side. While this usually can be solved with a subnetwork, we should still allow the player to pick a different transport mod without requiring some intermediate block, which can store everything.

By default off and only the choice between push everything on one side or try it on all sides.
This cannot reuse the directional setting as pushing out a complete pattern to each of the attached machines is still a valid case.

**Comment by Technici4n** [comment]
I think that having the choice between using a subnetwork and requiring another mod is fine.
