### ISSUE TITLE
Unable to create a manual processing recipe

### ISSUE THREAD

**Issue by FeedTheChunk** [AppliedEnergistics/Applied-Energistics-2#5454]
### Describe the bug

Unable to create a manual processing recipe.  I am trying to create a processing recipe that returns 4 non stackable items, potions in the case.  I can only add 3 outputs to the recipe when the recipe returns 4 potions.

![image](https://user-images.githubusercontent.com/35508630/135559922-0d709137-2747-443d-bc37-a96609f66f89.png)

There doesn't seem to be a way, that I can find anyway, on setting the number of returns items.  I thought that I remember there being a way in older versions, something like shift+scrolling maybe?  I have tried many different key / mouse combinations and am unable to change the number of items.

### How to reproduce the bug

Create a new pattern in the Pattern Terminal and attempt to add more than 3 returned non stackable items from the craft.

### Expected behavior

I would hope that there is a way that the user could somehow select how many items are returned from a customer / manual processing pattern craft.

### Which minecraft version are you using?

1.16

### On which mod loaders does it happen?

Forge

### Crash log

.

**Comment by yueh** [comment]
Right clicking with an item does place down a single one and each consecutive click would increase it by 1 up to the max stack size, which in this case hower is 1.

1.16 is in feature freeze now, so there won't be any changes for it. We might look into it again for 1.17 or 1.18, but there are currently more important things do finish first.

**Comment by FeedTheChunk** [comment]
Thanks for the feedback.

**Comment by Technici4n** [comment]
Closing in favor of #5866. (Soon)
