### ISSUE TITLE
fluix crytal doesnt crafting

### ISSUE THREAD

**Issue by lyricsdev** [AppliedEnergistics/Applied-Energistics-2#5455]
### Describe the bug

we are playing on fabric 1.16.5 and fluix crystal doesnt crafting when we are droping entites

### How to reproduce the bug

we are playing on fabric 1.16.5 and fluix crystal doesnt crafting when we are droping entites

### Expected behavior

we are playing on fabric 1.16.5 and fluix crystal doesnt crafting when we are droping entites

### Additional details

we are playing on fabric 1.16.5 and fluix crystal doesnt crafting when we are droping entites

### Which minecraft version are you using?

1.16

### On which mod loaders does it happen?

Fabric

### Crash log

nah

**Comment by Technici4n** [comment]
Are you sure you are dropping charged certus quartz, redstone and nether quartz in the water? Please post pictures of your setup.

**Comment by lyricsdev** [comment]
yea i'm sure it make a lights a full time but we was waiting it for 10 minutes but only purple lights

**Comment by Technici4n** [comment]
Video please?

**Comment by lyricsdev** [comment]
on server it doesnt work but in singleplayer it works pretty good 1 moment 
![изображение](https://user-images.githubusercontent.com/77627599/135760452-276a0e5f-a5a8-43e1-aa00-cb548ecceb8f.png)

**Comment by lyricsdev** [comment]
@Technici4n yea it works i downgraded on alpha.1 version but textures doesnt show up

**Comment by Mari023** [comment]
for the textures not showing: are you using sodium? (or iris, I think it may bundle sodium)
if yes, using indium should fix the rendering issue.

**Comment by lyricsdev** [comment]
i'm using a iris and sodium for shaders 
indium should fix this problem right

**Comment by Mari023** [comment]
> indium should fix this problem right
yes
