### ISSUE TITLE
no meteorites in 1.17.1

### ISSUE THREAD

**Issue by Chuunkyz** [AppliedEnergistics/Applied-Energistics-2#5462]
### Describe the bug

everything is in the title

### How to reproduce the bug

use the 1.17.1 version and that's all

### Expected behavior

meteorites

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

nope

**Comment by Mari023** [comment]
Interestingly I could find a meteorite
but that was on an earlier version I compiled myself (and naturally I neither now the commit nor do I still have the file)

**Comment by Mari023** [comment]
can you post the seed?
I just opened a new world and the first thing I saw was a meteorite:
![2021-10-03_23 29 29](https://user-images.githubusercontent.com/38946771/135772168-0d04c945-22f6-4831-93b5-e3e5c2dd6de4.png)

**Comment by shartte** [comment]
Yeah, please post the world-seed you used because I can also find meteorites in 1.17.1 Fabric.

**Comment by Chuunkyz** [comment]
mmh
i'm using the official mojang datapack
is that the reason of this ?

**Comment by Chuunkyz** [comment]
nvm, that's the datapack
