### ISSUE TITLE
[Crash on 1.17.1] REI Crash on AE2 Search

### ISSUE THREAD

**Issue by red2blue** [AppliedEnergistics/Applied-Energistics-2#5465]
### Describe the bug

On Another Quality Modpack 2, added the AE2 in a beta version. Opened REI and searched "@applied ore" and the game immediately crashed.

### How to reproduce the bug

Open REI

Search "@applied ore"

Crash

### Expected behavior

REI displaying applied energistics 2 ore

### Additional details

Whats weird is that Latest.log showed something completely different than the crash report. I assume the latest.log is the real reason why it crashed, and crash report is the mod that made it crash. 

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/ZC61Rjye (latest.log showed this when crashed) and crash report is different https://pastebin.com/U3sFtbxJ

**Comment by Technici4n** [comment]
Can't reproduce with AE2 and REI alone, must be a bug in another one of your mods.

![image](https://user-images.githubusercontent.com/13494793/135999067-b24fa1d0-fc36-4664-b6f6-4f52b76e3fde.png)

**Comment by red2blue** [comment]
Apologies. it was apparently Indrev alpha.5 that caused this REI issue for my modpack
