### ISSUE TITLE
Interfaces in fabric 1.17 do not have pattern slots

### ISSUE THREAD

**Issue by coolsa** [AppliedEnergistics/Applied-Energistics-2#5479]
### Describe the bug

Compiling from the most recent commit in fabric/1.17, the interface block has no slots to input crafting patterns.

![image](https://user-images.githubusercontent.com/1697614/136125242-30863e6c-d44f-4271-9e15-eef36bebf633.png)

### How to reproduce the bug

Place down an ME interface, and right click to open. The inventory for stored items appears, but the slots for patterns does not.

### Expected behavior

The interface would normally have slots to place crafting patterns in, to interact with certain blocks.

### Additional details

Tested on most recent commit and with local merged p2p-outer-node-in-world and fix-controller-init branches.

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

https://gist.github.com/coolsa/84fe9afc413434bd7b5f20b1baffdaee

**Comment by ruifung** [comment]
Pretty sure this isn't a bug and it's been moved to a "Crafting Interface" in https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/5428

**Comment by coolsa** [comment]
> Pretty sure this isn't a bug and it's been moved to a "Crafting Interface" in #5428

Ahh, I see it now: its called a "pattern provider."
I didn't see it until you linked that PR, closing this issue now. Thank you!
