### ISSUE TITLE
Interfaces under a storage bus should prevent insertion via the network when it would exceed the configured amount.

### ISSUE THREAD

**Issue by Technici4n** [AppliedEnergistics/Applied-Energistics-2#5482]
Otherwise, the item is injected into the interface, and then the interface has to insert it back into the network somehow. If this second insertion succeeds, the interface's item handler adapter only updates the next tick, causing duplicate items to be shown for a moment.

**Comment by Technici4n** [comment]
It looks similar from the outside (an ignored filter), but it really is the fault of the block (interface or DSU) for not properly implementing its filtering. So in this case it's our fault. :smile:

**Comment by mindforger** [comment]
sounds like an preprogrammed ticklag for improper formed/overloaded networks to me, can't you buffer the item before actually reporting it back (or something like hiding it from the network for the tick until the next update like you described in the OP)

**Comment by mindforger** [comment]
now that i think of it, doesn't the "old" interface have input slots that buffered back?

**Comment by Technici4n** [comment]
Addressed either by an earlier commit or by #5789, at least I can't reproduce it from the PR.
