### ISSUE TITLE
Yabba Barrels & AE

### ISSUE THREAD

**Issue by Quest79** [AppliedEnergistics/Applied-Energistics-2#5493]
### Describe the bug

I have Yabba barrels with infinity upgrades storing most of my items.
I have Dense Energy Cells providing power
I have plenty of CPU and whatnot to do the example auto-craft (see image)

I understand that Storage Drawers suffers from some 1-stack-only issue where if AE needs more than 1 stack of an item, crafts fail. Just yesterday I crafted a batch of **10 Enhanced Alloy Smelters (Ender IO**), and I cannot believe I had all the mats for 10 of them without AE needing to pull more than a stack of something out of my Yabba system (i took everything out of my AE system and put it into yabba too so no loose stacks were in any drives)

Please tell me Yabba doesnt suffer from this horrible 1-stack limitation too? Is there anything developers can do on their end or is this a Minecraft issue? I can go ask for a feature/bug request at Yabba but im not sure what the issue is exactly and who can help.

Thanks. 
<img width="604" alt="javaw 100921 083642 1208x1045" src="https://user-images.githubusercontent.com/635094/136665245-1c704328-972b-49e2-bbcb-fc4129d1986d.png">

### How to reproduce the bug

Place items in yabba barrales

Try to craft things that need more than 1 stack

### Expected behavior

Craft to start.

### Which minecraft version are you using?

1.12 - UNSUPPORTED

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/Quest79/cd5faffa94a6526a5381f79791000c51

**Comment by Technici4n** [comment]
> 1.12 - UNSUPPORTED

We don't support 1.12 anymore, sorry.

> Please tell me Yabba doesnt suffer from this horrible 1-stack limitation too? Is there anything developers can do on their end or is this a Minecraft issue?

This is pretty much a forge `IItemHandler` issue.
