### ISSUE TITLE
ComputerCraft Integration?

### ISSUE THREAD

**Issue by AlgorithmX2** [AppliedEnergistics/Applied-Energistics-2#55]
The ME Interface, or a new block added to AE2, could interact with the computer, allowing for the enabling/disabling of channels, cables, and such. As well as increased security, which could interact with a security station of some kind.

Such as, a CC program that reads interactions with the ME system by player name and time past, in minutes and seconds. The computer could output to a monitor, and when the program runs, it logs every event that occurs within the connected network.

The printed message could look something like this:
                 DatJoshKid opened ME Terminal 5 minutes ago

This would allow more careful monitoring of the ME system, and also power management if used by a clever program. I don't know if this is something on your side or CC's.

Originally Posted by DatJoshKid

This issue was migrated; For original details see http://ae-mod.info/Tracker/0526/

**Comment by mskurnik** [comment]
With the addition of a OpenComputers P2P port in RV3, have you guys re evaluated if ComputerCraft has the appropriate API support to create a ComputerCraft P2P port?

**Comment by XFactHD** [comment]
CC P2P is impossible because CC's API  doesn't offer interfaces to cables or cable-like connections.

**Comment by mskurnik** [comment]
I thought mods like redpower had bundled cables that allowed 16 channels to transfer similar to MFRs RedNet (which no longer can be used as a CC RedNet cable).

**Comment by XFactHD** [comment]
The rednet cable from MFR is a redstone cable with 16 channels. The bundled cable from RedPower is a redstone wire too, as is the bundled cable from Project:Red. The RedNet cable from CC is a networking cable solely for use with computers and components.

**Comment by mskurnik** [comment]
Sorry, I was sleep deprived when I wrote that.  I mean a P2P modem port that is literally a one-to-one connection.

**Comment by XFactHD** [comment]
If I understand you correctly then that is again a connection between two CC cables, which is, as I said, impossible.

**Comment by mskurnik** [comment]
[CCTweaks](https://github.com/SquidDev-CC/CC-Tweaks) adds network extensions including a cross dimensional bridge. Couldn't something like that be done for P2P port?  Since CCTweaks adds a new modem block that acts just like a regular modem but with 6 inputs, couldn't a P2P port be made with similar code?  It seems to me that the API access exists.

**Comment by XFactHD** [comment]
They are using internal classes which is not recommended because it can break in an update of the parent mod.
