### ISSUE TITLE
1.17.1 observation/bugs

### ISSUE THREAD

**Issue by MUHAKLorTheDorfTrottel4Github** [AppliedEnergistics/Applied-Energistics-2#5502]
### Describe the bug

appliedenergistics2-9.0.0-alpha.1.jar
fabric-api-0.40.1+1.17.jar
TechReborn-5.0.6-beta+build.94.jar
RoughlyEnoughItems-6.0.285-alpha-fabric.jar
===========================================
1- Tech reborn GRINDER always active
2- cannot drop seeds to puddle/ground
3- crafting terminal don't get recipe
4- storage monitor don't show amount
5- SMART DENSE CALE only accept 29 channels 
6- INSCRIBER "eats" press
7- ENERGY ACCEPTOR dont accept "E" from TECH REBORN
8- WIRELESS RECEIVER useless
regards
daniel

### How to reproduce the bug

bla bla

### Expected behavior

 bla bla

### Additional details

 bla bla

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

bla bla

**Comment by shartte** [comment]
Most of these are duplicates of previous reports.
Please check if any issues persist after the release of 9.0.0-alpha.2 (soonish)

**Comment by Technici4n** [comment]
If you open another issue, please open a new issue that follows the template. I understand that it will take you 5 more minutes to explain how to reproduce or post relevant screenshots, but fixing a single one of these bugs takes much longer for us, especially if you don't follow the template.

You can look at #5492 for an example of a high-quality report.
