### ISSUE TITLE
1.16.5 Spam log

### ISSUE THREAD

**Issue by szumaster** [AppliedEnergistics/Applied-Energistics-2#5506]
### Describe the bug

Spam + missing textures. Without sodium / indium / mom spaghetti / iris / canvas ,

### How to reproduce the bug

run appliedenergistics2-fabric-8.4.0-alpha.2

### Expected behavior

Solution

### Additional details

real size of spam: 749 KB (767,519 bytes

### Which minecraft version are you using?

1.16

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/yxupGNyA

**Comment by shartte** [comment]
Should be fixed in 8.4.0-alpha.3
