### ISSUE TITLE
9.0.0-alpha.2 v1.17.1 "Tab" Hotkey Not available

### ISSUE THREAD

**Issue by shuohua2000** [AppliedEnergistics/Applied-Energistics-2#5510]
### Describe the bug

After entering the game, the "Tab" hotkey bound to other mods cannot be used and needs to be bound again. However, once you completely exit the game, the "Tab" hotkey becomes invalid when you enter the game again.
It has been tested that it is not a problem with other Mods, because binding the "Tab" hotkey to any Mod function will fail. Only deleting AE2 will solve the problem.

### How to reproduce the bug

Bind the "Tab" hotkey to any other mod function, then exit the game and enter again. The "Tab" hotkey will no longer work.

### Expected behavior

Please fix it, thank you!

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

No crash log, not really a crash.

**Comment by Technici4n** [comment]
Fixed by #5753.
