### ISSUE TITLE
Pattern Terminal Crash 

### ISSUE THREAD

**Issue by Mari023** [AppliedEnergistics/Applied-Energistics-2#5512]
### Describe the bug

The pattern Terminal crashes when it is switched to processing mode / opened when in processing mode

### How to reproduce the bug

switch pattern terminal to processing mode

### Expected behavior

It shouldn't crash

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

https://gist.github.com/Mari023/bd7ef487c7f6c36c4146232bd6a4d584

**Comment by shartte** [comment]
How did this happen :-|
I tried this locally. I might have to update the fabric-api version in dev.
