### ISSUE TITLE
Wireless Terminal Drops When Removed From Security Terminal

### ISSUE THREAD

**Issue by SadBluez** [AppliedEnergistics/Applied-Energistics-2#5533]
### Describe the bug

_deja vu?_

When trying to link a wireless terminal in a **Security Terminal**, once the wireless terminal is linked by security terminal, removing the wireless terminal from the security terminal will instantly drop the linked wireless terminal.
![image](https://user-images.githubusercontent.com/54856793/137048024-88f35311-c5ec-41e4-b89b-78bd7e3676ed.png)

### How to reproduce the bug

Link a wireless terminal with a security terminal and remove the linked wireless terminal from the security terminal.

### Expected behavior

Not drop.

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/k7Vhiaf1

**Comment by Technici4n** [comment]
Fixed by #5550.
