### ISSUE TITLE
REI hotkeys cannot be used after searchbar was focused, even if it isn't focused anymore

### ISSUE THREAD

**Issue by Mari023** [AppliedEnergistics/Applied-Energistics-2#5535]
### Describe the bug

REI hotkeys like show recipe, show usage or favorite entry don't work if the Search Box Mode is any AUTO mode
Non-AUTO modes work fine, even when the search bar is focused

### How to reproduce the bug

set the Search Box Mode to any AUTO mode
press a key bound to a REI Keybinding
nothing happens

### Expected behavior

REI hotkeys to do their function in AUTO mode too

### Which minecraft version are you using?

1.17, 1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://gist.github.com/Mari023/b54b93ddc203fc09c13091bec7ec7d59

**Comment by shartte** [comment]
I am not super sure this can actually be fixed since we don't know what the REI hotkeys actually are.

**Comment by Mari023** [comment]
I think it did work in 1.16, it certainly did work at some point.

It also blocks them when manually removing the focus from the search (by clicking somewhere else).

I tried non-auto settings, and it seems that REI hotkeys only work until the first time the search field is focused

**Comment by shartte** [comment]
But you mean in Auto-Focus mode only, right? It's a bit of a problem design-wise because I believe REI doesn't hook into the onKey mechanics early enough to prevent us from even receiving the event. I'd have to look into that, honestly.

**Comment by Mari023** [comment]
even in non autofocus mode, it breaks after focusing once (but it works before the first focus)

**Comment by Technici4n** [comment]
Should be fixed now I hope (haven't checked but REI had changes in that area to fix these issues).
