### ISSUE TITLE
Will AE2 be made to be used with forge as well as fabric?

### ISSUE THREAD

**Issue by Agamemnon128** [AppliedEnergistics/Applied-Energistics-2#5544]
### Describe the feature

Sorry, wasnt a bug, so didnt seem like a good place to ask

### Reasons why it should be considered

I really like using the mod in minecraft

**Comment by shartte** [comment]
Forge on 1.17 is a shitshow. The build generally works, but we're waiting on Forge to fix their stuff before we make an actual release.
In the meantime we're working on new features on Fabric and keep both versions in sync.
