### ISSUE TITLE
Amethyst Shard to Fluix Crystal

### ISSUE THREAD

**Issue by lilrichy** [AppliedEnergistics/Applied-Energistics-2#5545]
### Describe the feature

Just an idea of a way to use amethyst shards = Put in charger to make Fluix crystal same way you put certus quartz crystal into charger to make charged certus quartz crystal.

### Reasons why it should be considered

Gives an alternative way to get Fluix crystal and a use for the new amethyst shards since you replaced there use with copper ingots.

**Comment by Technici4n** [comment]
Note that amethyst is incredibly hard to find (1/53 chance of a geode generating in a chunk).

**Comment by lilrichy** [comment]
Yes this was just an idea for an alternative recipe not a replacement for the seed.

**Comment by Technici4n** [comment]
Probably not gonna happen. Amethyst is too rare, yet potentially too easy to replicate (given other mods), to be balanced correctly. But we have another plan to make early game a bit less boring.
