### ISSUE TITLE
Error when looking through storage system [alpha4]

### ISSUE THREAD

**Issue by red2blue** [AppliedEnergistics/Applied-Energistics-2#5552]
### Describe the bug

A player was going through storage system, and a error popped up in console on dedicated server

There was no crash involved. Figured I might as well report this just in case there is something off. 

### How to reproduce the bug

Not sure, just saw the error.

### Expected behavior

not sure, just saw the error.

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/xmKgkD2b

**Comment by shartte** [comment]
> at net.minecraft.class_1735.handler$znl000$ledgerGetInitialStack(class_1735.java:1056) ~[intermediary-server.jar:?]

You didn't provide a full crashlog that includes a modlist, I'll just take a guess that this is from a mod called "ledger" (?) that injects itseif into our inscriber GUI. Sorry, but you gotta report that to them.

**Comment by red2blue** [comment]
You are correct. will do.

**Comment by PotatoPresident** [comment]
Just thought I'd mention for anyone that finds this that this has been fixed in dev for a while. New release should be soon, but until then you can grab the [latest actions build](https://github.com/QuiltServerTools/Ledger/actions?query=branch%3Amaster).
