### ISSUE TITLE
Meteorites not spawning

### ISSUE THREAD

**Issue by red2blue** [AppliedEnergistics/Applied-Energistics-2#5553]
### Describe the bug

Meteorites are not spawning at all. I am using Terralith mod(datapack) for vanilla biome creation. Though terralith has their own 'vanilla' biomes, regular Minecraft biomes still spawn, which I would imagine Meteorites should be generated in at the very least, as saplings, modded ore, and structures do. structures also spawn in terralith biomes. Not sure why Meteorites are not. 

Modlist is attached in pastebin. 

### How to reproduce the bug

Another Quality Modpack 2 -- 

Load into game
locate meteorite 
not available 

### Expected behavior

Meteorites generating

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/BD6M4def

**Comment by shartte** [comment]
Sorry, but there's not a whole lot to say, other than you might want to report this to Fabric.
We just register our structure with all overworld biomes, and if that fails with modded biomes, there's nothing we can do about it.

**Comment by red2blue** [comment]
@Technici4n I must report that Meteorites stopped spawning. It worked after the fix, but then I checked the other day as I was curious and wanted to visit one, and got the message from `/locate` that it could not be found.
