### ISSUE TITLE
floating water generated in meteorite pools

### ISSUE THREAD

**Issue by urmet** [AppliedEnergistics/Applied-Energistics-2#5574]
### Describe the bug

Running alpha.5 on fabric, I frequently noticed mobs swimming in the meteorite pool next to our base and creepers sneaking up to us all the time despite all the ground being lit up. Then when taking a swim with light overlay turned on, I noticed spawning spaces at the bottom. Turned out that there was a cave system under the meteorite and water didn't flow down into it, letting mobs spawn and then swim up, causing trouble.

### How to reproduce the bug

Have a meteorite generate on top of some caves

### Expected behavior

Water flows into the cave, not letting hordes of mobs spawn

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

none

**Comment by Technici4n** [comment]
Sorry, this issue is too old for us to reproduce it. If this happens again in 1.20 please open a new issue.
