### ISSUE TITLE
Performance issues with energy acceptors and complicated piles of tiny networks

### ISSUE THREAD

**Issue by seebs** [AppliedEnergistics/Applied-Energistics-2#558]
This behavior seems to have changed a lot with alpha29, but it's still acting badly in some ways. I first noticed it on rv2-alpha17.

Reproducer: Make a large pile of tiny tiny networks with power generation. Say, a grid of smart cable of different colors, with illuminated panels, joined by quartz fibers.

Attach energy acceptor.

Attach a power source.

In alpha17, this is fine as long as the power source is an AE2 vibration generator, but any other mod power source I tried produced horrible tick rate problems. (On a core i7 desktop, tick time went from 15ms to 55ms.) These were alleviated if there was an energy cell that could accept all the power the other mod could provide.

In alpha29, I got about 19ms tick time with no external power source or a low-energy cell, and about 30ms with a full energy cell. I can't reproduce this now because something went horribly wrong with my world save and it went to tick times >150ms regardless. Gonna see if I can make a better reproducer.

**Comment by Eufranio** [comment]
News?

**Comment by Eufranio** [comment]
Is there a temporary solution, workaround for this? I can't delete all AE2 stuff from the world, players will get mad...
