### ISSUE TITLE
Item Exporter causes lag

### ISSUE THREAD

**Issue by MCaesar** [AppliedEnergistics/Applied-Energistics-2#5584]
### Describe the bug

Noticed especially when exporting a large quantity of items. First noticed when exporting roughly 20-30k end stone into a quantum storage unit from Tech Reborn. It seems the exporter start out slow, then ramps up its speed over time (confirmed in AE2 discord as better for server performance). If there's a cap on the speed, the cap is too high, otherwise it's ramping up to a speed the game can't handle. As soon as the exporter is disconnected the lag immediately stops.
The lag seemed to be worse with 4 accelerator cards, presumably because it reaches untenable speeds faster, but still noticed the lag on an exporter without any cards, although not as extreme.

### How to reproduce the bug

Allow an item exporter to run continuously, the longer it runs the worse the lag gets.

### Expected behavior

No lag to be caused by the exporting of items, regardless of how long it runs.

### Additional details

Tech reborn quantum storage was a good way to notice the problem, as it allowed for a long period of continuous transfer. Disconnected exporter because of the lag, didn't let it get to the point of crashing, so unsure if it would get that extreme.

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/hayD2dTk

**Comment by shartte** [comment]
To summarize: We think this is not *actual* lag. It's the ME terminal being broken by your network inventory rebuilding each tick (due to another bug). The symptom in this case would be: you try to pick up an item from the network and nothing happens.

We'll fix item pickup being broken in the next release, while fixing the inventory being rebuilt each tick later.
