### ISSUE TITLE
Make control/informational machines not require channels

### ISSUE THREAD

**Issue by shartte** [AppliedEnergistics/Applied-Energistics-2#5616]
This might already be the case but should be formalized:

The only machines that should require channels should be ones that convert energy to/from items, or that conduct it (P2P, Spatial, etc.)

This would mean the following parts should *not* require channels:
- All Level Emitters
- Storage Monitor (Conversion Monitor should, since it can output items)

**Comment by shartte** [comment]
@Technici4n What do you think about this?

**Comment by Technici4n** [comment]
Ok to make level emitters and storage monitors not require channels. 👍

**Comment by Technici4n** [comment]
@mindforger I closed it because I merged PR #5616. Is there something you would like to add?

**Comment by mindforger** [comment]
No, i am terribly sorry, i must have accidentially reopened it while reading on my phone

**Comment by Technici4n** [comment]
No worries :)
