### ISSUE TITLE
Storage Bus Item Glitch with other Storages 

### ISSUE THREAD

**Issue by Lice2** [AppliedEnergistics/Applied-Energistics-2#5624]
### Describe the bug

We use stick pills, thanks to Storage.
And when the storage bus is on the barrels, you can double and multiply the items by getting out and in. 

### How to reproduce the bug

Make storage bus to the barrels 

### Expected behavior

We use stick pills, thanks to Storage.
And when the storage bus is on the barrels, you can double and multiply the items by getting out and in. 

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

none

**Comment by Technici4n** [comment]
From which mod are the barrels?

**Comment by Technici4n** [comment]
@Lice2 without this information, this will be impossible to debug. I have no clue what "stick pills" is supposed to mean.

**Comment by Lice2** [comment]
Hi i mean Stockpile
https://www.curseforge.com/minecraft/mc-mods/stockpile
and Dankstorage
https://www.curseforge.com/minecraft/mc-mods/dank-storage-fabric

**Comment by Technici4n** [comment]
This is not an issue with AE2 itself but with those mods, so it's on them to fix it. Thanks for reporting!
