### ISSUE TITLE
Tooltips on Fabric don't wrap properly

### ISSUE THREAD

**Issue by shartte** [AppliedEnergistics/Applied-Energistics-2#5626]
![grafik](https://user-images.githubusercontent.com/1261399/139601284-06e818cc-1446-44e5-85e8-10d360a985c7.png)

**Comment by xanthian** [comment]
![image](https://user-images.githubusercontent.com/7688001/141598800-12b91a6c-238e-4bf1-8a61-71a9e2384b61.png)

**Comment by shartte** [comment]
Using the same wrapping method as chat gets us this:

![grafik](https://user-images.githubusercontent.com/1261399/142763658-2f7683a8-16e9-4bf4-878c-f76a19c754fa.png)
