### ISSUE TITLE
webview for ME System for MC-Servers

### ISSUE THREAD

**Issue by cmod31** [AppliedEnergistics/Applied-Energistics-2#5628]
### Describe the feature

I would like to see the items we have in my browser or on my phone to know wich we have how much of

### Reasons why it should be considered

I don't want to boot up my whole atm 6 modpack to see what stuff i already have

### Additional details

Just make it work for servers would be easier i think

**Comment by shartte** [comment]
Sorry this is out of scope for AE2.

**Comment by cmod31** [comment]
Is it possible to make seperate plugin is there a api or something
