### ISSUE TITLE
ME Interface (ME Blank Pattern)

### ISSUE THREAD

**Issue by Wintori** [AppliedEnergistics/Applied-Energistics-2#5633]
### ME Interface BUG

I am playing on version 1.17.1. Downloading the latest update on this site ( https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2/files ). 9.0.0-beta.1 [FABRIC] . When opening the ME interface, the cells for templates do not appear from the bottom. **I cannot use ME Blank Pattern** ! Fix ME interface pls!!

### How to reproduce the bug

Open the ME interface and try to put the template there. To make an autocraft.

### Expected behavior

Add a window for templates at the bottom when opening the ME interface

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

https://gist.github.com/Wintori/2b8e795f351c1d4c4de44bc5302c1fb4

**Comment by shartte** [comment]
The interface was changed. You need to use a pattern provider.
