### ISSUE TITLE
Several items/recipes are unavailable, unable to progress

### ISSUE THREAD

**Issue by lwskosa** [AppliedEnergistics/Applied-Energistics-2#5634]
### Describe the bug

Items are missing from mod

- using 1.17.1-forge-37.0.103
- using appliedenergistics2-9.0.0-beta.1
- Windows 10 x64

## Missing items so far (there may be more):

- [Wooden Crank](https://ae-mod.info/Wooden-Crank/)
- [Quartz Grindstone](https://ae-mod.info/Quartz-Grindstone/)
- [Wooden Gear](https://ae-mod.info/Wooden-Gear/)

![image](https://user-images.githubusercontent.com/45472566/139757097-54a14c1c-e123-4c9b-8d1a-022f722963c7.png)

### How to reproduce the bug

1. Try to craft items as per their recipe
2. Items will not craft
3. Check JEI/attempt manually add via /give command
4. Items are not present
(So it is not just the recipe)

### Expected behavior

Items are present and player able to craft

## Additional mods I am using:

- appleskin-forge-mc1.17.1-2.1.0
- architectury-2.6.35
- balm-1.7.0+0
- cc-tweaked-1.17.1-1.98.2
- cfm-7.0.0pre25-1.17.1
- chiselsandbits-1.1.39-ALPHA
- cloth-config-5.0.38-forge
- Clumps-forge-1.17.1-7.0.10
- collective-1.17.1-2.64
- constructionwand-1.17.1-2.4
- cookingforblockheads-10.0.0+0
- corail_woodcutter-1.17.1-2.1.2
- elevatorid-1.17.1-1.8.1
- ironchest-1.17.1-12.0.2
- jei-1.17.1-8.1.0.31
- JustEnoughResources-1.17.1-0.13.0.131
- light-overlay-6.0.1-forge
- mcw-doors-1.0.4-mc1.17.1
- torchmaster-3.0.1-beta
- treeharvester_1.17.1-3.2
- veinmining-forge-1.17.1-0.12
- waystones-8.1.4+0
- xptome-1.17.1-v2.1.3

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Forge

### Crash log

Not applicable

**Comment by Ommina** [comment]
Grindstone and related have been removed.  ( See https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/5444 )

Alternate means to obtain what the grindstone used to provide should be available.  If there is something specific missing that is preventing progression, please be explicit with what it is.

**Comment by lwskosa** [comment]
> Alternate means to obtain what the grindstone used to provide should be available. If there is something specific missing that is preventing progression, please be explicit with what it is.

Consulted Wiki, did not say what changed, I do apologize if this is by design. Picking up the game after a rather long pause and 1.12.2, and I only remembered the old (before removal) progression.
No clue how can I use the charger without the crank though, as it is still missing, not just the grinder. As per seen on included screenshot

**Comment by Technici4n** [comment]
You can find the new progression on the new wiki: (we don't have access to the old one)

https://appliedenergistics.github.io/getting-started

**Comment by Technici4n** [comment]
You'll have to either use the vibration chamber, or install another mod that can produce energy for the charger.
