### ISSUE TITLE
Shift-Right Clicking on an empty storage device does not retrieve the unit inside

### ISSUE THREAD

**Issue by ThePiercedPrince** [AppliedEnergistics/Applied-Energistics-2#5635]
### Describe the bug

I have seen in videos and also even on your own website that this is supposed to be a feature.  When I attempt to do it in game it does not work unfortunately.  I asked in discord and nobody knew what I was talking about so either they didn't know, or it's not worked for a while now.

### How to reproduce the bug

shift-right click with an empty storage device in hand and nothing happens

### Expected behavior

According to the documentation when I shift-right click on an empty unit it is supposed to remove the internal unit.

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

I don't have a crash report

**Comment by shartte** [comment]
Yes this should work. Will check it. I think technician also looked into this recently, in addition to the shift+right-click, you should be able to also use a special recipe, which I think is also borked.

**Comment by Technici4n** [comment]
I can't reproduce this. Are you sure that the storage cell is actually empty (doesn't contain items)?

**Comment by ThePiercedPrince** [comment]
Yes, I made a brand new storage unit, as a test.  I am on AoF4 so perhaps there is a conflict somewhere.  I tried both the crafting recipe and also the shift right click option and nothing happens with either.

**Comment by Technici4n** [comment]
What do you call "storage unit"? Is it a storage cell, the thing you put in the drive? If that doesn't work then you should report this to aof4.

**Comment by ThePiercedPrince** [comment]
I just tried again after updating and it works! So I will close this.  Thank you for your attention.
