### ISSUE TITLE
REI Integration issue

### ISSUE THREAD

**Issue by xanthian** [AppliedEnergistics/Applied-Energistics-2#5637]
### Describe the bug

Unsure if this is an REI issue or AE2 issue.
When hovering over any of the + icons to move items to crafting grid, it displays this rather long unreadable string

![image](https://user-images.githubusercontent.com/7688001/139963333-4d3974b5-e2fc-4265-a5d5-3548d6dca5e8.png)

If the items are present and its possible to move them to the crafting grid using the + button, it will move them, but the display bug is still present.

### How to reproduce the bug

Open REI and hover the  +

### Expected behavior

Display correctly? :)

### Additional details

All mods used are latest releases.
No crash, but crash forced as advised.

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

https://gist.github.com/xanthian/3f8df5d44e98f093dfde2723d7c7c1ca

**Comment by Technici4n** [comment]
![image](https://user-images.githubusercontent.com/13494793/140587683-c8b37c81-d724-4742-ade0-d843760b34b6.png)

Can't reproduce, so I'm going to blame another mod.

**Comment by xanthian** [comment]
![image](https://user-images.githubusercontent.com/7688001/140604735-e4db1a8d-143a-4e93-a5e7-1e5d9deb3a7f.png)
Shame you can't recreate it, but I can assure you its not another mod I have.
See mod list.
Could it be differing versions to what you have?
