### ISSUE TITLE
[Crash] FAPI Transfer ->  AE2 ForgeEnergyAdapter + Indrev - Exception Ticking world

### ISSUE THREAD

**Issue by red2blue** [AppliedEnergistics/Applied-Energistics-2#5641]
### Describe the bug

Whenever a player joins he crashes the dedicated server due to his setup. Used Indrev pipes into AE2 

Reported to indrev https://github.com/GabrielOlvH/Industrial-Revolution/issues/343

### How to reproduce the bug

Unsure, all he repoted is that he crashed, looked at the server crash logs to verify. 

### Expected behavior

Indrev pipes working with ae2

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/NtD3HNzY

**Comment by Technici4n** [comment]
Indrev bug. I think it was fixed, but I'm not sure if it was released yet.
