### ISSUE TITLE
[1.16 Forge] Crash with Sky Stone Chest

### ISSUE THREAD

**Issue by viceversagames** [AppliedEnergistics/Applied-Energistics-2#5642]
### Describe the bug

Game crashed while mining a meterorite, bypassed NotEnoughCrashes and exited to desktop.

### How to reproduce the bug

No idea, but I think I removed the chest and opened it at the same time. I logged back in and had the press in my inventory, with the chest gone.

### Expected behavior

My game would still be running.

### Which minecraft version are you using?

1.16

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/viceversagames/dd0b3bc668f0186116d17d098fc599f2

**Comment by shartte** [comment]
This can occur if the screen opens on the client but the block or item for which it was opened on the server has already moved/been removed.

**Comment by shartte** [comment]
I'll retest this on Forge. On Fabric, you'll just get a log message instead of outright crashing the client. But I also see you have a mod installed that hooks into UI rendering, which might be the reason you see a hard crash instead:

> com.daderpduck.seamless_loading_screen.ScreenshotTaker.resizeScreen

**Comment by shartte** [comment]
Yes. Confirmed. This doesn't really crash on Forge either without that additional mod. But the fix we pushed will also fix it in case the mod is present. (Only on 1.18 onwards).
