### ISSUE TITLE
Pattern terminal won't let me add the recipe from JEI

### ISSUE THREAD

**Issue by djoveryde** [AppliedEnergistics/Applied-Energistics-2#5643]
### Describe the bug

I am running the latest 1.16.5 version of AE2 + JEI. 
I've just built the ME pattern terminal, added a blank pattern and now every time I try to add the recipe for the blank pattern from JEI the pattern flashes green and fails to input the recipe.
Not sure if I need to add something to a config or if I am missing something?

### How to reproduce the bug

Build ME pattern terminal. Try to add any recipe from JEI.

### Expected behavior

Pattern should go into the pattern terminal for adding to a blank pattern.

### Which minecraft version are you using?

1.16

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/tQj6Kje5

**Comment by Technici4n** [comment]
Hi, could you perhaps provide a video of this issue?

**Comment by djoveryde** [comment]
I'll give it a go. Further investigation I've found that I can open the recipe in JEI perfectly fine. However when I open the pattern terminal it fails to open the recipe and acts as though it wants to import the item into the pattern terminal instead.

**Comment by Technici4n** [comment]
Ah ok, that's just a JEI bug then.

**Comment by Technici4n** [comment]
See also https://github.com/mezz/JustEnoughItems/issues/2352.

**Comment by djoveryde** [comment]
https://user-images.githubusercontent.com/8558407/140543540-9e9a42bb-c8ea-4438-9a0f-3b28070945ea.mp4

**Comment by Technici4n** [comment]
Ah I see, yes this is indeed the JEI bug I linked. Thanks for reporting nonetheless.

**Comment by djoveryde** [comment]
Tried the R key, it just repeatedly types R into the text. Even manually set the keybind to be unique?

**Comment by djoveryde** [comment]
EDIT: Had to change the "Standard Search" to stop it from forcing text into the terminal
