### ISSUE TITLE
Add forge tag to ender pearl dust

### ISSUE THREAD

**Issue by ShinyPorygon** [AppliedEnergistics/Applied-Energistics-2#5645]
### Describe the feature

The ender dust should have the `forge:dusts/ender_pearl` tag.

### Reasons why it should be considered

This makes the mod more compatible with other mods, that have the same exact ender pearl to ender pearl dust recipe. And for pack makers who choose to choose a different ender dust to be the main one this makes them not have to either use specifically AE2's or make a new one.

**Comment by Technici4n** [comment]
We should change the tag we use from `forge:dusts/ender` to `forge:dusts/ender_pearl`. It is not clear which one should be used by mods, but with thermal and ae2 using the latter that should be enough for other mods to align.

**Comment by Technici4n** [comment]
Will be in the next release. Sorry it took forever... 😓
