### ISSUE TITLE
Chest pattern rendering bug

### ISSUE THREAD

**Issue by EnderProyects** [AppliedEnergistics/Applied-Energistics-2#5646]
### Describe the bug

When is a pattern of crafting a chest in a pattern and you press mayus to see the pattern it doesn´t apear

### How to reproduce the bug

make a pattern of a chest, place it on your inventory, press mayus to ( not) see it

### Expected behavior

To see the pattern

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/YwKeDfHw

**Comment by EnderProyects** [comment]
![image](https://user-images.githubusercontent.com/45178400/140663810-9ad65761-ad0c-4fe2-b219-bf2797b5f5e2.png)
I think I dont leave a photo here, so xd

**Comment by shartte** [comment]
This has been fixed
