### ISSUE TITLE
autocrafting job not properly utilizing multiple interfaces with the same recipy rv6-stable-7

### ISSUE THREAD

**Issue by T3cube** [AppliedEnergistics/Applied-Energistics-2#5647]
### Describe the bug

I have a bunch of interfaces with the same pattern present and they are not all being used to craft the item when requested. Only some of the interfaces are being used

![image](https://user-images.githubusercontent.com/70706789/140630051-95b53ec7-5d22-483b-9bbc-df7c58008a3f.png)

### How to reproduce the bug

Have a large crafting core with 255 coprocessors and capable of 5 million bytes of crafting capacity.
Set up a 64 ME interfaces with the same processing pattern for the machine.
issue a job.

### Expected behavior

ALL machines with the same pattern, should be used for crafting provided there are enough co-processors.

### Additional details

My network configuration is as follows:
1 central network which handles routing for other networks
64 subnetworks (one with 28 P2P channels and one with 4 P2P channels)that have their channels routed via P2P through the central network.
All subnetworks interface with the central network
The central network interfaces with all the subnetworks
All channels are extracted with P2P tunnels and are fed into the main network, then all channels are extracted into ME quantum rings for use elsewhere with a pairing quantum ring.
ME storage is on a unit (32 channels [28+4])
Storage busses are on a seperate unit which are getting items from barrels (YABBA)

Because crafting jobs cannot be issued from subnetworks, P2P tunnels are extracting tunnels directly from the main network into a quantum ring. The channels exit to an AE storage cell dimention (1024 channels total) into 512 import busses, and 512 interfaces.

this is a picture of the processing pattern segment of autocrafting and a unit (28+4) handling basic item exports
(the bottom is the one that is connected directly to the central network, and it is where i am having problems)
![image](https://user-images.githubusercontent.com/70706789/140630424-e2e478b6-b1b6-46d3-a696-f4317ee88ad9.png)

this is a picture of the assembler segment of the autocrafting and the ME drive network
![image](https://user-images.githubusercontent.com/70706789/140630452-2b15d4a8-762d-44b7-89d9-049a90128c5b.png)

this is a picture of the central network and the side that is handling channels for the processing patterns.
![image](https://user-images.githubusercontent.com/70706789/140630874-0645ecaa-8e88-4c03-a931-a5eda96d2249.png)

this is a picture of a 'unit' (white rainbow). 2 subnetworks interfacing with the central network and the central network interfacing with both networks. This is the one handling ME drives. (the drives being used are 16384k drives from extra cells 2 if that makes any difference)
![image](https://user-images.githubusercontent.com/70706789/140630723-290a3ac3-439f-420e-a7c3-b28abbd40dcc.png)

### Which minecraft version are you using?

1.12 - UNSUPPORTED

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/T3cube/fe4837a986f8b9ff348c9bea1c93ad71

**Comment by EnderProyects** [comment]
In the new versions it does not work either, you can try to put an interface in front of a chest, and from the chest move the items to the machines. Take into account that for example a double chest has nine faces for interfaces, and one for the items to come out for the machines (either with a pipe system or with a separate network)

**Comment by T3cube** [comment]
> In the new versions it does not work either, you can try to put an interface in front of a chest, and from the chest move the items to the machines. Take into account that for example a double chest has nine faces for interfaces, and one for the items to come out for the machines (either with a pipe system or with a separate network)

The problem with this is getting all the machines to accept the resources evenly. Pipes only go to the closest inventory first with the most space. This results in one machine having the entire workload and the rest acting is back up which is what I'm trying to avoid by splitting the items evenly across all machines with multiple interfaces because AE will split the resources evenly.
