### ISSUE TITLE
Make that formation planes can place ender crystals

### ISSUE THREAD

**Issue by EnderProyects** [AppliedEnergistics/Applied-Energistics-2#5655]
### Describe the feature

When the formation plane is placed under or to the side of the bedrock/obsidian, and it has a filter of ender crystals it could place it above.
![image](https://user-images.githubusercontent.com/45178400/140940089-f2c7647a-ebcc-45dc-babf-a5dcc3af36a5.png)

### Reasons why it should be considered

It can automate many things endgame, and although the bad thing is that it is an entity and not a block as such, it could be something unique, since there is no other entity that is put as such, with this many things can be automated in the end as a regenerated obsidian tower farm, dragonslayer, or endstone farm, without the need for a player present to place the endercrystals. ( I am talking in vanilla, idk with other mods)

**Comment by mindforger** [comment]
is there a reason it has to be from the bottom side? can't it be placed like samplings for example?

**Comment by EnderProyects** [comment]
No, there are two reasons because it can't be, one, the hitbox is bigger than a normal block, so if you try to place it with a block near you can't, two, the ender crystal explode when you use it

**Comment by EnderProyects** [comment]
![image](https://user-images.githubusercontent.com/45178400/140951965-80968987-77c4-4f60-9c7e-7798224e5144.png)
Well, this can be done but xd

**Comment by mindforger** [comment]
wait .... you can place water on the cables?! oh lord the possibilities

**Comment by shartte** [comment]
Yeah, yueh added cable waterlogging a while ago. We reaaaaaalllyyy suck at providing good changelogs :-(

**Comment by EnderProyects** [comment]
Well the thing is, could this be implemented?

**Comment by Technici4n** [comment]
I don't see us ever special casing this. If our rather general logic doesn't work, too bad!
