### ISSUE TITLE
Misplaced Sort Charm button

### ISSUE THREAD

**Issue by red2blue** [AppliedEnergistics/Applied-Energistics-2#5660]
### Describe the bug

![image](https://user-images.githubusercontent.com/35115304/141230935-40ed5134-2461-4b85-9e91-132f2c1cb1c0.png)

As you see in the screenshot, the charm tidy button is moved down to the hotbar. 

### How to reproduce the bug

Install Charm
turn on tidy sort config entry
open a AE2 chest

### Expected behavior

Should be in between Inv and Chest

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

no crash

**Comment by shartte** [comment]
You'll have to report this to the mod that adds the button, not us.

**Comment by Technici4n** [comment]
@shartte we can possibly solve it by changing in which order we register the slots though?
