### ISSUE TITLE
Forge Tags are pretty messed up

### ISSUE THREAD

**Issue by ChiefArug** [AppliedEnergistics/Applied-Energistics-2#5666]
Some items/recipes are missing tags that means they do not have full compatibility with other mods.
I will attempt to list them all (with as little wall-of-textness as possible). I am using the latest Forge 1.16.5 version (8.4.3) to check these.
Note: `#` denotes an item tag, `+` denotes a recipe and neither denotes an item.

`#appliedenergistics2:glass` should be migrated to `#forge:glass`
The two things currently added to this tag are `#forge:glass` and `minecraft:glass` (which is already in `#forge:glass`) so it is entirely unnecessary
Affected: 
```
	+appliedenergistics2:network/parts/quartz_fiber_part
	+appliedenergistics2:network/blocks/storage_chest
	+appliedenergistics2:network/blocks/spatial_io_port
	+appliedenergistics2:network/blocks/io_port
	+appliedenergistics2:network/blocks/io_condenser
	+appliedenergistics2:network/blocks/interfaces_interface
	+appliedenergistics2:misc/vanilla_daylight_detector
	+appliedenergistics2:decorative/quartz_glass
```
\
\
`#appliedenergistics2:wool` should be migrated to `#minecraft:wool`
The only thing being added to this tag is #minecraft:wool so it is unnecessary
Affected:
```
	+appliedenergistics2:network/cables/covered_fluix
	+appliedenergistics2:network/blocks/cell_workbench
	+appliedenergistics2:materials/cardfuzzy
```
\
\
`#appliedenergistics2:workbench` should be migrated to `#forge:workbench` as this is the tag mods like Better End use
Affected: 
```
	+appliedenergistics2:network/parts/terminals_crafting
	+appliedenergistics2:network/crafting/molecular_assembler
	+appliedenergistics2:materials/cardcrafting
	minecraft:crafting_table (Forge doesn't add this by default)
```
\
\
`#appliedenergistics2:crystals`
These are a mess due to them being sometimes equivalent.
Most of them should be able to just be migrated to `#forge:gems` but not in the case of where both are acceptable inputs.
Recommendation for that would be to keep `#appliedenergistcs2:gems/quartz` for that purpose, and just add both `#forge:gems/certus` and `#forge:gems/quartz` to it (and the pure versions too)
A similar situation applies for Fluix, with both the pure and non pure versions
\
\
`#appliedenergistics2:silicon` should be migrated to `#forge:silicon`
Affected:
```
	+appliedenergistics2:inscriber/silicon_print
	appliedenergistcs2:silicon
```
\
\
As mentioned in #5645 `#appliedenergistics2:ender_dust` should be migrated to `#forge:dusts/ender_pearl`
Affected:
```
	appliedenergistics2:ender_dust
	+appliedenergistics2:network/wireless_booster
	+Singularity Crafting (I cannot tell what it currently uses)
```
\
\
`#appliedenergistics2:dusts`
These are a mess due to them being sometimes equivalent.
Most of them should be able to just be migrated to `#forge:dusts` but not in the case of where both are acceptable inputs.
Recommendation for that would be to keep `#appliedenergistics2:dusts/quartz` for that purpose, and just add both #forge:dusts/certus and #forge:dusts/quartz to it)
\
\
`#appliedenergistics2:gears/wooden` should be migrated to `#forge:gears/wooden`
Affected:
```
	+appliedenergistics2:misc/grindstone
	appliedenergistics2:wooden_gear
```
\
\
`#appliedenergistics2:quartz_wrench` and `#appliedenergistics2:knife`
These should be kept as they are. It could be considered to add `#forge:wrench` to the wrenches, however there is not much use of that tag in other popular mods.

All the cable and panel tags make sense as they are. `#appliedenergistics2:metal_ingots` also makes sense as it is.
\
\
And that is it. I am happy to provide other info, ChiefArug 4639 on the AE2 Discord.

**Comment by Technici4n** [comment]
Hi, thanks for this. We'll look into fixing it for 1.18.

**Comment by shartte** [comment]
Yeah some of this stuff dates back to me trying to separate things we "provide" and things we "consume" into two sets of tags in 1.15.
My idea at the time was that we define a tag "ae2:glass" for when we want to use something glass-like in a recipe, while contributing our glass to "forge:glass" for others to use. This was supposed to enable modpacks to change what type of glass AE2 accepts separately from other mod's recipes. I don't think anyone ever used it like that.

On top of that, we probably also messed up the tags a little when we moved to data generating the tags.

**Comment by Technici4n** [comment]
Seems ok from inspection of our datagen in 1.18.2. Please open a new issue if some tags are still messed up after `v11.0.0-alpha.3`.
