### ISSUE TITLE
Game crashed, cant re-enter world 

### ISSUE THREAD

**Issue by xanthian** [AppliedEnergistics/Applied-Energistics-2#5667]
### Describe the bug

Placed a ME Fluid Storage bus on to a ME Fluid Interface (intentionally as I've no idea what i'm doing)
Game immediately crashed, on trying to reload the world it crashes again.

(I dont care about the world it was my creative test env luckily!)

### How to reproduce the bug

I've tried replicating the setup I had previously and it wouldn't crash, however I have gotten it to crash again using the same 2 items randomly placing them together in various combinations.

here is the world save.
[New World.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/7531784/New.World.zip)
,

### Expected behavior

Not to crash

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

https://gist.github.com/xanthian/56c99450588eece0b45981a9ad2f72e5

**Comment by Tahakk** [comment]
`Invalid Config setting.`
That's speaking for itself. If you didn't change the config I'd suggest deleting it and letting regenerate

**Comment by XFactHD** [comment]
This has nothing to do with config files, the crash occurs in the Fluid Interface configuration system

**Comment by XaidenHart** [comment]
I have experienced the same issue while connecting a fluid interface to a fluid storage bus. My world has crashed and will crash again upon restart.

Crash log:
https://gist.github.com/XaidenHart/7a1287e1b29045413029a3428a0c5f93

**Comment by XaidenHart** [comment]
I have played around with this and can reproduce the issue. All you need is to place a fluid storage bus onto a fluid interface and set a config slot in the interface to some fluid. I have tried updating to AOF4 1.1.0 and I'm still running into this issue.

Crash log:
https://gist.github.com/XaidenHart/d553cfe2bdfb439d4ce3eb570467c4f4

**Comment by Technici4n** [comment]
Did we ever fix this?

**Comment by xanthian** [comment]
No you didnt, not really as long as I remember not to do it :P

**Comment by shartte** [comment]
While crash bugs are really bad, I am not sure we want to invest the time to go back to 1.17 for fixing this? Thoughts?

We have a rather large backlog for 1.18 and fixing critical issues on 1.16 seems more important given how short the live of 1.17 turned out to be.

**Comment by xanthian** [comment]
havent tested this crash in 1.18, will try it and let you know.

and yes,, very shitty :(

**Comment by xanthian** [comment]
obvs cant replicate cos no such thing as fluid bus/interface now. closing
