### ISSUE TITLE
Missing textures in transparent and not-full blocks

### ISSUE THREAD

**Issue by UnusedCactus** [AppliedEnergistics/Applied-Energistics-2#5669]
### Describe the bug

![2021-11-14_17 49 23](https://user-images.githubusercontent.com/87100678/141702242-190a76cf-df51-470a-8797-f9c82a135055.png)
Textures and models are missing from blocks that are transparent and/or not full. This does not crash the game. All facade inventory textures are also missing. Hitboxes remain untouched. Afflicts 9.0.0 beta 2.

### How to reproduce the bug

Place a block that is transparent, does not consist of a full block (that also isn't a chest, half slab, or stair) or a block that consists of those properties from AE2.

### Expected behavior

No textures or proper models on blocks that are transparent or does not consist of a full block.

### Additional details

The modified version of Sodium included with Iris Shaders may cause this. Still a problem

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/QBWskbXz

**Comment by Technici4n** [comment]
Install indium.

**Comment by UnusedCactus** [comment]
It worked. Thanks
