### ISSUE TITLE
Crafting patterns containing empty slots are invalid

### ISSUE THREAD

**Issue by Mari023** [AppliedEnergistics/Applied-Energistics-2#5671]
### Describe the bug

on the master branch, crafting patterns with empty slots are invalid.
presumably, this happens because air is encoded and interpreted as part of the recipe. (see screenshot)

### How to reproduce the bug

create a valid crafting pattern where at least one slot is empty and encode it

### Expected behavior

The pattern to be valid

### Additional details

![2021-11-16_20 28 20](https://user-images.githubusercontent.com/38946771/142052582-d7bb0250-f017-4030-b471-80235ecc8eb9.png)

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

https://gist.github.com/Mari023/acc2ebad606901c14d9fd3b1601e4b67

**Comment by Technici4n** [comment]
Fixed in #5681.
