### ISSUE TITLE
ME Interface Terminal breakes with too many crafting patterns

### ISSUE THREAD

**Issue by N2Blue** [AppliedEnergistics/Applied-Energistics-2#5673]
### Describe the bug

Hi,

I am sadly certain this is a duplicate of #5298 and #5082, but seems to still occure.

Version: appliedenergistics2-8.4.3.jar
Modpack: FTB OceanBlock - Forge - SingePlayer - inBuild Java Version

I have setup a big autocrafting setup with 124 Molecular Assemblers and at the moment they are just half full with patterns.
But now if I put one more pattern into on of the connected ME Interfaces and then go to the Interface Terminal it will show me a blank page/no more patterns.

First I thought it will be a broken recipe, but I tracked it down and connected more and more ME Interfaces to the network till the error occured. I continue adding patterns till the error occured and so I found out the pattern does not matter, its just the amount of patterns.

Next thing is, the error is **not** happening when you put in the pattern, the error in the log is triggered when you **access the ME Interface Terminal**. You can still autocraft items through other Terminals.

If you look into the logs you see something like "Tried to read NBT tag that was too big; tried to allocate: 2097168bytes where max allowed: 2097152" and it looks like there is a limit of 2097152bytes which I hit/tried to exceed.

Maybe my log-files can help to locate the error.

### How to reproduce the bug

Using a lot of crafting patterns.

### Expected behavior

ME Interface Terminal should still work and show a overview of all patterns in connected ME Interfaces.

### Which minecraft version are you using?

1.16

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/N2Blue/f93a936e2173cf7095d6ca4652b5ec2a

**Comment by shartte** [comment]
Will be fixed in 8.4.4
