### ISSUE TITLE
Charged Quartz Ore spawn chance config doesn't do anything

### ISSUE THREAD

**Issue by ChiefArug** [AppliedEnergistics/Applied-Energistics-2#5686]
### Describe the bug

The config option for the chance for a certus quartz ore to be charged does not have an effect in game.
I think this is because `getSpawnChargedChance()` is never called (searched the github for it, only result was in the config file where its defined).

### How to reproduce the bug

Set `spawnChargedChance` in `appliedenergistics2-common.toml` to an extreme value, such as 0 or 1. Create a new world and fly around underground (`/fill ~-10 ~-10 ~-10 ~10 ~10 ~10 air replace #forge:stone` can be used to clear out stone around the player).
You will see the config value has no effect on whether charged or regular certus spawns.

### Expected behavior

Changing the config value should have an effect on the ores that spawn. Setting it to 0 should make no **charged** ores spawn and setting it to 1 should make all certus ores be **charged** ones.

### Which minecraft version are you using?

1.16

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/19175/f1e337be04be95bf513482ef28132255

**Comment by shartte** [comment]
Charged quartz only replaces quartz ore.
What effect did you expect??

Chief Arug ***@***.***> schrieb am Sa., 20. Nov. 2021, 00:48:

**Comment by 19175** [comment]
Like i said originally, I expect it to have an effect on the amount of **charged** ore in the world, not on the amount if regular ore.

**Comment by shartte** [comment]
We're unlikely to fix this retroactively for 1.16 at this point. Since there's no charged quartz spawns in 1.17+, I'll close this issue.

But thanks for reporting it in any case!
