### ISSUE TITLE
Starting an autocraft request doesn't leave the GUI

### ISSUE THREAD

**Issue by aaronhowser1** [AppliedEnergistics/Applied-Energistics-2#5694]
### Describe the bug

![image](https://user-images.githubusercontent.com/15698722/142747161-38b9870b-64f2-4738-b43e-79fcb3d3d508.png)
Clicking `Start` here keeps you in this GUI, so you think it didn't work, but it did

### How to reproduce the bug

Autocraft something, click Start

### Expected behavior

It should send you back to the terminal GUI

### Additional details

FTBTeam/FTB-Modpack-Issues/issues/208

### Which minecraft version are you using?

1.16

### On which mod loaders does it happen?

Forge

### Crash log

N/A

**Comment by Technici4n** [comment]
We've had reports of similar issues caused by some broken mixins in the wireless terminal mod you are using, can you confirm that it happens even with that mod removed?

PS: the correct CF page is https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2-wireless-terminals-forge, but your website references an older version of the mod for 1.12.

**Comment by Mari023** [comment]
I guess the pack contains [this version](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2-wireless-terminals-forge)
of wireless terminals instead [this 1.12 version](https://www.curseforge.com/minecraft/mc-mods/ae2wtlib)?

this is a know bug tracked [here](https://github.com/Tfarcenim/AE2WirelessTerminalLibrary/issues/27), and there is a PR that fixes the bug [here](https://github.com/Tfarcenim/AE2WirelessTerminalLibrary/pull/32)

**Comment by Technici4n** [comment]
Alright, thanks.

**Comment by aaronhowser1** [comment]
I think the problem with the page is because both have the same mod id, and it didn't know which to point it to. I'll forward that bit to the people in charge of that.

It does not happen when that mod is removed, sorry! Looks like they already have an issue for it too (Tfarcenim/AE2WirelessTerminalLibrary/issues/27)
