### ISSUE TITLE
Useless null check

### ISSUE THREAD

**Issue by Technici4n** [AppliedEnergistics/Applied-Energistics-2#5710]
The null checks for `node.getGrid()` in `IManagedGridNode` are useless: `getGrid` will never return a null grid.

**Comment by shartte** [comment]
Is it possible that this happens after/while destroying the grid?

**Comment by Technici4n** [comment]
No:
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/2760f4ededd3fe72a7c445fa49f739f9d26b89d1/src/main/java/appeng/me/GridNode.java#L279-L285

**Comment by shartte** [comment]
A nice, then you are fully correct, i think I added the
IllegalStateException later

**Comment by Technici4n** [comment]
Yeah, this is the kind of assumptions that are very hard to deal with... Only after extensive testing can we say that it's indeed safe to throw the exception...
