### ISSUE TITLE
ME fluid interface does not consume fluid

### ISSUE THREAD

**Issue by luoxingzlx** [AppliedEnergistics/Applied-Energistics-2#5711]
When one of its buffers is filled, using me fluid formation plane will not consume fluid
![ae bug](https://user-images.githubusercontent.com/44374013/143661251-8c3079fe-9b14-4438-8533-408f9745c0cd.gif)

reproduce the bug
https://streamable.com/5n2vh5

Minecraft 1.12.2
forge 14.23.5.2855
appliedenergistics2-rv6-stable-7

**Comment by Technici4n** [comment]
Sorry, the fluid interface is bugged in 1.12, but we don't support versions older than 1.16 anymore.
