### ISSUE TITLE
Annihilation planes on kelp hurt server TPS

### ISSUE THREAD

**Issue by cpm9** [AppliedEnergistics/Applied-Energistics-2#5713]
### Describe the bug

I don't know if this is fixable or not, users just probably shouldn't do this, but in case its something that shouldn't be happening I thought I would report it. If you set up about 200 annihilation planes to farm kelp then it really hammers the server tps down to about 10/20. 

### How to reproduce the bug

Set up about 200 annihilation planes to farm kelp on a forge server. This was done in the storage dimension, I don't know if that is relevant or not.

![image](https://user-images.githubusercontent.com/82549089/143732175-4d5efb4f-d136-43e7-badd-f103cf3982cf.png)

![image](https://user-images.githubusercontent.com/82549089/143732197-a097b643-23dc-44d6-81a5-316aa258efd0.png)

![image](https://user-images.githubusercontent.com/82549089/143732328-d173677a-c06f-43a1-8b6e-4f757ea26320.png)

### Expected behavior

I hoped that 200 annihilation planes would not bring server TPS to 10/20 but if I am wrong and this is expected behavior then I will understand.

### Additional details

I included the spark report as the "crash log" as there was no actual crash log.

appliedenergistics2-8.4.3
forge-1.16.5-36.2.6

### Which minecraft version are you using?

1.16

### On which mod loaders does it happen?

Forge

### Crash log

https://spark.lucko.me/VJoIWQS94I

**Comment by Technici4n** [comment]
Could you post the link to the spark profile?

**Comment by PrototypeTrousers** [comment]
oh he put the spark profile link under the the Crash log part.
His setup looks like 6 annihilation planes + storage bus on an interface, rinse and repeat 35 times

**Comment by Technici4n** [comment]
Oh sorry I'm blind. There are two things here that make this particularly bad:
- The very high nesting of storage busses and interfaces.
- Forge ItemStack capabilities.

You can reduce the former by changing your setup to use one network with a controller and p2p tunneling instead of highly nested storage busses on interfaces.
The latter will be addressed in the next 1.16 forge release (might still be in a while).

**Comment by Technici4n** [comment]
> The latter will be addressed in the next 1.16 forge release (might still be in a while).

@cpm9 Actually it was released, can you try the latest forge release from https://files.minecraftforge.net/net/minecraftforge/forge/index_1.16.5.html (36.2.19) and send us a new spark profile so we can know if the issue has been fixed? Thanks!

**Comment by cpm9** [comment]
> Actually it was released, can you try the latest forge release from https://files.minecraftforge.net/net/minecraftforge/forge/index_1.16.5.html (36.2.19) and send us a new spark profile so we can know if the issue has been fixed? Thanks!

Okay thanks I'll test with the new version

**Comment by Technici4n** [comment]
@cpm9 any update?

**Comment by cpm9** [comment]
> @cpm9 any update?

Yeah changing the setup like you suggested fixed it. So I guess we can close this now

**Comment by Technici4n** [comment]
I was wondering if the new forge version had fixed it (as it should have fixed the underlying problem).

**Comment by cpm9** [comment]
> I was wondering if the new forge version had fixed it (as it should have fixed the underlying problem).

I did update to the latest forge and ae2 but we had already changed the setup by that point and doing that fixed it, so I'm not sure if the forge version fixed the underlying problem

**Comment by Technici4n** [comment]
Ah ok, we'll let's assume it is fixed then. Thanks for your quick replies! :)
