### ISSUE TITLE
Inscriber bug

### ISSUE THREAD

**Issue by utaninja** [AppliedEnergistics/Applied-Energistics-2#5716]
### Describe the bug

When using the inscriber weather there is power on no power connected to it when you right click it there should be a ui that you can interact with but on the server whether there is power or not there is no way to interact with ae2 blocks that usually should be interactable
like that? This is for AE2. 

### How to reproduce the bug

use in inscriber weather serverside

### Expected behavior

https://cdn.discordapp.com/attachments/878829123080953936/915052264417263706/2021-11-29_20.30.17.png

### Which minecraft version are you using?

1.7  - UNSUPPORTED

### On which mod loaders does it happen?

Fabric

### Crash log

crash log: https://privatebin.net/?c8f2212c9ea6f1fb#9ZeLTEqVJxegPmWvoPnbhnfqSE1TLbwnAnUmiVUe8R5v

**Comment by Technici4n** [comment]
Update ledger.
