### ISSUE TITLE
Type limit is not enforced

### ISSUE THREAD

**Issue by yu-re-ka** [AppliedEnergistics/Applied-Energistics-2#5719]
### Describe the bug

I can insert more than 63 types of items into an item storage cell. It says 64 of 63 types used in the tooltip.

### How to reproduce the bug

Attempt to insert >63 different item types into a network with a single cell

### Expected behavior

When the number of types a cell can hold is reached, it should no longer be possible to insert items into the cell

### Additional details

Using the CI build from commit bef9dbc89795d29a9e76c95bcdd727a2bf6667f6

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://termbin.com/90nk

**Comment by shartte** [comment]
Sadly made another ID change that'll break your test setup, but it does fix the bug.
