### ISSUE TITLE
Textures disappear

### ISSUE THREAD

**Issue by DoctorSigma** [AppliedEnergistics/Applied-Energistics-2#5721]
### Describe the bug

I play with a certain build of mods. Sometimes the textures disappear as shown in screenshot 1, it only helps if I break one cable and put it back, after which not all textures are restored.

![image](https://user-images.githubusercontent.com/93322905/144577092-19aa11c3-de70-4180-a81d-53bf5731087f.png)

### How to reproduce the bug

I do not know why this happens so I do not know what steps to write, but I put the cable, terminal and interface for chests (storage interface). When I go far or go to another dimension the textures disappear. And I play with New Tardis Mod, and while the whole system is located in my "Tardis", it's a certain dimension of my own where I can go in and out, something like Nezer

### Expected behavior

Textures should not disappear, because I use facades and there, if there are no textures, everything is in holes

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/DoctorSigma/4842c35be7fd04c1433f66b9d2b359ed

**Comment by Technici4n** [comment]
Hi, we don't support rendering optimization mods. Can you try again without Magnesium or other such mods? If this fixes the issue, you'll have to report to them.

**Comment by DoctorSigma** [comment]
They are still disappearing, but at this moment when I do not have them, my friend has them .. I will try to write to the author of Magnesium

**Comment by Technici4n** [comment]
Did you or did you not try without Magnesium?

**Comment by Technici4n** [comment]
Going to close as it's probably a magnesium issue. Let me know otherwise.
