### ISSUE TITLE
Missing Ingredient Overlay is Wrong for REI for Shapeless Recipes

### ISSUE THREAD

**Issue by shartte** [AppliedEnergistics/Applied-Energistics-2#5724]
1.18.

It's unclear if this is an REI issue or ours.

![grafik](https://user-images.githubusercontent.com/1261399/144686687-531a895d-e0a7-4f24-a708-9ea6f6313ada.png)

**Comment by Mari023** [comment]
![2021-12-05_14 28 04](https://user-images.githubusercontent.com/38946771/144748572-2938d06e-f040-463a-8b45-02971bdc42e5.png)
This screenshot is just with REI installed, so this is definitely a REI issue.

**Comment by shartte** [comment]
https://github.com/shedaniel/RoughlyEnoughItems/issues/675
