### ISSUE TITLE
End cities are destroyed by meteorites

### ISSUE THREAD

**Issue by yu-re-ka** [AppliedEnergistics/Applied-Energistics-2#5725]
### Describe the bug

End cities are sometimes destroyed by meteorites

### How to reproduce the bug

Create a creative world with AE2, visit some end cities (`/execute in minecraft:the_end run teleport ~ ~ ~`, `/locate endcity`)

### Expected behavior

IMO meteorites should not be generated in the end

### Additional details

An example of an end city being damaged by a meteorite:

![image](https://user-images.githubusercontent.com/86169957/144706456-5080dbbd-908a-433a-9aa3-4db63810ee76.png)

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://termbin.com/90nk

**Comment by shartte** [comment]
Thanks for your report!

Can you please give me your world-seed and the location in the end where this occurred?
When I simply enter a world locally, there are no meteorites in the end.

**Comment by yu-re-ka** [comment]
seed: 4857117379606589205

```
/execute in minecraft:the_end run tp @s -4464 ~ 672
```

**Comment by shartte** [comment]
Yup, reproduced it in my dev env. Will fix this. What the fuck 😁
