### ISSUE TITLE
Autocrafting gets stuck

### ISSUE THREAD

**Issue by yu-re-ka** [AppliedEnergistics/Applied-Energistics-2#5726]
### Describe the bug

When starting an autocrafting job, it gets stuck under certain conditions.

### How to reproduce the bug

Prerequisite: A Minecraft 1.18 installation with AE2 10.0.0-alpha.1.

- Download the following world save: https://yaya.yuka.dev/public/AE2-test-world.tar
- Right-click the crafting storage to view the crafting status. Note that it is stuck. Cancel the crafting task.
- Open the crafting terminal and create a new crafting task for 11 Quartz Glass.
- Note how it gets stuck again.

### Expected behavior

11 Quartz Glass should be crafted and the crafting CPU should become available again.

### Additional details

![image](https://user-images.githubusercontent.com/86169957/144712697-1b5a7ce8-f981-4c55-a11e-636c373a4c24.png)
![image](https://user-images.githubusercontent.com/86169957/144712707-50dd3d73-6c20-408c-a1fb-010ec4c91662.png)

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://termbin.com/1dw3

**Comment by shartte** [comment]
Yeah, the molecular assembler is not producing the right amount of items (it only creates 1 quartz glass instead of 4).

**Comment by shartte** [comment]
Thanks a lot for the report. Will be fixed in the next alpha.
