### ISSUE TITLE
[1.18.0-Fabric] AE2's Meteor structure does not spawn when Repurposed Structures is on.

### ISSUE THREAD

**Issue by TelepathicGrunt** [AppliedEnergistics/Applied-Energistics-2#5727]
### Describe the bug

I was reported this bug on my github.
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/issues/162

However, I am having troubling finding exactly where in AE2 how it is associating the meteors to biomes to see if there is a conflict with my way of adding spacings/ configuredstructure<->biome associations to the chunk generator. What I do is grab the old entries from the map/multimap, add mine to it, and then set the field to that new map/multimap. It should not be causing any issue which is why I need to know what exactly AE2 is doing so I can narrow down what the conflict is. 
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/blob/4cdd3d9761389771d482046960d2c1a4399a1eb5/src/main/java/com/telepathicgrunt/repurposedstructures/RepurposedStructures.java#L103

Thank you in advance. I'll be trying to get AE2 into my RS dev environment if I can to debug more.

### How to reproduce the bug

Put on RS and AE2. Enter a world. Do locate command for meteor structure.

### Expected behavior

Returns a location for the meteor.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://gist.github.com/FreeFull/31dd81f0046be1d5ef20e556e70e3567

**Comment by shartte** [comment]
Yup, I am not sure on which end this issue occurs. Structures are still a bit of a mess.

We're using the Fabric API to add it here:
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/main/java/appeng/init/worldgen/InitBiomeModifications.java#L41

Since I adapted the Fabric API for 1.18, it's my fault either way if it's broken 😁

**Comment by TelepathicGrunt** [comment]
Issue was on my end with my noise setting deep copier code. Since dimensional allow/disallow configs was a huge request for RS but mojang decided multiple dimensions using the same noise setting shares that same instance of the noise setting for every world's unique chunk generator instances. The deep copy noise setting code I had was to solve that so I can add /remove structure spacing per dimension to allow the config to work properly as the alternative of moving the dimension allowing/disallowing to anywhere in structure gen would deadlock the world if attempted to be located in a disallowed dimension. My issue was I forgot to deep copy the configuredStructures field in structure settings class (mojmap)

**Comment by shartte** [comment]
Thanks for investigating this! For once, it wasn't my fault 😁

**Comment by red2blue** [comment]
This also happens on 1.17

can you release the fix for that as well?!
