### ISSUE TITLE
[1.18] Meteorites not spawning

### ISSUE THREAD

**Issue by red2blue** [AppliedEnergistics/Applied-Energistics-2#5733]
### Describe the bug

if Terralith 2 and AE2 are added, meteorites do not spawn in the world. 

### How to reproduce the bug

Add Terralith 2
/locate ae2:meteorites

### Expected behavior

Meteorites Spawning

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

n/a

**Comment by shartte** [comment]
Teralith is currently not supported because the mechanism of how worldgen datapack works: They completly replace the chunk generator, including all structure settings.

We'll investigate if we can port the hack we used in 1.17 forward to 1.18, but honestly, it's not the highest priority right now.

**Comment by shartte** [comment]
I've got reports that it actually works with the latest Teralith vevrsion, so I'll put this on hold until its reported again.

**Comment by red2blue** [comment]
Hmm it definitely doesn't work with my modpack and terralith is the only
biome controlling datapack/mod in it. My pack is Another Quality Modpack 2.
I had the same issue in 1.17. It was fixed after tech did some work but
then it stopped working again after a few updates.

**Comment by idkman2021** [comment]
this issue isn't solved
