### ISSUE TITLE
Crash with Wireless Terminal

### ISSUE THREAD

**Issue by TheJulianJES** [AppliedEnergistics/Applied-Energistics-2#574]
Something like #374.
If you right-click on the wireless terminal, switch to another item it will crash.
I'm playing on a server, maybe in the time it was a bit laggy, maybe the gui trys to open for another item, not for the wireless terminal.
I currently have OptiFine on my laptop, on my gaming pc I tried it without, still not working (crashing).
I also have ExtraCells2 installed, also crashes without.
Also portable cell, maybe [tested].

Version:
1.7.10 - AE2 rv2 alpha 28

Steps to reproduce:
1. Setup a server, maybe a bit laggy.
2. Right-click the wireless terminal.
3. Switch to another item/empty hand.
4. The wireless terminal gui will open shortly (no items and such).
5. Crash.

Crash report: http://pastebin.com/jp426z0k

**Comment by TheJulianJES** [comment]
#889 is maybe referenced.

**Comment by thatsIch** [comment]
probably resolved, closing
