### ISSUE TITLE
Compatible with Treasure 2

### ISSUE THREAD

**Issue by DoctorSigma** [AppliedEnergistics/Applied-Energistics-2#5741]
### Describe the bug

Hi! I'm playing with mod Treasure 2. Today, after updating this mod, I noticed a visual bug. When I throw a new item into the system (that is, items I retrieved after the update, old, once retrieved, items do not lag so) it visually "multiplies" as seen in the screenshots (1 screenshot I took immediately after putting the item in the system, and 2 2 seconds after that, I did not leave the terminal, and it does not double in the chest, but only visually in the terminal). It is placed through the storage bus in a vanilla chest.

![image](https://user-images.githubusercontent.com/93322905/145069843-2c8fa34a-2758-43f6-8052-5894d93c0fe8.png)
![image](https://user-images.githubusercontent.com/93322905/145069865-b58633ca-ed06-4650-bd20-825bfcb7af50.png)

### How to reproduce the bug

1) Make a storage system using a storage bus connected to a vanilla chest and a terminal.
2) Put the item from mod Treasure 2 in the system and wait 2 seconds (this works with items that can be obtained after the last update of the mode, ie old items that were obtained before the update do not reproduce)
3) See how the item reproduces ....

### Expected behavior

They should not reproduce

### Which minecraft version are you using?

1.16

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/DoctorSigma/ea84ea1e942541127827ad8577fd32a9

**Comment by Technici4n** [comment]
Hi, thanks for your report. This likely has to do with these items updating themselves while they are in the chest. However, this is not a critical issue, and the code was changed so much recently that trying to hunt the issue in 1.16 is likely going to be a waste of time. Should that occur again in MC 1.18, please open an issue.
