### ISSUE TITLE
Blocking Mode on machines does not work

### ISSUE THREAD

**Issue by ecatherman** [AppliedEnergistics/Applied-Energistics-2#5746]
### Describe the bug

Blocking mode seems to be not working for several machines including:
Induction smelter from Thermal Expansion
Energizing Orb from Powah

It seems to work fine on chests though.

Is there some sort of intake inventory that it should look at?

![image](https://user-images.githubusercontent.com/6530707/145130427-000c94b8-aae8-49c1-a2ae-2b4cdd9654d9.png)

![image](https://user-images.githubusercontent.com/6530707/145130526-fc4ffb22-ecdb-441a-81a2-34e0ed8cd44f.png)

![image](https://user-images.githubusercontent.com/6530707/145130923-8459b2af-1dbc-415a-a08d-3eb495d6f636.png)

### How to reproduce the bug

1. Setup an AE network with crafting storage.
2. put a interface on an induction smelter.
3. Add a recipe for invar and constantan
4. craft multiple sets of each at one time.
5. The interface will try to craft 2 recipes at the same time.

A. the energizing orb will allow you to insert as many items into it as you want but it can only craft with 1 at a time.
B. Place an energizing orb on an interface.
C. put in a recipe for energized steel.
D. try to craft more than 1 at a time.
E. The interface will insert many gold and iron stopping the craft.

### Expected behavior

The interface should wait for the input inventory to clear before inserting the next set.

### Additional details

I am using the OceanBlock Modpack by FTB Team version 1.10.1

### Which minecraft version are you using?

1.16

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/reGtxqxE

**Comment by Plet53** [comment]
A brief examination of the code tells me that blocking mode simply is not implemented at all. While the property is stored, it is never accessed outside of initialization of the interface menu.

**Comment by Technici4n** [comment]
Fixed in 1.18.
