### ISSUE TITLE
Opening AE2 pattern terminal freezes server for prolonged periods of time

### ISSUE THREAD

**Issue by Gombado** [AppliedEnergistics/Applied-Energistics-2#5752]
### Describe the bug

The freeze lasts about 2 minutes and occurs for all players on the server (currently 20 people- like an endless loop sort of thing?) - happens on both 'fresh' and existing ae2 systems regardless of player (happens for each player on the server). 

It happens only when opening a pattern terminal, doesnt happen for non pattern terminals. Restarting the server does not solve the issue.

### How to reproduce the bug

Trigger that caused this situation is unknown. Now that the faulty situation has occured the freezing of the server occurs every time anyone opens a pattern terminal.

### Expected behavior

The server to not freeze when you open the pattern panel

### Additional details

Multiplayer server 
ATM6 1.8.10 
appliedenergistics2-8.4.4
-ae2extras-1.3.1-1.16.5

forge-1_16

### Which minecraft version are you using?

1.16

### On which mod loaders does it happen?

Forge

### Crash log

-

**Comment by Technici4n** [comment]
Hi, would it be possible for you to generate a spark profile when this issue occurs? This will help track down the performance issue.

**Comment by Gombado** [comment]
> Hi, would it be possible for you to generate a spark profile when this issue occurs? This will help track down the performance issue.

Hey @Technici4n 

Attached youll find the logs you requested. You can also find the profile on: https://spark.lucko.me/r4xWgbWvAz

Note that we discovered that some players (right after restart) could use the pattern terminal without issue. For most players however the bug as logged occurs. 

Hope this helps / happy bughunting!

[sparkprofile-1 Issue 5752.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/7686503/sparkprofile-1.Issue.5752.zip)

**Comment by Gombado** [comment]
![image](https://user-images.githubusercontent.com/34801187/145430794-fa53bc3f-54ee-4f3a-99d9-01fd57933e78.png)
![image](https://user-images.githubusercontent.com/34801187/145430861-3c05f8b8-4d60-42ba-8dfc-2498e3a01654.png)

Some novice looking through the logs.. hope it helps!

**Comment by Technici4n** [comment]
Hi, this is indeed an issue with Polymorph I think? I would suggest reporting this to them (https://github.com/TheIllusiveC4/Polymorph/issues), and removing the mod as a temporary fix. Hopefully that fixes the lag issue! :)

**Comment by Gombado** [comment]
> 

Yeah I was just going to note that in ATM6 1.8.11 (one version after the one we use now) they removed the interaction of poly and ae2 (and rs)

![image](https://user-images.githubusercontent.com/34801187/145433041-fb9c4100-bd41-4737-addb-5818510b5cdd.png)

**Comment by Technici4n** [comment]
Glad that this is solved for you. And thanks for the kind words. :smile:
