### ISSUE TITLE
Partitions are completely ignored by the system

### ISSUE THREAD

**Issue by TheDyreBanana** [AppliedEnergistics/Applied-Energistics-2#5754]
### Describe the bug

ME Systems completely ignore any partitioning applied to a cell and just put items into whatever cell is first in the first slot in the drive. If you assign dirt to a cell and another nothing, it will put all items into whatever cell comes first. 

 
![image](https://user-images.githubusercontent.com/59154209/145577826-198fb0d6-5db1-4351-9626-7bd8441739fb.png)

![image](https://user-images.githubusercontent.com/59154209/145577897-e49801e1-0bce-47c9-ae5b-a42877004c4b.png)

### How to reproduce the bug

Just apply partitioning to any ME Cell, fluid or item doesn't matter.  

### Expected behavior

That the system would take partitioning into account when storing items/fluids and direct items to their appropriate cells. 

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

none

**Comment by shartte** [comment]
I thought I had tested this. Obviously I was wrong 😬 
I will look into it.
