### ISSUE TITLE
terminal Game Crash 1.18 forge

### ISSUE THREAD

**Issue by xXxCrepperBoyHDxXx** [AppliedEnergistics/Applied-Energistics-2#5755]
### Describe the bug

the game crashs wen i open the terminal

### How to reproduce the bug

just open the terminal and the game crashs

### Expected behavior

the terminal is opening and i can see my items

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/AiA7ub5H

**Comment by TheDyreBanana** [comment]
this also happens with the ME chest too
