### ISSUE TITLE
Formation plane doesn't function

### ISSUE THREAD

**Issue by TheDyreBanana** [AppliedEnergistics/Applied-Energistics-2#5758]
### Describe the bug

Formation plane just doesn't function at all. 

### How to reproduce the bug

Place a formation plane and configure it. 

### Expected behavior

That the formation plane would place the blocks. 

### Additional details

forge 38.0.17
applied energistics 10.0.0-alpha.4 
jei 9.0.0.40 
JEP 1.2.2
JER - 0.13.1.136

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

none

**Comment by TheDyreBanana** [comment]
ignore this im just stupid and forgot how it worked

**Comment by glmdev** [comment]
For people (like me) arriving here from a search engine, the formation plane only places items/blocks when they enter the network. It will not draw from existing storagef.
