### ISSUE TITLE
Minecraft 1.18.1 forge

### ISSUE THREAD

**Issue by Thomasasia** [AppliedEnergistics/Applied-Energistics-2#5759]
### Describe the feature

Please update to 1.18.1 for forge. :-)

### Reasons why it should be considered

Important!

**Comment by XFactHD** [comment]
First of all, don't beg modders to update, it's a dick move.

Secondly minor updates like this are binary compatible in most cases, which is also the case for 99% of mods in this case. Please check if something is actually broken before annoying modders about a minor update.

**Comment by Technici4n** [comment]
> First of all, don't beg modders to update, it's a dick move.

It's perfectly fine here. Not what I call begging.

> Secondly minor updates like this are binary compatible in most cases, which is also the case for 99% of mods in this case. Please check if something is actually broken before annoying modders about a minor update.

I believe we need to update our mods.toml file for ae2 to work in 1.18.1, which I suspect @Thomasasia already noticed.

So @XFactHD your message is very uncalled for, if we are annoyed we will say it ourselves. And we are not.

@Thomasasia Yes we will publish a 1.18.1 release soon. :)

**Comment by Patronos** [comment]
We are all very excited about MC 1.18 and really enjoy using one of the best mods (AE2) existing. Even if my comment won't validate as constructive - I nonetheless want to thank everyone involved for this great mod and the efforts that went into it. Thank you.

**Comment by shartte** [comment]
I thought I had actually already done this?

**Comment by shartte** [comment]
Yeah, no, Forge decided to bump their major version for 1.18.1.
We're compatible with 1.18.1, but not with Forge 39 :-P
We cannot support both in my opinion in that case and will probably just bump to minimum of 1.18.1.

**Comment by Yung719** [comment]
So we can’t change the toml to use ae2 in 1.18.1?

**Comment by shartte** [comment]
Try the latest alpha, it should work. I just forgot to close this issue.

**Comment by shartte** [comment]
Should be fixed in 10.0.0-alpha.5 for Forge
