### ISSUE TITLE
Can not autocraft fluids

### ISSUE THREAD

**Issue by DrummerMC** [AppliedEnergistics/Applied-Energistics-2#5761]
### Describe the bug

The autocrafting process for fluids can't be startet if  the fluid is the final result. If the fluid only used as substep it can be autocraftet.

### How to reproduce the bug

Make an pattern that produce a fluid. Example:
![image](https://user-images.githubusercontent.com/7688760/145678865-1afd1c52-c463-4bac-a65c-43426570f075.png)
Insert the pattern in an Pattern Provider
Try to craft the fluid -> Nothing happens (no dialog for the amount is opening)
![image](https://user-images.githubusercontent.com/7688760/145678946-f62ddfb7-c649-45a8-91a1-4419dc019620.png)

### Expected behavior

Fluids can be autocraftet

### Additional details

Version: 10.0.0-alpha.5

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/4BbmQK4R

**Comment by shartte** [comment]
Fixed in aa71cc14fffadfe134db98dffce1408571c2a718

**Comment by shartte** [comment]
Please note that the amount entry widget is currently in Fabric fluid units, which kinda sucks since 81000 = 1 bucket.
We'll work on that in #5712

Oh, and also: good seeing your name pop up on github 😁
