### ISSUE TITLE
TechReborn fluid Cells compat

### ISSUE THREAD

**Issue by yu-re-ka** [AppliedEnergistics/Applied-Energistics-2#5767]
### Describe the feature

I would like to be able to
- store/retrieve fluids from TechReborn Cells in the ME system by right-clicking in the terminal
- Substitute cells in crafting recipes with the respective fluid

### Reasons why it should be considered

Working with TechReborn fluid cells is a hassle without compat. The only other way I found involves setting up an export bus, dispenser and annihalation plane to convert fluid cells to the respective fluids.

**Comment by Technici4n** [comment]
Both of these features unfortunately require TR cells to support the fabric transfer API, it's on them to fix.

**Comment by Technici4n** [comment]
Going to close this as this needs work on TR's side first, then we can look into `Substitute cells in crafting recipes with the respective fluid` once they support the fabric fluid API.
