### ISSUE TITLE
TechReborn rolling machine compat

### ISSUE THREAD

**Issue by yu-re-ka** [AppliedEnergistics/Applied-Energistics-2#5768]
### Describe the feature

It would be great if we could set up autocrafting for the rolling machine from TR, which has crafting patterns like a crafting table.

### Reasons why it should be considered

Otherwise there is no way to automate the rolling machine, because there is no way to place the items in the correct crafting slots.

**Comment by xanthian** [comment]
You can do it.. if you have many many Rolling machines :D

**Comment by shartte** [comment]
On fabric it's possible to add this in an addon/compat-mod that targets AE2/TR.
Essentially it'd require some form of API from TR to set the recipe on the rolling machine, unless the only requirement is to place the items in the right slots. Then just provide ICraftingMachine via the API Lookup for the TR rolling machine and handle the incoming crafting job:

We're extremely unlikely to provide this functionality in AE2 directly, so I'll close this issue for now.
