### ISSUE TITLE
Textures not work

### ISSUE THREAD

**Issue by SpartanDraco** [AppliedEnergistics/Applied-Energistics-2#5785]
### Describe the bug

the textures in 1.18.1 and 1.18 do not work, both the terminal and the hard disk storage come out without textures when you place the block

### How to reproduce the bug

place the block
![Sin título](https://user-images.githubusercontent.com/11298827/145738802-4657ce12-8dab-438c-9df6-2cc3b7c90147.png)

### Expected behavior

let the textures be seen 

### Additional details

let the textures show, I say

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

it is not a code error

**Comment by mindforger** [comment]
your report is incomplete, please check the template and add exact versions used and add a modlist or a force crashlog

**Comment by xanthian** [comment]
> ### Describe the bug
> the textures in 1.18.1 and 1.18 do not work, both the terminal and the hard disk storage come out without textures when you place the block
> 
> ### How to reproduce the bug
> place the block ![Sin título](https://user-images.githubusercontent.com/11298827/145738802-4657ce12-8dab-438c-9df6-2cc3b7c90147.png)
> 
> ### Expected behavior
> let the textures be seen
> 
> ### Additional details
> let the textures show, I say
> 
> ### Which minecraft version are you using?
> 1.18
> 
> ### On which mod loaders does it happen?
> Fabric
> 
> ### Crash log
> it is not a code error

If this is Fabric, and you are using Sodium, install Indium.

**Comment by mindforger** [comment]
@xanthian 
>If this is Fabric, and you are using Sodium, install Indium.

that is why i asked for the modlist, because people forget/don't care to add it and a guessed answer would bloat the issue otherwise

**Comment by Technici4n** [comment]
Install indium indeed. (This type of issue is frequent and the answer is always the same, so don't hesitate to give this answer directly to avoid useless back-and-forth! :))

**Comment by SpartanDraco** [comment]
> @xanthian
> 
> > If this is Fabric, and you are using Sodium, install Indium.
> 
> that is why i asked for the modlist, because people forget/don't care to add it and a guessed answer would bloat the issue otherwise

I did it and it was fixed, I did not get other similar problems in the search engine for which I made the ticket, honestly indium should be an optional requirement in curseforge for fabric so that people do not come and create tickets, even so, the texture of the panel data is shifted to the left
