### ISSUE TITLE
certus_quartz _crystal Causing all clients on the server to crash. 

### ISSUE THREAD

**Issue by Penguax** [AppliedEnergistics/Applied-Energistics-2#5786]
### Describe the bug

Clients crash for unknown reasons when obtaining certus_quartz_crystals. The client will crash and end up having other clients crash too.

### How to reproduce the bug

Having, holding, or using certus_quartz_crystal in player inventory.

### Expected behavior

No crash/ use for regular recipies.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://paste.corebot.dev/gesusizipu.makefile

**Comment by Penguax** [comment]
Server doesn't recognize any issues and only see's players disconnect, this is occurring client-side only. 
This is what the server saw during one of the crashes. https://paste.corebot.dev/onipaxaxux.css

**Comment by shartte** [comment]
This is a crash in 

> at backtools.client.ConfigHandler.isItemEnabled(ConfigHandler.java:37)

Please report it to whatever mod that is.
