### ISSUE TITLE
Client crash "Non [a-z0-9/._-] character in path of location: ae2:MaterialItem[engineering_processor_press]"

### ISSUE THREAD

**Issue by mosharky** [AppliedEnergistics/Applied-Energistics-2#5787]
### Describe the bug

I instantly crashed after opening a Sky Stone Chest and clicking on an Engineering Processor Press

### How to reproduce the bug

1. Open Sky Stone Chest
2. Click on Engineering Processor Press
3. Crash?
4. ????
5. Profit

### Expected behavior

Being able to drag and drop the item into my inventory

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://gist.github.com/mosharky/ac992378bbcf3472b5243b240ba9dd91

**Comment by mindforger** [comment]
please use the search first, there has been reported the identical issue just a few hours ago

Duplicate https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/5786
