### ISSUE TITLE
Can't seem to be able to disconnect fluix\smart cable connections

### ISSUE THREAD

**Issue by Zarvera** [AppliedEnergistics/Applied-Energistics-2#5795]
### Describe the bug

On the latest Fabric version for 1.17, i can not dosconnect said cabled from each other and other machines by using Nether Quartz Wrench, leading to unnecessarily convoluted and spacious cabling. 
Documentation states that wrenches are capable of removing individual connections, so unless i'm grossly misunderstanding it, it's a bug.

### How to reproduce the bug

Craft wrench, right click cable connections to other cables and blocks.

### Expected behavior

I expect cables to detach from other cables\blocks on the r-clicked side.

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/w2qtkmz9

**Comment by xanthian** [comment]
Shift + R.Click.

**Comment by Technici4n** [comment]
That's not possible, but you can place cable anchors on the connection to prevent the cables from connecting.
Where did you see that in the documentation? We have to fix it, it's not correct.

**Comment by Zarvera** [comment]
Ah, anchors it is. Thanks.
As for documentation - https://appliedenergistics.github.io/features/simple-tools/wrench

> Useful for rotating blocks, _and removing individual parts from cables._

**Comment by Technici4n** [comment]
A part is a device you attach on a cable, like a storage bus or a quartz fiber. Hence the term "multipart cables".

**Comment by Zarvera** [comment]
Understood.
Since you're here, should i open issue about Crafting Pattern being simply destroyed when trying to encode with MI recipes involving liquids, or is it known\unfixable? Like "Coke Dust + 100 mB Water in a Mixer = 222 18/81 mB of Synthetic Oil". It's probably due to its queer liquid fraction measures i guess.

**Comment by Technici4n** [comment]
Definitely open an issue about that. Make sure to test with the latest alpha before reporting though (alpha 7).

**Comment by Zarvera** [comment]
Alright, will do.
