### ISSUE TITLE
Auto-Crafting Item Quotas

### ISSUE THREAD

**Issue by broman** [AppliedEnergistics/Applied-Energistics-2#5799]
### Describe the feature

Simple enough, my suggestion is a way to instruct the ME Network to automatically craft an item using available crafting resources until X items are present in the network. For example:

- I have a molecular assembler and pattern providers set up with patterns to create Fluix Cable from scratch
- As fluix cable is always useful to have on-hand, I would instruct the ME Network to automatically place a crafting order for 10 fluix cables whenever there are fewer than 10 fluix cables in the network.
- This way, I am never stuck waiting for fluix cables to finish crafting. I remove 5 fluix cable to connect a new machine to the network, and the next time I go into my ME storage there are 15 fluix cable waiting for me without me needing to remember to schedule a crafting order.

I would also suggest some sort of "ME Scheduling Terminal" to schedule these types of quotas.

### Reasons why it should be considered

The "basic" items of any mod become tedious to craft the later a player gets into the game, and AE2 does a wonderful job of making this tedium easier. However going a step further to remove the consideration of always making sure these items are crafted is a great step in the direction of increasing automation. As this mod goes a very long way in taking care of tedium for the player I feel as though completely abstracting away the chore of crafting and processing would be the logical next step to take in the AE2 auto-crafting pipeline.

**Comment by Technici4n** [comment]
This is already possible:
If you place an ME Interface with a crafting card, it will autocraft items. And if you place a storage bus on the interface, you will be able to access these items.

**Comment by broman** [comment]
Will it automatically craft a certain amount of items if they are not present in the ME system? I’m confused

**Comment by Technici4n** [comment]
Yes, just try it. :)
