### ISSUE TITLE
Redstone Comparator Recipe Issues (Not sure if you creating duplicate recipes or not. 

### ISSUE THREAD

**Issue by KaneHart** [AppliedEnergistics/Applied-Energistics-2#5801]
### Describe the bug

So I'm trying make a Comparator with this recipe:
![image](https://user-images.githubusercontent.com/425853/146459881-4f50f667-3411-458d-b671-cd023f34e27b.png)

Now here is what the advance tool tip shows:
![image](https://user-images.githubusercontent.com/425853/146459950-1b3919c5-9ecc-483a-9557-d681d9b5137a.png)

### How to reproduce the bug

Use a Certus Crystal and craft a Comparator.

### Expected behavior

Either the Comparator would be craftable with the AE2 Crystal or the extra bloat/clutter gets removed. 

### Additional details

Hope this enough to help figure it out. 

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

x

**Comment by Technici4n** [comment]
This is MI listing the tags of the item itself, and has nothing to do with the tags accepted by the recipe, or AE2 in general.
