### ISSUE TITLE
Fluid Autocrafting is not working in 1.18

### ISSUE THREAD

**Issue by stearnsbq** [AppliedEnergistics/Applied-Energistics-2#5802]
### Describe the bug

Autocrafting with fluids seems to be broken, I'm trying to autocraft lubricant from MI and the pattern provider refuses to put any fluid into the machine. For testing I've tried creating a dummy pattern that just puts a fluid into a tank and expects lubricant and the tank will not be filled with creosote. 

IMAGES:
https://i.imgur.com/tKS1M4T.png

https://i.imgur.com/qh30RK3.png

### How to reproduce the bug

1. Create a pattern that uses a fluid to craft some other fluid
2. Put pattern into a pattern provider facing a machine or fluid container
3. Request to craft fluid
4. Fluid will not be put into a container

### Expected behavior

Fluid should be put into the container / tank / machine. 

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/5UFTeact

**Comment by Technici4n** [comment]
Can't reproduce, sorry. Consider trying with the latest alpha (7).

![image](https://user-images.githubusercontent.com/13494793/146618631-ad0d9962-49fc-4096-af17-d0951add2a08.png)
