### ISSUE TITLE
Bug with the autocrafting processors

### ISSUE THREAD

**Issue by Dogsteeves** [AppliedEnergistics/Applied-Energistics-2#5803]
### Describe the bug

The processors aren't going into the interface properly in the first slot. I have 64 logic processors but won't go in the first slot, only the 2nd onward.

https://user-images.githubusercontent.com/34611694/146464741-e1ba0a74-a893-4d6c-9bd9-a90b1ce6c6c6.mp4

### How to reproduce the bug

have 64 Processors in your system and try and storage bus them inside a ME interface

### Expected behavior

I expected the interface to work as intended for it to hold 64 stack of each processor easily

### Which minecraft version are you using?

1.16

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/Nxfgp6Ab

**Comment by shartte** [comment]
Confirmed this problem also exists on 1.18
