### ISSUE TITLE
autocrafting bug with processors 

### ISSUE THREAD

**Issue by rav233PL** [AppliedEnergistics/Applied-Energistics-2#5805]
### Describe the bug

the error occurs only when creating processors interface puts printed logic / engineering / calculation processor into redstone slot and the whole creation process stops I tried with a flat interface and with normal on all sides and nothing came of it I attach screenshot AE version is 8.4.3 the same happens on 8.4.4 forge version is 36.2.8 MC 1.16.5

### How to reproduce the bug

make pattern of processor and put into interface of inscriber begin autocrafting of it

### Expected behavior

![2021-12-17_13 20 48](https://user-images.githubusercontent.com/96295416/146546306-7f0218c4-7e3c-4804-9c07-8d509b89292c.png)

### Which minecraft version are you using?

1.16

### On which mod loaders does it happen?

Forge

### Crash log

c

**Comment by shartte** [comment]
Placing items into the inscriber from the outside is side-sensitive. Please see https://appliedenergistics.github.io/features/me-network/powered-machines/inscriber
