### ISSUE TITLE
Incompatibility with Modern Industrialization

### ISSUE THREAD

**Issue by Wolfy8198** [AppliedEnergistics/Applied-Energistics-2#5807]
### Describe the bug

When you place an energy acceptor next to a block that uses/stores/creates energy from the Modern Industrialization mod, it causes my world to crash. I've tried to enter afterwards but it keeps crashing. The Energy Acceptor will show it has 0/infinity energy, and the bar will be full.

### How to reproduce the bug

1. Install the latest versions of Modern Industrialization and Applied Energistics 2
2. Open singleplayer world
3. Place any block that generates energy from Modern Industrialization
4. Place an Energy Acceptor next to it.

### Expected behavior

Not sure, was hoping maybe that since Modern Industrialization and Tech Reborn both use EU, they could be used as energy sources for Applied Energistics machines. I'm just trying to get major bugs solved before I release the modpack for my server.

### Additional details

![Screenshot 2021-12-17 172014](https://user-images.githubusercontent.com/64490202/146614582-f174584a-adfe-4ca6-94a1-6604e6b8975e.png)
This is what it showed from the Not Enough Crashes mod

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://bytebin.lucko.me/GYuzpEY1Lw

**Comment by Technici4n** [comment]
Report to AE2 additional opportunities. I'd heavily recommend to avoid a mod that messes with our internals like that and learn to use channels instead.
