### ISSUE TITLE
[1.16.5] Can't craft silicon

### ISSUE THREAD

**Issue by BCBAdrian** [AppliedEnergistics/Applied-Energistics-2#5809]
### Describe the bug

I can't craft silicon. There is no recipe. Also, if you take it from the creative, it does not work anywhere, for example, in the chisel. Accordingly, if it does not work in the chisel, it is impossible to create any processor.
The RefinedStorage modification is installed, but silicon from it is also not suitable!

### How to reproduce the bug

1. Install the mod on 1.16.5.
2. We understand that silicon cannot be crafted.

### Expected behavior

There is no recipe for silicon. If u  take it from creative - it simply does not work anywhere. 

### Which minecraft version are you using?

1.16

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/BCBAdrian/3871d4de47f9f20c349201003da237bb

**Comment by Technici4n** [comment]
Looks like a recipe bug in your modpack, I'm pretty sure it works correctly with AE2 alone.
