### ISSUE TITLE
Should we add back the option to disable channels?

### ISSUE THREAD

**Issue by Technici4n** [AppliedEnergistics/Applied-Energistics-2#5810]
It's possible. Do you want it?

**Comment by Shnupbups** [comment]
Yes please! Channels are are neat mechanic, but having more options is always good, and I'm sure some packs would want them disabled. I know I for one sometimes just can't be bothered with channels haha

**Comment by shartte** [comment]
What about a multiplier instead? At least it would somehow still make the controller/smart cables somewhat useful :-D

I am thinking about a config setting to make everything have x2 or x4 capacity (i.e. ad-hoc networks now supporting 16 or 32 devices, dense cable 128 or 256 channels).

**Comment by Shnupbups** [comment]
Yeah, a channel multiplier would be great! Though perhaps setting it to `0` could disable channels entirely still.

**Comment by embeddedt** [comment]
It would be useful for Fabric in particular, as Refined Storage isn't available. Players who are new to modded can eventually be eased into using channels, but having an option to introduce them to AE2 features without the complexity of channels would be ideal.

The multiplier would also work as it could always be set to a very high value.

**Comment by Ommina** [comment]
I have grown to love channels.  Nonetheless, yes, I wholly support the idea of an option to disable them or employ some power-of-two alternate.

**Comment by DFNanaIII** [comment]
> It's possible. Do you want it?

it serves well that we can activate or deactivate them but that it is the choice of people
