### ISSUE TITLE
Make oriented pattern provider texture more clear

### ISSUE THREAD

**Issue by ramidzkh** [AppliedEnergistics/Applied-Energistics-2#5817]
### Describe the feature

The pattern provider should indicate which way it's going to push things, like how the interface did before pattern providers were added

### Reasons why it should be considered

tell me which way this is oriented

![image](https://user-images.githubusercontent.com/19631324/146660320-a4071fa7-9cc9-4039-a039-cc667c1e6a3a.png)

(it's probably up but i just wrench it until it works anyway)

**Comment by shartte** [comment]
This is actually a bug, it worked before in 1.17 but stopped working in 1.18 (since i broke it)

**Comment by Technici4n** [comment]
Was fixed in a direct commit to master.

**Comment by shartte** [comment]
2ab0eb6844f4288e0e248e013498b3a428c33fa7
