### ISSUE TITLE
AE2 API Maven Artifacts have duplicate classes

### ISSUE THREAD

**Issue by ProjectET** [AppliedEnergistics/Applied-Energistics-2#5828]
The specific artifact that I was using had duplicate classes, using fabric loom it remaps one of the classes and leaves the other in intermediary.

The specific maven artifact in question is: `appeng:appliedenergistics2-fabric:10.0.0-alpha.7:api`

![Capture](https://user-images.githubusercontent.com/24382197/146739124-f50afdbc-4bbc-4e71-ad76-9046ff08538f.PNG)
Example of one of the non remapped duplicate classes

**Comment by ProjectET** [comment]
EDIT: After looking through the various artifacts, this seems to only affect the api. The duplicated classes are of compiled class files and uncompiled java files

**Comment by shartte** [comment]
Yeah that has always been like that. The api jar was always simultaneously a source jar and that is intentional.
Loom has a lot of remapping issues overall :| The only thing you can kinda do is detach the source and rely on the decompiled IntelliJ source.
