### ISSUE TITLE
[1.17] Cauldron wont give fluid output

### ISSUE THREAD

**Issue by Iluminatiko44** [AppliedEnergistics/Applied-Energistics-2#5829]
### Describe the bug

If you have a cauldron filled with lava it wont give any output to the ME-System.
I tried it with import/export/storage bus, interface and nothing worked.
Had fluid drives and terminal.

### How to reproduce the bug

1. Get a working ME-System with fluid components
2. Get a cauldron filled with lava
3. Try getting it out with some export buses or something similar
4. Does not wor
![2021-12-20_12 44 14](https://user-images.githubusercontent.com/49609323/146764433-642d4ccc-7e16-4783-a854-5fda7474f6df.png)
k

### Expected behavior

It should get the lava out of the cauldron into the System.

### Additional details

Modlist in the crash log.

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/Iluminatiko44/124fd44c94229b0a5b7224c9801b23f0

**Comment by shartte** [comment]
Please try what happens if you put an acceleration card into the import bus.

The import bus is not able to import a full bucket per tick, but the cauldrons can only be fully drained or not drained at all, which may lead to this issue.

**Comment by Iluminatiko44** [comment]
So i tried with 4 Accelaration card in my survival world, with and without a filter in the import bus
Still doesnt work ;(
![2021-12-20_13 30 11](https://user-images.githubusercontent.com/49609323/146767465-e77bcd28-60a8-491c-bb2f-98da78dafda9.png)
![2021-12-20_13 30 14](https://user-images.githubusercontent.com/49609323/146767480-41516041-9e65-4297-a680-f449056d5fdf.png)
![2021-12-20_13 31 24](https://user-images.githubusercontent.com/49609323/146767559-8dd4431d-fb9e-43ce-9af8-4f1127fa0061.png)

**Comment by Iluminatiko44** [comment]
There are also enough channels left

**Comment by shartte** [comment]
Oh _you are on Forge_! 

I don't think this works on Forge at all, sadly.

Sorry, I missed that initially.

**Comment by Iluminatiko44** [comment]
_And now what?_
Will it get added soon?

**Comment by shartte** [comment]
We are not adding anything to Cauldrons. Forge doesn't add Fluid transfer support to it, so we can't use it.
