### ISSUE TITLE
FPS Get low

### ISSUE THREAD

**Issue by xXxCrepperBoyHDxXx** [AppliedEnergistics/Applied-Energistics-2#5836]
### Describe the bug

When i search in the me somthing an there are a lot of item then it the FPS will drop 

### How to reproduce the bug

Get A Lot of items in the ME and than search somthing

### Expected behavior

No FPS Droping

### Additional details

https://streamable.com/cxb6i9

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/gETTnsYa

**Comment by Technici4n** [comment]
Hi, can you please try again without the legendary tooltips mod and report it to them if that fixes the issue?

**Comment by xXxCrepperBoyHDxXx** [comment]
it has made no difference the fps drops with it and without it

**Comment by Technici4n** [comment]
Ok, could you provide a [spark profile](https://www.curseforge.com/minecraft/mc-mods/spark) of your client to help us track the performance issue then? Thanks. (The command starts with `/sparkc`, not sure about the rest).

**Comment by xXxCrepperBoyHDxXx** [comment]
do you mean that https://spark.lucko.me/s1Px1lk1g6

**Comment by Technici4n** [comment]
Not exactly. That is a profile of your server (for TPS issues), but I need the client profile for FPS issues.

**Comment by shartte** [comment]
Yeah, I can reproduce low FPS with a drive full of enchanted items, basically. You alreay have very low fps to begin with, making it worse for you at the moment.

**Comment by shartte** [comment]
Closing this in favor of #5924
