### ISSUE TITLE
Autocrafting with LevelEmitter says missing Items

### ISSUE THREAD

**Issue by DrummerMC** [AppliedEnergistics/Applied-Energistics-2#5847]
### Describe the bug

If I have multiple crafting steps and using a level emitter to craft it sometimes says missing items for level emitter craftable items

### How to reproduce the bug

Setup a LevelEmitter with Crafting Card and item to "Sand"
![image](https://user-images.githubusercontent.com/7688760/146989289-16a7ab89-6cb5-4873-8971-96ec32374e78.png)
Add a glass Pattern to a Furnance
![image](https://user-images.githubusercontent.com/7688760/146989354-73233623-e731-48c3-aa99-7bbc06cd4d45.png)
Add a quartz glass pattern
![image](https://user-images.githubusercontent.com/7688760/146989467-b32b1b9d-fcfd-4763-8bf7-a6c716b91801.png)
Try to craft quartz glass
![image](https://user-images.githubusercontent.com/7688760/146989780-afef099d-4eed-43ef-b510-592c1d581491.png)

### Expected behavior

Sand is not missing

### Additional details

Version: 10.0.0 alpha 8

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

none

**Comment by shartte** [comment]
Does the sand show up as craftable in your terminal?

**Comment by DrummerMC** [comment]
yes, and i found out that this only happen if quartz dust is missing

**Comment by shartte** [comment]
Oh I have a hunch where this is coming from, I think the screen checks in the network storage whether items are actually missing or not, so emittable items will always show up as missing even though they're not. Thanks for reporting this!
