### ISSUE TITLE
Questing about config for making a new custom modpack?

### ISSUE THREAD

**Issue by mariodk** [AppliedEnergistics/Applied-Energistics-2#586]
i am making a new modepack
based on tech mods around mekanism,thermal expansion and afew others(no IC2 or gregtech)
since this modpack will be a Tech modpack for newbies 
but back to my questing
i want to know if it is possible to make AE2 to be more like AE1 via configs
since i dont like these channels system for my modpack
or atleast having unlimited Channels on a normal ME cable so you dont have to make the big onces
and also remove them

basely i want to make AE2 in my modpack to be like AE1 for 1.7 with multiblock for busses and so on 

so like if you making a big barrel room and want storage busses on each you are not limited to just 8 busses/barrels on the normal cable
i want to know if that is possible to turn off that channel system via config

**Comment by asgdfagdsfg** [comment]
It is NOT possible to "disable" channels, without breaking the mod. You guys are liars and should punch yourself in the balls for ruining a great mod like AE1!
Just give the normal glass cables 1 million channels, and we can finnally play this mod, in a GOOD way again... All this "alien meteor press throwing crystals into puddles stupidity" is disliked by pretty much everyone who knows it. I am FAIRLY certain, that most people that write here, never even played AE1, and can't even compare this "crap", to the "gold" we used to have...
