### ISSUE TITLE
Enable IStorageMonitorableAccessor for the blocking mode of Pattern Provider

### ISSUE THREAD

**Issue by DoremySwee** [AppliedEnergistics/Applied-Energistics-2#5860]
### Describe the feature

Add a new option for Blocking mode: Use IStorageMonitorableAccessor to monitor the content of aimed container.

The result would be: Greatly Simplifying tons of automation, of which Draconic/Thaumic Fusion and CraftingCore (ExtendedCrafting) are representative.

### Reasons why it should be considered

These automation, used to be challenging for most of the players, were considered as a major automation theme in the past few years. 
However, when it comes to the current AE2 society, most of players are already very familiar with these automation:
 the method of blocking some cobblestone inside the aimed container to block the following ingredients
 are no longer interesting.
These parts of automation now become redundant, and they makes automation inefficient in not only in-game timing (building and using) but also calculating resources.

On the other hand, by adding this feature, more efficient design can take place, for instance:
 4gt packaging item into one cell,     10Hz AE2 based piano (Note Block),          Instant item sorting while having the blocking mode easily worked.

**Comment by Technici4n** [comment]
I'm a bit confused. This is already supported in 1.18 as far as I know?

**Comment by Technici4n** [comment]
Closing for now as I think it's resolved.

**Comment by DoremySwee** [comment]
> Closing for now as I think it's resolved.

I haven't find this out on 1181, is it still full of unexpected behaviour?

**Comment by Technici4n** [comment]
> I haven't find this out on 1181, is it still full of unexpected behaviour?

What does this mean?

**Comment by DoremySwee** [comment]
> > I haven't find this out on 1181, is it still full of unexpected behaviour?
> 
> What does this mean?

![image](https://user-images.githubusercontent.com/66953201/147301120-abc269d7-5131-4d37-ab7a-d778041c72eb.png)
The PatternProvider sends items all the time no matter whether the Interface and chest in the left has items

That is, It's not yet actually supported in 1.18.1, as far as I know.

**Comment by shartte** [comment]
Oh, I see your point. `IStorageMonitorableAccessor` is not directly supported, that is correct. We only push directly into the target inventory of the interface. You could say `IStorageMonitorableAccessor` is not supported _at all_ by pattern providers at the moment.

**Comment by Technici4n** [comment]
`IStorageMonitorableAccessor` is supported by the pattern provider.

**Comment by Technici4n** [comment]
Blocking mode only blocks when the inventory contains one of the inputs of the pattern now.
It does actually work with only 1 CPU, but it fails the moment you start adding co-processors because the storage bus only updates its cache once per tick.

**Comment by shartte** [comment]
@DoremySwee Sorry for the confusion, and thank you for your report.
We're working on a potential fix for this.
