### ISSUE TITLE
90% of models is unable to load 1.18.1 fabric

### ISSUE THREAD

**Issue by TheBeautyLlama** [AppliedEnergistics/Applied-Energistics-2#5864]
### Describe the bug

90% of models is unable to load
![изображение](https://user-images.githubusercontent.com/84794955/147271544-29cda8a7-04f2-4c22-9fc8-4b9b77838035.png)

### How to reproduce the bug

1.18.1 ae2 latest fabric build (built from source)
Fabric API 0.44.0+1.18

### Expected behavior

loaded block models

### Additional details

MultiMC Log: https://paste.ee/p/9qlp8

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://paste.ee/p/9qlp8

**Comment by shartte** [comment]
If you are using Sodium, you'll also need to use Indium (due to Sodium not offering Fabric's full rendering API)

**Comment by TheBeautyLlama** [comment]
> If you are using Sodium, you'll also need to use Indium (due to Sodium not offering Fabric's full rendering API)

sodium is disabled

loaded mods is fabric api and ae2

**Comment by shartte** [comment]
My apologies, I just scanned immediately for "sodium" :-P

**Comment by shartte** [comment]
Oh, wait, you built from source yourself. 

Did you remember running the data generation? Most models are generated and not checked into source control.

Try running `gradlew runDatagen build` (on Fabric) and please try it again.

**Comment by TheBeautyLlama** [comment]
appliedenergistics2-10.0.0-alpha.8.jar was crashig so i decided to built from source, now appliedenergistics2-10.0.0-alpha.8.jar loading just fine, strange

btw 
![изображение](https://user-images.githubusercontent.com/84794955/147273381-887aa2cb-fbc0-417d-a725-3bf51a0eb9fc.png)

**Comment by shartte** [comment]
You can ignore the spotless errors. You do not need to run spotless (it just formats / checks formatting of JSON files). If you want to, you'd need to install npm.

Try running `gradlew runDatagen jar` for example.

**Comment by TheBeautyLlama** [comment]
ty for help
