### ISSUE TITLE
Right clicking the ME Controller with the network tool does not open the GUI

### ISSUE THREAD

**Issue by ramidzkh** [AppliedEnergistics/Applied-Energistics-2#5867]
### Describe the bug

Right clicking the ME Controller with the network tool does not open the GUI

### How to reproduce the bug

1. Place an ME Controller
2. Try using the network tool on it

### Expected behavior

The GUI would open for that network

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

N/A

**Comment by Technici4n** [comment]
It's probably because it attempts to rotate it? CPUs have the same issue. Blocks like drives or interfaces get rotated instead, idk if that's intended? :P

**Comment by ramidzkh** [comment]
Looks like it gets rotated, even if it's impossible to tell on the controller

![image](https://user-images.githubusercontent.com/19631324/147299108-8d520164-7c22-45cf-88ca-7bf057083244.png)
