### ISSUE TITLE
Cannot open portable cells from offhand

### ISSUE THREAD

**Issue by ramidzkh** [AppliedEnergistics/Applied-Energistics-2#5869]
### Describe the bug

I cannot open my 16k Portable Item Cell when it's in my offhand and there's nothing in my main hand

### How to reproduce the bug

1. Get a portable cell
2. Place it in your offhand
3. Use it

### Expected behavior

The portable item cell GUI will open

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

N/A

**Comment by shartte** [comment]
Should it open? I honestly have no idea what the "etiquette" for the off-hand is in Minecraft?

**Comment by shartte** [comment]
Fixed by fixing #5944 (488324a)
