### ISSUE TITLE
Disable a certain crafting cluster being used by automated requests

### ISSUE THREAD

**Issue by ramidzkh** [AppliedEnergistics/Applied-Energistics-2#5886]
### Describe the feature

A block which can be part of a crafting cluster which can suppress that cluster from being used for automated crafting requests caused by export buses or interfaces

### Reasons why it should be considered

If you have more crafting requests than processors, such as when items are being stocked in an interface/storage bus set-up, it becomes very difficult to queue a task manually

**Comment by EnderProyects** [comment]
Well, just add more processors xd

**Comment by shartte** [comment]
Just add it as a toggle button to the CPU UI using the existing UI setting infrastructure.
