### ISSUE TITLE
[1.9] Migration to Java 8

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#590]
The new minecraft launcher is now bundling Java 8 and basically defining it as baseline for minecraft.

Therefore we should consider the advantages and disadvantages of switching to Java8.

**Comment by gkuba** [comment]
There are builds of forge for 1.8 now and a good hand full of mods are starting to support 1.8 as well. Can we expect a 1.8 build in the near future? If it's not java 8 required doesn't bother me I'm just interested in the new features of 1.8 vanilla with AE networks.

**Comment by psxlover** [comment]
Please don't post on irrelevant issues, asking for ETA.

**Comment by thatsIch** [comment]
We want to release at least one additional revision until we update. Also considering our size, we wait for a recommended Forge Version.

Also we need to finalize the bugs on 1.7.10 before migrating, else users will not stop bugging us about bugs in 1.7.10 when we already moved on.

**Comment by gkuba** [comment]
Understandable thanks. At least we know you have a work plan in place for
it.

**Comment by cathode** [comment]
For what i's worth, i've been running my Forge server on Java 8 (openjdk8) on FreeBSD for months now. almost zero issues compared to constant issues with java 7 and 6. I'm running AE2 rv1 beta 37 on that server.

**Comment by thatsIch** [comment]
@cathode thats not the issue. The issue is, when we start JDK 8 classes, all other which do not have JRE 8 installed, will crash, because they are missing the classes.

I run personally JDK 8 as my development environment, so I know there are no issues, from the Mojang stats, only about 20% of all users are using Java 8 with still a small percentage using Java 6.

So by doing that, we would force users to use Java 8, but imo its not our place to decide. Forge is a better handler to deal with such dependencies.

**Comment by yueh** [comment]
@bonii-xx started a [post](http://www.reddit.com/r/feedthebeast/comments/2r52mu/) on reddit about it.
Of course Forge would still be better overall, but there should also be some pressure put on Forge by the mod devs.

**Comment by bonii-xx** [comment]
That was more out of curiousity, and to see how the situation currently is. Java7 is viable, but Grum himself told me that the "new" launcher and the "newer" launcher that enforces Java8 will coexist for a while, so you can't depend on the vanilla launcher giving people Java8.

**Comment by thatsIch** [comment]
When Mojang moves their Code from minimal requirement of Java 6 to Java 8, we all can enforce it and put pressure

https://help.mojang.com/customer/portal/articles/325948-minecraft-system-requirements

**Comment by thatsIch** [comment]
This is apparently post-poned to 1.9 due to Forge

**Comment by Baughn** [comment]
Got fixed, didn't it? There are a couple of 1.7 mods which require Java 8 now, so I expect you could switch if you want to.

**Comment by thatsIch** [comment]
We can switch any time, but since the base application is still Minecraft and they have the min requirement of Java 6, Forge is the next best instance to enforce it. This is additionally annoying if you put Java 8 Classes in your API and other people/mods can not use it

**Comment by yueh** [comment]
Many (popular) 1.8+ mods are already enforcing Java 8. Forge itself will not enforce it, they are still in the "but... but.. the minecraft requirements say it needs to run on a toaster".
