### ISSUE TITLE
crash which only seems to happen when AE is installed

### ISSUE THREAD

**Issue by ATH4** [AppliedEnergistics/Applied-Energistics-2#5901]
### Describe the bug

sometimes when breaking, or loading AE2 blocks, the server can crash[also happens if you load the world in singleplayer]

### How to reproduce the bug

run AE2 on an Athernos server[2.5gb ran and 2 Vcores]

### Expected behavior

when breaking AE2 blocks, mianly cables it should crash, not always though

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/5LK6xfzF

**Comment by shartte** [comment]
According to your crashlog this is related to a mod called "supplementaries", not AE2.

**Comment by ATH4** [comment]
i see, i will try uninstalling it

**Comment by ATH4** [comment]
i aplolgise for submitting a false bug report
