### ISSUE TITLE
Meteor and Meteor compas don't work

### ISSUE THREAD

**Issue by MehTV** [AppliedEnergistics/Applied-Energistics-2#5909]
### Describe the bug

I craft Meteor compas and it don't find the Meteor. I was flyed a lot of time and it wasn't fixed.

### How to reproduce the bug

craft the Meteor compas

### Expected behavior

Find the near Metror

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

/execute in minecraft:overworld run tp @s -20.77 79.51 355.39 235.95 27.45

**Comment by MehTV** [comment]
And metor compas don't work with sodium

**Comment by shartte** [comment]
We don't support sodium.

Please take the time to actually fill out the required information.

**Comment by Zolarix** [comment]
In Another Quality Modpack 2 v1.4.1 (Fabric), `/locate ae2:meteorite` returns the following instantly:
> Could not find that structure nearby 

By comparison in the same world and modpack, `/locate awesomedungeon:better_default_jungle_temple` eventually returns a result, 6485 blocks away, beyond the range of a meteorite compass. This suggests that Skystone Blocks are not generating in the world.

**Comment by shartte** [comment]
Is that what the original poster uses too?
Also: I still need the actual crash report, I don't know what AQM v2 actually includes.
Does it use Terralith?

**Comment by Zolarix** [comment]
> 

I have no affiliation with the OP and don't know which modpack they're using. AQM 2 does include Terralith. Apologies if it is mentioned as unsupported- I looked at the unsupported page and didn't find it.

The attached crash is not related to AE2 but is the latest one attached for your reference:
[crash-2021-12-26_06.32.19-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/7781730/crash-2021-12-26_06.32.19-server.txt)

**Comment by shartte** [comment]
Please don't hijack issues 😓 
We don't directly support modpacks in general, because it's technically impossible to actually reproduce these issues in a dev environment properly. That doesn't mean we try to use our powers of deduction to figure out the problem anyway.

Terralith is a recurring issue, really. But before it's confirmed OP doesn't actually use the same modpack, it might be unrelated.

**Comment by Zolarix** [comment]
I appreciate the information about Terralith - I will investigate the effect of removing it.

I think "hijack" is quite a strong word. I was trying to provide more detailed information about why, and I quote:
> Meteor and Meteor compas [sic] don't work

Which is the same issue I'm having.

I understand use of any mod is without guarantee or warranty about function or compatibility. I am not complaining or blaming, again, just trying to provide more information to determine the cause of the issue reported, which you can take or leave.

If hearing about compatibility issues offends you, you could add to the "Issues" guidance on the homepage that all bug reports when using the mod in a modpack will be considered invalid. I would only argue that a fair amount of people using the mod will do so via a modpack, so such information will, at the very least, narrow down which issues can be safely ignored.

**Comment by shartte** [comment]
Yeah, don't fret about it too much.
But without knowing what the environment for OPs issue was, it could be related, or not related at all.

**Comment by MehTV** [comment]
How to fix my problem? Maybe you know analog sodium for this?

**Comment by shartte** [comment]
The issue you reported at the start has nothing to do with Sodium, and you still didn't provide the requested information.

**Comment by shartte** [comment]
Assuming the Log-File from your other issue is current, you are also using Terralith. That'll be the reason no meteorites show up.
