### ISSUE TITLE
Level emitter acepting redstone

### ISSUE THREAD

**Issue by EnderProyects** [AppliedEnergistics/Applied-Energistics-2#5913]
### Describe the feature

![image](https://user-images.githubusercontent.com/45178400/147503047-677a351d-52cd-4a73-ad13-87147d7bc45f.png)

I was thinking that now are two modes, redstone when crafting, redstone to craft... Receive redstone to craft, and then you can use the numbers to specify the quantity of items yo want to request per redstone pulse, if there are no items to craft, it should do anything and don't work.

### Reasons why it should be considered

You can automate things more easily from machine outputs that give a redstone signal, or make complex circuits with it, there is some other mod that you can only craft x which depends on whether it is day or night, and then you can use a detector of light to do this, send signals from a network to a subnet or avoid having to restart an entire network when using a toggle bus.

**Comment by shartte** [comment]
Can't you already kinda do this with an export bus + redstone + crafting card?

**Comment by EnderProyects** [comment]
Well, yes and no, you can start a craft in a certain machine, but no in the entire network, and with the bus you can't specify the amount of materials you want to craft in a time,

**Comment by shartte** [comment]
If you put acceleration cards in, it will craft more than 1 per operation though.
I don't know if changing an "emitter" to also be a "receiver" is really the right way to approach this. Also, you can just have it export into an interface.

**Comment by EnderProyects** [comment]
Well as you decide I think it can be useful and easy to implement, you are right that you can actually use redstone card, but I think it's not the same ;3

**Comment by Technici4n** [comment]
We tend to avoid redundant features, and as explained before there are ways to achieve the same thing already.
