### ISSUE TITLE
💥API Breaks for 1.19

### ISSUE THREAD

**Issue by shartte** [AppliedEnergistics/Applied-Energistics-2#5915]
This is the tracking issue for planned breaking changes to AE2s API in 1.19.

- [x] Rename `PREVIEW_REGULAR` and `PREVIEW_LARGE_FONT` in `appeng.api.stacks.AmountFormat` to `SLOT` and `SLOT_LARGE_FONT` to better communicate that they format amounts intended to fit into a standard slot
- [ ] Consider using service loader more to make it easier for addons (they currently have to test stuff like "Is JEI loaded" for adding their own JEI type converters)
- [x] #6298.

**Comment by NoursInDev** [comment]
Get you the line for me ? I've don't found Preview regular and preview large font in amountformat.class.
