### ISSUE TITLE
Encoded Processing Pattern with Duplicate Outputs is Invalid

### ISSUE THREAD

**Issue by shartte** [AppliedEnergistics/Applied-Energistics-2#5917]
The following pattern can be encoded, but it is invalid due to the two outputs being the same:

![grafik](https://user-images.githubusercontent.com/1261399/147516371-a6537eae-69e8-4fdf-bb18-a9fa9b4b9734.png)
![grafik](https://user-images.githubusercontent.com/1261399/147516379-1e59d0b4-f739-41d3-8137-558866ad260b.png)

**Comment by Technici4n** [comment]
I'm not sure having two identical outputs is a good thing? Would need to check that it's handled correctly.

**Comment by shartte** [comment]
It's actually being merged into one stack when the pattern is decoded, but then it can't find the primary output anymore with exactly the same amount leading to this problem.

This might have been a bug introduced by my refactor. See this block from AEProcessingPattern. The comment doesn't match the actual code, and "smaller stack size" also just seems wrong? Shouldn't it be "larger stack size",  in case it got merged with secondary outputs?

```java
        // Ensure the primary output is the first in the list, even if it has a smaller stack size.
        int primaryOutputIndex = -1;
        for (int i = 0; i < condensedOutputs.length; ++i) {
            if (primaryOutput.equals(condensedOutputs[i])) {
                primaryOutputIndex = i;
            }
        }
```
