### ISSUE TITLE
Crafting CPU spat out half a million cobble.

### ISSUE THREAD

**Issue by BenWoodford** [AppliedEnergistics/Applied-Energistics-2#592]
This is on rv1-stable-1, so not sure if it's been fixed.

Loaded up our world (we're in ModSauce by the way) and it was lagging to all hell. Going down (slowly) to our crafting CPUs we found thousands of stacks of cobble laying on the ground. We had started off some compressed cobble just before saving and closing the world previously, so I presume the crafting CPU spat out all the ingredients upon reloading the world.

UPDATE: This just happened again, I'm not sure if it's specific to large quantities (our CPU is 1.3 million bytes, and it was processing about 50k cobble the second time around) but it spat it all out when the world was saved and then loaded again.

**Comment by akvgergo** [comment]
What about storing the items in a s
