### ISSUE TITLE
Player Requested Crafting Jobs doubled

### ISSUE THREAD

**Issue by mdgilene** [AppliedEnergistics/Applied-Energistics-2#5920]
### Describe the bug

Seeing some strange behavior where when a user requests a craft the job is sent to 2 crafting CPUs at the same time resulting in 2 times the requested amount being created.

I've tried to capture this in these screenshots.

https://imgur.com/a/HulIjtS

### How to reproduce the bug

1. Setup network with 2 or more crafting cpus (# memory/coprocessors doesn't seem to matter)
2. Setup any standard crafting recipe 
3. Request X amount
4. Receive 2X amount

### Expected behavior

Should only craft exact amount requested by player

### Additional details

Seems to be similar to the issue someone else brought up here but on a newer version of the mod. #5437

AE2 Version: v9.0.0-beta.2

AE2 Plugins:
- AE2WTLib: v9.0.0-beta.8

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/bLLUyMwa

**Comment by shartte** [comment]
As far as I know, this is an issue in AE2WTLib, and not in AE2 itself.

**Comment by mdgilene** [comment]
I don't see how this can be  an AE2WTLib problem. It occurs even when not using any of the wireless terminals it adds. I've gone into a creative world and setup a pure AE2 build that replicates the issue.

The issue only occurs when you select "automatic" for CPU selection. If you select a specific CPU then that CPU is used and no extra items are created.

I've attached a world where this is happening. This was created using the modpack "All of Fabric 4 1.1.3"

[New World.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/7785325/New.World.zip)

**Comment by shartte** [comment]
> I've gone into a creative world and setup a pure AE2 build that replicates the issue.

With AE2WTLib removed or was it still present?

If it was still present, try it again without AE2WTLib being installed...
