### ISSUE TITLE
cable and terminal removing on start world

### ISSUE THREAD

**Issue by MehTV** [AppliedEnergistics/Applied-Energistics-2#5921]
### Describe the bug

Cable and terminal don't not displayed

### How to reproduce the bug

Open worl
![2021-12-28_13 28 51](https://user-images.githubusercontent.com/96722494/147557589-a4291062-b735-40b7-b1de-2eac5f800b83.png)
d

### Expected behavior

I start my server and when i go to the ME system i don't find cable and termminal but devices online and else go to the cable he won't let you pass. 

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

/execute in minecraft:overworld run tp @s -163.91 71.00 -273.00 244.57 5.55

**Comment by MehTV** [comment]
and after placing they don't connectin
![2021-12-28_13 37 44](https://user-images.githubusercontent.com/96722494/147557860-ff04d69d-51ac-46d5-8d84-49864c522451.png)
g

**Comment by shartte** [comment]
Please follow the instructions in the issue template and provide a forced crash report, as well as your latest.log (server side in case this isn't single player)

**Comment by MehTV** [comment]
[latest.log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/7784502/latest.log)

**Comment by shartte** [comment]
Does this happen everytime you restart your server? Is there something in your client-side log? If the devices are online it may be just a client-side issue.

**Comment by xiPakuL** [comment]
This happens on my server aswell, some clients, like mine can see it, running sodium, indium, iris, others cannot, even others are rendering broken and dissapearing on relog
