### ISSUE TITLE
Opposite cable of the Me glass cable

### ISSUE THREAD

**Issue by EnderProyects** [AppliedEnergistics/Applied-Energistics-2#5929]
### Describe the feature

Add a cable that can transmit channels (at least 8 to be able to use p2p) but that does not allow the passage of power from one side of the network to the other, the cable itself could use power from the sides to which it is connected.
The recipe could be an energy acceptor in the middle, a smart cable on each side, and an anchor cable at the top and bottom.

### Reasons why it should be considered

It can be useful in cases of wanting only one area to use x energy instead of the entire network, it is also true that I do not know if it is easy to integrate since I do not know very well how the network controls energy consumption ...
Whether it is a positive or negative answer, it would be good to consider it.

### Additional details

It's funny because I was just thinking about it and someone just wrote in the discord with the same problem, so I guess I'm not the only one who thinks it would be useful.

**Comment by Technici4n** [comment]
Not gonna happen due to technical constraints. And I believe there are many ways to achieve this already with subnetworks.
