### ISSUE TITLE
Bind a crafting cluster to an interface or export bus

### ISSUE THREAD

**Issue by ramidzkh** [AppliedEnergistics/Applied-Energistics-2#5931]
### Describe the feature

Shift right clicking a memory card on a crafting cluster and then right clicking an export bus or interface with a crafting card will force that cluster to be used, bypassing #5886

### Reasons why it should be considered

This would allow some crafting card tasks to be prioritized over all others by binding them to a processor which cannot be automatically chosen for automation-queued tasks, so things like prioritizing the upkeep of a quarry over processing of the ores can be done

**Comment by Technici4n** [comment]
I don't think this would really be useful. An existing way of doing this would be with subnetworks.
