### ISSUE TITLE
ME Export Bus with Crafting Card bugged

### ISSUE THREAD

**Issue by Megafoan** [AppliedEnergistics/Applied-Energistics-2#5932]
### Describe the bug

When I use an ME Export Bus on a Vibration Chamber to insert Lava Buckets, I encounter an error when I give the Export Bus a Crafting Card in order to automatically craft the lava buckets. Specifically, this only happens when it is set to 'Use stocked items, or craft items while exporting'. In this mode, the Export Bus will only insert existing lava buckets in my system and will _not_ craft new ones when there are no more in the system. In 'Do not use stocked items, only craft items while exporting', it _will_ craft the buckets without issue. For reference, I am using Mystical Agriculture's 'Fire Essence' to craft the lava buckets.

### How to reproduce the bug

Set up a method of crafting lava buckets in an ME network. Use an ME Export Bus on a Vibration Chamber to insert Lava Buckets, with a Crafting Card. Have the card set to 'Use stocked items, or craft items while exporting'. Ensure there are no lava buckets already in the system.

### Expected behavior

I expect for lava buckets to automatically be crafted and inserted into the Vibration Chamber given my setup.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/BMEJ1UKM

**Comment by shartte** [comment]
> appliedenergistics2-10.0.0-alpha.4.jar

Please update to beta.2 and try it again.

**Comment by Megafoan** [comment]
The only versions available on CurseForge are alpha versions. 
![image](https://user-images.githubusercontent.com/8832558/147619674-e86d5d8e-5463-4dc8-bb6f-2669bdbcd9f9.png)

**Comment by shartte** [comment]
@Megafoan Oh, you seem to actually be on _1.18_ and not _1.18.1_
You'll need to update Minecraft itself too, we only publish newer versions for 1.18.1, even though it _technically_ would work on 1.18 too.

Also, the full list of files is here: https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2/files/all

**Comment by Megafoan** [comment]
Understood, thank you.
