### ISSUE TITLE
beta2 bricked my Instance (No SLF4J providers were found)

### ISSUE THREAD

**Issue by bearY0** [AppliedEnergistics/Applied-Energistics-2#5933]
So everything worked fine in my Instance (All of Fabric 5), even tried a fresh install. After adding Beta2 to the mod folder my game is completely bricked even if i remove it again.

![GDLauncher Error](https://i.imgur.com/bYS6yZJ.png)

Full crash report: https://pastebin.com/vMzLUB7m

**Comment by Technici4n** [comment]
```
Caused by: java.lang.RuntimeException: Failed to load AE2 config: ..\..\instances\AOF5\config\appliedenergistics2\client.json
```

Can you try deleting that file? (Of course, if you made any modifications, you'll have to re-apply them to the newly generated file)

**Comment by shartte** [comment]
Huh, I thought we had actually fixed this in the more recent versions?

**Comment by shartte** [comment]
> ae2: Applied Energistics 2 10.0.0-alpha.8

The crashlog you posted is an error that occurs specifically because you tried to downgrade it (config got written with new values the old version does not understand). What is the error you actually get with beta.2 in your server?

**Comment by bearY0** [comment]
> ```
> Caused by: java.lang.RuntimeException: Failed to load AE2 config: ..\..\instances\AOF5\config\appliedenergistics2\client.json
> ```
> 
> Can you try deleting that file? (Of course, if you made any modifications, you'll have to re-apply them to the newly generated file)

i deleted the ae2 config folder and the game loaded but when i tried to load my world it tried to connect to the AoF5 server, failed to connect and showed me the server list. then i repaired the insance and now i just get the same error in the launcher that i started with. new crash log: https://pastebin.com/npJvxDhF

**Comment by shartte** [comment]
You are using a version of `ae2wtlib` (an addon not produced by the AE2 devs) that is incompatible with your AE2 version
