### ISSUE TITLE
Tessellation Issues

### ISSUE THREAD

**Issue by wyckedawesome** [AppliedEnergistics/Applied-Energistics-2#5942]
### Describe the bug

I'd like to preface this by saying it might not be a problem on your end so I'll of course be submitting this same report to Optifine.
Attempting to change/apply a shader in a world containing ME Quantum Ring or Vibrant quartz glass results in a client-side crash due to tessellation issues. If the shader is already active upon worldload (or before the blocks are placed) the error does not happen. 
specifically I loaded my server that I had been playing in since the 1.18 release and realized I had forgotten to turn my shaders back on after doing some testing with the NoCubes mod. I went into the menu and turned the shaders on and had this crash:

[crash-2021-12-31_15.30.54-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/7797052/crash-2021-12-31_15.30.54-client.txt)

I checked the crash log and saw what it was and realized my wife's PC had the same crash recently, but I thought nothing of it because she has a mid-tier laptop w/ internal graphics attempting to run an experimental shader pack. I assumed her PC just couldn't handle the shader pack and the large number of mods we use at the same time.  We actually tried to apply her shaders twice:

[crash-2021-12-24_21.27.35-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/7797058/crash-2021-12-24_21.27.35-client.txt)

[crash-2021-12-24_21.31.59-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/7797059/crash-2021-12-24_21.31.59-client.txt)

Anyways, after realizing all this I thought I should file an error report. But I knew to check my version. I was on 10.0.0-beta.1 so I updated to 10.0.0-beta.2 and reloaded the game. When the game loaded my shaders were still not applied so I teleported far enough away that no ae2 blocks would be rendered (or simulated) and applied the shaders. Everything worked normally so I teleported back to my base (which has several quantum rings under and in it, as well as a house build nearby with some vibrant glass). For about 1/2 a second it seemed fine then it crashed:

[crash-2021-12-31_16.01.11-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/7797060/crash-2021-12-31_16.01.11-client.txt)

I reloaded again without changing anything and this time the shader was already applied when the world loaded and everything is working fine.
To round things out, here is a modlist:

[mods.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/7797067/mods.txt)

### How to reproduce the bug

Load a world with optifine with no shader applied. Place ME quantum ring and/or vibrant quartz glass in world. Apply shader. Crash should happen after reload finishes. Alternatively place blocks, teleport away, apply shader, shader succeeds, teleport back to blocks, crash happens. 

### Expected behavior

The game would perform the normal reload when changing shaders and then continue to work as usual.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

multiple crash reports attached to bug report

**Comment by Technici4n** [comment]
> Optifine

**Comment by Technici4n** [comment]
To give more details: we don't support a closed source mod that heavily modifies the game in broken and incompatible ways. Your only option is to stop using optifine if you want mods to work.
