### ISSUE TITLE
[1.18] Certus Quartz no longer works with TR Grinders

### ISSUE THREAD

**Issue by xanthian** [AppliedEnergistics/Applied-Energistics-2#5943]
### Describe the bug

As Above
Screenie from 1.17
(works with MI & TR machines)
![image](https://user-images.githubusercontent.com/7688001/147850398-12311043-b90f-4420-9e98-f120e1140f9f.png)

Screenie from 1.18
(Only works with MI macerator)
![image](https://user-images.githubusercontent.com/7688001/147850404-74fecc56-1342-4b4b-8a8b-ff7a92d1dcb1.png)

### How to reproduce the bug

Install 1.18 :)

### Expected behavior

Work with TR machines

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

.

**Comment by Technici4n** [comment]
Modid changed to `ae2`, TR needs to update.

**Comment by xanthian** [comment]
of course. 

pr sent in to TR :)
ty.
