### ISSUE TITLE
NoClassDefFoundError on attempting to open inventory

### ISSUE THREAD

**Issue by Moodsss** [AppliedEnergistics/Applied-Energistics-2#5953]
### Describe the bug

java.lang.NoClassDefFoundError: appeng/menu/me/items/PatternTermMenu

### How to reproduce the bug

Attempting to open up inventory

### Expected behavior

not this

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/zTTPedQX

**Comment by Ommina** [comment]
This looks like a wobble with Polymorph.  They may need to make changes to accommodate beta3.

**Comment by Technici4n** [comment]
Indeed, you can disable polymorph's AE2 compat module.

**Comment by Ommina** [comment]
Polymorph has an update out to fix this: Their version 0.35
