### ISSUE TITLE
A crafting card related, hard to reproduce bug that crashes the server

### ISSUE THREAD

**Issue by DoremySwee** [AppliedEnergistics/Applied-Energistics-2#5954]
### Describe the bug

I'm building the "Move and Select" Command for my ME Based Programmable Computer
And this stupid ME Network that turns the (0~255 cobblestone) data into [7digit 01] data suddenly blew the entire server up when I'm testing it.
So, the situation becomes really complicated, I think I can't even reproduce this bug at all.
And, I'm unwilling to publish the save to the public, at least, not yet, since I'm still working on it.
	MC version: 1.17.1
	Mods:	1.17.1-Forge 37.0.103
		appliedenergistics2-9.0.0-beta.1
		worldedit-mod-7.2.7

![The Broken World](https://user-images.githubusercontent.com/66953201/147875015-5d5d9435-f302-4f67-a8cd-f4786338a722.PNG)

The problem occurred when the ME export bus with crafting card was attempting to "craft" something.
I also tried ME interface in the same ME network, and it also shut down the server.

![NamelessScourge, the ME Export Bugggggggg](https://user-images.githubusercontent.com/66953201/147875014-0a58e338-f72f-4bf0-87e9-808ee959c357.PNG)

Here is how the network(part) should work:
	Step1: input cobblestones
	Step2: Emitter lights up, letting the export bus to publish crafting assignments
	Step3: Successfully Assigned
		Here is when the server shuts down.
	Step4: Cobblestone thrown into the matter condenser, and expected [Renamed Stones] gets back to the network

![The ME Network that blew the server up without explanation](https://user-images.githubusercontent.com/66953201/147875020-9c25fa18-8e6e-404f-8cbf-4c52df242596.PNG)
![The ME Network that blew the server up with explanation](https://user-images.githubusercontent.com/66953201/147875021-4fbb7a03-a420-40d0-ae83-9bb453775b16.PNG)
![Explanation2](https://user-images.githubusercontent.com/66953201/147875219-e1567ab3-7644-4d3a-80bc-b0f0cb8c4290.PNG)

The PatternProvider Aims at a Matter Condenser. I broke it, and tested the server again, and the server was blew up again and again. 
That is, the problem wasn't about the item delivery to the PP, or the item returning from outer system, it was about the "Crafting mission allocation for CPU" or "item delivery to CPU" or "Crafting tree calculation" under that circumstance.

Here comes the second ridiculous thing:   I tried publish the crafting assignment manually, and everything went perfectly, even though I reassembled the ME network all together.
        After this, I retried the experiment I did before, and the export crashes the entire server again.

Now, here comes the most weird series of events
	1  I built a similar ME network but differently shaped and without ME Controller but with Creative Cell filled with cobblestones, as shown in the picture, and everything went well.
![The ME Network that doesn't blow the Server up](https://user-images.githubusercontent.com/66953201/147875022-ced83b6a-3d7a-4fdf-9b0b-6500d18f5224.PNG)
	2   I simplified the structure as following, problems occurs still. Both by copying and Hand building
![AA](https://user-images.githubusercontent.com/66953201/147875232-8923948b-c828-495d-9a3a-f1978df198b1.PNG)

3   I replaced the 64k cell with creative one full of cobblestones, and things went well.
4   I replaced the creative cell in "The ME Network that doesn't blow the Server up" with a 64k cell and everything went on well????????????????
5: 
![Just another ME bomb](https://user-images.githubusercontent.com/66953201/147875028-62c0a4d0-7a8b-4362-b007-6f2447832c4c.PNG)
6: 
![Just Another Server Crasher](https://user-images.githubusercontent.com/66953201/147875031-bc801069-e062-4ef5-a8f5-beddbeea1fc8.PNG)
[crash-2022-01-02_17.21.22-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/7799020/crash-2022-01-02_17.21.22-server.txt)

### How to reproduce the bug

Unknown.
The Bug took place on the server.
[Wrong_World202201021815.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/7799034/Wrong_World202201021815.zip)

### Expected behavior

[The server should not crashes]

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/61VDxDGZ

**Comment by Technici4n** [comment]
Was fixed in 1.18...

**Comment by DoremySwee** [comment]
> Was fixed in 1.18...

Can we have a bug-free version...
I've carried this project from 1122 to 1165 and now 1171, due to all kinds of bugs

**Comment by DoremySwee** [comment]
> Was fixed in 1.18...
So What is the bug, can I avoid it?

**Comment by Technici4n** [comment]
IIRC this happens when some items that the system was planning to use for the crafting task are not available anymore the moment it is started.

**Comment by Technici4n** [comment]
But yeah, we don't have time to backport fixes to 3 versions, forge and fabric, so this is unfortunately going to remain a bug in 1.17.
