### ISSUE TITLE
Meteors not spawning / working

### ISSUE THREAD

**Issue by CryptNation** [AppliedEnergistics/Applied-Energistics-2#5957]
### Describe the bug

Meteors not spawning in no matter what and using the dev placer gives out a strange message
in the server console.

### How to reproduce the bug

On a modded server the meteors just don't spawn in.
Using the Dev Placer causes errors in the console.

### Expected behavior

Meteors to spawn in normally.

### Additional details

Modpack Modlist:
https://pastebin.com/tjyKMkMW

https://www.curseforge.com/minecraft/modpacks/crypts-additions

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/gBpZ1Xbs

**Comment by lilmayu** [comment]
Can confirm, no meteors even in newly generated world.

**Comment by mindforger** [comment]
terralith is causing this, can't find the relevant issue atm

**Comment by lilmayu** [comment]
That's weird tho. If it worked before even with terralith (how I mentioned there were meteors prior to beta 3, I was using terralith)

**Comment by xanthian** [comment]
Hope devs don't mind, - if you do, I'll delete this
But I made a datapack for someone else that asked in Discord about this.
It swaps Skystone to Polished Blackstone on the ME Controller recipe
Also adds the 4 inscriber presses (Certus, Gold, Diamond or Silicon surrounded by 8 Iron Ingot )

[ae2.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/7849667/ae2.zip)

To install copy the zip file into the Saves\World\Datapacks folder
(dont unzip it)

**Comment by shartte** [comment]
So, I just tried this again with the latest Terralith 2, and for me, it just works.

**Comment by shartte** [comment]
And I tried it again with a dedicated server and outside of the dev-environment with just AE2+Terralith. It _still_ works.

If you can find a combination of mods that actually breaks it, i'll investigate. I don't have the time to check every combination of mods in your modlist though.
