### ISSUE TITLE
Mixin Issue with Biomes O Plenty

### ISSUE THREAD

**Issue by coldReactive** [AppliedEnergistics/Applied-Energistics-2#5959]
### Describe the bug

Biomes O Plenty writes the same Mixin as AE2: https://github.com/Glitchfiend/BiomesOPlenty/issues/1940

Please update this issue with the conflict: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/5184

### How to reproduce the bug

1. Install Biomes O Plenty (15.0.0.63) and Applied Energistics 2
2. Start Minecraft

### Expected behavior

Minecraft starts without issue.

### Additional details

Adubbz Wrote:
> I’ll have to see if I can adjust my mixin strategy a bit to try and make it compatible, I don’t know if there’s much they can do at this moment

***

This issue should be closed if and when the conflict is fixed on either side.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/coldReactive/12c8fa7d5400b2dda1eeddf5738c5ee1

**Comment by Technici4n** [comment]
Fixed by the BOP dev!
