### ISSUE TITLE
Crash from Latest AE2 [1.18.1 Fabric]

### ISSUE THREAD

**Issue by red2blue** [AppliedEnergistics/Applied-Energistics-2#5960]
### Describe the bug

Latest update causes incompatibility with Polymorph client side.

### How to reproduce the bug

Update to latest AE2
Have polymorph

Join World
Press any key like "E"
Crash

### Expected behavior

not to crash

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/RSCJ24JL

**Comment by Technici4n** [comment]
Disable polymorph's ae2 module. Please do realize that polymorph is mixing into ae2, and that it's their problem if it crashes...
