### ISSUE TITLE
Priority auto crafting implementation in ME Pattern Provider

### ISSUE THREAD

**Issue by Irutar** [AppliedEnergistics/Applied-Energistics-2#5962]
### Describe the feature

Implement a system to enable selection of priority in the ME patent provider when one item can be obtained by using two different recipes. When writing about different, I mean completely different ways to get the item. For example: an object can be obtained by burning a powder in an oven or by a chemical reaction of two liquids. Priority would allow such a configuration to be set: if a powder is available this method would be preferred and only when the powder is unavailable the chemical reaction would be used. In this case, the powder is only obtained as a side effect of other crafting. There is no pattern for creating a powder here, but if it is available in ME network I would like it to be preferred for making an item.

### Reasons why it should be considered

AE is most often used with other mods. These mods often allow you to obtain one item with several methods. Being able to set priority on ways in which you would like to obtain item whould greatly improve the auto crafting system.

### Additional details

![46dce2405f66fa1610f99561ae58a904](https://user-images.githubusercontent.com/37962301/147990654-361ad40b-0e51-4b40-9c93-eb0c5c6f2b61.png)

**Comment by Technici4n** [comment]
Previously, you could set the priority for the whole pattern provider. Maybe I should look into adding it back? (Without the performance issues it caused in 1.12 of course :P )

**Comment by Irutar** [comment]
Would be nice
