### ISSUE TITLE
It said: Rendering entity in world, when it crashed

### ISSUE THREAD

**Issue by sashaironfist** [AppliedEnergistics/Applied-Energistics-2#5964]
### Describe the bug

when it crashed it said the following mod(s) have been identified as the potential cause: Applied energistics 2, Heros expansion. 

### How to reproduce the bug

i used heros expansion to try to lift ME drive using space stone

### Expected behavior

I expected it to work

### Which minecraft version are you using?

1.12 - UNSUPPORTED

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/vY9JU4H6

**Comment by sashaironfist** [comment]
NOTHING HAS 1.12.2 SUPPORTED!!!!!!!

**Comment by sashaironfist** [comment]
::::::::::::::::::(((((((((((((((((((((((((((((((((((((((((

**Comment by Seniorendi** [comment]
Yeah
I recommend switching to a modern version.
I also recommend to not do char spamming <:

**Comment by mindforger** [comment]
you are right with heros expansion, whatever block has been „grabbed“ with this mod does not like to be rendered this way heros expansion want to render ... So wrong mod here and 1.12 is now over a year old, you can not expect modders working in their free time (which you enjoy playing their mods) to support dozends of different versions at the same time

**Comment by shartte** [comment]
I didn't see the spamming here lol. I gave them a patched 1.12 version on discord that works around that "heros expansion" issue. 😓
