### ISSUE TITLE
Missing models of a crafting terminal and facades [Fabric][1.18.1][10.0.0-beta.3]

### ISSUE THREAD

**Issue by lanalancia** [AppliedEnergistics/Applied-Energistics-2#5967]
### Describe the bug

The cables, terminals and every block with unique model looks like a purple block. White outlines shows a model correctly.

![image](https://user-images.githubusercontent.com/96468948/148214655-3c118451-16ff-4a4c-a4a1-511dbefb09ad.png)

### How to reproduce the bug

1) place any block with a different model (cable, terminal, etc)

### Expected behavior

Block's models displaying correctly

### Additional details

No crashes or warnings

i'm using fabric. Minecraft version is 1.18.1

I have other mods, like Tech Reborn, but their blocks are isplaying correctly

Full list of my mods: 
![image](https://user-images.githubusercontent.com/96468948/148215446-fa581441-6a9b-473b-a0ee-4c0252c633ba.png)

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/cWmkqwQd

**Comment by Mari023** [comment]
you need indium for sodium to work with most mods (such as ae2) to work

**Comment by lanalancia** [comment]
> you need indium for sodium to work with most mods (such as ae2) to work

It's ok now, thanks
![image](https://user-images.githubusercontent.com/96468948/148217115-1cf53809-1250-4078-8025-b995fa2298be.png)
