### ISSUE TITLE
Meteorites generate despite disabling them

### ISSUE THREAD

**Issue by dav20011** [AppliedEnergistics/Applied-Energistics-2#5971]
### Describe the bug

In the 1.18.1 Forge version the `generateMeteorites = false` option gets ignored.

### How to reproduce the bug

1. Create a standard 1.18.1 Forge setup with just AE2 (newest version as shown in the crash report)
2. Start and stop the game and disable meteorites in `config/ae2-common.toml`
3. Relaunch the game, create a new world and look for a meteorite
4. Example: Use the world seed `-941960200960353326`, then execute `/tp -1954 76 -504`

### Expected behavior

There should be no meteorites in the world.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/GQ8s2qve

**Comment by dav20011** [comment]
Seems like the equivalent to [this](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/94624c1c7cdeaaa553b70b990295cc731b392bc0/src/main/java/appeng/init/worldgen/InitBiomeModifications.java#L40) was never implemented for the Forge version.

**Comment by shartte** [comment]
That does not work on Forge. Forge loads configuration files _after_ that code is run.

**Comment by dav20011** [comment]
That is indeed unfortunate. Maybe a comment that it does not work should do it for now.

But given that the meteorite generation is one of the most critized features of AE2 there should be some way to disable it. There seem to be other ways to register structures like [this](https://github.com/HellFirePvP/AstralSorcery/blob/5e34d885b12a759c5b061444271da6b1fd745048/src/main/java/hellfirepvp/astralsorcery/common/registry/RegistryWorldGeneration.java#L121) that work after the config has been loaded.

**Comment by shartte** [comment]
Yeah there is, it's a bit of a wild west at the moment. That's why I am keeping this issue open. 
We have the issue on the other end of the spectrum too, where people want it to generate in Terralith worlds, but it fails because Terralith takes an entirely different codepath.

**Comment by Technici4n** [comment]
Solved in 1.18.2: make sure that the `ae2:has_meteorites` biome tag is empty.

**Comment by spoorn** [comment]
Is this config no longer available?  I see nowhere to disable meteorites

**Comment by Technici4n** [comment]
> make sure that the ae2:has_meteorites biome tag is empty

**Comment by spoorn** [comment]
@Technici4n where is this `ae2:has_meteorites` biome tag?

**Comment by Technici4n** [comment]
This is standard data pack stuff, the tag is contained in the `data` folder of our JAR file, and you can refer to the Minecraft wiki for details on how to override it with a data pack.

**Comment by Technici4n** [comment]
Though if that is too hard/un-intuitive to do, we might consider adding back an additional config option.

**Comment by spoorn** [comment]
config would be easier for me as all of the config would be in one place
