### ISSUE TITLE
Ability to disable Facades in config file.

### ISSUE THREAD

**Issue by ShibeTemple** [AppliedEnergistics/Applied-Energistics-2#5977]
### Describe the feature

There should be an option under `[features.Facades]` to disable the blocks entirely. 

This was a feature in the past using the old configuration file, please see https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2140:
```
facades {
        B:Facades=true
}
```

### Reasons why it should be considered

Facades are not natural-sized blocks and often take up a lot of rendering time and can lag players. As they are non-essential, I would prefer to have them disabled to squeeze a bit more performance out of my game. Even simply viewing the list of facades in JEI/NEI/etc can significantly reduce framerate. While you can hide the facades from being listed here, I would simply like the legacy way of disabling them entirely so they cannot be used in the game world either.

Thank you.

**Comment by shartte** [comment]
> Facades are not natural-sized blocks and often take up a lot of rendering time and can lag players. 

Do you have any actual profiles of this? Facades are baked into the mesh same as the rest of the cable bus.

**Comment by Technici4n** [comment]
Just don't craft them if you don't want them. It is also possible to remove the recipe using KubeJS.
