### ISSUE TITLE
AutoCrafting now working on 1.18.1 Server

### ISSUE THREAD

**Issue by Zelioth** [AppliedEnergistics/Applied-Energistics-2#5978]
### Describe the bug

Auto Crafting will not function on 1.18.1 TNP 5 Server. When Requesting an item it goes to the Co-Crafting processing unit, and 64k Crafting storage multi blog and just sits there. I have Recreated the same AE system and Pattern in single player in the same mod pack with the same version mod and it functions perfectly. but on the server it just freezes at the Request stage. ALSO

When requesting a item to be crafted it goes to the "Crafting Plan" UI but at the bottom for "Storage" and "Co Processors" It says "N/A" even though I have them in the netowrk. If I change "Automatic it will let me select the specific Crafting CPU But still just sits in it instead of crafting the Item. 

### How to reproduce the bug

**Build the normal AE2 network.**

- Me Controller
- Me Flux Cable (Dense Smart and Regular Smart)
- Crafting CPU Multi Blocks
- Molecular Assembler
- Me Pattern Provider
- Storage drive and disk
- Me Terminal 

Once assembled and powered on the **SERVER** with AE2 place any pattern into the system and go through the normal ways of requesting the item to be crafted

After it will show in the MultiBlock Crafting CPU but never craft the Item.

### Expected behavior

When requesting the item to be crafted it will be sent to the Crafting CPU MultiBlock which will then Craft the item in the Molecular Assembler and once completed remove and return it to the AE2 System

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://bytebin.lucko.me/g8ZPUtnajQ

**Comment by shartte** [comment]
I've just tested this with the following setup, crafting simple crafting tables, and this works for me:

![grafik](https://user-images.githubusercontent.com/1261399/148691832-89305b58-44bb-42cb-bead-3cdc1d228b3f.png)

**Comment by Zelioth** [comment]
> I've just tested this with the following setup, crafting simple crafting tables, and this works for me:
> 
> ![grafik](https://user-images.githubusercontent.com/1261399/148691832-89305b58-44bb-42cb-bead-3cdc1d228b3f.png)

Was this on a single player or 1.18.1 server instance? my issue is only on the server for TNP5

**Comment by shartte** [comment]
This was on a server i started locally

**Comment by Zelioth** [comment]
> This was on a server i started locally

like Single player LAN or actual server, seperate mods, not just a server with ae2 in it

**Comment by shartte** [comment]
No, not single player lan. Dedicated server and direct connection from separate client to it.

**Comment by Technici4n** [comment]
There is probably a mod messing with the server, unfortunately this is not something that we can check or support and it will be for your modpack to figure out.
