### ISSUE TITLE
Crash With Polymorph

### ISSUE THREAD

**Issue by Idefkftt** [AppliedEnergistics/Applied-Energistics-2#5979]
### Describe the bug

Game crashes on opening player inventory.  Crash log cites a fault in Polymorph's functions but while referencing AE2 objects.  Report will be posted to both mods pages just for safety, if determined to be strictly a Polymorph issue, please ignore.

### How to reproduce the bug

1. Load associated mods
2. Load world
3. Open inventory
4. Crash

### Expected behavior

Not crash.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://crashy.net/MGmsAhUU7j6T8vqkKr6d

**Comment by shartte** [comment]
This crash is completely within Polymorph's code. They have not updated to internal changes within AE2, apparently.
