### ISSUE TITLE
Support recursive recipes

### ISSUE THREAD

**Issue by ramidzkh** [AppliedEnergistics/Applied-Energistics-2#5981]
### Describe the bug

I have a recipe where 3B Manganese Sulfuric Solution + 3 Raw Titanium -> 2.5B Manganese Sulfuric Solution + 4 Hot Titanium Ingot. When there is 6B of Manganese Sulfuric Solution and 21 Raw Titanium, 28 Hot Titanium Ingots should be craftable but it isn't. The recipe can be done 7 times requesting 4 Hot Titanium Ingots each however.

### How to reproduce the bug

(With MI but I suppose this can easily be replicated in vanilla)

1. Place a pattern provider with `3B Manganese Sulfuric Solution + 3 Raw Titanium -> 2.5B Manganese Sulfuric Solution + 4 Hot Titanium Ingot`
2. Place 6B of Manganese Sulfuric Solution and 21 Raw Titanium in the system storage
3. Try crafting 28 Hot Titanium Ingots

### Expected behavior

The crafting plan will be successful

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

N/A

**Comment by Piehthyte** [comment]
I can confirm, I have this issue as well. For me it's while trying to craft most AE things, but specifically AE Fluix Cable. 
Additional details are pretty much you can see the system shows it can craft something, you can click the craft button but nothing happens.

**Comment by yorii** [comment]
> I can confirm, I have this issue as well. For me it's while trying to craft most AE things, but specifically AE Fluix Cable. Additional details are pretty much you can see the system shows it can craft something, you can click the craft button but nothing happens.

Not the same issue as the one described, open another issue for this.

**Comment by mindforger** [comment]
pretty sure calculating recipes that reuse their own products have been a recursive challange since the beginning of ae2

**Comment by Piehthyte** [comment]
> pretty sure calculating recipes that reuse their own products have been a recursive challange since the beginning of ae2 ... Same goes with chance based recipes, breaking production chains when not setup for minimum product

Recursive recipes was it. Thanks!

**Comment by Technici4n** [comment]
One of the problems with recursive recipes is: should AE2 try to ensure that "enough" is left in the system after the crafting job? E.g. if there is a stone duplication recipe, one stone in the system, and you request 20... Should AE2 actually craft 21 stones so that there is one left after the recipe.

Not saying it's going to be implemented, but just thinking about challenges here.

**Comment by Technici4n** [comment]
I don't think this is ever happening.
