### ISSUE TITLE
AE2 causes Server crash forge with JEI

### ISSUE THREAD

**Issue by IgnaciaSaber** [AppliedEnergistics/Applied-Energistics-2#5982]
### Describe the bug

Every time I would click in JEI for a recipe my server would crash. I did try max tick time -1. Redid my server with a different forge version. I removed all JEI mods on server and it still crashed when I used JEI on client side. Nothing helped until I removed AE2 beta3. I did put AE2 beta 2 in and it worked as expected.

### How to reproduce the bug

Put AE2 beta3 and JEI in a server and try to look up a recipe.

### Expected behavior

After clicking on any recipe the server will immediately crash. This has to be on a server as my singleplayer client works just fine.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/0KqeT6EH

**Comment by Ommina** [comment]
That's Polymorph.  and I'm pretty sure it has already been fixed there.
