### ISSUE TITLE
[1.18] Deepslate ores do not use the correct base texture

### ISSUE THREAD

**Issue by Peach774** [AppliedEnergistics/Applied-Energistics-2#5983]
### Describe the bug

Deepslate has a different top texture than its sides but the certus quartz ores do not use this unique top as the base for the textures on the top side of the deepslate ore blocks.

### How to reproduce the bug

Look at the deepslate ores in the mod vs regular deepslate ores

### Expected behavior

The top texture for deepslate ores should be different than the sides

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

no crash

**Comment by xanthian** [comment]
Maybe i'm blind, but looking at the ore against vanilla, there is no top texture?

Top
![image](https://user-images.githubusercontent.com/7688001/148699338-bfc6eca7-ad9c-4043-a2bb-bc5e50e1b36f.png)


Side
![image](https://user-images.githubusercontent.com/7688001/148699368-c5224fdd-9777-40c4-983b-8e2d4dc5d0d1.png)


Aside from some shading around the ore deposit, both are identical.

Vanilla texture folder also has no reference to top variant of ore, but does have a top Deepslate texture for the block.
![image](https://user-images.githubusercontent.com/7688001/148699474-51d77359-fb30-489f-8b51-fa544ac6d738.png)

Also nothing in the model.json files to suggest an alternate texture.
![image](https://user-images.githubusercontent.com/7688001/148699518-7435d1d0-cd55-4b05-bcf3-f06dc153e46e.png)

**Comment by Peach774** [comment]
Huh, so only the block has the regular top texture but not ores? weird, guess this isn't a bug as much as a weird vanilla quirk.
