### ISSUE TITLE
UI enhancements and features

### ISSUE THREAD

**Issue by l-ricardo** [AppliedEnergistics/Applied-Energistics-2#5987]
### Describe the feature

**1-** A new storage monitor that keeps track of the amount of an item to see if the amount is increasing or decreasing. For example, every 20 min it sees the number of items in the network and calculates what was the net gain or net loss compared to the latest reading. It would be nice if this time were configurable at least 4 modes (1min, 5min, 10min, 20min).
![image](https://user-images.githubusercontent.com/88405145/148854657-b285ec6e-9e84-4f14-b631-da1514d6893f.png) ![image](https://user-images.githubusercontent.com/88405145/148854687-609f98a3-a4c0-4165-a03a-af26a9cc9e7b.png)

**2-** Reconsider the CTRL+CLICK on the JEI's move recipe button “+” triggers the auto crafting of the missing items. This already have been rejected 2 years ago in #4238 and in #4987 (11 months ago), both are blocked topics and as the modded Minecraft has changed a lot since I´d like to ask for a reconsideration and put in my 2 cents about the topic as I feel like the justify for the rejection doesn’t apply anymore. Two years ago, was “not possible” code wise “unless JEI allows us to explicitly do it”, now Refined Storage did it so it’s possible, and is one of their most likeable features. “This would clash with the design goal of auto crafting”, have to disagree it is not that OP and only saves search time and also there are crafts necessary only once in the entire playthrough. It would NOT clash with the design goal of auto crafting because if you need more than one of that item is a lot easier to encode the recipe as this method only request enough for 1 recipe. Sorry for bring that up again but as ae2 have reconsidered highly requested features in the past (e.g. wireless crafting terminal and infinite channels) I would like to give it a shot.
![image](https://user-images.githubusercontent.com/88405145/148854877-fe5c0935-1fc0-4aa7-b969-7fbfba603e11.png)

**3-** If the 2 suggestion get rejected again please consider at least the blue highlight on items which have they recipes encoded would be VERY useful mainly in the pattern encoding terminal to speed up the encoding process so we don´t have to search item by item to see if the network already knows how to craft it.
![image](https://user-images.githubusercontent.com/88405145/148855195-e6e36556-8a2c-4954-a46b-1e58434b6f4d.png)

**4-** Ability to do mathematical equations (+-*/) on the crafting amount screen. For example, I need 8 upgrades for each one of 13 machines but I already have 37 upgrades stored. It would be amazing be able to just write the amount as 8*13-37 rather than having ALT+TAB to open a calculator discover the answer and them type 67 on the crafting amount screen.

**5-** When HOLDING SHIFT prevents terminals from updating the positions of items. Useful when we are using SHIFT+CLICK to pick up some item but the terminal is configured to sorted by amount and items that I'm trying to get keep changing position, solves what was asked in #27.

**6-** Make view cells slots have a turn on and off with one more of those smaller buttons on the left (screenshot). View cells are rarely used and when they are, you don’t need to be seen them all the time. It would make the UI cleaner and improve compatibility with JEI/NEI that wouldn't have to zigzag all the time because of the exclusion zones.  It's annoying when you search for something in JEI finds and at the time you open the terminal to craft the item changed position because of the view cells space.
![image](https://user-images.githubusercontent.com/88405145/148855278-84d46166-0ca6-4430-a148-38220fa8bf34.png)

**7-** Make the same for the upgrade slots, not as necessary as the 6 suggestion, since the UI they apply are not ones of frequent interaction with the player (importer/exporters), but it would be nice for consistency with the view cells slot and also solve issue when an UI have both view cells and upgrade slots (screenshot from #5958), so when one opens the other closes, they both could also share the same button. For convenience the upgrade slot should be on by default, it would be a downgrade to add one more click in the path to add upgrade card to an importer, for example.
![image](https://user-images.githubusercontent.com/88405145/148855393-1f74d114-eea6-4748-94d4-44f356e6bd88.png)

**8-** Pattern Access Terminal enhancements: 
![image](https://user-images.githubusercontent.com/88405145/148855452-28d4d929-7db2-4672-935c-a47f91d2dbb8.png)
**8a-** Give the P.A.T. the ability to highlight Patterns Providers in world and print cords on the chat (Using the “!” button), something like what the prototype trousers fork of ae2 did in 1.12. It's great to debug in which one of the machines that have the same name the crafting progress got stuck or is too slow, or where the hell of the big base that machine was placed, or where is a Pattern Provider that should have been hidden but it was forgotten.
**8b)** Button for more search modes [Search for pattern output/ Search for pattern input/ Search for Pattern Provider's name/ All], sometimes we are looking for a specific pattern but there is a possibility that we need to know which pattern is the one who’s crafting is eating all of the searched resource and the third option deal with the fact that in most cases when placing patterns in the P.A.T. is more convenient to search for the name of the machine than to try remember what patterns are inside it.
**8c-** Add one button to [Hide full Patterns Providers / Don’t hide full Patterns Providers], I don’t need to see full Pattern Providers. Shadow back to #2929, only refresh the Hide Full when reopen because we don’t want to misplace a pattern in the last Provider slot and it disappear instantly.
**8d-** Add one button to [Show only Patterns Providers connected to Molecular Assemblers / Hide Patterns Providers connected to Molecular Assemblers / Show both]. Would be neat to have one P.A.T. for Molecular Assemblers and other for processing machines. Or just use this easy toggleable button to see only the molecular assemblers when inserting patterns.
Of course, these last 2 buttons (8c and 8d) need to be independent so big customization potential. And for sanity reasons automatically go back to the current behavior when using the search box because we don’t want to search a pattern that is in a full Provider and don’t find it because Hide full is on.

**9-** SHIFT+CLICK on “x” clears the crafting matrix by depositing items in the player's inventory instead of depositing them on the network or add a new button on the UI for that (example below). It would be a great enhancement to non-crafting table recipes that can be moved through JEI, a quick way to get everything into your hand.
![image](https://user-images.githubusercontent.com/88405145/148855599-0bd5fe19-5dcb-42c6-a191-3758b15afa4a.png) or ![image](https://user-images.githubusercontent.com/88405145/148855611-7d5f2b86-d3bd-49d4-ad63-c7b5f859475c.png)

**10-** Automatically keep P.E.T. fill with blank patterns (requiring a crafting card making use of suggestion 7 or as a build-in native feature). I'm asking for this because Refined Storage alloy you to set up an export bus with crafting upgrade that keeps their pattern encode terminal always full of patterns and always wanted something like this in ae2. That number be configurable might be a nice touch because filling with 64 can get kinda annoying, if you miss the encoding of some recipe.  
![image](https://user-images.githubusercontent.com/88405145/148855764-0f92da0d-9469-4d1b-8c98-82f62f7a3c9a.png) or ![image](https://user-images.githubusercontent.com/88405145/148856032-a9e3df9c-57fd-4290-af39-2b02036c3049.png) or ![image](https://user-images.githubusercontent.com/88405145/148856070-ffd76546-9fc7-4330-9b0e-e08cb4d50b89.png)

**11-** Combine processing patterns in an anvil/smiting table/matter condenser/inscriber to create processing patterns with more than 9 different items. In #3540, 4 years ago have been given excellent points about the theme by the issue’s author that I will not repeat myself here (please read there). Again, as this is a highly requested feature and ae2 have reconsidered those before I would like to give it another try now 4 years later to add some present perspective to invalidate some justifications for denial in the past, since I can’t do in the original feature request as it is already blocked.
In the old days few mods had this lack... but as the world of modded Minecraft has evolved and now there are many crafting mechanics that have support to use more than 9 unique item (Create's Mechanical Crafter, Draconic's Fusion Crafting, Botania's Runic Altar, Mythic Botany’s Rune Ritual, Occultism’s rituals, Astral Sorcery’s altars, Extended Crafting’s tables...) to solve this limitation is possible to use the work around of (micro)crafting to split that kind of recipes in smaller ones but that's bad thing because it loses all the magic and sense of scale of the endgame crafting and turns into a rabbit hole of a 3x3 crafting chain. It’s not like modpacks authors didn't want us to automate these recipes it’s just that they preferred the grandeur of giant crafting than having to subdivide it into minors just to be automatable. So, they are limited to using this type of recipe only for those who are one-time craft or can be bulk crafted. See the ATM star ATM6 for example, or any other endgame recipe for popular tech modpacks in versions after 1.16 (All the Mods, Seapolis, FTB oceanblock, Enigmatica, Skyopolis). 
![image](https://user-images.githubusercontent.com/88405145/148856560-5ef7a635-dfb8-433a-a935-4599536a3930.png)![image](https://user-images.githubusercontent.com/88405145/148856573-edd5c177-7f3d-4462-9b5e-e96c8d317e7f.png)![image](https://user-images.githubusercontent.com/88405145/148856583-5a26d484-5007-4eb0-aff2-c6c55185ee57.png)![image](https://user-images.githubusercontent.com/88405145/148856590-7cd2a2f1-6504-449c-9efa-9c6de4202777.png)![image](https://user-images.githubusercontent.com/88405145/148856599-0f4187f8-691b-4c21-ab84-1273e1c8e125.png)![image](https://user-images.githubusercontent.com/88405145/148856611-b8a45c6d-e8eb-4e40-80ed-cf9a1b08d84c.png)![image](https://user-images.githubusercontent.com/88405145/148856671-3ca8535b-5cef-4d5c-b880-5b331efbc913.png)![image](https://user-images.githubusercontent.com/88405145/148856694-d936d752-cc5c-4ecf-a14e-19f6c158d82b.png)
So my proposal is this: when in Pattern Encoding Terminal’s Process Mode if you don't set any output items and still hit the encoding recipe button you would be returned with a Partial Processing Pattern (that has only encoded input items) it could be combined with a Processing Pattern resulting in another Processing Pattern which one will have the Partial Processing Pattern inputs added to the original Processing Pattern, obviously this could be repeated and to create giant Processing Patterns and without needing any UI change to have a NxN matrix in P.E.T. (which would be a bad design choice in my opinion). At the end is just another nice mechanic that would remove the annoying 9 unique items limitation from modded Minecraft and if for some reason some modpack dev don't want it to be used it’s just a matter of removing the recipe of combining the patterns or the Partial Processing by itself.
![image](https://user-images.githubusercontent.com/88405145/148856818-380367a3-5c1b-4865-89d9-b8e45d707165.png)![image](https://user-images.githubusercontent.com/88405145/148856751-c93f3ec4-ac08-4cf9-a7eb-1f54e17a6972.png)

### Reasons why it should be considered

Aside from 11 no one brings a big gameplay change most of them are just QoL features to make the interaction between player and mod more enjoyable.  Reasons why should be considered were given in detail in each topic.

**Comment by shartte** [comment]
Thanks for the detailed suggestions.

But discussing 11 different suggestions in one issue is probably going to lead to pure chaos 😁

**Comment by l-ricardo** [comment]
Sorry for the huge issue, I even considered splitting it but I thought it was better than a flood of 11 suggestions as some of them had already been rejected in the past. 

> But discussing 11 different suggestions in one issue is probably going to lead to pure chaos 😁 

I can close this one and open one for each suggestion if you prefer.

**Comment by shartte** [comment]
If you can do that it'd be nice. Otherwise I'd have to do it myself.

**Comment by l-ricardo** [comment]
As asked, closing this one in favor of #5988 #5989 #5990 #27 #5991 #5992 #5993 #5994 #5995
