### ISSUE TITLE
Add a new storage monitor that tracks items net gain or net loss

### ISSUE THREAD

**Issue by l-ricardo** [AppliedEnergistics/Applied-Energistics-2#5988]
### Describe the feature

(Extracted from #5987)
A new storage monitor that keeps track of the amount of an item to see if the amount is increasing or decreasing. For example, every 20 min it sees the number of items in the network and calculates what was the net gain or net loss compared to the latest reading. It would be nice if this time were configurable at least 4 modes (1min, 5min, 10min, 20min).
![image](https://user-images.githubusercontent.com/88405145/148854657-b285ec6e-9e84-4f14-b631-da1514d6893f.png) ![image](https://user-images.githubusercontent.com/88405145/148854687-609f98a3-a4c0-4165-a03a-af26a9cc9e7b.png)

### Reasons why it should be considered

It´s not possible currently, at least without a really big and convoluted redstone contraption, which at the end will not be as accurate and repeatable as the suggestion. Imagine having a wall of these monitors to see if your miners are keeping up with your base needs.

**Comment by Technici4n** [comment]
Unlikely to ever happen in AE2 itself, but addon developers are welcome to use our API to implement this feature!
