### ISSUE TITLE
Hide option to view cells and upgrades slots

### ISSUE THREAD

**Issue by l-ricardo** [AppliedEnergistics/Applied-Energistics-2#5991]
### Describe the feature

(Extracted from #5987)
**1-** Make view cells slots have a turn on and off with one more of those smaller buttons on the left (screenshot). View cells are rarely used and when they are, you don’t need to be seen them all the time. It would make the UI cleaner and improve compatibility with JEI/NEI that wouldn't have to zigzag all the time because of the exclusion zones.  It's annoying when you search for something in JEI finds and at the time you open the terminal to craft the item changed position because of the view cells space.
![image](https://user-images.githubusercontent.com/88405145/148855278-84d46166-0ca6-4430-a148-38220fa8bf34.png)

**2-** Make the same for the upgrade slots, not as necessary as the 1 suggestion, since the UI they apply are not ones of frequent interaction with the player (importer/exporters), but it would be nice for consistency with the view cells slot and also solve issue when an UI have both view cells and upgrade slots (screenshot from #5958), so when one opens the other closes, they both could also share the same button. For convenience the upgrade slot should be on by default, it would be a downgrade to add one more click in the path to add upgrade card to an importer, for example.
![image](https://user-images.githubusercontent.com/88405145/148855393-1f74d114-eea6-4748-94d4-44f356e6bd88.png)

### Reasons why it should be considered

Done above.

**Comment by Technici4n** [comment]
I don't think this is going to be implemented. There are already enough toggles in the terminal, and the use case is rather limited.
