### ISSUE TITLE
Crafting matrix cleaning convenience

### ISSUE THREAD

**Issue by l-ricardo** [AppliedEnergistics/Applied-Energistics-2#5993]
### Describe the feature

(Extracted from #5987)
SHIFT+CLICK on “x” clears the crafting matrix by depositing items in the player's inventory instead of depositing them on the network or add a new button on the UI for that (example below). 
![image](https://user-images.githubusercontent.com/88405145/148855599-0bd5fe19-5dcb-42c6-a191-3758b15afa4a.png) or ![image](https://user-images.githubusercontent.com/88405145/148855611-7d5f2b86-d3bd-49d4-ad63-c7b5f859475c.png)

### Reasons why it should be considered

It would be a great enhancement to non-crafting table recipes that can be moved through JEI, a quick way to get everything into your hand.

**Comment by shartte** [comment]
I actually thought about this too and I am more in favor of having two buttons: an arrow-up (deposit to network) and arrow-down (deposit to player inventory).
