### ISSUE TITLE
Pattern Encoding Terminal fill itself with blank patterns

### ISSUE THREAD

**Issue by l-ricardo** [AppliedEnergistics/Applied-Energistics-2#5994]
### Describe the feature

(Extracted from #5987)
Automatically keep P.E.T. fill with blank patterns (requiring a crafting card making use of suggestion 2 of #5991 or as a build-in native feature). I'm asking for this because Refined Storage alloy you to set up an export bus with crafting upgrade that keeps their pattern encode terminal always full of patterns and always wanted something like this in ae2. That number be configurable might be a nice touch because filling with 64 can get kinda annoying, if you miss the encoding of some recipe.  
![image](https://user-images.githubusercontent.com/88405145/148855764-0f92da0d-9469-4d1b-8c98-82f62f7a3c9a.png) or ![image](https://user-images.githubusercontent.com/88405145/148856032-a9e3df9c-57fd-4290-af39-2b02036c3049.png) or ![image](https://user-images.githubusercontent.com/88405145/148856070-ffd76546-9fc7-4330-9b0e-e08cb4d50b89.png)

### Reasons why it should be considered

Done above

**Comment by Technici4n** [comment]
> Refined Storage alloy you to set up an export bus with crafting upgrade that keeps their pattern encode terminal always full of patterns

AE2's pattern terminal only occupies one side of a block, not the entire block, so connecting something to it would prevent normal terminal access.
