### ISSUE TITLE
Reconsider allowing processing patterns with more than 9 unique items

### ISSUE THREAD

**Issue by l-ricardo** [AppliedEnergistics/Applied-Energistics-2#5995]
### Describe the feature

(Extracted from #5987)
Combine processing patterns in an anvil/smiting table/matter condenser/inscriber to create processing patterns with more than 9 different items. In #3540, 4 years ago have been given excellent points about the theme by the issue’s author that I will not repeat myself here (please read there). Again, as this is a highly requested feature and ae2 have reconsidered those before I would like to give it another try now 4 years later to add some present perspective to invalidate some justifications for denial in the past, since I can’t do in the original feature request as it is already blocked.
In the old days few mods had this lack... but as the world of modded Minecraft has evolved and now there are many crafting mechanics that have support to use more than 9 unique item (Create's Mechanical Crafter, Draconic's Fusion Crafting, Botania's Runic Altar, Mythic Botany’s Rune Ritual, Occultism’s rituals, Astral Sorcery’s altars, Extended Crafting’s tables...) to solve this limitation is possible to use the work around of (micro)crafting to split that kind of recipes in smaller ones but that's bad thing because it loses all the magic and sense of scale of the endgame crafting and turns into a rabbit hole of a 3x3 crafting chain. It’s not like modpacks authors didn't want us to automate these recipes it’s just that they preferred the grandeur of giant crafting than having to subdivide it into minors just to be automatable. So, they are limited to using this type of recipe only for those who are one-time craft or can be bulk crafted. See the ATM star ATM6 for example, or any other endgame recipe for popular tech modpacks in versions after 1.16 (All the Mods, Seapolis, FTB oceanblock, Enigmatica, Skyopolis). 
![image](https://user-images.githubusercontent.com/88405145/148856560-5ef7a635-dfb8-433a-a935-4599536a3930.png)![image](https://user-images.githubusercontent.com/88405145/148856573-edd5c177-7f3d-4462-9b5e-e96c8d317e7f.png)![image](https://user-images.githubusercontent.com/88405145/148856583-5a26d484-5007-4eb0-aff2-c6c55185ee57.png)![image](https://user-images.githubusercontent.com/88405145/148856590-7cd2a2f1-6504-449c-9efa-9c6de4202777.png)![image](https://user-images.githubusercontent.com/88405145/148856599-0f4187f8-691b-4c21-ab84-1273e1c8e125.png)![image](https://user-images.githubusercontent.com/88405145/148856611-b8a45c6d-e8eb-4e40-80ed-cf9a1b08d84c.png)![image](https://user-images.githubusercontent.com/88405145/148856671-3ca8535b-5cef-4d5c-b880-5b331efbc913.png)![image](https://user-images.githubusercontent.com/88405145/148856694-d936d752-cc5c-4ecf-a14e-19f6c158d82b.png)
So my proposal is this: when in Pattern Encoding Terminal’s Process Mode if you don't set any output items and still hit the encoding recipe button you would be returned with a Partial Processing Pattern (that has only encoded input items) it could be combined with a Processing Pattern resulting in another Processing Pattern which one will have the Partial Processing Pattern inputs added to the original Processing Pattern, obviously this could be repeated and to create giant Processing Patterns and without needing any UI change to have a NxN matrix in P.E.T. (which would be a bad design choice in my opinion). At the end is just another nice mechanic that would remove the annoying 9 unique items limitation from modded Minecraft and if for some reason some modpack dev don't want it to be used it’s just a matter of removing the recipe of combining the patterns or the Partial Processing by itself.
![image](https://user-images.githubusercontent.com/88405145/148856818-380367a3-5c1b-4865-89d9-b8e45d707165.png)![image](https://user-images.githubusercontent.com/88405145/148856751-c93f3ec4-ac08-4cf9-a7eb-1f54e17a6972.png)

### Reasons why it should be considered

Done above.

**Comment by shartte** [comment]
I'd probably check what RS is doing here. For processing patterns, a simple scrollbar in the encoding terminal might suffice
