### ISSUE TITLE
Cannot use MI's string conjuration recipe

### ISSUE THREAD

**Issue by ramidzkh** [AppliedEnergistics/Applied-Energistics-2#5996]
### Describe the bug

MI's 1 String + 0.02B Nylon -> 2 String recipe isn't usable, and complains about missing materials. This happens for other conjuration style recipes

### How to reproduce the bug

1. Encode a string -> 2 string recipe and place it in a pattern provider (this is an idealization of the actual recipe, but does incur the same issue)
2. Put any amount of string in the system
3. Request double that quantity (Case A) 
![image](https://user-images.githubusercontent.com/19631324/149084382-7cbf95ca-d778-4a7c-9930-ab1770d98a13.png)

Additionally, if the initial items in the system cannot be used to fulfill the requested crafting steps, resources from those steps will not be considered. To test this, request more than double that quantity of string (Case B) 
![image](https://user-images.githubusercontent.com/19631324/149084403-636d6c19-30ae-4ca9-a55f-7c27e48fe44f.png)

### Expected behavior

(Case A and B) The plan should be successful and completable.
(Case B) Additional crafts of that conjuration should be done to fulfill the request quantity by the end

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

N/A

**Comment by aspiringLich** [comment]
AE2 in general is has always been bad with `input + stuff = more input recipes` because it gets confused or something.

**Comment by Technici4n** [comment]
Sorry, this is not going to be supported. Note that byproducts are correctly reused, but this kind of recursive pattern causes issues because we can't properly estimate how many times it must be requested.

Note that encoding such patterns would be a bad idea anyway, because the system wouldn't leave one extra string in the system for "the next time".
