### ISSUE TITLE
"Upgraded" Interfaces

### ISSUE THREAD

**Issue by 016Nojr** [AppliedEnergistics/Applied-Energistics-2#6000]
### Describe the feature

Either with separate blocks, or with a new upgrade card, being able to increase the number of crafting patterns an interface can hold-

### Reasons why it should be considered

I often run into the problem of running out of space in my interfaces, especially processing ones and being limited to sides on machines you have to create unnecessary large designs just to be able to craft with all the patterns you have.

**Comment by mthnry** [comment]
I like this idea as I run into similar space issues often. I'd even suggest different interfaces for shaped/shapedless crafting and machine crafting. The crafting interfaces would only work with molecular assemblers and keep their 9 slot limit. Machine interfaces would be available in different tiers, like storage 1k, 4k, 16k, 64k and hold more patterns respectively.

**Comment by Technici4n** [comment]
Pattern providers can push into subnetworks starting from 1.18, you can use that to your advantage.
