### ISSUE TITLE
[Fabric] Replacing current recipe from REI to crafting terminal doesn't clear  the grid first

### ISSUE THREAD

**Issue by BLovegrove** [AppliedEnergistics/Applied-Energistics-2#6007]
### Describe the bug

Say I craft a furnace in the crafting terminal, and the recipe is still sitting there to make more. If i then go into REI and craft a torch that only uses the upper left slot and the one below that, the rest of the cobblestone bits won't be cleared from the grid meaning you have to manually clear the grid before clicking into REI - something that hasn't been necessary in the past IIRC. 

### How to reproduce the bug

Described above. Try crafting something like a block of coal or a furnace that uses lots of slots, and then use REI, NEI, or similar to craft something that only uses a couple of slots. 

### Expected behavior

That when you press the plus button in REI (etc.) to add the recipe to the terminals crafting grid, it overrides whats already there by clearing it first.

### Additional details

Using Valhelsia: Vanilla Enhanced 1.18.1 pack.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/U7HLUExY

**Comment by shartte** [comment]
Please use beta.5, it contains fixes for this.
