### ISSUE TITLE
Storage Monitors, Level Emitters sometimes read quantity in main network instead of local subnet

### ISSUE THREAD

**Issue by Tallinu** [AppliedEnergistics/Applied-Energistics-2#601]
I'm running rv2-alpha-17 in the Direwolf20 pack playing on a MP server, so updating isn't really an option. I don't see anything in the change logs that seems relevant to this issue though.

http://imgur.com/C2U6OwP

Here's an example of the subnet setup in question. What's shown there is how it looks when I've 'fixed' all the glitches by removing/replacing the cables behind the storage monitors and temporarily disconnecting the level emitters. The arrowed interface in the floor has crafting patterns for the processors, and the only connection between the two networks is via quartz fiber (the main network also has a controller, so if there was a data connection both of them would turn red and stop working).

Whenever the power is cut and then restored, the subnet's monitors and emitters start out showing quantities of the listed materials that are present on the main network, instead of the zeros or whatever actual local contents they should be showing.

Even removing the quartz fiber power crossover and using another energy acceptor to power the subnet hasn't fixed the issue. The closest thing to a connection between those networks is the export bus sending output processors back into the interface with the crafting patterns.

I can try to add more info if necessary or reproduce in single player (I've been busy or I would've already), but I've been redoing the system trying to solve or reduce the severity of other glitchiness with general network and inscriber sluggishness (it's been like molasses in winter) so a lot has changed since that screenshot, but the issue I've described here still occurs.

Edit: Breaking and replacing the subnet controller also resets the storage monitor to zero, but as soon as the amount of redstone stored in the main network changes in any way, it starts showing that quantity again.

Another: Breaking the MAIN network's controller seems to have fixed this issue for the moment. I'm getting the feeling this may be a tough one to reproduce.

More screenshots: http://imgur.com/a/lQhli

**Comment by yueh** [comment]
Reopen when you can provide a concrete way to reproduce it.

**Comment by Tallinu** [comment]
Yeah, will do. Sorry about the lack of info on this one. I've played around
with it a little but haven't managed it so far... haven't had a lot of time
to devote to the problem.
