### ISSUE TITLE
Cann't Make Certus Quartz Dust

### ISSUE THREAD

**Issue by yw9381** [AppliedEnergistics/Applied-Energistics-2#6011]
### Describe the feature

Many productions require the use of `Quartz Glass`, `Quartz Glass` needs to be made with `Certus Quartz Dust`, But since the `grindstone`  is removed in https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/5444, the  `Certus Quartz Dust` cannot be make, There are currently no other mods that can make `Certus Quartz Dust`

- MineCraft Game Version: **1.18.1**
- Mod Loader: **Forge_39.0.18**
- AE2 Mod Version: **10.0.0-beta.4**

Mod List:
- awesomedungeon-2.0.3.jar
- [Balm] balm-2.4.0+0.jar
- DungeonCrawl-1.18.1-2.3.6.jar
- DungeonsArise-1.18.1-2.1.49c-beta.jar
- extraweapons-0.2.1.jar
- geckolib-1.18-forge-3.0.5.jar
- [JEI工作方块] JustEnoughProfessions-1.18-1.2.2.jar
- [JEI物品管理器] jei-1.18.1-9.2.1.71.jar
- [JEI进度] JustEnoughAdvancements-1.18.1-3.1.0.jar
- [Just Enough Resources] JustEnoughResources-1.18.1-0.13.1.141.jar
- LibraryFerret-Forge-1.18.1-1.0.3.jar
- LibX-1.18.1-3.1.8.jar
- PortableCraftingTable-1.18.1-3.0.0.jar
- Shrines-1.18.1-3.0.0-Beta8.jar
- sniffsinfinityweapons-1.18.1-2.6.3.jar
- thedragonlib-1.18.1-1.0.0.jar
- valhelsia_core-1.18.1-0.3.0.jar
- valhelsia_structures-1.18.1-0.1.0.jar
- walljump-forge-1.18.1-1.3.7.jar
- [一键背包整理Next] InventoryProfilesNext-forge-1.18-1.2.3.jar
- [伐树] FallingTree-1.18.1-3.2.0b1.jar
- [伤害显示] torohealth-1.18-forge-2.jar
- [合成辅助] craftingtweaks-forge-1.18.1-14.0.2.jar
- [应用能源2] appliedenergistics2-10.0.0-beta.4.jar
- [建筑之杖] constructionwand-1.18.1-2.6.jar
- [旅行地图] journeymap-1.18.1-5.8.0beta7.jar
- [无限+经验修补] InfinityMending-1.17-0.1.0.jar
- [更多的龙蛋] moredragoneggs-3.1.jar
- [更好的进度] BetterAdvancements-1.18.1-0.1.2.122.jar
- [机械动力] create-mc1.18.1_v0.4c.jar
- [极简血量显示] Neat 1.8-30.jar
- [模组名称显示] modnametooltip-1.18.1-1.18.0.jar
- [模组目录] catalogue-1.6.0-1.18.1.jar
- [物品栏HUD+] InventoryHud_[1.18].forge-3.4.4.jar
- [玉 🔍] Jade-1.18-4.1.1.jar
- [矿石挖掘] OreExcavation-1.10.159.jar
- [简易背包] simplybackpacks-1.18-2.0.1-build.28.jar
- [经验机制改革] Clumps-forge-1.18.1-8.0.4.jar
- [结构变体] repurposed_structures_forge-4.1.0+1.18.1.jar
- [耐久信息显示] durabilityviewer-1.18.1-forge39.0.9-1.10.jar
- [苹果皮] appleskin-forge-mc1.18-2.2.0.jar
- [装备扩充] armorplus-1.18.1-18.0.2-beta.jar
- [配置界面] configured-1.5.1-1.18.1.jar
- [飞轮] flywheel-forge-1.18-0.5.1.jar

### Reasons why it should be considered

please add grindstone or Provides other methods by which Certus Quartz Dust can be produced

**Comment by shartte** [comment]
We'll not re-implement the grindstone. In the meantime, you should get sufficient dust from mining ore.
