### ISSUE TITLE
Change how encoded pattern renders in inventory

### ISSUE THREAD

**Issue by k3nw4y** [AppliedEnergistics/Applied-Energistics-2#6016]
### Describe the feature

Show the output of the encoded pattern(which is in player inventory) while in pattern provider GUI/Interface terminal without sneaking

### Reasons why it should be considered

Its a small QOL and it makes easier if you have a lot of encoded patterns in your inventory

**Comment by Ommina** [comment]
How would I then differentiate between "thing" and "pattern encoded for thing"?

**Comment by ramidzkh** [comment]
Why not hold shift?

**Comment by Technici4n** [comment]
Do you have the FindMe mod installed by any chance?

**Comment by k3nw4y** [comment]
I also found that bug https://github.com/TeamAOF/All-of-Fabric-5/issues/102#issuecomment-1018567649
By the suggestion i mean this:
![image](https://user-images.githubusercontent.com/46229190/152641464-86d93dd2-b0b0-49eb-8752-5183543fddd3.png)
Currently we have to sneak to render the encoded pattern(the one in players inventory), even in the interface terminal, my suggestion is to render the encoded patterns in players inventory while we open the interface terminal

**Comment by Technici4n** [comment]
Fixed by #6132.
