### ISSUE TITLE
Breaking a ME Controller causes infinite huge lag of the Server

### ISSUE THREAD

**Issue by serveradmin9912** [AppliedEnergistics/Applied-Energistics-2#6017]
### Describe the bug

I'm playing with 3 people on a FTB Revelation 1.12.2 Server.

We have big AE2 systems, but the Server was working fine.
Then my mate wanted to change his system. He broke the controller and replaced it at another location. He connected it with the ME system and everything worked well.
But at this moment the Server started lagging extremely.

We didn't understand what happened, of course. We loaded an earlier backup of the world and rebuild every change  we've made till the lag started. This is how we found out that it's the ME Controller.

### How to reproduce the bug

Every time we break the Controller, the Server starts lagging as hell. 

Replacing it at the same position or replacing it on another location doesn't fix the problem. 
The whole world is "broke" after that, because it's unplayable with such a lag.

Animals need 10 seconds to fall down when spawned with a spawn egg.
Eating something takes 1 minute of right-click holding each item.

### Expected behavior

no lag.

### Additional details

Maybe it has something to do with the linking of the system?

Maybe I have to delete some data in the world folder?
Maybe I have to break all controllers of every me system and the delete something in the world folder?

### Which minecraft version are you using?

1.12 - UNSUPPORTED

### On which mod loaders does it happen?

Forge

### Crash log

dont have one

**Comment by mindforger** [comment]
it sounds plausibel, the reboot of a large enough network can cause lag. Try attaching a creative energy cell and test if the lag stays so bad like before or goes away after replacing the controller. There is a chance your network keeps bootlooping because of power starvation

**Comment by Technici4n** [comment]
We don't support 1.12 anymore unfortunately.
