### ISSUE TITLE
Certus Quartz Dust recipe missing

### ISSUE THREAD

**Issue by 016Nojr** [AppliedEnergistics/Applied-Energistics-2#6018]
### Describe the bug

In the 10.0.0 release changelog from Forge, the first line states this: `Added inscriber recipes to crush certus and fluix crystals back down to dust. This essentially makes certus crystals renewable for the time being.`

However, no such recipe seems to excist in the game.

### How to reproduce the bug

Check for recipes for Certus Quartz Dust

### Expected behavior

A recipe for Certus Quartz Crystals to dust

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

-

**Comment by shartte** [comment]
Thanks for reporting this. We made a mistake when we published the 10.0.0 release for Forge and it didn't actually include the changes listed since the last beta. I am releasing 10.01 right now to rectify this.
