### ISSUE TITLE
Problem of upgrade 1.17.1 server to 1.18.1

### ISSUE THREAD

**Issue by ZYFDroid** [AppliedEnergistics/Applied-Energistics-2#6019]
### Describe the bug

Recently I upgraded my minecraft server from 1.17.1 to 1.18.1. After that, all appliedenergistic blocks disappeared. 

There are also some errors in server console

in 1.17.1
![1 17 1](https://user-images.githubusercontent.com/39429452/150354535-7273aea9-4929-4526-baa3-7a6c7226bb5d.png)

in 1.18.1
![1 18 1](https://user-images.githubusercontent.com/39429452/150354593-0c206391-ce08-44af-9d23-66e34a6f9019.png)

errors in console
![serverlog](https://user-images.githubusercontent.com/39429452/150354689-bd0b7a5f-2e16-4869-8bd9-7f8229a7a1f6.jpg)

### How to reproduce the bug

- install ae2 (9.0.0 beta 1) on 1.17.1 server
- place some ae2 blocks
- upgrade to 1.18.1 (with ae2 10.0.0 installed)
- all ae2 blocks disappears

### Expected behavior

Ae2 blocks will not disappear after upgrade

### Additional details

mod in 1.17.1 version: 9.0.0 beta 1
mod in 1.18.1 version 10.0.0

other mods on 1.18.1
- Adorn-3.1.0+1.18.1-fabric.jar
- appliedenergistics2-10.0.0-beta.4.jar
- architectury-3.4.9.jar
- BetterPingDisplay-Fabric-1.18.1-1.1.1.jar
- Croptopia-1.18-FABRIC-1.8.0.jar
- extshape-1.3.1-mc1.17+.jar
- fabric-api-0.45.0+1.18.jar
- fabric-language-kotlin-1.7.1+kotlin.1.6.10.jar
- FallingTree-1.18.1-3.0.1.jar
- fat-experience-orbs-2.0.0+1.18.1.jar
- indrev-1.13.2-BETA.jar
- majobroom-1.2.jar
- MTR-1.18.1-3.0.0-beta-8.jar
- Patchouli-1.18.1-64-FABRIC.jar
- RoughlyEnoughItems-7.1.357.jar
- TechReborn-5.1.0-beta.4.jar

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

none

**Comment by mindforger** [comment]
stupid question, could one eventually use nbt editor to change the IDs or would it still break horribly?

**Comment by Technici4n** [comment]
> stupid question, could one eventually use nbt editor to change the IDs or would it still break horribly?

Possibly. Modded block entity data is also lost in the update, so you'd need to fix that too (there is a mod that fixes this on fabric iirc).

**Comment by Ommina** [comment]
Does the recently merged https://github.com/MinecraftForge/MinecraftForge/pull/8242 help with this sort of thing?

Although the very notion of TileEntities (yeah, yeah, I know) surviving between world updates just feels foreign.

**Comment by Technici4n** [comment]
Maybe, but I recommend not bothering.
