### ISSUE TITLE
[FABRIC 1.18.1 - AE2 version 10.0.0] Missing textures and block orientation bug.

### ISSUE THREAD

**Issue by wildmogway** [AppliedEnergistics/Applied-Energistics-2#6020]
### Describe the bug

The following list of blocks have an absence of textures, therefore making their use impractical and/or aesthetic:
- Quartz Fiber / Glass Cable / Covered Cable / Dense Cable / Smart Cable / Toogle Bus / Inverted Toogle Bus
- Cable Facade / Cable Anchor
- Storage Monitor / Conversion Monitor
- ME Terminal / Item Crafting Terminal / Pattern Provider Terminal / Pattern Terminal
- ME P2P Tunnel / FE P2P Tunnel / Item P2P Tunnel / Fluid P2P Tunnel / Redstone P2P Tunnel / Light P2P Tunnel
- ME Drive / ME Level Emitter

The following list of items do not work correctly:
- Meteorite Compass (in item form, there is no needle)
- Quantum Link Chamber (placed in the middle of the Quantum Ring, the latter takes their textures)

The following block list remains stuck in the north position:
- Inscriber / Charger / Crystal Growth Accelerator / ME Security Terminal / ME Chest / ME Drive / Vibration Chamber / Wireless Access Point

### How to reproduce the bug

The bug is native, no special manipulation is needed to reproduce it.

### Expected behavior

It is expected that these blocks have their natural textures used and that the possibility of orientation of the block can be similarly acquired in order to be able to correctly use the AE2 systems.

### Additional details

No Additional Details, but if I find other unexpected things I will let you know.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

There is no crash

**Comment by shartte** [comment]
Please follow the instructions in the issue template.

Your bug is impossible to work on otherwise.

**Comment by wildmogway** [comment]
[crash-2022-01-22_17.34.31-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/7918734/crash-2022-01-22_17.34.31-client.txt)

Excuse me, I am attaching the game crash report (caused manually).

I also allow myself to tell you that the Spatial Pylon and all the Crafting Storage are blocks made invisible (I had forgotten to mention it).

**Comment by shartte** [comment]
@wildmogway When you are running with Sodium (which doesn't support Fabric's rendering API), you need to also install Indium.

**Comment by shartte** [comment]
I also updated #5184 with some info on Sodium since this issue comes up relatively often.
