### ISSUE TITLE
[Bug] 10.0.0 Moving ME Security Terminal with a sticky piston caused server crash ( /carpet movableBlockEntities true )

### ISSUE THREAD

**Issue by Xastabus** [AppliedEnergistics/Applied-Energistics-2#6022]
### Describe the bug

I wanted to move an ME Security Terminal without having to go collect and re-link wireless terminals from other players sharing my network.  I placed a sticky piston to pull the terminal away from the network cable.  As soon as the security terminal moved the server crashed.

The terminal was moved when the server came back online.
![2022-01-22_21 19 44](https://user-images.githubusercontent.com/1816386/150662192-4327ee23-e816-40ed-8420-37e781be7a56.png)

### How to reproduce the bug

This may require Carpet Mod and the command `/carpet movableBlockEntities true`

Set up a simple network with an ME Security Terminal.
Place a piston or sticky piston in such a way as to move the security terminal.
move the security terminal.

### Expected behavior

It would be nice to be able to move the ME Security Terminal without having to re-link all wireless terminals.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://mclo.gs/WDzF7DY

**Comment by ramidzkh** [comment]
As a workaround for your setup, you could have an inverted toggle bus connecting the security terminal and place a button on it

**Comment by Xastabus** [comment]
That wouldn't really solve the problem.  The point of moving the terminal wasn't just to disconnect it from the network, I wanted to relocate it.

**Comment by Technici4n** [comment]
> /carpet movableBlockEntities true

There is your problem. You should not expect other mods to support this, use at your own risk.

**Comment by Xastabus** [comment]
I'm not expecting support for it, just informing of the conflict.  Also, it might be wise to consider that gnembon now works for Mojang... consider the potential that movableBlockEntities could be part of vanilla Java Edition in the future.
