### ISSUE TITLE
1.16 meteorite biome blacklist broken

### ISSUE THREAD

**Issue by Magi1053** [AppliedEnergistics/Applied-Energistics-2#6025]
### Describe the bug

Setting a meteorite biome blacklist crashes the server

### How to reproduce the bug

First of all I tried to add a biome to the blacklist in game, but no matter what I type the input isnt valid
![image](https://user-images.githubusercontent.com/1045179/150711524-45922c41-fbc1-41ad-9c2e-a98e99451b6d.png)

So I went into the config and set the value manually to `meteoriteBiomeBlacklist = ["minecraft:forest"]`, and now when I restart the server it crashes immediately

### Expected behavior

Need to be able to blacklist biomes to prevent the meteorite from spawning.

### Which minecraft version are you using?

1.16

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/raw/FB9J6k4b

**Comment by Technici4n** [comment]
`ResourceLocation.isResouceNameValid` is indeed a client-only method.

**Comment by Technici4n** [comment]
Our focus is on 1.18.2 now, so this will never be fixed due to limited manpower.

**Comment by ProsperCraft** [comment]
Is it fixed in 1.18.2 forward?  

I just came here because we had the same crash in 1.16.5

**Comment by Technici4n** [comment]
Yes it's fixed in 1.18.2 since it's now done via tags.
