### ISSUE TITLE
Some blocks are not captured in spatial storage

### ISSUE THREAD

**Issue by PDufresne-ETS** [AppliedEnergistics/Applied-Energistics-2#6027]
### Describe the bug

I currently play with the modpack atm6 1.8.16. I tried saving the Botania Gaia Ritual into a spatial storage and everything got captured properly aside from the 4 floating pylons. The entire ritual setup requires 9x3x9. But I used a 20x10x20 setup to display the issue.

![2022-01-25_11 48 58](https://user-images.githubusercontent.com/11092258/151021691-66b152d7-342b-409a-821e-c70d7e2220ca.png)
![2022-01-25_11 49 06](https://user-images.githubusercontent.com/11092258/151021696-0376c197-4438-4c57-a1f7-1018f461d445.png)

### How to reproduce the bug

I currently play with the modpack atm6 1.8.16. I tried saving the Botania Gaia Ritual into a spatial storage and everything got captured properly aside from the 4 floating pylons.

### Expected behavior

All blocks should be captured

### Which minecraft version are you using?

1.16

### On which mod loaders does it happen?

Forge

### Crash log

NA

**Comment by mindforger** [comment]
There needs to be compatibilty to allow movement of blocks (tile entitys) from other mods, spatial storage can not simply move any block, some are even blacklisted intentionally, nothing that the AE team can do about
