### ISSUE TITLE
ME Wireless Acces Point Crash

### ISSUE THREAD

**Issue by Raft08** [AppliedEnergistics/Applied-Energistics-2#6028]
### Describe the bug

When i place a ME Wireless Acces Point on my Applied network, server & game of the player that place the block crash. Then the world is corrupted I use [Amulet](https://www.amuletmc.com) to remove the block from world.

### How to reproduce the bug

Just place a ME Wireless Acces Point on your network

### Expected behavior

Use it with a wireless terminal

### Additional details

I'm using a [MohistMC](https://mohistmc.com) Server

I use my own made modpack you can download it [here](thegreatcraft.ddns.net/launchers/modded/zip/Modded-1.0.3.zip) It is a CurseForge Modpack zip. Or you can see modlist [here](http://thegreatcraft.ddns.net/launchers/modded/zip/modlist.html)

### Which minecraft version are you using?

1.16

### On which mod loaders does it happen?

Forge

### Crash log

[Client Latest](http://thegreatcraft.ddns.net/launchers/modded/logs/client-latest.txt)

[Server Latest](http://thegreatcraft.ddns.net/launchers/modded/logs/Server-latest.txt)

[Server Debug](http://thegreatcraft.ddns.net/launchers/modded/logs/Server-debug.txt)

**Comment by Raft08** [comment]
The links are from my Rasberry Pi it can come from that.
That is the issue!

Thank for helping me!

**Comment by Mari023** [comment]
It was https everywhere blocking your site from loading.
After visiting the root site and adding an exception I can visit it.
