### ISSUE TITLE
Broken P2P energy drain on Forge

### ISSUE THREAD

**Issue by ramidzkh** [AppliedEnergistics/Applied-Energistics-2#6033]
### Describe the bug

Fluid P2P tunnels drain 1RF per 1mB rather than 1AE per 125mB

### How to reproduce the bug

N/A

### Expected behavior

Each 125mB of transferred fluid will drain 1AE

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

N/A

**Comment by mindforger** [comment]
Which ae2 version?  If i remember right, this has been fixed, but i am not sure in which version

**Comment by ramidzkh** [comment]
This has been fixed on Fabric, but I'm reporting on Forge. Also, I'm looking at the code and noticed it, didn't notice it in game

**Comment by mindforger** [comment]
ah okay then nevermind

**Comment by Technici4n** [comment]
Will be in the next release.
