### ISSUE TITLE
[1.16.5] Crash when placing wireless access point

### ISSUE THREAD

**Issue by aking4125** [AppliedEnergistics/Applied-Energistics-2#6036]
### Describe the bug

Hello,

Upon placing an ME Wireless Access Point to a working ME Network, the server crashes repeatedly until the WAP is removed or a backup is loaded prior to the installation of the WAP.
[crash-2022-01-29_21.05.19-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/7965178/crash-2022-01-29_21.05.19-server.txt)
.

### How to reproduce the bug

Place a WAP on a Fluix cable connected to a working ME network? A possible conflict I'm guessing.

### Expected behavior

Not crash? The game continues normally with the WAP working as intended?

### Which minecraft version are you using?

1.16

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/33Hf5bLB

**Comment by Ommina** [comment]
#6028 I believe.

**Comment by aking4125** [comment]
Copy. Tomorrow we'll try and remove the AE Infinity Booster mod and see how it goes.

**Comment by shartte** [comment]
Yeah this is a third party mod mixing into AEs code. You'll have to ask that mod's author for support.
