### ISSUE TITLE
AE2 crashes on loading appliedenergistics2:pattern_terminal with Magnesium [1.16.5]

### ISSUE THREAD

**Issue by DejaVuMan** [AppliedEnergistics/Applied-Energistics-2#6038]
### Describe the bug

With Applied Energistics 2 version 8.4.7, the game will instantly crash upon reaching the pattern terminal or monitor within the Creative Menu for items or searching for it within Just Enough Items. The error appears to be related to the rendering process and causes an ArrayIndexOutOfBoundsException for item 35. Here are two separate crash logs uploaded to PasteBin ([here ](https://pastebin.com/ugpQHqCB)and [here](https://pastebin.com/a7WAR3Kv)), also attatched below.

Edit: the same issue occurs both with magnesium 1.6 and 1.5: https://pastebin.com/cBpnVBxW

### How to reproduce the bug

Upon loading into game in creative mode, select the "Applied Energistics 2" tab from the item list and scroll down until you reach the row with terminal crafting items.

Alternatively, in survival mode with JEI, search for the word "monitor" or "terminal."

### Expected behavior

Upon searching for the item, I expected to be able to see the item in the creative mode item list or find it within JEI.

### Which minecraft version are you using?

1.16

### On which mod loaders does it happen?

Forge

### Crash log

Magnesium 1.6: https://pastebin.com/ugpQHqCB, https://pastebin.com/a7WAR3Kv, 
Magnesium 1.5: https://pastebin.com/cBpnVBxW

**Comment by Technici4n** [comment]
This looks like a magnesium issue, it's up to them to ensure that they don't break other mods' rendering.

**Comment by DejaVuMan** [comment]
@Technici4n Thats what I thought as well, although I wasn't too sure.

**Comment by shartte** [comment]
Yeah I don't feel like this is something we support / can work on.
