### ISSUE TITLE
Game not starting /crashing

### ISSUE THREAD

**Issue by Chaos4Link** [AppliedEnergistics/Applied-Energistics-2#6039]
### Describe the bug

On the newest Forge Version of the Mod 10.0.1 and also the new beta one(10.0.1.0-beta1) and Forge 39.0.64.
The mod keeps crashing my game on startup and my server after intialisation.

### How to reproduce the bug

Start the newest version of the mod and just wait for the crash.

### Expected behavior

Definetly not a crash.

### Additional details

Forge Versions above .45 have broken a few mods.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/7eg7bQ8B

**Comment by shartte** [comment]
Report this to "beyond_earth":

`Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [beyond_earth.mixin.json:ArmorTranslucent] from phase [DEFAULT] in config [beyond_earth.mixin.json] FAILED during APPLY`
