### ISSUE TITLE
Automatically give a bucket of fluid from ME

### ISSUE THREAD

**Issue by yorii** [AppliedEnergistics/Applied-Energistics-2#6040]
### Describe the feature

When clicking on a fluid in ME storage, and there is an empty bucket available, automatically give the player a bucket of said fluid.

### Reasons why it should be considered

Simple and excellent QoL improvement

**Comment by Technici4n** [comment]
Done in https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/6670.
