### ISSUE TITLE
Spatial storage not working exclusively on an FTB Endeavour server

### ISSUE THREAD

**Issue by IawahR** [AppliedEnergistics/Applied-Energistics-2#6042]
Spatial storage does not format or store anything when trying to use on a server, though it works fine it single player.
**Describe the issue**

Expected behaviour:
Upon creating a SCS around the desired area to store, and supplying enough energy to spatial IO port, contained area should be stored in the drive thus formatting the drive and working as intended. 
Actual behavior:
Nothing works even when done as per the instructions of 10s of YouTube videos, the wiki, and forums. Cell does not format. No energy is even used for some reason. Operation simply does not happen.
**Environment**

Server run on the FTB Endeavor pack version 1.9.0. Issue does not consist in single player. No config was edited server-side from default.

https://pastebin.com/qkR9E5KN

**Comment by shartte** [comment]
Please  enable the AE2 debug log *on the server* and provide the server-side log-file after trying the `/ae2 spatial` command, and moving something into spatial storage.

**Comment by IawahR** [comment]
I am not the server owner and my friend who is isn't super familiar with this sort of thing, what would be the best way for me to direct him through that process?

**Comment by IawahR** [comment]
We managed to find a solution. The drive just did not update saying that it was formatted, so it had a size associated with it that we just didn't know about.
