### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by PavloosCzM** [AppliedEnergistics/Applied-Energistics-2#6047]
### Describe the bug

Server crash

### How to reproduce the bug

IDK

### Expected behavior

IDK

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/PYi5JPLz

**Comment by yorii** [comment]
Memory slot #0 capacity (MB): 16384,00
	Memory slot #0 clockSpeed (GHz): -0,00
	Memory slot #0 type: DRAM
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): -0,00
	Memory slot #1 type: DRAM
	Memory slot #2 capacity (MB): 4096,00
	Memory slot #2 clockSpeed (GHz): -0,00
	Memory slot #2 type: DRAM
	Memory slot #3 capacity (MB): 1024,00

bro... 😐

**Comment by PavloosCzM** [comment]
Server is running on Vmware, AMD Ryzen 7 5800X 8-Core Processor, 29 GB RAM

**Comment by PavloosCzM** [comment]
Server running 24/7 wiith 15 players avarage, and crashes about 6 times a day with this error

**Comment by mindforger** [comment]
the getGridNode call is nullable in some cases and some not, though i do not know the interclass relations (without diving deeper into the code), but maybe refactoring some of the calls to use a different names if not nullable or making them all the same @nullable or @notnull would allow for better awareness, because if the call is nullable, it should be guarded against to not crash like in this instance

**Comment by yorii** [comment]
> Server is running on Vmware, AMD Ryzen 7 5800X 8-Core Processor, 32 GB RAM DDR4 3200Mhz, 7 Cores and 29Gb RAM reserved for server.

The error log indicates that it has 4 mismatched memory sticks though, one 16GB, one 8GB, one 4GB and one 1GB.
Which actually sounds highly unplausible as I don't think 1GB DDR4 memory even exists?
Are you sure the server doesn't have memory issues?

**Comment by shartte** [comment]
> the getGridNode call is nullable in some cases and some not, though i do not know the interclass relations (without diving deeper into the code), but maybe refactoring some of the calls to use different names if not nullable or making them all the same @nullable or @NotNull would allow for better awareness, because if the call is nullable, it should be guarded against to not crash like in this instance

This happens because it becomes null after the part has been destroyed. This is probably the system hanging onto a part in some place after the part has already been destroyed.

**Comment by PavloosCzM** [comment]
@yorii Yes serveru is virtualized under vmware, system have 32Gb 2x16gb but under virtual host where is server running is allocated 29gb

**Comment by PavloosCzM** [comment]
@mindforger @shartte So how i fix it ?

**Comment by Technici4n** [comment]
The truth is that we don't know how to fix it. If anyone can reproduce this with only ae2 and fabric, please open a new issue with detailed instructions.
