### ISSUE TITLE
Server crashing on startup

### ISSUE THREAD

**Issue by Chaos4Link** [AppliedEnergistics/Applied-Energistics-2#6048]
### Describe the bug

The server crashes while starting or if somebody joins it.

### How to reproduce the bug

N/A

### Expected behavior

A smooth server start.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/kWAuT4kH

**Comment by Technici4n** [comment]
This looks like a weird interaction with another mod. Do you have more insight? Please try removing mods until it works again, otherwise it's hard to guess which other mod might be involved.

**Comment by Chaos4Link** [comment]
I noticed that the mods BeyondEarth and TinkersContstruct in combination with AE2 crash the game, i also started each mod without AE2 and there i had no crash issues.
