### ISSUE TITLE
Fluid Cell Exclude Filter Not Working

### ISSUE THREAD

**Issue by damonmensch** [AppliedEnergistics/Applied-Energistics-2#6049]
### Describe the bug

Fluid cell partitioned in excluded precise to exclude lava and water is still allowing input of lava and water.

### How to reproduce the bug

Partition a fluid cell in the cell workbench with an inverter card and add both lava and water to the programming.

### Expected behavior

Water and lava to bypass the card with the exclude partition and instead go to the one with the include partition

### Additional details

- Minecraft 1.18.1
- Fabric 0.12.12
- AE2WTLib 10.0.0-release
- Applied Energistics 2 10.0.0

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

N/A

**Comment by mnsnownutt** [comment]
Not to hijack this, but I just had the same issue partitioning an item drive with an inverter card.  The item still went into the drive, in fact, it was the only thing that went into the drive, so it is just not registering.

Applied Energistics 2 10.0.0-beta.4
