### ISSUE TITLE
Dense Energy Cell Power Resetting

### ISSUE THREAD

**Issue by HauntedToast** [AppliedEnergistics/Applied-Energistics-2#6051]
### Describe the bug

When I am near my base, the power in the dense energy cell continuously goes up, but when I go into another dimension or far away from my base, the power resets on all the energy cells. This also happens when I log out and back in. 

Is this a chunkloading issue or is there some block I should use. I do not understand why the energy cells void the energy. I fed the alternator into a FE cell and it continuously powered even while I was in the nether.

### How to reproduce the bug

I have a windmill going into an alternator at max speed, which is feeding into an energy acceptor which is then feeding into 9 dense energy cells, then my me system which consists of a me crafting terminal, wireless access point, and security terminal. 

Go into another dimension or far away from the system and come back. It should have less power than when you left

### Expected behavior

The power should continuously go up

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

N/A

**Comment by shartte** [comment]
Please make sure ot provide the forced crash-log as it's described in the issue template because it contains important information about your minecraft instance (mod list, versions, etc.).

Also, please clarify:

- Are you using a chunk-loader? It's not clear from your issue
- At the start you say "reset" and "void", but in the second paragraph you say "it should have less", does that mean the energy level stays the same or does it "reset" to 0?

**Comment by HauntedToast** [comment]
I am not using a chunk loader since I do not want to lag my server. 

I was saying it should be less in the “reproduce the bug” section as to what the outcome was for me. It was never at zero because it would start charging again once I got closer to my base but it reset the power while I was away. In other words it voided or reset the power but as soon as I came back it would start charging again therefore being lesser

**Comment by HauntedToast** [comment]
I just added my infinity wireless booster to my wireless access point from AE infinity boosters mod and I can access my terminal even without power from range but the items do not show up. I think it is still the same issue but it is interesting that the terminal will pull up but not shoe items since it is off
