### ISSUE TITLE
Channels per player

### ISSUE THREAD

**Issue by Goten87** [AppliedEnergistics/Applied-Energistics-2#6052]
### Describe the feature

sins you now always have access to the controller and channel cables can you make it that we can set the option per player with a command and then the global option in the config file to be the default how it will set first time when someone logs in

### Reasons why it should be considered

not all people want to play with channels and some do
i have a few friends that loves to play with it and keep it in mind
but me personally always have it off on my server
so if we can set it per player i can leave the default option to default and then for me and other people who dont like it turn it off

this way we can enjoy the mod how we want it

### Additional details

if this is already in please explain how i can use it

**Comment by shartte** [comment]
It's not always possible to know the player for each network, this would be confusing as hell, as it would sometimes work, and sometimes it would not. This is already a problem for sub-networks without a security-station as they act as "anonymous" when they access the primary network.

So per-player will probably not happen unless someone comes up with an actual idea to implement it **well**.

**Comment by shartte** [comment]
I mean the one block we currently have that is definitely "owned" by a player is the security terminal.
But any subnetworks you have do not inherit the ownership info.
