### ISSUE TITLE
AE2 network crashing periodically and storage busses not working properly

### ISSUE THREAD

**Issue by amonymlive** [AppliedEnergistics/Applied-Energistics-2#6061]
### Describe the bug

I am experiencing a problem when using AE2 on a large scale in Antimatter Chemistry 1.2.34.

We are currently in the end phase of Avaritia and therefore dealing with around 1.5 - 2.5 billion items in the system. Most of them (>99%) are stored in black hole units that are connected with storage busses. This setup worked pretty well until recently when the network started to shut down periodically around every 30 - 60 seconds. The network starts back up after about 2-3 seconds and I have the suspicion that this causes other problems in the system.

For example, the storage busses that connect the black hole units randomly stop working and stuff that is supposed to go into the black hole units lands directly inside the storage cells.

Our setup includes 3 quantum bridges which are all powered themselves by Flux Network supplies. There are Dense Energy Cells in the main part of the system as well as every quantum bridge end point. I thought those would fix it but unfortunately this is not the case. Most of the items are imported by 16 importers from Ender Chests from EnderStorage. Basically all of the imported stuff is supposed to go directly into the black hole units which unfortunately does not fully work anymore since recently. 

I hope this is a bug and is fixable in some way. But it might also be the large scale of our project that is getting to AE2's limits :/

### How to reproduce the bug

Unfortunately I have no idea what caused this since the system worked fine with a ton of items until recently. I can't recall doing anything different than maybe accidentally forgetting to add a black hole unit which just results in a full system which I have to fix manually. Maybe we also reached a critical threshold of max holding capacity of a network..? I am not sure.

### Expected behavior

The system not periodically shutting down and the storage busses working as expected.

### Which minecraft version are you using?

1.12 - UNSUPPORTED

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/PkZUYwgp

**Comment by Technici4n** [comment]
Make sure that there is no chunk unloading, p2p tunnel or toggle bus causing the network to reboot.

Can't help further, 1.12 is discontinued and won't receive further support or patches.
