### ISSUE TITLE
Cables and facades

### ISSUE THREAD

**Issue by vVERMaNn** [AppliedEnergistics/Applied-Energistics-2#6062]
### Describe the bug

Hello, I have such a problem that I put a cable on it, but it has a different texture, as in the photo, there are no facades at all
![2022-02-08_20 29 20](https://user-images.githubusercontent.com/99281131/153043528-2eb0cd59-faac-413b-a4f7-22cd26a942b0.png)

### How to reproduce the bug

Install cable or facade

### Expected behavior

Item with different texture as picture

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://gist.github.com/vVERMaNn/dd73b37b4c28a51a3caff56451a605bf

**Comment by Mari023** [comment]
install indium
