### ISSUE TITLE
Pattern Provider Return Inventory rarely "keeps" the returning item in its inventory instead of returning to ae network

### ISSUE THREAD

**Issue by ceasefyre** [AppliedEnergistics/Applied-Energistics-2#6063]
### Describe the bug

Occasionally, pattern provider ends up with an item in their return inventory which does not get ingested back into the ae network. The crafting system thinks something is still being processed and just not finishing. The fix requires hunting down the pattern provider, removing and replacing the item into the return inventory. Interfaces do not seem to suffer from this issue

### How to reproduce the bug

Not entirely sure. Suspect it might be some timing issue, e.g. perhaps adding cables to the network while it is working on crafting something, forcing the network to 'recheck' itself and somehow overriding the trigger to let the provider know that something entered its inventory?

### Expected behavior

items in the return inventory of a Pattern provider should not 'hang out' when it is connected to an ae network with acceptable storage capacity.

### Additional details

Interfaces don't seem to face this issue anywhere. Somehow, the check for inventory contents gets skipped in pattern providers in a way where it does not appear to happen in interfaces. This is anecdotal, not heavily tested.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

N/A

**Comment by shartte** [comment]
If it ever happens again, can you try inserting more into the return inventory to check if it "wakes up" and sends it back to the network?
Alternatively, you can try giving yourself a debug card (`/give @s ae2:debug_card`), place it in your off-hand and look at the pattern provider. If you have WTHIT installed, you should be given a tooltip that says if the device is sleeping. That info would be important for analyzing this.

**Comment by Technici4n** [comment]
To anyone seeing this again, please follow the instructions on this page: https://appliedenergistics.github.io/debug-card, and post the debug card info.
