### ISSUE TITLE
[1.18.1, TerraForged] Meteors generate regadless common config

### ISSUE THREAD

**Issue by HonzaVinCZ** [AppliedEnergistics/Applied-Energistics-2#6066]
### Describe the bug

Meteors generate in my world even though I disabled them in my common config.

### How to reproduce the bug

Meteor generation is set to false in common config > I create a new world using TerraForged preset and meteors are present.

### Expected behavior

Meteors are not supposed to spawn in my world. 

### Additional details

Mod list:

AdChimneys-1.18.1-7.0.0.1-build.0043.jar                             
AdditionalEnchantedMiner-1.18.1-18.5.jar                             
AdPother-1.18.1-5.0.0.0-build.0049.jar                               
alexsmobs-1.17.0.jar                                                 
AmbientEnvironment-forge-1.18.1-7.0.4.jar                            
AmbientSounds_v5.0.8_mc1.18.1.jar                                    
animal_feeding_trough-1.0.3+1.18.1-forge.jar                         
appleskin-forge-mc1.18-2.2.0.jar                                     
appliedenergistics2-10.1.0-beta.2.jar                                
architectury-3.4.9.jar                                               
BetterF3-1.2.2-Forge-1.18.jar                                        
BiomesOPlenty-1.18.1-15.0.0.104-universal.jar                        
bwncr-forge-1.18.1-3.10.18.jar                                       
catalogue-1.6.0-1.18.1.jar                                           
cc-tweaked-1.18.1-1.100.2.jar                                        
chipped-1.18.1-1.2.1-forge.jar                                       
citadel-1.10.10-1.18.jar                                             
cloth-config-6.1.48-forge.jar                                        
configured-1.5.1-1.18.1.jar                                          
Connectible+Chains-forge-1.18.1-2.0.1.jar                            
connectivity-1.18-2.5.jar                                            
Controlling-forge-1.18.1-9.0.6.jar                                   
corpse-1.18.1-1.0.0.jar                                              
CreativeCore_v2.4.1_mc1.18.1.jar                                     
DistantHorizons-1.6.0a-1.18.1.jar                                    
engineersdecor-1.18.1-1.1.19-b2.jar                                  
EnhancedVisuals_v1.4.4_mc1.18.1.jar                                  
FallingTree-1.18.1-3.2.1.jar                                         
FarmersDelight-1.18.1-1.0.3.jar                                      
farsightedmobs-forge-1.1-1.18.jar                                    
FastFurnace-1.18.1-6.0.2.jar                                         
FastWorkbench-1.18.1-6.0.1.jar                                       
flan-1.18.1-1.7.1-forge.jar                                          
ForgeEndertech-1.18.1-8.0.0.0-build.0040.jar                         
guardvillagers-1.18.1.4.0.jar                                        
hardcore_torches_forge-2.0.jar                                       
ImmersiveEngineering-1.18.1-7.1.0-145.jar                            
incontrol-1.18-6.0.0.jar                                             
inventorysorter-1.18-19.0.0.jar                                      
ItemPhysic_v1.4.20_mc1.18.1.jar                                      
Jade-1.18-4.1.2.jar                                                  
jei-1.18.1-9.3.2.92.jar                                              
journeymap-1.18.1-5.8.0beta14.jar                                    
JustEnoughResources-1.18.1-0.13.1.138.jar                            
Kiwi-1.18-forge-5.2.2.jar                                            
kubejs-forge-1801.4.1-build.271.jar                                  
kubejs-immersive-engineering-1801.2.0-build.16.jar                   
lctech-1.18-0.0.2.0.jar                                              
lightmanscurrency-1.18-1.0.3.4.jar                                   
maessentials-1.18-3.7.1.jar                                          
mods.txt                                                             
OptiFine_1.18.1_HD_U_H4.jar                                          
Patchouli-1.18.1-61.jar                                              
Placebo-1.18.1-6.1.0.jar                                             
rhino-forge-1800.1.7-build.92.jar                                    
rsgauges-1.18.1-1.2.13-b2.jar                                        
ScalableCatsForce-2.13.7-build-2-with-library.jar                    
seamless_loading_screen-1.18-3.0.0.jar                               
SereneSeasons-1.18.1-6.0.0.8-universal.jar                           
SimpleLogin-1.18-1.0.1.jar                                           
SnowRealMagic-1.18-forge-3.2.2.jar                                   
soundphysics-forge-1.18.1-1.0.4.jar                                  
stoneholm-1.4.1.jar                                                  
taterzens-1.8.3-forge.jar                                            
TerraBlender-forge-1.18.1-1.1.0.72.jar                               
TerraForged-1.18.1-0.3.0-alpha-2.jar                                 
ThisRocks-1.18.1-1.0.0.jar                                           
ToastControl-1.18.1-6.0.0.jar                                        
ToughAsNails-1.18.1-6.0.0.67-u
niversal.jar                           
Trapcraft-1.18.1-3.6.0.jar                                           
voicechat-forge-1.18.1-2.2.5.jar                                     
[1.18.1]+SecurityCraft+v1.9.0.2-beta1.jar                            

Latest Log:
[latest.log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/8054696/latest.log)

Screenshots:
![2022-02-13_00 16 11](https://user-images.githubusercontent.com/29098779/153732084-c62608e4-8f87-4554-bdd1-5c3d3287a6a7.png)

![Snímek obrazovky 2022-02-13 002835](https://user-images.githubusercontent.com/29098779/153732096-522bdb1a-b6e9-4ee5-a8be-f57104766e1c.png)

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

No crash log avaible

**Comment by Technici4n** [comment]
Solved in 1.18.2 since you can ensure that the `ae2:has_meteorites` biome tag is empty.
