### ISSUE TITLE
ME Interface doesnt have pattern section of the UI

### ISSUE THREAD

**Issue by BigBorgerMan** [AppliedEnergistics/Applied-Energistics-2#6067]
I am on a Minecraft server with a bunch of my friends on 1.18 all of fabric 5, and for some reason when i went to make the auto crafting stuff for the ME system it just doesn't have the pattern section
![bug](https://user-images.githubusercontent.com/99578092/153740722-9c3e34f0-28cb-417e-8b7f-c1543f67055c.png)

**Comment by BigBorgerMan** [comment]
![bug2](https://user-images.githubusercontent.com/99578092/153740744-ecc7cac8-5733-4460-86ff-a19177bb40f6.png)
This is the whole system I got going on (i know it isnt the most beautiful thing but im fixing it once i fix the problem)

**Comment by ramidzkh** [comment]
You need to use the ME Pattern Provider instead of the ME Interface
