### ISSUE TITLE
ME Toggle Bus & ME Level Emitter create infinite Network Booting

### ISSUE THREAD

**Issue by joshuaberube** [AppliedEnergistics/Applied-Energistics-2#6072]
### Describe the bug

When using an ME Toggle Bus (and Inverted Toggle Bus) paired with the ME Level Emitter connected to the ME system (it doesn't matter if the cables are connected to each other or if it's connected to different sides of the Controller), due to the nature of the Toggle Bus rebooting the network every time it switches between on/off (not sure if this is intentional), it causes a network reboot, which in turn, turns off the Level Emitter, but when it boots up again, the level Emitter turns back on, thus changing the state of the Toggle bus (hence the infinite loop).

![1a4bf7f0f37b289e53beaabc4c62d897 (1)](https://user-images.githubusercontent.com/59525363/153971280-a008aa85-92e6-428e-b860-65e7b05e7e63.gif)

### How to reproduce the bug

Connect a Fluix cable (doesn't matter if it's dense, covered, or smart) to the ME system. Have it come out a couple blocks or so to make it easier, then on the cable, add an ME Toggle Bus following along with the cable direction (you can also use ME Inverted Toggle Bus, both cause the bug). Then, add a second cable line, either from the ME Controller or branching off the original cable to the block above the Toggle bus. Then, on the cable that's now above the Toggle Bus, add a Level Emitter facing downwards (you may need to replace the toggle bus for the two cables to not connect. You can mess with the redstone settings, add a crafting Card, whatever you want, it will cause the infinite loop to occur when the Level Emitter gives off a redstone signal.

### Expected behavior

The ME Toggle to toggle on once with the Level Emitter and toggle off when the emitter is turned off.

### Additional details

I'm using version 10.0.0 release, but I have also tested this on 10.1.0-beta.2 and the same thing occurs.

This Bug is caused by the network reboot happening when the bus state is changed. If there was a way to disable that, then it would fix the bug (I'm not sure what other bugs this may cause though). I would be happy to fix it and submit a PR, however I am not experienced in Java so I could not find where the update in state causes the network to reboot

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/9UBDryUM

**Comment by ruifung** [comment]
I may be mistaken but...

Isn't this the existing intended behavior of AE networks? I.e. network reboot on change of network layout (i.e. / adding or removing devices.)

And toggle busses generally *will* cause a change in network configuration.

Unless it's only connected to quartz fiber, or on the other side of a subnetwork link.

**Comment by joshuaberube** [comment]
> I may be mistaken but...
> 
> Isn't this the existing intended behavior of AE networks? I.e. network reboot on change of network layout (i.e. adding or removing devices.)
> 
> And toggle busses generally _will_ cause a change in network configuration.
> 
> Unless it's only connected to quartz fiber, or on the other side of a subnetwork link.

If it is, do you have any idea how to get a similar setup with how AE2 currently works? Basically I only want it to collect the cobblestone (which is getting it via an Annihilation plate and a cobble gen farm) if I set it to craft it or if it needs it in a recipie. Currently that’s the only way that I can think of (without having the cobble gen just fill up a subnetwork or something).

**Comment by Tahakk** [comment]
Let it run on subnetwork pushing it into some kind of buffer that is possible to output redstone (drawer, chest etc.) and only stop it when it's full.

Than put importer for your main and if need it turn in on by the redstone signal.

**Comment by ruifung** [comment]
`main net -> interface <- storage bus -> toggle bus -> annihilation planes.
                  |---------------> lvl emitter ^`
Have the level emitter set to crafting provide cobble.

Or yknow, just assign it to stockpile cobble instead (configure level emitter to cobble level).

**Comment by joshuaberube** [comment]
> 

This worked- I hadn't thought about the fact of having a toggle bus on subnetwork would allow it to not restart the entire network. Thanks! I'll close this now as I assume that it is in fact intended behavior (although still confused about how the guy in the video got it to work). Hopefully this helps anyone who has had this issue

**Comment by ruifung** [comment]
> > 
> 
> This worked- I hadn't thought about the fact of having a toggle bus on subnetwork would allow it to not restart the entire network. Thanks! I'll close this now as I assume that it is in fact intended behavior (although still confused about how the guy in the video got it to work). Hopefully this helps anyone who has had this issue

Just briefly skimmed that video but... unless I'm remembering wrongly, don't annihilation planes take redstone cards? You could literally directly level emitter it.
