### ISSUE TITLE
Invisible Blocks Fabric 1.18.1

### ISSUE THREAD

**Issue by Gamerbolts** [AppliedEnergistics/Applied-Energistics-2#6073]
### Describe the bug

I am creating a rather large modpack. When I was working on quests for AE2 I decided to go and mess with the blocks and build myself an ME system. I placed down a Drive, then some cables and the drive and cables became invisible. They were ghost blocks I could still run into them, but waila was not picking them up and I could not go past them. When I placed more blocks down they would sometimes appear. But then I would place other cables and they would disappear.

I did have Sodium/Indium/Lithium/Phosphor/Iris Shaders installed and I removed all of those and it was still happening. I had just AE2, AE2Things and Wireless Terminals and it worked as normal.

My modlist
https://docs.google.com/spreadsheets/d/1S--Gsjqe4B8BPipKmOJVyV7nim12h63TUyKee_alI60/edit?usp=sharing

### How to reproduce the bug

It is a conflict of a mod that I am sure of. I just do not know which mod or mods are causing it or if you can look at the logs and see if there is anything that can be done.

### Expected behavior

The cables to not disappear when placed.

### Additional details

Server Log
[latest.log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/8092068/latest.log)

Client Log
[latest.log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/8092071/latest.log)

Any help is appreciated. Thank you!

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/d8DaqtwN

**Comment by Mari023** [comment]
two things you can try to narrow down the problem:
1. post the output from the debug card (see [this](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/5972#issuecomment-1019317341) comment on how to use it)
2. do a binary search, where you remove half of the mods (while keeping ae2 of course) until only the mod(s) which are causing it are left

I have a feeling it could be bclib, so you might want to try that first

**Comment by Gamerbolts** [comment]
I will try this :) Ty!

**Comment by Gamerbolts** [comment]
It's a mod called Super Block World. no idea why it is doing that. But I removed SBW from my server and the cables did not disappear. I readded SBW and used the same world and the cables started disappearing... No idea how or if this can be fixed so I guess I'll just remove SBW from my modpack.

**Comment by artheus** [comment]
@Gamerbolts From what I can see in the Super Block world mod, they are using a lot of mixins.
Some of which changes how the world/biomes/blocks behave, so I am guessing that the mod authors probably is not thinking much about how this might affect other mods.
So I think you should rather create an Issue ticket on their Github issue tracker, and explain this behaviour there.
This issue should be closed here.

**Comment by Gamerbolts** [comment]
@artheus Thanks I will do that!
