### ISSUE TITLE
 Redstone p2p tunnel does not work

### ISSUE THREAD

**Issue by Awesomerem1** [AppliedEnergistics/Applied-Energistics-2#6076]
### Describe the bug

I am unable to get the redstone p2p tunnel to get a "code" from the memory card

### How to reproduce the bug

When using a memory card on the p2p tunnel i am getting an invalid machine dialogue from the game

### Expected behavior

p2p tunnel should get a "code" and the memory card should remember this "code" so that it can be used on other tunnels

### Additional details

I am finding this on the All The Mode 7 modpack
There is also no crafting recipe for the redstone p2p tunnel

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/zvcXx9gZ

**Comment by Ommina** [comment]
In earlier versions (and I've no idea if this still applies or not, so this is very much a shot in the dark), that particular message would appear if there was an item in the offhand.  So ensure your offhand is empty.

None of the non-ME tunnels have a crafting recipe; they are placed in world as an ME tunnel, then whapped with some item to change their target.  Redstone torch would presumably work for a redstone tunnel.

**Comment by Technici4n** [comment]
The redstone p2p tunnel works like the others.
