### ISSUE TITLE
1.16.5 Server crashes upon placement of wireless access point

### ISSUE THREAD

**Issue by LordBumfuzzleVI** [AppliedEnergistics/Applied-Energistics-2#6077]
### Describe the bug

Server immediately crashes upon placing down a wireless access point within the world, throwing out a java.lang.ClassNotFoundException error. This crash allows the server to still save the world, consequently borderline corrupting the chunk it was placed in. This issue does not occur in singleplayer and is restricted to the multiplayer server.

### How to reproduce the bug

On a 1.16.5 dedicated server running forge 36.2.28, with a whole range of mods installed (mod list provided in crash log, unsure if one of those is somehow causing the issue), place down a wireless access point somewhere in the world. Game then forcibly disconnects the player showing the "java.lang.ClassNotFoundException" error screen (might not be the exact wording but I think you get the idea. Server console shows similar error. Upon loading back into server and loading the chunk, server again crashes like before.

### Expected behavior

idk, that it kinda just works like it should, like it does in singleplayer and has done in the past on a server, without the whole crashing thing.

### Which minecraft version are you using?

1.16

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/Aq42LC0J

**Comment by ProjectET** [comment]
issue is with ae2wtlib

**Comment by shartte** [comment]
> mixin:APP:AEInfinityBooster.mixins.json

Yeah, that's not fixable on our end, sorry.

**Comment by DurekuRyuu** [comment]
thank @ProjectET 
just ran into this problem myself.
