### ISSUE TITLE
is:issue is:open  game crashes if you craft a 16k crafting storage 

### ISSUE THREAD

**Issue by PORKOYAGER** [AppliedEnergistics/Applied-Energistics-2#6078]
is:issue is:open  game crashes if you craft a 16k crafting storage

**Comment by PORKOYAGER** [comment]
is:issue is:open  game crashes if you craft a 16k crafting storage

**Comment by shartte** [comment]
Please provide the information requested in the issue template.

**Comment by Technici4n** [comment]
Please reopen with the requested info.
