### ISSUE TITLE
Fabric: Sources jar doesn't keep the Minecraft class mappings.

### ISSUE THREAD

**Issue by artheus** [AppliedEnergistics/Applied-Energistics-2#6079]
### Describe the bug

While inspecting the AE2 sources there are a lot of errors related to Minecraft mappings not being preserved. This makes e.g. IDEA complain a lot about that the source code does not match the bytecode for classes.
It is annoying, but not necessarily a big problem.

### How to reproduce the bug

1. Create a new fabric mod
2. Add dependencies for AE2 api, as described in AE2 README
3. Navigate to view source code of e.g. `ICablePart`

This will show that e.g. `net.minecraft.world.entity.player.Player` is `net.minecraft.class_1657` which is not what is expected.

### Expected behavior

`net.minecraft.world.entity.player.Player` class in the AE2 Source jar should be shown as `net.minecraft.world.entity.player.Player` and not `net.minecraft.class_1657` which is currently shown.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

not relevant

**Comment by Technici4n** [comment]
#6450 is the solution, hasn't been implemented yet though.
