### ISSUE TITLE
Crafting stuck at Simulation mode.

### ISSUE THREAD

**Issue by mobehun** [AppliedEnergistics/Applied-Energistics-2#608]
I've been playing with AE2 for a while now but never seen something like this happen. Currently I'm using version rv2.alpha build 29 with The Dark Trilogy modpack.
When I try to auto-craft anything I get this:
http://i.imgur.com/8lmS03z.png
This is the setup I have currently:
http://i.imgur.com/p2yTIsw.png (1x4K Crafting Storage, 8xCrafting Co-Processing Unit)
http://i.imgur.com/PWCgBJP.png

**Comment by adasneves** [comment]
@mobehun I don’t know if you fixed it, but one think you meet to do is to remake the pattern, and click ignore NBT tags. This will stop checking metadata, and nbt tags

**Comment by mindforger** [comment]
Wow... Okay, you checked this post is 3 years old?

**Comment by JantoolHD** [comment]
I can confirm that this is still happening as of today with version 1.12.2 rv6 stable 7. Most important is that this only happens if you try to craft IC2 items/blocks.

Some pics of my Setup:
https://imgur.com/a/aAXrvjz

**Comment by Tahakk** [comment]
It would be nice if you created new issue than digging up old ones :)
If you want you can refer to this one via link
