### ISSUE TITLE
server crash atm6

### ISSUE THREAD

**Issue by zxoltari** [AppliedEnergistics/Applied-Energistics-2#6081]
### Describe the bug

atm6 stalls when there is plugins and was told by someone that it was caused by ae2 ERROR Exception caught during firing event: null

### How to reproduce the bug

if you add magma or mohist on atm6 the server will run for a min then stall 

### Expected behavior

i expect it to run fine but is not doing soo

### Which minecraft version are you using?

1.16

### On which mod loaders does it happen?

Forge

### Crash log

https://mclo.gs/qy85n2V

**Comment by zxoltari** [comment]
i am using the newest update of ae2

**Comment by Technici4n** [comment]
Well if you say that a plugin causes this, then clearly the plugin is to blame, not AE2. We only support normal forge and forge mods, not plugins.
