### ISSUE TITLE
ME bus failure

### ISSUE THREAD

**Issue by DekuMania** [AppliedEnergistics/Applied-Energistics-2#6087]
**Describe the issue**
Almost all of my ME import and export busses are not working, or working intermitedly. The storage bussed and interfaces for autocrafting are working like normal.

I am on FTB revelations 3.5.0 and the AE2 is Applied Energistics 2 rv6-stable-7

However this issue occured in FTB revelations 3.4.0 I am unsure if theres any difference in the ARe.

I have done some research before comeing here and I have checked my channels and none are over 32.
Power whise on my ME are as follows.
Energy usage: 7.35 kRF
Energy generation: 7.35 kRF
Max power: 66.22 MRF
Stored when being viewed doesn't dip below 65 MRF

This is being experienced on all deminsions with my system. For example overworld and minding dimension. I can only confirm one export that is consistently working and one of each the has sparkly worked. All devices say online and all quantum rings have power on both sides.

I have 20 dense storage cells and 5 energy cells.

Logs
Latest
Https://paste.feed-the-beast.com/view/03f3fa10
Debug
I am working on getting this one but its not letting me paste it.

**Comment by Technici4n** [comment]
Sorry, 1.12 is not supported anymore.
