### ISSUE TITLE
[BUG] Fabric 1.18 having issue with move items button visual

### ISSUE THREAD

**Issue by ilkerbey-01** [AppliedEnergistics/Applied-Energistics-2#6088]
### Describe the bug

When you view a recipe with REI in crafting terminal it should show the missing ingredients, instead it is making the + button yellow tint only if you have a missing ingredient.

### How to reproduce the bug

Make an average disk system with crafting panel
Open the terminal and look up for a random craft that you dont have ingredients (only one or all) 
Instead of + (move items button) turning red and highlighting missing ingredients it just makes + button yellow tint

### Expected behavior

Show what I am missing

### Additional details

![unknown-6](https://user-images.githubusercontent.com/34978332/156153648-91974499-0b97-4e61-bb4e-860774bc6ec0.png)

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://paste.ee/p/myoae

**Comment by Technici4n** [comment]
Fixed in #6349.
