### ISSUE TITLE
Model rendering errors with Sodium (v10.1.0 beta.2 @ fabric)

### ISSUE THREAD

**Issue by orbyfied** [AppliedEnergistics/Applied-Energistics-2#6089]
### Describe the bug

I haven't tested all models, but it looks like most of them are fine.
So far I have encountered:
- Facades in don't render correctly in item form or in block form.
- ME drives dont render correctly when placed.
- Cables don't render correctly.
When I say "don't render correctly", I mean that the blocks have the full block purple and black error model, and items have the full square purple and black model (full cube when held in hand).

It seems like dynamically generated models don't work correctly, as both cables and ME drives change their model based on multiple factors, like connections or drives inserted. One thing I noticed is that the hitbox/collision box still works and seems to correspond with the correct connection states on cables.

I tested with and without Sodium and Sodium seems to be the problem. Although this is not a massive concern it would be nice if it could somehow be fixed for QOL.

**Screenshot:**
![2022-03-01_18 07 14](https://user-images.githubusercontent.com/72315780/156215358-747c0f87-16ae-4369-8f3a-e40462066075.png)

### How to reproduce the bug

I am on Minecraft version `1.18.1`, with Fabric loader `0.12.12` and Fabric API `0.44.0`.
I'm using AE2 release `10.1.0 beta 2`.
I additionally have 2 rendering related mods:
```
Phosphor 0.8.1
Sodium 0.4.0
```
**Image of my mods folder:**
![image](https://user-images.githubusercontent.com/72315780/156215825-38675590-79ce-4cb4-935d-6f5d0e192100.png)

### Expected behavior

I expected the blocks and items to render correctly.

### Additional details

All information needed should be in the `How to reproduce.` field.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/ujybbPjj

**Comment by XFactHD** [comment]
You need to install Indium when you are using Sodium.

**Comment by orbyfied** [comment]
ah thanks
