### ISSUE TITLE
[BUG] Tweakaroo mod accurate placing setting

### ISSUE THREAD

**Issue by ilkerbey-01** [AppliedEnergistics/Applied-Energistics-2#6090]
### Describe the bug

when accurate placing option and the setting right below it in its menu(forgot its name sorry) enabled, ae2 terminals cant be opened.

### How to reproduce the bug

Install Tweakaroo and ae2
enable accurate placing and option below it
try to open a terminal

### Expected behavior

supposed to open the terminal when right clicked

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

Not related to a crash

**Comment by shartte** [comment]
You should report this to Tweakaroo, not us.
