### ISSUE TITLE
Client crash when entering server - ae2:qnb duplicate registraction

### ISSUE THREAD

**Issue by WanderingCat27** [AppliedEnergistics/Applied-Energistics-2#6092]
### Describe the bug

Crashes before even seeing the world of the server, goes from connecting to crash, this started happening yesterday and happens quite often, yet inconsistently. To get around this I just keep restarting the launcher until I make it into the server. This is ae2 10.0 fabric. I assume it is an ae2 bug because it is the only mod I see mentioned in the crash report right at the bottom.

### How to reproduce the bug

no idea what is causing it in particular, it only started yesteraday, but it happens quite often now

### Expected behavior

enter server without crashing

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/FqZvdMNE

**Comment by Technici4n** [comment]
Seems like an unrelated issue. The mention of AE2 appears to be a bad interaction with not enough crashes, not our fault.

**Comment by henrybleitch** [comment]
I'm having the same bug on Fabric 1.18.2, ae2 version 11.1.2 - did you find a solution for this?
