### ISSUE TITLE
Craft on Demand Not Working

### ISSUE THREAD

**Issue by Solverbolt** [AppliedEnergistics/Applied-Energistics-2#6098]
### Describe the bug

Attempting to use any AutoCrafting or Crafting on Demand is not working, except for one item. and I have done nothing different between the setups. 
(i apologize for the terrible circle for the one item that does work, becamse disabled and lost a lot of motor function)
![image](https://user-images.githubusercontent.com/38087746/156903752-03bc3e81-a0b7-43b2-b676-144bf9fedb0c.png)
![image](https://user-images.githubusercontent.com/38087746/156903764-86f1392f-b17b-4cc2-a4f3-f9eaa5da8866.png)
![image](https://user-images.githubusercontent.com/38087746/156903778-dd1a75ec-30be-4bbf-8095-cc7c8a841988.png)
![image](https://user-images.githubusercontent.com/38087746/156903829-0790bdfc-7ad4-4902-b721-7a6e21f3b7bc.png)
![image](https://user-images.githubusercontent.com/38087746/156903879-2c632cf3-f4c1-4a06-8812-a03548e1c243.png)
![image](https://user-images.githubusercontent.com/38087746/156903889-454711da-c3b8-4ca1-bf07-1a1cc47c7563.png)

### How to reproduce the bug

I carefully encoded each recipe with substitutions, just to avoid hassle in case i have dozens of different colors of wool. 
I put each recipe into an ME Interface tied to the molecular assemblers, then placed them in the pattern storage also attached. 
(refer to images)
In the case of some recipes that need to process through Inscribers, I set the recipe for each in the interface attached to said inscriber that matches, As I have done countless times before.  

System recognizes the patterns are there, even sends the information to the crafting computer setup, but then it just stalls out. I have plenty of parts to make hundreds of the item in question, but the system wont pull the items to the assemblers. 

### Expected behavior

Request item to be crafted:  
Item Crafts, 
Sends item back to AE system once completed

### Additional details

I have been using AE since the beginning, because it made so many different things possible in the past. Not sure what changed. Before, when you made certain patterns, like for the inscribers, you placed that pattern into the Interface that was attached to the inscribers, and the system recognized it perfectly. I could tell it I wanted 1000 logic circuits, and it worked without a hiccup as long as I had the CPU Core to handle it. 

Not anymore, and I am not sure where the issue is. The only thing that has changed from the past to now is the pattern provider. That was never in the previous versions i used. 

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/Solverbolt/ec5fccd19ee4dc732a6d125fca399065

**Comment by EnderProyects** [comment]
The pattern provider needs to be next to the molecular assembler

**Comment by Technici4n** [comment]
The pattern providers replace the interfaces, they should be next to the molecular assemblers.
