### ISSUE TITLE
1.18.1 Fabric - Crash with incompat between Reasonable Sorting, Applied Energetics 2 and Universal Graves

### ISSUE THREAD

**Issue by davidalb97** [AppliedEnergistics/Applied-Energistics-2#6101]
### Describe the bug

The game crashes when Reasonable Sorting, Applied Energetics 2 and Universal Graves are installed on the client, 
server has Applied Energetics 2 and Universal Graves. To crash, switch to creative and access inventory.

**Mod List: (Client)**
- ae2 10.1.0-beta.2
- cloth-config 6.2.57
- fabric 0.46.6+1.18
- fabricloader 0.13.3
- reasonable-sorting 1.5
- universal-graves 2.0.0-rc.5+1.18.1

**Mod List: (Server)**
- ae2 10.1.0-beta.2
- cloth-config 6.2.57
- fabric 0.46.6+1.18
- fabricloader 0.13.3
- universal-graves 2.0.0-rc.5+1.18.1

### How to reproduce the bug

- Run a local server with the installed mods (excluding reasonable-sorting);
- Run minecraft client with all the mods;
- Join the server;
- In the server console, change gamemode from survival to creative;
- In the client, access the inventory, causing the game to crash.

### Expected behavior

Can access the creative inventory without the game crashing, the inventory should be sorted with Reasonable Sorting mod.

### Additional details

**OS:** Linux (amd64) version 5.16.11-2-MANJARO
**DE:** KDE
**Java:** OpenJDK 17.0.3
**MC Version:** 1.18.1

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/1kLK5qqn

### Issues on the other mod repositories:
Patbox/UniversalGraves: https://github.com/Patbox/UniversalGraves/issues/68
SolidBlock-cn/reasonable-sorting: https://github.com/SolidBlock-cn/reasonable-sorting/issues/7

**Comment by Technici4n** [comment]
Seems to be an issue with the other mods not supporting modded creative tabs.
