### ISSUE TITLE
[Crash] Tried to enter the world

### ISSUE THREAD

**Issue by DoctorSigma** [AppliedEnergistics/Applied-Energistics-2#6102]
### Describe the bug

When I tried to enter the world I was scared, it's like the problem of compatibility with the Chunk Loaders mod from
SuperMartijn642.
I wrote to the Chunk Loaders fashion designer
and gave it a crash, he said sho it's a problem in your fashion or it's not compatibility ...

### How to reproduce the bug

Try to enter the world

### Expected behavior

-

### Which minecraft version are you using?

1.16

### On which mod loaders does it happen?

Forge

### Crash log

crash - https://gist.github.com/4a0d1c313b69d54455a3cbfb153c99f2.git latest - https://gist.github.com/e3c5f489950d5608188b58f6c2b5e830.git

**Comment by shartte** [comment]
It's incompatible.
The chunkloader mod is loading the chunk before the world has completed loading.
Forge has it's own chunkloading API, which is compatible with AE2.
Sorry, but we're not going to implement specific compatibility with this mod in 1.16.
