### ISSUE TITLE
Missing textures for items

### ISSUE THREAD

**Issue by CashierNub** [AppliedEnergistics/Applied-Energistics-2#6103]
### Describe the bug

please fix the missing textures on the 1.17.1 fabric versions

### How to reproduce the bug

just do sum code

### Expected behavior

i expect a new applied energistics for 1.17.1 bc i just was recording and then i saw when i place some blocks it was the missing texture texture

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/B4QPjHwZ

**Comment by Mari023** [comment]
you are using sodium, you need indium too
