### ISSUE TITLE
[1.17.1 FABRIC] AE2 + Sodium + Indium = Rendering Issues (appeng.blockentity.crafting.CraftingCubeModelData.getForward()" because "modelData" is null)

### ISSUE THREAD

**Issue by MSandro** [AppliedEnergistics/Applied-Energistics-2#6105]
### Describe the bug

not sure if this is an issue with AE2 or Indium.
Here you can find additional infos: https://github.com/comp500/Indium/issues/107

### How to reproduce the bug

install Sodium, Indium and AE2 on Fabric 1.17.1
I am playing on an Server, so no idea if this also happens in SP
build an AE2 System.
leave the area so the chunk with the ME-System will be unloaded
travel back.
Blocks will be invisible.

### Expected behavior

blocks should be visible

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

https://gist.github.com/MSandro/285cf68623a45784df45244485ab3b98

**Comment by shartte** [comment]
Can you please provide a full forced crash-log? It includes all mod-versions.

But yeah, we can probably guard against the model-data being null, but the underlying issue is: why is it null in the first place... (We still could not render anything sensible)

**Comment by MSandro** [comment]
![image](https://user-images.githubusercontent.com/10937159/158174516-437ccd1b-34c9-4cea-a4f1-b499ddefa2e9.png)
it does not crash.

**Comment by shartte** [comment]
That's why I said "forced". If you open a new issue, the issue description tells you how to *force* a crash to get a crashlog with all the mod versions (hint: hold F3+C)

**Comment by MSandro** [comment]
oh, thank you, but I kept trying to get to the bottom of the problem. Apparently an update of the Iris Shader Mod fixed the problem. So I'm closing this issue, thanks for the quick replya.
