### ISSUE TITLE
ME dense smart cable render wrong connected to a p2p tunnel

### ISSUE THREAD

**Issue by FlorianTyroller** [AppliedEnergistics/Applied-Energistics-2#6107]
### Describe the bug

ME dense smart cable render wrong connected to a p2p tunnel

### How to reproduce the bug

connect dense smart cable to p2p tunnel looks like this: 
![dense2](https://user-images.githubusercontent.com/51460328/158692682-f8efa766-63f8-421a-b774-eaade5440553.png)

### Expected behavior

this is how it looked in earlier versions: 
![dense1](https://user-images.githubusercontent.com/51460328/158692552-8df8484d-eae7-4a28-9008-df26f6e35e2d.png)

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

-

**Comment by Technici4n** [comment]
Fixed by #6126.
