### ISSUE TITLE
Game Crashes after linking export and import Bus to Immersive Engineering squeezer, fermenter and refinery 

### ISSUE THREAD

**Issue by freaki2010** [AppliedEnergistics/Applied-Energistics-2#6108]
### Describe the bug

* After I linked export and import bus to a squeezer, fermenter and refinery from Immersive Engineering my game crashed. 
* All machines where connected over the same cable tree.
* It's a Singleplayer world. 

* Squeezer import and export works.
* fermenter import and export works.
* When refinery start with processing the fluids the game crashes.
* I am exporting the fluids from squeezer and fermenter to the ME and export them to the refinery. 

### How to reproduce the bug

link export and import bus to  following immersive engineering machines: squeezer, fermenter and refinery.

### Expected behavior

The game should not crash. 

### Additional details

Forge version: forge-1.18.1-39.0.63-universal.jar
AppliedEnergistics version: appliedenergistics2-10.1.0-beta.1.jar
Immersive Engineering version: ImmersiveEngineering-1.18.1-7.1.0-145.jar

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/wBJixMvc

**Comment by Technici4n** [comment]
Should be fixed in the next release.
