### ISSUE TITLE
[1.17.1 FABRIC] rendering issue cause crash once I connect to the server

### ISSUE THREAD

**Issue by MSandro** [AppliedEnergistics/Applied-Energistics-2#6110]
### Describe the bug

I have no idea why it's happening. I've had some rendering issues with AE2 in 1.17.1. Now that I removed all performance mods like Sodium, Ferrite Core, Lithium, Phosphp and more my modpack crashes immediately.
I was able to play on my server for over an hour today. Suddenly my client crashed. Now when I try to reconnect, the modpack crashes again immediately.

I hope someone can help me soon.

### How to reproduce the bug

Sorry, I can not provide an exact task list.
the issues feels a bit random.

### Expected behavior

not crashing the game.

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

https://gist.github.com/MSandro/8d583a5a4a1c68c8c0879416e82265c0

**Comment by MSandro** [comment]
I am not an good Mod Dev, instead I am C# Programmer, but an Null Exception should not be that hard to fix!
```
"appeng.blockentity.crafting.CraftingCubeModelData.getForward()" because "modelData" is null
```

**Comment by MSandro** [comment]
I am not sure if this is an client or server issue, but now I have restarted my server and the problem is gone for now.

**Comment by MSandro** [comment]
New info: it is not an issue with the Wireless Terminal Mod!
https://github.com/Mari023/AE2WirelessTerminalLibrary/issues/130#event-6270515978

**Comment by MSandro** [comment]
Might be related to https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/6105
But as in this case I have removed Sodium and now the Modpack crashes

**Comment by 0gp** [comment]
same here:
![image](https://user-images.githubusercontent.com/62187599/159251779-ffc5617b-4332-41f0-9aac-9c1785dc532c.png)
https://crashy.net/3748lo5inBwGzWbCDdFn

**Comment by Technici4n** [comment]
Not going to support 1.17.
