### ISSUE TITLE
Cables get broken

### ISSUE THREAD

**Issue by redstonerti** [AppliedEnergistics/Applied-Energistics-2#6112]
### Describe the bug

Some cables in my world get disconnected from each other and look like single blocks. This causes them not to work and is not a simple visual bug. It is real
![image](https://user-images.githubusercontent.com/48157961/159143137-917b89ea-83c1-40f9-9b69-74c437ce2467.png)
It has already happened twice with different types of cables in the exact same spots
![image](https://user-images.githubusercontent.com/48157961/159143146-92d4fd23-6e90-48dc-88da-cd86515c61a9.png)
It happened when I left and came back to the area

### How to reproduce the bug

Place a lot of cables in different chunks to maximize the probablity of this happening. Ideally just make a massive straight line of cables spanning like 40 chunks. That way, the cables are always not all in render distance and this will likely happen

### Expected behavior

I expected the cables to stay connected to each other

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://mclo.gs/QYVBoii (forced client crash) https://mclo.gs/YeFJS44 (server's latest.log)

**Comment by redstonerti** [comment]
It just happened again today in the exact same spots. The server crashed due to probably some unrelated error, and when I started it up again, the cables were broken
Here's the crash, just in case: https://mclo.gs/U8HWX3N

**Comment by redstonerti** [comment]
THE **DISRISPECT**
![image](https://user-images.githubusercontent.com/48157961/160255700-7ef0b039-936f-4d3f-9178-a1e920209cab.png)
Guess what

It happened again

**Comment by l-ricardo** [comment]
Looks like #5972

**Comment by mindforger** [comment]
he is using fabric 46, but do that thing with the debug card, this might give more insight

**Comment by redstonerti** [comment]
Should I update my fabric version? Should I send a different kind of log? I'm not sure I understood that, sorry

**Comment by mindforger** [comment]
In the linked issue above is an explanation for how to spawn and use the debug card zu generate more data zu find the reason

**Comment by Technici4n** [comment]
Please use the debug card to check if this is only a visual issue, or if this is also a server issue.

**Comment by Technici4n** [comment]
More information on that page: https://appliedenergistics.github.io/debug-card. Can you provide us with the debug card output?

**Comment by MidCoard** [comment]
Yes, I can confirm it. My server crashed because of #6139. When I restart my server, some fluix are broken. And also it is not a visual issue. My system did not work!

**Comment by MidCoard** [comment]
Oh, I crashed my server and when i restart and enter the server.
![1](https://user-images.githubusercontent.com/24197013/162231113-fb9a3359-40f6-4ba4-a9cf-c20f7332ea85.jpg)
I remove one of them and put it back, it works.
![2](https://user-images.githubusercontent.com/24197013/162231666-27ff4439-7be6-4fbd-8fc4-85fb686e15b5.jpg)

**Comment by Technici4n** [comment]
Does this only happen after a server crash? To be honest, we have no idea why this happens.

**Comment by MidCoard** [comment]
Yes. And It doesn't happen every time.

**Comment by Technici4n** [comment]
Hmmm that's very annoying. If it can't be reproduced reliably it won't be possible to fix -_-

**Comment by minenine** [comment]
I am having this issue on the ATM7 public server as well, 1.18.2, latest or second latest version of AE2 forge as of writing this comment. the cables that got disconnected where ones that crossed chunk boarders into unloaded chunks as the middle chunk of my base is chunkloaded and the rest is not. and one small sub system i have for some reason. also its not just the cables that disconnect from eachother, the patter providers a and i assume other devices dont propagate channels until replace either
![image](https://user-images.githubusercontent.com/1365542/164910036-5f9e0efe-57bb-475a-b122-94483a70a0c6.png)
![image](https://user-images.githubusercontent.com/1365542/164910097-8b63c4e0-f2ca-4067-9d09-3ed38a14b2bb.png)
![image](https://user-images.githubusercontent.com/1365542/164910122-fcf86db4-5c30-4f8e-81ee-8f1e7df51b5a.png)

**Comment by MidCoard** [comment]
> ![1](https://user-images.githubusercontent.com/24197013/162231113-fb9a3359-40f6-4ba4-a9cf-c20f7332ea85.jpg)

![0C1F69533BCEAAF0008C536DDABC3234](https://user-images.githubusercontent.com/24197013/164953355-9e300976-0489-4c16-b0a7-f87efd170756.jpg)
I can confirm it

**Comment by mindforger** [comment]
>Hmmm that's very annoying. If it can't be reproduced reliably it won't be possible to fix -_-

Can you provide a minimal Setup to reliably reproduce that issue?

**Comment by Technici4n** [comment]
Please use the debug card to check if this is only a visual issue, or if this is also a server issue. These screenshots don't provide any information.
