### ISSUE TITLE
Logistic features

### ISSUE THREAD

**Issue by DoremySwee** [AppliedEnergistics/Applied-Energistics-2#6115]
Star*: The idea is unlikely to fit into the original structure of the mod, but it's still acceptable as matter cannon and Entropy Manipulator.

a) Design an upgrade card, probably named as "hyper card" or "frequency card", mainly for both porting busses.
    i)    The minimum updating cd turns into:      cd=rounds up(    cd(original)*(5-number of cards)/5    )
    ii)   Keep the maximum updating cd unchanged.
    iii)  Can be inserted into Matter Cannon
    iv)  Probably work as an advanced acceleration card for Inscriber
    v)   Provide an option called Lazy option: Whether it immediately switch onto extreme working rate after a success.
    vi)  This card should be much more expensive than acceleration card.
    vii*)When inserted in Level Emitter, they examine the network at a fast rate, and never miss any change in the network. An option is that it does not work if any external storage (Storage bus at default interfaces) or there is a ME-controller.
    viii)7 is stared because that may not be the problem of the emitter but the storage bus?

b*) "Shulker card" for ME-IO, so that the shulker boxes can work as if they are a cell in ME-IO.
    i)    Cells store items out-of-order, making it sometimes a bad idea to use cells to transport items in complicated automation.
    ii)   Currently it's not a good idea to use shulker boxes to package items up, since it causes block updates and it's very slow, the dropped shulker boxes are dropped all over the ground.
    iii)  But everything can be solved if we can have shulker boxes working as a cell.
    iv)  To avoid abuse of shulker card, it may be expensive. Together with hyper card and energy card, a new material card may be created.

c) Modify the ME-IO Port
    i)    Add an option for the original one, saying that transfer [after] processing, which means that if it fails to process from the very beginning, it doesn't transfer the cell to the output slots.
    ii)   For example, in this mode and the network has nothing stored, an empty cell will not be exported until items are imported into the network and then transfered into the cell.
    iii)  Apparently, it's a way of 20Hz examine and provide an access to "wait until a specific thing to take place"

d) Modify the blocking mode
    i)    [ADD] an option for blocking mode, using the capability that Storage bus uses instead of the common one.
    ii)   Apparently it is useful because of we've got all kinds of complicated machines requiring only one share of ingredients.
    iii)  And there were designs focusing on high efficiency using Item-P2P with blocking mode in 1.12.2, but they no longer work after the change in 1.16.5. However this can fix the problem.

**Comment by Technici4n** [comment]
a) No, the tick rate modulation exists to prevent lag. We won't allow bypassing this.
b) No, there is no good gameplay reason for this, and there is many code reasons not to do it.
c) That's quite niche. If the point is to "wait until a specific thing to take place", there is already various ways of doing this, e.g. with a level emitter.
d) That's already a thing in 1.18.
