### ISSUE TITLE
Spatial Drive/Loader

### ISSUE THREAD

**Issue by MrFrexxy** [AppliedEnergistics/Applied-Energistics-2#6116]
### Describe the feature

Add a ME spatial drive that stores & keeps spatial cells chunk loaded. Could consume more power depending on size of contained cells.

### Reasons why it should be considered

The current method of needing to have a spatial anchor/me system in each cell to keep it loaded doesn't make sense. The suggested method is more in line with how the other cells function. Also would (hopefully) be less jank; currently, if power to an anchor in a cell goes out, it stays unloaded until cycled through the spatial io.

**Comment by shartte** [comment]
You'd need a quantum bridge into the cell to keep it powered, but I don't think we'll introduce a special per-cell chunk loader.
An addon might do this in the future though.
