### ISSUE TITLE
Fluids update for Fabric 1.16.5

### ISSUE THREAD

**Issue by MegaLP** [AppliedEnergistics/Applied-Energistics-2#6118]
### Describe the feature

So the fluid level emitter is not working in fabric 1.16.5, and you can't craft with fluid amounts. There is no way to detect an amount of fluids or autocraft in an interface.

### Reasons why it should be considered

I believe the newer mod packs would use Minecraft 1.16.5. Also, I would be very happy if it gets updated.

**Comment by Technici4n** [comment]
Sorry, we don't backport features.
