### ISSUE TITLE
[1.17.1 FABRIC] crash on connecting my storage subsystem

### ISSUE THREAD

**Issue by 0gp** [AppliedEnergistics/Applied-Energistics-2#6120]
### Describe the bug

my ME-System often loses the connection to my storage subsystem.
it often does not show items and fluids.
to solve this I just reconnect the a cable in the subsystem.
and since today it crashes the server.

### How to reproduce the bug

* setup an ME-System
* setup an Subsystem for Item and Fluid Storage
* connect them with Storage Bus and Interface so you should see the Items in the Main System
* force an Reboot of the main system
* maybe you will see sometimes it does not show up the items stored in the subsystem
* remove a cable in the subsystem to disconnect the Interfaces.
* place the cable again
* maybe the server crashes after a few seconds

### Expected behavior

not crashing the server!

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

https://gist.github.com/0gp/29920cb9a162a70f48d8dc20bd801f44

**Comment by Technici4n** [comment]
Fixed in 1.18. 1.17 is not really supported anymore, sorry.
