### ISSUE TITLE
[FABRIC 1.17.1] can not start crafting process (java.lang.IllegalStateException: Failed to extract from parent)

### ISSUE THREAD

**Issue by MSandro** [AppliedEnergistics/Applied-Energistics-2#6121]
### Describe the bug

i can not start large crafting tasks.

### How to reproduce the bug

start a complex crafting task, like a Advanced Machine Hull from Modern Industrialization.
it will output an error on the server.

### Expected behavior

it should start crafting

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

https://gist.github.com/MSandro/7ef944093145fca1f6ef65189a602247

**Comment by MSandro** [comment]
#6075 same issue.
maybe the fix could be backported to 1.17.1? would be very nice.
thanks for your great work AE2-Team. I love the mod. But in 1.17.1 there are so many annoing bugs, and as I know there is no possible migration to 1.18.x.

**Comment by Technici4n** [comment]
I'm very sorry, but I don't see us fixing all the 1.17 bugs when we could be focusing on 1.18.2 features.
