### ISSUE TITLE
Incorrect Jade version range

### ISSUE THREAD

**Issue by pupnewfster** [AppliedEnergistics/Applied-Energistics-2#6122]
### Describe the bug

Unable to launch with both AE2 (11.0.0-alpha.1) and Jade (5.0.1) in 1.18.2 due to the [allowed jade version range](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/forge/master/gradle.properties#L26) using the version range for jade of 1.18.1 instead of 1.18.2

### How to reproduce the bug

Try to launch with AE2 and Jade. (I did it in my dev environment for datagen, but should work outside as well)

### Expected behavior

For it to launch correctly

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

There is no crash log I only found it is AE2 by using my debugger

**Comment by shartte** [comment]
Aaaaaah yes, I have to fix this. 
Thanks for reporting!

**Comment by shartte** [comment]
Should be fixed in 11.0.0-alpha.2
