### ISSUE TITLE
[1.18.1 Server Crash] Available slots null 

### ISSUE THREAD

**Issue by itsdinkd** [AppliedEnergistics/Applied-Energistics-2#6123]
### Describe the bug

A player on Another Quality Modpack 2 tried to setup automated crafting of MI electric circuit, and after doing so, it crashed the official server. When this player joins back, the server crashes. 

### How to reproduce the bug

Working on retrieving this. Will update asap 

### Expected behavior

Not to crash and to automate electric circuit crafting 

### Additional details

The crash error from latest log: https://gist.github.com/itsdinkd/ff2d2d311f2f621f52edd1e3e9f75e0c

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

Crash Report: https://gist.github.com/itsdinkd/0373c2f16db153553e2eafe31e024127

**Comment by Technici4n** [comment]
Looks like there is a broken sided inventory next to a pattern provider. Can't be from AE2 or MI though.

**Comment by itsdinkd** [comment]
Thanks. The player didn't answer my question when asked what inventory he used 🤷 first time seeing this crash.

**Comment by itsdinkd** [comment]
Oh looks like he did. He said he couldn't reproduce and then stated he believes its the recipes used and that they had too many recipes in one machine.

**Comment by itsdinkd** [comment]
@Technici4n After looking through it and removing the ae2:controller that was causing the issue, it would indicate that this is a ae2 issue. I uploaded a incomplete crash log as well. apologies. 

here is the full crash log; https://pastebin.com/YqhceEqw

https://media.discordapp.net/attachments/957289638588993607/958359637386723398/2022-03-29_15.38.31.png?width=1629&height=916

**Comment by Technici4n** [comment]
Same problem as before: some BlockEntity that implements SidedInventory or some block that implements InventoryProvider is broken. And neither AE2 nor MI have such blocks. Therefore it must be a block from another mod, next to a pattern provider.

The problem is not the controller itself, but the network that's connected to it.

**Comment by itsdinkd** [comment]
Wouldn’t pattern provider be a InventoryProvider?   From: Technici4nSent: Friday, April 1, 2022 12:06 AMTo: AppliedEnergistics/Applied-Energistics-2Cc: itsdinkd; AuthorSubject: Re: [AppliedEnergistics/Applied-Energistics-2] [1.18.1 Server Crash] Available slots null (Issue #6123) Same problem as before: some BlockEntity that implements SidedInventory or some block that implements InventoryProvider is broken. And neither AE2 nor MI have such blocks. Therefore it must be a block from another mod, next to a pattern provider.The problem is not the controller itself, but the network that's connected to it.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Technici4n** [comment]
No, it's not code-wise.

I just checked the line numbers more carefully, and it appears that the error comes from some block implementing SidedInventory. Neither AE2 nor MI has such a block, so it much be either a vanilla thing or from another mod.

**Comment by itsdinkd** [comment]
Ah okay understood 👌

**Comment by itsdinkd** [comment]
sorry tech for still talking about this lol. I just searched his region file for the chunk, and all he has are AE2, Tech reborn cables and solar panels, and MI stuff. He has 4 Minecraft vanilla barrels next to the pattern providers, and two kibe tanks to store steam. Would this be due to the barrel?
