### ISSUE TITLE
Storage busses only connected through ME interface get items from disconected ME system

### ISSUE THREAD

**Issue by PixieCatSupreme** [AppliedEnergistics/Applied-Energistics-2#6129]
### Describe the bug

I have recreated the setup from this [reddit post](https://www.reddit.com/r/feedthebeast/comments/sqe08h/comment/hwleryc/?utm_source=share&utm_medium=web2x&context=3), but items added to the ME system seem to magically appear inside the inscribers. Connecting power to the inscribers makes the storage busses act like they are connected to the ME system.

### How to reproduce the bug

Connect the inscribers the same way as in the aforementioned reddit post. Basically connect inscribers with storage busses through an ME interface and ME pattern provider and connect cabled so they are powered.

### Expected behavior

Items should only appear in the inscribers if they are provided through the pattern provider and interface, not when added to the ME system.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://0x0.st/oqUx.txt

**Comment by Technici4n** [comment]
Did you orient the pattern provider correctly?

**Comment by PixieCatSupreme** [comment]
Arrows point towards the ME interface so I assume so
![image](https://user-images.githubusercontent.com/7165868/161309994-565662f9-a057-4ec0-af78-e386f37b13e8.png)

**Comment by Technici4n** [comment]
Unable to reproduce, I can't access the ME Drive from the terminal there:
![image](https://user-images.githubusercontent.com/13494793/161379033-8d98bb6d-ff31-4348-a507-ceec505e0c09.png)

Just to be sure, can you enable `unsupportedDeveloperTools` in the config, hold a debug card (Dev.DebugCard in the creative menu) while looking at the pattern provider with WTHIT installed, and post the picture? It should show something like this:
![image](https://user-images.githubusercontent.com/13494793/161379118-50fd2b0d-5e5c-4044-8505-de9638428620.png)

**Comment by PixieCatSupreme** [comment]
Strangely enough when I add a ME drive to that network it does show up on a terminal
![2022-04-02_12 46 27](https://user-images.githubusercontent.com/7165868/161379866-3590f006-e79d-4075-ad5e-cd3264a008cc.png)
![2022-04-02_12 47 03](https://user-images.githubusercontent.com/7165868/161379881-392eb85b-f535-4fdd-9108-a6bcb921a03c.png)

Here is the  Pattern Provider with the debug card
![2022-04-02_12 46 45](https://user-images.githubusercontent.com/7165868/161379908-05364536-5a70-465a-85e1-29fe93ac7c32.png)

And here is my cable setup. The white wires should only provide power through the inscribers if I understand correctly
![2022-04-02_12 49 00](https://user-images.githubusercontent.com/7165868/161379949-f36c6e43-c454-4968-a75b-b7ab6f740b0d.png)
![2022-04-02_12 49 15](https://user-images.githubusercontent.com/7165868/161379955-473b6928-bf5e-44a3-97f7-533314e3b18c.png)

I noticed that if I replace my white cables with creative energy cells it no longer happens, but the white cables should only provide power right?
![2022-04-02_12 56 11](https://user-images.githubusercontent.com/7165868/161380099-85c9c602-61d0-4bdb-912a-112ac3f4b98a.png)

**Comment by Technici4n** [comment]
From the debug card, you can see that there is no node exposed on the west side (the W is the only letter in green). That means that there is no network connection whatsoever going on there.

But this might be it:
> the white cables should only provide power right?

No, it's quartz fibers that only provide powers. White cables are like other kinds of cables, but dyed white!

**Comment by PixieCatSupreme** [comment]
Ah I understand now, my bad! I thought the glass cables would only provide power in this case but adding quartz fiber in between does fix this. Thank you for your help!

**Comment by Technici4n** [comment]
No problem!
