### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by Impoli** [AppliedEnergistics/Applied-Energistics-2#6135]
### Describe the bug

Causes the game to crash on load, before splash screen when combined with Citadel. No crash report generated.

Game Version: 1.18.2
Forge Version: 40.0.36
Citadel Version: citadel-1.11.2-1.18.2
AE2 Version: appliedenergistics2-11.0.0-alpha.
[latest.log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/8411559/latest.log)
3

### How to reproduce the bug

Add AE2 and Citadel to mods.

### Expected behavior

The game successfully loading

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

none generated

**Comment by freopt** [comment]
having same problem

**Comment by freopt** [comment]
https://gist.github.com/freopt/deb2ccddcfa3228e86531d6e1d74bec3

**Comment by Technici4n** [comment]
Fixed. Will be in the 11.0.0-alpha.4, to be released in a few minutes.
