### ISSUE TITLE
Server crash (molecular assembler)

### ISSUE THREAD

**Issue by PTOM76** [AppliedEnergistics/Applied-Energistics-2#6136]
### Describe the bug

OS: Windows 11
MCVersion: 1.18.2
FabricAPI: 0.48.0+1.18.2
jar: appliedenergistics2-11.0.0-alpha.2

When I try to auto craft with molecular assembler, it crashes and falls down.

### How to reproduce the bug

Connect Molecular Assembler for automatic crafting.

### Expected behavior

Minecraft will crash.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/2Z4vQgKE

**Comment by Technici4n** [comment]
Oops yes. I noticed this while fixing another bug. 11.0.0-alpha.3 should be out in a bit with the fix.
