### ISSUE TITLE
 System Cycle Restart When Level Emitter Meets Toggle Bus

### ISSUE THREAD

**Issue by MidCoard** [AppliedEnergistics/Applied-Energistics-2#6137]
### Describe the bug

The environment is the Fabric v10.1.0-beta.2 for minecraft 1.18.1

In one system, when a level emitter aimed at a toggle bus, the system will turn off and turn on again and again.
The video you can see.

And when i use the wrench to remove it, the serve just crashed. The crashed report is above

https://user-images.githubusercontent.com/24197013/161723185-8c740f89-8280-4ad7-8e0c-c3143d841099.mp4

.

### How to reproduce the bug

In one system, put a level emitter aimed at a toggle bus.

### Expected behavior

The system will not turn off and turn on again and again.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

**Comment by mindforger** [comment]
in a way that is expected to happen, since the toggle bus extends the network and forces an update, this could end in an endless loop, but what did you want to build there?

**Comment by MidCoard** [comment]
a sub system that can turn on or turn off by a condition that the number of the item is bigger or smaller than a number. But the endless loop is never expected in the earlier version such as minecraft 1.16.5.

**Comment by mindforger** [comment]
never "expected" or "happened" ? i can remember a few issues about wrongly or not updating emitters, maybe one of them broke your design by fixing another issue

this requires somebody that worked on the actual code to answer then

**Comment by MidCoard** [comment]
Anyway, the endless loop is never happened when i use this design before. Thank you for your answer and there are still two more bugs. One is about the texture and the other one made the server crashed.

**Comment by mindforger** [comment]
make new reports for them please bunched up reports are bad to handle

**Comment by Technici4n** [comment]
Might be related to #5613, I'm not sure.

**Comment by Technici4n** [comment]
So, it turns out that the level emitter goes off for a split second since any change in the connections causes a network reboot, which always takes at least 1 tick, and the network is unavailable while it reboots. I would say this is working as expected?

**Comment by mindforger** [comment]
I do too, it might be inconveniant but it is gone for a reason i would say ... Leaving them in their last state might hurt other constructs as well. The workaround i exlained should do the trick in this case

**Comment by MidCoard** [comment]
The level emitter should emit the redstone signal and the toggle bus should receive the signal and make itself pass. So, maybe in its function view, this may be the expected? However, I know what you mean. The two things both trigger the reboot. Redesigning them may cause a huge change of the logic. This may be a feature?

**Comment by Technici4n** [comment]
I think it's basically the same issue as #5613. I personally think that the terminals "flashing" is quite a bad thing, but I'm not sure how that should be solved yet.
