### ISSUE TITLE
Molecular assembler server problem atm7

### ISSUE THREAD

**Issue by laur122** [AppliedEnergistics/Applied-Energistics-2#6138]
### Describe the bug

when I put a thing to craft by auto crafter in molecular assembler server crashed.

### How to reproduce the bug

https://user-images.githubusercontent.com/102950441/161746774-b153bb89-6e07-408e-b264-ff5f2dc3582c.mp4

### Expected behavior

To autograft the pattern.

### Additional details

![image](https://user-images.githubusercontent.com/102950441/161748278-f13d5072-2855-4d79-8fdf-0167dd8c1a8a.png)
![image](https://user-images.githubusercontent.com/102950441/161748335-e367b0f8-7bd2-41d3-b057-429863180a58.png)

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/laur122/b889757c07e8f1fd9f5ced3cf0a34fb3

**Comment by Technici4n** [comment]
Oops yes. It's already fixed on fabric, I'll try to get a forge update out soon.

**Comment by laur122** [comment]
Nice news:)

**Comment by Technici4n** [comment]
Released 11.0.0-alpha.4 yesterday with the fix.
