### ISSUE TITLE
Server crashed when removing Level Emitter

### ISSUE THREAD

**Issue by MidCoard** [AppliedEnergistics/Applied-Energistics-2#6139]
### Describe the bug

When using wrench removing it, the server crashed!

### How to reproduce the bug

Use wrench to remove the Level Emitter

### Expected behavior

...

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://paste.fastmirror.net/?5b853a3f323a25bb#JCQ8RxiTUYduJUNCqC6yxtW2cTb9w7Pkgd3Xim4VDBcS

**Comment by Technici4n** [comment]
Is there a way to reproduce this reliably?

**Comment by MidCoard** [comment]
However, I tried my best to reproduce. I can only reproduce it in my server. Can't in single player mode.

The above is what I have done in my server.

first put things like this.
![1](https://user-images.githubusercontent.com/24197013/161821004-2f17e4b0-9af9-4507-ab2c-53f50e94d6fb.jpg)

second remove the fluix in the level emitter block
![2](https://user-images.githubusercontent.com/24197013/161821037-ee982123-1ea6-408d-b74e-6b907b84f793.jpg)

then put back the fluix in the level emitter block
![3](https://user-images.githubusercontent.com/24197013/161821049-c26b210f-d8ec-4475-9def-8b82b4b0ef6c.jpg)

last remove the level emitter and the server crashed.

This may be caused by my certain design of this network system.

This is a bird's-eye view of this network system
![4](https://user-images.githubusercontent.com/24197013/161821495-c3e246f8-bfb2-47be-aa67-b14010964e7f.png)


I hope this can give you some information to help fix this issue!

**Comment by Technici4n** [comment]
Hello, would you mind joining our discord server to download the following file in `#dev-talk`, enabling `gridLog`, putting the following jar on your server, reproducing the crash, and then providing us with the full log? It will spam quite a bit, but it should give us insight into what's happening here. Thanks!

![image](https://user-images.githubusercontent.com/13494793/161986754-597ddc97-21ac-4a1e-9c63-a9ad39ea796e.png)

**Comment by MidCoard** [comment]
Ok there is.
https://paste.fastmirror.net/?6b665891b82416e9#4zCa9e8dcEsKorbooEVYF3RGsExc9oT1vDm5aD4Ct47K
