### ISSUE TITLE
Wrong Texture between Fluix and Toggle Bus

### ISSUE THREAD

**Issue by MidCoard** [AppliedEnergistics/Applied-Energistics-2#6140]
### Describe the bug

the texture between the toggle bus and the fluix is wrong. The picture you can see.
![more](https://user-images.githubusercontent.com/24197013/161719728-c847c19b-1375-4ac7-99a3-df58bd05d20b.png)

### How to reproduce the bug

First put fluix, and then put the toggle bus.
Make sure the fluix and the toggle bus are not in one block.

### Expected behavior

The normal fluix texture.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

no

**Comment by Technici4n** [comment]
I think this was fixed by #6126.
