### ISSUE TITLE
Certus Quartz Dust -> Silicon inside MC Blast Furnace?

### ISSUE THREAD

**Issue by Eleiyas** [AppliedEnergistics/Applied-Energistics-2#6141]
### Describe the feature

MC version: 1.18.2

Not sure if this is an oversight or a deliberate decision, but I think it should be possible to put Certus Quartz Dust inside a Minecraft Blast Furnace to produce Silicon faster.

Furnace: Certus Quartz Dust + Coal => Silicon
Blast Furnace: Certus Quartz Dust + Coal => Nothing happens

If this is supposed to be a thing, then clearly my game/install is bugged for some reason :P

### Reasons why it should be considered

Seems a no-brainer?

**Comment by Technici4n** [comment]
Yes, will definitely add this for the next release.
