### ISSUE TITLE
ME Ore Dictionary Export Bus 

### ISSUE THREAD

**Issue by Eleiyas** [AppliedEnergistics/Applied-Energistics-2#6143]
### Describe the feature

As the ExtraCells mod is deprecated and has been abandoned, with the 2 main forks over on CurseForge also not having been updated in 2+ years, I'd like to request that the ME Ore Dictionary Export Bus be included in the main AE2 project.

If you're using a vast amount of mods with different ores, it is impossible to have an Export Bus with enough Capacity Cards to have all the ores export from the AE2 storage system into a Furnace/Blast Furnace, etc.

Yes, you could have multiple furnaces with multiple buses, with each a different set of ores in, but it's a bit of a faf. 

### Reasons why it should be considered

ExtraCells is dead and both forks seem to be too.

**Comment by Technici4n** [comment]
I would love this feature too, but the main issue here is that there is no direct concept of "ore dictionary" anymore in modern MC. Items can have tags, for example `c:iron_ingots` (on Fabric, or `forge:iron/ingot` on Forge) for all iron ingots, but they could also be functionality tags such as `minecraft:beacon_payment_items` (by default, this includes netherite_ingot, emerald, diamond, gold_ingot and iron_ingot).

But we don't know which tags should be used as equivalent items, and which tags should not. And we wouldn't want to export gold instead of iron, for example, even if they have a tag in common.

**Comment by EnderProyects** [comment]
It could be added like mekanism, that you could write the appropriate tag, so instead of nine slots to place the filtered items, nine slots to place tags, or a searcher that open all the tags that are with the mods added

**Comment by Eleiyas** [comment]
> the main issue here is that there is no direct concept of "ore dictionary" anymore in modern MC. 


this explains why the ExtraCells add-on is pretty dead then.

without completely busting this mod/coding, the only solutions I see are separating ores by furnace (which I put in my OP), with each having a different set of ores.

OR another couple of solutions:
- Allow export buses to have more capacity cards in them and therefore increase the amount of slots
- Have an "advanced export bus", which is an export bus crafted with multiple capacity cards, then have that be able to accept capacity cards too; this would give (maybe) a 9x9 slot gui, allowing up to a total of 81 items to be exported.

**Comment by EnderProyects** [comment]
It would be nicer a tag-card that can be inserted in storage, import and export busses, and inside of disks and that you could select the tag as I said above ( the crafting can be made with an advanced card, a name press a cutting knife and copper)

**Comment by Eleiyas** [comment]
> I think ExtraCells is mostly dead because its core functionality (fluid support) was integrated in AE2.
> 
> Another option is to show a popup window listing all the tags of the item and where you can select which ones you want to match against. But I don't see us implementing something like that in the short or mid term.

then what about my idea of just more cards inside busses or an "advanced" bus with just a load more slots?

**Comment by Technici4n** [comment]
While it would be a nice feature, I think we will leave it to addon developers to implement it, if they want to.
