### ISSUE TITLE
Tiny tnt goes back to item when explode under water 

### ISSUE THREAD

**Issue by EnderProyects** [AppliedEnergistics/Applied-Energistics-2#6147]
### Describe the bug

Well if a ignited tiny tnt touch water it will drop back to an item, and wont explode ( in lava this dont hapen)
Video in discord

### How to reproduce the bug

![image](https://user-images.githubusercontent.com/45178400/162577062-8f370b68-0a71-4885-ad19-11ca041b100e.png)
Place redstone next to it or filnt and steel it

### Expected behavior

The tiny tnt to explode

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/k0WYV3qJ

**Comment by Technici4n** [comment]
Turns out this is working as expected!
