### ISSUE TITLE
Enhancement: Create contraption compatibility

### ISSUE THREAD

**Issue by Kuiki86** [AppliedEnergistics/Applied-Energistics-2#6156]
### Describe the feature

A nice enhancement woulld be the compatibility to create contraptions. Right now cables a monitors disappear on a contraption and reappear after stopping the contraption. Inventory access via wireless terminals are not possible.

It would be nice to have a compat like ars nouveau (compat mod: ars creo) for its tile entities.

### Reasons why it should be considered

AE2 is designed for mass storage and crafting. with create its possible to create huge ming maschines or mobile bases that need the storage :-)

### Additional details

https://www.curseforge.com/minecraft/mc-mods/ars-creo
https://www.curseforge.com/minecraft/mc-mods/create

**Comment by Technici4n** [comment]
Cool idea indeed, but I think the usefulness is rather limited besides mobile bases... but then you might as well use spatial IO to teleport your base. ;)

Having that said, it should be possible for addons to add a few specific new ME network blocks that would interact nicely with contraptions, for example a wireless terminal relay.

However, making all AE2 blocks and parts work on contraptions is entirely impossible at the moment, and would require an insane amount of changes. As such, it is never going to be implemented.
