### ISSUE TITLE
skystone tank crashes game

### ISSUE THREAD

**Issue by CalinDanca** [AppliedEnergistics/Applied-Energistics-2#6157]
### Describe the bug

Im Using Applied energistics 2 Fabric version 11.0.0-alpha.3

When you place down a skystone tank and attempt to right click it with a water or laval bucket (all ive tried) Your game crashes because of a rendering error

### How to reproduce the bug

1. Get a skystone Tank.
2. Place it down.
3. right click it with a bucket of lava or water.
4. Crash

### Expected behavior

I expected the tank to fill up with the liquid

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/L6ccVwp6

**Comment by Mari023** [comment]
you are using sodium without indium, which is not supported.
installing indium will probably fix this
