### ISSUE TITLE
AE2 crashes my Curseforge modpack on my Mac

### ISSUE THREAD

**Issue by INEEDHELP12321** [AppliedEnergistics/Applied-Energistics-2#6159]
### Describe the bug

I was making my own modpack and decided to add AE2 (Applied Energetics 2). It was a modpack with approximately 260 mods with AE2 and some of its addons. I started up the Minecraft launcher and it loaded until phase 5/7 Post initialising and it paused at Applied Energetics. It froze for a while until it crashed. I tried several things like trying again 5 times, providing 14G of RAM and other things and it still didn't work. I then reinstalled AE2 and the other mods and it still didn't work. I also removed AE2 and it worked perfectly. Is there any way I can add AE2? I don't know how to add a crash report but I'll try.

### How to reproduce the bug

I got this problem when downloading 260 mods including AE2. It happened on my Mac version 12.1 .

### Expected behavior

I expected to load in and to be a bit laggy however I wanted it and predicted it to be at least at the main screen.

### Additional details

Amount of RAM Used:
14G

Mac Version:
12.1

Forge version:
14.23.5.2859

Amount of Mods:
265 (259 excluding AE2 and its add ons)

Modpack Version:
1.12.2

### Which minecraft version are you using?

1.12 - UNSUPPORTED

### On which mod loaders does it happen?

Forge

### Crash log

can't

**Comment by Technici4n** [comment]
Sorry, we don't support 1.12 anymore. If you can provide us with a log, we might however be able to point you in the right direction to fix your issue. (Might be easier on discord).
