### ISSUE TITLE
Addon API usage issues

### ISSUE THREAD

**Issue by ramidzkh** [AppliedEnergistics/Applied-Energistics-2#6165]
* `IAEAddonEntrypoint` improperly says the common initializer is still named `appliedenergistics2` while it's `ae2`
* By the time `ae2` triggers, it is too late to register parts with `PartModels.registerModels` as it's already frozen. A temporary workaround I found was to trigger my initializer at the end of `AppEngBase#<init>`

I'm pretty sure these issues are exclusive to Fabric since `IAEAddonEntrypoint`'s not used on Forge and Applied Mekanistics registers P2P tunnel models with no issue

**Comment by shartte** [comment]
Which version are you targeting? 1.18.2?
(I know this probably exists on multiple versions but recent registry changes make it a bit more touchy)

**Comment by ramidzkh** [comment]
1.18.2, well `11.0.0-alpha.3`
