### ISSUE TITLE
Huge Lag When Opening the Terminal

### ISSUE THREAD

**Issue by MidCoard** [AppliedEnergistics/Applied-Energistics-2#6174]
### Describe the bug

(I do not know whether this is a bug or not)
In my server, the AE network has stored more than 2000 types of item.
I have used the spark mod to profile the whole process.
And i have noticed one thing is that 
<img width="582" alt="tooltip" src="https://user-images.githubusercontent.com/24197013/163593255-9c46de9a-0fbd-47b9-9e1d-098ca61e1314.png">
the method Platform.getTooltip() has spent much of the time.
So is there an optimization to this method?

### How to reproduce the bug

Store huge amount of items and open the terminal

### Expected behavior

Not so big lag.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://spark.lucko.me/JtAMATJOBf

**Comment by XFactHD** [comment]
Kiwi is adding a list of item tags to the item tooltip. The lookup to get those tags seems to be extremely slow. I'd suggest disabling that feature in the Kiwi config.

**Comment by MidCoard** [comment]
ok. Thanks. just now i have noticed it too.

**Comment by MidCoard** [comment]
I have disabled the feature in the Kiwi config, but I still feel obvious lag during searching. Since I want to search by tooltip, the Platform#getTooltip method always creates a new ItemStack to get its tooltip. So how about making a cache for it?
