### ISSUE TITLE
Compatibility with mod industrial reborn

### ISSUE THREAD

**Issue by Foxsyl** [AppliedEnergistics/Applied-Energistics-2#6175]
### Describe the feature

I use minectaft 1.18.1 
Latest forge
Latest mod Industrial reborn
Latest mod applied energetic 2

I can't use energy making machine from Industrial reborn with Applied energetic 2

### Reasons why it should be considered

This mod have compatibility with many mods 
And before have compatibility with 
"industrial craft 2"

But in new Minecraft versions industrial craft 2 is replace with Industrial reborn

### Additional details

Industrial reborn use power type IE

**Comment by Technici4n** [comment]
No, we have no plans to add external dependencies at the moment. However, they are free to integrate with our API to implement this feature, with `IAEPowerStorage` in particular.

**Comment by Foxsyl** [comment]
do you have tutorial on how i can do this or can you explain it to me 
and by the way i am bad at modding
