### ISSUE TITLE
Support other vanilla tables for Patterns and the Molecular Assembler

### ISSUE THREAD

**Issue by 62832** [AppliedEnergistics/Applied-Energistics-2#6178]
### Describe the feature

There are some tables in vanilla Minecraft that offer their own recipes which, while limited, are currently impossible to automate due to said tables having no associated tile entity data. The molecular assembler could do with supporting these tables, be it through an alternate mode for patterns or otherwise, in order to allow for their automation.

When encoding a pattern, one might be able to specify whether that pattern is to be encoded for a Crafting Table, Smithing Table or Stonecutter recipe, with such a setting also provided for the MA to operate in a "crafting mode", "smithing mode" or "stonecutting mode". The stonecutter would arguably be the most versatile, though the smithing table would also likely see some frequent use in modpacks, such as with the [Eternal Stella](https://wiki.valhelsia.net/external-mods/forbidden-and-arcanus/wiki/items#eternal-stella) item from _Forbidden & Arcanus_. The Grindstone and Loom could also be considered, albeit optionally.

### Reasons why it should be considered

Currently, recipes for these tables can only be carried out manually by a player and no mod out there to date actually exists that provides an automated solution for them. As was already discussed on the Discord, AE2 could fill in that gap quite nicely to allow for on-command tool smithing and stonecutting to supplement both heavily-modded and vanilla+AE2 gameplay.

**Comment by Technici4n** [comment]
Done in #6673 and #6676.

**Comment by ratkinsonuk** [comment]
For those trying to work this out, you put the Pattern Provider next to the Molecular Assembler, and the pattern for the Smithing recipe into both blocks. Once hooked up to your AE2 system, it should just craft and return the result.
