### ISSUE TITLE
Items losing data when put into storage

### ISSUE THREAD

**Issue by Rarity1** [AppliedEnergistics/Applied-Energistics-2#6179]
### Describe the bug

When you put specific items into the Ae2 system they lose information. Eg: Putting a buzzsaw or drill from Immersive Engineering into the ME system causes it to lose all attachments. Im not sure what all is affected but I found out this issue from some very expensive mishaps. 

### How to reproduce the bug

Have Immersive engineering and Ae2 installed. 

Make a small ME system with a drive installed and a storage terminal. 

Put a drill or buzzsaw with a drillhead or sawblade installed into the system.

???

Profit. 

### Expected behavior

The items to come out of the system exactly how they were put in. 

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://bytebin.lucko.me/zzm3iMVQPv

**Comment by Technici4n** [comment]
Fixed in version 11.0.0-alpha.5 (to be released shortly).
