### ISSUE TITLE
World can't load after removing Applied Energistics 2

### ISSUE THREAD

**Issue by Mykosayyad** [AppliedEnergistics/Applied-Energistics-2#6180]
I have looked to see if anyone else has had this issue but I have not found anything.

So basically when I installed the mod everything was fine but when I removed it and tried to load into my world again I got this issue. After adding the mod back the world loaded just fine. I was hoping I can get a solution to my issue here.
Latest log:
[latest.log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/8500168/latest.log)
.
Error Image:
![image](https://user-images.githubusercontent.com/102385088/163681039-11325ec8-3cf2-4175-8c2c-3f3bdbe4c3d6.png)

**Comment by Technici4n** [comment]
Seems like removing dimension mods causes a problem? This is either a forge or vanilla issue... we can't do anything about it. You can try editing the level.dat in an NBT editor (make a backup first!) to remove the dimension maybe?

**Comment by Mykosayyad** [comment]
@Technici4n Applied Energistics adds dimensions? It was the only mod I removed when it stopped loading.

**Comment by Technici4n** [comment]
Yes, the spatial storage dimension.

**Comment by Mykosayyad** [comment]
Ok thank you I will try removing it.
