### ISSUE TITLE
Huge Lag When Modifying the Network Structure

### ISSUE THREAD

**Issue by MidCoard** [AppliedEnergistics/Applied-Energistics-2#6183]
**Describe the issue**
In my server, I have created a huge AE network.
However, when I modify the network structure such as placing a fluix cable or removing a fluix cable,  there will be huge delay in the server side.
I have used the spark mod to profile it.

spark log: https://spark.lucko.me/gjVP1Ta3OZ

Is there a way to make the lag smaller?

**Environment**
Fabric 1.18.1 
10.1.0-beta.2

**Comment by MidCoard** [comment]
Seems like it caused by the level emitters, and I have removed some of them, It truly works.
In my opinion, there should be some changes in the level emitter.
Also like #6137 , the reboot of the network is also not a good thing.

**Comment by shartte** [comment]
How big is "huge"?

**Comment by MidCoard** [comment]
From the log, you can see that the tick in level emitter part has spent 70% of the time.
![lag](https://user-images.githubusercontent.com/24197013/163782027-6a74d1e6-59d2-4a5c-b9f6-47eeb76529cd.png)

**Comment by Technici4n** [comment]
Thanks for the report, will be fixed in the next 1.18.2 release.

**Comment by shartte** [comment]
@MidCoard I did backport this to 1.18.1

Can you please try the version that'll appear on this page under "Artifiacts" once the build has passed?
<https://github.com/AppliedEnergistics/Applied-Energistics-2/actions/runs/2183218745>

(It'll be version 0.0.0, which might be an issue, let me know if it is)

**Comment by MidCoard** [comment]
Thanks, I'll test it later.

**Comment by MidCoard** [comment]
That works fine. There will be some dependency problem because of the version. I have modified the version manually. Thanks a lot.

**Comment by Technici4n** [comment]
Cool! Thank you for the report and the testing :)
