### ISSUE TITLE
Gradle/Maven artifacts missing?

### ISSUE THREAD

**Issue by bdew** [AppliedEnergistics/Applied-Energistics-2#619]
I'm looking for artifacts to use in my gradle script for ae2stuff to update it to rv2 beta.

The [old repo](http://files.minecraftforge.net/maven/appeng/appliedenergistics2/maven-metadata.xml) seems to be missing everything after rv2-alpha-1 and hasn't been updated in a while.

Is there some newer repository somewhere?

**Comment by AlgorithmX2** [comment]
Starting with rv2-beta-7 new builds should be available on the forge maven again.
