### ISSUE TITLE
Game can't start with ae2 10.1.0 beta2

### ISSUE THREAD

**Issue by 755437985** [AppliedEnergistics/Applied-Energistics-2#6193]
### Describe the bug

cant run minecraft with ae2 10.1.0 beta2

### How to reproduce the bug

install forge 40.1.0 and ae2 10.1.0 beta2
run the game and crash

### Expected behavior

game starts normally

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/JZwzhbtm

**Comment by Technici4n** [comment]
Oh wait, you need AE2 version 11.x.x to play on 1.18**.2**.

**Comment by 755437985** [comment]
oh it works
i forgot to check all files on curse and think that 1.18.1 one works on .2
totally missed that newer version
