### ISSUE TITLE
ME Terminal Auto-Focus overrides the JEI Search bar when enabled

### ISSUE THREAD

**Issue by saovenn** [AppliedEnergistics/Applied-Energistics-2#6200]
### Describe the bug

If you set the Search Mode to **_Remember Search On_** and **_Auto Focus On_** and then click on the JEI Search Bar in the terminal, the terminal still takes the Search Bar and not the one from JEI, even though you clicked on JEI.

Video:

https://user-images.githubusercontent.com/44532103/164738066-18eec68a-518b-42c4-956f-9663d8cb1528.mp4

### How to reproduce the bug

1. Enable Auto Focus in the terminal
2. Reopen the terminal so that Auto-Focus selects the terminal search bar
3. Click on the JEI Search Bar
4. Write something, for example to look at a recipe
5. finished
(Video is in the description)

### Expected behavior

To write something in the JEI Search Bar, even with Auto-Focus enabled, when you press on it

### Additional details

**Modpack:** ATM7 1.18.2
**Mod Version:** appliedenergistics2-11.0.0-alpha.4

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

none

**Comment by Technici4n** [comment]
I think this is an issue with JEI not properly taking the focus even though it should, not completely sure though.

**Comment by Technici4n** [comment]
Confirmed working with REI. You can download it from https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items and https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items-hacks, that should be a suitable replacement for JEI with the issue fixed. (REI implements the JEI API for compatibility with JEI-using mods).

**Comment by Tahakk** [comment]
https://github.com/mezz/JustEnoughItems/issues/2839

Back and forth, yay
