### ISSUE TITLE
Corrupt your world with a single step

### ISSUE THREAD

**Issue by EnderProyects** [AppliedEnergistics/Applied-Energistics-2#6205]
### Describe the bug

If you place two storage bus in a single chest and then fill it, the world will freeze... for ever
![image](https://user-images.githubusercontent.com/45178400/164976251-3892b83c-2a59-43d7-94ff-991b40373a2f.png)

### How to reproduce the bug

https://drive.google.com/file/d/1N7GjPeXWJ_TfrbF49fbLs7OUH945S9Iz/view?usp=sharing

In the video you can see how to reproduce it and what it makes, reloading the world or alt+f4 does not work, also editing the world with MCedit, makes nothing

### Expected behavior

idk, for example to not make your world unusable 

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

It will not create a crash report xd

**Comment by shartte** [comment]
Please provide the forced crash log. I can reproduce this with 1.18.1, but not with Fabric 0.46.6+1.18

**Comment by EnderProyects** [comment]
[crash-2022-04-24_15.54.53-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/8549826/crash-2022-04-24_15.54.53-client.txt)

**Comment by shartte** [comment]
> fabric: Fabric API 0.46.1+1.18

Please update to `0.46.6+1.18` and try if that fixes your issue. This seems to be a fabric-api issue, not AE2.

**Comment by EnderProyects** [comment]
![image](https://user-images.githubusercontent.com/45178400/164980366-c53eee3f-f32c-43f2-89b0-d23578fc74f5.png)
The issue is still there

**Comment by 62832** [comment]
> ![image](https://user-images.githubusercontent.com/45178400/164980366-c53eee3f-f32c-43f2-89b0-d23578fc74f5.png)
Why are you still on `0.46.1+1.18`?

**Comment by EnderProyects** [comment]
Ups, I load the wrong one xd
