### ISSUE TITLE
Storage bus show as online but freeze function

### ISSUE THREAD

**Issue by Mecr0mage** [AppliedEnergistics/Applied-Energistics-2#6211]
### Describe the bug

the storage busses for the ME system will no longer push items into ME interface they are connected to but still still show as online. the temporary fix for this is to break the cable connected to the storage bus and reconnected until it happens again.

### How to reproduce the bug

i could not come up with a way to recreate this issue in single player. but it happens whenever the server restarts and i will provide as much info about the ME system and my set up as i can in additional info

### Expected behavior

the storage bus should keep pushing items into the sub system even if some items that are filtered end up in some of the main system storage drive somehow.

### Additional details

in the server im playing on i have a Main ME system that has items being imported into it from farms. then a few sub ME systems used for automated processing that have items pushed into them by a filtered storage bus (with a high priority) set to export only on a ME interfaces, and the sub systems push the refined items back through another filtered storage buss on a ME interface. everything except security terminal, wireless access point and crafting computers are connected by ME P2P tunnels. chunk that contains my main ME controller is chunkloaded, and after the server resets once ever 4 hours is when the storage bus that push into the sub systems stops working.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/Xda11aWh

**Comment by minenine** [comment]
oh we this is what i got from the debug card when i used it on the storage bus while it was not working correctly if this helps
https://pastebin.com/QUQnB3PZ

**Comment by CanadianBaconBoi** [comment]
I'm having the exact same issue in singleplayer.

**Comment by Technici4n** [comment]
@CanadianBaconBoi can you reproduce this with AE2 only? More insight to reproduce this issue would be appreciated.

**Comment by CanadianBaconBoi** [comment]
@Technici4n I did some testing and it seems like it was an issue with the container from another mod that the storage bus was attached to. What container is @minenine using that causes this issue?

**Comment by minenine** [comment]
the storage bus was hooked up to a sub ME system that had no internal inventory but was hooked up to a functional drawers controller via another storage bus. which would then process the items being deposited and then return them to the main ME system.

**Comment by Technici4n** [comment]
Could be a functional storage issue then, no idea. Does it happen for storage busses connected to a chest?

**Comment by minenine** [comment]
it could be the drawers causing, but why would replacing the cable on the storage bus, that pushes into the subsystem connected to the drawers fix the issue?

**Comment by EShelley** [comment]
Yea I appear to be having the same issue playing All The Mods 7 currently.  Thought it was an issues with the p2p links but on the other side I too have functional storage drawers attached via a storage bus.
![p2pBus1](https://user-images.githubusercontent.com/24532145/168456215-a4559615-b9be-4a88-9e0b-d7175173c376.jpg)  
![p2pBus2](https://user-images.githubusercontent.com/24532145/168456214-fe261752-41cb-4881-9cc6-68935b8f368b.jpg)  


You can see that I have p2p links on my main controler and then the dense cable out the other end.  All I have connected on  that bus are some storage buses attached to Functional Storage drawer controllers.  Guess Ill move away from p2p links for now.  Hope this helps.

**Comment by Mecr0mage** [comment]
Possible way to reproduce this bug,
![image](https://user-images.githubusercontent.com/1365542/168473034-b37652bb-aaca-4743-8492-145fa82b5786.png)
in this setup im using FTB chunks to force load the parent system on the left side
[modlist.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/8694932/modlist.txt)

**Comment by Technici4n** [comment]
Works fine with the following modlist:
![image](https://user-images.githubusercontent.com/13494793/172042855-82328ae9-cf4b-48a3-909a-1d2b328fba3e.png)
![image](https://user-images.githubusercontent.com/13494793/172042848-aa2721b9-7834-4ebd-a136-d8aace2df3d7.png)

I'm going to assume that https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/6208 solved this issue (it was only released in AE2 11.0.0).

**Comment by Technici4n** [comment]
In the end, we were able to reproduce and fix this issue in #6337!
