### ISSUE TITLE
Mass molecular assembler

### ISSUE THREAD

**Issue by minenine** [AppliedEnergistics/Applied-Energistics-2#6212]
### Describe the feature

The idea is a new molecular assembler using like netherite or something that would allow a standard crafting to do more crafts all in one operation instead of one craft at a time, it could also depend on acceleration card inserted, (ie. 0 cards = 8 crafts, 1 =16, 2=32, 3=48, 4=64)

this could alternatively be made into a card itself that can be applied to regular molecular assemblers and even pattern providers so they can try to push their recipe items in partial or full stacks

### Reasons why it should be considered

this would help when people are making patterns for things that commonly get crafted a lot and in large amount and would cut down on some operations for things like server performance. exp would be something like crafting a 5x compressed cobble

**Comment by Technici4n** [comment]
No for AE2 itself since we usually don't add features that are already possible, and in this case it should already be possible to go very fast with 6 fully upgraded molecular assemblers per interface....

**Comment by yorii** [comment]
@minenine try going here instead with this suggestion: https://github.com/ProjectET/AE2Things
