### ISSUE TITLE
Allow devices to be upgraded via custom crafting recipe

### ISSUE THREAD

**Issue by 62832** [AppliedEnergistics/Applied-Energistics-2#6216]
### Describe the feature

_YADS - Yet Another Discord Suggestion_

As an alternative to requiring the user to access the UI of a block or cable part to insert upgrade cards one by one, it would be handy to allow them to be upgraded in-place via the crafting grid, placing down the device itself and any valid combination of supported upgrades.

### Reasons why it should be considered

Currently, in the case of more intricate auto-crafting setups with large clusters of ME Pattern Providers and Molecular Assemblers, upgrading that many MAs is usually a very lengthy and tedious process. While this feature may not be necessary to consider for some cable parts or other devices of which only one may be required on a network (e.g. ME IO Port), at a minimum supporting this for the MA with Acceleration Cards would make the process of setting up these arrays less cumbersome and also slightly more able to be automated.

**Comment by 62832** [comment]
Fair enough, that sounds like a better approach. If need be, this issue can be closed in favour of #1382.

**Comment by Technici4n** [comment]
Agreed, I think the memory card is a better solution. It probably requires API breaking changes, so definitely something to look at for the 1.19 update.
