### ISSUE TITLE
p2p for Modern industrialization

### ISSUE THREAD

**Issue by FederAndInk** [AppliedEnergistics/Applied-Energistics-2#6227]
### Describe the feature

well, just like the TR p2p channel but a new one so it doesn't mix the power as MI as its specific way of doing power :)

### Reasons why it should be considered

As there is a p2p for TR, why not adding a p2p for MI?

**Comment by yorii** [comment]
This was added in the latest release of MI, just a few hours ago.

**Comment by FederAndInk** [comment]
seriously x)
well, great then thanks for the info
