### ISSUE TITLE
game crashes before launching

### ISSUE THREAD

**Issue by Gitcrafter** [AppliedEnergistics/Applied-Energistics-2#6232]
### Describe the bug

The game crashes before launching and gives me an exit-code 1

Forge: 1.18.2 40.1.0
Applied Energistics2: 10.1.0-beta.2

### How to reproduce the bug

Install Minecraft Forge 1.18.2 40.1.0 and add only Applied Energistics2: 10.1.0-beta.2 to the modfolder(any other mods don´t change the result) and start the game with the standard Minecraft Launcher, then the launcher tries to start the game and after a few seconds it will give you first an internal error and the an Exit-Code 1

### Expected behavior

the game to launch normaly

### Additional details

sadly there is neither a crashlog nor a log created, so this are all informations I can give you

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

see Additional details for the missing link

**Comment by 62832** [comment]
10.1.0-beta.2 isn't supported for 1.18.2. You should be using one of the 11.0.0-alpha builds [here](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2/files/all).

**Comment by Gitcrafter** [comment]
Thanks for the fast reply, but I tried the ae2 11.0.0-alpha.6 and it still gives me the same result

**Comment by Technici4n** [comment]
Please have a look at the `logs` folder.

**Comment by Gitcrafter** [comment]
the problem is, that it doesen´t produces any logs or crashreports for that matter, even after repeated tries

**Comment by Technici4n** [comment]
Make sure you're running the game with Java 17.

**Comment by Gitcrafter** [comment]
how do I check that? im using the java, that comes with the game

**Comment by Gitcrafter** [comment]
the crash happens ONLY with AE2 WITHOUT AND WITH other mods

**Comment by Gitcrafter** [comment]
well, that´s just unfortunate

**Comment by Gitcrafter** [comment]
after some more testing I noticed, that it now happens without any mods too, and after some more testing and after deleting and reinstalling the minecraft forge jar it seems to be fixed now,
thank you for your time and patience, even if you couldn´t do anything
