### ISSUE TITLE
[BUG] NPT out of stack when using select button

### ISSUE THREAD

**Issue by zyxkad** [AppliedEnergistics/Applied-Energistics-2#6237]
### Describe the bug

I'm at the **creative** mode, and it's the **single player** mode
It crashed when I use the `select button` (mouse middle) to select something

### How to reproduce the bug

I don't know, this happen randomly, but it usually happened after I did something with AE2

### Expected behavior

Nothing to crash it's right

### Additional details

No

### Which minecraft version are you using?

1.12 - UNSUPPORTED

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/dq39reHU

**Comment by Technici4n** [comment]
We don't support 1.12 anymore, sorry. But it probably looks an issue with some mod having deeply recursive NBT.
