### ISSUE TITLE
Wrong Channel Display in Dense Smart Table with Crafting Unit

### ISSUE THREAD

**Issue by MidCoard** [AppliedEnergistics/Applied-Energistics-2#6240]
### Describe the bug

Using dense smart table to connect each crafting unit will make wrong channel display.
It seem like one crafting unit has spent 4 channels.
![1](https://user-images.githubusercontent.com/24197013/166402348-69ef32a2-6d98-4f23-9fb6-d70b6086c256.jpg)
The first cable.
![2](https://user-images.githubusercontent.com/24197013/166402358-1ff669d3-5741-4079-9613-770661318be2.jpg)

### How to reproduce the bug

Place a AE controller and use its one face to connect each crafting unit as the pic.

### Expected behavior

even though the crafting unit can only carry 8 channels, the wrong channel display is a bad thing.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

no need

**Comment by MidCoard** [comment]
<img width="854" alt="image" src="https://user-images.githubusercontent.com/24197013/166403045-c9c302f2-8c64-45ea-be0a-e4ea22e7cf95.png">
The debug info is right, but the display is wrong.

**Comment by Tahakk** [comment]
Looks fine to me. Crafting unit can transfer 8 channels only, so dim line means 1 channel, bright means 2 channels -> the cable changes to non-dense version on connection when connected to machine

**Comment by Technici4n** [comment]
Exactly, you're looking at non-dense connections here. That's why it shows 4/8.
