### ISSUE TITLE
Game crashes while searching in JEI WITH installed shader

### ISSUE THREAD

**Issue by MeycsHD** [AppliedEnergistics/Applied-Energistics-2#6243]
### Describe the bug

Hey guys! My game crashes when I search something in JEI. It does work without shader but as soon as I use a shader, it will crash. 

MC 1.18.2

Forge: 40.0.44

Optifine: OptiFine_1.18.2_HD_U_H7

Shader : BSL_v8.1.02.2.zip
(I tested a few shader but MC crashed every time)

### How to reproduce the bug

See Description 

### Expected behavior

Well, that it does not crash :D

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/1UB80ihM

**Comment by MeycsHD** [comment]
Oh totally forget to mention that I'm using appliedenergistics2-11.0.0-alpha.6

**Comment by Mari023** [comment]
> It does work without shader but as soon as I use a shader, it will crash.

**Comment by MeycsHD** [comment]
Does anyone know another Forgemod for shaders?

**Comment by MeycsHD** [comment]
> > It does work without shader but as soon as I use a shader, it will crash.
> 
> it sounds like doesn't happen without outptifine

Nah, without the Shader. I still use Optifine. So it does work fine with OF

**Comment by MeycsHD** [comment]
It seems working fine with Rubidium and Oculus + Shader :)
