### ISSUE TITLE
Import buses working too fast on not-stackable items

### ISSUE THREAD

**Issue by DoremySwee** [AppliedEnergistics/Applied-Energistics-2#6248]
### Describe the bug

(newest forge version)
Without acceleration card, it just transported 54 cells in one tick under my eyes, like this:
![C24AFA60847647E39D12011692514E43](https://user-images.githubusercontent.com/66953201/166896910-1fd5daa1-25d6-4b75-a319-726d4a10c6c8.gif)

**Comment by Technici4n** [comment]
Fixed in 11.0.0, to be released in a few minutes.
