### ISSUE TITLE
Autocraft Queue block/feature

### ISSUE THREAD

**Issue by gman4161** [AppliedEnergistics/Applied-Energistics-2#6249]
### Describe the feature

Add a block(or a feature) that allows the player to queue up a recipe for autocrafting. Perhaps this could be similar to a crafting storage/co-processing block where 1 Crafting stager(queuer, deployer, etc) = 1 craft queue slot that the player/crafting cards can add to. 

### Reasons why it should be considered

During the early game of AE2 setup when you're just getting into autocrafting, but don't really have the resources to go insane with it, one of the most annoying things is seeing "no processors available" and you have to back out of the autocraft menu, wait for the craft to finish, and re-input the number of items to craft. this would be solved with a queue where you could have 5 recipies "going" but none of them would craft until the previous one was finished.

### Additional details

I would see this as a relatively cheap block as it'd be for earlyish game and it still requires other processors to work. I could see this being it's own multiblock(similar to a processor) taking its own channel, or even as another block in a processor similar to the co-processing unit.

**Comment by Technici4n** [comment]
Interesting suggestion, but I think that this would make autocrafting too easy. Nothing stops you from creating many small 1k CPUs in the early game.
