### ISSUE TITLE
Compression storage upgrade

### ISSUE THREAD

**Issue by Mecr0mage** [AppliedEnergistics/Applied-Energistics-2#6250]
### Describe the feature

a upgrade card could be slotted into a storage drive that would allow it to automatically 3x3 or 2x2 compress items/blocks its partitioned with into its most compressed form and then uncompressed it when needed IE: nugget > ingot > block and vis versa

### Reasons why it should be considered

currently there is not a great solution to passively compress or uncompress, and as it is rn adding all the recipes for each item you want to compress can be very tedious as you often need to have quite a few patterns if you want it to keep up with most other crafting processes.

**Comment by Technici4n** [comment]
We will not be adding this feature in AE2 itself, but addons should be able to using our API.
