### ISSUE TITLE
KubeJS Error with the recipes

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [AppliedEnergistics/Applied-Energistics-2#6253]
### Describe the bug

![image](https://user-images.githubusercontent.com/77451351/167263373-d88fcad3-12bd-45ba-949d-6ca140f9214d.png)

### How to reproduce the bug

I started ATM6

### Expected behavior

No KubeJS errors

### Which minecraft version are you using?

1.16 - MOSTLY UNSUPPORTED

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/vQ8E3Q47

**Comment by 62832** [comment]
This looks like it should be reported to the maintainers of the ATM6 pack instead of here. The "Pulse Centrifuge" isn't even an AE2 device, but one from the LazierAE2 add-on.
