### ISSUE TITLE
P2P - 1.16.5

### ISSUE THREAD

**Issue by RedstoneGamer123** [AppliedEnergistics/Applied-Energistics-2#6254]
### Describe the bug

Im playing a custom modpack.
When playing on my server I am not able to use the memory card to link any type of p2p tunnels, but when I tried it on singleplayer it worked just fine.

### How to reproduce the bug

Try to use p2p tunnels on a server.

### Expected behavior

The linkage of the p2ps

### Which minecraft version are you using?

1.16 - MOSTLY UNSUPPORTED

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/tswQ4h19

**Comment by ramidzkh** [comment]
Try removing the item you have in your offhand and using the memory card

**Comment by RedstoneGamer123** [comment]
Now I just seem dumb... That worked, thank you!

**Comment by ramidzkh** [comment]
It shouldn't, but plenty of server mods (even Sponge) somehow break it
