### ISSUE TITLE
Freeze

### ISSUE THREAD

**Issue by HacoKavanah** [AppliedEnergistics/Applied-Energistics-2#6255]
### Describe the bug

Opening crafting terminal (or wireless crafting terminal from that mod) can cause the game to freeze, this can only be solved by closing and restarting game.

### How to reproduce the bug

Happens to me randomly, more likely when starting game. This is not the first time.

### Expected behavior

-

### Additional details

I'll be posting the log, but it doesn't seem to show anything.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://gist.github.com/HacoKavanah/81c5a09126f281cd2e85deebeda707f9

**Comment by Technici4n** [comment]
Please provide a thread dump of the frozen game, we can't just guess why your game freezes.

**Comment by HacoKavanah** [comment]
Thank you for answering! Where can I find this? I'm kinda new to sending issues, I know my logs and crash reports but what is a thread?

**Comment by Technici4n** [comment]
https://access.redhat.com/solutions/19170 ;)

**Comment by HacoKavanah** [comment]
So I do this when the game freezes again?:3

**Comment by Technici4n** [comment]
Yes!

**Comment by Nidaelie** [comment]
getting same issue, game freezes with open gl error in console when opening ae2 terminals... game continues running but frozen, i can stil hear the sounds and events

**Comment by Technici4n** [comment]
Please provide a thread dump, we can't just guess why it freezes.
