### ISSUE TITLE
Unknown incompatibility with other mod?

### ISSUE THREAD

**Issue by poseidoncarrot** [AppliedEnergistics/Applied-Energistics-2#6258]
### Describe the bug

I was trying to add some mods up to make a sort of magicy techy origin server and my Minecraft kept crashing everytime I tried to open with applied energistics 2. The mods worked perfectly fine without applied energistics 2 but kept crashing with it.

### How to reproduce the bug

The only way I have found to stop the crashing was to remove the mod and I have no clue how to replicate it since I'm assuming it is just an issue for me. 

### Expected behavior

Open Minecraft the normal way?

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/uTimYjUp

**Comment by Mari023** [comment]
> Minecraft 1.18.2
ae2 10.1.0-beta.3

you need an 11.x.x version of ae2 for 1.18.2
https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2/files/all?filter-game-version=2020709689%3A9008
