### ISSUE TITLE
Crank Missing 

### ISSUE THREAD

**Issue by AyyWhitby** [AppliedEnergistics/Applied-Energistics-2#6259]
### Describe the bug

The crank is missing so I can't power the charger to make charged certus quartz crystals. 
![2022-05-13_13 45 08](https://user-images.githubusercontent.com/105499140/168289219-b25067e7-6226-47af-a860-460ee49f6c2d.png)
 

### How to reproduce the bug

I don't know if it can be reproduced I added this mod to the medieval Minecraft [Fabric] mod pack on the CurseForge app 

### Expected behavior

every video I have watched on ae2 shows they have a crank in the mod but I don't 

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

N/A

**Comment by Technici4n** [comment]
There is no crank anymore, but there are other ways to produce energy with the vibration chamber or with other mods.

**Comment by AyyWhitby** [comment]
Ohh Okay, Thanks 👍
