### ISSUE TITLE
The Charger crashes the server

### ISSUE THREAD

**Issue by Solar-Dolphin** [AppliedEnergistics/Applied-Energistics-2#6261]
### Describe the bug

The charger block was placed down in the world and caused a major crash this was on the fabric 1.18.2 version of the mod.

### How to reproduce the bug

Just craft and place down a charger.

### Expected behavior

it not to crash

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/37bPf9av

**Comment by mindforger** [comment]
Probably cross mod issue ...https://github.com/WearBlackAllDay/DimensionalThreading/issues/60

**Comment by Technici4n** [comment]
We don't support multithreading mods.
