### ISSUE TITLE
Bi-Directional/Export Only Storage Bus on Interface with Crafting card won't send crafting requests to Autocrafting system

### ISSUE THREAD

**Issue by ScorpioRage** [AppliedEnergistics/Applied-Energistics-2#6262]
**Describe the issue**
Expected: Interface would send crafting requests to system to keep specified stock, regardless of being able to see its own inventory on the system.
Actual: The interface is not sending Autocrafting requests even though it has a crafting card, and it doesn't have the correct stock of items.
Linked video demonstrating the problem: 
https://drive.google.com/file/d/1G3-fxKXVD00JbJvomBAC75nSPmYTPyT2/view?usp=sharing

**Environment**
Forge Minecraft 1.12.2
Mods used:
![image](https://user-images.githubusercontent.com/6668983/168460766-376c389e-1001-49e3-a73e-fb5e57b82e50.png)

**Comment by Technici4n** [comment]
Yes that's intended behavior. If you want to use autocrafting you'll have to do it all on one network.

**Comment by ScorpioRage** [comment]
It is all on one network?

**Comment by Technici4n** [comment]
Yes, storage bus + interface allows one network to interact with another network's storage, but they are separate networks. (That's why we refer to one of them as a _subnetwork_).

**Comment by ScorpioRage** [comment]
Did you watch the video I included? It's all on a single network. Every tutorial I've watched for keeping a system stocked with items uses this exact setup

**Comment by Technici4n** [comment]
Oh, sorry about that. You are using an unofficial version, so please report the issue to them: https://github.com/PrototypeTrousers/Applied-Energistics-2/issues.

**Comment by ScorpioRage** [comment]
Ahh, thanks for the redirect!
