### ISSUE TITLE
Milk is fluid but cannot be stored in system with fluid cell

### ISSUE THREAD

**Issue by uhloin** [AppliedEnergistics/Applied-Energistics-2#6273]
### Describe the bug

subj

### How to reproduce the bug

ME Drive with fluid 16k cell. Store water or lava from bucket with right key, cannot do the same with milk. 

### Expected behavior

like bucket with water or lava

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

-

**Comment by Technici4n** [comment]
Milk is not a fluid in Vanilla, and it's only a fluid with Forge if a mod enables it. I assume that's not the case in your pack.
