### ISSUE TITLE
Weird 'Client' crash but still loads?????

### ISSUE THREAD

**Issue by FluffyBumblee** [AppliedEnergistics/Applied-Energistics-2#6274]
### Describe the bug

Happens just before the MC window pops up during boot.

### How to reproduce the bug

appliedenergistics2-11.0.0 & https://www.technicpack.net/modpack/the-limit-reborn-1181.1905659 (modpack)
start, there you go!

### Expected behavior

To boot or atleast crash normally?

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://gist.github.com/FluffyBumblee/08808d8f644dda28ba8fe1234d561337

**Comment by ProjectET** [comment]
This is an issue with polymorph as their mixin is broken with the latest version of ae2

**Comment by FluffyBumblee** [comment]
oh ok, thanks!

**Comment by FluffyBumblee** [comment]
Updated Polymorph and it fixed
