### ISSUE TITLE
Weird loading loop on client 11.0.0 -release

### ISSUE THREAD

**Issue by netcore10** [AppliedEnergistics/Applied-Energistics-2#6285]
### Describe the bug

Weird loading loop.
Doesn't happen on alpha, no idea why.

Does have resource pack loading error in log.

### How to reproduce the bug

not sure, Could be a mod incompatability.

### Expected behavior

To load.

### Additional details

used in a modpack

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://gist.github.com/netcore10/4945c39756c73b1d334c1277174b1ce2

**Comment by Technici4n** [comment]
Definitely an issue with your pack since AE2 works fine in other modpacks.

**Comment by netcore10** [comment]
any clue as to what it could be? The log only mentions ae2.

**Comment by Technici4n** [comment]
Could be any mod with broken resources

**Comment by netcore10** [comment]
Hmm... gonna be a tough issue to fix then, might be forced to use an older version for now.
