### ISSUE TITLE
1.18.2 Forge mixin version

### ISSUE THREAD

**Issue by iglee42** [AppliedEnergistics/Applied-Energistics-2#6287]
### Describe the bug

I want to use applied energistics in my mod and i have a problem when i launch my test client.
The mixin's version is in Java 11 but the 1.18.2 use Java 17 so my game doesn't want to launch.

### How to reproduce the bug

Launch a dev environment with applied in run/mods

### Expected behavior

I just want that you change the mixin's version to Java 17

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/2GwkMsA7

**Comment by Technici4n** [comment]
This has to be an issue with your setup since it works fine for others. Maybe try to update Forge.
