### ISSUE TITLE
Certus Quartz seeds despawning

### ISSUE THREAD

**Issue by Blacksmith-Sarec** [AppliedEnergistics/Applied-Energistics-2#6292]
### Describe the bug

When I try to grow certus quartz seeds in water with no accelerators, they despawn about halfway through the growing process. I set a timer for 20 minutes and started it right as the seed hit the water. the seed despawned 12 minutes into the process.

### How to reproduce the bug

1. throw certus quartz seed into water with no growth accelerators.
2. Wait
3. The seed should despawn around halfway through the process.

A filtered hopper set to Certus Quartz crystals was underneath to catch it as soon as it fully grew, no items were in the hopper

### Expected behavior

I expected the growing process to finish and the finished crystal to be sucked into the filtered hopper below the seed

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/5mkL2BTj

**Comment by mindforger** [comment]
try disabling the whyyoumakelag mod, it seems to be the first best offender and it comes with a big warning to properly configure it before use

**Comment by Technici4n** [comment]
Features include "Customise item despawn time", so going to assume it's an issue on their side. Good catch, @mindforger! :smile:
