### ISSUE TITLE
[BUG]Copy item Bug!!!!! & the ME interface priority cannot work

### ISSUE THREAD

**Issue by miangou** [AppliedEnergistics/Applied-Energistics-2#6294]
### Describe the bug

You can swipe items through the input and output ports
And the me port priority is invalid
——————————————
你可以通过输入输出端口刷取物品
并且me端口优先级失效

### How to reproduce the bug

Add My Telegram and I'll send a video for you
[@](https://t.me/NatsumiXD)

### Expected behavior

priority works fine & Can't get extra items

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

NO

**Comment by miangou** [comment]
http://112.49.61.47:80/qqdownload?ver=537065739&rkey=3081db0201010481d33081d00201010201000204af7b751204819837303061306133323339333433343331333033333336333933383132323036343333333033343632333633323633333536323330333836363337333733393338333833343334333433303631333933363333333136313338363533383331313864386336633731333230653930373238613864666138393430363330626262626538303333386630656163346538303634306432383630330204628a2fa804210000000866696c65747970650000000431303033000000047175696300000001300400&filetype=1003&videotype=1&subvideotype=0&term=unknow

**Comment by miangou** [comment]
ok。wait a minute

**Comment by miangou** [comment]
https://drive.google.com/file/d/1Ky3i0-xAqA--tAFf6zVnjQUPqIi0R6a1/view?usp=sharing

**Comment by miangou** [comment]
> 我不会在 Telegram 上安装和添加你来获取错误报告的视频，抱歉。
> 
> 您也没有提供必要的强制崩溃报告。请这样做。
> 
> 但不管这些问题如何，从问题描述来看，我不明白如何重现这个问题。

https://drive.google.com/file/d/1Ky3i0-xAqA--tAFf6zVnjQUPqIi0R6a1/view?usp=sharing

**Comment by miangou** [comment]
> 我不会在 Telegram 上安装和添加你来获取错误报告的视频，抱歉。
> 
> 您也没有提供必要的强制崩溃报告。请这样做。
> 
> 但不管这些问题如何，从问题描述来看，我不明白如何重现这个问题。

Only video link:
https://drive.google.com/file/d/1Ky3i0-xAqA--tAFf6zVnjQUPqIi0R6a1/view?usp=sharing

**Comment by Mari023** [comment]
I can reproduce it
[crashlog](https://gist.github.com/Mari023/3da0d4cd0c1d4ec44275a7769bee137d)

**Comment by Mari023** [comment]
accorfding to GDLauncher this is latest fapi

**Comment by miangou** [comment]
https://drive.google.com/file/d/1Lg_5SoqCeQqB1CAkCQRCQswYNU7StJty/view?usp=sharing

> Please do F3+C (hold) and post the crash log.
> 
> This might be an old fabric-api version causing the double chest to dupe stuff.

**Comment by miangou** [comment]
> Please do F3+C (hold) and post the crash log.
> 
> This might be an old fabric-api version causing the double chest to dupe stuff.

I update from [11.0.0-alpha.5](https://github.com/AppliedEnergistics/Applied-Energistics-2/releases/tag/fabric%2Fv11.0.0-alpha.5) to [11.0.0](https://github.com/AppliedEnergistics/Applied-Energistics-2/releases/tag/fabric%2Fv11.0.0)

**Comment by Mari023** [comment]
![2022-05-22_15 26 06](https://user-images.githubusercontent.com/38946771/169697442-69020c9a-441e-4f54-a389-f89e4bf90b0c.png)
The export buses  both have 4 acceleration cards in them

**Comment by miangou** [comment]
Priority failures are common
Have a booster card when copying an item
I use translation software, so maybe the grammar is not very good
