### ISSUE TITLE
Lack of slots for templates in the ME Interface

### ISSUE THREAD

**Issue by Elpatov** [AppliedEnergistics/Applied-Energistics-2#6295]
### Describe the bug

Inventory cells for templates are missing in the ME Interface.

https://i.imgur.com/L09SRsE.png

### How to reproduce the bug

Put the ME Interface and visually verify this.

### Expected behavior

Obviously, template slots must be present for the ME Interface to do the job.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

No

**Comment by Technici4n** [comment]
Duplicate of #5479
