### ISSUE TITLE
Caught exception from Applied Energistics 2

### ISSUE THREAD

**Issue by Buchernov** [AppliedEnergistics/Applied-Energistics-2#6300]
### Describe the bug

I tried everything. help please
Says the error is on #988. Error is in the server

### How to reproduce the bug

Dont know

### Expected behavior

Launch server and always this error

### Which minecraft version are you using?

1.12 - UNSUPPORTED

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/Z9m4N5Bf

**Comment by Technici4n** [comment]
Seems like an issue with another mod: `dlovin/inventoryhud/gui/InventoryGui`. Additionally, 1.12 is not supported anymore.
