### ISSUE TITLE
Internal elements of fluix cables still render when it has a facade on all six sides

### ISSUE THREAD

**Issue by saltyseadoggo** [AppliedEnergistics/Applied-Energistics-2#6304]
### Describe the bug

It appears that, when you place a fluix cable and surround it on all six sides with facades, the internal model elements- the cables, backsides of the facades and the metal bits attaching them to the cable- all still render. I think it would be a good optimization for the client to have these faces be invisible in this case, so the whole block renders like a normal block.

### How to reproduce the bug

- Place fluix cable
- Attach facade to all six sides
- Enter spectator mode
- Clip into the block
- Observe inner elements rendering

### Expected behavior

The cable would not render its internal faces when they are all obscured.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

N/A, not a crash

**Comment by Technici4n** [comment]
I doubt such an optimization would make a difference in practice, and I generally dislike premature optimizations, i.e. optimizations that are not motivated by a performance report. Cable rendering is already quite efficient.
