### ISSUE TITLE
Crash upon loading

### ISSUE THREAD

**Issue by cybercat5555** [AppliedEnergistics/Applied-Energistics-2#6305]
### Describe the bug

When the game is launched with just AE2 and fapi, it crashes upon loading, before a proper crash log can be created. Mentions a mixin issue.

### How to reproduce the bug

Install the following:
- appliedenergistics2-10.1.0-beta.3
- fabric-api-0.51.1+1.18.2
- Fabric Loader 0.13.3 or 0.14.6 (tested with both) for 1.18.2
- Launch the game

### Expected behavior

Game would not crash upon loading, or at least get to the point where it can make a proper crash log

### Additional details

Unsure if this matters, but I am using GDLauncher

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://gist.github.com/cybercat5555/89a25f2a2f10b4112a9702962733c1c6

**Comment by 62832** [comment]
10.1.0 is for MC 1.18.1, not 1.18.2. Use 11.0.0 onwards.
