### ISSUE TITLE
Autocrafting duplicates Mystical Agriculture infusion crystals

### ISSUE THREAD

**Issue by jsmith42069** [AppliedEnergistics/Applied-Energistics-2#6306]
### Describe the bug

Autocrafting high tier essence from the Mystical Agriculture/ Mystical Agradditions mod with master infusion crystals gives me additional free master infusion crystals for every craft.
![tempsnip](https://user-images.githubusercontent.com/106430963/170821878-007c156a-ec38-443e-9293-ff18d042567b.png)
12k of these would be 3B+ inferium essence.
![tempsnip1](https://user-images.githubusercontent.com/106430963/170821932-b5709127-c48b-4ae4-accb-02106720bbb3.png)
When crafting essence, it always says it's crafting the infusion crystal even though there is no recipe available for it.

### How to reproduce the bug

Tried to reproduce it in a creative world but was unable to. Can't find what is causing this bug.

### Expected behavior

The number of infusion crystals is the same before and after crafting with them.

### Additional details

Modpack is TNP Limitless 5 v2.7.0

Here are some pictures of my setup:
![2022-05-28_03 47 07](https://user-images.githubusercontent.com/106430963/170822158-d4d80d3f-3514-46cd-8125-0b5cb56f6b1e.png)
![2022-05-28_03 47 18](https://user-images.githubusercontent.com/106430963/170822161-fae96a32-b9f9-4afd-b490-22731543f42a.png)
![2022-05-28_03 47 43](https://user-images.githubusercontent.com/106430963/170822164-c3052aec-5687-49ce-9200-764528918687.png)

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/sXT5UHze

**Comment by Technici4n** [comment]
Unfortunately I can't reproduce your issue, and you can't reproduce it either, so this is not going to be fixable. If someone can find a reliable way to reproduce this, please open a new issue.
