### ISSUE TITLE
Point meteorite compass to something other than sky stone

### ISSUE THREAD

**Issue by 62832** [AppliedEnergistics/Applied-Energistics-2#6315]
### Describe the feature

With the changes made to meteorites, including the addition of the fluix block core around the chest, it would be nice to amend the meteorite compass to make it point towards either those fluix blocks or the chest itself instead of the sky stone making up the meteorite.

### Reasons why it should be considered

Currently, having the meteorite compass point to naturally-generating sky stone from meteorites means it becomes tedious later on to ensure the compass stops pointing at an already-discovered meteorite.

The requirement is currently to mine out all the sky stone on the site of the meteorite to force the compass to point elsewhere, which is an extremely tedious process without an already fast tool or some extra utility mod for vein-mining. This is even worse when the meteorite is on the surface as opposed to underground due to the extra sky stone which, while loosely scattered about the site, still technically counts as part of the meteorite.

**Comment by 62832** [comment]
From what I glanced of the code while making the change in the linked PR, that shouldn't be the case. At least my impression was that the compass simply looks for the nearest chunk containing specifically a block of sky stone.

In fact, doing some testing I found that there is nothing yet present to distinguish between sky stone blocks placed manually by a player and sky stone blocks arising from worldgen in meteorites, and this behaviour would persist for now with the replacement with sky stone chests.

Are you certain that you removed all the sky stone in that chunk prior to also removing the oil? I could of course be very wrong and there could be some further miscalculation brought on by the extra worldgen as you mention.

**Comment by dBHI-zz** [comment]
Yes, I am positive that there were no skystones missed. I especially installed the Scannable Mod to search for the remaining Sky Stones.

**Comment by Technici4n** [comment]
Idea from #5875: we could also point to the closest fluix block, to be determined.

**Comment by Technici4n** [comment]
It's now pointing to the closest Mysterious Cube, as of 12.5.0-beta.
