### ISSUE TITLE
[1.18.2] Crash to desktop when Item is searched for in terminal. 

### ISSUE THREAD

**Issue by DoughnutDev** [AppliedEnergistics/Applied-Energistics-2#6316]
### Describe the bug

If there is a core sample from Immersive Engineering in the AE2 system you will crash.

### How to reproduce the bug

Place an Core Sample from IE and highlight/search for the core sample and it will crash the game.

### Expected behavior

Crash to desktop

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/DoughnutDev/2640228d257c734de9ef5b30d48469c9

**Comment by Technici4n** [comment]
The crash is an IE issue: https://github.com/BluSunrize/ImmersiveEngineering/issues/5318.
