### ISSUE TITLE
[1.18.2] Meteorites compass slowly spinning

### ISSUE THREAD

**Issue by DuckToFo** [AppliedEnergistics/Applied-Energistics-2#6321]
### Describe the bug

The meteorite compass keeps slowly spinning and not pointing to any specific locations
It may be because no meteorites spawned in my world

### How to reproduce the bug

I play AE2 with BYG (Oh, The Biomes You'll Go) which is the only mod that interferes in world generation

### Expected behavior

BYG's world gen may prevents the meteorites from spawning

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

No crashes

**Comment by Technici4n** [comment]
1.18.2 fixed these worldgen issues, there is nothing that we can do in 1.18.
