### ISSUE TITLE
[1.18.2 - Forge] Annihilation Plane Cannot be Enchanted using Anvil

### ISSUE THREAD

**Issue by StanleyMcClister** [AppliedEnergistics/Applied-Energistics-2#6338]
### Describe the bug

Using the new Annihilation Plane, it can not be enchanted via an Anvil. 

### How to reproduce the bug

Place an Annihilation Plane in an Anvil with a enchanted book. 

### Expected behavior

Annihilation plane should be enchantable by anvil. 

### Additional details

![2022-06-05_10 57 07](https://user-images.githubusercontent.com/67228240/172057050-19c30783-46f6-4a6b-b66b-f729ad481628.png)
![2022-06-05_10 57 45](https://user-images.githubusercontent.com/67228240/172057052-fd9b8efc-10f7-4512-9379-1ce251ce8ee1.png)

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

None

**Comment by StanleyMcClister** [comment]
Checked with both Vanilla and Modded Enchantments.  Apotheosis is installed.

**Comment by Mitchell5200** [comment]
Using an enchanting table works, as does a Pneaumatic craft pressure chamber. Just incase you wanted to know other things that do work

**Comment by Technici4n** [comment]
Fixed by #6339.
