### ISSUE TITLE
ME glass-cable is invisible 

### ISSUE THREAD

**Issue by QuentumXX** [AppliedEnergistics/Applied-Energistics-2#6348]
### Describe the bug

When im building with the ME glass cables, they are invisible, the crafting Terminal on the side of the block is also invisible.

### How to reproduce the bug

Playing sky bees 2 in the newest version

### Expected behavior

I expected, that the cables where visible

### Which minecraft version are you using?

1.16 - MOSTLY UNSUPPORTED

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/QuentumXX/c2208c2f7e8e6b6f4ba32480277d5d2a#file-crash-2022-06-09_19-29-18-client-txt

**Comment by Technici4n** [comment]
Probably an issue with your modpack. You might want to check that you don't have broken rendering optimization mods.
