### ISSUE TITLE
Mod is crashing game on load when wireless terminal placed in ring slot

### ISSUE THREAD

**Issue by sadovsf** [AppliedEnergistics/Applied-Energistics-2#6352]
### Describe the bug

Today i played Direwolf20 1.18 mod pack from FeedTheBeast and finally get into wireless terminal. I charged it, tested it (connected etc...) and wanted to place it in Curio slot. First i did place it in belt slot, then i for some reason wanted to move it to bottom most ring slot. Gave crashed right after that and i cannot load this save ever since. Crashing on same spot

### How to reproduce the bug

1) Create wireless terminal
2) Charge it
3) Put it into bottom most curio ring slot

### Expected behavior

Not crashing :)

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/5J8E8Yc8

**Comment by sadovsf** [comment]
Note, i was not able to get world working even after deleting userdata. Ended up restoring save from backup.

**Comment by Technici4n** [comment]
The issue is from the addon mod AE2wtlib by @Mari023.
