### ISSUE TITLE
Spatial Pylon Blocksates

### ISSUE THREAD

**Issue by hunte3er** [AppliedEnergistics/Applied-Energistics-2#6357]
### Describe the feature

Please give the option to have textures for left/right/top/bottom_end and horizontal/vertical_spanned. 

### Reasons why it should be considered

This would open up the opportunity for teyture pack creators to have shadows in their spatial pylon textures that look correct (see BDCraft).

### Additional details

![red_spanned_vertical](https://user-images.githubusercontent.com/72540426/173095695-dac3b77c-1087-4dee-bf67-1727988f629b.png)
![base](https://user-images.githubusercontent.com/72540426/173095697-9f6b0d4f-dcf7-42f5-954d-a87f5b81a3a5.png)
![base_end_bottom](https://user-images.githubusercontent.com/72540426/173095699-75cadcbc-68aa-4b42-8f0c-fe7ba2901a79.png)
![base_end_left](https://user-images.githubusercontent.com/72540426/173095700-20aa9885-a5c9-4192-b0c0-bc1b65282011.png)
![base_end_right](https://user-images.githubusercontent.com/72540426/173095703-29aa0309-bdc1-4ce5-9e96-4c1b7f32856e.png)
![base_end_top](https://user-images.githubusercontent.com/72540426/173095704-4cbefd32-7a0c-4779-9bb4-b945b624bdf1.png)
![base_spanned_horizontal](https://user-images.githubusercontent.com/72540426/173095706-628dd483-c2f8-4336-885d-7f4c504c3213.png)
![base_spanned_vertical](https://user-images.githubusercontent.com/72540426/173095707-d6231940-4a35-4ec1-9f45-71732913aa4b.png)
![dim](https://user-images.githubusercontent.com/72540426/173095708-636f4cb7-7b07-4722-8fdc-3f5779cd64f2.png)
![dim_end_bottom](https://user-images.githubusercontent.com/72540426/173095709-befd5b0c-9aa8-4442-94d6-54770028b85f.png)
![dim_end_left](https://user-images.githubusercontent.com/72540426/173095711-0fe6db53-69d0-44d6-96fa-60904dd76200.png)
![dim_end_right](https://user-images.githubusercontent.com/72540426/173095712-6a7506d6-30e9-4bb4-9bd7-ff75cc2aa491.png)
![dim_end_top](https://user-images.githubusercontent.com/72540426/173095714-3f767e08-e671-4e47-95f6-e09bbdb791c7.png)
![dim_spanned_horizontal](https://user-images.githubusercontent.com/72540426/173095715-a08937c5-8d69-4b68-b29b-e5bee55c8cfe.png)
![dim_spanned_vertical](https://user-images.githubusercontent.com/72540426/173095720-bf08c022-78aa-4deb-8d48-181ebda0babc.png)
![red](https://user-images.githubusercontent.com/72540426/173095722-06f8bf14-d003-4d8a-8de3-7790a935953a.png)
![red_end_bottom](https://user-images.githubusercontent.com/72540426/173095724-db1370eb-3762-4c5e-8dbc-fbfd359c8cc2.png)
![red_end_left](https://user-images.githubusercontent.com/72540426/173095727-74382332-cd46-4735-9a76-cee68d035dab.png)
![red_end_right](https://user-images.githubusercontent.com/72540426/173095731-f54d5e57-adc1-4c86-8ab1-dd91021ea1c9.png)
![red_end_top](https://user-images.githubusercontent.com/72540426/173095734-e302214d-c49a-4d13-9ad0-1dd477b7c3e2.png)
![red_spanned_horizontal](https://user-images.githubusercontent.com/72540426/173095735-68d18d8d-f18a-4d20-828a-f2d4b97e0f15.png)

**Comment by Technici4n** [comment]
While that would be cool, this is an unfortunate limitation of our model system, and I don't think that adjusting it to support this use case is possible for now.
