### ISSUE TITLE
AE2 broken values or id's idk// ic2 // need help

### ISSUE THREAD

**Issue by newbiiiie** [AppliedEnergistics/Applied-Energistics-2#6362]
### Describe the bug

all already know this bug with broken values and stuck re-battery items in ae2 autocraft system (not only ic2). 

### How to reproduce the bug

try to make pattern with any battery item and try to craft it with AE2

![001](https://user-images.githubusercontent.com/107325299/173230157-2e0e6753-6ede-4099-aa31-fe570fe9265c.png)
![002](https://user-images.githubusercontent.com/107325299/173230158-236669fc-67c9-4eda-89b0-d4b1f7230d80.png)
![003](https://user-images.githubusercontent.com/107325299/173230159-8e2fc390-0138-464b-afda-2acb188b90f9.png)
![004](https://user-images.githubusercontent.com/107325299/173230161-2ad1e053-13a5-42e2-af66-ea14beaab638.png)
![005](https://user-images.githubusercontent.com/107325299/173230162-fe41481b-e489-4627-ac8c-204755675217.png)
![006](https://user-images.githubusercontent.com/107325299/173230163-3ed06f02-0fc1-4255-a352-fafad7f718eb.png)
![007](https://user-images.githubusercontent.com/107325299/173230164-5eba1da3-ebec-4b60-a63d-40d37b138085.png)

### Expected behavior

i expected what it would work normally without stuck and no broken id's?

### Additional details

i don't need a solution with two patterns of the same item, i just want to AE2 would work as it should without bugs.  i hope anybody have cfg file with fixes or jar file with replace. help.. please...

industrialcraft_2_2.8.221_ex112
appliedenergistics2-rv6-stable-7
IndustrialUpgrade-1.12.2-2.3.5

### Which minecraft version are you using?

1.12 - UNSUPPORTED

### On which mod loaders does it happen?

Forge

### Crash log

no crash

**Comment by Technici4n** [comment]
We don't support 1.12.
