### ISSUE TITLE
Import/Export buses should scale items moved with dynamic tick rate

### ISSUE THREAD

**Issue by rjb3977** [AppliedEnergistics/Applied-Energistics-2#6366]
### Describe the feature

IO buses currently don't take ticksSinceLastCall into account when doing work, so they're quite slow when they're starting up. This also means that changing their dynamic ticking rates in the config changes their overall throughput, which doesn't seem consistent with the idea of dynamic ticking.

### Reasons why it should be considered

It will make the throughput of IO buses consistent even when they're not constantly active.

**Comment by Technici4n** [comment]
Thanks for the suggestion. I am not sure about this, we'll have to discuss it internally. Community feedback is welcome.

Personally I think that the ramping up effect is pretty cool.

**Comment by Silfryi** [comment]
I do like the ramp-up as well, it makes more sense here I feel. Not much left to say for me on this.

**Comment by Technici4n** [comment]
I think the current behavior is fine, I want to keep the ramp-up.
