### ISSUE TITLE
Annoying Bug: Broken Cables/Inscribers/Interfaces.

### ISSUE THREAD

**Issue by PiggyWhiskey** [AppliedEnergistics/Applied-Energistics-2#637]
I have an extremely annoying bug that is very hard for me to reproduce.

I've looked though previous issues and could see anything (May have missed it though)

Playing the Dark Trilogy Modpack 1.0.6 (AE2 RV2 Beta 1) on a server.
Extra mods are client side (InGameInfo/Schematica etc)

Now for the bug. All cables and AE2 machines break on server restart. 
The server is set to restart every 4 hours.

This includes ME Interfaces and the Inscribers.
I can Open the Inscriber interface, but not for the ME Interface interface.
The cables/Machines/Interfaces need to be broken and re-placed when this happens.
The "Break" occurs directly on the chunk boundary affects all AE2 blocks/cables outside of the chunk the Controller is in.

http://puu.sh/dMhxm/3b7bb22caf.jpg

I can't get this to repeat reliably. nor in Single Player.
I can see in the config that there are a few logging options. Not knowing if they work on client side or server side I didn't want to mess with them.

What can I do to help fault find this bug?

**Comment by PiggyWhiskey** [comment]
Update: I couldn't get access to the server logs.
But the issue seems to have resolved itself.
Several restarts and it hasn't caused an issue.

**Comment by yueh** [comment]
Reopen if you can provide a way to reproduce it.
