### ISSUE TITLE
Keep a certain number of items in stock and craft on demand

### ISSUE THREAD

**Issue by rosavi** [AppliedEnergistics/Applied-Energistics-2#638]
So, this is actually more of a question than a feature request or bug report, but this seemed the best place to ask since I don't have a reddit account and am currently unable to use IRC (long story).

Is there a way to keep a certain number of items always in stock but still be able to craft them when needed without duplicating everything? I have my printed circuits on automated crafting by way of level emitters, but if I want to auto-craft anything in bulk that requires more printed circuits than I currently have in stock it won't work. I could either duplicate everything (making more presses, inscribers, and using interfaces with patterns instead of level emitters) or I could greatly increase the number of items to keep in stock. Both seem very wasteful.

On the same note, I have my processors automated, but making each one takes a long time and I would like to keep a small number of each always in stock to speed up trivial crafting tasks.

Is there a way to do this? If there isn't, is there a chance such a feature could be added? Maybe an option on the interface that will autocraft stuff everytime it falls below a certain level without it needing to be manually requested?

**Comment by beepbeat** [comment]
You can also have an storage bus pointing on an interface with an crafting card as long as both the bus and the interface are in the same network. Just define your desires in the interface and the storage bus is able to read the inventory of the interface causing configured items to show up in the system.

**Comment by Morpheus1101** [comment]
This is essentially what im trying to do, but without success.  I have 15 interfaces, all with storage buses on them to maintain 1 stack of 15 different types of ore blocks, but once i run lower then 64, it isnt Automatically crafting more.  I have patterns for everything an 15 processors, but im not figuring out what im missing to why it isnt working. Do i need ot have those 15 on the same colored cable as m y dirves/autocrafting system ?

![javaw_2018-05-25_14-04-25](https://user-images.githubusercontent.com/10524952/40525758-63ec09aa-6025-11e8-8b47-fc3a56ff0d68.png)

**Comment by mindforger** [comment]
i think if you attach a storage bus on to an interface some special code is kicking in, i tried this one in 1.7.10 and it does not work because of an infinite loop it would cause or something like that

you should try the way @thatsIch already provided in 2014

**Comment by Morpheus1101** [comment]
I ended up working it all out.  I had to have the Interfaces on the same Network as my monitors then a completely separate colored cable again connected to the storage buses for it to do what i wanted.

**Comment by mindforger** [comment]
please send a picture of it, how it works :) would be a great reference to have

**Comment by Morpheus1101** [comment]
The Orange Cables are connected To 1 controller which has the interfaces you see here as well as my Interface, Crafting & Pattern Terminal, this enabled the autocrafting to start when the level of each ore block dropped below 64.  Then i had to use a separate sub network being the Lime Green Cables to connect to the StorageBuses in order for the network to see them.

![2018-05-25_18 44 17](https://user-images.githubusercontent.com/10524952/40535156-ad379950-604b-11e8-9042-9decd0cf53f7.png)
