### ISSUE TITLE
ME drive frontside is permanently cast in shadow when Rubidium is installed

### ISSUE THREAD

**Issue by Vapaman** [AppliedEnergistics/Applied-Energistics-2#6381]
### Describe the bug

Reported here on Rubidiums side
https://github.com/Asek3/Rubidium/issues/149

![kuva](https://user-images.githubusercontent.com/77460466/172957964-5f09b51e-3835-42c8-88eb-bfa4bd3bfcad.png)
![kuva](https://user-images.githubusercontent.com/77460466/174512180-8374fcd8-a049-4d3f-9734-ab4e04ba0e86.png)

Installed mods:

Forge 40.1.51
AE2 11.1.3
Rubidium 0.5.2a

This does not happen with other blocks, for example the ME chest
![kuva](https://user-images.githubusercontent.com/77460466/174512744-2a075967-c13f-4ad2-899a-491dadeed9ca.png)

### How to reproduce the bug

Place down a ME drive. The front of it is cast in shadow.

### Expected behavior

Expected look:
![kuva](https://user-images.githubusercontent.com/77460466/172958002-84fc939a-3884-4b2d-9acc-dd790899aaff.png)

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/FfZf8eDM

**Comment by Technici4n** [comment]
If it works with Sodium and Indium, it must be a bug in Rubidium.
