### ISSUE TITLE
Crash while loading with absolutely no log information

### ISSUE THREAD

**Issue by egshels** [AppliedEnergistics/Applied-Energistics-2#6384]
### Describe the bug

Started crashing while developing my modpack after adding AE2. Eventually narrowed it down to **only** AE2 - this happens without any other mods. Works on all Forge versions for 1.18.2. 
Edit: Re-installing the modpack does tell me a crash. It's weird though

### How to reproduce the bug

Launch the game.

### Expected behavior

It loads.

### Additional details

Here's my modpack file:
[Disccord Rebooted-1.0.0.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/8944926/Disccord.Rebooted-1.0.0.zip)
 

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/egshels/8a164ef93706ef1ee28baf7cfdc029e3
Edit: Updated log, with crash info this time https://gist.github.com/egshels/c45b511b826e67c1c881b7f66cc5a071

**Comment by Technici4n** [comment]
`cleancut` issue apparently, nothing to do with AE2.
