### ISSUE TITLE
Disabling channels on rv2 beta 2 is crashing the game

### ISSUE THREAD

**Issue by UnstableZer0** [AppliedEnergistics/Applied-Energistics-2#639]
i disabled channels on rv2 beta 2, aswell as achievements, as i read someone had a problem with facades and turning off achievements helped with it. 

using ae2stuff and ae2tech addon (and a couple other mods (136 in total)

anyway it's crashing me, i removed all the addon mods etc. tried that - crashed.
only if i reenable it it's working again. It also caused me to remove modular power suits.
it was working 1 time, i shut down the game and as i wanted to get back in crash, i'm nearly at 6 hours trying to figure out what's wrong. I might give a new instance a shot but i doubt that'll help. 
anyway: crashlog: http://paste.ee/p/bp4Cm it's throwing a couple exceptions before crashing. 
p2p tunnels are also turned off (crashed before aswell)

is there anythign i need to turn off to get it working? 

nvm, i forgot to save after setting achievements to false, works now. 

but if i want to look up the creative tab now, it's crashing
new crashlog: http://paste.ee/p/HjmOm

**Comment by robindegen** [comment]
Is this supposed to be fixed in the newer beta's? I've tested this with beta 7 and it still crashes. However, alpha build 29 seems to work. It just removes the controller and cables, is that correct?

**Comment by Cisien** [comment]
The most recent builds should be stable with channels disabled. If you're getting a crash still, can you post the crash log?

**Comment by robindegen** [comment]
@Cisien 
I cant seem to find anything AE2 specific in the callstack. I am running this as part of the resonant rise 3 modpack. Disabling seems to cause some conflict with another mod (dmillerw.remoteio) on AE2 rv2 build 5 (resonant rise 3 default) and build 7, that does not happen with rv2 alpha build 29. Do you still wish me to post this crashdump?

**Comment by Sailren** [comment]
if its something with the modpack tell them about it. it doesnt make sense if u just fix it in your client and other modpack users still crash

**Comment by yueh** [comment]
@robindegen the remoteio is not compatible with rv2 (there is already another issue: #719)
But nothing we can do at your side. Report it to the author of remoteio.

**Comment by robindegen** [comment]
@yueh That's strange, because it does seem to work with rv2 build 5 beta, as long as I leave channels enabled. Good to know though. @Sailren I will do further research to see where it goes wrong exactly and report it at the right place. Maybe I can debug some and send in a PR to fix it.

**Comment by yueh** [comment]
rv2 introduced the option to disable channels and it looks like the mod is depending on some items/recipes, which then are removed if they are not needed with disabling channels (or might cause issues etc)

**Comment by robindegen** [comment]
@yueh That would make sense but why does it work with rv2 alpha build 29 ? I changed nothing else, just downgraded to that alpha build. Then it works just fine. On that build i have disabled channels, and it removed all non fluix glass cables from the world (the smart and big ones). After placing back normal fluix cables, everything was fine.

**Comment by AnkokuTeion** [comment]
i have a bug, in creative with channels disabled, rv2 beta 24. getting the following crash report.

---- Minecraft Crash Report ----
// My bad.

Time: 06/04/15 18:24
Description: Rendering item

java.lang.RuntimeException: Unable to construct IBusPart from IBusItem : appeng.parts.p2p.PartP2PRFPower ; Possibly didn't have correct constructor( ItemStack )
	at appeng.items.parts.ItemMultiPart.createPartFromItemStack(ItemMultiPart.java:278)
	at appeng.client.render.BusRenderer.getRenderer(BusRenderer.java:168)
	at appeng.client.render.BusRenderer.renderItem(BusRenderer.java:142)
	at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:183)
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:563)
	at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:488)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: cofh/api/energy/IEnergyReceiver
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.getConstructor(Unknown Source)
	at appeng.items.parts.ItemMultiPart.createPartFromItemStack(ItemMultiPart.java:271)
	... 19 more
Caused by: java.lang.ClassNotFoundException: cofh.api.energy.IEnergyReceiver
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 24 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at appeng.items.parts.ItemMultiPart.createPartFromItemStack(ItemMultiPart.java:278)
	at appeng.client.render.BusRenderer.getRenderer(BusRenderer.java:168)
	at appeng.client.render.BusRenderer.renderItem(BusRenderer.java:142)
	at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:183)

-- Item being rendered --
Details:
	Item Type: ItemPart
	Item Aux: 466
	Item NBT: null
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:563)
	at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:488)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (429, 185). Absolute: (858, 334)
	Screen size: Scaled: (683, 353). Absolute: (1366, 705). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['Ankoku_Teion'/349, l='MpServer', x=-95.54, y=60.62, z=185.18]]
	Chunk stats: MultiplayerChunkCache: 121, 121
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-108,64,100), Chunk: (at 4,4,4 in -7,6; contains blocks -112,0,96 to -97,255,111), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 43713 game time, 43713 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 62 total; [EntitySheep['Sheep'/149, l='MpServer', x=-111.09, y=88.00, z=255.88], EntityChicken['Chicken'/157, l='MpServer', x=-102.38, y=64.00, z=107.63], EntityChicken['Chicken'/160, l='MpServer', x=-99.47, y=67.00, z=113.53], EntityChicken['Chicken'/161, l='MpServer', x=-100.63, y=71.00, z=118.41], EntityChicken['Chicken'/162, l='MpServer', x=-100.53, y=74.00, z=121.47], EntitySheep['Sheep'/165, l='MpServer', x=-97.13, y=88.00, z=260.81], EntitySquid['Squid'/551, l='MpServer', x=-43.56, y=59.34, z=164.94], EntitySheep['Sheep'/173, l='MpServer', x=-95.25, y=88.00, z=262.34], EntityChicken['Chicken'/175, l='MpServer', x=-77.41, y=88.00, z=143.47], EntityChicken['Chicken'/176, l='MpServer', x=-64.53, y=88.00, z=143.47], EntityChicken['Chicken'/177, l='MpServer', x=-69.50, y=88.00, z=139.50], EntityChicken['Chicken'/178, l='MpServer', x=-61.63, y=88.00, z=137.59], EntityItem['item.item.egg'/179, l='MpServer', x=-70.34, y=88.13, z=140.66], EntityItem['item.item.egg'/180, l='MpServer', x=-70.78, y=88.13, z=138.81], EntityItem['item.item.egg'/181, l='MpServer', x=-67.34, y=88.13, z=139.84], EntitySheep['Sheep'/182, l='MpServer', x=-67.50, y=73.00, z=159.50], EntitySheep['Sheep'/183, l='MpServer', x=-67.50, y=73.00, z=159.50], EntitySheep['Sheep'/184, l='MpServer', x=-70.41, y=63.00, z=167.50], EntitySheep['Sheep'/56, l='MpServer', x=-153.13, y=88.00, z=193.09], EntitySheep['Sheep'/185, l='MpServer', x=-72.50, y=65.00, z=169.34], EntitySheep['Sheep'/57, l='MpServer', x=-161.91, y=88.00, z=186.97], EntitySheep['Sheep'/58, l='MpServer', x=-157.78, y=90.00, z=185.13], EntitySheep['Sheep'/203, l='MpServer', x=-57.78, y=88.00, z=136.22], EntitySheep['Sheep'/204, l='MpServer', x=-48.16, y=88.00, z=139.44], EntitySheep['Sheep'/205, l='MpServer', x=-60.50, y=87.00, z=138.50], EntitySheep['Sheep'/206, l='MpServer', x=-51.81, y=83.00, z=142.19], EntitySheep['Sheep'/207, l='MpServer', x=-59.16, y=90.00, z=247.19], EntitySheep['Sheep'/79, l='MpServer', x=-145.03, y=64.00, z=127.03], EntitySheep['Sheep'/208, l='MpServer', x=-60.72, y=92.00, z=250.59], EntitySheep['Sheep'/80, l='MpServer', x=-147.50, y=64.00, z=133.50], EntitySheep['Sheep'/209, l='MpServer', x=-59.53, y=90.00, z=248.41], EntitySheep['Sheep'/81, l='MpServer', x=-146.84, y=64.00, z=131.50], EntitySheep['Sheep'/82, l='MpServer', x=-159.69, y=89.00, z=185.94], EntitySheep['Sheep'/83, l='MpServer', x=-140.41, y=77.00, z=229.47], EntitySheep['Sheep'/84, l='MpServer', x=-158.94, y=65.00, z=233.88], EntitySheep['Sheep'/85, l='MpServer', x=-151.91, y=66.00, z=239.88], EntitySheep['Sheep'/86, l='MpServer', x=-160.44, y=68.00, z=227.28], EntitySheep['Sheep'/87, l='MpServer', x=-165.06, y=64.00, z=250.03], GCEntityClientPlayerMP['Ankoku_Teion'/349, l='MpServer', x=-95.54, y=60.62, z=185.18], EntitySheep['Sheep'/227, l='MpServer', x=-40.50, y=91.00, z=137.50], EntitySheep['Sheep'/228, l='MpServer', x=-43.50, y=94.00, z=137.50], EntitySheep['Sheep'/229, l='MpServer', x=-40.16, y=86.00, z=140.66], EntitySheep['Sheep'/230, l='MpServer', x=-44.97, y=84.00, z=141.91], EntitySheep['Sheep'/102, l='MpServer', x=-130.84, y=63.00, z=107.22], EntitySheep['Sheep'/231, l='MpServer', x=-32.81, y=63.00, z=156.63], EntitySheep['Sheep'/103, l='MpServer', x=-134.97, y=63.00, z=107.84], EntitySheep['Sheep'/232, l='MpServer', x=-45.34, y=85.00, z=248.09], EntitySheep['Sheep'/104, l='MpServer', x=-133.47, y=63.00, z=109.25], EntitySheep['Sheep'/105, l='MpServer', x=-128.56, y=64.00, z=112.66], EntitySheep['Sheep'/106, l='MpServer', x=-143.72, y=64.00, z=134.84], EntitySheep['Sheep'/107, l='MpServer', x=-130.06, y=68.00, z=158.38], EntitySheep['Sheep'/108, l='MpServer', x=-132.47, y=68.00, z=158.63], EntitySheep['Sheep'/109, l='MpServer', x=-131.66, y=69.00, z=159.84], EntitySheep['Sheep'/110, l='MpServer', x=-130.50, y=71.00, z=163.50], EntitySheep['Sheep'/111, l='MpServer', x=-134.22, y=76.00, z=225.84], EntitySheep['Sheep'/112, l='MpServer', x=-130.50, y=73.00, z=223.50], EntitySheep['Sheep'/240, l='MpServer', x=-16.53, y=87.00, z=109.38], EntitySheep['Sheep'/113, l='MpServer', x=-130.50, y=71.00, z=224.50], EntitySheep['Sheep'/241, l='MpServer', x=-21.50, y=63.00, z=150.50], EntitySheep['Sheep'/114, l='MpServer', x=-128.38, y=66.00, z=225.34], EntitySheep['Sheep'/242, l='MpServer', x=-20.03, y=63.00, z=151.97], EntitySheep['Sheep'/243, l='MpServer', x=-19.97, y=63.00, z=147.03]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:909)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 333210792 bytes (317 MB) / 635453440 bytes (606 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.103.1352 Minecraft Forge 10.13.2.1352 18 mods loaded, 18 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.103.1352} [Forge Mod Loader] (forge-1.7.10-10.13.2.1352-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1352} [Minecraft Forge] (forge-1.7.10-10.13.2.1352-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	appliedenergistics2-core{rv2-beta-24} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.3.74} [Not Enough Items] (Not-Enough-Items-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DamageIndicatorsMod{3.2.0} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	appliedenergistics2{rv2-beta-24} [Applied Energistics 2] (appliedenergistics2-rv2-beta-24.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CarpentersBlocks{3.3.4} [Carpenter's Blocks] (Carpenter's Blocks v3.3.4 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FWG{1.0.3} [Fun World Gen] (Fun-World-Gen-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GalacticraftCore{3.0.11} [Galacticraft Core] (GalacticraftCore-1.7-3.0.11.306.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GalacticraftMars{3.0.11} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.11.306.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	journeymap{5.0.1} [JourneyMap] (JourneyMap5.0.1_Unlimited_MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mystcraft{0.11.0.00} [Mystcraft] (mystcraft-1.7.10-0.11.0.00.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	RedstonePasteMod{1.6} [Redstone Paste] (RedstonePasteMod-1.7.2-1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TConstruct{1.7.10-1.8.3.build919} [Tinkers' Construct] (TConstruct-1.7.10-1.8.3b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AE2 Version: beta rv2-beta-24 for Forge 10.13.2.1291
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:OFF, MJ6:OFF, MJ5:OFF, RF:OFF, RFItem:OFF, MFR:OFF, DSU:OFF, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: 1.7.10-Forge10.13.2.1352-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics GL version 3.1.0 - Build 9.17.10.2843, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [Sphax PureBDcraft  64x MC17.zip, BiomesOPlenty-1.7.10- x64.zip, Sphax64x_Galacticraft_3.0.6.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by thatsIch** [comment]
This seems related to the RF API, please open up a new issue
