### ISSUE TITLE
1.18.2 AE2 Things Advanced Inscribers are slow

### ISSUE THREAD

**Issue by ixam22** [AppliedEnergistics/Applied-Energistics-2#6402]
### Describe the bug

Advanced Inscribers are really slow

### How to reproduce the bug

produce anything in them, with 4 on one pattern provider speed is still lacking for bigger auto crafting, with full acceleration cards of corse

### Expected behavior

faster

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

a

**Comment by quietust** [comment]
I think you meant to report this in the ProjectET/AE2Things project.
