### ISSUE TITLE
When trying to load up a server with only AE2 rv6-stable-7 server crashes with error message

### ISSUE THREAD

**Issue by ValrV** [AppliedEnergistics/Applied-Energistics-2#6411]
### Describe the bug

net.minecraftforge.fml.common.LoaderException: appliedenergistics2 Failed load class: appeng.core.AppEng
error is given when trying to load up newest 1.12.2 version

### How to reproduce the bug

Downloaded forge-1.12.2-14.23.5.2860 server and put appliedenergistics2-rv6-stable-7 and appliedenergistics2-10.0.1 in mods folder
Started server and server crashed shortly with an error message

### Expected behavior

AE2 loaded up and server started with no crash

### Additional details

forge-1.12.2-14.23.5.2860, forge-1.12.2-14.23.5.2859 and forge-1.12.2-14.23.5.2854 were all tried in an attempt to get the mod to work
 9GB of ram was allocated and jdk-8.0.312.7 was used

### Which minecraft version are you using?

1.12 - UNSUPPORTED

### On which mod loaders does it happen?

Forge

### Crash log

---- Minecraft Crash Report ---- // This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]  Time: 29.06.2022 09:05 Description: Exception in server tick loop  net.minecraftforge.fml.common.LoaderException: appliedenergistics2 Failed load class: appeng.core.AppEng 	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:544) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:498) 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) 	at com.google.common.eventbus.EventBus.post(EventBus.java:217) 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:498) 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) 	at com.google.common.eventbus.EventBus.post(EventBus.java:217) 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) 	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595) 	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) 	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) 	at java.lang.Thread.run(Thread.java:748) Caused by: java.lang.ClassNotFoundException: appeng.core.AppEng 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) 	at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:75) 	at java.lang.Class.forName0(Native Method) 	at java.lang.Class.forName(Class.java:348) 	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539) 	... 31 more Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@3228d990 from coremod FMLCorePlugin 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260) 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) 	... 37 more Caused by: java.lang.IllegalArgumentException 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:185) 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:168) 	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:53) 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256) 	... 39 more   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- System Details -- Details: 	Minecraft Version: 1.12.2 	Operating System: Windows Server 2012 R2 (amd64) version 6.3 	Java Version: 1.8.0_312, Temurin 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin 	Memory: 9048504928 bytes (8629 MB) / 9261023232 bytes (8832 MB) up to 9261023232 bytes (8832 MB) 	JVM Flags: 2 total; -Xmx9G -Xms9G 	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0 	FML: MCP 9.42 Powered by Forge 14.23.5.2860 5 mods loaded, 5 mods active 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored  	| State | ID                  | Version      | Source                               | Signature                                | 	|:----- |:------------------- |:------------ |:------------------------------------ |:---------------------------------------- | 	| LC    | minecraft           | 1.12.2       | minecraft.jar                        | None                                     | 	| LC    | mcp                 | 9.42         | minecraft.jar                        | None                                     | 	| LC    | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 | 	| LC    | forge               | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 | 	| LE    | appliedenergistics2 | rv6-stable-3 | appliedenergistics2-rv6-stable-3.jar | None                                     |  	Loaded coremods (and transformers):  	Profiler Position: N/A (disabled) 	Is Modded: Definitely; Server brand changed to 'fml,forge' 	Type: Dedicated Server (map_server.txt)

**Comment by mindforger** [comment]
you sure you loaded the right file into your server?

appliedenergistics2-rv6-stable-3

from your log

also please use pastebin next time this is hard to read without any formatting

additionally 1.12 is not supported anymore
