### ISSUE TITLE
Bug in version 1.18.2 AE2 11.1.3[FORGE].

### ISSUE THREAD

**Issue by naluisio** [AppliedEnergistics/Applied-Energistics-2#6412]
### Describe the bug

 Hi devs. 
 I find Bug in ME Patternal Encoding Terminal. Craft bug on ME Patternal encolding. 

Sorry my english, i try speech on school lessom for no usse google translate ande increase my language.

### How to reproduce the bug

 After complete recipe on craft grid press encode Pattern and not put Pattern on slot for this recipe consume materials and not give for you recipe in all try. Same time this terminal not give for you your crafts.
Simple patern encoding use in all creation build

### Expected behavior

Give me recipe creation after pick.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

Not have, this in playn game.

**Comment by Technici4n** [comment]
Pattern encoding terminal doesn't allow crafting the items anymore. If you want to craft items, use a crafting terminal. If you want to encode patterns, use the pattern encoding terminal.

**Comment by naluisio** [comment]
@Technici4n 
The Bug I'm wanting to report happens by performing the sequence of events. 
Place the items arranged in the recipe format > press the button to encode with the empty pattern slot > try to pick up your recipe with both mouse buttons = start consuming your items without anything happening.

**Comment by Mari023** [comment]
the items in the recipe aren't "real" items.
so when you click on them, the disappear.
you don't loose anything however, since it doesn't use your items when you put a recipe in it

**Comment by naluisio** [comment]
@Mari023 they disappear from their disk in the amrazenamento part and don't come back

**Comment by Technici4n** [comment]
Could you maybe record a video of the issue?
