### ISSUE TITLE
Make Crafting / Processing mode button changing tooltips better

### ISSUE THREAD

**Issue by Technici4n** [AppliedEnergistics/Applied-Energistics-2#6418]
Based from some feedback:

> the button to swap between processing and crafting pattern mode feels backwards to me, it didnt make sense that it was telling me the current mode i was on. i assumed it meant press this button to go to that mode

**Comment by Technici4n** [comment]
We could have something like

`Crafting Mode` on one line.
`Click to change to Processing Mode` on the second line.

**Comment by 62832** [comment]
For whatever reason, I've found myself having this issue not with the recipe mode button, but with the substitutions one. Maybe that one could also be addressed alongside if need be?

**Comment by Shadow-Devil** [comment]
I would like to work on this issue. Anything else that should be changed than the two buttons (Crafting/Processing mode and Recipe/Substitution mode)?

**Comment by Technici4n** [comment]
> I would like to work on this issue. Anything else that should be changed than the two buttons (Crafting/Processing mode and Recipe/Substitution mode)?

@Shadow-Devil No idea. If you find another tooltip to change that's good, otherwise just these two is also good.
