### ISSUE TITLE
No Power

### ISSUE THREAD

**Issue by OMM1ner** [AppliedEnergistics/Applied-Energistics-2#6419]
### Describe the bug

ME System not receiving power when power is clearly working.

### How to reproduce the bug

I don't know how.

### Expected behavior

The ME System would have power to it, can be used.

### Additional details

Don't know if it's a crash or bug or if I'm doing something wrong. Followed a tutorial by RagePlayGames.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://appliedenergistics.github.io/ae2-site-archive/index.html

**Comment by mindforger** [comment]
no logs, no versions, no pictures ... how do you expect someone to help you?

**Comment by OMM1ner** [comment]
I apologise, but when I posted this, it was my first time on GitHub. I didn't know what you had to do, etc.

After a few hours, I kept trying but nothing happened.

**Comment by Technici4n** [comment]
Please ask on the Discord server, we will ask you to post relevant screenshots etc there. The mod is stable enough for "it doesn't work for me" to give us essentially 0 information about the issue that you are facing.
