### ISSUE TITLE
Dupe using Inscriber

### ISSUE THREAD

**Issue by nedfreetoplay** [AppliedEnergistics/Applied-Energistics-2#6422]
### Describe the bug

I use pipes from the Cyclic-1.16.5-1.5.15 mod and give the task to the pipe to replenish the Inscriber with items that are in the chest. The pipe successfully puts a lot of items in the Inscriber and leaves the same stack of items in the chest that are already in the Inscriber.

[Youtube video](https://youtu.be/9mmMLIms9bE)

### How to reproduce the bug

1. Place a item pipe from the Cyclic-1.16.5-1.5.15 mod
2. Put the chest and inscriber next to the pipe
3. Adjust the pipe to remove items from the chest using a wrench
4. Put any items that can stack from 3 pieces
5. Pick up items that appear in the Inscriber
6. Repeat the steps starting from step 4

### Expected behavior

The Inscriber should not fit more than 1 item per slot

### Which minecraft version are you using?

1.16 - UNSUPPORTED

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/w1tXFWQQ

**Comment by Technici4n** [comment]
This is clearly a cyclic bug since it does not occur with other kinds of pipes.
