### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by TheCherry** [AppliedEnergistics/Applied-Energistics-2#6426]
### Describe the bug

The Server crashs.
Used Version: AE2 12.0.1-alpha [FABRIC]
Its the 1.19 Version not 1.18! But I can't select 1.19 below.

Log File:
[latest.log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/9056901/latest.log)

 #6280 seems not to match. I haven't polymorph installed.

### How to reproduce the bug

Start the Server. If you need my Modpack, just tell me.

### Expected behavior

A booting Server

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://github.com/AppliedEnergistics/Applied-Energistics-2/files/9056901/latest.log

**Comment by TheCherry** [comment]
Now the Server boots but crash as soon as the first tick seems happen
[crash-2022-07-06_19.59.35-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/9057090/crash-2022-07-06_19.59.35-server.txt)
.

**Comment by Technici4n** [comment]
Fixed in recent versions.
