### ISSUE TITLE
Allow ComputerCraft to use Fluix Cables in place of networking cables

### ISSUE THREAD

**Issue by Merith-TK** [AppliedEnergistics/Applied-Energistics-2#6429]
### Describe the feature

I believe there are two ways to do this, 
1) Copy Wired Modem Logic (and Networking cables)

2) Master/Slave P2P connectors, 
The "Master" is the peripheral one wishes to connect, (in this case an monitor)
and the "Slave" is the connector that interfaces with the CC Computer, 

(screenshot uses P2P Energy just to give an visual,)
(Screenshot acquired from 1.18.2 version on Fabric)
![image](https://user-images.githubusercontent.com/10422110/177667249-900295a6-c762-4a46-91be-9e647aef52df.png)
![image](https://user-images.githubusercontent.com/10422110/177667840-9b8d2f0c-ff3d-4df6-9515-eaedef306fd9.png)

The "Slave" will mimic/copy the API of the Master

of course using fluix cables for this would come at the cost of Lanes being taken up!

### Reasons why it should be considered

Aesthetic's mostly, but would also allow for better integration of automation through other means that might not yet be completely supported by AE2, 

### Additional details
![image](https://user-images.githubusercontent.com/10422110/177668366-add7e6d3-33b1-41b8-a757-e4d7426f560c.png)
How I faked the screenshot

[Forge, CC:Tweaked](https://github.com/cc-tweaked/CC-Tweaked)
[Fabric, CC:Restitched](https://github.com/cc-tweaked/cc-restitched)

**Comment by 62832** [comment]
This just sounds like you're asking for a P2P tunnel to integrate with ComputerCraft which, granted, would make for a cool add-on. ME cables on their own as in that pic will not function unless powered to make up a dedicated ME network.

**Comment by Merith-TK** [comment]
I am aware of power limitations, and yeah, P2P CC tunnel would be very nice! even if it just replicates modems!

the only reason why AE2 showed up as an peripheral at all in the example, is because the Unlimited Peripheral Works mod for CC:Restitched, adds more Peripheral API's (fabric transfer api support as well which theoretically means it could interface with AE2 if ae2 presented its ME interfaces to CC)

**Comment by Technici4n** [comment]
Adding P2P tunnels for mod integrations should be done in addons, not AE2 itself. Feel free to ask for pointers on how to use the API.

> if ae2 presented its ME interfaces to CC

It's up to CC to use the AE2 API for this. For example, that's what the [Advanced Peripherals mod](https://www.curseforge.com/minecraft/mc-mods/advanced-peripherals) does on Forge. ;)
