### ISSUE TITLE
Use the material cannon to attack the end shadow dragon, causing the server to crash

### ISSUE THREAD

**Issue by 3cxc** [AppliedEnergistics/Applied-Energistics-2#6431]
### Describe the bug

Use the material cannon to attack the end shadow dragon, causing the server to crash

### How to reproduce the bug

Test under AE2 rv6-stable-7 version
Loading any bullets and shooting at the end of the shadow dragon will collapse

### Expected behavior

Fix the bug

### Which minecraft version are you using?

1.12 - UNSUPPORTED

### On which mod loaders does it happen?

Forge

### Crash log

NO log

**Comment by Technici4n** [comment]
1.12 is unsupported. This bug was fixed in 1.16 iirc.
