### ISSUE TITLE
Cable Facades don't have any recipes

### ISSUE THREAD

**Issue by Cop4Terminator** [AppliedEnergistics/Applied-Energistics-2#6433]
### Describe the bug

so before i could craft cable facades as normal but even after updating to the newest version of AE2, and looking everywhere in the configs i still can't seem to figure out why i can't craft any of the facades. i suspect some mod decided to manually remove the recipes, but as a placeholder until i figure it out, i added an EMC value to the facades so i can still get them some way or another.

### How to reproduce the bug

this is kinda hard to explain, but i have no clue how it even happened, one time it was fine, then after relaunching the modpack, it just stopped working.

### Expected behavior

for it to work normally

### Additional details

using a custom modpack, with things such as JEI, ProjectE, CraftTweaker etc, all preset in the crash log

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/5tAfr433

**Comment by Technici4n** [comment]
We can't do anything about your modpack. Please reopen if it happens with only AE2 installed (no other mods).
