### ISSUE TITLE
Matter condenser getting locked up

### ISSUE THREAD

**Issue by Mecr0mage** [AppliedEnergistics/Applied-Energistics-2#6435]
### Describe the bug

the Matter condenser seems to get stuck when it makes a stack of matter balls and continues to get items put in, building up its energy.

### How to reproduce the bug

make a processing pattern with 4 stacks of an item to make a matter ball and place it on a pattern provider facing a matter condenser, order X amount of matter balls like 2 or 4 stacks and let it go and have something extract the matter balls from the condenser slowly so a stack builds up and the energy inside builds up.

### Expected behavior

matter condenser will continue to use its built up energy to make matter balls after the stack inside is removed without having to switch mods back and forth.

### Additional details

Useing AE version (appliedenergistics2-11.1.3.jar)

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/xEgN30K3

**Comment by Mari023** [comment]
I think I fixed that exact issue in 11.1.4.
can you try if it still exists in that version?

**Comment by Mecr0mage** [comment]
i can check it out in single player when i get a chance, currently on a server.

**Comment by Mecr0mage** [comment]
Yes it is fixed in 11.1.4 mb lol, ill have to make sure to read the changelog if im not using the latest version. thank you.
