### ISSUE TITLE
Spatial anchor point overlay does not work correctly

### ISSUE THREAD

**Issue by Bifrost123** [AppliedEnergistics/Applied-Energistics-2#6436]
### Describe the bug

Spatial anchor point overlay does not work correctly

### How to reproduce the bug

It does not work after placing the cube

### Expected behavior

![Uploading unknown_2022.07.12-22.01_1.png…]()

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

None

**Comment by Technici4n** [comment]
Spatial anchor is not supported on Fabric for the moment due to the lack of a chunkloading API.
