### ISSUE TITLE
setable amount for crafting card

### ISSUE THREAD

**Issue by official-Cromatin** [AppliedEnergistics/Applied-Energistics-2#6438]
### Describe the feature

If you place an export bus in an inventory, you can put in a crafting card and thus determine that if there are no more items, this and that should be crafted.

Unfortunately, it is the case that you cannot set a quantity, and then only one is crafted at a time, now only the amount in the recipe can be adjusted.

### Reasons why it should be considered

If you have a large inventory or a lot of consumption, it takes a long time to fill it up, and it also generates some lag when a recipe is generatet over and over again.

**Comment by atlgeek007** [comment]
You don't even need a subnetwork on modern versions of AE2 since level emitters no longer take channels.

**Comment by Mari023** [comment]
> You don't even need a subnetwork on modern versions of AE2 since level emitters no longer take channels.
the storage bus does tho

but the actual reason to use a subnet is because you probably don't want to count the items you have in your main network, only the items in the external storage

**Comment by official-Cromatin** [comment]
There is a "Workaround" for this Issue, the Mod Lazier AE2 adds a Block Called ME Requester.

In it you can Specify different Items and how mouch should be in the System, you could even Specify the Number of Items that should be Craftet.

But it would be quite Nice to have this Implemented by Default

**Comment by official-Cromatin** [comment]
> you can do this with a small subnetwork: put a storage bus on the inventory and use a level emitter to send out a redstone signal to disable the export bus (requires a redstone card in the export bus)

This is an Solution but not very fancy and solves also not my initial problem, that i cant set the amount of the items which should be crafted

**Comment by Mari023** [comment]
oh, you mean it should craft multiple at once?
this is only really possible by changing the recipe
that would indeed be a nice feature for the crafting card

**Comment by official-Cromatin** [comment]
A small gui like the one where you can set the priority would be enough

And another function that would make the whole thing easier is that if you set a amount, the system in the background checks whether you have correspondingly large crafting CPUs, if not then the set amount is colored red

**Comment by Technici4n** [comment]
I don't want to overload GUIs more with niche features. This can already be achieved (in admittedly clunkier ways), or could also be provided by addon developers if they wish to.

**Comment by official-Cromatin** [comment]
Since AE version 12.6.0 there are menus in which you can set e.g. the search behavior of the terminal, at that time the feature request was rejected because you did not want to make the (old) menu even fuller.

With the new menu, the whole thing should be better implementable, and possibly also be transferable to other expansion cards.

**Comment by Technici4n** [comment]
I'll let others decide. :P

**Comment by Random832** [comment]
What if it just, when acceleration cards were also installed, did a simulated insert of the number it can normally insert per operation and used that [along with cpu availability and ingredient availability] to determine how many to request?

**Comment by DAmNRelentless** [comment]
*sad soon obsolete ME Requester author noises*

**Comment by official-Cromatin** [comment]
> 

I think the idea is not bad, but you should still be able to overwrite this value.

**Comment by official-Cromatin** [comment]
Another idea that came to my mind is that it should be possibe to set an limit for the exporter, when he shold stop filling the connected inventory

**Comment by Technici4n** [comment]
Anyway, I suggest using the ME Requester mod. (FYI you can use acceleration cards to increase the size of the crafting batches).
