### ISSUE TITLE
When JEI plus button is hovered item counts are not checked

### ISSUE THREAD

**Issue by sadovsf** [AppliedEnergistics/Applied-Energistics-2#6439]
### Describe the bug

New JEI integration which shows what items are not available, which can be autocrafted (using CTRL+click) seems to no be checking counts on items. Ex i have recipe which takes 3 of same item but i have only 2 in storage. It will be highlighted as possible to craft and when clicked recipe in grid will (as it should) be missing one item as it was not enough in storage and you have to search for it and request crafting "old way".

### How to reproduce the bug

1) Have 1 oak plank in storage and 2 sticks.
2) Search in JEI oak fence and try to craft it using CTRL+click method.
3) You will see everything is fine and end up with partial recipe in crafting grid.

### Expected behavior

Checking need of crafting items should take recipe counts of given items and how much is them in store into a count.

### Additional details

AE2 version used: 11.1.4
FTB pack: Direwolf20 1.18 version 1.7.0

Tested on dedicated server

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

Not crashing

**Comment by sadovsf** [comment]
Sure, current version in pack is `jei-1.18.2-9.7.0.209`

**Comment by Technici4n** [comment]
I can't reproduce the issue:
![image](https://user-images.githubusercontent.com/13494793/180600831-f08fd8df-5d33-4a36-a8c9-c2f8e1b6a569.png)

**Comment by Technici4n** [comment]
When the items are craftable:
![image](https://user-images.githubusercontent.com/13494793/180600892-f28eddfa-adf6-4fd6-a523-46596bd99987.png)
Works as expected:
![image](https://user-images.githubusercontent.com/13494793/180600913-0d7a9310-1893-4b85-a3e5-f828039e4a64.png)

**Comment by sadovsf** [comment]
And yet it happens quite often with mekanism "alloys" (base tear being enriched alloy) of various tears. I will try to get some more concrete repro (it happens quite often but usually i do something so i just search and order crafting by hand). Probably tomorrow. Iam thinking maybe some interaction with other mods, it is possible when this happens i use wireless terminal (different mod) iam not sure from top of my head as iam using both native terminal and wireless quite often. 

nvm, will let you know ASAP
