### ISSUE TITLE
Dupe 1.16.5

### ISSUE THREAD

**Issue by TakeshiOver** [AppliedEnergistics/Applied-Energistics-2#6443]
### Describe the bug

Does anyone know how to solve this dupe? I'm using the following mods:
Applied energistics2 - 8.4.7
Lazierae2-1.16.5 - 2.0.4
Ae2ao-1.16.5 - 6.0.0
Ae2extras-1.16.5 - 1.3.1
Ae2wtlib-1.16.5 - 0.3.3

### How to reproduce the bug

https://imgur.com/a/LbZnTIk

### Expected behavior

Many players were abusing this on my server

### Which minecraft version are you using?

1.16 - UNSUPPORTED

### On which mod loaders does it happen?

Forge

### Crash log

.

**Comment by Technici4n** [comment]
1.16 is not supported anymore, and I can't reproduce this in 1.19.

**Comment by mindforger** [comment]
wireless crafting wasnt a thing in 1.12 was it? I suppose a bug in the addons mods not ae2, check their github repos for similar issues and solutions
