### ISSUE TITLE
AE 2 Fabric conflicting with shaders

### ISSUE THREAD

**Issue by ghost** [AppliedEnergistics/Applied-Energistics-2#6444]
### Describe the bug

Immediate crash after displaying the Mojang splash screen.

### How to reproduce the bug

Download either Optifine + Optifabric or Sodium + Iris

### Expected behavior

Game to run

### Additional details

I have a few other mods installed but it will only crash after optifine or sodium is applied.

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/bnxTtKZu and https://pastebin.com/fgNrfGLt

**Comment by Mari023** [comment]
optifine is not supported.
there is a bug in noindium which makes it crash when sodium is used without indium (it is supposed to tell you that you need indium)

-> solution for using sodium + iris: install indium
