### ISSUE TITLE
Connection reset by peer - for one person

### ISSUE THREAD

**Issue by 30p87** [AppliedEnergistics/Applied-Energistics-2#6449]
### Describe the bug

On our private Server, one person is always getting disconnected. The message is good old 'Connection reset by peer'. On the server side it first just logs 'xyz lost connection: Disconnected', then it will change to 'xyz lost connection: Timed out'. The client side will always show the error 'Connection reset by Peer'. No more errors or anything from the client nor server side. Removing AE from the client and server fixes everything. Note that I can play just fine, using the same IP, and that he can play in single player too. Also, it happened on windows and on a fresh install of Pop!_OS. I use Arch (btw). So it bascially HAS to be something with the connection, from him to me, which get's initiated from AE, but blocked by something along the way.

### How to reproduce the bug

Use the exact mods we used (see additional details), and connect to a remote server. Idk what other information is relevant for this.

### Expected behavior

Not timing out.

### Additional details

Minecraft version: 1.12.2
Fabric version: 14.23.5.2860 (All parties)
Java version: Both clients: internal Java (1.8.0_202); Server: 1.8.0

Mods (all Client and Server side, out of convinience:
[1.12.2] SecurityCraft v1.8.20.2.jar
AutoRegLib-1.3-32.jar
backpacks1.12.2-3.5.12.jar
BadMobs-1.12.2-1.1.40.jar
BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar
BetterFoliage-MC1.12-2.3.3.jar
BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar
Bloodmoon-MC1.12.2-1.5.3.jar
coroutil-1.12.1-1.2.37.jar
DayZombiez.jar
DynamicSurroundings-1.12.2-3.6.3.jar
EnderCore-1.12.2-0.5.76.jar
EnderIO-1.12.2-5.3.70.jar
Forgelin-1.8.4.jar
furniture-6.3.2-1.12.2.jar
future-mc-0.2.10.1.jar
iChunUtil-1.12.2-7.2.2.jar
Jade-0.1.0.jar
jei_1.12.2-4.16.1.302.jar
mcw-doors-1.0.3-mc1.12.2.jar
mcw-fences-1.0.0-mc1.12.2.jar
mcw-furniture-1.0.1-mc1.12.2beta.jar
mcw-roofs-1.0.2-mc1.12.2.jar
mcw-windows-1.0.0-mc1.12.2.jar
memory_repo
MineTraps-1.12.2-v.1.0.4.jar
MixinBootstrap-1.0.5.jar
MobDismemberment-1.12.2-7.0.0.jar
mobsunscreen-1.12.2-2.1.3.jar
NiftyBlocks-1.21.jar
OptiFine_1.12.2_HD_U_G5(3).jar
OreLib-1.12.2-3.6.0.1.jar
Quark-r1.6-179.jar
snowvariants-1.12.2-1.3.1.jar
SpartanShields-1.12.2-1.5.5.jar
SpartanWeaponry-1.12.2-1.4.1.jar
switchbow-1.6.8.jar
thiccentities-1.4.jar
ToolBelt-1.12.2-1.9.14.jar
ToughAsNails-1.12.2-3.1.0.141-universal.jar
Xaeros_Minimap_22.12.0_Forge_1.12.jar
XaerosWorldMap_1.26.0_Forge_1.12.jar
zombieawareness-1.12.1-1.11.16.jar

### Which minecraft version are you using?

1.12 - UNSUPPORTED

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/KzDX6n9k

**Comment by Technici4n** [comment]
We don't support 1.12 anymore. I would suggest that you look in the logs and try to figure out the issue yourself.
