### ISSUE TITLE
Pattern Access Terminal should show custom chest names

### ISSUE THREAD

**Issue by piperswe** [AppliedEnergistics/Applied-Energistics-2#6456]
### Describe the feature

I connect my Pattern Providers to chests, which then have pipes which move the items to many machines. This way, I only need one Pattern Provider when splitting a workload across multiple machines. I would like to be able to rename these chests in an anvil, and have those names appear in the Pattern Access Terminal so I can tell Pattern Providers apart.

### Reasons why it should be considered

This is an unobtrusive way to allow for customization of the Pattern Access Terminal's groupings, and doesn't introduce any new mechanics or GUIs.

**Comment by Mari023** [comment]
renaming the chest in an anvil should already show the name in the Pattern Access Terminal.
If it doesn't, that would be a bug.

**Comment by 62832** [comment]
Wrong. You can already rename the *pattern provider itself* to have it show up under its own grouping in the terminal, either with an anvil, Inscriber Name Press or anything else capable of renaming items.

**Comment by Mari023** [comment]
> Wrong. You can already rename the _pattern provider itself_ to have it show up under its own grouping in the terminal, either with an anvil, Inscriber Name Press or anything else capable of renaming items.

well that's what I get for never doing it myself
I always thought you rename the target inventory but I guess I am wrong

**Comment by piperswe** [comment]
> Wrong. You can already rename the _pattern provider itself_ to have it show up under its own grouping in the terminal, either with an anvil, Inscriber Name Press or anything else capable of renaming items.

Oh wow, I didn't know this was possible. I'll have to do this then.

I still think that using the target's name as well makes sense, since the groupings use the type of the target by default
