### ISSUE TITLE
improvedFluidMultiplier config keeps reverting to 2.0 muiltipler

### ISSUE THREAD

**Issue by Saereth** [AppliedEnergistics/Applied-Energistics-2#6458]
### Describe the bug

I've changed the improvedFluidMultiplier config option to 5.0 and defined a custom fluid tag. Everytime I launch however the config is re-written to a 2.0 (default) multiplier. The increased speed does work but only at a 2x multipler (Tested in game)

### How to reproduce the bug

is the ae2 config and change the improvedFluidMultiplier to anything other than 2.0 with a custom fluid defined and it reverts on launch

### Expected behavior

I would expect it to use my new value

### Additional details

AE2: 11.1.4
Forge: 40.1.68
MC: 1.18.2

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

No crash

**Comment by Technici4n** [comment]
That's really strange, I just tested and I am able to change the config to a 5.0 multiplier without it reverting. I didn't set a custom fluid tag however. Not sure what could be going wrong.

**Comment by Technici4n** [comment]
I tried again with a production server and I can't reproduce this issue.
