### ISSUE TITLE
Improve Mod Compat for ModelsReloadMixin Hook

### ISSUE THREAD

**Issue by shartte** [AppliedEnergistics/Applied-Energistics-2#6464]
Some mods may call `ModelBakery#getBakedTopLevelModels`, which triggers our post-processing of the baked model map every time the getter is called.

Vanilla calls this method only once, after all models have been baked, from `net.minecraft.client.resources.model.ModelManager#apply`. The hook should be moved into that function after the call to the getter.

For reports of incompatibility, see #6462.

**Comment by jeebscrusts** [comment]
hi there, this seems not to work for my server with my modlist. any possibility you would know what this crashlog means? im not really used to reading java/minecraft crashlogs.

thanks for any help you can provide
[crash-2022-07-30_18.37.56-server (1).txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/9227109/crash-2022-07-30_18.37.56-server.1.txt)
.

**Comment by Mari023** [comment]
> hi there, this seems not to work for my server with my modlist. any possibility you would know what this crashlog means? im not really used to reading java/minecraft crashlogs.
> 
> thanks for any help you can provide [crash-2022-07-30_18.37.56-server (1).txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/9227109/crash-2022-07-30_18.37.56-server.1.txt) .

the crashlog has nothing to do with this issue
the issue you have is with collective-fabric, removing that collective-fabric should fix it

**Comment by jeebscrusts** [comment]
the crashlog must have something to do with the issue, given when i install this to the server it doesnt want to start.
removing collective-fabric will only make a few mods incompatible it seems.

are you saying that this version of ae2 is just not compatible with collective-fabric?
