### ISSUE TITLE
Cannot right click blocks while holding a facade

### ISSUE THREAD

**Issue by ChiefArug** [AppliedEnergistics/Applied-Energistics-2#6474]
### Describe the bug

When you hold a facade you cannot right click on blocks at all.
This differs from all other multipart pieces.

### How to reproduce the bug

Hold a facade. Try right click a chest, button, barrel ect

### Expected behavior

To be able to right click blocks while holding it.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/ChiefArug/8f49cb57830e0749bf2a28b0f011e39e#file-crash-report-txt

**Comment by Technici4n** [comment]
That's intended.

**Comment by ChiefArug** [comment]
Why...?
I don't see how that could be intended, if you are right clicking a block with an item and the item cannot interact with the block then it should let you interact with the block normally.

**Comment by Technici4n** [comment]
It makes it easier to place facades on many parts at once.

**Comment by ChiefArug** [comment]
But the facade cannot be placed there (there is no cable bus for it to attach to), so why is it still blocking the interaction if it can confirm that it cannot be placed?

**Comment by Technici4n** [comment]
Consider this a feature. :P

**Comment by Technici4n** [comment]
One could argue that the current behavior is good or bad depending on the circumstances and what one would expect, but nonetheless it was meant to be this way when the part placement logic was refactored a few months ago, and I don't want to change it atm.
