### ISSUE TITLE
[12.0.2-alpha] Annihilation plane

### ISSUE THREAD

**Issue by rootwalla** [AppliedEnergistics/Applied-Energistics-2#6477]
### Describe the bug

The annihilation plane cannot differentiate between ae2:quartz_block and ae2:flawed_budding_quartz.

### How to reproduce the bug

Place an annihilation plate and a storage bus and connect them, add an ae2:quartz_block to the storage bus, and place a ae2:flawed_budding_quartz next to the annihilation plane.

### Expected behavior

The flawed quartz remains until it's downgraded to Certus quartz block.

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/N9tnrz6S

**Comment by Technici4n** [comment]
That's normal since the filtering happens with the drops. You can enchant it with silk touch to alter the drops hence the filtering.

**Comment by rootwalla** [comment]
So if I enchant the plane with silk, it will differentiate a flawed/chipped/damaged from plain?

**Comment by rootwalla** [comment]
Thanks, seems that was the trick.
