### ISSUE TITLE
Compass not craftable

### ISSUE THREAD

**Issue by cyrok** [AppliedEnergistics/Applied-Energistics-2#6481]
### Describe the bug

Sky Compass not craftable in latest release with forge 41.1.0 on 1.19
doesnt even show up in jei as craftable

### How to reproduce the bug

-

### Expected behavior

-

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

-

**Comment by 62832** [comment]
The compass recipe was changed in 1.19 such that you now have to place a vanilla compass into the Charger.

**Comment by cyrok** [comment]
thanks
