### ISSUE TITLE
Inscriber not working with importer

### ISSUE THREAD

**Issue by cyrok** [AppliedEnergistics/Applied-Energistics-2#6482]
### Describe the bug

inscriber not importing to me system while inscribing silicon.
doesnt matter wich side, each one the same.
Forge 41.1.0

### How to reproduce the bug

use import bus on inscriber

### Expected behavior

silicon beeing importet into me system trough importer from inscriber

### Additional details

not tested with other recepies

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

-

**Comment by Technici4n** [comment]
Works fine for me.
