### ISSUE TITLE
opening an ofline interface

### ISSUE THREAD

**Issue by phorced** [AppliedEnergistics/Applied-Energistics-2#6484]
### Describe the bug

i opened an interface that was offline it had a barrel on the east interface on the west and a mekanism smelter above and crashed don't have a crash report cause i closed it using task manager but it has happened twice with the same result 

### How to reproduce the bug

 interface with north air south air east another interface west a minecraft barrel top a mekanism smelter and bottom air it was offline and above the smelter there was a crafter that was also offline (there were 4 interfaces to the east it was at the end)

### Expected behavior

freeze and no response i had a blue screen after first encounter and closed with task manager

### Additional details

minecraft 1.18.2 forge 40.1.68 ae2 2-11.1.5

last known info after crash is.
[16:46:13] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 3309ms or 66 ticks behind

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

[16:41:18] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2608ms or 52 ticks behind [16:46:13] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 3309ms or 66 ticks behind

**Comment by Technici4n** [comment]
Please provide the crash log. If you can't reproduce it yourself there is no way we will be able to.

**Comment by phorced** [comment]
going to try now again

**Comment by phorced** [comment]
had to roll back the world is now not happening again if it happens again i will try my out most to get a crash report
