### ISSUE TITLE
No Certus ore after version? 1.18.1

### ISSUE THREAD

**Issue by Ralvor** [AppliedEnergistics/Applied-Energistics-2#6486]
### Describe the bug

Hey guys 
i hope its nothing new.
I m playing minecraft 1.19 java on fabric with the mod appliedenergistics2-12.0.2-alpha and yeah i have tried the newest version same issu its the same problem. there are no Certus Quartz and yeah i have tried to gen. a new world same problem.
hm... i have tried downgrade minecraft till 1.18.1 and see there no problem with the mod appliedenergistics2-10.0.0
hope it,s help.
Same problem with the produktion with the seed if you trow certus quartz dust with sand in the water nothing happens, after a wile they only despawn...
i have saw in the creative mode that there arent certus seeds and Certus mining ore is missing to.
hope it cant be fixed. thanks and sry for the broken english.

### How to reproduce the bug

Install the mod?
appliedenergistics2-12.0.2-alpha

### Expected behavior

the world gen. generate Certus ore? =)
ant it works with the seed produktion in water.

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Fabric

### Crash log

no crash happens

**Comment by Mari023** [comment]
There is indeed no certus quartz ore in See 12.x.x. this is intended, See #6380

**Comment by Ralvor** [comment]
urg have missed this one thanks=)
the tutorial sould be updatet 
https://appliedenergistics.github.io/features/crystals
