### ISSUE TITLE
Facade does not have texture or craft.

### ISSUE THREAD

**Issue by timo1050** [AppliedEnergistics/Applied-Energistics-2#6488]
### Describe the bug

Playing on custom modpack.
We can't craft facade, this one appear without texture in JEI (Here i'm using REI but the same thing happens with JEI).
Once place it, the game crash.

### How to reproduce the bug

![2022-08-15_12 14 48](https://user-images.githubusercontent.com/8901731/184618400-146af87f-55af-4436-9b54-273ee1d70d8d.png)
![2022-08-15_12 15 00](https://user-images.githubusercontent.com/8901731/184618417-52f6fe22-821e-4e6b-a211-82fba919a884.png)
Just take a facade via JEI (or REI) and place it on a cable.

### Expected behavior

Would like to have the craft and the possibility of placing them without crashing.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/Sfd1CD9Y

**Comment by timo1050** [comment]
OK, i'm sorry.
After checking on the wiki, the recipes doesn't appear in JEI (or REI) but we can actually craft them.
I was used to see all type of in JEI in 1.16.5.

Resume : We can craft and use facade if we know the recipe.
I close Issues

**Comment by ryleu** [comment]
i think OP is saying that the different facade variations aren't showing in the REI menu, even though they can be crafted. i don't think this is a bug though
