### ISSUE TITLE
ranslation issue on PT-BR language, 256k ME cell shows as 16k instead

### ISSUE THREAD

**Issue by matpratta** [AppliedEnergistics/Applied-Energistics-2#6489]
### Describe the bug

In the Brazilian Portuguese translation the 256k storage component is displayed as 16k instead:
![183169349-522fbb29-5bb4-4adb-82d6-59dc94882c8b](https://user-images.githubusercontent.com/532195/184790055-7e91bf29-443e-4d05-aacb-cffb510d570d.png)

### How to reproduce the bug

1. Set game to Brazilian Portuguese (PT-BR)
2. Grab a 256k storage component
3. Name will say 16k instead

### Expected behavior

Name should show 256k instead of 16k

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

N/A

**Comment by istancescu** [comment]
Seems it happens to more than just BR Portuguese such as RO, JP (might be more)

**Comment by Technici4n** [comment]
I've been fighting crowdin for an hour and failed, that's why I assigned you. 😅

**Comment by Technici4n** [comment]
Fixed in recent releases.
