### ISSUE TITLE
AE2 ME quantum bug report

### ISSUE THREAD

**Issue by Henryxiangxiang** [AppliedEnergistics/Applied-Energistics-2#6492]
### Describe the bug

If we use the creative energy cell and energy cell with the quantum linker, we can't read the items in ME.

### How to reproduce the bug

1. Build a quantum linker with a creative energy cell.
2. Disconnect it.
3. Reconnect it with the energy cell.
4. The bug happened.

### Expected behavior

Steel can use the quantum link to read the items.

### Additional details

After we reset the ME controller, the bug will be fixed temporarily.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

NO crash

**Comment by Technici4n** [comment]
As far as I can tell, this is the same issue as #6432 with different symptoms. I'm working on a fix.
