### ISSUE TITLE
Crash on 1.12.2 Start up

### ISSUE THREAD

**Issue by LaserGamer90** [AppliedEnergistics/Applied-Energistics-2#6494]
### Describe the bug

Whenever I try to start the game with mods it gets to stage 4 and stops at the mod and them crashes

### How to reproduce the bug

im not sure how to recreate this but i think it might be incompatible with some of the mods i have installed

first screenshot of the mods: ![screenshot bug report](https://user-images.githubusercontent.com/111683652/185787240-a597b62f-9fd9-4d3a-840d-0a8dfb11e351.png)
 
Second: ![screenshot bug report 2](https://user-images.githubusercontent.com/111683652/185787275-9a9493ac-534d-4da4-a1aa-d1e8a111109e.png)

### Expected behavior

Crash on start up with some mods

### Additional details

I've tryed to load the mod by its self and it works

### Which minecraft version are you using?

1.12 - UNSUPPORTED

### On which mod loaders does it happen?

Forge

### Crash log

---- Minecraft Crash Report ----  WARNING: coremods are present:   ForgelinPlugin (Forgelin-1.8.3.jar)   Techguns Core (techguns-1.12.2-2.0.2.0_pre3.2.jar)   XaeroWorldMapPlugin (XaerosWorldMap_1.24.0_Forge_1.12.jar)   FutureMC (future-mc-0.2.10.1.jar)   SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.4.1.jar)   TransformLoader (DynamicSurroundings-1.12.2-3.6.3.jar)   FMLModule (mdxlib-3.0.0.26.jar)   XaeroMinimapPlugin (Xaeros_Minimap_22.10.0_Forge_1.12.jar) Contact their authors BEFORE contacting forge  // This doesn't make any sense!  Time: 8/21/22 11:25 AM Description: There was a severe problem during mod loading that has caused the game to fail  net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Energistics 2 (appliedenergistics2) Caused by: java.lang.IllegalArgumentException: Failed to register dimension for id 2, One is already registered 	at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:134) 	at appeng.core.Registration.registerSpatialDimension(Registration.java:201) 	at appeng.core.Registration.postInit(Registration.java:352) 	at appeng.core.AppEng.postInit(AppEng.java:235) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:497) 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) 	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:497) 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) 	at com.google.common.eventbus.EventBus.post(EventBus.java:217) 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:497) 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) 	at com.google.common.eventbus.EventBus.post(EventBus.java:217) 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754) 	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336) 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535) 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) 	at net.minecraft.client.main.Main.main(SourceFile:123) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:497) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- System Details -- Details: 	Minecraft Version: 1.12.2 	Operating System: Windows 10 (amd64) version 10.0 	Java Version: 1.8.0_51, Oracle Corporation 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation 	Memory: 606859608 bytes (578 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB) 	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M 	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0 	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 46 mods loaded, 46 mods active 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored  	| State | ID                  | Version           | Source                                        | Signature                                | 	|:----- |:------------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- | 	| LCHIJ | minecraft           | 1.12.2            | minecraft.jar                                 | None                                     | 	| LCHIJ | mcp                 | 9.42              | minecraft.jar                                 | None                                     | 	| LCHIJ | FML                 | 8.0.99.99         | forge-1.12.2-14.23.5.2860.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 | 	| LCHIJ | forge               | 14.23.5.2860      | forge-1.12.2-14.23.5.2860.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 | 	| LCHIJ | xaerominimap_core   | 1.12.2-1.0        | minecraft.jar                                 | None                                     | 	| LCHIJ | xaeroworldmap_core  | 1.12.2-1.0        | minecraft.jar                                 | None                                     | 	| LCHIJ | techguns_core       | 1.12.2-1.0        | minecraft.jar                                 | None                                     | 	| LCHIJ | mdxlib              | 3.0.0.26          | mdxlib-3.0.0.26.jar                           | None                                     | 	| LCHIJ | avp                 | 6.0.0.63          | aliensvspredator-6.0.0.63.jar                 | None                                     | 	| LCHIE | appliedenergistics2 | rv6-stable-7      | appliedenergistics2-rv6-stable-7.jar          | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 | 	| LCHI  | bettercaves         | 1.12.2            | bettercaves-1.12.2-2.0.4.jar                  | None                                     | 	| LCHI  | biomesoplenty       | 7.0.1.2445        | BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar | None                                     | 	| LCHI  | buildcraftlib       | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     | 	| LCHI  | buildcraftcore      | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     | 	| LCHI  | buildcraftbuilders  | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     | 	| LCHI  | buildcrafttransport | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     | 	| LCHI  | buildcraftsilicon   | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     | 	| LCHI  | buildcraftcompat    | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     | 	| LCHI  | buildcraftenergy    | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     | 	| LCHI  | buildcraftfactory   | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     | 	| LCHI  | buildcraftrobotics  | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     | 	| LCHI  | extendedrenderer    | v1.0              | coroutil-1.12.1-1.2.37.jar                    | None                                     | 	| LCHI  | coroutil            | 1.12.1-1.2.37     | coroutil-1.12.1-1.2.37.jar                    | None                                     | 	| LCHI  | configmod           | v1.0              | coroutil-1.12.1-1.2.37.jar                    | None                                     | 	| LCHI  | orelib              | 3.6.0.1           | OreLib-1.12.2-3.6.0.1.jar                     | 7a2128d395ad96ceb9d9030fbd41d035b435753a | 	| LCHI  | dsurround           | @VERSION@         | DynamicSurroundings-1.12.2-3.6.3.jar          | None                                     | 	| LCHI  | jei                 | 4.16.1.302        | jei_1.12.2-4.16.1.302.jar                     | None                                     | 	| LCHI  | mantle              | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                      | None                                     | 	| LCHI  | tconstruct          | 1.12.2-2.13.0.183 | TConstruct-1.12.2-2.13.0.183.jar              | None                                     | 	| LCHI  | extrautils2         | 1.0               | extrautils2-1.12-1.9.9.jar                    | None                                     | 	| LCHI  | forgelin            | 1.8.3             | Forgelin-1.8.3.jar                            | None                                     | 	| LCHI  | futuremc            | 0.2.6             | future-mc-0.2.10.1.jar                        | None                                     | 	| LCHI  | gravestone          | 1.10.3            | gravestone-1.10.3.jar                         | None                                     | 	| LCHI  | waila               | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     | 	| LCHI  | ironchest           | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.72.847.jar               | None                                     | 	| LCHI  | ironfurnaces        | 1.3.5             | ironfurnaces-1.3.5.jar                        | None                                     | 	| LCHI  | scp                 | $$version         | SCP_Lockdown-1.12.2-2.4.1-release.jar         | None                                     | 	| LCHI  | spartanshields      | 1.5.5             | SpartanShields-1.12.2-1.5.5.jar               | None                                     | 	| LCHI  | spartanweaponry     | 1.4.1             | SpartanWeaponry-1.12.2-1.4.1.jar              | None                                     | 	| LCHI  | spiderstpo          | 1.0.3             | spiders-2.0-1.12.2-1.0.3.jar                  | None                                     | 	| LCHI  | techguns            | 2.0.2.0           | techguns-1.12.2-2.0.2.0_pre3.2.jar            | None                                     | 	| LCHI  | waystones           | 4.1.0             | Waystones_1.12.2-4.1.0.jar                    | None                                     | 	| LCHI  | weather2            | 1.12.1-2.6.12     | weather2-1.12.1-2.6.12.jar                    | None                                     | 	| LCHI  | xaerominimap        | 22.10.0           | Xaeros_Minimap_22.10.0_Forge_1.12.jar         | None                                     | 	| LCHI  | xaeroworldmap       | 1.24.0            | XaerosWorldMap_1.24.0_Forge_1.12.jar          | None                                     | 	| LCHI  | betteranimalsplus   | 9.0.1             | betteranimalsplus-1.12.2-9.0.1.jar            | None                                     |  	Loaded coremods (and transformers):  ForgelinPlugin (Forgelin-1.8.3.jar)    Techguns Core (techguns-1.12.2-2.0.2.0_pre3.2.jar)   techguns.core.TechgunsASMTransformer XaeroWorldMapPlugin (XaerosWorldMap_1.24.0_Forge_1.12.jar)   xaero.map.core.transformer.ChunkTransformer   xaero.map.core.transformer.NetHandlerPlayClientTransformer   xaero.map.core.transformer.EntityPlayerTransformer   xaero.map.core.transformer.AbstractClientPlayerTransformer   xaero.map.core.transformer.WorldClientTransformer   xaero.map.core.transformer.PlayerListTransformer   xaero.map.core.transformer.SaveFormatTransformer   xaero.map.core.transformer.BiomeColorHelperTransformer FutureMC (future-mc-0.2.10.1.jar)   thedarkcolour.futuremc.asm.CoreTransformer SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.4.1.jar)    TransformLoader (DynamicSurroundings-1.12.2-3.6.3.jar)    FMLModule (mdxlib-3.0.0.26.jar)   com.asx.mdx.AccessTransformer XaeroMinimapPlugin (Xaeros_Minimap_22.10.0_Forge_1.12.jar)   xaero.common.core.transformer.ChunkTransformer   xaero.common.core.transformer.NetHandlerPlayClientTransformer   xaero.common.core.transformer.EntityPlayerTransformer   xaero.common.core.transformer.AbstractClientPlayerTransformer   xaero.common.core.transformer.WorldClientTransformer   xaero.common.core.transformer.EntityPlayerSPTransformer   xaero.common.core.transformer.PlayerListTransformer   xaero.common.core.transformer.SaveFormatTransformer   xaero.common.core.transformer.GuiIngameForgeTransformer   xaero.common.core.transformer.GuiBossOverlayTransformer   xaero.common.core.transformer.ModelRendererTransformer 	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 27.20.100.8984' Renderer: 'Intel(R) UHD Graphics' 	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768 	Pulsar/tconstruct loaded Pulses:  		- TinkerCommons (Enabled/Forced) 		- TinkerWorld (Enabled/Not Forced) 		- TinkerTools (Enabled/Not Forced) 		- TinkerHarvestTools (Enabled/Forced) 		- TinkerMeleeWeapons (Enabled/Forced) 		- TinkerRangedWeapons (Enabled/Forced) 		- TinkerModifiers (Enabled/Forced) 		- TinkerSmeltery (Enabled/Not Forced) 		- TinkerGadgets (Enabled/Not Forced) 		- TinkerOredict (Enabled/Forced) 		- TinkerIntegration (Enabled/Forced) 		- TinkerFluids (Enabled/Forced) 		- TinkerMaterials (Enabled/Forced) 		- TinkerModelRegister (Enabled/Forced) 		- wailaIntegration (Enabled/Not Forced)  	OptiFine Version: OptiFine_1.12.2_HD_U_G5 	OptiFine Build: 20210124-142939 	Render Distance Chunks: 8 	Mipmaps: 4 	Anisotropic Filtering: 1 	Antialiasing: 0 	Multitexture: false 	Shaders: null 	OpenGlVersion: 4.6.0 - Build 27.20.100.8984 	OpenGlRenderer: Intel(R) UHD Graphics 	OpenGlVendor: Intel 	CpuCount: 4

**Comment by Technici4n** [comment]
We don't support 1.12 anymore.

**Comment by LaserGamer90** [comment]
:(

**Comment by mindforger** [comment]
>Caught exception from Applied Energistics 2 (appliedenergistics2) Caused by: java.lang.IllegalArgumentException: **### Failed to register dimension for id 2, One is already registered**

please upload crashlogs always to pastebin or similar paste sites .. makes them WAY easier to read ...
