### ISSUE TITLE
Tag for export bus.

### ISSUE THREAD

**Issue by Rusketh** [AppliedEnergistics/Applied-Energistics-2#650]
I have a neat suggestion for export buses. If you could name them from there configuration menu you could add the ability to export items to it remotely via a terminal.. I see the potential use of this to add the ability to export to a trash can or export to your ore processing remotely.

**Comment by yueh** [comment]
I remember a similar suggestion about something like an Interface Terminal for buses.
But I think @AlgorithmX2 did reject it.

**Comment by thatsIch** [comment]
Remember reason?

**Comment by yueh** [comment]
I seem to remember something about being able to remotely add an ore to an export bus and so circumvent the autocrafting.
