### ISSUE TITLE
1.19.2 server crash at launch

### ISSUE THREAD

**Issue by Daltaxy** [AppliedEnergistics/Applied-Energistics-2#6504]
### Describe the bug

Hello. I come from https://github.com/badasintended/wthit/issues/161. I initially thought this was a WTHIT issue, but the owner redirected me here.
debug.log : https://gist.githubusercontent.com/Daltaxy/46a7cc23177b64a951b88467aa068ffb/raw/71a01bb109248fd4e744635c826826e02f71ab28/debug.log
crash report : https://gist.github.com/Daltaxy/042880ffe8c273d3e2919425852eafda#file-crash-2022-08-24_14-59-15-fml-txt

### How to reproduce the bug

Launch the server (hosted on my computer) with the mod installed

### Expected behavior

normal startup. Additionally, this doesn't really crash the server, it looks like it prevents the server from continuing to start.

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.githubusercontent.com/Daltaxy/46a7cc23177b64a951b88467aa068ffb/raw/71a01bb109248fd4e744635c826826e02f71ab28/debug.log

**Comment by Technici4n** [comment]
Looks like a forge issue... https://github.com/McModLauncher/modlauncher/issues/100

**Comment by Daltaxy** [comment]
> Looks like a forge issue... [McModLauncher/modlauncher#100](https://github.com/McModLauncher/modlauncher/issues/100)

what do I do then ? It genuinely seems like I am the only one affected by the issue ?

**Comment by Technici4n** [comment]
Can't reproduce in dev. Will try on a dedicated server.

**Comment by Technici4n** [comment]
Can't reproduce with the following mod sets, using the latest forge server installer (43.1.3):
![image](https://user-images.githubusercontent.com/13494793/187045816-764d60a6-b252-481d-9cde-148229e7e399.png)

It has to be an issue with your Forge install or with another mod.
