### ISSUE TITLE
not really a bug just need some help with te dimension id i know the version is unspported but im adding a mod that does not add a config option folder and ae2 does not let the game load because of the same dimension id

### ISSUE THREAD

**Issue by DragonWolf1619** [AppliedEnergistics/Applied-Energistics-2#6507]
### Describe the bug

i have been working with the aether creaters on my problem but the problem has changed to ae2 1.12.2 the aether 1 and the abyss 1 both use dimension id 4 but abyss has no config so I changed aether to 10 but abyss also has a dimension id 2 or does not work with ae2 1.12.2 can you plz tell me if they are compatible or what i can change ae2 dimension to so it works can you plz tell me the lowest and highest dimension id it can be if the mods are compatible 

### How to reproduce the bug

the easiest ways you can have the bug reproduce the problem is to
1. download my modpack on curseforge and add the abyss legacy link https://www.curseforge.com/minecraft/modpacks/death-smp
or
2. have the abyss legacy 1.12.2 most resent version and ae2 1.12.2 most resent version installed and load them 

### Expected behavior

after I added the abyss legacy game crashes and the aether legacy was the problem so I changed the aether legacy to dimension id 10 from 4 and the problem changed to ae2

### Additional details

if i have to respond i am going out soon and can not respond thanks for the help

### Which minecraft version are you using?

1.12 - UNSUPPORTED

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/DragonWolf1619/eb1e9fec1c4c04597ab1f37330b6a81a

**Comment by DragonWolf1619** [comment]
i removed the confige for ae2 and the dimension id was redone as 4 is that normal

**Comment by mindforger** [comment]
just use any number that works(i dont know the exact limit for 1.12 but taking a minimal aproach would be something between -128 and 127), you could use TellMe mod to dump all your dimension ids, but this requires the game to launch first :P

**Comment by Technici4n** [comment]
Unsupported means unsupported.
