### ISSUE TITLE
Pattern Encode || Wrapped Generic Stack

### ISSUE THREAD

**Issue by Tuho89** [AppliedEnergistics/Applied-Energistics-2#6508]
### Describe the bug

When Using JEI in combination with AE2 - ME Pattern Encoding Terminal. 
A dummy place holder appears in the pattern.
This place holder is invisible unless you mouse-over the pattern slots.

### How to reproduce the bug

Steps to reproduce:

1. Access 'Me Pattern Encoding Terminal'
![image](https://user-images.githubusercontent.com/78901454/186976578-0732cba8-33bd-40c4-ba26-cd9ff6f0347f.png)

3. Select an item in JEI to use for encoding ( In this Case Raw Gold)
5. Select the + symbol to insert the recipe in to 'ME Pattern Encoding Terminal'
![image](https://user-images.githubusercontent.com/78901454/186976715-82003715-e551-4162-9b48-6d6ce3baa378.png)

7. Mouse over the pattern slots.
![image](https://user-images.githubusercontent.com/78901454/186976768-b08f6aa0-1f0f-4f80-9023-524d72235e44.png)

### Expected behavior

The Dummy Place Holder should not pop in to the pattern. 

### Additional details

Back in 24 Sep 2021 this ticket was made:
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/5447

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/Zg8f7zAp

**Comment by Technici4n** [comment]
As discussed on Discord, this is caused by installing Applied Mekanistics on the client but not on the server.
