### ISSUE TITLE
Energy Acceptor not receiving power via RotaryCraft shaft junction

### ISSUE THREAD

**Issue by jkehler** [AppliedEnergistics/Applied-Energistics-2#651]
I am using the Energy Acceptor to convert power from RotaryCraft Hydrokinetic engines. The energy acceptor works fine when connected directly but when I use a shaft junction to split the shaft power 1:1 even then the Energy Acceptor no longer receives power via the shaft junction. Is this a bug of some sort?

**Comment by ReikaKalseki** [comment]
@thatsIch, @yueh

I just refactored the RC api. You are going to want to update.
