### ISSUE TITLE
Duplication bug while autocrafting with reusable items

### ISSUE THREAD

**Issue by Sakreton** [AppliedEnergistics/Applied-Energistics-2#6510]
### Describe the bug

To explain what i mean with reusable items: infusion crystals (Mystical agriculture) or Philiosopher stone (Project E).
In my scenario it only occurred when these items had no durability loss when crafting.

When autocrafting with these items i generally had no problem, it worked. But once you start a second job you start to dupe these items.

This runs on a server if it matters
For the record i only have a single pattern provider with 4 max speed molecular assembler connected.

### How to reproduce the bug

Add e.g. Prudention Essence to your autocrafting setup and run two jobs at the same time.

### Expected behavior

Do not duplicate the items xD

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/Sakreton/c5d7f1c4978274217b22f000e467e09c

**Comment by Technici4n** [comment]
Reproduced... WTF 😄
