### ISSUE TITLE
AE2 Crafting bug/Crash

### ISSUE THREAD

**Issue by Trist2000** [AppliedEnergistics/Applied-Energistics-2#6524]
### Describe the bug

When using AE2 Crafting Monitor to bulk craft anything, i.e. holding shift +clicking, dedicated server crashes.

### How to reproduce the bug

Craft ANY blocks in the AE2 Portable Crafting monitor in mass, i.e. use shift click to craft multiple blocks at once.

### Expected behavior

Server kicks players and ram cycles into high/low states until someone attempts to rejoin then it crashes.

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/F9fYDCM8

**Comment by Trist2000** [comment]
I am attempting to get a spark report but as soon as I mass craft any block from the remote crafting terminal the server hangs up and does not accept any commands to get the profiler to upload any results.

**Comment by mindforger** [comment]
you could try to reduce the amount until it does not crash, since this crash is a timeout crash you just have to wait 1 minute and hope it survives and then upload the profile

**Comment by Trist2000** [comment]
I have tried multiple times just taking 4 wood (2 in crafting area for pressure plate, 2 in me system) and when i shift click the craft to grab multiples it kicks me, then server hangs with the high/low ram usage for a while then just crashes.

**Comment by Technici4n** [comment]
Could you maybe use another profiling method then? (VisualVM or JFR for example)

**Comment by Trist2000** [comment]
https://spark.lucko.me/YUxAIe6QyB    finally got the spark to work durring a mass crafting

**Comment by Technici4n** [comment]
Hi, thanks a lot, that's very insightful. This should already be addressed by #6514. Can you update to AE2 version 12.2.0 and check whether the issue still occurs ? Thank you.

**Comment by Trist2000** [comment]
Ok, https://spark.lucko.me/bVnBRAnSJd     I have updated both ae2 and jei to the latest's and it is alot better. Still a small stutter but nothing like it was! G/j :)

**Comment by Trist2000** [comment]
Further testing with different items, First was turning hay bales into wheat, this one is turning wheat into hay bales, https://spark.lucko.me/mtsYrU7efY. The first was quick, second not so much, will test with different items and see if there is any that causes a large lag like before.

**Comment by Trist2000** [comment]
https://spark.lucko.me/RabOrKq5r8 ok, all in all its livable now. only slight lagging so not too bad, could be from the i7 computing and not a server, but its alot better all in all. Let me know if ya need any more diagnostics or anything.

**Comment by Technici4n** [comment]
May I ask how many kinds of items are in your network? It looks like you have a **colossal** amount of stored items.

**Comment by Trist2000** [comment]
![image](https://user-images.githubusercontent.com/112557254/188493483-570583d3-0942-475e-ac7c-57e7c8820b9d.png)
![image](https://user-images.githubusercontent.com/112557254/188493523-09a2b22b-d17d-49e8-9cf6-3a3e1918b3a5.png)
![image](https://user-images.githubusercontent.com/112557254/188493573-b7207ba1-0cec-4d3b-b3b6-907615644ccf.png)
![image](https://user-images.githubusercontent.com/112557254/188493612-8939700a-65f8-462b-a68a-498b22a762a7.png)
![image](https://user-images.githubusercontent.com/112557254/188493728-ddd3a447-c806-4936-91a6-614fa3f8f997.png)
![image](https://user-images.githubusercontent.com/112557254/188493793-ba7a3ee1-a666-440f-aca9-78f5a60a6892.png)
That is everything in it. Only thing ive got alot of is the Inferium Essence, and Prosperity Shards from Mystical agriculture. So unsure if this would be the cause of such an issue. I feel like iv had me systems in the past with a LOT more than this.

**Comment by Technici4n** [comment]
That's indeed not that much, we will investigate. Thanks!

**Comment by Trist2000** [comment]
Sounds good, also not sure if its an conflict issue with the mod biggerstacks-1.19-1.1  could be causing issues converting data from one type to another as far as how stack size is handled? but your welcome! thx for doin what ya do!

**Comment by Technici4n** [comment]
Not really, it's more of a performance issue with the data structure we use to represent stacks in the ME network as far as I can tell (nested hashmap).
