### ISSUE TITLE
Certus Quartz Ore Generation Forge 12.1.12-Beta

### ISSUE THREAD

**Issue by cjm7603** [AppliedEnergistics/Applied-Energistics-2#6525]
### Describe the bug

Certus Quartz ore does not generate in overworld. JEI does not indicate presence of ores at all.

### How to reproduce the bug

Installed Mods:

AE2 12.1.2-BETA
JEI 1.19.2-forge-11.2.0.256

All dependencies as well.

### Expected behavior

Certus Quartz ore should be a commonly generated ore.

### Additional details

Not sure if it isn't generating at all entirely. Looked through some caves but saw nothing, as well as JEI UI.

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/nLt739rg

**Comment by Sea-Kerman** [comment]
not a bug https://modrinth.com/mod/ae2/version/fabric-12.0.0-alpha

**Comment by cjm7603** [comment]
Ah I see, hadn't found that article I had just looked on the wiki.
