### ISSUE TITLE
`CraftingRecipeUtil#ensure3by3CraftingMatrix` should use `IShapedRecipe` on Forge

### ISSUE THREAD

**Issue by Technici4n** [AppliedEnergistics/Applied-Energistics-2#6536]
Otherwise weird stuff happens with IC2C according to @Speiger. :smile:

**Comment by Speiger** [comment]
Any mod that has custom recipe classes that don't extend ShapedRecipe and do their own stuff.
(Like IC2 Exp will have the same issue XD)

**Comment by Technici4n** [comment]
Fixed by 0bd2027dcbcdce10a91e7ed957e7048e30a18bb2
