### ISSUE TITLE
Change how presses are obtained in meteorites

### ISSUE THREAD

**Issue by Technici4n** [AppliedEnergistics/Applied-Energistics-2#6537]
Hunting for the 4 press types can be annoying. Soaryn suggests that we could instead have an "Alien Knowledge Fragment" (or other name) that can be found in meteorites, and which can be used to craft the 4 types of presses.

So the process would be:
1. Find meteorite, guaranteed to have a knowledge fragment.
2. Use the knowledge fragment to craft the 4 presses. Example recipe: `knowledge fragment (not consumed) + gold ingot -> logic press`.

The villager recipe for presses would not change.

Thoughts?

**Comment by Sea-Kerman** [comment]
Seems like a decent idea. Perhaps it's a cube (or, actually, 4 presses -> 4 sides, tetrahedron. ooh, spooky alien) that you stick in an inscriber and can use similarly to the press cloning recipes.

**Comment by Technici4n** [comment]
The idea is that with this concept you'd only need to find one meteorite in total which makes things easier on servers.
The advancements also have the issue that they don't work very nicely when multiple players are exploring at the same time.

It's just an idea, we don't necessarily have to do it. ;)

**Comment by DAmNRelentless** [comment]
I'd prefer another approach too. Especially on servers, it can be pretty annoying to find the 4 presses. A lot of server admins don't pre-gen their world and if several players hunt meteorites, it is also quite laggy. The stress on the server could be significantly lowered by a new mechanic.

**Comment by mrgreaper** [comment]
plus one for anything other than having to hunt multiple meteors. Its just not a fun activity, and as others have pointed out, its not good for servers.
