### ISSUE TITLE
Crash on Startup Rendering Overlay

### ISSUE THREAD

**Issue by minecraftchest1** [AppliedEnergistics/Applied-Energistics-2#6539]
### Describe the bug

Using [Forge Latest (1.19.2 - 43.1.25)](https://maven.minecraftforge.net/net/minecraftforge/forge/1.19.2-43.1.25/forge-1.19.2-43.1.25-installer.jar) and [12.2.0-beta for Forge on Minecraft 1.19.2](https://github.com/AppliedEnergistics/Applied-Energistics-2/releases/tag/forge%2Fv12.2.0-beta) with [OptiFine 1.19.2 HD U H9](https://optifine.net/adloadx?f=OptiFine_1.19.2_HD_U_H9.jar&x=c316) causes a crash on startup. Using AE2 and Optifine individually does not cause an error.

### How to reproduce the bug

AE2 jar: [appliedenergistics2-12.2.0-beta.jar.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/9538853/appliedenergistics2-12.2.0-beta.jar.zip)
Optifine jar: [Optifine-1.19.2.jar.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/9538855/Optifine-1.19.2.jar.zip)
Forge jar:  [Forge-1.19.2.jar.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/9538857/Forge-1.19.2.jar.zip)

Use the jar files above and Launch Minecraft with only the mods above installed.

### Expected behavior

Minecraft should load the main menu.

### Additional details

Error message:
```
The game crashed whilst rendering overlay
Error: java.lang.NoSuchMethodError: 'void net.minecraft.client.renderer.block.model.BakedQuad.<init>(int[], int, net.minecraft.core.Direction, net.minecraft.client.renderer.texture.TextureAtlasSprite, boolean, boolean)'
```
OS: Archlinux

```
$ cat /etc/*release
DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux-logo
```

Minecraft Launcher Version: v.2.3.394-1.1.28
Java version: Bundled JVM runtime, as well as java-17-openjdk
Game Directory: Default
JVM Arguments: `-Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M`

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

https://gitlab.com/-/snippets/2406147

**Comment by Technici4n** [comment]
That looks like Optifine messing with one of the Forge rendering hooks that we use, report it to Optifine.

**Comment by minecraftchest1** [comment]
Will do.
