### ISSUE TITLE
Substitution not working

### ISSUE THREAD

**Issue by jarquafelmu** [AppliedEnergistics/Applied-Energistics-2#6541]
### Describe the bug

I have recipes with Substitution turned on but it doesn't properly sub the ingredients.

So the problem is that the ME system is looking for Mekanism Bronze when it already knows how to craft Thermal Series Bronze.

If I deliberately change the recipe to use Thermal Series Bronze then it is happy. 

### How to reproduce the bug

1. Get the same ingot from two different mods
2. Create a recipe that uses one of those kinds
3. Only have the other kind of ingot in your system
4. System says it can't craft what it needs.

### Expected behavior

It shouldn't care what mod the bronze is from.

### Additional details

![image](https://user-images.githubusercontent.com/5807272/189501870-1485d220-6456-4a08-8173-0979e374289b.png)
![image](https://user-images.githubusercontent.com/5807272/189501899-afd5dc3c-f3a7-4dc7-9ad6-90862870fa63.png)
![image](https://user-images.githubusercontent.com/5807272/189501903-0a9c647d-f6ed-45f2-868b-554eb8dbe809.png)
![image](https://user-images.githubusercontent.com/5807272/189501998-b0051d5f-cc84-4061-98f9-26e9e8a7e8eb.png)

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/jarquafelmu/6c158a0cbb5922fae3ff02ddac2a7f7f

**Comment by Technici4n** [comment]
Hi, please make sure that the gear recipe has substitutions turned on. Could you show a screenshot of that pattern encoding?

**Comment by jarquafelmu** [comment]
A screenshot of the encoded pattern was included with my initial post

**Comment by mindforger** [comment]
That was the ingot pattern you posted there, not the gear recipe

**Comment by Technici4n** [comment]
Substitution only works for items that you already have - but recursive autocrafting will only work if you have a pattern for the exact item that you encoded.
