### ISSUE TITLE
Certus Quartz Ore is Missing 

### ISSUE THREAD

**Issue by Morels31** [AppliedEnergistics/Applied-Energistics-2#6545]
I noticed that i wasn't finding any certus quartz ores while mining, and so with commands i started removing all common blocks (dirt, stone, deepslate etc..) in a chunk, and the result was that were left only the ores... 
And to my surprise there weren't any certus quatz ores!

So i tried going in creative mode, to try and find it with the search bar... and... Nothing.
I tried searching it with JEI... Nothing.
So i thought that some other mods might be in some sort of conflict, and so with the forge launcher, i created a custom profile with:
-minecraft 1.19.2
-forge 43.1.1
-ae2 12.3.0-beta
trying to isolate the problem... and... Nothing.

- Environment: 
[crash-2022-09-11_08.46.17-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/9541938/crash-2022-09-11_08.46.17-client.txt)

**Comment by Sarioah** [comment]
Intended for the most part, except for the crash: https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/6380

**Comment by Morels31** [comment]
> Intended for the most part, except for the crash: #6380

What do you mean? the mechanics have changed?

When i search with JEI how to make certus quarts, it gives me only one recipe where it needs charged certus quarts lol

**Comment by Sarioah** [comment]
> What do you mean? the mechanics have changed?
Yes, you don't go searching for ore, you instead make a compass via the charger, then go find meteors for your first certus.
From there it's grown using the new budding mechanics.

**Comment by Morels31** [comment]
> > What do you mean? the mechanics have changed?
> 
> Yes, you don't go searching for ore, you instead make a compass via the charger, then go find meteors for your first certus. From there it's grown using the new budding mechanics.

Thanks a lot!
Have a good day : )
