### ISSUE TITLE
Disappearing items.

### ISSUE THREAD

**Issue by csblizzard93** [AppliedEnergistics/Applied-Energistics-2#656]
i am playing single player and using the 1.7.10 rv0 version of ae2. i have my me system set up, i can put items in it but when i walk away and come back. i can't see anything in it. but when i check my drive it says it has items in it. and i check my system itself and its all linked together and using power.
![2014-12-29_13 24 56](https://cloud.githubusercontent.com/assets/9687621/5572016/221a82d6-8f5e-11e4-844f-81cf6e403992.png)
![2014-12-29_13 25 01](https://cloud.githubusercontent.com/assets/9687621/5572018/221f6c38-8f5e-11e4-879f-efe64d10bf43.png)
![2014-12-29_13 25 11](https://cloud.githubusercontent.com/assets/9687621/5572017/221b15d4-8f5e-11e4-9147-a79f3a74943b.png)
![2014-12-29_13 25 14](https://cloud.githubusercontent.com/assets/9687621/5572015/221a5cc0-8f5e-11e4-81bb-b95b83af7138.png)
![2014-12-29_13 26 28](https://cloud.githubusercontent.com/assets/9687621/5572026/3c8e668c-8f5e-11e4-95b3-0a8ea8f18da6.png)

**Comment by styopa1** [comment]
i use rv2 ver 10. my items disapear too...

**Comment by styopa1** [comment]
i guess problem hide in storage cells: when i remove all my old cells from drive, and paste new cell, item will store normally, any other manipulation with network before and multiple restarts does not effect
