### ISSUE TITLE
pattern encoding for machines that create items from nothing

### ISSUE THREAD

**Issue by TOLoneWolf** [AppliedEnergistics/Applied-Energistics-2#6560]
### Describe the feature

I would like the option to encode an empty input to a pattern with an output.
Reason for this is the machine it's connected to takes 0 input to create cobble in this example.

### Reasons why it should be considered

This would allow you to schedule a craft that relies on a resource that will become available over time on its own.

### Additional details

![image](https://user-images.githubusercontent.com/8376628/190034054-55516c44-b14f-4ee9-b95d-dd227315e608.png)

**Comment by Sea-Kerman** [comment]
If there’s no input what does the pattern provider send to start the craft

Besides, I’m pretty sure there’s a function in the level emitter to “emit redstone signal to craft item” or something like that

**Comment by TOLoneWolf** [comment]
it sends nothing. just tells the system to wait for the output to be returned.

emitting redstone does not do the same thing.

**Comment by Sea-Kerman** [comment]
no, I mean how does the world know your ME system wants to craft cobblestone?

**Comment by TOLoneWolf** [comment]
what does the world have to do with the ME system waiting for resources to be returned from a "craft" from an external machine?

**Comment by Sea-Kerman** [comment]
how do you tell your machine to craft cobble?

**Comment by TOLoneWolf** [comment]
Level emitter if i want to turn it off or on. but that has nothing to do with the system not knowing it will get cobble from it.

**Comment by Sea-Kerman** [comment]
It has everything to do with the system knowing it will get cobble. No pattern required. How would a pattern with no inputs even work?
![2022-09-13_21 07 04](https://user-images.githubusercontent.com/41390862/190057286-406629a7-cb34-4b34-bf92-0e5dce86f8ab.png)

**Comment by TOLoneWolf** [comment]
ah crafting upgrade does 0 input crafting as an option nvm sorry sort of exists already jsut need to use an emitter even if you dont want to turn on or off something.
