### ISSUE TITLE
Adjust dust production

### ISSUE THREAD

**Issue by uhloin** [AppliedEnergistics/Applied-Energistics-2#6567]
### Describe the feature

1. Ender dust looks like crushed ender eye. May be it should be created in Inscriber (instead of Blast Furnace) like fluix crystal -> fluix dust? Or may be it is need some intermediate item "Ender Crystal" as result of drying eye in furnace?
2. Fluix dust and certus quarts dust looks like simpler and smaller items than crystals but their production has the same cost and requires even more steps. May be add crafts 1:4 or 1:9 similar to glowing dust and redstone dust? Like this:
Fluix crystal -> Inscriber -> 4/9 fluix dust -> water -> Fluix crystal 
Certus quarts crystal -> Inscriber -> 4/9 certus quarts dust -> water -> Certus quarts crystal 
Ender crystal -> Inscriber -> 4/9 ender dust -> water -> Ender crystal
3. Frequently and extensive used item "Fluix ME glass cable" is too expensive for such a small thing. The cost of thick cables is absurd. If use dust instead of crystals for craft cables with 1:4 or 1:9 receipts then cost becames more adequate.

### Reasons why it should be considered

Make crafts closer to the intuitive expectations of the players and already existing crafts.
Make basic item crafts cheaper.

**Comment by Technici4n** [comment]
Hi, thanks for the feedback.

1. Yes, we should definitely do that. The blast furnace recipe was added because we hadn't thought of using the inscriber as a smashing device back then.
2. It's pretty standard to have e.g. diamond or emerald dust that looks "small" compared to the crystals. You could consider that crystals contain a lot of air, while dust is a more compact structure. ;)
3. AE2 is somewhat expensive to setup, that's true, but with infinite certus quartz and the resource farming methods provided by most modpacks we think it's reasonable, and we are not going to change that. However you can adjust the recipes yourself using data packs if you want.

**Comment by Technici4n** [comment]
Fixed 1. in fde832291004075032a9261866eb3aca7c2ef239.

**Comment by uhloin** [comment]
3. Above farming and for farming -- could you make a feature for certus bud/cluster to gain signal 0-4 to comparator according of grow? As further dream -- grow and farm amethyst clusters with AE2 accelerators/comparators...

**Comment by Sea-Kerman** [comment]
What's the point of that though? If you want the crystals, filter the annihilation plane for crystals, If you want the dust, don't filter the annihilation plane so it breaks the buds as soon as they appear.

**Comment by uhloin** [comment]
But annihilation plane do not open any interface on right click. Only import bus has such filter. Also I tried but could not combine them together.

**Comment by Technici4n** [comment]
You can use a subnetwork to filter the annihilation plane.

**Comment by uhloin** [comment]
Please say how does this prevent ungrown crystals from being destroyed by the annihilation plane?

**Comment by Sea-Kerman** [comment]
Have a subnet with just an annihilation plane and a storage bus. 

Filter the storage bus for the drop of the block you want to filter for (in this case, a certus quartz crystal). 

Storage bus goes on some inventory, barrel, chest, ME interface, etc. 

An annihilation plane can only break the block in front of it if it can store the result in the network it's on. 

Ungrown buds drop certus dust, which cannot be stored, so the annihilation plane does not break the cluster.

Grown buds drop certus quartz crystals, which can be stored, so the annihilation plane breaks the cluster.

**Comment by uhloin** [comment]
Thank you, this trick really works, just need connect separate energy line to avoid concatenation with main network.
Strange thing is trick stop working if I try use cheaper ME Export Bus instead of ME Storage Bus in export-only (insert-only) mode.

**Comment by Sea-Kerman** [comment]
That's what quartz fibers are for. They transfer power but not data. 

The export bus doesn't work, because the annihilation plane only inputs ot network storage and the export bus only takes from network storage, but a network with just an annihilation plane and export bus has no storage so neither works.

**Comment by uhloin** [comment]
It is contrintuitive if export and import bus have not storages but their combination (storage bus) has some invisible storage.

About fiber it is not work as described. I even cannot connect fiber to fiber, the hole stay on every corner.

**Comment by Sea-Kerman** [comment]
It's not counterintuitive or invisible, that's exactly wwhat the storage bus does. It treats the inventory of the thing it's facing like network storage, so when the annihilation plane imports something into the network, the storage bus stores that thing in whatever inventory you connect it to.

Quartz fibers aren't cables by themselves, they're multipart bits like busses or terminals. You put them in between cables.

**Comment by uhloin** [comment]
If Storage Bus "treats the inventory of the thing it's facing like network storage" why Export Bus do not do exactly the same? They looks very similar and documentation say nothing about such difference. The documentation have many holes. I hope the time will come for Patchouli AE2 :)

Thank you again, fiber does work as yo said. I think it is next contrintuitive item, because it looks like a cable, used to create cables, but works as a sinlge piece like "ME Toggle Bus". I would make it as a separate element like "Information Isolator" with icon similar to "ME Toggle Bus" but transparent and would make craft of fluix cable direct: 
4 Glass, 2 Fluix Crystal, 3 Certus Dust -> 12 ME Fluix Cable

**Comment by uhloin** [comment]
I tried use the same method for amethyst but failed. It breaks bud without get shard and does not allow grow it to cluster. I tried set filter to amethyst shard and to amethyst cluster and both without success. Only way is enchant annihilation plane to silk touch and set filter to amethyst cluster but then full amethyst cluster is retrieved, need set it to ground and use pickaxe to make shards. I could not automate this with formation plane+second annihilation plane.

**Comment by uhloin** [comment]
Because of previous explanations I thought annihilation plane requires some storage and I tried scheme with annihilation plane, storage bus and formation plane in the same network. I thought annihilation place will get cluster, storage bus put it to container and get back and give to formation plane and formation it place cluster. But it does not work in such manner. The work of those planes is not obvious, and there are no examples in manual.
