### ISSUE TITLE
Crafting Plan resulting from JEI/REI "craft missing" is outdated

### ISSUE THREAD

**Issue by shartte** [AppliedEnergistics/Applied-Energistics-2#6583]
When using the "craft missing" feature in the JEI/REI integration, the resulting crafting plan incorrectly considers items moved from the network to the crafting terminal as being available for auto-crafting. This is due to the plan being built using the cached inventory before the next tick could update it.

**Comment by Technici4n** [comment]
Fixed in https://github.com/AppliedEnergistics/Applied-Energistics-2/commit/b4c9515d6dbf50b3cb8279bb1a04822cf9fb281b.
