### ISSUE TITLE
Achievement 'Next Gen Crafting'

### ISSUE THREAD

**Issue by uhloin** [AppliedEnergistics/Applied-Energistics-2#6590]
### Describe the bug

Description is "Craft a crafting unit". I crafted Crafting Unit and Crafting Co-Processing Unit and one more Crafting Unit but did not get acievment.

### How to reproduce the bug

-

### Expected behavior

-

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

-

**Comment by Technici4n** [comment]
You need one of the 1k-256k crafting storages apparently. It's a bit misleading so I'll change it ;)
