### ISSUE TITLE
Arrays of pattern providers over 8 bug out

### ISSUE THREAD

**Issue by tsbreuer** [AppliedEnergistics/Applied-Energistics-2#6596]
### Describe the bug

When making Pattern Provider towers, as shown in picture, if you have more than 8 pattern providers connected it will bug out.
![image](https://user-images.githubusercontent.com/6902643/190955136-12eb3c6d-52f9-48ab-a52f-ff521f7cacfd.png)

There's pattern provider assembler towers that go 4 pattern providers tall, so the seccond group of 8 should be connecting to the back smart cable. However, the back ones aren't connecting.

The Pattern providers still show up online, and the patterns in them are available to the network to autocraft, either directly or in recipes, however when attempting by a player or automation to autocraft, the crafting processor will get stuck on scheduled and do nothing for the problematic patterns.

If you disconnect the back cables, they will still show up as device online, even though they should show up as device missing channel:

![image](https://user-images.githubusercontent.com/6902643/190955853-a0755360-3e2c-4da4-a8ac-0ceae58ff328.png)

If you make the towers stop touching, it will go back to working fine, but its still not how it should work.

Short video:
https://youtu.be/8ZjY28tTVXg

### How to reproduce the bug

Placing 2 groups of 8 Pattern Providers in a way they are connected to eachother due to their molecular assemblers touching.

### Expected behavior

AE2 should be splitting the channels properly into each fluix cable, but its trying to send it all into one for some reason .

### Additional details

Version: appliedenergistics2-11.1.7

This seems to only happen with my setup of vertical towers with 4 pattern providers each on them, i have an identical setup that is only 2 tall instead and its splitting the channels just fine:
![image](https://user-images.githubusercontent.com/6902643/190957098-bccb73f7-212f-407d-91ab-11aabd4da145.png)
This is on ATM7 To the Sky 1.0.7 modpack.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/sqCgQiF0

**Comment by Sea-Kerman** [comment]
because channels can route through molecular assemblers (and they can only handle 8 channels) you're running into channel routing issues I think. It does not go by smartly allocating channels to cables and paths that can accept them, it goes by distance, so your current layout makes it route all the channels through the assemblers and not the cables.

**Comment by Technici4n** [comment]
Exactly what @Sea-Kerman said. You could use a p2p tunnel on your "main cable" to shorten that path.
