### ISSUE TITLE
Add support for EMI

### ISSUE THREAD

**Issue by Chikage0o0** [AppliedEnergistics/Applied-Energistics-2#6600]
### Describe the feature

Add support for EMI

### Reasons why it should be considered

EMI is a very unique recipe browser, which is different from REI/JEI. its unique recipe tree function can improve the game experience.

### Additional details

https://modrinth.com/mod/emi
https://github.com/emilyploszaj/emi/wiki/

**Comment by Technici4n** [comment]
We don't have the time/will to maintain integration for two recipe viewers (REI integration is falling behind JEI integration already), let's not make it worse. All of these mods should agree on a common API if they want everyone to support them.

**Comment by Chikage0o0** [comment]
This is a less than perfect support, to you can refer to it.

https://github.com/Chikage0o0/EMICompat/tree/1.19/src/main/java/me/chikage/emicompat/ae2

**Comment by T0pN1ck** [comment]
@shartte what about emi support?

**Comment by LostQuasar** [comment]
Something to keep an eye on
https://modrinth.com/mod/tla-api

Another note this mod exists in the mean time for EMI users it's not perfect but it's usable https://modrinth.com/mod/ae2-emi-crafting

**Comment by Technici4n** [comment]
We have EMI support in 1.20.4+.
