### ISSUE TITLE
AE2 Spamming console/Log with errors

### ISSUE THREAD

**Issue by Zelioth** [AppliedEnergistics/Applied-Energistics-2#6601]
### Describe the bug

I recently updated my 1.19.2 modpack and public server to the recent version of AE2, while also adding a few other mods. The only mod I think will interfere with AE2 things is called Almost Unified but I am unsure. Anyway after updating and starting my server this error continues to clutter the console 

23.09 01:41:06 [Server] Server thread/WARN [AE2:S/]: Could not decode an invalid crafting pattern {in:[{Count:1b,id:"minecraft:iron_ingot"},{Count:1b,id:"minecraft:iron_ingot"},{Count:1b,id:"minecraft:iron_ingot"},{Count:1b,id:"minecraft:iron_ingot"},{Count:1b,id:"dimstorage:dim_core"},{Count:1b,id:"minecraft:iron_ingot"},{Count:1b,id:"minecraft:iron_ingot"},{Count:1b,id:"minecraft:iron_ingot"},{Count:1b,id:"minecraft:iron_ingot"}],out:{Count:1b,id:"dimstorage:solid_dim_core"},recipe:"dimstorage:solid_dim_core",substitute:0b,substituteFluids:0b}: java.lang.NullPointerException 
[Ae2 Error.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/9630292/Ae2.Error.txt)

### How to reproduce the bug

Mod Pack : https://www.curseforge.com/minecraft/modpacks/friends-united/files/4001272
Forge Version : 43.1.27
AE2 Version : 12.5.2Beta

Our Public server has many AE systems active on it and I think it's the items within the system. Not sure why or how though
[latest(9).log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/9630301/latest.9.log)

### Expected behavior

To not spam with missing item recipes

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

No Crash Log

**Comment by Technici4n** [comment]
It's likely an interference with Almost Unified. You'll have to re-encode the erroring patterns.
