### ISSUE TITLE
Crashes upon load

### ISSUE THREAD

**Issue by CrystalWolfYT** [AppliedEnergistics/Applied-Energistics-2#6602]
### Describe the bug

By using the 1.19.2 1.5.2 I have overcome an issue in which upon launching minecraft, it will immediately crash after loading

### How to reproduce the bug

1. Game mode: None, Crashed upon load
2. Map: None.
3. Location: Loading Screen Upon Game Launch
4. Creating bug/crash: Launch game, game loads, crashes at completed loading screen.
5. Bug: Issue loading mod items

### Expected behavior

My expectations were the game would run normally without an issue, and boot up normally

### Additional details

The crash report inflicted that the issue wasn't rendering any of the mod items, rendering them as "the void"

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/CrystalWolfYT/3958d849cbc50d018b2b2bce0c89d821

**Comment by Technici4n** [comment]
Update AE2

**Comment by RealIndica** [comment]
@Technici4n This issue still occurs in the latest AE2 for 1.19.2. Exact same reason for crash, also.

**Comment by XFactHD** [comment]
If the crash is the exact same as the one posted above, then remove OptiFine. It breaks a recent change done by Forge and has not been updated to accommodate that change.
