### ISSUE TITLE
Spatial pylon has invalid texture

### ISSUE THREAD

**Issue by uhloin** [AppliedEnergistics/Applied-Energistics-2#6608]
### Describe the bug

It is because I use Rubidium but it was OK in previous versions AE2. I am not sure about exact version when texture was broken but not more than month ago.

### How to reproduce the bug

Use last version of AE2 and Rubidium for 1.19.2 and place spatial pylon.

### Expected behavior

-

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

-

**Comment by Technici4n** [comment]
We don't support rubidium, please report this issue to them.

**Comment by uhloin** [comment]
OK, I will report but they probably will want know what specific changes you made in your code which broken textures. Could you help with details?

**Comment by coderepo8593** [comment]
> OK, I will report but they probably will want know what specific changes you made in your code which broken textures. Could you help with details?

I will second this. What is unique about the mesh, maps, or texture that you believe might be causing it not to render, so that Rubidium can support this mod and likely others if this isn't particular to AE2?

**Comment by Technici4n** [comment]
No idea, we are using the standard rendering hooks provided by Forge.

**Comment by uhloin** [comment]
I found this issue probably not from AE2 or Rubidium. It occurs with some combination of 50 mods I use. If I remove some of them it fixed but there is no specific "bad" mod. I reinstalled Minecraft, copy all mods again and bug is disappeared. May be some file was corrupted.
