### ISSUE TITLE
Charger crashes server

### ISSUE THREAD

**Issue by Hippocat1** [AppliedEnergistics/Applied-Energistics-2#6620]
### Describe the bug

Charger crashes server

### How to reproduce the bug

Crafting it and placing on the ground

### Expected behavior

I guess it shouldn't lol

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/BS8g3qPN

**Comment by Technici4n** [comment]
Hi, please update Forge.

**Comment by Hippocat1** [comment]
> Hi, please update Forge.

I updated it, but it still crashes
https://pastebin.com/p3npiM7D

**Comment by XFactHD** [comment]
Try removing OptiFine, it's very likely nuking a feature added by Forge.

**Comment by Hippocat1** [comment]
> Try removing OptiFine, it's very likely nuking a feature added by Forge.

It doesn't works, sadly. Is there any version compatible to 43.1.2?

**Comment by Technici4n** [comment]
We only support Forge >= 43.1.24 and we don't support Optifine.

**Comment by Hippocat1** [comment]
> We only support Forge >= 43.1.24 and we don't support Optifine.

I have no clue how to update it on TL Launcher since their last forge version is 43.1.2. What can i do??

**Comment by Technici4n** [comment]
We don't support hacked clients. You can pay the game for example.

**Comment by Hippocat1** [comment]
> We don't support hacked clients. You can buy the game for example.

Alright, thanks
