### ISSUE TITLE
mod:item Card for export bus

### ISSUE THREAD

**Issue by joaquincabrerasimoes** [AppliedEnergistics/Applied-Energistics-2#6645]
### Describe the feature

A card that can be added to export bus in which you can write the "modid:itemid" for export and anything that matches that will be exported.

### Reasons why it should be considered

In my case the problem that I am facing is with the item called "Traveler's Goggles" from Tinkers Construct which are dropped from a mob farm I made, internally those are called "tconstruct:travelers_helmet". Just the other day I ended up having SO many of them in my ME system that the packet sent from the server to the client was bigger than 2MB and it wouldn't display any of my items. I had to remove drives from my ME so that the packet would be smaller than 2 MB and by hand delete 3000 "Traveler's Goggles" because Fuzzy Card would not work with them.

So, it would be cool to have a specific, provably expensive to make, card that could manage those items with weird behaviors from other mods.

### Additional details

![Screenshot 2022-10-01 115133](https://user-images.githubusercontent.com/34731493/193415236-1d800ba8-c8ad-4137-8676-0da43c06a880.png)

**Comment by Technici4n** [comment]
Fuzzy card will match any item based on the item ID only, so it should have worked?
