### ISSUE TITLE
Powered Doors. 

### ISSUE THREAD

**Issue by gkuba** [AppliedEnergistics/Applied-Energistics-2#665]
I think it would be cool to have powered doors that you can control access to via your security terminal like the rest of the network. This way you can separate parts of your base via security levels.

**Comment by RAnders00** [comment]
I'm not seeing how a "powered door" would fit the theme of Applied Energistics. I do not understand why it should be in AE, it might as well be a addon for it, if you really need to use AE's security system.

**Comment by Deshiba** [comment]
Hmm, this could possibly be done with formation and annihilation planes? If you place them on opposite sides and a level emitter on the formation plane. The planes would keep placing and breaking at high speed not allowing anything to get trough. Thus be 'closed'.

Turning this off would be done by switching the setting on the level emitter to a lower or higher number then there is of that item in the ME system. So the formation plane will not place new blocks and thus 'opening'.

This could be easier to set up if the blocks placed by the formation plane were considered part of the ME system and be labeled as unbreakable some how? But I wouldn't know how that'd look.
