### ISSUE TITLE
All AE2 autocrafting perpetually stuck in a "Scheduled" state

### ISSUE THREAD

**Issue by codedcosmos** [AppliedEnergistics/Applied-Energistics-2#6650]
### Describe the bug

When starting an autocrafting job, for example Quartz glass. With the appropriate amount of materials inside the system. (e.g. 4 minecraft:glass and 5 ae2:quartz_dust) (not sure about specific items ID's but you get the idea).

It gets stuck in a scheduled state. This happens for all jobs, not just quartz glass.

![image](https://user-images.githubusercontent.com/5248038/193518778-2372b5ba-5986-40c0-ba6f-906de2510867.png)

### How to reproduce the bug

ATM I can just schedule any crafting job and pauses indefinitely. 

Things I have attempted to fix the issue:

- Cancel job and restart it.
- Remove power source from AE2 system and replace.
- Remove and replace molecular assembler and pattern provider
- Remove power and molecular assembler and pattern provider and replace. 
- Break and replace crafting processors
- Don't use any crafting co processors

### Expected behavior

4 quartz glass to be created and it's crafting components removed from my system.

### Additional details

I am not using Black holes or drawers or anything fancy. Simply 8 AE2 drive bays filled with regular AE2 drives (1k and 4k).

I am on the Direwolf20 1.18 pack specifically 1.9.1.

I have a fairly small AE2 network. With channels disabled in the config. No custom AE2 addon mods have been used.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/codedcosmos/a15a24462e82ad8a46a79f391c22bd54

**Comment by Tahakk** [comment]
I'd say try to reproduce it in creative to see if it's modpack specific or just you setup specific. Or other option would be update your AE2 individually.

**Comment by codedcosmos** [comment]
Ok I'll do some more investigation along the lines of that and get back to you soon.

**Comment by Cdarkace** [comment]
I had the same issue, I had to recheck every pattern provider (I had the "tree" setup) and to fix the issue I had located patterns that were in pattern providers but the pattern access terminal couldn't see them. I removed the hidden pattern and put in new ones and it seemed to fix the issue

**Comment by codedcosmos** [comment]
Unfortunately I'm kinda burnt out of testing by doing it a bunch for my day job.

**Comment by Technici4n** [comment]
Some fix in this area will be in the next release.

**Comment by Quezler** [comment]
Encountering these same symptoms on stoneblock 3 (appliedenergistics2-forge-11.6.4)

Breaking & replacing the molecular assembler(s) next to the pattern provider seems to make it resume for me. 🤔 

When canceling the recipe some of the items crafted intermediately do show up, which gives the impression that when using the same provider/assembler for a recipe chain (e.g. logs -> planks -> crafting table) it imports the output of a step, as well as imports the items for the next step, and breaking & replacing causes it to retry the recipes, but that's just a totally untested hypothesis. 🙃

**Comment by Technici4n** [comment]
Will get the fix out in a bit.
