### ISSUE TITLE
AE2 M.E Drive block interior renders as Black when using True Darkness from Rubidium's Extras

### ISSUE THREAD

**Issue by Aeases** [AppliedEnergistics/Applied-Energistics-2#6652]
AE2 M.E Drive interior renders as black only on the Pitch Black Setting of Rubidiums True Darkness setting

### Specs / Game Info:
OS: Linux
Game Version: 1.18.2

Mods: 
> appliedenergistics2-11.5.0.jar
> rubidium-0.5.3a.jar
> rubidium_extras-1.18.2_v1.3.2.jar

GPU: RTX 3070
CPU: Ryzen 5600x
RAM: 32GB

### Demonstration Video:
https://youtu.be/RrtwxvV_SiA

<br>

[Latest.log](https://cdn.discordapp.com/attachments/963117719752953876/1026558858669347037/latest.log)

<br>

_possibly related?_

```rust
[01:55:06] [Render thread/WARN]: Method overwrite conflict for getSprite in ae2.mixins.json:unlitquad.BakedQuadAccessor, previously written by me.jellysquid.mods.sodium.mixin.core.pipeline.MixinBakedQuad. Skipping method.
```

<br>
<br>

![](https://media.discordapp.net/attachments/963117719752953876/1026557199910195210/unknown.png?width=635&height=566)

**Comment by Technici4n** [comment]
We don't support mods that mess with our rendering, report to them.
