### ISSUE TITLE
Forge Incompatibility

### ISSUE THREAD

**Issue by LordRelentless** [AppliedEnergistics/Applied-Energistics-2#6653]
### Describe the bug

I have Forge 43.1.3, I get an error message on load that it requires 43.1.24 and above and below 44, I can't use the mod.

### How to reproduce the bug

No idea, installed it into the official minecolonies mod pack, that's it.

### Expected behavior

To not kick an error saying it needs something it has.

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

no crash log created

**Comment by Tahakk** [comment]
41.1.3 is lower than 41.1.24... indeed get a proper forge version

**Comment by LordRelentless** [comment]
> 43.1.3 is lower than 43.1.24... indeed get a proper forge version

Um...43.1.3 is 43.1.30...30 is higher than 24...it is between 43.1.24 and 44.0.0...43.1.3 is the latest available Forge release from Forge's website. In fact I have specific 43.1.33f installed, literally released yesterday. 

Please check your mod and fix this problem.

**Comment by 62832** [comment]
Not sure why you're trying to apply usual numbering logic from maths given that there isn't such a thing as a number with two decimal points to begin with to apply that logic to. In software versioning, the dot is nothing more than a separator for a couple different numbers corresponding to dev stages.

Indeed, 43.1.3 is lower (rather, _earlier_) than 43.1.24.
