### ISSUE TITLE
Auto-crafting utilizing the AE2 Inscriber

### ISSUE THREAD

**Issue by IsaiahMM** [AppliedEnergistics/Applied-Energistics-2#6656]
### Describe the bug

Could be a bug but doubt it is. I'm more so requesting information. I looked for the discord to just ask on there but it isn't popping up when I search servers and I am unable to accept the invite.

Minecraft: 1.19.2
Forge: 43.1.27
AE2:  12.6.0

So, I have been trying now for a few days to completely automate making the different prints & processors for my AE2 system. I have watched many videos (there aren't many for automating the Inscriber, some creators only automate using the Advanced Inscriber from AE2 things.)  and tried to block for block copy their set ups to no avail. 

In addition, I tried myself using many different set-ups, utilizing different components such as the ME Exporter, ME Importer, ME Storage Bus, ME Pattern Provider, ME Interface and the Inscriber.

Although I have a much better understanding of how some of these components work now after a couple days of research; I still am unable to fully automate this process. I have been able to partially automate it using Interfaces, inscribers, and import buses, I find it very inefficient and it takes up a decent amount of space; compared to if I were able to completely automate it using the pattern provider and auto crafting.

Granted I still do not perfectly understand the blocks and their interactions with the overall system, I could have missed something on my setup, I would appreciate any guidance on doing this. 

Thank you in advance for any and all advice.

### How to reproduce the bug

Attempt auto crafting the processors using storage buses, pattern provider, importers, exporters, and/or interface.

### Expected behavior

According to the AE2 wiki I should be able to automate the process with Storage Buses but have not been able to.

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

NA

**Comment by Sea-Kerman** [comment]
Odd the invite isn't working

This is the general topology of the problem and solution
![Processor Automation](https://user-images.githubusercontent.com/41390862/194158362-1c69887b-a8f7-4df7-ac03-213dbd065c6d.png)
![2022-09-08_14 24 44](https://user-images.githubusercontent.com/41390862/194158509-5a85c78d-03ea-4d8d-b4e9-bd311601650a.png)
![2022-10-05_13 37 42](https://user-images.githubusercontent.com/41390862/194158799-c4e99a0b-6969-4536-ab53-960aa354e65b.png)

**Comment by Sea-Kerman** [comment]
The discord link on the website doesn't work?
https://appliedenergistics.github.io

**Comment by Sea-Kerman** [comment]
I just tried it and it worked fine for me. odd. Perhaps you are in too many discords?

**Comment by IsaiahMM** [comment]
I was able to join it now, thank you.

also I see in certain places in this build you have the normal Fluix glass cable in the same block as the smart cable. unless I'm doing something wrong, I am unable to have those two connected in the same block.
