### ISSUE TITLE
Catalyst crafting.

### ISSUE THREAD

**Issue by Kevin-Marsh** [AppliedEnergistics/Applied-Energistics-2#6660]
### Describe the feature

At the moment it is basically impossible to craft things in ae2 that use an item as a catalyst. Two main examples are mystical agriculture with the infusion stone and projecte with the philosophers stone. My thought about this would be to modify the way that crafts are handled slightly. I would love to see the ability for AE2 to have an option when making a pattern to set an ingredient as a catalyst. Basically it would mean being able to tick a box which tells the crafters that this item will be back after the current craft is done and they would know that it only needs the 1 item to complete all of the crafts.

### Reasons why it should be considered

It would simplify crafting for various mods that reuse items in their crafts.

**Comment by Technici4n** [comment]
Catalysts are already handled automatically by AE2 in 1.18+. Which version are you on?

**Comment by Random832** [comment]
If your catalyst item has a durability meter, you need to enable item substitutions in the pattern.

**Comment by Kevin-Marsh** [comment]
Huh, that worked. You guys continue to exceed expectations. Thank you for always making such an awesome mod.
