### ISSUE TITLE
import bus imports liquid from Tinker's casting table

### ISSUE THREAD

**Issue by Spongman** [AppliedEnergistics/Applied-Energistics-2#6675]
### Describe the bug

this never used to happen. import bus always used to wait until ingot was formed before importing it. now ingots never form, the liquid just gets imported into my AE2 system instead.

### How to reproduce the bug

tinker's foundry, pour into casting table with attached import bus.

### Expected behavior

wait for ingot to be cast.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

no crash

**Comment by Random832** [comment]
Unfortunately I suspect this is unsolveable due to regular import buses being able to import any type of object. You may need to use hoppers or another mod's item pipes, or a subnet that only has item storage, and import from there.

**Comment by Speiger** [comment]
Small suggestion:
Have a option to filter that says: "Items Only, Fluids Only, Both"
