### ISSUE TITLE
ME System deletes items

### ISSUE THREAD

**Issue by OldOpa** [AppliedEnergistics/Applied-Energistics-2#669]
I experienced it with livingwood from botania. I have enough storage seperated as a subnetwork. It doesn't matter if I shift-click the item in a (wireless) terminal or if i drop it in.

**Comment by TheJulianJES** [comment]
Can you maybe give us screenshots or a video, a log, your setup?

**Comment by OldOpa** [comment]
After some testing i found out that it has to do with p2p tunnels. I have my terminals set up with p2p tunnels (also over a ME Quantum Network Bridge). When i connect my terminals directly with my storage drive subnetwork or a import bus the items won't be deleted.

http://i.imgur.com/YW4NSrG.png - main network (storage subnework red)

http://i.imgur.com/0GXNF8A.png - terminals connected via p2p tunnel to main network (cyan cable)

http://i.imgur.com/JjpiATf.png - Quantum network bridge connected to main network with p2p (dark blue cable.

http://i.imgur.com/4x1rKjq.png - other end of quantum network bridge.

**Comment by OldOpa** [comment]
Oh and i forgot. clearing the crafting terminal with this setup will also delete the items.

**Comment by thatsIch** [comment]
And this helps us reproduce in what way?

Neither did you give us a version number, nor Forge, nor a minimal setup to reproduce this issue.

**Comment by TheJulianJES** [comment]
@OldOpa You've got a storage bus on a condenser?

**Comment by OldOpa** [comment]
Ok. Brief description. As you can see on the pictures you'll need a storage posibility (maybe as subnetwork), a p2p tunnel connected to the main system and a terminal connected with a p2p tunnel. 

For the condenser. The storage bus is only whitelisted for matterballs and on "extract only". Also a extra utilities transfer node is trying to keep the condenser "full". And at the time the problem occured the condenser was full because I didn't use the stored matterballsin quite a while. The drives also have a higher priority than the storage bus of the condenser.

Sorry for the missing versions. I use the latest version of applied energistics 2 (rv2-beta-6) and the recommened forge version (10.13.2.1230).

**Comment by thatsIch** [comment]
So you say, your condenser is not voiding your stuff?
Did you remove the storage bus on it for once, cause my networks dont void anything.

**Comment by OldOpa** [comment]
I rebuild my system and now it is fixed. Maybe it just was a bug when updating the version from stable to beta or so. 

Maybe you should add a check if the energy is full: https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv2/src/main/java/appeng/tile/misc/TileCondenser.java#L111

Thanks for your time and sorry if I wasted it.

**Comment by TheJulianJES** [comment]
You didn't waste it, I think direwolf20 said that there was a broken update with cables.
Now closing this would be a good idea =)

**Comment by thatsIch** [comment]
Its meant as a trash-can with nice side-effects.
