### ISSUE TITLE
Power Usage appears to be off

### ISSUE THREAD

**Issue by MuteTiefling** [AppliedEnergistics/Applied-Energistics-2#6693]
### Describe the bug

The power usage reported in Network Details appears to be incorrect. 

For the record, I am goofing with the configs. Currently, however, it's just set to this:
```json
  "PowerRatios": {
    "ForgeEnergy": 1.0,
    "UsageMultiplier": 1.0
  },
```

So, I have a tiny network setup. The draw is low, but the numbers don't add up. 
![image](https://user-images.githubusercontent.com/9543430/195595987-1f52bed2-73d8-466b-bbd9-f694b0016722.png)

Two Storage busses at 2 RF/t each, so 4. A crafting terminal at 0.5, and the channel drain at 0.4

That should be 4.9 RF/t. Maybe 5.7 if the channel drain is per channel. I'm really not sure how that's meant to be calculated.  Instead, it is much lower than expected at 2.9 RF/t

Similarly, when I bumped the power use up to 5.0, that same network started drawing 14.38 FE/t. This should be 14.5 at 5x the power usage. Also, all of the components still listed the same values which is counter-intuitive to the player.

### How to reproduce the bug

Create any small network where the power costs are easy to calculate manually
Check with a network tool

### Expected behavior

For the power usage to display accurately and be consistent with the config. 

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/MuteTiefling/8c7b8b5f654d4890876f8e3c14fea38b

**Comment by Technici4n** [comment]
> Two Storage busses at 2 RF/t each, so 4

It's actually the total power draw for the 2 storage busses. For example this is what I get if I add a third one:
![image](https://user-images.githubusercontent.com/13494793/202927497-16ee9309-d628-4ba8-8fea-049a57f580fd.png)

This explains the additional 2 RF/t in your math. :wink:
