### ISSUE TITLE
Additional filter options for export/import/storage buses

### ISSUE THREAD

**Issue by AerosAtar** [AppliedEnergistics/Applied-Energistics-2#6696]
### Describe the feature

Add additional filter options for use in the export bus, import bus and storage bus:

Examples:
* By tag
* By mod id
* By nbt

### Reasons why it should be considered

The currently available options for filtering the buses are extremely limited, both in scope and size. For example, the export bus, which only allows at most nine specific items to be listed.

Adding the additional options above would allow for more compact and simple setups with a much lower overhead for users and the networks. For example, exporting all #forge:ores items into a processing setup, instead of having to set up each ore individually across multiple export buses.

**Comment by CyberFoxar** [comment]
Another use for such a feature is when playing challenging modpacks that do not use cells and instead have us rely on storage busses.

This would allow for using both the AE2 terminal to find items as well as storing them in special places to directly go fetch them, the idea being to not have to create one (or a few if you have related mods) search in the terminal to grab the requiered item(s).

**Comment by Ashendale** [comment]
Came here searching how to use this feature. It doesn't exist. I'm in favor of adding it. I currently have my system with different kinds of seeds. I'd like to process one mod's seeds and ignore all the rest. Tag filtering would allow this.

I tried using a different mod to draw from the system using an ME Interface, but it doesn't work like that.

**Comment by CyberFoxar** [comment]
> Came here searching how to use this feature. It doesn't exist. I'm in favor of adding it. I currently have my system with different kinds of seeds. I'd like to process one mod's seeds and ignore all the rest. Tag filtering would allow this.
> 
> I tried using a different mod to draw from the system using an ME Interface, but it doesn't work like that.

 A workaround for your use-case would be using a pre-processing storage bus (put all seed from all mods in an inventory, use another mod to sort them out) or entry buffer (have all seeds go to a "holding" inventory, sort them using another mod, then input the seed you wanna keep in AE2).  We have both solution implemented in our game, it's annoying, but it works.

**Comment by Technici4n** [comment]
Closing in favor of #6853.
