### ISSUE TITLE
Support for Curios API

### ISSUE THREAD

**Issue by AerosAtar** [AppliedEnergistics/Applied-Energistics-2#6697]
### Describe the feature

Add curios support for the Wireless Terminal and Wireless Crafting Terminal, ideally by adding a new dedicated curio slot with custom icon.

### Reasons why it should be considered

Currently the wireless terminals do not function with the Curios API. Even if added via the curios datapack method, the termials do not open when the hotkey is pressed - they only work when in the hotbar or inventory.

This enhancement/feature would allow for users to make use of the terminals without having to sacrifice an inventory slot.

**Comment by Sea-Kerman** [comment]
AE2wtlib does this for trinkets it seems

**Comment by Mari023** [comment]
> AE2wtlib does this for trinkets it seems

and for curios too
