### ISSUE TITLE
Cannot hide facades in JEI using enableFacadesInJEI in client config

### ISSUE THREAD

**Issue by Cryotheus** [AppliedEnergistics/Applied-Energistics-2#6698]
### Describe the bug

The settings `enableFacadesInJEI` in `config/appliedenergistics2/client.json` has no effect.
- The Forge version is `40.1.80` for all tests.
- The Minecraft version is `1.18.2`
- The only mods installed are AE2 and JEI
- The configuration was only edited while the game was not running.

| AE2 | JEI | `"enableFacadesInJEI": true` | `"enableFacadesInJEI": false` |
| --- | --- | :---: | :---: |
| `11.5.0` | `9.7.1.255` | ![true](https://user-images.githubusercontent.com/14439112/195755118-2280c4ae-a308-4314-b9ff-a8b099d8af4a.png) | ![false](https://user-images.githubusercontent.com/14439112/195755214-3c5c92bf-b6b4-46a8-8ad1-be052a4ab749.png) |
| `11.6.1` | `9.7.2.264` | ![true](https://user-images.githubusercontent.com/14439112/195755529-0439d7d8-6b12-4191-9e55-534d94c39bc3.png) | ![false](https://user-images.githubusercontent.com/14439112/195755485-7884550e-e266-4ef8-a355-aac9fdb74115.png) |

### How to reproduce the bug

1. Ensure `enableFacadesInJEI` is set to `false`
2. Launch the game
3. Explore JEI and find facades for every possible block type

### Expected behavior

1. Ensure `enableFacadesInJEI` is set to `false`
2. Launch the game
3. Explore JEI and see facade only for stone (or entirely hidden, don't remember how this setting is supposed to work)

### Additional details

I am also unable to hide the facades using KubeJS.  
Hopefully this is not a duplicate, but at the time of posting this I did not find any other issues related to this.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/6jaw3q1E

**Comment by Technici4n** [comment]
This was fixed in 1.19, probably didn't get backported. Might never be due to limited time.

**Comment by Cryotheus** [comment]
If you lack time, would a pr to fix this for the 1.18.2 branch be accepted?
I won't make one if it's just gonna get ignored/declined.

**Comment by Technici4n** [comment]
Yes, no problem. Maybe look at #6559.
