### ISSUE TITLE
Lithium causes hoppers to stop pulling/pushing items into charger

### ISSUE THREAD

**Issue by purejosh** [AppliedEnergistics/Applied-Energistics-2#6699]
### Describe the bug

Having Lithium installed causes hoppers to no longer push/pull items into the charger. 
I've tested by removing only Lithium, and it started to work again. 

### How to reproduce the bug

Install the following two mods:
AE2 12.8.2-beta [FABRIC]
Lithium mc1.19.2-0.9.1

Observe that hoppers do not continuously pull or push items into the charger block. It will work once, and that's it. 

### Expected behavior

Work. 

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Fabric

### Crash log

https://gist.github.com/purejosh/c41c32f9174e98d4969bdb6b3366668d

**Comment by ramidzkh** [comment]
Use `mixin.block.hopper=false` in your lithium options. Ask the Lithium developers if they want to fix their patch to not break the charger

**Comment by purejosh** [comment]
Yep! They just provided that info to me, and it worked like a charm. I'm opening a github with them now to see if this behavior can be fixed from their end. Thank you! 

At least now this issue exists for search purposes.
