### ISSUE TITLE
Weird Crafting CPU placement

### ISSUE THREAD

**Issue by Speiger** [AppliedEnergistics/Applied-Energistics-2#6700]
### Describe the bug

Crafting CPUs can be placed next to each other in weird ways....

### How to reproduce the bug

![image](https://user-images.githubusercontent.com/2556269/195802799-d15ae848-1116-4a5f-b878-f5751bd522c7.png)

We just added the ones between them main columns afterwards since we wanted to make 2 bulk cpus to process 1 giant task...
Then this happend..

### Expected behavior

Shouldn't the CPUS deform?

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

No Crash

**Comment by Tahakk** [comment]
Maybe more description or more images? It's hard to see what "THIS" is supposed to be.

**Comment by Technici4n** [comment]
Hmmm, I am not sure I understand. Which CPUs multiblocks did you connect?

**Comment by Speiger** [comment]
@Technici4n @Tahakk The left side where there is rows that are not at the same height.
Sorry I thought it was obvious.
I am going to provide more images later today...

**Comment by Speiger** [comment]
Closing, Because this was just a Obscurator troll xD We had our fun. Have fun with the rest xD

**Comment by Technici4n** [comment]
Good thing we did not spend developer resources on this particular issue. While it can be fun for you, it will generally waste a lot of our limited time, so please don't do this again.
