### ISSUE TITLE
Meteorite Compass block self-destructs on a block update

### ISSUE THREAD

**Issue by Cryotheus** [AppliedEnergistics/Applied-Energistics-2#6704]
### Describe the bug

AE2 version: `11.6.1`  
Forge version: `40.1.80`  

A placed Meteorite Compass breaks itself when there is a block update.  

![demonstration](https://user-images.githubusercontent.com/14439112/195999592-917bafb2-3fd4-4ad7-a937-df2dc5d8a171.gif)

### How to reproduce the bug

1. Place a Meteorite Compass
2. Place a block next to it

### Expected behavior

The Meteorite Compass should only break when the block it is connected to is no longer suitable as an attachment.

### Additional details

I have the gamerule `doTileDrops` set to false in the demonstration. This does not change the behavior of the bug.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/6dEgpt7V

**Comment by 62832** [comment]
If I'm not mistaken, the ability for the meteorite compass to be placed down was supposed to be disabled altogether.

**Comment by Technici4n** [comment]
> If I'm not mistaken, the ability for the meteorite compass to be placed down was supposed to be disabled altogether.

It was removed in 1.19 only.

**Comment by Technici4n** [comment]
Tbh this is gone in 1.19, and minor enough for us not to fix. Sorry 😅
