### ISSUE TITLE
Shaped Processing (machine) Patterns Don't Work

### ISSUE THREAD

**Issue by TronWoWGamer** [AppliedEnergistics/Applied-Energistics-2#6707]
### Describe the bug

I am trying to autocraft a processing pattern through an ME Pattern Provider using a shaped recipe.  The Modpack in question is Caveopolis.  The machine in question is called the "Everything Combiner" which is a custom machine.  It uses recipes that are in a 3x3 configuration like a crafting recipe, but they are treated like a processing recipe in the AE system when encoding the pattern.

So, part of the problem is that it's actually a 2 sided craft, that is, there are two "crafting table" like sections in the machine, and for one of the recipes specifically, the second side is a mirror image of the first.  IF any of the items within the 3x3 space is duplicated in another space, rather than placing the items correctly in each space, it combines items that are the same.  I will attempt to explain below.

Let's say the following is a recipe, where each letter represents a different item.

A B C      J K M
D E F      N P Q
G H I      R S T

In this example, the craft will work because each item is different.

Now, suppose this is the Recipe with a mirror image next to it for the other side.

A B C
D E F
C B A

Instead of placing each letter in each space, it combines the A's, the B's and the C's so you get something like this (x is an empty spot) and it won't craft.

2A 2B 2C
D   E   F
x    x   x

Hopefully my pictures explain what is going on.

### How to reproduce the bug

use any recipe where items in the recipe are not all different

### Expected behavior

A craft of the recipe

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

there's no crash report

**Comment by Technici4n** [comment]
It's up to other mods to make their stuff automatable. We can't support every custom crafting table.
