### ISSUE TITLE
Startup Crash: Fabric 1.18.2 Upgrade AE2 from 11.0.0-alpha.5 to 11.5.0

### ISSUE THREAD

**Issue by TheWyzer** [AppliedEnergistics/Applied-Energistics-2#6708]
### Describe the bug

I am using a Modpack, Feta, which has AE2 in it, using 11.0.0-alpha.5.  I wanted to update the pack with the most current AE2 release 11.5.0, as I have seen and used the new UI.

Using Fabric Loader 0.14.9
Java 17

I have tried PolyMC, MultiMC and ATLauncher with same results.

### How to reproduce the bug

Update Feta modpack with AE2 11.5.0 for Fabric from 11.0.0-alpha.5

### Expected behavior

Launch game and create world.

### Additional details

I can return to the 11.0.0-alpha.5 version without issue at anytime.  I did also try versions 11.6.1-beta down to 11.1.0. with no joy.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/gj24Qpnc

**Comment by TheWyzer** [comment]
Did not see a Tag for bug or other options, incorrect tag applied.

**Comment by Mari023** [comment]
try if updating polymorph fixes this.

**Comment by TheWyzer** [comment]
Thank you very much for the solution to this problem!  The one mod, well there are a LOT of them in this pack, that I didn't update.  Updated Polymorph from 0.0.20 to 0.0.21 resolved this issue.

Thank you again.
