### ISSUE TITLE
Feature Request: Whitelist for Annihilation Plane

### ISSUE THREAD

**Issue by Cobra1117** [AppliedEnergistics/Applied-Energistics-2#671]
It would be nice if the annihilation plane could be upgraded to have a whitelist. This would be useful for automating any system where you need to "grow" something. For example:
* Crystal purification
* Wheat/carrot farms
* Botania living wood/stone

I'm not sure how he does it, but VSWE figured out a way to make Steve's Factory Manager do whitelists based on the items that would drop if the block was broken (rather than the block itself). That way, wheat farms could be set up by simply setting a whitelist to "wheat" (instead of having to know the metadata value for fully-grown wheat).

**Comment by gkuba** [comment]
I was recently trying to figure out how to do this kind of thing with the Annihilation plane as well. For example making fluix crystals. I can get the system to use the formation plane and drop redstone dust and both quartz into water but picking up JUST the fluix crystal is the issue.

**Comment by thatsIch** [comment]
This will be regulated in the future by the storage bus. The problem currently is, that the AP has an internal buffer. Depending if the buffer is really needed (mostly for performance) we might remove it.

**Comment by yueh** [comment]
A whitelist for annihlation planes was already rejected multiple times before.

Also crystal purifaction is already possible with AE2 and vanilla only. I know of 2 totally different approaches for it.
I am 99% certain that botania living wood/stone is automatable with AE2. Farming should be possible, but might be extremely inefficent until 1.8.

As @thatsIch said, it might be possible by the storage buses. But it is very likely a performance issue as each item hitting the plane will be checked if it can be inserted into the network and it is possible to deal with thousands of items a tick.

**Comment by gkuba** [comment]
Yueh do you have links to any write ups or youtube tutorials on how to do crystal purification with just AE2 + vanilla? I am one of those that doesn't use any other bigger mods like buildcraft or IC2 etc.

**Comment by Cobra1117** [comment]
@yueh I can see how that would work if the buffer was removed. However, I would be concerned about the performance issues as well--you could overload the network very quickly. The AE-only solutions that I've seen so far aren't much better--they usually involve having a fuzzy formation plane that drops the seed into moving water with an annihilation plane on the other end. This works, but you're still putting a ton of load on your network for a really basic task. If adding a whitelist to the AP isn't an option, maybe a block could be added that grows a single seed quickly (or the growth accelerator could be modified to accept seeds and grow them directly in an internal inventory). This method would require more resources (1 block per seed, rather than many seeds in a single water block), but would be much easier to automate.

(Side note: I do have a solution to this in my game, but I'm using other mods to solve the problem. As @gkuba pointed out, that doesn't work for many other players.)

**Comment by yueh** [comment]
The performance is actually no real issue. Every item colliding the plane is already directly inserted into the network. Except the last insert failed and locked it until the next tick. This can still be implemented by a simple boolean, which then locks the plane until the next tick.

I do not think we will ever add a machine to grow crystals. I personally like them as it is really easy to build a working setup for them, if you think outside the box. But no limits preventing faster, more complex builds. A setup with 6 CGAs is about twice as fast. I have a prototype for it, but it requires a completely different approach.

In the same way, annihilation planes will probably never see their own whitelist. Just respecting the network without locking up.
I do not really see the need to compete with EiO or SFM and dumb everything down and at the same time make it more powerful.

**Comment by Cobra1117** [comment]
*shrug* Fair enough. :-) Feel free to close this issue then.

**Comment by Tergiver** [comment]
I don't think it's about "dumbing down". It's about automation through progression. AE is an automation mod and yet critical AE components cannot themselves be automated through AE. You say that crystal purification is possible with AE and vanilla, but I cannot see the path, and I've really been trying.

**Comment by OscarBarrett** [comment]
@Tergiver It is definitely possible to automate crystal growth, using just AE and vanilla mechanics. I don't want to spoil anything on the tracker, but you can find more information around if you're still stumped. Some tutorials have previously been posted to reddit.

**Comment by Tergiver** [comment]
@OscarBarrett I didn't take your advice and search for the answer, I worked harder at it and I figured it out. It's ugly, and I have no doubt that someone smarter than I could do better, but it works. I even figured out how to power the growth accelerators only while they were growing :)

Thank you for the encouragement!
