### ISSUE TITLE
Inscriber does not cause Block Updates thus cannot work with Hoppers

### ISSUE THREAD

**Issue by burdoto** [AppliedEnergistics/Applied-Energistics-2#6718]
### Describe the bug

An Inscriber does not cause Block updates and thus, a Hopper attached to its side does not input once it can receive input.

### How to reproduce the bug

- Place an Inscriber with a Hopper attached to its side
- Input Logic Press to the Inscriber
- Input Gold Ingots to the Hopper
- Wait until first iteration of Inscriber is done
- Inscriber will not pull more Gold from the Hopper
- Neither does a hopper attached to the bottom of the Inscriber pull out the results

### Expected behavior

In the example; the Inscriber should be fed with Gold from the hopper.

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

https://crashy.net/lAFWsrryRTHUIpT7gdXC

**Comment by Technici4n** [comment]
Sounds like a bug with whatever performance mod you're using. Hoppers don't need block updates normally.

**Comment by Technici4n** [comment]
Sounds a lot like #6699

**Comment by burdoto** [comment]
After further investigation, I noticed the Hopper doesn't actually need a Block update, but a full on unlocking sequence to input 1 Item again.
Attaching a redstone clock makes it work again.

**Comment by Technici4n** [comment]
That's still something caused by Lithium.
