### ISSUE TITLE
Server crashes when certain AE2 blocks are moved by Quark or Carpet pistons

### ISSUE THREAD

**Issue by Random832** [AppliedEnergistics/Applied-Energistics-2#6719]
### Describe the bug

The server crashes in AE2's world tick subsequent to Quark placing our tile entity in a new location.

### How to reproduce the bug

- Build a multiblock AE2 structure (a single unpowered pylon was enough to trigger the bug)
- Move one of the blocks with a piston (I pulled it with a sticky piston to reproduce)

### Expected behavior

Either the block should refuse to move or it should cope with it somehow.

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/Random832/da3db95710348095778770942096baaf

**Comment by Random832** [comment]
I was able to reproduce the crash with spatial storage - i created a 2x2x2 spatial storage that removed a middle segment of a 4-block long controller, and that also crashed (though with a different error, it was trying to get a controller block state from an air block)

**Comment by Technici4n** [comment]
Can you try using carpet instead of quark?

**Comment by Mari023** [comment]
this is the result of splitting an me controller using spatial storage, a middle section is inside the spatial storage setup.
the controller has to be powered for the crash to occur.

https://gist.github.com/Mari023/958f87cfde43e16fe59883d3a9abed79

**Comment by Random832** [comment]
Same crash with carpet.

https://gist.github.com/Random832/ea8c93b6e97fb71a9f58de5f6fdf9f7e

The setup was using a sticky piston to pull a block out of the middle of a [three-block long, unpowered] spatial pylon.

**Comment by Random832** [comment]
Additional data points: 

I could not reproduce the spatial pylon issue with spatial storage (on either forge or fabric). I could not reproduce either the spatial pylon issue or the controller issue with Mekanism cardboard boxes.

**Comment by Technici4n** [comment]
We established that this is a bug with these mods. Moving blocks with e.g. Create contraptions does not crash.
