### ISSUE TITLE
Request for low capacity storage with support for more types

### ISSUE THREAD

**Issue by Entoarox** [AppliedEnergistics/Applied-Energistics-2#672]
While working with my AE system, I've found that in certain situations I am, even in the case of 1k cells, quickly reaching the limit of types, while never getting even close to reaching their capacity limits.

So if it is possible, I'd like to atleast see cells with double the type capacity at the cost similar to a 63-type capacity card of the next highest tier.
(Aka a 1k/127type cell, similar in cost to a 4k/63type cell, 4k/127type cell with similar cost to a 16k/63type cell, etc.)
The reverse of this (less types but more storage) would also be welcome if possible, if only so it doesnt feel like a waste of my 64k drive to be dedicated to only 4~5 types simply due to the amount of their resource I have, but are less of an issue because of extra cells.

I honestly dont know if it is even possible to change the amount of item types (and searching the issues did not help me know if anyone requested this before), but if it is, I would be incredibly grateful for it.

**Comment by Kasdar** [comment]
Have you looked at Adjustable ME Storage in Extra Cells?

**Comment by yueh** [comment]
63 types is the maximum size possible as the GUI does not support more slots.
Also who would craft these cells if the normal ones will provide about 3 times the space and 1.5 times the types for about the same resource cost?

Most likely would be something like a 0.25k/256 cell, but that might be already rejected earlier.

**Comment by thatsIch** [comment]
This was already rejected in AE1, 

the oroginal author was under the impression its easy enough to craft up quickly 1k storage cells for this kind of items and hook them up via a ME Drive.

**Comment by Entoarox** [comment]
@Kasdar I had not, after having just looked it up, I cannot find any info about the maximum number of types allowed by it, would you happen to know that?

@yueh I'm rather confused what the type limit has to do with GUI's, my thought was that it might be a limit caused by the NBT format, not some kind of GUI issue, so if you could explain that in more detail I would be gratefull.

@thatslch although I understand the thought, I am currently working in a situation where even a single block space is a premium, hence why I made the request, as effectively wasting 50% or more in capacity for each drive, even with 1k cells, when every bit of block space is valuable, is rather annoying.

**Comment by thatsIch** [comment]
Sounds like a use-case for the file-cabinet of XU. Be careful of overflow though.

**Comment by yueh** [comment]
The cell workbench is limited to 63 items (or multiple of 9) and there is maybe enough space to fit one more row without starting to use scrolling or multiple pages, which in my opinion should be avoid if not absolutely necessary.

Even with only a single item per type, a drive can hold 630 items equivalent of 23 vanilla chests. So quite space efficient.
You could look into other storage options like the filing cabinets @thatsIch mentioned. But the normal ones are, I think, limited to 576 items of the same ID or 1728 unstackable items with the advanced ones.

There is also the spatial IO. A 16x16x16 area should hold about 1.5k drives and you can either throw the cell away so no space wasted or store 27 of them inside a vanilla chest. There is probably nothing beating it in terms of space efficiency.

**Comment by Entoarox** [comment]
@thatsIch I am currently using that, but having issues getting items to try going into that first, am I perhaps overlooking something about how to do so?

@yueh Uuhm, dont you mean 63 at a single item per type? (at 2.33 chests worth of space) Anyhow, I do understand now how a GUI issue could be the problem (I completely forgot about the cell workbench when thinking about AE GUI's), so thanks for explaining that to me!

**Comment by yueh** [comment]
A drive needs 1 block as space and can hold 10 cells. Each cell holds 63 types. So 630 types total.

There might be other limitations, but the cell workbench is the most obvious example.
