### ISSUE TITLE
Please add the loot tables for the skystone chest back into the mod. 

### ISSUE THREAD

**Issue by purejosh** [AppliedEnergistics/Applied-Energistics-2#6720]
### Describe the bug

After updating AE2 recently, I've come to find that all skystone chests are empty. Turns out, as someone has informed me in the Discord, that meteorites were recently revamped to have  a block in the middle, which phases out the skystone chest. 

That's fine and all, I actually appreciate the new approach quite a bit. But here's the thing... I've pregenerated a 10k x 10k world. Every single meteor in the world border now has a chest in the center. And the loot tables are empty now. That's... that's really not good. 

Please, for the server admins who've actually prepared their world correctly, add the loot tables back into the mod. Or, provide an optional datapack to restore the loot tables to the game, should anyone have legacy generated meteors in their world. 

### How to reproduce the bug

Explained above. 

### Expected behavior

Provide loot tables for legacy generated meteors. 

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Fabric

### Crash log

n/a

**Comment by purejosh** [comment]
> 

I'm very aware. I've already fixed this issue on my server, by editing their .jar. However, it's not my responsibility to fix issues with their mod. 

Also, while creating a datapack fixes the issue for me, that does not fix the issues for all other server owners. The only reason I created this ticket was to help the other server owners get a better experience from this mod.

**Comment by Technici4n** [comment]
That's my mistake from when I made the changes. But it's too late now. We are not adding the old system back.

**Comment by purejosh** [comment]
> That's my mistake from when I made the changes. But it's too late now. We are not adding the old system back.

So, users who have pregenerated their worlds when there was chests are now screwed, essentially? I find that distasteful. It may be a decent idea to create a datapack for them and make it available in the Discord, at the very least, should anyone also report the same findings.

**Comment by purejosh** [comment]
To be clear, I'm not asking that you restore the old chest in the center system... that would be silly. I'm just asking that you put the loot tables back in the mod. After all, the loot tables will never be accessed, unless someone finds a skystone chest that's never been opened. No harm, no foul, and you're keeping support for old worldgen. I don't see any possible downside to restoring the old loot table .json back to the mod.

**Comment by Technici4n** [comment]
If you create a datapack and post it on discord we will pin it and link it to others having the same problem.

**Comment by purejosh** [comment]
> If you create a datapack and post it on discord we will pin it and link it to others having the same problem.

Did you remove the ae2:needs_press condition from the mod? I can't get the variable loot conditions working, if that was taken out.

**Comment by Technici4n** [comment]
Yeah it was removed

**Comment by purejosh** [comment]
[AE2 Sky Stone Chest Loot.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/9872369/AE2.Sky.Stone.Chest.Loot.zip)
Restores old-gen meteorite chest loot. Made by purejosh. https://discord.com/invite/X6AsDnqex6
Anyone who wants to have the meteorites that were generated before the Mysterious Cube was implemented to have useful loot in the chests can put this into their datapack folder, and either enable it, or restart their server. 

Here is a verbatim readout for anyone who wants to know the technical details:
```
{
  "type": "minecraft:chest",
  "pools": [
    {
      "rolls": 1,
      "entries": [
        {
          "type": "minecraft:item",
          "name": "ae2:mysterious_cube"
        }
      ]
    },
    {
      "rolls": {
        "min": 1,
        "max": 3
      },
      "bonus_rolls": 1,
      "entries": [
        {
          "type": "minecraft:item",
          "name": "ae2:certus_quartz_crystal",
          "functions": [
            {
              "function": "minecraft:set_count",
              "count": {
                "min": 1,
                "max": 12
              }
            }
          ]
        },
        {
          "type": "minecraft:item",
          "name": "ae2:sky_stone_block",
          "functions": [
            {
              "function": "minecraft:set_count",
              "count": {
                "min": 1,
                "max": 12
              }
            }
          ]
        },
        {
          "type": "minecraft:item",
          "name": "minecraft:gold_nugget",
          "functions": [
            {
              "function": "minecraft:set_count",
              "count": {
                "min": 1,
                "max": 12
              }
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by Technici4n** [comment]
Thanks!
