### ISSUE TITLE
Meteorite compass still points at harvested meteorites

### ISSUE THREAD

**Issue by burdoto** [AppliedEnergistics/Applied-Energistics-2#6721]
### Describe the bug

The Meteorite compass still points to meteorites even after they have been harvested.

### How to reproduce the bug

- Meteorite compass
- Harvest closest meteorite
- bug

### Expected behavior

compass should not point to harvested meteorites

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

not needed

**Comment by Technici4n** [comment]
The compass now points to the closest mysterious cube. If your world was generated using an old version of AE2 that didn't have the mysterious cubes the compass will still be pointing to the old meteorites even if you remove them, but I don't think this is worth fixing as people creating new worlds don't have that issue.

**Comment by burdoto** [comment]
the issue is that now on a larger server that has an older world its merely impossible for me to get ahold of enough certus crystals to build a proper system.

why exactly are certus crystals now meteorite exclusive? i've always been extraordinarily happy with AE, but this change is a true dealbreaker for me tbh

**Comment by Technici4n** [comment]
Certus crystals can be farmed infinitely. If you don't have enough of them (but still found a few) you must be doing something wrong. :P

Essentially, they grow similarly to amethyst - and the growth can be sped up massively using crystal growth accelerators.

**Comment by Sea-Kerman** [comment]
exactly. don't break the flawless budding blocks though, you can only move those with spatial storage (or cardboard boxes) as budding blocks degrade 1 tier when mined

so the minimum you need is 1 certus block and 1 certus crystal, so you can charge the crystal and make the lowest tier of budding block

**Comment by Technici4n** [comment]
Kind of. You can also craft new budding blocks directly. Please find a (mostly up to date) overview of the changes at #6380.
