### ISSUE TITLE
IC2Classic is out

### ISSUE THREAD

**Issue by Speiger** [AppliedEnergistics/Applied-Energistics-2#6722]
### Describe the feature

reference to #5021

### Reasons why it should be considered

"Will be included when IC2" is ported.
Which both are xD

**Comment by Technici4n** [comment]
We could look into an API that allows third party mods to integrate their energy systems with ours - but that would take quite a bit of effort, and the conversion to FE is always an option that we might deem sufficient for now.

**Comment by Technici4n** [comment]
Why close this? I think some API to let you integrate the IC2 enet with AE2 directly would be quite nice.

**Comment by Speiger** [comment]
@Technici4n all AE compat from my side has been canceled until the so hated "Forge feature" is properly supported.

**Comment by Speiger** [comment]
@shartte nah they wanted to do compat on their side. 
Was a friendly reminder from me, but I decided against that, for a few reasons.
