### ISSUE TITLE
Too many items in the system, prevents items from showing up

### ISSUE THREAD

**Issue by AzerJunior** [AppliedEnergistics/Applied-Energistics-2#6725]
### Describe the bug

I can not see or access any items on the ME network but I can put more in, whole system is chunk loaded. channels are correct, there are enough cells. storage drawers are disconnected issues still persists, i take out a few drive and items show up again but placing the drives back into the system causes the problem to happen again.

### How to reproduce the bug

can be replicated with enough items in the system (hundreds of types, millions of items).

### Expected behavior

To be able to see and take items out of my ME system

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/w2uhrLGM

**Comment by FelippeChemello** [comment]
![2022-11-23_17 53 39](https://user-images.githubusercontent.com/29099474/203647418-59dac1b2-2ad5-4b2e-9ab9-57e6bf6da77b.png)
![Screenshot from 2022-11-23 17-57-53](https://user-images.githubusercontent.com/29099474/203647453-21e730f0-93f7-4777-800a-22e733ec4300.png)
![Screenshot from 2022-11-23 17-52-51](https://user-images.githubusercontent.com/29099474/203647469-d981771f-329a-4abb-89ad-57aa8918e4b0.png)
