### ISSUE TITLE
Remove cable pathing between providers and interfaces.

### ISSUE THREAD

**Issue by Kevin-Marsh** [AppliedEnergistics/Applied-Energistics-2#6727]
### Describe the feature

I would like to be able to use a provider to feed into a subnet. The best way would be to dump into an interface with storage buses to sort where it is all going. At the moment the provider and interface cable path through each other taking the interface into the main network when I want it to be on the subnetwork. Removing the pathing between providers and interfaces would break this behaviour and allow for more complex subnetwork design.

### Reasons why it should be considered

This would allow interfaces to be used as subnetwork entry points.

**Comment by Random832** [comment]
If either the provider or the interface is turned into a panel form, or if the provider is in directional mode pointed towards the interface, they will not connect. If this is not adequate to solve your problem please describe your setup in more detail.

**Comment by Kevin-Marsh** [comment]
That would completely solve the issue. It would be more intuitive if the full blocks also had the behaviour since there kind of isn't a reason for a provider and an interface to be next to each other.

**Comment by Technici4n** [comment]
Special casing connections between two specific blocks is not possible with the current implementation, and would make the connection rules even harder to explain. 😅
