### ISSUE TITLE
Ae2 vacuum block

### ISSUE THREAD

**Issue by EnderProyects** [AppliedEnergistics/Applied-Energistics-2#6728]
### Describe the feature

A integrated vacuum block that pulls object inside of the block, or directly to the network, could be filtered using a subnet, or a filter inside the block, for crafting could use a singularity, so in terms of lore it creates a gravitational force that pulls objects inside of it. 

### Reasons why it should be considered

There is not any block in ae2 that can collect blocks ( apart from annihilation plane) and this could come along very well ( like the botania addon) 

### Additional details

For crafting: singularity, me chest, and sky stone blocks

**Comment by Technici4n** [comment]
No, there's already ways to achieve this using the tools available in AE2. If addon developers want to look into this, they can feel free.
