### ISSUE TITLE
Recipe to upgrade crafting storage

### ISSUE THREAD

**Issue by rladenson** [AppliedEnergistics/Applied-Energistics-2#6729]
### Describe the feature

A recipe to turn 1k Crafting Storage into 4k Crafting Storage and the same for each tier up. 

### Reasons why it should be considered

It would be really helpful for upgrading existing systems so you don't have to make it super big or trash the blocks you were already using

### Additional details

Recipe for 4k Crafting Storage could be the same as the recipe for 4k ME Storage Component but with one of the 1k ME Storage Components replaced with the 1k Crafting Storage (and similar for each tier up)

**Comment by EnderProyects** [comment]
You know you can dismantle the blocks to get the components out, right?

**Comment by rladenson** [comment]
I did not know that sorry
