### ISSUE TITLE
Many configuration options are simply broken

### ISSUE THREAD

**Issue by asiekierka** [AppliedEnergistics/Applied-Energistics-2#673]
For instance, you cannot disable dense cables (at least, when I disable them, they're still in the creative tabs - not sure about recipes), and I can't figure out how to re-enable the Eraser and co. after they disappeared in rv2 beta1.

**Comment by thatsIch** [comment]
Then tell us what is broken?

Not sure what the eraser is, but it sounds like an unsupported dev-tool you are talking about.

Also, can you look at the BC issue please

**Comment by yueh** [comment]
No feedback.
