### ISSUE TITLE
Getting Crash

### ISSUE THREAD

**Issue by Daihok41** [AppliedEnergistics/Applied-Energistics-2#6730]
### Describe the bug

I am getting crash with newest fabric version for 1.19.2- 12.8.4

### How to reproduce the bug

Load game with newest AE2 fabric version

### Expected behavior

Game will crash

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/a8cjUkBe

**Comment by 62832** [comment]
This is a problem with MEGA Cells rather than AE2 proper. I'll need to release a hotfix for that add-on fairly soon.
