### ISSUE TITLE
Requesting compatibility with IndustrialCraft's EU/t, which was just recently updated to 1.19

### ISSUE THREAD

**Issue by Maoman1** [AppliedEnergistics/Applied-Energistics-2#6731]
### Describe the feature

[Industrial Craft Classic](https://www.curseforge.com/minecraft/mc-mods/ic2-classic) was just recently updated to 1.19 and I would _deeply_ appreciate if you could make the energy acceptor compatible with its power system.

### Reasons why it should be considered

IC2 was always a huge part of technic pack, feed the beast, etc. It being updated to the latest version of minecraft is kind of a big deal if you ask me. Being compatible with such a major mod is just a good idea.

### Additional details

I would recommend a pretty harsh conversion rate of EU-to-AE since IC2 has solar panels--basically free energy. I was thinking at least 2 if not 4 units of EU equal to 1 unit of AE.

**Comment by Technici4n** [comment]
We don't have plans to support non standard energy systems anymore, but we're happy to work on an API to allow others to add support easily. However, the IC2C dev has no plans to work on AE2 compat from his side, so this is probably not gonna happen before a while. In the meantime, I think IC2C should be able to convert EU to FE, the latter of which AE2 can accept.

**Comment by Speiger** [comment]
@Technici4n any support from my side is linked to you support Capabilities properly.
And since you rather not support it because of a opinion then that's not IC2Classics fault, because in the end you choose not to want support.
