### ISSUE TITLE
Keep the item ID and name consistent

### ISSUE THREAD

**Issue by EvanHsieh0415** [AppliedEnergistics/Applied-Energistics-2#6740]
### Describe the feature

| Change? | Original Name         | (`ID`)                    |  \|   | Changed Name        | (`ID`)                  |
| :-----: | :-------------------- | ------------------------- | :---: | :------------------ | ----------------------- |
| Name/ID | Certus Quartz Crystal | (`certus_quartz_crystal`) |  \|   | Certus Quartz       | (`certus_quartz`)       |
|   :x:   | Certus Quartz Dust    | (`certus_quartz_dust`)    |  \|   | Certus Quartz Dust  | (`certus_quartz_dust`)  |
|   ID    | Certus Quartz Seed    | (`certus_crystal_seed`)   |  \|   | Certus Quartz Seed  | (`certus_quartz_seed`)  |
|   ID    | Certus Quartz Block   | (`quartz_block`)          |  \|   | Certus Quartz Block | (`certus_quartz_block`) |
| Name/ID | Quartz Glass          | (`quartz_glass`)          |  \|   | Certus Quartz Glass | (`certus_quartz_glass`) |
|         |                       |                           |  \|   |                     |                         |
|   :x:   | Fluix Crystal         | (`fluix_crystal`)         |  \|   | Fluix Crystal       | (`fluix_crystal`)       |
| Name/ID | Fluix Dust            | (`fluix_dust`)            |  \|   | Fluix Crystal Dust  | (`fluix_crystal_dust`)  |
| Name/ID | Fluix Seed            | (`fluix_seed`)            |  \|   | Fluix Crystal Seed  | (`fluix_crystal_seed`)  |
| Name/ID | Fluix Block           | (`fluix_block`)           |  \|   | Fluix Crystal Block | (`fluix_crystal_block`) |
### Reasons why it should be considered

In programming languages, consistency is very important
For the addon author of this mod, maintaining uniformity can increase the efficiency of programming

### Additional details

Because my English is not good, so the content is translated by machine, please forgive me if there are grammatical errors.

**Comment by Technici4n** [comment]
The only thing that seems maybe worth renaming is certus quartz blocks. I don't see a reason to change the other names as they are already consistent where they need to be.

**Comment by Technici4n** [comment]
Closing in favor of #6945
