### ISSUE TITLE
Hide fluid inventory of interfaces when using The one Probe

### ISSUE THREAD

**Issue by Sakreton** [AppliedEnergistics/Applied-Energistics-2#6742]
### Describe the bug

![grafik](https://user-images.githubusercontent.com/55781722/198889558-1d54ba49-b9e6-4804-9d0d-841d1ddf562e.png)

### How to reproduce the bug

Look at an interface in extended mode with The One Probe

### Expected behavior

Not showing the appr. 16 quadrillion tanks

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

Not a crash

**Comment by Technici4n** [comment]
Could you provide the TOP configs you are using to have that display?

**Comment by Sakreton** [comment]
[theoneprobe-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/9959802/theoneprobe-client.txt)
[theoneprobe-common.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/9959803/theoneprobe-common.txt)
[theoneprobe-common_SERVER.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/9959804/theoneprobe-common_SERVER.txt)

**Comment by Technici4n** [comment]
Hmmm, at this time we have limited interest in changes to our existing TOP support, and would recommend Jade instead.
