### ISSUE TITLE
appliedenergistics2 for forge in minecraft 1.18.2 requires beta versions of Just Enough Items

### ISSUE THREAD

**Issue by alexMcGarity** [AppliedEnergistics/Applied-Energistics-2#6748]
### Describe the bug

When attempting to load the release version of Applied Energistics 2 in addition to the release version of just enough items, I am unable to get to the menu screen and an error pops up stating that ae2 only supports jei 10.1.4.263 and above, which are currently in beta

### How to reproduce the bug

create a new modpack profile on curseforge and load the release version of Applied Energistics 2 in addition to the release version of just enough items
load up a new instance of this modpack

### Expected behavior

Getting to the minecraft menu screen with no issues

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/YTmRmRJm

**Comment by Technici4n** [comment]
Yes that is known, you can simply update JEI.

**Comment by Technici4n** [comment]
AE2 version 11.6.3 supports JEI 9 again. It will be released in a few minutes.

**Comment by alexMcGarity** [comment]
just saw this, thank you!
