### ISSUE TITLE
disabling paintballs cause NPE

### ISSUE THREAD

**Issue by beepbeat** [AppliedEnergistics/Applied-Energistics-2#675]
after disabling paintballs in the config i always get an NPE whilestarting MC.

Extract of the log file: http://pastebin.com/HjbyTzC9

**Comment by thatsIch** [comment]
I work on a fix to fix them all for once, this is a rather larger update.

**Comment by thatsIch** [comment]
Is fixed with using https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/981

not sure, if this is, how the API should look like though.
