### ISSUE TITLE
Crash when crafting job completes, because of toast notification

### ISSUE THREAD

**Issue by Sakreton** [AppliedEnergistics/Applied-Energistics-2#6750]
### Describe the bug

My game crashed 3 times and this perfectly synchronises with the completion of a crafting job, i cant see the pop up and had no terminal open at the time. Cant confirm ae2 is the cause though, cant reproduce. 

### How to reproduce the bug

Cant reproduce relibably

### Expected behavior

Not crash xD

### Additional details

Playing on a server, Server stays up.
appliedenergistics2-forge-12.8.3

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/Sakreton/cc78000f72d8f69fc4ae3a74bde0cfd8

**Comment by Technici4n** [comment]
Seems to be related to the `ToastControl` mod. Would you mind reporting the issue to its author? I doubt it's on our side...

**Comment by Sakreton** [comment]
Sure can do.

**Comment by Technici4n** [comment]
Closing as it's probably not on our side.
