### ISSUE TITLE
Ability to set name on pattern provider

### ISSUE THREAD

**Issue by johalun** [AppliedEnergistics/Applied-Energistics-2#6756]
### Describe the feature

Currently when you have sub networks for auto crafting the pattern provider show up in the pattern terminal as "AE2 Cable and/or Bus". It would be great if you could set a custom name on the pattern provider that would show up in the pattern terminal, for example "Ore Doubler" or "Steel Factory".

### Reasons why it should be considered

It would make it easier to tell the different pattern providers apart instead of having many rows all named "AE2 Cable and/or Bus".

**Comment by 62832** [comment]
This is already possible by renaming the inventory that the Pattern Provider is facing rather than the Pattern Provider itself.

**Comment by johalun** [comment]
How do you rename an inventory? In my case, there's only storage buses and import/export buses connected to mekanism machines on the sub network. I can't find ways to rename anything there...

**Comment by 62832** [comment]
Just as you would with any regular item, via an anvil or using an inscriber Name Press.

**Comment by johalun** [comment]
Ah I see! Hmm, but what part would I rename in this case? The pattern provider, the me interface connected to the pattern provider, or the storage bus that outputs the input items to the mekanism machine?

**Comment by 62832** [comment]
Whatever sits immediately next to the Pattern Provider as I've already said. In this case, it would be the Interface you mention.

**Comment by johalun** [comment]
Tried it and actually I had to rename the pattern provider. But, it works! Thank you so much for the help :)

**Comment by Random832** [comment]
Renaming the adjacent inventory itself does not currently work [issue #6695], but renaming the pattern provider itself in an anvil does work.
