### ISSUE TITLE
large crafting lag with storage bus+me interface pairs

### ISSUE THREAD

**Issue by jameseck** [AppliedEnergistics/Applied-Energistics-2#676]
Hi,

I'm running my game on a slightly modified version of the dw20 1.0.3 pack for 1.7.10.  Slightly modified means I've added some mods like gendustry, fastcraft, reika's reactorcraft, rotarycraft, geostrata, etc.

I know there was an issue in this pack with binnies mod, but I have the binnies fix mod installed, so I'm no longer seeing any crafting lag in crafting tables - my issue resides solely with the ME crafting terminal.

I've got a fairly large AE2 network, although I'm sure it isn't as large as some.  I've listed all of the elements at the bottom of this post for an idea of how big my network is.

In the ME crafting terminal, If I try and craft a stack of something...anything, say stone bricks, it either times my client out or it takes upwards of 20 seconds to craft a stack of bricks.  Note that this is not using the network to craft, this is just right clicking in the me crafting terminal to manually craft something.

I've narrowed the problem down my use of sub-networks.
I had all my storage cells on a super soaryn drive, hooked up to the main network with two storage bus+me interface pairs. I am/was also using me interface+storage bus to attach sub-networks for things like autocrafting.  6 alloy smelters, each with an me interface and a level emitter for crafting the enderio alloys.  I also had 6 sag mills and a number of other machines configured in a similar way.

I've replaced the me interface+storage bus pairs with p2p tunnels or direct cables to a controller instead and the lag seems to have completely gone - crafting a stack of items is now almost instant.

Is anyone able to comment on this?  Is it intended for there to be a penalty to attaching sub-networks in this way?  Or have I discovered a bug?  It feels kinda cheaty to use sub-networks in this way as it significantly cuts down on the number of channels (and therefore controllers you need.

Please let me know if you require any further information.

8 16k crafting storage
7 4k crafting storage
4 64k crafting storage
16 crafting co-processing unit
8 crafting unit
4 crystal growth accelerator
1 dense energy cell
2 energy acceptor
8 inscriber
1 me chest
7 me controller
1 me crafting terminal
7 dense cable blue
119 dense cable fluix
20 me drive
17 me export bus
12 me glass cable fluix
1 me import bus
39 me interface (full block)
10 me interface
1 me interface terminal
1 me io port
15 me level emitter
1 me pattern terminal
2 quantum link chamber
16 me quantum ring
1 me security terminal
10 me smart cable blue
208 me smart cable fluix
42 me smart cable green
12 me smart cable red
1 me wireless access point (32 upgrades)
152 molecular assembler
15 p2p tunnel me
16 quartz fiber
116 64k storage cells

**Comment by Cisien** [comment]
It would help a lot if you could get a snapshot using visualvm, it comes with the jdk.

**Comment by jameseck** [comment]
I've modified all of my current system so I can't easily get a snapshot now.
When I have time I'll try and replicate it in a test world.

**Comment by yueh** [comment]
No feedback.

**Comment by joshricker** [comment]
I can absolutely confirm this issue, and that it is still prestin in the rv2.beta build 10. This issues has been driving me crazy, but after seeing this post i removed my repeating net works and its MUCH better now. Its still kinda laggy with large amounts or crafting, maybe 3-4 secs of server lag if i fill my inventory with coal blocks for example. But when my network was as it was i was getting 2-5 mins of the server just locked up it i tried the same thing. Even just one stack via a right click in a crafting tremal was about 15 secs. He is a snapshot of a said 2-5 min lock up. http://puu.sh/gzbM1/b948ed5c05.nps
