### ISSUE TITLE
[from discussion in Discord] add input filtering to inscriber

### ISSUE THREAD

**Issue by Sea-Kerman** [AppliedEnergistics/Applied-Energistics-2#6768]
### Describe the feature

I assume this means only let valid recipes be put in by automation

### Reasons why it should be considered

see https://discord.com/channels/922828438274986004/922829733132124200/1039468991573413889

**Comment by Sea-Kerman** [comment]
a possible addition to this would be to allow automation to put 2 items in each slot, so that there isn't downtime between a craft finishing and the next set of ingredients being inserted, when using slow-polling item logistics like AE2 busses that poll only every second instead of pipes that poll every few ticks.

https://user-images.githubusercontent.com/41390862/207300467-95dec4bd-c124-498a-b30b-4f781430c15b.mp4

Using a hopper, which waits a bit under half a second between operations, goes a bit faster.

**Comment by Technici4n** [comment]
Implemented in #6958 alongside other inscriber changes.
