### ISSUE TITLE
Fabric 1.18.2

### ISSUE THREAD

**Issue by SaffireLeviathan** [AppliedEnergistics/Applied-Energistics-2#6769]
### Describe the feature

Honestly just wondering if there is a compatible version to work with fabric on 1.18.2, couldn't find a file anywhere  

### Reasons why it should be considered

Fabric good. 
In all seriousness I would like to add it to a current modpack but i can't find the available files to load.

**Comment by Sea-Kerman** [comment]
https://modrinth.com/mod/ae2/version/fabric-11.6.2
