### ISSUE TITLE
Memory card does not work with shield

### ISSUE THREAD

**Issue by uhloin** [AppliedEnergistics/Applied-Energistics-2#6772]
### Describe the bug

Place p2p block (for example on the ground), get shield to left arm (as usually), get memory card to main arm, press crouch+right click... result is "Memory card cleared".

If free left arm from shield, press crouch+right click... result is "New device configuration created..."

Please fix this. I lost huge amount of time with attempts to understand why memory card works in one mye world and does not work in another.

### How to reproduce the bug

-

### Expected behavior

This should not be dependent from shield.

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

-

**Comment by mindforger** [comment]
From the Debug Template:
>If it is not a crash report, you can hold F3+C for over 10 seconds to force one. This provides with more details to reproduce it without needing to manually acquire them.

**Comment by uhloin** [comment]
Here it is 

[crash-2022-11-12_09.58.43-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/9994265/crash-2022-11-12_09.58.43-client.txt)

**Comment by Technici4n** [comment]
Thanks for the report. This is a Forge bug. A workaround will be in the next release until Forge fixes it.
