### ISSUE TITLE
Channel issue when setting up P2P network

### ISSUE THREAD

**Issue by Kangy1103** [AppliedEnergistics/Applied-Energistics-2#6773]
### Describe the bug

Channels seem to be being duplicated or maybe even tripled when setting up a standard P2P network.

Mod Version: appliedenergistics2-forge-11.6.4

### How to reproduce the bug

Make a P2P network as in the screenshots below

![image](https://user-images.githubusercontent.com/42292756/201476377-e15a72b7-ecae-4058-acf9-1a2aa670ee33.png)

Each branch has 4 channels on the smart cable. When you connect 1 you branch it registers 4 channels, connect another branch and each smart cable registers 8 channels on each branch

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/42292756/201476464-0f7e3e8a-773f-4fc9-871a-71c489daa4ac.png">

Connect another set of 4 (should be 12 channels at this point) and it overloads the smart cables

<img width="967" alt="image" src="https://user-images.githubusercontent.com/42292756/201476491-2819ae53-8655-4b3c-bdb7-3952c1a2912a.png">

### Expected behavior

12 channels should be being sent through the dense cable but instead it's overloading the cable

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/Kangy1103/936d9357a284842388b7325c5d60b43a

**Comment by Technici4n** [comment]
That's because you're using an ad hoc network (i.e. without a controller), which is limited to 8 channels regardless of cable placement.

**Comment by Kangy1103** [comment]
> That's because you're using an ad hoc network (i.e. without a controller), which is limited to 8 channels regardless of cable placement.

I knew I was forgetting something stupid! Thanks!
