### ISSUE TITLE
Can't create cobblestone circuit molds in Sky Factory 4

### ISSUE THREAD

**Issue by J-Dog1922** [AppliedEnergistics/Applied-Energistics-2#6776]
### Describe the bug

It lets me place them in the inscriber, but nothing happens

### How to reproduce the bug

Nothing actually happens I can't craft it.

### Expected behavior

The creation of cobblestone circuit mold, but nope, nothing...

### Additional details

It may be unsupported, but its the only version that exists...

### Which minecraft version are you using?

1.12 - UNSUPPORTED

### On which mod loaders does it happen?

Forge

### Crash log

none

**Comment by Technici4n** [comment]
Unsupported means unsupported.

**Comment by mindforger** [comment]
Besides the version, there is no AE2 native item like a cobblestone circuit mold, that is a modpack issue
