### ISSUE TITLE
Rei Category 1.19.2

### ISSUE THREAD

**Issue by iglee42** [AppliedEnergistics/Applied-Energistics-2#6778]
### Describe the bug

I tried to look at all the recipes in rei but when I clicked I crashed

### How to reproduce the bug

Try to look all recipes with Rei

### Expected behavior

Fix this bug

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/VGWyLEvZ

**Comment by Technici4n** [comment]
Will be fixed in the next release (tonight).
