### ISSUE TITLE
"Glitching" Items

### ISSUE THREAD

**Issue by Elvarion** [AppliedEnergistics/Applied-Energistics-2#678]
appliedenergistics2-rv2-beta-4

Sometimes when you wrench facades/panels they decide to fly away into blocks and keep going for quite some time. Ive found facades on the surface and my base quite far underground.

This only seem to happen when there is a block above the cable the facade/panel is placed upon. Also I think its only localized to facades in the ceiling.

**Comment by thatsIch** [comment]
And this happens also with AE2 only? Never seen such thing happening

**Comment by Elvarion** [comment]
Confirmed with only AE2 rv2 beta 4

Take a look at these, you should be able to reproduce it
http://gyazo.com/5ab5197c81924c3edd5f99d1e319b216
http://gyazo.com/e85dc050b8463aa467c28889710be756

**Comment by yueh** [comment]
That is vanilla behaviour, not sure if we can really prevent it.

**Comment by Elvarion** [comment]
Alright, well if there is nothing to do about it then it cant be helped :p
Thanks for the help nonetheless!

**Comment by yueh** [comment]
There are actually some things we can try, just not sure if this can prevent every possibility.
Items spawning inside blocks will always float upwards through solid blocks until they reach a free block.

We could for example be a bit more intelligent about where to spawn them. That might then be similar to the current behaviour or they might for example spawn below the floor and falling somewhere.

Maybe take the player location into account if possible?

**Comment by Elvarion** [comment]
Perhaps a suggestion. Extra Utilities has the angel block. When broken it goes into your inventory directly. That would be somewhat useful. Since you are breaking the facades for a reason

**Comment by Cisien** [comment]
The methon that thermal expansion used, where when wrenching conduit inside of the normal pickup radius for the player would place the conduit in the inventory, while dropping normally if the player is too far away.

**Comment by yueh** [comment]
I am not sure about a built-in magnet mode.

Spawning it towards the player instead of letting it float/glitch through solid blocks is probably a good change. But I think there should still be the risk of losing an item to the void or lava, if you remove them carelessly (as with any other block).

**Comment by RAnders00** [comment]
It could work so it does not simply bounce off like vanilla block breaking does, but instead spawn a item entity that only moves downwars? Normally when you mine a block the item bounces out of the block into a random direction, but it could be done so the item does not bounce off but instead just drops - Pretty much the same behavoiur is already implemented for removing conduits. Just Shift-Wrench some and you will see they do not bounce around. I'm guessing this could help?

**Comment by yueh** [comment]
It does not really change anything about it.
The spawn location is the important part. If it then moves upwards, downwards or bounces around is not really relevant.

The main issue is spawning it inside an already existing block (the cable) and here does the minecraft physics take over and push it upwards until it finds an empty block.
So a downwards direction will still force it to behave exactly the same, except if it can glitch through a very thin floor and then fall down (into lava, the void, etc). Not a real improvement.

**Comment by thatsIch** [comment]
Why not just place the wrenched part into the players inventory

**Comment by RAnders00** [comment]
woops, looks like you Commented and closed it by accident, @thatsIch .

**Comment by thatsIch** [comment]
I closed it, cause I dont think, there should be any special interaction, 
because its how Minecraft Physics work.
