### ISSUE TITLE
holding Charger crashes game on fabric

### ISSUE THREAD

**Issue by Suyashtnt** [AppliedEnergistics/Applied-Energistics-2#6780]
**Describe the issue**
When I hold the charger in the game, it instantly crashes. I expect to be able to hold and place the charger without an instant crash

**Environment**
https://mclo.gs/Sa8q6tf game log

**Comment by Technici4n** [comment]
This is caused by the `dynamiccrosshair` mod. You can report the issue to them.

**Comment by Suyashtnt** [comment]
> This is caused by the `dynamiccrosshair` mod. You can report the issue to them.

Ok, thanks
