### ISSUE TITLE
Can't access Me System while being owner

### ISSUE THREAD

**Issue by GunterJauch138** [AppliedEnergistics/Applied-Energistics-2#6789]
ME System doesnt work i cant craft deposit or withdraw items

I build a SkyFactory 4 server been grinding for 3 month now and the Me System stop letting me draw items craft or deposit items i build a security terminal but im the only one playing. However i can deposit and access the items with a wireless Terminal but thats it. I want to craft i need it and allways accesing it over the wireless terminal sucks. I tried adding my biometric card to the secutity terminal but since im the Owner it doesnt work. I also tried breaking the security terminal but that still doesn't give me access

Im playing on SkyFactory 4 with EnderIO placed in additionally

**Comment by GunterJauch138** [comment]
I removed EnderIO since i just got it. But it didn't change a thing

**Comment by Technici4n** [comment]
That's a weird bug. We don't support 1.12 anymore, but I would suggest having a look at this fork: https://github.com/PrototypeTrousers/Applied-Energistics-2.
