### ISSUE TITLE
Autocrafting Logging

### ISSUE THREAD

**Issue by joshmackey** [AppliedEnergistics/Applied-Energistics-2#680]
I've got a series of crafting-enabled export buses and level emitters set up to ensure I always have a certain amount of material at the ready.

I haven't been able to catch it do it while I'm online, but since that particular area is covered by a chunk loader, it appears that when I'm offline, *something* is continuously requesting material to be crafted. For example, I ended up with over 500 pulsating iron (EnderIO) when the level emitter is set to to turn when under 30.

Is there a way to log all autocrafting requests in some way? A debug mode that outputs it to a text file maybe?

------------------
After writing the above, I found CraftingLog in the config file. Will this do what I want?

**Comment by thatsIch** [comment]
No, the crafting logging feature is not that advanced yet. 
Maybe check for chunk boundaries, maybe the level emitter gets deactivated by unloading and thus keep the export bus on exporting.

**Comment by joshmackey** [comment]
The level emitter and export bus are located in the same chunk. However, I increased the chunk loaders range to see if that solves the problem. I'll report back if so.

Any change of a recipe that combines the level emitter and export bus into one so I don't have to build odd contraptions?

**Comment by thatsIch** [comment]
No, we want to keep every part as atomic as possible to enable more creative and free builds in comparison to 10000 different parts which do just a single specific job.

**Comment by Cisien** [comment]
This sounds a lot like a chunk loading issue like thatsIch pointed out. If your storage unloads then the level emitter thinks there are 0 items in stock and issues a request to craft more

**Comment by yueh** [comment]
Inactive, reopen if the issue is still appearing and you have some way to reproduce it.
