### ISSUE TITLE
Upgrading disks

### ISSUE THREAD

**Issue by w3ricardo** [AppliedEnergistics/Applied-Energistics-2#6811]
### Describe the feature

I think that there should be a recipe for creating a bigger disk (like 4K) from a smaller one (1K) that preserves the contents of the disk.

### Reasons why it should be considered

When you start with AE you don't have a lot of resources and have to manually craft stuff, so you start with small disks. This would make it easier to upgrade to bigger disks, even if it only works in the vanilla crafting table.

### Additional details

I have seen some mods that let you upgrade a backpack without losing the contents of the backpack.

**Comment by mindforger** [comment]
also there is a block to move data between drives and/or the network
