### ISSUE TITLE
Make certus quartz decay less punishing

### ISSUE THREAD

**Issue by Technici4n** [AppliedEnergistics/Applied-Energistics-2#6817]
I don't think requiring silk touch for the automation setup adds much. I suggest instead:
- (flawless) always degrade by 1 level
- (not flawless, silk touch) don't degrade
- (not flawless, not silk touch) degrade by 1 level

**Comment by Sea-Kerman** [comment]
Would also allow you to get a bit cleaner operation of the auto-replacing, as the annihilation plane storage setup would be able to tell the difference between damaged and regular certus blocks
