### ISSUE TITLE
pattern encoding terminal

### ISSUE THREAD

**Issue by Artem77770** [AppliedEnergistics/Applied-Energistics-2#6821]
### Describe the bug

https://user-images.githubusercontent.com/115878617/207118003-b4a63936-a3d1-42a2-b184-1313c105e482.mp4

### How to reproduce the bug

-

### Expected behavior

-

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

-

**Comment by Artem77770** [comment]
appliedenergistics2-11.7.0

**Comment by cplir-c** [comment]
This looks like an item duplication bug for cards.

Put a card in the network tool.
Open the pattern terminal, shift click the card into the terminal, and toss the network tool on the ground. Now do it again.

Suddenly you have duplicate cards in the system.
