### ISSUE TITLE
Issuing A Crafting Job From A Non-AE Terminal

### ISSUE THREAD

**Issue by Nividica** [AppliedEnergistics/Applied-Energistics-2#683]
Hello AE2 Team,
I have recently been working on integrating the auto-crafting system with Thaumic Energistics, and have run into an issue dealing with issuing crafting jobs from my terminal.
When attempting to start a crafting job from my terminal, I am running into a crash originating from the GuiCraftConfirm button list. When the constructor is called, the field 'OriginalGui' is not set, [Lines 90 to 100](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/63e375f2087c8c1f1f1aae94c17163b1bb9deb19/src/main/java/appeng/client/gui/implementations/GuiCraftConfirm.java#L90). Because this field is not being set, the check on [line 122](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/63e375f2087c8c1f1f1aae94c17163b1bb9deb19/src/main/java/appeng/client/gui/implementations/GuiCraftConfirm.java#L122) fails and the cancel button gets added to the button list as null. This in-turn causes a NullPointerException to occur from "net.minecraft.client.gui.GuiScreen.drawScreen" when it gets the button.

My original thought was to remove the check on line 122 so that the cancel button is never null, then put the check on line 169. If the OriginalGui is null in that location then just close the gui, if not continue as usual. However after testing with these changes I ran into another issue where after pressing Start, the gui does not close but instead only disables the start button (see attached image), but the crafting work does get performed.

Another idea I had was adding a method to the ITerminalHost interface to retrieve the original gui, such as "getHostGUI()". However this may have further reaching repercussions than I am aware of.

Any help with the issue or suggestions would be greatly welcome, as I have hit a roadblock.

![craftwindow](https://cloud.githubusercontent.com/assets/1585989/5604813/3d05639c-93a3-11e4-9322-f8a23be89c58.jpg)

**Comment by thatsIch** [comment]
Looking at the code, the `this.OriginalGui` must be one of the following. So I think we can assume to set it `private final` and throw an `Exception` there, since it should not happen. That way, you can remove the null check.

**Comment by Nividica** [comment]
Would that allow me to call on the GUI from my terminal without leading to a crash?
More specifically the "ITerminalHost te" argument that is being passed into the GuiCraftConfirm constructor is of class type "AEPartArcaneCraftingTerminal" due to having been called from said terminal. As such none of the existing four checks will pass and the 'OriginalGui' field will always remain null.

**Comment by yueh** [comment]
I am not sure about it, as this is happening asynchronously. So you should not be able to catch the exception on your side and handle it. It would probably be closing the GUI completely instead of dropping back to your terminal.

The best way would probably be a new API to let addons register a custom `IGuiHandler` or a specific subclass for AE2 and add a mapping from a tileentity to a GUI. But that would not be a small change on our side.

**Comment by Nividica** [comment]
Indeed, the asynchronous nature of it is where I am having trouble. After I call on "Platform" to open the GUI execution passes out of my control. Calling method posted below. The crafting amount window functions as expected, however when you set how many you want it immediately crashes without ever presenting the user with the confirm gui.
I could indeed live with it just closing the GUI when Cancel or Start is pressed, but my aforementioned patch leaves the confirm GUI just hanging around when Start is pressed.
I am still tracing the code trying to find an 'elegant' way to solve the issue, but I'll admit, I get terribly lost moving through the packet code.

```java
public void onClientRequestAutoCraft( final EntityPlayer player, final IAEItemStack result )
	{
		appeng.util.Platform.openGUI( player, this.arcaneCraftingTerminalPart.getHostTile(),
this.arcaneCraftingTerminalPart.getSide(), GuiBridge.GUI_CRAFTING_AMOUNT );

		if( player.openContainer instanceof ContainerCraftAmount )
		{
			ContainerCraftAmount cca = (ContainerCraftAmount)this.player.openContainer;
			cca.craftingItem.putStack( result.getItemStack() );
			cca.whatToMake = result;
			cca.detectAndSendChanges();
		}
	}
```

**Comment by Nividica** [comment]
Shortly after writing that I found what I was looking for. It seems the packet invokes the [startJob](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/63e375f2087c8c1f1f1aae94c17163b1bb9deb19/src/main/java/appeng/container/implementations/ContainerCraftConfirm.java#L295) function of the container.
I will play with the code and see if I can at least get it to the point where it will close the GUI once the job has been started.

**Comment by yueh** [comment]
The usual issues of using internal code, which was never designed to work in another mod.

As you are already using internal code, you might want a bit more risky and subclass whatever you need. But I have no idea what bugs this will create and it can break with every new build.
You will probably also need to duplicate much of our code, which could also open up some license issues from LGPL to MIT (if someone would care about it)

**Comment by Nividica** [comment]
Fixed with commit https://github.com/Nividica/ThaumicEnergistics/commit/a2ae38edda55ee6db406f2f40ec12a781a8250fb of ThE.
