### ISSUE TITLE
Harmonize Import/Export Bus Filter Slot Count with Storage Bus

### ISSUE THREAD

**Issue by shartte** [AppliedEnergistics/Applied-Energistics-2#6835]
There's no real reason that import/export buses have only a single filter slot as opposed to the 9 that the storage bus has by default. Same for formation plane filtering.

The UI should be harmonized, which has the side-effect of greatly increasing the default filter slot count to 9.

**Comment by dokastho** [comment]
I'll be taking up development on this issue, deliver by 04/14

**Comment by ramidzkh** [comment]
Any progress @dokastho?

**Comment by dokastho** [comment]
Not yet, I'm working on #6833 still, it's taking me a little while to get familiar with the code base

**Comment by Technici4n** [comment]
If you need help feel free to post a message on the Discord server in #dev-talk
