### ISSUE TITLE
Water breaks waterlogged cables 

### ISSUE THREAD

**Issue by EnderProyects** [AppliedEnergistics/Applied-Energistics-2#6836]
### Describe the bug

If you place watter in a waterlogged cable this will break the cable

### How to reproduce the bug

Watterlogg a ME cable, then place another bucket to the cable, it will dropp de cable

### Expected behavior

To dont break the cable lol

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

*

**Comment by Technici4n** [comment]
Can't reproduce on Fabric. Can someone reproduce on Fabric or Forge?

**Comment by Technici4n** [comment]
Can't reproduce on Forge either.

**Comment by EnderProyects** [comment]
I just read about this in dev talk, and well, although I've been absent for half a year, I have to say that this continues to happen

**Comment by Random832** [comment]
Only happens when placing water against an adjacent solid block to the space the cable is in, not when clicking on the cable itself.
