### ISSUE TITLE
Interface is not supplied by a Storage Bus on an Interface

### ISSUE THREAD

**Issue by dBHI-zz** [AppliedEnergistics/Applied-Energistics-2#6847]
### Describe the bug

If I connect a subnet via Interface->Storage Bus, the Storage Bus does not access the items in the Interface in order to stock other Interfaces.

### How to reproduce the bug

![image](https://user-images.githubusercontent.com/3235171/208267656-2bf1e8fd-6b8b-468e-88ec-296281d79db9.png)
Provide an item in the left Interface and configure the right interface to stock this item.

### Expected behavior

The Storage Bus accesses the items in the left Interface and stocks it into the right interface.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/jKAVcMST

**Comment by dBHI-zz** [comment]
That does not matter. Both variants do not work.

**Comment by Technici4n** [comment]
You can increase the priority of the right interface to prevent this issue.

I think this behavior is reasonable, but we could perhaps only make it apply if the source interface already has the items it wants? (so in this case since the left interface is not configured it would still allow extracting anything).

**Comment by dBHI-zz** [comment]
Priority does not change anything, because there are 2 networks. Is there a way, to allow items from interfaces if they are in a different network or in the same network with lower priority?

**Comment by Technici4n** [comment]
You need the left interface to:
1) be configured (even with a junk item), and
2) have lower priority

**Comment by dBHI-zz** [comment]
Oh, thank you, that does work.

**Comment by Technici4n** [comment]
Perfect! Please leave it open.
