### ISSUE TITLE
Wireless Access Point receiving any item through pipes.

### ISSUE THREAD

**Issue by LucasSilvaPeres** [AppliedEnergistics/Applied-Energistics-2#6856]
### Describe the bug

I placed my WAP connected to a Pipe from Pipez and soon after I placed some ender pearls inside a barrel and they got transferred inside the WAP. Then I tested with cobblestone and was able to place an entire stack of cobblestone just fine and it worked like if it was Wireless Boosters.

### How to reproduce the bug

1. Place a barrel/chest with a pipe connected and configured to pull.
2. Place a Wireless Access Point connected to the same pipe
3. Place any item inside the chest/barrel
4. Item will end inside the WAP and will work exactly as a Wireless Booster.

### Expected behavior

Wireless Access Point shouldn't be able to receive items through pipes or at least should only receive Wireless Boosters

### Additional details

I'm playing on the version 12.9.1, FTB App on the modpack ATM8 on the latest version of the modpack.
Below are some prints showing it working
[How the barrel and the WAP are placed](https://prnt.sc/X_IzPsm6wnX9)
[Cobblestone inside the WAP](https://prnt.sc/WVB5p_MnS15h)
[171m from the WAP](https://prnt.sc/KzOMWmFREc8H)
[Being able to open the terminal](https://prnt.sc/1ZvZXuG3Li7O) It might look like I'm closer but it's due to the FOV distortion

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/yaCBPeVr

**Comment by Technici4n** [comment]
I can't reproduce this. Does it also happen with hoppers?

**Comment by Technici4n** [comment]
(or other automation such as Mekanism pipes, export busses, etc...)

**Comment by LucasSilvaPeres** [comment]
It's been a while but iirc I tested it with Pipez and Mekanism, didn't try with hoppers or export busses. Unfortunately I had to format my computer recently and lost this world so I can't test it again.

**Comment by Technici4n** [comment]
I see. I'll test on the Forge branch and see if it happens there.

**Comment by Technici4n** [comment]
Hi, I cannot reproduce this, so I'll have to assume another mod is interfering with us.
