### ISSUE TITLE
Request: Satellite  Crafting (Like in LogisticPipes)

### ISSUE THREAD

**Issue by ignisthedragon** [AppliedEnergistics/Applied-Energistics-2#686]
How about satellite crafting like at logistic pipes? Where players are able to tell an interface where to put in which item while autocrafting, not just all items in one inventory.

There are so many processed crafting recipes which require more than one machine to be used. The new processors are an great example for this problem or filled energy cell frames from TE. It would be really nice to have a kind of satellite interface, which can handle those multi-steps-craftingjobs. 
Maybe there could be an satellite interface, which can linked with an memory card to the main interface. Then the only other thing needed is a kind of special processing pattern, where you can configure exactly which item is where to put. Or there could be an upgrade card which allow an interface to act as an satellite interface.

And yes I know, there are some ways to make it work, for example to let the interface put all the items into a chest and sort them for example with enderio conduits or make some parts passive, but I think a satellite interface would be much easier to handle.

**Comment by yueh** [comment]
This is already supported. Use another network with a chest + import bus or interface as buffer and just use it like any other pipe mod.
