### ISSUE TITLE
Sustainable Fluix

### ISSUE THREAD

**Issue by Senteth** [AppliedEnergistics/Applied-Energistics-2#6866]
### Describe the feature

In previous versions of the mod, once you'd created your initial Fluix Crystal, you could craft Fluix seeds with sand + Fluix Crystals and slowly expand your supply.

With the rework, the only way to expand your supply is by crafting Fluix crystals directly, (1 Certus Quartz + 1 Redstone Dust + 1 Nether Quartz = 2 Fluix Crystals) which can quickly get expensive on the Nether Quartz.

You can transform Fluix Dust into a Fluix Crystal by adding a Charged Certus Quartz and tossing both in a pool of water, but this doesn't allow for growth since it only produces a single Fluix Crystal. 

I propose that the number of Fluix crystals obtained by combining a Fluix Dust and a Charged Certus Quartz in a pool of water be upped to 2 instead of 1, allowing for sustainable farming of Fluix once again. (it also brings it in line with the behavior for combining a Charged Certus Quartz with a Certus Quartz Dust in a pool of water, since you get 2 Certus Quartz out of it)

### Reasons why it should be considered

Sustainable farming, and bringing expected behavior of the transformation of Fluix Dust in line with that of Certus Quartz Dust.

**Comment by Technici4n** [comment]
> In previous versions of the mod, once you'd created your initial Fluix Crystal, you could craft Fluix seeds with sand + Fluix Crystals and slowly expand your supply.

This was never an intended feature before 1.17. Pure crystals were not supposed to be ground back to dust 1:1 but other mods broke that by adding recipes. -_-

Making Fluix sustainable would be too OP for my tastes. The main ingredient of Fluix (Certus) is already sustainable, and redstone and nether quartz are not hard to obtain in large quantities.

**Comment by mindforger** [comment]
I agree on the fluix, but maintaining a supply of certus is an issues imho, in the past you could craft a certus block from pure crystal and grind it back to dusts with loss but at least something above 100% output ... Imho budding quartz is nice and all but if you dont know, you will loose one meteorite cluster after another before realising you have to regenerate them .. This happened to almost all the people once that i know personally ... Having the flawless budding crystals NOT degenerate would be a large improvement for people not familiar with the mechanic. You can build your collecting setup around a meteorite and leave it as is with limited supply but maintenance free or pick up the budding blocks, making them mortal in the process requiring maintenance but having most efficient supply ... Maybe even lower the growthrate of a flawless budding block to encourage automation

**Comment by mindforger** [comment]
Another idea, when getting close to a NOT flawless budding crystal award an achievement „cracks are forming“ with the description hinting to think about regenerating and a second acievement „falling apart“ when there is a budding block in its last before final state hinting an urgent need to regenerate

**Comment by Random832** [comment]
easier advancement trigger might be when breaking a bud attached to a regular [depleted] certus block.

**Comment by mindforger** [comment]
yeah sounds better

**Comment by Technici4n** [comment]
Yeah there's some things to be done (See #6817). There's also the WIP guidebook that will hopefully make the whole concept clearer.
