### ISSUE TITLE
Charger eats my quartz

### ISSUE THREAD

**Issue by SmoothBrainInsomniac** [AppliedEnergistics/Applied-Energistics-2#6867]
### Describe the bug

After placing a hopper under the cherger it just eats quartz. Ive removed the hopper. Even went 1000 blocks away and tried it but the quartz just gets eaten

### How to reproduce the bug

Place hopper under the charger

### Expected behavior

A nice automated charger so I could go and do other stuff

### Additional details

none

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

none

**Comment by Technici4n** [comment]
Which version are you on? This bug was fixed ages ago in early 1.19 releases.

**Comment by SmoothBrainInsomniac** [comment]
nvm the problem solved itself. Sorry for the trouble.
