### ISSUE TITLE
Mattercannon that shoots singularities

### ISSUE THREAD

**Issue by Liamvant** [AppliedEnergistics/Applied-Energistics-2#687]
Just what the title says, and they would be way more powerfull than the paintballs :D

**Comment by Liamvant** [comment]
Edit: wrong thread, may be deleted

**Comment by ruifung** [comment]
And what would it do? Spawn a black hole ala ICBM? Or just a really high mass projectile?

**Comment by Cisien** [comment]
Yeah, no. AE I not a weapons of mass destruction mod. Perhaps some other mods can find a creative use for them, but AE is not that mod
