### ISSUE TITLE
useTerminalUseLargeFont location error

### ISSUE THREAD

**Issue by shane04111** [AppliedEnergistics/Applied-Energistics-2#6875]
### Describe the bug

When I turn on useTerminalUseLargeFont, the position of the number is no longer at the bottom right of the item
![image](https://user-images.githubusercontent.com/57738232/210269635-830511a3-d2d3-4e5b-9699-ebcf778868ce.png)

### How to reproduce the bug

1. Open client.json 
2. Set useTerminalUseLargeFont to true
3. save client.json
4. open the game

### Expected behavior

The number should appear in the bottom left corner of the item

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://mclo.gs/2FVDCaE

**Comment by Cjsah** [comment]
except fix
