### ISSUE TITLE
Modpack crashes because of AE2

### ISSUE THREAD

**Issue by PossessedDevil** [AppliedEnergistics/Applied-Energistics-2#6877]
**Describe the issue**
Tried to open a world, crashed while opening and went back to launcher

**Environment**
[crash-2023-01-01_22.14.44-server.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/10334161/crash-2023-01-01_22.14.44-server.txt)

- Environment:

**Comment by Technici4n** [comment]
This crash doesn't make sense, this is likely caused by a bad interaction with another mod?
