### ISSUE TITLE
Inscriber not rendering properly

### ISSUE THREAD

**Issue by Trent2Luigi** [AppliedEnergistics/Applied-Energistics-2#6888]
### Describe the bug

The Block only shows three parts of the texture. Attempts to break in survival, the game crashes. the block still works normally.

### How to reproduce the bug

Place the block down. Congrats, you done it.

### Expected behavior

The block is displayed like the item version.

### Additional details

![2023-01-09_19 29 39](https://user-images.githubusercontent.com/117208010/211442312-a697f947-0fee-42e6-a6f7-23f69dbf977a.png)

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/Trent2Luigi/23b7bf6f3ccb84df0b88149d8ec9d62b

**Comment by Trent2Luigi** [comment]
And yes, i tried without shaders.

**Comment by Sea-Kerman** [comment]
Optifine is incompatible with many mods, including AE2
