### ISSUE TITLE
Z-fighting in Dense/Smart Cables

### ISSUE THREAD

**Issue by corhean** [AppliedEnergistics/Applied-Energistics-2#6889]
### Describe the bug

Z-fighting occurs with dense/smart cables when they are connected with a cable facade at the same level.
![image](https://user-images.githubusercontent.com/70460842/211462323-5842e1e1-f728-4dba-ad1f-35e87b7b1ed0.png)
![image](https://user-images.githubusercontent.com/70460842/211462459-0fddaa63-d620-4d6b-88fa-5787af428d6e.png)

### How to reproduce the bug

make a dense cable add a cable facade on top of it, then add more dense cables (smart or otherwise).  connect any device/cable to the side that causes the cable to change to the connector-mode shape.  

### Expected behavior

the cable facade and the cable should not z-fight.  Unsure if there is a standard in development for which should take precedence.

### Additional details

part of ATM7 tts; forge 11.6.1-beta

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

n/a

**Comment by Mari023** [comment]
I think this might be similar to #4963
