### ISSUE TITLE
Illuminated Panel looking like ME Controller

### ISSUE THREAD

**Issue by fundor333** [AppliedEnergistics/Applied-Energistics-2#689]
Can you make an Illuminated Panel looking like ME Controller?

**Comment by ruifung** [comment]
This would be nice. The ME controller would make a excellent decorative surface. Especially if it can be powered to glow.

**Comment by yueh** [comment]
Illuminated Panels are currenty smaller than a full block, so the texture itself will not fit.
But there should be already a feature request about making them connecting textures similar to Formation/Annihilation Planes.

But the main reason against having some cosmetic/fake controller blocks is that they should be visually as distinct as possible. So not forcing you to attach a cable or break them to see if it is really a controller or a fake. I know Waila exists, but this is just another optional mod and we cannot assume it as always installed.

**Comment by Cisien** [comment]
I would like to get feedback on having a controller-like texture for these. Animated, connected texture, etc.

I believe people are requesting the controller block because that is an easy example.

Maybe we could even use this on a new panel to show off channel usage (and possibly activity)
