### ISSUE TITLE
Enable Autocraft to partially or fully ignore the NBT of the finished items.

### ISSUE THREAD

**Issue by KennysDaywalker** [AppliedEnergistics/Applied-Energistics-2#6893]
### Describe the feature

The ME Pattern Provider should get an upgrade slot for Fuzzy Card.
This activates the option (Fuzzy Comparison) for the inserted elements whether they are accepted for the Autocraft.

Example: You order a bow and put a used bow with any enchantments into the ME Pattern Provider which is then accepted as the crafted item.

### Reasons why it should be considered

This would make it possible, for example, to automate crafted Quantum Entangled Singularities. (Built a contraption that makes them, but the ME system won't accept them). There are quite a lot of mods with such items, which are always unique!

**Comment by Technici4n** [comment]
This cannot be implemented with the technical changes I have in mind for the autocrafting system. The calculation step needs to know which **exact** items will be produced.
