### ISSUE TITLE
"Crafting job completed" toasts do not work if the terminal is in a trinket / curio slot using ae2wtlib

### ISSUE THREAD

**Issue by Mari023** [AppliedEnergistics/Applied-Energistics-2#6898]
originally reported on the ae2wtlib repo: https://github.com/Mari023/AE2WirelessTerminalLibrary/issues/183
however, this isn't really fixable in ae2wtlib alone.

ae2wtlib would need some way to hook into PendingCraftingJobs#hasNotificationEnablingItem and check for wireless Terminals in trinket / curio slots

https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/a0336ccd2f73191319586564df6caa5be2ae13e6/src/main/java/appeng/client/gui/me/common/PendingCraftingJobs.java#L63-L77

**Comment by Technici4n** [comment]
Idea: just add an event that AE2 uses to detect additional ItemStacks... Something like this: https://github.com/Technici4n/Powah/commit/b265271790e4425d70426ebceab724725431e40c but on `master` and with a name more suited to AE2.
