### ISSUE TITLE
Compatibility request: fire a PlayerInteractEvent.LeftClickBlock from PartLeftClickPacket

### ISSUE THREAD

**Issue by desht** [AppliedEnergistics/Applied-Energistics-2#6905]
### Describe the feature

Please see https://github.com/FTBTeam/FTB-Mods-Issues/issues/634 for some background.

In summary, because AE2 uses a custom packet to send player left click events on the Conversion Monitor to the server, protection mods such as FTB Chunks don't get a chance to see the click on the server, and thus can't protect the clicked block from interaction.

A viable fix would be to fire a `PlayerInteractEvent.LeftClickBlock` from the server side packet handler and only proceed if that event doesn't get cancelled.

### Reasons why it should be considered

This would help integration with chunk protection mods, where SMP players want to keep their stored inventory safe. I'm aware that AE2 has its own security system, but it would be desirable to allow other protection mods to work here too.

**Comment by Technici4n** [comment]
Seems reasonable to me. :+1:

**Comment by desht** [comment]
If you're referring to `Level#mayInteract()`, all that does is check for spawn protection and world border.

**Comment by desht** [comment]
Pretty sure you still use that, but it's not sufficient on its own for a mod like FTB Chunks, where players have specific chunk claims...

**Comment by desht** [comment]
I noticed the above commit - thanks for that.  But is that Fabric-only?  Not sure how your multi-platform stuff works, but I don't see an equivalent Forge event being fired.

**Comment by Technici4n** [comment]
We use separate branches. It will be converted to the Forge event when we get to porting it for 1.19.4, no worries.

(We can't support anything other than 1.19.4 due to limited dev resources)
