### ISSUE TITLE
Auto-crafting does not work if processing pattern contains items and fluids simultaneously

### ISSUE THREAD

**Issue by ZekIzLoupriora** [AppliedEnergistics/Applied-Energistics-2#6906]
### Describe the bug

Auto-crafting does not work if pattern contains items AND fluids as inputs.

### How to reproduce the bug

**Current MultiMC setup:**
![image](https://user-images.githubusercontent.com/38569354/213610988-a554219a-f402-40b1-b41f-0664e7e277e9.png)
![image](https://user-images.githubusercontent.com/38569354/213611032-2c3066a2-c789-410a-9d0b-afe3181ae58a.png)

-----------------------------------------------------------------------------------------------------------------------------------------
**Steps to reproduce:**
Encode a processing pattern with some fluid and item as inputs:
![image](https://user-images.githubusercontent.com/38569354/213609607-7bf86752-a920-4a33-abff-66687a433c72.png)
Then place it in a pattern provider connected to some kind of fluid tank and a chest:
![image](https://user-images.githubusercontent.com/38569354/213609823-03b85c53-dae7-417f-a8fa-15df89a58dc7.png)
![image](https://user-images.githubusercontent.com/38569354/213609854-f6606155-95a0-4f93-a22f-3033958c65ec.png)
And request an auto-craft for it:
![image](https://user-images.githubusercontent.com/38569354/213610166-c98d805c-cb3e-437c-b57a-dd7e03efd98d.png)
Time in the crafting cpu that is doing that task will be going up infinitely:
![image](https://user-images.githubusercontent.com/38569354/213610213-295d112d-0963-45d3-a3b2-ac82df4dccbc.png)
after ~20 seconds:
![image](https://user-images.githubusercontent.com/38569354/213610249-62760a55-bfa0-41f8-9c83-1ef151df4c9c.png)
And the resources will not be put in any adjacent to pattern provider container, _although will be absent from the network_ until you cancel the task:
![image](https://user-images.githubusercontent.com/38569354/213610344-04035d2a-b0e1-43a4-a2a7-d5fa74b2bfb5.png)
![image](https://user-images.githubusercontent.com/38569354/213610353-fd46d6c2-f317-401b-a555-50300e91e29f.png)
![image](https://user-images.githubusercontent.com/38569354/213610423-a59c1d47-7f7c-47be-876b-8ad33c59e4d9.png)

### Expected behavior

System should put resources in the adjacent to pattern provider containers:
![image](https://user-images.githubusercontent.com/38569354/213610525-839cde17-6366-43f1-b8fe-eee5c6a12de2.png)

### Which minecraft version are you using?

1.19.2 (same bug happens on 1.18.2)

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/bSyQyChi

**Comment by Technici4n** [comment]
It's not a bug, it's just that things can only be pushed to one side, which must be the same for items and fluids.

**Comment by ZekIzLoupriora** [comment]
It is happening when the "output" is one side, too, e.g. import bus to a new ME subnetwork

**Comment by ZekIzLoupriora** [comment]
So, I made this setup with an import bus:
![image](https://user-images.githubusercontent.com/38569354/213771017-b859e676-ee11-430d-95de-d4d4e9e667af.png)
and apparently it does not work either:
![image](https://user-images.githubusercontent.com/38569354/213771091-6dce830d-13af-4588-a817-d5c12fe2e2ac.png)
Directly connecting pattern provider with a cable of different color does not work, because a new subsystem sees contents of an original one:
![image](https://user-images.githubusercontent.com/38569354/213771491-13210c22-e52a-43f1-8f8a-d78d04156056.png)
![image](https://user-images.githubusercontent.com/38569354/213771507-fd451694-ea19-4d35-8364-635449911f41.png)
and this is not the behaviour I am looking for.

Now I'll test it with another mod - Modern Industrialization - on Minecraft 1.18.2 and attach screenshots in an additional comment

**Comment by ZekIzLoupriora** [comment]
So apparently MI pipes can't extract items and/or fluids from pattern provider:
![image](https://user-images.githubusercontent.com/38569354/213773868-7d5e476e-ce71-4905-883d-cde86f125935.png)
![image](https://user-images.githubusercontent.com/38569354/213773900-819ac2ac-e976-4c38-99cb-5cf6d636f588.png)
I can't think of another mod that adds some "universal" storage block or some another solution to this problem

**Comment by Random832** [comment]
The easiest way to solve this problem is to use an interface with a subnet, similar to how you have to deal with machines that require different items to be pushed to different faces.

![image](https://user-images.githubusercontent.com/5147771/213792016-5c0dae45-f617-4c36-95d0-a7fe3cda93b0.png)

**Comment by ZekIzLoupriora** [comment]
> It's not a bug, it's just that things can only be pushed to one side, which must be the same for items and fluids.

    I didn't know that you could rotate pattern provider with a wrench. I still don't quite understand how that works, but thanks for the help, issue closed!
