### ISSUE TITLE
P2P tunnel naming or identification

### ISSUE THREAD

**Issue by cathode** [AppliedEnergistics/Applied-Energistics-2#691]
I'm finding it very tedious to keep track of P2P tunnels when you have more than one or two. It would be great if there was a way to name a P2P tunnel so that you could identify it with the network tool for example.

In fact, giving P2P tunnels a GUI and the ability to manually set their association and direction would be great.

**Comment by Cisien** [comment]
I believe there is already an open feature request asking to make keeping track of p2p easier. I'm on my phone at the moment, so tracking it down is tedious

**Comment by yueh** [comment]
#38, #43, #395 and maybe others.
