### ISSUE TITLE
Incompatibility causes crash on server 1.19.2

### ISSUE THREAD

**Issue by URSFR** [AppliedEnergistics/Applied-Energistics-2#6913]
### Describe the bug

I have made a modpack to play on a server which includes Applied Energistics 2 and DimThread.

### How to reproduce the bug

 By placing the Energy Cell block (which is in the same crash-report) it closes the server and corrupts the world.

### Expected behavior

It is expected that it will not close and not corrupt the server

### Additional details

I have searched with what causes the incompatibility and it is with DimThread
[DimThread](https://github.com/WearBlackAllDay/DimensionalThreading)

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/w40wdxES

**Comment by mindforger** [comment]
https://github.com/WearBlackAllDay/DimensionalThreading/issues/60
