### ISSUE TITLE
crafting order dont work with craft result produced in storage connected by storage bus

### ISSUE THREAD

**Issue by h1503** [AppliedEnergistics/Applied-Energistics-2#6914]
### Describe the bug

The crafting order get stuck forever if the result of the crafting go directly to a storage connected to the network by a storage bus.

Actually i can't send the result of my craft directly into my drawer from functional storage mod.
I made a workaround with buffer chest and importer to use the ME network to send result in the drawer.

### How to reproduce the bug

Create a pattern for a craft like an iron ingot made by a furnace where the result of the furnace is dropped in a chest connected to the network by a storage bus.
Ask the network to craft the iron ingo, it became available in the network but the task is stuck in crafting.

### Expected behavior

The task is completed when the iron ingot became available in the chest connected by the storage bus

### Additional details

This bug is weirder when the request is made by an exporter bus because the result is correctly send in the storage connected by the  exporter bus but the crafting task get stuck forever.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

no crash needed

**Comment by Technici4n** [comment]
This is intended behavior, and we have no plans to change it. Autocrafting works by "intercepting" items as they enter the network - if they never enter the network we can't properly mark jobs as finished.

**Comment by h1503** [comment]
Thx for the response i will use a buffer to send the item to the drawer
