### ISSUE TITLE
Server crash when moving AE2 block entities via Quark pistons

### ISSUE THREAD

**Issue by Tycherin** [AppliedEnergistics/Applied-Energistics-2#6926]
### Describe the bug

When I try to move AE2 block entities using pistons (which is one of the many things Quark enables), the block moves, but then the server crashes with this message: `java.lang.IllegalStateException: The node has already been initialized. Initialization data cannot be changed anymore.`

I tested this with the Drive, ME Chest, and Vibration Chamber blocks. It produced the same error each time. The stack trace calls out ManagedGridNode, so I'm guessing it affects any network-connected block entity.

I reproduced this in an environment with just these mods:
* AE2 - 11.6.4
* AE2 - 11.7 (separate test just to make sure the most recent version didn't fix the problem)
* AutoRegLib 1.7-53
* Quark 3.2-358

### How to reproduce the bug

1. Place one of the block entities listed above
2. Place a piston next to it
3. Use a lever to activate the piston and push the block sideways

### Expected behavior

Presumably AE2 either doesn't generate a crash or tells Quark not to move stuff

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/Tycherin/ab06d5a569d1a723e27d1f2ffc75cff5

**Comment by ramidzkh** [comment]
> or tells Quark not to move stuff

Ask Quark to blacklist AE2 blocks from moving; they're the one breaking that assumption so they should be the careful ones.

https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/6022#issuecomment-1019458615

**Comment by Technici4n** [comment]
This is quark's fault. AE2 block entities are designed to be moveable, up to quark to do it correctly.

**Comment by Random832** [comment]
This is actually a duplicate of https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/6719 - it also happens with Carpet on Fabric, and it's not clear what Quark (or Carpet) is doing wrong [it seems to do the same stuff every tile entity moving mod does]
