### ISSUE TITLE
Can't craft with crafting terminal with TofuCraftReload 1.19.2

### ISSUE THREAD

**Issue by yoshi0123** [AppliedEnergistics/Applied-Energistics-2#6927]
### Describe the bug

crafted items disappear when craft items with using crafting terminal with TofucraftReload

![59f3c4c50f83cb42f0a4d7257461c2c4](https://user-images.githubusercontent.com/16642229/218896846-e3cd3f9e-dca2-47e0-873e-11fc2c2bcbe5.gif)

### How to reproduce the bug

install these mods:
`forge-1.19.2-forge-43.2.0`
`appliedenergistics2-forge-12.9.2`
`TofuCraftReload-1.19-2.3.6.0`

craft with crafting terminal and disappear items
same bug happened with the newer version in 1.19.2 of TofuCraftReload

### Expected behavior

able to craft with it

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/yoshi0123/4fe4c98dd51da4fcfaceb6b2e9eec2b1

**Comment by Technici4n** [comment]
Fixed in TofuCraft apparently.
