### ISSUE TITLE
Fabric: ArrayIndexOutOfBoundsException with Sodium + Indium? Error Rendering Screen

### ISSUE THREAD

**Issue by suerion** [AppliedEnergistics/Applied-Energistics-2#6928]
### Describe the bug

The client from players crash with AIOOBE, we could not reproduce it, it crashe randomly. some player said, it crashed on scrolling, other doesn't aggree of this,

you could look on one Players Crashlog, For me it crash not.

### How to reproduce the bug

We don'T know how do reproduce

### Expected behavior

Client should not crash anymore.

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/xgqbSrem

**Comment by Technici4n** [comment]
Are these players using a specific language with special characters? This crash is related to font rendering... (very strange)

**Comment by suerion** [comment]
we use only english and german, 

ö ä ü? ß could also be? or you mean chinese language?

**Comment by Technici4n** [comment]
Could also be, it's still weird though.

**Comment by Technici4n** [comment]
Ah, I saw the Create comment. Have you ever had the bug since you installed bugjump?

**Comment by suerion** [comment]
I‘m asking the peoples on the server, i had a few days an vaccation. I will come back to you

**Comment by suerion** [comment]
With bugjump on my side, i had fixed the problems,

The Guy with the multiple problems does not tried it yet

**Comment by Technici4n** [comment]
Let's assume it's fixed then.
