### ISSUE TITLE
AE2 converting vanilla recipes to original if my mod Common Sense is downloaded.

### ISSUE THREAD

**Issue by TheaRTGGaming** [AppliedEnergistics/Applied-Energistics-2#6929]
**Describe the issue**
when common sense and AE2 are downloaded the mod AE2 overwrites the vanilla recipe changing code from Common sense to the 
Vanilla recipes.

**Comment by Technici4n** [comment]
We don't overwrite any vanilla recipe.

**Comment by TheaRTGGaming** [comment]
Did you even test it with my mod installed?

**Comment by Technici4n** [comment]
No, I don't have time. I've been modding for years, so I know that we don't break vanilla recipes.

**Comment by TheaRTGGaming** [comment]
well when i have my mod installed with yours, it converts the vanilla recipes to the vanilla recipes. meaning your code overwrites any vanilla changing recipes to only what your mod sets it to

**Comment by Mari023** [comment]
I tried both the fabric and the forge version, and I couldn't find a recipe that was broken

**Comment by TheaRTGGaming** [comment]
Then it must be my end because when i have this AE2 downloaded and Forge version my recipes get over writed

**Comment by TheaRTGGaming** [comment]
I am using forge 1.19.2 Version 43.2.3

**Comment by Random832** [comment]
I believe forge has problems with datapack loading order sometimes, try modifying the datapack order with commands after creating your world with the final mod list to make sure that vanilla and forge are early in the list.

**Comment by TheaRTGGaming** [comment]
or just recreate my mod playlist. because here it is
[Realistic Craft 1.0-1.0.0.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/10762946/Realistic.Craft.1.0-1.0.0.zip)

**Comment by Technici4n** [comment]
Please stop asking us to spend our time fixing your issue.
