### ISSUE TITLE
operators cannot place fluix cable on systems owned by someone else

### ISSUE THREAD

**Issue by Kurokodairua** [AppliedEnergistics/Applied-Energistics-2#6940]
### Describe the bug

Playing together with a friend (both operators) we didn't see the need to add me on our ME system security since I can access and craft on it without any issues. 
Wanting to expand on it we noticed I (not the owner of the system) cannot place any fluix cable on it / connect any new machines. 

### How to reproduce the bug

On a ME system owned by a different player, an operator tries to place a fluix cable. 
Similar to non-operators the cable just pops right off even though the operator-status should override any security settings.

### Expected behavior

Operators can physically edit ME systems without any security issues similar to [this](https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/5697) fix 

### Additional details

Happened while playing Stoneblock3 (mod version 11.7)

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/vfn5R7CF

**Comment by Technici4n** [comment]
The root issue seems to be that `SecurityService#hasPermission(int, SecurityPermissions)` does not check whether a player is OP. Sadly, it cannot do so if the player is not online. A compromise would be to require the player to be online. On it...
