### ISSUE TITLE
Crash with Better Furnaces Reforged

### ISSUE THREAD

**Issue by KateReller** [AppliedEnergistics/Applied-Energistics-2#6941]
### Describe the bug

When placing an ME Storage Bus on a Better Furnace (i.e Diamond Furnace), the game crashes.

### How to reproduce the bug

1. Place diamond furnace.
2. Place ME Storage bus
3. Experience a crash.

### Expected behavior

The game should not crash when placing a storage bus on a diamond furnace.

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Fabric

### Crash log

https://mclo.gs/4Al285y

**Comment by mindforger** [comment]
next time please only post the crash report, the whole log usually is impractical

>

  | #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\********\Apps\Prism\instances\qhot-fabric\.minecraft\crash-reports\crash-2023-02-25_21.55.48-server.txt
-- | --

**Comment by Technici4n** [comment]
This appears to be a Better Furnaces bug, please report it to them.
