### ISSUE TITLE
Game crashes when using JEI on rendering Item: "fluorescent_tube"

### ISSUE THREAD

**Issue by TheaRTGGaming** [AppliedEnergistics/Applied-Energistics-2#6942]
### Describe the bug

when scrolling threw JEI menu. when you get to the AE area it frezzes the game then crashes it.

### How to reproduce the bug

test JEI with AE and search threw the menu.

### Expected behavior

Game will freeze then crash.

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/TheaRTGGaming/51de3462f9db5e8edf74a1e11f9f5c36

**Comment by mindforger** [comment]
remove or try to update optifine, wrong mod repo btw.
