### ISSUE TITLE
Spatial I/O needs a lot more work.

### ISSUE THREAD

**Issue by simon12mm** [AppliedEnergistics/Applied-Energistics-2#6943]
### Describe the feature

It feels very unrefined, and i keep coming up with problems regarding storage cells on my FTB Minecraft Server. I mean, seriously? There's not even a way to clear/format a storage cell? I cannot use any size for one except the size of the first use?

### Reasons why it should be considered

It would make this feature, that currently feels more like a gimmick, into something that could actually be used often and for good reasons

**Comment by Technici4n** [comment]
I am closing this as a duplicate of #6642. I agree that spatial IO is a bit underwhelming at the moment, we will see what I can do about it when I find the motivation to work on it. :)
