### ISSUE TITLE
Can data transfer through Crystal Growth Accelerators?

### ISSUE THREAD

**Issue by Hazmatik** [AppliedEnergistics/Applied-Energistics-2#695]
I have my automated crystal growing set up using an interface connected to an item dropper with a redstone clock on top, and a transfer node from extra utilities connected to another interface on the bottom. As shown in the image (bottom view) the smart cable connected to the bottom of one of my CGAs is showing a channel being used and the other part of the smart cable going up to the top is showing zero. I'm assuming the channel the one connected to the CGA is showing is for my interface at the top. It just seems strange that data would transfer through the CGA and would default through that cable as opposed to the other cable running up to the top side that is providing power to them. I'm playing in the Karma modpack on the ATLauncher. AE2 version RV1-Stable 1

![2015-01-04_22 58 28](https://cloud.githubusercontent.com/assets/8119393/5609104/4f3b7f8e-9465-11e4-9bde-69aa1993e452.png)

**Comment by acters124** [comment]
Unlike the charger, inscriber, and the molecular assembler. This block allows connections to go through, and, if I can guess correctly, AE's path finding chooses Machines to go through instead of cables.

**Comment by yueh** [comment]
This is actually wrong. Any AE2 machine maybe besides the manual grindstone transmits 8 channels.

Rule of thumb: If a cable connects, it transmits channels.

**Comment by acters124** [comment]
Thanks for a new >"Rule of Thumb"
