### ISSUE TITLE
ME interfaces dont pull things from any chest

### ISSUE THREAD

**Issue by shivachirr** [AppliedEnergistics/Applied-Energistics-2#696]
ok i dont know what happening but for some reason when i go to do my auto crafting with a ae chest the interface just port the things into the chest but it dose dont pull out the finished item it has worked in the past fine it a bug that is annoying as hell to me because i cant fully do my inscriber auto crafting because of it it been happening for the a while now and i cant find a good way around it. its also not pulling from even the vanilla mc chest

**Comment by Cisien** [comment]
Screen shots of setup, please

**Comment by AlgorithmX2** [comment]
Me Interfaces don't pull things - Import buses do?

**Comment by Cisien** [comment]
Note to self, don't review issues when tired. Yeah, intended behavior.

**Comment by shivachirr** [comment]
normally no but when used in autocrafting it should unless it was changed with out any infomation posted or that i noticed

**Comment by Cisien** [comment]
the interface has never pulled items out of inventories.

Either the thing doing the crafting ejects into the interface, or you use an import bus to pull the item out of the thing doing the crafting.

I closed this issue because the behavior is intended, there is no reason to keep this issue open.
