### ISSUE TITLE
Spatial Anchor is not working in Fabric

### ISSUE THREAD

**Issue by moshner** [AppliedEnergistics/Applied-Energistics-2#6961]
### Describe the bug

I have installed a spatial anchor in my system and it isn't loading chunks. It says Loading 0 chunks in 1 worlds. Spanning: 5 chinks in 1 worlds.

### How to reproduce the bug

World of Pannotia Modpack version 13.0.0-HT
Create AE2 system
Add Spatial Anchor

### Expected behavior

Loads chunks

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Fabric

### Crash log

it is not crashing

**Comment by Mari023** [comment]
this is a known issue, it just isn't implemented since there is no chunk loading api in fabric

**Comment by moshner** [comment]
Is there a list of known issues somewhere so that i don't report more?

**Comment by Technici4n** [comment]
This was known but not reported as far as I know, so please leave it open until it's addressed in some way. If you don't find an issue on github already, then it's fine to report it!

**Comment by Sea-Kerman** [comment]
There’s a PR about this I think https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/6527

**Comment by Technici4n** [comment]
Implemented in #7011.

**Comment by Minenat69** [comment]
What was the version of AE2 ? I'm having the same issue and i'm trying to figure if it is because of Fabric. Also, if it is corrected, can you tell me the version of AE2 (or Fabric) in which this was treated ?
