### ISSUE TITLE
IllegalStateException with "Can't modify the empty stack". Causes full server crash on start.

### ISSUE THREAD

**Issue by BobyTheDragon** [AppliedEnergistics/Applied-Energistics-2#6965]
### Describe the bug

Me and some friends currently have a "bricked" server running All The Mods 8 1.0.13 with Applied Energistics 2 12.9.2 and Bigger Reactors 0.6.0-beta.6. The server now goes into a constant boot loop as it errors out on `Description: Ticking GridNode`. `java.lang.IllegalStateException: Can't modify the empty stack`.

This seems to have been caused while I was attempting to use ME Import Buses to import Bigger Reactors steam into the ME system, and then export steam that directly into a Bigger Reactors turbine. 

I seem to be getting AE2 errors. But I suppose it could be a Bigger Reactors issue? I am not technically advanced at understanding the inner workings of minecraft mods and forge. 

We have tried to restart the server a few times using forges `removeErroringBlockEntities` and `removeErroringEntities` but unfortunately to no avail so far. But every restart it does seem to change which node location it reports. In saying that the Bigger Reactors has 6 ME Import Buses.

### How to reproduce the bug

Using AE2 Import Bus connected directly to a fluid output port on a Bigger Reactors Reactor. AE2 system has a ME Fluid Drive that has been configured to only accept Bigger Reactors steam.

### Expected behavior

AE2 pulls steam from the Bigger Reactors system and stores it.

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/VAEXuC0i

**Comment by Technici4n** [comment]
This is very strange. I am pretty sure something is wrong on Bigger Reactors' end, but I have no idea what.

**Comment by BobyTheDragon** [comment]
No worries, I do have an update. After using Amulet (MCEdit clone) we managed to recover the world after deleting the Bigger Reactors machine as well as the ME import busses. Unfortunately the two chunks it was spread across got completely screwed in terms of modded items and blocks. But better to remake two chunks then tor restart a whole world haha. 

I might bring up this to the Bigger Reactors github as well. They mayyy have some sort of idea.

**Comment by Technici4n** [comment]
Confirmed to be an issue with Bigger Reactors, I talked with its author. See https://github.com/BiggerSeries/Phosphophyllite/issues/30.

**Comment by Technici4n** [comment]
Oh I just saw your reply, good that you managed to fix it. Should be fixed in BR soonish. :)

**Comment by BobyTheDragon** [comment]
Sweet as. Sorry to pester you guys with the issue haha.
