### ISSUE TITLE
Colored Portable Cells

### ISSUE THREAD

**Issue by UmbralSurvivor** [AppliedEnergistics/Applied-Energistics-2#6966]
### Describe the feature

The portable cell's "terminal" should be colorable by crafting it with a dye, similarly to placing a Terminal on a colored Cable.

### Reasons why it should be considered

This would allow the player to more easily differentiate the portable cells in their inventory, if multiple were present.

### Additional details

Given that all Portable Cells share the same footprint, the texture could be an "overlay" over where the screen is placed. This would lessen the amount of textures needed to be made (16 additional textures total vs 16 new textures per Portable Cell type)

**Comment by Technici4n** [comment]
An interesting idea from Discord is to allow coloring them like leather armor. The same system could be applied to memory cards too.
