### ISSUE TITLE
Formation Plane Crash with Flawed Budding Certus Quartz

### ISSUE THREAD

**Issue by Miku0Sama** [AppliedEnergistics/Applied-Energistics-2#6969]
### Describe the bug

When a Formation Plane on a sub-network attempts to place a Flawed Budding Certus Quartz Block on a dedicated server, it crashes the server. Also potentially soft-locks the server from launching forcing to restore a back-up of the world.

### How to reproduce the bug

1. Place a Formation Plane and an Import Bus on a isolated sub-network (no other devices and powered by quartz fiber)
2. Have the Formation Plane attempt to place a Flawed Budding Certus Quartz Block
3. Crash

### Expected behavior

Not crashing

### Additional details

My exact setup was identical to the one shown in this video: https://youtu.be/8xBNwD4UVpw?t=755

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Fabric

### Crash log

https://gist.github.com/Miku0Sama/686ee998bb034fe1756c1672516246f0

**Comment by Technici4n** [comment]
FTB Chunks bug, please report it to them.

**Comment by desht** [comment]
Ideally, your fake player object shouldn't really be using a null `connection` field, but I'll add an extra null-check to Chunks in any case.

**Comment by Technici4n** [comment]
You can also use the architectury isFakePlayer check
