### ISSUE TITLE
Some p2p connections failing to update

### ISSUE THREAD

**Issue by Ahkronn** [AppliedEnergistics/Applied-Energistics-2#698]
using RV2 Beta 7 build

I started getting the issue that certain p2p lines stopped working. Connecting a direct line to the cable from the controllers, wait a bit and then disconnect it will make the p2p work again.

Error logs go as follow:
[05:06:10] [Server thread/ERROR] [AE2:S/]: Error: appeng.api.exceptions.FailedConnection : null
[05:06:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: appeng.api.exceptions.FailedConnection
[05:06:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at appeng.me.GridConnection.<init>(GridConnection.java:67)

For a full server error log regarding this, please check the following link:
https://dl.dropboxusercontent.com/u/102174086/fml-server-latest.log

**Comment by Ahkronn** [comment]
Tried connect the p2p into a different Controller: didn't solve
Tried changing the p2p tunnels, controllers, cables...: didn't solve

**Comment by yueh** [comment]
Did it cause any crash as the log is incomplete in this regard?
If not it mostly looks like an error which could be suppressed and maybe added as a better logging message.

The stacktrace indicates this is an issue with your security permissions on the networks you want to tunnel (not the tunneling network). I can currently only imagine two options.

1. You are trying to tunnel two networks with different owners/security stations
2. You are using EnderIO ME conduits

**Comment by Ahkronn** [comment]
I am using EnderIO conduits, yes, but afaik the only one that interacts directly with my ME system would be the one at the energy acceptor, that hasnt cause any troubles until now.

Not linking two networks at all, although I had to break my old security station as it stop recognizing me at some point.

**Comment by Ahkronn** [comment]
OK, based on what you said I tried something that fixed my system.
I removed my Security station and all's working now.
I guess something weird happened when my security station "broke"...

**Comment by Ahkronn** [comment]
Add: note that I don't have another security station anywhere and only 3 or 4 p2p's stop working when I add one

**Comment by yueh** [comment]
Just the EnderIO ME conduits, the power ones should be ok.

The ME network usually assume it is fully chunkloaded, maybe some parts did not recieve the updated settings because they where not loaded.

But the error log should clearly be better.

**Comment by Ahkronn** [comment]
My all base was loaded, rechecked that before posting.
As said, when my security terminal stopped accepting me after a server restart, I broke it and re-placed it. That's when the issues started, not that I think about it. Removing the security terminal allows my all system to work perfectly (all the 20 p2p connections hehe)

**Comment by Cisien** [comment]
In your world directory, there is an applies energistics folder, can you post the settings file that is in that directory?

**Comment by Ahkronn** [comment]
@Cisien 

https://dl.dropboxusercontent.com/u/102174086/settings.cfg

**Comment by Zaflis** [comment]
I'm using DW20's pack 1.0.3, which comes with rv2-beta-1, and am also experiencing this bug.

Here's a test scenario to reproduce: http://imgur.com/CKybW1n
3 crafting terminals, of which blue one is not online. The P2P tunnel that is getting channel from other P2P tunnel is not getting powered up. I checked the changelogs up till beta-build 7 but they don't seem to tackle this issue.

**Comment by yueh** [comment]
This is intentional and also the documentation states you cannot nest P2P channels recursively.
