### ISSUE TITLE
I opened the inscriber and my server crashed

### ISSUE THREAD

**Issue by FizonHeXd** [AppliedEnergistics/Applied-Energistics-2#6986]
### Describe the bug

I placed down the inscriber just after making it when I tried to open it my server crashed immediately any ideas this is the crash report 

### How to reproduce the bug

Opening the inscriber

### Expected behavior

Server to crash

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/AdXQ6mif

**Comment by Technici4n** [comment]
Uninstall dimthreading, that kind of mod is broken by design.

**Comment by mindforger** [comment]
just as a sidenote
> This crash report has been saved to: /home/minecraft/multicraft/servers/server1808971/default/./crash-reports/crash-2023-03-22_22.53.39-server.txt
