### ISSUE TITLE
Fluid dupe with tanks/storage busses

### ISSUE THREAD

**Issue by billbertking1** [AppliedEnergistics/Applied-Energistics-2#6987]
**Describe the issue**

ATM8 1.0.13/ATM7: To The Sky Any/Before; if you put a minimum of 2 storage busses around a tank (Industrial Foregoing works best) you can put 1 bucket in, pull (if 2 storage busses) 2 out, put 2 in, pull 4 out, 4 in, 8 out, etc. thus duping the fluid. I expect it to work as items do, showing 2 items and only able to pull 1 out.

**Environment**

- Environment: atm8 1.0.13/atm7 to the sky: any version tested. Attached crash log is in atm8 1.0.13
[crash-2023-03-23_13.08.53-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/11054446/crash-2023-03-23_13.08.53-client.txt)

**Comment by Technici4n** [comment]
Hi, does this also happen with tanks from other mods (Mekanism for example)?

**Comment by billbertking1** [comment]
Yes, however the ultimate tank only got up to 64,000mb of fluid rather than getting completely full.

**Comment by Technici4n** [comment]
Thank you for the info, that was indeed an AE2 bug. Fix will be released whenever we have time to backport.
