### ISSUE TITLE
Different Mechanics for Channels

### ISSUE THREAD

**Issue by maxqia** [AppliedEnergistics/Applied-Energistics-2#699]
I wonder if instead of fully using the channel all the time, AE devices would only use up the channel as they are doing something (like importing/exporting).

**Comment by Cisien** [comment]
the channel is needed so the controller or other devices on the network know that the device is there. This would also cause all sorts of usability issues and unpredictable behavior when the line gets oversubscribed.

**Comment by asgdfagdsfg** [comment]
Just remove the shit from the mod, and the problem is gone, we can FINALLY play the mod properly again...
