### ISSUE TITLE
Game crashes on activating Spatial Containment Structure with ME Controller in it

### ISSUE THREAD

**Issue by SomeoneRand0m** [AppliedEnergistics/Applied-Energistics-2#6990]
### Describe the bug

As it says, the game crashes when I attempt to activate a Spatial IO controller while there's an ME Controller inside the pylons. Nothing is crossing the border of the pylons, or even brushing up next to them, for that matter.

### How to reproduce the bug

Create a Spatial Containment Structure, make a (most likely active, unsure) ME Controller within, activate it.

### Expected behavior

It does not crash when I do this. lol

### Additional details

This is for Minecraft 1.19.2, not .3, if that makes any difference. Also, I was using a moderately complex p2p subnetwork setup within the spatial pylons, which might contribute, frankly I have no idea. 
Additionally, I am still able to log back into the world after my game crashes, the structure successfully gets transported, and it does not crash when I bring it back into the overworld.

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/SomeoneRand0m/70d0533f75cf7021860b46f3a61d537d

**Comment by dokastho** [comment]
I tried replicating this bug with your AE2/FML version and was unable to cause a crash, maybe this is an ae2things issue?

**Comment by ben-mkiv** [comment]
i can confirm the issue, and also run into it. it's only happening like 1/10 tries...

here's the crash report which looks similar:
https://mclo.gs/xQL0Pjh

**Comment by Technici4n** [comment]
Hello, could you perhaps post a picture of the setup? I am unable to reproduce this issue or understand what is causing it.

**Comment by uberswe** [comment]
I encountered the same issue in 1.18.2. Here is the crash report

https://gist.github.com/uberswe/11640ccb8066dfdfa15708e0da803814

Initially it worked fine with this single ME controller which just has a spatial anchor and some power.

![2023-04-17_11 38 28](https://user-images.githubusercontent.com/1903284/232446886-ea2e4b5a-baf9-4897-9aa4-bf6efb1b3453.png)

But when I added my main ME controller with all my drives, assemblers, cpus and whatnot as you can see below it will crash the server randomly when I send the entire 16x16x16 area into the Spatial Storage or take it out. Seems to be about a 50% chance.

![2023-04-17_11 38 40](https://user-images.githubusercontent.com/1903284/232447381-f990ef3b-76ef-4d8b-a2fb-2970f2ae6715.png)
![2023-04-17_11 43 37](https://user-images.githubusercontent.com/1903284/232448028-a30af9a1-04c2-4153-8c69-cad96295ae2e.png)
![2023-04-17_11 45 39](https://user-images.githubusercontent.com/1903284/232448445-6be6bd33-4155-46d4-867b-5e0b84ebffce.png)

 - Removing the P2P tunnels made no difference.
 - I removed a corner of each quantum link to disable them, I had 4. Also no difference.
 - As the player, it makes no difference if I stand inside or outside the Spatial Storage area

**Comment by Technici4n** [comment]
Hi, could you generate a crash report with the very latest version of AE2? (11.7.2)
I added a bit of debug info to help track this down.

**Comment by uberswe** [comment]
> Hi, could you generate a crash report with the very latest version of AE2? (11.7.2) I added a bit of debug info to help track this down.

@Technici4n Here is a crash report for 11.7.2 https://gist.github.com/uberswe/23df393a21cb44202c4ccc94c8abd236

**Comment by Technici4n** [comment]
@uberswe Thanks. What are the positions of the controller inside the original world and inside the spatial dimension? (More or less)

**Comment by ben-mkiv** [comment]
![](https://i.imgur.com/Z6VviG1.png)

![](https://imgur.com/TJljiFd)


Main Network:

![](https://imgur.com/6fQ1pJ8)


"Sub" Network (green cables connected with glass fiber to the controller)

![](https://imgur.com/u1CeOZj)

**Comment by Technici4n** [comment]
Sorry I meant the x,y,z coordinates.

**Comment by uberswe** [comment]
> Sorry I meant the x,y,z coordinates.

In the overworld: -2133,84,-870
In the spatial dimension: -311,77,-314

**Comment by uberswe** [comment]
I can reproduce this issue in a single player world without any other mods

https://gist.github.com/uberswe/71145f49e362229ab0854b754c102157

It has happened both times I have tried it now

![2023-04-20_06 11 32](https://user-images.githubusercontent.com/1903284/233256256-8e673953-91f8-42b2-b0aa-ebe527b12698.png)

Here is my entire instance: [AE2 Test.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/11279719/AE2.Test.zip)

**Comment by Technici4n** [comment]
Thanks a lot for providing that test world, I couldn't have figured it out without that zip! :)

(Fix will be out for 1.19.2 in the next release, in a few weeks most likely.)

**Comment by coaber** [comment]
This also happened on my 1.18.2 modpack, after following a tutorial on how to teleport yourself in the spatial storage field using another ME network all was fine until i actually activated the field, game froze and had to actually force shut it down, after going back in the game and trying to bring it back in the main world, it kind of worked, except any tile entity that had nbt data stored was deleted

**Comment by Technici4n** [comment]
I will also backport it to 1.18.2.

**Comment by coaber** [comment]
Thanks!
