### ISSUE TITLE
Crafting terminal stop working

### ISSUE THREAD

**Issue by Nanteszin** [AppliedEnergistics/Applied-Energistics-2#6994]
### Describe the bug

The wireless crafting terminal stop working when I order crafiting something, its don´t open the item window.
But when I craft another wireless terminal and link it, this new one works again

### How to reproduce the bug

when I order to craft something the wireless terminal stop working

### Expected behavior

.

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

don´t have crash

**Comment by mindforger** [comment]
Press and hold F3 and C to force a crash and subsequent crashlog, you did not specify ANY usefull modlist or game versions ... Imagine some car mechanic asking what kind of vehicle you have, your equivalent answer would be „it's green“ :D
