### ISSUE TITLE
ME Interface to Formation Plane Dupe

### ISSUE THREAD

**Issue by Twisted6** [AppliedEnergistics/Applied-Energistics-2#6998]
### Describe the bug

Item not being removed from ME Interface after being placed by a Formation Plane

### How to reproduce the bug

The setup is ME Storage > Export Bus > ME Interface > Formation Plane. https://imgur.com/a/Af2SFXV

### Expected behavior

Item is removed from ME Interface when placed by Formation Plane

### Which minecraft version are you using?

1.19.2 (AE2 v12.9.2)

### On which mod loaders does it happen?

Fabric

### Crash log

-

**Comment by Technici4n** [comment]
FTB Chunks compat issue. See https://github.com/FTBTeam/FTB-Mods-Issues/issues/722.
