### ISSUE TITLE
ME Interface terminal doesn't show encoded patterns (items) without using shift button on keyboard.

### ISSUE THREAD

**Issue by dcwdamon** [AppliedEnergistics/Applied-Energistics-2#700]
Maybe it was a add-on, but previously when you put a pattern in an Interface terminal you can see without hitting "shift" what he makes, but when I updated the mod to Rv2 it doesn't work anymore.

You need to press shift if you want to see what he can make IN a interface.
Is this a config thing or a mod thing? Or is this a bug.

Thanks for helping.

Damon

Mods that interact with AE2
AE2 Version: rv2 beta 7
NEI 1.0.3.77
NEI addons 1.12.3.11
Forge 1236

**Comment by yueh** [comment]
We already had a report for it and it was some other mod interfering with it.
I think it was Reika's DragonAPI. If you do not use it, it can be really any other mod. Most likely some NEI related.

**Comment by dcwdamon** [comment]
I am using DragonAPI, I will test it now without the mod and see if it works or not, if not, I will look for other mods, thanks for the quick reply.

**Comment by dcwdamon** [comment]
I can't fix it with latest DragonAPI and latest AE2. Is there a way to fix it? Thanks.

**Comment by ReikaKalseki** [comment]
This is an ASM conflict. I doubt there is a fix.
