### ISSUE TITLE
Auto crafting not exporting items when ready back to the system

### ISSUE THREAD

**Issue by Rafa7046** [AppliedEnergistics/Applied-Energistics-2#7009]
### Describe the bug

When i build a simple auto crafting system if i request a item to be build in a Molecular assembler the item is crafted on the molecular but i doesnt returns to the system and is in a forever waiting loop, the only way i managed to work was using a ME Import bus on each molecular assembler

![image](https://user-images.githubusercontent.com/69091308/229323335-1334e5ac-8343-4b0c-afa6-91551a1f4c21.png)
![image](https://user-images.githubusercontent.com/69091308/229323349-fd7796c0-d909-4f1d-841f-ae4b4688e60b.png)

### How to reproduce the bug

Request a item to be auto crafted on a molecular assembler

### Expected behavior

The item get crafted and returns to the system

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/RAtTGeiN

**Comment by Sea-Kerman** [comment]
Optifine moment?

**Comment by Rafa7046** [comment]
Yeah.. it worked removing optifine, thanks for the help, i think i deserved for using optifne.
