### ISSUE TITLE
Spatial anchor loads unnecessarily large amount of chunks after transport to spatial dimension

### ISSUE THREAD

**Issue by stanleymorse1** [AppliedEnergistics/Applied-Energistics-2#7012]
### Describe the bug

When using spatial IO to physically store a spatial anchor, it's power usage spikes rediculously high and doesn't decrease until it depletes or is broken, even when brought back to the overworld.

### How to reproduce the bug

1. Create a basic 16^ SCS and attach a ME Controller and a spatial IO port
2. Create a quantum ring outside the SCS on the network and one inside with a spatial anchor attached to it, link and power the rings.
3. Put a blank spatial drive into the spatial IO port and power it, then check the ME controller to see the anchor's power usage spike
4. Wait a while
5. Put the spatial drive back into the left slot and power it, then right-click the spatial anchor and check its usage stats

### Expected behavior

I expected the spatial anchor to load no more than 4 chunks, as a misaligned 16^3 SCS could only possibly cross 4 chunk boundaries. Instead, the anchor reports loading 81 chunks, a 9x9 radius around itself, and does not return to normal until its power is depleted or it is replaced.
![2023-03-31_19 06 25](https://user-images.githubusercontent.com/47867840/229370104-eaae1b94-fd71-425f-bf20-d02ff5d6eace.png)

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/ATuqH9RT

**Comment by Technici4n** [comment]
The idea was that the anchor needs some time to turn back online after having been moved. But it should stop loading the extra chunks once the network has fully booted.
