### ISSUE TITLE
Faster molecular assemblers?

### ISSUE THREAD

**Issue by Shadedstalker2** [AppliedEnergistics/Applied-Energistics-2#7018]
### Describe the feature

Change the assemblers to be faster or add a faster assembler block to speed up crafts

### Reasons why it should be considered

The assemblers are slow and for larger packs it’s annoying to offload to an external crafter from rftools and others

**Comment by Technici4n** [comment]
You can place multiple molecular assemblers around each pattern provider for extra parallelism, and you can place the exact same pattern in multiple pattern providers for another level of parallelism.

**Comment by Shadedstalker2** [comment]
Yeah ik but that's more channels and still slower than a basic crafter on slow even with 6 assemblers

**Comment by Technici4n** [comment]
Yeah this isn't getting buffed to match OP mods.
