### ISSUE TITLE
Mana Fluxfield not powering AE2 directly

### ISSUE THREAD

**Issue by Gragnar** [AppliedEnergistics/Applied-Energistics-2#702]
I'm not sure if it's a missing mod or a bug and if so, which mod is responsible so I'll post this to both projects. I'm playing on a mostly magical playthrough and I'm trying to power AE2 directly from a Mana Fluxfield but none of the methods I've tried seem to work. I've tried to put the fluxfield next to an AE2 energy acceptor or next to an AE2 energy cell and in both cases the mana spreader shoots a couple times into the fluxfield and stops (probably because the fluxfield doesn't have anywhere to send RF) and the drives connected to either do not light up. I'm using the default settings for both Botania and AE2. I've also tried with and without COFHCore + COFHLib + ThermalFoundation. Here are a screenshot of the test setup and the list of mods I'm using:

![image](https://cloud.githubusercontent.com/assets/7951011/5630999/e41ad1a0-9590-11e4-80d8-ceb84d8bd1c4.png)

WaslieCore-1.1_B43
[1.7.10]Treecapitator-universal-2.0.4
AOBD-2.3.5
appliedenergistics2-rv2-beta-7
ArchimedesShips-1.7.1
Aroma1997Core-1.7.10-1.0.2.13
AromaBackup-1.7.10-0.0.0.5
Automagy-1.7.10-0.17.1
backpack-2.0.1-1.7.x
BiblioCraft[v1.9.1][MC1.7.10]
BloodMagic-1.7.10-1.3.0a-1
BloodUtils-1.4_B0
Botania r1.3-148
Carpenter's Blocks v3.3.4.1 - MC 1.7.10
Chisel 2-2.2.1
CodeChickenCore-1.7.10-1.0.4.29-universal
D3Core-1.7.10-1.1.0.16
Decocraft-v1.11_1.7.10
dimensional-anchor-59.0.2
eirairc-mc1.7.10-v1.7.52
extrautilities-1.2.1
fastcraft-1.12
Forbidden Magic-1.7.10-0.551
ForgeMultipart-1.7.10-1.1.1.320-universal
hopperductmod-1.7.10-1.3.2
immibis-core-59.0.5
INpureCore-[1.7.10]1.0.0B7-19
InventoryTweaks-1.59-dev-156
ironchest-1.7.10-6.0.62.742-universal
Jabba-1.2.0a_1.7.10
JourneyMap5.0.1_Unlimited_MC1.7.10
MobiusCore-1.2.3_1.7.10
MrCrayfishFurnitureModv3.4.7(1.7.10)
mystcraft-1.7.10-0.11.0.00
NotEnoughItems-1.7.10-1.0.3.74-universal
OpenBlocks-1.7.10-1.3
OpenModsLib-1.7.10-0.6
Sanguimancy-1.7.10-1.1.8-4
StorageDrawers-1.7.10-1.2.0
supercraftingframe-1.7.10.1
Thaumcarpentry-0.0.1.5-1.7.10
Thaumcraft-1.7.10-4.2.2.1
ThaumcraftMobAspects-1.7.2-2A
thaumcraftneiplugin-1.7.10-1.6a
thaumicenergistics-0.8.7.2a-rv2
ThaumicExploration-1.7.10-1.1-34
ThaumicInfusion-1.7.10-3.83
ThaumicTinkerer-2.5-1.7.10-162
TorchTools-1.7.10-1.1.0.21
Translocator-1.7.10-1.1.1.14-universal
twilightforest-1.7.10-2.3.2
Waila-1.5.7a_1.7.10
[1.7.10]bspkrsCore-universal-6.15
Baubles-1.7.10-1.0.1.10
CodeChickenLib-1.7.10-1.1.1.110-universal
commons-codec-1.9
commons-compress-1.8.1

**Comment by Gragnar** [comment]
After some more testing, I can use an ExtraUtilities energy transfer node to power the energy acceptor with the mana fluxfield, so the fluxfield definitely works. It seems to be something between the 2 blocks that prevent it from working.

**Comment by yueh** [comment]
This is a Botania issue. The mana fluxfield only powers `IEnergyHandler`, which are producers and recievers for RF. This would only make sense if Botania would allow to convert RF to Mana.

We are only using `IEnergyReceiver` as we only recieve RF and not produce it.
