### ISSUE TITLE
close wireless terminals and portable cells using the open keybind

### ISSUE THREAD

**Issue by Mari023** [AppliedEnergistics/Applied-Energistics-2#7020]
### Describe the feature

pressing the open terminal keybind while the terminal is open should close the terminal again
(same with portable cells)

### Reasons why it should be considered

mostly for consistency, since the vanilla inventory can also be closed by using the inventory key

### Additional details

originally opened on ae2wtlib: https://github.com/Mari023/AE2WirelessTerminalLibrary/issues/194

**Comment by Technici4n** [comment]
for wireless terminals specifically, right?

**Comment by Mari023** [comment]
yes, wireless terminals and portable cells only

**Comment by floridaman** [comment]
Socializing a potential way of adding this feature.

https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/7182
