### ISSUE TITLE
Crash with REI 11.0.597 and AE 14.0.0-alpha

### ISSUE THREAD

**Issue by HttpRafa** [AppliedEnergistics/Applied-Energistics-2#7021]
### Describe the bug

The mods crashes when opening the ME inventory.

### How to reproduce the bug

Install REI version 11.0.597
and AE version 14.0.0-alpha

### Expected behavior

The inventory opens

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/bXMFmy5w

**Comment by Mari023** [comment]
14.0.0-alpha was released for a prerelease and was compiled with an older REI version (for 1.19.3)

If you want to get ae2 and REI working together, you will have to compile ae2 yourself

(you might have to change `rei_version` to `11.0.597` in gradle.properties)

**Comment by HttpRafa** [comment]
Im going to do that. Thanks
