### ISSUE TITLE
Sorting Options

### ISSUE THREAD

**Issue by beiarii** [AppliedEnergistics/Applied-Energistics-2#7022]
### Describe the feature

Refined Storage comes with the abiltiy to sort by Last Modified, and as i tried to make the transition to AE2 this missing feature put me off from completing said transition.

### Reasons why it should be considered

it's just a general QoL change that would be nice to have as somebody transitioning to a more stable central storage system mod.

**Comment by Technici4n** [comment]
Duplicate of #4995
