### ISSUE TITLE
ME interfaces dont pull things from any chest or another interface when autocrafting

### ISSUE THREAD

**Issue by shivachirr** [AppliedEnergistics/Applied-Energistics-2#703]
im having to repost this due to 15 mins ago someone closed my old post while i was about to respond thinking it was resolved which its not and before i could say a thing.

when use me interfaces in anyway with chest or its self for autocrafting it dose not pull items the are completed from chest or ae chest and when you do 2 facing each other its a complet fail because they cant talk in the autocrafting setup. now this has worked it the past before the final version of RV1 and its still not working in RV2

![javaw 2015-01-06 12-44-37-89](https://cloud.githubusercontent.com/assets/9361172/5633090/00717910-95a2-11e4-9118-de6db0cadfc4.jpg)
![javaw 2015-01-06 12-25-03-66](https://cloud.githubusercontent.com/assets/9361172/5633092/00759630-95a2-11e4-8f61-450d70a16594.jpg)
![javaw 2015-01-06 12-24-56-58](https://cloud.githubusercontent.com/assets/9361172/5633091/00746648-95a2-11e4-84cc-ed02a0a379e3.jpg)

**Comment by yueh** [comment]
This has never worked, not even in AE1.
It will also never happen, even if you try to claim it is a bug.

Also you can still respond to closed issues.

**Comment by shivachirr** [comment]
im talking about for autocrafting when its used it should be pulling things form inventorys and it has worked in the past

**Comment by AlgorithmX2** [comment]
Other machines such as the Molecular Assembler or various machines in other mods, push results into the interface upon completion, however it is the responsibility of the machine to do this, or you need to use an import bus.

**Comment by shivachirr** [comment]
really then why has it worked in the past for me when useing autocrafting with a chest for my inscirbers

**Comment by AlgorithmX2** [comment]
I believe you may have confused two things, or something else, I assure you that neither I nor the current devs have ever implemented that.
