### ISSUE TITLE
Store item into Bottomless Bundle cause item duplicating

### ISSUE THREAD

**Issue by XenonDB** [AppliedEnergistics/Applied-Energistics-2#7033]
### Describe the bug

Testing in [AQM2 v1.4.4hf](https://www.curseforge.com/minecraft/modpacks/another-quality-modpack-2/files/4467986)

Since bottomless bundle can be placed as a block and store item into it, it may act like a black hole unit or something similar.
The bottom side is output while the others is input.

I setup a testing system for it's behavior:
![2023-04-09_02 32 01](https://user-images.githubusercontent.com/58476103/230737636-fba364e8-4bb0-4c78-823e-bd55a1484360.png)
store one lily pad into bundle and break the bundle to check it content
and found it contain two lily pad.

The reason that I consider it is a bug from AE2 is there's no such issue with Tom's Simple Storage:
![2023-04-09_02 45 40](https://user-images.githubusercontent.com/58476103/230737869-2ffa6334-c7bf-42c5-9ee7-73fa43c638df.png)

### How to reproduce the bug

Setup a network like first picture then store item into bundle.

### Expected behavior

Item shouldn't duplicating during this process.

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Fabric

### Crash log

https://paste.ee/p/ExTyx

**Comment by XenonDB** [comment]
To make sure it doesn't come from other mod, I make an environment which is only installed ae2, spectrum and its dependencies.
Duplicating still happens.
![2023-04-09_05 46 24](https://user-images.githubusercontent.com/58476103/230743953-b5d4d30d-b5a0-40bf-83ac-f21c448eea78.png)

Crash log:
https://paste.ee/p/dpyd0

**Comment by DaFuqs** [comment]
I can not reproduce it in the Spectrum dev + AE2 12.9.2. This is a good thing.
In dev, the Bottomless Bundle internals have gotten a total revamp, so probably is on Spectrum's side + already fixed. Consider it resolved for AE2 and in general when Spectrum 1.7 is released.
