### ISSUE TITLE
Maintain autocrafting stock levels

### ISSUE THREAD

**Issue by CommYutzy** [AppliedEnergistics/Applied-Energistics-2#704]
Would it be possible to create an interface/terminal where we can set to keep x number of an item crafted within the network? So for example I could set to automatically craft more logic processors when the inventory drops below 20. I understand this can be accomplished with a combination of level emitters, export buses, and interfaces but once you do that for enough items it really takes up a lot of room.

**Comment by yueh** [comment]
This is already possible with interfaces.

#638 and #389 are also related to it and might contain some more information.

**Comment by CommYutzy** [comment]
Umm maybe I'm retarded but I can't get it to work right. I've tried to set it up in every configuration posted and it never crafts the items. Would it be terribly hard to add an option to the interface terminal where you can set stock levels from one central location?
