### ISSUE TITLE
Make the "Middle Click to Change Amount" and crafting with Middle Click configurable in keybinds

### ISSUE THREAD

**Issue by sarpuser** [AppliedEnergistics/Applied-Energistics-2#7040]
### Describe the feature

It would be fantastic if we could rebind the button used to change the amount in a crafting recipe or request a craft of an already existing item.

### Reasons why it should be considered

The default key for the pick block function is the middle click button, and the middle click is a very convenient key for that. When I try to change the amount in a crafting recipe, it opens the menu but also grabs a pattern out of the pattern encoding terminal. Normally this would not be an issue but when trying to change an already existing craft it picks up the already encoded pattern and then when I am done setting the amount I have to put the pattern back into the slot and it loads the old pattern I am trying to change. When you are trying to request a craft of an already existing craft, it just grabs a random item and then you have to put it back into the system. <br>
<br>
![Screenshot 2023-04-12 at 02 19 29](https://user-images.githubusercontent.com/23362324/231368378-8d8f5368-9bb1-4077-92bb-8b448489f1d9.png)

**Comment by Sea-Kerman** [comment]
this is an issue with an inventory sorting mod. either choose a different button for "sort", or rebind "pick block"

the button for changing the amount/crafting something is whatever you have "pick block" bound to.

**Comment by sarpuser** [comment]
That makes sense. Thanks!

**Comment by sarpuser** [comment]
I just double checked. All the key binds for inventory sorting are turned off and the issue still persists. In addition to the original issue, I realized that if I am using the wireless crafting terminal and there is nothing in the crafting grid, middle clicking on a cartable item in the terminal will move my armor into the crafting grid. Like you said, this seems like a sorting issue but not sure how to fix it since all the keybinds for that are already off. Regardless, it would be nice to be able to rebind the button on the AE2 side.

**Comment by Sea-Kerman** [comment]
which sorting mod is it, because I know Inventory Profiles Next hides its keybinds in the mod config, not in the vanilla minecraft options menu

**Comment by sarpuser** [comment]
Quark inventory. The key binds for sorting player and target inventories are shown in the menu and neither are bound to any key.

**Comment by Sea-Kerman** [comment]
Very weird. Anyway, what you desire is a way to bind it separately from "pick block"?

**Comment by sarpuser** [comment]
Yes. It would be very useful in situations like this. Especially since this seems to be a Quark inventory problem and not an AE problem. This way if this situation arises in the future with other mods, we can always rebind the key and call it a day.

**Comment by Technici4n** [comment]
Not a fan of the idea, I think this is a quark bug more than anything else...
