### ISSUE TITLE
Option to switch to old 1.5.2 Recipe for AE

### ISSUE THREAD

**Issue by djoveryde** [AppliedEnergistics/Applied-Energistics-2#705]
Currently I have found the latest recipe for AE2 to be very complex. Is there a way to have the option to use the old recipe system for ME items instead of using Charged Certus in the recipe?

I'm using 1.7.10 minecraft, currently building a Voltz alternative modpack so trying to keep recipes as similar as I can

**Comment by yueh** [comment]
You can use our [Custom Recipes](http://ae-mod.info/Custom-Recipes/) to modify them.
