### ISSUE TITLE
ae2 contents in ME terminal only show transient items. Storage is on libe but does not show up

### ISSUE THREAD

**Issue by gzcwnk** [AppliedEnergistics/Applied-Energistics-2#7068]
### Describe the bug

yesterday I found my stored items became "invisible" However transient items are visible. I restored from 2 day ago backup today but it is happening again

### How to reproduce the bug

no idea

### Expected behavior

stored items are seen.

### Additional details

atm8  patch13

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

https://imgur.com/a/87YRDTk

**Comment by Technici4n** [comment]
I assume this is a duplicate of #6725, which will be fixed in the next release.
