### ISSUE TITLE
Mention in the Wrench's description in the docs that it can also apply a direction to the pattern provider.

### ISSUE THREAD

**Issue by deguix** [AppliedEnergistics/Applied-Energistics-2#7072]
### Describe the feature

Also mention in the autocrafting section in the pattern provider subsection that "the pattern provider will then push out the ingredients to" any adjacent blocks or to a certain one with the use of a Wrench.

That should allow people to understand that the Wrench is more useful than it seems, and that the pattern provider direction can be used to prevent pushing ingredients to multiple blocks when it's not intended.

For example, if a hopper is used to output the result back to pattern provider from a machine - to prevent adding another channel - and the pattern provider's direction wasn't set, then the ingredients on the first craft will be pushed to either the hopper or the machine, then on next craft it will spit to the other one, and it will keep switching between the 2 for now on on future crafts.

### Reasons why it should be considered

Right now there's no mention anywhere of the Wrench's use in determining the push direction of ingredients from pattern provider.

**Comment by Sea-Kerman** [comment]
Already in-progress https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/356b4de4b07b206563ebde5669eaf700fd77d007/guidebook/items-blocks-machines/pattern_provider.md
