### ISSUE TITLE
Buckets of fluid can't be extracted from terminal when >~54m buckets are available 1.19.2

### ISSUE THREAD

**Issue by jpenilla** [AppliedEnergistics/Applied-Energistics-2#7077]
### Describe the bug

Either clicking the fluid with an empty bucket or clicking the fluid with empty buckets in the system doesn't work when too much fluid is available.

### How to reproduce the bug

Fill a quantum tank from MI with 55m (~54296870.5074)+ buckets of fluid and attach a storage bus, or attach a storage bus to Granny's Sink from Coxhina Utilities. Then try to extract buckets of the fluid from a terminal.

### Expected behavior

Fluid extraction works normally

### Additional details

When >~54m buckets are available it won't display over that number. This is a less annoying and adjacent issue though.

54m buckets are presumably Long.MAX_VALUE of fluid units.
For example mana cells from AppBot with >200m mana work/display fine, but they don't have the 81000 parts.

Modpack tested on is AoF6 1.5.4

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Fabric

### Crash log

na

**Comment by 755437985** [comment]
got the same issue on ATM8-1.0.17 (Forge)
I can't get water out from any terminal with a storage bus attached to a infinite water source

**Comment by Technici4n** [comment]
Can't reproduce
![image](https://user-images.githubusercontent.com/13494793/236629990-abd56536-c6c3-4137-b854-7302adc1d485.png)

Make sure you are left clicking to fill the buckets.

**Comment by 755437985** [comment]
oh sorry, my bad.
not any terminal, just the wireless one doesn't work
![image](https://user-images.githubusercontent.com/25640242/236633226-53c7f7db-b267-4b65-af2c-55df793cc38d.png)

**Comment by jpenilla** [comment]
Ah yep, it's just wireless terminals. Regular terminals are fine.
