### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by p000q** [AppliedEnergistics/Applied-Energistics-2#7099]
### Describe the feature

We need this mod on fabric 1.19.4

### Reasons why it should be considered

People are upgrading to newer versions

**Comment by Mari023** [comment]
From the discord:
> **Development update**
We are working on bringing a vastly improved AE2 for Minecraft 1.20. This is necessary as there will be breaking changes. However, this means that we have little time for backports. As such, here is the current support status:
>
> - Minecraft 1.19.4: no usable released version, unsupported, will never be supported.
>- Minecraft 1.19.3: unsupported due to limited development time.
>- Minecraft 1.19.2: supported, important bug fixes only.
>- Minecraft 1.18.2: supported, important bug fixes only.
>- anything older: unsupported.
>
>I recommend that you stay on 1.19.2 or 1.18.2 until 1.20 releases.

**Comment by p000q** [comment]
Good afternoon, how long will the development for 1.20 take approximately?12 трав. 2023 р. о 23:12 Technici4n ***@***.***> пише:﻿
Closed #7099 as not planned.

**Comment by Technici4n** [comment]
Probably a few days after the final 1.20 release at most.

**Comment by embeddedt** [comment]
It will be ready when it's ready. :wink: Contributors are welcome to help speed it up.

**Comment by Technici4n** [comment]
No, he's right that I said we would release it, and we didn't, so the question is legitimate. AE2 15.0.0-alpha is now out for MC 1.20.1.

**Comment by p000q** [comment]
omggg finally🎆🎆Надіслано з iPhone13 черв. 2023 р. о 23:49 Technici4n ***@***.***> пише:﻿
No, he's right that I said we would release it, and we didn't, so the question is legitimate. AE2 15.0.0-alpha is now out for MC 1.20.1.

**Comment by Technici4n** [comment]
You can't, but you can ask the other mods to update. (Should be trivial)
