### ISSUE TITLE
Server freeze and 100%cpu

### ISSUE THREAD

**Issue by gaymode** [AppliedEnergistics/Applied-Energistics-2#710]
Hi, 
The server freezed. From the log given, I believe there are something wrong with ae2.
log: http://pastebin.com/VU7uMtTs
Before the freeze, I have shift-click the Jabba's B-space thingee to the pattern encoder.
I have got the freeze before and found that there is something wrong with ender chest (B-space crafting recipe include a ender chest from ender storage)
The freeze have occurred for about 3 minutes and spammed the log from server console.
During the 3 minutes, all players from server have been kicked out and received a 'Time out' message
I have to kill java to stop the server. (which, have damaged the map once)
Last time it freeze is because of dumping an ender chest into the AE network.

Hope there are enough informations for resolving this bug.

ae2 version: rv2 beta7
ender chest version: 1.4.5.27
Code chicken core version: 1.0.4.29
Jabba version: 1.2.0a

**Comment by gaymode** [comment]
After some tests, I found that crafting recipe using ender chest (The ender storage one, I did not test the vanilla one) will freeze the server. In my case, the jabba BSpace upgrade requires an ender chest and it will freeze the server.

**Comment by yueh** [comment]
The log itself just says our sever did not have enough memory while AE2 build a cache for the OreDictionary.

So either your server has really not enough memory available and it just randomly crashed while doing something AE2 related or the OreDictionary for your pack is ridiciulous large. Like oredict every possible enderchest, should be about 4096 or 8192 different ones, depending how the private ones are working.

We might be able to optimize our part a bit, but this might not be enough.

**Comment by gaymode** [comment]
It turns out there are at least 4097 ender chests in my mod pack. Even though I bump up the ram usage for server, I don't think my cpu is strong enough for handling this.
Maybe I should find a way to prevent ender storage registering its ender chest to OreDictionary. Or just change Jabba's recipe to use vanilla ender chest only.

So, I have come up with a suggestion. What about ae2 will escape the loop when it find there are too many items in the OreDictionary? That should solve the problem of too large OreDictionary.
