### ISSUE TITLE
Single meteor spawn in BWG4 island worlds.

### ISSUE THREAD

**Issue by chogata** [AppliedEnergistics/Applied-Energistics-2#711]
I have minecraft 1.7.10 and lots of mods. Two of them are AE2 and BWG4 (Better World Generation).

When I create a survival island world in BWG4 (standard or tropical island, large size) I always have only one meteor in my world. The world is infinite and other structures (like from Dungeon Pack mod) generate all over it. But there is always only one meteor, somewhere below the island. So it is not possible to gather all inscribers...

Versions:
1.7.10-Forge10.13.2.1272
BWG4-1.2.1
appliedenergistics2-rv1-stable-1

I cannot use rv2-beta, because it crashes at start. Might be because of all my other mods, but I want to have them all :)

**Comment by Cisien** [comment]
Rv2 will only spawn meteors in the overworld by default. If your island is the overworld, then you can disable the meteor Gen all together

**Comment by chogata** [comment]
Yes, the island is the overworld.

I will try later to test rv2 on a clean installation with no other mods than BWG4. See if it behaves just like rv1 or if something differs.

And yes, I know I can disable meteors altogether, but I'd rather they generated like on any other world ;)

**Comment by Cisien** [comment]
Meteors only spawn on land, if the rest of the world is void, where would the meteor land?

**Comment by chogata** [comment]
The rest of the world is NOT void - it's Ocean. Okay, "strange" ocean (sand level is 50, above is water and it's all the way flat), but definitely not void.

Tested rv2, behaves exactly the same - one meteor under the island, no meteors further in the ocean.

**Comment by yueh** [comment]
This is probably the issue.

Meteors do not spawn below y = 40 (center of the meteor).
Also they need an 30x30x30 area around them without some specific blocks like water.
So there is just not enough room to spawn them.

We mostly assume a worldgen similar to vanilla as well as default AE2 configs.
The moment a user or modpack maker decides to change this, we usually assume it is their responsibility to fix these ( of course we must provide at least one way to fix it).
The worldgen has still room to improve (see #398), but this is a bit tedious and doing it right requires quite a bunch of work. But we cannot support every possible worldgen, so some of them will always be an issue.

But you could for example add a custom recipe to craft the presses.

**Comment by chogata** [comment]
Consider adding an option to config so the presses could be found in chests around the world, like other regular loot. Then, in cases like this, there is an easy, acceptable alternative.

I did earlier exactly what you suggested, I added custom recipes for the presses. But I don't like this solution. The recipes are either cheap and then the whole experience is too easy, or they are difficult and then the players don't use ae2, because they choose to focus on another mod in the pack. Loot in chests is a stroke of luck, sometimes you find what you need early in the game, sometimes you need to wait, on multiplayer servers there is an option of swapping or buying presses... More fun ;)

**Comment by yueh** [comment]
Dungeon loot is even worse as you may never find any dungeon at all. Meteors at least have a reliable way of finding them. Also it was probably rejected many times earlier by @AlgorithmX2.

Honestly meteors are not hard to find. It maybe needs 2 or 3 minecraft days (without night) to visit enough meteors, if you press for them (and not mine the whole meteor).
Also you still need to find some charged certus, which might be quite unlucky sometimes.

Custom recipes allows you to balance it as you wish. Mostly limited by your ideas.
For sandbox themed packs, you can make it dirt cheap by putting dirt/cobble/logs/similar into a inscriber to get a press or something more balanced like 1 Iron Block + 1 Skystone Dust + 1 ingot/block of the actual material to craft the circuit. This would for example require to find at least 1 meteor.
For themepark packs (maybe even with a forced progression) you might even disable copying them completely and just hand them out through something like HQM.

**Comment by chogata** [comment]
Okay, it's your mod, I won't force you to change worldgen nor to change the rules ;)

I created this issue, because I thought it was a weird bug, but your explanation about the requirements about spawn area shows that this is just the case of no suitable environment on a survival island kind of world.

I will manage - I will choose a solution I hate the least and I'll implement it. My thoughts about some kind of option in config were more for less advanced MC players - people that are savvy enough to put together 10 mods by themselves, but not savvy enough to properly use mods like custom recipes or mine tweaker when something clashes.
