### ISSUE TITLE
Remove security system

### ISSUE THREAD

**Issue by Technici4n** [AppliedEnergistics/Applied-Energistics-2#7116]
The security system doesn't prevent removing blocks, so it has always been possible to go break the security station and then do anything with the system. It also requires the system to be powered and the security station to have a channel. See also #6860. Therefore it is more or less useless, and should likely be removed. Thoughts?

We will find another way to connect wireless terminals, likely through wireless access points.

Protecting your network will still be possible using mods like FTB Chunks.

**Comment by Technici4n** [comment]
Scheduled for 1.20 now. Giving a bit of time to collect opinions.

**Comment by SirEndii** [comment]
I agree that the security system has its flaws but securing my items from others was always helpful, especially if you don't have other mods like FTB Chunks or any other "region claim" mods installed

Wouldn't there be a way to make the security better instead of removing it?

**Comment by SirEndii** [comment]
> @SirEndii If you don't have any other chunk protection mod, they can just break your security terminal :-D

Yeah I know, that's why I asked to improve the security system instead of removing it

**Comment by Technici4n** [comment]
The main reason not to extend the functionality of security is that 1) it is already available in other mods, so just install them; and 2) that time could be better spent on other things instead.

**Comment by MommyHeather** [comment]
Honestly, it does more harm than good right now. I say remove it, because of other mods there's no real use for it other than the terminals.

**Comment by cplir-c** [comment]
Other claim mods and whatever can't really protect wireless AE access-- but you can't synchronize a wireless terminal without putting it through the security terminal wireless terminal slot. Maybe the security terminal should just be for configuring who can open the security terminal.
Some way to link a wireless terminal is definitely required still regardless.

**Comment by mopsy14** [comment]
Maybe it would be nice to make every block have some kind of security(a password or something). And then you can for example, use the security terminal to change this security on devices with the same password on the same network.
