### ISSUE TITLE
Once Powered, disconnecting power doesn't cause system to lose charge

### ISSUE THREAD

**Issue by RAWRwins254** [AppliedEnergistics/Applied-Energistics-2#713]
Howdy!

Been posting about this in #AppliedEnergistics channel on EsperNet, but was told rv2-b7 is out of date which is not actually the case according to ae2.ae-mod.info and curseforge. So here I am. The requirements to reproduce the bug in question are: a dense cable hooked up to a controller, a few energy cells (may not be required but they're in my set up so yeah), an energy acceptor, and finally, a power source for temporary connection. Connect everything up except for the power then connect power to the energy acceptor. Check with network tool to make sure it charged. If it did, disconnect power from the acceptor and re-check the system. My screen shows it re-charging up to the maximum it could at the point the power got disconnected. So if i add another energy cell for example, it will not charge past the original maximum that existed when the power was cut.

postimg.org/gallery/147616af2/02fb9b9a/
postimg.org/gallery/1l280dkm/d1a36a41/

Kinda irritating to be told my version is out of date when it's the most recent version not just for beta versions but for Alpha Versions too.

**Comment by RAWRwins254** [comment]
Also, to prove that rotarycraft is not somehow at fault, I disconnected the energy acceptor and moved it  to a new location more than 5 blocks away and reconnected it. Issue is still present.

**Comment by yueh** [comment]
Cannot reproduce it with only AE2. Adding energy cell just takes ages until a small network loses its power.

**Comment by RAWRwins254** [comment]
Yueh:  thanks for investigating. Maybe it is a power input issue. You used the vibration chamber to power it correct?

**Comment by RAWRwins254** [comment]
Yueh: I think i might've isolated the issue. It might be a client-rendering issue because when I logged in to my friend's server (the server on which this AE2 system is in place), it had run out of juice.
