### ISSUE TITLE
Disabling channels removed controller

### ISSUE THREAD

**Issue by raxixor** [AppliedEnergistics/Applied-Energistics-2#714]
Title mostly says it all.
On my server I ran a poll, which was to choose whether to leave channels on, or disable them. Disable won, so I disabled them, but now controllers are gone, along with smart cable.

**Comment by asgdfagdsfg** [comment]
Exact same problem, Developers just lie about the ability of disabling this retarded stuff.
Even local, no matter what version you put in, it either removes the controller, or it says "channels disabled" and still works exactly as it did with the channels.
Really hope that some GOOD developers pick up on this, and make this mod playable again.
The trolls that are working on it now, seem to only want to piss off people by removing everything the mod was ever good for. I seriously don't understand what you are supposed to do with the mod now. It's worse then EVERY other sorting / storage mod, that there is. Jabba and Buildcraft together are a million times better then this, and you have them from the START of the game, while this is pretty much the last endgame thing you used to make. When you achieved everything else, you got a ME, and became king (pretty much earned creative mode). And now when you reach this... you just realize, that your old crappy system was 1000 times better... So sad what the devs did to this mod...

**Comment by ktole1999** [comment]
when you disable channels it removes everything associated. cables, controller, etc. they are usless without channels

**Comment by Greymagic27** [comment]
Is there anyway to use applied energistics without the controller?

**Comment by mindforger** [comment]
>Greymagic27

the controller only provides additional channels when playing with channels enabled .... having a controller is useless without channels ... also many cables **being "animated" to show channels** are removed then

you may have to change a few recipes to be able to build a quantum link chamber but thats all

also this topic is years old and you should either test yourself before asikng in such an old thread or make an proper new issue if you are having trouble using AE2
