### ISSUE TITLE
Server and client crash appliedenergistics2-rv2-beta-7

### ISSUE THREAD

**Issue by Tsyklop** [AppliedEnergistics/Applied-Energistics-2#715]
Server and client crash with appliedenergistics2-rv2-beta-7
Crash-report:
http://pastebin.com/Jjgh50jc

**Comment by Cisien** [comment]
Please post the full crash log

**Comment by Tsyklop** [comment]
http://pastebin.com/4Y4T5gb5

**Comment by Cisien** [comment]
I think that log got cut off, I'm not seeing the expected details

**Comment by yueh** [comment]
Duplicate of #675
