### ISSUE TITLE
1.19.2 Wireless Terminal missing curio support

### ISSUE THREAD

**Issue by DevDyna** [AppliedEnergistics/Applied-Energistics-2#7150]
### Describe the feature

Add curio support at Wireless Terminal to open when on curio slots

### Reasons why it should be considered

Wireless crafting table already support curio when added
Wireless terminal why not? 
(maybe feature planned i can suppose or forgot to add)

**Comment by Mari023** [comment]
curios support is added by ae2wtlib, and requires some mixins into ae2 code.
since ae2wtlib doesn't touch the normal wireless terminal otherwise, I also didn't make it work with curios.

**Comment by DevDyna** [comment]
Ah ok , I never think that was added by ae2wtlib and that could cause problems , thanks anyway
