### ISSUE TITLE
Channels are sometimes shown on the wrong side

### ISSUE THREAD

**Issue by shartte** [AppliedEnergistics/Applied-Energistics-2#7151]
![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/1261399/d181f1f3-221d-4867-9bc2-12c42f6ad40d)

**Comment by Sea-Kerman** [comment]
it's actually that the channel texture is mirrored left-right

**Comment by Sea-Kerman** [comment]
(this is a .snbt)
[cable_direction_texture_problems.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/11548050/cable_direction_texture_problems.txt)
