### ISSUE TITLE
autocraft from items with a charge from IC2

### ISSUE THREAD

**Issue by DIMMMAZ05** [AppliedEnergistics/Applied-Energistics-2#7155]
### Describe the bug

When trying to auto-create in a molecular assembler, for example, MFE, the process simply freezes, despite the fact that all resources are needed. This happens only when crafting from energy crystals and batteries. There is no such error on version 1.7.10

### How to reproduce the bug

Just repeat the steps in the video. There is no need to build the ME system in the same way, but there must be mandatory blocks for autocraft
https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/84288748/2f923666-77dc-4da7-88e3-edfbad96ec0e

### Expected behavior

The MFE autocraft was supposed to begin

### Additional details

despite the fact that I have a large build, even with a pure AE2 + IC2, this problem occurs

### Which minecraft version are you using?

1.12 - UNSUPPORTED

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/DIMMMAZ05/87667db03a8c678c5371500a04ba980d

**Comment by Technici4n** [comment]
We don't support 1.12 anymore.
