### ISSUE TITLE
Full height style crafting terminal crash

### ISSUE THREAD

**Issue by Inteprise** [AppliedEnergistics/Applied-Energistics-2#7158]
### Describe the bug

I updated the prominence [fabric] modpack to the latest version 1.6.1 and i noticed my me crafting terminal was reset to the smallest height window i switched it to tall and everything was fine. the moment i pressed "full height terminal style" then  the interal server shutdown and the game froze.

### How to reproduce the bug

start with the small height terminal, keep switching till you get to the tall height then press full height and freeze.

### Expected behavior

To actually go to the full height terminal without freezing my game.

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Fabric

### Crash log

https://mclo.gs/1APwUBc

**Comment by Technici4n** [comment]
Can this be reproduced with AE2 alone? Also, does this happen every single time?

**Comment by Inteprise** [comment]
This can be reproduced in the prominence modpack every single time

with a fresh fabric modpack and AE2 alone it is not bugged

**Comment by Inteprise** [comment]
ahh.. for a report on the modpacks github someone mentioned an issue with Smooth Swapping (v0.6) and when i tested it with ae2 and smooth swapping it crashed as soon as i joined the world and it crashed immediately because i tries to render stuff like the vibration chamber or an AE item i have in my hand such as the charged staff or fluid cell


[crash-2023-05-30_13.55.23-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/11605668/crash-2023-05-30_13.55.23-client.txt)
[crash-2023-05-30_14.09.35-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/11605669/crash-2023-05-30_14.09.35-client.txt)

**Comment by Technici4n** [comment]
That's an issue with smooth swapping, it tries to use modmenu but fails, presumably because modmenu isn't loaded. What happens if you run with modmenu? Do you still get a crash, and if so do you get a different crash?

**Comment by Inteprise** [comment]
https://mclo.gs/ySqBv0D
https://mclo.gs/he6bUu2
https://mclo.gs/YGYigh8

hi, i added mod menu and it didnt crash on startup anymore, HOWEVER, just like in the modpack the original problem arose where the moment i put it from tall to full height my game crashed trying to render the crafting terminal screen, pattern encoding screen and regular me terminal storage screen

The pattern access terminal doesnt have this issue. (i can go from small to full and back no issue)

**Comment by Technici4n** [comment]
Ah I see. Yes it is actually a smooth scrolling problem, please report the issue to them. ;)
