### ISSUE TITLE
How do I disable Metors

### ISSUE THREAD

**Issue by Flukethoughts** [AppliedEnergistics/Applied-Energistics-2#716]
Everytime a metor hits it kills my server. What do I need to to Im using rv1 and there is so much lag on myself I can't stand it.

**Comment by Cisien** [comment]
Without any more details, all I can suggest is to update to the latest version of forge for 1.7.10.

**Comment by TheJulianJES** [comment]
@Flukethoughts Log? Forge? Server data? Something?

**Comment by TheJulianJES** [comment]
Also consider updating to the latest rv2 beta.

**Comment by Cisien** [comment]
Lack of response.
