### ISSUE TITLE
Suggestion for improving Inscriber

### ISSUE THREAD

**Issue by Kevin-Marsh** [AppliedEnergistics/Applied-Energistics-2#7161]
### Describe the feature

At the moment creating large cells can be time consuming since Inscribers take a while to make the parts. This can be overcome with making multiple inscribers in a subnet which increases lag. My suggestion is that the acceleration card might be able to perform in inscribers similar to  how it does in things like the import bus, not only increasing speed but also size. As an example, 1 acceleration could do 16, 2 could do 32, and three cards could do a stack at a time. It would vastly increase production speed without drastically altering the current system beyond the changes that already seem to be planned of increasing stack size in the inscriber.

### Reasons why it should be considered

Increasing production of cells without having to resort to addons or have 64 of each inscriber.

**Comment by Technici4n** [comment]
The inscriber will receive some improvements in 1.20.
