### ISSUE TITLE
Info Stat for space left in ME System

### ISSUE THREAD

**Issue by Satherov** [AppliedEnergistics/Applied-Energistics-2#7162]
### Describe the feature

You should have an extra button in your ME Terminal to show the remaining space in the System. So all remaining Types and all remaining bytes/ a list with how many of a certain item can still be stored

### Reasons why it should be considered

It would give you a better overview if you have many drives to see the remaining space without having to manually count it on all disks

**Comment by Technici4n** [comment]
This has been suggested a few times already, but I am not convinced. Showing the remaining space doesn't really make sense as it depends on how you use it. The lights of the cells on the ME Drive provide a rough approximation that should be sufficient in practice.
