### ISSUE TITLE
Terminal not showing items

### ISSUE THREAD

**Issue by GiancarloPessatti** [AppliedEnergistics/Applied-Energistics-2#7165]
### Describe the bug

Well, from what I understand so far, it goes like this: Every time my system exceeds a certain amount of items (I haven't done the calculations, but around 3 full drives of 256k drives), it stops displaying the items in the system. It doesn't stop working, only the terminals "break", by which I mean, for example, I open my terminal and I don't see any items. However, if I send a crafting request for an item, it still recognizes the items I have in the drives and crafts it accordingly. Obviously, I won't be able to retrieve the same item because no items appear in the terminals. Imports and exports still work, but the storage buses stop working, and the terminal doesn't go blank, it stays "on" but without items. (google translate, Im brazilian, sorry)

### How to reproduce the bug

I didn't try to reproduce the error, but here are some screenshots that might be helpful. (The items that appear in the terminal are items that are being brought in through some import. They appear and then disappear shortly after)
![Screenshot_1](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/106692510/d64f7d49-f528-4e14-881f-1f78026d68cb)

![Screenshot_2](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/106692510/5aa43da7-684d-4a71-8377-7e58c33b23cf)

![Screenshot_3](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/106692510/bc7f9ffe-f1ed-411c-a147-8aa47210df46)

![Screenshot_4](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/106692510/6354b420-248c-4ace-b02c-128b35f21e15)

![Screenshot_5](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/106692510/ade6376b-afbb-45f1-922d-c4c846d1e2ea)

![Screenshot_6](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/106692510/5064e178-8729-47bb-9a9b-8347a9a006f9)

Here's another thing, when I place a crafting terminal and quickly open it, my recipes appear, so I can initiate automatic crafting.

![Screenshot_7](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/106692510/87420332-1099-4824-829d-fad997743642)

![Screenshot_8](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/106692510/7757a2ca-5e8c-4628-83e6-f2097ddb0ef0)

However, after closing and trying to open it again, the bug reoccurs

![Screenshot_9](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/106692510/b0680076-6fb8-4d7f-b2ad-20efa7678274)

Here are some screenshots of my base. They probably won't be helpful, but since I'm still new to this mod, I hope it helps!

![Screenshot_10](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/106692510/6a9ef652-e307-4650-8320-b60a92e6c05a)

![Screenshot_11](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/106692510/f4414e05-63ac-48d5-9bfd-8807cacc0e49)

![Screenshot_12](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/106692510/f73b68c7-4297-4e54-b610-83d13a4963d7)

### Expected behavior

I expected to see my items

### Additional details

This happened after leaving my PC on overnight for farming

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/jkXUDe1M

**Comment by GiancarloPessatti** [comment]
oh, forgot to mention, Im playing at ATM8

**Comment by Technici4n** [comment]
Just update to the latest AE2. 😉 (Server has to update too).

**Comment by GiancarloPessatti** [comment]
ohhh, server too! srry about that
