### ISSUE TITLE
minetest port

### ISSUE THREAD

**Issue by tigercoding56** [AppliedEnergistics/Applied-Energistics-2#7170]
### Describe the feature

minetest is a opensource voxel game engine with a mostly version independent modding API   , https://dev.minetest.net/
i am asking this to the mod devs of all my fav mods  so feel free to close this issue 

### Reasons why it should be considered

allows more people to use mod

**Comment by 62832** [comment]
I'm pretty sure this is *massively* beyond the scope of this mod considering that you're asking for it to be ported to a different game engine altogether and a different language. We're not doing that any time soon.
