### ISSUE TITLE
can someone help me with this

### ISSUE THREAD

**Issue by hking4401** [AppliedEnergistics/Applied-Energistics-2#720]
I'm making a mod pack and every time I put applied energistics in it, it won't work here is the crash report
http://pastebin.com/p7ixPTQU

if it isn't applied energistics why isn't it working when I put it is

**Comment by Rious** [comment]
Please put the log on pastebin and put the link here, instead of the log itself.

**Comment by hking4401** [comment]
http://pastebin.com/p7ixPTQU

**Comment by Rious** [comment]
Which version of AE are you trying to use?
also seems to be a problem with codechicken core and not AE2.

**Comment by yueh** [comment]
I only see a problem with OpenMods, nothing related to AE2.
