### ISSUE TITLE
Auto crafting option change

### ISSUE THREAD

**Issue by blockbreaker1361** [AppliedEnergistics/Applied-Energistics-2#721]
When you go to your crafting terminal to auto-craft something, the amounts don't make any sense. Have you ever seen items in stacks of 10, 100 or 1000? I say no. What would be nice is for the amounts to conform to standard Minecraft sizes like 1,8,16,64 and so on. It would be really nice if this change was implemented as it would make auto-crafting so much easier.

**Comment by yueh** [comment]
The config file allows to change it.
