### ISSUE TITLE
on 1.20 Forge, the inscriber does not consume the input ingredient

### ISSUE THREAD

**Issue by Sea-Kerman** [AppliedEnergistics/Applied-Energistics-2#7216]
### Describe the bug

The inscriber does not consume the input ingredient and thus works infinitely. The results can be taken out but the input ingredient cannnot.

https://youtu.be/KmK5VUhVpFo

### How to reproduce the bug

put a certus quartz crystal in a powered isncriber in 1.20 Forge

### Expected behavior

The inscriber works as it did before, and does on Fabric

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/Sea-Kerman/ee6637b0aa3d7edaf10f0032c2cf6594

**Comment by techiend** [comment]
Im having the same issue, you can get the ingredient back by breaking the inscriber, but is a bug
