### ISSUE TITLE
Signs can't be placed on AE2 cables at all

### ISSUE THREAD

**Issue by KonSola5** [AppliedEnergistics/Applied-Energistics-2#7218]
### Describe the bug

When you attempt to place a sign on an AE2 Cable and/or Bus, the sign is not placed, even if there's a facade on the side you want to place signs on.

### How to reproduce the bug

1. Place any ME Cable.
2. Place any facade on the ME Cable.
3. Try to place a sign.

### Expected behavior

The sign should be placed.

### Additional details

This behavior is odd, because you can place levers, buttons, Redstone etc. just fine on cables with Facades.

Even in vanilla you can place Signs on Signs even if there's no logical support.

(FYI: Minecraft doesn't crash, it's just the form requires crash report even if there's no crash, is it for grabbing the current AE2 version and mods present?)

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/RpYrpJui

**Comment by mindforger** [comment]
>(FYI: Minecraft doesn't crash, it's just the form requires crash report even if there's no crash, is it for grabbing the current AE2 version and mods present?)
basically yes, because reproducing a bug is often essential to understand the reasons better and a crashlog contains all essential data without any clutter like the default log
