### ISSUE TITLE
Cables Despawn after chunks deload

### ISSUE THREAD

**Issue by rhinestar** [AppliedEnergistics/Applied-Energistics-2#722]
Serveral times, I've had to replace cables over a chunk border and they are in a spot where they cah't be broken. 

Playing in DW20 1.7 FTB 1.03

**Comment by yueh** [comment]
Please provide a more detailed description and possibly how to reproduce it.

**Comment by RTRGitHub** [comment]
I can help here.
I have constructed a relatively large ME network, I run a cable into my Autocrafting room, cross a border and into a crafting CPU, I leave, Unload the chunk/server restarts in that time, come back and one cable from the connection has diespawned, Rinse and repeat for the same result

**Comment by FireBall1725** [comment]
@rhinestar and @RTRGitHub do you have a security terminal on your networks?

**Comment by RTRGitHub** [comment]
Yeah I do, and a wireless network

**Comment by FireBall1725** [comment]
@RTRGitHub Yea, i am familiar with that issue, it has to do with the way the security terminal works, the issue would be solved if you can chunk load the entire area, or if you put a blank card in the system with build rights, however that would allow everyone to build.

**Comment by RTRGitHub** [comment]
That's not an issue for me, But thanks for the help =]

**Comment by FireBall1725** [comment]
ahh sorry, ment to direct it to @rhinestar .

**Comment by thatsIch** [comment]
Closing in favor for https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1074
