### ISSUE TITLE
Minecraft Crash on Start-up [Fabric 1.19.3]

### ISSUE THREAD

**Issue by JumperK** [AppliedEnergistics/Applied-Energistics-2#7220]
### Describe the bug

Attempting to run Minecraft will cause a crash on start-up.

According to the report, it cannot execute the "client" entrypoint stage due to errors from AE2.

### How to reproduce the bug

1. Install the mods in the report below
2. Install the latest Fabric Release of AE2
3. Launch the Game with the installed mods

### Expected behavior

The client should load.

### Additional details

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'ae2'!

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Fabric

### Crash log

---- Minecraft Crash Report ---- // Why is it breaking :(  Time: 2023-06-24 00:42:29 Description: Initializing game  java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'ae2'! 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53) 	at net.minecraft.class_310.<init>(class_310.java:465) 	at net.minecraft.client.main.Main.method_44604(Main.java:205) 	at net.minecraft.client.main.Main.main(Main.java:51) 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/client/itemgroup/FabricItemGroupBuilder 	at com.almostreliable.merequester.platform.Platform.createTab(Platform.java:46) 	at com.almostreliable.merequester.Registration.<clinit>(Registration.java:23) 	at appeng.core.definitions.AEParts.handler$cck000$merequester$initRegistration(AEParts.java:519) 	at appeng.core.definitions.AEParts.init(AEParts.java:165) 	at appeng.core.AppEngBase.<init>(AppEngBase.java:121) 	at appeng.core.AppEngClient.<init>(AppEngClient.java:112) 	at appeng.core.AppEngClientStartup.onInitializeClient(AppEngClientStartup.java:10) 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) 	... 8 more Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.client.itemgroup.FabricItemGroupBuilder 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) 	... 16 more   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Thread: Render thread Stacktrace: 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53) 	at net.minecraft.class_310.<init>(class_310.java:465)  -- Initialization -- Details: 	Modules:  		ADVAPI32.dll:Advanced Windows 32 Base API:6.3.9600.16384 (winblue_rtm.130821-1623):Microsoft Corporation 		COMCTL32.dll:User Experience Controls Library:6.10 (winblue_rtm.130821-1623):Microsoft Corporation 		CRYPT32.dll:Crypto API32:6.3.9600.20512 (winblue_ltsb_escrow.220711-1746):Microsoft Corporation 		CRYPTBASE.dll:Base cryptographic API DLL:6.3.9600.17415 (winblue_r4.141028-1500):Microsoft Corporation 		CRYPTSP.dll:Cryptographic Service Provider API:6.3.9600.17415 (winblue_r4.141028-1500):Microsoft Corporation 		DBGHELP.DLL:Windows Image Helper:6.3.9600.20369 (winblue_ltsb_escrow.220427-1727):Microsoft Corporation 		DEVOBJ.dll:Device Information Set DLL:6.3.9600.17415 (winblue_r4.141028-1500):Microsoft Corporation 		DNSAPI.dll:DNS Client API DLL:6.3.9600.16384 (winblue_rtm.130821-1623):Microsoft Corporation 		GDI32.dll:GDI Client DLL:6.3.9600.20716 (winblue_ltsb_escrow.221107-1755):Microsoft Corporation 		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:6.3.9600.17415 (winblue_r4.141028-1500):Microsoft Corporation 		IPHLPAPI.DLL:IP Helper API:6.3.9600.16384 (winblue_rtm.130821-1623):Microsoft Corporation 		KERNEL32.DLL:Windows NT BASE API Client DLL:6.3.9600.18217 (winblue_ltsb.160124-0053):Microsoft Corporation 		KERNELBASE.dll:Windows NT BASE API Client DLL:6.3.9600.20371 (winblue_ltsb_escrow.220429-1726):Microsoft Corporation 		MSASN1.dll:ASN.1 Runtime APIs:6.3.9600.20664 (winblue_ltsb_escrow.221012-1728):Microsoft Corporation 		MSCTF.dll:MSCTF Server DLL:6.3.9600.16384 (winblue_rtm.130821-1623):Microsoft Corporation 		NLAapi.dll:Network Location Awareness 2:6.3.9600.18895 (winblue_ltsb.180101-1800):Microsoft Corporation 		NSI.dll:NSI User-mode interface DLL:6.3.9600.17415 (winblue_r4.141028-1500):Microsoft Corporation 		NTASN1.dll:Microsoft ASN.1 API:6.3.9600.16384 (winblue_rtm.130821-1623):Microsoft Corporation 		Ole32.dll:Microsoft OLE for Windows:6.3.9600.20144 (winblue_ltsb_escrow.211004-1908):Microsoft Corporation 		OleAut32.dll::6.3.9600.20016:Microsoft Corporation 		PSAPI.DLL:Process Status Helper:6.3.9600.17415 (winblue_r4.141028-1500):Microsoft Corporation 		Pdh.dll:Windows Performance Data Helper DLL:6.3.9600.16384 (winblue_rtm.130821-1623):Microsoft Corporation 		RPCRT4.dll:Remote Procedure Call Runtime:6.3.9600.16384 (winblue_rtm.130821-1623):Microsoft Corporation 		SHCORE.dll:SHCORE:6.3.9600.16384 (winblue_rtm.130821-1623):Microsoft Corporation 		SHELL32.dll:Windows Shell Common Dll:6.3.9600.17031 (winblue_gdr.140221-1952):Microsoft Corporation 		SHLWAPI.dll:Shell Light-weight Utility Library:6.3.9600.16384 (winblue_rtm.130821-1623):Microsoft Corporation 		SspiCli.dll:Security Support Provider Interface:6.3.9600.20616 (winblue_ltsb_escrow.220912-1746):Microsoft Corporation 		USER32.dll:Multi-User Windows USER API Client DLL:6.3.9600.16384 (winblue_rtm.130821-1623):Microsoft Corporation 		USERENV.dll:Userenv:6.3.9600.16384 (winblue_rtm.130821-1623):Microsoft Corporation 		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation 		VERSION.dll:Version Checking and File Installation Libraries:6.3.9600.17415 (winblue_r4.141028-1500):Microsoft Corporation 		WINHTTP.dll:Windows HTTP Services:6.3.9600.16384 (winblue_rtm.130821-1623):Microsoft Corporation 		WINMM.dll:MCI API DLL:6.3.9600.16384 (winblue_rtm.130821-1623):Microsoft Corporation 		WINMMBASE.dll:Base Multimedia Extension API DLL:6.3.9600.16384 (winblue_rtm.130821-1623):Microsoft Corporation 		WINNSI.DLL:Network Store Information RPC interface:6.3.9600.17415 (winblue_r4.141028-1500):Microsoft Corporation 		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:6.3.9600.16384 (winblue_rtm.130821-1623):Microsoft Corporation 		WSOCK32.dll:Windows Socket 32-Bit DLL:6.3.9600.16384 (winblue_rtm.130821-1623):Microsoft Corporation 		api-ms-win-crt-convert-l1-1-0.dll:ApiSet Stub DLL:10.0.22000.194 (WinBuild.160101.0800):Microsoft Corporation 		api-ms-win-crt-environment-l1-1-0.dll:ApiSet Stub DLL:10.0.22000.194 (WinBuild.160101.0800):Microsoft Corporation 		api-ms-win-crt-filesystem-l1-1-0.dll:ApiSet Stub DLL:10.0.22000.194 (WinBuild.160101.0800):Microsoft Corporation 		api-ms-win-crt-heap-l1-1-0.dll:ApiSet Stub DLL:10.0.22000.194 (WinBuild.160101.0800):Microsoft Corporation 		api-ms-win-crt-locale-l1-1-0.dll:ApiSet Stub DLL:10.0.22000.194 (WinBuild.160101.0800):Microsoft Corporation 		api-ms-win-crt-math-l1-1-0.dll:ApiSet Stub DLL:10.0.22000.194 (WinBuild.160101.0800):Microsoft Corporation 		api-ms-win-crt-runtime-l1-1-0.dll:ApiSet Stub DLL:10.0.22000.194 (WinBuild.160101.0800):Microsoft Corporation 		api-ms-win-crt-stdio-l1-1-0.dll:ApiSet Stub DLL:10.0.22000.194 (WinBuild.160101.0800):Microsoft Corporation 		api-ms-win-crt-string-l1-1-0.dll:ApiSet Stub DLL:10.0.22000.194 (WinBuild.160101.0800):Microsoft Corporation 		api-ms-win-crt-time-l1-1-0.dll:ApiSet Stub DLL:10.0.22000.194 (WinBuild.160101.0800):Microsoft Corporation 		api-ms-win-crt-utility-l1-1-0.dll:ApiSet Stub DLL:10.0.22000.194 (WinBuild.160101.0800):Microsoft Corporation 		apphelp.dll:Application Compatibility Client Library:6.3.9600.16384 (winblue_rtm.130821-1623):Microsoft Corporation 		awt.dll:OpenJDK Platform binary:17.0.3.0:Microsoft 		bcrypt.dll:Windows Cryptographic Primitives Library:6.3.9600.16384 (winblue_rtm.130821-1623):Microsoft Corporation 		bcryptprimitives.dll:Windows Cryptographic Primitives Library:6.3.9600.20517 (winblue_ltsb_escrow.220725-1737):Microsoft Corporation 		cfgmgr32.dll:Configuration Manager DLL:6.3.9600.17415 (winblue_r4.141028-1500):Microsoft Corporation 		clbcatq.dll:COM+ Configuration Catalog:2001.12.10530.17415 (winblue_r4.141028-1500):Microsoft Corporation 		combase.dll:Microsoft COM for Windows:6.3.9600.20625 (winblue_ltsb_escrow.221003-0335):Microsoft Corporation 		dhcpcsvc.DLL:DHCP Client Service:6.3.9600.16384 (winblue_rtm.130821-1623):Microsoft Corporation 		dhcpcsvc6.DLL:DHCPv6 Client:6.3.9600.16384 (winblue_rtm.130821-1623):Microsoft Corporation 		fwpuclnt.dll:FWP/IPsec User-Mode API:6.3.9600.16384 (winblue_rtm.130821-1623):Microsoft Corporation 		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW 		java.dll:OpenJDK Platform binary:17.0.3.0:Microsoft 		javaw.exe:OpenJDK Platform binary:17.0.3.0:Microsoft 		jemalloc.dll 		jimage.dll:OpenJDK Platform binary:17.0.3.0:Microsoft 		jli.dll:OpenJDK Platform binary:17.0.3.0:Microsoft 		jna17453035549483723218.dll:JNA native library:6.1.4:Java(TM) Native Access (JNA) 		jsvml.dll:OpenJDK Platform binary:17.0.3.0:Microsoft 		jvm.dll:OpenJDK 64-Bit server VM:17.0.3.0:Microsoft 		kernel.appcore.dll:AppModel API Host:6.3.9600.17415 (winblue_r4.141028-1500):Microsoft Corporation 		lwjgl.dll 		management.dll:OpenJDK Platform binary:17.0.3.0:Microsoft 		management_ext.dll:OpenJDK Platform binary:17.0.3.0:Microsoft 		msvcp140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation 		msvcrt.dll:Windows NT CRT DLL:7.0.9600.17415 (winblue_r4.141028-1500):Microsoft Corporation 		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:6.3.9600.16384 (winblue_rtm.130821-1623):Microsoft Corporation 		napinsp.dll:E-mail Naming Shim Provider:6.3.9600.16384 (winblue_rtm.130821-1623):Microsoft Corporation 		ncrypt.dll:Windows NCrypt Router:6.3.9600.16384 (winblue_rtm.130821-1623):Microsoft Corporation 		net.dll:OpenJDK Platform binary:17.0.3.0:Microsoft 		nio.dll:OpenJDK Platform binary:17.0.3.0:Microsoft 		ntdll.dll:NT Layer DLL:6.3.9600.20302 (winblue_ltsb_escrow.220222-1158):Microsoft Corporation 		ntmarta.dll:Windows NT MARTA provider:6.3.9600.16384 (winblue_rtm.130821-1623):Microsoft Corporation 		perfos.dll:Windows System Performance Objects DLL:6.3.9600.16384 (winblue_rtm.130821-1623):Microsoft Corporation 		pnrpnsp.dll:PNRP Name Space Provider:6.3.9600.16384 (winblue_rtm.130821-1623):Microsoft Corporation 		profapi.dll:User Profile Basic API:6.3.9600.17415 (winblue_r4.141028-1500):Microsoft Corporation 		rasadhlp.dll:Remote Access AutoDial Helper:6.3.9600.17415 (winblue_r4.141028-1500):Microsoft Corporation 		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:6.3.9600.16384 (winblue_rtm.130821-1623):Microsoft Corporation 		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:6.3.9600.16384 (winblue_rtm.130821-1623):Microsoft Corporation 		sunmscapi.dll:OpenJDK Platform binary:17.0.3.0:Microsoft 		ucrtbase.DLL:Microsoft® C Runtime Library:10.0.22000.194 (WinBuild.160101.0800):Microsoft Corporation 		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation 		verify.dll:OpenJDK Platform binary:17.0.3.0:Microsoft 		winrnr.dll:LDAP RnR Provider DLL:6.3.9600.16384 (winblue_rtm.130821-1623):Microsoft Corporation 		zip.dll:OpenJDK Platform binary:17.0.3.0:Microsoft Stacktrace: 	at net.minecraft.client.main.Main.method_44604(Main.java:205) 	at net.minecraft.client.main.Main.main(Main.java:51) 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)  -- System Details -- Details: 	Minecraft Version: 1.19.3 	Minecraft Version ID: 1.19.3 	Operating System: Windows 8.1 (amd64) version 6.3 	Java Version: 17.0.3, Microsoft 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft 	Memory: 654442056 bytes (624 MiB) / 1409286144 bytes (1344 MiB) up to 2147483648 bytes (2048 MiB) 	CPUs: 4 	Processor Vendor: GenuineIntel 	Processor Name: Intel(R) Pentium(R) CPU  J2900  @ 2.41GHz 	Identifier: Intel64 Family 6 Model 55 Stepping 8 	Microarchitecture: Silvermont 	Frequency (GHz): 2.42 	Number of physical packages: 1 	Number of physical CPUs: 4 	Number of logical CPUs: 4 	Graphics card #0 name: Intel(R) HD Graphics 	Graphics card #0 vendor: Intel Corporation (0x8086) 	Graphics card #0 VRAM (MB): 2112.00 	Graphics card #0 deviceId: 0x0f31 	Graphics card #0 versionInfo: DriverVersion=10.18.10.3993 	Memory slot #0 capacity (MB): 8192.00 	Memory slot #0 clockSpeed (GHz): 1.60 	Memory slot #0 type: Unknown 	Virtual memory max (MB): 20610.96 	Virtual memory used (MB): 8373.93 	Swap memory total (MB): 12538.15 	Swap memory used (MB): 2089.89 	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M 	Fabric Mods:  		advancementinfo: AdvancementInfo 1.19.3-fabric0.68.1-1.3.1 		advancementscreenshot: Advancement Screenshot 4.0 		ae2: Applied Energistics 2 13.0.6-beta 			noindium: No Indium? 1.1.0+1.19 			team_reborn_energy: Energy 2.0.0-beta1 		ae2additions: AEAdditions 4.0.0-fabric 		ae2ao: AE2AO 14.0.0 		ae2wtlib: AE2WTLib 13.0.6-beta 		appleskin: AppleSkin 2.4.2+mc1.19.3 		architectury: Architectury 7.1.86 		balm-fabric: Balm 5.0.4 		bookshelf: Bookshelf 17.0.3 		carryon: Carry On 2.0.4.15 			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.1 		catalogue: Catalogue 1.7.0-1.19.3 		cem: Custom Entity Models 0.7.1 			completeconfig-base: completeconfig-base 2.2.0 			completeconfig-gui-cloth: completeconfig-gui-cloth 2.2.0 		citresewn: CIT Resewn 1.1.3+1.19.3 			citresewn-defaults: CIT Resewn: Defaults 1.1.3+1.19.3 		cloth-config: Cloth Config v9 9.0.94 			cloth-basic-math: cloth-basic-math 0.6.1 		collective: Collective 6.55 		compressed: Compressed 1.8.0 		configured: Configured 2.0.0 		controlling: Controlling For Fabric 10.0+9 		darkness: True Darkness 2.0.103 		extended_drawers: Extended Drawers 1.4.1+mc.1.19.3 			graphlib: Graph Lib 0.4.4+1.19.3 			mconfig: Mconfig 1.2.0+mc.1.19-rc1 				de_poiu_apron_apron: apron 2.1.1 				fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT 		fabric-api: Fabric API 0.76.1+1.19.3 			fabric-api-base: Fabric API Base 0.4.21+70be179c85 			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.20+49abcf7e85 			fabric-biome-api-v1: Fabric Biome API (v1) 12.1.2+f1c68e5885 			fabric-block-api-v1: Fabric Block API (v1) 1.0.5+e022e5d185 			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.31+928d44d585 			fabric-client-tags-api-v1: Fabric Client Tags 1.0.12+1134c5b885 			fabric-command-api-v1: Fabric Command API (v1) 1.2.23+f71b366f85 			fabric-command-api-v2: Fabric Command API (v2) 2.2.2+2961b4a085 			fabric-commands-v0: Fabric Commands (v0) 0.2.40+df3654b385 			fabric-containers-v0: Fabric Containers (v0) 0.1.47+df3654b385 			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.3+1d37d50285 			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+521b5c5285 			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.14+aeb40ebe85 			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.3.3+40dc7a9485 			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.42+00a2eb1085 			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.7+b83334a085 			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.40+3baeb27a85 			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.45+df3654b385 			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.30+99f9db8085 			fabric-item-api-v1: Fabric Item API (v1) 2.1.11+71b8257385 			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.14+b5470ac785 			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.31+bc01e09785 			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.29+df3654b385 			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.10+23a79c8a85 			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.22+75e9821185 			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.26+9e7660c685 			fabric-message-api-v1: Fabric Message API (v1) 5.1.0+c85585f885 			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.33+49abcf7e85 			fabric-models-v0: Fabric Models (v0) 0.3.27+11ba9c3b85 			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.17+4017a8cb85 			fabric-networking-v0: Fabric Networking (v0) 0.3.34+df3654b385 			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.4.3+eb2a3ba985 			fabric-particles-v1: Fabric Particles (v1) 1.0.20+f1e4495b85 			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+5176f73d85 			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.1.0+f7b4d36485 			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.2+3a95925a85 			fabric-renderer-indigo: Fabric Renderer - Indigo 0.8.0+3a95925a85 			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.31+df3654b385 			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.25+afca2f3e85 			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.18+f1e4495b85 			fabric-rendering-v0: Fabric Rendering (v0) 1.1.34+df3654b385 			fabric-rendering-v1: Fabric Rendering (v1) 1.13.0+ad17775585 			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.0+e63306e085 			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.1+b93ffe4d85 			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.41+f1e4495b85 			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.13+99f9db8085 			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.8+75e9821185 			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.15+ccd377ba85 			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.3.1+40dc7a9485 		fabric-language-kotlin: Fabric Language Kotlin 1.9.0+kotlin.1.8.0 			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.0 			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.0 			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.0 			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.0 			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5 			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4 			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4 			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0 			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1 			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1 			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1 		fabricloader: Fabric Loader 0.14.21 		fallingleaves: Falling Leaves 1.14.5+1.19.3 		fluidvoidfading: Fluid Void Fading 1.1.0 		forgeconfigapiport: Forge Config API Port 5.0.7 			com_electronwill_night-config_core: core 3.6.5 			com_electronwill_night-config_toml: toml 3.6.5 		highlighter: Highlighter 1.1.4 		iceberg: Iceberg 1.1.4 		inventoryprofilesnext: Inventory Profiles Next 1.9.2 		iris: Iris 1.5.1 			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre8 			org_anarres_jcpp: jcpp 1.4.14 			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1 		jade: Jade 9.2.0 		jamlib: JamLib 0.6.0+1.19.3 		java: OpenJDK 64-Bit Server VM 17 		jei: Just Enough Items 12.1.1.13 		jepp: Just Enough Painting Previews 1.19.2-1.1.0 		jeresources: Just Enough Resources 1.3.2.210 		journeymap: Journeymap 5.9.2 			journeymap-api-fabric: JourneyMap API 1.19.3-1.9-fabric-SNAPSHOT 		justenoughprofessions: Just Enough Professions (JEP) 2.2.0 		kleeslabs: KleeSlabs 13.1.0 		lambdynlights: LambDynamicLights 2.2.0+1.19.3 			pride: Pride Lib 1.2.0+1.19.3 			spruceui: SpruceUI 4.1.0+1.19.3 		leavesbegone: Leaves Be Gone 5.0.0 		libipn: libIPN 2.0.2 		lightoverlay: Light Overlay 7.0.2 		logical_zoom: Logical Zoom 0.0.18 		measurements: Measurements 1.4.1 		megacells: MEGA Cells 1.5.3-1.19.2 		merequester: ME Requester 1.19.2-1.1.2 			midnightlib: MidnightLib 0.6.0 		minecraft: Minecraft 1.19.3 		mousetweaks: Mouse Tweaks 2.24 		notes: Notes 1.19.3-2.0.0-fabric 		patchouli: Patchouli 1.19.3-78-FABRIC 			fiber: fiber 0.23.0-2 		pling: Pling 1.6.0 		puzzleslib: Puzzles Lib 5.0.33 		reeses-sodium-options: Reese's Sodium Options 1.4.9+mc1.19.2-build.67 		rightclickharvest: Right Click Harvest 3.2.2+1.19.x-1.20.1-fabric 		sodium: Sodium 0.4.8+build.22 		sodium-extra: Sodium Extra 0.4.16+mc1.19.3-build.91 			caffeineconfig: CaffeineConfig 1.0.0+1.17 		tipsmod: Tips 9.0.3 		travelerstitles: Traveler's Titles 1.19.3-Fabric-3.2.0 			org_reflections_reflections: reflections 0.10.2 		veindigging: VeinDigging 1.0.1 		youritemsaresafe: Your Items Are Safe 3.2 		yungsapi: YUNG's API 1.19.3-Fabric-3.9.0 			org_javassist_javassist: javassist 3.28.0-GA 	Launched Version: fabric-loader-0.14.21-1.19.3 	Backend library: LWJGL version 3.3.1 SNAPSHOT 	Backend API: Unknown 	Window size: <not initialized> 	GL Caps: Using framebuffer using OpenGL 3.2 	GL debug messages: <disabled> 	Using VBOs: Yes 	Is Modded: Definitely; Client brand changed to 'fabric' 	Type: Client (map_client.txt) 	CPU: <unknown>

**Comment by Technici4n** [comment]
ME Requester crash, not AE2 crash.

**Comment by JumperK** [comment]
> Reference

Tysm
