### ISSUE TITLE
item to remove channels or add

### ISSUE THREAD

**Issue by Goten87** [AppliedEnergistics/Applied-Energistics-2#723]
hello EA 2 devs i love the mod and i love the new setting for disabeling channels
but i have a friend server and some of my friend like the channels
is there a way to make the setting a item
like when you add that item to your network it will do channels or remove them
so we dont need to have the setting anymore but let the player deside if it wants it

**Comment by yueh** [comment]
Not possible as disabling channels will also remove items and blocks needed for channels.

**Comment by asgdfagdsfg** [comment]
Why is it not possible, when AE1 ran PERFECTLY without channels?
Those stupid excuses...
You are supposed to ADD stuff, NOT REMOVE stuff...
Developers these days... all such idiots...
Seriously, not only here, games all over the world, from 8 year old timmy, who is making his first sc2 map, to Blizzard online entertainment... EVERYWHERE developers REMOVE things from their game, and call it IMPROVEMENT... WHAT the fuck is up with you people? Seriously, i don't even WANT to hate on you, but what i REALLY want (besides playing my gosh darn minecraft in piece) is to UNDERSTAND, why SO MANY people do this... do you people seriously believe, that you are making things better? I know in some cases it's obviously money, but here for example... the devs are wasting their free time to ruin something, just like griefers, who usually give up after an hour, and don't... spend like hundreds of hours on it...
Just so you guys know, you are NOT making things better, you SUCK!
