### ISSUE TITLE
ME export bus

### ISSUE THREAD

**Issue by iiJonno** [AppliedEnergistics/Applied-Energistics-2#7231]
### Describe the bug

when using export bus in ATM9 only the 1st slot exports all others do nothing

### How to reproduce the bug

export multiple items

### Expected behavior

they export

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

https://mclo.gs/F7undBw

**Comment by 62832** [comment]
Toggle round-robin mode on.

**Comment by iiJonno** [comment]
![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/127353505/9df85135-4ad7-4e44-a789-3b04d528febd)

how do i toggle round robin, even when there is only 1 thing to export it doesnt work unless in slot 1

**Comment by 62832** [comment]
My mistake, I didn't realise that had gone away for some reason.

**Comment by iiJonno** [comment]
it doesnt show with more items in either

**Comment by iiJonno** [comment]
![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/127353505/a69b6d0c-d43c-413b-8359-4695afb3428e)

**Comment by iiJonno** [comment]
not totally sure i usually use RS as im not a fan of type limit or channels so im kinda ae2 noob

**Comment by iiJonno** [comment]
everything still seems to work fine can autocraft and the import bus works

**Comment by iiJonno** [comment]
ive tried exporting to vanilla chest, sophisticated chest, barrel, backpack, dim storage chest and still only slot 1 working

**Comment by iiJonno** [comment]
yes that works it shows up and multiple slots work

**Comment by 62832** [comment]
Does the initial issue of slots other than the first not working also go away when the capacity card is fitted?

**Comment by iiJonno** [comment]
yes all issues solved with cap card

**Comment by iiJonno** [comment]
when cap card removed issues come back

**Comment by iiJonno** [comment]
brilliant thankyou

**Comment by iiJonno** [comment]
after further playing only the first 5 slots work with 1 capacity card if i add another cap card the next 5 also work and so on, not sure if your fix will have also fixed this so just letting you know incase

**Comment by 62832** [comment]
I assumed this was already the case given the prior code, and the change should fully reflect the new config menu and mean this no longer is an issue.
