### ISSUE TITLE
[1.20.1] Roughly Enough Items incompatibility on Forge

### ISSUE THREAD

**Issue by FlashHUN** [AppliedEnergistics/Applied-Energistics-2#7233]
### Describe the bug

Installing Roughly Enough Items (12.0.625, REIPluginCompatibilities 12.0.54) alongside AE2 (15.0.2-alpha) crashes the game before it even loads.

### How to reproduce the bug

1. Install the following mods:
    - Applied Energistics 2 version 15.0.2-alpha
    - Roughly Enough Items version 12.0.625, REIPluginCompatibilities version 12.0.54
2. Launch the game
3. `Process crashed with exit code 1` - there's no crash report and the logs aren't detailed enough on my end, however the built-in output log of the Minecraft launcher does provide more context (linked at the Crash log section)

### Expected behavior

The game should launch without issues

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/QRKhwweN

**Comment by Technici4n** [comment]
REIPC needs to update the JEI version range it provides.
