### ISSUE TITLE
Mod incompatibility

### ISSUE THREAD

**Issue by bomxacalaka** [AppliedEnergistics/Applied-Energistics-2#7234]
### Describe the bug

Install vivecraft with ae2 results in game to crash

### How to reproduce the bug

1 - Install Vivecraft with forge 1.19.2 (I tried a few forge versions compatible with AE2)
2 - run minecraft to setup all files and folders
3 - add appliedenergistics2-forge-12.9.5.jar to mods folder
4 - run minecraft
5 - crash

### Expected behavior

Play VR games with AE2

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

appliedenergistics2-forge-12.9.5.jar

**Comment by Technici4n** [comment]
vivecraft problem
