### ISSUE TITLE
storage cell overfilled

### ISSUE THREAD

**Issue by drumattic** [AppliedEnergistics/Applied-Energistics-2#724]
hi, it seems that the 64 storage cells has no bytes limit (don't know for the others)
screen here : http://www.noelshack.com/2015-03-1421077945-2015-01-12-16-51-15.png

i'm playing singleplayer with the hermitcraft modsauce 1.0.1.1 (atlauncher)

**Comment by yueh** [comment]
There was a bug with an incorrect calculation for the sizes (#225).
Cells can overfill and do not loose any items, but you cannot put more items into them until it is below the limit.

**Comment by drumattic** [comment]
ok but the calculation of the size seems to be correct with my version...

**Comment by Cisien** [comment]
If you filled up the cell in rv1, then updated to rv2 you will see this. You can't insert any more items into the cell until you drop below the 64k limit.
