### ISSUE TITLE
Missing Texture Blocks in Fabric 15.0.3-alpha

### ISSUE THREAD

**Issue by MajesticMrPanda** [AppliedEnergistics/Applied-Energistics-2#7241]
### Describe the bug

Not sure if it's actually a bug or an issue with some other mod, but I only knew to send this in here. If it is a bug at least now you all will know about it. 15.0.3-alpha for Fabric using the latest Fabric loader and 1.20.1 is giving me a Missing Texture Block for all blocks within AE2. Again, not sure if this is a bug, simply something to expectedly deal with given the alpha status, or if I am dealing with a collision between mods. 

### How to reproduce the bug

Simply place any block down into the world. 

### Expected behavior

A rendered AE2 texture.

### Additional details

Thank you all so much for all of your work. I love this mod! I've included a screenshot of the missing textures with all the blocks on my toolbelt as well as one of the Facades tab.
![2023-06-27_18 41 19](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/137962320/d1dcca1f-6106-45d2-8a14-a57cb09981e6)
![2023-06-27_18 41 27](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/137962320/bca96488-73e9-434a-8e22-0aa45053591a)

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/YxhL3NN0

**Comment by Mari023** [comment]
install indium to fix this

**Comment by MajesticMrPanda** [comment]
Awesome, thank you so much
