### ISSUE TITLE
Documentation of Sky Stone is incorrect

### ISSUE THREAD

**Issue by a-a-GiTHuB-a-a** [AppliedEnergistics/Applied-Energistics-2#7245]
Sky Stone can be mined with an iron pick, but the documentation says a diamond pick is required.

**Comment by mindforger** [comment]
Why did you ignore the templates?

**Comment by Technici4n** [comment]
No idea if this is about the guidebook or the wiki.

**Comment by a-a-GiTHuB-a-a** [comment]
The website appliedenergistics2.github.io, so I guess it's the wiki? I'm going to close this because it was wayyy too unclear in the original post.
