### ISSUE TITLE
Power slowly increasing infinitely

### ISSUE THREAD

**Issue by DDock** [AppliedEnergistics/Applied-Energistics-2#725]
I am trying to figure out why this is happening. Seems the more base power it uses the faster it ramps up. In roughly one day the ME system requires over 20k rf/t which is the maximum enderio's conduits allow. The only way to reset how much power it uses is to restart the server. After restart, the network uses 700-800 rf/t which is normal. Network isn't a huge one. Have 80ish barrels with Storage Bus', 4 crafting Terminals, 5 ME Interface, 100 covered fluix cable, and 150 me conduit (enderio). Seems this issue happens every time the chunk loads. Any thoughts how to diagnose this further? If someone willing to help wants to join my server I can pm the information and show them my setup.

**Comment by yueh** [comment]
Please remove the EnderIO ME conduits and test it again.
They are a bit buggy and I think one of them was constantly adding new "cables" as long as the server runs.

I would also recommend that you use a network tool to check how many devices are on your network.
Even better would be a screenshot before and after the server restart and add it here.

**Comment by DDock** [comment]
Thank you so much. I look with the network tool before/after a restart and that looks like it is the problem. Went from 300ish me conduits to 111 after restart.

**Comment by kurokuno** [comment]
i had over 9000 conduits last night from this bug i can however say its to do with chunkloading if any 1 part of the conduit becomes unloaded it creates infinate new ones in its place

**Comment by tterrag1098** [comment]
I would appreciate assistance in solving this issue as I'm not sure why my grid nodes are sticking around.
