### ISSUE TITLE
[1.20.1]Breake access transformer

### ISSUE THREAD

**Issue by Rumaruka** [AppliedEnergistics/Applied-Energistics-2#7250]
### Describe the bug

Modpack runs for Minecraft 1.20.1
Reaches the "Loading Boostrap resources" stage and freezes in place

### How to reproduce the bug

I don`t know how to reproduce these bugs, im just runs modpack
![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/8148679/da60c8c4-f827-48fd-8e31-bd7e33745ed3)

### Expected behavior

Just setup mod

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

Lastest: https://gist.github.com/Rumaruka/8e5c44ca5f0c88e33c82cb494b65035a . debug: https://gist.github.com/Rumaruka/4fc70bc405f0736746975bbea5813077

**Comment by Technici4n** [comment]
Not an AE2 problem.
