### ISSUE TITLE
Wireless terminal 1.20 auto dies with me system

### ISSUE THREAD

**Issue by Steve8MC** [AppliedEnergistics/Applied-Energistics-2#7254]
### Describe the bug

when my me system run out of power and my wireless terminal is full the terminal just drops to 0.0% power

### How to reproduce the bug

the wireless terminal just dies with the me system

### Expected behavior

it's very annoying

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Fabric

### Crash log

https://gist.github.com/Steve8MC/14b16361d23b9a5d079ed9c5614d3ba0

**Comment by Mari023** [comment]
does this also happen without ae2wtlib?
