### ISSUE TITLE
Idea Tier 2 Portable Cell

### ISSUE THREAD

**Issue by kurokuno** [AppliedEnergistics/Applied-Energistics-2#726]
it would use an ME Drive Dense energy Cell and 64k to craft(adjustable based on what the devs think balanced is) giving 63 item types and probably 32k storage just right now it feels like since it went down to 27 types bags from other mods are just better in most ways unless attempting mass storage

**Comment by AlgorithmX2** [comment]
I previously rejected a similar request, the size and design of the Portable Cell were carefully selected to not impact general game-play while still giving the player a useful tool, that is why it appears abnormally limited in comparison to non-portable cells.

Its purpose wasn't to provide a ME Network on the go, it was more designed to make extended journeys and mining trips more reasonable with tech level.

Carrying around a full size 32k storage cell will basically make mining trips never end until you get board of mining, this was not the intention as it drastically alters the game-play of mining trips and expeditions.

What other mods do or don't do has no bearing on AE2's design, we don't care if another mod lets you carry your base around on your back, or not, that is not AE2's Style. I could just as easily use other mods as an excuse to remove the portable cell all together.

**Comment by kurokuno** [comment]
thankyou for replying so fast... i am very sorry if i some how offended you as it was not my intention it was just a suggestion that when looking in the previous suggestions i did not see i am very sorry if my idea came across as insulting and again thankyou for the fast reply

**Comment by AlgorithmX2** [comment]
I was not offended in anyway, I was merely attempting to explain our stance on things rather then simply saying "rejected'.

I'll go ahead and close this.
