### ISSUE TITLE
Bug Or Question

### ISSUE THREAD

**Issue by gameplayoffert** [AppliedEnergistics/Applied-Energistics-2#7269]
### Describe the bug

Hi, i don't know if that is a bug or not but i was a fan of AE2 in 1.12.2 especially with the "Creative Cell" to store infinite items type and count inside a network. I wanted to try that  in 1.20.1 but sadly it's not possible so can i know if that is a bug or not ? And if not, then can i know why this awesome feature has been removed ?

**Comment by Sea-Kerman** [comment]
AFAIK the creative cell was always infinite vending, not infinite storage. AFAIK there has never been an infinite storage cell for AE2, besides perhaps MEGA’s bulk storage cell, which stores max long of 1 type.

**Comment by Technici4n** [comment]
Indeed, it was never possible to store infinite types - just creative vending.

**Comment by gameplayoffert** [comment]
Ok, i checked in an older version and i thought i was possible but it's not so sorry for that. Otherwise is there a mod to store infinite storage or not ?
