### ISSUE TITLE
Guidebook change hotkey

### ISSUE THREAD

**Issue by hallool** [AppliedEnergistics/Applied-Energistics-2#7270]
### Describe the feature

is there a way to change the guide book hotkey? bcs W is anoying.. or disable completely

### Reasons why it should be considered

bcs W is anoying as a hotkey...

**Comment by hallool** [comment]
i gues theres no hotkey implementation? or is another mod doing this?

**Comment by hallool** [comment]
i think it would be more than welkome if there is an way of diong it i mean u cant even move with a create or ae2 item in ur hand..   i hope it works thx for the response

**Comment by hallool** [comment]
Yeah lets say im buiding idknow Auto crafting i Pick the item in the hotbar the i need to wait til the tooltip closes away to Mode it is pretty anoying if u bild  and normaly u switch alot from Tool to item in the hotbar. I dont know if u unverstanden my englich is not that good 🤷‍♂️

**Comment by 62832** [comment]
This has now been implemented as of AE2 15.0.10.
