### ISSUE TITLE
Issues with Forge Compatability

### ISSUE THREAD

**Issue by Meepin** [AppliedEnergistics/Applied-Energistics-2#7276]
### Describe the bug

Getting a launch error stating a mismatched forge version, "Mod ID: 'forge', Requested by: 'ae2', Expected range: '[47.0.1,47.1.3]', Actual version: '47.1.30'" I assume the range was typo-ed and looking for 47.1.30 rather than 47.1.3

### How to reproduce the bug

Launch AE on the newest version with newer version of Forge through Curseforge

### Expected behavior

Not have mismatching version requirements

### Additional details

![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/5864626/d3383634-bf2c-4c8d-9bf4-fc387ea4421a)

### Which minecraft version are you using?

MC Version 1.20.1. - Mod Version 15.0.5 Beta on Forge 47.1.30

### On which mod loaders does it happen?

Forge

### Crash log

No Crash log because of error during initialization, major snippet of error quoted in bug report

**Comment by Technici4n** [comment]
We do not support versions above Forge 47.1.3. You should downgrade Forge to that version.

**Comment by Meepin** [comment]
The issue is that version 15.0.4 beta does support it and loads properly

**Comment by Technici4n** [comment]
It doesn't matter. We won't support it going forward.
