### ISSUE TITLE
Energy cell RF Level Emmitter

### ISSUE THREAD

**Issue by dylanpiera** [AppliedEnergistics/Applied-Energistics-2#728]
I have a big reactor just for my AE network, And what i want it to do, When my AE power is almost down (15-20% left in energy cells) to output a redstone signal, Like the level emmiter 

This might be a nice feature in ae!

**Comment by kurokuno** [comment]
i second this idea!!



in the short term however dylanpiera you can use 2 redstone ports on the reactor one thats on from input and one that outputs on % to just tell the reactor to keep its self above a %

**Comment by yueh** [comment]
Already supported by the level emitter if you mean our own energy type AE.

**Comment by dylanpiera** [comment]
How do i do it with AE then, Cause thats what i mean?

**Comment by Cisien** [comment]
AE has no knowledge of the RF storage, and the storage is specific per mod.

The level emitter only supports ae's internal power type.

To judge power levels for cells you will need to use a comparator for thermal expansion, or a power monitor for enderio. As suggested earlier, you could then use Redstone p2p busses to move the signal to your reactor to control it.

**Comment by dylanpiera** [comment]
thats what i mean how do you emmit the internal energie

**Comment by AlgorithmX2** [comment]
There is a setting on the side of the level emitter to select "energy mode" instead of item mode, this lets you enter a specific energy level and output based on that.

**Comment by dylanpiera** [comment]
got it thanks!
