### ISSUE TITLE
Auto-Crafting stuck at Scheduled, item crafted but not returned

### ISSUE THREAD

**Issue by RetroAndDev** [AppliedEnergistics/Applied-Energistics-2#7280]
### Describe the bug

Tried to craft a block of diamond with a basic auto craft setup
The block is crafted inside the Molecular Assembler but never returned to the ME Pattern Provider
Works with ME Import bus if connected to Molecular Assembler

Here is my crafting setup : 
9 Diamond -> 1 block of Diamond
[MA] = Molecular Assembler / [PP] = Patern Provider / - Air block
I have two stacked like this : 
------[MA]
[MA]-[PP]-[MA]
------[MA]

Inside the CPU, crafting status is at "Scheduled'

### How to reproduce the bug

Make a basic autocrafting and try
Worked in 12.5.2-beta (1.19.2) and optifine
Not work above 12.5.2-beta (as far I tested) (1.19.2) with optifine
Works (1.19.2) without optifine

### Expected behavior

Crafted Item need to send to the AE system after being crafted

### Additional details

I absolutely need Optifine (for YouTube/records and more performances/details) and I can't use 12.5.2-beta on my primary game due to mods add-ons for AE2

Note : I am on an Apple Sillicon based MacBook Pro with MultiMC and Java from Azul Builds for macs-arm64 (JDK-19)

Screenshots : 
![2023-07-19_14 22 07](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/56597499/6abcf099-0631-4a75-8b2d-2cbbf6e5db19)
![2023-07-19_14 22 02](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/56597499/bb5f176a-b187-4edd-ae01-b3f6af8c8120)
![2023-07-19_14 21 58](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/56597499/3b83bb12-bfc9-4a76-ab2e-19d08d76558e)

Any solution/fix to make it working ?

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/RetroAndDev/ae03b546515e5748ab133c4ba874acfa

**Comment by Technici4n** [comment]
>  Works (1.19.2) without optifine

There you go, remove optifine. It breaks this.

**Comment by RetroAndDev** [comment]
Ok, thanks.
it's really uncool from the Optifine developers not to make it open-source...
This is a very strange issue, not present before 12.6.0 with laset optifine for 1.19.2
