### ISSUE TITLE
Game won't launch because the mod figures it needs the older version of Forge

### ISSUE THREAD

**Issue by NewAgeSoldier** [AppliedEnergistics/Applied-Energistics-2#7289]
### How to reproduce the performance issue

Install AE2, have Forge 47.1.27 and higher

In fact : Mod ID: 'forge', Requested by: 'ae2', Expected range: '[47.0.1,47.1.3]', Actual version: '47.1.26'

### Spark profile link

I can't provide a spark link as I can't get in the game

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Additional details

This is highly annoying

**Comment by NewAgeSoldier** [comment]
Forgot to add that I am now on AE2 : 15.0.5

**Comment by NewAgeSoldier** [comment]
> There is literally a pinned issue #7278

Ah, I should use my eyes a bit more often.... Thanks!

**Comment by NewAgeSoldier** [comment]
> We will release a version for NeoForge soon ™️ which might (or might not) work with newer Forge. I'd recommend swapping over to NF as soon as it is available in the CF launcher

Yeah, I will wait with that until more mods are available there, just heard of this today actually so.... Kind of late to the party one could say

**Comment by 62832** [comment]
> Yeah, I will wait with that until more mods are available there, just heard of this today actually so.... Kind of late to the party one could say

The vast *majority* of mods seem to be switching to NeoForge given the higher promised stability and existing team presence from the old Forge.

**Comment by NewAgeSoldier** [comment]
> > Yeah, I will wait with that until more mods are available there, just heard of this today actually so.... Kind of late to the party one could say
> 
> The vast _majority_ of mods seem to be switching to NeoForge given the higher promised stability and existing team presence from the old Forge.

Yeah, but right now I am sort of annoyed that I can't have the InfinityBooster as... It requires higher versions of Forge, which AE2 is not willing to update to :/

**Comment by NewAgeSoldier** [comment]
I just did an install of NeoForge and tested it... Uhm, Mod ID: 'forge', Requested by: 'ae2', Expected range: '[47.0.1,47.1.3]', Actual version: '47.1.57' same issue as usual lol

**Comment by 62832** [comment]
There is a newer build currently available for AE2 that specifically uses new versions of NeoForge.
