### ISSUE TITLE
Another crafting-card issue, not showing the options in an interface

### ISSUE THREAD

**Issue by djmulder** [AppliedEnergistics/Applied-Energistics-2#729]
Hey again,

I like them crafting cards.. now for the ME Interface. I insert a crafting-card and no-show on the config thingy to select to auto-craft items if they are not available.

![2015-01-13_18 45 09](https://cloud.githubusercontent.com/assets/10437793/5725598/875b70cc-9b54-11e4-9516-a96277373a45.png)

Really sucks :P I want to auto-craft steaks! :P haha

**Comment by yueh** [comment]
Not certain what you are trying to say.
But just configure the item you want to keep a stock of. The card will just request it to craft if not enough are available.

**Comment by djmulder** [comment]
Oh for export busses to the left there's a small button that you can toggle to: "craft if not available", also it doesn't seem to craft if it's requesting. (trying to figure out why now)

![2015-01-13_19 10 17](https://cloud.githubusercontent.com/assets/10437793/5725972/df0aedae-9b57-11e4-826c-486d7b5dcab8.png)
