### ISSUE TITLE
[1.20.1] Guide hotkey doesn't work in filter slots

### ISSUE THREAD

**Issue by XFactHD** [AppliedEnergistics/Applied-Energistics-2#7294]
### Describe the bug

Holding the guide hotkey on an item in the filter slots of a storage bus, import bus, etc. causes the bar progress to fluctuate in the first sixth or so of the bar and never complete.
![2023-07-29_01 47 00_](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/11262040/5bab6b2c-5bb8-48a4-b359-f18cb002b693)

### How to reproduce the bug

1. Place a cable with a storage bus on it
2. Place a certus quartz crystal in a filter slot
3. Hover the certus quartz crystal and hold the guide hotkey

### Expected behavior

Using the guide hotkey on an item in a filter slot should open the guide the same way it does for items in normal slots.

### Additional details

NeoForge 47.1.56
AE2 15.0.6 beta
No other mods

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/XFactHD/7df1de75ffffd363ab6e0074e014edbc

**Comment by 62832** [comment]
Seems as though this also happens on regular terminal slots that aren't things like view cells or the crafting matrix for a crafting terminal. My guess based on that is that this is currently an issue for instances of `FakeSlot` and `ClientReadOnlySlot`.

**Comment by XFactHD** [comment]
Fixed in #7965
