### ISSUE TITLE
Add a 'Mod Mode' to the View Cell

### ISSUE THREAD

**Issue by AlgorithmX2** [AppliedEnergistics/Applied-Energistics-2#73]
This mode would only show items from a selected mod in the upgraded terminal.

Originally Posted by alban987

This issue was migrated; For original details see http://ae-mod.info/Tracker/0786/

**Comment by Banjobeni** [comment]
I'd love to see the 'Mod Mode' implemented, either as a special View Cell or as a Card to be stuck into the View Cell.

I have a lot of houses in my base, each having special purposes. There are terminals in every house, and it would be great if those could only show stuff from that house's purpose. As most houses represent a mod, for example a cooking area crafting Harvestcraft eatables, a (persistent) mod filterability would be tremendously useful and highly appreciated!
