### ISSUE TITLE
[SUGGESTION] allow terminals to be able to see and display power stats etc

### ISSUE THREAD

**Issue by Ianaver** [AppliedEnergistics/Applied-Energistics-2#731]
It would be nice to be use existing ME terminals and be able to see power usage stats, maybe by adding an upgrade?

**Comment by Keridos** [comment]
:+1:

**Comment by Cisien** [comment]
I don't know what the existing terminals would show?

The network tool already shows power stats.

**Comment by yueh** [comment]
#115

**Comment by Ianaver** [comment]
oh.... XD sorry, I am not as familiar with RV2
