### ISSUE TITLE
Energy Ejector

### ISSUE THREAD

**Issue by oliverkane** [AppliedEnergistics/Applied-Energistics-2#732]
There's a block called an Energy Acceptor, which allows a ME network to absorb power from other mods sources.

Would there be any interest in myself or other making a pull-request containing a "Energy Ejector"?
Basically there's no way to get power back out of this system.  I think I can build it, but would like to know if would be welcomed and if so, what form it should take, ie: block, bus, etc.

Thoughts?

**Comment by yueh** [comment]
AE was never intended as power converter mod. If you want to transfer energy over AE2, there are P2P tunnels for it.

**Comment by shobu9** [comment]
@oliverkane it's called a p2p rf tunnel :3
