### ISSUE TITLE
Exact mode for processing patterns

### ISSUE THREAD

**Issue by Kevin-Marsh** [AppliedEnergistics/Applied-Energistics-2#7330]
### Describe the feature

Currently the patterns compress like items together. EG if you have a recipe that is redstone - iron - redstone then the pattern turns out as 2 redstone - iron. I am suggesting adding a mode that leaves the pattern as 1 redstone, 1 iron, 1 redstone.

### Reasons why it should be considered

Various mods such as Enderio and Elementalcraft require an exact input of items that can often contain duplicate items at various stages. This can be simply automated by leaving the recipe split into various parts instead of grouping so that the correct items are inserted in the correct pattern.

**Comment by mindforger** [comment]
@Technici4n i think what he meant was inserting the items not all at once but in sequence

**Comment by Technici4n** [comment]
Yes but in many cases the items will still stack in the target inventory. E.g. if you try to insert "apple, carrot, apple" into a chest it will still contain "2x apple, carrot" at the end of the process.

**Comment by Kevin-Marsh** [comment]
Yes with an except. The things that i was thinking of contain single item slots. By inserting the item in sequence the devices naturally seperate them. Another example is create meachnical crafters. They only hold a single item and the patterns are sequenced so inserting in sequence means they can be split into the approprite locations.

**Comment by Technici4n** [comment]
Hmmm ok I will look into it then.

**Comment by Technici4n** [comment]
This was indeed implemented in #7007.
