### ISSUE TITLE
Register certus quartz, nether quartz and fluix tools to the `TierSortingRegistry`

### ISSUE THREAD

**Issue by Technici4n** [AppliedEnergistics/Applied-Energistics-2#7333]

**Comment by Notarin** [comment]
@Technici4n You have not provided nearly enough context and details, why should they be added? what benefits does it provide? what reason is there to add it?

@shartte It is a specific java class, for more details google is your tool.

**Comment by Technici4n** [comment]
@Notarin don't be rude like that; we are the developers, not you. :wink:

**Comment by Notarin** [comment]
I noticed just shortly ago that this was internal conversation among developers, apologies.
Also, the intention was not to be rude but rather point out that, from what I initially assumed was an end user, the issue was more than poorly written.
