### ISSUE TITLE
My Cables arent connecting to the Controller 

### ISSUE THREAD

**Issue by KohChaos** [AppliedEnergistics/Applied-Energistics-2#7335]
![2023-08-16_17 03 52](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/142451985/340cd228-7a5a-45df-a98a-800069505903)

I'm trying to setup a new storage terminal in my creative version of the world for testing and the cables arent connecting to the controller and into the ME Drive so its just offline, this is the first time ive had this issue and i dont know why it isnt working right, im playing in All The Mods 9 (1.20.1)

**Comment by 62832** [comment]
Please look a bit more closely at what kind of controller that is.

**Comment by KohChaos** [comment]
> 

Thanks, they look very similar so I never relized I was using the wrong one.
