### ISSUE TITLE
Faster Molecular Assemblers

### ISSUE THREAD

**Issue by Shadedstalker2** [AppliedEnergistics/Applied-Energistics-2#7341]
### Describe the feature

Make molecular assemblers faster :)

### Reasons why it should be considered

for big modpacks like atm8 where you have to craft large amounts of items it simply takes too long to use just applied energistic for the crafting and basically means you gotta use other mods for fast crafting like rftools or even offload crafting to a seperate refined storage system

### Additional details

maybe add assemblers like the iron crafters mod have different tiers

**Comment by myrddraall** [comment]
Can you not just parallelize your crafts? 
You can add acceleration cards and have multiple molecular assemblers with the same patterns  and crafting cpu's with multiple coprocessors

**Comment by Shadedstalker2** [comment]
> Can you not just parallelize your crafts? You can add acceleration cards and have multiple molecular assemblers with the same patterns and crafting cpu's with multiple coprocessors.
> 
> Edit: Ran a test. 128 fully accelerated assemblers can craft 100k items in 10 min 30 seconds.

thats still slower than 1 rftools crafter
especially when i could have 5 crafters on 1 provider

**Comment by Notarin** [comment]
> > Can you not just parallelize your crafts? You can add acceleration cards and have multiple molecular assemblers with the same patterns and crafting cpu's with multiple coprocessors.
> > Edit: Ran a test. 128 fully accelerated assemblers can craft 100k items in 10 min 30 seconds.
> 
> thats still slower than 1 rftools crafter especially when i could have 5 crafters on 1 provider

Comparing to other mods isn't really a supporting point, other mods have different playstyles different objectives, and different developers with their own ideas, if we focus on making every mod balanced with eachother then we end up with massive overhead in planning and end up with cookiecutter features. Instead, a much better angle to approach this would be something like, "RFTools crafters far outscale the productions speed of the molecular assembler, for balancing purposes can we have the ability to configure the molecular assemblers speed?" or if that doesn't itch your fancy, maybe request a mechanic that adds to the mod, for example (this is not a real suggestion), "The molecular assembler is fairly limited in speed, there are three method to increase production, acceleration cards, more assemblers adjacent to the pattern provider, or more pattern providers with duplicate patterns, the first to have directly capped limits, while the last one become impractical at a certain point, this leaves this mod behind in modpacks that use faster assemblers, so I'd like to suggest a "Quantum Assembler", this quantum assembler is available to every pattern provider in the general vicinity, making it possible to add even more assemblers to a pattern provider, for a price of course, either through high power consumption, or a expensive crafting recipe, or both."
