### ISSUE TITLE
import busses won't import things from interfaces

### ISSUE THREAD

**Issue by dbhol** [AppliedEnergistics/Applied-Energistics-2#7345]
### Describe the bug

When connecting an impirt bus to an me interface, the import bus won't import items or fluids from the interface

### How to reproduce the bug

Connect an interface to an import bus and configure the interface to the item or fluid you wish to use. This should then go through to the import bus, but it does not and the destination does not receive the item or fluid

### Expected behavior

The item or fluid should pull through to the import bus

### Additional details

Mod version 12.9.5.
Bug was discovered while playing All The Mods 8 modpack.
@Sea-Kerman assisted me with this through discord as well

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

N/A

**Comment by Sea-Kerman** [comment]
![](https://cdn.discordapp.com/attachments/1143610751949471804/1143629771071295538/image.png)

**Comment by Technici4n** [comment]
This might be a configuration issue with the mekanism machine.

**Comment by Sea-Kerman** [comment]
I doubt that, as this setup worked. I believe we tried it with chests too
![2023-08-28_10 10 46](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/41390862/fb6afdc9-4cdc-4c32-b63a-95d30646a994)

it seems to be an atm8 only thing, actually

**Comment by Technici4n** [comment]
Probably another mod messing with us then... You'll have to binary search to find the culprit ^^
