### ISSUE TITLE
Spatial Anchor not loading the chunks across dimension

### ISSUE THREAD

**Issue by L-Lawlite** [AppliedEnergistics/Applied-Energistics-2#7347]
### Describe the bug

I have connected spatial anchor to my main me system and it is not loading chunks across dimension through quantum ring. I dont know if it is intentional or not.

![Spatial Anchor](https://media.discordapp.net/attachments/922828438274986007/1143889688021717133/2023-08-23_18.18.53.png?width=1269&height=667 "Anchor ui")

### How to reproduce the bug

Just connect spatial anchor to me system and see if it loads the things connected to quantum ring. 

### Expected behavior

I don't know if it should load it or it is working as intended.

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/N1PE7sKc

**Comment by Technici4n** [comment]
Hi, that is a limitation of the Forge chunk loading API, which we kept for the Fabric version for parity considerations. You need one anchor per dimension.

Maybe we should reconsider this in a future version.

**Comment by L-Lawlite** [comment]
Cool its resolved then.
