### ISSUE TITLE
Powdered Snow when not in a bucket should work as a "Fluid" in storage

### ISSUE THREAD

**Issue by coyo-t** [AppliedEnergistics/Applied-Energistics-2#7348]
### Describe the feature

Powdered Snow (the block, not in a bucket) should be catagorized as a "fluid" type in the same way water & lava are. Presently, if you place powdered snow infront of an annihilation plane, that powdered snow is just lost to the ether as there is no actual "Powdered Snow" block to work with. Additionally, powdered snow can neither be stored or retrieved from cauldrons.

Displayed in the interface it should look like a block, rather than the full-slot sprite that fluids normally look like.

### Reasons why it should be considered

It Would Be Neat.

Would make powdered snow collection with cauldrons automatable. Also frees up your buckets to hold other things. Just a nice if niche QoL thing.

**Comment by Technici4n** [comment]
Powdered snow is not a real fluid in the Minecraft/Forge/Fabric sense.
