### ISSUE TITLE
Security station not preventing structure modification?

### ISSUE THREAD

**Issue by Zaflis** [AppliedEnergistics/Applied-Energistics-2#735]
Using AE2 version rv2-beta-1. I have a security station on my storage subnetwork with 1 general purpose biometric card in it. It is set to: Deposit, Withdraw, Craft. So Build and Security are not allowed for anyone but me (one who placed the security station). Then i asked a friend to try and break 1 ME drive, and he just did that with a TiC pickaxe, and he did not have OP rights. Funnily he wasn't able to open the UI and access the cells though. But if he can break it, all the cells will fly to his hands :p

**Comment by RAWRwins254** [comment]
Although I'm not one of the people able to fix this, I'd recommend updating to rv2-beta7. They're going to say that if they can't reproduce that it's not present anymore and thus, it's an outdated bug.

**Comment by yueh** [comment]
Yes, security terminals only provide a network layer security. So other players cannot access your network, but they can still break it.

#24 is an open feature request for secure/unbreakable blocks.

**Comment by Cisien** [comment]
Use something like a spatial dimension or warded blocks from thaumcraft to handle the physical security of your storage.

**Comment by Zaflis** [comment]
It's that the Biometric cards have security property about "build". So it just is there hanging around for later actually doing nothing, or does it mean something else?
