### ISSUE TITLE
陨石罗盘无指针

### ISSUE THREAD

**Issue by DSLZL** [AppliedEnergistics/Applied-Energistics-2#7355]
### Describe the bug

在appliedenergistics2-fabric-15.0.7-beta版本中，无论是在单人还是多人上都无法看到陨石罗盘的指针

### How to reproduce the bug

做一个陨石罗盘

### Expected behavior

正常的看见指针

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Fabric

### Crash log

暂无

**Comment by 62832** [comment]
English, please.
