### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by wycats0** [AppliedEnergistics/Applied-Energistics-2#7359]
### Describe the bug

Looks like the mod isn't compatible with other mods, because I use many other mods that together works correctly, but when I added Applied Energistics the game crashes.

### How to reproduce the bug

The bug can be reproduced by playing Minecraft with this list of mods (Forge modloader)
Cyclops Core
Not Enough Crashes
Terrablenders
Crash Utilities
Regions Unexplored
Pam's HarvestCraft - Trees
Pam's HarvestCraft - Crops
Pam's HarvestCraft - Food Extended
Pam's HarvestCraft - Food Core
WaterPhysics
Jade
Forbidden & Arcanus
Library Ferret
Philips Ruins
Dynamic Lights
Better FPS - Render Distance
Rubidium
Easy Emerald
Xaero's Minimap
Collective
Mob Sunscreen
Citadel
Alex's Mobs
Serene Seasons
EvilCraft
Better Villages
Lost Cities
Corail Tomstone
Mo' Villager
Rare Ice
MoreVanillaArmor
Grimoire of Gaia
Architertury
Simply Swords
Minecraft Comes Alive
Ferrite Core
AI Improvements
FPS Reducer
FallingTree
Hopo Better Mineshaft
Valhesia Core
Game Menu Mod Option
Log Begone
Better Foliage
[crash-2023-08-19_18.20.44-fml.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/12458597/crash-2023-08-19_18.20.44-fml.txt)

### Expected behavior

I expect that the game crashes.

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

https://mclo.gs/yzOLNAF

**Comment by mindforger** [comment]
>Mod ID: 'forge', Requested by: 'ae2', Expected range: '[47.0.1,47.1.3]', Actual version: '47.1.44'</span>

**Comment by Technici4n** [comment]
Yeah your Forge version is too high.

**Comment by wycats0** [comment]
WTF man, I use the old version of Forge

**Comment by wycats0** [comment]
> Yeah your Forge version is too high.

Why the mod don't works with the oldest version of Forge?
