### ISSUE TITLE
Achievement "Recursive Networking" incorrectly awarded

### ISSUE THREAD

**Issue by RAWRwins254** [AppliedEnergistics/Applied-Energistics-2#736]
Hey guys!

Got an achievement glitch where AE2 gave me the "Recursive Networking" achievement even though I didn't meet the described requirements for it. The specific requirement I didn't meet was actually putting a storage bus on a ME Interface which is the trigger guideline for the achievement. Running Rv2-beta7.

**Comment by yueh** [comment]
Please provide more information on how to reproduce it.

Also keep in mind the achievement depends on other ones.
So you could already have built it. If you are missing the controller achievement, you should retroactively obtain it after getting the controller one. Or the ones before.

**Comment by RAWRwins254** [comment]
Yueh: All I did was craft the ME interface inside the ME crafting Terminal and it was awarded.

**Comment by asgdfagdsfg** [comment]
This mod is broken and crap as hell and you worry about textures?
The devs are not fixing ANYTHING here.
If you are playing on a server with AE2, you probably have to rebuild everything thanks to those idiots.
Seriously, worse then griefers. Ruining multiple servers at ONCE!
Hope you all get what you deserve for being such massive trolls, that you have to spend hundreds of hours, just to sabotage people and get off on "ruining sandcastles".
Most pathetic humans that i have ever heard off.

**Comment by yueh** [comment]
Closing as inactive, reopen when someone can provide a reliable way to reproduce it.

**Comment by Atraxi** [comment]
Still exists in rv3-beta-6.
Reproduce by crafting an interface from multi-part version back to full block version (assuming pre-req achievements are already awarded).

I can reliably reproduce in a fresh world so will update with more info if needed.

**Comment by markus512** [comment]
I can confirm that, just crafted an interface and got this archivement.

**Comment by vedalken254** [comment]
@Atraxi yup... you understood it right (I understand the basics, but Java is still something I haven't gotten around to learning yet.)
