### ISSUE TITLE
[minecraft 1.19.2][ae2 12.9.5] [All The Mods 8 1.0.25] spatial storage "unformatted text" does NOT go away after activating spatial I/O

### ISSUE THREAD

**Issue by jakyle** [AppliedEnergistics/Applied-Energistics-2#7364]
### Describe the bug

I am playing on a modded forge server (all the mods 8) I'm hosting on a local machine in my house. Whenever I use a Spatial IO port on a 16^3 Spatial Storage Cell, after submitting the redstone signal, the space DOES store into the Spatial Storage Cell. However, after said space is stored, the cell text does not change, which is to say, it still says it's Unformatted and it's capacity stays at 16x16x16. This is confusing because the cell is actually formatted but I have no way of actually knowing. Also, seprate issue, the moment I create a spatial storage cell, I'm unable to Uncreate said cell.

### How to reproduce the bug

Create a spatial IO and place in 16^3 cell and activate it with a redstone, after activation, the cell will still be read as "Unformatted"

### Expected behavior

I expect the cell to not say "Unformatted" and also display the now set dimensions of the spatial storage cell.

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

n/a

**Comment by Mortimyrrh** [comment]
Have also seen this in 1.19 on the (dw20 pack) but only on a multiplayer server could't reproduce in single player.

**Comment by Prian99** [comment]
The same is happening for me on my allthemods 9 to the sky server.
