### ISSUE TITLE
Z-fighting on angled dense cable

### ISSUE THREAD

**Issue by zax71** [AppliedEnergistics/Applied-Energistics-2#7372]
### Describe the bug

When an angled dense cable goes through a facade in to more than 2 dense cables, there is Z-fighting as you can see in the below image.

![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/67716263/cfef561f-1dff-49af-8199-318ede1ba6e3)

### How to reproduce the bug

Create a setup like below, I have tried many facades and all have worked.

![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/67716263/35e25a50-7e31-4ee2-badb-a2e10105c730)

### Expected behavior

I would expect it to look like the below

![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/67716263/92301d40-7642-4dfb-b345-1fb4294c8758)

### Additional details

I have not tried to reproduce this on Forge, and I am playing AOF6

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Fabric

### Crash log

N/A

**Comment by Technici4n** [comment]
I think I fixed this in 1.20. Can someone check?

**Comment by 62832** [comment]
Can confirm this was fixed in 1.20.

![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/5098830/1ad6914b-3c5c-4bcb-b79e-ccaa45145fec)

**Comment by zax71** [comment]
Ah, sorry about that one!
