### ISSUE TITLE
Quartz Fiber block causes crash when placed in world on Fabric

### ISSUE THREAD

**Issue by StormCircuit** [AppliedEnergistics/Applied-Energistics-2#7376]
### Describe the bug

When placing a quartz fiber block in a world with only AE2 and REI installed on Fabric, the game crashes.

### How to reproduce the bug

In Curseforge's launcher:
Install Fabric 0.14.22 on Minecraft 1.20.1
Install dependencies:
architectury-9.1.12-fabric.jar
cloth-config-11.1.106-fabric.jar
fabric-api-0.88.0+1.20.1.jar
Install REI
Install AE2

Open a new world, cheat in a quartz cable, place it in the world. The world should instantly freeze and then crash the game.

### Expected behavior

To place the block without crashing

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/XM5FGsR9

**Comment by StormCircuit** [comment]
Crashes even without REI

**Comment by Technici4n** [comment]
Thanks for the report. Please update to Fabric API 0.88.1.
