### ISSUE TITLE
Trying to remove mod made crush

### ISSUE THREAD

**Issue by ejexxeffer** [AppliedEnergistics/Applied-Energistics-2#7378]
### Describe the bug

Im install mod, then remove it. But without mod my server isn't starting. 
Here is log file: https://mclo.gs/6lBwrZP

### How to reproduce the bug

Im make this couple times. With mod server starting, when i remove mod server cant start.

### Expected behavior

Im delete mod and server start without mod, like anyone tell in the guide posts.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://mclo.gs/6lBwrZP

**Comment by Technici4n** [comment]
That's actually a vanilla bug, nothing we can really help with
