### ISSUE TITLE
Server crash, RF p2p, sophisticated backpacks

### ISSUE THREAD

**Issue by MasterSloth1** [AppliedEnergistics/Applied-Energistics-2#7390]
### Describe the bug

i have a RF p2p network setup, I have the output pushing rf into a sophisticated backpacks backpack with a battery upgrade and max netherite stack upgrades. I originally had 2 upgrades in the backpack and it was working fine, it completely filled up even, then I added more stack upgrades all to the max and then the server crashed

### How to reproduce the bug

1. setup a backpack with a battery upgrade and the rest of the upgrade slots filled with netherite stack upgrades
2. place backpack onto a RF attuned p2p the backpack side is the output
3. crash?

### Expected behavior

for it to continue being all good and keep charging the backpack

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/BbH2uaLa

**Comment by mindforger** [comment]
the crash itself is only showing your server ticking to death

How do you input the power into the backpack? 

How is AE2 supposed to be the reason for the crash?

**Comment by Technici4n** [comment]
The server deadlocked. It's weird that the thread dump does not provide the stack trace of the main server thread. Can you check again? It should be there, and will indicate the culprit...

**Comment by ticticboooomer** [comment]
i dont believe this is an issue with ae2, it looks like sophisticated backpacks allows more upgrades than a 64 bit integer can hold, thus causing an integer overflow. i took the upgrades out of the backpack and it seems to be fine now
