### ISSUE TITLE
Making a 1.19.4 port for fabric

### ISSUE THREAD

**Issue by Wartets** [AppliedEnergistics/Applied-Energistics-2#7391]
### Describe the feature

I love this mod, I've always put it in my modpacks. And, just as I wanted to add it, I notice that it exists in almost every version except 1.19.4. Would it be possible to have it in this version? I don't know if there's a reason for this, and I'm sorry it's already been requested (A request had already been made last May 2023, but perhaps since then it has become possible?).

### Reasons why it should be considered

It doesn't exist in this version!

**Comment by Technici4n** [comment]
No, update to 1.20.
