### ISSUE TITLE
Config: Disable Budding Decay

### ISSUE THREAD

**Issue by FooterMan15** [AppliedEnergistics/Applied-Energistics-2#7399]
### Describe the feature

Add a Config feature for disabling Budding Certus decay.

### Reasons why it should be considered

Better Modpack Customization
Potentially Geode implementation

**Comment by Sea-Kerman** [comment]
If you want that, just kubeJS up a recipe for flawless budding certus (which doesn’t decay).

**Comment by FooterMan15** [comment]
Both

**Comment by Sea-Kerman** [comment]
what exactly is your use case?
