### ISSUE TITLE
Facades do not have connected textures

### ISSUE THREAD

**Issue by DynamicSurbus** [AppliedEnergistics/Applied-Energistics-2#740]
If you use a block with connected textures for a facade the connected textures do not work, also it would be nice if these textures would also connect with the regular block not just other facades

**Comment by TheJulianJES** [comment]
It's hard to code, also the other mod maker have to implement some API parts, I think.

**Comment by Cisien** [comment]
I have a feeling that this just simply isn't feasable. Since connected texture support is per mod and not in forge, we would have to have custom logic for each mod, which we can't maintain in the long run. The problem with an API approach is convincing all of the other mods to depend on our API solely to benefit our user base, most mod devs wont bother.

**Comment by Entoarox** [comment]
@Cisien Maybe consider using the format used by Optifine/MCPatcher, and building upon that? Then it doesnt matter how the mod internally does the connecting, just that the 'stuff connects like this' file matches with that internal connected texture handling.

**Comment by Cisien** [comment]
@Entoarox are you suggesting we implement the connected texture piece of those mods? I don't know anything about what those do other than cause compatibility issues with other mods...

**Comment by Entoarox** [comment]
@cisien I am suggesting you make use of the existing format to define HOW textures connect to handle the compatibility, but how you actually DO the connecting can be left totally up to your own designs
Effectively, my idea is that you use the format to allow other mods to say "this is how the textures should connect", and you then use whatever method you have for doing the connecting to actually make the connections.
As it stands, the connected texture format used by optifine/mcpatcher only defines how connected textures should connect, both mods have their own way of actually making them connected.

**Comment by FireBall1725** [comment]
@Entoarox there is no "Generic" way to handle connected textures on the multi-parts.  It would be up to the mod to add support for that.

**Comment by TheJulianJES** [comment]
I agree with that.

**Comment by Entoarox** [comment]
@FireBall1725 Have I not been saying exactly that???
My suggestion was to use the format used by optifine/mcpatcher to have modders tell you how textures should connect (vertical, horizontal, both, etc.) and then handle actually doing the connecting yourself.

**Comment by FireBall1725** [comment]
there is so much that goes into some multi-parts that I dont think there could be an effective generic class made for this, the mod developers would need to add their logic to the multi-parts if they want it to work.

Either way, even if we invented some generic way, mod developers would still have to support AE2, and add their support to it.  So either way they need to add support, if they haven't done so now, I don't see how adding a generic option for them to do it would make them want to come and do it.

**Comment by DynamicSurbus** [comment]
Ok that is nice to know for making future bases

**Comment by siasur** [comment]
EnderIO is also able to connect the IO facades with blocks beside it. That's why I use the EnderIO ME Conduits when I have to go through a wall.

**Comment by mindforger** [comment]
@siasur besides this topic beeing heavily necroed with your post
EnderIO is replacing the cables with fake blocks hooking into their respective renderers enabling to run foreign render code ... 
facades are only placed side by side on the cables, they can not "use renderer of the block it mimics" on only one side of a block

**Comment by siasur** [comment]
@mindforger whoops... misread the year, sorry. Didn't wanted to necro
Oh, okay. I didn't knew that. Thanks for pointing out.
