### ISSUE TITLE
exit code 1 on launch

### ISSUE THREAD

**Issue by MrRoomba69** [AppliedEnergistics/Applied-Energistics-2#7400]
### Describe the bug

![Screenshot 2023-09-13 182115](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/118114584/19bc77c7-754c-4c1e-bee4-76ad59bbcb65)
![Screenshot 2023-09-13 182203](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/118114584/1ee64edc-33df-4e61-bfa3-d6056f0560b5)
when i launch the game it loads for a couple of seconds and gives me a crash popup

### How to reproduce the bug

launch the game on forge 47.1.0 with the mods installed in the mod list picture.

### Expected behavior

i thought it would load to the title screen

### Additional details

i gave it 10 GB with 16 extra MB

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/Ses16PKE

**Comment by 62832** [comment]
Update to Forge 47.1.3.
