### ISSUE TITLE
Weird bug with Continuity, annihilation and formation planes become invisible. (Pepper says this is on us)

### ISSUE THREAD

**Issue by Sea-Kerman** [AppliedEnergistics/Applied-Energistics-2#7401]
### Describe the bug

If there are any emissive (_e) textures in a resource pack, formation and annihilation planes turn invisible.

https://modrinth.com/resourcepack/emissiveae2/version/1.5

https://modrinth.com/resourcepack/example-emissive-textures/version/1

![2023-09-12_00 17 02](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/41390862/b9145aca-09f2-4a15-be09-025ff9e1568e)
![2023-09-12_00 16 43](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/41390862/b3606830-ee08-4865-9a3a-c7ef8af09f6f)

### How to reproduce the bug

Install AE2, Continuity, and a resource pack with optifine-format emissives
place a formation plane
enable the resource pack

### Expected behavior

Formation and annihilation planes do not become invisible

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Fabric

### Crash log

https://gist.github.com/Sea-Kerman/e11e3eeadf40bae6affc1e24a91553d7

**Comment by AlienXtream** [comment]
ok. good to know its on the bug tracker. not game breaking, but looks weird.

**Comment by Sea-Kerman** [comment]
fixed by #7616
