### ISSUE TITLE
[1.19+] Missing hotkey to autocraft already present item

### ISSUE THREAD

**Issue by LuciusV** [AppliedEnergistics/Applied-Energistics-2#7402]
### Describe the feature

I cannot get any combination of clicks to request autocrafting of already present items (checked that inventory sorting mods are disabled). Keys found on intetnet (like middle click) also don't work.

### Reasons why it should be considered

It if often required to autoccraft already present items, and moving mouse to  click stored/craftable every time is annoying.
RF storage has this feature for llong ago.

**Comment by Technici4n** [comment]
If middle click or the key you bound for "pick block" doesn't work, it's usually the fault of one of the inventory sorter mods.
