### ISSUE TITLE
Buildcraft integration crash

### ISSUE THREAD

**Issue by socialretard** [AppliedEnergistics/Applied-Energistics-2#743]
Server crashes whenever I place a BC pipe next to a storage bus. I either have to disable BC integration or delete the pipe using an editor to get it to boot again. Here is the crash log.

http://paste.ee/p/Nh4Y4

I am using:
Buildcraft 6.3.1
AE2 RV2-BETA-7

**Comment by yueh** [comment]
It looks like BC has changed something with the pipe plugs according to the crashlog.
I will look into it later.

**Comment by yueh** [comment]
It looks like BuildCraft broke some APIs (or better moved it to the API instead of internal classes).
So I am currently not sure if we can support 6.3.x as well as earlier version parallel.

@asiekierka I remember @thatsIch having some questions about something related to Facades and some crashes. Could you both solve it?

**Comment by thatsIch** [comment]
I am still waiting for a response for that, but I guess, we just remove it for now

**Comment by yueh** [comment]
Removing a feature is not really ideal, but you can currently force a crash with AE2 and newer buildcraft versions, as the API changed quite heavily.

So removing it and moving on is probably the best option for now.

**Comment by asiekierka** [comment]
Always support the latest stable release and that only. If you plan to support 6.3.x+ only, remove MJ integration altogether.

If you need any help from me to keep supporting BC, please tell me! It is very important to me that mods keep supporting BuildCraft.

**Comment by yueh** [comment]
I do not see anything preventing the BuildCraft support (as long as we are able).

It is mostly about the jump between 6.2 and 6.3 (or was it 6.1->6.2?) is pretty large.
And the lack of time on my side (and probably @thatsIch).
I also vaguely remember 6.3 not even providing the necessary functions for our integration, but as far as I know, they were added later in 6.3 or 6.4. (Detecting a plugged pipe in an easy way)

**Comment by thatsIch** [comment]
As stated in (here)[https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/319],
the BC API lacks an entry point to create an actual Facade when we wrench them from our cables. Currently I am using the internal class `ItemFacade` to get the `ItemStack`, or I am missing the pointer to where I get access to that class via the API

**Comment by thatsIch** [comment]
nvm I think I figured it out. Facades fixed indev

**Comment by asiekierka** [comment]
@thatslch - you can just store a copy of the ItemStack which is an IFacadeItem. (This would automatically add support for any ItemStack implementing IFacadeItem, which would be an interesting bonus.)

**Comment by thatsIch** [comment]
Actually its about, when the network is being constructed, forget the wrenching. 

At that point of time, we only know the type of block, the meta and if its of BC or not. `ItemFacade.FacadeState.create` was perfect for that.
