### ISSUE TITLE
Terminal not displaying the items from container

### ISSUE THREAD

**Issue by SaraXianLin** [AppliedEnergistics/Applied-Energistics-2#7435]
### Describe the bug

I can deposit items through the terminal, however I don't see the items in the terminal and I can see them only in container (barrel, chest, etc)
![Capturebug](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/77309538/2bf59868-4985-4fb5-96a0-71809416041a)
![2023-10-06_01 17 41](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/77309538/8ddee440-dbf6-4c22-a7f0-664e7c4821b7)
![2023-10-06_01 17 43](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/77309538/3832fcb2-f2ff-4732-8c0c-55b105d76f42)

### How to reproduce the bug

1.- Connect the controller to a container using a flux ME glass cable and ME storage bus while the controller is powered.
2.- See the terminal, and even there are items in the connected container, you cannot see them.
![Capturebug](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/77309538/5f90f8d4-2840-413c-ae86-3c805ab1bb61)

### Expected behavior

Be able to see the items from the connected container

### Additional details

I think it could be a incompatibility with another mod, I have been trying to find it however I have not been able to locate it.

This is from the modpack called Yes Nicer MC Fabric, any version containing the mod has this issue.

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Fabric

### Crash log

No Crash log

**Comment by Mari023** [comment]
you set your terminal to show fluid only, click on the bucket icon on the left and it should show items again
