### ISSUE TITLE
Why is this mod so incredibly bad now?

### ISSUE THREAD

**Issue by asgdfagdsfg** [AppliedEnergistics/Applied-Energistics-2#744]
Why make such a giant step backwards? It destroys the WHOLE purpose of the mod. I have never seen anyone use the mod for ANYTHING besides "connecting all machines with 1 wire, instead of multiple wires".

It was easy to use but hard to reach, the perfect combination.
Now you have to travel for many many hours, until you have everything you need for the basic items, and then you realize that the mod is limited to ****, and you have to set up all the old pipe systems again, because they are FAR more compact, than the dumb regular me cables.
I am feeding about 50 machines with ONE buildcraft pipe, the OLDEST AND CRAPPIEST pipe that there is, and it's just... so much better then having to deal with... machines that magically increase your cable size.

Really hate what the developers did, and the fact that you can't even disable this in the config, without removing the ME Controller from the game, is just pathetic.

Why do the mods put so much work into ruining this? They could have done a billion awesome things with this mod, and instead, they just put limitations in EVERYWHERE that make no sense.
Seriously, just WHAT is the benefit of having a ME System now? It's slower, less compact, more complicated, and way uglier then the 10 year old build craft items like the redstone engine or the pipes.
Yea, the mod is also SLOWER now... as if it wasn't enough that it was harder in every way already...
And the Controller looks like some... stone with glowing cracks in it... just WTF?

Hard to believe that the people that came up with all this stupid stuff, are the people that once made the great ME System...

Whoever is responsible for those changes... Punch yourself in the balls. You ruined online servers (where you are unable to cheat in the dumb new items) for so many people, you deserve it.

Edit:
Also, the other's are right. The idea of magic in this, is completely wrong... Let us make chips, not magic beans that turn into computer chips by lying in a puddle for about 9001 hours...

**Comment by yueh** [comment]
Some people enjoy a bit of a challenge and needing to think about it. Some do not.

It is a game and you should have fun with it. If you enjoy BC pipes or other mods more, use them.
Nobody is forcing you do use any mod you do not like or enjoy. That is the great thing about modded minecraft, there are so many different options to find the right ones for youself.

**Comment by asgdfagdsfg** [comment]
The servers i play on DO force me to use this crap instead of AE1.
Fix this crap already. Why are there SO MANY IDIOTS working on the mod, only to make it BAD???
This has nothing to do with challenge. No matter how much someone challenges you, you cant fit 2 blocks into the space of 1 block. This is PLAIN RETARDED!

**Comment by Pyeroh** [comment]
yueh is extremely nice with you, after a very long bad criticism of this wonderful mod. You shouldn't react like you do, if you want to be taken seriously.
By the way, without being as aggressive you are, AE2 is a big evolution in the modded Minecraft world. Indeed, you have to walk to find resources to start, like in vanilla. Indeed, the mod make you go through a progressive automation, which may look surly, but don't you do it with Minecraft Vanilla ? Do you start your non-modded world with a huge iron farm, followed by a even bigger automatic ore processor ? Well, I don't think so.

Oh, and I saw your other "issue". I think you're a troll, and you're bored, so you do that to have a good time, but it brings a bad ambiance to this tracker, where almost everyone expose his true problem, and where devs try to solve it.

However, I wish you to have a good game, whatever the server you play.

**Comment by asgdfagdsfg** [comment]
He is not nice, he is answering as if he didn't read my post.
Besides that, how can you people screw this mod up SO BAD and then call other people trolls?
Clearly YOU guys are trolling...
"You can just disable channels" (No you can't)
"We don't like the fact that you can disable channels and will remove it"
"We don't want the community to split up, and won't remove the feature"
Just wtf guys?
There IS NO FEATURE to actually disable that crap, without breaking the mod (removing the ME Controller)...
I think i tried EVERY version that you can download at the ae info site, and the versions that are installed in different modpacks. It works NOWHERE!
The mod, as it is, is complete garbage, and i will rather spend 1000 hours, making a working AE2 WITHOUT those idiotic channels, then using the system as it is now...

Really don't understand why there isn't already a version, where you don't have to worry about those insanely dumb channels...

**Comment by FireBall1725** [comment]
Here allow me to add my 2 cents to the entire thing, I hate feeding the trolls, but this is a great example of messages from real people I get all the time, and maybe someone else who is frustrated with the channel systems will be able to learn something.

@asgdfagdsfg it is people like you that I can't stand, a mod developer changes the mod, and you come along and go "OH NO, IT CHANGED!!!".  I have met many people who didn't like the channel system in AE2 and it was for the lack of understanding, very similar to your first message you posted about not being able to run one cable around your base.

That is why I love to make complex AE designs on my Server Play series that take AE2 to the limit and show that you CAN run one cable around your base still, it just requires you to think and plan it out a little better than in AE1.  I have over 300 grid nodes on my AE system, attached through 1 cable that runs around my entire base, and guess what, it works great.

If you really don't understand and are willing to learn then I think any of us would be more than happy to explain in detail how to setup a large AE system, but I can say that 1. the channel system is not going away, and 2. you still can run one cable around your base, and finally AE2 is far superior to AE1 any day of the week.
