### ISSUE TITLE
Server crashes 

### ISSUE THREAD

**Issue by MrGeorge547** [AppliedEnergistics/Applied-Energistics-2#7440]
### Describe the bug

[15:11:39] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception

net.minecraft.ReportedException: Readying AE2 block entity

Caused by: java.lang.IllegalStateException: The node has already been initialized. Initialization data cannot be changed anymore.

-- Block entity being readied --

Details:

World: minecraft:overworld

Name: ae2:growth_accelerator // appeng.blockentity.misc.GrowthAcceleratorBlockEntity

Block: GrowthAcceleratorBlock[growth_accelerator][facing=down,powered=false]

Block location: World: (456,56,583), Section: (at 8,8,7 in 28,3,36; chunk contains blocks 448,-64,576 to 463,319,591), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,-64,512 to 511,319,1023)

Block: GrowthAcceleratorBlock[growth_accelerator][facing=down,powered=false]

Block location: World: (456,56,583), Section: (at 8,8,7 in 28,3,36; chunk contains blocks 448,-64,576 to 463,319,591), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,-64,512 to 511,319,1023)

### How to reproduce the bug

Join a server then leave and then join again

### Expected behavior

connection closed

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/BJjchdqh

**Comment by 62832** [comment]
This looks to be a problem with EnderIO's conduits. Would you be able to try again without EnderIO present?

**Comment by mindforger** [comment]
if anyway possible, a picture of the basic setup causing this would be interesting
it looks a little bit funny too me, as if a gridnode that has been marked ready previously is now proxy-updating over a conduit causing a race condition where the another node is not yet ready but already loaded the init data

**Comment by Technici4n** [comment]
Looks like a problem with EnderIO, indeed.
