### ISSUE TITLE
When using the "Quantum Bridge Card" in the "Wireless Fabrication Terminal", the opening range when loading chunks does not increase.

### ISSUE THREAD

**Issue by BloodInAs** [AppliedEnergistics/Applied-Energistics-2#7442]
### Describe the bug

When using the "Quantum Bridge Card" in the "Wireless Fabrication Terminal", the opening range when loading chunks does not increase. Mechanically, it should work in such a way that you can open a terminal anywhere if the chunks are loading.

### How to reproduce the bug

insert the Quantum Bridge card into the Wireless Fabrication Terminal, leave someone nearby to load the ME, and fly off somewhere

### Expected behavior

With the Quantum Bridge Card inserted, Wireless Fabrication Terminal works at any distance with loaded chunks

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

-

**Comment by Mari023** [comment]
the quantum bridge card is not from ae2, it is [from an addon (ae2wtlib)](https://github.com/Mari023/AE2WirelessTerminalLibrary)

---

do you have the terminal linked to a quantum bridge on your network?
you have to insert the matching singularities in the terminal.

The singularity HAS to be created via the recipe and may not be obtained through creative or JEI / REI

**Comment by BloodInAs** [comment]
I crafted the map myself, but it still doesn’t work

**Comment by BloodInAs** [comment]
and what does the quantum bridge have to do with it? This is the same infinity boost card as in previous versions. It works simply, inserted into a wireless terminal, and it works from anywhere. So what does the bridge and the singularity have to do with it
