### ISSUE TITLE
Crafting and Pattern Encoding Terminals won't accept stacks as input.

### ISSUE THREAD

**Issue by kalutro** [AppliedEnergistics/Applied-Energistics-2#7448]
### Describe the bug

The mod IndustrialCraft 2 Classic has recipes that use stacks of items. For example, you can make 16 Overclock Upgrades with the following recipe in a normal crafting table.
![javaw_Oq5MYuqNOs](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/69569507/0d9ee813-7f2d-4250-bafc-f56d3b04bcad)

However, this does not work in the ME Crafting Terminal.
![javaw_rSm935HUZR](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/69569507/1f3e4d7a-d308-4d63-8dfb-a6afba6f0b58)

Furthermore, I cannot set up auto-crafting for this recipe in the ME Pattern Encoding Terminal, mainly because it is not a processing pattern so I cannot set the quantity of items.
![javaw_4BOjGfSBvY](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/69569507/2ff0721a-8003-4cb0-a3a2-35352e6d8e19)

I assume this is a bug, since the recipe works in a crafting table, though it may just not be implemented. If the latter is true, it would be great to see this implemented.

### How to reproduce the bug

Try to craft any recipe that uses stacked items.

### Expected behavior

I expected, at the least, the recipe would work in the ME Crafting Terminal.

### Additional details

Modpack is ATM VolcanoBlock 1.0.8
Minecraft 1.19.2
Forge 43.2.14

appliedenergistics2-forge-12.9.8
IC2Classic-1.19.2-2.0.7.1

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

N/A

**Comment by 62832** [comment]
Stacked crafting ingredients simply aren't a thing in either vanilla Minecraft or the majority of other mods, and we don't generally try to accommodate non-standard behaviour like this. It would be much more preferable either for IC2C to not do this or for the recipes within the pack to be changed to something standard, e.g. one cell with two blanks producing two upgrades.

**Comment by 62832** [comment]
Also, since IC2C apparently has its own means of bulk crafting these, you should be using a processing pattern to make these with the relevant machines instead of attempting to use regular autocrafting.
