### ISSUE TITLE
Items disappearing for split second in terminal.

### ISSUE THREAD

**Issue by APasz** [AppliedEnergistics/Applied-Energistics-2#745]
It only happens with things that aren't directly in the network but in MFR DSU's (have tested with Jabba barrels). I have only noticed it with things like cobble, sand and dirt which come in very fast from my quarry.
Also the entire network is chunk loaded.
Running rv2.b6, forge 1286 with about 170 mods.

**Comment by asgdfagdsfg** [comment]
Who cares? nothing works because of fucking channels! Developers certainly don't care about any problems, otherwise they would get of those idiotic things after 1 million hate threads on reddit, etc.

**Comment by yueh** [comment]
Could you please provide some information about your network so we could reproduce it?
Like heavily nested storage networks.

**Comment by APasz** [comment]
Most of the DSU's are on a sub-net which feeds into the main network which has the controller, CPU's, interfaces's, 6 MA's and a drive with 10 16k disks.

**Comment by yueh** [comment]
Exact numbers are usually not that important. Just an abstract description along the line of this is mostly enough to start:
> Barrels on a subnetwork, attached to a main network. But the input is bypassing the main network and inserted on an interface on the storage network.

**Comment by APasz** [comment]
Noted.

**Comment by Cisien** [comment]
Try placing an energy cell on the network. I'm curious if it's just running out of power (the subnet specifically)

**Comment by APasz** [comment]
Fired up MC this morning and the issue has stopped. I'm going to leave MC running all day to see if its a time sensitive issue.

**Comment by yueh** [comment]
Maybe just a random hiccup. Reopen if more information.

**Comment by Zaflis** [comment]
Definitely issue that happens when there is no AE2 energycell. I guess fix would be to up the default power max for networks. Using hotkeys to insert whole inventory of items in Terminal at once reproduces this easily, even if it's receiving power from full resonant energycell.

**Comment by Cisien** [comment]
The fix is already in the mod, and that I to use energy cells. That is why they are around.

**Comment by Zaflis** [comment]
I have 1 dense energy cell in the network, and it is always full of power.

Also changing the storage bus filter may not always update immediately. I save the settings in memory card, replace the storage bus and load settings. Filter update done.
