### ISSUE TITLE
Sculk Transmitter from Deeper and Darker crashes game when placed into ME storage

### ISSUE THREAD

**Issue by remotecontrol13** [AppliedEnergistics/Applied-Energistics-2#7455]
### Describe the bug

A Sculk transmitter from the mod Deeper and Darker was placed into the ME storage system. This transmitter was also linked to a barrel in the overworld. Upon accessing the crafting terminal, searching for the sculk transmitter item caused the game to crash. 

### How to reproduce the bug

1. Link sculk transmitter to barrel.
2. Place sculk transmitter in ME storage.
3. Destroy barrel.
4. Search for sculk transmitter in ME storage and hover over item.

### Expected behavior

The sculk transmitter item renders properly, and can be placed and removed from the storage system as normal.

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/SLN7CvyZ

**Comment by mindforger** [comment]
seems like the deepderdark mod does not like their blocks to be moved
can the transmitter even be moved by a piston without crashing?! 
you should ask deeperdarker dev about this issue and put the block on the blacklist for teleporting in the mean while to avoid that happening again

**Comment by Technici4n** [comment]
Looks like a bug in Deeper and Darker when trying to retrieve a tooltip.
