### ISSUE TITLE
Incompatibility with starlight 1.20.1

### ISSUE THREAD

**Issue by HumanF91R** [AppliedEnergistics/Applied-Energistics-2#7456]
### Describe the bug

Opening guide with starlight crashes the server

### How to reproduce the bug

Open the guide with starlight installed

### Expected behavior

Guide opens fine

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/ejsbDPjk

**Comment by Sea-Kerman** [comment]
Yes, we know. Remove starlight, it barely does anything in 1.20 anyway because Mojang essentially implemented it in the base game.
