### ISSUE TITLE
Mod sucks now, make it better again!

### ISSUE THREAD

**Issue by asgdfagdsfg** [AppliedEnergistics/Applied-Energistics-2#746]
Channels are retarded. Remove them!
Stupid troll developers making the game unplayable on servers...
And no, you can't disable this crap without breaking the mod.
Developers just lie about that. Pathetic people spending their time just to make other's people game experience worse... you guys are worse then griefers. Just destroy your shitty work on AE2 and let people go back to AE1, instead of fooling them and acting like this shit will ever become good again!

**Comment by TheJulianJES** [comment]
AE1 was way to overpowered, if you don't like channels disable them in the config. You should learn the mod! There is hole wiki, good spotlights on youtube. Try the mod!

**Comment by asgdfagdsfg** [comment]
Quote:"
And no, you can't disable this crap without breaking the mod."

As i said, you can't disable it. The Developers are just trolling.
They said many many times, that the mod is built on those "channels", why would "disabling" them, help us? OF COURSE it breaks the mod, if the mod NEEDS the "channels".

When people say that they don't want channels, they OBVIOUSLY mean, that they don't want TO CARE ABOUT channels, as in "we want unlimited channels per cable"...

Give us an option to do THAT, instead of the crappy "you can disable the thing, that makes the ME system RUN" troll move...

**Comment by FireBall1725** [comment]
Here allow me to add my 2 cents to the entire thing, I hate feeding the trolls, but this is a great example of messages from real people I get all the time, and maybe someone else who is frustrated with the channel systems will be able to learn something.

@asgdfagdsfg it is people like you that I can't stand, a mod developer changes the mod, and you come along and go "OH NO, IT CHANGED!!!". I have met many people who didn't like the channel system in AE2 and it was for the lack of understanding, very similar to your first message you posted about not being able to run one cable around your base.

That is why I love to make complex AE designs on my Server Play series that take AE2 to the limit and show that you CAN run one cable around your base still, it just requires you to think and plan it out a little better than in AE1. I have over 300 grid nodes on my AE system, attached through 1 cable that runs around my entire base, and guess what, it works great.

If you really don't understand and are willing to learn then I think any of us would be more than happy to explain in detail how to setup a large AE system, but I can say that 1. the channel system is not going away, and 2. you still can run one cable around your base, and finally AE2 is far superior to AE1 any day of the week.
