### ISSUE TITLE
Why is there no good version of AE for 1.7.10?

### ISSUE THREAD

**Issue by asgdfagdsfg** [AppliedEnergistics/Applied-Energistics-2#747]
Why are you not offering the GOOD version of the mod on this site?

This stupidity is driving me insane...

20 versions of this mod, and ALL of them are broken. For some of them you don't even have to disable channels, to be broken. There, the ME Controller, just doesn't accept energy at all...

I hate the devs more then regular griefers. They are literally griefing their own project, and with that, everyone who is "bound to servers" where you are forced to use this garbage...

Do something about those damn channels, or give your GOOD source code, to someone who knows how to IMPROVE things, instead of making them worse. This mod worked fantastic, and you are doing NOTHING but screwing it up. WHAT errors are you even fixing? Last time i saw AE1, it didn't have any... WHY is AE2 so much worse? I don't get it... you HAD a GOOD source code... why make it SO INCREDIBLY BAD, that it HAS to rely on something idiotic as "channels" because "they are required for the controller to see things!"... NO THEY ARE NOT! AE1 worked PERFECT! NO CHANNELS! God... it just goes beyond my mind... WHY??? How much time did you people spend on this crap? For WHAT??? Just getting some shits and giggles from people that actually believe your "you can disable channels!" troll move, like i did? Well, i hope you are laughing. Personally, i can't wait until you get bored of being massive trolls, and someone else picks up your old work... Even if i could get the basic stuff from your mod, working in a good mod, i would love to see a GOOD version of AE2. There is so much awesome stuff that could be added, but instead, stuff only gets removed, and slowed down... There are billions of people out there, that could do a WAY better job at making a successor to AE1.
The people that work on it now, clearly just want to ruin the fun for everyone. Why else would you crap all over one of the best mods that were ever made? Why remake it? Why change it? ALL you had to do, was make it compatible with the newest minecraft version, and everyone would be happy, but NO... The mod is way too good, stuff has to be slowed down, and nice and simple things, have to be converted into obscure, crappy mechanics, that make NO sense at all...

I just can't express how much this goes beyond my understanding...
WHY?
SO MANY PEOPLE?
JUST WHY???
Why do you WORK, to make something BAD???
You are not even earning big money, WHY IN THE WORLD WOULD YOU DO ""THIS"" IN YOUR FREE TIME???

What a massive nest of trolls... Amazing how they work together in a group to accomplish bigger troll-moves and bigger erections...
It's the only thing i can imagine... The devs get off, on people complaining about the mod, getting worse and worse.

They don't learn, they don't gain... There is just NO reasonable motivation behind this shit... except that they REALLY enjoy, ruining the mod for most of the old AE1 "fans", in certain way...

**Comment by FireBall1725** [comment]
Here allow me to add my 2 cents to the entire thing, I hate feeding the trolls, but this is a great example of messages from real people I get all the time, and maybe someone else who is frustrated with the channel systems will be able to learn something.

@asgdfagdsfg it is people like you that I can't stand, a mod developer changes the mod, and you come along and go "OH NO, IT CHANGED!!!". I have met many people who didn't like the channel system in AE2 and it was for the lack of understanding, very similar to your first message you posted about not being able to run one cable around your base.

That is why I love to make complex AE designs on my Server Play series that take AE2 to the limit and show that you CAN run one cable around your base still, it just requires you to think and plan it out a little better than in AE1. I have over 300 grid nodes on my AE system, attached through 1 cable that runs around my entire base, and guess what, it works great.

If you really don't understand and are willing to learn then I think any of us would be more than happy to explain in detail how to setup a large AE system, but I can say that 1. the channel system is not going away, and 2. you still can run one cable around your base, and finally AE2 is far superior to AE1 any day of the week.
