### ISSUE TITLE
simple storage network and AE2

### ISSUE THREAD

**Issue by newkincode** [AppliedEnergistics/Applied-Energistics-2#7471]
### Describe the feature

I want to use a simple storage network and AE2 together, but I found that two-way movement is almost impossible. I solved it by setting the box as below, but it would be better if I could link the root block and the storage bus.

### Reasons why it should be considered

Because it's good to be connected to everything

**Comment by newkincode** [comment]
![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/94734506/d398fb2b-92c9-4438-b56b-6f6e0c906bfc)

**Comment by Technici4n** [comment]
There isn't really a use case for this...
