### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by M3428** [AppliedEnergistics/Applied-Energistics-2#7472]
### Describe the bug

when i try to search for an item that i have in me system with [ @modname itemname ] it hide all items in terminal 
![1](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/61672224/e20da253-b3e7-41ab-b73f-093f4c31984b)
![2](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/61672224/06195b04-9814-4d85-9d6d-348e8819b3d4)
![3](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/61672224/b9c7a185-1f33-40e3-a55f-c967651b8dd7)

terminal setting

![4](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/61672224/e632a396-0658-4d35-96a3-24aec7591519)

ver appliedenergistics2-forge-15.0.15.jar

### How to reproduce the bug

....

### Expected behavior

it shows like this 
![5](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/61672224/f099c4a1-2a40-45ad-9e09-d88430f185f6)

### Additional details

i tried with search setting use ae , [search in tooltips] and without it , [sync with jei search] and without it

use jei . [search in tooltips] and without it 

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

....

**Comment by Mari023** [comment]
this is a known issue, you can only search for one of the following things:
- item name
- mod name
- item id
- tooltip

there is an open PR (#7311) that uses JEI / REI search to fix this, so it might

**Comment by Mithi83** [comment]
Either you are familiar with compiling mods yourself, in that case you can take the code from the pull request and compile it yourself.

Otherwise you have to wait for
1. The maintainer accepting the pull request into the development branch when everything has been reviewed and tested.
2. A new release of AE2
3. Potentially an update for the modpack you are playing

**Comment by Mari023** [comment]
fixed by #7924
