### ISSUE TITLE
native support for fluids

### ISSUE THREAD

**Issue by Radon-212** [AppliedEnergistics/Applied-Energistics-2#7483]
### Describe the feature

Its basically a feature which may exist in forge but doesnt in the fabric version of ae2, the fabric version contains the p2p fluid tunnel, but it does not contain the interface and some other items .

### Reasons why it should be considered

it should be considered essential as for both forge and fabric to have the same content thats offered by ae2

**Comment by Mari023** [comment]
fluids and item interfaces are unified, you can use both fluid and items in the same interface
