### ISSUE TITLE
Screen going black in spatial storage 

### ISSUE THREAD

**Issue by katenip** [AppliedEnergistics/Applied-Energistics-2#7489]
### Describe the bug

ok so a few seconds after going into spatial storage the screen goes black. Its not a crash im still in the game and can move around and hear sound and my friends can still see me and stuff. This happens to me and 2 of my friends but not to out other friend. 

### How to reproduce the bug

Enter a spatial storage dimension 

### Expected behavior

the game goes black entirely 

### Additional details

i can navigate the menus slightly using screenshots and when i leave the server it shows im in the server selector with the pause menu open 

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/S5ECedLa

**Comment by Alkiasan** [comment]
Happens for me too in 1.19.2, running on Quilt, confirmed multiple cases on my server too. Works in singleplayer as well.

Here's a list of mods me and this guy have in common:
AE2
AE2wtlib
Architectury
Badpackets
Charmonium
Cloth-Config
Create
CreateAdditions
CreateChunkloading
CreateUtilities
Emotecraft
EnhancedBlockEntities
EntityCulling
FabricLanguageKotlin
Farmer's Delight
Ferritecore
Geckolib
Immediatelyfast
Indium
LazyDFU
Lithium
MemoryLeakFix
Modmenu
Mousetweaks
Naturalist
Create: Steam and Rails
REI
Sodium
Trinkets
WTHIT
Xaero Minimap+Worldmap

Doesn't shorten it a lot, but at least gets rid of a decent amount of potential culprits, assuming this is a mod conflict.

**Comment by Alkiasan** [comment]
Update: Seems to be a conflict with ImmediatelyFast.
