### ISSUE TITLE
Cant automaticly take items out of an M E system

### ISSUE THREAD

**Issue by Antonhsus** [AppliedEnergistics/Applied-Energistics-2#7497]
### Describe the bug

Cant automaticly take items out of an M E system

### How to reproduce the bug

automaticly take items out of an M E system

### Expected behavior

An item to automaticly get out of an ME system

### Additional details

Cant automaticly take items out of an M E system

### Which minecraft version are you using?

1.12 - UNSUPPORTED

### On which mod loaders does it happen?

Forge

### Crash log

i dont have one

**Comment by Technici4n** [comment]
That's called an export bus.
