### ISSUE TITLE
The guide says that ammo weight affects damage, but it only affects weight

### ISSUE THREAD

**Issue by ChiefArug** [AppliedEnergistics/Applied-Energistics-2#7498]
The guidebook says that ammo weight affects damage, but that is untrue. It only affects penetration.
See code:
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/b271fa33c7efb90211620c3cb940f9c0a64d2b1f/src/main/java/appeng/items/tools/powered/MatterCannonItem.java#L181-L182
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/b271fa33c7efb90211620c3cb940f9c0a64d2b1f/guidebook/items-blocks-machines/matter_cannon.md?plain=1#L18

**Comment by Sea-Kerman** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/b271fa33c7efb90211620c3cb940f9c0a64d2b1f/src/main/java/appeng/items/tools/powered/MatterCannonItem.java#L347-L353

**Comment by ChiefArug** [comment]
Huh.. I tested this in game with custom ammo (weight of 1000) and that took 20 hits to kill a creeper.

**Comment by Sea-Kerman** [comment]
If you compare iron and gold you see a large difference.

**Comment by ChiefArug** [comment]
> Are you exaggerating with 20 hits? 👀 

Nope, I counted.
It may of been an issue with the incredibly custom KubeJS scripts I was using to add the ammo recipe, if the weight fields is optional and defaults to 1 damage. I can check tomorrow.

**Comment by ChiefArug** [comment]
1.20.1

**Comment by ChiefArug** [comment]
Tried again today.. and it worked?? No idea why it wasn't working before
