### ISSUE TITLE
Can we have a "HDD Activity" light on ME chests?

### ISSUE THREAD

**Issue by AlgorithmX2** [AppliedEnergistics/Applied-Energistics-2#75]
It's pretty simple, make the drive indicator light (whatever color it might be) blink when something is being written to it, or read from it. This lets me look at a small bank of ME chests and easily determine which one isn't seeing any activity. 

Impetus:

I have quarries and other auto-mining setups going all over the place, and the most efficient way to get that stuff back to my base for processing is to have whatever happens to be doing the mining dump the loot into an ender chest. I then place the corresponding ender chest at my base, slap an import bus on it and have it go into a chest. I use a series of sub networks to do this, because once those resources hit my main network, they immediately begin going through processing - something I don't want to happen until there's enough of it to power up some induction furnaces.

I'd like to know when a chest isn't seeing any more activity, because that lets me know whatever doing the mining is done (or stopped). I can do this now by opening up the storage interface to the chest, mousing over the drive and seeing if the byte count changes, but it seemed easy to just make the light blink .. and a bit more convenient :)

So, if it's not a lot of trouble, I'm sure some folks would appreciate it.

Originally Posted by tinkertim

This issue was migrated; For original details see http://ae-mod.info/Tracker/0808/

**Comment by killerall5385** [comment]
seems cool just add it to the main drives and that would be better.
