### ISSUE TITLE
Chunk Mesh Crash With Facades and Gregtech (ATM9)

### ISSUE THREAD

**Issue by AKlug1** [AppliedEnergistics/Applied-Energistics-2#7511]
### Describe the bug

"The game crashed whilst encountered exception while building chunk meshes"

### How to reproduce the bug

Genuinely have no idea but it happened twice, once when I was just idling. Error log seems to point at facades and something about Gregtech

### Expected behavior

The game not crashing

### Additional details

Sorry that I have no idea why this is happening. AE2 version 15.0.15

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/vnkntRVU

**Comment by Technici4n** [comment]
Should be fixed in recent 1.20 NeoForge: https://github.com/neoforged/NeoForge/pull/555.
