### ISSUE TITLE
Add a way to directly assign fluid to ME Storage Monitor

### ISSUE THREAD

**Issue by AlisonHuang777** [AppliedEnergistics/Applied-Energistics-2#7517]
### Describe the feature

For example, add a GUI for Storage Monitor so that the player can drag the desired filter from JEI.

### Reasons why it should be considered

Some mods do not add a correspond fluid container item (or it exists but not in normal form) when they add a new fluid to the game. Currently this makes it impossible to assign them to Storage Monitor.

### Additional details

E.g. https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry/issues/136

**Comment by Technici4n** [comment]
IMO that's really on these mods. You can always use a tank from any tech mod to set the fluid.
