### ISSUE TITLE
KubeJS `ServerEvents.recipes()` call breaks AE2 machine recipes on Quilt

### ISSUE THREAD

**Issue by Kneelawk** [AppliedEnergistics/Applied-Energistics-2#7519]
### Describe the bug

Creating a script in the `kubejs/server_scripts` folder with the content:
```js
ServerEvents.recipes(event => {
})
```
causes the charger and inscriber to become unusable and their recipes no longer appear in REI.

### How to reproduce the bug

* Add AE2 and KubeJS to an instance.
* Create a script in the minecraft `kubejs/server_scripts` folder with the following content:
  ```js
  ServerEvents.recipes(event => {
  })
  ```
* Load up a world and place down a charger and a creative energy cell, connected.
* Attempt to insert a certus quartz crystal into the charger.
* The charger refuses to accept the certus quartz crystal item.
* Additionally, the charged certus quartz and processor recipes are no longer available in REI.

### Expected behavior

The charger should accept the certus quartz item and the charged certus quartz and processor recipes should remain visible in REI.

### Additional details

This has been tested on QuiltLoader. When testing on FabricLoader, this issue did not appear. It is possible this is an issue in QSL.

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Quilt

### Crash log

https://mclo.gs/JEGO493

**Comment by Kneelawk** [comment]
Upon further inspection, the `ae2:charger` recipe type appears to get removed completely.

**Comment by Technici4n** [comment]
> This has been tested on QuiltLoader. When testing on FabricLoader, this issue did not appear. It is possible this is an issue in QSL.

We don't support quilt, sorry.

**Comment by Kneelawk** [comment]
Thankfully, I was able to find a workaround by manually registering all of AE2's recipe serializers with KubeJS.

**Comment by Kneelawk** [comment]
Looks like this isn't even an AE2 issue, as I'm running into it with other mods too.
