### ISSUE TITLE
ME Storage Bus does not detect being attached to an ME Pattern Provider

### ISSUE THREAD

**Issue by ProtoSebastian** [AppliedEnergistics/Applied-Energistics-2#7520]
### Describe the bug

While trying to automate making processors, I noticed the ME Storage Bus shows "Unattached" when connected to an ME Pattern Provider, and the finished processor doesn't get pushed inside the Pattern Provider's return inventory. even though It should be exposed using the ME Storage Bus.

### How to reproduce the bug

Try the example "Processor Automation" network in AE2 v12.9.8 for 1.19.2 Forge

### Expected behavior

Everything works until the last Inscriber that makes the actual processor, items stay inside and don't get pushed inside the return inventory of the Pattern Provider

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

not a crash report

**Comment by Sea-Kerman** [comment]
send a picture I guess

**Comment by ProtoSebastian** [comment]
![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/72770934/e274fa1e-a4cf-4940-a412-5ab3340f7719)
![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/72770934/c13189fc-4ba2-4fbc-884b-07708965ea53)

If I connect the Storage Bus to an inventory it can detect (like a barrel) all the finished items go there successfully. It's just an issue with the Pattern Provider.

**Comment by ProtoSebastian** [comment]
![2023-12-31_03 46 05](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/72770934/485dc797-02d9-4b91-ae7b-94cdbe77e53e)
![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/72770934/b022b363-dcf5-4a8a-9370-7f87146d42be)
![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/72770934/772efad8-a012-404a-adce-df7040a814f6)


more images, the Storage Bus connected to the Pattern Provider thinks it's not attached to an inventory, and the Engineering Processors don't get transferred.

![2023-12-31_03 50 07](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/72770934/5fb5ebce-e7d0-4da2-9048-b776eec3fb62)
![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/72770934/38d46f69-5951-47e7-850b-f59647b88a9a)
![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/72770934/33ab30d7-f02a-48a8-8aab-0d2d7545ff85)

but if I connect an inventory the Storage Bus detects (a barrel in this case) on the return subnet, it works and the Engineering Processors get transferred to that inventory. But it needs to go to the Pattern Provider inventory.

**Comment by ProtoSebastian** [comment]
The problem was optifine, I didn't realize that until I read [this page](https://guide.appliedenergistics.org/1.20.1/items-blocks-machines/molecular_assembler) and wondered if removing optifine would fix it, and it did.
