### ISSUE TITLE
Broken Spatial Anchor Loaded Chunks Rendering

### ISSUE THREAD

**Issue by AlisonHuang777** [AppliedEnergistics/Applied-Energistics-2#7538]
### Describe the bug

https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/51637996/d921a366-7195-4af0-9f29-808b0575d9a4

### How to reproduce the bug

See footage submitted.

### Expected behavior

Not broken.

### Additional details

Playing Prominence II Classic modpack. The pack is using Embeddium.

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

*(Not a crash report)*

**Comment by LostQuasar** [comment]
Can confirm happens in an instance with just Rubidium or Embeddium.

**Comment by Technici4n** [comment]
Can't reproduce with Embeddium 0.3.3 in 1.20.4.
