### ISSUE TITLE
When pushing autocrafting ingredients batches into some specific Create machines/containers, it is only able to push 1 batch

### ISSUE THREAD

**Issue by AlisonHuang777** [AppliedEnergistics/Applied-Energistics-2#7557]
### Describe the bug

In Create, **Crushing Whee**l, **Depot**, **Chute**, and **Belt** can only process/transfer 1 stack of items at a time, with each machine has their own different stack size limit. Now assuming that I have a Pattern which takes 1 item as input. So if I try to push batches of items with a Crafting CPU which only has 1 Crafting Unit, it is expected that the machines will only process/transfer 1 item for each batch, and will *not* accept more items until the process/transfer is complete.
However, when the Crafting CPU has more than 1 Crafting Units, it is expected that the machines will process/transfer more than 1 items at a time, since multiple batches of items are pushed at the same time, right? but **NO**... it is still the same with the scenario where the Crafting CPU has 1 Crafting Unit, only 1 item get pushed into the machine, and before the machine is done no more (batches of) items is accepted. Due to Create's machines (specifically Crushing Wheels in this scenario) is more efficient when processing multiple items (in 1 stack) at a time, this bug can greatly decreases the efficiency of some autocrafting setups that involves directly pushes ingredients into the machines.

Note that if the Pattern has more than 1 items as input, then those items can be pushed into the machine(s) normally, if not exceeding the stack size limit of the machine(s). But it is still can push only 1 batch of items.

### How to reproduce the bug

(I have properly described the bug in detail in the section above, so it should be not that hard to figure out how to reproduce the bug by yourself. ~~I'm just lazy.~~)

### Expected behavior

It should be able to push more than 1 items if I have more than 1 Crafting Units.

### Additional details

Playing Prominence II Classic modpack, using AE2 v15.0.11, Create v0.5.1.f. The version of Forge (which the modpack is using) is 47.2.6.

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

*not a crash report*

**Comment by AlisonHuang777** [comment]
Updated the original post to edit the phrasing and arrangement of the texts.

**Comment by Mari023** [comment]
patterns always get dispatched 1 at a time.
if you want more items to be dispatched in one operation, you have to encode the pattern so the system knows how much to push in one operation.
ie. 64 items -> 64 other items
instead of 
1 item -> 1 other item

**Comment by AlisonHuang777** [comment]
You didn't get my point.
The mentioned Create machines will block any input once it receive any items. My question is, since multiple operations of 
pushing (batches of) items are executed by multiple Crafting Units *at the same time* (e.g. *in the same tick*), shouldn't all of those items are able to enter the machine? Like, the machine will only locks the input after the items have imported.
If this is an issue with how Create manages things, then maybe you can tell me to report this to Create.

**Comment by Random832** [comment]
You can use an intermediate container [a subnet connected via a *configured* interface will allow you to get the full throughput potential - an unconfigured interface will have the same problem due to the pattern provider passing through directly to the storage bus], or configure the pattern to send multiple ingredients at a time [by doing so you won't even need the coprocessors, but it does lock you into only crafting multiples of whatever amount you set up the pattern for]

**Comment by AlisonHuang777** [comment]
Although I'm not asking for workarounds, but thanks for your respond. I have now convinced myself that this issue is more about mechanics of Create rather than that of AE2, so I'm going to report this (or, instead of that, *suggest*) to Create.
