### ISSUE TITLE
Extreme lag when crafting a large amount of items (Shift+Click) from the terminal

### ISSUE THREAD

**Issue by NullOnSec** [AppliedEnergistics/Applied-Energistics-2#7565]
### How to reproduce the performance issue

Setup a storage system with a crafting terminal, fill it up with a large amount of items (big stack sizes) and try to craft large amount of items shift clicking. After doing that, the server will literally hang for a few seconds; on lower end hardware the server would hang for a couple minutes.

![perf2](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/69851468/8110f97a-284f-4b33-9dca-aebe927f20e8)
![performance](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/69851468/ccb3f0fa-32ba-4247-bb74-432450587207)
The version of the mod is 15.0.18.

### Spark profile link

https://spark.lucko.me/FIbMX2JChM

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

**Comment by Mari023** [comment]
the spark link doesn't work for me (there might be an issue with spark, I experienced multiple cases of links not working recently), but my guess would be this issue is caused by FTB quests (see https://github.com/FTBTeam/FTB-Mods-Issues/issues/1063)

**Comment by NullOnSec** [comment]
Yeah, you're right. The performance issue are cause by ftb-quests not AE2. Thanks for the quick reply and for pointing that out.

**Comment by NullOnSec** [comment]
> FTB Quests 2001.3.1 should fix this problem.

Indeed, https://maven.ftb.dev/#/releases/dev/ftb/mods/ftb-quests-forge/2001.3.1 I updated to this version and the problem is solved.

Thanks.
