### ISSUE TITLE
Crafting CPU's should consider items coming in unscheduled

### ISSUE THREAD

**Issue by Josua-P** [AppliedEnergistics/Applied-Energistics-2#7568]
### Describe the feature

While crafting, CPU's should sometimes check if items listed as scheduled are available in the system. If so, these items should be used and all crafting steps necessary to craft them should be cancelled (or the count of scheduled items reduced).

### Reasons why it should be considered

In Create (as well as some Create submods), some recipes have a guaranteed output and some chance of providing more. In this case, all items that are not specified in the pattern are placed in the system and "lay around uselessly". This feature would significantly reduce crafting time for processes containing such items. 
(It would also be nice if you could “support” the system manually: For example, if you need a lot of concrete but the sand production speed is simply not enough, you simply go into the desert, fill a Shulkerbox of sand and load it into the system, so that the crushing wheel only has to take over the gravel.)

**Comment by Technici4n** [comment]
Autocrafting relies on the CPU being able to anticipate exactly which items it needs and which items it does not need. We will not be changing this, sorry. The extra items that "lay around useless" can be used by another crafting task. ;)
