### ISSUE TITLE
If you throw a stack of crystals into the funnel, the charger doesn't pick up the crystals, only one at a time

### ISSUE THREAD

**Issue by 0mommy** [AppliedEnergistics/Applied-Energistics-2#7569]
### Describe the bug

If you throw a stack of crystals in the funnel, the charger does not take the crystals, if you put in the funnel one by one, it takes them

### How to reproduce the bug

https://www.youtube.com/watch?v=R362cRUGBVI

### Expected behavior

It's coming off the stack

### Additional details

Methinks:
'ae2:certus_quartz_crystal' - true quartz crystal
'ae2:charged_certus_quartz_crystal' - A charged crystal of true quartz
'ae2:charger' - charger
'minecraft:hopper' - hopper

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

-

**Comment by Technici4n** [comment]
Can't reproduce on neoforge 1.20.4.
