### ISSUE TITLE
ME Interface priority does not work propely

### ISSUE THREAD

**Issue by Gui1803** [AppliedEnergistics/Applied-Energistics-2#7570]
### Describe the bug

_Made with my English learned at school and translate, sorry for any lack of clarity..._

I'm trying to create a system to deal with excess seeds. To do this, I tried to use the ME Interface to first send the seeds from the system to the Phytogenic Insolator (Thermal) and, after it was full, send them to the other Interface that is connected to a subnet with a Seed Reprocessor (the example was with seed wheat, but they would seeds from Mystical Agriculture).

As described, there is a need for a higher priority for Phytogenic, otherwise the seeds will be processed first and the phytogenic will not have seed. What happens is that **the system is sending the 2 ME Inteface to the internal stock randomly, without taking into account the priority set.** In the example I demonstrate the alternating priorities and it clearly did not affect the way the system sends the seeds.

In the video I show a system without any wheat seeds initially, to have greater control of the example. However, if I stock all the seeds (or at least 5, a value above that defined in both ME Interface), the system tries to fill that Interface until it reaches 4 slots, so it also does not act as a round-robin. This further slows down the flow, as while the ME Interface is filling up, the machinery is pulling resources, so it never reaches 4 until the machine is full.

AE2 : 15.0.19
Forge: 47.2.19
Modpack: ATM9 0.2.37

### How to reproduce the bug

Exemple: https://streamable.com/prf4i2

### Expected behavior

The priority should act on the ME Interface. The one with higher priority should always be refueled ahead. Furthermore, if the ME Interface with the highest priority loses 1 item (which went to the machine in my case), that item must be replenished first than the other ME Interface, regardless of whether the second one is full or not. **In other words, the ME Interface should act with real-time priority**

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

None

**Comment by Technici4n** [comment]
Thanks for the issue report. This is a bit counterintuitive, but it is how interfaces work, and it is not feasible to change it. Since interfaces work by "actively" pulling items from the system, they cannot respect priorities in that way. (Because even the higher priority interface might be sleeping for one tick, and the lower priority might get the request first).

To use priorities reliably, you need "passive" storage components, i.e. storage busses.
