### ISSUE TITLE
Add recipe confliction pattern encoding support

### ISSUE THREAD

**Issue by TNoStone** [AppliedEnergistics/Applied-Energistics-2#7573]
### Describe the feature

![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/815274/27d351eb-43dc-48ee-9112-085527530ece)
This is an image of an example of what I mean by recipe confliction support, shown in a crafting table.

AE2 system, from what I can tell, is not able to give the user the option to choose which output is given in a recipe confliction. 

### Reasons why it should be considered

Will improve autocrafting and mod compatibility

**Comment by Technici4n** [comment]
In my opinion, it's the job of modders and pack makers to ensure that this does not happen.

**Comment by 62832** [comment]
Have you heard of [Polymorphic Energistics](https://www.curseforge.com/minecraft/mc-mods/polymorphic-energistics)?

**Comment by TNoStone** [comment]
Hey thanks!
