### ISSUE TITLE
Logistics Pipes Integration

### ISSUE THREAD

**Issue by Y0da1** [AppliedEnergistics/Applied-Energistics-2#759]
Hey! I noticed today that I can not acces my LP system from any ME terminal, nor can I request from AE system using my Logistics Request Pipe.

I have a ME Interface connected to a Request Pipe and a provider pipe. This setup used to work on rv1 stable 1. Note that I use the lates beta, rv2 beta 7

I also noticed that there's no "Logistics Pipes" in modintegration config.

**Comment by Cisien** [comment]
AE doesn't have any support for Logistics Pipes at this time. However, Logistics Pipes does have AE support. Placing a provider pipe on an interface that is not configured will provide your logistics pipes network access to our ME network.

We have an open feature request already for the AE2 side of things. https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/759

**Comment by fdsgdfgdfh** [comment]
How about just making the shitty normal AE2 glass cables work properly? Then people would not need old crappy mods like logistic pipes... But no... they have to be useless as fuck. WHY would a cable support more then 3 machines? Fucking idiot devs...
