### ISSUE TITLE
Some squares lose texture when used with Continuity mod.

### ISSUE THREAD

**Issue by 123qwqeq** [AppliedEnergistics/Applied-Energistics-2#7596]
### Describe the bug

![2024-02-07_20 24 32](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/138661199/268d4c47-d973-4ae4-9ac4-08005d70e9d0)
game 1.20.1  fabric
mod 15.0.20
block ME Annihilation Plane
         ME Formation Plane

### How to reproduce the bug

Loaded with Continuity

### Expected behavior

The texture of the above two squares is missing

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Fabric

### Crash log

No crash.

**Comment by Technici4n** [comment]
Fixed by https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/7616, will be released soon™️.
