### ISSUE TITLE
Game crashes while opening guide to some items

### ISSUE THREAD

**Issue by ProGmr1337** [AppliedEnergistics/Applied-Energistics-2#7599]
### Describe the bug

When I try to open the guide to some items (i guess the complicated ones) my game crashes on opening of the guide, I wont even see the guide

### How to reproduce the bug

Open the guide to the ME controller, Annihilation plane, ME quantum ring, and other "complicated" items (best explanation for what guides crash the game)

### Expected behavior

I expect the game to open the guide to the item

### Additional details

Here is are the mods i use (i also use the modrinth app on 1.20.1 and Forge version 47.2.17, i don't know if fabric also crashes or not, fabric just sucks and more mods are compatible with forge so I pretty much only use forge) the crash log is from trying to open the ME controller guide
Here are the mods:
[Uh huh, sooooo 1.0.0.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/14201603/Uh.huh.sooooo.1.0.0.zip)

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

https://mclo.gs/WPwgv8l

**Comment by Sea-Kerman** [comment]
Remove starlight, minecraft 1.20 has had most of the Starlight optimizations integrated into vanilla, so mods go off of just the vanilla lighting engine now

**Comment by ProGmr1337** [comment]
> Remove starlight, minecraft 1.20 has had most of the Starlight optimizations integrated into vanilla, so mods go off of just the vanilla lighting engine now

Thanks, it worked!
