### ISSUE TITLE
Console spam with AE2 Rv2 B7

### ISSUE THREAD

**Issue by RTRGitHub** [AppliedEnergistics/Applied-Energistics-2#760]
http://pastebin.com/Ey9YQqg2

Tried using RV2 B7 and B6 with matching addons Extracells/Thaumic Energistics, Seeing this spam in console without chunks being loaded or players being on the server, often continues for up to 5 minutes straight

**Comment by yueh** [comment]
This looks like you have a security station somewhere, which tries to link with a non secure network or one belonging to another player.

**Comment by RTRGitHub** [comment]
Hmm, That's weird, That would  be a lot of security stations to search,,,

**Comment by yueh** [comment]
@RTRGitHub could you please try [this build](http://ci.tsr.me/repository/download/AppliedEnergistics_PullRequests/1025:id/appliedenergistics2-rv2-alpha-pr761.jar)?
It should contain a more useful error message.

**Comment by fdsgdfgdfh** [comment]
AE2 is complete garbage, what a surprise that those morons can't even make a console work right.

**Comment by RTRGitHub** [comment]
Will test it on my server now, thanks for the help :)

**Comment by RTRGitHub** [comment]
Hmm, Can't test it because thaumic energistics refuses to recognise the file as it isn't beta 7.. maybe some name changing will work..

**Comment by RTRGitHub** [comment]
Nope, I can't test this on the server without ripping out Thaumic energistics, due to ThEns dependency on Beta 7 =/

**Comment by yueh** [comment]
Maybe download the whole world, if it is not that large and drop Thaumic Energistics locally?

**Comment by RTRGitHub** [comment]
It's a big world, But I'm gonna use a backup for testing real quick

**Comment by RTRGitHub** [comment]
That worked, produced locations for the broken tunnels, thanks for the help!

**Comment by RTRGitHub** [comment]
Since we know the issue is fixed as it were, I'll close this, thanks
