### ISSUE TITLE
Cannot autocraft items when the ingredients are obviously enough

### ISSUE THREAD

**Issue by AlisonHuang777** [AppliedEnergistics/Applied-Energistics-2#7602]
### Describe the bug

https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/51637996/a2fe4213-add1-412c-80c9-3b6733f52724

### How to reproduce the bug

Unknown. (But please see the Additional details)

### Expected behavior

I should be able to craft it.

### Additional details

Playing Prominence II Classic v2.2.0 modpack, and it's modified: https://gist.github.com/AlisonHuang777/d7b6cd3edf14da526dda8b70a7914cd9
I'm willing to provide the world save if necessary.

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/AlisonHuang777/6bf0cdc6937764d5ccc75ef23fbbfa2c

**Comment by MageInBlack** [comment]
I cannot replicate it on my modpack or on Prominence II Classic with or without the modifications. The setup is not exact but similar in that it does the same thing. What i tried to replicate:

1. Create a new creative world
2. 2 nets, one to supply the interface that is set to stock 64 of the required items. The other to do the crafting, there is no level emitter cause i was testing only the part that could bug out. Pattern providers directionally feeding to interfaces connected to the storage buses at depot and deployer, filtered. Which creates another subnet for deploying
3. During those try and craft the first stage of precision mechanism: leave and re-enter the world. Enter the nether and repeat the quit and join. Quit the game entirely and re-join. Do same in the nether.

It works every time. I am able to set the first stage of precision mechanism to craft. As i cannot replicate this setup, there is more at play here and it is not that simply replicated

**Comment by AlisonHuang777** [comment]
I found the cause for this bug: #7484. The Pattern that I somehow created is using ingredients that contains `tag:{}` NBT data, thus the system could not understand the normal ingredients in the system which do not have that NBT data.
