### ISSUE TITLE
AE2/Powah "give item" glitch

### ISSUE THREAD

**Issue by Madfish5415** [AppliedEnergistics/Applied-Energistics-2#7603]
### Describe the bug

This bug allows you to give yourself any item (even creative ones) from a quartz certus. I'm using a certus quartz for the demo but it work with any item who can charge with powah.

Versions used:
appliedenergistics2-fabric-15.0.20
Powah-5.0.4

### How to reproduce the bug

You'll need:
1x Energizing orb and some power supply
1x Storage bus
1x Export bus
1x Barrel or any kind of storage

![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/44067562/1bd68c75-0f0a-40a0-b1eb-680f78f390f4)

Once done, just put whatever item you want in the export bus (using drag'n'drop from JEI, REI or others):

![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/44067562/55bc67de-b7ce-4c94-8a13-d6ec03819b8d)

Now put a certus quartz into the orb:

![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/44067562/65989af2-4d78-420f-9708-3f79bdf6bb42)

It will charge and get absorbed by the system

Open the barrel and TADDAAAAAAM:
![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/44067562/89c01199-3f9b-4877-8837-69bf81e58efb)

### Expected behavior

Just giving us the "charged" item.

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/cvvu20Bv

**Comment by Technici4n** [comment]
Probably a Powah bug, but I haven't confirmed it.

**Comment by Technici4n** [comment]
Should be fixed in https://github.com/Technici4n/Powah/commit/62b7f556959c413ebb94236e9beb9b373672b1a8.
