### ISSUE TITLE
Spatial IO doesn't work with budding redstone geore blocks from geore mod

### ISSUE THREAD

**Issue by typetetris** [AppliedEnergistics/Applied-Energistics-2#7617]
### Describe the bug

Trying to store a budding redstone geore block in spatial IO storage, it doesn't vanish.

### How to reproduce the bug

Use [GeOre Mod](https://www.curseforge.com/minecraft/mc-mods/geore) and build the spatial IO setup in the [linked images](https://postimg.cc/gallery/zNVHCgrH)

Pressing the button on the Spatial IO Port draws the energy and moves the spatial io storage cell from one slot to the other slot. The spatial io storage cell doesn't show any indication on hovering, that something was stored. The block doesn't vanish.

Client Log says stuff like:
> [09:49:31] [Render thread/WARN] [AE2:C/]: Failed to retrieve spatial storage dimension: java.lang.IllegalStateException: No server is currently running.

Sever log said:
> [13Feb2024 09:44:58.860] [Server thread/INFO] [Jade/]: Syncing config to GrumpySheep42 (f98c15e5-0f81-4b9f-a805-00c8589a62c3)
> [13Feb2024 09:45:58.765] [Server thread/WARN] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: GrumpySheep42 moved too quickly! -162.92558212372356,-64.5,-251.78497127004715
> [13Feb2024 09:45:58.767] [Server thread/WARN] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: GrumpySheep42 moved too quickly! -162.92558212372356,-64.5,-251.78497127004715
> [13Feb2024 09:47:16.020] [Server thread/INFO] [AE2:S/]: Block Copy Scale: 1, 1, 1
> [13Feb2024 09:47:16.021] [Server thread/INFO] [AE2:S/]: Block Copy Time: 502616
> [13Feb2024 09:47:16.036] [Server thread/INFO] [AE2:S/]: Update Time: 15261712
> [13Feb2024 09:47:16.075] [Server thread/WARN] [AE2:S/]: Exceeded time limit of 25 ms after processing 3 queued tick callbacks (1 remain)
> [13Feb2024 09:54:58.975] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
> [13Feb2024 09:54:58.976] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving players
> [13Feb2024 09:54:59.018] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving worlds

So the client seems to be confused, but the server did something?

### Expected behavior

I expected the block to vanish and the spatial storage cell to show some indication that something is stored.

### Additional details

[Full Client Log](https://unsafeperformio.org/client.log)
[Full Server Log](https://unsafeperformio.org/server.log)

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

Full client and server logs provided in the details, please tell me if a crash log is still needed.

**Comment by mindforger** [comment]
do other vanilla blocks vanish when placesd in the space together?! afaik they need to be whitelisted to be portable

**Comment by Mari023** [comment]
> do other vanilla blocks vanish when placesd in the space together?! afaik they need to be whitelisted to be portable

iirc by default all blocks are allowed now.

but the geore budding blocks have the tag that prevents blocks from being moved by spatial io (they aren't movable using 
create either)

**Comment by typetetris** [comment]
Ahh, that's sad. Can I configure it somehow to allow it with spatial IO?

I know GeOres author doesn't want them to be movable, but I like the flair of the scifi tech spatial IO more and want
it to be able to really move all blocks.

**Comment by typetetris** [comment]
Closing, not a bug

**Comment by Mari023** [comment]
> Ahh, that's sad. Can I configure it somehow to allow it with spatial IO?

I think you can remove the tag using a datapack
