### ISSUE TITLE
crash after start + Huge TPS consuming problem (1.7.10)

### ISSUE THREAD

**Issue by Cronosus** [AppliedEnergistics/Applied-Energistics-2#762]
Hello.
we have problem on server, crashing a short time after start.

full fml-server-latest.log: http://pastebin.com/fgmH973C
crash report: http://pastebin.com/vJecM5LJ

before this we have again and again TPS lowering problem (after few hours TPS going down to 10TPS and down.. we don't know why) with this spamming in console:
[21:17:30] [Server thread/WARN] [IC2/]: EnergyNet.removeTileEntity: appeng.tile.misc.TileInscriber@5e366688 (appeng.tile.misc.TileInscriber@5e366688) doesn't match the registered te appeng.tile.misc.TileInscriber@6702536a, skipping

can you help me please?

thanks in advance

**Comment by yueh** [comment]
#276

**Comment by Cronosus** [comment]
i try latest (rv2-b7) build a i have this
[15:15:10] [Server thread/WARN] [IC2/]: EnergyNet.removeTileEntity: appeng.tile.misc.TileInscriber@3ebe9fb9 (appeng.tile.misc.TileInscriber@3ebe9fb9) doesn't match the registered te appeng.tile.misc.TileInscriber@6702536a, skipping
+ tps going down under 1TPS.. :(

**Comment by Cisien** [comment]
those errors are harmless, they are from IC2.

Anything can cause TPS issues. Run visualvm and grab a snapshot to help narrow down what is causing it. Running Opis may help as well.

**Comment by Cronosus** [comment]
we test AE and problem found in autocrafing, crafting lowering rapidly tps
situation: while is crafter one item tps going down more than crafting example 64 items at once.
upgrades make it fastest and tps going down very rapidly. (one or more items.. tps going down)

**Comment by yueh** [comment]
Some mods like ExtraBees/ExtraTrees are know or were known to have extremely taxing crafting. It is not really noticeable in a vanilla crafting table as you usually craft a few items with it.
If a single item takes 0.5 msec, crafting a stack will already take about 32msec. So a major piece of a single tick. Now add constant autocrafting to it and add acceleration cards to make it even faster and you will notice it.

But sadly we cannot really do anything about it. I can only recommend, that you profile the server and identify the mod causing the issue and notify them.
