### ISSUE TITLE
Mod is awesome now!

### ISSUE THREAD

**Issue by fdsgdfgdfh** [AppliedEnergistics/Applied-Energistics-2#763]
Hey everyone! wonderful mod.

**Comment by FireBall1725** [comment]
@fdsgdfgdfh how does it feel to be a little kid who isnt going to get their way on here?  You can keep creating tickets, and all i will do is keep changing them. i can only hope that one day when you grow up that you will look back on your life and go, wow i was an idiot.

**Comment by FireBall1725** [comment]
actually, ill leave this open, would love to hear a reply from you about why you feel the need to be a complete idiot and why you fail at life?
