### ISSUE TITLE
Instead of the item's craft, hovering over it displays the item's involvement in another craft

### ISSUE THREAD

**Issue by 4u4aaa** [AppliedEnergistics/Applied-Energistics-2#7630]
### Describe the bug

Instead of the item's crafting, hovering over it displays the item's involvement in another craft. This happens when hovering over an item in a clip or search while the player is in the ME terminal for coded patterns. If the player moves to the ME manufacturing terminal, and points to the same item, the problem in the ME terminal for coded patterns with that item disappears for a while. Works with any item.

### How to reproduce the bug

 .

### Expected behavior

 .

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

.

**Comment by Technici4n** [comment]
Please show some pictures, I don't understand.
