### ISSUE TITLE
When you order autocrafting yellorium ingots in the furnace from ic3 autocraft does not complete, and some yellorium ingots disappear somewhere

### ISSUE THREAD

**Issue by 4u4aaa** [AppliedEnergistics/Applied-Energistics-2#7633]
### Describe the bug

When you order autocrafting yellorium ingots in the furnace from ic3 autocraft does not complete, and some yellorium ingots disappear somewhere

### How to reproduce the bug

.

### Expected behavior

.

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

.

**Comment by Technici4n** [comment]
What the hell is IC3?

**Comment by 4u4aaa** [comment]
The same IC2 only supplemented with self-written mods

**Comment by Technici4n** [comment]
Hmmm. Honestly this is likely an issue with some other mod. If this were an AE2 bug then it would have been reported to us much earlier.
