### ISSUE TITLE
If you throw a stack of crystals into the hopper, the charger won't pick up the crystals.

### ISSUE THREAD

**Issue by 4u4aaa** [AppliedEnergistics/Applied-Energistics-2#7634]
### Describe the bug

If you throw a stack of crystals in the hopper, the charger does not take the crystals, if you put 1 by 1 in the hopper, it does.

### How to reproduce the bug

.

### Expected behavior

.

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

.

**Comment by Technici4n** [comment]
Can you try with only AE2 (and Forge)?
