### ISSUE TITLE
Light P2P tunnel does not emmit sky light (only block light)

### ISSUE THREAD

**Issue by ImagineWave** [AppliedEnergistics/Applied-Energistics-2#7636]
### Describe the bug

![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/75631634/57edaeed-b271-40d5-af1a-9b752d48cf48)
![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/75631634/531a5bfe-d7be-469f-a806-6562a53e0005)
I've used it with glass and without it. it just doest emmit sky light. Light P2P litteraly have no other cases to use. PLS FIX

### How to reproduce the bug

![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/75631634/57edaeed-b271-40d5-af1a-9b752d48cf48)
![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/75631634/531a5bfe-d7be-469f-a806-6562a53e0005)
I've used it with glass and without it. it just doest emmit sky light. Light P2P litteraly have no other cases to use. PLS FIX

### Expected behavior

Teleport sky light level

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

.

**Comment by Technici4n** [comment]
That works as intended, they only emit block light.

**Comment by ImagineWave** [comment]
If so, what is the purpose of their existence? ;D

**Comment by Radon8472** [comment]
> If so, what is the purpose of their existence? ;D

Would be great if they could transmit sun light e.g. for solar machines from mekanism ect.
