### ISSUE TITLE
wireless crafting terminal

### ISSUE THREAD

**Issue by saphsara** [AppliedEnergistics/Applied-Energistics-2#7639]
### Describe the bug

when scrolling through storage with mouse wheel , it randomly removes item from storage and put it in our inventory. it also randomly removes all our equipped armor. we are using mod pack saphsgamingworld fabric on curse forge and fabric 1.20.1 

### How to reproduce the bug

when scrolling through storage with mouse wheel , it randomly removes item from storage and put it in our inventory

### Expected behavior

it should scroll with removing items.

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Fabric

### Crash log

n/a

**Comment by Technici4n** [comment]
Typically this happens with a broken "mouse tweaks" kind of mod.

**Comment by saphsara** [comment]
> Typically this happens with a broken "mouse tweaks" kind of mod.

ok i think i have that one will look at it, do you know how to fix mouse tweaks if that is the case?
