### ISSUE TITLE
Remove the retarded Channels already

### ISSUE THREAD

**Issue by dkjflghsdjfgh** [AppliedEnergistics/Applied-Energistics-2#764]
Hope you guys get hit by a fucking car, especially the one asshole that completely fucked up the mod and didn't understand what sarcasm is when people told him how "good" his ideas were...
You deserve that for being such pathetic little children.

**Comment by FireBall1725** [comment]
You want your way, you can have it.
AE2 will no longer have the option to disable the channels.
Thats what you were looking for, right?

**Comment by dkjflghsdjfgh** [comment]
There IS no option to disable them you moron!

**Comment by FireBall1725** [comment]
You must be too stupid to look in the config files then

**Comment by dkjflghsdjfgh** [comment]
You must be too stupid to read then, i explained that already, just like 100 other people.

**Comment by FireBall1725** [comment]
networkfeatures {
        B:Channels=true
        B:Crafting=true
        B:PowerGen=true
        B:QuantumNetworkBridge=true
        B:Security=true
        B:SpatialIO=true
    }

Change the true to false, boom no channels.

**Comment by dkjflghsdjfgh** [comment]
Changing the one "channel" thing in the "networkingfeatures" breaks the mod

**Comment by dkjflghsdjfgh** [comment]
It removes the ME Controller, learn to read

**Comment by FireBall1725** [comment]
what do you need a ME Controller for with no channels?

**Comment by dkjflghsdjfgh** [comment]
A non retarded ME System as it was in AE1?

**Comment by shobu9** [comment]
Calm down first of all channels are really not complicated to learn and they make doing cabling way more entertaining and also open config files theres channels : (disable it) if You really want No channels 

..... Stop fighting !

**Comment by FireBall1725** [comment]
with no channels enabled, you dont need a ME controller.

**Comment by dkjflghsdjfgh** [comment]
With no channels enabled, nothing i need from this mod works

**Comment by dkjflghsdjfgh** [comment]
Entertainment? How is this entertaining? Imagine they... make the SORTING mod harder... Takes 1 minute for 1 item to sort... chests dont open for 5 minutes after sorting... Thats NOT fun and NOT a challenge...

**Comment by FireBall1725** [comment]
@shobu9 i am not fighting, im just tired of this kid's crap that he has pulled all day today, he has created about a dozen accounts and posted all over our issue tracker.  If he would act like an adult then maybe his issues would be fixed

@dkjflghsdjfgh i have no interest in fixing anything for you.

**Comment by dkjflghsdjfgh** [comment]
"Acting like an adult"...
*looks at your edits*
Yea... right... because THAT is what we do here... that would TOTALLY explain the 200-300 missing threads...

**Comment by FireBall1725** [comment]
ok, @dkjflghsdjfgh i can see that you are unable to deal with this.

**Comment by dkjflghsdjfgh** [comment]
And i see that ur unable to actually disable channels

**Comment by shobu9** [comment]
Also this is not an issue... So talk to fireball on irc were No one else will ,...
Read it... *sigh-* i got brougth here by peapoles tired of getting messaged on github by you

**Comment by dkjflghsdjfgh** [comment]
Without breaking the mod of course

**Comment by FireBall1725** [comment]
If you want to talk to me on irc, im on #appliedenergistics feel free to join when your ready to stop acting like a kid, and can take a moment to listen to the devs.  Once again, no one is forcing you to use AE2, if you dont like it that much, then dont use it.

**Comment by Cisien** [comment]
if you don't like channels, then disable them in all rv2 releases. The controller, dense cables, and smart cables are removed because they aren't needed when channels are off. The controller is removed because it does not need to exist without channels.
