### ISSUE TITLE
Whatever

### ISSUE THREAD

**Issue by dsofidhsofi** [AppliedEnergistics/Applied-Energistics-2#765]
If you don't want to read the thread, don't read it, fireball will edit it anyways.

Besides that, what's your point in telling me what you just told me, when you just ban me again?

I am not giving up before this crap is playable again, i spent 1000s of hours on different servers and bases, and i am not reworking them all, because your retarded mod is on EVERYONES server, because the old mod just doesn't work at all anymore... If anyone had the choice, believe me... AE1 would be on pretty much EVERY good server, instead of this shitfest...

**Comment by Cisien** [comment]
Channels aren't going anywhere. If you don't like them, disable them in the configs.
