### ISSUE TITLE
Obvious trolls are obvious

### ISSUE THREAD

**Issue by dsofidhsofi** [AppliedEnergistics/Applied-Energistics-2#766]
So again, your only response is "Disable the thing that makes the whole mod work!"
Are you wondering about all the hate you get, or are you pissing people off on purpose just to get the hate?
Edit: Cisien, learn to read, disabling channels breaks the mod.

**Comment by FireBall1725** [comment]
you seem to be the only one with an issue like this?  maybe if you didnt post crap tickets, and gave us error logs or explained better than "it doesnt work" we might be able to help you.
