### ISSUE TITLE
You know what would be funny?

### ISSUE THREAD

**Issue by dvgdfg** [AppliedEnergistics/Applied-Energistics-2#768]
If you guys would put all the energy, you put into deleting threads, into the mod, then it would not suck so hard, people could play the game properly, and nobody would hate on you for forcing them to adapt to idiotic things that make no sense at all...

**Comment by FireBall1725** [comment]
If you wish to chat with us, http://esper.net/publicirc.php come chat on irc, channel #appliedenergistics we are all online, maybe we could explain to you how to use AE2
