### ISSUE TITLE
Viewing guide for sky stone and sky stone block causes a crash

### ISSUE THREAD

**Issue by benjamin051000** [AppliedEnergistics/Applied-Energistics-2#7681]
### Describe the bug

Holding [G] while hovering over sky stone or sky stone block (and potentially others) in the inventory/Just Enough Items causes a crash. When I rejoin without restarting (I have Not Enough Crashes so I can do this), I can't see any entities. Restarting the game returns to normal behavior.

### How to reproduce the bug

1. Acquire sky stone [block] or search for it in JEI
2. Hover over it with the cursor
3. Hold G until the bar fills up
4. Await eminent crash 
5. Rejoin without restarting
6. Observe no entities being rendered on client

### Expected behavior

Guide opens without crashing

### Additional details

One time this crashed and not enough crashes stated it was due to either AE2 or Starlight (forge port of . Other times it has stated that no mod directly caused the crash.

I have a feeling the entity rendering issues are likely a bug related to Starlight, not AE2.

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

https://bytebin.lucko.me/Wx8Lg6vijc

**Comment by Mari023** [comment]
remove starlight

**Comment by benjamin051000** [comment]
Ah, okay. It appears to work now.

**Comment by benjamin051000** [comment]
Should I maybe open an issue on starlight?

**Comment by Mari023** [comment]
> Should I maybe open an issue on starlight?

it is a known issue and fixed in later versions, but the fix was never ported to 1.20.1
