### ISSUE TITLE
Industrial craft 2 Classic support

### ISSUE THREAD

**Issue by BasilNozdrin** [AppliedEnergistics/Applied-Energistics-2#7713]
### Describe the feature

Energy acceptor should accept energy from 1.19.2 IC2classic mod

### Reasons why it should be considered

IC2 and AE for me are like brothers and after IC2c released for 1.19.2 I was really disappointed to find out that energy acceptor ignores IC2c energy.

**Comment by Technici4n** [comment]
At the moment we only plan to support Forge Energy. We are focused on NeoForge 1.20.4+ at the moment, where changes to the underlying energy system should fix IC2C compat.
