### ISSUE TITLE
craft bug

### ISSUE THREAD

**Issue by gjmhmm8** [AppliedEnergistics/Applied-Energistics-2#7717]
### Describe the bug

I encountered an issue while using the game’s crafting system. When attempting to craft an item B using item A and then return item A to its original state, the game cannot handle these two actions concurrently. I expect to be able to craft item B while still being able to revert item A to its original state for other uses.

### How to reproduce the bug

<img width="276" alt="Snipaste_2024-03-07_15-03-15" src="https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/73775469/f9ac156e-e8eb-437f-905f-153f5587f3ab">

### Expected behavior

it can use more A to craft B

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

ae2 version 15.0.21

**Comment by Technici4n** [comment]
Recursive recipes are not supported. See https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/7148.
