### ISSUE TITLE
Why am i such timewasting jerk?

### ISSUE THREAD

**Issue by gfdjhf** [AppliedEnergistics/Applied-Energistics-2#772]
Why do you waste everyones time, instead of doing what EVERYONE wants, and giving us the REAL ACTUAL option of "playing without channel limit"?

You just want to keep trolling, and more hate threads?

**Comment by FireBall1725** [comment]
Once again, you can complain all you like, but i can assure you 100% that you will not get what you want.  Please just safe yourself the effort and stop using AE if you dislike it that much, or better yet, how about you learn java and make it the way you want it, open source is great!
