### ISSUE TITLE
No Molecular Assembler

### ISSUE THREAD

**Issue by dog-lover-174** [AppliedEnergistics/Applied-Energistics-2#774]
I wanted to make a auto-crafting system in my creative world but I can't find the Molecular Assembler anywhere. If I look it up in NEI it doesn't show up, nor in the creative inventory. I also tried crafting it normally but it still won't work. I'm using the latest stablee version. (appliedenergistics2-rv0-stable-10)

**Comment by FireBall1725** [comment]
it was added in rv1, i would recommend upgrading to rv1-stable-1 or using the latest rv2-beta-7.

**Comment by dog-lover-174** [comment]
Thanks
