### ISSUE TITLE
Game crashes when opening the in-game guide.

### ISSUE THREAD

**Issue by Plexi09** [AppliedEnergistics/Applied-Energistics-2#7778]
### Describe the bug

When you open the guide, either with the item or by pressing the key on an item (G by default), the game crashes.

### How to reproduce the bug

Open the guide either with the item or by pressing the key on an item (G by default)

### Expected behavior

the guide to open

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

ZtzC0iUb

**Comment by Plexi09** [comment]
my bad, crash log here: https://pastebin.com/ZtzC0iUb

**Comment by Mari023** [comment]
remove starlight

**Comment by Plexi09** [comment]
it works thanks
