### ISSUE TITLE
Inscriber Shift Click

### ISSUE THREAD

**Issue by shadowfacts** [AppliedEnergistics/Applied-Energistics-2#779]
Shift clicking Acceleration Cards into an inscriber will not only fill up the three upgrade slots, but will put a fourth card into the center input slot. Should only be able to shift click upgrade cards into upgrade slots.

**Comment by yueh** [comment]
The middle input slot is still a valid place to place acceleration cards for example to name them.
So it is clearly not a bug.

We could maybe improve it, that it only sees it as valid inventory, if the upgrade slots are completely used. (If that is possible and shift click does not iterate over the whole inventory until everything is filled)

**Comment by yueh** [comment]
I do not think this is really possible. Shift clicking iterates over the whole inventory and tries to put a card wherever it fits.

**Comment by shadowfacts** [comment]
That's too bad.
