### ISSUE TITLE
The ME IO port can cause performance issues on certain storage components.

### ISSUE THREAD

**Issue by gjmhmm8** [AppliedEnergistics/Applied-Energistics-2#7795]
### How to reproduce the performance issue

The ME IO port can cause performance issues on certain storage components. It is recommended to retrieve component items in a single operation until no further items can be withdrawn, rather than repeating the retrieval every tick.

### Spark profile link

。

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Additional details

The ME IO port can cause performance issues on certain storage components.

**Comment by Technici4n** [comment]
Please post a spark profile that shows the issue.

**Comment by gjmhmm8** [comment]
It's another mod's bug
