### ISSUE TITLE
The ME IO port, when used in conjunction with an external storage bus, may lead to performance issues.

### ISSUE THREAD

**Issue by gjmhmm8** [AppliedEnergistics/Applied-Energistics-2#7796]
### How to reproduce the performance issue

The ME IO port exports using an external storage bus to connect to an exceptionally large chest.

### Spark profile link

https://spark.lucko.me/ptkXlw9S8u?hl=1674

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

**Comment by Technici4n** [comment]
The "Transmutation Interface" implementation is very laggy, please report this to the authors of that mod.

**Comment by gjmhmm8** [comment]
AE2 will remove items when storing them, and this operation can be very time-consuming in large storage containers.

**Comment by 62832** [comment]
This has nothing to do with AE2. You're trying to use a container that's horribly inefficient by design.

**Comment by gjmhmm8** [comment]
For the Forge API, how to improve the performance of containers?
