### ISSUE TITLE
Bring back blocky terminals from AE1 as an alternative

### ISSUE THREAD

**Issue by changhe3** [AppliedEnergistics/Applied-Energistics-2#7798]
### Describe the feature

Implement alternatives to the current panel-like terminals that occupy the whole block. The crafting recipes could be something like the corresponding terminal + energy cell.

### Reasons why it should be considered

For those of us who prefer the aesthetics of AE1 or RS. Also pattern encoding terminal works better this way as you would be able to put the export bus (for blank patterns) on top of the block which looks way better.

**Comment by 62832** [comment]
The [Fullblock Energistics](https://www.curseforge.com/minecraft/mc-mods/fullblock-energistics) add-on exists for this purpose.
