### ISSUE TITLE
Add Fluid Pattern from Extra Cells

### ISSUE THREAD

**Issue by DoremySwee** [AppliedEnergistics/Applied-Energistics-2#7814]
### Describe the feature

An item that can "record" a fluid, used for labeling fluids, which is a copy of the "ME fluid pattern" in extra cell.

### Reasons why it should be considered

To simplify the process of labeling fluids, especially if there is no convenient container for it.

**Comment by Mari023** [comment]
I don't think this is necessary, since you can already drag fluids from JEI / REI / EMI
together with being able to pin that, all use cases of extra cell's fluid pattern should already be possible, and imo even more convenient since you don't have to carry an item

**Comment by DoremySwee** [comment]
> I don't think this is necessary, since you can already drag fluids from JEI / REI / EMI together with being able to pin that, all use cases of extra cell's fluid pattern should already be possible, and imo even more convenient since you don't have to carry an item

Sometimes the fluid have nbt, and don't show up in JEI. (e.g. potion fluids)

**Comment by Technici4n** [comment]
Most modpacks have a simple tank item that you can use for this.

**Comment by DoremySwee** [comment]
> Most modpacks have a simple tank item that you can use for this.

Wait, can you always use the Skystone tank?
I tried, and failed (in 1.18) - don't know what's going on in the latest version.

**Comment by Technici4n** [comment]
No it needs a tank that works as an item. E.g. Mekanism or MI tank.
