### ISSUE TITLE
Why does the mod break, when you disable Channels?

### ISSUE THREAD

**Issue by dsfsdfsd** [AppliedEnergistics/Applied-Energistics-2#783]
Please remove the option to disable channels, my users are annoying me with their request for it

**Comment by FireBall1725** [comment]
lol

**Comment by FireBall1725** [comment]
I agree 100% about removing that option, let me talk with @yueh @Cisien and @thatsIch.  If they are on board then maybe we can do that.

**Comment by shobu9** [comment]
@FireBall1725 i not only agree i think it's a must channels balance out the mod of sorting and etc...M
May get more insults from others but i think it's should really happen.
If you don't like it don't play with it .

**Comment by Craftypiston** [comment]
Yes i think the option should be removed. Most people who complain about it don't know the mod fully and how to work around the "issue". I know since i was one of those people.
