### ISSUE TITLE
Wireless boosters cause server to crash

### ISSUE THREAD

**Issue by kiminga** [AppliedEnergistics/Applied-Energistics-2#7849]
### Describe the bug

After I place a stack of wireless boosters inside an access point and flew like 10 chunks away to try the wireless crafting terminal server died.

### How to reproduce the bug

Wireless server access point then add a stack of wireless boosters. Go 10-15 chunks away and try to use wireless crafting terminal.

### Expected behavior

Wireless crafting terminal to work at long distance.

### Additional details

 I upgraded the server's memory by double. The last server backup before the incident is deleted and I only have a backup from after the incident. Theres no crash log because I accidentally restored a backup of after the incident on apex hosting.

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/kiminga/14b4fdab14cbbf31d97e3620d65414ec

**Comment by mindforger** [comment]
There is no crashlog, only the basic log and neither a hint of a crash in there nor any usefull data aboutvyour setup
