### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by IvanDmitriev1** [AppliedEnergistics/Applied-Energistics-2#7854]
### Describe the bug

`java.lang.NoSuchMethodError: 'float appeng.util.Platform.getRandomFloat()'`

### How to reproduce the bug

Crash happened after few minutes after I crafted wireless terminal

### Expected behavior

This method apparently should exist `appeng.util.Platform.getRandomFloat()`

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Fabric

### Crash log

https://gist.github.com/IvanDmitriev1/7ab3e02173df2bba599d8dabb75e84d5

**Comment by Mari023** [comment]
update ExtendedAE

**Comment by IvanDmitriev1** [comment]
Thanks!
