### ISSUE TITLE
[Bug]: JEI Move Items (+) does not show in AE2 crafting grid (1.20.4 Neoforge)

### ISSUE THREAD

**Issue by MikeHollisJr2021** [AppliedEnergistics/Applied-Energistics-2#7857]
### Describe the bug

1. Open AE2 Crafting Grid
2. Find Item to craft in JEI
3. Look for + button

### How to reproduce the bug

1. Open AE2 Crafting Grid
2. Find Item to craft in JEI
3. Click + button

### Expected behavior

1. Open AE2 Crafting Grid
2. Find Item to craft in JEI
3. The + button is not there.

### Additional details

NOTE: Neoforge is not a selectable modloader, this is on Neoforge, not Forge as indicated by selection choices,

MC: 1.20.4 (Neoforge)
Neoforge: 20.4.223
AE2: 17.13.0-beta (latest version)
JEI: 17.3.0.52 & 17.3.0.49

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

I am unable to force a crash as I am using a chromebook keyboard, I can press F3, but not F3 and another key.

**Comment by MikeHollisJr2021** [comment]
This has also been reported on JEI's issue tracker here https://github.com/mezz/JustEnoughItems/issues/3508

**Comment by Mari023** [comment]
ae2 currently doesn't have a JEI integration. you have to use either REI or EMI.

**Comment by MikeHollisJr2021** [comment]
> ae2 currently doesn't have a JEI integration. you have to use either REI or EMI.

Ahh, I see, what changed, JEI has pretty much been the standard for a while now.

**Comment by mezz** [comment]
If you have issues with AE2 JEI integration, please report them to this new mod project: https://github.com/Tamaized/AE2-JEI-Integration
