### ISSUE TITLE
Any non-full block does not show a texture/shows a pink and black texture if Sodium is installed

### ISSUE THREAD

**Issue by RellinQuill** [AppliedEnergistics/Applied-Energistics-2#7865]
### Describe the bug

In the 1.20.1 version of minecraft the mod (15.2.0 Fabric) any block entity either does not show a texture or shows the pink and black tiles texture

### How to reproduce the bug

Place a wire/facade any other block entity

### Expected behavior

The wires and such should show their correct textures

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Fabric

### Crash log

No crash

**Comment by Mari023** [comment]
install indium

**Comment by MommyHeather** [comment]
![unknown-165.png](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/66441550/7676f6c1-3687-4c98-805b-df874b9feab7)



Sodium breaks the fabric rendering api, which ae2 uses. Indium fixes that api.
