### ISSUE TITLE
Improve searches to mimic JEI

### ISSUE THREAD

**Issue by iammael** [AppliedEnergistics/Applied-Energistics-2#7867]
### Describe the feature

Currently, some searches performed with Applied do not give the same result as JEI.

A picture is worth thousand words:
![2024-05-14_15 42 19](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/7931135/9f92f18a-0f3d-424d-a923-9d5a2aeefbd6)

Here, JEI found that I was looking for the AE² crafting card, but my terminal isn't showing the card (it would appear if I correctly typed "Crafting Card" as is it stored in the network).

As a side note, I thought the _new_ option to switch from AE search system to JEI's would solve that issue but, from what I understand it is only removing AE search bar.

### Reasons why it should be considered

JEI (or even its derivatives) being such a staple, I think it would be good for players that AE search results mimic as much as possible the ones from JEI.

For instance, the possibility of typing just a part of the name of an item (ie: "craf card" or "capa car") or its mod is a good part of JEI search system, allowing to perform quick searches. Because it's not available in AE, I end up needing to search for items twice before I can get them.

### Additional details

A few examples of where JEI would give an output but AE doesn't:

- `@ironf gold` -> Gold Furnace from the Iron Furnaces mod
- `@ae cable` -> Any cables from Applied (even querying with the full mod id "ae2" doesn't return a result because there's no cables starting with the word "cable", only ending with it).
- `@mek ulti uni ca` -> Ultimate Universal Cables from Mekanism
- (...)

**Comment by Mari023** [comment]
ae2s search is pretty simple, it only allows you to choose a search mode by prefixing the search string with a char (as displayed in the tooltip)
it then regex searches all items if they match in the given category (which is  why you can use a pipe `|` to search for multiple strings)

there is however an open PR that would fix this #7311

**Comment by iammael** [comment]
I don't know how I didn't find that issue before opening mine, but yes, this is pretty much the same request.

I'm closing that one then, it's not needed to have both.
