### ISSUE TITLE
Waila on parts

### ISSUE THREAD

**Issue by DrummerMC** [AppliedEnergistics/Applied-Energistics-2#787]
is there any way to add waila support on parts, that are not from ae directly(for example: ExtraCells)?

**Comment by TheJulianJES** [comment]
ExtraCells2 has to add it.

**Comment by DrummerMC** [comment]
But I don't know how I add this on parts

**Comment by TheJulianJES** [comment]
@DrummerMC You probaly could watch at this code ;)

**Comment by DrummerMC** [comment]
I have found a way to add this
