### ISSUE TITLE
Allow force starting of crafting jobs that are missing items

### ISSUE THREAD

**Issue by Burkino** [AppliedEnergistics/Applied-Energistics-2#7876]
### Describe the feature

When starting a craft you should just be able to shift click the grayed out "Start" button. This would just be a way to tell the system "I know I don't have all the required items, but craft what you can now, and just keep the job running because sometime in the future you will get more items."

### Reasons why it should be considered

This would just be a very nice quality of life feature. This would be extremely useful for large crafting jobs, I know the system will eventually get the items it needs, but it could still be doing work while it's waiting for those items.

**Comment by Technici4n** [comment]
This is unfortunately not how the autocrafting system works. It will store items in a separate inventory, which is why it needs the full set to be available when the job is started.
