### ISSUE TITLE
Regex search based view cell

### ISSUE THREAD

**Issue by Entoarox** [AppliedEnergistics/Applied-Energistics-2#788]
A view cell that allows regex search based filtering to be used
Effectively the ability to 'store' any search (as used in terminals) in a view cell instead of specific items.

(As an example, In my magical crops farm I keep using `^(magi|soul$|elem|effe)` to see only the magical crops seeds, without needing to constantly update the view cell whenever a new seed enters the AE system)

**Comment by yueh** [comment]
Most players do not know regex, so it is not a really accessibly for most of them.
Which means they will start copy&paste them, which is highly error-prone.

It would also mean to expose internal data like the ids of each item.
Which is not a goal of AE2.

**Comment by Cisien** [comment]
I do like the idea of being able to specify a text filter, maybe not regex directly, but use the same text filter the terminal already uses. It also supports regex. I font see any need to expose internal data to the client.

**Comment by yueh** [comment]
The terminals are clientside, so they are no issue. It is already possible, like `red|stick` to show redstone and sticks to craft redstone torches.

Everything related to view cells, buses or similar needs to be handled on serverside.
Meaning we cannot filter by the display name as this is not available. One example would be translations. Filter 1 would work for player A but not player B.

The item id is the only valid option to filter, but this would mean filtering by internal data.
Like you need to know that `item.appliedenergistics2.ItemMaterial@0` is a Certus Crystal and `item.appliedenergistics2.ItemMaterial@1` a charged one.

**Comment by Deshiba** [comment]
Well, would not a third filter be the mods installed by the server&client? Hypothetically, being able to add all the items from a mod without actually owning them yet would be a sort of "blacklisting" to what is now "whitelisting".

Asuming that mods have 1 name across all translations so that @mod.[modname] calls would still work.

**Comment by Larandar** [comment]
Not totally related but still on view cell : mod based cells? 
Like thaumcraft view cell, or any major mod, including applied energistic would be a great help
