### ISSUE TITLE
bug when using creative menu

### ISSUE THREAD

**Issue by PhantomAshes** [AppliedEnergistics/Applied-Energistics-2#7881]
### Describe the bug

was using creative menu to grab a night vision potion, typing in n, game froze then crashed, crash log reported an ArrayIndexOutOfBoundsException.

### How to reproduce the bug

be on creative
open mod menu
try and search for night vision potion

### Expected behavior

to get a night vision potion without issue

### Additional details

cant tell what other mod its conflicting with, if any, had to remove AE2 from the modpack

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/t1tjnvpr

**Comment by Mari023** [comment]
remove optifine
