### ISSUE TITLE
40% ae2 usage crazy bad performance

### ISSUE THREAD

**Issue by funnycubeguy** [AppliedEnergistics/Applied-Energistics-2#7884]
### How to reproduce the performance issue

I have a world with 4 of the same bases. If I remove the gregtech layer of these bases ae2 drops down to around 3%.

There are no addons just ae2 from the all the mods 9 pack. I have configured my ae2 config to raise ticks of everything with no luck. There seems to be a bug somewhere. I can reproduce on multiple servers with bases similar to this one

Here is the current config: https://pastes.dev/hp49gcOnCH

Same performance with default config

### Spark profile link

https://spark.lucko.me/hw0W9EgrHO

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

**Comment by Mari023** [comment]
39% of tick time is spend on ae2 iterating over every devices that can tick, without even doing any work (your tick rate settings might are basically equivalent to never tick).
(the other 2% ae2 is taking seems somewhat normal)

do you know roughly how many devices you have in the networks?
