### ISSUE TITLE
AE2 & Starlight Crash when opening Guide Book

### ISSUE THREAD

**Issue by s3ptum** [AppliedEnergistics/Applied-Energistics-2#7888]
### Describe the bug

Client crash while playing modded SMP on home server when opening AE2 guide book. 

Applied Energistics 2 [15.2.1]
Starlight [1.1.2]
Forge [47.2.32]

### How to reproduce the bug

Make guide by charging book then right clicking with book in hand. instant client CTD server still runs smoothly.

### Expected behavior

i assume new gui would appear and show AE2 guide.

### Additional details

Server and client are on same pc 64gb ram AMD 5900x
I am going to attempt to submit same info to Starlight as well.
</head> 
<body> 
	<details> 
		<summary>Mod List</summary> 
		<html><body><ul>
	<li>Pam's HarvestCraft 2 - Crops [1.0.3
] by Love, Cheese and small house plants</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/terrablender">TerraBlender</a> [3.0.1.6
] by Adubbz</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds">YUNG's Better Strongholds</a> [1.20-Forge-4.0.3] by YUNGNICKYOUNG, Acarii</li>
	<li><a href="https://minecraft.curseforge.com/projects/iron-chests">Iron Chests</a> [1.20.1-14.4.4] by cpw, alexbegt, progwml6</li>
	<li><a href="https://teamcofh.com/">Thermal Dynamics</a> [11.0.1] by King Lemming, covers1624</li>
	<li>Obscure API [15] by Obscuria</li>
	<li>Xaero's Minimap [24.1.1] by xaero96</li>
	<li><a href="http://minecraft.curseforge.com/projects/dynamictrees">Dynamic Trees</a> [1.20.1-1.3.0-BETA2
] by Ferreusveritas</li>
	<li><a href="https://github.com/Christofmeg/MekanismCardboardTooltip">Mekanism Cardboard Tooltip</a> [1.4.0] by Christofmeg</li>
	<li>Xaero's World Map [1.38.4] by xaero96</li>
	<li><a href="https://minecraft.curseforge.com/projects/biomes-o-plenty">Biomes O' Plenty</a> [18.0.0.598
] by Forstride, Adubbz</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/serene-seasons">Serene Seasons</a> [9.0.0.46
] by Adubbz, Forstride</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/ram-compat">RAM-Compat</a> [0.1.3] by SSKirillSS</li>
	<li><a href="http://enderio.com/">Ender IO</a> [6.0.25-alpha] by CrazyPants, tterrag, HenryLoenwind, MatthiasM, CyanideX, EpicSquid, Rover656, HypherionSA, agnor99, Ferri_Arnus, mystchonky</li>
	<li><a href="https://www.teamabnormals.com/mods/upgrade-aquatic">Upgrade Aquatic</a> [6.0.0
] by Team Abnormals</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/forgeendertech">ForgeEndertech</a> [11.1.3.1] by EnderLanky</li>
	<li><a href="https://aidancbrady.com/mekanism/">Mekanism: Tools</a> [10.4.6] by Aidancbrady, Thommy101, Thiakil, pupnewfster, dizzyd</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples">YUNG's Better Desert Temples</a> [1.20-Forge-3.0.3] by YUNGNICKYOUNG, Tera</li>
	<li>ChemLib [2.0.19] by DarkArcana</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/advanced-hook-launchers">Advanced Hook Launchers</a> [10.1.1.0] by EnderLanky</li>
	<li><a href="http://geckolib.com/">GeckoLib 4</a> [4.4.4] by Gecko, Eliot, AzureDoom, DerToaster, Tslat, Witixin</li>
	<li><a href="https://aidancbrady.com/mekanism/">Mekanism</a> [10.4.6] by Aidancbrady, Thommy101, Thiakil, pupnewfster, dizzyd</li>
	<li>recipeessentials mod [1.20.1-3.4
] by Someaddon</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/sophisticated-core">Sophisticated Core</a> [0.6.22.611] by P3pp3rF1y</li>
	<li><a href="https://tschipcraft.ddns.net/dynamiclights.html">Dynamic Lights</a> [1.8.2+mod] by Tschipcraft</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/ender-storage-1-8">EnderStorage</a> [2.11.0.188] by ChickenBones, covers1624</li>
	<li>FTB Teams [2001.3.0] by FTB Team</li>
	<li>JRFTL [1.6.0
]</li>
	<li><a href="https://www.curseforge.com/projects/60089">Mouse Tweaks</a> [2.25.1
] by Ivan Molodetskikh (YaLTeR)</li>
	<li>AE2WTLib [15.2.3-forge] by mari_023, Ridanisaurus, DomamaN202</li>
	<li>Resourcefulconfig [2.1.2]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/serene-seasons-pams-harvestcraft-2-crops-compat">Serene Seasons - Pam's HarvestCraft 2 - Crops Compat</a> [1.20.1-1.0.0
] by Darkorg</li>
	<li><a href="https://github.com/vectorwing/FarmersDelight">Farmer's Delight</a> [1.20.1-1.2.4] by vectorwing</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/ImmersiveArmors">Immersive Armors</a> [1.6.1+1.20.1] by Luke100000</li>
	<li><a href="https://www.curseforge.com/projects/351264">Kotlin for Forge</a> [4983659]</li>
	<li>Pam's HarvestCraft 2 - Food Core [1.0.5
] by Pamela Collins, ie MatrexsVigil, PamHarvestCraft</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/starlight-forge">Starlight</a> [1.1.2+forge.1cda73c] by Spottedleaf</li>
	<li>Alex's Delight [1.5] by NCP Bails</li>
	<li><a href="https://modrinth.com/mod/geophilic-reforged">Geophilic Reforged</a> [1.2.0] by bebebea_loste</li>
	<li><a href="https://minecraft.curseforge.com/projects/jade">Jade</a> [11.9.2+forge
] by Snownee</li>
	<li><a href="https://github.com/Umpaz/NethersDelight">Nether's Delight</a> [1.20.1-4.0] by Umpaz, SoyTutta</li>
	<li><a href="https://serilum.com/mod/tree-harvester">Tree Harvester</a> [8.7] by Rick South</li>
	<li><a href="https://teamcofh.com/">CoFH Core</a> [11.0.2] by King Lemming, Zeldo Kavira, covers1624, skyboy, Cynycal, Drullkus</li>
	<li><a href="https://www.teamabnormals.com/mods/boatload">Boatload</a> [5.0.1
] by Team Abnormals</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/rechiseled">Fusion</a> [1.1.1] by SuperMartijn642</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/silent-gear">Silent Gear</a> [3.6.3
] by SilentChaos512</li>
	<li><a href="https://teamcofh.com/">Thermal Expansion</a> [11.0.1] by King Lemming</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise">When Dungeons Arise</a> [2.1.58-1.20.x] by Aurelj, DiamondTown and Zephyrusj</li>
	<li>OctoLib [0.3] by SSKirillSS</li>
	<li>Resourceful Lib [2.1.25] by ThatGravyBoat, Epic_Oreo</li>
	<li><a href="https://infernalstudios.org/">Enemy Expansion</a> [2.3.1] by nekomaster1000</li>
	<li>Patchouli [1.20.1-84-FORGE
] by Vazkii</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/alexs-mobs">Alex's Mobs</a> [1.22.8] by Alexthe668, Carro1001, Paint_Ninja</li>
	<li><a href="https://www.curseforge.com/projects/531761">Balm</a> [7.2.2] by BlayTheNinth</li>
	<li>Twilight's Flavor &amp; Delight [2.0.11
] by lcy0x1 and Goulixiaoji</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/yungs-better-jungle-temples">YUNG's Better Jungle Temples</a> [1.20-Forge-2.0.5] by YUNGNICKYOUNG, Tera</li>
	<li><a href="https://teamcofh.com/">Thermal Locomotion</a> [11.0.1] by King Lemming</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/silent-lib">Silent Lib</a> [8.0.0
] by SilentChaos512</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/cloth-config-forge/">Cloth Config v10 API</a> [11.1.118] by shedaniel</li>
	<li><a href="https://www.curseforge.com/projects/679177">libIPN</a> [4.0.2] by blackd/mirinimi</li>
	<li><a href="https://github.com/MattCzyr/NaturesCompass">Nature's Compass</a> [1.20.1-1.11.2-forge] by ChaosTheDude</li>
	<li>Architectury [9.2.14] by shedaniel</li>
	<li><a href="https://curseforge.com/members/elocindev/projects">Shield Overhaul</a> [1.0.3] by ElocinDev</li>
	<li>Connectivity Mod [1.20.1-5.5
] by Someaddons</li>
	<li>Titanium [3.8.28
] by TheCodedOne, Buuz135</li>
	<li><a href="https://curseforge.com/minecraft/mc-mods/just-enough-mekanism-multiblocks">Just Enough Mekanism Multiblocks</a> [4.2] by gisellevonbingen</li>
	<li><a href="https://teamcofh.com/">Thermal Foundation</a> [11.0.4] by King Lemming</li>
	<li><a href="https://aidancbrady.com/mekanism/">Mekanism: Additions</a> [10.4.6] by Aidancbrady, Thommy101, Thiakil, pupnewfster, dizzyd</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/chunk-loaders">Chunk Loaders</a> [1.2.8a] by SuperMartijn642</li>
	<li>Aquamirae [6.API15] by Obscuria, Pluvia</li>
	<li>FTB Ultimine [2001.1.5] by FTB Team</li>
	<li>Mekanism: Weapons [1.5] by oMeranha</li>
	<li><a href="https://github.com/ZsoltMolnarrr/BetterCombat">Better Combat</a> [1.8.5+1.20.1] by Daedelus</li>
	<li><a href="https://github.com/Fuzss/puzzleslib">Puzzles Lib</a> [8.1.20] by Fuzs</li>
	<li><a href="https://github.com/Alex-the-666/Citadel">Citadel</a> [2.5.4] by Alexthe666</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer">Just Enough Resources</a> [1.4.0.247] by way2muchnoise</li>
	<li><a href="https://mcreator.net">Silence's Turrets</a> [2.3.4] by ASUS, MCreator</li>
	<li>FTB Chunks [2001.3.0] by FTB Team</li>
	<li>Cupboard utilities [1.20.1-2.6
] by Someaddon</li>
	<li>Player Animator [1.0.2-rc1+1.20] by KosmX</li>
	<li>Miner's Delight [1.20.1-1.2.3
] by Sammy;</li>
	<li>HopoBetterRuinedPortals [1.3.7] by Hoponopono</li>
	<li>Just Enough Effects Descriptions [1.20-2.1.12] by MehVahdJukaar</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/canary">Canary</a> [0.3.3] by AbdElAziz</li>
	<li>FTB Ranks [2001.1.3] by FTB Team</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/delightful">Delightful</a> [3.5.5
] by brnbrd</li>
	<li><a href="https://mcreator.net">Alex's Caves: Stuff &amp; Torpedoes</a> [1.0.2] by Furti_Two</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/immersive-aircraft">Immersive Aircraft</a> [1.0.1+1.20.1] by Luke100000</li>
	<li>Lightman's Discord Integration [1.20-0.2.0.3] by Lightman314</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/clear-water">Clear Water</a> [2.1] by ExpensiveKoala, AlexNijjar</li>
	<li><a href="https://github.com/AppliedEnergistics/Applied-Mekanistics#readme">Applied Mekanistics</a> [1.4.2] by ramidzkh</li>
	<li><a href="http://www.curseforge.com/members/melanx/">Just Enough Advancements</a> [1.20.1-5.0.1] by MelanX, noeppi_noeppi</li>
	<li><a href="https://www.curseforge.com/projects/223794">Applied Energistics 2</a> [15.2.1] by TeamAppliedEnergistics</li>
	<li><a href="https://tweaked.cc">CC: Tweaked</a> [1.110.3] by Daniel Ratcliffe, Aaron Mills, SquidDev</li>
	<li>RPG-HUD [3.10] by Raelzaryn</li>
	<li><a href="https://www.teamabnormals.com/mods/blueprint">Blueprint</a> [7.1.0] by Team Abnormals</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks">Iron's Spells 'n Spellbooks</a> [1.20.1-3.1.6] by Iron431, Lab3</li>
	<li><a href="https://manaandartifice.com/">Mana and Artifice</a> [3.0.0.14] by Mithion</li>
	<li><a href="https://sites.google.com/view/subnautica-flow-libary/startseite">Subnautica Flow</a> [1.2.2] by Pyro</li>
	<li>Sculk Horde [1.20.1-0.9.2] by Team Peril</li>
	<li>Just Enough Archaeology [1.20.1-1.0.4] by LobsterJonn</li>
	<li>Alchemistry [2.3.4] by DarkArcana</li>
	<li>Industrial Foregoing [3.5.17
] by Buuz135</li>
	<li><a href="https://www.stardustlabs.net/">Incendium</a> [5.3.5] by Stardust Labs</li>
	<li><a href="https://aidancbrady.com/mekanism/">Mekanism: Generators</a> [10.4.6] by Aidancbrady, Thommy101, Thiakil, pupnewfster, dizzyd</li>
	<li><a href="https://mrcrayfish.com/mods?id=framework">Framework</a> [0.6.27] by MrCrayfish</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/more-mekanism-processing">More Mekanism Processing</a> [4.0] by gisellevonbingen</li>
	<li><a href="https://github.com/Towdium/JustEnoughCalculation">Just Enough Calculation</a> [4.0.4] by Towdium, MorningSage, 6LeoY</li>
	<li><a href="https://discord.gg/CZQthZJjPc">HopoBetterUnderwaterRuins</a> [1.1.4] by Hoponopono</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/curios">Curios API</a> [5.9.1+1.20.1
] by C4</li>
	<li><a href="https://www.curseforge.com/projects/233071">CraftingTweaks</a> [18.2.3] by BlayTheNinth</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/silents-gems">Silent's Gems: Base</a> [4.7.0
] by SilentChaos512</li>
	<li><a href="https://github.com/Fuzss/cutthrough">Cut Through</a> [8.0.2] by Fuzs</li>
	<li>Pam's HarvestCraft 2 - Trees [1.0.2
] by Love, Cheese and small house plants</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons">YUNG's Better Dungeons</a> [1.20-Forge-4.0.4] by YUNGNICKYOUNG, Acarii</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib">SuperMartijn642's Core Lib</a> [1.1.17] by SuperMartijn642</li>
	<li><a href="https://github.com/Fuzss/mindfuldarkness">Mindful Darkness</a> [8.0.3] by Fuzs</li>
	<li><a href="https://teamcofh.com/">Thermal Innovation</a> [11.0.1] by King Lemming</li>
	<li>Ocean's Delight [1.0.2-1.20
] by Scouter456</li>
	<li><a href="https://discord.gg/CZQthZJjPc">HopoBetterMineshaft</a> [1.2.2] by Hoponopono</li>
	<li><a href="https://mrcrayfish.com/mods?id=cfm">MrCrayfish's Furniture Mod</a> [7.0.0-pre36] by MrCrayfish</li>
	<li><a href="https://moddinglegacy.com/">Scuba Gear</a> [1.0.6
] by KingPhygieBoo, MCVinnyQ</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge">YUNG's Better Mineshafts</a> [1.20-Forge-4.0.4] by YUNGNICKYOUNG</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks">Sophisticated Backpacks</a> [3.20.5.1044] by P3pp3rF1y, Ridanisaurus</li>
	<li><a href="https://modrinth.com/mod/botarium">Botarium</a> [2.3.3] by CodexAdrian</li>
	<li><a href="https://discord.gg/U8DvBAW">SecurityCraft</a> [1.9.9
] by Geforce132, bl4ckscor3, Redstone_Dubstep</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/better-advancements">Better Advancements</a> [0.3.2.162] by way2muchnoise</li>
	<li>Automobility [0.4.2+1.20.1-forge] by FoundationGames</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/rac-compat">RAC-Compat</a> [0.1.2.1] by SSKirillSS</li>
	<li>clientcrafting mod [1.20.1-1.8
] by Someaddon</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/just-enough-professions-jep">Just Enough Professions (JEP)</a> [3.0.1
] by Mrbysco, ShyNieke</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/libx">LibX</a> [1.20.1-5.0.14] by ModdingX</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/more-red-x-cc-tweaked-compat">More Red x CC:Tweaked Compat</a> [1.20.1-1.0.0] by YuRaNnNzZZ</li>
	<li><a href="https://modrinth.com/mod/ad-astra">Ad Astra</a> [1.15.18] by Alex Nijjar</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest">The Twilight Forest</a> [4.3.2145
] by Benimatic, AtomicBlom, Drullkus, Killer_Demon, quadraxis, Tamaized, williewillus, Andromander, GizmoTheMoonPig, jodlodi</li>
	<li><a href="https://blakesmods.com/mystical-agriculture">Mystical Agriculture</a> [7.0.11
] by BlakeBr0</li>
	<li>FTB Library [2001.2.2] by FTB Team</li>
	<li><a href="https://teamcofh.com/">Redstone Arsenal</a> [8.0.1] by King Lemming, Hekera</li>
	<li>Pam's HarvestCraft 2 - Food Extended [1.0.1
] by Love, Cheese and small house plants</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/yungs-better-ocean-monuments">YUNG's Better Ocean Monuments</a> [1.20-Forge-3.0.4] by YUNGNICKYOUNG, Tera</li>
	<li>Railcraft Reborn [1.1.1] by Sm0keySa1m0n, Edivad99</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/yungs-better-witch-huts">YUNG's Better Witch Huts</a> [1.20-Forge-3.0.3] by YUNGNICKYOUNG, Acarii</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/yungs-better-end-island">YUNG's Better End Island</a> [1.20-Forge-2.0.6] by YUNGNICKYOUNG, Acarii</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/additional-structures">Additional Structures</a> [4.2.1] by XxRexRaptorxX (RexRaptor)</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/yungs-better-nether-fortresses">YUNG's Better Nether Fortresses</a> [1.20-Forge-2.0.6] by YUNGNICKYOUNG, Acarii</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/relics-mod">Relics</a> [0.6.5.1] by SSKirillSS</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/gottschcore">GottschCore</a> [2.1.0] by gottsch</li>
	<li><a href="https://mrcrayfish.com/">MrCrayfish's Gun Mod</a> [1.4.17
] by MrCrayfish</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/just-enough-beacons-reforged">Just Enough Beacons</a> [1.2.0] by CerbonXD</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/yungs-api">YUNG's API</a> [1.20-Forge-4.0.5] by YUNGNICKYOUNG</li>
	<li><a href="https://github.com/Christofmeg/JustEnoughBreeding">Just Enough Breeding</a> [1.2.1
] by Christofmeg</li>
	<li><a href="https://www.curseforge.com/projects/495267">Inventory Profiles Next</a> [1.10.10] by blackd/mirinimi</li>
	<li><a href="https://docs.intelligence-modding.de/">Advanced Peripherals</a> [0.7.39r] by Srendi</li>
	<li><a href="https://teamcofh.com/">Thermal Cultivation</a> [11.0.1] by King Lemming</li>
	<li><a href="https://blakesmods.com/cucumber">Cucumber Library</a> [7.0.8
] by BlakeBr0</li>
	<li>Chefs Delight [1.0.3-forge-1.20.1
] by Redstone Games</li>
	<li>FTB Essentials [2001.2.2] by FTB Team</li>
	<li>AlchemyLib [1.0.30] by DarkArcana</li>
	<li><a href="https://modrinth.com/mod/enderman-overhaul">Enderman Overhaul</a> [1.0.4] by Alex Nijjar, Joosh</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/codechicken-lib-1-8">CodeChicken Lib</a> [4.4.0.509] by ChickenBones, covers1624</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/jei">Just Enough Items</a> [15.3.0.4] by mezz</li>
	<li><a href="https://minecraft.curseforge.com/projects/aquaculture">Aquaculture 2</a> [2.5.1] by Shadowclaimer, Girafi</li>
	<li><a href="https://enginehub.org/worldedit/">WorldEdit</a> [7.2.15+6463-5ca4dff] by EngineHub</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/cerbons-api">Cerbons API</a> [1.1.0] by CerbonXD</li>
	<li><a href="https://modrinth.com/datapack/explorify">Explorify</a> [1.4.0] by bebebea_loste</li>
	<li>Alex's Caves [1.1.4] by Alexthe668, Noonyeyz</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/chococraft">Chococraft 4</a> [0.9.11] by Mrbysco, Xalcon, Slayer5934, balika011</li>
	<li><a href="https://github.com/squeek502/AppleSkin">AppleSkin</a> [2.5.1+mc1.20.1
] by squeek</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/advanced-mining-dimension">Advanced Mining Dimension</a> [1.20.1-1.1.0] by Max Henkel</li>
	<li>Ender's Delight [1.0.3] by Axedgaming</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib">SuperMartijn642's Config Library</a> [1.1.8] by SuperMartijn642</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/more-red">More Red</a> [4.0.0.4
] by Commoble</li>
	<li><a href="https://github.com/TheIllusiveC4/Caelus">Caelus API</a> [3.2.0+1.20.1] by C4</li>
	<li>Lightman's Currency [1.20.1-2.2.1.3b] by Lightman314</li>
	<li><a href="https://mods.twelveiterations.com/mc/kleeslabs">KleeSlabs</a> [15.0.0] by BlayTheNinth</li>
	<li><a href="https://modrinth.com/mod/mekanism-ad-astra-ores">Mekanism: Ad Astra Ores</a> [0.3.0] by liberty</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/ad-astra-giselle-addon">Ad Astra: Giselle Addon</a> [6.7] by gisellevonbingen</li>
	<li><a href="https://serilum.com/mod/collective">Collective</a> [7.60] by Rick South</li>
	<li><a href="https://mrcrayfish.com/mods/goblintraders">Goblin Traders</a> [1.9.3] by MrCrayfish</li>
	<li><a href="https://www.curseforge.com/projects/941096">Polymorphic Energistics</a> [0.1.1-1.20.1] by 90</li>
	<li><a href="https://www.curseforge.com/projects/388800">Polymorph</a> [0.49.5+1.20.1] by Illusive Soulworks</li>
</ul></body></html> 
	</details>		 
</body> 
</html> 

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/h96LCPsD

**Comment by s3ptum** [comment]
I just took a vist to starlight github and its been locked and is read only. Ill probably just remove that mod. IDK why i even use most "performance" mods any way.
[https://github.com/PaperMC/Starlight/issues](url)

**Comment by Mari023** [comment]
you don't need starlight anymore, since the vanilla light engine got improved and now performs similar to starlight

**Comment by s3ptum** [comment]
Thanks i just removed it and guide opens fine!
