### ISSUE TITLE
Pattern becoming invalid 

### ISSUE THREAD

**Issue by kevinkk525** [AppliedEnergistics/Applied-Energistics-2#789]
I recently was wondering why I always get some inavlid pattern in my interfaces although they did work well before.
For a few weeks I thought it was because of a change in mods which would be reasonable as I updated some and removed others.
But today I recognized this (and I did not change any mod):
As soon as I put new pattern in my interfaces and reopen it/wait a bit (not completely tested) then I get an invalid pattern somewhere.
To me it looks as if I hit some kind of pattern maximum. Is that possible?

I'm running on rv1-stable.

**Comment by kevinkk525** [comment]
I could not reproduce this error today... strange, the days before I always had it. So for the moment just ignore that. I will use the beta anyways.
But is there a theoretical limit to pattern? I have around 600 in interfaces and the same amount in chests as backup.

**Comment by Cisien** [comment]
There is no max that I have seen in the code. I would love to see some screen shots of such a large build!

**Comment by kevinkk525** [comment]
Maybe not in the code but in the data type. like integer can only hold a certain value (like the extracell addon not showing more than 2MegaBuckets in the interface). Although there shouldn't be any issue like that and I could not reproduce it. Probably it took some time after deleting some mods until the ME system found all broken recipes...
Here are some pictures of the build: https://secure2web.de/owncloud/public.php?service=files&t=e8c45664885d1c73adf405c84df97003

**Comment by yueh** [comment]
Patterns become invalid the moment there is no defined recipe available for the defined crafting grid.
And this should happen when a pattern is loaded.

Are you accessing the patterns directly with OpenComputers? (or maybe it is implicitly done by OC)
This could cause some issues.

**Comment by kevinkk525** [comment]
Ok so they should have been invalid all at once on the first server restart after removing a mod.

Yes I am accessing the ME_controller directly with OC and pulling the item_list about every tick. Until now no pattern became invalid.
I also requested some craftings and pulled the crafting list with OC. Did not harm anything.

**Comment by yueh** [comment]
Not necessarily at server start, but certainly with the chunkload.
I honestly have no idea if dynamic recipes are possible (changing them at runtime), but that would cause patterns getting invalid on a chunk unload and load.

Not sure about pulling the ItemList each tick (in terms of performance)
There are better ways to do it, but they might not be available (or possible) in OC.

**Comment by kevinkk525** [comment]
I do not know a method that is less resource intensive. But acutally pulling the item_list is not a problem. Pulling the craftables_list however is a bit resource intensive and takes some ticks. So this shouldn't be done often. But with none of these I had any problem.
My 3 chunks are all loaded with cunkloaders so that should have happened immediately to all pattern.. Actually I only did remove Mekanism. Well as I can not reproduce it it probably was "nothing" or something really weird. We'll see.
