### ISSUE TITLE
Lock Configured ME Interface Slot to Configured Item - MC 1.20.1

### ISSUE THREAD

**Issue by MRuth** [AppliedEnergistics/Applied-Energistics-2#7895]
### Describe the feature

I found a similar reported issue under [Make ME interface slots with a configured item request locked to only the item #7695](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/7695), which was marked as closed with a fix merged ([#7752](https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/7752)), however that fix appears to be for MC 1.20.6.

Is there any chance of getting this feature / fix added to the 1.20.1 branch?

### Reasons why it should be considered

Similar in nature to what was provided in original issue, though in my testing the setup was to use an external interface to provide certain materials to an external automation, while still accepting returned items.

The returned items would be coming in at a rate fast enough where if the item to be stocked through the interface were depleted and therefore could not be filled, the slot would be open to the incoming items, which could potentially deadlock the system if the configured item was not able to be provided once available.

**Comment by Technici4n** [comment]
We're not going to change it in 1.20.1 cause it might break some setups. Wait for 1.21 ;)
