### ISSUE TITLE
Auto add a new rotor for kinetic windmill

### ISSUE THREAD

**Issue by LarsBorris** [AppliedEnergistics/Applied-Energistics-2#790]
Hello,

First: Awesome mod!
Second: No really! it IS awesome
Third: I have a suggestion!!

I wanted to use Kinetic Windmills from IC2 to produce all my EU power.
However I do not want to manually insert a new rotor when the old one is busted.

In creative mode, I have tried using the ME system to automatically (Fuzzy Export Bus!) add a rotor to a kinetic windmill.
It does add the rotor and it doesn't. Let me explain.
When you look at the windmill after the ME system added the rotor, you can see the block slowly rotating on the front of the windmill, but it doesn't "extend" to the real normal size.
If I open the GUI of the windmill the rotor is in its place and without doing anything else the rotor extends, becoming the real size and starts to operate (note: I only opened the GUI, didn't click anything else)

Recap:
The ME system is able to add the rotor but it doesn't work inside the windmill.
Opening the GUI (and nothing else) makes it work.

Can this be solved in any way?
Would be nice to have a bunch of windmills that automatically adds a new rotor when the old one is busted.

Thank you!
First post, be nice :)

**Comment by Deshiba** [comment]
Sounds to me like it is more of an issue with IC2 then AE2. Mainly because of you saying it functions normal when you "open the GUI". Does the same issue with the rotor-blades happen when you insert them with hoppers?

**Comment by LarsBorris** [comment]
I haven't tried hoppers yet.
Will test that when I get home from work :)
Thank you.

**Comment by yueh** [comment]
Is this even AE2 related? As there are no fuzzy export buses.

**Comment by Cisien** [comment]
The wind mill in the form that can accept replaceable rotors is new to 1.7, so it must be.

I'm guessing he is using an export bus with a fuzzy card.

I don't know why fuzzy is needed, unless he is trying to insert rotors with varrying damage

**Comment by TheJulianJES** [comment]
@LarsBorris What mc version are you using?
