### ISSUE TITLE
Disabling channels breaks other mods.

### ISSUE THREAD

**Issue by pabluuz** [AppliedEnergistics/Applied-Energistics-2#791]
I'm not quite sure if it's Your fault, but I thought that it would be nice to notify You.

Reproduce: Install newest remoteIO mod and newest AE, than disable channels.

All logs: www.pabluuz.pl/me

Hope that helps somehow. Good job with this mod!

**Comment by OscarBarrett** [comment]
It's apparently a problem on the RemoteIO side. https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/719#issuecomment-69478980

I doesn't look like anyone has reported the issue to RemoteIO yet.

**Comment by Cisien** [comment]
This needs to be reported to Remote IO. As stated in 719, we actually remove items from the game when the features they provide are disabled. Other mods need to be able to adapt to this.
