### ISSUE TITLE
Make AE Spatial function compatible for Mekanism conduits

### ISSUE THREAD

**Issue by Uptobillion** [AppliedEnergistics/Applied-Energistics-2#7911]
### Describe the bug

Some types of mek conduit will not be saved to AE Spatial dimension

### How to reproduce the bug

  1. Save these items to AE space(see pic)
![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/28522459/fcf778d7-56f5-4fde-b688-15009237b537)

2. Only item conduits, thermodynamic conduits and machine will be saved to spatial space
![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/28522459/aca86f33-6fe2-423d-98fd-de49ebdfce18)

### Expected behavior

All types of conduits will be saved to ae space

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

no crash log

**Comment by Mari023** [comment]
iirc spatial storage is opt out now, so if it doesn't work with some mekanism cables, that means that 
1. Mekanism would have to fix that
2. it probably doesn't work for a reason, which could e.g. be 
- It would crash
- It would produce an undesired side effect e.g. in case of mekanism releasing a lot of radiation could be such a side effect
- game play reasons / balancing reasons

while it is possible for a modpack author to allow it anyways by removing the blocks from the tag, doing so is is strongly discouraged for the above reason

**Comment by Technici4n** [comment]
Yeah, moving these cables is not safe. Nothing to do on our end I'm afraid.
