### ISSUE TITLE
Guidebook Crash: Inscriber

### ISSUE THREAD

**Issue by MynxOne** [AppliedEnergistics/Applied-Energistics-2#7912]
### Describe the bug

Using the guidebook hotkey over an inscriber (G) causes a crash immediately with error code -1.

### How to reproduce the bug

Simply using the guidebook hotkey in this modded environment.

### Expected behavior

A CTD of code -1.

### Additional details

Suspected 'Starlight' mod. Will try removing and testing further.

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/nzPkSGus

**Comment by MynxOne** [comment]
After further testing, AE2 is incompatible with 'Starlight' in this modded instance.

**Comment by 62832** [comment]
Just remove it, then.

**Comment by MynxOne** [comment]
Then I will reference this thread on their github to ensure the incompatibility is known. Thank you for your response.

**Comment by Mari023** [comment]
@MynxOne  they know, and it is fixed in newer versions
