### ISSUE TITLE
Error Ticking GridNode

### ISSUE THREAD

**Issue by dunkfordyce** [AppliedEnergistics/Applied-Energistics-2#792]
Im getting this as soon as my world starts: http://pastebin.com/1juRUi2j

World download for DW20 FTB pack ( I did try rv2-7 in the pack but I get the same error ) https://www.dropbox.com/s/pt9wre3fifa0u11/Backup-NW2-2015-1-20--20-14.zip?dl=0

**Comment by yueh** [comment]
Mostly communicated via IRC. No indication what causes the issue.

**Comment by AlgorithmX2** [comment]
Seems like the pattern some how got corrupted? finalOutput - is null? How that happened is a mystery however.

**Comment by yueh** [comment]
It can happen if the current task is serialized, saved to disk and minecraft then closed. After that disable one of the items in the crafting chain, start minecraft again and load the map = crash.
I am tempted to just call `cancel()` to the `readFromNbt()` if it the item went missing. I would expect that some items might be lost, but honestly with disabled items you already have some lost and probably other issues.

But this is not the case with this issue.
