### ISSUE TITLE
Networks not updating item amounts recieved/removed from sub-networks

### ISSUE THREAD

**Issue by Kitheyn** [AppliedEnergistics/Applied-Energistics-2#794]
Using RR3, v 3.2.2.1 with AE2-rv2-BETA-5.
Inputting items into a storage network from a crafting network does not update the storage network.

To clarify:
I have an ME Chest as storage with one 1k drive. This is on the blue network.
The same ME Chest is connected to a crafting network via storage bus. This is the white sub-network.
The white network successfully crafts logic processors and puts them into the ME Chest. I thought both networks would show the correct number. However, a crafting/access terminal on the blue network does not see the new items, even if they're on the same 1k storage drive.

The white network shows the correct amount, as well as directly accessing the ME Chest itself. Using the blue network/Chest to remove and replace the same type of item updates the amount to the correct number.  It's also possible to use the white network to take out all of one type of item.  The blue network will still show them, but the 'ghost' items can't be removed.

**Comment by yueh** [comment]
I cannot reproduce it in a simple setup with a ME Chest in one network and a storage bus and terminal on another one.

Are you using a security terminal by any chance?

**Comment by Cisien** [comment]
Also, can you post a screen shot of the network?

**Comment by Kitheyn** [comment]
Network setup.  White storage bus is beneath ME Chest. White network in the back is not attached to the white network near inscriber setup.  Green network is connected by glass cable, and p2p'd through a blue line. I'm not using a security terminal.  I had a Pneumatic Craft security station nearby that I'd dismantled, thinking it was the cause.

![2015-01-25_04 57 24](https://cloud.githubusercontent.com/assets/10646924/5891084/b26cb1b0-a44e-11e4-93b1-4a0c73d52b20.png)

Storage as shown by ME chest.  Blue network terminal shows same.

![2015-01-25_04 52 40](https://cloud.githubusercontent.com/assets/10646924/5891086/cadb7eb6-a44e-11e4-8905-54f69b215db4.png)

Crafting works as expected.
![2015-01-25_04 54 58](https://cloud.githubusercontent.com/assets/10646924/5891092/2b66a454-a44f-11e4-88c0-47251d6d6ea3.png)

Can be seen through the white network.
![2015-01-25_04 55 27](https://cloud.githubusercontent.com/assets/10646924/5891093/370ec7a0-a44f-11e4-8fae-9df60ec3043a.png)

Blue network shows no new items.
![2015-01-25_04 55 32](https://cloud.githubusercontent.com/assets/10646924/5891094/43d81220-a44f-11e4-8f28-23514dee7c00.png)

**Comment by Kitheyn** [comment]
Also, the crafted items are being imported by pumping it into an ME Interface Block via Ender IO item conduits.  Using the terminals to manually add/remove items works as expected.

**Comment by yueh** [comment]
These screenshot do not contain any proof, that the output is stored somewhere the blue network can access.

**Comment by Cisien** [comment]
Hmm also, I don't think the me chest can ever have items extracted from it with pipes or storage busses
