### ISSUE TITLE
ME system disconnecting

### ISSUE THREAD

**Issue by alundai159** [AppliedEnergistics/Applied-Energistics-2#795]
i have a large ME system that is in multiple chunks, now sometimes everything in 1 chunk just disconnects. all the cables and blocks are there but they just don't connect and everything is offlne. is this a known issue? is there something i can do about this, exept breaking and replacing every block? 
here is a picture of part of the system. http://imgur.com/fQslxLl

**Comment by Cisien** [comment]
This may be a symptom that the chunk is corrupt in some form

**Comment by Kazzamkablam** [comment]
you forgot to mention it's happening on forsaken.co server and not only case.

**Comment by alundai159** [comment]
yeah its happening on forsaken and i'm not the only one its happening to. is it also happening on other servers or is this possible something serverside?

**Comment by yueh** [comment]
Based on their P2W shop I would expect that they are using something like mcpc, bukkit, cauldron, etc.
This can cause unpredictable  sideffects with other mods, why it is the reason we do not support it.

**Comment by Kazzamkablam** [comment]
Appears it's also happening with FTB Infinity.

**Comment by Bestadd** [comment]
@kazzamkablam FTB infinity on forsaken.co?  If so this gives support to @yueh comment that's it's something server side causing this because I have been running a private FTB infinity server for about 20 of my friends and we all have huge AE networks and no one has had this problem.

**Comment by thatsIch** [comment]
Closing this for now
