### ISSUE TITLE
Crash when I press G

### ISSUE THREAD

**Issue by ShamHyper** [AppliedEnergistics/Applied-Energistics-2#7958]
### Describe the bug

When I hold down the G key to explore an item, minecraft crashes.

### How to reproduce the bug

I can't run minecraft on my modpack, I don't understand reading crash logs, and I can't figure out what the conflict is

### Expected behavior

It was expected that the "inspection" menu of the item would open

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/gFCXeMp9

**Comment by Mari023** [comment]
remove starlight.

**Comment by ShamHyper** [comment]
Can't

**Comment by ShamHyper** [comment]
Unless you can tell me an alternative for starlight

**Comment by Mari023** [comment]
you don't need it since 1.20

**Comment by ShamHyper** [comment]
Okay, I'll try without it, thanks.
