### ISSUE TITLE
Ae2 wrenching is different then any other cable Big issue.

### ISSUE THREAD

**Issue by Flukethoughts** [AppliedEnergistics/Applied-Energistics-2#796]
But ae2rv-1 security terminal doesn't prevent users from changing anything. I'm not sure if I understand what it is supposed to do but so far i can block the wrench on every other cable other then ae2. This is using grief prevention and a modified config for 1.7.10 I can block every other cable being touched by the wrench just not any ae2 cables.

**Comment by Flukethoughts** [comment]
Just want to restate this I can prevent every other cable in the game from being wrenched with grief prevention but I can't prevent anything that is ae2. Ae2 is the only cable that can be wrenched out of place. So I don't want to tell players to use enderio instead but it seems like it might be the only solution for this

**Comment by yueh** [comment]
Security terminals only provide a network level protection like access to the GUIs.
Not a physical protection preventing blocks from being destroyed.

Otherwise duplicate of #645

**Comment by Flukethoughts** [comment]
okay but it's not a duplicate i also noted the fact that every other cable is protected from interaction besides ae2 why is this and how would i fix it. 

endio doesn't have this problem
Mek doesn't have this problem
and a few others don't have this problem but for some reason all ae cables ignore permissions

Please explain.
