### ISSUE TITLE
Player inventory in Export Bus is Misaligned

### ISSUE THREAD

**Issue by shartte** [AppliedEnergistics/Applied-Energistics-2#7963]
![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/1261399/3dda00e1-6e1f-4935-b34b-ef3969e76d40)

**Comment by Mithi83** [comment]
I‘m currently out of town and not near any development setup, but a bit of digging around in the source showed some inconsistencies that could be relevant here:

src/main/resources/assets/ae2/screens/io_bus.json uses
```
  "background": {
    "texture": "guis/storagebus.png",
    "srcRect": [0, 0, 176, 251]
  },
```

As opposed to storage_bus.json itself which has
```
  "background": {
    "texture": "guis/storagebus.png",
    "srcRect": [0, 0, 176, 253]
  },
```

Notice the difference by 2 in the last number. My guess would be to a) verify that storagebus GUI is ok and b) copy over the number from storagebus.json would fix the problem. Bonus points for anyone willing to search for storagebus.png in other jsons and see if any other places are inconsistent.
I‘d do it myself, but that‘ll have to wait till next week.

**Comment by Mithi83** [comment]
formation_plane.json (251), storage_bus.json (253), io_bus.json (251). Git blame shows that storage_bus.json was updated during Rid’s retexturing, the other two were not and must be changed to 253 as well. Tested on an old laptop which took ages to set up the repo. I can‘t prepare a PR from abroad though.
