### ISSUE TITLE
Wrenches Do Not Exist in The Creative Menu

### ISSUE THREAD

**Issue by UnknownSerhan** [AppliedEnergistics/Applied-Energistics-2#7970]
### Describe the bug

https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/69000972/e85e098e-9019-44b7-8caa-eb0a46b4a3bc

No other words needed.

### How to reproduce the bug

Wrenches do not exist in the creative menu.

### Expected behavior

They should exist.

### Which minecraft version are you using?

1.21

### On which mod loaders does it happen?

NeoForge

### Crash log

No crash log needed.

**Comment by Mithi83** [comment]
The code suggests that it might be found in the CreativeModeTabs.TOOLS_AND_UTILITIES tab rather than the AECreativeTabIds.MAIN you are probably looking at.

**Comment by Mithi83** [comment]
![wrench](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/28407460/de03df3a-f02d-4b28-85aa-114651595fb8)
Doublechecked. From my perspective this is a case of "works as designed".

**Comment by UnknownSerhan** [comment]
Shartte told me to open an issue idk
