### ISSUE TITLE
Bug wih inscriber inventory

### ISSUE THREAD

**Issue by Neodark7** [AppliedEnergistics/Applied-Energistics-2#798]
![2015-01-24_16 19 08](https://cloud.githubusercontent.com/assets/7981869/5887804/e505c9aa-a3e4-11e4-9e8c-9f06ff4aba94.png)
![2015-01-24_16 19 14](https://cloud.githubusercontent.com/assets/7981869/5887805/e50a64d8-a3e4-11e4-8066-cb8929c73f91.png)

If we send silicon into an inscriber with a router (Router Reborn) the inscriber receive to many silicon and stop working

i use appliedenergistics2-rv2-beta-7

same with gold diamond and pure certus quartz

**Comment by TheJulianJES** [comment]
I guess the Router is bugged and dosen't respect all methods, but I'm not sure.

**Comment by Neodark7** [comment]
Or it's a bug with the inventory limit of the inscriber ? i don't know :(

**Comment by TheJulianJES** [comment]
I don't think, this was fixed.

**Comment by Neodark7** [comment]
well i'll report it on the issue tracker from router reborn too then

**Comment by yueh** [comment]
Minecraft inventory management is a bit wonky. You ask the inventory if it can accept a specific itemstack and what the stacklimit is and then actually dump whatever amount you want into it.

They are probably ignoring one of these limits.

**Comment by tomevoll** [comment]
Sorry for the late reply, i will look into it, the router do respect the inventory limit set, but i will double check to make sure, if there is a wrong limit reported i will make a workaround for it for now.
I need to get all the dev tools set up again, im on a new computer, i hope to have a update tomorrow :)

**Comment by tomevoll** [comment]
is it supose to only get 1 silicon ?

**Comment by tomevoll** [comment]
ops sorry i responded on the wrong page as well lol

**Comment by Neodark7** [comment]
nice ! i test that now

**Comment by tomevoll** [comment]
should be resolved now, was a glitch in the router
