### ISSUE TITLE
Molecular Assembler crashes when requesting a Stonecutting Pattern recipe

### ISSUE THREAD

**Issue by ImAK9** [AppliedEnergistics/Applied-Energistics-2#7981]
### Describe the bug

Requesting a stonecutter recipe (Stone Bricks) within Molecular Assembler crashes the server & locks the chunk.

### How to reproduce the bug

* Make a stonecutting pattern (In this case, Stone Bricks)
* Add to Molecular Assembler
* Request it

### Expected behavior

Request without crashing & locking the server

### Which minecraft version are you using?

1.21

### On which mod loaders does it happen?

NeoForge

### Crash log

https://hastebin.skyra.pw/uzedisiher.swift

**Comment by mindforger** [comment]
Please use pastebin or something similar, no idea what your link leads to, but there is either an error on this pageor it does strange things, my scriptblocker went crazy
