### ISSUE TITLE
Log spam with channels disabled

### ISSUE THREAD

**Issue by Parker8283** [AppliedEnergistics/Applied-Energistics-2#799]
Running rv2-beta-7. During the init stage, [this](https://gist.githubusercontent.com/Parker8283/0f544aa17f2483c54285/raw/gistfile1.txt) is what's spammed in the log. Channels are disabled, which is most likely the cause of this. There is nothing else that is disabled in the config.

**Comment by yueh** [comment]
Duplicate of #422
