### ISSUE TITLE
Cable Facades

### ISSUE THREAD

**Issue by MrFlamazing** [AppliedEnergistics/Applied-Energistics-2#8015]
### Describe the bug

The cable facades are not showing up in EMI. The recipe does work.

### How to reproduce the bug

Go into EMI, search "cable facades"

### Expected behavior

The cable facade will not show in EMI.

### Which minecraft version are you using?

1.21

### On which mod loaders does it happen?

NeoForge

### Crash log

N/A

**Comment by Mari023** [comment]
there is a config setting, `enableFacadesInRecipeViewer` that you have to enable so the items are visible in EMI

**Comment by MrFlamazing** [comment]
Thank you.
