### ISSUE TITLE
Cross network autocrafting?

### ISSUE THREAD

**Issue by blackrulz** [AppliedEnergistics/Applied-Energistics-2#802]
I don't know if it is intended or not, but if i connect two separate networks (both with controllers) with storage bus and interface , i can share all the block, but not the crafting recipes.

if it's intended i found a bug, as i can see only the first crafting recipe from the storage network (the first chamber's first pattern in the crafting line). if i try to craft that, the system can't see the crafting cpu:)

i tried to install the crafting card to the interface, but no luck there. 

dw20 1.7.10 pack rv2 beta 1 ae2

pics for proof :)
autocrafting network chamber, closest to the controller
![2015-01-25_13 58 56](https://cloud.githubusercontent.com/assets/7272058/5891516/06c5267e-a49b-11e4-8e93-20c9b5711a2c.png)

Crafting network
![2015-01-25_13 57 28](https://cloud.githubusercontent.com/assets/7272058/5891517/0ab91704-a49b-11e4-83e8-7cf201472a17.png)

storage network
![2015-01-25_13 57 18](https://cloud.githubusercontent.com/assets/7272058/5891518/0dad5240-a49b-11e4-8f69-0f9e63b27717.png)

**Comment by yueh** [comment]
Intended.
