### ISSUE TITLE
Wrong documentation for ChannelMode

### ISSUE THREAD

**Issue by Aresiel** [AppliedEnergistics/Applied-Energistics-2#8022]
The ChannelMode class' latter two comments ([1](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/42e225776c5494e6f561f067e1c25b1ebef54b79/src/main/java/appeng/api/networking/pathing/ChannelMode.java#L38), [2](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/42e225776c5494e6f561f067e1c25b1ebef54b79/src/main/java/appeng/api/networking/pathing/ChannelMode.java#L45)) are wrong.

An enum value with 0 adHocNetworkChannels and 0 cableCapacityFactor does not disable requirements, but rather limit the amount of used channels to 0.

See:
![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/25839246/815c8f3b-b0bb-445f-ac0c-7f42582c0a32)
with this setup
![image](https://github.com/AppliedEnergistics/Applied-Energistics-2/assets/25839246/39d7607b-879f-4a4f-ab13-408653237603)
and the following enum extension:
```java
@Mixin(appeng.api.networking.pathing.ChannelMode.class)
public class ChannelModeNoneEnumExtension {
    @Mutable
    @Shadow
    @Final
    private static appeng.api.networking.pathing.ChannelMode[] $VALUES;

    @Invoker(value = "<init>")
    private static appeng.api.networking.pathing.ChannelMode create(String name, int ordinal, int adHocNetworkChannels, int cableCapacityFactor){
        throw new IllegalStateException();
    }

    static {
        appeng.api.networking.pathing.ChannelMode NONE = create("NONE", $VALUES.length, 0, 0);

        $VALUES = ArrayUtils.add($VALUES, NONE);
    }
}
```

I would correct this by simply removing the remark, since it's (clearly) not utilized.

**Comment by Technici4n** [comment]
I sure hope you aren't doing this kind of enum extension in production. :smile:

**Comment by Aresiel** [comment]
> I sure hope you aren't doing this kind of enum extension in production. 😄

They say ignorance is bliss, I hope you remain blissful on this matter.
