### ISSUE TITLE
appliedenergistics2-rv2-beta-8 crash with Reikas RotaryCraft

### ISSUE THREAD

**Issue by Njet75** [AppliedEnergistics/Applied-Energistics-2#803]
Realease beta 8 crash with Rotarycraft

Crash report  http://pastebin.com/tcHxRVD4
Log file http://pastebin.com/DSA4YFe5 

Hope this helps 
/Njet

**Comment by yueh** [comment]
Report it to RotaryCraft. There is nothing related to AE2 in the crashlogs.

**Comment by Njet75** [comment]
Got this confirmed by Reika.
This issue can be closed if you wish.

Thanks for fast support.
/Njet

**Comment by Jax775** [comment]
Njet75, Where did he say this? Do you have a link or was it a PM?
Is he going to work on it?

**Comment by Njet75** [comment]
Reika told me on Minecraft forum that he will fix this in upcoming V4 of Dragon API.
Told me to use  appliedenergistics2-rv2-beta-7 until he realease new version.
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more?page=811#c16442
/Njet
