### ISSUE TITLE
Fabric 12.9.9 Matter condenser not generating anything

### ISSUE THREAD

**Issue by Nidaelie** [AppliedEnergistics/Applied-Energistics-2#8039]
### Describe the bug

Using matter condenser to get singularities or even matter balls but when filling the 64k disk nothing is generated but energy is consumed.

Also not accepting fluids

### How to reproduce the bug

using a matter condenser to get singularities, nothing is generated

### Expected behavior

generation of singularities and matter balls

### Additional details

Fabric 1.19.2

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Fabric

### Crash log

----

**Comment by Nidaelie** [comment]
sorry closing cause it is a server issue not mod issue

**Comment by ProjectRichTea** [comment]
Hey, we are having the same issue in our NeoForge server, could you please advise how you fixed the server issue for this? @Nidaelie
