### ISSUE TITLE
Annihalation Plane time out

### ISSUE THREAD

**Issue by teamMK** [AppliedEnergistics/Applied-Energistics-2#804]
On a server i imported may farming stuff with conveyorbelts and annihalations planes, but when my space in the storage cells is full and too much stuff is lying on the planes it starts to time out me and everyone else on the server, the dimension cant be loaded. Maybe the planes should get deactivated when there is no space in network.

**Comment by yueh** [comment]
What is the case.
But thousands of items floating around might cause it.

**Comment by Deshiba** [comment]
Sounds to me like you need to build some overflow protection in your network rather then this being an issue with AE2. This would happen with sorting pipes, conveyorbelts and even vanilla if you could get enough entities in 1 spot.
