### ISSUE TITLE
extended inscriber guide crash

### ISSUE THREAD

**Issue by Tsumiki129** [AppliedEnergistics/Applied-Energistics-2#8041]
### Describe the bug

wen holding g to bring up the guide the game crashes trying to open it

### How to reproduce the bug

holding g over ether inscriber or extended inscriber from extended ae mod causes crash

### Expected behavior

expected to see the inscriber/ extended inscriber in the guide book

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

https://mclo.gs/46tvF2W

**Comment by Mari023** [comment]
remove starlight
