### ISSUE TITLE
prominence 2 - electric macerator bug

### ISSUE THREAD

**Issue by gama2287** [AppliedEnergistics/Applied-Energistics-2#8044]
### Describe the bug

when inserting redstone ore into 2 electric macerators connected with ae2 buses sometimes it fills its input slot from output slots

### How to reproduce the bug

connect 2 electric macerators (1 will make redstone crushed dust then send it into the second macerator to make redstone dust) with ae2 subnet and fill the first macerator with redstone ore

### Expected behavior

first macerator makes redstone crushed dust and sends it into the second to make redstone dust

### Additional details

it happens when the first macerator has some redstone crushed dust in all 4 output slots and runs out of redstone ore so its overclock decreases and it fills its input slot with redstone crushed dust (it has no inserting pipes or redstone crushed dust filtered export buses connected to it)

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Fabric

### Crash log

https://gist.github.com/gama2287/72a7225345d56d4a6d0293ad93a4ba77

**Comment by gama2287** [comment]
![2024-07-18_19 21 58](https://github.com/user-attachments/assets/dfa2c74d-b69a-4944-995f-08955a962e09)

i just figured out that it happens only when import bus has acceleration cards in it

**Comment by gama2287** [comment]
thanks for your help
i guess i will just chose another ore processing setup for now and wait for fix

**Comment by Mari023** [comment]
this is indeed an ae2 bug:
1. ae2 extracts 96 items at once
2. it can only insert 64 items
3. it tries to give the remaining 32 items back
4. inserting into the macerator will put items into the input slots

conceptually, what ae2 is supposed to be doing here is either check first how many items it can even store, and/or abort the transaction and retry while only extracting 64 items

relevant code: https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/c718acc75ab7a52d03204f08178b4b0ecd8ce439/src/main/java/appeng/parts/automation/StorageImportStrategy.java#L101-L112

I am not sure how likely a fix for 1.20.1 fabric is at this point

**Comment by gama2287** [comment]
I think you're right about the fix, but I'll hope that a miracle happens
i dont really like other ore processing options in this modpack

**Comment by Mari023** [comment]
for your specific setup: you can use auto eject on the MI machines, and either push in the next machine directly, or into and interface.
both options shouldn't have this issue

**Comment by gama2287** [comment]
thank you! i'll try it

**Comment by Technici4n** [comment]
Sorry, we are focused on 1.21+ NeoForge development, and don't have time to go fix this Fabric-specific issue.
