### ISSUE TITLE
Level Emitters Power Wrong Export Bus

### ISSUE THREAD

**Issue by Kuaku** [AppliedEnergistics/Applied-Energistics-2#805]
I'm currently running rv2 beta 7 and I'm having issues with level emitters transmitting redstone power to the incorrect export bus. I'm currently utilizing level emitters to automatically craft common resources  for expanding my ME network storage. However, the level emitters are no longer working as expected. Now I have an excessive amount of resources that are not needed and serious deficit in resources that I do need.

I've built a mini version of the setup I'm currently using to demonstrate my current problem. In this instance, I have three showing, but I've only configured two. 

In this first screenshot, I have only configured the middle level emitter and export bus. The level emitter above the export bus is turned off, however the system is still trying to craft sand -- as seen by the crafting monitor.

![2015-01-25_14 59 14](https://cloud.githubusercontent.com/assets/678242/5893034/cdb2c324-a4a3-11e4-9009-574b8f1f3b57.png)

I then turned off the other level emitters and increased the minimum amount for crafting sand. I canceled all pending work requests and reconnected everything. The only level emitter lit is the one above the sand, and after waiting for a full minute now, no request has been input for crafting sand.

![2015-01-25_15 00 16](https://cloud.githubusercontent.com/assets/678242/5893047/2767a8a8-a4a4-11e4-8e5c-9a92ec514d2c.png)

I went ahead and configured the export bus to right to craft smooth stone and added a furnace with an interface on it. Please note that crafting sand and smooth stone both require cobblestone, as such, I could not possible craft either resource without having cobblestone in the system to begin with (which I have plenty of.) The level emitter is not lit above the export bus for stone, however the one from sand is powering it.

![2015-01-25_15 02 14](https://cloud.githubusercontent.com/assets/678242/5893055/640f3bd6-a4a4-11e4-955b-548522e754be.png)

Here's some screenshots as to how I have quickly configured the emitters and buses used for this example. These aren't the exact numbers I normally would use, but I believe they provide a good enough example.

Sand Level Emitter:
![2015-01-25_15 02 21](https://cloud.githubusercontent.com/assets/678242/5893063/9c9782f6-a4a4-11e4-9990-e71f67ee0bc5.png)

Sand Export Bus:
![2015-01-25_15 02 24](https://cloud.githubusercontent.com/assets/678242/5893067/af15ef08-a4a4-11e4-8a8b-e038f9f9220f.png)

Smooth Stone Level Emitter:
![2015-01-25_15 02 44](https://cloud.githubusercontent.com/assets/678242/5893069/bb48d4a2-a4a4-11e4-8e29-8b360e19a52d.png)

Smooth Stone Export Bus:
![2015-01-25_15 02 46](https://cloud.githubusercontent.com/assets/678242/5893071/c897b484-a4a4-11e4-9b43-2d118d0fa825.png)

I was originally running rv1 stable 1 where this was working, however the server kept crashing on restart due to some bug with the crafting export buses that I believe was fixed in rv2. However, now in rv2, this configuration is no longer working properly.

As an example to the issue I've run into with this, I try to keep about 5000 of certain items in stock. This problem has now caused me to have over 70,000 Pure Fluix Crystal, 74k Pure Nether Quartz Crystal and currently only 7 Pure Certus Quartz Crystal. In this case, I had the Fluix crystal on the left and Nether crystal on the right and the one lit was for Certus Crystal. I have a huge deficit for that crystal now and a massive surplus of the other two.

**Comment by Cisien** [comment]
To solve the issue this caused, you can craft the pure crystals into storage blocks, then craft the storage blocks back to the original item.

As for this bug, it is probably some vanilla Redstone behavior, try separating these busses by a block. It seems like a bug that cables are relaying Redstone like a full block

**Comment by yueh** [comment]
This looks like the cables are acting as a full block. Which is not the normal behaviour of AE2.

I remember another mod breaking the normal behaviour of a non full block and causing it to emit a redstone signal to every adjacent block. But I cannot remember which one it was. It could be RefinedRelocation or RemoteIO, for some reason I faintly remember them in that regard.

I can only recommend that you reproduce it with AE2 alone. This will not have the issue.
And then slowly add the other mods back until it breaks.

**Comment by Kuaku** [comment]
I'll see what I can do. I'm currently using a slightly modified version of the Modsauce pack, so it will take some time to go through the massive list of mods until I can find the offender. Let me know if you happen to remember what that mod is and I'll let you know my results.


Thank you!

**Comment by yueh** [comment]
This issue #646

**Comment by Kuaku** [comment]
I checked the changelogs on modsauce, and it looks like they added RemoteIO in their latest release. Based on the issue you've linked and that change in the log here, I'm suspect you're completely correct. A test with just Forge and AE2 installed resulted in exactly what you had expected.

**Comment by JelmarG** [comment]
In the meantime, you could try keeping the cables separated? If it's the cables that are acting like some kind of redstone conduit, something like this might work for you:
![56dfa19b0f](https://cloud.githubusercontent.com/assets/4349184/5894752/442d948e-a50d-11e4-93c9-55409804a51d.png)

**Comment by Kuaku** [comment]
I just removed RemoteIO from my server and client for now. Nobody on my server has utilized anything from RemoteIO yet, so there was no impact created with its removal for now. I'll just wait for a release and test it out manually before I add it back in.
