### ISSUE TITLE
Extend the fuzzy card to use oredictionary. 

### ISSUE THREAD

**Issue by ericBG** [AppliedEnergistics/Applied-Energistics-2#806]
It's really annoying to have to put every type of copper ore in my export buses si a card that allows oredictionary integration would be appreciated

**Comment by yueh** [comment]
It is using the oredict. Maybe the mod in question does not register their ores correclty?

**Comment by ericBG** [comment]
The problem was BR yellorium and IC2 Uranium. Will do some further testing when I get back home but I'm pretty sure it didn't work.

**Comment by TheJulianJES** [comment]
I think the are not in the ore dictionary.

**Comment by ericBG** [comment]
OK, this is not your fault and just a mod oddity. Even though IC2 Uranium and BR Yellorium are oredicted, their ores are not.
