### ISSUE TITLE
ME level emitter not working for fluids

### ISSUE THREAD

**Issue by jasteen** [AppliedEnergistics/Applied-Energistics-2#8067]
### Describe the bug

ME fluid emitter seems unable to detect fluids in the AE system.  even with copious amounts of fluid in the system, it will not deliver a redstone signal

### How to reproduce the bug

add fluid to system. set emitter to emit redstone above a threshold that is below the amount of the fluid you have in the system.

### Expected behavior

expect redstone signal to be emitted.  redstone signal is not emitted

### Additional details

currently on  ATM10 alpha v0.20
![2024-07-26_20 21 59](https://github.com/user-attachments/assets/75e64e0d-c2cb-417b-80c5-6a1ce29cc34f)
![2024-07-26_20 22 02](https://github.com/user-attachments/assets/3f78cefd-9681-4d80-bfec-8ed63193235d)
![2024-07-26_20 22 16](https://github.com/user-attachments/assets/d41fa800-e43a-4abf-8dcd-a19a561b4e76)

### Which minecraft version are you using?

1.21

### On which mod loaders does it happen?

NeoForge

### Crash log

https://pastebin.com/4Vscvnc9

**Comment by Mithi83** [comment]
Seems to work with a small test setup using just water. Just some thoughts:

- You're using a fuzzy card in there: Why?
- Are you sure that the level emitter is part of the network where the fluid is stored and not some subnetwork that can't see the fluid? Your screenshot of a wireless terminal is not that convincing as the wireless terminal might be part of a different network. Verify with a ME Terminal that you place next to the level emitter.

**Comment by jasteen** [comment]
dammit, you are right.  there was a very small pocket of my network that couldnt see any items, it was just a subnetwork carrying P2P tunnels.  sorry.
