### ISSUE TITLE
AE2 rv2 beta 8 with DragonAPI/RotaryCraft v3d crash

### ISSUE THREAD

**Issue by Narkomantra** [AppliedEnergistics/Applied-Energistics-2#808]
While trying to build my own modpack I've came across a problem with AE2 and RotaryCraft v3d with DragonAPI of the same version. Reproduced it with just these mods installed on a clear MultiMC instance. Crash report comes here: http://pastebin.com/f35kcD1h
I belive it may be that RC doesn't have the newest AE API or something like that, but trying to find 'appeng' API in DragonAPI or RotaryCraft jars wasn't successful. Any tips on how to make it work before AE2/RC devs fix it?

**Comment by yueh** [comment]
#803
