### ISSUE TITLE
Inconsistancy Annihilation/Formation logic?

### ISSUE THREAD

**Issue by Deshiba** [AppliedEnergistics/Applied-Energistics-2#809]
Annihilation and Formation planes are 2 sides of the same coin. Yet Formation planes get their own interface with upgrade card slot and filter settings, while Annihilation planes get regulated by a storage bus.

Why is that? Seems to me like you'd logically want the Formation plane to be governed by the storage bus too. It would allow you to get rid of an interface while keeping consistancy.

**Comment by yueh** [comment]
Each part should have its own independent task and not do redundant things provided by others.
If you want to make something custom, combine what you need.

(In other words the Annihilation Plane will never get a GUI to filter it)

**Comment by trejkaz** [comment]
But the ME Formation Bus has a GUI to filter it. How is this not a "redundant thing provided by others"?
