### ISSUE TITLE
[rv2-beta-1] - Multipart Interfaces do not "pull" autocrafted items like their block counterparts

### ISSUE THREAD

**Issue by ariosos** [AppliedEnergistics/Applied-Energistics-2#811]
Steps to reproduce:
1. Set up a small network as shown in the first image. Note the block form of the ME Interface.
2. Autocraft an item (I used planks into sticks) and observe that it works.
3. Replace the block form with the multipart form as shown in the 2nd image and try to auto-craft.

![blockinterface](https://cloud.githubusercontent.com/assets/7917753/5929990/d3885cd6-a657-11e4-899b-7d17e5d99fe5.jpg)
![multipartinterface](https://cloud.githubusercontent.com/assets/7917753/5929991/d388709a-a657-11e4-8292-865ff3ad62f7.jpg)

Observed Result: The item to be crafted will not craft. The molecular assembler appears to try and craft the item in its' internal inventory/crafting grid, but no item appears.

Expected Result: The multi-part form should work like the block form of the ME interface.

The one work-around I've found is to stick another cable to another side of the molecular assembler..

**Comment by yueh** [comment]
Directional interfaces are not transmitting power. This applies to block interfaces wrenched to a fixed direction as well as part interfaces.
You can notice it, because the assembler is missing the glowing ouline around the glass panels.

**Comment by ariosos** [comment]
Ah, I barely even noticed it. Also, when items are "stuck" in the assembler (it has a red background in the assembler GUI with the item it's trying to use), there's no way to tell just by looking at the assembler (without a gui). Would be nice to have some glowing indicator, like a translucent red glass.
