### ISSUE TITLE
"Couldn´t find recipe for..." error in guide book

### ISSUE THREAD

**Issue by Svetrikk** [AppliedEnergistics/Applied-Energistics-2#8115]
### Describe the bug

After removing recipe for some items and going to quest book I get "Couldn´t find recipe for..." for the item. Also is there a way to completely remove the guide book or remove specific parts from the guide book?

### How to reproduce the bug

1. Remove the recipe with KubeJS
2. Open guide with the item you deleted the recipe for

### Expected behavior

Not showing the "Recipes" field for items that have removed recipe

### Additional details

![image](https://github.com/user-attachments/assets/59504760-fe6d-4a2a-a91f-adab8301f5ca)

### Which minecraft version are you using?

1.21

### On which mod loaders does it happen?

NeoForge

### Crash log

-

**Comment by Mari023** [comment]
> Also is there a way to completely remove the guide book or remove specific parts from the guide book?

the guidebook is loaded from datapack, you should be able to replace pages with your own version of them

**Comment by Svetrikk** [comment]
Is there any guide on how to replace pages?

**Comment by Mari023** [comment]
there is some documentation on how to write guidebook pages here: https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/main/guidebook.md

replacing them should be like creating a new page, except you place them at the same path the page you want to replace is

**Comment by Svetrikk** [comment]
What about removing the page? I tried putting a blank file at datapackname/assets/ae2/ae2guide/items-blocks-machines/wrench.md and it did not do anything.

**Comment by Svetrikk** [comment]
What about deleting a page? I tried adding a blank file in datapackname/data/ae2/ae2guide/items-blocks-machines/wrench.md and it did not work

**Comment by Mari023** [comment]
you might also need a resourcepack and not a datapack, I am not sure

**Comment by Svetrikk** [comment]
Oh it is a resource pack and for some reason I put the RP in the datapack folder :D It works now, thank you!
