### ISSUE TITLE
Glowstone dust will cause autocrafting to be grayed out

### ISSUE THREAD

**Issue by ariosos** [AppliedEnergistics/Applied-Energistics-2#812]
Now for a very, very peculiar bug that took me 3 days to figure out...

Steps to Reproduce -
1. Create a simple autocrafting setup as shown in setup 1, with the crafting pattern being iron chestplates (it can be any item). That is, creative chests with a translocator feeding items into a DSU. (This represents end-game item production that's feeding items at a constant rate.)
2. Click on the bottom translocators to start pumping items into the DSUs.
3. Attempt to craft the iron chestplate. Notice that the "Crafting CPU: Automatic" button is grayed out.
4. Now, switch off the bottom translocator that's feeding the glowstone dust and try to autocraft again.

Observed Result: The autocrafting is grayed out when glowstone dust is constantly being fed into the system, but is not grayed out when it is not being fed into the system.

Expected Result: Items being fed into the system should not affect auto-crafting.

The initial setup. Yes, there's no storage chest for the items to be crafted, but that has no effect on the bug. There's also no Crafting Unit, but even with one added, the issue still occurs with the glowstone dust.
![setup1](https://cloud.githubusercontent.com/assets/7917753/5930922/30e1805e-a664-11e4-8340-9e47eb938286.jpg)

Both items are going from the creative storage chests into the DSUs to simulate item production, and the chestplate is not craftable.
![craftattemp1](https://cloud.githubusercontent.com/assets/7917753/5930925/353320ae-a664-11e4-83d5-808bf0b36add.jpg)

The gold translocator is turned off.
![setup2](https://cloud.githubusercontent.com/assets/7917753/5930927/37b2ad72-a664-11e4-9cbf-2b6f80c77a8f.jpg)

The iron chestplate can now be crafted.
![craftattempt2](https://cloud.githubusercontent.com/assets/7917753/5930929/3b847ac0-a664-11e4-98ed-2b1738794b6a.jpg)

Note: This can also happen using an Ender IO Item Conduit (even without speed upgrades).

Note 2: I'm using a custom private modpack, so there may be another mod conflicting and causing this issue (?). I couldn't reproduce this in the Direwolf pack. (will continue investigating after work tomorrow)

**Comment by Deshiba** [comment]
@ariosos it's allways a good idea to include your AE2 Version number.

I could not reproduce this with pureRV2B8 & Vanilla. (same set up using chests and hoppers).

**Comment by ariosos** [comment]
Quick update - I'm deleting mods as I go along (going to work soon, so may not be finished this morning). The version number is RV2-beta-1. I'm not sure of a quick way to compile a list of all the mods I have installed.

Also, removing some mods, the item that's causing the bug changed from glowstone dust to obsidian. So, some mod's still causing some conflict somewhere. :/ (hate these kinds of bugs - I'm a programmer, so I know some of the annoying ones to track down.)

**Comment by Deshiba** [comment]
You might want to update your build to RV2-beta-8. In the 7 versions your issue might have allready been fixed.

**Comment by ariosos** [comment]
Still doesn't work. Here's the mods and versions that I've narrowed it down to -

appliedenergistics2-rv2-beta-8
ChickenChunks-1.7.10-1.3.4.16-universal
CodeChickenCore-1.7.10-1.0.4.29-universal
CoFHCore-[1.7.10]3.0.0B9-40
CoFHLib-[1.7.10]1.0.0B8-34
ironchest-1.7.10-6.0.62.742-universal
MineFactoryReloaded-[1.7.10]2.8.0RC6-5
NotEnoughItems-1.7.10-1.0.4.83-universal
ThermalExpansion-[1.7.10]4.0.0B8-23
ThermalFoundation-[1.7.10]1.0.0RC1-13
Translocator-1.7.10-1.1.1.14-universal

Forge 10.13.2.1236 (I can't use the latest version of Forge as it didn't work with some of the mods I had when I built the modpack)

I've uploaded my save to - http://www.filedropper.com/flatworld (hopefully that link works) - it uses the mods listed above.

**Comment by yueh** [comment]
There was an issue with Waila + NEI. You did not list Waila, but maybe it is just NEI related?

**Comment by ariosos** [comment]
Possible - I did have to use an earlier version of NEI/Forge since some mods I added weren't working with the latest versions. (trying to install the latest version of Forge in the ATLauncher is a bit tedious/wonky at times...).

**Comment by thatsIch** [comment]
I wonder if this is a DSU/Storage Bus Adapater issue

**Comment by thatsIch** [comment]
Can not reproduce this in the current version and with MFR + AE2 only with this setup,
@ariosos can you maybe re-confirm this bug? Maybe its some interaction problem between translocators and the DSU invalading the inventory or so

![2015-04-14_17 41 05](https://cloud.githubusercontent.com/assets/2210496/7140752/73ad4e18-e2cd-11e4-8911-7c82f5c560ac.png)
