### ISSUE TITLE
Round Robin for Storage Bus'

### ISSUE THREAD

**Issue by NFLD99** [AppliedEnergistics/Applied-Energistics-2#8120]
### Describe the feature

Allowing Storage Bus' to have a Round Robin option so it distros between each bus equally

### Reasons why it should be considered

this would greatly help for things like auto smelters that dont use a CPU to run

**Comment by Technici4n** [comment]
No. That is not possible to implement in a performant way.

**Comment by NFLD99** [comment]
would it be possible via an addon mod?
