### ISSUE TITLE
[Forge 1.20.1] AE2 WTHIT Plugin crashes when using WTHIT 8.15.0

### ISSUE THREAD

**Issue by seancrain** [AppliedEnergistics/Applied-Energistics-2#8169]
### Describe the bug

Using AE2 alongside the newest build of WTHIT causes the game to crash, throwing an error related to the plugin not being able to load.

### How to reproduce the bug

1. Install AE2
2. Install WTHIT and Bad Packets
3. Launch Game
4. Crash before Main Menu

### Expected behavior

The game should load normally.

### Additional details

WTHIT has been reworking its internal plugin logic, and it looks like AE2 is still using the older system that no longer works. For the moment, using an earlier version of WTHIT fixes the issue.

I have also encountered crashes when using the newest builds of WTHIT on 1.19.2. I have not tested this but I have a strong suspicion that is the same error. 

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/7tMcC5ww

**Comment by deirn** [comment]
Fixed in WTHIT, it's an overlook on my part.

**Comment by seancrain** [comment]
Issue has seemingly been fixed with WTHIT 8.15.1 on 1.20.1.
