### ISSUE TITLE
Client Crash on viewing invalid pattern 1.21.1

### ISSUE THREAD

**Issue by micrwvae** [AppliedEnergistics/Applied-Energistics-2#8175]
### Describe the bug

hovering over an invalid pattern crashes me instead of giving me the option to take it out to clear it

### How to reproduce the bug

updated the allthemods 10 modpack and was rearranging my patterns
hovering over a invalid one crashed the client

previously i was able to view them just fine

### Expected behavior

pattern displays as invalid and can be cleared manually 

### Additional details

crash happening on
the allthemods10 modpack: 0.41
ae2 19.0.22

### Which minecraft version are you using?

1.21

### On which mod loaders does it happen?

NeoForge

### Crash log

https://mclo.gs/tGcakA0

**Comment by pedroksl** [comment]
Hi. It seems this bug has more to do with my mod [(AdvancedAE)](https://github.com/pedroksl/AdvancedAE) than AE2 itself. Would you mind reposting this issue over there? Thanks.

**Comment by micrwvae** [comment]
will do
