### ISSUE TITLE
Possible bug: EnderIO ME conduits reported an unfeasible number of cables

### ISSUE THREAD

**Issue by DenMesh** [AppliedEnergistics/Applied-Energistics-2#818]
Running AE2 rv2-beta7, EnderIO 2.2.6.317
Disclaimer: cannot provide a minimum working example yet, will do when I have more time.

A network with a multiblock controller has a bunch of Dense Cables going out. 3-4 blocks away from the controllers the cables are spliced into EnderIO Dense Conduits. At their destination the conduits are either spliced into dense cables once more or simply have covered cables branching off of them. When doing an inspection of the network with the Network Tool the amount of ME Conduits (EnderIO ones) is ridiculous: on the order of hundreds of thousands. The network by a rough estimate has no more that 500 of ALL cables taken together.
A related issue may be a significantly long time for network updates. When attaching new channel-using peripherals, i.e. terminals or buses, channel count update and peripheral activation happen after several minutes.

Will add better detailed information some time soon.

**Comment by yueh** [comment]
EnderIO issue, known and reported to them.
