### ISSUE TITLE
Why would I use pure crystals?

### ISSUE THREAD

**Issue by xJon** [AppliedEnergistics/Applied-Energistics-2#819]
Pure crystals cost more time and power. I don't understand why would I use them instead of the unpure crystals.

**Comment by UndeadZeratul** [comment]
Pure crystals are a way to double your existing quartz crystals, without having to go mine them manually or with quarries/mining bores.

Mining them costs time, and using quarries cost time and power.  I don't understand why I would mine them instead of growing pure crystals.
