### ISSUE TITLE
AE2 Running out of channels when there should be enough

### ISSUE THREAD

**Issue by MaxGib** [AppliedEnergistics/Applied-Energistics-2#8199]
### Describe the bug

I currently am running an ME system that has 6 ME controllers and has 27 channels in use. When using a dense cable that should support 32 channels, I am "running out of channels" when my smart cable says only 8 are being used if I add a single pattern processor and molecular assembler to the system. Here are screenshots to show.  
![2024-09-25_16 34 22](https://github.com/user-attachments/assets/a44f19fd-d648-40f5-a529-004a8519d79d)
![2024-09-25_16 34 33](https://github.com/user-attachments/assets/10271a75-78c7-4aec-a426-084079824f48)

![2024-09-25_16 34 58](https://github.com/user-attachments/assets/fdcbb8df-08c0-4f93-8822-962b594eb730)
But when adding the pattern processor and assembler this happens.
![2024-09-25_16 38 02](https://github.com/user-attachments/assets/3cfd4073-8431-469f-8faa-97ae22f4db9a)
![2024-09-25_16 38 15](https://github.com/user-attachments/assets/ab2ac9a4-051a-4849-8987-094694a923fc)
I am on ATM9 To the sky if that helps

### How to reproduce the bug

To further describe my setup, I have an endercell with 50 MFE providing power through ultimate energy cables, so that should not be the issue. I have 3 wireless systems connected that all either import or export items to or from automated systems. Please let me know if you need me to further describe the setup.

### Expected behavior

I expected the dense cable to be able to support everything connected to it, as there are not 32 items connected.

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/MaxGib/ed4ffae566621250ddc717a7f243274b

**Comment by MageInBlack** [comment]
That is not a bug, you are passing dense cable through a CPU. And any AE2 machine, including CPUs are acting as 8 channel cable. And you are passing at least 9 from what i can see

**Comment by Mari023** [comment]
full block devices (like your crafting cpu) act as non-dense cable and only allow 8 channels to pass through them (including the one channel it already uses for itself)

**Comment by Mari023** [comment]
like in this screenshot, you can clearly see the difference between the dense cable connection and the non dense cable connection
![cable](https://github.com/user-attachments/assets/55dbaaf7-bc68-46f2-9fd0-d7e39ba32b30)

**Comment by MaxGib** [comment]
Ahh, I see thanks, I did not know that. Thanks guys!
