### ISSUE TITLE
appeng.hook.tickhandler lag

### ISSUE THREAD

**Issue by Yselith** [AppliedEnergistics/Applied-Energistics-2#820]
Hello,

I got some lag from the appeng and logs too, 

http://pastebin.com/5bmj9G4n

http://img4.hostingpics.net/pics/765745Capture.png

**Comment by yueh** [comment]
1) (Log) Update to the latest beta, it will show a better log message including which P2P tunnels are causing it.

2) (Screenshot) There are some mods known (like Extrabees/Extratrees), which have a really taxing crafting handler or a huge amount of oredict entries. It might be already noticable in vanilla, when you craft a full stack. AE2 allows you to craft more items as well as faster in general, so it will be also way more noticable. But we cannot really do anything about it.

**Comment by Yselith** [comment]
Oh ok it's very good to know ! Is there a way to add the latest beta in the dw20 pack, cause actually players have to add it manually. I tried to swap mcmod.info & AppEng.class from the beta 1 to beta 7 & 8 but i got an class error.

**Comment by yueh** [comment]
Only two real options.
First bug the FTB team about their extremely slow update process as well as that they should update. (and start hoping)
The other is switch to a launcher which allows you to update the pack by yourself as well as push the changes to every user, without depending on someone else.

**Comment by Yselith** [comment]
Yeah sadly :/

And about limiting the crafting maximum process ?

**Comment by thatsIch** [comment]
Closing to missing updated logs
