### ISSUE TITLE
Client sided crash: "Tessellating block model - Indium Renderer"

### ISSUE THREAD

**Issue by james5922** [AppliedEnergistics/Applied-Energistics-2#8206]
### Describe the bug

Client sided crash on Fabric 1.20.1 when attempting to view a guidebook entry (for this particular crash, it was for the ME Controller).
The crash log blames AE2 for... not implementing a StarLight method(?), and also mentions Continuity.

### How to reproduce the bug

1 - Open an in-game AE2 guidebook entry (presumably one that shows a block model)
2 - Game crashes

### Expected behavior

No crash.

### Additional details

This crash occurred while on a server, though only my client crashed. The server is using a heavily edited version of the Quantum Freedom 2 modpack, which had the latest version of AE2 at the time it was put together.

From what I can tell this is not the same issue as #7421.

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Fabric

### Crash log

https://gist.github.com/james5922/147b22f011485e439e29f49993c71c2e

**Comment by Mari023** [comment]
remove starlight

**Comment by james5922** [comment]
alright, thanks
