### ISSUE TITLE
Infinite Channels arent actually providing more than 8 channels

### ISSUE THREAD

**Issue by Saereth** [AppliedEnergistics/Applied-Energistics-2#8208]
### Describe the bug

I have the channels set to "infinite" in the config, attaching more than 8 devices on the network is causing it to show device offline/no channel on newly connected devices

### How to reproduce the bug

setup ae2 with unlimited channels, connect more than 8 devices

### Expected behavior

Channels should be unlimited

### Additional details

![image](https://github.com/user-attachments/assets/77ecac63-f0e8-483a-89e5-51d610418f5c)
![image](https://github.com/user-attachments/assets/fd7c422d-82de-4b63-9479-fdb34c5c9b80)
![image](https://github.com/user-attachments/assets/ce77b5f4-7ac5-4325-a614-075f96f63556)
![image](https://github.com/user-attachments/assets/9838678e-38ad-4ca4-a3bf-b8db82c66af8)

### Which minecraft version are you using?

1.21

### On which mod loaders does it happen?

NeoForge

### Crash log

not a crash

**Comment by Saereth** [comment]
added
https://mclo.gs/nyr8UiH

**Comment by Saereth** [comment]
ok false alarm, deleting and regenerating the configs resolved the issue

**Comment by Mari023** [comment]
oh, I missed that at first: you showed the .json config, but newer version of ae2 (including the one you are using) uses a .toml config

regenerating the config "fixed" this because now there is only the .toml config file, and editing that works (and would have worked before)

**Comment by Saereth** [comment]
> oh, I missed that at first: you showed the .json config, but newer version of ae2 (including the one you are using) uses a .toml config
> 
> regenerating the config "fixed" this because now there is only the .toml config file, and editing that works (and would have worked before)

Yep, exactly this in case anyone else runs into it, dont even know when the configs change but I basically just removed all the ae2 configs entirely, let them regen, saw the new toml files and editing those worked fine.
