### ISSUE TITLE
Viewcells immediately fill up all JVM client memory and grind it to a halt

### ISSUE THREAD

**Issue by SubsterNL** [AppliedEnergistics/Applied-Energistics-2#821]
On my somewhat bigger storage network (10+ racks filled with 64K cells) I tried using viewcells.

It immediately grinds my client to a standstil and only way it to remove the viewcel and restart my client. 

There appears to be a very serious memory leak there.

Using beta 8. Running a local server (with mostly DW20 all updated mods and a few additions, using the standard MC launcher for my client with 3G max for my client..  Normal operations it runs around using about 1.2G out of 3G total).

**Comment by yueh** [comment]
Please provide more information on how to reproduce it.

**Comment by SubsterNL** [comment]
Very simple to reproduce... I just get an empty view cell.. Set it so it only displays dimlets (from RFTools) and put it in my ME crafting terminal... Using the fuzzy card for that. 

When I put it in my crafting terminal The client immediatly fills up all available memory and grinds to a halt... Since it doesn't exactly crash (yet) I don't really have an error log. If you want I can produce a normal client log.. I'm running a local server and the client on the same PC btw.. Pretty beefy computer and mostly DW20 like mods in 1.7.10

16 ME drives, half of them full of 64K storage cells.. About 2/3th of them are filled up.

**Comment by yueh** [comment]
Cannot really reproduce it with RFTools alone. Also the fuzzy card will not display every available dimlets as they are different items.

**Comment by SubsterNL** [comment]
Well no.. They have the same ID... only different sub numbers.. 

But not really the point. :) The point is that viewcells appear to be unusable in larger networks. I assume there is some sort of weird big memory leak there looking at how fast my client is eaten up.

**Comment by yueh** [comment]
Profiling/sampling with jvisualvm might help (see [Profiling](http://ae-mod.info/Profiling/))
I suspect something related to the oredictionary. But without an option to reproduce it with ae2 alone or a very limited amount of other mods, it is not really possible to track down.

Regarding the fuzzy card, they will not match different metadata as these are different items.
Just damage values or oredict entries.

**Comment by the-vindex** [comment]
Do you use server room with chain of interface-storage bus? Because I do and I have the same issue as you describe. Maybe this is common?

**Comment by yueh** [comment]
Two reports without any real facts count hardly as common.

**Comment by the-vindex** [comment]
@yueh: I was looking for common design patterns people use when causing the issue. 
@SubsterNL: could you react to my question?

**Comment by thatsIch** [comment]
Inactive close
