### ISSUE TITLE
AE x Sophisictaed Backpacks food duplication

### ISSUE THREAD

**Issue by Takinatar** [AppliedEnergistics/Applied-Energistics-2#8211]
### Describe the bug

**Describe the bug**
Having a food item in both AE System and in your backpack, with an Autofeed upgrade while having the "Restock" option on, in the wireless remote from applied, will cause the food to be duplicated on both sides when autofeed happen.

### How to reproduce the bug

**To Reproduce**
1. Put the food of your choice in AE storage and equip a wireless remote.
2. Put the same food in your backpack and equip a feeding upgrade.
3. Enable "Restock" in wireless remote and trigger the auto feed.
4. The food in both the AE System and in your backpack should have been duplicated.

### Expected behavior

**Expected behavior**
When you get fed by the autofeed, it should be duplicated in your backpack and in your AE storage?

### Additional details

**Screenshots**
![image4](https://github.com/user-attachments/assets/08b9eee5-9dc5-47a3-b0b0-df568d7a74f7)
![image3](https://github.com/user-attachments/assets/c2d83913-b113-4955-b573-d22e1d253a66)
![image2](https://github.com/user-attachments/assets/96fec064-8424-4230-845f-8e181ca8c7c0)
![image1](https://github.com/user-attachments/assets/388b7889-370b-4fb3-8e9a-2bd5ecd809af)

**Versions**
appliedenergistics2-19.0.23-beta

**Extra**
This bug also have been reported on Sophisticated Backpacks's repo as suggested by a user, as it is unclear "Who's fault it is".
https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/1176

### Which minecraft version are you using?

1.21

### On which mod loaders does it happen?

NeoForge

### Crash log

None

**Comment by Mari023** [comment]
the restock option is from an addon mod (ae2wtlib) and not by ae2
