### ISSUE TITLE
How to put ME Quantum increase energy expenditure alone?

### ISSUE THREAD

**Issue by SilenceDuan** [AppliedEnergistics/Applied-Energistics-2#823]
How to put ME Quantum increase energy expenditure alone?

I just want to adjust the energy ME Quantum, but does not change the other energy-consuming equipment and lines, I want two ME Quantum consumption 40000000EU = 4 minutes.

You know, AE balance is not very good, I want players to use rail transport, rather than very little energy ME Quantum, ME Quantum strength only for post players.

Moreover, AE is alien technology, in order to control human alien portal, cheap consume very inappropriate.

**Comment by yueh** [comment]
Not possible. You can only disable the QNB completely, if you want to prevent players from using it.

**Comment by SilenceDuan** [comment]
Thank you, and can only be disabled.
