### ISSUE TITLE
crash with autocrafting in inscribers

### ISSUE THREAD

**Issue by CroizzantYT** [AppliedEnergistics/Applied-Energistics-2#8235]
### Describe the bug

for some reason in a dedicated server everytime the press and the base item enters a inscriber it just crashes everything and the server freezes until u kill it, then it just rollbacks to when u didnt put the press inside the inscriber.

### How to reproduce the bug

with me, just put it inside an inscriber and it crashes

### Expected behavior

for it to output a printed circuit

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

it doenst make one and i cant crash a server

**Comment by 62832** [comment]
> it doenst make one and i cant crash a server
Ask your server operator to provide any recent logs.

**Comment by CroizzantYT** [comment]
so i am the operator and it doesnt send any logs, it just freezes the game for no reason and u cant kill it.

**Comment by 62832** [comment]
I didn't specify a crash log, I just asked for any logd including `latest.log` in case they might have any information.

Otherwise, do you have any exact steps to reproduce this? Are you playing on a larger modpack or does this also happen only with AE2?

**Comment by CroizzantYT** [comment]
this has 300 mods and it probable is some issue in the modpack. the modlist is:

https://pastebin.com/bm8xi5dg

**Comment by CroizzantYT** [comment]
and about logs, it doesnt make any if that happens for some reason

**Comment by 62832** [comment]
`latest.log` is always created in general for any running server/game and usually contains information about anything ongoing in that game. I asked for it specifically because it could shed some light on what exactly is happening just before the server freezes up.

Also, I see that among those listed mods is AECapFix, which indicates you're playing on a version between 1.18.x and 1.20.1 inclusive. I don't think we even provide support for either of those versions, especially not for an issue which might not even be reproducible, or at least you haven't given exact steps for to reproduce with AE2 alone.

**Comment by CroizzantYT** [comment]
i will try to get the log. about the version, it is 1.20.1 and the version thingy said it has support

**Comment by CroizzantYT** [comment]
looking here, every single log that occurred by that "crash" doesnt have anything related to ae2 or anything, and they stop logging when it "crashes" and just spams "[spark/] Timed out waiting for world statistics"

**Comment by 62832** [comment]
I will ask one more time then.
- Does this happen with AE2 *on its own* or on any other modpack that features it?
- Do you have any step-by-step instructions that can be used to reproduce this issue consistently for us to debug?

**Comment by CroizzantYT** [comment]
probably some incompatibility only in this modpack
download the modpack, put it in  a dedicated server and try it

**Comment by CroizzantYT** [comment]
[eternum.zip](https://github.com/user-attachments/files/17622946/eternum.zip)
