### ISSUE TITLE
ConcurrentModificationException in EnergyGridCache when using AE2 with Dimensional Doors (Minecraft 1.12.2)

### ISSUE THREAD

**Issue by MrLinusK** [AppliedEnergistics/Applied-Energistics-2#8238]
### Describe the bug

When entering a Dimensional Doors portal, Minecraft crashes due to a ConcurrentModificationException in the EnergyGridCache of Applied Energistics 2. The issue is specific to interactions between AE2’s power grid management and dimension-altering mods like Dimensional Doors.

I THINK

### How to reproduce the bug

Install: 
Applied Energistics 2 (rv6-stable-7)
Dimensional Doors (Dimensional Doors-3.2.2)
FluxNetworks (4.1.1.34)

Enter a portal generated by Dimensional Doors (I created a empty Dimension).
Create a EA2 system that consumes a power from a Flux Point, not sure if this mattes but i also had a quantum link.

### Expected behavior

Not a Crash?

### Additional details

Workaround: Disabling AE2’s power requirement (UsageMultiplier=0) in the AE2 configuration prevents the crash, indicating the issue lies in the energy grid handling.

### Which minecraft version are you using?

1.12 - UNSUPPORTED

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/YWmGNU5e

**Comment by Mari023** [comment]
1.12.2 is not supported anymore
