### ISSUE TITLE
ME IO Port not working

### ISSUE THREAD

**Issue by Daur99** [AppliedEnergistics/Applied-Energistics-2#825]
I can't get ME IO Port to transfer storage data from cells to network or vice versa. It's connected to the network and everything looks fine but it simply won't do anything. Playing on a Beyond Reality 2.2.3C server.

**Comment by yueh** [comment]
Could you provide some more informations? Maybe screenshots?

**Comment by Daur99** [comment]
I may have had it set up wrong, maybe not enough channels. I will try a different setup tonight to make sure and post more info if still not working. Thank you.
