### ISSUE TITLE
1.21.1: Wireless Universal Terminal: Add Tabs

### ISSUE THREAD

**Issue by hofq** [AppliedEnergistics/Applied-Energistics-2#8256]
### Describe the feature

The Navigation with a small single Button between the Terminals is a bid janky and was not what i expected from the universal terminal

### Reasons why it should be considered

A Menu in the Style of Tabs would be a lot more useful, as it supports muscle memory

**Comment by 62832** [comment]
The Wireless Universal Terminal is not our own item. Take it up with the developer for AE2 Wireless Terminals (AE2WTLib), the add-on that *does* add the universal terminal.
