### ISSUE TITLE
Autocrafting setup unable to craft a BSpace upgrade (Jabba) with EnderStorage

### ISSUE THREAD

**Issue by Pyeroh** [AppliedEnergistics/Applied-Energistics-2#827]
On my private modpack, I can't get my network to craft a BSpace upgrade with an enderchest from Ender Storage. I think it's because of the recipe of the BSpace upgrade, which require a Vanilla enderchest, and then is replaced by the EnderStorage one.
When I ask one upgrade, the simulation plan display "Calculating Please Wait..." and the game freezes.
When I use only AE2, EnderStorage, and Jabba, the game take about one minute to calculate the crafting plan, after that it slows down a lot.
If I only use a Vanilla Cafting Table, there's absolutely no problem.

Tested with AE2-rv2-8, EnderStorage 1.4.5-27, Jabba 1.2.0a (and NEI 1.0.4.83, plus latest dependancies)

**Comment by yueh** [comment]
EnderStorage is a bit special here as they add each color combination into the oredictionary, resulting in 4096 or 8192 (I cannot remember, if it also adds the diamond upgraded ones) entries, which all needs to be evaluated as potential crafting path and this just takes some time.

The best option currently is to activate the vanilla ender chest again.

**Comment by Pyeroh** [comment]
Thank you for your (very) fast answer ! It works perfectly, by activating this option. However, shouldn't it be possible to disallow this oredict search, via an ingame option, individually for each pattern ?
Well, it's just a suggestion, if it's not possible, using this workaround will be fine

**Comment by yueh** [comment]
There is a PR open (#829), which should improve the performance and lower memory consumption quite significant. But it needs further testing.

For example we a currently creating 16777216 distinct copies of enderstorage chests, including other overhead it consume about 600-1000 MB of memory for me.

**Comment by thatsIch** [comment]
Should be fixed
