### ISSUE TITLE
Access ME Chest inventory

### ISSUE THREAD

**Issue by Supdup** [AppliedEnergistics/Applied-Energistics-2#828]
Hi,

I don't know if it's a bug or an intended feature, but the ME Chest inventory interface acts weirdly when interacting with other mods (I didn't try with an ME Storage bus but it might be the same), meaning that when you try to get the number of items present in the chest, you will get a wrong value (may be as if the accessed inventory was the disk slot) but you can push items successfully. 

For instance, a translocator node will endlessly push items into the chest. The same happens using Steve's Factory Manager, it's the reason why I think it's probably related to the ME Chest.

**Comment by yueh** [comment]
ME chest do not expose their inventory stored on the disk to something accessing it. Only the inventory holding the cell itself. But similar to an interface they allow you to insert items directly into the network by piping them into it.
