### ISSUE TITLE
Limited amount of item stack insert or withdrawal in ME Network/ME Drive storage

### ISSUE THREAD

**Issue by YukiNoHana-0** [AppliedEnergistics/Applied-Energistics-2#8282]
### Describe the bug

Im using a mod called [biggerstacks](https://www.curseforge.com/minecraft/mc-mods/bigger-stacks)
I've set my item stack limit higher than 64.
Whenever I insert an item stack on my ME Network using Shift + Left Click on the crafting terminal, it only insert exactly 118 items, same as when withdrawing items, i only get 118 items when extracting instead of the configure stack I've set.

**_This was not happening before_,** it works perfectly before even I've set my stack limit to 10000 per stack of item, just one Shift + Left Click it will insert all the item stack.

On normal chest, like the vanilla Minecraft chest, this problem does not occur, i can insert or extract all the stack.

### How to reproduce the bug

Insert Items higher than 1000 count on the crafting terminal, must have biggerstack mod installed to test.

### Expected behavior

Insert all items at once on the ME Network or extract the configure stack, for example, if i have for example 20000 cobblestone on my network, and ive set my biggerstack config to 1000, with a left click, i should get 1000 cobblestone, but im only getting 118.

![image](https://github.com/user-attachments/assets/9168901d-d7b5-47ef-a11a-375de07c96a6)

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

there is no crash.

**Comment by YukiNoHana-0** [comment]
welp, i cant seem to find the reason why this is happening, i've tested a new world, created a ME network storage in creative mode, set bigger stack to 10000, inserted 10000 wood on the ME Network, it works in one click and when i extracted it with a left click, it pick up 10000 wood no problem.

i dont know whats happening on my previous world.

**Comment by YukiNoHana-0** [comment]
I've found the issue, I'm so dumb, it requires more energy, it seems that energy acceptor can't handle it.

**Comment by Mari023** [comment]
> it seems that energy acceptor can't handle it.

The energy acceptor could handle it, however your network has to have sufficient energy storage (it has to store all the energy you want to use in a single tick).

A controller has some internal storage, which is why it works with that.
Adding a (dense) energy cell would also fix this
