### ISSUE TITLE
ME Import Bus unable to pull from Ender Chest

### ISSUE THREAD

**Issue by katouriku** [AppliedEnergistics/Applied-Energistics-2#8284]
ME Import Bus unable to pull from Ender Chest.
I've tried pulling from all sides of the Ender Chest and have confirmed it's not a channel issue.
I believe I recall being able to pull from Ender Chests without issue on prior versions of the game.

- Environment: 
https://pastebin.com/FrNKRy4g

**Comment by Kevin-Marsh** [comment]
The fact that you don't appear to have an enderchest mod in the list implies to me that you are trying to use an importer to import from a vanilla enderchest which doesn't and has never worked.

**Comment by katouriku** [comment]
Oh, I apologize. I just checked and yes I was using an Ender Storage chest in past I realized. Out of curiosity is it a limitation of vanilla Ender Chests that prevents them from working with ME busses or a design choice? Sorry again for the false report and thanks for educating me on the cause of my issue!

**Comment by Kevin-Marsh** [comment]
Vanilla enderchests aren't really a storage type. I believe they store as a part of the player character data so there isn't ever anything in the chest or a method to pipe in or out.

**Comment by Mari023** [comment]
you also can't extract items out of them using a hopper.

Conceptually, the issue you face when trying to extract (or insert) from an enderchest with some kind of automatic device is that you have no clue from which player's enderchest you should extract.

**Comment by katouriku** [comment]
Ohh that makes a lot of sense. I've gone ahead and found a 1.21 enderchest
mod. Hopefully enderstorage gets updated someday haha. Thanks for your help!
