### ISSUE TITLE
Failing to load world / crashing

### ISSUE THREAD

**Issue by Titop54** [AppliedEnergistics/Applied-Energistics-2#8297]
### Describe the bug

Crashing when opening a world with an already network.
Tried with ae2 alone and no crash (tried 5 different times), recreating a medium size network (200~ channels)

### How to reproduce the bug

Monifactory modpack
Upgrade the included version to the lastest one
Enter a world with a network
Have a chance to crash

### Expected behavior

Not crashing / showing the screen that something crashed me

### Additional details

In case of monifactory, it will crash but not close the game, in that case, you can try again and maybe get into the world, not consistent

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

NeoForge

### Crash log

https://mclo.gs/bog7VRh

**Comment by Technici4n** [comment]
Duplicate of https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/8295#event-15742285622 but we need to backport the fix to 1.20 heh.

**Comment by Titop54** [comment]
Oh. It thought there were none, mb
Seems to be fixed, ty!
