### ISSUE TITLE
Possible solution for more powerful searching?

### ISSUE THREAD

**Issue by firelizzard18** [AppliedEnergistics/Applied-Energistics-2#8306]
### Describe the feature

@yueh has said a variation of the following on various different issues:

> Also compared to JEI we cannot take like 30-60 seconds to build a fast searchable cache during the startup or the initial serverjoin and then use it constantly.

I'm wondering if the following approach would be feasible:

1. Like JEI, build a global cache on startup/serverjoin. This cache would include all items, not just items within a given network.
2. When a user does a fuzzy/tag search, search the global cache.
3. Use the results from the global cache as a filter for the network contents, that is calculate the set intersection between the network contents and the global cache search results. Off the top of my head it seems like this could be done with a pair of trees.

If this is actually feasible, I'd be interested in working on it if I can find the time.

### Reasons why it should be considered

There are numerous feature requests for more search features; from a quick search:

- #4852
- #6853
- #5417

**Comment by Mari023** [comment]
I am a bit confused about the issues you linked, the first one is about Tag based and tooltip based search, both of which are implemented and work.
The second one is about better filtering for import/export buses and maybe interfaces, and the main problem there is how to make a good UI for that.
The third issue is the only one that seems really relevant to your proposal, tho there are already some improvements in that regard (search works word by word, so the example of searching `iron re` would work now.

So the only remaining one is fuzzy search

**Comment by firelizzard18** [comment]
Tag searching works? That's the one I actually care about, but when I search `#iron` or something like that it works in JEI but does not work in my ME terminal. I opened the issue because it seemed like an interesting programming challenge but tag searching is the reason I care. #4852 and #5417 have a comment from yueh like the one I quoted, which is why I listed them. #6853 seemed related; after reading the other issues I figured it had the same underlying issue (search performance), it wasn't obvious to me that it's about UI.

**Comment by firelizzard18** [comment]
This might be user error. Somehow I thought `#` was what you used in JEI to search by tag. `$` seems to do what I want.

**Comment by Mari023** [comment]
> This might be user error. Somehow I thought `#` was what you used in JEI to search by tag. `$` seems to do what I want.

it is a bit confusing, and different between recipe viewers (see #8291, which tries to help this a bit)

**Comment by firelizzard18** [comment]
What I care about is tag searching. That works and I don't know if it's new but I just noticed that my wireless terminal's search field has a tool tip that explains using @, $, #, and *. JEI's behavior is still confusing me, but that's obviously not an AE issue. Since fuzzy search isn't important to me, I'm going to close this.
