### ISSUE TITLE
Fluix Cable can't be placed. Drops as Item.

### ISSUE THREAD

**Issue by kyba274** [AppliedEnergistics/Applied-Energistics-2#832]
Hello,

I've got an odd error where my network spanning 4 chunks (with many subnetworks) was all working fine, and today one part of a subnetwork disconnected because the cables disappeared. The cables are not able to be replaced. When I try placing a cable there, it is immediately dropped on the ground as an item.
There have been no new additions to the network to prompt this to occur.

**Comment by JelmarG** [comment]
If you have an ME Security Terminal on your network; temporarily remove it and try again.
