### ISSUE TITLE
Request Logistic Pipe --> ME Interface ---- no Items from LP Network visible in AE2

### ISSUE THREAD

**Issue by Ioandar** [AppliedEnergistics/Applied-Energistics-2#833]
I have a Request Logistic Pipe connected to an ME Interface.

Problem: No Items from LP Network are visible in AE2

>  logisticspipes-0.8.3.98.jar
>  appliedenergistics2-rv2-beta-8.jar | appliedenergistics2-rv1-stable-1.jar

Connecting a MK2 with ModItemsink/Provider modules at the ME Interface WORKS FINE
-> Items from AE2 are available in LP
-> AE2 Items will be routed into the AE2 systems

davboecki said it is not on LP side. https://github.com/RS485/LogisticsPipes/issues/567#issuecomment-72397953 

Can you please have a look? I would love to see LP resources from within AE2 again

tyvm

**Comment by yueh** [comment]
There is currently no integration for LP in AE2.
See also #21.

**Comment by Ioandar** [comment]
oh, sorry, I missed that. tyvm for your fast answer!

LP -> AE2 does actualy work fine via ME Interface...

I would very much like to use AE2 again but without LP integration I find it hard to peek/migrate (I am an old LP dog and having some trouble learning all the cool new tricks AE2 has to offer)

If you could find some time to make the request-pipe qork again on the ME-Interface it would be great!

cheers and tyvm

**Comment by adamcogx** [comment]
Has anything been done in regards to getting AE2 to be able to request items from LP again?

**Comment by thatsIch** [comment]
No, we do not have enough man-power to realize this at the moment. There are more pressing issues to be dealt with.

I know of some people, who want to work on this, which are not part of the AE2 crew; so I let them deal with this
