### ISSUE TITLE
ME System causes occasional freezing

### ISSUE THREAD

**Issue by beewyka819** [AppliedEnergistics/Applied-Energistics-2#834]
Whenever I make an ME system with the latest version for 1.7.10 my console keeps saying that a mod is attempting to perform game activity during mod construction and that it's a serious programming error. This is a serious issue as it makes the game unplayable with an ME system

**Comment by yueh** [comment]
Please provide the corresponding logs (and please post them on pastebin or similar)

**Comment by beewyka819** [comment]
The console logs? Because the game wouldn't crash, just freeze up every 5-10 seconds, forgot to mention that, was in a rush. It also names some mods when the mods are actually construction loading, etc. on the Mojang screen, but only has this, unspecific one, with the ME System there, and when I remove the ME Controller it stops in the console. Anyway, just in case, here is the console logs: (warning, the error repeats A LOT, not even pastebin could fit it, so I went with tinypaste) http://tny.cz/16bd8e94

**Comment by yueh** [comment]
I do not see anything related to AE2 directly. It looks more like a serious issue with your modpack.
So I would recommend contacting the author of the atlauncher pack.

**Comment by beewyka819** [comment]
I am the author... but how come the error stops when I remove the ME Controller, before I place that down the error never occurs and my framerate is fine

**Comment by beewyka819** [comment]
On google I found something that is titled "Memory Leak in 1.7.10" and I see it mention the error below, will check this out.

**Comment by beewyka819** [comment]
Ah, figured it out, apparently Minecraft Loader has a memory leak with it, so I'll just remove that
