### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by nister6000** [AppliedEnergistics/Applied-Energistics-2#835]
Hello we got crash, i dont know how that happend.

AE version: RV2-BETA 8
Crash report:
http://pastebin.com/V8u1k3kK

**Comment by yueh** [comment]
We do not support bukkit/cauldron. Please try to reproduce it without them.

**Comment by nister6000** [comment]
I will try but i need play around with this, because i dont seen how this happend and where.

And it would be good if cauldron be supported because alot of servers use it.

**Comment by yueh** [comment]
Most mods do not support it, because it can just break or change things unpredictable (similar to optifine).

The only other option I would see, is if you are using EnderIO ME conduits as they are known to be buggy.

**Comment by nister6000** [comment]
I cant reproduce it, so i close this for some time.
When i will know more about this i will open.
