### ISSUE TITLE
Suggestion: Wireless and Sorting 

### ISSUE THREAD

**Issue by Cabius1** [AppliedEnergistics/Applied-Energistics-2#836]
I just have a couple suggestions. Wireless Import and Export Bus, an maybe a wireless transceiver that you can attach ME Network block (Ex: terminal) these would be extremely useful. Maybe the wireless would take more power depending on how far you are transmitting the signal. It would also have channels so you can pick what connects to what.

Another thing is it would be really nice if you could sort mods in your network. Could be something like creating a folder in a real computer, but in the ME computer it would make a tab, you can put any item into a tab that you want and it will always sort to that tab. There could also be preset tabs that you can make like Ores, Ingots,Building Blocks, sort by mod, etc. As an added functionality you could show or hide tabs on a terminal basis. So say I have a room for Ars Magica 2 I could make my terminal in that room that only shows Ars Magica 2 Items. 

Not sure how hard this would be to implement but It would be an amazing feature.

**Comment by yueh** [comment]
1) See #192. But things like wireless export/import buses will probably never happen.
The QNB is your solution, if you need wireless transfer. We might consider some short range connections, but these will probably be fairly limited to not make QNBs obsolete. But see the other issue for more details

2) Look at the [view cells](http://ae-mod.info/View-Cell/), which allow you to filter the items displayed in a terminal. They can be configured in a cell workbench similar to storage cells.
