### ISSUE TITLE
Option to have network wide channels instead of cable-wide/no channels

### ISSUE THREAD

**Issue by Entoarox** [AppliedEnergistics/Applied-Energistics-2#842]
I'd like the option to have channels be a network-wide property, with your controller count controlling how many channels your network supports.

Right now I am playing without channels because the feature I liked most about AE1 (p2p's for fluids & energy) are not compatible with the only way to have "one cable" in AE2 (using p2p & sub-networks)

At the same time, the idea of limiting how much a network can do without proper infrastructure appeals to me greatly, so having this middle-ground option would allow me to enjoy what I loved about AE1 most, without having to take away what I enjoy about AE2 completely.

**Comment by yueh** [comment]
It will not any interesting game mechanics, just put down more controller blocks. Which can easily achieve some 10k channels.

Also it would add some serious issues, even more then disabling channels.
There is a reason why controllers and some cables are disabled in this case.

**Comment by SephirothWS** [comment]
Yes, just right-click the P2P with the appropriate conduit (fluid, energy) should set the type of the P2P to that type...

**Comment by AlgorithmX2** [comment]
Only P2P ME Tunnels cannot transverse P2P Tunnels. Fluid/Energy/Item/Ect, all work over P2P ME Tunnels, so you can use P2P Tunnels to manage those tunnels.

I'm not sure what your issue is with that.

**Comment by Entoarox** [comment]
Oh, I was under the impression that all p2p tunnels had the inability to traverse me-p2p's, my apologies!
