### ISSUE TITLE
upgrade storage sell  to next tire without losing item in it 

### ISSUE THREAD

**Issue by Adnane13** [AppliedEnergistics/Applied-Energistics-2#844]
if you can upgrade 1K storage sell to 4K storage sell it well be easy

**Comment by JelmarG** [comment]
You don't have to lose the items on it, you use an ME I/O Port to export items on a cell to the network (onto other cells). You can't upgrade the cell itself, but you can remove the cell housing to use it again with a bigger storage component.

**Comment by AlgorithmX2** [comment]
Personally not a fan of this, its pretty easy to use the IO Port to empty a cell, and its prevents complication of the crafting handlers and adding recipes that use items that hold items ( this is bad news ).

Also this is akin to taking your hard drive out of your computer, opening it up, adding more platters, and sticking it back in your computer and expecting it to work, and still hold all your data.. something I would never expect to work, physically, or based on the fact that drives have partitions that are based on drive size ( which is changing ).

**Comment by Adnane13** [comment]
That's also is a solution

**Comment by Blarghedy** [comment]
I'm a pretty big fan of being able to increase the tire radius without repercussions, though.
