### ISSUE TITLE
Performance of autocraft requesting (frequent inv copying in MECraftingInventory.<init>)

### ISSUE THREAD

**Issue by vlad20012** [AppliedEnergistics/Applied-Energistics-2#845]
I found that the time required for craft requesting is directly proportional to the number of different items in the grid. Reached the point that one export bus with crafting card requires 18ms per one craft request. And I would not say it's a big grid. I have done profiling and foun a lot of interesting things:
![ae](https://cloud.githubusercontent.com/assets/3221931/6027626/7bd7c7c2-abf4-11e4-9e66-9f3c10b8c299.png)
As you can see, up to 70% of the server load is necessary for item extraction in MECraftingInventory constructing (MECraftingInventory:111). Unfortunately, I can not estimate how much we gain through multi-threading craft model, but I could clearly see how much we lose in the copying of inventory. On every request! I ask the developers to pay attention to this issue, which is already sufficiently felt the my server.

**Comment by yueh** [comment]
#670
