### ISSUE TITLE
Import Bus extracting items out of duplicator

### ISSUE THREAD

**Issue by Moonblaze1995** [AppliedEnergistics/Applied-Energistics-2#846]
I was just playing around with SSP, and was trying to use an import bus, connected to a duplicator to duplicate an item in the duplicator. When I initially insert the item in the duplicator, it doesn't duplicate. I have to interact with the Import Bus itself, remove and reinsert one card (Acceleration Card is what I used to test) it will finally start duplicating.

**Comment by yueh** [comment]
I have no idea what this is. But buses are dynamically adjusting their speed, so if there is nothing to do they will tick less frequently and they can even go to sleep when there are some issues with then inventory they are facing. Changing a card will force it to wake.

**Comment by yueh** [comment]
Closed as no further response
