### ISSUE TITLE
Duping Storage Cells with IO Port and ExtraUtilities Filing Cabinet

### ISSUE THREAD

**Issue by sevs44936** [AppliedEnergistics/Applied-Energistics-2#847]
Setup is somewhat simple, put a number of identical Cells into the Cabinet, if they are truely identical (freshly crafted/contain the exact same Items) they will stack.
Pull from the Cabinet into the IO Port (I used EnderIO Conduits, havn't tested any other transport mechanism).
Wait till the output side of the IO Port is full and some Cell Stacks are in the Input side.
Start pulling Cells out of the Output side of the IO Port. Cells are taken out of Output and are immediatly replaced, the Stacks on the Input don't go down.

Setup:
![2015-02-04_15 11 53](https://cloud.githubusercontent.com/assets/1660297/6041848/54910d4a-ac80-11e4-9acf-ef6d903f1599.png)
Stacked Cells:
![2015-02-04_15 12 25](https://cloud.githubusercontent.com/assets/1660297/6041849/549e66e8-ac80-11e4-9873-4dbc1096cf9a.png)
Stacks in the IO Port:
![2015-02-04_15 12 32](https://cloud.githubusercontent.com/assets/1660297/6041851/54a6c3d8-ac80-11e4-9b33-7ecebcee292d.png)
Many Cells:
![2015-02-04_15 12 38](https://cloud.githubusercontent.com/assets/1660297/6041850/54a59f62-ac80-11e4-971a-e4a6a0eb52af.png)

My gut feeling is the IO Port tries to unstack the Cell Stack, doesn't have enough room in the Output, puts some Cells from the Stack there, but then doesn't decrease the stack count.
I base this on the fact that when I put some speed upgrades in the Conduit pulling from the IO Port, this doesn't work anymore.

Found this first on a custom Bevos Tech Pack Server, reproduced on a striped down install with these mods:
forge-1.7.10-10.13.2.1236-universal.jar
CoFHCore-[1.7.10]3.0.0B8-36.jar
extrautilities-1.2.1.jar
NEIIntegration-MC1.7.10-1.0.1.jar
appliedenergistics2-rv2-beta-8.jar
CoFHLib-[1.7.10]1.0.0B7-29.jar
NotEnoughItems-1.7.10-1.0.3.73-universal.jar
MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar
CodeChickenCore-1.7.10-1.0.4.29-universal.jar
EnderIO-1.7.10-2.2.7.325.jar
neiaddons-mc1710-1.12.3.11.jar

**Comment by yueh** [comment]
For now I assume it is an EnderIO issue, maybe in combination with XU.

Cells have a stacklimit of 1, so even empty ones should never stack. If some mod decides to ignore this and create invalid stacks, then except it to break.

**Comment by sevs44936** [comment]
For reference, issue is with EnderIO, see: https://github.com/CrazyPants/EnderIO/issues/1630
