### ISSUE TITLE
Export bus high CPU load

### ISSUE THREAD

**Issue by justin2108** [AppliedEnergistics/Applied-Energistics-2#850]
almost 30% CPU time goes to the ExportBus asking for a crafting job.
Even when players are offline the ExportBus is keeping the server busy.
And yes all chunk loaders are disabled.

This happens only when a players has logged in and logged off.
On a server reset the cpu sits idle at 5% and RAM +- 1G

Here's a link to a screenshot i took http://postimg.org/image/5sutm10mt/
It shows with WarmRoast what hogs the CPU.

But this doesn't stop, because the ExportBus is asking for cpu time chunks in that area will never unload.
What causes a memory leak over time.

ow yeah btw 
running Java8 64b JDK
and the latest AE2 beta (Stable 1 has the same result )

**Comment by yueh** [comment]
#670
