### ISSUE TITLE
NEI vs RV2 Bld8 - NEI 'Usage' Crash

### ISSUE THREAD

**Issue by jester1147** [AppliedEnergistics/Applied-Energistics-2#856]
We have a custom mod pack, and we just went through and updated a number of our mods (we were on RV1 of AE2).  

We had an existing issue with Ender IO v. AE2 with ME Conduits.  Our fix was to update to the latest version of AE2 and Ender IO.  We updated to RV2 Build 8 however this brought about a new problem that was ONLY resolved by reverting to build 7.  

Whenever we would check the usage of an item (the magical 'u' key for NEI) we would get a crash. After stripping all of the mods to their previous (stable-ish) versions, we proceeded to rebuild piece by piece until we found AE2 to be our culprit.  

With some research, we found other mods causing similar issues (Rotarycraft, Qcraft, etc) but none of these are on our pack.  So currently, we are working with Build 7 until any more light can be shed on the subject.  

Any help on the matter would be appreciated. 
-Jester

Our modpack listing can be found here:
http://www.atlauncher.com/pack/Psytech
A copy of the pastbin for the crash can be found here:
http://pastebin.com/nRcgMbPN

**Comment by yueh** [comment]
This is an OpenComputers issue. They are using internal classes instead of the API, so it is expected that an update will break it.

**Comment by jester1147** [comment]
So would there be an easy fix to this? Well, short of getting rid of OC (lets face it, we are keeping AE2 and NEI lol)

**Comment by yueh** [comment]
Updating might be an idea.

**Comment by jester1147** [comment]
Fair enough, will test it out and respond here.  Thanks for the prompt response!

**Comment by jester1147** [comment]
Simple fix... thanks!  I will make sure this gets updated in our pack!
