### ISSUE TITLE
GUI of Wireless terminal flashes shortly on right-click when wireless terminal is unlinked

### ISSUE THREAD

**Issue by RAnders00** [AppliedEnergistics/Applied-Energistics-2#861]
I reported this issue a while back, but back then it was closed and commented as "not valid", but it is a valid bug.

If you spam-rightclick a **charged** and **unlinked** wireless terminal, you will sometimes see a terminal interface flash up for a short moment and close immediately again. I assume there is a check missing for a existing link?

Also as it is opening a GUI every single time key pressings are cancelled (press shift while you spam, you will un-crouch whenever you click because a GUI opens and crouching stops working. Also try walking a rightclick, you will stop)

All demonstrated here: https://www.youtube.com/watch?v=wpa-C-428y0

AE [rv2-beta-1](http://prntscr.com/6249rd)
Forge [10.13.2.1272](http://prntscr.com/6249xm)

**Comment by yueh** [comment]
This can probably happen on a high latency.

I could add a small check for a linked (and not empty) wireless terminal.
But I am not sure, if there is an easy way to invalid an already linked one. Say in case the security terminal was broken/replaced. Same for out of range checks.

**Comment by RAnders00** [comment]
You could make it so that it:

-          When the wireless term is unlinked, the GUI will not open on the client.

-          When the terminal is linked, a request is sent to the server. The server answers with a true/false whether a GUI may open.

 

A GUI should open when:

-          The security terminal exists, regardless of “Device missing channel” or “Device offline”.

-          If there is no security terminal there, the GUI shall not open.

-          If the system is out of power, the terminal should open anyways.

 

Here is it visually represented (this is what I actually mean, in case I derped up my text):

![visual representation](http://i.imgur.com/OSz6qLi.png)
