### ISSUE TITLE
AE2 Rv2 beta build 8, Crash on clicking item in terminal

### ISSUE THREAD

**Issue by Sparky24** [AppliedEnergistics/Applied-Energistics-2#862]
Clicking on a terminal is fine, you can scroll through and view items, however, clicking on an item seems to crash the client and kick you off the server.

Pastebin attached if of any use.

http://pastebin.com/B3bJGz3z

Many thanks

Sparkz

**Comment by yueh** [comment]
Sorry, but no support for cauldron.

**Comment by Sparky24** [comment]
Ah yes, my bad! Tested in single player, works fine. My apologies. Thanks for the quick reply!
