### ISSUE TITLE
Request: P2P/Pipe functionality for Import/Export busses

### ISSUE THREAD

**Issue by Cornflakes91** [AppliedEnergistics/Applied-Energistics-2#863]
may i ask for a small thing?

maybe import/export busses could behave like itemducts BC pipes if they have no inventory to access.

for smaller, controllerless (sub) networks it could behave like a single line of connected pipes
just plug and play

for controller based networks a mechanic like P2P tunnels could be used
"connect" the busses you want to behave like a pipe network with a memory card

and have the items transported through there never touching your storage cells.

as a limitation could the connected busses require direct channels to each other and not to the controller.

yes? no? maybe?

**Comment by yueh** [comment]
Already possible.

**Comment by Cornflakes91** [comment]
may i ask: how?

just tried with the current non-alpha build and i couldnt find out a way to use import/export busses without an inventory bus / storage cell / ME chest inbetween

**Comment by RAnders00** [comment]
Item P2P is the answer to your question - it has one input and an unlimited amount of outputs. [Read more](http://ae-mod.info/P2P-Tunnel/)

**Comment by yueh** [comment]
No, I did not consider p2p as solution.
Just the normal parts like import buses, storages buses or interfaces.
