### ISSUE TITLE
Wrong Calculation of Power in Network Tool

### ISSUE THREAD

**Issue by farodin91** [AppliedEnergistics/Applied-Energistics-2#865]
These power showed in the Network Tool, only the right power are used. 
If you use two Energy Acceptor in the some chunk. One is directly connected other is connected over a Quarz Fiber. 

Normal Power Usage 22EU per tick
With 2 Energy Acceptor 230EU per tick.

Version: rv1.stable build 1

**Comment by yueh** [comment]
Please update to the latest version and try again.
We sadly cannot support rv1 at all.

**Comment by yueh** [comment]
Closed for inactivity.
