### ISSUE TITLE
TE Machine Frame being deleted from Network (more details inside)

### ISSUE THREAD

**Issue by Erelaszun** [AppliedEnergistics/Applied-Energistics-2#866]
Repeatable Test:

I have a Machine Frame (Resonant) from TE In my network.

I go to a pattern terminal, pick ANY of the TE Machines that can use the Resonant machine frame, and search for it in NEI, I bring up the recipe, shift-click it into the pattern terminal, it places the ghost of the Machine Frame into the pattern terminal... but the item itself is removed from my network. 

Tested this on multiple networks on the server currently.

AE2 rv2,beta Build 8
Thermal Expansion 4.0.0B8-23
CoFH Core 3.0.0B9-40
CoFHLib 1.0.0B8-34
NEI 1.0.4.83

**Comment by yueh** [comment]
Cannot reproduce with the listed mods. Maybe something else interfering with it?

**Comment by Erelaszun** [comment]
going to use logs to get a list of all mods we use

**Comment by Erelaszun** [comment]
http://minecraft.csyne.com/ae2-debug.zip

Here is a zip of not only all mods we are currently using, but all configs as well...

**Comment by shobu9** [comment]
Strange ... i could reproduce it  but it looks like it doesn't happen to everywone ,,, After Reloading the World i had more luck tough , which it would actually craft it

**Comment by yueh** [comment]
Please reopen, if you can provide a reliable way to reproduce it.
