### ISSUE TITLE
Spatial IO: dense energy cable channel mismatch

### ISSUE THREAD

**Issue by Damit84** [AppliedEnergistics/Applied-Energistics-2#869]
Playing on DireWolf20 1.7.10 v 1.0.3
Mod Version: appliedenergistics2-rv2-beta-1

Bug / questionable behaviour:
I'm using a me controller as my base to build a spatial IO system. Every side on a controller should support 32 channels.
Using a normal smart cable activates the main pylon & 7 side pylons (8th side pylon in the upper right is off, because of missing channel.) -> Everything OK.

Replacing the smart cable(that connects the main pylon with the controller) with a dense cable will not activate the 8th pylon. Looking at the channel usage shows different count of channels entering and leaving the dense cable.

Please see attached screenshots.

Layout of my testbuild
![layout_smartcable](https://cloud.githubusercontent.com/assets/8322579/6096893/ff6e5356-afa7-11e4-881e-e5f5d52bbf90.png) 

Closeup of the smartcable. (Channel usage)
![closeup_smartcable](https://cloud.githubusercontent.com/assets/8322579/6096892/ff68a3ac-afa7-11e4-8224-7990c9be9153.png)

Closeup of the dense cable(Channel usage))
![closeup_densecable](https://cloud.githubusercontent.com/assets/8322579/6096894/ff722c7e-afa7-11e4-914f-95b0793dac88.png)

**Comment by yueh** [comment]
Working as intended. Only dense cables, p2p and QNB are transfering 32 channels at once. Nothing else. You can also notice it as the connection to the pylon is only a smart one.
