### ISSUE TITLE
Portable Cell [Upgrade Idea's]

### ISSUE THREAD

**Issue by kurokuno** [AppliedEnergistics/Applied-Energistics-2#870]
so i had some random thoughts on this i understand if there all shot down but still just felt like dropping them up here hope that is ok rather than thinking of bigger cells or more complicated cells i was just thinking of function's

idea 1 cell types example
1: combine portable cell with import bus to get importing Cell auto pulls the items set in a cell work bench from the players inventory
2: combine Cell with Export Bus will automatically push as much of the items stored/set as possible into the players inventory
3: combo cell export bus + storage bus with a cell to make it keep the specified amount of items in the players inventory
4: all of the upgrades on a single cell again the limiting factor of the upgrades would be the cells storage limitations and the power usage going up of corse

idea 2 card upgrade's
1: capacity card would increase the AE power storage of a cell when installed < was mostly thinking of this as a way to offset having say import/export/bus cells use power when doing there thing of course no where near enough to make it stupidly efficient or anything
2: acceleration card will make the cell import/export/bus faster with the players inventory

**Comment by shobu9** [comment]
Wouldn't that break the hole purpose of Drives?

**Comment by kurokuno** [comment]
well portable cells are very small in nature so i fail to see it breaking much and i had remembered reading that Algo had plans of making upgrades but never go to it

**Comment by shobu9** [comment]
Hum you are probably right, tough it migth make some other mods useless if thoses kinds of cell Appears. Alot of other mod creators are beeing ditched just because there's something else elsewere...

**Comment by Deshiba** [comment]
The first part is allready on #33

**Comment by Technici4n** [comment]
Sounds like a cool feature, but I don't think we are ever going to implement it due to limited manpower, having to figure out a nice config GUI, etc. Can happen in an addon or a PR though.
