### ISSUE TITLE
Applied Energistics causing a crash

### ISSUE THREAD

**Issue by teamminecraftash** [AppliedEnergistics/Applied-Energistics-2#871]
Im making a modpack and including AE2 in it. When I start, the game crashes and says that AE causes the crash. I have tried removing AE2, but it wont work. Here is the crash log:http://pastebin.com/gW0Zc0Fe. I am using 1.7.10 in rv1.stable build 1. The crash occured on startup of my Minecraft

**Comment by yueh** [comment]
ExtraCells issue, not directly related to AE2
