### ISSUE TITLE
Grinding sound for grindstone

### ISSUE THREAD

**Issue by rebio** [AppliedEnergistics/Applied-Energistics-2#872]
Pretty easy and simple idea: A 'grind' sound for the grinder.

I have prepared some sound files and a video, but github writes "Unfortunately, we don't support that file type. Try again with a PNG, GIF, or JPG." So no ogg and mp4 files in here.
They can be found on http://www.mediafire.com/download/zcbb6dsinymz5nu/grindstone_sound.zip

The sound files are not like a continuous stream, but one sound for every rotation. I also have some recordings with a continuos grind sound but did not cut or test them. I made 12 so that there are +50% of how many rotations (8) you need to grind one block so that it's not that much likely that you here the same sound twice while grinding one block. From what I saw I think the grindstone takes 0.9 seconds for one rotation. So the sound files are 0.9 second as well.

The files are encoded in the best ogg quality my system can deliver and I still have the wav files in case somebody wants to reencode them. It is also possible to get eg. 0.8 sec or 1 sec long sound files.

Edit: I saw that the AE2 textures and block models are licenced under CC-BY-NC-SA 3.0. My files can be used under that licence as well.

**Comment by thatsIch** [comment]
Did you actually overlay them to the video or implement it already?

**Comment by rebio** [comment]
I wish I was that good and could do it, but no: Just a video and placed the sounds in there, so sorry.
Since I don't really like the way how the 'tiled' sounds work together I will try a way with a continuous sound.
If the project is interested in my files it would be nice to tell me the exact length for one grind operation so that I can make them exactly that long...

**Comment by thatsIch** [comment]
Actually there is no set grind time set. Any item can register with a specific time needed in the grinder, so some stuff can take up to 10 seconds and other only to half a second.

**Comment by rebio** [comment]
That is not ideal for a sound...
However, I guess it would not be that much of an issue if the sound is eg. 0.5 seconds longer than the grinding time. So I could make sound files which are 1 second long and they could be played one after the other (even I need to test how the sound and visuals would work together if the sound is longer than the operation time).
Another thing which I thought about was maybe something like a 'warm up' and a 'cool down' part where you hear a difference between the start, the actual grinding and the end (eg. Fading in/out sounds, if the sound get's deeper or stays on that level, etc.)  Not sure how hard it would be to program, but it could may work like that: If the player clicks on the grindstone for the first time for the operation it starts playing the 'warm up' sound. if the player right clicks before the operation is done it could play one of the middle sounds. if it would be the last operation for this block in the grindstone a cool down sound could be used.

Just for info: what do you think about the sounds are they OK or should they be more of the same tone (like the difference from the deeper to the higher sounds shouldn't be that big, etc.)

**Comment by thatsIch** [comment]
I do not like the deeper versions.
I think the second "turn" was the best one.

**Comment by thatsIch** [comment]
Just to say, I am really not good with sound effects, I think AE2 is pretty much soundless besides the TinyTNT?

**Comment by rebio** [comment]
In that case I will try to optimise the sound and get it ready to use as fast as possible...

I will also have a look at Issue #89 drives give a server sound

**Comment by rebio** [comment]
Arrrg! No pm on github :-/
Then that way: Hey thatsIch: How can you include sounds into minecraft?
The problem I have is this: I can make exactly 1 second long files. But if you play them you hear a click at the end. I can make the file 1,1 sec long, but then you would hear this 'tiled' thing again if you play them one after the other. Can you code the audio thing that way that it start's a sound and after one second it starts the next one even the first one isn't finished?

**Comment by thatsIch** [comment]
1. no, I dont know what you mean with the click
2. sounds much better to me, I think I would take this. I have yet to work with Minecraft Sounds, but I do not see any way to stop a played sound if executed. Need to look further into this.

**Comment by rebio** [comment]
I finally had time to finish the grindstone sounds. In sum there are 3 start sounds, 3 end sounds and 30 middle sounds. I made that many so when you use the grindstone it's unlikely to hear the same sound twice while grinding 3 iron ore. (8 turns per ore would result in 24, but I had some recording material left and tried some different sounds to change it a little bit).

Now how including the files was meant to be:
You have a (random) start sound which would be played with every first turn of the grindstone. So when you right click it once, wait and click again it would play the start sound again. If you keep right clicking and there is still something to process inside the grindstone it would play a (random) middle sound up next. If there is nothing left to grind in the grindstone and if it's the last turn it would play a (random) end sound.

In my first post I wrote that the grinding seems to take 0.9 sec per rotation, so 6,3 seconds for iron ore, which would be very bad for a sound that is designed to be played 1 sec. If the sound is started every 0.9 sec it sounds like this: http://www.mediafire.com/listen/t5r4vif90c3tods/AE2+grindstone+sample+new2.ogg
Not bad I would say...

Now the important part: How should I send the files?

1) If the level of the recording 'drops' (because the recording has been cut) you hear a 'click' sound at the end of the file which I tried to avoid in the final audio. In my tests it seems that you wouldn't hear the sound in MC anyway, but I wanted to be on the safe side...
2) Nice to hear that it sounds better. I tested this whith doors (I simply used the grindstone sound in a resource pack) and it worked pretty fine (and as you said) once the sound started to play it was not stopped.

**Comment by yueh** [comment]
I am not sure, if it is even possible to overlap multiple sounds correctly. I remember that vanilla minecraft changes the speed of sound effects slightly to change the pitch slightly and make them not sounding monotone. It could be optional, but there is at least a chance that we can have issues with it.

**Comment by rebio** [comment]
The short answer yes you can overlap sounds. Yes MC changes the sound up a little bit, but that's not a problem. You can have a look at http://www.mediafire.com/watch/8zvxg37tdoxgfup/grindstone_sound_preview-door.mp4 (I recommend to download the file to your system, because the online version has not a good video quality). You can hear that it would work with MCs standard sound engine in 1.8.4 just fine. I replaced the open and close sound of the wooden/iron door with the grindstone sound.
a) "1" is the first sound, "2" is the second which is used (close and open sound)
b) wooden door to show how vanilla MC handels the sounds and that sounds can overlap each other.
c) showing the sound on an iron door with a lever
d) the sound played with 3 RS ticks delay
e) the sound played in a pulse mode
f) the sound played with 9 RS ticks delay
g) the sound with 10 RS ticks delay

IMPORTANT NOTE: The sound level is not representative. d) and e) are showcasing that sounds do overlap, but do sound terrible as actual block sound itself. f) or g) would be the sound to use and even the tick delay is different the same sound works for both. Just imagine that you would right click a grindstone and it would play the sound instead of open/close a door.

**Comment by rebio** [comment]
It has been 3 months now and the files are lying on my HDD.
Is it worth to keep them an include them with a pull request of a fork?

**Comment by rebio** [comment]
While cleaning up my PC I discovered that the files still exist in some folder.
What are the plans for sound in AE now? Are the files obsolete or will there be no files in AE in general...?

**Comment by thatsIch** [comment]
Just other priorities atm. If you want, you can provide them somewhere "persistent" and we can use them, when we are ready
