### ISSUE TITLE
How to disable channels 

### ISSUE THREAD

**Issue by MarshMilo100** [AppliedEnergistics/Applied-Energistics-2#873]
I have looked through the config files and the whole minecraft instance, but I cannot find out how to disable channels in ae2. I would just like to play for a while with channels disabled and see how well it plays. I am using minecraft 1.7.10, Forge 10.13.2.1236, and ae2 rv2-beta1

**Comment by shobu9** [comment]
Do in the .txt config folder control F then Type *channel you should see frther down a config for it 
tough be advised it will also take out the controller the smart and Dense Cables and anything cable channel related!

I'd say you should learn them!

**Comment by Entoarox** [comment]
the option to disable channels was added in a later release, try using the latest release (beta8, unless they in the last 72 hours released a new one), the option to disable channels should show up in the config.
