### ISSUE TITLE
Lag spike everytime AE2 updates.

### ISSUE THREAD

**Issue by halvors** [AppliedEnergistics/Applied-Energistics-2#874]
Lag spike everytime AE2 updates. I don't know how often this happends, seems to be every 30 seconds or so.

The problem is that it updates all the cables/storage etc, then the hole server freezes for 5 seconds, then it runs again and the rest of the cables/storage is updated.

Here is a VisualVM Profiling of my server: http://halvors.org/downloads/Applied%20Energistics%202.nps

I don't know that's causing this lag, but this shouldn't really happend.
See middle of this log output (Using UpdateLogging option in config file).

```
[23:24:00] [Server thread/INFO] [AE2:S/]: appeng.tile.storage.TileDrive @ -166, 73, -48
[23:24:00] [Server thread/INFO] [AE2:S/]: appeng.parts.layers.LayerIEnergyHandler_TileCableBus @ -166, 73, -47
[23:24:00] [Server thread/INFO] [AE2:S/]: appeng.parts.layers.LayerIEnergyHandler_TileCableBus @ -166, 73, -47
[23:24:00] [Server thread/INFO] [AE2:S/]: appeng.parts.layers.LayerIEnergyHandler_TileCableBus @ -170, 73, -47
[23:24:00] [Server thread/INFO] [AE2:S/]: appeng.parts.layers.LayerIEnergyHandler_TileCableBus @ -170, 73, -47
[23:24:04] [Server thread/INFO] [AE2:S/]: appeng.parts.layers.LayerIEnergyHandler_TileCableBus @ -165, 65, -62
[23:24:04] [Server thread/INFO] [AE2:S/]: appeng.parts.layers.LayerIEnergyHandler_TileCableBus @ -165, 65, -63
[23:24:04] [Server thread/INFO] [AE2:S/]: appeng.parts.layers.LayerIEnergyHandler_TileCableBus @ -170, 63, -59
[23:24:04] [Server thread/INFO] [AE2:S/]: appeng.parts.layers.LayerIEnergyHandler_TileCableBus @ -165, 65, -64
```

Hmm, may there be a Forge Multipart issue here? What happends when this code runs https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv2/src/main/java/appeng/tile/networking/TileCableBus.java#L138 and it is surrounded by Forge Multipart blocks?

**Comment by halvors** [comment]
Here is a VisualVM Profiler snapshot of my server: http://halvors.org/downloads/Applied%20Energistics%202.nps

**Comment by yueh** [comment]
I do not see anything particular related to AE2 and a performance issue.
The time spent in AE2 functions is mostly because it is accumulating time spent in mekanism (mostly its power system)

**Comment by halvors** [comment]
Hmm. Aa you in the logs it just stops for 4 seconds. Removing AE2 solved the issue. But who wanna do that :-) I think AE2 eventually messes up the connection. All i know is that the logs stops in the middle of cablebus updateing.

I've tested with just Mekanism works great. Adding AE2 and the lag begins.

Do you have any idea whats causing the issue? May there be a bad tileentity that stops the AE2 updating for some seconds? Is AE2 updates happend periodically in time span around 30 secounds between?

**Comment by KlutzLament** [comment]
Have you tried it without Mekanism?

**Comment by halvors** [comment]
You mean that Mekanism is the issue? Why would it be? And is it Mekanism that messes up AE2 or AE2 that messes up mekanism?

**Comment by TheJulianJES** [comment]
#893

**Comment by halvors** [comment]
Could someone please explain to me exactly how mekanism is responsible for this? Anyone know of any way to fix this?

Should this be submitted as a bug at the mekanism bug tracker? Or is it already?

**Comment by yueh** [comment]
Because the profile says so. The cpu spends the majority of the time calculating some mekanism energy. Even part which starts with ae is finally just spending time in mekanism code. (Event Processing)

**Comment by kevinkk525** [comment]
I do not know whether my problem is exactly the same but I'm ready to test that and I will share my experience:
Like you said I had lag spikes almost every 50-120s of about 1-3s length but our server is in testing phase so only 3 people are building something. After removing my old AE base that was built across 4 chunks (without quantum rings) to a new location and building it inside only 1 chunk, the lag spikes were less frequent.BTW: All of these chunks were chunkloaded. Then I checked all other ME networks I have and after replacing the remaining cross-chunk networks with quantum rings the lag spikes reduced to around 1-2s every 4-5min. Probably that could be lowered, I do not know what machines the other 2 player have inside there homes (but probably almost nothing).

**Comment by yueh** [comment]
There are similar issue on the mekanism tracker, closing it for now.
