### ISSUE TITLE
Energy Acceptor Issue

### ISSUE THREAD

**Issue by 8nothing** [AppliedEnergistics/Applied-Energistics-2#875]
For the past few hours, I've been having an issue with the energy acceptor. So basically, when I first got the mod, I wanted to see if it worked properly. I went into a single player world, and eventually wanted to test the energy acceptor. I made a simple circuit that involved an ic2 generator filled with coal to connect to a HV cable running into an acceptor. The acceptor then is next to a dense energy cell. It worked, and I moved on. However, when I started up my private server so that my firends and I can do survival, I made the exact same circuit. This time it didn't work. It pulled energy, but did not store AE in the energy cell. This means ic2 is sending energy, but the energy acceptor is not recieving and/or sending it to the energy cell. I wired everything up correctly, and used buildcraft kinesis piping for a more visual representation. If you want more information, let me know.

**Comment by TheJulianJES** [comment]
AE2 Version, Forge Version? Setup Screenshots?

**Comment by 8nothing** [comment]
Actually as it turns out, the server doesn't sync with my client correctly. So, it displays 0 when really it's getting the energy it needs. Sorry for the trouble.
