### ISSUE TITLE
Idea: Thicker cables and sub-controller

### ISSUE THREAD

**Issue by NationTec** [AppliedEnergistics/Applied-Energistics-2#877]
I wish to have thicker ME-Cables. My idea is, the thicker cables have 128 or more channels and can only connect to the controller and to a sub-controller. So i can make a infrastructure like a telecommunication network. 

For example:
Controller - 128 channel cable - sub-controller - dense cable - glass cable - interface

I hope you like my idea.

PS: Please excuse any spelling errors or grammar errors, I'm from Germany and my english is not the best.

**Comment by yueh** [comment]
How does this add something new compared to the already existing P2P tunnels?
They allow you to transfer 1024 channels over a dense cables and you could consider the controller of the underlay network as subcontroller.

**Comment by Entoarox** [comment]
@yueh It would make it much easier to identify how the connections are setup, especially since p2p's do not properly identify how many channels are actually being used.

**Comment by KlutzLament** [comment]
Connect a dense cable to the tunnel, that will show you how many channels are in use. Also, if you want multiple controllers you can use sub-networks.

**Comment by yueh** [comment]
@Entoarox so essentially nothing new? P2P are providing tunnels, but they do not care/know about the amount of channels going through them. It is not really their job to validate the network they are transmitting. It is just transmit that network, even if it is an invalid one.

As @KlutzLament already said, if you want to monitor it better, put a dense cable between the controller and the tunnel. The option is already there.
