### ISSUE TITLE
Idea: Multiple controller entities on a single network

### ISSUE THREAD

**Issue by hemu1** [AppliedEnergistics/Applied-Energistics-2#878]
I noticed a lot of the ideas behind AE and AE2 reflect on networking topologies. So, where did the decision to make only one controller per network come from? 
     If we take the analogy of a controller as the router, and channels as IP addresses, the problem of limited addresses was solved by installing a router with a NAT. 
     I think allowing to place another controller anywhere on the network where more channels are needed would be useful. The controller can have a designated "in" side and five "out" sides. The "in" would act as a single channel, while routing the 32*5 channels of other sides through it.

**Comment by KlutzLament** [comment]
If you want to have multiple controllers use sub-networks.

**Comment by yueh** [comment]
Except that AE2 is in no way designed like normal network.
SCSI is your option, if you want to compare it to something real.

**Comment by hemu1** [comment]
Thanks for pointing me toward subnetworks. That and the interface + storage bus connection to the main network was exactly what I was looking for.
