### ISSUE TITLE
[rv2.beta7] appeng.me.GridException: Connection already exists.

### ISSUE THREAD

**Issue by Fogger** [AppliedEnergistics/Applied-Energistics-2#879]
Suddenly, the server won't start, crashing at world load.

Crashlog: http://hastebin.com/aliwapudod.1c

**Comment by yueh** [comment]
Are you by any chance using EnderIO ME conduits?
If so, could you remove them? (Backup your world + remove EnderIO)

**Comment by Fogger** [comment]
ok, to update, we found that the error was coming from one of my Crafting CPU's, which was adjacent to 2 EnderIO Energy conduits.
![Where it used to be](http://i.imgur.com/tbSnKEc.png)
I will retest with removing only the conduits & return with my findings.

**Comment by yueh** [comment]
I also got a second report of it. Both are indicating EnderIO as issue.

**Comment by Fogger** [comment]
First I tried removing the conduits from the area, still crashed, so then I removed the EnderIO mod completely, still crashed..

**Comment by Fogger** [comment]
I removed the CompactMachines mod too, which was the other adjacent non vanilla blocks and it no longer crashed.

So I'll take it up with the dev there, but it isn't going to be easily reproducible, since these have been sat in this configuration for weeks, but only now suddenly hate eachother..

**Comment by yueh** [comment]
I did not really notice CompactMachines (or that they have an AE2 integration. It is not used that often).

I have not looked how they implement the integration. The Grid itself is constructed randomly, so it might be important in which order the devices come online to crash. Maybe even an interaction between EnderIO and CompactMachines in a specific order.

**Comment by nister6000** [comment]
The same crash btw.

https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/835
