### ISSUE TITLE
Spatal storage not working

### ISSUE THREAD

**Issue by CreeperHater2435** [AppliedEnergistics/Applied-Energistics-2#881]
I have bult a 16x16x16 SCS and have a online controler,a creative energy cell powering it,1 extra channel but it doesn't work. I give the spatal i.o. port a redstone signal and nothing happins. I have a 3x3 of vanilla grass blocks inside the SCS. Please help!

**Comment by acters124** [comment]
make sure all of the spacial pylons are connected to the controller and none are red.
pics of set up?

**Comment by yueh** [comment]
Closed for inactivity.
