### ISSUE TITLE
Spatial storage issue 1.7.10

### ISSUE THREAD

**Issue by pyrokilr18** [AppliedEnergistics/Applied-Energistics-2#883]
Hello I am having an issue with spatial storage in AE2. I am very familiar with how AE1 works with spatial storage so I thought it wouldn't be too much different with AE2. However, what I am trying to do is move a fortress from the deep dark from Extra utilities, to the overworld. Now I was able to accomplish this in AE 1 so I assumed it would work in AE2. So I was able to capture the fortress into a spatial cell but when I setup the SCS in the overworld with the exact same dimensions as the one I captured it with, it doesn't seem to want to reappear. I know the issue isnt with power or channels because the SCS is all purple. Ive attached some pictures of my spatial I/O port GUI with the cell information along with my SCS setup. I've changed the SCS several times to see if the dimensions were wrong but I had no luck. Am I missing something here or what? It would help alot if the mod would have verification in the spatial I/O port to let people know that thier SCS is setup correctly and is compatible with the spatial cell before powering and giving it channels. Any help would be strongly appreciated.

![2015-02-11_13 22 43](https://cloud.githubusercontent.com/assets/10963804/6153310/c3a8bcb6-b1f1-11e4-8074-8c27da6a9a50.png)
![2015-02-11_13 22 02](https://cloud.githubusercontent.com/assets/10963804/6153308/c3a889c6-b1f1-11e4-9198-61f7a132a824.png)
![2015-02-11_13 22 27](https://cloud.githubusercontent.com/assets/10963804/6153309/c3a8b57c-b1f1-11e4-8225-bcf02372adab.png)
![2015-02-11_13 23 13](https://cloud.githubusercontent.com/assets/10963804/6153311/c3a96c92-b1f1-11e4-911d-36aa9e723cca.png)
![2015-02-11_13 21 47](https://cloud.githubusercontent.com/assets/10963804/6153312/c3aa6ae8-b1f1-11e4-820a-65a3d82b4479.png)

**Comment by yueh** [comment]
As the size is not a square, did you account for the correct orientation?

**Comment by pyrokilr18** [comment]
yes the fortress entrance was on the right face of the structure relative to my I/O port setup so I made sure it was setup the same way as capturing it.

**Comment by KlutzLament** [comment]
And was that face the north, south, east, or west face? Which is it now?

**Comment by pyrokilr18** [comment]
it was on the east side

**Comment by KlutzLament** [comment]
Is it now also the east side?

**Comment by pyrokilr18** [comment]
the second picture is the side with the entrance Im talking about, if your implying that the orientation could be the issue, I could try moving the I/O port setup to a different side? is the spatial I/O port supposed to be directly connected to the SCS? cause mine is connected to the energy cells. Ill add any more pictures later if anyone needs them.

**Comment by yueh** [comment]
Not the orientation of the IO Port, the whole SCS.
If the longer side was oriented east/west, it also needs to be the same in the overworld.

**Comment by pyrokilr18** [comment]
Thanks guys, I finally got it to work. I checked the directions, the one side was 35 blocks width North/South in the deep dark. Then the overworld, it was going east/west so that was the problem.
