### ISSUE TITLE
Items with wrong NBT dont insert in to inscriber

### ISSUE THREAD

**Issue by AYuPro** [AppliedEnergistics/Applied-Energistics-2#885]
Some mods add own NBT tags to gold ingots, diamonds etc. 
When i use these items to create chipsets, i can't put those in inscriber.

This bug work in the TolkienCraftII modpack.

**Comment by yueh** [comment]
The slot used for gold/diamonds has no limitations at all. So there is no reason on AE2 side to prevent them from being inserted.

The recipe is probably not recognizing them as valid materials. As adding random NBT data will make them totally new items.
But this is probably an issue, which is better handled by the modpack. Like adding the correct recipes.
There is just no way we can imagine every possible option another mod can use to break something on our side and prepare a workaround for it.

**Comment by AlgorithmX2** [comment]
@yueh actually ignoring NBT on recipes like this makes sense, because you can add NBT using an anvil or a inscriber, so its technically a vanilla/AE2 feature as well.

**Comment by yueh** [comment]
Making an exception for named item is a valid enhancement. But this uses a known NBT tag.
I might be wrong here, but could ignoring a random NBT tag not be ignoring the difference between a oredict gold ingot and an oredict diamond? Or is it not possible to store this type of information in an NBT tag, only metadata (but then 1.8 removes the metadata?)

**Comment by AlgorithmX2** [comment]
I'm pretty sure that 1.8 removed block metadata, not item damage ( item metadata ).

Based on Forge, the OreDictionary dosn't support NBT Differentiated items, only itemid/damage.

Source:
https://github.com/MinecraftForge/MinecraftForge/blob/072aca43505001650e18169346590edc072af1d3/src/main/java/net/minecraftforge/oredict/OreDictionary.java#L413

**Comment by AYuPro** [comment]
Thanks for the explanation
