### ISSUE TITLE
Connecting a ME Conduit to an interface crashes the client

### ISSUE THREAD

**Issue by kennehisftw** [AppliedEnergistics/Applied-Energistics-2#888]
http://paste.ee/p/T97v8

I wasn't sure if I should post it to this issue tracker or the EnderIO tracker, so I did both.

**Comment by yueh** [comment]
Very likely an EnderIO issue.

**Comment by kennehisftw** [comment]
Yeah, from the EnderIO tracker I was informed that the version of AE2 I was using was not supported.
