### ISSUE TITLE
Portable cell dupe

### ISSUE THREAD

**Issue by Phyn** [AppliedEnergistics/Applied-Energistics-2#889]
Using the latest beta build, a portable cell can overwrite another portable cell if there is enough lag to switch items between activating the source and the GUI opening.

**Comment by RAnders00** [comment]
!! This is HIGH priority !!
The Dupe does indeed work (just tested and recorded it) when the server lags (e. g. generating new chunks)

See this: https://www.youtube.com/watch?v=bgY_zSjtBVk

**Comment by RAnders00** [comment]
@thatsIch @yueh @AlgorithmX2

**Comment by yueh** [comment]
I will not have time before next week to look at it and it will probably require a rewrite how AE2 handles GUI in general. (also improving the integration for addons). So it might take a while.

If someone can provide a relative easy fix, I should have time to review and merge it.
