### ISSUE TITLE
Where are the terminal blocks?

### ISSUE THREAD

**Issue by Malakai030** [AppliedEnergistics/Applied-Energistics-2#892]
I know its not a technical issue, it's an aesthetic one. I do like the new compact monitors, but I roughly miss the old ones as an alternative.
With the new ones it is impossible to hide any cabels behind the monitors as the monitors dont fit the block size anymore and hollow covers have a hole too small for the monitor.

This is bad if you want a clean, modern room without any cables to be seen, just you and the monitors.

This wouldnt matter if the system would only stand in my cellar, but I want acces to it from my work room, and my work room is always clean and beautiful, with no cables, no holes, no cobblestone and stuff, just lamps, buttons and monitors. Not even levers, because they are ugly ;)

So please bring back the old terminals as ALTERNATIVE way to setup the look of your ME system, pleeeeeeeze!

**Comment by yueh** [comment]
Use facades?

**Comment by Entoarox** [comment]
you can use cable facades or multipart strips to fill in the empty space around the terminal (personally I recommend using facades, because interactive multiparts are known to be slightly laggy, so having a lot of them is not really a smart thing to have)
