### ISSUE TITLE
ME IO Port does not work

### ISSUE THREAD

**Issue by SadGhoster87** [AppliedEnergistics/Applied-Energistics-2#894]
It is doing nothing:
![2015-02-14_16 48 42](https://cloud.githubusercontent.com/assets/10718120/6201640/ce822364-b469-11e4-84cc-2e494295c1e4.png)

**Comment by Cisien** [comment]
Because that isn't how it works. It is meant to connect to your AE system and either pull items from cells and into the network or the other way around.

**Comment by TheJulianJES** [comment]
For more information @SadGhoster87 please look in the Applied Energistics 2 wiki over at http://ae2.ae-mod.info

**Comment by SadGhoster87** [comment]
"It is meant to. . . pull items from cells and into the network or the other way around"
And what did you think I was trying to do?

**Comment by yueh** [comment]
As you did not say anything at all about it, probably assumed you have done the wrong thing.
There is also a creative cell in the output slot, so probably that you wanted to move the items to it or it completely filled your network.

**Comment by yueh** [comment]
Reopen when you can provide more information.
