### ISSUE TITLE
client crash with channels disabled

### ISSUE THREAD

**Issue by b0rg123** [AppliedEnergistics/Applied-Energistics-2#895]
with channels disabled and in creative mode if you scroll the pages when it gets to the ae2 page client crashes.    appliedenergistics2-rv2-beta-8  this is also part of the infinity ftb pack.

**Comment by TheJulianJES** [comment]
Could you please send us the crash-report.

**Comment by b0rg123** [comment]
https://gist.githubusercontent.com/b0rg123/d1515f293a86a0c9186c/raw/d44ae3b9c25d142fec877666520a83568fcdd216/gistfile1.txt

**Comment by yueh** [comment]
The crashlog also contains an error from WAWLA. Can you try it without that mod?

**Comment by b0rg123** [comment]
intresting. with wawla disabled it dont crash..... wonder what thats about.

**Comment by yueh** [comment]
It looks like it tries to render something as enchanted item/book, based on the crashlog
But you should probably report it to them.
