### ISSUE TITLE
Inaccessible buses and interfaces

### ISSUE THREAD

**Issue by MysticAura** [AppliedEnergistics/Applied-Energistics-2#897]
Version: appliedenergistics2-rv2-beta-8

After updating to this beta I could no longer access buses and interfaces once an ae-facade was placed on them. Any facades placed pre-update, are still accessible through the invisible facade, but any new ones placed have no luck.

If it helps, Waila is reading the inaccessible ones as Unnamed. While the others have their proper names.

This occurs on my server, but not single-player.

**Comment by yueh** [comment]
Cannot reproduce.
