### ISSUE TITLE
Stack Glitch.

### ISSUE THREAD

**Issue by SprinkCal** [AppliedEnergistics/Applied-Energistics-2#898]
Whenever I shift click an item into a terminal or pull out using left mouse click/shift +mouse click it will only pull out or put in a few eg. putting a stack of diamonds in will only put in 44. another example would be pulling out from terminal might only give me 2. It only happens in the terminal not in chests or other mod storage blocks. The number varies from 2 to 64 that it will put in/pull out. This doesn't happen in a wireless terminal.

**Comment by Cisien** [comment]
Make sure you have a power buffer on the network. If the network doesn't have enough power, then only some of a stack will be extracted before running out. An energy cell on the network should do it.

**Comment by SprinkCal** [comment]
Thanks, works now :)
