### ISSUE TITLE
Facades not available (Except Glass)

### ISSUE THREAD

**Issue by LarsBorris** [AppliedEnergistics/Applied-Energistics-2#899]
Hello,

I am using DireWolf20 v1.0.3 Server with MineCraft version 1.7.10. running on Windows Platform
Applied Energistics 2 RV2 -beta-1 is installed by default.

Clients are both Windows and Mac.

When I first started playing this modpack I could see/craft craft facades for almost all blocks in the game.
I have crafted some abyssal stone brick facades and slapped them on to cover cables.
Now recently I am unable to see any facades in anyeye except the glass facade.When i click NEI Subsets -> CreativeTabs The Applied Energistics 2 - Facades are dark grey (inactive)
Existing facades already created in the game and used to cover cables are still there and I can remove them and reapply them to cover cables. I just can't create any new ones.

I haven't changed anything on the server just been playing it with 6 other friends.

I have tried upgrading AE to beta-8 but with no success.
I have also tried disabling achievements because I remember reading somewhere that it might fix it.

Do you need any log files from me to investigate more?
This guy was talking about something similar:
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/377

I have attached 3 screenshots showing disabled Facades in NEI Subsets, The glass facade and a cutout of the config file showing that facades are enabled.

![skaermbillede 2015-02-16 kl 14 33 57](https://cloud.githubusercontent.com/assets/10630935/6212754/dfb29026-b5e8-11e4-864c-2cb9f895aff4.png)
![skaermbillede 2015-02-16 kl 14 31 34](https://cloud.githubusercontent.com/assets/10630935/6212720/952d6e90-b5e8-11e4-8cdd-5da40a020eea.png)
![skaermbillede 2015-02-16 kl 14 31 44](https://cloud.githubusercontent.com/assets/10630935/6212721/954d111e-b5e8-11e4-857f-4e36ba6d915d.png)

**Comment by yueh** [comment]
The DW20 uses inpure to merge every facade together, so are the really not craftable or just do not show up in NEI? (Hiding items in NEI is probably more confusing than having some extra page, which could just be moved to the end.)

The pack is also known for disabling random facades. There is Facade.cfg file in the same folder as the AE2 config. It allows to enable/disable each facade on its own. But it is not certain, that every facade renders correct, if you just enable every.

**Comment by LarsBorris** [comment]
Thanks for taking the time to answer me :+1: 
In the Facade.cfg the facades are enabled (the ones that should be enabled at least)
![skaermbillede 2015-02-17 kl 08 39 54](https://cloud.githubusercontent.com/assets/10630935/6224710/b5003bba-b680-11e4-9f7b-6a69bfd11284.png)

I have also tried running the game in single player mode and I am having the exact same issues.

Son of a gun!
I just tried putting a fitted abyssal stone in the center then surround it with 4 cable anchors.
Voilá I just crafted a facade!
So the facades are indeed enabled but the page in NEI is disabled?

Is there any way to enable the NEI page so i can see the different facades/recipies?

Thanks for your support :+1:

**Comment by RAnders00** [comment]
Uninstall the mod inPure.

**Comment by LarsBorris** [comment]
Tested and found to be a valid solution.
Disabling inpurecore, will this make other mods in the modpack stop working?
<a href="https://feedthebeast.atlassian.net/wiki/display/PML/Direwolf20+%281.7.x%29+1.0.3">Here</a> is a link to what mods the modpack contains.

Thanks :+1:

**Comment by yueh** [comment]
No, its sole purpose is to merge items like facades, covers and such into one single item in NEI, resulting in less displayed pages (and confusing some users)

**Comment by LarsBorris** [comment]
Alright, Thank you so much for the support :+1:
