### ISSUE TITLE
Crash from the Purified Certus Quartz Crystal 

### ISSUE THREAD

**Issue by Kmoosta** [AppliedEnergistics/Applied-Energistics-2#901]
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 2/16/15 3:46 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchFieldError: materialPureifiedCertusQuartzCrystal
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:695)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchFieldError: materialPureifiedCertusQuartzCrystal
	at thaumicenergistics.registries.RecipeRegistry.registerComponents(RecipeRegistry.java:82)
	at thaumicenergistics.registries.RecipeRegistry.registerRecipies(RecipeRegistry.java:546)
	at thaumicenergistics.proxy.CommonProxy.registerRecipes(CommonProxy.java:55)
	at thaumicenergistics.ThaumicEnergistics.postInit(ThaumicEnergistics.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.7.0_67, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 209859480 bytes (200 MB) / 609030144 bytes (580 MB) up to 3186360320 bytes (3038 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xincgc -XX:MaxPermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1286 Minecraft Forge 10.13.2.1286 77 mods loaded, 77 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	FML{7.10.85.1286} [Forge Mod Loader] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Forge{10.13.2.1286} [Minecraft Forge] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	appliedenergistics2-core{rv2-alpha-17} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NotEnoughItems{1.0.3.62} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.62-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	appliedenergistics2{rv2-alpha-17} [Applied Energistics 2] (appliedenergistics2-rv2-alpha-17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	betterbeginnings{0.0.6.0} [Better Beginnings] (Better-Beginnings-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BiblioCraft{1.8.2} [BiblioCraft] (BiblioCraft-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1019-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.9].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CoFHCore{1.7.10R3.0.0B7} [CoFH Core] (CoFHCore-[1.7.10]3.0.0B7-35.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThermalFoundation{1.7.10R1.0.0B3} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0B3-8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThermalExpansion{1.7.10R4.0.0B6} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0B6-16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BigReactors{0.4.0rc10} [Big Reactors] (BigReactors-0.4.0rc10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	AWWayofTime{v1.0.1g} [Blood Magic: Alchemical Wizardry] (Blood-Magic-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Baubles{1.0.1.8} [Baubles] (Baubles-1.7.10-1.0.1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Thaumcraft{4.2.1.4} [Thaumcraft] (Thaumcraft-1.7.10-4.2.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Botania{r1.3-149} [Botania] (Botania r1.3-149.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	camping{2.1} [The Camping Mod 2] (Camping-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CarpentersBlocks{3.2.8} [Carpenter's Blocks] (Carpenter's Blocks v3.2.8 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	carvablepumpkins{1.1} [carvablepumpkins] (Carvable-Pumpkins-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	chisel{1.5.7} [Chisel] (Chisel-1.7.10-1.5.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ComputerCraft{1.64} [ComputerCraft] (ComputerCraft-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	props{1.10} [Decocraft] (DecoCraft-Mod-1.7.10.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded{1.7.10R2.8.0RC4} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Railcraft{9.3.3.0} [Railcraft] (Railcraft_1.7.10-9.3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	EnderIO{1.7.10-2.1.8.260} [Ender IO] (EnderIO-1.7.10-2.1.8.260.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	EnderStorage{1.4.5.24} [EnderStorage] (EnderStorage-1.7.10-1.4.5.24-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	EnderZoo{1.7.10-1.0.2.7_beta} [Ender Zoo] (EnderZoo-1.7.10-1.0.2.7_beta.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ExtraUtilities{1.1.0k} [Extra Utilities] (Extra-Utilities-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	fairylights{0.3} [Fairy Lights] (Fairy-Lights-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	foxlib{1.7.10-0.5.0} [FoxLib] (FoxLib-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	harvestcraft{1.7.10d} [Pam's HarvestCraft] (HarvestCraft-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	iChunUtil{4.0.0} [iChunUtil] (iChunUtil-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Hats{4.0.1} [Hats] (Hats-4.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	inventorytweaks{1.59-dev-156-af3bc68} [Inventory Tweaks] (InventoryTweaks-1.59-dev-156.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	IronChest{6.0.60.741} [Iron Chest] (ironchest-1.7.10-6.0.60.741-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Waila{1.5.4a} [Waila] (Waila-1.5.4a_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	JABBA{1.1.4} [JABBA] (Jabba-1.1.4_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	journeymap{5.0.0RC3} [JourneyMap] (JourneyMap5.0.0RC3_Unlimited_MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	magicalcrops{1.7.2 - 0.1 ALPHA} [Magical Crops] (Magical-Crops-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC4} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC3} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC4} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC4} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC3} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC3} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC4} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC3} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC3} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC3} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC3} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC3} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC3} [MFR Compat: RP2] (MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC3} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC4} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC3} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC4} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC4} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	mobats{1.0} [Mo' Pigs Mod] (Mo Pigs-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Morph{0.9.1} [Morph] (Morph-Beta-0.9.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	PigCompanionMod{1.6.4} [PigCompanionMod] (Pig-Companion-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	StevesFactoryManager{A92} [Steve's Factory Manager] (StevesFactoryManagerA92.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Tails{1.7.10-1.1.1} [Tails] (Tails-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	TConstruct{1.7.10-1.7.1.build771} [Tinkers' Construct] (TConstruct-1.7.10-1.7.1c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	thaumicenergistics{0.8.7.2b-rv1} [Thaumic Energistics] (Thaumic-Energistics-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Errored
	ThaumicMachina{1.7.10-0.1.0 (Open-Beta)} [Thaumic Machina] (Thaumic-Machina-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-159.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	TMechworks{1.7.10-86.e500b88} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	AnimationAPI{1.2.2} [AnimationAPI] (Utility-Mobs-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	UtilityMobs{3.1.0} [Utility Mobs] (Utility-Mobs-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	AE2 Version: alpha rv2-alpha-17 for Forge 10.13.2.1230
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:ON, BC:OFF, MJ6:ON, MJ5:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF

**Comment by MrMetric** [comment]
I'm going to guess that your Thaumic Energistics version doesn't match your AE2 version

**Comment by Cisien** [comment]
Your ae2 version is very out of date, try updating along with all other ae2 addons
