### ISSUE TITLE
Certain blocks appearing transparent (certus quartz, seared bricks, etc.)

### ISSUE THREAD

**Issue by Nateolocity** [AppliedEnergistics/Applied-Energistics-2#902]
Mod Version: v1, Stable 1
Minecraft Version: 1.7.10
Mod Loaders Installed: Forge 10.13.2.1291, LiteLoader 1.7.10 (Latest)
OS: Mac OS X 10.9.2
Graphics: NVIDIA GeForce 320M 256 MB graphics
Java: Java 6

I recently got Applied Energistics 2 and upon starting to mine, I saw that the certus quartz block was transparent, but thought nothing of it so continued on. I am now at the point where I am making a smeltery. I noticed that the Seared Bricks block and others like the Seared Controller was also invisible. If you could help as soon as possible, it'd be great. Thank you! I will be trying different versions of the mod to see if its a version bug.

![2015-02-16_17 34 12](https://cloud.githubusercontent.com/assets/11036936/6220973/4fe2a9bc-b602-11e4-97db-f1ce14659f87.png)

**Comment by yueh** [comment]
This is probably caused by optifine. Based on your specs, it is understandable that you are using it. But it changes the rendering quite heavily and can cause such issues.

**Comment by Nateolocity** [comment]
Is there a known Optifine version that fixes this? Or should I get rid of it?

**Comment by Nateolocity** [comment]
Also, when I have the blocks in my hotbar, the textures appear but only one side of the texture. Like it's flat.

**Comment by Nateolocity** [comment]
Turns out it was because of the Optifine version. I updated it and it works now. I'll post again if it happens again and updating doesn't fix it.

**Comment by Cisien** [comment]
Also, update ae2. Rv1 is quite old and buggy

**Comment by Nateolocity** [comment]
what is the latest ae2 you guys would recommend me use? @yueh @Cisien

**Comment by Cisien** [comment]
Rv2 beta 8 -- the latest build

**Comment by mindforger** [comment]
another info i noticed aside from any optifine stuff when using mobile graphics, sometimes your RAM  assigned as additional VRAM can not keep up and gets compromised. Try reducing RAM load and double check if you have 8GB RAM you can not assign 8GB to your JavaVM as a huge chunk will be needed for your GFX

**Comment by Auroxiel** [comment]
Hello I'm having an issue with applied energistics 2, all of the blocks are invisible and xray glitching through the world. I'm not really sure how to fix it here are the mods I'm using. 
![capture](https://cloud.githubusercontent.com/assets/18739817/14920160/3705bef6-0dfa-11e6-8d75-59805ddc8725.PNG)
![2016-04-29_11 01 46](https://cloud.githubusercontent.com/assets/18739817/14920178/3fa6780c-0dfa-11e6-892c-1b420dc51f4e.png)
