### ISSUE TITLE
Drain not emptying into casting table (AE2)

### ISSUE THREAD

**Issue by Nateolocity** [AppliedEnergistics/Applied-Energistics-2#903]
Mod Version: v2, Beta 8
Minecraft Version: 1.7.10
Mod Loaders Installed: Forge 10.13.2.1291, LiteLoader 1.7.10 (Latest)
OS: Mac OS X 10.9.2
Graphics: NVIDIA GeForce 320M 256 MB graphics
Java: Java 6

When I put down the casting table and try to empty the aluminum into a regular cast it does not work. I have it built correctly, and even tried raising it a level and it won't work.

![2015-02-16_19 40 30](https://cloud.githubusercontent.com/assets/11036936/6222371/f8be056c-b617-11e4-94ce-88e1d135371c.png)

**Comment by Nateolocity** [comment]
I've even tried different versions and an empty hand.

**Comment by Cisien** [comment]
Wrong tracker?

**Comment by Cisien** [comment]
Also, you need aluminum brass, pure aluminum wont go in the table

**Comment by RAnders00** [comment]
BTW Java 6 is way out of date. https://www.java.com/de/download/manual.jsp
