### ISSUE TITLE
Unable to craft certain items, such as inscriber.

### ISSUE THREAD

**Issue by lokiwolf** [AppliedEnergistics/Applied-Energistics-2#904]
I found all four presses, had plenty of crystals to start with, went to craft the inscriber, and couldn't. I checked and double checked the recipe, made sure I didn't need anything special to do it. I had all the materials, and the recipe was correct, but nothing. Same goes for other items, like the glass cables.

**Comment by Cisien** [comment]
Version of mod? Are you running a modpack?

**Comment by lokiwolf** [comment]
I'm not entirely sure for the mod, I got it through forge 1.7.10. No modpack. As far as I can tell, the mod works fine otherwise. I figured out what I did wrong with the glass cables. Seems it's just this item that I can't craft. I decided to spawn it in creative mode, though that kind of still feels like cheating.

**Comment by mindforger** [comment]
lokiwolf: "I got it through forge 1.7.10" what does this mean? 
Did you even download it from the AE2 Homepage or just simply from "an random" site ? 
Normally the jar file contains the version in it's name ... 

You can tell the Version by reading the log if not already by filename [...]

and you could have probably uploaded your log already to pastebin to let other people find out for you what version you are using if not able by yourself :)

PS: this is one more reason to use a license which only allows distribution to public by licensed sites or inside a modpack, so can all of this unspecific bug reports be sent to the people who did the mess instead to blame the mod writer who didn't do anything wrong at all ... and by the way, who tells you that this particular 3d party host does not modify the jar and hook you with a trojan horse ?!

**Comment by lokiwolf** [comment]
Forge. As in the mod loader. Intended for minecraft 1.7.10. Which linked, I believe, to this site. This is all the information I can get. appliedenergistics2-rv1-stable-1

**Comment by Cisien** [comment]
Update ae2. Forge is only a mod loader. It does not offer mod downloads.

It is always best to download the mod from ae-mod.info

**Comment by lokiwolf** [comment]
the latest version available is the one i have, but I'm going to try and re download, see if i get different results. I recall downloading it directly from here, the forge site just linked me to this one.

**Comment by Cisien** [comment]
The latest is rv2 beta 8

**Comment by lokiwolf** [comment]
ahh, did not see that one

**Comment by lokiwolf** [comment]
think i've got it, though it seems the issue persists. not sure what's going on there. is anyone else having this issue?

**Comment by Cisien** [comment]
Try deleting your ae2 config. Also make sure there are no minetweaker scripts that may be disabling the recipe. If that fails, post your log

**Comment by lokiwolf** [comment]
Sorry if I sound like a noob, how do i do that stuff? XD

**Comment by Cisien** [comment]
Please post the log in pastebin next time.

You don't have minetweaker installed, so that suggestion can be ignored. Did you delete the ae2 config?

**Comment by lokiwolf** [comment]
Sorry about that, rather new to this. ^_^  I did.

**Comment by thatsIch** [comment]
This is the original recipe for the glass cable
http://ae-mod.info/ME-Glass-Cable/

if you use NEI you can verify if something changed the recipe

**Comment by Jules06** [comment]
Same problem here, deleting the config didn't work.

**Comment by Greennyy** [comment]
Im getting the same problem, though its a modpack i made myself  for personal use. as far as i am aware, theres no conflicts. i did notice that above the other person also had morph installed, and thts the only similarity in mods besides AE2 that we both have, which i believe i have the same update as he originally had, rv2 stable 1. Deleting the config did nothing for me either.  and with eni installed, it shows the item doesnt even HAVE a recipie. As in, i click on it in recipe mode, and nothing happens... theres multiple items that are broken as such. seeds, me drive, and a few other items that i could list if needed.

**Comment by Sslazz** [comment]
I'm seeing the same thing as Greennyy - NEI is not showing any recipies at all for the inscriber, and laying out the stuff in a standard crafting table does nothing.

**Comment by Sslazz** [comment]
Oop - upgrading to the latest beta resolved my issues.

**Comment by Greennyy** [comment]
fixed mine as well, everything is craftable... though now ive somehow lost nei recipes showing up at all. that may be i need to update that as well... but thats not a problem to post here on applied energistics.

**Comment by Jules06** [comment]
Updating thaumic energistics worked for me :)
