### ISSUE TITLE
Is this mod still being developed?

### ISSUE THREAD

**Issue by KamranMackey** [AppliedEnergistics/Applied-Energistics-2#905]
Is this mod dead or is it still being developed? There hasn't been a commit pushed to the repo in 14 days and I'm beginning to think that this mod is dead.

**Comment by teamMK** [comment]
Maybe the the people get buisy in rl?

**Comment by ate0ate** [comment]
Algorithm retired a while ago and said this...

"With a heavy heart I resign as developer of AE2. I will, over the next several weeks, be working with several people to open up the mod and put a team together to carry on at minimum maintaining the mod as I step down."

So, I guess the future is kind of up in the air?

**Comment by RAnders00** [comment]
There are lots of other developers heavily working on the mod
https://github.com/AppliedEnergistics/Applied-Energistics-2/graphs/contributors
especially thatsIch

**Comment by KamranMackey** [comment]
Yeah i know, but there hasn't been a commit to the repo in 14 days.

**Comment by yueh** [comment]
And it is not possible that we are just busy or some stuff just takes longer?

But if you just want a commit a day, I can get around and write a small script, which commits a random [fortune cookie](http://en.wikipedia.org/wiki/Fortune_%28Unix%29) each day.

**Comment by KamranMackey** [comment]
No thanks, i'm good lol
