### ISSUE TITLE
missing neighbor update when a QNB (Quantum Network Bridge) is formed or broken

### ISSUE THREAD

**Issue by MatthiasMann** [AppliedEnergistics/Applied-Energistics-2#906]
Forming or breaking of a multi block structure should cause a neighbor block update.

**Comment by AlgorithmX2** [comment]
Why? The block itself has no changes that the redstone/inventories and such around it need to be notified about?

And Doing Block Updates for Multi-blocks can also cause Block Update Feedback, so not doing it has benefits in removing that possible issue.

**Comment by MatthiasMann** [comment]
AE2 is the only mod not conforming to that - and it makes it nearly impossible to interact with AE2 in a reasonable way.

**Comment by AlgorithmX2** [comment]
I assume this is related to the continuing discussion about network connectivity detection, in which case you have more issues then just the QNB.

Once again, AE2's grid interactions are not handled with block updates.
