### ISSUE TITLE
Storage bus on Jabba barrels not converting by oreDict

### ISSUE THREAD

**Issue by eranor** [AppliedEnergistics/Applied-Energistics-2#908]
Hi.
I've tried to store items in Jabba barrels with storage buses, but I came to a problem.
The different oreDict items would not go into the barrel (e.g copper ingots, sulfur etc.).
Even if I set it as the filter, it won't work. I don't know if it's a bug or just a missing feature, but it would be awesome, if it could be fixed/implemented.

Thanks.

**Comment by AlgorithmX2** [comment]
The interface that AE2 uses to talk to Jabba ( IDSU ) is a single item storage medium, and it doesn't support this type of logic, so unless there is a change is made to IDSU, I don't think this will be changing any time soon.

**Comment by eranor** [comment]
Thank you for the answer. :)

**Comment by Tergiver** [comment]
@eranor  You can achieve this by adding (in addition to the storage bus) an export bus to another side of the barrel and putting all of the ores other than the ore in the barrel on that filter. Why does the export bus do what the storage bus cannot? Seems like a good question.

**Comment by eranor** [comment]
@Tergiver It was that, what I did at the end. :) As far as why is not working, as @AlgorithmX2 says the interface witch the barrel uses is the same as the MFR Deep Storage, and there this isn't implemented.  You would need a separate implementation or an exception for the barrels. (If I got it right.)
