### ISSUE TITLE
Storage Cell exceeding maximum capacity

### ISSUE THREAD

**Issue by kevinkk525** [AppliedEnergistics/Applied-Energistics-2#909]
While moving my AE base I realized that many of my Storage Cells exceeded their maximum sotrage capacity.
I do not know why and how this happened. It was just inside an ME Drive and the ME network is always being fed a lot of items as every normal system. Additionally I am pulling the ItemsInNetwork every tick by OpenComputers (don't know whether that is even important)

Version rv2-beta-8

![2015-02-18_00 23 44](https://cloud.githubusercontent.com/assets/9607123/6247182/a15c7a6e-b771-11e4-899e-3dbf7b62e1e7.png)

**Comment by TheJulianJES** [comment]
Since you have ExtraCells, could ExtraCells maybe cause this issue?

**Comment by kevinkk525** [comment]
Well possible... I do not know. I just wanted to let the devs know about that, maybe they immediately realize a possible bug. But as this is not a real bug that causes problems it surely isn't a priority.

**Comment by yueh** [comment]
Did you recently updated from rv1? (Or does this cell exist since rv1)

**Comment by kevinkk525** [comment]
oh good question. it is definitely possible that these cells were created while rv1-stable was running.

**Comment by yueh** [comment]
Because there was a bug and they calculated their size wrongly.
They do not lose any items, but you cannot put more in there until they are below the limit.

**Comment by kevinkk525** [comment]
ok good. so this is already fixed. Then you can close this issue. Thanks
