### ISSUE TITLE
Spawing Meteorites in multiple nearby chunks by spawn - FTB Infinity

### ISSUE THREAD

**Issue by vandench** [AppliedEnergistics/Applied-Energistics-2#911]
When I was playing FTB Infinity and when I created a new world there were quite a few incomplete meteorites in nearby chunks. Basically each of the affected chunks tried to create a new meteorite. I don't know if this was an inter-mod communications problem or something just broke in AE2. Also after taking a look at the console logs it shows quite a few errors with being unable to create the compass, I presume that it is unable to find the proper location of the meteorite. Here a few images along with the seed:
![2015-02-18_13 03 07](https://cloud.githubusercontent.com/assets/7896397/6254740/8b10b60e-b770-11e4-93f8-6e86307ffab2.png)
![2015-02-18_13 03 14](https://cloud.githubusercontent.com/assets/7896397/6254742/8b131c82-b770-11e4-9ad8-842464c04389.png)
![2015-02-18_13 03 37](https://cloud.githubusercontent.com/assets/7896397/6254741/8b110a5a-b770-11e4-8f07-5704fede0f7e.png)

If the seed is too obscure here it is: -6485081856914539833    and is a BiomesOP's world type, let me know if I got the seed wrong, I'm pretty sure it is correct. Here is the log as well: http://pastebin.com/2zk0w7mw  (I had to cut out a lot to stop my browser from crashing).

**Comment by Cisien** [comment]
Something is blocking ae's ability to write to one of the files in the world directory. Possibly async chunk generation. You can delete and recreate the world and hopefully avoid this

**Comment by yueh** [comment]
The actual issue is that AE2 cannot obtain the correct path to the world folder.
All logs/detailed reports, which I have read, tried to write to the folder of another save, mostly deleted ones.
No idea why this is happening, but we use the normal method to obtain that path from minecraft/forge.

**Comment by vandench** [comment]
Okay that makes sense, I had a feeling it was probably caused by some world gen modifier mod and not really AE2's fault.

**Comment by seebs** [comment]
We had exactly this symptom from a server which filled its disk.

We don't have usable logs from that, because, of course, the server's disk was full, and it couldn't write them.

It has also produced a world where, even after we nuked the affected regions, the server tends to crash with strange messages if you go to the region that was being generated at the time, often things like:

[19:19:33] [Chunk I/O Executor Thread-1/ERROR]: Chunk file at -634,-1217 is in the wrong location; relocating. (Expected -634, -1217, got -633, -1229)

**Comment by yueh** [comment]
A full disk is nothing we can somehow account for. It is the same category as starting to delete random world files and then complaining about the lost progress (that is an exaggerated example).

As long as we have no reliable way to reproduce it, there is nothing we can really debug.

**Comment by grompe** [comment]
I had this "scrambled meteorite chunks" issue happen to me when playing with version rv2-stable-3.

Started up an existent world, ran around some, quit to the main menu, deleted it, created another with seed "mango" (supposedly with meteorite near spawn), it flooded the log with error message:

    [AE Compass Service/INFO]: Failed to create AE2/compass/

along with an exception of AE2 trying to load a file from the deleted world:

    /deleted_world/AE2/spawndata/188.dat

and the meteorite chunks were looking similarly messy to the picture above.

Restarting Minecraft and recreating the world made the issue go away.

**Comment by thatsIch** [comment]
Does nothing for me.
How did you delete the world?

**Comment by thatsIch** [comment]
do you per chance have the full log?

**Comment by thatsIch** [comment]
the `Failed to create AE2/compass` message only is generated, if the program is not able to create it based on the security system of the OS. So if you for example have no permissions to create the folder (for some reason) it will not generate it.
