### ISSUE TITLE
crash on load 

### ISSUE THREAD

**Issue by Ace199102840** [AppliedEnergistics/Applied-Energistics-2#913]
http://pastebin.com/KLZxNUck

using :  appliedenergistics2-rv2-beta-8  

crashes on load .  i had to take out many mods till i figured out which mod was crash my game.  it is definitely this version of AE2, which is sucks cause i was using waila and noticed that this release has support with the waila mod.

**Comment by TheJulianJES** [comment]
A mod uses an old API, remove ExtraCells and other AE2 addons if you have any.

**Comment by Ace199102840** [comment]
thank you :)

**Comment by TheJulianJES** [comment]
@Ace199102840 Please close this issue now =)
