### ISSUE TITLE
Autosmelting with Tinker's Construct (crushed iron ore)

### ISSUE THREAD

**Issue by drakiesan** [AppliedEnergistics/Applied-Energistics-2#914]
Hi. I don't know if it's bug or not but crushed iron ore can't be smelted and it's using in pattern to make iron ingot.
![problem](https://cloud.githubusercontent.com/assets/11073580/6265751/d6da8508-b831-11e4-848a-1a1e974b034f.png)

**Comment by TheJulianJES** [comment]
Setup? Version?

**Comment by drakiesan** [comment]
I'm playing through AT launcher Sky Factory 2... AE2 rv2 beta 6 is there.

**Comment by TheJulianJES** [comment]
So I don't understand what's wrong? Crushed Iron Ore is from IC2 I think.

**Comment by KlutzLament** [comment]
What did you use in the pattern?

**Comment by DasKashi** [comment]
It's from Ex Nihilo.
Please clarify your problem, aint you able to start the crafting process? Did you start it but nothing is happening? Did you use a processing or a crafting pattern?

**Comment by drakiesan** [comment]
I'm not not able to smelt all my iron, because at some point it will fill with Crushed Iron Ore which is unsmeltable. Pattern is Iron Ore Gravel --> Iron Ingot (Tinker's construct will smelt it to molten iron which you can cast to castings...). But at Crafting menu is crushed iron ore as you see at picture.

**Comment by mindforger** [comment]
Explain your setup please, i am GUESSING right now, you are filling a tinkers smeltery with an interface and some crafting pattern? But after using up the smeltable stuff the interface starts filling the smeltery with crushed iron ore?! Please be more specific what you did and how you setup the pattern exactly.

**Comment by UniZero15** [comment]
You can't smelt the crushed ore directly. You need to combine them to make Iron Ore sand then you can smelt them.

**Comment by yueh** [comment]
I can only imagine two possibilities.

Either you have a pattern somewhere defining that recipe (crushed to ingots).
Or crushed ore is for whatever reason oredict with the ore sand, then there is nothing we can do as we get the wrong information to calculate it.
