### ISSUE TITLE
ME network consistently refusing item in- and output in relation to size.

### ISSUE THREAD

**Issue by DasKashi** [AppliedEnergistics/Applied-Energistics-2#915]
So we're running an FTB Infinity server with AE2 rv2-beta-8, we decided to turn off channels and yes, I know you're not really happy about people using this option, but with 3 and more people building and using the same me network together it got really annoying very fast. I'm not 100% sure that this is the source of our problem but let me explain ...

After one of us hooked up ~20 storage buses on barrels to the network, it stopped to work in a weird way, we weren't able to in- or output items at terminals and I'm not quite sure anymore, but I think in- and output-buses stopped doing so too. So I spent quite some time invenstigating and realized, that cutting connection of some parts of the network partially restored the functionality until we were able to at least in- and output a few items with disconnecting more parts resulted in a few stacks. 

After some time i realized that this problem was allready existing from the start when trying to dump the whole inventory into the network only moved like 2/3 or half of it. But we didn't realize the range of that problem since manual output is somewhat limited to single stacks per shift-click anyway.

I kinda optimized our whole network by replacing AE2 components with conduits where it made sense, this resulted in raising the amount we're able to move up to ~5 stacks again.

If this doesn't really make sense, feel free to ask ... I'll gladly answer.
I could also provide a download of the world save if that'd help further investigation.

**Comment by Cisien** [comment]
This sounds a lot like a power issue. Try adding some (dense) energy cells to the build to increase the buffer

**Comment by DasKashi** [comment]
So, that fixed the problem, thank you very much.
