### ISSUE TITLE
Little idea

### ISSUE THREAD

**Issue by AscalTheBest** [AppliedEnergistics/Applied-Energistics-2#917]
REMOVE THAT F*CKEN CHANNEL SYSTEM! EVERYONE RAGE ABOUT IT! THAT'S STUPID IDEA MAKING THAT MECHANIC!

**Comment by KlutzLament** [comment]
I enjoy the channel system. It balances the somewhat overpowered nature of AE by forcing the player to put some thought into the design of their network. It is a very well designed system and does not limit what can be done with it as long as the player is reasonably intelligent in how they design and build their system. It makes AE more fun.

**Comment by AscalTheBest** [comment]
Srsly? Someone enjoying that? Fun? It makes AE more shitty. I going to decompile and to the private build. That's really annoying. Do own mod like AE is easyier than do a big AE system.

**Comment by MrMetric** [comment]
You know, there's nothing stopping you from changing the mod however you want. Why not do that instead of complaining?

**Comment by vallard192** [comment]
I think the odds of someone who hasn't read the config file successfully
changing the mod are low.

When you do your private build, you might want to edit the config file to
turn off channels.  Or maybe just use the actual builds and edit the config
to turn off channels.

If you need help try googling "AE2 turn off channels".  The first result
should have all the information you need.
