### ISSUE TITLE
ME System freezing

### ISSUE THREAD

**Issue by Gerrygames** [AppliedEnergistics/Applied-Energistics-2#919]
My ME System is randomly freezing.
I can´t take items out of the terminal and the system isn´t finishing crafting operations. Also the system isn´t pulling/putting items out of/in interfaces. But the strangest thing is I CAN take items out of the wireless terminal :/

I don´t know how to reproduce the problem because it happens randomly but if it helps I could upload my world. The only thing I can say is that the channel-system is disabled.
And I had an similar problem in the 1.6 version (AE 1), where chunkloading the whole system fixed the problem, but now my whole system is chunkloaded.

I´m running the Direwolf20 modpack 1.7.10 v1.0.3 on a server.
AE Version: rv2-beta-1
Forge: 10.13.2.1272
Forge Mod Loader: 7.10.85.1272

Here´s a video:
http://youtu.be/fZPl4PJdnFI
Here´s the forge-log(Sorry I can´t use pastebin the file ist too big):
https://www.dropbox.com/s/gu2lfntjqs3n8o5/fml-server-latest.log?dl=0

And sorry for any mistakes, I´m German :D

**Comment by Gerrygames** [comment]
![2015-02-20_14 21 30](https://cloud.githubusercontent.com/assets/11089941/6286807/d6465916-b90b-11e4-8655-abadcfe8596c.png)
I disconnected my fast autocrafting system and now the system is working again :/ 
I don´t know what is wrong with it :(

**Comment by Gerrygames** [comment]
![2015-02-20_14 28 07](https://cloud.githubusercontent.com/assets/11089941/6286883/b496f9aa-b90c-11e4-98ff-5c3428ff0b8e.png)
When i connect these interfaces, the system freezes.
That makes no sense :/

**Comment by Gerrygames** [comment]
I think I know, what it is. The AE System can´t handle this much interfaces. The more interfaces i connect, the less items I can take out of the system.
Here´s a video:
http://youtu.be/mpGM09YAD98

**Comment by Cisien** [comment]
You might be running out of power. Try adding a (dense) energy cell to the network.

**Comment by tbbw** [comment]
I came here coz i was experiensing the same issues as Gerrygames did in the first video.
The solution was to add a dense energy cell as Cisien recomended.
The problem was that if the AE network ran out of that little extra power it needed it compleatly locked up until a change to the network was made ( add or remove an interface, controller, export/import buss ) so it would come back alive until it bumped down to 0AE storage.

**Comment by yueh** [comment]
Inactive.
Reopen it, if adding power cells did not solve it and the issue still exists.
