### ISSUE TITLE
Cables randomly brakes

### ISSUE THREAD

**Issue by AlgorithmX2** [AppliedEnergistics/Applied-Energistics-2#92]
What is happening?
Sometimes (randomly) the ME-cables just "pops" loose and breaks the connection. It happens to glass/smart/dense cables.
If I'm fast enough I can see the cable lying on the floor.
What is expected?

How to reproduce?
?
Server or Single Player?: Server and single
Screenshot?:
Crash Log?:

Originally Posted by zed65

This issue was migrated; For original details see http://ae-mod.info/Tracker/0954/

**Comment by thatsIch** [comment]
Closing this in favor of https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1074
