### ISSUE TITLE
Some GUIs don't respect extended reach

### ISSUE THREAD

**Issue by RAnders00** [AppliedEnergistics/Applied-Energistics-2#920]
As you can see [here](https://www.youtube.com/watch?v=Wf6qUsHQ3vs), the ME Drive (just as a example) does not respect extended reach (like the botania ring does)

I tested it using the latest AE2 and latest forge in singleplayer. (AE RV2-Beta-8, Forge #1291, Botania r1.5-163) as visible in the video. Also no other mods and via vanilla launcher.

**Comment by Cisien** [comment]
The AE GUIs explicitly check to make sure the player is within range, so this is by design.

**Comment by RAnders00** [comment]
But I am in range! The range is just not the vanilla range, but it's modified. Did you even watch the video and have you read the text? Wow. I know that they close when you are out of range, but the range that they check for is not respecting range extenders.

**Comment by yueh** [comment]
And there is a reliable way to distinguish between a somewhat valid range extender like the botania ring and something just temporary extending it to circumvent it?

**Comment by Cisien** [comment]
My point was the only known valid range is vanilla. There are no callbacks in vanilla that can tell us if the player is in range or not. Because of this, it is hard coded. It is hard coded like this to block mods that extend the range (such as enderio)

**Comment by AlgorithmX2** [comment]
@Cisien random thought, has anyone looked at TileChest.isUseableByPlayer to see if maybe something changed in a newer build of forge/MC? The isUseableByPlayer for AE2 is probably based on 1.6, so its possible there have been changes made.

I can't check since I don't have any source.

**Comment by thatsIch** [comment]
Looking through the code of minecraft, I found nothing we can swap it out. What we can do is just increase it to the default range of Minecraft which is the root of 64 (currently we are at the root of 32)
