### ISSUE TITLE
Server kicking player when trying to add or remove items via terminals

### ISSUE THREAD

**Issue by phauss** [AppliedEnergistics/Applied-Energistics-2#921]
I have an issue that affects users trying to add or remove items from ME terminals or crafting terminals. Users can access the UI for terminals, but they are kicked from the server with a "fatal error, connection terminated" type of message when any interaction occurs with items already in the system or when placing an item in the system network. Neither the server nor the user's client crashes. The issue affects every user, OP included. This only affects multiplayer on a custom modpack. My users report that the problem doesn't exist in single player.

I have tried disabling ExtraCells, updating and rolling back java versions, and ensuring the mod configs and version numbers (rv2 beta 8) match between client and server.

Server-side log at kick: http://pastebin.com/pXLWYDgr 
Client-side log at kick: http://pastebin.com/Siy4aveL

**Comment by Cisien** [comment]
Try without cauldron on the server. If the issue only happens with cauldron, then report it to them. We can't support cauldron at this stage.

**Comment by phauss** [comment]
I'll give that a shot. I should start looking at alternatives anyways. Thanks for the response.

**Comment by thatsIch** [comment]
Closing for now
