### ISSUE TITLE
ME systems aren't protected from other players

### ISSUE THREAD

**Issue by SebasvanDuuren** [AppliedEnergistics/Applied-Energistics-2#922]
I am running a server with Applied Energistics 2 and the players steal from eachother, I tried to slove the problem with LWC but it didnt really work. They are still able to connect their own cables to other people's cables and rob their whole storage. Is there a kind of protection/security system to slove this?

Something els, the ME system doesnt respect LWC at all. I can rob locked chests with import busses 

-Sebas

**Comment by cleverca22** [comment]
have you tried the security terminal?, it should restrict who can do what on the network

**Comment by SebasvanDuuren** [comment]
With security terminals, I as Admin with op cant look/edit their ME system and I still keep the problem with the LWC locked chests, The import bus empties the chest aswell

**Comment by yueh** [comment]
LWC is a bukkit plugin and we do not support anything related to it.

The question is probably, does any other item transport mod actually care for something like LWC as long as it is not part of forge?
