### ISSUE TITLE
Crash in ME fluid monitor.

### ISSUE THREAD

**Issue by slayerain** [AppliedEnergistics/Applied-Energistics-2#924]
I'm using R1-stable-1, not sure which is newer and bugless. When i trying to dump lava from universal fluid cells from IC experimental in ME fluid monitor game crash and after restart i get lava inside system and extra 1 cell.

**Comment by TheJulianJES** [comment]
1. rv1 is outdated, use rv2 beta (I think it's more stable than rv1)
2. Report this issue to ExtraCells

**Comment by slayerain** [comment]
i just tried replace rv1 with rv2 beta and game don't even start, drop in crash. and the bug not only about cells, i just check with bucket - same bihavior. When i tried plug ME fluid import bus to cistern with lava to suck it up game also crashed, all lava gone so us all my stuff in inventory.

**Comment by slayerain** [comment]
ok.. just tried rv0-stable-10, rv2-beta and rv2 alpha. all crash game on start. so i surpriced how rv1 works at all. Here is crash report mb u guys know wat went wrong. I use lates forge 10.13.2.1291 mb aplied energetics designed for old versions?
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: appeng.api.recipes.IRecipeHandler.injectRecipes()V
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:692)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: appeng.api.recipes.IRecipeHandler.injectRecipes()V
	at extracells.proxy.CommonProxy.addRecipes(CommonProxy.java:32)
	at extracells.Extracells.init(Extracells.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)
	... 10 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows XP (x86) version 5.1
	Java Version: 1.7.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode, sharing), Oracle Corporation
	Memory: 308361048 bytes (294 MB) / 760217600 bytes (725 MB) up to 760217600 bytes (725 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx750M -Xms750M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 Optifine OptiFine_1.7.10_HD_B5 44 mods loaded, 44 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized
	AppliedEnergistics2-Core{rv0-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	IC2{2.2.676-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.676-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized
	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel-1.7.10-3.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
	BuildCraft|Core{6.3.6} [BuildCraft] (buildcraft-6.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
	appliedenergistics2{rv0-stable-10} [Applied Energistics 2] (appliedenergistics2-rv0-stable-10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	BuildCraft|Transport{6.3.6} [BC Transport] (buildcraft-6.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
	BuildCraft|Silicon{6.3.6} [BC Silicon] (buildcraft-6.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
	BuildCraft|Builders{6.3.6} [BC Builders] (buildcraft-6.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
	BuildCraft|Energy{6.3.6} [BC Energy] (buildcraft-6.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
	BuildCraft|Factory{6.3.6} [BC Factory] (buildcraft-6.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ComputerCraft{1.65} [ComputerCraft] (ComputerCraft1.65.jar) Unloaded->Constructed->Pre-initialized->Initialized
	craftguide{1.6.8.1} [CraftGuide] (CraftGuide-Mod-1.7.10.zip) Unloaded->Constructed->Pre-initialized->Initialized
	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) Unloaded->Constructed->Pre-initialized->Initialized
	extracells{2.1.10} [ExtraCells] (ExtraCells-Mod-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Errored
	flansmod{4.9.0} [Flan's Mod] (Flans Mod-1.7.10-4.9.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Forestry{3.4.0.7} [Forestry for Minecraft] (forestry_1.7.10-3.4.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized
	WaslieCore{1.1} [WaslieCore] (WaslieCore-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ForestryExtras{3.1} [Forestry Extras] (ForestryExtras-2-3.1_B24.jar) Unloaded->Constructed->Pre-initialized->Initialized
	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite-1.7.10-2.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) Unloaded->Constructed->Pre-initialized->Initialized
	IronChest{6.0.62.742} [Iron Chest] (Iron-Chests-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	MouseTweaks{2.4.4} [Mouse Tweaks] (Mouse-Tweaks-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	NEIAddons{1.12.3.11} [NEI Addons] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized
	NEIAddons|Botany{1.12.3.11} [NEI Addons: Botany] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized
	NEIAddons|Forestry{1.12.3.11} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized
	NEIAddons|CraftingTables{1.12.3.11} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized
	NEIAddons|ExNihilo{1.12.3.11} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ForgeMultipart{1.1.0.296} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.296-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ProjRed|Core{4.4.5.44} [ProjectRed] (ProjectRed-Base-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ProjRed|Transmission{4.4.5.44} [ProjectRed-Transmission] (ProjectRed-Integration-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ProjRed|Transportation{4.4.5.44} [ProjectRed-Transportation] (ProjectRed-Mechanical-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ProjRed|Exploration{4.4.5.44} [ProjectRed-Exploration] (ProjectRed-World-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ProjRed|Compatibility{4.4.5.44} [ProjectRed-Compatibility] (ProjectRed-Compat-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ProjRed|Integration{4.4.5.44} [ProjectRed-Integration] (ProjectRed-Integration-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ProjRed|Illumination{4.4.5.44} [ProjectRed-Illumination] (ProjectRed-Lighting-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ProjRed|Expansion{4.4.5.44} [ProjectRed-Expansion] (ProjectRed-Mechanical-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ReiMinimap{1.7.10} [Rei's Minimap] (Reis-Minimap-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	McMultipart{1.1.0.296} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.296-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ForgeMicroblock{1.1.0.296} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.296-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	AE2 Version: stable rv0-stable-10 for Forge 10.13.0.1152
	Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Optifine
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.

**Comment by yueh** [comment]
This is an ExtraCells issue and needs to be reported to them.
It is not directly related to AE2.

**Comment by TheJulianJES** [comment]
@slayerain Just Info: Download http://shadowcity.net:8080/job/ecrv2/ latest Build and download latest rv2 build.

**Comment by Cisien** [comment]
When you update ae2 to rv2 you need to update all add on mods such as extra cells, otherwise it will crash

**Comment by TheJulianJES** [comment]
@Cisien Yeah, that was what I meant. =)

**Comment by slayerain** [comment]
ok ill try. thx for help ;) 

     On Sunday, February 22, 2015 10:16 PM, TheJulianJES <notifications@github.com> wrote:
   

 @Cisien Yeah, that was what I meant. =)—
