### ISSUE TITLE
ME Interface fails to autocraft using items from another configured ME Interface

### ISSUE THREAD

**Issue by GuestEG** [AppliedEnergistics/Applied-Energistics-2#927]
Pretty difficult to describe it short, sorry.
I'm using ae2 rv2 beta 8. 
What i have:
two networks, red (outer storage) and green (crafting units and local storage to keep local machinery alive).
Red have ME Interface configured to keep some items inside, which green network can use for autocrafting by Storage Bus attached to that red Interface.
Green network also have an ME Interface with a Crafting Card, which is configured to keep some amount of crafted products inside.
And green network do nothing to craft those products.
They can be crafted by manual request through terminals. They also would craft if there is Export Bus with Crafting Card configured to export such products somewhere. But ME Interface would not autocraft.
It would autocraft only in case of red ME Interface is un-configured and provide full access to red network's storage, what is sometimes unpreferable (in case you want to keep some items or byproducts in both networks intact).

how testing setup looks like:
![javaw 2015-02-22 18-42-49-88](https://cloud.githubusercontent.com/assets/1821205/6319286/fbf63ace-bac7-11e4-842c-d8feb73f782c.jpg)
Red network (rightmost) have stock of oak planks inside it's ME Chest. It's ME Interface configured to store 64 (1 stack) of those planks inside.
Green network can craft sticks from those planks, it's ME Interface (leftmost on the picture) configured to have 12 sticks inside and have Crafting Card.
It wouldn't craft those sticks until red network's Interface is cleared of any export configuration.
But you can request crafting of sticks through terminal or by using Export bus, and it will pull planks from configured ME Interface for that.

I think it is a bug.

**Comment by yueh** [comment]
#329

**Comment by GuestEG** [comment]
I understand it now, thanks. It is just very counterintuitive, because, according to Wiki, "The interface normally functions like a chest", so usual thought is "i can use it as a chest with configurable amount of items for another network to use".

**Comment by yueh** [comment]
The main issue is, that interfaces would start stealing items from eachother and causing a feedback loop.

If I have an idea on how to make them more fine-grained and let crafting requests bypass it, I will add it.
But it just adds more complexity and possible bugs. So for now it is not on a high priority.
