### ISSUE TITLE
Dense cables <ERROR>, Import buses "Device missing channel"

### ISSUE THREAD

**Issue by Novasae** [AppliedEnergistics/Applied-Energistics-2#928]
I've created a controller structure so that I could do autocrafting but all of a sudden devices are reporting that they are missing channels when they weren't before. I have tried without ME conduits but with regular cable to no avail. When I replace the dense cable they lose the <ERROR> text but still do not send out any channels.

EDIT: I am using FTB Infinity with the addition of Mekanism, Refined Relocation and Dynamic Lights.

**Comment by Novasae** [comment]
![2015-02-22_18 34 45](https://cloud.githubusercontent.com/assets/11149316/6319809/d8076214-bac2-11e4-856c-a7eadb0e42d7.png)
![2015-02-22_18 35 06](https://cloud.githubusercontent.com/assets/11149316/6319810/d80c46f8-bac2-11e4-9e27-114560294369.png)
![2015-02-22_18 35 28](https://cloud.githubusercontent.com/assets/11149316/6319811/d812e5c6-bac2-11e4-9dee-f4493a058701.png)
![2015-02-22_18 35 36](https://cloud.githubusercontent.com/assets/11149316/6319812/d815e9ba-bac2-11e4-846d-f632c4927029.png)

**Comment by Cisien** [comment]
What else is hooked to the dense cable, they can only ever move 32 channels, regardless how many connections you place on the controller.
