### ISSUE TITLE
Processor Press Plates

### ISSUE THREAD

**Issue by lightdo-t** [AppliedEnergistics/Applied-Energistics-2#929]
In super flat mode how to get the Processor Press Plates.

**Comment by mindforger** [comment]
same way as you get 99% of all other resources in superflat mode, cheat in, guess right? or what do you mean?

**Comment by yueh** [comment]
Flat worlds have way to many options compared to normal vanilla worlds, so basically treat them similar to skyblock maps or any other heavily modified map. So it is up to you to balance it.

Either use our [custom recipes](http://ae2.ae-mod.info/Custom-Recipes/) to make them craftable, cheat them in, use any other mod which lets you change the loot from chests and add them there or consider something like HQM.

This probably also applies to skystone and both certus variants.

**Comment by lightdo-t** [comment]
对不起，我不会英语。我的意思就是在超平坦地图的生存模式，如何获得那四个陨石箱子里面的四个很重要的模板？还有我发现AE网络的合成无法使用可控的自己合成自己的合成。例如：一：本来有一个萤石，用TC的萤石复制，无法一次性的制作2个以上。二：现有一个青石和一推羊毛，过程是现合成蓝色羊毛，再蓝色羊毛用IC2的附属mod的机器分子重组仪变成青石块，来制作大量的青石。
‍I'm sorry, I can't speak English very well. What I mean is the survival mode in super flat map, how to get the four meteorites four important template inside the box? And I found that AE network synthesis cannot use controllable synthesis of their own synthesis. For example: a: had a fluorite, fluorite copy with TC, cannot one-time production of more than 2. 2: a bluestone and push the wool, existing process is now synthetic blue wool, then blue wool with IC2 affiliated mod machine molecular recombination apparatus into bluestone blocks, to make a lot of bluestone.‍ 





------------------ 原始邮件 ------------------
发件人: "yueh";<notifications@github.com>;
发送时间: 2015年2月23日(星期一) 晚上9:16
收件人: "AppliedEnergistics/Applied-Energistics-2"<Applied-Energistics-2@noreply.github.com>; 
抄送: "lightdot"<1429592831@QQ.com>; 
主题: Re: [Applied-Energistics-2] Processor Press Plates (#929)




Flat worlds have way to many options compared to normal vanilla worlds, so basically treat them similar to skyblock maps or any other heavily modified map. So it is up to you to balance it.
 
Either use our custom recipes to make them craftable, cheat them in, use any other mod which lets you change the loot from chests and add them there or consider something like HQM.
 
This probably also applies to skystone and both certus variants.

**Comment by ken2812221** [comment]
你可以自己修改config文件，就可以合成了，隨便你怎麼設定都可以。
另外，青金石是lapis lazuli，不是bluestone

**Comment by lightdo-t** [comment]
翻译软件 翻译的, 还是不告诉我在哪里修改我怎么知道!(全部config拉进去翻译,一大推乱七八糟)






------------------ 原始邮件 ------------------
发件人: "ken2812221";<notifications@github.com>;
发送时间: 2015年2月25日(星期三) 凌晨4:04
收件人: "AppliedEnergistics/Applied-Energistics-2"<Applied-Energistics-2@noreply.github.com>; 
抄送: "lightdot"<1429592831@QQ.com>; 
主题: Re: [Applied-Energistics-2] Processor Press Plates (#929)




你可以自己修改config文件，就可以合成了，隨便你怎麼設定都可以。
 另外，青金石是lapis lazuli，不是bluestone

**Comment by lightdo-t** [comment]
如果不告诉我在哪里修改 我不知道哪里可以修改





------------------ 原始邮件 ------------------
发件人: "ken2812221";<notifications@github.com>;
发送时间: 2015年2月25日(星期三) 凌晨4:04
收件人: "AppliedEnergistics/Applied-Energistics-2"<Applied-Energistics-2@noreply.github.com>; 
抄送: "lightdot"<1429592831@QQ.com>; 
主题: Re: [Applied-Energistics-2] Processor Press Plates (#929)




你可以自己修改config文件，就可以合成了，隨便你怎麼設定都可以。
 另外，青金石是lapis lazuli，不是bluestone

**Comment by lightdo-t** [comment]
呵呵





------------------ 原始邮件 ------------------
发件人: "yueh";<notifications@github.com>;
发送时间: 2015年3月1日(星期天) 晚上9:05
收件人: "AppliedEnergistics/Applied-Energistics-2"<Applied-Energistics-2@noreply.github.com>; 
抄送: "lightdot"<1429592831@QQ.com>; 
主题: Re: [Applied-Energistics-2] Processor Press Plates (#929)




Closed #929.

**Comment by yueh** [comment]
We have noone speaking chinese, so it is not ideal to communicate. (Translation tools are pretty bad for it).

But your options are mostly:

1. Spawn the plates using NEI.
2. Create your own recipes. (Minetweaker for example)

I would be glad, if someone can volunteer and could translate it. (No, not with google translate. That just produces gibberish)

**Comment by lightdo-t** [comment]
Ok. I know.





------------------ 原始邮件 ------------------
发件人: "yueh";<notifications@github.com>;
发送时间: 2015年3月1日(星期天) 晚上9:37
收件人: "AppliedEnergistics/Applied-Energistics-2"<Applied-Energistics-2@noreply.github.com>; 
抄送: "lightdot"<1429592831@QQ.com>; 
主题: Re: [Applied-Energistics-2] Processor Press Plates (#929)




We have noone speaking chinese, so it is not ideal to communicate. (Translation tools are pretty bad for it).
 
But your options are mostly:
  
Spawn the plates using NEI.
 
Create your own recipes. (Minetweaker for example)
  
I would be glad, if someone can volunteer and could translate it. (No, not with google translate. That just produces gibberish)
