### ISSUE TITLE
Color Applicator

### ISSUE THREAD

**Issue by ken2812221** [AppliedEnergistics/Applied-Energistics-2#930]
If the cable attached with forge microblocks cover, I cant paint the cable with color applicator

version: rv2-beta-1(DW20 v1.0.3)

![2015-02-23_11 56 31](https://cloud.githubusercontent.com/assets/11154118/6322619/586b8e5e-bb53-11e4-8531-3a80a6b6dfd7.png)

**Comment by yueh** [comment]
#256
