### ISSUE TITLE
Fire ExplosionEvent for Tiny TNT

### ISSUE THREAD

**Issue by MineMaarten** [AppliedEnergistics/Applied-Energistics-2#932]
Some people have reported to me that Tiny TNT can't be used anymore to get Compressed Iron from Iron in PneumaticCraft. Recently, as a refactor, I've instead of using custom EntityItems, hooked into forge's ExplosionEvent to spawn Compressed Iron. This works fine for normal explosions.

After investigation, it seems that Tiny TNT simulates Explosions in a custom way, and doesn't fire the ExplosionEvent. My suggestion would be to do this :). Or, a simpler solution is to use World#createExplosion instead. But, I assume there was a reason to not do that in the first place?

**Comment by yueh** [comment]
´World.createExplosion()´ is not really an option. There is no guarantee that any explosion will happen as the explosion damage can be disabled in the configuration.

An `ExplosionEvent` is likely the way to go, but not available with the forge version we are currently using.

**Comment by Cisien** [comment]
I seem to remember algo going this route because of mods or addond for bukkit that blocked explosions. This would allow players to still be able to craft singularities even when the explosions are disabled

**Comment by AlgorithmX2** [comment]
Might need to either update forge, or reflect the event ; its likely the only solution without damaging the anti-explosion behavior.

**Comment by yueh** [comment]
I am already planning on updating forge to the latest recommended version as well as stuff like NEI. (It is probably WAILA breaking NEI 1.0.3 for indev).
Just have not come around to do it.

Adding the event is pretty trivial after that.

**Comment by JasonMcRay** [comment]
Sorry to bump this. but is something being done with this? It has been a year since the report and it still doesnt seem to be implemented.

**Comment by thatsIch** [comment]
sorry, not of importance
