### ISSUE TITLE
Thermal Dynamics: Dupe Glitch

### ISSUE THREAD

**Issue by Andre-Maartens** [AppliedEnergistics/Applied-Energistics-2#933]
I can't find all the links to the pictures anymore so i will just put the link to the issue at hand here:
https://github.com/CoFH/Feedback/issues/154
Only happens with ae2 blocks

**Comment by yueh** [comment]
And this is our issue because of what? There is no other item transport knowm with the same issue.

**Comment by Andre-Maartens** [comment]
just letting you know.. don't know why it happens just letting both parties know of the issue

**Comment by ken2812221** [comment]
I think it's a thermal dynamics issue, because ae2 blocks doesn't interact with the chest.

**Comment by Andre-Maartens** [comment]
all i want is for algorithm or someone from ae to speak with rwtema about this because i tested it with enderio etc and both thermal dynamics and ae2 is glitching but i determined it is the inscriber because td doesn't dupe with interfaces, drives, security terminals, p2p tunnels or busses
