### ISSUE TITLE
Server not starting when disabling channels 

### ISSUE THREAD

**Issue by Deadleh** [AppliedEnergistics/Applied-Energistics-2#934]
I've tried to disable channels on multiple versions of AE2, and the server just won't start when channels are disabled.
Here's a log: http://pastebin.com/5gwRURyA

Using version rv2-beta-8.

**Comment by budgej** [comment]
It should start; it just takes a long time.  Usually 2-3 minutes of that error.  Here's the first issue I saw about it.  #422

**Comment by Deadleh** [comment]
I let it run the other day, after 10 mins still this error, but I will let it run for a bit longer then :)

**Comment by Deadleh** [comment]
Alright, fixed it.
