### ISSUE TITLE
machine-crafting for item-doubling hangs at simulation

### ISSUE THREAD

**Issue by Yadokingu** [AppliedEnergistics/Applied-Energistics-2#937]
In botania you can double certain items, at the cost of a lot of mana, by dropping them in a mana pool. However when I try to automate this with AE, by attaching an interface to an open crate, it never stops simulating.
Note that the open crate is not the problem. Interfacing with it for every other recipe works flawlessly. Seems like AE gets confused by the doubling-recipe.

**Comment by yueh** [comment]
#439
