### ISSUE TITLE
Lag issue hard to track down

### ISSUE THREAD

**Issue by devryb** [AppliedEnergistics/Applied-Energistics-2#939]
How can I find what in my world is causing this?
http://puu.sh/gbsGI/03d4306488.png

**Comment by Cisien** [comment]
Opis may be able to help here

**Comment by Entoarox** [comment]
likely a crafting card upgrade in a interface or export bus somewhere, as the automated crafting in AE2 unfortunately is doing a lot of stuff rather inefficiently (@yueh I think is testing if they can remove the copying that causes the lag without causing problems)

**Comment by yueh** [comment]
Inactive (and very likely an duplicate of all similar reports)
