### ISSUE TITLE
Crash when auto-crafting using inscriber presses

### ISSUE THREAD

**Issue by vinc10** [AppliedEnergistics/Applied-Energistics-2#941]
I get [this](http://pastebin.com/76JU3GgB) "error(?)" when trying to do [this](http://imgur.com/ij0PgXQ) crafting operation (yes, i've tweaked recipes). It's not a crash, and the log doesn't really help. 

Playing FTB infinity 1.2.0 with Iguana tweaks and ModTweaker added. Tweaked Big Reactors fuel usage and disabled channels for AE2.

After selecting how many of a certain circuit (happens with all of them using similar recipes) i want, it throws me out of the terminal and prints the error in chat and log.

You can try reproducing it using [this](http://pastebin.com/tZM6swmq) Minetweaker and Modtweaker scipt.
Running singleplayer.

Using AE2 rv2-beta8  .

**Comment by yueh** [comment]
I can only recommend to try it without these recipes and if you need different recipes, use our [custom recipes](http://ae2.ae-mod.info/Custom-Recipes/).
Otherwise report it to the author of the script, as I am suspecting there is something wrong with it.

**Comment by vinc10** [comment]
Did not know about that feature. Thanks!
