### ISSUE TITLE
AE2 BC Builder Integration

### ISSUE THREAD

**Issue by Bestadd** [AppliedEnergistics/Applied-Energistics-2#942]
So last night I was working on a funky locomotion miner using annihilation planes (inspired by DW20) The base of this build (bottom two layers, top layer of frame blocks and the bottom being AE2 cables, interfaces, storage bus and annihilation planes).  Just getting two rows of the 18 rows done took me a while so I thought lets create a BC blue print and then use the path markers to let the builder build the remaining rows.  Sadly the builder wont place AE2 cables or parts.  As a low priority future enhancement would it be possible to get AE2 to work with the BC Builder.  

I'm just a user, so this may be a BC problem.  In which case let me know and I'll ask the BC devs. 

This would also be amazing for building SSD or extending them.

Just a thought I wanted to through out as I know there is already some integration with AE2 and BC when it comes to BC pipes.  

However, just in case this actually should have worked and is a config option or mod interaction problem I was in single player FTB Infinity 1.0.2

**Comment by AlgorithmX2** [comment]
As far as I know AE2 already fully supports the Builder, unless something has changed with its API, or a bug was introduced.

**Comment by yueh** [comment]
There was a major change in the API with 6.3 in general, so I would expect that the Builder has probably changed too. But I am not sure, if we can migrate everything. If I remember correctly, there was no way through the API to support BC Facades as currently with <6.3.

**Comment by thatsIch** [comment]
I think it is fixed, but I have no clue how the builder works, so somebody needs to test this.

**Comment by Bestadd** [comment]
@thatslch, since I'm the one who requested it it makes since I should test
it.  I'm not setup at all for Java development (all of my work currently is
PHP and C#) and have not been for quite a few years, would it be possible
for you to produce a build?

On Mon, Mar 9, 2015 at 5:14 AM, thatsIch <notifications@github.com> wrote:

> I think it is fixed, but I have no clue how the builder works, so somebody
> needs to test this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/942#issuecomment-77842820>
> .
>



-- 
Ross Lanes

**Comment by thatsIch** [comment]
The build is produced by TeamCity, just download it from there. 
The build server is always linked to each build

go to the PR https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/992
and click the green hook next to the commit http://puu.sh/gubHU/d63696fe80.png

**Comment by Bestadd** [comment]
@thatsIch may take me several days to test.  However, I'll report back on what I find as I find it by updating this comment.  My plan is to test this build with the specified version of forge and BC in an isolated MC instance both SP and Server.  If that all goes well I'll try updating the FRB infinity and DW20 packs and see if there are any problems there.

**Comment by Bestadd** [comment]
@thatsIch it works in both single player and server with BC and AE2 only.  When I creating this issue I did not expect it to be fixed for a few months, the AE2 team is truly amazing, thank you.

**Comment by thatsIch** [comment]
tbh the fix was already there a few month ago, but I kinda wanted to improve the usage of the new BC API, but sadly its still restricting us on its usage, so we pushed for the fix first before working on enhancements.
