### ISSUE TITLE
AE FrameQuarry

### ISSUE THREAD

**Issue by evenas98** [AppliedEnergistics/Applied-Energistics-2#943]
i was experiencing lag and breaking multiple blocks at the same time took very long after updating from Beta 7 to 8 and i think it's because you removed the buffer from annihilation plane! downgrading to beta 7 fixes it.

**Comment by yueh** [comment]
[Profile it.](http://ae-mod.info/Profiling/)

In general it mostly acts the same as before. The Plane will still be locked for a period of time. But instead of breaking the block and using the buffer to lock it (and try to flush the buffer every couple of ticks), now it test if it can store some items before breaking the block and if not, lock the plane for about 6 seconds until it tries again.

**Comment by evenas98** [comment]
well, i use 2 16k storage discs and both of them are not full, i can send you the world, it's a deep dark world (extra utilities) and you can look at it yourself, because i don't understand that profiling thing

**Comment by evenas98** [comment]
using 2 16k discs and both are not full, going to try profiling :) its like it only breaks 1 block a second instead off all blocks

**Comment by evenas98** [comment]
https://www.dropbox.com/s/k83s572fjjxquds/FrameQuarry.nps?dl=0

**Comment by evenas98** [comment]
there you go!

**Comment by evenas98** [comment]
and there is a computer on the quarry but its not running anything

**Comment by evenas98** [comment]
can send picture! :)

**Comment by evenas98** [comment]
![2015-02-26_19 46 19](https://cloud.githubusercontent.com/assets/6554873/6399024/2fb1a40e-bdf0-11e4-8d19-a2a069291948.png)

**Comment by evenas98** [comment]
and the bottom is the same as the front

**Comment by evenas98** [comment]
works completly fine on beta 7!

**Comment by yueh** [comment]
Is this related to that [reddit post](http://www.reddit.com/r/feedthebeast/comments/2x7zik/dw_104_trouble_with_ae2_tunnel_bore_since_update/)?

**Comment by evenas98** [comment]
yes

**Comment by evenas98** [comment]
bit im using a drive with storage drives

**Comment by evenas98** [comment]
but i think maybe it resets its information when the frame moves, and waits until it gets ticked

**Comment by evenas98** [comment]
talking about the annihilation plane

**Comment by evenas98** [comment]
or something along that line

**Comment by enkido** [comment]
Hello,
i dont want to hijack this thread, but  i think i got the same problem.
I have built an annihilation plane(32) powered cobble gen, with some molecular assembly chambers in single pattern mode attached to it., to compress the cobblestone
The attached picture is from rv7,

I observed the following behaviour:
On rv8:
  * the planes seems to sequentially break the stone
  * the assembly chamber has a big lag, crafts every couple of minutes, the stone piles up in the system
  * the frame rate drops from 60 to 20 fps, tps is about 5ms
  * the me controller looses power every now and then and the whole network goes dark for 5 seconds, the attached battery's are fully charged 

On rv7:
* the planes seems to break the stone simultaneously
* the frame rate drops from 60 to 48 fps, tps is about 5ms
* the assembly chamber keeps up with generated stone, none gets stored
  
![2015-02-26_21 17 45](https://cloud.githubusercontent.com/assets/6398971/6401296/aabfb21c-bdff-11e4-8b47-1ddba7e29d1a.png)

**Comment by evenas98** [comment]
yes, that is a good description of the issue!

**Comment by evenas98** [comment]
but mine doesn't loose power and i don't have autocrafting :)

**Comment by evenas98** [comment]
and a tip to you! use extra utilities transfer node with world interaction upgrades, MUCH more compact and lagg less

**Comment by evenas98** [comment]
1 world interaction upgrade per cobble 1 = 1 cobble, 64(max) = 64 cobbble a sec

**Comment by yueh** [comment]
There is an edit button, please use it...

**Comment by yueh** [comment]
@enkido Could you please test [this build](http://ci.tsr.me/repository/download/AppliedEnergistics_PullRequests/1092:id/appliedenergistics2-rv2-alpha-pr947.jar) (If it asks for a login, there is a link for a guest login below)

**Comment by enkido** [comment]
@yueh In case of my cobble gen this version behaves like the rv7, the crafting keeps up, no slow down noticeable and i haven't noticed any other problems
flawless :), thanks

**Comment by yueh** [comment]
Completely prevent a FPS drop is honestly not really possible, that is just the usual issue with massive amounts of block updates in minecraft.
I have tested it with 224 formation + annihilation planes cycling cobble stone around. Which technically places and removes 224 cobblestone every 1 or 2 ticks and obliterates the FPS doing so.
A quarry is probably active every few seconds, so it will shortly drop some frames, but not that massive.

**Comment by evenas98** [comment]
Going to test that build with my quarry now!

**Comment by Cisien** [comment]
Add some energy cells to that build to help speed up the network reforming after a move

**Comment by evenas98** [comment]
i have a dense energy cell :)
