### ISSUE TITLE
Outdated BuildCraft integration

### ISSUE THREAD

**Issue by zlainsama** [AppliedEnergistics/Applied-Energistics-2#945]
I had a serious crash regarding AE2 interacting with BC pipes, I couldn't restart the server without deleting some contents from the save data.

I found out that:
BuildCraft has changed it's TileGenericPipe code, there is no 'hasPlug' but 'hasBlockingPluggable'.

**Comment by zlainsama** [comment]
I couldn't reproduce the crash, but I think i should report the outdated BC integration to AE2.

**Comment by yueh** [comment]
#743
