### ISSUE TITLE
Crash with new ic2 damage items

### ISSUE THREAD

**Issue by jznomoney** [AppliedEnergistics/Applied-Energistics-2#946]
I am using the newest version of ic2 industrialcraft-2-2.2.684-experimental.jar and I was inserting a newer item iron turning bank that is created in a turning table, which I believe adds damage to the iron turning bank to use with certain recipes in ic2. When placing the iron turning bank configured to make a laser into a ae2 terminal I get a crash that references logistics pipes. Here is the log from it.  Not sure if it's an ae2 issue or logistics pipes.

http://pastebin.com/CNJiKmNG

**Comment by yueh** [comment]
Very likely just logistic pipes.
