### ISSUE TITLE
CPUCluster Crash

### ISSUE THREAD

**Issue by TerdyTheTerd** [AppliedEnergistics/Applied-Energistics-2#948]
http://pastebin.com/AHy8E4wu Crash Report

Hello, I'm not sure if this bug is a known bug, or if it a local problem with my server due to other mods installed, but what happened was I was setting up my ME system to autocraft strongboxes for deep storage units, I wanted to test it thus far and when i requested it to craft 16 of the strongboxes it crashes the server, the area is now corrupt as when I restart the server it crashes as soon as a player joins that area. Not a huge problem but just wanted to post it incase it is a bug with AE2

**Comment by Cisien** [comment]
I would start with that eureka mod. AE has no issue crafting strong boxes
