### ISSUE TITLE
Subnetwork no longer working corretly

### ISSUE THREAD

**Issue by charles7926** [AppliedEnergistics/Applied-Energistics-2#950]
I had a subnetwork in place to do a blacklist on an import bus (import bus -> Storage bus w/ inverter card -> interface).  it worked fine with rv2 beta 4 but after I updated to beta 8 it stopped working - nothing would import.

**Comment by yueh** [comment]
Cannot reproduce.

**Comment by thatsIch** [comment]
need more info, meanwhile closed
