### ISSUE TITLE
IC2 iron turning blank terminal issue

### ISSUE THREAD

**Issue by jznomoney** [AppliedEnergistics/Applied-Energistics-2#951]
When I place a newer item added in ic2 into an ae2 terminal I sometimes cannot get the item back out.  The item is called iron turning blank.  When I click on it in the terminal sometimes nothing happens and it gets trapped in the terminal storage.

**Comment by waucka** [comment]
Same here.  I'm using the FTB Infinity pack.  I put an iron turning blank (item id 4108:349525) in my AE system, and now nothing happens when I click, shift-click, right-click, or shift-right-click on it.

**Comment by waucka** [comment]
I can remove the turning blank if I remove and reinsert ANY storage cell (even a completely empty one).

**Comment by Cisien** [comment]
Please raise this issue with the ic2 team. AE doesn't have this issue with any other item in existence, and ae2 doesn't have any special support for ic2 items

**Comment by waucka** [comment]
I'm not overly familiar with how items work in Minecraft, but it seems to me that no item should need to have support for any particular storage mechanism.  It seemed more likely to me that AE2 was choking on it, possibly due to that crazy damage value.  Whatever; I'll report an ic2 bug.

**Comment by StrangeWill** [comment]
@waucka Got a link to the IC2 bug report? Same issue here, except playing with storage cells still doesn't let me get it back out.

**Comment by waucka** [comment]
@StrangeWill Sorry, I never got around to it.

**Comment by torndar** [comment]
As another workaround I was able to remove it by putting the cell in an ME Chest

**Comment by lixo03** [comment]
You can get the item via an export bus
