### ISSUE TITLE
Storage bus whitelist is partially ignored

### ISSUE THREAD

**Issue by Zaflis** [AppliedEnergistics/Applied-Energistics-2#953]
Expected behavior is that if storage bus has even 1 item slot set for specific item for whitelist, it will only store that item. What i see is that it stores all possible items in chest with this storage bus.

Workaround is that i fill ALL slots with any storable item, then nothing else goes in. So don't leave any blanks if you want to whitelist.
UPDATE: I was wrong, this workaround doesn't seem to work either. Or.. it works for chests but not ProjectE Condenser or trash can. So another workaround is using item pipe of any kind to transfer from chest to trashcan.

I used this for "store" excess seeds in trashcan until i realized what was happening... When it works, it's immensely more convenient than export bus+level emitter for every item type.

**Comment by Zaflis** [comment]
Also changing the storage bus filter may not always update immediately. I save the settings in memory card, replace the storage bus and load settings. Filter update done.

**Comment by yueh** [comment]
Cannot reproduce.

**Comment by Zaflis** [comment]
When i try it in flat test world (with same modpack and configs), neither can i. There's gotta be some reason it happens in my main base. At the time of testing it i propably had alot of crafting card operations going? Could network stress cause some information getting lost?

Here's network device usage if it matters: https://www.dropbox.com/s/iropbv9czgtklyg/AE2_storagebus_related.jpg?dl=0
I have disabled channels in config, so there's no ME controller or smart cables.

**Comment by yueh** [comment]
If it is not possible to reproduce it in a fresh world/different network, then in nearly all cases it is an issue with the network layout.

**Comment by Zaflis** [comment]
There's not even any P2P tunnels, but all is wired solid and chunkloaded. Only subnetwork that exists autocrafts pure crystals with formation plane. Main network has ME interface with crafting patterns connected to a ME interface of it.

**Comment by thatsIch** [comment]
Do you per chance use the Storage Bus on something like a DSU or so?

**Comment by Zaflis** [comment]
It was to Iron chest.

**Comment by thatsIch** [comment]
And just to rid it out, which version are you using ^^

**Comment by Zaflis** [comment]
rv2-beta8

**Comment by Zaflis** [comment]
Caught on tape :p
https://www.youtube.com/watch?v=l7dfCBb7PoE
Filter is set only for stairs but it's still sending stone in. Also, i am playing it on dedicated server on localhost. Maybe it's miscommunication between server<->client about filters and priorities?

I played around it randomly and got it even state where if its storage priority was -2000 (minus two thousand), it was using it as primary storage for all incoming items. It's difficult to reproduce so i cut video there with what i could do reliably.

**Comment by yueh** [comment]
The video is completely different to the issue description. Temporarly filtering the other items was never mentioned. But maybe something to start debugging.

**Comment by thatsIch** [comment]
Might be a thing, since stone is already in the chest, that it tries to fill it up,
but yea, initial description and video are 2 totally different things

**Comment by Zaflis** [comment]
Not entirely different, there's weird behavior with storage bus that i don't understand. I just did the test case again as in the video and relogged to server. The storage bus filter was still showing only stairs, and when i emptied the chest it was sending more stone in. So there's something more into it in the internals of the mod. Client does see the filter and priority correctly.

**Comment by yueh** [comment]
It is entirely different. The two omitted details (priority&changed filter) completely change it.

Know it is not about filtering not working, but the filter not correctly updating.
This could for example happen because of a race conditon always putting stone into the chest before the filter gets updated, resulting in stone still being whitelisted, as it is contained inside the inventory.
Or something related to the changed priority being ignored and only the default priority filters are cleared correctly.

**Comment by yueh** [comment]
Also cannot reproduce it with different priorities and changing the configuration on the fly.
It will also never look at the inventory to whitelist anything

In case the throughput should be important, the test did transfer 2k stone/tick.
