### ISSUE TITLE
Can't craft

### ISSUE THREAD

**Issue by evenas98** [AppliedEnergistics/Applied-Energistics-2#954]
![2015-02-28_05 08 29](https://cloud.githubusercontent.com/assets/6554873/6424898/f81ba490-bf0c-11e4-8f13-d7429a5c5ac0.png)
![2015-02-28_05 20 14](https://cloud.githubusercontent.com/assets/6554873/6424899/f81d7e00-bf0c-11e4-9280-e92759c9f634.png)
![2015-02-28_05 43 55](https://cloud.githubusercontent.com/assets/6554873/6424900/f8228332-bf0c-11e4-875f-5a2578f203a2.png)
i need to close, open, close, open, close, open until i  CAN craft, and yes SSP, i have avaliable CPU's and i have all items required

**Comment by evenas98** [comment]
Network has 2 dense energy cells, loads of power.

**Comment by evenas98** [comment]
and this
![2015-02-28_05 50 47](https://cloud.githubusercontent.com/assets/6554873/6424918/c5bf22aa-bf0d-11e4-8170-6d5cfd4d56d6.png)

**Comment by evenas98** [comment]
doesn't show all my items, closing gui and opening, and all items shows

**Comment by evenas98** [comment]
Using Beta 7 because of Annhiliaton plane bug

**Comment by thatsIch** [comment]
Do you have per chance for a result multiple recipes?

**Comment by evenas98** [comment]
i don't understand

**Comment by thatsIch** [comment]
Are you using multiple recipes for 1 single result like
8 oak > 1 chest
8 spruce > 1 chest

**Comment by evenas98** [comment]
i don't think so, pretty sure i only have one recipe for 1 thing

**Comment by thatsIch** [comment]
well, I need more information

please provide a modpack which cuts out as much as possible to reduce the overall load time and download time (cut out not needed dimensions, mods etc)

**Comment by vgamesx1** [comment]
@evenas98 
Do you have any storage buses connected to a barrel or a similar storage container? 
If so try removing it.

**Comment by evenas98** [comment]
I can try, but right now i am a little burned out on minecraft, so i will respond when i start playing again :)

**Comment by thatsIch** [comment]
Inactivity
