### ISSUE TITLE
Terminal turning off for no apparent reason

### ISSUE THREAD

**Issue by notchriss** [AppliedEnergistics/Applied-Energistics-2#957]
Sometimes terminal just goes offline for no apparent reason. I haven't discovered the system behind "sometimes" unfortunately. It's not the unloaded chunk, since the other terminal placed very close is always working. And it's not the channels stuff, nor the lack of energy, it just goes offline. When I restart the server, terminal is back up. 

Terminal is connected to a controller. I am using Bevo pack v. bpt12

**Comment by Zaflis** [comment]
Since the most relevant reason would be lack of energy, you might need to prove it a bit. Can you take a screenshot or document power values with Network tool? Do you have any spatial blocks?

**Comment by notchriss** [comment]
Sorry I completely forgot I posted here. I figured the bug already, it's related to Dense ME Conduit from Ender IO mod I used. You can connect this dense conduit directly to the terminal or any other AE2 device, but if you do so, all sorts of weird bugs follow, including this one. Once I rewired everything the way it's supposed to be, i.e. connecting only normal ME Conduit or real ME Cable to directly to devices, everything works now. Sorry for troubling you!
