### ISSUE TITLE
"Can't keep up" server messages. Believed to be AE's doing.

### ISSUE THREAD

**Issue by Loothor** [AppliedEnergistics/Applied-Energistics-2#959]
Hi all,

It may or may not be AE's doing, as I am not 100% sure how to read visualVM. 

My network:
I am using an enderchest that is accepting input from multiple ender quarries. There is a single point where 4 import busses with acceleration cards are importing into a storage bus | interface to the main network. (allows me to keep certain things in the chest, such as a linking book or certain tool)

From the storage, there are multiple P2P tunnels going to separate parts of the network for processing. 

I would be more than happy to zip up my world and mods folders if anyone would like to see if they experience the same thing.

Please see the VisualVM attachment:
https://www.dropbox.com/s/cz6wv6gi5tntwhf/Loothor%20Server%20Lag.nps?dl=0

**Comment by Loothor** [comment]
Anything else that I can upload to help troubleshoot this issue? (This one especially lags the server to unplayable.)

**Comment by Entoarox** [comment]
Seems to be that the storage update is causing the issue, probably because of the known problem with having to copy a lot of NBT data, you might want to separate your mining & processing network from your main storage network, that should at the least decrease the lag, as your main network (the one likely to be heavy on NBT items) will need to be updated less often.

**Comment by Loothor** [comment]
Thanks for the info Entoarox. We may go ahead and do that. Hopefully there is something the devs can do about speeding up the process, but maybe it is just the nature of the NBT size * amount.

**Comment by Entoarox** [comment]
they are looking into it, but removing the need to copy the NBT tags comes with issues of its own, so lets just collectively hope that those issues can be fixed and the lag removed!

**Comment by yueh** [comment]
Except that is in no way related to NBT at all.

**Comment by Entoarox** [comment]
huh, not? but why else would updating the storage take so long? (or did I misread what was taking so much time that badly?)

**Comment by Loothor** [comment]
Ento - thanks for the info though. We removed NBT stuff out of the inventory and it appears to be much faster. Quarries are offline for now so I cant tell you if it will start spamming the server with the messages again when I turn it back on. So, even though yueh is saying its not NBT related, it still helps. It also helps my other issue (that was closed and blamed on Mekanism) with crafting in the crafting terminal. Instead of 15+ seconds to craft a stack of iron from iron nuggets, it is now 5 seconds.

**Comment by thatsIch** [comment]
the profile is not available anymore :(

**Comment by yueh** [comment]
It is the usual issue with the scaling of a NavigableMap. it mostly overlaps with #853, even if not crafting related. #987 should also improve it.

A simple way to reproduce it, is using the debug ItemGenerator and attach 6 fully upgraded import buses. It should need about 14-16 filled drives (1k are enough) to store every generated type. It should generate about 7k items (vanilla + ae2)

I am under the impression, that a good storage design improves it (tree structure for example). Compared to just putting P2P down everywhere and have a huge network.
But it is hard to provide a reproduceable test. Mostly as the itemgenerator will continue to produce. So it is not really possible to profile a single cycle.
