### ISSUE TITLE
Adaptable crafting orders

### ISSUE THREAD

**Issue by AlgorithmX2** [AppliedEnergistics/Applied-Energistics-2#96]
If you put a crafting card in an export bus with 2 acceleration cards it will order crafting of 32 items at a time, but if you have only materials for 30 of said items if wont craft at all. I use acceleration cards as this items are used in other recepies and they take a while to craft so I make bigger orders and have a supply for next time they are needed. It would be cool if it would craft 30 instead of 32.
Maybe when you check if order is valid(there are enough materials for it) calculate how many it can craft and craft that many instead.

Originally Posted by auboli77

This issue was migrated; For original details see http://ae-mod.info/Tracker/0987/

**Comment by EvulOne** [comment]
This is still an open ticket, and I ran into this same issue today.

Using the current version of the FTB Infinity Evolved pack.
Current AE Version: rv3-beta-5
Current Forge Version: (Forge Mod Loader version?) 7.10.99.99

My example setup:
http://imgur.com/a/uYtpE

Adding enough materials to craft 32, or even a stack of the product, lets it run again.  Base cause of issue seems to be that acceleration cards make the system ONLY craft in larger batches; it won't attempt to craft say, 2 of an item if it has 2 or 3 acceleration cards in it.
