### ISSUE TITLE
P2P-Tunnels don't seem to work correctly

### ISSUE THREAD

**Issue by XFactHD** [AppliedEnergistics/Applied-Energistics-2#960]
I have 28 drives connected to my controller over a p2p-tunnel. They are placed 4 blocks high and in a 7 blocks long row. Below the drives is a dense cable. The problem is that only the first 7 are powered and using a channel.
The same problem occurs in my autocrafting area. I place 8 interfaces in a row, connect them with a piece of glass cable to a dense cable which than goes to a p2p-tunnel. On the piece of dense cable, where the glass cable connects, waila says that I am only using 7 channels (on that piece of dense cable I also connect a rf-p2p-tunnel and another interface on a dropper. When I look into the interface terminal I can only see 5 of the above mentioned interfaces and the Interface on the dropper and the rf-p2p-tunnel is also working. The dense cable directly on the p2p-tunnel says 8 channels used in waila.

I can't provide screenshots for now, because I am not at my computer, but tomorrow I will be able to upload some.

AE2-version: rv2-beta 8

Forge: I don't know, the modpack is DW20 with many more mods and some original mods updated.

PS: Sorry for my bad English, I am German.

Edit: Actually I have 5 rows with each 7 dense cables for the same purpose: to build a row of drives 7 blocks long and 4 blocks high. The 6 p2p tunnels I need for this build are connected by glass cable (which should be sufficient) and then I used a memory card on them. The p2p-input-tunnel is placed directly on the controller. All p2p-subnetworks are powered over glass fibre.

**Comment by XFactHD** [comment]
Actually I have 5 rows of each 7 dense cables for the same purpose: to build a row of drives 7 blocks long and 4 blocks high. The 6 p2p tunnels I need for this build are connected by glass cable (which should be sufficient) and then I used a memory card on them.

**Comment by mindforger** [comment]
AFAIK you can only couple a pair of p2p tunnels, not 1:n like the other tunnels

p2p -> peer to peer is always 1:1

**Comment by XFactHD** [comment]
No, it's 1:8 because you can only place them on a glass, covered ore smart cable.
If I place drives on the second row I have the same problem on this row but it doesn't effect the first row.

**Comment by Cisien** [comment]
Your issue sounds like pathing, make sure there is only 1 path per group of 8 devices. Adjacent blocks will be considered in pathing and my end up being preferred instead of a cable with free channels.

Also, all devices that share the same p2p frequency will share channels. For example, if you have 27 drives on one leg of the p2p, and 8 assemblers on the other, you will be over the channel limit by 3.

**Comment by XFactHD** [comment]
The 28 drives are on a path directly to the controller. If I place a row of 7 and 4 blocks high, the piece of dense cable directly on the p2p-tunnel says 14 channels on waila and only in those 14 can be used to read storage disks. When I then use the networking tool it displays the hole 28 drives and not just 14. If I only stack the drives 3 blocks high only 7 drives are reading disks and using a channel and the networking tool says the same as above mentioned.

In my setup I have one p2p-tunnel as input and 5 p2p-tunnels as output to connect the above mentioned 28 drives to each one of them.

The setup looks more or less like this:

 D    D.   D.  D.   D.  D    D
 D.   D.   D.  D.   D.  D.   D
 D.   D.   D.  D.   D.  D.   D
 D.   D.   D.  D.   D.  D.   D
DC DC DC DC DC DC DC
P2P

D=Drive
DC=Dense Cable
P2P=p2p-tunnel
The dots and the spaces have nothing to do with the setup, they are only for the purpose of readability.

**Comment by Cisien** [comment]
The drives are pathfinding the shortest route to the controller, which takes them through drives that are already full on channels. Seperate each column so no more than 8 drives connect to other drives

**Comment by XFactHD** [comment]
I solved the problem in a different way. I'll close the issue now.
