### ISSUE TITLE
Crafting system look

### ISSUE THREAD

**Issue by gixbit** [AppliedEnergistics/Applied-Energistics-2#961]
I like how powerful the new system for crafting is. But I would like it better if instead of the interfaces some kind of structure like the chambers pre1.7 were used with the assembler. The 9 max per interface makes it hard to organize and its incredibly ugly to deal with. Kinda just make patterns and throw it in and forget and hope you never have to find a pattern.

**Comment by yueh** [comment]
#393, #884
