### ISSUE TITLE
Auto-Crating "Simulation" 

### ISSUE THREAD

**Issue by DauntlessTris** [AppliedEnergistics/Applied-Energistics-2#962]
I know this is a big issue, but I just want a post that doesn't talk about it, because there are heaps of those.

I just want to know if this "Simulation" when trying to auto-craft items, is fixed in a more recent version of AE2. Because I like to use Deep Storages to store my massive amounts of Cobble, Iron, Gold, etc. But I keep getting stuck. (Storage Buses)

Is this fixed in a later version?

Thanks a bunch in advance.
Tris~

**Comment by thatsIch** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/682#issuecomment-68874043

related to this?

**Comment by Endder83** [comment]
I'm using FTB infinity (local) and still geting the same problem =/
