### ISSUE TITLE
[Config Request] Disabling surface meteor spawns

### ISSUE THREAD

**Issue by BarbasTheDog** [AppliedEnergistics/Applied-Energistics-2#965]
First of all, since this is just a config request, I understand that it should take a lower priority than the other 100+ actual issues in this issue tracker.

The idea itself is pretty easy: adding a config option that will disable surface meteor spawns while leaving the spawning of underground ones intact. Too often I find a mountain or an otherwise nice terrain formation that was made ugly by a huge meteor crater.
I know I could just lower the meteor spawning density, but that would force players to travel too far (and generate a lot of terrain) in order to find one and there would be a very high chance that they'd just find a duplicate press.

**Comment by yueh** [comment]
#398
