### ISSUE TITLE
Grindstone Crank Breaks When Right Clicked TE Autonomous Activator

### ISSUE THREAD

**Issue by mikeloeven** [AppliedEnergistics/Applied-Energistics-2#968]
Trying a low tier automation of the grindstone and found that Thermal Expansion's Autonomous Activator will break the crank instantly instead of turning it regardless of the inventory inside the device. It would appear that the issue is in AE rather than Thermal Expansion since the device works on pretty much any device that requires activation by right clicking with the exception of the crank

**Comment by XFactHD** [comment]
This behaviour is intended because it would be an automation with no energy cost.

**Comment by Cisien** [comment]
The autonomous activator actually costs power now :)

Plus I believe that restriction was lifted in ae2.

Make sure the activator is in right click mode, left click mode will break it, also make sure there is something for the grindstone to do. If there are no items in the grindstone and a player attempts to use the crank more than a few times, it will break.

**Comment by yueh** [comment]
As already said, it is an intended behaviour. Any FakePlayer will cause the crank to drop as it is not designed to be automated. Even if the Autonomous Activator requires energy now, it is still a FakePlayer and we cannot detect if it (or any other FakePlayer) is really consuming energy.
