### ISSUE TITLE
Not able to craft full tesseract frame

### ISSUE THREAD

**Issue by XFactHD** [AppliedEnergistics/Applied-Energistics-2#969]
I put all crafting recipes in the interface terminal to craft a tesseract from the basic parts to a finished tesseract. The system successfully crafted the empty tesseract frame, but wasn't able to fill it with resonant ender. To fill the tesseract I placed the interface on the magma crucible and on the right side I placed a filtered ender io item conduit to put the empty tesseract frame in the liquid transposer but nothing happens. The crafting cpu says "stored: 1 tesseract frame, 4 ender pearls" so itt seems to me that the interface can't place the ender pearls in the magma crucible or it can't inject the empty tesseract frame into the item conduit. The question is: Does the interface need something with an inventory that accepts the specific item?

**Comment by Cisien** [comment]
You need to use a buffer chest, the interface never actually holds the empty frame, and since it can't insert the empty frame into the crucible, it stalls.

**Comment by XFactHD** [comment]
Ok, this will become a bit tricky because if very little room, but it will work.
