### ISSUE TITLE
Crafting Status flickering text/lines

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#971]
Especially with fast assemblers, the lines for stored/scheduled/crafting are constantly changing their position, making it actually harder to read as it should.

A fixed position would probably make it easier to read. But then it would not be centered anymore and might look bad.

Maybe a redesign might be an idea?

**Comment by thatsIch** [comment]
Not sure, what you even mean, :octopus: 
which lines?

**Comment by yueh** [comment]
The ones displaying the current amout of stored, crafting or scheduled items.
Especially the crafting one causes it to switch very fast between 1 and 2 (or 2 and 3) lines and multiple times per second, thus also changing their position each time.

**Comment by Horseflywow** [comment]
if i understand im having the same issue its an issue of the CPU # changing constantly 
![this](https://cloud.githubusercontent.com/assets/15030000/10362682/18442e7a-6d7e-11e5-967a-9eff92a4384e.png)
![this2](https://cloud.githubusercontent.com/assets/15030000/10362701/34260032-6d7e-11e5-91eb-d9bb413c5fd3.png)

**Comment by thatsIch** [comment]
I do not think this is the same issue. Why is CPU: #0 constantly changing? To what?

**Comment by Horseflywow** [comment]
whenever you have more than one thing qued to auto-craft the different things constantly jump between different CPUs

**Comment by thatsIch** [comment]
oh thats probably if you have small jobs on the export buses

**Comment by Horseflywow** [comment]
yeah is there anyway to hide those or something? or should i make a request thing?

**Comment by thatsIch** [comment]
request thing?

but I think we have an issue about improving the GUI of that. I guess there could be a GUI option to hide automated crafting processes or something along that line.
