### ISSUE TITLE
ME Formation Plane ignore item config

### ISSUE THREAD

**Issue by Bestadd** [AppliedEnergistics/Applied-Energistics-2#974]
So last nite I was working on my push button spawn and kill wither.  I wanted to do this using AE2 ME Formation Plane; so I set up the 7 in the shape of the wither.  Configured the lower 4 to deploy soul sand and the top 3 to deploy wither skeleton sculls.   When the required 4 soul sand and 3 sculls enter the network via an import buss a scull is deployed where soul sand should go and soul sand gets deployed where sculls should go.  It seems to be rather random. 

I did solve this by having two sub-networks one for the sand and the other for the sculls but even then there seams to be a race condition and on occasion a scull will get deployed to the block space below the formation plane instead of in front of it.  This was solved by some red stone which holds the sculls for a few seconds before they can enter the scull sub network.  

If I'm not just being stupid and doing something obviously wrong, I'll take screen shots/video the tests so dev's can better understand.  

Also, this may be related to the storage bus problem #953, but I could be wrong.

**Comment by TheJulianJES** [comment]
Which version of AE2 are you using?

**Comment by Bestadd** [comment]
Sorry @TheJulianJES, I have been away, rv2-beta-1 is the version included
with the latest release of FTB Infinity which is the pack I used when
having the problem.  If you think this is fixed in a latter build I can try
manually updating the pack.

On Fri, Mar 6, 2015 at 4:38 AM, TheJulianJES <notifications@github.com>
wrote:

> Which version of AE2 are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/974#issuecomment-77552730>
> .
>



-- 
Ross Lanes

**Comment by thatsIch** [comment]
please try it

**Comment by Bestadd** [comment]
@thatsIch, well if I rebuild it exactly the exact same way I get the same behavior; however, it had nothing to do with   the Formation Plane but rather the order in which items entered the network.  

In the auto crafting pattern I had the sculls and sand in the shape of the wither.  This caused the import bus to try and import the sculls first and fail, so it moved onto the sand.  Since all planes had the same priority the plane used was random, if it was the bottom row then a scull would be placed on that block of sole sand from the formation plain two rows above (this is probably MC behavior and not an AE2 problem).

So solution was easy, change the pattern so its 4 soul sand and 2 sculls.  and up the priority of the plains so soul sand is deployed to the middle row first.

I confirmed this is both rv2-beta-1, in PR #942 (server and single player)

**Comment by thatsIch** [comment]
ok, then its just a matter of the problem and not a real bug. 
To create a wither, serialization is needed. You cant parallize it all together.

Thus closing

**Comment by yueh** [comment]
I should also add, that the formation planes can place skulls, reeds and IPlantable 1 block below them.
No idea about the intention behind it, but I would consider it as inconsistency
