### ISSUE TITLE
Having the system maintain a certain level of items

### ISSUE THREAD

**Issue by henriksjostrom** [AppliedEnergistics/Applied-Energistics-2#975]
I often find myself connecting a level emitter to an export bus that is exporting into the system again in order to make the AE system keep a certain number of items in stock. 

This is highly useful for example when the item need to be processed in something that takes time, for example when making an iron armor it is far easier to have a some iron in stock rather than smelting it when the crafting starts, I get my armor significantly faster.

This method however is very ugly, expensive and channel intensive.

Would it be possible to for example add a crafting upgrade to a level monitor in order to have it automatically start crafting the items whenever they drop below a certain amount?

**Comment by Entoarox** [comment]
storage bus on an interface with a crafting upgrade, allows you to keep 9 stacks per interface stocked at all times.

**Comment by henriksjostrom** [comment]
Oh, didn't know that. Very nice works well for small volumes. For Iron and similar resources I generally want stores of roughly 10^3, but for those cases I guess I can use my current solution.

**Comment by Entoarox** [comment]
in those cases it might be more space and design efficient to process your ores into their final form (ingots) at all times, and simply keep a small stock of 'dusts' available in those cases you need them.

**Comment by henriksjostrom** [comment]
Good point
