### ISSUE TITLE
appeng.serivces.VersionChecker (almost) constantly checking for updates.

### ISSUE THREAD

**Issue by Mortvana** [AppliedEnergistics/Applied-Energistics-2#976]
While playing a slightly modified version of ME^4 (Added TD, XR, CC, and BM), as I was experiencing some lag (likely Fluxed Crystals' fault) so I took a CPU profiler snapshot with sfPlayer1's Sampler. In the roughly 10-15 minutes of sampling, appeng.services.VerionChecker.run() and .sleep() had been invoked 140,895 times each. While it may be on its own thread, it still takes up CPU time, and was invoked far too often, 10 times, 5 seconds apart would be smarter in my opinion. It might be that my internet has been unreliable lately, or that my 2 year old A10 is dying, but ever little thing helps.
-Mortvana

**Comment by yueh** [comment]
The VersionChecker will only check every 4 hours, this is even preserved between restarts of the client.
If it is really called that often, then something externally is forcing it to wake up.

**Comment by TheJulianJES** [comment]
I don't think it's necessary to check while the client is running, 4 hours is probaly okay but is this really necessary? Check on startup might be enough since you can't update while the client is already running. ;)

**Comment by thatsIch** [comment]
You can disable the version checker in the configs. We might need to rewrite that anyways, for example by using the Git Tags. If the version checker is able to connect to the internet, it should shut up though and "un-thread" itself.

**Comment by thatsIch** [comment]
ok, the feeds server is down... soo *runs away*

**Comment by thatsIch** [comment]
sadly the API of GitHub only provides latest releases, not pre-releases, so we are stuck parsing the tag or pre-release list. 

I think about shutting the Thread down, if the information can not be retrieved on first try. No reason to hold onto an extra thread, just to post that information to the VersionChecker mod 4h later on.

**Comment by yueh** [comment]
The API is also rate limited to 60 Request/Hour per IP for unauthenticated users.
For most cases this should not be an issue, but we had to deal with it. As some crap ISPs put their users behind a NAT.

The version checker also does only monitor stable releases. So quite contrary to our actual release cycle. So it is mostly useless for now.

**Comment by thatsIch** [comment]
yea, I intended to put it into a config with default set to beta channel. This should be good, anyone who wants can set it to track alpha too

**Comment by TheJulianJES** [comment]
Yep, I was about to write this ;)
