### ISSUE TITLE
Can't use RF with ME Drive

### ISSUE THREAD

**Issue by rune120** [AppliedEnergistics/Applied-Energistics-2#978]
I can't figure out how to power the ME Drive with RF the Mekanism mod. On the AE2 website, it says I can power the machines with RF if I use a P2P Tunnel. I did everything it said to do, but it still doesn't work. But for some reason, I can power a ME Chest directly with RF without having to use a P2P Tunnel.

AE2 rv.beta build 8
Hermitcraft Modsauce 1.0.1.1
Single-player

**Comment by XFactHD** [comment]
The ME chest is in fact a standalone network, but it can also be used in a big network. The ME drive is only for networks with an external terminal and it needs to be powered by a power acceptor.

**Comment by rune120** [comment]
Thanks, that worked!
