### ISSUE TITLE
Make new file ja_JP.lang

### ISSUE THREAD

**Issue by zoutei** [AppliedEnergistics/Applied-Energistics-2#984]
Hello.
I don't have any experience of Open Source Project.
I have had my first pull request on my life yesterday.
I want to make new translations which is ja_JP.lang and translate English to Japanese.
I think it takes a lot of time, but I want to try it.
Please could you tell me which branch shell I create pull request for? (rv2 .rv3 or both)
Thank you.

**Comment by Entoarox** [comment]
the main branch, the rv2 one is where you should make pull requests, rv3 is actually behind rv2 (for reasons unknown to me)

**Comment by thatsIch** [comment]
branch rv2,

feel free to ask, if you have any questions.
