### ISSUE TITLE
Wireless Terminal

### ISSUE THREAD

**Issue by ChrisGamer2311** [AppliedEnergistics/Applied-Energistics-2#985]
The Wireless access terminal cause crash when going into AE Network

**Comment by Entoarox** [comment]
Without an actual crash report there is nothing the dev's can do to fix the issue, so please post a crash report so they can see about fixing it.

**Comment by TheJulianJES** [comment]
Maybe #574? Please post the crash report @ChrisGamer2311, upload it to http://pastebin.com or Gist.
