### ISSUE TITLE
AE2 Terminal Doubling item in interface with storage buses and ME chests

### ISSUE THREAD

**Issue by anarth** [AppliedEnergistics/Applied-Energistics-2#986]
Direwolf20 pack 1.1.1 

The AE2 terminal states there are twice as many items in the system as there should be when using ME chests and Storage buses 

No Storage Bus
![2015-03-08_11 27 45](https://cloud.githubusercontent.com/assets/11374690/6545573/47113ebe-c586-11e4-9174-80e259d8548f.png)

Inside Chest
![2015-03-08_11 28 24](https://cloud.githubusercontent.com/assets/11374690/6545577/4716a688-c586-11e4-859b-b15b1fc696f3.png)

From the Terminal
![2015-03-08_11 27 50](https://cloud.githubusercontent.com/assets/11374690/6545574/47151e76-c586-11e4-8312-b346511d3535.png)

Storage Bus (and power into back) 
![2015-03-08_11 28 20](https://cloud.githubusercontent.com/assets/11374690/6545575/4715c3b2-c586-11e4-9b67-5a08c13eea56.png)

Inside the chest
![2015-03-08_11 28 28](https://cloud.githubusercontent.com/assets/11374690/6545578/471700e2-c586-11e4-8bfb-e9ce1c136f08.png)

From the Terminal
![2015-03-08_11 27 53](https://cloud.githubusercontent.com/assets/11374690/6545576/4716311c-c586-11e4-9d3f-1c22b5725e48.png)

Even with the power cable in the back and no bus, it doesnt double in the terminal.

Note; you can only extract the amount of items you have in actuality (for instance, 2.) then what the terminal says.

**Comment by yueh** [comment]
If you attach an inventory twice to the same network, then it will of course report twice the amount of stored items. This will also happen with vanilla chest or any shared inventory like enderchests (EnderStorage)
