### ISSUE TITLE
 mod appliedenergistics2 (Applied Energistics 2) requires mod versions [Forge@[10.13.2.1230,)] to be available

### ISSUE THREAD

**Issue by Darkness3840** [AppliedEnergistics/Applied-Energistics-2#988]
im not sure what it is, but the console log is below, I appreciate all help, I am running cauldron 1.7.10 for a modded server. 

http://pastebin.com/trACyHq0

**Comment by Parker8283** [comment]
You version of Cauldron is running Forge 10.13.0.1207. You need to use a version of Cauldron that has at lease Forge version 10.13.2.1230.

**Comment by Darkness3840** [comment]
I could not find a cauldron version that runs that. Could anyone help me with that?






On Sun, Mar 8, 2015 at 2:36 PM -0700, "Parker Young" <notifications@github.com> wrote:












You version of Cauldron is running Forge 10.13.0.1207. You need to use a version of Cauldron that has at lease Forge version 10.13.2.1230.

**Comment by Parker8283** [comment]
Considering Cauldron isn't really supported my mod devs, nor is it really supported by the people who originally wrote it (due to many reasons), my best advice is to just drop Cauldron and switch to just standard Forge.

**Comment by Darkness3840** [comment]
I see. Although, do you have any other alternatives, because I would like to run plugins alongside the mods.






On Sun, Mar 8, 2015 at 2:40 PM -0700, "Parker Young" <notifications@github.com> wrote:












Considering Cauldron isn't really supported my mod devs, nor is it really supported by the people who originally wrote it (due to many reasons), my best advice is to just drop Cauldron and switch to just standard Forge.

**Comment by thatsIch** [comment]
There will be Sponge API of Forge for that in the future, not sure how much of it is already working
