### ISSUE TITLE
[Feature] Input/Output summaries per terminal group

### ISSUE THREAD

**Issue by netzgeist** [AppliedEnergistics/Applied-Energistics-2#994]
Problem:

Socialized networks are hard to track. 

Solution:

Implement some kind of community terminal, assignable to a single user. Let the terminal keep track of whatever is put in and out. Store this information somewhere so that the network owner can see and/or display it(Wrench, Computercraft, Information Panels or whatever nbt reading system one may preffer). The terminal needs to be limitable to a single user so each participant can have his own set of community terminals. The network owner should probably be able to override the tracking and use any terminal. 

Scenario:
X people use a network. X1 is lazy, autocrafts what he needs but never fills up the stocks. The network owner looks up the in/out summary of X1, finds that out and can communicate X1 that there is a problem.

**Comment by thatsIch** [comment]
So basically an admin panel,

the idea would generally, you supply a main network and everyone uses their own network. The main network only provides only a specific amount to every sub-network.

Thus, I would reject this idea. Making everything just more complicated than necessary.

**Comment by netzgeist** [comment]
@thatsIch you extended my idea. I was not about creating subnets and limiting supplies in/out them. 

Summary for new blocks:
- Community Terminal: Regular me-terminal. will send log-entries to a "logging-unit" when used. Can be bound to a single choosable player.
- Logging-Unit: Reviecer for log entries send from the same network.

Things to log:
Whatever the Terminal is able to do. Usually Insert Item, Retrieve Item, Craft Item. This way, we can just inhehit from the present terminals, reusing most of the code.

**Comment by yueh** [comment]
I do not see any real reason for it being part of AE2. It is a very narrow usage case and probably only rarely used. Also completely useless for singleplayer.

But the API provides everything to create an ae2 addon for this functionality.
Accessing the information is pretty trivial, so it is mostly about parsing/storing/displaying it.

**Comment by netzgeist** [comment]
I guess you are right, the scenario may not be common. I guess I'll dig into your api then ;). Have a nice week!

**Comment by yueh** [comment]
There is no need for a Community Terminal. Just a Logging Terminal to watch the network it is attached.
So just 1 block/tileentity and the GUI for it.

Look at `IGridNode`/`IGridHost` for the TileEntity being part of the ME network and `IStackWatcherHost` for being notified about changes to the inventory, it does also contain the source (like which player or a machine).

Our IRC channels is probably the better option for providing help in this case.
