### ISSUE TITLE
Energy Acceptor lost its energy

### ISSUE THREAD

**Issue by mezoty** [AppliedEnergistics/Applied-Energistics-2#997]
Energy Acceptor lost its internal energy when is unloaded with chunk where is placed.

**Comment by thatsIch** [comment]
Energy Acceptors should not have any internal energy anymore.

**Comment by mezoty** [comment]
hmm... interesting. Then is only one thing that is directly connected, Crystal Growth Accelerator. But its energy input direction is rotated out, from Energy Acceptor, its status is offline. Energetic loss of TE Energy Cell is 10.000 RF when chunk is again loaded.

**Comment by thatsIch** [comment]
Could you maybe post a Screenshot of your setup and show the chunk border?

**Comment by mezoty** [comment]
![2015-03-11_01 17 35](https://cloud.githubusercontent.com/assets/6764362/6588084/2682d4c4-c78d-11e4-8ff2-391b41e0f109.png)
![2015-03-11_01 18 00](https://cloud.githubusercontent.com/assets/6764362/6588089/31180986-c78d-11e4-9742-4f233b3fc822.png)
![2015-03-11_01 18 22](https://cloud.githubusercontent.com/assets/6764362/6588093/38ca0940-c78d-11e4-876c-77636aced07d.png)

**Comment by thatsIch** [comment]
Can you maybe try another supported power source? (like EU)

**Comment by Cisien** [comment]
Your accelerator is oriented incorrectly. It can only accept power on the sides without the grey grid texture.

**Comment by yueh** [comment]
As people are usually not mentioning the version they are using, is this related to #1005?

**Comment by mezoty** [comment]
"Problem" was detected in version rv2-beta-8 with rv2-beta-9 is it same.

**Comment by thatsIch** [comment]
wonder if the RF api changed or so..

**Comment by yueh** [comment]
Each grid has a small internal buffer (and an acceptor is already a grid).
Without it, it would not really work or at least shut off way more often. But grids are not really persistent things.

Of course we could reduce/remove it, but I am pretty sure most people will find it highly annoying, if the network has a power failure everything you extract a single item.

**Comment by mezoty** [comment]
Please, can somebody test this and confirm or refute my conclusion/observation? Thanks.

**Comment by mezoty** [comment]
With EU is same problem, loss is 512 EU or multiple of them. When is Chunk loader places, were not losses measured.

Setup for EU

![2015-03-12_04 34 07](https://cloud.githubusercontent.com/assets/6764362/6611946/ba86b5c8-c873-11e4-89ef-5312d1097959.png)

**Comment by thatsIch** [comment]
This is pretty annoying to test indev, because of the dependencies all power system mods require indev (which are not shared in public)
