### ISSUE TITLE
Cable parts of add-ons connect differently then regular ae parts

### ISSUE THREAD

**Issue by XFactHD** [AppliedEnergistics/Applied-Energistics-2#999]
This is more a question then an issue, but when you connect whatever part of an add-on to a cable, the connection renders like the edge of a covered cable that goes around a corner, even if you use glass cable. If you attach a regular ae part, it renders the connection like any other corner or "T" connection or whatever you build.

**Comment by yueh** [comment]
You should probably report it to that addon. They are probably reporting the wrong connection type.
